### ISSUE TITLE
Multi-root: Excluded file opens under wrong root

### ISSUE THREAD

**Issue by GoaLitiuM** [microsoft/vscode#95056]
Issue Type: <b>Bug</b>

I have a multi-root project setup in the following way:
- Project folder including all sub folders except subproject1 folder
- Subproject1 folder

When I open up a file located under subproject1 folder, the whole subproject1 folder gets collapsed in the explorer view and the opened file is shown under the main project root folder even though it is supposed to be excluded from it.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.19041

**Comment by GoaLitiuM** [comment]
If I have the main project root folder collapsed and only the subproject1 folder revealed in explorer view, the opened files appear under the subproject1 folder.

**Comment by kdlslyv** [comment]
Yeah, happens here as well even with all extension disabled.

Basically I have a structure with a project root directory, beneath a `client/` and a `server/` directory.
Now whenever I open an file under `client/` or `server/` it shows up in the project root folder too, plus the folder structure of where that file is.

When using `Ctrl+P` to navigate quickly, the explorer drawer annoyingly jumps around as well.

The entry disappears instantly once I close any of the files erroneously showing up there.

**Comment by vennekilde** [comment]
Same issue here

The issue only occurs for folders located in the root project directory, so say you have
`"folders": [{
	"path": "folder/subfolder"
}]` then the folder will not collapse, however it will still be shown in the wrong root

Until this gets resolved, i recommend just commenting out the files.exclude section that excludes folders located in the root, as it is at least usable in this configures, though the folders will be shown twice.

**Comment by kdlslyv** [comment]
I think this issue is erroneously categorized, it clearly results in buggy behavior to me which earlier versions of vscode didn't have.

Should be labelled as a bug.

**Comment by GoaLitiuM** [comment]
Yes, this is a regression, it worked in earlier builds but not after 1.44.0.

**Comment by vennekilde** [comment]
> Until this gets resolved, i recommend just commenting out the files.exclude section that excludes folders located in the root, as it is at least usable in this configures, though the folders will be shown twice.

Correction to my earlier statement.
If you require that your project is split into multiple roots, for things like gopls to work in a go module project, then there is nothing to do outside downgrading to a version < 1.44

**Comment by GoaLitiuM** [comment]
@isidorn Can you correct the issue filing please? This is a bug, not a feature request.

**Comment by isidorn** [comment]
Yes. Just did that. Thanks

**Comment by AndreasBackx** [comment]
Also bumped into this issue. It definitely is a regression as I used it before to work with Go projects that have multiple modules as it is the only workaround to get it to work. Unfortunate that it no longer works. https://github.com/golang/go/issues/32394

I made a repository that can reproduce this behaviour with a recording of it in action: https://github.com/AndreasBackx/vscode-exclude-bug

**Comment by ernestasjuska** [comment]
Yes. This is really annoying when working with deeply nested projects.

![repro](https://user-images.githubusercontent.com/53167314/85835124-2f53f000-b79d-11ea-8915-9723dc51988a.gif)

Version: 1.47.0-insider (user setup)
Commit: 6c235c723cb2d8defb840f732eac620f54aa8b9d
Date: 2020-06-26T06:20:06.931Z (1 hr ago)
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.18363

[expand_collapse.zip](https://github.com/microsoft/vscode/files/4835718/expand_collapse.zip)

**Comment by vennekilde** [comment]
A "workable" solution is to move all your subproject folders into folder under the root project

So if you have a project looking like this
```
./project
  ./subproject1
  ./subproject2
```
Then you can change it to this (remember to update `.vscode/settings.json` & `project.code-workspace` if used)
```
./project
  ./submodules/subproject1
  ./submodules/subproject2
```

Now when opening a file in one of the subprojects, it will not close the subproject folder on you

**Comment by TBBle** [comment]
Isn't ["out-of-scope"](https://github.com/microsoft/vscode/labels/%2Aout-of-scope) the wrong way to close a bug report, according to the 'decision making process' link? That probably should be ["Won't fix"](https://github.com/microsoft/vscode/labels/wont-fix), to make it clear that a regression bug has been decided to be kept, rather than treating it as a feature request that is not in scope.

**Comment by HHK1** [comment]
Observing the exact same issue. 
I looked around in the repo issues, and tried to add files directly as an alternative (https://github.com/microsoft/vscode/issues/45177). I have to say that the number of valid and researched issues marked as "out-of-scope" on the subject of multi-root is worrying. 

More transparency and explanations regarding those issues would be more helpful than just rejecting all those issues. There is a clear lack of support on multi-root workspaces, and it's hard to know wether to invest or not in this tool right now.
