### ISSUE TITLE
Failed to download v.1.44 update

### ISSUE THREAD

**Issue by pakLebah** [microsoft/vscode#95055]
I don’t know where to report this problem so I put it here. I apologize if this is a wrong place, but please solve the problem because I can no longer update my VS Code.

System:

- VSCode Version: 1.43.2
- OS Version: MacOS Mojave

Steps to Reproduce:
1. Click the `Manage` button and choose `Check for Updates…` to download the latest update manually from within VS Code.
2. I wait for a few minutes then an error dialog shows up saying the download failed because of response time out.
3. I've tried to download manually from the VS Code [download page](https://code.visualstudio.com/updates/v1_44) but the page can’t be loaded with also time out error. I couldn’t even open the VS Code website.

I’ve made sure there’s no problem with my internet connection, I can open any other web sites fast and full. I confirm my ISP doesn’t block any VS Code web sites, they also have no reason to do so. I ask some friends of mine, I confirm the problem also occurs on some other internet providers as well, while some other internet providers doesn’t have the problem. 

`traceroute` shows the connection to [code.visualstudio.com](code.visualstudio.com) got stuck at `ae142-0.icr02.by21.ntwk.msn.net (104.44.22.176)` that lead to time out. I think there’s a problem with VS Code site reachability, at least from Indonesia.

Does this issue occur when all extensions are disabled? Yes

**Comment by octref** [comment]
Maybe there's an issue with your ISP. If you go directly to this page and click Mac: https://code.visualstudio.com/updates/v1_44

What happens?

Here's the direct URL: https://az764295.vo.msecnd.net/stable/2aae1f26c72891c399f860409176fe435a154b13/VSCode-darwin-stable.zip

**Comment by pakLebah** [comment]
> Maybe there's an issue with your ISP.

As I said, nothing wrong with my internet connection and ISP. I can open any other web sites fast and full.

> If you go directly to this page and click Mac: https://code.visualstudio.com/updates/v1_44
What happens?

Long time waiting and ending with time out error.

> Here's the direct URL: https://az764295.vo.msecnd.net/stable/2aae1f26c72891c399f860409176fe435a154b13/VSCode-darwin-stable.zip

The same problem as above, time out error.

**Comment by octref** [comment]
Not really sure what I can help with — the `https://az764295.vo.msecnd.net` URL is an Azure CDN and you are having issue connecting to it. It's an Azure issue and there's nothing I can help with.

**Comment by pakLebah** [comment]
Out of nothing and it seems nobody is doing nothing, suddenly it all works again. I think you’re right, @octref… it’s an Azure issue. Well, thank you.
