### ISSUE TITLE
Text is blurry

### ISSUE THREAD

**Issue by bierchendk** [microsoft/vscode#95060]
Issue Type: <b>Bug</b>

In Debug of code, I created a breakpoint and moved the mouse to the variables window, watch and call stack windows which turns some of the menu text blurry.

If I move the cursor back to the code window, It gets clear again.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-cosmosdb|ms-|0.12.2
csharp|ms-|1.21.16
python|ms-|2020.3.71659
azure-account|ms-|0.8.9

</details>

**Comment by nbros** [comment]
I don't know if it's linked but I also noticed that text is blurry in the Terminal view at some heights: making the terminal bigger vertically fixes the blurriness.

To me the first one looks noticeably blurrier:

![image](https://user-images.githubusercontent.com/141089/79221716-9b89ad80-7e56-11ea-8c01-2c8ceec463a0.png)

![image](https://user-images.githubusercontent.com/141089/79221747-a93f3300-7e56-11ea-99cf-9c485b4753ca.png)

**Comment by nbros** [comment]
As indicated in https://github.com/microsoft/vscode/issues/92693#issuecomment-609821863, I tried removing the "window.zoomLevel" setting and it fixed the blurriness in the terminal.
Maybe try and see if it fixes your problem too?

**Comment by Succatash** [comment]
https://gyazo.com/fd08c41128f658a3a867e534a44b2c7c

mine can become really blurry n editing window I have reset zoom and it stays blurry

**Comment by xsrf** [comment]
Hey, I do have issues with blurry text rendering for years now in VSCode and also in MS Terminal.
Today I found out that it is caused by Intel HD Graphics Conservative Morphological Anti-Aliasing (CMAA). The hint in #44168 by @perryizgr8 that `--disable-gpu` solved the issue helped a lot! So I check if it is caused by some 3D graphics / anti-alias options and indeed, it is. If you do have Intel HD Graphics, it can be disabled on the 3D settings panel.

**Comment by Succatash** [comment]
Thanks, I have AMD but I will check if they have something akin to CMAA, I
did a full reboot and haven't had any issues since then
