### ISSUE TITLE
SCM does not respect global gitignore

### ISSUE THREAD

**Issue by wolf99** [microsoft/vscode#95064]
Issue Type: <b>Bug</b>

There is  global gitignore, for which the path is set in the global gitconfig `core.excludesfile`.

The global gitignore has one rule, which is to ignore the `.vscode` directory (and all of its contents, have tried adjusting the rule to `**/.vscode/` with no joy).
I have set the VSCode setting for `search.useGlobalIgnoreFiles` to `true` and restarted the application.

Using git itself at the command line correctly ignores `.vscode/settings.json`.  VS Code SCM does not ignore the same file and still shows it as having changes. Neither the file nor the directory have ever previously been committed in this repository.

![image](https://user-images.githubusercontent.com/281700/79077524-446ec600-7cfa-11ea-888c-acb4862f1a9d.png)

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
overtype|ada|0.2.0
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
todo-tree|Gru|0.0.171
plantuml|jeb|2.13.6
python|ms-|2020.3.71659
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.27.0
material-icon-theme|PKi|4.0.1
java|red|0.59.1
vscode-xml|red|0.11.0
glassit|s-n|0.1.6
code-settings-sync|Sha|3.4.3
vscode-checkstyle|she|1.3.2
code-spell-checker|str|1.8.0
open-in-browser|tec|2.0.0
shellcheck|tim|0.9.0
shell-launcher|Tyr|0.4.1
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2

(3 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
What does `git config --global core.excludesfile` return, if you run it from a Command Prompt?

**Comment by joaomoreno** [comment]
Note that `search.useGlobalIgnoreFiles` is a setting for the Search feature, not SCM.

**Comment by wolf99** [comment]
@joaomoreno per the screenshot in the original post it returns the expected and correct path to the global gitignore file in my windows user directory.

Is there a matching setting I need to set for the SCM do you know?

**Comment by joaomoreno** [comment]
In the screenshot you're executing git from bash.

**Comment by wolf99** [comment]
> In the screenshot you're executing git from bash.

True dat. No doubt no doubt no doubt 😄 .

You have hit the nail squarely on the head there @joaomoreno.
I had thought I had both Windows Git and Bash Git pointing to the same `.gitconfig`.
But that was not the case - nor could it be as the paths contained within would need to be different (e.g. `/mnt/c/...` vs `C:\...`).

With this I have solved this with a simple `git config --global core.excludes file <gitignore-path>` from the Windows command prompt.

Thanks for your help!

**Comment by joaomoreno** [comment]
![no doubt](https://media.giphy.com/media/XAdbHJywVjF5K/giphy.gif)
