### ISSUE TITLE
Account loading does not finish with latest VS Code Insiders

### ISSUE THREAD

**Issue by ayatokura** [microsoft/vscode#95061]
Issue Type: <b>Bug</b>

1. Run Visual Studio Code Insiders.
2. Click Account Icon.
3. It shows "Loading" for 1 hours.  The process seems stuck while loading account status.

[Screenshot]
<img src="https://uefzda.by.files.1drv.com/y4muyhfYor4H_Hd1m8jgX570mwEflIzxsaTuoUp_i-uxSOSEt0B4daM7h1e8y0Ww3-rUAb9mE6qyJWrn1btgsIKiJUTIZ_PG7aeuqJ5AyW5uN5vaSz6xjDqyKGpBTPEqXekcUZuGBxDsL3CLWLzemeiiYYMBTytCnIVmTyExWaF9rw-v1Q-_dMDj4Sq6ftU18aDYqI7heWwXGswiOJWmVebmQ?width=1790&height=1139&cropmode=none">

VS Code version: Code - Insiders 1.45.0-insider (44c5185373d5f209cd6c0b5d29a216fb801da34e, 2020-04-10T18:12:33.780Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU 4415Y @ 1.60GHz (4 x 1608)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (4.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ja|MS-|1.44.2
remote-wsl|ms-|0.44.2

(1 theme extensions excluded)

</details>

**Comment by ayatokura** [comment]
This was reproduced in my macOS environment.  Once this condition occurs, Setting Sync menu does not appear in the Manage gear menu.

バージョン: 1.45.0-insider
コミット: 44c5185373d5f209cd6c0b5d29a216fb801da34e
日付: 2020-04-10T19:43:46.226Z
Electron: 7.2.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

**Comment by RMacfarlane** [comment]
@ayatokura If you close and reopen the menu is it still "Loading..." after you have waited a bit?

**Comment by ayatokura** [comment]
Yes. No matter how many hours have passed the situation does not change.  I tried machine reboot and shutdown, but it didn't help.  If I reinstall and try the operation, the menu will be displayed. However, I get same problem again after I set Settings Sync feature.

**Comment by RMacfarlane** [comment]
Ok, thank you for confirming.

Can you run the command `Developer: Toggle Developer Tools` and report any errors that are in the console? What is in the log if you open the Output panel and select "Account" from the dropdown?

**Comment by ayatokura** [comment]
I have confirmed that it works by updating to the latest version 1.47.0 - Insiders in both Windows and macOS environment.  Thanks.
