### ISSUE TITLE
Command + act as text size increase not zoom

### ISSUE THREAD

**Issue by fishcharlie** [microsoft/vscode#95066]
In almost every text editor `Command +` acts as a way to increase the text size. In VS Code it increases the size of everything. There are a lot more use cases for needing to increase the text size as opposed to increasing the size of everything. For example when presenting code on a projector, it can be useful to hit `Command +` a few times so the audience can see the code easier.

Also in most text editors `Command + 0` acts as a way to reset the text size to normal. In VS Code it looks like this command is `Command + NumberPad 0`, most laptops these days don't have number pads. So that keyboard command is basically useless.

This should really be cleaned up and VS Code should be aligned with every other text editor out there.

**Comment by RMacfarlane** [comment]
@fishcharlie You can change your keybindings so that `Editor Font Zoom In`, `Editor Font Zoom Out` and `Editor Font Zoom Reset` are as you expect them. `Command +` and `Command -` for zoom is standard for many applications, we do not want to change default keybindings that our users now expect to behave a certain way

**Comment by fishcharlie** [comment]
@RMacfarlane 

> You can change your keybindings so that Editor Font Zoom In, Editor Font Zoom Out and Editor Font Zoom Reset are as you expect them.

Thanks!!

> Command + and Command - for zoom is standard for many applications

I'm unaware of any text editor who had the behavior of Command + and Command - acting as a zoom that zooms the entire interface. Would love to hear which applications you refer to. Of course for certain types of applications zoom is the default behavior. But I've never seen that behavior when it comes to text editors.

> we do not want to change default keybindings that our users now expect to behave a certain way

I'm curious if this is based on like surveys taken or feedback from the community, or just personal assumption. It's fine either way. And maybe I'm completely wrong, but I get the feeling most users would prefer default behavior to be text font size as opposed to interface zoom.

I guess my point is that I hope at some point this project can potentially reconsider their stance on being the only text editor (or major text editor) to have a different behavior on this. Of course thanks to your help it's working for me now, but just to help new users I think this would be beneficial to at least reconsider or think about more at some point.

**Comment by fishcharlie** [comment]
Also. One more thing I noticed. When rebinding my key commands to that, if you click on a terminal view and hit Command +, it still increases the text size of the editor. Feels like it should be smart enough to recognize that I last selected the terminal and increase the text size of that as opposed to the editor.
