### ISSUE TITLE
Keyboard shortcuts for switching focus between left & right sides of diff view

### ISSUE THREAD

**Issue by siddharth-krishna** [microsoft/vscode#95068]
It would be great if there was a keyboard shortcut to switch between the left and right sides of a diff view (what opens when you show changes to a file from the source control tab, or when you use the "Compare active file with..." command). I often find myself comparing two files, especially when refactoring, and copying content from the left file to the right one, and without keyboard shortcuts this is tedious as I have to use the mouse every time to switch focus. (If there's an existing command for this I can bind a keyboard shortcut to, that'd be great too!)

Thanks for all the amazing work!

VS Code version 1.44.0 on Windows 10

**Comment by joaomoreno** [comment]
@bpasero A workbench command?

**Comment by bpasero** [comment]
Added new commands: `workbench.action.compareEditor.focusPrimarySide`, `workbench.action.compareEditor.focusSecondarySide` and `workbench.action.compareEditor.focusOtherSide`.

**Comment by bpasero** [comment]
**Verification:** verify the new commands in https://github.com/microsoft/vscode/issues/95068#issuecomment-723842970 work as advertised when a diff editor is open.
