### ISSUE TITLE
Status bar color is not updated

### ISSUE THREAD

**Issue by ant-1** [microsoft/vscode#95063]
Issue Type: <b>Bug</b>

* Install ReUI extensions > status bar color remains "purple"

* Update settings.json file to change statusbar.background (let's say black) and statusbar.foreground (white) > status bar color remains "purple"

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T08:23:56.137Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-all-in-one|yzh|2.8.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
When no folder is open the setting is `statusBar.noFolderBackground`

**Comment by ant-1** [comment]
Thanks @gjsjohnmurray 
Seems to be the right track !

But I still have the purple status bar with the configuration below:

```json
{
    "workbench.colorTheme": "ReUI Default Bordered (react)",
    "workbench.colorCustomizations": {
        "statusBar.noFolderbackground": "#282c34",
        "statusBar.noFolderforeground": "#ddd",
    }
}
```

Do you have an idea of what I am missing ?

**Comment by RMacfarlane** [comment]
@ant-1 Background and foreground need to be capitalized:

```
{
    "workbench.colorTheme": "ReUI Default Bordered (react)",
    "workbench.colorCustomizations": {
        "statusBar.noFolderBackground": "#282c34",
        "statusBar.noFolderForeground": "#ddd",
    }
}
```

**Comment by ant-1** [comment]
My bad, you are totally right !
Thanks @RMacfarlane
