### ISSUE TITLE
install flutter

### ISSUE THREAD

**Issue by mohame-dmansour** [microsoft/vscode#95071]
Issue Type: <b>Feature Request</b>

Unable to open 'Extension: Flutter': An unknown error occurred. Please consult the log for more details..

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 6.3.9600

**Comment by sandy081** [comment]
> Unable to open 'Extension: Flutter': An unknown error occurred. Please consult the log for more details..

Can you please provide to steps to repro and also screen shot of what you are seeing and logs if possible.

**Comment by doctor-mostafa79** [comment]
The same issue happened when I tried to install flutter extension on VS code?!
Any help.
![Screenshot_74](https://user-images.githubusercontent.com/15583026/79792027-875e1880-834e-11ea-815e-a6dc7ede76b4.png)

**Comment by sandy081** [comment]
Does the extension got installed?

Can you please open the log `Toggle Developer Tools` and provide us the console logs?
