### ISSUE TITLE
Cmd+D with newline broken in Insiders

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#95073]
file:
```
line
|line
line
```

Cursor is the pipe. Shift+LeftArrow to select the newline. Cmd+D to select the next newline. 

In Stable: newline is selected.

In Insiders: it isn't.

**Comment by alexdima** [comment]
@JacksonKearl  I cannot reproduce:

![Kapture 2020-04-13 at 21 28 38](https://user-images.githubusercontent.com/5047891/79153239-d09ded80-7dcd-11ea-8d80-af2025f9bae3.gif)

**Comment by JacksonKearl** [comment]
Seems to work fine for me too now.
