### ISSUE TITLE
Info about vscode update

### ISSUE THREAD

**Issue by Pawan243** [microsoft/vscode#95088]
how to update new version of vscode on my machine?

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo such as what version you currently use, and on what platform.

**Comment by RMacfarlane** [comment]
@Pawan243 
<img width="287" alt="Screen Shot 2020-04-13 at 9 02 47 AM" src="https://user-images.githubusercontent.com/3672607/79136290-9f89d280-7d65-11ea-88b8-f74e404f95ad.png">
