### ISSUE TITLE
code-insiders 1.4.0 doesn't have 1.3.1's overflow icon when too many tabs are opened

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#9508]
- VSCode Version: Code - Insiders 1.4.0-insider (f4780e67933164a2289b86f2c279aaa05fda672f, 2016-07-19T05:07:05.876Z)
- OS Version: Windows_NT ia32 10.0.14390

Steps to Reproduce:

1. Open VS Code Insiders 1.4.0
2. Open a bunch of tabs to try to activate the overflow indicator
3. Observe that the indicator is not present in 1.4.0 as it was in 1.3.1

1.4.0:
![image](https://cloud.githubusercontent.com/assets/494055/16971740/2002220a-4ddb-11e6-8306-636a1d355f42.png)

1.3.1:
![image](https://cloud.githubusercontent.com/assets/494055/16971767/5af90306-4ddb-11e6-8b2c-9bfa4eac0083.png)

**Comment by kieferrm** [comment]
@dilijev please see #9159 for the reasoning behind the change.

@bpasero FYI.

**Comment by bpasero** [comment]
We are still looking into tabs UX and might find a better way to restore this functionality without having a dedicated action.
