### ISSUE TITLE
quick switch markdown preview theme / or better rendering for pictures with much transparent area.

### ISSUE THREAD

**Issue by eromoe** [microsoft/vscode#95087]
For example , there is a site, convert latex into picture so that easy to share in different sites. 
But the pictures are ugly under dark theme : 
![image](https://user-images.githubusercontent.com/3938751/79096302-53538800-7d8f-11ea-890f-512927c1adf1.png)

Can we add a light swith for preview pane ?

**Comment by mjbvz** [comment]
This is caused by your latex renderer producing images with bad transparency

**Comment by eromoe** [comment]
I know,  so I ask a feature for quick changing preview pane theme .
