### ISSUE TITLE
Unable to install VScode 1.44 in Mac

### ISSUE THREAD

**Issue by JijoBose** [microsoft/vscode#95085]
- VSCode Version: 1.44
- OS Version: MacOS Mojave 10.14.6

Steps to Reproduce:

1. Download the stable build from https://code.visualstudio.com/
2. Extract the zip file

<img width="382" alt="Screen Shot 2020-04-13 at 10 39 17 AM" src="https://user-images.githubusercontent.com/13100108/79093927-68bab900-7d73-11ea-82ce-acd863da8283.png">

**Comment by RMacfarlane** [comment]
@JijoBose Are you using the antivirus software Quick Heal? We are seeing reports of it removing a needed file: https://github.com/microsoft/vscode/issues/94858#issuecomment-612010439

**Comment by JijoBose** [comment]
> @JijoBose Are you using the antivirus software Quick Heal? We are seeing reports of it removing a needed file: https://github.com/microsoft/vscode/issues/94858#issuecomment-612010439

Yes I am using Quick Heal.
Thanks.. I'll disable and try again

**Comment by RMacfarlane** [comment]
@JijoBose You may still need to follow part of the directions in https://github.com/microsoft/vscode/issues/94858#issuecomment-612010439 to restore the deleted file
