### ISSUE TITLE
f12 can't got to definition but show alert with many file.

### ISSUE THREAD

**Issue by xyj404** [microsoft/vscode#95084]
- VSCode Version: 1.43.2
- OS Version: Darwin x64 18.2.0

Steps to Reproduce:

1. import a component, can't go to it's definition.
![image](https://user-images.githubusercontent.com/17355263/79092955-344ff880-7d85-11ea-93c4-51dfa6e6aa62.png)
It's ok when I use f12 at `'./SubmitButton'`. But when I use f12 at SubmitButton
![image](https://user-images.githubusercontent.com/17355263/79093392-c278ae80-7d86-11ea-8452-10a2e77e6178.png)

I don't know why It have 4 definition and can't go to `index.js` file.

Does this issue occur when all extensions are disabled?: No

**Comment by xyj404** [comment]
no same issues

**Comment by mjbvz** [comment]
So if you disable extensions, you don't see this issue?

**Comment by xyj404** [comment]
Thank you, It's become good when I disable unnecessary extensions. But I don't know why the command `code --list-extensions` no effects.
