### ISSUE TITLE
Setting "explorer.openEditors.visible": 0 does not actually set the Open Editors view to 0 / hidden

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#9509]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.14390

Steps to Reproduce:

1. Open VS Code
2. Open a bunch of tabs
3. Ctrl+Shift+P "settings" > Open User Settings
4. Set "explorer.openEditors.visible": 0 and save the settings.json file.
5. Observe that the height of the Open Editors view actually gets set to the same as if you had set "explorer.openEditors.visible": 1.
6. Close VS Code
7. Open VS Code
8. Open a bunch of tabs
9. Observe that the number of open editors visible appears to still be one.

![image](https://cloud.githubusercontent.com/assets/494055/16971870/23148d7e-4ddc-11e6-9bba-6e76ecd2232f.png)

Differs from the change mentioned in https://code.visualstudio.com/updates#vscode "Open Editors View"

Also repros in:
- VSCode Version: Code - Insiders 1.4.0-insider (f4780e67933164a2289b86f2c279aaa05fda672f, 2016-07-19T05:07:05.876Z)
- OS Version: Windows_NT ia32 10.0.14390

**Comment by kieferrm** [comment]
This only happens when VS Code has no open folder.

**Comment by bpasero** [comment]
As designed.

**Comment by isidorn** [comment]
Yes this is as designed as in that case we always want to show the open editors section (explorer is useless).

**Comment by dilijev** [comment]
Alright, then. Makes sense, of course. Maybe update documentation to avoid anyone's future confusion?

**Comment by isidorn** [comment]
@gregvanl ping for doc update request

**Comment by isidorn** [comment]
@gregvanl another ping for doc update request since people are still hitting this issue

**Comment by michelkaporin** [comment]
Maybe we should update documentation, people still hitting it... @gregvanl

**Comment by isidorn** [comment]
@michelkaporin maybe you should ping @gregvanl on slack also, not sure if he is reading all git hub notifications

**Comment by michelkaporin** [comment]
@isidorn will do 👍

**Comment by gregvanl** [comment]
Documentation updated with https://github.com/Microsoft/vscode-docs/commit/0385daf159043a762d6f2cd00c8a312fb83d5d29
