### ISSUE TITLE
On MAC, using ESLint and vetur, save vue file, card dead. Always prompt "saving 'xxx.vue' : getting code action from 'ESLint'"

### ISSUE THREAD

**Issue by ligouhai** [microsoft/vscode#95098]
If inscribe.
Every time you disable eslint, it doesn't solve the underlying problem

**Comment by yume-chan** [comment]
Translation: "Card dead" means "freezed" or "not responding".

**Comment by ligouhai** [comment]
> Translation: "Card dead" means "freezed" or "not responding".

Did you meet that too

**Comment by yume-chan** [comment]
> Did you meet that too

@ligouhai no.

**Comment by octref** [comment]
Please provide your information to https://github.com/microsoft/vscode-eslint/issues/904

**Comment by ligouhai** [comment]
> Please provide your information to [microsoft/vscode-eslint#904](https://github.com/microsoft/vscode-eslint/issues/904)

thank you
