### ISSUE TITLE
where i can found how to create javascript completionitems list ui in "VSCode source code"?

### ISSUE THREAD

**Issue by BleyChen** [Microsoft/vscode#951]
I want to develop an vscode plugin to change completionitem list UI ,anyone know where I can found the code that create the completionitem list UI in VSCode source?
![mmm](https://cloud.githubusercontent.com/assets/15098626/11551192/f72d0486-99b1-11e5-9994-e841694cf2be.png)

**Comment by egamma** [comment]
C:\Users\egamma\Projects\Monaco\src\vs\editor\contrib\suggest
I suggest to join the discussion on the completion UI in #369.
