### ISSUE TITLE
Display Debug Configuration Name in Terminal Session Dropdown for "console": "integratedTerminal"

### ISSUE THREAD

**Issue by bagratte** [microsoft/vscode#95107]
Issue Type: <b>Feature Request</b>

This will be especially useful in multi-root workspaces. There is currently no way to distinguish debug sessions in integrated terminal. This issue suggests Terminal session dropdown items be named after debug configuration names, just like the dropdown in 'Debug Console'.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11438666/79114053-581a3b00-7d93-11ea-8897-4f9b0bd72312.gif)

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T08:23:56.137Z)
OS version: Darwin x64 19.4.0

**Comment by Tyriar** [comment]
What's your proposal to improve it? The Python extension owns what the name is set to so I think this should probably get reported to them?

**Comment by bagratte** [comment]
My proposal is to name items in Terminal session dropdown after debug configuration names.
Let me know if I need to do anything with the second part of your comment.

**Comment by Tyriar** [comment]
You should reach out to https://github.com/microsoft/vscode-python with the request, they set that title here:

https://github.com/microsoft/vscode-python/blob/bd8d32bccbf9b459981db18c837ee68414335cf4/src/client/debugger/debugAdapter/DebugClients/LocalDebugClient.ts#L157-L163
