### ISSUE TITLE
Terminal links should open word links if there is exactly 1 matching file inside the workspaces

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95119]
With https://github.com/microsoft/vscode/issues/21125#issuecomment-612716041 I'm triggering quick access via `IQuickInputService.quickAccess.show(string)`. Ideally it would automatically activate the first item before showing the quick access if it's the only item available. Is there a way to way to do this already and if not could this be a new option here?

https://github.com/microsoft/vscode/blob/01a9cf11a61f8f9ef13c9c017fde44e8d93da94f/src/vs/platform/quickinput/common/quickAccess.ts#L13-L31

**Comment by bpasero** [comment]
No, quick input (and quick access) do not have such an option. Can you not simply check how many picks you return and if there is just one, take it?

**Comment by Tyriar** [comment]
@bpasero how would I go about doing that? Would that use all the quick access providers?

What I'm after is for a user to ctrl/cmd+click say "package.json", and if there is only 1 package.json in the workspace then it should open it directly (ideally without a flash of the quick input opening), otherwise do the equivalent of ctrl/cmd+p `package.json`.

**Comment by Tyriar** [comment]
I haven't touched any of these APIs before and only found this quickaccess.show by searching around which mostly does what I'm after.

**Comment by jmbockhorst** [comment]
Instead of using quick access to search for the files, you would probably have to search for them yourself, if there is only 1 result, use it, and if there are more, show a quick pick for all those files using `IQuickInputService.pick()`.

**Comment by Tyriar** [comment]
Thanks for the help all, I got this working and will make this issue a bug to verify.
