### ISSUE TITLE
Drag and drop a zipped file to vs code

### ISSUE THREAD

**Issue by wbail** [microsoft/vscode#95115]
Issue Type: <b>Bug</b>

Issue:
Unable to open 'FileName.cs': Unable to read file 'temp/path/to/file.cs' (Error: Unable to resolve non-existing file 'temp/path/to/file.cs'

Steps to Reproduce:
1. Double click into filezipped.zip;
2. Drag and drop the file directly to vs code.

Softwares:
1. 7zip / Version: 16.02 64bit
2. VS Code / Version: 1.44.0

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (18.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-author-generator|edw|0.0.10
csharp|ms-|1.21.16
highlight-bad-chars|wen|0.0.3

</details>

**Comment by isidorn** [comment]
dup of https://github.com/microsoft/vscode/issues/75559

**Comment by wbail** [comment]
Thanks!
