### ISSUE TITLE
Extension error with the latest update (1.44.0)

### ISSUE THREAD

**Issue by kanakshilledar** [microsoft/vscode#95117]
Issue Type: <b>Bug</b>

I am getting extension error after this latest update. I tried to reinstall vscode but same error is there. Your early action on the issue will be highly appericated.
Thank you sir/mam

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (3.42GB free)|
|Process Argv|D:\Document\Python Projects\Machine Learning|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.21.16
python|ms-|2020.3.71659
remote-wsl|ms-|0.44.2
cpptools|ms-|0.27.0
vscode-java-debug|vsc|0.25.1
vscode-maven|vsc|0.21.2

</details>

**Comment by RMacfarlane** [comment]
Likely a duplicate, please see https://github.com/microsoft/vscode/issues/94858#issuecomment-612010439
