### ISSUE TITLE
The terminal process terminated with exit code: 3221225477

### ISSUE THREAD

**Issue by davormilutinovic** [microsoft/vscode#95111]
Version: 1.44.0 (user setup)
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-07T23:31:18.860Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1."Open in Terminal" 
2.Error occurs The terminal process terminated with exit code: 3221225477

As I understood this is an old bug that was related to win7 x32 version but with new vsc 1.44 this occurs with win 10 x64

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Do you have anti-virus software that could be blocking the terminal? If so try following the instructions in https://code.visualstudio.com/docs/editor/integrated-terminal#_how-do-i-fix-the-errors-connectnamedpipe-failed-windows-error-232-or-terminal-exited-with-code-x-on-windows

**Comment by davormilutinovic** [comment]
I didn't have this problem with previous VSC version but today I have  Avast Antivirus app to the latest version and it is now working. I haven't use suggestions from ttps://code.visualstudio.com/docs/editor/integrated-terminal#_how-do-i-fix-the-errors-connectnamedpipe-failed-windows-error-232-or-terminal-exited-with-code-x-on-windows as this is not necessary now but maybe this will help someone else.
