### ISSUE TITLE
comments garbled.

### ISSUE THREAD

**Issue by Oger-Me** [Microsoft/vscode#9511]
- VSCode Version: 1.3.1
- OS Version: Win 10 Professional

Steps to Reproduce:

1. I'm from Chinese. and some comments of these code is garbled. see the following image:
![comments_garbled](https://cloud.githubusercontent.com/assets/3223890/16972191/06714132-4e5c-11e6-961f-bcc520e8f529.png)
![Uploading comments_garbled.png…]()

**Comment by dilijev** [comment]
I wonder if this is just an encoding issue. Would probably help to have a copy of the file uploaded to see what the binary contents of the file are. Also interesting is that there seem to be several Chinese characters in the view (near beginning of line 1, near middle of line 3, beginning of the 4th line from the end), but it could be just a coincidence that CJK characters show up in garbled Unicode.

Also could you post a screenshot or text of what you're expecting to see?

**Comment by kieferrm** [comment]
@Oger-Me I concur with @dilijev assumption that this is an encoding issue. I'm closing this for now. If you don't agree pls provide the information asked above.
