### ISSUE TITLE
Reveal in Explorer doesn't work for specific vscode files like settings.json or keybindings.json?

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#95118]
Issue Type: <b>Bug</b>

```js
{
	"key": "shift+alt+r",
	"command": "-revealFileInOS",
	"when": "!editorFocus"
},
{
	"key": "shift+alt+r",
	"command": "revealFileInOS",
},
```

1. Open a file outside of workspace ( `keybindings.json`)
1. Try to reveal it `revealFileInOS`

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

**Comment by IllusionMH** [comment]
Looks like it doesn't work for specific VS Code files.

With opened folder in `C:\project\project_name` I have no problem to Reveal in Explorer files like `C:\web\apache-tomcat\logs\catalina.out`, `C:\web\test.txt`, and `C:\Users\user_name\Documents\test.txt`.

But no luck for User `settings.json` or `keybinding.json` files

**Comment by isidorn** [comment]
Yes, I think we have this limitation.
Here's a code pointer in case you would like to investigate more https://github.com/microsoft/vscode/blob/96b8ab431e98e451daea76c576f4d4d0f68a3cf5/src/vs/workbench/contrib/files/electron-browser/fileCommands.ts#L17
