### ISSUE TITLE
Ctrl+Shift+H Global Search differs in focus behavior from Ctrl+Shift+F

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#9512]
- VSCode Version: Code - Insiders 1.4.0-insider (f4780e67933164a2289b86f2c279aaa05fda672f, 2016-07-19T05:07:05.876Z)
- OS Version: Windows_NT ia32 10.0.14390

Steps to Reproduce:

1. Open VS Code
2. Ctrl+Shift+F to open Global Find
3. Ctrl+Shift+F again returns focus to editor (subsequent invocations toggle focus)
4. Ctrl+Shift+H opens Global Replace
5. Ctrl+Shift+H again does not toggle focus between Global Replace and the editor

**Comment by sandy081** [comment]
Ctrl+Shift+H is a new command to open Replace in Files and this is not a View command like 
View -> Search. Hence it is not toggling the focus.
