### ISSUE TITLE
Provide a command to browse file system and return the file path selected

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#95123]
Hi Python extension dev here👋

We're planning to support the following way for users to type in the path to their Python interpreter.

![image](https://user-images.githubusercontent.com/13199757/79130470-dce96280-7d5b-11ea-99f7-49141ff0daa9.png)

Users would rarely add the interpreter path this way, so It would be great if we can also add a browse button, which will help the user browse their file system to find and select the interpreter directly.

This functionality is similar to `Open file...` in VS Code where user browses the file system to select a file to open. Similar to https://code.visualstudio.com/docs/getstarted/keybindings#_file-management

I have a workaround but it does not seem ideal,
Invoke the following commands in series:
- `workbench.action.files.openFile`
- Some way to get uri of Active Editor - `vscode.window.activeTextEditor.document.uri` doesn't seem to work for `python.exe` files. Also it looks like it's not immediately updated, I've wait for a while for it to be updated.
- `workbench.action.closeActiveEditor`

**Comment by chrmarti** [comment]
Would `window.showOpenDialog` do what you need? It doesn't open the file, but returns the chosen file(s) as its result.

**Comment by karrtikr** [comment]
That should do the job, thank you!

**Comment by karrtikr** [comment]
@chrmarti I've another question.

![image](https://user-images.githubusercontent.com/13199757/79130470-dce96280-7d5b-11ea-99f7-49141ff0daa9.png)

This look like a combination of an input box and a quickpick. Do you guys have a way where you can enter something into a input box as well select something in the dropdown quickpick list?

**Comment by chrmarti** [comment]
You seem to use `createQuickPick()`. With that you can add a listener `quickPick.onAccept()` and in there read `quickPick.value`. Could you give that a try?

**Comment by karrtikr** [comment]
Yeah it works, but the quickpick option list also disappeared when typing the interpreter path, but I guess that's how it works?

**Comment by chrmarti** [comment]
You can set `alwaysShow = true` on the items you don't want to be filtered out.

**Comment by karrtikr** [comment]
Got it, thanks again!

**Comment by karrtikr** [comment]
I used that, but when typing the interpreter path and pressing Enter, the `Browse...` item got selected (as it automatically became the active item while filtering) instead of accepting input from filterbox.

I had `activeItems` array set to `[]`, so it was not highlighted initially, but as soon as I started typing, it turned `blue` and was selected on pressing Enter.

**Comment by karrtikr** [comment]
Thanks, I used that, but when typing the interpreter path and pressing Enter, the `Browse...` item got selected (as it automatically became the active item while filtering) instead of accepting input from filterbox.

I had `activeItems` array set to `[]`, so it was not highlighted initially, but as soon as I started typing, it turned `blue` and was selected on pressing Enter. IMO filtering shouldn't highlight items it didn't match, even though `alwaysShow` is set to `true` for the item.

**Comment by chrmarti** [comment]
Ack, you need to add an item for the current value in the text box. I think the `Git: Clone` command will use that same approach in todays Insiders build - but that is not out yet.

**Comment by karrtikr** [comment]
> you need to add an item for the current value in the text box

Sorry I don't understand, can you please elaborate? is this text box referring to the filter box?

**Comment by chrmarti** [comment]
Yes, the user would type and you would just update the first item to be what the user has entered into the filter box. When the user presses enter, that special item would be accepted. I don't have an example at hand at the moment (the `Git: Clone` change hasn't made it yet).

**Comment by karrtikr** [comment]
I see, thanks a lot. Really appreciate your help.
