### ISSUE TITLE
javascript自動補全後不會有小括號

### ISSUE THREAD

**Issue by Racious** [microsoft/vscode#95137]
Issue Type: <b>Bug</b>

javascript自動補全方法後不會有小括號
還要自己手動打()才會出現，很困擾，希望能修正

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500X 6-Core Processor              (6 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (11.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.29
vscode-html-css|ecm|0.2.3
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|4.3.0
auto-rename-tag|for|0.1.1
autofilename|Jer|0.1.3
vscode-gutter-preview|kis|0.25.0
vscode-language-pack-zh-hant|MS-|1.44.2
material-icon-theme|PKi|4.0.1
polacode|pnp|0.3.4
vscode-css-peek|pra|3.0.2
r-lsp|REd|0.1.6
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.8.0
vscodeintellicode|Vis|1.2.6
JavaScriptSnippets|xab|1.7.2
material-theme|zhu|3.2.5

(1 theme extensions excluded)

</details>

**Comment by yume-chan** [comment]
Translation:

> # JavaScript autocomplete doesn't add braces
>
> There are no braces after autocompleted JavaScript functions.
>
> I have to type () manually. I'm confused, hoping to be fixed.

**Comment by yume-chan** [comment]
You can add `"javascript.suggest.completeFunctionCalls": true` (`"typescript.suggest.completeFunctionCalls": true` for TypeScript) to your settings to let vscode auto complete function braces and parameters for you.

**Comment by chrmarti** [comment]
Thanks @yume-chan, closing as question.
