### ISSUE TITLE
Stable v1.44.0 - No preference sync available in settings menu

### ISSUE THREAD

**Issue by o-l-a-v** [microsoft/vscode#95132]
- VSCode Version: 1.44.0
- OS Version: Windows 10 Enterprise, 19041.172

In the v1.44.0 changelog you mention that preference sync is available.

* https://code.visualstudio.com/updates/v1_44#_settings-sync

However, it does not show in the settings menu for neither of my three computers.

![image](https://user-images.githubusercontent.com/6450056/79138321-a12eb700-7db4-11ea-814b-15aa7eb8bb7f.png)

You documentation on "preference sync" still says sync is only for VSCode insider builds:

* https://code.visualstudio.com/docs/editor/settings-sync

Is sync not available for stable yet, even though it's mentioned in the changelog and it was said to come in v1.44.0?

**Comment by IllusionMH** [comment]
/question

It's mentioned in **Preview features** section of Release notes (usually in Insiders versions, sometimes features are behind disabled by default flag) - in this case it clearly states that sync is in Insiders build.

>**Settings Sync**
>We have been working the last couple of months to support synchronizing VS Code settings, extensions, and keyboard shortcuts across machines and **this feature is available for preview on the Insiders release.**

You need to install 1.45-insiders using https://code.visualstudio.com/insiders/

**Comment by o-l-a-v** [comment]
> Please ask your question on [StackOverflow](https://aka.ms/vscodestackoverflow). We have a great community over [there](https://aka.ms/vscodestackoverflow). They have already answered thousands of questions and are happy to answer yours as well. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Happy Coding!

This is not a feature request, this is an error report saying that what you say are available in the changelog, is not in actually available in the GUI. Incosistent documentation.

Please re-open or explain to me why a feature that per changelog should be in v1.44.0, isn't.

**Comment by IllusionMH** [comment]
This is standard bot response.
You should check https://github.com/microsoft/vscode/issues/95132#issuecomment-612975414 that clarifies what was communicated in Release notes.

**Comment by o-l-a-v** [comment]
> This is standard bot response.
> You should check [#95132 (comment)](https://github.com/microsoft/vscode/issues/95132#issuecomment-612975414) that clarifies what was communicated in Release notes.

I somehow missed that comment, thanks.
