### ISSUE TITLE
Keyboard shortcut to select all occurrances, then able to edit + tab through

### ISSUE THREAD

**Issue by jwlodek** [microsoft/vscode#95133]
I like to throw a lot of TODOs into my code to go back and add comments. It would be nice if there was a shortcut to select all occurrences of TODO, and then I could edit them one by one while tabbing through them, as is the case with say auto-created function docs for js.  Something like Ctrl-F -> TODO-> Escape -> Ctrl-E

**Comment by ArturoDent** [comment]
Not a built-in shortcut but an extension that will do this:

https://marketplace.visualstudio.com/items?itemName=danseethaler.tab-through-selections

**Comment by chrmarti** [comment]
You can `Ctrl + F` the first TODO and then just `F3` to jump to the next after you have edited the current. (Closing as `question`, let me know if this doesn't work.)

**Comment by jwlodek** [comment]
This is great thanks. Is there a way to rebind this behavior to a different shortcut? The F3 key is kind of out of the way. If not, then F3 will work.

**Comment by chrmarti** [comment]
You can edit the keybindings under `File` > `Preferences` > `Keyboard Shortcuts`.
