### ISSUE TITLE
Allow to maximize Side Bar

### ISSUE THREAD

**Issue by pavkum** [microsoft/vscode#95139]
- VSCode Version: 1.44
- OS Version: mac os catalina

Steps to Reproduce:

1. Move terminal to activity bar by dragging and dropping to activity bar
2. Try to maximize the terminal by running command "view: Toggle Maximized Panel"

Expected: Terminal should maximize
Actual: Terminal size stays the same

Does this issue occur when all extensions are disabled?: Yes

**Comment by ArturoDent** [comment]
If you have moved it to the Activity Bar then it is no longer in the Panel and so I would suspect the command

`View: Toggle Maximized Panel`

should do nothing to the Terminal - which I assume you now opened up in the Side Bar.  It doesn't look there is a `Maximize the Side Bar` command.

There is a "Toggle the Side Bar Visibility" command so you could physically drag the Activity Bar/Editor separator to one side to maximize it and then toggle will go back and forth but between a nearly full-sized Terminal and one not visible at all which may not be what you want.

**Comment by sbatten** [comment]
@ArturoDent is correct. The command is about the panel, not the terminal. It is working as intended.

**Comment by pavkum** [comment]
@sbatten @ArturoDent  When the terminal is moved to side bar we need a way to maximize it like it was possible when it was present in the panel.  I mentioned `view: toggle maximized panel`  to say we may need equivalent command to maximize terminal when it is present in sidebar.

Moving items from panel to sidebar strips of the maximizing capabilities but where as moving items from sidebar to panel adds the capability.
