### ISSUE TITLE
Command to re-wrap code to respect a preferred line length column (e.g. 80 columns)

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#9514]
- VSCode Version: Code - Insiders 1.4.0-insider (f4780e67933164a2289b86f2c279aaa05fda672f, 2016-07-19T05:07:05.876Z)
- OS Version: Windows_NT ia32 10.0.14390

For example, in Vim, you can select multiple lines of text and type `gq` and lines will be re-wrapped so that they don't exceed the setting for max line length (e.g. 80 columns).

It would be nice to see a similar feature in VS Code especially for wrapping comments, which also has the behavior of correctly inserting a syntax-aware single-line comment token (e.g. //) at the beginning of each wrapped line (and not moving that token into the re-wrapped text of the same lines).

Would also like this functionality to respect the indentation level of the code.

**Comment by stkb** [comment]
https://marketplace.visualstudio.com/items?itemName=stkb.rewrap

**Comment by dilijev** [comment]
@stkb Thanks. What is the distinction between features that are a part of VS Code by default versus things which are added as extensions?

**Comment by stkb** [comment]
To paraphrase something @bpasero once said: if it can be done as an extension, it should be done as an extension. Of course, some (small) features that were once extensions do get added to vscode from time to time.

**Comment by lorenzodallavecchia** [comment]
For languages that have a formatter (above all, TypeScript), the wrapping behavior would also make sense as part of the formatter.
The maximum line length for code and comments could be configured as two new formatter options, and the language service may make smart decisions about where to break the lines to not hurt readability.

Are there any plans for such a feature?

**Comment by alexburner** [comment]
+1 for having max line length as part of the formatter. I'm on a hunt for a `prettier` alternative, it just hit 1.0 but doesn't support TypeScript (https://github.com/prettier/prettier/issues/13)

Ideally my team would like a formatter (for ts/tsx) that handles an 80 col limit with the proper line breaks/indentation to make it look good. I'm looking at `typescript-formatter` (https://github.com/vvakame/typescript-formatter), which seems to be powered by `tsc` (https://github.com/vvakame/typescript-formatter/blob/master/lib/formatter.ts#L4), but also used by the VS Code team? (https://github.com/Microsoft/vscode/issues/17627)

**Comment by evmar** [comment]
clang-format (http://probst.io/blog/2015/01/15/clang-format-for-javascript/) supports TypeScript and does intelligent wrapping.

**Comment by alexburner** [comment]
Thank you @evmar ! I will look into this

**Comment by cyda89** [comment]
+1 for having max line length as part of the formatter. Since it is included for html ("html.format.wrapLineLength"), why should it not be for js/ts etc.?

**Comment by alexburner** [comment]
FWIW, `prettier` now supports typescript, and handles max line length:
https://prettier.io/docs/en/options.html#print-width
