### ISSUE TITLE
Terminal text does not reflow when terminal in Side Bar and the Side Bar is expanded

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#95149]
- VSCode Version: v1.44 and same in Insiders' this date
- OS Version:  W10

Steps to Reproduce:

1.  Drag Terminal header to Activity Bar
2.  Open the Terminal (into Side Bar)
3.  Run a Terminal command, like `ls`
4.  Drag Side Bar/Editor separator to the right .

The terminal output text does not reflow as the Side Bar area is expanded.  A new Terminal command will use the entire width but existing text does not reflow. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is a limitation on Windows due to the way it works. If you're on Windows 1903 you will likely be able to reproduce it in Windows Terminal which is the backend the terminal uses.
