### ISSUE TITLE
preferredDarkColorTheme and preferredLightColorTheme show incorrect warnings

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95144]
Both of these values are valid

![image](https://user-images.githubusercontent.com/2193314/79150647-fe5b4600-7d7d-11ea-8163-209b47a29794.png)

This was a new Windows 10 machine but I think I've seen this before reinstalling.

**Comment by Tyriar** [comment]
Also happens with color theme:

![image](https://user-images.githubusercontent.com/2193314/79171019-d7186f00-7da5-11ea-90a7-3e138085b608.png)

**Comment by aeschli** [comment]
duplicate of #94876
