### ISSUE TITLE
Settings sync complains about conflicts on a brand new Windows 10 install

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95143]
I just reinstalled Windows 10 and one of the first things I did was install VS Code. I definitely did not have settings before starting as I cleared all drives.

Conflicts despite empty settings.json:

![image](https://user-images.githubusercontent.com/2193314/79149750-788acb00-7d7c-11ea-9112-e35672bd1c8c.png)

Conflicts view calls out whitespace and comments?

![image](https://user-images.githubusercontent.com/2193314/79149811-8f312200-7d7c-11ea-9191-a8ff451d9e65.png)

Accepting remote got what I wanted, but that should have happened automatically.

**Comment by sandy081** [comment]
To verify:

- Have two insiders open with different user data directories and extension directories
- On first insiders turn on sync
- Have following settings content
```json
{
	// this is a comment
    "workbench.colorTheme": "Default Light+"
}
```
- Go to second instance
- Have empty settings
- Turn on sync and merge. Make sure there are no conflicts.
