### ISSUE TITLE
Rename Symbol does not replace multiple symbols on same line

### ISSUE THREAD

**Issue by kevinbeason** [microsoft/vscode#95145]
Issue Type: <b>Bug</b>

Rename Symbol function on C++ highlights all instances of the symbol and shows them in the pending rename list, but when confirming (by pressing the check mark), only renames the first instance of the symbol on each line.

For example, if renaming foo to bar on this line:
   
   foo = blah + foo;

"Rename Symbol" produces:

  bar = blah + foo;

where it did not rename the second instance of "foo".

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 3.10.0-1062.1.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: pearlsand|
|OS|Linux x64 3.10.0-1062.1.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (36 x 1873)|
|Memory (System)|187.44GB (123.32GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
activitusbar|Gru|0.0.26
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
material-icon-theme|PKi|4.0.1
copy-relative-path-and-line-numbers|ezf|0.2.8
ispc|int|1.0.0
cpptools|ms-|0.27.0

</details>

**Comment by chrmarti** [comment]
@mjbvz Is this caused by the extension?
