### ISSUE TITLE
User setting to disable smart step

### ISSUE THREAD

**Issue by orokanasaru** [microsoft/vscode#95155]
I'm trying to debug something. I've manually placed a breakpoint in JS code. Smart step skips over it and breaks in some completely unrelated code that it decided was more relevant. Trying to step into the method from the caller or step out from a method that it calls just leads to it getting skipped again.

Since this feature got released, I don't think I've ever gotten joy from using it, but I have had near constant pain from issues like this.

I can (and do) set `smartStep: false` in launch.json files, but I don't know of any way to disable it for all commands run manually in the Debugger Terminal.

My ask is to provide a way to disable it permanently in the normal user settings.

**Comment by weinand** [comment]
The "Smart step" feature has only an effect if you are using source maps and those maps don't have a mapping for some region of JS code. In this case "Smart step" tries to avoid showing you the "raw" JS code and continues running until it lands in the user visible source.

Are you using source maps? What is your source language, TypeScript?

**Comment by connor4312** [comment]
> disable it for all commands run manually in the Debugger Terminal

It sounds like they are 🙂 

You can configure the default options via `debug.javascript.terminalOptions`, for example:

```
  "debug.javascript.terminalOptions": {
    "smartStep": false
  },
```

Let us know if that does what you're after.

**Comment by orokanasaru** [comment]
@weinand, 

For further context:

I was getting an exception when running `rush update`. I tried debugging with break on exceptions, but the exception was thrown without breaking on it. I managed to search source on github to track it down to a pnpm error. I manually set the breakpoint in the source that I assumed was throwing the exception, and it still skipped over it. `console.log` debugging ended up being the way to debug the issue due to smart step trying to be too smart.

pnpm is written in TypeScript and built with source maps, but the package does not ship with them. It sounds like this is the exact scenario where smart step is designed to kick in, and is also exactly the reason why I never want to use it. 

Maybe it could be useful if it didn't skip over breakpoints and thrown exceptions, and provided a way to disable it for specific files to not skip over when re-running the debug command, but that's not the case currently.

@connor4312, 

Thanks! That option worked perfectly for this scenario.

**Comment by connor4312** [comment]
Ah, yea, that makes sense. For exception breakpoints and any breakpoints manually set, I think we should not smart step when we initially hit them. However, for general event breakpoints we probably still should--for instance, I might want to break on a click event handler and then smart step into my React-based callback.

cc @roblourens as well for thoughts
