### ISSUE TITLE
Ability to customize / highlight the active (in focus) editorGroup 

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [microsoft/vscode#95159]
As discussed [here](https://stackoverflow.com/questions/59075505/highlighting-better-the-current-editor-group). It would be great to be able to highlight the **editorGroup** in focus.

With increasingly larger screens and folks using more editor **groups**, it can be hard to know which exact `editorGroup` has the current focus on a quick look. Ideally one could customize e.g. its background color, the tab color, or e.g. maybe just display some bounding box around it (I'm including a made up example below for illustrative purposes).

<img width="1412" alt="s36NR" src="https://user-images.githubusercontent.com/1993919/79169887-b0653300-7dbb-11ea-9288-dd5f4428968c.png">

**Comment by bpasero** [comment]
@amelio-vazquez-reina the tab color at least is customizable, did you try to specify `tab.activeBackground` or `tab.activeForeground` or `tab.activeBorder`?

**Comment by amelio-vazquez-reina** [comment]
Thanks @bpasero . Yes, I played with all three, but they seem to customize the look of **all** active **tabs** in **all** editorGroups. What I proposing here is a way to customize the appearance of the editorGroup in focus.
