### ISSUE TITLE
Feature Request: Fallback for integrated terminal shell

### ISSUE THREAD

**Issue by janmoelter** [microsoft/vscode#95150]
With the setting `terminal.integrated.shell.*` it is possible to specify the default shell for the integrated terminal. However, using the same configuration on different computers, I frequently find myself in the situation, that my preferred shell is not available on all of them. When opening the integrated terminal in this case, it crashes with a notification saying that the terminal shell path cannot be found. This is unfortunate as no terminal can be opened in this state.

Hence, I was wondering whether it was possible to have a fallback for the terminal shell. This way, if the first shell cannot be found, the terminal could proceed with the next in a list, similar to how we have fallbacks for fonts (`terminal.integrated.fontFamily` or `editor.fontFamily`), and only throw an error if it cannot find any of the shells.

An alternative option would be that, when the terminal cannot find the shell, it at least gives the option to select an alternative shell instead of only presenting the error notification.

_Related Issues_: #10893, #11748

---

VS Code version: Code 1.44.0
OS version: Windows_NT x64 10.0.18363

**Comment by Tyriar** [comment]
This will probably get fixed by https://github.com/microsoft/vscode/issues/45444, we can probably also validate the shells exist of the ones you configure there.

/duplicate
