### ISSUE TITLE
"Debug VS Code Main, Renderer & Extension Host" launch config fails with timeout

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode#95152]
Issue Type: <b>Bug</b>

1. Clone VSCode repo
2. Open in VSCode
3. Build VSCode from source
3. Run "Debug VS Code Main, Renderer & Extension Host" compound launch config

Debugger fails to attach to VSCode with the following error message:
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:5870)

My current workaround is to add `"timeout": 20000` to the "Attach to Extension Host" launch config.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T08:23:56.137Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 6|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|-psn_0_196656|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
project-manager|ale|10.11.0
spellright|ban|3.0.50
vscode-css-modules|cli|0.2.3
vscode-eslint|dba|2.1.2
vscode-dash|dee|2.4.0
find-related|eam|0.9.0
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
prettier-vscode|esb|4.3.0
vscode-ghc-mod|hoo|1.2.0
search-node-modules|jas|1.3.0
hoogle-vscode|jca|0.0.7
language-haskell|jus|2.7.0
vscode-duplicate|mrm|1.2.1
vscode-scss|mrm|0.9.0
python|ms-|2020.3.71659
cpptools|ms-|0.27.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1947
debugger-for-chrome|msj|4.12.6
ruby|reb|0.27.0
vscode-quick-scope|ska|0.2.0
reveal|smu|1.2.7
vscodeintellicode|Vis|1.2.6
vim|vsc|1.13.1
vscode-ruby|win|0.27.0
material-theme|zhu|3.2.5

(1 theme extensions excluded)

</details>

**Comment by ChrisPapp** [comment]
I can duplicate this, most of the time with the error ECONNREFUSED 127.0.0.1:9222 (instead of 5870), when I have Chrome open.

**Comment by weinand** [comment]
Works fine for me in VS Code 1.50
