### ISSUE TITLE
Notebook UX Explorations

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#95154]
## Summary

This issue covers the ux explorations for our [Notebook native support](https://github.com/microsoft/vscode/issues/91987).

## Backlog
- [x] :running_man: 1. Cell toolbar
- [x] :running_man: 2. Cell progress and status
- [x] :running_man: 3. Output toolbar
- [x] :running_man: 4. Drag and drop
- [x] :running_man: 5. Folding indicators and folding UX
- [x] :running_man: 6. Keyboard and cell focus
- [x] :running_man: 7. Changing cell type
- [x] :running_man: 8. How does the current focus indication go together with SCM decorations?
- [ ] What does a minimap for notebooks look like?
- [ ] Overall polish: spacing, color, ...
- [ ] Notebook diffing
- [ ] Global notebook state and actions

### 1. Cell toolbar
Code Cells
<img width="866" alt="Cell toolbar - Code" src="https://user-images.githubusercontent.com/35271042/79805881-fec68480-831b-11ea-9b28-87ff4cfd1ad9.png">

Text Cells
<img width="866" alt="Cell toolbar - Markdown" src="https://user-images.githubusercontent.com/35271042/79805890-025a0b80-831c-11ea-9dd4-153a5154b4a8.png">

<img width="866" alt="Cell toolbar - Markdown Edit" src="https://user-images.githubusercontent.com/35271042/79805889-01c17500-831c-11ea-80e0-a8a1164d702b.png">

### 2. Cell progress and status

![Kapture 2020-04-16 at 22 09 14](https://user-images.githubusercontent.com/35271042/79534370-33da8a80-802f-11ea-8b09-72b2e2e1cba8.gif)

<img width="866" alt="Status Bar - Default" src="https://user-images.githubusercontent.com/35271042/79506613-269bac80-7feb-11ea-8929-52d77f04ea18.png">

<img width="866" alt="Status Bar - Running" src="https://user-images.githubusercontent.com/35271042/79506618-28657000-7feb-11ea-89c0-d3b2cc86aaae.png">

### 3. Output toolbar
Switcher for output renderers
![Kapture 2020-04-16 at 13 13 57](https://user-images.githubusercontent.com/35271042/79502208-2815a680-7fe4-11ea-9483-6e46e423b323.gif)

### 4. Drag and drop
![Kapture 2020-04-16 at 21 47 05](https://user-images.githubusercontent.com/35271042/79533077-e14b9f00-802b-11ea-94bf-100e8232012a.gif)

### 5. Folding cells
![Kapture 2020-04-16 at 15 11 20](https://user-images.githubusercontent.com/35271042/79511681-a4b08100-7ff4-11ea-84f8-5aac80760474.gif)

### 6. Keyboard and cell focus

Code Cells
![Kapture 2020-04-16 at 12 37 55](https://user-images.githubusercontent.com/35271042/79499011-239abf00-7fdf-11ea-90b1-16529f4b9cae.gif)

Text Cells
![Kapture 2020-04-16 at 12 22 02](https://user-images.githubusercontent.com/35271042/79497663-ed5c4000-7fdc-11ea-8bc5-896a84b52173.gif)

### 7. Changing cell type
![Kapture 2020-04-16 at 14 35 05](https://user-images.githubusercontent.com/35271042/79509003-88f6ac00-7fef-11ea-9408-64c70eacbff0.gif)

### 8. Focus indicator & SCM decorations
TBD

**Comment by babul7154** [comment]
when we will get this new jupyter notebook?

**Comment by misolori** [comment]
These initial explorations have been completed, please see our [Notebook UX Feedback](https://github.com/microsoft/vscode/issues/104772) issues for an up-to-date status on notebooks.
