### ISSUE TITLE
result of powershell command : help  can not be loaded to console

### ISSUE THREAD

**Issue by hanbaobao2005** [Microsoft/vscode#9516]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Step to Reproduce:

1. run PowerShell command : help Get-EventLog -Full

Issue:
The output of help command can be loaded to VSCode window.

**Comment by kieferrm** [comment]
Works in the latest insider build (1.4.0).
