### ISSUE TITLE
Windows Powershell should use the old paste behavior

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95169]
Use Windows PowerShell (v5) and try paste text with ctrl+v, it should paste, not print ^V

**Comment by Tyriar** [comment]
FYI @TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
hmm that's odd... Windows PowerShell _has_ PSReadLine... and I'm pretty sure it has ctrl+v

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/79181550-726b0d80-7dc1-11ea-9977-ec0fc470a71a.png)

**Comment by Tyriar** [comment]
This is with a new Windows 10 install, empty settings.json

**Comment by TylerLeonhardt** [comment]
Can you run `$Error` and see if anything is in there? PSRL should load just fine in Windows PowerShell.


cc @daxian-dbw

**Comment by Tyriar** [comment]
`$Error` prints nothing,

This is the executable used:

```
[2020-04-13 20:06:54.439] [renderer1] [trace] IPty#spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe [] {"name":"powershell.exe","cwd":"E:\\GitHub\\Tyriar\\xterm.js","env":{...},"cols":61,"rows":12,"useConpty":true,"conptyInheritCursor":false}
```

**Comment by Tyriar** [comment]
Reverted for now, seems to just be a out of sources problem.
