### ISSUE TITLE
revealInExplorer called on the folder should drop any explorer selection and focus the list

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95164]
This is the result of running the command on the opened folder:

![image](https://user-images.githubusercontent.com/2193314/79173772-69704100-7dad-11ea-95ab-ebe69beca66b.png)

I expect this:

![image](https://user-images.githubusercontent.com/2193314/79173790-768d3000-7dad-11ea-97a3-1d87f57e9ae1.png)

The reason on my end is it's unexpected when activating a terminal link of the opened folder https://github.com/microsoft/vscode/issues/29499

/cc @mjbvz

**Comment by isidorn** [comment]
You request makes sense and I have done that change. Try it out and let me know how it goes.

**Comment by Tyriar** [comment]
Thanks, works great
