### ISSUE TITLE
Markdown not properly formatting links at Debug Tab

### ISSUE THREAD

**Issue by marcelodasilva** [microsoft/vscode#95161]
- VSCode Version: 1.44.0
- OS Version: Zorin OS 15.1

Steps to Reproduce:

1. Open up Debug tab

Does this issue occur when all extensions are disabled?: Yes

Description:
I open my debugging tab, to create a launch.json for my project, it was expected that there would be a link to execute the action to generate the base template, and I realized that the markdown link formatting did not work.

screenshot:
![Captura de tela de 2020-04-13 20-23-17](https://user-images.githubusercontent.com/10062477/79170083-b0b5fc00-7dc4-11ea-87b9-34cae2f1ae15.png)

expected behavior: 
![ok](https://code.visualstudio.com/assets/docs/editor/debugging/debug-start.png)

my settings.json

```json
{
  "window.zoomLevel": 0,
  "workbench.startupEditor": "newUntitledFile",
  "editor.fontFamily": "Fira Code",
  "editor.fontLigatures": true,
  "editor.fontSize": 14,
  "workbench.iconTheme": "material-icon-theme",
  "editor.rulers": [
    80,
    120
  ],
  "editor.renderLineHighlight": "gutter",
  "editor.tabSize": 2,
  "terminal.integrated.fontSize": 14,
  "emmet.includeLanguages": {
    "javascript": "javascriptreact",
    "django-html": "html",
    "edge": "html"
  },
  "emmet.syntaxProfiles": {
    "javascript": "jsx"
  },
  "[javascript]": {
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": true
    },
  },
  "[javascriptreact]": {
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": true
    },
  },
  "[typescript]": {
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": true
    },
  },
  "[typescriptreact]": {
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": true
    },
  },
  "javascript.updateImportsOnFileMove.enabled": "never",
  "editor.parameterHints.enabled": false,
  "breadcrumbs.enabled": true,
  "javascript.suggest.autoImports": false,
  "editor.formatOnSave": true,
  "workbench.statusBar.visible": true,
  "editor.multiCursorModifier": "alt",
  "files.associations": {
    "**/*.html": "html",
    "**/templates/**/*.html": "django-html",
    "**/templates/**/*": "django-txt",
    "**/requirements{/**,*}.{txt,in}": "pip-requirements",
    ".sequelizerc": "javascript",
    "prettierrc": "json"
  },
  "gitlens.views.repositories.files.layout": "list",
  "emojisense.languages": {
    "plaintext": false,
    "json": true,
    "javascript": true,
    "javascriptreact": true,
    "typescript": true,
    "typescriptreact": true,
  },
  "prettier.requireConfig": true
}
```

**Comment by lukaschal** [comment]
File: vscode-workbench\vs_workbench_contrib_debug.xlf
ID: 0; "src/vs/workbench/contrib/debug/browser/welcomeView.openAFileWhichCanBeDebugged"
SRC: [Open a file](command:{0}) which can be debugged or run.
TGT: [Open a file](command:{0}) which can be debugged or run.

**Comment by danyeh** [comment]
Thank you for your feedback!
Looks like this was fixed back in May. Closing this.
https://github.com/microsoft/vscode-loc/blob/master/i18n/vscode-language-pack-pt-BR/translations/main.i18n.json#L3860
