### ISSUE TITLE
Application appears disabled but is editable, after update

### ISSUE THREAD

**Issue by jdelforno** [microsoft/vscode#95167]
Issue Type: <b>Bug</b>

Not sure on how to reproduce this issue.

Basically, the entire application is dull, like it's disabled pending an update. 

I've uninstalled via control panel, reinstalled and tried an uninstall, reboot, reinstall and the issue is still present.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor              (16 x 3900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (25.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
azureautomation|Awe|1.0.2
vscode-intelephense-client|bme|1.3.11
laravel-goto-view|cod|1.3.2
vscode-eslint|dba|2.1.2
dbrs-terraform|dbr|0.0.3
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
prettier-vscode|esb|4.3.0
php-debug|fel|1.13.0
vscode-pull-request-github|Git|0.15.0
vscode-github|Kni|0.30.3
aws-cli-configure|mar|0.3.0
terraform|mau|1.4.0
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-azurefunctions|ms-|0.22.0
vscode-azureterraform|ms-|0.3.0
python|ms-|2020.3.71659
remote-wsl|ms-|0.44.2
azure-account|ms-|0.8.9
azurecli|ms-|0.5.0
Go|ms-|0.13.1
powershell|ms-|2020.3.0
laravel-blade|one|1.20.0
laravel-extension-pack|one|0.6.1
laravel5-snippets|one|1.8.0
vscode-xml|red|0.11.0
terraform-doc-snippets|run|0.4.0
laravel-artisan|rya|0.0.27
salesforcedx-vscode|sal|48.10.0
salesforcedx-vscode-apex|sal|48.10.0
salesforcedx-vscode-core|sal|48.10.0
salesforcedx-vscode-lightning|sal|48.10.0
salesforcedx-vscode-lwc|sal|48.10.0
salesforcedx-vscode-visualforce|sal|48.10.0
code-settings-sync|Sha|3.4.3
vscode-ansible|vsc|0.5.2

</details>

**Comment by jdelforno** [comment]
![image](https://user-images.githubusercontent.com/52432197/79176072-ab979200-7e42-11ea-86fd-b0b963036614.png)

There's also this

**Comment by jdelforno** [comment]
Attempted to disable all extensions, still the same.

**Comment by jdelforno** [comment]
Only appears to be an issue on a 5k monitor. 1080p, no issue it seems.

**Comment by jdelforno** [comment]
Updated, issue still occurs.

[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version: 1.44.0 (user setup)
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-07T23:31:18.860Z (6 days ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by deepak1556** [comment]
Since it happens on 5k, most likely the hdr issue https://github.com/microsoft/vscode/issues/88491


@jdelforno how does it look when you start code with `--force-color-profile srgb` ?

**Comment by jdelforno** [comment]
> 
> 
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

Downloaded the insider build, issue still present.

> 
> 
> Since it happens on 5k, most likely the hdr issue #88491
> 
> @jdelforno how does it look when you start code with `--force-color-profile srgb` ?

This worked,

**Comment by deepak1556** [comment]
Thanks for confirming, I merging this to #88491
