### ISSUE TITLE
Support GitHub logins in settings sync

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95160]
Currently Settings Sync needs MSFT account. This request is to allow users to use GitHub account to login and use Settings Sync

**Comment by sandy081** [comment]
Here is my proposal for choosing between MSFT or Github account. We add another option to the Accounts picker (while turning on Settings Sync) to choose between MSFT or GitHub account

## 1. Turning on Sync (When not signed into any accounts)

<img width="618" alt="image" src="https://user-images.githubusercontent.com/10746682/79685838-f72fae80-823b-11ea-8993-478d4d80d3fb.png">

<img width="623" alt="image" src="https://user-images.githubusercontent.com/10746682/79685895-64dbda80-823c-11ea-9b75-fae40e086799.png">

## 2. Turning on Sync (When already signed into one of the accounts)

<img width="623" alt="image" src="https://user-images.githubusercontent.com/10746682/79685921-994f9680-823c-11ea-95c8-50ccd0da24c1.png">

<img width="622" alt="image" src="https://user-images.githubusercontent.com/10746682/79685992-1da21980-823d-11ea-9ca2-ac15f56139b2.png">
