### ISSUE TITLE
Uninstall every close window

### ISSUE THREAD

**Issue by zhafranth** [microsoft/vscode#95172]
When i save the project and close the window the visual studio code is uninstall and when iam reopend the project the visual studio code must be install

**Comment by chrmarti** [comment]
How do you start VS Code? From the start menu? Which OS and which version of VS Code are you using?

**Comment by joaomoreno** [comment]
Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by zhafranth** [comment]
> How do you start VS Code? From the start menu? Which OS and which version of VS Code are you using?

yes, I open from the start menu. I am using windows 10 and  vscode userSetup-x64-1.440 version

**Comment by zhafranth** [comment]
> Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

![image](https://user-images.githubusercontent.com/15321351/79581555-c002b580-80f4-11ea-8ce3-2ceaf4e3c120.png)

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
