### ISSUE TITLE
You need to enable Javascript

### ISSUE THREAD

**Issue by jcthird** [microsoft/vscode#95177]
Issue Type: <b>Bug</b>

 <noscript>
      You need to enable JavaScript to run this app.
    </noscript>

I get this erro everytime I try to run javascript on my code. I cant fix it

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (3.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|44%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.2
prettier-vscode|esb|4.3.0
python|ms-|2020.3.71659
LiveServer|rit|5.6.1

(1 theme extensions excluded)

</details>

**Comment by chrmarti** [comment]
Please attach a screenshot.
