### ISSUE TITLE
Nothing prints

### ISSUE THREAD

**Issue by nicholashuang23** [microsoft/vscode#95174]
Issue Type: <b>Bug</b>

I type print('hello') on vscode and saved it as python doc. when I try to run all that shows is PS C:\Users\user> python -u "c:\Users\user\Downloads\FOA\Untitled-1.py" which is the path. When I change the terminal to powershell instead of code, it shows up with Unable to initialize device PRN

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (2.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
code-runner|for|0.9.17
chat|kar|0.33.0
python|ms-|2020.3.71659
cpptools|ms-|0.27.0
vsliveshare|ms-|1.0.1947
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
vscode-xml|red|0.11.0

</details>

**Comment by chrmarti** [comment]
Please attach a screenshot.
