### ISSUE TITLE
VSCode flickers opening the css file 

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode#95178]
- VSCode Version: 1.44.0
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. open css file
2. change editor width

VSCode will flicker.

[font-awesome.min.css.zip](https://github.com/microsoft/vscode/files/4473186/font-awesome.min.css.zip)

**Comment by alexdima** [comment]
@kzhui125 How do you mean? I cannot reproduce any flickering:

![Kapture 2020-04-14 at 10 48 54](https://user-images.githubusercontent.com/5047891/79204971-a08e3300-7e3d-11ea-90f2-b78465fb362e.gif)

**Comment by kzhui125** [comment]
@alexdima 
It looks like this:
https://streamable.com/tproo5

Thanks,

**Comment by alexdima** [comment]
This reproduces with the following:
```
"editor.wordWrap": "on", // or a file with minified code which gets wrapping turned on automatically
"editor.minimap.enabled": true,
"editor.minimap.size": "fit",
```
And it reproduces at the boundary where the minimap switches scales. It looks like the layout is in some kind of loop:

![Kapture 2020-04-14 at 12 25 13](https://user-images.githubusercontent.com/5047891/79214470-0c2acd00-7e4b-11ea-9b3c-43275a622f48.gif)
