### ISSUE TITLE
SSIS Add-in Flat-File (RaggedRight) Issue

### ISSUE THREAD

**Issue by actuarysailor** [microsoft/vscode#95170]
RaggedRight does not work correctly.  There is a bug where if a line is too short, it then assumes the next line continues it.

Example:

Column1  Column2  Column3 Column4 \r\n
Column5  Column6  Column7\r\n
Column8  Column9  Column10 Column11 \r\n
Column12  Column13  Column14 Column15 \r\n

Issue: 
The parser will then treat the rows like this:

Column1  Column2  Column3 Column4 \r\n
Column5  Column6  Column7\r\nColumn8  Column9  Column10 Column11 \r\n
Column12  Column13  Column14 Column15 \r\n

This will result in two rows of data being dropped, not just the one that is too short...

It should check for the line breaks prior to parsing the sub-string.

**Comment by chrmarti** [comment]
Is this the SQL server extension? Please file against the extension that provides the functionality. (SQL server: https://github.com/Microsoft/vscode-mssql/issues)

/causedByExtension
