### ISSUE TITLE
deleted file

### ISSUE THREAD

**Issue by lady-eve** [microsoft/vscode#95173]
Issue Type: <b>Bug</b>

file was "deleted" in vs but still available on my desktop and in correct folder. would not show in folder tree in vs code. exited "deleted" tab and started over, and somehow text and tag autocompletion stopped working

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 1700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
save-typing|akh|0.1.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1

</details>

**Comment by chrmarti** [comment]
Please update to the latest version of VS Code to get the latest bugfixes and attach a screenshot.
