### ISSUE TITLE
Cannot find name 'BigInt'

### ISSUE THREAD

**Issue by bkilinc** [microsoft/vscode#95187]
Issue Type: <b>Bug</b>

in one project BigInt() constructor is reported as error with the message Cannot find name 'BigInt'. 
Example : this.value = BigInt(0);
in another project no error is reported and intellisense for BigInt works fine. The strange thing is; when I return back to previous project the errors are gone and it recognizes BigInt. And this is replicatable.
In the same workspace;
1. I open a file in first project and see BigInt errors.
2. I open a file in second project and see BigInt's are working fine.
3. I switch  to the file in first project and see BigInt errors are gone. 

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T11:22:13.689Z)
OS version: Linux x64 5.3.0-46-generic

**Comment by chrmarti** [comment]
Is this C++?

**Comment by bkilinc** [comment]
It is JavaScript

**Comment by mjbvz** [comment]
Do your projects have jsconfig or tsconfig files? Can you share these?

`BigInt` was only added in es2018 I believe so you'll need to update your `jsconifg`/`tsconfig` to tell VS Code that you are targeting a modern JS runtime and can use it

**Comment by bkilinc** [comment]
there is no jsconfig and tsconfig. But I noticed this error is gone if I require Knex.
I just created a blank project with try.js containing this.
let a = BigInt(1);
vscode shows error.
just install knex with" npm install knex" and the error is gone. 
removing knex shows error again. 
But I could not find where BigInt typedef comes from. I made a text search on node_modules with knex installed.

**Comment by bkilinc** [comment]
I have, Javascript > Implicit project config > Check JS option has been checked. To show errors.

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/TypeScript/issues/37986 to track why knex is causing `BigInt` to become valid
