### ISSUE TITLE
golang Find usage fail.

### ISSUE THREAD

**Issue by zouyx** [Microsoft/vscode#9518]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.1.7601
- About golang Find usage fail.

Steps to Reproduce:

1.select  a  method which you want to find usage.
2.click shift+f12
3.it will show : no result , actually it has been used.

**Comment by kieferrm** [comment]
@zouyx I assume you have the go extension installed and you perform `find references` in a go file?

Please provide a sample workspace and concrete steps that shows the problem.

**Comment by zouyx** [comment]
@kieferrm 
Hi , i have installed go ext.
The feature was fine before update vscode
I am not sure if relate to update.

Could you send me your email?

I can't upload my sample or error pic.

**Comment by kieferrm** [comment]
@zouyx can you explain your setup and show a minimal code snippet in the comment?

**Comment by zouyx** [comment]
@kieferrm 

you mean how to setup?
i installed a old version before,maybe 1.2.*
one day my friend come to help me to review my code and then click check update button
Automatically update to 1.3.1
the future cannot use.

the code as below
``go
package main

import (
	"fmt"
	"net/http"
)

func init() {
	http.HandleFunc("/test", handle)
}
func main() {
	addr := fmt.Sprintf("%s:%d", "127.0.0.1", 8082)
	http.ListenAndServe(addr, nil)
}

func handle(rw http.ResponseWriter, req *http.Request) {
	refer := req.URL.Query().Get("refer")
	fmt.Println("refer:", refer)

	testFind()
}

func testFind() {
	fmt.Println("test!")
}
``

**Comment by aeschli** [comment]
Please check that you also have the latest go extension installed (maybe uninstall and install).
If it still doesn't work, please file an issue against the go extension: https://github.com/Microsoft/vscode-go

**Comment by zouyx** [comment]
@aeschli @kieferrm 
thank you very much.

**Comment by aeschli** [comment]
Thanks @zouyx for getting back to us. Closing as suggested.
