### ISSUE TITLE
文件夹和文件无法点击

### ISSUE THREAD

**Issue by lumeme** [microsoft/vscode#95181]
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。

**Comment by byyxx128** [comment]
This issue can be closed because the author didn't provide valid information.
#73921
I have interpreted the reason why so many users create plenty of invalid issues.

**Comment by yume-chan** [comment]
Also I wonder why language classification didn't work (so the `translation-required-undefined` tag).

Anyway, the title translates to:

> # Can't click folders and files

**Comment by chrmarti** [comment]
@lumeme You didn't paste the report's details from the clipboard, please open a new issue including the details.
