### ISSUE TITLE
There is no formatter for 'typescript' files installed.

### ISSUE THREAD

**Issue by johndave8116** [microsoft/vscode#95180]
i have typescript formatter installed on my vs code then also its giving me this error.
because of this i have tried reinstalling my vs code then also it gives me such error.
please suggest me on this.

OS
Windows 7 

Version of VS Code
-x64-1.44.0

List of extensions that you have installed
1.  Angular Language Service
2. ESLint
3. TypeScript Hero
4. Material Icon Theme
5. HTML Snippets

![image](https://user-images.githubusercontent.com/16661250/79301105-473e0680-7f06-11ea-8fc0-0528081abfd1.png)

My code is not formatting when i try to  format it with Ctr + Shift + f 
pop-up appears right corner stating (There is no formatter for 'typescript' files installed.).
please refer the screen above.

Thank you.

**Comment by johndave8116** [comment]
No this doesn't  give me any fix.

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by johndave8116** [comment]
> /needsMoreInfo
> 
> Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

yes i have updated now 

#95180 ..please check above

**Comment by jrieken** [comment]
Please retry without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks. 

<img width="577" alt="screen shot 2018-05-09 at 08 45 10" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

**Comment by johndave8116** [comment]
i have tried this ..its all the same.

![image](https://user-images.githubusercontent.com/16661250/79314914-f3401b80-7f1f-11ea-8a94-f2dfae0f00f9.png)


waiting for your reply at the earliest.
Thank you.

**Comment by jrieken** [comment]
any chance this is https://github.com/microsoft/vscode/issues/94858

**Comment by johndave8116** [comment]
I disabled AV  and re installed ..now its working fine.
Thank You for your support !!!

**Comment by johndave8116** [comment]
> any chance this is #94858

this started when i updated my VS code to new version
