### ISSUE TITLE
Allow to define workbench.action.quickOpenView order

### ISSUE THREAD

**Issue by zhangwilling** [microsoft/vscode#95191]
Machine:  MacPro 2016
OS：Catalina 10.15.2
vscode: 1.44.0

I found  `workbench.action.quickOpenView` would focus on `Search` in `Side Bar` at latest version (1.44.0) by default, although the first item was `Explorer`. 

I also tried to drag sidebar's item order in ActivityBar, but the order of items in `quickOpenView` -> `Side Bar` not changed.

Previous versions always focused on the first item(`Explorer`), that's what i really want.

so, i want a feature to define quickOpenView's order. 

( Maybe it was a little bug at latest version ?)

**Comment by bpasero** [comment]
`workbench.action.quickOpenView` is meant to be used via keybindings only with the idea that you bring up the picker and release the keys to automatically pick the entry. As such all of these focus the second item by default. 

The command you want to use instead is: `workbench.action.quickOpenView`

**Comment by zhangwilling** [comment]
thanks for your response. 

But my case is when `Search` (other items) is visible, i will use `quickOpenView` and release immediately to pick the first one (`Explorer`). If i want the second, i will use picker (`workbench.action.quickOpenNavigateNextInViewPicker`) .

Now  i must show `quickOpenView` first, then use `workbench.action.quickOpenNavigatePreviousInViewPicker` to select the first (`Explorer`).

**Comment by zhangwilling** [comment]
`Explorer` is most important, so i want select it when i open `quickOpenView ` and release without quickOpen navigation.

**Comment by zhangwilling** [comment]
thanks for reopening.

I define a special shortcut key for `Explorer` temporarily. 😊

**Comment by bpasero** [comment]
I decided to revert back to how it was and now Explorer will always be the first entry: https://github.com/microsoft/vscode/issues/95448

**Comment by yinbun** [comment]
My current method is ctrl + q to pop up the view, and then ctrl + shift + q to return to the Explorer.I want to die

**Comment by zhangwilling** [comment]
but  i found source control war not at previous order.. 😂
