### ISSUE TITLE
vscode not responding while editing

### ISSUE THREAD

**Issue by dejour** [Microsoft/vscode#9519]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. it's random, but it happened several times. I don't know how to reproduce it
2.
![rk3so 1 2fsmd w l92_6](https://cloud.githubusercontent.com/assets/7224044/16976734/a97db730-4e83-11e6-8ddc-9d88a389ed36.png)

**Comment by kieferrm** [comment]
Can you please provide the info that you have such as the size of your workspace, types of files in the workspace, etc.?

What files do you edit when it happens?

Does it happened when you disabled all extensions you have installed? You can start vscode with `code --disabled-extensions` from the command line to verify that.

Thx!

**Comment by kieferrm** [comment]
No info. Closing.
