### ISSUE TITLE
intelisense support stopped 

### ISSUE THREAD

**Issue by Nileshdcool** [microsoft/vscode#95195]
Issue Type: <b>Bug</b>

From 2 days vs code has stopped working proeprly . No intellisense support for Angular , typescript, and HTML side. Every time it gives an error host provider stopped unexpectadaly 

VS Code version: Code - Insiders 1.45.0-insider (4f05de82a75569601bc2dc894023383b4ce1c2c0, 2020-04-13T17:53:50.995Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (2.61GB free)|
|Process Argv|--folder-uri file:///d%3A/Torakami/Projects/idea-expander/ideaexpender-web|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by jrieken** [comment]
@Nileshdcool Can you ckeck if it's this: https://github.com/microsoft/vscode/issues/94858

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Aneeds more info
