### ISSUE TITLE
Extension host failed -

### ISSUE THREAD

**Issue by Nileshdcool** [microsoft/vscode#95197]
Issue Type: <b>Bug</b>

Extension host failed -

Error - 
workbench.desktop.main.js:sourcemap:258 [Extension Host] Error: ENOENT: no such file or directory, open 'c:\Users\bingo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js' 

Vs code not working proeprly - Angular, Typescript, HTML intelisense styopped working

VS Code version: Code - Insiders 1.45.0-insider (c8826e4ff5246775ebee0fb932402de6af55ddc8, 2020-04-14T05:58:16.222Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (3.31GB free)|
|Process Argv|D:\Torakami\Projects\idea-expander\ideaexpender-web|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.2
Angular-BeastCode|Mik|8.1.2

</details>

**Comment by gjsjohnmurray** [comment]
If you are using Quick Heal antivirus see #94858
