### ISSUE TITLE
White Flash in Dark Theme

### ISSUE THREAD

**Issue by JHaller27** [microsoft/vscode#95190]
Issue Type: <b>Bug</b>

System info:
* VS Code on WSL (though also reproduced on host Windows 10)
* System theme set to dark
* VS Code Color Theme Preference set to "Dark+ (default dark)"

Repro steps:
1. Open VS Code

Expected result:
VS Code opens in dark mode, without flashing white

Actual result:
VS Code flashes bright white before switching quickly to dark theme.

I do not have epilepsy, but this could certainly be a trigger. Even without epilepsy, it hurts my eyes and is rather frustrating. I'm no expert, but this feels like an accessibility violation.

------

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.86GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/win/git/md2bb --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|15.93GB (6.86GB free)|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.6.6
remote-wsl|ms-|0.41.9
vim|vsc|1.13.1
python|ms-|2020.2.64397

</details>

**Comment by chrmarti** [comment]
Please update to the lastest version of VS Code and confirm the problem is still there.

**Comment by kshpytsya** [comment]
Happens here as well:

Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-08T11:22:13.689Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.5.0-pf2

**Comment by JHaller27** [comment]
@chrmarti Sorry, I was having issues updating (probably a WSL thing, not a VSCode thing). After updating my specs are:

Version: 1.44.1 (user setup)
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:48:12.622Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by Rakleed** [comment]
I can also reproduce this if my VS Code was opened in full screen mode, then closed, and opened again.

**Comment by Shindanaide** [comment]
I have the same issue with Dropdown Menus (File, Edit, Selection, ...). Clicking on a menu causes a white flash.

Version: 1.44.1
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-16T21:41:21.848Z
Electron: 7.1.14
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.33-3-MANJARO

**Comment by deepak1556** [comment]
@JHaller27  would be good to check if our exploration build that has Electron 8 runtime fixes the issue https://github.com/microsoft/vscode/issues/94074#issuecomment-607079209

@Shindanaide the menubar issue is tracked under https://github.com/microsoft/vscode/issues/80798 , please follow that for updates. Thanks!

**Comment by Rakleed** [comment]
@chrmarti please take a look.

**Comment by chrmarti** [comment]
@Rakleed Could you:
> [...] check if our exploration build that has Electron 8 runtime fixes the issue [#94074 (comment)](https://github.com/microsoft/vscode/issues/94074#issuecomment-607079209)
