### ISSUE TITLE
TypeError: Cannot read property '_acceptIsDirty' of undefined

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#952]
Seeing this in latest, making the PH go crazy:

![image](https://cloud.githubusercontent.com/assets/900690/11553945/bfbc16a4-9993-11e5-88c2-3e065e351963.png)

**Comment by bpasero** [comment]
@jrieken I pushed a workaround, but thats likely not the right fix: https://github.com/Microsoft/vscode/commit/2de359c7d3c3635d565b54e62affbc03f6aedc0e

**Comment by bpasero** [comment]
@jrieken also the integration tests are failing, this might be related: https://travis-ci.org/Microsoft/vscode/jobs/94578250

**Comment by jrieken** [comment]
I will investigate. @bpasero when did this happen? plain modes like JS and TS or mixed modes, like HTML+JS+CSS etc

**Comment by bpasero** [comment]
@jrieken yes in TS selfhost.

**Comment by jrieken** [comment]
Yeah, found it and triggered builds
