### ISSUE TITLE
Suggestion and auto-complete is very very very slow. 

### ISSUE THREAD

**Issue by abheist** [microsoft/vscode#95200]
Issue Type: <b>Performance Issue</b>
and my settings are
```
{
    "editor.fontSize": 16,
    "editor.lineHeight": 28,
    "editor.letterSpacing": 0.5,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "editor.formatOnSave": true,
    "editor.formatOnPaste": true,
    "editor.formatOnType": true,
    "workbench.iconTheme": "material-icon-theme",
    "editor.codeActionsOnSave": {
        "source.fixAll": true
    },
    "prettier.requireConfig": true,
    "git.autofetch": true,
    "editor.fontLigatures": true,
    "editor.fontFamily": "Fira Code, Menlo, Monaco, 'Courier New', monospace",
    "workbench.colorTheme": "Night Owl",
    "editor.detectIndentation": true,
    "emmet.includeLanguages": {
        "javascript": "javascriptreact",
        "jsx-sublime-babel-tags": "javascriptreact"
    },
    "emmet.triggerExpansionOnTab": true,
    "vsintellicode.features.python.deepLearning": "enabled",
    "typescript.suggest.completeFunctionCalls": true,
    "javascript.suggest.completeFunctionCalls": true,
    "editor.snippetSuggestions": "top",
    "editor.suggest.snippetsPreventQuickSuggestions": false,
    "emmet.showSuggestionsAsSnippets": true,
    "editor.tabCompletion": "on",
    "editor.quickSuggestions": true,
    "editor.quickSuggestionsDelay": 0,
    "files.associations": {
        "*.js": "javascriptreact",
    },
    "[javascriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[jsonc]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "workbench.colorCustomizations": {
        "[Night Owl]": {
            "activityBar.background": "#000C1D",
            "activityBar.border": "#102a44",
            "sideBar.background": "#001122",
            "sideBar.border": "#102a44",
            "sideBar.foreground": "#8BADC1"
        },
        "[Night Owl No Italics]": {
            "activityBar.background": "#000C1D",
            "activityBar.border": "#102a44",
            "sideBar.background": "#001122",
            "sideBar.border": "#102a44",
            "sideBar.foreground": "#8BADC1"
        }
    },
    "bracket-pair-colorizer-2.forceIterationColorCycle": true,
}
```

still when I write anything in reactJS fils with extention of .js.
The autocomplete dialog appears after many seconds and is dead slow.

VS Code version: Code - Insiders 1.45.0-insider (c8826e4ff5246775ebee0fb932402de6af55ddc8, 2020-04-14T05:52:37.373Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.65GB free)|
|Process Argv|../goldenSwan.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   23	    98	 79319	code-insiders main
    0	    66	 79364	   gpu-process
    0	    16	 79366	   utility
    0	   279	 79367	   window (WriteUpFunc.js — goldenSwan (Workspace))
    0	   147	 79370	     extensionHost
    0	    33	 79401	       /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer) /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=79370
    0	    82	 79411	       electron_node tsserver.js 
    0	   573	 79412	       electron_node tsserver.js 
    0	    66	 79414	         electron_node typingsInstaller.js typesMap.js 
    0	    82	 79413	       electron_node eslintServer.js 
    0	    33	 79371	     watcherService
    0	    33	 79378	     searchService
    0	    98	 79396	   shared-process
    0	     0	 79448	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    82	 79445	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (WriteUpFunc.js — goldenSwan (Workspace))
|    Folder (goldenSwan-frontend): 168 files
|      File types: js(41) svg(37) woff2(21) woff(18) json(6) png(5) css(4)
|                  eslintignore(1) eslintrc(1) gitignore(1)
|      Conf files: jsconfig.json(1) package.json(1) launch.json(1)
|                  settings.json(1)
|      Launch Configs: pwa-chrome;
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.1.2
es7-react-js-snippets|dsz|2.7.1
prettier-vscode|esb|4.3.0
material-icon-theme|PKi|4.0.1
vscodeintellicode|Vis|1.2.6
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by abheist** [comment]
And just tested more.
It working damn fast with TypeScript projects. i.e: create-react-app with TypeScript or Angular.

Though It's very slow in pureJS.

Found this ⚡️sign coming in status bar while working with TypeScript and not coming while working with JS.
<img width="378" alt="Screenshot 2020-04-14 at 4 09 23 PM" src="https://user-images.githubusercontent.com/5029660/79216299-90d91380-7e6a-11ea-8a25-5ccda45df4b3.png">

**Comment by mjbvz** [comment]
Does this reproduce [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by abheist** [comment]
Disabled all the extension, the problem still coming. will it be the case because of the **packages** I'm using?
I'm attaching gif for more help, PFA.

Packages, I'm using are:
```JSON
"@apollo/client": "^3.0.0-beta.41",
"@apollo/link-context": "^2.0.0-beta.3",
"draft-js": "^0.11.5",
"formik": "^2.1.4",
"graphql": "^14.6.0",
"immutable": "^4.0.0-rc.12",
"prop-types": "^15.7.2",
"react": "^16.13.0",
"react-dom": "^16.13.0",
"react-router-dom": "^5.1.2",
"react-scripts": "3.4.0",
"react-toastify": "^5.5.0",
"reakit": "^1.0.0-beta.16",
"styled-components": "^5.0.1",
"styled-icons": "^10.2.1",
"styled-theming": "^2.2.0",
"yup": "^0.28.3"
```

And I found this related issue with styled-components, not sure though: 
https://github.com/Microsoft/vscode/issues/71751#issuecomment-480126916
I tried installing `"@types/styled-components": "^5.1.0"`, but it also doesn't help.

![Screen Recording 2020-04-16 at 1 34 19 AM](https://user-images.githubusercontent.com/5029660/79384370-5f546b00-7f84-11ea-9e0f-36dbf7f57b5e.gif)

**Comment by mjbvz** [comment]
Thanks for testing. 

Can you also please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) and restarting VS Code

I see much better perf using typescript@next in a simple file with those dependencies installed. If you can share your project, I can also test using that

**Comment by abheist** [comment]
https://github.com/abheist/goldenSwan-frontend

you can test it here 👆

I also tried using `@types` in devDependencies. as mentioned in other threads. Still no progress. 😕

**Comment by mjbvz** [comment]
Did using typescript@next help?

**Comment by abheist** [comment]
Yep, a bit. The suggestion within code gets a bit better.
But when I'm trying to import it directly by writing:
`imp` and press `tab` or `control+space`, it starts to show `loading...`
and complete the tab in ~4 seconds. and this behaviour is when I disabled the `react snippets extension`

**Comment by joaopaulobdac** [comment]
TS 3.9 caused this issue when I updated to 1.46. Suggestions take much longer to show up and CPU temperature increases more than normal. After configuring VSCode to use TS 3.8.3 it went back to normal again.

**Comment by mjbvz** [comment]
@abheist If you still see this with TS 3.9+, please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

If you can share this log, it may help us track down what is taking so long

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
