### ISSUE TITLE
Autocomplete and intellisense is extemely slow

### ISSUE THREAD

**Issue by muraterd** [microsoft/vscode#95207]
Issue Type: <b>Performance Issue</b>

Autocomplete and intellisense is extemely slow. Also prettier with auto-format on save is too slow. I disabled auto-format on save functionality but no change 

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (24.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    81	  9360	code main
    1	   144	  9932	   gpu-process
    0	    62	 12688	   window (Issue Reporter)
    0	   349	 13992	   window (ClassPicker.tsx - *** - Visual Studio Code)
    8	   133	 14800	     extensionHost
    0	    51	 16556	       electron_node tsserver.js 
    0	   206	 16592	       electron_node tsserver.js 
    0	    44	 17240	         electron_node typingsInstaller.js typesMap.js 
    0	    31	 16640	       electron_node server.js 
    0	    31	 17152	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=14800
    0	     6	 14872	     console-window-host (Windows internal process)
    0	    70	 14916	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     4	 13084	       C:\WINDOWS\system32\cmd.exe /c ""C:\Program Files\nodejs\npm.cmd" start"
    0	    29	 18180	         "C:\Program Files\nodejs\\node.exe"  "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" start
    0	     4	 12860	           C:\WINDOWS\system32\cmd.exe /d /s /c react-scripts start
    0	    23	 10008	             electron_node react-scripts.js 
    0	   371	 17548	               node C:\Projects\MaC\***\node_modules\react-scripts\scripts\start.js
    0	   184	 17604	                 "C:\Program Files\nodejs\node.exe" --max-old-space-size=2048 C:\Projects\MaC\***node_modules\fork-ts-checker-webpack-plugin\lib\service.js
    0	    22	 15560	     watcherService 
    0	    11	 15696	       console-window-host (Windows internal process)
    0	    36	 16504	     searchService
    0	    26	 14176	   utility
    0	    14	 14740	   electron-crash-reporter
    0	    77	 16204	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (ClassPicker.tsx - *** - Visual Studio Code)
|    Folder (***): 258 files
|      File types: tsx(36) scss(34) ts(28) png(27) svg(27) jpg(16) json(6)
|                  woff(4) ico(2) gitignore(1)
|      Conf files: package.json(1) tsconfig.json(1) settings.json(1);
```

</details>
<details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
path-intellisense|chr|1.4.2
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
prettier-vscode|esb|4.3.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
docthis|joe|0.7.1
vscode-colorize|kam|0.8.16
csharp|ms-|1.21.17
material-icon-theme|PKi|4.0.1
quicktype|qui|12.0.46
code-settings-sync|Sha|3.4.3
swdc-vscode|sof|2.1.54
react-redux-es6-snippets|tim|2.1.0
jsx|Twe|0.0.1
unity-debug|Uni|2.7.5
wallaby-vscode|Wal|1.0.193
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.4.0
material-theme|zhu|3.2.5
html-css-class-completion|Zig|1.19.0

(3 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
