### ISSUE TITLE
Support synchronising extension's global state

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#95209]
Support synchronising extension's global state

**Comment by bwateratmsft** [comment]
For Docker extension, we'd need to be able to sync on a per-key basis. There are some areas where sync would be nice to have (nothing imperative, right now), but there are some where we cannot sync (e.g. machine-specific information that we want to cache forever because it's expensive to compute but never changes).

**Comment by legomushroom** [comment]
This could be useful for `Live Share` to sync up the chat history that is currently stored locally only. cc @jramsay @fubaduba

**Comment by sandy081** [comment]
**Proposal:**

Provide a contribution point for the extension to register memento keys to sync

```
"contributes": {
		"settingsSync.memento": {
			"global": [
				"key1"
			]
		}
}
```

**Comment by bwateratmsft** [comment]
I like that plan. We do have some keys in the Docker extension that are determined at runtime (thus couldn't be in package.json), but I don't think any of them need synchronization.

**Comment by jrieken** [comment]
```ts
export interface Memento {

		/**
		 * Return a value.
		 *
		 * @param key A string.
		 * @return The stored value or `undefined`.
		 */
		get<T>(key: string): T | undefined;

		/**
		 * Return a value.
		 *
		 * @param key A string.
		 * @param defaultValue A value that should be returned when there is no
		 * value (`undefined`) with the given key.
		 * @return The stored value or the defaultValue.
		 */
		get<T>(key: string, defaultValue: T): T;

		/**
		 * Store a value. The value must be JSON-stringifyable.
		 *
		 * @param key A string.
		 * @param value A value. MUST not contain cyclic references.
		 */
		update(key: string, value: any, includeInSettingsSync?: boolean): Thenable<void>;

		keys(): ReadonlyArray<string>;

		onDidChange: Event<{ readonly keys: ReadonlyArray<string> }>;
	}
```

**Comment by jrieken** [comment]
Alternative proposal avoiding update-sync-not-sync confusion and very simple migration. 

```
export interface Memento {

		/**
		 * Return a value.
		 *
		 * @param key A string.
		 * @return The stored value or `undefined`.
		 */
		get<T>(key: string): T | undefined;

		/**
		 * Return a value.
		 *
		 * @param key A string.
		 * @param defaultValue A value that should be returned when there is no
		 * value (`undefined`) with the given key.
		 * @return The stored value or the defaultValue.
		 */
		get<T>(key: string, defaultValue: T): T;

		/**
		 * Store a value. The value must be JSON-stringifyable.
		 *
		 * @param key A string.
		 * @param value A value. MUST not contain cyclic references.
		 */
		update(key: string, value: any): Thenable<void>;

		/**
		 *
		 */
		syncedKeys: string[];

		onDidChange: Event<{ readonly keys: ReadonlyArray<string> }>;
	}
```

**Comment by legomushroom** [comment]
@bwateratmsft agreed! But that is a different feature - we need context properties for the settings just like commands have :) Worths creating an issue for that if there isn't one yet 😊

**Comment by bwateratmsft** [comment]
@legomushroom I'm not sure I follow. This issue is about using settings sync to synchronize global state (mementos), right? I'm not  sure commands are related.

**Comment by sandy081** [comment]
Added following proposed API

```ts

export interface ExtensionContext {
	readonly syncedGlobalState: SyncedMemento;
}

export interface SyncedMemento extends Memento {

	/**
	 * List of keys whose values should be synced across devices when extensions synchronization is enabled .
	 * Set synced keys to an empty array to unset the synced state.
	 */
	syncedKeys: ReadonlyArray<string>;

}
```

**Note: `syncedGlobalState` will be removed and merged with `globalState` in `ExtensionContext once finalized**

@jrieken let me know if there are any suggestions.

**Comment by jrieken** [comment]
> Note: syncedGlobalState will be removed and merged with globalState in `ExtensionContext once finalized

Is having `SyncedMemento` only because of type-gymnastics or do you really want to introduce a new type? Also, what happened to the event? Are we still planning an adding that?

**Comment by sandy081** [comment]
> Is having `SyncedMemento` only because of type-gymnastics or do you really want to introduce a new type? 

Mainly to support `syncedKeys` only for `globalState`. As discussed in stand up, I will inline it as follows once finalised.

```
readonly globalState: Memento & {
	/**
	 * List of keys whose values should be synced across devices when extensions synchronization is enabled .
	 * Set synced keys to an empty array to unset the synced state.
	*/
	syncedKeys: ReadonlyArray<string>;
};
```

> Also, what happened to the event? Are we still planning an adding that?

Planning to add the event later.

**Comment by bwateratmsft** [comment]
This would still include the change to package.json to specify which keys to sync, right?

**Comment by sandy081** [comment]
> This would still include the change to package.json to specify which keys to sync, right?

`package.json` contribution is not needed and redundant. Extension shall update the keys using the above API.

**Comment by bwateratmsft** [comment]
If it's read-only, how do they update it?

**Comment by sandy081** [comment]
> If it's read-only, how do they update it?

`syncedKeys` is not read-only. You can update it by setting the new value.

**Comment by bwateratmsft** [comment]
You have it as a `ReadonlyArray<string>` in your proposed API. Should it actually be `readonly string[]`, which would allow adding/removing elements but not replacing the entire array?

**Comment by sandy081** [comment]
I do not think there is an easy way to listen to changes when elements are added or removed from an array. Hence went with updating the entire array for updates.

**Comment by bwateratmsft** [comment]
Good point, that makes sense. :thumbsup:

**Comment by sandy081** [comment]
Finalised following:

```
export interface ExtensionContext {
	readonly syncedGlobalState: Memento & {
		/**
		 * Set the keys whose values should be synced across devices when extensions synchronization is enabled .
		 */
		setKeysForSync(keys: string[]): void;
	};
}```

**Comment by RandomFractals** [comment]
this is great! please link to this issue in your vscode v1.51 update docs, or to better docs on this ext. state sync feature since the api link in that section is circular atm: https://code.visualstudio.com/updates/v1_51#_settings-sync
