### ISSUE TITLE
Can you put the outline on the right side alone

### ISSUE THREAD

**Issue by zzwwjjdj319** [microsoft/vscode#95204]
Can you put the outline on the right side alone? There are too many things on the left side, so you can't stop switching

**Comment by IllusionMH** [comment]
You should be able to drag sections between Action bar and Panel (near to Terminal, Output etc.) but I doubt that there is third pane to make it separate at this moment.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Aoutline
