### ISSUE TITLE
Open Settings Commands Confusion

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#95202]
These are the current commands related to opening settings:

![image](https://user-images.githubusercontent.com/2931520/79208991-18129100-7e43-11ea-95c0-e2eec773ce37.png)

In text:
* Open Default Settings (JSON)
* Open Settings (UI)
* Open Settings (JSON)
* Open User Settings
* Open Workspace Settings

I think there are a few issues here:
* Whats the difference between *Open Settings (UI)* and *Open User Settings*? I guess the first just opens the UI while the second also focuses the *User* tab (rather than the *Workspace* tab). This is confusing, why would you need *Open Settings (UI)* if there are both *Open User Settings* and *Open Workspace Settings*?
* *Open Settings (JSON)* actually opens the User Settings JSON file.
* A command is missing for opening the workspace user settings JSON file. This is already fixed in #93189.

I would love if there were these commands instead:
* Open Default Settings (JSON) *(unchanged)*
* Open User Settings (UI)
* Open User Settings (JSON)
* Open Workspace Settings (UI)
* Open Workspace Settings (JSON)

My workflow is usually that I type a combination of `settings`, `ui` or `json` and `user` or `workspace` into the command search window (and usually fail).

**Comment by sandy081** [comment]
Following commands are general commands to open Settings

- Open Settings (UI)
- Open Settings (JSON)

Following are specific commands to open specific tabs/files

- Open User Settings
- Open Workspace Settings
- Open Default Settings

**Comment by hediet** [comment]
Thanks for answering ;) I hope you're well during these crazy times!

> So I think they make sense

Technically, I agree. But I don't think it's the best user experience. I talked with a friend about it, he agreed that it is not so easy to distinguish them when you just want to open the settings, so maybe a discussion might be productive?

**Comment by SrTobi** [comment]
Also note that the keyboard settings are 2 additional menu points.

**Comment by phiresky** [comment]
i always just open random ones and hope it's the one i want :)

**Comment by sandy081** [comment]
Opened it for discussion.

**Comment by hediet** [comment]
Thanks for opening it again ;)

Another argument for why I think the `Open Settings (UI)` command is unneccessary:
There is no use case that could not use `Open User Settings` instead of `Open Settings (UI)`. Especially since `Open Settings (UI)`, from a user perspective, "randomly" opens either the user or workspace UI settings, depending on which was opened last.

I understand the separation in general and specific settings commands, but I don't think this separation contributes towards a better user experience. As a user, I often think what I want to do (what the outcome should be) and not how I want to do it. Thinking about whether to use `Open Settings (UI)` or `Open User Settings` is a question of how, as both usually have a similar outcome, in particular since the outcome of `Open Settings (UI)` is not very clear. In the end it is very important to the user whether he edits workspace or user settings.

**Comment by hediet** [comment]
I like the approach of Theia. Their settings UI does not look as good though.

There is exactly one relevant settings item (a no brainer which one to select):
![image](https://user-images.githubusercontent.com/2931520/80461597-cdf6d880-8935-11ea-9ade-57db65e2148d.png)

And from there you have the UI and both the workspace/json settings combined:

![image](https://user-images.githubusercontent.com/2931520/80461670-ec5cd400-8935-11ea-8568-440cd87dae05.png)

It writes the settings changed in the UI to either the user or the workspace json file, depending on which tab is active.

I understand something like this may not be implemented in VS Code. However, Theias user experience regarding settings is just much cleaner. Maybe just simpler settings commands in VS Code can improve that.
