### ISSUE TITLE
Change Installation Folder for extensions

### ISSUE THREAD

**Issue by simonflossmann** [Microsoft/vscode#9520]
- VSCode Version: 1.3.1
- OS Version: Windows 7

I have a very basic question. Currently the installation folder for the extensions is %USERPROFILE%\.vscode\extensions but unfortunately I not allowed to install more the 100 mb on my userprofile. Is there a possibility to change the location of the extension folder?

Best regards and thanks in advance,

Simon.

**Comment by kieferrm** [comment]
You can use `--extensionHomePath` when starting vscode from the command line.

**Comment by simonflossmann** [comment]
Please, reopen the ticket since it did not work for me. I copy the extension to C:\Project\extension. And tried to start vs code in the powershell with `code --extensionHomePath "C:\Project\extension"` but the extension are not availble. Thanks in advance 

Simon

**Comment by ptitgraig** [comment]
Indeed, not working for me either. Windows 7 32bits

**Comment by stevemaddock** [comment]
--extensionHomePath  works under windows 10 version 1703

**Comment by leonsco** [comment]
yes, --extensionHomePath works
