### ISSUE TITLE
Code 1.36.1 crashes Oracle VirtuaBox when trying to access a menu

### ISSUE THREAD

**Issue by azischler** [microsoft/vscode#95214]
Issue Type: <b>Bug</b>

VS Code running on Ubuntu in a VirtualBox machine on Windows 10.
When clicking on the menu bar, opens an empty frame and,  when clicking on the empty frame opens an error pop-up saying that the application was trying to access the address #0000, after that the VM goes down.
All applications/environments have been updated.
When VS Code 1.35 is installed the problem goes away.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 5.3.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (7 x 2903)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|11.96GB (7.31GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
project-templates|can|1.2.0
meld-diff|dan|1.0.10
vscode-markdownlint|Dav|0.34.0
githistory|don|0.6.3
gitlens|eam|10.2.1
compareit|in4|0.0.2
compare-folders|mos|0.8.0
vscode-docker|ms-|1.0.0
cpptools|ms-|0.27.0
git-merger|sha|0.4.1
markdown-preview-enhanced|shd|0.5.2
vscode-make|tec|1.0.2
mib|Ver|0.0.4
clang-format|xav|1.9.0

</details>

**Comment by deepak1556** [comment]
Is this still an issue with latest stable ? If so, can you check with `--disable-gpu` flag
