### ISSUE TITLE
C++ code is not running

### ISSUE THREAD

**Issue by frustratedsoul-cloud** [microsoft/vscode#95216]
what the fuck u dumb ass microsoft this vscode has wasted my time and yyyyyyy dont u set up everything  i am just a beginer and how come i know how to edit the launch.json and setting.json  u fuckers 
i will never use your dumbass software "vscode"
fuck developers not user friendly at all
and fuck u i lost total intrest in learning c++
thanks to u all developers

**Comment by tinyvan** [comment]
Visual Studio Code is created for production.It has a bit difficulty to learn to use.You can try some other devtools,such as Dev-C++ or CodeBlocks.
