### ISSUE TITLE
Folder listing filter

### ISSUE THREAD

**Issue by TurkeyMan** [Microsoft/vscode#9521]
- VSCode Version: 1.3.1
- OS Version: Windows + Xenial

Steps to Reproduce:

1. Open a folder, notice a tree view file listing
2. Do want a box to type a filter pattern, eg, '*.h', which would reduce the folder tree to only show files that match the filter pattern, and folder nodes leading to those files. All other files/folders hidden.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/9373
