### ISSUE TITLE
Extension Host Disabled on start up of VS Code

### ISSUE THREAD

**Issue by keyurpatel8118** [microsoft/vscode#95218]
Issue Type: <b>Bug</b>

Whenever, I start VS Code the extension host gets disabled. Therefore no extensions are working. 
In the Developer Tools the error coming is **"Error: ENOENT: no such file or directory"**

Currently I'm using March 2020 (version 1.44) of VS Code.

Please look over it.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.88GB free)|
|Process Argv|F:\Keyur\GitHub\sample|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
prettier-vscode|esb|4.3.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
vscode-auto-open-markdown-preview|hnw|0.0.4
material-icon-theme|PKi|4.0.1
LiveServer|rit|5.6.1
code-spell-checker|str|1.8.0
vscodeintellicode|Vis|1.2.6
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by alx-xlx** [comment]
**IntelliSense** has stopped working too, can someone confirm if it is due to Extension Host Disabed thingy
