### ISSUE TITLE
Opening multiple files from Ctrl+P no longer works

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#95212]
Issue Type: <b>Bug</b>

When you press Ctrl+P to search for a files, it used to be that you could press Arrow-Right to open a file without closing the menu. You could do this as many times as you wanted to open multiple files.

This no longer works. When you Arrow-Right, it replaces the previously opened file tab.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.87GB (33.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.2
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
generateuuid|Fir|0.0.5
vscode-mocha-test-adapter|hbe|2.3.0
vscode-test-explorer|hbe|2.17.0
vscode-esformatter|how|1.6.0
output-colorizer|IBM|0.1.2
code-beautifier|mic|2.3.3
vscode-lebab|mrm|2.6.0
vscode-puglint|mrm|2.3.0
vscode-kubernetes-tools|ms-|1.1.1
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.9
vsonline|ms-|1.0.1968
vscode-paste-image|mus|1.0.4
vscode-yaml|red|0.7.2

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
See also #94726

**Comment by oliversalzburg** [comment]
Thank you so much for the helpful message @vscode-triage-bot
