### ISSUE TITLE
New paste PSReadLine keybinding doesn't work in PowerShell Integrated Console

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95227]
Repro:

1. Install PS extension
2. Open the "PowerShell Integrated Console"
3. Paste in this:

```ps
if($true)
{
# asdf
}
else
{
}
```

It should look like this:

![image](https://user-images.githubusercontent.com/2193314/79232482-67919680-7e1c-11ea-8ea9-3954ccbeeaa7.png)

/cc @TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
As discussed, this is because we name the created terminal.

If we didn't name it, paste works... But that's not ideal for the PowerShell extension.

**Comment by Tyriar** [comment]
Just needs a core change to turn on the shell detection even if `name` is present. No changes on your end.

**Comment by Tyriar** [comment]
Problem line:

https://github.com/microsoft/vscode/blob/4a55d1179060689f72e8849f4120067afa37cf55/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1317-L1318

**Comment by Tyriar** [comment]
Oh I'm the author 😆

@TylerLeonhardt can you verify this when you get a chance?

**Comment by TylerLeonhardt** [comment]
@Tyriar  you may need to say it. It works.
