### ISSUE TITLE
Debug disconnect doesn't to anything

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#95228]
* this launch-config https://github.com/microsoft/vscode-github-issue-notebooks/blob/4934b2e156ac15d50d79ddaed69dbe92491a6ca2/.vscode/launch.json#L22
* attach
* disconnect
* :bug: nothing happens

**Comment by isidorn** [comment]
Works for me.
Here are my steps: I have 	
`"debug.node.useV3": true`
I run `scripts/code.sh`

From vscode insiders I run the Attach To Extension Host config
I click disconnect -> it disconnects

@connor4312 can you aslo try it out
@jrieken let me know if you do something differently

![diconnect](https://user-images.githubusercontent.com/1926584/79238462-b288c980-7e6f-11ea-944a-69c4b12d0126.gif)

**Comment by jrieken** [comment]
I have a video that's too large for my 4g connection... Please try with the my launch config

**Comment by isidorn** [comment]
I appologize, I missed that you are doing it from that repo, I thought it was from VS Code. Thus deleting my previous comment to make the discussion more concise.

I notice that VS Code is preoprly sending the disconnect to the vscode extension and it seems like the Node debugger starts the new session automatically by calling the `startDebugging` api 
@connor4312 can you please investigate what is going on the extension side.

**Comment by connor4312** [comment]
Thanks for the issue, surprised this didn't come up before. With `restart: true` js-debug wanted to try to reattach to the target even when it was killed, and depending on a race sometimes succeeded.

**Comment by jrieken** [comment]
This doesn't work. Sorry, didn't see that this was closed and was wondering when this gets fixed. I usually need to press disconnect multiple times and very quickly

[Apr-30-2020 12-18-10.gif.zip](https://github.com/microsoft/vscode/files/4557639/Apr-30-2020.12-18-10.gif.zip)

**Comment by connor4312** [comment]
Thanks for looking at this. I had fixed the case where you disconnect by clicking the button on the parent session, but when clicking on the child session we severe that specific connection which wasn't flagged as a graceful close in js-debug.

**Comment by jrieken** [comment]
This is still not disconnecting. I press the "global" disconnect button and it keeps reconnecting...

![May-01-2020 11-20-36](https://user-images.githubusercontent.com/1794099/80795806-da7d6a00-8b9d-11ea-9a71-6bfa6fb6d1f0.gif)

**Comment by connor4312** [comment]
@jrieken I didn't bump js-debug last night since it's a slightly riskier change. This should be fixed in the next Insiders next week.

**Comment by jrieken** [comment]
Ah, makes sense
