### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by iamkevalkaria** [microsoft/vscode#95226]
I did everything. I deleted all data of Visual Studio code, deleted extensions manually, on reinstalling it works at the very first instance but after turning off my PC and switching back, again same error occurs also my extension fails everytime

**Comment by tinyvan** [comment]
You can open a issue in the repository of extension.

**Comment by jrieken** [comment]
Please check if you are seeing this: https://github.com/microsoft/vscode/issues/94858
