### ISSUE TITLE
Extension Host illegal argument

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode#9522]
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open vscode. Done.

I have no idea if this is from an extension or vscode itself. The error message is too cryptic for me.

![image](https://cloud.githubusercontent.com/assets/8189808/16978929/c9f31714-4e5e-11e6-89f4-4db725c76977.png)

![image](https://cloud.githubusercontent.com/assets/8189808/16978909/a6ceb5a4-4e5e-11e6-9f1b-75849dcf804e.png)

**Comment by weinand** [comment]
@con-ssc It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by con-ssc** [comment]
@weinand seems to be the case. How can I identify which extension causes the issue?

**Comment by weinand** [comment]
@con-ssc shutdown VS Code and then temporarily move all extensions from your VS Code extension folder (I think that folder lives somewhere in AppData on Windows) into some other folder. Then move one extension back and start VS Code. Repeat this process until you've identified the one that produces the problem.

**Comment by con-ssc** [comment]
Hmm is there another way then trial and error? Maybe a more verbose logging or starting from console or something?

**Comment by weinand** [comment]
@jrieken @joaomoreno is there a better way to find the broken extension?

**Comment by con-ssc** [comment]
@weinand it is in %USERPROFIL%\.vscode-insiders problem is, I have 86 extensions+colorthemes and that would be really awful to test.

**Comment by weinand** [comment]
Only an extension with code can be the culprit. That rules out all color themes...

**Comment by con-ssc** [comment]
@weinand Using AstroGrep, the only extension file that has "publishDiagnostics" in it is the powershell one in "Microsoft.PowerShell.EditorServices.Protocol.dll" no idea if that helps

**Comment by weinand** [comment]
Then temporarily remove just that extension and verify that the problem disappears.
If this is the case please create an issue against the PowerShell extension.

**Comment by jrieken** [comment]
Yeah - looks like an issue with the _PowerShell_ extension then

**Comment by con-ssc** [comment]
Hmm, error persists after removing the powershell extension.

**Comment by con-ssc** [comment]
@weinand Found the extension that caused the error. It is Microsoft/vscode-comment @stevencl

**Comment by weinand** [comment]
@con-ssc great, and I noticed that you've already created Microsoft/vscode-comment#7. Thanks.

**Comment by con-ssc** [comment]
@weinand always a pleasure to help

**Comment by stevencl** [comment]
Unfortunately I can't repro this. I only have the vscode-comment extension installed and I do not see any errors showing up in the console. I don't make any calls to publishDiagnostics in my code.

**Comment by con-ssc** [comment]
Okay this seems to be I picked the wrong extension. I divide and conquered now every extension I had with yours and it seems to be https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint this is causing the trouble. And it is also causing it if it is the only extension.
Sorry for the trouble.

**Comment by con-ssc** [comment]
so it is back to vscode and @weinand since @dbaeumer is the author I guess.

**Comment by dbaeumer** [comment]
@con-ssc do you have any steps to reproduce this. Whay is happening is that the eslint library gives me a problem on a negative line (which of course is bogus) and we log that exception.

Will move to vscode-eslint since there is nothing vscode can do to fix this.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-eslint#120
