### ISSUE TITLE
Extension supplied JSON schema doesn't work

### ISSUE THREAD

**Issue by zogga007** [microsoft/vscode#95238]
I have an extension (private, not published) that builds on top of the native `json-language-features` and contributes a JSON schema ([validation.zip](https://github.com/microsoft/vscode/files/4476263/validation.zip)):
![image](https://user-images.githubusercontent.com/4518852/79244308-0b0f9500-7e77-11ea-9576-93360102419d.png)

It worked fine up until 1.43.2, but with 1.44.0 I get the following error:
![image](https://user-images.githubusercontent.com/4518852/79241689-ac94e780-7e73-11ea-8635-7ad3b33b59da.png)

- VSCode Version: 1.44.0
- OS Version: Win 10 Pro 1903 (18362.720)

Steps to Reproduce:

1. launch VSCode with the extension
2. check console

Obviously this can hardly be reproduced without the actual extension, but I haven't had the time yet to create a new extension that just supplies a schema to single out the issue.

Does this issue occur when all extensions are disabled?:
Yes (every extension but the one in question)

**Comment by aeschli** [comment]
What has changed is that `jsonValidation.fileMatch` can now also be an array of patterns.
Additionally, patterns can start with a `!`, which indicates that the pattern is an exclusion pattern.

You'll need to adopt the change in your code. Better add type checks for the future... :-)
