### ISSUE TITLE
Outline and notebooks

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#95234]
Currently, breadcrumbs and outline don't show anything when having a notebook open. We should come up with a way how this should work and then implement this.

**Comment by rebornix** [comment]
Agreed. While implementing Folding for cells, I actually reinvented the algorithm for markdown outlines again: finding `#` headers and use them as folding ranges. I'm wondering the outline for a notebook document is a mix of 

* Markdown headers
* Outline for the active cell, which is provided the language 

Showing outlines for every cell is a no-op IMHO as it requires creating text models for each cell.

**Comment by jrieken** [comment]
Yeah, that's the challenge here. We can have markdown define the "root structure" of outline but should happen with code cells? Showing outline for them will be expensive because models need to be created - which might already happen anyways when a smart language service is at work... We could differentiate between static outline and dynamic outline

1. static outline (in the panel and breadcrumbs): Show the structure as defined by markdown headings
2. dynamic outline (quick outline, breadcrumbs picker): Show the outline of the current cell - be it markdown or code

**Comment by andycraig** [comment]
Not sure if this is useful information or not but for R Markdown notebooks the R language server provides the outline for the whole document, markdown and code chunks included.

**Comment by jrieken** [comment]
@andycraig useful! can you point me to more information about this?

**Comment by andycraig** [comment]
@jrieken Here's a screenshot of an R Markdown (.Rmd) file. Note that the markdown headings and the function definitions in the code chunks are shown in the outline. The [R language server](https://github.com/REditorSupport/languageserver) is providing the symbols for both.

![outline](https://user-images.githubusercontent.com/23294156/79740253-54118e80-833a-11ea-9560-6f9ff923dba8.JPG)

The editor panel shows how R Markdown files are currently displayed in VS Code. The new VS Code Notebook seems like it will probably be a good fit for them. The point I wanted to highlight is that depending on the language server, it may already be providing symbols for the markdown as well as the code.

CC @renkun-ken, who implemented the handling of markdown in the R language server (as well as a lot of other features).

**Comment by renkun-ken** [comment]
Thanks @andycraig for introducing me to this discussion.

One thing to notice is that R language server is implemented in R and works for other editors that support LSP and thus is not designed specifically for VSCode.

Generally, I think mixing markdown outline and document symbols look natural and is easy for users to adopt.

**Comment by jrieken** [comment]
@renkun-ken, @andycraig Thanks for the update here. What you propose makes much sense - IMO the markdown outline should always work like that. Still, this item is specifically about notebook editors that don't show all text but markdown cells, code cells, and output (as shown below) and we wonder if a slightly different navigation is wanted

<img width="977" alt="image" src="https://user-images.githubusercontent.com/1794099/80370438-718dad80-8890-11ea-8363-b5fe13992b81.png">


What we are prototyping (!) to to is have an outline per notebooks that driven by markdown section headers and then have outline within each cell. The former should help you navigate quickly to a certain cell, the latter should help to navigate within a large cell. We we will also investigate to have a combined view of both (but due to time constraint not in the first version)

**Comment by jrieken** [comment]
I have now pushed a change that makes quick outline work for notebooks. This is different from classic document symbols and should be compared with a table of contents. 

<img width="726" alt="image" src="https://user-images.githubusercontent.com/1794099/80371679-9125d580-8892-11ea-972c-f07ae6d8f7e2.png">

@bpasero fyi this required some changes in `gotoSymbolQuickAccess.ts` but things did fit nicely into the existing "do something when not having a code editor"-flow. 

@roblourens The settings editor could also try to hook into this. That would provide some proofing of the toc-provider-concept and IMO be a neat feature


To wrap up (for this milestone): We now do have quick outline/navigation for notebooks but there are more open questions

* How does this apply to breadcrumbs and the outline-tree. Both are different because they are stable (e.g listen to change events) and are selection-sensitive?
* How does this work when mixing toc entries and classic document symbols?

**Comment by bpasero** [comment]
@jrieken saw the change, I wonder if the `ITableOfContentsProvider` should live somewhere more generic where it can also be used by breadcrumbs and outline view because imho they require the exact same information.

And then, once we have such a thing, I wonder if document symbols should just be one "TOC" provider variant. As such, the quick outline would only operate on your new registry and not go to document symbols.

Btw one thing to still adopt is support for navigating into symbols from quick open when you type `<notebook name>@<notebook symbol>`. Again, I think doing everything via the same registry would probably be the best going forward.

**Comment by jrieken** [comment]
>  I wonder if the ITableOfContentsProvider should live somewhere more generic where it can also be used by

Yeah - this should probably be some workbench service to which provider register and with with other work. I wanted to keep the change local because we don't actually know if the feature itself is in its final state or not. 

> And then, once we have such a thing, I wonder if document symbols should just be one "TOC" provider variant.

I don't see much value in that. TOC is concept of the workbench only (nothing like that standalone editor land) and it would throw us back into the two implementations world

**Comment by jrieken** [comment]
> Btw one thing to still adopt is support for navigating into symbols from quick open when you type <notebook name>@<notebook symbol>. 

For some reason this doesn't even open the notebook but the underlying file itself. Not sure why that is. Maybe missing to intercept the open request?

**Comment by bpasero** [comment]
@jrieken that sounds like a bug to me, we open the editor here, maybe you could check why it would not open your notebook:

https://github.com/microsoft/vscode/blob/2971e3a4e86f57285a572a75aa8ef15e5d28950b/src/vs/workbench/contrib/search/browser/anythingQuickAccess.ts#L770

**Comment by jrieken** [comment]
It does open (when nothing is open yet). I think you are off the hook but there is something wrong with how notebooks use the working copy service. Tho, since the anything handler uses document symbol this doesn't really work then. Needs some deeper thought next milestone, let's first validate this overall approach

**Comment by jrieken** [comment]
We have now table of contents that always for a notebook, using markdown headings and the first non-empty line of code cells. Calling is done for now and waiting for user feedback before moving on. 

@bpasero wrt the table of contents provider that I have added, we have https://github.com/microsoft/vscode/issues/97095 which I am going to use to further purse this

**Comment by jrieken** [comment]
to verify: 

1. open a notebook like GH issues notebook
1. make quick outline shows two kind of entries: markdown headers, the first non-empty line of code cells
1. make sure quick outline can be triggered via keyboard no matter where focus is
1. make sure quick outline can be triggered via F1

**Comment by JacksonKearl** [comment]
Finding that `Go to Symbol in Editor` shows the correct outline information, but the outline pane is empty? 

![image](https://user-images.githubusercontent.com/8586769/83703386-51a28580-a5c4-11ea-8cd5-a1dd28f81b61.png)

**Comment by jrieken** [comment]
>  but the outline pane is empty?

Yeah, we don't yet want to rewrite the whole outline that's why for now it is just quick outline.
