### ISSUE TITLE
Node Debug: Strange settings UI behavior

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#95231]
Couple issues:

- Node debug appears as `Node debug` and `Node Debug` in the settings UI
- Settings counts are off by one on each of those sections

![9e31d969-2f40-4b39-9082-824b6a8c6fcb](https://user-images.githubusercontent.com/22350/79240780-80c53200-7e72-11ea-9c9a-fc5af3bf3a1c.gif)

**Comment by roblourens** [comment]
This should be fixed in today's
