### ISSUE TITLE
Code Suggestions Long Delay

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode#9523]
- OS Version: Windows 10 x64

I experience that sometimes the completion suggestions have a pretty long delay. I mainly experience that in .js and .ts files. Sometime the .ts definitions are not automatically resolved until I press Ctrl+Space.

![image](https://cloud.githubusercontent.com/assets/8189808/16978985/13ddb69a-4e5f-11e6-82be-dba69b99997c.png)

**Comment by kieferrm** [comment]
@con-ssc It would be a great help if you could provide a sample workspace that exhibits that behavior as well as the file and position in file where you experience this. Thx!

**Comment by con-ssc** [comment]
I cannot force the delay, it just happens sometimes so it is hard to provide exact information about when and how and in what workspace.

**Comment by kieferrm** [comment]
@con-ssc any information about the workspace size, file size, ...? Are you developing code that uses npm like dependencies? If so, is there a certain dependency pattern? Are you running low on memory when it happens? Anything that may help to understand the issue better?

**Comment by kieferrm** [comment]
@dbaeumer feel free to close as we don't have additional info.

**Comment by con-ssc** [comment]
I have no npm modules installed. Where can I find the workspace size? The file size varies from about 40 lines to 1000 lines, doesn't seem to matter. I'm not running low on memory at all, also CPU is ok.
Is there a way to monitor the performance of the suggestion routine somehow?

**Comment by dbaeumer** [comment]
@con-ssc yes you can :-). Add the following to your settings `"typescript.tsserver.trace": "messages"` and open the Output view and switch to the TypeScript channel. This should give you a trace of the language server actions and how long they took. If you see slow code complete requests then the problem might be in the tsserver itself.

**Comment by con-ssc** [comment]
Does this exist for javascript as well?

**Comment by con-ssc** [comment]
I will keep you posted if I see anything. Would it be possible to somehow add a notification if the request time is higher than lets say 200ms or so?

**Comment by dbaeumer** [comment]
Yes, exists for JS as well. Same setting. 
No notification right now.

**Comment by con-ssc** [comment]
![image](https://cloud.githubusercontent.com/assets/8189808/17400146/9286721e-5a46-11e6-9f84-45ab3f74c683.png)

Okay I was "lucky" to have an example now.
![image](https://cloud.githubusercontent.com/assets/8189808/17400158/a80b576c-5a46-11e6-9007-97f080d18ccb.png)
![image](https://cloud.githubusercontent.com/assets/8189808/17400163/b0da2148-5a46-11e6-85f3-c48fe4a40f5d.png)

**Comment by dbaeumer** [comment]
Wow. The code complete request took ~17 seconds. I will move this to the TS team since they provide the server. @con-ssc would be great if you could share some code to be able to reproduce this.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#10133
