### ISSUE TITLE
Intellisense in Python working eratically

### ISSUE THREAD

**Issue by Trid-collab** [microsoft/vscode#95230]
We have written the needed data into your clipboard because it was 
Issue Type: <b>Bug</b>

The Intellisense in Python seems to be working eratcially, not showing up proper suggestions . Sometimes it works only when we press Crtl+Space
Sometimes it works perfectly automatically

Also it seems not work properly with Notebook Option. The suggestions which I get on normal python file is not availbale in Notebook option

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.3.71659
vscode-yaml|red|0.7.2
ayu|tea|0.18.0
vscodeintellicode|Vis|1.2.6

(1 theme extensions excluded)

</details>
too large to send. Please paste.

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Python extension. Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose
