### ISSUE TITLE
[0414/130320.699:ERROR:icu_util.cc(165)] Invalid file descriptor to ICU data received.

### ISSUE THREAD

**Issue by JoaoBueno** [microsoft/vscode#95247]
- VSCode Version: 1.44.0 (user version)
- OS Version: Windows 10.0.18363

Steps to Reproduce:

1. when I type: code .
2.[0414/130320.699:ERROR:icu_util.cc(165)] Invalid file descriptor to ICU data received.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by deepak1556** [comment]
Can you paste what the VS Code application folder contains ? This error happens when its missing the `icudtl.dat` file.
