### ISSUE TITLE
terminal tab disappears on lost focus

### ISSUE THREAD

**Issue by jaybee82** [microsoft/vscode#95242]
- VSCode Version: 1.45.0-insider
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Add new terminal [(menu) Terminal / New Terminal ]
2. New Terminal tab is created / got focused
3. select other tab (e.g. PROBLEMS or DEBUG CONSOLE)
4. Terminal tab disappears

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@jaybee82 can you screenshot your window with it disappeared? I would guess that this is just because `Problems` is taking up space and `Terminal` is in the triple-dot menu.

**Comment by jaybee82** [comment]
Ok so here are steps:

first, immediatly after start vscode, no terminal tab visible:
![image](https://user-images.githubusercontent.com/34724117/79419404-0b16ae80-7fb7-11ea-9358-f07cf6c9b4b6.png)

Then, after click [Terminal Menu] / New Terminal, everythings seems to be fine:
![image](https://user-images.githubusercontent.com/34724117/79419506-37cac600-7fb7-11ea-97ee-4671660fe520.png)

Now, after click on 'DEBUG CONSOLE' (or any other tab in this panel), terminal tab is hidden:
![image](https://user-images.githubusercontent.com/34724117/79419643-7eb8bb80-7fb7-11ea-8ee1-7ecf42344b22.png)

**Comment by giltayar** [comment]
_Exact_ same thing happens to me. I believe it started with 1.43, but I am not sure. I am currently on 1.44.1 on MacOS Catalina.

**Comment by jaybee82** [comment]
As a sidenote: terminal is not destroyed. if i click [Terminal Menu] / New Terminal one more time, tab is visible again and a new terminal is available. the 'lost' terminal is available via dropdown menu:
![image](https://user-images.githubusercontent.com/34724117/79421219-a8271680-7fba-11ea-91a7-74d93da6917b.png)

**Comment by giltayar** [comment]
Yup, same here. I just use Ctrl+` and the terminal appears again. It's just hidden (somewhere...)

**Comment by giltayar** [comment]
I found the problem! It may have been an inadvertent mistake on our side, or maybe the vscode upgrade somehow did this.

To fix it, right-click on the "Terminal" tab, and choose "Keep".

**Comment by jaybee82** [comment]
@giltayar that's it, thank you.
i never tried to hit right mouse button on any tab in this panel. maybe the default value for terminal changed?

i will close this...
