### ISSUE TITLE
Can't open new workspace from the command line

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9524]
> from #4015 by qapi 
- OS Version: OS X

Steps to Reproduce:
1. Run `code folder_1`: Code editor will open on `folder_1`
2. Without closing editor run `code folder_2`: Code editor will not open on `folder_2`, but instead it will focus on editor with `folder_1`

Another example:
1. Run `code folder_1`: Code editor will open on `folder_1`
2. Close editor but do not quit application
3. Run `code folder_2`: Code editor will not open on `folder_2` instead it will open editor with `folder_1`

**Comment by joaomoreno** [comment]
@qapi What version of Code are you using btw?

**Comment by qapi** [comment]
I am running 1.3.1 on both computers where I tested it.

**Comment by qapi** [comment]
I can gather more informations if needed?

**Comment by joaomoreno** [comment]
Absolutely. Can you try our [Insiders release](https://code.visualstudio.com/insiders), install the CLI command from the command palette and try it there?

**Comment by qapi** [comment]
I tried Insiders release ```Version 1.4.0-insider (1.4.0-insider)``` and I can't reproduce problem with it. However, stable version ```1.3.1``` still have same issues.

**Comment by joaomoreno** [comment]
Good news. Seems to be some strange setup with your stable configuration. Strange to ask, but I'm guessing it still reproduces after a machine reboot?

And you are absolutely sure the alias is not configured right? `which code` will give you the answer to that.

**Comment by qapi** [comment]
That command gives me ```/usr/local/bin/code``` output.

**Comment by joaomoreno** [comment]
- It still reproduces after a machine reboot?
- Both computers you tested it on have **exactly** the same problem?
- Do the folders you try to open have any special characters in them (spaces, etc)?

**Comment by qapi** [comment]
Yeah it does reproduce after machine(s) reboot on both machines exactly same issue. There are no special characters in name of folders or on path. Maybe it's not related and it sounds not related but I will mention it again: I believe I started experiencing problem after I encrypted hard drive on computer(s). It's called FileVault (on OSX).

**Comment by joaomoreno** [comment]
@vsrc Is this still an issue?

**Comment by vsrc** [comment]
@joaomoreno unfortunately it is still an issue including with version ```1.6.1``` However insiders version works fine this all time 😕  🤔  really wierd. I switched fully to use insiders version.

**Comment by joaomoreno** [comment]
Closing as insiders fixed it for user.
