### ISSUE TITLE
VSCode terminal remains hidden while it downloads extensions

### ISSUE THREAD

**Issue by abhijeetmanhas** [microsoft/vscode#95259]
- VSCode Version:1.43.1
- OS Version: Linux Ubuntu 18.0.4 LTS x86_64

Steps to Reproduce:

1. Open VSCode window in half size of screen
2. Reinstall any extension
3. Use terminal
4. You can't see your commands you run on terminal while extension is being installed

Does this issue occur when 

all extensions are disabled?: Yes, when we click on install extension again this issue appears

**Comment by chrmarti** [comment]
Please update to 1.44 and confirm the problem still exists.

**Comment by abhijeetmanhas** [comment]
Still exists, wait let me upload a screenshot

**Comment by abhijeetmanhas** [comment]
![Screenshot from 2020-04-14 23-41-20](https://user-images.githubusercontent.com/43112347/79495889-e8ca7280-8042-11ea-86e3-04ae8704bce2.jpg)

**Comment by abhijeetmanhas** [comment]
This is how it looks like, as you can see, we can't use terninal

**Comment by bpasero** [comment]
@abhijeetmanhas are you saying the notification comes back all the time even if you press Escape?

**Comment by abhijeetmanhas** [comment]
Oh I didn't tried escape button, I actually thought there might me a cross button in notification bar, but found none. Let me check if escape works.

**Comment by abhijeetmanhas** [comment]
Escape works, thanks it disappears when we press esc
