### ISSUE TITLE
Add prompting commands for managing selected tsdk

### ISSUE THREAD

**Issue by DuncanWalter** [microsoft/vscode#95250]
👋 It would be fantastic if my team could point workspaces to a specific version of typescript bundled with our internal extension. This behavior matches other extensions which use global installs or binaries like Flow Language Support when **not** configured to run flow binaries found in the workspace.

This issue is related to but more limited in scope than [#65546](https://github.com/microsoft/vscode/issues/65546). I understand that configuration on disk in a repo should be forbidden from determining which tsdk will run without manual approval. I think the utility I need can be provided without compromising that security by adding a pair of commands to the builtin typescript language features extension:

- `setTsdkPath`: takes a path as an argument, prompts the user for confirmation, returns void. Updates the workspace setting `tsdk` as well as the internal flag to enable use of workspace tsdks for that workspace
- `getTsdkPath`: returns a path to the currently active tsdk (alternatively, make setTsdkPath no-op if the given path matches the current path)

With these commands, extensions could automate the process of picking the right tsdk, and prompt the user to confirm when it would be changed. This does change the flow from opt-in to opt-out in some sense, so it might also be necessary to add a user level opt-in to "enable" these commands 🤷‍♂️.

I'd be happy to take a stab at implementing these features, but I want to get a thumbs-up from the team and confirm there aren't existing workarounds first.

cc @mjbvz based on responses to previous issues

**Comment by mjbvz** [comment]
Can you explain the use cases for this over using the workspace version of TypeScript or having everyone on your team set `typescript.tsdk` as a user setting (i.e. globally)?

**Comment by DuncanWalter** [comment]
Sure!  TLDR is we use a lightly patched version of TypeScript internally, and have enough engineers that it's worth our time to smooth over any of the devex problems/confusion caused by versioning it. 

Our frontend engineers use an internal package manager which has different file resolution than node. We maintain a patch for Typescript that resolves dependencies for this package manager and has a peer dependency on another internal tool. This means 
- we distribute our version of TS to be used when working on JS projects which don't have a usable TSDK in the workspace (to leverage TS for intellisense)
- we don't want to set any tsdk globally because it can't be used when working on traditional node projects, thus reintroducing the need for a workspace TSDK in JS projects
- we want to make sure the TS version distributed is paired with the correct version of its peer dependency

Asking our ~200 engineers to manage all of this by hand is impractical because the path to our TSDKs won't show up in the `Select TypeScript Version` prompt when it's not in the workspace, and the invisible `typescript.useWorkspaceVersion` setting is generally confusing.  #65546 and all its related/duplicate issues are evidence that this is a pain point even without the extra complexity of our patch- we need a solution that is painless over time and requires no education.

**Comment by mjbvz** [comment]
Thanks for the explanation.

Can your extension write the user's `typescript.tsdk` setting to point to the the TS version it ships?

**Comment by DuncanWalter** [comment]
> we don't want to set any tsdk globally because it can't be used when working on traditional node projects, thus reintroducing the need for a workspace TSDK in JS projects

A lot of us are switching between repos that use traditional node and internal apps frequently. We can't use the internal version of TS in traditional node contexts because neither flavor of TS should allow resolution of the other variety, and we can't easily pass configuration to tsserver when we don't have tsconfigs on disk in JS repos.

Less important, but the user setting also introduces another issue when we try to release a new version of the extension with a new TS version. So long as vscode windows remain open on an older version, they could "fight" for control of the setting.

**Comment by mjbvz** [comment]
I'm not inclined to add features that are specific to one company's setup (especially if such features could cause headaches if misused). That's why I suggest you look into writing an extension write the `tsdk` setting. That more or less is what `setTsdkPath` would do anyways

**Comment by DuncanWalter** [comment]
👋 hello again. Not wanting to add complexity is reasonable, so I spent some time trying to simplify this a bit further. I _think_ `__getTsdkPath` alone or even a way to read the `typescript.useWorkspaceVersion` flag would work for my case. I wasn't able to find a compelling way to achieve either of these with the current vscode API, but maybe I wasn't looking in the right places. Do you know of a way to achieve one of those effects without abusing sqlite or parsing output from `ps` off the top of your head? If not, would you be more open to a change that only added one of these effects either as a command or directly in the typescript-language-features extension api?

**Comment by mjbvz** [comment]
If your extension writes to the user's `typescript.tsdk`, then that version is what VS Code will use for IntelliSense (unless the user has explicitly selected to use the workspace version).

I believe you can tell your users never to use the workspace version of TypeScript if they are opening a workspace that requires the special TS version. That would allow your extension to specify which TS version to use by setting the `typescript.tsdk` setting on a user level

**Comment by DuncanWalter** [comment]
Again, that won't work because the setting needs to change depending on the workspace. For example, I have 7 vscode windows open right now,  3 of which shouldn't use our internal version of TypeScript. I understand that the user setting bypasses the `typescript.useWorkspaceVersion` check- that doesn't solve our use case

**Comment by mjbvz** [comment]
Makes sense. 

It still does not feel right to add functionality to VS Code to workaround a company specific problem. I'll keep the issue open for further feedback but without broader use cases, I think you're going to have to find a different way to workaround this.

We're more likely to implement #65546. We haven't prioritized it because not many users are actually using workspace TS versions and we need to be sure whatever we come up with would not make users less safe when opening untrusted workspaces

**Comment by DuncanWalter** [comment]
I'd be happy to make a PR for the implementation of that feature instead if it's helpful

**Comment by mjbvz** [comment]
For #65546?

**Comment by DuncanWalter** [comment]
For your comment about a workspace option that prompts: https://github.com/microsoft/vscode/issues/65546#issuecomment-451338003

**Comment by mjbvz** [comment]
Good to hear. My expectation for the prompt:

- Users should only ever see the prompt if they open a workspace that explicitly has workspace a `typescript.tsdk` setting
- The prompt should make it clear that code from the workspace is going to be run.
- Accepting the prompt should switch to the workspace version of TS and remember my decision (the same as manually switching to the workspace version today)
- There should be a way to dismiss the prompt so that it does not show up again in the workspace

Let me know if you have any questions about the structure of the TypeScript code or the feature design tiself

**Comment by DuncanWalter** [comment]
👍 Sounds good.

Just to address some ambiguity up front: 

I'm interpreting this to mean that the existing tsdk picker won't need to be displayed in order for a user to accept the workspace tsdk setting- is that what you were thinking?

> Users should only ever see the prompt if they open a folder that explicitly has a workspace typescript.tsdk setting

I was imagining that adding the setting to an already open window would trigger the prompt as well (assuming all other conditions are met). Seem reasonable?

**Comment by DuncanWalter** [comment]
The commands in this issue would introduce duplicate functionality now that https://github.com/microsoft/vscode/pull/95566 is merged. Use `enablePromptUseWorkspaceTsdk` instead.
