### ISSUE TITLE
Allow user-configurable indent in Explorer to indicate nesting in directories

### ISSUE THREAD

**Issue by KevinBuchs** [microsoft/vscode#95253]
I would like to be able to control the amount of indent in Explorer to indicate directory nesting. The indent is too small for me and makes it hard to distinguish the indent. 

![Screenshot from 2020-04-14 12-06-08](https://user-images.githubusercontent.com/53194155/79253188-65ddc800-7e48-11ea-8b9e-c020021d761f.png)

I cannot quickly determine what is nested in the above example. Ideally, I would be able to control the constant used to provide the indent via settings.

**Comment by IllusionMH** [comment]
/question

It's already there - `workbench.tree.indent` 😄

**Comment by ArturoDent** [comment]
See, e.g., https://stackoverflow.com/questions/55310734/how-to-add-more-indentation-in-the-explorer-file-tree-structure/55315106?r=SearchResults&s=5|43.8354#55315106
