### ISSUE TITLE
Error updating vscode - Windows 10

### ISSUE THREAD

**Issue by srinivasrk** [microsoft/vscode#95257]
- VSCode Version: 1.43.2
- OS Version: Windows 10

Steps to Reproduce:
On windows vscode promots update now and when trying to update it craps out with an error.
I've reinstalled vscode completely and still face this.

![image](https://user-images.githubusercontent.com/11569731/79258224-cffe6900-7e58-11ea-9e2d-50660a588e0c.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by 0xicl33n** [comment]
- VSCode Version: 1.44
- OS Version: Windows 10 Pro

I just had this problem. I had to close malwarebytes and rerun a downloaded installer, then it worked.

![image](https://user-images.githubusercontent.com/2192160/79259682-f369e980-7e41-11ea-9605-77d888f13b26.png)

It seems malwarebytes "locks" `%appdata%` and makes the application look like its not installed anymore 

![image](https://user-images.githubusercontent.com/2192160/79259804-257b4b80-7e42-11ea-8447-b099bdb6550a.png)

**Comment by srinivasrk** [comment]
Ouch! My laptop is connected to my work domain and I don't think I can
disable the Malwarebytes or any other antivirus software. Any workarounds?

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
