### ISSUE TITLE
Autocomplete not work in multiline edit

### ISSUE THREAD

**Issue by erica-zhou** [Microsoft/vscode#9525]
- VSCode Version: 1.3.1
- OS Version: OSX10.11

Steps to Reproduce:
shows like gif
![tmp](https://cloud.githubusercontent.com/assets/8351089/16980311/f7682390-4e97-11e6-9cae-29464ec7270d.gif)

**Comment by kieferrm** [comment]
Works in the latest insider build (1.4.0):

![multicursor](https://cloud.githubusercontent.com/assets/4674940/16992492/6a9c46f0-4e54-11e6-864d-95e2b122f523.gif)
