### ISSUE TITLE
The terminal process terminated with exit code: 4294901760

### ISSUE THREAD

**Issue by krishnalrsc** [microsoft/vscode#95258]
The terminal process terminated with exit code: 4294901760

**Comment by chrmarti** [comment]
What were you doing at the time?

**Comment by Tyriar** [comment]
Do you have anti-virus software that could be blocking it? https://code.visualstudio.com/docs/editor/integrated-terminal#_how-do-i-fix-the-errors-connectnamedpipe-failed-windows-error-232-or-terminal-exited-with-code-x-on-windows

Also you've left out any version information (vscode and OS).

**Comment by krishnalrsc** [comment]
> What were you doing at the time?

just practicing python
