### ISSUE TITLE
Define keybinding button should match blue button style used elsewhere

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95268]
We don't use round corners anywhere else:
![image](https://user-images.githubusercontent.com/2193314/79271858-5913a100-7e55-11ea-82bc-b664058b2796.png)

Can we match this?
![image](https://user-images.githubusercontent.com/2193314/79271871-60d34580-7e55-11ea-857e-05601e3689d4.png)

**Comment by sandy081** [comment]
This also changes all other similar buttons using floating click widget.

<img width="224" alt="image" src="https://user-images.githubusercontent.com/10746682/98003316-e701aa00-1dee-11eb-8b1a-4543354a1bad.png">

<img width="172" alt="image" src="https://user-images.githubusercontent.com/10746682/98003359-f3860280-1dee-11eb-93c2-f33ae0a5919f.png">
