### ISSUE TITLE
TypeScript build task fails when path to tsconfig.json file has spaces

### ISSUE THREAD

**Issue by terryaney** [microsoft/vscode#95261]
Issue Type: <b>Bug</b>

I couldn't comment on existing issues, but I'm still having the same problems as mentioned in these issues:

https://github.com/microsoft/vscode/issues/38408

https://github.com/microsoft/vscode/issues/36588

My output:

```
> Executing task: """c:\Users\terry.aney\OneDrive - Conduent\TS\Tutorial\node_modules\.bin\tsc.cmd" -p "c:\Users\terry.aney\OneDrive - Conduent\TS\Tutorial\Server\tsconfig.json""" <


'""c:\Users\terry.aney\OneDrive' is not recognized as an internal or external command,
operable program or batch file.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

```
Feel free to remove this issue and reopen other(s) if that is proper channel.

Version: 1.44.0 (system setup)
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-07T23:31:18.860Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.94GB (50.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.21.17
vscode-nuget-gallery|pat|0.0.9

</details>

**Comment by Tyriar** [comment]
This works when the default shell is Windows PowerShell or cmd.exe, but not PowerShell (core):

```
> Executing task: 'e:\Playground\Space folder\node_modules\.bin\tsc.cmd' -p 'e:\Playground\Space folder\tsconfig.json' <


ParserError: 
Line |
   1 |  'e:\Playground\Space folder\node_modules\.bin\tsc.cmd' -p 'e:\Playgro …
     |                                                         ~~
     | At line:1 char:56 + 'e:\Playground\Space folder\node_modules\.bin\tsc.cmd' -p 'e:\Playgro … +                                                        ~~
Unexpected token '-p' in expression or
     | statement.  At line:1 char:59 + … e_modules\.bin\tsc.cmd' -p 'e:\Playground\Space folder\tsconfig.json' +                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected
     | token ''e:\Playground\Space folder\tsconfig.json'' in expression or statement.

The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

`basename === 'powershell'` probably needs to be `basename === 'powershell' || basename === 'pwsh'` to fix.

Windows PowerShell for comparison:

```
> Executing task: & 'e:\Playground\Space folder\node_modules\.bin\tsc.cmd' -p 'e:\Playground\Space folder\tsconfig.json' <

error TS18003: No inputs were found in config file 'e:/Playground/Space folder/tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '[]'.


Found 1 error.

The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```
