### ISSUE TITLE
Caching issue related to extension folder path that affects Extension Host initialization

### ISSUE THREAD

**Issue by mike-grayhat** [microsoft/vscode#95269]
- VSCode Version: 1.44.1
- OS Version: Windows 10
- Does disabling all extensions (excluding remote ext) help: No

Seems like I have a weird caching issue related to extension path that affects Extension Host initialization - it doesn't start correctly if I run a fixed extension (that had been broken at some point), but it works flawlessly if i just copy the whole extension folder and run it from there with no changes to the code. I'm using a remote ubuntu server as the environment. At some point the extension stopped working, maybe it's related to "net" package in npm which we added accidentally and corporate proxy on the remote host. But even after the errors and proxy configs got fixed, the extension still keeps failing - the error seems to be related to wrong initialization of extension host since I see in web console of running extension window a lot of connection / reconnection logs to ehost with `Error received from starting extension host -> timeout` and the terminal doesn't start either. Additionally if I call Extension Host restart from extension development window the extension manages to load, but the restart broke the connection between development / running extension instances (not a big deal, but definitely not a normal development workflow). From my perspective there is something related to extension hashing based on extension folder path and ehost keeps reusing my old broken extension no matter what.

Steps to Reproduce (in a nutshell, it's hard to provide the code since the bug itself is very fragile and I failed to pinpoint it):

1. Break an extension (Extension Host doesn't work, terminal doesn't start)
2. Fix it
3. Try to run it and assure it doesn't work still (even after `rm ~/.vscode_server && killall node`, removing `out` and reinstalling npm packages on remote host)
4. Copy the whole extension folder to another directory `cp my-ext my-ext2 && cd my-ext2` and run it from there and assure that it's working.

**Comment by mike-grayhat** [comment]
Seems like I found the reason why extension host didn't start properly in my case - it happens if I add a breakpoint in the activation function. EHost still fails to start properly even if I disable (not remove) the breakpoint, which I did and forgot about it.

**Comment by chrmarti** [comment]
Not sure I understand. Could you file a new issue for the remaining problem?
