### ISSUE TITLE
Per file Open in editor

### ISSUE THREAD

**Issue by havra** [microsoft/vscode#95262]
Issue Type: <b>Feature Request</b>

Open in editor should have an option per file.

Repro steps
Search for content on all open files;
The content you need is on a file in the middle of the list;
Click in Open in Editor;

Verified Results
A long text file will be generated with information from several files that are irrelevant to my search;
I need to do another search on the result file to reach to my data;

Expected Results
Great to have "Open in editor" for all files and there are tons of good uses for it.
Would expect to be able to be able to have "Open in editor" only the results of one file for situations where I have multipe log files opened and I'm interested on the search results of a single file.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

**Comment by roblourens** [comment]
Sorry I don't really understand what you are asking for. What is "open in editor"?
