### ISSUE TITLE
Regression after 1.44.1-1586789296 in place upgrade - Cell execution (Ctrl-Enter) launches broken Python Interactive Window

### ISSUE THREAD

**Issue by rhy-ama** [microsoft/vscode#95265]
- VSCode Version: 1.44.1-1586789296_amd64.deb upgraded via apt
- OS Version: Ubuntu 18.04.1 5.3.0-42-generic
- Vanilla install python 3.7.6 64-bit as per VS docs, ms-python.python VS extension 2020.3.71659 / 

Steps to Reproduce:

1. Upgade working 1.44 Code install via ```apt-get --only-upgrade install code```
```
$ sudo apt-get --only-upgrade install code
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be upgraded:
  code
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 60.7 MB of archives.
After this operation, 1,024 B of additional disk space will be used.
Get:1 https://packages.microsoft.com/repos/vscode stable/main amd64 code amd64 1.44.1-1586789296 [60.7 MB]
Fetched 60.7 MB in 8s (7,141 kB/s)                                                                                                                                                                                
(Reading database ... 208770 files and directories currently installed.)
Preparing to unpack .../code_1.44.1-1586789296_amd64.deb ...
Unpacking code (1.44.1-1586789296) over (1.44.0-1586345345) ...
Setting up code (1.44.1-1586789296) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
```
2. Open empty Python file,  create a cell, launch cell via Ctrl-Enter, Python Interactive window opens empty (jupiter notebook not launched)

Does this issue occur when all extensions are disabled?: Yes/No

Not relevant

**Comment by rhy-ama** [comment]
PS: Finally got the window launched after repeatedly opening/closing Python interactive window and pointing to different cells in a py file

**Comment by chrmarti** [comment]
/causedByExtension

Not sure which Python extension this is. Please file an issue for the extension you are using.

**Comment by rhy-ama** [comment]
@chrmarti thank you. i shall after further testing, if necessary. 

the plugin is microsoft's ```Python extension for Visual Studio Code``` 

CC microsoft/vscode-python#11171
