### ISSUE TITLE
vscode Extension with edge Problem

### ISSUE THREAD

**Issue by 928PJY** [Microsoft/vscode#9527]
####OS Version:win10 x64

Hello Guys,

In vscode extension ,when I require npm package edge , I got some error ,So any help would be appreciated

In the beginning , I got a error as followed:

    Activating extension `test` failed: %1 is not a valid Win32 application.
    c:\Git\test\node_modules\edge\lib\native\win32\ia32\4.1.1\edge_nativeclr.node.
    Activating extension `test` failed:  %1 is not a valid Win32 application.
    c:\Git\test\node_modules\edge\lib\native\win32\ia32\4.1.1\edge_nativeclr.node
    Here is the error stack:  Error: %1 is not a valid Win32 application.
    c:\Git\test\node_modules\edge\lib\native\win32\ia32\4.1.1\edge_nativeclr.node
        at Error (native)
        at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:140:20)
        at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:140:20)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.n._load (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:20:23186)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (c:\Git\test\node_modules\edge\lib\edge.js:48:8)
        at Module._compile (module.js:434:26)

Then I drop the package and run  the command "npm install edge --arch=ia32" ,and then I got a error :
    
    The specified module could not be found.
    \\?\e:\Docfx\test\extensionTest\jscallTest\node_modules\edge\lib\native\win32\ia32\5.1.0\edge_nativeclr.node

and there are a error happen we I reinstall the package

    Activating extension `jipe.jscall2` failed: Module did not self-register..
    Activating extension `jipe.jscall2` failed:  Module did not self-register.
    Here is the error stack:  Error: Module did not self-register.

Any guidance would be appreciated!

**Comment by kieferrm** [comment]
Please provide source code of minimal extension showing the issue, the version of VS Code, the way how you activated the extension (launching out of VS Code, side install, etc.).

**Comment by 928PJY** [comment]
I'm sorry I did not express clearly , the version of VS code is 0.11.0 , and I use the command "yo code" to generate a demo extension .Here is the package.json file
    
    {
        "name": "jscall2",
        "displayName": "jscall2",
        "description": "call c# in js",
        "version": "0.0.1",
        "publisher": "jipe",
        "engines": {
            "vscode": "^1.0.0"
        },
        "categories": [
            "Other"
        ],
        "activationEvents": [
            "onCommand:extension.sayHello"
        ],
        "main": "./extension",
        "contributes": {
            "commands": [{
                "command": "extension.sayHello",
                "title": "Hello World"
            }]
        },
        "scripts": {
            "postinstall": "node ./node_modules/vscode/bin/install"
        },
        "dependencies": {
            "edge" : "^5.9.2"  
        },
        "devDependencies": {
            "vscode": "^0.11.0"
        }
    }

this is same as the vscode extension demo except the dependencies. and when I require the 'edge' and debug the process,I got a error  
    ![pi1](https://github.com/928PJY/learngit/raw/master/1.png)
and it jump to to the Exception catch in the file module.js
    ![pi2](https://github.com/928PJY/learngit/raw/master/2.png)

Finally, I got a error as followed

    Loading development extension at e:/Docfx/test/extensionTest/jscall2
    Activating extension `jipe.jscall2` failed: Module did not self-register..
    Activating extension `jipe.jscall2` failed:  Module did not self-register.
    Here is the error stack:  Error: Module did not self-register.
        at Error (native)
        at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
        at Object.Module._extensions..node (module.js:440:18)
        at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Function.n._load (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:11:29921)
        at Module.require (module.js:367:17)
        at require (internal/module.js:16:19)
        at Object.<anonymous> (e:\Docfx\test\extensionTest\jscall2\node_modules\edge\lib\edge.js:53:8)

Thanks!

**Comment by 928PJY** [comment]
And I use the module 'edge' because I want to call a C# dll in the extension write in JavaScript or Typescript ,so any help would be appreciated!!

**Comment by kieferrm** [comment]
Thanks @928PJY.  Having a simple project that does nothing else rather than loading edge everything works fine but loading the module in the extension host fails. 

@jrieken  any opinions?

**Comment by 928PJY** [comment]
Yes  ,but I think it is maybe the problem of the module 'edge'  ,It has some C++ code in this module. I have change it to the 'electron-edge'  , and it works! 
Thanks!

**Comment by jrieken** [comment]
Yes - 'edge' is a native extension that is compiled against nodejs, not electron. To make it work with the latter you need a recompiled version
