### ISSUE TITLE
Jupyter Enhancement

### ISSUE THREAD

**Issue by jpezzillo** [microsoft/vscode#95278]
I'm a big fan of the data viewer capability when using jupyter notebooks in vscode. It would be awesome if you could refresh the dataframe you're looking at with another button next to filter rows. Current state, you have to close the dataframe, and open it back up in data viewer to refresh. 

![image](https://user-images.githubusercontent.com/33739716/79285843-b545e780-7e8c-11ea-84d3-58baae823b16.png)

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Python extension. Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose
