### ISSUE TITLE
Error when updating from ppa on Ubuntu

### ISSUE THREAD

**Issue by danrneal** [microsoft/vscode#95271]
- VSCode Version: 1.44
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. `sudo apt update`

```
Failed to fetch http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2  File has unexpected size (171612 != 171467). Mirror sync in progress? [IP: 13.90.21.104 80]
   Hashes of expected file:
    - Filesize:171467 [weak]
    - SHA512:f7d4a72db6bf2c81806cd506353b68da7d57bc69b72a01695ac44fc18494a6c17987c48cfcb806bbdef5966372d8c2550a8f0e7d9ceb54c270827dc362763263
    - SHA256:1bea87fa36b58bc034d153c00cebf03c46303c6ef175e97df86bc63c6503ce91
    - SHA1:d4ca05c3b67cf15caf07bf9c17dc18403292ac6b [weak]
    - MD5Sum:ab7bb7a48f70850c05a4f647d3db704d [weak]
   Release file created at: Tue, 14 Apr 2020 17:11:00 +0000
```

**Comment by DamianRivas** [comment]
I'm having the same issue too. I can't run `apt update` because of this.

**Comment by SinaKarimi7** [comment]
same #77029

**Comment by SinaKarimi7** [comment]
I have this too. same #77029

**Comment by bruno-silva5** [comment]
Same issue here, can't run `apt-get update`

**Comment by tan9** [comment]
This kind of issues happens quietly often, a simple search comes out following results:

#86858 Dec 13, 2019
#77029 Jul 10, 2019
#74826 Jun 4, 2019
#70584 Mar 16, 2019
#66339 Jan 10, 2019
#66238 Jan 9, 2019
#42313 Jan 29, 2018
#41117 Jan 4, 2018
#41094 Jan 3, 2018
#25883 May 4, 2017

Maybe there is something wrong on the release process, I never met the same problem on all of my 20+ other apt repositories.

**Comment by RecodeExistence** [comment]
I have the same issue right now.  Used insider to test against, same problem.  
Possible server sync related?  

I put a post about it up.. will delete as duplicate.  

Please advise.  Things like unexpected filesizes compared to what's expected makes me antsy.

**Comment by tan9** [comment]
A workaround mentioned in https://github.com/microsoft/vscode/issues/45868#issue-305578099 is to download `.deb` from the [official site](https://code.visualstudio.com/download) and install manually.

**Comment by RecodeExistence** [comment]
> A workaround mentioned in [#45868 (comment)](https://github.com/microsoft/vscode/issues/45868#issue-305578099) is to download `.deb` from the [official site](https://code.visualstudio.com/download) and install manually.

Initially tried this.  

However... error no longer exists for me. Can anyone else confirm?  I'm hoping it was just a glitch in the matrix.

**Comment by danrneal** [comment]
All fixed for me too!
