### ISSUE TITLE
Add refactoring tools to editing in .ipynb file mode

### ISSUE THREAD

**Issue by rafwaf** [microsoft/vscode#95273]
Simple request: to add the wonderful refactoring tools that are available in the .py mode to the .ipynb mode.

Obviously implementing it will not be simple. But I think that's probably all the detail necessary for this feature request.

**Comment by chrmarti** [comment]
/causedByExtension

This is functionality provided by the Python extension. Please file a new feature request for it: https://github.com/microsoft/vscode-python/issues/new/choose
