### ISSUE TITLE
Emmet styles link not working with tab

### ISSUE THREAD

**Issue by RLWade** [microsoft/vscode#95277]
Issue Type: <b>Bug</b>

Hello. I am a new user. today inserting a css/styles.css link stopped generating when using tab.

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
    <link 
    </style>
</head>
<body>
    
</body>
</html>

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A10-7800 Radeon R7, 12 Compute Cores 4C+8G  (4 x 3491)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.95GB (2.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by effinrich** [comment]
> Issue Type: Bug
> 
> Hello. I am a new user. today inserting a css/styles.css link stopped generating when using tab.
> 
> <title>Document</title> <style>
> VS Code version: Code 1.44.1 ([a9f8623](https://github.com/microsoft/vscode/commit/a9f8623ec050e5f0b44cc8ce8204a1455884749f), 2020-04-11T01:48:12.622Z)
> OS version: Windows_NT x64 10.0.18362
> 
> System Info
> Extensions: none

I'm also having this issue today in addition to format on save no longer working.  In fact, no formatting is working as of today.  No changes on my end.

**Comment by chrmarti** [comment]
Is there anything in the console? (`Help` > `Toggle Developer Tools`)
