### ISSUE TITLE
Copy and paste from VScode to Excel replaces spaces with non-breaking spaces in .sh files

### ISSUE THREAD

**Issue by bhanratt** [microsoft/vscode#95274]
- VSCode Version: 1.44.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Create a new file in vscode with the .sh file extension or open an existing one.
2. Insert any words with a space character in that file. (for example I put the line `foo bar`).
3. Copy that line into excel. Then copy and paste the space character from excel into a unicode converter (e.g. https://www.branah.com/unicode-converter) 
4. It should return   `\u00a0` which is the non-breaking space in UTF-16

I am not sure if this happens in other file-types in VScode. I have only noticed it in .sh files. I have only noticed this starting today, and I believe my VScode updated today. As to why am copying things from .sh files to excel, I just happened to have a useful excel formula saved as a comment in a shell script. I tried reproducing these steps in Sublime-Text and did not have the problem.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by ComputerCarl** [comment]
I am also experiencing this issue with code pasted from OneNote 2016. My [issue filed in vscode-docker](https://github.com/microsoft/vscode-docker/issues/1884).

Pasting formatted text from OneNote will produce non-breaking spaces until cleaned with a service like pastebin.

**Comment by rebornix** [comment]
It's caused by copy/paste with syntax highlighting, you can disable it by `editor.copyWithSyntaxHighlighting`
