### ISSUE TITLE
Newline break syntax highlighting with const { ... } = this.props

### ISSUE THREAD

**Issue by janhartmann** [Microsoft/vscode#9528]
- VSCode Version: 1.4.0-insiders
- OS Version: Windows 10

When you have `const { map, coordinate } = this.props` in one line the syntax highlighting works fine for the document, but if you do:

```
const { 
    map, 
    coordinate 
} = this.props
```

The syntax highlighting breaks for the rest of the document:

Fine:
<img width="683" alt="syntax-highlight-fine" src="https://cloud.githubusercontent.com/assets/1107383/16980642/56a37f52-4e67-11e6-99b3-233596a93020.PNG">

Broken:
<img width="656" alt="syntax-highlight-broken" src="https://cloud.githubusercontent.com/assets/1107383/16980641/56a25cf8-4e67-11e6-989f-4e3c195224fc.PNG">

Notice `if` and `var`.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#219
