### ISSUE TITLE
The number of errors announced by the screen reader is not always compatible with the number of errors displayed.

### ISSUE THREAD

**Issue by jvesouza** [microsoft/vscode#95283]
Issue Type: <b>Bug</b>

1. Launch orca, I don't know if it happens with other screen reader.
2. Create in vscode a java script file.
3. Place in the file the following lines:
lvar x
lvar y
4. Press ctrl+shift+m and use up and down to explore the list displayed.

Three lines are displayed, with the first line containing the number of errors, in our case 2.
5. Fix the error of the first line by removing the letter l at the beginning of the line.
6. Repeat the step 4.
Two lines are displayed as expected but the first line still reports that there are 2 errors.
CC @isidorn 

VS Code version: Code - Insiders 1.45.0-insider (92ff20ac39c7507fdf4164e2bedfdfb700805fe1, 2020-04-14T18:11:49.145Z)
OS version: Linux x64 5.6.3-arch1-1

**Comment by isidorn** [comment]
@jvesouza great catch. Yes I can reproduce this also with VoiceOver.

@sandy081 it seems like you do some caching of the aria label? Or do you not refresh the whole parent (filename) when the number of errors in the file change? If you refresh the tree element the tree should ask you again for the `aria-label`. Can you look into this or provide a code pointer so I take a look. Thanks!

**Comment by sandy081** [comment]
@isidorn I do not think I am doing any caching and I guess I just refresh the children (or markers) of the resource. May be the tree is not re-rendering the parent / resource.

Not sure if I can look into this immediately but here is the code pointer if interested to debug - 

https://github.com/microsoft/vscode/blob/2548906f4c2d4f5c5a1e59af79aa7ba5cbe74244/src/vs/workbench/contrib/markers/browser/markersView.ts#L303

**Comment by isidorn** [comment]
@sandy081 Thanks for the pointer. I have pushed a fix after a consult with @joaomoreno 
We now re-render also the parent element so the aria-label gets updated.

@jvesouza you can try it out with VS Code insiders from Monday and let us know if it is good for you know. I checked it out and it seems fine for me now

**Comment by jvesouza** [comment]
@isidorn  It looks great! Thanks.
