### ISSUE TITLE
Call hierarchy shows wrong result at first

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#95288]
Version: 1.44.1 (system setup)
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:48:12.622Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
Steps to Reproduce:

1. Click show call hierarchy

From the gif you can see at first, the results are actually outgoing calls, but VS Code shows them as incoming calls.
![demo](https://user-images.githubusercontent.com/6193897/79295882-75bee000-7f0c-11ea-9461-1d4a6e2317fa.gif)

**Comment by jeanp413** [comment]
I'll take this up

**Comment by jeanp413** [comment]
Created a [PR in the vscode-references-view extension repo](https://github.com/microsoft/vscode-references-view/pull/59)
