### ISSUE TITLE
Updates WILL NOT WORK

### ISSUE THREAD

**Issue by owenshaupt** [microsoft/vscode#95286]
Issue Type: <b>Performance Issue</b>

This happened for the previous update, too. When trying to install the update (clicking on the popup notification in bottom right of from the gear icon menu) by restarting Code, nothing happens after the app terminates itself. It doesn't reopen, and when I open it manually it prompts me again to install the update. Last time I had to manually download, uninstall, and reinstall which clearly is not a good experience. Please fix, and stay safe y'all.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|18, 12, 8|
|Memory (System)|8.00GB (0.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   20	    90	 18029	code main
    9	    33	 18030	   gpu-process
    0	    16	 18033	   utility
    0	   197	 18034	   window (splash.jsx — photo-blog)
    0	   156	 18084	     extensionHost
    0	    57	 18091	       electron_node tsserver.js 
    0	   352	 18092	       electron_node tsserver.js 
    0	    66	 18109	         electron_node typingsInstaller.js typesMap.js 
    0	    25	 18095	       electron_node eslintServer.js 
    0	    33	 18087	     watcherService
    0	    25	 18110	     searchService
   26	    74	 18085	   shared-process
    0	     0	 18371	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    6	    74	 18365	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (splash.jsx — photo-blog)
|    Folder (photo-blog): 2575 files
|      File types: cache(849) rb(54) keep(19) jsx(16) svg(12) jbuilder(10)
|                  js(9) scss(8) woff(7) woff2(7)
|      Conf files: package.json(1) webpack.config.js(1);
```

</details>
<details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.3
es7-react-js-snippets|dsz|2.7.1
prettier-vscode|esb|4.4.0
auto-rename-tag|for|0.1.1
vscode-styled-components|jpo|0.0.29
node-module-intellisense|lei|1.5.0
vscode-language-babel|mgm|0.0.27
vscode-scss|mrm|0.9.0
atom-keybindings|ms-|3.0.6
vsliveshare|ms-|1.0.1947
ruby|reb|0.27.0
LiveServer|rit|5.6.1
ActiveFileInStatusBar|Ros|1.0.3
highlight-matching-tag|vin|0.9.9
simple-ruby-erb|vor|0.2.1
vscode-ruby|win|0.27.0
erb-vscode-snippets|Zne|0.0.4

</details>

**Comment by joaomoreno** [comment]
Can you run in a terminal with `code --verbose` and try to update? The terminal might output some meaningful info. It might be that macOS decided to put your App in quarantine.

**Comment by owenshaupt** [comment]
Here's the output from when I clicked to restart now and update:
```
[main 2020-04-17T17:00:26.910Z] Lifecycle#onBeforeWindowClose.fire() - window ID 1
[main 2020-04-17T17:00:26.911Z] Lifecycle#window.on('closed') - window ID 1
[main 2020-04-17T17:00:26.911Z] Lifecycle#onWillShutdown.fire()
[main 2020-04-17T17:00:26.931Z] [storage state.vscdb] close()
[main 2020-04-17T17:00:26.932Z] Lifecycle#app.on(window-all-closed)
[main 2020-04-17T17:00:26.932Z] Lifecycle#app.on(will-quit)
[main 2020-04-17T17:00:27.016Z] update#quitAndInstall(): after lifecycle quit() with veto: false
[main 2020-04-17T17:00:27.016Z] update#quitAndInstall(): running raw#quitAndInstall()
[main 2020-04-17T17:00:27.017Z] update#quitAndInstall(): running raw#quitAndInstall()
```
Is there other keywords I should look for in the output?

**Comment by owenshaupt** [comment]
I just followed the steps listed [here](https://github.com/microsoft/vscode/issues/13604#issuecomment-321231345), so I have the newest version now. It was in quarantine but I couldn't get it to update even after removing the quarantine and even restarting. If the next update comes around and the same issue occurs, I'll come back here. Thanks for the tip!

**Comment by joaomoreno** [comment]
Let me know how it goes.

**Comment by morozgrafix** [comment]
I have similar problem, put details in #95409
