### ISSUE TITLE
Toggle enable/disable breakpoints

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [microsoft/vscode#95280]
Currently the only commands that I know of to enable / disable breakpoints are:

```
{
        "key": "ctrl+x ctrl+i",
        "command": "workbench.debug.viewlet.action.disableAllBreakpoints"
    },
    {
        "key": "ctrl+x ctrl+l",
        "command": "workbench.debug.viewlet.action.enableAllBreakpoints"
    },
```

the above:

* Requires remembering two keybindings.
* Consumes two keybindings. 
  * Note that Users (my case) may want to only consume one so that they can use the other keybinding (chord in my case) for something else.

Is there a commandID for toggling enable/disable breakpoints? If not, I'd like this to be a feature request for it.

**Comment by isidorn** [comment]
No there is no command to toggle disablement.
However an extension can easily contribute such a command since we expose the `Breakpoint` through the VS Code api.
