### ISSUE TITLE
Opening Markdown from right click does not use extentions

### ISSUE THREAD

**Issue by cjshowalter** [microsoft/vscode#95282]
- VSCode Version: 1.44.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Open a markdown document
2. Right-click the tab, and select 'Open Preview'
You'll see it opens the generic preview, with the dark background. If you have something like 'Markdown preview enhanced' installed, and use the 'ctrl-shft-v' shortcut, it works and opens with the extension (The background will be white, etc). I don't see the shortcut listed next to the 'Open Preview' option, so maybe adding that there will fix this?

Does this issue occur when all extensions are disabled?: N/A

**Comment by mjbvz** [comment]
This seems like an extension issue to me. The markdown preview enhanced extension register a command to open itself, just like it already does for the keyboard shortcut

**Comment by cjshowalter** [comment]
I think I see what you're saying... I tried disabling the extension, and trying the keyboard shortcut still brought up your vanilla preview. 
Would tying the 'right click -> open preview', with the keyboard shortcut, be a possible feature enhancement you guys would consider? (Like, showing the shortcut next to the option, and just calling it if clicked on?) I think if someone has a md extension installed, it's reasonable to assume they want to 'use' it, but I'm not sure if it'd break any existing workflows....
