### ISSUE TITLE
We should to able to close all working tree in WorkSpace with command

### ISSUE THREAD

**Issue by ashish336b** [microsoft/vscode#95294]

**Comment by chrmarti** [comment]
What do you mean by 'working tree'? Can you achieve the same with multiple steps, what are these steps?

**Comment by gjsjohnmurray** [comment]
@ashish336b did you try the `File: Collapse Folder in Explorer` command from the Command Palette? It does the same as this button on the workspace title:

![image](https://user-images.githubusercontent.com/6726799/79327982-4066c200-7f0d-11ea-9cf9-692cc26617fc.png)

**Comment by ashish336b** [comment]
Thank you @gjsjohnmurray
