### ISSUE TITLE
[theming] code --disable-extensions Resets color theme

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode#9529]
![image](https://cloud.githubusercontent.com/assets/8189808/16980880/69eeb6b6-4e68-11e6-8db9-1360553ddb19.png)
- OS Version: Windows 10 x64

Steps to Reproduce:
1.  Start vscode with --disable-extensions
2.  Close vscode
3. Start vscode without --disable-extensions

The color theme will not get restored.

**Comment by kieferrm** [comment]
This requires a color theme from the extension market place.

**Comment by aeschli** [comment]
This is the expected behavior. If we can not find an theme we reset the setting to a default.

**Comment by aeschli** [comment]
No longer an issue since we store the theme in the settings.
