### ISSUE TITLE
Oscillating minmap width after pasting text

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#95297]
I happened to me several times that after pasting some text the minimap width got into this oscillating state (it is an mp4 movie).

[screencast 2020-04-15 08-24-32.txt](https://github.com/microsoft/vscode/files/4479429/screencast.2020-04-15.08-24-32.txt)

Resizing the window gets out of this state.

My minimap setting is: `"editor.minimap.size": "fit",`

**Comment by alexdima** [comment]
Let's track in #95178
