### ISSUE TITLE
Restart running npm/npx task in Terminal Panel

### ISSUE THREAD

**Issue by yzpTsubasa** [microsoft/vscode#95291]
Issue Type: <b>Feature Request</b>

I have some scripts in my package.json. 
And I can run these scripts by click "run" (a arrow icon) from "NPM SCRIPTS" list,
but if I wanna restart a running task, I have to switch to "NPM SCRIPTS",  then click "run" again.
Then VS Code will prompt "The task 'npm: ... ...  is already active."，finally I can restart it by click "Restart Task" button.
If there is a shortcut in Terminal Panel that can restart task, that will be handier.

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18362

**Comment by Lemmingh** [comment]
What a pity.
If there is a way to restart an npm script task by **just one click**, my life will be much easier when developing websites.
