### ISSUE TITLE
disabling snippets suggestion per extension.

### ISSUE THREAD

**Issue by butuzov** [microsoft/vscode#95298]
I would like to have settings section,  so I can disable snippets integration provided by the extension.

For example, I used to mine snippets starts with leading `_`, but official `go` has own snippets it would like to propose.

![image](https://user-images.githubusercontent.com/651824/79304828-d9401200-7efa-11ea-8f99-f8d7449d2b2f.png)

Here are two snippets (`_pkgm` from my custom snippets, and `pkgm`) and please let me explain why it's important to have such feature (disabling snippets suggestion ).

* Its a way easier to get an idea what is `_pkgm` then `pkgm` - I see difference way easier.
* again, I used to leading in suggestion.

its can be implemented for example in a next way (`settings.json`):

```json
...
"ms-vscode.go" : [
     "snippets": "disable"
],
...
``` 

This feature can be added per extension, but if this added via vscode, you can define rules for this per any custom extension, not waiting for implementation by extensions author.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Afeature-request+label%3Asnippets

**Comment by butuzov** [comment]
Look like this is issue #10565
