### ISSUE TITLE
uninstall report 

### ISSUE THREAD

**Issue by vaibhav842** [microsoft/vscode#95295]
How to uninstall vs code its extensions and erase all data and reinstall it again

**Comment by chrmarti** [comment]
Which OS are you on? I see some results when searching the web that might help: https://www.bing.com/search?q=uninstall+vscode

@joaomoreno Would it be worthwhile documenting this? (Can't find it right now.)

**Comment by joaomoreno** [comment]
https://code.visualstudio.com/docs/setup/setup-overview#_how-can-i-do-a-clean-uninstall-of-vs-code
