### ISSUE TITLE
can not step in constructor, will will terminate node.exe

### ISSUE THREAD

**Issue by flyingcodes** [Microsoft/vscode#953]
![1](https://cloud.githubusercontent.com/assets/12825770/11554233/1d0aa7c0-99d1-11e5-99a0-218f55b1344a.GIF)
![2](https://cloud.githubusercontent.com/assets/12825770/11554234/1d0e64c8-99d1-11e5-949b-1d3fa8ed1816.GIF)
![3](https://cloud.githubusercontent.com/assets/12825770/11554235/1d177d42-99d1-11e5-958d-a91d2ee957fb.GIF)

class CA {
	constructor(){		
	}	
}

class CB extends CA {
	constructor(p){
		super(p);
	}
}

var cb = null; // debugger pointer
//cb = new CB(123); // can not step in, will terminate node.exe
cb = new CB(); // step in, then follow line can step in, else can not
cb = new CB(123); // can step in if above is step in
console.log(cb);

**Comment by weinand** [comment]
@flyingcodes this is a node.js and not a VSCode problem. If I use node's builtin debugger from the command line and follow your steps I see the same crash:

`
node debug t1.js
`

Please file this bug against node.js.

**Comment by flyingcodes** [comment]
@weinand thanks, i had reported to node.js project. [https://github.com/nodejs/node/issues/4307](https://github.com/nodejs/node/issues/4307)
