### ISSUE TITLE
Allow for no-results message in editor.action.goToLocations-command

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#95308]
Is it possible to add the API to show the editor message?

The use case could be:

A extension registered a command in the context menu, and the user clicks on it. After the execution, show a editor message to provide some result hint.

![image](https://user-images.githubusercontent.com/6193897/79317704-9ac94800-7f38-11ea-89d0-9c676d8276db.png)

**Comment by jrieken** [comment]
@jdneo Is this a problem that occurs when using `editor.action.peekLocations` but not having a result? I am not a fan of exposing the in-editor-message widget but I can easily tweak the command so that can show a message

**Comment by jdneo** [comment]
Thank you @jrieken! 

In Java, we have a feature called `go to super implementation` (navigate to the implementation in the super type). Our current behavior is try to resolve it on hover, if it has a super implementation, then show the button in the hover information:
<img width="608" alt="Screen Shot 2020-06-15 at 7 23 50 PM" src="https://user-images.githubusercontent.com/6193897/84652280-f9fa0780-af3d-11ea-82e3-f7eddabb1894.png">

To better expose the feature, we hope to add it into the context menu as well. Something like this: ![demo](https://user-images.githubusercontent.com/6193897/79424914-826a3380-7ff3-11ea-850c-c360df608e8e.gif)

So we hope we can get the same experience when there is no result for this navigation, show the editor message, just like what VS Code has for `go to definition`, `go to reference`...

**Comment by jrieken** [comment]
Great. Than let's do this. The Java extension will call the [`editor.action.goToLocations`](https://github.com/microsoft/vscode/blob/012e874cb115cf02d8f452d53490e9333b679e5f/src/vs/editor/contrib/gotoSymbol/goToCommands.ts#L717) command when it has its results and I will make sure it shows a message when called without results, e.g support an argument with a custom no result message

**Comment by jdneo** [comment]
@jrieken Pretty cool! That works for us!

Thank you!

**Comment by jrieken** [comment]
Alright, I'll try to get something in for tomorrow

**Comment by jrieken** [comment]
I have pushed those changes, this is how you call the [api command](https://github.com/microsoft/vscode/blob/8434c86e5665341c753b00c10425a01db4fb8580/src/vs/editor/contrib/gotoSymbol/goToCommands.ts#L719)

```ts
return vscode.commands.executeCommand(
	'editor.action.goToLocations',
	vscode.window.activeTextEditor.document.uri, // anchor uri and position
	vscode.window.activeTextEditor.selection.start,
	[], // results (vscode.Location[])
	'goto', // mode
	'No Foo Found' // <- message
);
```

**Comment by jdneo** [comment]
Working like a charm!

![image](https://user-images.githubusercontent.com/6193897/85273596-5e721500-b4b0-11ea-9211-6ae832f04eae.png)

**Comment by jrieken** [comment]
Adding verified based on the previous comment

**Comment by jdneo** [comment]
Hi @jrieken,

one more question: The API works fine when the location array is empty. Today I tried to add a location into it:

```js
return commands.executeCommand(
    'editor.action.goToLocations',
    window.activeTextEditor.document.uri,
    window.activeTextEditor.selection.active,
    [targetLocation],
    'goto',
    'No super implementation found'
);
```

where the `targetLocation` is an object containing `uri` & `range:`

```
targetLocation = {
    uri: ...,
    range: ...,
};
```

Then I got an error: `Unable to open 'Person.java': Invalid arguments.`

Is that anything I missed here?

Thanks

**Comment by jrieken** [comment]
> where the targetLocation is an object containing uri & range:

The `range` must be an instance of `vscode.Range` otherwise this won't work. Can you confirm it is like that, e.g no lookalike type but the real thing?

**Comment by jdneo** [comment]
@jrieken

I tried to get a Range using the constructor, and failed to go to the target location.

```
targetLocation = {
    uri: Uri.parse(superImpl.uri),
    range: new Range(new Position(0, 0), new Position(0, 0)),
};
```

**Comment by jrieken** [comment]
Yeah, I see it now. There is something wrong

**Comment by jrieken** [comment]
Sorry, what must be is that the result array should be instances of vscode.Location-types. When calling commands we have special logic to check for that type which then turns it into the corresponding objects on the client side

**Comment by jdneo** [comment]
@jrieken Thank you! I should try to use the constructor of Location... 😃
