### ISSUE TITLE
Localhost  took too long to respond

### ISSUE THREAD

**Issue by sruthiragupathy** [microsoft/vscode#95301]
The local host is not working in the browser. I have installed node to work on react. When i give the command "npm start" to check if the web app works well on browser, the browser keeps on loading and after a while it says "This site can't be reached ,localhost took too long to respond".And the VS code is bit slow.
<img width="922" alt="VSCode" src="https://user-images.githubusercontent.com/37189469/79310344-698d4f80-7f19-11ea-9223-0cd2b4ebb856.PNG">
<img width="700" alt="localhost_err" src="https://user-images.githubusercontent.com/37189469/79310376-7447e480-7f19-11ea-8be7-14584a84e1da.PNG">

**Comment by chrmarti** [comment]
Not a problem with VS Code. Did you check your firewall rules?

**Comment by sruthiragupathy** [comment]
I checked the firewall rules and made some changes . It helped . Thank you so much.

**Comment by shraddha960** [comment]
Can you tell me what firewall changes you did because I m facing the same issue

**Comment by sruthiragupathy** [comment]
Yeah sure. I went to firewall settings . I found that the expired quick
heal in the system was causing this issue. So i uninstalled it . Herewith i
have attached the firewall settings screenshot . Hope that helps.

**Comment by shraddha960** [comment]
Thanks a lot for your help😊
