### ISSUE TITLE
Possible bug in the UI, settings icon - INSIDER

### ISSUE THREAD

**Issue by alan-hwp** [microsoft/vscode#95303]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Using Insider version :::
Version: 1.45.0-insider
Commit: 92ff20ac39c7507fdf4164e2bedfdfb700805fe1
Date: 2020-04-14T18:11:49.145Z
Electron: 7.2.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.4.0-177-generic snap
2. There appears to be a bug in the settings icon (cog in lower left part of the window) where it is showing a blue circle with a white 1, as if to indicate an update is available but the version is up to date. See attached screen shot.

![Screenshot from 2020-04-15 08-49-46](https://user-images.githubusercontent.com/56353019/79312512-e8bd5c00-7ef6-11ea-9e98-1b438f8bb394.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Does it indicate that Settings Sync needs you to sign in? Please attach a screenshot of the menu that opens when clicking on the gear.

**Comment by yume-chan** [comment]
See #94822

**Comment by alan-hwp** [comment]
Hi Christof,
Good Spot!! yes "Sign in to sync(1) " does appear. How can that be turned off or disabled?

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/94888

There was a bug in insiders before that enabled Settings Sync automatically and we fixed this in next insiders here - https://github.com/microsoft/vscode/issues/94888. But fix cannot recover from disabling the sync and removing the badge. 

To fix this please disabled Sync using the command  `Preferences Sync: Turn off`
