### ISSUE TITLE
Settings Sync unable login to MS account

### ISSUE THREAD

**Issue by htjain** [microsoft/vscode#95306]
- VSCode Version: 1.45.0-insider  
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Install VScode latest insider 
2. Try to login using MS account
3. Web browser opens  for http://127.0.0.1:XXXXX/signin?nonce=XXXXXXX
4. Connection timeout

> This page isn’t working
> 127.0.0.1 didn’t send any data.
> ERR_EMPTY_RESPONSE

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
Are you still seeing this in the latest VS Code?

**Comment by eagl3s1ght** [comment]
Thank you! It works for me now after having the issue mentioned for months
on my work PC.

Den tis 3 nov. 2020 kl 20:24 skrev Rachel Macfarlane <
notifications@github.com>:
