### ISSUE TITLE
Global search regex marked as invalid

### ISSUE THREAD

**Issue by kylemh** [microsoft/vscode#95313]
A regex which works perfectly on the popular regex browser testers yields an error in the global search tool.

The regex in question: https://regex101.com/r/hO7cu0/1

VSCode Version: 1.44.1
MacOS: 10.15.4 (19E287)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:

1. Put regex into global search input:
```
import\s?\{[\s\w\,]*Modal\,?[\s\w\,]*\}\s?from\s*[\"\'\s].*([\@\w\_\-]+)[\"\'\s].*\;$
```

2. Activate regex mode for search input.

3. See error:
<img width="452" alt="Screen Shot 2020-04-15 at 2 08 55 AM" src="https://user-images.githubusercontent.com/9523719/79320118-1b972e00-7ebe-11ea-855e-6c8add704f95.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment]
Seemingly you can't randomly escape everything in Code.

`import\s?\{[\s\w,]*Modal,?[\s\w,]*\}\s?from\s*["'\s].*([@\w_-]+)["'\s].*;$` is valid

**Comment by kylemh** [comment]
@yume-chan I've tried yours + explicitly adding `\n` (as instructed here: https://code.visualstudio.com/updates/v1_29#_multiline-search)

```
import\s?\{[\s\w\n,]*Modal,?[\s\w\n,]*\}\s?from\s?["'\s].*([@\w_-]+)["'\s].*;$
```

but I'm not getting any matches for my expected test cases... I'll re-open if you think that deservers it, but I'm willing to wager I'm just shit at Regex and you know your stuff!

**Comment by yume-chan** [comment]
Yeah, I don't mean you should close this issue. Code's behavior is definitely unexpected.

Relates to #94843

**Comment by IllusionMH** [comment]
> but I'm not getting any matches for my expected test cases...

Could you provide simplified examples that aren't matched please?
I've tried your last RegExp and it matches single and multiline named imports (that has at leas one word with `Modal` inside).

**Comment by kylemh** [comment]
True, let's not discuss my shitty regex though 😂 

The point is it doesnt work in the context of VS Code.

**Comment by IllusionMH** [comment]
> The point is it doesnt work in the context of VS Code.

Can you provide examples that aren't matched with latest regexp?
Because as I said - copied regexp doesn't report any issue and matches both multiline and single line imports. (Tested on Windows)

So at this point it's hard to guess what exactly doesn't work for you. I think that examples should help with narrowing issue

**Comment by kylemh** [comment]
I'm getting no matches for anything.

@IllusionMH maybe it's an OS discrepency? Do you have any settings changed, for example `search.usePCRE2`

**Comment by roblourens** [comment]
This works for me on mac as well.

![image](https://user-images.githubusercontent.com/323878/79515001-1b597880-800d-11ea-910d-a834143cce97.png)

**Comment by kylemh** [comment]
@roblourens do you have `search.usePCRE2` enabled?

**Comment by kylemh** [comment]
Workin' for me now. Sorry for the hunt. Still confused by the differences in browser regex tools vs VS Code's regex tool in terms of what should be escaped, tho!

**Comment by roblourens** [comment]
Yeah, search is implemented using Ripgrep which uses the Rust regex engine and is strict about escaping unnecessarily. `@` for example is not a special regex char so it doesn't need to be escaped in JS but it's allowed if you do.
