### ISSUE TITLE
Set default location for workspace configuration files

### ISSUE THREAD

**Issue by dhrunia** [microsoft/vscode#95311]
I save all my workspaces in a shared folder so I can access them across devices. It would be nice if vscode can be configured to have a default workspace storage directory. Currently the `open workspace` command opens file selection dialog in the current folder and I have to navigate manually to the place where I saved my workspaces.

**Comment by bpasero** [comment]
I think this request makes sense.

**Comment by bpasero** [comment]
@dhrunia we do have code though that will explicitly set the folder to be the parent of the workspace file to support the scenario better. Did you try?

For me, when I am inside a workspace and click "Open Workspace", the folder that opens by default is the parent of that workspace.

**Comment by dhrunia** [comment]
@bpasero no I wasn't aware of that setting. I will give try that, can you please point me to where I can set that.

Yes once inside a workspace "open workspace " is opening a selection dialog in the folder I choose the last workspace. Which is good enough for switching between workspaces. I think it would be nice if vscode could read workspace configs from a user defined default location and then have them displayed within the command pallette similar to how file selection (ctrl+p) does.

**Comment by bpasero** [comment]
@dhrunia there is no setting, it will just behave like that. I guess in your case you click "Open Workspace" when you are having a folder opened or no workspace at all.

**Comment by dhrunia** [comment]
> I guess in your case you click "Open Workspace" when you are having a folder opened or no workspace at all.

Yes

**Comment by Firehawke** [comment]
I have a number of different projects I use VSCode with and I prefer to keep all of my workspaces in a single folder together. I often open from a fresh VSCode instance by clicking "Open Workspace" and it inevitably goes to a folder that is not the folder I'd like to open from. Being able to configure a default workspace folder would save me a lot of trouble.

As a workaround, I could just doubleclick the code-workspace file (which appears to not be associated with VSCode by default, at least on Windows 10, and also doesn't have an icon.. I'll have to open an issue for that..) but please do consider a config option.
