### ISSUE TITLE
getWordRangeAtPosition can freeze the extension host

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#95319]
see https://github.com/microsoft/vscode-pull-request-github/issues/1629

When running `getWordRangeAtPosition` on very, very long lines then the whole extension host freezes. This is because word ranges are computed per line and a "good" combination of regexp and long line can stall the extension for a very long time.

**Comment by jrieken** [comment]
fyi @alexdima for better ideas. My bail-out plan is to give the underlying [`getWordAtText`](https://github.com/microsoft/vscode/blob/10629588780cc340c22a52970c2aea79c172926f/src/vs/workbench/api/common/extHostDocumentData.ts#L227)-function an optional time budget and once that's reach no word is found.

**Comment by alexdima** [comment]
Here's an idea:
1. Create a substring of the line 100 characters before and 100 character after
2. Find words in those 200 characters
3. If a word is found at that position, and its boundaries are strictly within the -100,+100 substring, go with that.
4. (optional) If a word is not found, repeat the search over the entire line text with a time budget

**Comment by jrieken** [comment]
I like that, in fact it is very similar to how `getWordAtPosFast` works. It defines these boundaries by looking for the last space before the match position.

**Comment by jrieken** [comment]
This is what I have done

* have an overall time budget of 150ms
* create a line substring if it is longer than 1000 characters
* repeatedly search for words at `column - (N*15)`

This favours "normal" word definitions and "normal" lines by preventing creation of new strings but it also means there is a max word length of 1000 characters. Hope this doesn't back-fire.

**Comment by jedwards1211** [comment]
Note that a time budget of 150ms is completely unacceptable for VSCodeVim users, it makes for a really agonizing typing experience

**Comment by connor4312** [comment]
Seems to work well in my testing. With a 50 MB single line, getting a word at any position was instant.
