### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by pavlyukpetr** [microsoft/vscode#95317]
Issue Type: <b>Bug</b>

Hello, after the last update the search is not working

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (6.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.3
githistory|don|0.6.3
prophet|Sqr|1.3.1
vscode-stylelint|sty|0.84.0
html-preview-vscode|tht|0.2.5

</details>

**Comment by LeoLfL** [comment]
for me the same

**Comment by pavlyukpetr** [comment]
> for me it was the same. i just reopened project (file -> open folder) and now it works

Yes, looks like it works. It takes some more time for search, but at least it works.
Thanks

**Comment by carey** [comment]
Given that you have the Prophet extension installed, I think this is probably #94928.

**Comment by pavlyukpetr** [comment]
I will close it since it works already after the reload.
