### ISSUE TITLE
[Feature Request] HTML Tag matching window

### ISSUE THREAD

**Issue by bingzheyuan** [Microsoft/vscode#9531]
I recall in webstorm or netbean, when you click on a HTML tag, if the corresponding matching tag is not in current view, a small window appears showing the matching tag as well as a few surrounding lines. It would be great to have this feature.

**Comment by alexandrudima** [comment]
fyi @aeschli Can this be implemented as some sort of go-to-definition for a html tag that goes to the corresponding closing/opening tag.

**Comment by mjbvz** [comment]
Closing as this feature was requested over a year ago and there has not been further interested expressed in it
