### ISSUE TITLE
Emoji handling in new Quick Pick

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#95312]
Issue Type: <b>Feature Request</b>

Having a markdown file with headers:

```markdown
# 💄 Wow
# ❌ Wow
```

Searching for `💄` 
![Screenshot (181)](https://user-images.githubusercontent.com/9638156/79319369-e49e3800-7f10-11ea-9b2b-203fa70d86b2.png)

Searching for `❌` - no results

**1.43.0** handled those correctly.

VS Code version: Code - Insiders 1.45.0-insider (1c36d747fbf113144d3bf82b0aa3cbd290714e38, 2020-04-15T05:37:18.376Z)
OS version: Windows_NT x64 6.2.9200

**Comment by bpasero** [comment]
I cannot reproduce btw:

![image](https://user-images.githubusercontent.com/900690/79323015-f29e8980-7f0d-11ea-9558-9503ab2bb8a9.png)

**Comment by usernamehw** [comment]
```diff
- @
+ @💄
```

**Comment by bpasero** [comment]
@jrieken can you check, this seems like a bug in the `createMatches` method to me where the unicode character is getting split into 2 with highlights each.

Test to reproduce which fails in `filters.test.ts`:

```ts
test('Unicode highlight broken #95312', function () {
	assertMatches('💄', '💄 Wow', '^💄^ Wow', fuzzyScore);
});
```

**Comment by jrieken** [comment]
Yeah, we match earch char code separately and 💄 is of length 2, other characters likely much longer. Unsure how to tackle this, definitely stretch for April

**Comment by bpasero** [comment]
The other matcher (still used for e.g. file search) does not seem to hit this:

![image](https://user-images.githubusercontent.com/900690/79360617-77a49580-7f44-11ea-9f08-4d0bd35c5ded.png)

I am not sure how yours work, but shouldn't multiple highlight positions that are next to each other, simply normalize into a single match-range? In other words: matching "foo" on "foobar" results in a match range from 0-3 and not 3 ranges for each character.

**Comment by bpasero** [comment]
Hm, I take it back. The match seems to have a correct range at least in the tests:

![image](https://user-images.githubusercontent.com/900690/79539010-c0b03300-8085-11ea-8779-73ba60616cbe.png)

Maybe its rather a bug in how we apply the match in the label.

**Comment by usernamehw** [comment]
I don't think this issue has any importance but searching for `❌` returns no results.

**Comment by bpasero** [comment]
Can you still report it?

**Comment by usernamehw** [comment]
In a separate issue?

**Comment by bpasero** [comment]
Well, let's leave this one to verify that the highlights are OK.

**Comment by usernamehw** [comment]
#95716
