### ISSUE TITLE
Can't remove unsaved files from a single open editor group

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9532]
1. Have two open editor groups.
2. In one of the panes, create a new Untitled file and make it dirty.
3. Open that file in the other pane, using Quick Open.

The Untitled file is now present in both groups. There seems to be no way to remove that file from a single group. Removing it from the group seems to mean _Closing_ and it will remove it from **all** the groups.

**Comment by bpasero** [comment]
Planned for August: https://github.com/Microsoft/vscode/issues/8983
