### ISSUE TITLE
why are there lots of code.exe and they occupy lots of RAM?

### ISSUE THREAD

**Issue by arbraham** [microsoft/vscode#95323]
Issue Type: <b>Performance Issue</b>

It's very strange today when I am creating a python program. My RAM of laptop is consumed dramaticlly. I found it's because of the code.exe of VisualStudioCode. I just opened the py file, no runing, but a lot of code.exe generated and consumed a lot of memory. Can you help me to check the reason?

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2491)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    68	  5344	code main
    0	    70	  1668	   shared-process
    0	    66	  3004	   window (Issue Reporter)
    0	   202	  3508	   window (批量分组处理数据.py - myPython - Visual Studio Code [Administrator])
    0	    92	  2744	     extensionHost
    0	    95	  3384	       C:\Users\Administrator\AppData\Local\Programs\Python\Python38\python.exe completion.py
    0	    34	  8268	         C:\Users\Administrator\AppData\Local\Programs\Python\Python38\python.exe lib\python\jedi\inference\compiled\subprocess\__main__.py lib\python 3.8.2
    0	    90	  3892	       electron_node tsserver.js 
    0	    43	 10352	         electron_node typingsInstaller.js typesMap.js 
    0	    28	  6060	       "D:\Programs\Microsoft VS Code\Code.exe" "d:\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=2744
    0	    30	  9696	       "D:\Programs\Microsoft VS Code\Code.exe" "d:\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain" --node-ipc --clientProcessId=2744
    0	    52	 10260	       "D:\Programs\Microsoft VS Code\Code.exe" "d:\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=2744
    0	    50	 10660	       electron_node tsserver.js 
    0	    34	  6776	     searchService
    0	    11	 10672	     watcherService 
    0	    25	  6596	   utility
    0	    68	  7244	   gpu-process
    0	    13	  8052	   electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (批量分组处理数据.py - myPython - Visual Studio Code [Administrator])
|    Folder (myPython): 38 files
|      File types: py(12) pyc(6) bak(4) log(2) exe(2) spec(2) json(1)
|      Conf files: launch.json(1)
|      Launch Configs: python;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.3.71659
cpptools|ms-|0.27.0

</details>

**Comment by chrmarti** [comment]
The included process info doesn't seem to show any process with excessive memory consumption. Are there other additional code.exe processes? What are their command line arguments?

**Comment by arbraham** [comment]
> The included process info doesn't seem to show any process with excessive memory consumption. Are there other additional code.exe processes? What are their command line arguments?

There are 8 code.exe always stay in the TaskManager. I don't know what they are, and I don't know what their command line arguments are:
![image](https://user-images.githubusercontent.com/1009896/79448368-e270d200-8013-11ea-9bfd-c01f7cd8e33c.png)
The 3 python.exe,  2 pythonw.exe consumes not so much memory as yesterday:
![image](https://user-images.githubusercontent.com/1009896/79448612-498e8680-8014-11ea-9a9d-a17469eecd5c.png)
