### ISSUE TITLE
Duplicate Refresh icon displaying on 3rd party extensions sidebars

### ISSUE THREAD

**Issue by waza-kaunda** [microsoft/vscode#95327]
Issue Type: <b>Bug</b>

Open VS Code an navigate to the sidebar for any of the extensions listed below : 
* Docker 1.0.0 - ms-azuretools.vscode-docker
* Oracle Developer Tools for VS Code - oracle.oracledevtools
* Test Explorer UI - benl.vscode-test-explorer

Also visible in Maven projects view in the file explorer.

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (11.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.1.0
cucumberautocomplete|ale|2.14.1
ng-template|Ang|0.901.0
vscode-log-viewer|ber|0.10.2
vs-code-bpmn-io|bpm|0.7.0
vscode-eslint|dba|2.1.3
vscode-protractor-snippets|dee|1.0.5
java-decompiler|dgi|0.0.2
xml|Dot|2.5.0
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.4.0
javac-linter|fau|1.3.1
vscode-firefox-debug|fir|2.7.2
jira-plugin|gio|0.19.0
gc-excelviewer|Gra|2.1.34
vscode-test-explorer|hbe|2.18.0
yuml|Jai|3.5.1
vscode-redux-devtools|jin|1.0.2
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
go-to-spec|Lou|0.1.3
vscode-docker|ms-|1.0.0
network-edge-devtools|ms-|1.0.0
vscode-edge-devtools|ms-|1.0.7
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
debugger-for-edge|msj|1.0.14
angular2-inline|nat|0.0.17
oracledevtools|Ora|19.3.2
vscode-boot-dev-pack|Piv|0.0.8
vscode-spring-boot|Piv|1.16.0
material-icon-theme|PKi|4.0.1
vscode-css-peek|pra|3.0.2
quicktype|qui|12.0.46
angular-karma-test-explorer|raa|1.2.5
bitbucket-pull-requests|Ram|0.3.10
java|red|0.59.1
vscode-xml|red|0.11.0
vscode-yaml|red|0.7.2
code-settings-sync|Sha|3.4.3
system-task-manager|sha|1.0.5
vscode-checkstyle|she|1.3.2
gitflow|vec|1.2.1
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2
vscode-spring-boot-dashboard|vsc|0.1.8
vscode-spring-initializr|vsc|0.4.6
JasmineSnippets|xab|1.0.1

(1 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/7779646/79331835-1a94e980-7f1c-11ea-997e-d94d5cf41e3e.png)

![image](https://user-images.githubusercontent.com/7779646/79331951-457f3d80-7f1c-11ea-927a-7401149a973c.png)

![image](https://user-images.githubusercontent.com/7779646/79332004-592aa400-7f1c-11ea-8759-220ff4137758.png)

**Comment by isidorn** [comment]
Looks like custom trees and an extension issue but first forwarding to @alexr00

**Comment by alexr00** [comment]
@waza-kaunda can you try disabling all extensions except one of the ones needed to reproduce the issue? For example can you disable every extension except the docker extension?
I can't reproduce the issue, which leads me to think that you have an extension installed that is adding lots of refresh buttons in views it doesn't own.

**Comment by waza-kaunda** [comment]
@alexr00 I did as you advised and found the extension causing the issue, I logged an issue on there
https://github.com/ShawnZhong/vscode-system-task-manager/issues/1

![image](https://user-images.githubusercontent.com/7779646/79498054-0094fd00-8029-11ea-98a7-8eaae3b8a45a.png)
