### ISSUE TITLE
Python's debbuger doesn't start

### ISSUE THREAD

**Issue by IdoPort1** [microsoft/vscode#95329]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I have tried to use an pre made debbuging script I have and VSCode just doesn't start the process for me to debug

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.90GB (2.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.34.0
vscode-npm-script|eg2|0.3.11
latex-workshop|Jam|8.8.0
vscode-docker|ms-|1.0.0
csharp|ms-|1.21.17
python|ms-|2020.3.71659
remote-wsl|ms-|0.44.2
cpptools|ms-|0.27.0
vs-keybindings|ms-|0.2.0
debugger-for-chrome|msj|4.12.6
java|red|0.59.1
code-spell-checker|str|1.8.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-pack|vsc|0.9.0
vscode-maven|vsc|0.21.2

</details>

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Python extension. Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose
