### ISSUE TITLE
Extension host terminated unexpectedly 

### ISSUE THREAD

**Issue by aashutosh9765** [microsoft/vscode#95321]
Issue Type: <b>Bug</b>

This bug  keeps coming even though I tried to reinstall. I clicked on Open Developer Tools and it show that it has issue with whatever theme I select which are built in

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (3.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-rename-tag|for|0.1.1
python|ms-|2020.3.71659
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by ArturoDent** [comment]
Did you see the pinned issue: https://github.com/microsoft/vscode/issues/94858?

**Comment by nguyenxndaidev** [comment]
Please vote this related issue: [Prevent global crash when extension crashes](https://github.com/microsoft/vscode/issues/100283)!

**Comment by chrmarti** [comment]
Closing as duplicate.
