### ISSUE TITLE
MyCompletionItem is expensive

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#95324]
This is a follow-up from https://github.com/microsoft/TypeScript/issues/36265#issuecomment-613971669

<img width="509" alt="Screenshot 2020-04-15 at 13 10 55" src="https://user-images.githubusercontent.com/1794099/79330998-c3dae000-7f1a-11ea-9424-8f9611aec58c.png">

* see attached profile [CPU-20200415T102048.875Z.cpuprofile.txt](https://github.com/microsoft/vscode/files/4480800/CPU-20200415T102048.875Z.cpuprofile.txt)
* the creation of `MyCompletionItem` is taking quite some time and sums up to more than the actual completion request

Also, it calls [`getWordRangeAtPosition`](https://github.com/microsoft/vscode/blob/ce57f8ad58fd0f4ea6051ae08b3894e47d8d4045/extensions/typescript-language-features/src/features/completions.ts#L182) *after* completions have arrived and therefore on a potentially different state, with different words etc. This should be all *before*

**Comment by jrieken** [comment]
related to https://github.com/microsoft/vscode/issues/95325

**Comment by mjbvz** [comment]
`getReplaceRange` https://github.com/microsoft/vscode/blob/ce57f8ad58fd0f4ea6051ae08b3894e47d8d4045/extensions/typescript-language-features/src/features/completions.ts#L181 is the most expensive part of this call

Now that  https://github.com/microsoft/TypeScript/issues/29270 is fixed, I believe I can just disable this branch for TS 3.9+

**Comment by mjbvz** [comment]
In a empty js file, I now see the TS extension's completion conversion take around 25ms down from around 50ms:

<img width="890" alt="Screen Shot 2020-04-15 at 2 20 56 PM" src="https://user-images.githubusercontent.com/12821956/79390312-55028480-7f24-11ea-8d50-32f6cce9641f.png">

@jrieken Let me know if you notice any other obvious optimization opportunities

**Comment by jrieken** [comment]
Look at this: The memoize util is responsible for 15-20% of the time it takes to convert completion items. 

<img width="1179" alt="Screenshot 2020-04-16 at 12 46 26" src="https://user-images.githubusercontent.com/1794099/79447594-6315db00-7fe0-11ea-941d-191af0a743d0.png">

You are better off nuking that using a good old field. I also believe (measure, this used to be true is the past when I measured that) that computation is faster if you use static maps instead of switch-case-statements. So, have `staticMap[entryKind]` instead of the switch-case (the same would then be true convertKind)

**Comment by mjbvz** [comment]
Good catch. Removing memo does improve `_convert`

The static map performs the same (or perhaps slightly worse) than the switch. I tested it by looping though a completion list 1000 times and converting the `kind` of every entry in it

**Comment by jrieken** [comment]
Thanks
