### ISSUE TITLE
Test: Breakpoints updated only after save

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#9533]
Test for #8077:

- [x] any OS -  **@sandy081**

New or changed breakpoints are now sent to the debug adapter only after a file has been saved so that they always correspond to the file on disk. Previously breakpoints were sent to the debug adapter immediately even before the file was saved to disk. In this case the debugger would register breakpoints for a source location that only exists in the editor buffer, but not in the file that the runtime sees.

(More details about this feature can be found here: #8077)

**Turn auto save off** and then launch a node debug session and stop on break.
Then verify:
* As long as the file is not edited breakpoints should behave normally, e.g. they are shown as verified, they are hit and can be enabled / disabled, deleted.
* As soon as a file is edited, breakpoints are shown as unverified and the hover message explains why.
* Once a file is saved breakpoints are still unverified (because node-debug does not yet implement hot-code-replacement). The hover message should be slightly different.

**Comment by sandy081** [comment]
Done with testing. LGTM.
