### ISSUE TITLE
ANSI colors in terminal corrupts output

### ISSUE THREAD

**Issue by rianquinn** [microsoft/vscode#95330]
- VSCode Version: 1.44.1
- OS Version: Windows 10

Steps to Reproduce:

1. Ok, this is a really strange one. I am working on some code in C++ that outputs ANSI color. I can only reproduce the issue in Git Bash for Windows when using ANSI color escape sequences when using VSCode. This test code will reproduce the issue:

```
    for (int i = 0; i < 1000; i++) { // NOLINT
        fputs("\033[0;92m", stdout);
        fputs("Hello", stdout);
        fputc(' ', stdout);
        fputs("\033[0;95m", stdout);
        fputs("World", stdout);
        fputs("\033[0m", stdout);
        fputc('\n', stdout);
    }
```
![image](https://user-images.githubusercontent.com/5932003/79333779-5740f080-7edc-11ea-99cf-688ceacfa42f.png)

2. If I run this code with no color, I do not see an issue. I also do not see an issue if I use CMD or powershell, but neither of those seem to support ANSI color by default so there is no color that outputs, and once again, if I test Git Bash with no color, I do not see an issue. If I run this from Git Bash directly, I also do not see an issue, so it seems to be specific to Git Bash in VSCode, or the use of ANSI colors in VSCode with the terminal. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps if it happens.

/needsMoreInfo

**Comment by rianquinn** [comment]
I did that and it does not happen in any terminal I have tested. It seems specific to VSCode

**Comment by rianquinn** [comment]
@Tyriar This is what it looks like in Windows Terminal. it doesn't output ANSI colors, but there are also no corruption issues. I also included a picture of what this looks like in Bash without VSCode. This is only an issue with Bash + VSCode

![image](https://user-images.githubusercontent.com/5932003/80226391-899fcb80-8609-11ea-81de-42f4eacd8657.png)

![image](https://user-images.githubusercontent.com/5932003/80226485-a805c700-8609-11ea-93f0-70a6d2c26b7d.png)

**Comment by rianquinn** [comment]
This is what is looks like in VSCode + Bash (as shown above)

![image](https://user-images.githubusercontent.com/5932003/80226775-0a5ec780-860a-11ea-8536-ca01b9c5d3f2.png)

**Comment by rianquinn** [comment]
It also gets worse the more you break up the characters. So for example, if you use printf to output each character one at a time, you get a lot more corruption. Here is an example. Let me know if you need any more info.

![image](https://user-images.githubusercontent.com/5932003/80227146-7e996b00-860a-11ea-998d-d0cca7b06d63.png)

**Comment by Tyriar** [comment]
Unconfirmed.

I'm not sure what's happening here. If you want to help move this issue along you can enable escape sequence logging to show what the process is sending over to the terminal: https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging

**Comment by Tyriar** [comment]
@meganrogge and I were just looking into this, we could repro and we found this sequence being printed which likely comes from conpty (possibly git bash):

```
[0;92mHello [0;95m[58X[58C[16;21H[?25h
[?25lWorld[0m
```

This is saying to write `Hello`, them move the cursor to position (16,21) and write `World`. This is enough for me to say that it's definitely not a problem with the terminal component in VS Code but an issue with the pty emulation provided by Windows (conpty) and there's nothing we can do.

You can try reproduce this in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701), if it happens there report to https://github.com/microsoft/terminal. If it doesn't happen there then chances are they have fixed the issue and we'll get the fix in an upcoming version of Windows 10.
