### ISSUE TITLE
[Solution] Extension Host. Linux. Not antivirus related

### ISSUE THREAD

**Issue by ocoka** [microsoft/vscode#95338]
Issue Type: <b>Bug</b>

Just open any TypeScript project

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-13T14:40:29.529Z)
OS version: Linux x64 5.3.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2730)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.51GB (2.62GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp-to-typescript|adr|1.12.1
autocomplete-symbols|aki|0.2.1
stackoverflow-search|Ale|1.2.0
ng-template|Ang|0.901.0
sourcetrail|ast|0.0.2
All-Autocomplete|Ati|0.0.23
markdown-mermaid|bie|1.4.3
exuberant-ctags|chr|0.0.12
vscode-eslint|dba|2.1.3
change-color|Dee|0.0.1
vscode-dash|dee|2.4.0
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-firefox-debug|fir|2.7.2
name-that-color|gui|0.1.2
vscode-systemd-support|han|0.1.1
auto-programming|hit|0.0.2
githd|hui|2.2.4
fuzzy-search|jac|0.0.2
search-editor-apply-changes|jak|0.1.1
ctags-support|jay|1.0.19
svg|joc|1.1.7
ctagsx|jta|1.1.1
git-graph|mhu|1.22.0
formate|Mik|1.1.4
vscode-scss|mrm|0.9.0
csharp|ms-|1.21.17
autorest|ms-|2.0.1
js-debug-companion|ms-|1.0.0
mono-debug|ms-|0.15.8
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
angular-console|nrw|11.1.3
vscode-jscpd|pau|0.3.4
vscode-spring-boot|Piv|1.16.0
git-file-history|pom|1.0.1
quicktype|qui|12.0.46
htmlescape-vscode-extension|ray|0.0.7
java|red|0.59.1
vscode-yaml|red|0.7.2
bash-debug|rog|0.3.7
incremental-search|sie|0.2.1
html-preview-vscode|tht|0.2.5
better-search|tra|0.0.6
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2
vscode-spring-boot-dashboard|vsc|0.1.8
vscode-spring-initializr|vsc|0.4.6
vim|vsc|1.13.1
vscode-ansible|vsc|0.5.2
quokka-vscode|Wal|1.0.287
wallaby-vscode|Wal|1.0.193
highlight-icemode-select|xuc|1.0.0

(1 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/8239290/79347460-63f53100-7f3c-11ea-85a1-00f1cf033d58.png)

**Comment by ocoka** [comment]
```
node --version
v12.16.2
```
```
npm --version
6.14.4
```

**Comment by ocoka** [comment]
I've disabled this extension, clear all cached files excluding my preferences in .config/Code/User/preferences.json, and now error gone, will watch on it 

csharp-to-typescript | adr | 1.12.1
change-color | Dee | 0.0.1
name-that-color | gui | 0.1.2
vscode-systemd-support | han | 0.1.1
csharp | ms- | 1.21.17
autorest | ms- | 2.0.1
js-debug-companion | ms- | 1.0.0
mono-debug | ms- | 0.15.8
vscode-spring-boot | Piv | 1.16.0
bash-debug | rog | 0.3.7
vscode-spring-boot-dashboard | vsc | 0.1.8
vscode-spring-initializr | vsc | 0.4.6
vscode-ansible | vsc | 0.5.2
ms-vsliveshare.vsliveshare

**Comment by ocoka** [comment]
Flight stable. I would like to propose a solution like:
1. save list of installed extension to file: ```$: code --list-extensions > backup.txt```
2. save your preferences and keyboard settigns from _~/.config/Code/User/ * .json_
3. remove *VSCode*.
4. ~install Atom~ (joke :smile:)
4. clear all cache, remove _~/.config/Code_ and _/.vscode_ directories
5. reinstall *VSCode*, from repository or by downloading packages from site
6. install all extensions from saved file by invoke: ```$: for e in $(< backup.txt); do code --install-extension $e; done```
7. copy back saved _preferences.json_ and _keyboard.json_

start *VSCode*, if error is still here try to disable extension one by one until error gone... :beers:

**Comment by chrmarti** [comment]
Not sure where SIGABRT would come from. Anyone?

**Comment by deepak1556** [comment]
The SIGABRT comes from this check https://github.com/nodejs/node/blob/master/src/node_zlib.cc#L568 .

However I am not sure what extension triggered that, based on https://github.com/microsoft/vscode/issues/95338#issuecomment-614066564 the npm version is not the issue, so most likely some extension used a really old version of node-tar that triggered this.

**Comment by deepak1556** [comment]
@ocoka can you narrow down which extension is causing this crash from your list , would be good to know.

**Comment by bpasero** [comment]
If any JS code can crash our extension host then I think we could look into overriding the attempt to access a certain code path and null it out. We did that in the past here:

https://github.com/microsoft/vscode/blob/3d40474537547f4eb98f1202c4815daaa2889a8d/src/vs/workbench/services/extensions/node/extensionHostProcessSetup.ts#L60

**Comment by ocoka** [comment]
> @ocoka can you narrow down which extension is causing this crash from your list , would be good to know.

I will try today

**Comment by ocoka** [comment]
Yes, I;ve found it:
![image](https://user-images.githubusercontent.com/8239290/79454608-3370ce00-7ff4-11ea-9fc6-a565d958a305.png)
*ms-vscode.autorest*
https://marketplace.visualstudio.com/items?itemName=ms-vscode.autorest
This one destroy your *extensionHost* - BAD GUY, Да ! )))

**Comment by deepak1556** [comment]
Thanks @ocoka , I can repro the crash! 

But I see that the extension was last updated in 2017, and I don't see access to their github repo :( 

Will let @alexdima @bpasero decide the next steps.

**Comment by bpasero** [comment]
@sandy081 do we have a way to remove the extension from the marketplace or at least signal that current versions of VSCode are not compatible?

I am not sure our solution that worked for `natives` will work in this case because possibly later versions of the module work fine...

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/80186519-63305f00-860e-11ea-86c8-017290deb52c.png)
