### ISSUE TITLE
File search is not working and rg process eats up CPU

### ISSUE THREAD

**Issue by frazer-robert** [microsoft/vscode#95336]
Issue Type: <b>Bug</b>

(cmd + P) to search a file is not Working. It just keeps on loading. rg process eats up all CPU usage always above 100% +. My vs code is newly installed and doesn't have any extensions in it.

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:47:00.296Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 5, 4|
|Memory (System)|16.00GB (2.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by frazer-robert** [comment]
![image](https://user-images.githubusercontent.com/60595768/79345423-b7707a80-7f4e-11ea-9d7d-52418483be05.png)

**Comment by induratized** [comment]
For me Cmd + P has changed. It now shows the definition of the code the caret is at.

**vscode** V1.44.1
**System**:
![image](https://user-images.githubusercontent.com/6311837/79399521-3393ae00-7fa1-11ea-9471-8de097671fee.png)

**Comment by induratized** [comment]
I changed nothing on my Mac and suddenly many keybinding have started misbehaving in vscode v1.44.1
- Cmd + b for view explorer display toggle
- Cmp + p for file search doesn't work
- Option + up/down key used to move line vertically

**Comment by induratized** [comment]
I have upgraded Mac but the issue still exists
![image](https://user-images.githubusercontent.com/6311837/79523584-2e576180-807c-11ea-982a-85b447a9e58c.png)

Apparently `Cmd + P` file search works `but` on a new file (`Cmd + N`) active tab.

**Comment by induratized** [comment]
@frazer-robert found a solution and it fixed my keybindings

https://github.com/microsoft/vscode/issues/94666

Look for @RMacfarlane 's solution
![image](https://user-images.githubusercontent.com/6311837/79524119-4d0a2800-807d-11ea-9065-3aaf13485739.png)

**Comment by roblourens** [comment]
Most likely https://github.com/microsoft/vscode/issues/94928, do you have a folder in your workspace which comes from a filesystem provider extension? Should be fixed in Insiders.

**Comment by frazer-robert** [comment]
Global text search is working but file search is not working. This process named rg makes my system very slow.
![image](https://user-images.githubusercontent.com/60595768/79526810-c147ca00-8083-11ea-8f91-0b87689135d7.png)

**Comment by roblourens** [comment]
If this still happens in the new 1.44.2 release, could you check whether any tips here help? https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory

**Comment by frazer-robert** [comment]
Did all those changes. But still it's very slow. 
![image](https://user-images.githubusercontent.com/60595768/79644408-6bc80600-81c6-11ea-8ed7-7636d9f48ec5.png)
![image](https://user-images.githubusercontent.com/60595768/79644434-9619c380-81c6-11ea-986e-a3a4d056df33.png)

**Comment by roblourens** [comment]
It looks like there are a ton of files in your workspace for it to go through. It seems like we are just bound by the rate that we can read them all. You might try using the `search.exclude` or `files.exclude` setting to narrow it down.
