### ISSUE TITLE
Vscode can't save the *.go file

### ISSUE THREAD

**Issue by zhanghuangbin** [microsoft/vscode#95347]
- VSCode 1.44.1 (system setup)
- OS Version: Window 7（Windows_NT x64 6.1.7601）

Steps to Reproduce:

1. create an file which name ends with .go
2. paste the following code
```go
package main

import (
	"fmt"
	"math"

)

type Abser interface {
	Abs() float64
}

func main() {
	var a Abser
	f := MyFloat(-math.Sqrt2)
	v := Vertex{3, 4}

	a = f  // a MyFloat implements Abser
	a = &v // a *Vertex implements Abser

	// In the following line, v is a Vertex (not *Vertex)
	// and does NOT implement Abser.
	a = v

	fmt.Println(a.Abs())
}

type MyFloat float64

func (f MyFloat) Abs() float64 {
	if f < 0 {
		return float64(-f)
	}
	return float64(f)
}

type Vertex struct {
	X, Y float64
}

func (v *Vertex) Abs() float64 {
	return math.Sqrt(v.X*v.X + v.Y*v.Y)
}

```

Does this issue occur when all extensions are disabled?: No

I guess it might be caused in that way：
1. the action of saving file might trigger some actions like auto formating file or other auto fix actions.
2. those actions might change the content of the saving file, which might trigger the actions mentioned in step1
3. step 1 and step 2 might cause Make circular call

**Comment by chrmarti** [comment]
/causedByExtension

Please file against the extension causing this. My first guess would be an extension contributing a code formatter for Go. Maybe the Go extension itself.
