### ISSUE TITLE
globals.d.ts not available in HTML <script> with ts-check

### ISSUE THREAD

**Issue by henrahmagix** [microsoft/vscode#95344]
- VSCode Version: 1.44.1
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. Make a HTML file and add the following:
```html
<script type="module">
  // @ts-check
  hello('henry');
</script>
```
2. Add a `globals.d.ts` file with the following:
```ts
declare function hello(name: string);
```
3. See that VS Code reports a problem:
```
{
	"resource": "/path/to/test/index.html",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Cannot find name 'hello'.",
	"source": "javascript",
	"startLineNumber": 3,
	"startColumn": 3,
	"endLineNumber": 3,
	"endColumn": 8
}
```

Does this issue occur when all extensions are disabled?: Yes

Related to https://github.com/microsoft/TypeScript/issues/37919

**Comment by henrahmagix** [comment]
Maybe this is the problematic line?
https://github.com/microsoft/vscode/blob/release/1.44/extensions/html-language-features/server/src/modes/javascriptMode.ts#L66
```ts
getCurrentDirectory: () => '',
```

**Comment by mjbvz** [comment]
This falls under #26338
