### ISSUE TITLE
Reloading window while explorer is open causes explorer to be empty

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#95345]
Noticed this with today's Insider's update:

![image](https://user-images.githubusercontent.com/35271042/79352231-6a5cbc00-7eee-11ea-81b6-e088daeb6d39.png)

1. Open explorer
2. Reload window
3. :bug: Explorer is empty

Toggling the sidebar visibility fixes this.

**Comment by isidorn** [comment]
Can not repro. What repo are you using? If you F1 > developer tools > do you see some errors in the developer console?

**Comment by misolori** [comment]
Hmm...I couldn't repro today. Will reopen if I see this.
