### ISSUE TITLE
Unable to watch for file changes in this large workspace - not a large workspace.

### ISSUE THREAD

**Issue by ChrisLee63** [microsoft/vscode#95348]
# Version:

VSCode Version: 1.44
OS Version: Ubuntu 16.04

# Steps to Reproduce:

1. Create a basic web project: `vue init webpack project`
2. Recursively count the number of files in the entire project directory: `find . -type f | wc -l`
    My project has 24906 files (including directories).
3. Check current limit of file watchers: `cat /proc/sys/fs/inotify/max_user_watches`
    Make a note of the watcher limit of 8192
4. Configure Visual Studio code to exclude the `node_modules` directory using
```
"files.watcherExclude": {
  "**/node_modules/**": true
}
```
5. Count files in only `node_modules`: `find node_modules -type f | wc -l`
    Make a note of the file count: 24800
6. Subtract the `node_modules` file count (24800) from project file count (24906)
    24906 - 24800 = 106
7. 106 is well within the watcher limit of 8192.

If VS Code honors watcherExclude, it must only watch 106 files.
But VS Code still complains it's "Unable to watch for file changes in this large workspace".

BTW, I use this [script](https://github.com/fatso83/dotfiles/blob/master/utils/scripts/inotify-consumers) to find who consume my inotify resources. The partly result is as following:

```
INOTIFY
   WATCHER
    COUNT     PID     CMD
----------------------------------------
    4446    20537  /usr/share/code/code --max-old-space-size=3072 /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsse
    2636    20559  /usr/share/code/code /usr/share/code/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTy
     796    19189  node /home/zjli/Desktop/project/node_modules/.bin/webpack-dev-server --inline --progress --config build/we
      81    17794  /usr/share/code/code /usr/share/code/resources/app/out/bootstrap-fork --type=watcherService
      54     1399  /usr/lib/unity-settings-daemon/unity-settings-daemon
      52    16611  node build/dev-server.js
      11     2210  zeitgeist-datahub
```

Oddly enough, this bug has certain randomness. Sometimes it appears five minutes after I open the project, sometimes it appears an hour later.

# Does this issue occur when all extensions are disabled?

Yes

I have read some related issues like #59679, but it does not help.

**Comment by shepelevstas** [comment]
I have the same problem.
VSCode Version: 1.46.1
OS Version: Fedora 32

I also wrote a script checking which files are being watched by the first proc that scored top in Inotify Watched Count script, and almost all of them are from node_modules from the workspace folder.
