### ISSUE TITLE
Add an option to disable the new "Faster task Quick Pick" functionality introduced in the March 2020 release

### ISSUE THREAD

**Issue by focorner** [microsoft/vscode#95358]
The <a href="https://code.visualstudio.com/updates/v1_44#_faster-task-quick-pick" target="_blank">March 2020 release</a> of VS Code introduced a new way of looking up tasks from third party extensions. Taken directly from the release notes:

> The task Quick Pick used to fetch all tasks from all task-providing extensions before displaying the list of tasks to choose from. Now, VS Code doesn't fetch any additional extension tasks before showing the Quick Pick dropdown, making it much faster. Extension contributed tasks are also only fetched when you ask for them, which frees up the extension host.

I think that this is a nice functionality and that it should be enabled by default (like it is now) to protect the extension host, because it is true that some third party task providers can slow things down quite a bit if those extensions are not using "task caching", for example.

However, for some particular use cases, my opinion is that this new functionality adds an unnecessary step, because we are no longer allowed to search for tasks by name: we now have to start by specifying the task provider before we can search for a task by name.

I understand that once you pick a particular task it gets cached, but this does not work that well with some task providers that are "more dynamic". In my opinion, for those dynamic task providers, the new functionality kind of defeats the purpose of having a dynamic task provider; i.e. the user might as well only use `tasks.json` to define his/her tasks manually since those tasks are no longer fully automatic anyways.

So here are my suggestions to improve the new functionality:
- Add a setting that allows the user to bypass the new mechanism to directly `Show All Tasks...` when the task picker is revealed; and/or
- Add a setting that allows the user to manually "whitelist" some task providers.

Personally, I would use the first idea, and I think that it would require a minimal effort to implement. The second idea could be interesting in some cases, but my guess is that it would require more effort to implement, but I'm sharing it anyways. :)

Thank you for your time and support. VS Code is a great tool, and we are very lucky to have it. So keep up the good work! A+ :)

Frank

**Comment by alexr00** [comment]
Thank you for the thoughtful issue!
To go back to the slow picker use `"task.quickOpen.showAll": true`.

**Comment by focorner** [comment]
@alexr00  Thank you! :)
