### ISSUE TITLE
typescript language feature intellisense crashing

### ISSUE THREAD

**Issue by tahsinature** [microsoft/vscode#95369]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

idk why. sometimes intellisense not loading....

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T08:23:56.137Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 6, 5|
|Memory (System)|16.00GB (0.96GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
path-intellisense|chr|1.4.2
bracket-select|chu|2.0.1
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.3
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
prettier-vscode|esb|4.4.0
code-runner|for|0.9.17
glitch|gli|0.1.6
dotenv|mik|1.0.1
vscode-docker|ms-|1.0.0
python|ms-|2020.3.71659
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vsliveshare|ms-|1.0.1947
vetur|oct|0.24.0
material-icon-theme|PKi|4.0.1
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
guides|spy|0.9.3
vscode-wakatime|Wak|4.0.0
quokka-vscode|Wal|1.0.287
vscode-proto3|zxh|0.4.2

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by tahsinature** [comment]
IntelliSense just not working

**Comment by mjbvz** [comment]
Did you test insiders with all extensions disabled?

**Comment by tahsinature** [comment]
nope

**Comment by mjbvz** [comment]
Please do

**Comment by tahsinature** [comment]
ok
