### ISSUE TITLE
Text from the search bar overlaps the top bar of a code view so that neither is readable

### ISSUE THREAD

**Issue by tristan957** [microsoft/vscode#95366]
Text from the search bar overlaps the top bar of a code view so that neither is readable. Image below.

- VSCode Version: 1.44.1
- OS Version: mac 10.15

Steps to Reproduce:

1. Open a search box for the file
2. Open a code view of another file or area of the same file. For example clicking `# References` using the Java Extension, or any other similar code-lens.
3. Scroll the search to cover the top bar of the code view

<img width="280" alt="image" src="https://user-images.githubusercontent.com/11936772/79370132-c38d1580-7f17-11ea-87f8-c2383f2ee326.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
I'm not seeing this issue anymore on latest version. We can reopen if you are seeing it again.
