### ISSUE TITLE
DAP "evaluate" request issued for invalid frameId

### ISSUE THREAD

**Issue by int19h** [microsoft/vscode#95367]
_Created from https://github.com/microsoft/debug-adapter-protocol/issues/60#issuecomment-613282870_

In https://github.com/microsoft/debugpy/issues/112, we're seeing VSCode send "evaluate" requests with invalid "frameId" - they're sequenced immediately after "continue" or "next", which invalidates frame IDs for all frames retrieved prior to unpausing. 

This came via a user-reported bug, for which we do not have our own repro. However, the user can repro it consistently and collect the logs.

The bug itself is about VSCode remote (SSH) sessions crashing during debugging, and in all cases, it appears that the crash immediately follows the IDE receiving a failure response to such an "evaluate" request. When DAP logging is enabled on both sides of the session, the client logs end when the request is sent, but the debug adapter logs show the request was received, processed, failed (due to invalid "frameId"), and failure response was sent back, after which the client disconnects eventually. We are not entirely sure that this problem is the root cause of the crashes, but given that this sequence of requests and responses shows up in *all* repro attempts so far, it's hard to believe that it is unrelated.

**Comment by isidorn** [comment]
Thanks for filling this issue.
As mentioned in the original comment
Yeah it is a bit tricky, since we do some ui optimisations (e.g we refresh the watch element with a slight timeout and thus it can happend that you get a stale evaluate). Thus I acknolwedge the bug but will not fix it right away, thus assinging to backlog.

**Comment by nickbattle** [comment]
We're seeing similar behaviour on 1.44.2.

After a debug stop, which retrieves a set of frameIds, a subsequent stop sometimes requests "scopes" for a frame using an old frameId (that is, a frameId from the previous stop). It doesn't happen every time - it's fairly rare, perhaps 1 in 50, but often enough to be an issue.

Logs available if required.

**Comment by isidorn** [comment]
Should be fixed via bf77670cd7
Good steps to repro here https://github.com/microsoft/vscode-js-debug/issues/455
