### ISSUE TITLE
TypeScript server crashed 5 times after starting

### ISSUE THREAD

**Issue by dcartman** [microsoft/vscode#95362]
Issue Type: <b>Bug</b>

Title says it. I just received the pop up notification when opening Xcode.

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:47:00.296Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (1.69GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
gitlens|eam|10.2.1
php-debug|fel|1.13.0
beautify|Hoo|1.5.0
vscode-sshfs|Kel|1.17.0
vscode-docker|ms-|1.0.0
csharp|ms-|1.21.17
python|ms-|2020.3.71659
cpptools|ms-|0.27.0
vsliveshare|ms-|1.0.1947
nunjucks|ron|0.2.3
propertylist|zho|0.0.2

</details>

**Comment by mjbvz** [comment]
When a crash happens in VS Code, you should see a notification that says, `Report Issue`. That will automatically fill in an issue that looks like: https://github.com/microsoft/TypeScript/issues/37939

If this doesn't work, then try running the `Developer: Toggle Developer Tools` command in the command palette. Then share the developer console output which should include the crash stacks well

**Comment by alesmenzel** [comment]
I am also seeing this after updating to the latest 1.44.2 which broke a lot of services. 

```
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z (2 days ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

Here are the first lines in the developer console of vscode:

```
[Extension Host] (node:53336) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:137
ipc.cp.ts:236 IPC "Search" crashed with exit code null and signal SIGKILL
(anonymous) @ ipc.cp.ts:236
3console.ts:137 [Extension Host] info
console.ts:137 [Extension Host] A non-recoverable error occured while executing tsserver command: updateOpen
t.log @ console.ts:137
6console.ts:137 [Extension Host] Error: Unexpected SIGPIPE    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap.js:5:80)    at process.emit (events.js:203:13)
t.log @ console.ts:137
notificationsAlerts.ts:40 The TypeScript language service died 5 times right after it got started. The service will not be restarted.
onDidChangeNotification @ notificationsAlerts.ts:40
24console.ts:137 [Extension Host] Error: Unexpected SIGPIPE    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap.js:5:80)    at process.emit (events.js:203:13)
t.log @ console.ts:137
log.ts:197   ERR [spellright] Spell checker not initialized properly. 
console.ts:137 [Extension Host] Git installation not found.
t.log @ console.ts:137
console.ts:137 [Extension Host] Looking for parseable documents...
ipc.cp.ts:236 IPC "Search" crashed with exit code null and signal SIGKILL
(anonymous) @ ipc.cp.ts:236
8console.ts:137 [Extension Host] Error: Unexpected SIGPIPE    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap.js:5:80)    at process.emit (events.js:203:13)
t.log @ console.ts:137
notificationsAlerts.ts:40 GitLens was unable to find Git. Please make sure Git is installed. Also ensure that Git is either in the PATH, or that 'git.path' is pointed to its installed location.
onDidChangeNotification @ notificationsAlerts.ts:40
24console.ts:137 [Extension Host] Error: Unexpected SIGPIPE    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap.js:5:80)    at process.emit (events.js:203:13)
t.log @ console.ts:137
notificationsAlerts.ts:40 The CSS Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.
onDidChangeNotification @ notificationsAlerts.ts:40
notificationsAlerts.ts:40 The JSON Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.
onDidChangeNotification @ notificationsAlerts.ts:40
log.ts:197   ERR Could not create TS service: Error: Could not create TS service
```

**Comment by mjbvz** [comment]
@alesmenzel It looks like your installation is corrupted since the `Search` process and all your language servers are crashing. Have you tried reinstalling VS Code?

**Comment by alesmenzel** [comment]
I don't like the idea of reinstalling after updating, but it seems like the issue was that I renamed a project folder vscode was using and after the update it tried the old location for some reason, after several restarts it started working again.. sorry I hijacked this issue, my issue is resolved

**Comment by mjbvz** [comment]
Closing as this as we need more information from the original poster
