### ISSUE TITLE
Windows paths beginning with \\?\ open in separate tab when opened from the integrated terminal

### ISSUE THREAD

**Issue by connorskees** [microsoft/vscode#95364]
Related to https://github.com/microsoft/vscode/pull/95147

When alt-clicking paths beginning with `\\?\` in the integrated terminal, they will open in a separate tab from those opened without the prefix.

E.g. 
```
cd %userprofile% 
mkdir foo && cd foo
echo bar > baz
echo %userprofile%\foo\baz VS \\?\%userprofile%\foo\baz
```
these two paths will open in separate tabs despite being the same file. 

In addition, some extensions not expecting paths to contain `\\?\` (namely, `rust-analyzer v0.2.135`) will crash when one opens a file in this way.

**Comment by Tyriar** [comment]
@bpasero support was just added in the terminal https://github.com/microsoft/vscode/issues/94961
