### ISSUE TITLE
Choose what to sync button alignment is off, especially when zoomed in

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95368]
Windows, regular DPI montior:

zoomLevel: 0
![image](https://user-images.githubusercontent.com/2193314/79371726-aea98580-7f09-11ea-98b0-43650677ac6e.png)

zoomLevel: 1
![image](https://user-images.githubusercontent.com/2193314/79371778-c2ed8280-7f09-11ea-8031-1509b29cfd00.png)

@alexr00 were you involved in the multi-select quick pick component?

**Comment by misolori** [comment]
Should be fixed now:

![image](https://user-images.githubusercontent.com/35271042/79411650-37e7a900-7f58-11ea-9f9d-5986112db80a.png)
