### ISSUE TITLE
Problem Count Gets Associated With Wrong Tab in Panel When Views Are Dragged

### ISSUE THREAD

**Issue by RealBarrettBrown** [microsoft/vscode#95372]
- VSCode Version: 1.44.1
- OS Version: MacOS 10.14.6

Steps to Reproduce:

1. In the lower panel, drag the Terminal view tab onto the Problems view and then place it to the left of the Problems view, combining the two views into one panel.
![image](https://user-images.githubusercontent.com/1630335/79376274-eaebde80-7f27-11ea-84b5-80eb9942fe53.png)
![image](https://user-images.githubusercontent.com/1630335/79375975-7add5880-7f27-11ea-9876-e5550f8fc4e9.png)

2. Drag the Problems view back up to the tab bar, removing it from the panel.
![image](https://user-images.githubusercontent.com/1630335/79376149-bc6e0380-7f27-11ea-8609-59fa04e4051f.png)

Expected results:
The Problem Count is displayed to the right of the "Problems" tab

Actual results:
The Problem Count is displayed to the right of the "Terminal" tab.

Does this issue occur when all extensions are disabled?: Yes/No
I can't reproduce the issue when extensions are disabled because the Count does not appear on the Problems tab.  This is likely because no extensions are running to search the code for problems.  I imagine that the problem would persist if there was a "Count" on the Problems tab.

**Comment by sandy081** [comment]
@sbatten Is this because of reusing the problems view container for terminal view but using the title of terminals view?

**Comment by sandy081** [comment]
Introduced following

- [`IActivityService.showViewContainerActivity`](https://github.com/microsoft/vscode/blob/1b30b9b6ba86207bc8ae37864bb3610e54fee302/src/vs/workbench/services/activity/common/activity.ts#L26) - to set the activity for the given container
- [`ViewContaierActivityByView`](https://github.com/microsoft/vscode/blob/1b30b9b6ba86207bc8ae37864bb3610e54fee302/src/vs/workbench/services/activity/common/activity.ts#L34) - that sets the activity for a given view on appropriate container
