### ISSUE TITLE
Allow `launch.json` configuration to access environment specified by `"envFile"`

### ISSUE THREAD

**Issue by jnickg** [microsoft/vscode#95371]
Possibly related to: https://github.com/microsoft/vscode/issues/2809 — ...However, that issue is extremely verbose, and topically does not sound quite the same.
Also related to: https://github.com/microsoft/vscode-cpptools/issues/5060 — They suggested filing an issue here, so here I am!

If a `launch.json` configuration specifies `"envFile"`, values in that file should be resolved _before_ resolving variables used in other parts of the launch configuration.

Motivation: If I have a workspace defining multiple tasks, that define different ways of preparing an arbitrary remote host for debugging (i.e. deploying different configuration files & executables, before starting `gdbserver` on the host), the user should not have to enter the remote host socket a second time in order to start debugging. There are possibly other values I would want to add to the `.env` file, as well.

One technique to support this would having each of those tasks create a `.env` file for the launch configuration(s) to read, in order to detect settings like IP address and Port.

For example, here is a sample `.env` file:
```
# VS Code remote-debugging environment file.
# The purpose of this file is to provide an environment which can be read
# by configurations in launch.json, such as remote-host socket.

REMOTE_HOST_SOCKET=192.168.1.155:1234
```

I should be able to create a launch config that specifies these values:
```json
{
            "envFile": "${workspaceFolder}/.vscode/remote_debug.env",
            "miDebuggerServerAddress": "${env:REMOTE_HOST_SOCKET}",
}
```
...where this launch config reads the environment variables in `remote_debug.env`, and they can be referenced by other parts of the launch configuration such as `miDebuggerServerAddress`.

Currently, when I try to do this, and add verbose logging, here is my output—please note the first line resolves `MIDebuggerServerAddress` to an empty string, and the last lines later resolve the environment file
```
1: (183) LaunchOptions  WaitDynamicLibLoad='true'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (183) LaunchOptions  MIDebuggerServerAddress=''\r\n"},"seq":20}
1: (183) LaunchOptions  MIDebuggerServerAddress=''
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (183) LaunchOptions  ExternalConsole='true'\r\n"},"seq":22}
1: (183) LaunchOptions  ExternalConsole='true'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (183) LaunchOptions>\r\n"},"seq":24}
1: (183) LaunchOptions>
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (184) LaunchOptions    <SetupCommands>\r\n"},"seq":26}
1: (184) LaunchOptions    <SetupCommands>
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (184) LaunchOptions        <Command IgnoreFailures='true' Description='Enable pretty-printing for gdb'>-enable-pretty-printing</Command>\r\n"},"seq":28}
1: (184) LaunchOptions        <Command IgnoreFailures='true' Description='Enable pretty-printing for gdb'>-enable-pretty-printing</Command>
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (184) LaunchOptions    </SetupCommands>\r\n"},"seq":30}
1: (184) LaunchOptions    </SetupCommands>
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (184) LaunchOptions    <Environment>\r\n"},"seq":32}
1: (184) LaunchOptions    <Environment>
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (184) LaunchOptions        <EnvironmentEntry Name='REMOTE_HOST_SOCKET' Value='192.168.1.155:1234' />\r\n"},"seq":34}
1: (184) LaunchOptions        <EnvironmentEntry Name='REMOTE_HOST_SOCKET' Value='192.168.1.155:1234' />
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (184) LaunchOptions    </Environment>\r\n"},"seq":36}
1: (184) LaunchOptions    </Environment>
```

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
fyi @weinand

**Comment by weinand** [comment]
As said many times: "envFile" is a node.js concept and as such not known to VS Code.

Please consider to add those values to your (VS Code) settings or your environment (outside of VS Code) and  refer to them with either `${config:NAME}` or `${env:NAME}`.

**Comment by jnickg** [comment]
@weinand I see your point. That said, just to clarify a user perspective here, I and many others don't care if you use node.js under the hood—having a clean way to pass information between setup tasks and launch configurations is a significant usability consideration. I have seen people go as far as creating a `launch.json.template` and doing string replacement in setup tasks, which feels hacky.

We did initially try having our setup script export to the environment when run through VS Code, and ran into issues that way as well. If you can point me to a working example of this, please let me know!

Using VS Code settings seems like it could work, though generally it doesn't feel that clean—we're trying to keep workspaces & tasks as light wrappers around IDE-agnostic tools, hence the decision to use a `.env` file.

I'll see how far we can get using VS Code settings.

**Comment by uglycoyote** [comment]
@isidorn I have a similar need for this feature after switching to WSL2.   Inside WSL2 I am running a local debug server (Parcel's dev server), which can be accessed from the Windows side as http://localhost:1234, but I am running into problems with debugging plugins while using "localhost"

As I described [in this issue on the vscode-firefox-debug plugin](https://github.com/firefox-devtools/vscode-firefox-debug/issues/238),  the VSCode debugger has communication issues when trying to talk to the dev server using localhost.  However it works fine when using the true IP address.

My process right now is that I need to run "ip addr" on WSL2 and then copy-paste the IP address in to launch.json each time I restart WSL2 and it gets a new IP address.  Since my launch.json is part of the git repo of my project, I'm constantly checking in new revisions of this file with new temporary IP addresses.  It would be great if I can check in the launch.json but configure it with a local environment file as suggested here.

**Comment by weinand** [comment]
@uglycoyote since VS Code has access to environment variables in the launch.json, did you try to store the WSL2 IP address in an environment variable (instead of an "envfile")?

**Comment by uglycoyote** [comment]
@weinand Thanks that does work. I didn't realize that plain environment variables worked.  To be honest it would have been a bit simpler to do this using an envFile, but I did get it working using environment variables.
