### ISSUE TITLE
Replacing the already open file crashed VSCode

### ISSUE THREAD

**Issue by chrisinhim** [microsoft/vscode#95373]
Issue Type: <b>Bug</b>

Hi VSCode Team,

Today I came across an issue with VSCode that crashed my Citrix VDI.

Here's the situation in detail:

file1.json (has some 5000 lines) is open in VSCode.
I received file2.json (has some 5000 lines) from my colleague and I opened it in VSCode.
In the same VSCode, I tried "Save As" option on file2.json to replace file1.json, which is already open.

Now VSCode stuck and it did never respond. Along with that my VDI also did not respond. I tried closing and restarting my VDI from outside and it's not opening now. VSCode has crashed my VDI itself.

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18363

**Comment by chrisinhim** [comment]
Please let me know what other information you need so that I can provide it.

**Comment by bpasero** [comment]
Could you share the files? Does it reproduce in insiders?
