### ISSUE TITLE
Breakpoint marker in wrong location

### ISSUE THREAD

**Issue by bookemdano** [microsoft/vscode#95370]
Issue Type: <b>Bug</b>

After multiple edits and runs the breakpoint markers start to move to the middle of the text. 
![image](https://user-images.githubusercontent.com/2606630/79372198-a52d1700-7f23-11ea-8eea-fb3414a3ca1d.png)

VS Code version: Code - Insiders 1.45.0-insider (1c36d747fbf113144d3bf82b0aa3cbd290714e38, 2020-04-15T05:37:18.376Z)
OS version: Windows_NT x64 10.0.19603

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (12.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.21.17
python|ms-|2020.3.71659
powershell-preview|ms-|2020.4.2
debugger-for-chrome|msj|4.12.6

</details>

**Comment by isidorn** [comment]
What debugger are you using? You should file that issue against that debugger since the extension controls the breakpoint location.
Looks like node thus for now forwarding to @connor4312 and @roblourens

**Comment by connor4312** [comment]
This is working as designed. The process you're debugging is running some code. If you make edits to that code, that will change your source code but not what's running in the debugger. We don't know what edits were made between whatever code is running in the debugee and the code on disk; we report breakpoints at positions which the debugee says they can be placed, which might not display in the proper locations if the file is changed.
