### ISSUE TITLE
Linux starting script fails

### ISSUE THREAD

**Issue by myelsukov** [microsoft/vscode#95387]
- VSCode Version: 1.44.1
- OS Version: Linux 5.6.4-arch1-1 #1 SMP PREEMPT x86_64 GNU/Linux

Steps to Reproduce:

1. Create a symbolic link to the VSCode starting script with a space in the name. For example: `ln -s /usr/share/code/bin/code "My VSCode"`
2. Execute "My VSCode" from the terminal

Error is printed to the terminal:
`./My VSCode: line 29: [: too many arguments`

All `$0` in the starting script (https://github.com/microsoft/vscode/blob/master/resources/linux/bin/code.sh) should be enclosed in double quotes to avoid this error.

Does this issue occur when all extensions are disabled?: Yes

**Comment by 9at8** [comment]
I can take this! @Tyriar

**Comment by Tyriar** [comment]
@9at8 great! 👍
