### ISSUE TITLE
Since Version 1.44.1 formatOnSave does not work any more

### ISSUE THREAD

**Issue by joeherold** [microsoft/vscode#95380]
- VSCode Version: 1.44.1
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. edit document
2. save document

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by joeherold** [comment]
![image](https://user-images.githubusercontent.com/3911545/79447048-8d1acd80-7fdf-11ea-87cc-8feca1268906.png)

Oh dear, I figured out what it was. I have no clou, how this changed, I did not, but there was a file specific setting for formatOnSave: false.... oh damn

**Comment by joeherold** [comment]
@jrieken  Is it possible, that the formatOnSave Setting was added/chanted by the update? Because it was set to false on every file format (now changed to true in the image), where a custom setting was available. And I know for sure, that I did not set this to false for every item.

![image](https://user-images.githubusercontent.com/3911545/79447385-13371400-7fe0-11ea-9951-83d870c4dbd8.png)

**Comment by jrieken** [comment]
> Because it was set to false on every file format, where a custom setting was available. And I know for sure, that I did not set this to false for every item.

Yeah, that is super strange... In what file do you see this? User settings, workspace settings, or the "generated" one? 

I have changed nothing in formatting land. @sandy081 does this ring a bell? did something change in config land? could an extension have done this or settings-sync?

**Comment by joeherold** [comment]
it in settings.json for the user settings.

**Comment by jrieken** [comment]
Any change that you have installed some "helpful" extensions that could have caused this?

**Comment by joeherold** [comment]
hmmm, the only change I made, was to switch from amVim to Vim and then back

**Comment by joeherold** [comment]
Here my whole settings:
https://gist.github.com/joeherold/889264c2984cb9cdd76515670284981b#file-settings-json

**Comment by sandy081** [comment]
> did something change in config land? could an extension have done this or settings-sync?

Nothing in config. Settings Sync is not available on stable and even then it should not be causing this. I suspect this is coming from an extension.
