### ISSUE TITLE
Spawned Node child process hangs when starting parent with debugger

### ISSUE THREAD

**Issue by filipmares** [microsoft/vscode#95381]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

We have a main Electron Node process which we start with the debugger. It seems one of our child processes also gets the debugger attached and hangs when starting. This was repreoduced by verifying non-insider build doesn't hang. 

VS Code version: Code - Insiders 1.45.0-insider (1c36d747fbf113144d3bf82b0aa3cbd290714e38, 2020-04-15T05:40:02.537Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (6.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.6.6
color-info|bie|0.5.1
gitlens|eam|10.2.1
prettier-vscode|esb|4.4.0
vscode-test-explorer|hbe|2.18.0
rest-client|hum|0.23.2
vscode-docker|ms-|1.0.0
python|ms-|2020.3.71659
azure-account|ms-|0.8.9
vsliveshare|ms-|1.0.1947
debugger-for-chrome|msj|4.12.6
vscode-yaml|red|0.7.2
vscode-sort-package-json|uni|1.2.2

(2 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
Do you have either of the settings `debug.javascript.usePreview` or `debug.node.useV3` turned on to use our new debugger?

**Comment by filipmares** [comment]
I do have one of those
`"debug.javascript.usePreview": true,`

Should I turn it off?

**Comment by connor4312** [comment]
Turning it off should fix the issue for you. I'll try to reproduce this tomorrow and, if successful, apply a fix to the new debugger for tomorrow's nightly build.

**Comment by filipmares** [comment]
Thank you!

**Comment by connor4312** [comment]
@filipmares can you provide your launch config for debugging and share how you're spawning the child process? Trying to reproduce this using the [electron-quick-start](https://github.com/electron/electron-quick-start) repo with a dummy child process and our [sample launch.json](https://github.com/microsoft/vscode-recipes/tree/master/Electron#configure-launchjson-file) works for me.

![](https://memes.peet.io/img/20-04-b8a0d98e-a822-4720-b41a-7b9b0d60ad6e.png)

**Comment by filipmares** [comment]
Will DM on Teams. :)

**Comment by connor4312** [comment]
This is similar to #95128, I put a workaround for in https://github.com/microsoft/vscode-js-debug/commit/6538f201351c1ef4d1d28b6217ae143ea1e6cf03 that should resolve it. Please let me know if you run into more issues.

/duplicate #95128
