### ISSUE TITLE
Hide only tag items in Git branch list.

### ISSUE THREAD

**Issue by clabough** [microsoft/vscode#95385]
There's currently a "Checkout Type" setting that allows the following options :  All, local, tags, remote.

There's not an option to show both local and remote only (i.e., hide only tags). I'd like to see this setting converted to a checkbox for each option so that any combination of options can be selected.

**Comment by AlCalzone** [comment]
I have a similar feature request. Not sure if it should be a separate issue, but I'd like to reorder the items in the checkout list. Currently remote branches come last. If a repo has a large number of tags and only few remote branches, it would be nice if the branches could be shown before the tags, so one doesn't have to scroll so far.

**Comment by ChrisPapp** [comment]
Hello @joaomoreno,
How about I combine the two requests, and make it into an array where the order of the choices matters? However, since it's an array, it will be updatable through JSON only.

**Comment by clabough** [comment]
Could be a text box with comma-separated values of Local,Remote,Tags and the order they're listed matters. To not show one, just remove it from the list.

**Comment by Kingwl** [comment]
I'd like to work on this.

**Comment by lszomoru** [comment]
Filed #111754 to track an edge case around setting behaviour when there is one invalid value in the list.
