### ISSUE TITLE
Settings: "terminal.integrated.commandsToSkipShell" commands need a nonintuitive "-" prefix

### ISSUE THREAD

**Issue by lbogdan** [microsoft/vscode#95383]
- VSCode Version: latest - **1.44.1 (user setup)**
- OS Version: **Windows_NT x64 10.0.18363**

### What were you trying to achieve?

Sending the Ctrl+P shortcut to the integrated terminal when that's focused, instead of triggering the "Go to File..." / "Quick Open" action.

### How to reproduce?

As advised here https://github.com/microsoft/vscode/issues/35722#issuecomment-334802447 : open the `Settings` tab, search for "skip shell", under the "Terminal > Integrated: Commands To Skip Shell" click on "Add Item", type "workbench.action.quickOpen" and click "OK".

Alternatively, open the `settings.json` file and add

```json
    "terminal.integrated.commandsToSkipShell": [
        "workbench.action.quickOpen"
    ]
```

### What is the expected behavior?

Ctrl+P is sent to the terminal when that's focused.

### What is the observed behavior?

Ctrl+P still opens the "Quick Open" palette.

### Workaround

By randomly browsing other related issues (and a few SO answers), I found that the skipped commands need a `-` prefix, so the "correct" setting should actually be

```json
    "terminal.integrated.commandsToSkipShell": [
        "-workbench.action.quickOpen"
    ]
```

, which indeed works, but it's completely nonintuitive.

I'm aware that "fixing" this would be a breaking change; I opened this issue anyway, maybe it will help others figure this out.

Also, the help message below the setting in the "Settings" tab could make this explicit (although I only read it **after** I found the answer, curious if it was specified or not 🙂).

Does this issue occur when all extensions are disabled?: Yes.

**Comment by usernamehw** [comment]
You are referring to the old issue #35722. The setting was changed since that time (because it was adding about 100+ lines of code to the user setting file and the list became outdated on each release).

Excluding with `-` sign is consistent with `keybindings.json` file.

Official docs contain the right info https://code.visualstudio.com/docs/editor/integrated-terminal#_forcing-key-bindings-to-pass-through-the-terminal

**Comment by usernamehw** [comment]
Setting description is not great though. It probably needs newlines and a mention of `-` to exclude from the list.
