### ISSUE TITLE
VSC 1.44.1 not able to list quick fix for curly brace encased require variables when converting to import.

### ISSUE THREAD

**Issue by 8cy** [microsoft/vscode#95398]
- VSCode Version: 1.44.1 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

When trying to convert a `const { foo } = require('bar');` to a Typescript import;
`import { foo } from 'bar';`, there are no quick fixes available to convert the const require to an import when the variable is encased in curly braces. When trying this without the curly braces, 
`const foo = require('bar');`,  it however does convert to an import. I think that despite curly braces, it should be converted and not ignored.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Thanks. This is actually a bug: https://github.com/microsoft/TypeScript/issues/38081
