### ISSUE TITLE
Install extensions under proxy problem

### ISSUE THREAD

**Issue by jacorachan** [Microsoft/vscode#954]
I have set up my corporate proxy as explained on the documentation:

![Proxy settings](http://i.imgur.com/Cv44idX.png)

But every time that I try to download an extension with `ext install extensionname`, it fails with this error:

![connection error](http://i.imgur.com/WI0oQWA.png)

**Comment by joaomoreno** [comment]
Duplicate of #69

**Comment by jacorachan** [comment]
Thanks @joaomoreno
