### ISSUE TITLE
"Restart to update" does not work

### ISSUE THREAD

**Issue by Haibao425** [microsoft/vscode#95409]
- VSCode Version: 1.44.0
- OS Version: Mac 10.15.4

**Comment by chrmarti** [comment]
Does it not do anything? What is in the dev console? (`Help` > `Toggle Developer Tools`)

**Comment by morozgrafix** [comment]
I have the same issue with VSCode 1.44.1 on OS X 10.14.6 (I've seen this happen on my machine with previous versions as well. The only solution for upgrade has been to download and install it manually) Update mode in settings is set to: `default`


Steps to reproduce:
1. Launch VSCode
2. Wait for it to check update and pop up modal to prompt for update (attempting to update to 1.44.2)
3. Click `Update Now`
4. VSCode closes and never restarts.
5. Update doesn't happen, manually starting it goes back to step 1 with v.1.44.1

Developer Tools close with the app, but I do see `Error: No application in the Launch Services database matches the input criteria.` when opening Dev Tools console. (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1611)


Launched it with `code --verbose` log is attached:
[VScode_1_44_1_verbose_log2.txt](https://github.com/microsoft/vscode/files/4518428/VScode_1_44_1_verbose_log2.txt)

**Comment by morozgrafix** [comment]
Searched through the related issues and looks found one of the posts mentioning that there is a chance that VSCode is in OS X quarantine.

1. ran `command ls -alR@ "/Applications/Visual Studio Code.app" | grep quarantine -B 1` and many files were in quarantine
2. removed them from there by running `xattr -srd com.apple.quarantine "/Applications/Visual Studio Code.app"`
3. checked again and quarantine was removed.

Attempted to upgrade again and VSCode just quit and didn't restart like before.

**Comment by joaomoreno** [comment]
@morozgrafix If you find Code to be in quarantine, it's actually easier to simply removing it, installing it again and remove it from quarantine. Do let me know how that goes.

**Comment by morozgrafix** [comment]
Completely removed VSCode from `/Applications` downloaded latest build v.1.44.2
Installed it into `/Applications` let's see what happens when next version is released. Will report back here.

By the way after fresh install I checked if new installation is in quarantine and it is for some reason, so removing and installing it again doesn't remove it from quarantine. (this specific machine is managed by company IT so they may have some restrictions related to putting things into quarantine)
I don't think quarantine has an effect on inability to restart and update from within VSCode, as I have tried it earlier.

**Comment by joaomoreno** [comment]
> I don't think quarantine has an effect on inability to restart and update from within VSCode, as I have tried it earlier.

It definitely does!

Please let me know how it goes.

**Comment by Haibao425** [comment]
I added Visual Studio Code.app into Developer Tools in Max OS -> Security&Privacy -> Privacy tab.

**Comment by morozgrafix** [comment]
@Haibao425 I don't see option for Developer Tools in Security&Privacy -> Privacy Tab. There is a chance that part of the settings is managed by company IT.

@joaomoreno when I do a fresh install OS X marks everything in `/Applications/Visual Studio Code` with quarantine attribute for some reason.

I just attempted to follow steps outlined in https://github.com/microsoft/vscode/issues/7426#issuecomment-425093469 which was referenced here https://code.visualstudio.com/docs/setup/mac#_vs-code-fails-to-update

```
sudo chown $USER ~/Library/Caches/com.microsoft.VSCode.ShipIt/*
xattr -dr com.apple.quarantine /Applications/Visual\ Studio\ Code.app
```

Will report back when next update becomes available

**Comment by joaomoreno** [comment]
Good to know. Closing this for now.

**Comment by morozgrafix** [comment]
@Haibao425 don’t see it on 10.4.x ¯\_(ツ)_/¯

**Comment by Haibao425** [comment]
> @Haibao425 I don't see option for Developer Tools in Security&Privacy -> Privacy Tab. There is a chance that part of the settings is managed by company IT.
> 
> @joaomoreno when I do a fresh install OS X marks everything in `/Applications/Visual Studio Code` with quarantine attribute for some reason.
> 
> I just attempted to follow steps outlined in [#7426 (comment)](https://github.com/microsoft/vscode/issues/7426#issuecomment-425093469) which was referenced here https://code.visualstudio.com/docs/setup/mac#_vs-code-fails-to-update
> 
> ```
> sudo chown $USER ~/Library/Caches/com.microsoft.VSCode.ShipIt/*
> xattr -dr com.apple.quarantine /Applications/Visual\ Studio\ Code.app
> ```
> 
> Will report back when next update becomes available

It works with the commands
