### ISSUE TITLE
regarding malfunction of extensions

### ISSUE THREAD

**Issue by GUDDUVK** [microsoft/vscode#95401]
extension host terminated unexpectedly
![Untitled](https://user-images.githubusercontent.com/54724299/79414193-9e57e000-7fc7-11ea-89ee-a9c218de64a9.png)

**Comment by GUDDUVK** [comment]
how to resolve this please help..!??

**Comment by gjsjohnmurray** [comment]
Did you see #94858 which is currently pinned at the top of the Issues page on GH?
