### ISSUE TITLE
View as DataFrame when debugging python

### ISSUE THREAD

**Issue by LastsForever** [microsoft/vscode#95405]
Python extensions lack the feature "View as DataFrame" As Pycharm or Spyder do. It will be very helpful when supporting this feature.
[https://www.jetbrains.com/help/pycharm/viewing-as-array.html](url)

-------------------------------------------------------------------
There was a same issue, but it was closed! Why?
[https://github.com/microsoft/vscode/issues/87262](url)

**Comment by chrmarti** [comment]
/causedByExtension

This is functionality provided by the Python extension. Please file a new feature request for it here: https://github.com/microsoft/vscode-python/issues/new/choose
