### ISSUE TITLE
Support parsing TSDoc string comments

### ISSUE THREAD

**Issue by christianalfoni** [microsoft/vscode#95408]
Hi there! I am using String Literal types to define classnames and would love to populate with some more information.

So basically:

```ts
type TClassnames = 
   /** Some docs about red-500 */
    | 'bg-color-red-500'
   /** Some docs about red-600 */
    | 'bg-color-red-600'
```

I would love to populate the docs on the right side of the intellisense:

<img width="521" alt="Screenshot 2020-02-12 at 07 31 36" src="https://user-images.githubusercontent.com/3956929/74308921-c0d04180-4d69-11ea-8953-48b7da62baa7.png">

This is how we can document with properties:

![Screenshot 2020-02-12 at 10 10 59](https://user-images.githubusercontent.com/3956929/74324332-31398b80-4d87-11ea-8f2e-e15b3ff67433.png)

Which would be amazing to have on string literals.

I thought it was a TSDoc issue, but given this context: https://github.com/microsoft/tsdoc/issues/164, it seems to be VSCode not parsing it?

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file an issue upstream](https://github.com/microsoft/TypeScript/issues/new/choose) so that they can take a look
