### ISSUE TITLE
Outline display unusual

### ISSUE THREAD

**Issue by conghaixu** [microsoft/vscode#95417]
Issue Type: <b>Bug</b>

Outline display unusual when coding is UTF-16

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18363

**Comment by chrmarti** [comment]
Please attach a screenshot.

**Comment by conghaixu** [comment]
![unusual](https://user-images.githubusercontent.com/14147368/79705233-8b0a8480-82e7-11ea-8437-ec7468f19a1c.png)
![normal](https://user-images.githubusercontent.com/14147368/79705239-9362bf80-82e7-11ea-9a7c-683b406f5ba6.png)
