### ISSUE TITLE
Format on save does not seem to work anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#95419]
This seems to happened recently, not sure what it could be.

**Comment by jrieken** [comment]
works for me

**Comment by bpasero** [comment]
This is selfhost (insiders) our workspace:

![Kapture 2020-04-16 at 11 40 48](https://user-images.githubusercontent.com/900690/79441136-285b7500-7fd7-11ea-94b4-6e913bbf889f.gif)

File is: `editorContextKeys.ts`

**Comment by jrieken** [comment]
Log files?

**Comment by bpasero** [comment]
I debugged this and see that we correctly call into `$provideDocumentFormattingEdits` and the result is empty edits, so this seems to be a TS regression. I am using 3.9.x.

**Comment by jrieken** [comment]
> and the result is empty edits, so this seems to be a TS regression. I am using 3.9.x.

Must be specific for that case because I am happy with 3.9.0-dev.20200413
