### ISSUE TITLE
keybinding gets lost frequently

### ISSUE THREAD

**Issue by chaoxu-alex** [microsoft/vscode#95412]
Keyboard shortcut gets lost easily after rebind. In my case, I remapped navigateForward/Back to cmd+]/cmd+[, but it get's lost frequently without knowing why, and when I open binding window, the binding is there, but not shown after menu item.

**Comment by chrmarti** [comment]
Please attach you keybindings.json. (`F1` > `Preferences: Open Keyboard Shortcuts (JSON)`)
