### ISSUE TITLE
On Mac french keyboard layout the backslash '/' blocked by shortcuts 

### ISSUE THREAD

**Issue by nie-xin** [Microsoft/vscode#9541]
- VSCode Version: 1.3.1
- OS Version:  OS X EI Captitan version 10.11.5

For a mac french keyboard (azerty layout), the general way to make a backslash '\' is by shift+alt+:

However, this combination is overwrited by vscode shortcut:

```
{ "key": "shift+alt+.",           "command": "closeTag.closeHTMLTagInPlace",
                                     "when": "editorTextFocus" },
```

which says

```
For your current keyboard layout press 
⇧⌥:
Key or key sequence (separated by space)
```

That makes it impossible to type '\', even after I changed the default shortcuts combination.

Any idea?

**Comment by kieferrm** [comment]
@nie-xin pls file the issue against the extension that registers this command.

**Comment by nie-xin** [comment]
Thanks @kieferrm , I didn't release that it was caused by closeHTMLTag extension :)
