### ISSUE TITLE
Search editor - Remember recent filter regexes

### ISSUE THREAD

**Issue by chavlji** [microsoft/vscode#95420]
[Search inside editor](https://github.com/microsoft/vscode/issues/88154) is an awesome feature!

It would, however, be much more useful with that small tweaks:
- remember state (show/hidden) of `Search details` panel
- remember the last content of fields `files to include` and `files to exclude`
- remember recent file filters

Sublime does all of this very good and I've used it all the time:
![Screenshot 2020-04-16 at 09 55 26](https://user-images.githubusercontent.com/5729421/79430284-ff33e800-7fc8-11ea-993e-4a2c9a0ff50b.jpg)

**Comment by gjsjohnmurray** [comment]
Are you aware that cursor-up in these fields can recall previous entries?

**Comment by roblourens** [comment]
You can navigate history with the arrow keys like @gjsjohnmurray points out

**Comment by chavlji** [comment]
Nope, it doesn't work in these fields. I'm using the latest insider version.

Besides don't just close it. Even if it would work it would only answer my 3rd point. What about the 1st and 2nd?

**Comment by roblourens** [comment]
1. The state is remembered per workspace. Can you give some more details about where you are not seeing that work?
2. The arrow keys
3. Can you explain what you mean by file filters?

**Comment by chavlji** [comment]
Sure. Thanks for reopening!

I press `cmd+shift+f` and set the search like this:
![Screenshot 2020-04-16 at 20 27 10](https://user-images.githubusercontent.com/5729421/79493038-30400700-8021-11ea-829f-c3ec0ea744d4.jpg)

I close the search tab.
Press `cmd+shift+f`again and all fields are reset:

![Screenshot 2020-04-16 at 20 27 35](https://user-images.githubusercontent.com/5729421/79493239-79905680-8021-11ea-8965-65a5bbcd3351.jpg)

**How it should be**
imo when I reopen it, it should look like where I've left it:
- search filed filled with previous string ('target')
- `search details` opened
- `files to include/exclude` filled with previous filters:
![Screenshot 2020-04-16 at 20 38 15](https://user-images.githubusercontent.com/5729421/79493747-3a163a00-8022-11ea-8833-cc5b50bace88.jpg)

Up/down arrows do work. But it would be nice if I wouldn't have to focus fields all the time and pressing arrow keys to restore the state...

**Comment by JacksonKearl** [comment]
Please try out `"search.searchEditor.experimental.reusePriorSearchConfiguration": true` in Insiders and let me know what you think.

Its a hidden setting, you'll have to enter it into settings.json manually.

**Comment by chavlji** [comment]
What do I think? I love it!!!

Thank you @JacksonKearl !

**Comment by JacksonKearl** [comment]
Discussing options for the future in #89353
