### ISSUE TITLE
typescript server died

### ISSUE THREAD

**Issue by benjaminwolkchen** [microsoft/vscode#95422]
Issue Type: <b>Bug</b>

typescript server died 5 times, will not be enabled again.

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-13T14:40:29.529Z)
OS version: Linux x64 5.3.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6100 Six-Core Processor (6 x 2318)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|3.75GB (0.94GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
es6-css-minify|olb|3.3.2
LiveServer|rit|5.6.1

</details>

**Comment by chrmarti** [comment]
Does this reproduce with source that you can share?

**Comment by benjaminwolkchen** [comment]
I was working with this Git(hub) Repo when the error happened: https://github.com/benjaminwolkchen/awesomebible
Its an ionic Project that uses angular.
The size of this Repo is 790 kB and it contains 28 files.

**Comment by mjbvz** [comment]
Please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). After installing that extension and restarting VS Code do you still see the issue?
