### ISSUE TITLE
getLinesViewportData api in verticalObjects is returning range where start line and end line is not visible

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#9542]
verticalObjects.getLinesViewportData() returns the view lines data those are not visible in the current view port. 

- When a line is wrapped and is not visible completely on the top, Some times start line number value is the wrapped line # which is not visible.
- End line number is always one number greater than visible end line

As a result, In Vim:
- `H` and `L` commands seem to go to outside the view.

**Comment by sandy081** [comment]
Closing this, since this is no longer an issue for VIM.

**Comment by alexandrudima** [comment]
@sandy081 Opened #10934 to follow up
