### ISSUE TITLE
Version 1.44.1 has problems in search: every search reports few result and executes forever

### ISSUE THREAD

**Issue by grazianobassi** [microsoft/vscode#95421]
Use Visual studio Code version 1.44.1
Execute a search with many potential result.
I expect all results but i receive few results and the search executes forever if not stopped.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo What platform? Also, is this a new problem for you with 1.44.1 (i.e. a regression)? Detailed steps to recreate the issue will also be useful, preferably on public source. And screenshots.

**Comment by Pollizzio** [comment]
Same problem.
Regression, the Search was working fine until this update.
Just go to "Search" tab and perform any search. No result or partials and progress bar loading endlessly.

Version: 1.44.1
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:47:00.296Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by gjsjohnmurray** [comment]
The fix mentioned by @roblourens is in 1.44.2 which is now available. Please update and retest.

**Comment by grazianobassi** [comment]
I tested version 1.44.2 and verified that now the search works properly. Thank you
