### ISSUE TITLE
Dark+ theme changed between 1.44 & 1.45

### ISSUE THREAD

**Issue by GongT** [microsoft/vscode#95434]
- VSCode Version: insider 1.45.0
- OS Version: Win 10 x64

# ← 1.44  |  1.45 →
![image](https://user-images.githubusercontent.com/2265048/79447847-139cd280-8013-11ea-982e-ab626f9991f3.png)

and this icon seems broken.
![image](https://user-images.githubusercontent.com/2265048/79448067-624a6c80-8013-11ea-9762-c44fe5712134.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by robertrossmann** [comment]
I suspect this is due to `Semantic Highlighing` being enabled by default in one of the latest updates... 🤔 You can try to turn it off in your Settings - `editor.semanticHighlighting.enabled`.

**Comment by IllusionMH** [comment]
1) Difference in highlight - most likely this is due semantic highlight (as mentioned above)

2) Found same issue - reported in #95437

**Comment by IllusionMH** [comment]
After reload I can confirm change in hightlight only started in today's build and looks like this is new color for constant values which is strange (especially after they were colored as functions before).

@aeschli can you clarify what changed here?
Looks worse than before especially with chosen color (as usually with any change in highlight 😄 )

I see crossed `foreground	entity.name.function { "foreground": "#DCDCAA" }` in the end for scopes info block.

**Comment by joaomede** [comment]
I updated today and realized that "editor.semanticHighlighting.enabled: false" does not work on false.

**Comment by aeschli** [comment]
dup of #89945
