### ISSUE TITLE
Account icon looks incorrectly in Insiders build

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#95437]
Issue Type: <b>Bug</b>

Account icon changed from outline with silhouette to something unhuman (maybe rotated husky face)
![image](https://user-images.githubusercontent.com/1312662/79448769-affeaf00-7fea-11ea-8a05-3168f515b6b6.png)

/cc @misolori 

VS Code version: Code - Insiders 1.45.0-insider (6e9a34c0de4181a99f11e106733ee3e8c9db79f1, 2020-04-16T05:45:56.832Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (16.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
I think it lacks any contrast between the background within the circle and the what I assume is supposed to be the body of the person (highlighted in red by me below on a clip from how it appears with 'Quiet Light' theme)

![image](https://user-images.githubusercontent.com/6726799/79453003-f818d400-7fe0-11ea-86df-187f1db23909.png)

**Comment by IllusionMH** [comment]
My theory is that addition of circle around silhouette went wrong and filled whole area. Therefore we can only see couple of empty areas from previous outline.

Otherwise it will be really bold solid icon where other icons were switched to light outline variants

**Comment by misolori** [comment]
This appears to be an icon rendering issue on Windows, looking into this now. Icon should look like this:

![image](https://user-images.githubusercontent.com/35271042/79460314-7d809200-7fa9-11ea-9f5d-32d1bf445ed7.png)

**Comment by misolori** [comment]
Should be fixed now:

![image](https://user-images.githubusercontent.com/35271042/79465992-dacc1180-7fb0-11ea-9cd0-dd590850b08c.png)
