### ISSUE TITLE
"Add all missing imports" adds them all in one line

### ISSUE THREAD

**Issue by jkasztur** [microsoft/vscode#95430]
- VSCode Version: 1.44.0
- OS Version: Linux x64 5.3.0-46-generic

Steps to Reproduce:

1. Create some typescript code without added imports
2. Add imports

Does this issue occur when all extensions are disabled?: Yes

![ezgif-6-17a8f65709a1](https://user-images.githubusercontent.com/6042169/79446302-4d071b00-7fde-11ea-8c65-a10324916402.gif)

**Comment by mjbvz** [comment]
Please share code to reproduce the issue

**Comment by jkasztur** [comment]
@mjbvz For me this happens for every import, e.g this code with axios and koa packages:
```

const client: AxiosInstance = Axios.create()
const router: Router = new Router()
```
to reproduce the imports in single line:
- there are no previous imports(if there are, the new ones are added correctly)
- the code does not start on first line

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/TypeScript/issues/38082 to track upstream
