### ISSUE TITLE
Sree

### ISSUE THREAD

**Issue by sreekumar360** [microsoft/vscode#95431]
Issue Type: <b>Feature Request</b>

No file sorting on the vs code explorer

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18363

**Comment by sreekumar360** [comment]
No file sorting on the vs code explorer

**Comment by gjsjohnmurray** [comment]
/duplicate

Also, please use descriptive titles for issues you create.
