### ISSUE TITLE
Quick Open View (CTRL+Q) focuses on Search instead of Explorer by default

### ISSUE THREAD

**Issue by matefriedl** [microsoft/vscode#95448]
- VSCode Version: 1.44.1
- OS Version: Win10 1803

Steps to Reproduce:

1. Press `CTRL+Q` to bring up Quick Open View (aka quick access view).
2. Observe how Search is in focus by default instead of Explorer.

Expected (1.43.2):
![image](https://user-images.githubusercontent.com/63063644/79461035-ea217e00-7ff5-11ea-96c8-14e3dcb9d268.png)

Actual (1.44.1):
![image](https://user-images.githubusercontent.com/63063644/79461132-0b826a00-7ff6-11ea-924d-abaefd403ab8.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by matefriedl** [comment]
Clicking on related issue accidentally wiped by nicely written bug report, please stand by while i fix it..

**Comment by yinbun** [comment]
Turns out I am not alone

**Comment by bpasero** [comment]
Arguably should maybe in this case not do that.
