### ISSUE TITLE
[Source Control][Style] Missing gap between buttons

### ISSUE THREAD

**Issue by TobiasSekan** [microsoft/vscode#95447]
<img width="313" alt="2020-04-16 14_57_49-Visual Studio Code" src="https://user-images.githubusercontent.com/17874713/79459241-4931c380-7ff3-11ea-8ba8-5cb7864a8ca1.png">

Version: 1.44.1 (user setup)
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:48:12.622Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Start VSCODE (without a repo)
2. Open SMC

Does this issue occur when all extensions are disabled?: Yes

**Comment by kanlukasz** [comment]
I can confirm it too

**Comment by joaomoreno** [comment]
This is already fixed in the latest insiders.
