### ISSUE TITLE
Completion inside strings of *.json files are overridden by the injected variables completion provided by default

### ISSUE THREAD

**Issue by apupier** [microsoft/vscode#95449]
- VSCode Version: 1.44.0
- OS Version: Fedora 31

Steps to Reproduce:

1. create an extension where you register a CompletionItemProvider on tasks.json files
2. provide some completion for it
3. launch the extension
4. open a tasks.json file
5. for instance use this content:

```
{
    "version": "2.0.0",
    "tasks": [
		{
			"label": "My Task",
			"type": "shell",
			"command": "echo Hello",
			"problemMatcher": []
		}
    ]
}
```
6. try calling completion inisde a string value (for instance in "echo Hello")

--> there is only the completion for the injected variables, other completions are not available

Does this issue occur when all extensions are disabled?: Yes

To ease reproducing, I created a branch based on vscode-extension-samples.
You can see the only differences provided to test it in this dummy PR https://github.com/apupier/vscode-extension-samples/pull/1

when calling completion on the first line, we can notice that the completion provided by the examples are provided:
![Screenshot from 2020-04-16 15-22-54](https://user-images.githubusercontent.com/1105127/79461274-3c629f00-7ff6-11ea-9801-a3efafc9852a.png)

if it is called inside String values, only the injected variables are provided:
![Screenshot from 2020-04-16 15-23-40](https://user-images.githubusercontent.com/1105127/79461343-543a2300-7ff6-11ea-84cd-bc6c77a23b64.png)

**Comment by alexr00** [comment]
Looks like this is true of any string value in any json file. If I change the document filter to settings.json instead of tasks.json I see the same behavior.

**Comment by aeschli** [comment]
@apupier What's the document selector  that you use when registering your completion provider?

**Comment by jrieken** [comment]
> The variable provider has language: jsonc, '**/task.json an is probably winning as it is more specific than yours. @jrieken for the details.

They are all equals - there is only general match (using `*`) and all other matches. I'd say this JSON's adventures word definition which means your suggestions are automatically filter unless you set the `filterText` and/or `range` properties correctly.

**Comment by apupier** [comment]
> > The variable provider has language: jsonc, '**/task.json an is probably winning as it is more specific than yours. @jrieken for the details.
> 
> They are all equals - there is only general match (using `*`) and all other matches. I'd say this JSON's adventures word definition which means your suggestions are automatically filter unless you set the `filterText` and/or `range` properties correctly.

I tried to ask on the slack but got no answer.
@jrieken Can you precise what would be a correct value?

Based on the documentation, I don't understand why I should provide any of them. They are both optional. I even less understand why not having them would hide some of the completions.

```


		/**
		 * A string that should be used when filtering a set of
		 * completion items. When `falsy` the [label](#CompletionItem.label)
		 * is used.
		 */
		filterText?: string;
```

```
		/**
		 * A range or a insert and replace range selecting the text that should be replaced by this completion item.
		 *
		 * When omitted, the range of the [current word](#TextDocument.getWordRangeAtPosition) is used as replace-range
		 * and as insert-range the start of the [current word](#TextDocument.getWordRangeAtPosition) to the
		 * current position is used.
		 *
		 * *Note 1:* A range must be a [single line](#Range.isSingleLine) and it must
		 * [contain](#Range.contains) the position at which completion has been [requested](#CompletionItemProvider.provideCompletionItems).
		 * *Note 2:* A insert range must be a prefix of a replace range, that means it must be contained and starting at the same position.
		 */
		range?: Range | { inserting: Range; replacing: Range; };
```
