### ISSUE TITLE
"Collapse All" button does not work in Debug -> Variables. Python. 

### ISSUE THREAD

**Issue by sartyukhov** [microsoft/vscode#95440]
- VSCode Version: 1.44.1
- OS Version: Manjaro Linux
- Extensions: ["ms-python.python", "VisualStudioExptTeam.vscodeintellicode"]
Steps to Reproduce:

1. Start debugging python project in docker container with installed extensions.
2. Stop somewhere by breakpoint
3. Open Run -> Variables panel
4. Click collapse all
5. Nothing happend, at all

![image](https://user-images.githubusercontent.com/23495999/79453564-88134980-7ff2-11ea-9565-c9d5d85d21f7.png)

Does this issue occur when all extensions are disabled?: No. Can't debug python project without python extension.

**Comment by isidorn** [comment]
@sartyukhov thanks for filling this.
@sbatten @sandy081 with the view refactoring work the timing changed when the view is asked for actions and when it is rendered. So actions were instiated before there was an instance of the tree present. I fixed this by changing the action to pass in the getter for the tree so it can retrieve it when it is being run not constructed

**Comment by sartyukhov** [comment]
Cool, thanks!

**Comment by sandy081** [comment]
Thanks for fixing @isidorn 

May be we shall move away from old model `getActions` to use `MenuRegistry` ?

Eg: 
https://github.com/microsoft/vscode/blob/88e98034a84ecbf65b7650f664a73a990457120a/src/vs/workbench/browser/parts/views/treeView.ts#L336-L356

**Comment by isidorn** [comment]
That works for me
