### ISSUE TITLE
VS Code detected unresponsive when starting Vscode

### ISSUE THREAD

**Issue by Bno93** [microsoft/vscode#95454]
- VSCode Version: 1.44.1
- OS Version: Win10 (1909)

Does this issue occur when all extensions are disabled?: Yes

Hi 

While starting vscode on my windows laptop I get the "window is not responding" message mutlipe times. I've also reinstalled vscode and I search for older issues like #88068 and #84914 but I'm not in a citrix environments, also a reboot didn't helped. 

Here is the console log of 'code --verbose' 

`
[main 2020-04-16T13:57:57.626Z] Starting VS Code
[main 2020-04-16T13:57:57.627Z] from: c:\Users\B_SCHWEIKERT\AppData\Local\Programs\Microsoft VS Code\resources\app
[main 2020-04-16T13:57:57.627Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'disable-extensions': false,
  'disable-gpu': false,
  telemetry: false,
  logExtensionHostCommunication: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickinput': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'disable-user-env-probe': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  trace: false,
  'force-user-env': false,
  'no-proxy-server': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false
}
[main 2020-04-16T13:57:57.629Z] Resolving machine identifier...
[main 2020-04-16T13:57:57.629Z] Resolved machine identifier: 14738ffe7715a92eadba4ad9bd8cb1545aedb51bea8fcd87e82966456e4a2962 (trueMachineId: undefined)
[main 2020-04-16T13:57:57.668Z] [storage state.vscdb] open(c:\Users\B_SCHWEIKERT\AppData\Roaming\Code\User\globalStorage\state.vscdb, retryOnBusy: true)
[main 2020-04-16T13:57:57.669Z] lifecycle (main): phase changed (value: 2)
[main 2020-04-16T13:57:57.672Z] windowsManager#open
[main 2020-04-16T13:57:57.676Z] window#validateWindowState: validating window state on 2 display(s) { mode: 1, x: -32000, y: -32000, width: 1644, height: 876 }
[main 2020-04-16T13:57:57.676Z] window#ctor: using window state { width: 1024, height: 768, mode: 1 }
[main 2020-04-16T13:57:57.742Z] lifecycle (main): phase changed (value: 3)
[main 2020-04-16T13:57:57.744Z] update#setState idle
[main 2020-04-16T13:57:57.879Z] [storage state.vscdb] Trace (event): PRAGMA user_version = 1;
[main 2020-04-16T13:57:57.932Z] [storage state.vscdb] Trace (event): CREATE TABLE IF NOT EXISTS ItemTable (key TEXT UNIQUE ON CONFLICT REPLACE, value BLOB)
[main 2020-04-16T13:57:57.933Z] [storage state.vscdb] Trace (event): SELECT * FROM ItemTable
[main 2020-04-16T13:57:57.935Z] [storage state.vscdb] getItems(): 78 rows
[main 2020-04-16T13:57:58.037Z] [storage state.vscdb] updateItems(): insert(Map(3) {storage.serviceMachineId => d8da7738-b732-4248-a926-4fb315446127, telemetry.lastSessionDate => Thu, 16 Apr 2020 13:53:14 GMT, telemetry.currentSessionDate => Thu, 16 Apr 2020 13:57:57 GMT}), delete(Set(0) {})
[main 2020-04-16T13:57:58.039Z] [storage state.vscdb] Trace (event): BEGIN TRANSACTION
[main 2020-04-16T13:57:58.040Z] [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('storage.serviceMachineId','d8da7738-b732-4248-a926-4fb315446127'),('telemetry.lastSessionDate','Thu, 16 Apr 2020 13:53:14 GMT'),('telemetry.currentSessionDate','Thu, 16 Apr 2020 13:57:57 GMT')
[main 2020-04-16T13:57:58.042Z] [storage state.vscdb] Trace (event): END TRANSACTION
[main 2020-04-16T13:58:00.746Z] getShellEnvironment: running on Windows, skipping
[main 2020-04-16T13:58:27.744Z] update#checkForUpdates, state =  idle
[main 2020-04-16T13:58:27.744Z] update#setState checking for updates
[main 2020-04-16T13:58:27.745Z] RequestService#request https://update.code.visualstudio.com/api/update/win32-x64-user/stable/a9f8623ec050e5f0b44cc8ce8204a1455884749f
[main 2020-04-16T13:58:27.930Z] [VS Code]: detected unresponsive
[main 2020-04-16T13:58:28.920Z] update#setState idle
[main 2020-04-16T13:59:03.859Z] [VS Code]: detected unresponsive
[main 2020-04-16T13:59:32.978Z] Shared process: IPC ready
[main 2020-04-16T13:59:33.545Z] Shared process: init ready`

**Comment by Bno93** [comment]
It also doesn't matter if I open vscode with a project e.g. java gradle or a single file or a new instance.

**Comment by chrmarti** [comment]
Please follow https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly to collect startup measurements.

**Comment by Bno93** [comment]
Hi, thanks for the reply. 
Today it seems to be back to normal behavior. 
I can't make out why this was happening.

**Comment by chrmarti** [comment]
Let us know when it occurs again!
