### ISSUE TITLE
The setting workbench.startupEditor = readme does not seem to work

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#95450]
![image](https://user-images.githubusercontent.com/172399/79462099-5e105600-7ff7-11ea-9261-b980b2e2b299.png)

**Comment by bpasero** [comment]
I tested this yesterday and felt it does work.

**Comment by chrmarti** [comment]
@bpasero You're right, it works when opening a folder, but not when only reloading the window. That's by design.

@egamma Could you check if that explains it?

**Comment by chrmarti** [comment]
Works for me. Please reopen if still an issue.
