### ISSUE TITLE
File paths with "+" character not identified as links in terminal

### ISSUE THREAD

**Issue by niklasnylen** [microsoft/vscode#95452]
When paths to files containing the + character are printed to the terminal they do not become clickable links.

Steps to reproduce:
```
mkdir foo+bar foo_bar && echo "sample text" > foo+bar/foo.txt && echo "sample text" > foo_bar/foo.txt

# This prints a path that is not clickable
echo "foo+bar/foo.txt" 
# This prints a path that is clickable
echo "foo_bar/foo.txt"
```

The "+" character in folder names is commonly used in matlab development since starting a folder name with + makes it a package.

**Comment by Tyriar** [comment]
This actually works with the new system we're working on. Try setting this in Insiders:

```
"terminal.integrated.experimentalLinkProvider": true
```

**Comment by niklasnylen** [comment]
I just tried it (Windows 10, VSCode Insiders 1.45.0) and it partially works.

If the path is `foo+bar/foo.txt` and the pointer is hovered anywhere after the last + in the path only the part after the last + is linked, i.e. `bar/foo.txt`

However if the pointer is hovered over the path anywhere before the last + the full path is linked. This also applies if the pointer is hovered over the first part of the path, then moved to the last part of the path.

**Comment by Tyriar** [comment]
Are you sure you enabled the setting? It works fine for me:

![b6858fbf-a85d-4bce-a11d-77c56691477a](https://user-images.githubusercontent.com/2193314/79580175-7aef6c80-807d-11ea-9e04-fe2ac5c94400.gif)

**Comment by niklasnylen** [comment]
Yes, the setting is enabled
![image](https://user-images.githubusercontent.com/51982908/79580791-d5aeb580-80c9-11ea-8c05-2835bcad58c5.png)

![image](https://user-images.githubusercontent.com/51982908/79581231-6d140880-80ca-11ea-9b9a-27b9de7d8227.png)

**Comment by Tyriar** [comment]
And you're up to date? I'm on yesterday's build

Version: 1.45.0-insider (user setup)
Commit: 6e9a34c0de4181a99f11e106733ee3e8c9db79f1
Date: 2020-04-16T05:45:56.832Z
Electron: 7.2.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by niklasnylen** [comment]
I'm on today's build:
Version: 1.45.0-insider (user setup)
Commit: a3083e58e2a9e77f60e531acaa32e18527ae8439
Date: 2020-04-17T08:09:47.238Z (7 hrs ago)
Electron: 7.2.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by Tyriar** [comment]
Weird... I updated and still don't see it. What happens when you ctrl+click the link? Does it open a file or a quick pick?

**Comment by niklasnylen** [comment]
If I click the full path it opens the file as expected. If I click the partial path it opens a new instance of VSCode but doesn't open any file or folder in it.

**Comment by Tyriar** [comment]
Had this changed at all? A lot of work has gone into links in the past few days.

**Comment by niklasnylen** [comment]
Tested in today's build (

If I hover over the file name, I see this:
![image](https://user-images.githubusercontent.com/51982908/80098628-7fc88a80-856d-11ea-8c68-2a5ac4e15578.png)

If I hover before the last +, I get this
![image](https://user-images.githubusercontent.com/51982908/80098768-b56d7380-856d-11ea-8124-842aa89425ea.png)

**Comment by Tyriar** [comment]
This might have been caused by https://github.com/microsoft/vscode/issues/95966
