### ISSUE TITLE
HTML language support in PHP files is really, really bad

### ISSUE THREAD

**Issue by gavin310** [microsoft/vscode#95453]
When editing `.html` files, the HTML language support is awesome. Indenting is almost always perfect, custom tags are supported, tag and property recommendations work great.

However, when editing a `.php` file that contains HTML, the HTML language support is horrible. It rarely gets the indentation correct, doesn't suggest tags or properties, doesn't support custom tags, and many other annoyances. PHP and HTML go hand-in-hand, so there's no reason why the HTML support should be so horrible.

I understand that this is because it's using the PHP language which has very basic HTML support, but when editing PHP templates and things like that it's very annoying. If there's a way to combine the PHP language with the HTML language that would make things much easier.

**Comment by chrmarti** [comment]
Have you tried any of the PHP extensions: https://marketplace.visualstudio.com/search?term=php&target=VSCode&category=All%20categories&sortBy=Relevance ?
