### ISSUE TITLE
Visual studio window automatically toggles in and out of full screen very fast

### ISSUE THREAD

**Issue by dhiren-eng** [microsoft/vscode#95457]
Issue Type: <b>Performance Issue</b>

VSCode suddenly toggles in and out of full screen so fast i.e. in a very high frequency and it stops when I press the alt button . It happens again at intervals of 5-7 minutes everytime.  When the sudden screen toggling happens it is seen that VS Code occupies 80% of CPU in the processes section of the task manager and I am unable to anything else in my system when this happens. (See screenshot below)

![image](https://user-images.githubusercontent.com/59474883/79472510-8f9e1700-8021-11ea-8ea8-880b70ebada1.png)

Another BIG issue is that while running code on react development server in VS Code (when the toggling issue is not happening) I notice the same thing that VS Code occupies 80% of CPU and the whole system gets drastically slowed down. It takes almost 2 minutes to switch from VS Code to chrome.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU B960 @ 2.20GHz (2 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.85GB (0.56GB free)|
|Process Argv|C:\Users\lenovo\Desktop\React Stephen Project\TeesExpress|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    72	  8848	code main
    0	    23	  2664	   utility
    0	   175	  3508	   window (Header.js - TeesExpress - Visual Studio Code)
    0	     9	  4860	     watcherService 
    0	     4	  8444	       console-window-host (Windows internal process)
    0	    75	  6108	     extensionHost
    0	   154	  4680	       electron_node tsserver.js 
    0	    43	  5340	         electron_node typingsInstaller.js typesMap.js 
    0	    48	  5792	       electron_node tsserver.js 
    0	    33	  6988	     searchService
    0	     4	  7248	     winpty-process
    0	     2	  6356	       C:\WINDOWS\system32\cmd.exe
    0	     6	  7836	       console-window-host (Windows internal process)
    0	    11	  5904	   electron-crash-reporter
    5	    63	  6136	   window (Issue Reporter)
    0	    76	  8120	   shared-process
    2	    96	  9208	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Header.js - TeesExpress - Visual Studio Code)
|    Folder (TeesExpress): 51 files
|      File types: js(21) json(5) html(2) png(2) prettierrc(1) gitignore(1)
|                  md(1) ico(1) txt(1) css(1)
|      Conf files: package.json(2);
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
prettier-vscode|esb|4.4.0
LiveServer|rit|5.6.1
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
