### ISSUE TITLE
Arabic Typo

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#95455]
Issue Type: <b>Performance Issue</b>

After i update this version the supporting for RTL language has a problem

see this type the > in the html dose not close correctly
<option value="ذكر">ذكر</option>

<option vlaue="ذكر">ذكر</option>

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.44GB (0.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    80	 19436	code main
    0	   155	   140	   gpu-process
   11	    75	  5328	   shared-process
    0	    14	  9180	   electron-crash-reporter
    2	    68	 24808	   window (Issue Reporter)
    0	   188	 25876	   window (visitors.php - Untitled (Workspace) - Visual Studio Code)
    0	    42	  7144	     watcherService
    0	   134	 15568	     extensionHost
    0	   187	 20424	       electron_node intelephense.js 
    0	    35	 21128	     searchService
    0	    25	 26680	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (visitors.php - Untitled (Workspace) - Visual Studio Code)
|    Folder (ehjizle.com): 1787 files
|      File types: png(669) svg(281) eps(249) psd(244) php(92) jpg(46) ttf(20)
|                  zip(15) html(15) css(12)
|      Conf files:
|    Folder (cbi): 138 files
|      File types: php(91) md(6) json(3) css(3) jpg(2) dist(2) lock(1) zip(1)
|                  DS_Store(1) gitignore(1)
|      Conf files:
|    Folder (archive.local): 1717 files
|      File types: jpg(748) php(387) pdf(167) xlsx(81) png(76) md(37) txt(14)
|                  cs(10) xls(8) xml(6)
|      Conf files: csproj(1) sln(1)
|    Folder (ninava.gov.iq): 5956 files
|      File types: pdf(2206) php(802) gif(727) jpg(631) png(355) rar(274)
|                  js(97) xlsx(81) swf(63) txt(40)
|      Conf files: csproj(1) sln(1);
```

</details>
<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.3.11
vscode-eslint|dba|2.1.3
vscode-html-css|ecm|0.2.3
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
php-debug|fel|1.13.0
php-pack|fel|1.0.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
mssql|ms-|1.9.0
material-icon-theme|PKi|4.0.1
vscode-icons|vsc|10.1.1
html-css-class-completion|Zig|1.19.0

(3 theme extensions excluded)

</details>

**Comment by danyeh** [comment]
We don't have localization language pack supports RTL language.
@chrmarti , assign back to you as the issue description more about enable RTL language support other than localization of RTL language itself.

**Comment by aeschli** [comment]
@AhmedNabeeh Can you add more information?
Maybe add screenshots,  or even a screencast?

**Comment by aeschli** [comment]
Closing as more information is needed.
