### ISSUE TITLE
Show documentation not showing up in right click menu

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#95461]
https://github.com/microsoft/vscode-eslint/issues/932

Steps to repro:

- clone https://github.com/Microsoft/vscode-eslint.git
- checkout `88aaa9e`
- chdir `playgrounds/ts`
- npm install
- open VS Code with eslint extension installed.
- open test.ts
- make sure problems view is not visible
- reload Window
- wait until ESLint errors show up in editor
- open problems view
- click on problem to see quick fixes. **Observe**: it doesn't work
- reload Window
- wait until problems show up in problems view.
- click on problem to see quick fixes: **Observe**: it does work

**Comment by jeanp413** [comment]
Created a PR #95653 that fixes this
