### ISSUE TITLE
Still can't format user settings.json in combination with editor.defaultFormatter

### ISSUE THREAD

**Issue by texastoland** [microsoft/vscode#95468]
- VSCode Version: 1.45.0-insider
- OS Version: Darwin  x64 19.4.0

Same exact issue as #79038 which was closed without explanation. Same results if configured for `jsonc` or `vscode-userdata`. Commenting out `editor.defaultFormatter` resolves the issue. I can't provide any additional insight relative to that thread and prettier/prettier-vscode#911. Was no one there able to repro?

**Comment by chrmarti** [comment]
It is in the fine-print: https://github.com/microsoft/vscode/issues/79038#issuecomment-528424519 says that the Prettier extension should not limit itself to `file` and `untitled` schemes, but only match on the language.

https://github.com/prettier/prettier-vscode/issues/911#issuecomment-559986406 appears to have missed that and the issue is now locked. /fyi @ntotten

**Comment by texastoland** [comment]
I saw the comment but didn't understand what it referred to after browsing Prettier's implementation. Someone else reported the same change in behavior for Beautify in the original thread: https://github.com/microsoft/vscode/issues/79038#issuecomment-528023315. It seems like Code may have introduced a breaking change that they weren't aware of. Prettier looks like the fifth most installed extension in the Marketplace and formatting editor settings sounds like a common use case. Is there anything I can do to help track down the root issue?

**Comment by jrieken** [comment]
> Is there anything I can do to help track down the root issue?

Yes. Please follow up with prettier on this. VS Code relies on uris and selector, a selector can define for what uri-scheme it works and that's what prettier does. You can see here that prettier only registers for `untitled` and `file` scheme (https://github.com/prettier/prettier-vscode/blob/30f675867fe53c62f041c575fbd60099c718734c/src/PrettierEditService.ts#L165) and as said in the original issue - parts of the settings.json are not from that scheme

**Comment by texastoland** [comment]
I'll reopen it there but I'm still unconvinced. The original reporter indicated that reverting his version of Code fixed it. Regardless whether Prettier was doing it wrong before it appears the behavior changed.

**Comment by ntotten** [comment]
@jrieken I don't think we should remove the `schema` should we? The VS Code docs mention this is recommended as we read from files? https://code.visualstudio.com/api/references/document-selector#document-scheme

Do you think we should just filter only on language or is it better to add a new selector for this type of file?

**Comment by jrieken** [comment]
> @jrieken I don't think we should remove the schema should we?

The [linked doc](https://code.visualstudio.com/api/references/document-selector#document-scheme) means that we want you to think about it :-) Often external tools have a builtin dependency on the local file system and cannot work with "just strings". However, if your tool can work with "just strings", then that's brilliant and you shouldn't artificially constrain yourself.  Use a selector like this and all is good" `{ scheme: '*', language: 'fooLang' }`

**Comment by ntotten** [comment]
@jrieken Gotcha, thanks for the info. I will do some testing and see. Right now we do read the file system for config, but there might be opportunities to allow things to work w/o a file system.

For now I addressed this issue by registering the special schema for `settings.json` https://github.com/prettier/prettier-vscode/blob/master/src/PrettierEditService.ts#L149-L155

Thanks!

**Comment by jrieken** [comment]
> Right now we do read the file system for config

Yeah, I'd say that's ok as long as you don't read a config from the file system based on some fake path of a file that doesn't exist. Or try using `vscode.workspace.fs` which allows to read contributed files systems
