### ISSUE TITLE
Asked to update twice

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#9546]
- VSCode Version: Current insiders (upgraded to 2016-07-20)
- OS Version: OS X

Steps to Reproduce:
1. Was asked to update yesterday
2. Only updated today
3. After restart I'm at insiders from 2016-07-19 and am asked to update
4. Update again, now I'm at 2016-07-20

Maybe we could just remove the prompt to update when we see a newer version on the server and then install that before prompting again?

**Comment by joaomoreno** [comment]
Won't fix any time soon.
