### ISSUE TITLE
This issue was closed but not fixed: #15564 Include newline when expanding line selection

### ISSUE THREAD

**Issue by davidpetrey** [microsoft/vscode#95467]
- VSCode Version:  1.44.1
- OS Version: Win 10

![image](https://user-images.githubusercontent.com/13895170/79486148-e5e86700-7fdb-11ea-9100-46828db54047.png)

Steps to Reproduce: 

1. Ctrl + L selects whole line and beginning of next line. Why is this the desired behavior? 
2. Same thing when you double click on the number in the Gutter. 

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by davidpetrey** [comment]
I'm a bit confused because it seems that this issue started out wanting to add the new line. But then at the bottom there is a comment about the issue not being fixed because it adds the new line. 

I only want the selected line. I'm not sure why you would want it with the added new line?
Could we have two commands? One that just selects the whole line and one that selects the line with the new line below?

#15564 Include newline when expanding line selection

**Comment by gjsjohnmurray** [comment]
When I want to omit the newline I follow the <kbd>Ctrl</kbd>+<kbd>L</kbd> with <kbd>Shift</kbd>+<kbd>LeftArrow</kbd>

**Comment by davidpetrey** [comment]
@gjsjohnmurray Sure there's lots of ways to do it. Why would I want it to work the way it currently does?  That's always seemed weird to me.

**Comment by davidpetrey** [comment]
I found a plugin that does what I want. 
https://marketplace.visualstudio.com/items?itemName=erhise.perfect-line-selection
