### ISSUE TITLE
Moving  a whole container should preserve the icon/title of the original container

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode#95472]
Issue Type: <b>Bug</b>

I moved the GitHub PRs view container to the panel then moved it back. When I moved it back, I lost the GitHub icon for the view container.

1. Move view container to the panel next to terminal
1. Move the view container back to the activity bar

Expected: view container and icon correctly show in the activity bar.
Actual: view container in the activity bar has a generic icon (everything within the view is correct).

![image](https://user-images.githubusercontent.com/1186948/79490541-e2e87900-7fd1-11ea-9aa8-55b528e88116.png)

VS Code version: Code - Insiders 1.45.0-insider (6e9a34c0de4181a99f11e106733ee3e8c9db79f1, 2020-04-16T06:35:37.145Z)
OS version: Windows_NT ia32 10.0.18363
Remote OS version: Linux x64 5.0.0-1036-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Snapdragon (TM) 8cx @ 2.84 GHz (8 x 1670)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.53GB (0.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: mhdevbox|
|OS|Linux x64 5.0.0-1036-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (2 x 2294)|
|Memory (System)|7.77GB (4.53GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
git-branch|ale|1.6.0
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
prettier-vscode|esb|4.4.0
vscode-pull-request-github|Git|0.15.0
vscode-azureappservice|ms-|0.16.5
vscode-azurefunctions|ms-|0.22.0
vscode-azureresourcegroups|ms-|0.1.0
vscode-azurestorage|ms-|0.9.0
vscode-cosmosdb|ms-|0.12.2
azure-account|ms-|0.8.9
vetur|oct|0.24.0
vue-vscode-extensionpack|sdr|0.2.0
code-spell-checker|str|1.8.0
vscode-status-bar-format-toggle|tom|2.0.0
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
@fiveisprime yea, we don't preserve the identity of the initial container when moved. we currently are thinking about enabling this, but there will still be a point which we will stop remembering (e.g. you move all these views individually to the panel). I am going to repurpose this issue for the work we have discussed.

**Comment by sbatten** [comment]
The solution we have discussed is having the view container's location be changeable, just like views in the view descriptor service.

**Comment by sandy081** [comment]
@sbatten Is this fixed with the changes you pushed yesterday?

**Comment by sbatten** [comment]
To Verify:
1. Install GitLens or similar extension with many views.
2. Drag GitLens by icon from Activity Bar to its own Panel.
3. Verify that the tab is called GitLens
4. Drag GitLens panel to the Activity Bar
5. Verify the Activity Bar icon is correctly the GitLens icon.

**Comment by AlencarGabriel** [comment]
Hello, I noticed that this correction came out in the last release.

However, I identified that extensions that were moved and lost the icon, still without the icon in the Activity Bar.

![vscode](https://user-images.githubusercontent.com/10109480/81336748-43724f80-9080-11ea-8094-4c438650e697.png)

**Comment by sbatten** [comment]
@AlencarGabriel  this issue only addressed moving the entire container as a whole. If you move views individually, the icons are still lost. This is being addressed with the next release.

**Comment by AlencarGabriel** [comment]
@sbatten , but what was actually moved was the entire containers. Remembering that I moved them before the April release.

![image](https://user-images.githubusercontent.com/10109480/81399022-b6bba600-9100-11ea-8f69-ad539a5f0f2e.png)

**Comment by sbatten** [comment]
If you moved them before release, then this fix has no effect. You will need to run reset view location before trying again.

**Comment by AlencarGabriel** [comment]
I ran the command "Reset View Locations", and the icons were successfully reset!

Thanks!
