### ISSUE TITLE
Unneeded menu separator under the More (...) menu

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#9547]
- VSCode Version: Code - Insiders 1.4.0-insider (0aa920603e48ad2333722d9ee97257e40ea24d12, 2016-07-20T05:07:18.076Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Open VS Code
2. Click the More (...) menu on the top right
3. Observe the unnecessary menu separator at the top of the list

![image](https://cloud.githubusercontent.com/assets/494055/16997141/0d61a376-4e69-11e6-8f87-a2dd53322551.png)

**Comment by f111fei** [comment]
related https://github.com/Microsoft/vscode/issues/9190.

@jrieken  I think it's better to remove `Separator` at https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/contextview/electron-browser/contextmenuService.ts#L33

This is the code that remove `Separator`
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/actionBarRegistry.ts#L184

**Comment by jrieken** [comment]
Pushed a change to fix this, tho up to @bpasero to decide how to proceed with this

**Comment by bpasero** [comment]
LGTM
