### ISSUE TITLE
intellisense not working with AL

### ISSUE THREAD

**Issue by karenjh2** [microsoft/vscode#95474]
Issue Type: <b>Bug</b>

In a project, I create a new file. I type tp and expect page snippet list to appear. It does not. So I type Control+space. I see Loading message, and it is stuck on that.

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz (1 x 2667)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (7.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
al-code-outline|and|1.0.38
al-toolbox|Bar|1.0.1
bracket-pair-colorizer-2|Coe|0.0.29
al-codeactions|dav|0.1.8
githistory|don|0.6.3
gitlens|eam|10.2.1
todo-tree|Gru|0.0.172
rest-client|hum|0.23.2
al-test-runner|jam|0.2.11
al-object-designer|mar|0.2.0
vscode-docker|ms-|1.0.0
al|ms-|5.0.254558
powershell|ms-|2020.4.0
snippet-creator|nik|0.0.5
createGUID|nwa|0.0.2
al-var-helper|ras|2.4.0
xliff-sync|rva|0.3.6
vscode-icons|vsc|10.1.1
al-extension-pack|wal|1.0.7
crs-al-language-extension|wal|1.2.1
vscode-todo-highlight|way|1.0.4

</details>

**Comment by chrmarti** [comment]
/causedByExtension

Please file against the AL extension contributing IntelliSense for AL.
