### ISSUE TITLE
UX : editor panel seperator(sash) not showing the cursor

### ISSUE THREAD

**Issue by stevezhaoUS** [microsoft/vscode#95471]
- VSCode Version: 1.44.1
- OS Version: MacOSX Catalina (Darwin x64 19.3.0)

Steps to Reproduce:

1. open any sidebar or split editor
2. hovering mouse on the sash, the cursor not showing.

Does this issue occur when all extensions are disabled?: Yes

This is not a big issue, but it affecting the user experience, when there is no sash for splited-panel, it's not easy to drag&drop.

**Comment by sbatten** [comment]
@stevezhaoUS I am not able to reproduce. When I hover any of these things, I get the resize cursor.

**Comment by stevezhaoUS** [comment]
Sorry, false alarm. The issue is caused by my system. close now.
