### ISSUE TITLE
 Support tmux control mode (-CC flag) re-do

### ISSUE THREAD

**Issue by dfee** [microsoft/vscode#95477]
Spinning off from https://github.com/microsoft/vscode/issues/90696 which I saw was just closed, I'd like to re-propose this feature.

> I saw the suggestion from @roblourens to use tmux in microsoft/vscode-remote-release#1185
> 
> That's mostly good, however has a few issues:
> 
>     code command doesn't work inside tmux.
>     no GUI support - the built-in tab management and split panes then aren't usable.
>     scrolling doesn't work (control codes not sent to the terminal?)
> 
> I'd love to see support for tmux's control mode (tmux -CC) - then vscode could use its native tab/window management and sessions would be persisted between app opens/closes.

**Comment by dfee** [comment]
It's a re-do of the (now closed) first linked issue.

**Comment by Tyriar** [comment]
I'll reopen the other one
