### ISSUE TITLE
Automatic updates

### ISSUE THREAD

**Issue by twallace27603** [microsoft/vscode#95479]
We have written the ne
Issue Type: <b>Bug</b>

So, this is probably on me, but the automatic update has failed multiple times.  It actually wipes out my VS Code installation and I have to re-install. I have turned the auto-update off and it isn't a big deal but I do like the feature. BTW - the version showing below is the one I just manually installed because the auto-update failed.  Thanks for looking at it.

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (4.86GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
asp-net-core-snippet-pack|adr|1.51.0
azds|azu|2.0.220200407
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.1.3
netcore-snippets|dog|3.1.4
jquerysnippets|don|0.0.1
xml|Dot|2.5.0
gitlens|eam|10.2.1
rest-client|hum|0.23.2
markdown-shortcuts|mdi|0.12.0
azure-pipelines|ms-|1.165.1
vscode-apimanagement|ms-|0.1.3
vscode-azureappservice|ms-|0.16.5
vscode-azurefunctions|ms-|0.22.0
vscode-azurestorage|ms-|0.9.0
vscode-cosmosdb|ms-|0.12.2
vscode-docker|ms-|1.0.0
vscode-logicapps|ms-|0.2.33
csharp|ms-|1.21.17
vscode-aks-tools|ms-|0.0.4
vscode-kubernetes-tools|ms-|1.1.1
mssql|ms-|1.9.0
python|ms-|2020.3.71659
remote-wsl|ms-|0.44.2
azure-account|ms-|0.8.9
azurecli|ms-|0.5.0
powershell|ms-|2020.4.0
vscode-node-azure-pack|ms-|0.0.10
azurerm-vscode-tools|msa|0.9.0
debugger-for-chrome|msj|4.12.6
es6-css-minify|olb|3.3.2
vscode-gitignore-generator|pio|1.0.1
vscode-yaml|red|0.7.2
arm-snippets|sam|1.4.19
bootstrap4-vscode|the|6.1.0
html-preview-vscode|tht|0.2.5
msbuild-project-tools|tin|0.3.5
azure-iot-toolkit|vsc|2.16.1
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|2.8.0
json|Zai|1.0.4

</details>
eded data into your clipboard because it was too large to send. Please paste.

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
