### ISSUE TITLE
Partial selected strings with non-alphabet characters 

### ISSUE THREAD

**Issue by abelardolg** [microsoft/vscode#95478]
- VSCode Version: 1.44.0
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1. Write any strings with non-alphabet characters such as "CY$Fzw10Am"
2. Double click to try to entirely select it.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ArturoDent** [comment]
This is because the `$` in your string is defined as a word separator. See the setting

> Editor: Word Separators

This setting can be edited  to remove the `$` from the list of word separators and then double-clicking on your string `CY$Fzw10Am` would act as you desire.

**Comment by abelardolg** [comment]
Thanks, @ArturoDent  :) It worked! :)
