### ISSUE TITLE
Change open new external terminal registration in web

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95481]
Instead of registering the command in web we should just add a keybinding for the integrated terminal instead.

**Comment by bpasero** [comment]
For the sake of code bundle size, I would prefer to not use `isWeb` but define a different contribution file, such as `nativeTerminal.contribution.ts`

**Comment by Tyriar** [comment]
@bpasero there is already the desktop side of this in `electron-browser/terminal.contribution`. I see some components use x.web.contribution.ts so I'll go with that https://github.com/microsoft/vscode/issues/96711
