### ISSUE TITLE
Visual studio does not start AS a normal user if it was started as a root user for first time 

### ISSUE THREAD

**Issue by rudedev** [Microsoft/vscode#9548]
- VSCode Version:Version 1.3.1
- OS Version: Any Linux(RHEL in my case ) machine

Steps to Reproduce:
0 . Login as root user to a linux machine ( at "login screen" choose username as root and give the root password)
1.  Download the VS Code RPM
2. Install it ( rpm -ivh, in my case )  
3. After installation is done, run the command, "code" on terminal
4. We see a message,  _I_t is recommended to start vscode as a normal user. To run as root, you must specify an alternate user data directory with the --user-data-dir argument.__

4.1 -- To be able to run, we give something like code --user-data-dir=/home/troll_user/troll_folder

4.2 -- It runs , do some code editing, save some file.
1.  Now change user via terminal, su trolluser 

5.1 Try typing code on terminal now.
1. We get an error, 
           _bash: /root/.bashrc: Permission denied_

---

How to get code working as a normal user now.

Notice, I have not logged off, I logged in as root user to being with, ran _code_, then did su trolluser, then cannot run _code_

**Comment by Tyriar** [comment]
Yes this is a limitation currently, it was brought up in a discussion around https://github.com/Microsoft/vscode/issues/3884

**Comment by bpasero** [comment]
@Tyriar I wonder if we detect that the user runs as admin we let all folders we use in Code be different from the normal one when you are not admin. That way you would be able to run both as admin and non admin (even at the same time).

Still, the bigger issue is that I think we should not encourage users to run Code as admin (though in this case I see how refusing to start is not a good choice either). But for cases where you just want to save 1 file where you need admin rights, we should just bring up user elevation for the save operation.

**Comment by Tyriar** [comment]
@bpasero yes I think we should eventually disallow running as sudo, instead opting for an elevation. There is [a package that would allow us to do this](https://www.npmjs.com/package/runas) but it doesn't show the prompt on Linux.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/8842
