### ISSUE TITLE
Ctrl + Alt + Cmd + L cannot be used as a keybinding

### ISSUE THREAD

**Issue by peterkhayes** [microsoft/vscode#95489]
Issue Type: <b>Bug</b>

I use a lot of custom keybindings, but I've found that one specific key combination doesn't work - `Ctrl + Alt + Cmd + l` (that's a lowercase "L"). On the keybindings page, when I enter this combination, nothing registers. And when I set this combination manually in `keybindings.json`, it doesn't register when I try to use it.

Strangely, all of the following commands do work:
* `Ctrl + Alt + l`
* `Ctrl + Cmd + l`
* `Alt + Cmd + l`
* `Ctrl + Alt + Cmd + Shift + l`

Additionally, I could not find any existing keybindings, or any Mac OS keybindings, that collide with `Ctrl + Alt + Cmd + l`.

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:47:00.296Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (1.43GB free)|
|Process Argv|/Users/peterhayes/Remix/remix/monorepo.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.3
githistory|don|0.6.3
EditorConfig|Edi|0.14.5
vsc-space-block-jumper|jmf|1.2.2
code-settings-sync|Sha|3.4.3
change-case|wma|1.0.0

</details>

**Comment by chrmarti** [comment]
This works for me. Maybe some other application captures this combination?

**Comment by cmdoptesc** [comment]
`CTRL + ALT + CMD + L` doesn't work for me, either.

On VS Code 1.44.2, steps to repro:
- open Keyboard Shortcuts (⌘K ⌘S)
- click "Record Keys"
- try to enter `CTRL + OPT/ALT + CMD + L` (⌃ + ⌥ + ⌘ + l) and notice that it won't register

⌃ + ⌥ + ⌘ + any other letter works, though

**Comment by alexdima** [comment]
If the keybinding is not printed in the input box of VS Code, it means that VS Code is not receiving the keybinding from the OS. Possible reasons why that would happen:
- another application has registered a global keybinding and "steals" it.
- the OS itself is using it (you can check in Settings > Keyboard).

In any case, there is nothing we can do on the side of VS Code if the keybinding does not reach us. There is no possible code change for us to do if the OS is not sending the keybinding to the application.
