### ISSUE TITLE
Small window to display Chinese characters garbled

### ISSUE THREAD

**Issue by Quiet-Dev** [microsoft/vscode#95499]
![无标题](https://user-images.githubusercontent.com/57312796/79540548-ec99db80-80ba-11ea-9ba1-f623941db55b.png)
Issue Type: <b>Bug</b>

Hover over the variable or function, the Chinese character declaration of the pop-up window is garbled

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (3.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.17
vscode-language-pack-zh-hans|MS-|1.44.2
cpptools|ms-|0.27.0

</details>

**Comment by octref** [comment]
Please give a minimal repro case. This does not happen to me.
Also, are you not using utf-8?

![image](https://user-images.githubusercontent.com/4033249/79600003-4e4a4d80-809b-11ea-9198-495dadc8ca4b.png)
