### ISSUE TITLE
开发版账户按钮

### ISSUE THREAD

**Issue by dstyxy** [microsoft/vscode#95491]
版本: 1.45.0-insider (user setup)
提交: 6e9a34c0de4181a99f11e106733ee3e8c9db79f1
日期: 2020-04-16T05:45:56.832Z
Electron: 7.2.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

请求：
这个眼睛好吓人，能否更改一下呈现方式，比如头像之类的。
![image](https://user-images.githubusercontent.com/28044114/79527059-438eb900-8099-11ea-8605-3ac87c53eee5.png)

**Comment by yume-chan** [comment]
Duplicate of #95437
