### ISSUE TITLE
Use .jsonc instead of .json in .vscode

### ISSUE THREAD

**Issue by Davilink** [microsoft/vscode#95496]
When we create launch settings, vscode automatically create a file launch.json with... comment inside the file.
![image](https://user-images.githubusercontent.com/1498932/79538488-6ea1ea00-8052-11ea-8f8c-a4096fe23021.png)
In my opinon it would be better to use `launch.jsonc` and `task.jsonc` (use of the `.jsonc` extension). 

First, vscode interpret, specially, these files as JSON with comment, but the file extension is still .json, it's a little confusing because as far as i know the JSON spec doesn't allow comment in it, so it could mislead some people thinking that you can put comment in JSON file.

Second, it will make the file extension more popular due of the popularity of vscode, so more people will know about this extension.

For example i created an issue in the aspnetcore project for using appsettings.jsonc instead of appsetting.json when scaffolding a project. One of the reason for not using it was because the file extension was not popular enough, but we go in circles... if nobody use it, nobody will know about it, and if no one know about it, nobody will use it.

https://github.com/dotnet/aspnetcore/issues/13070#issuecomment-520619971
https://github.com/microsoft/vscode/issues/79744

**Comment by aeschli** [comment]
I agree we should have done that, but it's too late now. A migration of the existing configuration file is painful and IMO not worth it. 
But yes, we should remember to use the jsonc extension for all new files.
