### ISSUE TITLE
Update test viewlet to use codicon

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#95494]
https://github.com/microsoft/vscode/blob/87287d027563185f57e10b9724d3fff2ad81e122/src/vs/workbench/api/browser/viewsExtensionPoint.ts#L258-L258

This should use our codicon via `ThemeIcon`. I attempted to update this but didn't have success as it impacted other parameters.

**Comment by sandy081** [comment]
Which codicon shall be used?

**Comment by misolori** [comment]
We have that icon as `beaker` in codicons:

![image](https://user-images.githubusercontent.com/35271042/79922095-2a16a580-83e8-11ea-9734-cc5bc565bb88.png)

**Comment by bpasero** [comment]
@sandy081 can you also delete the svg icon?
