### ISSUE TITLE
Unable to extract "case" property of Javascript object

### ISSUE THREAD

**Issue by TAYTS** [microsoft/vscode#95490]
- VSCode Version: 1.44.1
- OS Version: Darwin x64 19.4.0

Steps to Reproduce:

1. Create a JS object with "case" as one of the property
`const testing = { case: 10 };`
2. Deconstruct to get the "case" property
`const {case} = testing;`

<img width="437" alt="Screenshot 2020-04-17 at 10 28 48 AM" src="https://user-images.githubusercontent.com/29126748/79525785-4dfb8380-8096-11ea-97fd-71b224e05ac6.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Using a keyword in a destructuring is a syntax error. That code will not run in node or browsers
