### ISSUE TITLE
File explorer unresponsive, high cpu consumption

### ISSUE THREAD

**Issue by venil7** [Microsoft/vscode#9549]
- Version 1.3.1 (1.3.1)
- MacOS El Capitan

when I open a Folder with my project File explorer becomes unresponsive,
 a little progressbar keeps scrolling , and files never show up

(other folders of similar size are fine)

and CPU consumption by Electron Helper jumps to > 100%

<img width="268" alt="screen shot 2016-07-20 at 19 52 02" src="https://cloud.githubusercontent.com/assets/508022/16999011/de72e03e-4eb3-11e6-8c23-3cc8b4b45ae8.png">

**Comment by kieferrm** [comment]
@venil7 Does that happen only for a specific folder or any folder? If specific, can you provide details about your workspace (number of files, symlinked folders, etc.)? If any folder, is the volume on a special drive?

**Comment by kieferrm** [comment]
No info. Closing.
