### ISSUE TITLE
tns --version shows old version but command line terminal shows other

### ISSUE THREAD

**Issue by jitendrakansal** [microsoft/vscode#95505]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

When i execute tns --version in VScode terminal it shows 4.2.2
but when i execute same command in Terminal (MacOS), it shows 6.5.0
how can i find where tns 4.2.2 reference is being picked up by VSC terminal?

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:47:00.296Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.63GB free)|
|Process Argv|-psn_0_4293656|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
markdown-preview-github-styles|bie|0.1.6
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.34.0
xml|Dot|2.5.0
copy-relative-path|eri|0.0.4
prettier-vscode|esb|4.4.0
vs-code-xml-format|fab|0.1.5
type-script-preview|feb|0.0.1
beautify|Hoo|1.5.0
RelativePath|jak|1.4.0
java|red|0.60.0
vscode-xml|red|0.11.0
vsc-extension-mbt|SAP|1.5.0
vsc-extension-mdk|SAP|1.15.0
vscode-cds|SAP|1.2.11
markdown-preview-enhanced|shd|0.5.3
nativescript|Tel|0.11.0
vscode-status-bar-format-toggle|tom|2.0.0
import-beautify|var|0.3.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2

</details>

**Comment by jitendrakansal** [comment]
![image](https://user-images.githubusercontent.com/31536700/79545741-7d5bc180-8091-11ea-853d-33d7fd3b276b.png)
added screenshot

**Comment by chrmarti** [comment]
`which tns` will show you where the old version is installed. There must be a difference in how your PATH is set up. Does this change when you turn off inheriting of the environment?
![image](https://user-images.githubusercontent.com/9205389/79734967-d593fd00-82f7-11ea-9f76-c81fcd795981.png)

**Comment by jitendrakansal** [comment]
@chrmarti which tns in VSC terminal was pointing to different path. I had to delete it manually and reinstalled node 10.15. I turned off inheriting of the environment and then can see right version showing up in VSC terminal. Thanks for help.
