### ISSUE TITLE
welcome view content layout is broken?

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#95508]
welcome view layout is handled by the `ViewPane` parent  class 

https://github.com/microsoft/vscode/blob/7fa1bef37f8f42cd92f76b1a8d7bcd6d30855ee6/src/vs/workbench/browser/parts/views/viewPaneContainer.ts#L335-L340

None of the sub classes (views) are calling `super.layoutBody()`. Does it mean that if any of these views has welcome view content then welcome view is not layout correctly?

**Comment by joaomoreno** [comment]
I actually went through all the subclasses and added `super.renderBody()` to all `renderBody()` methods. Forgot to do the same for `layoutBody`...

**Comment by sandy081** [comment]
Verified by code review
