### ISSUE TITLE
Settings - option `Show modified only` disappeared

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#95500]
```
Version: 1.44.1 (system setup)
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:48:12.622Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```
It has always been possible to see only the settings that are being modified ( `Show modified only`). Now it's gone:

![obraz](https://user-images.githubusercontent.com/30685349/79541825-d07e4600-808a-11ea-849e-d9fefb4eabcf.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Thanks for pointing this out. You can still enter `@modified` in the search bar and you should get a suggestion popup for that.

FYI @sandy081 this is from https://github.com/microsoft/vscode/commit/9cf403aabf1a4d1a51b61a5a8646060f6767197e, thanks for modernizing those action registrations though!

**Comment by sandy081** [comment]
Sorry for breaking.
