### ISSUE TITLE
Accounts Icon Jagged Edge / Poor Icon Choice

### ISSUE THREAD

**Issue by atom0s** [microsoft/vscode#95506]
Issue Type: <b>Bug</b> (Visuals)

The new(?) 'Accounts' button icon above the settings cog wheel looks pretty bad. I am not sure if this is brand new, I just noticed it today after updating to the latest Insider build. The button curve of the button is jagged and it doesn't look like that is either on purpose or just poorly done.

Here is an image of what I mean (including a zoomed pic):
![image](https://user-images.githubusercontent.com/1422090/79545382-70b17c00-8045-11ea-98f6-d4523800353c.png)

The bottom looks pretty awful.

Feedback regarding it in general:
 - It doesn't resemble 'Accounts' to me personally and I had no idea what it was at first glance. 
 - There doesn't seem to be a way to disable this button. It would be nice to not see it at all.

VS Code version: Code - Insiders 1.45.0-insider (6e9a34c0de4181a99f11e106733ee3e8c9db79f1, 2020-04-16T05:45:56.832Z)
OS version: Windows_NT x64 10.0.18363

**Comment by atom0s** [comment]
Is there a way to disable this button altogether?

**Comment by gjsjohnmurray** [comment]
> Is there a way to disable this button altogether?

@RMacfarlane may know.

**Comment by RMacfarlane** [comment]
Currently no, it cannot be disabled
