### ISSUE TITLE
Tasks: Slow to trigger build

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#95507]
We're supposed to be doing some caching such that the user doesn't have to wait for `Fetching build tasks...` too many times. When running in Remote WSL, it seems this isn't working as I see the `Fetching build tasks...` every time I press <kbd>Ctrl Shift B</kbd>.

**Comment by alexr00** [comment]
The culprit is the typescript task detection. With `"typescript.tsc.autoDetect": "off"` it's ok.

**Comment by joaomoreno** [comment]
Log: https://gist.github.com/joaomoreno/7b2d3472f57f351dda60c851dcc4161a

**Comment by joaomoreno** [comment]
There are two problems here, after discussing with @alexr00:

- TS task detection in our repo seems very slow in my setup
- Triggering <kbd>Ctrl Shift B</kbd> on a workspace with an explicit default task in `tasks.json` should bypass any auto detection.
