### ISSUE TITLE
Synchronize outline with cursor in markdown files

### ISSUE THREAD

**Issue by nachocab** [microsoft/vscode#95504]
Currently, it's possible to navigate to a section of a markdown file by clicking on the outline headers

![image](https://user-images.githubusercontent.com/27538/79544104-c8c0a080-808e-11ea-8d72-d5c942d199da.png)

However, it's not possible to see where in the outline I am once I change the position of the cursor. It would be great if there was some sort of visual indication (outline or breadcrumbs) to know what markdown headers are above the current cursor position).

The 'Show in code outline' command also doesn't work.

**Comment by jrieken** [comment]
<img width="404" alt="Screenshot 2020-04-17 at 09 53 11" src="https://user-images.githubusercontent.com/1794099/79545642-51404080-8091-11ea-93f9-773daaf280b5.png">

**Comment by nachocab** [comment]
It works great. Sorry about that, I couldn't find it documented anywhere.
