### ISSUE TITLE
Alert emoji can not display properly

### ISSUE THREAD

**Issue by lyqflnh** [microsoft/vscode#95502]
![image](https://user-images.githubusercontent.com/20616682/79543199-9713fd80-80bf-11ea-91ff-079d2fc5e480.png)

**expect**

![image](https://user-images.githubusercontent.com/20616682/79543330-db070280-80bf-11ea-82a7-887ebd2c2b41.png)

**Comment by IllusionMH** [comment]
Same on Windows.
⚠ uses Segoe UI Symbol, but other emoji Segoe UI Emoji.
Is it possible to switch order of fonts for this case?

**Comment by alexdima** [comment]
Let's track in #32840
