### ISSUE TITLE
Eslint stopped working 2 days ago

### ISSUE THREAD

**Issue by JustFly1984** [microsoft/vscode#95519]
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:

1. Eslint extension just stopped working for me 2 days ago, can't reproduce, but it happened after vscode has been updated to 1.44.1 version. still doesn't work in 1.44.2
2. In the output of Eslint extension I see errors, which I have no clue how to decipher.

output
```
[Info  - 5:36:16 PM] ESLint server stopped.
[Info  - 5:36:16 PM] ESLint server running in node v12.8.1
[Info  - 5:36:16 PM] ESLint server is running.
(node:31979) UnhandledPromiseRejectionWarning: Error: Request workspace/configuration failed with message: Cannot read property 'source.fixAll.eslint' of null
    at /Users/$$$/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:8961
    at /Users/$$$/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:9255
    at Immediate.<anonymous> (/Users/$$$/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:9616)
    at processImmediate (internal/timers.js:439:21)
(node:31979) UnhandledPromiseRejectionWarning: Error: Request workspace/configuration failed with message: Cannot read property 'source.fixAll.eslint' of null
    at /Users/$$$/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:8961
    at /Users/$$$/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:9255
    at Immediate.<anonymous> (/Users/$$$/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:9616)
    at processImmediate (internal/timers.js:439:21)
```

No - with this command eslint also disabled. I have tried to disable all extensions but eslint, didn't solve an issue. reinstalled vscode and eslint extension multiple times.

I have my projects running node 13

I've created according issue in vscode-eslint repo https://github.com/microsoft/vscode-eslint/issues/950

**Comment by dbaeumer** [comment]
This is a problem of the ESLint extension.
