### ISSUE TITLE
Indexing broken when using cmd +p or find all

### ISSUE THREAD

**Issue by JaccoGoris** [microsoft/vscode#95513]
Issue Type: <b>Bug</b>

- use cmd + p to search for a file
result: the file can not be found even while it is clearly there in the explorer

This also happens with find all, hence why I think something is wrong with the indexing.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv|-psn_0_13647107|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
snapshot-tools|asv|0.4.0
atlascode|atl|2.5.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|2.0.0
githistory|don|0.6.3
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
vscode-npm-script|eg2|0.3.11
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|4.4.0
live-html-previewer|hdg|0.3.0
presentationmode|jsp|1.1.5
code-coverage|mar|1.2.1
git-graph|mhu|1.22.0
dotenv|mik|1.0.1
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.0.0
python|ms-|2020.3.71659
vsliveshare|ms-|1.0.2000
debugger-for-chrome|msj|4.12.6
react-proptypes-intellisense|OfH|1.0.3
open-html-in-browser|pea|2.1.2
material-icon-theme|PKi|4.0.1
vscode-react-refactor|pla|1.0.5
vscode-yaml|red|0.7.2
synthwave-vscode|Rob|0.1.2
markdown-preview-enhanced|shd|0.5.3
vscode-3dviewer|sle|0.1.0
sort-lines|Tyr|1.9.0
html-css-class-completion|Zig|1.19.0

(4 theme extensions excluded)

</details>

**Comment by JaccoGoris** [comment]
I noticed in my ystem info that I had something that ate up all my ram.
after killing that and reloading the vscode window, it works again.
So this might be a non-issue. feel free to close this if it is not relevant.

**Comment by chrmarti** [comment]
Please also update to 1.44.2. Closing for now, let us know when this comes up again.
