### ISSUE TITLE
Initializing js/ts features Causes Application to hang

### ISSUE THREAD

**Issue by karna41317** [microsoft/vscode#95515]
Issue Type: <b>Bug</b>

vs code hangs and  Initializing js/ts features on taskbar never completes and it Causes Application to hang , I have installed latest vscode just now. I stil have same issue

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.86GB free)|
|Process Argv|-psn_0_1143063|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.29.0
gitlens|eam|9.9.3
prettier-vscode|esb|3.20.0
shell-format|fox|6.1.2
vscode-npm-dependency|how|1.2.2
vscode-styled-components|jpo|0.0.26
vscode-html-format|moh|0.0.3
vscode-apache|mrm|1.2.0
python|ms-|2019.10.41019
sublime-keybindings|ms-|4.0.3
vscode-typescript-next|ms-|3.9.20200416
vscode-nginx|sha|0.6.0
ayu|tea|0.18.0
vscode-status-bar-format-toggle|tom|1.5.0
vscode-todo-highlight|way|1.0.4

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
How big is your js/ts project? How long have you waited before concluding that the initializing step never completes?

Does the same happen if you run with all extensions disabled?

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by karna41317** [comment]
> How big is your js/ts project? How long have you waited before concluding that the initializing step never completes?
> 
> Does the same happen if you run with all extensions disabled?

It never complets unfortunately.

**Comment by mjbvz** [comment]
Try testing in insiders with extensions disabled
