### ISSUE TITLE
XML Formatting shortcuts no longer work

### ISSUE THREAD

**Issue by kakins** [Microsoft/vscode#9551]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. Try pressing the default alt+shift+f keys, nothing happens
2. Try manually setting your shortcut key preferences for editor.action.format, nothing happens

**Comment by kieferrm** [comment]
@kakins pls provide additional info so that we can recreate the problem without any guessing. Thanks!

**Comment by kakins** [comment]
@kieferrm Sure thing.  What additional information do you need?

**Comment by kieferrm** [comment]
@kakins  here is what would be helpful:
- extensions you have installed
- source workspace or file (if file suffices)
- any selection in the file
..

**Comment by kakins** [comment]
Thanks.  I ended up installing the XML Tools extension and formatting now works with ALT+SHIFT+F.  Is this extension required for XML formatting?  I was under the impression VS Code can do it natively.

However, up to that point, here are the details:

- Extension(s): C# Extension
- File: A general XML file
- Selections in the file: none.

**Comment by kieferrm** [comment]
VS Code provides syntax highlighting for xml out of the box. But no other service.

**Comment by kakins** [comment]
I'm sorry, maybe you didn't understand my original post.  I was not talking about syntax highlighting.  I was talking about XML **formatting**.  This I could not get to work out of the box with VS Code.  I had to install the XML Tools extension.  The post was not invalid.

**Comment by kakins** [comment]
Oh I think I misunderstood originally.  For some reason I thought Visual Studio helped with syntax formatting out of the box.  Thanks for your help!
