### ISSUE TITLE
Pressing esc in terminal navigation mode navigates to previous line

### ISSUE THREAD

**Issue by jvesouza** [microsoft/vscode#95514]
Issue Type: <b>Bug</b>

1. Launch orca.
2. Press ctrl+` to activate an integrated terminal.
3. Type commands in the terminal.
4. Press ctrl+up two or thre times.
5. Press the escape key to return to input mode.

Instead of returning to the input mode, the previous line is displayed as if I had pressed ctrl + up.
I also can't type commands in the terminal.

CC @webczat @isidorn

VS Code version: Code - Insiders 1.45.0-insider (a3083e58e2a9e77f60e531acaa32e18527ae8439, 2020-04-17T08:09:45.292Z)
OS version: Linux x64 5.6.4-arch1-1

**Comment by isidorn** [comment]
@jvesouza thanks for filling this!
Yes, I see the same on macOS. When in terminal navigation mode pressing `esc` navigates to the previous line. It should exit the terminal navigation mode.

@Tyriar can you maybe investigate?

**Comment by Tyriar** [comment]
This was a regression in a big refactor I did, thanks for finding 😃

**Comment by jvesouza** [comment]
I tested it here and it is working as expected. Thanks.

**Comment by isidorn** [comment]
@jvesouza awesome. Adding verified label.
