### ISSUE TITLE
CTRL + Tab, + up or down arrow buttons, no longer work

### ISSUE THREAD

**Issue by josiahmccorkle** [microsoft/vscode#95518]
Issue Type: <b>Bug</b>

I can use the CTRL + Tab feature, but can no longer use the up and down arrows to navigate the list of open files. 

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.29
beautify|Hoo|1.5.0
Angular-BeastCode|Mik|8.1.2
vscode-typescript-tslint-plugin|ms-|1.2.3
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.6
quicktype|qui|12.0.46
csharp2ts|raf|0.0.24
code-spell-checker|str|1.8.0
vscodeintellicode|Vis|1.2.6
json|Zai|1.0.4

</details>

**Comment by gjsjohnmurray** [comment]
Please update to 1.44.2 and test again.
