### ISSUE TITLE
Movimentação utilizando os direcionais entre os dados de uma query SQL com problemas 

### ISSUE THREAD

**Issue by DouglasPR77** [microsoft/vscode#95526]
Existe um problema quando uma aba é aberta com um resultado de uma query. Quando se usa as setas do teclado para se mover dentro desses dados, e a posição escolhida chega perto do fim da tela as setas param de funcionar. Esse problema ocorre sempre que a quantidade de colunas é maior que a quantia visível em tela. Tendo sempre a necessidade de clicar novamente com o mouse, para que volte a funcionar a movimentação pelo setas do teclado

**Comment by DouglasPR77** [comment]
There is a problem when a tab is opened with a query result (SQL). When using the arrow keys to move within these data, and the chosen position comes close to the end of the screen, the arrows stop working, causing the cursor not to move between the data. This problem occurs whenever the number of columns is greater than the amount visible on the screen. Thus, needing to click again with the mouse, so that the movement by the arrow keys of the keyboard will work again.

![image](https://user-images.githubusercontent.com/63856221/79753258-ff472700-82eb-11ea-8d68-d81a88b35664.png)

As we can see in the image above, the problem of locking the keyboard directionals occurs when you scroll through some columns of data (always using the directional ones) until the bottom bar moves to view data that was not previously on the screen. Whenever the direcinal is moved for data that are outside the limit of the screen, they lock, needing to click with the mouse to return to work.

I thank you for the support and I ask for tolerance for my bad English.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz (4 x 2691)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.1.34
rainbow-csv|mec|1.7.0
mssql|ms-|1.9.0
quicktype|qui|12.0.46
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.1.1
txt-syntax|xsh|0.0.3
material-theme|zhu|3.2.5


</details>

**Comment by chrmarti** [comment]
/causedByExtension

This appears to be caused by the MS SQL extension, please file an issue for that: https://github.com/Microsoft/vscode-mssql/issues
