### ISSUE TITLE
Duplicate characters / words

### ISSUE THREAD

**Issue by linhkhoi1309** [microsoft/vscode#95520]
Issue Type: <b>Bug</b>

This happended when I wrote a new code and clicked mouse to another section in my file. It duplicated word and reduce my time a lot, hope you would fix it as soon as possible. I've tried to google it but didn't get any answer appropriately.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU       M 620  @ 2.67GHz (4 x 2660)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (3.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|4.4.0
LiveServer|rit|5.6.1

</details>

**Comment by chrmarti** [comment]
Did you maybe set a second text cursor? https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor

**Comment by linhkhoi1309** [comment]
No i did not set anything but however, iy has been removed somehow. Sorry
for reply late

Vào 16:18, T.2, 20 Th4, 2020 Christof Marti <notifications@github.com> đã
viết:
