### ISSUE TITLE
Blackout overwrote my file with empty data

### ISSUE THREAD

**Issue by benlowry** [Microsoft/vscode#9552]
- VSCode Version: 1.3
- OS Version: Windows 10

Steps to Reproduce:

1. unsaved state on existing file
2. cut power to desktop

VSCode no longer understands the encoding and there's nothing in the file, although it's not zero bytes either.

**Comment by kieferrm** [comment]
@benlowry if you don't have autosave enabled vscode does not write a file's content to disk. With autosave enabled it still relies on the operation system file system to perform that operation. Let's assume autosave was enabled and a save operation was in progress when the power outage happened. Whatever vscode is trying to write at this point has still to go through all the layers down to the actual buffer of the disk. Given all that I don't see how vscode could have changed anything in respect to the outcome of the write operation. I do see however how frequent, silent persisting of a dirty buffer state could have made it easier for you to recover. See #101.

**Comment by kieferrm** [comment]
Marking as duplicate fo #9589.
