### ISSUE TITLE
VSC loses resolution while I'm working

### ISSUE THREAD

**Issue by ygspasov** [microsoft/vscode#95523]
I'm having a strange problem where my code becomes barely visible while I'm working. I've been having this issue for more than a month already. I've tried updating the graphic drivers but it doesn't work. The program keeps switching from normal to very bad resolution, making the code unreadable.

![bad](https://user-images.githubusercontent.com/10303050/79567226-8615bd00-80bc-11ea-9459-c1c33763d87d.jpg)
![normal](https://user-images.githubusercontent.com/10303050/79567229-86ae5380-80bc-11ea-9de7-a8d69bf33b4f.jpg)

- VSCode Version: 1.44.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Open VSC
2. Start working with it.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with the --disable-gpu option?

**Comment by ygspasov** [comment]
> 
> 
> Does the problem also happen if you launch with the --disable-gpu option?

I haven't tried it but I've found that the following solution worked for me: https://stackoverflow.com/questions/36108515/how-to-reset-settings-in-visual-studio-code

I still don't know what has caused the problem but it seems that I'm no longer experiencing it so I'm closing the issue.
