### ISSUE TITLE
Failed to delete using recycle bin

### ISSUE THREAD

**Issue by smerinohpe** [microsoft/vscode#95539]
Issue Type: <b>Bug</b>

In eplorer tab, when you try to delete file, the program ask to delete moving the file to recycle bin, but this process fail and and ask you to delete permanently. Why not found Recycle Bin?

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz (8 x 2699)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|12.00GB (3.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.15.0
python|ms-|2020.3.71659
remote-wsl|ms-|0.44.2

</details>

**Comment by gjsjohnmurray** [comment]
Your extensions list includes remote-wsl. When you see this problem are you using that? Or working with local Windows files?

**Comment by smerinohpe** [comment]
With local windows files

**Comment by gjsjohnmurray** [comment]
Works OK for me. My full info from Help\About:

Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Does https://github.com/microsoft/vscode/issues/4855#issuecomment-204903960 apply to you?

And is your install a User one or a System one? I don't know if that's relevant thought. As shown above, mine is User.

**Comment by smerinohpe** [comment]
I have found the problem and is my fault.
The drive that I am access is in a remote drive mount as local, and it hasn't attach a recycle bin, so always do permanent delete. Sorry for inconvenience.
