### ISSUE TITLE
Enabling or disabling sync from CLI should not persist

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#95532]
Start code insiders from CLI by enabling or disabling sync. This state should not be persisted after you restart.

Steps:

- Check your sync state (turned on or off)
- From CLI `code-insiders --sync on/off`
- Make sure Sync is on or off when the window opens
- Make sure you cannot turn on or off sync (no actions are shown)
- Quit and restart code insiders normally
- Make sure Sync state is same as in step 1

**Comment by roblourens** [comment]
Works but the blue button in the settings editor still appears. I filed https://github.com/microsoft/vscode/issues/96727 to hide that too.
