### ISSUE TITLE
Blank terminal on Mac

### ISSUE THREAD

**Issue by jlin96** [microsoft/vscode#95531]
<img width="1393" alt="Screen Shot 2020-04-17 at 9 55 06 AM" src="https://user-images.githubusercontent.com/25333405/79576789-d1ff3c80-8091-11ea-916b-665fab72a606.png">

- VSCode Version: 1.44
- OS Version: Mojave 10.14.5

Steps to Reproduce:
Not sure how to reproduce, was working on a rails project and the terminal started typing behind the console and then I tried clearing it and the terminal just came up as a blank slate and no matter if I restarted VScode, opened a new file it would still be blank. I tried looking up solutions but have not found any that works for macs.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Tyriar** [comment]
Please try enabling trace logging to give us some insight into what's happening when the terminal launches:

https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
