### ISSUE TITLE
Support hvplot as pandas plotting backend in vscode Python extension

### ISSUE THREAD

**Issue by fkromer** [microsoft/vscode#95535]
When using `matplotlib` as plotting backend for `pandas` plots are displayed correctly.

```
import pandas as pd
pd.options.plotting.backend = 'matplotlib'

pd.DataFrame.plot()
```

However when I use `hvplot` as plotting backend I get the following error message:

```
TypeError: Cannot read property 'startsWith' of undefined at 
  
    in t
    in div
    in div
    in div
    in div
    in div
    in div
    in t
    in f
    in t
    in div
    in div
    in div
    in t
    in main
    in div
    in t
    in f
    in p
```

Would be great if `hvplot` support would be added.

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Python extension. Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose

**Comment by fkromer** [comment]
Issue reference: https://github.com/microsoft/vscode-python/issues/11268
