### ISSUE TITLE
vs code is very slow

### ISSUE THREAD

**Issue by hema8531** [microsoft/vscode#95537]
Whenever i open the vs Code its loading very slow, my Os in Windows 10

**Comment by gjsjohnmurray** [comment]
Please follow the instructions at https://github.com/microsoft/vscode/wiki/Performance-Issues

Those instructions will create a new GH issue, so once you have done that I suggest you come back to this one, add a #nnnnn reference to the new one, then close this one.

**Comment by shakazed** [comment]
Please follow these instructions for reporting performance issues: https://github.com/microsoft/vscode/wiki/Performance-Issues
