### ISSUE TITLE
The new  Progregress Events don't always work for Debugger Adapters launch requests

### ISSUE THREAD

**Issue by awto** [microsoft/vscode#95541]
- VSCode Version: 1.44.2, 1.45.0-insider
- OS Version: OSX, Win 10

Steps to Reproduce:

1. Get the [fork of vscode-mock-debug](https://github.com/awto/vscode-mock-debug) which demonstrates the problem in [this commit](https://github.com/awto/vscode-mock-debug/commit/10655fbd62a92a89a4684845334d691bc33f80ce)
2. Run it

Expected Progress showing "before..." and after "after...". But "before..." progress isn't displayed.
The progress is displayed only if I `sendEvent` after I 
 
There I send progress events before sending response for `launchRequest`. Sending it after `sendResponse` or adding some timeout before the event works. However, in my adapter the launch request may be long and I also need to perform some actions before sending response to report some error gracefully.

Here is a summary code from `launchRequest`:

```typescript
// IF the next line is uncommented the bellow event sends work well
// await timeout(1000);  l
this.sendEvent(new ProgressStartEvent("before-response", "before-1"));
await timeout(2000);
this.sendEvent(new ProgressUpdateEvent("before-response", "before-2"));
await timeout(2000);
this.sendEvent(new ProgressEndEvent("before-response", "before-3"));
await timeout(2000);

this.sendResponse(response);

//  the next works even if the events sends and timeouts above are removed
this.sendEvent(new ProgressStartEvent("after-response", "after-1"));
await timeout(2000);
this.sendEvent(new ProgressUpdateEvent("after-response", "after-2"));
await timeout(2000);
this.sendEvent(new ProgressEndEvent("after-response", "after-3"));

```

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
@awto thanks for filling this issue with good reproducable steps.
I have pushed a fix for this issue. It would be great if you try it out with VS Code insiders from Tuesday and let me know if it is really fixed for you. Thanks!

**Comment by awto** [comment]
@isidorn  Thanks! It works.

**Comment by isidorn** [comment]
Thanks for letting us know. Adding verified label.
