### ISSUE TITLE
Add a "recenty used input" to user inputs for launch configurations.

### ISSUE THREAD

**Issue by GlenDC** [microsoft/vscode#95540]
There is a "Rerun tasks" option for running tasks again with same input, which resolves it for tasks as long as the "recently used input" feature is not possible (as discussed in https://github.com/microsoft/vscode/issues/65066). However for Launch.json configurations that doesn't seem to be available.

> I tried the rerun task (not that it helps me with debugging) and even there it seems that it asks for the input args once again, so even if such a rerun option would become available for debugging, that wouldn't really help me much

It is a bit of a nuance currently that when wanting to debug multiple times in a row that each time you have to select and/or enter the different user input variables. Would be great that it remembers the recently used input when selecting input (especially for promptStrings), but a "Rerun debug config" would be even greater.

You can restart a debug session while it is active, but not possible to do so afterwards.

**Comment by alexr00** [comment]
This is handled at the tasks level for tasks (not variable resolving), so assigning to @isidorn.

**Comment by isidorn** [comment]
@GlenDC this is a fair feature request. However I believe this could be achieved by an extension.
An extension would simply `resolveDebugConfigurations` for `*` type that way it would be called last.
It would contribute a command "Rerun Debug Configuration" or something like that and that command would simply call the `debug.startDebugging` api via the last used configuration.

**Comment by muman613** [comment]
This is needed for tasks.json also.

**Comment by sourabh2902** [comment]
Hi
Is this feature available in the latest version?
