### ISSUE TITLE
Do we have any Variable that give me Parent Folder of a File?

### ISSUE THREAD

**Issue by madoodia** [microsoft/vscode#95542]
Hello

I have a problem with `Variables Reference` of VSCode.

in simplest way I want to ask

if I have this path `/my/path/to/project` as my workspace
and `/my/path/to/project/folder1` as subdirectory
how can I get `folder1` as a word like `${fileParentDirName}` or something?
with current `Variable References` of VSCode there is not any variable to give me the parent dir name of a file (despite of how many level it deeps in a hierarchy

because I need this single word to use in `launch.json`

may you ask why I need this (maybe you can give me an alternative way)

Suppose I have this file `/my/path/to/project/folder1/main.cpp`, and when I build it it will create  `folder1` as executable file (in `linux`), I setuped debugger in `launch.json` but when I hit `F5` what should be `"program": ???` content to find the `folder1` as target? (when I open `main.cpp` and hit `F5`)

If I had a variable that give me direct parent of opened file it would be great, like `"program": "${relativeFileDirname}/${fileParentDirName}"`

I hope this makes sense
thanks

**Comment by ArturoDent** [comment]
As a workaround you could use the extension https://marketplace.visualstudio.com/items?itemName=rioj7.command-variable which provides many more vaiables that can be used in launch/tasks including

${command:extension.commandvariable.file.fileDirBasename}

which I believe is the target you are looking for.

**Comment by madoodia** [comment]
thanks @ArturoDent 
I didn't know that
