### ISSUE TITLE
Debugger gets stuck

### ISSUE THREAD

**Issue by spin711** [microsoft/vscode#95545]
Issue Type: <b>Bug</b>

While debugging a python script, the I cannot continue stepping through the code since MSC debugger is not responding anymore. At least for me, it seems that it gets stuck after 15 successful times of stepping. This is repeatable.
Also the debug console is impacted, meaning I do not get a requested content of a variable once the above happens.
Please fix asap, since one cannot work with this version anymore properly.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (0.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.3
python|ms-|2020.2.64397
team|ms-|1.161.0

</details>
e written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment]
Are you able to update to the current release (1.44.2) and retest?

**Comment by spin711** [comment]
Yes, I updated to version 1.44.2, but the same issue. The only thing I observe is, that the number of steps I can perform is not as constant as I thought within the same script. Although it seams repeatable starting at the same line it changes when the starting position and thus the lines of code are different.

**Comment by spin711** [comment]
There seems to be also a dependency with the number and the type of variables in the watch.

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Python extension. Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose
