### ISSUE TITLE
Improper tab auto completing of html tags

### ISSUE THREAD

**Issue by netm** [Microsoft/vscode#9554]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. In Hanldebars or Html language mode
2. Type \<p then tab->tab to create a paragraph tag
3. The tag start is inserted **a tab space to the left** not where the cursor started
4. The older version used to insert properly

Love this app!!

**Comment by kieferrm** [comment]
@netm I can't reproduce the behavior you describe in stable 1.3.1 or insiders 1.4.0. Neither on MacOS nor Windows. Pls reopen with additional details.

**Comment by netm** [comment]
Cool - can I send you a wee video?

**Comment by mrmlnc** [comment]
@netm, Just create a GIF and attach it to the comment 👍

**Comment by netm** [comment]
![code](https://cloud.githubusercontent.com/assets/1432243/17044740/eaea50f4-5016-11e6-8321-51bf0e72335d.gif)

:)

**Comment by mrmlnc** [comment]
Hmmm, can you try to run VS Code without extensions? From the command line, execute: code --disable-extensions and try your steps again to see if it reproduces.

In VS Code version 1.4.0-insiders i can't reproduce the behavior that you describe.
![2016-07-22_05-37-41](https://cloud.githubusercontent.com/assets/7034281/17045035/7262d626-4fce-11e6-942e-6e2c97e1b57c.gif)

**Comment by netm** [comment]
Have tried running without extensions and the same behaviour is happening, odd :-/

**Comment by mrmlnc** [comment]
@netm, what is your OS version and editor? Can provide the settings of editor?

**Comment by netm** [comment]
Mac 10.11.5, Code 1.3.1

**Comment by SchroterQuentin** [comment]
I have the same issue on both my windows 10 and linux debian 8 and I try without extensions and nothing change
Code 1.3.1

**Comment by mrmlnc** [comment]
@SchroterQuentin, in version 1.4.0 this problem is solved.
![2016-08-03_14-36-58](https://cloud.githubusercontent.com/assets/7034281/17364246/c5e61f84-5987-11e6-8c37-81872fef0f28.gif)
