### ISSUE TITLE
launch.json: support debug active test file

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#95544]
Issue Type: <b>Feature Request</b>

Our launch.json supports debugging all mocha test files perfectly but we can't tweak it to debug a single test file easily without hard coding.

For example, I want to debug a unit test file `/home/rebornix/vscode/out/vs/workbench/contrib/notebook/test/notebookFolding.test.js`, what I need to do in VS Code `launch.json` is tweaking `Run Unit Test`

```diff
{
    "type": "node",
    "request": "launch",
    "name": "Run Unit Tests",
    "program": "${workspaceFolder}/test/unit/electron/index.js",
    "args": [
        "--remote-debugging-port=9222",
+.     "--run=/home/rebornix/vscode/out/vs/workbench/contrib/notebook/test/notebookFolding.test.js"
    ],
    "outFiles": [
        "${workspaceFolder}/out/**/*.js"
    ]
}
```

I'd like to replace the hard code file path with variables, what we have right now are

*  `"workspaceFolder" : "/home/rebornix/"`
* `"relativeFileDirName": "src/vs/workbench/contrib/notebook/test/"`
* `"fileWithNoExtension": "notebookFolding.test"`

The only change we need to do is replacing `src` with `out` but I guess it requires knowledge of `tsconfig`. If the typescript can contribute a variable like `outputFilePath` then the problem can be solved.

cc @mjbvz 

VS Code version: Code - Insiders 1.45.0-insider (6e9a34c0de4181a99f11e106733ee3e8c9db79f1, 2020-04-16T05:41:45.257Z)
OS version: Darwin x64 19.2.0

**Comment by isidorn** [comment]
This makes perfect sense and was also requested by @joaomoreno 
The alternative approach to contributing variables that need to be resolved is to pass the filter based on the currently active file

Workaround: use `.only` in your mocha test file until we fix this. And try not to commit that accidentally.
For now assigning to May since I think this would help with our selfhosting.
Also assigning to @connor4312 for ideas
fyi @weinand @roblourens

**Comment by weinand** [comment]
Since commands can be used as variables, typescript can already contribute a command "outputFilePath".

**Comment by isidorn** [comment]
@weinand nice idea. Is it possible for the typescript extnesion to contribute this command @mjbvz

**Comment by joaomoreno** [comment]
@rebornix Also wants this.

**Comment by connor4312** [comment]
Yea, I think a command is the way to go here.

> Is it possible for the typescript extnesion to contribute this command

This would be nice but might not always be possible in esoteric build setups. js-debug could contribute this since we build a mapping for sourcemaps in the workspace already. Interested to hear Matt's thoughts :)

**Comment by isidorn** [comment]
@mjbvz ping

**Comment by mjbvz** [comment]
Just to make sure I understand, the request is for a command that returns the output file path for the currently active TS file? I don't think TS has an API for this but I'll check with the TS team

**Comment by isidorn** [comment]
Correct.

**Comment by isidorn** [comment]
I will not have time to look into this this milestone.
Pushing out to On-Deck.
@connor4312 if you are passionate and can tackle this in the JS-debug feel free to assign back to May
