### ISSUE TITLE
Debug dropdown text overlaps "v" icon

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95543]
![image](https://user-images.githubusercontent.com/2193314/79589530-649bdd80-808a-11ea-97cd-ca93d73e4f88.png)

Expected:

![image](https://user-images.githubusercontent.com/2193314/79589593-86956000-808a-11ea-81fc-c9bb9b38d5c7.png)

**Comment by isidorn** [comment]
This feels like the custom dropdown rendering issue. Unfortunetly the custom dropdown has no owner.
Will try to find an owner for it so it is no longer an orphan.

**Comment by isidorn** [comment]
Fixed in latest insiders. Sorry for the slow fix.
