### ISSUE TITLE
Terminal links should dismiss when their line content changes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95556]
Repro

1. Click the terminal to focus it
2. Hover a link
3. Press enter until the link position moves, it should dismiss when the text underneath no longer exists

![image](https://user-images.githubusercontent.com/2193314/79595995-a92c7680-8094-11ea-917f-0e753d26ca35.png)

**Comment by connor4312** [comment]
I still see this in today's insiders:

![](https://memes.peet.io/img/20-04-fffdf945-2b0e-440d-9b01-a7491c339216.png)

**Comment by Tyriar** [comment]
I think my xterm update didn't work, or I forgot to do it 🤔 There was another bug that was meant to be fixed that wasn't too.
