### ISSUE TITLE
Problème avec les fonctions anonymes

### ISSUE THREAD

**Issue by Sebooli** [microsoft/vscode#95558]
Je suivais un tuto sur le Code en JavaScript. Lors de la déclaration de ma fonction anonyme la première de mon couple mon couple de parenthèse est souligné en rouge. J'ai essayé le code sur SublimText et pas de problèmes. HELP ME !!!
/:(
Please !!!

**Comment by boltex** [comment]
Ajoute ici un exemple du code et de la fonction que tu essayé de codé, ou bien ajoute une (ou plusieurs) captures d'écran à ce post svp pour que l'on voit de quoi tu parles plus exactement. (bouton print-screen sur ton clavier) et ensuite colle directement ici..

**Comment by Sebooli** [comment]
Bonjour,
Désolé je viens de comprendre mon erreur je débute soyez indulgent !
mais merci pour la rapidité de votre réponse.
Amicalement
Sèb

**Comment by chrmarti** [comment]
Assuming this is solved.

**Comment by kiw-boop** [comment]
mon curseur n'écrit pas, n'efface pas et est parfois statique.
Comment résoudre ce problème, merci.

**Comment by chrmarti** [comment]
@kiw-boop Please file a new issue in English. Thanks.
