### ISSUE TITLE
Markdown previewing a link can't have whitespace in-between [] and ()

### ISSUE THREAD

**Issue by jbuschdev** [Microsoft/vscode#9555]
- VSCode Version: 1.3.1
- OS Version: Windows 10 Anniversary Preview

Steps to Reproduce:

1. Type `[Go to bing]         (https://www.bing.com)` inside .md file
2. Preview .md file in VS Code

Expected: See a hyperlink to bing.com w/ the text "Go to bing"
Results: See the raw markdown

Issue: Markdown preview doesn't handle whitespace between the [] and () of the link element.

**Comment by lextm** [comment]
There is no strict spec on Markdown, so it would be subjective to say whether there can be spaces between [] and (). Some parser allows that, while others not.

So if your case, please use the strictest form that all parsers agree on and leave no space there.

**Comment by jbuschdev** [comment]
You're right, there is no strict spec for Markdown, but I did find CommonMark which attempted to come up with a common standard for parsers to follow. 

http://spec.commonmark.org/0.26/#example-479

According to their spec, spaces are **not** allowed between [] and (). I'll update my markdown files to handle that. Seems github.com's parser does allow spaces, which led to my confusion =) 

Thanks
