### ISSUE TITLE
Semantic token coloring for variable has changed

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#95554]
Issue Type: <b>Bug</b>

Apologies if this is as designed, but I was thrown off by the color changes to variables in insiders.

Insiders:
<img width="778" alt="Screen Shot 2020-04-17 at 10 02 28 AM" src="https://user-images.githubusercontent.com/3672607/79595389-95344500-8093-11ea-8e50-4941486f50d9.png">

Stable:
<img width="933" alt="Screen Shot 2020-04-17 at 10 03 11 AM" src="https://user-images.githubusercontent.com/3672607/79595396-9a918f80-8093-11ea-82c4-7a755266e258.png">

VS Code version: Code - Insiders 1.45.0-insider (a3083e58e2a9e77f60e531acaa32e18527ae8439, 2020-04-17T08:08:39.508Z)
OS version: Darwin x64 18.7.0

**Comment by gjsjohnmurray** [comment]
Probably #95434 which has been closed as a dup of #95346

**Comment by RMacfarlane** [comment]
Thanks @gjsjohnmurray!
