### ISSUE TITLE
Coloring/Highlighting Issues for Exceptions and Constants in PHP

### ISSUE THREAD

**Issue by eeasoftware** [microsoft/vscode#95559]
- VSCode Version: 1.44.1
- OS Version: Windows 10 (on dev machine), Centos 7 & php7.4 (on server)

Steps to Reproduce:

1. Multiple Exception types in a catch block separated by a single pipe '|' highlights only the class name of the last class (see item1.png):

example: catch (\Namespace\Exception1 | \Namespace\Exception2 | \Namespace\Exception3 $e) {...}

- only Exception3 would have correct class coloring/highlighting

![item1](https://user-images.githubusercontent.com/25559097/79602440-b737c280-80a7-11ea-8364-3a2f96afd963.png)

2. When using a namespaced constant as a default value for a parameter in a function definition is colored red incorrectly (see item2.png).

example: public static function redirect(string $locationUri, array $responseCode = \Http\Response\Code::SEE_OTHER, array $additionalRedirectHeaders = []): void

- \Http\Response\Code::SEE_OTHER is colored red even though there is no error.  changing this to a [] colors correctly, but the other does not

![item2](https://user-images.githubusercontent.com/25559097/79602465-c159c100-80a7-11ea-8441-f988301e6f6b.png)

3. When using an Uppercase constant name that is the same as a PHP primitive (in my example: STRING vs string, the coloring is incorrect.  It is colored as a type instead of the constant name (see item3.png)

example: public const STRING = 2;

- String is colored as if it were a data type primitive instead of the color of constant declared names.

![item3](https://user-images.githubusercontent.com/25559097/79602482-c6b70b80-80a7-11ea-8be7-83e3eba0d73b.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Moved to owning repo https://github.com/atom/language-php/issues/390
