### ISSUE TITLE
Dead space with multiple panels

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#95561]
Here is a screen recording of the problem

![vscode-bug-n](https://user-images.githubusercontent.com/15984272/79609762-98f9b300-80f7-11ea-80bb-955905ff7d0c.gif)

The terminal is shrinked

Relates to feature #11889

Version: 1.45.0-insider
Commit: a3083e58e2a9e77f60e531acaa32e18527ae8439
Date: 2020-04-17T08:09:45.292Z
Electron: 7.2.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-91-generic

**Comment by Tyriar** [comment]
@sbatten I can only repro this when I collapse a pane above the terminal like in the gif. It seems like it's related to bad layout dimensions coming through but it seems to only happen in the terminal so it's probably on my end.

**Comment by opus131** [comment]
Would be great if this could be fixed. I'd like to move the terminal in the sidebar, but due to this issue I had to move it back to the panel.

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by sbatten** [comment]
still repros

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/80991

**Comment by Tyriar** [comment]
No longer repros:

![Image](https://user-images.githubusercontent.com/2193314/207092652-bc4cb3b0-346d-4def-b062-ee9e1d7387b5.gif)
