### ISSUE TITLE
[Docs] misleading key-binding "when" resource

### ISSUE THREAD

**Issue by jepetty** [microsoft/vscode#95568]
- VSCode Version: 1.44.0
- OS Version: Windows 10 19041.207

Steps to Reproduce:

1. Specify a command to appear only when `resource =~ /some regex/`

From the [documentation](https://code.visualstudio.com/docs/getstarted/keybindings#_contexts) for "resource" Resource context:
> The full Uri of the Explorer or editor file

I would expect that I should be able to filter by a full path, such as `file:///C:/foo/src/bar.cs` or `C:/foo/src/bar.cs`, but instead the path used to filter starts at the workspace root (i.e. if VS Code has opened folder "foo", the path used is `src/bar.cs`). Is this expected? Is there a way to filter when a command appears by the actual full URI, not the full workspace URI? 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
Please provide the full sample code for how to set this up until the issue comes up.

**Comment by jepetty** [comment]
I'll close this as I've discovered a solution to my problem.

It seems you can filter commands with `resource =~ /src[...]/` or `resource =~ /folderRoot/src[...]`, which allows you to determine which workspace root the resource originates from
