### ISSUE TITLE
Ship vs loader in notebok webview in Web

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#95560]
Issue Type: <b>Feature Request</b>

Webviews in web are iframes hosted on azure websites which is not in the same origin as the vscode web, so it can't access modules from vscode in the same way as running in Desktop. In notebook, we are using `vs/loader.js` as the builtin AMD loader in the webview, to make it work in Web, IMHO we need to bundle `vs/loader.js` together with other webview resources (`main.js`, `pre.js`, etc).

VS Code version: Code - Insiders 1.45.0-insider (a3083e58e2a9e77f60e531acaa32e18527ae8439, 2020-04-17T08:08:39.508Z)
OS version: Darwin x64 19.2.0

**Comment by rebornix** [comment]
@mjbvz does this make sense?

**Comment by mjbvz** [comment]
Sure. Here's the script that publishes the webview assets: https://github.com/microsoft/vscode/blob/8065712528e697a85a7d1ee4739530c0f8aae1b9/build/azure-pipelines/common/publish-webview.sh

The other (simpler) option is to inline the script

**Comment by rebornix** [comment]
@mjbvz  inlining the script is actually the right fix. Bundling loader.js with `main.js` doesn't fix the issue as the webview content is in the inner iframe, which will not have access to the loader script.
