### ISSUE TITLE
Live share extension opens in another VSCode opened instance

### ISSUE THREAD

**Issue by roslynn** [microsoft/vscode#95567]
- VSCode Version: 1.44.2
- OS Version: Windows 10 Pro 1903, 18362.752, x64 

Steps to Reproduce:

1. Open two projects in two separate VSCode instances
2. Install Live Share extension (v1.0.1615)
3. Click the extension icon
4. Click "Start collaboration session..."
5. Observe it opening in the other instance which is confusing if you have the project on the ither screen and you have not noticed that VSCode opened the panel but in a different window.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the LiveShare extension. Please file a new issue for it: https://github.com/MicrosoftDocs/live-share/issues
