### ISSUE TITLE
Live share extension applies colaborators formatting rules

### ISSUE THREAD

**Issue by roslynn** [microsoft/vscode#95564]
OS: Windows 10 x64
VSCode version: 1.44.2
Live-Share extension installed, version v1.0.1615
No formatting rules on Save are set on my VSCode.
Started live share session and invited a collaborator to join me.
When I clicked save the code formatted to follow the rules that the collaborator had put in place.

I think the expected behaviour should be to enforce the formatting rules of the presenter (host).

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the LiveShare extension. Please file a new issue for it: https://github.com/MicrosoftDocs/live-share/issues
