### ISSUE TITLE
Opening a single file should be almost be as quick as opening up in a basic text editor

### ISSUE THREAD

**Issue by Mike737377** [Microsoft/vscode#9556]
- VSCode Version: 1.3.1
- OS Version: Windows 10

I've noticed that the start up times for VS code are slowing down with each iteration of VS Code. 

Steps to Reproduce:
1. Open windows explorer and browser to a file which you want to edit (eg. text, markdown, html, javascript file)
2. Open vs code via explorers file context menu using the "Open in VS Code" option
3. Initial load time to the point where you can viewing and editing the file should be as close to opening up in something similar to notepad.

Expectations:
- Intellisense or syntax highlighting doesn't need to be loaded straight away, it could be deferred until the editor has finished the initial load.
- This should not apply to loading up whole directories/projects/solutions as the individual users task isn't a quick edit or view.

I'm hoping by raising this issue that performance benchmarks for VS code initial load times will be established for future releases.

**Comment by eByte23** [comment]
+1

**Comment by Mike737377** [comment]
Probably could be worked in along with the performance tests in pull request #9545

**Comment by egamma** [comment]
>I've noticed that the start up times for VS code are slowing down with each iteration of VS Code. 

We have telemetry on the startup time, but I currently fail to open the report. @bpasero may be you have more luck. Does the report confirm the slow down?

**Comment by bpasero** [comment]
I can open the report but I am not seeing any data for post 1.0 so I cannot make a qualified statement.

Moving to redmond to get this report working again.

**Comment by digeff** [comment]
+1 It takes several seconds when I use Open in Code to see the file, and I'd love for this to be instantaneous...

**Comment by chrisdias** [comment]
i think this issue can be closed in favor of all the work going on in #15455.
