### ISSUE TITLE
Fuzzy search (ctrl-p) much slower after most recent update

### ISSUE THREAD

**Issue by callumdmay** [microsoft/vscode#95578]
Issue Type: <b>Bug</b>

Fuzzy search seems a lot slower since the most recent update. Can take upwards of 30 seconds to a minute to fuzzy find a file, when before it would take less than 10 seconds with an average of 3 to 4 seconds.

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9940X CPU @ 3.30GHz (28 x 3312)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.71GB (37.24GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
copy-relative-path|ale|0.0.2
vscode-svgviewer|css|2.0.0
git-diff-and-merge-tool|dav|1.0.1
vscode-eslint|dba|2.1.3
gitlens|eam|10.2.1
beautify|Hoo|1.5.0
cpptools|ms-|0.27.0
vscode-gn|npc|1.1.0
vscode-icons|vsc|10.1.1
vscode-jumpy|wma|0.3.1
clang-format|xav|1.9.0
material-theme|zhu|3.2.5

</details>

**Comment by chrmarti** [comment]
@roblourens Did anything change here? (/cc @bpasero)

**Comment by roblourens** [comment]
Can you update to 1.44.2 and let me know whether it's any different? There was a search-related issue fixed but not sure whether it's the same.

**Comment by callumdmay** [comment]
No that didn't fix it. I have a repro between two devices, one running 1.44.2 and one running 1.43.1 and the difference is quite apparent

**Comment by roblourens** [comment]
There haven't been any other search related changes lately. Do any tips in here sound relevant? https://github.com/microsoft/vscode/wiki/Search-Issues Is MsMpEng.exe using all your cpu?

**Comment by callumdmay** [comment]
Just checked and MsMpEng.exe isn't using an abnormal amount of cycles. My workspace is very large (It's the Chromium repo) however that's the case on both devices. The one running 1.43.1 is actually much less powerful than the one running 1.44.2, however the fuzzy search is resolving on that device in 1/3 of the time.

**Comment by callumdmay** [comment]
Is there anything else I can check or test that would be useful here?

**Comment by roblourens** [comment]
Is rg.exe using high CPU the whole time? Or what is? Or could it be a disk bottleneck?

**Comment by callumdmay** [comment]
Nothing stands out as using high CPU, rg spikes initially on both devices but then uses minimal cycles or the process exits. Nothing stands out in terms of consuming heavy CPU. Disk read/write never breaks 10% on either device. I also just confirmed that downgrading to 1.43.1 on the offending device solves the issue
