### ISSUE TITLE
Jupyter notebook refuses to save

### ISSUE THREAD

**Issue by tommly** [microsoft/vscode#95571]
Issue Type: <b>Bug</b>

Jupyter notebook sessions refuse to save. Auto-save is enabled. The tab shows unsaved work indicator *. The save button is active (not grey) and unclickable. The file was opened and is no longer in the file system, apparently removed by VScode. When closed all progress and the file itself is lost. Not sure how to reproduce as it seems to happen at random. Only workaround is to copy and paste all cells into new session. Randomly, that session will also stop saving during this process. 

This is similar to the issue shown below, except the listed workarounds (add/remove line numbering, github) do not work.

https://developercommunity.visualstudio.com/content/problem/165245/save-not-doing-anything.html

-Tom

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T11:22:13.689Z)
OS version: Linux x64 5.3.0-7642-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.36GB (14.62GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.3.71659
vscodeintellicode|Vis|1.2.6

</details>

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Python extension. Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose
