### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by spidax** [microsoft/vscode#95579]
My vscode startup is extremely slow, reinstalling it or removing cached data didn't help, disabling extensions didn't increase load time by much either.

Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

[prof-3848.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/4495858/prof-3848.extHost.cpuprofile.txt)
[prof-3848.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/4495859/prof-3848.main.cpuprofile.txt)
[prof-3848.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/4495860/prof-3848.renderer.cpuprofile.txt)
[Startup Performance.txt](https://github.com/microsoft/vscode/files/4495861/Startup.Performance.txt)

**Comment by jrieken** [comment]
This is https://github.com/microsoft/vscode/issues/56644 which is that something on machine slows down the creation of the renderer process. We have learned that this is

* AV software
* the Badlion Client (see https://github.com/microsoft/vscode/issues/56644#issuecomment-613858693)
