### ISSUE TITLE
Collapsible types in TypeScript

### ISSUE THREAD

**Issue by 16oh4** [microsoft/vscode#95577]
I would like to be able to collapse types in TypeScript just like other code blocks.

![image](https://user-images.githubusercontent.com/37783822/79623637-1535cb80-80e3-11ea-8f09-fd557c42cbfa.png)

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/38080 to track upstream

**Comment by 16oh4** [comment]
@mjbvz Awesome, thanks a lot to everyone at the TypeScript team!!
