### ISSUE TITLE
pdksh, dash, mksh, posh, hushlogin not highlighting as shell script code

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#95583]
VSCode does a decent job highlighting many different shell script languages. But it doesn't seem to be aware that pdksh, dash, mksh, and posh, especially configuration files like `.hushlogin` and shebanged extensionless scripts, are POSIXy shell scripts. They just highlight as Plain Text files instead.

Same for `.tcshrc`, that's a Tcsh shell script.

**Comment by aeschli** [comment]
PR welcome!
