### ISSUE TITLE
Add icon file extension for Latino Programming Language

### ISSUE THREAD

**Issue by MelvinG24** [microsoft/vscode#95585]
Hi everyone,

I am working on this project calls Lenguaje Latino (Latino Programming Language) which is a programming language with Spanish syntax. I have created a VS-Code extension for this language, but I couldn't find a way to associate my icons to the language extension file from my extension.

I will love with you can add this icons on VS-Code code so it can apply the corresponded desktop icons to the language extension file which is ".lat"

I have already created the icons, I will leave the link down bellow for your review
- icon file win32:
[Latino-iconFile-win32.zip](https://github.com/microsoft/vscode/files/4496125/Latino.zip)
- icon file darwin:
[Latino-iconFile-darwin.zip](https://github.com/microsoft/vscode/files/4496126/Latino.zip)

here is as well a link to my extension if anyone want to have a look
https://marketplace.visualstudio.com/items?itemName=MelvinGuerrero.latino-vscode

Thank you so much

**Comment by gjsjohnmurray** [comment]
I think you need to get your icons adopted by https://github.com/jesseweed/seti-ui and then they will subsequently arrive in VS Code

**Comment by MelvinG24** [comment]
> I think you need to get your icons adopted by https://github.com/jesseweed/seti-ui and then they will subsequently arrive in VS Code

Thank you for respond. I have already pull my request on seti-ui repository, but from what I understand they only work with the U.I. icons not with the desktop file icons, isn't it?

**Comment by gjsjohnmurray** [comment]
@MelvinG24 see https://github.com/microsoft/vscode/issues/83659#issuecomment-548049112

**Comment by misolori** [comment]
Thanks for the suggestion, but we're not tracking file icon requests and will close this. See https://github.com/microsoft/vscode/issues/60699#issuecomment-429208011 for details.
