### ISSUE TITLE
EXTENTIONS list empty

### ISSUE THREAD

**Issue by alanbohuang** [Microsoft/vscode#9558]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1.  Command Palette (Ctrl+Shift+P) inside VS Code and type ext install to run the Extensions: Install Extension command
2. only get @popular in the EXTENSIONS list, what I am trying to find is Chrome Debugging for VS Code
https://code.visualstudio.com/blogs/2016/02/23/introducing-chrome-debugger-for-vs-code

**Comment by lextm** [comment]
Please refer to "Search for an Extension" section,

https://code.visualstudio.com/docs/editor/extension-gallery

**Comment by joaomoreno** [comment]
Simply replace `@popular` with the search term `chrome debugging`.
