### ISSUE TITLE
Debugger can't display Rust chars (UTF-32)

### ISSUE THREAD

**Issue by DeanRoddey** [microsoft/vscode#95580]
Version: 1.44.1 (system setup)
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:49:29.947Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT ia32 10.0.18363
Rust (rls) 0.7.2

This may not actually be an issue with VSC, but I have no way to figure out who is actually at fault so I'm trying to whittle it down.

When debugging Rust in VSC, it seems incapable of displaying the values of Rust chars (which are UTF-32 code points.) I brought this up on the Rust repo and the implication was it couldn't be their code/symbol generation problem. So I'm going to the other end, and I guess I'll chop away at the ends till only one party is left.

The screen cap shows a local char being declared and what gets displayed in the debugger. One obvious possibility is that VSC isn't set up to display UTF-32 and might need to transcode such a value in order to display it, which would require knowing it's UTF-32.

Does the Rust plugin have any responsibility in this area?

![RustCharDbg](https://user-images.githubusercontent.com/45377887/79626235-859d1680-80fc-11ea-8d94-6c843514daa0.png)

**Comment by isidorn** [comment]
@DeanRoddey thanks for filling this issue, but yeah the rust plugin has responsibility. They should return the values of variables as string as speicifed in the debug adapter protocol.
So please file an issue in their repository and tell them that they can ping me or @weinand for clarification on that issue.

Thanks. Thus closing this one

**Comment by DeanRoddey** [comment]
OK, I posted over there, and linked them to this one for background.
