### ISSUE TITLE
Unindenting moves cursor to beginning of line

### ISSUE THREAD

**Issue by mxmlnkn** [microsoft/vscode#95591]
Issue Type: <b>Bug</b>

This is basically the same as demonstrated in #53748 I don't understand why it was closed. I run into this every minute or so and it's frustrating.

![](https://user-images.githubusercontent.com/484784/42398201-8a3f063c-812e-11e8-84fe-a936a894559c.gif)

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 5.3.0-45-generic

**Comment by alexdima** [comment]
@mxmlnkn

This does not reproduce for me:

![Kapture 2020-04-24 at 23 26 51](https://user-images.githubusercontent.com/5047891/80258308-38342280-8683-11ea-8da7-004249915260.gif)

**Comment by mxmlnkn** [comment]
I did a bisect on my settings and the bug only reproduces with the `"editor.autoIndent": "keep"` line.

**Comment by alexdima** [comment]
Thank you, I can reproduce now with the following steps:
* use `"editor.useTabStops": false`
* have a file with the content:
```
        just some text
        
```
* position cursor at the end of the second line (after the whitespace):
![image](https://user-images.githubusercontent.com/5047891/80366127-055b7b80-8889-11ea-8587-6d7571e549c9.png)
* press `Shift` + `Tab`

**Comment by mxmlnkn** [comment]
Cool, that was fast. I hope it works. Thank you.
