### ISSUE TITLE
lost live-preview folders

### ISSUE THREAD

**Issue by adhubyani** [microsoft/vscode#95592]
- VSCode Version: 1.4.4.2
- OS Version: windows 10

hello
i started VScode today and found that it was automatically updated to V1.4.4.2 and terminated "live-preview" folder which was created to save files for live preview extension
https://github.com/profimedica/LivePreview-VSCode-Extension
Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
I suggest you report this to the extension author.

**Comment by adhubyani** [comment]
> I suggest you report this to the extension author.

ok, thank you
