### ISSUE TITLE
Cursor repositioning as I type the code

### ISSUE THREAD

**Issue by prachi14-techved** [microsoft/vscode#95593]
We have written the `needed
Issue Type: <b>Bug</b>

VS Code has been acting in a wiered manner past 7 days, as the extensions were not working. Today  there was a release due to which I am unable to type CSS Code. The moment I type something it repositions the cursor to the last line in the file. Moreover on pressing the enter key  the code does not start on the new line whereas it gets back to the start of previous line. Kindly provide a fix release as soon as possible.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (7.76GB free)|
|Process Argv|E:\Prachi\Projects\Mobileum\Mobileum-WBA-18-04-2020|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
project-manager|ale|10.11.0
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.1.3
jquerysnippets|don|0.0.1
css-flexbox-cheatsheet|dzh|2.0.1
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
mithril-emmet|Fal|0.7.5
auto-rename-tag|for|0.1.1
beautify|Hoo|1.5.0
Angular2|joh|9.1.2
css-snippets|joy|1.0.2
css-compact|jso|1.0.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
code-fragments|mar|1.2.0
vsliveshare|ms-|1.0.2000
material-icon-theme|PKi|4.0.1
vscode-css-peek|pra|3.0.2
LiveServer|rit|5.6.1
css-tree|sac|1.1.0
html-to-css-autocompletion|sol|1.1.2
css-auto-prefix|spo|0.1.7
guides|spy|0.9.3
bootstrap4-vscode|the|6.1.0
html-preview-vscode|tht|0.2.5
refactor-css|urb|0.4.2
html-snippets|wge|0.1.5

(1 theme extensions excluded)

</details>
` data into your clipboard because it was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment]
If none of your extensions are working, first check the pinned issue about Quick Heal antivirus impacting VS Code.

If that doesn't apply, I suggest the following procedure.

Start by disabling all your extensions. There's a command on the Command Palette (type 'disable' to locate it). If the problem goes away, use the Extensions section to disable all of yours, then re-enable them selectively until the problem returns.

**Comment by prachi14-techved** [comment]
Hi John,

 

Thanks for the quick response. Will try it and get back.

 

Cheers!!!

**Comment by prachi14-techved** [comment]
Hi,

 

Thanks a lot for the quick ation on the same. This issue has been closed and no longer persists.

 

Thanks & Regards,

Prachi Gad | Sr.Associate - UI Development

Contact :022 6132 1000 | Ext : 330

Email :  <mailto:prachig@techved.com> prachig@techved.com

"High Quality. On Time. We swear by it!"

Techved Logo

Latest Publication:

 <https://tinyurl.com/y65d98xc> https://tinyurl.com/y65d98xc

See us at:

www.techved.com


 <https://www.linkedin.com/company/techved-consulting2019> linkedIn

 <https://www.facebook.com/techvedconsulting/> Facebook

 <https://twitter.com/techved> Twitter

 <https://www.instagram.com/techved_consulting/> Instagram
