### ISSUE TITLE
Integrated terminal blank commands

### ISSUE THREAD

**Issue by renanmpg** [microsoft/vscode#95602]
- OS Version: Windows 10

When I use the terminal, all my commands are blank, and the colors are weird, looks like is selected, but it isn't!

![Captura de tela 2020-04-18 12 07 05](https://user-images.githubusercontent.com/63917260/79641499-44dde580-816e-11ea-9ed6-b8e88496ca77.png)

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/needsMoreInfo
