### ISSUE TITLE
up arrow in integrated terminal displays as escape sequence

### ISSUE THREAD

**Issue by tomprogers** [microsoft/vscode#95606]
Issue Type: <b>Bug</b>

When I press the up arrow in the integrated terminal -- to repeat the last command -- the command displays as:

```
^[[A
```

It should instead display the text of the last command, e.g.:

```
yarn start
```

If I hit Enter, it still executes the last command properly.

This problem did not occur until VS Code updated yesterday.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz (4 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
vscode-eslint|dba|2.1.3
spacecadet|geo|0.0.1
todo-tree|Gru|0.0.172
vscode-power-mode|hoo|2.2.0
docthis|joe|0.7.1
vscode-peacock|joh|3.7.0
vscode-html-format|moh|0.0.4
sublime-keybindings|ms-|4.0.6
fix-json|oli|0.1.2
vscode-graphql|Pri|0.2.14
synthwave-vscode|Rob|0.1.3
sort-lines|Tyr|1.9.0
markdown-all-in-one|yzh|2.8.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Can you share your settings.json and [do this](https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging) to see what is getting sent to the shell?

**Comment by tomprogers** [comment]
This is embarrassing, but after a reboot, the problem seems to have remedied itself. Having read the linked wiki article, I suspect the problem may have been triggered by a lot of zooming I was doing for screenshotting purposes.

If you still want my settings and terminal logs, let me know. Otherwise, I think you can close this one.

**Comment by Tyriar** [comment]
If it happens again and you find out more let me know.
