### ISSUE TITLE
lost connection device. Exited (sigterm)

### ISSUE THREAD

**Issue by wonao** [microsoft/vscode#95604]
Issue Type: <b>Bug</b>

I working on flutter 2.2 and yesterday, it was compinling well, but today, without any appearing reason, I have this error code when I try to compile :   
```

sK9LdDSXh9RzyfkztFjKIg==/lib/x86/libflutter.so (offset 0x113f000)
    #18 pc 000007d3  <anonymous:cdd80000>
Lost connection to device.
Exited (sigterm)
```

Compiling is working well on android Studio...

Therefore and maybe linked, I encounter an error message not blocking : 
```
flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [version 10.0.18363.778], locale fr-FR)
    • Flutter version 1.12.13+hotfix.9 at E:\dev\src\flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Youstella\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\Youstella\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
```

Can you help me ?

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.9.1
flutter|Dar|3.9.1
material-icon-theme|PKi|4.0.1

</details>

**Comment by chrmarti** [comment]
This doesn't look like a problem with VS Code. Which process prints the 'lost connection' error message?

**Comment by wonao** [comment]
I'm trying to debug a flutter code. I was first thinking it was a problem with VS code, bu tthe problem is on my app code ..., but I annot compile it and debug it by myself. Here is my class code : 
`import 'package:flutter/material.dart';

class VisitCard extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xFF6A1B9A),
      appBar: AppBar(
        title: Text('Mon Profil'),
        backgroundColor: Colors.transparent,
        elevation: 0.0,
      ),
      body: Center(
          child: Padding(
        padding: EdgeInsets.all(15),
        child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              CircleAvatar(
                radius: 70.0,
                backgroundImage: AssetImage('assets/kitty.jpg'),
              ),
              Card(
                child: Text(
                  'Alice',
                  style: TextStyle(fontFamily: 'YatraOne', fontSize: 10),
                ),
              ),
              Card(
                  child: Text('Une petite merveille !',
                      style: TextStyle(
                        fontFamily: 'JosefinSans',
                        fontSize: 10,
                      ))),
              RaisedButton(
                onPressed: () {},
                child: Text('Plus d\'infos',
                    style: TextStyle(
                      color: Colors.white70,
                    )),
                color: Colors.blueAccent,
              ),
            ]),
      )),
    );
  }
}
`

**Comment by chrmarti** [comment]
Sorry, I don't know Dart. Best to ask in the Dart community.
