### ISSUE TITLE
Make folder area's file differences in folder more exaggerated

### ISSUE THREAD

**Issue by CrazyVideoGamez** [microsoft/vscode#95619]
Could you guys make it so the file is more easier to see which folder each file is in what folder? Because, it is hard to see what files are in what folders. For example, files inside a folder are on the same "level" as the files outside that folder.
![Image of folder area](https://user-images.githubusercontent.com/59106025/79673883-ce5fd880-81ab-11ea-93d9-8ef9a7ad090e.png)

**Comment by gjsjohnmurray** [comment]
Try increasing `workbench.tree.indent`

**Comment by gjsjohnmurray** [comment]
Also, are you using file icon theme extension? If so, please test with one of the built-in ones (Minimal or Seti) in case the one you're using has faulty alignment.

**Comment by joaomoreno** [comment]
Setting is `workbench.tree.indent`.
