### ISSUE TITLE
Gutter customization

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#9561]
- VSCode Version: 1.4.0-insiders
- OS Version: Windows 10 x64

People asked for this feature when they request for git blame info #2248. Now I found we are relying on this as well when implementing Vim's relative line numbers.

![image](https://cloud.githubusercontent.com/assets/876920/17011009/f0f23d9e-4f3b-11e6-9eae-7bb5da4bd65a.png)

See image above, you can set relative line numbers in Vim then you can easily know how many lines up or down you want to operate, instead of calculating the line numbers yourself. Currently it's not possible.

cc @kieferrm

**Comment by kieferrm** [comment]
Starting with @sandy081 as he is looking into the VIM gaps.

**Comment by ryu1kn** [comment]
I'm very curious how or to what extent we will be able to customise a gutter.

I've developed an extension called Annotator (https://github.com/ryu1kn/vscode-annotator) which displays git blame output along with your code. I wanted to display blame information into a gutter but as the feature is not yet available, I ended up using a html view, aligning the blame with the code on my own.

![Annotator](https://raw.githubusercontent.com/ryu1kn/vscode-annotator/master/images/screencaptures/light-theme.png)

By using a raw html, I could easily add some features like colouring each commit, but I also had to give up some basic features like syntax highlighting or text search; so I'm thinking to rewrite the extension if the customisable gutter become available.

**Comment by alexandrudima** [comment]
`editor.lineNumbers: "relative"` and in the API at text editor options `lineNumbers: "relative"`. To check with @jrieken if the API is good enough -- @jrieken pls see a8894fbf0edb35e3aab742b4c540b25c11ac60cc and let me know if you think it is ok -- it reflects the user setting...

**Comment by alexandrudima** [comment]
There is a slight change from my previous comment, the API now contains an enum and the user settings are "on" | "off" | "relative"

**Comment by agauniyal** [comment]
What about @ryu1kn's request for vscode-annotator. Any plans in upcoming releases?
