### ISSUE TITLE
Default keybindings for search settings are inconsistent

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#95618]
Issue Type: <b>Bug</b>

This is the default keybinding to toggle 'whole word'
```
{
  "key": "alt+w",
  "command": "toggleSearchWholeWord",
  "when": "searchViewletFocus"
}
```

This is the default keybinding to toggle 'case sensitive'
```
{
  "key": "alt+c",
  "command": "toggleSearchCaseSensitive",
  "when": "searchViewletFocus && !fileMatchOrFolderMatchFocus"
}
```

Notice the difference in the when clauses. The case sensitive binding has the extra `!fileMatchOrFolderMatchFocus`. This means that, depending where exactly your focus in the search viewlet is, there are places where Alt+W works and Alt+C does not.

I've checked the rest of the default bindings and nothing else is bound to Alt+C that would require this exception. Both bindings should use the same when clause. Specifically `"when": "searchViewletFocus"`.

VS Code version: Code - Insiders 1.45.0-insider (a3083e58e2a9e77f60e531acaa32e18527ae8439, 2020-04-17T08:09:47.238Z)
OS version: Windows_NT x64 10.0.18362

Extensions: none

**Comment by roblourens** [comment]
@sandy081 it has been like this a long time, from https://github.com/microsoft/vscode/commit/dc62a6efcc28f9c7540f06620c1ecb5155081f3f

On mac, the keybinding conflicts with the "copy path" command, is that why you added that? On windows there is no conflict. And I also noticed that "copy path" doesn't work in search from the keybinding anyway, I can fix that.

**Comment by sandy081** [comment]
I think this is like this to be in consistent with Find widget.

**Comment by roblourens** [comment]
He's asking about why the when clause is different between toggleSearchWholeWord and toggleSearchCaseSensitive - the find widget equivalent commands aren't different.

**Comment by sandy081** [comment]
Ah ok. It seems to me the reason you mentioned (but sorry not 100 percent sure). Please feel free to remove/fix it.

**Comment by roblourens** [comment]
I'm just going to leave it. I don't want to change the keybindings and users don't really need to change that toggle when focus isn't on the input box. But I'll use this issue to fix the fact that some of the search commands don't work with keybindings at all.

**Comment by akbyrd** [comment]
Please don't leave the edge case in there. I'd rather not need to keep keybindings to work around jank.

**Comment by roblourens** [comment]
I think the right fix to make it consistent would be adding the extra when clause to all the keybindings which I assume you don't want. Either that or change the keybinding for "copy path" and make people unhappy. I would change the when clause just for Mac if that was possible.

**Comment by roblourens** [comment]
I mean, I guess it is possible, I'll only add the when clause for mac. Hope that helps.

**Comment by akbyrd** [comment]
Thanks, that covers my case. I'd argue that adding the clause the other keybinding on mac would be worthwhile to keep them consistent. But I don't use the platform so I don't have much stake in it.
