### ISSUE TITLE
Markdown activates extensions on focus out

### ISSUE THREAD

**Issue by borishere** [microsoft/vscode#95615]
Issue Type: <b>Bug</b>

1. Click on 'Notifications' button
2. Click outside of VS Code window
3. 'Activating Extensions...' messages will appear
![678](https://user-images.githubusercontent.com/4622497/79671112-83a48780-81d0-11ea-83b8-c8bca5bec628.gif)

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (2.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.1.0
pascal|ale|9.0.0
pascal-formatter|ale|2.2.0
vscode-toggle-quotes|Bri|0.3.2
turbo-console-log|Cha|1.4.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|2.1.3
vscode-faker|dee|1.3.1
vscode-npm-script|eg2|0.3.11
output-colorizer|IBM|0.1.2
bridlensis|idl|1.0.1
innosetup|idl|1.3.0
nsis|idl|3.26.1
vscode-placeholder-images|Jak|0.1.0
HTMLHint|mka|0.6.0
vscode-filesize|mkx|2.1.4
python|ms-|2020.3.71659
cpptools|ms-|0.27.0
incrementor|nms|0.1.0
LiveServer|rit|5.6.1
vscode-qt-for-python|sea|0.4.2
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.8.0
vscode-stylelint|sty|0.84.0
open-in-browser|tec|2.0.0
material-theme|zhu|3.2.5

</details>

**Comment by bpasero** [comment]
This looks like extensions activating when window focus looses. I do not think this is related to notifications at all.

**Comment by alexdima** [comment]
@jrieken in this case, I think there is one startup extension that blocks the extension host for more than 5 seconds. So there are very many extensions that take longer than 5s to activate, so the `Activating Extensions...` message is shown once per extension that takes longer than 5s to activate.

**Comment by jrieken** [comment]
This seems to be triggered by the markdown preview, at least that's the activation events that fired on focus out

<img width="1081" alt="Screenshot 2020-04-27 at 09 15 59" src="https://user-images.githubusercontent.com/1794099/80344350-b7824b80-8867-11ea-871c-15762073b7f8.png">

**Comment by jrieken** [comment]
Adding @mjbvz for the activation but this might as well work as designed

@bpasero the problem is the showing of progress as notification which was in a way a breaking change. The status-bar-progress has a default delay of 150ms, the notification area has none which makes this so flicker'ish

**Comment by bpasero** [comment]
@jrieken this is the change we did to show all window progress (the one that appears in status) as hidden notifications right?

**Comment by jrieken** [comment]
I believe so, but I don't really know what happened there.

**Comment by bpasero** [comment]
I pushed a change to bring back `150ms` delay. I no longer see this appearing, but leaving open for the fact that we activate extensions on focus out.

**Comment by mjbvz** [comment]
This is a with webviews. To repro:

1. Open markdown preview.
1. Put it in a background tab
1. Reload window
1. Now click outside the window.

The markdown preview should not be activated here since the preview is not visible
