### ISSUE TITLE
Live Share audio problem

### ISSUE THREAD

**Issue by TutoDS** [microsoft/vscode#95611]
Ui.
I'm using macOS and Live Share Audio (my microphone) not working.
Anyone can help me?

**Comment by TutoDS** [comment]
When try start a call appear this:
```
SlimCore not found: /Users/tutods/Library/Application Support/Code/User/globalStorage/ms-vsliveshare.vsliveshare-audio/slimcore-4.0.2019.37.01.4/bin/slimcore.node
```

**Comment by TutoDS** [comment]
I try reinstall and is stuck with this message:
```
Downloading dependencies...: Finishing VSLS Audio installation (downloading)...
```

**Comment by TutoDS** [comment]
Anyone plase??

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the LiveShare extension. Please file a new issue for it: https://github.com/MicrosoftDocs/live-share/issues
