### ISSUE TITLE
VS Code ignores tsconfig.json despite being set to use latest Typescript

### ISSUE THREAD

**Issue by CG-Tespy** [microsoft/vscode#95613]
Issue Type: <b>Bug</b>

Create a project with a tsconfig file with these contents:

    {
      "compileOnSave": false,
      "compilerOptions": {
          "sourceMap": true,
          "target": "es6",
          "experimentalDecorators": true,
          "noImplicitAny": false
      },
    }

Create a someThing.ts file with these contents:

    'use strict';

    class someThing
    {
        someStr: string = "This is a string";
        num: number = 1;
        get Num(): number { return this.num; }
        get SomeStr(): string { return this.someStr; }

    }

Try running tsc someThing.ts in the terminal, and see errors about how you can only use accessors in es5 or later despite the tsconfig file.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (9.70GB free)|
|Process Argv|D:\Documents\Programming\JavaScriptSandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
shaderlabvscodefree|aml|1.1.6
githistory|don|0.6.3
vscode-babel-coloring|dza|0.0.4
vscode-npm|fkn|3.3.0
auto-using|Fud|0.7.15
godot-tools|gee|1.0.3
gc-excelviewer|Gra|2.1.34
csharpextensions|jch|1.3.1
docthis|joe|0.7.1
docomment|k--|0.1.9
vscode-language-babel|mgm|0.0.27
rmmvpluginsnippet|MJM|1.4.4
rmmvvscodeplugingenerator|MJM|0.4.0
csharp|ms-|1.21.17
python|ms-|2020.3.71659
cpptools|ms-|0.27.0
vscode-typescript-next|ms-|3.9.20200417
debugger-for-chrome|msj|4.12.6
javascript-test-runner|osh|1.2.1
tsimporter|pmn|2.0.1
java|red|0.60.0
vsc-nwjs|rua|1.0.18
shader|sle|1.1.4
unity-tools|Tob|1.2.3
unity-debug|Uni|2.7.5
errorlens|use|3.1.0
vscodeintellicode|Vis|1.2.6

</details>

**Comment by mjbvz** [comment]
`tsc` does not automatically pick up the tsconfig when you pass it a file. You need to compile the project instead: `tsc -p tsconfig.json`
