### ISSUE TITLE
the window Visual Studio Code doesnt show up when open file

### ISSUE THREAD

**Issue by anhlt570** [Microsoft/vscode#9562]
- VSCode Version: Code - Insiders 1.4.0-insider (0421a3492317a4ca1adaa7f3513391d312cb10c3, 2016-07-14T05:07:04.955Z)
- OS Version: Windows_NT ia32 10.0.10586
- Description : why Visual Studio Code doesnt open the window and show it on top of screen imediatly when i open a file. i always have to open it and then click on the icon on taskbar to preview the file. that is ridiculous
Steps to Reproduce:

1. open any file by visual stuido code(both right click then choose open by  Visual Studio Code and double click)

**Comment by kieferrm** [comment]
This happens when vscode is already running and the file is opened in a new window. When vscode does not run yet, it will launch and be activated.

**Comment by anhlt570** [comment]
yes. the vscode is launch but what i want is that it will be show up the window when i open another file from explorer. I like this editor but opening  a file and then click the icon on taskbar to show the window really annoyed me
Or is there a setting for that??

**Comment by kieferrm** [comment]
@anhlt570 there is no setting. My comment was a clarification of what you see for @bpasero. It was not a justification of the current behavior.

**Comment by bpasero** [comment]
This looks like https://github.com/Microsoft/vscode/issues/929
