### ISSUE TITLE
Silverblue missing dependency `libX11-xcb`

### ISSUE THREAD

**Issue by hholst80** [microsoft/vscode#95627]
Silverblue missing dependency `libX11-xcb`

```
⬢[hh@toolbox ~]$ sudo dnf install code
Last metadata expiration check: 0:01:47 ago on Sun Apr 19 10:15:27 2020.
Package code-1.44.2-1587059974.el7.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
⬢[hh@toolbox ~]$ code
/usr/share/code/bin/../code: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
⬢[hh@toolbox ~]$ 
```

Workaround:

install `libX11-xcb` package. then code works as expected.

**Comment by hholst80** [comment]
A fix here seems almost trivial yet the duplicate bug has been open for roughly four years? What is the underlying problem?

**Comment by Tyriar** [comment]
It probably is, the solution will involve adding things to https://github.com/microsoft/vscode/blob/master/resources/linux/rpm/dependencies.json and then verifying it during PR with a product build.
