### ISSUE TITLE
Support left and right scroll wheel

### ISSUE THREAD

**Issue by Flaryer** [microsoft/vscode#95625]
Sometimes the code (take C ++ as an example) will be very long, and the screen is very small, you need to drag the code left and right, and the slider that drags left and right is too narrow, the mouse moves from top to bottom to the slider, slightly Moving too far will trigger the function of adjusting the size of the bottom window. I don't know if there is a good solution to this.  
But when I use the left and right scroll function of the Logitech mouse, the first scroll is effective, the second scroll is invalid, which is very bad. Hope to fix it.
![1](https://user-images.githubusercontent.com/30646834/79681890-978fce00-8250-11ea-94ac-678ac6ad0cb4.png)

**Comment by alexdima** [comment]
@Flaryer Holding Shift and scrolling the mouse wheel will scroll horizontally. Would that work for you?

**Comment by Flaryer** [comment]
It works! thank you! I'm sorry to cause trouble for you because you don't have a deep understanding of the software!
