### ISSUE TITLE
Intellisense not autocompleting the fields name in jupyter notebooks.

### ISSUE THREAD

**Issue by akshitgupta29** [microsoft/vscode#95635]
Issue Type: <b>Bug</b>

Intelli sense is not working with the jupyter notebooks.

![image](https://user-images.githubusercontent.com/12370891/79686419-d415f680-825d-11ea-9e19-9cd72fd7aea7.png)

The same thing works very well in the jupyter notebooks.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-html-css|ecm|0.2.3
code-runner|for|0.9.17
vscode-docker|ms-|1.0.0
python|ms-|2020.3.71659
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.6
vscode-css-peek|pra|3.0.2
view-in-browser|qin|0.0.5
view-in-default-application|see|3.3.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by akshitgupta29** [comment]
PS: I am using two different laptops and accordingly two versions of VS code as well. But the issue is in there for both of them.

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Python extension. Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose
