### ISSUE TITLE
HTML Closing tag Setting

### ISSUE THREAD

**Issue by mmostafa261** [microsoft/vscode#95648]
Issue Type: <b>Feature Request</b>

Hello anyone
I request you to add more advanced settings about the html auto close tags
to be 
1- Html Auto Close Tags (Which add closing tag as soon as you finish writing its opening tag and it make it hard for us as every tag we finish we will use the arrow keys to skip the tag)
2- Auto add closing tag as i write "</" (like sublime text 3) it really make it easier for us.
I hope that you make this as soon as you see my report
*If there anyway to edit in vs code internal files to disable the function of auto close tags from roots please say it
Thanks for reading
But you're combining both of the settings in one setting which make it hard

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

**Comment by octref** [comment]
Both are available:

- When finishing writing `<div>` with `>`, auto complete `</div>`
- When writing `<div></`, auto complete `div>`

Please clarify what you want.
