### ISSUE TITLE
width in the left side of each line

### ISSUE THREAD

**Issue by dhjdf98dfgnj789** [microsoft/vscode#95643]
- VSCode Version :Version: 1.44.1 (system setup)
- OS Version: Windows_NT x64 

Does this issue occur when all extensions are disabled?: Yes

The problem in red.
![width](https://user-images.githubusercontent.com/63966739/79692390-8bfed000-826d-11ea-9557-deca875f4f01.png)

The  good stander
![58344409-70473b80-7e0a-11e9-8570-b2efc6f8fa44](https://user-images.githubusercontent.com/63966739/79692398-9caf4600-826d-11ea-8198-d61e20be91bd.png)

How can i git red of it.

**Comment by gjsjohnmurray** [comment]
https://code.visualstudio.com/docs/editor/codebasics#_indentation

**Comment by dhjdf98dfgnj789** [comment]
@gjsjohnmurray Thank you Jone. 

I am idiot how i miss that. I did try tab size a few times. 

All the best for you.
