### ISSUE TITLE
Run => add configuration needs to not automatically install things

### ISSUE THREAD

**Issue by roncanepa** [microsoft/vscode#95645]
I'm on macOS.

I tried searching for previous mentions of this, but based on the words, there are too many unrelated results to dig through.

I was looking in the "Run" menu and saw "configurations," including "add configuration..." so I was curious and clicked on it, thinking it'd open up another prompt/window of some kind.  Especially since that's often what an ellipses means in a menu.

Instead, VS Code automatically started installing a bunch of crap I don't need or want without asking/confirming or given me an easy way to remove it.  This is NOT good behavior.  I don't even have a .net Core project open!  It's an R project.

Followup question: how do I remove this junk?

```
Installing C# dependencies...
Platform: darwin, x86_64

Downloading package 'OmniSharp for OSX' (47441 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for OSX'

Downloading package '.NET Core Debugger (macOS / x64)' (41849 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (macOS / x64)'

Downloading package 'Razor Language Server (macOS / x64)' (51065 KB).................... Done!
Installing package 'Razor Language Server (macOS / x64)'

Finished

Failed to spawn 'dotnet --info'
```

**Comment by isidorn** [comment]
Please file against the C# extension you are using. The extension is doing the installation.
