### ISSUE TITLE
"Command + V" does not paste; Takes cursor to top of the page

### ISSUE THREAD

**Issue by Genysys** [microsoft/vscode#95649]
- VSCode Version: 1.44.2
ff915844119ce9485abfe8aa9076ec76b5300ddd
x64
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:

1. Copy any text or code. ( Command + V)
2. Try to paste it in vscode ( Command + C)
3. Text not copied but cursor returned to left corner of editor.

My user bindings are empty, so not sure why this is happening.

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by rebornix** [comment]
@Genysys sorry for the late response, are you still seeing this issue on latest version?
