### ISSUE TITLE
vscode macOS c++ debug external console does nothing

### ISSUE THREAD

**Issue by hellblazer33** [microsoft/vscode#95640]
I am on vscode on mac trying to debug c++ In program where we have to input but it doesnt work as vscode launches external console(terminal) but nothing happens in the terminal.

I am using "externalConsole: true" the terminal launches but debugger doesnt work after launching terminal and nothing happens.

if "externalConsole: false" and program without input then it works perfectly.
I think its problem with latest vscode update for macos.I have windows too and there external console works perfectly while debugging.

- VSCode Version:1.44.2
- OS Version:10.15.4 MacOS Catalina

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
/causedByExtension

Please open an issue for the C++ extension: https://github.com/Microsoft/vscode-cpptools/issues.
