### ISSUE TITLE
Name with umlauts are broken in VSCode.

### ISSUE THREAD

**Issue by KhushalGupta** [microsoft/vscode#95646]
Name that contains umlauts are broken in VSCode.
Attaching a screenshot for reference.
<img width="150" alt="Screenshot 2020-03-31 at 15 09 51" src="https://user-images.githubusercontent.com/17666396/78030052-cc9bb580-7361-11ea-9979-7f58bc4504f5.png">

**Comment by eamodio** [comment]
I checked and code lens render properly with umlauts. This must be an issue with GitLens.
