### ISSUE TITLE
Unable to use recomandations

### ISSUE THREAD

**Issue by SaurabhSinghCS** [microsoft/vscode#95644]
Issue Type: <b>Feature Request</b>

When we type div in html syntex it will only write it as a text not as a tag

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.17134

**Comment by gjsjohnmurray** [comment]
Is this a .html file? What does the language mode indicate at the right-hand end of your status line?

**Comment by chrmarti** [comment]
In an empty html file try entering `d` `i` `v` and then press Tab. Does that work? If not, please attach a screenshot.
