### ISSUE TITLE
Problems panel filters are not applied to new problems

### ISSUE THREAD

**Issue by matangover** [microsoft/vscode#95641]
- VSCode Version: 1.44.2
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:
1. Open VS Code, create a new file and set its language mode to JSON.
2. Type `blah` into the editor.
3. Observe a problem is generated in the Problems panel: `Expected a JSON object, array or literal.`
4. Filter the Problems view by typing `object` in the Filter box. 
5. Type `"` into the beginning of the file, so that the editor now contains `"blah`.
6. Observe that the Problems panel **filter is not applied** to the newly generated problem. That is, the Problems view now contains `Unexpected end of string` which does not match the filter `object`.
7. Clear the filter box. Retype the filter `object`, the problem disappears.
8. Delete the `"` from the editor. Observe that the Problems view **does not show any problem**, even though it should.
9. Clear the Filter box and retype the filter `object`. The problem is now displayed.

In this simple repro, the effect is minimal, but when navigating a workspace with hundreds of files where each file has dozens of problems (and new problems are displayed whenever a file is opened or edited), this quickly becomes annoying. Many problems appear which do not match my filter, and problem which do match my filter are not displayed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@joaomoreno Tree re-render is being called when markers are changed. I also checked that tree is applying the filtering again and the filtering is done on updated model. But the tree is not getting updated.

Code pointers : 
https://github.com/microsoft/vscode/blob/711dac05db03f6055702372cd0fffd634bded665/src/vs/workbench/contrib/markers/browser/markersTreeViewer.ts#L484

**Comment by joaomoreno** [comment]
@sandy081 The tree is doing the right thing.

The calls are:

https://github.com/microsoft/vscode/blob/bffb916f12634bb53681dc8f64b1ad24a269e31f/src/vs/workbench/contrib/markers/browser/markersView.ts#L310-L311

Set children won't filter the element you're setting the children on. Rerender has nothing to do with filtering, just calls `renderElement` once again.

Maybe what we should do is call `refilter` if the filter input text is not an empty string.

**Comment by sandy081** [comment]
> Set children won't filter the element you're setting the children on.

After children are set, tree is applying the filter on them. So you mean to say that the filter result is not being considered?

**Comment by joaomoreno** [comment]
When calling `setChildren(element, subtree)`, the entire `subtree` will be refiltered... but here we're calling `setChildren` on the problem itself, as a performance measure, so only that problem's children will be refiltered.

**Comment by sandy081** [comment]
> but here we're calling `setChildren` on the problem itself

correction - we are calling `setChildren` on the resource and children are problems. So the problems shall get filtered right?

**Comment by joaomoreno** [comment]
Oh, my bad. So right! Yup, seems like a bug related to a scoped `setChildren` and `TreeVisibility.Recurse`.

**Comment by joaomoreno** [comment]
Added a test case for this: https://github.com/microsoft/vscode/commit/b0958b2b972574feeb3a06b82bfb067fc8ee8fa5

**Comment by joaomoreno** [comment]
Similar issue: 

![recording](https://user-images.githubusercontent.com/22350/81308911-a238c880-9082-11ea-90a1-c0c10b47b277.gif)

**Comment by joaomoreno** [comment]
Great issue!

**Comment by matangover** [comment]
Thanks for such a fast fix 🚀
