### ISSUE TITLE
Multiline selection in Jupiter notebook

### ISSUE THREAD

**Issue by YashKarthik** [microsoft/vscode#95651]
- VSCode Version:1.44.2
- OS Version:macOS Mojave 10.14.5

Steps to Reproduce:

1.Open any `.ipynb` file in Vscode
2.Turn on multiline selection using command palette
Multiline selection doesn't happen :(

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Python extension. Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose
