### ISSUE TITLE
extension host terminated unexpectedly

### ISSUE THREAD

**Issue by tanya4067** [microsoft/vscode#95655]
Issue Type: <b>Bug</b>

i dnt know

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.3
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
md2reader|gdr|0.8.0
chocolatey-vscode|gep|0.7.1
python|ms-|2020.3.71659
powershell|ms-|2020.4.0
vscode-zipexplorer|sle|0.3.1

</details>

**Comment by tanya4067** [comment]
What I need to do to fix this problem . It is even not working after reinstalling it . Please help me in fixing this bug.

**Comment by tanya4067** [comment]
Help me in fixing this bug. Sent from Mail for Windows 10 From: vscodebot[bot]Sent: Monday, April 20, 2020 2:10 AMTo: microsoft/vscodeCc: tanya4067; AuthorSubject: Re: [microsoft/vscode] extension host terminated unexpectedly (#95655) (Experimental duplicate detection)Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:Extension host terminated unexpectedly. (#94722) extension host terminated unexpectedly (#95458) extension terminated host unexpectedly (#94804) plugin server terminated unexpectedly (#91813) Extension host terminated unexpectedly (#95146) —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by gjsjohnmurray** [comment]
Do you use Quick Heal antivirus? If so, see #94858
