### ISSUE TITLE
Special character issue in the save file prompt message

### ISSUE THREAD

**Issue by megametres** [microsoft/vscode#95652]
Issue Type: <b>Bug</b>

Requirement:
 - An unsaved new file with special character ( ex: é ) in the first +- 80 char
Step to reproduce:
- Try to close this unsaved file
Expected:
- The special character should display correctly in the confirmation prompt
Actual:
- The special character does not display correctly in the confirmation prompt

![image](https://user-images.githubusercontent.com/2496407/79697421-c9a13000-8250-11ea-9048-601b0d8d0232.png)

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 5.3.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 4005)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|31.34GB (4.09GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|3.0.1
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.3
vscode-firefox-debug|fir|2.7.2
code-runner|for|0.9.17
beautify|Hoo|1.5.0
sqltools|mtx|0.21.7
cargo|pan|0.2.3
vscode-yaml|red|0.7.2
rust|rus|0.7.2
crates|ser|0.4.9
vscode-icons|vsc|10.1.1
debug|web|0.24.0

</details>

![character_issue](https://user-images.githubusercontent.com/2496407/79697399-9d85af00-8250-11ea-9bfb-465c9e76b9d4.jpg)

**Comment by bpasero** [comment]
I cannot reproduce on my Ubuntu 18:

![image](https://user-images.githubusercontent.com/900690/79763002-c5921280-8323-11ea-8959-581fe8fe815d.png)

So I suspect a OS/Electron issue.

**Comment by megametres** [comment]
Maybe a locale issue...?
Here are mine:
$ locale
LANG=fr_CA.UTF-8
LANGUAGE=fr
LC_CTYPE="fr_CA.UTF-8"
LC_NUMERIC="fr_CA.UTF-8"
LC_TIME="fr_CA.UTF-8"
LC_COLLATE="fr_CA.UTF-8"
LC_MONETARY="fr_CA.UTF-8"
LC_MESSAGES="fr_CA.UTF-8"
LC_PAPER="fr_CA.UTF-8"
LC_NAME="fr_CA.UTF-8"
LC_ADDRESS="fr_CA.UTF-8"
LC_TELEPHONE="fr_CA.UTF-8"
LC_MEASUREMENT="fr_CA.UTF-8"
LC_IDENTIFICATION="fr_CA.UTF-8"
LC_ALL=

**Comment by megametres** [comment]
I tought it was specified in the system info, I have ubuntu 19.10

**Comment by kenliten** [comment]
Not working the same way for me

I've trying to reproduce it in OpenSUSE Tumbleweed and got this:
![image](https://user-images.githubusercontent.com/21057320/97772017-1f686600-1b19-11eb-9637-24c564be5397.png)

This could be a platform specific issue?

**Comment by deepak1556** [comment]
Unable to repro on Ubuntu 22.04 with latest stable `1.74`
