### ISSUE TITLE
Provide a way for extension authors to specify that a preview of their extension satisfies the extension recommendation for associated file types

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/vscode#95657]
Right now the PowerShell extension provides both a stable and a preview version.  It is very important for our testing that both extensions do not get loaded at the same time. However, whenever we have folks test the preview extension, they get pestered to install the "recommended" extension for the file type via this notification:

![image](https://user-images.githubusercontent.com/5177512/79705818-3a0d7880-8274-11ea-8b32-9b3dfd3f7ea7.png)

I'm looking at this code wondering how I can get this mechanism to recognize both `ms-vscode.powershell` **and** `ms-vscode.powershell-preview` as satisfying the recommendation for PowerShell script files. Hence, eliminating this notification when someone has the preview installed.

https://github.com/microsoft/vscode/blob/2225d77536d12fea2eda04930f431a5eb0930bba/src/vs/workbench/contrib/extensions/test/electron-browser/extensionRecommendationsService.test.ts#L225-L227

Also, that file extension list is in need of work.  First, it should also list `**/*.psd1, **/*.psm1`.  Second, I don't believe `**/*.ps` is a PowerShell file.  Isn't that like a postscript file or something?  Indeed, it seems that PowerShell does not recognize .ps files:

![image](https://user-images.githubusercontent.com/5177512/79706027-041cc400-8275-11ea-9db5-daef86eec3e1.png)

So, I think I'll submit a PR to fix the extension list but it would be nice to know if there is a way to include both `ms-vscode.powershell` and `ms-vscode.powershell-preview` as recommended extensions for those file extensions.  One option is maybe to use a regex to match the extension name e.g. `ms-vscode\.powershell(-preview)?`  CC @TylerLeonhardt @rjmholt

**Comment by chrisdias** [comment]
There's no way to have more than 1 extension for an important recommendation that I know of.  That would be a separate issue from updating the files we identify to prompt for the extension.

is it just `**/*.psd1` and `**/*.psm1` or are there more?

**Comment by rkeithhill** [comment]
The primary file types that contain code are: `**/*.ps1`, `**/*.psd1` and `**/*.psm1`.  There are a few more "auxiliary" file types used by PowerShell but they are configuration files (not code) - one is XML file `*.ps1xm1` and another is a console config file `*.psc1` but I don't "think" we want to map them to the PowerShell extension since it doesn't provide any specific features for these two file types.  @TylerLeonhardt @rjmholt  Any thoughts on these last two file types?  Anything missing?

**Comment by rjmholt** [comment]
CDXML and PS1XML are definitely primarily XML files. I don't know anything about PSC1 files. I can't think of any other file extensions though.

**Comment by rkeithhill** [comment]
Turns out PSC1 is also an XML file (see Export-Console command in v5 - not brought to core).  So yeah, think the file types should be `**/*.ps1`, `**/*.psd1` and `**/*.psm1` and NOT `**/.ps`.  @chrisdias do you want to update the file extension list or would you like me to submit a PR for that?

**Comment by chrisdias** [comment]
i'll do it, no need for a pr.

**Comment by chrisdias** [comment]
recommendations have been updated.  note in insiders we recommend the preview extension, in stable we recommend the stable version.  

the original issue to be able to promote 2 extensions is still open.

**Comment by sandy081** [comment]
Currently we do not support preview extensions - Here is the request to support that - https://github.com/microsoft/vscode/issues/15756
