### ISSUE TITLE
Provide a way to get diagnostic info for an issue about an extension that's not hosted on GIthub

### ISSUE THREAD

**Issue by iliazeus** [microsoft/vscode#95669]
RIght now, there's an Issue Reporter that collects all the info, but it only works with GitHub issues. But our team develops an extension using a GitLab repository.

It would be nice to have a way to collect the diagnostic info for a GitLab issue, similarly to what the Issue Reporter does. For example, something like `env.getDiagnosticInfo(): string` in the api. Or just having the default Issue Reporter work with GitLab issues.

**Comment by gjsjohnmurray** [comment]
#73515 is related. Pinging @RMacfarlane for any news of plans of better support for extensions hosted elsewhere than GitHub.

**Comment by iliazeus** [comment]
Looks like [this](https://code.visualstudio.com/updates/v1_87#_contributing-additional-data-in-issue-reporter) recent change adds something similar? Not really clear from the docs what the `uri` parameter does.
