### ISSUE TITLE
'Notebook' commands should only show in command palette when you are in a notebook

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#95664]
Issue Type: <b>Bug</b>

**Repro**
1. Open a js file
1. In the command palette, search `Notebook`

**Bug**
A bunch of notebook specific commands are shown. Most start with `Notebook: ` but there's also `Insert code cell above` and `Insert markdown cell above`

VS Code version: Code - Insiders 1.45.0-insider (a3083e58e2a9e77f60e531acaa32e18527ae8439, 2020-04-17T08:08:39.508Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (7.92GB free)|
|Process Argv|-psn_0_14245269|
|Screen Reader|no|
|VM|14%|
</details>

**Comment by rebornix** [comment]
@jrieken currently with the new action registration, we will always populate the command in command palette if `f1` is set to `true` due to 

https://github.com/microsoft/vscode/blob/93958d98e8fad242a59a89b9e2d992c804ad142b/src/vs/platform/actions/common/actions.ts#L444-L446

To fix this, we can use `precondition` to control if one action should be populated to the command palette.

**Comment by jrieken** [comment]
Yes - `precondition` ftw. This also helps with unwanted keybindings

**Comment by rebornix** [comment]
@jrieken as discussed above, precondition will be used as menu when clause in the command palette, if the action is registered through `registerAction2`. I'm not sure if we have a debt item for `registerAction` but we may want to highlight that how `precondition` take effects.
