### ISSUE TITLE
Error renaming a folder.

### ISSUE THREAD

**Issue by shrutipant7** [microsoft/vscode#95666]
![Screenshot (18)](https://user-images.githubusercontent.com/29400237/79719878-1d695300-82fd-11ea-8fd1-99736c4dd882.png)

- VSCode Version: 1.44.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Try renaming any folder containing one or more sub folders.
2. The left-side explorer pane freezes.

Does this issue occur when all extensions are disabled?: Yes/No yes

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by mikyladewitt** [comment]
I can reproduce this on the following Insiders build:

Version: 1.45.0-insider
Commit: ec0d19789f89d4c25895f4a0cf364276cfb0c6ed
Date: 2020-04-20T06:04:22.698Z (16 hrs ago)
Electron: 7.2.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

It seems like it happens whether or not extensions are disabled. Reproduced with steps above. Alsp:

1. Ran `Extensions: Disable All Installed Extensions`
2. Attempted to rename using steps to reproduce
3. Left-side explorer dims and is unusable like in bug description

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/95315
