### ISSUE TITLE
Read-only notebooks/cells still display UI for editing/running them

### ISSUE THREAD

**Issue by lostintangent** [microsoft/vscode#95662]
I’m implementing a notebook provider for the [CodeTour](https://aka.ms/codetour) extension, in order to provide an alternative way to [view the guided tours associated with a codebase](https://github.com/vsls-contrib/codetour/blob/master/README.md#notebook-view). I noticed that even though I’m marking the document and cells as [non-runnable/editable](https://github.com/vsls-contrib/codetour/blob/master/src/notebook/index.ts#L8), much of the notebook’s editing/running UI is still displayed (e.g. the run cell command in the editor “tab”, the + markdown/code cell hover command).

Is it possible to suppress these UI elements? Or maybe I’m misunderstanding the meaning of the document/cell metadata properties? Thanks!

**Comment by rebornix** [comment]
@lostintangent you are correct that Run/Edit buttons should not be displayed when the metadata says `non-runnable/non-editable`

**Comment by lostintangent** [comment]
@rebornix OK cool, thanks for confirming that! I'm loving the new notebook experience BTW. So beautiful 😄
