### ISSUE TITLE
python notebook tabs not re-opening after session restart

### ISSUE THREAD

**Issue by noamza** [microsoft/vscode#95663]
Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134

notebook tabs are not restored when vscode is restarted. this is specific to ipynb files, regular python py file tabs re-ppen after restart. 

Steps to Reproduce:

1. open ipython notebook
2. close vscode
3. restart vscode

I am not sure how to do this, clearly the python extension is needed to render the notebook.

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Python extension. Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose

**Comment by noamza** [comment]
thank you for the response, will do
