### ISSUE TITLE
highlight problem

### ISSUE THREAD

**Issue by WLcHaok** [microsoft/vscode#95673]
Issue Type: <b>Bug</b>

doesn't matter what programming language i use the highlitter is broken.For example when i use c# and write a word it instantly turn green and can't be change

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Atom(TM) CPU D2500   @ 1.86GHz (2 x 1866)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|1.98GB (0.19GB free)|
|Process Argv|C:\Users\clone\Documents\Unsatisfied Start -g C:\Users\clone\Documents\Unsatisfied Start\Assets\CharacterController2D.cs:1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.21.17
unity-tools|Tob|1.2.3
unity-debug|Uni|2.7.5

</details>

**Comment by gjsjohnmurray** [comment]
Are you using Quick Heal antivirus? If so, see #94858

**Comment by WLcHaok** [comment]
Sorry for the late response.Also i don't think that i have Quick Heal antivirus and this what the output gave out Starting OmniSharp server at 4/22/2020, 12:26:30 PM
    Target: c:\Users\clone\Documents\Unsatisfied Start\Unsatisfied Start.sln

OmniSharp server started.
    Path: C:\Users\clone\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\OmniSharp.exe
    PID: 4416

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.1.7601.65536 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.4 - "C:\Users\clone\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'C:\Users\clone\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.4 - "C:\Users\clone\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = C:\Users\clone\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = C:\Users\clone\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild
            MSBuildToolsPath = C:\Users\clone\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\clone\Documents\Unsatisfied Start'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Users\clone\Documents\Unsatisfied Start\Unsatisfied Start.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\clone\Documents\Unsatisfied Start\Assembly-CSharp.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\clone\Documents\Unsatisfied Start'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\clone\Documents\Unsatisfied Start\Assembly-CSharp.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\clone\Documents\Unsatisfied Start' on host 3564.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\clone\Documents\Unsatisfied Start\Assembly-CSharp.csproj'.
c:\Users\clone\Documents\Unsatisfied Start\Assembly-CSharp.csproj
C:\Users\clone\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1177,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\clone\Documents\Unsatisfied Start\Assembly-CSharp.csproj

**Comment by WLcHaok** [comment]
is the quick heal antivirus necessary?

**Comment by WLcHaok** [comment]
Also I unable to disable my C# extensions because the notifications :  Cannot disable extension 'C#'. Extension 'Debugger for Unity' depends on this.

**Comment by WLcHaok** [comment]
when i disable all the extensions and reload them they disappeared so i have to find each of them and enable them all.Then it gave me a notification :Some projects have trouble loading. Please review the output for more details. Source: C# extensions

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the C# extension. Please file a new issue for it: https://github.com/OmniSharp/omnisharp-vscode/issues
