### ISSUE TITLE
ctrl+left key cannot jump

### ISSUE THREAD

**Issue by elementyang** [microsoft/vscode#95676]
Issue Type: <b>Bug</b>

When I upgraded to version 1.44.2(user setup), ctrl+left key failed, and cannot jump. Please bug fix it quickly.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.62GB (3.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
Go|ms-|0.14.1

</details>

**Comment by chrmarti** [comment]
Does `Ctrl+Right` work to word-navigate to the right?

**Comment by elementyang** [comment]
yes, ctrl+Right shows navigate. Maybe vscode don't find godef.

**Comment by alexdima** [comment]
@elementyang Can you please comment out your `keybindings.json` file and disable all your extensions?
