### ISSUE TITLE
Polish for the goto error peek

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#9567]
- VSCode Version: 1.4.0-insiders
- OS Version: Linux

Steps to Reproduce:
1. Install Markdown spelling extension
2. F8 thru a markdown file
   ![image](https://cloud.githubusercontent.com/assets/6461412/17014955/b73e9188-4f27-11e6-9ef6-8385a377f5ed.png)

![image](https://cloud.githubusercontent.com/assets/6461412/17016701/8c1f8710-4f30-11e6-95fd-2b8dece05958.png)

The mix of fonts doesn't look very good, especially that (1/3) is smaller than the error text.
I suggest to render the error text with the regular workbench font (also the problems view does that), at least when they are single line errors.

**Comment by jrieken** [comment]
No, we cannot use the regular workbench font because some error messages are multiline and use mono-space font for formatting like so

```
console.lok
              ^^^

'lok' not found
```

**Comment by jrieken** [comment]
@bgashler1 @stevencl for font suggestions wrt to the non error text.

**Comment by stevencl** [comment]
@misolori - I was going to close this but thought I would pass on to you to see if you had any quick suggestions?

**Comment by misolori** [comment]
I think adding some padding will be a good start, but i'll take a closer look

![image](https://user-images.githubusercontent.com/35271042/45392281-7cbc9880-b5db-11e8-88c6-38ebe9c204c8.png)
