### ISSUE TITLE
Don't close the instance I just opened to install an update

### ISSUE THREAD

**Issue by Stardidi** [microsoft/vscode#95674]
Issue Type: <b>Bug</b>

After opening VSCode, it starts to install/apply an update in the background and then closes the windows _I just opened_. This is incredibly frustarting, as the program is actively undoing the action I just took.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.17763

**Comment by gjsjohnmurray** [comment]
Are you saying that VSCode restarted without asking you? My experience of the automatic update is that I get a (1) badge appear on the gearwheel in the bottom left. Then when I click on the gearwheel to see its menu the usual "Check for Updates..." option has changed into one that will trigger a VSCode restart when I select it.

**Comment by Stardidi** [comment]
Yes, it indeed restarts and close the entire application without asking me. This has been happening for a longer time (several months). 

I have never interacted with the gearwheel menu, although I may have pressed 'install update' in the bottom-right toast notification during the previous start of VSCode. 
So
- Start VSCode
- Get update toast notification, click 'install updates'
- Reboot PC
- Open VSCode
- VSCode closes itself

I now suspect it may have to do with me doing a force-restart, without giving it time to finalize it's update process. This might then trigger that finalization during the next start-up, rather than in the background after close when it's normally supposed to happen

**Comment by joaomoreno** [comment]
> I now suspect it may have to do with me doing a force-restart, without giving it time to finalize it's update process. This might then trigger that finalization during the next start-up, rather than in the background after close when it's normally supposed to happen

It could be... If you wait for the update to complete... does the issue reproduce?

**Comment by Stardidi** [comment]
> > I now suspect it may have to do with me doing a force-restart, without giving it time to finalize it's update process. This might then trigger that finalization during the next start-up, rather than in the background after close when it's normally supposed to happen
> 
> It could be... If you wait for the update to complete... does the issue reproduce?

Is there any way for me to force an install of an update without there actually being a new update?

**Comment by joaomoreno** [comment]
Open `C:\Users\USER\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\product.json` and change the value of `commit` to `update`.

**Comment by Stardidi** [comment]
@joaomoreno Thanks, I was indeed able to reproduce that way:
- Change the product.json as instructed
- Open VSCode
- Close VSCode
- Quickly reopen VSCode
- VSCode closes itself

**Comment by joaomoreno** [comment]
Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`. Can you repro then?

**Comment by Stardidi** [comment]
Disabling the background updates does seem to prevent the issue. 

A few more details:
- The second instance is only killed if CodeSetup-stable-* is already started when it launches. 
- It may take ~30 seconds before the second instance is killed. 
- While trying out some more things, I finally got this pop-up:
![image](https://user-images.githubusercontent.com/636535/80505913-3dd88380-8975-11ea-912c-1064ceef70c0.png)
Which would seem like the expected behavior for an installer
