### ISSUE TITLE
Errors when opening webview

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#95678]
Sometimes, when I create a webview, the panel opens but is empty.

When I close and re-create the webview, it always ends up working after a few times.

Here are some logs I found in the developer console. I am not 100% sure they are related, but it's probable.

![Capture du 2020-04-20 11-23-30](https://user-images.githubusercontent.com/15984272/79736559-43412880-82fa-11ea-9740-d6f7f3c6f0a8.png)

My colleague works on macOS and never has the problem, so I guess this does happen on linux only.

This issue has been there for months, but I cannot reproduce reliably.

I only reproduced it within the Extension Development Host. It might happen outside, but I never try it, and since it's random (it can not happen for a few days) I cannot say if it happens outside Extension Development Host.

Do you know about those issues?

---

> Version: 1.45.0-insider
Commit: a3083e58e2a9e77f60e531acaa32e18527ae8439
Date: 2020-04-17T08:09:45.292Z (3 days ago)
Electron: 7.2.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-91-generic

Does this issue occur when all extensions are disabled?: don't know (need extension to create webview panel)

Full text logs
```
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1608   ERR connect ECONNREFUSED /run/user/1001/vscode-fdc6cfa3-1.45.0-insider-shared.sock: Error: connect ECONNREFUSED /run/user/1001/vscode-fdc6cfa3-1.45.0-insider-shared.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1608   ERR connect ECONNREFUSED /run/user/1001/vscode-fdc6cfa3-1.45.0-insider-shared.sock: Unknown (UserDataSyncError) undefined: connect ECONNREFUSED /run/user/1001/vscode-fdc6cfa3-1.45.0-insider-shared.sock
    at Function.toUserDataSyncError (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2674:678)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5437:605
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1608   ERR connect ECONNREFUSED /run/user/1001/vscode-fdc6cfa3-1.45.0-insider-shared.sock: Error: connect ECONNREFUSED /run/user/1001/vscode-fdc6cfa3-1.45.0-insider-shared.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4228 [Extension Host] STOPPED on first line for debugging on port 12104
_tryFindDebugPort @ /usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4228


/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1608   ERR connect ECONNREFUSED /run/user/1001/vscode-fdc6cfa3-1.45.0-insider-shared.sock: Error: connect ECONNREFUSED /run/user/1001/vscode-fdc6cfa3-1.45.0-insider-shared.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1608   ERR Error: connect ECONNREFUSED /run/user/1001/vscode-fdc6cfa3-1.45.0-insider-shared.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (/usr/share/code-insiders/resources/app/out/vs/code/electron-browser/workbench/net.js:1056)
t.log @ /usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:258

```

**Comment by mjbvz** [comment]
Are you sure those errors only happen when you start a webview? What if you try other extension functionality, such as intellisense?

Also, that error about `.sock` can often be fixed by fully quitting and restarting VS Code. Have you tried doing that?

**Comment by sguillia** [comment]
> Are you sure those errors only happen when you start a webview?
It is likely but I'm not sure. I happens when I start a webview and it doesn't load. I don't always have the dev tools open.

> What if you try other extension functionality, such as intellisense?
The only symptom is the webview not opening. I haven't noticed any other malfunction with intellisense.

> Also, that error about .sock can often be fixed by fully quitting and restarting VS Code. Have you tried doing that?
When I have the webview problem, re-opening a few times fixes the problem. I have no need to restart VS Code since there are no other problems. If I do, chances are it will do the same as re-opening the webview: it will work again

I'll update if I have more info

**Comment by mjbvz** [comment]
Any updates on this issue? I haven't seen any other reports of it
