### ISSUE TITLE
Extension Feature Contributions doesn't render markdownDescription

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#95671]
Issue Type: <b>Bug</b>

```js
"errorLens.padding": {
	"type": "string",
	"default": "",
	"markdownDescription": "Adds padding for the message. Visible difference when `message` colors are set. [Issue #23](https://github.com/usernamehw/vscode-error-lens/issues/23). Example: `2px 1ch`.",
	"examples": [
		"2px 1ch"
	]
},
```

![Screenshot (185)](https://user-images.githubusercontent.com/9638156/79727148-93b58780-82f4-11ea-89af-3fbf581c8901.png)

VS Code version: Code - Insiders 1.45.0-insider (ec0d19789f89d4c25895f4a0cf364276cfb0c6ed, 2020-04-20T06:08:30.812Z)
OS version: Windows_NT x64 6.2.9200

**Comment by jeanp413** [comment]
I'll take this up
