### ISSUE TITLE
Git not working with new update

### ISSUE THREAD

**Issue by anilarusys** [microsoft/vscode#95684]
Issue Type: <b>Bug</b>

When code updated it start display error "Restart Extension Host" and no git changes or difffrence display on project area.

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.3
vscode-pull-request-github|Git|0.15.0
githd|hui|2.2.4
vscode-github|Kni|0.30.3
git-tree-compare|let|1.9.1
java|red|0.60.0
vscode-java-pack|vsc|0.9.0
vscode-maven|vsc|0.21.2

</details>

**Comment by gjsjohnmurray** [comment]
Are you using Quick Heal antivirus? If so, see #94858

**Comment by consal** [comment]
I have exactly the same issue after the new update

**Comment by consal** [comment]
I can't provide more feedback as I immediatelly rolled back to 1.43, sorry :(

**Comment by chrmarti** [comment]
Closing as we don't get additional information.
