### ISSUE TITLE
Backport fix for VoiceOver Can't Find Web Content If you Stop Interact 

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#95689]
Just creating this issue so we have something to track this work 

As already discussed with @deepak1556 we should backport fix for https://github.com/electron/electron/issues/17207 in our electron build

**Comment by deepak1556** [comment]
Thanks @isidorn

**Comment by deepak1556** [comment]
Sorry I forgot to update here, the electron backport landed in `7.2.4` and went out with the stable release `1.45` today.

**Comment by isidorn** [comment]
Awesome, thanks!
