### ISSUE TITLE
git changes lags in editor

### ISSUE THREAD

**Issue by Iipal** [microsoft/vscode#95688]
SCM shows 0 changes but in the editor, I still see bugged git changes. It lags appear from version +-1.42

- VSCode Version: 1.44.2
- OS Version: Windows 10 x64 + WSL Ubuntu 16.04
- No plugins for work with git installed

Steps to Reproduce:
1. Stage a few changes and add commits from SCM
2. Add tags from the terminal and run: `git push origin --all && git push origin --tags`
3. open SCM: 0 changes but in editor still see bugged changes

Forgot to take a screenshot, if it appears again I'll add it later

**Comment by joaomoreno** [comment]
You seem to be missing file events. Please go through the following steps:

1. Run `Git: Set Log Level...` and choose `Trace`
2. Run `Git: Show Git Output`
3. Reproduce the issue and wait 10-20 seconds
4. Paste the whole output here

**Comment by Iipal** [comment]
@joaomoreno 
[git.log](https://github.com/microsoft/vscode/files/4506408/git.log)

**Comment by cveld** [comment]
I am wondering if vscode is considering building a git service instead of invoking the git cli? Or, if git cli is considering to build a performant "server" edition, like the dotnet cli?
Additionally, I noticed that the performance of the vscode git scm integration is much slower than the regular commandline interaction. Ideally vscode should be on par or even surpass the commandline performance.

**Comment by joaomoreno** [comment]
@lipal File events seem to work fine here. How often does this reproduce for you?

@cveld As I mentioned to you in private, please just file an issue with your specific situation. Commenting on other issues is counterproductive.

**Comment by Iipal** [comment]
@joaomoreno random, sometimes it appears just once a month, sometimes every day, but anyway it frequently appears from time to time

**Comment by Iipal** [comment]
@joaomoreno 
![image](https://user-images.githubusercontent.com/31858171/80288059-ffa54f00-873d-11ea-8ab4-2f68b56930d1.png)

**Comment by joaomoreno** [comment]
In that case, running `git status` would return the changes? Or was the editor simply out of date?

**Comment by Iipal** [comment]
@joaomoreno The editor is out of date. `git status` returned nothing.

**Comment by joaomoreno** [comment]
This is strange, since I can't reproduce at all. Are the files stored in the WSL side or in Windows?

**Comment by Iipal** [comment]
@joaomoreno WSL only

**Comment by joaomoreno** [comment]
@lipal Developing VS Code using WSL is what I do most of the time.

If you could find steps which would reproduce this on your machine 100% of the time, that would be great.
