### ISSUE TITLE
Javascript Highlighting broken // showing errors where there are none

### ISSUE THREAD

**Issue by lukboegit** [microsoft/vscode#95685]
- VSCode Version: 1.44.2 and insiders build
- OS Version: MacOS 10.15.4

Steps to Reproduce:

Highlighting just started to be broken out of the blue in Javascript. I am just learning, so I was fooling with HTML/CSS/JS when VS Code was showing faux errors and weird behaviors in highlighting. The error messages would not show when i closed and reopened the file or when i was opening the same file in sublime text.

<img width="1031" alt="Screenshot 2020-04-20 at 13 02 47" src="https://user-images.githubusercontent.com/56566099/79744770-3f67d300-8307-11ea-93b2-551870f7f0f3.png">

<img width="956" alt="Screenshot 2020-04-20 at 11 58 22" src="https://user-images.githubusercontent.com/56566099/79741820-2ad50c00-8302-11ea-91a7-1c926caaf4b1.png">
<img width="595" alt="Screenshot 2020-04-20 at 11 59 18" src="https://user-images.githubusercontent.com/56566099/79741822-2c9ecf80-8302-11ea-8704-a2b72b1368e8.png">

I am happy to provide any additional Information, but as I am fairly new it would be great if you could tell me what you need or where to find it...

Thank you in advance!

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by lukboegit** [comment]
> var Input;
var lastInput;
var position =0;
var ftext = [ "Und", "dann", "eines"];
var opacityTitle=1;


document.addEventListener("keydown", function(event) {
 if (event.which >= 32 && event.which <= 122 && event.which != lastInput) {
    lastInput = event.which;
     advance();
 }
else if (event.which == 8) {
    lastInput = event.which;
    strikeOut();
}
});

document.addEventListener("keydown", function(event) {
    document.getElementById("fade").style.opacity = opacityTitle;
    opacityTitle -= 0.06;
   });

function advance(){
    document.getElementById("butt").innerHTML += "<p id=\"" + position + "\" class=\"word\">" + ftext[position] + "</p>";
   
    var nextWord = document.createElement("P");
    var textnode = document.createTextNode(ftext[position]);
    nextWord.appendChild(textnode);
    nextWord.classList.add("word");
    document.getElementById("butt").appendChild(nextWord);
    position++;
    var foo=3;
    var bar=4;

}

function strikeOut(){
    document.getElementById("butt").innerHTML = lastInput;

}


<img width="989" alt="Screenshot 2020-04-20 at 20 31 57" src="https://user-images.githubusercontent.com/56566099/79786674-20d4fc80-8346-11ea-9d6f-dbeebb2a59ec.png">
<img width="1051" alt="Screenshot 2020-04-20 at 20 32 31" src="https://user-images.githubusercontent.com/56566099/79786689-2894a100-8346-11ea-9928-c67754784c49.png">

I have not changed anything between the first and the second screenshot besides closing and reopening the file. 
Also the wrong syntax highlighting (see line 31) is changing when I type. Or it is correct when I open the file, then I cut some lines and insert them right back in and the highlighting is completely different.

**Comment by mjbvz** [comment]
Thanks.

The line `var ftext = [ "Und", "dann", "eines"];` include an invisible character: http://www.fileformat.info/info/unicode/char/2029/index.htm

This causes both the highlighting and error detection to have issues. 

@alexdima Adding you to see if we want to render this character (it also does not show up with `editor.renderControlCharacters` enabled)

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/38078 for the TS issue

**Comment by alexdima** [comment]
@mjbvz The PS (U+2029) character is rendered on Windows in Edge and in VSCode. Is this perhaps a mac specific rendering issue?
![image](https://user-images.githubusercontent.com/5047891/80285380-c8767400-8724-11ea-92de-25012d3dbf32.png)
![image](https://user-images.githubusercontent.com/5047891/80285391-dc21da80-8724-11ea-8aee-7cb885022ef7.png)

**Comment by mjbvz** [comment]
Thank you for the investigation @alexdima 

Yes the the rendering bug is Mac specific. The paragraph separator is rendered for me on windows but not on MacOS

**Comment by alexdima** [comment]
This is now a lot better because the following shows up when opening a file or pasting this code (due to #96142):

![image](https://user-images.githubusercontent.com/5047891/81694717-f6b4bd00-9461-11ea-905c-2a48853dc9d8.png)

**Comment by alexdima** [comment]
To verify, open a file with the PS character and click "Ignore problem for this file":

You can grap a PS character from here:

```
var ftext = [ "Und", "dann", "eines"];
```
