### ISSUE TITLE
Scrollbar on tabs hides behind the active tab

### ISSUE THREAD

**Issue by DannyJJK** [Microsoft/vscode#9568]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:31:10.994Z)
- OS Version: Darwin x64 16.0.0

Steps to Reproduce:

1. Open enough tabs to allow scrollbar

![screen shot 2016-07-21 at 09 30 56](https://cloud.githubusercontent.com/assets/11057501/17016220/fc986120-4f25-11e6-9f45-54fcf4f7277c.png)

This could be the intended design (to make the active tab stand out more), but it seems kind of odd to me. In other applications, the scrollbar is usually displayed over any content that's there

**Comment by stevencl** [comment]
On Windows I see the scrollbar displayed like so:

![image](https://cloud.githubusercontent.com/assets/1704059/17144163/c489d59e-534d-11e6-98a7-4e6fbfa57cd1.png)

Perhaps this is a bug on Mac? (I don't have a Mac easily at hand to try)

**Comment by stevencl** [comment]
Looks like this is fixed on the insiders build. I see it fixed in the insiders build on Windows and Mac.

**Comment by bpasero** [comment]
Yeah, fixed for 1.4 👍
