### ISSUE TITLE
Relative and absolute path of the same file open from SCM(Git) compare

### ISSUE THREAD

**Issue by marckassay** [microsoft/vscode#95690]
- VSCode Version: 1.44.2
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Click on 'Explorer' and open any file 
2. Modify file and save
3. Click on 'Source Control' and open modified file
4. Click on the 'Open File' icon in the SCM changes list

Does this issue occur when all extensions are disabled?: Yes

After all steps are completed and if the issue has been replicated, there should be 3 tabs open:
- Relative path to file (from steps 1 and 2)
- Working Tree tab. Its using Absolute path. (from step 3)
- Absolute path to file (from step 4)

The issue is that there is a relative and absolute path of the same file opened. I believe VS Code should regain focus on the relative path tab after step 4 .

**Comment by marckassay** [comment]
And today, with no known changes to my system that would effect this issue, I'm not able to replicate the issue.

**Comment by joaomoreno** [comment]
Great to know, closing this.
