### ISSUE TITLE
Can not open the app

### ISSUE THREAD

**Issue by towry** [Microsoft/vscode#9569]
- VSCode Version: 1.3.1
- OS Version: OS X 10.11.5

Steps to Reproduce:

1.  Download the zip file from `code.visualstudio.com`, then unzip it.
2.  Click the `Visual Studio Code.app`, it shows up in the dock, after 3 seconds, it exit.

I had installed the app before.

**Comment by kieferrm** [comment]
@towry Do you have any additional information such as crash logs? You can open the `Console` tool on your Mac and scan the User Diagnostic Reports section for crash files. Search them for `Visual Studio Code`. 

Also do you see the same when you download the zip again?

**Comment by towry** [comment]
@kieferrm Problem solved. The solution is remove the folder `rm -rf Library/Application\ Support/Code`.
