### ISSUE TITLE
Restrict find (Ctrl+F) to current selection automatically

### ISSUE THREAD

**Issue by kaba2** [microsoft/vscode#95692]
When the Find dialog is not open, and I press Ctrl+F, I expect "Find in selection" to be active if and only if I have an active selection in the editor. This is how it works e.g. in Visual Studio (edit: except for single lines). Currently, the "Find in selection" is always disabled. The natural flow to me when searching in a selection is to first select, and then press Ctrl+F to open Find dialog.

**Comment by kaba2** [comment]
I found out there is a setting "Auto Find In Selection" where you can select "never", "always", and "multiline". Out of these, "multiline" is almost what I am describing. However, it does not work when the selection only spans a single line (the same happens in Visual Studio).

**Comment by IllusionMH** [comment]
IIRC by default single line selection will be used as search value and if you have search in selection for single line enabled you will search for same value as in selection which won't pruduce results you want.

**Comment by kaba2** [comment]
That sounds reasonable. However, there are two types "lines"; I wasn't clear. The first type of line is everything between two end-of-lines characters, call it a logical line. The second type of line is when a long logical line word-wraps into multiple editor lines. Such long logical lines are natural when writing, say, papers in Latex; I use a single logical line to correspond to a single paragraph. So now when I select multiple editor lines of that single logical line, I'd expect "multiline" to enable "Find in Selection" in Find. But this does not happen, perhaps because it works in terms of logical lines.

**Comment by Lohoris** [comment]
Related: https://github.com/Microsoft/vscode/issues/8787
