### ISSUE TITLE
Peek of a change hides its beginning

### ISSUE THREAD

**Issue by Melebius** [microsoft/vscode#95691]
When I use *Go > Next/Previous change* from the main menu, the peek view is shown over the editor. The change in question is shown above the peek window and if it’s a bit longer, its beginning is hidden. I usually want to see (and sometimes also edit) the beginning of the change. When I try editing directly in the peek view (which usually shows the beginning I am looking for), it says “Cannot edit in read-only editor”.

![](https://user-images.githubusercontent.com/8669864/79754514-f8cea480-8317-11ea-9bac-529c109a4f84.PNG)
Note: Just one line is hidden in the screenshot but I hope you get the idea…

### Expected behavior
Either of the following:
- The beginning of the found change should be shown when using *Go > Next/Previous change*.
- The peek view should be editable.

### Enabled extensions
Extension | Author (truncated) | Version
-- | -- | --
svn-scm | joh | 2.10.6

### My system information
CPUs | Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2294)
-- | --
GPU Status | 2d_canvas: enabled flash_3d: enabled flash_stage3d: enabled flash_stage3d_baseline: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: disabled_off protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled viz_display_compositor: enabled_on viz_hit_test_surface_layer: disabled_off_ok webgl: enabled webgl2: enabled
Load (avg) | undefined
Memory (System) | 7.89GB (0.70GB free)
Process Argv |  
Screen Reader | no
VM | 0%

### VS Code version
Version: 1.45.0-insider (system setup)
Commit: ec0d19789f89d4c25895f4a0cf364276cfb0c6ed
Date: 2020-04-20T06:08:30.812Z
Electron: 7.2.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.1.7601

Note: I’m reporting this on Windows with SVN (using an extension) but I’ve also experienced the problem on macOS using the built-in Git support.

**Comment by joaomoreno** [comment]
Why not making the editor editable?
