### ISSUE TITLE
Setting request: Don't collapse explorer node on single click (unless on twistie)

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95697]
I've found it pretty annoying for a while how if I want to search on a particular folder in the explorer, I need to click it (which collapses it), then click it again (to re-expand) and then hit alt+shift+f. This happens other times too, when I collapse folders I typically do it with the left arrow.

I couldn't see a request for this but I think I'd prefer the following behavior:

- Single click does not change expand/collapse state, unless the twistie is hit
![image](https://user-images.githubusercontent.com/2193314/79761327-20048200-82d6-11ea-8824-9f60f3f36b4d.png)
- The twistie has a hover effect
- Clicking on a _focused_ explorer folder would collapse it

This could potentially be a good default as well as you can do more with it, it just needs a little more precision to collapse a folder in a single click.

I like the current single click to expand behavior as expanding a folder is what I want to do almost all the time when I click a folder.

**Comment by Tyriar** [comment]
Another idea is to make the whole left activate the twistie which would probably make it even easier to collapse:

![image](https://user-images.githubusercontent.com/2193314/79761876-df593880-82d6-11ea-8aa5-3d24c73778ae.png)

**Comment by isidorn** [comment]
@Tyriar Why not just right click on the folder > context menu > Find in Folder? That is what I do.

I would not change this only for the explorer as all Tree should behave the same in our Workbench and be consistent. Thus also assigning @joaomoreno

**Comment by misolori** [comment]
> I like the current single click to expand behavior as expanding a folder is what I want to do almost all the time when I click a folder.

I'm confused by this, given the issue is about doing the opposite. I'm also of the mind that if you're searching for something why not use the Search viewlet w/ find in folder?

**Comment by Tyriar** [comment]
> Why not just right click on the folder > context menu > Find in Folder? That is what I do.

To avoid using my mouse, it's faster to hit alt+shift+f and start typing then to locate and click find in folder.

> I'm confused by this, given the issue is about doing the opposite.

Typically when I click expanded folders I'm working on them and do not want them collapsed.
Typically when I click collapsed folders I'm about to start working on them so I want them expanded.

---

I almost have a workaround for my problem by right clicking and then left clicking the item to keep it expanded, however that ends up multi-selecting for some reason. (no ctrl held for gif)

![2b5d124e-7b12-4274-9ba4-7fec9adb7753](https://user-images.githubusercontent.com/2193314/79785095-286db480-82f8-11ea-9f9c-37860b95fa68.gif)

**Comment by joaomoreno** [comment]
Since the tree already has this option, this is up to the explorer to adopt. Let me know if you need anything else @isidorn

**Comment by isidorn** [comment]
Yeah, tree already has this option true.
Though I would not change the default explorer bheavior since users are used to this and to not break muscle memory. A setting might make sense and might add it in the future.

**Comment by gjsjohnmurray** [comment]
@Tyriar does `"workbench.list.openMode": "doubleClick"` give you what you want? I don't know if it'll have other consequences though.

**Comment by Tyriar** [comment]
@gjsjohnmurray nice, it's exactly what I want (in the explorer at least) with the exception of hover feedback on the twistie. fyi @joaomoreno

**Comment by Tyriar** [comment]
Actually the setting makes double clicking needed to activate a file as well.

**Comment by gjsjohnmurray** [comment]
> 
> 
> Actually the setting makes double clicking needed to activate a file as well.

@Tyriar it doesn't seem to have that side-effect for me when I first make the change to my setting. A single click on a file in the tree still opens it. But after I restart VSCode a single click on a file no longer opens it, and I have to use a double click. Seems like the change gets immediately detected by the folder click logic, but the file click logic only catches up with the change after a restart.

Regardless of that minor bug, clearly this setting isn't going to meet your need.

Version: 1.45.0-insider (user setup)
Commit: d342048538c28d54afd1c6beea03f3a89af04359
Date: 2020-04-23T05:57:41.076Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by misolori** [comment]
> Actually the setting makes double clicking needed to activate a file as well.

There's an issue for that now https://github.com/microsoft/vscode/issues/95948

**Comment by joaomoreno** [comment]
@Tyriar Given https://github.com/microsoft/vscode/issues/95948, does this issue still need to exist?

**Comment by Tyriar** [comment]
It doesn't cover what I'm after exactly, which is:

- Double click is needed to collapse folders, twisty is still a single click though
- Single click for opening files

I can close this off though, I might reopen a new one when I can think of a better proposal for a setting.

**Comment by joaomoreno** [comment]
We currently have `workbench.list.openMode`. We could simply introduce `workbench.tree.folderOpenMode` to cover your case.

**Comment by Tyriar** [comment]
@joaomoreno or `openMode: 'doubleClick' | 'singleClick' | 'doubleClickFolder'`?

**Comment by joaomoreno** [comment]
Added `workbench.tree.expandOnFolderClick` to control whether clicking the folder name expands/collapses the node. When set to false:

- Clicking the twistie will always toggle collapse state
- Single clicking the folder name will do nothing if collapsed and collapse if expanded
- Double clicking the folder name will expand if collapsed

**Comment by bpasero** [comment]
@joaomoreno tried to verify this but isn't the issue title this: "Don't collapse explorer node on single click (unless on twistie)" but the setting only works when expanding and not collapsing? I find this works a bit weird, I think I would have expected 1 setting to control wether folder click expands or collapses and not make this specific to expand.

**Comment by joaomoreno** [comment]
The title doesn't match the feature description.

But yeah I am also not a big fan on distinct behavior based on the node's state. I'll just make it expand/collapse on double click on the name and not make it dependent on the node's state.

**Comment by joaomoreno** [comment]
@bpasero Can you verify out of sources?

**Comment by bpasero** [comment]
The behaviour works as I would expect now. The settings name, not sure. Not every tree is about "folders" and this now also impacts collapsing. Maybe make this similar to the existing `workbench.list.openMode` and call it `workbench.list.expandMode` with options `singleClick` and `doubleClick`? I would say that it is quite obvious that a single click on the twistie expands/collapses.
