### ISSUE TITLE
Random highlighting of source code

### ISSUE THREAD

**Issue by emceearjun** [microsoft/vscode#95699]
Issue Type: <b>Bug</b>

The source code in my VSCode editor gets randomly highlighted with red.
I have not been able to figure out what the trigger is or whether this is intentional and means something. It is pretty distracting and creates a lot of confusion while browsing code.
I first noticed this only a couple of releases ago.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|32.00GB (15.91GB free)|
|Process Argv|C:\ws\gateway-web-apps|

|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.14.1
better-toml|bun|0.3.2
FreeMarker|dco|0.0.9
vscode-generate-getter-setter|DSK|0.5.0
prettier-vscode|esb|4.4.0
vs-code-xml-format|fab|0.1.5
testcafe-snippets|hdo|1.64.0
vscode-docker|ms-|1.0.0
python|ms-|2020.3.71659
vscode-jest|Ort|3.1.1
java|red|0.60.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
testcafe-test-runner|rom|2.0.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2
quokka-vscode|Wal|1.0.287

</details>

Attached screenshot here:

![vscode_highlighting_issue](https://user-images.githubusercontent.com/9413392/79762008-cafd5600-833f-11ea-9729-66669292f47a.PNG)

**Comment by chrmarti** [comment]
/needsMoreInfo

Does this occur with all extensions disabled? (`F1` > `Developer: Reload With Extensions Disabled` or `code --disable-extensions`)
