### ISSUE TITLE
Intellisense for nodejs required packages.

### ISSUE THREAD

**Issue by abhilashsajeev** [Microsoft/vscode#957]
```
var express = require('express');

var app = express();

var port = process.env.PORT || 3000;

app.listen(port);
```

In the following code I required express but when I enter app and press crtl + space  it shows no suggestions. 

It would be nice to have code assist for installed packages because nodejs developers always play with packages.

**Comment by SamVerschueren** [comment]
@jrieken Is this possible to implement without something like a (typescript) definition file?

**Comment by jrieken** [comment]
very hard. behind the scenes we just the typescript compiler to drive JS. There is a branch in TS that adds deep understanding of commonjs modules. Once we have adopted that we will be better off.

**Comment by SamVerschueren** [comment]
Good to know :).

**Comment by abhilashsajeev** [comment]
As vscode is marketed as a nodejs IDE I think it is very important to add this support. This will make Webstorm has this kind of support but its too heavy.

**Comment by SamVerschueren** [comment]
I never saw VS Code marketed as an IDE to be honest, but maybe I just missed that :). In my opinion, VS Code is an enhanced text editor, just like Atom or Sublime Text. If you want an IDE, go for Visual Studio ;).

Apart from that, it would be very nice to have this. I was only asking @jrieken if it was possible as I was interested in the technology behind it and to how it can be accomplished.

**Comment by abhilashsajeev** [comment]
![vs](https://cloud.githubusercontent.com/assets/8110867/11564149/ada6b176-99fd-11e5-82e3-74fec6ae0781.png)
 That is in the home page.

**Comment by jrieken** [comment]
In full agreement - VS Code should have the best JS support you can get, like the same is true for TS, C#, go you name it.

As of today our JS support is a little rusty, incomplete, and buggy. The TS team works on better support for plain JS and once they are ready we will jump on it.

@SamVerschueren The details are crazy ;-) We take JS code, create a copy with TS-constructs on the fly, pass that to the TS compiler, and map the results back to original JS code. [This](https://github.com/Microsoft/vscode/blob/master/src/vs/languages/typescript/common/js/requireRewriter.ts) guy for instance takes `require('foo').toString()` and generates something like `import * as $$foo;\n$$foo.toString()` to make TS types flow better.

**Comment by abhilashsajeev** [comment]
@jrieken : So the support for this feature will take some time to implement.

**Comment by SamVerschueren** [comment]
@jrieken So type definitions won't be necessary anymore in the future as they can be generated on the fly?

**Comment by jrieken** [comment]
depends... Even if tsc understands this

```
module.exports.foo = function(a, b, c) {
   return a * b;
}
```

to be a module that exports a member `foo` of type function you will need to help it out the types of the parameters. They cannot be inferred by TS. That's why there are `d.ts`-files

**Comment by jrieken** [comment]
@abhilashsajeev The TS team is working on this since a while and close to finish

**Comment by jrieken** [comment]
All details in here: https://github.com/Microsoft/TypeScript/issues/4789

**Comment by abhilashsajeev** [comment]
@jrieken :+1:  Thats great! as long as this comes out I would completly switch my node.js devs to vs code.

**Comment by sarbbottam** [comment]
Is there any update on this, https://github.com/Microsoft/TypeScript/issues/4789 has been fixed.

**Comment by egamma** [comment]
@sarbbottam yes, Code is now using Salsa. Currently Salsa still requires that you install .d.ts files.

@abhilashsajeev Once you do `tsd install express node` then you get nice Intellisense:

![image](https://cloud.githubusercontent.com/assets/172399/13596087/6eb5374a-e510-11e5-97f6-fe3ff418f4f7.png)

**Comment by sarbbottam** [comment]
Thanks @egamma. Is there no way to get intellisense with out `tsd` files?

**Comment by SamVerschueren** [comment]
// Offtopic
[tsd](https://github.com/DefinitelyTyped/tsd) is deprecated in favor of [typings](https://github.com/typings/typings).

**Comment by egamma** [comment]
@SamVerschueren correct, and we have already updated our docs.

**Comment by SamVerschueren** [comment]
@egamma nice :+1:

**Comment by egamma** [comment]
@sarbbottam 
>Thanks @egamma. Is there no way to get intellisense with out tsd files?

Pls see https://code.visualstudio.com/Updates#_languages-javascript for scenarios where you do not need `.d.ts` files, but the type information that isn't in JS has to come from somewhere, e.g. JSDoc comments.

**Comment by NickGrease** [comment]
Can someone please tell me if [this](http://stackoverflow.com/questions/36413868/vs-code-intellisense-for-node-type-require) is supposed to work? I've spent the entire day reading just about everything I can - which was a mistake, because I'm pretty sure no one on the planet has the same answer - yes,no,with d.ts,without d.ts, typings, dst, .jsconfig, .tsconfig, user settings, etc - not one straight answer.

Sorry.

**Comment by SamVerschueren** [comment]
Yes that works, but it seems that `module.exports.generateCanvas` should be `exports.generateCanvas`. This seems to be a bug because they are equivalent. If you add internal documentation, that documentation is also attached to the intellisense.

![intellisense](https://cloud.githubusercontent.com/assets/1913805/14273412/d25b8f3c-fb0a-11e5-8082-d411b857b7d5.gif)

Some notes to take into account.
- This is only the case for VS Code 0.10.11 (fixed in the insiders build and in the next release). When you require `file1.js` in a new file, it does not provide intellisense right away, it has to reload the project first by closing and reopening the project.
- `module.exports` does not work for intellisense. Will create an issue for that.

**Comment by SamVerschueren** [comment]
Issue created https://github.com/Microsoft/vscode/issues/4943

**Comment by NickGrease** [comment]
@SamVerschueren  I was a bit frustrated previously, so thank you for your time. I am using the Insider edition, and the code you wrote does indeed work. At some point yesterday in my attempt to fix my issue, I had downloaded typings, and installed several (node,browserify) d.ts files to my original project, and the fix you proposed above didn't work until I deleted the typings folder in my project. However, I couldn't duplicate that behavior in a new project. I'm happy just to get intellisense working again, so thanks for helping me out.

**Comment by jrieken** [comment]
Closing this as we have moved to project Salsa. Let's discuss new issues separately.

**Comment by shakvaal** [comment]
@jrieken Could you please provide a link?

**Comment by jrieken** [comment]
Salsa is part of TypeScript (basically the `allowJs` flag): https://github.com/Microsoft/TypeScript
