### ISSUE TITLE
Formatting files on two successive saving (formatOnSecondSave)

### ISSUE THREAD

**Issue by BlackWild** [microsoft/vscode#95706]
I think it would be a great developer experience if it was possible to format a file when pressing `crtl+s` or `cmd+s` twice, more technically, when using the keyboard shortcut of saving on an unchanged file.

Using `cmd+s` for the second time is a more convenient and quick way than using another shortcut for formatting files (on Windows: `Shift+Alt+F`).

I suggest adding an option that hitting
- `ctrl+s` on a changed file just saves the file
- `ctrl+s` on an unchanged file formats and then saves the file

Currently, the closest I can get to this feature is by changing my settings to this:
```json
"editor.formatOnSave": true,
"files.autoSave": "afterDelay"
```
which (almost) keeps the files saved, and then I use `ctrl+s` to format the document; But, the problem is that it bombards me with warnings and compiler errors when I am writing a section of code due to the incomplete format of that section during writing. Also, I am not a fan of keeping a file saved like that and would like to save a file when a meaningful section of code is completely added or changed.

**Comment by jrieken** [comment]
> when using the keyboard shortcut of saving on an unchanged file.

That's already how it works. When saving a file that has no changes (has just been saved) we still invoke save participants, like format-on-save, and when those participants have changes we save them or stop.

**Comment by jrieken** [comment]
Adding @bpasero for more background on explict-save and save-after-delay but I believe nothing is missing here

**Comment by BlackWild** [comment]
> That's already how it works. When saving a file that has no changes (has just been saved) we still invoke save participants, like format-on-save, and when those participants have changes we save them or stop.

It's true, and I currently use this functionality in the workaround I explained.

But what I am looking for is to be able to manually save a file without formatting, as well as formatting and saving an already saved file more conveniently. This is possible now by saving a file (`ctrl+s`) and then formatting the file (`shift+alt+f`) followed by another saving. However, since hitting `ctrl+s` on an already saved file has no use, I think we can use this second hit to also format the document; It's just a quicker way of managing both saving and formatting.

Consider this case for example; when I want to add a new code section like a for loop in the middle of a file, I temporarily add several new lines to make some space for the loop. But if `formatOnSave` is enabled, the formatter will remove this extra space on every manual saving., which is not what I want when I am working on the loop. In order to fix this, I need to add `"files.autoSave": "afterDelay"` setting which frequently saves the progress and does not trigger formatting. But I don't think constantly and automatically saving the file is the best solution here.

I suggest adding an option that hitting
- `ctrl+s` on a changed file just saves the file
- `ctrl+s` on an unchanged file formats and then saves the file

In the example, this option ables me to both save the progress without dealing with formatting, and format and save the file conveniently when it is done. (by hitting `ctrl+s` twice)
