### ISSUE TITLE
Capital letters in workspace path cause search results duplicated under Other Files

### ISSUE THREAD

**Issue by bluemonkmn** [microsoft/vscode#95700]
Issue Type: <b>Bug</b>

1. Create a Visual Studio Code Workspace file.
2. Enter or change one of the letters in the path in the workspace file's "folders" section to be a capital letter (using a text editor).
3. Open the workspace in VS Code
4. Open a file from within the workspace folder
5. Perform a global search (Ctrl-Shift-F) for some text in the file

Expected Result:
The result should appear once for the opened file in the workspace-relative path

Observed result:
The result appears twice, once in the workspace-relative path, and once under "Other Files" with the fully qualified path in lowercase.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (12.25GB free)|
|Process Argv|C:\landmark\ben1\Shortcuts\ben1.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.5.1
accurev|blu|0.1.0
lpl-outline|blu|0.1.5
indentation-level-movement|kai|1.3.0
lpl-language-debugger|Bel|0.1.1
lpl-language-server|Bel|1.6.2
rainbow-csv|mec|1.7.0
csharp|ms-|1.21.17
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-yaml|red|0.7.2
vscodeintellicode|Vis|1.2.6

</details>

**Comment by roblourens** [comment]
This is https://github.com/microsoft/vscode/issues/12448
