### ISSUE TITLE
No support for baseUrl feature in TypeScript 2.0?

### ISSUE THREAD

**Issue by rolandoldengarm** [Microsoft/vscode#9570]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. I have installed TypeScript 2.0. 
2. I am trying to use the new baseUrl feature.
3. I get runtime errors in Code, but it compiles fine when using tsc -p ./ from the command line.

Doesn't Code support this new feature?

**Comment by rolandoldengarm** [comment]
[ts2.0 base url test.zip](https://github.com/Microsoft/vscode/files/376968/ts2.0.base.url.test.zip)
See example. It will compile fine with tsc -p ./ but intellisense in Code will show an error in lib\lib.ts

**Comment by kieferrm** [comment]
@rolandoldengarm did you configure `typescript.tsdk` in your user or workspace settings to point to your TS 2.0 install?

**Comment by rolandoldengarm** [comment]
No, did not know about that. Found the documentation now to do that, thanks :) Will test that shortly, but this issue can be closed.
