### ISSUE TITLE
Remote explorer: location specific code?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#95705]
Found this by accident, I think we cannot have location specific code anymore given views can move around:

https://github.com/microsoft/vscode/blob/3ec72784c1e4b220da8b332bd3519c161042b576/src/vs/workbench/contrib/remote/browser/explorerViewItems.ts#L44

**Comment by alexr00** [comment]
Can we move view containers? The dropdown is tied to the viewlet, not the view, so I think it shouldn't be moving. I'd actually prefer to not allow any of the views in the remote explorer to move since it completely breaks the drop down functionality.

**Comment by bpasero** [comment]
I thought you can move any view to be a panel, e.g. like you can do for "Search". But @sandy081 or @sbatten can probably answer this better.

**Comment by sandy081** [comment]
> Can we move view containers? 

Yeah we are planning to support moving view containers.  So user can move Remote Explorer completely to panel unless you do not want to. But I do not see a reason why not to.

**Comment by alexr00** [comment]
I think moving the whole remote explorer makes sense, but moving individual views from it breaks it. (I'll fix the location specific color)
