### ISSUE TITLE
The editor freezes while parsing JSX. 

### ISSUE THREAD

**Issue by vchouhan** [microsoft/vscode#95708]
Not sure how to reproduce but I've noticed that when I working with a react app and I’ve language mode `JS Babel`, and Prettier as a default formatter the editor typing freezes when it encounters errors with JSX, mean it can’t parse JSX, all other functionality of VS code are working.

**Comment by chrmarti** [comment]
/needsMoreInfo

Which OS and which VS Code version are you on?

Does this occur with all extensions disabled? (`F1` > `Developer: Reload With Extensions Disabled` or `code --disable-extensions`)

**Comment by vchouhan** [comment]
MAC OSX: 10.15.5
[extensions.txt](https://github.com/microsoft/vscode/files/4542475/extensions.txt)

VSCODE
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z (1 wk ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

This usually happens while working on JSX files. I've disabled all formatting on save and yet it fails. 

If you need any other info, please reach out. Thank you.

**Comment by chrmarti** [comment]
Does this occur with all extensions disabled? (`F1` > `Developer: Reload With Extensions Disabled` or `code --disable-extensions`)
