### ISSUE TITLE
vscode.executeCompletionItemProvider returns the wrong CompletionItemKinds in insiders

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#95715]
The current insiders build is returning the wrong CompletionItemKinds for methods (it's returning property).

Repro steps:

1. Create a new extension with `yo code`
2. Paste in the following code which returns two completion items, one Property and one Method:
  ```ts
	import * as vs from 'vscode';

	export function activate(context: vs.ExtensionContext) {

		vs.languages.registerCompletionItemProvider({scheme: "file"}, {
			provideCompletionItems(document: vs.TextDocument, position: vs.Position, token: vs.CancellationToken, context: vs.CompletionContext) {
				return [
					new vs.CompletionItem("My Method", vs.CompletionItemKind.Method),
					new vs.CompletionItem("My Property", vs.CompletionItemKind.Property),
				];
			}
		});

		let disposable = vs.commands.registerCommand('vscode-repro-completion-kinds.helloWorld', async () => {
			const doc = vs.workspace.textDocuments.length
			? vs.workspace.textDocuments[0] 
			: await vs.workspace.openTextDocument();

			const completions = await vs.commands.executeCommand("vscode.executeCompletionItemProvider", doc.uri, new vs.Position(0, 0)) as vs.CompletionList;
			console.log(JSON.stringify(completions.items.filter((c) => c.label.startsWith("My ")), undefined, 8));	
		});

		context.subscriptions.push(disposable);
	}

	export function deactivate() {}
  ```
3. Press F5 to run the extension
4. Open the Dev Tools
5. Run the "Hello World" command

The output looks like this:

```
[
	{
		"label": "My Method",
		"kind": "Property",  // <------ This is incorrect
		"sortText": "My Method",
		"insertText": "My Method"
	},
	{
		"label": "My Property",
		"kind": "Property",
		"sortText": "My Property",
		"insertText": "My Property"
	}
]
```

**Comment by DanTup** [comment]
@jrieken not sure if this may be related to ab24124841766a6f7ab993a3ad83ed8c436366a7 - there seem to be a few paths that use `Property` as a fallback, but I'm not sure why it's getting to that.

**Comment by jrieken** [comment]
Yeah, looks like this is the bad line: https://github.com/microsoft/vscode/blob/8f1b2e565797929d8e8fd772ed35fa202ac76567/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L957. I made the `from` function not accept `undefined` anymore because it faster if it only runs with SMIs but the usual error happened...

**Comment by DanTup** [comment]
Fix looks good - my integration tests are passing again :) Thanks!
