### ISSUE TITLE
No emmet expansions when multiple cursors are used

### ISSUE THREAD

**Issue by dslpp056193** [Microsoft/vscode#9571]
- VSCode Version: 1.3.1
- OS Version: windows 10

Steps to Reproduce:

When you try write emmet function with multiple coursors, it will not be work.
Example:
If you try use emmet in next case, you get nothing, just ugly tabs

```
selector{
        height: 50px !|
        width: 50px !|
        top: -1px !|
}
```

Its very sadly, can you fix it?

**Comment by egamma** [comment]
Currently the implementation is intentionally checking for a single selection. Will investigate what it means to support multiple cursors.

**Comment by dslpp056193** [comment]
In this case i try use `!important` shortcut, but not succesfully.
It's need in a lot of cases. 
Consider the following case:
I created 2-3 `div`'s in html, and some time later i want add `span` in every `div`. I want type `span` and hit **tab**, but i can't do it, because VSC not supported emmet with multiple cursors.
I leave sublime and atom, but in them it works and it useful.

**Comment by egamma** [comment]
The current behavior is consistent with the way snippets are handled in the multiple cursor case.

**Comment by egamma** [comment]
Shifting - depends on the support of multi cursors in snippets.

**Comment by ramya-rao-a** [comment]
With the work being done as part of #21943, multi cursor support is doable but the whole snippet expansion is still blocked by #16037

**Comment by ramya-rao-a** [comment]
Changes for #21943 is merged.

Set `emmet.useNewEmmet` to `true` to get emmet abbreviation expansions in the suggestion list.
This will work in multi cursor too

For details on this setting read https://github.com/Microsoft/vscode/issues/1952#issuecomment-305390464
