### ISSUE TITLE
argument is undefined or null

### ISSUE THREAD

**Issue by Javohir-code** [microsoft/vscode#95710]
Issue Type: <b>Performance Issue</b>

I deleted monokai++ extension and when I try to open any ... .js or .json file. vscode says: Assertion failed: Argument is undefined or null. Even I could not open settings. nothing worked. I reinstall it but nothing changed. Please help. Thank you in advance.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N3050  @ 1.60GHz (2 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (4.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    92	 11336	code main
    0	   151	  3044	   window (My projects - Visual Studio Code)
    0	    64	   624	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    2	    60	  1688	     extensionHost
    0	    83	  9324	       electron_node tsserver.js 
    0	    45	   844	         electron_node typingsInstaller.js typesMap.js 
    0	    49	 11048	       electron_node tsserver.js 
    0	    28	 13332	       "C:\Users\Javokhir\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Javokhir\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=1688
    0	    11	  8036	     watcherService 
    0	    11	 10672	       console-window-host (Windows internal process)
    1	    36	 10636	     searchService
    0	     5	 13404	     console-window-host (Windows internal process)
    0	    25	  5908	   utility
    0	    14	  7996	   electron-crash-reporter
    0	    70	 11552	   shared-process
    2	   138	 12296	   gpu-process
    0	   116	 12712	   "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" -- "https://go.microsoft.com/fwlink/?LinkID=533483#vscode"
    0	     6	 11864	     crashpad-handler
    0	   114	 13232	     window (undefined)
    0	     8	 14136	     watcher
    0	    73	 14340	     gpu-process
    0	    34	 14360	     utility
    0	   131	 14756	     window (undefined)
    0	   120	 14796	     window (undefined)
    0	   125	 16004	     window (undefined)
    0	   204	 16944	     window (undefined)
    0	    73	 17548	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (My projects - Visual Studio Code)
|    Folder (My projects): 148 files
|      File types: js(52) jpg(19) html(14) css(8) png(7) json(6) log(4) jsx(3)
|                  md(2) zip(1)
|      Conf files: package.json(2);
```

</details>
Extensions: none

**Comment by chrmarti** [comment]
Did you delete the extension using the UI or directly on disk?

Is there anything in the console? (`Help` > `Toggle Developer Tools`)

**Comment by Javohir-code** [comment]
In the console git installation not found as warning . That's it. But does not work yet

**Comment by Javohir-code** [comment]
Thanks, it works again. I deleted visual studio code from computer but extensions and settings are not removed. Before this I couldn't open settings.json to fix the null. After I remove the vscode, it opens another thing then I fix the problem with changing the null. Thank you

**Comment by chrmarti** [comment]
Closing, thanks.
