### ISSUE TITLE
You just crashed my graphics driver with a live update.

### ISSUE THREAD

**Issue by leventt** [microsoft/vscode#95711]
Issue Type: <b>Bug</b>

Please don't update this editor while I code and let it wait for a restart.
Cheers!

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
Can you show me the error? What happened?

**Comment by joaomoreno** [comment]
Also, if you don't want updates in the background, set `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by leventt** [comment]
That setting will work perfectly. You can close this. For the error, I don't have any unfortunately. When the live update was triggered, my screen went white then the buffer had some misalignment in GPU it looked like. It was all glitchy, until I restarted.

Cheers!
