### ISSUE TITLE
Some emoji not matched using new Quick Pick

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#95716]
Issue Type: <b>Bug</b>

Having a markdown file with headers:

```markdown
# ❌ Wow
```

Searching for symbol `@❌` - returns no results
VS Code version: Code - Insiders 1.45.0-insider (ec0d19789f89d4c25895f4a0cf364276cfb0c6ed, 2020-04-20T06:08:30.812Z)
OS version: Windows_NT x64 6.2.9200

**Comment by bpasero** [comment]
This is probably the gist of what was mentioned in

Test that isolates the issue into the filter:

**Comment by bpasero** [comment]
One thing I am not sure about: the second invocation returns `0,4,0`. My understanding is that the first number is the score and so I ignore scores of `0`, but the value of `4` seems to suggest that there is still a match?

**Comment by jrieken** [comment]
> My understanding is that the first number is the score and so I ignore scores of 0, but the value of 4 seems to suggest that there is still a match?

This isn't the right understanding - it will return `undefined` when there is no match.

**Comment by isidorn** [comment]
Seems to work fine, adding verified label
![Screenshot 2020-04-30 at 14 35 46](https://user-images.githubusercontent.com/1926584/80710980-e7dc1b00-8aef-11ea-8fca-21456734dda5.png)
