### ISSUE TITLE
Save button doesn't work

### ISSUE THREAD

**Issue by thejoao94** [microsoft/vscode#95719]
I have to constantly close my VS Code and close my html file and create a new one to save any changes I have made to the file. If I try and save the file manually the Save - Ctrl + S function on the file toolbar doesn't fade away like it's supposed to after you save the changes you've made.

**Comment by sbatten** [comment]
i'm not quite sure I understand. are you saying the dirty indicator doesn't disappear after saving? perhaps you could provide a gif or screenshot of what you are seeing.
