### ISSUE TITLE
Extension registered schema providers random fail to get invoked

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#95729]
- VSCode Version: 1.45.0-insiders (repros with non-insiders too)
- OS Version: Windows

Steps to Reproduce:

1. Install the C/C++ extension (may repro with other extensions). Our extension uses

```typescript
    class SchemaProvider {
        provideTextDocumentContent(uri) { // When the bug occurs this doesn't get called by VS Code
            return __awaiter(this, void 0, void 0, function* () {
		// ...
                return // file contents
            });
        }
    }
// This register always gets called by our extension
    vscode.workspace.registerTextDocumentContentProvider('cpptools-schema', new SchemaProvider());
```
2. Create a blank test.cpp file (to activate our C/C++ extension).
3. Use the C/C++: Edit Configuration (JSON) command to create a new c_cpp_properties.json.
4. Keep using reload window until the bug randomly repros (repro probability is high for me, it doesn't repro when debugging our extension). Other members of our team and some of our extension users have also hit this, but some people do not repro it.

Bug: See the screenshot. It fails to load the schema. It gets fixed after clicking the retry button in the status bar that appears.

![image](https://user-images.githubusercontent.com/19859882/79806171-a2b03000-831c-11ea-8c2b-903ab20bb8ff.png)

Originally reported at https://github.com/microsoft/vscode-cpptools/issues/4841 .

Does this issue occur when all extensions are disabled?: Requires our C/C++ extension but we don't believe it's our bug.

**Comment by Colengms** [comment]
We are using this to implement localizeable schemas, as suggested here: https://github.com/microsoft/vscode/issues/78737

In Sean's case, I suspect the issue may be that the file is already open when launching VS Code, and there is an attempt to access the uri before we call registerTextDocumentContentProvider().  If we registered this immediately in activate(), would that be sufficient to ensure it's always registered before used by VS Code?

**Comment by sean-mcmanus** [comment]
I modified our code to register as soon as possible, but the issue was still easily reproduced.

Our package.json has
```
    "jsonValidation": [
      {
        "fileMatch": "c_cpp_properties.json",
        "url": "cpptools-schema:///c_cpp_properties.schema.json"
      }
    ],
```

so it seems like VS Code should be able to recognize that our extension needs to be activated before it tries to do json validation on that file.

**Comment by jrieken** [comment]
What activation events is your extension using and can you guarantee that registerTextDocumentContentProvider is called *during* activate?

**Comment by sean-mcmanus** [comment]
The relevant activation event is "workspaceContains:/.vscode/c_cpp_properties.json", which corresponds to the file that we're registering the schema for.

We can guarantee that the registerTextDocumentContentProvider is called during the activate -- our current shipping code doesn't call it right away (it does so asynchronously after some delay during activation), but I moved the call to the start of the activate hoping that would fix or at least help, but it didn't help.

**Comment by jrieken** [comment]
Ok, understood. So, there is two problem here

* VS Code doesn't wait for `workspaceContains` (and also not `*`) activation to finish. They just happen and are not part of a flow like "A command has been triggered, lets see if extensions to contribute something"
* For text document content provider we actually don't send an event...

I will push a change for seconds (likely re-using the onFileSystem-event) and then your extension needs to adopt it

**Comment by jrieken** [comment]
Actually - we already send out said activation event which leaves nothing to do here for us

**Comment by sean-mcmanus** [comment]
Okay, thanks -- adding the onFleSystem:cpptools-schema activationEvent appears to have fixed the issue.
