### ISSUE TITLE
Dynamically setting command filter context does not work

### ISSUE THREAD

**Issue by jepetty** [microsoft/vscode#95727]
- VSCode Version: 1.45.0-insiders
- OS Version: Windows 10 19041.207

## Problem description

I'm trying to create an extension that will display a command only on certain files, based on a filter I set after my extension has loaded. My package.json for my custom command looks like this:
```json
"contributes": {
    "commands": [
        {
            "command": "myCommand",
            "title": "My Command",
            "category": "MyExtension"
        }
    ],
    "menus": {
        "editor/context": [
            {
                "command": "myCommand",
                "group": "navigation",
                "when": "resource =~ myExtension:myFilter"
            }
        ]
    }
}
```

Then, once my extension loads, I set the value of my filter `myExtension:myFilter` with:
```ts
await vscode.commands.executeCommand('setContext', 'myExtension:myFilter', '/root((?!badPath))[a-zA-Z0-9_/.]*.(cs|ts|js)$/i');
```
But, debugging VS Code, I see that when the Regex is evaluated in [contextKey.ts](https://github.com/microsoft/vscode/blob/master/src/vs/platform/contextkey/common/contextkey.ts#L565..L568), the regex used for comparison is always null (which makes sense, because `this.regExp` is `readonly`, and thus won't be updated with my new value). If I copy-paste this Regex so it's statically set in my package.json, the filtering occurs as expected.

I would expect this to work as it does when I'm using a boolean value to filter like so:
```json
"menus": {
    "editor/context": [
        {
            "command": "myCommand",
            "group": "navigation",
            "when": "myExtension:myFilter"
        }
    ]
}
```
```ts
await vscode.commands.executeCommand('setContext', 'myExtension:myFilter', true);
```

Is it possible to allow these regex filters to be dynamically set? If not, is there a recommended way to only display commands for a subset of files?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
> Is it possible to allow these regex filters to be dynamically set? If not, is there a recommended way to only display commands for a subset of files?

No - context keys are static, context values can be set with the `setContext`-command and then context keys are re-evaluated. If you want to match on certain files you must know the match-criteria statically.
