### ISSUE TITLE
Does not display folders

### ISSUE THREAD

**Issue by altogua** [microsoft/vscode#95720]
Hemos escrito los datos necesarios en su Portapapeles porque eran demasiado grandes para enviarlos. Ahora debe pegarlos.
hoLA,en Visual studio version :1.43.2,  no me carga las carpetas, no las visualiza. Solo visualiza los archivos

**Comment by altogua** [comment]
Hello, in Visual studio version: 1.43.2, it does not load the folders, it does not display them. Just view the files

**Comment by sbatten** [comment]
@altogua can you provide a screenshot/gif of what you see?

**Comment by altogua** [comment]
![No VISUALIZA las CARPETAS](https://user-images.githubusercontent.com/62995279/79851473-a3e96780-83c5-11ea-9664-91afa3c85333.jpg)
![No VISUALIZA las CARPETAS](https://user-images.githubusercontent.com/62995279/79851532-bc598200-83c5-11ea-91de-f6fb53b3f983.jpg).

thanks for answering. Here I send some images as requested.Carlos


> Hola, en la versión de Visual Studio: 1.43.2, no carga las carpetas, no las muestra. Solo mira los archivos
Pero tengo 2 notebook y en una abre las carpetas.
tengo ademas la version 16.5.4, y tampoco ahi me las abre.
![No VISUALIZA las CARPETAS](https://user-images.githubusercontent.com/62995279/79853007-c7151680-83c7-11ea-8598-9b2593699e88.jpg)

**Comment by altogua** [comment]
aqui esta una toma de pantalla de lo que sucede. Tengo la versión de visual 16.5.4 y tampocoalli me abre las carpetas.Esto me sucede en una notebook, enla otra no,es algun cortafuegos queno logro desinescar, e anulado el firewall, el antivirus y nada, gracias,

**Comment by altogua** [comment]
Here is a screenshot of what is happening. I have the version of visual 16.5.4 and neither does it open the folders for me. This happens to me in a notebook, in the other it does not, it is some firewall that I cannot un-install, and I canceled the firewall, the antivirus and nothing, thanks,

**Comment by sbatten** [comment]
@altogua were you able to resolve your issue? Are you able to open folders from other locations on your computer?
