### ISSUE TITLE
VS Code doesn't recognise selected Index as a property

### ISSUE THREAD

**Issue by futurelucas4502** [microsoft/vscode#95723]
From VS code > Help > About:
- VS Version: 1.44.2 (user setup)
- Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
- Date: 2020-04-16T16:36:23.138Z
- Electron: 7.1.11
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Adding .selectedIndex() and hovering over for emmet suggestion results in "any" instead of the property and information about it
![image](https://user-images.githubusercontent.com/48055553/79793454-81653900-8348-11ea-9a13-dcf14410907a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
See https://stackoverflow.com/a/53798013/306149

**Comment by futurelucas4502** [comment]
That is a different issue where it's not appearing as they have not set it as a constant or variable this is not a question but a bug report where it isn't appearing at all for example if I was to then change it to what you have linked me to where I set the element as a variable:
![image](https://user-images.githubusercontent.com/48055553/79805958-3a367280-835f-11ea-80d0-cc2ffe345837.png)
It still doesn't work because VS Code isn't finding the correct property information for .selectedIndex therefore I am asking if this issue can be fixed in a future release.

**Comment by ArturoDent** [comment]
Try

`/** @type {HTMLSelectElement} */`
`var selected = document.getElementById("...")`
`selected.selectedIndex`  // hover now

**Comment by futurelucas4502** [comment]
Why is that not default behavior? @ArturoDent

**Comment by mjbvz** [comment]
Because there's no way for VS Code to know the type html element `getElementById` will return. You need to annotate that if you are accessing a property that only exists on specific elements such as `<select>`

Showing `selectedIndex` by default would be misleading

**Comment by futurelucas4502** [comment]
Ah okay it just seemed broken to me due to the fact it seems to be able to handle many other HTML specific properties
