### ISSUE TITLE
commands work in terminal but not in integrated terminal Catalina

### ISSUE THREAD

**Issue by xiaoouwang** [microsoft/vscode#95725]
- VSCode Version: Version: 1.44.2
- OS Version: Darwin x64 19.4.0. Catalina 10.15.4

Steps to Reproduce:

The following command works in terminal or iterm:

`sendpraat praat 'execute "test.praat"'
`

however if you use it in the integrated terminal neither works, nothing happens.

I suspect it had something to do with the Catalina's new privacy system because when I use the command in terminal it asked permission so in my automation panel the praat program is related to terminal.

![image](https://user-images.githubusercontent.com/16024291/79797692-fee47580-8357-11ea-8d43-b902436b0546.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
> when I use the command in terminal it asked permission

@xiaoouwang what permission was asked ?

**Comment by xiaoouwang** [comment]
> > when I use the command in terminal it asked permission
> 
> @xiaoouwang what permission was asked ?

![image](https://user-images.githubusercontent.com/16024291/79897114-85a55b00-8409-11ea-9426-05a44b66ac54.png)

Actually I can replicate it simply by unchecking praat under terminal or iterm. When I uncheckit the command simply does nothing.

Too bad that I can't add manually items in the Automation tab.

**Comment by deepak1556** [comment]
Thanks, this is not possible to workaround at the moment, the work done for https://github.com/microsoft/vscode/issues/95062#issuecomment-614246634 should help this one too.

**Comment by xiaoouwang** [comment]
> Thanks, this is not possible to workaround at the moment, the work done for [#95062 (comment)](https://github.com/microsoft/vscode/issues/95062#issuecomment-614246634) should help this one too.

tks, I finally use sudo code to launch vscode and the command works. It's a "dangerous" workaround but better than nothing.

**Comment by deepak1556** [comment]
Merging this to https://github.com/microsoft/vscode/issues/95062
