### ISSUE TITLE
When the dark theme is on, some pop-ups remain white

### ISSUE THREAD

**Issue by Rakleed** [microsoft/vscode#95722]
- VSCode Version: 1.44.2
- OS Version: Windows 10 v. 1909 (18363.778 build)

Steps to Reproduce:

1. Make sure that the Default Dark+ theme on VS Code are enabled.
2. Press "Help" and select "Check for Updates..." or "About". Or try opening the GitHub link from Release Notes.

Does this issue occur when all extensions are disabled?: Yes

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/19418601/79787841-50890200-8350-11ea-90d9-177219bbaddc.png)

![image](https://user-images.githubusercontent.com/19418601/79787897-6eeefd80-8350-11ea-8340-19daffed0587.png)

![image](https://user-images.githubusercontent.com/19418601/79787913-76aea200-8350-11ea-9cd2-8493f1c4c86d.png)

![image](https://user-images.githubusercontent.com/19418601/79787935-7f9f7380-8350-11ea-8268-8221d6b878ca.png)

</details>

**Comment by beastdestroyer** [comment]
Those are windows 10 dialog boxes that VSCode uses, doubt that Microsoft has a dark theme version of those inbuilt into the OS

**Comment by sbatten** [comment]
as @beastdestroyer says, these are just native os dialog message boxes and are not themable.
