### ISSUE TITLE
Code - Insiders Helper CPU running high

### ISSUE THREAD

**Issue by gerhardcit** [Microsoft/vscode#9572]
- VSCode Version: Code - Insiders 1.4.0-insider (3abddec3580ab09c11c7f7cc5a2954908b9a4522, 2016-07-21T05:03:46.731Z)
- OS Version: Darwin x64 15.5.0

Steps to Reproduce:

1. Install latest version
2. Open web app with HTML and json
3. CPU starts running high

This use the be the Electron Helper.. now it is back.. with a new name.

[Sample of Code - Insiders Helper.txt](https://github.com/Microsoft/vscode/files/375676/Sample.of.Code.-.Insiders.Helper.txt)

**Comment by kieferrm** [comment]
@gerhardcit Do you have a sample workspace that shows that behavior. Can you pls give us the concrete steps, i.e. which file you open, what you do in the editor, etc. so that we don't have to guess when we try to reproduce it. Thanks!

**Comment by gerhardcit** [comment]
@kieferrm , It could be related to the update of an extension: Auto Rename Tag. (just upgraded to 0.0.6) after working for 2 hours without problem (from hibernate state) and the problem occured.

Also, after quitting the Insiders App, the Helper keeps running in the background. It seem to disconnect from the parent process somehow. 

<img width="758" alt="screenshot 2016-07-24 11 33 26" src="https://cloud.githubusercontent.com/assets/5508278/17083050/0a8a3cf8-5193-11e6-9a2f-fd6a58ffe05f.png">
[Sample of Code - Insiders Helper2.txt](https://github.com/Microsoft/vscode/files/380213/Sample.of.Code.-.Insiders.Helper2.txt)

**Comment by gerhardcit** [comment]
Extending the fileWatcher seems to help with this.
files.watcherExclude": {
".hg": true,
"bower_compoments": true,
.... add any build folders that will change a lot
}
Closing..

**Comment by dantesun** [comment]
I have the same issue here. The cpu load becomes high once I opened a package.json file. Below are the package.json file and "Code Helper" command lines. So I think it might related to npm intellisense.
`
{
  "name": "ng-book2-reddit",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "clean": "rm -f ./*.js; rm -f ./*.js.map; rm -f ./intermediates/*.js; rm -f ./intermediates/*.js.map",
    "tsc": "./node_modules/.bin/tsc",
    "tsc:w": "./node_modules/.bin/tsc -w",
    "serve": "./node_modules/.bin/live-server --host=localhost --port=8080 .",
    "go": "concurrent \"npm run tsc:w\" \"npm run serve\" "
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "core-js": "2.2.2",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "^0.19.6",
    "ts-helpers": "1.1.1",
    "tslint": "3.7.0-dev.2",
    "typescript": "1.9.0-dev.20160409",
    "typings": "^0.8.1",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "concurrently": "1.0.0",
    "live-server": "0.9.0",
    "typescript": "1.7.3"
  }
}
`

`
501 93842 93835   0 11:03PM ??         0:03.87 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=gpu-process --channel=93835.0.2120300640 --no-sandbox --supports-dual-gpus=true --gpu-driver-bug-workarounds=17,31,36,48,50,54,61,67,70 --gpu-vendor-id=0x10de --gpu-device-id=0x0fe9 --gpu-driver-vendor --gpu-driver-version
  501 94203 93835   0 11:03PM ??         0:00.53 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=SharedProcess
  501 94204 93835   0 11:03PM ??         0:22.47 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --no-sandbox --lang=en-US --node-integration=true --background-color=#131313 --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=34037 --channel=93835.1.44068021
  501 94205 94204   0 11:03PM ??         0:02.54 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost
  501 94208 94204   0 11:04PM ??         0:00.22 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=watcherService
  501 94211 94204   0 11:04PM ??         0:00.20 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap /usr/local/bin/git /Users/dsun/workspace/opensource/angular2-starter utf8 /Applications/Visual Studio Code.app/Contents/MacOS/Electron 2.6.1
  501 94213 94205   0 11:04PM ??         0:00.33 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json/node_modules/vscode-languageclient/lib/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json/server/out/jsonServerMain.js
  501 94630 94204   0 11:05PM ??         0:00.45 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper ./terminalProcess
  501 95073 93835   0 11:08PM ??         0:04.60 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --no-sandbox --lang=en-US --node-integration=true --background-color=#131313 --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=34037 --channel=93835.2.795817435
  501 95077 95073   0 11:08PM ??         4:40.29 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost
  501 95078 95077   0 11:08PM ??         0:00.23 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json/node_modules/vscode-languageclient/lib/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json/server/out/jsonServerMain.js
  501 95360 67782   0 11:12PM ttys003    0:00.00 grep --color=auto Code Helper
`

**Comment by jfcartier** [comment]
Workaround here https://github.com/Microsoft/vscode/issues/11096#issuecomment-274879938
