### ISSUE TITLE
What I want to say is that there are a lot of blank lines in the text content of the console, and the problem that the mouse cursor cannot select the text content from right to left.

### ISSUE THREAD

**Issue by 395053994** [microsoft/vscode#95737]
Issue Type: <b>Bug</b>

What I want to say is that there are a lot of blank lines in the text content of the console, and the problem that the mouse cursor cannot select the text content from right to left.
May I ask when the problem can be fixed?

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|9.59GB (4.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|2.1.5
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.4.0
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.1
comment-translate|int|1.4.2
vuejs-extension-pack|mub|1.2.1
color-highlight|nau|2.3.0
vetur|oct|0.24.0
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.16.0
vscode-manifest-yaml|Piv|1.16.0
vscode-spring-boot|Piv|1.16.0
java|red|0.60.0
vscode-xml|red|0.11.0
vscode-yaml|red|0.7.2
vue-vscode-snippets|sdr|1.9.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2
vscode-spring-initializr|vsc|0.4.6
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

![kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk](https://user-images.githubusercontent.com/27546390/79821700-0476a580-83c2-11ea-9921-6390533c86ad.png)
![kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk](https://user-images.githubusercontent.com/27546390/79821813-43a4f680-83c2-11ea-8071-e8576217a336.png)
![kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk](https://user-images.githubusercontent.com/27546390/79821885-78b14900-83c2-11ea-86b6-8d68a0d72578.png)

May I ask when the problem can be fixed?

**Comment by 395053994** [comment]
For details, please refer to:
https://github.com/microsoft/vscode-java-pack/issues/359

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/2163
