### ISSUE TITLE
Tasks 'command' from system environment variable enclosed in single quotes

### ISSUE THREAD

**Issue by rstreif** [microsoft/vscode#95738]
- VSCode Version: 1.44.2
- OS Version: Linux 5.3.11-300.fc31.x86_64 #1 SMP Tue Nov 12 19:08:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. I have a cross compile environment that sets ${CXX} to:
$ echo ${CXX}
arm-altec-linux-gnueabi-g++ -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/home/xyz/systemroot

2. I am using this variable as the command in a task command in tasks.json:
"command": "${env:CXX}"

3. When running the task I am getting the output from the shell:
> Executing task: 'arm-altec-linux-gnueabi-g++  -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/home/xyz/systemroot' -g helloworld.cpp -o /home/xyz/vscode/helloworld/.vscode/tasks <

/bin/bash: arm-altec-linux-gnueabi-g++  -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/home/xyz/systemroot: No such file or directory
The terminal process terminated with exit code: 127

For some reason vscode surrounds the content of the environment variable, which is the command, with single quotes before passing the entire command string to the shell. That causes the shell to look for a file that has that name when of course the first piece is the command and the rest are arguments.

Now of course I can split up the actual command and the arguments but that makes the entire thing less portable. All I want to do is source my environment and the use the environment variables in vscode.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Does one of the alternate quoting options solve this for you? ex:
```
                        "command":{
				"quoting": "escape",
				"value": "${env:CXX}"
			}
```
