### ISSUE TITLE
An error occurred while loading the image.

### ISSUE THREAD

**Issue by doublelam** [microsoft/vscode#95736]
Issue Type: <b>Bug</b>

when clicking an image from left panel， there's a great probability encounter this issue, sometimes when you click another image and then re-click the previous image, you won't encounter this issue, but, mostly, you still get this issue

and when I click the 'Open file using VS Code's standard text/binary editor?' is useless, nothing happened
![image](https://user-images.githubusercontent.com/12025501/79821908-823ab100-83c2-11ea-9a1d-098caedfcecb.png)

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T08:23:56.137Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 6, 6|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|-psn_0_2298417|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.1
vscode-gutter-preview|kis|0.26.1
vscode-typescript-tslint-plugin|ms-|1.2.3
color-highlight|nau|2.3.0
vscode-xml|red|0.11.0
code-spell-checker|str|1.8.0

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you reload with all extensions disabled?

**Comment by doublelam** [comment]
> Does the problem also happen if you reload with all extensions disabled?

was trying to disable all extensions, this issue still exists, I guess it's related to memory. when my mac has lower memory, I meet this issue more often. anyway, I still meet this issue though it has enough memory, especially when clicking images one by one and preview an image which hasn't been opened before

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by thunfischtoast** [comment]
I encounter this issue sometimes when working on a SSH-Remote.
I can reproduce it in the following version with just Remote - SSH extension enabled and nothing else.

Version: 1.45.0-insider
Commit: abb4a35cfc26102f93fd00df7b59ce1a19c2017a
Date: 2020-04-28T05:38:07.215Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-96-generic

**Comment by tillig** [comment]
I noticed an earlier ticket with a similar issue where the problem had something to do with a `%` being in the name of the file or somewhere in the path. I'm seeing this while working on an Azure DevOps wiki where there's URL encoding in the path.

The image is at `/Stand%2DIn-Data/Data-Model-ERD.png` in the repo. (This way, in Azure DevOps wiki, it renders as `Stand-In Data`.) If I move this same image _out_ of that folder to some other location, like `/Test/Data-Model-ERD.png` it renders just fine. This leads me to believe the `%` is absolutely the culprit, at least in my case.

I notice that this log message shows up in the `Log (Window)` output pane when the image fails to render the first time. It only shows up once, regardless of whether I close and reopen the image.

```
[2020-05-12 07:34:19.980] [renderer1] [error] Cannot read property 'important' of undefined: TypeError: Cannot read property 'important' of undefined
    at e.fetch (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6606:708)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async e.doActivate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6606:343)
    at async Promise.all (index 2)
    at async e.activateProactiveRecommendations (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6724:681)
```

Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by chrisdias** [comment]
@mjbvz this happens for me 100% of the time when using Remote - WSL.  If I open a folder locally I can view the images. Trying to open any images when remote give this error.

There are no errors in the console.

Using latest Insiders
```
Version: 1.46.0-insider (user setup)
Commit: 9e439b13d5784538333bee044ca1d1a992bc1c90
Date: 2020-05-28T18:44:47.151Z
Electron: 7.3.0
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```
