### ISSUE TITLE
Typings should not be included in search, go to file etx

### ISSUE THREAD

**Issue by slowmove** [Microsoft/vscode#9573]
- VSCode Version: 1.3.0
- OS Version: OS X El Capitan

Steps to Reproduce:
1. Install typings with ```typings install dt~node``` for instance.
2. Exclude typings in ```"search.exclude"``` in settings.
3. Go to file (cmd + p) and search for index still shows index.d.ts

![skarmavbild 2016-07-21 kl 12 37 36](https://cloud.githubusercontent.com/assets/624182/17020219/b648fb4c-4f40-11e6-93ba-e3a776da680b.png)

![skarmavbild 2016-07-21 kl 12 42 44](https://cloud.githubusercontent.com/assets/624182/17020218/b647d686-4f40-11e6-96f3-0daf6dc32fa2.png)

**Comment by kieferrm** [comment]
In our latest insider 1.4.0 that works as expected.

In 1.3.0 it appears you need to restart vscode otherwise the change to the exclude paths may not be in effect.
