### ISSUE TITLE
Extensions opening side panel crash

### ISSUE THREAD

**Issue by sierisimo** [microsoft/vscode#95734]
I'm currently writting a Markdown file which includes generated PNG files.

Those PNG files are generated through the PlantUML plugin. 

I was trying to review some previously created diagramas or markdown files using on the left 2 vertical panels and on the right the preview of the current document (can be the preview of the markdown or from the plantuml) 

After trying to change from one panel to other on the left side, VSCode suddenly crashed, after reopening VSCode and having a single panel view everytime I try to open a panel a preview panel with the CMD + Shit + P and selecting any option of preview (markdown or plantuml) the editor crashes.

**Comment by mjbvz** [comment]
Please fill out the issue template and be sure to test with extensions disabled

**Comment by sierisimo** [comment]
I'll try to provide more info based on the templates and docs but I created this issue from the `Help -> Report Issue`

So, I wasn't aware on the template or format coming from that window.
