### ISSUE TITLE
pullFrom does not work with fetchOnPull enabled

### ISSUE THREAD

**Issue by PascalPixel** [microsoft/vscode#95743]
Issue Type: <b>Bug</b>

1. In settings, set `"git.fetchOnPull": true,`
2. Using the command palette, checkout a branch that is behind `master` in commits.
3. Using the command palette, run `Git: Pull from...`
4. Select `origin`
5. Select `master`
6. VScode's git will only `fetch` from `master` and not `pull` at all.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (5.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dongskyler** [comment]
Can I take on this issue? Thank you

**Comment by AmberHayden** [comment]
I also encountered this issue too. Is this issue solved already?

**Comment by love-ui** [comment]
Delete

**Comment by Milestoniel** [comment]
Hall

**Comment by ricksentam** [comment]
@Git {git.fetchOnPull = false}

**Comment by ricksentam** [comment]
@Git {git.fetchOnPull = false} now

**Comment by tabaddor** [comment]
I'd like to work on this issue. Is there any other information I should know?

**Comment by AliabbasMerchant** [comment]
This issue is the same as #97472, and @mdasifhasan has already found a solution to the issue there

**Comment by PascalPixel** [comment]
Closing since there is more progress on #97472
