### ISSUE TITLE
snippets for markdown didn't work in jupyter notebooks

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [microsoft/vscode#95741]
Issue Type: <b>Bug</b>

as the  title said

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (1.18GB free)|
|Process Argv|C:\Users\wuxin\Desktop\VSNotes.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.20.0
path-intellisense|chr|1.4.2
Vsnips|cor|0.4.4
vscode-markdownlint|Dav|0.34.0
python-extension-pack|don|1.6.0
prettier-vscode|esb|4.4.0
julia-debug|Jud|0.0.32
language-julia|jul|0.15.23
language-julia-insider|jul|0.15.24
kite|kit|0.110.0
MagicPython|mag|1.1.0
vscode-language-pack-zh-hans|MS-|1.44.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.3.71659
vsnotes|pat|0.7.1
vscode-yaml|red|0.7.2
markdown-preview-enhanced|shd|0.5.3
vscode-julia-formatter|sin|0.0.4
vscode-markdown-paste-image|tel|0.12.3
python|tht|0.2.3
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.1.1
jinja|who|0.0.8
markdown-all-in-one|yzh|2.8.0
material-theme|zhu|3.2.5

</details>

**Comment by rebornix** [comment]
Please file issues against the Python extension, which provides the Jupyter notebook feature.
