### ISSUE TITLE
Unable to hide problems tab on Panel.

### ISSUE THREAD

**Issue by krishnatoshniwal** [microsoft/vscode#95740]
Issue Type: <b>Bug</b>

I'm unable to hide or remove the problems tab when I build or debug code and there's a syntax error. The problems tab unhides itself and puts the focus back on itself moving the focus from the Terminal or the Debug Console.  

VS Code version: Code 1.44.2
OS version: Linux x64 4.18.0-20-generic

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-bazel|Baz|0.3.0
theme-monokai-pro-vscode|mon|1.1.15
python|ms-|2020.3.71659
cpptools|ms-|0.27.0
vscode-yaml|red|0.7.2
vscode-capnp|xmo|1.0.0

</details>

**Comment by sandy081** [comment]
How are you hiding the problems tab?

**Comment by krishnatoshniwal** [comment]
Here are some more details. I'm hiding the problems tab by clicking right on the PROBLEMS tab and selecting the hide button. But the tab reappears if the build fails showing me all the C++ warnings and errors which have nothing to do with the syntax error. The actual syntax error displayed on the TERMINAL tab loses focus once the build fails. 
I didn't face this issue before and this started turning up recently - I don't believe this has something to do with the updates. 
Is there a way I can disable or turn off the PROBLEMS tab completely?

**Comment by krishnatoshniwal** [comment]
@sandy081 I apologize I didn't update the issue with more details before, could this be reopened?
