### ISSUE TITLE
Mouse scroll in Explorer doesn't work while dragging a file

### ISSUE THREAD

**Issue by Wolfenberg** [microsoft/vscode#95744]
Issue Type: <b>Bug</b>

On MacOS in a long list of files in Explorer try dragging a file to move to another location. While dragging the file for moving, mouse scroll is expected to scroll the tree of files in Explorer, but does not. It's expected as standard behaviour systemwide in MacOS. 

(Instead I have to keep mouse pointer next to the edge of the top or bottom of Explorer and wait till it scrolls to needed location. Which is harder to do in with a large project.)

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 6|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
jest-snippets|and|1.8.0
jsrefactor|cms|2.20.6
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
vscode-generate-getter-setter|DSK|0.5.0
prettier-vscode|esb|4.4.0
vscode-jest-runner|fir|0.4.15
vscode-yarn|gam|1.7.0
macros|ged|1.2.1
vscode-pull-request-github|Git|0.15.0
intellij-idea-keybindings|k--|0.2.38
typelens|kis|1.9.4
refactorix|kri|0.3.6
go-to-spec|Lou|0.1.3
string-manipulation|mar|0.3.2
Kotlin|mat|1.7.1
cpptools|ms-|0.27.0
node-debug2|ms-|1.42.2
vsliveshare|ms-|1.0.2000
color-highlight|nau|2.3.0
vscode-versionlens|pfl|0.25.0
synthwave-vscode|Rob|0.1.3
partial-diff|ryu|1.4.1
vscode-fileutils|sle|3.0.1
vscode-icons|vsc|10.1.1
gitblame|wad|3.2.0
wallaby-vscode|Wal|1.0.195
vscode-js-console-utils|wht|0.7.0

</details>

**Comment by joaomoreno** [comment]
This is a browser limitation. Nothing we can do here, right @deepak1556? I also can't drag selected text and scroll the page, on Chrome.

**Comment by Wolfenberg** [comment]
@joaomoreno In Chrome I can start dragging the image or link and while holding the button, also scroll the page.

**Comment by joaomoreno** [comment]
Interesting. I can't, but maybe that's because I'm on Windows.

**Comment by joaomoreno** [comment]
@isidorn Wanna look into this? I don't have a Mac right now.

**Comment by isidorn** [comment]
Just tried it out.
* Works: drag a file outside of vscode and scroll the explorer while dragging
* Does not work: drag a file inside explorer and scroll the explorer while dragging
* Works: drag a link inside chrome and scroll while dragging

**Comment by joaomoreno** [comment]
Thanks! Weird behavior. We need someone to debug on macOS.
