### ISSUE TITLE
Internal files from Application folder shows up in "Go to file" (cmd + p)

### ISSUE THREAD

**Issue by slowmove** [Microsoft/vscode#9574]
- VSCode Version: 1.3.0
- OS Version: OS X El Capitan

Steps to Reproduce:

1. Open "Go to file" (cmd + p)
2. Search "Index"

![skarmavbild 2016-07-21 kl 12 45 15](https://cloud.githubusercontent.com/assets/624182/17020294/00041dac-4f41-11e6-8832-340d88fffabc.png)

**Comment by kieferrm** [comment]
@slowmove this usually is not the case. vscode searches inside the folder you opened in your workspace and across all files that are currently open if they do not already belong to your workspace.

Here are a few ideas what could cause this:
- you opened a folder in vscode that is a parent folder of `/Applications`
- you have a symlink in your workspace that points to or inside `/Applications`

Is any of that the case?

**Comment by slowmove** [comment]
No, I was in the folder ```~/src/node-modules/json-tryparse``` in the terminal, opening VSCode using ```code .```.

Though when I tested right now the application folder items just appeared when I edited the exclude settings. Reloading the windows fixed it. May be related to #9573 then?
