### ISSUE TITLE
"Expand all" functionality (File Explorer, Test Explorer, Outline, Timeline ...)

### ISSUE THREAD

**Issue by akanz1** [microsoft/vscode#95746]
I would like to request an "Expand All" functionality. Originally I noticed the lack of this functionality for the Test Section in the Python extension. When all tests pass the results are collapsed by default forcing me to individually click through the tree structure to get an overview of all the tests detected / run.

However, this also applies to many other parts of VSCode, such as the file explorer or the outline section. (Also see https://github.com/microsoft/vscode/issues/94820 and https://github.com/microsoft/vscode/issues/88682)

Just like we already have the possibility to "Collapse All" (see Screenshot) it would be nice to have that same button expand all. I.e. toggle between Expanding and Collapsing all tests.

![vscode_testing](https://user-images.githubusercontent.com/51492342/79948632-7efffd80-8474-11ea-9646-240623446d54.png)

Another example is the "outline" panel.
![expand_all](https://user-images.githubusercontent.com/51492342/80316219-ac460600-87fc-11ea-994d-fa650db41993.png)

**Comment by sbatten** [comment]
@akanz1 can you provide a screen shot and information about what tests you are running? It sounds like this is an extension that you have installed, but I am not sure.

**Comment by akanz1** [comment]
@sbatten I hope this clarifies the issue! Apologies for the vague description.

**Comment by sbatten** [comment]
looks like a request for the tree view api to have expand all functionality

**Comment by alexr00** [comment]
This is coming from the Python extension.

**Comment by sbatten** [comment]
@alexr00 it's true that they contribute the tree view, but the request is about having the expand all functionality. core vs code provide the collapse all functionality that tree view providers may opt into. should we not support expand All as well?

**Comment by alexr00** [comment]
@sbatten thanks for the reminder!

**Comment by RLlane2126** [comment]
https://github.com/microsoft/vscode/issues/94820
