### ISSUE TITLE
Generated component not showing in explorer

### ISSUE THREAD

**Issue by praveentoby** [microsoft/vscode#95752]
Issue Type: <b>Bug</b>

When I generate new component in angular, it gets generated successfully, but the not showing in explorer

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 4.4.0-174-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|11.63GB (1.89GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
format-html-in-php|rif|1.6.2
highlight-matching-tag|vin|0.9.9

</details>

**Comment by gjsjohnmurray** [comment]
Go to https://code.visualstudio.com/docs/getstarted/tips-and-tricks and search the page for `files.exclude`

Then check your user settings, and the settings for your workspace, to see if `files.exclude` is causing your generated file to be excluded.
