### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by alx-xlx** [microsoft/vscode#95758]
- VSCode Version: 1.44.2
- OS Version: Win10 x64

Steps to Reproduce:

1. Install Quick Heal
2. Run vscode

Does this issue occur when all extensions are disabled?: Yes/No
![ghyubqI8GD](https://user-images.githubusercontent.com/42188371/79853911-46b1de00-83e6-11ea-8962-17789726ada3.png)

why do i see a virus ?
Please don't tell me to exclude it from AV.
I don't want to infect my PC

**Comment by yume-chan** [comment]
See #94858

**Comment by gjsjohnmurray** [comment]
It's a false positive. See #94858

/duplicate
