### ISSUE TITLE
Setting to control opacity of inserted/removed background in diff editor

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#95756]
I've started using the PR extension a lot recently, and I find the diff editor to have too much going on when there are lots of changes.

When I'm looking at a large number of changes, I would like the "this line has some changes" color to be much lower opacity than the "this is the thing that changed in this line" color. As far as I can tell, I can only set a color for the inserted/removed backgrounds once, and I can't individually control the opacity for "this line has some changes" and "this is the thing that changed".

**Comment by alexdima** [comment]
Let's track in #103207
