### ISSUE TITLE
Sync pick an account polish feedback

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95761]
The blue text just repeats information, that's normally used to categorize items when there are groups of >1:

![image](https://user-images.githubusercontent.com/2193314/79860283-3a4a6880-8387-11ea-8aba-b4b47c6b4244.png)

Also lots of repetition:

- Pick an account
- Select an account
- Use * accounts

I suggest we change it to this:

![image](https://user-images.githubusercontent.com/2193314/79860518-a4630d80-8387-11ea-9e71-f8fbb5fb66d5.png)

**Comment by Tyriar** [comment]
I see the more advanced one now after you've signed in, can we only show that when there are accounts already logged in?

**Comment by sandy081** [comment]
> I see the more advanced one now after you've signed in, can we only show that when there are accounts already logged in

When are you seeing this? There is just one picker and it shows all signed in accounts grouped by provider.

**Comment by Tyriar** [comment]
The first screenshot is when you're turning on sync and have no accounts signed in.

**Comment by sandy081** [comment]
I am asking about the more advanced one you mentioned?

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/79901516-ca5ad300-83c4-11ea-8bea-f2361ef9b402.png)

**Comment by sandy081** [comment]
Changed the initial account picker to pick between Microsoft/Github and untouched the other advanced one

<img width="616" alt="image" src="https://user-images.githubusercontent.com/10746682/79957717-4a933e00-8482-11ea-8364-d84cf6f3a6ce.png">
