### ISSUE TITLE
Cursor jumps to first field when tabbing through Search sidebar fields/options

### ISSUE THREAD

**Issue by ESWAT** [Microsoft/vscode#9576]
- VSCode Version: 1.3.1
- OS Version: OS X El Capitan 10.11.6 (15G31)

Steps to Reproduce:

1. Bring up the Search sidebar
2. Enter a query to search and wait for results
3. Hit the tab key until cursor lands on the *files to include* field
4. Notice the cursor jumps back to the search query field almost immediately

**Comment by kieferrm** [comment]
If after step 4. you tab again to the _files to include_ field the focus stays where it is supposed to be.

**Comment by mattmcardle** [comment]
I am also experiencing this issue on the following platform:

•VSCode Version: 1.3.1
•OS Version: Windows 7 Enterprise SP1
