### ISSUE TITLE
List: range selection should update focused element

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95767]
Current behavior looks a little weird imo:

![55a14309-f15c-49e4-97ff-7692a09c041b](https://user-images.githubusercontent.com/2193314/79865419-fc9e0d80-838f-11ea-895c-bc789ddaa05c.gif)

I think the reason behind this is because the original item is important as it is the root item if the user shift+clicks elsewhere. But even so, the last clicked item is probably more important at this point. I suggest we move to what Windows explorer does and highlight the item that was most recently clicked:

![222f4401-258b-4ba7-9d7a-834837ea9c24](https://user-images.githubusercontent.com/2193314/79865297-c9f41500-838f-11ea-9529-a550e8a6d266.gif)

**Comment by joaomoreno** [comment]
This is hard to implement without introducing yet another trait in the list...

**Comment by Tyriar** [comment]
Yes aligning with Windows Explorer isn't the goal, making it functionality and as users expect is. Windows Explorer happens to have maintained a tree view for decades so it's a good point of reference.

Finder's behavior: https://github.com/microsoft/vscode/issues/95768#issuecomment-617212952
