### ISSUE TITLE
Auto-complete keyword root only (IntelliSense)

### ISSUE THREAD

**Issue by codingKerensa** [microsoft/vscode#95765]
Not sure if I'm lazy or dim - probably both.

Would be great if the auto-complete had an keyboard combination to just complete the keyword currently being typed. i.e anything before a period.

Example from Go:
I'm wanting to type
_case fooBarVeryLongNameHere._**unusual**

I start typing `case foo`...
and the auto-complete suggestions are:
- fooBarVeryLongNameHere.**commonX**
- fooBarVeryLongNameHere.**commonY**
- fooBarVeryLongNameHere.**commonZ**

`.**unusual**` is not listed - which is fine! But could there not be a keyboard combination _just_ to complete `fooBarVeryLongNameHere`? Perhaps something like Ctrl+{PERIOD}, or Shift+ENTER?

_Loving vscode! Thanks for bringing a super-quick IDE to linux._

**Comment by IllusionMH** [comment]
> Example from Go:

Most likely this should be reported to Go extension because it provides completion list.

**Comment by codingKerensa** [comment]
I thought this went beyond the entries of the completion list, but I'll check with the Go extension repo. Many thanks! 

(Btw, question should have been labelled: **feature request**, apologies)
