### ISSUE TITLE
Simple file dialog: Save As does not right trim spaces from a filename 

### ISSUE THREAD

**Issue by jpagliaccio** [microsoft/vscode#95760]
Issue Type: <b>Bug</b>

If you do a Save As, and add a space to the end of the filename by accident,  there is no right trim of trailing spaces. You get files with a trailing space in the filename which is very confusing especially when using the new SSH extension to a Linux system.

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.16299
Remote OS version: Linux x64 3.10.0-1062.18.1.el7.x86_64

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
mssql|ms-|1.9.0

(1 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
If you are running on a system where spaces in the filename are permitted (not Windows) then you should be allowed to have a space.

**Comment by jpagliaccio** [comment]
Agreed as part of The name. Not in trailing though. It's not done that way.
I would say it's not common but I have never seen that. Like trailing
spaces in a password. Good luck debugging that. If someone actually wanted
a trailing space they should do it explicitly. My opinion. It should be
trimmed l and r.

**Comment by weinand** [comment]
While trying to verify this on macOS I found this strange behavior:
On "Save As" on a file (e.g. test.js) I added a space at the of "test.js" and saved.
A file "test.js mjs" showed up in the explorer.

![2020-06-04_17-27-41 (1)](https://user-images.githubusercontent.com/1898161/83776748-d5be4100-a688-11ea-8707-91be812d00fa.gif)

**Comment by alexr00** [comment]
This change only impacts the simple file dialog. We let the system file dialog do whatever it's going to do.

**Comment by weinand** [comment]
@alexr00 BTW, this problem does not occur in Stable.
