### ISSUE TITLE
Use more prominent focus indicator in trees

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95768]
From https://github.com/microsoft/vscode/issues/93916

The different shades of backgrounds in the explorer are a little confusing:

![image](https://user-images.githubusercontent.com/2193314/79865698-6f0eed80-8390-11ea-8113-9d5633392eb5.png)

A border could be nicer and more obvious which is the special item, it also aligned with Windows Explorer:

![image](https://user-images.githubusercontent.com/2193314/79865658-5e5e7780-8390-11ea-93de-26bd8cf4e5c9.png)
![image](https://user-images.githubusercontent.com/2193314/79865665-60283b00-8390-11ea-9956-e5a5303d4301.png)

Related: https://github.com/microsoft/vscode/issues/95767

**Comment by joaomoreno** [comment]
What does Finder do?

**Comment by joaomoreno** [comment]
Also, this will affect users of the list/tree which use it in strange ways, outline for example. This is a *bit* item.

**Comment by Tyriar** [comment]
Finder doesn't distinguish the items:

<img width="217" alt="Screen Shot 2020-04-21 at 7 22 55 AM" src="https://user-images.githubusercontent.com/2193314/79877299-ecdaf500-83a0-11ea-910a-9ac2384d97a0.png">

When right clicking everything gets a white outline:

<img width="352" alt="Screen Shot 2020-04-21 at 7 23 24 AM" src="https://user-images.githubusercontent.com/2193314/79877363-fe240180-83a0-11ea-8ccb-7eb1c18cfc2c.png">

Right clicking something not in the selection will get a blue outline:

<img width="234" alt="Screen Shot 2020-04-21 at 7 23 47 AM" src="https://user-images.githubusercontent.com/2193314/79877404-0bd98700-83a1-11ea-8015-0b7d888dddb0.png">

**Comment by akbyrd** [comment]
Windows resets selection on right click

![Stupid Highlight 2](https://user-images.githubusercontent.com/484784/83901287-5aec3900-a70f-11ea-8f07-46c14e08e3f3.gif)

Windows also changes selection when you use the arrows keys

![Stupid Highlight 3](https://user-images.githubusercontent.com/484784/83901504-b8808580-a70f-11ea-8624-d046f1b6dca9.gif)

In contrast with vscode which leaves a confusing persistent selection behind

![Stupid Highlight](https://user-images.githubusercontent.com/484784/83458828-0c415500-a418-11ea-98b6-0f81c6c9f79f.gif)

**Comment by joaomoreno** [comment]
This is now fixed
