### ISSUE TITLE
consider to add a table view for variables and watches

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#95766]
With the arrival of more flexible window/workbench layout, debug views are no longer constrained by narrow vertical layout arrangement. A variable view can now be moved to the horizontal panel:

<img width="1459" alt="2020-04-21_13-13-34" src="https://user-images.githubusercontent.com/1898161/79859924-16604480-83d2-11ea-99e9-23a2c8fbe5f7.png">

This makes it possible to explore a table view for the debugger's variables and  watches views.

**Comment by isidorn** [comment]
We decided to go another path for this via custom webviews thus closing this.
