### ISSUE TITLE
find in files - inconsistency in marking results as "dirty"

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#95779]
BTW looks like there is inconsistency in marking results as "dirty" - removing file from result prevents next search to be performed immediately (requires <kbd>Enter</kbd> ), but removing one match from file that has several - allows immediate search.

_Originally posted by @IllusionMH in https://github.com/microsoft/vscode/issues/91901#issuecomment-617222704_

**Comment by IllusionMH** [comment]
Looks like middle ground and place where logic is missing is https://github.com/microsoft/vscode/blob/652bd167ef6a828303e72b8c84f96b3ba1ee5edd/src/vs/workbench/contrib/search/common/searchModel.ts#L580-L595

This one always receives `FileMatch` and can only calculate if whole file was added/removed, but doesn't know if it was "updated" therefore won't be handled later
https://github.com/microsoft/vscode/blob/652bd167ef6a828303e72b8c84f96b3ba1ee5edd/src/vs/workbench/contrib/search/common/searchModel.ts#L721-L723

It feels like `onFileChange` should also receive optional parameter - changed `Match` and verify if this match is in its list of removed lines. Is it proper fix or wrong approach?

**Comment by JacksonKearl** [comment]
Ended up making it so the file match will explicitly include whether results are removed in its onchange event.
