### ISSUE TITLE
Suddenly unable to open files, settings or anything else

### ISSUE THREAD

**Issue by ghostrib** [microsoft/vscode#95772]
Issue Type: <b>Bug</b>

I don't have a lot steps to reproduce. It just seemed to happen out of nowhere. I have been working on a project every day using VS Code. This morning I'm working and suddenly when I try to switch tabs to another open file, I'm unable to do so and receive this message in the bottom right corner of the screen. `Unable to open 'colors.js': Cannot read property 'other' of null. `I disable all extensions and tried again. Still doesn't open anything. I quit the program and restarted. Didn't help either. When I tried to open a file after restarting, I received the same error message as before as well as a new but similar one. `Unable to open 'colors.js': Assertion Failed: argument is undefined or null.` I am able open the sidebar and and see the contents of folders. But that's all I can do. Any file I try to open, new or old I get these errors. Let me know if you need any more information.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3330S CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by sbatten** [comment]
@ghostrib can you run `Developer: Toggle Developer Tools` and share any errors in the console?

**Comment by bpasero** [comment]
This probably is https://github.com/microsoft/vscode/issues/94931

**Comment by sbatten** [comment]
@ghostrib let us know if you believe it is something different.
