### ISSUE TITLE
Graphical distortion of the environment

### ISSUE THREAD

**Issue by joseluis240** [microsoft/vscode#95770]
Issue Type: <b>Bug</b>

When I open the Visual Studio Code and I move the mouse the graphical environment becomes distorted and worse.

Another case similar is...
https://github.com/microsoft/vscode/issues/90021

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (3.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.9.1
flutter|Dar|3.9.1
vscode-language-pack-es|MS-|1.44.2
awesome-flutter-snippets|Nas|2.0.3

</details>

**Comment by deepak1556** [comment]
Can you provide a bit more info,

1) Did this appear only with `1.44.2`, was it working before ?

2) Does the issue repro with hw acceleration disabled https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

3) Can you also try our exploration build https://github.com/microsoft/vscode/issues/94074#issuecomment-607079209 and see if the issue repros.

4) Please a attach a video demo showing the issue, specifically which component is of the editor gets distorted.

Thanks!

**Comment by joseluis240** [comment]
180/5000
 Desktop Screenshot 2020.04.20 - 22.39.06.79.png
<https://drive.google.com/file/d/1snEefVfxQm7smL8-nHgfCbqek1oLkUoj/view?usp=drive_web>
 Desktop Screenshot 2020.04.21 - 10.42.44.99.png
<https://drive.google.com/file/d/1IIF_8fO8r-Pq3bZFNmHy-Y4p9-LAcDFq/view?usp=drive_web>
 Distortion VSC.mp4
<https://drive.google.com/file/d/1Qa66Fa-DiyXi88yFFJRfgetKWXFyST20/view?usp=drive_web>
I attach video and images about the problem. This problem did not give me
with the previous version. I have tried to change *argv.json* file as
advised but it does not work.

**Comment by deepak1556** [comment]
I don't have access to those image files, also where you able to try the exploration build https://github.com/microsoft/vscode/issues/94074#issuecomment-607079209 and see if the issue repros ?

**Comment by joseluis240** [comment]
Sorry, you can try again please! now I accept sharing this video in google
drive

**Comment by deepak1556** [comment]
Thanks this seems to be same issue as https://github.com/microsoft/vscode/issues/94523 , the exploration builds should fix this for now.

Also in the video I see that you are not restarting code after setting `"disable-hardware-acceleration": true`. Can you please restart for the configuration to apply.

**Comment by joseluis240** [comment]
Yes, I restarted multiple times after change to disable gpu acceleration
but it didn't work. I just try your exploration build and I install spanish
language extension (all ok). After that I install flutter extension (and
suddenly the GUI was wrong with distortions... Could this extension make
damage to displays?

**Comment by deepak1556** [comment]
> After that I install flutter extension (and
suddenly the GUI was wrong with distortions... Could this extension make
damage to displays?

Oh thats interesting, can you try uninstalling the extension in stable build and see if the issue goes away ?

**Comment by joseluis240** [comment]
I just uninstall all extensions in stable build and continue with problem!
I uninstall and restart one-to-one all extensions but it doesn´t work. I
can't undestand.

**Comment by deepak1556** [comment]
Is this still an issue with latest insiders https://code.visualstudio.com/insiders ?
