### ISSUE TITLE
Error: there is no registered task type 'Java'. Did you miss to install an extension that provides a corresponding task provider?

### ISSUE THREAD

**Issue by 395053994** [microsoft/vscode#95774]
Issue Type: <b>Bug</b>

Error: there is no registered task type 'Java'. Did you miss to install an extension that provides a corresponding task provider?

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

Error: there is no registered task type 'Java'. Did you miss to install an extension that provides a corresponding task provider?
![bug33333333333333333333](https://user-images.githubusercontent.com/27546390/79873381-9f4e9e80-8419-11ea-892a-7c128dab7b9c.png)

What caused this error? ? ?

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|9.59GB (4.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|2.1.5
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.4.0
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.1
comment-translate|int|1.4.2
vuejs-extension-pack|mub|1.2.1
color-highlight|nau|2.3.0
vetur|oct|0.24.0
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.16.0
vscode-manifest-yaml|Piv|1.16.0
vscode-spring-boot|Piv|1.16.0
java|red|0.60.0
vscode-xml|red|0.11.0
vscode-yaml|red|0.7.2
vue-vscode-snippets|sdr|1.9.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2
vscode-spring-initializr|vsc|0.4.6
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
Can you share repro steps?

**Comment by 395053994** [comment]
You will receive this message in the output window when you start the vscode Java maven project. . .


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"SteVen Batten"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 凌晨3:20
收件人:&nbsp;"microsoft/vscode"<vscode@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vscode] Error: there is no registered task type 'Java'. Did you miss to install an extension that provides a corresponding task provider? (#95774)





 
Can you share repro steps?

**Comment by sbatten** [comment]
looking at the maven extension, I do not see a task type of java. Rather, generated tasks use the type `shell`. Can you share your `tasks.json`, or which task you are running?

**Comment by gvsandeep2647** [comment]
Facing the same issue.
Just trying to run a simple gradle project.
In the output tab:
```
Error: there is no registered task type 'Java'. Did you miss to install an extension that provides a corresponding task provider?
```

Terminal Output:
```
e7a7dba6 Refreshing Maven model:  [0/-1]
b1ca8343 Repository registry initialization [Done]
706795a3 Updating indexes [Done]
```
