### ISSUE TITLE
Compact nested directory formatting does not persist after rename

### ISSUE THREAD

**Issue by guywaldman** [microsoft/vscode#95771]
- VSCode Version: 1.44.2
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create a folder with a nested path (i.e. `a/b`), which should be displayed in the file explorer like so:
    
    ![image](https://user-images.githubusercontent.com/6546430/79869997-f2f5c380-83ea-11ea-885b-ac34eed94975.png)

2. Rename the `a` folder to `aa` and the compact nested hierarchy formatting is not persisted:

    ![image](https://user-images.githubusercontent.com/6546430/79870106-1fa9db00-83eb-11ea-9d72-7ce9735fa816.png)

Expanding the folder displays the nested structure as expected:

![image](https://user-images.githubusercontent.com/6546430/79870182-436d2100-83eb-11ea-963a-3db02a199102.png)

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by joaomoreno** [comment]
This is because the folder is new and new folders are always collapsed. @isidorn Could fix it in the Explorer.

**Comment by isidorn** [comment]
Agree with this limitation. No plan to fix this or next milestone thus assigning to Backlog. Clean PR which fixes this is welcome

**Comment by guywaldman** [comment]
@isidorn I'll give this a shot next week or so 🙂
