### ISSUE TITLE
The window has crashed

### ISSUE THREAD

**Issue by algv** [microsoft/vscode#95777]
Version: 1.44.2 (system setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:33:57.013Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT ia32 10.0.17763

Steps to Reproduce:
1. write code
```js
var buffer = Buffer.alloc(1*1024*1024*50 - 1, "1");
const str = buffer.toString();
console.log(buffer.length);
```

2. start debug

3. show "str"
![crash](https://user-images.githubusercontent.com/16474118/79877579-1160bc80-83f5-11ea-9936-f33aa5727b90.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
Thanks for the issue, can you try out [our new debugger](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly) and see if it fixes this for you?

**Comment by algv** [comment]
new debugger
![изображение](https://user-images.githubusercontent.com/16474118/79952249-cee5c100-8482-11ea-9bc5-db2501855610.png)

```json
launch.json:
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Mocha",
      "type": "node",
      "request": "launch",
      "program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
      "stopOnEntry": false,
      "args": [
        "test/signed_data_big.js"
      ],
      "cwd": "${workspaceRoot}",
      "runtimeExecutable": null,
      "runtimeArgs": [
        "--nolazy"
      ],
      "env": {
        "NODE_ENV": "development"
      },
      "sourceMaps": false,
      "outFiles": "${workspaceRoot}/buildjs",
    },
  ]
}

```

**Comment by connor4312** [comment]
`outFiles` should be an array rather than a string

**Comment by algv** [comment]
Now with debugger work nice. But if change code and alloc ~100mb on start debug зrocess exited with code 3221226505

**Comment by algv** [comment]
![322](https://user-images.githubusercontent.com/16474118/80001972-b0ee7f80-84c7-11ea-9dca-b35ea2983c53.gif)

**Comment by connor4312** [comment]
This is the process running out of memory when it's inspected. Not ideal, but not avoidable. Node.js doesn't give us a head's up before it runs out of memory, and internally we must enumerate all properties in order to inspect array values.
