### ISSUE TITLE
Arrow keys not working in R session in terminal

### ISSUE THREAD

**Issue by darthVade7** [microsoft/vscode#95776]
Issue Type: <b>Bug</b>

**steps to reproduce:**
-   install R on your system
-   Configure the path variable
-   launch vscode and in the embedded terminal window, run 'Rterm'
-   In the launched R interpreter session, try 2-3 basic operations like assigning variables values e.g. : a = 1
-   Now try arrow keys (up and down) to go to previous commands/operations or (using left-right arrow) to move the cursor in currently entered text. It won't work.

**Where does it work?**
- If you launch a 'Rterm' in system PowerShell/cmd (outside visual studio code), it works just fine.
- P.S. previously it worked just fine in vs code on windows v1809. The issue came after I have upgraded my system to Windows 1909.
- It works fine on ubuntu even in vs code.

**tried options**

- Removing vscode and all of its associated files in the 'users' directory 
- Downgrading vscode to older versions

**system info**
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
python|ms-|2020.3.71659
atom-keybindings|ms-|3.0.6
LiveServer|rit|5.6.1

</details>

**Comment by Tyriar** [comment]
Can you try reproduce this in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps if it happens?

Also make sure the Windows Enable Conpty setting is set to true.

**Comment by darthVade7** [comment]
windowsEnableConpty is set to true,
As you have said I did install windows terminal and faced the same issue

**Comment by Tyriar** [comment]
Please report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps then 🙂
