### ISSUE TITLE
While installing VS code, it is showing a path and an error that " an error occurred while rename a file in directory destination".

### ISSUE THREAD

**Issue by Virenderrrrr** [microsoft/vscode#95773]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Virenderrrrr** [comment]
While installing the latest version of vs code it is showing a path and an error that is " an error occurred while rename of file in directory destination". Please help me.

**Comment by joaomoreno** [comment]
Can you show me a screenshot?

**Comment by Virenderrrrr** [comment]
![Capture](https://user-images.githubusercontent.com/51049628/80101580-39842300-858f-11ea-8ff5-1ba04b0feaa1.PNG)
here you go @joaomoreno

**Comment by joaomoreno** [comment]
Can you try out system setup? https://code.visualstudio.com/docs/?dv=win64

**Comment by Virenderrrrr** [comment]
It's still showing the same error.

**Comment by Virenderrrrr** [comment]
On the top it is showing Visual Studio Code (Unsupported)...
and even I open editor it is showing that " extension host terminated unexpectedly".
Please anyone help.

**Comment by joaomoreno** [comment]
> Visual Studio Code (Unsupported)

This means you either did not install VS Code from https://code.visualstudio.com/ or something in your system is messing with the VS Code installation. In any case we can't offer support for that, sorry!

Please try asking this question in StackOverflow.
