### ISSUE TITLE
Rust syntax highlighting breaks with raw strings in attributes

### ISSUE THREAD

**Issue by ExoticMatter** [microsoft/vscode#95782]
VSCode Version: 1.44.2

When raw string literals that use `##`s appear in attributes in a Rust file, syntax highlighting breaks.

Steps to Reproduce:

1. Copy the following code into a Rust source file:

```rust
#[cfg(feature = r#"""#)]
const _: () = ();
```

You will get something similar to the following:

![Screenshot_20200421_121815](https://user-images.githubusercontent.com/7787686/79883411-43a8f480-83ca-11ea-8d5b-987d33067328.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Looks like that's not a permitted raw string literal because double quotes are not permitted in raw string literals: https://rahul-thakoor.github.io/rust-raw-string-literals/
https://doc.rust-lang.org/reference/tokens.html#raw-string-literals

**Comment by ExoticMatter** [comment]
Raw string literals can contain double quotes by surrounding the opening and closing quotes with an equal number of pound signs, as in `r#""Hello""#`, `r##""Hello""##`, etc.

>All Unicode characters contained in the raw string body represent themselves, the characters U+0022 (double-quote) (except when followed by at least as many U+0023 (#) characters as were used to start the raw string literal) or U+005C (\) do not have any special meaning.
>
>Examples for string literals:
>
>```rust
>"foo"; r"foo";                     // foo
>"\"foo\""; r#""foo""#;             // "foo"
>
>"foo #\"# bar";
>r##"foo #"# bar"##;                // foo #"# bar
>
>"\x52"; "R"; r"R";                 // R
>"\\x52"; r"\x52";                  // \x52
>```

Such literals are already highlighted correctly in VSCode when used outside of attributes, which can be demonstrated by pasting the following snippet into a Rust source file:

```rust
fn main() {
    println!(r#""Hello, world!""#);
}
```

**Comment by alexr00** [comment]
Thanks for the additional info! Moved to the owning repo: https://github.com/zargony/atom-language-rust/issues/151
