### ISSUE TITLE
Bot proposal: Generic labeller

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95786]
There is currently `/needsMoreInfo` but this bugs me as I add it to saved replies which has a nicely crafted message about needing more information and then the bot comes in with their own generic one. We should solve this problem more generically and just be able to add arbitrary labels to an issue this way.

That way I could do things like this:

```
/label needs-more-info integrated-terminal
/label integrated-terminal integrated-terminal-conpty upstream 
```

We have some labels that have spaces and for those I think we should support quotes similar to how a bash does it:

```
/label needs-more-info "custom editors"
```

**Comment by aeschli** [comment]
Is there a syntax for removing labels? :-)

**Comment by Tyriar** [comment]
@JacksonKearl  `/label -label -"needs more info"` would make sense

**Comment by JacksonKearl** [comment]
@Tyriar Yeah that makes sense.

And looks like the fix I thought I made to not recursively throwing errors didn't actually work... 🙈🙉🙊

**Comment by JacksonKearl** [comment]
#96600
