### ISSUE TITLE
Wrong icon for CompletionItemKind (method)

### ISSUE THREAD

**Issue by cynecx** [microsoft/vscode#95787]
```
Version: 1.45.0-insider
Commit: b83339a3a7bd8e3ec8a8b79deda9c37e0d91f094
Date: 2020-04-21T05:32:26.392Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.6.6-arch1-1
```

Steps to Reproduce:

1. Insert this typescript code in an empty editor:
```typescript
class Test {
    foo() {

    }
}

let a = new Test();
a.<|> // <|> is the cursor
```

2. Try to trigger the auto-completion. Something like this should show up:

![image](https://user-images.githubusercontent.com/5961244/79891383-31967880-8401-11ea-968c-827e764d5be5.png)

Notice how the completion item kind icon is wrong (At least I think it's wrong, I don't remember seeing the "property" icon for methods).

Does this issue occur when all extensions are disabled?: Yes

**Comment by cynecx** [comment]
Nvm, it seems that the master branch already has a fix.

**Comment by gjsjohnmurray** [comment]
#95715
