### ISSUE TITLE
Open the documentation (ala `show hover`) in a pane

### ISSUE THREAD

**Issue by NightMachinary** [microsoft/vscode#95784]
I like to be able to see the documentation of the symbol at cursor using a keyboard shortcut. I know of the command `editor.action.showHover`, but I can't scroll that popup's contents using the keyboard. In fact, I prefer to have a documentation pane open at the right side that just shows the docs for anything the cursor is on.

It is also imperative that this pane supports wrapping the text. Intellij IDEA has a LOT of problems with this wrapping thing which makes their documentation pane pretty useless unless your monitor is huge.

Here is a screenshot of `show hover`:
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/rWhwf.png

**Comment by jvesouza** [comment]
@NightMachinary I don't know if you use a screen reader, and if you do, I don't know which one, but if I understood correctly, recently something similar to what you describe was implemented in Orca. I press ctrl + k ctrl + i with the cursor on the desired element and the documentation appears. I can use the arrows to browse the documentation.
Please excuse me if I have the wrong understanding.

**Comment by isidorn** [comment]
Exactly what @jvesouza just said. Ctrl +k, ctrl + i passes focus the hover.
For putting the hover documetion in the side view, this could be done by the extension. 
Though we can leave this open as a feature request for now.

**Comment by NightMachinary** [comment]
@isidorn @jvesouza  It doesn't pass the focus for me. I also don't get what 'screen reader' is. I don't use one.

**Comment by octref** [comment]
Scrolling -> #93611
I don't think we'll consider adding a "documentation pane" anytime soon, as most people seem to be happy with current inline hover.
