### ISSUE TITLE
VsCode Variables Fail with Symlinks

### ISSUE THREAD

**Issue by egarson** [microsoft/vscode#95785]
Issue Type: <b>Bug</b>

Add a symlink at top-level to a folder underneath `test/`, for example `test/widget_tests`, and add a file there. So, we have `./test`, `./test/widget_tests` (the real directory) and `./widget_tests` (symlink pointing to `./test/widget_tests`).

Next, add a new .vscode/launch.json configuration that 'uses' the symlinked directory:
```
      {
         "name": "Widget Integration Tests",
         "type": "dart",
         "request": "launch",        
         "program": "./widget_tests/${fileBasename}",
         "args": [
            "--no-pub",
            "--flavor",
            "staging"
         ],
      },
```
Now, select the widget_test file in the Explorer and invoke the new menu item. The goal of course is simply to pass the widget test file to `flutter run` (yes: *run*, not *test*).  Unfortunately, VSCode complains about fileBasename being unresolvable: "Launch config property 'program' has unresolvable variable ${fileBasename}". I think the symlink is to blame, unless I have misunderstood the use of these variables?

And thanks for an awesome IDE.

VS Code version: Code - Insiders 1.45.0-insider (ec0d19789f89d4c25895f4a0cf364276cfb0c6ed, 2020-04-20T05:59:50.147Z)
OS version: Linux x64 5.3.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4311)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.58GB (9.97GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|11.1.0
flutter-snippets|ale|2.0.0
dart-code|Dar|3.9.1
flutter|Dar|3.9.1
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
pubspec-assist|jer|0.3.6
firebase-explorer|jsa|0.3.3
vscode-emacs-friendly|lfs|0.9.0
flutter-tree|mar|1.0.0
goto-next-previous-member|mis|0.0.5
awesome-flutter-snippets|Nas|2.0.3
hide-gitignored|npx|1.1.0
material-icon-theme|PKi|4.0.1
explorer-exclude-vscode-extension|Red|1.2.0

(3 theme extensions excluded)

</details>

**Comment by weinand** [comment]
This works fine for me in VS Code 1.50

**Comment by egarson** [comment]
Thank you, this has indeed been fixed.
