### ISSUE TITLE
Getting Message after using few minutes VS Code "The window is no longer responding"

### ISSUE THREAD

**Issue by himanshu-a-rana** [Microsoft/vscode#9578]
- VSCode Version: 1.3.0
- OS Version: Windows 7

Steps to Reproduce:

1. 
![the window is no longer responding](https://cloud.githubusercontent.com/assets/10171747/17021596/a4757a1e-4f66-11e6-8cbc-db729a39a7b8.PNG)

2. After using some VS Code for few minutes it displays attached message.

**Comment by himanshu-a-rana** [comment]
I think this message displays due to package CSS Class Hint

**Comment by kieferrm** [comment]
#9519 mentions something similar.

@himanshu-a-rana do you have a sample workspace that shows this behavior?  What are the exact steps, i.e. what file is open, where is the cursor, what do you type, etc.

Does it happened when you disabled all extensions you have installed? You can start vscode with code --disabled-extensions from the command line to verify that.

**Comment by himanshu-a-rana** [comment]
After uninstalling 'CSS Class Hint' extension, VS Code is stable. Error was not reproduced.
