### ISSUE TITLE
Remote Explorer reconnect is problematic

### ISSUE THREAD

**Issue by john-aws** [microsoft/vscode#95788]
- VSCode Version: 1.44.2
- OS Version: OS X 10.14.6

Steps to Reproduce:

1. launch Remote Explorer, connect to remote host via SSH 
2. make some edits, save them
3. close laptop, come back later (next morning in my case)
4. make more edits to remote files, try to save edits, fail
5. find that you are disconnected with no way to re-connect and avoid losing your edits

The Remote Explorer's SSH Targets pane shows no entries. Refreshing it shows no entries.

Switching to another running instance of VS Code and restarting the connection process, choosing the same hostname, and re-opening the same folder on the remote simply switches focus to the VS Code instance that's disconnected from the remote host and provides no help in reconnecting.

The Remote Explorer status shows 'Disconnected from SSH: hostname'. Clicking on that and choosing "Remote-SSH: Connect to host" appears to do nothing.

The only option available at this point seems to be to quit and restart VS Code completely, and then rely on it to reconnect and bring up the dirty buffers for you to save. That does seem to work, but it's not ideal.

Does this issue occur when all extensions are disabled?: Not tested

**Comment by ykfq** [comment]
Facing same problem on windows 10 with vscode version `1.44.2`.
Downgrade to `1.43.2` and now its working fine.

**Comment by alexdima** [comment]
@john-aws On step 3., when you return to the laptop. Normally, a blocking dialog that you really cannot miss shows up letting you know you are disconnected. Is that not the case for you?

**Comment by john-aws** [comment]
I never saw that dialog, but let me re-test and get back to you.

**Comment by john-aws** [comment]
Confirmed that I do now see the 'Attempting to reconnect' dialog and, after 2 cycles, it was able to reconnect. I suppose there is a chance this dialog did previously appear and was immediately cancelled by an errant key press while I was looking at different monitor. Happy for this to be closed and if I can provide a consistent repro I will re-open with more details.
