### ISSUE TITLE
Commands for terminal control in the debugger

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [microsoft/vscode#95799]
Issue Type: <b>Feature Request</b>

It would be great to be able to send commands to the debugger console similar to those supported by any other first class terminal:

Most notably things I see missing:

* Go back/forward in the command history (e.g. `Ctrl+p` / `Ctrl+n`)
* History search based on partial matches, e.g. as with `readline` in the shell, see e.g. [this](https://askubuntu.com/questions/59846/bash-history-search-partial-up-arrow), (e.g. also  `Ctrl+p` / `Ctrl+n`)
* Commands to copy / paste text in the REPL from / to the debug console
* Command to **exit** the REPL itself, _while_ keeping the _focus_ and _cursor_ in the debug console, so that one can **scroll** up and generally _navigate_ the screen history of the debugging console to e.g. copy / paste text from the history debugging console window. This is equivalent to e.g. the [copy-mode in tmux](https://tmuxguide.readthedocs.io/en/latest/tmux/tmux.html#copy-mode), or e.g. the ["char mode" in a terminal within Emacs](https://www.gnu.org/software/emacs/manual/html_node/emacs/Term-Mode.html).

For cross-reference, this was also also asked [here](https://stackoverflow.com/questions/61192348/keyboard-shortcuts-for-the-vscode-debugging-console).

VS Code version: Code - Insiders 1.45.0-insider (b83339a3a7bd8e3ec8a8b79deda9c37e0d91f094, 2020-04-21T05:38:43.781Z)
OS version: Darwin x64 19.4.0

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by amelio-vazquez-reina** [comment]
Thanks @isidorn  That's great to hear. On this note, the keybindings `Up` and `Down` specifically already go back / forward in the command history and they are pretty fundamental. Are they tied to any particular command ID? (or is there any way to configure them?)

**Comment by isidorn** [comment]
@amelio-vazquez-reina yeah the commands are `history.showPrevious` and `history.showNext` and you should be able to customise them.
Code pointer https://github.com/microsoft/vscode/blob/1af3b9dce3d2ead4c3c0bb010dc47a4752af13d1/src/vs/platform/browser/contextScopedHistoryWidget.ts#L78
