### ISSUE TITLE
Clone Repository - Repository does not exist error

### ISSUE THREAD

**Issue by nrayburn-tech** [microsoft/vscode#95790]
Issue Type: <b>Bug</b>

I am attempting to clone a repository from inside of the explorer, but receive a fatal git error.
```
git clone 'Clone%20from%20URL' does not exist
fatal: repository 'Clone%20from%20URL' does not exist
```
1. Open new editor without a workspace/folder
2. Open the command palette, use Git: Clone.
3. Enter URL for repo. `https://github.com/microsoft/vscode.git`
4. Browse to folder location to create the repo.
5. Click `Select Repository Location`.
6. Error is thrown.

VS Code version: Code - Insiders 1.45.0-insider (b83339a3a7bd8e3ec8a8b79deda9c37e0d91f094, 2020-04-21T05:38:43.781Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.11.0
vscode-eslint|dba|2.1.5
EditorConfig|Edi|0.14.5
prettier-vscode|esb|4.4.0
debugger-for-chrome|msj|4.12.6
vetur|oct|0.24.0
vscode-import-cost|wix|2.12.0

</details>

**Comment by joaomoreno** [comment]
This was broken for 1 day in `master`, it has been fixed since. Thanks for filling!
