### ISSUE TITLE
Support for TabCompletion

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#9579]
We have a first cut for the 'tab completion'-feature which is about inserting a snippet when matching a prefix and pressing <kbd>Tab</kbd>.

![jul-21-2016 14-25-12](https://cloud.githubusercontent.com/assets/1794099/17022702/cfd18462-4f4f-11e6-9d2b-036aaee3ad14.gif)

Open questions:
* by default we have '24x7' Intellisense. combined with the new `snippetSuggestions = top` setting you can achieve the same
* for <kbd>Tab</kbd> to work we need to know snippets statically which isn't true for completions of [type snippet](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2163) that come from contributed completion providers (IMO this is a corner case)

**Comment by jrieken** [comment]
_ghetto tab completion_ using the `snippetSuggestions` property

![jul-21-2016 14-32-25](https://cloud.githubusercontent.com/assets/1794099/17022845/a3d5b5b2-4f50-11e6-843a-199ff8004a5e.gif)

**Comment by jrieken** [comment]
@Microsoft/vscode looking for feedback on this

**Comment by d4rkr00t** [comment]
I've tested it a bit. And it works great, thanks so much!
