### ISSUE TITLE
theme gray space in editor

### ISSUE THREAD

**Issue by J131-dev** [microsoft/vscode#95793]
Issue Type: <b>Bug</b>

In the editor window there are light areas around (and under) the code lines, except where the line highlighter is.  Around the highlighter there is a chunk of ~9 lines that are the same color as the theme's background color.

This happens in all pre-installed themes except for the high contrast.

I am unsure how to reproduce this, other than maybe it is due to a high display resolution (3840 x 2160).

![screenshot](https://user-images.githubusercontent.com/3783439/79902285-d780bd80-83d6-11ea-95ab-431b74dd57d8.png)

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

Extensions: none

**Comment by sbatten** [comment]
if you run vs code (close all instances first) with `code --user-data-dir newFolder` where `newFolder` is an empty folder, does this reproduce?

**Comment by IllusionMH** [comment]
Do you have HDR enabled?
Looks very similar to #93338.

You can try if it's fixed if you launch VS Code with next flags `--force-color-profile srgb` or`--disable-gpu`

**Comment by J131-dev** [comment]
Yes I do have HDR on, and launching with '--force-color-profile srgb' fixes the issue for that session - closing and relaunching without the flag reproduces the issue.

I found that by setting the program to run in compatibility mode for Windows 8 solves the problem.

**Comment by IllusionMH** [comment]
You can add it permanently following steps described in https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration but set `"force-color-profile": "srgb"` instead.

Most likely should be merged with #88491

/cc @deepak1556

**Comment by J131-dev** [comment]
Thanks, for the help!  Its a great IDE

**Comment by deepak1556** [comment]
Thanks @IllusionMH , yup this should be merged to https://github.com/microsoft/vscode/issues/88491
