### ISSUE TITLE
DAP Progress Indicator isn't removed on a failed launch request

### ISSUE THREAD

**Issue by awto** [microsoft/vscode#95800]
- VSCode Version: 1.45.0-insider
Commit: b83339a3a7bd8e3ec8a8b79deda9c37e0d91f094
Date: 2020-04-21T05:38:43.781Z 
- OS Version: OSX

Steps to Reproduce:

1. Clone https://github.com/awto/vscode-mock-debug.git
2. Run it as an extension, and launch some demo project
3. It supposed to report "the problem" on launch and the launch is aborted
4. But the progress indicator is kept running

Here is the code of the launchResponse:

```typescript
this.sendEvent(new ProgressStartEvent("LAUNCH", "before-1"));
await timeout(1000);
this.sendEvent(new ProgressUpdateEvent("LAUNCH", "before-2"));
await timeout(1000);
this.sendErrorResponse(response, 1000, "some problem");
this.sendEvent(new ProgressEndEvent("LAUNCH", "before-3"));
```

If the last `sendEvent` is moved to before `sendErrorResponse` everything works fine. 

This looks like a minor thing, I can always stop it manually before `sendErrorResponse` of course So no problems if you just close this. I report it if it is a part of some larger problems and it is also convenient to stop the progress in the handler's `finally` block. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
@awto thasnk for filling this. Yeah doing this inside a launch request is a bit of a corner case, thus we do not handle this that well.
Code pointer in case you are interested in a PR
https://github.com/microsoft/vscode/blob/86db1ec2acb0b38fe99fa253d707b7d6032eef16/src/vs/workbench/contrib/debug/browser/debugProgress.ts#L20

**Comment by awto** [comment]
@isidorn Thanks for the pointer, there is actually another thing which I cannot reproduce on the small test case yet, but on my adapter the progress randomly isn't shown at all. With this source pointer it maybe be easier to understand what happens. I'm not sure when I'll have enough time on this though, so probably it is worth closing this ticket for now.

**Comment by isidorn** [comment]
Ok, let's close the ticket and we can reopen later.
