### ISSUE TITLE
Terminal window will not grow beyond 4 lines (height) in Live Share session

### ISSUE THREAD

**Issue by daltschu22** [microsoft/vscode#95803]
- VSCode Version: 1.44.2
- OS Version: Windows 10 (Version 2004)

Steps to Reproduce:

1. Start a live share collaboration session. 
2. Join the newly created live share session.
3. As an attendee (not the host) request control of the terminal. 
4. Attempt to grow the terminal in height beyond 4 lines.
5. The window itself will grow, but the actual number of lines on screen do not.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Tyriar** [comment]
You can report this to live share, it might be by design.
