### ISSUE TITLE
Restart to Update Does not Update (Windows 10)

### ISSUE THREAD

**Issue by homestar9** [microsoft/vscode#95808]
I receive a notification to "restart visual studio code to apply the latest update", however after I click "update now" and VS Code restarts, I am prompted with the same notification.

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (12.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
tinypng|and|0.3.3
bracket-pair-colorizer-2|Coe|0.0.29
vscode-markdownlint|Dav|0.34.0
make-hidden|dev|3.0.3
gitlens|eam|10.2.1
auto-close-tag|for|0.5.7
beautify|Hoo|1.5.0
vscode-peacock|joh|3.7.0
vscode-cflint|Kam|0.3.4
vscode-cfml|Kam|0.5.3
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-docker|ms-|1.1.0
vsliveshare|ms-|1.0.2000
indent-rainbow|ode|7.4.0
vscode-coldbox|ort|0.1.0
vscode-commandbox|ort|1.0.2
vscode-testbox|ort|0.2.0
vscode-yaml|red|0.7.2
code-settings-sync|Sha|3.4.3
ignore-gitignore|stu|1.0.1
bracket-padder|via|0.2.0
vscode-icons|vsc|10.1.1
grammarly|znc|0.12.1

</details>

**Comment by joaomoreno** [comment]
Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by homestar9** [comment]
That did the trick, thank you!

It's strange because the normal auto-update feature worked for me a few months ago.

![image](https://user-images.githubusercontent.com/5341142/80136995-66b4df00-8557-11ea-8921-69c49949f9f7.png)
