### ISSUE TITLE
"Unable to resolve workspace folder" for path that includes ~ (tilde)

### ISSUE THREAD

**Issue by phaseOne** [microsoft/vscode#95809]
Issue Type: <b>Bug</b>

This is a regression from somewhere around the last release. Just noticed it after the latest update.

# Steps to reproduce

1. Create a `.code-workspace` file in `~/Documents`. Add paths that use the `~` (tilde) to reference the `$HOME` folder, e.g. `~/demorepo1`
2. Open the Workspace
3. Watch as the workspace folders fail to resolve

<img width="961" alt="Screen Shot 2020-04-21 at 4 51 23 PM" src="https://user-images.githubusercontent.com/1310985/79926584-2720b280-83f2-11ea-9fc9-d134ca860adb.png">

# System Details

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by phaseOne** [comment]
Noting that this bug also causes search to fail.

<img width="867" alt="Screen Shot 2020-04-22 at 11 44 20 AM" src="https://user-images.githubusercontent.com/1310985/80020889-9cda5c00-848e-11ea-8650-db05aa9398c3.png">

Reproducible on latest Insiders build.

I've also tried going back a few versions of the official releases, but it didn't fix the regression. Maybe this is an issue with a package dependency that's installed on first launch?

**Comment by aeschli** [comment]
To my knowledge, using `~` in workspace folders is not supported. @bpasero ?

**Comment by bpasero** [comment]
> To my knowledge, using ~ in workspace folders is not supported.

Yes, my understanding too.

**Comment by aeschli** [comment]
Closing as not supported.

**Comment by ppo** [comment]
@aeschli is there a supported way of referencing the home folder in a `.code-workspace`? (I tried `$HOME`, `${env:HOME}`, and `${env.HOME}`)  
And if not, can we transform this into a feature request? :wink:

**Comment by aeschli** [comment]
similar as  #44755
