### ISSUE TITLE
Settings Sync: use profile avatar

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#95804]
![image](https://user-images.githubusercontent.com/35271042/79923209-f177cb80-83e9-11ea-8ed2-241fc15627f8.png)

I would really love it if Settings Sync used my profile avatar from the account that I've logged in as. If there are multiple, default to the one that sync is connected to. If there is no avatar, use the default icon we use today. Also allow for the user to select their avatar if there are multiple avatars.

cc @Tyriar @kieferrm @roblourens

**Comment by Tyriar** [comment]
I have mixed feeling about this. I brought it up in a UX meeting months ago and if I remember right there was some negativity to the idea.

**Comment by sandy081** [comment]
Currently Accounts dropdown shows 

- All logged in accounts
- Preferences sync entry

If we are not intending to add other features, this can be used to represent sync. 
Another idea is to separate accounts and sync and add sync account as a new entry?

**Comment by sandy081** [comment]
After discussing with @jrieken we also came to similar idea of having separate sidebar entry for sync. 

- Showcase Preferences Sync viewlet as primary UI. Currently this viewlet is shown only when asked to show backup views. Make it primary and introduce more sections and actions - say connected machines, what is being synced and actions to turn off, nuke data, sync now etc., This will improve transparency and reliability.

Following @misolori 's initial suggestion we can use signed in user's avatar as icon for this entry.

**Comment by misolori** [comment]
I’m not sure how useful another activity bar entry for sync would be. I like the current approach with its minimal UI. You only ever need to access the backups in very specific scenarios and I like that it only shows up in that case.

I was simply suggesting that whenever we have an entry for a “signed in” account we should show the user’s profile photo instead of a generic icon.

**Comment by Tyriar** [comment]
It's common in browsers to merge sync and sign in into the same icon, another one would be too much clutter.

**Comment by jrieken** [comment]
> I would really love it if Settings Sync used my profile avatar from the account

Not a fan of looking at my face while code. Tho, we could add a "right click > hide gesture". Or use an icon theme for this 🤣

**Comment by sandy081** [comment]
The pain point that we are addressing here is to have a single UI (view) for managing sync related things like - configuring / turning off sync, seeing synced devices and data, actions like syncing now, showing logs and current Quick pick approach will be overloaded to support this.

Agreed that additional primary activity bar entry will be too much. How about clicking on `Preferences Sync is On` opens this viewlet?

**Comment by Tyriar** [comment]
> Not a fan of looking at my face while code.

:+1: to this.

**Comment by misolori** [comment]
> Not a fan of looking at my face while code. Tho, we could add a "right click > hide gesture"

I think the right-click to hide gesture should be added regardless. If you don’t want sync or to show accounts then it would be annoying to see that icon. 

Showing a user’s avatar is a very common thing that all major browsers support and VS also does. It’s another way of building confidence that you are signed in without having to click on anything. With the right-click option you can always hide this.

**Comment by misolori** [comment]
We discussed this today in our weekly Settings Sync meeting and agreed on the following:

- The account icon is primarily used for accounts and sync is there as an entry point, so it would be odd to use the sync profile avatar as a replacement
- We should allow users to hide account icon via right-click #97167
- We should explore using a richer ui for the account picker (similar to the notification pane) to make information clearer and more actionable #97168

Given the first point, it doesn't sound like surfacing the profile avatar to replace the account icon makes sense. Will rely on the third point (#97168) to take care of this and will close this issue.
