### ISSUE TITLE
file menu flips to left screen in multiscreen environment

### ISSUE THREAD

**Issue by jjmartin** [Microsoft/vscode#9580]
- VSCode Version: 1.3.1
- OS Version: Microsoft Windows [Version 10.0.10586]

Steps to Reproduce:

1. make 2 screens next to each other and put vscode on right screen, maximize
2.  open file menu

![image](https://cloud.githubusercontent.com/assets/607183/17023790/c11154d2-4f1a-11e6-8688-b0546bc875bb.png)

**Comment by kieferrm** [comment]
I'm guessing that's an Electron issue.

**Comment by bpasero** [comment]
@jjmartin  we just released a new insiders build with a newer Electron. maybe you could give that build a try to see if it fixes this issue.

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by jjmartin** [comment]
it did, thanks
