### ISSUE TITLE
Allow "launch" json setting to be placed into a "[language]": object.

### ISSUE THREAD

**Issue by GinoMan** [microsoft/vscode#95815]
Currently, VSCode supports having a "launch" object in settings.json which allows you to specify "tasks" that would normally be in "tasks.json" inside the config file. This is very useful as often you will want to use similar launch actions in multiple projects ("run the current file in the python interpreter", "open index.html in the browser", "launch node run", etc) but when you do that, all of the actions will appear regardless of the context of your particular project (so if you're writing a python program, you'll have "open index.html in browser" when there isn't any index.html). Some of these are not going to make any sense to do in that context. 

So the idea is that you can put "launch" inside a language block normally used for the editor and if you're editing a project that contains files of that language, then that option will appear in "run and debug". It may also be nice to add a "availableWhen" property in any "configurations" object that allows you to specify "if `__main__.py` exists" or "if `node_modules` exist". This would allow an even more robust per-language and even per-project-type configuration of tasks. Also, by framing it this way, if a project employs multiple types of code (e.g. a flask server that serves pages written with react), then everything will be there for react and for python.

**Comment by alexr00** [comment]
@GinoMan is this about launch or tasks?

**Comment by GinoMan** [comment]
I think ultimately, this is "launch", since the debug/run menu looks at the "launch.json" or the launch settings in the config file to populate that list. It would be useful to break that down further into languages so that if you're on a python file, then you can see python's launch options. If you're in a node project then you see node's launch options. Etc.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
