### ISSUE TITLE
Improve hover UX so moving point diagonally from highlight to hover doesn't clear over

### ISSUE THREAD

**Issue by greggman** [microsoft/vscode#95816]
It woudl be nice if the hover UX allowed the pointer to go diagonally up and right where it comes off the highlighted text and makes it to the hover. As it is the hover disappears because there is an instant where the pointer is neither on the highlighted text nor on the hover box

![hover-ux](https://user-images.githubusercontent.com/234804/79932233-fc813900-8487-11ea-8bc2-95a4e5755156.gif)

This has been a known issue for UX design since in the 1980s in particular going from a menu item to a submenu item and there are [various solutions](https://css-tricks.com/dropdown-menus-with-more-forgiving-mouse-movement-paths/).

I would be nice if hovers had some similar solution. Maybe a small delay (100ms?) before they disappear so when the mouse travels that small amount shown above they don't vanish. There is a settable delay before showing. Maybe a solution would be a delay for hiding as well?

**Comment by octref** [comment]
That's a nice thing to have. The reason it's disappearing is because your mouse moved outside of the word, but I agree a delay might make this better.

**Comment by legomushroom** [comment]
Tested this today on stable 1.95.3(f1a4fb) on Windows 11 and issue seems to be fixed due to the fact that the hide delay of the popup is much longer now, making it much easier to interact with. Please reopen if the behaviour still causes issues for you.
