### ISSUE TITLE
Terminal: Ability to pass Page Up / Page Down and possibly other keys directly to the terminal

### ISSUE THREAD

**Issue by Nowaker** [microsoft/vscode#95819]
Page Down (Linux) and Fn + Down (Mac) performs `workbench.action.terminal.scrollDown` action by default. This is great and it should stay like that.

However, there's situations when we need to pass the "Page Down" key to the underlying terminal. For example, when looking at a long `git diff` that uses a pager. Because Page Down key is hijacked by VSCode, there's no way to pass it to the underlying shell session when using the Terminal.

General idea: Please us to pass the keys that are normally hijacked by VSCode to the underlying shell session under certain conditions.

Specific ideas:

- Proposal 1: When Ctrl+Shift+[key] (Linux) or Fn+Shift+[key] (Mac) are pressed, pass [key] directly to the session. The most feasible solution for that would be a new keybinding, e.g. `workbench.action.terminal.passKeyCombination` = `Ctrl+Shift`.
- Proposal 2: Introduce keystroke action for each key, e.g. `workbench.action.terminal.sendKey.pageDown`, `...pageUp`, and so on, and allow us to bind any key (e.g. Ctrl+Shift+PageDown) to that action. Some reasonable defaults for Linux and Mac should be provided.

**Comment by Tyriar** [comment]
@Nowaker so the way this works is that the default is to pass everything through the terminal, however there is a setting `terminal.integrated.commandsToSkipShell` which is pre-populated with all terminal commands and a bunch of other ones that if the keystroke would activate one of those commands, it skips it.

There are 2 ways to workaround your problem:

The first is to unbind the command that you want to go to the shell by adding this to keybindings.json (notice the `-` in front of the command name):

```json
{
  "key": "pagedown",
  "command": "-workbench.action.terminal.scrollDown",
  "when": "terminalFocus"
},
{
  "key": "pageup",
  "command": "-workbench.action.terminal.scrollUp",
  "when": "terminalFocus"
}
```

You can then add other keystrokes to send it, eg.

```json
{
  "key": "ctrl+alt+pagedown",
  "command": "workbench.action.terminal.scrollDown",
  "when": "terminalFocus"
},
{
  "key": "ctrl+alt+pageup",
  "command": "workbench.action.terminal.scrollUp",
  "when": "terminalFocus"
}
```

An alternative way is to do something very similar to your second proposal. There is an existing [`sendSequence` command](https://code.visualstudio.com/docs/editor/integrated-terminal#_send-text-from-a-keybinding) that can send whatever you want to the terminal. I think this is using the right sequences for page up/down:

```json
{
  "key": "ctrl+shift+pagedown",
  "command": "workbench.action.terminal.sendSequence",
  "when": "terminalFocus",
  "args": { "text": "\u001b[6~" }
},
{
  "key": "ctrl+shift+pageup",
  "command": "workbench.action.terminal.sendSequence",
  "when": "terminalFocus",
  "args": { "text": "\u001b[5~" }
}
```

This last command is pretty advanced but it allows you do pretty much whatever you want 😃

**Comment by Tyriar** [comment]
> Page Down (Linux) and Fn + Down (Mac) performs workbench.action.terminal.scrollDown action by default.

Also FYI the default for defaults are ctrl+shift+up/down on Linux, cmd+alt+up/down on Mac. Maybe you have keybindings for these or a keymap extension?

https://github.com/microsoft/vscode/blob/dbfe5613ca423c52d9a93bc7fbb31c7a69c77c03/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L657-L666

**Comment by Nowaker** [comment]
@Tyriar Thanks for your guidance. The second option looks exactly like what I'm looking for! Sending any sequence is the goal, so that's great something like that already exists. That's awesome. Thank you.

Quick question: I'm seeing `KeyMod.CtrlCmd` in the source file you mentioned. Is it possible to use "ctrlcmd" directly in the keybindings.json? I maintain [my keybindings as a template](https://gitlab.com/Nowaker/dotfiles-vscode/-/blob/master/keybindings.template.jsonc) where a script replaces `$CTRL` with `ctrl` or `cmd` based on target platform. It'd be definitely an improvement if I could use `ctrlcmd` instead.

**Comment by Tyriar** [comment]
No you can't use CtrlCmd, but you can accomplish the same thing using `"when": "isMac"` or `"when": "!isMac"`. In the upcoming settings sync feature keybindings will be platform specific by default so you could probably retire your old system.

I prefer to maintain a platform agnostic setup keybindings file, here's a snippet from it:

```json
{ "key": "ctrl+shift+w",     "command": "workbench.action.closeAllEditors" },
{ "key": "cmd+shift+w",      "command": "workbench.action.closeAllEditors", "when": "isMac" },
{ "key": "ctrl+shift+o",     "command": "workbench.action.files.openFolder", "when": "!isMac" },
{ "key": "ctrl+r",           "command": "workbench.action.gotoSymbol" },
{ "key": "alt+-",            "command": "workbench.action.navigateBack" },
{ "key": "alt+shift+-",      "command": "workbench.action.navigateForward" },
{ "key": "ctrl+,",           "command": "workbench.action.openGlobalSettings" },
{ "key": "ctrl+k ctrl+s",    "command": "workbench.action.openGlobalKeybindingsFile" },
{ "key": "cmd+k cmd+s",      "command": "workbench.action.openGlobalKeybindingsFile", "when": "isMac" },
{ "key": "cmd+shift+,",      "command": "workbench.action.openRawDefaultSettings", "when": "isMac" },
{ "key": "ctrl+alt+o",       "command": "workbench.action.openRecent" },
{ "key": "ctrl+shift+r",     "command": "workbench.action.reloadWindow", "when": "!isMac" },
{ "key": "cmd+shift+r",      "command": "workbench.action.reloadWindow", "when": "isMac" },
{ "key": "ctrl+shift+i",     "command": "workbench.action.toggleDevTools", "when": "!isMac" },
{ "key": "cmd+alt+i",        "command": "workbench.action.toggleDevTools", "when": "isMac" },
{ "key": "ctrl+shift+q",     "command": "workbench.action.toggleMaximizedPanel" },
{ "key": "ctrl+0",           "command": "workbench.files.action.showActiveFileInExplorer" },
{ "key": "ctrl+shift+e",     "command": "workbench.files.action.focusFilesExplorer" },
{ "key": "ctrl+shift+x",     "command": "workbench.action.terminal.kill" },
{ "key": "ctrl+shift+j",     "command": "workbench.action.terminal.focusNext" },
{ "key": "ctrl+shift+k",     "command": "workbench.action.terminal.focusPrevious" },
{ "key": "ctrl+a",           "command": "workbench.action.terminal.selectAll", "when": "terminalFocus && !isMac" },
{ "key": "cmd+q",            "command": "-workbench.action.quit", "when": "isMac" },
{ "key": "cmd+q cmd+q",      "command": "workbench.action.quit", "when": "isMac" },
{ "key": "shift+f12",        "command": "editor.action.referenceSearch.trigger" },
```

If you end up using `isMac` which is way better imo you can set `"sync.keybindingsPerPlatform": false` to share the file between platforms. The features is up on [Insiders](https://code.visualstudio.com/insiders) if you want to try it out.

**Comment by Nowaker** [comment]
Thanks! I'll stay with my $CTRL approach for less code duplication and consistent generation. Do you think a feature request asking for support for CtrlCmd in keybindings.json would be plausible/reasonable for you and other VS Code devs, or probably a meh?

**Comment by Tyriar** [comment]
@Nowaker I doubt it would happen, as the `is<Platform>` keys accomplish a similar thing. Also most people edit keybindings via the UI now so I'd expect most improvements to work well there as well.

**Comment by Tyriar** [comment]
> I'll stay with my $CTRL approach for less code duplication and consistent generation

The benefit of moving away from that is you can use settings sync and no longer even need to maintain/run your script anymore.

**Comment by Nowaker** [comment]
> I doubt it would happen

Thanks for offering your opinion. In this case, I won't be creating a feature request for that. :)

> no longer even need to maintain/run your script anymore

I prefer "everything as code" approach while being stored in git repo, e.g. CI as code, Infrastructure as Code, Configuration as Code) so I'll continue using that, but thanks. :)
