### ISSUE TITLE
No way to come back from "Show all tasks" in task quick pick

### ISSUE THREAD

**Issue by doudou** [microsoft/vscode#95814]
Issue Type: <b>Bug</b>

- open the task quick pick
- select "show all tasks"

There are no entries to go back. Moreover, closing and re-opening the dialog still shows the whole task list sorted alphabetically (last used entry is not first)

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 5.0.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 3587)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|15.38GB (5.18GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
QML|bbe|1.0.0
vscode-glsllint|CAD|0.0.13
systemd-unit-file|coo|1.0.6
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.27.0
vsliveshare|ms-|1.0.2000
vetur|oct|0.24.0
ruby|reb|0.27.0
rock|roc|0.6.3
shader|sle|1.1.4
cmake|twx|0.0.17
vim|vsc|1.13.1
vscode-ansible|vsc|0.5.2
vscode-ruby|win|0.27.0

</details>

**Comment by alexr00** [comment]
Can you provide a screen recording of what you see? I didn't put a "back" option in "Show All Tasks..." because you now have all the tasks visible, whereas going back would only show you a subset of tasks again.

I do not see the full tasks list when I run the "Run Task" command, only when I do "Show All Tasks..." from within the "Run Task command".

**Comment by doudou** [comment]
So. More subtle that I initially thought.

The difference is between "Run Task" and "Run Build Task". The former seems to behave as expected. The latter, not so much. It's now only sorted alphabetically and not by recent. My muscle memory seems to have been using both interchangeably.

![vscode-run-build-task](https://user-images.githubusercontent.com/292/80108005-31f25900-8552-11ea-85e3-a49fb5813a36.gif)

**Comment by alexr00** [comment]
Interesting. I still can't get that behavior. I still see sorting by recent in Run Build Task. 
Can you provide a repository I can clone where you see this happen + list of extensions you have that are providing tasks (specifically that autoproj task)?

**Comment by doudou** [comment]
It's unfortunately more complicated than just cloning a repo.

Anyways, assuming an Ubuntu install, you'd need to run the script [from this gist](https://gist.github.com/doudou/43994afffae8e1267d8f7c1435019bb5) in an empty folder. It needs to install a bunch of things ruby-related.

Then, add the `base/cmake` folder a VSCode instance where [the Rock extension](https://marketplace.visualstudio.com/items?itemName=rock-robotics.rock) is installed.

Unfortunately there doesn't seem to be a way to disable all extensions while still letting the user re-enable some, so I can't check if the problem comes from a bad interaction between the rock extension and another.

![vscode-minimal-buildconf](https://user-images.githubusercontent.com/292/80229948-96cbb300-8627-11ea-8025-d506eeb5f12c.gif)

**Comment by alexr00** [comment]
Same as https://github.com/microsoft/vscode/issues/95971#issuecomment-619878851

**Comment by alexr00** [comment]
Same as https://github.com/microsoft/vscode/issues/95971

**Comment by doudou** [comment]
> Same as #95971

Not entirely it seems.

I've made sure that the type in `registerTaskProvider` matches the one in `TaskDefinition` (https://github.com/rock-core/vscode-rock/pull/72), which indeed fixed #95971

However, I still have some of the same behaviors:
- in `Run Build Task`: not sorted by recent.
- in `Run Task/Show All Tasks`: no "Go Back" button

**Comment by alexr00** [comment]
> in Run Build Task: not sorted by recent.

I see where the problem is. Trying to come up with a reasonable solution.

> in Run Task/Show All Tasks: no "Go Back" button

This is intentional. You now can see all tasks, why bother going back to the more limited view when you are already at the more powerful one.

**Comment by doudou** [comment]
> I see where the problem is. Trying to come up with a reasonable solution.

OK, thanks

> This is intentional. You now can see all tasks, why bother going back to the more limited view when you are already at the more powerful one.

I understood otherwise from one of your previous comments, but that's fine with me.

**Comment by alexr00** [comment]
@doudou thanks for you patience with this. I've merged a change that will be in the next insiders. Please let me know whether it works for you!

**Comment by doudou** [comment]
Just checked code-insiders, and it works fine there. I'm anxiously waiting for 1.45 now ;-) Thanks.
