### ISSUE TITLE
"Go back" Jumps to different editor when in split editor mode with same File

### ISSUE THREAD

**Issue by jannickj** [microsoft/vscode#95818]
- VSCode Version: 1.44.2
- OS Version: ubuntu 18.04

If you like split mode + Jump to definition then this feature/bug is very annoying.

If you have a file you are working on and you have two editors of that file open:
One for writing code and one for looking around / changing types.
Then if you "Go to definition" while coding (in your main editor), and jump to another file. 
Vscode is now treating your look around editor with the file you were working on as your main editor.
Meaning that now the "Go back" command will not reopen the file in your current editor but instead jump to your other editor.
The behavior is very unexpected/disrupting and feels very buggy.

Steps to Reproduce:

1. Open File A
2. Split Editor creating Editor A and Editor B both with File A
3. In Editor A run "jump to definition" in File A jumping to File B
4. In Editor A run "Go back" while on File B
5. Observe Editor B jumping to where you last were on Editor A

Does this issue occur when all extensions are disabled?: Yes

**Comment by jannickj** [comment]
@bpasero which issue is it a duplicate of? #83907 has nothing to do with this issue.

**Comment by bpasero** [comment]
Quite sure: https://github.com/microsoft/vscode/labels/workbench-history

**Comment by jannickj** [comment]
To anyone like me who could find the issue, the one that is related (but is having the problem show up in a different way) is: https://github.com/microsoft/vscode/issues/9526
