### ISSUE TITLE
vscode show wrong font color for the method keyword

### ISSUE THREAD

**Issue by symphony2014** [microsoft/vscode#95823]
- VSCode Version:1.44.2
- OS Version:Windows 10 Enterprise 1909
Steps to Reproduce:

1.Open  [elide_inports_spec.ts](https://raw.githubusercontent.com/angular/angular-cli/master/packages/ngtools/webpack/src/transformers/elide_imports_spec.ts) in vscode.
You will found the wrong font color around **tags.stripIndent** which should be black since the keyword is method name.
![image](https://user-images.githubusercontent.com/6380601/79942151-c13b3600-8498-11ea-94e2-85f130a44e58.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
What theme are you using?

**Comment by symphony2014** [comment]
> What theme are you using?

I just use the default light theme.
![image](https://user-images.githubusercontent.com/6380601/80112936-3f402f80-85b4-11ea-968c-eb1144ee57f8.png)

**Comment by alexr00** [comment]
Are you sure you have all extensions disabled? I'm not able to reproduce that behavior. Can you share all your settings.json?
![image](https://user-images.githubusercontent.com/38270282/80480700-664e8680-8951-11ea-862d-c86d8993c7d7.png)

**Comment by symphony2014** [comment]
@alexr00  When I choose `Light+(default light)`,  it works, I guess it's just `Light(visual studio)` theme style.
