### ISSUE TITLE
The diff editor doesn't work well when clicking the change in REFACTOR PREVIEW panel

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#95822]
Version: 1.45.0-insider (user setup)
Commit: b83339a3a7bd8e3ec8a8b79deda9c37e0d91f094
Date: 2020-04-21T05:41:11.873Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:
1. Install Java Language Support extension.
2. Clone https://github.com/spring-projects/spring-petclinic, and open it in VS Code.
3. Wait for the Java extension to be ready. There is an icon at the right bottom corner, 👍 means ready.
4. Go to file explorer, select the file `src\main\java\org\springframework\samples\petclinic\vet\Specialty.java`, and rename it to `Specialty1.java`.
5. The java extension will compute the update, and trigger the preview panel. See the screenshot below. You can see the correct diff summary at the preview panel, but when you click the child edit to open the diff editor, it doesn't render the diff texts correctly. When you check all edits and apply the refactoring, the changes can be applied correctly. This looks like it's a VS Code bug.

   ![image](https://user-images.githubusercontent.com/14052197/79938208-8d5b1300-848e-11ea-9631-6f99c20b2745.png)

Share more background about Java implementation. When renaming a file, the Java extension will generate a workspace edit with needConfirmation property enabled, then call `workspace.applyEdit` API to trigger the preview panel.

**Comment by testforstephen** [comment]
// @jrieken

**Comment by jrieken** [comment]
>  This looks like it's a VS Code bug.

This is the design. The diff editor shows a preview of what is going to happen when pressing apply and changes that aren't selected are not previewed (because they will not happen)
