### ISSUE TITLE
Unable to close find widget using keyboard

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#9582]
- VSCode Version: insider
- OS Version: OS X

At least once per day I get into a situation that I can not close the find widget using the keyboard (esc or cmd + F). The only way to close it is by clicking on the X.
Sorry for no steps, I just open the find widget, go on my buisness and some time later can not close it via keyboard.

**Comment by alexandrudima** [comment]
Most likely #10358 , steps in #10075

**Comment by bpasero** [comment]
Should be fixed now that https://github.com/Microsoft/vscode/issues/10075 landed.

**Comment by alexandrudima** [comment]
@jrieken You can have the pleasure of closing :)
