### ISSUE TITLE
JS intellisense not working for socket.io client

### ISSUE THREAD

**Issue by OSG-Proj** [microsoft/vscode#95824]
- VSCode Version: Newest
- OS Version: Win10

Steps to Reproduce:

1. Make JS intellisense work for client side libraries such as socket.io when imported to html
2.

Does this issue occur when all extensions are disabled?: same thing happens even if I do

**Comment by mjbvz** [comment]
Please share a code example that demonstrates the issue

**Comment by OSG-Proj** [comment]
var socket = io(); no intellisense at io()
When using client side socketio library in JS

**Comment by mjbvz** [comment]
Are you importing `io` somehow?

**Comment by OSG-Proj** [comment]
No, and import works only with the aliased path which then gives a problem when I try to use it with an html file

**Comment by mjbvz** [comment]
So you're writing this JavaScript in an html file?

**Comment by OSG-Proj** [comment]
Embedding it

**Comment by mjbvz** [comment]
Duplicate of #26338
