### ISSUE TITLE
Implement VS Code support for dynamic debug configs

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#95835]
please see #88230 for the detailed discussion.

**Comment by isidorn** [comment]
VS Code now supports dynamic debug configs. Thus closing this.
Here's a test plan item placeholder https://github.com/microsoft/vscode/issues/95837

**Comment by weinand** [comment]
@isidorn to make the new folder-like entries in the quick pick really stand out, we should use either the folder icon that task is using or the new debug icon we are using for session in the call stack view.

<img width="774" alt="2020-04-22_09-52-28" src="https://user-images.githubusercontent.com/1898161/79955578-4d406400-847f-11ea-8192-f9d93b0ff13f.png">

**Comment by isidorn** [comment]
@weinand makes sense. Pushed a change

![Screenshot 2020-04-22 at 10 20 17](https://user-images.githubusercontent.com/1926584/79958231-fb99d880-8482-11ea-882c-fc44b5bc5049.png)

**Comment by weinand** [comment]
Nice! 

I noticed that you've added an ellipsis too (which IMO makes sense).
@alexr00 you might want to consider this too...

**Comment by isidorn** [comment]
@weinand yeah, I pinged also @alexr00 for that, but since they mostly show more of those items she thought it looks a bit like clutter.

**Comment by weinand** [comment]
@isidorn for sake of consistency then let's remove the ellipsis from debug too.

**Comment by isidorn** [comment]
I would like debug to be consistent across quick pick and our debug dropdown where we also show elipses (we can not show icons so it is a good diferentiator).
Also I prefer corectness over consisntency, so I would like to keep the elipses :)

**Comment by weinand** [comment]
@isidorn fair enough, so let's put some pressure on Tasks... 😁

fyi @alexr00

**Comment by weinand** [comment]
@isidorn IMO the interaction with the new "Dynamic" items in the drop down menu is rather strange: selecting them has no effect but one has to press the play button to get the quickpick.
This is unexpected and very different from the "Add configuration..." item which works without the play button.

**Comment by isidorn** [comment]
@weinand this was a delibarate choice to tackle two problems:
* What if a user wants to change the dynamic configuration provided, he would have to choose another item in the dropdown and choose this one again.
* What if a user reloads, should it be the same one as last time, or we should ask again? Then we need to store.

Also it is about starting debugging so it made more sense to behave like the other options which are also configurations and nothing happens once you choose them.
"Add configuration" felt like a special case and I did not think others should align to it.

All in all I deliberatly made it this way because I thought it will be smother.
I might be wrong and we can easily change though.

**Comment by weinand** [comment]
@roblourens @connor4312 what do you think?
if you do not have a debug extension that implements a dynamic debug configuration provider, just checkout mock-debug and run the extension via F5.
in the new instance open the debug dropdown and play with the "Mock Debug" item...

**Comment by connor4312** [comment]
> What if a user wants to change the dynamic configuration provided, he would have to choose another item in the dropdown and choose this one again.

I'm not sure what you mean by this. If I have a configuration in the launch configuration, I can hit the gear to jump to it. But for dynamic configurations that isn't useful. Is there a different action you're thinking of?

> What if a user reloads, should it be the same one as last time, or we should ask again? Then we need to store.

Imo a good behavior would be to still select the dynamic configuration (so I can hit the play button or F5 to run it again) but automatically open the quickpick as soon as I select it. I think it's safe to assume that when a user makes a selection, especially for a dynamic configuration, they intend to start debugging as well.

**Comment by alexr00** [comment]
The folder icon alone signifies that there is more menu to be shown (file pickers don't show an ellipse for folders). Having both is redundant, and the ellipse does add more noise.

If you really want tasks to have both though I will add it.
