### ISSUE TITLE
[C++] "struct foo::bar baz" confuses syntax highlighter

### ISSUE THREAD

**Issue by tbm0** [microsoft/vscode#95834]
Issue Type: <b>Bug</b>

`struct foo::bar baz` confuses the C++ syntax hilighter, for example in this code snippet:

```c++
void test() {
    struct foo::bar baz;
    if (bar(baz,
            "%u;%ld",
            false);) {
        
    }
}
```

![image](https://user-images.githubusercontent.com/658101/79951062-54b03f00-8478-11ea-9e4f-908f36524509.png)

Removing the "struct" prefix fixes things. It is redundant but it should still be OK to have. This worked alright in previous vscode versions. Reproduced with all extensions disabled.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 5.3.0-46-generic
Remote OS version: Linux x64 5.3.0-40-generic

<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
lex-flex-yacc-bison|fau|0.0.3
osdk|Jed|0.0.5
nim|kos|0.6.6
python|ms-|2020.4.74986
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
cmake-tools|ms-|1.3.1
cpptools|ms-|0.27.0
vscode-scheme|sjh|0.4.0
cmake|twx|0.0.17

(2 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
Moved to owning repo: https://github.com/jeff-hykin/cpp-textmate-grammar/issues/471
