### ISSUE TITLE
runtimeExecutable for different operating systems

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#9583]
- VSCode Version: 1.3.1
- OS Version: Windows 10 & Ubuntu 16.04

I am using vscode on both windows (At work) and linux (At home). The issue I am having is with using electron on both OS's.

I have the `runtimeExecutable` set to `${workspaceRoot}/node_modules/.bin/electron` which works on my linux machine but doesn't work on my windows machine.

I then have to change the `runtimeExecutable` to `${workspaceRoot}/node_modules/.bin/electron.cmd` on my windows (note the `cmd`). Changing these all the time gets annoying.

Is there a way to define a windows executable and a linux executable? Maybe in a way like this:

```json
"runtimeExecutable": {
    "linux": "${workspaceRoot}/node_modules/.bin/electron",
    "darwin": "${workspaceRoot}/node_modules/.bin/electron",
    "win32": "${workspaceRoot}/node_modules/.bin/electron.cmd",
},
```

And when mac/linux use the same executable:

```json
"runtimeExecutable": {
    "unix": "${workspaceRoot}/node_modules/.bin/electron",
    "win32": "${workspaceRoot}/node_modules/.bin/electron.cmd",
},
```

**Comment by kieferrm** [comment]
One possible work-around is to use different, platform specific launch configurations.

**Comment by TheColorRed** [comment]
That works great! I didn't even know that was a feature of the launch configuration!

Thanks!

**Comment by weinand** [comment]
@TheColorRed please see this resolved feature request https://github.com/Microsoft/vscode/issues/1873 for how to do this easily (or the last release notes of 1.3.0).
