### ISSUE TITLE
Add keyboard shortcut for 'Add all missing imports'

### ISSUE THREAD

**Issue by sandorvasas** [microsoft/vscode#95831]
Be able to set a shortcut for the above. Hovering, waiting, clicking while refactoring, especially with a touchpad is painful.

**Comment by wesbos** [comment]
FYI you can use ⌘ + . to bring this up with the keyboard

**Comment by mjbvz** [comment]
@wesbos This change lets you use 'add missing imports' from anywhere in the file, not just when you are over an error. This is similar to how organize imports works

Example keybinding:

```json
    {
        "key": "ctrl+shift+i",
        "command": "editor.action.sourceAction",
        "args": {
            "kind": "source.addMissingImports",
            "apply": "first"
        }
    },
```
