### ISSUE TITLE
change in icons for the menu

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#95838]
Issue Type: <b>Bug</b>

after the latest update observed tick marks in the menu instead of the ">" sign to indicate there is a submenu.
is this expected change? i have pinned the menu in the sidebar.

![image](https://user-images.githubusercontent.com/9264813/79955921-14af8300-849d-11ea-92bd-75da2861d5fc.png)

VS Code version: Code - Insiders 1.45.0-insider (6fc9bd19c5a3c9c42d9a5c23152b1680bc308a57, 2020-04-22T06:26:58.340Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.15.0-96-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (9.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: angular_serve|
|OS|Linux x64 4.15.0-96-generic|
|CPUs|Intel Xeon E312xx (Sandy Bridge, IBRS update) (4 x 2399)|
|Memory (System)|7.79GB (4.41GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.6
ng-template|Ang|0.901.2
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
prettier-vscode|esb|4.4.0
node-debug2|ms-|1.42.2
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2000
vscode-xml|red|0.11.0
vscode-yaml|red|0.7.2
LiveServer|rit|5.6.1
sonarlint-vscode|Son|1.15.0
vscodeintellicode|Vis|1.2.6

</details>

**Comment by IllusionMH** [comment]
I don't think that this one is intended.

/cc @misolori 

May be something with codicons or styles.
I noticed that I have sometimes spinning `codicon-tree-item-expanded` instead of `codicon-loading` because former overrides styles of loader. Haven't noticed this problem before

**Comment by misolori** [comment]
@aeschli related to product icon overrides?

**Comment by IllusionMH** [comment]
@misolori sorry for mention, I was not aware about changes in approach to use Codicons and thought that it might be unintentional font update.

Yes, looks like it was part of #95435 . PR with fix is available
