### ISSUE TITLE
Opening an existing file causes recompiling

### ISSUE THREAD

**Issue by wuliZXF** [microsoft/vscode#95833]
Issue Type: <b>Bug</b>

- Compile and start the react project
- Open an existing tsx file in the project
- The project will be recompiled though the file is not be changed

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.69GB (19.02GB free)|
|Process Argv|--folder-uri file:///d%3A/repos/Topologies/sources/dev|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-eslint|dba|2.1.5
xml|Dot|2.5.0
vs-code-xml-format|fab|0.1.5
gc-excelviewer|Gra|2.1.34
vscode-react-typescript|inf|1.3.1
vscode-azureappservice|ms-|0.16.5
csharp|ms-|1.21.17
azure-account|ms-|0.8.9
cpptools|ms-|0.27.0
powershell|ms-|2020.4.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
vscode-jest|Ort|3.1.1
typescript-hero|rbb|3.0.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by wuliZXF** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by wuliZXF** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Yes

**Comment by mjbvz** [comment]
VS Code doesn't automatically compile your code. How are you starting the compiling? Are you using a task? From the command line?

**Comment by wuliZXF** [comment]
> VS Code doesn't automatically compile your code. How are you starting the compiling? Are you using a task? From the command line?

I just ran `npm start` for my nodejs project in a VS Code terminal. In the past, node would re-compile the changed file right after I saved my changes. But now it seems it does that sometimes when I just open an existing file without any change.

**Comment by mjbvz** [comment]
Have you tools changed? For example, have you updated the packages that are watching an re-compiling the files?

**Comment by wuliZXF** [comment]
> Have your tools changed? For example, have you updated the packages that are watching an re-compiling the files?

I don't think so. What I did is just opening some existing files in the explorer.

**Comment by mjbvz** [comment]
Seems like the same root cause as #96338
