### ISSUE TITLE
Test: dynamic debug configurations

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#95837]
Refs: #95835, #88230

- [x] anyOS @connor4312 
- [x] anyOS @RMacfarlane 

Complexity: 3

Authors: @weinand, @isidorn

---

We now support dynamic debug configurations, that means an extension can contribute dynamically created debug configurations to places where only the static debug configurations from the launch.json were shown previously.

Develop an extension that uses the [new API](https://github.com/microsoft/vscode/blob/c610dd7fc70a4ecb99c7d7111605182f94cfef43/src/vs/vscode.proposed.d.ts#L728-L761) or modify an existing debug extension to use the new API and verify the following:
* the extension API for dynamic debug configs works as [specified](https://github.com/microsoft/vscode/blob/c610dd7fc70a4ecb99c7d7111605182f94cfef43/src/vs/vscode.proposed.d.ts#L728-L761)
* When invoking the "Select and Start Debugging" command, you are presented with a "dynamic debug configuration container" for your extensions. 
* This container item is decorated with a folder icon, is in a separate group and once you choose it you can see a list of dynamic debug configurations which just got resolved
* Once you choose a configuration, debug is started
* The same container for dynamic debug configurations appears in the debug viewlet's dropdown menu (but it does not have an icon for technical reasons). 
* Once you start debugging and the chosen option is the container, you can choose a configuration and start debugging.

Feedback on the whole flow is very welcome:
@connor4312 @RMacfarlane do you like the behavior of the container item in the debug viewlet's drop down menu? After selecting it nothing happens but you have to press the play button to actually make a selection. The alternative interaction would be to open the quickpick immediately when selecting the  container item.

**Comment by RMacfarlane** [comment]
I felt ok about having the quickpick shown when you press the play button, it didn't bother me. But I think the alternative of showing the quickpick immediately would be better - that way if I repeatedly stop and start debugging, I don't have to keep making the same selection.

**Comment by weinand** [comment]
@isidorn pls see Rachel's comment

**Comment by isidorn** [comment]
@RMacfarlane makes sense. Please file a new feature request for this, thanks.
