### ISSUE TITLE
Prompt for GPG passphrase to sign commits not displayed

### ISSUE THREAD

**Issue by MrChocolatine** [microsoft/vscode#95839]
- VSCode Version: 1.44.2
- OS Version: macOS Mojave

Steps to Reproduce:

Where VSCode is supposed to ask for the passphrase to sign commits when creating them directly through the interface and not with a terminal?

When I already entered my passphrase, by creating a commit through the terminal, I don't have any problem, creating another one within VSCode works.

But when it is not the case, or when my passphrase is expired and I need to type it again, creating a commit with VSCode interface does do anything.

I can see something is waiting:
![vscode-git-00](https://user-images.githubusercontent.com/47531779/79955386-abb51480-8476-11ea-8a9e-91fde053b750.png)

But in the end I don't have anything at all, neither in my VSCode terminal, nor if I open/kill a new terminal tab, or in my iTerm terminal. I can't type my passphrase anywhere.

Shortly after, once the timeout is over:
![vscode-git-01](https://user-images.githubusercontent.com/47531779/79955571-e7e87500-8476-11ea-9cae-a6a13ce0a1f4.png)

After all of this, when I try to create the commit in a VSCode terminal by simply typing `git commit`, I am invited to type my commit message, fine, then I am usually asked to type my passphrase in the terminal but again nothing shows up, the terminal is kind of waiting without anything else. And I need to kill the agent with `gpgconf --kill gpg-agent` to make everything work again.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
#43809
