### ISSUE TITLE
Debugger does not launch Chromium if Chrome is not installed

### ISSUE THREAD

**Issue by unikitty37** [microsoft/vscode#95847]
Issue Type: <b>Bug</b>

On macOS, with Chrome not installed, Chromium installed in /Applications, and the following `launch.json`:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}"
    }
  ]
}
```

Press F5 to start a debug session.

**Expected behaviour:**

Chromium launches and loads the page.

**Actual behaviour:**

Visual Studio Code complains that Chrome is not found.

**Notes:**

Chromium is Chrome without all the Google extras. It is just as capable of debugging an application. If Chrome is not installed, Visual Studio Code should fall back to Chromium.

Ideally, the documentation should also give details on using other Chromium-based browsers, such as Vivaldi (or, these days, Microsoft's own Edge 😀) — setting `RuntimeExecutable` to `/Applications/Chromium.app` produces the unhelpful error `Chrome error: Error: spawn /Applications/Chromium.app EACCES`. Similar results for Vivaldi.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-add-brackets|ali|0.11.0
vscode-color|ans|0.4.5
vscode-database|baj|2.2.0
color-info|bie|0.5.1
vscode-multi-line-tricks|big|0.0.3
vscode-toggle-quotes|Bri|0.3.2
solargraph|cas|0.21.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.29
vue-peek|dar|1.0.2
vscode-eslint|dba|2.1.5
vscode-dash|dee|2.4.0
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.4.0
gitlab-workflow|fat|2.2.0
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.2
code-runner|for|0.9.17
rest-client|hum|0.23.2
mark-as-excluded|jcm|0.2.6
docthis|joe|0.7.1
graphql-for-vscode|kum|1.15.3
node-module-intellisense|lei|1.5.0
git-graph|mhu|1.22.0
dotenv|mik|1.0.1
vscode-elixir|mjm|1.1.0
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.1.0
python|ms-|2020.4.74986
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-ssh-explorer|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
abracadabra|nic|4.1.0
vetur|oct|0.24.0
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.0.1
tsimporter|pmn|2.0.1
tslint-vue|pro|1.5.6
quicktype|qui|12.0.46
typescript-hero|rbb|3.0.0
ruby|reb|0.27.0
vscode-yaml|red|0.7.2
stylelint|shi|0.51.0
autoimport|ste|1.5.3
move-ts|str|1.12.0
open-in-browser|tec|2.0.0
tmlanguage|Tog|0.9.0
sort-lines|Tyr|1.9.0
highlight-matching-tag|vin|0.9.9
vscode-icons|vsc|10.1.1
vscode-ansible|vsc|0.5.2
vscode-todo-highlight|way|1.0.4
vscode-ruby|win|0.27.0
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
html-css-class-completion|Zig|1.19.0

(3 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
`runtimeExecutable` is documented as an optional field in the [Chrome debugger readme](https://github.com/Microsoft/vscode-chrome-debug#other-targets).

Note that on OSX `Chromium.app` is just a directory. You will need to find the binary path within the app, for instance inside `Google Chrome.app` the actual binary is `Google Chrome.app/Contents/MacOS/Google Chrome`.
