### ISSUE TITLE
"do you want to save changes" prompt appears after closing unchanged untitled file

### ISSUE THREAD

**Issue by domagojk** [microsoft/vscode#95842]
- VSCode Version: 1.44.2
- OS Version: Darwin x64 19.3.0

Steps to Reproduce:

This happens in my extension, which can be reproduced like this:

```typescript
const uri = vscode.Uri.file('/path/to/save/the/file.ext').with({ scheme: 'untitled' })
const doc = await vscode.workspace.openTextDocument(uri)
vscode.window.showTextDocument(doc)
```

When closing a file opened like this (without modifying it) I get the prompt: "Do you want to save the changes you made to file.ext". 
Before updating to version 1.44 it would just close as expected, but now it seems there is some undo history stored.

**Comment by bpasero** [comment]
This is the correct behaviour, untitled editors with associated path will ask to save on close. We did however push a change last milestone to enforce this behaviour also when running extension development mode to aid custom editor development where you otherwise could not test this.
