### ISSUE TITLE
Emmet doesn't work with hbs

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode#95845]
Issue Type: <b>Bug</b>

It seems that if I use "inMarkupAndStylesheetFilesOnly" I cannot expand with Tab in hbs files.

VS Code version: Code - Insiders 1.45.0-insider (6fc9bd19c5a3c9c42d9a5c23152b1680bc308a57, 2020-04-22T06:20:01.720Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 8, 6|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|-psn_0_1249585|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (75)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
cucumberautocomplete|ale|2.14.1
cypress-snippets|and|1.2.0
vscode-apollo|apo|1.15.2
atlascode|atl|2.5.1
phpstan|bre|1.1.3
twigcs|cer|1.1.0
vscode-opennewinstance|chr|0.0.7
transformer|dak|1.6.0
scss-grammar-extended|dan|1.0.0
vscode-eslint|dba|2.1.5
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.2.1
emberjs|emb|1.0.1
vscode-ember|emb|0.2.0
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|4.4.0
vs-code-xml-format|fab|0.1.5
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vsc-ember-cli|fel|0.3.3
file-icons|fil|1.0.23
vscode-firefox-debug|fir|2.7.2
vscode-architect|gil|0.1.0
vscode-pull-request-github|Git|0.15.0
dance|gre|0.2.2
rest-client|hum|0.23.2
output-colorizer|IBM|0.1.2
composer|ika|0.7.1
smarty|imp|0.3.0
path-autocomplete|ion|1.13.6
svelte-vscode|Jam|0.9.3
exercism|jgo|0.0.4
vscode-peacock|joh|3.7.0
ember-related-files|jos|1.5.0
php-cs-fixer|jun|0.1.151
language-haskell|jus|2.7.0
graphql-for-vscode|kum|1.15.3
php-symbols|lin|2.1.0
phpmd|lin|1.2.1
web-accessibility|Max|0.2.82
twig-language-2|mbl|0.9.1
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.1.0
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
vscode-remote-extensionpack|ms-|0.20.0
js-debug-companion|ms-|0.0.4
js-debug-nightly|ms-|2020.3.2517
references-view|ms-|0.0.50
vscode-typescript-next|ms-|3.9.20200421
debugger-for-chrome|msj|4.12.6
vscode-versionlens|pfl|0.25.0
EmberES6Snippets|pha|2.3.3
vscode-yaml|red|0.7.2
elastic|ria|0.13.3
vscode-javascript-booster|sbu|0.12.3
code-settings-sync|Sha|3.4.3
phpcs|she|1.0.8
svg-preview|Sim|2.8.3
vscode-vuln-cost|sny|1.1.1
sourcegraph|sou|1.1.0
autoimport|ste|1.5.3
tech-debt-tracker|Ste|0.27.1
cucumber|ste|0.12.0
vscode-stylelint|sty|0.84.0
vscode-field-lights|sve|0.0.11
php-phan|Tys|1.2.4
vscode-phpsab|val|0.0.5
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.1.1
twig|wha|1.0.2

(2 theme extensions excluded)

</details>

**Comment by octref** [comment]
Which is exactly what the documentation says:

> // The option `"inMarkupAndStylesheetFilesOnly"` applies to html, haml, jade, slim, xml, xsl, css, scss, sass, less and stylus.

**Comment by bm-stschneider** [comment]
<img width="785" alt="image" src="https://user-images.githubusercontent.com/30625381/80404956-3d32e500-88c2-11ea-8b24-023de1911d7e.png">

**Comment by bm-stschneider** [comment]
What is handlebars then? I thought it counts as markup.
