### ISSUE TITLE
Highlighting of closing braces is indicating wrong brace when cursor is behind opening brace

### ISSUE THREAD

**Issue by teetotum** [microsoft/vscode#95843]
Issue Type: <b>Bug</b>

* view this code snippet in the editor
```
//test.tsx
import * as React from 'react';

export const render = () => {
  const foo = true;
  return <div>{foo && <div>test</div>}</div>;
};
```
* place the cursor directly before the opening brace in `return <div>{foo && <div>test</div>}</div>;`
* the corresponding closing brace on the same line is highlighted correctly
* move the cursor one character further (directly behind the opening brace)
* bug is visible: the closing brace of the last line (i.e. closing brace of the 'render' function) is highlighted

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (1.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
prettier-vscode|esb|4.4.0
vscode-docker|ms-|1.1.0
sqltools|mtx|0.21.7
stylelint|shi|0.51.0

</details>

**Comment by dfireBird** [comment]
I think this bug is only happening in JSX only (a particular edge case).

**Comment by NayamAmarshe** [comment]
Any fix for this?
