### ISSUE TITLE
Use void instead `CustomDocumentContentChangeEvent`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#95849]
Using marker interfaces in a structurally typed language like TypeScript has zero value. It cannot be told apart other empty things and makes it more cumbersome for extension authors. For custom documents and the `onDidChange`-event it is enough to have this

```
readonly onDidChange: Event<void> | Event<CustomDocumentEditEvent> 
```

**Comment by mjbvz** [comment]
Structurally yes it doesn't add anything, but it lets us document the event and the interface can be extended if needed in the future

Can you explain how it be more any cumbersome for extension authors?

**Comment by jrieken** [comment]
> Can you explain how it be more any cumbersome for extension authors?

Sure. First, it is a new concept which we have never used before and that by itself adds complexity. Then, you need to write `emitter.fire({})` instead of `emitter.fire()` - the ladder is  enough to express what we need to know - which in return means the former isn't needed. 

Ideally TS would allow us to define these as overload instead of or-types. That would make the whole documentation indirection obsolete.

**Comment by mjbvz** [comment]
All the documentation has to go into the single property's documentation. 

The current API is what we agreed to as a group. It's fine with me to switch it, but I want to make sure we have thought it through. The current design also has the advantages I noted: documentation and extensibility if needed
