### ISSUE TITLE
add 'open reveal in file explorer ' in editor context menu

### ISSUE THREAD

**Issue by Oneliey** [microsoft/vscode#95844]
add 'open reveal in file explorer ' in editor context menu like in explorer side bar
![image](https://user-images.githubusercontent.com/30212642/79963882-877c2680-84bc-11ea-9bf6-87f7af13668c.png)
![image](https://user-images.githubusercontent.com/30212642/79963907-8e0a9e00-84bc-11ea-89e4-5da14983b1ea.png)

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by Oneliey** [comment]
Thanks( What new feature will be in the next release?
