### ISSUE TITLE
Add option to install *.vsix files headless

### ISSUE THREAD

**Issue by cdietrich** [Microsoft/vscode#9585]
- VSCode Version: 1.3.1
- OS Version: Mac OS X 10.11.5

it would be nice to be able to install extensions that are packeged as vsix files headlessly e.g.
`code --install-extension my.vsix`

**Comment by lextm** [comment]
https://code.visualstudio.com/Docs/extensions/install-extension 

What do you mean by "headless", unless the documented approach is not what you wanted?

**Comment by cdietrich** [comment]
I want to be able to install plugins that are not in the marketplace the same way as I can do it for plugins that are in the marketplace. Means I want to be able to call `code --install-extension my.vsix` so that the plugin gets installed without opening a code window. This would allow me to provision code without opening closing Windows. 

So basically dealing with vsix and marketplace should be the same

**Comment by lextm** [comment]
@cdietrich Thanks. Yes, that's not yet supported and should be a good feature request.

**Comment by franzbecker** [comment]
That was super fast, thanks a lot! 👍

**Comment by cdietrich** [comment]
it works like a charm, thanks 👍
