### ISSUE TITLE
Fade out problem icons in status bar when problem count is zero.

### ISSUE THREAD

**Issue by k-l-lambda** [microsoft/vscode#95855]
![image](https://user-images.githubusercontent.com/11451724/79966740-7503ec00-84c0-11ea-8071-fd8c3ea05d7b.png)

When errors and warnings' count is zero, please fade out the icons color, or hide them simply to reduce annoyance, and make that more noticeable when problems are not empty.

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/51010
