### ISSUE TITLE
Can't get vscode://open links to work

### ISSUE THREAD

**Issue by felixfbecker** [microsoft/vscode#95850]
- VSCode Version: 1.44.2
- OS Version: macOS

Steps to Reproduce:

1. Run `open 'vscode://open?url=file:///Users/felix/git/sourcegraph/README.md'` (pointing to a file that exists on disk, while having VS Code open with the folder opened)
2. Observe how VS Code opens, but the file doesn't get opened

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
Where you get that URL format?
It has different format in docs [Opening VS Code with URLs](https://code.visualstudio.com/docs/editor/command-line#_opening-vs-code-with-urls)

See discussion https://github.com/microsoft/vscode/issues/4883#issuecomment-270073371

**Comment by joaomoreno** [comment]
@bpasero `vscode://open` Are these the new URLs you introduced recently, for remote?

**Comment by joaomoreno** [comment]
@felixfbecker Does `Developer: Open URL` do anything when you give it that URL?

**Comment by felixfbecker** [comment]
Sorry, I googled around and didn't find the official documentation, but picked up that this should work somewhere. `vscode://file/` works as expected.

**Comment by IllusionMH** [comment]
@joaomoreno In my case it does nothing.

Tried to paste `https://github.com/microsoft/vscode/issues/95850` and `file:///C:/web/projects/vscode/README.md` and not sure if I'm doing this correctly.

Pasting second into Windows Explorer address bar - opens MD file in VS Code 😄 

@felixfbecker glad that this one works for you.

**Comment by bpasero** [comment]
@joaomoreno remote URIs are: `vscode://vscode-remote/<authority>/<path>`
