### ISSUE TITLE
Speed up "Quick Open" in big projects 

### ISSUE THREAD

**Issue by emattias** [microsoft/vscode#95853]
I have a big repo and I often need to open files in our big `node_modules` folder so I have removed `node_modules` from the exclude.

This results in quick opening (target file not in `node_modules`) can take 29 seconds:

![CleanShot 2020-04-22 at 11 46 09](https://user-images.githubusercontent.com/351537/79967609-56393180-848f-11ea-8e14-d9fe91bf5271.gif)

## Suggestions/Ideas 

*(other than completely excluding big folders)*

1. exclude `node_modules` unless it is explicitly included in the search string.
	- It might be nice to have a shorter alias than `node_modules`. Like `~` that has been used [in sass](https://www.npmjs.com/package/node-sass-tilde-importer).
2. limit number of required matches to show result list
3. depriotize certain folders (`node_modules`) and first search and show matches from other folders
4. granular options to make the search less fuzzy
	- ex: require atleast 3 character match to show as result.

**Comment by roblourens** [comment]
I think this is the best solution, being able to leave node_modules in the excludes but temporarily turn them off: https://github.com/microsoft/vscode/issues/15604

Your suggestions are good ones but aren't possible with our current implementation - for example, we don't show any matches until we have walked the entire tree and scored all potential matches.
