### ISSUE TITLE
[api] use of generic in providers

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#95852]
We have added a generic to the `CustomEditorProvider`-provider. Two remarks

1. I was confused by `DocumentType extends CustomDocument = CustomDocument` and I would have preferred the usual usage of a single letter name, like `T extends CustomDocument = CustomDocument`
1. We adding an inconsistency wrt other providers which also support resolving of custom objects, e.g `CompletionItemProvider`, `CodeLensProvider`, `WorkspaceSymbolProvider`, and `DocumentLinkProvider` . I think we should do this in an all-or-nothing approach so that we make it clear that `WorkspaceSymbolProvider` isn't any different to `CustomEditorProvider ` wrt this.

**Comment by mjbvz** [comment]
I'll rename it to `T`.

I'm also in favor of point 2. I have this problem with the TypeScript extension today and end up having to call to `instanceof`. As long as we provide a default value for the generic type this should not be a breaking change
