### ISSUE TITLE
activityBar.border is no longer rendered on Insiders

### ISSUE THREAD

**Issue by robertrossmann** [microsoft/vscode#95858]
```
Version: 1.45.0-insider
Commit: 9328b32008089c515f39a13db9c71e57c7d36823
Date: 2020-04-22T08:41:53.798Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

After updating to the latest VS Code - Insiders build (see above) my UI no longer shows the Activity Bar border. There is simply no border visible. I believe this worked in the previous Insiders build, or at most two builds back. Stable works just fine. Attaching some screens below.

Steps to Reproduce:

1. Set a colour contribution for `activityBar.border`
1. Observe no border is shown on the Activity Bar

Does this issue occur when all extensions are disabled?: **Yes**

### Screenshots

These have been taken with the same configuration. Notice the border is missing on Insiders.

**VS Code:** (working)

![VS Code - working](https://user-images.githubusercontent.com/3058150/79971476-a6ff5900-8494-11ea-8b10-a08d95d3849d.png)

**VS Code - Insiders:** (no border)

![Scr VS Code - Insiders - no border](https://user-images.githubusercontent.com/3058150/79971560-bd0d1980-8494-11ea-9669-1119bb38e802.png)

**Comment by robertrossmann** [comment]
A possibly related issue with borders not showing in the workbench panels: #95439.

**Comment by sbatten** [comment]
@misolori did your sectionHeader tweaks do something here?

**Comment by misolori** [comment]
@sbatten nope, mine was re-adding the line I removed https://github.com/microsoft/vscode/commit/bf3640a8c27b47c7195ddf3365ba7f92a4366684

https://github.com/microsoft/vscode/blob/4b178bfc9f137699e1d115f883c1c17a1149b7ff/src/vs/workbench/browser/parts/views/media/paneviewlet.css#L6-L8

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/commit/12a084bf1b77d9f89690858383f1a3cfe73150aa caused this it seems

//cc @rebornix

**Comment by rebornix** [comment]
@sbatten should we restrict this to safari?

**Comment by rebornix** [comment]
After we make the content `position: absolute`, its parent `part` no longer has any height. Set it to `100%` to inherit.

**Comment by robertrossmann** [comment]
@rebornix Sorry to be the bad messenger but I am still not seeing the activity bar border on latest insider even though I see your commit where you fix this (c610dd7) being already included in it. 😢 🤷‍♂️ 

```
Version: 1.45.0-insider
Commit: abb4a35cfc26102f93fd00df7b59ce1a19c2017a
Date: 2020-04-28T05:34:21.109Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

**Comment by sbatten** [comment]
@rebornix same, sidebar on the left is not fixed.

**Comment by sbatten** [comment]
fixed by https://github.com/microsoft/vscode/commit/4d3fdac546e9e348653b7f9e5f573197b50282e7
