### ISSUE TITLE
CustomDocument#dispose should be #delete

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#95851]
This came up yesterday and we concluded that deleting is the 99% way how extension would implement nuking of a backup, so we should just call it `delete`. We should also consider if `backupId` should be named just `id`, like TreeItem#id, Breadpoint#id etc etc

```
interface CustomDocumentBackup {
	readonly id: string;
	delete(): void | Thenable<void>;
}
```

**Comment by mjbvz** [comment]
I'm good with delete.

We intentionally decided to call it `backupId` though so that would be is symmetrical with the `backupId` field passed to open: https://github.com/microsoft/vscode/blob/f56960538dfdd03173ac57cdfcc8964c6d7549be/src/vs/vscode.proposed.d.ts#L1406

**Comment by mjbvz** [comment]
I kept it as `backupId` for now but we can discuss it tomorrow
