### ISSUE TITLE
Align API for NotebookEditors and CustomEditors?

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#95854]
It is nice to think of a notebook editor as a special case of a custom editor. However, the APIs are still very different

* There is `EditableCustomDocument#save` (and more) vs `NotebookProvider#save`
* There is no API for backup, save-as, or revert in custom documents
* There is `openCustomDocument` and `resolveCustomEditor` but only `NotebookProvider#resolveNotebook` which is kinda both
* Notebooks cannot express if the same notebook(document) supports being opened multiple time per resource
* notebooks are public objects and custom editors are private objects (unsure if that has an effect...)

**Comment by rebornix** [comment]
Proposal from today's discussion: a `NotebookContentProvider` will be responsible for providing the raw data for a notebook document and the core will create a managed object `vscode.NotebookDocument` accordingly. The `NotebookContentProvider` will be the hook for working copy service (save/undo/redo). 

```ts
export interface NotebookData {
    readonly cells: NotebookCell[];
    readonly languages: string[];
    readonly displayOrder?: GlobPattern[];
    readonly metadata: NotebookDocumentMetadata;
}

export interface NotebookContentProvider {
    open(uri: Uri): NotebookData;
    save(document: NotebookDocument, cancellation: CancellationToken): Thenable<void>;
    saveAs(targetResource: Uri, document: NotebookDocument, cancellation: CancellationToken): Thenable<void>;
    readonly onDidChange: Event<void>;
    revert(document: NotebookDocument, cancellation: CancellationToken): Thenable<void>;
    backup(document: NotebookDocument, cancellation: CancellationToken): Thenable<CustomDocumentBackup>;
}
```

**Comment by mjbvz** [comment]
@jrieken Keep in mind that we are trying to finalize custom editors this iteration so it is quite late to be making significant changes to the API without very good reason to. 

Can `NotebookDocument` be an abstract class? Something like:


```ts
export abstract class NotebookDocument {
     constructor(uri: Uri, data: NotebookData);
     
    abstract save(cancellation: CancellationToken): Thenable<void>;
    abstract saveAs(targetResource: Uri, cancellation: CancellationToken): Thenable<void>;
    abstract readonly onDidChange: Event<void>;
    abstract revert(cancellation: CancellationToken): Thenable<void>;
    abstract backup(cancellation: CancellationToken): Thenable<CustomDocumentBackup>;
}

export interface NotebookData {
    readonly cells: NotebookCell[];
    readonly languages: string[];
    readonly displayOrder?: GlobPattern[];
    readonly metadata: NotebookDocumentMetadata;
}

export interface NotebookContentProvider {
    open(uri: Uri): NotebookDocument;
}
```

We explored this approach for custom editors in previous API drafts

**Comment by jrieken** [comment]
> so it is quite late to be making significant changes to the API without very good reason to.

I know that but have a consistent API between custom editors and notebook editor is a very good reason.

> Can NotebookDocument be an abstract class?

It could but that wouldn't make it more similar to custom editors and it would introduce a new concept...
