### ISSUE TITLE
Scrolling in a browser affects scrolling in VS Code Studio

### ISSUE THREAD

**Issue by anegoda1995** [microsoft/vscode#95857]
When I scrolling in browser (Google Chrome version 80.0.3987.163 (Official Build) (64-bit)) by mouse wheel, then ALT-TAB (switch) to my VS Code and want to scroll something there by mouse wheel I see that my VS Code window jump as much as I scrolled in the browser window.

**Comment by Sumith1896** [comment]
Happens for me too, posted some more system/version details in https://github.com/microsoft/vscode/issues/96148 

please feel free to close it as a duplicate if this issue can be reproduced.

**Comment by franku** [comment]
Same applies when scrolling in the "konsole" terminal program.

**Comment by rebornix** [comment]
may I ask if you all are using Linux?

**Comment by franku** [comment]
This appeared for me on Fedora 32, will see if the same applies to 33; after a recent upgrade have to try first.

**Comment by franku** [comment]
Fedora 31: Mousewheel increments are "accumulated" somehow when using another application and switching back with Alt+Tab to either window, vs code or another application. Then, when using the mouse wheel, the first mouse increment applies the accumulated mouse increments (pls apologise my naive description).

Fedora 33: The first mousewheel increment after switching the window back to vs code with Alt+Tab is ignored. And it does not matter if I use the mousewheel in the previous application. This, however, is much better than the scrollbars jumping to a completely different window section as with Fedora 31.

From my point of view this is acceptable after switching to Fedora 33.

**Comment by rebornix** [comment]
@franku thanks for the detailed info! Are you seeing this issue with other applications (especially another Electron app) or just with VS Code?

**Comment by franku** [comment]
I also use Atom but cannot remember the scolling isuue.
