### ISSUE TITLE
Go To Line should include "filename.exenstion:line number" format

### ISSUE THREAD

**Issue by hughbe** [microsoft/vscode#95856]
In C# and visual studio stack traces we have the `filename.extension:line number`format

E.g. https://dev.azure.com/dnceng/public/_build/results?buildId=610643&view=ms.vss-test-web.build-test-results-tab&runId=19169530&resultId=108656&paneView=debug

>   at System.Windows.Forms.Tests.TabControlTabPageCollectionTests.TabPageCollection_CopyTo_InvokeNullGetItemsNotEmpty_Success() in D:\a\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\TabControl.TabPageCollectionTests.cs:line 1260

Using go to line (cmd+shift+o), we should be able to paste in something like `TabControl.TabPageCollectionTests.cs:line 1260` and be able to navigate to line `1260` of `TabControl.TabPageCollectionTests.cs`

**Comment by bpasero** [comment]
Open for a PR, code is in:

https://github.com/microsoft/vscode/blob/d342048538c28d54afd1c6beea03f3a89af04359/src/vs/workbench/contrib/search/common/search.ts#L113
