### ISSUE TITLE
Icons: defaultIcon.png should be just one

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#95859]
I am not sure that is possible, but I see a `defaultIcon.png` still in our sources.

**Comment by bpasero** [comment]
There are some more:

![image](https://user-images.githubusercontent.com/900690/79972095-b337e600-8495-11ea-9f2f-cf1d0076c1b1.png)

**Comment by misolori** [comment]
@sandy081 correct me if I'm wrong, but I don't believe we can use our icon font for extensions that don't have an extension image?

@bpasero the `letterpress*.svg` and `code-icon.svg` are the ones that are replaced in our build process with our brand icons. We can't turn these into an icon font as we've intentionally excluded our logos (for legal reasons). The others don't really relate to our product icons (extension icons, command palette is used in ui walkthrough)

**Comment by sandy081** [comment]
Yes you are correct.

**Comment by misolori** [comment]
In that case I'll close this since there isn't anything else we can do.

**Comment by bpasero** [comment]
@sandy081 but do we need 2 `defaultIcon`?

![image](https://user-images.githubusercontent.com/900690/80689609-e13cac00-8acd-11ea-8131-544e5af0e243.png)

**Comment by sandy081** [comment]
No one should be sufficient.

**Comment by bpasero** [comment]
I still see 2 icons, I think you missed to delete it.

**Comment by sandy081** [comment]
🤦🏻‍♂️
