### ISSUE TITLE
Cannot reference regex group for find and replace in Search Panel

### ISSUE THREAD

**Issue by Dekeyras** [Microsoft/vscode#9586]
- VSCode Version:  1.3.1
- OS Version: Win7

Steps to Reproduce:
1. Open the search panel
2. Click the regex search option
3. Enter a regex with a group
4. Open the replace text field
5. Reference the group from the Find text field with $1
6. Replace all

Expected:
$1 to replace with the match of the regex group

Actual:
Replaces with "$1" string instead

**Comment by sandy081** [comment]
Duplicates #9010
