### ISSUE TITLE
Add an option to show only folders in Open Recent

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#95865]
Issue Type: <b>Feature Request</b>

I use `File: Open Recent...` exclusively to switch projects, but there are a lot of files in there with similar names that get in the way.

It would be great to have an option to filter out files from that command (false by default) and leave only `workspaces`.

**Comment by sbatten** [comment]
So by default, the quick pick shows workspaces first, then files. So my assumption is that you would like this to hold even when searching. Do you think having higher priority for workspaces during search would help address the issue?

**Comment by usernamehw** [comment]
No, it would be unexpected for users. Ok, it's easier to write an extension for that.
