### ISSUE TITLE
Allow use of integer variables in tasks.json

### ISSUE THREAD

**Issue by dwilliamson** [microsoft/vscode#95866]
I'm trying to call `revealLine` from a task input as that allows variable substitution (unlike keybindings):

```
    "inputs": [
        {
            "id": "RevealLine",
            "type": "command",
            "command": "revealLine",
            "args":{
                "lineNumber": "${lineNumber}",
                "at": "center"
            },
        }
    ]
```
Obviously this fails because the command `revealLine` expects an integer as the first command. It works fine if I substitute `"${lineNumber}"` with any old integer.

Of course, this is a valid JSON file with no pre-process and I anticipate you want to keep this concept. But it occurs to me that the type matching between strings an integers could be loosened a bit, allowing this conversion. I may be useful elsewhere.

Thanks again for this great tool.

**Comment by alexr00** [comment]
This would require that the variable substitution know something about where the variable substitution is happening. Instead, you could very easily write your own command that takes a string lineNumber and converts it to a number before calling the revealLine command.

**Comment by dwilliamson** [comment]
Sorry, I'm unsure what this means: doesn't the variable substitution already happen in `tasks.json`? So as far as I'm aware the above piece of code ends up being presented to the command as:

```
"args":{
                "lineNumber": "123",
                "at": "center"
            },
```

The problem is that the command itself wants a `number` type, not a `string` type:
https://github.com/microsoft/vscode/blob/7c17748db7b43d11a5cd20563888da0519d1360d/src/vs/editor/browser/widget/codeEditorWidget.ts#L579-L590

I'm totally aware there are command extensions out there that can service my needs but I don't trust extensions as a rule and prefer to keep those installed to a minimum.

In this case a very simple addition would be to convert from string to integer but that may seem too specific. I've not dug any deeper into the code than this but I _hand-wave_ assumed there'd be some higher level point (e.g. https://github.com/microsoft/vscode/blob/a109b2561de478e23c29c139d2cc4ecc0776eb65/src/vs/editor/browser/controller/coreCommands.ts#L1482) that allowed you to be relaxed about the type of inputs you expect.

**Comment by alexr00** [comment]
@rebornix would you consider changing the reveal line command to handle a string for the lineNumber?

**Comment by rebornix** [comment]
@alexr00 we can support both `number | string`.

**Comment by rebornix** [comment]
Verifier, please test that you are not seeing warnings in keybindings editor when adding below

```
{
    "key": "cmd+i",
    "command": "revealLine",
    "args": {
      "lineNumber": "70",
      "at": "center"
    }
```

and also it works as expected

**Comment by weinand** [comment]
The title of this feature request no longer matches what was actually implemented to close the issue.

The feature "Allow use of integer variables in tasks.json" is still not supported.
But the command "revealLine" now supports a string and a number for the line number argument.

I've verified that "revealLine" now accepts a string argument.
