### ISSUE TITLE
Initializing JS/TS language features fails

### ISSUE THREAD

**Issue by lukaarma** [microsoft/vscode#95869]
Issue Type: <b>Bug</b>

Yesterday evening this problem started to appear on the stable build, so I tried to disable all extension and it kept happening.
So i tried to switch to insider verions but even after the first ever install and with no extension installed whatsoever it doesn't work

VS Code version: Code - Insiders 1.45.0-insider (9328b32008089c515f39a13db9c71e57c7d36823, 2020-04-22T08:44:55.510Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (6.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by lukaarma** [comment]
This might be a clone of #95515 , sorry if that's the case

**Comment by lukaarma** [comment]
This is the report generated from the stable build if it can help :)

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (6.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). After installing that and restarting VS Code, do you still see the issue?

**Comment by Libidine** [comment]
> Please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). After installing that and restarting VS Code, do you still see the issue?

This helped in my case, but do I now need to keep this extension enabled all the time?

**Comment by lukaarma** [comment]
Ok sorry I'm late but I didn't have time
Today I started VSCode for the first time in 4 days and it's working without any problem, even with extensions enabled, so I'm not sure what happened

I don't have a chance anymore to try what you suggested so I'm closing this, thanks for the help anyway!
