### ISSUE TITLE
Disable built-in tsLint messages on `// @flow` (flow.js) annotated files 

### ISSUE THREAD

**Issue by HotscriptGG** [microsoft/vscode#95871]
Please add an option to default JS&TS built-in plugin to disable tsLint messages on files which have explicit flow.js annotation `// @flow` at the top of the file.

![Zrzut ekranu 2020-04-22 o 14 23 30](https://user-images.githubusercontent.com/1574210/79981370-d8802080-84a4-11ea-9782-afe664c35e9f.png)

**Comment by IllusionMH** [comment]
This are TS messages not TSLint.

Did you follow steps described in https://github.com/flowtype/flow-for-vscode#setup to disable built-in support for JS?

**Comment by HotscriptGG** [comment]
You are right. Message comes from TS but it behaves sort of like a basic linter.

I am aware of https://github.com/flowtype/flow-for-vscode#setup but I don't want to disable amazing support which comes with the built-in js&ts plugin in the whole project. I am introducing Flow to a bigger codebase step by step and don't want to loose workflow for my teammates and me in the plain js files. It would be great to have an option to disable TS type annotation messages and red lines on files which use Flow keeping other benefits.

**Comment by IllusionMH** [comment]
I doubt that TS8010 (TS8008 etc.) will be the only problem.
Basically Flow syntax is invalid JS and if your plain JS files reference file with Flow annotations (especially like `{|prop: string|}` which would be also invalid TS) it won't be even possible to get exports from Flow file - so some of workflow would be "broken" at least in some places.
Therefore Flow should be responsible for whole workflow (anyway it should be this way in the end).

I'm might be wrong and also curious if there is solution :)

BTW there is https://github.com/microsoft/TypeScript/issues/35470 that might help in this case but now in case of exact types.

**Comment by mjbvz** [comment]
VS Code's built-in JS/TS targets standard JS and we've decided to leave Flow up to extensions.

If you want to use Flow, you need to follow their setup instructions. I know the story is not great for mixed projects but this is all caused by Flow's decision not to introduce a new file extension for the language

**Comment by mjbvz** [comment]
I should also add that the issue is larger than just about disabling a warning in flow files. The built-in JS/TS extension is not able to parse flow code, which means many of its basic features will either not work correctly and could even corrupt the file

**Comment by HotscriptGG** [comment]
Thank you for the reasonable answers.

Till next time 😎

**Comment by MatrixV01** [comment]
Super helpful information as I deal with this same error in my flow .js files using type. Thanks.
