### ISSUE TITLE
Do not make requests if token is not valid or session is signed out

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#95879]
Do not make requests if token is not valid or session is signed out

**Comment by connor4312** [comment]
@sandy081 do you have verification steps for this?

**Comment by sandy081** [comment]
There are no steps to verify. @Tyriar please check if the 401s on the server are reduced? or do code review as verification/

**Comment by Tyriar** [comment]
It seems to have only gotten worse, DM'd details.

**Comment by sandy081** [comment]
@Tyriar Guessing this is fixed, please verify.

**Comment by Tyriar** [comment]
There is only one remaining issue afaik which I just linked.

**Comment by Tyriar** [comment]
I think it is this same issue as the client retries 100 times after a 401.

**Comment by sandy081** [comment]
If the client sees successive (2) 401s then it shows following sign in notification to the user instead of retrying continuously. 

<img width="469" alt="image" src="https://user-images.githubusercontent.com/10746682/84141503-93fc1480-aa53-11ea-9e4b-f23def09c7db.png">

On first 401, client renews the token. If 401 happens again after renewal then there is something wrong with server or client. Hence a notification to sign in again is shown instead of retrying

**Comment by roblourens** [comment]
Is there a way to trigger this locally? Or @Tyriar are you able to verify?

**Comment by sandy081** [comment]
@Tyriar Can you please verify that if 401s are reduced on server?
