### ISSUE TITLE
Feature request: support capturing groups for regular expressions in find/replace.

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#9587]
Feature request: support capturing groups for regular expressions in find/replace.
- During a search in the editor, match each captured group to a selection, such that non-capturing groups are not selected but do provide context.

And possibly:
- Support references to the captured groups in the replace expression in both global and editor find/replace actions. The syntax for this should only be enabled if capturing groups are used.

(see #9444)

**Comment by roblourens** [comment]
> Support references to the captured groups in the replace expression in both global and editor find/replace actions

We do this now, with $1, $2, etc

I think the original request is unlikely
