### ISSUE TITLE
Settings sync should contribute its own timeline view

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95874]
Seems like an obvious and accessible place to expose readonly server versions for settings and keybindings. Then the current backups view can be only be for local backups which are more intended for disaster recovery.

![image](https://user-images.githubusercontent.com/2193314/79985727-e5c6ec00-845f-11ea-8f2c-a98231a92bc4.png)

To minimize requests to the server, we could take the following steps:

- Make sure it's only triggering when timeline is visible (I think this is covered within timeline itself?)
- Aggressively cache the version information and delete old versions following rules of the server without verifying with the server (I think its 20 versions max)

cc @eamodio

**Comment by sandy081** [comment]
Timeline view for settings and keybindings makes sense. IMO it shall include both local and remote versions as timeline can support multiple providers. 

Remote and Local backup views can still exist and be used to show a consolidated view.

**Comment by eamodio** [comment]
Sounds like a great use case. We might just need some tweaks to how we display the filename in the header depending on what the uri of the settings sync would be. I can probably look at the label formatter stuff for it too.

**Comment by sandy081** [comment]
/duplicate

#92166
