### ISSUE TITLE
Creating and running a shell task results in ugly output

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#95876]
If you do something like:
```
 const t = new vscode.Task({ type: 'shell' }, vscode.TaskScope.Global, `Shell ${++i}`, 'test', new vscode.ShellExecution('echo hello world'), []);
    await vscode.tasks.executeTask(t);
```
Then you end up with some ugly output in the tasks output.

**Comment by bwateratmsft** [comment]
The error output looks like this:
```
Error: the task 'Shell 0' neither specifies a command nor a dependsOn property. The task will be ignored. Its definition is:
{
    "type": "shell",
    "id": "shell,echo hello world,",
    "problemMatcher": [],
    "label": "Shell 0"
}
```

The task system does still execute the task, despite the error output. Additionally, I found that doing `t.definition.command = 'dummy';` _after_ the constructor makes the error go away, but still the correct command `echo hello world` is executed, allowing for the issue to be mitigated.

**Comment by alexr00** [comment]
Issue appears to be fixed now.
