### ISSUE TITLE
feature request: inline incremental search

### ISSUE THREAD

**Issue by siegebell** [microsoft/vscode#9588]
Feature request: [Visual Studio's incremental search](https://msdn.microsoft.com/en-us/library/f27e8wzh%28v=vs.90%29.aspx), with support for multiple cursors and regular expressions.

(See #9444)

**Comment by rebornix** [comment]
Our Find Widget is incremental at this moment. This one is more likely an inline incremental search, similar to Vim search.

**Comment by lascarayf** [comment]
Eclipse have this feature with "Ctrl+J" and "Ctrl+Shift+J" shortcuts. It's very useful.

**Comment by idanre1** [comment]
I would like to see incremental search as in emacs ctrl-s and ctrl-w within the search

**Comment by amunger** [comment]
From the description in the Visual Studio document, this is how the search widget currently works. Please provide the specific feature that is missing if you're still looking for further enhancements.

**Comment by idanre1** [comment]
Hi
I would repeat my former statement:
"emacs ctrl-s and ctrl-w"

I will provide with an example:
> The quick brown<b> fox</B> jumps over the lazy dog

Lets assure the cursor is near the `fox` word, click CTRL-F enters vscode to incremental search mode.

What is missing and exists in emacs:
During search mode while the cursor is still near `fox`, pressing in emacs CTRL-W, will automatically **increment** the search to `fox jumps` thus every press on ctrl-w will increment the search term with additional word.


That way you use the cursor to start the search and incrementally broaden the search term with more clicks.

There is also a keyboard shortcut to remove the last word from the search term.

Hope this added info would help to understand why vscode incremental search is inferior to emacs.
