### ISSUE TITLE
Introduce an `inline` group to debug/callstack/context

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#95887]
Refs: https://github.com/microsoft/vscode/issues/94812

Extensions should be able to contribute actions to be shown inline in items within the call stack view.

**Comment by isidorn** [comment]
As mentioned in the ref issue:

To start we will only support this on the debug session elements.

As the context when the contributed action is triggered on the session we would pass the session id to the extension. You can use the id to match the session, the only problem is that there is no API to get all sessions so you would have to store the session which you create, or to simply listen to our session creation events and store them.

**Comment by connor4312** [comment]
That's fine for me, js-debug already tracks its sessions for a range of existing functionality.

**Comment by isidorn** [comment]
I pushed a change to support this.
I tried out with a toy sample in Mock debug and this works nicely.
@connor4312 let me know how it goes once you try it out in js-debug. Also adding verification-needed so you can add verify if all is good.

Please note the following: all contributed actions will be shown at the debuging of the toolbar (as you designed in the original issue). If we want to support ordering we can do that but would require more refactoring.

**Comment by isidorn** [comment]
We should not forget to mention this in the release notes as it is a new contribution point!

**Comment by connor4312** [comment]
@isidorn I tried this and the button was there but the icon was not show (I could see the tooltip when I hovered where I should have been, I was able to click it). Both using a codicon and a local svg.

These were the two commands I tried: https://github.com/microsoft/vscode-js-debug/blob/882634f32da2d7311bfb710f04eeded5638b011f/src/build/generate-contributions.ts#L963-L974

As:

```js
{
  "command": "extension.NAMESPACE(node-debug).startProfile",
  "group": "inline",
  "icon": "$(circle-outline)",
  "when": " !jsDebugIsProfiling"
},
{
  "command": "extension.NAMESPACE(node-debug).stopProfile",
  "group": "inline",
  "icon": "resources/dark/stop-profiling.svg",
  "when": " jsDebugIsProfiling"
}
```

(I will add extra parts to the `when` condition, just made it simple for testing)

Also, it looks like the menu items aren't updated when the context keys change, the same bug we had with the debug toolbar earlier.

**Comment by isidorn** [comment]
@connor4312 thanks for trying it out! 
I pushed a change that the menu updates on context keys change.
Looking into the icons not being rendered...

**Comment by isidorn** [comment]
Ok I looked into it and could not figure it out.
@jrieken @bpasero is there some secret sauce that I am missing to allow extensions to contribute icons to a menu. Action nicely gets added with title text but there is no icon. Looking at the css, the rule to apply the image is not there.
When adding the actions to the actionBar I am using the `add({icon: true`

**Comment by jrieken** [comment]
needs more context. @connor4312 refers to commands defined inside code which puzzles me. This should only work when defining commands inside package.json. For the tweak Idk if there is anything special, check if SCM is doing anything different?

**Comment by isidorn** [comment]
Ok I this required some hard core digging to Moria to figure out that I need to have a `MenuEntryActionViewItem` for my contributed icon to be rendered

So this should now work nicely. @connor4312 please try it out. Thanks
![Screenshot 2020-04-27 at 15 10 49](https://user-images.githubusercontent.com/1926584/80376408-0e087d80-889a-11ea-830d-df85cf29ed2b.png)

**Comment by connor4312** [comment]
> refers to commands defined inside code which puzzles me

we automate some of the js-debug package.json generation. Saves repetition since many options are shared between debug types, and lets us type-check to contributions to ensure that e.g. all options are documented and all strings are localized.

> So this should now work nicely

Validated out of sources, works beautifully, thanks!

![](https://memes.peet.io/img/20-04-37e79641-b1aa-442b-9674-5857e2c55fa5.png)
