### ISSUE TITLE
"Cannot launch program" when debugging file with no extension with node

### ISSUE THREAD

**Issue by zzptichka** [microsoft/vscode#95889]
- VSCode Version: 1.44.2
- OS Version: Ubuntu 18.04

Steps to Reproduce:

Simple project with 2 files:
**main**
```  
    #!/usr/bin/nodejs
    console.log("hi");
```
**launch.json**
```
{
     "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/main"
        }
    ]
}
```

Does this issue occur when all extensions are disabled?: Yes

When trying to debug I'm getting "Cannot launch program... Setting outFiles might help" error.
Running `node main` or `main` in terminal obviously works just fine.
If I rename main file to main.js and change "program" parameter to "main.js" in launch.json everything works.
Don't see why file extension should be mandatory. For example, `express-generator` generates project with no extension by default.

**Comment by zzptichka** [comment]
It appears changing `#!/usr/bin/nodejs` shebang to portable `#!/usr/bin/env nodejs` solves it

**Comment by connor4312** [comment]
This is a known behavior with the current debugger; it will require outFiles if the file doesn't end with `.js` and doesn't have that specific hashbang. If you run into this elsewhere, you could try using our [new debugger](https://github.com/microsoft/vscode-js-debug) which does not have this behavior.

Related: https://github.com/microsoft/vscode/issues/89882
