### ISSUE TITLE
"Extension 'ESLint' cannot format 'File.ts'", then it does

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#95880]
I have eslint set up to format on save, and it does, but it also puts a notification in the status bar saying that it cannot. 

![Kapture 2020-04-22 at 7 06 30](https://user-images.githubusercontent.com/8586769/79992052-d77cce00-8467-11ea-8814-75a17a0efc82.gif)

Repro: https://github.com/JacksonKearl/eslint-cannot-format-repro

https://github.com/microsoft/vscode/blob/43bfc2cda0bf7e5f4d037d06e39754e878bc2a90/src/vs/workbench/contrib/format/browser/formatActionsMultiple.ts#L95-L101

**Comment by jrieken** [comment]
@db to confirm but afaik ESLint is not a formatter, e.g it doesn't contribute into the "Format Document" command but it contributes code actions. Now, the line between code actions and formatting is blurry but in our API and features it's pretty crisp: An extension that calls "registerFormattingProvider" is a formatter (and hence part of the formatting flows) and an extension that calls "registerCodeActionProvider" is not a formatter, but used for fixes, refactorings, and clean-up.

**Comment by dbaeumer** [comment]
@jrieken ESLint does contribute a formatter if the setting `eslint.format.enable` is set to true. In this case it dynamically registers a formatter provider.

**Comment by dbaeumer** [comment]
@JacksonKearl do you have code actions on save enabled as well. If so I guess the formatting happens because of that. But it still doesn't explain the message unless `eslint.format.enable` is not set to true.

**Comment by JacksonKearl** [comment]
I had `"editor.defaultFormatter": "dbaeumer.vscode-eslint"` but not `"eslint.format.enable": true,`, that probably explains it. Is there benefit to using it as a formatter rather than just applying the code actions on save?

**Comment by dbaeumer** [comment]
Only benefit is that you can invoke the formatter with the default formatter key binding. I personally prefer code action on save. 

Closing the issue. Please ping if you think otherwise.
