### ISSUE TITLE
Login use one user and act as another user.

### ISSUE THREAD

**Issue by allstable** [microsoft/vscode#95881]
Hello, here is an new request.
Image this situation: 
    Connect the remote host through a general user,which has only little privilege, and then elevate its privilege to a super user,let us say root. We need to do the work under the root user.
    So, in VS Code, how can I make it? Becuase there is a situation where we can only use the general user to connect to the remote host. 
   Looking for the reply,thanks so much.
More info: 
    Login the remote host through a general user,but then need to switch to root(in the VS Code User Interface,not the VS Code Terminal),the files are down root home directory.Just like below:

<img width="884" alt="图片" src="https://user-images.githubusercontent.com/25278505/80048105-d0c28980-8541-11ea-8163-64f81e1f4d88.png">

**Comment by allstable** [comment]
> Hello, here is an new request.
> Image this situation:
> Connect the remote host through a general user,which has only little privilege, and then elevate its privilege to a super user,let us say root. We need to do the work under the root user.
> So, in VS Code, how can I make it? Becuase there is a situation where we can only use the general user to connect to the remote host.
> Looking for the reply,thanks so much.
> More info:
> Login the remote host through a general user,but then need to switch to root(in the VS Code User Interface,not the VS Code Terminal),the files are down root home directory.Just like below:
> 
> <img alt="图片" width="884" src="https://user-images.githubusercontent.com/25278505/80048105-d0c28980-8541-11ea-8163-64f81e1f4d88.png">

<img width="884" alt="图片" src="https://user-images.githubusercontent.com/25278505/80048200-154e2500-8542-11ea-9d95-6af94576ba07.png">

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/690
