### ISSUE TITLE
watch task fails to pick up refactoring of interfaces

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#95893]
Issue Type: <b>Bug</b>

Both @isidorn and me ran into this issue when we refactored interfaces, the changes are not picked up by the watch task. For example, if I can change below interface

```ts
export interface A {
  func(): void;
}
```

to

```ts
export interface A {
  func(): Promise<void>;
}
```

Our `gulp watch` is fine with the change, no errors/warnings emitted. However it does break the build. @isidorn is refactoring in a different way but ran into the problem.

VS Code version: Code - Insiders 1.45.0-insider (9328b32008089c515f39a13db9c71e57c7d36823, 2020-04-22T08:41:53.798Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (2.82GB free)|
|Process Argv|-psn_0_14368179|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
gitlens|eam|10.2.1
tsl-problem-matcher|eam|0.1.1
vscode-pull-request-github-insiders|Git|2020.4.31142
vscode-docker|ms-|1.1.0
vscode-language-pack-zh-hans|MS-|1.45.0
remote-containers|ms-|0.112.0
remote-ssh-edit-nightly|ms-|2020.4.9540
remote-ssh-nightly|ms-|2020.4.9540
js-debug-nightly|ms-|2020.4.1517
powershell|ms-|2020.4.0
vscode-github-issue-notebooks|ms-|0.0.10
vsliveshare|ms-|1.0.2000
debugger-for-chrome|msj|4.12.6
kuskus-extensions-pack|ros|1.0.1
kuskus-kusto-language-server|ros|1.0.1
kuskus-kusto-syntax-highlighting|ros|1.1.8
sourcekit-lsp|unp|0.0.1

(4 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
My refactoring was that I added a required method to an interface.
And the build did not pick up all the users of the interface

**Comment by jrieken** [comment]
I am sorry but there will be no more changes being made to `gulp-tsb`. TypeScript finally provides  the fast-and-loose compilation mode and we have somewhat successfully tested that already. It's just a matter of getting that into our gulp-pipeline.
