### ISSUE TITLE
Max file watcher as a user setting instead of admin

### ISSUE THREAD

**Issue by rusu24edward** [microsoft/vscode#95898]
I'm running into the classic `Visual Studio Code is unable to watch for file changes in this large workspace` problem. The [resolution](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc) for this problem is very clear! Unfortunately, I'm ssh'ed to a system where I am not an admin and do not have access to `/etc/sysctl.conf`.

Is it possible to make this a user configurable settings instead of/in addition to a setting in sysctl.conf?

**Comment by bpasero** [comment]
No, not that to my knowledge.
