### ISSUE TITLE
[folding] // region foldings do not work

### ISSUE THREAD

**Issue by Hauptsatana** [microsoft/vscode#95895]
Issue Type: <b>Bug</b>

Editor does not detect region folding [as stated in docs](https://code.visualstudio.com/docs/editor/codebasics#_folding) when it is written as `// region` with something inside block.

![image](https://user-images.githubusercontent.com/4078263/80008708-89a4ac00-84e1-11ea-85f5-eb4f09e42a27.png)

while `// #region` and empty `// region` works fine.

![image](https://user-images.githubusercontent.com/4078263/80008358-1438db80-84e1-11ea-9bd4-0a34d42fc858.png)

![image](https://user-images.githubusercontent.com/4078263/80008600-6679fc80-84e1-11ea-8b3d-c904f3192664.png)

Also tested that on clean setup of VS Code and VS Code Insiders (no extensions)
VS Code version: Code - Insiders 1.45.0-insider (9328b32008089c515f39a13db9c71e57c7d36823, 2020-04-22T08:44:55.510Z)
OS version: Windows_NT x64 6.1.7601

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8350 Eight-Core Processor            (8 x 4013)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (3.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.1.5
githistory|don|0.6.3
xml|Dot|2.5.0
gitlens|eam|10.2.1
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.2
todo-tree|Gru|0.0.172
XMLLanguageSupport|IBM|0.0.1
icon-fonts|idl|2.3.0
markdown-shortcuts|mdi|0.12.0
cpptools|ms-|0.27.0
vscode-typescript-tslint-plugin|ms-|1.2.3
java|red|0.60.0
aspnet-helper|sch|0.6.4
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2
gitblame|wad|3.2.0
vscode-todo-highlight|way|1.0.4
wilderminds-aspnetcore-snippets|wil|0.2.1
markdown-all-in-one|yzh|2.8.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by KissInno** [comment]
Same issue with me.
Very strange, it was running fine for months up to today :-(
Did you find a fix pelase?

**Comment by aeschli** [comment]
Folding regions come from the TS server. Maybe a change in TypeScript?

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/microsoft/TypeScript/issues/29379

**Comment by mjbvz** [comment]
I'm going to update our docs though since only `//#region` currently works

**Comment by dufferzafar** [comment]
@mjbvz Is there similar support for the JSON file types? (or JSON with comments?)

Neither of `//region` or `//#region` work in such cases.

**Comment by aeschli** [comment]
@dufferzafar Each language defines the region pattern it supports. The request to add also region markers for JSONC is https://github.com/microsoft/vscode/issues/95287
