### ISSUE TITLE
UX for an empty notebook

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#95903]
We prevent the user from emptying a notebook - if the last cell is deleted, we insert a new empty cell. But a notebook provider can still cause an empty cell to be created either by resolving a notebook to have no cells or deleting cells programmatically.

We could

- Make this an error, say notebooks have to return at least one cell
- Insert an empty cell, which would make the document dirty upon opening
- Show some nice UX which explains that the notebook is empty and has buttons to insert a cell

**Comment by rebornix** [comment]
Me personally prefer the last one

> Show some nice UX which explains that the notebook is empty and has buttons to insert a cell

It's weird to me that you can't have an empty notebook. Users might delete all cells to get a clean state to restart the work while showing errors or inserting empty cells immediately seems like the editor tries to fight back.

**Comment by roblourens** [comment]
@rebornix added a toolbar when it's empty, I think this is enough
