### ISSUE TITLE
Delete output cell in notebook

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#95907]
- notebooks should provide Clear Output out of the box
- I should be able to clear output using the keyboard

### challenges
- if a cell has more than one output cell,  can I delete only one of them? If we allow to delete individual output cells we need a way to focus them with the keyboard. So far, we only focus input and output together
- I'd like to use `Backspace` to delete the output cell(s) if there are any, and I'd like to use `Backspace` to delete the cell if there is no output. I could accomplish that if we had a context key `hasOutput`

**Comment by rebornix** [comment]
For April we can move the clear output actions into the core first.

**Comment by rebornix** [comment]
Moved *Clear Active Cell Output* and *Clear All Cells Outputs* into core and added a new context key `notebookCellHasOutputs`. I use below keybinding to conditionally clear outputs.

```json
  {
    "key": "alt+Backspace",
    "command": "workbench.action.notebook.clearCellOutputs",
    "when": "notebookEditorFocused && notebookCellHasOutputs"
  }
```

For deleting individual cell output, let's look into it next iteration.

**Comment by rebornix** [comment]
We support both commands now in the core.

**Comment by rebornix** [comment]
The only command missing now is deleting an individual output.

**Comment by roblourens** [comment]
Related to this request for Copy and other commands on individual outputs https://github.com/microsoft/vscode/issues/124917

**Comment by tanhakabir** [comment]
I also think clearing all outputs for one cell seems sufficient to me. Closing this issue but feel free to open it if you think otherwise!
