### ISSUE TITLE
editor.action.refactor default keybinding has no args, causes warning

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95909]
I was just fixing https://github.com/microsoft/vscode/issues/94556 to show args and I noticed that this one actually doesn't have any args by default (see default keybindings file).

![image](https://user-images.githubusercontent.com/2193314/80022109-6f8ead80-8490-11ea-8d59-e445c987db7c.png)

Seems like args should not be required for the command then.

**Comment by Tyriar** [comment]
Doesn't seem to be fixed?

![image](https://user-images.githubusercontent.com/2193314/80109849-dd8bb100-8532-11ea-8e35-d015c4c1fe5f.png)

**Comment by Tyriar** [comment]
@mjbvz I wouldn't think that last commit would fix it either and may actually cause another bug. Not sure why it's being marked as mandatory.

This is sendSequence which is not mandatory but the `text` arg is:

https://github.com/microsoft/vscode/blob/34a9a5e080a0ef14ee0ba1944e79e4a698dbf62b/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L1062-L1087

**Comment by mjbvz** [comment]
I confirmed that this issue is fixed for me in the build from master. I believe it has something to do with how we use a conditional schema to provide IntelliSense for the refactor arguments

We should also allow `kind` to be undefined for this command

Let me know if you still see the error
