### ISSUE TITLE
Include .editorconfig support in Code by default

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/vscode#95902]
I want to pick up the discussion from https://github.com/microsoft/vscode/issues/56742 again. I think .editorconfig support should be included by default, not requiring an extension. VS2019 did that and it was a huge productivity boost. I know installing VS extensions is more difficult than VSCode extensions but it would still help a lot of people, knowing that support is included by default and being able to rely on it.

Default support for `.editorconfig` files and applying it's rules in VS Code.

**Comment by Tyriar** [comment]
:-1: it's already a recommended extension which shows a notification when you have `.editorconfig` in the folder. Bundling = bloating. Plus settings sync is around the corner so you wouldn't need to worry about it ever again after installing the first time if you sign in.

**Comment by Stanzilla** [comment]
My personal use case is having to tell teammates that they have to install it instead of it just working out of the box. I agree on bloating concerns but yeah...

**Comment by Tyriar** [comment]
I guess they ignore the recommendation 🤷‍♂️

**Comment by Stanzilla** [comment]
Pretty much yes, I see it as a requirement not a recommendation.

**Comment by Tyriar** [comment]
Even without the bloat point, the extension is an effort by the community and I don't think we could include it in the product we ship without taking ownership of it as well. I get your argument and I was on that side as well a while ago, but don't think you'll be able to convince anyone in the team to bundle it 🙂
