### ISSUE TITLE
Notenbooks should respect `editor.scrollBeyondLastLine`

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#95905]
I have set this to `false`. The notebook editor does not respect this.

**Comment by rebornix** [comment]
Good catch, we should use this same editor option from Monaco to control this feature.

**Comment by bpasero** [comment]
I do not see any difference changing this in the notebook.

**Comment by JacksonKearl** [comment]
@bpasero `editor.scrollBeyondLastLine` allows you to scroll untill the bottommost cell is at the top of the screen. When it's false you can't scroll beyond it being at the bottom of the screen.
