### ISSUE TITLE
Custom dialog icons don't have the correct color tokens

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#95900]
![image](https://user-images.githubusercontent.com/35271042/80015594-d6a76480-8486-11ea-8171-a661a498dc5a.png)

These all have the Info/Warning/Error icons and used the respective colors.

cc @sbatten

**Comment by aeschli** [comment]
I pushed a proper fix. As the dialog is in base it should get all colors as arguments.
What's done in SeverityIcon is a hack. All these rules should go to the corresponding components

**Comment by aeschli** [comment]
To verify:
- set `"workbench.dialogs.customEnabled": true`
- close an editor with unsaved content
