### ISSUE TITLE
Clearing an environment variable causes relaunch terminal button to get stuck

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#95919]
1. Create an environment variable collection and apply it to your terminal
2. Clear the collection
3. Relaunching the terminal doesn't dismiss the button (It seems to unset the variables in the terminal correctly, just the button sticks around)

```
Version: 1.45.0-insider (user setup)
Commit: bd262894bbaac5156d5bf832160b7056c91decea
Date: 2020-04-22T17:16:24.886Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

![](https://memes.peet.io/img/20-04-1056ddb9-fc31-405e-a8d3-0dde13906b02.gif)

**Comment by Tyriar** [comment]
Hmm, haven't seen this. I guess it's an edge case with removing variables that I didn't test.
