### ISSUE TITLE
Allow autocomplete suggestions while filling out code snippet placeholders

### ISSUE THREAD

**Issue by GlenNicholls** [microsoft/vscode#95917]
Issue Type: <b>Feature Request</b>

When filling out code snippet placeholders (e.g. `${arg}`), autocomplete suggestions do not work. If I'm inserting an `if` snippet in Python for example, I do not get autocomplete suggestions as I type variable names.

Lets say I have the following

```
var1 = 1
var2 = 2
```

When I start to type `if`, the snippet suggestion for that code snippet shows and I hit `TAB` to confirm it so I get the following:

```
if expression:
    pass
```

as I start typing in the `expression` field, I would like to still see autocomplete suggestions. E.g. when I start to type `var`, I should see suggestions for `var1` and `var2`. The only time that autocomplete suggestions should not show is if the code snippet template is having the user fill in placeholders within a comment. In code snippets of actual code, autocomplete should still work.

I'm not sure if this is a bug, but this feature doesn't exist so I marked it as a feature request.

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18362

**Comment by usernamehw** [comment]
```js
"editor.suggest.snippetsPreventQuickSuggestions": false,
```
