### ISSUE TITLE
Use annotation to search for excluded file by name

### ISSUE THREAD

**Issue by jpenna** [microsoft/vscode#95918]
Sometimes I want to search a file in `node_modules` or another excluded folder. It would be really nice to write a symbol before a file name to tell VS Code to include (or include only) excluded files. 

Something like the following (using `~` in this case, but it could be `^` or anything):

<img width="615" alt="Screen Shot 2020-04-22 at 5 22 33 PM" src="https://user-images.githubusercontent.com/16005946/80030004-002fb280-84be-11ea-80e7-fe4b811cc51e.png">

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/15604
