### ISSUE TITLE
Debug does not stop at break point

### ISSUE THREAD

**Issue by pseudocyber** [microsoft/vscode#95927]
Issue Type: <b>Bug</b>

I have a simple python 3.8.2 script, with a break point set.  Debug will run, but will not stop at the breakpoint.  I have uninstalled, and re-installed VSC.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (23.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.4.74986

</details>

**Comment by pseudocyber** [comment]
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File (Integrated Terminal)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
        }
    ]
}`

**Comment by mwpenny** [comment]
I am experiencing the same issue when trying to debug TypeScript code. My launch config starts a process which builds my code and then starts a runner process, then VSCode attaches to the runner process which I can manually trigger to call my code. `outFiles` is correctly pointing to the generated JS.

I'm not sure exactly when this broke for my project but it used to work. Strangely, if I launch my build+runner process manually and then attach VSCode the the runner process ("attach" request in the launch config) then the breakpoint is hit when I trigger the runner.
