### ISSUE TITLE
Multi desktop

### ISSUE THREAD

**Issue by HaLeiVi** [microsoft/vscode#95925]
VS Code misbehaves with multiple desktops. The desired behavior would be, like ther applications, when openening a file (associated with VS Code) to open a new window on the new desktop even if there is already an instance on another desktop.

Moreover, even when I already have it open on both desktops, when I open an associated file, it will go to the last used window, even if that is on a desktop other than the active one.

**Comment by sbatten** [comment]
please see the setting `window.openFilesInNewWindow`

**Comment by HaLeiVi** [comment]
Why did you close this before confirming this addresses the issue? It doesn't.
The way it handles new files is fine. The issue is that it moves to another desktop. Te desired behavior of most applications is to ignore open instances of other desktops.

**Comment by sbatten** [comment]
That is what the setting addresses, not new files.

**Comment by AragornJIA** [comment]
what we ask is that it will open a new window at different virtual desktop, and open a tap at the same window when we open a new file.
