### ISSUE TITLE
debugger not showing watch and callstack

### ISSUE THREAD

**Issue by salong3** [microsoft/vscode#95920]
- VSCode Version: ff915844
- OS Version: Ubuntu 18.04

Steps to Reproduce:

I can debug file normally but the watch and callstack tabs do not appear. I have tried uninstalling and reinstalling vs code and replacing the .vscode and the issue still persists. 

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by salong3** [comment]
![debugThing4](https://user-images.githubusercontent.com/64167406/80032508-1e86b580-84a0-11ea-90d9-f8c54b903ac9.PNG)

**Comment by sbatten** [comment]
@salong3 can you please right-click where it says RUN at the top of the view? Are `Watch` and `Callstack` present in the menu? Are they checked?

**Comment by salong3** [comment]
I was able to fix the problem by creating a new user. There was some config file that i missed somewhere.
