### ISSUE TITLE
Add commands to execute Document[Range]SemanticTokensProvider

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#95922]
+ Add `vscode.executeDocumentSemanticTokensProvider` - Execute document semantic tokens provider.
  - *uri* - Uri of a text document
+ Add `vscode.executeDocumentRangeSemanticTokensProvider` - Execute document range semantic tokens provider.
  - *uri* - Uri of a text document
  - *range* - Range in a text document

I am working on an extension that needs to analyze a file and find certain tokens. I am relying on `vscode-go` to provide language features, but I can't see any way for my extension to get a list of semantic tokens in the document. The only thing that comes close is `vscode.executeDocumentSymbolProvider`, but that does not do what I need.

**Comment by alexdima** [comment]
Duplicate of #91375
