### ISSUE TITLE
Show Gravatar on the details of commits in Timeline view

### ISSUE THREAD

**Issue by Diogo-Rossi** [microsoft/vscode#95934]
The new feature "Time line view" allows to view information about specific commits (author, e-mail, date and time of commit, commit message, etc . . .) when we "rest the mouse cursor" over the commit item.

Could these information include the **Gravatar image** of the author?

**Comment by lszomoru** [comment]
The `Commits` view is being contributed by the GitLens extension, which the `Timeline` view is part of VS Code. Looking at the Timeline API, it seems that currently it only supports providing an icon for the timeline item. I will reach out to the API owner to see if there are any plans to enable the scenario in which we can display the avatar.

**Comment by JacksonKearl** [comment]
Nothing in the works for increasing the scope of timeline item icons.

**Comment by lszomoru** [comment]
Given the lack of API, I will be closing this issue.

**Comment by JacksonKearl** [comment]
I misread the issue, this has to do with the timeline hovers, which do now support markdown. This is the same as #143170
