### ISSUE TITLE
nvm change node version failure!

### ISSUE THREAD

**Issue by xcondor** [microsoft/vscode#95931]
Issue Type: <b>Feature Request</b>

It's failure when I change  node version by nvm use command. 
ex: 
nvm use 13.6.0 
command display: Now using node v13.6.0(npm v6.13.4)
BUT,  In Fact, It's use node 6.7.0

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 17.7.0

**Comment by alexr00** [comment]
Let me make sure I understand:

In a terminal you do an `nvm use` to change the node version.
The terminal now uses the correct node version.
VS Code still uses the old node version.

Is that what you're seeing?

**Comment by xcondor** [comment]
> Let me make sure I understand:
> 
> In a terminal you do an `nvm use` to change the node version.
> The terminal now uses the correct node version.
> VS Code still uses the old node version.
> 
> Is that what you're seeing?

Yes, It' is.
