### ISSUE TITLE
Dynamically toggle linting for a file

### ISSUE THREAD

**Issue by waynehoover** [microsoft/vscode#95933]
I would like to dynamically toggle linting for a file. For example I might open up a random file from the internet to look at that is hard to read because nearly every line has a lint warning underline. 

I would like to turn off linting for just this file while i'm looking at it, then toggle it back on possibly too.

**Comment by sandy081** [comment]
This is similar to the request to clear diagnostics. Hence marking this as duplicate.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/66982
