### ISSUE TITLE
Semantic Highlighting: fontStyle doesn't seem to function correctly

### ISSUE THREAD

**Issue by CleanCut** [microsoft/vscode#95932]
I can't find a way to _replace_ a `fontStyle` that is `underline` in the selected theme with one that is only italic (no underline).  It appears a user-specified `fontStyle` merges with the default `fontStyle` to create a style that is the sum of all the parts, with no way to selectively remove part of the style.  If the user definition _replaced_ the default 

- VSCode 1.44.2 ff915844119ce9485abfe8aa9076ec76b5300ddd and 1.45.0-insider ec0d19789f89d4c25895f4a0cf364276cfb0c6ed
- OS Version: macOS 10.15.4 (19E287)

Steps to Reproduce:

0. Select the `monokai` theme
1. [Install Rust](https://www.rust-lang.org/learn/get-started) on your system, and the `rust-analyzer` plugin (yes when it prompts you to download the thing)
2. Create a new rust project (`cargo new scratch`) and open it in VSCode
3. Add the following code to the top of `src/main.rs`:
```rust
trait MyTrait {}
struct MyStruct;
impl MyTrait for MyStruct {}
```
4. Notice that `MyTrait` is green and underlined (once Semantic Highlighting has kicked in).
<img width="428" alt="image" src="https://user-images.githubusercontent.com/5838512/79876418-409d0c80-83a8-11ea-9293-e33e021e38b7.png">

5. Attempt to replace the underline with italics in `settings.json`.  

```json
    "editor.tokenColorCustomizationsExperimental": {
        "interface": {
            "fontStyle": "italic"
        }
    },
```

It adds italics but leaves the underline, when it should have replaced the underline.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/5838512/79880146-d89cf500-83ac-11ea-84b4-3def5b461a5e.png">

Leaving `fontStyle` blank is supposed to clear the style entirely, but by itself without an accompanying `foreground` it does absolutely nothing (style remains underlined).
```json
    "editor.tokenColorCustomizationsExperimental": {
        "interface": {
            "fontStyle": ""
        }
    },
```
<img width="373" alt="image" src="https://user-images.githubusercontent.com/5838512/79880467-477a4e00-83ad-11ea-9e2c-59509959873c.png">

However, if you add a foreground color then a blank `fontStyle` suddenly starts clearing the style like it is supposed to:
```json
    "editor.tokenColorCustomizationsExperimental": {
        "interface": {
            "foreground": "#ff8800",
            "fontStyle": ""
        }
    },
```
<img width="329" alt="image" src="https://user-images.githubusercontent.com/5838512/79880561-6b3d9400-83ad-11ea-8a40-4560309708ea.png">

But even with a new foreground, an italic `fontStyle` does not replace the underline:
```json
    "editor.tokenColorCustomizationsExperimental": {
        "interface": {
            "foreground": "#ff8800",
            "fontStyle": "italic"
        }
    },
```
<img width="409" alt="image" src="https://user-images.githubusercontent.com/5838512/79880654-89a38f80-83ad-11ea-9eb2-ef326835a6c5.png">

#

Does this issue occur when all extensions are disabled?: N/A - if I disable extensions, then Semantic Highlighting won't work for Rust.

**Comment by aeschli** [comment]
I fixed that `"fontStyle": ""` doesn't not clear all styles.
Also, now `fontStyle` sets/clears all styles, like it does in in TextMate theme.
To set or unset individual styles, I added properties `bold`, `italic`, and `underline` in addition to `fontStyle`. Note: `fontStyle` wins against `bold`, `italic`, and `underline`

**Comment by CleanCut** [comment]
@aeschli Thanks!
