### ISSUE TITLE
Source control pane steals focus when `git add` completes

### ISSUE THREAD

**Issue by markdefalco** [microsoft/vscode#95940]
Issue Type: <b>Bug</b>

1. Modify some files in a git repo
2. Select one or more files in the Source Control pane.
3. Click '+' to stage those files
4. Click in your terminal and start typing 'git commit -m"

Expected: I can complete writing my commandline instruction

Actual: Source Control pane steals focus back and starts searching for some sequence of letters I've just typed mid-command.

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (4.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.2.1
prettier-vscode|esb|4.5.0
svg|joc|1.1.7
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-stylelint|sty|0.84.0

</details>

**Comment by joaomoreno** [comment]
Very similar to https://github.com/microsoft/vscode/issues/92401

Is there any reason why you're not using the commit box instead of using the terminal to commit?

**Comment by markdefalco** [comment]
That does look like a dupe.

I have no reason to not use the commit box, I'm just used to doing 90% of git commands via commandline, The UI is a much quicker way to add/remove files from stage.  I'm also not always doing a commit right after, I may be creating a new branch, stashing, or running some other command.
