### ISSUE TITLE
Tree: Clicking on folder twisties should expand/collapse

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#95948]
Hello,

I have the `"workbench.list.openMode"` option set to `"doubleClick"`, so the folders are opened after double-clicking.

But if you click the arrow:
![image](https://user-images.githubusercontent.com/30685349/80068635-3f064c80-8540-11ea-9aa8-16d006bbbde3.png)
then the folder is expanded with one click (this demarcation is very helpful)

Can you add an option that will make the folder icons behave like the default arrows?
I would like to hide the arrows, keeping the one-click function on the folder icons

**Comment by joaomoreno** [comment]
This reproduces on themes like Ayu in which the twisties are hidden and only the folders show.

**Comment by joaomoreno** [comment]
With the latest changes, folders actually expand on single click, despite this setting. I think this is actually good behavior since nothing really opens when you click it. Let's see if users complain.
