### ISSUE TITLE
typing is not coming correct

### ISSUE THREAD

**Issue by Najibvenkitta** [microsoft/vscode#95943]
while coding html it very difficult to code space and enter key are not working properly

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version, platform, step by step repro. A video or animated gif could help.

**Comment by Zooce** [comment]
I've noticed something odd with typing in the editor as well. I don't know how it happens, but I'll be editing some text, then doing some stuff in the integrated terminal (zsh for me), then all of a sudden in the editor I can no longer use the Enter key to write new lines, while using Command+Enter does write new lines.

OS: macOS 10.15.4
**About VS Code:**
Version: 1.45.0-insider
Commit: a250df703de955a38aed427a917bce8278ab3331
Date: 2020-04-24T20:46:59.782Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by alexdima** [comment]
@Zooce This most likely indicates that there is some keybinding customization bound to `"Enter"`. Can you please open the Keyboard Shortcuts and search for `"Enter"` with quotes. How does it look, here is mine:
![image](https://user-images.githubusercontent.com/5047891/80414610-98200880-88d1-11ea-98e6-46e0ed778989.png)

@Najibvenkitta  Please provide additional information and some steps.

**Comment by Zooce** [comment]
Oh interesting. I think my issue is being caused by `rust-analyzer.onEnter` which is its "Enhanced enter key".

For reference:
* https://github.com/rust-analyzer/rust-analyzer/issues/4052
* https://github.com/rust-analyzer/rust-analyzer/issues/4050

**Comment by alexdima** [comment]
FYI, as a workaround, you can unbind their keybinding.
