### ISSUE TITLE
Identifiers are colored in bold when targetting keywords

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#95949]
- Have a TS file with a constant variable declaration, e.g.:
```ts
const something = 3
```
- Have the following settings:
```js
"workbench.colorTheme": "Default Light+",
"editor.tokenColorCustomizations": {
  "textMateRules": [
    { "scope": "storage.type.ts", "settings": { "fontStyle": "bold" } },
  ]
}
```
- Open in VS Code stable (with semantic highlighting enabled)
![image](https://user-images.githubusercontent.com/5047891/80072335-63652780-8546-11ea-9273-81f2e8033f1f.png)
- Open in VS Code Insiders (with semantic highlighting enabled)
![image](https://user-images.githubusercontent.com/5047891/80072424-81328c80-8546-11ea-8033-5307a8105eb5.png)

---

Some more observations. The issue is resolved in Insiders by doing:

```js
"workbench.colorTheme": "Default Light+",
"editor.tokenColorCustomizations": {
  "textMateRules": [
    { "scope": "storage.type.ts", "settings": { "fontStyle": "bold" } },
    { "scope": "variable.other.constant", "settings": { "foreground": "#001" } }
  ]
}
```

But in the most crazy twist, the issue appears again when changing the color from `#001` to `#000`:
```js
"workbench.colorTheme": "Default Light+",
"editor.tokenColorCustomizations": {
  "textMateRules": [
    { "scope": "storage.type.ts", "settings": { "fontStyle": "bold" } },
    { "scope": "variable.other.constant", "settings": { "foreground": "#000" } }
  ]
}
```

**Comment by aeschli** [comment]
No longer see this is Version: 1.45.0-insider
Commit: a250df703de955a38aed427a917bce8278ab3331
Date: 2020-04-24T09:57:20.729Z

and also not from source.

@alexdima Same for you?

**Comment by aeschli** [comment]
I don't see it from source, but (again) in Version: 1.45.0-insider
Commit: a250df703de955a38aed427a917bce8278ab3331
Date: 2020-04-24T09:57:20.729Z

- settings as above (first example)
- set log level: Trace
- ts file with single line content `const foo`
   - without semicolon: `foo` not bold
   - with semicolon `foo` bold
- check log: `TRACE tokenStyleMetadata variable declaration readonly: foreground 1, fontStyle 0`
(or set breakpoint at `ColorThemeData.getTokenStyleMetadata`
-> no style returned

Maybe a bug when merging syntax and semantic tokens?




```

**Comment by aeschli** [comment]
Bug is in the merge: 
https://github.com/microsoft/vscode/blob/25e889af458c2be6b2ba2a3b5510b370586bb5c5/src/vs/editor/common/model/tokensStore.ts#L1042

`const foo;`

- because `foo` has the forground color, it is merged with the space before
- when merging with the semantic token, it's an overlapping case. aIndex is not incremented after emit
-The mergeIndex is aIndex - 1 which is the `const` token so that why bold is merged in

**Comment by alexdima** [comment]
Thank you for tracking this down! This was a problem since the first implementation of the metadata merging via https://github.com/microsoft/vscode/commit/6085f3b7608c7ffdceb7875a64f4bcfed2252e02.
