### ISSUE TITLE
Stepping when in a skipped frame navigates me back out to the last non skipped frame

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#95954]
Repro steps:
Debug something that will have skipped frames
Break in
Step into a function that will be in in a skipped frame
Keep stepping over some stuff in the skipped frame

Expected: I intentionally stepped in, I expect to go to that file
Actual: each time I step over while in a skipped frame in I'm shown the editor that the last non skipped frame was from. This means I have to keep re-opening the frame I care about.
![confusingStepping](https://user-images.githubusercontent.com/38270282/80080164-821ceb80-8551-11ea-91e4-338cdef76846.gif)

**Comment by isidorn** [comment]
Good point and agree with your request.
I will not have time this milestone, thus assigning to May.
Here's a code pointer in case someone wants to tackle it in the meantime https://github.com/microsoft/vscode/blob/1af3b9dce3d2ead4c3c0bb010dc47a4752af13d1/src/vs/workbench/contrib/debug/browser/debugService.ts#L1144
Basically the autoFocus of frames should take into account the previous one if it is deempahisezed.

**Comment by dongskyler** [comment]
I'd like to tackle this issue

**Comment by isidorn** [comment]
Sorry, my mistake.
Here's a correct one https://github.com/microsoft/vscode/blob/ee9f5d1f1a7e29b634c89bdc8e073e0763aa0cc8/src/vs/workbench/contrib/debug/browser/debugService.ts#L1144

**Comment by dongskyler** [comment]
@isidorn Thank you. That’s very helpful. I’m looking into the issue. It seems, near Line 1144, the `if (! stackFrame)` section isn’t taking some corner cases into considerations.

**Comment by dongskyler** [comment]
Just to give an update. I'm still working on it. This will be my first contribution to VS Code. Sorry it is taking some time, but I am making progress.

**Comment by isidorn** [comment]
No hurries. Take your time.
