### ISSUE TITLE
Test: mouse scroll wheel should switch tabs

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#95952]
Refs: https://github.com/microsoft/vscode/issues/13902

- [ ] any os @isidorn
- [x] any os @joaomoreno

Complexity: 3

---

A new setting `workbench.editor.scrollToSwitchTabs` allows to enable switching tabs via mouse wheel. 
* verify this works as advertised with the 3 options provided
* verify you can scroll to switch tabs even with this setting turned off when you press and hold the `Shift` key.

**Comment by joaomoreno** [comment]
Love this TPI. I think it's the first time in my career that I think _this TPI should actually have a lower complexity_.

**Comment by bpasero** [comment]
You can have some of mine if you feel bored :P

**Comment by isidorn** [comment]
Oh my stop saying TPI, sandeep got into your mind with his acronyms for everything :)

**Comment by bpasero** [comment]
How is our TPI score currently?

**Comment by isidorn** [comment]
Works lovely

**Comment by joaomoreno** [comment]
@isidorn OK BOOMER
