### ISSUE TITLE
'webview.getWebContents()' is deprecated and will be removed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#95955]
`Please use 'remote.webContents.fromId(webview.getWebContentsId())' instead`

![image](https://user-images.githubusercontent.com/900690/80080237-a11b7d80-8551-11ea-8fb7-5e41b41225aa.png)

Seeing this in my E8 exploration build console. I am not sure we want to support the usage of the `remote` module. Maybe we can do this access alternatively not requiring it at all?

//cc @deepak1556

**Comment by bpasero** [comment]
Looks like https://www.electronjs.org/docs/breaking-changes#deprecated-webviewgetwebcontents outlines a solution without `remote` module.

**Comment by mjbvz** [comment]
@bpasero @deepak1556 We use the web contents in a few different ways:

- https://github.com/microsoft/vscode/blob/e0015ab71f4381b9270c81915ba72e48044c7ffd/src/vs/workbench/contrib/webview/electron-browser/webviewElement.ts#L81

 - https://github.com/microsoft/vscode/blob/e0015ab71f4381b9270c81915ba72e48044c7ffd/src/vs/workbench/contrib/webview/electron-browser/webviewElement.ts#L219

Moving all of these to use ipc will be difficult. There may be some other electron APIs that can help us here though

This doesn't block updating electron 8 though, correct?

**Comment by deepak1556** [comment]
This doesn't block electron 8 but will block electron 9 exploration.

> Moving all of these to use ipc will be difficult

Can you expand on this ?

Whatever method is being used on `webview.getWebContents()`, all of them are internally forwarded to the main process over ipc by electron, so any usage we have now can be moved without relying on `webContents` directly in the renderer.

Also catching the webContents on the renderer side is not a good idea as there is no clear signal for the destruction path, which can lead to issues like https://github.com/microsoft/vscode/issues/96207 . Handling the `webContents` method on the main process will avoid such issues.

**Comment by bpasero** [comment]
@deepak1556 does it make sense to push this any further given we already know that `webcontents` will not work with context isolation?

Can you maybe clarify what the exact conditions are, because I thought about enabling preload+contextIsolation this month, but maybe we cannot do that until we are off `webview`?

**Comment by deepak1556** [comment]
@bpasero we need a bit of planning here on how to tackle this over the next few iterations.

1) `webview.getWebContents()` is removed from Electron 9, so current webview usage cannot work after with it moving forward.

2) when using `webview` under contextIsolation, electron will throw a deprecation log in the devtools console 

`Security Warning: A WebContents was just created with both webviewTag and contextIsolation enabled.  This combination is fundamentally less secure and effectively bypasses the protections of contextIsolation.  We strongly recommend you move away from webviews to OOPIF or BrowserView in order for your app to be more secure`

But the usage has not been blocked in electron master yet and it will most likely happen with electron v12 which gives us time to transition to OOPIF based implementation.



Given the above we can start the work for preload+contextIsolation in this iteration and in parallel start exploring the transition to OOPIF which will atleast take one or two iterations.

In this iteration, I am exploring https://github.com/microsoft/vscode/issues/96307 which is one of the blocker for iframe transition. And the actual work to transition can happen in June or July depending on @mjbvz availability.

And to answer the main question of fixing the usage of `webview.getWebContents`, we should do it if we want to adopt electron 9 and higher, but if we can wait a couple more iterations for the iframe transition to finish then this work can be avoided.

Just to reiterate the transition to OOPIF will not block adopting preload+contextIsolation work, so please go ahead with it :)

**Comment by mjbvz** [comment]
I quickly explored two other approaches for serving up the content for the webview (the stuff that we control). These would (ideally) let us move away from custom protocols but I couldn't get either working :

- Use `protocol.interceptHttpProtocol` to intercept requests to `vscode-webview-test.com`

    I couldn't get this working for https requests. There also does not appear to be a way to limit which requests are intercepted. Also, I always ended up either crashing VS Code or getting into an intercept loop when I tried using these

- Use `webRequest.onBeforeRequest`

    This doesn't seem to provide enough flexibly for serving up custom content when a request is made

**Comment by bpasero** [comment]
@deepak1556 it looks like this was the last dependency on `remote` module, so I think we can now configure `enableRemoteModule: false` for all our windows, would you agree?

**Comment by deepak1556** [comment]
@bpasero yes that would be safe to add now.
