### ISSUE TITLE
Cannot install latest Insiders update

### ISSUE THREAD

**Issue by anatolyburakov** [microsoft/vscode#95953]
- VSCode Version: Insiders latest
- OS Version: Windows 10

Steps to Reproduce:

1. Update Insiders to latest version

Does this issue occur when all extensions are disabled?: N/A

Cannot update to latest Insiders version - installer says "there was an error while marking a file for deletion: Failed to mark file for deletion: Access is denied. Please verify there are no Visual Studio Code processes still executing". No processes executing, setup is run as admin (i use a system-wide version).

**Comment by anatolyburakov** [comment]
Update: waiting a few minutes before hitting the "retry" button seems to have fixed the problem. Clearly something persists after VSCode has exited. So, the issue is solved for me for now, but best look into it anyway.

**Comment by joaomoreno** [comment]
Thanks for the report! This might've occurred due to some software analysis program in your system (antivirus,etc).

**Comment by anatolyburakov** [comment]
@joaomoreno maybe this is the case, but this has been consistently happening since that update two weeks ago, whereas before it never did. This leads me to conclude that something has changed in the installation procedure that causes this.
