### ISSUE TITLE
I can not debug nodejs. Getting an error.

### ISSUE THREAD

**Issue by tanvirgeek** [microsoft/vscode#95962]
Issue Type: <b>Bug</b>

Having error while try to debug nodejs.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.10586

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.9.1
flutter|Dar|3.9.1
es7-react-js-snippets|dsz|2.7.1
code-runner|for|0.9.17

</details>

**Comment by tanvirgeek** [comment]
Can not connet to runtime process: timeout after 1000 milisecond.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you provide more info about file/app you are trying to debug and your launch.json configuration?

**Comment by tanvirgeek** [comment]
launch.json:

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "NODE_OPTIONS": "--inspect=5858",
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}\\js.js"
        }
    ]
}

**Comment by tanvirgeek** [comment]
I am trying to debug very basic javascript. like 1+1 = 2. It is not an express project. Just plain javascript.

**Comment by tanvirgeek** [comment]
I am trying to debug very basic javascript. like 1+1 = 2. It is not an express project. Just plain javascript.

**launch.json:**

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "NODE_OPTIONS": "--inspect=5858",
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}\\js.js"
        }
    ]
}

**Comment by IllusionMH** [comment]
1. There is not need to set `"NODE_OPTIONS": "--inspect=5858",` - VSCode will provide correct flag `--inspect-brk` and this property is not used (according to highlight).
1. When you use `\` in paths you need to escape it otherwise it escapes next character. `"program": "${workspaceFolder}\\js.js"`

**Comment by tanvirgeek** [comment]
I have removed "NODE_OPTIONS": "--inspect=5858", and escaped the path, Still getting the same error. :(

**Comment by tanvirgeek** [comment]
in the debug console I am getting this message:
 C:\Program Files\nodejs\node.exe --inspect-brk=38032 js.js

**Comment by IllusionMH** [comment]
Try to increase timeout and check if you can attach debbuger to node started manually Example with chrome https://nodejs.org/en/docs/guides/debugging-getting-started/#chrome-devtools-55-microsoft-edge

Also make sure that both node and VS Code aren't blocked by firewall.
