### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by vik753** [microsoft/vscode#95965]
Every 5 min I have this error.

CPUs | Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: enabledrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 15.81GB (6.38GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
better-comments | aar | 2.0.5
project-manager | ale | 10.11.0
vscode-toggle-quotes | Bri | 0.3.2
npm-intellisense | chr | 1.3.0
bracket-pair-colorizer-2 | Coe | 0.0.29
vscode-eslint | dba | 2.1.5
es7-react-js-snippets | dsz | 2.7.1
gitlens | eam | 10.2.1
prettier-vscode | esb | 4.5.0
auto-close-tag | for | 0.5.7
auto-rename-tag | for | 0.1.2
vscode-google-translate | fun | 1.4.3
copy-filename | jac | 2.3.1
vscode-redux-devtools | jin | 1.0.2
expand-region | let | 0.1.4
Angular-BeastCode | Mik | 8.1.2
vscode-scss | mrm | 0.9.0
vscode-docker | ms- | 1.1.0
debugger-for-chrome | msj | 4.12.6
vscode-extension-auto-import | Nuc | 1.4.3
vetur | oct | 0.24.0
indent-rainbow | ode | 7.4.0
vscode-jest | Ort | 3.1.1
material-icon-theme | PKi | 4.0.1
heroku-command | pko | 0.0.8
live-sass | rit | 3.0.0
LiveServer | rit | 5.6.1
code-settings-sync | Sha | 3.4.3
vscode-scss-formatter | sib | 2.0.0
code-spell-checker | str | 1.8.0
open-in-browser | tec | 2.0.0
highlight-matching-tag | vin | 0.9.9
vscode-import-cost | wix | 2.12.0
markdown-all-in-one | yzh | 2.8.0

**Comment by ArturoDent** [comment]
Did you see #94858 ?  Check for anti-virus quarantine.
