### ISSUE TITLE
打开终端报错

### ISSUE THREAD

**Issue by liunianyishi01** [microsoft/vscode#95960]
Issue Type: <b>Bug</b>

vscode 终端进程已终止退出代码: 4294901760

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
vscode-standardjs|che|1.2.3
bracket-pair-colorizer|Coe|1.0.61
vue-peek|dar|1.0.2
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.2
vue-snippets|hol|0.1.11
vscode-language-pack-zh-hans|MS-|1.44.2
debugger-for-chrome|msj|4.12.6
vetur|oct|0.24.0

</details>

**Comment by byyxx128** [comment]
This is an known bug of Windows 10.
Please upgrade your OS.
The latest public release is version 1909 build 18363.
***
Win10 的已知bug……升级系统吧……太老了……

**Comment by Tyriar** [comment]
These issues are usually related to anti-virus but you might also have legacy console mode set in cmd.exe (conhost):

- https://code.visualstudio.com/docs/editor/integrated-terminal#_how-do-i-fix-the-errors-connectnamedpipe-failed-windows-error-232-or-terminal-exited-with-code-x-on-windows
- https://code.visualstudio.com/docs/editor/integrated-terminal#_how-do-i-fix-when-a-terminal-exits-with-error-code-3221225786-on-windows
