### ISSUE TITLE
Breakpoints are not resolved properly for symlinked files

### ISSUE THREAD

**Issue by AmeliaMesdag** [Microsoft/vscode#9596]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:
1. Set a breakpoint in VS Code to a file which is symlinked from another location ie ( ${workspaceRoot}\node_modules\linked_project\lib\test.js where ${workspaceRoot}\node_modules\linked_project\ is linked to C:\linked_project)
2. The breakpoint is set to node_modules\linked_project\lib\test.js which is never triggered
3. If C:\linked_project\lib\test.js is opened directly from the Open File dialog, breakpoints set are triggered properly

**Comment by weinand** [comment]
Starting with node.js 6.3 it is possible to pass a `"--preserve-symlinks"` as a runtime argument to node.js. This fixes the issue.
See #23753.
