### ISSUE TITLE
Debug fails to disconnect from targets

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#95964]
Ever since I started using the new JS debugger, when running our top level `VS Code` target and then manually closing the code-oss window, the `Attach to Shared Process` and `Attach to Extension Host` targets remain:

![image](https://user-images.githubusercontent.com/22350/80099549-ea2dfa80-856e-11ea-8669-86f089def012.png)

Eventually, maybe 1 minute later, the `Attach to Extension Host` goes away, but the other one stays, I always have to manually disconnect from it.

![image](https://user-images.githubusercontent.com/22350/80099672-24979780-856f-11ea-81a1-d5807ab4a453.png)

cc @weinand @isidorn

**Comment by connor4312** [comment]
This is because `restart: true` is set for the shared process and extension host, which allows them to reconnect when vscode is reloaded. Eventually js-debug in extension host gives up, but the shared process is using the previous Node debugger which doesn't give up. Both these are working as designed, this is kind of a downside of the compound launch configs in that there's no "compound stop".

**Comment by joaomoreno** [comment]
Yeah, would actually LOVE ❤️  a compound stop. Could this be a feature of compounds, @isidorn & @weinand? Meaning, if something like `stopAll: true` was set in the compound, all targets would share the same `Stop` action, and I would see no `Disconnect` actions.

**Comment by isidorn** [comment]
We could add a `stopAll` attribute to the compound, however how would that work? Clicking stop on any of the compound sessions would send stop to all sessions? And it would never be rendered as dicsonnect?

**Comment by connor4312** [comment]
Maybe compound launch configs could have a pseudo-root, which has a "stop" action that affects all individual configs?

```
VS Code
 |- Attach to Shared Process
 |- Attach to Extension Host
 |- Main Process
 |- Renderer
````

The compound config could have an option whether sessions can be stopped individually, or whether stopping one session is treated as stopping the whole set of configuration.

**Comment by isidorn** [comment]
@connor4312 ok makes somewhat sense, the flaw of my proposel is that once compound starts 4 sessions those sessions are not related in any way. So adding a pseudo root might be smart. The pseudo root would not be rendered, and the pseudo root would remember the `stopAll` attribute.

Here are code pointers for a PR. We should add the attribute [here](https://github.com/microsoft/vscode/blob/616882b83f2010b551fff2da0e63c55b2464fcbf/src/vs/workbench/contrib/debug/common/debug.ts#L522) and to the schema [here](https://github.com/microsoft/vscode/blob/616882b83f2010b551fff2da0e63c55b2464fcbf/src/vs/workbench/contrib/debug/common/debugSchemas.ts#L193).
Code pointer for the debug session to add the pseudo root stopAll smartness [here](https://github.com/microsoft/vscode/blob/616882b83f2010b551fff2da0e63c55b2464fcbf/src/vs/workbench/contrib/debug/browser/debugSession.ts#L67)

**Comment by joaomoreno** [comment]
I like both options. 👍

**Comment by joaomoreno** [comment]
@connor4312 Please let's have the bot not do this for ourselves.

**Comment by weinand** [comment]
BTW, the bot's wording sounds wrong: ...fixed in **to** the latest...

**Comment by roblourens** [comment]
Much better, and I added this attribute to our compound config. But the behavior partly confuses me and I opened https://github.com/microsoft/vscode/issues/99299
