### ISSUE TITLE
Git paths in a workspace are not detected if defined after a non-git path

### ISSUE THREAD

**Issue by Yajo** [microsoft/vscode#95963]
Issue Type: <b>Bug</b>

Create a structure like this:

```bash
mkdir project
cd project
git init
git clone https://github.com/OCA/server-tools.git OCA/server-tools
git clone https://github.com/OCA/web.git OCA/web
mkdir -p my/custom/addons/private
cat > project.code-workspace <<END
{
  "folders": [
    {"path": "OCA/server-tools"},
    {"path": "my/custom/addons/private"},
    {"path": "OCA/web"},
    {"path": "."}
  ]
}
END
# Now open it in vscode
code --disable-extensions project.code-workspace
```

Results:

![2020-04-23_12-23](https://user-images.githubusercontent.com/973709/80094152-ac74a600-855d-11ea-8e2e-2dcba219b65a.png)
![2020-04-23_12-24](https://user-images.githubusercontent.com/973709/80094156-ada5d300-855d-11ea-8cc6-97ad547f56f6.png)

Workaround: put all non-git folders second-to-last, just before `"."`.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 5.5.15-200.fc31.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.48GB (0.93GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joaomoreno** [comment]
Fantastic repro steps! 👏 Thanks a bunch for that.

**Comment by joaomoreno** [comment]
Unfortunately this is the problem of having nested git repositories, which VS Code doesn't support yet. So I'm glad you found a way to get it working OK-ish. #37947

**Comment by Yajo** [comment]
Yikes... **that** bug again... :man_facepalming: :grin:
