### ISSUE TITLE
vscode 1.44 breaks "recent tasks" for tasks generated by my extension

### ISSUE THREAD

**Issue by doudou** [microsoft/vscode#95971]
- VSCode Version: 1.44.2
- OS Version: Ubuntu 19.04

Steps to Reproduce:

1. Run a task generated by my extension https://github.com/rock-core/vscode-rock
2. Try to re-run it from the "recent tasks" list
3. Nothing happens

The same task under "Show all tasks" do work.

One thing that might help understanding the issue on your side: the tasks don't show up under the provider's submenu, only in the "Show all tasks" entry. The task `source` field do match the provider name.

**Comment by alexr00** [comment]
I am not familiar with rock, can you provide a simple project I can open where there will be rock tasks?

**Comment by doudou** [comment]
Will do.

**Comment by doudou** [comment]
Same process than with #95814 

Assuming an Ubuntu install, you'd need to run the script [from this gist](https://gist.github.com/doudou/43994afffae8e1267d8f7c1435019bb5) in an empty folder. It needs to install a bunch of things ruby-related.

Then, add the `base/cmake` folder in a VSCode instance where [the Rock extension](https://marketplace.visualstudio.com/items?itemName=rock-robotics.rock) is installed.

Unfortunately there doesn't seem to be a way to disable all extensions while still letting the user re-enable some, so I can't check if the problem comes from a bad interaction between the rock extension and another.

![vscode-minimal-buildconf](https://user-images.githubusercontent.com/292/80229948-96cbb300-8627-11ea-8025-d506eeb5f12c.gif)

**Comment by alexr00** [comment]
Thank you for the repro! 
The problem is that you register a task provider [here ](https://github.com/rock-core/vscode-rock/blob/1c35d08476cb6548aa7781650a7ef32094d4a134/src/extension.ts#L55) that says it will provide tasks of type `autoproj`.
Then [here](https://github.com/rock-core/vscode-rock/blob/1c35d08476cb6548aa7781650a7ef32094d4a134/src/tasks.ts#L39), you provide tasks with a different type. I will add some kind of error so that extension developers know that they shouldn't really be doing this.
I think I can also add a work around so that it does still work.

**Comment by alexr00** [comment]
There is not a good work around. I will only add the warning.

**Comment by doudou** [comment]
More than fair ... thanks for the help.

In any case, can I register the same provider object for different types ? Or do I have to create two ?

**Comment by alexr00** [comment]
Yes, you can have the same provider object for different types.

**Comment by doudou** [comment]
A suggestion: amending [this documentation](https://code.visualstudio.com/api/references/vscode-api#TaskDefinition) to explicitely link the 'type' from TaskDefinition with the type from `registerTaskProvider` (and vice-versa, probably)

**Comment by doudou** [comment]
> Yes, you can have the same provider object for different types.

Tasks end up being duplicate (I don't see a parameter in resolveTask that would allow to discriminate which tasks it should return, and it will become rather ugly ... I've split into two providers).

![image](https://user-images.githubusercontent.com/292/80384135-e229cf80-887a-11ea-9a86-836dd6f0b701.png)
