### ISSUE TITLE
vs code打不开文件，settings.json,

### ISSUE THREAD

**Issue by hwxjGItHub** [microsoft/vscode#95975]
总是出现：无法打开“settings.json”: Assertion Failed: argument is undefined or null。

**Comment by byyxx128** [comment]
Try this please.
#93679

**Comment by byyxx128** [comment]
Try this please.
https://github.com/microsoft/vscode/issues/93679#issuecomment-614137061

**Comment by Tyriar** [comment]
@JacksonKearl again the bot isn't closing the issue

**Comment by JacksonKearl** [comment]
Here also, `needs more info`'s only get closed when last commenter is a team member. This is consistent with old bot behaviour.
