### ISSUE TITLE
Intrusive "Keep the undo-redock stack" dialog on tab close

### ISSUE THREAD

**Issue by bagage** [microsoft/vscode#95970]
- VSCode Version: 1.44.2
- OS Version: Windows 7

Steps to Reproduce:

1. Open a big file, in my case a xml file that I generate from a script. I keep it open to check that my script properly generated what I expected.
2. Modify/Launch the script multiple times.
3. Once you're happy with it, close the generated xml file.

Expected the tab to close silently.
Instead, dialog poping up:

> Keep the undo-redo stack for <filepath> in memory (250.0 MB)?

I'd either like, from most preferred to less one, to:
1. **have a button "Do not show again for current file"** (persistent accross restarts), 
2. or (a little worse) "Do not show again for current session", 
3. or worse a global setting to completely disable that feature.

Does this issue occur when all extensions are disabled?: Yes

**Comment by dirck** [comment]
Seconding: this is an unnecessary headache.  I'm sure there are many better ways to deal with this.
