### ISSUE TITLE
[folding] Setting the same value for 'start' and 'end' markers for folding does not work

### ISSUE THREAD

**Issue by mccarthyp-snet** [microsoft/vscode#95974]
Issue Type: <b>Bug</b>

Setting the same value for 'start' and 'end' markers for folding in language-configuration.json does not work.

example language-configuration.json:

```
{
    "folding": {
        "markers": {
            "start": "^#####",
            "end": "^#####"
        }
    }
}
```

For simplicity sake, I'd like to be able to use a single string as a section divider, e.g. '#####', and then be able to fold from that divider to the next occurrence of that divider. As far as I can tell, there is not currently a way to do this. It doesn't work when setting the 'start' and 'end' markers to the same string, even though I couldn't find anything acknowledging this is a limitation. Alternatively, this scenario could possibly be handled by just defining the 'start' string, and not defining an 'end' string, but that does not currently work, either.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
peter-notes|pet|0.0.1

</details>

**Comment by aeschli** [comment]
Sorry, that's not supported.
