### ISSUE TITLE
Feature request: API for active custom text editor changed

### ISSUE THREAD

**Issue by nwalters512** [microsoft/vscode#95977]
The `window.onDidChangeActiveTextEditor` API sends events when you switch between text editors, but the callback is invoked with `undefined` when a custom editor is opened. For instance, if you have a normal text editor open and then open some image `foo.png` (the preview for which is displayed with a [custom editor](https://github.com/microsoft/vscode/tree/master/extensions/image-preview)), the callback passed to `window.onDidChangeActiveTextEditor` is invoked with `undefined`.

I'd like some way of being notified when the user switches to a custom editor. It's possible that this is just a bug with `window.onDidChangeActiveTextEditor` and that it *should* be getting an event when a custom editor is opened, but if not, it'd be great to have some new API that works the same but for custom editors.

**Comment by mjbvz** [comment]
There are events on the webview panel for this: https://github.com/microsoft/vscode/blob/f56960538dfdd03173ac57cdfcc8964c6d7549be/src/vs/vscode.d.ts#L6789

We intentionally do not expose a global event for this as, unlike a `TextEditor`, a custom text editor is private to each extension
