### ISSUE TITLE
activityBar.border does not seem to work anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#95972]
On macOS I am trying to configure `activityBar.border` but this color is not showing up for me.

![image](https://user-images.githubusercontent.com/900690/80111873-bd82de80-8580-11ea-9d8f-4f9b10c649a6.png)

It is however set on the pane, so I suspect some layout issue.

![image](https://user-images.githubusercontent.com/900690/80111956-d3909f00-8580-11ea-8be9-27b5332cef24.png)

**Comment by bpasero** [comment]
Can be verified with a theme such as: https://marketplace.visualstudio.com/items?itemName=GitHub.github-vscode-theme

**Comment by robertrossmann** [comment]
Looks like a duplicate of #95858. 🕵️ 😇
