### ISSUE TITLE
Notebook toolbar box shadow theme rule

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#95983]
Issue Type: <b>Bug</b>

Let's make it themeable. cc @misolori 

<img width="903" alt="image" src="https://user-images.githubusercontent.com/876920/80124933-d7530000-8545-11ea-8027-41a4cb9017c0.png">

VS Code version: Code - Insiders 1.45.0-insider (d342048538c28d54afd1c6beea03f3a89af04359, 2020-04-23T07:46:52.128Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.19GB free)|
|Process Argv|-psn_0_16011076|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
gitlens|eam|10.2.1
tsl-problem-matcher|eam|0.1.1
vscode-pull-request-github-insiders|Git|2020.4.32581
vscode-docker|ms-|1.1.0
vscode-language-pack-zh-hans|MS-|1.45.0
remote-containers|ms-|0.112.0
remote-ssh-edit-nightly|ms-|2020.4.9540
remote-ssh-nightly|ms-|2020.4.9540
js-debug-nightly|ms-|2020.4.1517
powershell|ms-|2020.4.0
vscode-github-issue-notebooks|ms-|0.0.10
vsliveshare|ms-|1.0.2048
debugger-for-chrome|msj|4.12.6
kuskus-extensions-pack|ros|1.0.1
kuskus-kusto-language-server|ros|1.0.1
kuskus-kusto-syntax-highlighting|ros|1.1.8
sourcekit-lsp|unp|0.0.1

(4 theme extensions excluded)

</details>

**Comment by misolori** [comment]
Yes, this should use `widget.shadow`

**Comment by rebornix** [comment]
Removed it for now and we can add a new theme color later on. `widgetShadow` is too heavy for the cell toobar.

**Comment by rebornix** [comment]
We are not using shadows any more.
