### ISSUE TITLE
Debug dropdown not working

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#95982]
![image](https://user-images.githubusercontent.com/35271042/80123456-c608f400-8543-11ea-9a8a-0a66328a33bb.png)

This is from today's insiders, I can't even open the dropdown menu. The other dropdowns in the terminal/output/remote explorer appear to work normally.

**Comment by misolori** [comment]
This appears to work in OSS, wonder if this was already fixed?

**Comment by isidorn** [comment]
I can not reproduce this.
What Repository are you working with?
If you F1 > developer tools > console  are there some errors there?

**Comment by misolori** [comment]
I just realized that this is caused by the [Device Simulator](https://marketplace.visualstudio.com/items?itemName=ms-python.devicesimulatorexpress) extension, after I disable that and the Python extension (it depends on it) then it works. Wonder why that is happening. Also getting this message based on my local config:

![image](https://user-images.githubusercontent.com/35271042/80127088-b213c100-8548-11ea-8453-a3f6255616f8.png)

Here are the logs:

[-1587661198070.log](https://github.com/microsoft/vscode/files/4524022/-1587661198070.log)

**Comment by misolori** [comment]
So I just installed the extension dependencies (second notification) and the dropdown now appears. It seems like the extension is blocking the dropdown somehow.

**Comment by isidorn** [comment]
That extension is star activated which is a bug on their side.
However the debug dropdown should not be broken when an extension takes an inifinite amount of time to activate.

**Comment by isidorn** [comment]
@misolori great catch anyways. Let me know if you can still repro tomorrow, though I am pretty cerent my fix fixes it.
