### ISSUE TITLE
做项目，里面的一个文件合并不了

### ISSUE THREAD

**Issue by youyonghui** [microsoft/vscode#95987]
Issue Type: <b>Bug</b>

修改文件名也不行，但主要问题是已在标题里说明

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.85GB free)|
|Process Argv|C:\Users\youyo\Desktop\sy-jd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
daily-anime|dee|1.2.0
vscode-power-mode|hoo|2.2.0
vscode-language-pack-zh-hans|MS-|1.44.2
vetur|oct|0.24.0
LiveServer|rit|5.6.1
background|sha|1.1.23
open-in-browser|tec|2.0.0

</details>

**Comment by byyxx128** [comment]
【TRANSLATION】
> TITLE: A file cannot merged into my project.
> CONTENT: As the title...Renaming is not working.
***
### Can you provide more details about your problem? Screenshots are welcome.
***
在GitHub反馈问题不要标题党……我们想帮你翻译都没法翻译……请给出详细的步骤以及截图。

**Comment by isidorn** [comment]
Fixed in latest vscode insiders
