### ISSUE TITLE
Excessive Debugger Console output causes VS Code to become unresponsive

### ISSUE THREAD

**Issue by baulig** [microsoft/vscode#95981]
Issue Type: <b>Performance Issue</b>

When debugging an app that dumps excessive amounts of output to the Debugger Console, VS Code becomes unresponsive.

In my example, I was debugging a .NET Core app and by accident logged some 15 MB of debugging output to the console - about 11k lines some of which were extremely long because it included a base64-encoded binary.  This was a mistake but due to the unresponsiveness it was hard to find which piece of my code was actually doing that.

This is probably not a scenario that will happen during day-to-day usage, but I think we should still deal with it in a reasonable way.

VS Code version: Code - Insiders 1.45.0-insider (d342048538c28d54afd1c6beea03f3a89af04359, 2020-04-23T07:46:52.128Z)
OS version: Darwin x64 19.4.0

**Comment by isidorn** [comment]
Thanks for reporting this, however dup of https://github.com/microsoft/vscode/issues/81464
