### ISSUE TITLE
Debug problem

### ISSUE THREAD

**Issue by ivano-manara** [Microsoft/vscode#9598]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:31:10.994Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. create asp.net project
2. open project with visual studio code
3. launch dotnet restore
4. launch dotnet -v run
5. click debug with processId
6: error: "Il processo dell'adattatore di debug è stato terminato in modo imprevisto"

**Comment by kieferrm** [comment]
Google translate tells me the error message is: "The adapter debugging process has been terminated unexpectedly"

**Comment by kieferrm** [comment]
The debugger is provided by the C# extension you are using. Pls file the defect in their repository:  https://github.com/OmniSharp/omnisharp-vscode/issues
