### ISSUE TITLE
Expose client watcher as service

### ISSUE THREAD

**Issue by Akumzy** [microsoft/vscode#95991]
Currently, extension authors are bundling their own file system watcher which is not that straight forward considering they're going support multiple platforms. 

Some like [graphql-for-vscode #issue Setup way too complex ](https://github.com/kumarharsh/graphql-for-vscode/issues/42#issuecomment-618520439)  choose to use Facebook watchman which many users are finding difficult to set up and others.

How about exposing or extending the core watcher client as a service the extensions can subscribe to instead of bundling their own fs-watcher which I believe many of us Visual Studio Code will appreciate.

**Comment by bpasero** [comment]
@Akumzy there is `workspace.createFileSystemWatcher`?

**Comment by Akumzy** [comment]
I didn't know about that.

Thanks for the response
