### ISSUE TITLE
Webpack warnings cannot be matched

### ISSUE THREAD

**Issue by cjam** [Microsoft/vscode#9599]
- VSCode Version: 1.3.1
- OS Version: OS X 10.11.5

I am using webpack to build and pack up my application.  Webpack produces warnings in the following format when you accidentally use an import with the wrong case in the file path: (i.e. ./**C**omponents/SomeComponent vs ./**c**omponents/SomeComponent)

```
WARNING in ./src/Components/SomeComponent.tsx
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
```

Now when I try to use the following problem matcher for this:

```
				{
					"owner": "webpack",
					"fileLocation": "relative",
					"severity": "warning",
					"pattern": [						
						{
							"regexp": "WARNING in (.*)",
							"file": 1
						}
						,{
							"regexp": "(.*)$",
							"message": 1,
							"loop": true
						}
					]					
				}
```

I get the following message when trying to build the project:

> The problem pattern is invalid. It must have at least a file, message and line or location match group.

So it seems that the problem matcher validation logic requires that there is a location (line,col) for a rule to be valid.  Couldn't the default just being the first line / column of a file so that the matcher could handle scenarios like this where its a file in general that produces the warning?

I admit, I feel like Webpack's warning should include a line/col as it is complaining about a specific import.  But it would also be nice to be able to handle plugins that aren't necessarily being good citizens with respects to the output they surface.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/6538
