### ISSUE TITLE
Double-clicking a view splitter should equally resize the 2 adjacent views

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#95994]
When double-clicking here, I would like the search view and results view resized to take up the space equally
![image](https://user-images.githubusercontent.com/641685/80131724-a637f700-8568-11ea-809e-fc6ba36a77c4.png)

Additionally, I would love it if double-clicking on a view header would "maximize" that view -- either collapse all other views or just shrink all other views so that the double-clicked view takes up a must space as it can. Honestly it would be nice to have both of those behaviors with a modifier key to switch between them, because sometimes I just want to expand the current view (probably should be the default) and other times I want to collapse everything to focus on 1 view (with modifier)

**Comment by joaomoreno** [comment]
What if there are 3 views? Would you expect both adjacent views to get the same size, or all 3 views to have the same size?

**Comment by joaomoreno** [comment]
> Additionally, I would love it if double-clicking on a view header would "maximize" that view -- either collapse all other views or just shrink all other views so that the double-clicked view takes up a must space as it can. Honestly it would be nice to have both of those behaviors with a modifier key to switch between them, because sometimes I just want to expand the current view (probably should be the default) and other times I want to collapse everything to focus on 1 view (with modifier)

Why not a maximize action icon to the right of each header? cc @misolori 

@sbatten I would do this at the view pane container layer. The splitview exposes the `onDidSashReset` such that clients can do what they want.

**Comment by eamodio** [comment]
I'd just want it to it to equally size the 2 adjacent views (splitting the space they both are currently using). But I know that for editors we resize them all (which I honestly don't like).
