### ISSUE TITLE
Add support for Perl5 symbol indexing

### ISSUE THREAD

**Issue by recursionbane** [Microsoft/vscode#96]
There doesn't seem to be a way to force indexing of Perl5 files for symbol harvesting, so the "Go to definition" and "Go to Symbol" do nothing (without any feedback to the user) when clicked for Perl5 (and likely, Perl6) files in a project.

**Comment by mjbvz** [comment]
Thank you for the request. Since perl is not one of our core targeted languages, symbol indexing is an advanced language feature that we would expect an extension to provide.
