### ISSUE TITLE
Tasks -> New Window (from Windows task bar) no-ops when running under Admin mode

### ISSUE THREAD

**Issue by Zlatkovsky** [Microsoft/vscode#9600]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1. Launch VS Code under Admin mode
2. Windows Taskbar -> right-click on VS Code --> New Window.  Nothing happens.  But works fine had VS Code been launched regularly, without Admin mode.

Tried it a few times back and forth, 100% repro.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/4921
