### ISSUE TITLE
Why isn’t this vim?

### ISSUE THREAD

**Issue by patternagainstuser** [microsoft/vscode#96008]
No plugin installer.  Not even vim-plug or vundle.

**Comment by rcjsuen** [comment]
@patternagainstuser You mean why doesn't VS Code support Vim plug-ins?

**Comment by rcjsuen** [comment]
@patternagainstuser If you are however talking about how to enhance your Visual Studio Code install, perhaps this article about the [Extension Marketplace](https://code.visualstudio.com/docs/editor/extension-gallery) will help you.

**Comment by mjbvz** [comment]
Hi, it seems you may have recently [exited vim](https://exitvim.net). I know that the brave new world of non-vim programs you are now facing can come as a shock after years of grasping in the dark for the right key combination, but it will be ok :)

Check out the [VS Code docs](https://code.visualstudio.com/Docs) to get started. Any there's always the [Vim Extension](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim)
