### ISSUE TITLE
UI Change:  Make it easier to scroll through "containing" window when peek window is open

### ISSUE THREAD

**Issue by jastich** [microsoft/vscode#96000]
Scrolling (with mouse's scroll wheel) is difficult when the peek window is open, because the peek window moves with the lines of the "containing" window and the editor changes to scrolling the peek window when the cursor enters the peek window.

Observed behavior:
- Open peek window.
- Initiate scrolling with cursor outside of the peek window (the "containing window").
- While scrolling, peek window moves with the containing window and passes under the cursor.
- **Scrolling context immediately shifts to scroll within the peek window.**

Desired behavior:
- Open peek window.
- Initiate scrolling with cursor outside of the peek window (the "containing window").
- While scrolling, peek window moves with the containing window and passes under the cursor.
- **Scrolling context continues to scroll the containing window where scrolling was initiated.**

I assume that each "click" of the scroll wheel is an individual event.  To illustrate the desired behavior, a possible solution would be to retain a reference to the window where the first scroll event was issued and clear the reference when the mouse is moved relative to the screen (perhaps with a few pixels of threshold).  Therefore, I would continue to scroll the same window until I move the mouse cursor relative to the screen.

Version:  1.44.2
OS:  Linux x64 3.10.0-957.27.2.el7.x86_64

**Comment by robertrossmann** [comment]
A similar, very related annoyance - when you initiate scrolling **inside** a peek editor and you hit the bottom of the peeked document while the scroll event is still “going on” (very easily replicated on Apple trackpads with two-finger swipes) the outer document starts scrolling.

I just want to quickly get to the end of that peeked file, only to find the peek view flying off the screen at supersonic speed. 🚀 😀
