### ISSUE TITLE
Move 'Extension' button in Activity Bar to the bottom

### ISSUE THREAD

**Issue by pawelzwronek** [microsoft/vscode#96006]
Extensions are to customize VSCode, just like Manage button. It would be great to declutter upper area of Activity Bar and move this this button to the very bottom, above Manage button. Also it's used quite occasionally.

**Comment by gjsjohnmurray** [comment]
Did you try dragging it and dropping it where you want it?

**Comment by gjsjohnmurray** [comment]
Sorry, I didn't understand first time.

It is already possible to hide it completely (context menu lets you clear its checkmark), then use the Extensions option from the menu of the Manage button (gearwheel).

**Comment by pawelzwronek** [comment]
No problem. This will do, thx 👍 but I think it's wort to consider to add an option 'Move to the bottom' on RMB for every button on Activity Bar ❓  I always think for a moment which button to click when I move mu cursor over Activity Bar.
