### ISSUE TITLE
Tasks: tasks.json file created in wrong location, in WSL

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#96003]
Open a Remote WSL window on an empty folder and run `Tasks: Configure Task`. The `tasks.json` file will be in the wrong location:

![image](https://user-images.githubusercontent.com/22350/80138914-e2d61380-85a5-11ea-9dcb-a06d4d6e29c1.png)

Isn't this file supposed to be in the workspace `.vscode` folder?

**Comment by alexr00** [comment]
There are user tasks and folder tasks. If you already have a user task configured, then it will open the tasks.json in the location that you show. If you don't, they you will be asked which kind of task you'd like to create in the .vscode folder. What happened when you ran the **Tasks: Configure Task** command?

**Comment by joaomoreno** [comment]
Odd, I can't repro now. I also don't exactly remember, but I'm quite sure no ask was made.

Let's close it.
