### ISSUE TITLE
Keyboard Shortcuts: Make "Previous Used Editor" and "Next Used Editor" mappable to shortcuts

### ISSUE THREAD

**Issue by tommymcglynn** [microsoft/vscode#96004]
I use these commands frequently and it would be nice if I could map these in the Visual Studio Code Keyboard Shortcuts. As a workaround, I'm using the Keyboard Shortcuts built into macOS System Preferences.

**Comment by ArturoDent** [comment]
Are these the commands you are looking for:

`workbench.action.openPreviousRecentlyUsedEditor`

`workbench.action.openNextRecentlyUsedEditor`

They are unbound by default, you can bind them yourself.  See https://code.visualstudio.com/updates/v1_42#_navigate-most-recently-used-editors

For example,

```
{
    "key": "ctrl+tab",
    "command": "workbench.action.openNextRecentlyUsedEditor",
    "when": "editorTextFocus"
},
{
    "key": "ctrl+shift+tab",
    "command": "workbench.action.openPreviousRecentlyUsedEditor",
    "when": "editorTextFocus"
}
```

**Comment by tommymcglynn** [comment]
Yes, that's exactly what I was looking for. Thank you.
