### ISSUE TITLE
Rename popup sometimes populates with text on the left side omitted

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#96013]
- VSCode Version:
Version: 1.45.0-insider (user setup)
Commit: d342048538c28d54afd1c6beea03f3a89af04359
Date: 2020-04-23T05:57:41.076Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Install the C/C++ extension -- required to invoke renaming. The bug doesn't repro with non-Insiders VS Code, so we don't believe it's a bug with our C/C++ extension (i.e. it's a VS Code regression).
2. Create a test.cpp file with code
```
int do_not_Cut_Off_This_Text;
```
with the cursor at Te|xt.
![image](https://user-images.githubusercontent.com/19859882/80152030-d0d97e00-856f-11ea-87da-9054acedb204.png)
3. Do a Rename.
![image](https://user-images.githubusercontent.com/19859882/80152056-dafb7c80-856f-11ea-8207-b6e59548f77d.png)
So if you enter a 2 at the end, the result is `int Cut_Off_This_Text2;`

Bug: The rename dialog pops up with the left-side text omitted -- this causes users who intend to append text to the end to accidentally do an incorrect rename with the text at the left omitted (when they don't notice that characters on the left side of the symbol got cutoff).

Does this issue occur when all extensions are disabled?: Seems to require an extension that supports rename, but doesn't repro with TypeScript, so there might be other internal requirements.

**Comment by jrieken** [comment]
Does your extension implement `prepareRename`?

**Comment by sean-mcmanus** [comment]
@jrieken No, we don't implement prepareRename. See https://github.com/microsoft/vscode-cpptools/blob/master/Extension/src/LanguageServer/client.ts#L892 .

**Comment by jrieken** [comment]
This is a regression from tweak make to getting the current word. Surprised it took so long to be discovered...
