### ISSUE TITLE
Double click to find variable usages highlights non-exact matches

### ISSUE THREAD

**Issue by kevin-lin** [Microsoft/vscode#9601]
- VSCode Version: 1.3.1
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. double click on variable name ex: 'user'
2. the 'user' part of 'username', 'newuser', 'USER', etc are also highlighted

<img width="147" alt="screen shot 2016-07-21 at 3 46 11 pm" src="https://cloud.githubusercontent.com/assets/2602416/17041327/47e14294-4f5a-11e6-801d-9a9ad1530ab3.png">

**Comment by Spown** [comment]
you have to use find function with whole word matching for that
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-07/Code_2016-07-22_11-18-30.png)
