### ISSUE TITLE
Every time I load up a new window I get a file that theme that opens and hides

### ISSUE THREAD

**Issue by chrisbull** [microsoft/vscode#96012]
Every time I load up a new window I get a file that appears to some kind of VSCode theme JSON file, it shows, but before I can really tell what it is, it hides. If in the middle of me opening a file, it overrides the file that I just opened and then closes itself. So it's really annoying. Wasn't happening before the update, but is happening since.

Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z (1 wk ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with all extensions disabled?

**Comment by Tyriar** [comment]
@JacksonKearl again the bot isn't closing the issue

**Comment by JacksonKearl** [comment]
Again `needs more info` doesn't get closed if last commenter isn't a team member

**Comment by Tyriar** [comment]
@JacksonKearl shouldn't the community members that help triaging be treated as the team in this respect?

**Comment by JacksonKearl** [comment]
That would make sense. Historically they haven't so I didn't for this implementation either.

**Comment by JacksonKearl** [comment]
#97025
