### ISSUE TITLE
The VSCode  main window  frame always refresh  and  screen shake, when moving  the mouse from the file view  to  terminal view.  You can see it very clear when using the Teamviewer  remote  access the another computer.

### ISSUE THREAD

**Issue by jxliaocb** [microsoft/vscode#96017]
1. remote access the  another machine by TeamViewer.
2. Open the VSCode.
3. Move mouse form one view to another view,  the main frame refresh frequently.

**Comment by sbatten** [comment]
At first read, this sounds like a Team Viewer issue. Could you provide more details?
