### ISSUE TITLE
Allow user to specify file location when prompted "Error: Unable to resolve non-existing file"

### ISSUE THREAD

**Issue by forrestthewoods** [microsoft/vscode#96018]
I am using VS Code to debug a C++ compiled `.exe`. I can configure a ` launch.json` that successfully launches my `.exe.`  However when I attempt to step into a function I get the following error:

`Unable to open 'thing.cpp'. Unable to read file 'c:\foo\bar\baz'. (Error: Unable to resolve non-existing file 'c:\foo\bar\baz'.

This makes sense. The file does not exist at 'c:\foo\bar\baz' because it was produced by a caching build system. However the file does exist on my hard drive in another location.

In Visual Studio I get a similar prompt. Except Visual Studio lets me specify the file location. This lets me successfully step-into and debug my code. Unfortunately VS Code does not give me this option. The file exists in my VS Code workspace which makes it particularly frustrating.

My feature request: when debugging fails to read the file allow the user to specify the file's location. If a file with the correct filename and similar path offer to open that file automatically.

**Comment by sbatten** [comment]
@roblourens @weinand likely this can be handled by the extension, but not sure if there is some general logic that spans debug adapters

**Comment by roblourens** [comment]
This is handled differently for each debug adapter. Please file this issue on the repo for the vscode-cpptools extension:

https://github.com/microsoft/vscode-cpptools/issues

Thanks!
