### ISSUE TITLE
autocomplete for variables and functions inside console.log()

### ISSUE THREAD

**Issue by hefayed** [microsoft/vscode#96014]
- VSCode Version: 1.44.2
- OS Version: macOSX 10.5.4

Steps to Reproduce:

1. create any function or a variable for example let myName = name;
2.type console.log(myName) f autocomplete works just create and another console.log(myName) and see if autocomplete works , for me sometime it works and sometime it does't

Does this issue occur when all extensions are disabled?: Yes

Autocomplete works

![Screen Shot 2020-04-23 at 2 19 35 PM](https://user-images.githubusercontent.com/13040034/80152849-498d0a00-8571-11ea-89a3-f66fd4cb6317.png)

if I am inside console.log sometime it works and sometime it doesn't

![Screen Shot 2020-04-23 at 2 20 10 PM](https://user-images.githubusercontent.com/13040034/80152887-5b6ead00-8571-11ea-9b4c-b2211dc22c06.png)

**Comment by mjbvz** [comment]
Looks like you are using the logging snippet. 

Try setting: `"editor.suggest.snippetsPreventQuickSuggestions": false` to enable suggestions while completing snippets
