### ISSUE TITLE
Fix 'The operand of a 'delete' operator must be optional' errors in VS Code codebase

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#96022]
The latest TS 3.9 nightly catches a potential strict null check violation where you delete a property that is not marked optional:

```ts
interface Foo {
   x: number;
}

const a: Foo = { x: 3 };

delete a.x // new error here since `x` is not marked as being potentially undefined 
```

This revealed a few potential errors in our code:

- [x] `vs/workbench/contrib/tasks/browser/taskQuickPick.ts(56,11)` @alexr00 
- [x] `vs/workbench/contrib/tasks/browser/taskQuickPick.ts(57,11)` @alexr00 
- [x] `vs/workbench/contrib/tasks/common/taskConfiguration.ts(1204,13)` @alexr00 
- [x] `vs/workbench/contrib/search/test/browser/queryBuilder.test.ts(954,10)` @roblourens 
- [x] `vs/workbench/contrib/search/test/browser/queryBuilder.test.ts(955,10)` @roblourens 
- [x] `vs/workbench/contrib/search/common/searchModel.ts(1103,10)` @roblourens 
- [x] `vs/workbench/contrib/debug/browser/debugToolBar.ts(274,11)` @isidorn 
- [x] `vs/workbench/browser/parts/statusbar/statusbarPart.ts(706,12)` @bpasero 
- [x] `vs/platform/environment/node/argv.ts(253,9)` @aeschli  
- [ ] `vs/workbench/api/node/extHostDebugService.ts(100,12)` @weinand 
- [x] `vs/code/electron-main/window.ts(762,11)`  @bpasero 
- [X] `vs/code/electron-main/app.ts(196,12)` @mjbvz  
- [x] `vs/server/remoteCli.ts(128,9)` @aeschli  

I've made some initial assignments but please reassign if you are not the correct owner

**Comment by mjbvz** [comment]
I've marked this as April since it blocks us from picking up the latest TS build and providing feedback on it

/cc @DanielRosenwasser for awareness of the impact of this change

**Comment by mjbvz** [comment]
Actually looks like TS may be reverting this change for TS 3.9. We should still fix these issues but don't need to do it this iteration

**Comment by alexr00** [comment]
@mjbvz How can force the error so I can make sure it's fixed?

**Comment by mjbvz** [comment]
In the root of the VS Code project:

 - `yarn add typescript@3.9.0-dev.20200423`
- Then restart the watch task and you should start seeing the errors

**Comment by mjbvz** [comment]
Closing this since most bugs have been fixed. I believe that TS 4.0 should add this check back
