### ISSUE TITLE
Open in Container ignores host environment variables

### ISSUE THREAD

**Issue by airtonix** [microsoft/vscode#96032]
- VSCode Version: 1.41.0
- Local OS Version: win 10 pro insider preview 2004 19536.1000
- Remote OS Version: docker for windows 2.1.0.5
- Remote Extension/Connection Type: Docker

Our docker containers use npm scripts, some of which requires that NPM_TOKEN is set from the users shell profile scripts (powershell, bashrc, etc).

This works fine when vscode remote dev container is not involved. BUt when we "Open in Container" the NPM_TOKEN var is mysteriously missing.

I've created a quick reproduction of the scenario with just a tiny docker-compose.yml and some arbitrary environment variables.

### On Windows 10 Pro with Docker for WIndows

1. Be on Windows 10 pro as above
2. don't be using WSL
2. have powershell
3. have vscode with remote docker development extension
4. pull this repo: https://github.com/airtonix/vscode-remote-dev-containers-blank-compose-env-vars-broken
5. open powershell
6. type `$env:FOO="bar"`
7. run `docker-compose run --rm foo`
8. see that `FOO` is visible and contains the value `bar`
9. see that `BAR` is absent
10. launch a devcontainer environment
11. when in shell, type `env`
12. see that `FOO` is absent
12. see that `BAR` is absent

### ON MacOsx with Docker for Mac:

1. Be on MacOSx Sierra
2. have vscode with remote docker development extension
3. pull this repo: https://github.com/airtonix/vscode-remote-dev-containers-blank-compose-env-vars-broken
5. open a terminal
6. type `export FOO="bar"`
7. run `docker-compose run --rm foo`
8. see that `FOO` is visible and contains the value `bar`
9. see that `BAR` is absent
10. launch a devcontainer environment
11. when in shell, type `env`
12. see that `FOO` is visible and contains the value `bar`
12. see that `BAR` is absent

What I expect:

That FOO is visible and has the value 'bar' on all operating systems.

**Comment by Tyriar** [comment]
@chrmarti 

Pretty sure this is regarding the dev containers extension as it's referring to the environment 

> type $env:FOO="bar"
> run docker-compose run --rm foo
> see that FOO is visible and contains the value bar
> see that BAR is absent
> launch a devcontainer environment
> when in shell, type env
> see that FOO is absent
> see that BAR is absent

Might be by design?

---

> you also remove things that aren't prefixed with VSCODE

So this a problem for you? Changing your variable to not be VSCODE sounds like an easy fix? All variables used to be listed explicitly but then we kept adding new ones and it went out of date.

**Comment by airtonix** [comment]
The point is that because you're not documenting the things you're removing, and are now removing things not prefixed with `VSCODE`... how are we to know?

do one or the other please: document or stick to removing only those prefixed with `VSCODE`.

By the way, my example of using `VSCODE` was just that... an example. we don't actually use that variable, but are experiencing that many more of our environment variables from the magic `.env` file are not making it into the container when launched by vscode-remote.

Just to preempt you:

1. yes i know that a service in docker-compose.yml needs to have the variable whitelisted (without value) for it to make it into the container
2. yes i know that we need a `.env` file 

The thing that is not clear with regards to vscode-remote is where this file lives. Is it relative the CWD when the docker-compose process is executed? does it just have to be next to any of the `docker-compose.yml` files included?

**Comment by chrmarti** [comment]
The `.env` file needs to be in `docker-compose`'s cwd which is the workspace folder (parent folder of the `.devcontainer` folder).

**Comment by Tyriar** [comment]
Just to clarify the `VSCODE_`/`ELECTRON_`/etc. removal isn't even an issue here, you're just commenting on it in passing. We've been doing this for years and the only complaints we've had are that we're not removing _enough_ variables. This seems too obscure to take up more space [here](https://code.visualstudio.com/docs/editor/integrated-terminal#_common-questions).
