### ISSUE TITLE
Separate terminal history per editor/folder/project

### ISSUE THREAD

**Issue by martindanielson** [microsoft/vscode#96033]
In many of my assignments there are at least 2, usually more, different code bases we are working on. I mostly work with React but there is always a back-end of some sort and sometimes micro-services int he form av separate APIs.

This leads me to organize myself to use several editors for each code-base. This works perfectly in VS Code and it even highlights old "folders" I have had open before in the MacOS context menu.

My biggest issue in terms of developer experience is that when I close down my computer the terminal history (I believe it is zsh) is merged into one of the (either from VS Code or separate terminal window) and it slows down my workflow a lot having to re-write commonly used commands and the ability to find back to what branches etc I have switched between.

Would be great to have a separate history per terminal. Is this something that could be accomplished in VS Code you think? It would take it from awesome ty hyper-awesome.

MacOS, Catalina, evergreen VS Code.

Thanks for an awesome software that is helping me become a better coder each day.

**Comment by sh7dm** [comment]
I'm not sure, but I heard about [this zsh plugin](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/per-directory-history/per-directory-history.zsh), you can use it with oh-my-zsh. Shell keeps history, so this is a solution probably.

**Comment by Tyriar** [comment]
I don't think this is possible. Things you could try:

- A shell plugin like @sh7dm suggests
- Set up a bunch of aliases with simple and/or unique names (ctrl+r) so you're less reliant on history
