### ISSUE TITLE
the "open with" option in windows broser doesn't work

### ISSUE THREAD

**Issue by Havarkus** [microsoft/vscode#96036]
When using Unity, or even the windows browser, i am unable to open a file in VSC, despite the default program for that specifid file type (.cs files) being VSC. I cannot open the files through double clicking either, i have to open VSC by itself and copy the text into the window which completely defeats the purpose of using it in the first place.

**Comment by joaomoreno** [comment]
What happens when you double click it?

**Comment by Havarkus** [comment]
I’m not sure if this worked before, but if I open the files manually in the Microsoft file browser with double click it opens them fine in VSC, but not if I try to do that in Unity

**Comment by joaomoreno** [comment]
Oh. Please file an issue to Unity.
