### ISSUE TITLE
Unable to open multiple visual studio code?

### ISSUE THREAD

**Issue by dongrizhixue** [Microsoft/vscode#9603]
- VSCode Version: 1.3.1
- OS Version: windows 10 pro 1511

Steps to Reproduce:

1. 
2.

**Comment by Spown** [comment]
Menu:File:NewWindow (ctrl+shift+n). Some shortcuts are not implemented yet #48

**Comment by dongrizhixue** [comment]
Oh, I see

**Comment by Spown** [comment]
or
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-07/2016-07-22_11-38-44.png)

you can close the issue

**Comment by dongrizhixue** [comment]
Thank you
