### ISSUE TITLE
VSCode is unable to open any kind of file

### ISSUE THREAD

**Issue by VishalAmbavade** [microsoft/vscode#96035]
Issue Type: <b>Bug</b>

I've been trying to open my python files on VSCode this morning and it is just unable to open those files. In fact, I tried opening c program files as well but they also seem not to work with VSCode. I have even uninstalled the software, uninstalled the extensions and installed again but the issue is not resolved.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.2.0
python|ms-|2020.4.74986
sqltools|mtx|0.21.7
vscodeintellicode|Vis|1.2.6

</details>

**Comment by Red13x3** [comment]
I have the exact same issue. No files, not even selecting File > New File does not successfully create a new file!  Can't open Setting. It comes up with errors like:
Assertion Failed: argument is undefined or null. (See attached image)

I have tried a full uninstall and reInstall. I had and have no extensions whatsoever. It was working fine and then after editing some setting, one of which opened a json file that I made no changes to and closed immediately. After that, I cannot open any files at all.

Luckily the file I was working on was autosaving... Guess I'm back to Notepad until this is fixed. :(

![image](https://user-images.githubusercontent.com/13119623/80209543-9eb24400-8675-11ea-8868-bb206f3adb24.png)

**Comment by Red13x3** [comment]
Here is my VS Code info:
Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/94931
