### ISSUE TITLE
HTML - Quicksuggestions do not work (without pressing CTRL + Space) for ID and Name when using Emmet 

### ISSUE THREAD

**Issue by gabriel-cloud** [microsoft/vscode#96042]
- VSCode Version: 1.44.2
- Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
- OS Version: Darwin x64 19.4.0
- macOS version: 10.15.4

Steps to Reproduce:

1. New HTML doc
2. Type `inp` and then press TAB
3. As expected you get the full, pre-filled and text pre-selected `<input type="text" name="" id="">`
4. If one now types, `text` gets replaced with the new characters, as expected
5. Pressing Tab automatically goes in between the " " of `name=`, as expected
6. If you then start typing, you do not get any auto-complete suggestions. So, if you have had a `<label for="test1">`, and then an `<input...`, you would not get the `test1` suggestion when typing in the "pre-selected" syntax.
7. If you, however, after pressing tab, press the left arrow and then right arrow to move the caret back and forth a character(and therefore losing the pre-selection) you now get the auto-suggestion when typing.
8. CTRL+Space work fine at step 6.

Does this issue occur when all extensions are disabled?: Yes

Settings.json:
```
{
    "editor.quickSuggestions": {
        "other": true,
        "comments":true,
        "strings": true,
    },
    "editor.acceptSuggestionOnCommitCharacter": true,
    "editor.suggest.statusBar.visible": true,
    "editor.acceptSuggestionOnEnter": "on",
    "editor.quickSuggestionsDelay": 10,
    "editor.suggestOnTriggerCharacters": true,
    "editor.tabCompletion": "on",
    "editor.suggest.localityBonus": true,
    "editor.suggestSelection": "recentlyUsed",
    "editor.wordBasedSuggestions": true,
    "editor.parameterHints.enabled": true,
}
```
[Screen Recording 2020-04-23 at 15.58.28.mov.zip](https://github.com/microsoft/vscode/files/4527326/Screen.Recording.2020-04-23.at.15.58.28.mov.zip)

**Comment by gjsjohnmurray** [comment]
Try setting: "editor.suggest.snippetsPreventQuickSuggestions": false to enable suggestions while completing snippets.

**Comment by gabriel-cloud** [comment]
Nice one @gjsjohnmurray . That was it. Ta 👍
