### ISSUE TITLE
Support table header alignment in TSDoc Markdown

### ISSUE THREAD

**Issue by christianalfoni** [microsoft/vscode#96044]
Hi there!

I noticed that the markdown parser of intellisense does not take into account alignment of table headers:

<img width="642" alt="Screenshot 2020-04-24 at 10 17 32" src="https://user-images.githubusercontent.com/3956929/80190682-fb314700-8614-11ea-9f31-de0b3f535105.png">

<img width="623" alt="Screenshot 2020-04-24 at 10 17 40" src="https://user-images.githubusercontent.com/3956929/80190701-01272800-8615-11ea-90de-84c4028e6f8e.png">

The **Properties** are still center aligned, while they should have been left aligned. Would be awesome to get this in 😄 👍

**Comment by octref** [comment]
Dup of #95937, which is just fixed.
