### ISSUE TITLE
Multiple Selection cursor flutters away randomly when the number of cursors goes up

### ISSUE THREAD

**Issue by FremdSprach** [microsoft/vscode#96040]
Issue Type: <b>Bug</b>

The cursor's behavior becomes unpredictable when the number of multiple cursors goes up.

 The cursor could go somewhere two lines down from the expected location, or just appear in the beginning of the opened file.

VS Code version: Code - Insiders 1.45.0-insider (d342048538c28d54afd1c6beea03f3a89af04359, 2020-04-23T05:57:41.076Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (138)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.0.5
html-snippets|abu|0.2.1
increment-selection|alb|0.2.0
numbered-bookmarks|ale|7.0.0
project-manager|ale|10.11.0
vscode-sequence-diagrams|Ale|0.4.0
copy-relative-path|ale|0.0.2
auto-add-brackets|ali|0.11.0
shaderlabvscodefree|aml|1.1.6
html-class-suggestions|And|1.0.7
previewseqdiag-vscode|ari|0.2.4
insertnumbers|Asu|0.9.1
All-Autocomplete|Ati|0.0.23
unique-lines|bib|1.0.0
markdown-mermaid|bie|1.4.3
path-intellisense|chr|1.4.2
regex|chr|0.2.0
highlight-line-vscode|cli|0.0.1
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.0.29
vscode-clock|Com|0.0.1
vscode-ipaddress|Com|1.0.0
markdown-table-prettify|dar|2.4.0
vscode-markdownlint|Dav|0.35.0
jshint|dba|0.10.21
vscode-quick-select|dba|0.2.8
empty-indent|Dmi|0.2.0
docs-markdown|doc|0.2.66
python-preview|don|0.0.4
jquerysnippets|don|0.0.1
python-extension-pack|don|1.6.0
xml|Dot|2.5.0
EditorConfig|Edi|0.14.5
graphviz-preview|EFa|1.4.0
LogFileHighlighter|emi|2.8.0
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|32.6.0
filter-line|eve|2.0.1
vscode-relative-line-numbers|ext|0.0.5
markdown-table-formatter|fcr|2.0.4
file-icons|fil|1.0.23
auto-close-tag|for|0.5.7
auto-complete-tag|for|0.1.0
code-runner|for|0.9.17
terminal|for|0.0.10
duplicate|gee|1.0.1
graphviz-markdown-preview|gee|0.0.8
mdmath|goe|2.4.0
beautify|Hoo|1.5.0
vscode-settings-cycler|hoo|1.0.1
rest-client|hum|0.23.2
output-colorizer|IBM|0.1.2
compareit|in4|0.0.2
path-autocomplete|ion|1.13.6
vscode-essentials|jab|1.5.0
open-file-from-path|jac|1.3.3
yuml|Jai|3.5.1
RelativePath|jak|1.4.0
fontawesome-autocomplete|Jan|0.1.8
hungry-delete|jas|1.6.0
markdown-extended|jeb|1.0.17
plantuml|jeb|2.13.8
vscode-text-pastry|jkj|1.2.0
vscode-graphviz|joa|0.0.6
svg|joc|1.1.7
docthis|joe|0.7.1
vscode-peacock|joh|3.7.0
indentation-level-movement|kai|1.2.1
auto-comment-blocks|kev|1.0.1
vsc-python-indent|Kev|1.8.1
vscode-gutter-preview|kis|0.26.1
markdown-math|koe|0.1.0
vscode-view-in-browser|kop|1.0.5
graphql-for-vscode|kum|1.15.3
vscode-simple-icons|Lau|1.13.2
vscode-smart-column-indenter|lmc|0.0.13
MagicPython|mag|1.1.0
markdown-converter|man|3.0.2
string-manipulation|mar|0.3.2
markdown-shortcuts|mdi|0.12.0
rainbow-csv|mec|1.7.0
python-path|mge|0.0.11
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.6.0
vscode-filesize|mkx|2.1.4
theme-monokai-pro-vscode|mon|1.1.15
python|ms-|2020.4.74986
remote-wsl|ms-|0.44.2
cpptools|ms-|0.27.0
vscode-mscgen|msc|1.2.0
reload|nat|0.0.6
gremlins|nho|0.15.1
deepdark-material|Nim|3.2.1
incrementor|nms|0.1.0
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.0.1
polacode|pnp|0.3.4
vscode-graphql|Pri|0.2.14
text-power-tools|qcz|1.11.1
subtle-brackets|raf|3.0.0
java|red|0.60.0
vscode-xml|red|0.11.0
vscode-yaml|red|0.7.2
synthwave-vscode|Rob|0.1.3
partial-diff|ryu|1.4.1
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.5.3
auto-rename-tag|Sim|0.1.4
indenticator|Sir|0.6.0
shader|sle|1.1.4
swdc-vscode|sof|2.1.76
dot|Ste|0.0.1
vscode-graphql|stp|0.2.3
code-spell-checker|str|1.8.0
tabnine-vscode|Tab|2.7.0
ayu|tea|0.18.0
open-in-browser|tec|2.0.0
graphviz-interactive-preview|tin|0.0.6
vscode-input-sequence|tom|0.2.0
python-extended-snippets|tus|0.0.1
sort-lines|Tyr|1.9.0
vscode-counter|uct|1.3.5
alphabetical-sorter|ue|2.0.1
remove-empty-lines|use|0.0.6
vscodeintellicode|Vis|1.2.6
rainbow-tags|vol|0.3.1
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-maven|vsc|0.21.2
vscode-icons|vsc|10.1.1
vim|vsc|1.13.1
JavaScriptSnippets|xab|1.8.0
linecount|yyc|0.1.7
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|2.8.0
material-theme|zhu|3.3.1

(23 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo Does the problem also happen if you launch with all extensions disabled?

**Comment by FremdSprach** [comment]
Hi, I reproduce this problem like this:

1. Disable all the extensions and reload VS Code, the multiple cursors works perfect again.

2. Enable only the Vim [Vim emulation for Visual Studio Code] extension, the problem arises again.

So this bug was probably imported with the Vim extension, not VS Code itself.

Should I close this issue and submit another one to the Extension category, though?

**Comment by alexdima** [comment]
@FremdSprach If the issue reproduces only when having the vim extension enabled, then please open an issue against the vim extension with your precise steps. They will investigate on their side and determine if there is an underlying VS Code issue or not.
