### ISSUE TITLE
No option to move files/folders to trash while using remotes

### ISSUE THREAD

**Issue by h4wwk3ye** [microsoft/vscode#96055]
- VSCode Version: 1.44.2
- OS Version: Windows 10 (version 2004, Os build 19041.207)
- WSL distro: Pengwin (wsl2)

Steps to Reproduce:

1. Right-click on any directory/file to delete and the only option present is to delete permanently.

**Comment by aeschli** [comment]
Not sure what's the right approach.
The remotes also have trash folders that can be used
Or use the local trash folder.

**Comment by bpasero** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/1770
