### ISSUE TITLE
Fix and re-enable remote terminal integrated tests

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#96057]
They're probably flaky because there is still a case where the terminal won't launch https://github.com/microsoft/vscode-remote-release/issues/2313

**Comment by joaomoreno** [comment]
@Tyriar Is this still an issue?

**Comment by vhood** [comment]
@joaomoreno "the terminal won't launch" still is a very common problem.
- https://github.com/microsoft/vscode-remote-release/issues/1154
- https://github.com/microsoft/vscode-remote-release/issues/2313
- https://github.com/microsoft/vscode-remote-release/issues/2579
- https://github.com/microsoft/vscode-remote-release/issues/2979
- https://github.com/microsoft/vscode-remote-release/issues/3082
- https://github.com/microsoft/vscode-remote-release/issues/3312
- https://github.com/microsoft/vscode-remote-release/issues/3320
- https://github.com/microsoft/vscode/issues/102880
- https://github.com/microsoft/vscode/issues/102911

**Comment by abhijeetmanhas** [comment]
I'm also facing this same issue, whenever I use remote ssh.
![Screenshot from 2020-07-27 12-46-09](https://user-images.githubusercontent.com/43112347/88515258-0bd4cd00-d009-11ea-80d7-dcf805869391.png)
No options are shown even

**Comment by davyarris** [comment]
I am also experiencing this issue. On WSL 1

**Comment by sameronline** [comment]
I'm constantly getting this issue and it's very frustrating....

**Comment by Dreamupers** [comment]
![image](https://user-images.githubusercontent.com/49057488/93780557-e3f59480-fc5a-11ea-8333-128d36aada4e.png)

**Comment by Tyriar** [comment]
This issue is about tests, https://github.com/microsoft/vscode-remote-release/issues/2313 is tracking the bug.
