### ISSUE TITLE
cant create file by quick button in Folder Explorer

### ISSUE THREAD

**Issue by darktutu** [microsoft/vscode#96051]
Issue Type: <b>Bug</b>

open a repository in vscode ,then I create markdown file in a folder. I cant create a new file in folder by  quick button in Foder exporer when the file count get 20 .
![image](https://user-images.githubusercontent.com/1868626/80200931-f17c0380-8655-11ea-989d-9f67958bef10.png)

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
xml|Dot|2.5.0
gitlens|eam|10.2.1
json-tools|eri|1.0.2
dotnet|for|0.0.4
rest-client|hum|0.23.2
rainbow-csv|mec|1.7.0
csharp|ms-|1.21.17
python|ms-|2020.4.74986
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
Go|ms-|0.14.1
vscode-typescript-tslint-plugin|ms-|1.2.3
vetur|oct|0.24.0
code-settings-sync|Sha|3.4.3
vscode-icons|vsc|10.1.1

</details>

**Comment by isidorn** [comment]
Fixed in latest insiders. If you can reproduce with vscode insiders from next week let me know and i can reopen
