### ISSUE TITLE
Extension icon not showing when installed locally

### ISSUE THREAD

**Issue by lumaxis** [microsoft/vscode#96056]
Issue Type: <b>Bug</b>

I'm developing a small extension and recently published it to the Marketplace. Now, in a new version, I want to add an icon to it. I'd like to see how the icon looks in the Extensions sidebar before actually publishing a new version.
When trying to install a new version from a local package, I can't get the icon to show up, it keeps showing me the default placeholder, even though I think I set up the `icon` property in my `package.json` correctly.

Steps to repro:

1. Develop an extension and add an icon to it
2. Package the extension using `vsce package`
3. Install the extension using `code --install-extension my-extension.vsix`
4. Observe that it doesn't show the local icon

VS Code version: Code - Insiders 1.45.0-insider (d342048538c28d54afd1c6beea03f3a89af04359, 2020-04-23T07:46:52.128Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|64.00GB (17.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
vscode-browser-preview|auc|0.6.6
markdown-preview-github-styles|bie|0.1.6
LinkCheckMD|bla|0.3.1
better-toml|bun|0.3.2
solargraph|cas|0.21.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|2.1.5
vscode-npm-source|dku|1.0.0
binary-plist|dni|0.4.0
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
vscode-npm-script|eg2|0.3.11
code-runner|for|0.9.17
vscode-pull-request-github|Git|0.15.0
rest-client|hum|0.23.2
customize-ui|ioc|0.1.35
monkey-patch|ioc|0.1.7
ReplaceWithNewline|jma|0.0.1
docthis|joe|0.7.1
vscode-peacock|joh|3.7.0
azure-pipelines|ms-|1.165.1
vscode-apimanagement|ms-|0.1.3
vscode-azurefunctions|ms-|0.22.0
vscode-azureresourcegroups|ms-|0.1.0
vscode-docker|ms-|1.1.0
vscode-aks-tools|ms-|0.0.4
vscode-kubernetes-tools|ms-|1.2.0
remote-containers|ms-|0.112.0
remote-ssh-edit-nightly|ms-|2020.4.9540
remote-ssh-nightly|ms-|2020.4.9540
azure-account|ms-|0.8.9
azurecli|ms-|0.5.0
Go|ms-|0.14.1
powershell|ms-|2020.4.0
vscode-node-azure-pack|ms-|0.0.11
vscode-typescript-next|ms-|3.9.20200423
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2048
vsonline|ms-|1.0.1968
debugger-for-chrome|msj|4.12.6
debugger-for-edge|msj|1.0.14
color-highlight|nau|2.3.0
gremlins|nho|0.15.1
vscode-ts-markdown-to-playground|Ort|1.1.0
quicktype|qui|12.0.46
ruby|reb|0.27.0
vscode-yaml|red|0.7.2
vscode-sort-json|ric|1.18.0
vscode-hexdump|sle|1.7.2
code-spell-checker|str|1.8.0
code-spell-checker-german|str|0.1.4
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.1.1
codetour|vsl|0.0.23
gistfs|vsl|0.0.66
gitdoc|vsl|0.0.5
vscode-wakatime|Wak|4.0.0
vscode-todo-highlight|way|1.0.4
vscode-ruby|win|0.27.0
material-theme|zhu|3.3.1

</details>

**Comment by lumaxis** [comment]
Okay, after a little more investigation and some help from @eamodio, I think this might be a regression in Insiders.

- Stable:
    Using `"icon": "images/icon.png"` and installing the extension locally works as expected
- Insiders:
    Using `"icon": "images/icon.png"` and installing the extension locally does **not** work as expected
    However, using `"icon": "./images/icon.png" (notice the `./`) works during local debugging. That obviously doesn't work with `vsce package` though.

**Comment by sandy081** [comment]
Its because you have the extension available in the market place and we give preference to it.
You can try changing the identifier so that it won't match to your extension in market place and change the id back and publish.

**Comment by eamodio** [comment]
@sandy081 why would it be different in stable vs insiders, and why would changing the path to the icon to be `./images/icon.png` cause it to show up?

**Comment by sandy081** [comment]
Oh sorry I did not look at the other comment. Sorry about that.

There should not be any difference, I am not sure why it works on stable and not on insiders. I can try if user can provide me the VSIX that user can repro.

**Comment by lumaxis** [comment]
@sandy081 Attached the `.vsix` file. Note that I only renamed it to add the `.zip` file extension so that GitHub lets me upload it, it didn't actually zip it again.

[snippet-copy-0.2.0.vsix.zip](https://github.com/microsoft/vscode/files/4542308/snippet-copy-0.2.0.vsix.zip)

**Comment by sandy081** [comment]
I cannot repro this as you have latest extension in the marketplace with icon.

This is how it works in insiders/stable:

After you install, icon is picked from the disk until the extension is synced from Marketplace. Once it is synced icon from Marketplace is shown. It could happen that on Insiders, extension got synced and hence no icon is shown. In stable, try to refresh the extensions view and you shall see the same.

Closing this with above explanation.
