### ISSUE TITLE
No italics option for fonts.

### ISSUE THREAD

**Issue by TKF12** [microsoft/vscode#96050]
Add font italic options

**Comment by gjsjohnmurray** [comment]
Please clarify what you mean. Screenshots might be useful. They can usually be pasted direct into the GH textfield from the clipboard.

**Comment by TKF12** [comment]
Font without italics option






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"John Murray"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月24日(星期五) 晚上6:22
收件人:&nbsp;"microsoft/vscode"<vscode@noreply.github.com&gt;;
抄送:&nbsp;"1073516818"<1073516818@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vscode] Font without italics option (#96050)





 
Please clarify what you mean. Screenshots might be useful. They can usually be pasted direct into the GH textfield from the clipboard.

**Comment by TKF12** [comment]
No italics option for fonts.

**Comment by gjsjohnmurray** [comment]
Which font are you using? Does it support italics?

**Comment by TKF12** [comment]
> 您使用哪种字体？它支持斜体吗？

"editor.fontFamily": "MONACO, Consolas, 'Courier New', monospace",
