### ISSUE TITLE
custom snippets for completion items

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#96059]
The idea is to provide a way to override the snippets returned by language servers / extensions with user defined snippets for a better editing experience.

```js
createApp|
```

With completion by the Language Server / Extension
```js
import {createApp} from 'vue'

createApp() // no snippet
```

With a snippet: 

```jsonc
// vue-snippets.json
{
	"prefix": "createApp",
  	"body": ["createApp(App).mount('#app')"],
    "description": "Create a Vue App"
}
```

```js
createApp(App).mount('#app') // no auto-import
```

With (proposed) smarter snippet:

```jsonc
// vue-snippets.json (pseudo-code)
{
	"completionLabel": "createApp",
  	"body": ["createApp(App).mount('#app')"],
    "description": "Create a Vue App"
}
```

```js
import {createApp} from 'vue'

createApp(App).mount('#app') // auto import and snippet :)
```

This would also partially fix https://github.com/microsoft/vscode/issues/1304 since the language server can be smart enough to not suggest `class` inside an object but instead only where it makes sense. 

What it doesn't fix is how to handle snippets that don't directly correspond to a completion item (like `forof`, `forin`), but that is where https://github.com/microsoft/vscode/issues/58112 could come into play.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Asnippets
