### ISSUE TITLE
Button to scroll to the bottom in the terminal

### ISSUE THREAD

**Issue by leopf** [microsoft/vscode#96052]
I would like a button on the right of the integrated terminal to scroll all the way to the bottom with one click. 

I often work with linting libraries that can occasionally output a lot of text into the console. When I scrolled up to address some issue, I need to drag the scrollbar all the way down again to get to the bottom of the terminal. This seems unnecessary and could be avoided by adding a button and/or shortcut to do that for me.

**Comment by ArturoDent** [comment]
There is a command `workbench.action.terminal.scrollToBottom` already bound to <kbd>Ctrl</kbd>+<kbd>End</kbd> that will go to the bottom.  You can also scroll down by a page.  Search for `terminal` and `scroll` in the keyboard shortcuts.
