### ISSUE TITLE
Pressing Enter on a confirmation dialog does not activate the focused button

### ISSUE THREAD

**Issue by ivanjonas** [microsoft/vscode#96066]
- VSCode Version: 1.44.2
- OS Version: MacOS 10.14.6

Steps to Reproduce:

1. Open an existing file.
2. Edit the file so you see the "dirty" marker as a prompt to save the file.
3. Instead of saving, attempt to close the file with Cmd + W.
4. You will be prompted with three options: "Don't Save", "Cancel", and "Save" (screenshot below). The "Don't Save" option appears focused in blue so that it can be activated with the keyboard instead of the mouse.
5. Pressing Enter and Space produce different results
  A. If you press Space, the focused "Don't Save" button is clicked, and your edits are discarded. 
  B. If you press Enter, the unfocused "Save" button is clicked, and your edits are saved. The user probably expected the edits to be discarded based on the focus state of the Don't Save button.

![image](https://user-images.githubusercontent.com/4935079/80229325-43089c00-861e-11ea-925b-e77b646124c8.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by ivanjonas** [comment]
Apparently, this is a native MacOS confirmation, and that's just how they work. 

https://apple.stackexchange.com/a/284134

I would close this bug right away, but I'm not sure what the design guidelines are. It seems counter-intuitive that there are TWO default actions, and they do opposite things. Would it perhaps be good/possible to put the default focus on the Save button? Is this a case where the unintuitive behavior has been around for so long that it is now expected, and good UX does not unreasonably subvert user expectations?

**Comment by sbatten** [comment]
this is controlled by the OS, potentially electron @deepak1556
