### ISSUE TITLE
PHP and HTML don't mix

### ISSUE THREAD

**Issue by thegreatrazz** [Microsoft/vscode#9606]
- VSCode Version: 1.3.1
- OS Version: Windows 10 November Update

Steps to Reproduce:

1. Set code syntax to PHP
2. Write some HTML and PHP code in the same file

The PHP syntax highlighting and intellisense doesn't mix with HTML, other editors do this... Sublime Text, Electron, Wrangler etc. It's a pain, too bad because the rest is really good.

![image](https://cloud.githubusercontent.com/assets/7696711/17045572/927c9ffa-501e-11e6-88df-40b3f48ba526.png)

**Comment by wholroyd** [comment]
This is related to https://github.com/Microsoft/vscode/issues/1751. There are ways around it, but it doesn't always work well if you're trying to override a built-in language that ships with Code.

**Comment by wUFr** [comment]
+1 - im too lazy to switch manualy between languages (:

**Comment by aeschli** [comment]
I think what you see is #3995
