### ISSUE TITLE
Find & Replace \r\n says successful, but it did nothing.

### ISSUE THREAD

**Issue by mbomb007** [microsoft/vscode#96067]
- VSCode Version: 1.44.2 (system setup)
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Find and Replace `\r\n` with `\n` with regex mode on.
2. It shows X occurrences in Y files correctly
3. Click to Replace All.
4. It *incorrectly* shows `Replaced X occurrences across Y files with '\n'.`
5. Changing the regex to something else and back shows the occurrences are still there.

Does this issue occur when all extensions are disabled?: Yes

Related: https://github.com/microsoft/vscode/issues/31449

Please fix it so that we can use regex to replace \r.

**Comment by roblourens** [comment]
It is not actually possible to search for `\r` in the editor because the editor normalizes those away. But, workspace search will return the results. This is a common point of confusion, we should do something better here.

**Comment by mbomb007** [comment]
Files still actually contain `\r`, though, regardless of the normalization. So the best solution would be to allow find/replace of them.

**Comment by LAK132** [comment]
It doesn't work with workspace search and replace either. I think vscode is attempting to revert/normalise line endings on save? Maybe it shouldn't do that after a workspace search and replace...

**Comment by rebornix** [comment]
In the editor, you can always change the line break used in the document and once you save, the new line break will be used.

**Comment by LAK132** [comment]
that doesn't help if you need to change the line endings of thousands of files

**Comment by mbomb007** [comment]
There is an active Backlog for a similar issue, so please upvote it so this gets fixed: https://github.com/microsoft/vscode/issues/31449

**Comment by mbomb007** [comment]
I wonder if there's any way to normalize line endings in multiple files at once. Maybe with tasks?

**Comment by roblourens** [comment]
This depends on and is very closely related to https://github.com/microsoft/vscode/issues/31449 so I will close this as a dupe of that.
