### ISSUE TITLE
.gitignore_global should use the Ignore language mode

### ISSUE THREAD

**Issue by johnbillion** [microsoft/vscode#96079]
When opening a `.gitignore_global` file, it doesn't use the `Ignore` language mode for syntax highlighting, commenting, etc. Opening a `.gitignore` file does.

**Comment by joaomoreno** [comment]
`.gitignore_global` isn't a standard file name, it's just a suggestion given by GitHub. A user can always call it simply `.gitignore`. But sure... we'll take it...
