### ISSUE TITLE
When auto formatting (Windows ctrl+alt+a), it jumps to the last line of code.

### ISSUE THREAD

**Issue by animanoir** [Microsoft/vscode#9607]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

I've been experiencing this issue mostly on HTML files.

1.  Select all (ctrl+a)
2.  Autoformat (ctrl+alt+a)

Most of the times it jumps to the last line of code, and when you have 3000+ it is a bit frustrating to search where you where.

**Comment by kieferrm** [comment]
@animanoir I'm assuming you're using an extensions to format. The built-in formatter uses `Shift+Alt+F`.

The formatter should behave like that: 
- no selection -> format whole file
- selection -> format selection

In your scenario: After step 1 you have a selection that goes from position 0 to the end of the file. The caret is at the end of the file. After the format, the code reveals the caret. Thus, it scrolls to the end. Long story short, you should not have to use step 1 at all to format a whole file. If the extension you use requires that, please file an issue against them.
