### ISSUE TITLE
Notebook UI not applied to file that was already opened in the workspace

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#96078]
Version: 1.45.0-insider
Commit: d342048538c28d54afd1c6beea03f3a89af04359
Date: 2020-04-23T07:46:52.128Z (1 day ago)
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:

1. Open a folder before installing any notebook-based extension
2. open a bunch of files, they'll open in the raw text editor
3. close VS Code
4. install extension that uses a notebook-based extension
5. reopen same folder
6. notice files (that should be in Notebook UI) are still in raw text editor

![image](https://user-images.githubusercontent.com/2644648/80240254-64fe2080-8616-11ea-9eab-77d2ae9eb5e6.png)

Workaround - close the tab and reopen the file:

![image](https://user-images.githubusercontent.com/2644648/80240329-8101c200-8616-11ea-8cb9-a55594d62344.png)

cc @rebornix

**Comment by rebornix** [comment]
Good catch. Interesting bug for workbench restore.

**Comment by rebornix** [comment]
After digging into the code a bit more, I think this might be a "feature", with which you can always see the content with the last editor type you specified (in above case, it's `file`). However I also agree this is not friendly for first-time user experience with "custom" editors. cc @mjbvz

**Comment by rebornix** [comment]
Maybe the first time when a new editor type is registered on user's machine, we can show a notification.

**Comment by TylerLeonhardt** [comment]
Yeah I think this is by-design because it's 'restoring' the editors.
