### ISSUE TITLE
uninstaller

### ISSUE THREAD

**Issue by JonathanDotCel** [microsoft/vscode#96076]
No uninstall entry under AppWiz.cpl, Win10 x64
(haven't performed a shell or os restart yet, but it's not there)

**Comment by sbatten** [comment]
How did you install vs code?

**Comment by JonathanDotCel** [comment]
https://code.visualstudio.com/download
(as of about an hour ago)
Cheers, J

**Comment by joaomoreno** [comment]
I can't reproduce this. Does it appear after you restart?

**Comment by JonathanDotCel** [comment]
Sorry, I'm not able to reproduce it either!
Any suggestions? Willing to give it a shot. 
Otherwise feel free to close the issue, thanks.
