### ISSUE TITLE
remote ssh mode: need to run within remote python env

### ISSUE THREAD

**Issue by galactica147** [microsoft/vscode#96088]
I'm trying Remote-SSH mode to connect to a remote dev server where I have all the necessary python libs, however there seems no way to use the remote env but only a local one. This is quite counter-intuitive. 

Question:
is there a walk around to run Remote-SSH using remote python env? 

Thanks!

**Comment by roblourens** [comment]
Can you check whether the Python extension helps you here? I am not totally familiar with that workflow but I think it has an option to fix your terminal environment.
