### ISSUE TITLE
TreeView.reveal after TreeDataProvider.refresh

### ISSUE THREAD

**Issue by msteen** [microsoft/vscode#96089]
- VSCode Version: 1.44.0 2aae1f26c72891c399f860409176fe435a154b13 x64
- OS Version: Linux old-phoenix 5.5.13 #1-NixOS SMP Wed Mar 25 15:10:18 UTC 2020 x86_64 GNU/Linux

Steps to Reproduce:

```ts
import * as vscode from "vscode"

class MyTreeDataProvider implements vscode.TreeDataProvider<vscode.TreeItem> {
  private _onDidChangeTreeData = new vscode.EventEmitter<vscode.TreeItem | undefined>()
  readonly onDidChangeTreeData = this._onDidChangeTreeData.event

  public items: vscode.TreeItem[] = []

  refresh(): void {
    this._onDidChangeTreeData.fire()
  }

  getTreeItem(element: vscode.TreeItem): vscode.TreeItem {
    return element
  }

  async getChildren(element?: vscode.TreeItem) {
    if (element === undefined) {
      return this.items
    } else {
      return []
    }
  }

  getParent() {
    return null
  }
}

export function activate() {
  const myTree = new MyTreeDataProvider()
  const myTreeView = vscode.window.createTreeView("myTreeView", {
    treeDataProvider: myTree,
  })
  // ... at some later point ...
  const item = new vscode.TreeItem("Foo")
  myTree.items = [item] // change tree data
  myTree.refresh() // trigger rerender
  // The following throws Error: TreeError [myTreeView] Data tree node not found: [object Object]
  myTreeView.reveal(item)
  setTimeout(() => myTreeView.reveal(item), 1000) // this works though
}
```

The package.json should be irrelevant as long as it contains a `myTreeView` view. Let me know if I have to include it even still. The problem is as is shown in the comments, what if you want to reuse a tree view and reveal one of the newly introduced tree items (i.e. data tree nodes)? As far as I know I am left with no hook that is called after `myTree` is finished rebuilding the tree. I tried:

```ts
onDidChangeTreeData(() => myTreeView.reveal(item))
```

However this did not work either. I might be missing something obvious here, because surely showing a newly introduced item within a tree view as active should be a common use case. Maybe I am going about it the wrong way.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
You can know when your tree view is done refreshing based on what `getChildren` is called with.

However, additional API do know when we are done calling `getChildren` might be helpful.

**Comment by msteen** [comment]
Although additional API for this might indeed be helpful, shouldn't this just work? If I can fix it myself with `getChildren`, why can't this happen already behind the scenes? This seems inconsistent with #47153 which should then also be fixable with `getChildren`, but has been deemed a bug.
