### ISSUE TITLE
Typescript syntax highlighting xpath

### ISSUE THREAD

**Issue by DrSammyD** [microsoft/vscode#96087]
Issue Type: <b>Bug</b>

Xpath strings with interpolated variables are being collored as comments instead of strings.
![image](https://user-images.githubusercontent.com/774363/80248676-48b5b000-8625-11ea-8c12-305606222874.png)

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.66GB (14.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
insertnumbers|Asu|0.9.1
gitlens|eam|10.2.1
powershell|ms-|2020.4.0
sublime-keybindings|ms-|4.0.7
vscode-typescript-next|ms-|3.9.20200423

</details>

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by DrSammyD** [comment]
```ts
return By.xpath(`//*[contains(@class, "${Blade.bladeClass}") and descendant::*[contains(@class, "fxs-blade-title-subtitle") and descendant::*[contains("Deployment",text())]]]`);
```

**Comment by mjbvz** [comment]
Works fine for me in VS Code insiders:

<img width="1192" alt="Screen Shot 2020-04-24 at 4 31 05 PM" src="https://user-images.githubusercontent.com/12821956/80264438-01411b00-8649-11ea-84b0-753d435efecb.png">


Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
