### ISSUE TITLE
Broken task detection within a workspace

### ISSUE THREAD

**Issue by johnbillion** [microsoft/vscode#96086]
Issue Type: <b>Bug</b>

When attempting to configure or run a task defined in a workspace configuration file, Code displays the following error:

```
Error: The npm task detection didn't contribute a task for the following configuration:
{
    "label": "Test",
    "type": "npm",
    "script": "test"
}
The task will be ignored.
```

Managing tasks in `tasks.json` file works as expected, but managing these tasks within a workspace file does not.

## Steps to Reproduce

1. Create an npm project: `mkdir foo && cd foo && npm init`
2. Fill out package information and run `npm install`
3. Create a `foo.code-workspace` file with the following contents:  
    ```
    {
        "tasks": {
            "version": "2.0.0",
            "tasks": [
                {
                    "label": "Test",
                    "type": "npm",
                    "script": "test",
                }
            ]
        },
        "folders": [
            {
                "path": "."
            }
        ]
    }
    ```
4. Open the workspace in VS Code
5. Attempt to run any of the `Tasks` commands, for example `Configure Default Build Task`.
6. Observe the error above.

---

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (2.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
alignment|ann|0.3.0
vscode-intelephense-client|bme|1.3.11
wordpress-i18n-tagger|cam|0.0.8
bracket-pair-colorizer-2|Coe|0.0.29
vscode-dash|dee|2.4.0
EditorConfig|Edi|0.14.5
php-debug|fel|1.13.0
vscode-pull-request-github|Git|0.15.0
vscode-wordpress-hooks|joh|0.1.0
vscode-peacock|joh|3.7.0
rainbow-csv|mec|1.7.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
sublime-keybindings|ms-|4.0.7
php-docblocker|nei|2.1.0
vscode-sort-json|ric|1.18.0
trailing-spaces|sha|0.3.1
phpcs|she|1.0.8
vscode-stylelint|sty|0.84.0
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by alexr00** [comment]
Only shell and process tasks are supported in the workspace file. https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-task-configuration

**Comment by johnbillion** [comment]
Thanks!
