### ISSUE TITLE
Function Keys don't work in Integrated Terminal

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#9608]
- VSCode Version: 1.4.0-Insiders
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open Integrated Terminal
2. Press F5 to debug

Expected: The debugging process starts up
Actual: Nothing happens.

Not sure if it's valid but we can press function keys in Debug Console.

**Comment by kieferrm** [comment]
Related to #7269.

**Comment by Tyriar** [comment]
Closing as duplicate, currently you'll need to either close the terminal (<kbd>ctrl</kbd>+<kbd>`</kbd>) or move focus to the editor (<kbd>ctrl</kbd>+<kbd>1</kbd>) beforehand.
