### ISSUE TITLE
Implement Window/Page scroll commands

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#9609]
These commands are needed for Vim:

From https://github.com/VSCodeVim/Vim/issues/210:

Vim has handy commands for scrolling without moving the cursor, e.g. zt, which scrolls the screen so that the line with the current cursor is placed as the first line. E.g., I often do actions like /main(<CR>zt, so that I can see as much of the main function as possible.

Would it be possible to implement zt, zb and zz?

Thanks!

- [x] Scroll window upwards/downwards by lines (real line) or window size (eg, half window size)

```javascript
executeCommand('editorScroll', {to: 'up', by: 'line', value: 10, revealCursor?: false});
```

### 'to'
- up
- down

### 'by'
- line
- wrappedLine
- page
- halfPage

### 'revealCursor'

- If `true` reveals the cursor while scrolling otherwise does not.

- [x] Scroll line to a specific position of the window

```javascript
executeCommand('revealLine', {lineNumber: 10, at: 'top'});
```

### 'at'
- top
- center
- bottom

- [x] Scroll horizontal scrollbar by column numbers.
Horizontal scrolling is already implemented by cursor move commands. Hence marking this done. See #8997

**Comment by rebornix** [comment]
About the first task, just realized that we have `scrollLineUp` `scrollLineDown`, `scrollPageUp` and `scrollPageDown` commands already. The only part missing is scrolling half page down.

**Comment by sandy081** [comment]
@rebornix Delivered a new command called `editorScroll`. Try it and let me know the feedback. See the description for usage. 
Thanks

**Comment by rebornix** [comment]
@sandy081 I just ran your commands but see below errors

```
error.stack
Error: argument does not match one of these constraints: arg instanceof constraint, arg.constructor === constraint, nor constraint(arg) === true
    at f (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:29:13605)
```

any idea?

**Comment by sandy081** [comment]
@rebornix Hmm strange, I do not see any issue while using this command in our sample Vim extension. Can you show me how are you calling this command?

**Comment by rebornix** [comment]
@sandy081 I just simply called `await vscode.commands.executeCommand('editorScroll', {to: 'up', by: 'line', value: '1'});`. This error occurs always on 1.5.0-Insider.

**Comment by rebornix** [comment]
Finally I saw the problem. I'm not using the value of `to` correctly, I thought `to: 'up'` will move current line move upwards but actually it will move the line downwards. For example, let's say currently the first line shown in the window is No.20 and we run `await vscode.commands.executeCommand('editorScroll', {to: 'up', by: 'line', value: '1'});`, the first line shown will change to No.19. Is this expected?

**Comment by sandy081** [comment]
@rebornix editorScroll command does not disable any scrolling in the above scenario. It just scrolls the window up or down irrespective of the cursor position. It does not reposition the cursor if it goes outside view port. I think this is beyond the scope of command's functionality.

**Comment by rebornix** [comment]
@sandy081 that's what I'm seeing, now I reposition the cursor in VSCodeVim's code and it works well. The only issue I see is scrolling doesn't work on first line, can you help confirm?

**Comment by sandy081** [comment]
@rebornix Enhanced `editorScroll` command to reveal cursor while scrolling. See the description for syntax and how to use.


Also implemented `revealLine` command to reveal the line at the given logical position in the screen. Again see the description for usage.

**Comment by rebornix** [comment]
@sandy081 Played with `revealLine` not sure I'm doing correctly but when I run ` await vscode.commands.executeCommand('revealLine', {lineNumber: 1, at: 'top'});`, the window scroll down by 1 line and the cursor doesn't move. The cursor behavior is expected but seems `top` is not working. I suppose `'revealLine', {lineNumber: 1, at: 'top'}` will move current line to the top first line in the window, right?

**Comment by sandy081** [comment]
@rebornix Yeah, please check if there is some side effect from Vim extension, because this was working properly in the sample.

**Comment by rebornix** [comment]
@nschurmann https://github.com/Microsoft/vscode/issues/14854#issuecomment-257939552
