### ISSUE TITLE
Add support to dispatch keybindings based on CAPSLOCK

### ISSUE THREAD

**Issue by bitm0de** [microsoft/vscode#96097]
Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

In my case, I have a keybinding entry:
`{ "key": "j", "command": "vscode-neovim.compositeEscape1", "when": "editorTextFocus && neovim.mode != normal", "args": "j" }`

The lowercase 'j' gets inserted even when I have CAPSLOCK enabled so if I try to type "JUSTIFY" it comes out as "jUSTIFY".

P.S - Is there a "when" clause to determine if CAPSLOCK is enabled? If not, this would be a good addition to be able to check these things.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
Keybindings rules are not meant to be used for text input. Consider, for example, the case where the keyboard is on a different keyboard layout, like Russian, where `j` nor `J` are produced when pressing `j`.

The keybindings rules are evaluated on `keydown` and the produced character occurs only after that.

If you wish to capture textual input, then it is possible to overwrite the built-in `type` command of the editor, but I think the vim extension you have installed is already doing that, so perhaps you need some kind of feature from the vim extension?

**Comment by bitm0de** [comment]
Capslock isn't necessarily text input though since by default it just toggles modes. If the keybinding rules are only evaluated on keydown, this shouldn't affect the ability to check for capslock being enabled/disabled at that point in time via the when clause.

If the vim extension is capturing text input though, maybe that is the issue here and why I'm seeing this behaviour of a lowercase 'j' when capslock is enabled...? Maybe I will have to spend some time looking through the extension to observe where the real problem is.

I just figured maybe some extensibility here on the VSCode side might still be a good thing. Thanks for responding.
