### ISSUE TITLE
Breadcrumbs filter

### ISSUE THREAD

**Issue by avicenna-developer** [microsoft/vscode#96102]
A filter field in the breadcrumbs would be useful in the searching related blocks of code.

**Comment by avicenna-developer** [comment]
These issues aren't related to the issue posted by me.

________________________________
Alejandro Reinoza
Software Developer
Avicenna Medical Systems, Inc.
http://www.avicenna-medical.com/
(914) 704-5981
alejandro@avicenna-medical.com

**Comment by jrieken** [comment]
I don't understand what you want. Please clarify

**Comment by avicenna-developer** [comment]
> I don't understand what you want. Please clarify
The default behavior when clicking on a breadcrumb node is to display sibling nodes in a list, therefore an input field in that list to filter out sibling nodes should come in handy.

**Comment by jrieken** [comment]
> display sibling nodes in a list, therefore an input field in that list to filter out sibling nodes should come in handy.

You can simply type in that list to filter or find, just like in all other lists.

**Comment by avicenna-developer** [comment]
That's the matter, that list doesn't have a input field to type.

_______________________________
Alejandro Reinoza
Software Developer
Avicenna Medical Systems, Inc.
http://www.avicenna-medical.com/
(914)704-5981
alejandro@avicenna-medical.com

**Comment by jrieken** [comment]
That was a design decision that we have made for all trees and list and, honestly, we have no plans of changing that
