### ISSUE TITLE
Editing powershell files bring up the powershell editor services process which takes cpu consumption to 100%

### ISSUE THREAD

**Issue by allendm-msft** [Microsoft/vscode#9610]
- VSCode Version:1.3.1
- OS Version:Win10

Steps to Reproduce:

1. Open github repo "vsts-tasks" in vscode
2. Play around with some of the powershell files

**Comment by kieferrm** [comment]
This most likely is https://github.com/PowerShell/PowerShellEditorServices/issues/31.

Also see #9503.
