### ISSUE TITLE
Make measuring extension host latency easier

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#96109]
Make measuring extension host latency easier. Although we can use `editor.action.measureExtHostLatency`, it is difficult to use it repeatedly for monitoring the latency since the command opens a new editor on each execution. A command printing the results to the console is preferable, which is used in #87039.

**Comment by LeuisKen** [comment]
I prefer to show latency outputs on status bar, like this product. 
![image](https://user-images.githubusercontent.com/7701575/81367681-7ec45b00-9120-11ea-8dd4-1bc323e9b172.png)
“网络延迟 高” means "High network latency".
This feature will be really helpful when I'm using Visual Studio Codespace and VS Code Remote. It can remind me of the current network quality, and warns me to try to improve the network quality when the quality is poor. And in this case, this feature will not for developers but for users. The display of this status could be controlled by settings.json.

**Comment by LeuisKen** [comment]
I found my problem is not as complex as I imagined. By using some tricks, I wrote a simple extension that could do this work. And I just publish it to the marketplace.
https://marketplace.visualstudio.com/items?itemName=LeuisKen.latency
