### ISSUE TITLE
Error when using "Files: Reopen with..." with "permanent/pinned" tabs

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#96105]
Version: 1.45.0-insider
Commit: d342048538c28d54afd1c6beea03f3a89af04359
Date: 2020-04-23T07:46:52.128Z (1 day ago)
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:

1. open a file in a Notebook UI
2. "double click" on tab to make it permanent/pinned (not italicized file)
3. use "Files: Reopen With..." to re open in Text editor 
4. a _new tab_ is opened (doesn't seem expected to me...)
5. click on the other tab (the tab in Notebook mode)
6. at this point you can't click back to the tab with the text editor

Stack trace from dev tools:

```
ERR Cannot read property 'kind' of null: TypeError: Cannot read property 'kind' of null
    at asHoverContent (/Users/tyleonha/Code/PowerShell/vscode/vscode-powershell/node_modules/vscode-languageclient/lib/protocolConverter.js:101:27)
    at asHover (/Users/tyleonha/Code/PowerShell/vscode/vscode-powershell/node_modules/vscode-languageclient/lib/protocolConverter.js:134:31)
log.ts:197   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
```

cc @rebornix

**Comment by rebornix** [comment]
I can't reproduce this issue in latest Insiders now.

**Comment by TylerLeonhardt** [comment]
I can still repro this.

**Comment by TylerLeonhardt** [comment]
new steps:

open a file in a default text editor
"double click" on tab to make it permanent/pinned (not italicized file)
use "Files: Reopen With..." to re open in Notebooks
a new tab is opened (doesn't seem expected to me...)
click on the other tab (the tab in default mode)
at this point you can't click back to the tab with the Notebook

**Comment by TylerLeonhardt** [comment]
This appears to be important:

```json
"workbench.editorAssociations": [
        {
            "viewType": "default",
            "filenamePattern": "*.ps1"
        }
    ],
```
