### ISSUE TITLE
Honor workbench.editorAssociations in Notebooks

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#96101]
Version: 1.45.0-insider
Commit: d342048538c28d54afd1c6beea03f3a89af04359
Date: 2020-04-23T07:46:52.128Z (1 day ago)
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:

1. set this:
```
"workbench.editorAssociations": [
        {
            "viewType": "default",
            "filenamePattern": "*.ps1"
        }
    ]
```
2. Open a file that has a Notebook provider associated to it.

**Expected**: Opens in Text editor
**Actual**: Opens in Notebook

cc @rebornix

**Comment by rebornix** [comment]
Already fixed in latest Insiders.

**Comment by TylerLeonhardt** [comment]
Can confirm. This is fixed.

**Comment by isidorn** [comment]
Adding verified label per Tylers comment.
