### ISSUE TITLE
VSCode JS debugger fails to honor symlinks when expanding ${file}

### ISSUE THREAD

**Issue by kingces95** [microsoft/vscode#96114]
- VSCode Version: 
> Version: 1.45.0-insider
Commit: a250df703de955a38aed427a917bce8278ab3331
Date: 2020-04-24T20:46:59.782Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

- OS Version:
![image](https://user-images.githubusercontent.com/4120386/80271377-6867cb00-865b-11ea-8c69-979f015e37a9.png)

Steps to Reproduce:
1. Create a debug profile that opens `${file}`
2. Create a `foo/test.js` with code `console.log(__dirname)`
3. Create a symbolic link to `foo/` named `bar/`
4. Open `bar/test.js`
5. Start debugging

Expect to log `bar/` but actually logs `foo/`

See video: https://youtu.be/U28dq6Ctam4

Source: [symlink.zip](https://github.com/microsoft/vscode/files/4532365/symlink.zip)

Does this issue occur when all extensions are disabled?: Yes

**Comment by kingces95** [comment]
There are a number of other symlink unexpected behaviors. Linked content not refreshing, moving links around doesn't update the relative path to reflect the links new location, etc. 

If symlink support is slated to be first class, I can make vids.

**Comment by connor4312** [comment]
This happens when running the file with Node.js directly from the terminal as well; this does not appear related to debugging.

```
➜  foo ll
total 0
lrwxr-xr-x  1 copeet  staff    31B May 13 08:49 bar -> /Users/copeet/Downloads/foo/foo
drwxr-xr-x  3 copeet  staff    96B May 13 08:50 foo
➜  foo node foo/test.js 
/Users/copeet/Downloads/foo/foo
➜  foo node bar/test.js
/Users/copeet/Downloads/foo/foo
```

/out-of-scope
