### ISSUE TITLE
Empty panel behaves weird

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96117]
I removed all panes from the panel and got an empty panel. I cannot drop anything in there it seems and after a reload I am greeted with errors when I drag over:

```
compositeBar.ts:227 Uncaught TypeError: Cannot read property 'id' of undefined
    at Object.onDragOver (compositeBar.ts:227)
    at Object.onDragOver (dnd.ts:634)
    at HTMLDivElement.<anonymous> (dnd.ts:468)
```

It also looks like the "..." thing that appears cannot be interacted with and is not rendered centered:

![image](https://user-images.githubusercontent.com/900690/80272924-157b2b80-86ce-11ea-8ec1-16a31794aec3.png)

**Comment by SirIntruder** [comment]
In case anyone needs a workaround until this gets fixed, "View: Reset View Locations" will put tabs back into the panel.

**Comment by sbatten** [comment]
we now get the following: 
![image](https://user-images.githubusercontent.com/6561887/81726175-cf4af980-943b-11ea-8d33-7c77711b1151.png)

Alternate string suggestions welcome.

**Comment by bpasero** [comment]
Maybe just "Drag a view into the panel to display"?
