### ISSUE TITLE
`Cannot read property 'uri' of undefined` when command without any workspace folder open

### ISSUE THREAD

**Issue by ganxy1028** [microsoft/vscode#96111]
Issue Type: <b>Bug</b>

When command without any workspace folder open, it will fail with an alert `Cannot read property 'uri' of undefined`. However, everything is all right with there is a folder in workspace

I reported this bug in https://github.com/microsoft/vscode-python/issues/11291, but this morning, I found it happens on both `Python` and `Markdown All in One` extension, so I think it might be a vscode issue.

![markdown_fail](https://user-images.githubusercontent.com/26629457/80270468-0060c580-86eb-11ea-902b-20c1b8f52f0c.png)

![python_fail](https://user-images.githubusercontent.com/26629457/80270505-56356d80-86eb-11ea-9b1d-122797f7480f.png)

The console for python fail is so much, so it is attached in a zip.
[python_fail_logs.zip](https://github.com/microsoft/vscode/files/4532320/python_fail_logs.zip)

It may be a `workspace.workspaceFolders[0].uri.fsPath` problem? Sorry, I'm not professional enough.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.4.74986
vscodeintellicode|Vis|1.2.6
markdown-all-in-one|yzh|2.8.0

</details>

**Comment by gjsjohnmurray** [comment]
More than one extension developer has made the same mistake when using the API. Please report each one you see to the extension author.
