### ISSUE TITLE
Should not allow to "Hide" the last view in a custom view container

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96116]
When I make e.g. "NPM Scripts" its own container, I am offered with a "Hide" action still, even though it is the only view:

![image](https://user-images.githubusercontent.com/900690/80272652-997fe400-86cb-11ea-88a4-ef9277326599.png)

**Comment by sbatten** [comment]
To Verify:
1. Drag outline from explorer into Activity Bar
2. Open outline viewlet and right click the header.

Ensure "Hide" is not shown and that you cannot toggle it via the checkbox option
