### ISSUE TITLE
Key bindings issue after update

### ISSUE THREAD

**Issue by kirill-kruchkov** [Microsoft/vscode#9611]
- VSCode Version: 1.4.0 - Insider (01a3f868552dc8011adf4e79bee8cfb09babfe31  2016-07-22T05:01:51.457Z)
- OS Version: OS X El Capitan 10.11.5 (15F34)

Steps to Reproduce:

Cmd+/ is mapped to comment or uncomment current or selected line(s) of code.

1. New update comes
2. Click update in green bar
3. VSCode restarts
4. Cmd+/ is now to duplicate current tab.

After manual quit and start Cmt+/ stands for comment/uncomment again.

**Comment by kieferrm** [comment]
@kirill-kruchkov that's a tough one. Worked perfectly for me trying the same scenario. No way to reproduce.
