### ISSUE TITLE
[json] Formatting a JSON file should not remove the trailing newline

### ISSUE THREAD

**Issue by aaronfranke** [microsoft/vscode#96112]
In #19281, @mousetraps said that removing the newline at the end is by design.

However, this may not be an ideal design. By POSIX definition, a text file ends with a newline character. If it does not end with a newline character, it is not a text file, only a stream of bytes.

Therefore, for anyone who wishes to have their JSON files be POSIX-valid text files, I think it would be best if VS Code did not remove already-existing newline characters in text files.

It is not necessary for VS Code to add newline characters where there currently aren't any, unless users have "Files: Insert Final Newline" enabled, in which case it should. Regardless of this setting, VS Code should not remove already-existing trailing newline characters (it should leave 0 or 1 of them).

**Comment by aeschli** [comment]
duplicate of #17359 

Also related: #23260
