### ISSUE TITLE
Error message like "No space left" while open terminal

### ISSUE THREAD

**Issue by ArianeLu** [Microsoft/vscode#9612]
- VSCode Version: 1.3.1
- OS Version: Windows 10 Version 1511

Steps to Reproduce:

1. Just open built-in terminal

![20160722163440](https://cloud.githubusercontent.com/assets/4962408/17051273/680ae6b2-502a-11e6-91f3-e29030f13d98.png)

See the screenshot, sorry for Chinese in it, because my system language is Chinese.
It mean "No space left on devices, can't process this command"
I have check my disk, both have 50GB free space.

**Comment by Tyriar** [comment]
@ArianeLu are you still running into this issue? Anymore information you can provide?

**Comment by ArianeLu** [comment]
@Tyriar One of my computer still have this error message, it just a message, terminal work fine.

**Comment by Tyriar** [comment]
Interesting, it's probably an upstream problem so let's keep this one closed.
