### ISSUE TITLE
Resetting view locations shows codicon in panel area

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96121]
I had the terminal in the sidebar and invoked the "Reset View Locations" command. Back in the panel the terminal seems to have gotten a codicon that is not rendered:

![image](https://user-images.githubusercontent.com/900690/80272874-ab628680-86cd-11ea-97f9-235c17645000.png)

![image](https://user-images.githubusercontent.com/900690/80272877-b2899480-86cd-11ea-9ff5-de67664279d9.png)

**Comment by sandy081** [comment]
/duplicate

fixed by #96465.
