### ISSUE TITLE
"Add missing enum member" refactor duplicates comment

### ISSUE THREAD

**Issue by kaleidawave** [microsoft/vscode#96129]
- VSCode Version: 1.44.2
- OS Version: n/a

Steps to Reproduce:

1. Given this code in a TypeScript file:

```ts
// My Comment
enum X {
    Foo,
}

X.Bar
```
2. As the `Bar` entry does not exist on `X` it will give the option "Add missing enum member". Applying it duplicates the comment above:
```ts
// My Comment
// My Comment
enum X {
    Foo,
    Bar
}

X.Bar
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Thanks for the repro steps.

This is fixed for me in TypeScript 3.9. We won't bundle TS 3.9 for another iteration (VS Code 1.46). Until then, you can use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)
