### ISSUE TITLE
Set default browser for VSCode application

### ISSUE THREAD

**Issue by 1oglop1** [microsoft/vscode#96132]
Hi, I'm using multiple browsers / profiles and I would like to be able to set the default web browser per application or workspace.

The solution could be similar to what VisualStudio have which gives a user drop down menu to chose the browser.
Ideally there should be an option in settings to select a default browser for all actions which require VSCode to open the web browser.

Example of current problems:
If I want to log in into a LiveShare extension it opens my default browser (chrome) where my microsoft profile is different then the one I want to use to sign in for sharing the code.

This is very irritating because the microsoft URLs often contains multiple redirects and who knows what so I cannot just copy the URL and sing in using a different browser with the correct profile.

Here is more evidence that this feature would be appreciated by more people.
https://stackoverflow.com/questions/47519768/how-do-i-set-the-default-browser-as-chrome-in-visual-studio-code/47520320

**Comment by cobr31** [comment]
Agree with 1oglop1: Feature request gets my vote too. Seriously detracts from an otherwise useful tool. Scratching my head to understand why it wasn't there to begin with.

**Comment by gitowiec** [comment]
When this feature will be relesased?

**Comment by MuqadderIqbal** [comment]
Do we have an update on when this option will become available?

**Comment by diligent176** [comment]
I'm looking for this feature too, landed here...  
I can set almost everything in VS Code, why not the default web browser?  :-)

**Comment by devchia254** [comment]
I am also waiting for this feature. Any update?

**Comment by Yemzibossa** [comment]
How I wish I can also change my default browser on VS Code... Mine is always opening UC Browser of which I want Google Chrome...

**Comment by asmetcalf** [comment]
Looking forward to seeing this feature implemented as well.

**Comment by AyoCodess** [comment]
any update?

**Comment by shivshivshivshiv** [comment]
[SOLVED]
https://stackoverflow.com/a/59882442/15664422

copy-pasting it here..

 Set BROWSER variable in package.json present in your project in the following manner:

Replace:

"start": "react-scripts start"
With:

Linux:
"start": "BROWSER='google-chrome-stable' react-scripts start"
Windows:
"start": "BROWSER='chrome' react-scripts start"
OS X:
"start": "BROWSER='google chrome' react-scripts start"

**Comment by mamakawama** [comment]
Watching this as well

**Comment by henriiqueg** [comment]
Updates?

**Comment by mailsanchu** [comment]
Any updates

**Comment by SulthanNK** [comment]
Any updates about this feature?

**Comment by zhongxiang117** [comment]
Any updates? It gets my vote too.

**Comment by AKP2401** [comment]
Gets my vote too.
😄

**Comment by krish-1010** [comment]
Where setting?

**Comment by krish-1010** [comment]
![where](https://user-images.githubusercontent.com/75911554/124607475-83eb7a00-de8b-11eb-9893-e3a7b517acaf.jpg)

**Comment by MKstudio-Tech** [comment]
Gets my vote too. Please add this feature.

**Comment by muhdamean** [comment]
Here is what I find
Go to Settings -> Extensions -> Live Server Config -> Custom Browser
you can then choose your browser of choice

**Comment by SulthanNK** [comment]
> Here is what I find
> Go to Settings -> Extensions -> Live Server Config -> Custom Browser
> you can then choose your browser of choice

Yes @muhdamean It works only using while using a live server extension.
But, people who work using NodeJS or some other web-based projects need this feature. Because we can't choose the browser of our choice while the NodeJS server starts running.

**Comment by ayushi-vishwakarma08** [comment]
Any updates? Please add this feature. It gets my vote too.

**Comment by Soulzityr** [comment]
Can we get an update as to when this feature is expected? This seems to be a commonly needed one.

**Comment by diarybook** [comment]
Gets my vote too. Please add this feature.

**Comment by saulvg1** [comment]
Any updates on this? I know there was an update recently.

**Comment by ThaDaVos** [comment]
I would love to see this feature too

**Comment by joeaddison** [comment]
+1

**Comment by evanwilliamson-syneos** [comment]
+1

**Comment by jan-niestadt** [comment]
+1

**Comment by sahilrajput03** [comment]
Need this feature ASAP!!

**Comment by TomaszGasior** [comment]
@sahilrajput03 Please don't write this kind of comments. They don't help in resolving the issue but cause sending spam notifications to all people subscribed to the topic. Instead, just subcribe to get new information about the progress. Thank you.

**Comment by smcenlly** [comment]
I'd really like to see this feature. I assume that there needs to be some special processing in `nativeHostMainService.ts`?

https://github.com/microsoft/vscode/blob/b4d5b4ed69af953901051b1f049851b9dca3563e/src/vs/platform/native/electron-main/nativeHostMainService.ts#L449

I assume could check to see if file type is URL (`http` or `https`) and if so, open with a specific browser based on a new setting?

I'd be happy to contribute if someone from the VS Code team is happy with the approach.

**Comment by srveit** [comment]
+1

**Comment by Arinze25** [comment]
+1

**Comment by soyfrien** [comment]
Yes, I prefer having Microsoft stay in Edge (and my system default to the new DuckDuckGo browser).

**Comment by blakegearin** [comment]
+1

**Comment by nulevii** [comment]
Any updates?

**Comment by johndifelice** [comment]
After all this it's closed and the links send you round in circles.

**Comment by Cylecq** [comment]
+1

**Comment by dbanks12** [comment]
+1

**Comment by TomaszGasior** [comment]
Please stop writing "+1"  or "any updates" comments like that — that's just spam.  Don't write comment if you do not have any valuable information to add to the topic.  Thank you.

**Comment by smcenlly** [comment]
FYI to any Mac users following this thread, I found [https://choosy.app](https://choosy.app), which allows me to configure default browser based on app. It's a paid app, but does the job well.

**Comment by bathyscaaf** [comment]
Just found this thread.  I would like this ability as well, here is my use case:

I have 2 projects, both Vue based -- but one is Vue2 and the other is Vue3.
Vue2 and Vue3 have different devtools extensions, so I have the Vue2 devtools installed on Firefox Dev Edition browser, and Vue3 devtools installed on Chrome.

My OS default, daily driver browser is Firefox with Noscript enabled -- not what I want to develop with.

The ability to set the default browser per project would be pretty handy.

**Comment by TinyMito** [comment]
Would love to see this as well, I'm using Firefox Developer Edition and every time React app launch, it loads into my other primary normal browser.

**Comment by jons-pf** [comment]
Please implement this!

**Comment by a3diti** [comment]
+1
still needing this

**Comment by guidonaselli** [comment]
+1

**Comment by bpasero** [comment]
How would this work as setting? Allow to configure the path to an executable and then we would just execute that path and append the URL as argument?

**Comment by smcenlly** [comment]
@bpasero - I think that sounds reasonable. I think (in addition) it would ideal if you could iterate the browsers in an OS specific way (e.g. [for MacOS](https://stackoverflow.com/questions/931264/enumerating-installed-browsers-on-os-x)), but starting with a setting as you describe would work and I'm sure would satisfy the needs of this issue.

I assume you'd expose as a VS Code setting which means it could then be overridden at the workspace level?

**Comment by bpasero** [comment]
What is the use case for a workspace specific setting? I was thinking of a application global setting.

**Comment by alexkuc** [comment]
@bpasero What's the advantage of enumerating apps in a specific way, like in the MacOS example linked?

**Comment by smcenlly** [comment]
@bpasero - for me personally, I prefer to use Safari, but when I'm doing front-end development, I use Chrome. So I would have a workspace override for my front-end projects only. Having said that, I think I mentioned above, I found another solution (https://choosy.app/), so I'm really only advocating for others in my reply.

@alexkuc - enumerating apps capable of launching websites (i.e. browsers) provides a nicer UX (vs. needing to find the path for your browser), that's all.

**Comment by 6XGate** [comment]
Definitely need this. I use FF Dev Edition for work, and need anything from the AWS Plug-in in VSCode to open in that browser and not my OS default. The OS default is used for personal stuff. IntelliJ and its family (like WebStorm and PHPStorm) already support this.

**Comment by viktor-berezin** [comment]
+1

**Comment by lockiandd** [comment]
+1 for me. I have different browsers authorized to different users and require the ability to launch to a specific browser that I do not wish to be my default browser from vscode.

**Comment by laurensnl** [comment]
+1

**Comment by ijuji** [comment]
+1 !!

**Comment by snaow** [comment]
+1

**Comment by alexkuc** [comment]
@smcenlly Your recommendation of [Choose](https://choosy.app/) looks good but it appears it is not published on App Store so it didn't go through the regular Apple-vetting process for apps. Being super paranoid given how not even MacOS is safe anymore from malware. Is it something you can vouch for in terms of this app being safe?

**Comment by smcenlly** [comment]
@alexkuc - I’ve been using it since I mentioned and it’s been good. Since then, I kind of feel this isn’t necessarily a VS Code issue. There’s likely a windows “Choosy” equivalent.

**Comment by danielsharvey** [comment]
> Your recommendation of [Choosy](https://choosy.app/) looks good but it appears it is not published on App Store so it didn't go through the regular Apple-vetting process for apps. Being super paranoid given how not even MacOS is safe anymore from malware. Is it something you can vouch for in terms of this app being safe?

@alexkuc I recommend it. It has some good options in terms of rules which I make regular use of.

**Comment by fanckush** [comment]
Here's a solution for macOS to open **all** links from vscode no matter where from (think tooltips, integrated terminal etc.) in firefox and everything else as normal is Safari

1. install [fnicky](https://github.com/johnste/finicky) using [brew](https://brew.sh) 
```  sh
brew install --cask finicky
```

2. in your home directory `~/` create the following file
```  sh
touch ~/.finicky.js
```

3. paste the following block into it
``` js
module.exports = {
  defaultBrowser: 'Safari',
  handlers: [
    // open any link clicked in Vscode in BRave Browser
    {
      match: ({ opener }) => opener.bundleId === 'com.microsoft.VSCode',
      browser: 'Firefox',
    },
  ],
}
```

4. make sure Flinky is your default browser and make sure to reload the config file 
![image](https://github.com/microsoft/vscode/assets/6278713/ffd3f4e0-162e-420f-8717-87d90a983772)


Done, now every link clicked from within VSCode will take you to Firefox and everything else will go to Safari

**Bonus:** https://github.com/johnste/finicky?tab=readme-ov-file#example-configuration

**Comment by SavvasNestorLopez** [comment]
Any updates here without 3rd party solutions?

**Comment by nesslopz** [comment]
Any updates here without 3rd party solutions?

**Comment by bpasero** [comment]
With todays insider build, a new setting `workbench.externalBrowser` can be configured. Please try it out and let me know how it works.

You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
Sorry, due to some trouble, we only now have an insiders build out including this change 🙏

**Comment by Nisheshg5** [comment]
Can we also specify the browser profile with this change?

**Comment by bpasero** [comment]
Please open a new FR.
