### ISSUE TITLE
Emmet not running/working

### ISSUE THREAD

**Issue by musayev-io** [microsoft/vscode#96139]
**Problem**: Emmet does not appear to be running, even though it's supposed to be installed with VS Code. When running `Developer: Show Running Instances`, Emmet does not appear on the list. 

- VSCode Version: 
```Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

- OS Version:macOS Mojave: 10.14.6 (18G4032)

Steps to Reproduce:

1. Type `div.container` in VS Code and run `Emmet: Expand Abbreviation`
2. Receive the following error in the bottom left of the screen: _**"Command 'Emmet: Expand Abbreviation' resulted in an error (command 'emmet.expandAbbreviation' not found)"**_

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
> `Developer: Show Running Instances`

Do you mean `Developer: Show Running Extensions`?

Help -> Toggle Developer Tools. Do you see any errors?

Also what is the filetype you are editing? Try it in a HTML file.
