### ISSUE TITLE
Autocomplete hangs in go

### ISSUE THREAD

**Issue by kstenerud** [microsoft/vscode#96136]
- VSCode Version: 1.44.2
- OS Version: Ubunut 20.04

Steps to Reproduce:

1. Download and install visual studio code
2. Install Microsoft go extension
3. Install all recommendations
4. Open go file
5. Hover over a function

It will display "Loading..." and never show anything else.

Does this issue occur when all extensions are disabled?: Yes/No

No. When extensions are disabled, go is not supported.

**Comment by usernamehw** [comment]
You should file the issue at the extension repository https://github.com/Microsoft/vscode-go
