### ISSUE TITLE
WSL2: Git not showing modifications on symlink folder

### ISSUE THREAD

**Issue by Mystic8b** [microsoft/vscode#96131]
- VSCode Version: 1.44.2
- OS Version: Win10 2004 19041.208
- WSL Version: 2
- Distro: Ubuntu 20.04

Steps to Reproduce:

1. Create a symlink to the directory with the github project in wsl:
`ln -s /mnt/c/Users/Mystic/Documents/Projects/ ~/projects`
2. Open project in vscode
`mystic@officePC ~/projects/myproject (master)$ code .`

Thereafter:
- I do not have a flag about a change in the settings.json file (the letter M should be on the right);
- In bash, the default directory opens (maybe it’s impossible otherwise, but this is also not convenient).

![image](https://user-images.githubusercontent.com/35394377/80279237-d0beb700-8704-11ea-948d-f492dd7bee4d.png)

Does this issue occur when all extensions are disabled?: I'm not sure, because I need the wsl extension

**Comment by Mystic8b** [comment]
Flags in the explorer are not displayed only if you open the directory through a symlink, if you can do something with it, it will be very good.
In the terminal, vscode is always the default directory because I added the line `cd ~` to **.bashrc** to start in the home directory. I feel so much more comfortable. There may be workarounds to change the default directory and so that in vscode when opening through code. opened the current path?

**Comment by aeschli** [comment]
Assigning to @joaomoreno to investigate the git issue.
@Mystic8b Please file a separate feature request to allow configuring the initial working directory.

**Comment by joaomoreno** [comment]
#5970
