### ISSUE TITLE
Debug hover goes to the wrong place

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#96134]
I keep seeing this, but I don't have specific repro steps, it just happens a lot from time to time recently. Have you seen this? I can try to debug or narrow it down if you haven't.

![Apr-25-2020 08-08-11](https://user-images.githubusercontent.com/323878/80280802-1448ff00-86cc-11ea-9dbd-192447d6fec4.gif)

I don't think there is anything about this specific code, I've seen it in lots of cases.

**Comment by isidorn** [comment]
I also see this from time to time. Assigning to May to look deeper since I think we always behaved like this, though we should improve.

**Comment by roblourens** [comment]
It's definitely worse this month than in the past. Happens fairly often for me, but seems random.

**Comment by isidorn** [comment]
Ok, let me assign to april, I might have time to look into it tomorrow

**Comment by isidorn** [comment]
@roblourens please try it out now. Thanks a lot!

**Comment by roblourens** [comment]
Seems fixed now, thanks!

**Comment by isidorn** [comment]
Great, thanks for trying it out and letting me know!
