### ISSUE TITLE
Path doesn't get added automatically during setup

### ISSUE THREAD

**Issue by ishandeveloper** [microsoft/vscode#96141]
- VSCode Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

![image](https://user-images.githubusercontent.com/54989142/80286049-b6a5c880-8746-11ea-9f11-7bf6cf95c252.png)

Steps to Reproduce:

1. Download and install using 64-bit Windows User Installer
2. Run <code>code</code> in the Powershell window.

<details>
<summary>error logs</summary>
<pre>
code : The term 'code' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
 +code
 +~~~~
    + CategoryInfo          : ObjectNotFound: (code:String) [], CommandNotFoundException
   + FullyQualifiedErrorId : CommandNotFoundException
</pre>
</details>

I know it's a simple issue and can be resolved just by adding the VSCode installation path to the environment variables. 

But, it should happen automatically during installation, right?

**Comment by joaomoreno** [comment]
Show me your PATH: `echo $env:PATH`.
