### ISSUE TITLE
Passing args launch.json vs launch.vs.json

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode#96145]
When passing arguments in VS2019 in `launch.vs.json` like that:
```
"args": [
                "--show-system-console",
                "--renderer: OpenGL[Debug]",
                "--resolution: 640x480",
],
```
the C++ program receives in `main(argc, argv) ` - 6 parameters.

If the same is passed in `launch.json` in Visual Studio Code (Linux)

receives in `main(argc, argv)` - 4 parameters. Why is that discrepancy?
I don't see this behavior documented here:
https://code.visualstudio.com/docs/cpp/launch-json-reference

**Comment by weinand** [comment]
Please file issue against the C++ extension
