### ISSUE TITLE
Submodules without .gitmodules

### ISSUE THREAD

**Issue by sveinse** [microsoft/vscode#96143]
As a developer I'd like to be able to define recursive git repos without using `.gitmodules`. It is very nice that VSCode is able to pick up on recursive git repositories using `.gitmodules` and for git projects that use gitmodules, the functionality is as expected.

However, some project only use submodules for grouping multiple repos in VSCode, and not as commited git submodules. Having to use `.gitmodules` as an mechanism for setting up sub repositories in VSCode is not optimal. It requires to use the file `.gitmodules` which leaves the repo "dirty" and you'll have to live with this extra file which is an annoyance.

I would like to propose either

* a) having a workspace setting that lists the subrepos for the project, or
* b) the ability to configure an alternative filename to read the subrepo config from, with default value  `.gitignore` as current implementation.

With the latter b) proposal, it would be possible to specify e.g. `.mysubrepo` as the subrepo config file and have this ignored by git. Adding ignore on `.gitmodules` is not a viable solution.

**Comment by joaomoreno** [comment]
> a) having a workspace setting that lists the subrepos for the project, or

It exists: `git.scanRepositories`.

**Comment by sveinse** [comment]
Ok, thanks. I tested adding my list of (sub)repos to `git.scanRepositories` in my workspace settings to `"git.scanRepositories": [ ".", "${workspaceFolder}", "repo1", "repo2", "${workspaceFolder}/repo1", "${workspaceFolder}/repo2" ], but none of these produced any results. The source control view only contains the top-level repo. I'll write a new bug report on it.
