### ISSUE TITLE
Ballistic scrolling on virtual widgets doesn't work when using touch

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9614]
Affected widgets:
- Editor
- Tree
- List

Steps:
- Using a touch device, scroll away a long list of elements.
- The scrolling will come to a complete stop once the element in which the touch event started goes out of the DOM.
- This is fixed when using the scroll wheel, we should implement the same when using touch.

**Comment by alexandrudima** [comment]
@joaomoreno Is this a regression? Do you mean touch as in a touch-screen on Windows?

**Comment by joaomoreno** [comment]
Don't think it is a regression... I believe we fixed it for ballistically scrolling when started from a `mousewheel` event... but not a `touchstart` one.

**Comment by joaomoreno** [comment]
Fixed.
