### ISSUE TITLE
Shell command in back quotes with <<

### ISSUE THREAD

**Issue by psycho-coder** [microsoft/vscode#96144]
Issue Type: <b>Bug</b>

Highlight be broken if script has back quotes with <<.
Example:
1. Create file test.sh
2. Open test.sh and paste example below

CHANGELOG=`cat << EOF
nginx ($VER-2~$REL) $REL; urgency=low

  * $VER

 -- $CONTRIB_NAME <$CONTRIB_EMAIL>  $DATE
EOF`

3. Write code below CHANGELOG.

[Gist with example](https://gist.github.com/psycho-coder/e0e5aa52c4166ee209c66a9e2965fdd2)
All code below back quotes will be highlighted as 'shell code'.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexr00** [comment]
Moved to owning repo: https://github.com/atom/language-shellscript/issues/158

**Comment by alexr00** [comment]
Closing in favor up the upstream issue.
