### ISSUE TITLE
macos vscode extremely slow. Freezing computer

### ISSUE THREAD

**Issue by mattstrayer** [microsoft/vscode#96140]
Issue Type: <b>Performance Issue</b>

Python /django project, 

.venv in root directory 

On save it hangs, on any operation it hangs. 

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (2.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   15	    98	 12921	code main
   10	    98	 12923	   gpu-process
    0	    33	 12937	   utility
   20	   131	 13163	   shared-process
    0	     0	 13845	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
   11	   295	 13550	   window (rate.py — tax)
    1	   131	 13559	     extensionHost
   27	    33	 13639	       /Users/matt/Sites/lowercase/tax/.venv/bin/python3 /Users/matt/.vscode/extensions/ms-python.python-2020.4.74986/pythonFiles/pyvsc-run-isolated.py /Users/matt/.vscode/extensions/ms-python.python-2020.4.74986/pythonFiles/completion.py
    0	    33	 13641	         /Users/matt/Sites/lowercase/tax/.venv/bin/python3 /Users/matt/.vscode/extensions/ms-python.python-2020.4.74986/pythonFiles/lib/python/jedi/inference/compiled/subprocess/__main__.py /Users/matt/.vscode/extensions/ms-python.python-2020.4.74986/pythonFiles/lib/python 3.8.2
    0	    33	 13560	     watcherService
    0	    33	 13565	     searchService
   38	    66	 13843	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (rate.py — tax)
|    Folder (tax): 10914 files
|      File types: py(2090) pyc(2089) mo(1198) po(1198) html(121) js(89)
|                  txt(72) svg(26) css(14) dat(13)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.35.0
prettier-vscode|esb|4.5.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.1.0
python|ms-|2020.4.74986
Go|ms-|0.14.1
vetur|oct|0.24.0
language-stylus|sys|1.11.0
vscode-icons|vsc|10.1.1
markdown-all-in-one|yzh|2.8.0

(4 theme extensions excluded)

</details>

**Comment by mattstrayer** [comment]
Opened settings and it hung. I ran `code --status` while that hung and the following report was generated.

Version:          Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS Version:       Darwin x64 19.4.0
CPUs:             Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)
Memory (System):  32.00GB (2.20GB free)
Load (avg):       1, 1, 1
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    9	   131	 12921	code main
    3	    98	 12923	   gpu-process
    0	    33	 12937	   utility
    1	   131	 13163	   shared-process
    0	     0	 13989	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    9	   295	 13550	   window (Settings — tax)
    0	   131	 13559	     extensionHost
    0	    33	 13891	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=13559
    0	    33	 13901	       /Users/matt/Sites/lowercase/tax/.venv/bin/python /Users/matt/.vscode/extensions/ms-python.python-2020.4.74986/pythonFiles/pyvsc-run-isolated.py /Users/matt/.vscode/extensions/ms-python.python-2020.4.74986/pythonFiles/completion.py
    0	    33	 13903	         /Users/matt/Sites/lowercase/tax/.venv/bin/python /Users/matt/.vscode/extensions/ms-python.python-2020.4.74986/pythonFiles/lib/python/jedi/inference/compiled/subprocess/__main__.py /Users/matt/.vscode/extensions/ms-python.python-2020.4.74986/pythonFiles/lib/python 3.8.2
    0	    33	 13560	     watcherService
    0	    33	 13565	     searchService

Workspace Stats:
|  Window (Settings — tax)
|    Folder (tax): 10914 files
|      File types: py(2090) pyc(2089) po(1198) mo(1198) html(121) js(89)
|                  txt(72) svg(26) css(14) dat(13)
|      Conf files: settings.json(1)

**Comment by deepak1556** [comment]
Is this still an issue with latest insiders https://code.visualstudio.com/insiders ?

**Comment by mattstrayer** [comment]
@deepak1556 I haven't run into this for a while. Going to close
