### ISSUE TITLE
C/C++ include <header_with_underscore> not found

### ISSUE THREAD

**Issue by m-j-w** [Microsoft/vscode#9615]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

1. install the C/C++ extension
2. set the include path correctly to the system headers' directory in c_cpp_properties.json
3. Create a new C++ file that includes e.g. `<array>` and `<type_traits>`
4. Observe that `<array>` is found, but `<type_traits>` not, although both being in the same directory.

![image1](https://cloud.githubusercontent.com/assets/14040010/17051916/6a5f16e2-4ffb-11e6-81a5-a60edd41ff9c.png)

Tested on Windows with Cygwin, Mingw64 and MSVC header directories. Same behaviour for all of them. Restarting VS Code doesn't solve the problem.

**Comment by kieferrm** [comment]
Pls refile the issue in the C++'s repo: https://github.com/Microsoft/vscppsamples/issues. Thanks a ton.
