### ISSUE TITLE
Settings UI "add item" button is too wide

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#96159]
Dunno where this came from

![image](https://user-images.githubusercontent.com/323878/80294273-7b4ad000-872d-11ea-928a-ce4b07289e11.png)

**Comment by Diuda** [comment]
Hey @roblourens, is this already being worked upon? If not, I'd like to fix this. Seems like a trivial issue for contributing for the first time.

**Comment by roblourens** [comment]
Sorry @Diuda, I didn't see your update this morning. You were right :)
