### ISSUE TITLE
Shell tasks are delayed 500 ms when using ConPTY

### ISSUE THREAD

**Issue by jcedwards** [microsoft/vscode#96158]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Create a new shell task that just echos something to the terminal.
2. Try running the task with terminal.integrated.windowsEnableConpty set to true and then false. There should be a 0.5 second delay before the echo'd text appears when windowsEnableConpty is set to true.

Digging into this further, looks like the terminal waits until the timeout on line 140 of terminalProcess.ts fires before executing the script. Increasing the wait time on line 142 proportionately increases how long it takes for a task to start running. There's a comment that suggests the body of the timeout can be called synchronously, which appears to work for me, but I have not tested it rigorously. Currently setting windowsEnableConpty to false, but would like to be able to move to ConPTY, since it's the future.

VS Code version: Code - Insiders 1.45.0-insider (a250df703de955a38aed427a917bce8278ab3331, 2020-04-24T10:02:48.114Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/blob/84ac04e8155d473868f5301eb979ed0dd527e116/src/vs/workbench/contrib/terminal/node/terminalProcess.ts#L139-L142

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/91905
