### ISSUE TITLE
Auth problems with GH Auth provider

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#96157]
I created a PR with the GH PR extension from a public branch in this repo. I get the following auth error:

![image](https://user-images.githubusercontent.com/4674940/80293077-0f5a6e80-8711-11ea-9227-009de002d7ed.png)

Need to make sure that when changing the OAuth app we are back in a working state.

**Comment by RMacfarlane** [comment]
Should be fixed with https://github.com/microsoft/vscode/commit/b05b32bfd86de0ead6456e4b0cc4339cf124e3e2
