### ISSUE TITLE
Update VSCode insiders fails as keep asking to install update

### ISSUE THREAD

**Issue by talr1** [microsoft/vscode#96169]
Trying to update VSCode insiders, but setup seems to fail and keeps asking to restart vscode to update, but version remain as is.

Version: 1.45.0-insider (user setup)
Commit: d342048538c28d54afd1c6beea03f3a89af04359
Date: 2020-04-23T05:57:41.076Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. just clicking "restart to update"

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by talr1** [comment]
the issue is not related to sync settings notification. there is an actual update to be installed which fails

**Comment by talr1** [comment]
i found in the %temp% folder the file vscode-inno-updater-1587969158.log:

Apr 27 09:32:38.973 INFO Starting: C:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe, false
Apr 27 09:32:38.974 INFO Checking for running Code - Insiders.exe processes... (attempt 1)
Apr 27 09:32:38.994 INFO Code - Insiders.exe is running, wait a bit
Apr 27 09:32:39.494 INFO Checking for running Code - Insiders.exe processes... (attempt 2)
Apr 27 09:32:39.508 INFO Code - Insiders.exe is running, wait a bit

....

Apr 27 09:33:08.816 INFO Checking for running Code - Insiders.exe processes... (attempt 59)
Apr 27 09:33:08.830 INFO Code - Insiders.exe is running, wait a bit
Apr 27 09:33:09.331 INFO Checking for running Code - Insiders.exe processes... (attempt 60)
Apr 27 09:33:09.348 INFO Gave up waiting for Code - Insiders.exe to exit
Apr 27 09:33:09.348 INFO Checking for possible conflicting running processes... (attempt 1)
Apr 27 09:33:09.362 INFO Kill process if found: 43928, Code - Insiders.exe
Apr 27 09:33:09.362 INFO Found Code - Insiders.exe running, pid 43928, attempting to kill...
Apr 27 09:33:09.362 WARN Kill error Failed to kill process

process 43928 is a suspended process of vscode insiders which can't be killed

Code - Insiders.exe	43928	Suspended	user	00 	16 K	"C:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" --type=utility --field-trial-handle=1412,15749705139751901036,14175070510773858324,131072 --disable-features=LayoutNG,PictureInPicture,SpareRendererForSitePerProcess --lang=en-US --service-sandbox-type=utility --service-request-channel-token=1863200307481062260 --mojo-platform-channel-handle=3108 --ignored=" --type=renderer " /prefetch:8	Disabled

in one at temp to kill this process while vscode was opened i saw a message notification that the extension host process had an issue (don't remember the exact phrase).

maybe there is an issue that a certain extension is holding the vscode process alive and prevent the upgrade?

how can i find the culprit extension with uninstalling all of them?

**Comment by joaomoreno** [comment]
Can you completely uninstall VS Code, reinstall it and ses if the problem keeps happening?

**Comment by talr1** [comment]
i can try, but i wanted to avoid it so i won't lose any debug/install logs which might help solve the problem.

**Comment by talr1** [comment]
uninstalling vscode insiders did not help as not all files got removed.
besides the data folder with all the extensions, the vscode executable got left behind and could not be removed and it is actually the suspended process that could not be killed.

only a restart to the machine allowed to deleted the file and install a fresh vscode insiders version.

i can try again to install the coming few updates to see if issue persists.
but i assume there should be some way to detect or log a faulty process/extension that might cause such issues in the future.

**Comment by joaomoreno** [comment]
OK Let me know. You can also disable Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.
