### ISSUE TITLE
【Abort trap: 6】crashed  on macOS , cv2.VideoCapture(0) 

### ISSUE THREAD

**Issue by 12343954** [microsoft/vscode#96167]
![image](https://user-images.githubusercontent.com/1804003/80300171-e8fa0900-87cc-11ea-8ef6-1cb17bb33e76.png)

VScode version: 1.44.2
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.6.0

**Comment by deepak1556** [comment]
Thanks for the report, merging to https://github.com/microsoft/vscode/issues/95062
