### ISSUE TITLE
There is a situatioin nodejs code has no code-auto-completion

### ISSUE THREAD

**Issue by tap6** [microsoft/vscode#96160]
![123](https://user-images.githubusercontent.com/23492851/80294602-2d6db080-879d-11ea-996a-49d90923539c.png)

Issue Type: <b>Feature Request</b>

I common the no Code auto-complete position.
I'm not sure if the question is mine or VS,if you can figure out why this happend i would be appreciated.
Thanks~~~

Nodejs - Serv.js
===========
```js
const net = require( 'net' );
const port = 8000;
const hostname = '127.0.0.1';

// Define two variables, one for counting and one for saving the client
let clients = {};
let clientName = 0;

// createServer
const server = new net.createServer((c)=>{
  c.write('123')
});

server.on('connection', (client) => {
  
  client.name = ++clientName; // give every client a name
  clients[client.name] = client; // save client to clients
  console.log(client);
  
  //client.     //The Socket cannot be recognized as a Socket and cannot be automatically completed
  //client.write('hello everybody~~');  //Handwriting,code works

  // for (i in clients){
  //   clients[i].                   //no automatically completed either
  // }

  client.on('data', function (msg) { //Receive messages from customers
    console.log(`client${client.name}Send a message:${msg}`);
  });

  client.on('error', function (e) { //Listen for client exceptions
    console.log('client error' + e);
    client.end();
  });

  client.on( 'close', function () {
    delete clients[client.name];
    
    console.log(`Client${ client.name }is offline`);
  });

});

server.listen( port,hostname,function () {
  console.log(`Serv runs on：http://${hostname}:${port}`);
});
```

Nodejs - Client.js
===========
```js
const net = require('net');

const socket = new net.Socket();

const port = 8000;

const hostname = '127.0.0.1';

socket.setEncoding = 'UTF-8';

socket.connect( port,hostname,function(){
  socket.write('hello AVBody~~');
});

socket.on( 'data', function ( msg ) {
  console.log( msg.toString() );
});

socket.on( 'error', function ( error ) {
  console.log( 'error' + error );
});

socket.on('close',function(){
  console.log('Serv is not alive');
});
```
------------------

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

**Comment by dbaeumer** [comment]
This has nothing to do with LSP. Looks like a general TS question to me.

**Comment by mjbvz** [comment]
This code is incorrect; you are calling `new net.createServer(...)` but `createServer` is not a constructor so `new` should not be used here. After fixing this, I see suggestions working as expected

VS Code will report this problem if you enable [type checking in JS files](https://code.visualstudio.com/Docs/languages/javascript#_type-checking)

**Comment by tap6** [comment]
> This code is incorrect; you are calling `new net.createServer(...)` but `createServer` is not a constructor so `new` should not be used here. After fixing this, I see suggestions working as expected
> 
> VS Code will report this problem if you enable [type checking in JS files](https://code.visualstudio.com/Docs/languages/javascript#_type-checking)

How stupid i am...
I'm so sorry to bring you extra workload

**Comment by tap6** [comment]
> This code is incorrect; you are calling `new net.createServer(...)` but `createServer` is not a constructor so `new` should not be used here. After fixing this, I see suggestions working as expected
> 
> VS Code will report this problem if you enable [type checking in JS files](https://code.visualstudio.com/Docs/languages/javascript#_type-checking)

and Thanks for your guiding, bro
