### ISSUE TITLE
Add ability to rename current open file from command palette

### ISSUE THREAD

**Issue by nikitavoloboev** [microsoft/vscode#96162]
There seems to be no way I can trigger to rename current file from command palette. Perhaps I miss something aside from downloading [another extension](https://marketplace.visualstudio.com/items?itemName=sleistner.vscode-fileutils) that would let you do it. And I don't want to download an extension just for one action of renaming my file.

**Comment by isidorn** [comment]
Thsi is currently not possible. And yeah download an extension for now.
Though I can leave this open as we might tackle in the future.
