### ISSUE TITLE
vscode opens files from comman line in separate instances

### ISSUE THREAD

**Issue by EugenWiens** [Microsoft/vscode#9616]
- VSCode Version: 1.3.1
- OS Version: 
Distributor ID:	Ubuntu
Description:	Ubuntu 14.10
Release:	14.10
Codename:	utopic

If I start vscode multiple times from the command line with file as parameter it opens for every file a new instance.
Is it possible that vscode opens the files from command line in the same instance. So that I get the behavior of geany (editor on ubuntu).

Regards,

Eugen Wiens

**Comment by kieferrm** [comment]
Duplicate of #9479.
