### ISSUE TITLE
[Feature Request - Extensions] Show actual date (most recent, prior history) of updates to extensions

### ISSUE THREAD

**Issue by MostHated** [microsoft/vscode#96165]
Hello,
   It would be extremely helpful to be able to see more details about extensions. The biggest one would be seeing a date list of when the extension was updated. At the very least, the date of when the most recent update occurred. Sometimes there will be a few different similar extensions or some that look really useful, so you download it, only to find out it's not compatible anymore and you look at the github and it has not been updated in months. It would be great if you could see the dated date right along the top of the extension page along with the other details (near the number of downloads and rating stars, etc).

Thanks,
-MH

**Comment by sandy081** [comment]
/duplicate 

https://github.com/microsoft/vscode/issues/70736
