### ISSUE TITLE
[git] The native implementation of git seems to be unable to handle git ssh keys with password

### ISSUE THREAD

**Issue by zero-24** [microsoft/vscode#96178]
- VSCode Version: 1.44.2
- OS Version: Win 10

## System info
- Version: 1.44.2 (user setup)
- Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
- Datum: 2020-04-16T16:33:57.013Z
- Electron: 7.1.11
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- Betriebssystem: Windows_NT ia32 10.0.18362

Steps to Reproduce:

1. Setup a git repo with ssh auth
2. that ssh key has to require a PW
3. try to upload the commits from VScode

## error message

![image](https://user-images.githubusercontent.com/2596554/80304261-120e9f80-87b5-11ea-82b9-b030ba104abe.png)

Git log
![image](https://user-images.githubusercontent.com/2596554/80304301-35394f00-87b5-11ea-97d6-1f8ada1e3aae.png)

Does this issue occur when all extensions are disabled?: Yes/No

Yes as it is the native implementation of git not supporting it right now?

**Comment by joaomoreno** [comment]
#13680
