### ISSUE TITLE
[ts] Coloring in .ts file fails if generic class variable is defined

### ISSUE THREAD

**Issue by olivermue** [Microsoft/vscode#9617]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Create a simple class that contains a class variable of a generic type:
```typescript
export class MyClassContainingGenericMember {
    private _thisColorsAlwaysCorrectly: string;
    private _mappings: Map<number, { key: string, value: string }>;
    private _thisColorsWrong: { [k: string]: { key: string, value: string } };

    public thisColorsAlsoWrong() {
        this.andThisIsAlsoPlainWhite();
    }

    private andThisIsAlsoPlainWhite() {
        console.log("Hello");
    }
}
```
2. Open that file in Visual Studio Code.
3. Comment out the line `private _mappings ...` by prefixing with `//` (press <kbd>Ctrl</kbd>+<kbd>K</kbd>+<kbd>C</kbd>).
4. Watch how the colors of the keywords `public` and `private` and the method names are changing.

**Comment by aeschli** [comment]
this seems fixed with with the latest grammar update.
