### ISSUE TITLE
Not opening firefox when link clicked.

### ISSUE THREAD

**Issue by OskarZyg** [microsoft/vscode#96177]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Go to Ubuntu 19.10 with default installation of firefox
2. Click on any link and open it.
3. Clicking on the error message crashes it.

Image:
![Screenshot from 2020-04-26 10-52-14](https://user-images.githubusercontent.com/56176746/80304109-0a96c880-87ac-11ea-908d-fb599c1b0f9e.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@joaomoreno can you test this? I vaguely remember you using ubuntu primarily

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/85344
