### ISSUE TITLE
Typescript failing multiple times

### ISSUE THREAD

**Issue by SiddhantBohra** [microsoft/vscode#96179]
Issue Type: <b>Bug</b>

Typescript service failing multiple times

VS Code version: Code - OSS 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-16T21:41:21.848Z)
OS version: Linux x64 5.4.34-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz (4 x 3700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.66GB (2.71GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
prettier-vscode|esb|4.5.0
vscode-docker|ms-|1.1.0
vscode-kubernetes-tools|ms-|1.2.0
python|ms-|2020.4.74986
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2048
material-icon-theme|PKi|4.0.1
vscode-yaml|red|0.7.2
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.6

</details>

**Comment by mjbvz** [comment]
When TS fails, click the `report issue` notification. This should include the call stack of the crash. Please include that
