### ISSUE TITLE
The default profile in configuration file does not take effect

### ISSUE THREAD

**Issue by wbpluto** [microsoft/vscode#96185]
Terminal is installed from the store. PowerShell 7.1 Preview 2 is installed through MSIX and is the default configuration file.
But every time you open Terminal, Windows PowerShell is opened by default.

V: 1.44.2 (system setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19613

Steps to Reproduce:

1.
2.

![image](https://user-images.githubusercontent.com/5191513/80306570-b402ac00-87f6-11ea-87dd-1627a0c3431c.png)

**Comment by sbatten** [comment]
VS Code has its own terminal setting. please run the command: Ctrl+Shift+P => `Select Default Shell`

**Comment by Tyriar** [comment]
If you're talking about ctrl+shift+c to launch WT (via the `"terminal.external.windowsExec": "wt"` setting), then we just say to WT to open a terminal on a particular directory. If you don't want Windows PowerShell then this sounds like a but in WT -> https://github.com/microsoft/terminal

Code to launch for reference:  https://github.com/microsoft/vscode/blob/ece3baa11ed5ded6a39c132e44ed2a4ee787cbd1/src/vs/workbench/contrib/externalTerminal/node/externalTerminalService.ts#L76-L111
