### ISSUE TITLE
Focus terminal after dragging a folder from explorer to terminal

### ISSUE THREAD

**Issue by Bharatwasi** [microsoft/vscode#96181]
<b> Current Installed VS Code Details</b>

`Version: 1.44.2 (user setup)`
`Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd`
`Date: 2020-04-16T16:36:23.138Z`
`Electron: 7.1.11`
`Chrome: 78.0.3904.130`
`Node.js: 12.8.1`
`V8: 7.8.279.23-electron.0`
`OS: Windows_NT x64 10.0.17763`

<b>Steps to Reproduce</b>

1. Open VS code 
2. Open a Folder having nested folders in it
3. Open the Powershell terminal
4. Now Type "cd" and drag a folder to change the current directory 
5. Now see the cursor is not in the PowerShell window and if  you hit enter command would not execute

<b>Expected Behavior</b>

 After dragging a folder to PowerShell terminal cursor should be in the PowerShell terminal 

<b>Other Configuration</b>

Does this issue occur when all extensions are disabled?: <b>Yes</b>

<b> Screenshot </b>

![image](https://user-images.githubusercontent.com/10395693/80304597-ae946a00-87d4-11ea-9d58-a3ff2f1bcef7.png)

<b> Submitted By : </b>amityadav.java@gmail.com

**Comment by ChrisPapp** [comment]
@Tyriar Can I take this?

**Comment by Tyriar** [comment]
@ChrisPapp sounds good, thanks 😃

**Comment by Bharatwasi** [comment]
Thanks, everyone!!
