### ISSUE TITLE
VSC stagnate repeteadly

### ISSUE THREAD

**Issue by bendaoud7** [microsoft/vscode#96183]
Hello team,

VSC stagnate repeteadly since last update. After its lunch, it start stagnate several times and recover its operations normally after few seconds.

Best regards,

**Comment by deepak1556** [comment]
can you please fill out the issue template







- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.


Does this issue occur when all extensions are disabled (--disable-extensions) ?:
