### ISSUE TITLE
正在初始化JS/TS语言功能，导致vscode卡死

### ISSUE THREAD

**Issue by tomatobybike** [microsoft/vscode#96187]
正在初始化JS/TS语言功能，导致vscode卡死

**Comment by gpake** [comment]
Translation:
VSCode got stucked when initializing JavaScript / TypeScript language function.

**Comment by mjbvz** [comment]
We'll try to translate issues but this doesn't even follow our the issue template so it's not actionable 

See https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by jackchoumine** [comment]
> Translation:
> VSCode got stucked/freezed when initializing JavaScript / TypeScript language function.

how to disabled init js langauge?
