### ISSUE TITLE
Error when invoking `explorer.newFile` while explorer viewlet is collapsed

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#96196]
- VSCode Version: From sources

Steps to Reproduce:

1. Open a folder in vscode
2. Collapse explorer viewlet
3. Invoke `explorer.newFile` or `explorer.newFolder` command
4. Error `Command 'File: New Folder' resulted in an error (TreeError [FileExplorer] Data tree node not found: [object Object])` shows in notifications

**Comment by isidorn** [comment]
@jeanp413 good catch, thanks for reporting this.
I believe this was like that since we shipped stable and our changes to the view / viewlet infrastucture.
Issue was that open viewlet does not exapnd the explorer view which makes sense since a viewlet is a superset.
