### ISSUE TITLE
Experimental support for decorators is a feature that is subject to change in a future release

### ISSUE THREAD

**Issue by MilenkoM** [microsoft/vscode#96193]
- VSCode Version:
1.44.2
ff915844119ce9485abfe8aa9076ec76b5300ddd
x64
- OS Version:
Ubuntu 18.04
Steps to Reproduce:
My code:
```
function logConstructor(inConstructor: Function) {
  console.log(inConstructor);
}

@logConstructor
class Spaceship {
  constructor() { console.log("constructor"); }
```
}

const s = new Spaceship();
1. tsc myscode.ts
2. Output
TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning.

My tsconfig:
  "compilerOptions": {
    "allowJs": true,  
    "experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
    "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */
    /* Basic Options */
    // "incremental": true,                   /* Enable incremental compilation */
    "target": "ES2017",                       
    "module": "commonjs", 
"strict": true,

Does this issue occur when all extensions are disabled?: Yes

**Comment by MilenkoM** [comment]
I checked javascript.implicitProjectConfig.experimentalDecorators,again the same issue.

**Comment by yume-chan** [comment]
`tsc yourfile.ts` won't use your tsconfig.json or any other configurations.

Read the [documentation](https://www.typescriptlang.org/docs/handbook/compiler-options.html).

Use `tsc` or `tsc -p yourconfig.json` or `tsc -p yourconfig.json yourfile.ts` instead.
