### ISSUE TITLE
Code - OSS cannot run globally installed packages when running tasks on Arch Linux

### ISSUE THREAD

**Issue by nmggithub** [microsoft/vscode#96197]
- VSCode Version: 1.44.2
- OS Version: Arch Linux (rolling)

Steps to Reproduce:
1. Install `npm` and `nodejs`
2. Create a `~/.profile` file containing
`PATH="$HOME/.node_modules/bin:$PATH"
export npm_config_prefix=~/.node_modules`
3. Run `npm install -g firebase-tools`
4. Login and start developing a project
5. Use the command palette to run the `serve` task, which includes a firebase command

Expected: The build runs and then the firebase command runs
Actually: The build runs and then it log shows the error `sh: firebase: command not found`

This does not happen when running `npm run serve` in the terminal environment. Is there something different about the tasks environment?

Does this issue occur when all extensions are disabled?: No

**Comment by nmggithub** [comment]
Ok, this is odd. It does not occur with extensions disabled but the only extension I have installed is an icon theme.

**Comment by alexr00** [comment]
Tasks does not use your .profile. Instead, it uses the environment of VS Code. Can you open the developer tools console and run `process.env`? Does your path there include the items you want?

**Comment by nmggithub** [comment]
This also did not work even when I put the things into `~/.bashrc` it appears Tasks sets the node prefix itself when running. I "solved" my issue, by running `sudo npm install -g firebase-tools`. Tasks now knows where to find it, but I don't think that it changing the node prefix would be helpful in all circumstances.
