### ISSUE TITLE
Explorer remains faded after clicking on Collapse Folders action while editing new file/folder

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#96198]
- VSCode Version: From sources

Steps to Reproduce:

1. Open folder in vscode
2. Open explorer, select a folder  and click on `New File`/`New folder` action
3. Click on `Collapse Folders in Explorer` Action
4. :bug: Explorer remains faded

**Comment by isidorn** [comment]
Deja vu!
Great catch, had to remove the code you added to prevent this from happening due to my refactoring.
Now just changed the collapse to make sure to remove the edited element.
