### ISSUE TITLE
Can't build in Windows 10

### ISSUE THREAD

**Issue by Umriyaev** [Microsoft/vscode#962]
I followed instructions from https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source , but the build is unsuccessful. 
I'm using node v5.1.0, Visual Studio 2015 Community (I installed C++ build tools), MSBuild v14.0.24720.0
npm-debug.log file gives following error: 
```
21173 verbose stack Error: oniguruma@5.1.1 install: `node-gyp rebuild`
21173 verbose stack Exit status 1
21173 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
21173 verbose stack     at emitTwo (events.js:87:13)
21173 verbose stack     at EventEmitter.emit (events.js:172:7)
21173 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
21173 verbose stack     at emitTwo (events.js:87:13)
21173 verbose stack     at ChildProcess.emit (events.js:172:7)
21173 verbose stack     at maybeClose (internal/child_process.js:818:16)
21173 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
21174 verbose pkgid oniguruma@5.1.1
21175 verbose cwd E:\Github\vscode
21176 error Windows_NT 10.0.10586
21177 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
21178 error node v5.1.0
21179 error npm  v3.3.12
21180 error code ELIFECYCLE
21181 error oniguruma@5.1.1 install: `node-gyp rebuild`
21181 error Exit status 1
21182 error Failed at the oniguruma@5.1.1 install script 'node-gyp rebuild'.
21182 error Make sure you have the latest version of node.js and npm installed.
21182 error If you do, this is most likely a problem with the oniguruma package,
21182 error not with npm itself.
21182 error Tell the author that this fails on your system:
21182 error     node-gyp rebuild
21182 error You can get their info via:
21182 error     npm owner ls oniguruma
21182 error There is likely additional logging output above.
21183 verbose exit [ 1, true ]
```
Git shell is giving following error:
```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): 
error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. 
To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to
 the current Visual Studio tools by selecting the Project menu or right-click the solution, and then 
selecting "Upgrade Solution...". 
[E:\Github\vscode\node_modules\vscode-textmate\node_modules\oniguruma\build\oniguruma.vcxproj]
```
However, as I mentioned earlier, my MSBuild version is 14.0.24720.0
I tried following workarounds from * User/Repository#Num: nodejs/node-gyp#679 :
 - set environment variable GYP_MSVS_VERSION = 2015
 - tried to run ```scripts\npm install --msvs_version=2015
 - update Visual Studio
But still without success.

Steps to reproduce the bug:
- install Visual Studio Community 2015
- install node.js v5.1.0
- clone repository using command ```git clone https://github.com/microsoft/vscode
- go to repository ```cd vscode```
- install mocha gulp ```npm install -g mocha gulp
- run install script ```scripts\npm install```

**Comment by alexandrudima** [comment]
@Umriyaev not sure how to fix the specific node-gyp issue you run into.

But here is a hackish workaround. It involves "manually installing" `vscode-textmate@1.0.8` in the node_modules such that npm does not need to install it:
 * download [VSCode for windows as a zip](http://go.microsoft.com/fwlink/?LinkID=615207)
 * extract the zip and take `resources\app\node_modules\vscode-textmate` and copy it to where you have checked out vscode in `$\node_modules\vscode-textmate`
 * the vscode-textmate version in that zip is 1.0.6 and we now use 1.0.8 on master, so npm install will still try to install it, therefore:
 * download [vscode-textmate@1.0.8](https://registry.npmjs.org/vscode-textmate/-/vscode-textmate-1.0.8.tgz)
 * extract the tgz on top of `$\node_modules\vscode-textmate`

Run `scripts\npm install` again. This time, since `npm` finds vscode-textmate@1.0.8 it won't try to install it, therefore it won't utilise `node-gyp` and will continue with the other node modules (that don't require `node-gyp`).

**Comment by joaomoreno** [comment]
Can you try installing Visual Studio 2013 instead of 2015?

**Comment by DickvdBrink** [comment]
I did manage this on a Windows 10 pc, with only VS2015. If I recall correctly I installed alot of packages with `npm install <name> --no-bin-links` manually because of some very weird errors. Will try to check it out again tonight

**Comment by Umriyaev** [comment]
@alexandrudima Thank you so much! Your workaround worked for me.
I guess it should be added to [How to build and run from source](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source) .
Of course after finding more generic solution.

**Comment by joaomoreno** [comment]
It's definitely just a workaround, let's try to find why you couldn't compile. I'll set up a VM tomorrow with exactly your setup and see what I get.

**Comment by joaomoreno** [comment]
Just set up a brand new Windows 10 VM. Installed **VS Community 2015**, **node 5.1.0** and **Python 2.7**. Got some errors at first, but realised I did not install the C++ tooling. Went to **Control Panel**, hit **Modify** in the Visual Studio item and added the **Visual C++** tooling.

![image](https://cloud.githubusercontent.com/assets/22350/11742193/26cb85e4-9ffe-11e5-9dc0-502a601e5212.png)

I successfully ran `.\scripts\npm.bat install` afterwards.

Not sure what is wrong with your system, but it's at best a Visual Studio and/or npm issue.

**Comment by joaomoreno** [comment]
You seem to be in a system that has had Visual Studio 2013 installed before, since you mention the following path:

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets
```

In my brand new VM, I only have the `V140` directory, not the `V120`:

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140
```

**Comment by Umriyaev** [comment]
I see.
Thank you for your help.

**Comment by joaomoreno** [comment]
In case you actually find a solution to your problem, can I ask you to post it here? Maybe it'll help others. :+1:

**Comment by Umriyaev** [comment]
Sure! Of course I will
