### ISSUE TITLE
Could not load markdown.styles

### ISSUE THREAD

**Issue by arnofly** [microsoft/vscode#96201]
- VSCode Version:
- OS Version:
Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

settings.json
{
    "markdown.styles": [
        "D:\\\markdown-override.css"
    ]
}

![image](https://user-images.githubusercontent.com/45882853/80316705-9ede4b00-87ff-11ea-98d9-8ad89fc66db7.png)
### Please, why?

I would like override CSS global styles of Markdown feature by default for all my MD files. Markdown PDF extension lets me do it, but my styles are applied on export only, not on preview.
Thx.

**Comment by mjbvz** [comment]
See https://code.visualstudio.com/Docs/languages/markdown#_using-your-own-css

This setting only supports loading a css file from your current workspace
