### ISSUE TITLE
Allow to open the same file in different tabs

### ISSUE THREAD

**Issue by genivaldosc** [microsoft/vscode#96212]
Allow to open the same file in different tabs. Today it is possible to use “Open to the side”, but on smaller monitors there is no space. The feature is practical for working with files with many lines and easy to switch between areas edited with Ctrl + Tab. In Netbeans I used the clone function.

Thanks

![image](https://user-images.githubusercontent.com/25187586/80323126-dc42d880-87ff-11ea-902c-6e3881e6e5bd.png)
![image](https://user-images.githubusercontent.com/25187586/80323149-f381c600-87ff-11ea-9aaf-614933a521cd.png)

**Comment by gjsjohnmurray** [comment]
#41289
