### ISSUE TITLE
VS Online git credentials are not working when connected from VS Code insiders

### ISSUE THREAD

**Issue by dbanisimov** [microsoft/vscode#96213]
Issue Type: <b>Bug</b>

When working with git on cloud-hosted Visual Studio Online environment the git credentials are not shared between Code Insiders and the remote environment. For every operation git asks for a username and a password. This happens both for Code GUI git and cmd git.
This started to happen recently and it doesn't happen when using vsonline via browser or via stable vscode.

VS Code version: Code - Insiders 1.45.0-insider (a250df703de955a38aed427a917bce8278ab3331, 2020-04-24T10:02:48.114Z)
OS version: Windows_NT x64 10.0.19536
Remote OS version: Linux x64 5.0.0-1036-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|VS Online: introwise-experts|
|OS|Linux x64 5.0.0-1036-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz (4 x 2693)|
|Memory (System)|7.77GB (3.70GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.7.2
dotenv|mik|1.0.1
remote-wsl|ms-|0.44.2
vsonline|ms-|1.0.2096
debugger-for-chrome|msj|4.12.6
vscode-eslint|dba|2.1.5
vscode-pull-request-github|Git|0.15.0
dotenv|mik|1.0.1
azure-account|ms-|0.8.9
vsliveshare|ms-|1.0.2048
vsonline|ms-|1.0.2096
vscodeintellicode|Vis|1.2.6

(2 theme extensions excluded)

</details>

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the VS Online extension. Please file a new issue for it: https://github.com/MicrosoftDocs/vsonline/issues
