### ISSUE TITLE
Source Control UI gets cramped when there are lots of project folders

### ISSUE THREAD

**Issue by jedwards1211** [microsoft/vscode#96215]
Here's my source control pane right now...  I'd rather it would just show a single project at once (with a dropdown at the top to switch between them, that syncs to the project containing the file in the active text editor)

Compounding the problem is the fact that removing a project folder from the workspace doesn't remove it from this list.  I only actually have 10 project folders in the workspace right now but there are over 20 source control providers in this accordion. (I think I've seen a separate issue for this)

![image](https://user-images.githubusercontent.com/1448194/80331221-11095c80-880d-11ea-90a8-adbfda2ac718.png)

**Comment by joaomoreno** [comment]
Can you expand the `Source Control Providers` view and simply click on the repository you want to have visible?

**Comment by jedwards1211** [comment]
oh thanks, nevermind, ever since collapsing it awhile ago I completely forgot about it
