### ISSUE TITLE
After restart VSCode looses context and hangs on welcome page 

### ISSUE THREAD

**Issue by PavelSosin-320** [microsoft/vscode#96217]
Issue Type: <b>Bug</b>

In addition to "Welcome page remains open after opening workspace"
1. Create a project
......
2. Restart VSCode
Actual:
-- Welcome page is shown instead of recent context:
    --  selected folder
    --  Opened editor
    --  Used development container
Expected:
   Take me back to my work context as all normal IDEs do.
Show Welcome page once per update i.e. "don't show me again"

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.19613

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (3.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-cudacpp|kri|0.1.1
vscode-docker|ms-|1.1.0
csharp|ms-|1.21.17
vscode-kubernetes-tools|ms-|1.2.0
remote-containers|ms-|0.112.0
remote-wsl|ms-|0.44.2
cpptools|ms-|0.27.0
vscode-yaml|red|0.7.2
msbuild-tools|ste|0.0.12
msbuild-project-tools|tin|0.3.5
vscode-ansible|vsc|0.5.2

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by sbatten** [comment]
Please see settings: `window.restoreWindows` and `workbench.startupEditor`
