### ISSUE TITLE
In a big project (a couple of files woth more than 10k lines and a lot of files with some hundreds of lines) editor slows down and uses a lot of cpu .

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#9621]
- VSCode Version:1.3.1
- OS Version:ubuntu 16.4 

Steps to Reproduce:

1. open a project containing files with a lot of lines (over 10k)
2. open a big file and write something then go to new line

after this the operation takes about 2 seconds and uses a lot of cpu makes computer slow too.

**Comment by kieferrm** [comment]
@NikosEfthias what kind of files do you open/edit. Do you have a sample workspace you could share? Any extensions you have installed for those file types? Do you see the same sluggishness when you start vscode with the `--disable-extensions` command line arg?

**Comment by NikosEfthias** [comment]
without extensions it is okay but in that case autocomplete wont work altough typings are installed

**Comment by NikosEfthias** [comment]
without extensions seem okay how can i see which extension is causing this?

**Comment by kieferrm** [comment]
No easy way to my knowledge at this point. Start without any extension and then add one at a time every time testing if it starts slowing down. Sorry that there is nothing simpler right now.

**Comment by NikosEfthias** [comment]
Is there a way to disable extensions rather then uninstalling
