### ISSUE TITLE
Test config based recommendations

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#96228]
- [x] anyOS @deepak1556
- [x] anyOS @fiveisprime

Complexity: 2

---

- Open a folder that is a git repo
- Open Extensions View and make sure `Gitlens` extension is shown in recommendations
- Open a folder that is a git repo with Github remote
- Open Extensions View and make sure `GitHub Pull Request` extension is shown in recommendations

**Comment by deepak1556** [comment]
Verified on macOS

**Comment by fiveisprime** [comment]
Working on Windows

![image](https://user-images.githubusercontent.com/1186948/80514613-9851ef80-8935-11ea-9050-7be8e46a5a2b.png)


Does **not** work on WSL 

![image](https://user-images.githubusercontent.com/1186948/80514666-ab64bf80-8935-11ea-8a78-9a9a12437ad8.png)

**Comment by sandy081** [comment]
Please file an issue for WSL case.
