### ISSUE TITLE
Provide API docs and/or .d.ts for the webview scripts

### ISSUE THREAD

**Issue by iliazeus** [microsoft/vscode#96221]
It would be nice to have a reference of the api available through `acquireVsCodeApi()`. Right now, one needs to sift through the guide on webview extensions. And, ideally, I'd love to have a `.d.ts` declaration file.

**Comment by namaggarwal** [comment]
@mjbvz I would like to take this up. Any good place to start ?

**Comment by mjbvz** [comment]
Once you put together a d.ts file for the types, they should likely be published to [Definitely Typed](http://definitelytyped.org). See how `@types/vscode` is published on there as an example

**Comment by chenjigeng** [comment]
I think if I wanted to put it under window, I'd probably have to write it like this
```
interface Window {
	acquireVsCodeApi: <T = any>() => {
		getState: () => T;
		setState: (data: T) => void;
		postMessage: (msg: unknown) => void;
	}
}
```
But should this thing be put in @types/vscode or a new types file?

**Comment by mjbvz** [comment]
Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53370
