### ISSUE TITLE
Web: home indicator causes activity bar cheese

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96225]
When the bar overflows the gear icon bleeds into the status bar.

**Comment by rebornix** [comment]
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/876920/80766143-920c7080-8af9-11ea-83b7-23aa3ff94326.png">

I'm seeing this one Safari where I didn't see this on Chromium based browsers which have minimal height for the page.

**Comment by bpasero** [comment]
That seems unrelated to my change, you do not even have the home indicator. Can you report it as separate issue? It probably exists from before my change.

**Comment by RMacfarlane** [comment]
Verified that this does not happen when the "web: home" indicator is present
