### ISSUE TITLE
CompletionItem sortText not respected

### ISSUE THREAD

**Issue by Raghul-S-1994** [microsoft/vscode#96224]
I have been working on a language server based vscode extension to provide custom ranked javascript completions. But whatever the sortText is, the completions are always at the bottom, after completions by *TypeScript and JavaScript Language Features* builtin extension.`

**Comment by jrieken** [comment]
This is now enough information to provide a meaningful reply.

**Comment by Raghul-S-1994** [comment]
Let's take method completion for example 
`console.<completion trigger>`

In this case, the plugin provides few completions as follows, which I wish to be ranked/shown at the top. 
1. assert
2. warn
3. error
4. log


The completion item for _error_ (3rd completion above) would look like this

> CompletionItem [
  label = "Ⓒ error"
  kind = Method
  tags = null
  detail = null
  documentation = null
  deprecated = null
  preselect = null
  **sortText = "error"**
  filterText = "error"
  insertText = "error"
  insertTextFormat = PlainText
  textEdit = null
  additionalTextEdits = null
  commitCharacters = null
  command = null
  data = null
] 

The completions from my plugin are preceded by the text **Ⓒ** . And you can see from the below gif that they are at the bottom.

![vscode_completion_demo](https://user-images.githubusercontent.com/20701077/80354930-05fa0f00-8895-11ea-8c47-b1ef79fbb7d4.gif)

**Comment by Raghul-S-1994** [comment]
Let's take method completion for example 
`console.<completion trigger>`

In this case, the plugin provides few completions as follows, which I wish to be ranked/shown at the top. 
1. assert
2. warn
3. error
4. log


The completion item for _error_ (3rd completion above) would look like this

> CompletionItem [
  label = "Ⓒ error"
  kind = Method
  tags = null
  detail = null
  documentation = null
  deprecated = null
  preselect = null
  **sortText = "error"**
  filterText = "error"
  insertText = "error"
  insertTextFormat = PlainText
  textEdit = null
  additionalTextEdits = null
  commitCharacters = null
  command = null
  data = null
] 

The completions from my plugin are preceded by the text **Ⓒ** . And you can see from the below gif that they are at the bottom.

![vscode_completion_demo1](https://user-images.githubusercontent.com/20701077/80356571-435f9c00-8897-11ea-8599-a2f47c839d0c.gif)

**Comment by jrieken** [comment]
Ok, thanks for clarifying. What's happening is that your sortText is compared with the sortText TypeScript uses. And they seem to using something "creative". When showing completion with details and can press `Cmd+?` to see the sorting internals and it seems that TypeScript uses `"0"` as sortText 🤷 ... So, you need to find something before that

<img width="738" alt="Screenshot 2020-04-27 at 11 30 18" src="https://user-images.githubusercontent.com/1794099/80356943-7a738480-887a-11ea-8c49-4b224e3421c7.png">
