### ISSUE TITLE
[typescript] Sintax Highlight breaks when a variable is assigned an object in a new line.

### ISSUE THREAD

**Issue by locovich** [Microsoft/vscode#9622]
- VSCode Version: 1.3.0, 1.3.1 (did not test previous versions)
- OS Version: Win10

Steps to Reproduce:

1. Open Code. 
2. Open the attached example file SintaxHighlightBugReport.ts (inside the zip, github does not support ts attachments)
3. Observe that the method wronglyHighlitedCode is not correct in terms of highlighted code colors (is all white text). 

I've attached a screen grab too, in which I've marked the behavior I'm observing in my PC.
![codesyntaxhighlightingbug](https://cloud.githubusercontent.com/assets/4842125/17056589/b412e2fc-4fea-11e6-84fa-1d70c66fc0d5.PNG)

[SyntaxHighlightBugReport.zip](https://github.com/Microsoft/vscode/files/378111/SyntaxHighlightBugReport.zip)

Hope this helps!

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#221
