### ISSUE TITLE
New File icon not working 

### ISSUE THREAD

**Issue by Prankurtiwari** [microsoft/vscode#96232]
- VSCode Version: version 1.44
- OS Version: windows 10

Steps to Reproduce:

1.Scale the VSCode windows to 50% horizontal division 
2. Now click on add new file icon (in my case it is refreshing it not creating a new file till I maximize it to full screen at that point it work properly) 

Does this issue occur when all extensions are disabled?: yes

**Comment by isidorn** [comment]
Fixed with latest vscode insiders
