### ISSUE TITLE
Downloading files while in remote-ssh session select name as Untitled rather than filename

### ISSUE THREAD

**Issue by whobbes** [microsoft/vscode#96235]
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z (1 wk ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:

1. Use vs-code with REMOTE-SSH to run on another machine via SSH
1. Right-click on file in explorer > Download
2. Name of file is **Untitled** rather than current name of file

Can't run remote SSH with all extensions disabled.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode-remote-release/issues/2536
