### ISSUE TITLE
editor.action.addCommentLine toggles the comment line

### ISSUE THREAD

**Issue by cg-cnu** [microsoft/vscode#96234]
As mentioned in the [docs](https://code.visualstudio.com/api/extension-guides/command) `editor.action.addCommentLine` **comments the currently selected lines in the active text editor**. By the name of the action, I was expecting it to comment the line if it is not already a comment and ignore otherwise. Currently it is toggling the comment.

For one of my extension I am looking for a way to comment only if the current line is not already one. Is there any way to do it currently with the existing API ? Does it make sense to rename the action to `toggleCommentLine` for clarity ?

**Comment by alexdima** [comment]
@cg-cnu There are multiple commands:
* `Add Line Comment` - `editor.action.addCommentLine` - `cmd+k cmd+c`
* `Remove Line Comment` - `editor.action.removeCommentLine` - `cmd+k cmd+u`
* `Toggle Line Comment` `editor.action.commentLine` - `cmd+/`

I'm not sure, what exactly do you mean? That you find the identifier `editor.action.commentLine` unsuitable for the command?

**Comment by cg-cnu** [comment]
Hey @alexdima Sorry I think I got a bit confused with the api here. This would have been a question infant. I am closing this one. Thanks for your time!
