### ISSUE TITLE
git takes centuries without informing or prompting for what to do

### ISSUE THREAD

**Issue by pierrecoach** [microsoft/vscode#96231]
We have written the needed data into your clipboard because it was too larg
Issue Type: <b>Bug</b>

Context : a project with python virtual environment used to run jupyter
Action : I open vs code and want to see the changes in git
Expected : after a while it shows the changed files on the left, or it displays a progress bar, or if it takes more than 5 minutes there is a problem and it prompts me for what to do (eg: commit all without see, discard all without see, keep waiting, explain what it is doing exactly ...)
Actual : 20 minutes waiting with the animation under 'source control', but still nothing displayed under the 'changes'

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.36GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|10.12.0
vscode-color|ans|0.4.5
code-gnu-global|aus|0.2.2
better-toml|bun|0.3.2
path-intellisense|chr|1.4.2
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.35.1
jshint|dba|0.10.21
vscode-eslint|dba|2.1.5
githistory|don|0.6.4
jquerysnippets|don|0.0.1
xml|Dot|2.5.0
vscode-generate-getter-setter|DSK|0.5.0
vscode-html-css|ecm|0.2.3
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.11
vs-code-xml-format|fab|0.1.5
vscode-npm|fkn|3.3.0
code-runner|for|0.9.17
gc-excelviewer|Gra|2.1.34
beautify|Hoo|1.5.0
rest-client|hum|0.23.2
path-autocomplete|ion|1.13.6
latex-workshop|Jam|8.9.0
csharpextensions|jch|1.3.1
docthis|joe|0.7.1
Angular2|joh|9.1.2
vscode-codemetrics|kis|1.24.0
eml|lei|0.4.0
MagicPython|mag|1.1.0
prettify-json|moh|0.0.3
easy-less|mrc|1.6.3
vscode-docker|ms-|1.1.0
vscode-language-pack-fr|MS-|1.44.2
csharp|ms-|1.21.17
mssql|ms-|1.9.0
python|ms-|2020.4.74986
remote-wsl|ms-|0.44.2
cpptools|ms-|0.27.0
Go|ms-|0.14.1
mono-debug|ms-|0.15.8
powershell|ms-|2020.4.0
debugger-for-chrome|msj|4.12.6
latex-formatter|nic|1.0.5
vscode-tap|num|1.0.2
tsimporter|pmn|2.0.1
typescript-hero|rbb|3.0.0
rust|rus|0.7.4
yo|sam|0.9.3
vscode-node-tap|sar|0.2.0
crates|ser|0.4.9
code-settings-sync|Sha|3.4.3
stylelint|shi|0.51.0
vscode-hexdump|sle|1.7.2
code-spell-checker|str|1.8.0
rust-pack|Swe|0.2.23
react-beautify|tai|0.3.0
shell-launcher|Tyr|0.4.1
vscode-icons|vsc|10.1.1
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0
commandlist|yam|1.0.3
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|2.8.0
html-css-class-completion|Zig|1.19.0

</details>
e to send. Please paste.

**Comment by joaomoreno** [comment]
Can you reproduce if you run with `code --disable-extensions`?

**Comment by pierrecoach** [comment]
Hi,

Sorry I removed everything and recloned from master, losing intermediate changes, so I cannot reproduce.

I think

  *   the incident can be closed as not reproducible,
  *   there should be a way to explain stuck users like I was that there is a problem (as explained in my text), but this is probably a feature request…

greetings

Pierre

De : João Moreno<mailto:notifications@github.com>
Envoyé le :lundi 27 avril 2020 16:16
À : microsoft/vscode<mailto:vscode@noreply.github.com>
Cc : Pierre<mailto:pierre169518185@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [microsoft/vscode] git takes centuries without informing or prompting for what to do (#96231)


Can you reproduce if you run with code --disable-extensions?
