### ISSUE TITLE
python： Segmentation fault

### ISSUE THREAD

**Issue by qiaohesoft** [microsoft/vscode#96237]
Issue Type: <b>Bug</b>

It reports “Segmentation fault” when import matplotlib.pyplot before others  packages,but it will do well when import matplotlib.pyplot behind others packages.For example,
       from matplotlib import pyplot as plt
       from gluoncv import model_zoo, data, utils
       It will be wrong.
       from gluoncv import model_zoo, data, utils
       from matplotlib import pyplot as plt
        It  will be well.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 5.3.0-3-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1899)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|15.60GB (4.66GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.44.2
python|ms-|2020.4.74986

</details>

**Comment by alexr00** [comment]
Does this happen if you disable all extensions?

**Comment by Tyriar** [comment]
@JacksonKearl needs more info not closing out the issue?

**Comment by JacksonKearl** [comment]
I would expect to have been closed tomorrow. It's a 7 day delay, Alex labeled it at 4:57AM 7 days ago, the last bot run was at ~4:20AM today, so it just missed the cutoff.
