### ISSUE TITLE
Test syncing UI state

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#96236]
Ref - #93332

- [x] anyOS @connor4312
- [x] anyOS @Tyriar

Complexity: 4

Authors: @sandy081 @RMacfarlane @octref 

---

## Set Up

- To test, have two insiders open with different user data directories and extension directories

**Note**: Wait a moment for sync to be triggered and done on other machine before testing synced UI state - Check sync logs.

- Test that trusted domains are synced
  - Open a link that is not trusted
  - Remember to trust this link
  - Go to another instance of VS Code 
  - Try to open the same link and make sure that you are not asked to trust the link again

- Test that trusted extensions are synced
  - Sign in with GH account to settings sync
  - Write test extension that tries to access this same token:
```ts
	const session = await vscode.authentication.login("github", ['user:email']);
	const token = await session.getAccessToken();
	vscode.window.showInformationMessage('Successfully logged in');
```
- Test that ignored recommendations are synced
  - Open a python file and see that you get a notification to install python extension
  - Ignore this recommendation by choosing `Do not shown again`
  - Go to another instance of VS Code
  - Try to open python file and make sure notification is not shown

**Comment by connor4312** [comment]
> Test that trusted extensions are synced

What's the expected outcome of this test case? I get the following dialog the first time per window I try to sign in, on both machines:

![](https://memes.peet.io/img/20-04-91da61e9-42a8-4af3-a143-24cecd8c82fd.png)

**Comment by RMacfarlane** [comment]
Ah, sorry, that dialog should be shown every time .login is called. My code above should have been:
```
const sessions = await vscode.authentication.getSessions("github", ['user:email']);
if (sessions.length) {
    const token = await sessions[0].getAccessToken();
    vscode.window.showInformationMessage('Successfully logged in');
}

```
