### ISSUE TITLE
The Timeline icon is the same like the Outline icon

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#96246]
The Timeline icon is the same like the Outline icon
![obraz](https://user-images.githubusercontent.com/30685349/80367109-c7f7ed80-888a-11ea-9d95-0ab2dce5dff5.png)
In my opinion, these icons should be different

For The timeline it should be something like:
![obraz](https://user-images.githubusercontent.com/30685349/80367457-6e43f300-888b-11ea-91e1-76d19a796d7d.png)
or
![obraz](https://user-images.githubusercontent.com/30685349/80367492-7e5bd280-888b-11ea-9d44-fccfceb0cf31.png)

**Comment by gjsjohnmurray** [comment]
Already resolved in 1.45.0-insider. Below is how Extensions, Timeline, Outline appear in Quiet Light theme:

![image](https://user-images.githubusercontent.com/6726799/80379122-90db0980-8895-11ea-98d4-6ba83d3dc925.png)
