### ISSUE TITLE
Explorer: new file does not allow ./ syntax?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96243]
![image](https://user-images.githubusercontent.com/900690/80362034-384e4100-8882-11ea-889e-c90279336d64.png)

I think it is fair to prevent creation of files outside the workspace root, but `./` seems pretty safe to me.

**Comment by isidorn** [comment]
This is a fair request.
We are open to pull requests that fix this.
Code pointer https://github.com/microsoft/vscode/blob/1a3d767b1a7043bcb3d5e81ab66108963e425612/src/vs/workbench/contrib/files/browser/fileActions.ts#L806

**Comment by LilJohny** [comment]
Hello, @isidorn  Can I take it?

**Comment by isidorn** [comment]
Sure. We accept concise and preicse PRs. Also for this I think you can add unti tests.

**Comment by LilJohny** [comment]
@isidorn Please, check my PR. If it is good, I`ll add unit tests specific to this case. I already tested it manually.

**Comment by LilJohny** [comment]
I added two tests also.
