### ISSUE TITLE
executeDefinitionProvider has a breaking change in Insiders

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#96240]
This may be known/deliberate, but I couldn't find anywhere listing breaking changes to check. If it is, feel free to close!

The `executeDefinitionProvider` command used to always return `Location`s (as documented [here](https://code.visualstudio.com/api/references/commands) - they always had a `uri` field). This was the cause even if the provider returned `DefinitionLink`s. Now (in insiders), the `DefinitionLinks` will be returned from the command instead, so if anyone is relying on the `uri` property, it will become `undefined` after the update.

Here's an example. In Insiders, uncomenting the line that adds `targetSelectionRange` causes the command to crash (calling `toString` on an undefined `uri`), but in stable that's not the case, and reading the `uri` is fine.

```ts
import * as vs from 'vscode';

export function activate(context: vs.ExtensionContext) {

	vs.languages.registerDefinitionProvider([{ language: "dart" }], {
		provideDefinition(document: vs.TextDocument, position: vs.Position, token: vs.CancellationToken): vs.ProviderResult<vs.Definition | vs.DefinitionLink[]> {
			const range = new vs.Range(new vs.Position(1, 0), new vs.Position(1, 3));
			return [{
				// Uncomment this code to cause vscode.executeDefinitionProvider to start returning DefinitionLinks
				// In current stable, the returned objects will always have .uri, even if this line is uncommented.
				// targetSelectionRange: range,
				targetRange: range,
				targetUri: document.uri,
			} as vs.DefinitionLink];
		}
	});

	let disposable = vs.commands.registerCommand('vscode-repro-definition-uris.helloWorld', async () => {
		const doc = await vs.workspace.openTextDocument({language: "dart"});
		const editor = await vs.window.showTextDocument(doc);

		const locations = await vs.commands.executeCommand("vscode.executeDefinitionProvider", doc.uri, new vs.Position(0, 2)) as vs.Location[];
		const location = locations[0];
		console.log(location.uri.toString());
		console.log(location.range);
		console.log(JSON.stringify(locations, undefined, 8));
	});

	context.subscriptions.push(disposable);
}

export function deactivate() { }
```

I don't know how many extensions use this command - I was using it for tests, and I've just updated them to support either. If the function is used by other extensions, this might cause them bugs though.

**Comment by dbaeumer** [comment]
This is actually as designed. That the API commands still returned `Locations` and not `LocationLinks` even though the provider returned them was considered a bug. Otherwise a extension calling for example into the TypeScript language service via that API could never get a correct location since the returned locations range was pointing `LocationLink#range` and not to `LocationLink#selectionRange` which was a bug as well.

However we need to update the documentation to make this clear.

**Comment by DanTup** [comment]
> That the API commands still returned `Locations` and not `LocationLinks` even though the provider returned them was considered a bug.

I presumed this was done for backwards compatibility - otherwise any extension that was written using `Locations` could fail if a registered provider started returning `DefinitionLink`s.

Out of interest - are breaking changes recorded anywhere that extension developers can review prior to each release? This change only broke my tests, but it's not inconceivable that extensions could use this command and become broken when the release goes out. It'd be good to know a little in advance so a fix could be developed/released out before VS Code releases.

**Comment by dbaeumer** [comment]
I will mention it in the release notes.
