### ISSUE TITLE
tag completion HTML, REACT, REACT-NATIVE 

### ISSUE THREAD

**Issue by Fylls** [microsoft/vscode#96245]
when you want to wrap around a new  tag in a component/markup the process can be frustrating.

Every time you close a tag, fortunately VScode completes it for you:
e.g. if i write :  `<View>` VScode creates for me the relative closing tag so: `<View></View>`

but if you went to wrap around a long script you have to cut(CTRL + X) the closing tag and put it at the end of the script.

**Comment by alexr00** [comment]
I'm not sure I understand 

> but if you went to wrap around a long script you have to cut(CTRL + X) the closing tag and put it at the end of the script.

Can you share a screen recording?

**Comment by Fylls** [comment]
![GameScreen js-CORSO-Visual-Studio-Code-2020-04-27-17-01-53](https://user-images.githubusercontent.com/55017307/80388017-a823f200-88a9-11ea-8b73-9ab893d7d7a8.gif)

it is not a big problem but it would be a nice feature to add something that can wrap one tag  both to the beginning and to the end of a specific script in just one command.

**Comment by alexdima** [comment]
I'm not a big user, but I believe `emmet` can do this:

![Kapture 2020-04-27 at 21 11 20](https://user-images.githubusercontent.com/5047891/80410967-b1be5180-88cb-11ea-8812-de1112acb714.gif)

**Comment by Fylls** [comment]
Is where a way to bind it to a specific key in order to make it more easy to reach or something similar?
thanks a lot for the replay, didn't know VScode had this feature, seems great!

**Comment by alexdima** [comment]
@Fylls Yes, keybindings can be bound to all actions. You can open the keybindings editor (ctrl+k ctrl+s) and search for the action you want and then add a keybinding for it:

![image](https://user-images.githubusercontent.com/5047891/81041683-b9bf5800-8eae-11ea-988f-263beed20fde.png)

We have a lot of documentation on this and many other topics at https://code.visualstudio.com/docs
