### ISSUE TITLE
command to reload a single given Webview

### ISSUE THREAD

**Issue by brunoNetId** [microsoft/vscode#96242]
Feature request for VSCode Webview Extensions.

A command already exists to reload Webviews, and one can programatically invoke it by implementing the following line:
    vscode.commands.executeCommand("workbench.action.webview.reloadWebviewAction")

However, the above command reloads ALL webviews, which might be undesirable when multiple Webviews are displayed on screen.

The need requested is to have the ability to reload a specific Webview. For example to be able to identify a specfic Webview that is open, and request a reload to refresh its HTML content.

Thanks

**Comment by mjbvz** [comment]
Can you share your use case for this?

**Comment by brunoNetId** [comment]
I'm developing an extension (webview-1), and I'd like to make use of an existing extension (also webview-2).
  1) Helps defining processing flows.
  2) Helps defining data transformations.

The second one runs a local Java JVM that holds state. The extension can submit data and request state to/from the JVM.

The extension I'm trying to develop defines processing flows and might launch 1) to start defining data transformations. It might submit data to the JVM, and changes would need to be refreshed on its Webview.

**Comment by mjbvz** [comment]
Thanks. Does your extension control both of the webviews being developed? Also, how would your extension identify which webview to refresh? The viewType or editor group for example?

**Comment by brunoNetId** [comment]
No, I only control the one I'm developing, but the user would be making use of both.
I'm relatively new to VSCode and I don't know well what the possibilities are. I did find the reload command (mentioned in the description), it's just missing to take a webview 'id' to refresh.
I was hoping the API would allow to get the list of open editors (from the explorer for instance) and pick the one corresponding to the data transformations Extension.
Thanks

**Comment by mjbvz** [comment]
Related #15178 

Webviews are only known to the extension that created them so they don't really have a concept of an id that other extensions can use. How about filing a feature request against the extension that provides these webviews to add an API for refreshing them?

**Comment by brunoNetId** [comment]
Your suggestion might be a possible option, I'll try to progress following
that direction.
Thanks for you help.

**Comment by mjbvz** [comment]
Ok, I'll close this issue for now then since it sounds like an extension specific solution may be the way to go
