### ISSUE TITLE
code runner not found

### ISSUE THREAD

**Issue by tirthmakawana** [microsoft/vscode#96254]
Issue Type: <b>Bug</b>

please fix my problem. whenever i press code runner button it shows "command code-runner not found

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.17
python|ms-|2020.4.74986

</details>

**Comment by alexr00** [comment]
This is caused by the code-runner extension.

**Comment by tirthmakawana** [comment]
> This is caused by the code-runner extension.

How do I rectify it ?

**Comment by tirthmakawana** [comment]
> This is caused by the code-runner extension.

Ok done... I uninstalled the VScode and then reinstalled it😅😅
