### ISSUE TITLE
Intellisense no long works and fans going constantly

### ISSUE THREAD

**Issue by Undistraction** [microsoft/vscode#96255]
Issue Type: <b>Bug</b>

After upgrading to Version: 1.44.2, Intellisense no longer works at all in my VSCode project, and as soon as I open a JavaScript file, the fans on my laptop run at full and don't stop until I close VSCode. 

If I hover over a symbol I see [Loading…] but it never loads anything.

I've disabled all extensions and still see the same behaviour.

If I open the Process Explorer I see:

```
CPU %	Memory (MB)	pid	Name
3	131	96471	code main
0	98	96472	     gpu-process
0	33	96474	     utility
0	328	96475	     window (CorporateAccessHero.js — sleepstation-public)
0	98	96482	         extensionHost
0	66	96717	             electron_node tsserver.js 
111	2163	96721	             electron_node tsserver.js 
0	98	96741	                 electron_node typingsInstaller.js typesMap.js 
0	33	96734	             /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=96482
0	0	96483	         /bin/bash -l
0	33	96533	         watcherService
0	33	99928	         searchService
0	98	96761	     shared-process
0	66	99941	     window (Process Explorer)
```

My `jsconfig.json`:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "jsx": "react"
  },
  "include": ["./src/**/*.js"],
  "exclude": [
    "node_modules",
    "dist",
    "coverage",
    "demo",
    "static",
    "public",
    ".cache"
  ]
}
```

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|32.00GB (11.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). After installing that extension and restarting VS Code, do you still see the issue?

**Comment by Undistraction** [comment]
@mjbvz Thank you. That definitely appears to have helped. I'll report back tomorrow after I've used this for a few hours.

**Comment by Undistraction** [comment]
@mjbvz Been using VSCode all day. Intellisense appears to be working correctly now, but Fans still going hard. 

Activity monitor reports `Code helper (Renderer)` is using over 100% CPU, and this is with VSCode in the background (I haven't used it for an hour or so). CPU Time: `1:25:41.62`

If I run the process explorer:
```
100	66	9807	             electron_node server.js 
```

Let me know if I can give you any other info.

**Comment by mjbvz** [comment]
Thanks for testing.

Is the processes with the high cpu usage called `server.js` and not `tsserver.js`? If it's just `server.js`, it may be started by one of your other extensions. To see which one, can you share the full process info for that process by running `ps aux PROCESS_ID` on the command line

**Comment by Undistraction** [comment]
@mjbvz It is `server.js`.

The result of `ps aux PROCESS_ID` is:

```
pedrbrowne  9807 100.0  0.2  5973368  55304   ??  R    Mon08pm 991:41.72 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Re
```

**Comment by mjbvz** [comment]
Thanks. That's from the gutter-preview extension. Please file an issue against them

**Comment by Undistraction** [comment]
@mjbvz Looks like that was just masking the problem, or possibly an additional issue. I'm seeing the same behaviour now with `tsserver.js` (Fans on constantly, intellisense no longer working):
```
105	 1180	10420	             electron_node tsserver.js 
```

The result of `ps aux PROCESS_ID` is:
```
USER         PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND
pedrbrowne 17652 102.7  2.1  6949044 714464   ??  R     7:26pm   1:16.20 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) --max-old-space-size=3072 /Users/pedrbrowne/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200503/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/_0/7sk3xl9n18ldl4zswn5_xm6c0000gq/T/vscode-typescript503/25c3a398dcbdcdf4c64c/tscancellation-7ca5fc6d21093ead1de8.tmp* --logVerbosity verbose --logFile /Users/pedrbrowne/Library/Application Support/Code/logs/20200504T185114/exthost1/vscode.typescript-language-features/tsserver-log-00BWMT/tsserver.log --globalPlugins typescript-vscode-sh-plugin --pluginProbeLocations /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
```

I can open this as a new issue if you'd prefer.

**Comment by Undistraction** [comment]
@mjbvz I've created a follow-on issue here: #97055
