### ISSUE TITLE
Using `createMatches` with offset is bogous

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96256]
Stumbled over the new `offset` parameter of `createMatches`: https://github.com/microsoft/vscode/blob/4711909afcdd79cd1cc9b96063212b81ae80d8c7/src/vs/base/common/filters.ts#L395

This tells me that something hasn't been understood because [`FuzzyScore`](https://github.com/microsoft/vscode/blob/4711909afcdd79cd1cc9b96063212b81ae80d8c7/src/vs/base/common/filters.ts#L524) itself already has the notion of an offset. The idea is that no substrings are created but `fuzzyScore` (and its cousins) should be called with a `wordPos` which is the offset at which matching should start inside a word. That offset is that captured inside the score and used when creating matches. The new offset doesn't fit into this.

**Comment by bpasero** [comment]
**Verification:** use quick outline and search. The highlights should be proper and results too.
