### ISSUE TITLE
Terminal: Improve environment variable collection popup

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#96250]
This can get pretty verbose quickly:

![image](https://user-images.githubusercontent.com/22350/80371019-7dc63a80-8891-11ea-8375-9b47ef5001cf.png)

Also, should we indicate which extension is doing which changes?

**Comment by Tyriar** [comment]
Might be better:

Extensions have made changes to this terminal's environment:

```
VSCODE_GIT_IPC_HANDLE=/tmp/vscode-git-ipc-blah...
FOO=${FOO}BAR
BAR=FOO${BAR}
```

Using a code block and not wrap it just like in the editor?

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/80614487-5c7d5f80-89f3-11ea-9769-5ff0f9a3cdfc.png)

(this one now doesn't show by default https://github.com/microsoft/vscode/issues/96574)

![image](https://user-images.githubusercontent.com/2193314/80614451-538c8e00-89f3-11ea-9ea4-fa0480f5c0fd.png)

**Comment by joaomoreno** [comment]
> Also, should we indicate which extension is doing which changes?

☝️

**Comment by Tyriar** [comment]
👉 https://github.com/microsoft/vscode/issues/96699

**Comment by joaomoreno** [comment]
@Tyriar The icon seems to be gone today:

![image](https://user-images.githubusercontent.com/22350/80721115-24af0e80-8afe-11ea-8f9d-be467ed3052e.png)

**Comment by Tyriar** [comment]
Only the warning shows by default now as basically every terminal will have it now due to git using the API. Use `"terminal.integrated.environmentChangesIndicator": "on"`
