### ISSUE TITLE
Veird artifacts in VSC on windows focus change

### ISSUE THREAD

**Issue by atamanoff** [microsoft/vscode#96269]
![Безымянный2](https://user-images.githubusercontent.com/40996318/80385830-3ea6e200-88af-11ea-8049-82f33e693b35.png)
Issue Type: <b>Bug</b>

Hello, I have weird artifacts in VSC when I change window focus (click on control panel or other program). This artifacts look like white dots and lines, like weird snow around words and images. 
This artifacts disappear when I click back on VSC window, sometimes I need to move cursor around artifacts. 
My PC and system perfectly fine, I work and play on this PC for few years. And this artifacts only appears in VSC.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (10.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-docker|ms-|1.1.0
python|ms-|2020.4.74986

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
Duplicate of #93356 or #94523

Is it reproducible if you start code with `code --disable-gpu`? https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Comment by atamanoff** [comment]
> Duplicate of #93356 or #94523
> 
> Is it reproducible if you start code with `code --disable-gpu`? https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

Disabling hardware acceleration in argv.json helped, no more artifacts! Thank you very much!
