### ISSUE TITLE
Option to disable creation of a branch when a remote tracking branch is selected

### ISSUE THREAD

**Issue by bharath144** [microsoft/vscode#96264]
When using vscode with Git repositories, in the branch switching pane if a remote tracking branch is selected, vscode automatically creates a local branch using selected remote tracking branch.

It would be useful to have a setting to turn this off and checkout the remote tracking branch in a detached state. I use branches in detached state to browse the code, run quick builds, copy code. With the local branches getting created, my repo ends up with a lot of those and I end up spending time later to cleanup the local branches. 

To get around this, I switch to the terminal and checkout the remote tracking branch (`git checkout origin/<remote_branch_name>`) and then switch back to vscode.

**Comment by joaomoreno** [comment]
Setting makes sense!

**Comment by heinemannmarkus** [comment]
I've created a pull request for this feature. This is the first time for me contributing to an open-source project so please tell me if I missed something or didn't solve the issue right.

**Comment by aditya237** [comment]
heyy

**Comment by markuscodes1** [comment]
I have tried to find out why the tests fail under windows and macos but without result. Has anyone an idea?

**Comment by joaomoreno** [comment]
You can now checkout in detached mode:

![recording (8)](https://user-images.githubusercontent.com/22350/98372802-a13b2080-203e-11eb-85ca-c2ab8c73c9d7.gif)

**Comment by roblourens** [comment]
This seems like the "Checkout to (Detached)" command is doing a normal checkout

- Run that command in the vscode repo
- pick some random remote branch, `origin/joh/outline`
- Now I have a local branch, `joh/outline`

In the git output channel, I see that it ran this command `> git checkout -q --track origin/joh/outline`

**Comment by joaomoreno** [comment]
**Verification**:

1. Test that running `Git: Checkout` will have an option to Checkout in detached mode
2. Test that `Git: Checkout Detached` works

In detached mode, the branch status bar indicator won't indicate the branch name but the commit id.
