### ISSUE TITLE
VSCode Extension Error

### ISSUE THREAD

**Issue by felipeagrela** [Microsoft/vscode#9626]
- VSCode Version: 1.3.0
- OS Version: Windows 10 Pro x64

Steps to Reproduce:
1. Open CMD
2. code --install-extension csharp

C:\WINDOWS\system32>code --install-extension csharp

![vscode](https://cloud.githubusercontent.com/assets/4611836/17062598/0139c414-500a-11e6-8044-fb37761b70bc.PNG)

**Comment by felipeagrela** [comment]
Yes, I'm using proxy and I use "http.proxy" tag to configure it

**Comment by joaomoreno** [comment]
- Do you set it globally or in the workspace settings?
- Can you install extensions inside the product, using that proxy setting?

**Comment by felipeagrela** [comment]
"http.proxy": "http://proxy.example.com.br:portNumber"

No, I can't install inside...

**Comment by joaomoreno** [comment]
What do you see inside? Any errors? Can you successfully browse extensions?

**Comment by felipeagrela** [comment]
I can browse normally, but when I click on install button they change to installing but nothing changes...

![vscode2](https://cloud.githubusercontent.com/assets/4611836/17105215/ab583742-525c-11e6-992a-62d0301c9b7c.PNG)

**Comment by joaomoreno** [comment]
Alright. I just pushed some changes that should fix the lack of an error. These will be available tomorrow in the Insiders release. Do you mind retrying tomorrow with that build? We'll possibly get a more detailed error message. Thanks!
