### ISSUE TITLE
vscode in chrome os assumes user's home is workspace (bad assumption)

### ISSUE THREAD

**Issue by leemke** [microsoft/vscode#96268]
Issue Type: <b>Performance Issue</b>

Just install Vscode in chrome os, and used the chrome os/linux short cut to start
vscode.  By default this method assume that "linux files" (user $HOME) is the workspace.

Without reading how to start vscode for linux documentation, it becomes difficult to 
create a new workspaces within workspaces. My guess is vscode does not like workspaces within workspaces. 

To circumvent this problem, I now create new workspaces by using the 
linux command line instructions to create a new workspace/project.
Then when I start Vscode in chrome OS (from linux app folder), I have
no problems. 

If you are new to vscode and follow the tutorial videos, and don't know the unstated assumption that the starting folder becomes the workspace it makes it difficult to
create multiple projects (workspaces), with different languages under the same home workspace.  I assume each project is isolated from other projects by placing them in different workspaces.  

Just a suggestion after spending days trying to understand and set up multiple workspaces. Not a good experience. 

Suggestion: provide a facility (in "file" drop down menu) for creating a workspace.
and other facilities for modifying and deleting work spaces (they may exist but I don't see them in the file menu). Include in the "create new workspace" option a requirement for the user to specify where the workspace is located. Allow the user 
to navigate to an existing folder and create a new folder in that menu, rather than assuming the workspace folder already exist (which is part of the linux command line process).
No longer assume the starting directory is the default workspace. Make the user always define where the workspace is located rather than assuming the starting directory.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 4.19.98-08076-g24ab33fb8e14

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (2 x 1607)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|6.48GB (1.97GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|100%|
</details><details>
<summary>Workspace Info</summary>

```
|  Window (hello_world.cpp - cpp_hello_world (Workspace) - Visual Studio Code)
|    Folder (cpp_hello_world): 8 files
|      File types: code-workspace(1) h(1) cpp(1) json(1)
|      Conf files: tasks.json(1);
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
c-cpp-compile-run|dan|1.0.8
vscode-eslint|dba|2.1.5
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
cpptools|ms-|0.27.0
material-icon-theme|PKi|4.1.0
vscode-arduino|vsc|0.3.0

(1 theme extensions excluded)

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by alexr00** [comment]
Can you provide steps for how you are trying to do this?

> Without reading how to start vscode for linux documentation, it becomes difficult to
create a new workspaces within workspaces.

**Comment by leemke** [comment]
It appears, that following the tutorial for new VScode beginners, (in the Chrome OS env) that launching the app from tray, places you in the users home directory by default
(i.e $HOME directory).  When you create a file, it is in that directory. When you save as
a workspace your $HOME directory becomes the workspace (by default). 
I don't remember this being mentioned in the tutorial (video). 
I read a linux info for Vscode.  It started by creating a directory, under your home
directory, going to that directory and starting "code" from there. 
I assumed that is the way to do it.  

now I have learned that I can create a new directory/folder within vscode, to whatever
depth needed and save it as a workspace.  This added information would be more
helpful in the initial video tutorial. It took me some time to figure out this process.
I believe workspaces are a very important part of vscode. They should be addressed
from the beginning.  Default values make it quick, but can lead to frustration down the road.
