### ISSUE TITLE
Action tooltip and ARIA label do not update on keybinding change

### ISSUE THREAD

**Issue by ndarilek** [microsoft/vscode#96260]
Say you have the following in keybindings.json:

```
{
  "key": "ctrl+shift+alt+g",
  "command": "workbench.view.scm"
}
```

Tabbing through the various buttons (I.e. Explore, Run, etc.) still speaks the default ctrl+shift+g keybinding for this action, despite the new one working fine and the old one no longer being accurate.

**Comment by isidorn** [comment]
This is a general issue that actions are not listening on [`onDidUpdateKeybindings` event](https://github.com/microsoft/vscode/blob/616882b83f2010b551fff2da0e63c55b2464fcbf/src/vs/platform/keybinding/common/keybinding.ts#L55) and thus we do not update the tooltip.

First assigning to @sandy081 and then we might have to assign this to every client of `lookupKeybinding` such that they all listen to the keybinding change event and update

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/96019

**Comment by sandy081** [comment]
@isidorn I fixed the viewlets/panels in the issue - https://github.com/microsoft/vscode/issues/96019

Reassigning this to you if you want to use this to track other usages

**Comment by isidorn** [comment]
Let's close for now and when new issues arrive we can reopen since you fixed for views.
