### ISSUE TITLE
showQuickPick in onDidDeleteFiles doesn't work for multiple deleted files

### ISSUE THREAD

**Issue by ws93** [microsoft/vscode#96274]
- VSCode Version: Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
- OS Version: OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Clone my template extension project: https://github.com/ws93/deletefilesapi (The 4-line [code](https://github.com/ws93/deletefilesapi/blob/master/src/extension.ts#L14-L17) I added after `yo code`)
2. `npm install` and then run extension
3. open a folder that contains multiple files
4. `ctrl` select 2 files and right click and delete them
5. I expect to see 2 quickpickers one by one. But instead, it seems the extension cancelled the first quick pick popup and only shows the second one. The selected item for first quickpicker is `undefined`.

There's also an issue #86210 with `onDidDeleteFiles` api that if you `ctrl` select multiple files and delete them, it will trigger `onDidDeleteFiles` multiple times instead of having one `FileDeleteEvent` that contains an array of multiple deleted files. 

So I'm not sure if the problem is when the second event got fired it also fired a `cancel` or `esc` so it cancelled the first `showQuickPick`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This is the same underlying reason as #86210
Once we tackle that, we can look into this one. Until then assigning to backlog.
