### ISSUE TITLE
How to decide to execute Language Service of "Rename"?

### ISSUE THREAD

**Issue by johnsoncodehk** [microsoft/vscode#96273]
TypeScript LS and my program also provide the rename capability for TypeScript language, but I can't seem to control which Language Service is used to perform the rename action in VSCode.

I think it should be like formatting action, let users choose, did I miss something?

**Comment by jrieken** [comment]
see https://github.com/microsoft/vscode/blob/47b1183dfda519c32d78b591cfa721d3b0b874ae/src/vs/vscode.d.ts#L9632

**Comment by jrieken** [comment]
There can only be one rename provider for a language and it goes by score. A tie-breaker is the time an extension is registered so can enforce your extension to win by taking a dependency onto the built-in TS extension

**Comment by johnsoncodehk** [comment]
@jrieken Thank you! I am still in the exploration stage, so what I know may not be correct.

I hope the language program can be used out of the box. The typescript plugin solution seems to require users to edit tsconfig.json to take effect.

In addition, I seem to be able to gain full control by intercepting the rename behavior through LanguageClientOptions.middleware.provideRenameEdits?

I hope to avoid the Language Service competition behavior that is not perceivable by users, so I consider not providing the rename function for the time being. I may open a new issue to request the rename action to obtain the same user choice as the formatting action.
