### ISSUE TITLE
Test Notebooks

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96279]
Refs: https://github.com/microsoft/vscode/issues/91987

- [x] anyOS @RMacfarlane
- [x] anyOS @sandy081 
- [x] anyOS @bpasero (web)

Complexity: 5

Authors: @jrieken, @misolori, @rebornix, @roblourens 

---

1.  First and foremost install the GH issues notebook extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-github-issue-notebooks

#### Language Features

* Test that labels get verified when a repo is specified, e.g `repo:microsoft/vscode label:ffff` should trigger a warning
* Test that labels get verified against all repos, e.g `repo:microsoft/vscode label:bug repo:microsoft/vscode-docker label:*english-please`
* Test that code cells can be formatted via "Format Document" and "Format Selection" (the formatter removes whitespace, e.g `$foo= fff  label:bug` should become `$foo=fff label:bug`)
* Test that there is a global "Format Notebook" command that formats multiple code cells (and that this operation can be undone)
* Test that there is quick outline for notebooks and that it is driven by markdown headers 

### Drag & Drop

Test that you can drag cells by their left margin and drop them to reorder the notebook. Note these known issues: https://github.com/microsoft/vscode/issues/96308

- Cells should go to the correct spot after dropping
- You should be able to scroll by dragging to the top or bottom of the viewport
- The cell should be visible after dropping
- You shouldn't be able to drop in another editor or window

### Cell language selector button

You can click it to see a list of languages supported by the notebook (in the github issues case, just "github-issue" and markdown). And you can pick a language to switch a cell from markdown-type to code-type and back. 

### Folding

We supported cell based folding in a notebook. The Folding regions are calculated based on the most important headers in a markdown cell (when a markdown cell has `h1`, `h2` and `h3`, `h1` will be used then). Please test

* Folding regions are correct (especially nested folding) 
* Fold/Unfold doesn't break the rendering of outputs (you can execute the query first to get a well rendered result)
* Navigation works fine when there are folded regions (arrow up/down)
* Folding regions and collapsed states are restored when reopen a file (if the file on disk doesn't change)
* Folding regions are updated after a markdown cell is updated and quit edit mode)
* Moving cells (using commands or drag and drop) will update the folding regions correctly

### Web

This is particularly for testers for Web platform. Running notebook in the Web is the same as running it locally. The major difference is on Desktop the outputs are rendered in Electron Webview while in Web, it's rendered in iframe. Please make sure that outputs are rendered properly.

---

Bash on it in general and watch out for layout issues, like cells that are the wrong height or width, covering up other cells, etc. Issues like this that have repro steps are very valuable.

**Comment by bpasero** [comment]
I am not seeing a "Format Notebook" command:

![image](https://user-images.githubusercontent.com/900690/80511892-02da4e00-897d-11ea-99ce-48ade145646c.png)

**Comment by bpasero** [comment]
As for quick outline, I get this:

![image](https://user-images.githubusercontent.com/900690/80511937-14bbf100-897d-11ea-932a-10fa20fde1ed.png)

Not sure I need todays insider build for this (I am currently on yesterdays).

**Comment by jrieken** [comment]
@bpasero Requires a pretty recent build (since I did those features late on monday). Also make sure not to be focused a code cell but inside other notebook things
