### ISSUE TITLE
Git: Support showing stashes in the UI

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#96286]
![image](https://user-images.githubusercontent.com/35271042/80404175-a0e2f100-8875-11ea-964e-ddde84f7b9fe.png)

Would be great if when you saved a stash that the UI would surface this (maybe in another view) w/ related actions (apply, discard, etc.)

**Comment by joaomoreno** [comment]
Sorry @misolori, closing this as GitLens offers this feature already.
