### ISSUE TITLE
Test NotebookConcatDocument

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96282]
Refs: https://github.com/microsoft/vscode/issues/96279

- [x] anyOS @weinand
- [x] anyOS @sbatten

Complexity: 4

Authors: @jrieken, @misolori, @rebornix, @roblourens 

---

To help extension authors integrate existing language services with notebooks we have added a "concat document". That is all code cells of a notebook represented as single document. 

1. Install https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-github-issue-notebooks so that you have notebook sample

Now, use the [`vscode.notebook.createConcatTextDocument`](https://github.com/microsoft/vscode/blob/8ec6ec7dc128b949f445ba254eabc8e931e90f78/src/vs/vscode.proposed.d.ts#L1804)-API and to implement some fake language features, e.g. write a fake go-to-definition feature that uses [`positionAt`](https://github.com/microsoft/vscode/blob/8ec6ec7dc128b949f445ba254eabc8e931e90f78/src/vs/vscode.proposed.d.ts#L1713) and `locationAt`-API

The general flow is like this

* keep a concat document around and implement fake go-to-def using that document (e.g jump to a random line)
* register a language feature for notebook cells, e.g `{scheme: vscode-notebook}`-selector
* map a cell onto the concat document (request) and map the result back onto cells

**Comment by jrieken** [comment]
fyi - use the [vscode-dts](https://www.npmjs.com/package/vscode-dts)-utility to use the latest version of `vscode.d.ts` and/or `vscode.proposed.d.ts`

**Comment by weinand** [comment]
@jrieken Could the "NotebookConcatDocument" approach make existing language features automatically available to notebooks?
E.g. the JavaScript GoTo-Definition could work if:
- a notebook supports the "NotebookConcatDocument"
- the DocumentSelector of the "NotebookConcatDocument" matches the existing language feature
- and the language feature support is "pure", that means it only accesses resources via a document

**Comment by jrieken** [comment]
Yeah, maybe. The problem is that a concat document isn't a document, e.g it doesn't appear in the list of open text documents or in the respective events. So, a "magic integration" won't be possible - unfortunately. 

The benefit of the concat document is that everything appears to be within one file, e.g there is no need for export/import statements (which will feel alien in notebooks) in order to reference variables and functions from other cells. However, that comes at the cost of isolation. If you have two cells that define different variants of the same (named) function you will have a conflict..
