### ISSUE TITLE
Cursor doesn't always follow line indentation

### ISSUE THREAD

**Issue by eodeluga** [microsoft/vscode#96289]
If you start a new block of code, the cursor auto indents when you create a line break (new line) for the body of the block e.g 

    class Test {
    

    }

Here the opening curly brace of the block is followed by two line breaks before the closing brace.

If you arrow up now, the cursor doesn't stay inline with the indentation, but jumps to the beginning of the previous line.

The behaviour is the same using this code style too

    class Test
    {
        // Some comment huh
    
        
    }

Looking at the settings page and searching for 'cursor', there is not an option to change this behaviour from what I can see.

I work with C# but presume this happens in other languages, and wanted to know if this is a bug or if I'm doing something wrong.

Possibly irrelevant, but I don't see this in other IDEs I use such as IntelliJ where the cursor always follows line indentation when moving between lines.

Thanks.

**Comment by alexdima** [comment]
This is the setting `"editor.trimAutoWhitespace"`. From your description, it appears that you want the automatic whitespace inserted by the editor to be kept, so simply configure that to `"editor.trimAutoWhitespace": false`.
