### ISSUE TITLE
Missing saveAs csv file type in file saveAs dialog

### ISSUE THREAD

**Issue by lkhatkar** [microsoft/vscode#96283]
Missing saveAs csv file type file saveAs dialog. I needed to save exported csv content from sqlite3 but could not found any extension type as csv in file save as dialog.

**Comment by alexr00** [comment]
Can you provide steps for how to reproduce your problem?

**Comment by lkhatkar** [comment]
Steps to reproduce:
Open any .csv file,
Click on File->SaveAs
SaveAs dialog opens and it is missing saveAs csv file type

**Comment by alexr00** [comment]
What OS and version of VS Code are you using?

**Comment by lkhatkar** [comment]
Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by alexr00** [comment]
@alexdima this appears to be because the ModeService doesn't know the file extension `csv`.

**Comment by alexdima** [comment]
I could not reproduce on macOS.

**Comment by alexdima** [comment]
I think there will always be file extensions which we don't know, but I agree it is a bit ugly that the current file's extension is not shown in this list. @bpasero perhaps the list coming in from the mode service can be enhanced with the current file's extension if the current file's extension is not in that list?

I think the workaround for now is to choose "No extension" and just type `file2.csv`. Leaving it to @bpasero if he wants to add automatically the current file extension.

![image](https://user-images.githubusercontent.com/5047891/81715658-c2003000-9478-11ea-9cb2-23bf0dea00fc.png)

**Comment by bpasero** [comment]
This might require help from Electron.

**Comment by bpasero** [comment]
**Verification (Windows, macOS)**
* open a *.csv file
* save as
* you should see CSV file extension as first entry in the dropdown
