### ISSUE TITLE
Test: GitHub authentication for Git commands

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#96280]
Refs: https://github.com/microsoft/vscode/issues/96241, https://github.com/microsoft/vscode/pull/96069

- [x] macOS @misolori
- [x] linux @isidorn
- [x] windows @fiveisprime

Complexity: 3

---

Communication with GitHub for the git features should now be handled automatically by VS Code.

**Note:** Please disable any credential manager you might have installed in your system by unsetting the `credential.helper` git config.

- Clone a private HTTPS repo with the `Git: Clone` commands
- Use the `Git: Pull`, `Git: Push` and `Git: Fetch` commands

At no point in time should you be asked for credentials within VS Code, but instead go through the auth flow similar to the GitHub Pull Requests extension.

Additionally, the same auth integration should be working in the integrated terminal: `git clone`, `git push`, `git fetch`, `git pull` should all work automatically without any prompt for credentials.

Test that you can disable GitHub authentication with the `git.githubAuthentication` setting. Once disabled, you should get prompted for credentials in the quick open UI.

Also test that you can disable the terminal integration with `git.terminalAuthentication` setting. Once disabled, quick open commands should work fine, but terminal shell commands should prompt for auth in the shell itself.

**Comment by fiveisprime** [comment]
Works on Windows. Some thoughts on this:

* The flow is fantastic: the command I run (both via command or terminal) continues after authenticating 💃
* It seems unusual that customers would have credential helper unset. In that case, they'll see the GitHub auth modal instead - cancelling out of that triggers the GitHub extension
* I'm not in love with the message "The extension 'Git' wants to sign in using GitHub." (especially when using the terminal) but I don't have a better suggestion. Are we confident that people will understand what that means?

**Comment by joaomoreno** [comment]
> It seems unusual that customers would have credential helper unset.

Actually, I think this is specifically addressed to those who have nothing configured. And those who do should not have their setup hijacked.

> I'm not in love with the message "The extension 'Git' wants to sign in using GitHub." (especially when using the terminal) but I don't have a better suggestion. Are we confident that people will understand what that means?

Yup, I had the same concerns... we'll just have to wait and see. ;)

**Comment by misolori** [comment]
I had a few hiccups with the initial experience that need some polish. My hypothesis is that advanced users will already be logged in and won't experience this but newer users to VS Code and programming in general will likely hit this more. So if we're able to smooth out that experience I think it'll increase the odds of attaching them as active users.
