### ISSUE TITLE
Scroll highlight text within integrated terminal

### ISSUE THREAD

**Issue by Healthfundr** [Microsoft/vscode#9628]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:52:42.674Z)
- OS Version: Darwin x64 15.5.0

Problem:
Unable to highlight and copy content that is longer than viewable terminal window.

Steps to Reproduce:
1. Launch integrated terminal
2. Produce text within the terminal that requires you to scroll to see all of it.
3. Scroll to the top with mouse
4. Click to highlight from the top
5. Continue to highlight all the content by scrolling down
6. You will be unable to scroll to capture all of the content

Expected behavior:
Should be able to scroll with highlighted content to the bottom of the terminal window.

**Comment by Tyriar** [comment]
Duplicate #9958
