### ISSUE TITLE
Bug: 'Add Cursor Up' Keybind is not adding cursor to above/below lines.

### ISSUE THREAD

**Issue by pr3tori4n** [microsoft/vscode#96292]
It's Not working in Insiders as of time of writing.
Using mousewheel click+drag does work to add cursor to mulitple lines.

- VSCode Version: 1.44
- OS Version: Windows 10

Steps to Reproduce:

1. Open a file
2. Attempt to use Add Cursor Up keybinding (Ctrl + Alt + UpArrow)
2. Attempt to use Add Cursor Down keybinding (Ctrl + Alt + DownArrow)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
What does VS Code detect when you press the desired key combination? 

![keyboard-input](https://user-images.githubusercontent.com/5047891/80482640-da3e5e00-8954-11ea-9583-0f652b0595a8.gif)
