### ISSUE TITLE
Pin folders to top bar, like files

### ISSUE THREAD

**Issue by TlStephen2011** [microsoft/vscode#96291]
It would be nice to be able to pin a folder to the top bar and when you click it, it would show a dropdown of files in the folder. This would allow development without the sidebar open most of the time.

**Comment by TlStephen2011** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Pin tab (#93488)](https://www.github.com/microsoft/vscode/issues/93488)
> * [Some filetypes do not appear on the taskbar jumplist and cannot be pinned (#48688)](https://www.github.com/microsoft/vscode/issues/48688)

It's a different suggestion.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by 5dao** [comment]
hi,this issue could be make better

please vote it 

@bpasero @isidorn @TlStephen2011 @doudou @threeve 

#99415
