### ISSUE TITLE
Provided terminal environment variables override those given explicitly in `vscode.window.createTerminal`

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#96295]
```
Version: 1.45.0-insider (user setup)
Commit: 0778354f3a6a2c21b7f738a5e6b02e2f1c765e73
Date: 2020-04-27T05:42:11.567Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

Steps to Reproduce:

1. In an extension, provide environment variables to `context.environmentVariableCollection`. Accept the changes.
2. Use `vscode.window.createTerminal` to create a terminal with an `env` overriding one of the variables you set
3. Observe that the variable from the context is used

I think variables defined at the time of `createTerminal` should take precedence over the ambient onces set in the context.

Currently in js-debug this prevents us from properly debugging scripts using the integrated terminal whilst auto-attach is on, in the NODE_INSPECTOR_IPC redirects to auto attach's server rather than the one for this specific session.

**Comment by Tyriar** [comment]
Well it was always going to be just something that is placed on top of the environment at the very end. If it's not it gets complicated how the environment is generated and the info popup could be lying.

Here's a workaround, though you would get the stale icon in the new terminal:

```ts
const overridden = ctx.environmentVariableCollection.get('NODE_INSPECTOR_IPC');
window.createTerminal
if (overridden) {
  ctx.environmentVariableCollection.replace('NODE_INSPECTOR_IPC', overridden.value);
}
```

> Currently in js-debug this prevents us from properly debugging scripts using the integrated terminal whilst auto-attach is on, in the NODE_INSPECTOR_IPC redirects to auto attach's server rather than the one for this specific session.

Why doesn't the auto attach method work generally as well?

**Comment by connor4312** [comment]
> Well it was always going to be just something that is placed on top of the environment at the very end. If it's not it gets complicated how the environment is generated and the info popup could be lying.

The environment provided in `createTerminal` is the most local data. Whoever is creating the terminal is explicitly setting those environment variables to enable functionality in the terminal they're setting. I think they should take precedence over the 'ambient' variables otherwise set in the terminal.

> Why doesn't the auto attach method work generally as well?

It works, but the auto attach server isn't using the settings that the launch.json might have. For example, if my launch configu has some specific handling of sourcemaps, the auto attach server doesn't have that handling.

**Comment by Tyriar** [comment]
Just for `replace` you mean? So it would change from:

```
if strictEnv
  Set env as TerminalOptions.env
  Apply env mutations from environmentVariableCollection (this is probably wrong)
else
  Set env as process.env
  Apply env from workspace/user settings
  Apply env from TerminalOptions.env
  Apply env mutations from environmentVariableCollection
```

To:

```
if strictEnv
  Set env as TerminalOptions.env
else
  Set env as process.env
  Apply env from workspace/user settings
  Apply replace mutations from environmentVariableCollection
  Apply env from TerminalOptions.env
  Apply append and prepend mutations from environmentVariableCollection
```

**Comment by Tyriar** [comment]
strictEnv problem: https://github.com/microsoft/vscode/issues/96630

**Comment by connor4312** [comment]
Hmm, yea. Thinking about it more, I see the difficulty for consumers who might use prepend/append; I was coming at it from a key/value perspective... consumers don't have access to apply any other extensions' mutations themselves.

From that POV I the current behavior might be OK. I can modify js-debug to always append and make the bootloader pick the right left-most value in the variable to solve this scenario.

**Comment by Tyriar** [comment]
Ok, well thanks for helping me find the strictEnv bug 🙂
