### ISSUE TITLE
Colors sepcified in the themes are not rendered correctly.

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#9629]
- VSCode Version:
Latest &mdash; 1.3.1
- OS Version:
OS X &mdash; 10.11.3

Hello, 
I  hope you're doing great today.

As I was designing a theme for Code, I noticed what renders is not what I've specified. I know that you may say fonts render with many shading so the final coloring may be changed and that's why I tried every color that I specified and even the background colors rendered incorrectly. 

<img width="477" alt="screen shot 2016-07-22 at 9 04 58 pm" src="https://cloud.githubusercontent.com/assets/2157285/17064117/204cf27c-5050-11e6-8a72-cc64a568a370.png">

I don't know if it's a feature (which if it is, it's really a bad one) or a bug. If this is a bug I really hope that this issue helps you. But if it's part of the architecture; how it applies to colors and how can I choose a color in a way that after your filter it looks the way I want?

Thanks a lot
Pouya

**Comment by pmkary** [comment]
I did a bit more of experimenting, It seems that both Code and Sublime renders the colors same way. Why is that so? And how does one gets the colors they want in the final render?

**Comment by kieferrm** [comment]
@bpasero any idea?

**Comment by pmkary** [comment]
Is that because of the sRGB standard?

**Comment by pmkary** [comment]
I think I found where the problem was, [this link was very good](https://github.com/jibsen/tmcolorconv).

**Comment by bpasero** [comment]
@aeschli fyi
