### ISSUE TITLE
Test: Link provider-based terminal links

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#96299]
Refs: #95081, #90298, #29499

- [x] windows @roblourens
- [x] anyOS @joaomoreno 

Complexity: 4

---

How links in the terminal work have changed a lot this iteration, to enable the new functionality use this setting:

```
"terminal.integrated.experimentalLinkProvider": true
```

Do some experimental testing with links and the hover, here are some places to start:

- Different link types work
  - Revealing folders in current window
  - Opening folders in new window (when the folder is outside the workspace)
  - Opening files
  - Searching the workspace for the link (aka "word" links)
- The new hover text is correct and the link works
- Holding ctrl/cmd vs not holding when hovering
- The link "highlight"
- Alignment of the hover with the editor's hover

Known issues: https://github.com/microsoft/vscode/issues/96266

**Comment by joaomoreno** [comment]
Great job! 👏
