### ISSUE TITLE
Change code.cmd to use "start"

### ISSUE THREAD

**Issue by BrandonKi** [microsoft/vscode#96290]
Change line 5 of code.cmd from
`"%~dp0..\@@NAME@@.exe" "%~dp0..\resources\app\out\cli.js" %*`
to
`start "%~dp0..\@@NAME@@.exe" "%~dp0..\resources\app\out\cli.js" %*`

If "code" is called from a batch file it stops execution of the batch file until VSCode is closed.

**Comment by joaomoreno** [comment]
Sorry @aeschli, forwarding this to you since you seem to know a bit more than me: https://github.com/microsoft/vscode/commit/0dc03a8281e736dd801de7485cf74495175120e2#

**Comment by aeschli** [comment]
Hm, I'd rather not make any changes to not break any integrations.

Also, here's what I tried and what worked for me

- no VSCode instances open, run `code-insiders.cmd` from the command prompt: not blocking
- create `x.bat` file with content `call "pathToCodeInsiders.cmd"`, no VSCode instances open, run `x.bat` from command prompt: not blocking

Please let me know if I misunderstood your use-scenario.

**Comment by BrandonKi** [comment]
This may be some weird windows behavior, but whenever I pass args to `code.cmd` using call, it is blocking. 
An example of this would be a bat file with only `call "path/to/code.cmd" "path/to/file"` .  
However if no args are given it works completely fine for me.
