### ISSUE TITLE
Do dynamic launch configs need extension activation?

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#96297]
Refs: #95837

Since we show the dynamic configuration in subfolders, do extensions need to be eagerly activated, or could we have a contribution in the package.json and lazily activate them via the `onDebugResolve:*` events?

**Comment by weinand** [comment]
We've introduced a new activation event `onDebugDynamicConfigurations` for this.
Please see mock-debug: https://github.com/microsoft/vscode-mock-debug/blob/6be4f5b4b246dafe25f1e1d8ef420f7dccd8f627/package.json#L56

**Comment by connor4312** [comment]
I found that, but am wondering if it's necessary 🙂We only show the debug type "folder" in select menus, and it seems like extensions could indicate that they provide dynamic configurations for a debug type in their package.json. Avoiding eager activation would make startup perceptually faster and would fix https://github.com/microsoft/vscode/issues/96293.

**Comment by weinand** [comment]
We could just check for existence of the activation event `onDebugDynamicConfigurations`: if it exists we would show the dynamic container in the menus but we would not actually activate the extension. Activation would only happen if the dynamic container is actually triggered.

@isidorn what do you think?

**Comment by isidorn** [comment]
@weinand I like that idea a lot.
Let me assign this to April so I change this right now.

**Comment by isidorn** [comment]
@weinand one thing to think about: once the container is choosen we could actually do a type specific activation. So `onDebugDynamicConfigurations:node`.
Without this we would activate all dynamic provider extensions once one is picked. Not the cleanest.
Let me know what you think.

**Comment by weinand** [comment]
Yes please. It is always preferable to have type specific activation.

**Comment by isidorn** [comment]
Ok, so I will only activate the type specific event. I will not set a general event ever.
So that extension can only listen to their type specific one.

**Comment by isidorn** [comment]
Got this working.
However the getDynamicConfigurations is still an async method since we need to get all extensions, and thus #96293 will probably not be fixed.

Also I send out both the general `onDebugDynamicConfigurations` acivation event and the scoped one. Let me know if I should get rid of the general one

**Comment by roblourens** [comment]
It's a little strange that you are using an activationEvent as a signal of whether an extension will contribute something. Seems like it should be something in the contribution section, like a flag on the debugger contribution. It also threw me off that only the extension that contributes the debugger can contribute a debug configuration for that debugger, when usually a different extension could contribute something for another extension's debugger, right?

**Comment by weinand** [comment]
@roblourens 
- yes, using the activationEvent to signal whether an extension will contribute something is somewhat on the edge. I was considering it as an implementation detail (or optimisation). Having a declarative flag on the debugger contribution would be a bit surprising (or redundant) for the new dynamic API. We don't have something like this anywhere else.
- why do you think that only the extension that contributes the debugger can contribute a dynamic debug configuration for that debugger? That was not the idea and if this is true it would be a bug. @isidorn is this true?

**Comment by isidorn** [comment]
@weinand this should work for all extensions - I look at all the extensions, not only the debug ones. If it does not work it is a bug and can you please file a new one and I can investigate more. Thanks

**Comment by weinand** [comment]
@isidorn the question is: if there is a `onDebugDynamicConfigurations` specified for a non-debugger extension, under what name will the container item appear in the Quickpick?

**Comment by isidorn** [comment]
So I take it back I was wrong in my previous comment, just double checked the code. Since it that contribution has no `type`, it has no label and we do not show it.
Code pointer https://github.com/microsoft/vscode/blob/2e80a8f99e239a712d58081b2fbc6ceafd03f176/src/vs/workbench/contrib/debug/browser/debugConfigurationManager.ts#L252

So we only support extensions that contribute a debugger type at least.

**Comment by weinand** [comment]
@isidorn in https://github.com/microsoft/vscode/issues/96297#issuecomment-621076971 you suggested that the activation event has a type (`onDebugDynamicConfigurations:node`) and in https://github.com/microsoft/vscode/issues/96297#issuecomment-621123650 you even said that you only support activation for a specific type.

So I suggest you use the "type" on the activation event to find the debugger's name for the "folder" container item in the quick pick.

**Comment by isidorn** [comment]
That could work but is a bit ugly. Created this issue for that which I will tackle once there is a use case for this. @roblourens let me know if you are already hitting this limtation
https://github.com/microsoft/vscode/issues/96905

**Comment by weinand** [comment]
@isidorn I don't think that this is any more ugly than the use of `onDebugDynamicConfigurations` at all. It is just a fix for the current incomplete implementation.

Use case: I have the use case already in my "Nodebook" where I need to contribute a dynamic debug configuration from the nodebook extension for the existing Node debugger.
Without the fix I'm blocked.
