### ISSUE TITLE
Editor.renameOnType: true

### ISSUE THREAD

**Issue by FatTonyy** [microsoft/vscode#96301]
This works only on html but not on jsx, I dunno about vue though since I never used it.

- VSCode Version: 1.44
- OS Version: windows

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by IllusionMH** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/94316

It's implemented only for HTML at this point.

JSX requires additional work as described in linked issue. Vue extension would need to implement support when API is finalized.
