### ISSUE TITLE
Test: profiling termination conditions and state

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#96305]
Refs: https://github.com/microsoft/vscode-js-debug/issues/415

- [x] anyOS @egamma
- [x] anyOS @dbaeumer

Complexity:  3

---

Profiling (which you can start via the "Take Performance Profile" command or context menu item) now supports a couple termination conditions:

 - Manual -- run the profile until manually stopped
 - Interval -- run the profile for an amount of time, or until manually stopped.
 - Breakpoints -- run the profile until a breakpoint is hit, or until manually stopped. The user can choose one or more breakpoint to run until.

Please verify each of these. I have a [demo script](https://github.com/microsoft/vscode-js-debug/blob/master/demos/node/main.js) that does some busy-work which I've been using to profile.

Observe some states while profiling:

 - If you start while paused on a breakpoint, starting the profile should continue the debugger
 - Breakpoints should not be hit and should be marked unverified (the "unfilled" circle state), _with the exception of_ any breakpoints used in the "Breakpoints" termination condition. These should remain verified, and hitting one should keep the debugger paused and open the profile.
 - Setting a breakpoint while the profile is running should keep it as unverified.
 - After the profile completes, breakpoints should be re-verified and can be hit again. Any breakpoints set while the profile is running are also verified at this point.
 - `debugger;` statements should stop the debugger in the "breakpoints" condition, and be ignored otherwise.

**Comment by egamma** [comment]
>Profiling (which you can start via the "Take Performance Profile" command or context menu item)

@connor4312 sry, but I cannot find this command, what context menu are you referring to? Is there additional setup needed? Do I need an extension?

**Comment by dbaeumer** [comment]
@egamma thanks for this. The context menu entry is here:

<img width="301" alt="capture" src="https://user-images.githubusercontent.com/1931590/80495634-73c33b00-8968-11ea-80ef-e45173839aaa.png">

**Comment by egamma** [comment]
The commands are in the Call Stack's Context menu.
