### ISSUE TITLE
The terminal process command 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed to launch (exit code: {2})

### ISSUE THREAD

**Issue by mickeyegp73** [microsoft/vscode#96304]
Cannot open terminal. The following message appears 
The terminal process command 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed to launch (exit code: {2})

**Comment by mickeyegp73** [comment]
Tried but not working

**Comment by Tyriar** [comment]
Do you have anti-virus software that could be blocking the terminal? If so try following the instructions in https://code.visualstudio.com/docs/editor/integrated-terminal#_how-do-i-fix-the-errors-connectnamedpipe-failed-windows-error-232-or-terminal-exited-with-code-x-on-windows

/label needs-more-info integrated-terminal

**Comment by JacksonKearl** [comment]
^ no dashes in "needs more info".

**Comment by mickeyegp73** [comment]
I can open the terminal from the command line but from the vscode cannot is there a solution for that? 
What kind of more info needed?

**Comment by Tyriar** [comment]
@mickeyegp73 https://github.com/microsoft/vscode/issues/96304#issuecomment-620595268
