### ISSUE TITLE
Relative symlinks fail to update when enclosing folder is moved to a different depth.

### ISSUE THREAD

**Issue by kingces95** [microsoft/vscode#96303]
- VSCode Version: 
> Version: 1.45.0-insider
Commit: a250df703de955a38aed427a917bce8278ab3331
Date: 2020-04-24T20:46:59.782Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

- OS Version:
![image](https://user-images.githubusercontent.com/4120386/80271377-6867cb00-865b-11ea-8c69-979f015e37a9.png)

Steps to Reproduce:
1. Create a `foo/test.js`
2. Create a symbolic link to `foo/` named `bar/`
3. Create a folder `baz`
4. Move `bar` into `baz`

Expect the relative link `baz/bar/test.js` to be updated so that it points to `foo/test.js` but actually the link is not updated and is broken.

Source: [symlink.zip](https://github.com/microsoft/vscode/files/4532365/symlink.zip) -- You just have to create `baz` and then move `bar` into it.

[Video](https://youtu.be/ecZcqARRExc)

Does this issue occur when all extensions are disabled? Yes

Created with same environment as #96114

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by kingces95** [comment]
Oh, no! Into the backlog! Hehe. 

Well, the case that this is a bug is that (1) the UI already has those little arrow indicators for linked files and (2) supports moving directories. Without supporting moving directories that contain links, VSCode is straddling the symlink support fence -- on one side we get the little arrow and on the other side we don't get to move directories.

Also, the git client for windows took great pains to provide UI for automating enabling symlinks. And it could only do that because windows allowed symlinks in developer mode. Seems a shame the reset of the tool chain went through all the trouble to enable symlinks in their tools but we come up just a tad short in the editor.

So, that's my pitch! Happy triaging!

**Comment by isidorn** [comment]
Ok, let me assign a bug label.

**Comment by kingces95** [comment]
@isidorn, oh, happy day! Thanks. Here are a few more issues that could be fixed as part of symlink mini bug bash #96648
