### ISSUE TITLE
Test: ExtensionContext.environmentVariableCollection UX

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#96300]
Refs: #46696, #95573 

- [x] macOS @chrisdias
- [x] Windows @gregvanl

Complexity: 3

---

The UX side of this API is done. An extension can contribute environment changes to terminals via this API:

https://github.com/microsoft/vscode/blob/686ad172176f48eaef00d9e128d0fc0e999bbd52/src/vs/vscode.proposed.d.ts#L1047-L1053

The API itself was tested last month, this month focus on the UX side of things with the indicator that appears in the top-right of each terminal, the hover and the relaunch terminal command.

![image](https://user-images.githubusercontent.com/2193314/80433078-cb9b6c80-88aa-11ea-878a-dc8cf1e6d69f.png)

Use the Update Environment and Clear Environment commands in this extension as a place to start: https://github.com/microsoft/vscode-extension-samples/tree/master/terminal-sample

**Comment by gregvanl** [comment]
Just a testing note on Windows. Noodling around relaunching terminal may hang the editor due to https://github.com/microsoft/vscode/issues/76548
