### ISSUE TITLE
Test proposed custom editor API 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#96315]
Refs #77131 

- [ ] Mac @alexdima 
- [ ] Linux @deepak1556
- [x] Windows @roblourens

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%2396315%0A%0A)

---

Test using the updated custom editor API proposal from #77131. To be clear, this is the proposal for full custom editors (such as for binary editors) and not the already finalized api for custom text editors

**Overview**
This iteration we again reworked the custom editor API proposal to better align it with the notebook api and also help implementers. For this exploratory test plan item, your goal is to try using the API and try to find bugs in our custom editor implementation. I've intentionally left this open ended. 

Areas to focus on:

- Do custom editors behave like normal editors for save, edit, and revert?

- Try using `supportsMultipleEditorsPerDocument` with your custom editor.
    - When this setting is disabled, ensure you can't get into a state where more than one copy of the editor is opened for a single document.
    - When it is disabled, make sure splitting and other operations work as expected

- Backup
     - Make sure your extension can back up the resource and that these are properly restored
     - Make sure VS Code calls dispose on the backup when you would expect

**Resources**
Sample custom editor extension to build on (it's the "paw draw" editor): https://github.com/mjbvz/vscode-extension-samples/tree/custom-editor-examples

**Comment by roblourens** [comment]
@mjbvz which backups are referred to here? It looks like vscode decides when CustomDocumentBackups are deleted, is that correct?

```
 * During `revert`, your extension should also clear any backups for the custom editor. Backups are only needed
* when there is a difference between an editor's state in VS Code and its save state on disk.
```

**Comment by mjbvz** [comment]
That's actually an out of date comment. VS Code will now call `.delete` on the current backup for you. I'll fix the comment

**Comment by alexdima** [comment]
Here is my status on this: I started testing and then looked to integrate a hex editor into vs code, but I couldn't find one that works well, so I started building one. But building one is taking quite some time. So, this item will leak through to the debt week for me, I'm sorry about that.

If you want more timely feedback, please also assign someone else.

**Comment by roblourens** [comment]
I also tried to build a real custom editor, then realized that I would spend more time with my code than the API 😆

**Comment by deepak1556** [comment]
In my case, I am building a custom editor for chromium cache files `<User-data-dir>/Cache` and I can't seem to finish it in the testing week. I will also continue exploring in debt week. For now I can sign-off with verifying the sample extension provided, if thats required.

**Comment by roblourens** [comment]
This one shouldn't have had its milestone moved. Did you finish testing @alexdima and @deepak1556? We have 5 extra points now.

**Comment by mjbvz** [comment]
I think this one should be left in the April milestone. I created a new test plan item for this iteration: #99003
