### ISSUE TITLE
Test: "Reopen with" command and Editor Associations

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#96312]
Refs: #94408

- [ ] anyOS @alexdima
- [x] anyOS @roblourens

Complexity: 4
Authors: @mjbvz @rebornix 

----

This iteration, we made "File: Reopen With..." and setting `workbench.editorAssociations` options generic , which can be used for both Custom Editor and Notebook. 

*Setup*

* Install the [Github issue notebooks](https://github.com/microsoft/vscode-github-issue-notebooks extension
* Create a mock custom editor which can open `*.github-issues` files:
  * clone https://github.com/microsoft/vscode-extension-samples/tree/master/custom-editor-sample
  * modify the file association from https://github.com/microsoft/vscode-extension-samples/blob/master/custom-editor-sample/package.json#L29 to `*.github-issues`
  * `npm run compile`
* Debug the custom editor sample extension.
* Create a `test.github-issues` file from File Explorer
* Turn off auto save (saving will save content to the disk and then the file format may not be opened by custom editor or notebook correctly as their schema are different)
* Open `test.github-issues`

*Test*

* Make sure you can use "File: Reopen with..." to switch between text editor, custom editor and notebook
  * Make sure that you can configure which editor to be the default editor to open by clicking the gear icon on the entry in the quick pick
  * Make sure that closing the editor and reopen again will respect the setting
* Open `settings.json`
  * Edit `workbench.editorAssociations`, make sure IntelliSense works and give all avaibable options including GitHub issues notebook and the custom editor you wrote.

**Comment by rebornix** [comment]
@alexdima @roblourens I updated the set up steps in detail, let me know if it's still difficult to setup or any step is confusing. Enjoy:)

**Comment by roblourens** [comment]
There are other ways to end up with two tabs by clicking around, probably all the same as #96454. Otherwise looks great!

**Comment by alexdima** [comment]
:+1: Works well!
