### ISSUE TITLE
Intellisense tip "Process keyword" was not localized 

### ISSUE THREAD

**Issue by Wanye1062271859** [microsoft/vscode#96325]
- VSCode Version: 1.44.2
- OS Version: Windows x64 10.0.18363
- Language: Non-English

Steps to Reproduce:
1. Open a workspace which contains a .cpp file
2. Open a cpp file
3. Type "#include" in the cpp file

Expected:
The intellisense tip "Process keyword"  was localized 

Actual:
"Process keyword" was not localized 
![image](https://user-images.githubusercontent.com/29274719/80442415-68a7e500-893f-11ea-9571-b2d373f16934.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
This only happens when you have the C++ extension installed.
