### ISSUE TITLE
[seti] icon for postcss

### ISSUE THREAD

**Issue by jibberishclient** [microsoft/vscode#96326]
I've configured my .css extension to map to postcss syntax in VS Code. However, once I do so in the JSON settings I lose my default icons:

![image](https://user-images.githubusercontent.com/11995299/80442493-02897680-88db-11ea-98a4-6c74d8d68ace.png)

Is there a way to configure a single icon for a particular file extension preferably without a 3rd party plugin? vscode-icons seems to override the existing seti icon set.

**Comment by roblourens** [comment]
So if I set this, should notebook.css still have the css icon?

![image](https://user-images.githubusercontent.com/323878/83696262-a264af00-a5c1-11ea-8b9d-befa0ffe1775.png)

Normally looks like this

![image](https://user-images.githubusercontent.com/323878/83696271-a85a9000-a5c1-11ea-8742-0237c24b12b2.png)

**Comment by roblourens** [comment]
It does if I actually install the postcss language extension

**Comment by aeschli** [comment]
Oh, yes, there needs to be some extension that defines the language
