### ISSUE TITLE
The keyboard shortcut doesn't work on setting UI window

### ISSUE THREAD

**Issue by Wanye1062271859** [microsoft/vscode#96324]
- VSCode Version: 1.44.2
- OS Version: Windows x64 10.0.18363

Steps to Reproduce:
1. Open Setting UI page
2. Expand Text Editor node and switch to Cursor node
3. Click on the item "Cursor Blinking"
4. Press Shift+F9 to invoke More Actions...

Expected:
The following action list show up
![image](https://user-images.githubusercontent.com/29274719/80441613-d8b56b80-893d-11ea-99df-4b57623a559b.png)

Actual:
Nothing happen

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
This works for me. After

> Click on the item "Cursor Blinking"

It won't work if the dropdown is expanded, you will have to close it first. Is that the case for you?

**Comment by Wanye1062271859** [comment]
Hi roblourens, 
Click on the item "Cursor Blinking". Only the icon "More actions ..." is displayed, and the drop-down list is not expanded.

**Comment by roblourens** [comment]
The dropdown needs to be focused though, are you sure that it is focused? It should have an outline. Where do you click when you say "click on the item..."?

**Comment by Wanye1062271859** [comment]
Yes, when the gear icon is displayed, then I pressed the shortcut key "Shift+F9".
![image](https://user-images.githubusercontent.com/29274719/80579635-f5849880-8a3c-11ea-9480-6b58361ee0ed.png)

**Comment by roblourens** [comment]
It looks like the dropdown is not focused though. Just clicking on the item itself isn't sufficient unfortunately.
