### ISSUE TITLE
Global search is too slow

### ISSUE THREAD

**Issue by HuXiaoTu** [microsoft/vscode#96329]
Issue Type: <b>Performance Issue</b>

search err，Global search is too slow，Console error：Failed to load resource: the server responded with a status of 500 (Internal Server Error)

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   101	  6328	code main
    0	   184	   216	   window (undefined)
    0	    25	  5564	   utility
    4	    74	 11852	   shared-process
    3	   219	 12216	   gpu-process
    1	   221	 12428	   window (gisWeather - Visual Studio Code)
    0	    62	  6792	     extensionHost
    0	    51	  9876	       electron_node tsserver.js 
    0	   260	  9892	       electron_node tsserver.js 
    0	    52	  1256	         electron_node typingsInstaller.js typesMap.js 
    0	    42	 12792	       "C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=6792
    0	    10	 10580	     watcherService 
    0	    11	  8428	       console-window-host (Windows internal process)
    0	    34	 13436	     searchService
    0	    14	 13664	   electron-crash-reporter
    0	    65	 13820	   window (问题报告程序)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (gisWeather - Visual Studio Code)
|    Folder (gisWeather): 14122 files
|      File types: json(10844) js(1122) png(483) vue(255) gif(169) css(136)
|                  html(87) jpg(75) map(62) md(54)
|      Conf files: package.json(3) grunt.js(1);
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.44.2

</details>

**Comment by roblourens** [comment]
Can you give more details? Do any of these tips help? https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory
