### ISSUE TITLE
Comment on Folder or File

### ISSUE THREAD

**Issue by qkreltms** [microsoft/vscode#96331]
For now comment is possible  on code blocks like
```js
// Do something
function doSomething() {
}
```
I'm looking for comment on file or folder when mouse is over them when I wrote comment on it then It would appears like
![12](https://user-images.githubusercontent.com/25196026/80446199-2ab3bc80-8951-11ea-834a-f91eb9b50b2a.png)

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
