### ISSUE TITLE
Semantic coloring issues for SPGoding.datapack-language-server extension

### ISSUE THREAD

**Issue by SPGoding** [microsoft/vscode#96332]
I currently only have this issue with my [SPGoding.datapack-language-server](https://marketplace.visualstudio.com/items?itemName=SPGoding.datapack-language-server) extension, however this is not a bug of this extension because the information shown in `Developer: Inspect Editor Tokens and Scopes` is correct (or I might misunderstood something?).

## The Problem

At first everything looks great. However, after rapidly deleting a whole line (by `Ctrl + X`) and then undoing it (by `Ctrl + Z`), the text might lose its color, though the `Developer: Inspect Editor Tokens and Scopes` tool told me that they still have the correct semantic tokens and modifiers.

![img](https://i.imgur.com/QJzCVXL.gif)

## Background

My legend ([permalink](https://github.com/SPGoding/datapack-language-server/blob/3a47904ca2f99a86cc6617b302ae820460ebc069/src/client.ts#L96)):
```typescript
new SemanticTokensLegend(
    ['annotation', 'boolean', 'comment', 'entity', 'keyword', 'literal', 'identity', 'number', 'operator', 'property', 'string', 'type', 'variable', 'vector'],
    ['declaration', 'deprecated', 'documentation', 'firstArgument']
)
```

My `package.json` semantic contributions ([permalink](https://github.com/SPGoding/datapack-language-server/blob/3a47904ca2f99a86cc6617b302ae820460ebc069/package.json#L2081)):

```json
"semanticTokenTypes": [
    { "id": "annotation", "description": "An annotation in doc comments" },
    { "id": "boolean", "description": "A real boolean value" },
    { "id": "entity", "description": "An entity or a score holder" },
    { "id": "literal", "description": "A literal argument" },
    { "id": "identity", "description": "A namespaced ID" },
    { "id": "vector", "description": "A vector" }
],
"semanticTokenModifiers": [
    { "id": "firstArgument", "description": "The first argument in a command" }
],
"semanticTokenScopes": [
    {
        "language": "mcfunction",
        "scopes": {
            "annotation": ["support.type.doc.annotation.mcfunction"],
            "boolean": ["constant.language.boolean.mcfunction"],
            "entity": ["support.class.entity.mcfunction"],
            "literal": ["keyword.other.mcfunction"],
            "literal.firstArgument": ["keyword.control.mcfunction"],
            "identity": ["entity.name.function.mcfunction"],
            "vector": ["constant.numeric.vector.mcfunction"]
        }
    }
]
```

## Test Repository

I've made a test repository in case you need it: https://github.com/SPGoding/vscode-96332

## Info

VS Code version: Code - Insiders 1.45.0-insider (0778354f3a6a2c21b7f738a5e6b02e2f1c765e73, 2020-04-27T05:42:11.567Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (0.95GB free)|
|Process Argv|C:\SPGoding\Projects\SPGoding\Typescript\datapack-language-server.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
vscode-autohotkey-plus|cwe|2.3.8
vscode-eslint|dba|2.1.5
ghlink|dt|1.2.0
vscode-npm-script|eg2|0.3.11
todo-tree|Gru|0.0.173
vscode-test-explorer|hbe|2.18.0
vscode-edit-csv|jan|0.2.6
Kotlin|mat|1.7.1
rainbow-csv|mec|1.7.0
vscode-language-pack-de|MS-|1.45.0
vscode-language-pack-fr|MS-|1.45.0
vscode-language-pack-zh-hans|MS-|1.45.0
python|ms-|2020.4.76186
remote-wsl|ms-|0.44.2
vscode-typescript-tslint-plugin|ms-|1.2.3
java|red|0.60.0
vscode-yaml|red|0.7.2
shader|sle|1.1.4
datapack-json|SPG|2.0.10
datapack-language-server|SPG|2.0.0
vscode-mc-shader|Str|0.8.5
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2
vscode-icons|vsc|10.1.1
markdown-all-in-one|yzh|2.8.0

</details>

Does this issue occur when all extensions are disabled?: No

**Comment by SPGoding** [comment]
Is there any more information I should provide to help you guys locate the issue? @aeschli

**Comment by alexdima** [comment]
I can see the following exception in the developer tools:

```
  ERR Invalid typed array length: -4294967171: RangeError: Invalid typed array length: -4294967171
    at new Uint32Array (<anonymous>)
    at F._setDocumentSemanticTokens (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2635:864)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2634:870
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

By breaking on error, I can see the following:

![image](https://user-images.githubusercontent.com/5047891/81055149-6b1eb780-8ec8-11ea-842c-713176770852.png)

So it looks like the returned semantic tokens edits are illegal, in this case they ask to delete very many tokens.

**Comment by alexdima** [comment]
@SPGoding Can you please check on your side in the semantic tokens edit computation logic you have? 

(The inspector does not reveal problems with the token edits because the inspector makes a separate full document request)

**Comment by SPGoding** [comment]
Thanks for your help!

> (The inspector does not reveal problems with the token edits because the inspector makes a separate full document request)

That totally makes sense. So this isn't an issue with VS Code, I will close this issue. Sorry for disturbing!
