### ISSUE TITLE
Advice / Best Practices request: React / JSX / eslint setup

### ISSUE THREAD

**Issue by MrSkinny** [Microsoft/vscode#9633]
- VSCode Version: 1.3.1
- OS Version: 10.11.5

I really like VSC and it's interesting when you start a Typescript project how everything seems to light up in terms of linter/debugging without any config.

But using ES6, JSX, etc. I'm having a really hard time getting the editor to cooperate. Would love to see a Best Practice guide here for what is a common great setup for a React JSX project (not exactly an 'under-the-radar' tech).  

I tried the popular ESLint extension and out of the box it's popping up annoying "React is defined but never used" because JSX calls `React.createElement` but that's obviously not present in the file. Even if this is an ESLint problem, I'd love to hear the VSC community's solutions for this.

Sorry if Github Issues ain't the right place for this, but [Idea Board](https://visualstudio.uservoice.com/forums/293070-visual-studio-code) only suggests here for  discussions.

**Comment by egamma** [comment]
@MrSkinny we have some documentation on this:
https://code.visualstudio.com/docs/languages/javascript

https://code.visualstudio.com/docs/languages/javascript#_javascript-linters-eslint-jshint
https://code.visualstudio.com/docs/languages/javascript#_jsx-and-react-native

Does this cover your needs? If not what is missing?

**Comment by vanflymen** [comment]
@egamma, the [javascript documentation](https://code.visualstudio.com/docs/languages/javascript) is convoluted and (in parts) vague for someone starting out. It may be better to have a separate section/page for React that explicitly explains how to set up VSCode for a React project.

For example, could you please clarify what this means:

> If your project has a jsconfig.json file, then make sure that typings is contained in the project context defined by the location of the jsconfig.json file. If you have no jsconfig.json, then you need to manually add a /// reference to the .d.ts from each JavaScript file.

**Comment by MrSkinny** [comment]
I'd also love to see some advice on getting rid of unused var errors on `React` and defined components when they're only used inside JSX.  I realize this is an ESLint problem, but was unable to find good solution on their side.

**Comment by egamma** [comment]
Thanks for the feedback, moving the issue over to vscode-docs.

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-docs#484
