### ISSUE TITLE
Workspace symbol search broken

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96336]
* see attached screen shot (latest insider, latest ts)

<img width="1000" alt="Screenshot 2020-04-28 at 08 55 13" src="https://user-images.githubusercontent.com/1794099/80456512-ff6ba600-892d-11ea-9fa6-962bcde58465.png">

**Comment by mjbvz** [comment]
This is be fixed for the newer TS versions we are now using in the VS Code workspace. Please make sure you are using TS 3.9.0-20200427+
