### ISSUE TITLE
Cant' close "Search In Files (Ctrl + Shift + F)" Functionality

### ISSUE THREAD

**Issue by ZackPlauche** [microsoft/vscode#96334]
Issue Type: <b>Bug</b>

1. Press Ctrl+Shift+F
2. Press every button on the search to try to close it.
3. Press Ctrl+Shift+F again to try to close it.
4. Realize you can't intuitively close it without switching to another left bar menu.
![image](https://user-images.githubusercontent.com/43456955/80452155-53768a80-892e-11ea-81fd-271390ed7c07.png)

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.29GB free)|
|Process Argv|C:\Users\zackp\Desktop\template|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.20.0
python-extension-pack|don|1.6.0
auto-rename-tag|for|0.1.2
day-night-theme-switcher|fre|0.1.2
MagicPython|mag|1.1.0
python|ms-|2020.4.76186
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.6

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
@ZackPlauche to toggle the Side Bar use [Ctrl+B](https://code.visualstudio.com/docs/getstarted/userinterface#_basic-layout). Or in your specific case, click on the Search button  in the Activity Bar to toggle between showing and hiding it in the Side Bar.

**Comment by gjsjohnmurray** [comment]
Context menu is another way:
![image](https://user-images.githubusercontent.com/6726799/80470244-a1dd5680-8939-11ea-8863-491d0bedaf3a.png)

**Comment by roblourens** [comment]
Another way is to drag it like you are resizing the sidebar, but resize it all the way until it's hidden.
