### ISSUE TITLE
[Code completion] don't close popup on cursor left/right

### ISSUE THREAD

**Issue by mojo2012** [microsoft/vscode#96333]
I'm a long term user of Eclipse and one of the things I really miss when using VSCode is that the autocomplete popup closes when pressing cursor left or right.
The behaviour is best understood with two little gifs

Eclipse:
![eclipse_autocomplete](https://user-images.githubusercontent.com/1330361/80450568-11dfe280-8922-11ea-98d3-d42e79e0a817.gif)

VSCode:
![vscode_autocomplete](https://user-images.githubusercontent.com/1330361/80450468-df35ea00-8921-11ea-8a66-7141c63a5eb9.gif)

The way Eclipse does this is way more intuitive an reduces distraction from what you actually want to achieve (like looking for a method that is quite similar than the one you already selected.

**Comment by berry120** [comment]
Ah yes, echoing my support for this - wanted it for a while.

**Comment by setu9760** [comment]
Absolutely yes to this.

**Comment by jrieken** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/3295
