### ISSUE TITLE
Restarting TS server is unintentionally saving a file

### ISSUE THREAD

**Issue by ravshansbox** [microsoft/vscode#96338]
Issue Type: <b>Bug</b>

When I have unsaved changes to a file and I restart TS server, file is being saved without my intention.

VS Code version: Code - Insiders 1.45.0-insider (abb4a35cfc26102f93fd00df7b59ce1a19c2017a, 2020-04-28T05:34:21.109Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|-psn_0_5944747|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
prettier-vscode|esb|4.5.0
vscode-styled-components|jpo|0.0.29

</details>

**Comment by mjbvz** [comment]
https://github.com/microsoft/vscode/blob/3f0aeab1ca42cc732eb83107fa1e6c93d81d872d/extensions/typescript-language-features/src/typeScriptServiceClientHost.ts#L178

Looks like it has been this way for a while but we can check if this workaround is still needed

**Comment by mjbvz** [comment]
Fixed by 986a9c8bc9425fbed40794302472d8798105a46a
