### ISSUE TITLE
angular i18n pluralization breaks html formatter

### ISSUE THREAD

**Issue by Shigerua** [microsoft/vscode#96343]
- VSCode Version: 1.44.2
- OS Version: Windows 10 64bit

Steps to Reproduce:

1. Create an new html file
2. Put this code somewhere in the html file
```
   <div *ngIf="currentPeriodType === '0'">{currentMultiplier,
    plural, =1 {{{currentMultiplier}} Day} other {{{currentMultiplier}} Days} }
   </div>
```
3. Try to format your html file

The html code gets formatted well till the pluralization. After this line the code doesn't get formatted anymore. Looks like vs code html formatter can't handle this syntax.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying HTML formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?
