### ISSUE TITLE
C# syntax highlighting is broken by multiline types

### ISSUE THREAD

**Issue by svenskmand** [microsoft/vscode#96341]
- VSCode Version:
Version: 1.44.2 (system setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
- OS Version: Windows 10

Steps to Reproduce:

1. Open a new C# file and input the following code
```
namespace Foo {
	public interface IBar<T> {
		IList<T> Baz(IList<IList<IList<IList<IList<IList<
		IList<IList<T>>>>>>>> foobar);		
	}	
}
```
2. The type of the `foobar` variable and the rest of the method has a white text color and no syntax highlighting.

This is how the syntax highlighting looks before the line break:
![Without line break]( https://snipboard.io/njzfVS.jpg )

This is how the syntax highlighting looks with the line break:
![With line break]( https://snipboard.io/9Hg4QU.jpg )

Does this issue occur when all extensions are disabled?: Yes

**Comment by svenskmand** [comment]
PS: can I upload pictures to show the problem without having to host the images myself? As far as I can see I can only add an image using an url.

**Comment by alexr00** [comment]
Moved to owning repo https://github.com/dotnet/csharp-tmLanguage/issues/179

**Comment by svenskmand** [comment]
> 
> 
> Moved to owning repo [dotnet/csharp-tmLanguage#179](https://github.com/dotnet/csharp-tmLanguage/issues/179)

Thanks :)
