### ISSUE TITLE
Unhappy account picker

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96348]
re #96226

* Logged in with Github
* Setting up pref sync
* :bug: the account picker mixes accounts I am logged in to with account providers. What are the odds that I don't want to use the existing provider?

<img width="747" alt="Screenshot 2020-04-28 at 10 55 03" src="https://user-images.githubusercontent.com/1794099/80468403-6c3b6c00-893f-11ea-8371-3e15ccc9ed74.png">

IMO it should be
```
------------------------------------------------
jrieken (GitHub)                      logged in
------------------------------------------------
Login with Microsoft                      others
Login with GitHub
```

So, have a group for account I am logged in to and have a group for providers

**Comment by sandy081** [comment]
@misolori Any suggestions for this? There is another scenario that there are multiple logged in accounts.

**Comment by sandy081** [comment]
<img width="626" alt="image" src="https://user-images.githubusercontent.com/10746682/80508250-1b943500-8978-11ea-9421-026c11c4afb1.png">

<img width="611" alt="image" src="https://user-images.githubusercontent.com/10746682/80508334-36ff4000-8978-11ea-9ae1-67fb2cad6100.png">


<img width="624" alt="image" src="https://user-images.githubusercontent.com/10746682/80508069-dcfe7a80-8977-11ea-8c2a-01f78ca07672.png">


<img width="613" alt="image" src="https://user-images.githubusercontent.com/10746682/80508593-86457080-8978-11ea-931e-8b805aa1549e.png">

Feedback 🔝 ?

**Comment by misolori** [comment]
I like the proposed UI much better 👍
