### ISSUE TITLE
system interrupts process spikes upon search

### ISSUE THREAD

**Issue by thatandyrose** [microsoft/vscode#96349]
Issue Type: <b>Performance Issue</b>

Hi guys, I started noticing this yesterday while doing a global search on my project in vscode.

I've searhed on this project millions of times, nothing different. But yesterday I noticed it being VERY slow.

When I checked my processes, I saw that, during the search (and only during the search) the System Interrupts process just stayed at 100%.

As soon as the search ends (which takes way longer than normal) CPU usage for that process goes down again to like 5% total.

I'm on Windows 10 Version 10.0.18363.778.

The only other bit of info I can provide is I updated Windows recently ,these are the most recent updates.

https://support.microsoft.com/en-us/help/4549951/windows-10-update-kb4549951

I'm only reporting this to you guys since the ONLY trigger for this System Interrupts process CPU usage is VSCode search... 

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.71GB free)|
|Process Argv|--disable-gpu --disable-gpu --disable-gpu-compositing|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    68	  3632	code main
    0	    23	  1820	   utility
    0	    60	  5132	   gpu-process
    1	    69	 14644	   window (Issue Reporter)
    0	    13	 15744	   electron-crash-reporter
    0	   229	 17092	   window (landing_page_settings_serializer.rb - SnipInt - Visual Studio Code)
    0	     6	  1324	     console-window-host (Windows internal process)
    0	    14	  2188	     watcherService 
    0	     5	  6348	       console-window-host (Windows internal process)
    0	    67	  4264	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     5	 17616	       "C:\HashiCorp\Vagrant\bin\vagrant.exe" ssh
    0	    57	 11260	         ruby C:\HashiCorp\Vagrant\embedded\gems\2.2.5\gems\vagrant-2.2.5\bin\vagrant ssh
    0	     7	 12492	           C:\WINDOWS\System32\OpenSSH\\ssh.EXE vagrant@127.0.0.1 -p 2222 -o LogLevel=FATAL -o Compression=yes -o DSAAuthentication=yes -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i C:/Users/thata/projects/SnipInt/.vagrant/machines/default/virtualbox/private_key
    0	    36	  8572	     searchService
    0	    66	 10520	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     5	 11912	     console-window-host (Windows internal process)
    0	    46	 21952	     extensionHost
   13	    65	 19056	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (landing_page_settings_serializer.rb - SnipInt - Visual Studio Code)
|    Folder (SnipInt): 15727 files
|      File types: cache(8596) json(1785) rb(1438) slim(303) coffee(261)
|                  js(243) scss(136) vue(112) png(83) map(66)
|      Conf files: package.json(1) tsconfig.json(1);
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
erb|Cra|0.0.1
gitlens|eam|10.2.1
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
html-slim-scss-css-class-completion|gen|1.7.4
vscode-colorize|kam|0.8.16
VS-code-vagrantfile|mar|0.0.7
remote-wsl|ms-|0.44.2
vetur|oct|0.24.0
slim|sia|0.1.2

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
I'm not sure about "system interrupts", do you see other processes using high CPU during that time too? rg.exe?

**Comment by thatandyrose** [comment]
hey @roblourens thanks for following up on this.

Hmm so you know what... I could not replicate the System Interrupts high CPU usage (although I have observed it several times ONLY when searching in VSCode).

However, what I can CONSITENTLY replicate is VERY SLOW searching, and yes, high rg.exe usage or, for some reason, high Windows Defender usage... but, ONLY when searching in VSCode? 🤔

I wouldn't think this was a VSCode issue EXCEPT the search is VERY slow and it the high cpu usage only happens when I search in VSCode? 🤔

I recorded a video here for you to see. In the video I do 3 searches... you'll notice they are very slow, BUT rg.exe only kicks in on the 2nd search.

https://www.loom.com/share/f5e4e5b0e417467aa9423e9768370f60

Any ideas? 🤔

**Comment by roblourens** [comment]
Yeah, Windows Defender likes to kick in while searching, and slow it down significantly. You might have some luck if you exclude your dev folder in Windows Defender.

**Comment by thatandyrose** [comment]
hey @roblourens thanks so much... just a question. What is rg.exe and why would I have not seen this behaviour before do you think? The weird thing is, it's never happened before? Any ideas?

thanks again for your help!

**Comment by roblourens** [comment]
rg.exe is the process that actually does the search. It should be using high CPU, the fact that it's not shows that it's being throttled by Windows Defender. Unfortunately I have no idea why Defender does what it does, you are not the only person to report an issue like this and I wish there was some rhyme or reason to it, sorry.
