### ISSUE TITLE
Subrepos disappear from source control view

### ISSUE THREAD

**Issue by sveinse** [microsoft/vscode#96342]
- VSCode Version: 1.44.2
- OS Version: Win 10.0.18363

Steps to Reproduce:

1. Create a new empty directory and open in VSCode
2. Open terminal and enter `git init sub1`. Observe that the source control view will show the repo
3. Enter `git init sub2` and observe the source control view
4. Enter `git init .` and observe that the new top-repo has been added with total 3 repos available (as expected)
5. Restart VSCode
6. Observe that `sub1` and `sub2` is now gone from the source control view

Setting `git.autoRepositoryDetection` or setting `"git.scanRepositories" = ["sub1", "sub2"]` does not help in showing the subrepos in the source view.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sveinse** [comment]
I think this is an effect of a) #96356 code picking up the git add as per step 1-4 and b) #96372 / #37947 that code does not support nested repos, making the subrepos disappear after restart. I believe the issue can be closed as duplicate.

**Comment by joaomoreno** [comment]
Sorry for not getting back to you, @sveinse, is this still an issue?
