### ISSUE TITLE
Not all rulers are being displayed when using zoom level less than 0

### ISSUE THREAD

**Issue by johncruise** [Microsoft/vscode#9634]
- VSCode Version: 1.4.0-insider (2016-07-22T05:07:03.113Z)
- OS Version: Windows 7

Steps to Reproduce:
1. In settings, setup editor.rulers to [71, 99]
2. Setup window.zoomLevel to -1
3. Setup editor.fontSize to 13
4. Reload Window
5. Open any file
6. Open split editor window (ctrl+)

After above, most of the time the 2nd ruler at the left window does not show up.  This only started manifesting on newer version (no problem with older version)

**Comment by kieferrm** [comment]
It seems that there are general issues with multiple rulers when the zoom level is -1 depending on how wide an editor is.

![3vqqhsyx0m](https://cloud.githubusercontent.com/assets/4674940/17109027/13fa3be0-524b-11e6-8b0a-4cbfbdfa6994.gif)

**Comment by johncruise** [comment]
Thank you for confirming.  The show-and-tell screenshot is very informative RE: how to get around this.  Unfortunately, in my environment the left pane doesn't show the other ruler no matter how I resize the width.  What I end up doing (to get a side-by-side code experience) is open the 3rd/last editor pane and minimize the width of the left most.  Ugly solution but it works.

Please keep the bug open until there's a permanent fix.  Thanks for the support.

**Comment by alexandrudima** [comment]
I think this is how Chromium deals with a 1px vertical line when it is zoomed below 100%. My recommendation is to not use `window.zoomLevel`.

**Comment by johncruise** [comment]
Not using `window.zoomLevel` as a solution is not enticing in my case.  The reason why I use it is because all the window component of vscode are a tad big for my taste (icons, folder or solution view, etc) and although I like to see them all the time so I can navigate through my files, they are just taking too much space.

I will only go back to 100% zoom level if there's a way for me to customize font size of the other elements of the window that is not tied up to the editor window's font.

**Comment by alexandrudima** [comment]
:+1: I would also like a way to customize the font size of other elements of the window. Please create an issue for that so I can upvote it :). The zoom level is a cheap trick that causes multiple problems, such as this one, or breaking antialising, etc.

**Comment by johncruise** [comment]
I'll create one.  Thanks for the recommendation.

**Comment by eldarshamukhamedov** [comment]
Here is @johncruise's followup ticket: https://github.com/Microsoft/vscode/issues/10605. How do you guys feel about allowing the ruler width to be styled via themes? Could be a quick fix for the relatively small group of users who are affected by this.

**Comment by alexandrudima** [comment]
The same happens when using for example the Zoom Level on Windows to something like 125%. Some rulers are 1px wide and some are 2px wide depending on how the rulers align with the screen pixels:

![image](https://user-images.githubusercontent.com/5047891/27137410-31595158-511e-11e7-934b-b9de713dc019.png)

Thanks to the help from @fj128  in discussions in #28542 , we have a plan on how to workaround this.

**Comment by alexandrudima** [comment]
With the technique discussed in #28542:

When Windows is set to 125% and `window.zoomLevel: 0`:
![image](https://user-images.githubusercontent.com/5047891/27137701-db10f7b4-511e-11e7-85c6-80cb44703132.png)


When Windows is set to 125% and `window.zoomLevel: -2`:
![image](https://user-images.githubusercontent.com/5047891/27137602-964c4138-511e-11e7-9f13-f411ea9ee3b4.png)

**Comment by KernelDeimos** [comment]
Why is this closed? I have no idea what to do about this. Is it possible to configure the thickness of the ruler?

**Comment by fj128** [comment]
Not a maintainer, but from what I understand, it is closed because it has
been fixed and now we just wait for the next release.
