### ISSUE TITLE
Misleading sync message

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96347]
re #96226

* turning on sync
* the message says "first time sync is setup"
* the message *also* says "merge or replace with data from the cloud"
* ❓ so what kind of "first time sync" is this?

<img width="540" alt="Screenshot 2020-04-28 at 10 55 40" src="https://user-images.githubusercontent.com/1794099/80467945-dacbfa00-893e-11ea-9862-732ac43ab6ac.png">

**Comment by sandy081** [comment]
This is to inform that you are syncing for the first time from this machine and want to merge or replace?

So you are confused with this message `first time sync is setup` that sync is already setup?

**Comment by jrieken** [comment]
Yes, the message is bad.

**Comment by sandy081** [comment]
This message was updated based on suggestions here - https://github.com/microsoft/vscode/issues/91545

To make it clear that sync is being set up, would like to change

```
It looks like this is the first time sync is being set up.
Would you like to merge or replace with the data from the cloud?
```

**Comment by jrieken** [comment]
Unsure about the wording but the message had more information before, esp. the fact that it is the first time that sync is being used from "this machine". If it would be "setup" how come it already has data.

**Comment by sandy081** [comment]
Will fix this message with https://github.com/microsoft/vscode/issues/96370
