### ISSUE TITLE
Cannot log-in from account menu

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96346]
re #96226

* open the account menu
* you cannot use it to sign in
* select "F1 > sign" and see different sign-in options
* It's impossible for me to know what is the "official" sign-in and what not

<img width="621" alt="Screenshot 2020-04-28 at 10 47 31" src="https://user-images.githubusercontent.com/1794099/80467312-ee2a9580-893d-11ea-97d4-046e063cd469.png">

**Comment by sandy081** [comment]
We decided not to show general sign in actions in favour of features requires sign in to show them during their flow.

**Comment by jrieken** [comment]
Following that logic: there should not be "Microsoft Account: Sign In", right?

**Comment by sandy081** [comment]
Yes

**Comment by RMacfarlane** [comment]
I've removed the "Microsoft Account: Sign In" and "Microsoft Account: Sign Out" commands

@sandy081 Was the text in the account menu at one point "Sign in to turn on preferences sync" or has it always just been "Turn on preferences sync"?

**Comment by sandy081** [comment]
I do not remember. Accounts menu can have following entries

`Turn on Preferences Sync`
`Sign in to Sync Preferences`
`Preferences Sync is On`

**Comment by sandy081** [comment]
Assigning to this milestone so that it will be verified.

**Comment by jrieken** [comment]
I still see an azure login thing but I guess that will disappear in the near future...

<img width="275" alt="Screenshot 2020-04-30 at 12 07 32" src="https://user-images.githubusercontent.com/1794099/80698743-316e3b00-8adb-11ea-995b-733a4690388b.png">
