### ISSUE TITLE
Can not switch to Korean if VSCode installed by snap

### ISSUE THREAD

**Issue by trainto** [microsoft/vscode#96345]
- VSCode Version: 1.44.2
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Install VSCode via 'Ubuntu Software'
2. Try switch input method

Does this issue occur when all extensions are disabled?: Yes

I tried to install VSCode via 'Ubuntu Software' (snap), and it works fine just except switching input method. (I'm using iBus)

So I remove VSCode, and install again using .deb downloaded from VSCode website, then it works fine.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/96041
