### ISSUE TITLE
[semantic tokens] improve code completions for `editor.semanticTokenColorCustomizations`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96351]
I have

```
"editor.tokenColorCustomizations": {
		"semanticHighlighting": true
	},
	"editor.tokenColorCustomizationsExperimental": {
		"*.static": {
			"fontStyle": "italic"
		}
	},
```

but it seems that the config for statics cannot be moved into the new config...

<img width="540" alt="image" src="https://user-images.githubusercontent.com/1794099/80469122-6b570a00-8940-11ea-8c7c-80312644792d.png">

**Comment by aeschli** [comment]
The form has slightly changed:
```
"editor.semanticTokenColorCustomizations": {
    "enabled": true,
    "rules": {
        "*.static": { ... }
   }
}
```
I wanted the enablement together with the rules, but avoid any name clashes of `enabled` with rule selectors. (also to give more space for future enhancements)

**Comment by jrieken** [comment]
Understood. There is some fishy intellisense ordering happening here - the relevant pieces show at the bottom...

<img width="514" alt="Screenshot 2020-04-29 at 09 40 48" src="https://user-images.githubusercontent.com/1794099/80571811-82a7fd00-89fd-11ea-81dc-b06e6ae20873.png">

**Comment by aeschli** [comment]
The original issue is not a bug but as intended, so I rename it to the ordering issue. Hope that's ok for you.

**Comment by aeschli** [comment]
To verify:
- in the settings add
```
"editor.semanticTokenColorCustomizations": {
    |
}
```
- code assist at |
- verify that `rules` and `enabled` show first

**Comment by roblourens** [comment]
Still no

![image](https://user-images.githubusercontent.com/323878/83696031-0044c700-a5c1-11ea-83e7-f529fb8e4974.png)

**Comment by dbaeumer** [comment]
Verified

<img width="575" alt="capture" src="https://user-images.githubusercontent.com/1931590/83859502-4f543e80-a71e-11ea-8856-210554399001.png">

**Comment by JohnYacoub** [comment]
have the same issue and can't get it to work ? does it have anything do do with eslint configuration ?
