### ISSUE TITLE
Adding a git repo adds it to the source control view even when disabled

### ISSUE THREAD

**Issue by sveinse** [microsoft/vscode#96356]
- VSCode Version: 1.44.2
- OS Version: Win 10.0.18363

Steps to Reproduce:

1. Create a new empty directory and open in VSCode
2. Set the following workspace settings: `"git.autoRepositoryDetection": false` and `"git.detectSubmodules": false`.
3. Open terminal and create a new subrepo: `git init sub`. Observe that despite the workspace settings, the repo is discovered and opened.

If VSCode is restarted, the repo is no longer found, which is in accordance with the `git.autoRepositoryDetection` setting.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
This is #37947.

The `git.scanRepositories` setting might be a workaround for now.

**Comment by sveinse** [comment]
@joaomoreno This is not #37947, this issue is not about nesting since the top work directory is not a repo. It is about VSCode behaving inconsistently when a repo inside the work directory is created. It will add the new repo to the source control view even when it shouldn't according to settings. VSCode must be restarted to fix it. Please consider to reopen the issue.

**Comment by joaomoreno** [comment]
Sorry, I misread the instructions indeed! 👍

**Comment by joaomoreno** [comment]
The problem is that we're still detecting git repos based on file change events, despite this setting value: https://github.com/microsoft/vscode/blob/27a97b9534e6ddf6c7cf8a4270827157e1eb9288/extensions/git/src/model.ts#L93-L93

**Comment by joaomoreno** [comment]
Suggestion from @jrieken:

> make it a tri-state setting: on open, on edit, never
