### ISSUE TITLE
Duplicate Entries in the Manage Trusted Extensions Dialog

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#96355]
Testing https://github.com/microsoft/vscode/issues/96313

Not clear what has caused this. I've signed-out and signed back in multiple times into the Github account. I'm now seeing duplicated entries in the Manage Trusted Extensions Dialog for the GitHub account.

Also the 'auth' entry is not helpful.

![image](https://user-images.githubusercontent.com/172399/80470981-0a7d0100-8943-11ea-827f-52aa68fbdc01.png)

I've tried to reproduce the issue by signing in/out multiple times. I could not reproduce it anymore.

**Comment by RMacfarlane** [comment]
I'm having trouble reproducing this now, and have also just made a change to clear the trusted extension cache on sign out (https://github.com/microsoft/vscode/issues/96616). So am optimistically closing this as fixed
