### ISSUE TITLE
Manage Trusted Extensions Quick Pick not useful when empty

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#96359]
Testing https://github.com/microsoft/vscode/issues/96313

When an account has no trusted extensions, then the shown Quick Pick should not be shown, instead there should be an Alert that there are no trusted extensions.
![image](https://user-images.githubusercontent.com/172399/80472209-b5da8580-8944-11ea-84c7-e30bcb20581c.png)

**Comment by mrsidverse** [comment]
How to select trusted extension?

**Comment by meganrogge** [comment]
@mrsidverse click the person icon on the activity bar, then your username, then Manage Trusted Extensions
