### ISSUE TITLE
GitHub Authorization web page is referring to the no longer existing status bar item

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#96350]
Testing #96313

When signing into GitHub, then the authorization page shown in the browser still refers to the no longer existing status bar item, see the screenshot below.

![image](https://user-images.githubusercontent.com/172399/80469000-3fd41f80-8940-11ea-9f8f-91ecb03a4f48.png)

**Comment by RMacfarlane** [comment]
@egamma I added back a statusbar item specifically because of this, it should show up only for the duration of the sign in process

**Comment by RMacfarlane** [comment]
Please let me know if it doesn't work for you, but this should be supported
