### ISSUE TITLE
"Sign in to null" is an ugly message

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#96368]
Refs: #96313

ubuntu 18, follow the GitHub authentication flow. Notice the page says "sign in to null..." in the status bar. This is a wrong message, we shuold not show "null" here

![Screenshot 2020-04-28 at 11 56 21](https://user-images.githubusercontent.com/1926584/80474051-4c0fab00-8947-11ea-89df-ecb1acadbf92.png)

**Comment by gjsjohnmurray** [comment]
See also #96350
