### ISSUE TITLE
Accounts context menu should show what account is being used for sync

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96362]
#96226

* I have to select the sync-entry to know what account is being used
* IMO it would be nice to have some kind of hint what account is used for sync at this level

<img width="379" alt="Screenshot 2020-04-28 at 11 41 18" src="https://user-images.githubusercontent.com/1794099/80472570-31d4cd80-8945-11ea-810b-6f27412c8e67.png">

**Comment by RMacfarlane** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/97168
