### ISSUE TITLE
The TypeScript language service died 5 times right after it got started. The service will not be restarted.

### ISSUE THREAD

**Issue by dipti-code** [microsoft/vscode#96366]
We have written the needed data into your clipboard because it was too large to send. Please paste.

while opening specific to my project.its showing the error.
But other typescript projects not showing this error.
My ts.config

{
  "compilerOptions": {
     "target": "es6",
     "module": "commonjs",
     "baseUrl": ".",
     "strict": true,
     "noImplicitAny": false,
     "paths": {
        "*": [
           "./*"
        ],
        "src/*": [
           "./src/*"
        ],
        "test/*": [
           "./test/*"
        ]
     },
     "types": [
         "node",
         "@wdio/sync",
         "@wdio/jasmine-framework"
      ],
      "allowSyntheticDefaultImports": true,
       "esModuleInterop": true
  },
  "include": [
   ["./**/*.ts"]
  ]
}

**Comment by mjbvz** [comment]
Please fill in the issue template
