### ISSUE TITLE
Merge "Show Extension/Feature using this account" and "Manage Trusted Extensions"

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96367]
#96226

* select an account
* select "show extensions/features using this account"
* 😕 you get a quick pick that doesn't allow you to do anything at all
* select "manage trusted extension"
* 😕 you get a slight different quick pick that at least allows to check/uncheck extensions

**useless _picker_**

<img width="698" alt="Screenshot 2020-04-28 at 11 52 40" src="https://user-images.githubusercontent.com/1794099/80473680-c429a100-8946-11ea-9f3b-dfacd80c6f15.png">

**better picker, but it shows different info?**
<img width="795" alt="Screenshot 2020-04-28 at 11 58 56" src="https://user-images.githubusercontent.com/1794099/80474393-b0326f00-8947-11ea-9bfd-e50ea8d08b7b.png">

**Comment by rebornix** [comment]
It confuses me as well when I see different results in these two quick picks.

**Comment by RMacfarlane** [comment]
Couple of thoughts here:

If combining them into one, "Preferences Sync" becomes something that could potentially be unchecked, do we want to treat it any differently? The result would be that if preferences sync tries to read a token from that account, you see a consent dialog. Seems a bit weird for there not to be trust for VSCode itself, but this would then be consistent with extensions.

Erich had an idea of showing the "last used" time, when the extension or core feature last read the access token. If we added that, that would make it more obvious that some extensions have actually used a token during this session, and some have not.

**Comment by sandy081** [comment]
What happens if I uncheck in general say on `Github Pull Requests Nightly Build` ?

**Comment by RMacfarlane** [comment]
If you uncheck an extension and it tries to read an access token, a consent prompt is shown. Otherwise it is able to read the access token silently. It's similar to how "Trusted Domains" behaves

**Comment by RMacfarlane** [comment]
I removed the "Show features and extensions using this account" option and have added timestamps showing when an extension last accessed the account in "Manage Trusted Extensions".

Preferences sync is not listed there, it's only extensions. We can show which account is being used by preferences sync by exploring a richer accounts UI: https://github.com/microsoft/vscode/issues/97168
