### ISSUE TITLE
workbench.colorCustomizations  can't change color

### ISSUE THREAD

**Issue by G-rass** [microsoft/vscode#96360]
![image](https://user-images.githubusercontent.com/12094087/80471938-ad02a780-8976-11ea-98cb-cfe42cc9dd61.png)
Other characters can change color, only folder is always blue, this color limits my theme, and makes me very uncomfortable, I hope to change here

**Comment by usernamehw** [comment]
Try to experiment and find the color, starting with:
```
"terminal.ansiBlue"
"terminal.ansiBrightBlue"
"terminal.ansiMagenta"
"terminal.ansiBrightMagenta"
```

**Comment by G-rass** [comment]
![image](https://user-images.githubusercontent.com/12094087/80473682-0f5ca780-8979-11ea-8c08-6d165cbc723c.png)
I changed all this to black, but it didn't work

**Comment by Tyriar** [comment]
Are you sure you saved your settings file?
![recording (1)](https://user-images.githubusercontent.com/2193314/80616156-643e0380-89f5-11ea-8c86-34359ccd20da.gif)

If so, can you turn on the DOM renderer (setting `"terminal.integrated.rendererType": "dom")and then inspect the DOM (Help > Toggle Developer Tools) to see what class structure the row in question has, you want to look for the `.xterm-rows` element:

![image](https://user-images.githubusercontent.com/2193314/80616336-a5361800-89f5-11ea-876e-0430497c29dc.png)
