### ISSUE TITLE
Notification consistency with sign in and sign out

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#96364]
Refs: https://github.com/microsoft/vscode/issues/96313

1. Sign in to GitHub, the flow goes nicely -> I do not get a notification that I signed in correctly
2. Sign out of GitHub, the flow goes nicely -> I do get a notification taht I signed out correctly

These two flows should be consistent. I suggest to simply remove the notification that I sucesffully signed out since it is easy for user to check this by clicking on the profile in the activity bar. Especially since there is a confirmation dialog before

![Screenshot 2020-04-28 at 11 51 01](https://user-images.githubusercontent.com/1926584/80473516-8d538b00-8946-11ea-8b33-a4b467275eb5.png)

**Comment by RMacfarlane** [comment]
I think having the sign out notification is useful - in the sign in case, there is more feedback that it has succeeded. If signing into settings sync, there's a notification that it has started, so anything additional would just be more noise. I guess extensions can be a little more subtle, but I think generally extensions do something after getting credentials, like refreshing a view.
