### ISSUE TITLE
Open xdg-open dialog instead of vscode-insiders

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#96365]
Refs: https://github.com/microsoft/vscode/issues/96313

Ubuntu 18. Do the GitHub authentication dance. Notice the dialog which says "Open xdg-open". As a new user I would be puzzled by this name and would expect that this dialog mentions VS Code insiders

![Screenshot 2020-04-28 at 11 48 16](https://user-images.githubusercontent.com/1926584/80473589-a52b0f00-8946-11ea-9e4f-3307996840db.png)

**Comment by RMacfarlane** [comment]
I don't think I'm able to control this - this dialog comes from the browser when trying to open the url a "vscode-insiders". @joaomoreno do you know if there's anything we can do to change this when setting up the protocol handler?
