### ISSUE TITLE
Add back button to sync config

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96361]
#96226

The state below is always a dead end but I often use it to check what is being sync for my account, not for tweaking anything. Go back is what I often want and not losing "all state"

<img width="721" alt="Screenshot 2020-04-28 at 11 36 29" src="https://user-images.githubusercontent.com/1794099/80472109-93e10300-8944-11ea-8d78-c621713d3580.png">

**Comment by sandy081** [comment]
`Go back` to what?

**Comment by jrieken** [comment]
> Go back to what?

Where I came from

**Comment by sandy081** [comment]
Ah sorry! I was thinking that this picker was shown using the command `Preferences Sync: Configure...`, You can also come from `Preferences Sync is On` menu. Now I got it.
