### ISSUE TITLE
GitHub Auth: Could not find a way to paste in an access token manually

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#96363]
Testing #96313

The Web Page shown in the auth flow shows me detailed information for how to add an access token manually in case there are issues. I could not find a command to do so in VS Code.

See also #96350

![image](https://user-images.githubusercontent.com/172399/80473249-2a61f400-8946-11ea-9e49-1be488193eae.png)

**Comment by RMacfarlane** [comment]
Closing since this should be covered by the statusbar item that gets added during login for this purpose

**Comment by kelseiv** [comment]
@RMacfarlane what is "statusbar item that gets added during login for this purpose"? I see "Connect" on my statusbar, and when I click Connect, I see You don't have any connections yet. Still not sure where to enter the authorization token. Any help is greatly appreciated-thank you!
