### ISSUE TITLE
Auto attach stopped working after adding launch.json node preview

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#96375]
Issue Type: <b>Bug</b>

Found while testing https://github.com/microsoft/vscode/issues/96296. I don't know if this is a bug in the auto attach feature but wanted to report it.

I followed the steps in the test case and everything was working well.

I then added a launch.json, choosing the Node preview option (fairly random choice on my part). A bunch of things were installed (Omnisharp, .Net Core debugger, Razor Language Server)

I can debug the code from the launch action but now running from the terminal and auto attach doesn't work. Whenever I try to run from the terminal I get the following error:

C:\src\testApril2020>node fibonnaci.js
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'C:\Users\stevencl\AppData\Local\Temp\vscode-js-debug-bootloader.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1296:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:444:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:68:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}

VS Code version: Code - Insiders 1.45.0-insider (abb4a35cfc26102f93fd00df7b59ce1a19c2017a, 2020-04-28T05:36:25.810Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (3.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
EditorConfig|Edi|0.14.5
vscode-github-releases-updater|joa|0.18.0
vscode-peacock|joh|3.7.0
chat|kar|0.33.0
vscode-docker|ms-|1.1.0
csharp|ms-|1.21.17
python|ms-|2020.4.76186
remote-containers|ms-|0.113.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.9
js-debug-companion|ms-|1.0.0
cloudenv-extensions|ms-|1.0.1369
vsliveshare|ms-|1.0.2048
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.3.4
vsonline|ms-|1.0.2096
debugger-for-chrome|msj|4.12.6
test-search-rg|rob|0.0.3
code-spell-checker|str|1.8.0

</details>

**Comment by connor4312** [comment]
Thanks! <3
