### ISSUE TITLE
Leftover guide bar to the right of view container titles in panel

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#96379]
Testing https://github.com/microsoft/vscode/issues/96318

Note that it doesn't matter if I actually drop the view. The little guide bar to the right of terminal will stick around until I try to move another view.
![leftoverbar](https://user-images.githubusercontent.com/38270282/80483719-d57aa980-8956-11ea-953e-e38bb3b77067.gif)

**Comment by sbatten** [comment]
for some reason that I could not explain, the dragLeave event does not fire sometimes and I could not get a reliable repro, it would repro until I tried to dig. the fix I have pushed is to clean up on the drag end event so that when this does occur, it gets cleaned up fairly immediately.
