### ISSUE TITLE
Keep trailing whitespaces in commit message

### ISSUE THREAD

**Issue by hensz** [microsoft/vscode#96376]
Hi!

We're using commit hooks to extend the manually entered commit message (we're using gerrit and need gerrit commit IDs). However the commit hooks have a bit strange behavior: The text is only added to the end of the commit message if the commit message ends with a space (no idea why this is the case).

However this is no problem for me: I simply create a git commit message template that ends in a new line with a space. This works totally fine when using git commit from the command line. After the commit is done, the space is removed and the commit message looks as expected. But when I commit from within VS Code, it seems that the commit message editor removes trailing spaces before passing the message to git.

Can the behavior be disabled?

Thanks,
Torsten

**Comment by joaomoreno** [comment]
Could you fix the commit hooks instead? It seems odd that we'd not trim the input here....

**Comment by hensz** [comment]
Not that easy, since the commit hooks are not maintained by me but by a different department. I could also think of other reasons to use the commit message unmodified, so I'd not consider this as a workaround for a bug in a different piece of software.

**Comment by joaomoreno** [comment]
> other reasons to use the commit message unmodified

Can you elaborate on this?

**Comment by hensz** [comment]
Sometimes whitespaces have a meaning. Perhaps this is only for formatting reason, perhaps some other tool like our commit hook is relying on this.

I just looked into the commit hook, but the logic is too complicated for me ;-)
Perhaps we can adapt the hook, there's some special handling of "footer" which I haven't heard before.

Nevertheless in my opinion there should be a way to pass user-defined input unmodified to underlying tools, regardless of which UI and which tool.

**Comment by joaomoreno** [comment]
> Perhaps we can adapt the hook, there's some special handling of "footer" which I haven't heard before.

Let me know how it goes.

**Comment by hensz** [comment]
Hi!
Today I learnt that the commit hook is not done by us, but taken from gerrit and only adapted to our needs. See here for the rationale:
https://gerrit-review.googlesource.com/Documentation/cmd-hook-commit-msg.html

I understand that there are some special marker in the commit message (e.g. signed-off) that need to be last. That's why the hook works in the way it does, resulting in this strange behavior. Of course someone could fix it (if he mastered the scripting magic of this hook), but I cannot, and also the colleagues I asked cannot fix this. The hook has a rather complicated logic, and changing things like the footer handling that we don't fully understand might have unforeseen impact.

**Comment by joaomoreno** [comment]
Got it. In any case I don't think this warrants the change you're proposing in VS Code, so I'll close down the issue.
