### ISSUE TITLE
Which version of TypeScript is Visual Studio Code "Insiders" using?

### ISSUE THREAD

**Issue by httpdigest** [Microsoft/vscode#9637]
- VSCode Version:1.4.0-insider (commit 01a3f86)
- OS Version:Windows 7 x64

I get inconsistent behaviour between the typescript compiler (installed with `npm install -g typescript@next`) and the TypeScript language services included in Visual Studio Code "Insiders".
To get a quick fix [for this TypeScript issue](https://github.com/Microsoft/TypeScript), I installed the development version, currently Version 2.1.0-dev.20160722, of typescript via npm.
Now, the issue is gone when I build the application with the typescript task (on save) inside of Visual Studio Code "Insiders".
However, when I edit the source code (just adding a newline at the end or other insignificant changes), the error pops right up again without invoking tsc via the task but using the built-in TypeScript language services of the editor.

The Info output of Visual Studio Code "Insiders" in the menu "Help" -> "Info" does not show the TypeScript version used, either.

What is the TypeScript language service version that Visual Studio Code "Insiders" uses for its internal editor, then?

**Comment by kieferrm** [comment]
We are bundling TS version 1.8.10 right now.  You can change the TS language server version vscode uses by setting the `typescript.tsdk` property to the path of your custom TS language server installation.

**Comment by chadmott** [comment]
thanks @kieferrm 
for anyone else pulling hair out b/c VSCode squiggle lines on "exports" and "require" et. al. while using TS 2.0 just make that change in settings
`"typescript.tsdk": "/usr/local/lib/node_modules/typescript/lib"` <- or whatever your path is
