### ISSUE TITLE
Cannot move default view containers by icon

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#96377]
Testing https://github.com/microsoft/vscode/issues/96318
![ViewsNotMoving](https://user-images.githubusercontent.com/38270282/80483328-3190fe00-8956-11ea-833a-b57d609999c9.gif)

**Comment by sbatten** [comment]
some containers cannot be moved. this is because they views themselves have not been configured for panel view. @isidorn this is because the explorer still does not support being in the panel, do you want to continue disallowing it to move or should we have it move next milestone?
