### ISSUE TITLE
local undo

### ISSUE THREAD

**Issue by agocorona** [microsoft/vscode#96371]
Sometimes, after some scattered changes in a file here and there, I want to undo what was edited in a  selected block of code without touching other blocks.  

How? By applying only the undo's that involve changes within this block.  

keys [CTRL] b z, for example.

**Comment by alexdima** [comment]
@agocorona This is not normally something an editor provides. But if you have your source code under source control, you can bring up the diff editor to see the effective changes in a certain area.

**Comment by agocorona** [comment]
Hi, it is not  something an  editor provides,  but it may be very useful since modern OSs allow to keep sessions for days while the user performs  random changes in the files without  doing commits.  And I think that it may be useful and doable.
