### ISSUE TITLE
Sync wants to merge right after turning it on

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96370]
re #96226

This is basically the back story for https://github.com/microsoft/vscode/issues/96347

* I work on a single computer with VS Code Desktop only
* I did enable settings-sync with GH-accounts shortly after we started to support GH-accounts
* for some unknown reason settings sync is off 🤷 
* enable sync tells me that I have to merge to continue

That's the moment where I stop using this feature and where I want a way to see what data we have stored. There is no way to figure that out and that's undermining trust in this feature. Things that we should do better

* give me a way to nuke the cloud data _without_ being sync'ing, just a big stop this switch so that I am always in control. Ideally I want to be able to inspect the cloud-data but this is a good start
* know that I am always coming with the same machine (as I am in this case) and don't start talking about merging and so

**Comment by sandy081** [comment]
There is a remote backup view to inspect the data in the cloud but that is available only after sync is enabled. May be we can show this always.

> give me a way to nuke the cloud data without being sync'ing, just a big stop this switch so that I am always in control

So you are asking for `Replace Cloud` action? Is not it a big decision for the user to decide without knowing what is there in the cloud? Probably have an action to show the remote backup view and decide then?

**Comment by jrieken** [comment]
> So you are asking for Replace Cloud action?

Not really, I am asking for "nuke the cloud" command  and a "Show me what you have command" - both without sync'ing but only being logged in

**Comment by sandy081** [comment]
Ok fair enough. Will add "Show Remote Data" action that shows the remote backup view and provide action there to nuke.

**Comment by sandy081** [comment]
> for some unknown reason settings sync is off

As discussed this could be a bug, please see if this happens again and provide the logs (Preferences Sync & Account).

**Comment by sandy081** [comment]
> know that I am always coming with the same machine (as I am in this case) and don't start talking about merging and so

This is a fair assumption. 

@Tyriar is it possible to know from the server that it has data synced only from this device through the manifest request?

**Comment by Tyriar** [comment]
@sandy081 not unless we start tracking which machine each version is done with as we've been talking about recently.

**Comment by hickeng** [comment]
@Tyriar 
I have observed the same behaviour, however I got a prompt to view the conflict.
There is no actual conflict... but the settings have been reordered. A sort is necessary based on the key of each level of the hierarchy.

<details><summary>remote</summary><p>

```json
{
    "window.zoomLevel": 0,
    "gitlens.advanced.messages": {
        "suppressCommitHasNoPreviousCommitWarning": false,
        "suppressCommitNotFoundWarning": false,
        "suppressFileNotUnderSourceControlWarning": false,
        "suppressGitVersionWarning": false,
        "suppressLineUncommittedWarning": false,
        "suppressNoRepositoryWarning": false,
        "suppressResultsExplorerNotice": false,
        "suppressShowKeyBindingsNotice": true,
        "suppressUpdateNotice": false,
        "suppressWelcomeNotice": true
    },
    "gitlens.keymap": "none",
    "gitlens.historyExplorer.enabled": true,
    "[markdown]": {},
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\wsl.exe",
    "gitlens.views.fileHistory.enabled": true,
    "gitlens.views.lineHistory.enabled": true,
    "go.formatTool": "goimports",
    "html.trace.server": "messages",
    "liveshare.diagnosticLogging": true,
    "liveshare.featureSet": "insiders",
    "remote.SSH.showLoginTerminal": true,
    "go.inferGopath": true,
    "python.jediEnabled": false,
    "terminal.integrated.rendererType": "dom",
    "files.trimTrailingWhitespace": true,
    "gitlens.blame.ignoreWhitespace": true,
    "go.gocodeAutoBuild": true,
    "go.useLanguageServer": true,
    "go.testTags": "unit_tests",
    "remote.SSH.path": "C:\\WINDOWS\\System32\\OpenSSH\\ssh.exe",
    "remote.SSH.remotePlatform": {
        "dev": "linux"
    },
    "editor.largeFileOptimizations": false,
    "vs-kubernetes": {
        "vs-kubernetes.kubectl-path.linux": "/home/ghicken/.vs-kubernetes/tools/kubectl/kubectl",
        "vs-kubernetes.draft-path.linux": "/home/ghicken/.vs-kubernetes/tools/draft/linux-amd64/draft",
        "vs-kubernetes.minikube-path.linux": "/home/ghicken/.vs-kubernetes/tools/minikube/linux-amd64/minikube",
        "vs-kubernetes.helm-path.linux": "/home/ghicken/.vs-kubernetes/tools/helm/linux-amd64/helm"
    }
}
```
</p></details>
<p/>

<details><summary>local</summary><p>

```json
{
    "remote.SSH.remotePlatform": {
        "nimbus-dev": "linux"
    },
    "editor.largeFileOptimizations": false,
    "vs-kubernetes": {
        "vs-kubernetes.kubectl-path.linux": "/home/ghicken/.vs-kubernetes/tools/kubectl/kubectl",
        "vs-kubernetes.draft-path.linux": "/home/ghicken/.vs-kubernetes/tools/draft/linux-amd64/draft",
        "vs-kubernetes.minikube-path.linux": "/home/ghicken/.vs-kubernetes/tools/minikube/linux-amd64/minikube",
        "vs-kubernetes.helm-path.linux": "/home/ghicken/.vs-kubernetes/tools/helm/linux-amd64/helm"
    },
    "go.formatTool": "goimports",
    "terminal.integrated.copyOnSelection": true,
    "terminal.integrated.scrollback": 10000,
    "html.trace.server": "messages",
    "liveshare.diagnosticLogging": true,
    "liveshare.featureSet": "insiders",
    "remote.SSH.showLoginTerminal": true,
    "go.inferGopath": true,
    "python.jediEnabled": false,
    "terminal.integrated.rendererType": "dom",
    "files.trimTrailingWhitespace": true,
    "gitlens.blame.ignoreWhitespace": true,
    "go.gocodeAutoBuild": true,
    "go.useLanguageServer": true,
    "go.testTags": "unit_tests",
    "remote.SSH.path": "C:\\WINDOWS\\System32\\OpenSSH\\ssh.exe",
    "window.zoomLevel": 0,
    "gitlens.advanced.messages": {
        "suppressCommitHasNoPreviousCommitWarning": false,
        "suppressCommitNotFoundWarning": false,
        "suppressFileNotUnderSourceControlWarning": false,
        "suppressGitVersionWarning": false,
        "suppressLineUncommittedWarning": false,
        "suppressNoRepositoryWarning": false,
        "suppressResultsExplorerNotice": false,
        "suppressShowKeyBindingsNotice": true,
        "suppressUpdateNotice": false,
        "suppressWelcomeNotice": true
    },
    "gitlens.keymap": "none",
    "gitlens.historyExplorer.enabled": true,
    "[markdown]": {},
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\wsl.exe",
    "gitlens.views.fileHistory.enabled": true,
    "gitlens.views.lineHistory.enabled": true
}
```
</p></details>
<p/>

**Comment by sandy081** [comment]
Improved the first time sync replace or merge dialog and is shown only when 

- user last synced from another machine and there are some changes (local or remote)

<img width="643" alt="image" src="https://user-images.githubusercontent.com/10746682/83416691-53801380-a421-11ea-9a2d-b7bf9530cb09.png">

Also added an option to view synced data
