### ISSUE TITLE
vscode does not honor git.scanRepositories or git.detectSubmodules

### ISSUE THREAD

**Issue by sveinse** [microsoft/vscode#96372]
- VSCode Version: 1.44.2
- OS Version: Win 10.0.18363

Steps to Reproduce:

1. Create a new empty directory and open in VSCode
2. Open terminal and create a new git repo: `git init .`
3. In terminal create a new sub repo: `git init sub`. Observe that the sub repo is NOT found in the source control view.
4. Open workspace settings and add: `"git.scanRepositories": ["sub"]` and ensure `git.detectSubmodules` is true.
5. Observe that the sub module is not found and presented in the source control view.

The expected behavior is that VSCode would find the explicitly listed repos listed in `git.scanRepositories`. No combination in any of the settings of `git.autoRepositoryDetection`, `git.detectSubmodules` and `git.scanRepositories` seems to be able to add the sub repo to the source control view.

The only way to have the repo added is by adding `.gitmodules`, which is normally a file under git control and it creates an unwanted dirty top-level repo, ref #96143 

```
[submodule "sub"]
	path = sub
	url = foobar
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
This is https://github.com/microsoft/vscode/issues/37947

Only submodules are supported now.

**Comment by sveinse** [comment]
@joaomoreno while this issue is related to nested git repos per #37947 , is ignoring the `git.scanRepositories` and `git.detectSubmodules` settings expected? I would argue it is unexpected and thus a bug, whereas #37947 is a feature-request.

**Comment by joaomoreno** [comment]
The fact that Code doesn't find repos within repos is just the lack of having implemented nested repo support, despite those settings.
