### ISSUE TITLE
View moved to panel is awkwardly sized and in a new window changes size

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#96381]
Testing https://github.com/microsoft/vscode/issues/96318

The left screen is what I started with. I moved a Gitlens view into search. It ended up being very narrow. Then I opened a new window on the right. In that one, the search and file history are now equally sized.
![image](https://user-images.githubusercontent.com/38270282/80483877-18d51800-8957-11ea-9c0e-89f45d79c38f.png)

**Comment by sbatten** [comment]
some work was done for another issue, we don't a clean have a way to ensure the sizes are equal, but we do better in most cases now.
