### ISSUE TITLE
Inconsistent view container opening in panel on pause

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#96387]
Testing https://github.com/microsoft/vscode/issues/96318

It was very intuitive that if I pause over a view container title while dragging that it would open the view container so I could put the view in that container. However, it doesn't seem to work consistently. Here, I can't get the Output to open:
![outputNotOpening](https://user-images.githubusercontent.com/38270282/80485558-f09ae880-8959-11ea-8563-cd8f66c5d775.gif)

There are also somehow two underlined view containers in the panel

**Comment by sbatten** [comment]
i think the double outline is indicative of whatever  the real issue is here. need to investigate. any idea how to get the double outline?

**Comment by alexr00** [comment]
Double outline?

**Comment by sbatten** [comment]
sorry, double underline

**Comment by alexr00** [comment]
No, I don't know how I got it.
