### ISSUE TITLE
Terminal unusable after moving

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#96389]
Testing https://github.com/microsoft/vscode/issues/96318

I was actually trying to capture a recording of:
- Terminal is in sidebar in it's own view container
- Try to move terminal back to my favorite spot to the right of Output in the panel
- It looks like it moved for a split second, then focus was on the Explorer and the terminal was still in the sidebar
However, I got this instead
![terminalAfterMove](https://user-images.githubusercontent.com/38270282/80486014-b120cc00-895a-11ea-9380-0a142fe6f742.gif)

**Comment by sbatten** [comment]
You say terminal was still in the sidebar but based on your GIF, i don't see its icon in the sidebar after the move?

**Comment by alexr00** [comment]
The terminal starts in in the sidebar. After I drag it back to the panel it is broken.

**Comment by sbatten** [comment]
this should be fixed now. please verify.
