### ISSUE TITLE
Git gutter not working with UNC paths

### ISSUE THREAD

**Issue by Varstahl** [microsoft/vscode#96388]
- VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
- OS version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. open a UNC folder
2. edit anything
3. git diff is working while there is no git gutter in the file editor

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/284077/80485000-efb58700-8958-11ea-83ed-61f523465e29.png)

**Comment by gjsjohnmurray** [comment]
Is #91548 relevant?

**Comment by joaomoreno** [comment]
cc @eamodio Wasn't this fixed?

**Comment by joaomoreno** [comment]
@Varstahl What git version are you using?

**Comment by Varstahl** [comment]
> Is #91548 relevant?

@gjsjohnmurray  I'm not 100% sure, go to definition doesn't work in my project.

> What git version are you using?

```
> git --version
git version 2.26.2.windows.1
```

To memory this has never worked, that I can recall. At one point I think it was simply stated as unsupported, so I just mapped the network share to a drive and went from there, it worked alright. Today I had some network issues so I stumbled on this again, read it was fixed, tried but it still doesn't work on my end, even with all extensions disabled.

**Comment by eamodio** [comment]
@joaomoreno yeah, I thought this was fixed. It works for me with both mapped or unmapped. And I'm running the same windows and git versions.

@Varstahl Do you see any errors in the output channel for _Git_?

**Comment by Varstahl** [comment]
Not really, here's the log:
```
Using git 2.26.2.windows.1 from E:\Software\Git\cmd\git.exe
> git rev-parse --show-toplevel
> git rev-parse --git-dir
Open repository: \\WebDev\Web\auth
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git rev-parse --show-toplevel
> […]
> git rev-parse --show-toplevel
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
```

**Comment by joaomoreno** [comment]
Maybe case sensitivity?

**Comment by Varstahl** [comment]
@joaomoreno nailed it! Disconnecting the drive didn't work, but disconnecting, restarting the O/S  and reopening from the share fixed it.

Is it a bug, given that NetBios names should be case insensitive?

**Comment by joaomoreno** [comment]
Was the issue at all related to case sensitivity, or some other random thing which got fixed from the rebooting?

**Comment by Varstahl** [comment]
Definitively case sensitivity. You made me doubt it for a second but I redid the whole procedure opening the share as `\\WebDev\` instead upon reboot, and it failed again. 100% reproducible.

When I see `Open repository: \\WebDev\` in the git log, the gutter fails.

**Comment by joaomoreno** [comment]
What is the actual path name?

**Comment by Varstahl** [comment]
It only works when the NetBios name is spelt in all uppercase, `\\WEBDEV\`. the rest I navigated through window and stays the same, `Web\auth`. So, `\\WEBDEV\Web\auth` works, `\\WebDev\Web\auth` (or any other capitalization I guess) doesn't.

**Comment by joaomoreno** [comment]
@eamodio Can you repro?
