### ISSUE TITLE
No indication of selected container in panel when moving a view into the panel

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#96386]
Testing https://github.com/microsoft/vscode/issues/96318

Usually the corresponding panel view container gets an underline. But when I move the output into some sidebar view container, then move it back to it's own container in the panel, it isn't clear which view container in the panel is visible (no underline on output)

![image](https://user-images.githubusercontent.com/38270282/80485240-50dd5a80-8959-11ea-8417-b90154554839.png)

**Comment by sbatten** [comment]
I think this also fails to repro after the fixes with listeners
