### ISSUE TITLE
Panel gets into empty state

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#96384]
Testing https://github.com/microsoft/vscode/issues/96318

When I move a the last view in a container out of the panel, the panel get's into an empty state. Seems like we should select another view container.
![image](https://user-images.githubusercontent.com/38270282/80485028-fd6b0c80-8958-11ea-9321-76e3d1325372.png)

**Comment by sbatten** [comment]
this is only for terminal and part of a separate issue where we need to deal with panel empty state.

**Comment by sbatten** [comment]
actually, what exactly were your steps? which panel did you move a view out of and how?

**Comment by alexr00** [comment]
I think I had put a gitlens view into the output container, then one by one moved both views out of the output panel container and into the sidebar.

**Comment by sbatten** [comment]
lots of listeners/registration issues fixed yesterday, likely related to this. can you repro anymore?

**Comment by alexr00** [comment]
Yes, it's fixed now.
