### ISSUE TITLE
Git: Failed to show text document , should show in editor #undefined

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96397]
Refs: https://github.com/microsoft/vscode/issues/96279

![image](https://user-images.githubusercontent.com/900690/80489190-c0eedf00-895f-11ea-8177-01be4c24f4b4.png)

I got this by clicking on the "Open File" quick action from the Git changes view.

**Comment by jrieken** [comment]
@joaomoreno Is the git extension using the `showTextDocument`-API and not the `vscode.open`-command?

**Comment by jrieken** [comment]
Oh, I see: https://github.com/microsoft/vscode/blob/cab6f958a23b9c5376b051960859e047036c9b25/extensions/git/src/commands.ts#L839

**Comment by joaomoreno** [comment]
I've called every possible method in our code to be able to open documents. The current approach is probably already the 53rd iteration.

**Comment by jrieken** [comment]
Yeah, git isn't to blame. This is two problems

* the `showTextDocument`-API must overrule the custom editor settings and always open a text editor
* there is no API to do the right thing, like open this URI with potentially these options

**Comment by bpasero** [comment]
@jrieken 

> the showTextDocument-API must overrule the custom editor settings and always open a text editor

We have a `ignoreOverrides` editor option that we could simply add to this options bag [1]

> there is no API to do the right thing, like open this URI with potentially these options

Can you clarify what API is needed, wasn't sure I understand that message.

[1]
https://github.com/microsoft/vscode/blob/997b4c863a45f171570d5167fee31e74b018ba06/src/vs/workbench/api/browser/mainThreadEditors.ts#L121-L128

**Comment by jrieken** [comment]
The `showTextDocument`-API has guarantee that it opens a text editor or errors. Therefore we cannot make it open a custom editor and need an API which doesn't return anything but accepts the union of all editor options. Like, open this uri as any editor, if it's a text editor use these options, if it's a foo editor use these options etc

**Comment by jrieken** [comment]
> We have a ignoreOverrides editor option that we could simply add to this options bag [1]

👍 thanks. I have pushed a change that uses this flag

**Comment by bpasero** [comment]
Sounds good. I feel that we should then close this issue for the actual bug I filed and be able to verify it and have a new issue for the new API.

**Comment by jrieken** [comment]
Agreed - I'd say we fold the API request into the "expose editor tab model api request"
