### ISSUE TITLE
git.terminalAuthentication requires terminal restart to take effect

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#96399]
Refs: https://github.com/microsoft/vscode/issues/96280

Ubuntu 18
1. Open a terminal, nicely clone a private repository and see how the login flow to GH works nicely
2. Change `git.terminalAuthentication` to false
3. Go back to the open terminal and do some git commands in the private repo -> they still work. The change to my setting was not applied 🐛 

I would expect that the setting description notes that the terminal should be restarted. Or even better that the terminal listens on changes in this setting.

**Comment by joaomoreno** [comment]
This is how the terminal environment feature works. Notice the top right corner of the terminal. As you toggle the setting it should switch from an information to a warning icon. This is because there is no way to "hot swap" environment variables in a terminal.

**Comment by Tyriar** [comment]
The idea came up of relaunching terminals automatically if they had received no input in the UX call, but this case still wouldn't be covered and should not be covered without manual intervention as we don't know if it's safe to kill the terminal session.

**Comment by isidorn** [comment]
That all makes sense, however I think you can still mention this in the setting description. That the terminal needs to be restarted for this to take effect.

**Comment by joaomoreno** [comment]
Yup, good point.
