### ISSUE TITLE
Can't get extension provided view containers back

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#96393]
Testing https://github.com/microsoft/vscode/issues/96318

For example, take the GitHub Pull Request extension.

- Move the issues view into it's own view container in the sidebar.
- Move the pull request view into it's own view container in the sidebar.
- How can I get my GitHub view container back? Having to reset all view location seems a bit heave since I may have done other customizing I want to keep.

**Comment by sbatten** [comment]
individual views can be reset to their default locations, right click the view header, `reset view location`
