### ISSUE TITLE
Request: add 'Open' to Find in files results

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/vscode#96395]
It would be great to add 'Open File' to this menu:

![image](https://user-images.githubusercontent.com/172594/80488705-ab28ec00-8956-11ea-8f1c-854caf8e735f.png)

Use case: I want to search for some text in my open folder, but rather than just replace it, I'd like to do some specific work around where the file mentions the text.

**Comment by roblourens** [comment]
Don't you want to left-click the match to see that match in the file?
