### ISSUE TITLE
Snippet descriptions are not localized

### ISSUE THREAD

**Issue by Wanye1062271859** [microsoft/vscode#96396]
VSCode Version: 1.44.2
OS Version: Windows x64 10.0.18363
Language: Non-English

**Steps to Reproduce:**
1. Open a workspace which contains .cpp files
2. Open a cpp file
3. Type "#region" 

Expected:
The intellisense tip "Folding Region..." was localized

Actual:
"Folding Region..." was not localized
![image](https://user-images.githubusercontent.com/29274719/80491102-d9c5b780-8994-11ea-852a-f94fd982219f.png)

**Comment by aeschli** [comment]
The description comes from a snippet file. We don't have a localization story for snippets.
