### ISSUE TITLE
Numbering items in the Explorer

### ISSUE THREAD

**Issue by Jacquers** [microsoft/vscode#96390]
I'd like to have numbering for the items in the tree view, similar to how the editor has line numbers. Configurable. It would be useful if you have a long list of similar items (e.g. I was working with a directory of .sql files). If there is already an extension for this, please point me in the right direction, thanks.

**Comment by alexr00** [comment]
Sounds like a feature request to have a setting that turns on some numbering for trees.

**Comment by joaomoreno** [comment]
This won't ever happen for the tree itself, but rather for each tree instance. The tree doesn't own what is rendered inside each tree element. Which VS Code feature tree would you like this in? The file explorer?

**Comment by Jacquers** [comment]
Yes, the Explorer :)

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
