### ISSUE TITLE
Notebook: message can overflow the cell

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96404]
Refs: https://github.com/microsoft/vscode/issues/96279

![image](https://user-images.githubusercontent.com/900690/80490745-1d52fe00-8962-11ea-89d3-c3973fdf552f.png)

It looks like a long enough string can overflow the cell.

//cc @jrieken

**Comment by jrieken** [comment]
@rebornix this is error output, not "normal" output. https://github.com/microsoft/vscode-github-issue-notebooks/blob/3c2a56faa435ce4d250b9344f16f7e1432d37b80/src/notebookProvider.ts#L142
