### ISSUE TITLE
Notebook: registers duplicate working copies with same resource

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96402]
Refs: #96279

I noticed an error telling me that a working copy with a notebook URI was already registered. There can only ever be one working copy registered for a given resource. Please check that this is the case. And keep in mind that the registration needs to be disposed when the model is gone.

In this particular case I was opening a notebook in the plain text editor.

`Cannot register more than one working copy with the same resource vscode-notebook://vsonline%2Bbace8651-cbe6-4eeb-9183-649c2faf82d4/home/vsonline/workspace/electron/foo.github-issues.`

**Comment by jrieken** [comment]
@rebornix I have pushed a workaround for this that ensures that there is only one instance of NotebookEditorInput per resource. Tho, there is also [`_resourceMapping`](https://github.com/microsoft/vscode/blob/93b38d7298cd4ea8b8d9234d80f2cf7dcb6fefc1/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts#L176) which I am not sure about

Anyways, talked to @bpasero and the better approach is to register/cache a model, not the input.

**Comment by bpasero** [comment]
For reference: text editor inputs (`FileEditorInput`) are all cached by resource, so I think having a cache for notebooks is fine too. But what drives the working copy is a model and not the editor input. The editor input is just delegating into the model for things like saving or eventing. The model is unique and single per resource.

**Comment by rebornix** [comment]
> what drives the working copy is a model and not the editor input

👍 we should then implement the working copy delegate in the `NotebookTextModel` instead of the input.

**Comment by rebornix** [comment]
The `NotebookEditorInput` is already a slim object dedicated to Tabs and working copy service is registered only in `EditorModel`, which is a 1-1 mapping to resource URI.
