### ISSUE TITLE
Trackpad: Tab switch on mouse scroll: horizontal scrolling sensitivity too high

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#96409]
Refs: https://github.com/microsoft/vscode/issues/95952

1. "workbench.editor.scrollToSwitchTabs": natural
2. Have a mouse with horizontal press
3. Horizontal scroll is too senstivie in the tab area and seems pretty useless due to that

Vertical scroll works just fine. And horizontal scroll in the editor has good sensitivity so maybe you could check with Alex how he handles the horizontal scroll.

**Comment by bpasero** [comment]
@isidorn I assume you tested this from the balcony where you have no external mouse attached but the macOS touchpad?

**Comment by isidorn** [comment]
@bpasero no it is raining, and I am on the balcony only for the standup.
This is with an external mouse. The MS one. The small scroll can be pressed left and righ.

**Comment by bpasero** [comment]
Up for help: the code that checks for the wheel event is here:

https://github.com/microsoft/vscode/blob/ca0af15b543f83f48a80f2644272718d5a327542/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L325-L358

**Comment by garyshell** [comment]
To add my specifics here from #97265, I am on a Mac and using a Mac "Magic Mouse" that mimics a trackpad for horizontal and vertical scrolling.  Both of those work as expected within an editor window, but when using horizontal scroll in the tabs, it shoots instantly to the last tab when scrolled right and instantly to the first tab when scrolling left.

**Comment by texastoland** [comment]
@bpasero Maybe it's obvious but the issue looks like a tab change is triggered every single scroll event. It just needs throttled with at least 100 ms threshold. There's already a decorator in common:
https://github.com/microsoft/vscode/blob/e0639de66595b5e4e41c9b3d0116f865237ff8a5/src/vs/base/test/common/decorators.test.ts#L167-L174

**Comment by bpasero** [comment]
@texastoland happy to test this out in a PR. I gave debouncing a very brief try and felt it was not working, but I was not using that annotation but something else.

**Comment by texastoland** [comment]
I'll give it a shot 🤙🏽

**Comment by rightaway** [comment]
I'm having the opposite problem when using the mouse scroll wheel. When I scroll, there's a delay before it switches. In other applications like browsers it switches immediately. And even if I use keyboard shortcuts in vscode to switch tabs they switch immediately, so something is different about the scroll behavior.

**Comment by SerenaPaley** [comment]
Hi, I would like to try solving this problem. I am from Grace Hopper OSD

**Comment by isidorn** [comment]
@texastoland thanks
