### ISSUE TITLE
Scroll to switch tabs: Reverse mode is strange when tabs overflow

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#96405]
Testing https://github.com/microsoft/vscode/issues/95952

I find the `reverse` setting value to be quite weird in this situation:

1. Have a bunch of open tabs, let's say 10
2. Scroll all the way to the right and open the first tab

Now, scroll up, next tab will be selected. Again, next tab will be selected. Repeat until you get to the last tab. Scroll up once more, you actually scroll up, but no tab changes. Again, you keep scrolling up. Repeat until you get to the far left of the scroll view.

It's very strange that always scrolling in the same direction will take me to the far right and then to the far left.

Is `reverse` really important to have as a setting? And if we reverse it, shouldn't the scrolling be reverse too? Those two should be identical right?

**Comment by bpasero** [comment]
I like that idea of having a setting to change the scrolling direction which then has an impact on this too. I think I will go ahead and change the setting to be just a `boolean`.
