### ISSUE TITLE
Notebook: input reports dirty even with auto save on

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96400]
Refs: https://github.com/microsoft/vscode/issues/96279

You want to copy this behaviour over to your editor input which will hide the dirty indicator when auto save is on.

https://github.com/microsoft/vscode/blob/abb4a35cfc26102f93fd00df7b59ce1a19c2017a/src/vs/workbench/contrib/customEditor/browser/customEditorInput.ts#L121-L131

**Comment by rebornix** [comment]
Verifier: please validate that when auto save is set to after delay, you don't see the dirty indicator.
