### ISSUE TITLE
Never ending progress when forgetting to register custom editor provider

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#96407]
Testing #96315

* Have an extension with the following `package.json`:
```
    ...
    "activationEvents": [
        "onCustomEditor:my.custom.editor"
    ],
    ...
    "contributes": {
        "customEditors": [
            {
                "viewType": "my.custom.editor",
                "displayName": "My Custom Editor",
                "selector": [
                    {
                        "filenamePattern": "*.bin"
                    }
                ]
            }
        ]
    }
```
* Have the extension have a main file with an `activate` method that doesn't do anything
* Open a file with the extension `.bin`:
* Observe, there is a spinner that never stops and no message is presented to informat that an editor is missing or cannot be loaded:

![Kapture 2020-04-28 at 15 26 56](https://user-images.githubusercontent.com/5047891/80492729-baaf3180-8964-11ea-8c84-85ea68447945.gif)

**Comment by mjbvz** [comment]
Closing this since we have not seen reports of it causing problems for users. This is also the behavior of normal webviews
