### ISSUE TITLE
Notebook: splitting editor results in "Cannot read property sendMessage of undefined"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96401]
Refs: https://github.com/microsoft/vscode/issues/96279

* open a GH notebook
* click on split button

=> 🐛 `Unable to open 'foo.github-issues': Cannot read property 'sendMessage' of undefined.`

**Comment by rebornix** [comment]
I don't always see this happening, but when it happens, the error is from webview internals.

**Comment by rebornix** [comment]
Already fixed in Insiders.
