### ISSUE TITLE
Terminal link detection doesn't handle words of non-english characters

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#96416]
Testing #96299

```sh
touch '我是学生.txt'
touch '我是很酷.txt'
ls
```

If I hover one of those names, only one character is highlighted. I figured words would just be delimited by whitespace and some characters like `()[]` etc

**Comment by Tyriar** [comment]
Good find, I think it's happening because to the right of each wide char is an "empty" char which is probably being interpreted as a space

**Comment by Tyriar** [comment]
Fixed this but there is still a glitch where the underline will show on an extra character, this is in xterm.js deferred to https://github.com/xtermjs/xterm.js/issues/2887
