### ISSUE TITLE
Take performance profile should be a button in the debugger floating tool bar

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#96417]
Testing https://github.com/microsoft/vscode/issues/96305

Like with the stop button.

**Comment by connor4312** [comment]
Thanks for the issue. We considered this, but initially decided that placing a button there might be too prominent for an action that users will only take in a small proportion of debugging sessions.  cc @misolori for thoughts here.

**Comment by misolori** [comment]
We could add it as a setting and/or always show it once the user has taken a profile. We did explore surfacing this in the call stack view:

![image](https://user-images.githubusercontent.com/35271042/80632316-f3eeac80-8a0b-11ea-90c6-d6374d15dd8f.png)

**Comment by dbaeumer** [comment]
Having it in the call stack view would be fine for me as well.

**Comment by connor4312** [comment]
We very recently added this 🙂 It's not the same icon as in the screenshot.

![](https://memes.peet.io/img/20-04-c06ca69f-d0b8-4818-8770-5cb8ac456ff1.png)

Opened https://github.com/microsoft/vscode-codicons/issues/13 to get the codicon
