### ISSUE TITLE
Screen cheese with terminal info icon

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96419]
* have a terminal that shows the I
* open search
* 🧀 both overlap unpleasantly 

<img width="316" alt="image" src="https://user-images.githubusercontent.com/1794099/80496936-1c25cf00-896a-11ea-8a84-9b44290af373.png">

**Comment by jrieken** [comment]
@Tyriar How do I now see this notification/warning?

**Comment by Tyriar** [comment]
`"terminal.integrated.environmentChangesIndicator": "on"`

**Comment by jrieken** [comment]
thanks
