### ISSUE TITLE
Executing workbench.files.action.* commands

### ISSUE THREAD

**Issue by sleistner** [Microsoft/vscode#9641]
Is there a way to execute any of the `workbench.files.action` commands from an extension?

**Comment by kieferrm** [comment]
You can execute some of them like this `vscode.commands.executeCommand('workbench.files.action.focusFilesExplorer');`.

**Comment by sleistner** [comment]
I'm particularly interested in `workbench.files.action.renameFile`.
Would that be possible?
If not what is the design decision behind it?
