### ISSUE TITLE
Weird character on terminal name

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#96412]
- Drag terminal into explorer pane
- "Reset view location"
- Now it looks like this

![image](https://user-images.githubusercontent.com/323878/80494559-64be9780-892c-11ea-8494-08655cc26704.png)

**Comment by Tyriar** [comment]
@sbatten know what this could be?

@roblourens can you check what HTML content it is and what the bad character is?

**Comment by roblourens** [comment]
It's this codicon 
![image](https://user-images.githubusercontent.com/323878/80509551-326a6580-893f-11ea-87bf-1486377d7036.png)

**Comment by sbatten** [comment]
duplicate #96121
