### ISSUE TITLE
Markers viewlet goes empty when being dragged

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96413]
while verifying #94530

[Screen Recording 2020-04-28 at 15.41.37.mov.zip](https://github.com/microsoft/vscode/files/4546096/Screen.Recording.2020-04-28.at.15.41.37.mov.zip)

* see attached recording 🔝 
* show markers
* have file with errors
* drag marker to sidebar
* drag back to bottom panel
* :bug: panel is empty, content is gone

**Comment by sbatten** [comment]
okay, this is the third issue around moving a default view container to and from the sidebar causing issues. have a feeling there is a singular issue in the moving view containers logic.

**Comment by sandy081** [comment]
Looks like panel composite is not removed on deregister - https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/parts/panel/panelPart.ts#L225

Hence ViewPaneContainer.create is not called when view container is moved back to panel.
