### ISSUE TITLE
Can't debug Node app in WSL

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#96411]
Testing #96296

When using the new debugger in a WSL repo:

![image](https://user-images.githubusercontent.com/22350/80494067-850b4800-8966-11ea-8e8b-29e814331cbf.png)

Works fine in a Windows folder.

I've tried using `browserLaunchLocation`, but that seems available to `pwa-chrome` only.

**Comment by connor4312** [comment]
This is the same as https://github.com/microsoft/vscode-js-debug/issues/451 -- please let me know if you continue to hit this on the latest Insiders!
