### ISSUE TITLE
Add javascript.format.insertSpaceAfterNameForNamedFunctions option

### ISSUE THREAD

**Issue by wrummler** [Microsoft/vscode#9642]
- VSCode Version: 1.3.1
- OS Version: Windows 7 Pro 64-bit

It'd be nice to have an option like `javascript.format.insertSpaceAfterNameForNamedFunctions` such that setting it to `true` causes Alt+Shift+F to reformat `function foo() { }` to `function foo () { }`.

This could be done with a more generic solution by inferring from linter options as mentioned via #4374. However, some tools might enforce options in a way that inferring could possibly be difficult (says me, a pretty serious JS newbie). For example, when using [`standard`](https://www.npmjs.com/package/standard) and [`vscode-standardjs`](https://marketplace.visualstudio.com/items?itemName=chenxsan.vscode-standardjs), I'm not sure how this rule's presence could be easily detected. (But maybe I just haven't thought about it hard enough.)

**Comment by dbaeumer** [comment]
Moving to TS team.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#10132
