### ISSUE TITLE
vscode causes all files with mime video/* to have a .ts (typescript) file icon thumbnail

### ISSUE THREAD

**Issue by wafiazmihartono** [microsoft/vscode#96426]
- VSCode Version: 1.44.2
- OS Version: Windows 10 1909 build 18363.815

Steps to Reproduce:

1. Install vscode with these options checklisted:

- Add "Open with Code" action to Windows Explorer file context menu
- Add "Open with Code" action to Windows Explorer directory context menu
- Register Code as an editor for supported file types
- Add to PATH (requires shell restart)

I think it is the third point that causes the problem

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
File association in Windows doesn't work at the mime level, but at the file extension level. So what file extensions are these video files?
