### ISSUE TITLE
[feature request] support for syntax highlight of inline GLSL shader literals in C++ code

### ISSUE THREAD

**Issue by DoDoENT** [microsoft/vscode#96424]
Currently, the default C++ syntax highlight allows special syntax highlight of C++ raw string literals for SQL and regular expressions by using `sql` and `re` prefixes.

It would be great to provide the same features for GLSL shaders, as they are also common in C++ raw string literals.

I've created a PR on [cpp-textmate-grammar repository](https://github.com/jeff-hykin/cpp-textmate-grammar/pull/472) with this feature added.

Please consider adding this to the default c++ syntax highlighter.

**Comment by alexr00** [comment]
We pull in the grammar updates from https://github.com/jeff-hykin/cpp-textmate-grammar/ about once per month. Currently, there's a [bug ](https://github.com/jeff-hykin/cpp-textmate-grammar/issues/460) that's preventing that. We'll get this change next time we pull in the changes.
