### ISSUE TITLE
DnD a cell is not working as expected

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#96427]
Testing #96279

Check this video.

![Kapture 2020-04-28 at 16 33 46](https://user-images.githubusercontent.com/10746682/80500403-76289380-896e-11ea-8509-95d533aae653.gif)

Here I am trying to drag and drop a cell on the top. Feedback shows I am moving the cell to a position before the target cell but it is moved to a position after the target cell.

**Comment by sandy081** [comment]
Not sure if this is already covered here - https://github.com/microsoft/vscode/issues/96308

**Comment by roblourens** [comment]
Off by one :)
