### ISSUE TITLE
all "languages" supported as extensions.

### ISSUE THREAD

**Issue by leemke** [microsoft/vscode#96422]
Issue Type: <b>Feature Request</b>

I want to know what languages come pre-installed with basic Vscode.
I looked into the extensions list. I did not see any, other than the ones I 
installed.  Does that mean that support for other languages does not exist
already installed?  

Would like to see all pre-installed supported capabilities listed as extensions.
Just because it is listed as an extension does not mean it can be uninstalled.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 4.19.98-08076-g24ab33fb8e14

**Comment by IllusionMH** [comment]
You can check pre-installed extension using `@builtin` query in extensions search.

**Comment by leemke** [comment]
Thank you for your response.

Do any of these builtin languages have properties, launch, and tasks json
files? How do you tell vscode
which type of environment you are using (which set of .vscode files to use)?

Thanks again
Lawrence Emke

**Comment by IllusionMH** [comment]
Not sure what you try to ask and why, but they are regular extensions and you can check their code in folder https://github.com/microsoft/vscode/tree/master/extensions

**Comment by sandy081** [comment]
Same here.. not sure what is your question. Can you please explain what you are looking for?
