### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node..

### ISSUE THREAD

**Issue by MaxwellHarper** [microsoft/vscode#96432]
Issue Type: <b>Bug</b>

Unable to open 'auth-success.html': Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.. 

I recently installed the "Glitch" extension ... not sure id this has anything to do with the issue. 

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (5.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.29
vscode-npm-script|eg2|0.3.11
vscode-npm|fkn|3.3.0
csv-to-table|php|1.2.3

</details>

**Comment by alexr00** [comment]
Can you provide steps to reproduce this issue?

**Comment by RMacfarlane** [comment]
@MaxwellHarper I believe this is being caused by the extension and not VSCode, we have no file called 'auth-success.html' in our sources. The "Glitch" extension is closed source so I'm not able to confirm that it's the problem by searching. What were you doing before you saw this error message?
