### ISSUE TITLE
Notebook: first cell has a "Ctrl+Enter to run" but not play button

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96438]
Refs: https://github.com/microsoft/vscode/issues/96279

Unclear to me why the first cell has no run button, but same indication for using Ctrl+Enter to run?

![image](https://user-images.githubusercontent.com/900690/80509270-79754c80-8979-11ea-9012-ad5fde82fe72.png)

**Comment by jrieken** [comment]
In the first cell, there is nothing to run. Only a variable is defined. The "Ctrl+Enter" message is gone in latest insiders which seems not to be deployed. fyi @roblourens

**Comment by bpasero** [comment]
Yeah I am on yesterdays version it seems.

**Comment by bpasero** [comment]
Now I see a "Play" button but not the "Ctrl+Enter" thing?

![image](https://user-images.githubusercontent.com/900690/80578654-19c68200-8a09-11ea-93b5-109e9d7924cc.png)

**Comment by jrieken** [comment]
Yeah, ctrl+enter is gone. The play button is maybe there because the cell is empty 🤔

**Comment by jrieken** [comment]
fyi - I have pushed a change that makes sure empty/new cells aren't runnable
