### ISSUE TITLE
When saving Notebooks, give me details about which cells are new

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#96435]
Related to #96433 I have been storing metadata for Markdown cells. I store this in a `Map` in the _renderNotebook_ function.

However, if I create new markdown cells while in Notebook Mode (and save the document), the render function doesn't get run again and so the metadata isn't updated. To get around this, I added:

https://github.com/TylerLeonhardt/vscode-powershell/blob/fe8576bda498b81f89f05806b2667d8c50e0f6a9/src/features/PowerShellNotebooks.ts#L155-L156

That will set the metadata for markdown cells that don't exist in my `Map` but this is not really ideal... Ideally, I get some hook or property somewhere of the new cells that are being saved to the file so I can process them in any way I choose.

cc @rebornix

**Comment by jrieken** [comment]
By now we have events that fire whenever a cell is added to a notebook (`onDidChangeNotebookCells`). This event should allow you to keep track of things.
