### ISSUE TITLE
Cannot open notebook in file-only workbench

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96436]
* have this setting `"window.openFilesInNewWindow": "on"`
* open an existing issues notebook 
* :bug: the notebook opens as text file, not notebook
* :bug: there is no reopen with command

**Comment by jrieken** [comment]
@bpasero notebooks use [`EditorService#overrideOpenEditor`](https://github.com/microsoft/vscode/blob/93b38d7298cd4ea8b8d9234d80f2cf7dcb6fefc1/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts#L130) to hook into editor opening. This works well but it seems that it is skipped when opening a notebook file in a new workbench (setting above)

**Comment by bpasero** [comment]
Hm, no. this is already broken for images too.

@mjbvz can you please take a look? E.g. when I do `code <path to PNG>`, it does not open your image preview.

**Comment by mjbvz** [comment]
Moving out of April since notebooks are not shipping yet

**Comment by mjbvz** [comment]
@sandy081 Custom editors rely data from the custom editors extension point:

https://github.com/microsoft/vscode/blob/70a890efb6601c04e5235b06e537bdf47d85281d/src/vs/workbench/contrib/customEditor/common/contributedCustomEditors.ts#L34

Early in startup, `setHandler` has not yet been fired so we don't think there are any custom editors. What is the recommendation if we need extension point data early on in startup? Should we add a promise that is resolved when `setHandler` is called for the first time?

**Comment by bpasero** [comment]
One thing to note: be careful with adding code on the critical startup path that waits on the extension host to be ready because that may result in deadlocks where the one waits on the other and vice versa. I think we had these issues in the past, not sure this applies here as well.

**Comment by sandy081** [comment]
@alexdima is the right person to answer about extension point handling.

**Comment by alexdima** [comment]
@mjbvz `IExtensionService.onDidRegisterExtensions` is the event which fires after all the extensions have been registered and their extension points got handled. For convenience, the very same is available in the form of a promise at `IExtensionService.whenInstalledExtensionsRegistered`.

**Comment by mjbvz** [comment]
3c3c2fd cache the editor information in a memento to avoid delaying startup. I believe that the cache should match your installed custom editors in almost all cases, although I can think of instances where the cached data may be inconsistent with the actual extensions (such as uninstalling extensions from the command line)

@rebornix You will likely need to do something similar for notebooks
