### ISSUE TITLE
RegExp should match `\w` on all `.* Letter` Unicode categories

### ISSUE THREAD

**Issue by kimbar** [microsoft/vscode#96431]
Issue Type: <b>Bug</b>

Type

```
Żółty
```

Try to find `\w+`

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:33:57.013Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-profile-switcher|aar|0.3.3
vscode-sqlite|ale|0.8.1
markdown-mermaid|bie|1.4.3
vscode-markdownlint|Dav|0.35.1
vscode-eslint|dba|2.1.5
python-preview|don|0.0.4
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-statusbar-debugger|fab|2.0.6
vscode-pyvmmonitor|fab|0.0.3
vscode-firefox-debug|fir|2.7.2
code-runner|for|0.9.17
github-linker|gim|0.2.3
fortran|Gim|0.2.0
beautify|Hoo|1.5.0
output-colorizer|IBM|0.1.2
vscode-ebnf|igo|1.0.3
latex-workshop|Jam|8.9.0
vscode-edit-csv|jan|0.2.6
vscode-github|Kni|0.30.3
l13-projects|L13|0.13.2
restructuredtext|lex|126.0.0
git-graph|mhu|1.22.0
mssql|ms-|1.9.0
python|ms-|2020.4.76186
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
cpptools|ms-|0.27.0
vsc-nwjs|rua|1.0.18
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
guides|spy|0.9.3
rewrap|stk|1.9.1
reflow-paragraph|Tro|1.3.0
vscode-svg-previewer|vit|0.5.1

</details>

**Comment by rebornix** [comment]
`\w` in JavaScript regex is `[a-zA-Z0-9_]` so currently it doesn't match Unicode letter.
