### ISSUE TITLE
InputBox: prompt should support codicons

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#96430]
This should get me a `codicon-add` icon in the input box prompt label:

```
			const input = await vscode.window.showInputBox({
				placeHolder: 'Name',
				prompt: '$(add) Create'
			});

```

**Comment by chrmarti** [comment]
@joaomoreno I guess this must be trivial, do you have a code pointer on how to do it?

**Comment by joaomoreno** [comment]
Yeah, here's me adopting it in the Button class: https://github.com/microsoft/vscode/commit/b005f534a60e8ba622ca1416cf8c517b674f2fcd

**Comment by joaomoreno** [comment]
Pushing out to August.
