### ISSUE TITLE
NotebookConcatDocument.locationAt does not report error on illegal arguments

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#96444]
Refs #96282:

Use zipped project from https://github.com/microsoft/vscode/issues/96439#issue-608430537
and replace `provideDefinition` with this:

```ts
	provideDefinition(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken): vscode.ProviderResult<vscode.Definition | vscode.DefinitionLink[]> {

		const project = this.container.lookupProject(document.uri);

		if (project.concatDoc) {
			const loc = new vscode.Location(document.uri, position);

			// map cell doc location to concat document position
			let pos = project.concatDoc.positionAt(loc);

			// errorneous "goto definition": go to a line outside of document
 			pos = new vscode.Position(pos.line+1000, pos.character);

			// map concat document position back to cell doc location
			try {
				const newLocation = project.concatDoc.locationAt(pos);
				return newLocation;
			} catch(e) {
				console.log('oops');
			}
		}
		return undefined;
	}
```
`locationAt` does not report error if position's line is out of range.

**Comment by jrieken** [comment]
Today, the concat document wants to be graceful and always returns something. This aligns with how `positionAt` and `offsetAt` work in `vscode.TextDocument` work. Still, it might be better to return `undefined` in this (and similar cases), or at least have the equivalent of `vscode.TextDocument.validate[Range|Position]`

**Comment by jrieken** [comment]
The auto-adjust behaviour is still as before but I have added validateRange, validatePosition, and contains. This keeps it aligned with text documents but still allows you to check ranges et al
