### ISSUE TITLE
Terminal environment info indicator in wrong place

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#96441]
I saw this randomly a couple times while playing with the terminal today. I don't have good steps but I just saw it after hiding/showing the panel a couple times. It goes to the correct spot if I resize the panel or window

![image](https://user-images.githubusercontent.com/323878/80509762-71002000-893f-11ea-9c7c-009f54f0f61f.png)

**Comment by Tyriar** [comment]
I think this has the same root cause as https://github.com/microsoft/vscode/issues/96586

/duplicate
