### ISSUE TITLE
Notebook: cell language selector should open dropdown menu at location not quick pick

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96445]
Refs: https://github.com/microsoft/vscode/issues/96279

Clicking the "Cell Language Selector" imho should just open a menu at the point where I click (similar to code actions) and not quick pick which is in a different part of the screen potentially.

![image](https://user-images.githubusercontent.com/900690/80512296-914ecf80-897d-11ea-9bdb-3cc14d0e012c.png)

**Comment by roblourens** [comment]
I think we have lots of ux that works this way and we should stay consistent
