### ISSUE TITLE
suggestion: put stars rating to left of downloads in extension viewlet

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#9644]
- VSCode Version: 1.4 Insiders

i like how we reduce some of the UI noise by showing a single star with the # of reviews (or stars, honestly i dont know)  but it looks like its clipped

![image](https://cloud.githubusercontent.com/assets/1487073/17074889/7eb6f848-5038-11e6-9f36-52a298f34f12.png)

suggestion: put the stars before the number of downloads and left align them

![image](https://cloud.githubusercontent.com/assets/1487073/17074926/1e73e6c0-5039-11e6-868b-71c97cd47262.png)

**Comment by joaomoreno** [comment]
Sorry man. 🍺
