### ISSUE TITLE
Notebook: "Open in Browser" opens no tab or just 1

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96440]
Refs: https://github.com/microsoft/vscode/issues/96279

Having < 10 issues and clicking the "Open in Browser" action only seems to open 1 browser tab and when having more than 10, I get a dialog asking me if I really want to open (e.g. 11) tabs, but none open.

![image](https://user-images.githubusercontent.com/900690/80509536-d96bf300-8979-11ea-841a-f46578b3e6e8.png)

**Comment by jrieken** [comment]
reference: https://github.com/microsoft/vscode-github-issue-notebooks/blob/df7e55de8aaacd4040ef0d851cda1cb2d6bd559d/src/commands.ts#L53

**Comment by jrieken** [comment]
> I get a dialog asking me if I really want to open (e.g. 11) tabs, but none open.

That's actually a good find

**Comment by bpasero** [comment]
> This calls the openExternal API and that's likely defunct in the web case?

That would not explain why it works for 1 issue. We also use this API a lot for opening auth callbacks, so I think the only thing going wrong is opening more than one link one after the other.

This should end up here I guess?

https://github.com/microsoft/vscode/blob/3dcbfe2b70b7cb4626201b77f0fd6676e961f2c7/src/vs/workbench/api/browser/mainThreadWindow.ts#L45

**Comment by bpasero** [comment]
Popup blocker!

**Comment by sbatten** [comment]
it doesn't seem like there was any code fix here, just allowing popups. I test in web and allowed popups and saw all the tabs open.

**Comment by jrieken** [comment]
One fix happened in the other repo and I forgot to link it here...
