### ISSUE TITLE
Theme selection instantly closes if focused tab is Markdown preview

### ISSUE THREAD

**Issue by cycron** [microsoft/vscode#96449]
Issue Type: <b>Bug</b>

If the focused tab is a Markdown preview, the "Select theme" menu instantly closes upon opening it.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (26.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-m3u|af4|1.0.0
Bookmarks|ale|11.1.0
language-mcfunction|arc|0.16.0
vscode-language-pack-de|MS-|1.44.2
python|ms-|2020.4.76186
material-icon-theme|PKi|4.1.0
ayu|tea|0.18.0
vscode-todo-highlight|way|1.0.4
material-theme|zhu|3.3.1

(10 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate and already fixed in the upcoming release
