### ISSUE TITLE
Notebooks: show errors in overview ruler

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96442]
Refs: https://github.com/microsoft/vscode/issues/96279

I think it would be great if errors in a notebook could be shown in the overview ruler:

![image](https://user-images.githubusercontent.com/900690/80511240-218c1500-897c-11ea-8860-49b5f24cc33d.png)

//cc @jrieken

**Comment by jrieken** [comment]
I also somewhat surprised that there is no squiggle for the reported error

**Comment by bpasero** [comment]
I think in my screenshot the error did show up in the cell, I just had it scrolled out of view here for showing why I like the idea of having overview ruler decorations.

**Comment by rebornix** [comment]
Valid feature request, we should have an overview ruler for the notebook editor which accepts contributions. On the overview ruler we can show diagnostics and scm.
