### ISSUE TITLE
Notebook: there should be an affordance to add Code/Markdown above first cell

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96446]
Refs: https://github.com/microsoft/vscode/issues/96279

Currently it looks like you can only add below:

![image](https://user-images.githubusercontent.com/900690/80512514-e38ff080-897d-11ea-8b7b-f9da3cc0d46e.png)

**Comment by misolori** [comment]
This is issue keeps coming up in the Python Notebook user studies, we should find a way to make this happen. Maybe an invisible cell at the top or a custom area where we can trigger the toolbar.

**Comment by misolori** [comment]
@rebornix fixed this last week, you can now add cells above the first cell.

![image](https://user-images.githubusercontent.com/35271042/90354932-9bb1d980-dfff-11ea-8540-6b15f94cbbca.png)
