### ISSUE TITLE
Clicking tab of open non-default editor reopens it with the default editor

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#96455]
Test #96312

- Setup steps in test issue
- Open .github-issues file
- "Reopen with" cat scratch editor
- Click the editor tab
- It switches back to the notebook editor

![Apr-28-2020 11-54-59](https://user-images.githubusercontent.com/323878/80515577-c8a28980-8947-11ea-976a-89469a6fc221.gif)

**Comment by rebornix** [comment]
Verifiers:

* Install the [Github issue notebooks](https://github.com/microsoft/vscode-github-issue-notebooks extension
* Create a `test.github-issues` file
* Open the file
* Reopen the file with text editor from command palette: "File: Reopen with ..."
