### ISSUE TITLE
Resetting view location causes rendering issue in panel

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#96452]
![image](https://user-images.githubusercontent.com/35271042/80513579-1dd4a000-8934-11ea-9971-6fab7d265b2f.png)

1. Move output and debug console to sidebar
2. Reset their view location
3. :bug: The font is displayed weirdly and the icon sometimes appears

This does not appear to affect Problems and the Terminal

**Comment by sbatten** [comment]
duplicate
