### ISSUE TITLE
Moving split views into panel causes problems to show multiple inputs

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#96453]
![image](https://user-images.githubusercontent.com/35271042/80513988-bbc86a80-8934-11ea-9208-baa38c6a170a.png)

1. Move terminal to sidebar
2. Move problems to sidebar and split with the terminal
3. Move terminal back to panel (not reset)
4. :bug: problems panel shows multiple inputs

**Comment by sbatten** [comment]
@sandy081 thought you already fixed this one

**Comment by sbatten** [comment]
its possible this only breaks whenever the codicon issue we see up there is in action

**Comment by sandy081** [comment]
Yeah I thought so too

**Comment by sandy081** [comment]
Caused due to listener leaks which did not get dispose.
