### ISSUE TITLE
Data migration tests do not work anymore

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#96459]
#96319

  1) VSCode Smoke Tests (Electron)
       Data Migration: This test MUST run before releasing by providing the --stable-build command line argument
         verifies opened editors are restored:
     Error: Timeout: get element '.tabs-container div.tab.active[aria-selected="true"][data-resource-name$="Untitled-1"]' after 20 seconds.
      at /home/parallels/vscode/test/automation/out/code.js:174:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/parallels/vscode/test/automation/out/code.js:9:58)

  2) VSCode Smoke Tests (Electron)
       Data Migration: This test MUST run before releasing by providing the --stable-build command line argument
         verifies that 'hot exit' works for dirty files:
     Error: Timeout: get element '.tabs-container div.tab.active.dirty[aria-selected="true"][data-resource-name$="readme.md"]' after 20 seconds.
      at /home/parallels/vscode/test/automation/out/code.js:174:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/parallels/vscode/test/automation/out/code.js:9:58)

  3) VSCode Smoke Tests (Electron)
       Dataloss
         verifies that 'hot exit' works for dirty files:
     Error: Timeout: get element '.tabs-container div.tab.active[aria-selected="true"][data-resource-name$="readme.md"]' after 20 seconds.
      at /home/parallels/vscode/test/automation/out/code.js:174:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/parallels/vscode/test/automation/out/code.js:9:58)

Works when run manually

**Comment by bpasero** [comment]
Yeah I think I can reproduce, somehow the one window does not close.

**Comment by bpasero** [comment]
Still broken due to https://github.com/microsoft/vscode/issues/96681. Moving to Eric.
