### ISSUE TITLE
Unable to reset view location for terminal

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#96451]
![image](https://user-images.githubusercontent.com/35271042/80513406-d9490480-8933-11ea-9ece-2af21dc1c59c.png)

I would expect for this view to get the same options to reset the view location as others.

**Comment by sbatten** [comment]
@misolori but the view is in its default location :P. You moved the terminal view container into the side bar so therefore the view is in its default container.

but seriously, view containers need reset as well

**Comment by misolori** [comment]
<img width="100%" src="https://media.giphy.com/media/ANbD1CCdA3iI8/giphy.gif">

**Comment by misolori** [comment]
@sbatten where's the duplicate link?

**Comment by sbatten** [comment]
https://github.com/microsoft/vscode/issues/93836
