### ISSUE TITLE
can not open eatensons

### ISSUE THREAD

**Issue by hehuakun** [Microsoft/vscode#9645]
![2016-07-23 09 44 14](https://cloud.githubusercontent.com/assets/12748014/17075029/15a37494-50ba-11e6-89c4-6bdadbf963a6.png)
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:31:10.994Z)
- OS Version: Darwin x64 15.3.0

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Are you behind a proxy? If so, did you [configure it](https://code.visualstudio.com/docs/customization/userandworkspace)?
