### ISSUE TITLE
Linux Smoke Test: turns off editor line numbers and verifies the live change

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#96458]
#96319

       Preferences
         turns off editor line numbers and verifies the live change:
     Error: Timeout: is active element '.quick-input-widget .quick-input-box input' after 20 seconds.

Works when manually tested.

**Comment by JacksonKearl** [comment]
@bpasero assigning you because it seems the issue is with the quick input

**Comment by bpasero** [comment]
Works fine today:

![image](https://user-images.githubusercontent.com/900690/80573747-d9630600-8a00-11ea-8706-166d142e384e.png)
