### ISSUE TITLE
Notebook: expands weirdly

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96450]
Refs: https://github.com/microsoft/vscode/issues/96279

For a folded region with many items below, I would expect that expanding the region leaves the position stable. But here it seems like it scrolls down too. 

I tried with the GH Notebook.

![Kapture 2020-04-28 at 18 34 15](https://user-images.githubusercontent.com/900690/80513222-07076b00-897f-11ea-9e94-24ce71ae1254.gif)

**Comment by rebornix** [comment]
I'm not seeing this issue anymore in Insiders. We had polishes on cell focus which solves this problem.
