### ISSUE TITLE
ailed to save 'component.tsx': The content of the file is newer. Please compare your version with the file contents.

### ISSUE THREAD

**Issue by pvijeh** [microsoft/vscode#96456]
this "failed to save 'component.tsx': The content of the file is newer. Please compare your version with the file contents." 

is a terrible feature--- please get rid of it.   I want to be able to override a file.

**Comment by alexr00** [comment]
Looks like there is a setting for this: https://github.com/microsoft/vscode/issues/66035#issuecomment-579706551
