### ISSUE TITLE
Linux Smoke Test: Extensions

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#96461]
#96319 

  8) VSCode Smoke Tests (Electron)
       Extensions
         install and activate vscode-smoketest-check extension:
     Error: Timeout: is active element 'div.extensions-viewlet[id="workbench.view.extensions"] .monaco-editor textarea' after 20 seconds.
      at /home/parallels/vscode/test/automation/out/code.js:174:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/parallels/vscode/test/automation/out/code.js:9:58)

**Comment by JacksonKearl** [comment]
@sbatten seems to be a view thing? 

Works when manually run.

**Comment by JacksonKearl** [comment]
See also #96460

**Comment by sbatten** [comment]
same as other, ran fine on windows looks flaky

**Comment by joaomoreno** [comment]
Works for me running on Linux:

```
*** Smoketest setup done!
  VSCode Smoke Tests (Electron)
    Extensions
      ✓ install and activate vscode-smoketest-check extension
  1 passing (12s)
Done in 12.22s.
```

**Comment by sandy081** [comment]
Actually works for me too on Mac.

**Comment by sandy081** [comment]
Thanks @joaomoreno
