### ISSUE TITLE
Should status bar be included in "Focus Next Part"?

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#96468]
Testing https://github.com/microsoft/vscode/issues/96263

Issue Type: <b>Bug</b>

When I was first navigating through all of the parts, I could not tell what was focused when it reached the status bar, since there was no visual change. Once it's focused, I'm not sure how to interact with it, trying to tab to an individual item just shifts focus to the activity bar. Is there actually any action I can take with it using the keyboard?

VS Code version: Code - Insiders 1.45.0-insider (abb4a35cfc26102f93fd00df7b59ce1a19c2017a, 2020-04-28T05:34:21.109Z)
OS version: Darwin x64 18.7.0

**Comment by eamodio** [comment]
I had exactly the same experience. I expected the status bar to show focus on one of the items or something and allow me to move around.

**Comment by isidorn** [comment]
This is good feedback, however we already have this item planned for May to address this concern. https://github.com/microsoft/vscode/issues/95433
And the status bar currently should be included since when it is focused the screen readerer reads it's content.

Due to the above closing as duplicate
