### ISSUE TITLE
Electron 8: Linux smoke test errors

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#96466]
#96316

  9) VSCode Smoke Tests (Electron)
       Localization
         starts with 'DE' locale and verifies title and viewlets text is in German:
     Error: Timeout: get text content 'div[id="workbench.view.explorer"] .split-view-view:nth-child(1) .title' after 20 seconds.
      at /home/parallels/vscode/test/automation/out/code.js:174:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/parallels/vscode/test/automation/out/code.js:9:58)

Seems to work manually.

**Comment by sbatten** [comment]
seems flaky, this ran fine on windows

**Comment by dbaeumer** [comment]
@JacksonKearl which platform are you on?

**Comment by JacksonKearl** [comment]
.deb, Ubuntu 18

**Comment by dbaeumer** [comment]
Thanks!

**Comment by dbaeumer** [comment]
I am closing this issue. The smoke tests passed in the weeks where Electron 8 was in insiders.
