### ISSUE TITLE
Focusing empty editor group is not useful

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#96469]
Testing https://github.com/microsoft/vscode/issues/96263

Issue Type: <b>Bug</b>

1. Close all editors
2. Cycle focus around the workbench using F6

The empty editor group is not skipped, but there is no visual indicator that it has focus, and I don't think I can interact with it in any way.

VS Code version: Code - Insiders 1.45.0-insider (abb4a35cfc26102f93fd00df7b59ce1a19c2017a, 2020-04-28T05:34:21.109Z)
OS version: Darwin x64 18.7.0

**Comment by isidorn** [comment]
Good point. I think we could change the editor part that when it has focus that Enter / space open a new editor.
Another idea for focus on an empty editor is to have the watermark tips be focused and read out.

fyi @bpasero @chmarti

**Comment by bpasero** [comment]
Empty editor groups:
- visually indicate that they are focused
- are useful to get focused as e.g. opening an editor will target it
- are also read out by screen readers afaik

**Comment by chmarti** [comment]
@isidorn It happened again. You mean @chrmarti
