### ISSUE TITLE
The `logname` in the built-in terminal differs, depending on how you launched VSCode

### ISSUE THREAD

**Issue by bramus** [microsoft/vscode#96463]
- VSCode Version: 1.44.2 (Commit ff915844119ce9485abfe8aa9076ec76b5300ddd)
- OS Version: Darwin x64 19.4.0

I'm hopping over from https://github.com/laravel/valet/issues/904#issuecomment-620670136 here, as I've narrowed it down to being VSCode related issue.

Depending on how you launched VSCode, the output of `logname` in the built-in terminal will be different:

1. VSCode is launched from the CLI (using `code`): `logname` will yield your username (cfr. `whoami`).
1. VSCode is launched from the macOS Dock / Spotlight / Finder: `logname` will yield `root`.

This breaks the correct working of `valet share`, as it uses that result to launch `ngrok`:

```
sudo -u "$(logname)" "$DIR/bin/ngrok" …
```

I expected the result for `logname` in VSCode's Terminal to be the same as when running `logname` in `Terminal.app` itself, independent of how I launch VSCode.

### root

1. Launch VS Code from the Dock
1. Open the built-in terminal
1. Type in `logname`
1. See `root` appear

### Username

1. Launch VS Code from the CLI using `code`
1. Open the built-in terminal
1. Type in `logname`
1. See _your username_ appear

Does this issue occur when all extensions are disabled?: Not Applicable as launching VSCode from the CLI will yield the correct result.

**Comment by joaomoreno** [comment]
What does `echo $USER` return in both cases?

**Comment by bramus** [comment]
In both cases `bramus` (my username) is returned.

**Comment by joaomoreno** [comment]
So... how does `logname` work? Unfortunately I don't have a macOS to test this. @bpasero can you check. @deepak1556 any thoughts?

**Comment by bramus** [comment]
Afaik `logname` is a binary shat ships with BSD. More info on https://www.freebsd.org/cgi/man.cgi?query=logname

> The logname utility writes the user's login name to standard output followed by a newline.
> 
> The logname utility explicitly ignores the LOGNAME and USER environment variables because the environment cannot be trusted.

**Comment by bramus** [comment]
if it helps I've created a small testscript to run:

```bash
echo "\$USER: $USER"
echo "logname: $(logname)"
echo "whoami: $(whoami)"
```

Output when running this in `Terminal.app`, or in VSCode that's been launched from the CLI:

```
$USER: bramus
logname: bramus
whoami: bramus
```

Output when running this in VSCode that's been launched from the Dock / Finder / Spotlight:

```
$USER: bramus
logname: root
whoami: bramus
```

**Comment by bpasero** [comment]
Sorry, this is the first time I head about `logname`. 

Is this related to us resolving the shell environment?

//cc @Tyriar

**Comment by Tyriar** [comment]
@bramus currently this is by design but there is this setting `"terminal.integrated.inheritEnv": false` that might fix it? That feature retains the LOGNAME variable but maybe it still works.

https://github.com/microsoft/vscode/blob/151c443411dc2908c2356a2eaf79f5d2747ac44f/src/vs/workbench/contrib/terminal/node/terminalEnvironment.ts#L48-L72

The fix to this might be to remove LOGNAME from that list?

**Comment by bramus** [comment]
Erm, this got auto closed. How do I reopen this @alexr00? And can this be prevented somehow?

**Comment by Tyriar** [comment]
@bramus can you try `"terminal.integrated.inheritEnv": false`?

**Comment by bramus** [comment]
> @bramus can you try `"terminal.integrated.inheritEnv": false`?

That one still yields `root`

**Comment by Tyriar** [comment]
Ok, maybe removing this will fix it then:

https://github.com/microsoft/vscode/blob/151c443411dc2908c2356a2eaf79f5d2747ac44f/src/vs/workbench/contrib/terminal/node/terminalEnvironment.ts#L64

If not I'm not sure if we can fix it. I'll queue a build with that for you to test out.

**Comment by Tyriar** [comment]
Took 4 builds to finally succeed ☹️ 

@bramus can you check if setting inheritEnv to false works with this build? https://az764295.vo.msecnd.net/insider/325bc186522b43100dbb0811b2a767d84c5fef76/VSCode-darwin-insider.zip

**Comment by bramus** [comment]
Doesn't seem to work. With `inheritEnv ` set to `false` I get:

```
$USER: (empty)
logname: root
whoami: bramus
```

**Comment by Tyriar** [comment]
That's a shame, I'm not sure what could fix this then. Seems related to how we launch VS Code.

**Comment by bramus** [comment]
Is there a way (other than having me reply every week, or requesting to reopen) to prevent this issue from getting autoclosed?

**Comment by deepak1556** [comment]
I have removed the label that would trigger this.

Also I haven't looked into this issue yet, so pending triage.

**Comment by bramus** [comment]
Thanks.

**Comment by dodgycoffee** [comment]
No updates on this in a while. Can confirm this is still an issue.

If launched via the dock, returns as root. If launched via CLI, returns proper user. Only happening with VScode as far as I can tell.

**Comment by bramus** [comment]
Also happens in Hyper (see https://github.com/vercel/hyper/issues/3762), so
I guess it's an Electron issue?

>

**Comment by bramus** [comment]
I've filed [an issue over at Electron](https://github.com/electron/electron/issues/26721), and the reply there was as follows:

> This is not an electron issues, this is fundamentally how Cocoa apps works, you can check by making a simple swift app that just exec's `logname` and comparing. Whether it's a bug in Cocoa / macOS is up to your interpretation, but it's definitely not an Electron specific issue 😄

* waves fist at Apple *
