### ISSUE TITLE
Linux Smoke Test: Views

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#96460]
#96319

  5) VSCode Smoke Tests (Electron)
       Language Features
         verifies problems view:
     Error: Timeout: get element '.panel .markers-panel' after 20 seconds.
      at /home/parallels/vscode/test/automation/out/code.js:174:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/parallels/vscode/test/automation/out/code.js:9:58)

  6) VSCode Smoke Tests (Electron)
       Language Features
         verifies settings:
     Error: Timeout: get element '.panel .markers-panel' after 20 seconds.
      at /home/parallels/vscode/test/automation/out/code.js:174:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/parallels/vscode/test/automation/out/code.js:9:58)

  7) VSCode Smoke Tests (Electron)
       Statusbar
         verifies that 'Problems View' appears when clicking on 'Problems' status element:
     Error: Timeout: get element '.panel .markers-panel' after 20 seconds.
      at /home/parallels/vscode/test/automation/out/code.js:174:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/parallels/vscode/test/automation/out/code.js:9:58)

Works when run manually

**Comment by sbatten** [comment]
same as others, flaky

**Comment by JacksonKearl** [comment]
Confused. Why are you assigning me? Shouldn't flakyness be fixed?

**Comment by joaomoreno** [comment]
@JacksonKearl @sbatten All three errors mention `markers-panel` -> @sandy081

**Comment by sandy081** [comment]
I cannot repro them on Mac, I do not have linux set up now and I am setting it.

**Comment by sandy081** [comment]
Works for me on Mac & Linux.
