### ISSUE TITLE
Titles are broken in panel

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#96465]
1. Move terminal to sidebar
2. Move problems to sidebar and split with the terminal
3. Reset view locations

Problems title is shown with icon

<img width="394" alt="image" src="https://user-images.githubusercontent.com/10746682/80520910-6f0f7e80-898a-11ea-9bf8-dbf36be94802.png">

**Comment by sandy081** [comment]
Caused by 66efeebc55f8e01dd929ae17e23e113eb657dbcd

**Comment by sbatten** [comment]
there are a few issues related to this, let me aggregate

**Comment by sbatten** [comment]
resolved the rest to https://github.com/microsoft/vscode/issues/96121

**Comment by sandy081** [comment]
This issue got surfaced because of the change 66efeebc55f8e01dd929ae17e23e113eb657dbcd. Core problem lies while registering the panel. Panel is getting registered with icon which which should not be.
