### ISSUE TITLE
why cant show FULL symbols in vs code 

### ISSUE THREAD

**Issue by SangLiang** [Microsoft/vscode#9647]
When i write Javascript, it shows like that :
![image](https://raw.githubusercontent.com/SangLiang/Blog/gh-pages/pics/vscodeProblem.png)
that is not i want

**Comment by kieferrm** [comment]
@SangLiang what operating system, vscode version, etc? Can you provide some sample code that exhibits this behavior? Thx!

**Comment by SangLiang** [comment]
os:window 7 
vscode version: 1.3.1
when you define a javascript function and use prototype to define another function ,the symbols cant show FULL function name or other infomation.
such as:
![image](https://cloud.githubusercontent.com/assets/7955162/17122880/f0a97a62-5311-11e6-818b-6115dac98760.png)
I just want it can show complete function name , I think it is an easy bug. thx! : )

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/TypeScript/issues/8238
