### ISSUE TITLE
Breakpoints look like they're set immediately based on the gutter but that's not always true

### ISSUE THREAD

**Issue by ivanhernandez13** [microsoft/vscode#96476]
Issue Type: <b>Bug</b>

1. git clone https://github.com/ivanhernandez13/vscode-mock-debug
2. npm install, compile, run the mock debug extension.
3. create a `readme.md` file in your workspace with multiple lines
4. run the "Ask for file name" configuration and select `readme.md`
5. set a breakpoint on any line
6. hit continue (within 5 seconds of step #5)

The breakpoint looks like it's set (filled in red circle) but the debug adapter hasn't finished setting the breakpoint so it will be skipped.

The fork of vscode mock debug contains a simple [change](https://github.com/ivanhernandez13/vscode-mock-debug/commit/601879181fd577b929077868ca55a13e51e606b7) to delay the setBreakpoint response by 5 seconds. This is obviously a contrived example but in a real debugger, the logic to set a breakpoint might take a non-trivial amount of time to finish during which the UI will show no indication the breakpoint is pending. 

Breakpoints can be unverified and are displayed as an outlined red circle. Would it be possible to use the unverified state as the initial state and only change it to the verified state once the debug adapter responds and verifies it?

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2191B CPU @ 2.30GHz (36 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|128.00GB (54.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
lldb-vscode|llv|0.1.0
vim|vsc|1.13.1

</details>

**Comment by weinand** [comment]
@ivanhernandez13 I'll provide an answer...
