### ISSUE TITLE
Calling authentication.login too fast results in an error

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#96478]
```
Version: 1.45.0-insider (user setup)
Commit: abb4a35cfc26102f93fd00df7b59ce1a19c2017a
Date: 2020-04-28T05:36:25.810Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

Refs: https://github.com/microsoft/vscode/issues/96236

Steps to Reproduce:

1. Follow the steps to create an extension with the sample code
2. Immediately after VS Code opens with the extension, trigger that code
3. An error happens:

![](https://memes.peet.io/img/20-04-9155cf35-2434-4cc3-a7f2-9b02489994ba.png)

**Comment by RMacfarlane** [comment]
I also forgot to say in my directions that the extension should add `vscode.github-authentication` as an extension dependency 🤦‍♀️

This is expected without it, the authentication provider takes some time to activate and VSCode will throw when you try to login or getSessions on a provider that doesn't exist. If you don't directly depend on the auth provider, you can also check if the provider exists in the array of `vscode.authentication.providerIds` and register for the `onDidChangeAuthenticationProviders` providers event

**Comment by connor4312** [comment]
Cool, verified that works!
