### ISSUE TITLE
Settings sync stuck on "Turning on settings sync..."

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#96479]
Issue Type: <b>Bug</b>

Running out of OSS. I'm not signed into any account, and have confirmed that both auth provider extensions successfully activate.

<img width="337" alt="Screen Shot 2020-04-28 at 12 30 41 PM" src="https://user-images.githubusercontent.com/3672607/80529342-32bd2d80-894c-11ea-88f0-2c25403dc96e.png">

VS Code version: Code - OSS Dev 1.45.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.7.0

**Comment by sandy081** [comment]
Looks like the turning on state was not reset.

**Comment by sandy081** [comment]
To verify:

- Click on turn on sync action
- While the picker is open close the window or quit VS Code
- Open VS Code and make sure you can turn on sync
