### ISSUE TITLE
Why is there a quick pick with only a single option?

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#96472]
Testing https://github.com/microsoft/vscode/issues/96305

In the following quick pick there is only a single option. I first thought this is an input box where I can enter the name of the file.

![image](https://user-images.githubusercontent.com/172399/80523539-88b2c500-898e-11ea-9ee5-7b3fac15916d.png)

Suggest to integrate the message from this quick pick into the one that follows, where I enter how long to run the profile.

**Comment by connor4312** [comment]
Later we will add heap profiles as well, and perhaps tracing profiles for browsers: https://github.com/microsoft/vscode-js-debug/issues/435
