### ISSUE TITLE
keyboard binding addSelectionToNextFindMatch  aka  ctrl+d and cmd+d

### ISSUE THREAD

**Issue by codeangler** [microsoft/vscode#96477]
- VSCode Version: Version: 1.44.2

- OS Version:  macos 10.14.6 (18G103)

Steps to Reproduce:

1. highlight text in a file
1.  use `cmd+d`
1.  expect the next match to be selected
1. doesn't

It seems that the new VS version (march 2020) modified the behavior of `cmd+d` which now loads find (aka `cmd+f`) and therefore use the find options (e.g. Match Case, Match whole word, use regular expressions).

As a result, now selecting the end of a string e.g. `eks_cluster_cidr` and selecting `_cidr`  won't match other `_cidr` if a previous use of  "find" was using Match Whole Word.  

IMHO: the expected behavior is that

```

{ "key": "cmd+f",                 "command": "editor.action.extensioneditor.showfind",
                                     "when": "!editorFocus && activeEditor == 'workbench.editor.extension'" },
```

is independent of 

```

{ "key": "cmd+k cmd+d",           "command": "editor.action.moveSelectionToNextFindMatch",
                                     "when": "editorFocus" },
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@codeangler 

`cmd+d`/`ctrl+d` always respected the settings of the find widget. That is why those find settings (match word and whole words) appear in the top right corner when pressing `cmd+d`/`ctrl+d` even without a find widget visible:

![image](https://user-images.githubusercontent.com/5047891/80593031-bba59900-8a20-11ea-9158-fd19a73497e5.png)

When the find widget is visible and pressing `cmd+d`/`ctrl+d`, the find settings flash for a second to highlight the fact that they are used as input to the commands.

---

There is a small twist to the above. When having whole words off in the find widget and pressing `cmd+d`/`ctrl+d` without a selection, the selection expands to the word on which the cursor is sitting and subsequent `cmd+d`/`ctrl+d` use whole words even if the find widget whole words is off.

---

What has changed in 1.44 is that the definition for what constitutes a word when searching with `cmd+d`/`ctrl+d` is now read from the setting `"editor.wordSeparators"` and no longer decided by the language configuration. So, perhaps you are trying out in a programming language where the language configuration defined `_` as a word separator before, but it is not a word separator by default. If you want `_` to be a word separator, you can configure that via `"editor.wordSeparators"`.
