### ISSUE TITLE
Notebooks: Scroll notebook when navigating quick outline

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#96489]
Issue Type: <b>Bug</b>
Testing https://github.com/microsoft/vscode/issues/96279

1. Create GitHub issues notebook
2. Add a markdown cell with a header in it, then some other cells such that the first cell is out of the viewport, then another markdown cell with a header in it
3. Scroll to the top of the notebook
4. Open quick outline and navigate down through the entries

It would be cool if the notebook scrolled down to put the other header into view. I expected this behavior since it happens in normal editors

VS Code version: Code - Insiders 1.45.0-insider (abb4a35cfc26102f93fd00df7b59ce1a19c2017a, 2020-04-28T05:34:21.109Z)
OS version: Darwin x64 18.7.0

**Comment by rebornix** [comment]
Pushed a change which will reveal the cell into view when the selection in the quick pick changes. The missing part is we are lack of some sort of decoration to show in the notebook editor to indicate which cell is the one you select in the quick pick.

**Comment by jrieken** [comment]
> The missing part is we are lack of some sort of decoration to show in the notebook editor to indicate which cell is the one you select in the quick pick.

There is actually some kind of feedback here - it uses the focus indicator because the picker reveals and selects item. Not sure if that's enough?

![May-13-2020 11-47-56](https://user-images.githubusercontent.com/1794099/81797975-c0357b80-950f-11ea-82b2-339be7c359dc.gif)

**Comment by misolori** [comment]
Wouldn't we want to show the same selected color we use in the editor?

![image](https://user-images.githubusercontent.com/35271042/81852226-8a909280-950f-11ea-903d-970431ffdccf.png)

**Comment by jrieken** [comment]
I am not familiar enough with the notebooks internal so maybe @roblourens can help me here. I think what's needed is some sort of `setDecoration(cell, className): IDisposable`. That should allow to add and remove (via the returned disposable) styles to a notebook cell. Or we keep it specific and define something like `setHighlight(cell)` which is something volatile and entirely managed by the notebook

**Comment by jrieken** [comment]
The preview logic start here: https://github.com/microsoft/vscode/blob/ae6e90c44c943498a286189b52f9dc8b24e412be/src/vs/workbench/contrib/notebook/browser/contrib/toc/tocProvider.ts#L52

I have now also added restoring of the initial view state when nothing got picked

**Comment by roblourens** [comment]
I'll do this in debt week, need to pick a color, any idea @misolori?

**Comment by misolori** [comment]
Could we use the same color as `editor.rangeHighlightBackground` for the cell background color? 

![image](https://user-images.githubusercontent.com/35271042/86147231-fde56800-baad-11ea-84ca-6f5c06427261.png)

![image](https://user-images.githubusercontent.com/35271042/86147296-1190ce80-baae-11ea-99e3-979e902f9898.png)

**Comment by rebornix** [comment]
+1 for `setDecoration` API as we might later on use this API for other purposes like Problems (cell level error/warning), SCM, etc. I can take a look at this together with some refactoring with existing cell decorations storage.

**Comment by jrieken** [comment]
Seeing nice highlights, close as done. Thanks @rebornix
