### ISSUE TITLE
Do all methods need "customDocument" in the name?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#96486]
Testing #96315

Seems redundant to say `revertCustomDocument`, `saveCustomDocument`, and so on when the object only deals with CustomDocuments

**Comment by mjbvz** [comment]
The names are intentionally explicit to match what we do for our existing providers: https://github.com/microsoft/vscode/blob/47b1183dfda519c32d78b591cfa721d3b0b874ae/src/vs/vscode.d.ts#L2273
