### ISSUE TITLE
Show long file and folder names on hover in the file explorer

### ISSUE THREAD

**Issue by xt0rted** [Microsoft/vscode#9648]
- VSCode Version: 1.3.1
- OS Version: Win10 Build 14393

Steps to Reproduce:

1. Expand a couple folders deep (such as the contents of `bower_components`)
2. Watch your file and folder names get cut off
3. Profit

I'd like to see a tooltip or something that displays the full file or folder name on hover if it's cut off. This also makes multiple files that start with the same value impossible to tell which is which since they're clipped.

A horizontal scrollbar in the explorer might be nice as well, but the tooltip would be enough.

![capture](https://cloud.githubusercontent.com/assets/831974/17075573/98382314-5065-11e6-98bc-25bb605a9517.PNG)

**Comment by joaomoreno** [comment]
Can't reproduce both in Windows and macOS.

File labels do have tooltips, are you sure you are waiting enough time in order for them to appear?

**Comment by xt0rted** [comment]
@joaomoreno I get tool tips when the file is in the Open Editors section, but if I open a folder then none of that tree view, aside from the top level item, has tooltips. Once I open one of the files then I'll get a tooltip, but only in the Open Editors section, the entry in the folder tree view still lacks a tool tip.

**Comment by joaomoreno** [comment]
This is odd. Can you open the Developer Tools, and inspect the DOM nodes in there? I'm pretty sure they have a `title` attribute.

**Comment by xt0rted** [comment]
There's no title attribute on those elements.

I just installed the insider build and that has title attributes. It looks like this was fixed a few days ago in 8cf6ff05c266ab310e52878d040ba9d6e5490ad3 and just hasn't made it into a stable release yet.

**Comment by joaomoreno** [comment]
Oh wow! My bad, I just assumed this had always been there. Thanks for looking into it, great investigative skills. 👍
