### ISSUE TITLE
Terminal environment message font seems large

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#96498]
testing https://github.com/microsoft/vscode/issues/96300

I couldn't figure out how to check the font size using the dev tools, but if i zoom in and copy some of the text, it looks like the font is slightly larger than the rest of the tool.

This a zoom of the word "Extensions..." in the popup, and a file in the workspace named "LICENSE", so both have capital "E", which I'm trying to compare.

![image](https://user-images.githubusercontent.com/1487073/80548559-1206cf00-8970-11ea-88d4-53dead3d7d69.png)

**Comment by Tyriar** [comment]
I'm pretty sure it's the same size as the hover in the editor which it's copying:

![image](https://user-images.githubusercontent.com/2193314/80605926-85e4be00-89e8-11ea-9534-a681076efa68.png)
