### ISSUE TITLE
terminal info icon alignment

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#96495]
testing https://github.com/microsoft/vscode/issues/96300

the info icon is not aligned with any other markers in the terminal that i can see.

![image](https://user-images.githubusercontent.com/1487073/80547620-8ee47980-896d-11ea-9751-9fb3ce772a56.png)

**Comment by Tyriar** [comment]
It's actually pretty correct, your lines seem to be a little off:

![image](https://user-images.githubusercontent.com/2193314/80600029-ac9ef680-89e0-11ea-85c4-66b597a77788.png)

Going to leaving as is as I've already centered it around the x:

![image](https://user-images.githubusercontent.com/2193314/80600103-c3454d80-89e0-11ea-8e58-3b153d62ed17.png)
