### ISSUE TITLE
suggest unexpected completion items including special character.

### ISSUE THREAD

**Issue by kaakaa** [Microsoft/vscode#9649]
- Mac OSX
- VS Code 1.3.1
- vscode-go 0.6.39

With displaying completion widget, when inputting a character VSCode cannot 
correctly filter completion items including special characters (`$`, `_`, `/` and so on).

![vscode-js](https://cloud.githubusercontent.com/assets/1453749/17075967/5cacc914-50e0-11e6-835c-921e4780fd3b.png)

I think that special character is not equal to upper case for matching camel case.
In this case, VSCode should suggest `ArrayBufferConstructor` and `abc`.
(And I cannot understand why `a$b_c` isn't suggested.)

In golang this issue is particularly problematic, since most of package name is separated `/` (e.g. `io/ioutil`, `internal/golang.org/x/net/http2/hpack`).
[Search relevance in 'Add import' · Issue #390 · Microsoft/vscode-go](https://github.com/Microsoft/vscode-go/issues/390)

---

When filtering completion items, VSCode seems to consider the keyword including special characters camel case.
[vscode/filters.ts at 35e5c9af12045c89790be81d51a742dd7c2a30c4 · Microsoft/vscode](https://github.com/Microsoft/vscode/blob/35e5c9af12045c89790be81d51a742dd7c2a30c4/src/vs/base/common/filters.ts#L168)

Is this  bug?

**Comment by kieferrm** [comment]
The Go extension provides the completion proposals. Moved to the extensions issue tracker: https://github.com/Microsoft/vscode/issues/9649

**Comment by ramya-rao-a** [comment]
Reopening this issue as it has nothing to do with the Go extension
The given example is in a simple js file.

**Comment by jrieken** [comment]
This is the defined behaviour of JavaScript as that it always suggest all symbols from the current project

**Comment by mjbvz** [comment]
Yes, this is the expected behavior for JavaScript files. I believe `a$b_c` is excluded from the results only because of the `isCamelCaseWord` heuristic.

@jrieken Is it possible to tell the suggestion matcher what constitutes a word delimiter for camel casing? The `nextAnchor` function will currently always detect any letter after a `$` as a new word in camel casing.

**Comment by jrieken** [comment]
Not really - we could change the camel case matcher (cc @joaomoreno) tho

**Comment by joaomoreno** [comment]
The current camel case matcher has grown to be more than just that. It would also match `array_buffer_constructor`, which is a common naming scheme for C, for example.

I'd say the real bug here is that we don't show `a$b_c` in the results.

**Comment by jroesch** [comment]
We have been experimenting with `latex` style unicode input in our VSCode extension, and when no completions are shown for input like `->`, is it due to this behavior? if so it would great to allow non-alpha numeric input to trigger completions.

**Comment by mjbvz** [comment]
Here's what we show in 1.20 for this case:

![screen shot 2017-12-20 at 4 43 50 pm](https://user-images.githubusercontent.com/12821956/34235215-040116e8-e5a5-11e7-8a2b-48fcd2230a64.png)
