### ISSUE TITLE
GH authentication flow suggest to manually add the token if the redirec fails

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#96505]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode/issues/96313.

1) Create a new local folder with a couple of files
2) Open VS Code on this folder
3) Go to the SCM viewlet and choose `Publish to GitHub`
4) Sign-in
-> After I successfully signed in on the web page the web page tries to redirect to VS Code but also shows me the token (which is the whole URL and not the token) and suggest that I can add it manually when the redirect fails. I don't think we have the support to manually add the token anymore.

VS Code version: Code - Insiders 1.45.0-insider (abb4a35cfc26102f93fd00df7b59ce1a19c2017a, 2020-04-28T05:36:25.810Z)
OS version: Windows_NT x64 10.0.18363

**Comment by RMacfarlane** [comment]
I added support for manually adding the token anymore because that seemed easier than messing with the auth server - there should be a "Signing into github.com..." status bar item that appears only for the duration of sign in, clicking on it should show an input box you can paste the URL into
