### ISSUE TITLE
auto-save large json file gives useless popup suggestion

### ISSUE THREAD

**Issue by breathe** [microsoft/vscode#96509]
Issue Type: <b>Bug</b>

How do i get rid of this stupid popup?  Whenever I save a large json file I see this thing which means nothing to me ...  it's hard for me to know if the file save/format operation that I am after is taking forever because of this popup or some other reason ...

If I click the configure button I takes me to a search for settings related to `editor.codeActionsOnSave`
 

![image](https://user-images.githubusercontent.com/434034/80550642-f4d8fd00-897d-11ea-85ac-ad8cab106d1f.png)

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (4.13GB free)|
|Process Argv|../../itsacheckmate.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.12.0
vscode-erb-beautify|ali|0.2.0
vscode-apollo|apo|1.15.3
ohm|att|1.0.0
vscode-database|baj|2.2.0
markdown-mermaid|bie|1.5.0
mermaid-markdown-syntax-highlighting|bpr|1.0.2
better-toml|bun|0.3.2
solargraph|cas|0.21.1
bracket-pair-colorizer-2|Coe|0.0.29
erb|Cra|0.0.1
vscode-markdownlint|Dav|0.35.1
vscode-eslint|dba|2.1.5
make-hidden|dev|3.0.3
xml|Dot|2.5.0
vscode-pandoc|Dou|0.0.8
gitlens|eam|10.2.1
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.5.0
simple-new-file|fay|1.1.1
vscode-pull-request-github|Git|0.15.0
path-autocomplete|ion|1.13.6
search-node-modules|jas|1.3.0
vscode-rufo|jnb|0.0.1
restructuredtext|lex|126.0.0
fish-ide|lun|0.4.0
bash-ide-vscode|mad|1.9.1
python|ms-|2020.4.76186
cpptools|ms-|0.27.0
debugger-for-chrome|msj|4.12.6
vscode-activedocumentindicator|ojk|0.0.1
vscode-versionlens|pfl|0.25.0
gitlink|qez|0.5.1
ruby|reb|0.27.0
vscode-yaml|red|0.7.2
bash-debug|rog|0.3.7
bash-beautify|sha|0.1.1
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.3
fish-vscode|sky|0.2.1
vscode-hexdump|sle|1.7.2
cmake|twx|0.0.17
highlight-matching-tag|vin|0.9.9
simple-ruby-erb|vor|0.2.1
vscode-ansible|vsc|0.5.2
vscode-mermaid-preview|vst|1.5.2
quokka-vscode|Wal|1.0.289
wallaby-vscode|Wal|1.0.196
vscode-ruby|win|0.27.0
vscode-import-cost|wix|2.12.0

</details>

**Comment by jrieken** [comment]
> How do i get rid of this stupid popup?

By pressing "configure" inside that message

**Comment by breathe** [comment]
@jrieken Extremely false comment.

**Comment by breathe** [comment]
I get udUtter bullshit like this when I try to save ruby files.

![image](https://user-images.githubusercontent.com/434034/84353925-424fa900-ab7d-11ea-9666-53f058e42020.png)

Clicking 'configure' takes me to a complete meaningless and useless portion of the config.

Why the fuck is "Github Pull Requests and Issues" involved at all in saving a ruby file.

VSCode is getting horrible -- feels like every release is breaking basic functionality.
