### ISSUE TITLE
Terminal Environment change icon position

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#96504]
testing https://github.com/microsoft/vscode/issues/96300

The info/warning icon for the terminal environment change indicator feels like its just floating way over on the right (see the top picture below).

I wonder if we could put it near the `TERMINAL` tab, sort of like a badge, the bottom picture:

![image](https://user-images.githubusercontent.com/1487073/80549480-36fc4180-8972-11ea-8cf9-9db89fa29a7b.png)

**Comment by Tyriar** [comment]
The issue with this approach is that it's terminal specific, what do you do when there are split terminals? I was going to re-explore this when terminal tabs happen, in the meantime the info icon no longer shows by default.

/duplicate https://github.com/microsoft/vscode/issues/10546
