### ISSUE TITLE
Terminal environment change notification always exists?

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#96506]
testing: https://github.com/microsoft/vscode/issues/96300

It seems like I now **always** get a notification that the environment variables for my terminal sessions have been changed:

![image](https://user-images.githubusercontent.com/1487073/80549967-6b243200-8973-11ea-908d-f3d54f143e01.png)

- Start insiders
- open a folder
- open a terminal
 
result: the information icon is over on the right...

As a normal every day user user, this information doesn't help me. I can't change it, I don't know why its there, etc.  I found this because I was searching in the terminal extension sample to see where the "VSCODE_GIT_IPC..." etc variables were being set.

And, I also find that if I'm moving my mouse to (for example) get to the "x" to close the pane, I often hit this information icon and get the big popup.  

Suggest that by default we don't show the information icon unless a 3rd party extension actually asks to change the environment.

**Comment by Tyriar** [comment]
On master the default is to only show the warning because of this.
