### ISSUE TITLE
Seeing two GH auth flows when Publishing a repository to GH

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#96507]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode/issues/96313.

1) Create a new local folder with a couple of files
2) Open VS Code on this folder
3) Go to the SCM viewlet and choose `Publish to GitHub`
4) Sign-in in the browser and go through the two pop-up dialogs
5) Back in VS Code enter a repository name in the input box and press `ENTER`
-> I get a new pop-up asking me whether I allow the `git` extension to sign-in. I though I just had done this, but I actually gave the Pull Request extension the right to sign in although I initiated the action in the SCM viewlet. Technically I understand why that is happening but in this setup it feels like a broken flow.

VS Code version: Code - Insiders 1.45.0-insider (abb4a35cfc26102f93fd00df7b59ce1a19c2017a, 2020-04-28T05:36:25.810Z)
OS version: Windows_NT x64 10.0.18363

**Comment by RMacfarlane** [comment]
Since the `Publish to GitHub` action now comes from the built in "GitHub" extension, I believe only one dialog should be triggered now.
