### ISSUE TITLE
Open an Http Url from extension

### ISSUE THREAD

**Issue by XVincentX** [Microsoft/vscode#9651]
- VSCode Version: 1.3.1
- OS Version: Darwin Kernel Version 15.6.0

Hello folks,
I'm actually working on a VSCode extension which is linting a document and sometimes it might fail due to wrong settings (for example, I cannot provide symbols location if the user does not enable sourcemaps for the parser).

When this happens, I'm showing a `warning` message, which is totally ok. Obviously the space there is limited; therefore I wanted to provide a `More Info` button which, when clicked, it will open a webpage (potentially a Github wiki) with a more detailed explanation of the problem.

To do that, I'm using `sendNotification` from the server sending the interested URL but, unfortunately, I didn't find any way to open an `http` URI from the client application. It looks like `vscode.previewHtml` does not support `http/s` schemas.

What would be the best way to do that?

**Comment by jrieken** [comment]
Apart from node_modules that do this, you can use the `vscode.open` command which also support web links:

```js
        vscode.commands.executeCommand('vscode.open', vscode.Uri.parse('http://www.pinkbike.com/news/fail-of-the-month-june-2016.html'));

```

**Comment by XVincentX** [comment]
I didn't know `open` was able to do that, thanks!

**Comment by jrieken** [comment]
Yeah - I have pushed a tiny doc update
