### ISSUE TITLE
Better performance overall

### ISSUE THREAD

**Issue by Katolus** [microsoft/vscode#96513]
I would suggest taking VSCode and bringing back simplicity and performance that I started using it for. 

![flameshoot_2020-04-29-11-46-50](https://user-images.githubusercontent.com/20417569/80554010-28b03300-8a0f-11ea-83fa-cdc167f06287.png)

**Comment by alexr00** [comment]
If you're having a performance issue please check out the wiki page here and consider collecting some actionable information for us to investigate: https://github.com/microsoft/vscode/wiki/Performance-Issues
