### ISSUE TITLE
Cursor up/down doesn't work well in wrapped cells

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#96517]
- Focus a markdown cell with wrapped text
- Press down to get to the next wrapped line
- The next cell is focused instead

**Comment by roblourens** [comment]
@rebornix I can't figure out how to tell whether a line is wrapped, any idea?

**Comment by rebornix** [comment]
Good catch, didn't take wrapped line into account when dealing with cursor movement. We can't directly read wrap line information from `ICodeEditor` but we can use `getTopForPosition` to check if current cursor is at the last wrapped line.
