### ISSUE TITLE
Sometimes comments prompt replaces placeholder text

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#96516]
Found while testing https://github.com/microsoft/vscode/issues/96314

- VSCode Version: 1.45 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Use simple text in comment-sample
 ```
commentController.options = { placeHolder: 'place holder', prompt: 'prompt'}
```
2. Expand **prompt** and see 'place holder' text

![image](https://user-images.githubusercontent.com/12818376/80555107-2228a980-8984-11ea-97a9-bab5ef060978.png)

3. Now click Finish Draft
4. Reopen comment and expand **prompt** and you see 'prompt' text in the input box.

![image](https://user-images.githubusercontent.com/12818376/80555204-6ae06280-8984-11ea-9b6b-ec84cedc6459.png)

**Comment by gregvanl** [comment]
Repros with default text as well without commentController.options set.

**Comment by rebornix** [comment]
Good catch, thanks!

**Comment by gregvanl** [comment]
Still repros for case when not commentController.options set.

![image](https://user-images.githubusercontent.com/12818376/80730909-083fb180-8abf-11ea-957f-8feb88a7eb7e.png)

See comment in https://github.com/microsoft/vscode/commit/bcb50dda0eabf2e4fcd2aa76eead6d8b47b87e49 where "Reply..." is still hard-coded in case when placeholder option not set.

**Comment by rebornix** [comment]
@gregvanl that was expected and IIRC we want to show "Rely..." when there are already some comment in the comment thread. The new options will override this behavior.
