### ISSUE TITLE
Auto indent 2 tabs when I typing the '{}' in a label.

### ISSUE THREAD

**Issue by simon-woo** [microsoft/vscode#96523]
- VSCode Version:1.44.2
- OS Version:10.15.4 

Steps to Reproduce:

1.```      <span>{}</span>     ```

Does this issue occur when all extensions are disabled?: Yes

ps: reinstall vscode will repetition this bug.

**Comment by alexr00** [comment]
Can you provide a screen capture of the behavior you're seeing.
