### ISSUE TITLE
Cloning repo does not offer to sign in with GitHub

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#96524]
Testing #96280

![image](https://user-images.githubusercontent.com/35271042/80563114-ebac5800-899e-11ea-9b02-d618083d318e.png)

I have a fresh copy of Insiders w/ the nightly GH PR extension (not signed in) and I am also signed out of git globally. When I attempt to clone a private repo, I get hit with the error above. Based on the test plan item's description:

> At no point in time should you be asked for credentials within VS Code, but instead go through the auth flow similar to the GitHub Pull Requests extension

I assume that if it detects I am not signed in then it would prompt me to do so. This is not happening for me.

**Comment by misolori** [comment]
Sorry, didn't realize this didn't work via ssh. It works with http.

**Comment by joaomoreno** [comment]
Yeah nothing to be done with SSH.

**Comment by misolori** [comment]
Should we tell the user that this isn't supported via this command instead of showing this error? If I didn't know about the test plan item I would assume that this doesn't work.

Alternatively, when someone pastes in a ssh url, can we detect that and offer an https clone instead? That would be a smoother experience then dropping them off at a dead end.

![image](https://user-images.githubusercontent.com/35271042/80616023-453f7180-89f5-11ea-826c-525bf9864b2a.png)

**Comment by joaomoreno** [comment]
But it is, if you already have SSH configure, like I do. We're just doing the same we've always done.

I think we've fine since by default GitHub shows you the HTTPS clone link anyways, unless you actively choose SSH.
