### ISSUE TITLE
Focus lost when renaming file

### ISSUE THREAD

**Issue by silvanverschuur** [microsoft/vscode#96528]
When I rename a file focus is lost after some time (couple of seconds). It looks like there's some idle timeout. This is very annoying when you're not quick enough typing the new filename.
I haven't seen this behaviour before version 1.44.

- VSCode Version: 1.44
- OS Version: MacOS

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by silvanverschuur** [comment]
I tried Visual Studio Code Insiders and I cannot reproduce this issue. The strange thing is that I cannot reproduce it with the Visual Studio Code either. So I think I'll close this issue for now. Thanks for helping me.
