### ISSUE TITLE
Open remote files from terminal

### ISSUE THREAD

**Issue by pramitbhatia** [microsoft/vscode#96525]
Issue Type: <b>Feature Request</b>

I have a laptop running windows 10 enterprise and I use Remote Development extension pack to connect to my development VM at work. The VM is headless linux. Up until yesterday I was able to open files from the remote terminal using the command "code abc.py" and then "abc.py" would open in the same window in the editor. Today when I am doing the same thing, it says "code: command not found"

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.xxxxx
Remote OS version: Linux x64 x.x.x-xxx-generic

I have edited the OS version and Remote OS version to avoid possible company privacy policy breach

**Comment by Tyriar** [comment]
Definitely working for me in wsl.

**Comment by pramitbhatia** [comment]
The command works for me as well in WSL.
The problem is occurring on remote SSH connection to Linux machine

**Comment by pramitbhatia** [comment]
Found the fix after a bit of trial-and-error.
Just updated the PATH variable manually to include .vscode-server/bin/.....

Request: I wish the path was automatically added to bash upon installation.
Thanks :)
