### ISSUE TITLE
Global search by using regex did not work

### ISSUE THREAD

**Issue by KayIter** [microsoft/vscode#96521]
VSCode Version: 1.41.1
OS Version: Windows X
Steps to Reproduce:

Press Ctrl+Shift+F
Type in some text which you are sure exists in one of the unopened files.
VS Code 'Find in Files' feature will not locate the unopened file.
Does this issue occur when all extensions are disabled?: Yes
regex: `(?<!t\()'([^']*[^\x00-\xff]+[^']*)'`  
![image](https://user-images.githubusercontent.com/22729459/80559671-eee02c00-8a10-11ea-89f1-48f6e3af00c4.png)
only find the result in my opening file

**Comment by roblourens** [comment]
Can you share the text which is supposed to match that regex?

**Comment by KayIter** [comment]
<code><FormPanel.Item
            label={'来源'}
            segment={{
              options: Product.ChartFromOptions,
              value: chartFrom,
              onChange: value => actions.create.inputChartFrom(value)
            }}
          ></FormPanel.Item></code>
the word in label will be matched.
![image](https://user-images.githubusercontent.com/22729459/80633363-36a39980-8a8b-11ea-9ab8-88979895eb8f.png)
but when  i close the file, it will not be match at all.

**Comment by roblourens** [comment]
This appears to be an actual ripgrep bug which appears to be already fixed upstream so next week I will have to update ripgrep.

For my own future reference

- Have a file containing `xyz来源`
- Run `rg '(?<!a).*[^\x00-\xff]' --auto-hybrid-regex`
- Should be a result but in rg v11 there were no results found

**Comment by roblourens** [comment]
Verification steps

- Open a workspace with a file containing `xyz来源`, the file should not be open
- Search for the regex `(?<!a).*[^\x00-\xff]`
- There should be a result
