### ISSUE TITLE
Locking a cell removes squiggles

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96529]
* have cell with errors
* lock/unlock it
* :bug: squiggle hides/shows

![Apr-29-2020 08-54-19](https://user-images.githubusercontent.com/1794099/80568283-0ad6d400-89f7-11ea-86e3-b0485cd7278f.gif)

**Comment by connor4312** [comment]
I see squiggles in this cell:

![](https://memes.peet.io/img/20-04-fe038be5-e5b0-43cd-9100-c1c78a41c0d5.png)

```
Version: 1.45.0-insider (user setup)
Commit: a0fe37870c42e0704a492cdc6b8550b4cf23f63c
Date: 2020-04-30T05:39:08.281Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by jrieken** [comment]
> I see squiggles in this cell:

That's a good thing ;-)

**Comment by connor4312** [comment]
Oh, I misread the issue. Sounds like this is working as intended.
