### ISSUE TITLE
onDidChangeTextDocument return wrong rangeOffset

### ISSUE THREAD

**Issue by susiwen8** [microsoft/vscode#96526]
- VSCode Version: 1.44.2
- OS Version: Darwin x64 17.7.0

`More detail`
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.7.0

Steps to Reproduce:

1. Open a ts file, content as follow
```typescript
    import echarts from 'echarts';

    const option: echarts.EChartOption = {
        title: {
        backgroundColor: 123,
        borderColor: false,
        textAlign: 'left',
        a: '',
        bottom: 1,
        subtext: '',
        text: 1234,

        hasdhakdha: '',
        target: '12sds34',
        textStyle: {
            color: '#',
            fontFamily: '',
            fontWeight: 'bold',

            rich: {
                a: {
                    fontFamily: 1,
                    align: '',

                    
                    textShadowColor: 2,
                    borderRadius: 0,
                    align: 'left',
                    backgroundColor: 123,
                    textBorderWidth: 1,
                    adaa: 2
                }
            },
            lineHeight: 2,
            textBorderColor: 1,
            textShadowOffsetX: 12,
            fontSize: 1,
        },
        color() {
            return '';
        },
        subtextStyle: {
            verticalAlign: 1,
        },
    },
    geo: {
        aspectScale:  1,
        roam: true,
        regions: [],
        emphasis: {
            itemStyle: {
                borderColor: "#000",
            },
        },
    },
    series: [
        {
            barMaxWidth: 5,
            type: 'bar',
            barCategoryGap: '',
            barWidth: 5,

            barGap: '',
            barMinHeight: 2,
            jhass: 1,
            data: [],
            label: {
                rich: {
                    a: {
                        fontFamily: '',
                        fontSize: 12,
                        fontWeight: 12,
                        textBorderWidth: 12,
                        textBorderColor: '',
                        textShadowBlur: 1,
                        textShadowOffsetX: 1,
                        borderWidth: 1,
                    }
                }
            },
            barMinWidth: 1,
        },
        {
            type: 'line',
            xAxisIndex: 1,

            hoverAnimation: true,
            symbolKeepAspect: true,
            yAxisIndex: 1,
            sss: 2,
            label: {
                show: true
            },
        },
        {
            type: 'line3D',
            grid3DIndex: 1,
        }
    ]

};
```
2. press enter at somewhere, right bottom will show the rangeOffset, then go somewhere else press enter, you can see rangeOffset is wrong, the press enter again, rangeOffset is correct

Gif shows the process

Does this issue occur when all extensions are disabled?: Yes
![test-1588138215409](https://user-images.githubusercontent.com/20318608/80563582-01ad2d80-8a1e-11ea-9fd7-6c4b99b926b8.gif)

**Comment by alexr00** [comment]
Does this still occur if you disable all installed extensions?

**Comment by susiwen8** [comment]
@alexr00 Hi. Yes, I was developing my own extension, so I set `"--disable-extensions"` in lauch.json, so the only extension wasn't disable was my extension, but this problem so far only happened in  TS file, JS file was fine.

**Comment by susiwen8** [comment]
@alexr00 @alexdima 
![Screen Shot 2020-04-29 at 17 33 21](https://user-images.githubusercontent.com/20318608/80581357-9e33f780-8a3f-11ea-9782-e4eb327a0b5c.png)
Here is the code I use.

**Comment by susiwen8** [comment]
Update: It's not bug, `contentChanges` is an array, but I cannot find enough infos about `TextDocumentContentChangeEvent` 
https://code.visualstudio.com/api/references/vscode-api#TextDocumentContentChangeEvent
@alexdima Could you enlighten the meaning of each item in  `contentChanges`

**Comment by alexdima** [comment]
Each change in `contentChanges` represents a single change. For example, when doing a replace all in a file with 3 matches, there will be 3 elements in `contentChanges`, each one describing the change that occurred around each match. The changes are sorted and make sense only read from 0 to `contentChanges.length`.

**Comment by susiwen8** [comment]
@alexdima Thanks

**Comment by susiwen8** [comment]
@alexdima But hit `enter` return two `contentChange`, one of them, `text` was `""`, other one was `\n`. I thought it should have only one `contentChange`.

**Comment by alexdima** [comment]
@susiwen8 The editor has very many features and it would take me a long time to explain everything one by one. Please trust that those are correct since hundreds of extensions depend on those being correct and everything would fall apart if those had any kind of glitch.

In this case, you might be running into something that is controlled by the option `"editor.trimAutoWhitespace": true`. When you first press Enter, you will notice that the editor inserts `\n` followed by many tabs or many spaces to match your indentation. Then, when you move onto a different line and press Enter, the automatic inserted indentation is removed, so that is the second change. This would become more obvious if rendering whitespace would be enabled. Also please note that looking only at the `text` of a change does not make sense, a change is made up out of a `range` and a `text` and seeing an empty `text` most likely indicates that there was a deletion of sorts.
