### ISSUE TITLE
open vscode in WSL, and windows10 crash after building haskell app several times

### ISSUE THREAD

**Issue by tfangz888** [microsoft/vscode#96538]
- VSCode Version: 1.44.2
- OS Version: windows10

Steps to Reproduce:

1. installed vscode
2. installed WSL
3. installed haskell stack in WSL
4. installed haskell platform in WSL
5. configure vscode to support remote edit from WSL as user mannual from Microsoft.
6. create a haskell app by "stack new project1" in WSL
7. input "code . " in WSL.
8. edit source code, and build haskell app by "stack build" -> "stack exec project1-exe"
9. for one hour or so, sudenly windows 10 crashed in blue screen.
10.
11. repeate step 6-7.
12. just edit source in vscode. do not "stack build" in WSL windows
13. open another WSL windows, switched to the haskell project.
14. input "stack build"
15. there is not crach problem any more.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment]
Can you file this against https://github.com/Microsoft/wsl/issues ? They need to investigate why there's a blue screen.
