### ISSUE TITLE
VSCode‘s tasks.json will not be updated in WSL2 unless restart VSCode

### ISSUE THREAD

**Issue by YbJerry** [microsoft/vscode#96537]
Issue Type: <b>Bug</b>

When I use WSL2, I don't know why tasks.json will not be updated such as I add a new line in the "args" option. The same question will occure when I add a new code-snippet file. By the way, I open the "autosave".

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (9.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|12.43GB (11.87GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.44.2
cpptools|ms-|0.27.1
vscodeintellicode|Vis|1.2.6
language-x86-64-assembly|13x|2.3.0
html-snippets|abu|0.2.1
lex-flex-yacc-bison|fau|0.0.3
vscode-language-pack-zh-hans|MS-|1.44.2
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0

</details>

**Comment by alexr00** [comment]
This happens for both tasks, snippets, and launch. @aeschli, I think there might be some problem with file watching in WSL2.

**Comment by aeschli** [comment]
To debug the file watcher, run `Set Log Level...`, `Trace`, reopen the remote window and observe the `Output`, `Log (Remote Server)` log. Look for `[File Watcher]` messages.
Check that there are no error messages and that the exclusion patterns look right.

**Comment by alexr00** [comment]
I just tested and confirmed that it repros an hour ago. Now, I don't see the issue happening. @YbJerry is this problem consistent?

**Comment by YbJerry** [comment]
Yes, it is consistent and I find a funny thing. I deleted my "tasks.json" file. But when I pressed Ctrl+Shift+B, VSCode will still run build tasks unless I restart VSCode. So I guess VSCode will save a copy of the files in the folder of ".vscode"?

**Comment by alexr00** [comment]
@YbJerry can you try using the latest version of VS Code (1.45.1)?

**Comment by YbJerry** [comment]
@alexr00 I'm using the latest version of VS Code. The issue still exists.
![图片](https://user-images.githubusercontent.com/34412324/82894179-c05c5f00-9f84-11ea-936d-7f4804f4ba6e.png)
Translation:
版本 —— Version
提交 —— Commit
日期 —— Date
1周前 —— A week ago

**Comment by YbJerry** [comment]
@alexr00 @aeschli  I discovered something new. If a folder in Windows is mounted on WSL2 like "mnt/d/", the issue will occur. If a folder is originally in WSL2 like "/home/ybjerry/", everything is OK.
