### ISSUE TITLE
希望能在终端上 双击可以放大 整个终端

### ISSUE THREAD

**Issue by lifetin** [microsoft/vscode#96539]
Issue Type: <b>Feature Request</b>

希望能在终端上 双击可以放大 整个终端,或是快放大与缩小.现在必须手动拉动终端才能扩大,恢复时也要拉动才能缩小.  很小的功能,但是很实用.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.17134

**Comment by lifetin** [comment]
![44](https://user-images.githubusercontent.com/10474968/80574490-83a85100-8a34-11ea-8d1b-fb4ad4e339f0.png)

**It is hoped that double clicking on the terminal can enlarge the whole terminal, or quickly enlarge and shrink it**

**Comment by Tyriar** [comment]
![recording](https://user-images.githubusercontent.com/2193314/80614753-afefad80-89f3-11ea-99e4-25bcca7d15b4.gif)
