### ISSUE TITLE
Clean up Terminal UI and Output for Code

### ISSUE THREAD

**Issue by ishaansathaye** [microsoft/vscode#96533]
Since there is no separate window to show the output like in Pycharm, this means we have to search for the output in Terminal. Need a theme or settings for terminal to make certain things different color (eg. errors in red). Another thing is that it should be possible to not just run the code in integrated terminal but in a separate window designated for just the output of code (not the lof files tab).

**Comment by alexr00** [comment]
The terminal colors already exist. You can change them or install a theme that sets them https://code.visualstudio.com/api/references/theme-color#integrated-terminal-colors.

For running the code and having it output somewhere else, you should post an issue in the repo of whatever python extension you're using to run code.
