### ISSUE TITLE
The TypeScript language service died 5 times right after it got started. The service will not be restarted.

### ISSUE THREAD

**Issue by mucic** [microsoft/vscode#96534]
Issue Type: <b>Bug</b>

The TypeScript language service died 5 times right after it got started. The service will not be restarted.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 8, 6|
|Memory (System)|8.00GB (0.20GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
react-hooks-snippets|AlD|1.1.6
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.1.5
prettier-vscode|esb|4.5.0
vscode-styled-components|jpo|0.0.29
react-snippets|run|0.1.2
mdx|sil|0.1.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mucic** [comment]
After fresh install and all extensions removed **problem is solved**. 
This looks like it might be related to some of this extensions:


Extension | Author (truncated) | Version
-- | -- | --
react-hooks-snippets | AlD | 1.1.6
bracket-pair-colorizer-2 | Coe | 0.0.29
vscode-eslint | dba | 2.1.5
prettier-vscode | esb | 4.5.0
vscode-styled-components | jpo | 0.0.29
react-snippets | run | 0.1.2
mdx | sil | 0.1.0
