### ISSUE TITLE
Wrong order of preview scripts

### ISSUE THREAD

**Issue by goessner** [microsoft/vscode#96530]
Version: 1.44.2 (system setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Add `markdown.previewScripts` to `package.json` of a (markdown) extension.
2. Inject a local  `<script>` element into a markdown document.
3. Expect the local script being able to access content of the extension-specific script.

Does this issue occur when all extensions are disabled?: Yes

---
There  are two different kinds of preview scripts possible. An extension related preview script is defined in `package.json`.

```json
  "contributes": {
		"markdown.markdownItPlugins": true,
		"markdown.previewScripts": [
			"./regional.js"
		]
  }
```
The content of `regional.js` is
```js
document.body.innerHTML += 'regional';
```

Inside of a markdown document `test.md` a local script `local.js` is injected.
```md
# Preview Script Test

<script src="local.js"></script>
```
`local.js` looks like ...
```js
document.addEventListener("DOMContentLoaded", () => {
        document.body.innerHTML +=  'local<br>';
});
``` 
Now previewing `test.md` gives
![grafik](https://user-images.githubusercontent.com/4902746/80567804-25f51400-89f6-11ea-9d6d-fb133b885c13.png)

which demonstrates an unintuitive order of script invocation.

It is expected, that script `local.js` is able to access objects and functions from previously loaded extension-specific script `regional.js`. This is not the case.

A workaround is possible, but also unintuitive. Extension-specific preview scripts should always be loaded before local scripts injected to markdown documents.

**Comment by mjbvz** [comment]
We intentionally load extension contributed scripts asynchronously and after the rest of the document: https://github.com/microsoft/vscode/blob/c5dc9d16be5cbd18b4a1bc44941ef8a1b16cf983/extensions/markdown-language-features/src/features/previewContentProvider.ts#L190

This is done for better performance and user experience
