### ISSUE TITLE
JavaScript IntelliSense not working correctly

### ISSUE THREAD

**Issue by ameyer117** [Microsoft/vscode#9654]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:31:10.994Z)
- OS Version: Darwin x64 15.6.0

Issue: JavaScript IntelliSense does not activate until the file has been saved, closed and re-opened.

Steps to Reproduce:
1. Create HTML file
2. Create Javascript file
3. Type "do" and all that will show is a dowhile suggestion.
4. Save Javascript file
5. Close Javascript file
6. Re-open Javascript file and IntelliSene all of a sudden starts working on that file.

![errorpic](https://cloud.githubusercontent.com/assets/15789820/17080186/83731458-50eb-11e6-9109-d7675168eb2c.png)

![workingafterreopen](https://cloud.githubusercontent.com/assets/15789820/17080195/c0b3b1ce-50eb-11e6-842f-03afc7358853.png)

**Comment by dbaeumer** [comment]
I can't reproduce this using the upcoming 1.4 build. Please ping if you still see this with the next build.

![capture](https://cloud.githubusercontent.com/assets/1931590/17398778/d04bb648-5a3e-11e6-8494-3a1600fe39f8.png)
