### ISSUE TITLE
Snippet tab stop selection issue

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [microsoft/vscode#96545]
- VSCode Version:
Version: 1.45.0-insider
Commit: 4bd206856db30c27d38aa0f1fbe74bac6156edc7
Date: 2020-04-29T05:33:59.143Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0

- OS Version:
OS: Windows_NT x64 10.0.19035

Steps to Reproduce:

1. Create a snippet with the following code.
```
{
    "my test 1": {
        "scope": "",
        "prefix": [
            "test1"
        ],
        "body": [
            "${1:{}${2:fff}${1/[\\{]/}/}"
        ],
        "description": "my test 1"
    }
}
```

2. Invoke the snippet and this is what happened.

<img src="https://i.imgur.com/XVdKNiV.gif" />

Expected behavior:
- Invoke the snippet, tab stop 1 (both `{`) is selected
- Press tab, last `{` changed to `}` and selection moved to `fff`

Actual behavior:
- Invoke the snippet, tab stop 1 (both `{`) is selected
- Press tab, last `{` changed to `}` and selection moved to `fff}`

Does this issue occur when all extensions are disabled?: Yes

**Comment by jeanp413** [comment]
Took a look at this but don't know how to fix it.
I think the error is in the decoration range calculation inside intervalTree.
This line :arrow_down: is being executed with `insertingCnt` being the length of the transformed text (`}`)
changing the decorarion range from `fff` to `fff}`
https://github.com/microsoft/vscode/blob/b3882f0dfe480de31bebbfc85771184850698f38/src/vs/editor/common/model/intervalTree.ts#L459

Later the decoration range is used to create the selection [here](https://github.com/microsoft/vscode/blob/b3882f0dfe480de31bebbfc85771184850698f38/src/vs/editor/contrib/snippet/snippetSession.ts#L152-L154)

```
nodeAcceptEdit (intervalTree.ts:459)
acceptReplace (intervalTree.ts:314)
acceptReplace (textModel.ts:3034)
_doApplyEdits (textModel.ts:1381)
applyEdits (textModel.ts:1355)
pushEditOperation (editStack.ts:359)
_pushEditOperations (textModel.ts:1303)
pushEditOperations (textModel.ts:1212)
executeEdits (cursor.ts:665)
executeEdits (codeEditorWidget.ts:1092)
move (snippetSession.ts:123)
_move (snippetSession.ts:561)
next (snippetSession.ts:547)
next (snippetController2.ts:232)
handler (snippetController2.ts:257)
runEditorCommand (editorExtensions.ts:159)
(anonymous) (editorExtensions.ts:182)
invokeFunction (instantiationService.ts:61)
invokeWithinContext (codeEditorWidget.ts:361)
runCommand (editorExtensions.ts:175)
handler (editorExtensions.ts:94)
invokeFunction (instantiationService.ts:61)
_tryExecuteCommand (commandService.ts:84)
(anonymous) (commandService.ts:73)
Promise.then (async)
executeCommand (commandService.ts:73)
_doDispatch (abstractKeybindingService.ts:200)
_dispatch (abstractKeybindingService.ts:159)
(anonymous) (keybindingService.ts:248)
```
