### ISSUE TITLE
Timeline bug display when unfold the view

### ISSUE THREAD

**Issue by jeffreyyjp** [microsoft/vscode#96548]
- VSCode Version:1.44.2
- OS Version:macOS 10.15.4

Steps to Reproduce:

1. switch to different files in the editor
2. see the unfolding view of timeline

![image](https://user-images.githubusercontent.com/17985592/80583664-1819b000-8a43-11ea-927c-027ecf81c1bf.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible in VS Code insiders? Looks like line wrapping of filename was replaced with `...` if it overflows.
![image](https://user-images.githubusercontent.com/1312662/80593221-789bf380-8a29-11ea-913a-b8cf3ad2b3c8.png)
