### ISSUE TITLE
Notebook: quick outline should highlight cell on navigation in quick pick

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96543]
Refs: https://github.com/microsoft/vscode/issues/96279

Similar to editor quick outline where we reveal and highlight a symbol before picking it.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Afeature-request+label%3Anotebook+label%3Aoutline
