### ISSUE TITLE
VSCode’s Code Helper Renderer process using 100% of CPU  and process using more than 3GB memory - slows down the whole system in my MacBook Pro.

### ISSUE THREAD

**Issue by marypieroszkiewicz** [microsoft/vscode#96541]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. VS Code Version: 1.44.2
2. MacOS Catalina Version: 10.15.4

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment]
Please collect a performance trace as shown here: https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu
