### ISSUE TITLE
Handle invalid token type/modifier indexes

### ISSUE THREAD

**Issue by prostakm** [microsoft/vscode#96540]
- VSCode Version:   1.45.0-insider Commit: abb4a35cfc26102f93fd00df7b59ce1a19c2017a
- OS Version: Darwin x64 19.4.0

I'm experimenting with semantic tokens response implementation as part of Swift LSP server (sourcekit-lsp). Everything seems to be working fine with proposed API, but in the end recognized tokens are not colored like it's determined: 

![image](https://user-images.githubusercontent.com/6282784/80574364-f946f980-8a01-11ea-98a5-3253fd0e80b3.png)

So, as you can see on attached screenshot, "previews" token color (foreground) seems to be taken from semantic token foreground (#569CD6) and should be displayed with this color, but in fact in editor it's displayed with #D4D4D4 (which is a color determined by textmate coloring) 

It looks like a bug to me, but maybe I'm missing something?

**Comment by aeschli** [comment]
Can you enable `Set Log Level...` `Trace`, reload the editor and check the log for messages containing `tokenStyleMetadata`?

**Comment by aeschli** [comment]
@alexdima Could be a token merging issue given that the TextMate token starts with the whitespace and has the background color

**Comment by alexdima** [comment]
From the looks of it, there is definitely a bug somewhere. @prostakm Is there a way for us to try to reproduce?

**Comment by prostakm** [comment]
@aeschli @alexdima Thanks for help. I've looked into trace logs as Martin suggested, and I've found out a root cause for this behavior: 

trace log :
`
[2020-04-29 16:40:29.028] [renderer1] [trace] telemetry/UnhandledError {"msg":"Cannot read property 'length' of undefined","callstack":"TypeError: Cannot read property 'length' of undefined\n    at Object.u [as parseClassifierString] (out/vs/workbench/workbench.desktop.main.js:2615:207)\n    at E.getTokenStyleMetadata (out/vs/workbench/workbench.desktop.main.js:5394:28)\n    at t.SemanticTokensProviderStyling.getMetadata (out/vs/workbench/workbench.desktop.main.js:1654:382)\n    at Object.t.toMultilineTokens2 (out/vs/workbench/workbench.desktop.main.js:1655:537)\n    at F._setDocumentSemanticTokens (out/vs/workbench/workbench.desktop.main.js:2634:358)\n    at out/vs/workbench/workbench.desktop.main.js:2632:906\n    at processTicksAndRejections (internal/process/task_queues.js:85:5)","count":1}
`

It turned out a bug in my code, when I supplied semantic token index higher then legend tokens count. In process in `SemanticTokensProviderStyling.getMetadata(...)` tokenType is resolved to undefined : 

![image](https://user-images.githubusercontent.com/6282784/80612486-519aed00-8a3c-11ea-9251-2c134a9cfcca.png)

`ColorThemeDatagetTokenStyleMetadata()` calls `ColorThemeData.parseClassifierString()` which expects value as it's first argument, and it crashes since it's undefined

![image](https://user-images.githubusercontent.com/6282784/80613100-1e0c9280-8a3d-11ea-9124-7a85b6a6b6dc.png)

I think it would be worth to test somewhere against token index being out of bounds. 

After fixing my code to pass proper token identifiers, in range of legend tokens, everything works fine.

**Comment by aeschli** [comment]
To verify:
- open https://github.com/microsoft/vscode-extension-samples/tree/master/semantic-tokens-sample in Extension Development Host]
- In the Extension Development Host
  -  open `sample.semanticLanguage`
  - Use the scope inspector (`Developer: Inspect Editor Tokens and Scopes`) on the `notInLegend` token. You should not see any semantic token related errors in the dev tool console or Output (Window) log
