### ISSUE TITLE
Use paths of compilerOptions instead of relative path when auto import

### ISSUE THREAD

**Issue by AdonLee** [microsoft/vscode#96547]
when you type something, vscode always show some suggestions. some of them need to be import from other place. if you select the suggestion then vscode will auto import the selected item.
as you see below, "./src/libs/services/*" is aliased to be  "@shopping/services/*" for sake of readability, i hope vscode use "@shopping/services" instead of  "./src/libs/services/*"  in the path of  the importing file

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es2017",
    "paths": {
      "@shopping/services/*": ["./src/libs/services/*"]
    },
    "baseUrl": ".",
    "rootDir": ".",
    "module": "commonjs",
    "outDir": "../../dist/out-tsc",
    "sourceMap": true,
    "jsx": "preserve",
    "resolveJsonModule": true,
  }
}

```

expect
```typescript
import { IUserCurrencyInfoModel } from './src/libs/services/membership';
```
to be
```typescript
import { IUserCurrencyInfoModel } from '@shopping/services/membership';
```

thanks for watching!!

**Comment by mjbvz** [comment]
Please fill out the issue template.

Also describe your general project structure including where tsconfig and ts files are located 

/needsMoreInfo
