### ISSUE TITLE
code-insiders.sh prompts me for WSL although I do want to start the Linux version

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#96555]
###Setup

- WSL 2
- add support to run graphical apps in WSL2 (xlibs, ...)
- install an xserver on Windows side
- install code insiders in Linux
- try to run code insiders
- you get
```
To use VS Code with the Windows Subsystem for Linux, please install VS Code in Windows and uninstall the Linux version in WSL. You can then use the 'Visual Studio Code - Insiders' command in a WSL terminal just as you would in a normal command prompt.
Do you want to continue anyways ? [y/N] y
```

I would like to have the ability to start the Linux version as well. Couple of ideas to achieve that:

- check the origin of code-insider.sh. If on a Windows drive the start the WSL version. If on a Linux share then start the Linux version
- check if the environment has a `DISPLAY` variable set and if so start the Linux version directly.

**Comment by dbaeumer** [comment]
@joaomoreno FYI.

**Comment by aeschli** [comment]
> I would like to have the ability to start the Linux version as well. 

That we already have, you just have to press `y` every time.

The question is, how often do you run on the WSL side. Is it just for testing?
I would think running on the Windows side still has more advantages and we want to promote that, no?

**Comment by dbaeumer** [comment]
Agree, but IMO we can detect what to do. If the `code.sh` comes from a windows drive (e.g. `/mnt/c/Users/xxxx/AppData/Local/Programs/Microsoft VS Code Insiders/bin/code-insiders`) then it is clear to start the Windows application. If `code.sh` comes from the Linux part and a `DISPLAY` variable is set then I think you want to start the Linux version.

**Comment by aeschli** [comment]
When you see the error message, it's already clear that you called `code.sh` from a VSCode linux install (only that code.sh has the WSL check with the error message).

And even when we see the DISPLAY variable, we still want to inform the user that installing VSCode in WSL is not the best choice. IMO we should show the message at least once. 

Did I miss a good use case why someone would install a Linux VSCode in WSL? If it is a problem with running integration tests, we could also add an additional command line parameter, or a env variable that we test for.

**Comment by dbaeumer** [comment]
It is not about running tests. That I have under control now :-). It is to verify things under Linux. You remember the extension I gave you for testing. To make sure it is working in pure Linux I install Linux into WSL as well.

**Comment by dbaeumer** [comment]
I would be happy to have a switch `--forcePlatfrom` or something. The I would add a alias to my bashrc.

**Comment by aeschli** [comment]
There's already an env variable that you can set to avoid the warning:
`DONT_PROMPT_WSL_INSTALL=1 code-insiders` should do the trick.

I'll add a message to the script to tell you that.
