### ISSUE TITLE
Add some right padding to the folding icon 

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#96556]
#96279

<img width="273" alt="image" src="https://user-images.githubusercontent.com/10746682/80588618-f4da0b00-8a18-11ea-8d36-a5d468ef0d47.png">

**Comment by rebornix** [comment]
This is what Monaco Editor looks like when the line numbers and gutter areas are hidden. We may want to tweak the CSS for this case cc @misolori

**Comment by misolori** [comment]
@sandy081 how do you get to this state? I haven't been able to repro:

![image](https://user-images.githubusercontent.com/35271042/80650739-66ba5080-8a29-11ea-9561-67c08ceb5b4f.png)
