### ISSUE TITLE
Cannot navigate problems across cells

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#96551]
Testing  #96279

- Have two GitHub issues cells that has problems
- Open marker peek in one of the cells
- Use navigation (up and down) arrows in the peek
🐛 This navigates only in the cell

**Comment by jrieken** [comment]
This is now working @sandy081 I also pushed https://github.com/microsoft/vscode/commit/ce486da91f24410e39ae33ac823890442b031033 which relaxed the "go to error" commands to also work on readonly editors. Since a while we allow squiggles in readonly errors and removing the precondition seemed like the best to do

**Comment by sandy081** [comment]
![Kapture 2020-04-30 at 16 31 55](https://user-images.githubusercontent.com/10746682/80722900-30033980-8b00-11ea-814b-dcad1fded93d.gif)

Not working yet

```
Version: 1.45.0-insider
Commit: a0fe37870c42e0704a492cdc6b8550b4cf23f63c
Date: 2020-04-30T05:36:26.465Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

**Comment by jrieken** [comment]
Please file a separate issue for that - those action always and only navigate within an editor, never across many editors. What should work is F8 which does this correctly

**Comment by jrieken** [comment]
and sorry, only know I have read the issue properly. ⌨️ person...

**Comment by sandy081** [comment]
Done - https://github.com/microsoft/vscode/issues/96708

**Comment by jrieken** [comment]
did event know that we have those buttons

**Comment by sandy081** [comment]
These were introduced for using mouse navigation.

**Comment by jrieken** [comment]
to verify: 

* have errors across cells
* keep pressing F8 and make sure they you reach them all
