### ISSUE TITLE
New markdown or code cell shall be created at the end of the folded cell

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#96558]
#96279

- Have a markdown cell followed by code cell
- Fold markdown cell
- Create a markdown cell
🐛 Expected to create at the end and without expanding the first markdown cell

**Comment by sandy081** [comment]
Newly created markdown cell is still getting created in between existing markdown and code cells. It is expected to create at the end (after code cell). 

Let me know if it is clear?

**Comment by rebornix** [comment]
Previous fix only fixes code cell but not markdown cell.
