### ISSUE TITLE
Notebook: renaming an opened notebook closes it

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96564]
Steps:
* open a notebook (I used GH search)
* run a query
* save it
* rename from explorer

=> 🐛 the notebook closes

I would expect the notebook to reopen with the new name.

**Comment by bpasero** [comment]
Looks like `notebookEditorInput` is missing to implement the `move` method. Inspiration:

https://github.com/microsoft/vscode/blob/f00d8903af842c19b09f88db05e76c2ac424078b/src/vs/workbench/contrib/searchEditor/browser/searchEditorInput.ts#L219-L227

**Comment by rebornix** [comment]
Fixed in master now.
