### ISSUE TITLE
New folder followed by new file breaks the Explorer and needs a reload

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#96566]
* Right click in the explorer and create a new folder, e.g. `test`
* Immediately right click on the new folder and create a new file
* Observe that the explorer is broken

![Kapture 2020-04-29 at 13 45 47](https://user-images.githubusercontent.com/5047891/80592449-c3b10900-8a1f-11ea-8909-40c26ca21901.gif)

**Comment by isidorn** [comment]
Thanks for catching and filling this.
Had to push an ugly timeout because the tree refresh can cause a blur event thus leading to the input box getting disposed. Now I ignore blur events for 100ms.
