### ISSUE TITLE
Off to create launch configuration in workspace file

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#96567]
Verifying https://github.com/microsoft/vscode/issues/95482

- create a new workspace with some new empty folders
- save the workspace file
- open the debug viewlet and click on the `create a launch.json file`
- I can choose in which folder to create
- I actually want to store it in the workspace file. Would be cool if that's an option too.

**Comment by isidorn** [comment]
@aeschli I think this makes sense. And there was a similar PR from a community member to tackle something related.
Thus opening this up for PRs.
Code pointer 
https://github.com/microsoft/vscode/blob/8091d54386e3f95fb4ea6b718581ed9fcc3cadad/src/vs/workbench/contrib/debug/browser/debugActions.ts#L95
