### ISSUE TITLE
Notebooks: Cannot "Save As..." notebook

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96565]
Steps:
* open a notebook
* select File > Save As...

=> 🐛 nothing happens, I am not being asked for a path.

**Comment by bpasero** [comment]
Looks like `notebookEditorInput` is missing to implement the `saveAs` method.

**Comment by rebornix** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/96482 . Thanks for reporting, it might require some API change, we will look into this in next Iteration.
