### ISSUE TITLE
No commands to fold/unfold markdown content

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#96561]
#96279

No commands to fold/unfold markdown content

**Comment by rebornix** [comment]
Can you elaborate a bit more on this? The regular Fold/Unfold commands are still available in the Monaco Editor.

**Comment by sandy081** [comment]
I do not see editor folding commands when I am in markdown cell. I see them when I am in markdown editor. See the video

![Kapture 2020-04-29 at 22 02 45](https://user-images.githubusercontent.com/10746682/80641496-3db7b100-8a65-11ea-9e41-2b0400953072.gif)

**Comment by tanhakabir** [comment]
I see `Notebook: Fold Cell` and `Notebook: Unfold Cell` in stable today
