### ISSUE TITLE
Cannot edit at the end when content in the markdown cell are folded

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#96562]
#96279

Have following markdown cell

<img width="833" alt="image" src="https://user-images.githubusercontent.com/10746682/80590312-fc4ee380-8a1b-11ea-8a60-06b5a156dc26.png">

Cannot use only keyboard to add content at the end of the cell

**Comment by rebornix** [comment]
Can you reproduce the same issue in regular editor with markdown file?

**Comment by sandy081** [comment]
Same with markdown file

**Comment by aeschli** [comment]
@sandy081 Can you explain how you want to add content in a markdown file if not with the keyboard?

**Comment by sandy081** [comment]
Actually `cmd+down` allows me navigate to end. So closing.
