### ISSUE TITLE
The git repository has too many active changes

### ISSUE THREAD

**Issue by iyartsev** [microsoft/vscode#96577]
- VSCode Version: 1.44.2
- OS Version: Windows 10 Enterprise 1909 Build 18363.778

Does this issue occur when all extensions are disabled?: Yes

I get "The git repository has too many active changes" warning but there is no active changes at all. VS Code shows always 0 changes even if changes were made. I have this problem with one particular project (workspace). At first it worked fine, I finished the project and haven't opened it for some period of time. When I recently opened it again I got this problem.
![vs](https://user-images.githubusercontent.com/43533665/80603279-7c7f4400-8a30-11ea-9049-65bf698caf1b.png)

**Comment by joaomoreno** [comment]
If you run `git status` from the command line on that folder, what's the result?

**Comment by iyartsev** [comment]
> If you run `git status` from the command line on that folder, what's the result?


```
$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	<file>
	<folder>
	<folder>
	<folder>
	<folder>

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by joaomoreno** [comment]
Why are all those files untracked? Are you building a huge commit?

**Comment by iyartsev** [comment]
Those file are untracked because they should not be tracked, they are temporary files/folders. 
One of the folders contained a lot of files (9500+). I removed this files/folders and now the Problem is gone.
Thank you very much!
But I think this should be considered as a bug anyway, since no active changes were present. At least the warning message should be consiedred to be changed.

Best Regrards,
Ivan

**Comment by joaomoreno** [comment]
This is not a bug, since those were active changes. If you want certain files to be ignored from git, just add them to [`gitignore`](https://help.github.com/en/github/using-git/ignoring-files).
