### ISSUE TITLE
Markdown extension enhancement (update on css change)

### ISSUE THREAD

**Issue by stevensona** [Microsoft/vscode#9657]
In addition to rerendering the markdown preview of a markdown file when the contents of the document change, it should also rerender when any of the associated styles (from `"markdown.styles"`) are modified. If I get time, I will attempt to take a stab at this.

**Comment by stevensona** [comment]
Because the markdown preview is an HTML document that is referencing the stylesheet, it really only makes sense to update the view when the CSS file is saved, not edited.

**Comment by mjbvz** [comment]
Rolling this into #32111, which tracks adding a refresh command for the markdown preview.
