### ISSUE TITLE
Terminal info hover is getting in my way

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96574]
* have a terminal with tweaked context
* move your mouse
* you are facing a big hover that hard to dismiss (and easily reappears)

* suggestion: show this only on click
* suggestion: show this (on hover) only after a good delay (200ms or so)

<img width="637" alt="Screenshot 2020-04-29 at 15 10 33" src="https://user-images.githubusercontent.com/1794099/80599706-a3874700-8a2b-11ea-97a0-058dd6380716.png">

**Comment by Tyriar** [comment]
Same feedback from @bpasero. My plan it to add the hover delay and also I think I've got enough feedback about it being scary to change the default to only show the warning icon:

```
"terminal.integrated.environmentChangesIndicator": "warnonly"
```
