### ISSUE TITLE
Problem with new folder/file combination

### ISSUE THREAD

**Issue by mikes-zum** [microsoft/vscode#96572]
Working in Markdown

Right-click on top folder name in the tree-view and select "New Folder".
The new folder when added appears in the list.

Right-click on the new folder and select "New File". The tree-view greys out and nothing is selected, rather than there being a "slot" under the folder name to add the file. It is necessary to right-click on the new folder and select "New File" again, then the new file can be added.

This used to work but seems to have been broken since the start of this week.

**Comment by isidorn** [comment]
Thanks for filling this, however dup of https://github.com/microsoft/vscode/issues/96566
So it should be fixed tomorrow, please do let me know if you still see it then
