### ISSUE TITLE
DebugSession setBreakPointsRequest Regression

### ISSUE THREAD

**Issue by GordonSmith** [microsoft/vscode#96579]
- VSCode Version: 1.44.2
- OS Version: Windows 10 (2004)

Steps to Reproduce:

1.  Implement a DebugSession with a  setBreakPointsRequest method
2.  Add some breakpoints to your code before submitting
3.  In `DebugSession.setBreakPointsRequest ` return the "response" without adding a "breakpoints" array.

Does this issue occur when all extensions are disabled?: NA

My debug sessions are hanging (not proceeding to the "ConfigurationDoneRequest") with the following code:
```
    protected setBreakPointsRequest(response: DebugProtocol.SetBreakpointsResponse, args: DebugProtocol.SetBreakpointsArguments): void {
        this.sendResponse(response);
    }
```

But proceed as expected with the following:
```
    protected setBreakPointsRequest(response: DebugProtocol.SetBreakpointsResponse, args: DebugProtocol.SetBreakpointsArguments): void {
        response.body = {
            breakpoints: []
        };
        this.sendResponse(response);
    }
```

The above code is quite old, so suspect this is a regression in VS Code

**Comment by isidorn** [comment]
Please change https://github.com/microsoft/vscode-mock-debug such that this issue is reproducable. So I can clone and see the issue.

**Comment by GordonSmith** [comment]
@isidorn - https://github.com/microsoft/vscode-mock-debug/pull/42

**Comment by GordonSmith** [comment]
Previous behaviour:
* The program would have completed without any breaks and "configurationDoneRequest" **would** have been called..

New behaviour:
* The program appears to be "stuck" and "configurationDoneRequest" is **never called**.

**Comment by weinand** [comment]
@GordonSmith the spec says that the `breakpoints` array is  mandatory, so if you are sending a response without a `breakpoints` array you are violating the spec.

@isidorn Since VS Code was handling this situation gracefully before, we should continue to do so.

**Comment by GordonSmith** [comment]
@weinand thanks for the update.  100% agree about the specification.

But this issue is with the `vscode-debugadapter -> DebugSession` , either its ` dispatchEvent` logic or an invalid declaration?

The `setBreakpointsRequest` declaration is:
```javascript
protected setBreakPointsRequest(response: DebugProtocol.SetBreakpointsResponse, args: DebugProtocol.SetBreakpointsArguments, request?: DebugProtocol.Request): void;
```

Where `SetBreakpointsResponse` is declared as:
```javascript
interface SetBreakpointsResponse extends Response {
    body: {
        breakpoints: Breakpoint[];
    };
}
```
Isn't the onus on the caller of `setBreakPointsRequest` to honour the declaration?

I would suggest that its this **cast** that prevented TypeScript from catching this specific issue at compile time...:  https://github.com/microsoft/vscode-debugadapter-node/blob/master/adapter/src/debugSession.ts#L506

**Comment by GordonSmith** [comment]
Further - The default implementation is also "violating the spec"...:  https://github.com/microsoft/vscode-debugadapter-node/blob/master/adapter/src/debugSession.ts#L722-L724

**Comment by isidorn** [comment]
@GordonSmith I could not reproduce the exact issue you were seeing after cloning Mock debug with latest VS Code insiders.
Please try to repro with VS Code insiders in a couple of days when the commit I just pushed is a part of the release.

As for other locations that you found that violate the spec we are open for PRs that fix this, feel free to create one a ping me on it. Thanks a lot!

**Comment by GordonSmith** [comment]
@isidorn:  https://github.com/microsoft/vscode-debugadapter-node/pull/230

**Comment by isidorn** [comment]
Thanks a lot for the PR, initialy assigned to @weinand
