### ISSUE TITLE
Jupyter-notebook background-color not correct when connected via SSH

### ISSUE THREAD

**Issue by Hujedamej** [microsoft/vscode#96571]
The background color of jupyter notebooks are not correct if connected to a remote server via SSH, locally it works fine.

    VSCode Version: 1.44.2
    Local OS Version: Ubuntu 19.10
    Remote OS Version: Ubuntu 19.10
    Remote Extension/Connection Type: Remote-SSH v0.51.0 / SSH
    Other Extensions: Python v2020.4.74986 (on server and locally)

Steps to Reproduce:

1.  select a Color Theme
2. open a .ipynb file (the jupyter module must be installed in the python environment to open it as a jupyter-notebook) - background color is as it should be
3.  connect to a vscode server via SSH (local network) and open a .ipynb file (the python extension with jupyter module must be installed on the server) - the background color is dark grey and not as in all other tabs according to the selected color theme

**Comment by roblourens** [comment]
We've made tons of changes, this probably works now, please let me know if not.
