### ISSUE TITLE
Documentation about publishing an extension is invalid with new page design

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#9658]
there no such menus and buttons anymore in visualstudio site and also vsce wont work with obtained token
![](http://i.imgur.com/WtnJ9Ej.png)

**Comment by gregvanl** [comment]
Hi Nikos, 
If you are still having trouble publishing an extension with the latest vsce and you feel the documentation on code.visualstudio.com is wrong, please enter an issue on https://github.com/Microsoft/vscode-docs/issues.
Thanks
