### ISSUE TITLE
some bug 

### ISSUE THREAD

**Issue by masterkaizer** [microsoft/vscode#96585]
Issue Type: <b>Bug</b>

when i git commit some time it dont find my repo 
or 
sometime its says missing permision

VS Code version: Code - Insiders 1.45.0-insider (4bd206856db30c27d38aa0f1fbe74bac6156edc7, 2020-04-29T05:33:59.143Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900KS CPU @ 4.00GHz (16 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.81GB (49.51GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/israe/OneDrive/Bureau/brandon%20sellam%20homework/homework-10|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
deepcode|dee|2.0.1
vscode-mysql|for|0.4.0
dotenv|mik|1.0.1
python|ms-|2020.4.76186
open-in-browser|tec|2.0.0
commandlist|yam|1.0.3

</details>

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the error?
