### ISSUE TITLE
Find a better way to display collapsed views in Panel

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#96584]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode/issues/96318. 

At the right side of the panel are three collapsed views. This has been going through several iterations but the current solution is less than perfect. It wastes space and does not look good. 

![image](https://user-images.githubusercontent.com/4674940/80608475-acf0bf00-89eb-11ea-97be-0e1d0cf75f07.png)

VS Code version: Code - Insiders 1.45.0-insider (4bd206856db30c27d38aa0f1fbe74bac6156edc7, 2020-04-29T05:31:36.229Z)
OS version: Darwin x64 18.7.0

**Comment by joaomoreno** [comment]
Related: https://github.com/microsoft/vscode/issues/94249

**Comment by joaomoreno** [comment]
From https://github.com/microsoft/vscode/issues/94249

> > and vertically feels like it changes the aesthetics a lot:
> > ![image](https://user-images.githubusercontent.com/35271042/78270757-1a2e3480-74c0-11ea-8e8d-12b9fc38dbd2.png)
> 
> I kinda like this!

This solution is so good, why aren't we doing this exactly? Looks so much better than the current approach and doesn't waste any space.

**Comment by sbatten** [comment]
As mentioned last week or the week before, we would like to explore this version but instead of the icons being on 3 separate bars, they go to a single bar making them even more compact. @joaomoreno

**Comment by sbatten** [comment]
The above change implements the simplest version of bookend style with icons. Let's try it out and iterate as needed.

**Comment by bpasero** [comment]
Cool. Gave it a try, but seems to have some issues still:

![image](https://user-images.githubusercontent.com/900690/81643442-e1ba3880-9425-11ea-83ec-ea5ee44fec30.png)

In this example (using `yarn web`) I dragged open editors and some debug views into a panel.

**Comment by joaomoreno** [comment]
Lookin' pretty sexy over here

**Comment by sbatten** [comment]
@bpasero updated

**Comment by bpasero** [comment]
@sbatten yeah works better. do we need new icons for all of the views, e.g. in debug?

![image](https://user-images.githubusercontent.com/900690/81774693-83578d80-94eb-11ea-842b-550de8e0f2c6.png)

//cc @sandy081

**Comment by sandy081** [comment]
Yeah this is being tracked here - https://github.com/microsoft/vscode/issues/93964

@sbatten 👏
