### ISSUE TITLE
Restoring panel state

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#96582]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode/issues/96318.

- move the sidebar view container of the docker extension into the panel
- reload the window
-> The docker view container is back in the sidebar

VS Code version: Code - Insiders 1.45.0-insider (4bd206856db30c27d38aa0f1fbe74bac6156edc7, 2020-04-29T05:31:36.229Z)
OS version: Darwin x64 18.7.0

**Comment by sbatten** [comment]
fixed by https://github.com/microsoft/vscode/commit/6b95e9f5d0d06749353bcfa94a2e7c8852b3e6b8
