### ISSUE TITLE
Opening saved search editor throws DisposableStore errors

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#96587]
While verifying #89268

- Open one of the searches under `.vscode/searches` in the vscode repo

![image](https://user-images.githubusercontent.com/323878/80609582-dfa3b300-89fd-11ea-939d-9824eff583ac.png)

**Comment by roblourens** [comment]
Dunno if it's related but I saw this too, I think when opening a code-search file in git diff view: 
![image](https://user-images.githubusercontent.com/323878/80609765-20033100-89fe-11ea-8db0-c297f7fe44f9.png)

**Comment by JacksonKearl** [comment]
Noticing lots of weirdness with saved search editors that wasn't there when I last updated...

**Comment by roblourens** [comment]
That may be related to whatever is going on in https://github.com/microsoft/vscode/issues/96454

**Comment by JacksonKearl** [comment]
Fixed now. Thanks!
