### ISSUE TITLE
Remote explorer duplicate info in dropdown and section header

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#96588]
Issue Type: <b>Bug</b>

See the following screenshots.

![image](https://user-images.githubusercontent.com/4674940/80609297-c7776800-89ec-11ea-910c-61f64ca2f9dc.png)

![image](https://user-images.githubusercontent.com/4674940/80609350-d2ca9380-89ec-11ea-8110-714bc553cc06.png)

We should consider collapsing the section header with the view container header if there is no other view (such as Feedback) visible. Same way we do it in the explorer.

VS Code version: Code - Insiders 1.45.0-insider (4bd206856db30c27d38aa0f1fbe74bac6156edc7, 2020-04-29T05:31:36.229Z)
OS version: Darwin x64 18.7.0

**Comment by alexr00** [comment]
As part of https://github.com/microsoft/vscode/issues/86037, the title of view view would be Targets, which would remove the duplicate string.
