### ISSUE TITLE
Terminal does not adapt its size

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#96586]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode/issues/96318. 

1) join Terminal and Output view containers in the panel
2) collapse both of them
3) reload you window
4) expand the terminal
-> see screenshot

![image](https://user-images.githubusercontent.com/4674940/80608861-44561200-89ec-11ea-819c-f0e60bf4ae9b.png)

VS Code version: Code - Insiders 1.45.0-insider (4bd206856db30c27d38aa0f1fbe74bac6156edc7, 2020-04-29T05:31:36.229Z)
OS version: Darwin x64 18.7.0

**Comment by Tyriar** [comment]
I've been trying to find repro steps to get into this state 👍

**Comment by Tyriar** [comment]
@sbatten looks like it's on your end?

![image](https://user-images.githubusercontent.com/2193314/80627891-6dcf6780-8a05-11ea-8487-8ded450f0656.png)

I guess the other panels don't suffer from this as they use css to layout?

**Comment by Tyriar** [comment]
Hopefully this will fix the other issues I've seen where the scroll bar appears on the left like this.

**Comment by joaomoreno** [comment]
I still see this: 
![image](https://user-images.githubusercontent.com/22350/80725863-eddbf700-8b03-11ea-8a52-33959f011732.png)

**Comment by Tyriar** [comment]
@joaomoreno is the scrollbar in the middle or the end? The problem is fixed for me in both windows and wsl.

**Comment by joaomoreno** [comment]
It's next to the content:

![image](https://user-images.githubusercontent.com/22350/80955312-5f1af300-8dff-11ea-8b23-d97ce4040290.png)

**Comment by sbatten** [comment]
@Tyriar I debugged this and it seems you are not applying the dimensions properly to terminal tabs created after the initial expand. When the terminal view is expanded, the right dimensions are passed here: https://github.com/microsoft/vscode/blob/9237df9e9ae2275880d97ba4baa583cae73cf02f/src/vs/workbench/contrib/terminal/browser/terminalView.ts#L117-L124

But the next line is about updating existing terminals. This happens on reload and there are no existing terminals yet. The first terminal is then created but is not properly sized.
