### ISSUE TITLE
View drag indicators are hard to see

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#96595]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode/issues/96318.

When draging a view container icon along the activity bar or along the panel title almost all of the time what I'm dragging hides the line that's shown to indicate the insert position. Also, I cannot move outside a bit (such as down in the panel, or in my case left from the activity bar) as this changes the feedback to in view feedback (blue rectangles). 

VS Code version: Code - Insiders 1.45.0-insider (4bd206856db30c27d38aa0f1fbe74bac6156edc7, 2020-04-29T05:31:36.229Z)
OS version: Darwin x64 18.7.0

**Comment by sbatten** [comment]
this was resolved by a separate issue. this fix was to shift the feedback image down and to the right allowing more visibility under the cursor.
