### ISSUE TITLE
Tests shows "can not find module" red squiggle when tests directory is excluded from main tsconfig.json

### ISSUE THREAD

**Issue by kpritam** [microsoft/vscode#96594]
- VSCode Version:  1.44.2
- OS Version: MacOs catalina 10.15.4 (19E287)

Steps to Reproduce:

1. Checkout this reproducer repo: https://github.com/kpritam/vscode-test-import-bug
2. Load project in vscode
3. Run `npm test`, all works fine
4. Open `src/tests/index.test.ts` file, vscode shows red squiggle with can not find module error

More information:
```json
===== tsconfig.json =====
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "rootDir": "./src",
    "moduleResolution": "node",
    "lib": ["ES2015", "DOM", "DOM.Iterable"],
    "resolveJsonModule": true,
    "strict": true,
    "baseUrl": "src",
  },
  "include": ["src/**/*", "index.ts"],
  "exclude": ["node_modules", "dist", "src/tests/*"]
}
```

```js
==== jest.config.json ====
module.exports = {
  roots: ['<rootDir>'],

  preset: 'ts-jest',
  testRegex: '(/src/tests/.*|(\\.|/)(test|spec))\\.ts?$',
  moduleFileExtensions: ['ts', 'js', 'json', 'node'],
  moduleDirectories: ['node_modules', 'src'],
};
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
You've excluded that test file from your tsconfig project. That means that that settings like `rootDir` will not apply to it.

If you want to use those settings you need to create a tsconfig that includes the test files too
