### ISSUE TITLE
Cannot move problems to the far right of the panel

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#96596]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode/issues/96318.

![image](https://user-images.githubusercontent.com/4674940/80611365-5ab19d00-89ef-11ea-9be0-c03a11c785c5.png)

When I grab the Problems tab I cannot move it farther to the right although there are two more views on the panel. How do I do this without resizing my window or playing Towers of Hanoi?

VS Code version: Code - Insiders 1.45.0-insider (4bd206856db30c27d38aa0f1fbe74bac6156edc7, 2020-04-29T05:31:36.229Z)
OS version: Darwin x64 18.7.0

**Comment by sbatten** [comment]
unless I see more issues about this, the cost to fix this is rather high
