### ISSUE TITLE
Open with for custom editors doesn't always show active

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#96591]
Testing https://github.com/microsoft/vscode/issues/94347

It only shows which one is active if it's the built in editor:
![image](https://user-images.githubusercontent.com/38270282/80610282-7477d200-8a39-11ea-82fc-bd3e201acc3d.png)
![image](https://user-images.githubusercontent.com/38270282/80610334-85284800-8a39-11ea-8556-e560be79b6e1.png)

**Comment by mjbvz** [comment]
@rebornix 0593e5b Should fix this for notebooks too. As part of the fix, changed `getEditorOverrides` to take a resource instead of an editor input
