### ISSUE TITLE
Hardware Acceleration issue with various graphics cards

### ISSUE THREAD

**Issue by gsogeek** [microsoft/vscode#96598]
We have written the needed data i
Issue Type: <b>Bug</b>

When launching the application with hardware GPU support enabled, the application UI is unstable and degrades to the point of becoming unusable (screenshot 1) The UI will degrade over time when left open, progressing from minor blur to becoming usable on the elements from the application. As seen on screenshot 2, this doesn't appear to affect active text boxes.

-Screenshot 1:
![image](https://user-images.githubusercontent.com/348429/80613656-8fcbe880-8a0b-11ea-9a5d-f7674147db86.png)

-Screenshot 2:
![image](https://user-images.githubusercontent.com/348429/80613715-a2462200-8a0b-11ea-8ff1-7cda4300bfd9.png)

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (5.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (83)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vscode-toggl|arm|0.0.5
LinkCheckMD|bla|0.3.1
npm-intellisense|chr|1.3.0
vscode-css-modules|cli|0.2.3
bracket-pair-colorizer-2|Coe|0.0.29
vscode-markdownlint|Dav|0.35.1
vscode-simpler-icons|dav|1.6.5
jshint|dba|0.10.21
vscode-eslint|dba|2.1.5
docs-article-templates|doc|0.2.8
docs-authoring-pack|doc|0.1.8
docs-images|doc|0.0.8
docs-linting|doc|0.0.3
docs-markdown|doc|0.2.66
docs-metadata|doc|1.0.4
docs-preview|doc|0.3.47
docs-yaml|doc|0.2.5
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
prettier-vscode|esb|4.5.0
vscode-firefox-debug|fir|2.7.2
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.2
cloudcode|goo|1.2.1
todo-tree|Gru|0.0.173
helium-icon-theme|hel|1.0.0
beautify|Hoo|1.5.0
rest-client|hum|0.23.2
easy-icons|jam|0.3.1
vscode-peacock|joh|3.7.0
chat|kar|0.33.0
vscode-gutter-preview|kis|0.26.1
vscode-docker|ms-|1.1.0
csharp|ms-|1.21.17
vscode-edge-devtools|ms-|1.0.7
kind-vscode|ms-|0.0.3
kubernetes-opa-vscode|ms-|0.0.2
vscode-kubernetes-tools|ms-|1.2.0
mssql|ms-|1.9.0
python|ms-|2020.4.76186
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-ssh-edit-nightly|ms-|2020.4.9540
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.9
azurecli|ms-|0.5.0
Go|ms-|0.14.1
powershell-preview|ms-|2020.4.3
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2104
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.3.4
vsonline|ms-|1.0.2116
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.6
debugger-for-edge|msj|1.0.14
vscode-react-native|msj|0.15.0
vscode-sanddance|msr|1.2.12
color-highlight|nau|2.3.0
vetur|oct|0.24.0
indent-rainbow|ode|7.4.0
vscode-css-peek|pra|3.0.2
vscode-seedling-icon-theme|ras|0.5.0
vscode-yaml|red|0.7.2
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.4
gruvbox-material|sai|6.1.10
code-settings-sync|Sha|3.4.3
music-time|sof|1.8.21
swdc-vscode|sof|2.2.2
code-spell-checker|str|1.8.0
vscode-field-lights|sve|0.0.11
sass-indented|syl|1.8.3
opa|tsa|0.4.2
highlight-matching-tag|vin|0.9.9
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.1.1
codetour|vsl|0.0.23
gistfs|vsl|0.0.66
armviz|yte|0.0.9

(7 theme extensions excluded)

</details>

**Comment by deepak1556** [comment]
Can you see if the issue happens with exploration builds https://github.com/microsoft/vscode/issues/94074#issuecomment-607079209

> When launching the application with hardware GPU support enabled,

Have you tried to disable hw acceleration in `1.44.2` https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration ?

**Comment by gsogeek** [comment]
That build didn't change the effect when the GPU was enabled. Using the disable flag does resolve the issue, but is not a valid long-term solution.

GPU Enabled:
![Exploratory1](https://user-images.githubusercontent.com/348429/80803414-333e0a00-8b80-11ea-90fe-e69e34e75179.PNG)

with --disable-gpu added:
![Exploratory2](https://user-images.githubusercontent.com/348429/80803600-ca0ac680-8b80-11ea-9d41-c121f67755b0.PNG)

**Comment by gsogeek** [comment]
I'm doing a bit more testing on the affected devices and there seems to be a common element between electron-based apps and the Radeon driver being delivered in the latest round of Windows Updates... I'm seeing it stabilize and clear up when I remove the driver set, and re-install from AMD (Radeon Software 19.10.24.04) rather than what is delivered by windows update. I'll know more for sure when I run that process on a second affected machine and establish a pattern.

**Comment by gsogeek** [comment]
This is a result of a windows update interacting with a Radeon GPU.
