### ISSUE TITLE
Bot: Unlabel and unassign

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#96600]
But should have ability to remove labels and assignees added with slash-label and slash-assign commands.

**Comment by JacksonKearl** [comment]
Ref'd the wrong issue...

**Comment by JacksonKearl** [comment]
\label api

**Comment by JacksonKearl** [comment]
\label api

**Comment by JacksonKearl** [comment]
\label api

**Comment by JacksonKearl** [comment]
fourth time's the charm...
\label api

**Comment by JacksonKearl** [comment]
\label -api

**Comment by JacksonKearl** [comment]
now, when a label or assignee is prefixed with `-`, it will be removed. To escape this, simply use quotes as before: (replace `slash` with a slash)

```
slash-assign JacksonKearl -NotJacksonKear
slash-label -remove -"remove with spaces" "-add with a leading hyphen" -"-remove with hypen"
```

**Comment by roblourens** [comment]
sldkfj
ssldfj sdf
lsjkdf
lsdkfj
/label api

**Comment by roblourens** [comment]
First it said `/label verified 😎` on the same line which i think prompted the error.
