### ISSUE TITLE
Opening a file randomly overwrites the file in the current tab

### ISSUE THREAD

**Issue by DelvarWorld** [Microsoft/vscode#9660]
- VSCode Version: 1.3.1
- OS Version: OSX

Steps to Reproduce:

1. Open a file in a tab
2. Find a new file by pressing ⌘P and hit Enter

Based on (the phase of the moon?) the current tab will either be replaced by the new file, or the new file will be opened in a new tab.

When splits are involved, I literally have no idea where a file will be opened. Sometimes I'll hit ⌘-Enter to to try to open the file in a tab in my second split, but the same problem happens, the file in the second split will be randomly overwritten.

There are clearly some rules about tabs/splits I don't understand, but this is alien behavior compared to other editors. My mental model of how file handling is implemented in vscode is currently "random number generator."

**Comment by gertcuykens** [comment]
Can you try opening project directory first so you see them all in de side bar. I think when you open a new non project file vscode considers it as just notes that can be discarded if nothing is changed in it.

**Comment by DelvarWorld** [comment]
Are you saying if I want to open two files in two tabs, I have to make a change to one of them first?!

**Comment by gertcuykens** [comment]
This is done so you don't end op with 100 tabs if you want to quickly read files but don't know which file it was. Maybe there is a option or maybe a extra edit pannel command so it does open a new tab. But personally I prefer current behavior to only create new tabs when they have changes on them.

**Comment by kieferrm** [comment]
@DelvarWorld  when you open a file with `⌘P` or by single click in the file explorer or search pane the file is opened in `preview mode`.  When a file in preview mode is modified or a file is opened by double click the editor is being pinned. When use tabs, the preview tab has an *italic* title.

As @gertcuykens says the reason behind that is that otherwise you would end up with too many tabs  too easily. However, I can see that for `⌘P` that this might cause slight confusion. Pls reopen if there are more issues.

@bpasero FYI

**Comment by DelvarWorld** [comment]
@kieferrm can you clarify that the only way to open two files in two tabs is to force the user to edit one of them, undo the edit, then open the next file? Or is there another way?

**Comment by gertcuykens** [comment]
When you double click on the tab it stays open even if you don't change anything.

**Comment by kieferrm** [comment]
@DelvarWorld as mentioned above: Double click the file in the file explorer.

**Comment by bpasero** [comment]
Please note that you can disable the preview altogether by setting `"workbench.editor.enablePreview": false`
