### ISSUE TITLE
[Feature request] Command to clear undo history for current file/session.

### ISSUE THREAD

**Issue by mmghv** [microsoft/vscode#96601]
It would be very useful to have a command to clear undo history for current file/session.

That would allow for more control while trying to benefit from the "persist undo" feature, so I can use it but still have the ability to clear undo history whenever I want.

**Scenario when this is needed:**
When I finish some changes and commit them, I usually want to clear undo history so that I can start a new commit and not undo changes from previous commit by accident.

**Comment by boltex** [comment]
My extension (https://github.com/boltex/leointeg) uses file system api to implement custom 'editors' for my needs as indicated in the docunmentation here https://code.visualstudio.com/api/extension-guides/virtual-documents#file-system-api .

I need to  be able to 'block' or 'clear' undos when closing or switching from one of them to another. 

It used to be that doing vscode.WorkspaceEdit "rename" operation would 'clear'/'block' all undos for the newly named document to traverse across the point where the document was renamed, but lately the newer versions of vscode tries to open a document with the old name when pressing ctrl+Z on a newly renamed document (in a custom filesystem)... Is there a way to disable that? Or a way to clear the undo stack for a given document URL? or for a filesystem scheme only in particular? 

Thanks!
