### ISSUE TITLE
InputBox buttons not showing in version 1.44

### ISSUE THREAD

**Issue by alejhb** [microsoft/vscode#96602]
Issue Type: <b>Bug</b>

The InputBox buttons are not shown in version 1.44 the same code, shown below, works with version 1.43.

To reproduce:
Create a new extension and implement the hello word command as shown below, then run the extension and execute the command.

// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';
import * as path from 'path';

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {

	// Use the console to output diagnostic information (console.log) and errors (console.error)
	// This line of code will only be executed once when your extension is activated
	console.log('Congratulations, your extension "test" is now active!');

	// The command has been defined in the package.json file
	// Now provide the implementation of the command with registerCommand
	// The commandId parameter must match the command field in package.json
	let disposable = vscode.commands.registerCommand('extension.helloWorld', () => {
		const searchBox = vscode.window.createInputBox();
		

		searchBox.buttons = [{iconPath: {
			light: vscode.Uri.file(path.join(context.extensionPath,'resources', 'light', 'bins.svg')),
			dark: vscode.Uri.file(path.join(context.extensionPath,'resources', 'dark', 'bins.svg'))
		},
		tooltip: "Browse for file(s)"}];
		
		searchBox.onDidTriggerButton((button) => {
			if(button.tooltip === "Browse for file(s)") {
				vscode.window.showInformationMessage('Button Clicked!');
			}
			searchBox.dispose();
		});

		searchBox.show();
	});

	context.subscriptions.push(disposable);
}

// this method is called when your extension is deactivated
export function deactivate() {}

Installation details:

Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:50:03.709Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-96-generic

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 4.15.0-96-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz (32 x 1613)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 4|
|Memory (System)|31.37GB (4.41GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
restructuredtext|lex|126.0.0
ruby-rubocop|mis|0.8.3
vscode-typescript-tslint-plugin|ms-|1.2.3

</details>

**Comment by chrmarti** [comment]
Workaround is to set a title.
