### ISSUE TITLE
Regions issue

### ISSUE THREAD

**Issue by MartinGonzalez** [Microsoft/vscode#9661]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Regions must be in the same tab. It would be great to allow us to fold no matter if they are in the same tab or not.
![wrong](https://cloud.githubusercontent.com/assets/4130008/17082018/93afe09a-5144-11e6-809b-345afabc7cc7.png)
![right](https://cloud.githubusercontent.com/assets/4130008/17082019/95e419ee-5144-11e6-8e7f-1e5c435f0699.png)

Steps to Reproduce:

1. Create a Script (C#)
2. Create a method
3. Create a region encapsulating the method (Must be at the same tabulation)
4. Region cannot be fold
5. Move the method using tab
6. Now you can fold the region

**Comment by kieferrm** [comment]
@MartinGonzalez I moved this issue to the repo for the C# extensions Pls subscribe to https://github.com/OmniSharp/omnisharp-vscode/issues/617.
