### ISSUE TITLE
Inactive selected items of sidebar have almost the same color that the sidebar separators

### ISSUE THREAD

**Issue by gorka-gil-ob** [microsoft/vscode#96618]
Having almost the same color makes the sidebar file browser section more difficult to read.

I would suggest to change list.inactiveSelectionBackground default value, for example:

"list.inactiveSelectionBackground": "#45525e"

I'm not expert in colors, nor like to edit color themes, but this case was annoying me a bit :)
Any color different of the current one will work for me.

**Comment by gorka-gil-ob** [comment]
Forgot to mention:
- I refer to the theme: Default Dark+
- I'm using version: 1.44.2

**Comment by misolori** [comment]
This is actually improved, we recently updated the section header backgrounds transparent and use borders instead:

![image](https://user-images.githubusercontent.com/35271042/80741596-bc950400-8ace-11ea-9d4b-2aa5afbefadc.png)

See #93764

**Comment by gorka-gil-ob** [comment]
that's great !

thanks for the really fast response.

Continue with the good work, it is a pleasure to use vscode !!
