### ISSUE TITLE
Notebook renderer starter: Clarify how to debug

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#96619]
Issue Type: <b>Bug</b>

https://github.com/microsoft/vscode/issues/96302

How do I make breakpoints set within the `client` folder not be ignored?

VS Code version: Code - Insiders 1.45.0-insider (4bd206856db30c27d38aa0f1fbe74bac6156edc7, 2020-04-29T05:31:36.229Z)
OS version: Darwin x64 18.7.0

**Comment by connor4312** [comment]
This is something several people have asked about, I've opened an issue for it here 🙂  https://github.com/microsoft/vscode/issues/96626
