### ISSUE TITLE
Support double click view container sash to center 

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#96622]
Double clicking this:

![image](https://user-images.githubusercontent.com/2193314/80626465-5c855b80-8a03-11ea-81be-91c9db5fe4f2.png)

Should result in the sash being centered:

![image](https://user-images.githubusercontent.com/2193314/80626514-6c9d3b00-8a03-11ea-86e2-46801d7720a0.png)

This is an existing gesture that exists for viewlet, panel, editor groups and terminal splits.

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/95994
