### ISSUE TITLE
Notebook renderer starter: Hot reload?

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#96623]
Issue Type: <b>Bug</b>
https://github.com/microsoft/vscode/issues/96302

1. `npm run watch`, F5
2. Create GitHub issues notebook and run a query, change output renderer to `x-application/github-issues`
3. Make a change within `render` in `render.ts` in the client folder
4. Switch output renderer back and forth

I expected my changes to be picked up and rendered, is this not the case?

VS Code version: Code - Insiders 1.45.0-insider (4bd206856db30c27d38aa0f1fbe74bac6156edc7, 2020-04-29T05:31:36.229Z)
OS version: Darwin x64 18.7.0

**Comment by connor4312** [comment]
This should be picked up. When you make a change, do you see anything in the console output for the notebook webview? (`Developer: Open Webview Developer Tools`)

**Comment by connor4312** [comment]
I misunderstood the issue. I think that we have file caching in VS Code that would not render when just switching between views. The 'new' notebook renderer starter supports better hot reloading at this point via HMR/webpack-dev-server, thus closing the issue.
