### ISSUE TITLE
HTML autocomplete LI tag does not insert a newline on enter

### ISSUE THREAD

**Issue by ayyash** [Microsoft/vscode#9662]
- VSCode Version: 1.4.0-Insider
- OS Version: Windows 10

1. Type LI then tab (this will produce `<li></li>`)
2. Type enter (to make a new line between the `<li></li>`)

Expected: a new line insert between the tags
Buggy behavior: The cursor jumps outside of the LI tags

**Comment by kieferrm** [comment]
@ayyash I can't reproduce this behavior with the latest insider. Can you pls try if you see the same behavior if you launch vscode with the `--disable-extensions` command line argument? 

Pls reopen if you have additional information.

**Comment by ayyash** [comment]
you're right, it works without extensions, now I have to figure out which extension :/
