### ISSUE TITLE
Expanding a collapsed panel can result in the panel content being too large

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#96624]
Found when testing https://github.com/microsoft/vscode/issues/96586#event-3284936985

Notice how as I tab to the last item, the panel shifts:

![recording (2)](https://user-images.githubusercontent.com/2193314/80626787-d3baef80-8a03-11ea-97b6-bc455ebf7541.gif)

**Comment by sbatten** [comment]
resolving as duplicate unless it repros after your shift fix
