### ISSUE TITLE
after update, C/C++ Extension stopped working in VSCode insiders

### ISSUE THREAD

**Issue by salda** [microsoft/vscode#96636]
- VSCode Version: Version: 1.45.0-insider (system setup)
Commit: 4bd206856db30c27d38aa0f1fbe74bac6156edc7
Date: 2020-04-29T05:33:59.143Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
- OS Version: Windows 10

Steps to Reproduce:

1. run VSCode Insiders
2. write code/run task
3. watch VSCode insiders being slow, Intellisense not working, ctrl+shift+B not running task etc.

Check this image:
![image](https://user-images.githubusercontent.com/3855627/80643001-aa33af80-8a67-11ea-8d0e-8448a2551066.png)

Does this issue occur when all extensions are disabled?: No

**Comment by alexr00** [comment]
Can you provide a copy/pastable task that I can use to try to repro with?

**Comment by sean-mcmanus** [comment]
@alexr00 We are seeing tons of VS Code Insider user reports involving the error "The task provider for "C/C++" tasks unexpectedly provided a task of type "shell": https://github.com/microsoft/vscode-cpptools/issues/5388 . It doesn't appear with VS Code non-Insiders and repros with our insiders and non-insiders versions of our C/C++ extension so it seems like it's a VS Code Insiders regression and not a bug with our extension. I don't understand the repro yet though.

**Comment by ivankravets** [comment]
Hi @alexr00, again a ton of reports about "The task provider for "C/C++" tasks unexpectedly provided a task of type "shell" for @PlatformIO. How could we fix it?

**Comment by pfeerick** [comment]
@ivankravets It looks to be a two-fold issue... recent change in VSCode has exposed an configuration issue in the C/C++ extension. Explained here: https://github.com/microsoft/vscode-cpptools/issues/5388#issuecomment-625275433, with a fix to hide that message due in the next few days: https://github.com/microsoft/vscode-cpptools/issues/5388#issuecomment-626082004

**Comment by sean-mcmanus** [comment]
@ivankravets We shipped a fix for 0.28.0-insiders3 Friday evening, but we found some last minute issues so 0.28.0 won't be released till  Tuesday evening probably.

**Comment by ivankravets** [comment]
Thanks, @sean-mcmanus, for the updates!

**Comment by sean-mcmanus** [comment]
@faelv Look for code that creates vscode.Task objects with the source field being undefined.

**Comment by faelv** [comment]
Thanks for the reply @sean-mcmanus. Source is `"composer"`, a string... maybe I should wait for a new build.

**Comment by faelv** [comment]
> Thanks for the reply @sean-mcmanus. Source is `"composer"`, a string... maybe I should wait for a new build.

Just pointing out that it keeps happening in 1.46.1

**Comment by sean-mcmanus** [comment]
@faelv There's a difference between the "source" and "type" (that I didn't realize previously), so you should double check that all the "type" strings are not undefined. You can refer to the PR at https://github.com/microsoft/vscode-cpptools/pull/5585/files where I fixed an issue where we were using an incorrect "source" of type "shell" instead of "C/C++" where the "type" is "shell". We have another work in progress PR to try to change the "type" to "cppbuild" at https://github.com/microsoft/vscode-cpptools/pull/5659 that may be helpful as well.
