### ISSUE TITLE
Environment variable collections should not be applied to terminals that use TerminalOptions.strictEnv API

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#96630]
It also shouldn't show the warning for these terminals.

**Comment by brianignacio5** [comment]
@Tyriar I'm using engine v1.45 and @types/vscode^1.45.0 and still happening this. Env Variables are post appending. Is not clear to me if this is already part of 1.45.0 or not.

Using macOS Catalina and VSCode info
Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by Tyriar** [comment]
I just tested this and it's working fine and not applying when `strictEnv` is set.
