### ISSUE TITLE
To open extension side bar as soon as command execution is complete.

### ISSUE THREAD

**Issue by ngarg-panw** [microsoft/vscode#96631]
I am working on an extension which uses TreeView API to show the results in the side bar. 
I have the following the in the extension:
Option on the context menu.
Icon button in the activitybar, clicking on which side bar opens(Uses TreeView API).

Right now, After clicking on the option on context menu the command completes but user has no way of knowing. The results will only be visible when i click on the button on activitybar to open sidebar for that extension.

It would be nice to have the possibility to open that side bar automatically once the command completes to display the results. Also, some indication on the activitybar button (badge) with count of issues or something will be helpful at the very least.

Thanks!

**Comment by alexr00** [comment]
You can do this in your command using the API
https://github.com/microsoft/vscode/blob/0ccc731fb80cdaf312b9e59acab10dcf198dee55/src/vs/vscode.d.ts#L7876-L7888
