### ISSUE TITLE
Cells missing "Run Below" option after first cell

### ISSUE THREAD

**Issue by tigerhawkvok** [microsoft/vscode#96634]
Version: 1.44.2 (system setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Create a notebook with `#%%`-style cells
2.  Try to run everything below a point

Does this issue occur when all extensions are disabled?: Yes

Honestly, "Run Above" could go away altogether if it was an either/or; it's "run below" that's the more important of the two. There used to be both, but one went away a while ago and seeing as it hasn't come back it's clearly not on someone's radar (though I thought there was an issue about this, I couldn't find it)

**Comment by rebornix** [comment]
sorry for the late response, this is a feature currently contributed by the Python extension, please file issues against them. Also, the Python extension is moving their implementation to VS Code native notebook API, once that's done, this issue will be gone.
