### ISSUE TITLE
Source Control stages Merge Changes when trying to stage all Changes

### ISSUE THREAD

**Issue by bruno-brant** [microsoft/vscode#96640]
Issue Type: <b>Bug</b>

During a rebase (not sure if that's the only scenario), my SOURCE CONTROL tab display three sections, MERGE CHANGES, STAGED CHANGES and CHANGES. 

If I click the + button on the CHANGES section, in order to stage all items below CHANGES, VS Code also adds everything on MERGE CHANGES.

VS Code version: Code - Insiders 1.45.0-insider (4bd206856db30c27d38aa0f1fbe74bac6156edc7, 2020-04-29T05:33:59.143Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (1.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.5.0
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
plantuml|jeb|2.13.8
svg|joc|1.1.8
vscode-peacock|joh|3.7.0
chat|kar|0.33.0
rust-analyzer|mat|0.2.151
vscode-todo-parser|min|1.9.1
remote-wsl|ms-|0.44.2
vsliveshare|ms-|1.0.2104
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.3.4
vscode-xml|red|0.11.0
vscode-yaml|red|0.7.2
crates|ser|0.4.9
vscode-hexdump|sle|1.7.2
markdown-all-in-one|yzh|2.8.0

</details>

**Comment by pfongkye** [comment]
Hello @joaomoreno @bruno-brant 
I would like to work on this issue if no one else is.
Regards.

**Comment by swapnilmisal** [comment]
@joaomoreno hey could you please review the pr that I have opened and also could you please suggest any changes if required.

**Comment by pfongkye** [comment]
Hi @swapnilmisal 
I'm also working on this issue. You can check my PR #97349

**Comment by swapnilmisal** [comment]
@pfongkye I have gone through your PR also left a comment.
