### ISSUE TITLE
Use global tasks.json before project based tasks.json

### ISSUE THREAD

**Issue by jchannon** [Microsoft/vscode#9664]
- VSCode Version: 1.3.1
- OS Version: OSX 10.11.5

Steps to Reproduce:
1. Create a new project and setup tasks.json.
2. Create a new projects and setup another tasks.json
3. Repeat for each project
4. I have a lot of csharp projects and having to copy paste tasks.json to each is cumbersome.
5. Could VSCode look for a tasks.json or tasks.{language}.json in a global directory eg. ~/.vscode/tasks that can be applied to projects?
6. If tasks.json exists locally then it uses that or it merges both files some how

**Comment by QantumEntangled** [comment]
Is this on the roadmap yet?

**Comment by dbaeumer** [comment]
@QantumEntangled no. Can you provide me with a use case for when you would need such a global tasks.json file now that we have contributable task detection. For example there is no need anymore to setup a tasks.json file to compile TS files. The TypeScript language extension now contributes tasks to do that and they are available without a tasks.json file in the workspace.

**Comment by QantumEntangled** [comment]
@dbaeumer A few different things, but mostly attaching a terminal-executed command to shortcut keys. AFAIK the only way to do this is with tasks and I would like to assign one of two keyboard shortcuts to things and not have to copy-paste a task config into every workspace.

Currently I'm trying to map "ctrl+alt+z" to zip all the files WITHIN the workspace and into a file [workspaceName]-[timeDate].zip using a terminal command. Everything works great except making it global.

If there's a better way to do this that would be great, but I REALLY don't see the point in pushing this into a whole extension, that's pretty overkill.

**Comment by dbaeumer** [comment]
@QantumEntangled that kind of task does makes sense to me.

**Comment by dbaeumer** [comment]
Dups #1435.
