### ISSUE TITLE
Cell language picker shows incorrect language

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#96642]
Issue Type: <b>Bug</b>

In the picture below a markdown cell is in edit mode:
![image](https://user-images.githubusercontent.com/4674940/80645971-bd6f5c80-8a20-11ea-9dea-e553a4a806dd.png)

VS Code version: Code - Insiders 1.45.0-insider (4bd206856db30c27d38aa0f1fbe74bac6156edc7, 2020-04-29T05:31:36.229Z)
OS version: Darwin x64 18.7.0

**Comment by roblourens** [comment]
I can't repro, what did you do to get into that state?

**Comment by roblourens** [comment]
I remember fixing issues like this earlier
