### ISSUE TITLE
Linked file does not show little linked arrow

### ISSUE THREAD

**Issue by kingces95** [microsoft/vscode#96646]
- VSCode Version: 
> Version: 1.45.0-insider
Commit: a250df703de955a38aed427a917bce8278ab3331
Date: 2020-04-24T20:46:59.782Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

- OS Version:
![image](https://user-images.githubusercontent.com/4120386/80271377-6867cb00-865b-11ea-8c69-979f015e37a9.png)

Steps to Reproduce:
1. Create `foo/test.js`
2. Create`bar/`
3. Create a symbolic link in `bar` to `foo/test.js` named `test.js`

Expect a little arrow to show that `bar/test.js` is a linked file. Actually see no such little arrow -- just a green "U". It's also odd that directories `foo` and `bar` are colored red in the explorer. What's the matter with 'em?

![image](https://user-images.githubusercontent.com/4120386/80650205-3fef2080-8a0f-11ea-848c-c0d89c6cf073.png)

[symlink.zip](https://github.com/microsoft/vscode/files/4554801/symlink.zip)

Does this issue occur when all extensions are disabled? Yes

**Comment by bpasero** [comment]
I cannot reproduce btw:

![image](https://user-images.githubusercontent.com/900690/97551247-06ee3380-19d3-11eb-98c9-4ff53ea9623e.png)
