### ISSUE TITLE
Clearing the contents of settings.json does not trigger a settings update.

### ISSUE THREAD

**Issue by Wanye1062271859** [microsoft/vscode#96655]
- VSCode Version: 1.44.2
- OS Version: Windows x64 10.0.18363
- C/C++ Extension: 0.28.0-insiders

**Steps to Reproduce:**
1. Download repo https://devdiv.visualstudio.com/DevDiv/_git/Vcls-vscode-test.
2. Open SingleRootProject and install C/C++ Extension.
3. Open setting.json file, uncomment and copy the content of "editor.tokenColorCustomizations" from semantic_colorization.cpp to it.
4. Add setting "compilerArgs": ["/clr"] to c_cpp_properties.json, make sure semantic tokens are colored based on their type in semantic_colorization.cpp
5. Delete all contents of settings.json file and save it.

**Expected:**
The Semantic colorization returns to the original color in semantic_colorization.cpp.

**Actual:**
Semantic colorization doesn't update.

**Comment by Colengms** [comment]
I think a simple explaination of this issue is: Clearing the contents of settings.json does not trigger a settings update.  I assume this is because empty contents are not a valid JSON object.

**Comment by aeschli** [comment]
I can reproduce what @Colengms describes: Clearing the contents of settings.json does not trigger a settings update.

**Comment by sandy081** [comment]
@aeschli How are you clearing the contents? Are you leaving empty json object or completely emptying the file?

**Comment by aeschli** [comment]
Select all, delete (no JSON object)
