### ISSUE TITLE
Allow goToSymbol via copy pasted path

### ISSUE THREAD

**Issue by ackvf** [microsoft/vscode#96651]
Our code comments sometimes mention symbols in other files. I want to be able to copy such a path `LayoutEditor.tsx@acceptsChildren` and paste it into goToSymbol field like this:

![vscode-go-to-symbol](https://user-images.githubusercontent.com/2313018/80656685-0dcad680-8a82-11ea-9a5f-04632f69fbcf.gif)

However, it doesn't work currently and needs to be done in two steps.

**Comment by mjbvz** [comment]
Seems to me that ideally that symbol in the comment should just be clickable. That falls under https://github.com/microsoft/TypeScript/issues/35524

**Comment by ackvf** [comment]
@mjbvz That comment is not actually a jsdoc and we don't use `@see` in that instance. But if it were supported by jsdoc, we might consider switching over.

Though, the copy/paste is generally useful as I also sometimes share these symbol links via instant messaging with colleagues.
