### ISSUE TITLE
[Refactor Preview] Cannot apply refactoring because 'x' file has changed in the meantime

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#96654]
We try to enable preview refactoring when the user renames a package from file explorer, but it seems pretty often to run into the notification `"Cannot apply refactoring because 'x' file has changed in the meantime"`, even though we didn't really modify these files.

<img width="444" alt="Screen Shot 2020-04-29 at 11 57 41 PM" src="https://user-images.githubusercontent.com/148698/80653298-2b943d80-8a7a-11ea-9f09-b06ef06e1201.png">

Screencast: https://streamable.com/eoyh9w

BTW, if you want me to provide reproduce steps, i can package a private vscode-java.vsix, and share how to reproduce it using a Java sample code.

**Comment by testforstephen** [comment]
// @jrieken

**Comment by jrieken** [comment]
This messages is rooted [here](https://github.com/microsoft/vscode/blob/954d03fd6e5c7f15293eed94c07f19b2ae4e8b1d/src/vs/workbench/services/bulkEdit/browser/conflicts.ts#L53) and [here (same file)](https://github.com/microsoft/vscode/blob/954d03fd6e5c7f15293eed94c07f19b2ae4e8b1d/src/vs/workbench/services/bulkEdit/browser/conflicts.ts#L74) and it means what it says. Either the file on disk or in memory has changed *before* applying the workspace edit - it will then fail to apply. Can you try setting breakpoints in the locations I have pointed out to see why the file changes?

**Comment by testforstephen** [comment]
Thanks for the instruction. I enabled two breakpoints at what you mentioned, the conflicted files are the sub files from the renamed folder. Given we didn't change these sub files, so vscode will receive FileDidChangeEvent for sub files when renaming a parent folder, right?

![image](https://user-images.githubusercontent.com/14052197/80696617-38607200-8b0a-11ea-8b99-8bbb5614c297.png)

When renaming a package (folder), we will start a job when receiving `onWillRenameFiles` event, waitUntil and save the result to a shared variable. And then when receiving `onDidRenameFiles`, if the result is already computed, apply/preview the edit directly. 

So when receiving FolderDidRenameEvent, looks like it'll trigger sub files didChangeEvent at the same time. **Is there any safe way to make sure FolderDidRenameEvent listener to know all sub file didChangeEvent ready**?

**Comment by jrieken** [comment]
> Given we didn't change these sub files, so vscode will receive FileDidChangeEvent for sub files when renaming a parent folder, right?

idk - @bpasero do you? are events fired for all children when a folder is being renamed?

**Comment by testforstephen** [comment]
i found the language server actually received `'workspace/didChangeWatchedFiles'` notification twice during renaming a Java folder.

The first one is indeed related with rename operation, which only contains old location delete, new location create, and no sub files event. 

The second one is received after calling the api workspace.applyEdit to trigger preview. Also the server received a series of didOpen/didClose textDocument events ([bulkEditPreview.ts](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/bulkEdit/browser/bulkEditPreview.ts#L406)) before the `didChangeWatchedFiles` notification. Since the server didn't receive any didChange textDocument event, there must be some code changing the disk file instead of the document. And the changed sub files in the second `didChangeWatchedFiles` notification are just same as the error "Cannot apply refactoring because 'x' file is changed in the meantime".  The weird thing is the changed sub files are not same when trying multiple times. It probably changed 1 file, 2 files, 4 files etc. Kind of a multi-threaded competition issue.

**Comment by jrieken** [comment]
> The second one is received after calling the api workspace.applyEdit to trigger preview

This is you triggering the event. See https://github.com/microsoft/vscode/blob/master/src/vs/vscode.d.ts/#L9255-L9265

**Comment by testforstephen** [comment]
>This is you triggering the event. See https://github.com/microsoft/vscode/blob/master/src/vs/vscode.d.ts/#L9255-L9265

Sorry for the confusion. The second [didChangeWatchedFiles](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_didChangeWatchedFiles) notification is not rename event.

I draw the whole workflow below. The second 'didChangeWatchedFiles' notification (step 6) just says some sub files under the renamed folder are changed during previewing the workspace edit. And if i commented out step 3, the extension won't receive this extra 'didChangeWatchedFiles' notification. That's why i suspect the applyEdit api changed some files due to some reason.


```
1. In file explorer, try to rename a Java folder 
src/main/java/org/springframework/samples/petclinic/vet to vetnew
                                ↓
2. onWillRenameFiles event arrives. In the event callback, the extension will call waitUntil to 
waiting for computing the workspace edit, then save the result to a global variable 
instead of passing it to waitUntil promise. We want to preview the edit, it's not suitable to 
do that in the onWill listener, so we just let waitUntil promise returns null.
                                ↓
3. onDidRenameFiles event arrives. In the event callback, the extension will call 
workspace.applyEdit to preview the cached edit .
                                ↓
4.  'workspace/didChangeWatchedFiles' notification arrives. Below is its payload:
Params: {
    "changes": [
        {
            "uri": ".../src/main/java/org/springframework/samples/petclinic/vetnew",
            "type": 1
        },
        {
            "uri": ".../src/main/java/org/springframework/samples/petclinic",
            "type": 2
        },
        {
            "uri": ".../src/main/java/org/springframework/samples/petclinic/vet",
            "type": 3
        }
    ]
}
                            ↓
5. A series of textDocument/didOpen and textDocument/didClose notifications arrive. These text 
documents all are the files touched by the applied workspace edit. And these text document events
may start to arrive after step 3.
                            ↓

6. A second notification 'workspace/didChangeWatchedFiles' arrives.  Its payload:
Params: {
    "changes": [
        {
            "uri": ".../src/main/java/org/springframework/samples/petclinic/vetnew/Specialty.java",
            "type": 2
        },
        {
            "uri": ".../src/main/java/org/springframework/samples/petclinic/vetnew/Specialty.java",
            "type": 2
        }
    ]
}

                            ↓
7. In the REFACTOR PREVIEW panel, click "Apply Refactoring" button, will get the error saying 
'Specialty.java' is changed in the meantime.
```

**Comment by testforstephen** [comment]
it turns out the Java language server modified some files when it received `textDocument/didOpen` events for the sub files under the renamed folder.

Will close the issue, thanks for the support!
