### ISSUE TITLE
No focus when creating new file with vscode not in foreground

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#9665]
- VSCode Version: 1.4.0-insider
- OS Version: OSX

Steps to Reproduce:

1. Have VSCode open and any other app so that both of them are visible
2. Make sure other app is in foreground (has focus)
3. Right click any folder in VSCode and select New file
4. Input box does not have focus (you cant start typing - you will be typing in other app)

Here is screenshot
![image](https://cloud.githubusercontent.com/assets/1723815/17084928/d27aac3e-5198-11e6-867d-88e77f3ac4fb.png)

**Comment by joaomoreno** [comment]
This is OS behaviour, there is nothing we can do as an app.
