### ISSUE TITLE
Energy hog when running, on mac 10.15.4

### ISSUE THREAD

**Issue by murthysista** [microsoft/vscode#96657]
Issue Type: <b>Bug</b>

Ever since the OS upgrade, this product has been a energy hog. It is my favorite editor so far - but this problem is making me look for alternatives

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|17, 10, 6|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
json-tools|eri|1.0.2
macros|ged|1.2.1
gc-excelviewer|Gra|2.1.34
beautify|Hoo|1.5.0
prettify-json|moh|0.0.3
python|ms-|2020.4.76186
java|red|0.60.0
vscode-hexdump|sle|1.7.2
octave|toa|0.0.3
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2

</details>

**Comment by jrieken** [comment]
> Ever since the OS upgrade, this product has been a energy hog.

Are you saying it was better before the upgrade? Isn't that a OS bug then?

You can use this guide to inspect what's happening while using VS Code: https://github.com/Microsoft/vscode/wiki/Performance-Issues. I agree that it shouldn't just burn and waste energy and that things should run as minimal as possible but without actionable information there won't be a code change.
