### ISSUE TITLE
Slow rendering plus import errors 

### ISSUE THREAD

**Issue by mich2k** [microsoft/vscode#96652]
Hello, I am having a very woody experience on my dell xps 15 7590
indeed just today vscode suggested me to switch to dom renderer even if this (even if improved a bit) didnt help so much
here is my code status

thank you

```
/usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so: undefined symbol: g_date_time_format_iso8601
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
[17502:0430/013114.722896:ERROR:gl_surface_glx.cc(88)] glXGetFBConfigs failed.
[17502:0430/013114.722933:ERROR:gl_surface_glx.cc(128)] Failed to get GLXConfig
[17502:0430/013114.722938:ERROR:gl_surface_glx.cc(477)] CreateDummyWindow(gfx::GetXDisplay()) failed
[17502:0430/013114.722945:ERROR:gl_initializer_x11.cc(148)] GLSurfaceGLX::InitializeOneOff failed.
[17502:0430/013114.724897:WARNING:x11_util.cc(1399)] X error received: serial 401, error_code 8 (BadMatch (invalid parameter attributes)), request_code 78, minor_code 0 (X_CreateColormap)
[17502:0430/013114.724992:ERROR:viz_main_impl.cc(176)] Exiting GPU process due to errors during initialization
[17477:0430/013114.727154:WARNING:gpu_process_host.cc(1225)] The GPU process has crashed 1 time(s)
[17477:0430/013114.759632:WARNING:gpu_process_host.cc(995)] Reinitialized the GPU process after a crash. The reported initialization time was 14 ms
Version:          Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS Version:       Linux x64 5.5.19-050519-generic
CPUs:             Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 899)
Memory (System):  15.27GB (3.55GB free)
Load (avg):       1, 1, 1
VM:               0%
Screen Reader:    no
Process Argv:     --force-user-env --no-sandbox --unity-launch --no-sandbox
GPU Status:       2d_canvas:                     unavailable_software
                  flash_3d:                      disabled_software
                  flash_stage3d:                 disabled_software
                  flash_stage3d_baseline:        disabled_software
                  gpu_compositing:               disabled_software
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        disabled_off
                  rasterization:                 disabled_software
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  disabled_software
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         unavailable_software
                  webgl2:                        unavailable_software

CPU %	Mem MB	   PID	Process
    0	   141	  2496	code main
    0	    31	  2498	   zygote
    0	   203	  2532	   gpu-process
    0	    78	  2533	   utility
    0	   109	  2682	   shared-process
    0	     0	 17510	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 17511	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   344	 12783	   window (● monete.c - Fond-INF-2 - Visual Studio Code)
    0	   188	 12830	     extensionHost
    0	    31	 12899	       /home/mich/.vscode/extensions/ms-vscode.cpptools-0.28.0-insiders/bin/cpptools
    0	     0	 17229	         /home/mich/.vscode/extensions/ms-vscode.cpptools-0.28.0-insiders/bin/cpptools-srv 12899 1
    0	    63	 13227	       /snap/code/31/usr/share/code/code /snap/code/31/usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=12830
    0	    63	 12848	     watcherService
    0	    63	 13011	     searchService
    0	     0	 15776	     /bin/bash
    0	   219	 13685	   window (undefined)

Workspace Stats: 
|  Window (● monete.c - Fond-INF-2 - Visual Studio Code)
|    Folder (Fond-INF-2): 148 files
|      File types: tlog(24) c(15) sln(4) vcxproj(4) filters(4) user(4) log(4)
|                  lastbuildstate(4) suo(4) db(4)
|      Conf files: sln(4) launch.json(1) settings.json(1) tasks.json(1)
|      Launch Configs: cppdbg
```

- Ubuntu 20.04 fossa

even without extensions i keep having this error

**Comment by mich2k** [comment]
This is code exploration status, seems working slightly better so far, at least there is not tearing as before
`[34515:0430/031725.621232:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
Version:          Code - Exploration 1.45.0-exploration (f04d8ca5cc1122855000e63140f3b165346c1869, 2020-04-28T06:33:40.082Z)
OS Version:       Linux x64 5.5.19-050519-generic
CPUs:             Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 1243)
Memory (System):  15.27GB (1.17GB free)
Load (avg):       1, 1, 1
VM:               0%
Screen Reader:    no
Process Argv:     --no-sandbox --unity-launch
GPU Status:       2d_canvas:                  enabled
                  flash_3d:                   enabled
                  flash_stage3d:              enabled
                  flash_stage3d_baseline:     enabled
                  gpu_compositing:            enabled
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          disabled_off
                  opengl:                     enabled_on
                  protected_video_decode:     unavailable_off
                  rasterization:              disabled_software
                  skia_renderer:              enabled_on
                  video_decode:               unavailable_off
                  viz_display_compositor:     enabled_on
                  vulkan:                     disabled_off
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %	Mem MB	   PID	Process
    0	   125	 26557	code-exploration main
    0	    31	 26561	   zygote
    0	   141	 26584	   gpu-process
    0	    47	 26600	   utility
    0	   219	 26603	   window (● monete.c - Fond-INF-2 - Visual Studio Code - Exploration)
    0	   172	 26655	     extensionHost
    0	    16	 26746	       /home/mich/.vscode-exploration/extensions/ms-vscode.cpptools-0.27.1/bin/cpptools
    0	     0	 26794	         /home/mich/.vscode-exploration/extensions/ms-vscode.cpptools-0.27.1/bin/cpptools-srv 26746 0
    0	     0	 26656	     /bin/bash
    0	    63	 26679	     watcherService
    0	   109	 26688	   shared-process
    0	     0	 34527	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 34528	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   172	 26941	   window (undefined)

Workspace Stats: 
|  Window (● monete.c - Fond-INF-2 - Visual Studio Code - Exploration)
|    Folder (Fond-INF-2): 146 files
|      File types: tlog(24) c(15) sln(4) vcxproj(4) filters(4) user(4) log(4)
|                  lastbuildstate(4) suo(4) db(4)
|      Conf files: sln(4) launch.json(1) tasks.json(1)
|      Launch Configs: cppdbg`

**Comment by deepak1556** [comment]
Thanks for the detailed info, the insiders version seems to be crashing in the gpu process, can you try running with hw acceleration disabled https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

> This is code exploration status, seems working slightly better so far, at least there is not tearing as before

Thats good to know, the runtime probably gained support for your gpu since most of the hw accelerated features are enabled. But when you mean slightly better, does that imply you are still seeing slow rendering ?

**Comment by mich2k** [comment]
The first status log is the standard version (the blue one) and the second one the orange one (exploration)
thank you for your reply
so, at the moment the slow rendering seems fixed with code exploration, even if i still have this error:
```[12919:0430/142255.423735:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
Version:          Code - Exploration 1.45.0-exploration (f04d8ca5cc1122855000e63140f3b165346c1869, 2020-04-28T06:33:40.082Z)
OS Version:       Linux x64 5.5.19-050519-generic
CPUs:             Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4036)
Memory (System):  15.27GB (7.96GB free)
Load (avg):       1, 1, 1
VM:               0%
Screen Reader:    no
Process Argv:     --no-sandbox --unity-launch
GPU Status:       2d_canvas:                  enabled
                  flash_3d:                   enabled
                  flash_stage3d:              enabled
                  flash_stage3d_baseline:     enabled
                  gpu_compositing:            enabled
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          disabled_off
                  opengl:                     enabled_on
                  protected_video_decode:     unavailable_off
                  rasterization:              disabled_software
                  skia_renderer:              enabled_on
                  video_decode:               unavailable_off
                  viz_display_compositor:     enabled_on
                  vulkan:                     disabled_off
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %   Mem MB     PID  Process
    0      125    9359  code-exploration main
    0       31    9363     zygote
    0      141    9386     gpu-process
    0       47    9402     utility
    0      250    9410     window (● monete.c - Fond-INF-2 - Visual Studio Code - Exploration)
    0      172    9460       extensionHost
    0       16    9616         /home/mich/.vscode-exploration/extensions/ms-vscode.cpptools-0.27.1/bin/cpptools
    0        0    9649           /home/mich/.vscode-exploration/extensions/ms-vscode.cpptools-0.27.1/bin/cpptools-srv 9616 0
    0       47   11758         /usr/share/code-exploration/code-exploration /usr/share/code-exploration/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=9460
    0        0    9461       /bin/bash
    0        0   12875         bash /usr/bin/code-exploration --status
    0       63   12880           electron_node cli.js 
    0       94   12893             /usr/share/code-exploration/code-exploration --status --no-sandbox
    0       31   12895               zygote
    0       63   12919               gpu-process
    0       63    9484       watcherService
    0      109    9542     shared-process
    0        0   12927       /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0        0   12928         /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0      203   10796     window (undefined)

Workspace Stats: 
|  Window (● monete.c - Fond-INF-2 - Visual Studio Code - Exploration)
|    Folder (Fond-INF-2): 146 files
|      File types: tlog(24) c(15) sln(4) vcxproj(4) filters(4) user(4) log(4)
|                  lastbuildstate(4) suo(4) db(4)
|      Conf files: sln(4) launch.json(1) tasks.json(1)
|      Launch Configs: cppdbg```

meanwhile If i running with the disable hw flag also this error vanishes:
```
Version:          Code - Exploration 1.45.0-exploration (f04d8ca5cc1122855000e63140f3b165346c1869, 2020-04-28T06:33:40.082Z)
OS Version:       Linux x64 5.5.19-050519-generic
CPUs:             Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 899)
Memory (System):  15.27GB (7.76GB free)
Load (avg):       1, 1, 1
VM:               0%
Screen Reader:    no
Process Argv:     --no-sandbox --unity-launch
GPU Status:       2d_canvas:                  unavailable_software
                  flash_3d:                   disabled_software
                  flash_stage3d:              disabled_software
                  flash_stage3d_baseline:     disabled_software
                  gpu_compositing:            disabled_software
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          disabled_off
                  opengl:                     disabled_off
                  protected_video_decode:     disabled_off
                  rasterization:              disabled_software
                  skia_renderer:              enabled_on
                  video_decode:               disabled_software
                  viz_display_compositor:     enabled_on
                  vulkan:                     disabled_off
                  webgl:                      unavailable_software
                  webgl2:                     unavailable_software

CPU %   Mem MB     PID  Process
    0      141   13913  code-exploration main
    0       31   13917     zygote
    0      188   13940     gpu-process
    0       47   13951     utility
    1      344   13962     window (argv.json - Fond-INF-2 - Visual Studio Code - Exploration)
    0      188   14008       extensionHost
    0       47   14052         /usr/share/code-exploration/code-exploration /usr/share/code-exploration/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=14008
    0       16   14079         /home/mich/.vscode-exploration/extensions/ms-vscode.cpptools-0.27.1/bin/cpptools
    0        0   14009       /bin/bash
    0        0   14172         bash /usr/bin/code-exploration --status
    0       47   14177           electron_node cli.js 
    0       94   14189             /usr/share/code-exploration/code-exploration --status --no-sandbox
    0       31   14191               zygote
    0       47   14214               gpu-process
    0       31   14225               utility
    0       63   14032       watcherService
    0      141   14127     shared-process
    0        0   14235       /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0        0   14236         /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Stats: 
|  Window (argv.json - Fond-INF-2 - Visual Studio Code - Exploration)
|    Folder (Fond-INF-2): 146 files
|      File types: tlog(24) c(15) sln(4) vcxproj(4) filters(4) user(4) log(4)
|                  lastbuildstate(4) suo(4) db(4)
|      Conf files: sln(4) launch.json(1) tasks.json(1)
|      Launch Configs: cppdbg```

**Comment by mich2k** [comment]
I have tried Insiders version too, but it has all the issues that the standard vscode (1.44.2) has

**Comment by deepak1556** [comment]
Thanks for testing, the gpu issue is something that gets fixed over upgrade in runtime of VSCode, fortunately for your case its fixed in electron 8 which will be available for insiders release in next week. Until then I would suggest you to disable hw acceleration with your current build. Will update this issue once the build is out.

**Comment by mich2k** [comment]
updated:
Code - Insiders

```
code-insiders --status
/usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so: undefined symbol: g_date_time_format_iso8601
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
[13063:0510/000054.441183:ERROR:gl_surface_glx.cc(88)] glXGetFBConfigs failed.
[13063:0510/000054.441244:ERROR:gl_surface_glx.cc(128)] Failed to get GLXConfig
[13063:0510/000054.441252:ERROR:gl_surface_glx.cc(477)] CreateDummyWindow(gfx::GetXDisplay()) failed
[13063:0510/000054.441262:ERROR:gl_initializer_x11.cc(148)] GLSurfaceGLX::InitializeOneOff failed.
[13063:0510/000054.443950:WARNING:x11_util.cc(1399)] X error received: serial 401, error_code 8 (BadMatch (invalid parameter attributes)), request_code 78, minor_code 0 (X_CreateColormap)
[13063:0510/000054.444050:ERROR:viz_main_impl.cc(176)] Exiting GPU process due to errors during initialization
[13036:0510/000054.448223:WARNING:gpu_process_host.cc(1225)] The GPU process has crashed 1 time(s)
[13036:0510/000054.495927:WARNING:gpu_process_host.cc(995)] Reinitialized the GPU process after a crash. The reported initialization time was 19 ms
Version:          Code - Insiders 1.46.0-insider (d487078dc7fc1c276657cadb61b4f63833a8df55, 2020-05-07T16:36:39.681Z)
OS Version:       Linux x64 5.4.0-29-generic
CPUs:             Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 900)
Memory (System):  15.27GB (10.29GB free)
Load (avg):       1, 1, 1
VM:               0%
Screen Reader:    no
Process Argv:     --force-user-env --no-sandbox --unity-launch --no-sandbox
GPU Status:       2d_canvas:                     unavailable_software
                  flash_3d:                      disabled_software
                  flash_stage3d:                 disabled_software
                  flash_stage3d_baseline:        disabled_software
                  gpu_compositing:               disabled_software
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        disabled_off
                  rasterization:                 disabled_software
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  disabled_software
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         unavailable_software
                  webgl2:                        unavailable_software

CPU %	Mem MB	   PID	Process
    0	   125	 12836	code-insiders main
    0	    31	 12838	   zygote
    0	    47	 12878	   utility
    0	    94	 12879	   gpu-process
    0	   297	 12890	   window (Welcome - Visual Studio Code - Insiders)
    0	    94	 12941	     extensionHost
    0	   109	 12958	   shared-process
    0	     0	 13071	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 13072	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

```

code-exp

```
 code-exploration --status
[14073:0510/000329.345933:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
Version:          Code - Exploration 1.46.0-exploration (7faa10cfc640a15751049cdc6e894c5d146ff7dd, 2020-05-08T06:40:01.797Z)
OS Version:       Linux x64 5.4.0-29-generic
CPUs:             Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 900)
Memory (System):  15.27GB (9.06GB free)
Load (avg):       1, 1, 1
VM:               0%
Screen Reader:    no
Process Argv:     --no-sandbox --unity-launch
GPU Status:       2d_canvas:                  enabled
                  flash_3d:                   enabled
                  flash_stage3d:              enabled
                  flash_stage3d_baseline:     enabled
                  gpu_compositing:            enabled
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          disabled_off
                  opengl:                     enabled_on
                  protected_video_decode:     unavailable_off
                  rasterization:              disabled_software
                  skia_renderer:              enabled_on
                  video_decode:               unavailable_off
                  viz_display_compositor:     enabled_on
                  vulkan:                     disabled_off
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %	Mem MB	   PID	Process
    0	   125	 13632	code-exploration main
    0	    31	 13635	   zygote
    0	   109	 13658	   gpu-process
    0	    47	 13674	   utility
    0	   328	 13677	   window (massHashConverter.py - Progetti [in_progress] - Visual Studio Code - Exploration)
    0	   172	 13732	     extensionHost
    0	    31	 13950	       /usr/bin/python3 /home/mich/.vscode-exploration/extensions/ms-python.python-2020.4.76186/pythonFiles/pyvsc-run-isolated.py /home/mich/.vscode-exploration/extensions/ms-python.python-2020.4.76186/pythonFiles/completion.py
    0	    16	 13967	         /usr/bin/python3 /home/mich/.vscode-exploration/extensions/ms-python.python-2020.4.76186/pythonFiles/lib/python/jedi/inference/compiled/subprocess/__main__.py /home/mich/.vscode-exploration/extensions/ms-python.python-2020.4.76186/pythonFiles/lib/python 3.8.2
    0	    47	 13951	       /usr/share/code-exploration/code-exploration /usr/share/code-exploration/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=13732
    0	     0	 13733	     /bin/bash
    0	    63	 13754	     watcherService
    0	    63	 13798	     searchService
    0	   125	 13819	   shared-process
    0	     0	 14085	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 14086	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Stats: 
|  Window (massHashConverter.py - Progetti [in_progress] - Visual Studio Code - Exploration)
|    Folder (Progetti [in_progress]): 18 files
|      File types: py(3) git(2) gitignore(2) md(2) inp(2) json(1)
|      Conf files: settings.json(1)
```

**Comment by deepak1556** [comment]
@mich2k sorry we haven't pushed electron 8 to insiders, please continue to use the exploration build if you need hw acceleration. I will update this bug once electron 8 based insiders is ready.

**Comment by deepak1556** [comment]
Should be fixed in latest insiders https://code.visualstudio.com/insiders, please check. Thanks!
