### ISSUE TITLE
how to debug main process

### ISSUE THREAD

**Issue by erasermeng** [microsoft/vscode#96659]
![image](https://user-images.githubusercontent.com/8306959/80678125-e5c48d00-8aec-11ea-8cbc-bf29f1ba8032.png)

I found that "Launch VS Code (Main Process)" has been removed

how to debug main process now?

**Comment by joaomoreno** [comment]
Simply run the `VS Code` config and you'll be automatically debugging all processes.

**Comment by erasermeng** [comment]
![image](https://user-images.githubusercontent.com/8306959/80778375-cc7a1a00-8b9a-11ea-880c-b5b754b3380f.png)

@joaomoreno  I set a breakpoint in the main function, but it does not seem to take effect

**Comment by joaomoreno** [comment]
I believe you can't debug it that early, right @weinand @connor4312 ?

**Comment by connor4312** [comment]
Yea--in our debug setup, the main process is attached to asynchonrously, so the debugger won't be attached for things that happen early in startup.

**Comment by erasermeng** [comment]
so I think the launch script should be reserved？ @joaomoreno  @connor4312 
![image](https://user-images.githubusercontent.com/8306959/81243982-c9bc7080-9043-11ea-9707-1188cf6d3236.png)

**Comment by joaomoreno** [comment]
@erasermeng You're right, I've added the `Main Process` target back.
