### ISSUE TITLE
The previous workspace is also opened when executing "code . " in a new workspace

### ISSUE THREAD

**Issue by Wanye1062271859** [microsoft/vscode#96661]
- VSCode Version: 1.44.2
- OS Version: Windows x64 10.0.18363

Steps to Reproduce:
	1. Download MultiRootProjects from repo https://devdiv.visualstudio.com/DevDiv/_git/Vcls-vscode-test
	2. Open "Command Prompt" window
	3. Cd to project_A, type "code ." to open Project_A
	4. File -> Add Folder to Workspace->Select "Project_B" 
	5. Close Vscode (There is no any tips to ask to save current workspace)
	6. Cd to project_C in command window.
        7. Execute "Code ."

**Notes:** If the previous workspace was opened again because it has not been saved, Vscode should provide some hints to save changes when performing the step 5.

Expected:
Only the project_C folder was opened

Actual:
Two Vscode instances were opened at the same time
![image](https://user-images.githubusercontent.com/29274719/80678876-5ae49200-8aee-11ea-9dc5-1e8716be10b3.png)

**Comment by bpasero** [comment]
https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-file
