### ISSUE TITLE
Give option to turn off bell when focusing next terminal

### ISSUE THREAD

**Issue by aounleonardo** [microsoft/vscode#96666]
I'm on Mac OS and using the integrated terminal. When I focus the next terminal using the keystroke `workbench.action.terminal.focusNext` or `focusPrevious`, the bell rings and I would like to disable it. I've tried removing the Enable Bell checkbox in the integrated terminal settings but it doesn't remove it.

**Comment by Tyriar** [comment]
If the bell is ringing and enableBell is off, it's something in your shell that's doing it.

**Comment by aounleonardo** [comment]
Thanks, I'll look into it
