### ISSUE TITLE
VSCode don't see pip modules, which were created with virtual env

### ISSUE THREAD

**Issue by ivnvalxndr1** [microsoft/vscode#96668]
Мы скопировали необходимые данные в буфер обмена, так как у них был слишком большой размер для отправки. Вставьте эти данные.

**Comment by ivnvalxndr1** [comment]
использую VS Code для разработки на python:
1) create project folder "test";
2) in the folder i opened terminal, then use command "python -m venv env" to create virtual env. env was created successful.
3) i activate virtual env with commands "cd env/Scripts" , "activate". activating was successful.
4) then i install module "flask" in the virtual env with command "pip install Flask". Flask was installed successful.
5) in our folder "test" i creating test file "testapp.py". in the file i write starting template:
 "
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello World!'

if __name__ == '__main__':
    app.run()
" 
and save it.
6) i run "testapp.py" with virtual env.


7) #############error point##############
#######error:


[Running] python -u "c:\Users\xxx\Desktop\test\testapp.py"
Traceback (most recent call last):
  File "c:\Users\xxx\Desktop\btrb\python.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

[Done] exited with code=1 in 0.079 seconds


############# i waited to see:
Running on http://127.0.0.1:5000/


...
vs code is looking for module flask globally, and not in virtual env

**Comment by ivnvalxndr1** [comment]
i edited description of my problem on English language

**Comment by Tyriar** [comment]
@JacksonKearl english please bot misbehaving above.

**Comment by Tyriar** [comment]
@ivnvalxndr1 please report this to https://github.com/microsoft/vscode-python, thanks.
