### ISSUE TITLE
*.json files constantly reside in the "Recent files" section at Windows 10

### ISSUE THREAD

**Issue by MxGrv** [microsoft/vscode#96670]
- VSCode Version: 1.44.2
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create or open a new *.json file
2. Try to delete it from recents
3. Deletion is only possible once the file is deleted (e.g., by means of the system Explorer)

Nowhere near to any kind of significant bug, but pretty annoying and curious (as no other extension ever had the same behavior) 😃

Does this issue occur when all extensions are disabled?: Yes
![issue](https://user-images.githubusercontent.com/18613763/80693921-6dee6680-8adc-11ea-8656-9cbe4088e2ba.png)

**Comment by bpasero** [comment]
The JSON files appear under "Recent Workspaces"?
