### ISSUE TITLE
Notebook: copy / paste cell polish

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#96675]
1. Copy a cell
2. Cmd + V to paste a cell only works if the focus is inside the cell. It should work if you have the focus between the cells (still in the notebook)

Also
1. Cmd + C is a shortcut to copy a cell
2. However it has not effect since the editor copy line always ovewrites it

**Comment by rebornix** [comment]
The issue should be gone now in Insiders.

**Comment by cipri-tom** [comment]
I have seen in the default keyboard shortcuts that `c` should copy a cell (without cmd) and `v` should paste it, but this is not working. Is this supposed to work in the stable version? 


```
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

**Comment by rebornix** [comment]
@cipri-tom no, we don't support native notebook yet in Stable.
