### ISSUE TITLE
Editor Hover behind cell border...

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96676]
maybe related to https://github.com/microsoft/vscode/issues/96604

* have a readonly cell
* type
* 🧀 there is z-index issues

<img width="467" alt="Screenshot 2020-04-30 at 12 09 54" src="https://user-images.githubusercontent.com/1794099/80698961-8611b600-8adb-11ea-9a9f-14c84889aa96.png">

**Comment by rebornix** [comment]
yup, it should be set to 50. we need to also validate all content/overlay widgets in Monaco to make sure they have the right z-index.

**Comment by rebornix** [comment]
already fixed.
