### ISSUE TITLE
Use `registerAction2` instead of registerWorkbenchAction

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96672]
We should use [`registerAction2`](https://github.com/microsoft/vscode/blob/7aa60aef945db6ee09bd02ced0c7c2e4d59dec09/src/vs/platform/actions/common/actions.ts#L423) instead of the old action world. Using the new way yield in less code and brings everything (command, keybinding, menus) together in one place. 

You should also revisit the "externalize-to-contants" pattern because that's very heavy on code size (cannot be minified, doubles strings). Similar issue for reference https://github.com/microsoft/vscode/issues/94157

**Comment by JacksonKearl** [comment]
👍for registerAction2. 

As for the constants, is something like https://github.com/microsoft/vscode/commit/920de306db255e016bc16b08a3a868841fabd00a the correct fix? It's not clear to me what the difference here is.

**Comment by jrieken** [comment]
> 👍for registerAction2.

Thanks!

> As for the constants, is something like 920de30 the correct fix? It's not clear to me what the difference here is.

Yeah, that one potential fix. The problems is that once a variable is exported it cannot be minified anymore and that means the 20-or-so characters (bytes) occur over and over again. Local variables are minified, so that definitely helps. This is definitely the game of marginal gains 🤓 

Using `registerAction2` often also helps in a way that extracting the string as constant isn't needed anymore because it is only used once.
