### ISSUE TITLE
Cannot drop view when notebook shows

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96678]
* drag problems view into sidebar
* open a notebook
* drag problems view back into panel
* :bug: not possible
* open a text editor, it works

[Screen Recording 2020-04-30 at 12.14.27.mov.zip](https://github.com/microsoft/vscode/files/4557626/Screen.Recording.2020-04-30.at.12.14.27.mov.zip)

**Comment by roblourens** [comment]
I also can't drop files on top of it to open in an editor.

**Comment by roblourens** [comment]
We just need to disable `pointer-events` on the webview when a drag starts. Maybe all things that do DND can set some global class on body while dragging
