### ISSUE TITLE
Notebook auto save doesn't work with `onFocusChange`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96673]
* use `"files.autoSave": "onFocusChange"`
* edit notebook (source or markdown)
* focus into the debug viewlet (or something else that takes focus without opening another editor)
* :bug: notebook isn't saved

**Comment by jrieken** [comment]
re https://github.com/microsoft/vscode/issues/94052

**Comment by bpasero** [comment]
@rebornix fyi, had to implement `isReadonly` in notebook editor input to return `false`. It took the default impl which is `true` but I think we do not support readonly notebooks currently anyways. Otherwise we need to tweak that method again.
