### ISSUE TITLE
Notebooks: undo/redo bound to active cell only?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96687]
I noticed that Undo/Redo only seems to work in the currently active cell. Shouldn't undo/redo-stack be scoped to the entire notebook and we allow to undo across multiple cells?

I think even things such as reordering cells or creating/deleting cells should contribute to the undo/redo stack.

//cc @jrieken

**Comment by jrieken** [comment]
> I think even things such as reordering cells or creating/deleting cells should contribute to the undo/redo stack.

It does but I believe you cannot be focused inside a code editor when triggering those. Not sure why that is and I agree that it shouldn't be like that

**Comment by rebornix** [comment]
Now the native undo/redo supports both cell changes and cell content change.
