### ISSUE TITLE
Notebook: cursor very close to border

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96682]
Not sure if intentional but the cursor could maybe get a bit of padding to the left?

![Kapture 2020-04-30 at 13 17 31](https://user-images.githubusercontent.com/900690/80704526-038df400-8ae5-11ea-9abc-463c5b401c9b.gif)

**Comment by bpasero** [comment]
Looks a bit unbalanced with the status message:

![image](https://user-images.githubusercontent.com/900690/80704568-1c96a500-8ae5-11ea-9386-2dd6d09faf7e.png)

**Comment by roblourens** [comment]
That would be a bug, I've never seen that. Do you still see it?

**Comment by bpasero** [comment]
I think last I tried it was fine.
