### ISSUE TITLE
Notebooks: dataloss on shutdown when not saving

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96685]
Steps to Reproduce:

1. make notebook dirty
2. close VSCode

=> 🐛 you just lost your data because backup does not seem to be implemented

https://github.com/microsoft/vscode/blob/f00d8903af842c19b09f88db05e76c2ac424078b/src/vs/workbench/contrib/notebook/browser/notebookEditorInput.ts#L221

If you `throw new Error()` at least you will get this UI:

![image](https://user-images.githubusercontent.com/900690/80706216-3ab1d480-8ae8-11ea-8f2b-2d3788820105.png)

Though it fills up the devtools with exceptions...

**Comment by jrieken** [comment]
I like the throwing

**Comment by jrieken** [comment]
I have pushed a change to throw an error and thereby preventing dataloss, removing important and moving to May. To actually and correctly implement this we need to add more API (similar to custom binary editors)
