### ISSUE TITLE
No option to ignore json schema

### ISSUE THREAD

**Issue by CameronNDS** [microsoft/vscode#96683]
Issue Type: <b>Feature Request</b>

Atm if you load a json file that includes a schema, VSCode automatically validates the file against that schema. I'd like the option to ignore schema validation. It's very annoying have debug messages telling you something is wrong when you know that already and there's nothing you can do due to the poor design of the schema.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.0.0

**Comment by aeschli** [comment]
What schema is that and how is it associated to your file?
