### ISSUE TITLE
Unable to open image with URI encoded character in name

### ISSUE THREAD

**Issue by jamesots** [microsoft/vscode#96689]
Issue Type: <b>Bug</b>

If I try to open an image with a name such as 'test-%41.png' it says 'An error occurred while loading the image'.

In the developer console, the following error is shown:
```
Error: Unable to read file '/Users/james.ots/test-A.jpg' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/Users/james.ots/test-A.jpg')
    at e.doReadAsFileStream (fileService.ts:457)
```

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|-psn_0_147492|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by YaAlfred** [comment]
Looks like the problem is on the webviewProtocols.ts, line 22

We got request.url, 
`which is a string 'vscode-resource://file///Users/arturas/Downloads/test%D0%B0%41.jpg?version=1588318675861'`
looks like it is correct,
next, when we do 
`URL.parse(request.url)`
it becomes an object
```
authority: "file"
fragment: ""
path: "///Users/arturas/Downloads/testаA.jpg"
query: "version=1588318675861"
scheme: "vscode-resource"
_formatted: null
_fsPath: null
fsPath: "///Users/arturas/Downloads/testаA.jpg"
__proto__: URI
```
and the paths are not correct here.

**Comment by yume-chan** [comment]
@YaAlfred I don't think the decoding process is faulty, but the encoding part.

Every browser will interpret `test-%40.jpg` as `test-A.jpg`.

![image](https://user-images.githubusercontent.com/1330321/80867527-28da5800-8cc7-11ea-8a60-1d7f870885c9.png)

So the url should escape `%`  in the first place.

![image](https://user-images.githubusercontent.com/1330321/80867554-49a2ad80-8cc7-11ea-8659-77f717072031.png)

**Comment by YaAlfred** [comment]
You're right. The percent ("%") character is missed in the uri.ts encodeTable, and in the encodeURIComponentMinimal() 562 line.
