### ISSUE TITLE
Code Completion sometimes take too long to resolve

### ISSUE THREAD

**Issue by tonyobanon** [microsoft/vscode#96684]
Issue Type: <b>Bug</b>

Code completion now has an issue where it takes longer than expected to resolve. This is a very recent issue that I began noticing, some days ago.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
mustache|daw|1.1.1
vscode-eslint|dba|2.1.5
xml|Dot|2.5.0
gitlens|eam|10.2.1
dotenv|mik|1.0.1
vscode-docker|ms-|1.1.0
LiveServer|rit|5.6.1

</details>

**Comment by alexr00** [comment]
This is probably caused by one of your installed extensions taking a long time to provide the completion. Can you try disabling your installed extensions and see if it still happens?

**Comment by Tyriar** [comment]
@tonyobanon what language are you using?
