### ISSUE TITLE
Command links in settings message don't work

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96680]
re https://github.com/microsoft/vscode/issues/91618

* have message that uses a command link, e.g `Hello [command](command:deleteLeft)`
* this isn't becoming a link

Because of security concerns, command-links must be enabled via the isTrusted-flag. Because these links are from extensions they should be trusted

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/71295
