### ISSUE TITLE
Unable to recognize HTML File

### ISSUE THREAD

**Issue by charanjeet8587** [microsoft/vscode#96692]
Hi Team,

Hope you guy's are doing great.

I want to report an issue with the visual studio code where i am creating a file with the name of index.html but VS code is showing this as an simple folder symbol (But creating HTML file in my suggested location). Moreover on this up to the 3 character while creating the file (Index.HTML) it showing HTML Symbol fine but when i typing last letter of the file (HTML) it is not recognizing as a HTML file also my browser is showing Template issue while running this file.

I am new user and learning codes and might be i am doing something wrong here and issue also looks very uncommon.

Please help and thanks in advance.

Regards,
Charanjeet [Singh[](url)](url)

**Comment by isidorn** [comment]
Hi, thanks we are doing good. Hope you are also good.
Thanks for filling this issue. I can not reproduce this. 
Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by charanjeet8587** [comment]
Hi Isidorn,
VS code via this link is working perfectly fine. Thanks for response. 
Have a lovely weekend ahead. Be safe.

**Comment by isidorn** [comment]
Glad to hear, thus closing this.
