### ISSUE TITLE
Variable paging: support object properties for arrays

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#9670]
I've added protocol support for Variables and the variablesRequest to distinguish between indexed and named properties of an object. This makes it possible to show both types of properties like in this example:

![2016-07-24_23-59-07](https://cloud.githubusercontent.com/assets/1898161/17086753/b2989d06-51fa-11e6-90e8-98be0fded40d.png)

The API works as follows:

- a Variable optionally returns an `indexVariables` and/or a `namedVariables` property.
- the `indexVariables` works like 'totalCount' before.
- an `namedVariables` indicates that the variable has 'named' properties (in addition to 'indexed' properties). In this case the frontend is expected to request both the 'named' properties and the 'indexed' properties. The 'named' properties are requested through the variableRequest with a filter attribute 'named'.

**Comment by isidorn** [comment]
From how the protocol is designed I see that the named properties should also support paging? If yes, how should the UI distinguish between chunks of named and chunks of indexed variables if an object has 100+ named and 100+ indexed variables?
Currently we show the indexed with `0..99:`

**Comment by weinand** [comment]
@isidorn the UI could use 'a'-'z' for the top level nodes. However, I don't think that we have to support paging for now. Showing always all named properties is fine for now.
The typical use case for named properties is an array that always has a single `length` property.
