### ISSUE TITLE
Signature help selection changes while typing

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#96702]
Noticed this while verifying #94834

```ts
declare function foo(a: number, b: 'abc'): void;
declare function foo(a: number, c: 'xyz'): void;

foo()
```

- Trigger signature help in foo
- Switch to 2/2
- Start typing a number, type quickly
- Sometimes it will switch back to 1/2, seems to happen randomly

![Apr-30-2020 09-46-21](https://user-images.githubusercontent.com/323878/80724570-9f106c00-8ac7-11ea-8a76-d4baa081ff26.gif)

**Comment by mjbvz** [comment]
Just tested this again in an empty project but could not reproduce. @roblourens Let me know if you still see this. If so, what project were you in?

**Comment by mjbvz** [comment]
Actually I can still see this after really mashing away at the number pad, but not commonly. Taking a quick look
