### ISSUE TITLE
Reloading the window is not retaining the cells positions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#96709]
#96279

![Kapture 2020-04-30 at 17 24 19](https://user-images.githubusercontent.com/10746682/80728778-9c356b80-8b07-11ea-847e-ab6e1caccf46.gif)

**Comment by roblourens** [comment]
Guessing this is just another instance of the bug with not saving the content

**Comment by rebornix** [comment]
right, the code cell (second cell in the UI) is gone after reload, even though the editor has no dirty indicator any more.

This should already be fixed in master.
