### ISSUE TITLE
all extenstions are disabled temprarorily error

### ISSUE THREAD

**Issue by Goutampatidar** [microsoft/vscode#96705]
Issue Type: <b>Bug</b>

all extenstions are disabled temprarorily error

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:33:57.013Z)
OS version: Windows_NT ia32 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (1.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you have a screenshot? Are you sure you haven't loaded VS Code with extensions disabled using `>Developer: Reload Window With Extensions Disabled` or `--disable-extensions` CLI flag?

**Comment by Goutampatidar** [comment]
It's showing that all extension are disabled temperorily

**Comment by sandy081** [comment]
Can you please provide the screenshot of the message you are seeing?

**Comment by Goutampatidar** [comment]
Yes

**Comment by sandy081** [comment]
Just FYI I do not see a screenshot yet
