### ISSUE TITLE
Cannot navigate problems across cells

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#96708]
Testing  #96279

- Have two GitHub issues cells that has problems
- Open marker peek in one of the cells
- Use navigation (up and down) arrows in the peek
🐛 This navigates only in the cell

![Kapture 2020-04-30 at 16 31 55](https://user-images.githubusercontent.com/10746682/80722900-30033980-8b00-11ea-814b-dcad1fded93d.gif)

**Comment by jrieken** [comment]
Sorry - you own this feature 🙊

**Comment by sandy081** [comment]
Yup and it is scoped to single text document just like outline. Seems this also needs adopted for Notebooks.

**Comment by jrieken** [comment]
Yeah - this is actually more interesting and we have to see how we make this work...

**Comment by rebornix** [comment]
For problem navigation, or any other similar features, previously we always build two actions/commands:

* navigate in current document
* navigate in workspace

Now with composite editors concept, we need an action which allows you navigate in the composite editors. IMHO we need to introduce this concept into all language features in a generic way.
