### ISSUE TITLE
Stopping a session from call stack actions view always goes to the active session

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#96713]
```
Version: 1.45.0-insider (user setup)
Commit: a0fe37870c42e0704a492cdc6b8550b4cf23f63c
Date: 2020-04-30T05:39:08.281Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

Steps to Reproduce:

1. Have two launch configs running, A and B
2. Select launch config A from the call stack view
3. Click stop/disconnect on config B
4. Config A exits

Recording: https://memes.peet.io/img/20-04-08083092-2b69-4405-9d53-93cf511622ec.webm

**Comment by isidorn** [comment]
I can not reproduce this with just a simple example. Here are my steps.
Have the following program and have two launch configs which break on it
```
debugger;
console.log('hello connor')
```

Click stop on an unfocused one -> the correct one gets stopped.
In case you want to investiate more. Put a breakpoint [here](https://github.com/microsoft/vscode/blob/bddccf854580a3c6eac972233dcd969a05b9a35f/src/vs/workbench/contrib/debug/browser/debugCommands.ts#L284) and checkout what is the context and on which Session the `disconnect` gets sent.

![recording (1)](https://user-images.githubusercontent.com/1926584/80968055-9e553e00-8e17-11ea-87dc-a2c22ce598a6.gif)

**Comment by connor4312** [comment]
Looking into it some more, this seems to happen _only_ with attach. I can easily reproduce it with two launch configs like:

```js
    {
      "type": "pwa-node",
      "request": "attach",
      "trace": true,
      "name": "[Node] Attach to program",
      "port": 9229
    },
    {
      "type": "pwa-node",
      "request": "attach",
      "trace": true,
      "name": "[Node] Attach to program2",
      "port": 9229
    },
```

**Comment by isidorn** [comment]
@connor4312 thanks for providing more details. Yes the `disconnect` command was not respecting the context passed properly. I have pushed a fix.
