### ISSUE TITLE
Sync "remote backup" is empty

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#96717]
![Apr-30-2020 12-10-13](https://user-images.githubusercontent.com/323878/80739142-9164e180-8adb-11ea-9cce-8d82a9dec146.gif)

I'm not sure what this is supposed to show, but if the groups are empty, I should still be able to expand them. The expand/collapse flicker makes it look broken.

**Comment by sandy081** [comment]
Can you please check the network requests in the shared process if the requests are failing?

**Comment by roblourens** [comment]
Sorry, it works today, I'll check if I see this again
