### ISSUE TITLE
Resolve relative paths in terminal link handler

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#96715]
You could resolve these so it would search for the right file. Or do you not want to make assumptions about the format of the thing?

![image](https://user-images.githubusercontent.com/323878/80738201-3d0d3200-8ada-11ea-83e8-ba4f70d355c5.png)

![image](https://user-images.githubusercontent.com/323878/80738213-439ba980-8ada-11ea-8fe0-0396ea9e31a8.png)

**Comment by Tyriar** [comment]
I don't really want to make assumptions for the Search Workspace one, did these not come up as validated links because package.json isn't in the workspace root?

**Comment by Tyriar** [comment]
Started a discussion in https://github.com/microsoft/vscode/issues/96722, if that's no good I can just normalize the path which isn't super smart but it will find results.

**Comment by Tyriar** [comment]
Open to PRs, more detailed repro in https://github.com/microsoft/vscode/issues/96722#issue-610279693

**Comment by vibhavsarraf** [comment]
I would like to work on this issue. We only want to normalize the path in the filter string, right? So:
./package.json -> package.json
a/../b/./c -> b/c

**Comment by Tyriar** [comment]
@vibhavsarraf yes, but just for the [TerminalWordLinkProvider](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/terminal/browser/links/terminalWordLinkProvider.ts)

**Comment by vibhavsarraf** [comment]
@Tyriar I have raised a PR for this issue. Please review it.
