### ISSUE TITLE
Show full vscode URI when asking to open

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#96710]
This prompt isn't that helpful, if you are going to ask me whether it's ok to open a URI, I need to see what the URI is. It could be a tooltip on the truncated form. Also the truncated form could be longer.

![image](https://user-images.githubusercontent.com/323878/80731395-7640a480-8ad0-11ea-8d78-72652aabb3c4.png)

**Comment by joaomoreno** [comment]
The URL is cropped now because https://github.com/microsoft/vscode/issues/66628

Do you have a suggestion?

**Comment by roblourens** [comment]
Tooltip? Or show the full URI path and only truncate the query?

**Comment by joaomoreno** [comment]
We can't show tool tip on VS Code, since that uses a modal popup, which is native. Your screenshot shows web, right?

Well, even if we only truncate the query, it could be that it's the query that contains `?andPleaseStealCreditCard=1`.

**Comment by roblourens** [comment]
No I'm using desktop vscode. That's ok if there isn't really anything we can do.
