### ISSUE TITLE
Support searching and validating unnormalized paths in quick access

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#96722]
Context: https://github.com/microsoft/vscode/issues/96715

Terminal programs sometimes output relative files like `x/../file`, currently clicking on a "search workspace" link will find nothing:

![image](https://user-images.githubusercontent.com/2193314/80743431-c8ce9080-8ad1-11ea-802d-96b0fd9fc3fa.png)

If the quick access understood this syntax there would be exactly one match here:

![image](https://user-images.githubusercontent.com/2193314/80742608-83f62a00-8ad0-11ea-81d9-99f0f8c1d3b9.png)

**So the feature request is**, if the search string contains a folder `../`, can we use that information to filter the results such that the folder structure is ensured? In the example this would require a sibling folder `browser/` to exist next to any result (the initial `./` can be trimmed off on my end).

A compromise is to normalize the path as suggested in https://github.com/microsoft/vscode/issues/96715, but then the folder information would not get respected and the results aren't as expected either:

![image](https://user-images.githubusercontent.com/2193314/80743525-f74c6b80-8ad1-11ea-8ac4-b95a8c1a8492.png)

I could also normalize the path and then validate it inside the terminal component to open the file if there is exactly one, it seems to be a generally useful feature to make quick access smarter though.

**Comment by bpasero** [comment]
I am not sure how to do this, needs support from RipGrep to search these kind of paths. Moving to Rob to see if that is feasable. I think the only solution is to call `path.normalize` on the input if it contains `..` maybe.

**Comment by roblourens** [comment]
Ripgrep won't be able to help here.

> In the example this would require a sibling folder browser/ to exist next to any result

I hadn't thought of taking it that far, I figured it would just resolve to any "tsconfig.json" but I would imagine having something sort of like our excludes with "when" clauses to check the filesystem around a match before returning it.

**Comment by Tyriar** [comment]
If this seems like too much and ripgrep can't support this sort of thing then that's fine we can just normalize. The question is should we normalize on the terminal end or quick access? From my perspective it would be nice for the terminal to hand off the exact search string to quick access and have it figure it out by normalizing, provided there aren't any foreseen problems with normalizing there.

**Comment by roblourens** [comment]
I should mention that I don't have a real scenario for `foo/../bar`, I made that case up when I saw the `./foo` issue. The terminal knows what the terminal's cwd is, right? So it could resolve `./` to that folder.

**Comment by Tyriar** [comment]
> The terminal knows what the terminal's cwd is, right?

Relative links are only resolved to the initial cwd. The terminal can know about the cwd on mac and linux but that is only used when splitting right now, would need to come up with a polling strategy otherwise. There is also the issue of folders being active only applying to a particular chunk of the buffer. The new links to search quick access make this much less of a problem though.

**Comment by bpasero** [comment]
Is this actionable still?

**Comment by Tyriar** [comment]
@bpasero how about calling resolve on the path, maybe only if it contains `..`? The alternative is that I do this in the terminal link handler (https://github.com/microsoft/vscode/issues/96715#issuecomment-622012892), seems generally useful for the quick access though.

**Comment by bpasero** [comment]
@Tyriar I am not sure this ever happens outside your scenario, I mean a user would likely not type this. So I suggest you normalize.
