### ISSUE TITLE
Intellisense for sass modules not working

### ISSUE THREAD

**Issue by milottit** [microsoft/vscode#96723]
- VSCode Version:
```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:50:03.709Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-96-generic
```
- OS Version:  Linux x64 4.15.0-96-generic -> Ubuntu 18.04

Steps to Reproduce:

1. Write a scss file in a folder as:
```scss
@use "sass:color";

$primary-color: #6b717f;

$c1: color.scale($primary-color, $lightness: 20%);
$c2: color.s();
$c3: color.; // Tap Ctrl-Space to trigger intellisense 
```
![image](https://user-images.githubusercontent.com/8853905/80748604-75862d80-8b25-11ea-9e3a-34e52bea9730.png)

Here you can notice that code completion is not working.
The @use directive is working though.

That issue [SASS Modules (@forward and @use) #81943](https://github.com/microsoft/vscode/issues/81943#issuecomment-558865889) enable syntax highlighting and language server support for SCSS modules. But apparently not code completion and validation.

Apparently vscode-css-languageservice supports Sass Module but I have impression reading the vscode-scss extension code, that nothing has been done to enable code completion and validation. It would be a nice feature to add.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
VSCode's scss support is single file, and does not resolve any imports.
There are extensions that provide that: https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-scss

We have https://github.com/microsoft/vscode/issues/47331 as issue to go cross file.
