### ISSUE TITLE
odd behavior when editing command in internal console

### ISSUE THREAD

**Issue by localvar** [Microsoft/vscode#9672]
- VSCode Version: 1.3.1
- OS Version: Windows 10 professional (64bit)

Steps to Reproduce:

1.  set the shell of internal console to git bash: `"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"`
2. enter a command like `abcd efgh hijk mnop`, but don't hit `enter` to execute it
3. use `left` and `right` arrow keys to move the cursor (repeat several times)
4. the command becomes something like `abccd efgh hijk mnop`

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/7345
