### ISSUE TITLE
Problems filter focus outline is cut off when sharing a panel

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#96726]
Top and bottom outline is getting clipped

![image](https://user-images.githubusercontent.com/2193314/80745824-bc4c3700-8ad5-11ea-91f9-084e0efe3800.png)

**Comment by sbatten** [comment]
To Verify:
1. Use a theme that has borders such as high contrast theme
2. With Problems in its default position, focus the filter box and make sure the borders look right without clipping
3. Move Problems inside another panel and focus the filter box and make sure the borders look right without clipping
