### ISSUE TITLE
VSC in macOS 10.12 does not display as Retina

### ISSUE THREAD

**Issue by Rombus** [Microsoft/vscode#9673]
- VSCode Version: 1.3.1
- OS Version: 10.12 Beta (16A254g)

Steps to Reproduce:

1. Fresh install of VSC on 10.12 Public Beta 2
2. Launch App

App does not display in Retina and looks fuzzy.

**Comment by bpasero** [comment]
Can you attach a screenshot?

@weinand have you seen this before on 10.12 Beta?

**Comment by weinand** [comment]
@bpasero I didn't notice anything special when trying VSC on Sierra. But try yourself, the MBP with Sierra is in the office (and I'm on vacation...).

**Comment by Rombus** [comment]
Screenshots are attached. This is happening in both Public Beta 2 and Public Beta 3. The first screen shot shows PB2 and VSC 1.3, and the second screenshot shows PB3 and VSC 1.4. Unfortunately VCS updated after I updated to PB3. I put TextEdit windows and the system info panels on both screenshots. I'm starting to think this might be a change in the way macOS handles determining if an app is retina or not, but I haven't been able to dig deep into it. 

![serria pb2](https://cloud.githubusercontent.com/assets/550610/17446474/0fa10caa-5b0f-11e6-8954-d55e53c39459.png)
![serria pb3](https://cloud.githubusercontent.com/assets/550610/17446476/1325d338-5b0f-11e6-943b-5fb2017d3025.png)

**Comment by Rombus** [comment]
I tried doing a build from source ([from these directions ](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source)) using NodeJS 6.3.1 and the build was successful and runs in 2x Retina mode. I'm very new to working on projects like VCS, so if you need any info from me let me know whats needed and I'll do what I can to provide the info. Attached is a screenshot showing VSC running in Electron with the build terminal, macOS version and an example TextEdit window

<img width="1440" alt="build from source" src="https://cloud.githubusercontent.com/assets/550610/17467548/f45fe2f4-5ce4-11e6-88c1-e2ad7d5d92b4.png">

**Comment by bpasero** [comment]
@Rombus are you saying when you run out of sources the issue does not show?

**Comment by bpasero** [comment]
We are also on a old Electron version and we should revisit this when we update (Chrome 49 => Chrome 52).

**Comment by Rombus** [comment]
@bpasero That's correct, running from source the issue does not show.

**Comment by bpasero** [comment]
This might be related (fixed in Chrome 52): https://bugs.chromium.org/p/chromium/issues/detail?id=619981

**Comment by bpasero** [comment]
@rombus we just released a new insiders build with a newer Electron. maybe you could give that build a try to see if it fixes this issue.

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by Rombus** [comment]
I can confirm the following using macOS Sierra 10.12 GM Release: 
VSC 1.4.0 - Same problem as stated above
VSC 1.5.2 - Same problem as stated above
VSC 1.6.0-insider - It displays properly in HiDPI mode and looks great

**Comment by bpasero** [comment]
Great, thanks.

**Comment by bpasero** [comment]
Fixed with the electron update.
