### ISSUE TITLE
Lost "reset view location" context menu item

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#96736]
Dragging and reording things, and I don't see that item on the terminal now, but I think it should be there right?

![image](https://user-images.githubusercontent.com/323878/80761509-545f1600-8b00-11ea-96d3-741297c15acf.png)

**Comment by roblourens** [comment]
I think that's only when it's inside another container?

**Comment by sbatten** [comment]
yea, since you can move view containers now, this isn't considered moved. there is a separate issue for allowing to reset view containers to their default locations.
