### ISSUE TITLE
Add setting to specify shellArgs for the automationShell

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode#96732]
We can set a separate shell for tasks/debug (using `terminal.integrated.automationShell.windows`) which is a useful feature, but there doesn't seem to be a way to specify shellArgs for the automationShell (and only the automationShell), aka a setting like "terminal.integrated.automationShell.shellArgs.windows"

> NOTE: This is related to https://github.com/microsoft/vscode/issues/90073, but that discusses existing behavior about the current shellArgs setting being ignored. I have no problem with that behavior, I'm asking for a _new feature_ to specify automation-specific shellArgs

As background, I work on the Azure Functions extension and we've had several users reports problems while debugging because they like to use `Set-Location` in their PowerShell profile (Personally I wouldn't do that, but 🤷‍♂️). However, that breaks tasks/debug because the PowerShell profile changes the cwd to the wrong folder. If there was a setting `terminal.integrated.automationShell.shellArgs.windows`, they could add `-NoProfile` as an arg specific to the automation shell and keep `Set-Location` in their profile for non-automation scenarios.

Original issues on the Functions extension: https://github.com/microsoft/vscode-azurefunctions/issues/1175, https://github.com/microsoft/vscode-azurefunctions/issues/1260, https://github.com/Azure/azure-functions-core-tools/issues/1945

**Comment by ezpuzz** [comment]
In PowerShell I have a default profile with a custom prompt and other customizations. I would like to use `-NoProfile` only when running automation tasks because these customizations have an impact on terminal startup time.

**Comment by LuanVSO** [comment]
this would work like a charm for using msys2 to compile code without adding it to the windows path

**Comment by polyclash** [comment]
We need to set the shell args to run specific msys2 bash debug.
upvoted this.

**Comment by thorn0** [comment]
Another reason why this setting is needed: https://github.com/microsoft/vscode/issues/63156#issuecomment-822027307

**Comment by Tyriar** [comment]
Note that shell/shellArgs are deprecated, when we add this we will want it to be `automationProfile.<platform>` and also support `icon` and `env`.

**Comment by alumni** [comment]
One more thing, after the addition of shell profiles. Currently I have the following setting:
```json
"terminal.integrated.defaultProfile.windows": "Git Bash",
```
However, NPM scripts are still running with PowerShell. I'm looking forward for this `automationProfile` to be added, but it would also be nice if `defaultProfile` would work if `automationProfile` is not set.

**Comment by marhoy** [comment]
> Note that shell/shellArgs are deprecated, when we add this we will want it to be `automationProfile.<platform>` and also support `icon` and `env`.

When will the `terminal.integrated.automationProfile.<platform>` be available?
I'm very much looking forward to this, as I want to run `zsh --login`, as I do for the `defaultProfile`.
I'm on version 1.56.2.
