### ISSUE TITLE
Remote Explorer SSH Targets periodically empty

### ISSUE THREAD

**Issue by john-aws** [microsoft/vscode#96737]
- VSCode Version: 1.44.2
- OS Version: OS X 10.14.6

Steps to Reproduce:

1. use VS Code for a while (do not use Remote Explorer)
2. choose the Remote Explorer pane
3. the SSH Targets list is sometimes empty

My system has numerous SSH targets configured in ~/.ssh/config. Sometimes VS Code will show these targets, sometimes it will not. There is no obvious reason when it fails to show them and there is no indication of errors in the UI. Quitting VS Code and restarting it seems to correct this and the list is immediately populated. This may not be trivial to reproduce.

Does this issue occur when all extensions are disabled?: Not tested

**Comment by roblourens** [comment]
Hm, no idea. Next time this happens you could check whether there are errors in the developer tools console (Help > Toggle Developer Tools) or, see if clicking the "refresh" icon in that panel fixes it.
