### ISSUE TITLE
Can't change theme when opening Jupyter notebook

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/vscode#96738]
- VSCode Version: 1.44.2
- OS Version: Windows 8.1 / Windows 10 /Ubuntu

Steps to Reproduce:

0. Install the Microsoft Python plugin to get Jupyter support.
1. Open whatever Jupyter notebook
2. Use "ctrl+shift+p" and type "theme" to change theme, the command menu just disappears.
Need to open up a new window and do the same thing to change the theme. 

EDIT: Just discovered that it behaves the same under Ubuntu too.

Does this issue occur when all extensions are disabled?: No

**Comment by rebornix** [comment]
This feature is provided by the Python extension now so please file issues against them.
