### ISSUE TITLE
Add setting to show breadcrumbs on inactive editors when tabs are not shown

### ISSUE THREAD

**Issue by pappy74** [microsoft/vscode#96744]
Currently, if you turn tabs off, breadcrumbs only show up on the "active" editor. 

https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/noTabsTitleControl.ts#L239

I understand why you might want that as the default, but I would like them to always appear (I get a lot of value over having that context always-visible).

Could you add a setting to change that behavior?

**Comment by jrieken** [comment]
@bpasero fyi - such a setting should probably also apply when not showing breadcrumbs the the path only

**Comment by pappy74** [comment]
FWIW, I patched in a change to always show the breadcrumbs, and my opinion has changed... this *should* be the default... it's lovely :)

But I leave that particular decision to y'all.

**Comment by pappy74** [comment]
I'm curious. Do the rules change if I'm willing to send a patch?
