### ISSUE TITLE
Allow Line Numbers in Notebook Cells

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#96742]
Issue Type: <b>Feature Request</b>

Notebook cells markdown in edit mode and code cells should allow line numbers. I enabled word wrap and it was difficult to discern lines.

VS Code version: Code - Insiders 1.45.0-insider (a0fe37870c42e0704a492cdc6b8550b4cf23f63c, 2020-04-30T05:39:08.281Z)
OS version: Windows_NT x64 10.0.19041

**Comment by rebornix** [comment]
I'm wondering if we should introduce quick actions in the toolbar for switching notebook line numbers. For ppl who are using word wrap, the editor looks wrong without line numbers. @misolori what do you think?

**Comment by misolori** [comment]
@rebornix yea i think we can surface this via the ellipsis in the toolbar. We did originally design these options:

![image](https://user-images.githubusercontent.com/35271042/81109649-3eba6980-8ecf-11ea-8732-56f6fa9e9904.png)

**Comment by rchiodo** [comment]
I assume all of these would be mapped to commands? I'm asking because Jupyter has keyboard shortcuts for each of these.

**Comment by rebornix** [comment]
Let's track it in https://github.com/microsoft/vscode/issues/106054.
