### ISSUE TITLE
Terminal faded font doesn't render

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#96749]
Trying out zsh autosuggest and in Terminal.app and Hyper I get nice lightening of the suggest text, but in vscode that isn't present. 

![image](https://user-images.githubusercontent.com/8586769/80774564-42866e80-8b12-11ea-9c6e-24c62f983ef0.png)

**Comment by Tyriar** [comment]
It's probably your theme, can you check another?

**Comment by JacksonKearl** [comment]
👍
`"terminal.ansiBrightBlack": "#747474",` did it.
