### ISSUE TITLE
Terminal: environment variables hover text covered by scrollbar

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#96740]
Issue Type: <b>Bug</b>

<img width="727" alt="image" src="https://user-images.githubusercontent.com/876920/80766457-56be7180-8afa-11ea-995b-6766f5d354c1.png">

The text in the hover is covered by the horizontal bar.

VS Code version: Code - Insiders 1.45.0-insider (a0fe37870c42e0704a492cdc6b8550b4cf23f63c, 2020-04-30T05:36:26.465Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.23GB free)|
|Process Argv|-psn_0_28097226|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
gitlens|eam|10.2.1
tsl-problem-matcher|eam|0.1.1
vscode-pull-request-github-insiders|Git|2020.4.42661
vscode-docker|ms-|1.1.0
vscode-language-pack-zh-hans|MS-|1.45.0
remote-containers|ms-|0.114.0
remote-ssh-edit-nightly|ms-|2020.4.9540
remote-ssh-nightly|ms-|2020.4.9540
js-debug-nightly|ms-|2020.4.2517
powershell|ms-|2020.4.0
vscode-github-issue-notebooks|ms-|0.0.18
debugger-for-chrome|msj|4.12.6
kuskus-extensions-pack|ros|1.0.1
kuskus-kusto-language-server|ros|1.0.1
kuskus-kusto-syntax-highlighting|ros|1.1.8
sourcekit-lsp|unp|0.0.1

(4 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
I'm not sure we can add padding conditionally to a `DomScrollableElement` only if there is a scroll bar? I don't want it to have uneven padding when there is no scroll bar.
