### ISSUE TITLE
Breadcrumb picker typed text foreground/background/border settings

### ISSUE THREAD

**Issue by jx22** [microsoft/vscode#96752]
Issue Type: <b>Feature Request</b>

While one can customize the appearance of the foreground and background of entries that appear in the breadcrumb picker, the box that pops up to show text as one starts typing cannot be similarly customized as far as I can tell. Typed text can sometimes be hard to read because of poor color contrast. I imagine new settings that are similar in effect to editorWidget.foreground, editorWidget.background and editorWidget.border for the Find/Replace widget. Alternatively, these elements could be mapped to existing foreground, background and border settings.

![image](https://user-images.githubusercontent.com/14957748/80778710-22f54300-8b1e-11ea-8d95-547a380b9ae7.png)

VS Code version: Code - Insiders 1.45.0-insider (a0fe37870c42e0704a492cdc6b8550b4cf23f63c, 2020-04-30T05:39:08.281Z)
OS version: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
Colors are:

- `listFilterWidget.background`
- `listFilterWidget.outline`
- `listFilterWidget.noMatchesOutline`
- `list.filterMatchBackground`
- `list.filterMatchBorder`

**Comment by jx22** [comment]
Oh, awesome! Thanks, @joaomoreno !
