### ISSUE TITLE
Sidebar Open Editors panel should open OVER the folder panel to prevent unexpected double click behaviour

### ISSUE THREAD

**Issue by SteveMcArthur** [microsoft/vscode#96759]
- VSCode Version: 1.44.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open a file by clicking on it in the sidebar folder panel. This causes the file to appear in the Open Editors panel which expands Open Editor panel and pushes the folder panel down.
2. Now open a file by double clicking a file. The first click opens your file which pushes the folder panel down so that the second click hits the file above the first and opens it.

The behaviour of the Open Editors panel is different from the other two panels at the bottom. The Outline and Timeline panels at the bottom open "over" the folder panel. So the folder panel is not resized. The Open Editor panel should do the same. 

The problem makes it look like the wrong file is opening, since the second click opens a different file and makes it active. This had me confused for while until I worked out what was happening.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/93662
