### ISSUE TITLE
"vscode.openWith" doesn't seem to play nice with "workbench.editorAssociations" setting

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#96751]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Have the following setting:
```json
"workbench.editorAssociations": [
{
    "viewType": "default",
    "filenamePattern": "*.ps1"
}
],
```
2. open a (in this case ps1) file in a different viewType like `PowerShellNotebookMode` (using the editor command "Files -> Open with...")
3. try running:
```
await vscode.commands.executeCommand("vscode.openWith", vscode.notebook.activeNotebookDocument.uri, "default");
```
or
```
vscode.commands.executeCommand('vscode.openWith', vscode.notebook.activeNotebookEditor!.document.uri, 'default')
```

Nothing happens. Nothing shows up in dev tools or anywhere. Going _too_ `PowerShellNotebookMode` works... but not going to `default.

For some reason... "Files -> Open with..." picking the default editor works... but not via the API (`vscode.openWith`)

cc @rebornix @mattbierner

**Comment by rebornix** [comment]
No longer reproduce in latest Insiders.
