### ISSUE TITLE
breadcrumb picker typed text should behave like other input boxes

### ISSUE THREAD

**Issue by jx22** [microsoft/vscode#96753]
Issue Type: <b>Feature Request</b>

When one starts typing while viewing the breadcrumb picker for a file, the picker does filter as one types and/or highlight matches, as it should. However, it does not seem to be possible to click at a specific place in the input box for the breadcrumb picker or move the cursor around with arrow keys, or select all that you have entered and then copy or cut or paste. These behaviors are available in the Find/Replace widget, the Command Palette, Search and the editor. Clicking in the field where one has typed or hitting the arrow keys to move around has no effect. It would be nice to have the same capabilities one finds in other text boxes in this one.

![image](https://user-images.githubusercontent.com/14957748/80779019-36ed7480-8b1f-11ea-8556-3bb1c74c87a3.png)

VS Code version: Code - Insiders 1.45.0-insider (a0fe37870c42e0704a492cdc6b8550b4cf23f63c, 2020-04-30T05:39:08.281Z)
OS version: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/70646
