### ISSUE TITLE
Extra 'e' When Hovering Over Struct

### ISSUE THREAD

**Issue by Miserlou** [microsoft/vscode#96760]
- VSCode Version: 1.44.2
- OS Version: OSX

Steps to Reproduce:

1. Hover over a certain class name
2. It has an extra e.
<img width="454" alt="Screen Shot 2020-05-01 at 12 40 53 AM" src="https://user-images.githubusercontent.com/139987/80782543-9d38be00-8b44-11ea-90d8-5542b806d141.png">

I don't understand this. It's only this class.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Miserlou** [comment]
Notice that the hover says 'NeedleDisplaye' but the struct is 'NeedleDisplay'.

**Comment by Miserlou** [comment]
I closed the tab and reopened it and the bug went away.

While in the error condition, it generated a hover-error in the constructor that also went away.

**Comment by alexr00** [comment]
What language is that? C++?

**Comment by Miserlou** [comment]
Yes, C++.

**Comment by alexr00** [comment]
Can you provide a copy/pasteable example?

**Comment by Miserlou** [comment]
Not really. I can't reliably reproduce this. It just happened and I can't explain it.

**Comment by alexr00** [comment]
There shouldn't be any hover there at all if you don't have an extension to provide it installed. Are you sure you have all extensions disabled?

**Comment by Tyriar** [comment]
Please report this to https://github.com/microsoft/vscode-cpptools
