### ISSUE TITLE
[JS] Suggestion on import file and go To File for CSS (also sass & less)

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [microsoft/vscode#96762]
Directory and file suggestion on importing a css / sass / less file is a good feature which VS Code is missing that.
Also Go to file or Go To Reference feature which add an ability to alt + click on file import to open the file.

Note: These features already implemented for JS files, But does not applied to CSS files, for example when you try to import a CSS file there is not any file suggestion and also after import you can not alt + click to open the CSS file.

**Comment by AmirHosseinKarimi** [comment]
Also I can produce this problem apply on importing image or other files except .js

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/microsoft/TypeScript/issues/15146
