### ISSUE TITLE
When deserializeWebviewPanel fails, we should be able to display an error message in a better way

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#96761]
When we can not restore `Webview` with `WebviewPanelSerializer.deserializeWebviewPanel`, we should be able to display an error message on each `Webview`, or in other much better ways.

Typically, when files we wanted to preview on `Webview` have been removed, we cannot restore the `Webview`. In those cases,  the current API gives extension authors no way to tell users what went wrong. Although the authors can use `showErrorMessage` or `showInformationMessage`, it does not seem an appropriate way when multiple restoring fails at the same time. We should be able to tell users what went wrong on each `Webview`.

Since restoring Notebook, #95361, would easily fail, extension authors of Notebook would need this feature.

**Comment by mjbvz** [comment]
Can you explain what problem you are running into and the use case for this proposal?

Webviews are already free to show their own error message if they cannot restore themselves properly (such as if the file they were previewing no longer exists). However VS Code will show a generic error message if the webview throws an uncaught exception while restoring a webview

**Comment by tamuratak** [comment]
I missed that we could use `Webview` itself to display error messages. 

`WebviewPanelSerializer.deserializeWebviewPanel` really works well. Thank you.
