### ISSUE TITLE
Path with whitespace have no terminal link

### ISSUE THREAD

**Issue by github0null** [microsoft/vscode#96765]
- VSCode Version: 1.41.1
- OS Version: windows 10 

Steps to Reproduce:

1. input a path with whitespace, but have no underline to jump
2. Here are some screenshots
![test](https://user-images.githubusercontent.com/43022536/80791464-4d014080-8bc4-11ea-828a-feee77631186.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Please start by updating from 1.41.1 to the latest version, 1.44.2. Even better, install Insiders from https://code.visualstudio.com/insiders/ so you can try the nightly builds. This can coexist with the regular version.

Also please clarify what part of VS Code your screenshots come from.

**Comment by github0null** [comment]
This screenshot is from the output of the terminal.

When the mouse hovers over a path, the path becomes a clickable link, but when there is a space in the path, the link does not appear.

I have updated to 1.44.2, but the problem still exists.

![test](https://user-images.githubusercontent.com/43022536/80803076-cb210f80-8be3-11ea-9542-d8557277525b.png)

**Comment by gjsjohnmurray** [comment]
Thanks @github0null. This looks like a duplicate of #21125 and though that one was opened a long time ago there's been some recent activity that looks promising.

**Comment by github0null** [comment]
Thanks, while this problem may seem trivial, it can sometimes be very frustrating, and sometimes it is inevitable that there will be whitespaces in the path.
