### ISSUE TITLE
vscode frequently crashes on macOs

### ISSUE THREAD

**Issue by maziac** [microsoft/vscode#96769]
- VSCode Version: 1.44.2
- OS Version: macOS, Darwin x64 19.4.0

There is no exact way to reproduce this. It happens during development of a vscode extension.
I.e. vscode starts another vscode window at which the extension is running.
I normally can run the extension a little bit but suddenly I get a crash at "crmainbrowser".

I attached the crash file.
[vscode1.44.2_crash_on_mac.txt](https://github.com/microsoft/vscode/files/4563475/vscode1.44.2_crash_on_mac.txt)

**Comment by maziac** [comment]
From what I can see this is not related to #94932.

**Comment by deepak1556** [comment]
Is this still an issue with latest insiders https://code.visualstudio.com/insiders

**Comment by maziac** [comment]
Haven't seen it anymore.

**Comment by deepak1556** [comment]
thanks for confirming!
