### ISSUE TITLE
Provide alt-click in Source Control view

### ISSUE THREAD

**Issue by niccolomineo** [microsoft/vscode#96764]
It could be useful to have ALT + click bound to opening the file when clicking on it in Source Control.

**Comment by alexr00** [comment]
You can create your own keyboard shortcuts https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by niccolomineo** [comment]
It is not really the same thing. What I am asking is not to consider binding two keys to an action, but rather to do bind them to a specific UI element (the file in the Source Control).

**Comment by alexr00** [comment]
@alexdima this looks like a feature request to be able to include `click` as one of the keys in keyboard shortcuts.

@joaomoreno is there a context already for source control file list items?

**Comment by joaomoreno** [comment]
The only way we could do this would be to introduce an alternative command to the SCM API, which I am not a big fan of...
