### ISSUE TITLE
Interactive window prompt placeholder does not disappear when going through previous commands 

### ISSUE THREAD

**Issue by ldorigo** [microsoft/vscode#96773]
Issue Type: <b>Bug</b>

When pressing the 'up' key to go through previous inputs in the python interactive window prompt, the plaeholder text (sometimes?) doesn't disappear, resulting in overlayed text:

![image](https://user-images.githubusercontent.com/8631181/80808998-170e8d00-8bc1-11ea-9c4d-a2231b7236ae.png)

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.12.0
ng-template|Ang|0.901.4
gitignore|cod|0.6.0
vscode-eslint|dba|2.1.5
vscode-html-css|ecm|0.2.3
gitignore|mic|1.0.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.5.76608-dev
remote-wsl|ms-|0.44.2
gremlins|nho|0.15.1
autodocstring|njp|0.5.1
vscode-css-peek|pra|3.0.2
vscode-yaml|red|0.7.2
vscode-autohotkey|sle|0.2.2
html-preview-vscode|tht|0.2.5
vscodeintellicode|Vis|1.2.6
html-css-class-completion|Zig|1.19.0

</details>

**Comment by rebornix** [comment]
This feature is provided by the Python extension, please file issues against them for now.
