### ISSUE TITLE
Show quickpick when selecting dynamic debug configuration container

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#96778]
Issue Type: <b>Feature Request</b>

Currently, when selecting a dynamic debug configuration container in the debug viewlet dropdown, a quickpick for selecting the actually configuration is shown when pressing 'play'. It would be nice if this quickpick were shown when first choosing the container so that the user doesn't have to keep choosing the configuration when stopping and restarting debugging.

Refs: https://github.com/microsoft/vscode/issues/95837

VS Code version: Code - Insiders 1.45.0-insider (a0fe37870c42e0704a492cdc6b8550b4cf23f63c, 2020-04-30T05:36:26.465Z)
OS version: Darwin x64 18.7.0

**Comment by isidorn** [comment]
@RMacfarlane Thanks a lot for feedback @weinand also gave the same feedback.
So now I have changed that as soon as you select a debug configuration container we ask you to choose a configuration

**Comment by isidorn** [comment]
To verify:
1. Have js-debug extension installed
2. Select it in the debug dropdown
3. Make sure we immediatly ask you to choose a configuration
