### ISSUE TITLE
Text replacement doesnt work in macOS

### ISSUE THREAD

**Issue by ljhack** [microsoft/vscode#96771]
- VSCode Version: 1.44.2
- OS Version: macOS 10.15.4

Steps to Reproduce:

1.
macOS: System Preferences / Keyboard / Text / 
Replace: omw
With: On my way!

2.
WRONG: in VSCode, Type: omw, Show: omw

3.
CORRECT: in Safari, Type: omw, Show: On my way!

Does this issue occur when all extensions are disabled?: Yes

**Comment by canturkisci** [comment]
Is this issue getting closed? I just discovered there is an issue for it and know others who would want this feature.
