### ISSUE TITLE
selecting a line longer than the window, ie horizontal scroll is broken

### ISSUE THREAD

**Issue by mithereal** [microsoft/vscode#96787]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. try to select and highlight a long code line making the horizontal scrollbar move and it randomly flips out, and automatically moves the scrollbar randomly causing the editor pane to move   it refuses to respect where i have my mouse cursor regardless i am selecting code. 
2. this has been going on now for over 1.5 years, there is absolutely no reason i can use this anymore, i cannot even do my job. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexdima** [comment]
@mithereal I'm not sure I understand what the problem is. Selecting, even on a long horizontal line works fine for me. Can you please create a screen recording to better demonstrate the problem?
