### ISSUE TITLE
Search all panes from search viewlet

### ISSUE THREAD

**Issue by beltaurus** [microsoft/vscode#96788]
I searched for "search terminal", got 106 matches, but nothing that seems to match the desired feature...

Sometimes, in the middle of a debug run, I need to search for a string in the output of my debug run (could be OUTPUT, DEBUG CONSOLE, TERMINAL)... For my more complex jobs, that is almost impossible to do visually.
I would like the "Search" view to have the option to search my output windows for the string (obviously I can't replace it, but finding it is all we need anyway).

**Comment by ArturoDent** [comment]
You want to search across Output, Debug Console and Terminal at the same time?  I.e., In a single Find Widget find your term wherever it might be?

**Comment by beltaurus** [comment]
Note that the 'work around' of putting a break point in the location where output is being produced is not relevant: in the middle of my debugging, I realize that a certain event should or shouldn't have passed before the current status. This event can be traced by inspecting the output/terminal information, where you might have multiple occurrences of the search string...

I would indeed like to search any of the terminals (note that for the 'Terminal' and 'Output' tabs, there might be a bunch of different terminals to be searched).

How to do this can be reviewed by productivity/easy-of-use experts:

Maybe under "Search Details" there can be check boxes (default 'off'), corresponding to the potential search areas:

![image](https://user-images.githubusercontent.com/54114043/80989520-e6f60280-8de9-11ea-9199-7cf0352120e3.png)

```
Consoles to search:
[ ] Output
[ ] Debug Console
[ ] Terminal
```
