### ISSUE TITLE
Should we remove the status bar of a cell when output is cleared?

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#96786]
After running "Clear All Cells Output", the cells still say `X results, took Y.ZZsecs`. I find that confusing since there are no results any more.

**Comment by roblourens** [comment]
Since the extension controls the status bar, it would have to know when this happened, and there isn't any event fired when the outputs change, awkward. Or vscode could take control here and clear it anyway. I wonder what happens if you run this command while the cell is in the middle of executing?

**Comment by rebornix** [comment]
This is doable now by extensions.

**Comment by Tyriar** [comment]
So this is a GH notebooks bug then?

![image](https://user-images.githubusercontent.com/2193314/83793426-5f521c80-a651-11ea-9663-0421601d4fd8.png)

**Comment by roblourens** [comment]
Yeah it hasn't been implemented there yet. I opened an issue https://github.com/microsoft/vscode-github-issue-notebooks/issues/40
