### ISSUE TITLE
Code lens get randomly bungled in the latest stable, "actual command NOT FOUND" error on click

### ISSUE THREAD

**Issue by SirIntruder** [microsoft/vscode#96783]
- VSCode Version: 1.44.2
- OS Version: Win10

This looks like the same issue as locked&closed https://github.com/microsoft/vscode/issues/84153. 
I think I've found a simple and reliable repro so I suggest that issue to be reopened.

Repro steps:
1: Make basic HelloWorld c# program with "dotnet new console". Add test class like in the gif to have some densely packed code lens.
2. Move/delete/enter multiple lines at the same time.
3. Result: code lens get mixed up, and clicking on the bungled ones result in `actual command NOT FOUND` errors

Here is a visual demonstration:

![codelensbug](https://user-images.githubusercontent.com/5102661/80819509-6494f500-8bd5-11ea-9147-737a3c176b7e.gif)

It's broken whenever number of references doesn't match the field name. It frequently gets bungled and un-bungled on every change, so it's likely some racing-conditions are going on.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Abug+label%3Aeditor-code-lens

**Comment by jrieken** [comment]
Maybe not https://github.com/microsoft/vscode/issues/92660...

**Comment by SirIntruder** [comment]
You meant #84153? I've found that issue, but opened this one since it's marked as locked/fixed

**Comment by SirIntruder** [comment]
About #92660, I get a combination of disappearing code lens + bungled references value when I try to do the same thing in vscode repo.

**Comment by jrieken** [comment]
Can you try this with [VS Code Insiders](https://code.visualstudio.com/insiders/)? There has been a code change that might have fixed this...

**Comment by SirIntruder** [comment]
```
Version: 1.45.0-insider (user setup)
Commit: fd5d9a30259bb2bebab3e62dfd8315c2e1b27744
Date: 2020-05-04T09:29:52.824Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134
```

This is the insiders build I tried, and unfortunately, it didn't get better. I think It also started flashing "MISSING COMMAND" frequently between edits, don't recall doing it that before.

On the bright side, "disappearing code lens" bug in typescript repos does not seem to happen anymore - but all references drop to zero when moving lines around.

**Comment by strowk** [comment]
Same in a newest 1.47.0

**Comment by mattacosta** [comment]
Still happening as of the latest 1.48 insiders release (in a TypeScript file).

My console entry is slightly different to the one in #84153 though:
```
actual command NOT FOUND                                                   notificationsAlerts.ts:40
onDidChangeNotification @ breadcrumbsModel.ts:39
```

**Comment by jrieken** [comment]
Still unable to reproduce. Anyone that can, please run with trace log level (F1 > Set Log Level > Trace) and check the extension host log (F1 > Show Logs > Extension Host) for messages starting with `CommandConverter#`

**Comment by SirIntruder** [comment]
[trace.txt](https://github.com/microsoft/vscode/files/5519515/trace.txt)

It's all the "638 MISSING" commands

**Comment by SirIntruder** [comment]
[trace2.txt](https://github.com/microsoft/vscode/files/5519582/trace2.txt)

This one might be better, I disabled some noisy extensions.
I also have an feeling that this thing is much easier to repro on a bottom of a long file.

**Comment by jrieken** [comment]
Thanks @SirIntruder. I can reproduce and I believe I know what's happening here: Code lens works in two phases. 

1. First we ask about all potential code lens places and 
2. second we ask to resolve those places (for visible places which repeats when scrolling etc). 

Whenever you type we start again but there is also code to resolve new places when typing, e.g when removing a large block of text which then reveals new, unresolved places. The problem is that the resolve call isn't valid because the positions of the original lenses have changed. Another problem is that the resolve-after-type races against the resolve-after-places.
