### ISSUE TITLE
initial startup performance slow on "workbench ready" (1771 ms) and "extensions registered" (1919 ms)

### ISSUE THREAD

**Issue by josephsieh** [microsoft/vscode#96785]
Issue Type: <b>Performance Issue</b>

initial startup performance slow on "workbench ready" (1771 ms) and "extensions registered" (1919 ms).

Hit F1 and select "Startup Performance.".

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-3245 CPU @ 3.20GHz (32 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|224.00GB (16.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   15	     0	 14610	code main
    4	     0	 14611	   gpu-process
    0	     0	 14613	   utility
   11	   229	 14614	   window (Startup Performance)
    1	     0	 14618	     extensionHost
   16	     0	 14622	   shared-process
    0	     0	 14639	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
   27	     0	 14637	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none

### Performance Marks

| What                                                            | Duration | Process          | Info                                     |
| --------------------------------------------------------------- | -------- | ---------------- | ---------------------------------------- |
| start => app.isReady                                            | 43       | [main]           | initial startup: true                    |
| nls:start => nls:end                                            | 0        | [main]           | initial startup: true                    |
| require(main.bundle.js)                                         | 61       | [main]           | initial startup: true                    |
| app.isReady => window.loadUrl()                                 | 189      | [main]           | initial startup: true                    |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 593      | [main->renderer] | NewWindow                                |
| require(workbench.desktop.main.js)                              | 478      | [renderer]       | cached data: YES, node_modules took 38ms |
| require & init workspace storage                                | 14       | [renderer]       | -                                        |
| init workspace service                                          | 18       | [renderer]       | -                                        |
| register extensions & spawn extension host                      | 124      | [renderer]       | -                                        |
| restore viewlet                                                 | 19       | [renderer]       | workbench.view.explorer                  |
| restore panel                                                   | 0        | [renderer]       | -                                        |
| restore editors                                                 | 217      | [renderer]       | 1: workbench.input.settings2             |
| overall workbench load                                          | 435      | [renderer]       | -                                        |
| workbench ready                                                 | 1771     | [main->renderer] | -                                        |
| extensions registered                                           | 1919     | [renderer]       | -                                        |

**Comment by jrieken** [comment]
There is actually nothing suspicious here. The startup time of 1.7sec is well within the average and while we constantly work on improving performance there is nothing actionable in this item
