### ISSUE TITLE
Sash on top of hover

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#9678]
1.  Open the horizontal panel and have it expanded all the way to the top
2. Start debugging the following code snippet
3. Hover over `range`. the complex hover should go over the horizontal panel. Notice that the sash is over the hover

Currently sash has `z-index 100` and hovers `50`, but changing this did not have an effect.
This also happens for the regular hover, however there is an unrelated issue there that the regular hover closes when you leave the editor area (if you want to see it there just comment out the hide method)

```
var range = {

    startLineNumber: 7,

    endLineNumber: 8,
    startColumn: 123,
    text: "lineContext.getTokenEndIndex(tokenIndex) + 1",
    te: "11",
    te6: "11",
    // te7: myLongString,
    child: {
    aunt: {

    grandchild: {
    lala: 'adasd',
    evenMore: 'alskdjlaksd',
    t3: 'asdlkasdjlkasdjlkasdjlkads',
    t5: 'asddasdasadsadsadsads',
    t7: 'asdasdadsadsadsasdasdasdads',
    t9: 'asddasadsads',
    i: 1123,
    j: 12121
    }
    }
    }
}
var t = range;
debugger;
```

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/media/workbench.css#L29
