### ISSUE TITLE
Can only type some letters (wfjzn)

### ISSUE THREAD

**Issue by muyao-xu** [microsoft/vscode#96799]
Issue Type: <b>Bug</b>

I cannot type any letters other than 'w' 'f' 'j' 'z' 'n' in the application (the text editor and all other input fields). I did ont install any extensions.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 5.2.17-1rodete3-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU @ 2.20GHz (64 x 2200)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|2, 2, 1|
|Memory (System)|56.60GB (7.15GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by muyao-xu** [comment]
A browser window is opened to submit this issue from the appli

**Comment by KozakBartosz** [comment]
I also have this problem. I have no idea what caused it. I've tried everything. I reinstalled the program without any extensions, but the problem still exists.

I noticed that double clicking the alt key brings you back to typing. The problem reappears when switching between other programs. It looks like focus and defocus on vscode window isn't working properly.

VScode version: 1.47.2
System: Pop!_OS 20.04 LTS
Shell: Gnome 3.36.3

**Comment by robjfoster** [comment]
Are there any updates on this? I'm having the exact same issue (can only type wfjzn). If I alt-tab away and then back to vscode it allows me to type as normal for a fraction of a second before the problem reappears. I have reinstalled vscode several times and the problem reoccurs every time. I have no extensions installed.

Code version: 1.48.1
OS: Ubuntu 20.04.1 LTS

The problem is not present for me in Code-Insiders version 1.49.0.

**Comment by deepak1556** [comment]
Is this still an issue with latest insiders https://code.visualstudio.com/insiders ?
