### ISSUE TITLE
php.validate.executablePath - Unable to override in workspace

### ISSUE THREAD

**Issue by zizzer** [microsoft/vscode#96794]
- VSCode Version: 1.44.2
- OS Version: Win 7 x64

Steps to Reproduce:

1. Install the Remote Development extension
2. Connect to a remote host via SSH
3. Open settings and search 'php.validate.executablePath'
4. This setting only appears for your remote host and not in 'User' or 'Workspace'

The setting is limited to "machine" scope only and adding it to the Workspace settings.json has no effect. See Line 42 of the inbuilt [php-language-features](https://github.com/microsoft/vscode/blob/master/extensions/php-language-features/package.json) extension

The issue with this is that if you are running multiple versions of PHP on the remote host using docker, you are unable to specify a project specific version to use for validation.

I think the scope of the php.validate.executablePath should be expanded for flexibility.

**Comment by sandy081** [comment]
File this against php extension and request to change the scope of the setting to `machine-overridable`.

**Comment by yume-chan** [comment]
@sandy081 op is talking about the built-in PHP extension.

https://github.com/microsoft/vscode/blob/9f07996c19ea2e17676075bc9017978fd26a8702/extensions/php-language-features/package.json#L35-L43
