### ISSUE TITLE
Task does not leverage cwd for problemMatcher

### ISSUE THREAD

**Issue by vrachels** [microsoft/vscode#96796]
- VSCode Version: 1.44.2
- OS Version: Linux x64 4.4.0-53-generic Ubuntu 16.04.6 LTS

Steps to Reproduce:

1. Create a task with
* options : cwd : `<some subfolder or workspace folder>`
* problemMatcher, ie $gcc
2. Execute task which has errors (ie, compile errors)

note
* task output is "> Executing task in folder `<workspace root, not cwd>`"
* execution does occur correctly
* problem matcher 'problem files' are built using `<workspace root>/<matched relative path>`
* clicking on a file or problem gets the 'unable to read file' dialog (of the above invalid path)

Does this issue occur when all extensions are disabled?: Yes... task output is still incorrect, though my specific problem matcher (gcc) cannot run due to disabled extension.

**Comment by alexr00** [comment]
Can you please provide a full copy/pastable example?
