### ISSUE TITLE
Unsaved data lost on freeze.

### ISSUE THREAD

**Issue by m-garg** [Microsoft/vscode#9679]
- VSCode Version: 1.3.1
- OS Version: OS X El Capiton, 10.11.4 (15E65)

Sometimes VSCode freezes unexpectedly.
So, if we click on the "reopen" when prompted, all the unsaved changes are lost.
Also, VSCode opens the files which were open long time back, not the files which I was working on at the time of crash.

**Comment by cihancil** [comment]
I came to open same exact issue.
When VS code crashes all the open editors are closed.

**Comment by wUFr** [comment]
#9406 similar problem, started in 1.3.0

**Comment by kieferrm** [comment]
Related to #101.

**Comment by m-garg** [comment]
Sometimes, vscode freezes when not even using it.

**Comment by wUFr** [comment]
i had to rollback to 1.2.1 ... 1.3.0 freezes a lot, mostly when you save larger file, then after like 5 to 10 sec delay, it will freeze and wont save changes

**Comment by bpasero** [comment]
Yes, I would think #101 would resolve this issue. However, would be interesting to learn why the freezes suddenly happen. 

If people on this thread could share more details when this happens and if it reproduces with extensions disabled?

**Comment by m-garg** [comment]
@bpasero Freezing is not that frequent for me. And, till now, I'm not able find the common action which leads to the freezing (as I say, sometimes it crashes even in the background).

**Comment by bpasero** [comment]
Ok lets close this until we have more info on it.

**Comment by JWess** [comment]
This is an important ticket. Sometimes I will open a new file to take a few notes, but then I will forget to save the new file. Several times when I go to close my VS Code window, it prompts for me to save my new file, but when I affirm that I want to save it, the save explorer window pops up and completely freezes. VS Code is then frozen and must be force-quit.
