### ISSUE TITLE
Add a command pallete command & keybinding for completely minimizing the workbench

### ISSUE THREAD

**Issue by arschles** [microsoft/vscode#96793]
Currently, you can toggle the workbench or toggle it maximized but there doesn't seem to be a way to toggle it minimized. For example, if you run a `workbench.action.toggleMaximizedPanel` when it's already maximized, the workbench will go back down to 1/2 screen. It would be nice if either it went down to its original position - which could be completely minimized - or there was a different command that would automatically completely minimize the terminal.

**Comment by bpasero** [comment]
Moving to Steven, given he added support via the custom title to do this, so we probably would need to expose the commands.

**Comment by arschles** [comment]
thanks @bpasero. I discovered ctrl+J that technically does full minimization when the workbench is the whole screen, so that'll do the job for me. I'm going to close this issue now. Thanks again!
