### ISSUE TITLE
A new command of "enter"

### ISSUE THREAD

**Issue by weidonglian** [microsoft/vscode#96792]
A feature we could easily bind a keyboard short cut to the "enter" key. vscode has now 'tab' command, why not a new 'enter' command which behaves exactly the same as 'enter'. 
I would like to bind "ctrl+j" or "ctrl+m" to this new "enter" command. 
I tried the following macro: 
            "lineBreakInsert",
            "cursorHome",
            "cursorDown"
It is not perfect and not the same as "enter" key.

**Comment by alexdima** [comment]
You could use:
```
{
	"key": "ctrl+j",
	"command": "type",
	"args": {
		"text": "\n"
	},
	"when": "editorTextFocus"
},
```

**Comment by weidonglian** [comment]
> "args": {
> 		"text": "\n"
> 	},

That works really well.
