### ISSUE TITLE
Extension page version number styling

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#96802]
Issue Type: <b>Bug</b>
https://github.com/microsoft/vscode/issues/94123

Tthe italicized version number at the top of an extension's page looks out of place to me, I think it would look more consistent for it to not be in italics, and perhaps say "Version" in front of it.
<img width="816" alt="Screen Shot 2020-05-01 at 1 59 30 PM" src="https://user-images.githubusercontent.com/3672607/80841379-1e7b6980-8bb4-11ea-9f67-863519953745.png">

Just a suggestion, feel free to close.

VS Code version: Code - Insiders 1.45.0-insider (ece7aaee861d7261a728d52ce436c667030ce17d, 2020-05-01T09:44:59.826Z)
OS version: Darwin x64 18.7.0

**Comment by sandy081** [comment]
No hard feelings. Changed as per your suggestion

<img width="632" alt="image" src="https://user-images.githubusercontent.com/10746682/80965259-84fdc300-8e12-11ea-9c8c-4e6b4870908a.png">
