### ISSUE TITLE
Want `Close Folder` button in Explorer control

### ISSUE THREAD

**Issue by MightyPen** [microsoft/vscode#96808]
It is unnecessarily tedious to Close a Folder, to have to perform: **Alt** \> **File** \> **Ctrl+K F**. This is not the easiest hotkey (or "chord") sequence, and the whole action sequence requires use of the keyboard. A pure mouse option would be easier.

When NO folder is open, the Explorer panel offers a prominent blue button labeled `Open Folder`. Good.

- _**My Request:**_ &nbsp; When a folder IS open, offer a button labeled `Close Folder`.
  - `Close` a folder is very different than `Hide` the Explorer panel, obviously. I am asking for **Close** folder, not Hide.

This will make it easier to `Close Folder` when a folder is open.

---

_Loosely Related Issue is **94755**_: &nbsp; `https://github.com/microsoft/vscode/issues/94755`

- https://github.com/microsoft/vscode/issues/94755
- _Title:_ &nbsp; 'Add "Close folder" on Welcome screen (if a folder is open)'

---

Thank you. Gene Milener (GeneMi at Msft = MightyPen) , 2020/May/01

. .

**Comment by isidorn** [comment]
Please assign a custom keybinding to this command, via File > prefernces > keyboard shortucts
You can also write an extension to contribute this command whenever you want.
We will not change the default built in experience for now, thus closing this. Thank you
