### ISSUE TITLE
Ability to move the cursor with the arrow keys and respect the current horizontal position

### ISSUE THREAD

**Issue by inferiorhumanorgans** [microsoft/vscode#96809]
Given this version of VSCode:

```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

Given the text:

```
foo
foo bar
foo bar baz
foo bar
foo
```

If I use the mouse and position the cursor after `foo bar` on line two and press the down arrow the cursor moves to the same horizontal position on the next line.  If I use the arrow keys and go to the end of the second line and then press the down arrow the cursor is moved to the end of the next line.

This behavior persists even after running with `--disable-extensions` and appears to be new/changed.

Some way to revert to never following the end-of-line would be much appreciated.

**Comment by alexdima** [comment]
@inferiorhumanorgans Indeed, this is relatively new behaviour (came in via https://github.com/microsoft/vscode/pull/88664) that is triggered only by the `cursorEnd` and `cursorEndSelect` commands. There is no way to currently configure this behaviour.

**Comment by reduckted** [comment]
> There is no way to currently configure this behaviour.

Please add an option to turn this off. This behavior is really annoying.

**Comment by inferiorhumanorgans** [comment]
Agreed, this really violates the policy of least surprise and ideally would be backed out until it can be made configurable.

**Comment by reduckted** [comment]
> @alexdima  (came in via #88664)

What I don't understand is why this change was made. The reason given in the PR was:

> I added end key remembering behaviour that exists in almost all editors.

This behavior doesn't exist in Visual Studio or Atom (at least with the default settings I used). What editors actually have this behavior?

**Comment by Florent-Steiner** [comment]
Please Help. This is really annoying. Both cursorEndSelect  and cursorHomeSelect are wrong.

**Comment by alexdima** [comment]
I have pushed that the default is back to what we had before the March release (i.e. End and Shift+End are not "sticking" to the end of the lines). To get the sticky behaviour, you now need to customize in `keybindings.json` e.g.

```
    { "key": "end",       "command": "cursorEnd",       "when": "textInputFocus", "args": {"sticky":true} },
    { "key": "shift+end", "command": "cursorEndSelect", "when": "textInputFocus", "args": {"sticky":true} },

```

**Comment by reduckted** [comment]
Thank you for fixing this.

**Comment by Florent-Steiner** [comment]
Wonderfull news :)
Did you fixed it for cursorHome too ?

**Comment by gjsjohnmurray** [comment]
> Wonderfull news :)
> Did you fixed it for cursorHome too ?

@Florent-Steiner please clarify what you think got broken in cursorHome

**Comment by Florent-Steiner** [comment]
Hello John,

This is the full issue :

1/ Type a three lines text
2/ Go to the middle of line 2
3/ Press and don't release shift key
4/ Press Up
5/ Press Home: you should be at the beginning of line 1
6/ Press End: you should be at the end of line 1, not line 2
7/ Release shift key
8/ Go to the middle of line 2
9/ Press and don't release shift key
10/ Press Down
12/ Press End: you should be at the end of line 3
11/ Press Home: you should be at the beginning of line 3,  not line 2
13/ Release shift key

—
Best regards,

 *           Florent STEINER*
            // Cogérant
            florent@adopteunmec.com
            +33 6 61 18 27 79


Le dim. 21 juin 2020 à 04:26, John Murray <notifications@github.com> a
écrit :

**Comment by gjsjohnmurray** [comment]
@Florent-Steiner I wasn't able to reproduce your problem on Windows (reloaded with all extensions disabled):

![junk](https://user-images.githubusercontent.com/6726799/85273878-17672e00-b476-11ea-8bc2-437467e5f279.gif)

Note that screencast mode doesn't show it clearly, but I held Shift down from step 3 to step 7, and from step 9 to step 13.

Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by Florent-Steiner** [comment]
That meands you fixed the issue for both cursorHome and cursorEnd.
Thank you very much <3
