### ISSUE TITLE
Disabling an extension causes the ignored sync icon to appear

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#96806]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/35271042/80845463-1fb19400-8bbe-11ea-8129-edb4ee1273bc.png)

VS Code version: Code - Insiders 1.45.0-insider (ece7aaee861d7261a728d52ce436c667030ce17d, 2020-05-01T09:44:59.826Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|16.00GB (2.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-track-build-errors|aes|0.0.2
mock-debug|and|0.36.2
emojisense|bie|0.7.0
vscode-opennewinstance|chr|0.0.7
vscode-eslint|dba|2.1.5
pug-formatter|duc|0.6.0
gitlens|eam|10.2.1
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
vscode-open-in-github|fab|1.2.3
vscode-pull-request-github|Git|0.16.0
todo-tree|Gru|0.0.174
all-symbol-kinds|jri|0.0.1
vscode-colorize|kam|0.8.16
theme-monokai-pro-vscode|mon|1.1.15
vscode-duplicate|mrm|1.2.1
vscode-scss|mrm|0.9.0
vscode-azureappservice|ms-|0.16.5
remote-containers|ms-|0.114.0
remote-ssh-edit-nightly|ms-|2020.4.9540
remote-ssh-nightly|ms-|2020.4.9540
remote-wsl|ms-|0.44.2
azure-account|ms-|0.8.9
vscode-github-issue-notebooks|ms-|0.0.19
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2104
svg-preview|Sim|2.8.3
vscode-fileutils|sle|3.0.1
notification-tester|svi|2.4.8
enumerator|swi|0.0.6
sass-indented|syl|1.8.3
sort-lines|Tyr|1.9.0
material-theme|zhu|3.3.1

(4 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
I cannot repro this, can you please check if the extension is ignored already by looking into ignored extensions setting?

**Comment by misolori** [comment]
I think you're right, I can't repro this again and I must've ignore it at some point. Sorry for the false alarm.
