### ISSUE TITLE
Bug with problems area, developing with Python

### ISSUE THREAD

**Issue by Ernest05** [microsoft/vscode#96800]
- VSCode Version:
Version: 1.44.2
- OS Version:
Ubuntu Cinnamon 20.04
Linux x64 5.4.0-28-generic
Steps to Reproduce:

1. Open a Python file into VSCode
2. Do any error into the code
3. Open issues area and click on any issue into the area
4. VSCode crashes, or VSCode causes the OS (Ubuntu) to crash

Does this issue occur when all extensions are disabled?: Yes/No
This issue persists even if all extensions are disabled.

Hello,
I report an issue I found 1/2 days ago on VSCode. When I'am working with Python and when I got a syntax problem, or any problem, if I click on any problem into the problems area, VSCode crashes, so the Window doesn't responding during around one minute, next Ubuntu says me the application doesn't respond and that it is necessary to force it to close. Or simply, VSCode causes the OS to crash... This bug is very annoy, and I hope you can resolve it.
I wish you a good day/evening, and thanks for reading my issue!
Sincerely.

**Comment by alexr00** [comment]
Can you please provide a copy/pastable example of the code with the error?

**Comment by sandy081** [comment]
This works for me with other language errors. I would recommend to file issue against Python extension first.
