### ISSUE TITLE
Should brackets follow a method or function

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#9680]
- VSCode Version: 1.3.1
- OS Version: macOS 10.12

When I use `tab` or `enter` to select a method or function. It may be better to auto insert pair of brackets after method or function name.

*before:*
**`console.log`**

And it should like this. *after:*
**`console.log(...);`** or **`console.log();`**

So other languages should also do.

Thinks a lot.

**Comment by dbaeumer** [comment]
We discussed and decided against it since function can be referenced by name as well: `var log = console.log`. To help we insert the closing bracket when you type (.
