### ISSUE TITLE
Munged path when running WSL-remote; gives {path} is not a valid tsserver install

### ISSUE THREAD

**Issue by mjyeaney** [microsoft/vscode#96804]
Issue Type: <b>Bug</b>

When using VSCode (on Windows) against WSL-Remote, I get the following error:

> The path /mnt/c/Projects/Local/who-demand-supply-web-app/C:\Users\micha\AppData\Roaming\npm\node_modules\typescript\lib doesn't point to a valid tsserver install. Falling back to bundled TypeScript version.

If you look at the path, there is an obvious issue with joinging *nix paths and Windows paths - however, I can't find anywhere where the path is specified. 

I frequently switch between edits on windows and WSL, so hardcoding this isn't really an option.

Is this a known issue?

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2001)|
|Memory (System)|15.89GB (7.57GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
json-tools|eri|1.0.2
prettier-vscode|esb|4.5.0
docomment|k--|0.1.9
csharp|ms-|1.21.17
python|ms-|2020.4.76186
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-docker|ms-|1.1.0
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
vscode-iot-device-cube|vsc|0.2.0
vscode-icons|vsc|10.1.1

</details>

**Comment by mjyeaney** [comment]
Any input / updates here?

**Comment by mjbvz** [comment]
It looks like you are using a workspace or user version of TypeScript. Is that correct? Can you please provide steps to reproduce this?

**Comment by mjyeaney** [comment]
@mjbvz - I'm using Typescript from my WSL Ubuntu install (which is currently version 3.8.3).  There's not really any steps....opening any project from WSL that uses Typescript causes this error for me.  If I use a project on Windows, everything works fine.
