### ISSUE TITLE
Add next occurrence [⌘ D] unexpected behavior

### ISSUE THREAD

**Issue by jaredyam** [microsoft/vscode#96814]
- VSCode Version: 1.43.0-insider
- OS Version: mac)S 10.15.4

In my use case, I wish the ⌘D shortcut could let me quickly select bits of the same variables and then rename them synchronously. This method works fine in SublimeText and I think it should be the same in VsCode. Unfortunately, when I type the backspace key, I wish the result should delete one char at once or remove one word is fine. The result in VsCode is unexpected for me, the behavior is shown in GIFs below.

Steps to Reproduce:
Reproduce procedure in VsCode:
![Screenflick Movie](https://user-images.githubusercontent.com/50312506/80851843-a6b24b00-8c56-11ea-96ce-512f39e39313.gif)
![Screenflick Movie -vscodegif](https://user-images.githubusercontent.com/50312506/80851846-a9ad3b80-8c56-11ea-84b7-f89b1e3d8cba.gif)
The same procedure in Sublime:
![Screenflick Movie——sublime](https://user-images.githubusercontent.com/50312506/80851857-bdf13880-8c56-11ea-801f-69fba825c877.gif)

When I typed backspace it should have the same effects at all my selected words, right? are there any features I don't know about? or my settings' problem? 

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
From your screen recording, I can see that you have vim enabled. So the following statement in the issue report is false:

Does this issue occur when all extensions are disabled?: Yes
