### ISSUE TITLE
allow to copy the content of variables/watch window

### ISSUE THREAD

**Issue by stardeath** [microsoft/vscode#96811]
seems like, at the moment, in the variables and watch windows, we are only able to have "Copy Value" and "Copy as Expression" in variables window and "Copy Value" in watch window, each of these option being able to copy only part of a line.
i would like to be able to copy the whole variables/watch to clipboard (either with keyboard shortcut, like "ctrl+a, ctrl+c" or with a rigth-click option).
for example :
![screenshot](https://user-images.githubusercontent.com/22247160/80850042-2968e500-8c1a-11ea-9e3c-2d405236e631.png)
would give something like :

`- Local`
`  + this: function SceneManager() { ... }`
`    fTime: 0.010340000037103891`
`    newTime: 709.5299998763949`
`+ Global`
and
`  sprite.__name: not available`
`+ [this.width, this.height]: Array(2) [undefined, undefined]`
`  this.transform.localTransform.dump(): not available`
(sorry I wasn't able to have a good indentation for the results)

this is from JavaScript debug, but since it's only the visible content of these windows, it should be language independent.

Version: 1.45.0-insider ece7aaee861d7261a728d52ce436c667030ce17d
OS: Windows_NT x64 10.0.18363

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by starball5** [comment]
> i would like to be able to copy the whole variables/watch to clipboard (either with keyboard shortcut, like "ctrl+a, ctrl+c"

This is implemented now, no? https://github.com/microsoft/vscode/issues/114353 -> https://github.com/microsoft/vscode/pull/114388.

**Comment by isidorn** [comment]
Correct. This is now implemented!
