### ISSUE TITLE
Typo in placeholder text of editor switcher

### ISSUE THREAD

**Issue by himanshupal** [microsoft/vscode#96815]
The _edit active_ is spelled _edt active_
![image](https://user-images.githubusercontent.com/40417771/80852539-13254e00-8c47-11ea-9207-7be4e6639485.png)

- VSCode Version: 1.44.2
- OS Version: Windows10 1909

Steps to Reproduce:

1. Open vsCode without opening any files
2. Click `Ctrl` + `Tab`

Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment]
Interesting question. `edt` is a command to show all editors.

Not sure who named that, but that's definitely intended, maybe because it's shorter?

Ref #93637

![image](https://user-images.githubusercontent.com/1330321/80866257-435d0300-8cc0-11ea-9e19-61226e993cfe.png)

**Comment by himanshupal** [comment]
Oh. I get it.
