### ISSUE TITLE
Clicking the Markdown preview button crashes VSC

### ISSUE THREAD

**Issue by memco** [microsoft/vscode#96818]
Issue Type: <b>Bug</b>

For me any time I click the "Open preview to the side" button in the top right corner of a markdown file it crashes VSC. Interestingly, this crash does not happen if I trigger the action with the keyboard shortcut or from the command palette—it is only when clicking the button.  Is there a setting or something I can check to diagnose or troubleshoot?

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|23, 8, 5|
|Memory (System)|16.00GB (0.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.1
vscode-standardjs|che|1.3.0
shell-format|fox|7.0.1
vscode-colorize|kam|0.8.16
nim|kos|0.6.6
fish-ide|lun|0.4.0
rust-analyzer|mat|0.2.151
pyright|ms-|1.1.34
python|ms-|2020.4.76186
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
cpptools|ms-|0.27.1
sublime-keybindings|ms-|4.0.7
color-highlight|nau|2.3.0
vetur|oct|0.24.0
fish-vscode|sky|0.2.1
uridecode|sry|0.3.5
zig|tie|0.2.4
expand-selection-to-scope|vit|0.2.0
change-case|wma|1.0.0
sublime-commands|Zar|0.1.0

(6 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by memco** [comment]
No. A fresh install of insiders with no extensions does not have this behavior.

**Comment by mjbvz** [comment]
Ok. Closing as not-reproducible.

if you have a chance, see if you can find which extension is causing this or if it was VS Code insiders that fixed this
