### ISSUE TITLE
One suggestion is to open different extensions in batches in different workspaces

### ISSUE THREAD

**Issue by syouSui** [microsoft/vscode#96812]
Hello, it is recommended to add a setting that can batch control the extensions that need to be turned on for each job, so that different extensions for workspaces in different languages will greatly improve fluency.

**Comment by usernamehw** [comment]
Possible duplicate of #40239

**Comment by syouSui** [comment]
> /duplicate

I had seen #40239 and find the "disabled" attribute is not legal for the extensions.json file.And the extensions.json file is only suit for "recommendations" and "unwantedRecommendations". I use a extensions called 'Profile Switcher" to replace my requirement now. But it's still a little inconvenient. What did you do about it? Thanks

**Comment by sandy081** [comment]
#40239 is an open feature request and we have not decided yet on how to implement this.
