### ISSUE TITLE
UI ERROR?

### ISSUE THREAD

**Issue by 1369521908** [microsoft/vscode#96824]
- VSCode Version:1.44.2
- OS Version:window 10 professional 1909 (18363.592)

Steps to Reproduce:

1.open VSCode
2.switch to other application
3.wait a few second
4.then 
![微信图片_20200502161509](https://user-images.githubusercontent.com/32727597/80859696-48f12380-8c95-11ea-8363-59420b6c5c80.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by yume-chan** [comment]
Looks like same type of artifacts as #94523 and #92379.

Please try to disable GPU acceleration: https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Comment by 1369521908** [comment]
Thanks ,it works !! : )
