### ISSUE TITLE
[folding] allow empty lines as folding markers

### ISSUE THREAD

**Issue by shadowninja69** [microsoft/vscode#96821]
Issue Type: <b>Bug</b>

language folding marker end doesn't work on empty line

Steps to Reproduce:

1. 
```
	"folding": {
		"markers": {
			"start": "whatever",
			"end": "^\r?\n"
		}
	}
```
2. Tried to match "end" as the first empty line it finds, doesn't work.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.90GB free)|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|Memory (System)|15.89GB (6.90GB free)|
|VM|0%|

</details>

**Comment by shadowninja69** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Setting the same value for 'start' and 'end' markers for folding does not work (#95974)](https://www.github.com/microsoft/vscode/issues/95974)

No that is not the same issue

**Comment by aeschli** [comment]
That's correct, empty lines currently can not be used as regions markers. We have currently no plans to allow that.
