### ISSUE TITLE
when debug node.js

### ISSUE THREAD

**Issue by juniris** [microsoft/vscode#96828]
Issue Type: <b>Bug</b>

it will display that there is no valid call stack, very annoying

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T11:22:13.689Z)
OS version: Linux x64 4.16.18-galliumos

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz (2 x 2582)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|3.77GB (0.04GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
gdb-debug|Dam|1.0.7
code-runner|for|0.10.0
vscode-language-pack-zh-hans|MS-|1.44.2
python|ms-|2020.4.76186
cpptools|ms-|0.27.1
js-debug-nightly|ms-|2020.5.118
open-in-browser|tec|2.0.0
python|tht|0.2.3
debug|web|0.24.0
markdown-pdf|yza|1.4.4

(1 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
Can you try [our new debugger](https://github.com/microsoft/vscode-js-debug/#nightly-extension) and see if that fixes the problem for you?

If not, please collect a trace log using the following instructions: 

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

/needsMoreInfo
