### ISSUE TITLE
Issue with editor.formatOnSave: true for <li> tags with embedded tag. Extra space is added from line break

### ISSUE THREAD

**Issue by xta** [microsoft/vscode#96825]
- VSCode Version: 1.44.2
- Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
- Date: 2020-04-16T17:07:18.473Z (2 wks ago)
- Electron: 7.1.11
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Darwin x64 18.7.0

Issue with editor.formatOnSave: true for `<li>` tags with embedded tag

Steps to Reproduce:

1. With `"editor.formatOnSave": true` in Settings and using the following example snippet in a Vue file:

```
    <li>Lorem ipsum dolor sit amet, consectetur
      <strong>adipiscing</strong> elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </li>
```

2. The autoformat changes it to:

```
    <li>
      Lorem ipsum dolor sit amet, consectetur
      <strong>adipiscing</strong> elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </li>
```

The line break after `<li>` is an issue since the HTML page renders an unintended space between the `li` bullet and the start of the content ("Lorem ...")

This does not occur if I remove the `<strong></strong>` tags inside the `li`. However, for my use case, I do want to use misc tags within the `li` tag.

**Comment by yume-chan** [comment]
I'm not familiar with Vue, but at least in HTML, leading line breaks will not affect render result.

And for Vue, in my simple test, the line break has no effect either.

https://jsfiddle.net/yume_chan/mrg9s36d/1/

**Comment by yume-chan** [comment]
Ref vuejs/vue#7701

**Comment by xta** [comment]
I can close this issue since I was able to debug & fix on my end.

My issue was having this in my CSS:
```
ul {
  list-style: circle inside;
}
```

Having `inside` can cause issues across browsers, so I removed it in my site styling. MDN has further discussion about browser behavior variance (bug) https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-position

Thanks @yume-chan.
