### ISSUE TITLE
[loc][Query][DevDiv] Please clarify "open editors"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#9682]
Hi, we have a query from our translator. Can you help please? Thanks!

Source:
Open Editors

File NAme:
src\vs\workbench\parts\files\browser\views\openEditorsView.nls.resx

Resource ID:
".resx", 0; "treeAriaLabel"

Query:
Are the editors already öpen or should they be opened?	DE_Translator2	7/21/2016 10:02:27 PM

**Comment by kieferrm** [comment]
The editors are already open.
