### ISSUE TITLE
Terminal panel blank (but kind of responsive) in Vscode Linux

### ISSUE THREAD

**Issue by mi-lad** [microsoft/vscode#96826]
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.5.19-1-MANJARO

Steps to Reproduce:
Not predictable but often happens after wake up from suspense.

The terminal looks blank but I think it's a rendering issue. The terminal process seems to responsive, if I do Ctrl+D it quits and opening it again renders everything correctly. I have tried all the options in `terminal.integrated.rendererType` but it didn't make a difference.

I did a quick search in the GitHub issues and I came across many similar issues. Most of them however are marked as closed. It happens for me all the time, on multiple machines.

**Comment by Tyriar** [comment]
Setting terminal.integrated.rendererType to dom should definitely make this not happen (it might not fix current terminals), it's much slower though.
