### ISSUE TITLE
When I delete the workspace folder on file explorer, the workspace folder on VSC does not close

### ISSUE THREAD

**Issue by PeterF521** [microsoft/vscode#96823]
- VSCode Version: 1.44.2
- OS Version: Ubuntu 20.04 LTS

Steps to Reproduce:

1.Open a workspace Folder
2.Add Files into that.
3.Delete the workspace folder from file explorer. 
4.Return to vscode.

Does this issue occur when all extensions are disabled?: No

**Comment by PeterF521** [comment]
It isn't covered by other issue

**Comment by ArturoDent** [comment]
There is a setting you should look into:

> Workbench > Editor: Close on File Delete
> 
> Controls whether editors showing a file that was opened during the session should close automatically when getting deleted or renamed by some other process. Disabling this will keep the editor open  on such an event. Note that deleting from within the application will always close the editor and that dirty files will never close to preserve your data.

It is false - disabled by default, enable it.

**Comment by isidorn** [comment]
@ArturoDent thanks for jumping in. That settings seems to cover this, thus closing
