### ISSUE TITLE
Snap version opens links in new Firefox process and profile, not existing process and profile

### ISSUE THREAD

**Issue by BillDietrich** [microsoft/vscode#96829]
Issue Type: <b>Bug</b>

Have Firefox browser running with your normal profile (lots of extensions, for example).  In VSCode, open an HTML file for editing, and ctrl+click on an URL in the file to open it.  VSCode will not open a new tab in the existing Firefox process, instead it will launch a new Firefox process with a temporary or empty profile.  The new Firefox will show up in the running-application list (alt+tab on Ubuntu 20.04) with VSCode's icon, not Firefox's icon, associated with it.

Same happens if a link is opened via an extension, instead of via ctrl+click in editor pane.

Please either revert to the non-snap behavior (open new tab in existing Firefox process) or provide a setting to select between old and new behaviors.  Thanks.

VS Code version: Code - Insiders 1.45.0-insider (ece7aaee861d7261a728d52ce436c667030ce17d, 2020-05-01T09:46:11.716Z)
OS version: Linux x64 5.4.0-28-generic snap
Ubuntu 20.04 desktop GNOME

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU       M 370  @ 2.40GHz (4 x 933)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|7.58GB (1.10GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
linkcheckerhtml|Bil|2.2.0
web-accessibility|Max|0.2.82
HTMLHint|mka|0.6.0

</details>

**Comment by isgj** [comment]
Maybe the `code` snap should use the `browser-support` interface.
Other electron based snaps that open links with the default configuration browser are connected to `browser-support` interface.

#### Disclaimer
I'm a snap noob

**Comment by NotWoods** [comment]
This seems to be a [snapd issue](https://bugs.launchpad.net/snapd/+bug/1835024) as the Slack snap has the same problem. You can configure Firefox to work around the problem!

1. Open some URL from the VSCode snap.
2. In the new window, navigate to `about:profiles`.
3. Ensure that the profile marked as "Default Profile" matches Firefox when opened normally.
4. Use the "Set as default profile" button under the correct profile to change the default.

In my case, `default-release` was the profile used when opening Firefox normally, and `default` was used by VSCode and Slack. Setting `default-release` as the default in both versions fixed the issue.

![image](https://user-images.githubusercontent.com/1782266/93691869-4eaea080-faa0-11ea-995f-27a9acbaacc3.png)

**Comment by timotree3** [comment]
Wow awesome discovery NotWoods. That solution works perfectly. Thanks so much

**Comment by joaomoreno** [comment]
cc @flexiondotorg @sergiusens

**Comment by joaomoreno** [comment]
Closing as won't fix, given the current workaround.

**Comment by akhilalekha** [comment]
> This seems to be a [snapd issue](https://bugs.launchpad.net/snapd/+bug/1835024) as the Slack snap has the same problem. You can configure Firefox to work around the problem!
> 
>     1. Open some URL from the VSCode snap.
> 
>     2. In the new window, navigate to `about:profiles`.
> 
>     3. Ensure that the profile marked as "Default Profile" matches Firefox when opened normally.
> 
>     4. Use the "Set as default profile" button under the correct profile to change the default.
> 
> 
> In my case, `default-release` was the profile used when opening Firefox normally, and `default` was used by VSCode and Slack. Setting `default-release` as the default in both versions fixed the issue.
> 
> ![image](https://user-images.githubusercontent.com/1782266/93691869-4eaea080-faa0-11ea-995f-27a9acbaacc3.png)

How do I open some url in vs code "snap" ? I don't understand what snap is?
