### ISSUE TITLE
Feature requset: creating custom variables in snippets

### ISSUE THREAD

**Issue by mterczynski** [microsoft/vscode#96832]
I would like to be able to create variables for use in snippets to get rid of code duplication.

For example, I might want to transform a file name or current date in a certain way and reuse the output in multiple places.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Afeature-request+label%3Asnippets
