### ISSUE TITLE
A log file to list all of the notifications that occurred

### ISSUE THREAD

**Issue by Rubix982** [microsoft/vscode#96838]
Hello!
I often find myself working on some project when some notifications pop up on the bottom. Mostly, it is related to some packages or other side effects when I'm working on something. They aren't my top priority, and I know that aren't really that important when I'm working on them, but it's something that I would like to later look on into.

For example `changelogs` for packages, package deprecation notices, options that are triggered in certain situations and which I can look up later on what exactly caused those issues ( if they are even worth looking into or not ). It can be useful to read these information as they can be related to `documentation`, `debugging`, and `troubleshooting`.

But all of the notifications vanish when I click on the `cross` button on the notification top bar - some just clog up the notification bottom button with stuff I rather not want to be bothered about, and visually it just makes it hard to navigate what's currently important and what I want to later `read`, or `later attend to`. 

So the **feature request** would be that there is some place or file where we can look up all the notifications that occurred, say in a `day`, or the last `hour`. Or maybe add another button when the notification pops up, something like `attend later`.

Thank you, and have a nice day!

**Comment by coffenbacher** [comment]
![image](https://user-images.githubusercontent.com/245867/86028337-a03a1880-b9e6-11ea-8199-20fdfc5f4006.png)

I found this issue when trying to find a log file to figure out where this notification was coming from. As far as I can tell, there's no way to see what's causing this. A log file of notifications with standard fields would be helpful!

**Comment by Rubix982** [comment]
Thanks, @coffenbacher. I hope the request gets accepted as well!
