### ISSUE TITLE
Files don't appear in the explorer tab

### ISSUE THREAD

**Issue by viclafouch** [microsoft/vscode#96833]
- VSCode Version: 1.44.2
- OS Version: Catalina 10.15.4

Steps to Reproduce:
I don't know how to reproduce the bug, but since 1 week or 2, my files don't appear anymore in Visual's file explorer. I have to delete my entire folder and re-clone the project from git... 

The bug appears quite often... 

![May-02-2020 16-23-23](https://user-images.githubusercontent.com/23353836/80866981-f82bfb80-8c91-11ea-8211-22e87dfb092b.gif)
![May-02-2020 16-23-51](https://user-images.githubusercontent.com/23353836/80866987-011ccd00-8c92-11ea-99de-bba951797712.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by viclafouch** [comment]
### I don't have any other duplicate project, that the only one.. I just don't understand what is going on with my Visual.. :/ 

Step on this video : 

* I found my files with the native explorer (without Visual)
* I didn't  find my files with the explorer (Open in Finder with Visual)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23353836/80867428-31fe0180-8c94-11ea-8a60-4dae6cb3072c.gif)

**Comment by viclafouch** [comment]
A have again this bug today... wt* is going on ^^

![image](https://user-images.githubusercontent.com/23353836/80920021-6bef0680-8d6d-11ea-9e03-a75f31621811.png)

**Comment by viclafouch** [comment]
I've just reproduced the bug..

https://youtu.be/3e9X6ErFMqo

**Comment by viclafouch** [comment]
I have already `Clear editor history` and that didn't work.

Look at this video, we can see that, apparently, I have multiple version of my project when I'm browsing different files. I can't just work :( 

The video : https://youtu.be/0inL0t2tFx8

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
