### ISSUE TITLE
Javascript suggestions not working

### ISSUE THREAD

**Issue by ssdtrdhinesh** [microsoft/vscode#96839]
Issue Type: <b>Bug</b>

Whenever I have hit the ctrl+space, VS Code doens't show the related varialbes/methods as suggestion.

Really hard to work on this editor, even tried uninstalling and installing it.
Added jshint extenstion - nothing works out.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.93GB (0.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.21
vscode-icons|vsc|10.1.1

</details>

![image](https://user-images.githubusercontent.com/11424605/80872788-29b1c080-8cac-11ea-97cd-973ad8438337.png)

**Comment by mjbvz** [comment]
Please share code that reproduces the problem (as text, not screenshots)
