### ISSUE TITLE
[loc][Query][DevDiv] Pelase clarify "Balance"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#9683]
Hi, we have a query from our translator. Can you help pleasE? Thanks!

Source:
Emmet: Balance (inward)

File Name:
src\vs\workbench\parts\emmet\node\actions\balance.nls.resx

Resource ID:
".resx", 0; "balanceInward"

Query:
What exactly is meant by "balance"?  	DE_Translator2	7/21/2016 9:53:34 PM

**Comment by egamma** [comment]
Balancing is meant in the sense that after executing the action you have a matching tag on both sides of the selection.

This is the full explanation.
http://docs.emmet.io/actions/match-pair/
