### ISSUE TITLE
Test: 'Variable paging'

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#9684]
Test for #9537:

- [x] macOS - **@joaomoreno**
- [x] windows - **@kieferrm**

Previously large data structures (Array, Buffer, Map, Set) were broken into "chunks" in the debug extension. Starting with VS Code 1.4 this is done on the VS Code side so all the debug extensions will benefit from this.

Write or use a js/ts program with an array/buffer/map/set with more than 100 items and verify:

* data structures with a large number of children are displayed in chunks (these chunks are displayed collapsed and the children are fetched lazily on expand).
* Array, Buffer, Map, and Set also display programmatically added named properties.  
* you can inspect these large data structures in: the VARIABLES view, WATCH expressions, REPL, and hover

**Comment by joaomoreno** [comment]
@Tyriar @isidorn This test plan needs two testers at least.
