### ISSUE TITLE
npm debugger timeout parameter shift breakpoints activation

### ISSUE THREAD

**Issue by xrobert35** [microsoft/vscode#96842]
- VSCode Version: 1.44.2
- OS Version: Ubuntu 20.04

Hello,

I try to launch an **npm script** to launch a node server thanks to webpack (using the nestjs cli).

here is the base configuration 

```json
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Api",
      "runtimeExecutable": "npm",
      "cwd": "${workspaceFolder}/packages/apis",
      "runtimeArgs": ["run-script", "api:start"],
      "autoAttachChildProcesses": true,
      "port": 9229,
      "outputCapture": "std",
      "restart": true,
    }
```

This run the "api:start" script :

```
"api:start": "nest start api --debug --watch"
```

The is problem is, this script need more than **10 seconds** to make the debugger available. 

![image](https://user-images.githubusercontent.com/33020856/80892024-35ab7b80-8cc8-11ea-8903-e76b6277f56e.png)

So I got this message : 

![image](https://user-images.githubusercontent.com/33020856/80892041-5bd11b80-8cc8-11ea-94e7-ac4d2da336da.png)

The application is launched in the background but the debugger is not attached. 

**Solution**  I added the **timeout** parameter and set it to 15 seconds.

```    {
      "type": "node",
      "request": "launch",
      "name": "Launch Api",
      "runtimeExecutable": "npm",
      "protocol": "inspector",
      "cwd": "${workspaceFolder}/packages/apis",
      "runtimeArgs": ["run-script", "api:start"],
      "autoAttachChildProcesses": true,
      "timeout": 15000,
      "port": 9229,
      "outputCapture": "std",
      "restart": true
    },
```

![image](https://user-images.githubusercontent.com/33020856/80892066-9dfa5d00-8cc8-11ea-84f4-9a37689680f3.png)

As you can see the **debugger is well attached** and I can set breakpoint, the hot reload is working great (debugger reattached himself and so on) really nice.

**The real problem** is that thoses breakpoints will be really activated 15 seconds after the "Debugger attached" is displayed. I have tried with a 45 seconds timeout to be sure i'm not crazy :p and breakpoint are only activated 45 seconds after the message is displayed. So I can't debug the launch of my application. Am I missing something ?

Thanks

Does this issue occur when all extensions are disabled?: Yes

I made a simple test with the first configuration without "timeout" with this script 

```javascript
console.log("Hello");

setTimeout( () => {
    console.log("Hello 4 ");
}, 4000);

setTimeout( () => {
    console.log("Hello 5 ");
}, 5000);

setTimeout( () => {
    console.log("Hello 6 ");
}, 6000);

setTimeout( () => {
    console.log("Hello 7 ");
}, 7000);
```

```
node --inspect script.js
```

And I can only debug "Hello 6" and "Hello 7"

**Comment by connor4312** [comment]
Thanks for the issue, can you enable `"trace": true` in your config and share the log file here?

/needsMoreInfo

**Comment by xrobert35** [comment]
Hello

here is the debug.legacy.txt of the test with the last script posted and breakpoint set and Hello 4 / 5 / 6 / 7  only  6 and 7 worked

[debugadapter-legacy.txt](https://github.com/microsoft/vscode/files/4575546/debugadapter-legacy.txt)

**Comment by connor4312** [comment]
@roblourens it looks like we might be waiting for a paused event for a timeout before initializing the debug session, there's a five second pause before this message is printed:

```
[15:25:34.633 UTC] 1588605934.633: Did not get a pause event after starting, so continuing
[15:25:34.634 UTC] To client: {"seq":0,"type":"event","event":"initialized"}
```

Not sure if you want to tackle it at this point or if there's an easy solution for xrobert.

@xrobert35 you can give [our new debugger](https://github.com/microsoft/vscode-js-debug/blob/master/README.md) a shot which _should_ avoid this issue. We're expecting the new debugger to exit preview within the next few release.

**Comment by xrobert35** [comment]
Using the new debugger seem to fix the problem with the simple script.

However, it's getting worse if I try to debug the webpack app, cause I can't set breakpoint anymore, looks like the debugger doesn't read the sourcemap ?

**Comment by connor4312** [comment]
Can you share the trace logs using the new debugger as well?

**Comment by xrobert35** [comment]
Here is the trace log  of the working simple script

[logsimple.json.txt](https://github.com/microsoft/vscode/files/4576105/logsimple.json.txt)

Here's the trace log of the webpack app (current debugged)
[tracewebpackold.log](https://github.com/microsoft/vscode/files/4576152/tracewebpackold.log)

Here's the trace log of the webpack app (new debugger)  sorry big file  : https://easyupload.io/v8oxs5

Hop this help

**Comment by connor4312** [comment]
Thanks! You can get around this today by manually specifying the `sourceMapPathOverrides` and replacing `${workspaceFolder}` with `${workspaceFolder}/packages/apis`.

I've made a change in the debugger to default to resolving from the `cwd` that should make this scenario work in the future. It will be tonight's nightly build.

**Comment by xrobert35** [comment]
i'm not very familiard with this options, I tried to add it : 

```
      "type": "node",
      "request": "launch",
      "name": "Launch api",
      "runtimeExecutable": "npm",
      "protocol": "inspector",
      "cwd": "${workspaceFolder}/packages/apis",
      "sourceMapPathOverrides": {
        "${workspaceFolder}/*": "${workspaceFolder}/packages/apis/*"
      },
```

or 

```
      "type": "node",
      "request": "launch",
      "name": "Launch api",
      "runtimeExecutable": "npm",
      "protocol": "inspector",
      "cwd": "${workspaceFolder}/packages/apis",
      "sourceMapPathOverrides": {
        "${workspaceFolder}": "${workspaceFolder}/packages/apis"
      },
```
but nothing changed. Perhaps i'm doing it wrong.
Will try on the next insider release

**Comment by xrobert35** [comment]
Ok, it seem to work great with build ```2020.5.417``` of the new debugger 

thank you :)
