### ISSUE TITLE
an error occurred when trying to rename a file in the destination directory movefile failed

### ISSUE THREAD

**Issue by oluwatosinolamilekan** [microsoft/vscode#96848]
![image](https://user-images.githubusercontent.com/29930457/80894619-7dd09b00-8cd4-11ea-99ce-10dd4f3b2891.png)

**Comment by oluwatosinolamilekan** [comment]
Not working

**Comment by joaomoreno** [comment]
Does this happen when you try to install VS Code or when you try to update it?

**Comment by oluwatosinolamilekan** [comment]
Yes.. i had vscode before only that i updated my vscode and an error occur about my extension i wasnt able to use them again to i uninstall and install back then i have getting that error

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by oluwatosinolamilekan** [comment]
it hang to a point anytime i try to install it again and agin
