### ISSUE TITLE
Flutter hot reload during debug stepping

### ISSUE THREAD

**Issue by mrgnhnt96** [microsoft/vscode#96841]
Issue Type: <b>Bug</b>

When I am stepping through my code during debug, if I accidentally hot reload my app and then press continure the app will freeze and will not reload. VS Code will say that is is syncing files with the app and if you try to hot reset the app it will say "reload already in progress" and will not let me continue. The only way that I have found to get around this bug is to completely stop my app, and run it again.

STEPS TO REPRODUCE:
Flutter run app
add breakpoint
hot reset
when breakpoint is hit, click hot reload
try pressing hot reset

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|26, 45, 26|
|Memory (System)|16.00GB (0.77GB free)|
|Process Argv|-psn_0_163880|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
increment-selection|alb|0.2.0
Bookmarks|ale|11.1.0
pubmanager|bco|0.0.13
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.0.29
dart-code|Dar|3.10.0
flutter|Dar|3.10.0
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
carbon-now-sh|eri|1.2.0
prettier-vscode|esb|4.5.0
vscode-flutter-i18n-json|ess|0.28.0
vscode-todo-plus|fab|4.17.0
git-project-manager|fel|1.7.1
bloc|Fel|3.5.0
kotlin|fwc|0.2.11
vscode-pull-request-github|Git|0.15.0
flutter-stylizer|gml|0.0.16
vscode-flutter-files|gor|2.1.1
vue|jcb|0.1.5
pubspec-assist|jer|1.0.2
vscode-rufo|jnb|0.0.1
vscode-gutter-preview|kis|0.26.1
syntax-project-pbxproj|mar|0.1.3
Kotlin|mat|1.7.1
metago|met|3.7.0
git-graph|mhu|1.22.0
flutter-widget-wrap|mrg|1.0.0
hive-object-converter|mrg|0.1.2
python|ms-|2020.4.76186
cpptools|ms-|0.27.1
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2104
gradle-language|nac|0.2.3
incrementor|nms|0.1.0
indent-rainbow|ode|7.4.0
dart-syntax-highlighting-only|osc|1.0.1
vscode-yaml-sort|Pas|2.3.1
open-html-in-browser|pea|2.1.2
material-icon-theme|PKi|4.1.0
ruby|reb|0.27.0
java|red|0.61.0
vscode-xml|red|0.11.0
vscode-yaml|red|0.7.2
vscode-open|san|0.1.0
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
todo-list|Tza|1.6.0
highlight-matching-tag|vin|0.9.9
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2
vscode-icons|vsc|10.1.1
vscode-wakatime|Wak|4.0.0
vscode-todo-highlight|way|1.0.4
vscode-ruby|win|0.27.0
flutter-stateful-widget-generator|yum|0.0.2
markdown-all-in-one|yzh|2.8.0
propertylist|zho|0.0.2

</details>

**Comment by isidorn** [comment]
Please file against the flutter extension. Thanks!
