### ISSUE TITLE
Working Copy in Notebook

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#96840]
Notebook is similar to Custom Editor in terms of Working Copy. With https://github.com/microsoft/vscode/issues/95854, we aligned the API between Notebook and Custom Editor for `save`/`backup`/`revert`.

```ts
export interface NotebookContentProvider {
    open(uri: Uri): NotebookData;
    save(document: NotebookDocument, cancellation: CancellationToken): Thenable<void>;
    saveAs(targetResource: Uri, document: NotebookDocument, cancellation: CancellationToken): Thenable<void>;
    readonly onDidChange: Event<void>;
    revert(document: NotebookDocument, cancellation: CancellationToken): Thenable<void>;
    backup(document: NotebookDocument, cancellation: CancellationToken): Thenable<CustomDocumentBackup>;
}
```

However, the major difference between Notebook and Custom Editor is, the notebook document is pretty close to `CustomTextEditor` which is serializable (the core defines the schema) and the renderer proc has the source of truth. It's a bit close to `CustomBinaryEditor` only in a specific case: the notebook has an output which is an interactive widget (rendered in the webview then) and the notebook provider wants to save its state.

Take GH Notebook and Kusto Notebook as examples, the document consists of a list of cells and some metadata. They can serialized and restored without delegating it to the notebook content providers. With #96810 , every cell in the notebook document will hold a text buffer, the document's data structure is as below

```markdown
NotebookDocument
  - Cell
    - textBuffer (`PieceTreeTextBuffer`)
    - metadata (Key-Value pairs)
    - outputs (JSON object)
  - Cell
  - Cell
```

Hot Exit and Revet can be implemented by creating snapshots from the notebook document, which under the hood is creating snapshots from `PieceTreeTextBuffer` and serializing metadata. For example, the snapshot will be like 

```markdown
[ { textBufferSnapHost (`PieceTreeSnapshot`), metadata, outputs } ]
```

`Save` and `SaveAs` are still delegated to the notebook provider as we are not sure how to mix Markdown cell and Code cell in the same document. For most generic notebook document provider, its shape will be 

```ts
export interface NotebookContentProvider {
    open(uri: Uri): NotebookData;
    save(document: NotebookDocument, cancellation: CancellationToken): Thenable<void>;
    saveAs(targetResource: Uri, document: NotebookDocument, cancellation: CancellationToken): Thenable<void>;
    readonly onDidChange: Event<void>;
}
```

Only when the notebook provider is in favor of storing the intermediate states of outputs rendered in the webview (say `ipywidgets`), it needs to implement two optional delegates 

```diff
+  revert(document: NotebookDocument, cancellation: CancellationToken): Thenable<void>;
+  backup(document: NotebookDocument, cancellation: CancellationToken): Thenable<CustomDocumentBackup>;
```

Considering that the difference is relatively small (compared to Custom Editor), we can just make `backup/revert` optional instead of having explicit separation between `*TextEditor` and `*BinaryEditor`. 

@bpasero @jrieken @mjbvz a short summary is 

* `save/saveAs` are delegated to notebook content provider
* the core is responsible for backup most of the time and in runtime the core has the source of truth
* notebook content provider overrides `backup/revert` only when it cares about the state of webview outputs.

Does this make sense to you?

**Comment by bpasero** [comment]
Not sure I fully understand, but are you suggesting that the state of webview output should be part of backups? My naive assumption would be that the working copy for notebooks would only care about the text models but not the output assuming that this can be produced simply by opening the notebook and running the cells?

**Comment by rebornix** [comment]
> but are you suggesting that the state of webview output should be part of backups 

For some scenarios, the extension (Jupyter) does want to save the intermediate state of widgets in the webview or the state in the kernel (running in another process) into the file on disk. I'm suggesting only in this case we delegate `backup`/`revert` to the notebook provider. For all other cases, it's handled by the working copy service.

**Comment by mjbvz** [comment]
For cases like Jupyter, won't the extension also also need to know about undo/redo? Is this already part of the API?

**Comment by bpasero** [comment]
I would probably think that:
* all the textual state of the notebook (e.g. each cells input) goes into [`IWorkingCopyBackup.content`](https://github.com/microsoft/vscode/blob/756849af07555b1e8b76883319414a300a59c4ed/src/vs/workbench/services/workingCopy/common/workingCopyService.ts#L40) as snapshot
* any output state is likely extension dependent and probably needs to be backed up by the extension

We have a similar model for custom editors where we only persist metadata on the workbench side and ask the extension to backup the rest because we cannot know what needs to be backed up.

**Comment by rebornix** [comment]
> For cases like Jupyter, won't the extension also also need to know about undo/redo? Is this already part of the API?

@mjbvz we don't know the answer yet as it's unknown yet what *Undo/Redo* means after you execute a cell and receive outputs since you can't "Undo" the execution (which has side effects in the kernel).

Previously we were thinking of using `NotebookContentProvider.onDidChangeNotebook` to trigger dirty state change, with which extensions can decide if outputs changes should trigger save events or not. 

> all the textual state of the notebook (e.g. each cells input) goes into IWorkingCopyBackup.content as snapshot
> any output state is likely extension dependent and probably needs to be backed up by the extension

@bpasero this aligns with my mental model of how would notebook providers handle output state. For notebooks which don't care about output states, everything is textual and we can handle them in the renderer (by snapshot). For Jupyter notebook, it requires delegate to the notebook provider.

**Comment by rebornix** [comment]
@mjbvz I thought about it again and read how CustomBinaryEditor handles undo/redo, I think we can follow the same pattern and mix it with textural change managed by the renderer:

When users make changes to the content in a cell, add/delete cells, we manage the undo/redo stack in the core.

After an execution, if the extension just return outputs, we can wrap the change in an undo/redo point. Extensions can use a metadata `trackOutputs` (need a better name)  to control if they want to exclude output changes from  undo/redo/backup. For example, GH NB will set `"trackOutputs": false` to avoid dirty content change after execution.

For Jupyter notebook, since they want to track the undo/redo element after execution, they can set `"trackOutput": false` and push their own undo redo stack by 

```diff
interface NotebookDocumentEditEvent {
    readonly document: NotebookDocument;
    undo(): Thenable<void> | void;
    redo(): Thenable<void> | void;
    readonly label?: string;
}

They can assign outputs to a code cell and update its own internal states, etc. And when users undo, they are responsible for reverting the outputs changes.
export interface NotebookContentProvider {
+    readonly onDidChange: Event<NotebookEditEvent>;
}
```
