### ISSUE TITLE
Webview: Enable the use of localStorage property from window

### ISSUE THREAD

**Issue by M-Widman-Mesh** [microsoft/vscode#96843]
Would like to revisit issue[#48464](https://github.com/Microsoft/vscode/issues/48464#event-1672093568).

My question is: 
Has there been any additional discussion about allowing the use of LocalStorage in the Webview? Would be really awesome if we could have some type of option to allow this! 

Our primary use is that within our web application we use firebase and firebase requires localStorage in order to function properly.

**Comment by mjbvz** [comment]
Unfortunately this is not something we can really workaround. For security reasons, we run each webview in its own data origin and that prevents access to localStorage
