### ISSUE TITLE
Do not show `Sign in with Github` if user has already signed into Github

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#96845]
<img width="638" alt="image" src="https://user-images.githubusercontent.com/10746682/80893774-a1481580-8cd5-11ea-8686-3f6a6898451b.png">

**Comment by sandy081** [comment]
@RMacfarlane Is it possible to sign into another GitHub account as an extension or is it restricted to only one GitHub account?

**Comment by sandy081** [comment]
Looks like @RMacfarlane added this support.

**Comment by RMacfarlane** [comment]
Oh, yes, sorry, there was another issue tracking this.

**Comment by sandy081** [comment]
To verify:

- Turn on Settings Sync using Github account
- Turn off Settings Sync
- Turn on Settings Sync again
- Make sure you see only one entry for Github account but not both
  - either last used with sync or
  - Sign in with Github
