### ISSUE TITLE
[javascript] "Unreachable code detected" after return statement inside catch block of class member anonymous function

### ISSUE THREAD

**Issue by Nu11u5** [microsoft/vscode#96847]
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:50:03.709Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.19.113-08528-g5803a1c7e9f9

### Steps to Reproduce:

Paste the sample code into a new javascript file:

``` javascript
//@ts-check

class Test1 {
    constructor() {
        const someValue = function () {
            try {
                return true;
            }
            catch (e) {
                return false; // return statement inside catch block
            }
        }();

        // "Unreachable code detected" below this line
        const anotherValue = function () {
            return true;
        }();

        this.property = someValue && anotherValue;
    }
}


class Test2 {
    constructor() {
        const someValue = function () {
            try {
                return true;
            }
            catch (e) {}
            return false; // return statement outside catch block
        }();

        // No "unreachable code" error
        const anotherValue = function () {
            return true;
        }();

        this.property = someValue && anotherValue;
    }
}
```

### Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by IllusionMH** [comment]
This is TS issue https://github.com/microsoft/TypeScript/issues/36828 that already fixed upstream in TS3.9 (and I think will be available in 1.45)

You can use https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next extension`` which provides nightly builds with the fix.
