### ISSUE TITLE
VSCode survey doeesn't show if I configure the target URL as a trusted domain

### ISSUE THREAD

**Issue by patricio-ezequiel-hondagneu-roig** [microsoft/vscode#96855]
1. Open VSCode
2. Receive a notification suggesting me to do a quick survey
3. Clicking the link to the survey
4. VSCode warns me that the target URL is not a trusted domain
5. I click to configure the survey's URL as a trusted domain
6. The URL is added to the list of trusted domains, but the survey is not opened in my browser and I can't find how to trigger that survey again

**Comment by Tyriar** [comment]
FYI @sana-ajani

**Comment by JacksonKearl** [comment]
Fixed bug where selecting "Trust this domain" or "Trust this domain and all subdomains" wouldn't open the domain.
Additionally, added a notification for what domain you tried to open w/ option to copy for when you "Manage trusted domains" in the editor. 

![image](https://user-images.githubusercontent.com/8586769/82085932-98c2e800-96a2-11ea-91e1-adbde1eae005.png)
