### ISSUE TITLE
Add scope to integrated terminal

### ISSUE THREAD

**Issue by ryuta69** [microsoft/vscode#96854]
I'd like to add scope to terminal, and tried to make PR, but i found this PR https://github.com/microsoft/vscode/pull/54911 .

It says 'Thanks for the PR. However we prefer to first discuss features before just coding.', so I'd like to discuss.

My purpose is only to add `fontStyle: italic` to terminal, while I think this would be also good for theme creators.

**Comment by Tyriar** [comment]
> My purpose is only to add fontStyle: italic to terminal

Sorry but I don't think we should add a setting like this because terminal programs determine when to write italic text (eg. `echo -e '\x1b[3m'`).

**Comment by ryuta69** [comment]
okay, thank you.
