### ISSUE TITLE
VScode writing commit checksum to file if changes aren't accepted

### ISSUE THREAD

**Issue by thefattestcat** [microsoft/vscode#96858]
Steps to Reproduce:

1. Not accepting changes to current file.

VSCode:
![image](https://user-images.githubusercontent.com/48980192/80908538-c475d200-8d74-11ea-87c1-e46bf8c1df77.png)

Git repo:
![image](https://user-images.githubusercontent.com/48980192/80908565-f0915300-8d74-11ea-9c42-b4f413509cde.png)

**Comment by joaomoreno** [comment]
That is a merge conflict marker which you have committed by accident.
