### ISSUE TITLE
Can't install any extentions behind a corporate proxy

### ISSUE THREAD

**Issue by vborzykin** [Microsoft/vscode#9685]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:
1. Open extentions
2. Wait loading @popular
3. Press install on any extention
4. Nothing happened, after 10 minutes waiting

my proxy setup is (from user's settings.json):
"http.proxyStrictSSL":false,
"http.proxy": "http://user:pass@webproxy:3128/",
"https.proxy": "https://user:pass@webproxy:3128/",

![2016-07-25_15-34-30](https://cloud.githubusercontent.com/assets/720193/17095191/6dc67512-527d-11e6-95d9-02be8d3280b8.gif)

**Comment by generelspaz** [comment]
+1 Same behavior here

**Comment by joaomoreno** [comment]
@vborzykin Can you try using the [latest Insiders build](http://code.visualstudio.com/insiders), see if you get any errors?

**Comment by vborzykin** [comment]
@joaomoreno, I can.
Proxy settings are already defined.
![code - insiders_2016-07-26_14-09-12](https://cloud.githubusercontent.com/assets/720193/17129020/b7b7f44e-533a-11e6-9fb9-8b995099a0a1.png)

**Comment by joaomoreno** [comment]
407 means proxy authentication required.

Are you **sure** you have the right user name and password in the URL? Note that any special characters need to be [properly escaped](http://stackoverflow.com/a/6172831/261019).

One way to verify whether you have the right value is to run something like the following snipped in the command line. In the following example, the password has the `@` special character:

```
$ node -p 'require("url").parse("http://user:pass%40123@webproxy:3128/")'
Url {
  protocol: 'http:',
  slashes: true,
  auth: 'user:pass@123',
  host: 'webproxy:3128',
  port: '3128',
  hostname: 'webproxy',
  hash: null,
  search: null,
  query: null,
  pathname: '/',
  path: '/',
  href: 'http://user:pass%40123@webproxy:3128/' }
```

**Comment by vborzykin** [comment]
Can you can say URL and file extention?
Maybe, our proxy block connection by them.

**Comment by joaomoreno** [comment]
And you still get 407? Just triple check that your credentials are OK and the settings are OK too. 407 is a configuration problem.

Also what do you get when running this from a Command Prompt?

```
reg query "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ProxyServer"
```

Finally, if you want to _sideload_ an extension you can download it from the Marketplace (https://dbaeumer.gallery.vsassets.io/_apis/public/gallery/publisher/dbaeumer/extension/vscode-eslint/0.10.17/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage) and simply open it in Code with `File > Open`.

**Comment by vborzykin** [comment]
@joaomoreno 
I still get 407 error. I already rechecked my credentials hundreds time and all of them OK. 

> reg query "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ProxyServer"
Error: Unable to find the specified key or value in the registry.

**Comment by joaomoreno** [comment]
Do you have a systems administrator in your corp environment that could help you out with this?

**Comment by joaomoreno** [comment]
Closing in favor of #22214
