### ISSUE TITLE
[Cosmetic] [Minimap] Minimap shadow does not show in lower split

### ISSUE THREAD

**Issue by awilkins** [microsoft/vscode#96861]
- VSCode Version: 1.44.2
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Make a 2x2 split editor layout

Minimap doesn't render a shadow in the lower set of splits.

![Screenshot from 2020-05-03 10-32-51](https://user-images.githubusercontent.com/368399/80910795-f3b32180-8d29-11ea-933c-141a8fab16e6.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
The minimap only renders a shadow when there is content under it, i.e. when the file has a horizontal scrollbar and the scrollbar is not all the way to the right.
