### ISSUE TITLE
Remote WSL with SSH support for GitHub

### ISSUE THREAD

**Issue by AtlasRW** [microsoft/vscode#96864]
Issue Type: <b>Feature Request</b>

Hi, since I'm using Remote WSL on VS Code, each time I try to Push/Pusll/Sync on my GitHub repositories I get asked my GitHub Username/Password, either using VS Code GUI commands or bash CLI commands.
Even after trying to configure SSH a thousand different ways in my WSL distro (Kali Linux), I found no way to fix this.
Please help, I'm desperate at this point. Thank you for your time.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

**Comment by alexr00** [comment]
Check out the insiders build, we now will prompt for sign in through GitHub if you try to push/pull/sync.
