### ISSUE TITLE
Markdown syntax highlighting doesn't cover links with deferred urls if it contains spaces

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#96867]
`[Fira Code]` should be highlighted just like `[Iosevka]`

![image](https://user-images.githubusercontent.com/2193314/80915376-da4cae00-8d06-11ea-8b68-44454e0e8692.png)

**Comment by mjbvz** [comment]
Closing due to lack of further user interest expressed in this.

I'm concerned that we could introduce false positive link highlighting by trying to support this using text mate grammars. Proper support would use semantic highlighting instead but again, we want to see more user interest in this
