### ISSUE TITLE
Add limelight like hyperfocus to zen mode

### ISSUE THREAD

**Issue by ce3a** [microsoft/vscode#96865]
For even less destruction in zen mode, it would be great to have only the current code section highlighted. Similar to the [limelight](https://github.com/junegunn/limelight.vim) plugin in vim. Here is an example:

![Peek 2020-05-03 13-02](https://user-images.githubusercontent.com/5941722/80912620-82319e00-8d3e-11ea-953f-572d9912ec3e.gif)

Any chance we can get a "hyperfocus zen mode" in future versions of VSCode?

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by nicofranzp** [comment]
I've been looking for the same thing for months now. It would be great to have this feature
+1

**Comment by RewardedIvan** [comment]
For anyone still looking for an extension that can do the same thing [this](https://marketplace.visualstudio.com/items?itemName=IvoBarros.vs-focus) might do it for you.

**Comment by sirdeniel** [comment]
This feature increases productivity, I think this is a must-have
