### ISSUE TITLE
jupiter not closed

### ISSUE THREAD

**Issue by tahavs** [microsoft/vscode#96869]
Issue Type: <b>Bug</b>

i want to get out jupiter text formating that assigned wrongly to my .txt format file... but format selecting icon in blue bar underneath is disapear

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.65GB (14.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
gitlab-workflow|fat|2.2.0
php-intellisense|fel|2.3.14
auto-rename-tag|for|0.1.2
code-runner|for|0.10.0
vue-snippets|hol|0.1.11
beautify|Hoo|1.5.0
reg|ion|1.0.1
sublime-babel-vscode|jos|0.2.10
react-native-snippet|jun|0.5.6
gitlab-notifications|log|0.0.8
Angular-BeastCode|Mik|8.1.2
python|ms-|2020.4.76186
cpptools|ms-|0.27.1
vscode-typescript-tslint-plugin|ms-|1.2.3
vetur|oct|0.24.0
laravel-blade|one|1.21.0
laravel5-snippets|one|1.8.0
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1

(4 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
You can disable the extension which contributes Jupiter text format.
