### ISSUE TITLE
Ctrl+W vs. Ctrl+F4

### ISSUE THREAD

**Issue by daniel-liuzzi** [microsoft/vscode#96862]
Issue Type: <b>Bug</b>

According to [Keyboard shortcuts for Windows](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf), both <kbd>Ctrl</kbd>+<kbd>W</kbd> and <kbd>Ctrl</kbd>+<kbd>F4</kbd> close the editor. Default keybindings support this, as both shortcuts bind to the `closeActiveEditor` command.

_In theory_ both shortcuts should do the exact same thing. In practice, however, they behave differently:

- <kbd>Ctrl</kbd>+<kbd>W</kbd> closes the window when empty
- <kbd>Ctrl</kbd>+<kbd>F4</kbd> does not

I'm not sure whether this is by design, but I found it somewhat confusing.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

**Comment by daniel-liuzzi** [comment]
@bpasero and @alexr00, perhaps my phrasing wasn't all that clear, and this made the triage bot think I'm asking question. I am certainly not; I meant to report what appears to be a bug. I have now edited my original post to reflect this. Kindly consider reopening this issue. If you need more information, I'll be more than happy to to provide it. Thanks.

**Comment by bpasero** [comment]
i am not sure about that reference you mention but if you check the keybindings editor you can see the `Ctrl+W` closes the window when no editor is open:

![image](https://user-images.githubusercontent.com/900690/81492445-f7015c80-9297-11ea-8e81-3269318f6b22.png)

You can configure that.

**Comment by daniel-liuzzi** [comment]
Oh, I see it now. By default, both Ctrl+W and Ctrl+F4 bind to `View: Close Editor`, but Ctrl+W happens to also bind to `Close Window` (whereas Ctrl+F4 does not.) I wasn't even aware a single shortcut could bind to multiple commands. Thanks for clarifying this!
