### ISSUE TITLE
Add Net Promoter Score feedback support

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#9686]
CC @seanmcbreen 

fwlink to the survey: http://go.microsoft.com/fwlink/?LinkId=823149

**Comment by joaomoreno** [comment]
We should propose the user to answer the NPS score after a **fixed amount** of **sessions**. The proposal should occur with a certain degree of **probability**. If the survey happens to not be shown, it will not be shown again to this user. The user can opt to either get asked again later or not get asked again.

- A **session** is an execution of VSCode, capping at the maximum of **one per day**.
- The survey should be proposed at the **9th** session.
- The probability of being proposed is **15%**.
- If the user requests to do the survey later, we should propose it at the **12th**, **15th** session, etc.
- Any of following outcomes will result in never asking the user again (until we release a new version that overwrites this):
 - User clicks the **Don't ask again** button
 - User clicks the **Yes, let's answer the survey** button
 - User is part of the **85%** of users that didn't get selected for the survey proposal

**Comment by egamma** [comment]
@joaomoreno this captures well what we discussed, but I defer to @seanmcbreen since he did the spec.

**Comment by joaomoreno** [comment]
Pushed 5bcde31162bba1091435c5ad6c59c5f0c4de039e containing the logic described above. [nps.contribution.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/nps.contribution.ts) is the interesting part.

**Comment by joaomoreno** [comment]
I've also set the `npsSurveyUrl` key in the `product.json` of both **stable** and **insiders**, in the distro repo. Should it be the same URL, @seanmcbreen?

I'll assign this to someone, needs a code review.

**Comment by joaomoreno** [comment]
@jrieken Can you review? Let me know if you'd like me to run you through the code, might be easier.

**Comment by joaomoreno** [comment]
@jrieken I take it back, I'll just create a test plan item and let it be assigned. No op here.

**Comment by Tyriar** [comment]
Verified in https://github.com/Microsoft/vscode/issues/9690
