### ISSUE TITLE
Tsc -p does not properly register tsconfig.json file

### ISSUE THREAD

**Issue by CG-Tespy** [microsoft/vscode#96870]
Issue Type: <b>Bug</b>

A followup to this: https://github.com/microsoft/vscode/issues/95613
The solution offered was passing the file using the tsc -p command, but it didn't quite work. 

Steps to reproduce:
Create a project with a tsconfig.json file with these contents:
```
{
  "compilerOptions": {
    "target": "es6",                          
    "module": "commonjs",                     
    "strict": true,                          
    "esModuleInterop": true,                  
    "forceConsistentCasingInFileNames": true 
  }
}
```

To that project, add a Person.ts file with these contents:
```
class Person
{
    FirstName: string = "";
    LastName: string = "";

    get FullName() { return `${this.FirstName} ${this.LastName}`; }

    constructor(firstName?: string, lastName?: string)
    {
        this.FirstName = firstName || "";
        this.LastName = lastName || "";
    }
}
```

In the terminal, run "tsc -p tsconfig.json"
Then run "tsc Person.ts"
There should be an error that says "error TS1056: Accessors are only available when targeting ECMAScript 5 and higher."

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (9.70GB free)|
|Process Argv|D:\Documents\Programming\TypeScriptSandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-npm-script|eg2|0.3.11
docomment|k--|0.1.9
node-module-intellisense|lei|1.5.0
vscode-language-babel|mgm|0.0.27
csharp|ms-|1.21.17
tsimporter|pmn|2.0.1
unity-debug|Uni|2.7.5

</details>

**Comment by spahnke** [comment]
You only need to run `tsc -p tsconfig.json` which already compiles your `Person.ts` file (or even simpler just run `tsc`). In fact you *must not* run `tsc Person.ts` otherwise this won't work. Also, this is no issue with Visual Studio Code but a question regarding the usage of the TypeScript compiler. You would get the same results when you follow your own steps on the Windows command line instead of the integrated terminal. I suggest you read up on the TypeScript documentation [here](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html).

**Comment by CG-Tespy** [comment]
Ah, I see. You're right, and thank you for the link to the documentation
