### ISSUE TITLE
Tweet your feedback dialog box says 'Show Feedback Smiley in Status Bar' when there's actually a different icon than a smiley that's in the status bar

### ISSUE THREAD

**Issue by abhishekwl** [microsoft/vscode#96878]
- VSCode Version: 1.44.2
- OS Version: Linux x64 5.4.0-7626-generic

Steps to Reproduce:

1. Launch VS Code
2. Tap the icon the left of the bell icon on the bottom right. It opens up a dialog box
3. At the bottom of this dialog box, there's a checkbox that says 'Show Feedback Smiley in Status Bar'

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Changed to "Show Feedback Icon in Status Bar"
