### ISSUE TITLE
Parenthesis added to links when clicked

### ISSUE THREAD

**Issue by jadchaar** [microsoft/vscode#96876]
- VSCode Version: 1.44.2
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. Run `python3 -m http.server`
2. Cmd + click the link in the parentheses provided in the "Serving" prompt that is printed:
<img width="436" alt="Screen Shot 2020-05-03 at 12 50 41 PM" src="https://user-images.githubusercontent.com/7388203/80920273-b5732d80-8d3c-11ea-9cac-be9645288f39.png">

When the browser pops up with the clicked link, `http://0.0.0.0:8001/)` is pasted into the URL bar and the page fails to load due to the parenthesis.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is fixed if you use `"terminal.integrated.experimentalLinkProvider": true` in the upcoming version. Check out the release notes when it goes out probably later this week.
