### ISSUE TITLE
Intellisense/Autocompletion initial scroll position problem

### ISSUE THREAD

**Issue by andreialecu** [microsoft/vscode#96872]
Issue Type: <b>Bug</b>

I'm attaching a recording below:

![mUwfXkf8nc](https://user-images.githubusercontent.com/697707/80917110-8cb35e00-8d65-11ea-9234-3dd4d844f33e.gif)

I'm pressing `ctrl+space`. 

Depending on whether the cursor is immediately after the `{` or at least one space after, the scroll position of the completion list will be different.

The options are still at the top of the list in the second case, but it's inconvenient having to scroll up every time.

I feel like this may have already been reported but I couldn't find anything. Hopefully this can be improved.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.84-microsoft-standard
Remote OS version: Linux x64 4.19.84-microsoft-standard
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (2.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|Memory (System)|9.73GB (1.05GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|Memory (System)|9.73GB (1.05GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|Memory (System)|9.73GB (1.05GB free)|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Self contained repro:

```ts
function foo(a: { x: string }) { }

foo({ })
```

**Comment by jrieken** [comment]
What's your value for the `editor.snippetSuggestions`-setting?

**Comment by andreialecu** [comment]
![image](https://user-images.githubusercontent.com/697707/81042455-d3659d00-8eb8-11ea-9a4c-23d4856740ed.png)

**Comment by andreialecu** [comment]
Interestingly, in the self contained repro by @mjbvz above, it does open to the top when a space is present, but unrelated snippets still appear:

![image](https://user-images.githubusercontent.com/697707/81042727-6b638680-8eb9-11ea-9f28-df87909ece33.png)

![image](https://user-images.githubusercontent.com/697707/81042748-76b6b200-8eb9-11ea-8331-f968198e4b6a.png)

**Comment by jrieken** [comment]
> , it does open to the top when a space is present, but unrelated snippets still appear:

YEah, that's what I am seeing as well...

@andreialecu Please try this:

* show intellisense, make sure the details window also shows
* press `ctrl+?`. it will change the details window to a "debug" view
* check the `sortText` properties of snippets and other suggestions

**Comment by andreialecu** [comment]
Somehow I cannot seem to reproduce it today. I'm not sure what is missing. I feel this starts happening randomly a few hours into usage. 

Here's something interesting though that may be related and is also odd:

![vBP5nEpHSm](https://user-images.githubusercontent.com/697707/81043324-b7fb9180-8eba-11ea-94c7-6ec7caf03047.gif)

Simply pressing space when intellisense is open after a single space makes it show a third list of unrelated suggestions.

**Comment by andreialecu** [comment]
> * press `ctrl+?`. it will change the details window to a "debug" view

I cannot seem to open this debug view. `?` is `shift+/` on the keyboard so I have to press `ctrl+shift+/` for `ctrl+?` if that is relevant.

**Comment by andreialecu** [comment]
FWIW: the sort was correct in my initial recording, it was just that the list would open with a scroll position that was in the middle of the list. I had to keep `PGUP` pressed on the keyboard to go to the top and see the actual relevant members.

**Comment by andreialecu** [comment]
Here's an example from today where it doesn't open to the top:

There is an `_id` property above at index 0 in the list, but it opens at index 1.

![s8tSvxTAsu](https://user-images.githubusercontent.com/697707/81044470-1590dd80-8ebd-11ea-8e82-b931f3f33946.gif)

This somehow seems to get exacerbated under certain circumstances that I'm not sure about.

**Comment by andreialecu** [comment]
Here's an instance where this happens in the opposite way:

![image](https://user-images.githubusercontent.com/697707/81045470-f1360080-8ebe-11ea-869a-e8a85864f0c9.png)

Notice how right after `{` it opens up in the middle of the list, but after a space it's at the top.

**Comment by jrieken** [comment]
> Maybe it's possible it drifts one scroll position downwards under certain circumstances until after enough time it ends up in the middle of the entire list.

No. That's on purpose. The editor remembers that for a certain context a certain completion has been selected in the past it will reveal that. You control this via the `editor.suggestSelection` setting

**Comment by andreialecu** [comment]
I understand. Then that's the only recording where it might be working properly. :)

What could be happening is that I may have accidentally triggered a snippet in the past in the context of that completion and it remembered it, so it opened it there. But I can't seem to reproduce it currently.

Also, is there any particular reason why snippets are included in the dropdown when it opens after whitespaces but not directly after `{`? 

And, the third scenario here I assume is indeed a bug: https://github.com/microsoft/vscode/issues/96872#issuecomment-623897299 (After a fourth space, the list just closes entirely.)

**Comment by jrieken** [comment]
> Also, is there any particular reason why snippets are included in the dropdown when it opens after whitespaces but not directly after {?

Yes.  All snippets show when the prefix is whitespace and when having any kind of prefix, only snippets the overlap with that will show. We do that because otherwise snippets would show all the time

**Comment by andreialecu** [comment]
@jrieken here's a repro that I can reproduce very reliably:

![5ftUcgWfHg](https://user-images.githubusercontent.com/697707/81068189-a03b0200-8ee8-11ea-81e9-e98ed25d7099.gif)

```ts
function foo(a: { p: string, pr: string }) {}

foo({p: "", <ctrl+space>})
```

It seems to be important for the property name's first few letters to match the first letters of one of the available snippets.

**Comment by jrieken** [comment]
> @jrieken here's a scenario that I can reproduce very reliably:

Please write precise steps as I am having trouble to follow gifs

**Comment by andreialecu** [comment]
Sorry. Indeed it won't reproduce directly in a new VSCode window. I still think it is related to the first few letters of what it thinks the `context` for that completion should be. My initial report shows similar behavior (it opens at the letter `i`).

If there is any other tracing information I could provide while the issue manifests, let me know.

**Comment by denkquer** [comment]
Glad I found this Issue, I am having the same complaints. It really kills your flow whenever this happens..

**Comment by aminify** [comment]
Why the hell isn't `"editor.suggestSelection": "first"` the default behavior?
After hours of investigating why my typescript suggestion doesn't work I came to this.

PLEASE LET THE USERS DECIDE IF THEY WANT TO GET YOUR SUGGESTIONS.

We as users always get headaches because some fancy guy thinks it's cool to have these stupid options set for everybody.

**Comment by everyonesdesign** [comment]
Should this option have `first` as the default value?

Having it guessing the right option for autocompletion made me multiple times think that the autocompletion is broken and/or there's no relevant options to suggest. The behaviour seems like a bug, and quite a disorienting one.

In case if you're using snippets and are pre-selected with the first option, it's obvious that the list is there, but it's not scrolled. The behaviour seems like a lacking feature (in reality the feature is there, but disabled).

Also, if that option disrupts the flow for some people so much, should there be some small help icon in the corner of the autocomplete menu, allowing to understand what exactly is happening? I googled this issue up, but maybe some people tried to do the same and didn't find it due to other phrasing / other interface languages.

**Comment by jrieken** [comment]
> Should this option have first as the default value?

This actually happened this milestone via: https://github.com/microsoft/vscode/issues/136864. Sorry for not remembering this issue but I believe we are better off now. Closing this as dupe/resolved. Changes are in current insiders and next stable release
