### ISSUE TITLE
Navigation to ts file from html file same as IntelliJ Ultimate

### ISSUE THREAD

**Issue by bms241093** [microsoft/vscode#96871]
Issue Type: <b>Feature Request</b>

I am an angular developer.  My company provides IntelliJ Ultimate for angular development. I am more comfortable with IntelliJ features. But at home i have visual studio for angular development. I am looking for some features of IntelliJ in VS Code. One feature is as follow,
Everytime I have to copy the name of variable or method name from .html then I usually find( ctrl+F ) the same in typescript file.
I am looking for some solution like when i am on html file, if I get any method  or variable name  and press ctrl+mouse , i should redirect to typescript file on same variable or method. 

Angular uses component communication using @Input decorator , @Output decorator and BehaviourSubject during this time any variable from .ts file can be used in any .html file that moment it really creates big problem to find , here IntelliJ works prefectly , just press ctrl+mouse , u will be redirected to the same .ts file , irrespective of the file path. 

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

**Comment by mjbvz** [comment]
Try the angular extensions to see if they provide this functionality
