### ISSUE TITLE
"Check For Updates" doesn't show anything if no editor window opened

### ISSUE THREAD

**Issue by narqo** [Microsoft/vscode#9687]
- VSCode Version:
1.3.1
- OS Version:
MacOS 10.11

Steps to Reproduce:

1. Start VS Code.
2. Close all editor windows.
3. From the toolbar select "Code" → "Check For Updates...".

Nothing will be shown, as it looks like, informational popups only work inside the editor window.

**Comment by kieferrm** [comment]
This works for me on MacOS with 1.3.1 and the insiders build 1.4.0.
