### ISSUE TITLE
Word wrap affected by combining diacritics

### ISSUE THREAD

**Issue by theodore-s-beers** [microsoft/vscode#96880]
- VS Code version: 1.44.2
- OS version: macOS 10.15.4

Steps to reproduce:

1. Enter some text that contains a number of combining diacritics, and is long enough to trigger word wrap (if enabled).
2. On a separate line, enter the same text, normalized to Unicode form NFC.
3. Note the difference in where the wrap occurs.

Does this issue occur when all extensions are disabled?: Yes
Tested in Insiders?: Yes

My apologies if this is a duplicate. I looked at a number of Unicode-related issues but didn't see this in particular.

I've attached a screenshot in which the discrepancy should be clear. The example text is also pasted below.

I guess combining characters—or these ones, at least—are being counted toward the length of the line. This isn't a big deal; the workaround is easy (normalize to NFC); and I have no idea whether it would be worth the effort to make word wrap more "Unicode-aware." But, may as well file it…

```
Text copy-pasted (in part) from WorldCat, probably in form NFD to facilitate search:

Taqī al-Dīn Kāshānī. _Khulāṣat al-ashʿār va zubdat al-afkār: bakhsh-i Khurāsān_. Edited by ʿAbd al-ʿAlī Adīb Barūmand and Muḥammad Ḥusayn Naṣīrī Kahnamūʾī. Tehran: Mīrāṡ-i Maktūb, 2014.

Same text, normalized to NFC:

Taqī al-Dīn Kāshānī. _Khulāṣat al-ashʿār va zubdat al-afkār: bakhsh-i Khurāsān_. Edited by ʿAbd al-ʿAlī Adīb Barūmand and Muḥammad Ḥusayn Naṣīrī Kahnamūʾī. Tehran: Mīrāṡ-i Maktūb, 2014.
```

![wrap](https://user-images.githubusercontent.com/32523293/80922958-c776bf80-8d80-11ea-98e3-75b3079e4960.png)

**Comment by alexdima** [comment]
Please configure `"editor.wrappingStrategy": "advanced"`.

**Comment by theodore-s-beers** [comment]
Thanks! I didn't know this option existed. (It looks like it arrived a few months ago, so I wasn't missing out for too long…)

**Comment by theodore-s-beers** [comment]
P.S. I probably would have found the option if it appeared as a search result for "word wrap." For some reason, "Editor: Wrapping Indent" comes up, but "Editor: Wrapping Strategy" doesn't. Thanks again.
