### ISSUE TITLE
Cursor jumps to top of tree after deletion

### ISSUE THREAD

**Issue by kingces95** [microsoft/vscode#96883]
- VSCode Version: 
> Version: 1.45.0-insider
Commit: a250df703de955a38aed427a917bce8278ab3331
Date: 2020-04-24T20:46:59.782Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

- OS Version:
![image](https://user-images.githubusercontent.com/4120386/80271377-6867cb00-865b-11ea-8c69-979f015e37a9.png)

Steps to Reproduce:

1. Create a tree of directories
2. Delete the last directory

After deletion, I expected the cursor to move to the item above the deleted item but it actually jumps to the top of the tree.

The other cut, paste, open, rename, and navigation features work wonderfully. It's just this one that can hamper using the UI move files around using the keyboard and not the mouse. 

https://youtu.be/53vfAH_6bsk

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/71315
