### ISSUE TITLE
Find In Folder Should Override Search Exclude Glob If Folder Is a Subfolder Within A Glob

### ISSUE THREAD

**Issue by weshoke** [microsoft/vscode#96887]
One of the globs to ignore search on (an rightly so) is `**/node_modules`.  However, I frequently poke around in the code within node_modules and like to search within a particular module to find where some code is. So, for example, I have a `node_modules/faye` and I'd like to find some code in that module.  I'll:

1. Click on the folder within the Explorer
2. Right click and Find in Folder
3. Enter some text to search for
4. Get no results

In this instance, it's really clear that I'd like to override the global setting to ignore `**/node_modules` since I'm explicitly asking to search within a folder.  My proposed solution is that if a folder in Find in Folder is one that is normally ignored, unignore searching within that folder in this particular case.

**Comment by isidorn** [comment]
Sounds search specific thus forwarding to Rob and Jackson.
