### ISSUE TITLE
Folders and files ignored in .gitignore not graying out

### ISSUE THREAD

**Issue by icavalheiro** [microsoft/vscode#96886]
Issue Type: <b>Bug</b>

VS Code do not gray items that are included in the .gitignore and inside a working git folder.
This is happening for all of the projects I have cloned and has been happening for weeks.

**Steps to reproduce**:
- install vs code
- clone a repo from github/gitlab/bitbucket
- "npm install parcel-bundler" to generate "node_modules/"
- open on vscode

These are some SS from the issue:
![image](https://user-images.githubusercontent.com/11912413/80927227-bf178800-8d72-11ea-887b-b8140e1afd58.png)
![image](https://user-images.githubusercontent.com/11912413/80927256-df474700-8d72-11ea-9d85-f717fe93ef76.png)

Alternative steps to reproduce issue:
https://github.com/microsoft/vscode/issues/96886#issuecomment-624343551

**Expected behavior**:
Files and folders included in the .gitginore must appear grayed out in the explorer.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (9.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
dotenv|mik|1.0.1
vscode-docker|ms-|1.1.0
csharp|ms-|1.21.17
vetur|oct|0.24.0
vscode-icons|vsc|10.1.1

</details>

**Comment by jrieken** [comment]
These steps don't make sense. What happens between 2 and 3 because if those files would be ignored and how come they show up after clone?

**Comment by icavalheiro** [comment]
@jrieken ,
I've added the missing step.

**Comment by jrieken** [comment]
Ok, different steps. Anyways, try this

* run the `git check-ignore` command, seehttps://git-scm.com/docs/git-check-ignore#git-check-ignore--z
* check the git output logs

**Comment by icavalheiro** [comment]
Hi @jrieken ,

After running the command I got an empty output... This let me think my git might had a bug or something... Checking git version I realized I was running the **2.9.0.windows.1**, and this is not the latest version, updating to the **2.26.2.windows.1** and restarting _vscode_ fixed the issue.
This might have been a bug with GIT or something...
Closing.
