### ISSUE TITLE
Text cursor not focused back to the terminal after restoring terminal panel size

### ISSUE THREAD

**Issue by rahmatrhd** [microsoft/vscode#96889]
- VSCode Version: 1.44.2
- OS Version: Darwin x64 19.4.0

When focused on the terminal then maximize the terminal panel and then restore it back (minimize), the cursor is not focused back to the terminal

Steps to Reproduce:

![Screen-Recording-2020-05-04-at-07 30 41](https://user-images.githubusercontent.com/5003439/80929832-4a2b6900-8dd9-11ea-943a-2893b6a4c504.gif)

1. Click/focus to the terminal
2. Click on the maximize panel size
3. Restore by clicking it again
4. You will see the cursor get focused back to the editor

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This could also be seen as a feature since you're minimizing the terminal, it's related to the panel-level action focusing the editor.

**Comment by isidorn** [comment]
This request makes sense. Leaving it up to @sbatten since he owns the layout now.

**Comment by sbatten** [comment]
IIRC, this is by design. It used to keep focus, but since the intent of restoring down the panel is to show the editor, we put focus in the editor.

**Comment by Tyriar** [comment]
I see in 1.43 it's like this as well, it's a little inconsistent though as focus is not added when you maximize it 🤷‍♂️

**Comment by Tyriar** [comment]
I'm not a fan of this change, we're just maximizing and restoring, operating systems don't do that with windows. I've hit it a few times recently where I've restored the panel to see their editor and kept typing into the terminal but the focus shifts to the editor.
