### ISSUE TITLE
A More Intuitive "Stage/Unstage Selected Range" UI Suggestion for Diff Editor 

### ISSUE THREAD

**Issue by MrRogerHuang** [microsoft/vscode#96884]
VS Code 1.44.2 Source Control supports to stage a portion of changes in a file from popup menu as shown in this screenshot.
![image](https://user-images.githubusercontent.com/49478723/80925260-d5e4cb80-8dc0-11ea-9c36-e89a01a82ff2.png)
However, I think it is more intuitive to do this action by clicking the "+" sign in the VS code diff editor as indicated in the screenshot above. Similarly, the diff editor may provide a "-" sign to unstage a portion of changes.

Please support this Source Control UI improvement. Thanks.

**Comment by joaomoreno** [comment]
#25887
