### ISSUE TITLE
js-debug profiles are opened as text instead of custom editor

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#96888]
```
Version: 1.45.0-insider (user setup)
Commit: ece7aaee861d7261a728d52ce436c667030ce17d
Date: 2020-05-01T09:46:47.589Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

I have the following code in js-debug ([ref](https://github.com/microsoft/vscode-js-debug/blob/master/src/ui/profiling/uiProfileManager.ts#L217-L218)):

```js
const document = await vscode.workspace.openTextDocument(fileUri);
await vscode.window.showTextDocument(document);
```

Previously (at least as recently as last monday/tuesday I think) this would cause the profile to be opened in the custom editor for profiles. In the most recent Insiders, this no longer happens; it opens as text. Recording: https://memes.peet.io/img/20-05-cad139df-9872-4ea7-8f5c-1fcdc7fcff34.webm

**Comment by bpasero** [comment]
See https://github.com/microsoft/vscode/issues/96397#issuecomment-621802672

//cc @jrieken

**Comment by jrieken** [comment]
You should be using `vscode.commands.executeCommand('vscode.open', someUri`)

**Comment by connor4312** [comment]
Okay, I will put in a fix for this in js-debug as a candidate issue.

**Comment by connor4312** [comment]
actually, nevermind, this isn't bundled with stable (even though it's in the oss package.json) so there's no need to make this a candidate.
