### ISSUE TITLE
_New File_ should create a new file in the current directory.

### ISSUE THREAD

**Issue by PlanMan1717** [microsoft/vscode#96885]
On the _Welcome_ tab as you open a new window:
The `New File` button creates a new file but does not put it in the current directory if opened.
Control+N also creates a file but does not put in in the directory I'm working in.
For consistency, could they create the file in the working directory, and immediately bring focus on the naming box to make things less confusing.

**Comment by chrmarti** [comment]
I think we have consistency for "New Untitled File". We could change the label on the Welcome page to fully ready "New Untitled File". Changing it to immediately save (like in the Explorer) does not seem appealing to me.

**Comment by bpasero** [comment]
We have some heuristic as to what folder to select by default in the dialog. I would not change this for specific cases.
