### ISSUE TITLE
the terminal won't close when it is exited

### ISSUE THREAD

**Issue by ElhamAryanpur** [microsoft/vscode#96882]
Issue Type: <b>Bug</b>

the terminal won't close after like, exiting, or deleting it. it stays open just removes the text.

back in the day, when you deleted a terminal process, it auto closed. but now it stays.

VS Code version: Code - OSS 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-23T19:32:05.786Z)
OS version: Linux x64 5.4.35-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2363)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|7.70GB (2.55GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-vlang|0x9|0.1.2
language-x86-64-assembly|13x|2.3.0
include-autocomplete|ajs|0.0.4
vscode-sqlite|ale|0.8.1
arepl|alm|1.0.23
svelte-intellisense|ard|0.7.1
code-gnu-global|aus|0.2.2
kivy-vscode|Bat|0.5.3
QML|bbe|1.0.0
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
c-cpp-compile-run|dan|1.0.8
vscode-markdownlint|Dav|0.35.1
vscode-eslint|dba|2.1.5
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.5.0
vscode-svelte-snippets|fiv|0.3.0
language-cython|guy|0.0.6
CppSnippets|har|0.0.14
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
jquery-snippets|Hri|1.0.0
discord-vscode|icr|3.14.0
elixir-ls|Jak|0.3.3
svelte-vscode|Jam|0.9.3
vscode-peacock|joh|3.7.0
vscode-rust|kal|0.4.2
chat|kar|0.33.0
Lua|key|0.0.9
discord|Kua|0.0.6
ccpp-extension-pack|Leo|0.3.0
vscode-clangd|llv|0.0.23
asm-code-lens|maz|1.4.3
vscode-language-babel|mgm|0.0.27
vscode-elixir|mjm|1.1.0
python|ms-|2020.4.76186
cpptools|ms-|0.27.1
Go|ms-|0.14.1
vsliveshare|ms-|1.0.2104
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.3.4
es6-css-minify|olb|3.3.2
java|red|0.61.0
LiveServer|rit|5.6.1
rust|rus|0.7.4
swdc-vscode|sof|2.2.3
cython|tcw|0.1.0
nativescript|Tel|0.11.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
I think this is already fixed, a workaround is to run this command:

![image](https://user-images.githubusercontent.com/2193314/80945673-2e0bd580-8da1-11ea-8756-a88c9589d31a.png)
