### ISSUE TITLE
Include a bracket pair colorizing feature

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/vscode#96899]
One of my favorite extensions for VSCode, [Bracket Pair Colorizer (2)](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2) has sadly been abandoned by his author, stating he won't continue developing it. Now, of course the community could step up and maintain a fork or create a new version but I feel like this is such a good and fundamental feature, why not make it an option in VSCode itself? The original extension also always had performance problems which, I think, could be avoided by having it in the core experience.

**Comment by pablolucio97** [comment]
A native feature of bracket colors look be a good idea.

**Comment by eitsupi** [comment]
Unfortunately, https://github.com/CoenraadS/Bracket-Pair-Colorizer-2 seems to have been archived.
Any update?

**Comment by KMFSousa** [comment]
Related: https://github.com/microsoft/vscode/pull/129231

**Comment by hediet** [comment]
Implemented with #129231.

You can try out the feature in todays Insider build by setting `"editor.bracketPairColorization.enabled": true`!
We would love to hear your feedback.
