### ISSUE TITLE
JS Profiler : Not Working When `/tmp` and `/${workspaceFolder}` are on different mount

### ISSUE THREAD

**Issue by olivierchatry** [microsoft/vscode#96897]
Issue Type: <b>Bug</b>

I guess the extension is using Rename instead of Move when getting the profile file from temporary forlder to project folder ( probably for performace reason ).

That will not work if `/tmp` ( where it store the temporary profile being made), and the target project folder are not on the same mount.

I get this error :

``` 
ERR EXDEV: cross-device link not permitted, rename '/tmp/vscode-js-profile-8e643a75.cpuprofile' -> '/home/olivier/Documents/my-project/vscode-profile-2020-05-04-09-42-35.cpuprofile': Error: EXDEV: cross-device link not permitted, rename '/tmp/vscode-js-profile-8e643a75.cpuprofile' -> '/home/olivier/Documents/my-project/vscode-profile-2020-05-04-09-42-35.cpuprofile'
``` 

VS Code version: Code - Insiders 1.45.0-insider (ece7aaee861d7261a728d52ce436c667030ce17d, 2020-05-01T09:46:11.716Z)
OS version: Linux x64 5.6.8-300.fc32.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 3821)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|31.30GB (22.79GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgo|ajh|0.1.0
vscode-json|and|1.5.0
vscode-custom-css|be5|3.0.9
gltf-vscode|ces|2.2.10
bracket-pair-colorizer-2|Coe|0.0.29
systemd-unit-file|coo|1.0.6
vscode-markdownlint|Dav|0.35.1
mustache|daw|1.1.1
vscode-eslint|dba|2.1.5
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-ember|emb|0.2.0
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
svgeditor|hen|2.9.0
beautify|Hoo|1.5.0
svelte-vscode|Jam|0.9.3
theme-karyfoundation-themes|kar|20.0.3
vscode-smart-column-indenter|lmc|0.0.13
fish-ide|lun|0.4.0
align-vertically|mat|0.2.0
vscode-docker|ms-|1.1.0
vscode-kubernetes-tools|ms-|1.2.0
python|ms-|2020.4.76186
cmake-tools|ms-|1.3.1
cpptools|ms-|0.27.1
Go|ms-|0.14.1
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
vetur|oct|0.24.0
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.1.0
java|red|0.61.0
vscode-yaml|red|0.7.2
rust|rus|0.7.4
code-settings-sync|Sha|3.4.3
kpd-vscode|Ska|1.1.0-alpha.0
fish-vscode|sky|0.2.1
shader|sle|1.1.4
vscode-bolt-language|smk|0.0.4
ayu|tea|0.18.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2
vscode-icons|vsc|10.1.1
debug|web|0.24.0
better-align|wwm|1.1.6

(15 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
Does this reproduce if you disable all extensions?

**Comment by olivierchatry** [comment]
I will check, but I'm guessing it will.

**Comment by olivierchatry** [comment]
Seems like it will be hard to do as the javascipt debugger is an extension. Maybe I should move this task to the JS debugger extension, but looking at the code of the extension, it does not copy or renames any file, so my guess is that the issue is with visual code, when it get back the results from the

**Comment by olivierchatry** [comment]
Found it, 

it is in the extension :

https://github.com/microsoft/vscode-js-debug/blob/25b3cdf31d45f6500fe7aa386b0a06e879adb263/src/ui/profiling/uiProfileManager.ts#L214

@alexr00 is it possible for you to move this bug to this repos ? https://github.com/microsoft/vscode-js-debug

**Comment by alexr00** [comment]
I think this is for @connor4312 then. I'll let him move it if he wants.

**Comment by connor4312** [comment]
Thanks for digging into this, Oliver!

**Comment by olivierchatry** [comment]
No problem, thanks fro the great work !

**Comment by connor4312** [comment]
note: will be in the next Insiders, the version didn't get bumped in today's.

**Comment by olivierchatry** [comment]
Thought so, tried today version and it had the same issue. Will wait for
tomorrow build. Thanks a lot.

**Comment by olivierchatry** [comment]
Tried with today build, guess it did not make it as I still get ther error with VS Code version: Code - Insiders 1.45.0-insider (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-06T08:26:27.875Z)

**Comment by connor4312** [comment]
Yes, sorry, I misspoke. We're in endgame now so Insiders builds are built off the 1.45 release branch. This will be in the first 1.46.0-insider release which should happen Thursday or Friday.

**Comment by olivierchatry** [comment]
No worries. I will wait, but reading your change, I think it will be 
all good. In the mean time, I just copied my project over to /tmp and 
profiled from there.

Thanks !

**Comment by olivierchatry** [comment]
Just tested on insider 1.46, and it is working. Thanks a lot for the quick fix !

**Comment by connor4312** [comment]
Awesome thanks for verifying!
