### ISSUE TITLE
revealFileInOS (Shift+Alt+R) doesn't work in multi-root workspaces

### ISSUE THREAD

**Issue by Abir-Tx** [microsoft/vscode#96893]
Issue Type: <b>Bug</b>

The Shift+Alt+R open the terminal menu instead of the show in explorer option all the time. Please fix it as soon as possible

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.42GB (2.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
bracket-pair-colorizer-2|Coe|0.0.29
githistory|don|0.6.5
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
cpptools|ms-|0.27.1
material-icon-theme|PKi|4.1.0
java|red|0.61.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Default binding for shift+alt+r:

![image](https://user-images.githubusercontent.com/2193314/80945788-762af800-8da1-11ea-896c-6d06e440edc9.png)

**Comment by Tyriar** [comment]
@sbatten maybe related to alt to open menu?

**Comment by sbatten** [comment]
This is working properly for me. @Abir-Tx, where is focus when you run the command. It cannot be in the editor, otherwise the Run menu should be opened.

**Comment by Abir-Tx** [comment]
> This is working properly for me. @Abir-Tx, where is focus when you run the command. It cannot be in the editor, otherwise the Run menu should be opened.

Not working for me on my two computers. The focus is on opened file in VS Code but still pressing Shift+Alt+R doesn't work as expected.

![image](https://user-images.githubusercontent.com/28858998/81041473-be483880-8ecf-11ea-9c73-3218e6c21b4a.png)

After pressing Shift+Alt+R - 
![image](https://user-images.githubusercontent.com/28858998/81041546-f0f23100-8ecf-11ea-8557-3b932c5aeab8.png)

**Comment by Tyriar** [comment]
I can repro in a multi-root workspace.

**Comment by bpasero** [comment]
I cannot reproduce on Windows, here is what I do:
* open a multi-root workspace
* click on a file in one folder
* hit `Shift+Alt+R`

The file is revealed.

**Comment by Tyriar** [comment]
@bpasero that's my repro:

![recording (9)](https://user-images.githubusercontent.com/2193314/81076354-69d99480-8ea0-11ea-8f0e-2c815d1938b5.gif)

**Comment by bpasero** [comment]
It should work if you modify the keybinding to work even when the editor is not focused:

![image](https://user-images.githubusercontent.com/900690/81077058-c367b080-8eec-11ea-8fa9-118621ded0b5.png)

```json
{
    "key": "shift+alt+r",
    "command": "revealFileInOS"
}
```

**Comment by Tyriar** [comment]
@bpasero wouldn't that open the explorer's focused item, not the active editor file?

**Comment by bpasero** [comment]
It should work fine. We have code that returns the correct resource depending on focus.

**Comment by Tyriar** [comment]
@bpasero oh, how come it's `!editorFocus` by default then?

**Comment by bpasero** [comment]
🤷

**Comment by Abir-Tx** [comment]
Yeah after modifying the keybinding it is working now.
Thanks :-)

**Comment by gjsjohnmurray** [comment]
> It should work if you modify the keybinding to work even when the editor is not focused:

See also https://github.com/microsoft/vscode/issues/92893#issuecomment-600418796

Does the default keybinding deserve to be changed?
