### ISSUE TITLE
Unexpected default cursorSelect keybindings

### ISSUE THREAD

**Issue by poacher2k** [microsoft/vscode#96894]
Issue Type: <b>Bug</b>

Starting vscode this morning, these keybindings were appended to the end of the "Default Keybindings". Most of them - like `ctrl+shift+p`, `ctrl+shift+f` and `ctrl+shift+e` - interferes with other default functionality.

The keybindings that were added:
```
{ "key": "ctrl+shift+b",          "command": "cursorLeftSelect",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+shift+p",          "command": "cursorUpSelect",
                                     "when": "editorTextFocus" },
{ "key": "alt+f",                 "command": "cursorWordEndRight",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+shift+f",          "command": "cursorRightSelect",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+shift+n",          "command": "cursorDownSelect",
                                     "when": "editorTextFocus" },
{ "key": "alt+b",                 "command": "cursorWordStartLeft",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+f",           "command": "cursorWordEndRightSelect",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+b",           "command": "cursorWordStartLeftSelect",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+shift+e",          "command": "cursorEndSelect",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+shift+a",          "command": "cursorHomeSelect",
                                     "when": "editorTextFocus" }
```

VS Code version: Code - Insiders 1.45.0-insider (ece7aaee861d7261a728d52ce436c667030ce17d, 2020-05-01T09:46:47.589Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
ndjson-colorizer|bus|1.0.0
vscode-exports-autocomplete|cap|0.5.4
bracket-pair-colorizer-2|Coe|0.0.29
vcard|cst|1.0.1
vscode-markdownlint|Dav|0.35.1
vscode-eslint|dba|2.1.5
vscode-generact|Den|1.0.5
javascript-ejs-support|Dig|1.3.1
es7-react-js-snippets|dsz|2.7.1
EditorConfig|Edi|0.14.5
prettier-vscode|esb|4.5.0
vscode-firefox-debug|fir|2.7.2
auto-close-tag|for|0.5.7
macros|ged|1.2.1
duplicate|gee|1.0.1
todo-tree|Gru|0.0.174
vscode-npm-dependency|how|1.2.2
fuse-vscode|iGN|0.0.1
reg|ion|1.0.1
lorem-whatever|job|1.0.2
vscode-random|jre|1.6.1
graphql-for-vscode|kum|1.15.3
expand-region|let|0.1.4
rainbow-csv|mec|1.7.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-duplicate|mrm|1.2.1
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.1.0
csharp|ms-|1.21.17
python|ms-|2020.4.76186
atom-keybindings|ms-|3.0.7
cpptools|ms-|0.27.1
vscode-typescript-next|ms-|4.0.20200503
vsliveshare|ms-|1.0.2104
color-highlight|nau|2.3.0
advanced-new-file|pat|1.2.0
vscode-react-refactor|pla|1.0.5
px-to-rem|sai|1.3.1
vscode-sanity|san|0.0.3
twig-for-craft-2|sel|0.5.0
code-settings-sync|Sha|3.4.3
shader|sle|1.1.4
vscode-stylelint|sty|0.84.0
ejs-snippets|The|0.7.0
vsfire|tob|1.4.1
vscode-input-sequence|tom|0.2.0
vscodeintellicode|Vis|1.2.6
twig|wha|1.0.2
vscode-import-cost|wix|2.12.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.3.1

</details>

**Comment by alexdima** [comment]
@poacher2k These come from one of the extensions you have installed. Extensions can contribute keybindings.

**Comment by chrisdias** [comment]
i rolled back changes to the atom keybinding extension https://github.com/microsoft/vscode-atom-keybindings/commit/d0f6378cfb3922cf99197c61ecc589cfd8db466d
