### ISSUE TITLE
In multi-root workspace, new settings from folder settings.json are ignored

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#96898]
- VSCode Version: 1.44.2
- OS Version: Windows 10 (SSH to Linux)

Steps to Reproduce:
1. Have a folder with a `.vscode/settings.json`  that has `"my.setting": "foo"` and a `.vscode/launch.json` with uses `${config:my.setting}` - this works fine when opening this folder.
2. Now integrate this folder into a multi-root workspace. The launch config will still be shown, but `${config:my.setting}` will not be seen any more. It's greyed out as an "Unknown Configuration Setting", which appears understandable at first. But the reason it's not applied is not that, see 1.

Proposed solution: Either 
a) apply unknown config settings from folder settings also in multi-root workspaces, or
b) correct the warning message to something like this:

> This setting cannot be applied in this workspace. It will be applied when you open the containing workspace folder directly.

Does this issue occur when all extensions are disabled?: Pretty sure yes (have not tested)

**Comment by sandy081** [comment]
> The launch config will still be shown, but ${config:my.setting} will not be seen any more. It's greyed out as an "Unknown Configuration Setting",

Where are you seeing this? Is it when you open `launch.json` ?

@isidorn FYI

**Comment by bersbersbers** [comment]
> > The launch config will still be shown, but ${config:my.setting} will not be seen any more. It's greyed out as an "Unknown Configuration Setting",
> 
> Where are you seeing this? Is it when you open `launch.json` ?

Sorry, I should have been e more specific.

> The launch config will still be shown

This is in the debug panel.

> ${config:my.setting} will not be seen any more

This is when I launch a debug configuration: I get an alert window telling me that the variable is not defined.

> It's greyed out as an "Unknown Configuration Setting",

This is in `settings.json`.

**Comment by sandy081** [comment]
> It's greyed out as an "Unknown Configuration Setting",

Do you see any info when you hover on it?

**Comment by bersbersbers** [comment]
> > It's greyed out as an "Unknown Configuration Setting",
> 
> Do you see any info when you hover on it?

@sandy081, just this:

![image](https://user-images.githubusercontent.com/12128514/80961107-86c38880-8e0a-11ea-9a81-d0a692eea9b9.png)

**Comment by sandy081** [comment]
What do you see when you open the folder directly?

**Comment by bersbersbers** [comment]
@sandy081 the setting is shown similar to the settings around it, just without hover info:

![image](https://user-images.githubusercontent.com/12128514/80963534-6a761a80-8e0f-11ea-8e0f-19ca2d5d5cc2.png)

**Comment by sandy081** [comment]
Can you please check if the extension contributing this extension is enabled in the workspace?

**Comment by bersbersbers** [comment]
@sandy081 there is no extension involved. I made up `"my.setting"` myself to have a place to make debug configs a bit more variable. That's why I called this a "new" setting, sorry if that was misleading.

**Comment by sandy081** [comment]
You are seeing `Unknown Configuration` because no extension has contributed. It is expected.

Leaving to @isidorn for debug related issue.

**Comment by bersbersbers** [comment]
@sandy081 But I am seeing "Unknown configuration" *only* if I open the folder as part of a workspace; I do *not* see "Unknown configuration" when loading the folder as a folder.

At the very least, this feels inconsistent to me.

**Comment by sandy081** [comment]
Please open a separate issue for that and provide steps to repro

**Comment by bersbersbers** [comment]
@sandy081 "that" is the issue I am talking about here. The setting works and is shown as working in a folder; same setting does not work and is shown as unknown in a multi-root workspace containing that folder. I don't really see the need to open a separate issue.

**Comment by sandy081** [comment]
It's bug that `Unknown Configuration` message is not shown when opened as folder. Fixed to show the `Unknown Configuration` always if the setting is not registered.

To verify

- Open folder in VS Code
- Add setting `"my.setting": "foo"` to folder settings
- Make sure above entry is dimmed and on hover `Unknown Configuration Setting` is shown
- Open the same folder as Multi root folder workspace
- Open folder settings and make sure setting is dimmed and `Unknown Configuration Setting` is shown on hover.

**Comment by bersbersbers** [comment]
If I understand correctly, this grays out unregistered settings even if they are read and used correctly (e.g., by a debug configuration). So for me, you "fixed" something that was not broken, but I may be wrong. I will wait for this change to make it to insiders and then re-check my original issue, and possible re-file another issue then.

**Comment by sandy081** [comment]
> this grays out unregistered settings even if they are read and used 

Yes.

>  So for me, you "fixed" something that was not broken, but I may be wrong

`Unknown Configuration Settings` are treated as `window` scoped configurations and `window` scoped configurations in folder settings are not read in multi folder workspace. Hence your setting is not read in multi folder workspace. This is expected.

**Comment by bersbersbers** [comment]
> `Unknown Configuration Settings` are treated as `window` scoped configurations 

Alright, this is the bit of information I was missing - thanks!

> and `window` scoped configurations in folder settings are not read in multi folder workspace. 

Yes, I was aware of that - thanks for confirming.

> Hence your setting is not read in multi folder workspace. This is expected.

If this is expected, I find it suboptimal that this is not reflected in the GUI like other `window`-scoped settings are. Like, in a workspace, `"window.zoomLevel"` in a folder `.vscode/settings.json` is shown as 
> This setting cannot be applied in this workspace. It will be applied when you open the containing workspace folder directly.

If I understand you correctly, in a workspace, I would expect unknown/non-registered settings in a `.vscode/settings.json` to be annotated the same way. It is not really relevant that the setting is unknown - it will not be loaded anyway. This is similar to `"window.zoomLevel"` which, in a workspace, does *not* show this context-sensitive help in a folder `.vscode/settings.json` either (and this is expected!):

> Adjust the zoom level of the window. The original size is 0 and each increment above (e.g. 1) or below (e.g. -1) represents zooming 20% larger or smaller. You can also enter decimals to adjust the zoom level with a finer granularity.

Of course, my suggestion could be slightly misleading with typos. For example, adding `"python.pythonpath"` (incorrect), which currently shows "Unknown Configuration Setting", would show "...cannot be applied in this workspace" under my suggestion, incorrectly suggesting that the correct `"python.pythonPath"` (note the capital "P") might not be applied, either, if the user is unaware of the typo. I guess a proper solution would then be to combine the two messages: that is, something like

> This setting is unknown. As such, it cannot be applied in this workspace. It will be applied when you open the containing workspace folder directly.

if a setting is unknown *and* in a folder `.vscode/settings.jscon` in a workspace.

**Comment by sandy081** [comment]
Thanks for detail explanation and I understand your reasoning. IMO an unknown configuration is something which should not be applied anytime. Also the following message is misleading

> This setting is unknown. As such, it cannot be applied in this workspace. It will be applied when you open the containing workspace folder directly.

Ability to apply an unknown setting is weird. 

Hence to be consistent, I would fix to load unknown settings always.

**Comment by bersbersbers** [comment]
> I would fix to load unknown settings always.

This makes a lot of sense to me: it's actually my preferred solution, see a. above. Thanks! Looking forward to the May release, I might check insiders around mid May.

**Comment by bersbersbers** [comment]
Yesterday's insiders build behaves pretty well in all aspects discussed here, thank you. Looking forward to the next release ;)
