### ISSUE TITLE
ho fatto una buona/ottima traduzione in italiano dell intera estensione di python (italian translation)

### ISSUE THREAD

**Issue by MineFriend** [microsoft/vscode#96896]
ho tradotto in italiano (alcune righe sono in beta  , e hanno tra parentesi (w.i.p) sta a significare che, non sapevo come tradurle o la traduzione potrebbe non rispecchiare la funzionalita ) 475 righe in confronto alle 30 righe scrause che ci stanno nel file default in italiano .... questo è il file :

en)
I translated into Italian (some lines are in beta , and have in brackets (w.i.p) means that, I didn't know how to translate them or the translation might not reflect the functionality) 475 lines compared to the 30 scrause lines that are in the default file in Italian .... this is the file :

**Comment by MineFriend** [comment]
ho chiuso il vecchio ticket e lasciate aperto questo.....

**Comment by MineFriend** [comment]
@alexr00 @vscode-triage-bot  I made a better Italian translation than the default one, the default one is 30 lines mine and 475 lines ..... my translation is in beta (some translations have in brackets (w.i.p) means that, either I didn't know how to translate them or the translation could be wrong .... I couldn't put every single function of the extension) so I wanted to publish the translation so that other people with more experience than me (who tested more functions of python) could correct the translations that I did wrong.

Translated with www.DeepL.com/Translator (free version)

**Comment by MineFriend** [comment]
....if i write it in english how do the italians understand that it is an italian translation????... then i don't understand why you have chisuo the section where one could give a hand to translate both v queues and extensions...... i'm talking about the link you put in the docs of vs code (https://aka.ms/vscodeloc) what's the use of this link if when i click it sends me somewhere else????

**Comment by MineFriend** [comment]
if I write the title/description in english how do the italians understand that it's an italian translation???... then I don't understand why you closed the section where one could give a hand to translate both vs code and maybe even the extensions...... I'm talking about the link you put in the docs of vs code (https://aka.ms/vscodeloc) what's this link for if when I click it it sends me somewhere else????

Translated with www.DeepL.com/Translator (free version)

**Comment by MineFriend** [comment]
so?

**Comment by MineFriend** [comment]
later I'll correct the mistakes in the general translation of VS Code...

**Comment by MineFriend** [comment]
obviously always for Italian

**Comment by MineFriend** [comment]
my translation is fine for VS Code version: Code 1.44.2.  what more information do you want?

**Comment by mich2k** [comment]
ma scusa, traduci il bot di vscode e poi scrivi
"italian traslaction"

**Comment by MineFriend** [comment]
non avete capito....

**Comment by MineFriend** [comment]
ma che c'entra il bot? ma chi ha mai nominato il bot???!!! io boh non ho parole 
....

**Comment by mich2k** [comment]
Greve, comunque translascion me la segno

**Comment by MineFriend** [comment]
ma segnati quello che te pare professore

**Comment by MineFriend** [comment]
io mi segno greve
