### ISSUE TITLE
Dynamic contirbutions can only be contributed by extensions that contribute a debugger

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#96905]
From @wienand So I suggest you use the "type" on the activation event to find the debugger's name for the "folder" container item in the quick pick.

Code pointer
https://github.com/microsoft/vscode/blob/2e80a8f99e239a712d58081b2fbc6ceafd03f176/src/vs/workbench/contrib/debug/browser/debugConfigurationManager.ts#L252

**Comment by isidorn** [comment]
Since @weinand is blocked assigning to may

**Comment by isidorn** [comment]
Adding bug label so we get this verified.

**Comment by connor4312** [comment]
Verified with a caveat https://github.com/microsoft/vscode/commit/e6bd1d1ae758f379170457992ed386971ba55268#r39672935
