### ISSUE TITLE
Navigation back in the list of recent items using the SHIFT key

### ISSUE THREAD

**Issue by Aminadav** [microsoft/vscode#96901]
- VSCode Version:1.44.2
- OS Version: MacOS Catalina

Steps to Reproduce:

1. Press CMD+TAB (or shift+TAB) and hold the CMD. 
2. Press two times TAB.
3. Now I with to go back to the previous item (While CMD is still pressed).
4. Add the SHIFT key TAB (CMD+SHIFT+TAB).
5. Now it's not going back to the previous item in the list as I expected. (Instead I need to press up&down, but shift should work)

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/3584317/80954259-b8862080-8e05-11ea-8512-803c823af7b0.png)

**Comment by bpasero** [comment]
![recording (1)](https://user-images.githubusercontent.com/900690/80970406-651ecd00-8e1b-11ea-85fd-985eb006a84f.gif)

I cannot reproduce, you might be having a keybinding associated that interfers.
