### ISSUE TITLE
Test: Add Net Promoter Score feedback support

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9690]
- [x] @weinand
- [x] @seanmcbreen (review the spec)

This shouldn't be tested but rather code reviewed. The behaviour we are trying to achieve is described in #9686.

**Comment by weinand** [comment]
Tested through debugging: 
- Found an incorrect check that would prevent the dialog from ever showing.
- The notification does not show because of https://github.com/Microsoft/vscode/issues/9769

**Comment by Tyriar** [comment]
Closing this off since the test is complete.
