### ISSUE TITLE
Cannot exit VS Code

### ISSUE THREAD

**Issue by stefjoosten** [microsoft/vscode#96900]
- VSCode Version:
- OS Version: macOS Catalina, version 10.15.1 (19B88)

I have not been able to make this issue reproducible because it does not occur frequently. However, when it happens, these symptoms occur:

1. VS code stays live with 0 windows, whereas I would expect it to die.
2. command-Q does not work
3. VS code claims that one window is still open, but doesn't show it.
4. If I close this window blindly (without it being shown on the screen), I can make VS code die.

Does this issue occur when all extensions are disabled?: Yes/No
I don't know how to launch code from the command line, so I cannot check this. 
The command `code` is not in the path.

**Comment by bpasero** [comment]
Without steps to reproduce, this will be hard to diagnose.
