### ISSUE TITLE
Markdown preview fails to open after window reload on WSL

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#96917]
Same setup as https://github.com/microsoft/vscode/issues/96916

Open the markdown preview, side by side. Reload the window:

![image](https://user-images.githubusercontent.com/22350/80971374-f6db0a00-8e1c-11ea-9109-12abe72e1801.png)

**Comment by mjbvz** [comment]
I can't reproduce this with a Ubuntu 20 WSL workspace (on Parallels). Please let me know if you are still seeing this

Assigning to May for verification
