### ISSUE TITLE
Automatically indent files on save according to indentation settings

### ISSUE THREAD

**Issue by rightaway** [microsoft/vscode#96910]
If I'm using tabs for example as the chosen indentation, and a file accidentally has spaces for indentation at some points within the file, vscode should automatically convert all tabs to space on save.

You have to trigger the formatting manually, and if you forget to do so then your file can be left with mixed indentation which is really not good.

**Comment by IllusionMH** [comment]
VSCode already has setting for this `"editor.formatOnSave": true`.
Does this setting resolve your problem?

**Comment by rightaway** [comment]
@IllusionMH I already have this setting enabled, and it does it for certain file types but misses many file types like `.md` markdown files.

**Comment by mjbvz** [comment]
@rightaway Sorry I missed this issue. Can you share a code example of the problem an describe the expected behavior?

**Comment by Lemmingh** [comment]
I do **not** think "just **converting tabs to spaces** according to **indentation settings**" is feasible for Markdown.

Theoretically, you can set `tabSize` to arbitrary value. So from the perspective of CommonMark, it *can* be **semantic change** and turn your document to a **totally different** one. All in all, it's **too dangerous**.

---

[CommonMark](https://spec.commonmark.org/0.29/) handles whitespace characters in a very complex way. For example, "*2.2 Tabs*" says

> Tabs in lines are not expanded to spaces. However, in contexts where whitespace helps to define block structure, tabs behave as if they were replaced by spaces with a tab stop of 4 characters.
>
> internal tabs are passed through as literal tabs, not expanded to spaces.

Besides, a huge number of rules under "*5.2 List items*" also count.

Thus, (represented in JavaScript string)

```javascript
"* abc\n\n\t456"
```

and

```javascript
"* abc\n\n    456"
```

should be compiled to the same result, **no matter what `tabSize` (indentation setting / tab visual length) is**.

---

IMHO, the **safest** way to format a Markdown document is to parse it to AST and regenerate it **according to the Spec strictly**.

Or **at least**, only convert each leading tab (U+0009) to 4 spaces (U+0020).

---

A few more to consider: Different Markdown flavors don't agree on how to handle whitespace characters. See [babelmark3](https://babelmark.github.io/).

Although most VS Code users are supposed to write in CommonMark, one may prefer to use other flavor. Therefore, if this request is implemented, a new setting is also needed to turn it off.

**Comment by mjbvz** [comment]
VS Code does not include a built-in markdown formatter, we leave that up to extensions

Closing this an extension candidate
