### ISSUE TITLE
Show progress notification if turning on sync takes longer time

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#96911]
From @misolori 

When I turn on sync for the first time, it ends up taking quite a long time (~1min) and it was hard to tell whether something was stuck or if it was still in progress. The gear badge is subtle and am wondering if we should show a progress toast after 15-20s to give the impression that things are still syncing? I feel like maybe we've discussed this before.

cc @Tyriar

**Comment by sandy081** [comment]
Yes first time set up might take longer time depends on number of extensions to install or snippets etc., 

> we should show a progress toast after 15-20s to give the impression that things are still syncing?

Do you mean the progress notification ?

**Comment by misolori** [comment]
> Do you mean the progress notification ?

Yes, I wonder if progressive disclosure makes sense here when it takes a long time. In my case, the first time I set this up it took 1 minute and though there was a badge, after waiting that long it feels like things maybe stopped working and there was no way to tell besides looking at the logs (which I think average users would miss).

**Comment by sandy081** [comment]
This was fixed in June already
