### ISSUE TITLE
Typing is laggy when outline is visible

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#96914]
Steps:

1. Open `vscode-docs`
2. Open `release-notes/v1_45.md`
3. Make sure outline is visible in the sidebar
4. Type some text

Here's the profile screenshot with outline open:

![image](https://user-images.githubusercontent.com/22350/81074660-9c5baf80-8ee9-11ea-9d84-ffa88985493c.png)

With outline closed:

![image](https://user-images.githubusercontent.com/22350/81074669-9fef3680-8ee9-11ea-8c23-0af2afb88cfb.png)

cc @jrieken

**Comment by joaomoreno** [comment]
Figured out that [this](https://github.com/microsoft/vscode/blob/68213a7df9ee450fecec51f4f2a6dc8a44592f53/src/vs/workbench/contrib/outline/browser/outlinePane.ts#L613-L613) is called on every keystroke. This is odd, especial because [`getLiveMarkers(textModel)`](https://github.com/microsoft/vscode/blob/68213a7df9ee450fecec51f4f2a6dc8a44592f53/src/vs/workbench/contrib/outline/browser/outlinePane.ts#L606-L606) always returns an empty collection. So why is `onDidChangeMarker` actually firing?

**Comment by jrieken** [comment]
Adding @sandy081 who wrote that marker service and because this likely affects the markers panel?

**Comment by jrieken** [comment]
This doesn't reproduce for me, e.g no slow typing or freezing nor does the FPS change when toggling `outline.problems.enabled`. The CPU profiles shows that very little time is spend in `updateMarker` (when typing four times `console.log();\n` in TS files that already has some errors). 

<img width="755" alt="image" src="https://user-images.githubusercontent.com/1794099/81074270-117ab500-8ee9-11ea-9099-f4a7d24bd13f.png">


I am not arguing that it is smart to always call this function but I definitetly see no slowing, freezing and anything remotely related to that.

**Comment by jrieken** [comment]
Freeze only repos on windows (linux unknown, mac not)

**Comment by jrieken** [comment]
The event firing soo often is actually the right thing because it means (bad naming) ranges of diagnostics markers of this file have changed. And that happens when typing...

**Comment by jrieken** [comment]
Pushed change to debounce the `onDidChangeMarker` inside the outline pane (see comment above) and I also don't send the event when before and after no marker where there

@sandy081 leaving the rest to you. Idk how else this service is used and if its internal content change listener should be debounced or not. I feel it should but idk how that affects other consumers. This call/event: https://github.com/microsoft/vscode/blob/d2c6b2cd073ec1d871729e008c17aff12601c382/src/vs/editor/common/services/markerDecorationsServiceImpl.ts#L118

**Comment by joaomoreno** [comment]
Thanks @jrieken, debouncing is definitely a good change.

But yeah, there's still the question of why is that even firing at all, when there aren't any changes to the markers.

**Comment by sandy081** [comment]
I introduced `IMarkerDecorationsService`initially for Monaco editor to show squiggles and hovers.

@jrieken Seems you added `onDidChangeMarker` and `getLiveMarkers` afterwards and `OutlinePane` is the only consumer.

**Comment by jrieken** [comment]
@sandy081 please carefully

https://github.com/microsoft/vscode/commit/404f66c13cb3c4ef0fb30db8a09b2967fc4b8367

**Comment by sandy081** [comment]
Sorry @jrieken. I just focused on last comment - https://github.com/microsoft/vscode/issues/96914#issuecomment-624096004

Also debounced the internal content change event.
