### ISSUE TITLE
[loc][Query][vscode_extensions] Localizability of strings

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode#96913]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Id | File Name Live Page Extended | String Resource ID | Full Source String | Extended Description
-- | -- | -- | -- | --
49,332 | Src\vscode-extensions\FeaturePromotion.json | 0;   "rules[1].IntallerMessage" | This setup requires the [2] [3]   version [1].  Please install the [3]   and run this setup again.  The [3] can   be obtained from the web.  Would you   like to do this now? | What do the placeholders stand   for?     This query also applies to the following ResID:     0; "rules[2].IntallerShortMessage"
49,337 | Src\vscode-extensions\FeaturePromotion.json | 0;   "rules[3].dotnetCLR" | .NET   Core Desktop Runtime | Is   "Desktop Runtime" generic and therefore translatable?

**Comment by alexr00** [comment]
I can't find those strings in this repo. What repo are they coming from?
