### ISSUE TITLE
Ctrl+Shift+e doesn't open the Explorer tab on Ubuntu on the snap version

### ISSUE THREAD

**Issue by Bakerbakura** [microsoft/vscode#96919]
Issue Type: <b>Bug</b>

1. Install and open the snap version of VSCode on Ubuntu
2. Open any file, and close the Explorer tab
3. Inside the file, try the command 'Ctrl+Shift+e'

Expected behaviour: open the Explorer tab.
Actual behaviour: an underlined 'e' is shown in the file, which is indicative of the emoji annotation functionality in ibus.

- I have disabled the ibus emoji annotation functionality in ibus-setup, as suggested by some other posts.
- I've tried this using the apt version of VSCode, and it works as expected, so this is a snap-specific problem.
- I've also tried this on the Insiders version of VSCode, and the problem persists.
- I've had this experience both on Ubuntu 19.10 and more recently on Ubuntu 20.04.
- From some research online, it seems that the problem may be an oldish version of GTK bundled with the snap version of VSCode; apparently versions of GTK before 3.24 forced this sort of behaviour.

I hope that this problem can be fixed in the snap version of VSCode, as I personally prefer snap to apt for this sort of application...

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 5.4.0-28-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4087)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.50GB (0.16GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
chronicler|arc|0.1.7
spellright|ban|3.0.50
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
latex-workshop|Jam|8.9.0
vscode-edit-csv|jan|0.2.6
vscode-peacock|joh|3.7.0
python|ms-|2020.4.76186
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0

(1 theme extensions excluded)

</details>

**Comment by julianlam** [comment]
For what it's worth it's not just the 'buntu Snap version that suffers from this.

Today I installed Pop!_OS and installed vscode via the deb downloaded from the main website. Ctrl-shift-e was also overridden by ibus.

**Comment by Bakerbakura** [comment]
Unfortunately the suggestions given in #48480 don't quite work for me. If I run `GTK_IM_MODULE=xim code` in terminal then it works properly, but when I try modifying the code.desktop file to have `Exec=GTK_IM_MODULE=ibus code --force-user-env --no-sandbox --unity-launch %F` or `Exec=env GTK_IM_MODULE=ibus code --force-user-env --no-sandbox --unity-launch %F`, Code doesn't work as expected when opening from the GNOME application menu, even after restarting GNOME.

Any idea what I'm doing wrong?

**Comment by Tyriar** [comment]
Not sure, I haven't used Ubuntu primarily in a while, but it definitely a case of something intercepting the keystroke before we have a chance to action it.

**Comment by stoically** [comment]
Setting `/desktop/ibus/panel/emoji/hotkey` to `[]` in the `dconf` editor did the trick for me.

**Comment by Bakerbakura** [comment]
I have `/desktop/ibus/panel/emoji/hotkey` set to `[]` in the `dconf` editor too. but unfortunately I still have the same behaviour

**Comment by stoically** [comment]
Do you run stock Gnome? Did you make sure to apply the value? Does it respond with `@as []` when running `dconf read /desktop/ibus/panel/emoji/hotkey` in the terminal? Might also want to try reloading gnome (Alt+F2 and then executing just `r`) or even restarting the OS.

**Comment by stoically** [comment]
You might also need to make sure that you remove the `GTK_IM_MODULE=ibus` workarounds.

**Comment by Bakerbakura** [comment]
@stoically Yes, stock GNOME on Ubuntu 20.04. It does respond with `@as []` when I run `dconf read /desktop/ibus/panel/emoji/hotkey` in the terminal. I have reloaded GNOME and restarted the OS a few times since doing the `dconf` method, which was a few weeks ago.

Strangely enough, I no longer have the ctrl+shift+e problem anymore! I'm really not sure what fixed the issue; maybe the latest update to VSCode?

**Comment by stoically** [comment]
Glad it works now for you.

> maybe the latest update to VSCode?

Don't think so, I was running latest VSCode and only changing `/desktop/ibus/panel/emoji/hotkey` to `[]` helped in my case.
