### ISSUE TITLE
Markdown preview fails to load images on WSL

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#96916]
I keep our docs repo in WSL. It seems the markdown preview fails to render the images:

![image](https://user-images.githubusercontent.com/22350/80971265-c72c0200-8e1c-11ea-9f0b-e763bc3b0b19.png)

**Comment by rchiodo** [comment]
I believe I'm hitting the same issue on insiders. I get 404 errors in the webview dev console:
![image](https://user-images.githubusercontent.com/19672699/83311414-ffc4be80-a1c3-11ea-990b-d28bbce00e86.png)

Here's the file in insiders:
![image](https://user-images.githubusercontent.com/19672699/83311428-094e2680-a1c4-11ea-9951-15c3ff651066.png)

Here's the file in released:
![image](https://user-images.githubusercontent.com/19672699/83311385-ecb1ee80-a1c3-11ea-93f0-6f53ad955306.png)

I believe this is the cause of a bug in our python extension:
https://github.com/microsoft/vscode-python/issues/12006

**Comment by mjbvz** [comment]
Just tested on WSL2 and it seems to work fine now for me.

<img width="2160" alt="Screen Shot 2020-07-08 at 8 02 59 PM" src="https://user-images.githubusercontent.com/12821956/86992332-21677d00-c156-11ea-8640-816efbf3a1da.png">


Marking for July so we can verify this
