### ISSUE TITLE
F2 to rename show refactor failed

### ISSUE THREAD

**Issue by 1995huei** [microsoft/vscode#96923]
Issue Type: <b>Bug</b>

I use F2 to rename bute it didn't work,and show error about refactor failed,while yesterday it's work,and I don't know what' the problem

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
pylingo|dia|0.0.2
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
code-runner|for|0.10.0
python|ms-|2020.4.76186
sqltools|mtx|0.21.7
material-icon-theme|PKi|4.1.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Which language?

**Comment by Tyriar** [comment]
@mjbvz I often saw this a while ago in the xterm.js codebase (TS) where it would fail the first time and work when I tried again. Not sure about a reliable repro case.

**Comment by mjbvz** [comment]
@1995huei Which language was this for?
