### ISSUE TITLE
Using python virtual environment on bash terminal in windows 

### ISSUE THREAD

**Issue by lanzkron** [microsoft/vscode#96924]
Issue Type: <b>Bug</b>

1. Use Git-Bash as shell for terminal on windows.
2. Create a python virtual environment (`python -m venv venv`)
3. Activate the virtual environment (`source venv/Scripts/activate`)
4. Try to perform any command (e.g. `ls`)
> bash: ls: command not found

Notes:
* When using the Python extension it automatically activates venv causing the problem but if the extension is disabled and ran manually the same happens
* When using standalone Git-bash terminal the problem doesn't happen

Here is a copy past of the output from VSCode terminal using bash (followed by the output from a Git-bash standalone terminal)

# VSCode terminal

/c/code/example
$ ls
main.py  venv

/c/code/example
$ echo $PATH
/mingw64/bin:/usr/bin:/c/Users/my-user/bin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/bin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/libnvvp:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cmd:/c/WINDOWS/System32/OpenSSH:/c/Program Files/Docker/Docker/resources/bin:/c/ProgramData/DockerDesktop/version-bin:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Program Files (x86)/IncrediBuild:/c/Program Files/NVIDIA Corporation/Nsight Compute 2019.5.0:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Users/my-user/AppData/Local/Programs/Python/Python37/Scripts:/c/Users/my-user/AppData/Local/Programs/Python/Python37:/c/Users/my-user/AppData/Local/Microsoft/WindowsApps:/c/Users/my-user/AppData/Local/Programs/Microsoft VS Code/bin:/c/Utils/google-cloud-sdk/bin

/c/code/example
$ source venv/Scripts/activate
(venv) 
/c/code/example
$ ls
bash: ls: command not found
(venv) 
/c/code/example
$ echo $PATH
C:\code\example\venv/Scripts:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program 
Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Microsoft 
SQL Server\130\Tools\Binn\;C:\Program Files (x86)\IncrediBuild;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.5.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\my-user\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\my-user\AppData\Local\Programs\Python\Python37\;C:\Users\my-user\AppData\Local\Microsoft\WindowsApps;;C:\Users\my-user\AppData\Local\Programs\Microsoft VS Code\bin  

# Git-bash terminal

/c/code/example
$ ls
main.py  venv/

/c/code/example
$ echo $PATH
/c/Users/my-user/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/my-user/bin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/bin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/libnvvp:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cmd:/c/WINDOWS/System32/OpenSSH:/c/Program Files/Docker/Docker/resources/bin:/c/ProgramData/DockerDesktop/version-bin:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Program Files (x86)/IncrediBuild:/c/Program Files/NVIDIA Corporation/Nsight Compute 2019.5.0:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Users/my-user/AppData/Local/Programs/Python/Python37/Scripts:/c/Users/my-user/AppData/Local/Programs/Python/Python37:/c/Users/my-user/AppData/Local/Microsoft/WindowsApps:/c/Users/my-user/AppData/Local/Programs/Microsoft VS Code/bin:/c/Utils/google-cloud-sdk/bin:/usr/bin/vendor_perl:/usr/bin/core_perl

/c/code/example
$ source venv/Scripts/activate
(venv)
/c/code/example
$ ls
main.py  venv/
(venv)
/c/code/example
$ echo $PATH                                                                                                            C:\code\example\venv/Scripts:/c/Users/my-user/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/my-user/bin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/bin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/libnvvp:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cmd:/c/WINDOWS/System32/OpenSSH:/c/Program Files/Docker/Docker/resources/bin:/c/ProgramData/DockerDesktop/version-bin:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Program Files (x86)/IncrediBuild:/c/Program Files/NVIDIA Corporation/Nsight Compute 2019.5.0:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Users/my-user/AppData/Local/Programs/Python/Python37/Scripts:/c/Users/my-user/AppData/Local/Programs/Python/Python37:/c/Users/my-user/AppData/Local/Microsoft/WindowsApps:/c/Users/my-user/AppData/Local/Programs/Microsoft VS Code/bin:/c/Utils/google-cloud-sdk/bin:/usr/bin/vendor_perl:/usr/bin/core_perl

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (18.31GB free)|
|Process Argv|ocr.model|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.1
vscode-docker|ms-|1.1.0
python|ms-|2020.4.76186
cmake-tools|ms-|1.3.1

</details>

**Comment by lanzkron** [comment]
Python details:
> Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)] on win32

**Comment by Tyriar** [comment]
For issues with Python please report to the Python extension https://github.com/microsoft/vscode-python

**Comment by lanzkron** [comment]
@Tyriar why do you think this is caused by the Python extension? I specified that it reproduces when the Python extension is disabled.

**Comment by Tyriar** [comment]
@lanzkron because venv is a python thing so they are also the experts in the area and aim to support it.

**Comment by lanzkron** [comment]
@Tyriar I'll open an issue for Python but I think the `caused-by-extension` tag is not appropriate here.
