### ISSUE TITLE
Search/Replace - Make replace box the same as the search box

### ISSUE THREAD

**Issue by Stooshie** [microsoft/vscode#96926]
Would it be possible to make the Search and Replace boxes, in the file manager, behave in the same way.

Although you can put multiline text in both boxes, the replace box is only one line high.

Thanks,

Andrew Wilson.

Currently using:
Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by roblourens** [comment]
You can insert a newline the same way, with shift+enter, does that now work for you?
