### ISSUE TITLE
Suspending PC and restarting causes parts of vscode to become glitchy

### ISSUE THREAD

**Issue by searchableguy** [microsoft/vscode#96921]
- VSCode Version: 1.44.2
- OS Version: Linux pop-os 5.4.0-7626-generic #30~1588169883~20.04~bbe668a-Ubuntu SMP Wed Apr 29 21:00:02 UTC  x86_64 x86_64 x86_64 GNU/Linux
- V8: 7.8.279.23-electron.0
- Commit:  ff915844119ce9485abfe8aa9076ec76b5300ddd

Steps to Reproduce:
1. Suspend PC
2. Reopen PC

Does this issue occur when all extensions are disabled?: Yes/No
 Yes

Screenshot -> https://postimg.cc/14rJp08P

**Comment by yume-chan** [comment]
Looks same as #69665
