### ISSUE TITLE
Environment variables from (builtin?) extensions that update are not cleared

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#96929]
```
Version: 1.45.0-insider (user setup)
Commit: ece7aaee861d7261a728d52ce436c667030ce17d
Date: 2020-05-01T09:46:47.589Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

I noticed this morning that I received this error when running a script:

```
Error: Cannot find module 'c:/Users/Connor/.vscode-insiders/extensions/ms-vscode.js-debug-nightly-2020.4.3017/src/bootloader.js'
```

I currently have version `2020.5.217`. It looks like variables for the old version weren't cleared on update. If I recall correctly the intention was that they would be. If not, a workaround I can do is to store a copy of the bootloader script in the extension's workspace storage directory. Let me know what the preferred solution would be 🙂

**Comment by Tyriar** [comment]
The design is not to clear on extension updates, only uninstall/disable (based on the `IExtensionService.onDidChangeExtensions` event).
