### ISSUE TITLE
Break-on-exception settings not visible for launch.json-less project if no breakpoints

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#96931]
If you're working on a simple script and have no launch.json, the tickboxes to control break-on-exception behaviour are not visible unless you add breakpoints:

<img width="876" alt="Screenshot 2020-05-04 at 17 25 23" src="https://user-images.githubusercontent.com/1078012/80989185-7a502780-8e2c-11ea-9040-3a4f97458b70.png">

<img width="878" alt="Screenshot 2020-05-04 at 17 25 17" src="https://user-images.githubusercontent.com/1078012/80989178-78866400-8e2c-11ea-877b-0d2d004eb36b.png">

It feels a little weird to have to add a breakpoint to enable break-on-exception and then remove it again.

**Comment by isidorn** [comment]
This is currently by design. Though we might change it in the future.
Thanks for the feedback.
