### ISSUE TITLE
Could not load the token provider for AccountProvider GitHub

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#96936]
activating extension ms-vsonline.vsonline failed. Seems to only happen in extension development host?

![image](https://user-images.githubusercontent.com/8586769/80996865-6210e600-8df5-11ea-9985-0133ac697519.png)

**Comment by RMacfarlane** [comment]
I'm currently not able to reproduce this, let me know if you still see this and I will reopen.
