### ISSUE TITLE
Inline assembly comment does not terminate at end of string when ARM extension installed

### ISSUE THREAD

**Issue by Sierraffinity** [microsoft/vscode#96937]
- VSCode Version: 1.44.2
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Install the extension "ARM" by dan-c-underwood.
2. Type `asm("@")` into a file being parsed as C, and then type anything below it. It will be parsed incorrectly and show up as a light blue color (in my theme anyway).

Does this issue occur when all extensions are disabled?: No

I've opened an issue with the extension author [here](https://github.com/dan-c-underwood/vscode-arm/issues/15) and he believes that this is an issue with the C parser provided natively by Code, specifically in [this file](https://github.com/microsoft/vscode/blob/master/extensions/cpp/syntaxes/c.tmLanguage.json).

**Comment by alexr00** [comment]
@jeff-hykin FYI

**Comment by shuffle2** [comment]
Wanted to note that `asm(";")` also produces this behavior. See https://github.com/dan-c-underwood/vscode-arm/issues/18

**Comment by alexr00** [comment]
Can you provide a full copy/pastable example?

**Comment by jeff-hykin** [comment]
![code](https://user-images.githubusercontent.com/17692058/98317262-cded2a80-1fa1-11eb-8d03-86ed20c62580.png)

Also thanks for coincidentally bumping this. I can't reproduce any of the issues
