### ISSUE TITLE
Logpoint causes VS Code to hang while debugging

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#96945]
Add a Logpoint of `{fileName}` or `{filename}` to the following line and debug VS Code using the _VS Code_ launch config
https://github.com/microsoft/vscode/blob/15742965126175e46e70cb3a5bf3662361f3a068/src/vs/platform/diagnostics/node/diagnosticsService.ts#L143

With either the current debugger or js-debug VS Code will hang pretty immediately upon start. Using `{fileName}` as the Logpoint you should see some output before the hang (and it seems to take a bit longer but that could just be perception).

```
Version: 1.45.0-insider (user setup)
Commit: fd5d9a30259bb2bebab3e62dfd8315c2e1b27744
Date: 2020-05-04T09:29:52.824Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by eamodio** [comment]
I also see the same behavior if I add a `console.log(fileName);` statement to that line. But again, only when debugging.

**Comment by isidorn** [comment]
VS Code is not doing anything special with regards to log points. What might happen is that a lot of logs are comming to the debug console and that the debug console causes VS Code to hang (which should not happen).
Though first assigning to @connor4312 to see what is happening on the vscode side
