### ISSUE TITLE
Artifacts on 1440p screen

### ISSUE THREAD

**Issue by nukaboy** [microsoft/vscode#96940]
- VSCode Version: 1.44.2
- OS Version: Windows 10.0.18362
Steps to Reproduce:
1. Launch Code on a QHD (1440p) screen

Does this issue occur when all extensions (and custom designs) are disabled?: Yes

I just used code for the first time on my new QHD monitor, and i noticed weird boxes rendered on the right side of the editor window that only disappear around the line i am editing.

![image](https://i.imgur.com/d1LlCrf.png)

**Comment by IllusionMH** [comment]
Do you have HDR screen?

Looks like duplicate of #88491 see if `code --force-color-profile srgb` works then you can add is as permanent option: https://github.com/microsoft/vscode/issues/88491#issuecomment-589527628

**Comment by nukaboy** [comment]
Thanks, setting `"disable-color-correct-rendering": false` in `argv.json` fixed the issue
