### ISSUE TITLE
Project level snippets apply to all languages and all files

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#96944]
- VSCode Version: Insiders 1.45.0
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. Create a file called `.code-snippets` within the `.vscode` folder in any repository
2. Copy this code to it:
```
{
	"Test": {
		"prefix": "test",
		"body": [
			"<html>",
			"\t<head>",
			"\t\t<title>$1</title>",
			"\t</head>",
			"\t<body>",
			"\t\t$0",
			"\t</body>",
			"</html>"
		],
		"description": "testing project-level snippets"
	}
}
```
3. Notice that while you have this repository opened, this snippet will show up in all files (even other repository files and newly created files) independent of language.

I would expect the snippets configured within this repository to only apply to this repository.

Also, it would make sense to have snippets work like settings: you should be able to apply them at the user level, at the implicit workspace level (inside the .vscode folder) and at the explicit workspace level (inside a .code-workspace file). Would it make sense to create a feature request for this?

Does this issue occur when all extensions are disabled? Yes

**Comment by jrieken** [comment]
That's the design

**Comment by andrecasal** [comment]
Ok, thanks @jrieken!
