### ISSUE TITLE
Notebooks: pasting notebook JSON into notebook should automatically add cells

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#96943]
I've been sharing notebooks with others and keep running to the issue of easily adding/importing notebooks from others. Currently the steps that I do is:

1. Copy notebook JSON
2. Create new txt file
3. Paste notebook json and save
4. Rename output to `{name}.github-issue`
5. View notebook

I would LOVE it if I could just paste in the JSON data into any notebook an have it automatically add the cells to my notebook. Be it on an empty notebook or in an existing one.

**Comment by rebornix** [comment]
We don't know yet if ppl will give it thumbups or not yet.

**Comment by tanhakabir** [comment]
This sounds relevant to this where we need the functionality of automatically switching https://github.com/microsoft/vscode/issues/81832
