### ISSUE TITLE
Flag corrupt or useless extensions in VS code

### ISSUE THREAD

**Issue by HermHack78** [microsoft/vscode#96942]
Need to have an icon like a flag or something that users can click in order to signal a corrupt or useless extension. Could be included in each extension window next to the extension identifier or using the more action dots in the top right of the window to access the flag and notify action.

**Comment by chrisdias** [comment]
If you find an extension that is harmful in any way you can submit an abuse report from the marketplace page for that extension. on the right side of the page you will find a link:

![image](https://user-images.githubusercontent.com/1487073/81092181-1756a300-8eb5-11ea-918c-27fde427378f.png)

We take abuse reports very seriously and will investigate them immediately.

The definition of "useless" is more subjective, it can be the opinion of one person while another finds it useful.  Feedback like that is better suited for the "Ratings & Review" section in the Marketplace for each extension. Informative reviews help the author improve the extension and helps others make better decisions on what to expect.

![image](https://user-images.githubusercontent.com/1487073/81092358-538a0380-8eb5-11ea-9ab1-5b40a2d00167.png)

You can quickly get to the Marketplace page for an extension from within VS Code by selecting the extension and then clicking on the title or stars in the preview shown to the side.

![image](https://user-images.githubusercontent.com/1487073/81092837-0fe3c980-8eb6-11ea-8f58-336aad0de276.png)
