### ISSUE TITLE
Remote status bar item isn't flush with the activity bar

### ISSUE THREAD

**Issue by kdrag0n** [microsoft/vscode#96952]
- VS Code Version: Code - Insiders 1.45.0-insider (fd5d9a30259bb2bebab3e62dfd8315c2e1b27744, 2020-05-04T09:21:17.770Z)
- OS Version: macOS High Sierra 10.13.6

The remote item in the status bar has a filled background that makes it stand out, but it's slightly different from the status bar in terms of width, which looks odd since the they converge in the bottom-left corner:

![image](https://user-images.githubusercontent.com/7930239/81024209-9ac9b300-8e27-11ea-85a3-f56711ff32e2.png)

Steps to Reproduce:

1. Open VS Code
2. Make sure at least one remote extension is enabled
3. Look at the bottom-left corner where the status and activity bars converge

Does this issue occur when all extensions are disabled?: Not if all remote extensions, including the built-in Remote-TestResolver extension, are disabled.

**Comment by misolori** [comment]
I'm personally not a fan of this given that the status bar was never intended to align with the activity bar and that the sidebar can also be placed on the right side. This would also introduce inconsistencies with regular status bar items that use only a single icon. Will close this as `as-designed`.

**Comment by kdrag0n** [comment]
In most areas of the rest of the UI, bars that intersect have matching widths/heights. For example, the tab and search bars have matching heights so they look consistent. When the explorer is open and breadcrumbs are enabled, they still match. In the Settings view, the search and scope bars have the same width. Why should this be an exception to all of the other bars?

It's especially distracting because the remote icon has a background color than the bar it intersects (sidebar), so it stands out more.

**Comment by misolori** [comment]
> Why should this be an exception to all of the other bars?

Unlike the other areas, the status bar doesn't have a fixed-width for the items below. The other areas you mentioned all have a consistent height. That's the difference. Additionally, when the sidebar is on the right side, then this would not look good.

> It's especially distracting because the remote icon has a background color than the bar it intersects (sidebar), so it stands out more.

This is only in the case when you are not connected to remote, otherwise it breaks (which is why I think this wouldn't work here). You can always override this remote background to be transparent if it's too distracting for you:

```json
"workbench.colorCustomizations": {
  "statusBarItem.remoteBackground": "#0000"
},
```
