### ISSUE TITLE
Explorer asks for Workspace ?

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/vscode#96957]
How do I get a workspace to always open when starting or re-starting code.  Currently when I start or re-start code the explorer asks that I open up a folder; this is what I want to resolve.

**Comment by Tyriar** [comment]
What about using `"files.hotExit": "onExitAndWindowClose"` and exiting always by exiting the application (alt+f, x). This will relaunch whatever windows you had opened before.

**Comment by SheepDomination** [comment]
@Tyriar That solution didn't work.

**Comment by SheepDomination** [comment]
Is this a bug ?
