### ISSUE TITLE
Test: Integrated terminal IME support 

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9695]
Test for #7045:

- [x] Windows - **@rebornix**
- [x] OS X - **@kieferrm**
- [x] Linux - **@joaomoreno**

The integrated terminal now supports input via IMEs  (Input Method Editors). During development I tested this across all 3 OS' with Japanese and Korean IMEs as I'm familiar with them. Here are some things to try:

- Install/enable an IME for the OS, preferably not Japanese/Korean
- Test input, if you're familiar with the IME try all the edge cases
  - Multiple character compositions?
  - Multiple keystrokes per character?
  - Multiple characters reducing to a single character?
- Test executing a command using the text (eg. `echo`)

See https://github.com/sourcelair/xterm.js/pull/175 for more details on the change and testing that was performed at implementation time.

**Comment by ZCShou** [comment]
@Tyriar  Cannot follow cursor! The first input is ok ,but The following Input can not work well!

Win10 x64  Chinese IME

**Comment by rebornix** [comment]
@Tyriar try type two Chinese characters then switch to English and type 'abc', you will see the cursor position is wrong, which breaks deleting functionality.

**Comment by Tyriar** [comment]
@ZCShou @rebornix are you experiencing the cursor-related issue I describe at the bottom of https://github.com/sourcelair/xterm.js/pull/175#issue-165207779? I found that input seemed fine but the cursor disappeared so the composition window was never in the right position.

**Comment by rebornix** [comment]
@Tyriar I ran into the issue you described there and the input works fine. Besides, the cursor position comes back if you switch to English IME but the position is wrong, and its offset depends on how many Chinese characters you type

At first, type `abc` and the cursor is at the right of last char.

![image](https://cloud.githubusercontent.com/assets/876920/17124842/958bb988-5320-11e6-9b96-e2c026c15791.png)

Then type a Chinese char `吕` (lv) and `abc` again

![image](https://cloud.githubusercontent.com/assets/876920/17124858/ba791e3e-5320-11e6-9bbe-b231fcdd3523.png)

See above, the cursor is on last char. Then you type `鹏` (peng) and `abc`

![image](https://cloud.githubusercontent.com/assets/876920/17124870/d72f2578-5320-11e6-93b2-afe4a0c69769.png)

The cursor now is on the last two char of text. I suppose its offset is just how many Chinese chars you type. My suspicion is we don't move the cursor position when we handle CJK IME composition?

**Comment by Tyriar** [comment]
The cursor position is handled entirely by the pty though, not vscode. I wonder if this is something to do with https://github.com/Microsoft/vscode/issues/7345 which is an upstream problem that does weird things when using backspace/left/right.

**Comment by joaomoreno** [comment]
@Tyriar I've found it hard to test and even to know whether what I did actually tested your work. I followed a [guide or two](https://www.reddit.com/r/elementaryos/comments/33cfha/multiple_inputs_under_freya_chinese_case_pinyin/) in installing IMEs, I was able to type some Japanese/Korean, but I'm not sure I actually tested what you should be tested.

**Comment by Tyriar** [comment]
@joaomoreno no problems, I did a bunch of testing myself on Linux so hopefully that will be enough.
