### ISSUE TITLE
Dragging activity bar/panel items can activate blurred editor content dragover

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#96951]
- Open settings editor (or notebook)
- Drag an activity bar icon
- The settings editor is blurred but I can scroll it by dragging over the top or bottom of it
- The blurred layer should intercept the dragover event, or, the thing that does DND for these should set something identifiable on dataTransfer so the list can ignore those events if needed

**Comment by sbatten** [comment]
To Verify:
1. Open settings editor (or notebook)
2. Drag an activity bar icon over the editor toward the top or bottom edge

Ensure the editor does not scroll
