### ISSUE TITLE
Highlight problem

### ISSUE THREAD

**Issue by WLcHaok** [microsoft/vscode#96965]
Issue Type: <b>Bug</b>

Just type in a word and instead of it beeing blue it turns green. It happened in a sudden and I don't know what causes it?

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Atom(TM) CPU D2500   @ 1.86GHz (2 x 1866)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|1.98GB (0.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
workspace|Foo|1.1.1
vscode-nuget-package-manager|jmr|1.1.6
vscode-vsproj|jRi|1.2.1
csharp|ms-|1.21.17
unity-tools|Tob|1.2.3
unity-debug|Uni|2.7.5

</details>
![image](https://user-images.githubusercontent.com/64002325/81038804-e50b6c80-8ed9-11ea-8fa4-64ecf14a737d.png)

**Comment by Tyriar** [comment]
This is the C# extension
