### ISSUE TITLE
feature bookmark line

### ISSUE THREAD

**Issue by dungmv** [microsoft/vscode#96961]
Issue Type: <b>Feature Request</b>

I think bookmark line should integrate to the VSCode, this feature very useful

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

**Comment by scriptingstudio** [comment]
> We try to keep VS Code lean and we think the functionality you're asking for is great for a VS Code extension. Maybe you can already find one that suits you in the [VS Code Marketplace](https://aka.ms/vscodemarketplace). Just in case, in a few simple steps you can get started [writing your own extension](https://aka.ms/vscodewritingextensions). See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Happy Coding!

if something is optional (external) it will almost never be used (popular).
