### ISSUE TITLE
Open readme.md by default when opening a new directory/project with one in

### ISSUE THREAD

**Issue by gilescope** [microsoft/vscode#96963]
Open readme.md by default when opening a new directory/project with one in.

For prior art see Jetbrains.

Why: We have a single point of how to get started in a project. If that's stuck in front of people's faces more often it's likely to help people get started AND the information is even more likely to be up to date.

(Config option to disable for sure, but on by default seems best for the world.)

**Comment by gilescope** [comment]
Happy for someone to write this as an extension but honestly I think it's better for everyone if this is baked in by default.

**Comment by gjsjohnmurray** [comment]
Did you see the `workbench.startupEditor` setting?
