### ISSUE TITLE
Open with Code for windows libaries

### ISSUE THREAD

**Issue by YoraiLevi** [microsoft/vscode#96960]
Messing around with context menus on windows I saw that there is no entry point for Open with Code for libraries but `Git` does have one, to unify the experience I have created a snip that adds the functionality.
https://gist.github.com/YoraiLevi/418c973a319008fb2f5c1ebbbd38bad2

As it stands right now, I am using the windows `libraries` feature to aggregate folders together.
It is a little confusing that sometimes `Open with Code` shows up and sometimes it doesn't base on whether I have navigated to the folder directly or accessed through a library shortcut.

**Comment by joaomoreno** [comment]
Libraries aren't actually folders in your system, so what folder could Code open?

**Comment by YoraiLevi** [comment]
> Libraries aren't actually folders in your system, so what folder could Code open?

Libraries have 'default save location' Code opens that
![image](https://user-images.githubusercontent.com/50873841/81579551-fad6d100-93b4-11ea-9312-24b630ec4acd.png)
![image](https://user-images.githubusercontent.com/50873841/81579615-07f3c000-93b5-11ea-9a42-8eacf1bfb716.png)
![image](https://user-images.githubusercontent.com/50873841/81579802-425d5d00-93b5-11ea-80e1-c0860c518b97.png)

but doing this:
![image](https://user-images.githubusercontent.com/50873841/81579838-4f7a4c00-93b5-11ea-994b-a4ab8dc82bcc.png)
results in an error
![image](https://user-images.githubusercontent.com/50873841/81579705-25c12500-93b5-11ea-9d31-52d26374ae7e.png)


This is useful for my workflow because I press on the left side panel to go to my 'source' library and then navigate to my source folder, inside.
Unless this registry key is added, it is 'random' whether 'Open with Code' shows up in the nested folders.
aka, navigating to 'repos'(nested inside the source library) might not have the 'Open with Code' because windows treats the entire explorer window as a library location.

**Comment by joaomoreno** [comment]
Interesting.

**Comment by YoraiLevi** [comment]
seem simple enough, i'll see when I have the time! thanks

**Comment by mitchell-frost** [comment]
Can I work on this?

**Comment by YoraiLevi** [comment]
> Can I work on this?

Yea, I wrote the 3 lines that are supposed to work on a fork on my github, I just don't have the time to setup an enviroment to check it and verify that that's how it should be done

**Comment by YoraiLevi** [comment]
Updating: Personally I am still using my own registry "hack", I noticed an issue regarding passing arguments since an recent update to(Updating it manually as needed for myself)
![image](https://user-images.githubusercontent.com/50873841/87878923-fef42000-c9ef-11ea-99fd-8d27692b287d.png)
the update changed the context menu commands to:
`"C:\Program Files\Microsoft VS Code\Code.exe" "%1"`
but this doesn't work for libraries for some reason, yet the old %V option does.
`"C:\Program Files\Microsoft VS Code\Code.exe" "%V"`
