### ISSUE TITLE
Javascript Literal Strings

### ISSUE THREAD

**Issue by Cypherjac** [microsoft/vscode#96975]
Issue Type: <b>Bug</b>

I have an XMLHttpRequest function:
`id_generate.open("GET", origin + "php/server/visitors.php", true);`

Which I wanted to convert to this template string:
```
id_generate.open("GET", `${origin}php/server/visitors.php`, true);
```

When I was converting it manually (because vscode shows a certain yellow bulb where you can select the option of converting to a literal string and it is done automatically), I got this error:
Unterminated string literal: ',' expected.

When I click on the error, it takes me to this line: 
```
id_generate.open("GET", `${origin}php/server/visitors.php`, true);
                          ^^^^^
```

First, there is no problem with that literal string.
But here is where the bug is:

I convert it back to the original value:
`id_generate.open("GET", origin + "php/server/visitors.php", true);`

But the error in the console is still indicating at the exact same place where it was before.
Then the comma after ....php"**,** has a certain pale red underline which is wavy that indicates that is where the error is.
So I backspace the comma, then the wavy underline now moves to the space which is after the comma [NOTE: I have backspaced the comma and it is no longer there]
Then I backspace that whitespace leaving this value below:
...php"**t**rue);
Now in this case, the wavy underline has shifted and is under the letter "t" of the word "true".
So I keep backspacing while rewriting the original string, here is what I mean,
I backspace the word **true**, then I rewrite it again, after that the wavy underline now shifts to the closing bracket: ...php"true**)**;
[NOTE: This whole time, the error in the 'PROBLEMS' section of the console, is still showing the same error, even after saving the file, and there is not any string literal in my code]
To explain further, the bug is that there is still an error in the console and the wavy underline keeps shifting position each time I backspace the character on which it was on (be it a whitespace, a bracket, double quotes ... all characters)

Here is the image showing the wavy character I am talking about and the string which I converted back to a literal string --- with no issue whatsoever but the wavy line and the error in the console are the problems(bugs):

[NOTE: In the snips below the `origin` variable is the `or` variable and I also removed the parameter passed to the function as an attempt to see if the error would change but the error doesn't change at all.
Even after commenting out the entire code in the file, the wavy line you see at the bottom of the snip that has now shifted position still remains visible and the error still stays there]

<img width="353" alt="VSsnip" src="https://user-images.githubusercontent.com/59499095/81055492-70cccb00-8ed1-11ea-9ec7-54a932c6dd8e.PNG">

Below is the error in the console that doesn't seem to leave even after commenting out the whole code in the file
<img width="248" alt="Capture2" src="https://user-images.githubusercontent.com/59499095/81055598-b4bfd000-8ed1-11ea-9939-75d2dec93eb7.PNG">

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-browser-preview|auc|0.6.6
vscode-intelephense-client|bme|1.3.11
vscode-eslint|dba|2.1.3
python-preview|don|0.0.4
vscode-npm-script|eg2|0.3.11
php-debug|fel|1.13.0
vscode-firefox-debug|fir|2.7.2
vscode-npm|fkn|3.3.0
vs-code-http-server-and-html-preview|Fli|2.2.2
chartjs-markdown-preview|Flo|0.0.2
code-runner|for|0.9.17
vscode-mysql|for|0.4.0
live-html-previewer|hdg|0.3.0
url-preview|Her|0.0.2
composer|ika|0.7.1
phpcs|ika|1.0.5
Untabify|ili|0.0.2
mysql-scratchpad|jbl|0.1.1
php-cs-fixer|jun|0.1.151
vscode-inline-svg|kon|0.9.4
Anyview|luf|0.0.4
csharp|ms-|1.21.17
mssql|ms-|1.9.0
python|ms-|2020.3.71659
remote-wsl|ms-|0.42.4
Go|ms-|0.14.1
debugger-for-chrome|msj|4.12.6
live-server-preview|neg|0.1.4
vscode-json-editor|nic|0.2.3
mysql-inline-decorator|odu|0.0.5
javascript-test-runner|osh|1.2.1
vscode-chartjs|Ran|1.2.0
java|red|0.59.1
preview-vscode|sea|2.1.0
svg-preview|Sim|2.8.3
html-preview-vscode|tht|0.2.5
vscode-svg-previewer|vit|0.5.1
vscode-java-debug|vsc|0.25.1
vscode-java-test|vsc|0.22.3
json|Zai|1.0.4

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Cypherjac** [comment]
So I disabled all extensions and that seemed to make things even worse: Here are the snips of the error after disabling all the extensions:
<img width="376" alt="snip2" src="https://user-images.githubusercontent.com/59499095/81091970-9d500980-8f08-11ea-94cb-39d7431b49d1.PNG">

 The error is still showing, but now the error in the console jumped upto 35, it was affecting even other parts of the file that I didn't touch.
This is just a section of the error in the console:
<img width="289" alt="snip3" src="https://user-images.githubusercontent.com/59499095/81092151-de481e00-8f08-11ea-8a2a-a300d2307ca9.PNG">

**Comment by Cypherjac** [comment]
So I tried with the latest vscode insiders build, though now I have 2 vscode editors on my PC ... but anyway, I have _error-tested_ the same file again by trying to convert that section of the file into a template string, then reconvert it again to its original form and it doesn't seem to show any error afterwards.
This means the error has been patched in the latest build of **vscode - insiders** ,
