### ISSUE TITLE
Emmet change direction modifier doesn't work

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#96977]
- VSCode Version: Insiders 1.45.0
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. On an HTML file, write `div>li.item$@-3*5` and press `Tab`
2. Notice that the change direction modifier `@-` did not apply

Does this issue occur when all extensions are disabled? Yes

**Comment by rzhao271** [comment]
Duplicate of #69168
