### ISSUE TITLE
Test: Provide a separate 'Insert snippet' command that allows the user to pick a snippet

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9697]
Test for #9072, #9122, #6320, #9286:

- [x] Windows - **@DonJayamanne**
- [x] OS X - **@Tyriar**
- [x] Linux - **@kieferrm**

There is a new command to insert snippets. Verify that
* there is a _Show Snippets_ command in `F1`, and that
* it does what you expect

**Comment by waderyan** [comment]
I'm not seeing a `Show Snippets` command. 

![image](https://cloud.githubusercontent.com/assets/2449568/17156045/94d67142-533c-11e6-94fa-09cf7b69edb8.png)

**Comment by DonJayamanne** [comment]
@waderyan, @Tyriar, that's odd I just tested this on my OSX and it works! Thought I'd mention that.
@Tyriar, yes I have tested this on windows and it works as expected (thought I'd test on OSX as well, as that's my primary OS)

**Comment by Tyriar** [comment]
@DonJayamanne are you on the same commit as Wade's in the screenshot?

**Comment by DonJayamanne** [comment]
@Tyriar, identital
<img width="289" alt="screen shot 2016-07-27 at 12 57 38" src="https://cloud.githubusercontent.com/assets/1948812/17162476/c338a47a-53f9-11e6-9c14-a13edf191593.png">

**Comment by egamma** [comment]
Works for me on both OS X and Windows.

**Comment by egamma** [comment]
Suggest to make labels matching Snippets (`Show Snippets`, `Preferences: Snippets`) more distinct, e.g.,:
`Insert Snippet`, `Preferences: Edit Snippets`

![image](https://cloud.githubusercontent.com/assets/172399/17166372/e17156b2-53d6-11e6-9bae-cda882ca2567.png)

**Comment by waderyan** [comment]
Ok I see it now. Weird it didn't show yesterday.

**Comment by bpasero** [comment]
@jrieken maybe this was discussed when I was on vacation but is there a reason we cannot show the list of snippets in the intellisense widget? I find it better to show the snippets closer to where I am typing.

**Comment by jrieken** [comment]
Yeah, it's mostly to be aligned with other editors and to avoid ambiguity between snippets and the current line text wrt to filtering, selection etc. Last there technical debt that didn't allow it ;-) We figured ship it and wait for feedback ;-)

**Comment by bpasero** [comment]
Ok. because I think it would be cool if I could assign a keybinding like 

`{ "key": "ctrl+space", "command": "editor.action.showSnippets", "when": "editorTextFocus && suggestWidgetVisible" }`

And then essentially I could show snippets only by pressing Ctrl+Space twice (similar to Eclipse).
