### ISSUE TITLE
Horizontal scrolling is not supported or broken

### ISSUE THREAD

**Issue by evgarthub** [microsoft/vscode#96986]
Device: Logitech MX Masters 2S (with horizontal scroll wheel)
OS: Windows 10 Pro

Steps to reproduce:
1a. Open many files at point when opened tabs require more that available window width, so scrolling is required in order to navigate to last/first tab.
2a. Hover over line with tabs and use scroll wheel (horizontal one)

1b. Open file with content that requires more horizontal space that is available in your window, so horizontal scroll appeared.
2b.  Hover over editor and use scroll wheel (horizontal one)

Actual result (a, b):
Inconsistent, can scroll a bit and then won't work at all, or doesn't work immediately.

Expected result (a):
Horizontal and vertical scroll wheels do the same, scroll through tabs.
Expected result (b):
Vertical scroll wheel scrolls lines of code (vertically)
Horizontal scroll wheel scrolls to the end/start of the line (horizontally)

**Comment by bpasero** [comment]
@evgarthub to clarify, horizontal scrolling does not work also in the editor for you when the line is long?

**Comment by evgarthub** [comment]
@bpasero indeed, I noticed that when it stops working I need to find another window/program with horizontal scroll do scrolling there and then VSCode scrolling start working again.

**Comment by bpasero** [comment]
Sounds like https://github.com/microsoft/vscode/issues/84136 however on Windows. Moving to you Deepak.

**Comment by arbraham** [comment]
I got the same issue. The horizontal scroll works in DOC, chrome, etc., but always fails in VSC at the first time. After I open a DOC and try the scoll, open VSC, left click the horizontal bar, then I can do horizontal scroll in VSC, but it still always fail like losing the focus on the bar.

**Comment by ahmedhassan-eng** [comment]
Same here. Just moved from Sublime to VS Code and was wondering what's wrong.
- Windows 10 Enterprise 1709. 
- VS Code 1.45.1 User Setup. 
- Mouse MX Master.

I can confirm the behavior/ workaround below:

> @bpasero indeed, I noticed that when it stops working I need to find another window/program with horizontal scroll do scrolling there and then VSCode scrolling starts working again.

**Comment by CiriousJoker** [comment]
Possibly related:

- https://github.com/electron/electron/issues/20874
- https://bugs.chromium.org/p/chromium/issues/detail?id=1044457

**Comment by yijiangw** [comment]
If Logitech Options has been uninstalled, the horizontal scroll wheel will work well on vscode. And if old version of  Logitech Options is installed, that scroll wheel even cannot work on Chrome.

**Comment by dvdvnl** [comment]
I have the same issue with:

* Logitech MX Master 2S
* Logitech Options 8.20.329
* Windows 10 Pro (10.0.19041)
* VSCode 1.47.3

I too can verify this behaviour:
> @bpasero indeed, I noticed that when it stops working I need to find another window/program with horizontal scroll do scrolling there and then VSCode scrolling starts working again.

**Comment by JinZhenlin** [comment]
I am experiencing the same issue: 

- Logitech MX Master 3
- Lotitech Option: Lastest Version (Cannot find the version on Windows) 
- Windows 10 Enterprise, 10.0.18363 
- VS Code Version 1.50.1

Also, I noticed it was working for an initial 0.5 second when I scroll horizontally. After that half second, it stops working.

**Comment by deepak1556** [comment]
Merging this to https://github.com/microsoft/vscode/issues/84136
