### ISSUE TITLE
Event listener leak in WalkThroughPart

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#96988]
I just had this window opened like this for a couple hours and this warning showed up:

![image](https://user-images.githubusercontent.com/22350/81065478-dc1b9a80-8edb-11ea-84bd-5a18b9404363.png)

**Comment by joaomoreno** [comment]
After half an hour:

![image](https://user-images.githubusercontent.com/22350/81070455-8ba83b00-8ee3-11ea-84aa-4fdb483b322f.png)

**Comment by chrmarti** [comment]
@joaomoreno Looks like your listener: https://github.com/microsoft/vscode/blame/master/src/vs/workbench/browser/parts/editor/baseEditor.ts#L203
