### ISSUE TITLE
Test: Support tab completion for snippets

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9698]
Test for #9579:

- [x] Windows - **@egamma**
- [x] OS X - **@joaomoreno**
- [x] Linux - **@aeschli**

There is a new configuration property `editor.tabCompletion` which defaults to `false`. When set to `true` verify that

* pressing the <kbd>Tab</kbd> key when the cursor follows a snippet prefix expands the snippet
* reason about the name of this setting (`tabCompletion`) - rationale was that folks know this feature as _tab completion_
* make sure things are live: run the `Preferences: Snippet` to define a new snippet and make sure it works without restart
* use prefixes with non-word characters like `c'l` and make sure it works

**Comment by gerane** [comment]
@Tyriar Would this work for extension snippets as well? Meaning if you have an extension that creates a new snippet, would it still require a restart for the new extension snippet to be loaded?

**Comment by jrieken** [comment]
yes - in order to activate extension you need to reload the editor

**Comment by aeschli** [comment]
I like it, I think we should enable it by default.
The conflict with Emmet is not really a problem given that we have no default snippets for html and the user just needs to pick non conflicting snippet names.

**Comment by jrieken** [comment]
@aeschli Ideas about the name `tabCompletion` vs `snippetTabCompletion`?

**Comment by joaomoreno** [comment]
I like the current proposal, but I think adding the prefix `snippet` would benefit it as the feature only revolves around snippets...

**Comment by aeschli** [comment]
I'd stick with tabCompletions, it seems to be an established term e.g. in shells. snippetTabCompletion is a strange construct, maybe rather snippetCompletionOnTab or snippetExpansionOnTab

**Comment by Tyriar** [comment]
Closing this off since the test is complete.
