### ISSUE TITLE
Duplicated files opened, breakpoints not visible

### ISSUE THREAD

**Issue by WurmD** [microsoft/vscode#96997]
Issue Type: <b>Bug</b>

1) Connect through SSH to ubuntu machine
2) Set breakpoint in first line of main()
3) "Start Debugging"

Duplicated file is opened where:
 - Breakpoints are not visible (but execution stops in set breakpoint)
 - File path with prepended "/mnt"

![image](https://user-images.githubusercontent.com/2193314/81087231-4d445900-8eae-11ea-9090-9c1252eda0ff.png)

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.15.0-96-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (17.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 144.76.103.190|
|OS|Linux x64 4.15.0-96-generic|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 900)|
|Memory (System)|62.77GB (2.62GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
cmake-tools|ms-|1.3.1
cpptools|ms-|0.27.1

</details>

**Comment by WurmD** [comment]
@weinand , what extension? How are you determining that?

**Comment by weinand** [comment]
cpptools, the C++ extension.
