### ISSUE TITLE
Cannot attach to extension host in container

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#96995]
Issue Type: <b>Bug</b>

That is a local extension host running the container while VS Code is connected to the container with Remote-Containers.

I see this with `Debug: Attach to Node Process` and the preview version of that.

![image](https://user-images.githubusercontent.com/9205389/81069542-518a6980-8ee2-11ea-9395-15747b59b859.png)

![image](https://user-images.githubusercontent.com/9205389/81069485-36b7f500-8ee2-11ea-87c2-65bfb8a33bc8.png)

VS Code version: Code - Insiders 1.45.0-insider (d4b8ec9da3bf1061a948fbb1b0d9d3db750cc79f, 2020-05-05T07:13:27.726Z)
OS version: Darwin x64 19.2.0
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.36GB free)|
|Process Argv|-psn_0_1974754|
|Screen Reader|no|
|VM|22%|

|Item|Value|
|---|---|
|Remote|Container vscode-remote-containers_devc…|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|Memory (System)|7.78GB (1.77GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|eam|0.1.1
vscode-docker|ms-|1.1.0
remote-containers|ms-|0.115.99
remote-ssh-edit-nightly|ms-|2020.4.9540
remote-ssh-nightly|ms-|2020.4.9540
remote-wsl|ms-|0.44.2
debugger-for-chrome|msj|4.12.6
vscode-eslint|dba|2.1.5
vscode-pull-request-github|Git|0.16.0
vscode-docker|ms-|1.1.0
python|ms-|2020.4.76186
vscode-versionlens|pfl|0.26.1
vscode-open-in-github|sys|1.13.1

</details>

**Comment by weinand** [comment]
@chrmarti what do you mean by "preview version of that"?
Of what?

**Comment by chrmarti** [comment]
@weinand I have `Debug: Attach to Node Process` and `Debug: Attach to Node Process (preview)` in the command palette.

**Comment by weinand** [comment]
Aha, now I understand...

**Comment by connor4312** [comment]
Thanks for the issue. Inside the bootloader called when programs are launched, we spawn a separate "watchdog" process that we use to set up communication since "wait for inspector" action that we run in the debugee is synchronous and blocks the main thread. We did the same thing for processes we attached to (not just those we launch) since the machinery was already built for that.

Therefore, we required Node to spawn the process to attach to any program. However, when js-debug itself is doing the attachment, it can run the necessary logic in the extension host process directly and we can avoid spawning a separate process.

**Comment by chrmarti** [comment]
Verified when starting the target with a fixed port:
```
/bin/code-insiders --extensionDevelopmentPath=`pwd` --inspect-extensions 1234
```

The preview version doesn't show the process and the non-preview version fails to attach when starting without fixed port:
```
/bin/code-insiders --extensionDevelopmentPath=`pwd`
```

The non-preview version appears to use `0` as the port:
![image](https://user-images.githubusercontent.com/9205389/83855266-1f09a180-a718-11ea-9a01-9d5377745ad4.png)

Not sure if this is a known limitation, but the non-preview version should at least not try to connect to port 0. Extracting a new issue for that.
