### ISSUE TITLE
Proposal for separating the vscode tools from the vscode API

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#970]
Currently the vscode node module combines the tools and the vscode API into one unit, we want to decouple the API from the used modules.

Support that the vscode tools and its API can evolve separately.

**Comment by bpasero** [comment]
Here is the proposal that you can already try out by installing the generator from the next branch:

`npm install --g generator-code@next`

* an extension is now generated with a npm post install script that will download the correct version of vscode.d.ts depending on the engine field of the extension
* the logic to find the right version to download is by applying a semver check and taking the smallest vscode version that qualifies the engine version
* you can specify to depend on `vscode: "*"` and this will pull down the vscode.d.ts as we have it on master

To not break existing extensions, we publish the `vscode` module as version `0.2.0`. 

In order for existing extensions to adopt this change:
* change dependency of `vscode` to `0.2.0`
* add the following scripts section to `package.json`:

```
"scripts": {
   "postinstall": "node ./node_modules/vscode/bin/install"
}
```
* adjust the `engine` field for vscode depending on API needs
* run `npm install` to pull  down the correct vscode.d.ts version

**Comment by felixfbecker** [comment]
@bpasero Should `vscode` be a dependency or a `devDependency`?

**Comment by bpasero** [comment]
@felixfbecker devDependencies
