### ISSUE TITLE
Dragging an unfocused view focuses it

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#97005]
![recording (41)](https://user-images.githubusercontent.com/22350/81083132-7d164f80-8ef4-11ea-900a-1257f51ea32f.gif)

**Comment by sbatten** [comment]
@joaomoreno this is not new, this has been this way for as long as I can recall

**Comment by joaomoreno** [comment]
@sbatten I also have bugs that have been there since a long time, but they are still bugs.

Here's the Windows explorer:

![recording (43)](https://user-images.githubusercontent.com/22350/81160800-d7fa8600-8f8a-11ea-8c44-f58254322795.gif)

And Slack:

![recording (44)](https://user-images.githubusercontent.com/22350/81160955-142de680-8f8b-11ea-95cd-34d6f1b74bb2.gif)

And VS Code:

![recording (45)](https://user-images.githubusercontent.com/22350/81161019-332c7880-8f8b-11ea-86b3-5d8ee32d9ea3.gif)
