### ISSUE TITLE
Commit msg box doesn't use consistent indentation

### ISSUE THREAD

**Issue by Alex131089** [microsoft/vscode#97009]
- VSCode Version: 1.44.2
- OS Version: Win 10 1809

Steps to Reproduce:

1. In a project using a CVS (Git in my case), enter commit message, indenting a line using spaces
2. Type enter
3. Next line will be indented using tab and not spaces as the previous line

Does this issue occur when all extensions are disabled?: Yes

Example of resulting commit msg: 
```md
test

  * line 1 indented with 2 spaces[enter]
	* line 2 is automatically indented with a tab instead of 2 spaces, no consistency
```

Related custom settings:
```jsonc
{
    "editor.detectIndentation": true, // default
    "editor.tabSize": 2,
    "editor.insertSpaces": false,
}
```

This is to reopen #92148.

**Comment by Alex131089** [comment]
Why mixing tab and spaces? Shouldn't the commit msg use consistent style?

To respond to https://github.com/microsoft/vscode/issues/92148#issuecomment-608336182 : I don't know about a setting, do what you consider best, but I think the commit msg should use a consistent indentation style and the **code editor** user preferences shouldn't override that (so maybe a dedicated setting if people want that strange behavior, I don't know).

**Comment by Tyriar** [comment]
Might be related to the temporary git commit file being outside the workspace?

**Comment by joaomoreno** [comment]
It's related to this being a standalone editor. We can inherit the editor settings here.

**Comment by joaomoreno** [comment]
Actually I can't reproduce this.

![recording (3)](https://user-images.githubusercontent.com/22350/81544915-66e71400-9378-11ea-9fd3-b50528f34c8a.gif)

@Alex131089 Can you please provide a [screen recording](https://gifcap.dev/)?

**Comment by Alex131089** [comment]
Start command line : `Code.exe --disable-extensions Z:\Path\To\lib_network_tests`
Version : still 1.44.2 for now

![recording](https://user-images.githubusercontent.com/1735067/81699514-c243ff80-9467-11ea-8706-a99bfee1d4ba.gif)

**Comment by Alex131089** [comment]
```
"editor.insertSpaces": false
```
seems to be required to have this behavior

**Comment by joaomoreno** [comment]
Got it. But if you have `insertSpaces` set to `false`, why would you expect spaces to be inserted there?

**Comment by Alex131089** [comment]
I tried to explain it in a previous comment but anyway, it's because *to me* this box is not a *code editor*, it's a box to type you commit message.

The way I see it:
* It's not a *code* editor, why should it follow it's rules?
  * The indentation style is not respected and leads to malformed commit message (especially with `editor.tabSize=<number of spaces in previous line>`)
  * Maybe add dedicated setting to control this box independently if you want, I don't know
* If you absolutely want to consider it as a *code* editor, then I checked and I have `"editor.detectIndentation": true`, so I'm not sure it's working as expected?

**Comment by joaomoreno** [comment]
Simple input boxes wouldn't even preserve indentation, but I guess you're also not in favor of disabling autoIndent?

Detect indentation is working, but the detection happens only when the _file_ is open, not as you type.

**Comment by Alex131089** [comment]
> I guess you're also not in favor of disabling autoIndent?

In the commit msg box only? Yes you can, I don't think I would be bothered and I seem to remember/understand this was the behavior not so long ago? But it may bother other people 😅

> Detect indentation is working, but the detection happens only when the file is open, not as you type.

Yes I saw that in the setting description, I wasn't sure it tries to redetect after a while / after there's new content, or not. Maybe this feature could act differently, by deciding indentation style on first indented line typed, when the file is initially empty?

**Comment by joaomoreno** [comment]
@alexdima Let me try to summarize this for you: Is there any way _delay_ the auto indentation detection until it is actually needed, ie when the user presses `Enter` at the end of a line which is actually indented?

**Comment by alexdima** [comment]
@joaomoreno You could call `model.detectIndentation(defaultInsertSpaces, defaultTabSize)`. If the buffer does not have sufficient indentation to make a good guess, the passed in `defaultInsertSpaces` and `defaultTabSize` are used.

If you allow these settings to be customizable via a language selector in user settings, then you should do this only when `editor.detectIndentation` is set to `true`, and you can read the `defaultInsertSpaces` and `defaultTabSize` from the settings with the help of the model service e.g.:
```ts
let creationOpts = modelService.getCreationOptions(model.getLanguageIdentifier().language, model.uri, model.isForSimpleWidget);
model.detectIndentation(creationOpts.insertSpaces, creationOpts.tabSize);
```

**Comment by joaomoreno** [comment]
> @joaomoreno You could call `model.detectIndentation(defaultInsertSpaces, defaultTabSize)` any time you want. If the buffer does not have sufficient indentation to make a guess, the passed in `defaultInsertSpaces` and `defaultTabSize` are used.

This is fantastic, I wasn't aware of this API!
