### ISSUE TITLE
Add extension name (before or after) the command in palette

### ISSUE THREAD

**Issue by copdips** [microsoft/vscode#97001]
Some extensions (often for the same usage) create the some actions with the same names or same prefixes, which makes the users unable to know which action is for which extension.

I installed several extensions on postgresql, below example is a search result from the quick action (F1) by searching the keyword `postgre`:

The last 2 actions give the extension name, it's good for me. But for others, all of them have the prefix `PostgreSQL:`. Is it possible to add the extension names to all the actions ?
 
![image](https://user-images.githubusercontent.com/13083856/81078095-11c97f00-8eee-11ea-9fc7-b377f79503cb.png)

**Comment by bpasero** [comment]
I am not convinced this is wise given only in corner cases this happens. We already ensure that the command ID shows up if the name truly is identical.

**Comment by copdips** [comment]
@bpasero 
It's not only for distinguish same name command across the different extensions, it's also for let the users to know which command is from which extension.

Refer to the given screenshot example, how do user know the commands prefixed by `PostgreSQL:` are from which postgre extension?

**Comment by bpasero** [comment]
Yeah I get it, might also be nice to know the extension to maybe uninstall it in case there are unwanted commands.

@sandy081 what do you think about showing the extension name as description of a command?

**Comment by sandy081** [comment]
Not a big fan to show it in the command palette by default. Since it is a trouble shooting case, how about adding a separate command to trouble shoot commands showing the extensions contributing them?

**Comment by bpasero** [comment]
Yeah maybe. Could also experiment with showing the extension in a hover when you hover over the command?

**Comment by sandy081** [comment]
May be.

**Comment by copdips** [comment]
any updates please?

**Comment by heartacker** [comment]
> 是的，也许。当您将鼠标悬停在命令上时，还可以尝试在悬停中显示扩展名吗？

YES, I REALLY NEED THIS

**Comment by copdips** [comment]
@bpasero @sandy081,

Although this issue is closed due to the lack of vote up, is it possible to review the needs, it's more a less a bug, and makes the extension confusing.

**Comment by bpasero** [comment]
I would reach out to extensions to e.g. add prefixes to better distinguish.

**Comment by copdips** [comment]
@bpasero ,
totally agree, if it's not difficult to be implemented.
