### ISSUE TITLE
Generate SNMP traps

### ISSUE THREAD

**Issue by mahesh4576** [microsoft/vscode#97015]
Dear All,
We have 2 servers with centos 7 & running few applications on "server A". 3rd party monitoring system is installed in "server B" & it is supporting SNMP traps.
I need to generate SNMP traps from "server A" to monitor services status in running applications. Please find each steps below for more information about my requirement. 
1. Create a shell script to check the running status of all the services & save in separate files.
2. create a shell script to read the each results & generate SNMP traps
3. Configure 3rd party system to monitor system applications status via generated SNMP traps

I can do the 1st & 3rd points. But i need support for 2nd point. Do you have some idea how can i write a script?

**Comment by Tyriar** [comment]
Is this a feature request for VS Code? SNMP traps don't appear to have anything to do with a code editor?

**Comment by mahesh4576** [comment]
Hi,
This is not a feature request.
I have only small knowledge about the SNMP traps for monitoring activities.
Is there a possibility to do my step 2 via SNMP V3. As i describer more, if i installed SNMP V3 on "server A", can I generate SNMP traps via SNMP V3 with supporting shell script. Hope shell script is used to read some service running status & generate SNMP traps.

**Comment by Tyriar** [comment]
It really seems like this has nothing to do with vscode.

**Comment by mahesh4576** [comment]
Noted & thank you for the feed backs.
