### ISSUE TITLE
Restarting debugging fails (inconsistently)

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#97013]
- VSCode Version: 1.44.2
- OS Version: Windows 10, Linux SSH

Steps to Reproduce:

1. Use remote SSH to Linux server
2. Debug some big Python code (TensorFlow, NVidia GPU, large amounts of RAM, etc. etc.)
3. Decide to restart Debugging (e.g., on exception, on breakpoint, ...)

This often works, but sometimes simply fails. Then, Restart has the same effect as Stop.

Does this issue occur when all extensions are disabled?: No (but irrelevant, I need the Python extension)

I get this error log:

```
  ERR timeout after 1000 ms: Error: timeout after 1000 ms
    at t.RawDebugSession.handleErrorResponse (file:///C:/Users/bers/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3044:67)
    at file:///C:/Users/bers/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3043:339
    at async t.RawDebugSession.shutdown (file:///C:/Users/bers/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3041:336)
    at async e.terminate (file:///C:/Users/bers/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6272:211)
    at async e.restartSession (file:///C:/Users/bers/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6299:430)
```
Can I increase this timeout somehow to investigate whether it's just a timing issue?

**Comment by isidorn** [comment]
@bersbersbers you can change this 1000 to any other number here 
https://github.com/microsoft/vscode/blob/15e13c94c8dbc05e0e4b61424d0ed4bc6b10bff1/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L494
Just for experiment: you can look at the minified sources of vscode, saerch for 'disconnect' and change the 1000 after it. That should hopefully change it.

**Comment by bersbersbers** [comment]
@isidorn, thanks! I tracked down the code in `C:\Users\bers\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.js`. In this file, I found `try{await this.send("disconnect",{restart:t},void 0,1e3)}` and changed `1e3` to `1e4`.

My installation of VS Code is now [unsupported](https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt-unsupported), but that is fine. The problem has not re-appeared since. I still may need a couple of hourse or days to confirm it's gone, will get back to you here.

**Comment by isidorn** [comment]
@bersbersbers ok. We can increase that timeout to 2000 by default. And if that does not fix it we might introduce a setting (which I would personally not like).

**Comment by weinand** [comment]
@isidorn we have to be careful when changing the timeout of a disconnect, because it affects your "restart" logic both for normal debugging and EH debugging (where old sessions and new sessions might overlap and you keep things around in some maps).

Maybe another option could be to swallow the timeout silently?

**Comment by bersbersbers** [comment]
> Maybe another option could be to swallow the timeout silently?

A short update from me: setting the timeout to 10s fixed the issue for me. Setting it to 2s still seemed to be insufficient sometimes. This whole thing fits into the larger scheme of me using an ordinary laptop (Dell E6440) and SSH remoting over VPN, where other timing-based issues are frequently arising. For example, https://github.com/microsoft/vscode-python/issues/9393; or, very similarly, switching the debug configuration shortly *after* pressing F5, in which case also the *new* debug configuration is (incorrectly) started.
So anything that helps avoid these timing-based behavior would certainly be appreciated ;)

**Comment by xackus** [comment]
I am affected by this when debugging a C++ program on a machine in my local network.
I haven't encountered any other timing issues.
