### ISSUE TITLE
Test: API - support group ordering for menu contributions

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9702]
Test for #9153:

- [x] any os - **@chrisdias**
- [x] macOS - **@weinand**

When using the [`menuitems`](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus) contribution point, you can control the order of menu items and of menu item groups. Verify that:
* groups are sorted lexicographically - except for the `navigation` group which comes first always
* menu items are sorted lexicographically when they just specify a group. When the group matches a  pattern like `some_group@10` the number used to promote/demote the item.

**Comment by weinand** [comment]
@jrieken I suggest to mention the predefined non-obvious group names in the doc, e.g. the name of the "Cut/Copy/Paste" group.

**Comment by jrieken** [comment]
Agree - we should document the groups we define by default
