### ISSUE TITLE
Go to file shortkey is not working (ctrl + p)

### ISSUE THREAD

**Issue by Xumochuan** [microsoft/vscode#97035]
Issue Type: <b>Bug</b>

Hi
I love Visual Studio code very much.
By the way, shortkey <ctrl + p> is not working, but other shortkeys work well.
I have to click "go to file..." from "menu".
Thanks

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (6.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexdima** [comment]
Which commands are bound to the desired key combination?

e.g. You can search for `"ctrl+p"` with the quotes:
![keyboard-conflicts](https://cloud.githubusercontent.com/assets/5047891/25484174/38f5b004-2b59-11e7-994b-dfa96ef043ce.gif)

**Comment by Xumochuan** [comment]
Hi, @alexdima 
Great.
There were 2 shortcuts about "go to file..."

![image](https://user-images.githubusercontent.com/47884397/81510782-13a89d80-9347-11ea-9da8-00b9b18b8b72.png)

Ctrl+E is working. 
Thanks
