### ISSUE TITLE
Command line option to kill language server

### ISSUE THREAD

**Issue by dashesy** [microsoft/vscode#97036]
I use project with Python/C++ over SSH.
After few days of use, I guess VSCode updates and previous language server processes remain dangling.
What is the best way to kill them all?

Something like `killall node` does not kill them.

**Comment by dbaeumer** [comment]
This is a problem of the Python / C++ language server. The should exit if their parent process dies / disappears. Can you please file the issue against the owner of the language server that is leaking.
