### ISSUE TITLE
Test: API - support for document link provider

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9703]
Test for #1805:

- [x] any os - **@waderyan**
- [x] macOS - **@weinand**

We added new api that allows to [register link providers](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3814) for documents. Verify that
* the API makes sense and fits into the `languages` namespace
* the API docs makes sense
* there is always the default link provider (works for http, https, and file schemas)
* cases when links touch or intersect are resolved by using the link from the [higher](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3606) ranked provider
* for advanced cases there is a command `vscode.executeLinkProvider` that allows to retrieve the same data the UI uses

**Comment by waderyan** [comment]
@weinand how did you test these three? 

* there is always the default link provider (works for http, https, and file schemas)
* cases when links touch or intersect are resolved by using the link from the higher ranked provider
* for advanced cases there is a command vscode.executeLinkProvider that allows to retrieve the same data the UI uses

The function is not available to me. I'm on the latest Insiders version, updated to the lasted code-generator, and created a new extension. 

![image](https://cloud.githubusercontent.com/assets/2449568/17155719/3050ecd0-533b-11e6-8e37-ea72aac3cfcb.png)

**Comment by jrieken** [comment]
@waderyan In the `package.json` of your extension you must set the version of the vscode  dependency to `*`. Only then it downloads the latest api shapes

**Comment by weinand** [comment]
@waderyan I just copied the vscode.d.ts manually into my extension.

**Comment by waderyan** [comment]
Great that did it :)
