### ISSUE TITLE
Var in function gets Codelens if same name

### ISSUE THREAD

**Issue by pushkine** [microsoft/vscode#97032]
1.44.2
```
	"typescript.implementationsCodeLens.enabled": true,
	"typescript.referencesCodeLens.enabled": true,
```

```ts
function x(){
	const x = Object()
	x.foo = ""
}
```
![Code_2020-05-05_22-26-01](https://user-images.githubusercontent.com/30108880/81112750-6c2f0380-8f1f-11ea-8857-5fdf9ccbf958.png)
![Code_2020-05-05_22-22-31](https://user-images.githubusercontent.com/30108880/81112633-3d189200-8f1f-11ea-80d7-ff9ae7c86e76.png)

**Comment by Kingwl** [comment]
I don't know why but seems x has been resolved as a class in treeNav command

**Comment by tabaddor** [comment]
I'd like to take on this issue. Is there any other information I should know?

**Comment by Kingwl** [comment]
Sorry....But I think I have already resolved the issue.

**Comment by Kingwl** [comment]
And it's has merged. ping @mjbvz .

**Comment by mjbvz** [comment]
Thanks @Kingwl!

To verify, make sure you are the current TS 4.0 highly build in your workspace
