### ISSUE TITLE
Diff editor scroll bar too thick

### ISSUE THREAD

**Issue by sungle3737** [microsoft/vscode#97046]
- VSCode Version: 1.44.2
- OS Version: windows 10 pro 1909

Steps to Reproduce:

1. change file
2. click git changes

![image](https://user-images.githubusercontent.com/27716524/81134608-40983180-8f90-11ea-9321-a7abe481431a.png)

### Scroll bar looks weird isn't it?

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@sungle3737 The diff editor scrollbar includes something called a diff overview ruler. Normally, this shows additions and deletions across the two files, e.g.:

![image](https://user-images.githubusercontent.com/5047891/81564760-8a21bb80-9398-11ea-8797-52d71584b3e9.png)

From your screenshot, it appears that it is colored in one single block color. Also, from your screenshot, it appears to me that you are using a custom theme or you are perhaps using color customizations in your `settings.json`.

Can you please switch back to the default theme / remove any color customizations from your `settings.json`?

**Comment by sungle3737** [comment]
![image](https://user-images.githubusercontent.com/27716524/81570155-2bc9fc80-93db-11ea-920c-88688efdd2e1.png)
```
 "scrollbarSlider.activeBackground": "#98c2bead",
```
yes i added transparency it works! thank you!
