### ISSUE TITLE
Can't copy text in integrated terminal input field

### ISSUE THREAD

**Issue by gerane** [Microsoft/vscode#9704]
when you try to copy text in the input field for the integrated terminal it does not register the terminal as being selected. Instead it launches an external terminal. If I highlight text inside of the terminal ctrl+shift+c works as expected.

```json
{ "key": "ctrl+shift+c",          "command": "workbench.action.terminal.copySelection",
                                     "when": "terminalFocus" },
{ "key": "ctrl+shift+c",          "command": "workbench.action.terminal.openNativeConsole",
                                     "when": "!terminalFocus" }
```

It is registering as if the terminal is not selected.

- VSCode Version: 1.4.0-insiders 7/25
- OS Version: Windows 10

Steps to Reproduce:

1. Select text in the integrated terminal input field 
2. ctrl + c erases text and gives you ^C
3. ctrl + shift + c opens an external terminal

**Comment by gerane** [comment]
I am also noticing that it will not respect my keybinding in my keybinding.json. To try to work around this I tried to set the following

```json
{ "key": "ctrl+shift+alt+c",          "command": "workbench.action.terminal.openNativeConsole",
                                             "when": "!terminalFocus" }
```

However, ctrl+shift+c is still taking precedence.

**Comment by Tyriar** [comment]
@gerane looks like one of the recent changes made this regress. Thanks for finding it :smiley:

**Comment by gerane** [comment]
@Tyriar Seems to be happening with paste and preview as well

**Comment by gerane** [comment]
@Tyriar is there a way to make a "when:" for terminal text selection? I know there is terminal focus, but if you could specify terminal text selected, you could probably use ctrl+c and not impact the breaking out if you can also control when that can occur. Several editors and terminals i use have this sort of behavior. 

Eventually, I would think you would want intelligent handling of ctrl+c and ctrl+v in the terminal. If text is selected it copies, if a command is running or no text is selected it terminates, and so on.

**Comment by gerane** [comment]
@Tyriar I think the paste one might be a little more problematic

**Comment by gerane** [comment]
@Tyriar hmm, it would appear that your last merge in xterm.js addresses this =)

sourcelair/xterm.js#118

**Comment by Tyriar** [comment]
Should be fixed with the 2 linked commits, there is one remaining issue in that double clicking the prompt line to highlight doesn't work all the time. This should be fixed when virtual selection is added to the terminal and we no longer need to rely on native selection https://github.com/sourcelair/xterm.js/issues/207
