### ISSUE TITLE
Snap: "Open Containing Folder" does nothing on KDE

### ISSUE THREAD

**Issue by davido-bs** [microsoft/vscode#97045]
- VSCode Version: 1.44.2
- OS Version: Kubuntu 19.10 (also confirmed still an issue on 20.04)

Version details:
```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:50:03.709Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-51-generic snap
```

Steps to Reproduce:

1. Right click on a folder in the sidebar in the workspace and select "Open Containing Folder".
2. Nothing happens. Expected Dolphin to open the selected folder.

This is an issue particular to the snap package. This is not an issue on the deb package, nor is it an issue on stock Ubuntu.

Does this issue occur when all extensions are disabled?: Yes

**Comment by 9at8** [comment]
@davido-bs I am using Manjaro with KDE and it opens up the folder in dolphin for me.

```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-23T19:32:05.786Z
Electron: 7.1.14
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.6.10-3-MANJARO
```

**Comment by 9at8** [comment]
@davido-bs I installed `code-insiders` from snap, and I couldn't reproduce this on Manjaro / KDE. Dolphin opens up for me.

```
Version: 1.46.0-insider
Commit: 288852d8c26d797974bfb8aed06e1bff9b809223
Date: 2020-05-12T05:34:26.476Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.6.10-3-MANJARO snap
```

**Comment by joaomoreno** [comment]
@davido-bs Can you try the latest stable/insider?

**Comment by davido-bs** [comment]
@joaomoreno Just did a fresh install of `code-insiders` on a fresh Kubuntu 20.04 install. Still not working.
