### ISSUE TITLE
vscode: "the folder currently open doesn't have a git folder" (but it does have)

### ISSUE THREAD

**Issue by evowilliamson** [microsoft/vscode#97056]
- VSCode Version: 1.44.2
- OS Version:5.3.0-51-generic #44-Ubuntu

Steps to Reproduce:

1. git clone any project
2. open code
3. click on "Source control" in left bar
4. vs code says: "the folder currently open doesn't have a git folder" and offers to initialize a repository

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Have you tried opening that folder?

`File > Open Folder`

**Comment by evowilliamson** [comment]
Yes.

These are the steps that I perform to reproduce my problem:
* In my project directory run the command "code ."
* Once code has started, click on the "Source Control" icon
* Code responds with the folder currently open doesn't have a git folder" and offers to initialize a repository

I've attached the screenshots.

![inside_code2](https://user-images.githubusercontent.com/14161480/81730173-68eec700-948d-11ea-80db-72958e8ef178.png)
![inside_code1](https://user-images.githubusercontent.com/14161480/81730175-69875d80-948d-11ea-9d66-aaae6f2e5eed.png)
![console_start](https://user-images.githubusercontent.com/14161480/81730176-6a1ff400-948d-11ea-9a98-481b1750296d.png)

**Comment by joaomoreno** [comment]
Are there any error in the Developer Tools? <kbd>F1</kbd>, `Developer Tools`.

Also, how did you install VS Code?

**Comment by evowilliamson** [comment]
- There are no errors in the Developer Tools console.
- I installed it using the following link: https://code.visualstudio.com/docs/?dv=linux64_deb
- I also tried to install through snap, with the same result

**Comment by joaomoreno** [comment]
What happens if you run `git status` in that folder?

**Comment by evowilliamson** [comment]
`ivo@ivo-ThinkPad-P53:~/projects/web3.py$ pwd
/home/ivo/projects/web3.py
ivo@ivo-ThinkPad-P53:~/projects/web3.py$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/carver/2x-test-speed
  remotes/origin/cburgdorf-patch-1
  remotes/origin/cburgdorf-patch-2
  remotes/origin/cburgdorf-patch-3
  remotes/origin/fix_docs_build
  remotes/origin/master
  remotes/origin/piper/concurrent-test-runs
  remotes/origin/piper/misc-bugfixes
  remotes/origin/piper/refactor-manager-module
  remotes/origin/revert-contract-test
  remotes/origin/v3
  remotes/origin/v4
ivo@ivo-ThinkPad-P53:~/projects/web3.py$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
ivo@ivo-ThinkPad-P53:~/projects/web3.py$ 

`

**Comment by evowilliamson** [comment]
> ivo@ivo-ThinkPad-P53:~/projects/web3.py$ pwd
> /home/ivo/projects/web3.py
> ivo@ivo-ThinkPad-P53:~/projects/web3.py$ git branch -a
> * master
>   remotes/origin/HEAD -> origin/master
>   remotes/origin/carver/2x-test-speed
>   remotes/origin/cburgdorf-patch-1
>   remotes/origin/cburgdorf-patch-2
>   remotes/origin/cburgdorf-patch-3
>   remotes/origin/fix_docs_build
>   remotes/origin/master
>   remotes/origin/piper/concurrent-test-runs
>   remotes/origin/piper/misc-bugfixes
>   remotes/origin/piper/refactor-manager-module
>   remotes/origin/revert-contract-test
>   remotes/origin/v3
>   remotes/origin/v4
> ivo@ivo-ThinkPad-P53:~/projects/web3.py$ git status
> On branch master
> Your branch is up to date with 'origin/master'.
> 
> nothing to commit, working tree clean
> ivo@ivo-ThinkPad-P53:~/projects/web3.py$ 
> 
>

**Comment by evowilliamson** [comment]
```
ivo@ivo-ThinkPad-P53:~/projects/web3.py$ pwd
/home/ivo/projects/web3.py
ivo@ivo-ThinkPad-P53:~/projects/web3.py$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/carver/2x-test-speed
  remotes/origin/cburgdorf-patch-1
  remotes/origin/cburgdorf-patch-2
  remotes/origin/cburgdorf-patch-3
  remotes/origin/fix_docs_build
  remotes/origin/master
  remotes/origin/piper/concurrent-test-runs
  remotes/origin/piper/misc-bugfixes
  remotes/origin/piper/refactor-manager-module
  remotes/origin/revert-contract-test
  remotes/origin/v3
  remotes/origin/v4
ivo@ivo-ThinkPad-P53:~/projects/web3.py$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
ivo@ivo-ThinkPad-P53:~/projects/web3.py$ 


```

**Comment by joaomoreno** [comment]
Can you really reproduce this with any project?

What does `Git: Show Git Output` show?

**Comment by evowilliamson** [comment]
Where do I execute that command ? Is that a command i need to execute in some visual code terminal ?

**Comment by evowilliamson** [comment]
Hi @joaomoreno,

I think (my) issue has been solved: On my ubuntu system, I have an alias of the'git' command to a shell script where I conditionally do some settings (username, password, etc..) and at the end call the git command. For some reason, Visual code cannot execute correctly that script and therefore fails to call the git command. 

Thanks for your time!
