### ISSUE TITLE
[themes] Use light theme for --disable-extensions

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#97058]
Is it possible to use `default light+` theme for CLI flag `--disable-extensions` if the current theme type is `light`?

I'm running extension tests by launching vscode instance and would like to avoid unnecessary extension activations, but the theme switching (from `light` to `dark` and back) is blinking too much.

**Comment by Tyriar** [comment]
I think the problem is with the "quick layout" feature or whatever it was called that caches colors from the previously used theme.

**Comment by usernamehw** [comment]
Maybe that's different features. I've notices white flashes while switching workspaces, but this is not it. 
It's applied to all moments when active color theme `"workbench.colorTheme"` is not activated and replaced with default one `"Default Dark+"`.
When the active color is light - defaulting to dark theme is a bit unpleasant.

**Comment by aeschli** [comment]
Found a simple fix, sorry for the swirl.
