### ISSUE TITLE
WSL Debug uses Windows' npm rather than WSL

### ISSUE THREAD

**Issue by Keydex** [microsoft/vscode#97051]
Issue Type: <b>Bug</b>

When trying to launch my debug console through launch.json, WSL debug console attempts to use my window's runtimes (npm) as noted by 
`"/mnt/c/Program Files/nodejs//npm: 3: /mnt/c/Program Files/nodejs//npm: : not found" `
rather than using the sub systems' npm package. Not sure if this is intended. 

My launch.json is and this happens when the workspace is in the mounted c drive, or in the subsystem's filesystem
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch via npm",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "runtimeExecutable": "npm",
            "runtimeArgs": ["run-script", "debug"],
            "port": 9229,
            "smartStep": true,
            "skipFiles": ["<node_internals>/**"]
          }
    ]
}
```
I can get around this by changing the `runtimeExecutable` to the absolute path the npm's bin folder on the subsystem. But just weird that debugging attempts to use the programs on my windows system. Perhaps it's because npm is in my windows path and vscode looks if it exists there first before the subsystem?

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>
|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|Memory (System)|63.95GB (48.55GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.1.0
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.6
terraform-doc-snippets|run|0.4.0
code-settings-sync|Sha|3.4.3

</details>

**Comment by Keydex** [comment]
This might actually be caused by this, due to me using ${} for workspaceFolder.

**Comment by isidorn** [comment]
Since the other issue was assigned to @weinand forwarding this issue to him as he has better background

**Comment by weinand** [comment]
Since we are now using the new js-debug, this issue has become obsolete.
