### ISSUE TITLE
Errors for merge conflicts

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#97054]
Merge feature might conflict with other extensions:

![image](https://user-images.githubusercontent.com/1092613/79763520-7b5d6100-8324-11ea-9a59-74781ed1be24.png)

![image](https://user-images.githubusercontent.com/1092613/79763461-697bbe00-8324-11ea-95dc-bf0b00eac19d.png)

Is it possible to use decorations instead of text that generates errors?

**Comment by joaomoreno** [comment]
This is not the merge feature, these are literally merge characters inserted by Git and the language service fails to detect them, and it's in its right to do so.

We won't do anything here besides implementing an actual merge editor, making these merge markers irrelevant.
