### ISSUE TITLE
Workspace folders divider object

### ISSUE THREAD

**Issue by 5argon** [microsoft/vscode#97050]
We could already name and manually sort each workspace folder so it reflects nicely on the explorer. I would like to request a divider object where you could give it a `name` just like a folder, but there is no content and there is no expand arrow button on its left.

![image](https://user-images.githubusercontent.com/5653276/81139210-26aa1f00-8f8f-11ea-8c94-eb4fcc6f0426.png)

As seen on this image, the "---" is intended to be a divider. But the `folders` configuration doesn't allow an entry with just `name` so I have to use a dummy `path` just to get a divider. 

A divider maybe omitted from this new terminal dialog and only have it affects the explorer. 

![image](https://user-images.githubusercontent.com/5653276/81139324-886a8900-8f8f-11ea-8f6a-3780a955cb40.png)

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
