### ISSUE TITLE
openNativeConsole cannot have Custom Keybinding

### ISSUE THREAD

**Issue by gerane** [Microsoft/vscode#9706]
Because of issue #7904 I was needing to set a different keybinding for openNativeConsole. However, it is not respecting the keybinding being set in keybindings.json. No matter what I try to set ctrl+shift+c remains the keybinding.

This may also be happening with ctrl+shift+v and preview.

- VSCode Version: 1.4.0-insiders 7/25
- OS Version: Windows 10

Steps to Reproduce:

1. Set a new keybinding for openNativeConsole
2. test copying text in the console input.

**Comment by gerane** [comment]
just noticed that ctrl+v actually works for pasting into the terminal.

**Comment by kieferrm** [comment]
Duplicate of #7269.
