### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by martingbrown** [microsoft/vscode#97067]
Proper Visual Studio has had a feature for creating [bookmarks](https://docs.microsoft.com/en-us/visualstudio/ide/setting-bookmarks-in-code?view=vs-2019) in code for years. It would be great if that could be replicated in Visual Studio Code.

# Minimum Feature Set
Ctrl+K, Ctrl+K toggles a bookmark on the line the cursor is on. This is signified by a mark in the gutter.
Ctrl+K, Ctrl+P Moves the cursor to the previous bookmark.
Ctrl+K, Ctrl+N Moves the curstor to the next bookmark.

# Advanced Feature Set
Bookmarks can be seen as a list in a separate pane listing File and Line number. Ctrl+K, Ctrl+W opens the paine and double-clicking an item places the cursor on that bookmark.
Bookmarks can be given names.
Bookmarks can be grouped in a hierachy.
Bookmarks can be disabled to prevent them being moved to when Ctr+K, Ctrl+N is pressed.

**Comment by yume-chan** [comment]
I'm using the [Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks) extension and it's pretty good.
