### ISSUE TITLE
Have CTRL+SHIFT+P always stay on "searching scripts/macros", and not to files when deleting search.

### ISSUE THREAD

**Issue by rw3iss** [microsoft/vscode#97076]
I find I use the CTRL+SHIFT+P shortcut, to search extensions and scripts/macros, but I also use CTRL+P to search files a lot...

The issue is that these two pieces of functionality are very different, and never really used "at the same time", but when you CTRL+SHIFT+P and search a macro, and fail to find one or mess up, and backspace/delete the entire search, it then falls back to only searching files, even though we're still wanting to be on the macro/script search. Then we have to CTRL+SHIFT+P again. If we wanted to search files we would enter the file shortcut.

So this is a little aggravating and seems non-intuitive to push the user back to searching files when they are already trying to search macros.

Would it be possible to change the default behavior to just stay on the macro/script search when hitting CTRL+SHIFT+P?

**Comment by Tyriar** [comment]
That's just how it was designed, to help you understand better, you can hit ctrl+p and type `?` to view all the capabilities of this component.

<img width="604" alt="Screen Shot 2020-05-07 at 12 31 48 PM" src="https://user-images.githubusercontent.com/2193314/81336743-b9fe5580-905e-11ea-8642-5a2aaf1030de.png">

**Comment by rw3iss** [comment]
Cool, I don't know how ? is supposed to help. 
I get I can go back and redo the search, enter different commands (?), but that's not the point, I think it's a pretty lame design.

User wants to search macros... CTRL+SHIFT+P to search them... THAT'S IT... then I fuck up the text and backspace, now I have to fuddle around with other shortcuts and ? and all that bullshit to get back to what I wanted to do. Lame design. 

They are two separate functionalities. Great that ? shows me everything, I should be able to type that regardless! ... but backspacing out of original context should now remove me from that context! Annoying that developers think these kinds of things are helping.

**Comment by Tyriar** [comment]
fyi @bpasero
