### ISSUE TITLE
impossibly laggy typing

### ISSUE THREAD

**Issue by GorroRojo** [microsoft/vscode#97073]
Issue Type: <b>Performance Issue</b>

open an html file, apply html5-boilerplate from extension, switch applications, switch back, and start typing.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 5.4.0-26-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2644)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|8, 9, 10|
|Memory (System)|15.35GB (5.79GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   126	 11694	code main
    0	    31	 11696	   zygote
    0	    47	 11732	   utility
    0	    79	 11733	   gpu-process
    0	   204	 11761	   window (index.html - EjerciciosTeatrales - Visual Studio Code)
    0	   110	 11824	     extensionHost
    0	    94	 11858	       /snap/code/31/usr/share/code/code /snap/code/31/usr/share/code/resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=11824
    0	    63	 11840	     watcherService
    0	    63	 11856	     searchService
    0	   110	 11792	   shared-process
    0	     0	 14920	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 14921	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   110	 14899	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html - EjerciciosTeatrales - Visual Studio Code)
|    Folder (EjerciciosTeatrales): 12 files
|      File types: css(3) html(2) zip(1) png(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
gitlens|eam|10.2.1
html-snippets|gey|0.2.3
vscode-picture|Jak|1.0.0
tag-inserter|l7s|1.4.0
quickstart|lol|0.1.0
vscode-clang|mit|0.2.3
python|ms-|2020.4.76186
cmake-tools|ms-|1.3.1
cpptools|ms-|0.27.1
html5-boilerplate|sid|1.0.3
ejs-snippets|Tao|0.1.0
cmake|twx|0.0.17
HTML5-extension-pack|wal|0.0.3
html-snippets|wge|0.1.5
clang-format|xav|1.9.0
explicit-folding|zok|0.6.0

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by GorroRojo** [comment]
turns out i needed more swap memory, works much better now, sorry
