### ISSUE TITLE
Hide Flutter debug bar from top screen OSX

### ISSUE THREAD

**Issue by kevingb20** [microsoft/vscode#97075]
Hi. I need to hide the bar that contains flutter actions(hot reload, hot restart) or move it to the bottom or to a fixed position because it doesn't let me see my code windows tabs. Is there a way to do it?

<img width="408" alt="Screen Shot 2020-05-06 at 09 25 22" src="https://user-images.githubusercontent.com/19670643/81188898-8bf41500-8f7b-11ea-92f3-37948662b8db.png">

**Comment by yume-chan** [comment]
Disable: `"debug.toolBarLocation": "hidden"`

Display in Debug view: `"debug.toolBarLocation": "docked"`

You can't move it anywhere else. See also #91411
