### ISSUE TITLE
Typescript overload selection should prioritise specificity, where overloads types are a subset of the generic

### ISSUE THREAD

**Issue by neefrehman** [microsoft/vscode#97086]
Opening this issue here as a comment on my issue in the TypeScript repo suggests that it's an editor issue: https://github.com/microsoft/TypeScript/issues/38357#issuecomment-624746295

## Suggestion

I suggest that when the return type of an overloaded function is a subset of the generic type, it should be prioritised in TypeScript's selection when it matches a developer's input.

A current use case where the default overload selection isn't quite what I want is that I have three overloads to cover the most common use cases of a function I've made (that have exactly `1`, `2` and `3` as their parameters), and there's a generic returned type as a fallback (for any `number`).

Ideally, I the generic type should be suggested first so the user knows that any number can be accepted as a parameter, and then the more specific overloads to be suggested if the user enters those parameters. Currently, this doesn't happen as `1`, `2` and `3` still are a subset of `number`, so the generic type is still suggested despite a more specific return type being available.

I could solve this by placing the generic overload last, but then the selected intellisense suggestion would be that `1` is accepted as a parameter, which I think is bad UX for the user, as they can actually use any `number`.

## Example

The following code is an example where I would like the most generic type to be suggested first, but then to be taken over by the more specific ones if the user enters the related parameters.

Currently the only two options are to _only_ suggest/use the most generic type (current structure), or to _always_ suggest the most specific type at first, then get less specific (placing the generic overload last, bad UX).

```js
type GenericType = number[] | GenericType<number>[]

function overloadedFunction(n: number): GenericType;

function overloadedFunction(n: 1): number[];

function overloadedFunction(n: 2): number[][];

function overloadedFunction(n: 3): number[][][];
```

A fully fleshed out example of a function like this, with comments and further explanation, is at [this playground link](https://www.typescriptlang.org/v2/en/play?ssl=6&ssc=14&pln=3&pc=1#code/C4TwDgpgBAsghsATgSwB4B4AqA+KBeKTAbQF0oAfWBFDHUgbgChGAzAVwDsBjYZAew5QuiCAggA5ACLIAthA4BnfhzgAbAIKJEcEFmwAKRlCgcAXCbYyARhEQAaI1GQdkvNQDU1bCAoD85zEYASnN4JDQ9JlZOHmUhETEpWXklATVNbV0cQ2MzKABGB2NnV2QPLx9-QmCAhmZ2bl4BeNFgCWk5RWV0rR09HJNzACYipxc3VU9Vbz8AmsJSOujGuOFW9uSutI1erINHPIBmUZKJqZmqwJCFkkWSKIbY5rXEjpTuncz+g-MOSxt7I5TmVJhUFAF8BZVKooAB6WFQdAAWigwAAFsgFFBbIg+IgoAJVCAoHAwJA4IgsWjbBA7FAWM5oM4oO4AMoAYT4ABNoHAOFzUdT6TEmoIAO54gDWWIZHAg8zCND0UAA3o4uAIFMAhGwtPJgG8thwAOrILnoyEcJjGDWKbUiGRwEocADmhtSiktUBR+WtQk12rlEC5CgAShAuLqPZCHU6XK73cosbgAAxRG0BnV6jjARVoSEZHT6SPZg2bD2m81ooIAOgZ0P0wPK0x8QXT-rt9OcajzqEtEGDYYjUeUjmMvizIhzvZrjrA+n0QXwuBebSSnQ9PUy+gALHSm6CWwogkEx1BzCWp7nqGh2yJgLrBLKezfUEwAL7MeEd3h-aCgMBnBdFpXnLD5C2JGxVD4MVmFXDYN34L8EUkbxUT4QVoDxHl8T4FgCQAN1saC4AFR5RQUOl0WgF15FsZAuFRcAfCgMVkGhKAbCgBQ2BdWitWDLtKWAOkxQxLg0ScLEeSUEQuRrRhv0wakRBJVTnDaaFMRSJkFB4li4BYNp8QAoDMKErUoAAIn0Ky6TRGCICIxBTEUhE3KgAAJGkxnMsBVB0F1cU4AV9AAMigTkZL5LkrD4VAl1cVj2JhHkWDgNhVG1YAMOokwIFQbU+GckiuXMAADPJ8nK0TqUEJKFAczKuQ8rUdGSi08touUUEYgDoCUbhoA4DCwApOA5GMqA0TgLEbHkKAxr0wSYqcbUNWa7jeA4ri+WJP5rFsBTvw8gBJQQ2Si2lzJ4vifFFKAACoJQ4AByYBHqgGRiv-XKhT4ajcJKvhSMo7EiMEAQuGgEA+DYJjIAKOkRgJfFDg82bzIZYTFvGybbDpU6oBdGY5ojDKFH-BzKagAiwS2lKvoQCSoEq-5bBq1jxMkjU5BlZBhOOhF1FUBQMMxuAoBEHisqliAH0QOUBX6qSqHCVA6RG7KhW+1SFEgLhkAZPrmJlXEZHMn7EFKhQhagDzxAgVwVLUqnoDAEQWBpAUbBmgj+F1OlMaJ9FnElNamclFjdYGnT6TxG7eP4ij0K2ilgAx7XoG+yzuvorgqLq4n5a+vEBoNo2GKcfC+QBl2rdKpngAknwaygEX0Thl1JKJiaSTFCkqYQDzMFZZKOLUAeQCxD2IC9kyhWxyyG5BsrpuAYAwHBeEXWdtgrBrXnYRgBjcTFozYUwZjWWEZAwGAWFMX0hRYXyAAOAA2FMAGIn+8XnOjACRAAdiGPkAArDuYBhxgEeTOv6TaYtVBEUwjTKwxJ-JwENq6cyedeqEWIqvKAAUtR0isGwLOgg8qU1UBGNoAoNIQC0pTRQA0k73VHN+CUm0uLogQAUVWWDob3xWliSWY1tD43sFzBiPdBRh1VlYUiUAACqAANeOC9oBsEpviTG1FiRcD5FAHRvIOD7XZogBSZ1XoW1kHAXe8ZgJi0mhiHBMdiHICjpFVkrIyEUK5j5PKj0l4fQIdbIhmJFooDxKUSmXI6ScG2iSUuIhWoV2NgSOUadEDACxDlJuLNXAKSAA).

**Comment by mjbvz** [comment]
The TypeScript service provides the overload suggestions (and orders them) so please continue to follow up on the TypeScript repository
