### ISSUE TITLE
Debug: Toggle Auto Attach should change user settings by default, not workspace settings

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#97087]
cc @connor4312 

I was confused why the auto attach status bar entry kept disappearing and I kept getting prompts to relaunch my terminals. This was happening because the toggle auto attach command saves a workspace setting, which I never want to commit so it always ends up getting cleared. Auto attach is something I want to toggle on briefly and then toggle off again and I would prefer use the command/keybinding rather than the mouse.

Related: https://github.com/microsoft/vscode/issues/53640

**Comment by connor4312** [comment]
Referenced in the PR, auto attach now toggles globally by default, except if there's already a workspace setting present that would override it. In both cases, there's a button on the quickpick that you can use to swap into the other scope.
