### ISSUE TITLE
Max-width autocomplete does max-height instead

### ISSUE THREAD

**Issue by iRoachie** [Microsoft/vscode#9708]
- VSCode Version: 1.3.1
- OS Version: Windows 10 build 10586.494

Steps to Reproduce:

1. In a sass file, type 'maxw' and press enter
2. Snippet expands to max-height instead of max width

![max-width bug](https://cloud.githubusercontent.com/assets/5962998/17107174/3163cd70-525c-11e6-8549-d24ff90a3771.gif)

**Comment by mrmlnc** [comment]
As I understand it, you use Sass with `sass-intended` extension. This error does not refer to the editor. Please create an issue in the plugin repository.

Error this: https://github.com/robinbentley/vscode-sass-indented/blob/master/snippets/sass-indented.json#L507-L514

**Comment by iRoachie** [comment]
Thanks! Can close
