### ISSUE TITLE
ERRO de dll ao atualizar

### ISSUE THREAD

**Issue by scooweb** [microsoft/vscode#97083]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Estou tentando atualizar um programa o VSCode e gera esse erro como faço para corrigir?
api-ms-win-crt-runtime-l1-1-0.dll
2.
![image](https://user-images.githubusercontent.com/7991451/81206438-81994180-8fa2-11ea-895d-0a14af283eaf.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by pedrowindisch** [comment]
Quando isso aconteceu comigo, precisei reinstalar os pacotes redistributíveis do Visual C++. Esse problema, porém, aconteceu comigo no Visual Studio, e não no Visual Code. Não sei se a solução servirá pra você. Qualquer coisa, [segue o link para o site da última versão suportada.](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

Por questões de internacionalização, segue o trecho traduzido pro inglês.

When I faced the problem you just described, I had to reinstall my Visual C++ redistributable packages. However, that happened when I was using Visual Studio, and it didn't beset my VSCode installation. I don't know if the solution I'm giving you will actually be helpful in your case, but [here is the link](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) you can be visiting if you want to download the latest supported packages.

**Comment by deepak1556** [comment]
@scooweb which version of windows are you on ?

Also please try the installation instructions for VC++ packages specified by @pedrowindisch , thanks!

VSCode or rather electron links with UCRT statically, so this issue is rather from the inno_updater package itself.
