### ISSUE TITLE
Different spacing in front of text for search and replace fields

### ISSUE THREAD

**Issue by deathly809** [microsoft/vscode#97094]
There seems to be some extra spacing before the text in the search field that is not present in the replace field.

- VSCode Version: 1.45.0-insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Open Search replace for document

Does this issue occur when all extensions are disabled?: Yes/No
Yes

![image](https://user-images.githubusercontent.com/1381210/81227438-48ac9d00-8fa1-11ea-8e94-a40ca64dfeae.png)

**Comment by roblourens** [comment]
Strange, I can't reproduce this. If you update to the latest insiders 1.46 does it still happen?

**Comment by deathly809** [comment]
Seems to be fixed in latest version.  Closing since issue seems to be gone.
