### ISSUE TITLE
'reversed' not reversed when parsing ordered lists in HTML5.

### ISSUE THREAD

**Issue by mloutris** [microsoft/vscode#97097]
Visual Studio Code Version: 1.44.2 (system setup)
Electron:  7.1.11
Chrome:  78.0.3904.130
Node.js:   12.8.1
V8:           7.8.279.23-electron.0
OS:           Windows_NT x64 10.0.18362
Parsing HTML5 pages with ordered lists, the list numbers are **not** reversed, and appear in ascending order from top to bottom. When I display the file index.html in a Chrome browser, the numbers are reversed, decreasing from the highest value to the lowest. 
Example:
<ol reversed title="Pies">
    <li>Key lime</li>
    <li>Cherry</li>
    <li>Apple</li>
</ol>
NOTE 1: This is also a problem with Microsoft's Bing and Internet Explorer.
NOTE 2: The '.txt' extension on the attached file below needs to be removed.
              It was added because GitHub does not recognize the '.html' file extension. 
[index.html.txt](https://github.com/microsoft/vscode/files/4589477/index.html.txt)

**Comment by Tyriar** [comment]
Is this a problem with VS Code's UI or something It's not clear, a screenshot would help.

**Comment by mloutris** [comment]
I tried copying the source file as well as pasting it, but GitHub messed up both. 
1. The first screen shot is of the extremely basic markup text. 
2. The second shows the text displayed in Chrome with the list items in reverse order, largest value at the top, decreasing toward the bottom.  This is how the feature is explained to work. 
3. The last screen shot shows the same markup displayed using VS Code with Live Server. 
Keep in mind that this is not an important feature, but I was surprised that it didn't work. 
I can only tell you that it is not a problem with the HTML, but I suspect it may have something to do with the code parsing the markup text, or the actual support for reversing ordered lists may not be supported. It also appears to be a Microsoft related issue, as reversed ordered lists are not supported by Bing, IE or Live Server, but is supported by Chrome, Firefox and just about every other browser. 

![html_code_list_order_reversal](https://user-images.githubusercontent.com/25943739/81346368-c8109e00-907f-11ea-8fcb-c1c445b6b413.png)

![list_order_reversal_correctly_displayed_chrome](https://user-images.githubusercontent.com/25943739/81346378-ce067f00-907f-11ea-8a7f-7c518f873c64.png)

![list_order_reversal_incorrectly_displayed_vscode_live_server](https://user-images.githubusercontent.com/25943739/81346389-d363c980-907f-11ea-8693-4b81cb424daa.png)

**Comment by Tyriar** [comment]
Sounds like this is a problem with the live server extension then?

**Comment by mloutris** [comment]
I don't really know the functionality provided by VS Code versus a browser. If VS Code is just using a standard browser, then I would think the issue resides in the browser.
