### ISSUE TITLE
Workspace config - folder specific files association not working

### ISSUE THREAD

**Issue by nsgundy** [microsoft/vscode#97096]
- VSCode Version: 1.44.2
- OS Version: Ubuntu 19.10

Steps to Reproduce:
1. Open a `.code-workspace` that has `files.associations` configured using the `workspaceFolder` variable like so:
```
{
  "folders": [
    {
      "name": "Base",
      "path": "."
    },
    {
      "name": "Other",
      "path": "../other"
    }
  ],
  "settings": {
    "files.associations": {
      "${workspaceFolder:Other}/**/*.c": "cpp"
    }
  }
}
```
2. Open a `.c` file located in the `${workspaceFolder:Other}` location and observe that the language mode is displaying `C`, instead of the expected `C++`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@bpasero Do you support variables in files associations?

**Comment by bpasero** [comment]
I have never seen this syntax `${workspaceFolder:Other}` and thought it was something you came up with. If not, then it explains why this does not work.

**Comment by sandy081** [comment]
Configuration does not support any variables. Hence moving this to you if you are willing to support variables.

**Comment by bpasero** [comment]
@nsgundy how did you encounter this syntax you are using? wondering what made you use it?

**Comment by nsgundy** [comment]
> @nsgundy how did you encounter this syntax you are using? wondering what made you use it?

@bpasero See https://code.visualstudio.com/docs/editor/variables-reference#_variables-scoped-per-workspace-folder

**Comment by bpasero** [comment]
@nsgundy that seems to be debug and task specific, not in general. You can use this in `task.json` and `launch.json`.

**Comment by nsgundy** [comment]
Is variable substitution not supported outside of tasks.json / launch.json? It surely would be useful to have.
