### ISSUE TITLE
Outdated QDK extension automatically installed on VS code and cannot automatically update

### ISSUE THREAD

**Issue by KittyYeungQ** [microsoft/vscode#97093]
Transferring issue submitted here:
https://github.com/microsoft/qsharp-compiler/issues/427

- VSCode Version: macOS 10.13.6
- OS Version: Visual Studio Code 1.25.0

Unable to update the QDK on macOS. Tried uninstalling and reinstalling but not resolved.

**To Reproduce**

1. - Install an earlier version of the QDK.  0.2.118063001 was installed (yes, from June 2018).
2. - Try to install a newer version.
3. - Uninstall/reinstall procedures don't give you a newer version.
4. - Automatic updates don't pull in anything new.

**Expected behavior**

Automatic update should pull the QDK extension. I should also be able to upgrade.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
QDK isn't bundled with VS Code, also you're on an ancient version, maybe that's causing your issue?

**Comment by KittyYeungQ** [comment]
@tpetchel Could it be your VS Code was old?
