### ISSUE TITLE
Cannot validate the php file. The php program was not found.

### ISSUE THREAD

**Issue by schinaider** [Microsoft/vscode#971]
I'm geting the message when i open Visual Studio Code:

" Cannot validate the php file. The php program was not found. Use the 'php.validate.executablePath' setting to configure the location of 'php' "

**Comment by felixfbecker** [comment]
Dude it is what the message says - you have to install php and then either put the path of the php binary in the setting or inside your %PATH%.

**Comment by schinaider** [comment]
But i use Wamp. I solved The problem, but why this message? Why i have to install php? If i don't want, The message will be showing to me... I think it isn't good.

Enviado pelo meu Windows Phone
________________________________
De: Felix Becker<mailto:notifications@github.com>
Enviada em: ‎03/‎12/‎2015 15:17
Para: Microsoft/vscode<mailto:vscode@noreply.github.com>
Cc: schinaider<mailto:victoralmeidaschinaider@hotmail.com>
Assunto: Re: [vscode] Cannot validate the php file. The php program was not found. (#971)

Dude it is what the message says - you have to install php and then either put the path of the php binary in the setting or inside your %PATH%.

---

**Comment by felixfbecker** [comment]
You don't need to, but it cannot validate (lint) the file without it. Just like the message says. I'm not familiar with Wamp, search for your php.exe.

**Comment by schinaider** [comment]
Sorry for anything 😃. I just want to say i think is not user friendly to show The message all time i open the Visual Code. I think it will be good, if i could easily desativate the warning... Understand?

Enviado pelo meu Windows Phone
________________________________
De: Felix Becker<mailto:notifications@github.com>
Enviada em: ‎03/‎12/‎2015 15:29
Para: Microsoft/vscode<mailto:vscode@noreply.github.com>
Cc: schinaider<mailto:victoralmeidaschinaider@hotmail.com>
Assunto: Re: [vscode] Cannot validate the php file. The php program was not found. (#971)

You don't need to, but it cannot validate (lint) the file without it. Just like the message says. I'm not familiar with Wamp, search for your php.exe.

---

**Comment by felixfbecker** [comment]
Imo if you do PHP development you probably have PHP installed, right?!

**Comment by dbaeumer** [comment]
@schinaider I see your point. I added a setting php.validate.enable. If set to false VSCode will not validate php files at all and therefore will not show a message if it can't find the php executable. To not break things the setting is true by default.

**Comment by davonta** [comment]
New to php development and am using wamp, I'm getting the same message. Not sure how to validate the php file or use the setting exactly. Can someone give me the step by step version so my wordpress themes can update?

**Comment by dbaeumer** [comment]
You need to set the settings `"php.validate.executablePath"` to a path of the php executable. For example on Windows to: `"C:\\apps\\php\\php.exe"`

**Comment by davonta** [comment]
using the command prompt?

**Comment by dbaeumer** [comment]
It is a VS Code setting. File > Preferences > Workspace Settings.

**Comment by davonta** [comment]
Works. You're awesome, thank you!

**Comment by djuka038** [comment]
How to set on ubuntu?

**Comment by victorschinaider** [comment]
Basically, the same way in windows. Just search the executable path of php, and set in "executablePath". Some paths you can find "/usr/bin/php" or "/bin/php". If you use xampp, just search in  xampp bin folder.

**Comment by djuka038** [comment]
Thanks

**Comment by IntoTheQCD** [comment]
I gave up after an hour of trying to pathed this thing correctly to my php.exe that came with xampp.
