### ISSUE TITLE
Terminal background with unwarranted highlighting

### ISSUE THREAD

**Issue by smith-xyz** [microsoft/vscode#97105]
- VSCode Version: 1.44.2
- OS Version: WIN 10

Steps to Reproduce:

Not sure on its reproducibility, seems environmental but I can't seem to find settings to dictate the background. 
1. Recently opened VS code, opened the terminal
2. typed npm test 'file' and the lines were now highlighting blue.

No new extensions/themes/local settings to powershell or cmd have been added between the time when the background was just black and when I opened vs code to see this behavior.

![image](https://user-images.githubusercontent.com/51304449/81233872-a521b380-8fc5-11ea-8093-d8162582875d.png)

Insiders build:
![image](https://user-images.githubusercontent.com/51304449/81236210-adc8b880-8fca-11ea-82b6-95a6b6f51bae.png)

Settings.json
{
    "workbench.sideBar.location": "left",
    "editor.minimap.enabled": false,
    "window.zoomLevel": 0,
    "git.confirmSync": false,
    "git.enableSmartCommit": true,
    "java.home": "C:\\Program Files\\Java\\jdk-14",
    "java.help.firstView": "gettingStarted",
    "java.configuration.checkProjectSettingsExclusions": false,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "azureFunctions.showProjectWarning": false,
    "java.semanticHighlighting.enabled": false,
    "terminal.integrated.rendererType": "dom",
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
}

Does this issue occur when all extensions are disabled?: Yes, disabled extensions and flipped through various themes to see if that would do the trick.

I have found similar tickets but pointing back to the old backend "winpty". Other than that, I've yet to find a solution - though I do understand this may be specific to my environment.

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
