### ISSUE TITLE
Search is only searching open files [2020]

### ISSUE THREAD

**Issue by thiagomota456** [microsoft/vscode#97107]
Whe i search with `ctrl + shift + f` the vs code only find between open files

`$ code -v`
`1.44.2`
`ff915844119ce9485abfe8aa9076ec76b5300ddd
x64`

`$ lsb_release -a`
`No LSB modules are available.`
`Distributor ID: Ubuntu`
`Description:    Ubuntu 20.04 LTS`
`Release:        20.04`
`Codename:       focal`

**Comment by thiagomota456** [comment]
It isn't my problem : https://stackoverflow.com/questions/60730541/vscode-only-search-open-files-in-a-workspace-2020

**Comment by roblourens** [comment]
Can you check whether any of the tips in here are relevant? https://github.com/microsoft/vscode/wiki/Search-Issues#missing-search-results

You could also try updating to the just released 1.45

**Comment by thiagomota456** [comment]
> Can you check whether any of the tips in here are relevant? https://github.com/microsoft/vscode/wiki/Search-Issues#missing-search-results
> 
> You could also try updating to the just released 1.45

Thanks. My problem is in the .gitignore
