### ISSUE TITLE
Emmet not enabled/working on Visual Studio Code

### ISSUE THREAD

**Issue by Dragonfly-coding** [microsoft/vscode#97112]
Hello, I am new to coding and I just downloaded VSC. I believe Emmet should be equipped and enabled already with a visual studio code download, but I am watching video on how to use VSC and none of the Emmet shortcuts the coders on the videos are using are working for me. 

Whenever I try to type "!" or "html" or "<div" nothing appears on my screen as an option for autocomplete. (Note: exclude the quotations for the above, I am typing what is between them)

Here are my settings.json

{
    "editor.tabCompletion": "on",
    "emmet.showSuggestionsAsSnippets": true,
    "editor.quickSuggestions": true,
    "emmet.triggerExpansionOnTab": true,
    "files.associations": {"*html" : "html"}
}

Thank you!

**Comment by gjsjohnmurray** [comment]
What language mode did you set for your file?

![image](https://user-images.githubusercontent.com/6726799/81294257-87585b00-9066-11ea-831e-1663a26552e1.png)

**Comment by Dragonfly-coding** [comment]
Hi John!

I'm not quite sure how to do that or that you needed to set this, but I'm
looking to use VSC for html and CSS currently and JavaScript in a few weeks.

Very beginner over here and I so appreciate your help!

Amanda

**Comment by gjsjohnmurray** [comment]
@Dragonfly-coding in the open file in VS Code where you're typing HTML and disappointed not to see the HTML-related suggestions appear, what does the indicated portion of your status line report? If it's not saying "HTML", click on it and choose HTML from the list of options.

If the above advice doesn't help, maybe paste screenshots into your reply comment here on GH. Usually a screenshot copied to your clipboard pastes OK directly into the "Write" tab in GH. Switch to the "Preview" tab to see how it looks.

**Comment by Dragonfly-coding** [comment]
Hello! You're brilliant.  It was set to Plain text. I've changed it to HTML
and I'm on my way.  Thank you thank you!

**Comment by gjsjohnmurray** [comment]
@Dragonfly-coding I'm glad to have helped. Please close the issue.
