### ISSUE TITLE
The terminal shell path does not exist

### ISSUE THREAD

**Issue by juxeii** [microsoft/vscode#97119]
- VSCode Version: 1.44.2
- OS Version: RELH7

Steps to Reproduce:

1. Install https://marketplace.visualstudio.com/items?itemName=matepek.vscode-catch2-test-adapter
2. Install https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer
3. Add
```
{
	"label": "Activate Test Explorer",
	"command": "${command:test-explorer.reload}", // For running use "${command:test-explorer.run-all}"
	"problemMatcher": [],
	"runOptions": {
		"runOn": "folderOpen" // This will cause the trigger. Have to run manually once!
	}
}
```
to `tasks.json`.
4. Run this taks manually once.
5. Reload vscode

A warning shows up on the terminal output(the actual command is executed):

```
> Executing task: ${command:test-explorer.reload}  <

The terminal shell path "${command:test-explorer.reload}" does not exist

Terminal will be reused by tasks, press any key to close it.
```
The extension author catch2-test-adapter suggested to report this issue, see: https://github.com/matepek/vscode-catch2-test-adapter/issues/189#issuecomment-624629616

**Comment by alexr00** [comment]
This is happening because the default task type is `process`. The command `${command:test-explorer.reload}` isn't returning a path to shell, so the variable isn't replaced. Which means that when the task runs it's trying to execute `${command:test-explorer.reload}` as a path. This of course fails.

A simple way to make this a little better 
```
{
	"label": "Activate Test Explorer",
	"type": "shell"
	"command": "echo ${command:test-explorer.reload}", // For running use "${command:test-explorer.run-all}"
	"problemMatcher": [],
	"runOptions": {
		"runOn": "folderOpen" // This will cause the trigger. Have to run manually once!
	}
}
