### ISSUE TITLE
Debugger: error text from configurationDone is not shown to the user

### ISSUE THREAD

**Issue by gregg-miskelly** [microsoft/vscode#97110]
**Issue Type:** Bug

## Issue
If a debug adapter fails configurationDone, then debugging stops. But VS Code will no longer show the user the error message that the debug adapter sent. 

This issue was previously reported and fixed (see https://github.com/microsoft/vscode/issues/87745) but it has regressed in the most recent version of VS Code (insiders and standard).

Insiders version that I checked:
Version: 1.45.0-insider (system setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-06T09:26:27.927Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by gregg-miskelly** [comment]
CC @isidorn

**Comment by isidorn** [comment]
@gregg-miskelly I have no clue how I removed the `.error` call in the past couple of releases, but reintroduced it now so we should be good.
Try it out with VS Code insiders from Monday and let me know how it goes. Thanks!

**Comment by gregg-miskelly** [comment]
@isidorn Thanks for the quick fix. Works great.

**Comment by isidorn** [comment]
Thanks for letting us know, adding verified label.
