### ISSUE TITLE
Tab page multi-selection

### ISSUE THREAD

**Issue by ishen7** [microsoft/vscode#97114]
Issue Type: <b>Feature Request</b>

Currently VS Code does not support tab page multi-selection, hoping to increase the tab page multi-selection function, just like the Chrome browser.

VS Code version: Code - Insiders 1.45.0-insider (d4b8ec9da3bf1061a948fbb1b0d9d3db750cc79f, 2020-05-05T07:13:27.726Z)
OS version: Darwin x64 19.4.0

**Comment by IllusionMH** [comment]
Just in case - in meantime you can select several tabs in Open Editors section.
