### ISSUE TITLE
[error] [File Watcher (chokidar)] terminated unexpectedly and is restarted again...

### ISSUE THREAD

**Issue by surban** [microsoft/vscode#97122]
Issue Type: <b>Bug</b>

Using VS Code with the WSL extension to connect to a Ubuntu 20.04 distribution.

Log (Remote Server) displays the following message approximately every 2-3 minutes.
`[error] [File Watcher (chokidar)] terminated unexpectedly and is restarted again...`

Additionally the `.../out/bootstrap-fork --type=watchService` process in WSL is running constantly at 100% CPU load.  

The setting `files.watcherExclude` has been used to exclude all `.git` folders and other large folders of the project. However this did not help.

Retrying with VS Code Insiders with no extensions (besides WSL) did not help either.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.19619
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2186M  CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (17.03GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu/home/surban/dev/enqt/tfds|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Xeon(R) E-2186M  CPU @ 2.90GHz (12 x 2904)|
|Memory (System)|24.87GB (19.81GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
rust-analyzer|mat|0.2.159
rainbow-csv|mec|1.7.0
crates|ser|0.4.9
pdf|tom|0.6.0
vscode-lldb|vad|1.5.0
markdown-pdf|yza|1.4.4
vscode-ron|a5h|0.6.0
QML|bbe|1.0.0
bracket-pair-colorizer-2|Coe|0.0.29
systemd-unit-file|coo|1.0.6
arm|dan|1.3.1
vscode-docker|ms-|1.1.0
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
vsonline|ms-|1.0.2131
devicetree|plo|0.1.1

</details>

**Comment by hechenglo03** [comment]
me too

**Comment by studgeek** [comment]
https://github.com/microsoft/vscode/issues/105364 seems to be another example of this. In that other bug I included some more info that seems to imply its not an inotify issue.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
//cc @aeschli this seems WSL specific and is maybe addressed

**Comment by aeschli** [comment]
@surban Can you check what the setting `remote.WSL.fileWatcher.polling` is configured to?
If it's true, can you disable is and see if that makes a difference?
