### ISSUE TITLE
Add Folder View In Source Control Page

### ISSUE THREAD

**Issue by AndySampsonBusinesswiseSolutions** [microsoft/vscode#97124]
Within the Source Control page, allow changes to be grouped by folder.
This will allow for easier searching/committing of changes when working in large projects and changes to a large number of files have been made

In the attached screenshot, I have changes in 160 files but, although they are ordered by folder, I might not want to commit a set of changes in a specific folder and this takes a lot of time to work out exactly where I need to highlight to ensure the correct set of changes are staged

![image](https://user-images.githubusercontent.com/57349948/81268422-d343d980-903f-11ea-953e-552a41bdb840.png)

**Comment by usernamehw** [comment]
```js
"scm.defaultViewMode": "tree",
```

![81268422-d343d980-903f-11ea-953e-552a41bdb840](https://user-images.githubusercontent.com/9638156/81278313-2d539780-905e-11ea-8014-2f3770d34e1d.png)

**Comment by AndySampsonBusinesswiseSolutions** [comment]
omg, you are awesome!! :D

many thanks for pointing this out.

I will close this issue.
