### ISSUE TITLE
Add return type hint to function hover

### ISSUE THREAD

**Issue by tweakimp** [microsoft/vscode#97129]
Right now, the hover over function calls does only show type hints for its arguments and the docstring, but not its return type hint.
![image](https://user-images.githubusercontent.com/20489521/81274802-18243c00-9051-11ea-8b88-f91d925a19bf.png)
It would be very helpful if the returning type would also be shown in the hover if there is a return type hint.

**Comment by IllusionMH** [comment]
You need to request this feature from extension that provides support for this language.

For example TS Language Server returns function signature that has return type.
![image](https://user-images.githubusercontent.com/1312662/81284921-6e9c7500-9067-11ea-8fb7-b1b25791108a.png)

**Comment by tweakimp** [comment]
I created an issue in the vscode-python extension, thank you.
