### ISSUE TITLE
Source file map elements with array values in launch.json

### ISSUE THREAD

**Issue by axtschmied** [microsoft/vscode#97136]
In the debug configuration file (`launch.json`) a source file map can be given to map debug source folders to the original folder of source files. This is very useful, but currently folders can only be mapped one-to-one, meaning that for every debug source folder only one folder can be given.

However in case of out-of-source build, often the content of multiple folders gets copied into a common source folder, therefore the files can not be mapped to the original source files, except for the content of one folder.

It would be very useful in my opinion to be able to map multiple folders (as an array) to one debug source folder. Here is an example for that:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "program.exe",
            "cwd": "${workspaceFolder}",
            "sourceFileMap": {
                "C:\\build\\copied_source_files": ["C:\\folder_1\\src", "C:\\folder_2\\src"],
            },
            "MIMode": "gdb",
            "miDebuggerPath": "gdb.exe"
        }
    ]
}
```

I know, that there can be some issues, if the file names are not unique, but in case of e.g. out-of-source build the file names have to be unique anyway.

Maybe there is some way to do something similar, but I haven't found a solution so far, and since I'm using my company's tool chain, I can not change the build process either.

**Comment by IllusionMH** [comment]
/extension c++

Debugger for C++ and its config/behavior are provided by extension

**Comment by IllusionMH** [comment]
/extC++

Debugger for C++ and its config/behavior are provided by extension and this feature request should be filed there if doesn't exist.
