### ISSUE TITLE
Typescript absolute import not working on new/renamed files until refreshing project or restart

### ISSUE THREAD

**Issue by fabioimpe** [microsoft/vscode#97135]
- VSCode Version: 1.44.2
- OS Version: Windows 10

Having this project structure:

```
src
|__ folderA
    |__ file1
    |__ file2
|__ folderB
...
```

Steps to Reproduce:

1. Set "compilerOptions.baseUrl" property in tsconfig.json to your "src" folder
2. Set vscode "typescript.preferences.importModuleSpecifier" setting to "non-relative" (or auto)
3. Create a new file (or rename an existing one) under the src folder (or any subfolder)
4. On that file try to import something typing its location based on the src folder (ex. folderA/file1)
5. Autosuggestion doesn't suggest it and filling by hand results in the error "Cannot find module 'folderA/file1/'. ts(2307)"

Workaround:

F1 -> Typescript: Reload project
or
F1 -> Developer: Reload window
or
Restart vscode

I tried also with setting this in tsconfig:
```
"baseUrl": ".",
"paths": {
  "*": ["src/*"]
}
```

Does this issue occur when all extensions are disabled?: Yes

Am I missing something? Could you please help me?

Thank you

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by fabioimpe** [comment]
Hi @mjbvz unfortunately it doesn't work even in the insider build

**Comment by fabioimpe** [comment]
Hi @mjbvz, sorry to bother you, can I ask if this can be marked as a bug? Thank you

**Comment by fabioimpe** [comment]
It happens also on macOS

**Comment by mjbvz** [comment]
Can you share a small example project (a link to a GitHub repo is fine)

**Comment by fabioimpe** [comment]
Hi @mjbvz, I’m in holiday at the moment and I have no access to my machine, but I don’t think a whole example project is needed, you just have to execute an `npm init` then install typescript and follow my repro steps. Thanks for the effort

**Comment by mjbvz** [comment]
Yes please share an example project. That way we are on the same page
