### ISSUE TITLE
extension are not working when using the --force-user-env option

### ISSUE THREAD

**Issue by davguez** [microsoft/vscode#97133]
On ubuntu 20.04, using the snap version of vscode, when starting from terminal with just "code", everything is fine, but when using the generated icon, the extension tab is refreshing infinitely.

actually the command line registered for the icon is

`env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/code_code.desktop /snap/bin/code --force-user-env --no-sandbox --unity-launch %F`

and it turns out that removing only the --force-user-env option the problem is removed...

**Comment by joaomoreno** [comment]
Do you have any errors in the Developer Tools?

**Comment by davguez** [comment]
@joaomoreno  I tried it but don't see anything clear to me on the console... but I'm attaching it anyway...
[code_devlog.log](https://github.com/microsoft/vscode/files/4623829/code_devlog.log)

**Comment by joaomoreno** [comment]
Could you show me a screenshot of the dev tools instead? Thanks!

**Comment by davguez** [comment]
@joaomoreno  sure, here it is
![image](https://user-images.githubusercontent.com/11659881/81990228-69cb5880-9647-11ea-8b49-36c8dd21eb67.png)

**Comment by joaomoreno** [comment]
Let's try a cleaner setup, show me the devtools but run with `--disable-extensions --force-user-env`

**Comment by davguez** [comment]
this time no error in log:
![image](https://user-images.githubusercontent.com/11659881/82201053-74684500-9908-11ea-961b-89535ba7d638.png)
still I can't see any of the available  extensions but I don't know if the --disable-extensions is also disabling the extension search or not

**Comment by joaomoreno** [comment]
Can you show me your `.bash_profile` or `.bash_rc`?

**Comment by davguez** [comment]
sure... here they are
[bash_ini.zip](https://github.com/microsoft/vscode/files/4659360/bash_ini.zip)

**Comment by joaomoreno** [comment]
Can you comment out the conda setup from `bashrc`?

Or maybe the `ds4drv` line from `bash_profile`?

Does any of these changes fix it?

**Comment by davguez** [comment]
indeed commenting out the conda part is fixing the issue.... I don't know what is wrong with the conda setup and if the fix should be done on conda or on vscode, but indeed you're right.

Thx
