### ISSUE TITLE
Wrong value should be replaced with default value when getting configuration

### ISSUE THREAD

**Issue by asurance** [microsoft/vscode#97130]
I noticed that wrong value can be prompted as error by configuring `pattern`,`minimum` or something like this. However, I still get the wrong value  by `workspace.getConfiguration` and setting the wrong value will trigger `workspace.onDidChangeConfiguration`.Since the extension developer has restricted the value in the configuration, these wrong values should not be got by the extension developer, right?

**Comment by sandy081** [comment]
Its not possible as VS Code configuration does not know about such semantics.
