### ISSUE TITLE
ctrl+h now wipes out RE from find field

### ISSUE THREAD

**Issue by tbfleming** [Microsoft/vscode#9713]
- VSCode Version: insiders
- OS Version: Windows 10

Steps to Reproduce:
1. Press ctrl+f
2. Enter an RE to find
3. Press ctrl+h
4. RE is now gone

![animation](https://cloud.githubusercontent.com/assets/418464/17112147/c9cb57fc-5272-11e6-81f1-72a34f39d1e6.gif)

**Comment by rebornix** [comment]
let's track this issue in the latest one https://github.com/Microsoft/vscode/issues/20768 .
