### ISSUE TITLE
Can't configure recent tasks

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#97134]
1. Run a task
2. Open the run task picker again
3. See the task in the recent section
4. Use configure task gear

**Comment by lszomoru** [comment]
Here are my repro steps:
1. Open the `vscode` repository
2. Run the `npm eslint` task
3. Choose `Tasks: Run Task` from the palette
4. Click `Configure Task` for the `npm eslint` task

This will open the `tasks.json` file but if you look in the SCM viewlet you will notice that this resulted in a change to the `tasks.json` file. A new `npm eslint` task has been added and the only difference is that the newly added one has the `label` property set.

**Comment by alexr00** [comment]
This is specific to extension contributed tasks that are already in tasks.json and don't have a label.

**Comment by alexr00** [comment]
To verify:
1. Follow the steps here: https://github.com/microsoft/vscode/issues/97134#issuecomment-638876828
2. Then, run follow those steps again, but with the `npm 7z` task instead of the `npm eslint` task.
Verify that for both you see tasks.json opened and the chosen task selected.

**Comment by connor4312** [comment]
This will be available for verification in https://dev.azure.com/monacotools/Monaco/_build/results?buildId=77510&view=results
