### ISSUE TITLE
[HTML] CSS IntelliSense within HTML files

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#97149]
I'd like to request CSS IntelliSense within HTML files.

For easy reference:
| DESTINATION | SOURCE | SUPPORTED | COMMENTS |
|---|---|---|---|
| ID attributes | Style tag | NO | |
| ID attributes | External CSS files | NO | |
| Class attributes | Other class attributes | NO | Not sure if useful |
| Class attributes | Style tag | NO | [Check this extension](https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion) |
| Class attributes | External CSS files | NO | [Check this extension](https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion) |
| Style tag | ID attributes | NO | |
| Style tag | Class attributes | NO | |
| Style tag | IDs from style tag | NO | |
| Style tag | Classes from style tag | YES | |
| Style tag | External CSS files | NO | [Check this extension](https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion) |

The suggested extension in the comments column, caches CSS classes in your repository coming from any CSS or HTML file in your repository. Even though this is better than nothing, it does pollute your suggestion box with CSS classes your HTML doesn't link to and doesn't show IDs.

**Comment by andrecasal** [comment]
Neither of those issues are duplicates.

**Comment by aeschli** [comment]
Thanks for the nice table. #47331 is the issue we use for this.
It's all intervened:  Make CSS/HTML work across files and among each other.

**Comment by andrecasal** [comment]
Hey @aeschli thanks for the heads up. I'll copy the table to that issue for convenience.
