### ISSUE TITLE
Git operations are too slow in Python

### ISSUE THREAD

**Issue by SimiCode** [microsoft/vscode#97147]
Issue Type: <b>Bug</b>

Git ops are too slow when using Python. To my surprise, yesterday I was editing a JavaScript Project and Git was working at normal speed.

I have tested this with all extesnions disabled and it still happens.
What Could be wrong with Git in Python? 

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.55GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/EdisonAbahurire/Desktop/projects/celvisual-visualization|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by SimiCode** [comment]
I recorded a Video but Github Wont let me attach it here

**Comment by joaomoreno** [comment]
What extensions do you have installed?

---

Can you reproduce the issue again, but first:

- Open `Developer: Show Running Extensions`
- Click the `Start Extension Host Profile` button at the top right, it's the circle
- Reproduce the issue
- Stop profile

You can show me a screenshot of the profile result. You can also send me the profiling results.

---

You can upload the video to youtube and send us the link.

**Comment by SimiCode** [comment]
Video on Youtube: Watch the waiting animation in the top of the git sidebar. https://youtu.be/35ndo1hXX8c

**Comment by SimiCode** [comment]
Remember, this still happens with all extensions disabled

**Comment by SimiCode** [comment]
Profile file is here: Was too huge to paste
https://raw.githubusercontent.com/SimiCode/SCROLL/master/CPU-20200513T112847.200Z.cpuprofile.txt

**Comment by joaomoreno** [comment]
Could you show me a video, but with all extensions disabled?

**Comment by SimiCode** [comment]
Hello, I updated VSCode and Pycharm yesterday. The issue seems not to be happening. Even with extensions enables. Lets close for now.
