### ISSUE TITLE
JS: bind() removes function annotations

### ISSUE THREAD

**Issue by sKopheK** [microsoft/vscode#97143]
- VSCode Version: 1.44.2 (ff915)
- OS Version: Win_NT x64 10.0.18362

Steps to Reproduce:

```
function tripple(n) {
    return n * 3;
}
const bound = tripple.bind(this);
```
[Playground Link](https://www.typescriptlang.org/v2/en/play?useJavaScript=true#code/GYVwdgxgLglg9mABFATjADugNgUwBRgCUiA3gFCKWIo5QgpJIBUiAzANxkC+ZZECAZyiIARnHAATRAF5kaTLgB0ImGAl4oACxgDCnMmMl5CQA)

In the above mentioned playground everything works as it should, but in VS Code there's no intellisense hint upon clicking into `bound()` statement:

![image](https://user-images.githubusercontent.com/5802917/81285942-e70e3080-907d-11ea-97e6-d994d9658750.png)

Tested with all extensions disabled.

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
By default TS (powers JS functionality) doesn't enable `strictBindCallApply` [compiler option](https://www.typescriptlang.org/docs/handbook/compiler-options.html).

You need to create `jsconfig.json` with at least
```json
{
    "compilerOptions": {
        "strictBindCallApply": true
    }
}
```

See https://code.visualstudio.com/Docs/languages/javascript#_javascript-projects-jsconfigjson for details.
