### ISSUE TITLE
fb196011ee5c00724e0ac8cc999864a6042f44cf causes tasks to hang VS Code

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#97145]
Bisect shows that the hang starts with fb196011ee5c00724e0ac8cc999864a6042f44cf

Repro:
Execute the Run Task command.

**Comment by jrieken** [comment]
@dbaeumer wrote that code and I only un-commented it ;-)

**Comment by dbaeumer** [comment]
This got fixed in the meantime.
