### ISSUE TITLE
更改windows用户名后无法更新vscode

### ISSUE THREAD

**Issue by kengdiea** [microsoft/vscode#97140]
Issue Type: <b>Bug</b>

即使我卸载都无法安装，下载新的安装包也无法安装，因为官网的安装包无法指定安装目录，也没查到vscode安装配置文件在哪，就不能更改安装位置，就会一直报错，目前只能重装系统或改回原用户名才能解决，但是我不想这么做，不然我也不会更改用户名，重装系统也不考虑

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (2.81GB free)|
|Process Argv|C:\Users\Dante\Desktop\mpvueTest|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by yume-chan** [comment]
Translation:

> # Can't update vscode after changing my user name
>
> Can't install even after I uninstalled, also can't install with a newly downloaded installer, because I can't specify installation location from the official installer, and can't find where vscode's installation configuration is, so can't change installation location, so it keeps showing errors, currently only reinstalling OS or changing user name back can fix it, but I don't want to do that, or I won't change my user name, reinstalling OS is also not considered.
