### ISSUE TITLE
"Find References" no longer shows the view

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#97144]
This is probably a layout regression (cc @sandy081 @sbatten). Steps:
* find references
* right click hide the find references view
* do again

=> 🐛 the view does not open for may nor shows

**Comment by sandy081** [comment]
Is it running out of sources?

**Comment by sandy081** [comment]
Looks like only on OSS and caused due to my refactorings.

**Comment by sandy081** [comment]
To verify:

Make sure Find References opens References Viewlet + View with results.

**Comment by bpasero** [comment]
No, I am seeing this in my exploration build too.

**Comment by sandy081** [comment]
Is your exploration build in sync with insiders?

**Comment by bpasero** [comment]
Well it is ahead. So makes sense that you can only reproduce in OSS.
