### ISSUE TITLE
Add file to gitignore

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#9714]
This is a feature request for Git. 

Frequently (on a mac) I get this pesky .DS_Store file showing up. I see it then add it to my .gitignore. What would be great is a menu item to add a file to gitignore. An [extension](https://marketplace.visualstudio.com/items?itemName=michelemelluso.gitignore) exists to do this and I think it would be great to add the functionality to the git context menu. 

![image](https://cloud.githubusercontent.com/assets/2449568/17113077/d76cd67a-525d-11e6-8e24-253cf4265d09.png)

**Comment by Tyriar** [comment]
Closing since there's an extension already
