### ISSUE TITLE
Vscode cannot be updated after changing the Windows username

### ISSUE THREAD

**Issue by kengdiea** [microsoft/vscode#97141]
Issue Type: <b>Bug</b>

Even when unload all can't install, I download the new installation package cannot install, official installation package is not installed the specified location, also didn't find where vscode installation configuration file, can't change the installation location, would have been an error, currently only reshipment system or to change back to the original user name to solve it, but I don't want to do so, otherwise I wouldn't change the username, reshipment system does not consider

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (2.81GB free)|
|Process Argv|C:\Users\Dante\Desktop\mpvueTest|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joaomoreno** [comment]
I'm not sure I fully understand the issue, but can you completely uninstall VS Code? And then reinstall it?

**Comment by kengdiea** [comment]
I'm worried that I won't be able to install after uninstalling, because I can't overwrite the installation when I download again, and updates won't be able to install.I would like to ask where the installation profile is, I need to modify the installation path

**Comment by joaomoreno** [comment]
We do not support changing the installation path, only uninstalling and reinstalling in a different location. Sorry about that!
