### ISSUE TITLE
Test: Navigation keys move focus in the status bar

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#97156]
Refs: https://github.com/microsoft/vscode/issues/95433

- [x] any os @bpasero
- [x] any os @chrmarti

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%2397156%0A%0A)

---

1. Use `F6` and `Shift + F6` to navigate the workbench
2. Once focus is on the status bar (first F6 after editor focus) make sure you can use Left / RIght navigation to focus each status bar item. `Home` and `End` to focus first and last item.
3. Once the focus is on a status bar item make sure you can execute it via space / enter
4. Hidden status bar items are nicely skipped
5. Move focus away to status bar and focus it again - verify that the last focused status bar item is focused again
6. Esc clear focus from the items to the staus bar
7. Turn on a screen reader on your machine and make sure that the screen reader reads the correct content once each item is focused.

**Comment by jvesouza** [comment]
@isidorn   I tested and got the following results:

* If I move the focus to notifications and press enter or space bar, the focus is moved to the editor if there are no notifications.

* If I move the focus to problems and press the space bar or enter, the focus sometimes is moved to the editor and sometimes is moved to problems view.

**Comment by isidorn** [comment]
@jvesouza thanks a lot for testing. Awesome feedback.
1) Agree. Created this issue for this https://github.com/microsoft/vscode/issues/97513
2) Can not repro. Focus is always moved to the problems view. @sandy081 is there a scenario when you pass the focus to the editor automatically from the problems view
3) Makes sense. Created this issue https://github.com/microsoft/vscode/issues/97512

**Comment by jvesouza** [comment]
@isidorn  Steps used to reproduce test 2 using orca.

* Create an empty file called test.js.

* Insert the following line without the quotations:
"1.2.3"

* Press f6 until locate the status bar.

* Press right or left arrow until found errors.

* Press space or enter.

The focus is moved to the problem view, as expected.

* Press f6 again until locate the status bar.

* Press right or left arrow until found errors.

* Press space or enter.

The focus is moved to the file being edited instead of being moved to the problem view.

**Comment by sandy081** [comment]
> Can not repro. Focus is always moved to the problems view. @sandy081 is there a scenario when you pass the focus to the editor automatically from the problems view

Yes on `Enter` on a problem moves focus to Editor.

**Comment by isidorn** [comment]
@jvesouza thanks a lot for the steps. I can reproduce.
@sandy081 the issue here is that the Problems status bar entry is a toggle, so the second time @jvesouza triggers it, it closes which is unexpected. 

So I suggest the following workaround:
If triggered via Mouse the problems status action is indeed a toggle
If triggered via Keyboard the problems status action always moves focus to the Problems view.
The problem with that is that in the command we do not know if triggered via mouse or keyboard afaik.
Alternative is for [`IStatusBarEntry`](https://github.com/microsoft/vscode/blob/756e105ee4f12330c454eb2b61fca10c35b6ced8/src/vs/workbench/services/statusbar/common/statusbar.ts#L22) to introduce a `keyboardCommand` which would be triggered via keyboard.
@bpasero let me know what you think

**Comment by sandy081** [comment]
I see. Just FYI there are other status bar items follow toggling pattern say build task entry that shows terminal.
