### ISSUE TITLE
Remove the debug.enableAllHovers settings

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#97153]
- VSCode Version: Insiders 1.45.0
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. Open your default settings
2. Notice the `debug.enableAllHovers` setting still exists but it is not used

The debug.enableAllHovers setting was [added as a workaround](https://github.com/microsoft/vscode-docs/issues/3242) for the LiveShare extension which [no longer uses it](https://github.com/MicrosoftDocs/live-share/issues/3002) and also seems to have no plans to use it in the future. I suggest we remove this setting from VS Code entirely.

Does this issue occur when all extensions are disabled? Yes

**Comment by isidorn** [comment]
@andrecasal awesome, thanks for pushing this. I just removed it.

**Comment by andrecasal** [comment]
You're very welcome, thanks 👍
