### ISSUE TITLE
Don't show task error when task providers provide shell tasks

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#97155]
https://github.com/microsoft/vscode-cpptools/issues/5388

I added a warning about task providers that don't provide the task type they say they will in April. It looks like the C++ extension is hitting this.

**Comment by alexr00** [comment]
This isn't really a bug, so much as the system implicitly allowed a behavior that now it does not.

**Comment by alexr00** [comment]
To verify:
- Install version 0.27.1 the C/C++ extension. (Extension viewlet -> right click on extension -> install another version)
- Open a C++ file. It can be empty.
- From the command palette Tasks: Run Task
- Choose the "Show All..." option
- Verify that you don't get a warning notification about task errors.

**Comment by weinand** [comment]
In 1.45.0 I get:
`The task provider for "C/C++" tasks unexpectedly provided a task of type "shell".`

Tn 1.45.1 this message no longer appears.
