### ISSUE TITLE
`gpu-process` goes to 100 when typing fast or highlighting text (no extensions installed, fresh reinstall)

### ISSUE THREAD

**Issue by GregHilston** [microsoft/vscode#97151]
I've been noticing that VSCode has been running incredibly sluggish while no other application on my machine has been. I've checked the CPU and memory consumption of the computer and performed a restart.

I disabled all extensions and even uninstalled and reinstalled VS Code. `gpu-process` skyrockets to 100 when typing quickly and highlighting text with the cursor and draging the highlight around. 

I have used VS Code for a while with no issue and not sure what is causing this. To repeat, no other application is demonstrating any signs for being slow at all.

**Comment by GregHilston** [comment]
I've discovered from [this Stackoverflow link](https://stackoverflow.com/a/30007549/1983957) how to disable the `gpu-process` by launching with:

`$ code --disable-gpu`

and can confirm that the lag is gone. Any ideas as to why using the `gpu-process` would cause issues? I'm not running any gpu application, rendering, gaming, etc. Strictly text editing.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo please see https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by GregHilston** [comment]
Hey @gjsjohnmurray here is output from `code --status`

OS: macOS Catalina 10.15.4
Processor: 2.2 Ghz 6-Core Intel Core i7
Memory: 16 GB 2400 MHz DDR4
Graphics: Radeon Pro 555X 4 GB 
Graphics: Intel UHD Graphics 630 1536 MB

**Scenario 1**

- no extensions enabled
- no workspace active
- idle

```
$ code --status                                                                                                                                                                                                                                                      130 ↵
[32941:0507/101547.737460:WARNING:dns_config_service_posix.cc(184)] dns_config has unhandled options!
Version:          Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS Version:       Darwin x64 19.4.0
CPUs:             Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)
Memory (System):  16.00GB (0.43GB free)
Load (avg):       3, 4, 3
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    0      131   32278  code main
    0       98   32288     gpu-process
    0       16   32311     utility
    0      115   32345     shared-process
    0        0   32944       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    1      246   32793     window (Untitled-1)
    0       66   32799       extensionHost
```

The important thing here is that `gpu-process` is at 0. 

**Scenario 2**

- no extensions enabled
- no workspace active
- I've typed in a few lines and drag the cursor quickly to exacerbate the issue

```
$ code --status                                                                                                                                                                                                               Pyke-3.local: Thu May  7 10:17:43 2020

[34469:0507/101743.935293:WARNING:dns_config_service_posix.cc(184)] dns_config has unhandled options!
Version:          Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS Version:       Darwin x64 19.4.0
CPUs:             Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)
Memory (System):  16.00GB (0.14GB free)
Load (avg):       3, 4, 3
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    2      131   32278  code main
   97       98   32288     gpu-process
    0       16   32311     utility
    0      115   32345     shared-process
    0        0   34484       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    6      246   32793     window (asdasdasdasdasasdasdasdasdasdasdasdasasd    Untitled-1)
    0       66   32799       extensionHost
```

**Scenario 3**

- all extensions enabled
- my workspace active
- `gpu-process` disabled by adding the line `"disable-hardware-acceleration": true` to my `argv.json`
- launched with `$ code --disable-gpu` just to be sure

```
$ code --status

[38955:0507/102259.045600:WARNING:dns_config_service_posix.cc(184)] dns_config has unhandled options!
Version:          Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS Version:       Darwin x64 19.4.0
CPUs:             Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)
Memory (System):  16.00GB (0.09GB free)
Load (avg):       4, 4, 3
VM:               0%
Screen Reader:    no
Process Argv:     --disable-gpu
GPU Status:       2d_canvas:                     unavailable_software
                  flash_3d:                      disabled_software
                  flash_stage3d:                 disabled_software
                  flash_stage3d_baseline:        disabled_software
                  gpu_compositing:               disabled_software
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        disabled_off
                  rasterization:                 disabled_software
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  disabled_software
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         unavailable_software
                  webgl2:                        unavailable_software

CPU %   Mem MB     PID  Process
   76      131   38023  code main
   14      180   38033     gpu-process
    0       16   38035     utility
    0      115   38099     shared-process
    0        0   38958       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
   37      344   38580     window (Untitled-1 t notes)
    1      131   38605       extensionHost
    0       33   38610         electron_node serverMain.js
    0       66   38611         electron_node languageserver.js
    0      131   38618         electron_node server.js
    0       33   38607       watcherService
    0       33   38614       searchService

Workspace Stats:
|  Window (Untitled-1 t notes)
|    Folder (notes): 646 files
|      File types: md(303) png(171) pdf(20) jpg(9) DS_Store(8) csv(8) zip(4)
|                  code-workspace(3) txt(2) PNG(2)
|      Conf files:
```

**Comment by deepak1556** [comment]
Thanks for the details, is it possible for you to confirm from which VSCode version this issue started appearing ?

> Now i'm not sure why gpu-process even exists with my attempts to disable it

GPU process does many other things apart from hw acceleration, so it will always exist. But the flag `disable-gpu` or setting the runtime argument `"disable-hardware-acceleration": true` will disable hw acceleration which seems to be the source of issue for your particular graphics card.

Couple of things to try:

1) Disable automatic graphic switching from the System Preferences > Energy Saver
   * Manually switch between your cards and see which one is causing the issue

2) Install our [exploration build](https://az764295.vo.msecnd.net/exploration/db8e3acd50a25be5bfac2988b4a291832a51e7cb/VSCode-darwin-exploration.zip) that has newer chromium runtime and verify if the issue happens there as well.

**Comment by GregHilston** [comment]
@deepak1556 
> Thanks for the details, is it possible for you to confirm from which VSCode version this issue started appearing ?

Sure thing!

```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z (3 wks ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

> GPU process does many other things apart from hw acceleration, so it will always exist. But the flag disable-gpu or setting the runtime argument "disable-hardware-acceleration": true will disable hw acceleration which seems to be the source of issue for your particular graphics card.

Makes perfect sense!

> Disable automatic graphic switching from the System Preferences > Energy Saver

Understood, disabled as described above. Problem is still occurring. I'm enabling automatic graphic switching, just to let you know for future dialogues.

>  Manually switch between your cards and see which one is causing the issue

Not sure how to achieve this one. Google foo failing me here.

> Install our exploration build that has newer chromium runtime and verify if the issue happens there as well.

Will try this and report back

**Comment by GregHilston** [comment]
@deepak1556 Confirmed that this issue does *not* occur with the `Code -Exploration` executable you linked above. 

Just to be super clear, this is with the "automatic graphic switching" disabled (back to its original setting) and by launching exploration normally. IE I did *not* turn on `--disable-gpu`.

Obviously this fresh install has no extension, but I want to point out that we ran my non-exploration executable without any extensions earlier and still had issues.

So what does this tell us?

**Comment by deepak1556** [comment]
> Manually switch between your cards and see which one is causing the issue
>
> Not sure how to achieve this one. Google foo failing me here.

https://github.com/CodySchrank/gSwitch seems to be widely used one.


> Confirmed that this issue does not occur with the Code -Exploration executable you linked above.

Thanks for confirming, most likely support for your gpu was updated in chromium. I am not sure which commit fixed it, have to check.

But for now you can work with `"disable-hardware-acceleration": true` in your insiders build. We will be pushing the runtime present in exploration to insiders soon.

**Comment by GregHilston** [comment]
@deepak1556 Understood, this solution totally works with me!

I wasn't sure if continuing the dialogue work help VS Code, so glad we got to the bottom of this. 

I think we're good to close this if you are and I'll go with this solution. 

Thank you guys :) What a pleasant experience,

**Comment by galich** [comment]
`code --disable-gpu` helps, thanks for that

but running Code Insiders (at the moment it's Electron 8 already) - i can see the difference when GPU is on or off. It's always better with no GPU.

* running on VMWare VM with NVidia GeForce 1070 on host with Windows 10 2004 on host and VM.

**Comment by deepak1556** [comment]
Should be fixed in latest insiders https://code.visualstudio.com/insiders and will also be fixed in next stable release.
