### ISSUE TITLE
Erratic behaviour when trying to switch tabs using shift+vertical scroll on Apple trackpad

### ISSUE THREAD

**Issue by robertrossmann** [microsoft/vscode#97164]
```
Version: 1.45.0-insider
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-06T08:25:01.764Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

When I try to use the new "tab switch using scroll" functionality with an Apple trackpad, the tab bar starts to behave erratically, sometimes switching tabs, sometimes not, and 99.9% of the time it switches to a completely random tab instead of the next or previous one.

Further observations lead me to believe that the vertical scroll events are triggering *both* tab switch and tab bar scroll (to reveal tabs not currently visible). I am attaching performance profiles for troubleshooting - they include screen recordings & input events and animations, perhaps it will help in investigation. 🙏 

Steps to Reproduce:

1. Buy an Apple laptop / Apple trackpad 💰 😇 
1. Open a bunch of tabs so they no longer fit into the visible area
1. Using the trackpad, do a vertical scroll (with two fingers) while holding shift key to perform a tab-switch-on-scroll
1. Observe jumpy at best tab switching, generally chaotic behaviour

My regular wheel mouse works as intended - a single wheel click switches to the next tab. ✅ 

Performance profiles attached below. ⬇️ 

[chrome-performance-profiles.zip](https://github.com/microsoft/vscode/files/4594315/Archive.zip)

Does this issue occur when all extensions are disabled?: 🤷‍♂️

**Comment by robertrossmann** [comment]
@bpasero I am not certain that this is a duplicate of #96409 as that issue mentions the *horizontal* scrolling sensitivity (presumably where you tilt the scroll wheel to the sides to scroll horizontally), whereas my problem is with the new vertical scrolling functionality to switch tabs. Unless, of course, the root cause is the same, but I do not know that. 😇 Just want to be sure. Thanks!

**Comment by bpasero** [comment]
@robertrossmann if your issue is about the new feature to switch tabs while scrolling, then yes it is the same issue. To clarify, the issue is about reducing the sensitivity of switching tabs during a scroll with Apple touchpads.

**Comment by robertrossmann** [comment]
@bpasero 💯 . Thanks for clarifying - confirmed duplicate.
