### ISSUE TITLE
Add option to hide account icon in activity bar

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#97167]
For those that are uninterested in signing into an account or don't want to see the icon in the activity bar, we should provide a way to hide this via the right-click menu like the rest of the other options. I'd also expect it to show up in the general right-click menu:

<img width="50%" src="https://user-images.githubusercontent.com/35271042/81323233-e9569780-9049-11ea-82a7-38863a34d66a.png">

**Comment by hparadiz** [comment]
It's amazing how much I hate that icon being there. [Chrome all over again](https://github.com/hparadiz/chromium-disable-profile-button-patch).
