### ISSUE TITLE
Shift+option+f (Format Document) not working on India keyboard layout

### ISSUE THREAD

**Issue by pulgupta** [microsoft/vscode#97166]
Issue Type: <b>Bug</b>

Shift + option + f (Format Document) is not formatting the code if the keyboard is selected as ABC - India on mac. 
Ideally it should format the file. It is working perfectly if I am switching over to US keyboard.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
prettier-vscode|esb|4.5.0
beautify|Hoo|1.5.0
vscode-kubernetes-tools|ms-|1.2.0
debugger-for-chrome|msj|4.12.6
vscode-react-native|msj|0.15.0
java|red|0.61.0
vscode-xml|red|0.11.0
vscode-yaml|red|0.7.2
vscode-checkstyle|she|1.3.2
sonarlint-vscode|Son|1.15.0
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2

</details>

**Comment by ArnieO** [comment]
I assume this has the same root cause.
On Windows 10: Shift+Alt+F is not working with Norwegian keyboard layout.

**Comment by MarioPeters** [comment]
same problem with german keyboard layout

**Comment by alexdima** [comment]
I have tried the ABC - India keyboard layout and I can confirm that the shortcut Shift+Option+F is entering some kind of composition mode. This is something the OS does, on this particular keyboard layout, so I am sorry, but there is nothing we can do in VS Code about it:

![Kapture 2020-12-09 at 15 44 14](https://user-images.githubusercontent.com/5047891/101644452-7b39df00-3a35-11eb-8193-a92b55538bcb.gif)

There are similar problematic keybindings that only use Option+Key tracked in #41024
