### ISSUE TITLE
Enlarge/change icons for a more touch-friendly interface

### ISSUE THREAD

**Issue by juanmbraga** [microsoft/vscode#97169]
Hey there, 
I was hoping to bring attention to the fact that the icons for the left panels are rather small, and I also believe them to be "tough" or not as intuitive as it could be. 

Since the day I got a touch screen laptop, I could never go back. It allows me to be more productive without having to buy a mouse to carry around, or memorize loads of commands. 
Yes, I am aware that Ctrl + '+' is capable of enlarging the whole interface, but it cannot be as elegant as something designed with touch in mind. The text size, for instance, is already fine for the code, but could be bigger on the left panels. The best way to exemplify my point is OneNote, which has a modern-looking interface, with bigger icons with touch in mind (I believe). Not only that, its icons also have more "feedback", meaning it changes when the cursor hovers over them. 

Of course, one can't expect for a different UI layout to be fit for everybody, so having an option to toggle between normal and touch, as in Office products, would be best, I imagine.

FInally, a last comparison I could make is related to the "feeling" of apps like OneNote and Office programs on windows. The latter, even though quite polished and feature-rich, does not offer the same experience as the previous. 

P.S.I: When I say "OneNote", I am refering to the app that already comes with Windows 10, and not the one included in Microsoft Office. 
P.S.II: I wrote this after researching a way to make things bigger, but could only find about the ctrl+ command.

**Comment by rebornix** [comment]
@misolori can correct if I was wrong but I think this can be improved by supporting https://github.com/microsoft/vscode/issues/519 ( *Allow to change the font size and font of the workbench* ). We are already using icon font thanks to the work @misolori has done, we can use font size to control the icons in the UI in a similar way.

**Comment by juanmbraga** [comment]
Yes @rebornix, issue #519 does involve this in a way, but wouldn't this be slightly different in the sense that it is a request for either a change in the entire interface (unlikely) or a switch to activate a more touch friendly UI? 
If, however, this feature request is deemed to be redundant in relation to issue #519 , I am ok with it being closed.

**Comment by misolori** [comment]
Closing in favor of #519, that feature should be able to designate specific font sizes for certain areas (activity bar, sidebar, trees, etc.) since they all vary and there is no single size that works across all.
