### ISSUE TITLE
JS suggestion Intellisense not working

### ISSUE THREAD

**Issue by ThomasLai1991** [microsoft/vscode#97163]
**Version of VS Code**
![image](https://user-images.githubusercontent.com/22364905/81374828-c05e0180-9132-11ea-83a8-5504e4e50542.png)

**Your operating system**
windows 7 ultimate SP1

**List of extensions that you have installed**
![image](https://user-images.githubusercontent.com/22364905/81375016-1df24e00-9133-11ea-84b2-b1ecb1900653.png)

**I've tried disabled all extension then restart VScode, still not working.**

**Reproducible steps (1... 2... 3...) that cause the issue**

1 $ mkdir toDoList      create a directory
2 $ cd toDoList           move into the created directory
3 $ node init               initialize package.json
4 $ npm i express       install express
5 $ touch app.js          create a js file
6  try to type something to trigger intellisense (say setTimeOut or setInterval or just a dot)

**What you expected to see, versus what you actually saw**
I expected to see intellisense pop up telling me any suggested methods or variables
I saw no suggestions in intellisense but only the recorded names of what I typed before

**Images, animations, or a link to a video showing the issue occurring**
![GIF 2020-5-8 14-02-26](https://user-images.githubusercontent.com/22364905/81375766-cb199600-9134-11ea-9cd5-f31596125577.gif)

for comparison below is what happen **on my another computer** everything works fine with similar settings.
![GIF 8-05-2020 6-12-07 p m](https://user-images.githubusercontent.com/22364905/81376901-fdc48e00-9136-11ea-81fd-e19b4ee034bb.gif)

**A code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally**

https://github.com/ThomasLai1991/ReportIntellisenseIssue

**Errors from the Dev Tools Console (open from the menu: Help > Toggle Developer Tools)**

![image](https://user-images.githubusercontent.com/22364905/81378865-a4f6f480-913a-11ea-96c1-007b42794dff.png)

![image](https://user-images.githubusercontent.com/22364905/81379303-74fc2100-913b-11ea-88b4-bc4481ba9496.png)

**Hmm...I just noticed this error from Dev Tools Console, I suspect my error has something to do with this. This setting.json I did not touch manually before as I am not an expert and know nothing much about it but might cause by something else when I learn about bable and node, and I don't know how to fix it as well**

- I have selected the file type as JavaScript at the bottom right corner
- I've checked the the setting that JavaScript suggestions are all turned on

But there is no suggestion at all, even a simple setTimeOut or setInterval is not there. My vscode on my another computer is working fine with identical settings.

I've tried to uninstall and reinstall vscode with the lastest version, no luck.

![image](https://user-images.githubusercontent.com/22364905/81317372-56584480-90bf-11ea-853a-f35413050608.png)

![image](https://user-images.githubusercontent.com/22364905/81317688-bc44cc00-90bf-11ea-9c6d-67c94ea5124b.png)

**Comment by mjbvz** [comment]
Please fill out the issue template. For example, what VS Code version and OS are you on?

/needsMoreInfo

**Comment by ThomasLai1991** [comment]
Thank you very much for your response, I have updated the information
according to the guidelines, thanks.

**Comment by ThomasLai1991** [comment]
> Please fill out the issue template. For example, what VS Code version and OS are you on?
> 
> /needsMoreInfo



> Please fill out the issue template. For example, what VS Code version and OS are you on?
> 
> /needsMoreInfo

Thank you sir, I've update more info.

I now highly suspect this error has something to do with the setting.json as shown in the screenshot of "Toggle Developer  Tools"
But I still don't know what is the proper value for that setting of  'javascript':'babel-node'
Would you please see to it? thanks

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by ThomasLai1991** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Hi Sir,
No it does not reproduce in the latest VS code insider.

what I found is that when I comment out this line in my settings.json in my normal vscode verson:
"javascript": "babel-node",
the bug is gone. And because the insider build use a different settings.json, the insider build does not have the same bug.

But would you mind to tell me what is the proper way to address the bug cause by that line instead of simply comment it out? Any materials to read to guide me on the settings? I don't see why babel-node is going to be a problem for JavaScript suggestion. Thank you so much, again.

**Comment by mjbvz** [comment]
What extension does the `"javascript": "babel-node",` setting come from? Can you share the full setting name?

**Comment by ThomasLai1991** [comment]
{
    "liveServer.settings.donotShowInfoMsg": true,
    "open-php-html-js-in-browser.selectedBrowser": "Chrome",
    "javascript": "babel-node",
    "[javascript]": {
        "editor.defaultFormatter": "bysabi.prettier-vscode-semistandard"
        
    },
    "javascript.suggest.completeFunctionCalls": true,
    "emmet.showSuggestionsAsSnippets": true,
    "editor.suggest.filterGraceful": false,
    "editor.quickSuggestions": true,
    "editor.lineNumbers": "on",
    "vim.insertModeKeyBindings": [
        {
            "before":["<space>","<space>"],
            "after":["<Esc>"]
        }
    ],
    "editor.cursorSurroundingLines": 15
}


this is the whole of my settings.json.
As far as as I remember I only manually set the vim settings only, didn't touch too much on any other settings, basically keep everything default.  Thank you.

**Comment by mjbvz** [comment]
It sounds like this issue is caused by one of you extensions. I don't know which extension contributes ` "javascript": "babel-node"`, but since removing that setting fixes intellisense, that extension is likely the cause.

Once you find which extension causes this, please file an issue against them
