### ISSUE TITLE
Allow tasks to run commands regardless of their output

### ISSUE THREAD

**Issue by bjarkihall** [microsoft/vscode#97161]
- VSCode Version: 1.44.2
- OS Version: Win10

Steps to Reproduce:
1. Define a task with command variable.
2. An error is thrown if the command doesn't resolve to a string.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

---

I'm trying to execute extension commands via tasks.json but an error is thrown since the commands return booleans once resolved, instead of strings.

[My issue](https://github.com/microsoft/AL/issues/5859) and others similar to it could be resolved by forcing extension creators to change their commands (or add new ones) so they return strings/undefined/null but that shouldn't really be necessary.

[We should be able to execute commands as tasks](https://github.com/microsoft/vscode/issues/11396) but the implementation assumes that the command is being run to [replace a command variable with the string output](https://code.visualstudio.com/docs/editor/variables-reference#_settings-command-variables-and-input-variables).

I thought of four different solutions to this:

1) Don't rely on the output of command variables, e.g. task type: "command".

Tasks would be able to have type: "command" and command: "commandId" for executing a command, without expecting an output (since it wouldn't require resolveVariablesFromSet to be called). See: [terminalTaskSystem's](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts) executeCommand.
This was the original proposition in 2018 so I'm not sure why it's not possible.
```
{
    "tasks": [
        {
            "label": "MyTask",
            "type": "command",
            "command": "MyCommand"
        }
    ]
}
```

2) It might be simpler to just detect if the command variable is the same as the task's command itself and skip the error throwing and the shell execution, since the output of the command variable would be blank.
```
{
    "tasks": [
        {
            "label": "MyTask",
            "command": "${command:MyCommand}"
        }
    ]
}
```

3) Use extended form of variables, e.g. something like "${command:myext.mycommand-default}" or "${commandIgnore:myext.mycommand}" so that they can output something other than a string (or choose to ignore the output and return empty string). See lines 184 and 322 (case 'command'): [configurationResolverService](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/configurationResolver/browser/configurationResolverService.ts). Similar method is suggested in #92854, except that's just for env variables, but would then apply to more types of variables.
```
{
    "tasks": [
        {
            "label": "MyTask",
            "command": "${command:MyCommand-default}"
            or...
            "command": "${commandIgnore:mycommand}"
        }
    ]
}
```

4) Provide a type and a fallback/default value for input commands, so you'd have something like:
```
{
    "tasks": [
        {
            "label": "MyTask",
            "type": "shell",
            "command": "echo",
            "args": ["${input:MyCommand}"]
        }
    ],
    "inputs": [
        "id": "MyCommand",
        "type": "command",
        "command": "myextension.mycommand",
        "returnType": "none",
        "defaultValue": ""
    ]
}
```
The returnType could also have the values "number" (fixes #95866) | "string" (default) | "boolean" etc. which would validate (just like is done now agains the string) before throwing the error.
The defaultValue could be assigned instead of throwing the error.
These could also reside within a deeper "option" object or maybe a single property which covers all the cases mentioned if that's preferred.

Please give feedback to these suggestions (or even come with an alternative) and I might submit a PR if it's simple enough to implement!

**Comment by aniongithub** [comment]
This is VERY relevant. I use a command from, say a CMake extension in `tasks.json` to build instead of invoking `cmake` directly in order to use extension settings. This always leaves a nasty error toast even though the command itself executed correctly.

An easy way for VS Code to keep existing handling of return values, but suppress the error message would be using a setting that we could set in `settings.json`, say:

`suppressCommandOutputTypeErrors: true`

this would allow workspaces to selectively supress this error if they use commands that don't return strings. Given that extensions are _the_ way to do things in VS Code, having this pop up an error for tasks that don't return string paints the picture something is broken when it clearly isn't.

**Comment by n8layman** [comment]
This seems to get around the error message. Basically, you can take advantage of `"command": "runCommands"` in an input and make sure the last command you run does return a string - even if you don't do anything with it.


```
{
  "version": "2.0.0",
  "inputs": [
    {
      "id": "RTerm",
      "type": "command",
      "command": "runCommands",
      "args": {
        "commands": [
          "r.createRTerm",
          "workbench.action.terminal.moveToEditor",
          "editor.action.copyLinesDownAction"
        ]
      }
    }
  ],
  "tasks": [
    {
      "label": "Startup R Terminal",
      "type": "process",
      "command": "${input:RTerm}",
      "problemMatcher": [],
      "presentation": {
        "reveal": "always",
        "panel": "new"
      },
      "runOptions": {
        "runOn": "folderOpen"
      }
    }
  ]
}

```
