### ISSUE TITLE
Explore a richer ui for the account picker and settings sync

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#97168]
Similar to Chrome and Edge, we should explore using a richer ui to make the information and actions much clearer. This could follow the similar visual patten as notifications.

## Chrome
<img width="50%" src="https://user-images.githubusercontent.com/35271042/81324578-068c6580-904c-11ea-9a4d-ec231752c0fb.png">

## Edge
<img width="50%" src="https://user-images.githubusercontent.com/35271042/81324500-e9579700-904b-11ea-8f6c-43ac9f8112ec.png">

**Comment by misolori** [comment]
Here's my proposal for this rich ui. This would be scoped to the account manager and clicking on any of the account items will link to their respective quick pick menu items, clicking on "Sync is on" would open the Preferences Sync quick pick, and whenever an extension does a silent sign in with the badge, this would open the flow for signing into an extension.

![Kapture 2020-05-14 at 10 56 31](https://user-images.githubusercontent.com/35271042/81968692-98a6e780-95d1-11ea-9706-1ac2fee94318.gif)

**Comment by bpasero** [comment]
@misolori @RMacfarlane @sandy081 hey, I was wondering if we could make progress on this item, e.g. by putting it back to some milestone? I really liked the UX I saw and wish we could start on the implementation 👍

**Comment by TylerLeonhardt** [comment]
Closing this in favor of #136889 (I included @misolori's mockup there)
