### ISSUE TITLE
When in centered layout, show inline diff view also in centered layout

### ISSUE THREAD

**Issue by robertrossmann** [microsoft/vscode#97165]
```
Version: 1.45.0-insider
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-06T08:25:01.764Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

When in centered layout, opening a diff view in inline mode (as opposed to side-by-side mode) should not force the diff view into full editor width as it does for side-by-side diff views.

This is a follow-up from #94696 where we discussed this might be a bug. 🤔 

Steps to Reproduce:

1. Toggle centered layout
1. Open a diff view in inline mode
1. Observe diff view now occupies full editor width (as if centered layout was not enabled)

**Demo:**

![inline-diff](https://user-images.githubusercontent.com/3058150/81321082-6c034500-9092-11ea-9686-b86f88b1113f.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
@rebornix how to check if diff is in inline view?
@robertrossmann would you like to submit a PR to fix this?
Code pointer https://github.com/microsoft/vscode/blob/193483676699fcbde88f7a7748b189cb2bda7efe/src/vs/workbench/browser/layout.ts#L1209

**Comment by robertrossmann** [comment]
@isidorn I'm afraid this is too much for me at this moment. The `centerEditorLayout()` method is not fired when I switch from inline to side-by-side diff view and I could not figure out how to query the `SideBySideEditorInput` instance for the current display mode. Both of these events would need to be handled so that we can keep the centered layout when an inline diff is opened and we should switch to full-width layout when the diff editor's layout is switched from inline to side-by-side.

**Comment by isidorn** [comment]
@robertrossmann no worries, thanks for trying. Peng might give some good tips, and I might also look into this in the future.

**Comment by petevdp** [comment]
Apologies for not mentioning that I was working on this, but I implemented a fix for this in  #97311

**Comment by ChrisPapp** [comment]
I was playing around with this and managed to fix it, so I created. My browser did not update so I didn't see your message, sorry for duplicate PR  :sweat_smile:

**Comment by petevdp** [comment]
> I was playing around with this too and managed to fix it, so I created a PR. My browser did not update so I didn't see your message, sorry for the duplicate PR

No problem! haha both our bads I guess :rofl:
