### ISSUE TITLE
[scss] depricated color list is not correct

### ISSUE THREAD

**Issue by ChadNedzlek** [Microsoft/vscode#9716]
- VSCode Version: 1.3.1

Steps to Reproduce:

1.  Open a SCSS file
2.  Type body { color: lightgray; }

"lightgray" is red.  It looks like there is some list in extensions/scss/syntaxes/scss.json that calls them "deprecated", but I can see no evidence that these colors have been deprecated, and are in specs as far back as 2011. The link in file doesn't actually point to anything.

**Comment by aeschli** [comment]
This got fixed in the latest grammar, we need to update..

**Comment by ChadNedzlek** [comment]
What is the "latest grammar"? Can we update it? It's very difficult to edit my website using VS Code, and this is newly broken behavior (it worked fine in VSCode 1.0)

**Comment by aeschli** [comment]
It was just a note for myself. I'll update to the latest grammar for the next release.
