### ISSUE TITLE
Allow extensions to contribute a view to the navigation pane.

### ISSUE THREAD

**Issue by indiejames** [Microsoft/vscode#9717]
It would be very useful for extensions to be able to contribute views to the navigation pane / leftmost pane. For instance, a Clojure extension might contribute a tree view of namespaces with symbols as the leaves for project navigation. This would allow a user to jump to a position in a file were a symbol within a namespace was defined.

**Comment by kieferrm** [comment]
@indiejames seems my original comment didn't make it through. Just pushing back on your use case a bit, why is what we have in the command palette not enough?

![screen shot 2016-08-02 at 1 49 21 pm](https://cloud.githubusercontent.com/assets/4674940/17344718/1320df9e-58b8-11e6-91f2-9988a2d4b652.png)

(I can see other good use case for a custom navigation pane, but I wonder about your concrete example.)

**Comment by indiejames** [comment]
I think the command palette symbol navigation is great once you are familiar with the symbols in a project and you know which one you want, but a browsable tree structure is very helpful when you are exploring a new codebase. Instead of browsing files you browse namespaces and symbols. I'll try to put an example image together later tonight when I have more time.

**Comment by indiejames** [comment]
This is sort of what I'm thinking for Closure namespaces:

![vscode-nav](https://cloud.githubusercontent.com/assets/308058/17353075/53f2bc66-590a-11e6-9f9b-1a4d0d892a80.png)

**Comment by ivanz** [comment]
Was just about to open an issue for the same thing, when I found this one! Similar situation here: the "command palette" is good for when know in advance what you are looking for , but not particularly amazing for code exploration. I have been using VSCode over the last 2 weeks on a couple of C# projects and would have been great to have some sort of a symbol browser on the side.

**Comment by patrickjuchli** [comment]
This would be a great feature for extensions. I'm working on a JS code exploration tool that would fit perfectly into this side bar. I could also imagine to use the VSCode UI Elements for that. Maybe the side bar could be a good test bed for custom UI extension features in the future?

**Comment by FabianLauer** [comment]
@aeschli j4i, looks like this is being tracked here: https://github.com/Microsoft/vscode/issues/15262
Also: https://github.com/Microsoft/vscode/issues/15217#issuecomment-259488001

**Comment by pavolmarko** [comment]
I would also be interested in this - my usecase is writing an extension which displays a view very similar to the Git view, but instead of displaying unstaged/staged changes, would display changes done since the current branch has branched off the master branch, as this would help me in my workflow.

**Comment by sandy081** [comment]
This is implemented by #26948. Please use this feature and open new issues for new requests. Closing this.
