### ISSUE TITLE
Wrong window closing after Codespace timesout and you "ok" the message

### ISSUE THREAD

**Issue by lucasavila00** [microsoft/vscode#97172]
- VSCode Version:
Visual Studio Code 1.44.2
- OS Version:
ProductName:    Mac OS X
ProductVersion: 10.15.4
BuildVersion:   19E266

Steps to Reproduce:

1. Have one window open on a local project
2. Have another window open with a Codespace
3. Let the Codespace be suspended due to inactivity
4. A pop up will take focus saying it was turned off etc
5. Click "OK" on that pop up from Codespace window
6. VSCode will close the window that had the local project and keep the Codespace window open

Does this issue occur when all extensions are disabled?: 
Is Codespace working as an extension?
Because it shouldn't affect my local window anyways, so I though about creating the issue here instead of in the Codespace's repository.

Thanks for your time :)

**Comment by bpasero** [comment]
@lucasavila00 can you demonstrate this flow with a screen capture or images, not quite clear to me yet.

**Comment by lucasavila00** [comment]
Window on the left is Codespace. On the right is local.

![Screen Shot 2020-05-08 at 07 57 09](https://user-images.githubusercontent.com/12750442/81399597-a0fab080-9101-11ea-8c15-261256b25213.png)

Make the local window full screenish.

![Screen Shot 2020-05-08 at 07 58 36](https://user-images.githubusercontent.com/12750442/81399676-ca1b4100-9101-11ea-958d-b4ca08f7e377.png)

After some time Codespace window will open a native popup saying  "it disconnected because of not being active etc" and will be brought to the front. (Not shown in Screenshot but is that macos native popup)

![Screen Shot 2020-05-08 at 08 00 53](https://user-images.githubusercontent.com/12750442/81399805-123a6380-9102-11ea-80b3-cf3f7d9066f5.png)

After you click OK on Codespace's window popup VSCode will close local window and leave codespace one not connected but open like this.

![Screen Shot 2020-05-08 at 08 02 25](https://user-images.githubusercontent.com/12750442/81399913-4f9ef100-9102-11ea-910b-070db5b5155b.png)

Let me know if that explains it or I can make a video or something.
Thanks :)

**Comment by bpasero** [comment]
@lucasavila00 can you specifically add the screenshot of the dialog you see, I need it to understand what code triggers the closing.

**Comment by lucasavila00** [comment]
Ok. I'm waiting for it to go inactive and I send it.

**Comment by lucasavila00** [comment]
Here are the screenshots.

I have two monitors, a and b.
I have Codespace on monitor A and local on monitor B running for a while.

Then the two screens change at the same time to become this:

A - 
![a0](https://user-images.githubusercontent.com/12750442/81412306-0e1a4000-911a-11ea-9042-5b2ccd67517f.png)

B - 
![b0](https://user-images.githubusercontent.com/12750442/81412476-4caffa80-911a-11ea-8048-ad2d3c98cbcc.png)


I click save on screen B, then OK on screen A.

They become:

A -
![a1](https://user-images.githubusercontent.com/12750442/81412401-2c803b80-911a-11ea-85d3-824d7a4f91b3.png)

B - 
![b1](https://user-images.githubusercontent.com/12750442/81412419-31dd8600-911a-11ea-9f0e-983330b93026.png)

**Comment by bpasero** [comment]
@lucasavila00 any idea why you see the dialog on your local workspace on monitor B? does that appear all of the sudden out of nowhere?

**Comment by lucasavila00** [comment]
@bpasero  Yes, out of nowhere at the same time as Codespace does.
If I don't have anything to save it just closes the window, though. If I have unsaved changes it will ask me if I want to save them.

Somehow the "close" command is being sent to the wrong window that caused it, it seems.

**Comment by bpasero** [comment]
@lucasavila00 so is there any action you do that triggers this "close", that was not clear to me from your screenshots yet.

**Comment by lucasavila00** [comment]
No input from me.
The action that triggers both events in both windows is Codespace telling me it shut down because I didn't use it in the last 30 minutes.

**Comment by bpasero** [comment]
Ok thanks, I will follow up with checking what the extension actually does in that moment.

**Comment by bpasero** [comment]
@lucasavila00 but in your initial steps it seems you are first clicking OK before the second window closes, so it is not happening automatically?

> Steps to Reproduce:
> 
> Have one window open on a local project
> Have another window open with a Codespace
> Let the Codespace be suspended due to inactivity
> A pop up will take focus saying it was turned off etc
> Click "OK" on that pop up from Codespace window
> VSCode will close the window that had the local project and keep the Codespace window open

**Comment by lucasavila00** [comment]
It is happening as soon as it shuts down.

It just happened again I can confirm it:
No need to click OK in A before B closes.

I'm sorry, I probably forgot the details when I first reported the issue and misreported it.
