### ISSUE TITLE
markdown preview is confused and missing the ``` end block

### ISSUE THREAD

**Issue by lovettchris** [microsoft/vscode#97170]
Try and preview the attached markdown file, notice the tripple back-tick end block on `Code and activity coverage options` is ignored, and the rest of the file is formatted as code.r clipboard because it was too large to send. 

[coverage.zip](https://github.com/microsoft/vscode/files/4595088/coverage.zip)

**Comment by mjbvz** [comment]
The markdown is incorrect. 

~~~md
`````
code 
```

text
~~~

Most markdown specs require the the number of opening backticks for fenced code blocks match the number of closing backticks

**Comment by lovettchris** [comment]
I see thanks, but it renders correctly on Github via Jekyll.

**Comment by mjbvz** [comment]
There are lots of different markdown specs. We target common mark: https://commonmark.org

**Comment by lovettchris** [comment]
Fair enough and I see the same rendering here: https://spec.commonmark.org/dingus/
Interesting that commonmark lists GitHub as a commonmark adopter then... must still be some ambiguity in the spec.

I notice the spec says " code fence is a sequence of at least three consecutive backtick character", but the key thing that Github seems is "The closing code fence must be at least as long as the opening fence"... so you can close this issue if you like.

**Comment by lovettchris** [comment]
By the way thanks for the quick turnaround on this, that's impressive.
