### ISSUE TITLE
Collapse Folders in Explorer command not working correctly in Multi-root Workspaces

### ISSUE THREAD

**Issue by u84six** [microsoft/vscode#97174]
- VSCode Version: 1.44.2
- OS Version: macOS Catalina

Steps to Reproduce:

1. Load Multi-root Workspace with two or more root folders
2. Open the root folders, then open some subfolders in each
3. Use the command "File: Collapse Folders in Explorer"

You'll notice that if collapses all subfolders but not the roots folders.

Work-around: issue the same command again.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This is how we designed the feature, we first collapse everything but the roots, and only then the roots.
We might reconsider and add a setting to control this in the future.
fyi @roblourens
