### ISSUE TITLE
Add new semantic token scopes to Dark+ and Light+ themes?

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#97177]
Hi @alexr00 .  You had helped us out in the context of [this issue](https://github.com/microsoft/vscode/issues/80783 ), with new entries in the Dark+ and Light+ themes for the TextMate scopes we had added for our semantic colorization implementation in the C/C++ Extension.  VS Code has since added a new Semantic Tokens API.  We're in the process of removing our custom implementation in favor of using the new API.  As a result, our scopes are changing to semantic token scopes.  Would it be possible to get these new scopes added to the Dark+ and Light+ themes as well, to make the transition as seamless as possible for users?

Our custom semantic tokens are:

old scope|	new semantic token scope
--|--
entity.name.type.class.reference|	referenceType
variable.other.property.cli|	cliProperty
entity.name.type.class.generic|	genericType
entity.name.type.class.value|	valueType
entity.name.function.templated|	templateFunction
entity.name.type.class.templated|	templateType
entity.name.function.operator|	operatorOverload
entity.name.function.operator.member|	memberOperatorOverload
keyword.operator.new|	newOperator
entity.name.operator.custom-literal.number|	numberLiteral
entity.name.operator.custom-literal|	customLiteral
entity.name.operator.custom-literal.string|	stringLiteral

'variable' is not a custom token, but 'global' and 'local' are custom modifiers:

old scope|	new semantic token scope
--|--
variable.other.global|	variable.global
variable.other.local|	variable.local

We use standard semantic tokens and modifiers for the following, so I suspect they are already accounted for.  Though combining the ‘static’ modifier with ‘property’ and ‘member’ might be unique.

old scope|	new semantic token scope
--|--
entity.name.type|	type
variable.other.enummember|	enumMember
variable.other.event|	event
entity.name.function|	function
entity.name.label|	label
entity.name.function.preprocessor|	macro
variable.other.property|	property
entity.name.function.member|	member
entity.name.namespace|	namespace
variable.parameter|	parameter
variable.other.property.static|	property.static
entity.name.function.member.static|	member.static

Thanks!

**Comment by aeschli** [comment]
@Colengms

When you switch to semantic tokens and you use custom token types/modifiers, you can also contribute a mapping to TextMate scopes through the `semanticTokenScopes` contribution point: https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-token-scope-map
That you can even do for language specific scopes. The idea for the mapping is that themes don't necessarily need any adoption. 

Adoption is only needed if you want to add new theming for semantic classifications that have no equivalent TextMate scope. There's no point in inventing a new TextMate scope, unless it's also something you want to use in your TextMate grammar, so we would add such a styling rule in the new semanticTokenColors section.
If you want such new styling, you need to tell us what classifications need what color/style.

Anther reason for an adoption in the theme is to remove TextMate theming rules for cpp specific scopes that are were just added for you and are not used in your grammars.

**Comment by Colengms** [comment]
@aeschli .  We had previously created new TextMate scopes for our prior custom implementation of semantic colorization using decorators.  I assumed I should not map our new semantic tokens to our custom TextMate scopes - They should probably be retired.  Therefor, I don't believe I have existing scopes to map my new semantic tokens to.  I'm using superType to map to the closest existing types, but that does not color most of our custom tokens.

**Comment by Colengms** [comment]
> Adoption is only needed if you want to add new theming for semantic classifications that have no equivalent TextMate scope.

To clarify, we have new semantic classifications do not have equivilent TextMate scopes.  More accurately, we had created TextMate scopes for them, which were adopted into the plus themes, but use of those scopes should be removed from plus themes, and switched to our new semantic classifications.

**Comment by alexr00** [comment]
>  I assumed I should not map our new semantic tokens to our custom TextMate scopes - They should be retired. Therefor, I don't believe I have existing scopes to map my new semantic tokens to. 

@aeschli, is this correct? Or instead should @Colengms use the `semanticTokenScopes` contribution point?

**Comment by aeschli** [comment]
Yes, if the scopes were just added for the previous C++ semantic effort, then we should remove them again. We can replace them with semantic token theming rules.
(`semanticTokenColors` property in theme definition files: https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#theming)

Do we have a list of the scopes we ended up adding? I thought it was only a few.

**Comment by alexr00** [comment]
The scopes that were added are in the following changes:
https://github.com/microsoft/vscode/commit/6d7917cd3c4ecc17f249583daf9c2f6c23e6d6e2
https://github.com/microsoft/vscode/commit/c1fdabc4f28f20fd63c6a6ef68d182617fb82813
https://github.com/microsoft/vscode/commit/6ba021ba320ee21bd533cd51dc756a6a56f92c4c
https://github.com/microsoft/vscode/commit/219735002a0cebdc886ebfbcadac2dc133422c42

**Comment by aeschli** [comment]
The following scopes were added the dark vs/plus themes based on wished from the C++ team. We added them without source.cpp qualifier, using existing color (except one new color for label)

dark_vs: [diff](https://gist.github.com/aeschli/87231cd075e82c500efc1befeea77f14/revisions)  [bcc8fb6](https://raw.githubusercontent.com/microsoft/vscode/bcc8fb61cca9b1fed803cb6988a166730fe28be9/extensions/theme-defaults/themes/dark_vs.json) [master](https://raw.githubusercontent.com/microsoft/vscode/master/extensions/theme-defaults/themes/dark_vs.json)

dark_plus: [diff](https://gist.github.com/aeschli/79e806dc6ded7b8bcb4d601047fcdcc9/revisions)  [bcc8fb6](https://raw.githubusercontent.com/microsoft/vscode/bcc8fb61cca9b1fed803cb6988a166730fe28be9/extensions/theme-defaults/themes/dark_plus.json) [master](https://raw.githubusercontent.com/microsoft/vscode/master/extensions/theme-defaults/themes/dark_lus.json)

scope|	color     | action
--|--|--
"entity.name.operator.custom-literal.number" |  number (#b5cea8) | replace
 "variable.other.enummember" | number | keep
"entity.name.function.preprocessor | keyword (#569cd6) | keep
"keyword.operator.noexcept" | keyword | remove
"entity.name.operator.custom-literal.string" | string (#ce9178)  | replace
"meta.embedded.assembly" | string  | remove
"keyword.operator.aligno/typeid/alignas/python/wordlike" | keyword | remove 
"entity.name.operator.custom-literal" | function (#DCDCAA) | replace
"entity.other.attribute" | type (#4EC9B0)  | keep
"entity.name.operator" | operator keyword (#C586C0) | keep
"entity.name.label" | new color (#C8C8C8)  | keep

For the colors to replace I would, according to the table above, add the following
```
	"semanticTokenColors": {
		"stringLiteral":"#ce9178",
		"customLiteral": "#DCDCAA",
		"numberLiteral": "#b5cea8",
	}
```

**Comment by aeschli** [comment]
@Colengms Let me know if that make sense.

**Comment by Colengms** [comment]
@aeschli The following were not requested by the C++ team, and were not part of our (prior) semantic colorization feature.  I suspect these were requests from Jeff Hykin and others, as some additional C++ related requests were batched with ours.  I suspect these should be kept:

"keyword.operator.noexcept"
"meta.embedded.assembly"
"keyword.operator.aligno/typeid/alignas/python/wordlike"
"entity.other.attribute"

Updated table:
|scope|color|action|
|---|---|---|
|"entity.name.operator.custom-literal.number"|number (#b5cea8)|replace|
|"variable.other.enummember"|number|keep|
|"entity.name.function.preprocessor|keyword (#569cd6)|keep|
|"keyword.operator.noexcept"|keyword|keep|
|"entity.name.operator.custom-literal.string"|string (#ce9178)|replace|
|"meta.embedded.assembly"|string|keep|
|"keyword.operator.aligno/typeid/alignas/python/wordlike"|keyword|keep|
|"entity.name.operator.custom-literal"|function (#DCDCAA)|replace|
|"entity.other.attribute"|type (#4EC9B0)|keep|
|"entity.name.operator"|operator keyword (#C586C0)|keep|
|"entity.name.label"|new color (#C8C8C8)|keep|

I believe the following should be added:

Dark:

```
	"semanticTokenColors": {
		"newOperator":"#C586C0", 
		"stringLiteral":"#ce9178",
		"customLiteral": "#DCDCAA",
		"numberLiteral": "#b5cea8",
	}
```

Light:

```
	"semanticTokenColors": {
		"newOperator":"#AF00DB", 
		"stringLiteral":"#a31515",
		"customLiteral": "#795E26",
		"numberLiteral": "#098658",
	}
```

The TM scope for new operator may have already been present (?), but is not currently associated with a predefined semantic token or base type, so we had to add a custom token for it.

**Comment by aeschli** [comment]
`entity.name.operator.custom-literal` is used in the [cpp](https://github.com/microsoft/vscode/blob/master/extensions/cpp/syntaxes/cpp.tmLanguage.json#L7724) and [cpp.embedded.macro](https://github.com/microsoft/vscode/blob/master/extensions/cpp/syntaxes/cpp.embedded.macro.tmLanguage.json#L7724) grammars, so I leave it in.
