### ISSUE TITLE
Outline Panel With No Contents on Startup

### ISSUE THREAD

**Issue by phptek** [microsoft/vscode#97173]
- VSCode Version: 1.45.0
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. [OK] Open a single .py file with at least one class and some attributes
2. [OK] Observe the "Outline" panel shows some expected symbols
3. [OK] Close VSCode
4. [OK] Re-open VSCode
5. [OK] Observe original .py file is has automatically been opened
6. [FAIL] Observe the "Outline" panel contains no symbols and shows the message "No symbols found in document 'foo.py'"
7. [OK] Close the .py file
8. [OK] Re-open the .py file
9. [OK] Observe the "Outline" panel now shows the expected symbols

Some sort of trigger for the "Outline" panel looks like it's not being run on startup?

Does this issue occur when all extensions are disabled?: Yes (Of course! Python language capabilities are provided by an extension)

**Comment by jrieken** [comment]
Does not reproduce for me - neither with TypeScript nor with python
