### ISSUE TITLE
 Using styled-components breaks highlighting

### ISSUE THREAD

**Issue by opotonil** [microsoft/vscode#97179]
First I thought the trouble was the `styled-components` [extension](https://github.com/styled-components/vscode-styled-components/issues/218) but after disable it the trouble continue, so now I am not sure about where is the trouble.

- VSCode Version: 1.44.2
- OS Version: Linux x64 5.6.8-arch1-1

Steps to Reproduce:

![screen-1](https://user-images.githubusercontent.com/63747287/81337220-fbb4ed80-90aa-11ea-8fda-00af456aa8c8.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please always share the text of the code along with screenshots

/needsMoreInfo

**Comment by opotonil** [comment]
Excuse me @mjbvz, here is the text of the code:

```typescript
const ComponentContainer = styled.div.withConfig({
    shouldForwardProp: (prop) => !["cell", "width", "height"].includes(prop),
})<Pick<CoverComponentProps, "cell" | "width" | "height">>`
    ${({ theme, cell, width, height }) => css`
        position: relative;
        width: ${width};
        background: ${theme.colors.grays[5]};

        ${cell
            ? css`
                  padding-top: ${height};
              `
            : css`
                  height: ${height};
              `};
    `};
`;

const ContentContainer = styled.div`
    position: absolute;
    top: 0px;
    right: 0px;
    bottom: 0px;
    left: 0px;
    display: flex;
    justify-content: center;
    align-items: center;
`;
```

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript-TmLanguage/issues/822 to track upstream

**Comment by mikestopcontinues** [comment]
I don't believe the upstream issue fully explains the issue. Here's another sample:

<img width="452" alt="81820322-1990b100-94f6-11ea-905b-53ab55930db1" src="https://user-images.githubusercontent.com/150434/81820830-b4898b00-94f6-11ea-8826-ae089aa41b07.png">
