### ISSUE TITLE
Experimental decorators warning still showing when set to true in jsconfig.json

### ISSUE THREAD

**Issue by karaluton** [microsoft/vscode#97183]
- VSCode Version: 1.44.2
- OS Version: 10.14.6

Steps to Reproduce:

1. In `jsconfig.json` set `experimentalDecorators` option to true.
2. In a JS file use a decorator.
3. At first, the warning goes away but after having VS Code open for a while it will show again. Quitting and reopening VS Code fixes it but it will eventually show up.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
