### ISSUE TITLE
Recognize .bats as Bash language

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode#9718]
I write bats (https://github.com/sstephenson/bats) tests using vscode and every time I open the file I set language to `Shell Script (bash)` manually.

May be add .bats to the list so that its language is detected automatically?

**Comment by aeschli** [comment]
You can add the file association in the settings.
Check out the `"files.associations"` setting.

**Comment by XVincentX** [comment]
@aeschli 
Would it be possible to set that option from an extension?

Basically saying "hey, if you install my extension, all `.something` files will be "coloured" using `bash` language"

**Comment by aeschli** [comment]
Yes, you can do that in a extensions. Just declare a 'language' contributions using the same id like the existing 'bash' language configuration (`shellscript`) and with '.something' in `extensions`
(all declarations are merged, so you don't need to repeat the other file extensions).
See [here](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages) for more information on the language configuration point.

**Comment by XVincentX** [comment]
@aeschli 
Thanks!
Think is that I'd like to give a new name to the language.

Let me elaborate with a practical example:
Swagger is a YAML file after all, but I am performing other operations on that.
I'd like to take advantage of `YAML` colorisation and still offer new capabilities based on language id

Does that make sense?

**Comment by aeschli** [comment]
If your files are just almost like language X but not 100%, then it's much better to have your own language id. You can copy some of the existing support (e.g. the text mate grammar) but contribute tailored support for it. Check the doc for more information on how to create and publish and extension...

**Comment by XVincentX** [comment]
@aeschli Thanks again.
Actually the language X would be 100% the same. Should I copy the definitions anyway?
