### ISSUE TITLE
terminal font size issue

### ISSUE THREAD

**Issue by nanixne** [microsoft/vscode#97188]
- VSCode Version: 1.45.0 (regression)
- OS Version: Windows 10

Steps to Reproduce:

1. open terminal font messed.
2. but if do not use default fontsize 14 either 13 or 15, it works
    "terminal.integrated.fontSize": 15,
3. "Consolas" always works, but I use "Liberation Mono"
4. uses msys2 bash as terminal  

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
Please provide a screenshot illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/needsMoreInfo

**Comment by nanixne** [comment]
![Capture](https://user-images.githubusercontent.com/46426003/81414916-54b56d80-910d-11ea-8f5f-3538d5860dcd.PNG)

sorry for missing screenshot, I just know drag picture to here to upload.
this bug can reproduced even using powershell as terminal.

steps like:
1. please type `exit` in terminal to complete quit your terminal
2. change terminal font family to "terminal.integrated.fontFamily": "Liberation Mono",
3. press Ctrl + ` to active terminal, font like the screenshot
4. change/add "terminal.integrated.fontSize": 13, everything looks good immediately
5. remove or change to default font size (14), font size changed and still look good
6. type `exit` to quit terminal
7. press Ctrl + ` to active terminal, font like screenshot.

'consolas' always work.

**Comment by Tyriar** [comment]
> change terminal font family to "terminal.integrated.fontFamily": "Liberation Mono"

Is it just this font that shows problems? Are you sure it's installed correctly? It looks like that is not actually Libration Mono as the `l` differs a lot from what I see [here](https://www.fontsquirrel.com/fonts/liberation-mono).

**Comment by nanixne** [comment]
yes, this is regression it work correctly on 1.44.2

**Comment by nanixne** [comment]
i downloaded from https://releases.pagure.org/liberation-fonts/liberation-fonts-ttf-2.00.1.tar.gz
which contains all three with multiple style liberation fonts.

**Comment by nanixne** [comment]
if you keep fontsize 13 (or any other value which is not default) every thing works.
so it seems that initial part with default fontsize has some issues, just my two cents.

**Comment by nanixne** [comment]
I cannot reproduce it today..
