### ISSUE TITLE
Error: file is a directory when ctrl+click on a path in terminal

### ISSUE THREAD

**Issue by warpdesign** [microsoft/vscode#97186]
- VSCode Version: 1.45.0
- OS Version: Windows 10.0.18363.778

Steps to Reproduce:

1. Open the integrated terminal with cmd.exe as shell
2. Ctrl+click on the command prompt

Does this issue occur when all extensions are disabled?: Yes

![terminal_click](https://user-images.githubusercontent.com/199648/81348097-bcdc6300-90bd-11ea-89ab-75a3561ed85a.gif)

**Comment by warpdesign** [comment]
> I don't think this actually reaches the bar for a recovery release fix, I've only had this one report plus the old link system is getting torn out next release. Closing in favor of the new system: `"terminal.integrated.experimentalLinkProvider": true`

Does this mean using the experimental provider should fix the problem?

**Comment by Tyriar** [comment]
Yes the link will work when using that setting, along with many other links. The one caveat is that in Windows links can break when you resize the terminal (will be fixed this iteration)
