### ISSUE TITLE
Activating extension failed: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api

### ISSUE THREAD

**Issue by TomasHubelbauer** [microsoft/vscode#97181]
- VSCode Version: 1.45.0
- OS Version: Windows 10

Steps to Reproduce:

1. Do the following:

Hi! I am using VS Code 1.45.0 and attempting to develop an extension which uses the proposed APIs. I have correctly placed `vscode.proposed.d.ts` into my extension's `src` and I've also added `enableProposedApi: true` to its `package.json`. However, when I run the extension using F5 for debugging, the extension host VS Code instance reports this error:

> Activating extension failed: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api

I have set the `--enable-proposed-api` arg in `.vscode/launch.json` for both configurations and that did not change anything - I am still getting the same error.

But I also believe this should not be necessary to do manually: the extension hosts / whatever mechanism actually runs the extension host has the knowledge of the extension's `package.json` so it knows it has this flag set in it and as such should (IMO) pass the necessary command line argument by itself.

Thoughts?

Does this issue occur when all extensions are disabled?: Does not apply!

**Comment by jrieken** [comment]
Please share you extension repo or a full sample that allows us to reproduce this

**Comment by TomasHubelbauer** [comment]
https://github.com/tomashubelbauer/vscode-video

**Comment by jrieken** [comment]
Please try without this line: https://github.com/TomasHubelbauer/vscode-video/blob/master/.vscode/launch.json#L15

**Comment by TomasHubelbauer** [comment]
I added it because it would produce the same error without it. I added in on the suggestion of the error message, but it did not help as per my original report. Without it, the same thing happens.

**Comment by jrieken** [comment]
> Hi! I am using VS Code 1.45.0 and attempting to develop an extension 

oh wait. are you using insiders or stable?

**Comment by TomasHubelbauer** [comment]
Ah! Sorry for wasting your time. It's been a while since I worked on VS Code extension development and it didn't occur to me that I needed to use VS Code Insiders to use these APIs. Thanks for spotting this!
