### ISSUE TITLE
Search editor does not persist the 'exclude configured files' setting

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#97180]
Issue Type: <b>Bug</b>

**repro**
1. Do a normal search
1. Make sure excluded configured files is enabled
1. Now open the results in a search editor

**Bug**
The search editor does not have 'exclude configured files' enabled, which makes searches very slow in projects with `node_modules`:

![Screen Shot 2020-05-07 at 12 31 15 PM](https://user-images.githubusercontent.com/12821956/81340096-1dd74d00-9064-11ea-84fe-fc81cf51bf07.png)

VS Code version: Code - Insiders 1.45.0-insider (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-06T08:25:01.764Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.04GB free)|
|Process Argv|-psn_0_45714326|
|Screen Reader|no|
|VM|11%|
</details>

**Comment by JacksonKearl** [comment]
Thanks!
