### ISSUE TITLE
Expose “Title detail/description” in Treeview API

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#97193]
Refs: #97190 

Based on the Timeline experience, it would be great if the Treeview API could expose the **title detail/description** which you see today, in the Timeline view. It displays the _current/active filename_.

Just like the Timeline view, this property should be writeable in runtime, instead of pre-defined in `package.json`.

Thank you

**Comment by eamodio** [comment]
This is actually being tracked here: https://github.com/microsoft/vscode/issues/105667
