### ISSUE TITLE
Setting has an invalid type, expected "array". Fix in JSON

### ISSUE THREAD

**Issue by EduardoBautista** [microsoft/vscode#97192]
- VSCode Version: 1.45.0
- OS Version: macOS Catalina 10.15.4

![image](https://user-images.githubusercontent.com/1585126/81354430-2d20bf80-9091-11ea-8c00-0500a66ad20d.png)

My `settings.json` file:
```
{
    "workbench.colorTheme": "Dracula",
    "files.autoSave": "afterDelay",
    "editor.fontFamily": "Operator Mono Ssm",
    "editor.rulers": [
      80
    ]
}
```

The setting does work, it just shows that warning.

Steps to Reproduce:

1. Settings > "rulers" in search
2. Click on "Edit in settings.json" under "Editor: Rulers"
3. Add any number inside of the array for the field "editor.rulers"

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Bug in my validation 
![image](https://user-images.githubusercontent.com/323878/81410713-d0f88280-9106-11ea-955c-a96f041b1865.png)

**Comment by roblourens** [comment]
This affects all numeric array settings

**Comment by JacksonKearl** [comment]
Any idea why this is just now showing up? Looks like the code is old and I'm pretty sure I've use the UI for rulers before.

**Comment by roblourens** [comment]
I only added those validations last month.

**Comment by JacksonKearl** [comment]
My bad, read the "a month ago" as "8 month ago".

**Comment by roblourens** [comment]
Better fix inb82e5905ef2ae58d709abe2c7d58a057230940fd

**Comment by gobbo712** [comment]
as of firiday may 15 this issue is NOT corrected
![image](https://user-images.githubusercontent.com/10387083/82072344-f872c080-96ad-11ea-9ecc-9e9020d4b251.png)
![image](https://user-images.githubusercontent.com/10387083/82072378-045e8280-96ae-11ea-93ba-c8335d4f4ae7.png)

**Comment by JacksonKearl** [comment]
@roblourens looks like settings with type `"string"` and default `null` still error in Stable. Fixes in Insiders.

**Comment by roblourens** [comment]
Dang. Sorry @gobbo712, it will be fixed in the next release.

**Comment by gatopeich** [comment]
I am getting this for certain "boolean", will the fix address them too?

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

If so, can you tell me which setting it is/

**Comment by gobbo712** [comment]
Hi Rob, it works fine with insiders version
