### ISSUE TITLE
`npm run install` is executed instead of `npm install` from npm: install in recently used tasks

### ISSUE THREAD

**Issue by infinnie** [microsoft/vscode#97197]
- VSCode Version: 1.44.2
- OS Version: Windows 7

Steps to Reproduce:

1. Execute the npm: install task from Terminal / Run Task… / Show All Tasks… and the `npm install` command is correctly executed.
2. Click the Terminal / Run Task… menu again. The `npm: install` task appears in recently used tasks.
3. Click the `npm: install` and what is executed is `npm run install` instead of the expected `npm install`, which would then raise an error.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by infinnie** [comment]
What if there is an `install` script (that is equivalent to `postinstall`) in the `package.json` that you expect to execute via `npm run install` (rerun the script itself without installing dependencies again)?

**Comment by alexr00** [comment]
It would do an `npm install`, not an `npm run install`.
