### ISSUE TITLE
CSS Color preview boxes are not being removed correctly in the 1.3.1

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#9719]
- VSCode Version: 1.3.1
- OS Version: macOS 10.11.3

Steps to Reproduce:

![css-bug](https://cloud.githubusercontent.com/assets/2157285/17115817/5825d124-52ca-11e6-8cef-313f4845a6ae.gif)

It started by coming of the new release (1.3.1) and happens all the time within CSS and Less.

Hope it have helped you.
Pouya

**Comment by aeschli** [comment]
Not a bug. There's a updating delay of 500ms after the last file modification for performance reasons.
