### ISSUE TITLE
[v1.45] the color of constant is inconsistency in default dark+

### ISSUE THREAD

**Issue by flasco** [microsoft/vscode#97206]
- VSCode Version: 1.45.0
- OS Version: macOS 10.14.4

Steps to Reproduce:

1. the color of constant is inconsistency  in default dark+

![image](https://user-images.githubusercontent.com/20221600/81368233-d3b4a100-9121-11ea-96a1-42dfd9c3bda1.png)
![image](https://user-images.githubusercontent.com/20221600/81368240-d6af9180-9121-11ea-9f55-52264be07db9.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by flasco** [comment]
![image](https://user-images.githubusercontent.com/20221600/81368460-63f2e600-9122-11ea-9b90-d4a17cb8b7e6.png)

extensions was closed.

**Comment by usernamehw** [comment]
Do you have `editor.semanticHighlighting.enabled` enabled in settings?

**Comment by flasco** [comment]
thanks! it solved my problem..  :)

**Comment by AndreasCag** [comment]
I have same issue with variables in dark+ theme.

`"editor.semanticHighlighting.enabled": false` didn't help in my case, though I used it previously to fix dark theme and it helped.

Do I miss something?

**Comment by usernamehw** [comment]
It works only if it's true (default value):
```js
"editor.semanticHighlighting.enabled": true
```

**Comment by AndreasCag** [comment]
@usernamehw thank you!
