### ISSUE TITLE
Hard to see which buttons are toggled in find/replace dialog boxes

### ISSUE THREAD

**Issue by user474** [microsoft/vscode#97204]
OS: Windows 10
![image](https://user-images.githubusercontent.com/55680783/81366472-19776680-912e-11ea-99cc-efcf1f0e92c1.png)

As you can see in the image above it is really hard to see which buttons are toggled and which are not especially when you have the monitor's contrast and brightness turned down all the way which is what I have when working at night.

The blue highlighting has very little contrast on the dark background. I have to look very closely to see which buttons are toggled.

Maybe a white highlighting or a lighter text color is more appropriate to indicate which buttons are on and which are off.

Thank you.

**Comment by misolori** [comment]
Verifiers: verify that you can set the new color token, `inputOption.activeForeground`, and that the default Dark/Light themes have this set like below. Ensure you test all instances of the Find widget (Search, Editor, Terminal, Debug Console)

## Dark
![image](https://user-images.githubusercontent.com/35271042/81370114-2c942300-90a9-11ea-9e09-1b6fff3d9633.png)


## Light
![image](https://user-images.githubusercontent.com/35271042/81370110-27cf6f00-90a9-11ea-91a3-e4e5f6f8f87d.png)

**Comment by isidorn** [comment]
Works great, nice job. Adding verified label.
