### ISSUE TITLE
${config:<name>} variables fail to resolve in multi-root workspace launch configurations.

### ISSUE THREAD

**Issue by bzarco** [microsoft/vscode#97202]
Issue Type: <b>Bug</b>

When I try to use `${confg:<name>}` variables in multi-root workspace launch configurations, they fail to resolve with error:

```
'${config:<name>}' can not be resolved in a multi folder workspace. Scope this variable using ':' and a workspace folder name.
```

This is not right, as there is no way to scope config variables with workspace folder names.

Minimal example, launching the configuration `Launch Program` will fail to resolve the config variable:

Hierarchy:

```
Desktop:
  test1
  test2
  test.code-workspace
```

test.code-workspace:

```
{
  "folders": [
    {
      "path": "./test1"
    },
    {
      "path": "./test2"
    }
  ],
  "launch": {
    "configurations": [
      {
        "name": "Launch Program",
        "type": "node",
        "request": "launch",
        "program": "${config:editor.fontSize}"
      }
    ]
  }
}
```

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 19.4.0

**Comment by Vitaly-Rudenko** [comment]
Can confirm. It's really annoying since I can't launch debug configuration in my workspace :(
