### ISSUE TITLE
shortcut key effect changes according to the position of the focus

### ISSUE THREAD

**Issue by dsyx** [microsoft/vscode#97211]
My environment:
Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16: 36: 23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

I usually use wsl or remote ssh in Code integrated terminal. I have encountered such a problem: when I want to change the `htop` view display format, I used the shortcut key `F5`, in theory this operation should take effect in `htop`. However, the actual effect of the operation is to start Code's Debug feature (Code's `F5`).

This does not conform to the normal logic of thinking, and the solution I have proposed is to confirm the effect of the shortcut key through the position where the current focus is focused.

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/94268#issuecomment-607835394 for a pointer to how to stop `F5` in Terminal from being treated as a VS Code command.
