### ISSUE TITLE
Type information doesn't appear when hovering over watch expressions

### ISSUE THREAD

**Issue by wesrupert** [Microsoft/vscode#9721]
- VSCode Version: 1.3.1

Now that the type information goes in the tooltip, there's no place for the user to view the type information for a root-level watch expression, as watch expressions only show the expression's value in their tooltip.

### Steps to Reproduce:

1. Hit a breakpoint
2. Create a watch expression
3. Hover mouse over the name of the watch expression

### Expected Result:
- Tooltip appears with type information like it does in the variables section

### Actual Result:
- Tooltip appears with expression's value

*Note:* Expanding an expandable watch expression and hovering over the name of a child item gives the type tooltip as expected!

**Comment by isidorn** [comment]
This should work in the latest vscode insiders release - please try it there and let me know how it goes. Thanks!
