### ISSUE TITLE
Wait for process in integrated terminal to end

### ISSUE THREAD

**Issue by Salil03** [microsoft/vscode#97217]
While developing extensions, we can send commands to integrated terminal using the `terminal.sendtext("your command")` But this does not  tell me when that command has finished executing. Typescript continues to execute other commands before integrated terminal finishes executing `your  command.` Also there is no way to extract the stderr/stdout.

It would be a nice feature to return the following in sendtext command:

1. exit code
2. stderr
3. stdout
4. give a way of knowing when the process ends

**Comment by Tyriar** [comment]
To get exit code and know when the process ends:

https://github.com/microsoft/vscode/blob/1c4b3759ff8c4483e506834e51d7e9fa31ac80b6/src/vs/vscode.d.ts#L5300-L5313

stderr and stdout are by design not exposed as everything is just coming over a single text stream to the terminal.
