### ISSUE TITLE
Terminal not accepting input with ctrl + v.

### ISSUE THREAD

**Issue by imdeep2905** [microsoft/vscode#97219]
- VSCode Version: 1.45.0
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Compile and run any Code in terminal which accepts input via stdin.
2. Paste your input in terminal it will sometimes show "^V" in terminal but not the actual inputs.
![issue](https://user-images.githubusercontent.com/55349690/81380262-36a93680-9128-11ea-9ee3-186a8967f251.PNG)

EDIT : It occurred after the latest update.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
@TylerLeonhardt can you help investigate this one? Forgot how to check if PSReadline is up and what version it is

**Comment by TylerLeonhardt** [comment]
PSReadLine appears to be loaded because there's syntax highlighting.

To confirm, @imdeep2905 can you run:

```pwsh
Get-Module PSReadLine
```

Can you also share if you changed any of the default key handlers or if you used a different PSReadLine edit mode?

**Comment by imdeep2905** [comment]
> PSReadLine appears to be loaded because there's syntax highlighting.
> 
> To confirm, @imdeep2905 can you run:
> 
> ```powershell
> Get-Module PSReadLine
> ```
> 
> Can you also share if you changed any of the default key handlers or if you used a different PSReadLine edit mode?

`ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler...}`

Above is the output of command you told me to run.

I didn't do anything related to key handlers. The issue seems quite random very hard to catch.

**Comment by TylerLeonhardt** [comment]
Interesting... Have you heard of anything like this before @daxian-dbw?

@imdeep2905 so it does work for you some/most of the time?

**Comment by imdeep2905** [comment]
Yup it seems like it works perfectly most of the time.

**Comment by daxian-dbw** [comment]
@imdeep2905 what `EditMode` are you using with PSReadLine (run `Get-PSReadLineOption | % EditMode`)? `Emacs`?
> show "^V" in terminal

This indicates `ctrl+v` is not bound in PSReadLine.
@TylerLeonhardt mentioned VSCode on windows is updated to directly pass `ctrl+v` to PSReadLine, is that change first introduced in `1.45.0`? Could this be related to that?

**Comment by imdeep2905** [comment]
That command you told me to run ```(i.e. Get-PSReadLineOption | %EditMode)``` gives no output.

**Comment by TylerLeonhardt** [comment]
Maybe just paste the result of `Get-PSReadLineOption`

**Comment by imdeep2905** [comment]
```
EditMode                               : Windows
AddToHistoryHandler                    : 
HistoryNoDuplicates                    : True
HistorySavePath                        : C:\Users\Deep Raval\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine\ConsoleHost_history.txt
HistorySaveStyle                       : SaveIncrementally
HistorySearchCaseSensitive             : False
HistorySearchCursorMovesToEnd          : False
MaximumHistoryCount                    : 4096
ContinuationPrompt                     : >> 
ExtraPromptLineCount                   : 0
PromptText                             : > 
BellStyle                              : Audible
DingDuration                           : 50
DingTone                               : 1221
CommandsToValidateScriptBlockArguments : {ForEach-Object, %, Invoke-Command, icm...}
CommandValidationHandler               : 
CompletionQueryItems                   : 100
MaximumKillRingCount                   : 10
ShowToolTips                           : True
ViModeIndicator                        : None
WordDelimiters                         : ;:,.[]{}()/\|^&*-=+'"–—―
CommandColor                           : "$([char]0x1b)[93m"
CommentColor                           : "$([char]0x1b)[32m"
ContinuationPromptColor                : "$([char]0x1b)[37m"
DefaultTokenColor                      : "$([char]0x1b)[37m"
EmphasisColor                          : "$([char]0x1b)[96m"
ErrorColor                             : "$([char]0x1b)[91m"
KeywordColor                           : "$([char]0x1b)[92m"
MemberColor                            : "$([char]0x1b)[97m"
NumberColor                            : "$([char]0x1b)[97m"
OperatorColor                          : "$([char]0x1b)[90m"
ParameterColor                         : "$([char]0x1b)[90m"
SelectionColor                         : "$([char]0x1b)[30;47m"
StringColor                            : "$([char]0x1b)[36m"
TypeColor                              : "$([char]0x1b)[37m"
VariableColor                          : "$([char]0x1b)[92m"
```

**Comment by Tyriar** [comment]
@TylerLeonhardt anything else to do here?

@daxian-dbw as a workaround you can remove the ctrl+v keybinding as below, you will lose multi-line paste in PowerShell though:

```json
{
	"key": "ctrl+v",
	"command": "-workbench.action.terminal.sendSequence",
	"when": "terminalFocus && !accessibilityModeEnabled && terminalShellType == 'pwsh'"
}
```

**Comment by TylerLeonhardt** [comment]
@imdeep2905 can you still repro this behavior?

**Comment by imdeep2905** [comment]
It turns out that now I understand when this problem occurs. Whenever program is being compiled (with combined compile and run command) pasting will always result in the issue. Although if u paste it after program is compiled then there is no issues.

So it's not a major issue. We can close the issue if you want.

P.S. It wasn't happening in previous versions.

**Comment by Tyriar** [comment]
I guess ^v gets routed to the program that doesn't know how to handle it, and not to psreadline in that case. I'll keep this open as we could create another context key for when another program is running in the terminal and disable it in that case https://github.com/microsoft/vscode/issues/99991
