### ISSUE TITLE
Color self-adoption 'Render Whitespace' is needed

### ISSUE THREAD

**Issue by pjx206** [microsoft/vscode#97214]
I'm using the theme `One Dark Pro` and I've set `Editor: Render Whitespace`.
But I found that the dots rendered are not very easy to identify because their color is nearly the same as the background's. I have to stare at the whitespace for a while to see them.
![image](https://user-images.githubusercontent.com/31790712/81374858-ce138700-9132-11ea-9bca-2e2f06358e4c.png)

**Comment by usernamehw** [comment]
You can already do that. From `settings.json`

```js
"workbench.colorCustomizations": {
	"editorWhitespace.foreground": "#ff0000",
}
```
Also possible for a specific theme
```js
"workbench.colorCustomizations": {
	"[Monokai]": {
		"editorWhitespace.foreground": "#ff0000",
	},
}
```

**Comment by gjsjohnmurray** [comment]
Also consider raising the issue with theme provider at https://github.com/Binaryify/OneDark-Pro
