### ISSUE TITLE
Git SCM hit Github

### ISSUE THREAD

**Issue by tamtranjy** [microsoft/vscode#97224]
Issue Type: <b>Performance Issue</b>

Hi,
Recently, our organization IP address has been blocked by Github due to abuse protection mechanism. I have checked firewall log as well as user laptop and seen that he is using Code with SCM enable. Although it is a local bare repo in his working directory, many connections have been sent to Github.
This leads to the situation that Github blocked access from our organization and other users cannot access Github pages.

Could you please help me to check this issue?

BR,
Tam

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
What extensions do you have installed in that machine?

**Comment by tamtranjy** [comment]
> What extensions do you have installed in that machine?

C/C++ 0.27.1
C++ Intellisense 0.22
Notepad++ keymap 1.0.5
Python 2020.4.76186

**Comment by joaomoreno** [comment]
Could you show me what kind of URLs from GitHub are being hit? This is very strange, since Code doesn't talk to Github automatically.

**Comment by tamtranjy** [comment]
I do not know the URL. I can only catch the SrcIP and DstIP of his laptop then compare them with the IP addresses in _https://api.github.com/meta_.

**Comment by joaomoreno** [comment]
Are you sure no other extensions are installed?

**Comment by tamtranjy** [comment]
Sorry for late reply.  
I pretty sure that no others plugins were installed on user's laptop.
I have tried to reproduce the issue on his laptop and my laptop as well  but the issue had not happened again.
