### ISSUE TITLE
Aria Autocomplete not working with JSX (React)

### ISSUE THREAD

**Issue by deadcoder0904** [microsoft/vscode#97220]
Issue Type: <b>Bug</b>

Can't get autocomplete suggestions for aria attributes while using JSX (React). Just write open any React project & try typing `aria-` & see there is no autocomplete.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|14.95GB (8.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (120)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-profile-switcher|aar|0.3.3
string-converter|ada|0.1.2
codesnap|adp|1.0.27
alpine-js-intellisense|adr|1.2.0
markdown-toc|Ala|1.5.6
TabOut|alb|0.1.6
Bookmarks|ale|11.1.0
project-manager|ale|10.12.0
alignment|ann|0.3.0
vscode-apollo|apo|1.15.4
ascii-tree-generator|apr|1.2.3
svgmini|ave|0.2.1
vscode-icontheme-nomo-dark|be5|1.3.6
search-crates-io|bel|1.2.1
color-info|bie|0.5.1
vscode-tailwindcss|bra|0.2.0
better-toml|bun|0.3.2
simple-react-snippets|bur|1.2.2
turbo-console-log|Cha|1.4.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
overmind-devtools-vscode|chr|0.0.27
coddx-alpha|cod|0.2.28
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.10.1
flutter|Dar|3.10.1
vscode-eslint|dba|2.1.5
emulate|Die|1.4.0
githistory|don|0.6.5
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|4.5.0
vscode-highlight|fab|1.4.1
vscode-open-in-github|fab|1.2.3
vscode-todo-plus|fab|4.17.1
auto-rename-tag|for|0.1.2
code-runner|for|0.10.0
macros|ged|1.2.1
gc-excelviewer|Gra|2.1.34
debug-visualizer|hed|1.0.0
headwind|hey|1.6.5
RelativePath|jak|1.4.0
latex-workshop|Jam|8.9.0
svelte-vscode|Jam|0.9.3
hungry-delete|jas|1.6.0
search-node-modules|jas|1.3.0
vscode-pigments|jas|2.0.0
pubspec-assist|jer|1.0.3
vscode-hacker-typer|jev|0.1.1
vscode-text-pastry|jkj|1.2.0
read-time|joh|0.2.0
vscode-cloak|joh|0.3.0
vscode-peacock|joh|3.7.0
vscode-styled-components|jpo|0.0.29
vscode-colorize|kam|0.8.16
swift|Kas|0.2.0
auto-comment-blocks|kev|1.0.1
vscode-dashboard|kru|2.1.2
node-module-intellisense|lei|1.5.0
expand-region|let|0.1.4
Kotlin|mat|1.7.1
metago|met|3.7.0
vscode-language-babel|mgm|0.0.27
git-graph|mhu|1.22.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.15
vscode-docker|ms-|1.1.0
python|ms-|2020.4.76186
vscode-typescript-tslint-plugin|ms-|1.2.3
wordcount|ms-|0.1.0
debugger-for-chrome|msj|4.12.6
vetur|oct|0.24.0
vscode-jest|Ort|3.2.0
cargo|pan|0.2.3
advanced-new-file|pat|1.2.0
vscode-versionlens|pfl|0.27.0
material-icon-theme|PKi|4.1.0
remove-comments|pli|1.2.2
polacode|pnp|0.3.4
total-lines|pra|0.0.1
prisma|Pri|0.0.35
vscode-graphql|Pri|0.2.14
java|red|0.61.0
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.4
ActiveFileInStatusBar|Ros|1.0.3
rust|rus|0.7.5
vscode-javascript-booster|sbu|0.12.3
crates|ser|0.4.9
code-settings-sync|Sha|3.4.3
mdx|sil|0.1.0
svg-preview|Sim|2.8.3
vscode-fileutils|sle|3.0.1
velocity|sod|0.2.0
autoimport|ste|1.5.3
vscode-field-lights|sve|0.0.11
ayu|tea|0.18.0
alphabetical-sorter|ue|2.0.1
vscodeintellicode|Vis|1.2.7
vscode-svg-previewer|vit|0.5.2
rainbow-tags|vol|0.3.1
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2
vscode-icons|vsc|10.1.1
codetour|vsl|0.0.25
gistfs|vsl|0.0.67
gitdoc|vsl|0.0.6
gitmoji-vscode|Vtr|0.1.8
vscode-wakatime|Wak|4.0.0
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|2.8.0
material-theme|zhu|3.4.0

(43 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
<img width="1206" alt="Screen Shot 2020-05-08 at 11 53 05 AM" src="https://user-images.githubusercontent.com/12821956/81438978-7bca6a00-9122-11ea-8d44-fc8b75dc1325.png">

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by deadcoder0904** [comment]
Hey @mjbvz, that's not JSX. Notice, you are missing the `() => ` like:

```js
const a = () => <div ari></div>
```

I don't have insiders build but it doesn't work with all extensions disabled while using the latest version which just released (April 2020) :)

**Comment by mjbvz** [comment]
Yes it is valid jsx. Your example also works fine for me in insiders:

<img width="943" alt="Screen Shot 2020-05-08 at 9 13 27 PM" src="https://user-images.githubusercontent.com/12821956/81463749-c377e280-9170-11ea-883b-807ad32b2977.png">

Do you import react or reference it anywhere in your project?

**Comment by deadcoder0904** [comment]
> Do you import react or reference it anywhere in your project?

No, I'm using it with [Next.js](https://nextjs.org) so no need to do

```js
import React from 'react'
```

It's just a basic project I just started & couldn't find `aria` autocompletion within it.

**Comment by mjbvz** [comment]
Put together minimal repo upstream: https://github.com/microsoft/TypeScript/issues/39530
