### ISSUE TITLE
React JSX Comment syntax highlight

### ISSUE THREAD

**Issue by kannan-balasubramanian** [microsoft/vscode#97223]
Issue Type: <b>Bug</b>

In the React JSX code, when I comment a component tag, the highlight is working correctly. The moment I save the file, the highlight is not working properly.

Please check the screenshot at [https://imgur.com/a/NySvGqQ](https://imgur.com/a/NySvGqQ)

------------------------------------------------------------------------------------------------------------

VS Code version: Code - Insiders 1.46.0-insider (d487078dc7fc1c276657cadb61b4f63833a8df55, 2020-05-07T16:19:54.327Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.67GB (19.70GB free)|
|Process Argv|--user-data-dir userdata --extensions-dir extensions|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
bracket-pair-colorizer-2|Coe|0.0.29
sublime-babel-vscode|jos|0.2.10
powershell|ms-|2020.4.0
material-icon-theme|PKi|4.1.0
code-spell-checker|str|1.8.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Might be a problem with format on save?

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also please always share the text of the code along with screenshots

**Comment by kannan-balasubramanian** [comment]
Yes, it's still reproducible after commenting and saving the file.
Please note that before saving the file the highlighting works fine, but the moment the file is saved then the highlighting goes wrong.

The format on save is enabled.
------------------------------
Please find below the React code (PS: the bug reporting editor doesn't highlight the below code properly, so have uploaded the code [here](https://pastebin.com/SngP4NiC) too.)

`import React, { Component } from 'react';
import Radium, { StyleRoot } from 'radium';

class App extends Component {
  render() {
    return (
      {/* <StyleRoot> */}
        <div>
          <h1>Hi, I'm a React App</h1>
        </div >
      {/* </StyleRoot> */}
    );
  }
}

export default Radium(App);`
---------------------------------
Version: 1.46.0-insider
Commit: d487078dc7fc1c276657cadb61b4f63833a8df55
Date: 2020-05-07T16:19:54.327Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by mjbvz** [comment]
Are you sure that's valid JSX? I've only seen that style of comment inside other jsx elements
