### ISSUE TITLE
unable to open file and setting

### ISSUE THREAD

**Issue by nayanpal777** [microsoft/vscode#97239]
Issue Type: <b>Bug</b>

unable to open file and setting error message such as
Unable to open 'angApp.js': Assertion Failed: argument is undefined or null.
Unable to open 'Settings': Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node..

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

**Comment by IllusionMH** [comment]
/needsMoreInfo

> VS Code version: Code 1.40.2

is old version.

Is it reproducible in latest version v1.45?
https://code.visualstudio.com/Download
