### ISSUE TITLE
Hang due to recursive regex in TextMate highlighting

### ISSUE THREAD

**Issue by sheaf** [microsoft/vscode#97238]
VS Code: versions 1.44 and 1.45    
OS: Windows 10 x64    

-------------------------------------

In working on the [Haskell syntax highlighting extension](https://github.com/JustusAdam/language-haskell) I unfortunately had to resort to some rather complex regular expressions (I wish there was a better system for syntax highlighting but oh well).

[One in particular](https://github.com/JustusAdam/language-haskell/blob/89e185cf6339da9e4dc651c4948509e511a06246/syntaxes/haskell.YAML-tmLanguage#L797) seems to cause VS Code to hang.

I've managed to minimise the problem to the following. Enable TextMate highlighting with the following single pattern:

```json
  "patterns": [
    {
      "begin": "=",
      "end": "(?<paren>\\((?:[^\\(\\)]*|\\g<paren>)*\\))\\s*`[\\p{Lu}\\p{Lt}][\\p{Ll}_\\p{Lu}\\p{Lt}\\p{Nd}]*`"
    }
  ],
```

With syntax highlighting enabled and using the above TextMate rule, paste the following into a VS Code window:

```haskell
= ( T b c ( d e ) f ) `C` ( A b )
```
This should not cause any particular issues yet (although the syntax highlighting might be a bit slow to appear, not that you can tell as no TextMate scopes are present in this minimal repro).    
Now try to remove the closing parenthesis after `f`. This should cause VS Code to hang for an unreasonable amount of time (and it is significantly worse with the non-simplified regular expression).

Note that using the same regular expression

```regex
(?<paren>\((?:[^\(\)]*|\g<paren>)*\))\s*`[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}]*`
```

in an online editor such as [Regex101](https://regex101.com/) causes no issues, and the highlighting updates very responsively.

This is with VS Code 1.44 (on Windows 10 x64).    
The situation seems to have improved slightly with the update 1.45 as the hang is noticeably smaller, but I still feel like the delay is unreasonable for a simple recursive expression (used to parse nested parentheses), given that other highlighters seem to be much faster.

**Comment by effleurager** [comment]
A regex search of a file with the following also causes a hang:
```ruby
smallest_valid_png = %w[89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 00 01 00 00 00 01 08 06 00 00 00 1f 15 c4 89 00 00 00 0a 49 44 41 54 78 9c 63 00 01 00 00 05 00 01 0d 0a 2d b4 00 00 00 00 49 45 4e 44 ae 42 60 82]
```
regex: 
```regex
(?:smallest_valid_png = %w\[)(?:.*( ))*\]
```

**Comment by alexr00** [comment]
@sheaf Can you try again with 1.46 or 1.47 insiders? There have been some textmate related changes.

**Comment by effleurager** [comment]
No change in regex thrashing behaviour.

---
Version: 1.47.0-insider
Commit: e95f9e63380a139cb1cbe54bacfc6703b96e30b9
Date: 2020-07-07T07:46:45.605Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Comment by sheaf** [comment]
Hey @alexr00, thanks for the follow-up. Unfortunately I haven't noticed any improvements on 1.46.1 compared to 1.45 (whereas 1.45 had been a significant improvement on 1.44).

**Comment by alexr00** [comment]
@alexdima is there anything that vscode textmate can do about this?

**Comment by alexdima** [comment]
`vscode-textmate` uses [oniguruma](https://github.com/kkos/oniguruma) as the regex library, so it might have some missed optimization opportunity compared to regex101 for the regex:
```regex
(?<paren>\((?:[^\(\)]*|\g<paren>)*\))\s*`[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}]*`
```

Regarding https://github.com/microsoft/vscode/issues/97238#issuecomment-631545925 , that looks to be mentioning a search in file, where we use the built-in JavaScript regex, so these two issues are AFAICT unrelated.
