### ISSUE TITLE
Update variables in Variable Window

### ISSUE THREAD

**Issue by caboom04** [microsoft/vscode#97236]
I have a problem when I developing a Debug Server for C/C++.
When I set new value to a variable in Variable Window, the client send SetVariableRequest. The variable is changed and it has side effects on other varialbes (tags of a union, etc.), it seems that there is no API to notify VSCode to update the variables. The variables in Watch Window will evaluate again.
I think that, there should be a way to notify VSCode to update some/all nodes in Variable Window. Otherwise, it looks very strange.

**Comment by weinand** [comment]
You can use the newly [`invalidated` event](https://code.visualstudio.com/updates/v1_50#_new-invalidated-event) to force a refresh.
