### ISSUE TITLE
Login dialog will not go away.

### ISSUE THREAD

**Issue by jonathan-meyer** [microsoft/vscode#97233]
Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Start VSCODE
2. Pull hair out!

![image](https://user-images.githubusercontent.com/20321382/81394113-6f78e980-90ef-11ea-858c-04c0a70654cb.png)

The dialog box will not go away! And as you can see from the image it does't even tell you what username/password it wants. 

Does this issue occur when all extensions are disabled?: Yes/No

YES!!!

![image](https://user-images.githubusercontent.com/20321382/81394456-ef9f4f00-90ef-11ea-8927-35b4001514ea.png)

**Comment by Tyriar** [comment]
Does it reproduce if you close all windows and launch with `code --disable-extensions`?

**Comment by jonathan-meyer** [comment]
I found a work around. 

Uninstall 1.45 and install 1.44
