### ISSUE TITLE
JS convert to template string incorrect when original contains quote character

### ISSUE THREAD

**Issue by 5argon** [microsoft/vscode#97232]
Issue Type: <b>Bug</b>

If I have a cursor at the `hello` of the first line below and use lightbulb suggestion "Convert To Template String" it would change to the one like `helloWithQuote2`.

```
  const helloWithQuote = '"' + " hello " + '"'
  const helloWithQuote2 = `\\" hello \\"`
  console.log(helloWithQuote)
  console.log(helloWithQuote2)
```

![image](https://user-images.githubusercontent.com/5653276/81392748-543ac800-9149-11ea-9cbc-3692ebd367f4.png)
Output : 
```
" hello "
 \" hello \" 
```

Meaning that the conversion result is wrong because it adds an escaped backslash.

Expected result should be :
![image](https://user-images.githubusercontent.com/5653276/81393061-dc20d200-9149-11ea-9237-3f6eaab8911b.png)

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
svelte-intellisense|ard|0.7.1
npm-intellisense|chr|1.3.0
mustache|daw|1.1.1
prettier-vscode|esb|4.5.0
dotnet-test-explorer|for|0.7.1
vscode-pull-request-github|Git|0.16.0
vscode-mocha-test-adapter|hbe|2.3.0
vscode-test-explorer|hbe|2.18.0
svelte-vscode|Jam|0.9.3
vscode-edit-csv|jan|0.2.7
vscode-peacock|joh|3.7.0
docomment|k--|0.1.9
graphql-for-vscode|kum|1.15.3
Kotlin|mat|1.7.1
vscode-clang|mit|0.2.3
HTMLHint|mka|0.6.0
lc3-assembly|mke|0.1.5
csharp|ms-|1.21.18
cpptools|ms-|0.27.1
Go|ms-|0.14.1
color-highlight|nau|2.3.0
language-liquid|nei|0.1.1
proto|pet|0.0.2
much-assembly-required-language-support|PJB|0.1.5
java|red|0.61.0
postcss|ric|2.0.0
text-marker|ryu|1.11.0
vscode-bolt-language|smk|0.0.4
ayu|tea|0.18.0
vsfire|tob|1.4.1
ink|tom|0.1.0
sort-lines|Tyr|1.9.0
unity-debug|Uni|2.7.5
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2
vim|vsc|1.14.1
better-align|wwm|1.1.6
vscode-surround|yat|1.0.2

(34 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Works fine for me in VS Code insiders (1.46). Let me know if you still see the issue in that version
