### ISSUE TITLE
[v1.45] Holding CTRL while clicking on a recently opened workspace does not open a new window anymore

### ISSUE THREAD

**Issue by carestad** [microsoft/vscode#97237]
- VSCode Version: 1.45.0
- OS Version: Pop!_OS 20.04

Steps to Reproduce:

1. Click `File > Open Recent` (and make sure you have another recent workspace in the list)
2. Hold the `CTRL` key while selecting a recent entry in the list (this used to work up until v1.45)

Trying different combinations of modification keys like `SHIFT`+`CTRL` before selecting an entry does not work either.

This was a very handy way of opening other workspaces in separate windows up until the recent release. Not sure what might have "broken" it, or if it ever was an intended feature.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@carestad what OS is that you are using, a Linux variant? Do you see a custom title/menu or the native one. Can you attach a screenshot?

**Comment by bpasero** [comment]
I can reproduce when custom menu is enabled. Probably a regression where we no longer forward the event that I need to check on.

**Comment by carestad** [comment]
> @carestad what OS is that you are using, a Linux variant? Do you see a custom title/menu or the native one. Can you attach a screenshot?

I am using Pop!Os. It is a Ubuntu variant, based of Ubuntu 20.04. They are a lot similar.

**Comment by bpasero** [comment]
@sbatten it is here:

https://github.com/microsoft/vscode/blob/54808814bac0d6ef1850e2c2bd15443c505ead25/src/vs/workbench/browser/parts/titlebar/menubarControl.ts#L225-L231

Open for suggestions how to fix this. In Electron we actually get the event through still.

**Comment by bpasero** [comment]
There are at least 2 more actions expecting an `event` object that are maybe broken too:

https://github.com/microsoft/vscode/blob/54808814bac0d6ef1850e2c2bd15443c505ead25/src/vs/workbench/contrib/debug/browser/debugActions.ts#L84

and

https://github.com/microsoft/vscode/blob/54808814bac0d6ef1850e2c2bd15443c505ead25/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L191

//cc @isidorn @Tyriar

**Comment by isidorn** [comment]
@bpasero thanks for the ping. It is not major breakage in debug, so we can live with it and fix in may.

**Comment by Tyriar** [comment]
Not that big of a deal in terminal either, you can ctrl+click the terminal + icon to split it, but the split button is right next to it.

**Comment by falco467** [comment]
I can confirm the bug on windows 10 with 1.45.0

**Comment by feeva** [comment]
Note, Ctrl + click on Welcome page works well. (at least Windows 10 for me)

**Comment by bpasero** [comment]
This is actually a general issue and seems to originate from https://github.com/microsoft/vscode/commit/102f6d3a00300ac6dfaace5330e5781415122599

We could probably isolate the change that was made to pass `undefined` only for context menus, but not in other cases to give others a chance to adopt this somewhat breaking change.

To recap:
* some menu entries relied on the `event` being passed around (e.g. open recent)
* some actions such as the terminal one relied on the `event` being passed around from our normal action bar (unrelated to menus)

I think the right fix depends on the area:
* menus should contribute an `alt` command to signal what should happen on option click, this applies to the "open recent" sub menu and probably also the debug one
* terminal should investigate if it can follow a similar approach, this depends on wether commands can be contributed to the place where the terminal action is used

**Comment by bpasero** [comment]
I had to add a new option to the view item to get the event for the new home indicator:

https://github.com/microsoft/vscode/commit/77b5058284a50445674ee3b237ad64793b38965e#diff-f2797369572d3575ad7eb5de58fdde7cR34

**Comment by sbatten** [comment]
Leveraging the option @bpasero  provided, I added the same option on menu widgets that the menu bar can set. We can't just have this flag on all menus since that would reintroduce the bug I fixed with the commit that created this issue. Instead limiting it to the menu bar sufficiently blocks this from impacting any extension contributed actions.
