### ISSUE TITLE
Run C/C++ Tasks tips "The task provider for "C/C++" tasks unexpectedly provided a task of type "shell"."

### ISSUE THREAD

**Issue by Gorgeous2017** [microsoft/vscode#97244]
Issue Type: <b>Bug</b>

when I run tasks in VSCode, it give me a error tips.
![Screenshot_20-05-08_18-49-57](https://user-images.githubusercontent.com/33201519/81399537-bb627780-915d-11ea-9cb8-721fb312dc95.png)
![Screenshot_20-05-08_18-51-40](https://user-images.githubusercontent.com/33201519/81399545-bd2c3b00-915d-11ea-8a81-43ba1290f3d0.png)

this tasks is create in Feb. In that time, no error tips.

my task.json like this:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "ESP8266 Project Clean",
            "type": "shell",
            "command": "make",
            "args": [
                "clean"
            ],
            "options": { 
                "cwd": "${fileDirname}/.." 
            }
        },
        {
            "label": "ESP8266 Project Make",
            "type": "shell",
            "command": "make",
            "args": [
                "all"
            ],
            "options": {
                "cwd": "${fileDirname}/.." 
            },
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": [
                    "relative",
                    "${fileDirname}/.."
                ],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }
        },
        {
            "label": "ESP Build",
            "type": "shell",
            "dependsOrder": "sequence", 
            "dependsOn": [ 
                "ESP8266 Project Clean",
                "ESP8266 Project Make"
            ],
            "group": {
                "kind": "build", 
                "isDefault": true 
            }
        }
    ]
}
```

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (3.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
increment-selection|alb|0.2.0
project-manager|ale|10.12.0
doxdocgen|csc|0.6.0
arm|dan|1.3.1
c-cpp-compile-run|dan|1.0.8
prototxt|dmi|0.0.6
githistory|don|0.6.5
gitlens|eam|10.2.1
git-project-manager|fel|1.7.1
vscode-power-mode|hoo|2.2.0
comment-translate|int|1.4.2
better-cpp-syntax|jef|1.14.30
polacode-2019|jef|0.5.2
vscode-gutter-preview|kis|0.26.1
mssql|ms-|1.9.0
python|ms-|2020.4.76186
cpptools|ms-|0.28.0-insiders2
snippet-creator|nik|0.0.5
vscode-jsp|pth|0.0.3
java|red|0.61.0
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.3
pdf|tom|0.6.0
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2
clang-format|xav|1.9.0
markdown-all-in-one|yzh|2.8.0
material-theme|zhu|3.4.0
linkerscript|Zix|1.0.0

</details>

**Comment by Tyriar** [comment]
/extC++

cc @alexr00
