### ISSUE TITLE
Custom editor does not open properly

### ISSUE THREAD

**Issue by caponetto** [microsoft/vscode#97242]
```
Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:10:24.511Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.6.10-300.fc32.x86_64 snap
```
Steps to Reproduce:

1. Package and install the [custom-editor-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/custom-editor-sample);
2. Run VSCode from terminal using `--args --enable-proposed-api`;
3. Open the file `example.pawDraw`;
4. Close VSCode and repeat step 2.

**Expected behavior**: `example.pawDraw` is loaded properly.
**Current behavior**:  `example.pawDraw` is not loaded properly. See:
![Screenshot from 2020-05-08 07-48-01](https://user-images.githubusercontent.com/638737/81398929-87a53480-9100-11ea-9a21-7f067a09d02e.png)

I need to reopen the file in order to load it properly.
It also happens to the custom editor that I'm working on, which jeopardizes the backup feature.

Does this issue occur when all extensions are disabled?: Not applicable

/cc @mjbvz

**Comment by mjbvz** [comment]
Are there any errors printed in the console when this happens?

**Comment by caponetto** [comment]
No, I can only see `INFO` logs.

I just tested on Windows and I can confirm that it is working fine.
Probably it is a Linux thing.

**Comment by caponetto** [comment]
@mjbvz FYI: I cannot reproduce this issue on v1.47.0. :smile:
