### ISSUE TITLE
Limitation of the number of model markers / errors

### ISSUE THREAD

**Issue by N8th8n8el** [microsoft/vscode#97243]
- VSCode Version: Version: 1.44.1
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
- OS Version: MacOS 10.15.4 (19E287)

Background:

I am working on a webapp using the monaco editor (https://github.com/Microsoft/monaco-editor)
(to indicate errors I use the `monaco.editor.setModelMarkers` function). 

I noticed that there seems to be a limitation of the number of markers that can be shown. Since monaco is part of VSCode I then tried to reproduce the issue in VSCode:

Steps to Reproduce:

1. Create new file and change filetype to `JavaScript`
2. Change the file content to 
```js
const x1 = 
const x2 = 
const x3 = 
const x4 = 
//...
const x998 = 
const x999 = 
const x1000 = 
```
JS code to generate this: 
```js
[...Array(1000).keys()].map(k => `const x${k + 1} = `).join('\n')
```
Pastebin: https://pastebin.com/g8NVVgJW

The modelMarkers that indicate the errors stop appearing at line 502:
![Screenshot 2020-05-08 at 12 48 38](https://user-images.githubusercontent.com/19362696/81398881-57728b80-912a-11ea-9d31-35bb66033323.png)

Does this issue occur when all extensions are disabled?: Yes

Is this intended behaviour or a bug? If it is intended, is there a workaround to show all markers?

**Comment by alexdima** [comment]
This number is currently hard coded [here](https://github.com/microsoft/vscode/blob/8f0f44cd0f718e9c2277758b400b7b34676d7bf6/src/vs/editor/common/services/markerDecorationsServiceImpl.ts#L143). This is intended behaviour. The idea is that if you have so many errors/warnings in a single file, it doesn't help to render another 1000 errors. This most likely indicates some kind of configuration problem and seeing thousands and thousands of errors is not really helpful, as it is highly unlikely that the errors will be tackled one-by-one, and even if they are, it is very likely they need to be tackled top-bottom.

**Comment by N8th8n8el** [comment]
Thanks for your detailed response.
I agree with the points you made and just wanted to make sure it is intended.
