### ISSUE TITLE
Cannot find node.js debug environment

### ISSUE THREAD

**Issue by matehc** [microsoft/vscode#97250]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I tried selecting the debug tool, however, when i click in the run debug, it doesn't show me a list of environment to choose for debugging. I my case, I need the node.js environment.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
auto-add-brackets|ali|0.11.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
prettier-vscode|esb|4.5.0
auto-close-tag|for|0.5.7
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.2
rest-client|hum|0.23.2
html-tag-wrapper|hwe|0.2.3
vscode-colorize|kam|0.8.16
auto-save|mcr|1.0.3
powershell|ms-|2020.4.0
open-html-in-browser|pea|2.1.2
material-icon-theme|PKi|4.1.0
LiveServer|rit|5.6.1
lorem-ipsum|Tyr|1.2.0
highlight-matching-tag|vin|0.9.9
better-align|wwm|1.1.6

</details>

**Comment by isidorn** [comment]
First open a javascript file. then it should show
