### ISSUE TITLE
How to unblock progress on vscode most liked issue 

### ISSUE THREAD

**Issue by LifeIsStrange** [microsoft/vscode#97252]
I was reading [the vscode 2020 roadmap](https://github.com/microsoft/vscode/wiki/Roadmap), in it you say you are working on 

> Workbench layout
Support for detachable workbench parts is our most upvoted feature request which due to architectural issues is challenging to implement. 

I have not read most comments of the thread https://github.com/Microsoft/vscode/issues/10121
But from what I understand the difficulty involve a lack of API in electron for multi screen window placement (among maybe other things). 
Not everybody is like me a chromium nerd. 
Rejoice yourself, I don't know how much it will unblock the most liked vscode issue but chromium 80 (current stable chromium is 81) brought [a window placement API tailor made for multi screen! ](https://www.chromestatus.com/feature/5252960583942144), you should probably consider it.
And Electron 8.2.4 is stable and use chromium 80. 
So fixing this issue should be prioritarised https://github.com/microsoft/vscode/issues/94074

To what extent this API will resolve the original issue is a matter of your expertise.

**Comment by Tyriar** [comment]
We're working on it, you can see progress as part of the flexible layout work that's been happening. Also Electron has new APIs coming that allow direct window-to-window communication that should also help with this.

/duplicate
