### ISSUE TITLE
Enhancement: option for smartSelect to ignore subwords

### ISSUE THREAD

**Issue by kamenminkov** [microsoft/vscode#97257]
Consider the following TypeScript snippet:

```TypeScript
class Person {
	private age: number;
	private firstName: string;
	private lastName: string;
}
```

Place multiple cursors like so (`|` denoting a cursor without a selection) and execute Expand Selection (`editor.action.smartSelect.grow`):
```TypeScript
class Person {
	private |age: number;
	private |firstName: string;
	private |lastName: string;
}
```
The result as of now is the following (`[` and `]` denoting selection) - Expand Select respects subwords in camelCase words:
```TypeScript
class Person {
	private [age]: number;
	private [first]Name: string;
	private [last]Name: string;
}
```
At this point, if you execute Expand Selection again, the following thing happens (again using square brackets to denote selection):

```TypeScript
class Person {
	[private age: number;]
	private [firstName]: string;
	private [lastName]: string;
}
```

What I'm suggesting is the following: a setting, say `editor.smartSelect.ignoreSubwords`, which, if set to `true`, will alter Expand Selection so that triggering it **once** from the same initial state will result in the following:

```TypeScript
class Person {
	private [age]: number;
	private [firstName]: string;
	private [lastName]: string;
}
```

The example applies to the normal use of one cursor too (and so should the suggested setting), but selecting multiple varied terms (including words with and without subwords) illustrates even better why it might be useful.

**Comment by hihihlo** [comment]
or just add a new command (e.g. editor.action.smartSelect.grow_NoCase).

many people need copy **variable name** or **function name** in source code (in VsCode), 
and find it in log file (in text editor),
both name (var/func) just need *_*whole name_** rather than camelCase *_*part of name_** !

please consider the suggestion, thanks !

**Comment by jrieken** [comment]
To verify

* make sure the `editor.smartSelect.selectSubwords` setting exists
* make sure it is properly documented
* make sure it does works as promised

**Comment by kamenminkov** [comment]
Wow, that's awesome! Glad to finally see it implemented and after a quick try I can confirm it's working as intended (latest insider build).
