### ISSUE TITLE
Color picker has a scrollbar

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#97254]
![image](https://user-images.githubusercontent.com/22350/81410352-da064580-9140-11ea-8761-ea4519a4e87f.png)

**Comment by rebornix** [comment]
The hover has a max height of 250px, which is higher than the color picker itself. The scrollbar appears when there are other hover info. It's not what we can avoid. It's arguable if we should increase the max height when the color picker is there but I doubt if it changes the experience noticeably.
