### ISSUE TITLE
无法打开源代码管理

### ISSUE THREAD

**Issue by chenrui2014** [microsoft/vscode#97268]
Issue Type: <b>Bug</b>

项目是从github上拉下来的，但是用vscode打开后，在源代码管理菜单中显示当前打开的文件夹没有git存储库，打开的文件夹实际存在.git文件夹

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:10:24.511Z)
OS version: Linux x64 4.15.0-97-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3365)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.51GB (11.64GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.23.5
project-manager|ale|10.12.0
jest-snippets|and|1.8.0
vscode-django|bat|0.20.0
simple-react-snippets|bur|1.2.2
gitignore|cod|0.6.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.35.1
jshint|dba|0.10.21
vscode-eslint|dba|2.1.5
lua-debug|dev|1.1.1
react-redux-react-router-snippets|dis|0.4.29
git-extension-pack|don|0.1.3
githistory|don|0.6.5
python-extension-pack|don|1.6.0
es7-react-js-snippets|dsz|2.7.1
vscode-babel-coloring|dza|0.0.4
gitlens|eam|10.2.1
prettier-vscode|esb|4.5.0
vscode-firefox-debug|fir|2.7.2
vscode-jest-runner|fir|0.4.17
docker-explorer|for|0.1.7
docker-extension-pack|for|0.0.1
vscode-pull-request-github|Git|0.16.0
vscode-mocha-test-adapter|hbe|2.3.0
vscode-test-explorer|hbe|2.18.0
beautify|Hoo|1.5.0
vscode-react-typescript|inf|1.3.1
kubernetes-snippets|ipe|0.1.9
webpack|jer|2.2.0
svg|joc|1.1.8
vscode-rust|kal|0.4.2
Lua|key|0.0.9
vscode-github|Kni|0.30.3
MagicPython|mag|1.1.0
rust-analyzer|mat|0.2.159
vscode-language-babel|mgm|0.0.27
git-graph|mhu|1.22.0
vscode-docker|ms-|1.1.0
vscode-language-pack-zh-hans|MS-|1.45.1
vscode-kubernetes-tools|ms-|1.2.0
python|ms-|2020.4.76186
cpptools|ms-|0.27.1
Go|ms-|0.14.1
js-debug-nightly|ms-|2020.5.617
vscode-typescript-next|ms-|4.0.20200507
debugger-for-chrome|msj|4.12.6
vscode-react-native|msj|0.15.0
vscode-jest|Ort|3.2.0
material-icon-theme|PKi|4.1.0
vscode-graphql|Pri|0.2.14
vscode-yaml|red|0.7.2
rust|rus|0.7.5
git-merger|sha|0.4.1
markdown-preview-enhanced|shd|0.5.3
js-jsx-snippets|sky|10.1.0
lua|sum|0.16.3
vscode-helm|tec|0.4.0
python|tht|0.2.3
vscode-lua|tri|0.12.4
vscodeintellicode|Vis|1.2.7
vscode-icons|vsc|10.1.1
jinja|who|0.0.8
vscode-go-autotest|win|1.6.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|2.8.0
vsc-docker|Zim|0.34.0
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by alexdima** [comment]
Closing after >7 days without an answer.
