### ISSUE TITLE
Git - Make "Publish To GitHub" option available for Initialised Git Repo

### ISSUE THREAD

**Issue by snerks** [microsoft/vscode#97264]
The `Publish To GitHub` option appears to be available only when a folder has not yet been initialised with Git.

It would be good if the `Publish to GitHub` option were available for a local Git Repository that has not yet been Published to GitHub. This feature is available in GitHub Desktop (on Windows).

**Comment by joaomoreno** [comment]
Still a work in progress: https://github.com/microsoft/vscode-pull-request-github/issues/1664
