### ISSUE TITLE
Unable to authenticate with GitHub

### ISSUE THREAD

**Issue by ahinkle** [microsoft/vscode#97261]
- VSCode Version: 1.45.0
- OS Version: MacOS Catalina 10.15.4

Steps to Reproduce:

1. Update to 1.45.0 (from latest 1.44)
2. Open an existing project
3. Open GitHub issues pane in Explorer
4. Displays the following error:
```
{"message":"Validation Failed","errors":[{"message":"The listed users cannot be searched either because the users do not exist or you do not have permission to view the users.","resource":"Search","field":"q","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/search/"}
```

I don't see a way to login to GitHub in the editor (including settings). How can I authenticate?

![Screen Shot 2020-05-08 at 9 30 01 AM](https://user-images.githubusercontent.com/17038330/81416758-ca223d80-910f-11ea-8020-b758e340978e.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
@ahinkle Just to confirm, is this view from the "GitHub Issues" extension?

**Comment by ahinkle** [comment]
ah- my mistake. Confused a different extension during the install.
