### ISSUE TITLE
terminal.integrated.commandsToSkipShell > Find Disabling Not Working in April 2020 Update

### ISSUE THREAD

**Issue by mscott5861** [microsoft/vscode#97262]
- VSCode Version: April 2020
- OS Version: Windows 10

Steps to Reproduce:

1. In `settings.json`, set `"terminal.integrated.commandsToSkipShell": [
  "-workbench.action.terminal.focusFindWidget"
]`

I use this setting to avoid sending <Ctrl + F> to the integrated terminal, as it's used for autocomplete in Fish shell and is indispensable to my workflow. This setting in `settings.json` has worked for as long as I've used VS Code, though I can't find any documentation of it being removed in the April 2020 update. I disabled auto-updates as a result and rolled back to the March 2020 update, where it continues to function as normal.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
The command name changed, update to this:

```
"terminal.integrated.commandsToSkipShell": [ "-workbench.action.terminal.focusFind" ]
```
