### ISSUE TITLE
New Switch tabs using mouse wheel is too fast

### ISSUE THREAD

**Issue by garyshell** [microsoft/vscode#97265]
Issue Type: <b>Bug</b>

On a Mac using the Mac "Magic Mouse" the tab switching is too fast.  With three tabs open it switches instantly between the leftmost and righmost tabs.  It is impossible to move to the one in the middle.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (3.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.29
githistory|don|0.6.5
plsql-language|xyz|1.8.2

</details>

**Comment by bpasero** [comment]
Happy for help in https://github.com/microsoft/vscode/issues/96409

/duplicate

**Comment by garyshell** [comment]
@bpasero this is not really a duplicate.  I read thru the #13902 issue and saw no mention of the scroll SPEED. The problem I have is that the new feature scrolls too fast.

**Comment by garyshell** [comment]
@bpasero Oh wait,  I see you referenced a second issue and that one does indeed address my issue.
