### ISSUE TITLE
Quick-fix import adding `.js` extension to TypeScript import.

### ISSUE THREAD

**Issue by itsjamie** [microsoft/vscode#97260]
When using the quick-fix to automatically add import statements to a project that is a mix of Typescript and Javascript, the automatic import is adding `.js` extensions to the file import path, when the file that it is pointing at is written in TypeScript, and ends with a `.ts` extension.

- VSCode Version: 1.45.0
- OS Version: 10.15.4

Steps to Reproduce:

I haven't been able to successfully create a simple reproduction of this issue. Hoping someone may have some idea of why it's happening.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?
