### ISSUE TITLE
Search file on file_list

### ISSUE THREAD

**Issue by devjavivazz** [microsoft/vscode#97278]
<b>Please Add Feature Request</b>

On Explorer "left container" (file list) add "filter files"
home.html
contact.html
another...
another...
another...
...

If I want search home.html file, then ...
**Search:** hom...

_(result...)_
home.html
home.php
...
...

VS Code version: Code 1.45.0

**Comment by devjavivazz** [comment]
![image](https://user-images.githubusercontent.com/1087216/81428312-b8499600-9121-11ea-8ea2-dcebae228ef1.png)

**Comment by joaomoreno** [comment]
@devjavivazz Have you tried just typing?

https://code.visualstudio.com/docs/getstarted/userinterface#_filtering-the-document-tree

**Comment by devjavivazz** [comment]
Thanks João!


__________________________________________________________________________________

Advertencia: La información del presente correo es confidencial y exclusiva
de la persona y de la institución a la que hace referencia. Si usted no es
el destinatario, el uso total o parcial, la distribución, copia, uso, o
cualquier otra acción relacionada, puede ser ilegal y está prohibida. Por
favor notifique al remitente inmediatamente y elimine este mensaje de
cualquier computadora. En caso de que exista una copia impresa, destrúyala.

Disclaimer: The information in this email is confidential and exclusively
for the person or institution to which it refers. If you are not the
intended recipient of this message, any full or partial distribution,
disclosure, copying, use or any other relative action of the same kind is
prohibited and may be unlawful. Please notify the sender and immediately
and permanently delete this message from any computer in which it resides
and in case of existing, destroy any copy printed out.
