### ISSUE TITLE
Terminal process terminated with exit code : 4294967295

### ISSUE THREAD

**Issue by sknazimuddin** [microsoft/vscode#97277]
- VSCode Version: 1.45.0(user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. New Terminal
2. The Terminal process terminated with exit code : 4294967295

Does this issue occur when all extensions are disabled?: Yes/No

 I can't run Python without the python extension.

**Comment by Tyriar** [comment]
Do you have anti-virus software that could be blocking the terminal? If so try following the instructions in https://code.visualstudio.com/docs/editor/integrated-terminal#_how-do-i-fix-the-errors-connectnamedpipe-failed-windows-error-232-or-terminal-exited-with-code-x-on-windows

/label "needs more info" integrated-terminal
