### ISSUE TITLE
"Open with..." on explorer does not work

### ISSUE THREAD

**Issue by caponetto** [microsoft/vscode#97271]
```
Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:10:24.511Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.6.10-300.fc32.x86_64 snap
```

Steps to Reproduce:

1. Open a folder that has some text files;
2. Right click on any text file and choose "Open with...";
3. Select "Text Editor - Built-in".

**Expected behavio**r: the file is opened.
**Current behavior**: nothing happens.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
The bug is that `open with` should not be shown at all in these cases

**Comment by caponetto** [comment]
Hi @mjbvz
I opened this issue because "_Open with... Text Editor_" does not work for the custom editor that I'm working on. I can only manage to open the text version of the file if use "_Reopen with... Text Editor_".
The steps to reproduce with text files that I mentioned was just a simpler way to raise this issue.

Now I see, on the insiders build, that "_Open with..._" is not available anymore for text files due to your fix, but it still there for custom editors and does not work. Should I open a new issue?
