### ISSUE TITLE
pulldown menus all flash white

### ISSUE THREAD

**Issue by lucky-wolf** [microsoft/vscode#97270]
Issue Type: <b>Bug</b>

Create a VBox VM for...
Install Linux Mint 19.3 w/ Cinnamon
Install VSCode - Insiders Edition
Choose a dark theme in VSCode (the default is fine)
As you pull-down menus from the top menu-bar, they all draw first in bright white, then overlay the dark theme - making them flash.

NOTE: this occurs whether I use the default display settings, or I agree to use the DOM model.

VS Code version: Code - Insiders 1.46.0-insider (d487078dc7fc1c276657cadb61b4f63833a8df55, 2020-05-07T16:36:39.681Z)
OS version: Linux x64 5.3.0-51-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (8 x 3700)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 0|
|Memory (System)|7.77GB (0.24GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-markdownlint|Dav|0.35.1
jshint|dba|0.10.21
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
gitlens|eam|10.2.1
vscode-pull-request-github|Git|0.16.0
vscode-edit-csv|jan|0.2.7
rainbow-csv|mec|1.7.0
python|ms-|2020.4.76186
cpptools|ms-|0.27.1
Go|ms-|0.14.1
scala|sca|0.3.9

</details>

**Comment by charbelnicolas** [comment]
This has already been fixed in an recent exploration build, who knows when, or if they will ever backport the fix. Maybe in a year or so when they decide to upgrade to the newest or more recent builds of electron and chrome , maybe then we will see a fix.

**Comment by deepak1556** [comment]
@lucky-wolf can you verify if the issue happens with the exploration build https://az764295.vo.msecnd.net/exploration/7faa10cfc640a15751049cdc6e894c5d146ff7dd/code-exploration-1588920827.tar.gz ? Thanks!

**Comment by lucky-wolf** [comment]
Thanks, I check it out and leave a response tomorrow.

**Comment by TDL3** [comment]
> @lucky-wolf can you verify if the issue happens with the exploration build https://az764295.vo.msecnd.net/exploration/7faa10cfc640a15751049cdc6e894c5d146ff7dd/code-exploration-1588920827.tar.gz ? Thanks!

I can confirm on manjaro 20.0.3 gnome edition this issue is fixed

**Comment by charbelnicolas** [comment]
When is the stable build with the fix coming out?

**Comment by lucky-wolf** [comment]
Hi this appears to be fixed.  I had given up on it - but the bot reminded me to look - and sure enough - it appears to be fixed!

Version: 1.49.0-insider
Commit: e4256dd1a02339bb1d56647ecd9134bf38bc7c03
Date: 2020-09-04T18:45:03.783Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-45-generic snap

Thanks!

**Comment by bkramer-moz** [comment]
I'm getting white flash bug from today's upgrade of VSCode.  I could really use a fix... it's pretty eye jarring.
