### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by andm13** [microsoft/vscode#97284]
I recently tried to save a file and i dont have permisions to save it. I ran visual studio as an admin and i still get the error. I can make changes in notepad or other IDE.

**Comment by haroldao** [comment]
what was your issue message?

**Comment by andm13** [comment]
I get unable to save because of permission but if I check the files I have
all the permissions.

**Comment by haroldao** [comment]
did you search your issue on StackOverflow?

**Comment by andm13** [comment]
I did but could not find a solution. But installing the program again and
restarting my pc worked.
