### ISSUE TITLE
Command + C not working

### ISSUE THREAD

**Issue by vimson** [microsoft/vscode#97288]
Issue Type: <b>Bug</b>

Dear Team,

After an update in Mac OS Catalina, Command + C is not working. Even if i select a text the context menu not showing any command there.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (2.91GB free)|
|Process Argv|-psn_0_544901|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
live-html-previewer|hdg|0.3.0
theme-monokai-pro-vscode|mon|1.1.15
LiveServer|rit|5.6.1

</details>

**Comment by Tyriar** [comment]
Can you put a [gif](https://gifcap.dev/) together after enabling screencast mode (F1 > screencast) showing the problem?
