### ISSUE TITLE
"editorLineNumber.activeForeground" Not Highlighting the Current Line

### ISSUE THREAD

**Issue by Arpitx** [microsoft/vscode#97292]
**- VSCode Version:** 1.45.0
**- OS Version:** Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Copy and paste the line "editorLineNumber.activeForeground" with a color code assigned to the same
2. After successfully performing step 1, if a user tries to write code, the active line number is not highlighted. A file has been attached for reference.

Does this issue occur when all extensions are disabled?: Yes
[LineNumberHighlightBug.zip](https://github.com/microsoft/vscode/files/4601023/LineNumberHighlightBug.zip)

Thanks

**Comment by rebornix** [comment]
`"editor.renderLineHighlight"` should be set to  `"all"` or `"gutter"`.
