### ISSUE TITLE
Translation for Context Menu on Windows

### ISSUE THREAD

**Issue by Hitnnan** [microsoft/vscode#97293]
Well, even if I install the Portuguese Brazilian pack, when I right-click on any program or on Desktop, appears the line that says "Open with Code".
I just need that line translated, because is very odd my system that is in Portuguese, with this line in English.
That line should looks like: "Abra com VS Code", or "Abra com  Code". The first one is better, I think.
Thank you!
[https://imgur.com/gallery/DIOFzrp](url)

**Comment by joaomoreno** [comment]
This is actually already done: https://github.com/microsoft/vscode/blob/master/build/win32/i18n/messages.pt-br.isl#L9

But you would have to have selected Brazilian Portuguese at the time of installation.

**Comment by Hitnnan** [comment]
Opa, mas pera lá. Quando eu vou instalar não existe opção de PT-BR, o que
devo fazer? Baixei a última versão no site oficial.

Em seg., 11 de mai. de 2020 às 08:35, João Moreno <notifications@github.com>
escreveu:
