### ISSUE TITLE
VSCode engine version != vscode version?

### ISSUE THREAD

**Issue by CoenraadS** [microsoft/vscode#97295]
- VSCode Version: 1.45.0
- OS Version: Windows 10

Steps to Reproduce:

I have an extension that broke between 1.44.0 and 1.45.0

So I made an update, setting the vscode version to 
`
"engines": {
        "vscode": "^1.45.0"
    },
`

However after publishing, vscode 1.45.0 would not find an update.
Now I downgraded the engine version to 1.44.0 and the update is found

**Comment by alexdima** [comment]
I think this is about the extension viewlet / marketplace not finding a good update.

**Comment by sandy081** [comment]
Can you please provide us the extension to reproduce this?

**Comment by CoenraadS** [comment]
https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2

I published 0.1.3 which targets `"vscode": "^1.45.0"` however this update is not found inside vscode.

**Comment by CoenraadS** [comment]
After uninstalled 0.1.2 now 0.1.3 is found.. no idea but I guess it's fixed?
