### ISSUE TITLE
Add Cancel or Clouse button to input box triggered by Extensions

### ISSUE THREAD

**Issue by wbpluto** [microsoft/vscode#97297]
At present, the parameter input box popped up by Extensions can only be closed by keyboard ESC. I hope to provide a visual button in order to improve the accessibility of the interface.

![image](https://user-images.githubusercontent.com/5191513/81444130-3735e180-91a9-11ea-8c45-1d45429dc9dd.png)
![image](https://user-images.githubusercontent.com/5191513/81444141-3ac96880-91a9-11ea-9429-af5285b8c9a4.png)

**Comment by gjsjohnmurray** [comment]
See also #75186, which was closed as a dup (dubiously IMO).

**Comment by misolori** [comment]
> can only be closed by keyboard ESC

You can also click anywhere outside of the quick pick and it will close it. The same applies to all of our context menu and top level menus. This should be much faster than navigating to a close button. 

Given that #75186 was open for a few months without any upvotes I'm going to close this as `as-designed`
