### ISSUE TITLE
Find widget hover feedback is inconsistent

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#97299]
![image](https://user-images.githubusercontent.com/2193314/81444933-dd8fd180-912c-11ea-9a01-d7c94dcb8f78.png)
![image](https://user-images.githubusercontent.com/2193314/81444949-e7193980-912c-11ea-96f6-2a613cbca5a9.png)

Most buttons in the UI don't have any hover feedback, including find in terminal.

**Comment by misolori** [comment]
This is coming from here:

https://github.com/microsoft/vscode/blob/d996bb1d285c80dbf262526553d90e414243d63b/src/vs/editor/contrib/find/findWidget.css#L129-L131

FYI @aeschli since it looks you were the last one to edit that line

**Comment by misolori** [comment]
I've removed the background hover feedback on the find widget arrows, find in selection, and close. Verifier should make sure to check all find widgets (search, editor search, terminal, etc.).
