### ISSUE TITLE
Cannot add folder to workspace

### ISSUE THREAD

**Issue by AGiantSquid** [microsoft/vscode#97294]
Issue Type: <b>Bug</b>

- Click "File" > "Add Folder to Workspace..."
- Select folder I wish to add in pop-up
- Nothing Happens

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (8.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|Memory (System)|15.82GB (8.70GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|mau|1.4.0
python|ms-|2020.4.76186
remote-containers|ms-|0.117.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0

</details>

**Comment by AGiantSquid** [comment]
![add-folder-not-working](https://user-images.githubusercontent.com/26531374/81442448-7839e180-9128-11ea-8e61-11ffe620092c.gif)

**Comment by bpasero** [comment]
I cannot reproduce when I try with WSL, but something to note is that the paths in the folder picker seems weird, they almost look like windows paths but with slashes. I am not sure about this setup, for me paths show up as unix paths.

**Comment by aeschli** [comment]
@AGiantSquid How come you have the `/c/Users/...` folder. Did you create a symlink or change the wsl config? 

Can you check if there's anything in the logs? (Output > Log...)

**Comment by xgfone** [comment]
@bpasero @aeschli I met with the trouble like @AGiantSquid. It is OK before updating VSCode to 1.45.0.

**Comment by csams** [comment]
I'm running Fedora 31, code version 1.45.1-1589445456.el7.  All of File -> _Open File_, _Open Folder_, _Open Workspace_, and _Add Folder to Workspace_ present a dialog that's completely unresponsive (I can't even drag it) other than the Cancel button. I don't see anything in any of the logs.

**Comment by SirDavidLudwig** [comment]
I ran into this issue today using 1.45.1.

From what I found, it will not let you add a folder if you what you have opened *is* a folder, it must be a workspace. The current workaround/solution is to open one of the folders like you normally would (open folder/add folder to workspace, either works), then save the current workspace. Once VS code refreshes, you can then add more folders to the workspace without issue.

**Comment by bpasero** [comment]
@SirDavidLudwig can you describe the exact steps from 0 to issue how to reproduce? is this WSL1 or 2?

**Comment by SirDavidLudwig** [comment]
@bpasero Sure.

I am using WSL 1 and VS Code v1.45.1 with only the WSL (v0.44.2) extension installed. This is one of possible multiple ways to reproduce the issue.

1. From a fresh VS Code session with no files/workspaces open, connect to WSL by either clicking the icon in the bottom-left corner, or through the Ctrl+Shift+P Command menu (>Remote-WSL: New Window)
2. When the new window is ready, open a new folder through `File -> Add Folder to Workspace...`. This folder should open just fine.
3. Add another folder through `File -> Add Folder to Workspace...`, in this case nothing happens for me/us.

Note: I found that if you add the first folder by clicking the big `Open Folder` button in the explorer panel this issue doesn't occur.

**Comment by bpasero** [comment]
This is due the following line:

https://github.com/microsoft/vscode/blob/88ae7a43871d9bda8c2cc1951be8857935cab30e/src/vs/workbench/services/workspaces/browser/abstractWorkspaceEditingService.ts#L134

As you can see from debugging, the remote authority casing differs:

![image](https://user-images.githubusercontent.com/900690/82746600-f2f23600-9d91-11ea-9713-451004ff4816.png)

**Comment by xgfone** [comment]
@bpasero Yes, you're right! After I had modified my configuration file `wsl.code-workspace` from `"remoteAuthority": "wsl+Ubuntu-18.04"` to `"remoteAuthority": "wsl+ubuntu-18.04"`, it works again.

But I did nothing about `wsl.code-workspace` before upgrading the vscode from `1.44.0` to `1.45.0`. After upgrading it, however, it didn't work. From `1.44.0` to `1.45.0`, what happened about WSL workspace?

**Comment by aeschli** [comment]
@bpasero Thanks for tracking that down. If only @isidorn had copy/pasted my suggestion from https://github.com/microsoft/vscode/issues/94191#issuecomment-608285021 :-)

**Comment by bpasero** [comment]
@aeschli oh yeah true :)

**Comment by isidorn** [comment]
Oh my! Sorry for that. I should have just copied.
