### ISSUE TITLE
Option to sign up commit apparently is not working

### ISSUE THREAD

**Issue by morbec** [microsoft/vscode#97300]
- VSCode Version:  1.45.0
- OS Version: macOS Catalina 10.15.4

Steps to Reproduce:

1. Set up VS Code to sign commits: `"git.enableCommitSigning": true`
2. Try to commit 

Does this issue occur when all extensions are disabled?: Yes

[vscode-git.log](https://github.com/microsoft/vscode/files/4601415/vscode-git.log)

**Comment by joaomoreno** [comment]
The only thing this will do is add `-S` when calling `git commit`, so you should [setup git to be able to sign your commits](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work).

**Comment by morbec** [comment]
Hi @joaomoreno 

Thanks for your comment but I already have git set up to sign commits and it works as expect in the terminal but when I try to commit via VS Code nothing happens, I expected to have a place (popup for example) where  I could type my passphrase as in the terminal but I can't type my passphrase anywhere.

**Comment by joaomoreno** [comment]
Got it, that's https://github.com/microsoft/vscode/issues/43809
