### ISSUE TITLE
Launch program "C:\Users\my_user\workspace" does not exist.................except it actually does.

### ISSUE THREAD

**Issue by LightningRpper** [microsoft/vscode#97305]
When running code in VS Code, I'm getting an error saying that the workspace folder does not exist, when in fact it does. What's going on here?

![cide](https://user-images.githubusercontent.com/54909296/81450718-931c4e00-9148-11ea-9ccf-beb0fc17d6db.PNG)

**Comment by mjcrouch** [comment]
presumably "program" should be the full path to the executable file insdie the folder, not just the name of a folder - I would guess that's why it complains...

**Comment by alexr00** [comment]
@mjcrouch is correct. A folder is not an executable.
