### ISSUE TITLE
Debt: use ipc to communicate with the auth dialog

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#97301]
Follow-up to https://github.com/microsoft/vscode/issues/97199 , since `executeJavaScript` calls are hard to debug and they are just inline script evaluation that can easily break CSP.

1) We should change `BrowserWindowConstructorOptions` for the auth window

**from**

```
const opts: BrowserWindowConstructorOptions = {
			alwaysOnTop: true,
			skipTaskbar: true,
			resizable: false,
			width: 450,
			height: 220,
			show: true,
			title: 'VS Code',
			webPreferences: {
				nodeIntegration: true,
				webviewTag: true
			}
		};
```

**to**

```
const opts: BrowserWindowConstructorOptions = {
	alwaysOnTop: true,
	skipTaskbar: true,
	resizable: false,
	width: 450,
	height: 220,
	show: true,
	title: localize('authRequire', "Proxy Authentication Required"),
	webPreferences: {
	      sandbox: true,
               contextIsolation: true,
               preload: require.toUrl('vs/code/electron-browser/proxy/auth-preload.js')
	}
};
```

2) Setup ipc channel in the preload script

3) Replace `executeJavaScript` call in `vs/code/electron-main/auth.ts` with `win.webContents.send`

This will align well with https://github.com/microsoft/vscode/issues/92164 

/cc @bpasero once you setup a structure for how preload communication should look, we can adopt it here.

**Comment by Ejgwg0629** [comment]
Could you please change the `opts.height` to some number bigger by the way, maybe 320? 
I can hardly find the `submit` button in our case..

**Comment by bpasero** [comment]
As discussed, the auth dialog should use `IMainProcessService` and channels to communicate with the main side. A good place to learn from is our issue reporter window.

**Comment by joaomoreno** [comment]
Let's do this on debt week.

**Comment by joaomoreno** [comment]
Pushing out, no rush here.

**Comment by deepak1556** [comment]
thanks @joaomoreno
