### ISSUE TITLE
Recognize more shell script files

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#97313]
Let's expand the file patterns recognized as POSIZy shell scripts:

* Files with ash, dash, posh, yash shebangs
* zsh core configuration files (`zshrc`, `.zshrc`, `*.zshrc`, `zshenv`, `.zshenv`, `*.zshenv`, `zlogin`, `.zlogin`, `*.zlogin`, `zprofile`, `.zprofile`, `*.zprofile`, `zlogout`, `.zlogout`, `*.zlogout`)
* Slant rhyme filenames like `bashrc_Apple_Terminal`, `zshrc_Apple_Terminal`

This last one is going to trigger some false positives, but perhaps that is better than highlighting as TXT files.

**Comment by aeschli** [comment]
Also see  #95583.
PRs are welcome!

**Comment by aeschli** [comment]
Cool. Have a look here: https://github.com/microsoft/vscode/blob/master/extensions/shellscript/package.json#L14
