### ISSUE TITLE
"Open definition to the side" opens definition in the same group

### ISSUE THREAD

**Issue by tlemo** [microsoft/vscode#97317]
Issue Type: <b>Bug</b>

 "Open definition to the side" works... unless there are multiple definition candidates. In this case the disambiguation popup shows up, after which the definition is opened in the *current* group, rather than *to the side*

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:10:24.511Z)
OS version: Linux x64 4.15.0-99-generic

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.1.0
pascal-language-basics|Ans|0.1.8
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
shell-format|fox|7.0.1
html-preview-vscode|geo|0.2.5
vscode-graphviz|joa|0.0.6
language-haskell|jus|3.0.3
rainbow-csv|mec|1.7.0
python|ms-|2020.4.76186
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
cpptools|ms-|0.27.1
debugger-for-chrome|msj|4.12.6
LiveServer|rit|5.6.1
llvm|RRe|0.0.3
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.3
perforce|sle|3.2.0
graphviz-interactive-preview|tin|0.0.8
cmake|twx|0.0.17
vscode-lldb|vad|1.5.0
vscode-preview-server|yui|1.3.0

</details>

**Comment by jrieken** [comment]
> after which the definition is opened in the current group, rather than to the side

From there, you need to use command+click to open to the side. We don't seed the widget with an open-to-side-by-default mode because there is no visual indication for that. Also, command+click is always opening a location to the side.

**Comment by tlemo** [comment]
@jrieken : Thanks for looking into it, and the suggested workaround.

Wouldn't it make more sense to implicitly open to the side from the disambiguation widget if the lookup was initiated with "Open definition to the side"? Right now the behavior is inconsistent, frustrating (not to mention confusing) - "Open definition to the side" sometime opens to the side, sometime it doesn't.

I find this functionally (open to the side) very valuable and a key part of the development workflow. Is there any chance you'd reconsider and have the "open definition to the side" work consistently, regardless of disambiguation widget or not?

**Comment by tlemo** [comment]
FYI - the Ctrl(command)+click in the disambiguation widget is also slightly broken: #97542
