### ISSUE TITLE
[Configuration] Get configuration doesn't return default value if not found.

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#9731]
- VSCode Version: 1.4.0-Insider
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Add a new boolean option to contribution list of an extension
2. Run/debug the extension, try fetch the configure by `vscode.workspace.getConfiguration("section").get("optionName",  undefined)`

If user doesn't  set a value for this config in his/her settings.json, the return result of this expression should be `undefined`. While what we get is `false`.

If the config is defined as `number`, this expression will return `null`. If user sets this config explicitly, we can get the correct value.

BTW, it seems we don't have a chance to know whether a Code config, for example `editor.tabSize`, is set by User or Workspace or just default value. It's a potential feature request.

**Comment by jrieken** [comment]
@rebornix How did you define the configuration property? If the default is defined to be `false` that the behaviour is expected

**Comment by rebornix** [comment]
@jrieken the thing is I didn't define its default value. A good proof is when we define a Number type configuration and don't add default value for it, you always get `null`, it's not even a number.

**Comment by jrieken** [comment]
Understood. It seems like the value is set to `null` when not being defined which defeats [this](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostConfiguration.ts#L56) check.

@aeschli Did we change the default value when the definition doesn't contain a value?

**Comment by aeschli** [comment]
I'm not aware of any recent changes, but there's a bug that we are missing numbers [here] [here](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/configuration/common/model.ts#L234).
I'll fix this but IMO a default value should always be set in the default configuration settings.

**Comment by rebornix** [comment]
@aeschli Once you fix the the number default value, the second parameter `defaultValue` of  `vscode.workspace.getConfiguration("section").get("optionName", undefined)` no longer works as there is always a value in Code, right? Besides, I'd like to set default value for all configs while implementing extensions, but if I do that, I'll never know where the configuration is from. Seems we simply merged Code default config, Extension default config, User setting and Workspace setting.

The reason I want to know the source of the config is that we have overlap between Vim and Code configuration. For example, `vim.tabstop` is totally the same as `editor.tabSize` from Code. We want to know if user sets `vim.tabstop` explicitly, if so we use `vim.tabstop` otherwise we still use `editor.tabSize`. But a default value makes it impossible as we always get a value from `vim.tabstop` through API. What do you think or any advice?

**Comment by aeschli** [comment]
Ihe 'defaultValue' parameter in WorkspaceConfiguration.get is useful if the key doesn't exist at all (e.g. if you access settings of an extension that is not present). No change for existing configurations: we already had the default value; it was just wrong for 'number', as you found out.
At the moment we don't have any API that would tell you where an option is defined (default, user or workspace). We were planning on adding such an API. We have no issue yet, please file one and we plan it.

**Comment by jrieken** [comment]
@aeschli There is still an issue here in which the default for not having a default is `null` but the logic expects `undefined` for that.

**Comment by aeschli** [comment]
Looked at it with Joh, he ran again in the number case. Tried again, an all seems fine now.
