### ISSUE TITLE
Allow adding metadata to CellDisplayOutput

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#97316]
https://github.com/microsoft/vscode/issues/96433 tracks ability to add metadata to cells, & notebooks.
We also need the ability to add metadata to cell output as well.

Consider the following example:
* When rendering matplotlibs in Jupyter, the output contains additional metadata useful for rendering.
* E.g. if a png/svg is returned metadata can be returned in the output indicating whether a white/light background needs to be used.
* In such a case, a custom renderer for `image/png` or `image/svg+xml` will need access to this metadata to wrap the image with a white background container or the like.

@rebornix

**Comment by rebornix** [comment]
Re #93265 . We now support metadata (and also custom ones) in CellDisplayOutput.
