### ISSUE TITLE
Move cache folders to .cache on Linux platform

### ISSUE THREAD

**Issue by danielsouzat** [microsoft/vscode#97315]
All VSCode related storage seems to be inside '~/.config/Code\ - \OSS' or inside the project folder. And inside that folder we have some cache folders: 'blob_storage', 'Cache', 'CachedData', 'CachedExtensions', 'Code\ Cache', 'GPUCache'. If those folders can be safely deleted as apparently is wouldn't be better to have them inside '~/.cache/Code\ - \OSS'? It would make easier to backup code setting and extensions with a lot smaller size.

I'm using Manjaro. I don't know if it's a distro related thing.

**Comment by Tyriar** [comment]
Everything in there used, a lot of it is part of the Chromium user data directory though.

For backup you should check out the upcoming [settings sync feature](https://code.visualstudio.com/docs/editor/settings-sync) (insiders only atm).
