### ISSUE TITLE
QuickSuggestion does not desappear

### ISSUE THREAD

**Issue by BenderEviler** [microsoft/vscode#97312]
Issue Type: <b>Bug</b>

When i'm finished writting a word that the quick suggestion failed to guess, that suggestion remains on the screen. So, if a hit the 'enter', instead of going to the next line, it will unnecessarily accept the word, and i'll have to hit 'enter' again.
Steps to reproduce:
1 - create a new .txt file
2 - inside the file write "babe baby"
3 - insert some lines and try to write "babe", character by character
the suggestion will show the word "babe" until you finish the last character, and when you've already finished the entire word the suggestion will remain in the screen. Now, if you wanna go to the next line, you'll have to hit 'enter' twice, cause the first hit will accept the suggestion.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Tyriar** [comment]
You can use this setting to disable the feature in plain text:

```json
"[plaintext]": {
  "editor.quickSuggestions": false
}
```

I do the same in markdown as it drives me crazy for similar reasons, you can always hit ctrl+space to trigger it manually still though.

**Comment by BenderEviler** [comment]
I don't want to disable quick suggestions on txt files, I want it to work properly. This is a bug and it has to be fixed.
Besides, this bug happens not only on txt files, it happens in any kind of file.

**Comment by jrieken** [comment]
>  Now, if you wanna go to the next line, you'll have to hit 'enter' twice, cause the first hit will accept the suggestion.


Use the value `smart` for this setting `editor.acceptSuggestionOnEnter`

**Comment by BenderEviler** [comment]
jrieken, 
You solutions did not solved the problem.
The problem is not that I have to hit enter twice, that's a consequence of the problem.
The problem is, quick suggestion is not going away when it's supposed to.
If i've finished writting a word, that word should not still be available in the quick suggestion.
There are three easy steps that I described to reproduce the problem, I think you didn't even tried them and proceeded to close this issue, wrongly.

**Comment by BenderEviler** [comment]
> > Now, if you wanna go to the next line, you'll have to hit 'enter' twice, cause the first hit will accept the suggestion.
> 
> Use the value `smart` for this setting `editor.acceptSuggestionOnEnter`

That solved the problem.
Thanks!
