### ISSUE TITLE
Setting has an invalid type, expected "string"

### ISSUE THREAD

**Issue by s1nce** [microsoft/vscode#97318]
- VSCode Version: 1.45.0
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Change Font Weight to any value instead of "normal"
2. Then you will get this error
Setting has an invalid type, expected "string". Fix it in JSON.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/97192
