### ISSUE TITLE
Markdown preview - jump to precise source location in the .md document

### ISSUE THREAD

**Issue by pavel-a** [microsoft/vscode#97310]
Issue Type: <b>Feature Request</b>

Currently double click in preview jumps to unrelated location in the .md file (last edit location?)

Would be cool to jump from any place in preview to corresponding place in its source .md file.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

**Comment by mjbvz** [comment]
Can you please provide an example where it jumps to the wrong location?

**Comment by pavel-a** [comment]
Hi Matt
Very simple. I open a md file with several subheaders, like:

## Part 1
blah blah 1

## Part 2
blah blah 
.... etc


Then I open preview and double click on Part2 header or text below it.
Code immediately activates the .md document, but it does not navigate anywhere close to Part 2.

In the opposite direction this works fine: when I right click on .md tab title and select Preview, it navigates in the preview to the matching place in the .md.

My use case is this: I start reading in preview mode, if I want to make a change I need to quickly jump into the .md.

Thanks and best regards,
-- pavel

**Comment by mjbvz** [comment]
Works for me with a markdown preview to the side of the current document:

![May-11-2020 10-51-53](https://user-images.githubusercontent.com/12821956/81594397-ad873f00-9375-11ea-96ae-793a2fd6aab8.gif)
Are you using a preview to the side or opening it in the current editor group?

**Comment by pavel-a** [comment]
Thanks Matt, side-by-side is the key!
When I put the windows side by side it works for me too. Otherwise it does not.

-- pa
