### ISSUE TITLE
Quick Open and Quick Access view usability issues

### ISSUE THREAD

**Issue by texastoland** [microsoft/vscode#97327]
I'm not sure if this is a bug or feature request. I love the Quick Access view conceptually. But it only stays open for me while keeping control pressed and receives no filter input like the main file/line/symbol/command palette. The only navigation is by either <kbd>Q</kbd>/<kbd>⇧Q</kbd> again or the arrow keys with the other hand. Switching the shortcut to a function key at least keeps the view open to use the mouse.

I don't use the Quick Open tab switcher for the same reason. Although it requires fewer key strokes for the last editor (<kbd>⌃-</kbd> does the same thing without the pause) than the file picker your eyes have to scan the entire potentially scrolling list for similarly named files in no discernible order then tab until you reach it. At least the icons are helpful affordances applicable to Quick Access too.

My ideal solution would be for these to reuse the widget from the command palette. Perhaps it could be an alternate binding by adding <kbd>⌥</kbd> or something. I'd be happy to contribute to any solution.

- VSCode Version: Version: 1.46.0-insider
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. <kbd>⌃Q</kbd> (default binding)

Does this issue occur when all extensions are disabled?: **Yes**

Search Terms:

- <kbd>Quick Open</kbd> (label)
- <kbd>quickOpenView</kbd> (action)
- <kbd>Quick Access</kbd> (name)
- <kbd>viewQuickAccess</kbd> (file)

**Comment by bpasero** [comment]
@texastoland to clarify, you would like what `Cmd+P` gives your for quick open view? If you press `Cmd+P` and leave `Cmd` hold and press `P` you can navigate in the list and pick on release.

**Comment by texastoland** [comment]
I think you heard the opposite of what I attempted to convey. That's a quite unusable pattern. I gave a concrete use case with switching tabs to explain why. In short I want to be able to filter the quick access/quick open/tab switcher views like the command palette.

**Comment by bpasero** [comment]
> My ideal solution would be for these to reuse the widget from the command palette. 

I do not understand your "solution". They are all using the same "quick pick" widget underneath.

**Comment by texastoland** [comment]
I mean it doesn't stay open and can't be filtered for me and never has in the case of the tab switcher. I looked at the file but not in depth. I just made the assumption they were different widgets because of the difference in behavior.

**Comment by bpasero** [comment]
`Ctrl+Tab` and `Ctrl+Q` as you already figured out use the "quick navigation" modes where the input field is hidden. But there are other commands to get the "normal" mode, e.g. for editors:

```json
{
  "key": "Cmd+Tab",
  "command": "workbench.action.showEditorsInGroup"
}

{
  "key": "Ctrl+Q",
  "command": "workbench.action.openView"
}
```

**Comment by texastoland** [comment]
Wow you guys think of everything. One small feedback is the various quick navigation modes (file/line/symbol/workspace symbol/editor/view/command) are tricky to discover. A "master" navigation or menu item or even web page would be extra helpful. Thanks so much for the top!

**Comment by texastoland** [comment]
For anyone who stumble on it I found just adding shift key variations of the bindings helpful:

```json
  {
    "key": "ctrl+shift+q",
    "command": "workbench.action.openView"
  },
  {
    "key": "ctrl+shift+tab",
    "command": "workbench.action.showEditorsInGroup"
  },
```
