### ISSUE TITLE
Git has some problum in code indentation of Python

### ISSUE THREAD

**Issue by senayuki** [microsoft/vscode#97329]
- VSCode Version:1.45.0
- OS Version:Windows 10 1909

Steps to Reproduce:
1.Change code indentation
![image](https://user-images.githubusercontent.com/27473098/81466372-beb03e80-9203-11ea-8460-701bbd9fde73.png)
2.Use `Stage Selected Ranges`, then the change of code indentation was ignored.
![image](https://user-images.githubusercontent.com/27473098/81466390-f15a3700-9203-11ea-9e46-5de3093708ed.png)

I can only stage all change in this file. Sometimes when I revert a change, the indentation of the entire file becomes confusing.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Set this to show the diff in that case:

```
"diffEditor.ignoreTrimWhitespace": false
```
