### ISSUE TITLE
Read from stdin, wsl

### ISSUE THREAD

**Issue by rafee** [microsoft/vscode#97324]
- VSCode Version: 1.45.0 (Windows)
- OS Version: Ubuntu 20.04/WSL2

Feature from #6161

Steps to Reproduce:

1. `man curl | code -` on WSL2 Terminal
2. Temporary file created with blank content

Does this issue occur when all extensions are disabled?: Yes/No, Not checked, because this disables WSL extension as well and shows error.

**Comment by rafee** [comment]
I just checked. It works in PowerShell but doesn't work in WSL. Maybe it has something to do with vscode not being native installed.

**Comment by Axlyted** [comment]
got the same issue. is there a workaround? vim seems to handle it pretty well btw

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode/issues/99815
