### ISSUE TITLE
No internet connection under corporate proxy ( net::ERR_NO_SUPPORTED_PROXIES )

### ISSUE THREAD

**Issue by nascarsayan** [microsoft/vscode#97326]
- VSCode Version: 1.45.0 (April Release)
- OS Version: MacOS Catalina 10.15.4

Steps to Reproduce:

1. Using VSCode in a corporate environment with proxy
2. Set `http_proxy="http://<host>:<port>/"`, `https_proxy=$http_proxy` in the environment variables
3. In `settings.json`
   1. Don't set `"http.proxy"`
   2. Set `"http.proxyStrictSSL": false`
   3. Set `"http.proxySupport": "on"`

4. No internet connection inside vscode, for example, Extensions tab says "We cannot connect to the Extensions Marketplace at this time, please try again later".

5. Console Tab in Developer Tools logs : `Failed to load resource: net::ERR_NO_SUPPORTED_PROXIES`

Does this issue occur when all extensions are disabled?: Yes

PS: VSCode has been working fine in MacOS Catalina 10.15.4 before the 1.45.0 update. Also VSCode Insiders doesn't give this error and works fine.

**Comment by nascarsayan** [comment]
It seems setting in environment variables
`http_proxy="http://<host>:<port>/"` gives error but
`http_proxy="http://<host>:<port>"` doesn't.
OR in `settings.json`
`"http.proxy": "http://<host>:<port>/"` gives error but
`"http.proxy": "http://<host>:<port>"` doesn't.

The **proxy URL** isn't being parsed correctly IMO.

**Comment by dineiar** [comment]
Shouldn't this issue remain open as a bug report?

IMO this should be fixed.

**Comment by chrmarti** [comment]
/duplicate https://github.com/microsoft/vscode/issues/97885

This is fixed in VS Code Insiders.
