### ISSUE TITLE
Terminal attempts to do automatic github authentication even when disabled.

### ISSUE THREAD

**Issue by a-tiller** [microsoft/vscode#97320]
- VSCode Version: 1.45.0
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1.  add: `{
  "git.enabled": false,
  "git.terminalAuthentication": false,
  "git.githubAuthentication": false,
}`
to settings.json
2. git push from the integrated terminal

Does this issue occur when all extensions are disabled?: Yes

Error text: 

Missing or invalid credentials.
Error: connect ENOENT /run/user/1000/snap.code/vscode-git-0ebaf733d8.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1056:14) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'connect',
  address: '/run/user/1000/snap.code/vscode-git-0ebaf733d8.sock'
}

**Comment by Tyriar** [comment]
Did you restart the terminal after your disabled it?

**Comment by a-tiller** [comment]
Yes, I've both killed the terminal and restarted the VM. 

Not sure if this is helpful, but before I added the two new settings vscode was trying to handle the authentication even though I had `git.enabled: false` set (requesting username and password from the command palette). That's what sent me looking for the new settings in the first place.
