### ISSUE TITLE
Confusing documentation for "environment" in launch.json

### ISSUE THREAD

**Issue by jhasse** [Microsoft/vscode#9733]
- VSCode Version: 1.3.1 with C/C++ extension 0.7.1
- OS Version: Linux

Steps to Reproduce: Open launch.json and hover over "environment":
![bildschirmfoto zu 2016-07-26 09-14-41](https://cloud.githubusercontent.com/assets/80071/17129146/ad8f5b5c-5311-11e6-953c-d82ed8d6c60f.png)

I followed the example, but I'm getting `Incorrect type. Expected "array"`. This page https://code.visualstudio.com/docs/editor/debugging says I should use `"env"`, but I guess that's because it's for Node.js debugging and I'm trying to debug a C++ application?

**Comment by kieferrm** [comment]
I moved the issue to https://github.com/Microsoft/vscppsamples/issues/116. @jhasse pls subscribe there.

[Here is some information](https://code.visualstudio.com/docs/languages/cpp#_debugging) about C++ debugging, but I didn't see anything related to environment the than the empty array in the screenshot on the page

**Comment by jhasse** [comment]
Thanks :)
