### ISSUE TITLE
[panel] focus box on actions is cut off

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#9734]
Testing #9724.
Linux, Elementary OS Freya

- open a terminal
- enable tab-focus mode (<kbd>ctrl</kbd>/<kbd>cmd</kbd>+<kbd>m</kbd> default)
- tab through to the '+' action in the terminal

-> Focus box is cut off

![image](https://cloud.githubusercontent.com/assets/6461412/17129252/40a01c10-5312-11e6-959a-4a2a42d94992.png)

**Comment by Tyriar** [comment]
This is a generic issue is present on all panels.

**Comment by bpasero** [comment]
Does not happen in the viewlets though, moving to @isidorn
