### ISSUE TITLE
SmartCase search only works in some directories

### ISSUE THREAD

**Issue by DrDecane** [microsoft/vscode#97340]
Issue Type: <b>Bug</b>

1. set `"search.smartCase": true` in user settings
2. Case insensitive search now works just fine for some folders/directories, but does not work at all for others.

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (3.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-standardjs|che|1.3.0
bracket-pair-colorizer-2|Coe|0.1.1
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|4.5.0
macros|ged|1.2.1
color-highlight|nau|2.3.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.8.0
code-spell-checker-german|str|0.1.4

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Can you give some more details about what you see? Is there anything different about the directories?

For a case that doesn't work, please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by DrDecane** [comment]
That's the trace it gives me for both a working and not working case somehow. However, in the not working case it obviously does not find any word and does not go to the next match either

![trace](https://user-images.githubusercontent.com/49991315/81494986-2bcbde80-92ad-11ea-8995-0feb77d7c0d6.PNG)

**Comment by roblourens** [comment]
Are you sure that case sensitive search mode is not toggled on?

**Comment by DrDecane** [comment]
Absolutly. What would even be the point in setting smartCase to true but then toggle on case sensitive search?

**Comment by roblourens** [comment]
Well, I thought you might have done it by accident and in some themes it is not obvious. Does it consistently work/not work for a folder or does it work for some queries?

**Comment by DrDecane** [comment]
Double checked again, it's definitely off. It consistently does/doesn't work. At first I thought it might be due to different file types and/or languages used among the folders, but that does not seem to be the case.

**Comment by roblourens** [comment]
Sorry, I have no clue what's going on, it's a very simple feature 🤔 

You could check whether toggling case sensitive on and off and trying searches would fix it. Or try launching with `--user-data-dir=somefolder` and open the same folder, and see whether that's any different.

**Comment by DrDecane** [comment]
I set the setting back to its default value of false. Now the case insensitive search works just fine, if I toggle the case sensitive search mode off (which obviously is the correct behavior). Turning smartCase back to true without changing anything else and it clashes again. So maybe there is an interference with that maybe?

**Comment by roblourens** [comment]
I just have no idea. I feel like it's going to be something simple that I'm not thinking of. Are you up for debugging a little to figure it out? If so you can follow these steps:

- Help > Toggle Developer Tools
- Wait a few seconds for sourcemaps to load
- ctrl+p, find QueryBuilder.ts
- Find this method

![image](https://user-images.githubusercontent.com/323878/82161714-9f995880-9864-11ea-8ae0-4bbd008fd9d1.png)

- Step into containsUppercaseCharacter
- And the check is literally `target !== target.toLowerCase()`, it's very simple, but is apparently returning true here (or there is something else going on, like it thinks case sensitive mode is enabled)
