### ISSUE TITLE
Found a bug while copying and pasting the code

### ISSUE THREAD

**Issue by binay798** [microsoft/vscode#97345]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

At first i copied two lines of html code and i tried to paste those two lines of code in another two line of same file by using ( alt + left click ) on two different lines . But those copied codes didn't paste on the two different lines as i expected. I expected that both lines of code would be copied on two different lines but only first line of code was pasted on first line and second code was pasted on another second line where i wanted the code to be copied

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 5.3.0-51-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 1442)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|3.78GB (0.13GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.4.76186
cpptools|ms-|0.27.1
material-icon-theme|PKi|4.1.0
LiveServer|rit|5.6.1

</details>

![first](https://user-images.githubusercontent.com/61418155/81473167-73565a00-921c-11ea-88c4-5406fcdf7da5.png)

![second](https://user-images.githubusercontent.com/61418155/81473165-72252d00-921c-11ea-8b6b-839d60abe89a.png)

![third](https://user-images.githubusercontent.com/61418155/81473160-6df90f80-921c-11ea-92ab-810f088eb3f1.png)

**Comment by jeanp413** [comment]
@binay798 I think you are looking for this setting `"editor.multiCursorPaste": "full"`. By default it's set to `"spread"`
