### ISSUE TITLE
Export a class decorated with decorators, which cannot be automatically imported in other files

### ISSUE THREAD

**Issue by zhydn** [microsoft/vscode#97346]
- VSCode Version:1.45
- OS Version: win10 1909

Steps to Reproduce:

1. Export a class decorated with decorators, which cannot be automatically imported in other files
2. 
  ```js
import { Column, Entity } from 'typeorm';
import Base from './Base';

export default 
@Entity()
class Order extends Base {
  @Column('varchar', {
    nullable: true
  })
  name = '';
}import { Column, Entity } from 'typeorm';
import Base from './Base';

export default 
@Entity()
class Order extends Base {
  @Column('varchar', {
    nullable: true
  })
  name = '';
}
```
3.  ![Snipaste_2020-05-09_20-13-28](https://user-images.githubusercontent.com/43907589/81473522-950e0c00-9231-11ea-9b62-76ee91d1ec21.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share a complete, self-contained code example. The current one doesn't make much sense  to me

**Comment by zhydn** [comment]
case1 
![Snipaste_2020-05-12_13-05-35](https://user-images.githubusercontent.com/43907589/81640715-da108900-9451-11ea-9944-1a157f1f7710.png)

case2 
![Snipaste_2020-05-12_13-09-00](https://user-images.githubusercontent.com/43907589/81640795-10e69f00-9452-11ea-94d4-36f389316f92.png)

case3 
![Snipaste_2020-05-12_13-06-22](https://user-images.githubusercontent.com/43907589/81640822-222fab80-9452-11ea-89dd-b1d48ff12f7c.png)

Use the decorator and export the class like case1 and case2. When importing this class in other files, you can see the path and automatically import the import statement, but the usage in case3 does not

**Comment by mjbvz** [comment]
I'm not sure the is a valid context for decorators. For the code:

```ts
function Bar(x) { return x; }

export default @Bar() class X { }
```

I see the following syntax error in VS Code insiders:

<img width="922" alt="Screen Shot 2020-06-01 at 8 41 41 PM" src="https://user-images.githubusercontent.com/12821956/83477532-4d515d80-a448-11ea-993e-e0e4b7aa1c20.png">

@zhydn Do you also see this error reported? Have you disabled JavaScript validation?

**Comment by zhydn** [comment]
I have disabled JavaScript validation

**Comment by zhydn** [comment]
And Eslint tips:  Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead.

**Comment by mjbvz** [comment]
The issue is that we don't support this syntax. You can suppress the errors but our tooling still does not understand this code so it cannot provide proper tooling support

Please file an issue against the TypeScript project if you think the syntax errors themselves are incorrect
