### ISSUE TITLE
Can't install extension

### ISSUE THREAD

**Issue by bashgaa** [microsoft/vscode#97350]
When i install extension from browser 
 following "https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github" url. But notification shows An "unknown error occurred. Please consult the log for more details."

Extension not install

**Comment by wbing520** [comment]
Could you please give more details, like screenshot? What is your browser, VS code version and OS version? It works on Chrome, Windows 10 (Version 1909) with VSCode 1.45.0. Thanks.

**Comment by sandy081** [comment]
> When i install extension from browser

What do you mean by installing from browser? Are you using VS Code from browser?
