### ISSUE TITLE
Quick open doesn't select the first entry on open

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#97353]
- Press cmd+P
- The first entry should be selected but isn't in Insiders

Stable:
![image](https://user-images.githubusercontent.com/323878/81476432-83981600-91d7-11ea-9701-8368723235a2.png)

Insiders:
![image](https://user-images.githubusercontent.com/323878/81476438-901c6e80-91d7-11ea-80e6-bded788cb93e.png)

**Comment by bpasero** [comment]
@roblourens I cannot reproduce, tried running out of sources and with insiders. Do you reproduce with a new user data dir and no settings/keybindings?

**Comment by roblourens** [comment]
Works fine today 🤷
