### ISSUE TITLE
provideCompletionItems will automatically add on 'JavaScript Language Basics'

### ISSUE THREAD

**Issue by susiwen8** [microsoft/vscode#97358]
I have registered `provideCompletionItems`, but seems like it will automatically add build in Snippets, How can I remove those?
<img width="691" alt="Screen Shot 2020-05-09 at 23 59 43" src="https://user-images.githubusercontent.com/20318608/81478734-be3e9480-9251-11ea-9f8c-b34755da8949.png">

**Comment by jrieken** [comment]
That's snippet completions which can be configured (individually via settings), as an extension there is no way to surpress completions of other extensions

**Comment by susiwen8** [comment]
@jrieken Thanks for reply
