### ISSUE TITLE
Incorrect Find Count

### ISSUE THREAD

**Issue by adebiyial** [microsoft/vscode#97351]
- VSCode Version:  1.45.0
- OS Version: Darwin x64 19.4.0

Steps to Reproduce:

1. Create any file (JS, for example).
2. Type multiple `console.log()`
3. Find (`CMD + F`) `console`
4. Delete each instance of `console` found
5. Check the Find window to the top-right, the count shows something like *? of 5*

Does this issue occur when all extensions are disabled?: Yes/No
<img width="987" alt="Screenshot 2020-05-09 at 15 07 29" src="https://user-images.githubusercontent.com/18689106/81475906-d6d58d00-9206-11ea-92f4-458eafc67396.png">

**Comment by Tyriar** [comment]
This is by design so that another search doesn't need to happen until you ask for it.
