### ISSUE TITLE
Settings has an invalid type, expected "string". Fix in JSON. Live Server Not Previewing.

### ISSUE THREAD

**Issue by Darshan20J** [microsoft/vscode#97355]
- VSCode Version: 1.45.0
- OS Version: Windows 10 1903

Steps to Reproduce:

1. Settings > Liveserver
2.  Settings : Host
3. Edit in JSON settings:json

![vscode error](https://user-images.githubusercontent.com/59853594/81477124-a0facd80-9233-11ea-9140-66e8e9e05d96.jpg)

4. I have edited in JSON settings and saved the file but it still not working for me. Take a look
![vscode error2](https://user-images.githubusercontent.com/59853594/81477289-a3115c00-9234-11ea-8803-6b3524d2cf4f.jpg)

5. After saving. Again shows error!! What????????
![vscode error 3](https://user-images.githubusercontent.com/59853594/81477334-f1265f80-9234-11ea-9070-865b91214dfb.jpg)

6. Liveserver is not working as it in previous versions.

**Comment by LSUESL** [comment]
I'm seeing this error sprinkled throughout the settings page. I do not have Live Server installed, so I don't think it's related to that. For example, the GitLens "Heatmap: Age Threshold" setting gives this error, and setting it to an empty string does not remove the error.

I've been trying to isolate this for the past couple of days, and backed out most all of my extension installs, and even reinstalled VSCode (MacOS) FWIW, but these errors still appear, and do not resolve by adding a value in settings.json. 

Unfortunately, I can't pin down WHEN they began to appear. I'm new (~week) to VSCode and these error flags may have been lurking in my settings all along...

**Comment by Darshan20J** [comment]
Thank You ! But I need some help.

**Comment by tgodzik** [comment]
Happens the same to me, looks like it detects that `1.23.4` etc. is not a string. If you write localhost there, it will most likely stop showing an issue. We have a setting that has a value like `0.9.0` and that is also shown as not a string despite actually being a string.

**Comment by takezoe** [comment]
https://github.com/microsoft/vscode/commit/5d8cb8a6a30e2123d0dca80b2cf4e4bbd7d1518b fixed this issue as well as https://github.com/microsoft/vscode/issues/97192? Actually, there are further modifications in settings validation in the latest master: https://github.com/microsoft/vscode/blob/306235b1e6780216df21da373965323f7a921888/src/vs/workbench/services/preferences/common/preferencesValidation.ts

This issue may not happen on the latest master.

**Comment by Darshan20J** [comment]
So now what should i do to fix that issue?

**Comment by elspnm** [comment]
> * VSCode Version: 1.45.0
> * OS Version: Windows 10 1903
> 
> Steps to Reproduce:
> 
> 1. Settings > Liveserver
> 2. Settings : Host
> 3. Edit in JSON settings:json
> 
> ![vscode error](https://user-images.githubusercontent.com/59853594/81477124-a0facd80-9233-11ea-9140-66e8e9e05d96.jpg)
> 
> 1. I have edited in JSON settings and saved the file but it still not working for me. Take a look
>    ![vscode error2](https://user-images.githubusercontent.com/59853594/81477289-a3115c00-9234-11ea-8803-6b3524d2cf4f.jpg)
> 2. After saving. Again shows error!! What????????
>    ![vscode error 3](https://user-images.githubusercontent.com/59853594/81477334-f1265f80-9234-11ea-9070-865b91214dfb.jpg)
> 3. Liveserver is not working as it in previous versions.

Uninstall VS Code fully > delete .vscode and Code folder then install the user setup not the system setup file. Then install the live server. It works fine in both win 7 and 10 with latest chrome v81.

Try and reply.

**Comment by klesun** [comment]
@elspnm I have same issue with other random [vscode-phpstan](https://marketplace.visualstudio.com/items?itemName=calsmurf2904.vscode-phpstan) extension. I tried uninstalling vscode and removing `/c/Users/User/.vscode`, then installing the "Insiders" build: `v1.46.0-insider` dated `2020-05-07` and the issue does not seem to be fixed there yet.

![image](https://user-images.githubusercontent.com/5202330/81509666-ef33cd80-9314-11ea-8298-aa7b16db2155.png)

**Comment by elspnm** [comment]
> * VSCode Version: 1.45.0
> * OS Version: Windows 10 1903
> 
> Steps to Reproduce:
> 
> 1. Settings > Liveserver
> 2. Settings : Host
> 3. Edit in JSON settings:json
> 
> ![vscode error](https://user-images.githubusercontent.com/59853594/81477124-a0facd80-9233-11ea-9140-66e8e9e05d96.jpg)
> 
> 1. I have edited in JSON settings and saved the file but it still not working for me. Take a look
>    ![vscode error2](https://user-images.githubusercontent.com/59853594/81477289-a3115c00-9234-11ea-8803-6b3524d2cf4f.jpg)
> 2. After saving. Again shows error!! What????????
>    ![vscode error 3](https://user-images.githubusercontent.com/59853594/81477334-f1265f80-9234-11ea-9070-865b91214dfb.jpg)
> 3. Liveserver is not working as it in previous versions.

Have you tried to run the VSCode in compatibility mode (win7) . In win 7 there is no issue at all. 
But when it comes to win10 lot of issue for different people. Ofcourse this extension needs to fix those bugs.

**Comment by lcbm** [comment]
This is also happening in **Linux 5.6.11-arch1-1 x86_64**. I'll leave some info here, hope it helps somehow. If anything else is needed, let me know and I'll be glad to help further :smiley: 

**Environment**
- OS: `Linux 5.6.11-arch1-1 x86_64`
- Package:  [`visual-studio-code-bin (AUR)`](https://aur.archlinux.org/packages/visual-studio-code-bin), via [`yay`](https://github.com/Jguer/yay)
- `$ code --version`: 1.45.0 d69a79b73808559a91206d73d7717ff5f798f23c x64

**Other information**
From what I noticed, only settings related to `Java` extensions have this behavior. Not sure if this is coincidence or not, but earlier I had to add `java.home` setting to my `settings.json` file, as well as `java.semanticHighlighting.enabled`. Also, note that the settings which the `errors` refer to, are not set in the `settings.json` file. See below :point_down: 
>**note**: the java extensions I have enabled are from the [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack).

settings.json:

```json
{
    "workbench.colorTheme": "Dracula",
    "workbench.iconTheme": "material-icon-theme",
    "editor.fontFamily": "Fira Code",
    "editor.renderWhitespace": "all",
    "editor.tabSize": 2,
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "editor.fontLigatures": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.rulers": [
        100
    ],
    "window.zoomLevel": 0,
    "[json]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "sync.gist": "3d5eafa3aa57d371f3c166c7ce273635",
    "go.useLanguageServer": true,
    "java.home": "/usr/lib/jvm/java-13-openjdk/",
    "java.semanticHighlighting.enabled": true,
}
```

Errors:

![vscode_error_settings_may_11_2020](https://user-images.githubusercontent.com/31375047/81573329-b3cbea00-937a-11ea-85cb-496fa7397b76.png)

**Comment by roblourens** [comment]
Sorry everyone. This is fixed in https://github.com/microsoft/vscode/issues/97192. Will be in the next release this week.

**Comment by BasuRB** [comment]
This is still broken. 
```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-33-generic snap
```

**Comment by cedricvidal** [comment]
Also broken on OSX:

```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.6.0
```

**Comment by roblourens** [comment]
The duplicate issue noted that there is another case where this appears, and is currently fixed in Insiders and will be in the next release - https://github.com/microsoft/vscode/issues/97192#issuecomment-629373359
