### ISSUE TITLE
Read line hover details!

### ISSUE THREAD

**Issue by simoebenhida** [microsoft/vscode#97356]
I'm not sure if this already exists! But it will be cool to have `Line` Object return details hover of a line! So it can help when developing an extension!

![Screen Shot 2020-05-09 at 15 12 21](https://user-images.githubusercontent.com/19809072/81477485-86aafa80-9207-11ea-93a8-d0acdbc7b3d0.png)
For example, here I want to get the namespace of that variable!

`TextDocument.lineAt(Position).hoverDetails` and it will give each word/details array or something

**Comment by jrieken** [comment]
You get trigger the data providers themselves via command: see https://code.visualstudio.com/api/references/commands and find `vscode.executeHoverProvider`
