### ISSUE TITLE
When edit javascript in *.html, autocomplete not work

### ISSUE THREAD

**Issue by jaylinwang** [Microsoft/vscode#9735]
- VSCode Version:  1.3.1
- OS Version: OSX10

When edit javascript in *.html, autocomplete not work,is a bug?

**Comment by wUFr** [comment]
i believe its not supported right now - you have to switch document language manualy to javascript, i +1 it yesterday somewhere, since other editors will detect javascript or even php inside html document

**Comment by wUFr** [comment]
so workaround: every time you will edit JS in HTML file, change language in bottom right corner (:

**Comment by jaylinwang** [comment]
@wUFr thanks 😄

**Comment by kieferrm** [comment]
Duplicate of #3465.
