### ISSUE TITLE
If find and replace is launched with multiple cursors present, automatically send first to find and the second to replace

### ISSUE THREAD

**Issue by veddandekar** [microsoft/vscode#97365]
When we have text selected and press the ctrl+F key combination to launch find, the selected text is directly sent to the find field. However, if we select text and press the ctrl+H key combination to launch find and replace, highlighted text is only sent to the find field and the replace field is left blank.

This is an understandable limitation in most applications as they only support a single cursor. However, as Visual Studio supports multiple cursors and selections, I think a feature to send the first highlighted text to the find field and the next highlighted text to the replace field would fit perfectly in VS Code.

The feature would work as follows -
1) Select the text you wish to find.
2) Preserving the previous selection, make a new selection (multi-cursor - can be done by pressing and holding the alt key while making the second selection).
3) Launch find and replace(ctrl+H, by default).

At the end of these three steps, the first selection will be placed in the find field and the second selection will be placed in the replace field.

The following image would be the result after completing the above three steps. Here, "Hello" was selected first, then "World"
![VSMultipleFindAndReplace](https://user-images.githubusercontent.com/42548201/81480819-b0851100-9249-11ea-9565-1e9b3c3c443c.png)

I have managed to locally implement this feature and I have been using the modified build for a while now. I will attach a PR of the same for whoever wishes to try/test the same.

Small, simple but usable features like this are what make VS Code great and I think this feature will add to the overall convenience of using VS Code.

What do you guys think?

**Comment by Tyriar** [comment]
This is certainly not how I would expect it to work so it's opening up users to getting confused imo.

> I have managed to locally implement this feature and I have been using the modified build for a while now.

You can probably write an extension to do this?

**Comment by rebornix** [comment]
Interesting idea. I'm not sure yet how we are going to introduce it without breaking existing users' expectations. Let's see how others think about it.
