### ISSUE TITLE
Extension API: window.activeColorTheme does not report the correct theme

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#97369]
- VSCode Version: 1.45.0
- OS Version: Win / Lubuntu

Steps to Reproduce:

1. Chose a light theme
2. Restart VS Code
3. Invoke an extension command that does this:
```ts
const ui = {
    [ColorThemeKind.Light]: "light",
    [ColorThemeKind.Dark]: "dark",
    [ColorThemeKind.HighContrast]: "highContrast",
}[window.activeColorTheme.kind];
console.log(`Theme is ${ui}`);
```

This extension should now report `Theme is light`. However, for me it reports `Theme is dark`.
If I change the theme to a dark theme, then back to a light theme and then run the extension command again, it correctly reports `Theme is light`.
If I restart VS Code, it reports again `Theme is dark`, even though the theme is light.

**Comment by aeschli** [comment]
Sorry for that, pushed a fix. Hope it's ok if that comes in May, or do you need it urgent?

**Comment by hediet** [comment]
Thank you for fixing it so quickly! Great work by the way! It is not urgent ;)
