### ISSUE TITLE
Set java vmargs in vscode at workspace level

### ISSUE THREAD

**Issue by Shabirmean** [microsoft/vscode#97363]
I would like to be able to set java VM arguments at workspace level. That is, not having to have it in each launch configuration in the **_launch.json_**. This would be a specific arguments_(say a java-agent)_ I want to be added and used whenever a launch is triggered for the current workspace in vscode. I also don't want it to be global to all Java projects opened in vscode, just the current workspace.

I have tried adding this in .vscode/settings.json, but it doesn't seem to work:
```json
{
  "java.jdt.ls.vmargs": "-javaagent:/Users/me/my-agent.jar"
}
```
I have also opened a [SO post here](https://stackoverflow.com/questions/61700234/how-to-set-java-vmargs-in-vscode-at-workspace-level) about this requirement.

The requirement is for the purposes of [this plugin](https://marketplace.visualstudio.com/items?itemName=shabirmean.ebean-enhancement&ssr=false#overview).

I need to set a **_javaagent_** runtime argument per workspace. I am currently doing this by updating the workspace launch configurations. This forces me to ask the user to pick a configuration or to set the update on all configurations. Ideally, it would be at a level up where the argument will be inserted to all launch configurations in that workspace.

**Comment by Shabirmean** [comment]
The requirement is similar to as mentioned in https://github.com/microsoft/vscode-java-pack/issues/312.

**Comment by Shabirmean** [comment]
@Tyriar - I don't see why its tagged as **_caused by extension_**. It is a request for a feature for the purposes of building or enhancing an extension. Not necessarily caused by it.

**Comment by weinand** [comment]
In a launch config you can access workspace settings via the `${config:NAME}` syntax.
So you can pass a workspace setting to your Java runtime in a launch.config.
