### ISSUE TITLE
Update crashes when MS Outlook is active 

### ISSUE THREAD

**Issue by SourceressNL** [microsoft/vscode#97367]
Issue Type: <b>Bug</b>

If MS Outlook is active and Visual Studio Code starts to (auto)update, the program crashes and is unusable afterwards. I have to completely remove it and install it again, with MS Outlook turned off. 
I have to do this every single update, since Outlook is always active on my machine.

The error says the update can't be installed because it has no access to the Visual Studio Code bin folder. (what is MS Outlook even doing in the VSC bin folder??)

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.17763

**Comment by joaomoreno** [comment]
/duplicate #60697

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
