### ISSUE TITLE
Update Installation

### ISSUE THREAD

**Issue by ShaleenAg** [microsoft/vscode#97364]
Issue Type: <b>Bug</b>

Vs code is not identifying my install location ....whenever I try to update it ..........it goes to the default location and not my current one and the update fails

here is the inno updater log 
```
May 09 22:56:41.984 INFO Starting: C:\Program Files\Microsoft VS Code\Code.exe, false
May 09 22:56:41.996 ERRO Bad arguments: Code path doesn't seem to exist: C:\Program Files\Microsoft VS Code\Code.exe
```

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.20.0
bracket-pair-colorizer-2|Coe|0.1.2
c-cpp-compile-run|dan|1.0.8
python-extension-pack|don|1.6.0
gitlens|eam|10.2.1
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|4.5.0
r|Iku|1.3.0
r-pack|Iku|0.0.2
MagicPython|mag|1.1.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.4.76186
remote-wsl|ms-|0.44.2
cpptools|ms-|0.28.0-insiders3
Go|ms-|0.14.1
indent-rainbow|ode|7.4.0
java|red|0.61.0
vscode-yaml|red|0.7.2
r-lsp|REd|0.1.6
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.10.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.3
vscode-icons|vsc|10.1.1
jinja|who|0.0.8
material-theme|zhu|3.5.0

(2 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Does the issue resolve if you uninstall and reinstall VS Code?>

**Comment by ShaleenAg** [comment]
> Does the issue resolve if you uninstall and reinstall VS Code?>

Haven't tried uninstalling it yet... It took me a lot of time to set it up

**Comment by joaomoreno** [comment]
Please let me know once you do.
