### ISSUE TITLE
Delete files not found in Recycle bin

### ISSUE THREAD

**Issue by CXXVII** [microsoft/vscode#97366]
I discard my folder in source control in activity panel VS CODE. I didn't know it was deleted in my PC. I checked those file recycle bin but there are not here. Any one know how to get it. Please help me.
Thank you.

VS CODE version : 1.45.0
OS : Windows 10 Pro 1903 (OS Build 18362.418)

**Comment by gjsjohnmurray** [comment]
Did you get this message?

![image](https://user-images.githubusercontent.com/6726799/81485687-04dac180-9247-11ea-9bea-a2ff4c16d61c.png)

**Comment by gjsjohnmurray** [comment]
If you still have the file open in VS Code you might be lucky. Look for its tab with a '(deleted)' suffix in the label.

![image](https://user-images.githubusercontent.com/6726799/81485795-d5788480-9247-11ea-87d4-963553005755.png)

Make the file dirty (e.g. add a space and delete it).

Save the file.

**Comment by CXXVII** [comment]
> Did you get this message?
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/6726799/81485687-04dac180-9247-11ea-9bea-a2ff4c16d61c.png)
> 
> 


I don't remember exactly. I think it show message. It’s my fault😔 Thank you

**Comment by CXXVII** [comment]
> If you still have the file open in VS Code you might be lucky. Look for its tab with a '(deleted)' suffix in the label.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/6726799/81485795-d5788480-9247-11ea-87d4-963553005755.png)
> 
> 
> 
> Make the file dirty (e.g. add a space and delete it).
> 
> 
> 
> Save the file.

Thank you 😊
