### ISSUE TITLE
Quick suggestion doesn't desappear when it has to

### ISSUE THREAD

**Issue by BenderEviler** [microsoft/vscode#97362]
Issue Type: Bug

When i'm finished writting a word that the quick suggestion failed to guess, that suggestion remains on the screen. So, if a hit the 'enter', instead of going to the next line, it will unnecessarily accept the word, and i'll have to hit 'enter' again.
Steps to reproduce:
1 - create a new .txt file
2 - inside the file write "babe baby"
3 - insert some lines and try to write "babe", character by character
the suggestion will show the word "babe" until you finish the last character, and when you've already finished the entire word the suggestion will remain in the screen. Now, if you wanna go to the next line, you'll have to hit 'enter' twice, cause the first hit will accept the suggestion.

Obs: I don't want to disable quick suggestions on plain text (i know how to do it), I want it to work properly. And this bug happens on any kind of file, not only txt files.

VS Code version: Code 1.44.2 (ff91584, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Tyriar** [comment]
Please don't create duplicates.

/duplicate https://github.com/microsoft/vscode/issues/97312
