### ISSUE TITLE
Built-in functionality to easily add a command to right-click context menu

### ISSUE THREAD

**Issue by mccarthyp-snet** [microsoft/vscode#97372]
Built-in functionality to add a command to the right-click context menu would be great. I had to learn how to create my own extension just to add "Run Selected Text in Active Terminal" to the context menu in the Editor. Seems simple enough to add this as a built-in functionality, though.

**Comment by sbatten** [comment]
An extension could provide this feature. One extension can provide a way to register arbitrary commands. e.g. https://marketplace.visualstudio.com/items?itemName=maruruh.vscode-quick-menu-builder
