### ISSUE TITLE
Killing bash upsets panel toggle keybinding

### ISSUE THREAD

**Issue by wolf99** [microsoft/vscode#97379]
- VSCode Version: 1.44.2
- OS Version: 10.0.8363

Steps to Reproduce:

1. Open the terminal panel (tried with cmd and bash shells)
2. Kill the shell (`exit` in cmd, `^d` in bash, or just use the garbage can icon), so that there is no shell instance open.
3. Try to toggle the panel to close it using the `workbench.action.terminal.toggleTerminal` keybinding (default is `Ctrl+'`).

Expectation: Panel closes

Actual: Panel stays open and new shell instance is loaded

This issue does not occur if using the "x" button on the panel controls.

Does this issue occur when all extensions are disabled?: Yes

PS: just discovered the `Ctrl+J` default binding for `workbench.action.togglePanel`... The issue does not occur when using this instead of the `Ctrl+'` command. But what is the difference between these two? They should both only toggle the view rather than take any action in the terminal, right? Or maybe there are additional semantics here...

**Comment by Tyriar** [comment]
Should be fixed in 1.45

**Comment by wolf99** [comment]
Confirmed. bash and init processes close as expected also.
