### ISSUE TITLE
Improve new constant color

### ISSUE THREAD

**Issue by pedroassis** [microsoft/vscode#97373]
- VSCode Version: 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c)
- OS Version: MacOS Catalina 10.15.3

Variable highlighting is all over the place, there seems to be a new type of highlighting for a local variable, but its confusing/annoying.

The shade for it is too close to the unused variable color.

Steps to Reproduce:

1. Create a new File
2. Set the language to JS
3. Paste the snipped
```js
function name(test) {
    const unused = 'unused';
    const { ola } = test;
    const test2 = ola.another;
    return { ola, test2 };
}
```

![image](https://user-images.githubusercontent.com/4248124/81484168-fcb85d00-9219-11ea-87db-847792a9a1cc.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

EDIT: 
And if you access a prop from a shaded variable, the prop is not shaded, as shown in the `ola.another`.

If you use the variable inside an object it also doesn't get shaded. It looks like a diff variable.

**Comment by rauenzi** [comment]
This seems to be part of the new update https://code.visualstudio.com/updates/v1_45#_new-color-for-constants-in-the-default-dark-theme

However I wish they also provided a way to revert the change in that changelog because it makes it impossible to distinguish for me as well.

**Comment by yoohahn** [comment]
Same for TypeScript. Really poor choice of color here from the team.
Would love to disable this change or at least be able to override the color.

**Comment by kasvtv** [comment]
Would love to be able to disable this. As it looks now it seems all `const` variables are unused!

**Comment by pedroassis** [comment]
And if you access a prop from a shaded variable, the prop is not shaded, as shown in the `ola.another`.

If you use the variable inside an object it also doesn't get shaded.

@rauenzi did you find how to disable? I couldn't figure it out.

**Comment by kasvtv** [comment]
Got a fix that overrides the constants to their old value in default dark +. Add the following to the `settings.json`:
```
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": ["variable.other.constant", "variable.other.enummember"],
        "settings": {
          "foreground": "#9CDCFE"
        }
      }
    ]  
  },
```

**Comment by tonivj5** [comment]
> Got a fix that overrides the consts (and enums, these have the same shade) to their old value in default dark +. Add the following to the `settings.json`:
> 
> ```
>   "editor.tokenColorCustomizations": {
>     "textMateRules": [
>       {
>         "scope": ["variable.other.constant", "variable.other.enummember"],
>         "settings": {
>           "foreground": "#9CDCFE"
>         }
>       }
>     ]  
>   },
> ```

It works perfect :clap:! The new color looks too dark (it seems unused :disappointed:)

**Comment by aeschli** [comment]
Please use the following setting if you prefer the previous coloring:
```
    "editor.tokenColorCustomizations": {
        "[Default Dark+]": {
            "textMateRules": [
                {
                    "scope": ["variable.other.constant", "variable.other.enummember"],
                    "settings": {
                        "foreground": "#9CDCFE"
                    }
                }
            ]
        },
        "[Default Light+]": {
            "textMateRules": [
                {
                    "scope": ["variable.other.constant", "variable.other.enummember"],
                    "settings": {
                        "foreground": "#001080"
                    }
                }
            ]
        }
    }
```

**Comment by fr3gu** [comment]
This needs to be a setting. As a person with impaired color vision it totally defeats the purpose of dimming unused variables. Side by side I can distinguish them with some efforts, but at a glance I cannot discern if there is a difference.

**Comment by misolori** [comment]
Here's a couple of variations that we've been exploring for the Dark theme. The intent is try to stay close to the "blue" color range so as to not be too different. You can test these out by using [the instructions above](https://github.com/microsoft/vscode/issues/97373#issuecomment-627177235).

## Option 1 `#8F9DFF`
<img width="50%" src="https://user-images.githubusercontent.com/35271042/83069067-2648f500-a01e-11ea-8376-3509a513bd6d.png">

## Option 2 `#4FC1FF`
<img width="50%" src="https://user-images.githubusercontent.com/35271042/83069483-cbfc6400-a01e-11ea-82b5-903e7ae98e77.png">

## Option 3 `#82DFE8`
<img width="50%" src="https://user-images.githubusercontent.com/35271042/83069578-f9e1a880-a01e-11ea-9550-fa83349afbe8.png">

## Option 4 `#3CD9E8`
<img width="50%" src="https://user-images.githubusercontent.com/35271042/83069811-5cd33f80-a01f-11ea-809a-25763475dbab.png">


Once we've identified a version that works better we'll move to exploring one for the Light theme:

**Comment by fr3gu** [comment]
That's great. Personally, I will test option 2 for a while. Thanks!

**Comment by aeschli** [comment]
I also like 2 the most.

**Comment by vnestere** [comment]
I think this feature should be optional. I personally don't want to have separate color for constants. It only makes reading code harder, and does not worth it.

**Comment by sashahavia** [comment]
I also do not understand the benefit/need to separate color for constants. It makes no sense and the options above are not great. Why do we need a rainbow of colors? Whoever is doing that obviously doesn't work with VSCode on daily basis. Your last update for constants messed with a lot of people.
Imagine you come in to the office and your office is upside down. This is how I felt when I opened my laptop in the morning to work but instead spend hours debugging VSCode and searching for solution online. Finally asking you for the override to the original colors.
