### ISSUE TITLE
Markdown preview is rendered with strange fonts

### ISSUE THREAD

**Issue by dimitry-ishenko** [microsoft/vscode#97374]
Issue Type: <b>Bug</b>

1. Remove all font settings in settings.json.
2. Create new file and change language to Markdown.
3. Enter the following:
<img src="https://user-images.githubusercontent.com/2858291/81481345-6413e400-91fd-11ea-8513-89e81cd4dfc7.png" width="75%" />

4. Press Ctrl+Shift+V to show preview:
<img src="https://user-images.githubusercontent.com/2858291/81481379-bbb24f80-91fd-11ea-9f03-2a3ae9a5c7e6.png" width="75%" />

5. Observe the file rendered with Ubuntu for the plain text and Courier New for the code block. I do not have these fonts specified anywhere in my settings (including GNOME settings). My settings are:
```bash
dimitry@laptop:~$ fc-match monospace
CourierMod-Regular.ttf: "Courier" "Regular"
dimitry@laptop:~$ fc-match sans-serif
CenturyGothic-Regular.ttf: "Century Gothic" "Regular"
dimitry@laptop:~$ fc-match system-ui
CenturyGothic-Regular.ttf: "Century Gothic" "Regular"
```

6. Change Markdown preview font to your favorite font, eg:
`"markdown.preview.fontFamily": "'Roboto Mono'"`

7. Observe the plain text rendered in the proper font, but the code block is still rendered using Courier New:

<img src="https://user-images.githubusercontent.com/2858291/81482798-a9d5aa00-9207-11ea-926c-ec9e792a15ae.png" width="75%" />

Current behavior:

The code blocked are rendered using Courier New font, disregarding the `markdown.preview.fontFamily` setting.

Expected behavior:

Code blocks are rendered respecting the `markdown.preview.fontFamily` setting or at least using the `monospace` font.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:10:24.511Z)
OS version: Linux x64 5.4.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 3237)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.23GB (4.95GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.1
vscode-docker|ms-|1.1.0
python|ms-|2020.4.76186
cmake-tools|ms-|1.3.1
cpptools|ms-|0.27.1
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.7
vscode-icons|vsc|10.1.1

</details>

**Comment by dimitry-ishenko** [comment]
If I completely uninstall Courier New from the system, the code blocks are now rendered with DejaVu Sans Mono, which again is not specified in any of my settings:

<img src="https://user-images.githubusercontent.com/2858291/81484802-9251ed80-9216-11ea-9daa-e6a6bb4760c0.png" width="75%" />

**Comment by dimitry-ishenko** [comment]
Thank you @mjbvz. It's working great now.

**Comment by isidorn** [comment]
Adding verified per Dimitry's comment
