### ISSUE TITLE
Replacing a text in a ts file does not retain casing of replacing text

### ISSUE THREAD

**Issue by Spambit** [microsoft/vscode#97375]
Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
Steps to Reproduce:
1. Open a typescript file 
2. Press `Command + F` in Macbook to bring up replace text tool in that file
3. Put 'test' in first text box and `testToBe` in 2nd textbox
4. Hit enter
5. See the text `test` would be replaced with `testtobe` instead of `testToBe`

Does this issue occur when all extensions are disabled?: Yes/No - Yes

**Comment by ArturoDent** [comment]
You have the `**Preserve Case**` option selected probably - looks like `AB` at the end of the replace field.

Perhaps unintuitively, it seems to "preserve" the case of the test in the document - in your case that was `test` so it used all small letters `testtobe`  as the replacement.  If you had started with `Test` in the document and replaced it with the `Preserve Case` option the replacement would be `TestToBe`.

Without the `Preserve Case` option selected, you get `testToBe` for both text `test` and `Test`.

You will have to try the various combinations to learn what "Preserve Case" does.

See https://code.visualstudio.com/updates/v1_37#_preserve-case-in-find-and-replace and https://code.visualstudio.com/updates/v1_38#_preserve-case-in-search-and-replace

**Comment by Spambit** [comment]
Thanks for your reply in such a dummy thing!! Sorry. Fixed!
