### ISSUE TITLE
markdown.preview.breaks doesn't add any extra line breaks

### ISSUE THREAD

**Issue by jli** [microsoft/vscode#97382]
- VSCode Version: 1.46.0-insider, also 1.45.0
- OS Version: Mac OS X Catalina, also High Sierra

Steps to Reproduce:

1. Turn on `markdown.preview.breaks`
1. Create markdown file with multiple consecutive line breaks somewhere.
1. Open markdown preview.

The settings description for `markdown.preview.breaks`: "Sets how line-breaks are rendered in the markdown preview. Setting it to 'true' creates a <br> for every newline."

However, enabling this doesn't seem to have any effect on the markdown preview. I would expect that multiple newlines in the source markdown file would result in more vertical whitespace in the preview, but this isn't the case. See the attached screenshot.

Does this issue occur when all extensions are disabled?: Yes

![bug screenshot](https://user-images.githubusercontent.com/133466/81488961-0eabf700-923e-11ea-8608-53ad79e6d81e.png)

**Comment by mjbvz** [comment]
This setting only effects cases like:

```md
some
text
```

Which will have a new line between `some` and `text` instead of being a single paragraph. I'll clarify this in the setting docs
