### ISSUE TITLE
(C#) Folding is disabled when writing code

### ISSUE THREAD

**Issue by JotaRata** [microsoft/vscode#97385]
Issue Type: <b>Bug</b>

I have a file where I defined many large Dictionaries
Fold every Dictionary to reduce space
Write anything, errors will arise, as the code is not writed completely yet

(example, if you start typing:
public float GetMyFloat(string arg){ ...
A error will popup in the Problems tab, as you haven't defined a return yet)

As soon a problem appears in the Problems tab, every folded Dictionary will be unfolded

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.86GB (0.77GB free)|
|Process Argv|C:/Users/Jose Joaquin/Documents/Unity Projects/UnivGoggles/Universe Goggles|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
docomment|k--|0.1.9
csharp|ms-|1.21.15
python|ms-|2020.4.76186
csharp|ms-|1.21.12
unity-debug|Uni|2.7.5

</details>

**Comment by aeschli** [comment]
This issue needs to be filed against 
https://github.com/OmniSharp/omnisharp-vscode/
Would you mind filing the issue there? (Unfortunately, the issue-transfer tool only works with write access on both repos, which I haven't)
