### ISSUE TITLE
Redundant conditions specified for keyboard shortcuts

### ISSUE THREAD

**Issue by sunliangqin** [microsoft/vscode#97381]
Issue Type: <b>Bug</b>

I noticed that some keyboard shortcuts have the same condition specified which seems redundant. 

![image](https://user-images.githubusercontent.com/211268/81488814-06928e00-9223-11ea-824d-cf78eff99054.png)

![image](https://user-images.githubusercontent.com/211268/81488828-2b870100-9223-11ea-9b79-65af8805e8ed.png)

VS Code version: Code - Insiders 1.46.0-insider (d487078dc7fc1c276657cadb61b4f63833a8df55, 2020-05-07T16:19:54.327Z)
OS version: Windows_NT x64 10.0.17763

**Comment by ZainChen** [comment]
Hello everyone, I'm looking at this problem.

**Comment by ZainChen** [comment]
＃98872

**Comment by ZainChen** [comment]
This is my solution. :smiley:
