### ISSUE TITLE
git ".ignorefile" 

### ISSUE THREAD

**Issue by omidiu** [microsoft/vscode#97383]
Issue Type: <b>Bug</b>

The problem is when I commit file in git and after that want to remove it from tracking in "gitignore" using "git rm --cached <file>" visual studio doesn't show that file Faint again. 

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
javascript-ejs-support|Dig|1.3.1
jquerysnippets|don|0.0.1
cpptools|ms-|0.27.1
debugger-for-chrome|msj|4.12.6
material-icon-theme|PKi|4.1.0
LiveServer|rit|5.6.1
indenticator|Sir|0.6.0

</details>

**Comment by joaomoreno** [comment]
I'm not so sure I understand but it seems this might be a git usage misunderstanding? Have you read https://git-scm.com/docs/gitignore?

**Comment by omidiu** [comment]
> I'm not so sure I understand but it seems this might be a git usage misunderstanding? Have you read https://git-scm.com/docs/gitignore?

Yes. Actually I know what is .gitignore.      
 By default vs code show what is in .gitignore file like as transparent. But if one file tracked and I want to make it as untrack file. when I use "git rm --cached "  and write name of that file in .gitignore after that vs code don't show that file like as transparent anymore.
