### ISSUE TITLE
Special font-size for quick fix widget?

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#9738]
Why do we use a special font size for quick fix widget, imho it should be the same font size as the editor so it reads nicer. The current way it feels a bit alien to me

![screen shot 2016-07-26 at 09 42 47](https://cloud.githubusercontent.com/assets/1926584/17129844/ba8cd59c-5315-11e6-9a24-fd6dafd0e803.png)

My proposal: 

![screen shot 2016-07-26 at 09 45 51](https://cloud.githubusercontent.com/assets/1926584/17129851/c452efee-5315-11e6-819a-6e2283fb93ac.png)

Font is defined here: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/quickFix/browser/quickFix.css#L40

**Comment by aeschli** [comment]
Good find, I wasn't aware that we use a special font, probably some leftover.
