### ISSUE TITLE
Debugger links to lines are broken

### ISSUE THREAD

**Issue by mihael-stormrage** [microsoft/vscode#97397]
- VSCode Version: 1.45.0
- OS Version: Windows_NT x64 10.0.18363

When I'm getting an error in code interpretator tells in which file, line and on which symbol it is. And it gives me a link like "file:///file:line:symbol", but when I'm trying to follow it I'm getting an error "Unable to open 'file.js:19:23' ":
![image](https://user-images.githubusercontent.com/54357100/81495796-24bcc480-92dd-11ea-847e-85089f52a7c7.png)

In Insider build 1.46.0 comes the same, but if I run `node D:\mihan\Documents\Code\Projects\cultist-simulator-description-tooltip-mod\recipes.js` in CMD Terminal links there works fine.

![image](https://user-images.githubusercontent.com/54357100/81495984-79ad0a80-92de-11ea-9148-3c9ae6e2e6c2.png)
Stable build doesn't have links in terminal output.

I think that new terminal links functional was implemented separately of the old buggy one. My request is to fix other links which occurs in debugger and output (using Code Runner) windows.

Steps to Reproduce:

1. Run Node.js code with an error in debugger or using Code Runner Extension.
2. Ctrl+RigtClick on link to file:line[:symbol]

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/34026
