### ISSUE TITLE
Can't push changes to Github workflows if VS Code authenticated as OAuth Github app

### ISSUE THREAD

**Issue by tysonite** [microsoft/vscode#97396]
Issue Type: <b>Bug</b>

* Authenticate VS Code as OAuth App on Github
* Modify `.github/workflows/<any_file>`
* Commit & Push

Error will appear:
```
 ! [remote rejected] master -> master (refusing to allow an OAuth App to create or update workflow `.github/workflows/test.yml` without `workflow` scope)
```

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (2.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|Memory (System)|7.82GB (2.97GB free)|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.4.76186
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2

</details>

**Comment by joaomoreno** [comment]
Oh that's pretty rough. Maybe let's add a workflow scope to it.

@RMacfarlane How easy is it to redefine the scopes for an existing key, which users might already have cached?

**Comment by RMacfarlane** [comment]
Unfortunately it's not possible to modify an existing token to add scopes, a new one has to be requested with the additional scopes

**Comment by joaomoreno** [comment]
@RMacfarlane What I meant to ask was: users will simply get asked to go through the flow once again if I change the scopes here, right? https://github.com/microsoft/vscode/blob/master/extensions/git/src/github.ts#L23-L23

**Comment by RMacfarlane** [comment]
Yep, that's correct!

**Comment by JacksonKearl** [comment]
Whats the process for registering VSCode as an OAuth app?

**Comment by joaomoreno** [comment]
@JacksonKearl This is the automatic git auth in VS Code: if you try to pull/push from a git repo using HTTPS, authentication will happen automatically with the GH auth provider.

Steps:

1. Clone a repo from GitHub
2. Make a change to a workflow file
3. Push

**Comment by JacksonKearl** [comment]
Havent been able to repro the initail error. Steps:

In a VM without my git auth already registered:
- Clone a repo via the integrated clone over https
- add workflow file.
- native-looking popup asks me to log in to github
- log in, push goes through.

This is on Windows 10

**Comment by joaomoreno** [comment]
Maybe it's specific to the workflow or to our auth. I also didn't repro before the change.

Marking as verified.

**Comment by WouterDeKort** [comment]
I have the same issue when using Visual Studio CodeSpaces. I've cloned a repo with a workflow file, made a change to the workflow file and now get the error on push that my OAuth App doesn't have the workflow scope.
