### ISSUE TITLE
javascript optional chain completions

### ISSUE THREAD

**Issue by lc150303** [microsoft/vscode#97398]
Issue Type: <b>Bug</b>

After disable the javascript.suggest.includeAutomaticOptionalChainCompletions, and have an object A with declared type { B?: {C: 0} }. when I typed A.B.C,  it will be auto replaced by A.B?.C, but in js file the '?.' operator should not exist.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (1.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Please share a complete code example

**Comment by lc150303** [comment]
I have a jsconfig.json with
```json
{  
    "include": [  
        "*"  
    ],  
    "compilerOptions": {  
        "checkJs": true,  
        "strict": true,  
    }  
}
```
and the setting is `"javascript.suggest.includeAutomaticOptionalChainCompletions": false`, and the code is 
```js
/**
 * @type {{b?:{c:number}}}
 */
let a = { b: { c: 7 } };
a.b?.c;
```
the '?' was inserted after i typed `a.b.c;`.

**Comment by lc150303** [comment]
> Please share a complete code example
@mjbvz 
as above

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/TypeScript/issues/38487 to track upstream
