### ISSUE TITLE
VS Code Not Recognising Git Repo

### ISSUE THREAD

**Issue by paul-a-byford** [microsoft/vscode#97392]
Issue Type: <b>Bug</b>

After updating to 1.45.0 VS Code is not recognising the git repo, it was working fine before the upgrade. 
* The Source Control panel has the message 'The folder currently open  doesn't have a git repository.' and has the initialise repository button
* However if i run `git status` in the integrated terminal I can see the branch that i was on and the status of untracked and uncommited files

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (10.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by paul-a-byford** [comment]
reboot resolved

**Comment by joyceerhl** [comment]
Hi VS Code team, I'm experiencing the exact same issue on macOS with a fresh install of VS Code version 1.45.1. The insiders build does not have this problem but I would like to use the stable VS Code release.

## Steps to reproduce
1. Install latest VS Code
2. Clone [vscode-python](https://github.com/microsoft/vscode-python.git)
3. Open folder in VS Code.
4. Source control displays the following message:

<img width="759" alt="Screen Shot 2020-06-03 at 4 02 33 PM" src="https://user-images.githubusercontent.com/30305945/83697392-bdc8bd80-a5b3-11ea-898e-f541992de316.png">

## Troubleshooting
I have already:
1. Uninstalled and reinstalled VS Code
2. Rebooted my machine
3. Deactivated all extensions

After `cd`ing to the folder containing the git repo and opening the folder in code, the output of `git rev-parse --show-toplevel` is: `/Users/Joyce/Desktop/Projects/vscode-python`.

The output panel for git displays this:
```sh
Looking for git in: usr/local/bin/git
Using git 2.11.1 from usr/local/bin/git
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
[truncated: 100 more of the same message]
```

## System Info
VS Code version: Code 1.45.1 
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (2 wks ago)
OS version: Darwin x64 18.7.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
