### ISSUE TITLE
vscode is not compliant to X Session Management spec.

### ISSUE THREAD

**Issue by rajinder-yadav** [microsoft/vscode#97395]
Issue Type: <b>Bug</b>

VSCode does not save X Session info on Linux, as a result session management is broken.

See: https://bugs.kde.org/show_bug.cgi?id=421035

VS Code version: Code - Insiders 1.43.0-insider (e6a45f4242ebddb7aa9a229f85555e8a3bd987e2, 2020-02-21T05:40:52.685Z)
OS version: Linux x64 5.6.11-1-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 3571)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|31.30GB (24.75GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.1.10
vscode-base64|ada|0.1.0
markdown-toc|Ala|1.5.6
Bookmarks|ale|11.1.0
ng-template|Ang|0.901.6
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.35.1
vscode-eslint|dba|2.1.5
EditorConfig|Edi|0.14.5
prettier-vscode|esb|4.5.0
markdown-preview-bitbucket|hbr|1.0.0
vscode-peacock|joh|3.7.0
solidity|Jua|0.0.72
sort-typescript-imports|mic|1.4.1
vscode-docker|ms-|1.1.0
python|ms-|2020.4.76186
cpptools|ms-|0.27.1
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
angular2-inline|nat|0.0.17
vetur|oct|0.24.0
vscode-yaml|red|0.7.2
markdown-preview-enhanced|shd|0.5.3
language-stylus|sys|1.11.0
find-then-jump|tra|2.0.4
sort-lines|Tyr|1.9.0
better-align|wwm|1.1.6
markdown-pdf|yza|1.4.4

(8 theme extensions excluded)

</details>

**Comment by irfan798** [comment]
Did anybody looked into this?

What are the steps to make it compliant to X Session Management?

**Comment by rajinder-yadav** [comment]
If I can add my input the application should record:

1. Size
2. Location

The location should take into consideration multiple-monitor setup as well as what "virtual desktop" (1 or all) the application should come up after session is saved and rebooted. Also the application must remove itself from the session when told to do so, so it doesn't keep coming up on reboots.

There might be other X Session Management requirements, but this is what I have a problem with on Linux. I originally open this as a Linux/KDE bug and was told this is the responsibility of the application (vscode) not the OS or Window manager. Historical reason why session are saved this (stupid) way, but this should help shed some light and context.

**Comment by irfan798** [comment]
This might be chromium related issue ( thus electron -> vscode ) 
Can you also check if chromium is restored properly, because on my setup its not.

**Comment by rajinder-yadav** [comment]
chromium fails session restore for me also

**Comment by deepak1556** [comment]
Closing as not actionable in VSCode, since this is an issue with the Chromium runtime.
