### ISSUE TITLE
Changes view input box moves up when clicking on a change

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#97393]
Steps to Reproduce:

1. I am in a multiroot setup, which probably is required for this
2. have 1 change
3. click it

=> 🐛 you see the view move up a bit

![recording](https://user-images.githubusercontent.com/900690/81494406-0341e580-92a9-11ea-9f3c-7a51f0fd5e49.gif)

**Comment by joaomoreno** [comment]
Look at that amazingly super optimized GIF!

**Comment by bpasero** [comment]
"Kap your hands, say yeah" :D
