### ISSUE TITLE
ProblemMatcher encoding issue

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode#974]
I'm working on a Windows 7 machine with german localization. My problem matcher works fine but german umlauts are not displayed properly.  (The first word of the shown warning should be "Rückgabewert") 
See the picture.

![vscodeproblemmatcherencodingissue](https://cloud.githubusercontent.com/assets/3448684/11566498/f889d152-99e2-11e5-9ec4-d880d43590aa.png)

**Comment by dbaeumer** [comment]
@Wosi can you pleae attach a screen shot showing the output viewlet (e.g.Ctrl+Shift+U)

**Comment by Wosi** [comment]
![vscodeproblemmatcherencodingissueoutput](https://cloud.githubusercontent.com/assets/3448684/11654650/b201120e-9da7-11e5-9747-5005ffe1124f.png)

**Comment by dbaeumer** [comment]
@Wosi thanks

**Comment by xWuliou** [comment]
when I get the folder list and output it .the folder name contains chinese. 
then the output like this:

['$RECYCLE.BIN', 'itunes', 'kankan', 'python', 'System Volume Information', 'tools', 'Ѹ������']

**Comment by ysqi** [comment]
I got something too.
- VSCode Version: v1.0.0
- OS Version:  6.1.7601 Service Pack 1 Build 7601
- OS Name:          Microsoft Windows 7 家庭普通版        
- Code page: 936
- Step: [ less config](https://code.visualstudio.com/docs/languages/css#_transpiling-sass-and-less-into-css)

![image](https://cloud.githubusercontent.com/assets/2821085/14803838/fa4c9d5c-0b8f-11e6-99ed-c091c609feda.png)

**Comment by longjxchina** [comment]
please support chinese (output window, reference pop,etc)

**Comment by dbaeumer** [comment]
This got addressed by the new terminal runner. To make use of the new terminal runner please see: https://code.visualstudio.com/docs/editor/tasks#_convert-from-010-to-200

The new terminal runner uses a terminal to execute tasks. This terminal by default uses the OS defined terminal, however there are various VS Code settings to control the terminal encoding as well. See the `terminal.integrated.shell` and `terminal.integrated.shellArgs` setting as well the `options.shell` property of a task.
