### ISSUE TITLE
Please add an option to disable warnings from simplifycompositelit

### ISSUE THREAD

**Issue by rajatsingh25aug** [microsoft/vscode#97406]
I keep on getting warnings like this `redundant type from array, slice, or map composite literalsimplifycompositelit`.

The point is that I write the code explicitly that way and I don't know how to disable this warning.
<img width="1679" alt="Screenshot 2020-05-10 at 7 13 11 PM" src="https://user-images.githubusercontent.com/17253992/81500853-7ae83280-92f2-11ea-9265-29e5278d77f4.png">
Please write a feature so that I can disable the warnings like above from the VScode's `settings.json`.
thanks

**Comment by sandy081** [comment]
Please file the issue against the extension that is generating these errors.

**Comment by rajatsingh25aug** [comment]
@sandy081 , This issue started to come when  I installed the go vscode extension.

**Comment by sandy081** [comment]
Please file against go extension.
