### ISSUE TITLE
"New folder" in tree context menu doesn't give focus to the tree if it was with another app

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#97408]
I seem to hit this quite a lot (even though it seems quite contrived!):

- Open two separate VS Code windows
- Put focus into the first VS Code window (in an editor)
- Without focusing the second VS Code window, right-click on its Explorer tree and pick "New Folder"

The explorer will add a new node to the tree, however it never gives focus to this VS Code window, so when you start typing, the text appears in the editor of the first VS Code window, rather than in the edit box in the tree of the second VS Code window.

It doesn't need to be two VS Code windows, if Chrome has focus, then it will receive the keystrokes instead, but a VS Code editor is an easy way to see the typing.

I think VS Code should be getting focus when you right-click on it to open the context menu.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/88822

**Comment by DanTup** [comment]
@isidorn that issue was closed as a dupe of #70966, but the title of that talks about highlighting (which sounds like a visual issue). If it's the same issue, it may be worth making the title of that issue clearer (the issue reported here is that VS Code doesn't take focus despite opening a context menu and clicking on an item, leaving focus in another application).

**Comment by isidorn** [comment]
There is already an issue about App not getting focus on context menu. Which is an underlying Electron issue. I could not find it, but did not search enough. You can search more and find the actual duplicate. Thank you.
