### ISSUE TITLE
"Taller" debug console input line + ability to move it to the top of the debug console

### ISSUE THREAD

**Issue by nazariyv** [microsoft/vscode#97402]
How difficult is to move the debug console line to the top and make it a bit larger?

Currently it is very "short" line at the bottom of the screen.

<img width="518" alt="Screenshot 2020-05-10 at 12 11 38" src="https://user-images.githubusercontent.com/13678461/81497605-705c7780-92b7-11ea-9243-0a52b7961e63.png">

**Comment by ArturoDent** [comment]
You can make the debug console input larger with `Shift+Enter` (and smaller with `Enter`) while in a active debug session.

See https://github.com/microsoft/vscode/issues/51725#issuecomment-558084413

Moving it to the top may be a new request.

**Comment by isidorn** [comment]
Moving to the top -> out of scope
You can make it larger by increasing "debug.console.lineHeight" and how @ArturoDent suggested. 
Thus closing this

**Comment by tiptronic** [comment]
Adding some pixels between the bottom of the debug-console and the status-bar at the bottom would make it feel better (and help not inadvertently touch elements in the status-bar)
