### ISSUE TITLE
Semantic highlighting - Used variable marked as unused

### ISSUE THREAD

**Issue by Jet132** [microsoft/vscode#97401]
Issue Type: <b>Bug</b>

Since version 1.45 a lot of class attributes in TypeScript get marked as unused, even though they are used.
![image](https://user-images.githubusercontent.com/37117573/81497408-a3563980-92be-11ea-9b35-5aa91e38f445.png)
I haven't tested this with JS, but I can clearly see that it only appears after the TSServer has finished loading.

VS Code version: Code - Insiders 1.46.0-insider (d487078dc7fc1c276657cadb61b4f63833a8df55, 2020-05-07T16:19:54.327Z)
OS version: Windows_NT x64 10.0.18362

**Comment by aeschli** [comment]
This is the constant color, not the unused color.

**Comment by misolori** [comment]
Unused variables are less opaque and if you over it you'll see more details.

![image](https://user-images.githubusercontent.com/35271042/81581328-6c862f00-9363-11ea-8145-ebe7acd3628a.png)

![image](https://user-images.githubusercontent.com/35271042/81581349-7740c400-9363-11ea-9689-2ca75fc198b6.png)
