### ISSUE TITLE
VSCode updated automatically and closed all windows

### ISSUE THREAD

**Issue by csrapr** [microsoft/vscode#97403]
my vscode force closed for an update and I lost 14 hours of DL training
DON'T DO THAT AGAIN
thank you.

**Comment by joaomoreno** [comment]
VS Code should never automatically update without your consent. Are you sure it didn't close because Windows decided to restart your machine due to an update?

**Comment by csrapr** [comment]
No, I was working on a different window when everything closed down and a tiny update window with a progress bar opened. When I reopened the program I got the changelog tab

**Comment by joaomoreno** [comment]
@csrapr Has this happened again since?
