### ISSUE TITLE
Powershell syntax highlighting

### ISSUE THREAD

**Issue by scriptingstudio** [microsoft/vscode#97404]
Powershell methods `foreach` and `where` are not highlighted after curly bracket. With parenthesis it works fine.

Example code:
`@($group).where{$_.count -gt 1 -and $_.name}.foreach{...}`
"where" is highlighted.
"foreach" is not highlighted.

It does not depend on powershell ext. I use the latest vscode.

**Comment by alexr00** [comment]
Moved to owning repo (we get our grammar for syntax highliting from PoserShell/EditorSyntax)
