### ISSUE TITLE
Debug: 'Disconnect' icon should be different than 'Stop'

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9740]
Currently we use the same `Stop` icon for both `Stop` and `Disconnect` actions. It would be more intuitive to use an icon that confers the idea of a _disconnection_ when the `Disconnect` action is in place.

cc @bgashler1

**Comment by isidorn** [comment]
Makes sense, @bgashler1 could you provide one such icon?

**Comment by bgashler1** [comment]
@isidorn this is the closest icon I have to disconnect.  If this works, I can give you both light and dark versions of it.

![disconnect_16x](https://cloud.githubusercontent.com/assets/11839736/17720052/c59cfe66-63d3-11e6-9e14-2779e482700e.png)

For clarification, is this in place of the Stop icon when debugging inside the floating debug menu?  Could you show me a screenshot of how this is currently in the product?  Thanks!

**Comment by joaomoreno** [comment]
Looks good!

Yes, it is in place of the last icon in the screenshot:

![image](https://cloud.githubusercontent.com/assets/22350/17728168/3ff35310-645e-11e6-965a-724c0195903c.png)

**Comment by bgashler1** [comment]
@joaomoreno 
[Disconnect_16px.zip](https://github.com/Microsoft/vscode/files/423876/Disconnect_16px.zip)

**Comment by bgashler1** [comment]
@isidorn 
Just found out that Visual Studio uses a different icon.  We should probably remain consistent and use this (see below)
![image003](https://cloud.githubusercontent.com/assets/11839736/17757504/1f72a152-649c-11e6-965c-ebff6f5e9608.png)

Here are the icons.  The correct one to use is in folder "02 use this"

**Comment by joaomoreno** [comment]
Not the biggest fan of that icon. Not only it has a different aesthetics than the other icons (looks like two crossed handmade brush strokes, while the others are simpler, more iconic), but also doesn't convey any _disconnect_ semantics, unlike the one you posted 2 comments above.

**Comment by bgashler1** [comment]
@joaomoreno I hear you and can see why you feel that way.  @isidorn do you agree with him?

**Comment by isidorn** [comment]
I agree with the points @joaomoreno made about the X icon. Another downside is that we previously used this icon in a lot of places but removed it everywhere. I do not see why we would go back to using it.
So I will go with the first proposal, which I think will work nicely.

**Comment by bgashler1** [comment]
Sounds good.  You'll find those assets in the same zip file under the other folder.

**Comment by bpasero** [comment]
Obsolete
