### ISSUE TITLE
View menu is getting out of hand in size

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#9741]
View menu has too many entries. We either need submenus or we need to remove entries.
Once we decide what we want here I can do the changes in code.

ping @stevencl @bgashler1 

![screen shot 2016-07-26 at 09 58 12](https://cloud.githubusercontent.com/assets/1926584/17130170/7d9b639a-5317-11e6-8ba7-4bb1d1362d28.png)

**Comment by bpasero** [comment]
We decided to not take action here given the large number of uses in the menu. Making our users click two times seems odd and this menu is not much larger than ST view menu either.
