### ISSUE TITLE
Provide different sorting for "Source control providers" view

### ISSUE THREAD

**Issue by benlowry** [microsoft/vscode#97411]
When working in a folder that has multiple repositories, like a folder containing a Github org's projects, there are two features that would improve the UI:

- ~~allow the box containing the repositories to resize, it's fixed at the moment with space for 10 repositories after that you have to scroll~~
- sort the repositories by name, this has been mentioned #42850 but nothing happened and the current sorting makes it slow to find repositories when you have to scroll and they're not ordered alphabetically

**Comment by joaomoreno** [comment]
> allow the box containing the repositories to resize, it's fixed at the moment with space for 10 repositories after that you have to scroll

You can change `scm.providers.visible` to 0.

**Comment by lawga** [comment]
@joaomoreno scm.providers.visible is no longer available, how do we set this option now?

**Comment by joaomoreno** [comment]
This is now gone, and needs rethinking in the new view.
