### ISSUE TITLE
Support fold regions for lambda without block

### ISSUE THREAD

**Issue by xiaoxiangmoe** [microsoft/vscode#97415]
```ts
const fooBar$ = pageList$.pipe(
  map(pageList =>
    pageList.map(
      page =>
        page.pageConfig.find(
          config =>
            config.key.orgId === KeyOrgId.MyOrg &&
            config.key.Id === KeytId.MyKey,
        ).data ?? {},
    ),
  ),
  shareReplay(1),
)
```

This TypeScript code can't fold unless we change all `x=>y` to `x=>{ return y; }`

**Comment by aeschli** [comment]
That's TypeScript, I assume.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
