### ISSUE TITLE
ampersand in regex search buggy [\d-&]

### ISSUE THREAD

**Issue by rayfoss** [microsoft/vscode#97417]
- VSCode Version: 1.45.0
- OS Version: Windows 10

Steps to Reproduce:

1.type & into a document
2.search for it with regex `[\d-&]`

This is valid JavaScript regex, but vscode flags it as invalid syntax. Range out of order in character class

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rayfoss** [comment]
Looks like browser JavaScript is wrong and the regex engine in vscode is right

**Comment by ArturoDent** [comment]
regex101 and 3 or 4 other online regex testers had no problem with `[\d-&]`.  They do not treat it as a character range - should they?  Of course, better would be `[-\d&]` to avoid confusion, but I think vscode is wrong in this case.

**Comment by rayfoss** [comment]
I thought it was just a backward compatible thing... i'm for doing whatever works on the web. Regex performance on the sort of text documents we deal with should not be a big issue

**Comment by alexdima** [comment]
We create our RegExp with the following:

`new RegExp('...', 'gu')`

Using the `u` modifier makes the validation of the regex more strict, so that error is thrown by the JS regex engine, not by us. The solution is to escape the `-` i.e. `[\d\-&]`
