### ISSUE TITLE
Application frequently stalling for ~10 seconds

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#97420]
Issue Type: <b>Bug</b>

I've been periodically encountering an issue where VS Code hangs for about 10 seconds after every action I perform. This includes modifying text, opening menu bar, and saving a file.

When this happens, one of the child processes is pegging on of my CPU cores at 100%. This is the command line for the sub process (excuse typos, I couldn't find a way to copy this and had to transcribe it manually)
```
"C:\Program Files\Microsoft VS Code\Code.exe"
--type=renderer
--disable-color-correct-rendering
--field-trial-handle=...
--disable-features=LayoutNG,PictureInPicture,SpareEndererForSitePerProcess
--lang=en-US
--standard-schemes
--secure-schemes=vscode-resource
--bypassscp-schemes
--cors-schemes=vscode-resource
--fetch-schemes=vscode-resource
--service-worker-schemes
--app-user-model-id=Microsoft.VisualStudioCode
--app-path="C:\Program Files\Microsoft VS Code\resources\app"
--node-integration
--webview-tag
--no-sandbox
--no-zygote
--background-color=#212121
--device-sacle-factor=1
--num-raster-threads=4
--enable-main-frame-before-activation
--service-request-channel-token=... renderer-client-id=9
--no-v8-untrusted-code-mitigations
--mojo-platform-channel-handle=2664/prefetch:1
```

Here's a screenshot from Very Sleepy during one of the hangs
![image](https://user-images.githubusercontent.com/484784/81507905-50c44f80-92b5-11ea-8b87-a52476ad6126.png)

I've also created a dump file when the application was hung (~640 MB) if that's useful. I can collect additional data if necessary as well.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
auto-align|bla|0.0.13
graphviz-preview|EFa|1.3.3
vsc-material-theme-icons|equ|1.1.4
vsc-space-block-jumper|jmf|1.2.2
Lua|key|0.0.9
remote-containers|ms-|0.117.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.28.0-insiders3
code-settings-sync|Sha|3.4.3
shader|sle|1.1.4
dot|Ste|0.0.1
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
