### ISSUE TITLE
Terminal links includes trailing brace for braced hyperlinks

### ISSUE THREAD

**Issue by nschonni** [microsoft/vscode#97427]
Issue Type: <b>Bug</b>

Installing from nodejs/nodejs.dev, there is a warnin around @babel/polyfill. 
```
npm WARN deprecated @babel/polyfill@7.8.7: � This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
```
The autolint in the terminal highlights `https://babeljs.io/docs/en/babel-polyfill)` including the trailing `)`, making the link fail

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz (24 x 2933)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.99GB (14.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.35.1
vscode-eslint|dba|2.1.5
docs-article-templates|doc|0.2.8
docs-authoring-pack|doc|0.1.8
docs-images|doc|0.0.8
docs-linting|doc|0.0.3
docs-markdown|doc|0.2.68
docs-metadata|doc|1.0.4
docs-preview|doc|0.3.49
docs-yaml|doc|0.2.5
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.6.0
vscode-codeql|Git|1.1.3
vscode-pull-request-github|Git|0.16.0
vscode-test-explorer|hbe|2.18.0
rest-client|hum|0.23.2
bats|jet|0.1.7
vale|lun|0.6.0
vscode-github-actions|me-|3.0.0
azure-pipelines|ms-|1.165.1
vscode-apimanagement|ms-|0.1.3
vscode-docker|ms-|1.1.0
python|ms-|2020.4.76186
remote-wsl|ms-|0.44.2
azure-account|ms-|0.8.11
cpptools|ms-|0.27.1
Go|ms-|0.14.1
powershell|ms-|2020.4.0
vscode-typescript-tslint-plugin|ms-|1.2.3
team|ms-|1.161.0
vscode-yaml|red|0.7.2
code-spell-checker|str|1.8.0
highlight-trailing-white-spaces|yba|0.0.2

</details>

**Comment by Tyriar** [comment]
Should be fixed if you jump onto the new links: "terminal.integrated.experimentalLinkProvider": true
