### ISSUE TITLE
Debian package for Code-Insiders is not disabling hardware acceleration.

### ISSUE THREAD

**Issue by tylertownsend** [microsoft/vscode#97422]
- VSCode Version: 1.46-insider
- OS Version: Linux x64 4.15.0-99-generic (Ubuntu 18.04.04 LTS)

Steps to Reproduce:

1. Open Insiders
2. Install Synthwave84 extension (v0.1.5)
3. Open argv.json and set `"disable-hardware-acceleration": true`
4. Close out of VSCode-Insiders and reopen.

Does this issue occur when all extensions are disabled?: No

Notes
 - There seems to be a bit of latency with extensions disabled (debian package).
 - Installing the snap version of insiders and following the same steps shows that the hardware acceleration is disabled as seen in the table below.
 - The visual indicator is the white space in the editor.

| Snap   |     Debian      |
|----------|:-------------:|
| ![snap-insiders](https://user-images.githubusercontent.com/24819293/81508120-fe842e00-92b6-11ea-9c04-1310b7eda0af.png)|![debian-insiders](https://user-images.githubusercontent.com/24819293/81508169-65a1e280-92b7-11ea-863e-a7d18ea82aca.png)|
|Version: 1.46.0-insider|Version: 1.46.0-insider|
|Commit: d487078dc7fc1c276657cadb61b4f63833a8df55|Commit: d487078dc7fc1c276657cadb61b4f63833a8df55|
|Date: 2020-05-07T16:36:39.681Z|Date: 2020-05-07T16:36:39.681Z|
|Electron: 7.2.4|Electron: 7.2.4|
|Chrome: 78.0.3904.130|Chrome: 78.0.3904.130|
|Node.js: 12.8.1| Node.js: 12.8.1|
|V8: 7.8.279.23-electron.0|V8: 7.8.279.23-electron.0|
|OS: Linux x64 4.15.0-99-generic snap| OS: Linux x64 4.15.0-99-generic|

**Comment by deepak1556** [comment]
Thanks for the details! I am unable to repro this on my parallels vm. Can you try setting

`"disable-color-correct-rendering":  false`


> Installing the snap version of insiders and following the same steps shows that the hardware acceleration is disabled as seen in the table below.

How are you confirming hw acceleration is disabled ?

**Comment by tylertownsend** [comment]
### Disabled Hardware Explanation
The vim extension installed was causing some latency issues. I would type and after a second or 2 the text would follow. I found out that disabling the hw acceleration could reduce the latency.

However, I also noticed with another extension, the SynthWave 84' theme, that color rendering was also changed. This is from my regular **VSCode**:

| Hardware Enabled  | Hardware Disabled |
|----------|:-------------:|
|![Screenshot from 2020-05-14 12-11-39](https://user-images.githubusercontent.com/24819293/81975879-8b432a80-95dc-11ea-9bc4-592d8d7809c1.png)|![Screenshot from 2020-05-14 12-13-31](https://user-images.githubusercontent.com/24819293/81975891-8e3e1b00-95dc-11ea-9ede-4f23d8d100f1.png)|

- Version: 1.45.0
- Commit: d69a79b73808559a91206d73d7717ff5f798f23c
- Date: 2020-05-07T16:10:24.511Z
- Electron: 7.2.4
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Linux x64 4.15.0-99-generic

### Disabling Color Correct Rendering
With your recommendation to set `"disable-color-correct-rendering": false`, this was the result in **VSCode-Insiders**:
![Screenshot from 2020-05-14 12-30-47](https://user-images.githubusercontent.com/24819293/81977395-d1998900-95de-11ea-802b-bb5a5d34ef56.png)

It still shows this weird color rendering in the editor.

**Comment by deepak1556** [comment]
Thanks for the data, we should take a JS profile to see whats causing the latency with vim extension. I am not familiar with the extension itself, would be better to raise an issue with the extension and if they narrow it down to an issue in VSCode, we can continue from there.

But as for the color rendering, can you see if things are better with our exploration https://github.com/microsoft/vscode/issues/94074#issuecomment-607079209 ?
