### ISSUE TITLE
Markdown in hover widget rendered poorly

### ISSUE THREAD

**Issue by inazarenko** [microsoft/vscode#97429]
Issue Type: <b>Feature Request</b>

Some extensions use markdown in the text they provide for the hover-over widget for identifiers. E.g. vscode-clangd produced the following example:

````markdown
### function `EquivToProto`

---
→ `::testing::PolymorphicMatcher<internal::ProtoStringMatcher>`

Parameters:

- `const std::string & x`
---
```cpp
// In namespace protobuf_matchers
inline ::testing::PolymorphicMatcher<internal::ProtoStringMatcher> EquivToProto(
```

````

The hover widget uses editor font size (in my case, 18) for the entire contents of the widget. However, it only sets the editor font (in my case, Consolas) for the code fragment in the last section. The first two sections are rendered using default Mac fonts (i.e. Monaco for monospace sections), resulting in too-large type. Those fixed-width sections also look inconsistent with the editor look.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 19.4.0
Remote OS version: Linux x64 4.15.0-96-generic

<img width="1078" alt="Screen Shot 2020-05-10 at 2 09 06 PM" src="https://user-images.githubusercontent.com/12076208/81510853-f84b7d00-92c9-11ea-89f3-c88414d40e27.png">

**Comment by Tyriar** [comment]
@mjbvz please pass it on if you're not the right person for this. I don't have any experience with how language extensions use the hover.

**Comment by mjbvz** [comment]
I believe this is by design: #69970

Custom editor fonts often end up looking out of place when rendered inline next to our normal UI text. However it does still make sense to use your editor font code blocks since these are rendered as their own block elements
