### ISSUE TITLE
Disable autocomplete with enter in debug console

### ISSUE THREAD

**Issue by Moeyoo** [microsoft/vscode#97439]
- VSCode Version: 1.44.2
- OS Version: Windows 10

### Please reopen issue https://github.com/microsoft/vscode/issues/45156
**This bug affects multiple OS and multi languages. It makes debug console almost unusable. Please consider fix it.**

#### Other reports:
https://github.com/Microsoft/vscode/issues/60877
https://github.com/microsoft/vscode-python/issues/7113

**Comment by isidorn** [comment]
We can reopen the original issue, thus closing this one
