### ISSUE TITLE
[terminal] Copy action enabled on empty selection, but copy doesn't work

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#9743]
Testing #9723

Linux, Elementary OS
- Open the terminal
- select some text in the terminal, use copy from the context menu, paste the text: works
- set the focus to the cursor position (no selection), use copy from the context menu, paste the text: still pastes the previous text

-> Maybe the copy menu should not be present (or disabled) if the selection is empty

**Comment by stevencl** [comment]
Another option would be to copy the whole line if there is no selection like we do in the editor?
