### ISSUE TITLE
Inserting code snippet causes auto scroll to placeholder / top line of snippet

### ISSUE THREAD

**Issue by infixint943** [microsoft/vscode#97430]
Issue Type: <b>Bug</b>

Like what the heading says, inserting a code snippet anywhere in the code file causes an autoscroll. This is a slight inconvenience, as while inserting snippets, viewing code above it is desirable, causing us to rescroll into view. So adding an option to revert to the functionality in the stable release would be preferred

VS Code version: Code - Insiders 1.46.0-insider (d487078dc7fc1c276657cadb61b4f63833a8df55, 2020-05-07T16:36:39.681Z)
OS version: Linux x64 5.4.38-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 1744)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|5.71GB (1.21GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|deepin|
|XDG_CURRENT_DESKTOP|Deepin|
|XDG_SESSION_DESKTOP|deepin|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.27.1
Go|ms-|0.14.1
material-icon-theme|PKi|4.1.0
material-theme|zhu|3.5.0

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Yeah - that's a regression from a recent change to keep the position stable when additional edits are inserted...

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/94173

**Comment by jrieken** [comment]
fixed via c4e781b

**Comment by infixint943** [comment]
Yep, it works fine now.
Thanks a lot!
