### ISSUE TITLE
升级到1.45.0版本，网络有代理，输入账号、密码登不成功

### ISSUE THREAD

**Issue by Daiyichen** [microsoft/vscode#97435]
升级到1.45.0版本，网络有代理，输入账号、密码登不成功

**Comment by God512** [comment]
I also find this problem after upgrading to 1.45.0.

In previous version, after launching vs code, a window is popped. In this window, I can input username and password for authentication of proxy and press `OK` button. And then this window is closed. vs code can connect to internet via proxy.  
But for 1.45.0, I also can get this window, but window isn't closed after input username/password and  press `OK` button.

**Comment by gegertyson1314** [comment]
Our company also encountered such problems. Now we can't work normally.

**Comment by Barry-SH** [comment]
Whether is there a workaround way to make proxy work well ?

**Comment by gegertyson1314** [comment]
We can only work offline......

**Comment by Barry-SH** [comment]
In addition, I found this issue on Ubuntu 20.04.  
In my window environment, I not find this issue since proxy doesn't need username/password.

**Comment by chrmarti** [comment]
Workaround if you cannot revert to 1.44: https://github.com/microsoft/vscode/issues/97199#issuecomment-626002254

/duplicate https://github.com/microsoft/vscode/issues/97199

**Comment by Barry-SH** [comment]
@chrmarti 

Thank you. Now it works well.
