### ISSUE TITLE
Objects properties in React Native are all suffixed with a '?'

### ISSUE THREAD

**Issue by jshaolin** [microsoft/vscode#97436]
- VSCode Version: 1.45.0
- OS Version: Windows 10 Home Edition 1809

- Dump from VS Code About: 
Version: 1.45.0 (user setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Just upgrade to 1.45.0
2. Create a stylesheet using StyleSheet and when autocomplete shows up you'll see the available style options like for instance **width** but saying **width?**.

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
It means optional properties.
