### ISSUE TITLE
Drag tab to start a new window

### ISSUE THREAD

**Issue by johnzjq** [microsoft/vscode#97437]
Issue Type: <b>Feature Request</b>

As a developer, I would like to drag a tab to anywhere out of the focus of vscode to start a new window, so that I could be able to move the new window to another virtual desktop

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

**Comment by kanlukasz** [comment]
Sounds like https://github.com/microsoft/vscode/issues/10121
