### ISSUE TITLE
Copying a long value from debug watch results in pasting partial value

### ISSUE THREAD

**Issue by doronAtuar** [microsoft/vscode#97444]
- Version: 1.45.0
- Commit: d69a79b73808559a91206d73d7717ff5f798f23c
- Date: 2020-05-07T15:57:33.467Z
- Electron: 7.2.4
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Darwin x64 18.7.0

For me it reproduced with C++ 
But it probably occurs in other languages as well, haven't verified that.
 
Steps to Reproduce:
1. Start a debugging session
2. add an expression that has a long value to watch
![Screen Shot 2020-05-11 at 8 49 26](https://user-images.githubusercontent.com/6897301/81528088-92600380-9364-11ea-9017-deda24d06901.png)
3. Copy value
4. paste it somewhere in a text area
5. the pasted text appears is limited and ends with '...'
![Screen Shot 2020-05-11 at 8 50 33](https://user-images.githubusercontent.com/6897301/81528097-95f38a80-9364-11ea-8bc9-4e66f93b92f3.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Please file this against the C++ extension and mention the following:
VS COde sents the `clipboard` context when copying. Their extension should set the capability `supportsClipboardContext` and respect the clipboard context by evaluation the full thing.

**Comment by WardenGnaw** [comment]
@isidorn 
In the EvaluateRequest with `clipboard` as the context, it seems like the expression is set to the value, not the expression. Is this expected?

![image](https://user-images.githubusercontent.com/3953714/81997459-a7f35880-9604-11ea-9644-c77d7f9e766b.png)

```
{"command":"evaluate",
"arguments":{
"expression":"\"abcdefghijklmnopqrstuvwxyz0abcdefghijklmnopqrstuvwxyz1abcdefghijklmnopqrstuvwxyz2abcdefghijklmnopqrstuvwxyz3abcdefghijklmnopqrstuvwxyz4abcdefghijklmnopqrstuvwxyz5abcdefghijklmnopqrstuvwxyz6abcdefghijk\"...","
   frameId":1000,
   "context":"clipboard"
},
"type":"request",
"seq":25}
```

**Comment by isidorn** [comment]
@WardenGnaw yeah this is how we implemented it here
https://github.com/microsoft/vscode/blob/04080683fef61d210785cfca9538d4ea37c3fa3d/src/vs/workbench/contrib/debug/browser/watchExpressionsView.ts#L192

Maybe not the best when you do it on a top level wath expression.
We could fix it to make the CopyValue handle both Variable and Expression. But this might be fine for now.

**Comment by WardenGnaw** [comment]
Hmm. In the C/C++ debugger, it defaults to displaying up to 200 characters. So the value we would get when stopped, would be the truncated 200 limited value.

I was expecting when a user selects `Copy Value`, an EvaluateRequest would have its expression field set to the original expression (in the image above it would be "str") so we can re-query the debugger to give the full value. 

We would do so by noticing it was a ClipboardContext. Tell the debugger to have unlimited display when evaluating a variable, evaluate a variable, reset the display back to the default and return the full display in the response.

**Comment by isidorn** [comment]
@WardenGnaw you are correct, I have pushed de3e5a4bf4 to tackle this.
Please try it out with vscode insiders from Tuesday and let us know how it works for you.
I have also created this follow up isse for js-debug https://github.com/microsoft/vscode-js-debug/issues/476

**Comment by WardenGnaw** [comment]
@isidorn Sorry for the delay, I tested this out and the expression of the evaluate request is what we expect, the variable to evaluate. 

Thanks you again!

**Comment by isidorn** [comment]
@WardenGnaw thanks for letting us know!
