### ISSUE TITLE
Test JSON intellisense improvements

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#9744]
- [x] @isidorn os x

In JSON documents that have a schema associated (e.g. package.json, settings.json) I added suggestions if we only know the type of a property, but don't have any defaults or enums in the schema: New object, new array, new string....
The goal is to avoid the textual proposals that are (IMO) confusing.
- test that the proposals show up
- test that they apply well (enter template mode)
- test that they don't confuse

In JSON documents that have no schema associated:
- add a completion proposal for $schema (top level of an object)
In JSON documents that have schema or no schema associated:
- proposals for $schema values

**Comment by isidorn** [comment]
@aeschli is testing on just one platform enough? Maybe I do os x and you assign someone from redmond for another platform?

**Comment by aeschli** [comment]
@isidorn One platform is enough

**Comment by isidorn** [comment]
@aeschli please clarify and elaborate what to do for json documents hat have no schema associated

**Comment by aeschli** [comment]
@isidorn All that has changed is that you get a proposal for $schema. Using that, you can select a schema and get more useful proposal (without a schema there's not much help)
```
{
   |code assist here
}
```

**Comment by isidorn** [comment]
Feature looks good, my biggest concern is that as a user it is always a surprise what will I get for suggestions inside a json file - especaily if I am not familiar with how json schemas work.
