### ISSUE TITLE
Restore preferences from remote backups

### ISSUE THREAD

**Issue by texastoland** [microsoft/vscode#97443]
I accidentally rimrafed my `.vscode-insiders` directory with all my extensions. I found the backup but I can't do anything with it. There's no restore button, context menu item, action in the command palette, mention in the [official doc](https://code.visualstudio.com/docs/editor/settings-sync), or previous issues here. The CLI can't even consume the JSON file. I'm going write something with grep but I'm confused how the backups are intended to be used.

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/93960

**Comment by texastoland** [comment]
My workaround was:

```shell
cat extensions.json |
  jq '.[]
      .identifier|select(.uuid)
      .id        |select(test("^ms-vscode.")|not)' |
  xargs -n1 code-insiders --install-extension
```

**Comment by texastoland** [comment]
I previously saw the screenshot and still don't understand how to sync. I haven't been able to make it work on Insiders either. I think this needs a UX review because I can't find it even as a user who's already familiar with the particular feature.

**Comment by texastoland** [comment]
@sandy081 I finally clicked the cloud icon. It's a little unintuitive. Could I request it be added to the context menu for the file too?
