### ISSUE TITLE
 Cannot read property 'getModelColumnOfViewPosition' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#97449]
Issue Id: <b>0ea181d1-0d98-457f-645a-79a45f46e8a1</b><br /><br />*Versions* <br />- 1.45.0<br />-  d4b8ec9da3bf1061a948fbb1b0d9d3db750cc79f<br />-  fd5d9a30259bb2bebab3e62dfd8315c2e1b27744<br />-  ece7aaee861d7261a728d52ce436c667030ce17d<br />-  a0fe37870c42e0704a492cdc6b8550b4cf23f63c<br />*Stack* <br />TypeError: Cannot read property 'getModelColumnOfViewPosition' of undefined<br />[/vs/editor/common/viewModel/splitLinesCollection.ts#870:42 (convertViewPositionToModelPosition)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/common/viewModel/splitLinesCollection.ts#L870:42 (convertViewPositionToModelPosition))<br />[/vs/editor/common/viewModel/splitLinesCollection.ts#149:21 (convertViewPositionToModelPosition)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/common/viewModel/splitLinesCollection.ts#L149:21 (convertViewPositionToModelPosition))<br />[/vs/editor/browser/viewParts/lineNumbers/lineNumbers.ts#69:75 (onCursorStateChanged)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/browser/viewParts/lineNumbers/lineNumbers.ts#L69:75 (onCursorStateChanged))<br />[/vs/editor/common/viewModel/viewEventHandler.ts#112:14 (handleEvents)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/common/viewModel/viewEventHandler.ts#L112:14 (handleEvents))<br />[/vs/editor/common/view/viewEventDispatcher.ts#88:21 (_doConsumeQueue)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/common/view/viewEventDispatcher.ts#L88:21 (_doConsumeQueue))<br />[/vs/editor/common/view/viewEventDispatcher.ts#71:9 (func)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/common/view/viewEventDispatcher.ts#L71:9 (func))<br />[/vs/editor/browser/view/viewImpl.ts#573:9 (safeInvokeNoArg)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/browser/view/viewImpl.ts#L573:9 (safeInvokeNoArg))<br />[/vs/editor/browser/view/viewImpl.ts#360:12 (_renderOnce)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/browser/view/viewImpl.ts#L360:12 (_renderOnce))<br />[/vs/editor/browser/view/viewImpl.ts#112:80 (_eventHandlerGateKeeper)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/browser/view/viewImpl.ts#L112:80 (_eventHandlerGateKeeper))<br />[/vs/editor/common/view/viewEventDispatcher.ts#67:7](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/common/view/viewEventDispatcher.ts#L67:7)<br />    at t.ViewEventDispatcher.emitMany (out/vs/workbench/workbench.desktop.ma<br />

**Comment by alexdima** [comment]
Fixed with the refactorings done for #97447
