### ISSUE TITLE
 Cannot read property 'createOnigString' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#97454]
Issue Id: <b>268e0e4b-cd04-d2ab-01d0-2d55c0c80a55</b><br /><br />*Versions* <br />- 1.45.0<br />*Stack* <br />TypeError: Cannot read property 'createOnigString' of undefined<br />    at Grammar.createOnigString (\node_modules.asar\vscode-textmate\release\main.js:2601:30)<br />    at Grammar._tokenize (\node_modules.asar\vscode-textmate\release\main.js:2697:33)<br />    at Grammar.tokenizeLine2 (\node_modules.asar\vscode-textmate\release\main.js:2670:22)<br />[/vs/workbench/contrib/preferences/browser/settingsEditor2.ts#508:91 (controlsElement)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts#L508:91 (controlsElement))<br />[/vs/workbench/contrib/preferences/browser/settingsEditor2.ts#478:54 (_tokensCount)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts#L478:54 (_tokensCount))<br />[/vs/editor/common/core/lineTokens.ts#189:76 ([object Object])](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/common/core/lineTokens.ts#L189:76 ([object Object]))<br />[/vs/editor/common/core/lineTokens.ts#90:8](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/common/core/lineTokens.ts#L90:8)<br />[/vs/editor/common/core/lineTokens.ts#64:2 (LanguageFeatureRegistry)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/common/core/lineTokens.ts#L64:2 (LanguageFeatureRegistry))<br />[/vs/editor/common/modes.ts#1768:41](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/common/modes.ts#L1768:41)<br />[/vs/editor/common/modes.ts#1753:59](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/common/modes.ts#L1753:59)<br />    at processImmediate (<REDACTED: user-file-path>:439:21)<br />

**Comment by alexdima** [comment]
I don't see how this could happen.
