### ISSUE TITLE
Index signature parameter does not accept redefined valid types

### ISSUE THREAD

**Issue by danibishop** [Microsoft/vscode#9745]
- VSCode Version: 1.3.0
- OS Version: Windows 10 Pro - 64 bits

Steps to Reproduce:

1. Create an alias type for string
2. Create an index signature parameter using the new type

This makes the spellcheck fail in the parameter name for the index because "An index signature parameter type must be 'string' or 'number'"

`
var d1: { [id: string]: {}; } = {} // Spellcheck Ok

type otherString = string;

var d2: { [id: otherString]: {}; } = {} // Spellcheck complains about 'id'
`

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#10130
