### ISSUE TITLE
 Cannot read property 'startLineNumber' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#97451]
Issue Id: <b>7a80640b-3b2e-d7d7-a3ab-e2f49e302e9a</b><br /><br />*Versions* <br />- 1.45.0<br />-  ece7aaee861d7261a728d52ce436c667030ce17d<br />*Stack* <br />TypeError: Cannot read property 'startLineNumber' of undefined<br />[/vs/editor/common/core/range.ts#323:25 (collapseToStart)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/common/core/range.ts#L323:25 (collapseToStart))<br />[/vs/editor/contrib/gotoSymbol/goToCommands.ts#169:21 (_openReference)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/contrib/gotoSymbol/goToCommands.ts#L169:21 (_openReference))<br />[/vs/editor/contrib/gotoSymbol/goToCommands.ts#140:35 (_onResult)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/contrib/gotoSymbol/goToCommands.ts#L140:35 (_onResult))<br />[/vs/editor/contrib/gotoSymbol/goToCommands.ts#109:16](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/editor/contrib/gotoSymbol/goToCommands.ts#L109:16)<br />    at processTicksAndRejections (internal/process/task_queues.js:85:5)<br />

**Comment by alexdima** [comment]
It looks like the range is `undefined` in `goToCommands.ts`
