### ISSUE TITLE
 Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#97459]
Issue Id: <b>de429439-c5d5-13b2-ed17-cf9039cae2ae</b><br /><br />*Versions* <br />- 1.45.0<br />*Stack* <br />TypeError: Cannot read property 'body' of undefined<br />[/vs/workbench/contrib/debug/browser/debugSession.ts#595:15](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/workbench/contrib/debug/browser/debugSession.ts#L595:15)<br />    at processTicksAndRejections (internal/process/task_queues.js:85:5)<br />

**Comment by bpasero** [comment]
Just a thought: with strict null checks working properly, I wonder why methods such as https://github.com/microsoft/vscode/blob/5d37bb76cd1c583332fb3f350f064b07b029e92a/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L425 are not typed in a way that you account for `undefined` or `null` values. Seems like this should be handled on the level of the language?

**Comment by bpasero** [comment]
E.g. in a way how https://github.com/microsoft/vscode/commit/4fee76e61ba1b0a3df9fb9ce7a984c487a80aba4 was fixed

**Comment by isidorn** [comment]
Thought about that fix actually. The problem with that is that I would have to change the signature of all the rawDebugSession methods and this only happens in a weird corner case when it is triggered on a debug session shutdown.
So yes I agree with you we should fix it like that. I would just wait for potenitally more corner case, as for just one I would not change the whole world.
