### ISSUE TITLE
 Uncaught Error: Cannot read property 'reprocess' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#97453]
Issue Id: <b>062d2ec3-7ca8-2a57-9c42-a30f669cd58f</b><br /><br />*Versions* <br />- 1.45.0<br />*Stack* <br />Error: Cannot read property 'reprocess' of undefined<br /><br />TypeError: Cannot read property 'reprocess' of undefined<br />[/vs/workbench/services/configuration/browser/configurationService.ts#506:114 (onDefaultConfigurationChanged)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/workbench/services/configuration/browser/configurationService.ts#L506:114 (onDefaultConfigurationChanged))<br />[/vs/workbench/services/configuration/browser/configurationService.ts#98:136 (call)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/workbench/services/configuration/browser/configurationService.ts#L98:136 (call))<br />[/vs/base/common/event.ts#587:15 (fire)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/base/common/event.ts#L587:15 (fire))<br />[/vs/platform/configuration/common/configurationRegistry.ts#197:33 (registerConfigurations)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/platform/configuration/common/configurationRegistry.ts#L197:33 (registerConfigurations))<br />[/vs/platform/configuration/common/configurationRegistry.ts#184:7 (registerConfiguration)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/platform/configuration/common/configurationRegistry.ts#L184:7 (registerConfiguration))<br />[/vs/workbench/contrib/externalTerminal/node/externalTerminalService.ts#372:23](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/workbench/contrib/externalTerminal/node/externalTerminalService.ts#L372:23)<br />[/vs/base/common/errors.ts#26:11](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/base/common/errors.ts#L26:11)<br />

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/79809
