### ISSUE TITLE
Window oversized vertically

### ISSUE THREAD

**Issue by ziad-akiki** [microsoft/vscode#97460]
Issue Type: <b>Bug</b>

My setup includes a 200% scale - 3000x2000 screen resolution and a 100% scale FHD monitor (Extended mode). 
When opening VS Code on the FHD monitor (Maximized), the window is oversized vertically, the status bar is trimmed at the bottom and the title bar above is trimmed from the top.

![Bottom screenshot](https://user-images.githubusercontent.com/40595927/81528823-2f6f6c00-9366-11ea-8745-ed40f79c1def.png)

![Top screenshot](https://user-images.githubusercontent.com/40595927/81528868-48781d00-9366-11ea-9050-983a5117d64f.png)

I also have a lower res, 100% scale laptop. When connected to the same monitor, I don't experience this issue with VS Code. Note as well that the issue does not happen on the 3000x2000 laptop monitor.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.29GB free)|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-intelephense-client|bme|1.3.11
vscode-eslint|dba|2.1.1
gitlens|eam|10.2.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
vscode-solution-explorer|fer|0.3.9
vscode-pull-request-github|Git|0.16.0
beautify|Hoo|1.5.0
sftp|lix|1.12.9
regionfolder|map|1.0.10
vscode-azureappservice|ms-|0.16.5
csharp|ms-|1.21.15
mssql|ms-|1.9.0
python|ms-|2020.3.71659
azure-account|ms-|0.8.11
azurecli|ms-|0.5.0
cpptools|ms-|0.27.1
debugger-for-chrome|msj|4.12.6
vetur|oct|0.24.0
java|red|0.58.0
vscode-xml|red|0.11.0
format-html-in-php|rif|1.6.2
vscodeintellicode|Vis|1.2.6
vscode-arduino|vsc|0.3.0
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.2

</details>

**Comment by deepak1556** [comment]
Thanks for the details provided, this issue is being tracked under https://github.com/microsoft/vscode/issues/85592 , please follow that issue for updates.
