### ISSUE TITLE
Smart text highlighting in log files

### ISSUE THREAD

**Issue by LWChris** [microsoft/vscode#97479]
Issue Type: <b>Bug</b>

It appears to me VS Code tries to improve the highlighting even of raw text files like log files. For example, it seems to make timestamps green and numbers with two or more digits blue.

I like this feature, but it should either exclude hexadecimal numbers or learn to highlight them consistently altogehter. The current scheme makes logs that contain MAC addresses very difficult to read:

`89:A1:23:45:AB:C0` has `89` in blue, `1:23:45` in green and the rest in white.

VS Code version: Code - Insiders 1.45.0-insider (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-06T09:26:27.927Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by aeschli** [comment]
Highlighting comes from the log grammar: https://github.com/emilast/vscode-logfile-highlighter/blob/master/syntaxes/log.tmLanguage

**Comment by alexr00** [comment]
Moved to owning repo
