### ISSUE TITLE
Task started with vscode.tasks.executeTask doesn't generate any completition notification if dependency task fails, preventing its execution.

### ISSUE THREAD

**Issue by VMinute** [microsoft/vscode#97475]
Issue Type: <b>Bug</b>

In my extension, I need to provide users a flexible way to perform some operation (copy build output to a local folder that will be then deployed to a device). Since the way to do it is heavily dependent on language/tools used I decided to let user define a task with a specific name that would be executed by the extension. Everything works fine when a single task is defined, things start to get messy when task has some dependencies (generated using dependson). Dependent tasks are correctly executed, but if one of them fails there is no way to detect the issue from the callbacks provided by vscode.tasks.

To reproduce the issue:

1. Create a task "A" and a task "B" with a dependency:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "B",
            "command": "true",
            "type": "shell",
            "args": [],
        },
        {
            "label": "A",
            "command": "true",
            "type": "shell",
            "args": [],
            "dependsOn": [
                "B"
            ]
        },
    ]
}
```
2. in an extension find a task named "A" and execute it, waiting for its completition:
```
// load task list
        var tasks = await vscode.tasks.fetchTasks();
        var taskA: vscode.Task | undefined = undefined;

        // search for a task named "A"
        for (var t of tasks) {
            if (t.name === "A") {
                taskA = t;
                break;
            }
        }

        if (taskA === undefined) {
            vscode.window.showErrorMessage("Can't find a task named A.");
            return;
        }

        // emitter used to detect task completition
        var emitter = new EventEmitter();

        // the process event arrives before the generic terminate one (checked inside vscode sources)
        vscode.tasks.onDidStartTaskProcess(e => {
            console.log("Task " + e.execution.task.name + " started.")
        });

        vscode.tasks.onDidEndTaskProcess(e => {
            console.log("Task process " + e.execution.task.name + " terminated.")
            if (e.execution.task.name === "A") {
                emitter.emit("terminated", e.exitCode);
            }
        });
        vscode.tasks.onDidEndTask(e => {
            console.log("Task process " + e.execution.task.name + " terminated.")
            if (e.execution.task.name === "A") {
                emitter.emit("terminated", -1);
            }
        });

        try {
            var execution = await vscode.tasks.executeTask(taskA);
        }
        catch (e) {
            console.log("Task execution generated an exception.");
            return null;
        }

        var code = await new Promise<Number>((resolve, reject) => {
            emitter.on("terminated", code => resolve(code));
        });

        vscode.window.showInformationMessage("Task A terminated with exit code " + code.toString());
```
3. when task A completes or fails (replace true with false in command to make it fail), the information message is correctly shown.
4. make task B fail by replacing "true" with "false".
5. In this case, completion of task A is never reported and message is not shown

Expected behavior would be that also completion of A would be notified via OnEndTask callback, to let the extension know that the task was "sort of" completed (even if not executed at all). For process/shell tasks having OnEndTask called with no call to OnEndTaskProcess matching call would mean that a dependency task has failed.

Otherwise, caller would have no way to detect such an issue and will wait forever.

I published a small sample extension:
https://github.com/VMinute/taskexecutionsample

The repo contains 3 subfolders with very simple task.json files to show the execution behavior (linux only):
- testokfolder - both task A and task B execution succeed, the user is notified
- testfailA - task B succeeds, task A fails, the user is notified
- testfailB - task B fails, task A is not executed, no notification

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 4.15.0-99-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2864)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.40GB (0.79GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|3.1.0
better-comments|aar|2.0.5
vscode-languagetool|ada|3.8.0
vscode-languagetool-en|ada|3.8.0
Bookmarks|ale|11.1.0
vscode-sqlite|ale|0.8.2
swagger-viewer|Arj|3.0.1
vagrant|bbe|0.5.0
vscode-svgviewer|css|2.0.0
python-snippets|cst|0.2.0
dart-code|Dar|3.10.1
flutter|Dar|3.10.1
vscode-markdownlint|Dav|0.35.1
xml|Dot|2.5.0
vscode-pandoc|Dou|0.0.8
dummyext2|dum|0.0.1
graphviz-preview|EFa|1.3.3
bitbake|Eug|1.1.2
vscode-reveal|evi|4.0.3
gitlab-workflow|fat|2.2.0
vscode-npm|fkn|3.3.0
pythonsnippets|frh|1.0.2
gc-excelviewer|Gra|2.1.34
svgeditor|hen|2.9.0
githd|hui|2.2.4
compareit|in4|0.0.2
vscode-graphviz|joa|0.0.6
vscode-sshfs|Kel|1.17.0
autoconf|mae|0.1.0
marp-vscode|mar|0.13.0
rainbow-csv|mec|1.7.0
vscode-docker|ms-|1.1.0
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-ssh-explorer|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.11
cmake-tools|ms-|1.3.1
cpptools|ms-|0.28.0-insiders
Go|ms-|0.14.1
vscode-typescript-tslint-plugin|ms-|1.2.3
easyzoom|Nab|0.1.0
autodocstring|njp|0.5.1
vscode-gn|npc|1.1.0
devicetree|plo|0.1.1
remote-vscode|raf|1.1.0
languagetool|ray|1.0.1
vscode-yaml|red|0.7.2
startanyshell|rem|0.3.1
wordcount|rid|0.1.33
LiveServer|rit|5.6.1
rust|rus|0.7.5
partial-diff|ryu|1.4.1
vscode-qt-for-python|sea|0.4.2
code-settings-sync|Sha|3.4.3
vscode-hexdump|sle|1.7.2
torizon|Tor|1.0.0
vscode-lldb|vad|1.5.0
vscodeintellicode|Vis|1.2.7
vscode-arduino|vsc|0.3.0
vscode-todo-highlight|way|1.0.4
zoombar-vscode|wra|1.2.1
markdown-pdf|yza|1.4.4

</details>

**Comment by VMinute** [comment]
I opened also a question on stackoverflow, in case there is a workaround that does not require changes to vscode.
https://stackoverflow.com/questions/61678941/how-to-detect-failure-of-task-execution-from-a-vscode-extension

**Comment by meganrogge** [comment]
Hi and thanks for the great repro steps - using your example repo, I am following the steps you said above - making task B fail by setting that to false. 

I do see a notification though related to the completion status of task A. 

It's possible some other fix has fixed this. Can you pls see if you can still repro this on insider's? I cannot.

https://user-images.githubusercontent.com/29464607/169109426-4c76ce4d-271f-43cf-af5d-0daee8953a12.mov

**Comment by meganrogge** [comment]
The logs for the above run look correct to me too:

![Screen Shot 2022-05-18 at 10 53 46 AM](https://user-images.githubusercontent.com/29464607/169109677-de2a0dfd-2a42-41fb-9e66-0f9e602329fa.png)
