### ISSUE TITLE
Git Pull From, when git.fetchOnPull=true, does nothing

### ISSUE THREAD

**Issue by FDiskas** [microsoft/vscode#97472]
Issue Type: <b>Bug</b>

Git pull from command does not works as acpected. I select this from Source controll view. And I select a branch (origin/develop) from dropdown menu. In OUTPUT I see only thous commands and no fetch from origin develop
```
> git pull --tags
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse MY_CURRENT_BRANCH
> git rev-parse --symbolic-full-name MY_CURRENT_BRANCH@{u}
> git rev-list --left-right MY_CURRENT_BRANCH...refs/remotes/origin/MY_CURRENT_BRANCH
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
```
I supose the folowing command to be executed
```> git pull origin develop```

VS Code version: Code - Insiders 1.46.0-insider (d487078dc7fc1c276657cadb61b4f63833a8df55, 2020-05-07T16:30:12.593Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
react-toolkit|Cod|1.1.23
workspace-archive|Cod|1.0.23
vscode-github|Kni|0.30.3
vscode-wakatime|Wak|4.0.0
Handlebars|and|0.4.1
snapshot-tools|asv|0.4.0
atlascode|atl|2.5.1
vscode-browser-preview|auc|0.6.7
color-info|bie|0.5.1
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
gitlens|eam|10.2.1
prettier-vscode|esb|4.5.0
restore-git-branch-tabs|gko|0.4.1
todo-tree|Gru|0.0.174
vscode-peacock|joh|3.7.0
intellij-idea-keybindings|k--|0.2.38
chat|kar|0.33.0
graphql-for-vscode|kum|1.15.3
vscode-regexp-preivew|Lul|1.0.0
syntax-project-pbxproj|mar|0.1.3
handlebars-formatter|mfe|1.0.0
vscode-docker|ms-|1.1.0
js-debug-companion|ms-|1.0.0
vsliveshare|ms-|1.0.2106
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.3.4
debugger-for-chrome|msj|4.12.6
vscode-css-navigation|puc|1.9.0
vscode-yaml|red|0.7.2
git-autoconfig|shy|0.0.1
mdx|sil|0.1.0
code-spell-checker|str|1.8.0
vscode-icons|vsc|10.1.1
quokka-vscode|Wal|1.0.289
vscode-webhint|web|1.5.5
material-theme|zhu|3.4.0

</details>

**Comment by joaomoreno** [comment]
Can you reproduce if you run with `code --disable-extensions`?

**Comment by FDiskas** [comment]
Yes it is reproducible. If I search in OUTPUT for `origin` or `develop` - no results.

**Comment by joaomoreno** [comment]
Can you please provide a [screen recording](https://gifcap.dev/)?

**Comment by FDiskas** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/468006/81933058-6c9d5d80-95f5-11ea-94b4-44854e73a7cf.gif)

**Comment by FDiskas** [comment]
And changes was not applied from origin/develop

**Comment by FDiskas** [comment]
only `git pull --tags` was executed, but I see in source code 
https://github.com/microsoft/vscode/blob/054c34282e4091bb2772a445bfa54249ee06d2c6/extensions/git/src/git.ts#L1571-L1574
That it should work :/

**Comment by joaomoreno** [comment]
Do you have `git.fetchOnPull` enabled?

**Comment by FDiskas** [comment]
It's was enabled - yes
![image](https://user-images.githubusercontent.com/468006/82306632-f79ca000-99c7-11ea-8352-03e40ef4acc7.png)

**Comment by mdasifhasan** [comment]
It seems its because when `git.fetchOnPull=true` it does not pass in the remote and branch to the pull function.
https://github.com/microsoft/vscode/blob/a537cb7370c70b2e6a9d30d917b4ddb58a8c666c/extensions/git/src/repository.ts#L1165-L1169

I can try fixing this issue if thats alright? This will be my first issue too.
