### ISSUE TITLE
Debug: do not rely on event being passed around into command

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#97470]
Extracted from https://github.com/microsoft/vscode/issues/97237

Debug contributes a menu entry such as:

https://github.com/microsoft/vscode/blob/6177de0c0f52b6977b5d2f2bdf9482620c4fd5c5/src/vs/workbench/contrib/debug/browser/debug.contribution.ts#L416-L423

Within it probes for an `event` which we no longer pass around: https://github.com/microsoft/vscode/blob/6177de0c0f52b6977b5d2f2bdf9482620c4fd5c5/src/vs/workbench/contrib/debug/browser/debugActions.ts#L108

A better way would be to register an `alt` command, such as:

```js
MenuRegistry.appendMenuItem(MenuId.MenubarDebugMenu, {
	group: '2_configuration',
	command: {
		id: ConfigureAction.ID,
		title: nls.localize({ key: 'miOpenConfigurations', comment: ['&& denotes a mnemonic'] }, "Open &&Configurations")
	},
	alt: {
		id: ConfigureActionOnSide.ID,
		title: nls.localize({ key: 'miOpenConfigurations', comment: ['&& denotes a mnemonic'] }, "Open &&Configurations On Side")
	},
	order: 1
});
```

This requires our menus to support `alt` which I think they do.

**Comment by isidorn** [comment]
@bpasero thanks for the suggestion, however currently the debug view title bar is not a menu, thus the solution you propose is not possible.
I have simply removed support to open the launch.json to the side. We might re-introduce it in the future once the users start complaining.

**Comment by bpasero** [comment]
@isidorn I think it is fine to remove the support, but curious how you can contribute to it like a menu if it is not a menu? where does it appear?

**Comment by isidorn** [comment]
@bpasero the top level main menu debug submenu.

![Screenshot 2020-05-11 at 11 33 12](https://user-images.githubusercontent.com/1926584/81546822-3785d680-937b-11ea-8418-f9fcc6eba2cd.png)

**Comment by bpasero** [comment]
@isidorn my understanding is that the menus support alternative commands. @sbatten can you verify?

**Comment by isidorn** [comment]
@bpasero my point was simply: it was not working for the main menu, it was only working for the debug title area which is not the menu.
So I would not make the change that it suddently only works in the Main Menu.
