### ISSUE TITLE
Terminal cursor shows some screen cheese

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#9747]
See attach screen capture

![screen shot 2016-07-26 at 10 43 38](https://cloud.githubusercontent.com/assets/1794099/17131481/eede60ba-531d-11e6-949c-ef358f9f9663.png)
ty

**Comment by Tyriar** [comment]
OS? Can't repro on Linux or Mac. Can you inspect the terminal to see what element it is if it's still happening?

**Comment by jrieken** [comment]
macOS, doesn't repo today...

**Comment by jrieken** [comment]
![screen shot 2016-07-27 at 15 59 05](https://cloud.githubusercontent.com/assets/1794099/17177729/18829562-5413-11e6-8344-a243695e673b.png)

When zooming in the becomes more obvious. My guess is that it's the default resize handle all textarea-element have on the mac

**Comment by Tyriar** [comment]
You don't have an IME or anything active do you? The text area is supposed to be off screen generally.

**Comment by jrieken** [comment]
No, nothing special... It only happens when the terminal has focus

**Comment by Tyriar** [comment]
While I can't reproduce it being visible, I do see why it's happening; the composition update function isn't checking whether a composition is active before positioning the text area. Created https://github.com/sourcelair/xterm.js/issues/209 to follow this up in August  :+1:

**Comment by Tyriar** [comment]
Ahah, I also see why the text area handle is visible at all, fix for that incoming.

**Comment by Tyriar** [comment]
Very low risk change so I'm pushing to master

**Comment by Tyriar** [comment]
Change applies this style:

![image](https://cloud.githubusercontent.com/assets/2193314/17223843/3859edb8-54b3-11e6-82bb-a419c3cb161b.png)

Which overrides:

```css
..., .monaco-shell textarea:focus, ... {
  ...
  opacity: 1!important;
}
```

**Comment by Tyriar** [comment]
Upleveled xterm.js, the element should be off screen in addition to being fully transparent now.
