### ISSUE TITLE
Some strange slash symbol in launcn.json config description.

### ISSUE THREAD

**Issue by QuestionAndAnswer** [microsoft/vscode#97481]
- VSCode Version: 1.45.0
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Create launch.json config
2. Add configuration for node.js
3. Set "outFiles" options to anything and hover mouse over property word.

![image](https://user-images.githubusercontent.com/6842709/81546461-11fccb00-9383-11ea-969c-3728c3cf03e2.png)

You'll see in the end of description (in example section) different slashes. They are aligned on different angel. 

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

**Comment by isidorn** [comment]
This is coming from the javascript debugger. Forwarding to @connor4312 
Might it be that we are using some funky slash, or is this an electron rendering issue?

**Comment by isidorn** [comment]
Also I can reproduce, but only with the old debugger, not the new one. Thus forwarding aslo to @roblourens 

![Screenshot 2020-05-12 at 10 13 31](https://user-images.githubusercontent.com/1926584/81658672-46cb5980-9439-11ea-8a69-746dd95d4ade.png)

**Comment by roblourens** [comment]
It's an italic slash, we probably just need to wrap that in backslashes.
