### ISSUE TITLE
"Open With..." does not work

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#97488]
- VSCode Version: 1.44
- OS Version: Windows 10

Steps to Reproduce:

1. Install my [Draw.io](https://github.com/hediet/vscode-drawio/) extension
2. Open a new `.drawio` file (a drawio editor shows up)
3. Try to open this file with the default text editor using the `openWith` command

It should open the `.drawio` file with the default text editor, but nothing happens.
As my extension just uses the Custom Text Editor API, I guess this is not a bug in my extension but rather in VS Code.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

Also, what about the current release: 1.45?

**Comment by hediet** [comment]
Same with the current release (1.45):
![image](https://user-images.githubusercontent.com/2931520/81599151-9e7dac80-93c8-11ea-859e-86821fb6eada.png)

**Comment by mjbvz** [comment]
This seems to be fixed for me in current VS Code insiders builds:

![Jun-30-2020 16-20-50](https://user-images.githubusercontent.com/12821956/86186372-c5fe1500-baed-11ea-9fa8-7a0c582b4e1f.gif)


Let me know if you still see this issue

**Comment by hediet** [comment]
Thanks for fixing it! Works perfectly now!

**Comment by dbaeumer** [comment]
Marking as verified due to creator's comment.
