### ISSUE TITLE
Make new break points unverified on a file which is updated during debug session

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#9748]
Testing #9533

- VSCode Version: latest insiders
- OS Version: OSX

Steps to Reproduce:

1.  Enable a break point on a file and start the debug session
2. During the debug session, modify the fie
3. Note that existing break points are unverified - Good
4. Put a new break point in the file

Expected
- New break point has to be in unverified state

Actual
- New break point is active

**Comment by isidorn** [comment]
This appears only when doing extension host debugging, after looking on @sandy081 machine I speculate that the node debug is returning breakpoints always as verified in the case of extension host debugging. Thus forwarding to @weinand to investigate
