### ISSUE TITLE
Debug Console does not flush console.log before exit

### ISSUE THREAD

**Issue by adelphes** [microsoft/vscode#97489]
Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:10:24.511Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-29-generic

Steps to Reproduce:

1. Start a debugger with the following program:
```
for (let i=0; i < 1000; i++) {
    console.log({i});
}
```
2. When the program exits, see that the Debug Console has not printed all 1000 objects.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I can reproduce this also with the js-debug. Thus forwarding to @connor4312 to investigate first on the debug extension side.

**Comment by connor4312** [comment]
Thanks, this is the same as https://github.com/microsoft/vscode-js-debug/issues/161. tl;dr is that in order to print complex things like objects, the debug UI needs to make a followup request to the debugger. If the program/debug session exits too quickly, this cannot be done.

/duplicate
