### ISSUE TITLE
type checking bug of JavaScripts

### ISSUE THREAD

**Issue by lc150303** [microsoft/vscode#97485]
Issue Type: <b>Bug</b>

my jsconfig.json is 
```json
{
    "include": [
        "src/*"
    ],
    "compilerOptions": {
        "checkJs": true,
        "strict": true,
    }
}
```
and the codes are
```js
let s = new Set([1, 2]);
for (let t of s) {     // this 's' is underlined
}
```
it underlines the 's' in `for of` with red wavy line, saying 

> Type 'Set<number>' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators. 

but  '--downlevelIteration' doesn't exist in jsconfig.json.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (1.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>Extensions: none

**Comment by mjbvz** [comment]
What file is opened if you run `go to definition` on `Set`?

Also, try adding `"target": "es2016"` into the `compilerOptions`.

**Comment by lc150303** [comment]
1. It pops up a peek window that shows 2 definition in **lib.es2015.collection.d.ts**,  2 in **lib.es2015.iterable.d.ts** and 1 in **lib.es2015.symbol.wellknown.d.ts**. These files are in **C:\Users\***\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\**. 

2. Adding `"target": "es2016"` fixes it, thanks.
