### ISSUE TITLE
Move generic hover widget to base ui and extend in ContentHoverWidget

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#97496]

**Comment by Tyriar** [comment]
We could also expose the widget in a HoverService for ease of use in the workbench, this would handle:

- Ensuring only 1 is shown at a time
- Timeout scheduling, resetting if the mouse moves
- Easy breaking out of the container

See dialog and context menu service for similar services.

**Comment by rebornix** [comment]
> Timeout scheduling, resetting if the mouse moves

FYI we may also want to reset the hover when the target element's position changes in the workbench. We had an issue in Notebook that when the notebook scrolls, the hover doesn't go away as its relative position to the Monaco Editor container doesn't change. Now with the hover being promoted to workbench/service level, we can fix this issue by having  position monitoring on the hover target. (but not sure about the perf penalty)

**Comment by Tyriar** [comment]
@rebornix the notebook would still use the editor's version and its lifecycle management though. For the workbench-level hover the plan is to ensure only a single hover shows at a time.

**Comment by Tyriar** [comment]
To verifier: test the hover and its overflow behavior by:

- Writing links in the terminal
- Run the [terminal-sample extension](https://github.com/microsoft/vscode-extension-samples/tree/master/terminal-sample) and `Update Environment`/`Clear Environment` commands to show the environment variable indicator. More entries can be [added here](https://github.com/microsoft/vscode-extension-samples/blob/f2a57780639bce99099d5128db2d3be83012d0c0/terminal-sample/src/extension.ts#L148-L152) to make the hover bigger and test bounds overflow behavior

**Comment by connor4312** [comment]
Well, since you asked for overflow behavior 😄  It looks like if you set too many variables to extends over the height of the vscode window. Maybe we need `max-height: 90vh` or something on it.

![](https://memes.peet.io/img/20-07-4d8c1165-aab6-4917-8a06-560b474c2761.png)

Marking as 'found', but this is an edge case so feel free to push...
