### ISSUE TITLE
Restore Windows setting is ignored if app opened via Open With Code shortcut

### ISSUE THREAD

**Issue by gitvadim** [microsoft/vscode#97493]
Issue Type: <b>Bug</b>

# Repro steps:

1. Set Restore Windows to none,
2. Open a new Editor
3. Open a few documents
4. Close the editor
5. Right click any folder and select Open with Code

# Actual result

The app will open with all the documents that were open before you closed it

# Expected result

If Restore Windows is set to none the app should open 'empty' with no documents but scoped to the folder that was right-clicked.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3675)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (16.14GB free)|
|Process Argv|F:\Source\SAM\Def6\imc-uxp\frontend\exhibitor-portal|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-for-handlebars-vscode|alo|2.0.1
Handlebars|and|0.4.1
vs-edit-hosts|con|0.0.1
dart-code|Dar|3.10.1
flutter|Dar|3.10.1
xml|Dot|2.5.0
vscode-docker|ms-|1.1.0
python|ms-|2020.4.76186
powershell|ms-|2020.4.0
vscode-scss-formatter|sib|2.0.1
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|2.8.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@gitvadim where editors dirty in that session or did you use untitled workspaces?

**Comment by gitvadim** [comment]
@bpasero 
I did not create any workspaces (at least knowingly); the editor can be dirty but does not have to -- the issue reproduces regardless.

**Comment by bpasero** [comment]
I cannot reproduce. I need exact steps like I would have never used VSCode before, including keyboard interaction and mouse interaction. Ideally video.

**Comment by gitvadim** [comment]
I've attached a video. In the video I'm double-clicking files in VSCode to 'pin' the editor.
[video.zip](https://github.com/microsoft/vscode/files/4610535/video.zip)
