### ISSUE TITLE
Timeline entries should not end up in history

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#97499]
* open timeline for something
* select many to its entries to find a certain version
* 😞 the history is now full of timeline entries that I never use again

<img width="718" alt="Screenshot 2020-05-11 at 14 46 41" src="https://user-images.githubusercontent.com/1794099/81564547-31522300-9398-11ea-802d-671738d272a2.png">

**Comment by eamodio** [comment]
@jrieken is this still happening for you? I can't reproduce this.
