### ISSUE TITLE
Auth redirect now opens a new window of VS Code

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#97509]
1. Install GitHub Pull Requests and issues
2. Sign out of GitHub in VS Code if you were signed it
3. Sign in using the "Sign in" in the PR view
4. Get taken to browser and allow
5. Click the button to redirect back to VS Code
Expected: goes to same window and finishes auth
Actual: creates a new VS Code window.

**Comment by RMacfarlane** [comment]
I'm having trouble reproducing this, what's your default browser?

@deepak1556 @joaomoreno Have we changed anything recently that would impact our protocol handlers?

**Comment by deepak1556** [comment]
> Have we changed anything recently that would impact our protocol handlers?

I haven't touched it.

Also I couldn't repro this on latest insiders, macOS with chrome and linux host with firefox.

**Comment by alexr00** [comment]
This was with latest insiders and Edge Dev. 
With Edge (non-dev) it does still work. Looks like an Edge bug!
