### ISSUE TITLE
Laggy vsc

### ISSUE THREAD

**Issue by bilomania** [microsoft/vscode#97505]
i cant select my code without lagging 

System Information: 

CPUs	AMD FX(tm)-6350 Six-Core Processor (6 x 3892)
GPU Status	2d_canvas: enabled
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
multiple_raster_threads: enabled_on
oop_rasterization: disabled_off
protected_video_decode: unavailable_off
rasterization: enabled
skia_renderer: disabled_off_ok
video_decode: enabled
viz_display_compositor: enabled_on
viz_hit_test_surface_layer: disabled_off_ok
webgl: enabled
webgl2: enabled
Load (avg)	undefined
Memory (System)	15.97GB (6.10GB free)
Process Argv	E:/2. GameDevTools/Unity/Projects/Desert-Traveler -g E:\2. GameDevTools\Unity\Projects\Desert-Traveler\Assets\_Scripts\Player.cs:1:0
Screen Reader	no
VM	0%

Enabled Extentions: 

Extension | Author (truncated) | Version
-- | -- | --
unity-code-snippets-improved | ble | 1.4.1
eppz-code | epp | 1.2.41
chuck | for | 0.2.1
chunity | jat | 0.0.4
unity-code-snippets | kle | 1.3.0
csharp | ms- | 1.21.18
remote-wsl | ms- | 0.44.2
cpptools | ms- | 0.27.1
msbuild-project-tools | tin | 0.3.5
unity-tools | Tob | 1.2.3
unity-debug | Uni | 2.7.5
unity-snippets | Ycl | 0.1.2

**Comment by Tyriar** [comment]
Please reopen a new issue following https://github.com/microsoft/vscode/wiki/Performance-Issues
