### ISSUE TITLE
Improve the debian package metadata

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9750]
When in Elementary OS (and Ubuntu too), double clicking the deb package opens this window:

![image](https://cloud.githubusercontent.com/assets/22350/17131785/5881e540-531f-11e6-8d0e-8c88a124a079.png)

We should improve this:

- Set a better label for the title: `VS Code Insiders`
- The `https://code.visualstudio.com/docs/setup/linux` link in the description can't be clicked. Maybe we should remove it and add it some other way, like the `Developer Web Site` link is set.
- Include our icon
- Include a screenshot
- Add out license, instead of leaving it `Unknown`

**Comment by Tyriar** [comment]
- It's conventional for the package name to be the command name (code-insiders/code). It also cannot have spaces
- Nothing we can do about the link being unclickable
- Icon and screenshot are only available when the package is uploaded to launchpad https://github.com/Microsoft/vscode/issues/4923

**Comment by chrmarti** [comment]
@Tyriar What about the license field? It might make sense to set that.
