### ISSUE TITLE
Scroll tabs with Scroll too sensitive on OSX

### ISSUE THREAD

**Issue by dtiziani** [microsoft/vscode#97504]
Issue Type: <b>Bug</b>

The feature to switch tabs through scroll is too sensible, using macOSX with magic mouse. if there was a sensitivity configuration would be nice.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 4, 4|
|Memory (System)|16.00GB (0.88GB free)|
|Process Argv|-psn_0_323663|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (101)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|11.2.0
project-manager|ale|10.12.0
aws-toolkit-vscode|ama|1.9.0
ascii-tree-generator|apr|1.2.3
atlascode|atl|2.5.1
vscode-tldr|bmu|1.0.0
vscode-standardjs-snippets|cap|0.8.9
vscode-standardjs|che|1.3.0
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
markdown-table-prettify|dar|2.4.0
vscode-markdownlint|Dav|0.35.1
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
python-extension-pack|don|1.6.0
xml|Dot|2.5.0
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
vscode-npm-script|eg2|0.3.11
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
carbon-now-sh|eri|1.2.0
pull-request-monitor|eri|1.7.1
prettier-vscode|esb|4.6.0
php-intellisense|fel|2.3.14
vscode-jest-runner|fir|0.4.17
code-runner|for|0.10.0
todo-tree|Gru|0.0.174
create-tests|har|1.1.1
vscode-mocha-test-adapter|hbe|2.4.0
vscode-test-explorer|hbe|2.18.0
beautify|Hoo|1.5.0
rest-client|hum|0.23.2
output-colorizer|IBM|0.1.2
plantuml|jeb|2.13.8
vscode-position|jtr|1.0.1
vscode-github|Kni|0.30.3
git-indicators|lam|2.1.2
vscode-python-test-adapter|lit|0.4.2
makefile-command-runner|mad|1.4.1
MagicPython|mag|1.1.0
Runner|mat|0.1.16
terraform|mau|1.4.0
import-sorter|mik|3.3.1
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
theme-monokai-pro-vscode|mon|1.1.15
thrift-syntax-support|mrk|0.0.3
vscode-duplicate|mrm|1.2.1
vscode-cosmosdb|ms-|0.12.2
vscode-docker|ms-|1.1.0
csharp|ms-|1.21.18
python|ms-|2020.4.76186
azure-account|ms-|0.8.11
Go|ms-|0.14.1
vscode-typescript-tslint-plugin|ms-|1.2.3
sqltools|mtx|0.21.7
deepdark-material|Nim|3.2.1
autodocstring|njp|0.5.1
hide-gitignored|npx|1.1.0
material-icon-theme|PKi|4.1.0
polacode|pnp|0.3.4
gitlink|qez|0.5.1
remote-vscode|raf|1.1.0
beautify-json|ran|1.0.2
typescript-hero|rbb|3.0.0
java|red|0.61.0
vscode-yaml|red|0.7.2
bash-debug|rog|0.3.8
vscode-jest-test-adapter|rtb|0.2.0
gi|rub|0.2.11
terraform-doc-snippets|run|0.4.0
yo|sam|0.9.3
markdown-preview-enhanced|shd|0.5.3
vscode-spotify|shy|3.1.0
vscode-taskexplorer|spm|1.26.3
ayu|tea|0.18.0
arcade|tha|0.17.18
pdf|tom|0.6.0
autocomplate-shell|tru|0.1.1
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.7
vscode-svg-previewer|vit|0.5.2
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.10.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.3
vscode-icons|vsc|10.1.1
codetour|vsl|0.0.25
gistfs|vsl|0.0.67
vscode-import-cost|wix|2.12.0
vscode-surround|yat|1.0.2
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|2.8.0
sort-js-object-keys|zen|1.0.6
material-theme|zhu|3.5.0
vscode-proto3|zxh|0.4.2

(7 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Probably a dup of #96409
