### ISSUE TITLE
Add full GitHub support for VS Code .

### ISSUE THREAD

**Issue by ManavRaja** [microsoft/vscode#97500]
Visual Studio Code should have full GitHub support so we can do everything we need to in GitHub in VS Code instead of using Git & then pushing to a GitHub repository. (Like Atom Code Editor)

**Comment by alexr00** [comment]
We have some GitHub support with the GitHub Pull Requests and Issues extension. You can read about our philosophy on adding GitHub support in [this blog](https://code.visualstudio.com/blogs/2020/05/06/github-issues-integration#_our-integration-approach).

**Comment by ManavRaja** [comment]
Ok, Thanks
