### ISSUE TITLE
There are two KeytarCredentialsService implementations

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#97501]
We have 

1. `src/vs/workbench/services/credentials/node/credentialsService.ts` and
1. `src/vs/platform/credentials/node/credentialsService.ts`

Both look very, very similar

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/1794099/81565317-6b6ff480-9399-11ea-9d1f-72ccaf894335.png">

**Comment by sandy081** [comment]
I don't remember who created these two, but history shows @bpasero and @chrmarti . Hence assigning them.

Seems first one `src/vs/workbench/services/credentials/node/credentialsService.ts` is not used anywhere.
