### ISSUE TITLE
Make suggestion widget aria label more concise

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#97510]
As reported by @pawelurbanski 
Everytime it is triggered screen reader reads: "Suggestion. Use navigation keys to navigate".. And then the item…
Since users trigger this many times per day, reading the "Use navigation keys to navigate" is not needed

**Comment by isidorn** [comment]
We could instead just read "Suggestion" and then the `aria-label` of the selected item. Or just the `aria-label` of the selected item.

**Comment by pawelurbanski** [comment]
Just the label of the item:
A bit of pseudo code:
Var wnd = window;
Wnd.addEventListener(…);
Dissecting the first line:
Pressing: ‘v’ would yield: Suggest. Var. Then I keep on typing and want to get completion for a window object. Press: ‘w’ and get again Suggest. Window.
The same for line 2 when using the variable and the method with a dot notation.
The context is extremely obvious. I don’t think that any user who is fluent enough to write even small amount os code needs this additional information besides just the label for the item being suggested.

**Comment by MarcoZehe** [comment]
Since there is no audible clue that this is indeed a suggestion box, keeping the label for the container as "Suggestion" would be OK, IMO, but yes, removing that "Press up and down to navigate" is indeed too much for that label. It is announced that the user is in a listbox anyway, which always gets navigated with arrow keys.

**Comment by pawelurbanski** [comment]
The widget is activated in the editor. And it takes just seconds to get that association.
While there maybe is no very direct clue about the role of the container the label for the item being suggested is very obvious.
We should try to keep in mind the audience for VS Code – at least power user or developers. Even if VS Code is used in the classroom or by a complete beginner, hearing this: ‘Suggestion.’ Label before the item would stop making sense after at most a dozen times IMHO.
I vote for just the label of the item currently being suggested coming from the aria-activedescendant association. In case when there is nothing to be suggested just set the label to: No Match – just 2 very short sylabels in a phonetic sense.

**Comment by MarcoZehe** [comment]
It would help if VS Code had, on Windows at least, the ability to trigger the same Windows event that the start menu triggers when you type something in the search box and suggestions become available. NVDA makes a distinct sound in this instance, but I have not seen this anywhere except the start menu search box, AKA Cortana search box. That would be cool as an alternative to the "Suggestions" label for the container. :-)

**Comment by webczat** [comment]
Not sure if you disable automatic suggestions/quick suggest? I always get confused by that happening and not sure if it helps if it announces that it's a suggestion or not. In the case of manually activated by ctrl+space I am ok with hearing the suggestion word.

**Comment by pawelurbanski** [comment]
Attaching a sound is the screen reader side and very likely a custom classimplemented for the start menu control. When it comes to triggering a control with a label when invoked with a shortcut it would require using a flag that would later on be used in a condition to add this ‘suggest’ label. I find it also very redundant to add this label in case when someone mantually triggers the intellisense autocomplete widget, for it is a very direct action with a very predictable behavior attached to the shortcut.

**Comment by alex19EP** [comment]
OK. my two cents. I am totally for deleting arrow information. and not only from the autocomplete widget, but also from other VsCode parts.

As for the label, this is an ambiguous situation and we need to think about it. I, as an advanced user, would prefer not to hear: "Suggestion, but you need to think about novices too.

**Comment by pawelurbanski** [comment]
I mentioned novices in my previous comment. Learning the context around intellisense, which is a feature of the editor should take at most half an hour at most…
User who want to take a shot at coding are either power users or enrolled in a course with instructors who will be more than happy to spend a few minutes explaining / helping out. While we should not make the learning curve steep and entering coding difficult, we can expect reasonable fluency working with tools like VS Code or other kinds of IDEs.
It applies equally to people with and without disabilities…

**Comment by webczat** [comment]
I believe in vs and eclipse it would just indicate that you are in a list, then say the suggestion.

**Comment by isidorn** [comment]
Thanks a lot for feedback. It is sometimes hard to find a delicate balance between an experience for novice users and for pros.
Though based on your feedback I have decided to remove the "Use the navigation keys to navigate" message all over vscode. Since the screen reader will always announce the correct role I feel it is pretty obvious to use the up / down arrow key.

So pushing this out to insiders so we get feedback.

fyi @joaomoreno since you might have a good reason when you originally added this message.

**Comment by joaomoreno** [comment]
@isidorn Just follow the git blame trail: https://github.com/microsoft/vscode/issues/52658#issuecomment-402643764

**Comment by isidorn** [comment]
Awesome that we removed it then. There was no good motivation to add it in the first place.
