### ISSUE TITLE
Changing order of folders listed in .code-workspace breaks VSCode's ability to find type definitions

### ISSUE THREAD

**Issue by Merott** [microsoft/vscode#97514]
It seems that the order of folders listed in `.code-workspace` (Multi-root workspaces) affects TS Server's ability to correctly find the relevant type definitions.

I wish I could explain it better, but unless I figure out exactly what's causing it, I can only demo it ([demo repo](https://github.com/Merott/demo-vscode-issue) / [demo video](https://raw.githubusercontent.com/Merott/demo-vscode-issue/master/recording.mov))

- VSCode Version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
- OS Version: Darwin x64 19.4.0

**Steps to Reproduce:**

1. Clone/download the [demo repo](https://github.com/Merott/demo-vscode-issue)
2. Run `yarn install` in both `app` and `api` directories
3. Open [`project.code-workspace`](https://github.com/Merott/demo-vscode-issue/blob/master/project.code-workspace) with VSCode
4. Make sure to have the [Vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur) extension installed
   _NOTE: The issue doesn't seem to have anything to do with Vue or the Vetur extension, but I've run into it while working on a Nuxt app, and I don't know how to reproduce it in a basic TS project yet. I've done all I can to set up a demo repo that's as simple as possible._
5. Verify that [`app/pages/index.vue`](https://github.com/Merott/demo-vscode-issue/blob/master/app/pages/index.vue) contains no errors
6. Open [`project.code-workspace`](https://github.com/Merott/demo-vscode-issue/blob/master/project.code-workspace) with a text editor, and change the order of the folders, putting `app` after `api`
7. Back in VSCode, notice [`app/pages/index.vue`](https://github.com/Merott/demo-vscode-issue/blob/master/app/pages/index.vue) reports an error for `asyncData`

Here's a [demo video](https://raw.githubusercontent.com/Merott/demo-vscode-issue/master/recording.mov) to quickly demonstrate the issue.

**Does this issue occur when all extensions are disabled?:** Yes. I have tested this with a fresh install of the latest Insiders build, using only the Vetur extension (see my comment under step 4)

**Comment by mjbvz** [comment]
VS Code does not provide any error reporting in Vue out of the box so please follow up with the Vetur extension

**Comment by Merott** [comment]
@mjbvz 

How are you certain that the error is caused by Vetur? Did you try out the demo repo or watch the demo video?

As I mentioned, the issue doesn't seem to have anything to do with Vue or Vetur. It's just that I didn't know how to reproduce the issue in a plain TypeScript setup.

**Comment by mjbvz** [comment]
Because VS Code does not report errors in vue files unless you install an extension
