### ISSUE TITLE
April 2020 release breaks "variable.parameter.js" tokenColorCustomizations

### ISSUE THREAD

**Issue by somebeaver** [microsoft/vscode#97516]
- VSCode Version: 1.45.0
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. Update to April 2020 (v1.45.0)
2. See screenshot. The "resolve" parameter should be using the color of `variable.parameter.js` but it's using `entity.name.function.js`. I have tried moving the rule around in my settings.json but it does not change anything.

![image](https://user-images.githubusercontent.com/3053410/81579081-b37f1f00-9379-11ea-9ac5-fc6572daa772.png)

I downgraded to 1.44.2 which does not have this issue.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Maybe an intentional change. See #91038

**Comment by somebeaver** [comment]
I see, thank you for linking that. I read dannymcgee's reasoning, but I fundamentally disagree with changing the long standing behavior here. Parameters are parameters, and should always have the same color.

**Comment by gjsjohnmurray** [comment]
cc @aeschli

**Comment by aeschli** [comment]
#91038 was the reason for that change. It's part of semantic highlighting for TypeScript/JavaScript.
You can turn on/off semantic highlighting for your theme as shown here: https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview#which-themes-offer-semantic-highlighting
