### ISSUE TITLE
VS Code Accessibility Community Call - May 2020

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#97519]
One of our team's top priorities is to make VS Code more accessible product and improve experiences for every user. We will hold a regular call where users in our accessibility community can give feedback, bring up problems, and share accessibility practices. The first call will be held on **Tuesday, May 12 at 10am EST / 4pm CEST / 7:30pm IST**. Please join our [Gitter channel ](https://gitter.im/Microsoft/vscode-a11y) to get details on how to join the call.

### Agenda:

- Introductions and meet and greet

- Feedback on proposal for terminal links: https://github.com/microsoft/vscode/issues/95570

- Feedback on accessibility for settings editor: https://github.com/microsoft/vscode/issues/97567

- Remaining time on general accessibility feedback: What can be smoother or easier?

We will post a link to the recorded video at the end of the call and post notes from the call on this issue. Thank you!

---
Thanks all for joining us! Here is a link to the recording: https://www.youtube.com/watch?v=twiG4v8RTOc

**Comment by isidorn** [comment]
@roblourens maybe fill in the settings UX accessibilty issue

**Comment by isidorn** [comment]
Closing this since we have done our accessibility community call.
Corresponding discussions can be found in the linked issues above, and the link for the recording can be found in @sana-ajani inital comment.
