### ISSUE TITLE
number/boolean values not working

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#9752]
re #9560

```
{
    "command": "echo",
    "isShellCommand": true,
    "args": ["Hello World", "${workspaceRoot}", "${config.editor.lineNumber}"],
    "showOutput": "always",
    "version": "0.1.0"
}
```

* have a `task.json` like above
* the value of `editor.lineNumber` isn't interpreted, the same for `boolean` values

I'd expect that I can use primitive values like `boolean` and `number` in addition to `string`. Maybe even arrays.

**Comment by DonJayamanne** [comment]
@jrieken, I believe this can be resolved. Will submit a new PR for this tomorrow once I have tested the code thoroughly and updated the unit tests.
Thanks for identifying this.

**Comment by isidorn** [comment]
@DonJayamanne if you plan to work on an item in this iteration than assign it to the july milestone. If the code is unit tested and the changeset is not huge feel free to push to master without a pr. Though if you prefer a code reveiw feel free to submit a pr and assign to me :)

**Comment by DonJayamanne** [comment]
@isidorn, it is a small change and will push directly to master tomorrow. Cheers.

**Comment by DonJayamanne** [comment]
@jrieken, please re-test #9560 with the new insider build when the new build gets released. 
In the future, do I just close these issues (such as this) or wait for you to close it?
Thanks.

**Comment by isidorn** [comment]
@DonJayamanne we just close the issue once we pushed the fix. @jrieken does not need to re-test this now, during our verification process (usually thursday) bug creators verify that the fix is good. More about verification can be found here 
https://github.com/Microsoft/vscode/wiki/Issue-Tracking#verification
