### ISSUE TITLE
Error files output on "ng serve" does not allow control-click to navigate to file.

### ISSUE THREAD

**Issue by wa1gon** [microsoft/vscode#97524]
Error files output on "ng serve" does not allow control-click to navigate to file.  Sometimes it works and sometimes it doesn't.

Version: 1.45.0 (user setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by Tyriar** [comment]
Can you show a screenshot?

**Comment by wa1gon** [comment]
Here you go.  Maybe it has something to do with the colorization as the red errors at the bottom do show the ctrl-click tooltip.

![image](https://user-images.githubusercontent.com/1592175/81599926-87ba6400-938e-11ea-9ae0-43f2d3d603b7.png)

**Comment by Tyriar** [comment]
Can you try after setting this to enable the new links system?

```
"terminal.integrated.experimentalLinkProvider": true
```

**Comment by wa1gon** [comment]
Changing the setting did seem to do the trick.
