### ISSUE TITLE
Pinned tabs: doesn't toggle with shortcut

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#97520]
Issue Type: <b>Bug</b>

I can toggle it once with <kbd>Ctrl</kbd>+<kbd>K</kbd> <kbd>Ctrl</kbd>+<kbd>Enter</kbd> but then it stops working. Probably something about `editorSticky` context key.

VS Code version: Code - Insiders 1.46.0-insider (2b472d1e4aaaecdda5ca96289869f90ae82de3a1, 2020-05-11T10:00:12.459Z)
OS version: Windows_NT x64 6.2.9200

**Comment by bpasero** [comment]
Thanks, weird. I can reproduce.
