### ISSUE TITLE
Integrated terminal links not recognized when starting with workspace folder

### ISSUE THREAD

**Issue by colelawrence** [microsoft/vscode#97528]
- VSCode Version: 1.46.0-insider
Commit: 2b472d1e4aaaecdda5ca96289869f90ae82de3a1
Date: 2020-05-11T09:54:42.339Z (7 hrs ago)

- OS Version: Darwin x64 19.4.0

Steps to Reproduce:

1. Run a command that prints a path like `workspaceFolderA/readme.md`
2. Notice that a direct link is not found (bug)
3. Try opening "Find in Project" (Cmd + P) and paste path `workspaceFolderA/readme.md`
4. See no results (screenshot below)

![image](https://user-images.githubusercontent.com/2925395/81589623-90f40280-9387-11ea-8dbe-37203501cd71.png)

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by Tyriar** [comment]
This is working as designed, links are only validated relative to the root directory. What you're seeing is the fallback search from which you can tweak by removing the first path manually.

**Comment by colelawrence** [comment]
@Tyriar thanks for the follow-up!

So is this a feature suggestion? Because if this experience worked as I'm suggesting, it seems like an obvious net positive.

This is a much larger issues when I have multiple workspace folders and `workspaceFolderA/src/index.ts` doesn't resolve, and removing the prefix then requires me to choose from multiple workspace folders `src/index.ts` items...

**Comment by colelawrence** [comment]
Another approach that would solve my problem would be the ability to configure the resolver "root directory" for my multi-root as you described. Is that something that can be configured?
