### ISSUE TITLE
Vscode does not render \n , \t characters

### ISSUE THREAD

**Issue by ElHex** [microsoft/vscode#97539]
- VSCode Version: 1.45.0
- OS Version: Windows 10 / 10.0.18363

Steps to Reproduce:

1. Launch VS code
2. Install XDebug or try to debug anything that outputs \n or \t

![kRbXi](https://user-images.githubusercontent.com/52222397/81595979-5000eb80-9391-11ea-8f85-b947c0ff8b97.png)

This was working the last time I tried to debug on a project

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Please file this against your debug extension.
More details why vscode is no longer escaping whitespace can be found here https://github.com/microsoft/vscode/issues/73845

**Comment by ElHex** [comment]
Hey @isidorn, just spoke with the xDebug guys and the do not escape anything, seems like a vscode thing, they just send it as base64 encrypted
