### ISSUE TITLE
Typescript module resolution fails in files matched by config.exclude

### ISSUE THREAD

**Issue by beck** [microsoft/vscode#97531]
Using `tsconfig.json`:
```json
{
  "compilerOptions": {
    "baseUrl": "."
  },
  "exclude": [
    "**/*.spec.ts"
  ]
}
```

Absolute imports in any `spec.ts` are now broken and throw:
> Cannot find module 'hello' or its corresponding type declarations.ts(2307)

Gist of minimal project:
https://gist.github.com/beck/849700fc765bcfe6b80a8f85cc29b0f7

Screenshot:
<img width="891" alt="Screen Shot 2020-05-11 at 1 14 46 PM" src="https://user-images.githubusercontent.com/154988/81590818-6efb7f80-9389-11ea-868b-dc1b0a772499.png">

Deleting `"**/*.spec.ts"` from `exclude` fixes module resolution. Is this expected behavior?

VSCode Version:  1.45.0 & 1.46.0-insider
OS Version: OSX 10.15.4
Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Yes, that style of module import only works if you set a `baseUrl`. A `baseUrl` only applies to files that are in the JS project you have defined (and your current config explicitly excludes `index.spec` from the project)

**Comment by beck** [comment]
Thanks for the super quick reply. Is there anyway to configure absolute importing across all files and exclude specs from the output build?

**Comment by mjbvz** [comment]
Try having your top level `tsconfig.json` include all files, then create a `tsconfig.build.json` that only includes the files you want to build
