### ISSUE TITLE
Debug mode kicks off for ANY npm command

### ISSUE THREAD

**Issue by ericklind** [microsoft/vscode#97535]
Issue Type: <b>Bug</b>

I have a react app I've been working on for the last year. I have been using VS Code thoughout the whole development process and everything seemed to be working fine until Friday, when any npm or yarn command (start/run/build) kicks off a debugger. It has never done this before. 

When it is running in debug mode, the debug toolbar does not have option to stop. I can only pause or refresh. When I choose Stop Debuging from the Run menu, it stops the whole npm command, so it is no longer running. Why is this happening and how do I stop it? I'm unable to do build in the terminal because it kicks off the debbuger and never completes. 

I have not changed anything in the last few weeks with debugging configurations. I'm assuming this has something to do with the update on Friday. Please let me know how to fix this.

Thanks.

Erick

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.5.0
bracket-pair-colorizer-2|Coe|0.1.2
vscode-eslint|dba|2.1.5
vscode-npm-script|eg2|0.3.11
vscode-firefox-debug|fir|2.8.0
rest-client|hum|0.23.2
csharpextensions|jch|1.3.1
vscode-docker|ms-|1.1.0
csharp|ms-|1.21.18
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
Go|ms-|0.14.1
js-debug-companion|ms-|0.0.4
js-debug-nightly|ms-|2020.5.617
powershell|ms-|2020.4.0
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.6
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.1.0
quicktype|qui|12.0.46
preview-vscode|sea|2.1.0
code-settings-sync|Sha|3.4.3
todo-list|Tza|1.6.0
highlight-matching-tag|vin|0.9.9

(1 theme extensions excluded)

</details>

**Comment by usernamehw** [comment]
Maybe it has something to do with `js-debug-nightly` debug nightly extension.

Or with a setting `debug.node.autoAttach`.

**Comment by ericklind** [comment]
It was both, actually. I disabled the extension and it work as expected. Then I re-enabled it and changed the autoAttach to off and it worked as expected. 

Thanks!
