### ISSUE TITLE
Add `in` operator support to when clauses

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#97544]
Refs: #96927

There is a desire to be able to show a context menu command conditionally on explorer folders (or others) based on computed/determined criteria. For example, lets say I have a folder with a certain file type in it (or all of the same type) and I want to offer a command to only show up for folders that match that criteria. Today this isn't possible, since we don't offer any trigger on selection in the explorer tree (so you can't set a "global" context value), nor is it possible to lookup a context value using another context value.

To address this I propose a new `in` operator to be supported. This `in` operator would allow using an existing context key as a lookup key into another context value. The target of the `in` would be either an array or an object.

For example:

Given something like the following context key,
```json
foldersToShowCommandFor: [ 'test', 'src/foo', 'src/foo/bar' ];
```

You'd then be able to use the following `when` on a command:
```json
"menus": {
	"explorer/context": [
		{
			"command": "ext.jsFolder",
                        "when": "explorerResourceIsFolder && resourceFilename in foldersToShowCommandFor"
		}
	]
}
```

@idoprz Please add any more details or specifics about your use case too.

//cc @alexdima @jrieken

**Comment by isidorn** [comment]
This can not be solved just to be specific to the explorer, thus unassing myself.

**Comment by idoprz** [comment]
Hi,

Looks great to me! would solve allot of problems.
How would I set "foldersToShowCommandFor"? I assume I can set it in my extension code? Do I use setContext command for it? I saw it been used in GitLens, but it's not documented (#46445). Is it ok to use it?

**Comment by idoprz** [comment]
Hi,
Any news on this?

**Comment by idoprz** [comment]
Hi,
Is this item going into development?

**Comment by eamodio** [comment]
@idoprz I've opened a PR for this feature. Hopefully we can get it in soon.

**Comment by idoprz** [comment]
Amazing! Thanks for following through.
