### ISSUE TITLE
Shell Script syntax coloring wrong when variable names end in digits

### ISSUE THREAD

**Issue by bland328** [microsoft/vscode#97540]
- VSCode Version: 1.45.0
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. Create this script:
```
#!/bin/bash
var1=3
echo "$(( 2 * var1 ))"
```
2. Within the arithmetic statement, the digit `1` at the end of the variable name `var1` is colored as if it were a stand-alone numeric value, rather than part of the variable name.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
@bland328 we get our shellscript grammar from https://github.com/atom/language-shellscript. However, they are no longer fixing bugs in their textmate grammar. I will leave this bug open so we don't forget about it if we ever change grammars.

![image](https://user-images.githubusercontent.com/38270282/81661137-fa354d80-943b-11ea-943c-1a4e24911713.png)

**Comment by alexr00** [comment]
https://github.com/microsoft/vscode/issues/77675 tracks considering a new shellscript grammar. Closing in favor of that issue.
