### ISSUE TITLE
Terminal lacks focus indication

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9754]
Testing #9695

Through two separate situations, I've been able to get into a state in which the terminal lacks focus indication through the cursor:

- Simply disable cursor blinking (related to #9753). When moving focus to the editor and back to the terminal, there is no indication that the terminal has focus at all.
- Or, leave the blinking cursor, run the `htop` command, exit it with <kbd>Q</kbd> and the terminal will then lack focus information when moving focus to the editor and back again.

**Comment by Tyriar** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/44cd0bee8299f5dcdb40ae31a0f5965ee29cedc9
