### ISSUE TITLE
VSCode Startup "no longer responding"

### ISSUE THREAD

**Issue by usmcguy** [microsoft/vscode#97549]
[prof-acba.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/4612014/prof-acba.extHost.cpuprofile.txt)
[prof-acba.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/4612017/prof-acba.main.cpuprofile.txt)
[prof-acba.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/4612018/prof-acba.renderer.cpuprofile.txt)

This is installed on a Server 2016 Virtual Machine in a Citrix Environment.

When launching VS Code, Icon will appear in task bar, but get an error "This window is no longer responding". Have tried launching with --disable GPU.

**Comment by jrieken** [comment]
Adding @bpasero for the message itself

The app is actually not froozen, just running v e r y slowly. I guess that due to the environment. How is the VM spec'ed? How many cores does it have?

**Comment by bpasero** [comment]
The message "This window is no longer responding" indicates that even Chrome itself thinks the window is frozen, e.g. after N seconds of the window not responding to anything.

**Comment by usmcguy** [comment]
8cores 20GB

**Comment by jrieken** [comment]
The profile shows mostly idle once the renderer is up and running 👇 

<img width="1061" alt="Screenshot 2020-05-12 at 13 48 53" src="https://user-images.githubusercontent.com/1794099/81684523-548fd780-9457-11ea-9ea7-94234196a5a0.png">

Is there any perceivable slowdown? Does the cursor stop blinking? Does it actually freeze?

**Comment by usmcguy** [comment]
I only get a black window. If I click inside the window, thats when the window pops up with the error message.

**Comment by usmcguy** [comment]
This only seems to occur if I use the user or system install. If I use the zipped packge, the app launches fine.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by usmcguy** [comment]
Sorry for the delay. When I used the 1.46.0 insider install, it took a while (over 10 minutes) to launch but eventually opened. Not ideal waiting that long though.
