### ISSUE TITLE
Ctrl+select definition doesn't close the disambiguation widget

### ISSUE THREAD

**Issue by tlemo** [microsoft/vscode#97542]
Issue Type: <b>Bug</b>

1. Goto definition for any symbol which requires disambiguation
    ... disambiguation widget will show up
2. Ctrl+select one of the defitions (to open definition to a side)

Expected: disambiguation widget will close (as it does when regular select is used)

Actual: disambiguation widget stays open

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:10:24.511Z)
OS version: Linux x64 4.15.0-99-generic

**Comment by jrieken** [comment]
The concept of "disambiguation widget" doesn't exist, it's simply the peek widget which is launched and because it doesn't look any different it also doesn't behave any different. No plans to change that.

**Comment by tlemo** [comment]
Regardless of what the disambiguation UI is called, or how it's implemented, the issue is the inconsistent behavior. Especially in the context of #97317.
