### ISSUE TITLE
Markdown preview using wrong text color

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#97545]
Saw this in today's insiders where all markdown text was rendered in a weird blueish color, it's more noticeable on a light theme:

![image](https://user-images.githubusercontent.com/35271042/81603292-f1347580-9382-11ea-8756-5ee1cffbdcaf.png)

## Dark
![image](https://user-images.githubusercontent.com/35271042/81603012-73706a00-9382-11ea-8559-8e904bf1a35c.png)

## Light
![image](https://user-images.githubusercontent.com/35271042/81603027-79664b00-9382-11ea-893a-7121cafc0afe.png)

**Comment by mjbvz** [comment]
This is caused by the one Dark Pro extension that recently added markdown styling (without scoping it to only be enabled when the theme is enabled)

https://github.com/Binaryify/OneDark-Pro/issues/388
