### ISSUE TITLE
semantic highlighting: Readonly<T> fields not highlighted as constant

### ISSUE THREAD

**Issue by bmalehorn** [microsoft/vscode#97551]
- VSCode Version: 1.45
- OS Version: Darwin x64 18.7.0

Steps to Reproduce:

1. create a typescript file
2. paste in this code:
```ts
type Foo = {
  readonly bar: string;
  ack: string;
};

const f = (foo: Foo, readonlyFoo: Readonly<Foo>) => {
  foo.bar;
  foo.ack;
  readonlyFoo.bar;
  readonlyFoo.ack;
};
```
3. 
![image](https://user-images.githubusercontent.com/3344958/81611533-14195680-9390-11ea-8e16-6da4cce15ab4.png)

Expected: `readonlyFoo.bar` and `readonlyFoo.ack` would both be highlighted as constants, same as `foo.bar`. All three are `readonly` attributes.
Actual: `readonlyFoo.bar` and `readonlyFoo.ack` are both highlighted as non-constants.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Moved to https://github.com/aeschli/typescript-vscode-sh-plugin/issues/16
