### ISSUE TITLE
Extension host terminated unexpectedly.  Code: 134 Signal: null

### ISSUE THREAD

**Issue by ycagelulu** [microsoft/vscode#97557]
Issue Type: <b>Bug</b>

I ran a python code, and I only enable the extension "Python". Otherwise, I cannot "run current file in Python interactive window".

If the code runs longer, it will stop and pop up a notification---Extension host terminated unexpectedly.  Code: 134 Signal: null

What I have tried:
1. I disabled other extensions (excluding the needed Python)

Hope you can help me!

[https://drive.google.com/open?id=1s2YakhXiqNIgM32cnsscM6S-r-gIsBKq](url)

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by ycagelulu** [comment]
### I reproduced it with your nightly insider builds
Here is my system information:

CPUs | Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: enabledrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 7.89GB (1.99GB free)
Process Argv |  
Screen Reader | no
VM | 0%


Here is my enabled extension:

Extension | Author (truncated) | Version
-- | -- | --
python | ms- | 2020.5.78807

You can see the screenshot
![vscodeissue_2](https://user-images.githubusercontent.com/44679111/81742695-26fe5a80-9466-11ea-8739-22c3d9eae0cb.jpg)

Please let me know if anything else you needed.

**Comment by ycagelulu** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

Have done it. But still the same problem. You can see as below.

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? We recently added support for producing a crash dump to a local folder and I am curious to test if it actually works in this case.
