### ISSUE TITLE
macOS Inverted Cursor

### ISSUE THREAD

**Issue by dmaixner93** [microsoft/vscode#97550]
- VSCode Version: 1.45.0
- OS Version: OS: macOS Catalina Version 10.15.4

Steps to Reproduce:

1. Set color theme to any color theme with a dark background.
2. Open 'New Terminal', hover over text and observe the inverted cursor
3. Hover over text in standard editor, and notice the cursor has not inverted, making cursor difficult to locate and blocking text from the "bolder" design caused by the white border
![editor_cursor](https://user-images.githubusercontent.com/43049828/81611772-47b0ac80-93a1-11ea-8512-5fcc3ae2dd8f.jpg)
![terminal_cursor](https://user-images.githubusercontent.com/43049828/81611777-48e1d980-93a1-11ea-8fc9-b43db5afac42.jpg)

.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by dmaixner93** [comment]
This issue randomly occurred one day after opening VSC. No settings were changed and nor were any extensions edited/added/removed.

**Comment by alexdima** [comment]
Will be addressed by https://github.com/microsoft/vscode/pull/96947
