### ISSUE TITLE
Show unfocused cursor on editors as outlined blocks (like in terminal)

### ISSUE THREAD

**Issue by nahuel** [microsoft/vscode#97552]
Currently an unfocused VSCode terminal shows the current cursor position as an outlined block:

![Untitled](https://user-images.githubusercontent.com/15200/81612846-d9291a00-93b3-11ea-9bcb-fa54eddf7a07.jpg)

It will be nice (and consistent) if cursors on unfocused *editors* showed also as outlined blocks, just like in terminal. Emacs does this by default and is an useful hint to see which window is unfocused, also it works to leave a "visual marker" when checking code in multiple windows.

**Comment by Tyriar** [comment]
@alexdima this is about the editor copying the terminal's unfocused style
