### ISSUE TITLE
[terminal] Popups shown for each command executed

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#9756]
Elementary OS, Freya

Every time I execute a command in the terminal, the OS shows a popup that the task has completed. That doesn't happen when I do the same in the OS'es terminal, or with other commands that VSCode runs internally.

![command-popups2](https://cloud.githubusercontent.com/assets/6461412/17132399/de732342-5321-11e6-9d97-f3862930ae4a.gif)

**Comment by Tyriar** [comment]
I've never seen this 😕 @joaomoreno did you see anything like this when you were using Elementary?

**Comment by joaomoreno** [comment]
Nope, I can't reproduce this. Must be something @aeschli has installed...
