### ISSUE TITLE
Keyboard shortcuts are not preserved between sessions

### ISSUE THREAD

**Issue by sumitsumit** [microsoft/vscode#97562]
I love codespaces, but am finding the keyboard shortcuts are not preserved between sessions. The setting file's path is reported as /User/keybindings.json, but this doesn't exist in the container. For now I'm saving a copy in .vscode and then copying it over when the bindings disappear. Note that I'm using an in-private window for codespaces, as otherwise it gets very confused between my personal and organization microsoft accounts (separate issue).

**Comment by bpasero** [comment]
@sumitsumit is it possible that you are using different browsers for different sessions, e.g. home and work?

**Comment by bpasero** [comment]
Oh, this explains it:

> Note that I'm using an in-private window for codespaces

I think settings are stored in IndexDB or localStorage.

**Comment by bpasero** [comment]
I would appreciate if you could report this issue to https://github.com/MicrosoftDocs/vsonline/issues

**Comment by sumitsumit** [comment]
will do!
