### ISSUE TITLE
Can't use Proxy Authentification since Update on 1.45

### ISSUE THREAD

**Issue by PSTobiasMueller** [microsoft/vscode#97576]
Issue Type: <b>Bug</b>

Since the latest Update the Proxy Authentification seems to have a bug.
When i start VSCode it prompts for my Credentials (as always), but the Button Ok/Cancel are out of order. I can fill in my credential, but i cant confirm them with the OK Button. Same is for the Cancel button. The only thing that works is to close the dialog via X in the System Menu (top right).

In the main.log File i see an entry for every click:

[2020-05-12 07:06:06.562] [main] [error] webContents#will-navigate: Prevented webcontent navigation

I switched back to Version 1.44. There's the proxy authentification working properly.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.75GB (1.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
gitlens|eam|10.2.1
vs-code-xml-format|fab|0.1.5
beautify|Hoo|1.5.0
vscode-line-endings|jha|0.2.0
csharp|ms-|1.21.18
powershell|ms-|2020.4.0
vscode-icons|vsc|10.1.1
material-theme|zhu|3.5.0

</details>

**Comment by chrmarti** [comment]
/duplicate https://github.com/microsoft/vscode/issues/97199

See https://github.com/microsoft/vscode/issues/97199#issuecomment-626002254 for a workaround.
