### ISSUE TITLE
unexpected paste when find in a text

### ISSUE THREAD

**Issue by BoyiAli** [microsoft/vscode#97570]
Issue Type: <b>Bug</b>

I pressed ctrl+f to find in a text. 
I inputed the string in the textBox.
when i click the "find next" button, it may do a unexpected paste sometimes. sometimes it pasted in the textbox. and sometimes it pasted in the user texts.
it really trouble me. 

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
masm|blt|0.0.4
githistory|don|0.6.5
vscode-language-pack-zh-hans|MS-|1.45.1
csharp|ms-|1.21.18
remote-containers|ms-|0.117.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.28.0-insiders3
platformio-ide|pla|1.10.0
material-theme|zhu|3.5.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with all extensions disabled?

**Comment by BoyiAli** [comment]
> Does the problem also happen if you launch with all extensions disabled?

Yes. the problem happened from when i first installed to now.

**Comment by gjsjohnmurray** [comment]
Can you post details of simple repro steps? Pasted screenshots may help, but please also paste any text blocks needed in a file tab. Even better, animated GIF or link to short video.

**Comment by BoyiAli** [comment]
> Can you post details of simple repro steps? Pasted screenshots may help, but please also paste any text blocks needed in a file tab. Even better, animated GIF or link to short video.

OK, I will try to do it. but it don't reappear always. Maybe it will reappear several day late.

**Comment by alexdima** [comment]
@BoyiAli What kind of mouse do you have? Does this reproduce with any mouse?

**Comment by BoyiAli** [comment]
> Can you post details of simple repro steps? Pasted screenshots may help, but please also paste any text blocks needed in a file tab. Even better, animated GIF or link to short video.

![ezgif-4-805795c3b957](https://user-images.githubusercontent.com/37391630/81662081-a5abc580-946f-11ea-86f6-328773a90231.gif)

I find it happened when i use "Microsoft Pinyin input method" to input.
I typed a English word but i forgot to turn to English(from Chinese), i didn't finish it.
In that time,  any where  i  clicked it will pasted the word in that place.

**Comment by BoyiAli** [comment]
![ezgif-4-343bdeb10d0a](https://user-images.githubusercontent.com/37391630/81879286-e6fdbb80-95bc-11ea-9510-8e6ee6593916.gif)
This gif can show this problem clearly.

**Comment by willthefirst** [comment]
I could not reproduce this on a Mac, after setting the input method to Pinyin.

![2020-06-24 at 1 03 PM](https://user-images.githubusercontent.com/1113314/85600242-479c0180-b61b-11ea-9416-e4a4ebb83ad7.gif)

**Comment by rebornix** [comment]
@BoyiAli can you check if you are still seeing this?

**Comment by BoyiAli** [comment]
> @BoyiAli can you check if you are still seeing this?

Yes,it's still there.
