### ISSUE TITLE
Turing on settings sync on a new device scrambles all viewlet items

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#97571]
1. Have activity bar items organized in a reasonable way. (Explorer, Search, SCM, Debug, Extensions, GHPR, Docker, LS, for instance)
2. Enable settings sync on a fresh install of something (Code - OSS, for instance).
3. Back to first window. Icons have been scrambled to put all extension contributed icons above the builtin ones (besides explorer).
![image](https://user-images.githubusercontent.com/8586769/81635193-7476bb00-93c5-11ea-9b11-601906bc0422.png)

**Comment by sandy081** [comment]
Thanks for filing the issue. 

@joaomoreno FYI
