### ISSUE TITLE
Important Issue for me

### ISSUE THREAD

**Issue by MannaSoumik** [microsoft/vscode#97572]
Issue Type: <b>Bug</b>

net::ERR_PROXY_CONNECTION_FAILED

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G2030 @ 3.00GHz (2 x 2993)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.97GB (5.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
Have you reviewed the information at https://code.visualstudio.com/docs/setup/network ?

**Comment by chrmarti** [comment]
Do you have HTTP_PROXY or HTTPS_PROXY environment variables or the `http.proxy` setting set?

**Comment by chrmarti** [comment]
Also: What exactly does not work?
