### ISSUE TITLE
Add support for tsdoc {@inheritDoc}

### ISSUE THREAD

**Issue by kuoruan** [microsoft/vscode#97577]
Unlike jsdoc's ```@ inheritdoc```,
tsdoc's ```@inheritDoc``` enclosed in "{ }" braces, is not supported by vscode.

```
/** {@inheritdoc IStringBuilder.append} */
```

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
