### ISSUE TITLE
[makefile] Syntax highlighting incorrect

### ISSUE THREAD

**Issue by awsdert** [Microsoft/vscode#9757]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. open any makefile
2. add
```
define defined
	$(info Checkng existance of $(1))
	$(if ifeq "$(flavor $(1))" "undefined",0,1)
endef
```
BEFORE some random lines with syntax highlighted expected
3. Look at syntax highlighting from $(1)) "undefined" onwards

Same also proves true for the origin variant of flavor
Here is an example
[paths.mk.txt](https://github.com/Microsoft/vscode/files/383477/paths.mk.txt)

**Comment by kieferrm** [comment]
Here is what that looks like:

![3sxngw7iws](https://cloud.githubusercontent.com/assets/4674940/17150730/65ee7148-5325-11e6-8b95-d5d7803821d2.gif)

**Comment by awsdert** [comment]
Same thing I get (minus the colour scheme you're using), the bottom lot
shouldn't lose their syntax highlight the moment flavor/origin gets put in
​I noticed that it seems to stem from the bracket recognition missing the
closing bracket

**Comment by awsdert** [comment]
Had to manually copy the changes to my installation but it worked so thank you :)
