### ISSUE TITLE
Opening Shell type

### ISSUE THREAD

**Issue by VineethPeddi** [microsoft/vscode#97581]
Issue Type: <b>Feature Request</b>

While executing a program in c++, vscode is showing a popup or notification.  Then notification is there are task errors.  When the output is opened it is giving an error like "The task provider for "C/C++" tasks unexpectedly provided a task of type "shell".".
  How do I resolve this issue?

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
/duplicate of #97155 and a candidate to be fixed in 1.45.1
