### ISSUE TITLE
A black marker is shown when context menu is closed

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#9758]
Testing #9723 
- VSCode Version: Latest insiders
- OS Version: OSX

Steps to Reproduce:
1. Open Terminal 
2. Right click to show context menu
3. Left click some where in terminal area to close the context menu

A black marker appears

![jul-26-2016 11-15-30](https://cloud.githubusercontent.com/assets/10746682/17132557/942f5372-5322-11e6-82a5-84bbe5d32158.gif)

**Comment by Tyriar** [comment]
It's appears to be a selection, need to check whether it happens upstream.

**Comment by Tyriar** [comment]
@sandy081 closing this off, if it still repros on Mac feel free to open on https://github.com/sourcelair/xterm.js (I don't have my Mac with me).

**Comment by Tyriar** [comment]
Fixed in #9958, https://github.com/sourcelair/xterm.js/pull/670
