### ISSUE TITLE
Update the `vscode-uri` package with `Uri.joinPath`

### ISSUE THREAD

**Issue by iliazeus** [microsoft/vscode#97580]
`Uri.joinPath` [is now a part of the API](https://github.com/microsoft/vscode/commit/00ce259594a15d21bdac58c31a17b6371d3a479f), but it's not yet in the [`vscode-uri`](https://www.npmjs.com/package/vscode-uri) npm package.

The standalone `vscode-uri` package is convenient, for example, for writing and unit testing extension modules that do not directly depend on vscode itself, but still operate `Uri`s.

**Comment by jrieken** [comment]
It's not that easy because `joinPath` uses node's `path#join`-utility. The vscode-uri package runs also in browsers so I need a good replacement or copy-paste of node's lib

**Comment by iliazeus** [comment]
There's [browserify's implementation], which matches Node.js 10.3 API.

[browserify's implementation]: https://github.com/browserify/path-browserify

**Comment by jrieken** [comment]
This happened vscode-uri@3.0.0. Becasuse its path-math utils are slightly different than the built-in once they are exposed a sibling, e.g `import { URI, Utils} from 'vscode-uri`, see https://github.com/microsoft/vscode-uri#usage-util
