### ISSUE TITLE
Close icons in Search window moved, decreased productivity

### ISSUE THREAD

**Issue by retepaskab** [microsoft/vscode#97593]
Issue Type: <b>Bug</b>

The X buttons to dismiss a search result has been moved from the right side of the window to the end of the line. Now it isn't possible to dismiss many search results without moving the mouse.
Also there is an increased probability to mistakenly hit the X when clicking on a result to open it.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|30.91GB (19.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
Bookmarks|ale|11.2.0
alignment|ann|0.3.0
close-all|ben|1.0.2
tslint|eg2|1.0.44
vs-code-xml-format|fab|0.1.5
vscode-npm|fkn|3.3.0
formatdump|pba|0.0.4
gdl-xml|pba|1.23.5
guid|kos|0.0.1
vs-color-picker|lih|1.0.0
perl-debug|mor|0.6.3
language-gettext|mro|0.1.1
python|ms-|2020.4.76186
cpptools|ms-|0.27.1
color-highlight|nau|2.3.0
printcode|nob|3.0.0
relativegoto|ret|0.0.1
perforce|sle|3.2.0
vscode-hexdump|sle|1.7.2
vscode-todo-highlight|way|1.0.4
goto-line-ex|xyz|0.0.4

(1 theme extensions excluded)

</details>

**Comment by retepaskab** [comment]
Ok, there is a setting for it.

**Comment by paulsturgess** [comment]
> Also there is an increased probability to mistakenly hit the X when clicking on a result to open it

This is happening to me _all of the time_ – what setting do I need to edit to disable this? I have searched online and not been able to find anything :(
