### ISSUE TITLE
My Code Becomes Error Codes After Run Build Task

### ISSUE THREAD

**Issue by zhuyuanzy** [microsoft/vscode#97599]
- VSCode Version:
I can't Find it.
- OS Version:
macOS Catalina 10.15.4

Steps to Reproduce:
1. I Click 'RUN' -> 'Run Build Task'
2. After this, my source code becomes error code, and except this, no more happen.

Here are pics:

![](https://s1.ax1x.com/2020/05/12/YNNEvQ.png)

After 'Run Build Task', it becomes this:

![](https://s1.ax1x.com/2020/05/12/YNNeDs.png)

![](https://s1.ax1x.com/2020/05/12/YNNKU0.png)

Does this issue occur when all extensions are disabled?:  I didn't try this

What should/can I do?

**Comment by gjsjohnmurray** [comment]
It looks like you configured your build task so gcc writes its output (the compiled code) into the .c file that contains your C source.

It's more usual to send the output to a different file, e.g. with a .o extension.

/question
