### ISSUE TITLE
No cut, copy, paste in editor context menu for untitled files

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#9759]
Refs: #9694

- VSCode Version: insiders
- OS Version: only in linux, works ok on OS X

Steps to Reproduce:

1.  Linux, open new untitled file
2.  Context menu -> there is no cut, copy, paste

![screen shot 2016-07-26 at 11 26 08](https://cloud.githubusercontent.com/assets/1926584/17132836/c521f8ee-5323-11e6-8ddb-1ec0a8fc3cc3.png)

**Comment by jrieken** [comment]
I believe that's not linux specific but an issue with 'needsTextFocus' context key... Somehow we have already lost focus before checking the keys

![screen shot 2016-07-26 at 12 16 59](https://cloud.githubusercontent.com/assets/1794099/17134498/f8808136-532a-11e6-8c51-9ddb9acfa51d.png)

**Comment by jrieken** [comment]
To verify

* open vs code
* toggle dev tools and selecting something in there
* **right** click into a writeable editor, make sure cut, copy, paste is there

**Comment by isidorn** [comment]
This looks good, but while verifying this I uncovered #9851
