### ISSUE TITLE
formatter will enter loop running

### ISSUE THREAD

**Issue by MichaelPanW** [microsoft/vscode#97598]
- VSCode Version:1.45.0
- OS Version:Windows 10

Steps to Reproduce:
I abled true Format On Save.
When I use vscode for about 10 minutes.
Formatter will enter loop running like picture.
Cannot save or close the window.
I try to use other format extensions will have the same problem.
The same problem occurs when you clear and reinstall.

![image](https://i.imgur.com/QeE9WUJ.jpg)

Does this issue occur when all extensions are disabled?: No

**Comment by jrieken** [comment]
This is a problem with the phpfmt extension, never finishing formatting. You can press the configure link to disable format on save

![68747470733a2f2f692e696d6775722e636f6d2f5165453957554a2e6a7067](https://user-images.githubusercontent.com/1794099/81692153-3da0b380-945e-11ea-98db-acf445d68e1d.jpeg)

**Comment by MichaelPanW** [comment]
But this problem not only for phpfmt
use other format extensions will have the same problem.
![image](https://i.imgur.com/l3UZ7Ny.jpg)

When i click configure just show the setting
![image](https://i.imgur.com/3swh2yU.jpg)

**Comment by jrieken** [comment]
> When i click configure just show the setting

Getter closer. Now, uncheck the setting to disable format on save. 

> But this problem not only for phpfmt use other format extensions will have the same problem.

Yeah, that sounds fishy. It seems that there is something blocking all operations on the extension host. For that use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions
