### ISSUE TITLE
Web File explorer d&d drop folder with nested files

### ISSUE THREAD

**Issue by steven166** [microsoft/vscode#97592]
I would like to drag and drop folders from my local computer in the file explorer of the web-based version of VSCode.

**Comment by isidorn** [comment]
Created this test plan item https://github.com/microsoft/vscode/issues/97714
@bpasero feel free to edit it.

**Comment by bpasero** [comment]
Cool, I did a few tweaks and increased complexity to 3 by asking to test in all our browsers. Great to see this can be verified in `yarn web`
