### ISSUE TITLE
add support for configuration variables (config) settings.json' values

### ISSUE THREAD

**Issue by GitMensch** [microsoft/vscode#97590]
According to [variable reference docs](https://code.visualstudio.com/docs/editor/variables-reference#_is-variable-substitution-supported-in-user-and-workspace-settings) there are some predefined variables that work "out if the box", including `env`.
I've just tested this and found it to work perfectly in settings for plugins:

```json
{
  "myExtension.folderList": [
    "${workspaceFolder}",
    "${env:PSModulePath}/common/sub1",
    "${env:PSModulePath}/common/sub2",
    "${env:PSModulePath}/common/sub3"
  ]
}
```

Additional to the ones supported there are [https://code.visualstudio.com/docs/editor/variables-reference#_configuration-variables](configuration variables) - but those are currently only supported for launch.json and tasks.json.

Doing so would allow for something like the following:

```json
{
  "personal.commonFolder": "${env:PSModulePath}/common",
  "myExtension.folderList": [
    "${workspaceFolder}",
    "${config:personal.commonFolder}/sub1",
    "${config:personal.commonFolder}/sub2",
    "${config:personal.commonFolder}/sub3""
  ]
}
```

... just in case I've missed it - there is no way to actually set an environment variable in users'/workspace settings, is there?

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/2809

**Comment by jason-ha** [comment]
@sandy081 I don't see this as covered by supporting env variables. This would be about supporting other config value substitution.

@GitMensch I am curious if you have example of getting substitution to work. I opened an [issue with @prettier/prettier-vscode](https://github.com/prettier/prettier-vscode/issues/1351) because `${workspaceFolder}` didn't get resolved in settings value. I have since created a test extension using Hello World sample to explore the issue myself, but could not replicate your success.

package.json:
```
	"contributes": {
		"commands": [
			{
				"command": "helloworld.helloWorld",
				"title": "Hello World"
			}
		],
		"configuration": {
			"type": "object",
			"title": "Hello World Extension",
			"properties": {
				"myExtension.folderList": {
					"type": "array",
					"markdownDescription": "Folder List",
					"scope": "resource"
				}
			}
		}
	},
```

extension.ts:
```
		let value = vscode.workspace.getConfiguration('myExtension').get('folderList');
		vscode.window.showInformationMessage('HelloWorld found ' + value + '!');
```

Result:
```
HelloWorld found ${workspaceFolder},${env:PSModulePath}/common/sub1,${env:PSModulePath}/common/sub2,${env:PSModulePath}/common/sub3!
```

**Comment by GitMensch** [comment]
I also think that `${config}` is quite different to `${env}`and that this should be reopended (I did found the second in the issue tracker but not the first when searching...)

@jason-ha my working example is a setting I use in an extension, it could be possible that the `${workspaceFolder}` is resolved somewhere in its code, of course. if you want to have a look at this: https://github.com/spgennard/vscode_cobol/issues/130 (if I remember correctly I did used `${env}` in its setting before and found it working, too).

**Comment by jason-ha** [comment]
Indeed vscode_cobol does this processing itself in [configuration.ts](https://github.com/spgennard/vscode_cobol/blob/master/src/configuration.ts#L210):
```
function getCopybookdirs_defaults(invalidSearchDirectory: string[]): string[] {
    let editorConfig = workspace.getConfiguration('coboleditor');
    let dirs = editorConfig.get<string[]>('copybookdirs');
    if (!dirs || (dirs !== null && dirs.length === 0)) {
        dirs = DEFAULT_COPYBOOK_DIR;
    }

    let extraDirs: string[] = [];

    for (let dirpos = 0; dirpos < dirs.length; dirpos++) {
        let dir = dirs[dirpos];

        /* remove ${workspaceFolder} */
        dir = expandEnvVars(dir);

        if (dir.startsWith("${workspaceFolder}")) {
            dir = dir.replace("${workspaceFolder}", "").trim();

            // remove / or \ forward
            if (dir.startsWith('/') || dir.startsWith('\\')) {
                dir = dir.substr(1).trim();
            }
        }

        // ignore empty elements
        if (dir.length !== 0) {
            if (dir.startsWith("$")) {
                var e = process.env[dir.substr(1)];
                if (e !== undefined && e !== null) {
                    e.split(path.delimiter).forEach(function (item) {
                        if (item !== undefined && item !== null && item.length > 0) {
                            if (isDirectory(item)) {
                                extraDirs.push(item);
                            } else {
                                invalidSearchDirectory.push(item);
                            }
                        }
                    });
                } else {
                    invalidSearchDirectory.push(dir);
                }
            } else {
                if (dir !== ".") {
                    extraDirs.push(dir);
                }
            }
        }
    }

    return extraDirs;
}
```

**Comment by jason-ha** [comment]
I also looked around VS Code code for the internal support. I found [IConfigurationResolverService ](https://github.com/microsoft/vscode/blob/4a8dc15b9511154fedc572c930df0a072762caa1/src/vs/workbench/services/configurationResolver/common/configurationResolver.ts) and implementation [AbstractVariableResolverService](https://github.com/microsoft/vscode/blob/9450b5e5fb04f2a180cfffc4d27f52f972b1f369/src/vs/workbench/services/configurationResolver/common/variableResolver.ts#L28), but I don't see public exposure / documentation apart from some debugging support.

**Comment by sandy081** [comment]
#2809 is an umbrella item for variable substitution.

**Comment by GitMensch** [comment]
@sandy081 If vscode team wants to do all variants with one (I still believe `env` substitution to be too different from `config`) then please edit the title of #2809 making this obvious.
Substitution for `env` entries has multiple issues found in the issue search, `conf` entries not.

I suggest a title like: "Support variable substitution when resolving values in settings (environment, config, ...)" and add a note to it - this is the only way people can know what they vote the other issue for.
