### ISSUE TITLE
Documnet tabs - more user friendly navigation

### ISSUE THREAD

**Issue by it-xtech-dev** [microsoft/vscode#97597]
When multiple document tabs are open and overflowing available width it is hard do access hidden tabs. There could be potentially multiple solution for this problem. I have noted some ideas below:
1. Dropdown for hidden tabs at the end of tabs line.
2. Make scroll bar thicker or make it thicker when hovered with some (0,5s) delay.

Generally scrollbars are thin and hard to spot and click. 

I'm using VS on windows 10 and MacOs Catalina.

It Man.

**Comment by bpasero** [comment]
@it-xtech-dev you can maybe play around with configuring:
* `"workbench.editor.tabSizing": "shrink"`
* `"workbench.editor.titleScrollbarSizing": "large"`
