### ISSUE TITLE
invalid user name and password

### ISSUE THREAD

**Issue by mmshareef** [microsoft/vscode#97609]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

I got  a promt while pushing code to git hub to authorise vs code.
After i went ahead with the authorisation I was able to push the changes to git but later when i tried to push other changes to the the git repository I am a recieving a message invalid/missing credentials. I tried revoking vs code's authrisation and pushing the changes to git hub but the problem still persists

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:10:24.511Z)
OS version: Linux x64 5.3.0-46-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2433)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 1, 1|
|Memory (System)|3.75GB (1.10GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
bootstrap-snippets-vscode|bha|0.3.0
the-powerful-bootstrap|Cro|1.2.4
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.6.0
bootstrap-4-cdn-snippet|eve|1.4.1
auto-close-tag|for|0.5.7
angular-bootstrap|her|4.0.9
stylelint-plus|hex|0.52.10
python|ms-|2020.4.76186
color-highlight|nau|2.3.0
jade-bootstrap|pac|0.2.7
material-icon-theme|PKi|4.1.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
sass-indented|syl|1.8.3
bootstrap4-vscode|the|6.1.0
Bootstrap-extension-pack|wal|0.0.3
bootstrap-3-snippets|wcw|0.1.0
bootstrap-v4-snippets|Zac|1.1.3

</details>

![Screenshot from 2020-05-12 15-14-29](https://user-images.githubusercontent.com/61781425/81691866-2ae8a780-947b-11ea-8169-969933fd6839.png)

![Screenshot from 2020-05-12 15-14-29](https://user-images.githubusercontent.com/61781425/81691885-320fb580-947b-11ea-957f-4b2a4e6df430.png)

**Comment by joaomoreno** [comment]
Does the `/run/user/1000/snap.code` directory existe?
