### ISSUE TITLE
builtin cpp extension should define common problem matchers

### ISSUE THREAD

**Issue by GitMensch** [microsoft/vscode#97600]
The builtin cpp extension provides syntax highlighting and more, it is reasonable to have it define common problem matchers, too (documenting how to manually add this is good, but it should be pre-defined already).

The most common one is likely gcc but cl should be defined, too.

**Comment by alexr00** [comment]
The Microsoft C/C++ extension provides these problem matchers. We want to provide syntax highlighting out of the box, but if you need a problem matcher that is better provided by an installable extension where folks more expert in that language can do it justice.

**Comment by GitMensch** [comment]
> We want to provide syntax highlighting out of the box, but if you need a problem matcher that is better provided by an installable extension where folks more expert in that language can do it justice.

Thank you for this note, sounds reasonable.
Although I do wonder why you'd have to be an expert in a language for a common pattern match.

> The Microsoft C/C++ extension provides these problem matchers

I see, looks nearly identical. The issue with this extension and its dependency is that those are not MIT-Licensed like the builtin extension. Is there a possibility that this will change?
