### ISSUE TITLE
typescript extension yields errors when compiler does not

### ISSUE THREAD

**Issue by eankeen** [microsoft/vscode#97607]
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 5.6.8-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2399)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 6, 7|
|Memory (System)|7.70GB (0.17GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (79)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|11.1.0
flutter-snippets|ale|2.0.0
jest-snippets|and|1.8.0
vscode-database|baj|2.2.0
vscode-node-readme|ben|3.0.2
markdown-preview-github-styles|bie|0.1.6
better-toml|bun|0.3.2
simple-react-snippets|bur|1.2.2
solargraph|cas|0.21.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.1.2
vscode-zonefile|Com|0.0.4
language-postcss|cpy|1.1.0
dart-code|Dar|3.10.1
flutter|Dar|3.10.1
vscode-markdownlint|Dav|0.35.1
vscode-eslint|dba|2.1.5
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.14.5
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.6.0
gitlab-workflow|fat|2.2.0
vscode-firefox-debug|fir|2.8.0
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.2
vscode-yarn|gam|1.7.0
vscode-pull-request-github|Git|0.15.0
webpack-snippets|gog|0.0.4
ansible|haa|0.2.8
CppSnippets|har|0.0.14
vue-snippets|hol|0.1.11
svelte-vscode|Jam|0.9.3
vscode-deno|jus|1.27.0
vscode-github|Kni|0.30.3
terraform|mau|1.4.0
vscode-language-babel|mgm|0.0.27
hg|mrc|1.3.0
vscode-azureterraform|ms-|0.3.0
vscode-docker|ms-|1.1.0
vscode-kubernetes-tools|ms-|1.2.0
mssql|ms-|1.9.0
python|ms-|2020.4.76186
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
azure-account|ms-|0.8.11
cpptools|ms-|0.27.1
Go|ms-|0.14.1
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-next|ms-|4.0.20200511
debugger-for-chrome|msj|4.12.6
vscode-react-native|msj|0.15.0
sqltools|mtx|0.21.7
vetur|oct|0.24.0
marko|pca|0.4.0
material-icon-theme|PKi|4.1.0
tsimporter|pmn|2.0.1
polacode|pnp|0.3.4
typescript-hero|rbb|3.0.0
ruby|reb|0.27.0
vscode-yaml|red|0.8.0
markdown-preview-enhanced|shd|0.5.3
vscode-wl|shi|1.7.3
move-ts|str|1.12.0
vscode-stylelint|sty|0.84.0
vscode-gulp|tan|0.0.4
shellcheck|tim|0.9.0
errorlens|use|3.1.1
vscode-ruby|win|0.27.0
JavaScriptSnippets|xab|1.8.0
clang-format|xav|1.9.0
yarn-ui|xqc|0.1.2
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|2.8.0
vscode-proto3|zxh|0.4.2

(2 theme extensions excluded)

</details>

Steps to Reproduce:
```sh
git clone https://github.com/eankeen/repro-typescript-extension-false-positives
cd repro-typescript-extension-false-positives
code .
```

Haii, it looks like the built in typescript extension shows `Cannot find module './thing'` - even though the project compiles successfully? Wasn't sure what do do, but I downloaded the 'JavaScript and TypeScript Nightly' (`ms-vscode.vscode-typescript-next`) and a 'TypeScript Importer' (`pmneo.tsimporter`) package, but that didn't get rid of the error. Image below depicts error and successful compilation. Note that I added the "rootDir" in the `one/tsconfig.json` folder because I thought that might help - but it doesn't.

![image](https://user-images.githubusercontent.com/24364012/81685224-c1ca4b00-940c-11ea-8398-fbec2e552333.png)

Does this issue occur when all extensions are disabled?: [No]

If you need any other information let me know

Thanks,
Edwin

**Comment by graygilmore** [comment]
Surprised to not see more issues posted about this. I'm also experiencing this but with relative paths. Only started ~1.45.0 and persists after today's update to 1.45.1. Occurs with or without extensions disabled.

**Comment by mjbvz** [comment]
I can't repo this in the latest VS Code insiders (1.47) using that example project

@eankeen Do you only see this when extensions are enabled? If so, then please file an issue against whichever extension is causing this
