### ISSUE TITLE
Status bar is eager to please

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#97605]
1. Click the git branch indicator, it opens quick open
2. Go down to the currently checked out branch, press <kbd>Enter</kbd> once

🐛 Quick open appears again

It seems that quick open eats the <kbd>Enter</kbd> key down event, but status bar handles the key up event and triggers the action once again.

**Comment by isidorn** [comment]
3. Make sure that the editor area is empty
In order to repro and verify
