### ISSUE TITLE
ERROR running force:source:retrieve: Cannot read property 'getWorkspaceElements' of undefined

### ISSUE THREAD

**Issue by cantoniac** [microsoft/vscode#97606]
Issue Type: <b>Bug</b>

sfdx:Retrieve source in Manifest from org

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (1.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
xml|Dot|2.5.0
prettier-vscode|esb|4.6.0
java|red|0.61.0
vscode-xml|red|0.11.0
salesforcedx-vscode|sal|48.14.0
salesforcedx-vscode-apex|sal|48.14.0
salesforcedx-vscode-apex-debugger|sal|48.14.0
salesforcedx-vscode-apex-replay-debugger|sal|48.14.0
salesforcedx-vscode-core|sal|48.14.0
salesforcedx-vscode-lightning|sal|48.14.0
salesforcedx-vscode-lwc|sal|48.14.0
salesforcedx-vscode-visualforce|sal|48.14.0
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.10.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.3

</details>

**Comment by alexdima** [comment]
@cantoniac Can you please provide some steps. I don't see this error. Does this error reproduce when you disable all extensions?

**Comment by gjsjohnmurray** [comment]
@alexdima this is likely to be caused by one of the Salesforce (sfdx) extensions @cantoniac is using.

**Comment by alexdima** [comment]
@cantoniac can you please report this directly against to Salesforce?
