### ISSUE TITLE
URL detection in terminal includes closing square bracket

### ISSUE THREAD

**Issue by georgemarrows** [microsoft/vscode#97617]
Issue Type: <b>Bug</b>

Here's a URL in the embedded VS Code terminal, as output by the Google Cloud cli tool:

```
target url:      [https://georgem1-dot-xxx.appspot.com]
```

When I command-click on it, it tries to open

https://georgem1-dot-xxx.appspot.com]/

**NB the trailing square bracket has been wrongly included.**

Not the most important bug, but consistently annoying!

Thanks for VS Code.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 18.7.0

**Comment by Tyriar** [comment]
Should be fixed with new link system: `"terminal.integrated.experimentalLinkProvider": true`
