### ISSUE TITLE
Default directory

### ISSUE THREAD

**Issue by Mystic8b** [microsoft/vscode#97618]
If you change the default directory using `cd ~ /` (for example) in `.bashrc`, then after opening the project with `.code` in the vscode terminal, this default directory opens. I would like to be able to change it at the system level to avoid such a problem, maybe through wsl.conf or something else.

**Comment by joaomoreno** [comment]
I really don't understand what the issue is, sorry. Do you mind rephrasing that? Maybe give me steps to reproduce it?

**Comment by Mystic8b** [comment]
Sure.
When opening the terminal, the default working directory: /mnt/c/Users/MyUser
![image](https://user-images.githubusercontent.com/35394377/81723827-1660db00-948c-11ea-926d-00fff94e45f1.png)
This is not convenient for me, I changed the directory by adding the line `cd ~` to `/home/myuser/.bashrc`
After that, when I open the terminal, the user’s home directory opens. 
![image](https://user-images.githubusercontent.com/35394377/81724343-e1a15380-948c-11ea-8fdf-2498af1c5718.png)
But if then I go to /home/myuser/projects/myproject and execute `.code` to open the project in vscode:
![image](https://user-images.githubusercontent.com/35394377/81724605-55dbf700-948d-11ea-8c42-9b4c729203ed.png)
then in the vscode terminal I do not open the project directory, but the home directory opens, as cd ~ is executed from .bashrc
![image](https://user-images.githubusercontent.com/35394377/81724788-9e93b000-948d-11ea-8c6a-3b3cf419ff60.png)

**Comment by Mystic8b** [comment]
Wow, this can be changed with `startingDirectory`
Ok, im done :D
