### ISSUE TITLE
'Terminal: Copy Selection' no way to be executed from the command palette

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#9761]
Refs: #9100 

Linux, insiders
1. Try to execute the command 'Terminal: Copy Selection' from the command palette
2. There is no way to do this, since when the command palette has focus the terminal does not and the action will complain
3. I would expect the action to still work, or to not be present in the command palette

This action and the paste into intregrated terminal do not feel like global workbench actions to me. Due to this and #9760 I propose to remove them from the command pallete. If there is no mechanism for global workbench actions to be omitted from the command pallete we should introduce one, since these actions should not be in the command pallete imho

**Comment by Tyriar** [comment]
This is a know issue, it can be made to work once virtual selection is added to xterm.js https://github.com/sourcelair/xterm.js/issues/207

**Comment by Tyriar** [comment]
This will be fixed when we manage the selection model ourselves https://github.com/Microsoft/vscode/issues/9958

**Comment by Tyriar** [comment]
Fixed in https://github.com/sourcelair/xterm.js/pull/670
