### ISSUE TITLE
VS: The workspace doesn't have a GIT repository (if node_modules are soft links)

### ISSUE THREAD

**Issue by sashilazar** [microsoft/vscode#97620]
I just upgraded to 1.45.   Since I kept switching between branches, I had "node_modules" as a soft link to "node_modules.branchA" or "node_modules.branchB", depending on which branch I had checked out.

Except that VS says "The folder doesn't have a GIT repository".   It turns out that "git status -z -u" gave an error if the "node_modules" folder was linked.    Once I removed the link and renamed the correct node_modules folder, the GIT tools were available in VS.

**Comment by joaomoreno** [comment]
> It turns out that "git status -z -u" gave an error if the "node_modules" folder was linked

Then it's a git issue, not VS Code.
