### ISSUE TITLE
Export manager instance and typings from extensions/image-preview 

### ISSUE THREAD

**Issue by Janne252** [microsoft/vscode#97624]
If I wanted to create an extension that allows previewing image formats that aren't supported by the bundled extension `image-preview` (image type not supported by Chromium?), I could save a lot of effort and time by being able to utilize `image-preview` extension and take advantage of its features:
- Zooming
- Image resolution info (Status bar item)
- Image file size info (Status bar item)

### Proposal: Take advantage of existing API: vscode.extensions.getExtension('&lt;id&gt;')

Example:
```typescript
import * as vscode from 'vscode';
import * as ImagePreview from 'vscode/extensions/image-preview';
const imagePreview = vscode.extensions.getExtension('vscode.image-preview') as vscode.Extension<ImagePreview>;

// in a CustomReadonlyEditorProvider
class MyCustomReadonlyEditorProvider implements vscode.CustomReadonlyEditorProvider {
    openCustomDocument(uri: vscode.Uri, openContext: vscode.CustomDocumentOpenContext, token: vscode.CancellationToken) {
        return { uri, dispose: () => { } };
    }
    resolveCustomEditor(document: vscode.CustomDocument, webviewPanel: vscode.WebviewPanel, token: vscode.CancellationToken) {
        // convert the image to a more standard image document like PNG
        const convertedDocument = ...;
        imagePreview.manager.resolveCustomEditor(convertedDocument, webviewPanel, token);
    }
}
```
Being able to directly work with the manager instance would allow taking advantage of the existing status bar items. If there's ever going to be a status bar item that describes the image pixel format or other image meta data, those could also be used with other image formats.

**Comment by mjbvz** [comment]
I suggest starting by forking the image-preview extension. If there are a bunch of extensions that end up doing this, we could investigate adding an API instead. Making the preview generic will complicate things so I don't want to look into this unless there are good use cases

**Comment by Janne252** [comment]
Thanks for the reply. As the bundled extension is part of the vscode repository, I can't just fork a singular extension without cloning entire vscode repository. I think my approach to prototyping and testing this concept of sharing the image preview functionality amongst multiple non-web image format preview extensions will be based on a copy of the `vscode.image-preview` extension with some modifications to allow usings its providers, since extensions can require other extensions (`extensionDependencies`).
