### ISSUE TITLE
[tab completion] Don't complete if selection is not empty

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#9762]
Testing #9698:

- enable tab completion: `"editor.tabCompletion": true`
- create a html snippet
```json
	 "Div": {
		"prefix": "div",
		"body": [
			"<div>",
			"    ${}",
			"</div>"
		],
		"description": "New div"
	}
```
- in a html file have a line with content 'div', select the whole line from left to right, press tab
-> div is expanded. I would expect it to be indented.
IMO we should only do tab completion on an empty selection, so that it's also possible to indent a line.

**Comment by jrieken** [comment]
Unsure - other editor support tab completion with a selection...

**Comment by aeschli** [comment]
But adding indentation with tab should still reliable work. Right now if your selection ends with snippet prefix the whole selection is replaced by a snippet.
![indent-with-tab](https://cloud.githubusercontent.com/assets/6461412/17139034/2783da10-5343-11e6-812b-7f8e57e04d4f.gif)

**Comment by jrieken** [comment]
Yeah
