### ISSUE TITLE
Terminal copy / paste shortucts make a confusing user experience

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#9763]
Refs: #9100

1. `ctrl + shift + c`, and `ctrl + shift + v` are copy / paste when terminal has focus
2. these keybindings do some completly different actions when terminal does not have focus. Both these actions are 'heavy', opening preview and opening a terminal outside of vscode
3. While I tested the copy / paste feature I accidently triggered the other actions multiple times and this led to a very frustrating experience

My suggestions is that these actions should be disabled when terminal is visible. Not when terminal has focus, imho that is the biggest flow of the current approach. If these actions were enabled when terminal is visible they could also be exectued from the command palette (my concers around this are raised in other bugs).

**Comment by Tyriar** [comment]
Requesting feedback from @kieferrm (markdown preview) @bgashler1 (general UX). Personally I think it's fine currently but curious what others think.

Related: #8818

**Comment by Tyriar** [comment]
Closing off since I got no more feedback. Also keybindings can be customized now and #8818 will improve upon this even more by adding a `terminalSelection` (or similar) state.
