### ISSUE TITLE
Emmet kicks in when editing pure xml documents

### ISSUE THREAD

**Issue by fbricon** [microsoft/vscode#97632]
- VSCode Version: 1.45.0 and 1.46.0-insiders
- OS Version: macOS Catalina 10.15.4

Steps to Reproduce:

1. Create an xml document. containing 
```xml
<a>

</a>
```
2. Within the `<a>` tag, start typing `a`, emmet proposes a *ton of snippets.

<img width="1011" alt="Screen Shot 2020-05-12 at 7 52 19 PM" src="https://user-images.githubusercontent.com/148698/81728365-a140d600-948a-11ea-8126-00d5678e31f7.png">

Emmet should not contribute to xml completion with unrelated HTML bloat.

Does this issue occur when all extensions are disabled?: Yes

**Comment by iamkacperwasik** [comment]
As the docs says:

> Emmet abbreviation and snippet expansions are enabled by default in html, haml, pug, slim, jsx, `xml`, xsl, css, scss, sass, less and stylus files, as well as any language that inherits from any of the above like handlebars and php.

You can disable `emmet` for `xml` in `settings.json` like so
```json    
"emmet.excludeLanguages": [
    "xml"
]
```

[Read here](https://code.visualstudio.com/docs/editor/emmet) for more info.

**Comment by rzhao271** [comment]
I forgot that workaround existed.
I still think that XML, even when Emmet is enabled, shouldn't output HTML abbreviations, though, which it still does.

**Comment by rzhao271** [comment]
Reopening because it turns out that now the suggestion hides only when it exactly matches, e.g. `a` doesn't show the `<a>` suggestion but still shows all the other HTML suggestions.
