### ISSUE TITLE
HDR compatibility

### ISSUE THREAD

**Issue by Linferz** [microsoft/vscode#97634]
Hello!
On my HDR monitor when HDR feature are switched on, application window is  very dark. Its very uncomfortable to work with that.

Its much lighter on a screenshot than IRL

![DSC_0129](https://user-images.githubusercontent.com/65249634/81731261-5da09900-9497-11ea-8ca9-f3f933646622.JPG)

![Снимок1](https://user-images.githubusercontent.com/65249634/81731060-19ad9400-9497-11ea-834a-b761952f8873.PNG)

**Comment by deepak1556** [comment]
I am merging this to https://github.com/microsoft/vscode/issues/88491 , please follow the workaround mentioned there. Thanks!
