### ISSUE TITLE
Would you be interested in providing a (brief) JSONC/"JSON with Comments" spec somewhere?

### ISSUE THREAD

**Issue by ell1e** [microsoft/vscode#97635]
Could you possibly be interested in providing a (brief) JSONC/"JSON with Comments" spec somewhere? https://code.visualstudio.com/docs/languages/json#_json-with-comments says it allows comments, but it does seem to also allow trailing commas I've heard from another place. Would it be possible to put somewhere the exact extensions it allows compared to strict JSON, so that it can be implemented the same in other projects? (E.g. I'd like to use the format too, but I don't want to call it "JSON", but if I call it "JSON with Comments" people might expect the same featureset as in VS Code, but I don't even know what exactly the featureset is)

**Comment by aeschli** [comment]
It's really just intended to be used for the VSCode settings files. No ambition to define and champion a new JSON flavor / standard.

**Comment by ell1e** [comment]
@aeschli could you maybe add just informal 1-2 sentences to the section I linked for a more complete listing of the derivations it supports at least? Also please note a lot of places refer to parsing it "like VS Code's jsonc", that is also how I got to that link. So you kind of seem to have defined a new JSON flavor already, just very vaguely.
