### ISSUE TITLE
Undo `any` type

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#97636]
This is causing a compilation error both in `yarn watch` and in VS Code:

https://github.com/microsoft/vscode/commit/cd93eaacd56fcac764e0bfb588884c9d9161f778

**Comment by mjbvz** [comment]
Hey I don't think this change is. Just delete the `node_modules` under `search-results` and run yarn again

**Comment by mjbvz** [comment]
Builds were also green with my original change in: https://dev.azure.com/vscode/VSCode/_build/results?buildId=43448&view=results

Let me know if you see any failures in the build tasks

**Comment by joaomoreno** [comment]
Was missing to remove `node_modules`, I expected yarn to simply do the right thing. 🤔
