### ISSUE TITLE
Trailing slash added to remote repository URL

### ISSUE THREAD

**Issue by L0xl3y** [microsoft/vscode#97637]
## The problem 
Right now I cannot push code to a remote repository due to the fact that VSCode adds a trailing slash at the end of the URL.

This happens with both the WSL and PowerShell terminals

## Steps to reproduce
Add the remote repository with the following command.
git remote add origin https://github.com/Username/SomeRepo.git

Verify that that it has been added successfully.
git remote -v
both for push and pull tags should show and have identical URL's.

Push code to said remote repository
git push origin master

After which you should be prompted to enter your details.
After doing so, it returns with the following message
remote: Repository not found
fatal: repository 'https://github.com/Username/SomeRepo.git/' not found

**Comment by joaomoreno** [comment]
Can you please provide a [screen recording](https://gifcap.dev/)?

**Comment by L0xl3y** [comment]
Somehow the issue has resolved itself, did a git pull and now everything works as expected
