### ISSUE TITLE
Exclude private package files from auto import

### ISSUE THREAD

**Issue by fgarcia** [microsoft/vscode#97631]
I work on a mono repo and I would like vscode to stop auto importing from private, non-built files of my packages. Some of my packages are just package-prototypes (without their own package.json file) 

For example if I have

```
packages/foo/src/tool.js
packages/foo/index.js
```

I would like to import `tool` from `packages/foo` and not `packages/foo/src/tool`. 

The most similar issue is https://github.com/microsoft/vscode/issues/52087 which was closed as a duplicate of https://github.com/microsoft/vscode/issues/35350, but I am not sure how they compare or how https://github.com/microsoft/vscode/issues/35350 could solve this

Ideally some option with a pattern list to exclude import suggestions. In my case it could be `exclude: ['**/src/*']`

**Comment by mjbvz** [comment]
Actually this is a duplicate of https://github.com/microsoft/TypeScript/issues/35395

We are still waiting for more feedback upstream so please upvote that issue
