### ISSUE TITLE
Support CodeLens in diff editor

### ISSUE THREAD

**Issue by ludokx** [microsoft/vscode#97640]
Related to issue [monaco-editor #1909](https://github.com/microsoft/monaco-editor/issues/1909), it would be great to be able to add code lenses to the diff editor (original and/or modified) but they are hard coded to be disabled in diff editors (see [here](https://github.com/microsoft/vscode/blob/6d70b4f04271dfd5c9f0693a4c7952fdc9c72b7d/src/vs/editor/browser/widget/diffEditorWidget.ts#L1051)).

It should be possible to enable CodeLens in the original/modified editor with editor options.

**Comment by alexdima** [comment]
In VS Code, this is available via the setting `diffEditor.codeLens`, which acts very similarly to `editor.codeLens`.
