### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by LittleJeff1** [microsoft/vscode#97648]
Why do I keep getting a message "Permission Denied" in the terminal when I try to run my code? I was just trying to follow a tutorial and do the Hello World message in Python but I keep getting that permission denied message .

**Comment by LittleJeff1** [comment]
![image](https://user-images.githubusercontent.com/57117920/81752988-bd3f7a00-9480-11ea-967f-009efb52663a.png)

**Comment by alexdima** [comment]
@LittleJeff1 Your terminal looks like bash, but it looks like you are editing files on Windows. Did you configure this integrated terminal on purpose? Could you double check the settings you have?

**Comment by DTKx** [comment]
Hello!
I have been having almost the same issue here, i was looking for similar open issues and I found this one here.
I just changed from spyder to VS and i am trying to use the virtual environment features of VS, however when I tried to create a virtual environment the Permission denied error appears:
![image](https://user-images.githubusercontent.com/63344441/83289960-24ca2900-a1e6-11ea-8add-7c88674438f1.png)

I have already checked if the python was added to path and it is, moreover I can access python throught the cmd normally.
![image](https://user-images.githubusercontent.com/63344441/83290048-4b885f80-a1e6-11ea-99a2-f98128ae56a8.png)
![image](https://user-images.githubusercontent.com/63344441/83290147-75da1d00-a1e6-11ea-9d0b-50d60f2f573e.png)

This are my json configurations
![image](https://user-images.githubusercontent.com/63344441/83290193-91ddbe80-a1e6-11ea-8c3e-a76534d5df99.png)


This is the Visual Studio that i am using
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Any clue is  usefull :)
Thanks

**Comment by DTKx** [comment]
Moreover,i do not recall having changed the integrated terminal to the git bash. Is there any other default setting?
However i did tried to completelly unistall VS in order to clean up any installations mistakes i might have made, however i was not well succeeded. So also if you can advise of how to completelly uninstall it would be welcomed

**Comment by codingbelhaous** [comment]
i have the same issue when i try to writte ./hello it wont run for me eather  and i dont know what to do ige t this message hope u could help me 
bash: ./hello: Permission denied 
![Capturec](https://user-images.githubusercontent.com/109922546/184257102-d0f8d0bc-760d-4c84-81dc-a0884184cfc3.PNG)
