### ISSUE TITLE
@pytest.mark.xfail undefined

### ISSUE THREAD

**Issue by rayfranrocha** [microsoft/vscode#97647]
- VSCode Version: 1.45.0
- OS Version: MacOS Mojave (10.14.6)

Steps to Reproduce:
1. I created a test_file.py and I want to write a test that I expect some error. Then I tried to put @pytest.mark.xfail. When I run the test I got "undefined" as the answer.
2. I import pytest and I try to use the autocomplete after @pytest.mark. I don't have 'xfail' as an option, it only shows _markers and _config
3. I write manually the annotation @pytest.mark.xfail
4. I ran pytest -runxfail the test run ok
5. but when I try to use: View > Command Pallet > Python: Configure Tests > pytest framework > folder pytest... I got the undefined error as the output and the test is skiped

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by alexdima** [comment]
@rayfranrocha This appears to be an issue with the python extension, not with vscode itself. Please open an issue directly against https://github.com/Microsoft/vscode-python/issues if you use the `ms-python.python` extension.
