### ISSUE TITLE
Code Normalization

### ISSUE THREAD

**Issue by Shekhrozx** [microsoft/vscode#97656]
### Before

```
for(var i=0;i<10;i++){
console.log("hello world!");
}
```

### After

```
for(var i  = 0; i < 10; i++) {
     console.log("hello world!");
}

```

**Comment by trizin** [comment]
The code formatting is available in Visual Studio Code through the following shortcuts:

 - On Windows <kbd>Shift</kbd> + <kbd>Alt</kbd> + <kbd>F</kbd>
 - On Mac <kbd>Shift</kbd> + <kbd>Option</kbd> + <kbd>F</kbd>
 - On Linux <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>

Or you can right click the file and select format document from the menu.
Also I highly recommend you to check the [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) extension
