### ISSUE TITLE
vscode difftool switch editor with keyboard

### ISSUE THREAD

**Issue by starjesse** [microsoft/vscode#97658]
![image](https://user-images.githubusercontent.com/33248281/81762949-8ad56180-9500-11ea-89a9-28c6b0550492.png)
When I use vscode diffmode(code -d) to compare two files, I always want to copy something from the left side to the right side, or from the right side to left side. 
But now I can only click one side with mouse, copy the code, and then click another side, paste the code.

Is there any way to switch the editor with the keyboard(like vimdiff 'ctrl w + w')? Or use the modification directly(like vimdiff 'dp' and 'do')?

**Comment by saurabh-hirani** [comment]
This is an indispensable feature if you are used to vim - please add support for it - as using the mouse to switch editors is a pain.
