### ISSUE TITLE
Theme does not update if auto-updated by OS X when window.autoDetectColorScheme is enabled

### ISSUE THREAD

**Issue by aterenin** [microsoft/vscode#97652]
- VSCode Version: 1.45.0
- OS Version: Catalina

Steps to Reproduce:

1. Set "window.autoDetectColorScheme" to "true".
2. Set "Appearance" to "auto" in System Preferences.
3. Wait for OS to change dark mode due to time of day. Theme will not update. Note that the theme does update if manually changed in System Preferences.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aterenin** [comment]
Weird - just had the color scheme auto-switch by the OS and this time it did update. On the other hand, the previous two days it did not. This issue may not reproduce consistently - I'll try to see if I notice anything which seems to affect it.

**Comment by mcnesium** [comment]
I see this on Manjaro Gnome ([Matcha theme](https://github.com/vinceliuice/Matcha-gtk-theme/) light/dark), except that it has never worked over here before.

**Comment by aterenin** [comment]
Had this fail again today. Definitely seems like a non-deterministic problem.

**Comment by aeschli** [comment]
This got fixed for OSX for October.
Note that for Linux that still is not supported (waiting for Electron support. Issue is #102795
