### ISSUE TITLE
Completion adds more duplicate snippets as you type

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#97659]
Version: 1.46.0-insider (user setup)
Commit: 288852d8c26d797974bfb8aed06e1bff9b809223
Date: 2020-05-12T05:43:31.363Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
Steps to Reproduce:

Completion adds more duplicate snippets as you type

![image](https://user-images.githubusercontent.com/148698/81757302-ba637a00-94be-11ea-894c-bcf30233e268.gif)

We have predefined some snippets in a [json file](https://github.com/redhat-developer/vscode-java/blob/master/snippets/java.json) and registered them in package.json. Meanwhile, the language server side will also contribute some other snippets.

This issue only happens in 1.46 insider version, in the stable version (1.45.0), it works fine. So I guess it's a regression in the insider?

Also, if I just start the client side (not launch the language server), the duplication won't be observed. Does that mean something wrong when merging the results from client & server when providing the completion list?

**Comment by jrieken** [comment]
>  Meanwhile, the language server side will also contribute some other snippets.

I can repro for Java but not for TypeScript... How does the language service contribute these other snippets? Does it tweak the snippet file on disk?

**Comment by jdneo** [comment]
The language server will resolve some other snippets according to the context. It won't tweak the snippet json file.

**Comment by jrieken** [comment]
Ok - this only happens when using incomplete results list and is due to bogous provider filtering, e.g the snippet provider is asked again for suggestion despite its suggestion being kept...

**Comment by jdneo** [comment]
@jrieken Thank you, I'll test it after new insider released and let you know if the problem fixed.

**Comment by jdneo** [comment]
@jrieken Verified the issue has been fixed. Thank you!
