### ISSUE TITLE
Enable history in input prompt

### ISSUE THREAD

**Issue by felipecassiors** [microsoft/vscode#97655]
To provide a way to enable history in the input prompt, used for `launch.json` and `tasks.json`. This would enable developers to re-use the previously used values for the same input, without having to edit the `default` field all the time.

See this practical example (from https://github.com/rogalmic/vscode-bash-debug/pull/139):
![](https://user-images.githubusercontent.com/29582865/81350560-948e3d80-9098-11ea-96d4-dc4e6d1fbd9e.gif)

Instead of writing manually or relying on the `default` value, it would be extremely useful to have a history of the last used values, which could be presented as a list of options to pick above of input prompt or even simply having the last value in the field (instead of the `default`).

In this specific scenario, I'm debugging a big amount of bash scripts in a single repository, all of them with their own set of optional and positional arguments (and any sort of mix between them), which makes unfeasible to create a new `configuration` property in `launch.json` for every possibility. 

But this, of course, would not be only useful for this, since the input prompt is acceptable from other fields as well.

For the specification, it could be something like (look at the commented line): 
```JSONC
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "bashdb",
      "request": "launch",
      "name": "Bash-Debug (simplest configuration)",
      "program": "${file}",
      "cwd": "${workspaceFolder}",
      "argsString": "${input:arguments}"
    }
  ],
  "inputs": [
    {
      "id": "arguments",
      "type": "promptString",
      "default": "--help",
      "history": true, // <-- this activates the history for this input
      "description": "The arguments to pass to the script"
    }
  ]
}
```

**Comment by weinand** [comment]
@felipecassiors so you are asking for a history mechanism on the string input box for "input variables", right?
Please note that "input variables" are independent from "launch.json" and work in "tasks.json" too.

**Comment by felipecassiors** [comment]
Right. 

Cool to see it's being used in different places, which means this feature could be useful in more scenarios. 

However, I think in some scenarios you might not want to use this, that's why I think it should be configurable.
