### ISSUE TITLE
Infinite initializing JS/TS language features

### ISSUE THREAD

**Issue by nad182** [microsoft/vscode#97657]
Issue Type: <b>Bug</b>

The issue is only with one project (everything works fine in other projects). "Got to definition", auto-imports, intellisense - nothing works. Actually, it works for a few seconds, when the project is just opened, but then stops.
After 5 minutes I get an error that 
> The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

I've tried the following: 
- different versions of VS Code (March and April updates)
- different Typescript version (3.8.3, 3.7.4), enabling and disabling extensions
- removing/reinstalling `node_modules`
- `files.exclude` and `files.watcherExclude` of `build` and `node_modules` folders
- restarting typescript server
- disabling/re-enabling `TypeScript and JavaScript Language Features` extension

The last time I worked on this project (couple of moths ago), the issue was NOT present.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 8, 7|
|Memory (System)|16.00GB (5.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.1.2
vscode-eslint|dba|2.1.5
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.6.0
vscode-docker|ms-|1.2.0
debugger-for-chrome|msj|4.12.6

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)? It includes the latest typescript version

**Comment by nad182** [comment]
@mjbvz , thanks for your reply! I've just tried the insiders build and the issue seems to have disappeared. Does it mean I need to stick with this VS Code build for this particular project? 

Please, also allow some more time for experiencing the current build (and making sure I don't face the same problem again) before closing this issue.

**Comment by mjbvz** [comment]
Thanks for testing. The insiders build includes a new TypeScript version (3.9) that may fix this. We will ship this new TS version with VS Code 1.46

Let me know if you still see this in VS Code insiders of with VS code 1.46+
