### ISSUE TITLE
Snippets can not be first suggestion

### ISSUE THREAD

**Issue by zhaorx** [microsoft/vscode#97653]
- VSCode Version: 1.45.0
- OS Version:

Steps to Reproduce:

1. Set editor.snippetSuggestions to top
2. Set editor.suggestSelection to first
But when i input 'func' ,the snippet is not the default suggestion.
![image](https://user-images.githubusercontent.com/13824730/81758082-6921ad80-94f3-11ea-83d5-9bf863795160.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
Use this setting to control what is selected `editor.suggestSelection`
