### ISSUE TITLE
DETACHABLE TERMINAL

### ISSUE THREAD

**Issue by jackson9820** [microsoft/vscode#97669]
Issue Type: <b>Feature Request</b>

while working with internal files one can easily open files in code with inbuilt terminal but while working with remote connection code command will not be working and always having my terminal open is anoying to work like i can see only half screen insted a detachable terminal screen would be a good option where one can just concentrate on the code while working on linux servers using ssh

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:10:24.511Z)
OS version: Linux x64 5.3.0-51-generic
Remote OS version: Linux x64 4.9.0-8-amd64

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/10121 https://github.com/microsoft/vscode/issues/34442
