### ISSUE TITLE
Intellisense not working again

### ISSUE THREAD

**Issue by KushagraPan** [microsoft/vscode#97666]
Issue Type: <b>Performance Issue</b>

Javascript intellisense not working again, Have tried restarting, reinstalling the extensions etc

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics     (8 x 3893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.93GB (5.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    84	 18948	code main
    0	    73	  5448	   shared-process
    0	   186	 14868	   gpu-process
    0	    14	 19752	   electron-crash-reporter
    1	    67	 21952	   window (Issue Reporter)
    0	   220	 25324	   window (● client.js - Vanilla - Visual Studio Code [Administrator])
    0	    34	  7988	     searchService
    0	     6	 15168	     console-window-host (Windows internal process)
    0	     5	 19712	     "C:\Program Files\Git\bin\bash.exe"
    0	    10	 13228	       "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0	    13	 24612	     watcherService 
    0	    11	 16864	       console-window-host (Windows internal process)
    0	    80	 24884	     extensionHost
    0	    52	  9488	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=24884
    0	    38	 12364	       electron_node eslintServer.js 
    0	    31	 26452	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=24884
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● client.js - Vanilla - Visual Studio Code [Administrator])
|    Folder (Vanilla): 4 files
|      File types: html(1) js(1) css(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
prettier-vscode|esb|3.20.0
svg|joc|1.1.8
vscode-language-babel|mgm|0.0.27
remote-wsl|ms-|0.40.3
sublime-keybindings|ms-|4.0.7
LiveServer|rit|5.6.1
mdx|sil|0.1.0
vscodeintellicode|Vis|1.2.7
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
