### ISSUE TITLE
I can't run my app when open vscode befor run my app but when I run npm before open vscode I can run my app

### ISSUE THREAD

**Issue by Mo-Alaa88** [microsoft/vscode#97660]
- VSCode Version:1.45.0
- OS Version:Ubuntu x64  18.04.4 LTS

Steps to Reproduce:

1. run VSCode by code . 
or by open with  other application on my code folder 
2. run npm like `start npm ` or `npm run dev`

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by alexdima** [comment]
@Mo-Alaa88 I'm not sure I understand? Do you run `npm run dev` in VSCode's integrated terminal and it fails, while when you run `npm run dev` in another OS terminal it works?

**Comment by Mo-Alaa88** [comment]
@alexdima  I always run  `npm run dev` in my OS terminal but when I run `npm run dev` after open my code folder by VSCode it fials
I run `npm run dev` without terminal VSCode

**Comment by Tyriar** [comment]
Can you create a gif showing your problem?
