### ISSUE TITLE
support limit markdown.styles active in single theme

### ISSUE THREAD

**Issue by Binaryify** [microsoft/vscode#97663]
`markdown.styles` only support css link array now, it don't support limit active in one theme, and it will cause active in global scope, if it can support object like 
```js
"editor.tokenColorCustomizations": {
        "[One Dark Pro]": {
            "textMateRules": []
        },
       
    }
```
that will better

![image](https://user-images.githubusercontent.com/12221718/81767899-202a2300-950c-11ea-8a6e-5874ea3c5278.png)

**Comment by mjbvz** [comment]
My proposal is to add a data attribute inside webviews with the theme name. This would let you write css such as:

```css
body[data-vscode-theme="One Dark Pro"] {
    background: red;
}
```

**Comment by Binaryify** [comment]
@mjbvz that's good enough :)
