### ISSUE TITLE
[Ctrl+Alt+UpArrow/DownArrow] doesn't work on RDP

### ISSUE THREAD

**Issue by hiroshi24da** [microsoft/vscode#97671]
Issue Type: <b>Bug</b>

1. VScode is installed on remote PC.
2. Using the PC on RDP.
3. [Ctrl+Alt+UpArrow/DownArrow] doesn't work. (insert cursors up and down)
    Nothing happens.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU G3900T @ 2.60GHz (2 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.35.1
vscode-docker|ms-|1.2.0
vscode-language-pack-ja|MS-|1.45.1
python|ms-|2020.5.78807
remote-containers|ms-|0.117.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
team|ms-|1.161.0
printcode|nob|3.0.0
markdown-all-in-one|yzh|2.8.0

</details>

**Comment by alexdima** [comment]
@hiroshi24da 
It is possible that VS Code does not receive the keybindings from the OS. What is detect when you press the desired key combination? 

![keyboard-input](https://user-images.githubusercontent.com/5047891/80482640-da3e5e00-8954-11ea-9583-0f652b0595a8.gif)

**Comment by hiroshi24da** [comment]
Hi.
On my case, ”Ctrl+Alt+UpArrow" is defined in Keyboard Shortcuts, and
nothing is defined in Keybindings.json.
It's effective on local operation on the PC, but not effective via RDP.


2020年5月13日(水) 16:50 Alexandru Dima <notifications@github.com>:

**Comment by alexdima** [comment]
@hiroshi24da Can you please follow the steps that I do in the GIF and check if the keybinding reaches VS Code?

**Comment by hiroshi24da** [comment]
OK.
”Ctrl+Alt+UpArrow” shows "Ctrl+Alt+".
”UpArrow” shows " Up".

2020年5月14日(木) 1:02 Alexandru Dima <notifications@github.com>:

**Comment by alexdima** [comment]
@hiroshi24da Thank you. This indicates that VS Code does not receive the keybinding "ctrl+alt+up" from the OS. IMHO I believe this is a problem with the RDP client, which probably "eats up" those keybindings to do something with them and does not send them to the remote machine.

Unfortunately there is no possible thing we can do on our side, since VS Code does not receive the keybindings.

**Comment by hiroshi24da** [comment]
Thanks for your help.
