### ISSUE TITLE
replace bug

### ISSUE THREAD

**Issue by Morteza-Jenabzadeh** [microsoft/vscode#97670]
Issue Type: <b>Bug</b>

Hello
I'm trying to replace all '1px' to '0.1rem'  when match whole word is enable.
But among VS code finds there is '2.1px' which is defenetly out of our case !

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (10.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
es7-react-js-snippets|dsz|2.7.1
svn-scm|joh|2.11.1
code-spell-checker|str|1.8.0

</details>

**Comment by alexdima** [comment]
@Morteza-Jenabzadeh The find widget honors the setting `editor.wordSeparators`. By default, `.` is a word separator, so `2` and `1px` appear as two distinct words separated by `.`.

You can customize this, perhaps only for css in your `settings.json`:
```
"[css]": {
  "editor.wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",<>/?", // . removed
}
```

**Comment by Morteza-Jenabzadeh** [comment]
Thanks for your help
