### ISSUE TITLE
Drag things over Stickty Notes app will freeze the program

### ISSUE THREAD

**Issue by MichaelSuen-thePointer** [microsoft/vscode#97673]
- VSCode Version: 1.45.o (user setup)
- OS Version: Win 10 1909 (10.0.18363.720)

Steps to Reproduce:

1. Open Win10 Sticky Notes App
![image](https://user-images.githubusercontent.com/12868093/81774341-e6ade380-951c-11ea-98ab-947b7ad4e675.png)
![image](https://user-images.githubusercontent.com/12868093/81774362-f3323c00-951c-11ea-8158-bf6e54603617.png)

2. Open VSCode
3. Drag anything draggble (tabs, file list entry, etc.) out of window, over Stcky Notes App window.
![image](https://user-images.githubusercontent.com/12868093/81774571-794e8280-951d-11ea-9bd5-0691ed5cf3a1.png)
![image](https://user-images.githubusercontent.com/12868093/81774589-83708100-951d-11ea-85d5-7d3ef5ba1dfb.png)
![image](https://user-images.githubusercontent.com/12868093/81774618-97b47e00-951d-11ea-9c74-25b8077d13fc.png)

4. The whole program hanged

P.S. Don't know if it is a bug of Sticy Notes App or VSCode

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
> The whole program hanged

Does it eventually show a crash dialog and goes down or just keeps hanging?

**Comment by MichaelSuen-thePointer** [comment]
> Does it eventually show a crash dialog and goes down or just keeps hanging?

Yes it keeps hanging, and interacting with it won't make the window fade white, no 'stop working' dialog

**Comment by bpasero** [comment]
This sounds like an Electron/Chrome issue to me.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 8.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/41f7c1439b6388c146486bd0c48403a967650448/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/41f7c1439b6388c146486bd0c48403a967650448/code-exploration_1.45.0-1588316142_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/41f7c1439b6388c146486bd0c48403a967650448/code-exploration-1.45.0-1588316312.el7.x86_64.rpm)
* Linux (ZIP): [Download](https://az764295.vo.msecnd.net/exploration/41f7c1439b6388c146486bd0c48403a967650448/code-exploration-1588316492.tar.gz)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/41f7c1439b6388c146486bd0c48403a967650448/VSCodeUserSetup-x64-1.45.0-exploration.exe)

**Comment by MichaelSuen-thePointer** [comment]
@bpasero 
Also hanged, "analyze wait chain" in task mgr shows it is waiting for DataExchangeHost.exe, killing it will 'unfreeze' VS Code

![image](https://user-images.githubusercontent.com/12868093/81787187-40210d00-9533-11ea-98b0-664c7b415d93.png)

I very much doubt it is a bug in Windows or Sticky Notes App, because another software 7-zip file manager also have similar drag and drop hanging issue.

**Comment by bpasero** [comment]
Ok thanks, I am closing this issue. VSCode will not be able to fix it. A fix would have to go into Windows, Electron (https://github.com/atom/electron) or Chrome.
