### ISSUE TITLE
Add GitHub Actions to Approved Badges

### ISSUE THREAD

**Issue by Umoxfo** [microsoft/vscode#97676]
Please support a status badge of GitHub Actions [https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow](https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow)

**Comment by alexdima** [comment]
@Umoxfo What exactly do you mean? Where to support these badges?

**Comment by Umoxfo** [comment]
I mean that the VS Code Extension publishing tool may be accepted the GitHub Actions badges.

[https://code.visualstudio.com/api/working-with-extensions/publishing-extension#publishing-extensions](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#publishing-extensions)

Currently approved badge list by the publishing tool:
[https://code.visualstudio.com/api/references/extension-manifest#approved-badges](https://code.visualstudio.com/api/references/extension-manifest#approved-badges)

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode-vsce/issues/389
