### ISSUE TITLE
Lint warnings don't show up in diff editor

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9767]
Strange...

![image](https://cloud.githubusercontent.com/assets/22350/17134691/fe7aa728-532b-11e6-8e7f-60f7d2d218a9.png)

**Comment by joaomoreno** [comment]
@Tyriar @egamma  Not sure if regression, leaving it for July for discussion.

**Comment by egamma** [comment]
Cannot reproduce it. @joaomoreno do you remember your steps? When this happens does the problems view show the warning. 

![image](https://cloud.githubusercontent.com/assets/172399/17137085/7aa5ca64-5339-11e6-98eb-2d739432911e.png)

**Comment by joaomoreno** [comment]
Argh... it's on the staged resource, which is read-only... Never mind.
