### ISSUE TITLE
Visual Studio Codespaces Frequently Gets Stuck in "Opening Remote"

### ISSUE THREAD

**Issue by nemosupremo** [microsoft/vscode#97679]
Issue Type: <b>Bug</b>

Visual Studio Codespaces Frequently Gets Stuck in "Opening Remote" (with Azure) - and this prevents any extensions from being loaded.

I'm using the default code space docker config (so no devcontainer json), with the following extentions:

* Go (with gopls)
* Rust-Analyzer

I'm not even sure how to begin debugging this issue as the logs don't present any useful information.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 19.4.0
Remote OS version: Linux x64 5.3.0-1020-azure
Remote OS version: Linux x64 5.3.0-1020-azure
Remote OS version: Linux x64 5.3.0-1020-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: Nimi|
|OS|Linux x64 5.3.0-1020-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz (8 x 2693)|
|Memory (System)|15.61GB (5.33GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: Nimi|
|OS|Linux x64 5.3.0-1020-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz (8 x 2693)|
|Memory (System)|15.61GB (5.33GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: Nimi|
|OS|Linux x64 5.3.0-1020-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz (8 x 2693)|
|Memory (System)|15.61GB (5.33GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
EditorConfig|Edi|0.14.5
vscode-pull-request-github|Git|0.16.0
beautify|Hoo|1.5.0
rust-analyzer|mat|0.2.166
terraform|mau|1.4.0
python|ms-|2020.5.78807
Go|ms-|0.14.1
vsliveshare|ms-|1.0.2106
vsonline|ms-|1.0.2167
vscodeintellicode|Vis|1.2.7
vscode-proto3|zxh|0.4.2
vscode-docker|ms-|1.2.0
vsonline|ms-|1.0.2167

(1 theme extensions excluded)

</details>

**Comment by nemosupremo** [comment]
I think the issue may be caused by the fact I'm trying to use something other than the default workspace. In my single "codespace" I have default workspace you get, but I also create new workspaces to split up my projects. When launching these workspaces from the welcome screen it connects successfully 70% of the time.

**Comment by alexdima** [comment]
Could you please open the issue against https://github.com/MicrosoftDocs/vsonline/issues , I could not transfer it automatically because it is in another GitHub organisation...
