### ISSUE TITLE
Allow to select text while jumping between brackets

### ISSUE THREAD

**Issue by Janjuks** [Microsoft/vscode#9768]
- VSCode Version: 1.3.1
- OS Version: Win 7 x64

For me, the default shortcut for jumping to matching bracket was `ctrl+shift+\`
I changed it to `ctrl+]`  and while holding down shift, I expect it to select the text from bracket to bracket. I believe that this is a reasonable request as this behaviour can be seen in many other text editors.

Thanks! 
Also just want to thank you for doing this, I love this editor!

**Comment by alexandrudima** [comment]
This could be implemented in the [`BracketMatchingController`]( https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/bracketMatching/common/bracketMatching.ts#L58) by:
* adding a new action
* mostly invoking the same methods, but instead extending the selection
* writing tests :)

**Comment by chewong** [comment]
I can have a look at this!

**Comment by dhruvdutt** [comment]
Any updates @chewong

**Comment by afonsobspinto** [comment]
Hey guys. Me and some friends would like to solve this one for a school project. Is that ok?

**Comment by rebornix** [comment]
@afonsobspinto thanks! I'll take a look at the PR ;)

**Comment by itslittlejohn** [comment]
I think it would also make sense to add a variant that only selects the corresponding bracket, and not the text between. Similar to `CTRL`+`D` but would skip intermediate matches and only select the matching bracket/brace/paren. Thoughts on that?

**Comment by ddoria921** [comment]
what's the status on this?

**Comment by Janjuks** [comment]
It's merged! 🎉
I'm hoping January release? Not sure how these releases work. The last update I have is November 2017.

Thanks @afonsobspinto & friends! Praise! 🙌

**Comment by alexandrudima** [comment]
This will ship in the upcoming January release, thanks to PR #39066 from @afonsobspinto

To do what the OP requests, edit `keybindings.json`:
```
	{
		"key": "ctrl+\\",
		"command": "editor.action.jumpToBracket",
		"when": "editorTextFocus"
	},
	{
		"key": "ctrl+shift+\\",
		"command": "editor.action.selectToBracket",
		"when": "editorTextFocus"
	}
```
