### ISSUE TITLE
Text in middle of terminal section blurred since upgrade to 1.45.0

### ISSUE THREAD

**Issue by wivory** [microsoft/vscode#97682]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Use VS Code with terminal window open across bottom (I have 2 editors side by side above).
2. After a short period (under 15 minutes typically), text in the middle of the terminal window goes blurry.  Clicking the maximize button (to reduce from full screen to smaller) and again (back to full screen) fixes the problem for a while, then it returns.  Very very annoying.

This only started on Monday this week after I upgraded to 1.45.0.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:10:24.511Z)
OS version: Linux x64 4.15.0-99-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 3540)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|62.52GB (36.51GB free)|
|Process Argv|-r /home/wivory/VSCodeWorkspaces/fleetwood_go.code-workspace --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
cpputest-test-adapter|bne|0.1.2
yacc|car|1.3.1
gitlens|eam|10.2.1
vscode-test-explorer|hbe|2.18.0
workspacesort|ici|1.5.9
jenkins-pipeline-linter-connector|jan|1.2.0
plantuml|jeb|2.13.9
code-groovy|mar|0.1.2
python|ms-|2020.5.78807
cpptools|ms-|0.28.0
Go|ms-|0.14.1
vscode-groovy-lint|Nic|0.13.0
vscode-print|pdc|0.7.14
rf-intellisense|Tom|2.8.0
vscode-workspace-explorer|tom|1.5.0
yang-vscode|typ|2.0.3

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot of [a gif](https://gifcap.dev/) illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal

**Comment by wivory** [comment]
Hope PNG is ok - have attached 2 screenshots, one of which show fuzzy
text in the terminal window (half way along top of terminal is
worst).  Minimising and restoring doesn't fix it; switching from full
screen to reduced size and back does.

**Comment by Tyriar** [comment]
@wivory attaching via email doesn't work on github, you need to go to github.com for that.

**Comment by wivory** [comment]
OK – will need to wait until I’m back at work on Monday then.

 

Thanks,

 

William

**Comment by wivory** [comment]
Adding 2 screenshots.  Look at the middle of the top line of the terminal section of the screen and you should be able to see that it's somewhat out of focus in one.  Note in addition to my initial comments that minimising / back to full screen doesn't solve the problem - it's only when you resize the window (eg toggle the maximise button) that fixes it.
![all_text_clear](https://user-images.githubusercontent.com/19471731/84626079-6512f200-aedc-11ea-89f1-4eb7fba8beb7.png)
![fuzzy_top_middle_of_terminal](https://user-images.githubusercontent.com/19471731/84626083-65ab8880-aedc-11ea-9c25-4ea90b38d5e7.png)

**Comment by Romyanmar4** [comment]
``<script src="//code.jivosite.com/widget/p3yqJKpweV" async></script>

**Comment by Romyanmar4** [comment]
[<script src="//code.jivosite.com/widget/p3yqJKpweV" async></script>](<script src="//code.jivosite.com/widget/p3yqJKpweV" async></script>b19cEXMX1mxH3​) #98778

**Comment by Tyriar** [comment]
Can you share your settings.json?

**Comment by wivory** [comment]
{
    "python.testing.nosetestsEnabled": true,
    "editor.formatOnSave":
true,
    "editor.acceptSuggestionOnEnter": "off",
    "editor.rulers":
[
        80,
        120
    ],
    "go.buildOnSave": "off",
    "go.vetOnS
ave": "off",
    "go.formatTool": "gofmt",
    "workbench.colorTheme": "D
efault Light+",
    "files.trimTrailingWhitespace": true,
    "editor.ren
derWhitespace": "boundary",
    "[groovy]": {},
    "python.testing.pytes
tEnabled": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "worksp
aceExplorer.workspaceStorageDirectory": "/home/wivory/VSCodeWorkspaces"
,
    "groovyLint.basic.run": "onType",
    "jenkins.pipeline.linter.conn
ector.url": "http://scottykins.edi.vyatta.net/pipeline-model-
converter/validate",
    "jenkins.pipeline.linter.connector.user": "admi
n",
    "jenkins.pipeline.linter.connector.pass": "admin",
    "[c]": {
  
"editor.formatOnSave": false
    },
    "files.exclude": {
       
"**/build": true
    },
    "[robot]": {
        "editor.tabSize":
4
    },
    "window.zoomLevel": -1,
    "C_Cpp.default.defines": []
}

**Comment by Tyriar** [comment]
Workaround is to use the setting `"terminal.integrated.rendererType": "dom"`

**Comment by wivory** [comment]
Thanks - that appears to have fixed the problem.

Regards,

William

**Comment by wivory** [comment]
While still waiting on a fix for the original problem, I've updated from 1.48 to 1.50 (1.49 had a different bug I was avoiding until fixed), and now find that the search box is permanently out of focus.  Does this need a separate bug?  It's really annoying, doesn't clear (even temporarily) if I resize the window, so it's back to 1.48, again.
![Screenshot from 2020-10-13 08-15-11](https://user-images.githubusercontent.com/19471731/95828317-bfa64880-0d2c-11eb-9af8-53e6de74fcdf.png)

**Comment by Tyriar** [comment]
@wivory yes that looks like a different thing, probably related to Electron so you could search the issues for electron/blurry.

Another potential workaround is to make sure `window.zoomLevel` is set to 0 and change the editor/terminal text size manually.

**Comment by wivory** [comment]
Upgraded to 1.56 today. Problem is back as it seems the rendererType option is now greyed out in settings.json and doesn't work. Coming up to a year after I first filed this )-:

**Comment by Tyriar** [comment]
@wivory it changed to: `"terminal.integrated.gpuAcceleration": "off"`

**Comment by Tyriar** [comment]
Let's track this in https://github.com/microsoft/vscode/issues/85154

/duplicate
