### ISSUE TITLE
I can't resize editor's layouts

### ISSUE THREAD

**Issue by aragong** [microsoft/vscode#97680]
Issue Type: <b>Bug</b>

With todays update, the cursor doesn't change to the selection mode when is over a layout boundary so I can't resize my editor layouts.

There is any new way to do that? or it is only a bug?

VS Code version: Code - Insiders 1.46.0-insider (d0a3feff23c47876412f5e289b935aabf02c71ae, 2020-05-13T05:35:51.092Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3411)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.98GB (9.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.5.78807
remote-wsl|ms-|0.44.2
material-icon-theme|PKi|4.1.0

(1 theme extensions excluded)

</details>

**Comment by YBogomolov** [comment]
It seems that this is related to this PR: https://github.com/microsoft/vscode/pull/97266

**Comment by YBogomolov** [comment]
The sashes are still present, but their position and behaviour is incorrect:
![image](https://user-images.githubusercontent.com/908865/81781041-2fa36f00-9500-11ea-9a9a-1ad9ac4c2e5c.png)

I guess it would be better to draw @lszomoru @joaomoreno attention to this ticket.

**Comment by aragong** [comment]
is there any way for me to downgrade this version until the bug will be fixed? I can only find "check for updates" in the preferences... Thank you for your help, @YBogomolov

**Comment by joaomoreno** [comment]
I've unreleased that build and will be releasing a new Insiders today with the fix. Sorry for the disturbance.

**Comment by joaomoreno** [comment]
Build running.

**Comment by joaomoreno** [comment]
Meanwhile, if you check for updates once again, you should be reverted back to a good build, until the fix finishes building.

**Comment by aragong** [comment]
> Meanwhile, if you check for updates once again, you should be reverted back to a good build, until the fix finishes building.

It works perfect! Thank you very much @joaomoreno 🚀

**Comment by joaomoreno** [comment]
Thank you for being on top of things! 🙏

**Comment by lszomoru** [comment]
We have published a new Insiders build that contains the fix for this issue. Apologies for the inconvenience.

**Comment by aragong** [comment]
Thank you for solving it so quick! you are 🚀 's!
