### ISSUE TITLE
Disable formatOnSave on custom files

### ISSUE THREAD

**Issue by FreifeldRoyi** [microsoft/vscode#97685]
Hi,  
Is it possible to add a custom file type for the formatOnSave action? 
For example, a `.env` with a long connection string  with semi-colons is always formatted when I hit save.

Since I have .env files with the environment suffixed (e.g `.env.dev`) I wish I could not only have the .env files added to [this](https://code.visualstudio.com/docs/languages/identifiers) list, but also custom files

Thank you

**Comment by jrieken** [comment]
Yes, format on type can be configured per language, like so (css)

```
"[css]": {
        "editor.formatOnSave": false
 },
```

**Comment by FreifeldRoyi** [comment]
But CSS is a known type and is listed in the manual... How do I set a file with an unknown type?

**Comment by jrieken** [comment]
@sandy081 for the ⬆️

**Comment by sandy081** [comment]
There is no support for extension specific settings - https://github.com/microsoft/vscode/issues/35350
