### ISSUE TITLE
[folding] fold surrounding

### ISSUE THREAD

**Issue by gerich-home** [microsoft/vscode#97684]
This feature request looks related to #78557 but is about **siblings** of the current region, not nested.

When you are editing a large file with deep nesting you can get lost in the structure. It is sometimes extremely hard to estimate where you are, how much elements are around the current piece.
If you scroll up or down to find the parent of the element (especially if neighbours are large enough and look similar to each other) you get lost.

The purpose of the feature request is to allow you to **quickly get focused on the current piece** of structure and fold others, unrelated regions.
So my proposal is to **introduce some command** (for example `<alt> + click`) **to collapse all siblings on all levels** starting from current level up to root.

So, given you are editing a file like this:
```json
{
    "destination_addresses": [
      "Washington, DC, USA",
      "Philadelphia, PA, USA",
      "Santa Barbara, CA, USA",
      "Miami, FL, USA",
      "Austin, TX, USA",
      "Napa County, CA, USA"
    ],
    "origin_addresses": [
      "New York, NY, USA"
    ],
    "rows": [{
      "elements": [{
          "distance": {
            "text": "227 mi",
            "value": 365468
          },
          "duration": {
            "text": "3 hours 54 mins",
            "value": 14064
          },
          "status": "OK"
        },
        {
          "distance": {
            "text": "94.6 mi",
            "value": 152193
          },
          "duration": {
            "text": "1 hour 44 mins",
            "value": 6227
          },
          "status": "OK"
        },
        {
          "distance": {
            "text": "2,878 mi",
            "value": 4632197
          },
          "duration": {
            "text": "1 day 18 hours",
            "value": 151772
          },
          "status": "OK"
        },
        {
          "distance": {
            "text": "1,286 mi",
            "value": 2069031
          },
          "duration": {
            "text": "18 hours 43 mins",
            "value": 67405
          },
          "status": "OK"
        },
        {
          "distance": {
            "text": "1,742 mi",
            "value": 2802972
          },
          "duration": {
            "text": "1 day 2 hours",
            "value": 93070
          },
          "status": "OK"
        },
        {
          "distance": {
            "text": "2,871 mi",
            "value": 4620514
          },
          "duration": {
            "text": "1 day 18 hours",
            "value": 152913
          },
          "status": "OK"
        }
      ]
    }],
    "status": "OK"
  }
```
the behavior will be as shown below.

When you open a file:
![image](https://user-images.githubusercontent.com/296593/81785345-e276cb80-9506-11ea-822b-8c130e66b8f3.png)
after you `<alt>+click` on the folding indicator on line 36 it should look like that:
![image](https://user-images.githubusercontent.com/296593/81785726-4b5e4380-9507-11ea-95b2-40376f338608.png)

**Comment by aeschli** [comment]
Nice suggestion, also useful as command.

PRs accepted or could also be implemented as an extension

**Comment by isidorn** [comment]
I verify that this works as described, however I personally find it quite confusing.
I had to read it a couple of times for me to figure out what is exactly going on. Also the toggle behaviour of this `alt` mode is weird.

Adding verified label, however wanted to share my feedback even though I am not a heavy user of folding

**Comment by isidorn** [comment]
Another problem I see is discoverability...

**Comment by isidorn** [comment]
Due to the above I suggest to just have a command. The alt click behaviour I find very cryptic.

**Comment by aeschli** [comment]
@isidorn The PR also added two new commands: `Unfold All Regions Except Selected` and `Fold All Regions Except Selected.
Yes, you need to know about them. Agree that this is hard to discover, but then also kind of an 'expert' feature.

What we need is a hover when the mouse is over the folding indicator.

**Comment by isidorn** [comment]
Yes, the hover over the folding indicator would help
