### ISSUE TITLE
find shows count '? of 2' after removing any found result

### ISSUE THREAD

**Issue by nithil** [microsoft/vscode#97681]
- VSCode Version: 1.45.0
- OS Version: macOS 10.13.6 (Darwin x64 17.7.0)

Steps to Reproduce:

1. in a new file add code as shown in image
![Screen Shot 2020-05-13 at 12 19 48](https://user-images.githubusercontent.com/31035540/81780494-3e941c80-9514-11ea-87ff-7e96a149647b.png)

2. then start changing the found result, the count changes to '?'. shouldn't it be now 2 of 2

Does this issue occur when all extensions are disabled?: Yes

If this is a expected behavior, then let me know.

**Comment by svipas** [comment]
Same for me, this happened after 1.45.0 release.

**Comment by alexdima** [comment]
I can see a difference of behaviour, but I'm not 100% sure it is a bug, or perhaps the find widget is now simply more honest.

Before, whenever doing an edit with the find widget open, it would render `1 of X`, regardless of the position in the file. Now, it renders `? of X`.

@rebornix This was introduced via
https://github.com/microsoft/vscode/commit/e57b91ce779416524cc1a911fd637eba534e0ae2#diff-a58154d49e17ccebe339b37046661368
