### ISSUE TITLE
onDidOpenNotebookDocument fires notebook has no cells

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#97694]
* the GH issues notebooks has this https://github.com/microsoft/vscode-github-issue-notebooks/blob/de9a43406d854c87e0b150b5b58e276f7d2a9bd2/src/notebookProvider.ts#L49
* :bug: when the event fires notebooks have no cells (`[]`) which means the project isn't setup correctly

The real world impact be seen like this

* have a cell that defines a variable
* have a cell that uses the variable
* collapse the former
* reload -> compile errors...
* expand -> all good

![May-13-2020 11-28-01](https://user-images.githubusercontent.com/1794099/81795821-da218f00-950c-11ea-9328-916ec0c1eded.gif)

**Comment by rebornix** [comment]
Good catch, it was broken after introducing the backup. Will add tests once we have smoke test infra there.
