### ISSUE TITLE
Make repl themable

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#97695]
I stumbled over [repl.css](https://github.com/microsoft/vscode/blob/b814ec355adb68ea6aa589e0c557d472c5ce4d05/src/vs/workbench/contrib/debug/browser/media/repl.css#L103) and saw that there are still many colors hard-coded.

Also while at the .css file, it's good practice to qualify all rules with `.monaco-workbench` (or `.monaco-editor`) now that the workbench can be embedded in the web.

**Comment by isidorn** [comment]
Thanks @aeschli for great feedback.
There was some unused CSS, like the .annotation in the repl, so I removed that. I have also now qualifed all with `.monaco-workbench`.

There is still one hard coded color for warning in repl, but I believe @robertrossmann tackled this with his great PR. Though I might be mistaken?

**Comment by robertrossmann** [comment]
@isidorn I did, indeed, add colour contribution points to the REPL as part of #94838 but eventually you asked me to defer those until later, I do not remember the reason precisely... 🤔 So the REPL is still not theme-able, unfortunately.

**Comment by isidorn** [comment]
@robertrossmann thanks for refreshing my memory.
In case you would like to contribute that part of your PR we are open to accept it now :D
From the `.css` I only see a need for `warn` color, not sure if there is more.

**Comment by robertrossmann** [comment]
@isidorn I am working on this now. ✅ 

I am taking it a step further, though, and adding theming to most of the REPL elements (errors, warnings, infos, source filenames etc.). Basically I want the whole REPL view to be fully customisable. 💪 🚀

**Comment by isidorn** [comment]
To verify, make sure you can customise the following colors in the debug console. You can use the setting `workbench.colorCusomisations`:

`debugConsole.infoForeground`
`debugConsole.warningForeground`
`debugConsole.errorForeground`
`debugConsole.sourceForeground`
`debugConsoleInputIcon.foreground`
