### ISSUE TITLE
Make noteboook themable

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#97696]
I stumbled over [notebook.css](https://github.com/microsoft/vscode/blob/b814ec355adb68ea6aa589e0c557d472c5ce4d05/src/vs/workbench/contrib/notebook/browser/media/notebook.css) and saw that it contains hardcoded colors.
I know this is ongoing work, just a reminder to make the notebook themeable.

Also while at the .css file, it's good practice to qualify all rules with .monaco-workbench (or .monaco-editor) now that the workbench can be embedded in the web.

**Comment by rebornix** [comment]
Thanks, it makes good sense.

**Comment by misolori** [comment]
I've moved all of the hardcoded colors into the following theme colors:

- `notebookStatusErrorIcon.foreground`
- `notebookStatusSuccessIcon.foreground`
- `notebookStatusRunningIcon.foreground`
- `notebook.cellStatusBarItemHoverBackground`

Also prepended all css rules with `.monaco-workbench`

**Comment by JacksonKearl** [comment]
I'd expect the timer and `GitHub Issues`  to be red here?

![image](https://user-images.githubusercontent.com/8586769/83704015-d510a680-a5c5-11ea-90ee-93b719da3520.png)


Edit: nevermind, see that its the hover.

**Comment by misolori** [comment]
@JacksonKearl yea it's just the bg hover on this one
