### ISSUE TITLE
Start Without Debugging still launches program in debug mode

### ISSUE THREAD

**Issue by pszrux** [microsoft/vscode#97699]
- VSCode Version: 1.45.0 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

  1. I run a python file through `run without debugging`. 

  2. however, vscode launch program in debug mode. the same issue:  #[1957](https://github.com/Microsoft/vscode-go/issues/1957), but the solution doesn't work.

My launch configuration:
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Python: Current File",
      "type": "python",
      "request": "launch",
      "program": "${file}",
      "console": "integratedTerminal"
    }
  ]
}
```

Does this issue occur when all extensions are disabled?: Yes

how do I fixed it?

**Comment by weinand** [comment]
"Start Without Debugging" for a python program works fine for me.

Please note that "Start Without Debugging" still starts a debug session but breakpoints will be not hit.
