### ISSUE TITLE
Cannot turn off selected text color change in High Contrast Theme

### ISSUE THREAD

**Issue by yoshioka-naoki** [microsoft/vscode#97706]
Text color changes to black when selected in editor.
It happens only in High Contrast Theme.

Though I can change the color in settings.json `editor.selectionForeground`, what I want is reserve the original color.
How can I do that?
![image](https://user-images.githubusercontent.com/55611674/81807107-6e651380-9558-11ea-816e-f5039b621aaf.png)

**Comment by alexdima** [comment]
@aeschli is it possible to define a color as `null`?

This color is defined in the following way:
```
editorSelectionForeground = registerColor('editor.selectionForeground', { light: null, dark: null, hc: '#000000' }
```

I think the desire here would be to get the value of `editor.selectionForeground` to be `null` from the user settings.

**Comment by aeschli** [comment]
No, `null` is not allowed in the settings, but you can make it transparent.

**Comment by yoshioka-naoki** [comment]
Thanks.  how to set it transparent?

**Comment by aeschli** [comment]
e.g. `#00000000`. The last two digits (alpha value) just need to be `00`.

Note: I pushed a fix for this to work. It will be in tomorrows insiders and in stable 1.46.

**Comment by aeschli** [comment]
To verify:
- select high contrast theme
```
	"editor.tokenColorCustomizations": {
		"editor.selectionForeground": "#0000"
	}
```
- select text and verify that the foreground color is the regular test color with highlighting
