### ISSUE TITLE
can't resize window panels with mouse drag

### ISSUE THREAD

**Issue by elias551** [microsoft/vscode#97709]
resize cursor don't appear and console can't be resized. Shortcut to toggle visibility still works as a workaround for now

Version: 1.46.0-insider
Commit: d0a3feff23c47876412f5e289b935aabf02c71ae
Date: 2020-05-13T05:34:04.109Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-51-generic

**Comment by ngollan** [comment]
While waiting for a fix, what's the shortcut?

**Comment by joaomoreno** [comment]
This is already fixed in the latest insiders.

**Comment by elias551** [comment]
Thanks for the quick reply and fix :)

@ngollan default is CTRL + ` (backtick)
