### ISSUE TITLE
Incorrect syntax highlighting of PHP strings containing an SQL query

### ISSUE THREAD

**Issue by MmAaXx500** [microsoft/vscode#97703]
- VSCode Version: 1.45.0 and 1.46.0-insider (e88b8d32aa7233f6cb3665f6dae9fa78b1e8aafb)
- OS Version: Win 10 1909

Syntax highlighting around an array appended to an SQL query string is incorrect.
Note the dots and square brackets.

Steps to Reproduce:

1. Paste this to a PHP file:
```
<?php
$wrong    = "SELECT * FROM '" . $var["foo"] . "'";
$expected = "select * from '" . $var["foo"] . "'";
?>
```

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/36025825/81802535-8caa1f80-9516-11ea-8d1e-3a0d83038693.png)

**Comment by alexr00** [comment]
Moved to owning repo: https://github.com/atom/language-php/issues/392
