### ISSUE TITLE
Enrich yarn web to include GH support

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#97708]
Today you can run the web version of VSCode "serverless" via `yarn web`. In this model we add a single extension into the `staticExtensions` property to run it inside the web worker and that one registers a file system provider:

https://github.com/microsoft/vscode/blob/77b5058284a50445674ee3b237ad64793b38965e/extensions/vscode-web-playground/src/extension.ts#L36

This is an in-memory provider and the idea would be to use a GH provider, maybe depending on a query parameter in the URL. This would only provide a readonly view on a repository, but that is fine to begin with. We could expand the capabilities depending on available API, e.g. allowing to search.

My understanding is that Eric you already wrote a file system provider once for GH that we could maybe use here.

**Comment by eamodio** [comment]
This is now supported using a `?gh=<user>/<repo>` query string

**Comment by bpasero** [comment]
@eamodio having trouble trying this out, is there something I need to do other than running `yarn web` with that URL?

After the auth callback, I see this in VSCode:

![image](https://user-images.githubusercontent.com/900690/84233074-e724a480-aaf1-11ea-9279-5fc3a23d1bc4.png)

And the callback seems to be returning to a "Not Found" page?

**Comment by eamodio** [comment]
Sorry I forgot to mention, that we can't currently support the full auth flow in `yarn web` (because GitHub won't allow a local host return URI). But you can provide a personal access token instead by clicking on the status bar entry when the auth flow starts. That will then be saved in local storage.

**Comment by bpasero** [comment]
Ok thanks, will try that.

I pushed https://github.com/microsoft/vscode/commit/6a927e6bb5125a66f6cc9750261081a16f60a3c6 to fix a bad path for `callback.html` that was still pointing to the old location.

**Comment by eamodio** [comment]
Awesome, thanks!
