### ISSUE TITLE
Incorrect presentation group in launch configurations with name collisions

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#97712]
- VSCode Version: 1.45.0
- OS Version: Windows 10

Steps to Reproduce:
`launch.json`:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "presentation": {
                "group": "Group 1"
            },
            "name": "Name 1"
        },

        {
            "presentation": {
                "group": "Group 2"
            },
            "name": "Name 1"
        },
        {
            "presentation": {
                "group": "Group 2"
            },
            "name": "Name 2"
        }
    ]
}
```

Note that both tasks with `Name 1` are shown in the same group, despite the latter clearly being configured to be in `Group 2` with `Name 2`:
![image](https://user-images.githubusercontent.com/12128514/81818047-cd616300-952d-11ea-929b-b3e10a7da37b.png)
(`cia` being the name of the folder in the workspace)

**Comment by isidorn** [comment]
Yeah the names should be unique.
We will most probably not fix this bug. Though assigning it to backlog.
