### ISSUE TITLE
Proxy modal window not working and application is stuck

### ISSUE THREAD

**Issue by samuelsunil** [microsoft/vscode#97719]
- VSCode Version: 1.0.45 latest
- OS Version: Mac OS Catalina

Steps to Reproduce:

1. Behind a proxy wall, open the application
2. VS Code automatically prompt the Proxy credentials entry modal
3. After entering the credentials, clicking on "OK" or 
"Cancel" does not do anything

Does this issue occur when all extensions are disabled?: Yes/No: NA, Does not allow me to disable extensions. Proxy window opens immediately

One thing I noticed, in the 1.44 version, the proxy address would appear on top of the modal for reference. I don't see that in the new version. 

<img width="469" alt="Screen Shot 2020-05-13 at 8 24 22 PM" src="https://user-images.githubusercontent.com/7824573/81829198-45dd1980-9558-11ea-96de-d57f8366aaf8.png">

**Comment by notqualifiedforthis** [comment]
Same thing here on my work laptop (Win 10 Enterprise 1809) behind proxy.  Same steps to reproduce and only way to close is title bar X.

**Comment by thekineticeffect** [comment]
Have been seen this issue as well, on fresh installations of the April release on Windows 10 and MacOS Mojave. Only using the window manager’s X button can close the dialog.

**Comment by Serpen** [comment]
Same here on Win10 1909 on VS Code 1.45.0. There are 2 modal proxy windows, have to close it twice via X.

By the way it would be nice to have the realm name from the 407 message stated in the dialog like IE, Edge, Firefox are doing. Currently nobody really know what this dialog is really about.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/97199
