### ISSUE TITLE
Debug console panel title is wrongly added when it's inside another view container

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#97711]
Repro:

1. Track debug console into terminal
2. Reload the window

![image](https://user-images.githubusercontent.com/2193314/81817953-40dd8300-94e2-11ea-97a9-70dfcd43b401.png)

**Comment by sbatten** [comment]
almost definitely a result of https://github.com/microsoft/vscode/commit/f397e4559aafaaf27f0828569abd2615e27063fd

**Comment by sbatten** [comment]
reverted that change. will try to fix the other issue a different way.
