### ISSUE TITLE
Explorer: weird hover effect when hovering into view

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#97716]
Steps to Reproduce:

1. I run out of master with fresh user data dir on macOS
2. zoom in once (important it seems)
3. open a folder
4. move mouse into explorer

=> 🐛 notice how the elements move up and down

![recording](https://user-images.githubusercontent.com/900690/81825304-c68b1e00-9536-11ea-9335-0b6772d22d14.gif)

Not sure if related to the translate3d issue.

**Comment by isidorn** [comment]
I can repro when I zoom in once.
I can repro both with Open Editors and with Explorer.
The best I can do is do a Git bisect. @joamoreno let me know if you would like me to go on this path.

**Comment by bpasero** [comment]
I have a feeling this started only recently.

**Comment by joaomoreno** [comment]
There were no changes here recently. And I don't a macOS to repro. So yeah, try to bisect.

My two cents tho: Electron update, which will be a pain to bisect through. 😢

**Comment by isidorn** [comment]
Ok bisecting.
Also we did not do an electron update in the last 2 months so I think it is something else.

**Comment by isidorn** [comment]
This is the commit to blame
https://github.com/microsoft/vscode/commit/e074920d89c9ff425d5e582aeb85fda309bcf7cf
@sbatten can you look into this please?

![Screenshot 2020-05-13 at 18 23 40](https://user-images.githubusercontent.com/1926584/81838768-e296bb80-9546-11ea-9161-1b6a161dbb9a.png)
