### ISSUE TITLE
In Markdown preview, bullet lists of 2nd level render without indent

### ISSUE THREAD

**Issue by pavel-a** [microsoft/vscode#97718]
Issue Type: <b>Bug</b>

Example of two-level bulleted list

## Two level list:

```md
*  GUI - the GUI application
  * GUI_QA - PC side utility to test the GUI (simulates board)
  * BOARD_QA - connects to the board over tcp (simulates host)
*  scripts/foo.py - utility for building foo
```

In preview, all items above are displayed at one level, items 2,3 without indentation. 

For indentation, two spaces must be enough per the specification: https://guides.github.com/features/mastering-markdown/#syntax
But it seems that 3 spaces are needed. 

*  GUI - the GUI application
   * GUI_QA - PC side utility to test the GUI (simulates board)
   * BOARD_QA - connects to the board over tcp (simulates host)
*  scripts/foo.py - utility for building foo

Please either fix implementation or the spec.
Other editors (I use Typora ) render 2 spaces indent correctly.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.83GB free)|
|Process Argv|C:\DATA\PART2\Proj\Terra\REPO_MASTERMASTER\docum\notes.md|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
python|ms-|2019.10.41019
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-wsl|ms-|0.40.3
vscode-remote-extensionpack|ms-|0.17.0
cpptools|ms-|0.26.2

</details>

**Comment by mjbvz** [comment]
Our built-in markdown preview targets commonmark. The rendering matches the common mark spec: https://spec.commonmark.org/dingus/?text=*%20%20GUI%20-%20the%20GUI%20application%0A%20%20*%20GUI_QA%20-%20PC%20side%20utility%20to%20test%20the%20GUI%20(simulates%20board)%0A%20%20*%20BOARD_QA%20-%20connects%20to%20the%20board%20over%20tcp%20(simulates%20host)%0A*%20%20scripts%2Ffoo.py%20-%20utility%20for%20building%20foo

Just get rid of the extra space in `* GUI ` if you want this to render as nested lists
