### ISSUE TITLE
Can't expand array in watch expressions & repl

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9771]
Testing #9684

```es6
const arr = new Array(10000);
console.log(arr);
```

1. Set breakpoint on line `2`.
2. Add `arr` watch expression.
3. Start debug

Can't expand the `arr` watch expression when paused in the breakpoint. Also can't expand the same expression in the repl.

![image](https://cloud.githubusercontent.com/assets/22350/17137521/da3106d6-533b-11e6-8e36-b1786e6b042d.png)

![image](https://cloud.githubusercontent.com/assets/22350/17137535/f3c313e6-533b-11e6-98e3-8f24542f7f9d.png)

**Comment by isidorn** [comment]
The issue here seems to be that the node debug adapter is not sending `indexedVariables` for evaluate calls. Forwarding to @weinand
