### ISSUE TITLE
update messed up sometimes

### ISSUE THREAD

**Issue by danardf** [microsoft/vscode#97722]
Version: 1.45.0 (user setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Click on the gear on left bottom 
2. An update is present,  click on update.
3. the window is closing.
4. It start to update and there's some error with the privilege. 

Does this issue occur when all extensions are disabled?: I don't know.
this issue occur when some files are editing. 

Sometimes the update works perfectly.

**Comment by danardf** [comment]
It seems the update is trying to change root folder to update.
sometimes it's here:
C:\Users\me\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Visual Studio Code
Sometimes it's here:
C:\Program Files\Microsoft VS Code\Code.exe

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
