### ISSUE TITLE
/Applications/VSCode.app/Contents/Resources/app/bin/code: line 10: ./MacOS/Electron: No such file or directory

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#97728]
- VSCode Version: 1.45.0
- OS Version: macOS Catalina

Steps to Reproduce:

1. Write a direnv `.envrc` that exits with a non-zero code.
2. Try to launch VSCode on that project directory.

**Comment by deepak1556** [comment]
Can you provide minimal repro with detailed steps, I am not familiar with direnv. Thanks!
