### ISSUE TITLE
Force textEditor options for language types

### ISSUE THREAD

**Issue by XVincentX** [Microsoft/vscode#9772]
Hello - I have another question here.

Due to parser limitation, some documents I'm analyzing should have a default tab size and tab for indent.

I've looked into the API, but I do not find anyway to specify those options as default when working with documents in editor when `languageId === myThing`

I was thinking about hooking on `window.onChangeActiveTextEditor` but at first that would change the options every time and also it seems like `textEditor.options` are read only (or changes are not propagated)

Where should I look into? Is it possible to specify default options in contributions point probably?

Thanks a lot again,
V.

**Comment by jrieken** [comment]
You are on the right path. Listening to `onDidChangeActiveTextEditor` and updating the options is OK (the editorconfig-extension does the same btw). Note that the `options` isn't  a live object but you must assign new options ala `textEditor.options = { tabSize: 12 }`

**Comment by XVincentX** [comment]
Thanks a lot for the answer. Probably this part is a bit under documented!

**Comment by XVincentX** [comment]
@jrieken It looks like it's not possible to set new line type; am I missing something? Where is that option set?

**Comment by jrieken** [comment]
True - I need to check with @alexandrudima why that is but for now you use the [setEndOfLine](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1008)-method from the TextEditorEdit. Like so

```
textEditor.edit(editBuilder => {
  editBuilder.setEndOfLine(EndOfLine.CRLF)
})
```

**Comment by XVincentX** [comment]
Thanks!
