### ISSUE TITLE
Allow camera permission in vscode

### ISSUE THREAD

**Issue by jobinv12** [microsoft/vscode#97726]
unable to videocapture in opencv

**Comment by alexdima** [comment]
@jobinv12 I'm not sure, what exactly do you mean?

**Comment by jobinv12** [comment]
> @jobinv12 I'm not sure, what exactly do you mean?

So when in use videocapture(0) it does not return video from the webcam.instead it aborts.

**Comment by alexdima** [comment]
@jobinv12 In my stock installation of VS Code, `opencv` does not execute. So can you please provide clear steps?
