### ISSUE TITLE
Focus is pulled away from commit message box when a file change is staged or unstaged

### ISSUE THREAD

**Issue by callumdmay** [microsoft/vscode#97727]
Issue Type: <b>Bug</b>

1. Modify a file in a git controlled repo (preferably a large one, to give yourself more time to type out a commit message before the file is moved into staged)
2. Go into the source control view, and move the file from CHANGES to STAGED CHANGES
3. Before the file appears in STAGED CHANGES (the staging operation is in progress) start typing out a commit message.
4. As soon as the file is moved into staged changes, the focus on the commit message box is lost and you start typing into what I believe is the filter for this view?

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

**Comment by callumdmay** [comment]
Here I hit stage on that file, clicked he commit message box, started typing asasasa.... and then once the file moved into the STAGED CHANGES section the focus was pulled away from the commit message box and continued typing where that red text is

![image](https://user-images.githubusercontent.com/10503759/81837730-126ba200-94fa-11ea-9a4d-94ff7926266e.png)

**Comment by joaomoreno** [comment]
This is already fixed in Insiders, can you check?
