### ISSUE TITLE
Initializing JS/TS language features uses 100% of CPU + never stops

### ISSUE THREAD

**Issue by antony** [microsoft/vscode#97734]
This issue has been closed here https://github.com/microsoft/vscode/issues/68896 and it was suggested to open a new issue https://github.com/microsoft/vscode/issues/71620 which was immediately closed as a duplicate. I'm opening this issue because this problem still exists (and has done for me since around last June if not before).

The "Initialising JS/TS langugage features" status pops up when I open a JS file, runs my CPU up to 100% and almost freezes my machine. It makes using VSCode painful, if not sometimes impossible if I need two copies open at once.

* None of the tips, scenarios, or workarounds in the previous issues have any bearing on the problem.
* `--disable-extensions` has no effect.
* I now have a brand new XPS laptop, with a fresh install of the OS, and it's occurring again, immediately.
* The verbose tsserver logs don't show anything unusual or interesting.
* insiders builds don't solve the issue (I've tried a few, periodically)
* I have no jsconfig
* I'm not using a network drive
* The project is a Svelte project but it occurs only when I open a JS file
* I (think) intellisense is working

I'm therefore marking it as severe.

Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:50:03.709Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.5.19-050519-generic

Steps to Reproduce:

1. Open a project
2. Open any JS file

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by antony** [comment]
Thanks for the info - right now with insiders I'm seeing the same issue, but without the excess cpu usage.

I'll report back as soon as I'm able to trigger the high CPU usage.

**Comment by antony** [comment]
I'm having trouble reproducing the high CPU with insiders, so I'll close this and re-open if I run into further issues. Very excited!
