### ISSUE TITLE
VS Code Politely Crashes on Loss of Network Connected Files

### ISSUE THREAD

**Issue by mkormendy** [microsoft/vscode#97738]
Issue Type: <b>Bug</b>

When files on mounted shares have lost their connection, VS Code politely says it had an issue and needs to reboot.

It would be nicer if VS Code stored the content in a temporary file on the local file system when it decides it wants to crash, with a path of where it was originally found so that when the network comes back it would simply reference that file on the mounted share again to write over when saved again, or if the network is unavailable, the contents of that file could be saved elsewhere.

The mounts I have are on a VPN network and from time to time, I lose connection to the VPN network (out of my control) and then VS Code wants to restart all over again and I lose my changes.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.3.11
vscode-devtools-for-chrome|cod|0.0.7
bracket-pair-colorizer|Coe|1.0.61
jshint|dba|0.10.21
vscode-eslint|dba|2.1.5
vscode-dash|dee|2.4.0
devsync-vsc|Dev|1.0.6
githistory|don|0.6.5
permute-lines|ear|1.1.0
prettier-vscode|esb|4.7.0
vscode-browser-refresh|fab|1.1.5
php-debug|fel|1.13.0
auto-rename-tag|for|0.1.2
vscode-mysql|for|0.4.0
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.5.0
cpptools|ms-|0.28.0
debugger-for-chrome|msj|4.12.6
live-server-preview|neg|0.1.4
code-settings-sync|Sha|3.4.3
uridecode|sry|0.3.5
ghosttext|tok|1.1.0
codetour|vsl|0.0.25
gistfs|vsl|0.0.67
gitdoc|vsl|0.0.6
change-case|wma|1.0.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by mkormendy** [comment]
So I tested with the insider build, and in two scenarios this is the outcome:

**Scenario 1:** when the file has not been edited (just opened), instead of politely crashing, the file I was working on simply closes on its own without any sort of notice.

**Scenario 2:** same as before (screenshot attached).

![Screen Shot 2020-05-15 at 1 03 56 PM](https://user-images.githubusercontent.com/1437667/82081900-b006d300-96ac-11ea-85c1-285067e8c3d6.png)

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
