### ISSUE TITLE
Search all open files does not function properly

### ISSUE THREAD

**Issue by reamesgeo** [microsoft/vscode#97749]
Issue Type: <b>Bug</b>

"Find in Files" (Ctrl-Shift-F) no longer searches all open files.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
tslint|eg2|1.0.44
python|ms-|2020.5.78807

</details>

**Comment by Nokel81** [comment]
This is supper annoying. Until I found this issue I thought I was going crazy.

Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z (1 wk ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by Nokel81** [comment]
Though I did a "Code > Restart to Update" and that might have fixed it.

**Comment by roblourens** [comment]
Can you give more details about exactly what you are seeing?

**Comment by Nokel81** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  I was seeing "search all files" only searching the currently open files (all of them).                                                                                                                                             Sebastian Malton                                                                                                                                                                            From: notifications@github.comSent: May 17, 2020 6:18 PMTo: vscode@noreply.github.comReply to: reply@reply.github.comCc: sebastian@malton.name; comment@noreply.github.comSubject: Re: [microsoft/vscode] Search all open files does not function properly (#97749)  
Can you give more details about exactly what you are seeing?

**Comment by reamesgeo** [comment]
> Can you give more details about exactly what you are seeing?

I can indeed.

A)  Typically I start by opening a pre-existing 'workspace'  with ~10-15 files, either just python or mixed JS/HTML/CSS

B) Initially, Ctrl-Shift-F only yields results on the one file that I am viewing as the 'active' file on the screen;  none of the files open in the background tabs yield any results.

C)  Let's say I have 10 files open;    If I click-cycle through 4 different files to make them the 'active' and open document, and THEN Ctrl-Shift-F,  it will then identify results in those 4 files I've 'made active' at some point during the session, and the 6 remaining ones will still not work.

D) In other words, any files that are 'inactive', opened in the background,  will never yield results in the 'find in all files,'  until they're manually selected first,  and only then will the command search through them.

E)  For most of 2019, when I would Ctrl-Shift-F  to find keywords, things worked as-expected. The problem behavior began in late 2019/early 2020, on several Windows 10 machines simultaneously, and has persisted through multiple Win / VS updates.

**Comment by roblourens** [comment]
I see. This is a known issue, https://github.com/microsoft/vscode/issues/62488, sorry for the trouble
