### ISSUE TITLE
FR: Being able to browse a zip file

### ISSUE THREAD

**Issue by yashshah1** [microsoft/vscode#97748]
Currently, when you try and open a zipfile in VSCode, you are given a message like this:
![image](https://user-images.githubusercontent.com/31387795/81854124-14c21080-957b-11ea-965e-d3373caa7966.png)

## Feature Request
Enable inbuilt support for viewing and browsing a zipfile (something like how vim does it)
![image](https://user-images.githubusercontent.com/31387795/81854997-52736900-957c-11ea-906d-143e066566a2.png)

- Probably start with just viewing a zip and being able to browse the directory structure
- Can be extended to maybe opening and viewing a file

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/75559
