### ISSUE TITLE
Variable paging still faces performance issues 

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9774]
Testing #9684

```
const arr = new Array(Math.pow(10, 9));
console.log(arr);
```

1. Set breakpoint on line `2`.
2. Start debug
3. Expand the `arr` local variable

VS Code will eventually crash. This happens because, I'm guessing, the tree will show `10^7` items in the tree, since the page size is fixed to 100.

Pages should be recursive. Expanding `arr`, in this case, should show a set maximum number of pages (eg 1000); and each page, when expanded, would contain further pages. Eg:

- `[0...10000]`
  - `[0...100]`
    - `0`
    - `1`
    - ...
  - `[100...200]`
    - `100`
    - `101`
    - ...
  - ...
- ...

**Comment by isidorn** [comment]
Yes, good suggestion. I can look into this in debt week.
FYI @weinand

**Comment by weinand** [comment]
Yeah, that would have been my next feature request for variable paging...
Chrome dev tools use the same approach.
