### ISSUE TITLE
In a notebook (.ipynb file) paste double pastes.

### ISSUE THREAD

**Issue by ddouglas87** [microsoft/vscode#97743]
Issue Type: <b>Bug</b>

If I copy text from one cell and paste into another cell it double pastes.

If I cmd+z to undo it undoes one of the two pastes implying the issue is pasting.  In .ipynb files, VSC double pastes.

I tried pasting in a .py file with no issue.  Likewise pasting in the issue reporter has no issue, just in Jupyter Notebook cells.

I manually restarted VSC and the issue went away.  After a while (12 minutes of use) the issue randomly came back when pasting between different notebooks.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|-psn_0_12950617|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.5.78807

</details>

**Comment by alexdima** [comment]
Please open an issue directly against the python extension at https://github.com/Microsoft/vscode-python/issues
