### ISSUE TITLE
Make autocomplete pop-up windows expandable

### ISSUE THREAD

**Issue by Goreuncle** [microsoft/vscode#97740]
Issue Type: <b>Feature Request</b>

Unlike other IDEs, VSC doesn't seem to allow autocomplete pop-up window expansion. 

Such a feature would come in handy, imho.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Afeature-request+label%3Asuggest+label%3Aux
