### ISSUE TITLE
[themes] language specific tokenColors

### ISSUE THREAD

**Issue by yadayadaydadaa** [microsoft/vscode#97753]
`"configurationDefaults: { "[language]": { "editor.tokenColorCustomizations": { … }}}` does not currently seem to do anything in `package.json`. I think it should—please allow it.

**Comment by aeschli** [comment]
We don't support defining tokenColors by language, neither in themes not in settings.
-> `editor.tokenColorCustomizations` can not be scoped by language.

Instead you have to write language specific rules as seen here: https://github.com/microsoft/vscode/issues/20652#issuecomment-409862378

**Comment by yadayadaydadaa** [comment]
> We don't support defining tokenColors by language, neither in themes nor in settings.
> -> `editor.tokenColorCustomizations` can not be scoped by language.
> 
> Instead you have to write language specific rules as seen here: [#20652 (comment)](https://github.com/microsoft/vscode/issues/20652#issuecomment-409862378)

That still does not appear to work in `package.json` `configurationDefaults`. (The package in question https://marketplace.visualstudio.com/items?itemName=vomout.latex-syntax adds special syntax highlighting for certain LaTeX commands. Currently the user has to configure it instead of the package providing sane defaults. Ideally it would be based on semantic highlighting https://github.com/microsoft/language-server-protocol/issues/18 https://github.com/latex-lsp/texlab/issues/235 without any package—just the language server adding command-specific tags and the user configuring what they want to configure—but while waiting for that to get somewhere, TextMate regexp forest approaching SkyNet level consciousness is what we have.)

**Comment by aeschli** [comment]
`configurationDefaults` is only allowed for language scoped settings (`{ "[language]":`...`).
I created https://github.com/microsoft/vscode/issues/97895 to warn about this.

I understand the desire for a grammar author (or semantic token provider) to add colors and styles for new and non-standard tokens/scopes. But its impossible to pick colors and styles that work in all themes. Theming has to be the responsibility of the theme or the user.

I don't have a good solution in mind for this right now.
