### ISSUE TITLE
Cordova Debug won't start

### ISSUE THREAD

**Issue by wimZ** [microsoft/vscode#97751]
Issue Type: <b>Bug</b>

When I start debug in both my Cordova projects, using vscode-insiders debug seems to start for 1-2 seconds then closes without any indication. 

Using the current regular version of vscode everything works as expected.

Version: 1.46.0-insider (user setup)
Commit: e88b8d32aa7233f6cb3665f6dae9fa78b1e8aafb
Date: 2020-05-13T08:04:48.706Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

VS Code version: Code - Insiders 1.46.0-insider (e88b8d32aa7233f6cb3665f6dae9fa78b1e8aafb, 2020-05-13T08:04:48.706Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
bracket-pair-colorizer-2|Coe|0.1.3
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.7.0
vscode-todo-plus|fab|4.17.1
auto-rename-tag|for|0.1.2
minify|Hoo|0.4.3
vscode-azurefunctions|ms-|0.22.0
azure-account|ms-|0.8.11
cordova-tools|msj|1.9.4
JavaScriptSnippets|nat|0.2.0
indent-rainbow|ode|7.4.0
inline-html|pus|0.2.5
java|red|0.61.0
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
JavaScriptSnippets|xab|1.8.0
local-history|xyz|1.8.1

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
Please file issue against Cordova debugger
