### ISSUE TITLE
Extension packs: Conditionally include an extension

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#97750]
Issue Type: <b>Feature Request</b>

The Visual Studio Codespaces extension pack currently includes the Azure Account extension, but doesn't need it when installed in some environments such as GitHub codespaces. @sandy081 I'm not sure how feasible this is, at installation time would it be possible to evaluate a "when" condition for the current remote authority?

VS Code version: Code - Insiders 1.46.0-insider (e88b8d32aa7233f6cb3665f6dae9fa78b1e8aafb, 2020-05-13T08:04:25.590Z)
OS version: Darwin x64 18.7.0

**Comment by sandy081** [comment]
There is no way currently for such a thing but if extension kind of `Azure Account` extension is `ui` then it will not be installed in codespaces.
