### ISSUE TITLE
Why the colon?

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9775]
Testing #9684

Each variable page group seems to end with the colon `:`, as if there is a value right after it.

![image](https://cloud.githubusercontent.com/assets/22350/17137952/3a8904f0-533e-11e6-8dc4-a1e953b45a0e.png)

But there never is 😢

**Comment by isidorn** [comment]
This was originaly proposed by @weinand 
I am fine with removing the colon. @weinand opinion?

**Comment by weinand** [comment]
@isidorn what do chrome dev tools in this case?

**Comment by isidorn** [comment]
@weinand they do not have the colon, and they also do what @joaomoreno proposed in #9774

![screen shot 2016-07-26 at 15 25 11](https://cloud.githubusercontent.com/assets/1926584/17139525/2d8d37d8-5345-11e6-843a-2ff84def34e1.png)

**Comment by weinand** [comment]
@isidorn we should not only remove the colon in this case but establish the rule that there is only a colon if it is followed by a value.

**Comment by weinand** [comment]
@isidorn please consider to use the ellipsis character instead of '..'

**Comment by joaomoreno** [comment]
@isidorn Shouldn't individual indexes *not* have the array brackets?

![image](https://cloud.githubusercontent.com/assets/22350/17207721/2387f580-54b6-11e6-8b2b-0eefc1bff71d.png)

**Comment by weinand** [comment]
@joaomoreno the brackets of the individual indexes are provided by the backend. They are not created in the VS Code debugger UI.
The current strategy for node-debug is to user brackets for arrays only and to use plain numbers for (well known) data structures that preserve insertion order like Maps or Sets.

**Comment by joaomoreno** [comment]
That actually makes sense. Closing.
