### ISSUE TITLE
Extension-aware sorting

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#97765]
This is the usual sort order the following file names will be sorted with:

```
foo
foo_bar
foo_baz
```

The issue is that once those file names get an extension, and the extension is the same, the order gets messed up because _unfortunately_ `_` comes before `.`:

```
foo_bar.ts
foo_baz.ts
foo.ts
```

To make an analogy I think sorting file names should be like sorting people names, you sort by name first and then by surname (or vice versa), whatever the surname is it can't change the sort order people with different names will be in. Similarly file names should be sorted by their "base" name first and then by their extension:

```
foo.ts
foo_bar.ts
foo_baz.ts
```

I don't know if this makes sense to everybody, probably not given how this isn't the default already, but given how there are settings for customizing the sort order already maybe they could be expanded a bit to account for this too?

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/27286 and https://github.com/microsoft/vscode/issues/27759
