### ISSUE TITLE
Always fails to update/download any Package

### ISSUE THREAD

**Issue by A7madSab** [microsoft/vscode#97766]
Issue Type: <b>Bug</b>

Installing a package doesn't work for me, it always fails and promts me to download and install manually 

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.1
vscode-apollo|apo|1.15.4
vscode-svgviewer|css|2.0.0
es7-react-js-snippets|dsz|2.7.1
vsc-python-indent|Kev|1.8.1
python|ms-|2020.3.71659
remote-wsl|ms-|0.42.3
color-highlight|nau|2.3.0
lorem-ipsum|Tyr|1.2.0
vscodeintellicode|Vis|1.2.6
material-theme|zhu|3.4.0

</details>

**Comment by joaomoreno** [comment]
Are you behind a proxy? Can you show me a screenshot of the error?
