### ISSUE TITLE
Title on external link notification is too close to border

### ISSUE THREAD

**Issue by devinvalenciano** [microsoft/vscode#97760]
- VSCode Version: 1.46.0-insider
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Click on external link (I clicked on the logo at the top of the "Bookmarks" extension page)
2. External link confirmation box should pop up, title of the box will be too close to the left side of window.

![image](https://user-images.githubusercontent.com/1389808/81871886-9428f300-952d-11ea-8406-7f80c24066f2.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment]
@sbatten is this a general native widget issue?

**Comment by sbatten** [comment]
external https://github.com/electron/electron/issues/17736

**Comment by JacksonKearl** [comment]
This will be fixed if/when the electron fix goes in, not much I can do here.
