### ISSUE TITLE
Debug console history shouldn't be the first thing selected

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#97761]
- Have a js debug session
- Type `this.blah = 1` in the debug console
- Type `this.bl` looking for completions on `this`
- I quickly hit `tab` expecting it to complete `blah` the same way it would work in the editor, but it picks a history entry that I didn't mean to repeat

![image](https://user-images.githubusercontent.com/323878/81874088-c55fee00-9542-11ea-81cb-ce107a83467a.png)

Chrome/Edge Devtools for comparison
![image](https://user-images.githubusercontent.com/323878/81874195-ff30f480-9542-11ea-9c33-a3acef0d641d.png)

And since the history search is quite fuzzy, this happens a lot. Could we put the history entries at the bottom? I think that would address this for me.

cc @connor4312

**Comment by isidorn** [comment]
That was my intention, but I was unsucesfful to make the history always at the end since the suggest widget sometimes resorts it. I am using a silly approach of having a `ZZZ` sort text.
I am open to PRs that fix this. Code pointer https://github.com/microsoft/vscode/blob/f432c0e060e9b964ece8b1b461ae7c51262b316b/src/vs/workbench/contrib/debug/browser/repl.ts#L183

fyi @jrieken on ideas

**Comment by jrieken** [comment]
`sortText` doesn't count anymore as soon as there is prefix to rank against, e.g the history entry selects a large portion of text and I guess therefore gets a very good score...

**Comment by jrieken** [comment]
This is quite tricky actually, the score gets better the more it matches (which I believe makes sense) but this does favour completions that select longer prefixes...

**Comment by tabaddor** [comment]
I can look into this issue.

**Comment by isidorn** [comment]
@tabaddor I think it might not be that simple, looking at Joh's comment from above. You are welcome to try to solve this.

**Comment by roblourens** [comment]
I don't know if I'm the only one with this issue, but makes the console really hard to use imo. What if there was a different binding to trigger history vs completions? Or maybe even just a setting to disable history in completions. I can use arrow keys for history 90% of the time.

![image](https://user-images.githubusercontent.com/323878/86191045-e54f6f00-bafa-11ea-8ac3-66bae025c330.png)

**Comment by isidorn** [comment]
Yeah you can disable them for now 	`"debug.console.historySuggestions": false`

**Comment by roblourens** [comment]
Oh sorry didn't realize it already exists

**Comment by isidorn** [comment]
No worries, idealy we should fix this and not have a setting to disable. But this is just how things are right now.
