### ISSUE TITLE
File ends up empty after crash in window

### ISSUE THREAD

**Issue by chivoyage** [microsoft/vscode#97768]
- VSCode Version: 1.45.0 
- OS Version: W10 1909

Steps to Reproduce:

1. Install any html5 previewer plugin
2. Write bad code for a loop that throws infinite errors while creating webgl objects on canvas. (was using threejs)
3. Wait until vscode is non responsive. Force close.
4. Voila, your file is 0kb and you have lost 2 days worth of code. (later recovered from cloud backup)

Does this issue occur when all extensions are disabled?: No

**Comment by bpasero** [comment]
@chivoyage sorry to hear that you lost your work. Do you happen to know if the file was dirty at the point the window crashed or saved?

**Comment by chivoyage** [comment]
I save files frequently, it was saved before the 2-3 lines of the bad loop. So that probably makes it dirty when the window froze?

I was able to restore my work because I figured I had file Version history on and my file was in a cloud folder (but this is outside of vscode).

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by bpasero** [comment]
> I save files frequently, it was saved before the 2-3 lines of the bad loop. So that probably makes it dirty when the window froze?

I cannot follow, why would it become dirty when the bad loop executed?

**Comment by chivoyage** [comment]
I didn't get what you meant by dirty, that's why the question mark. Simply speaking, the few lines of the loop were unsaved upon freeze, everything before was saved.

The freeze happened because html preview was on in vscode and the loop was throwing infinite canvas errors.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by bpasero** [comment]
If the file is saved in VSCode and VSCode crashes I would not know how the file can end up empty. I have an idea of what can happen if the file is not saved because then we keep a backup of the contents to restore on next start.

**Comment by chivoyage** [comment]
I was baffled too. I had been working on it and saving it frequently for 2 days, a few PC reboots in between. After the freeze and force close, the first thing I did is reopen vscode, where the file opened as empty and then I panicked and went to the folder in explorer and the file showed as 0kb.
If vscode keeps any kind of log, I can forward that.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by bpasero** [comment]
@chivoyage you could do F1 > "open logs folder" and zip up the contents. They include all the logs we produce. Mail is fine.

**Comment by chivoyage** [comment]
Sent you a zip!

**Comment by bpasero** [comment]
@chivoyage thanks, I saw errors but not related to saving files unfortunately. 

Here is the scenario where a file can end up empty:
* file is dirty
* you save it (or it gets auto saved)
* we use node.js for writing to the file
* one of the first things node.js is doing when writing is truncate the file to 0 bytes
* then the data is written into the file

If between the last step and the step before a crash happens, there is a chance that the file ends up with 0 bytes. However, that should only happen if the file was not saved already, hence my question for how this can be reproduced.

**Comment by chivoyage** [comment]
One point I may have failed to mention is 
- I did try pressing ctrl+s multiple times during the freeze. (which I assumed probably didn't work)
And as mentioned in my first message,
- I force closed it (because it was unresponsive for a long time)
- it didn't crash on me.

So could be that despite being unresponsive, node.js might have started the save process from one of my ctrl+s's. But I assumed force closing shouldn't do anything to the original file.

Is there a way where VScode can temporarily autobackup in logs somewhere before node.js truncates the file to write to it?

**Comment by bpasero** [comment]
Ah yeah so that might explain it. There is a chance that this Ctrl+S still went to the file and in the middle of writing VSCode was crashing. We currently do not have a way to write to a different file and then overwrite the original one as this may cause external tools to think the file was renamed/replaced instead of just written to. I think this technique of file writing is called "atomic writes" but may come with its own set of issues. 

Though arguable this technique could be used to keep a backup of the original contents before trying to write.

**Comment by bpasero** [comment]
Btw very much related and maybe should merge into this issue: https://github.com/microsoft/vscode/issues/34915

**Comment by chivoyage** [comment]
Got it. So now I can certainly try and avoid this scenario except in the case of power-loss-on-desktop-without-UPS but the atomic write can certainly be debated since this may happen in multiple scenarios. 

Sure, can merge it!

**Comment by bpasero** [comment]
So one change I did a long time ago is what VSCode does when you save while the file is not dirty. We used to only touch it (change the modification time) but then changed that to actually write the same contents to the file that are already in:

https://github.com/microsoft/vscode/blob/869929e8c6ccee871e483d32335b884d2a372e96/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L758-L778

I wonder if this code should change to be more careful here because at this point there is literally no backup of the file (if the file was dirty we actually have a backup to restore from).

**Comment by chivoyage** [comment]
Yeah, I'd vote in favor of backing-up non-dirty files at least until the next save.  
I'm glad onedrive version history saved me.

Anyway, how can I merge this with #34915? Or can you do it? 
I'm more of designer, less of a developer so don't have much experience with github.
