### ISSUE TITLE
titleBar.activeBackground is not working in fn+f5 environment

### ISSUE THREAD

**Issue by jmhungdev** [microsoft/vscode#97772]
- VSCode Version: 1.45.0
- OS Version: macOS Mojaves 10.14.6 (18G4032)

Steps to Reproduce:

1. creating a fresh start theme through Yeoman in json file
2. set titleBar.activeBackground color (to any color that's noticeably changed)
3. press fn + f5 in a simulated VS Code environment renders changed theme
4. titleBar.activeBackground color is not changed

a list of keys that don't work in this simulated environment:
  - titleBar.activeBackground
  - titleBar.inactiveBackground
  - window.inactiveBorder
  - window.activeBorder

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by sbatten** [comment]
Extension Host environments on mac os do not use the custom title bar that is needed for these keys to have any effect. @bpasero is this limitation still needed?

**Comment by bpasero** [comment]
@sbatten yes needed, because of the fact that we want to use devtools in that target and there is a long outstanding bug in Electron that you cannot move a window with custom titlebar when devtools are visible in the same window. 

See https://github.com/electron/electron/issues/3647

**Comment by bpasero** [comment]
I think this is not worth pushing...
