### ISSUE TITLE
how to use postinstall script  in extension development

### ISSUE THREAD

**Issue by Abbyyan** [microsoft/vscode#97776]
I'm develop an extension and want to do some report function after my extension is installed, so i use the `postinstall` script in `pacakge.json`, but it seems not worked. How should i use this script or if there are some methods that i can realize this function please? Thanks a log.

Now i use `postinstall` in `package.json` just like this, but it doesn't work. Hope for some suggestions. Thanks a lot. 
```shell
"scripts": {
    "vscode:prepublish": " npm run compile;  ",
    "compile": "npx tsc -p ./ ; ",
    "postinstall": "sh build/report.sh"
  },
```

**Comment by sandy081** [comment]
`postinstall` is not meant for vs code and it is `node` specific. There is no `post install` for extension installation.

**Comment by Abbyyan** [comment]
Does the postinstall in node worked after the extension installed ?

**Comment by sandy081** [comment]
Nopes
