### ISSUE TITLE
[ms-vscode.cpptools]: Menu item references a command 'workbench.action.gotoSymbol' which is not defined in the 'commands' section

### ISSUE THREAD

**Issue by fangguangyang** [microsoft/vscode#97774]
- VSCode Version: 1.46.0-insider
- OS Version: win10 + remote-ssh; remoteos: centos7.7

Steps to Reproduce:

1.just open vscode
![image](https://user-images.githubusercontent.com/14014903/81885835-cab64a80-95cd-11ea-9d4c-82048c91047d.png)

Does this issue occur when all extensions are disabled?: No

**Comment by fangguangyang** [comment]
The previous version did not have this problem, it appear today when I update vscode to the lastest version

**Comment by sean-mcmanus** [comment]
I repro this too. It's for the "Go to Symbol in Editor".

Our C/C++ extension uses

```
        {
          "when": "editorLangId == c",
          "command": "workbench.action.gotoSymbol",
          "group": "other1_navigation@3"
        },
        {
          "when": "editorLangId == cpp",
          "command": "workbench.action.gotoSymbol",
          "group": "other1_navigation@3"
        }
```

Let us know if we need to change something with our extension.

**Comment by jrieken** [comment]
Yeah, I have changed there something yesterday...
