### ISSUE TITLE
It keeps repeating to sign in even after I do.

### ISSUE THREAD

**Issue by UNBRUHMOMENTO** [microsoft/vscode#97770]
Issue Type: <b>Bug</b>

Basically, i want to join a liveshare session when it tells me to sign in. I sign in with Microsoft (Tried GitHub too) and when i go back, it signs me in. Though 2 seconds later, the same message pops up to say to sign in again. Then it tells me that my sign in in token is expired.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3194)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.19GB free)|
|Process Argv|-n C:\Users\Joel C\AppData\Local\Temp\vsliveshare\tmp-E6D960429C00B27607FD2A68AD31A70DE28C\Visual Studio Live Share.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vsliveshare|ms-|1.0.2106

</details>

**Comment by keremispirli** [comment]
Same behavior in 1.46 and 1.47.

**Comment by RMacfarlane** [comment]
Are you still seeing this in the latest version of VS Code?
