### ISSUE TITLE
Unused Let and Used Const too similar in typescript with the new Semantic Token Color Customization default colours

### ISSUE THREAD

**Issue by David-Tennant** [microsoft/vscode#97784]
- VSCode Version: 1.45.0
- OS Version: Microsoft Windows 10 Pro, 10.0.183363 Build 18363

Issue:

Steps to Reproduce:

1. Use theme "Dark+" aka "default dark"
2. Create a typescript file with used and unused consts and lets

Does this issue occur when all extensions are disabled?: Yes

Thanks for the new colorization. Unfortunately, the color of a used `const` looks very similar to the color of an unused `let` especially when you have underlining messing with the view of the colors

With underlining:

![image](https://user-images.githubusercontent.com/40059359/81904628-d0a72e00-95c3-11ea-81dd-98e85dd820f9.png)

Without underlining:

![image](https://user-images.githubusercontent.com/40059359/81904694-e583c180-95c3-11ea-84bb-2d98c74fd158.png)

I have tried tweaking the colors but haven't found a comfortable color yet. Hence an issue without a PR haha. Thanks again for the feature its quite nice

**Comment by mattacosta** [comment]
Duplicate of #95346.

If you want the old colors back, you can add this to your settings:
```json
"editor.tokenColorCustomizations": {
    "[Default Dark+]": {
        "textMateRules": [
            {
                "scope": ["variable.other.constant", "variable.other.enummember"],
                "settings": {
                    "foreground": "#9CDCFE"
                }
            }
        ]
    },
}
```

**Comment by David-Tennant** [comment]
Duplicate of #95346.

I will be closing this now. Thanks, @mattacosta for finding the other issue. I didnt see it
