### ISSUE TITLE
Error traduccion en Español

### ISSUE THREAD

**Issue by icao** [microsoft/vscode#97786]
Issue Type: <b>Bug</b>

Existe un error de traducción en esta sección donde describe Editor: Fortmat on save 

en la descripcion aparece: Error al guardar '{0}': Un formateador debe estar disponible...........

El error es que parece -> r '{0}'
En la version en ingles no aparece.
Me di cuenta porque pense que tenia que configurar un objeto con algun formateador por default, pero no es asi. El error es que aparece n esos caracteres en la traduccion en Español

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (7.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
scss-lint|ada|0.1.10
Bookmarks|ale|11.2.0
vscode-color|ans|0.4.5
vscode-custom-css|be5|3.0.9
simple-react-snippets|bur|1.2.2
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
compulim-vscode-closetag|Com|1.2.0
vscode-svgviewer|css|2.0.0
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.35.1
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.14.5
vscode-npm-script|eg2|0.3.11
eppz-code|epp|1.2.41
vsc-material-theme|Equ|32.6.0
prettier-vscode|esb|4.7.0
auto-rename-tag|for|0.1.2
terminal|for|0.0.10
sass-lint|gle|1.0.6
vuejs-peek|ish|0.0.3
svg|joc|1.1.8
docthis|joe|0.7.1
intellij-idea-keybindings|k--|0.2.39
vsc-python-indent|Kev|1.10.1
csstriggers|kis|0.12.1
git-indicators|lam|2.1.2
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.2.0
vscode-language-pack-es|MS-|1.45.1
vscode-edge-devtools|ms-|1.0.7
python|ms-|2020.5.78807
remote-wsl|ms-|0.44.2
powershell|ms-|2020.4.0
vsliveshare|ms-|1.0.2106
color-highlight|nau|2.3.0
vetur|oct|0.24.0
react-proptypes-intellisense|OfH|1.0.3
vuehelper|oys|0.1.0
material-icon-theme|PKi|4.1.0
vscode-template-literal-editor|pli|0.9.0
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.5
sass-indented|rob|1.5.1
vue-vscode-extensionpack|sdr|0.2.0
bunker|sld|1.1.6
vscode-field-lights|sve|0.0.11
notification-tester|svi|2.4.8
language-stylus|sys|1.11.0
ayu|tea|0.18.0
es6-string-html|Tob|1.8.8
vscode-iconfont-preview|und|0.1.0
vscode-todo-highlight|way|1.0.4
vscode-jumpy|wma|0.3.1
markdown-all-in-one|yzh|2.8.0
html-css-class-completion|Zig|1.19.0

(34 theme extensions excluded)

</details>

**Comment by danyeh** [comment]
Following up [336350]

**Comment by danyeh** [comment]
Fixed in 1.52 language pack. https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-es
