### ISSUE TITLE
Text proposals make sense inside strings

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#9778]
Refs: #9744

- VSCode Version: insider
- OS Version: os x

Steps to Reproduce:

1. Open a json file, go inside a string "" and trigger suggest
2. Notice that the only suggestion does not make sense
3. This is the only use case where text proposals actually make sense and this experience is now worse when compared to the stable IMHO

![screen shot 2016-07-26 at 14 56 06](https://cloud.githubusercontent.com/assets/1926584/17138566/36f6feac-5341-11e6-9541-35a548c4f57a.png)

**Comment by aeschli** [comment]
Fixed. Removed the empty string proposal and improved the word regex so that the word base proposals make more sense.
