### ISSUE TITLE
File extension cpuprofile not recognized by javascript profiler when filename changed using Mac's finder

### ISSUE THREAD

**Issue by refs** [microsoft/vscode#97792]
- VSCode Version: 1.46.0-insider (Commit: e1d8f5155c0db5ffdc130c9aa0f14efac02dfdfb)
- OS Version: MacOS Catalina, 10.15.4

Loading a cpuprofile results on the javascript profiler does not recognize the `.cpuprofile` extension.

Steps to Reproduce:

1. Follow the instructions in [profile the running extensions](https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions)
2. end up with the following cpuprofile file: [CPU-20200514T083510.480Z.cpuprofile.txt](https://github.com/microsoft/vscode/files/4627072/CPU-20200514T083510.480Z.cpuprofile.txt)
3. Remove the `.txt` suffix from step 2
4. Load the file on the javascript profiler
5. Can't load file:

![grafik](https://user-images.githubusercontent.com/6905948/81913577-73fe4000-95d0-11ea-8678-544b7ce9007a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@refs A `.cpuprofile` must be loaded in the JavaScript Profile tab:

![image](https://user-images.githubusercontent.com/5047891/81914964-40241a00-95d2-11ea-9901-da285c188456.png)

**Comment by refs** [comment]
@alexdima that is indeed the sequence of steps I follow:

![screencast 2020-05-14 11-03-41](https://user-images.githubusercontent.com/6905948/81915450-e2440200-95d2-11ea-9afd-8e9ea7796ccf.gif)

**Comment by alexdima** [comment]
@refs Can you please use `ls` in a terminal to confirm the file extension is `.cpuprofile`? I have just tried to profile the extensions, which generates a file named `CPU....cpuprofile.txt` and for whatever reason using the macOS finder to strip the `.txt` extension does not work. The macOS finder is ignoring my file rename. I have tried in a terminal and that worked well.

**Comment by refs** [comment]
wow... can confirm that renaming it via the cli did solve the issue, as opposite to using the finder app to rename it. The file extension on an `ls` was `.cpuprofile`, but using the finder app, even with the `.cpuprofile` extension, the finder still thinks it's a text file. Only after renaming through the cli it doesn't recognize it as a text file anymore, and loading works.

**Comment by alexdima** [comment]
- the macOS finder is written by Apple
- the Chrome developer tools are written by Chromium

Please create issues against those projects if you want.
