### ISSUE TITLE
Property type dedicated to filepath in contribution points

### ISSUE THREAD

**Issue by pierretallotte** [microsoft/vscode#97796]
According to the documentation page of [Contribution Points][1] of Visual Studio Code, a property can have only one of the following type: `number`, `string`, `boolean`, `object` or `array`:
> **type**
>
>Entries of type `number`, `string`, `boolean` can be edited directly in the Settings UI.
>
>For `boolean` entries, the `description` (or `markdownDescription`) will be used as the label for the checkbox.
>
>Other types, such as `object` and `array`, aren't exposed directly in the settings UI, and can only be modified by editing the JSON directly. Instead of controls for editing them, users will see a link to `Edit in settings.json` as shown in the screenshot above.

Therefore, if I want a property that will contain a file path, I should use the `string` type.

The issue with the `string` type is the user has to type the file path manually (or copy-paste it). It can be interesting to have a dedicated type for filepath that can open a file browser to help the user selecting the file/folder associated to this property.

  [1]: https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema

**Comment by sandy081** [comment]
I do not think we can allow a type called `filepath` as we use JSON schema. It seems it is needed only for UI for allowing a file picker.

**Comment by roblourens** [comment]
I think having extra metadata for this sort of thing would make sense. There is an open issue for it here: https://github.com/microsoft/vscode/issues/56834
