### ISSUE TITLE
Display a property in the settings view depending on the value of another property

### ISSUE THREAD

**Issue by pierretallotte** [microsoft/vscode#97797]
The `package.json` file of my Visual Studio Code extension looks like this:
```json
{
    "contributes": {
        "configuration": {
            "properties": {
                "myplugin.optional.behavior": {
                    "type": "string",
                    "enum": [
                        "Optional",
                        "Mandatory",
                        "None"
                    ]
                },
                "myplugin.optional.behaviorvalue": {
                    "type": "string"
                }
            }
        }
    }
}
```
Here, I want that if my user specify the value `None` to `myplugin.optional.behavior`, the property `myplugin.optional.behaviorvalue` would not be displayed in the settings view of my extension. On the other hand, if the user specify `Mandatory`, I would like to make the property `myplugin.optional.behaviorvalue` not optional.

I think it can be interesting to add a new configuration key such as:
```json
{
    "contributes": {
        "configuration": {
            "properties": {
                "myplugin.optional.behavior": {
                    "type": "string",
                    "enum": [
                        "Optional",
                        "Mandatory",
                        "None"
                    ]
                },
                "myplugin.optional.behaviorvalue": {
                    "type": "string",
                    "dependsOn": "myplugin.optional.behavior",
                    "mandatoryIf": [ "Mandatory" ],
                    "disabledIf": [ "None" ]
                }
            }
        }
    }
}
```
The new `dependsOn` key indicates the property `myplugin.optional.behaviorvalue` is displayed (or not) depending on the value given to the corresponding property (in my example `myplugin.optional.behavior`). The `mandatoryIf` key indicates which values of the `dependsOn` property make it mandatory and the `disabledIf` key makes the property not displayed for the corresponding value of the `dependsOn` property.

**Comment by roblourens** [comment]
I'm curious what the use case is for this? Also this is introducing the concept of a "mandatory" setting which is not something we currently have. There is probably a better way to model this using a single setting.

**Comment by pierretallotte** [comment]
The extension needs some information about the build. This information can be located in a VS Code build task (1), in a compilation database (2) or the user can let the extension automatically determines the configuration to use (3).
In the case (2), the extension needs an extra information about the location of the compilation database. In the case (3), no more information are necessary. And, for the case (1), it depends if the user wants to use the default build task of the project or use another one.

Therefore, I imagine the following workflow: the user selects how he wants to configure the extension: build task (1), compilation database (2) or automatically (3).
If (1) or (2), a new field appear below to let the user enters the name of the build task (1) or the location of the database (2). The description associated to the field can vary depending of (1) or (2). If the user selects (3), no extra field appear.
The concept of "mandatory field", for case (2), can indeed be managed by the extension.

Currently, I have to always display the second property whatever the user selected before. The description says the same in every cases and I find that very confusing for the user as the same property can store a build task name (1), a filepath (2) or nothing (3).

**Comment by roblourens** [comment]
Thanks for the explanation. I think that dynamic requirements like this is not a good fit for our settings schema or editor. We actually already have dependencies between settings like this, like afterSaveDelay: 
![image](https://user-images.githubusercontent.com/323878/82449214-7d742600-9a70-11ea-8379-92aa26f05e96.png)

So I would recommend adding a similar note to your second setting, or you can pack all that info into a single object-type setting (but then you won't be able to set it through the settings UI).
