### ISSUE TITLE
Search: should not have theme dependent rules

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#97794]
Such as:

https://github.com/microsoft/vscode/blob/046e3c7f0ea03489293e29c79093020d19ffce51/src/vs/workbench/contrib/search/browser/media/searchview.css#L305-L308

**Comment by roblourens** [comment]
That one rule doesn't make sense and I removed it, but are you saying that we shouldn't have rules with the `vs/vs-dark` classes in css at all?

**Comment by bpasero** [comment]
@roblourens 

> but are you saying that we shouldn't have rules with the vs/vs-dark classes in css at all

I think we can look at it case by case, but typically I think this is debt for various reasons:
* it could mean that you declare a color which then cannot be themed
* margins, paddings, etc. should typically not be theme dependent, unless maybe you do it for high contrast theme only which is a bit special

**Comment by roblourens** [comment]
Ok. The remaining rules are button hovers, e.g. `background-color: rgba(255, 255, 255, 0.1)`, I don't know if they should be themeable or not, other hover states are but these are more comparable to toolbar action items which don't have hover states
