### ISSUE TITLE
Eternally "Checking For Updates..." 

### ISSUE THREAD

**Issue by nchammas** [Microsoft/vscode#978]
If you leave VS Code open long enough, the "Checking For Updates" menu eventually hangs in this state:

![screen shot 2015-12-03 at 12 16 16 pm](https://cloud.githubusercontent.com/assets/1039369/11568017/efb9bb8a-99b7-11e5-8813-2a9c934e7daf.png)

Once in this state, you need to restart VS Code to get it to really check for updates.

I'm not sure what triggers this, but I've seen this behavior since many versions ago. It may relate to locking and unlocking my Mac, or it may just be a matter of keeping VS Code open for a long time. I'm not sure.

**Comment by rhires** [comment]
I have this issue as well.

**Comment by awgeorge** [comment]
Had this issue with 0.10.3 OSX - The automatic update never fired I ended up downloading it again manually.

I had a machine running 0.10.1 that also wasn't updating.

**Comment by nchammas** [comment]
As of 0.10.6, this isn't happening for me anymore.

@rhires / @awgeorge - What about you?

**Comment by nchammas** [comment]
Never mind. It's happening again. Still haven't been able to figure out what triggers this behavior.

**Comment by nchammas** [comment]
As of 1.1.1, I'm not seeing this anymore. I'm not sure when exactly this stopped happening, though.

**Comment by awgeorge** [comment]
1.1.1 seems to be fine for me too - Like yourself, wasn't paying attention to when it was fixed.

**Comment by wub** [comment]
As of 1.10.2 on Windows 8.1 x64, this is happening for me.

**Comment by atif089** [comment]
1.13.1 and Windowx 10 x86 and this still happens. Happened on Mac OSX as well this morning. After a bunch of restarts, it updated.
