### ISSUE TITLE
Smart indent in braces does not respect indentation settings

### ISSUE THREAD

**Issue by alanondra** [microsoft/vscode#97802]
Issue Type: <b>Bug</b>

Set the following in settings.json:
```
...
"editor.insertSpaces": false
...
```

Take an existing block of code:
```
bar();
```

Wrap code with conditional statement:
```
if (foo) {
bar();
}
```

Expected result:
Indented `bar();` with an additional tab.

Actual result:
Indented `bar()`; an additional level, with tabs on all three lines converted to spaces.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (9.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.3.11
gitignore|cod|0.6.0
php-debug|fel|1.13.0
php-cs-fixer|jun|0.1.151
php-docblocker|nei|2.1.0

</details>

**Comment by alexdima** [comment]
@alanondra I think you are missing some steps in your description, I don't expect `bar();` to be indented if I type a line above it and a line below it. Why should it be indented? Do you run an action? Typing will not indent other lines.
