### ISSUE TITLE
Julia Notebook support for VS Code

### ISSUE THREAD

**Issue by rangan2510** [microsoft/vscode#97806]
I love how I can write python scripts and run them in the interactive notebook on VS Code.  I would love to have a similar feature available for Julia where cells can be separated using #%% or maybe even something else.

**Comment by rebornix** [comment]
Once we make the Notebook API public, this can be done by an extension, thanks!

**Comment by davidanthoff** [comment]
We are working on support for Julia Notebooks that use the Notebook API in [this branch](https://github.com/julia-vscode/julia-vscode/pull/980). Things are pretty functional already!
