### ISSUE TITLE
Unable to install coreclr-debug on Elementary OS

### ISSUE THREAD

**Issue by Firaenix** [Microsoft/vscode#9780]
- VSCode Version: Version 1.3.1 and Version 1.4.0-insider
- OS Version: Elementary OS Freya 0.3.2

Steps to Reproduce:

1. Install Elementary OS
2. Install Visual Studio Code
3. Install C# extension
4. Load a .NET Core project
5. Attempt to debug the project

Able to see the error log when the developer console is open within Visual Studio Code.
Should this not install correctly even if using Elementary OS? 
Elementary OS is built on Ubuntu 14.04.

Thanks very much.

![image](https://cloud.githubusercontent.com/assets/8898038/17138956/d4605fd2-5385-11e6-8697-b3bb8f609024.png)

**Comment by kieferrm** [comment]
@Firaenix I moved this defect to https://github.com/OmniSharp/omnisharp-vscode/issues/625. Pls subscribe there.
