### ISSUE TITLE
Proxy authentication window

### ISSUE THREAD

**Issue by paullAlves** [microsoft/vscode#97804]
Issue Type: <b>Bug</b>

When using proxy, the buttons OK and Cancel of atuthenticatication window no has function.  

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (0.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
gitlens|eam|10.2.1
XMLLanguageSupport|IBM|0.0.1
xml-format|mik|1.0.2
csharp|ms-|1.21.18
vetur|oct|0.24.0
material-icon-theme|PKi|4.1.0
vscode-xml|red|0.11.0
vscode-yaml|red|0.8.0
vscode-xml-complete|rog|0.2.10
vscode-apielements|vnc|0.6.7
plsql-language|xyz|1.8.2

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Fixed in `master` already.
