### ISSUE TITLE
launch.json: Allow to specify process name filter in command:pickProcess OR present picker when using processName property when there is more than one process

### ISSUE THREAD

**Issue by bergmeister** [microsoft/vscode#97815]
As a user, who wants to a process named `foo` but there is more than one process with this name, I'd like to attach to it without having to type the process name in the filter presented by `${command:pickProcess}`. Essentially, I want an option to pre-populate the filter.
An alternative would be to improve the `processName` property to not give an error to the user if there is more than one process but rather present a picker with the list of processes of that time.

Background: When debugging binary PowerShell modules (i.e. written in .Net). there is usually more than one PowerShell process running.

**Comment by weinand** [comment]
@bergmeister VS Code does not provide generic "Pick Process" functionality; instead individual extensions contribute process pickers for their specific domain.

You mention `command:pickProcess` which is the node.js picker but then you are talking about PowerShell modules. So I don't really understand the scope of your feature request...

Please note: a process picker is just a VS Code "command" and as such can be implemented in an extension. For using it in a launch.json or task.json you can just refer to it via the variables syntax: `${command:<picker_command_id>}`. So if you want to have a better picker, you can just copy an existing picker from an extension and improve it in your own extension (and publish it on the Marketplace).

**Comment by bergmeister** [comment]
@weinand My specific use case is attaching to a binary PowerShell module, i.e. attaching to a PowerShell process of (which is named either `powershell` or `pwsh`). A PowerShell process is essentially just a .Net or .Net Core process, the attaching itself is done by the C# extension called `OmniSharp`. If I understand you correctly, this would be a feature request for the `OmniSharp` extension then?

**Comment by weinand** [comment]
@bergmeister If there is already a picker that has the basic functionality (e.g. listing all .Net or .Net Core processes), then I suggest to file the feature request against the extension that own that picker. That might be "OmniSharp" then.

But if the picker is more PowerShell specific, then file against the PowerShell extension (even if they don't have a picker yet; they might be interested in creating one...)

Or be adventurous and roll your own ;-)

**Comment by aprilandjan** [comment]
For anyone who is interested in this, I just made a simple extension to provide such a configurable `PickMatchedProcess` command while debugging `node.js` programs, see <https://github.com/aprilandjan/vscode-node-debug-process-picker>.

The core codes are in fact from [vscode-node-debug](https://github.com/microsoft/vscode-node-debug), and it should be easy to be modified to find out other language processes.

Thank @weinand for suggestions in https://github.com/microsoft/vscode/issues/97815
