### ISSUE TITLE
COMPILING VERY SLOWLY

### ISSUE THREAD

**Issue by ujjwalsrivastava-us** [microsoft/vscode#97811]
Issue Type: <b>Bug</b>

Because of new update my vs code has started comiling code very slowly

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

If anyone's going to be able to help you they'll first need to know what language you're coding in. And they may also want to you follow the steps in this wiki page:

https://github.com/microsoft/vscode/wiki/Performance-Issues

Finally, PLEASE DON'T SHOUT in your issue titles.
