### ISSUE TITLE
Lots of bogus proposals for $schema after editing $schema value

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#9781]
Refs: #9744

- VSCode Version: insiders
- OS Version: os x

Steps to Reproduce:

1. Create a new file myjson.json, trigger intelli-sense for $schema, choose first proposal
2. Delete the first proposal character by character, trigger intelli-sense again, notice a bunch of bogus proposals. Seems like you remember all the past values of the property while I was deleting it

![schemaproposals](https://cloud.githubusercontent.com/assets/1926584/17139073/465733e2-5343-11e6-99a3-656b99287f53.gif)

**Comment by aeschli** [comment]
Good catch!

**Comment by isidorn** [comment]
While verifying found #9883
