### ISSUE TITLE
Controls should not have superfluous help text in their accessible labels

### ISSUE THREAD

**Issue by Neurrone** [microsoft/vscode#97818]
Issue Type: <b>Bug</b>

CC: @isidorn

1. Multiple tree views such as the explorer view, the tree view rendering the results of a find in project etc all have this help text as part of the tree view's accessible label: "Use the navigation keys to navigate.".

Although not a bug strictly speaking, it doesn't really convey any additional useful information (the tree view role is sufficient). More significantly, the label is read in its entirety before NVDA starts to read the items inside the tree view when it gains focus, which is slightly annoying.

Hence, I would like to propose removing it.

If there're no objections, I'd like to take this opportunity to submit my first PR to Vs Code to fix this :)

VS Code version: Code - Insiders 1.46.0-insider (288852d8c26d797974bfb8aed06e1bff9b809223, 2020-05-12T05:43:31.363Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (3.68GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|33%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
notes|can|1.0.0
vscode-markdownlint|Dav|0.35.1
vscode-eslint|dba|2.1.5
prettier-vscode|esb|4.7.0
rest-client|hum|0.23.2
python|ms-|2020.5.78807
remote-wsl|ms-|0.44.2
cpptools|ms-|0.28.0
Go|ms-|0.14.2
vsnotes|pat|0.7.1
rust|rus|0.7.8
markdown-preview-enhanced|shd|0.5.3
vscode-webhint|web|1.5.5

</details>

**Comment by Neurrone** [comment]
This is also applicable to the quick picker as well: "Quick Input. Use the navigation keys to navigate.  list." would read better if it just announced "Quick Input list"

Probably best to remove all references to this text project wide.

**Comment by isidorn** [comment]
Great proposal but we actually already removed it, more details here https://github.com/microsoft/vscode/issues/97510
Thus closing as duplicate and if you update to latest insiders should be fixed.

As for the first PR, we can find some other area. Maybe the references list for enter and space moving focus / not moving focus. Let me know what you are interested in and I can provide pointers.
Also fyi we have channel for accessibility so consider joining it https://gitter.im/Microsoft/vscode-a11y

**Comment by Neurrone** [comment]
Wow, glad that I filed an issue first as I wouldn't have realized this was already worked on.

> Maybe the references list for enter and space moving focus
Sure, that sounds like a manageable first PR :)
