### ISSUE TITLE
Disable Editor When Disconnected

### ISSUE THREAD

**Issue by kingces95** [microsoft/vscode#97828]
I expect that if VSO is unable to save a file, then VSO will disable editing the file. Actually, if I enter the disconnected state, I'm able to edit files but when I go to save them I discover I cannot save. 

![image](https://user-images.githubusercontent.com/4120386/81962269-34732c00-95af-11ea-81b9-9ff46a1a19a3.png)

**Comment by bpasero** [comment]
Thanks for reporting this issue. It seems to be about GH Codespaces or Visual Studio Online. As such can you please report it here: https://github.com/MicrosoftDocs/vsonline/issues

Thanks!
