### ISSUE TITLE
Can't read HTTP response headers in variables pane or hover

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9782]
I have some code that uses Node's base `http` module to do a request.

I can't seem to inspect the response's headers in the variables pane nor in the hover.

I could only read them when using the repl:

![image](https://cloud.githubusercontent.com/assets/22350/17139201/c01a498a-5343-11e6-9cfe-766231fc9251.png)

**Comment by isidorn** [comment]
I believe this is coming from the node adapter, thus forwarding to @weinand

**Comment by weinand** [comment]
@joaomoreno what version of node is this?

**Comment by joaomoreno** [comment]
The one in the current electron we use: so 5.10.

**Comment by weinand** [comment]
@joaomoreno But this was not extension host debugging, so you were not running electron's node?

**Comment by weinand** [comment]
@joaomoreno I cannot reproduce.  Can you?

**Comment by joaomoreno** [comment]
I couldn't reproduce it more than once, no.
