### ISSUE TITLE
VS Code creates directory in workspaceStorage for every file you open from command line.

### ISSUE THREAD

**Issue by mario-grgic** [microsoft/vscode#97822]
- VSCode Version:

```
Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z (6 days ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

```
- OS Version:
```
OS: Darwin x64 19.4.0
```

Steps to Reproduce:

If you use ```code``` command line launcher to casually explore files on the filesystem, VS Code will create a directory in 

```~/Library/Application\ Support/Code/User/workspaceStorage ```

for every open file. The directory contains at least two files and can be around 24 KB. 

Eventually, workspaceStorage directory can get polluted with way too many directories. 

Is there a better way to support this use case. If you work from command line and use ```code``` to open files, this is clearly not ideal.

Even an option passed with ```code``` (something like ```--no-workspace-storage```) would suffice to prevent writing these settings would be an improvement.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Currently not, but you can always pass `--user-data-dir <path>` to control where these files should go and as such could point to the temp directory.

This may also be helpful: https://code.visualstudio.com/docs/editor/portable
