### ISSUE TITLE
Linux save as root: cannot open temp file

### ISSUE THREAD

**Issue by cropinghigh** [microsoft/vscode#97827]
- VSCode Version: 1.44.2 from official repositories
- OS Version: Manjaro Linux 64-bit, all packets up to date

Steps to Reproduce:

1. Open any root-owned file with VS code as user(like config file)
2. Edit it
3. Try to save
4. Get message "Failed to save 'FILENAME': Insufficient permissions. Select 'Retry as Sudo' to retry as superuser."
5. Click "Retry as Sudo"
6. Enter sudo password
7. Get "Failed to save 'FILENAME': Command failed: cd "/home/USERNAME"; "/usr/bin/pkexec" --disable-internal-agent /bin/bash -c "echo SUDOPROMPT; \"/usr/bin/code\" --file-write \"/tmp/code-elevated-geaxtw\" \"/etc/FILENAME\""
Error using --file-write: EACCES: permission denied, open '/tmp/code-elevated-geaxtw'"

Does this issue occur when all extensions are disabled?: Yes

By running this command manually in terminal, same error.

> ls -lah /tmp/code-elevated-geaxtw 

output:

-rw-r--r-- 1 USERNAME USERNAME 587 may 14 19:13 /tmp/code-elevated-geaxtw

**Comment by cropinghigh** [comment]
Also: 
If i click Retry as Sudo, then keep password window, open terminal, chown file from /tmp/code-elevated-***** to user root : group root, then manually execute command in terminal, it saves file

**Comment by bpasero** [comment]
We are using https://github.com/jorangreef/sudo-prompt as library for this. @jorangreef have you seen such an issue before? I think this is `sudo-prompt` trying to access a temp file.

**Comment by jorangreef** [comment]
Sorry @bpasero I haven't.

**Comment by bpasero** [comment]
@jorangreef I assume that `/tmp/code-elevated-geaxtw` is something `sudo-prompt` generates to then call as `sudo`? And it basically contains whatever I instruct `sudo-prompt` to execute?

@cropinghigh any clue why this file cannot be accessed? Are you using multiple accounts on the same box?

**Comment by jorangreef** [comment]
> I assume that /tmp/code-elevated-geaxtw is something sudo-prompt generates to then call as sudo?

@bpasero, no, that's not a file created by sudo-prompt.

**Comment by bpasero** [comment]
@jorangreef oh sorry, my bad, this is something VSCode does!

@cropinghigh it looks like VSCode cannot write to tmp dir, that is not something we can easily recover from, can you check permissions on your OS?

**Comment by cropinghigh** [comment]
VSCode excellently writes to /tmp/code-elevated-geaxtw, and can read there, and in my problem it runs as root by pkexec, but it want to check file owner:group, and because of file written by name of user, not root, and /usr/bin/code --write-file runned as root, it thinks file is not own by user, and throws read error. I think issue is in vscode save part, that checks ownership of temp file on save, because if i chown file to root:root, it saves it. I think checking file ownership on reading temp file should be removed, because if user does not have permissions to this file, OS block reading file, and second check is not needed.

**Comment by bpasero** [comment]
@cropinghigh this is the first time I hear about such an issue, but your analysis seems correct, VSCode writes this file as the original user and then a sudo instance of VSCode tries to read from that file to write it to the target. This is our way of transferring the data that needs to be written to the target because the data is something you write in the editor and does not exist anywhere yet. 

I am open for suggestions how to fix this, the code is here:

https://github.com/microsoft/vscode/blob/1fc148b25413ec45e4eb6ce13fa44c0eb813ea4a/src/vs/code/node/cli.ts#L78-L113

And the exception very likely happens here:

https://github.com/microsoft/vscode/blob/1fc148b25413ec45e4eb6ce13fa44c0eb813ea4a/src/vs/code/node/cli.ts#L92
