### ISSUE TITLE
April 2020 Recovery Endgame

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#97826]
- [x] Create a milestone `<Month> <Year> Recovery` @connor4312
- [x] Bump the version number @connor4312
- [x] [🔖candidate issues](https://github.com/issues?q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+milestone%3A%22April+2020+Recovery%22+)
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `master` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `master`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch @connor4312
- [x] Issues are verified on `stable` build and the `verified` label is added @connor4312
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch @connor4312
- [x] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test) stable bits  (⚠️ MUST run with `--stable-build` argument ⚠️ )
  - [x] Windows - @JacksonKearl 
  - [x] OS X - @rebornix  
  - [x] Linux - @connor4312
- [x] Sanity check of installable bits
  - [x] Windows 32 bit - @connor4312
    - [x] signed installer 32-bit
    - [x] signed user installer 32-bit
    - [x] zip 32-bit
  - [x] Windows 64 bit - @JacksonKearl 
    - [x] signed installer 64-bit
    - [x] signed user installer 64-bit
    - [x] zip 64-bit
  - [x] OS X - @roblourens 
  - [x] Linux
    - [x] deb package 64-bit - @connor4312
    - [x] rpm package 64-bit - @RMacfarlane 
    - [x] archives - @RMacfarlane 
    - [x] snap (`sudo snap install --classic --dangerous <file>.snap`) - @connor4312
  - [x] Server ([instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers))
    - [x] Linux - @connor4312
    - [x] macOS - @connor4312
    - [x] WIndows - @roblourens 
- [x] Publish website **@gregvanl**
- [x] Publish stable build @connor4312
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z`

**Comment by gjsjohnmurray** [comment]
@connor4312 the candidate issues link is bad. It should be looking for `milestone:"April 2020 Recovery"` but is actually going for `milestone:"May 2020 Recovery 2"`

**Comment by connor4312** [comment]
fixed :)

**Comment by EliotArmstrong** [comment]
fixed
