### ISSUE TITLE
Perform search automatically when running search.action.openNewEditor

### ISSUE THREAD

**Issue by dufferzafar** [microsoft/vscode#97823]
I'm using the functionality added in #95582 to build a "saved search" for all my TODOs, like so:

```json
    {
        "key": "alt+k alt+t",
        "command": "search.action.openNewEditor",
        "args": {
            "query": "(TODO|NOTE|BUG):",
            "regexp": true
        },
        "when": "editorTextFocus"
    }
```

Now, this launches the search editor with the input box focused and the "query" selected. 
After which I have to press enter to actually run the search.
And then, click the search results part to focus that area so I can use Arrow Keys / Page Up/Down to browse the results.

I want two little improvements - perform the search automatically - don't wait for me to press Enter.

And, when you've already run the search, just focus the search results for me - avoiding the need to click that area.

I suppose they could implemented as other optional arguments? `performSearch: true` and `focusResults: true`.

/cc: @JacksonKearl

**Comment by JacksonKearl** [comment]
> I suppose they could implemented as other optional arguments? performSearch: true and focusResults: true.

This sounds reasonable.

**Comment by ArturoDent** [comment]
I agree that the autorun feature would be great.  In the meantime, as a workaround, you could incorporate a macro like

    "multiCommand.commands": [

      {
        "command": "multiCommand.runSearchEditorwithArguments",
        "interval": 200,   // needs a small delay so results are loaded before focusing them
        "sequence": [
          {
            "command": "search.action.openNewEditor",
            "args": {
              "query": "(TODO|NOTE|BUG):",
              "regexp": true,
              "includes": "${fileDirname}",
              "showIncludesExcludes": true,
              "contextLines": 3,
            }
          },
          "rerunSearchEditorSearch",                    // runs the search
          "search.action.focusNextSearchResult"  // focus first result
        ]
      }
    ]

but hopefully an autorun feature makes this moot.
