### ISSUE TITLE
Custom renderers do not render output when loading an existing Notebook

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#97838]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.Register a custom renderer for `text/html` and custom pre-load script file.
2.Run a cell with `text/html` output will be rendered using custom renderer
3. Open a notebook with above cell information.
4. The preload script is not loaded, hence custom rendering fails.
5. Running the cell results in preload script being loaded

Does this issue occur when all extensions are disabled?: N/A

@rebornix /cc

**Comment by rebornix** [comment]
Already fixed in master and will be shipped soon.

**Comment by JacksonKearl** [comment]
@DonJayamanne can you confirm this is working now?

Otherwise, @rebornix  how can I verify this?

**Comment by connor4312** [comment]
I know how to verify this
