### ISSUE TITLE
Top level suggestions for tsconfig schema do not make sesne

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#9783]
Refs: #9744

insiders, os x

1. Have a myjson.json with the following content
```json
| trigger intelli-sense here
{
"$schema": "http://json.schemastore.org/tsconfig"
}
```
2. trigger intelisense outside of the object, notice bogu proposals
3. I am only getting this if I choose the tsconfig schema so the problem might be with the schema and not with us, but still creating issue so you are aware

![screen shot 2016-07-26 at 15 18 09](https://cloud.githubusercontent.com/assets/1926584/17139354/5f3974f0-5344-11e6-883d-71648f1930b0.png)

**Comment by aeschli** [comment]
fixed. Now you get just text proposals... :-(
