### ISSUE TITLE
auto-renaming tags notifier popping up multiple times

### ISSUE THREAD

**Issue by 97krihop** [microsoft/vscode#97833]
a notifier is asking every time a open a HTML asking to activate 
"VS Code now has built-in support for auto-renaming tags. Do you want to enable it?" even with i have activated it.

**Comment by aeschli** [comment]
To reproduce
- fresh user data store
- `editor.renameOnType` is disabled (which is the default)
- install auto rename tag extension (`formulahendry.auto-rename-tag`)
- switch between html files
- popup shows: `VS Code now has built-in support for auto-renaming tags...`
- continue to switch between html files
- versify that no additional popup are showing
