### ISSUE TITLE
VScode folder pane shows "Folder contains emphasized items" with marking the folder as error (red in color) but no errors on files/code

### ISSUE THREAD

**Issue by aravindk777** [microsoft/vscode#97836]
- VSCode Version: 1.45.0
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Create a folder, say "models"
2. Create a file with hyphen in it. in my case, i wanted to create a model class file in angular with the camelcasing. 
3. commit/push to git
4. remove few files and add few others like the above naming format. 

`ng g class doc-status --type model`

so i would have my class name as 
```
export class DocStatus {
}
```
And then, after i rename them back to normal class names in typescript and change, i was able to get rid of the red error like marker on that folder. 

**History**:
I had few files and removed them later. And added few more additional files. Since then, i noticed this behavior. Renaming to normal and again restoring back, removes the folder view from error like red colored to normal folder view (yellow for modified).

**Concern:**
Why is this inconsistency? is this due to pending git commit/push? Ideally it should detect the local changes and react to the valid behavior. as there is no error(s) on my code/files, i would not like to see that folder colored in red if its all the pending git commit/push to reflect. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
I'm not sure if this is a problem with the decorations in the explorer or with the diagnostics, I'm confused.

**Comment by jrieken** [comment]
I am confused by your step, something simpler to reproduce would be helpful. 

Anyways, when this happens what does the Problems panel show (F1 > Focus on problems view)? Are there error or is it empty?

**Comment by aravindk777** [comment]
Hi,
The steps could be as follows. 

1. create a simple angular project (or any other for that trial)
2. Ensure to **enable git source** of your choice to this project. 
3. Add or restructure the folders and files for the project. 
4. In my case, i added a folder called "models", added "ng g class Users --type model". It will by default create the model and spec file. 
5. commit the changes to the git, (no need to push to origin).
6. Now, go back to the models folder, remove the spec file.
7. you can see the the models folder turns to red color as if there's some error. 

Please note - 
1. there would not be any error or note in the problems tab. 
2. I have disabled all the extensions in VS, restarted and then attempted the above steps. 

### **Screen shots:**
![image](https://user-images.githubusercontent.com/40478917/82160601-927c6980-9864-11ea-8f0a-69e4c9e672be.png)

**pending git changes shows the deleted file:**
![image](https://user-images.githubusercontent.com/40478917/82160616-ade77480-9864-11ea-9c90-029758ebe43a.png)

**problems tab:**
![image](https://user-images.githubusercontent.com/40478917/82160629-bdff5400-9864-11ea-86e0-a0b787d11450.png)

**Output tab:**
![image](https://user-images.githubusercontent.com/40478917/82160637-c6578f00-9864-11ea-88f2-d6327c759853.png)

The folder view and hovering over shows the below:
![image](https://user-images.githubusercontent.com/40478917/82160694-1f272780-9865-11ea-9396-24f50e7ea14f.png)

I hope this helps. 

Other than this msg on hovering over, saying "contains emphasized items", i dont see any reason or details for the folder to look like some error. I am assuming that the difference is only the uncommitted changes of the deleted file. 

Is this is detected as some error by default? Why would vs code would determine this as some concerned item? I havent built or ran any command indeed.

**Comment by jrieken** [comment]
Before I am diving into angular, pls try this

* F1 > Log Level > Trace
* F1 > Show Log > Windows
* Reproduce the issue
* attach the log file or all messages that start with `DecorationsService#getDecoration#getOrRetrieve`
* share the folder name in which you have wrong highlights.

**Comment by aravindk777** [comment]
> [2020-05-19 11:04:52.911] [renderer4] [trace] telemetry/activityBarAction {"viewletId":"workbench.view.explorer","action":"show"}
> **[2020-05-19 11:04:52.975] [renderer4] [trace] DecorationsService#getDecoration#getOrRetrieve vscode.git {"weight":3,"bubble":false,"color":"gitDecoration.ignoredResourceForeground","tooltip":null,"letter":null} false {"$mid":1,"fsPath":"c:\\code\\Fun\\AngularDCore\\ClientApp.Angular\\ClientApp\\dist","_sep":1,"external":"file:///c%3A/code/Fun/AngularDCore/ClientApp.Angular/ClientApp/dist","path":"/c:/code/Fun/AngularDCore/ClientApp.Angular/ClientApp/dist","scheme":"file"}**
> **[2020-05-19 11:04:52.980] [renderer4] [trace] DecorationsService#getDecoration#getOrRetrieve vscode.git {"weight":3,"bubble":false,"color":"gitDecoration.ignoredResourceForeground","tooltip":null,"letter":null} false {"$mid":1,"fsPath":"c:\\code\\Fun\\AngularDCore\\ClientApp.Angular\\ClientApp\\node_modules","_sep":1,"external":"file:///c%3A/code/Fun/AngularDCore/ClientApp.Angular/ClientApp/node_modules","path":"/c:/code/Fun/AngularDCore/ClientApp.Angular/ClientApp/node_modules","scheme":"file"}**
> **[2020-05-19 11:04:52.980] [renderer4] [trace] DecorationsService#getDecoration#getOrRetrieve vscode.git {"weight":3,"bubble":false,"color":"gitDecoration.ignoredResourceForeground","tooltip":null,"letter":null} false {"$mid":1,"fsPath":"c:\\code\\Fun\\AngularDCore\\ClientApp.Angular\\ClientApp\\out-tsc","_sep":1,"external":"file:///c%3A/code/Fun/AngularDCore/ClientApp.Angular/ClientApp/out-tsc","path":"/c:/code/Fun/AngularDCore/ClientApp.Angular/ClientApp/out-tsc","scheme":"file"}**
> [2020-05-19 11:05:08.639] [renderer4] [trace] CommandService#executeCommand moveFileToTrash
> [2020-05-19 11:05:08.640] [renderer4] [trace] telemetry/workbenchActionExecuted {"id":"moveFileToTrash","from":"contextMenu"}
> [2020-05-19 11:05:08.643] [renderer4] [trace] DialogService#confirm Are you sure you want to delete 'health-check.model.spec.ts'?
> [2020-05-19 11:05:11.637] [renderer4] [trace] [text file model] load() - enter file:///c:/code/Fun/AngularDCore/ClientApp.Angular/ClientApp/src/app/root/app.component.html
> [2020-05-19 11:05:11.909] [renderer4] [trace] [File Watcher (C#)] [DELETED] c:\code\Fun\AngularDCore\ClientApp.Angular\ClientApp\src\models\health-check.model.spec.ts
> [2020-05-19 11:05:11.998] [renderer4] [trace] [File Watcher (C#)]  >> normalized [DELETED] c:\code\Fun\AngularDCore\ClientApp.Angular\ClientApp\src\models\health-check.model.spec.ts
> [2020-05-19 11:05:13.651] [renderer4] [trace] [File Watcher (C#)] [CHANGED] c:\code\Fun\AngularDCore\ClientApp.Angular\ClientApp\src\models
> [2020-05-19 11:05:13.717] [renderer4] [trace] [File Watcher (C#)]  >> normalized [CHANGED] c:\code\Fun\AngularDCore\ClientApp.Angular\ClientApp\src\models
> **[2020-05-19 11:05:17.051] [renderer4] [trace] DecorationsService#getDecoration#getOrRetrieve vscode.git {"weight":1,"bubble":true,"color":"gitDecoration.deletedResourceForeground","tooltip":"Deleted","letter":"D"} true {"$mid":1,"fsPath":"c:\\code\\Fun\\AngularDCore\\ClientApp.Angular\\ClientApp\\src","_sep":1,"external":"file:///c%3A/code/Fun/AngularDCore/ClientApp.Angular/ClientApp/src","path":"/c:/code/Fun/AngularDCore/ClientApp.Angular/ClientApp/src","scheme":"file"}**
> **[2020-05-19 11:05:17.056] [renderer4] [trace] DecorationsService#getDecoration#getOrRetrieve vscode.git {"weight":1,"bubble":true,"color":"gitDecoration.deletedResourceForeground","tooltip":"Deleted","letter":"D"} true {"$mid":1,"fsPath":"c:\\code\\Fun\\AngularDCore\\ClientApp.Angular\\ClientApp\\src\\models","_sep":1,"external":"file:///c%3A/code/Fun/AngularDCore/ClientApp.Angular/ClientApp/src/models","path":"/c:/code/Fun/AngularDCore/ClientApp.Angular/ClientApp/src/models","scheme":"file"}**
> **[2020-05-19 11:05:17.057] [renderer4] [trace] DecorationsService#getDecoration#getOrRetrieve vscode.git {"weight":1,"bubble":true,"color":"gitDecoration.deletedResourceForeground","tooltip":"Deleted","letter":"D"} true {"$mid":1,"fsPath":"c:\\code\\Fun\\AngularDCore\\ClientApp.Angular\\ClientApp\\src","_sep":1,"external":"file:///c%3A/code/Fun/AngularDCore/ClientApp.Angular/ClientApp/src","path":"/c:/code/Fun/AngularDCore/ClientApp.Angular/ClientApp/src","scheme":"file"}**
> [2020-05-19 11:05:17.371] [renderer4] [trace] MainThreadTimeline#emitChangeEvent: id=git-history, uri=undefined
> **[2020-05-19 11:05:32.846] [renderer4] [trace] DecorationsService#getDecoration#getOrRetrieve vscode.git {"weight":1,"bubble":true,"color":"gitDecoration.deletedResourceForeground","tooltip":"Deleted","letter":"D"} true {"$mid":1,"fsPath":"c:\\code\\Fun\\AngularDCore\\ClientApp.Angular\\ClientApp\\src\\models","_sep":1,"external":"file:///c%3A/code/Fun/AngularDCore/ClientApp.Angular/ClientApp/src/models","path":"/c:/code/Fun/AngularDCore/ClientApp.Angular/ClientApp/src/models","scheme":"file"}**
> **[2020-05-19 11:05:39.027] [renderer4] [trace] DecorationsService#getDecoration#getOrRetrieve vscode.git {"weight":1,"bubble":true,"color":"gitDecoration.deletedResourceForeground","tooltip":"Deleted","letter":"D"} true {"$mid":1,"fsPath":"c:\\code\\Fun\\AngularDCore\\ClientApp.Angular\\ClientApp\\src\\models","_sep":1,"external":"file:///c%3A/code/Fun/AngularDCore/ClientApp.Angular/ClientApp/src/models","path":"/c:/code/Fun/AngularDCore/ClientApp.Angular/ClientApp/src/models","scheme":"file"}**
> [2020-05-19 11:05:39.041] [renderer4] [trace] telemetry/workbenchActionExecuted {"id":"workbench.files.openFile","from":"explorer"}
> [2020-05-19 11:05:39.042] [renderer4] [trace] telemetry/editorOpened {"typeId":"workbench.editors.files.fileEditorInput","resource":{"mimeType":"text/x-typescript, text/plain","scheme":"file","ext":".ts","path":1820148836}}
> [2020-05-19 11:05:39.043] [renderer4] [trace] telemetry/workbenchActionExecuted {"id":"workbench.files.openFile","from":"explorer"}

**Comment by aravindk777** [comment]
I'll leave to the experts to comment on, but i think the color coding of the folder is just showing us that, there is something deleted content out there for git (like yellow for modified / M). Am i right?

**Comment by jrieken** [comment]
Thanks. This is helpful!

**Comment by jrieken** [comment]
It seems that deleting a file shouldn't bubble up to parent folders because it doesn't explain itself well enough

**Comment by jrieken** [comment]
using these steps (also to verify)

* have a folder `foo`
* create two files `bar` and `delme`
* commit changes so that the git viewlet is clean
* in the terminal (**!**) type `rm foo/delme`
* :bug: the foo-folder shows that it has emphasised items

**Comment by aravindk777** [comment]
I tested on the insiders version and it works as expected. Thanks for the quick fix. :) A great tool and a great team! 👍
