### ISSUE TITLE
Cannot run extension tests when editing remotely.

### ISSUE THREAD

**Issue by ericsnowcurrently** [microsoft/vscode#97844]
- VSCode Version: 1.45.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. in VS Code connect to a remote host using one of the "remote" extensions (e.g. SSH)
2. on that host clone the https://github.com/microsoft/vscode-python repo
3. open that folder
4. in the "Run" side bar select the `Tests (Single Workspace, VS Code, *.test.ts)` config
5. run it

At this point the "Extension Development Host" starts up and its window opens.  In that window there are 2 message boxes in the bottom right.  One says `All installed extensions are temporarily disabled.`, along with something about reloading (which doesn't work, see #94532).  The other says `Extension 'Remote - SSH' is required to open the remote window.` (with an offer to install & reload, which doesn't work).  In a green area in the bottom left corner, where it normally shows the transport and remote config (e.g. "SSH: some-host"), it shows "Disconnected from ssh-remote+some-host" instead.

I used to be able to run these tests remotely like this while working on the Python extension.  I'm not sure when I last did so, but it's been a while (maybe mid-2019).  From #81653 it looks like there were some related changes in September 2019, though I'm not sure if those are the cause.  In case it matters, the Python extension's tests use "vscode-test".

**Comment by ericsnowcurrently** [comment]
The commits mentioned in #81653:

* https://github.com/microsoft/vscode/commit/1c6938e342a71e43a74eb3d017d02f76575b4128
* https://github.com/microsoft/vscode/commit/fb10f85b4c20038c2634c368d2c2d57d08d756ce

**Comment by weinand** [comment]
The debug configuration disables all extension by passing the "--disable-extensions" argument. This will disable the "Remote - SSH" extension which is required when running the tests remotely. 
If I disable the "--disable-extensions" argument, the tests seem to run fine.

**Comment by ericsnowcurrently** [comment]
> If I disable the "--disable-extensions" argument, the tests seem to run fine.

Gah!  I'm not sure how I did not see that in the extension's launch.json.  I thought it was something in VS Code.  Sorry for the noise.

**Comment by weinand** [comment]
@ericsnowcurrently your issue wasn't "noise"...
It was actually providing helpful insights to make me file this issue: https://github.com/microsoft/vscode-remote-release/issues/3016

**Comment by ericsnowcurrently** [comment]
@weinand, oh good. 🙂
