### ISSUE TITLE
Powershell 7.0 double spaced

### ISSUE THREAD

**Issue by mottykohn** [microsoft/vscode#97847]
Issue Type: <b>Bug</b>

There is a space between each letter in powershell 7.0 and cursor is misplaced

![image](https://user-images.githubusercontent.com/17966568/81983044-bb9cc000-9600-11ea-828d-4cb95851ea9c.png)
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (2.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.901.7
alignment|ann|0.3.0
githistory|don|0.6.5
xml|Dot|2.5.0
gc-excelviewer|Gra|2.1.34
vscode-awk-hint|han|0.0.2
live-html-previewer|hdg|0.3.0
search-editor-apply-changes|jak|0.1.1
AWK|lug|0.0.2
rainbow-csv|mec|1.7.0
Angular-BeastCode|Mik|8.1.2
mssql|ms-|1.9.0
sqlops-debug|ms-|1.3.0
python|ms-|2020.5.78807
remote-wsl|ms-|0.44.2
azure-account|ms-|0.8.11
powershell|ms-|2020.4.0
vsliveshare|ms-|1.0.2106
debugger-for-chrome|msj|4.12.6
angular2-inline|nat|0.0.17
ng-refactor|ng-|0.1.0
vscode-versionlens|pfl|0.27.0
csharp2ts|raf|0.0.24
vscode-yaml|red|0.8.0
loopback-json-schemas|seq|1.0.0
vscode-scss-formatter|sib|2.0.1
quokka-vscode|Wal|1.0.289

</details>

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/needsMoreInfo

**Comment by mottykohn** [comment]
I cannot reproduce anymore my own issue. If it happens again I'll reopen
