### ISSUE TITLE
VSC Live server icon missing from status bar

### ISSUE THREAD

**Issue by VinceCaruso** [microsoft/vscode#97840]
- VSCode Version: 1.45.0
- OS Version: Windows 10 (version1903)

Steps to Reproduce:

1. open vsc
2.open folder
3. No 'live server' icon appears on status bar
4. uninstall extension
5. reinstall extension
6. unstall VSC
7 reinstall VSC
8. reinstall extension
9. Additionally the alt O and alt L, dont work either. 

Does this issue occur when all extensions are disabled?: Yes/No
see above

**Comment by alexdima** [comment]
@VinceCaruso Can you please create an issue directly against the extension at https://github.com/ritwickdey/vscode-live-server/issues .
