### ISSUE TITLE
Allow trailing commas in settings JSON when viewed from git stage/index

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#97843]
In #26830, you guys enabled accepting trailing commas for VS Code's own settings JSON files. Unfortunately, this exception does not apply when, let's say, viewing a diff between a JSON file and the last version committed to a git repo:
![image](https://user-images.githubusercontent.com/12128514/81976156-64aae100-9628-11ea-989b-5d55f25ea4ee.png)
Note the "(git)".

I feel VS Code should know, and could know, that these are its own settings JSON files, too, and allow trailing commas.

**Comment by bersbersbers** [comment]
@vscodebot the linked feature request is different.

**Comment by sandy081** [comment]
settings.json is configured to be a `jsonc` file and hence I think trailing commas are allowed. Not sure how to enable the git version of the file?

@aeschli assigning to you, I assume this has to be configured in git extension is it?

**Comment by bersbersbers** [comment]
@sandy081 I do not have any git extension installed, if that's what you mean.

I enable "the git version of the file" by adding the file to a git repo, committing, making changes and then opening the diff from the "Source Control" thing - just as one example.

**Comment by sandy081** [comment]
@bersbersbers `git` extension is installed by default.

**Comment by bersbersbers** [comment]
Thank you, this is working fine now!
