### ISSUE TITLE
Update still fails with "There was an error while marking a file for deletion"

### ISSUE THREAD

**Issue by jmaynard** [microsoft/vscode#97846]
Issue Type: <b>Bug</b>

I'm still having the same failure to install updates from within VSCode. I can delete Code.exe from File Explorer with no issues. There are no VSCode processes running. This has been a problem for me for the last several releases, and with VSCode's at-least-monthly cadence (a good thing, don't get me wrong), this means it's a constant annoyance. This worked for the first few times ince I installed VSCode on this machine in January, but nto any more.

It would be very nice if the message would at least show what file is having the problem so we could narrow down the issue. The logs contain exactly no useful information, simply that the install failed.

Every time, I have to manually download the installer and run it with VSCode shut down, and that always works. I've looked at issues 80899 and 47841, and it looks like this has been a problem for going on two years with no resolution or any hint of any way to collect meaningful information. Can we at least get full diagnostics from the failure so we can see about nailing this problem to the wall?

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363
Fetching remote diagnostics for 'ssh-remote+11.4.2.21' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD PRO A10-8730B R5, 10 COMPUTE CORES 4C+6G    (4 x 2396)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.43GB (2.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'ssh-remote+11.4.2.21' timed out.
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.1.3
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
vscode-git-branch-sidebar|mia|1.2.0
azure-account|ms-|0.8.11
cpptools|ms-|0.28.0
sqltools|mtx|0.21.7

</details>

**Comment by joaomoreno** [comment]
Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by jmaynard** [comment]
I've turned off the option. Went to apply the update, and VSCode exited, applied the update, and started again, all by itself.

Might be worth making it obvious that this is the first thing to do if trouble is encountered while applying an update in the background.

**Comment by joaomoreno** [comment]
Yes, we're working on that. Closing the issue.
