### ISSUE TITLE
Multi-root: Allow disabling tests (discovery/prompts/...) for a root

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#97842]
Multi-root workspaces are motivated like this:
> For example, you might have a repository with a product's documentation which you like to keep current when you update the product source code.

Exactly my use case. However, in such a multi-root workspace, I am now often confronted with the choice of one of the two folders for various operations. This is mostly fine, but really useless when it comes to testing: my documentation repo does not offer any testing whatsoever. So it's unnecessary work for me to select the product repo each time I discover tests, or run all tests, etc.

Maybe I have missed it, but a setting to disable all test functionality would be highly appreciated. I would then put this setting into the `.vscode/settings.json` in the documentation repo and be very happy. (If this already exists, I'd be even happier, but I haven't found it yet.)

**Comment by alexdima** [comment]
@bersbersbers VS Code does not ship any test functionality by default, so I believe you wish to ask for this "ignore" support from an extension that you are using. What extensions do you use? (I could try to find out their repository information and point you to it)

**Comment by bersbersbers** [comment]
Oh, you mean the "Test Explorer" is exclusive to the Python extension then? Interesting - I will refile with them. Thanks!
