### ISSUE TITLE
Markdown syntax highlighting not support alternative header styles

### ISSUE THREAD

**Issue by tschuegge** [Microsoft/vscode#9784]
![readme_md_-_app-zeiterfassung-multi-user](https://cloud.githubusercontent.com/assets/11212275/17139252/fe0a58ac-5343-11e6-8cde-883c104324e5.jpg)

H1 and H2 are not highlighted. The preview is fine.

Tested on VS Code 1.3.1 on OS X 10.11.6

**Comment by eklavyamirani** [comment]
I wanna give this one a try. Here is what I have achieved so far.
![wip alternate text highlight in md](https://cloud.githubusercontent.com/assets/1318529/17513688/1a433774-5e4c-11e6-8814-c61797c3300f.png)

**Comment by eklavyamirani** [comment]
@kieferrm Couple of updates on this:

1. trying to highlight both lines at the same time, the way I was trying above doesn't look practical. It automatically highlights the current line assuming a match of the begin, until it finds a non matching end/while (Basically the line highlights, and if the next line isn't a '-{3,}' then the syntax goes back to normal mode.

2. The alt heading 2 syntax (just the -{3,} part) is conflicting with the rule meta.separator.markdown, which takes precedence and hence the issue.

Would it be a better option to fix this conflict instead?

**Comment by tschuegge** [comment]
It doesn't work with 1.9.0
![test_md](https://cloud.githubusercontent.com/assets/11212275/22589138/0e2992aa-ea09-11e6-9d24-c0853b8b8bed.png)

**Comment by eklavyamirani** [comment]
@tschuegge I believe this is as designed. Getting the TM grammar to highlight both the lines is tricky. If you refer to my previous comment, the first point:

> 1. trying to highlight both lines at the same time, the way I was trying above doesn't look practical. It automatically highlights the current line assuming a match of the begin, until it finds a non matching end/while (Basically the line highlights, and if the next line isn't a '-{3,}' then the syntax goes back to normal mode.)

This would be confusing for the user. In simple terms, it means that as soon as a user starts typing, the line highlights, and goes back to normal syntax if the next line is neither of the alternate H1/H2 (---/===) text.

@kieferrm What do you think?

**Comment by tschuegge** [comment]
Is it possible to let the line white and if a line starts with --- oder ===, then this one and the previous one switch to blue?
That is the same behavior like in other editors.
