### ISSUE TITLE
Mouse right-click create file/folder does not claim window focus

### ISSUE THREAD

**Issue by Adam-Langley** [microsoft/vscode#97856]
Issue Type: <b>Bug</b>

Set window focus to any _other_ window (Safari?), right click on a folder in VS Code and choose to create a new folder.
Start typing a name for the folder - your keystrokes are still sent to the _other_ window.

Expected behavior:
As soon as VS Code creates a text-entry for the new folder, it should grab window focus so the keystrokes will be captured.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|10%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.10.1
flutter|Dar|3.10.1
vscode-icons|vsc|10.1.1

</details>

**Comment by isidorn** [comment]
https://github.com/microsoft/vscode/issues/97408
