### ISSUE TITLE
Format on type is not working

### ISSUE THREAD

**Issue by ronakg** [microsoft/vscode#97853]
- VSCode Version: 1.45.1
- OS Version: macOS 10.15.4 (19E287)

Steps to Reproduce:

1. Type out following lines in a python file

```python
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('-a', '--abc', nargs=5, required=True, default=5, help='some help text that is very long to trigger reformat')
```

The last line should get reformatted with typing, but it doesn't.

If I select the line and run `Format Selection` from command palette, it looks like following -

```python
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('-a', '--abc', nargs=5, required=True, default=5,
                    help='some help text that is very long to trigger reformat')
```

Does this issue occur when all extensions are disabled?: Yes*

It's difficult to reproduce this without extensions because a formatter must be available for this. I disabled everything except the Python language pack to reproduce this.

**Comment by alexdima** [comment]
Please create an issue directly against the extension at https://github.com/Microsoft/vscode-python/issues . The authors of the extension will investigate and determine if this is caused by vscode and can reach out to us in that case.
