### ISSUE TITLE
Perf regression: force reflow in markdown cell

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#97859]
Issue Type: <b>Bug</b>

Not sure which line of code but it triggers forced reflow 100% the time when a markdown cell is opened.

<img width="2061" alt="image" src="https://user-images.githubusercontent.com/876920/82003819-31f7ed00-9616-11ea-8870-e5f106198157.png">

VS Code version: Code - Insiders 1.46.0-insider (e1d8f5155c0db5ffdc130c9aa0f14efac02dfdfb, 2020-05-13T20:32:52.338Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (0.70GB free)|
|Process Argv|-psn_0_4404275|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
gitlens|eam|10.2.1
tsl-problem-matcher|eam|0.1.1
vscode-pull-request-github-insiders|Git|2020.5.19650
vscode-docker|ms-|1.2.0
vscode-language-pack-zh-hans|MS-|1.45.1
remote-containers|ms-|0.117.1
remote-ssh-edit-nightly|ms-|2020.5.19620
remote-ssh-nightly|ms-|2020.5.19620
js-debug-nightly|ms-|2020.5.617
powershell|ms-|2020.4.0
vscode-github-issue-notebooks|ms-|0.0.22
vsliveshare|ms-|1.0.2169
debugger-for-chrome|msj|4.12.6
kuskus-extensions-pack|ros|1.0.1
kuskus-kusto-language-server|ros|1.0.1
kuskus-kusto-syntax-highlighting|ros|1.1.8
sourcekit-lsp|unp|0.0.1

(5 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
We can't avoid this as long as we are using the virtualized list.

**Comment by roblourens** [comment]
I've been wondering about prerendering markdown somewhere to improve this. Especially when you have flickering as images load in
