### ISSUE TITLE
[vscode insiders]fold level 1

### ISSUE THREAD

**Issue by yyjazsf** [microsoft/vscode#97855]
Issue Type: <b>Bug</b>

- open a typescript project
- open a .ts file
- press command + k, command + 1, does't work

btw: work in vscode(same project and file)

result use command k,command + 1:
<img width="288" alt="WX20200515-082029@2x" src="https://user-images.githubusercontent.com/2438224/81998552-63f46800-9685-11ea-90ba-681271826e69.png">

result use command k,command + 2:(open an new editor area)
![image](https://user-images.githubusercontent.com/2438224/81998403-fba58680-9684-11ea-9404-2c9852b2a55d.png)

VS Code version: Code - Insiders 1.46.0-insider (e1d8f5155c0db5ffdc130c9aa0f14efac02dfdfb, 2020-05-13T20:32:52.338Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-3223 CPU @ 3.50GHz (16 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (8.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|11.2.0
vscode-eclipse-keybindings|alp|0.12.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
systemd-unit-file|coo|1.0.6
dart-code|Dar|3.10.1
vscode-markdownlint|Dav|0.35.1
vscode-eslint|dba|2.1.5
vscode-stylesheet-formatter|dba|0.2.0
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.14.5
vscode-element-helper|Ele|0.5.6
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|4.7.0
auto-close-tag|for|0.5.7
shell-format|fox|7.0.1
vscode-pull-request-github|Git|0.16.0
gc-excelviewer|Gra|2.1.34
githd|hui|2.2.4
vscode-pigments|jas|2.0.0
json-escaper|jos|1.1.0
vscode-colorize|kam|0.8.16
node-module-intellisense|lei|1.5.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.2.0
debugger-for-chrome|msj|4.12.6
vetur|oct|0.24.0
material-icon-theme|PKi|4.1.0
java|red|0.61.0
vscode-xml|red|0.11.0
vscode-yaml|red|0.8.0
code-settings-sync|Sha|3.4.3
vscode-nginx|sha|0.6.0
svg-preview|Sim|2.8.3
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.0
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.4
vscode-nginx|wil|0.7.2
JavaScriptSnippets|xab|1.8.0
ddx|yyj|1.0.2

(3 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
@yyjazsf 
Which commands are bound to the desired key combination?

![keyboard-conflicts](https://cloud.githubusercontent.com/assets/5047891/25484174/38f5b004-2b59-11e7-994b-dfa96ef043ce.gif)

**Comment by yyjazsf** [comment]
control + k? macos use (command + k, command + 1)
![image](https://user-images.githubusercontent.com/2438224/82106353-f151be00-9752-11ea-9e9a-70151fe7d2ca.png)

**Comment by alexdima** [comment]
@yyjazsf The GIF I pasted is an example that I recorded 6 months ago on Windows. Can you please search in the keybindings not for "Fold" and not for "control+k", but for the keybinding that is problematic on your machine i.e. "cmd+k cmd+1" or "cmd+k cmd+2"

**Comment by yyjazsf** [comment]
![image](https://user-images.githubusercontent.com/2438224/82271280-ee9cd600-99a9-11ea-9156-2fe44f63cb80.png)
![image](https://user-images.githubusercontent.com/2438224/82271304-ffe5e280-99a9-11ea-9e10-99f10fd51a46.png)

**Comment by yyjazsf** [comment]
I disible all extensions, it does work, then I one by one enable, also work well. I can't reappear the bug.   thanks for you help. and sorry for wasting your time
