### ISSUE TITLE
Can't create a file in the root of a project if there are no files already there.

### ISSUE THREAD

**Issue by TheSmokingGnu** [Microsoft/vscode#9785]
- VSCode Version: 1.3.1
- OS Version: 10.9 Mac

Steps to Reproduce:

1. Add a new project
2. Add a folder
3. Select that folder
4. Try to add file in the root.

**Comment by kieferrm** [comment]
Works for me on MacOS with 1.3.1

![ts8ndghfct](https://cloud.githubusercontent.com/assets/4674940/17149955/69b5112c-5322-11e6-864e-f9d135d22d91.gif)
