### ISSUE TITLE
Overwrite cursor

### ISSUE THREAD

**Issue by rutherd313** [microsoft/vscode#97854]
Issue Type: <b>Feature Request</b>

As soon as visual studio code starts, my cursor is already at overwrite mode and it takes a century of carefully toggling the insert key at the right moment while typing a letter or number on the keyboard to render it back to a non-overwrite cursor. Did not have this issue in the past, just recently.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18362

**Comment by alexdima** [comment]
@rutherd313 Does this reproduce when disabling all extensions? I am asking because VS Code actually lacks an overwrite mode, it is one of those things that we never got around to implement in the editor.

**Comment by rutherd313** [comment]
Hi alexdima, I played around with the extensions and I found out that it was Vim (vscodevim) that was causing this issue.
