### ISSUE TITLE
Fix all quick fixes should not be marked as preferred

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#97866]
Issue Type: <b>Bug</b>

**Repro**

1. In a TS file:

```ts
export const _ = 1;

const a = 1;
const b = 2;
```

2. Put cursor on `a` and trigger auto fix 

**Bug**
Context menu is shown. This should instead just fix the single error and remove `a`

VS Code version: Code - Insiders 1.46.0-insider (e1d8f5155c0db5ffdc130c9aa0f14efac02dfdfb, 2020-05-13T20:32:52.338Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.13GB free)|
|Process Argv|-psn_0_59869461|
|Screen Reader|no|
|VM|11%|
</details>

**Comment by lramos15** [comment]
I still get the option to pick between a and b when triggering auto fix.

**Comment by mjbvz** [comment]
@lramos15 Are you selecting both lines? That is the expected behavior if your selection includes both `a` and `b`

However if I only have the cursor on `a`, auto fix does the correct thing for me

**Comment by lramos15** [comment]
I was executing the wrong keyboard shortcut 🤦. This works as expected.
