### ISSUE TITLE
Starting rg.exe of vscode(v1.45.1) takes up a lot of CPU

### ISSUE THREAD

**Issue by guchengjie** [microsoft/vscode#97860]
Issue Type: <b>Performance Issue</b>

Vscode is updated to version 1.45.1, and rg.exe starts to occupy a lot of CPU after startup

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.88GB (15.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    82	 23908	code main
    0	   205	  3600	   gpu-process
    0	    14	  8332	   electron-crash-reporter
    3	    76	 10716	   shared-process
    1	    74	 18200	   window (问题报告程序)
    0	    26	 19516	   utility
    0	   208	 21272	   window (sheet.js - 无标题 (工作区) - Visual Studio Code)
    0	    43	  1564	     searchService
   73	    49	 10436	       "d:\soft\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --files --hidden --case-sensitive -g **/*.{css,html} -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --follow --no-config --no-ignore-global
    0	    11	 20236	         console-window-host (Windows internal process)
    0	    47	 15880	     watcherService
    0	   162	 20036	     extensionHost
    7	   138	  1680	       electron_node tsserver.js 
    6	    55	 13416	         electron_node typingsInstaller.js typesMap.js 
    0	   110	 14956	       electron_node eslintServer.js 
    0	    54	 20152	       electron_node tsserver.js 
```

</details>

**Comment by cheTesta** [comment]
+1, also on Mac OS

Rg and Code Helper (Renderer), at startup are taking heckton of CPU usage..




Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (1 day ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by aaomidi** [comment]
+1 here

**Comment by roblourens** [comment]
Please see the tips here: https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory
