### ISSUE TITLE
[Feature request] Support insertTextFormat in vscode.CompletionItem to be consistent with LSP

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/vscode#97865]
In current vscode api, `vscode.CompletionItem` doesn't have `insertTextFormat` field, which is defined in LSP's `CompletionItem`. As an auto-completion extension developer, I expect that vscode can take the result of language server directly. But now, I have to convert it manually everytime:
```typescript
let result : CompletionList = await completionConn.sendRequest("textDocument/completion", completionParam);
let completionResult: vscode.CompletionItem[] = []
result.items.forEach(item => {
	let resultItem = new vscode.CompletionItem(escapeTabStopSign(item.label));
	if (item.insertTextFormat == 2) {
		resultItem.insertText = new vscode.SnippetString(item.insertText);
	} else {
		resultItem.insertText = item.insertText;
	}
	completionResult.push(resultItem);
	});
return completionResult
```

Is it possible to add `insertTextFormat` to vscode.CompletionItem and automatically convert `label:string` to `SnippertString` if `insertTextFormat == 2`? Any discussion is welcome :-)

**Comment by jrieken** [comment]
There is a client library that does the LSP-vscode.dts integration for you, no need for the snippet that you have provided. Adding @dbaeumer for more info

**Comment by HaoboGu** [comment]
> There is a client library that does the LSP-vscode.dts integration for you, no need for the snippet that you have provided. Adding @dbaeumer for more info

Thanks for the reply!
Of course I know the `vscode-languageclient` pakcage, but the point is, I think the vscode api should be consistent with LSP, which provides much convenience when the developers decide to do something by theirselves, for example, using a customized client. 

Additionally, this would help to eliminate many mistakes caused by misusing `vscode.CompletionItem` and `CompletionItem` from `vscode-languageserver-protocol`(which stolen an afternoon from me!)

**Comment by jrieken** [comment]
I am sorry but this will not happen. Usually the LSP is modelled after vscode.dts has changed, e.g the `SnippetString` came first, but LSP ihas different requirements and different power of how expressive it can be (in comparison to vscode.dts is just TypeScript). Therefore slight changes can happen but we will not circle them then back into vscode.dts because that would means there is two ways to express on thing.

**Comment by HaoboGu** [comment]
Thanks for the explanation, I have two more questions. Appreciate if you can answer them.

> Usually the LSP is modelled after vscode.dts has changed, e.g the SnippetString came first

Does it mean that LSP will support `SnippetString` in the future?

> Therefore slight changes can happen but we will not circle them then back into vscode.dts because that would means there is two ways to express on thing

I agree that there can be slight differences. But in my opinion, if vscode api and LSP are consistent, there is only one way to express on a thing. Can you please explain it a lot more? 

Thanks again for your reply

**Comment by jrieken** [comment]
> Does it mean that LSP will support SnippetString in the future?

No/Yes - it does already support via the `insertTextFormat` flags. That is the LSP way to talking about snippet strings. For vscode.dts it is easy and elegant to use or-types but for LSP that often a headache and therefore this approach has been taken.
