### ISSUE TITLE
Object state is captured from first evaluation

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#97863]
Why am I seeing these ℹ️ decorations? The code doesn't look new but I don't remember seeing them before. I think it's telling me that the object view is like a snapshot, not a live view, which is fine but it seems a bit in my face. I shouldn't see it on the primitive. And it should be centered on the line.

![image](https://user-images.githubusercontent.com/323878/82006758-24e6f800-962e-11ea-8b2f-2569e8f68a37.png)

**Comment by isidorn** [comment]
I started removing the annotation, but there were some leftovers, thus it looked ugly.
We can bring it back once we polish this experience.
