### ISSUE TITLE
getting this error when debug python app.

### ISSUE THREAD

**Issue by frndxyz** [microsoft/vscode#97869]
python app show this error popup:

Error parsing URI:
expected string, not PyQt5.QtCore.QByteArray(b'file:///Users/pravin/.vscode-insiders/extensions/ms-python.python-2020.5.78807/pythonFiles/lib/python/debugpy/no_wheels/debugpy')

Version: 1.46.0-insider
Commit: e1d8f5155c0db5ffdc130c9aa0f14efac02dfdfb
Date: 2020-05-13T20:32:52.338Z (1 day ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.7.0

2020-05-15 11:13:41.883 Python[24347:901705] *** Assertion failure in -[QNSApplication run], /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1561.61.100/AppKit.subproj/NSApplication.m:3827
2020-05-15 11:13:41.913 Python[24347:901705] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSApp with wrong _running count'
*** First throw call stack:
(
0 CoreFoundation 0x000000010010a0db __exceptionPreprocess + 171
1 libobjc.A.dylib 0x0000000100ddd942 objc_exception_throw + 48
2 CoreFoundation 0x000000010010fcc2 +[NSException raise:format:arguments:] + 98
3 Foundation 0x0000000108b20a30 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
4 AppKit 0x000000011199f710 -[NSApplication run] + 447
5 libqcocoa.dylib 0x000000012592a623 _ZN21QCocoaEventDispatcher13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 2579
6 QtCore 0x0000000113418b6f _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 431
7 QtCore 0x000000011341d0f2 _ZN16QCoreApplication4execEv + 130
8 QtWidgets.abi3.so 0x000000011611c152 ZL23meth_QApplication_exec_P7_objectS0 + 82
9 Python 0x00000001007b94c8 _PyCFunction_FastCallDict + 552
10 Python 0x0000000100842e94 call_function + 612
11 Python 0x00000001008448a4 _PyEval_EvalFrameDefault + 5604
12 Python 0x0000000100842230 _PyEval_EvalCodeWithName + 2720
13 Python 0x0000000100842a5b fast_function + 219
14 Python 0x0000000100842e7b call_function + 587
15 Python 0x00000001008448a4 _PyEval_EvalFrameDefault + 5604
16 Python 0x0000000100842bde fast_function + 606
17 Python 0x0000000100842e7b call_function + 587
18 Python 0x00000001008448a4 _PyEval_EvalFrameDefault + 5604
19 Python 0x0000000100842230 _PyEval_EvalCodeWithName + 2720
20 Python 0x00000001008423d4 PyEval_EvalCode + 100
21 Python 0x000000010083f1bf builtin_exec + 623
22 Python 0x00000001007b94c8 _PyCFunction_FastCallDict + 552
23 Python 0x0000000100842e94 call_function + 612
24 Python 0x00000001008448a4 _PyEval_EvalFrameDefault + 5604
25 Python 0x0000000100842230 _PyEval_EvalCodeWithName + 2720
26 Python 0x0000000100842a5b fast_function + 219
27 Python 0x0000000100842e7b call_function + 587
28 Python 0x00000001008448a4 _PyEval_EvalFrameDefault + 5604
29 Python 0x0000000100842230 _PyEval_EvalCodeWithName + 2720
30 Python 0x0000000100842a5b fast_function + 219
31 Python 0x0000000100842e7b call_function + 587
32 Python 0x0000000100844dc6 _PyEval_EvalFrameDefault + 6918
33 Python 0x0000000100842230 _PyEval_EvalCodeWithName + 2720
34 Python 0x0000000100842a5b fast_function + 219
35 Python 0x0000000100842e7b call_function + 587
36 Python 0x0000000100844dc6 _PyEval_EvalFrameDefault + 6918
37 Python 0x0000000100842bde fast_function + 606
38 Python 0x0000000100842e7b call_function + 587
39 Python 0x00000001008448a4 _PyEval_EvalFrameDefault + 5604
40 Python 0x0000000100842bde fast_function + 606
41 Python 0x0000000100842e7b call_function + 587
42 Python 0x00000001008448a4 _PyEval_EvalFrameDefault + 5604
43 Python 0x0000000100842230 _PyEval_EvalCodeWithName + 2720
44 Python 0x00000001008423d4 PyEval_EvalCode + 100
45 Python 0x000000010083f1bf builtin_exec + 623
46 Python 0x00000001007b94c8 _PyCFunction_FastCallDict + 552
47 Python 0x0000000100842e94 call_function + 612
48 Python 0x00000001008448a4 _PyEval_EvalFrameDefault + 5604
49 Python 0x0000000100842230 _PyEval_EvalCodeWithName + 2720
50 Python 0x0000000100842a5b fast_function + 219
51 Python 0x0000000100842e7b call_function + 587
52 Python 0x00000001008448a4 _PyEval_EvalFrameDefault + 5604
53 Python 0x0000000100842230 _PyEval_EvalCodeWithName + 2720
54 Python 0x0000000100842369 PyEval_EvalCodeEx + 105
55 Python 0x00000001007910fa function_call + 186
56 Python 0x000000010075d1b3 PyObject_Call + 99
57 Python 0x00000001008975d1 RunModule + 161
58 Python 0x0000000100898928 Py_Main + 4104
59 Python 0x0000000100000dfe Python + 3582
60 Python 0x0000000100000c34 Python + 3124
61 ??? 0x0000000000000007 0x0 + 7
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by alexdima** [comment]
Please create an issue directly against the extension at https://github.com/Microsoft/vscode-python/issues
