### ISSUE TITLE
jupyter notebooks in WSL not working

### ISSUE THREAD

**Issue by AvinashAnad** [microsoft/vscode#97872]
Issue Type: <b>Feature Request</b>

Hi Team,
I am able to view the jupyter notebooks while using my local instance of VSCode, whereas when I switch to WSL and try to view the notebooks they are the plain old json view. Could you please help me to run the jupyter noetbooks in WSL. 
PS: jupyter is installed in WSL.

Regards,
Avinash

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

**Comment by alexdima** [comment]
@AvinashAnad Can you please create an issue directly against the python extension at https://github.com/Microsoft/vscode-python/issues ?
