### ISSUE TITLE
remote connection got "check remote" tab in "Terminal"  window

### ISSUE THREAD

**Issue by ROGERDJQ** [microsoft/vscode#97875]
- VSCode Version: 1.45.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. connect to remote by ssh
2. **Terminal** got "Check remote" which is not able to close
<img width="756" alt="微信截图_20200515150647" src="https://user-images.githubusercontent.com/25008973/82021643-c4070080-96bd-11ea-8330-a376149a17b8.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-python/issues/11122
