### ISSUE TITLE
In the "search and replace" window, a question mark is displayed instead of the number of the searched word Expected Result: The number of the searched word can only be a positive integer.

### ISSUE THREAD

**Issue by sgdreamer7** [microsoft/vscode#97878]
- VSCode Version: 1.45.0 (user setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Open several tabs with files with source code (at least one search word should be present in any of them).
2. Change focus between tabs.

or

1. Open several tabs with files with source code (at least one search word should be present in any of them).
2. Delete the line that contains the search word.

Does this issue occur when all extensions are disabled?: Yes
![screenshot](https://user-images.githubusercontent.com/2242840/82024658-c86cf280-9698-11ea-842d-0667aa9959f4.png)

**Comment by alexdima** [comment]
Possible dup of #97681

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/commit/fbdc028fe4abd3601adbd23883791453501536c3
