### ISSUE TITLE
Typescript Build Errors not being displayed on "PROBLEMS" tab

### ISSUE THREAD

**Issue by hc-danieltiziani** [microsoft/vscode#97879]
- VSCode Version: 1.45.1
- OS Version: Mac Catalina

Steps to Reproduce:

1. Open Typescript Project
2. Start Build task (default)
3. It starts the terminal and outputs errors in compilation
4. But the 'PROBLEMS' are not displayed on the respective tab, only on the terminal

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/58551089/82025295-66f55580-9691-11ea-9d4e-8e018970fc3f.png)

![image](https://user-images.githubusercontent.com/58551089/82025317-6eb4fa00-9691-11ea-8275-359559ac031b.png)

**Comment by alexr00** [comment]
You probably opened the file and then closed it. If the file is open, the errors will show. If the file is closed, the errors will show. If you open the file and there are errors, then you close the file while there are still errors, they will hide. This is a limitation of how we do problems (problems that come from the typescript language server have the same type as those from the task, this is so you don't see the same problem twice). https://github.com/microsoft/vscode/issues/58210 discusses this.
