### ISSUE TITLE
Test: web indication that a breakpoint is hit

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#97876]
Refs: https://github.com/microsoft/vscode/pull/96934

- [x] anyOS @chrmarti
- [x] macOS @misolori

Complexity: 2
Authors: @bpasero @isidorn

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%2397876%0A%0A)

---

When vscode is run in web and a breakpoint is hit we now update the title of the tab.
1. `yarn web` to get vscode running in the web
2. Start debugging something, for example our [smoke-test express starter sample](https://github.com/microsoft/vscode-smoketest-express)
3. Hit a breakpoint while debugging your application

Verify:
* There is a breakpoint decoration in the browser tab as long as the breakpoint is hit and the focus is not on the tab
* As soon as you focus the tab the breakpoint decoration is gone
* Please try multiple browsers: Chrome, Firefox, Safari
* Feedback on how to indicate this better is welcome! Note that in VS Code app on breakpoint hit we blink the Window, that is not possible in the web.

**Comment by chrmarti** [comment]
@isidorn Could you tell me / point me to documentation on how to make `yarn web` open a local folder (or allow the resulting workbench to do that)? I have tried `gulp mixin-server` without luck.

**Comment by bpasero** [comment]
@chrmarti pinged you in Slack

**Comment by chrmarti** [comment]
Works well. Feedback part: Maybe you have experimented with web notifications. Could these be a light-enough way of telling the user that an unfocused tab hit a breakpoint?

**Comment by isidorn** [comment]
@chrmarti thanks for testing and for feedback. Web notifications might be too noisy for my taste, similar as I would hate a web notification when I get a chat massage. Not sure what @bpasero thinks, I am fine with experimenting.

**Comment by bpasero** [comment]
Worth a try I think.

**Comment by chrmarti** [comment]
I think the main trouble with web notifications is that you first need the user's permission to use them. Throwing the browser's 'Allow this page to show notifications?' at them without introducing why this might be needed always seems a little rough to me. Maybe first explain why this would improve the experience and go to the notification API only when the user indicated they would like to enable it. (I see a similar pattern in mobile apps.)
