### ISSUE TITLE
Configuring link settings for the first time doesn't open clicked link in browser

### ISSUE THREAD

**Issue by infixint943** [microsoft/vscode#97886]
Issue Type: <b>Bug</b>

After clicking a link and configuring link trust, the clicked link doesn't open automatically, forcing to reclick the link again.
However, once the link trust is configured, the clicked link opens normally.

VS Code version: Code - Insiders 1.46.0-insider (e1d8f5155c0db5ffdc130c9aa0f14efac02dfdfb, 2020-05-13T18:15:00.101Z)
OS version: Linux x64 5.4.40-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2118)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|5.71GB (2.31GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|deepin|
|XDG_CURRENT_DESKTOP|Deepin|
|XDG_SESSION_DESKTOP|deepin|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
chat|kar|0.33.0
cpptools|ms-|0.28.0
Go|ms-|0.14.2
vsliveshare|ms-|1.0.2169
material-icon-theme|PKi|4.1.0

(2 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
Actually, how did you configure trust? Did you open the file to edit, or choose one of the "Trust this domain" options?
