### ISSUE TITLE
tabCompletion interferes with quickSuggest

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#9788]
Testing #9698

- open JS file
- type 'for'
- TAB

-> you do not get the for snippet, but 'for' gets completed with the keyword 'for' (when autoSuggest is not loaded yet, then it works.)

Minimal fix is to recommend to disable quick suggest when you want to have tab completion.

**Comment by jrieken** [comment]
Added a message to the `tabCompletion` config
