### ISSUE TITLE
Bug - Unreachable code detected

### ISSUE THREAD

**Issue by FloydSamkhyey** [microsoft/vscode#97888]
- VSCode Version: Code 1.45.1
- OS Version: Windows 10 x64
This happens without ts-check, with ts-check, without all extensions

![rr](https://user-images.githubusercontent.com/60310172/82030052-93649e00-96a0-11ea-814c-9807993189cf.png)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by FloydSamkhyey** [comment]
Oh, you fixed it. Now code displays correctly.
