### ISSUE TITLE
Views are gone in electron 8

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#97884]
I started selfhosting on the E8 build. I noticed I didn't have an Output pane anywhere. It wasn't on the activity bar or in the panel. It didn't appear in any of the context menus of those areas. It was just gone. Running `Git: Show Git Output`, which would normally reveal the output pane, would do nothing at all.

I ran `View: Reset View Locations` and now it's back.

I can't reproduce.

**Comment by jrieken** [comment]
I didn't have a terminal. The reset command brought it back. 🐟-y

**Comment by sandy081** [comment]
Trying to understand what would have happened. By any chance you remember

- What was the build you were using before?
- What were the view customisations you had?

**Comment by sandy081** [comment]
Also you have settings sync enabled?

**Comment by jrieken** [comment]
Yeah, sync enabled (but only using one machine). Saw this with 172e95180396a1b6889938f87ee92c9f9d5e2e48 (electron 8 test), used e1d8f5155c0db5ffdc130c9aa0f14efac02dfdfb before that

**Comment by sandy081** [comment]
One of the reasons I asked if sync is enabled is to get the global state. It would be great if you can get the global state before and after?

**Comment by jrieken** [comment]
how?

**Comment by jrieken** [comment]
this?

[globalState.zip](https://github.com/microsoft/vscode/files/4633970/globalState.zip)

**Comment by bpasero** [comment]
I did not encounter this. Note that the E8 build is 1day old, does not match todays insider.

**Comment by sandy081** [comment]
We have some changes to handling view state recently.  It shall handle smoothly when you move from older to newer version but there are chances to see unexpected results if you move back and forth. From the build commits I can say that e1d85f1 is with old logic and 172e951 has new logic.

**Comment by sbatten** [comment]
Got the repro on @joaomoreno's machine. The issue is well understood and is a result of the electron build missing a few key commits for the view changes @sandy081 mentioned. Since today's insiders build resolves the issue correctly, I will not worry about this interim issue. I recommend we upgrade the e8 build by a day.
