### ISSUE TITLE
A Document Being Saved by xcdevice

### ISSUE THREAD

**Issue by rgb1380** [microsoft/vscode#97893]
I am seeing large documents (1.6GB) being created in MacBook Air's temporary folder (in my case: /private/var/folders/xb/j4_1kvcx0x1679jq7slr5vvm0000gn/T/TemporaryItems/(A Document Being Saved By xcdevice)/dyld_shared_cache_arm64, then in another folder:  (A Document Being Saved By xcdevice 2) with the same file. These type of folders continue to be created with the same file inside until the entire disk is used up. The documents seem to be created by vscode. 

- VSCode Version: 1.45.1
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. Open vscode
2. Load a flutter project
3. Connect an iPhone (in my case it is an iPhone 7 plus, iOS 13.1.3)

For me, this is a repeatable problem.  Disconnecting the iPhone, or closing vscode stops the temporary files from being created. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexdima** [comment]
Please create the issue directly against the flutter extension at https://github.com/Dart-Code/Dart-Code/issues
