### ISSUE TITLE
Get an error when trying the AWS tutorial for running a Lambda locally under SAM with vscode codelens

### ISSUE THREAD

**Issue by nickweavers** [microsoft/vscode#97896]
- VSCode Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
- OS Version:
Windows 10 Pro
Version	1909
Installed on	21/08/2019
OS build	18363.836

Steps to Reproduce:

Follow the steps described in this short video tutorial exactly, but choose the nodejs12.x runtime. When you finally click the "Debug locally" CodeLense option above the exports.lambdaHandler = async (event, context) => { the error will be produced in the "Debug console".

The steps listed are:

1. open a bash terminal in WSL
2. cd to a directory you'd keep your projects in (for me /c/var/www/lambda)
3. In vscode CTRL-SHIFT-P
4. Select "AWS: Create new SAM application"
5. Select node12.x as SAM Application Runtime
6. Select ASW SAM Hello World as SAM Application Template
7. Enter . as the workspace folder for the new project
8. Click okay at the path confirmation /c/var/www/lambda/
9. enter sam-app as the name of your new app
10. In vscode, edit the sam-app/hello-world/app.js file
11. Insert a new line after line 19 and add console.log("We got here!");
12. Place a breakpoint on this new line
Click Configure in the CodeLens options above the exports.lambdaHandler = async (event, context) => {
13. Click on the TERMINAL link when placed into the editor fore template.json
14. enter sam local generate-event apigateway aws-proxy | clip
15. select the {} in the "event": {}, in templates.json and paste in the clipboard
16. ALT-SHIFT-F to auto format
17. Now click the ``Debug Locally"" CodeLens option in the app.js file

Observed result:

The debugger first stops at the line
const RAPIDClient = require("./RAPIDClient.js");
in file index.js
image
![image](https://user-images.githubusercontent.com/194136/82035366-53e58400-9697-11ea-84b6-c8195b2a2042.png)

After clicking the continue button in
image 
![image](https://user-images.githubusercontent.com/194136/82035427-6790ea80-9697-11ea-9535-dea8f1575daf.png)
it gets here
image
![image](https://user-images.githubusercontent.com/194136/82035467-74154300-9697-11ea-9344-23538325d9f0.png)

then clicking continue again gives the error below in the DEBUG CONSOLE

2020-05-10T16:33:02.723Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module 'app'","Require stack:","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1153:14)","    at Object..js (internal/modules/cjs/loader.js:1176:10)","    at Module.load (internal/modules/cjs/loader.js:1000:32)","    at Function._load (internal/modules/cjs/loader.js:899:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)","    at internal/main/run_main_module.js:18:47"]}
START RequestId: b9a1ab35-1c23-10e5-fcfb-b89d7e57ac38 Version: $LATEST
END RequestId: b9a1ab35-1c23-10e5-fcfb-b89d7e57ac38
REPORT RequestId: b9a1ab35-1c23-10e5-fcfb-b89d7e57ac38	Init Duration: 20909.03 ms	Duration: 1.53 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 42 MB	

{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js"}

Expected result
I expected the working result they show in the video, which was that the debugger stops at the breakpoint on the console.log("AM is the coolest"); statement.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by nickweavers** [comment]
Additional info...

When I run Vscode local sam debug on myApp and
the debugger stops on the first breakpoint, DockerDesktop shows shows that a container is running and clicking Inspect on DockerDesktop shows a mount point is being created on this directory /tmp/aws-toolkit-vscode/vsctkTI3eKg/output/awsToolkitSamLocalResource

![image](https://user-images.githubusercontent.com/194136/82035693-c48ca080-9697-11ea-95b2-93563ff94644.png)

Listing the contents of this directory in my wsl bash I see:
```
nickw@nicks-xps-15-9560:/tmp/aws-toolkit-vscode/vsctkTI3eKg/output/awsToolkitSamLocalResource
$ ls -la
total 16
drwxrwxrwx 1 nickw nickw 512 May 15 08:40 .
drwxr-xr-x 1 nickw nickw 512 May 15 08:40 ..
-rwxrwxrwx 1 nickw nickw 2101 Oct 26 1985 README.md
-rwxrwxrwx 1 nickw nickw 978 Oct 26 1985 myApp.js
drwxrwxrwx 1 nickw nickw 512 May 15 08:40 node_modules
-rwxrwxrwx 1 nickw nickw 728 Oct 26 1985 package.json
-rwxrwxrwx 1 nickw nickw 1668 Oct 26 1985 template.yaml
```
But the vscode debug OUTPUT pane shows:
```
Attaching debugger to SAM Application...
Debugger attached.
Debugger attached
2020-05-15T08:14:50.956Z undefined ERROR Uncaught Exception

{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'myApp'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module 'myApp'","Require stack:","- /var/runtime/UserFunction.js","- /var/runtime/index.js"," at _loadUserApp (/var/runtime/UserFunction.js:100:13)"," at Object.load (/var/runtime/UserFunction.js:140:17)"," at Object.<anonymous> (/var/runtime/index.js:43:30)"," at Module._compile (internal/modules/cjs/loader.js:1153:14)"," at Object..js (internal/modules/cjs/loader.js:1176:10)"," at Module.load (internal/modules/cjs/loader.js:1000:32)"," at Function._load (internal/modules/cjs/loader.js:899:14)"," at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)"," at internal/main/run_main_module.js:18:47"]}
START RequestId: 542fa657-ac24-1eca-333b-a4f92d27a9b5 Version: $LATEST
END RequestId: 542fa657-ac24-1eca-333b-a4f92d27a9b5
REPORT RequestId: 542fa657-ac24-1eca-333b-a4f92d27a9b5 Init Duration: 2042883.21 ms Duration: 2.44 ms Billed Duration: 100 ms Memory Size: 128 MB Max Memory Used: 41 MB

{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'myApp'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js"}
Local invoke of SAM Application has ended.
```
Any ideas on why the error is saying that myApp can't be found when it is clearly in the directory that is being mounted and that directory is in the wsl file system?

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you please clarify how it is related to the editor itself?

If there is problem with extension you are using for AWS - please report it in extension repo.
If you have general question related to this topic - you should use StackOverflow instead of editor issue tracker.

**Comment by nickweavers** [comment]
Okay, thanks.
