### ISSUE TITLE
Build task bug

### ISSUE THREAD

**Issue by the-wulv** [microsoft/vscode#97891]
Issue Type: <b>Bug</b>

In the `tasks.json` file, when the command is a path, VSCode wraps the whole command in double quote marks, and so it cannot be executed by the shell.

For example, this g++ command "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-win32-seh-rt_v6-rev0\\mingw64\\bin\\g++.exe" produces this:

![εικόνα](https://user-images.githubusercontent.com/49089857/82033415-5d75e880-96a5-11ea-8048-b6a5d46985bf.png)

This is my `tasks.json` file (in case something is wrong with it):
```jsonc
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "shell: g++.exe build active file",
            "command": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-win32-seh-rt_v6-rev0\\mingw64\\bin\\g++.exe",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-win32-seh-rt_v6-rev0\\mingw64\\bin"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
vscode-browser-preview|auc|0.6.7
vscode-eslint|dba|2.1.5
xml|Dot|2.5.0
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
vscode-pull-request-github|Git|0.16.0
output-colorizer|IBM|0.1.2
bridlensis|idl|1.0.1
nsis|idl|3.26.1
vscode-peacock|joh|3.7.2
chat|kar|0.33.0
python|ms-|2020.5.78807
cpptools|ms-|0.28.0
vsliveshare|ms-|1.0.2169
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.3.4
material-icon-theme|PKi|4.1.0
rockstar-language|ra1|1.0.0
vscode-javascript-booster|sbu|0.12.3
vscode-hexdump|sle|1.7.2
vscode-icons|vsc|10.1.1

(1 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
If you're using `cmd.exe` (and it looks like you are), then Tasks just runs `cmd.exe /c <your command>`, which I tried and it shows the same behavior that you're seeing.

You can try escaping your spaces with a carrot:
```
            "command": "C:\\Program^ Files\\mingw-w64\\x86_64-8.1.0-win32-seh-rt_v6-rev0\\mingw64\\bin\\g++.exe",
```
