### ISSUE TITLE
Expanding a folder in the Explorer tab resulted in sub-tree being inserted in wrong spot

### ISSUE THREAD

**Issue by JobLeonard** [Microsoft/vscode#9789]
- VSCode Version: 1.3.1
- OS Version: Ubuntu 16.04

Steps to Reproduce: I have no idea, sorry :(. But here's what I did prior to this bug happening, although I don't know if any of it is relevant:

- commit+push, leaving a comparison window open
- switch branches in VSC to a branch where the committed file does not yet exist
- switch branches _in terminal_ outside of VSC

Sorry about the weird description in the title, it's the best I could make of it, but here's a screencapture:

![wat](https://cloud.githubusercontent.com/assets/259840/17141916/60febaac-534e-11e6-9f54-7af900a2d524.gif)

I "fixed" it by closing/opening VSC, but it's still weird behaviour that might hint at a deeper bug.

**Comment by bpasero** [comment]
Please report back once you have reliable reproducible steps.
