### ISSUE TITLE
Warnd when using configurationDefaults without an override property

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#97895]
From https://github.com/microsoft/vscode/issues/97753#issuecomment-628687342

configurationDefaults are only allowed for override properties. All others are ignored, but no warning is shown.

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/blob/master/src/vs/workbench/api/common/configurationExtensionPoint.ts#L124

**Comment by sandy081** [comment]
Added warning for non supported defaults.

@aeschli Is it possible to add this to json schema? 

https://github.com/microsoft/vscode/blob/master/src/vs/workbench/api/common/configurationExtensionPoint.ts#L88-L103 ?

**Comment by aeschli** [comment]
@sorry for the late response, to make this work, also additionalProperties: false is needed:
```
// BEGIN VSCode extension point `configurationDefaults`
const defaultConfigurationExtPoint = ExtensionsRegistry.registerExtensionPoint<IConfigurationNode>({
	extensionPoint: 'configurationDefaults',
	jsonSchema: {
		description: nls.localize('vscode.extension.contributes.defaultConfiguration', 'Contributes default editor configuration settings by language.'),
		type: 'object',
		patternProperties: {
			'^\\[.*\\]$': {
				type: 'object',
				default: {},
				$ref: resourceLanguageSettingsSchemaId,
			}
		},
		errorMessage: nls.localize('config.property.defaultConfiguration.languageExpected', "Language selector expected (e.g. [\"java\"])"),
		additionalProperties: false
	}
});
```

I made some more improvements and pushed the fix

**Comment by aeschli** [comment]
Verified that a warning is shown
