### ISSUE TITLE
Const variables in JavaScript is shown as unused

### ISSUE THREAD

**Issue by Eddi-S** [microsoft/vscode#97898]
Issue Type: <b>Bug</b>

Create an empty JavaScript file (test.js)
Add the following content:

```
function name() {
    const usedConst = 2
    let usedLet = usedConst + 2
    console.log(usedLet)
}
```

The variable usedConst is now faded (as if it was unused). I have also tried disabling my extension but with no effect.
![image](https://user-images.githubusercontent.com/65396539/82037997-31f1fe80-96a3-11ea-8273-ea9ad62ee641.png)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.62GB free)|
|Process Argv|--folder-uri file:///c%3A/workspace/missinglink|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
python|ms-|2020.5.78807
remote-wsl|ms-|0.44.2

</details>

**Comment by IllusionMH** [comment]
Unused has different color, this one is for constants.
See https://github.com/microsoft/vscode/issues/95346#issuecomment-626912507

/assign @aeschli

**Comment by evg656e** [comment]
I have color blindness (deuteranomaly) and I hardly see the difference between unused and const variable now. I suggest to make const variable a brighter (closer to normal variables).

**Comment by Eddi-S** [comment]
@IllusionMH Thanks for clearing that up. But I agree with @evg656e that the difference is not that big and it might be easy to make the same mistake that I made.
I have made anther example showing the colour difference. 
![image](https://user-images.githubusercontent.com/65396539/82076245-d5f89b80-96dd-11ea-9343-41813cfe12e9.png)

**Comment by IllusionMH** [comment]
Just in case - I wanted clarify current behavior and linked post with "workaround" (should be more clear here). No suggestions if this issue should be closed.

**Comment by aeschli** [comment]
We have #97373 to track improvement of the const color.
