### ISSUE TITLE
Split branches from tags in source control checkout window

### ISSUE THREAD

**Issue by HitLuca** [microsoft/vscode#97909]
I am working on a project that has many tags, and whenever I want to switch branches by clicking the bottom-left source control button, I am presented with branches and tags combined in a single list. It would be useful to split them to reduce the clutter

Bottom-left source control button:
![image](https://user-images.githubusercontent.com/7645621/82051512-47beee00-96ba-11ea-8c6b-772d95b788d8.png)

List of branches + tags popup
![image](https://user-images.githubusercontent.com/7645621/82051541-5c9b8180-96ba-11ea-8b06-50f5d8e429de.png)

An alternative would be to have origin/ branches on top, so that all branches are grouped, but I believe that moving tags away completely is a better solution

**Comment by HitLuca** [comment]
Just noticed it, the tags are also not ordered semantically, that would be a welcome feature too

**Comment by lszomoru** [comment]
Verification steps:
1. Launch the latest VS Code Insiders
2. Open a folder/workspace that contains a git repository
3. Ensure that the git repository has local/remote branches, and tags
4. Click on the "Checkout" status bar item to bring out the checkout quick pick
    * Confirm that the local branches, remote branches, and tags are grouped (separator, group labels)
