### ISSUE TITLE
User installed extension is logged as "built-in extension"

### ISSUE THREAD

**Issue by Nokel81** [microsoft/vscode#97906]
- VSCode Version: 1.45.0
- OS Version: Darwin 10.15.3

Steps to Reproduce:

1. Have a file open
2. Have the Global Find left sidebar open
3. Have cursor select one of the text boxes in the find sidebar
4. Press `⌘+J` or "join lines" and notice that even though there is no flashing cursor on the main file display, nonetheless, lines are joined.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@Nokel81 This appears to be a problem with your user configured `keybindings.json`. By default, we do not ship with `cmd+j` bound to join lines. I am guessing that the problem is a missing context key, e.g.:

```
{ "key": "cmd+j", "command": "editor.action.joinLines", "when": "textInputFocus" }
```

Can you please double check your keybindings?

**Comment by Nokel81** [comment]
Sorry for the late response. This is the content of my `keybindings.json` file:

```
// Place your key bindings in this file to override the defaults
[
]
```

<img width="1541" alt="Screen Shot 2020-11-18 at 8 14 10 AM" src="https://user-images.githubusercontent.com/8225332/99534839-0c0d2580-2976-11eb-92a7-de2c8074708b.png">

This is what I see when I searched for "join" in the keyboard shortcuts UI.

**Comment by alexdima** [comment]
@Nokel81 I think this is a keybinding contributed by one of your extensions.  Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command Developer: Toggle Keyboard Shortcuts Troubleshooting
  * This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* You can then press `cmd+j` and check what keyboard shortcut VS Code detects and what command is invoked.

This will output if the keybinding rule is a built-in one or contributed by an extension.

If you are having trouble understanding the output, please feel free to paste here and we can help decipher it for you.

**Comment by Nokel81** [comment]
This is the relevant logs:

```
[2020-11-18 13:59:55.901] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [meta], code: MetaLeft, keyCode: 91, key: Meta
[2020-11-18 13:59:55.901] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: MetaLeft, keyCode: 57 ('Meta')
[2020-11-18 13:59:55.901] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched.
[2020-11-18 13:59:56.168] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [meta], code: KeyJ, keyCode: 74, key: j
[2020-11-18 13:59:56.168] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: KeyJ, keyCode: 40 ('J')
[2020-11-18 13:59:56.168] [renderer1] [info] [KeybindingService]: | Resolving meta+[KeyJ]
[2020-11-18 13:59:56.168] [renderer1] [info] [KeybindingService]: \ From 2 keybinding entries, matched editor.action.joinLines, when: no when condition, source: built-in extension ms-vscode.atom-keybindings.
```

Namely, this shows that it is the "built-in extension ms-vscode.atom-keybindings"

**Comment by alexdima** [comment]
* Oh, that's a bug in the debugged output. `ms-vscode.atom-keybindings` is an extension, but not a built-in extension. The output should read: "source: extension ms-vscode.atom-keybindings". I suggest we use this issue to track this bug.
* Basically the atom keybindings extension defines `cmd+j` for join lines, but forgets to define a `when` clause. Let's track that at https://github.com/microsoft/vscode-atom-keybindings/issues/70

**Comment by alexdima** [comment]
Until https://github.com/microsoft/vscode-atom-keybindings/issues/70 is addressed, you can use the following in your `keybindings.json`:

```
{ "key":"cmd+j", "command":"-editor.action.joinLines" }, // remove the keybinding with missing when clause
{ "key":"cmd+j", "command":"editor.action.joinLines", "when": "editorTextFocus && !editorReadonly" },
```

**Comment by Nokel81** [comment]
Thanks for the quick response and will do.
