### ISSUE TITLE
Multiline selection is broken, probably not as intended

### ISSUE THREAD

**Issue by johschmitz** [microsoft/vscode#97904]
- VSCode Version: 1.45.0
- OS Version: Linux Mint 19.3

Steps to Reproduce:

1. Place cursor at beginning of any line.
2. Hold down Shift+Alt with left hand.
3. Press DownArrow repeatedly with right hand.
4. Press UpArrow once with right hand.

Current behaviour:
Multiline cursor **extends** towards the Up direction.

Expected Behaviour:
Multiline cursor **should shrink** one line from the bottom of its already extended multilines.
The same for the other direction, when selecting Up, Up, Up then once Down it should grow back one line not add another line at the bottom.
_Optionally_: After holding down an _additional_ button (e.g. Ctrl) the currently implemented behaviour should occur.

Reason:
The current implementation forces the user to place the initial single line cursor in the middle of the block instead of the first or last line in order to be able to use this feature in any sensible way. There is no way to shrink the cursor when you accidentially extend one line too much. This is extremely  annoying and I classify this as a bug.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by IllusionMH** [comment]
AFAIK this is intended behavior and available in a lot of other editors.

> There is no way to shrink the cursor when you accidentially extend one line too much.

There is shortcut exactly for this Cursor Undo <kbd>Ctrl</kbd>+<kbd>U</kbd>

**Comment by johschmitz** [comment]
> There is shortcut exactly for this Cursor Undo Ctrl+U
This seems very impractical.
I have to take both hands down the keys because I can't reach U with the left hand to undo, then after undo go back to the arrow keys. Very impractical, also need to remember another shortcut.
I just used the feature again to comment a lot of lines in a Terraform (.tf) file because the normal commenting doesn't work there. When you want to extend the cursor more lines than fit in your screen by keeping arrow pressed there's almost no way to hit the right line and you almost allways have to undo.
Not all other editors do this!
Examples:
vim - Press Ctrl+V then move cursor to extend or shrink (does not do it)
notepad++ hold alt+shift then move cursor to extend or shrink (does not do it)
sublime-text - semi does it but at least lets you go back when one side of the multiline cursor is at the beginning or end of the file, also seems to be buggy, sometimes extends into another column?

I just noticed that Shift+Ctrl works too in VSCode. Maybe at least one of them Shift+Ctrl or Shift+Alt could have the "one way" behavior. That way we could quickly switch between both ways of selecting.

@IllusionMH honestly do you often place the cursor in the middle of the text block then you extend upwards and downwards? Who really does this instead of starting from the first or last line?

**Comment by IllusionMH** [comment]
I not arguing that <kbd>Ctrl</kbd>+<kbd>U</kbd> is faster or better than cursor arrows, just stating the fact that this isn't VS Code only thing and definitely not a bug or the end of the world.

Personally I rarely use these shortcuts to create mutliline selections, but in other cases <kbd>Ctrl</kbd>+<kbd>U</kbd> works fine. Even when I do - it's usualye 1 direction and next operation still requires move of right hand (<kbd>Shift</kbd>+<kbd>End</kbd> or <kbd>Ctrl</kbd>+<kbd>L</kbd>) so it doesn't bother me.

**Comment by johschmitz** [comment]
Okay I understand for you it is not a big deal but I am using multiline cursor quite a lot and this issue bites me almost every single time.
So it would be great to have <kbd>Ctrl</kbd> + <kbd>Shift</kbd> for vim type multicursor behavior and <kbd>Ctrl</kbd> + <kbd>Alt</kbd> for sublime-text/legacy type multicursor behavior.

**Comment by alexdima** [comment]
@johschmitz Please use the following keybindings in your `keybindings.json`:
```
    { "key": "shift+alt+down",     "command": "cursorColumnSelectDown",      "when": "textInputFocus" },
    { "key": "shift+alt+left",     "command": "cursorColumnSelectLeft",      "when": "textInputFocus" },
    { "key": "shift+alt+pagedown", "command": "cursorColumnSelectPageDown",  "when": "textInputFocus" },
    { "key": "shift+alt+pageup",   "command": "cursorColumnSelectPageUp",    "when": "textInputFocus" },
    { "key": "shift+alt+right",    "command": "cursorColumnSelectRight",     "when": "textInputFocus" },
    { "key": "shift+alt+up",       "command": "cursorColumnSelectUp",        "when": "textInputFocus" },
```

![Kapture 2020-11-16 at 14 58 32](https://user-images.githubusercontent.com/5047891/99260855-3ba81a80-281c-11eb-9da2-e45869144d8a.gif)
