### ISSUE TITLE
Add switch tab shortcuts (similar to browsers)

### ISSUE THREAD

**Issue by maximilianMairinger** [microsoft/vscode#97905]
### Feature request

Currently pressing `ctrl+2` splits the editor. I personally find this option rather useless and would much prefer a way to hotkey to different already opened tabs (`ctrl+1` => first tab; `ctrl+2` => second tab). So that the hotkeys would replicate the behaviour that most browsers (e.g. chrome) currently have.

If you consider this a breaking feature request, since the default shortcuts would be rebound, I would suggest making this an option to enable in the shortcut settings. Since this alone would require the user to rebind 9 shortcuts, Id also consider an additional option somewhere else in the settings, where those hotkeys could be toggled.

**Comment by bpasero** [comment]
See
![image](https://user-images.githubusercontent.com/900690/82185492-930b1380-98e9-11ea-83c4-e6a3b8a6327d.png)

**Comment by maximilianMairinger** [comment]
Thanks alot. Sorry, but I wasnt able to find anything online about this.
