### ISSUE TITLE
Highlighted text in editor should be string to be searched for

### ISSUE THREAD

**Issue by csicky** [microsoft/vscode#97914]
Issue Type: <b>Bug</b>

I select a text in the editor, then click the search in the sidebar. Until now, the selected search was auto populated in the search box. Now it is not doing that.

https://www.loom.com/share/17b72bac896a429696251f363ee8221c

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-blink-mind|awe|0.0.10
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
prettier-vscode|esb|4.7.0
auto-close-tag|for|0.5.7
favorites|kdc|2.4.5
back-n-forth|nic|3.0.2
vetur|oct|0.24.0
nativescript|Tel|0.11.0

</details>

**Comment by yume-chan** [comment]
See https://github.com/microsoft/vscode/issues/91901#issuecomment-615432975.

A new setting, "search.seedOnFocus" has been added to control this behavior, and it's default to `false`.

Sadly it didn't get mentioned in the Release Notes.

**Comment by csicky** [comment]
I don't know if it is the same, but I have this checkbox checked and it still not working:
![image](https://user-images.githubusercontent.com/3931907/82066699-6fbd4a00-96d8-11ea-8096-0056e6f743ea.png)

**Comment by csicky** [comment]
OK, I searched now on `search.seedOnFocus` and found that one checkbox. Now it is working. The one in the above checkbox is probably the small search in top right corner of the editor. It is confusing a bit, maybe the one in the screenshot above could be placed next to this one for people to know even if the meaning of the text is similar, there are actually two settings.

**Comment by csicky** [comment]
@yume-chan thank you for clarifying it.
