### ISSUE TITLE
No syntax highlighting for custom class python 

### ISSUE THREAD

**Issue by ramank775** [microsoft/vscode#97910]
- VSCode Version: 1.45.1 (user setup)
- OS Version:  Microsoft Windows 10 Pro (Version	10.0.18363 Build 18363)

Steps to Reproduce:

1. Create a new custom class 
2. Create an object of that custom class. There is no syntax highlighting while creating the class
3 Create an object of builtin class. Syntax highlighting is here

Does this issue occur when all extensions are disabled?: Yes/No
Yes
![image](https://user-images.githubusercontent.com/24293550/82052927-16561a80-96da-11ea-9820-1dee80c70348.png)

**Comment by alexr00** [comment]
Highlighting like that requires semantic highlighting, which we do not provide for Python. I recommend that you file this as a feature request with the Microsoft Python extension (or whichever python extension you like to use).
