### ISSUE TITLE
Create A Standardized Test System Like Language Service and Make Testing First Class

### ISSUE THREAD

**Issue by JohnGalt1717** [microsoft/vscode#97919]
One of the real breakthroughs of VS Code is the language service.  It allows any language to be hooked in and work with all of the first class features of a modern editor. It's what enables VS Code to be so great.

Right now, there's no such thing for testing and as a result you have separate test stuff for .net core, protractor, java, etc. and none of them work very well.

It would be really great (and I think necessary) for VS Code to get to where VS.net is with a standard test hardness similar to how the language service works that every test system can hook into and automatically provide tests to a test tab on the left side.  This would allow realtime background test monitoring, tests from multiple providers in the same folder (this happens with Angular as an example), and live testing similar to VS.net.

This is really the last blocker we have with our team being able to use vs code with remote containers and slim down from vs.net and even using Android Studio from flutter etc.  The test systems are just too unreliable as it stands so adding a standardized system would be a HUGE win for everyone I think.

**Comment by dbaeumer** [comment]
This would require API and VS Code and something like a LSP for testing.

**Comment by JohnGalt1717** [comment]
@dbaeumer 

The hope from this would be to create a first class testing story in VS Code that works for all languages and enables all of the features you get in vs.net and other IDEs but does so in a generic way instead of being targeted to just a select few languages etc.

Am I conveying the idea well enough?

**Comment by connor4312** [comment]
We've started on this in https://github.com/microsoft/vscode/issues/107467

/duplicate https://github.com/microsoft/vscode/issues/107467 https://github.com/microsoft/vscode/issues/9505
