### ISSUE TITLE
Add option to configure the default show context (number of context lines) in search editor

### ISSUE THREAD

**Issue by Dzejkop** [microsoft/vscode#97915]
I keep opening the search editor and clicking the show context button every single time - the show context to me is one of the stronger features of the search editor.

It would be nice to be able to configure it permanently. I know `reusePriorSearchConfiguration` exists but that would affect all the other settings.

My proposal is to add `search.searchEditor.defaultShowContextValue` property (`number | null`) which when defined would override the default value for the number of context lines.

`reusePriorSearchConfiguration` would take precedence if both are used.

**Comment by JacksonKearl** [comment]
Thanks for this and the PR! I unfortunately wasn't able to get around to it in the May iteration but I've scheduled it for June.

**Comment by JacksonKearl** [comment]
Closed with #97920.

**Comment by connor4312** [comment]
1. A description would be helpful. Right now this is probably not apparent to a normal user

![](https://memes.peet.io/img/20-06-a0ed6d5f-eb3e-433a-a8b8-836ea621ce49.png)

2. This doesn't appear to work for me. I set it to the suggested value of `2` but context was not shown

![](https://memes.peet.io/img/20-06-4b1aee6b-e05b-49c3-b63e-56add39ed088.png)

```
Version: 1.46.0-insider (user setup)
Commit: 1bfa086adb9271ff56be11821da686e4cfffb672
Date: 2020-06-02T06:55:33.079Z
Electron: 7.3.0
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by JacksonKearl** [comment]
Description was already added in master, will look into rest

**Comment by JacksonKearl** [comment]
The description is:

The default number of surrounding context lines to show in Search Editor results. If defined, this overrides `#search.searchEditor.reusePriorSearchConfiguration#` for context line configuration in new Search Editors.

Testing, this does seem to work: if I set the value, then open a new search editor, and run a query, it will have context. It doesn't update live, but I think based on the description that wouldn't be expected.

**Comment by connor4312** [comment]
That doesn't work for me. Here's a recording, maybe I'm missing something: https://memes.peet.io/img/20-06-28fc1d00-d10d-4ea3-8563-cf0a1058e6d3.webm

**Comment by JacksonKearl** [comment]
Ah... hm. This was meant for the command `Search Editor: open new Search Editor`, not `Search Editor: Open Results in Editor`. `Open in editor` doesn't run a new search, so it can't get the context lines. Agreed that it's confusing...

**Comment by JacksonKearl** [comment]
I've updated the name of the setting to `defaultNumberOfContextLines` and updated the description text to be more specific about where it applies. Also updated so the number isn't displayed when it is not actually used (open results in editor case).

Please verify:
1. `search.searchEditor.defaultNumberOfContextLines` name and description make sense.
2. When the setting is set to some value, running "Search Editor: Open new Search Editor" will pre-fill that value correctly, and searches will have that number of context lines
3. when creating a search editor from existing results ("Open Results in Editor"), the context lines box does not incorrectly show that context lines are enabled.

**Comment by roblourens** [comment]
Please consider giving it a numeric default instead of null, so we can use the settings GUI for it too

**Comment by JacksonKearl** [comment]
We actually can render `number | null` in the settings editor. Empty input is mapped to null. (That was one of my intern projects lol)
![image](https://user-images.githubusercontent.com/8586769/83697516-0f714800-a5b4-11ea-9898-843d1d20965c.png)

**Comment by roblourens** [comment]
Oh yeah I forgot we can for number. Not string.

**Comment by joaomoreno** [comment]
This doesn't seem to work if I type a search term and press <kbd>Ctrl Enter</kbd>: no context lines are added to the view.
