### ISSUE TITLE
Allow key binding for individual launch configurations

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#97921]
I would like to be able to start my 4 or 5 different launch configurations with different key bindings - F5 starts only the one  selected in the "Run" panel, and that sometimes changes unexpectedly (compare #90216, 2nd problem).

See also https://stackoverflow.com/questions/48645098/vscode-keyboard-shortcut-for-launch-configuration

**Comment by ArturoDent** [comment]
I tried this and it worked! (but not the `preLaunchTask`).  In your keybindings.json:

```
{
  "key": "alt+j",
  "command": "debug.startFromConfig",
  "args": {
      "type": "node",
      "request": "launch",
      "name": "First Debugger",
      "program": "${workspaceFolder}/test.js",
      "console": "integratedTerminal",
      //"preLaunchTask": "run echo of variables"  // can't get it to find a preLaunch task
  }
}
```
I assumed that referring to a launch config by `name` would get that config from launch.json but that doesn't seem to be the way it works - I had to include all the `args` unfortunately.

There is no need for this configuration to also appear in your launch.json.  So obviously, this config does not need to be the current chosen option in the `Run` options dropdown.

I just discovered this in reference to your question so give it a test.

**Comment by bersbersbers** [comment]
Thank you - I haven't tried it yet, but it's definitely an interesting approach. I dislike the need to duplicate the launch configurations, though. So I have experimented with saving at least the debug config args in a new settings variable 
```
"args": [
    "--mixed-precision",
    ...
]
```
and re-using that in the launch config
```
    "args": "${config:args}",
```
but it seems this is being detected as an incorrect type - which makes sense:
> In the first pass, all variables are evaluated to string results.

https://code.visualstudio.com/docs/editor/variables-reference

So I'd still welcome a way without having to duplicate all my launch configurations ;)

**Comment by ArturoDent** [comment]
I agree, I'm hoping that @isidorn has some guidance on the usage of `debug.startFromConfig` which would allow using just a reference to an existing launch config.  If not possible, I will open an issue.

It should work like the `runTask` command which does use a single argument referencing the task's `label` argument only.

**Comment by isidorn** [comment]
Actually this can be done by an extension.
Just use the `debug.startFromConfig` command and you can pass the full configuration. You would have to use node io to read launch.json and for each of the configuration contribute a command and a keybinding.
