### ISSUE TITLE
Console window opens when running code-insiders script on windows

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#97922]
Electron 8 exploration build

<img width="678" alt="capture" src="https://user-images.githubusercontent.com/1931590/82062218-164e1e80-96ca-11ea-9238-6d138efb57e5.png">

**Comment by bpasero** [comment]
I have never seen this.

**Comment by dbaeumer** [comment]
@bpasero I started VS Code from powershell using `C:\apps\VSCode\electron8\bin\code-insiders`. If I do `C:\apps\VSCode\electron8\bin\code-insiders.cmd` (observe the `.cmd` extension) no cmd window is shown.

**Comment by dbaeumer** [comment]
Doesn't happen with normal insider.

**Comment by deepak1556** [comment]
Thanks for testing!

> Doesn't happen with normal insider.

Did you try running with the absolute path to script file `C:\Users\demohan\Local\AppData\Programs\Microsoft VS Code.- Insiders\bin\code-insiders` ?

Console window will show up for the normal insiders as well, but running just `code-insiders` won't.

This has always been the case, seems to be an issue from the `code-insders` script not `code-insiders.cmd` sciprt.

I am not sure how path to the script makes a difference, would like some powershell expert to shed more light on this.

**Comment by deepak1556** [comment]
Can use `ELECTRON_NO_ATTACH_CONSOLE` when using `code-insiders` script to avoid the shell.
