### ISSUE TITLE
The term 'Checkpoint-Computer' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by bobmaars** [microsoft/vscode#97923]
Issue Type: <b>Bug</b>

I've just moved from ISE to Visual Studio Code: Nice work fellows, I do like the NEW interface and the ability to select the language and install the appropriate language modules... Yeah, it's kinda been there but I'm just saying it's a great improvement over ISE... I Used similar MS Visual Studio tools a number of years back... Nicely done...
Ok I've had a Checkpoint-Computer script that I use to run "AdHock" checkpoints that's been running for at least 6 years. This still works great using Powershell 5, but I think I'm missing the module for Microsoft.PowerShell.Management in the new version 7.  So I tried the following:
Find-Module -Name * | Out-GridView   #Note: Takes a long time and there are hundreds... Choose wisely! - I wanted to see all that was available to me.
Get-Module -ListAvailable -All | Out-GridView # same again see what's there...
Find-Module -Name *CheckPoint* | Install-Module -Force -Verbose
e.g.: Checkpoint-Computer -Description "MODIFY_SETTINGS" -RestorePointType MODIFY_SETTINGS
error: Checkpoint-Computer : The term 'Checkpoint-Computer' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
So it looks like (obviously) I'm missing a bunch of modules I'd previously installed way back for ISE and PS5, that are missing from Powershell 7.
Question: Is there a way that I can list all Installed Modules on both versions 5 and 7 and install only the missing modules.?
What am I missing?

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 1995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.44.2
powershell|ms-|2020.4.0

</details>

**Comment by alexdima** [comment]
Thank you for the kind words. Please create the issue directly against the PowerShell extension at https://github.com/PowerShell/vscode-powershell

**Comment by bobmaars** [comment]
Awesome, thanks:  I've just posted a request for this..
