### ISSUE TITLE
Decouple VS Code to platform(engine) and VS Code

### ISSUE THREAD

**Issue by Serhioromano** [microsoft/vscode#97926]
Recently I came across Azure Data Studio and I was amassed that it is done as VS Code. As I understand they share some code. Because even extension works of the same format. For those who are not aware here is screenshot.

![2020-05-15_21-40-56](https://user-images.githubusercontent.com/650741/82069251-d7818e00-96f4-11ea-97ad-94aa9a0fde69.png)

You know InteliJ IDEA has MPS. This is their engine. All IDEs build based on it. PhpStorm, WebStorm, you name it. All those IDEs share same UI and set of core functionality. And MPS is free. You can use it to create IDE for your own language.

But Azure Data Studio went further. It is not only IDE for language development it is IDE for DB management. Another words VS Code became a base for another app. I have few project that I would gladly make look like VS Code.

Is it possible to decouple VS Code to lets call it UI engine and VS Code that is build on top of UI Engine. So that other people can benefit and use UI engine to create their own apps. For instance I have a task to create application that calculate calories and report nutrients in different types of food. I see it perfectly well in VS Code like UI. 

Would be cool to install UI Engine, write few lines of code in VS Code and you have already a desktop app that looks like VS Code and benefit of all its goodies like themes, preference manager, etc...
 
In Microsoft is planning to build more of those apps the same style, they will first benefit from his approach.

**Comment by egamma** [comment]
@Serhioromano I'm glad that you like Azure Data Studio. 

>Is it possible to decouple VS Code to lets call it UI engine and VS Code that is build on top of UI Engine. So that other people can benefit and use UI engine to create their own apps. 

The idea is good, but we currently do not have the resources to invest into this, sorry.
