### ISSUE TITLE
Search Module "files to include" is case sensitive. Request for case insensitive, or a toggle.

### ISSUE THREAD

**Issue by battarro** [microsoft/vscode#97929]
On the search module, the "files to include" portionis case sensitive on the files name
for example I was trying to find something in any of my test files, so I was using
*test*.* as the search criteria, but I got no results. I had to use *Test*.* instead

This is contrary to Windows behaviour where files are case insensitive. 
for example if I do a `dir *Test*.*`  vs  `dir *test*.*` they both return the same results.

I understand that unix is not like this, so can you include a button/setting to turn this on and off, similar to the one on the text search box?

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/10633
