### ISSUE TITLE
Add "Add all Missing Imports" to JavaScript files

### ISSUE THREAD

**Issue by wesbos** [microsoft/vscode#97925]
JavaScript files already have auto-import and it works really well, but it's missing the "Add all missing Imports" feature that `.ts` files get. 

Take this code for example:

```js
const OrderContext = React.createContext();

const OrderProvider = function({ children }) {
  const [order, setOrder] = useState();
  return (
    <OrderContext.Provider value={{ order }}>{children}</OrderContext.Provider>
  );
};

export default OrderContext;
export { OrderProvider };
```

You can go 1-by-1 and import the following:

`import React, { useState, useEffect } from 'react';`

If you go to a missing import, and hit ⌘+. to bring up the code actions on a `.ts` file, it gives you "add all missing imports":

<img width="604" alt="Screen Shot 2020-05-15 at 11 23 21 AM" src="https://user-images.githubusercontent.com/176013/82068156-a460df80-969f-11ea-82b2-59d74b1a6da6.png">

Rename that file to `.js` and that feature is missing:

<img width="334" alt="Screen Shot 2020-05-15 at 11 18 54 AM" src="https://user-images.githubusercontent.com/176013/82068197-b17dce80-969f-11ea-9c35-f69be187a782.png">

I could be wrong, but it seems like the tech is there, can we get this code action added for .js files too?

**Comment by mjbvz** [comment]
This is already available when you [enable type checking in JS files](https://code.visualstudio.com/Docs/languages/javascript#_type-checking)

It can be difficult to correctly resolve symbols in JS files, so we don't show 'add missing import'  and other quick fixes by in plain, unchecked JS. These actions would end up showing in places they should not an also may break your code if you use them without understanding their impact. By enabling type checking, a user opts into using a stricter code structure so we can make more assumptions and show more potential fixes
