### ISSUE TITLE
Contributed tasks don't run from Ctrl+P > task menu

### ISSUE THREAD

**Issue by joelspadin-garmin** [microsoft/vscode#97937]
Issue Type: <b>Bug</b>

When running a task contributed by an extension from Ctrl+P > "task", then expanding one of the contributed task groups and selecting a task, nothing happens.

**To reproduce:**

1. Clone https://github.com/joelspadin-garmin/vscode-private-extension-manager and open the code workspace.
2. Press Ctrl+P and type "task" followed by a space.
3. Under the "contributed" section, select "npm"
4. Select the "npm: install extension" task.

**Expected behavior:** a new terminal opens and runs "npm install" in the extension folder.

**Actual behavior:** nothing happens.

If I use **Ctrl+Shift+P > Tasks: Run Task** instead and then select the task the same way, the task runs.

This continues to happen even with all extensions disabled, just using the tasks provided by built-in extensions. It also happens for any contributed tasks, as I originally discovered this when trying to write a new extension that contributes `taskDefinitions`.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980XE CPU @ 3.00GHz (36 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.71GB (35.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
@joelspadin-garmin thank you for filing this issue! You can get the fix ahead of our regular stable release by installing the [insiders build](https://code.visualstudio.com/insiders/). It installs side by side with stable.

**Comment by joelspadin-garmin** [comment]
Thanks!
