### ISSUE TITLE
Clicking on settings does not clear online settings

### ISSUE THREAD

**Issue by UltraKenchie** [microsoft/vscode#97936]
- VSCode Version: 1.45.1
- OS Version: Windows 10 18363

Steps to Reproduce:

1. Go to Online Services Settings (File > Preference > Online Services Settings)
2. Go to Settings (File > Preference > Settings or CTRL + ,)

Going to settings should clear the the search from online services settings tag

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
I'm not sure that it should do that. If I type in a search term then run the command to open the settings editor, I expect it to focus the settings editor with the search term still there. So I think in this case it should open the settings editor and the user can clear the search term if they want to. We even added a button for clearing the search recently.
