### ISSUE TITLE
Allow to open a workspace without closing the current window

### ISSUE THREAD

**Issue by ppo** [microsoft/vscode#97931]
Issue Type: <b>Feature Request</b>

Currently, when opening a workspace (via `Open Workspace…` and `Open Recent`), it closes the current window and opens the workspace in a new window.  
So currently, if I want to open several workspaces, I've to open a new window and then opening the workspace.

I doesn't seem to be a bug so I guess it's a "feature" :wink:  
So please add a preferences setting to change that behavior.

The behavior is not the same when opening a workspace from the command line (`code xxx.code-workspace`). In that case, it opens the workspace in a new window, leaving all the other windows open.

VS Code version: Code - Insiders 1.46.0-insider (e1d8f5155c0db5ffdc130c9aa0f14efac02dfdfb, 2020-05-13T20:32:52.338Z)
OS version: Darwin x64 19.4.0

**Comment by RandomShaper** [comment]
I'm not sure this is related, but until the last update I was able to open a recent folder/workspace in a new window by holding Shift.

- It has stopped working for me on Windows in v. 1.45.1.
- It still works for me on Linux (v. 1.45.0).

**Comment by ppo** [comment]
@RandomShaper Not working on Mac v1.45.1.

**Comment by bpasero** [comment]
Configurable via `"window.openFoldersInNewWindow": "on"`

**Comment by WestXu** [comment]
So is it a bug of the current release? Holding shift works in previous builds, and it was really convenient. Why is this issue closed?

**Comment by bpasero** [comment]
@WestXu see https://github.com/microsoft/vscode/issues/97237

//cc @sbatten

**Comment by MrEduar** [comment]
> Configurable via `"window.openFoldersInNewWindow": "on"`

Thanks you so much!! I thought this functionality had been removed. You should leave it on by default.

**Comment by ppo** [comment]
But with that, it always blindly opens a new window, even if we're on a blank window 😕 (just saying but Atom handles that perfectly)

**Comment by MrEduar** [comment]
> But with that, it always blindly opens a new window, even if we're on a blank window 😕 (just saying but Atom handles that perfectly)

Damn right. I hadn't noticed. That's too bad. How can I mimic behavior before these updates? I want to open the recent projects in a new tab just by pressing the ctrl key. When I click on it I usually want the project to open in the same window. What happened? Why did it change?
