### ISSUE TITLE
The Update messed up the colour in formatting

### ISSUE THREAD

**Issue by aniket-chowdhury** [microsoft/vscode#97934]
We have written the needed data into your clipboard because it was too large to send. Please paste.How is it that an update that was supposed to supposed to quicken the formatting does not format the document at all.

I copied some code from one file, created another pasted it and the blighter would not use colours to format the document it.

**Comment by alexdima** [comment]
@aniket-chowdhury Can you please include some clear steps and follow the issue template?

**Comment by aniket-chowdhury** [comment]
I don't know it just glitches some times and some times it works fine. I will close this issue. It seems internal.
