### ISSUE TITLE
Opening already opened editor should update its title

### ISSUE THREAD

**Issue by Huachao** [Microsoft/vscode#9794]
- VSCode Version: 1.3.1
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1.When my extension has following code, while the `previewUri` is fixed for each time, the title of preview pane is always the value of the first time.
```typescript
commands.executeCommand('vscode.previewHtml', previewUri, ViewColumn.Two, `${Date.now()}`).then((success) => {
                }, (reason) => {
                    window.showErrorMessage(reason);
                });

**Comment by jrieken** [comment]
@bpasero If I make the `HtmlInput` override `matches` to take also the name into account this works, tho I doubt it's the right fix. We don't do this anywhere and also it will open a new tab each time. Is there a way to tell the editor one open to update the title from the input?

**Comment by bpasero** [comment]
@jrieken I see the problem and overriding matches is not good for this so we need some API on the editor service to update the title of an existing editor.

I wonder if it already works using the `forceOpen` option? This will cause the editor to be replaced even if it is already opened. Though I am not sure this is the best choice if the title is updating frequently.

**Comment by bpasero** [comment]
Best solution is to update the title for an editor when an extension asks to open it. Currently we just ignore this request when the editor is already opened.

**Comment by Huachao** [comment]
@bpasero I still found the problem in my code, when I want to preview the same uri with different title, the sample code is still like
```typescript
commands.executeCommand('vscode.previewHtml', previewUri, ViewColumn.Two, `${Date.now()}`).then((success) => {
                }, (reason) => {
                    window.showErrorMessage(reason);
                });
```

**Comment by bpasero** [comment]
@Huachao so you say it does not work for you with 1.5?

**Comment by Huachao** [comment]
Yes.

**Comment by bpasero** [comment]
@Huachao can you attach the full extension workspace for me to reproduce what happens?

**Comment by Huachao** [comment]
Oh, @bpasero , I found that the title really changed of vs code window, but what I also want to change is the title of the tab.

**Comment by bpasero** [comment]
@Huachao yeah that should work, so please can you share your extension?

**Comment by Huachao** [comment]
@bpasero my extension source code is [here](https://github.com/Huachao/vscode-restclient), you can update this [line](https://github.com/Huachao/vscode-restclient/blob/master/src/controllers/requestController.ts#L78) to 
```typescript
await commands.executeCommand('vscode.previewHtml', previewUri, ViewColumn.Two, `Response-${response.elapsedMillionSeconds}ms`)
```

**Comment by bpasero** [comment]
@Huachao can you give me some instructions how to set the extension up to make a request etc.?

**Comment by Huachao** [comment]
Hi @bpasero , I have sent you an email to you in your corp account, and you can directly install that version, it doesn't work as expected

**Comment by bpasero** [comment]
I can reproduce.

**Comment by bpasero** [comment]
Fix pushed for September. Best to verify with an extension that uses the HTML preview command with the same resource but different label multiple times, because that is the scenario for @Huachao

**Comment by Huachao** [comment]
thanks @bpasero, I tested it in insider build, and the issue is fixed.

**Comment by bpasero** [comment]
Awesome 👍
