### ISSUE TITLE
Text pointer almost invisible on dark theme (macOS)

### ISSUE THREAD

**Issue by nosenfield** [microsoft/vscode#97943]
The textfield pointer within VSCode properly inverts color when over the integrated terminal, but not when over the rest of the VSCode window and contrast outline is very faint. At any screen brightness less than full, pointer becomes nearly invisible. Issue not present in macOS Mojave 10.15.5 (has clear outline on pointer). See attached stills from screen captures. Possible resurgence of this issue: https://github.com/microsoft/vscode/issues/754

**macOS High Sierra 10.13.6**
<img width="1134" alt="Screen Shot 2020-05-15 at 3 31 40 PM" src="https://user-images.githubusercontent.com/24323176/82090164-0bdc5680-96c3-11ea-86e0-0b6248e167d0.png">
<img width="1134" alt="Screen Shot 2020-05-15 at 3 31 45 PM" src="https://user-images.githubusercontent.com/24323176/82090166-0c74ed00-96c3-11ea-9ce6-4de90aaa4469.png">

**macOS Mojave 10.15.5**
![Screen Shot 2020-05-15 at 4 02 34 PM](https://user-images.githubusercontent.com/24323176/82091709-db49ec00-96c5-11ea-87da-983efe57c041.png)

- VSCode Version: 1.45.1
- OS Version: macOS High Sierra 10.13.6

Steps to Reproduce:

1. set theme to any with dark background
2. open new file, move pointer over file view

Does this issue occur when all extensions are disabled?: Yes

**Comment by dmaixner93** [comment]
I hate to sound like I am over complaining on this issue.

I believe the cursor displayed in the Terminal screenshot is best fix for this issue.

The cursor in the Mojave screenshot it too thick at times and covers letters.
