### ISSUE TITLE
The similar notifications appear again and again even If I close them. There should be a separate tab for notifications where a developer can see all the notifications.

### ISSUE THREAD

**Issue by TashikMoin23** [microsoft/vscode#97948]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Version, platform, source of the notifications. They may be coming from one of your extensions, but you haven;t given us any information about what extensions you are using, nor if you retried with all extensions disabled.
