### ISSUE TITLE
Install Path not found - VS 2017, 2019, and any workloads or any modify, repair or install

### ISSUE THREAD

**Issue by retrorocketstudios** [microsoft/vscode#97947]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Launch the Installer from Windows or Console (w admin priv)
2. Attempt to install any workloads, or modify/repair any installation of VSStudio
3. Always get this error (have uninstalled and reinstalled 3 times)
[dd_setup_20200514235643_errors.zip](https://github.com/microsoft/vscode/files/4636998/dd_setup_20200514235643_errors.zip)
4. All Installs are on "C:\Program Files (x86)\Microsoft Visual Studio" (2017\Community and 2017\Community)

Does this issue occur when all extensions are disabled?: Yes

Matthew Weng
mbwdigital@gmail.com

**Comment by alexdima** [comment]
@retrorocketstudios Unfortunately, this repository is not about Visual Studio, but about Visual Studio Code.
