### ISSUE TITLE
Allow GitHub compatible HTML tags in markdown contexts

### ISSUE THREAD

**Issue by pfitzseb** [microsoft/vscode#97940]
It would be great if the set of HTML tags that work on GitHub also were allowed in `MarkdownString`s.
AFAICT, those are
```
h1 h2 h3 h4 h5 h6 h7 h8 br b i strong em a pre code img tt
div ins del sup sub p ol ul table thead tbody tfoot blockquote
dl dt dd kbd q samp var hr ruby rt rp li tr td th s strike summary
details caption figure figcaption
abbr bdo cite dfn mark small span time wbr
```
([source](https://github.com/jch/html-pipeline/blob/13057c4dcde5e769dd116682f1bed7e65e920b40/lib/html/pipeline/sanitization_filter.rb9)).

Some work in that direction is already happening in #97793.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Afeature-request
