### ISSUE TITLE
Each time you launch, the application version rolls back

### ISSUE THREAD

**Issue by Quorten-L** [microsoft/vscode#97945]
1. Open Visual Studio Code
2. Check the version (could be 1.40 always)
3. Check for update
4. Update 
5. Restart app 
6.The application version again changes to 1.40

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
