### ISSUE TITLE
Python Go to Definition not working

### ISSUE THREAD

**Issue by plade1** [microsoft/vscode#97955]
Issue Type: <b>Bug</b>

I opened a remote python repository and when I right click on a function or variable I don't see "Go To Defnition" option.

Also my gitlens extension is not working anymore.

This happened just after the most recent upgrade.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 19.4.0
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.23GB free)|
|Process Argv|-psn_0_4678774|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vscode_edgenode|
|OS|Linux x64 3.10.0-1127.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (16 x 2397)|
|Memory (System)|62.74GB (39.47GB free)|
|VM|100%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
gitlens|eam|10.2.1
python|ms-|2020.5.78807
markdown-preview-enhanced|shd|0.5.3
markdown-pdf|yza|1.4.4

</details>

**Comment by roblourens** [comment]
Do you have the python extension installed on the remote? Please open a separate issue on the gitlens repo for that issue, and give more details.

**Comment by plade1** [comment]
Thank you for the info. I actually uninstalled and reinstalled Python and Gitlens extensions on the remote and now they are working.
