### ISSUE TITLE
Git: Host Verification failed in "Remote - Containers"

### ISSUE THREAD

**Issue by floatingpurr** [microsoft/vscode#97954]
- VSCode Version:  1.45.1
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. Install Remote - Containers
2. Open an existing folder checked into git repo using a dev container in VSCode (such a repo should point to a private remote repository already reachable with your ssh key on the host).
3. Sync your code
4. You get the **Git: Host Verification failed.**

In order to make things work, I have to run `git fetch` in the consolle of the remote VSCode. After that, the connection to the repo with the key starts working properly (e.g., I can sync the code pressing the VSCode button)

Does this issue occur when all extensions are disabled?
Into the dev container I have no other extensions.

**Comment by joaomoreno** [comment]
#89829
