### ISSUE TITLE
json file auto-formats on save even though i turned off the format on save feature

### ISSUE THREAD

**Issue by BraveNewMath** [microsoft/vscode#97956]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I am working on a file with a .json extension

when i save it, it automatically indents. 

normally this would not be a problem,
except i need it to not autoformat because this is a special json file

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (3.96GB free)|
|Process Argv|--folder-uri file:///c%3A/projects/esri/Aspire-Elasticsearch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.2.0
vscode-angular2-files|ale|1.6.2
bracket-pair-colorizer-2|Coe|0.1.3
vscode-eslint|dba|2.1.5
xml|Dot|2.5.0
gitlens|eam|10.2.1
code-runner|for|0.10.0
sass-lint|gle|1.0.6
todo-tree|Gru|0.0.175
smarty|imp|0.3.0
Angular2|joh|9.1.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
aws-cli-configure|mar|0.3.0
git-graph|mhu|1.22.0
csharp|ms-|1.21.18
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2169
debugger-for-chrome|msj|4.12.6
qub-msbuild|qub|0.6.3
vscode-todo-highlight|way|1.0.4

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`
