### ISSUE TITLE
Notebook opens as resource with vscode-notebook scheme

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#97952]
- Open notebooks A and B in two tabs
- Reload the window
- A is persisted open
- Switch to B

![image](https://user-images.githubusercontent.com/323878/82100008-531c1480-96ce-11ea-800a-a5014d039908.png)

- Click B in the explorer
- It opens, but the open editor has a resource with `vscode-notebook` scheme, the hint for me is that relative paths to images can't be resolved

**Comment by rebornix** [comment]
It's already fixed in Insiders.
