### ISSUE TITLE
Automatically Change Color Theme based on Sun Rise/Sun Set, Times, etc.

### ISSUE THREAD

**Issue by tommymaynard** [microsoft/vscode#97950]
Up until recently, I always used a dark color theme in VS Code (love Monokai). Due to the pandemic, and working from the patio during the last few days, I'm simply had to switch to a light theme. It's become as close to mandatory as it ever will. I've found and fell in love with [Hop Light](https://marketplace.visualstudio.com/items?itemName=bubersson.theme-hop-light). This got me thinking.

Maybe it's because my iPhone can switch between dark and light themes based on sun rise/sun set, but I'd love to be able to do the same thing VSCode. I'd like to see Color Themes that would switch *for* me automatically. It could be bound to sun rise/sun set, or a minimum due to a hard-coded times in Settings/my settings.json file.

If this can't be done, I'd at least like to hear why? How often is the settings.json file evaluated? Just at program launch and saves, or what? More information around if something like this could be implemented would be great to read about.

**Comment by aeschli** [comment]
We already have setting that the themes changes along with the light / dark OS theme: `window.autoDetectColorScheme` along with `workbench.preferredDarkColorTheme` and `workbench.preferredLightColorTheme`

If you are looking for different themes form morning/evening/night, there are extensions that can do that, e.g. https://marketplace.visualstudio.com/items?itemName=freetonik.day-night-theme-switcher
The current theme comes out of settings.json and is updated whenever the (saved) file content of that file changes. Extensions also have API to change the settings.

Let me know if that works for you!

**Comment by tommymaynard** [comment]
That'll have to do. Thanks.
