### ISSUE TITLE
Pill badge text is off center

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#97960]
In the keybindings editor, I assume this is from the change to the "pill" badges. It looks a couple pixels off vertical center to me?

![image](https://user-images.githubusercontent.com/323878/82105222-d4c86e00-96df-11ea-9dce-b3267f7968e1.png)

**Comment by misolori** [comment]
@roblourens I'm assuming this is when you're zoomed in?

**Comment by roblourens** [comment]
No zoom, this is on a macbook retina display
