### ISSUE TITLE
Fix missing Windows setup languages

### ISSUE THREAD

**Issue by Hitnnan** [microsoft/vscode#97961]
@joaomoreno told me that I just need to install from zero VS Code, so that I need to setup Portuguese Brazilian when installing. Well, when I open the installer, the option pt-BR does not appear.
How can I make this good?
https://github.com/microsoft/vscode/blob/be61b7d3abc7e532ddacaa9e799b301c59aca4e6/build/win32/i18n/messages.pt-br.isl#L9

**Comment by joaomoreno** [comment]
Oh it seems we never really exported the pt-BR for the setup: https://github.com/microsoft/vscode/blob/master/build/win32/code.iss#L47-L57

**Comment by joaomoreno** [comment]
The following languages were missing: brazilian portuguese, hungarian and turkish.

**Verification:**

```
code-setup.exe /lang=brazilianPortuguese
code-setup.exe /lang=hungarian
code-setup.exe /lang=turkish
```
