### ISSUE TITLE
Replace doesn't show preview for multiple matches on same line

### ISSUE THREAD

**Issue by loren-jiang** [microsoft/vscode#97964]
- Version: 1.45.1
- OS: Linux x64 5.3.0-45-generic snap

Steps to Reproduce:

1. 'Find' string of interest that has matches on same line

See last line in picture:
![image](https://user-images.githubusercontent.com/24639810/82107451-a6955f00-96dc-11ea-8bb8-a41be604c15f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Matches on the same line always show as different entries in the search viewlet. The next line should be the second match in the same line, is it?

**Comment by loren-jiang** [comment]
You're totally right, my bad. 

Thanks for checking!
