### ISSUE TITLE
can not save .dart file

### ISSUE THREAD

**Issue by YYQ8023** [microsoft/vscode#97972]
Issue Type: <b>Performance Issue</b>

create a .dart file then save it , vscode will show "Saving 'test.dart':Runnind 'Dart' Formatter(configure)" long long time,and finally it doesn't saved.

VS Code version: Code - Insiders 1.46.0-insider (6849775440496504e0677ffcf2a46d47ad9130f5, 2020-05-15T09:06:06.454Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (2.52GB free)|
|Process Argv|-psn_0_4834460|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   14	    98	 23071	code-insiders main
   18	    66	 23074	   gpu-process
    0	    16	 23076	   utility
    2	   295	 23077	   window (spider.controller.ts — goushubao-server)
    0	   115	 23087	     extensionHost
    0	    66	 23105	       electron_node tsserver.js 
   32	   229	 23106	       electron_node tsserver.js 
    0	    66	 23117	         electron_node typingsInstaller.js typesMap.js 
    0	    49	 23112	       electron_node server.js 
    0	    33	 23113	       electron_node eslintServer.js 
    0	    33	 23159	       /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer) /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=23087
    0	    33	 23088	     watcherService
    0	    33	 23114	     searchService
   19	   279	 23078	   window (a.dart — sjtu-ele-pc)
    0	   147	 23086	     extensionHost
   84	   229	 23103	       /Users/raymonda/flutter/bin/cache/dart-sdk/bin/dart /Users/raymonda/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=VS-Code --client-version=3.10.1
    0	    33	 23089	     watcherService
    0	    33	 23096	     searchService
    9	   115	 23092	   shared-process
    0	     0	 23203	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
   40	    66	 23201	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (a.dart — sjtu-ele-pc)
|  Window (spider.controller.ts — goushubao-server)
|    Folder (sjtu-ele-pc): 142 files
|      File types: vue(63) js(24) DS_Store(4) svg(4) json(3) png(2)
|                  browserslistrc(1) editorconfig(1) gitignore(1) md(1)
|      Conf files: package.json(1)
|    Folder (goushubao-server): 835 files
|      File types: js(219) ts(210) map(207) less(6) pem(6) json(5) sh(5)
|                  crt(3) key(3) ejs(3)
|      Conf files: settings.json(1) gulp.js(1) package.json(1)
|                  tsconfig.json(1) tslint.json(1) webpack.config.js(1);
```

</details>
<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.10.1
flutter|Dar|3.10.1
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
prettier-vscode|esb|4.7.0
code-runner|for|0.10.0
todo-tree|Gru|0.0.175
vue-snippets|hol|0.1.11
dotenv|mik|1.0.1
vscode-language-pack-zh-hans|MS-|1.45.1
korofileheader|OBK|4.7.0
vetur|oct|0.24.0
vscode-javascript-booster|sbu|0.12.3
vue-vscode-snippets|sdr|1.9.0
vscodeintellicode|Vis|1.2.7
vscode-icons|vsc|10.1.1
vue|Wsc|0.0.3
material-theme|zhu|3.6.1

</details>

**Comment by jrieken** [comment]
This is likely caused by the dart extension itself, or by another extension. This issue is that you have enabled format on save, formatting is done by extensions and if it takes them really, really long you see this message. You can disable format on save again (also per language) and you should follow-up with the extension causes this (likely dart)
