### ISSUE TITLE
Pygame module issue

### ISSUE THREAD

**Issue by AE0n-exe** [microsoft/vscode#97977]
Issue Type: <b>Bug</b>

When I call any member on the "pygame" python module, an error appears : it looks like Visual Studio Code don't know any member of this module.
I've tried with 'init', 'KEYDOWN', & 'QUIT'.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) N4000 CPU @ 1.10GHz (2 x 1094)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.78GB (0.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.5.78807
pygame-snippets|tus|0.0.1
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by alexdima** [comment]
Please create an issue directly against the extension at https://github.com/Microsoft/vscode-python/issues
