### ISSUE TITLE
[css][html] Option to disable MDN Reference popups only (without effecting other functionalities)

### ISSUE THREAD

**Issue by megavolkan** [microsoft/vscode#97979]
Pretty please give us an option to disable ONLY and ONLY those 'MDN Reference' info boxes but NOT the hover boxes alltogether. 

Disabling Editor > Hover in Settings also disables other useful things like ColorPicker popup plugins depending on it etc. MDN info may be useful for some but most of the time it is just a HUGE annoyance for others. 

Taking this idea one step further MDN Reference may be removed alltogether and/or make it an optional download for whoever needs it. I know it is there to help but it is also a source of problem too eager to get in the way between you and your code.

**Comment by alexdima** [comment]
@megavolkan What programming language do you use? Do you use a specific extension?

**Comment by megavolkan** [comment]
Mainly HTML and CSS

**Comment by palbergstrom** [comment]
Would like to see the same. Very annoying.

**Comment by aeschli** [comment]
You are talking about the `MDN Reference` link, or the whole text?
![image](https://user-images.githubusercontent.com/6461412/85517356-74dab680-b5ff-11ea-83fa-86b5ca1ec6d3.png)

**Comment by megavolkan** [comment]
I'm talking about the whole "box". Very intrusive, popping all the time, blocking my way when i need to see or select some text, element etc. When i try to click with mouse to select some code and all of a sudden MDN reference box pops open, i find myself accidentally clicked the link, my default browser launches... I know i can set a longer delay for the box to open but some really useful plugins (like color picker) would be delayed too. Just because of this i returned to Atom editor.

**Comment by aeschli** [comment]
You can turn off the automatic hover (`"editor.hover.enabled": false`) and manually trigger it when you need it (e.g. for the colors): Command `Show Hover (Ctrl + K, Ctrl + I)`. Is that useful?
There are many extensions that provide hovers and ask each extensions author to provide settings for hover would work too, but might not happen for all extensions.

**Comment by megavolkan** [comment]
Sorry but not the same thing, hover functionality is really useful and very easy to get bits of information real quick (without key clicks or anything). If "hover" functionality is solely created for MDN Reference box in mind and other 3rd party plug-in developers kind of "hijacked" it for their own purpose then i can understand it would be a hard decision to "remove" or "disable" it from the codebase of VS Code. On the other hand if it is not the case and hover using plug-ins and MDN Reference hover boxes can coexist without effecting each other that means (at least to me) something is wrong with the logic the way this function is represented to users. It's looking like "You like hover? You'll have MDN whether you like it or not". 
Answer to your question: I know i can turn-off hover, i turned it off and regretted it because of the side effects with the plugins.  Using a color-picker (or whatever) with a hover gesture is way easy and way useful than enabling it with a key stroke. I stand by my request, i wish MDN Reference SHOULD be optional or better "opt-in" rather than mandatory.

**Comment by palbergstrom** [comment]
Agree with megavolkan. MDN Reference should be optional.

**Comment by aeschli** [comment]
If I understood correctly @megavolkan want's neither the `MDN Reference` link nor the description.

**Comment by megavolkan** [comment]
> If I understood correctly @megavolkan want's neither the `MDN Reference` link nor the description.

I'd prefer the MDN Reference popup (and yes naturally including MDN reference link and the description) totally gone. But NOT the hover+popup functionality which has a purposeful usacase for plugins.
By the way i'm not against the "MDN Reference" itself. I understand it may be helpful for those who would prefer to display it for some reason. Therefore it should be initially disabled and then enabled in the settings if need be.

**Comment by CocoThePimp** [comment]
> > If I understood correctly @megavolkan want's neither the `MDN Reference` link nor the description.
> 
> I'd prefer the MDN Reference popup (and yes naturally including MDN reference link and the description) totally gone. But NOT the hover+popup functionality which has a purposeful usacase for plugins.
> By the way i'm not against the "MDN Reference" itself. I understand it may be helpful for those who would prefer to display it for some reason. Therefore it should be initially disabled and then enabled in the settings if need be.

Completely agree. 

There are two different things, informations (MDN popup hovers), and tools (color picker).
MDN pop up is annoying, but color picker is awesome.

**Comment by samad-nasar** [comment]
I want to disable the whole MDN box pop-up and not the other pop-ups. A way to disable it?

**Comment by megavolkan** [comment]
> I want to disable the whole MDN box pop-up and not the other pop-ups. A way to disable it?

No. Not to my knowledge at least. This topic is aiming to make devs hear/acknowledge the issue and users demanding a solution.

**Comment by spartanatreyu** [comment]
It'd probably be better to pull the mdn hover functionality into it's own plugin that's installed by default (Built-in extension), but can be disabled independently.

That way it helps everyone in this thread above and could be updated/improved independently of vscode (for things like showing default css values).

**Comment by ldandriscoll** [comment]
I agree the general purpose of the pop up is good (e.g. color selector). I don't use the MDN reference but I see how people could find it useful. However, I cannot count the number of times I randomly clicked the MDN link and it's the only one annoying thing about VS code. I think other user suggestions of making it a third party plugin that people can choose to install is a great solution to this problem.

**Comment by AaronDeMent** [comment]
Maybe just change the delay to say something like 1000  that way if it is something you want it you can wait and it will show otherwise it gives you time to select something without it popping up right away.

**Comment by megavolkan** [comment]
> Maybe just change the delay to say something like 1000 that way if it is something you want it you can wait and it will show otherwise it gives you time to select something without it popping up right away.

I have tried it. It is not practical and doesn't address the main problem, just sliding it under the carpet.

**Comment by AaronDeMent** [comment]
I agree it would be nice to have the ability to remove just the MDN but setting the delay to 1000 actually solves my issue of accidentally clicking on it in a fast code entry instance. Just a thought not a perfect solution but for me it is better.

**Comment by samad-nasar** [comment]
I have increased the popUp delay to some 2000. Now it is not much annoying,
and i can get the reference too when necessary.

**Comment by rodwestmoreland** [comment]
> I agree it would be nice to have the ability to remove just the MDN but setting the delay to 1000 actually solves my issue of accidentally clicking on it in a fast code entry instance. Just a thought not a perfect solution but for me it is better.

Thanks for the tip - I didn't think about increasing the delay.  It isn't an actual solution, as mentioned, but it is much less annoying with a longer delay.  I'd rather wait a couple of seconds for something I need than to have it pop over what I'm looking at or accidently hitting that goofy MDN link.

**Comment by wireinet** [comment]
My God, just remove MDN – why is this such a problem? Can't developers make this an option? it's not clear who might need it at all!

**Comment by palbergstrom** [comment]
> My God, just remove MDN – why is this such a problem? Can't developers make this an option? it's not clear who might need it at all! The most unnecessary feature in the best editor! God, how annoying this pop-up window is and how annoying it is!

+1

**Comment by aeschli** [comment]
Should the option remove all of the info (1), or just the link (2)

![image](https://user-images.githubusercontent.com/6461412/85517356-74dab680-b5ff-11ea-83fa-86b5ca1ec6d3.png)

Please add your vote for (1) or (2)

**Comment by megavolkan** [comment]
> Should the option remove all of the info (1), or just the link (2)
> 
> ![image](https://user-images.githubusercontent.com/6461412/85517356-74dab680-b5ff-11ea-83fa-86b5ca1ec6d3.png)
> 
> Please add your vote for (1) or (2)

1

**Comment by spartanatreyu** [comment]
@aeschli Why not both?

Have an option with three different values:
- Full: Shows reference information and link (this is the current behaviour and should be the default)
- Compact: Continues to show helpful reference information while preventing the user from accidentally clicking at the wrong time and having their browser steal focus
 - None: No pop ups at all

**Comment by wireinet** [comment]
> @aeschli Why not both?
> 
> Have an option with three different values:
> 
> * Full: Shows reference information and link (this is the current behaviour and should be the default)
> * Compact: Continues to show helpful reference information while preventing the user from accidentally clicking at the wrong time and having their browser steal focus
> * None: No pop ups at all

Please tell me where this options you find

**Comment by spartanatreyu** [comment]
@wireinet This doesn't exist, I made it up as a possible solution to the issue.

**Comment by wireinet** [comment]
> @wireinet This doesn't exist, I made it up as a possible solution to the issue.

oh..sorry ))
Yes, that would be a very good solution and very handy!

**Comment by dimkzr** [comment]
Half a year and still no solution?
This MDN popup is the most annoying thing in the otherwise amazing editor.

**Comment by aeschli** [comment]
I added two new settings:
  "html.hover.documentation": false,
  "html.hover.references": false,

**Comment by ArturoDent** [comment]
It looks like the commit affects html but not css/scss.  Reading through the issue it doesn't appear to have been limited to html MDN references and documentation.  Are the same settings coming to css/scss?

**Comment by aeschli** [comment]
Yes, still working on that. That's why the issue is still open.

**Comment by vhanadium** [comment]
This does not work on the HTML and CSS in PHP too.

**Comment by aeschli** [comment]
For PHP you need to file the issue against the PHP extension that you use.

**Comment by vhanadium** [comment]
I meant that the MDN popup is shown on the HTML of a PHP file

**Comment by dimkzr** [comment]
That's probably because "html" there refers to file type, and not the language actually used.

**Comment by vhanadium** [comment]
It seems but "html.hover.documentation" and "html.hover.references" should work on every HTML and CSS content on every file type. That thing is a real pain !
