### ISSUE TITLE
No way to control multiple rename providers

### ISSUE THREAD

**Issue by gituser3000** [microsoft/vscode#97976]
- VSCode Version: 1.45.1

Steps to Reproduce:

1. Register additional rename provider in extension
```
    return vscode.languages.registerRenameProvider({ pattern: "**/*.ts"}, {
        async provideRenameEdits(document, position, newName, token){
```
2. Rename provider is not working for .ts files
In [$mol framework](https://github.com/eigenmethod/mol) we have files that are [compiled to .ts](https://tree.hyoo.ru/#compile)
I can register a rename provider for .myType->.ts. So renaming in my files leads to renaming in .ts. But i can not register .ts -> .myFile. 

There were multiple discussions about formatting, but renaming can not be controlled (with a flag for example).
https://github.com/Microsoft/vscode/issues/48695
https://github.com/microsoft/vscode/issues/41882

**Comment by jrieken** [comment]
Yes - currently there is only support for a single rename provider.
