### ISSUE TITLE
How to disable errors squiggles on any languages?

### ISSUE THREAD

**Issue by Imputes** [microsoft/vscode#97973]
I try this:
`"problems.decorations.enabled": false,`
But I still found that vscode can detect json syntax errors

**Comment by Imputes** [comment]
Oh, I found settings about this is in settings extensions, sorry

**Comment by alexdima** [comment]
@Imputes Do you still have an issue or have you been able to resolve it by yourself?

**Comment by Imputes** [comment]
As shown in this picture:
![image](https://user-images.githubusercontent.com/12896162/82119189-1542ed00-97af-11ea-934d-76b4fe6fa509.png)
I don't want to have this error message and the mouse pointer will display information when hovering.
I tried setting the JSON option of extensions in settings, but there is no error check option.
![image](https://user-images.githubusercontent.com/12896162/82119265-8b475400-97af-11ea-80d1-5aa858488715.png)
So I don’t know how to achieve the effect I want

**Comment by Imputes** [comment]
I hope to read and write the file, put it in vscode to do it, and the rest is done by the terminal.
If this setting cannot be achieved, forget it, thanks for your reply

**Comment by alexdima** [comment]
@Imputes  On line 45 you are lacking a comma

**Comment by Imputes** [comment]
Do you know how to solve [this](https://developercommunity.visualstudio.com/content/problem/459820/cant-open-folder-in-vs2019.html) problem, thank you

**Comment by Imputes** [comment]
> @Imputes On line 45 you are lacking a comma

I know, that's what I did intentionally, just to see if vscode can detect errors. What I want is that vscode does not detect task errors.

**Comment by alexdima** [comment]
> What I want is that vscode does not detect task errors

You can disable the builtin JSON extension that creates this errors.
