### ISSUE TITLE
Issue on showing nested array when Persian letters exist in it

### ISSUE THREAD

**Issue by mhlm71** [microsoft/vscode#97971]
Issue Type: <b>Bug</b>

When there are Persian letters in a nested array, following example is shown mistakenly:

var list = [['0101', 'عید نوروز'], ['0102', 'عید نوروز']];

While example above is shown almost truly in Note Pad++.

If it's written by English letters it will be like this:
var list = [['0101', 'xxx'], ['0102', 'yyy']];

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3210 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (2.22GB free)|
|Process Argv|C:\Users\g.karbasiun\Desktop\Login\index.html|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by rzhao271** [comment]
It still shows up differently in VS Code, and it's hard to actually select the string.

In the following screenshot, I managed to select one of the strings, but it wasn't in a very intuitive way:
![Demo showing the behaviour is still broken](https://user-images.githubusercontent.com/7199958/159591344-0d6548dc-6704-4512-ac1b-97811ab943ea.PNG)

**Comment by alexdima** [comment]
@rzhao271 The fix is helpful only if the text is syntax highlighted. By pasting it outside a `<script>` tag, this text is basically plaintext and then plaintext bidi layout rules kick in. We only override the default bidi layout rules when having multiple tokens in the text. So to verify, you would need to use a JS file or paste inside a `<script>` tag.
