### ISSUE TITLE
In python notebook the curser is in offset then the real position in text

### ISSUE THREAD

**Issue by tzoof** [microsoft/vscode#97978]
Issue Type: <b>Bug</b>

I'm connected via ssh to remote machine
When I am connected for a while or the vscode is open for a while (I never use it without ssh so can't separate) 
In python notebook, when selecting some part of the code the curser is showing me position x while it is actually on position x-2 or x-3 or sometime even x+1
That makes it really annoying to write.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.0.0-1036-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (11.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|29%|

|Item|Value|
|---|---|
|Remote|SSH: <dns name>|
|OS|Linux x64 5.0.0-1036-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (12 x 2593)|
|Memory (System)|220.39GB (4.73GB free)|
|VM|0%|

Fetching remote diagnostics for 'ssh-remote+<dns name>' timed out.
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
gc-excelviewer|Gra|2.1.34
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.5.78807
vscode-yaml|red|0.8.0

</details>

**Comment by alexdima** [comment]
Please create an issue directly against the extension at https://github.com/Microsoft/vscode-python/issues
