### ISSUE TITLE
auto suggestion is annoying

### ISSUE THREAD

**Issue by fssrepository** [microsoft/vscode#97986]
Issue Type: <b>Bug</b>

I hate the IntelliSense, when I'm trying to make a new line, and the enter picking the first suggested word from the drop-down list. My heart rate just going up, it's not healthy, that what i have entered will be noticed later. I disabled this feature also on the phone. (it's pretty annoying also, when you are using different language, and it's changing your words completely, to delete back takes more time, just to leave the whole feature)

However I would suggest, don't pick up the first suggested world on entering (just when using arrows), however, you can show the popup.

It's pretty annoying on chrome also, when you would like to remove part of the URL, and you can't just delete the whole or load the subpage first.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:10:24.511Z)
OS version: Linux x64 4.15.0-99-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2921)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.59GB (11.30GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.12.0
Gradle|caz|1.1.2
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
xml|Dot|2.5.0
gitlens|eam|10.2.1
tsl-problem-matcher|eam|0.1.1
vscode-livescript-preview|ehe|1.1.0
LogFileHighlighter|emi|2.8.0
prettier-vscode|esb|4.7.0
code-runner|for|0.10.0
todo-tree|Gru|0.0.175
svg|joc|1.1.8
vscode-svg-dev|kon|0.8.16
git-graph|mhu|1.22.0
code-beautifier|mic|2.3.3
mongodb-vscode|mon|0.0.2
vscode-docker|ms-|1.2.0
python|ms-|2020.5.78807
azure-account|ms-|0.8.11
cpptools|ms-|0.28.0
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
createGUID|nwa|0.0.2
livescript|pse|0.1.1
java|red|0.61.0
vscode-yaml|red|0.8.0
vscode-hexdump|sle|1.7.2
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.1
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.22.4
vscode-proto3|zxh|0.4.2

</details>

**Comment by jrieken** [comment]
>  My heart rate just going up, it's not healthy, 

Then this will be good for your health: `"editor.acceptSuggestionOnEnter": "smart"`

**Comment by fssrepository** [comment]
Thank you doctor, you saved my life. :)
