### ISSUE TITLE
running highlighted python script results in errors whereas running the script in terminal runs without issue

### ISSUE THREAD

**Issue by cyrusmaz** [microsoft/vscode#97989]
Issue Type: <b>Bug</b>

## REPRODUCING THE BUG: 
type python3 in the VSC terminal to open up a python shell,
paste the following code into a new file, highlight everything (e.g. with command+A on Mac) and press Shift+Enter (on Mac) to run the highlighted code.

## SCREENSHOTS:
exhibit 1:
![image](https://user-images.githubusercontent.com/60046238/82123984-56fd7480-976a-11ea-95bc-d0d0f55e825d.png)
exhibit 2:
![image](https://user-images.githubusercontent.com/60046238/82123989-5f55af80-976a-11ea-8850-5f5155cb4fac.png)
exhibit 3:
![image](https://user-images.githubusercontent.com/60046238/82123993-6381cd00-976a-11ea-987e-26366ec3e6c0.png)
exhibit 4:
![image](https://user-images.githubusercontent.com/60046238/82123996-67155400-976a-11ea-97d8-79ac1da7c104.png)

## EXPECTED RESULTS: 
there is nothing logically or syntactically incorrect about the code above. If you run the entirety of the script in the terminal (python3 script.py) or even pressing the green triangle button on the top right, it runs without issue. 

## INTERESTINGLY: 
this error doesn't play out in the exact same manner each time. i have attached screenshots of various ways it happened while i was filling out this issue report. in fact sometimes there is no error at all, but usually there is. 

## LASTLY:
this is the simplest code i could produce that demonstrates this bizarre issue. but it's been happening in all my work recently. disabling all extensions seemed to make the issue disappear at first, but it re-emerged as badly as ever.

similar issue was raised in 2017 ( #https://github.com/microsoft/vscode-python/issues/259) but the thread was closed as resolved. 

## CODE: 
```

import numpy as np
import pandas as pd

task1={
    'aaa' :       "random", 
    'bbbbb' : 25,
    'cc' :   "random2",
    'd_d_d' :   "random3",
    'ee_eeee' :        False}



task2={
    'aaa' : "x", 
    'bbbbb' : 5,
    'cc' : "random2",
    'd_d_d' : "random3",
    'ee_eeee' : False}

task3={
    'aaa' : "random", 
    'bbbbb' : 25,
    'cc' : "random2",
    'd_d_d' : "random3",
    'ee_eeee' : False}

task4={
    'aaa' : "y", 
    'bbbbb' : 5,
    'cc' : "random2",
    'd_d_d' : "random3",
    'ee_eeee' : False}



task5={
    'aaa' : "random", 
    'bbbbb' : 25,
    'cc' : "random2",
    'd_d_d' : "random3",
    'ee_eeee' : False}

task6={
    'aaa' :       "z", 
    'bbbbb' : 5,
    'cc' : "random2",
    'd_d_d' : "random3",
    'ee_eeee' : False}

task7={
    'aaa' : "random", 
    'bbbbb' : 25,
    'cc' : "random2",
    'd_d_d' : "randojkhm3",
    'ee_eeee': False}

task8={
    'aaa' : "x", 
    'bbbbb' : 60,
    'cc' : "random2",
    'd_d_d' : "random3",
    'ee_eeee' : False}


one_round = [task1, task2, task3, task4, task5, task6, task7, task8]



pd.DataFrame(one_round)

```

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz (4 x 1300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.5.78807

</details>

**Comment by Tyriar** [comment]
Unconfirmed
