### ISSUE TITLE
docker-compose task `failed to launch` when type is `process`.

### ISSUE THREAD

**Issue by MicahZoltu** [microsoft/vscode#97981]
I have been using a `docker-compose` task for some time.  Today I updated both my version of Windows 10 to major update 1909 and I also updated Docker for Windows to latest.  When I try to run my `docker-compose` task that used to work just fine, I now get the following error:
```
> Executing task: C:\Program Files\Docker\Docker\resources\bin\docker-compose  <
The terminal process command 'C:\Program Files\Docker\Docker\resources\bin\docker-compose' failed to launch (exit code: {2})
```
If I change the task to `shell` instead of `process` it works, and if I run `docker-compose` in a powershell window it also works fine.

Changing the task `command` to `cmd` also works fine, so it seems to be something related to how `docker-compose` is working relative to how `VSCode` expects `docker-compose` to work.

### VSCode/Windows version:
```
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z (2 days ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

### Docker version:
```
Docker Desktop Community: 2.3.02
Docker Engine: 19.03.8
Docker Compose: 1.25.5
```

### Steps to Reproduce:
1. Create a new folder.
2. Create a subfolder called .vscode
3. Create a file in that subfolder called tasks.json
4. Put the following in it:
    ```
    {
        "version": "2.0.0",
        "tasks": [{
            "label": "temp",
            "type": "process",
            "command": "docker-compose",
            "problemMatcher": [],
        }],
    }
    ```
5. Open the folder in VSCode.
6. In the command pallet choose Tasks: Run Task
7. Choose temp from the list.

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

**Comment by alexr00** [comment]
Thank you for the clear repro steps! I think there probably used to be some kind of mapping between `docker-compose` and `docker-compose.exe`. If I throw a `.exe` on the end of your `command` it works.

I'm guessing that `docker-compose` is still somehow mapped to `docker-compose.exe`, but that it isn't a mapping that the task system can take advantage of. Is adding the `.exe` a reasonable solution for you?

**Comment by MicahZoltu** [comment]
That does appear to fix the issue.

It is a bit odd that I don't need `.exe` on `cmd`, and the inconsistency is confusing for me (as a user).  It would be nice if VSCode was consistent in its demand for file extension or not, or it was consistent with a command/powershell prompt.  Having to guess which things need an extension and which don't and having the documentation leave off the extension in examples is confusing.
