### ISSUE TITLE
Print Dialog Appearing intermittently when opening quick-nav: cmd-p

### ISSUE THREAD

**Issue by nerique** [microsoft/vscode#97983]
- VSCode Version: 1.45.1
- OS Version: macOS Catalina v10.15.4

Steps to Reproduce:

1. Launch Project
2. Enter Quick-Nav shortcut Cmd-P (⌘-P)
3. Print Dialog appears over Quick-Nav Menu (BAD)
4. Close Print Dialog
5. Enter Quick-Nav shortcut again
6. Print Dialog does not appear
7. Switch to another app and switch Back
8. Process repeats 

Seems to occur most reliably after first launching, or after switching back into VSCode from another app. Using Cmd-Tab reproduces the problem more reliably than switching apps with the mouse

Videoscreen :

https://share.getcloudapp.com/geuWKOkW

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
This does not sounds like something VSCode triggers or can fix. I suggest you check if maybe you have a global shortcut defined in your OS that triggers this?

**Comment by JacksonKearl** [comment]
I'm also seeing this, for me it just started with the last update to insiders.

**Comment by JacksonKearl** [comment]
In my case my OS was acting up about a lot of things (randomly spawning apps with no user interaction, for instance). Restarting fixed that and this.

**Comment by nerique** [comment]
I had the same behaviour. A restart fixed the issue.

*JULIEN* BALMONT

CTO & Co-fondateur

+33.6.62.66.91.38

zenchef.com ( https://bit.ly/2lwukWJ ) Blog tech & product ( https://medium.com/zenchef-tech-and-product )

( https://bit.ly/2mXu3cr ) ( https://bit.ly/2mNbGtK ) ( https://bit.ly/2mNbGtK ) ( https://bit.ly/2mXu3cr ) Icone LinkedIn ( https://bit.ly/zenchef-linkedin )

Sent via Superhuman ( https://sprh.mn/?vip=julien@zenchef.com )
