### ISSUE TITLE
Feature Request: Preserve Case - Find / Replace

### ISSUE THREAD

**Issue by shaneparsons** [microsoft/vscode#9798]
It'd be awesome if a **preserve case** feature was eventually added to the find/replace functionality!

ST3's implementation of it is a good example if you need one.

**Comment by peabnuts123** [comment]
This would be life-changing

**Comment by axefrog** [comment]
Example: currently implementing an immutable red/black tree, and there is an if/else statement, with each branch containing a mirror of the other branch. To implement the second branch, I need to replace all instances of "left" with "right" and vice versa. This includes:

- left/right (local variable)
- Left/Right (part of a function name)
- LEFT/RIGHT (a constant indicating branch direction)

A case-insensitive replacement operation would make this doable in one step. Instead, I have to first replace each case of _left_ with _foo_ (3 steps). Next I replace each case of _right_ with _left_ (3 more steps). Finally, I replace _foo_ with _right_, for a total of 9 steps. With case insensitive replacement, it'd be 3 steps total.

**Comment by rebornix** [comment]
Let's track the setting persistence in #6158

**Comment by ant31** [comment]
@rebornix I think this is not a duplicated issue. 
The issue #6158 is about 'saving' the setting. 
This issue (from what I read) is about keeping the case for the replaced word (default in emacs)
eg: 
```
foo-bar
FOO-BAR
Foo-Bar
```
```
// find: foo-bar
// replace: keep-case
keep-case
KEEP-CASE
Keep-Case
```

```

**Comment by axefrog** [comment]
@ant31 The feature is/would be per-character, not per word, which means your example would resolve as:

```
// find: foo-bar
// replace: keep-case
keep-case
KEEP-CAse
Keep-case
```

**Comment by rebornix** [comment]
Sorry for closing it too fast and Thank you for making it clear, it's a valid feature request.

**Comment by vilic** [comment]
Just wrote a simple extension that covers some use case. Check out https://marketplace.visualstudio.com/items?itemName=vilicvane.sensitive-replace

**Comment by alexgvozden** [comment]
this should work exactly like described in case when using Cmd + D , Add selection to Next Find 

there are so many situations in using camel case / hungarian notation where it would be useful... 

hope it gets built in ? :)

**Comment by peabnuts123** [comment]
@vilic 's extension looks almost perfect, it just needs to be across an entire project 👍

**Comment by mrahhal** [comment]
While an extension can get the job done, being built into the Find/Replace window would be ideal, with an option right next to "Use Regular Expressions", that searches in the entire file.

This hasn't been active in a long while. Is this not planned anymore? This would truly be a life changer.

**Comment by slinstj** [comment]
It would be really appreciated! PHPStorm has this feature for at least 2 years.

Unfortunatelly, the extension (even being good) does not get the job done in my case (pun not intended) because so many times I have to search/replace *over all project's files*, not only on a selected text.

**Comment by xKloc** [comment]
Really need this. I'm having to do 3 find and replaces where a case preserve would make it only 1.

Find: foo
Replace: bar

FOO->BAR
Foo->Bar
foo->bar

**Comment by theodore-q** [comment]
I too would really like this functionality

**Comment by JasonWThompson** [comment]
The way Eclipse does this is through a regex replace token \C.

So I can search for foobar and replace it with \Cbazqux and it will work as expected.

**Comment by gui679** [comment]
Why the freak this is not implemented yet ?

**Comment by gmosx** [comment]
This is an extremely useful feature, I love the implementation in WebStorm.

**Comment by gmosx** [comment]
@barnc : [Open Source is Not About You](https://gist.github.com/richhickey/1563cddea1002958f96e7ba9519972d9>)

**Comment by barnc** [comment]
@gmosx if you’re going to leave sarky single link comments I’d recommend making sure said links don’t 404, hth.

**Comment by ant31** [comment]
> not qualify as an excuse for it

As far as I know, they don't owe you an excuse to NOT implement a feature. 
Plus who are 'they'? It's an opensource project with 700+ contributors!  maybe it's time for you to contribute too instead of whining?

**Comment by Eccenux** [comment]
It's not just any open source project. And not everyone can contribute. It's an important project of Microsoft connected with their effort do being nice to devs again and with their effort to spread TypeScript (among other things I guess).

But... Yet another comment with _why is this not implemented_ is not helpful for devs. Just add +1 to the initial comment and maybe some PM from Microsoft will finally make time to do this.

**Comment by clshortfuse** [comment]
I just found out that Mac OS X has something called "Paste and Match Style" which defaults to `Shift+Cmd+V`. I think this can be used, if you can consider the capitalization of a word to be its "style".

**Comment by BillDenton** [comment]
Nearly 3 years. Is there any hope of this getting implemented?

**Comment by itsafire** [comment]
Today was my day to really try vscode. I'm back to emacs with its case aware search and replace. This feature is really very important for refactoring. The current implementation can do harm your code.

**Comment by alexplummer** [comment]
> Today was my day to really try vscode. I'm back to emacs with its case aware search and replace. This feature is really very important for refactoring. The current implementation can do harm your code.

Seems a tad overly dramatic no? If it really is such a game changer and so vital for refactoring, why not just use the extension provided further up the page?

**Comment by leawp** [comment]
@itsafire 
You can do it with regex capturing groups
Search term: `(benev)(a)(lence)`
Replace with: `${1}o${3}`

![obraz](https://user-images.githubusercontent.com/6289091/60735340-4299fa00-9f53-11e9-8e27-c82564545f52.png)

it will match regardless of case so the result will be

![obraz](https://user-images.githubusercontent.com/6289091/60735323-3150ed80-9f53-11e9-8b66-6341849a8af4.png)

**Comment by clshortfuse** [comment]
@leawp Neat, but that wouldn't work if you want to the change to be relative to the case of the search.

Here `o` is always lowercase. Changing `BENEVALENCE` would yield `BENEVoLENCE`. I usually confront this issue when changing a camel-case word like wanting the following:

* `lastTabIndex` => `lastItemIndex`
* `tabIndex` => `itemIndex`

Here, replacing `tab`/`Tab` would with `Item` versus `item` would relative to the search result's capitalization.

**Comment by leawp** [comment]
@clshortfuse yeah, I realized it after reading some comments, added a little explanation to mine.

**Comment by zacaj** [comment]
One of those really simple features that forces me to keep another text editor around

**Comment by rebornix** [comment]
With #60311 merged, you will be able to preserve case when doing single replacement in Find Widget from tomorrow's Insiders. It's still in its early stage so currently we only support following patterns

* all lower case
* ALL UPPER CASE
* Title Case

Feel free to contribute more patterns for this feature. Considering we already have the infrastructure there, it would be straightforward to add more, all you need to do is 

* detect the pattern for the find result, for example, detecting camelCase or snake_case by regex
* convert the `replace` term to the new pattern
* do a replacement ;)

**Comment by vmphipps** [comment]
Amazing, I'm so excited!!!

**Comment by vmphipps** [comment]
Not working as expected; I'll have a PR done in a bit

**Comment by vlmphipps** [comment]
Insiders now works as expected :D

**Comment by uglyeoin** [comment]
Although we have preserve (sensitive) case in normal find and replace we cannot do it when using replace all across multiple files.  That would be useful.

**Comment by rebornix** [comment]
@uglyeoin it's being tracked in https://github.com/microsoft/vscode/issues/78397

**Comment by peabnuts123** [comment]
I think this issue can be closed and new issues be created / referenced here for any related functionality that isn't in yet. Thanks to all who contributed 🙂

**Comment by rebornix** [comment]
Thanks all for the patience and contribution to this feature. If you are interested in contributing more patterns to Preserve Case, you can follow https://github.com/microsoft/vscode/issues/9798#issuecomment-515153288 and if you run into issues while playing with this feature, please file new issues in this repository.
