### ISSUE TITLE
Typescript getters/setters generator for ECMAScript syntax private properties

### ISSUE THREAD

**Issue by josesei** [microsoft/vscode#97987]
When you declare a property with ECMAScript new private property like #property , the system does not recognize is as a property for the purpose of generating the corresponding getters/setters. 
![image](https://user-images.githubusercontent.com/34694779/82122216-93c86c00-9768-11ea-86e7-9274aec44309.png)
![image](https://user-images.githubusercontent.com/34694779/82122268-e144d900-9768-11ea-87e2-a3f260ea368d.png)

Thank you, I really enjoy VSCode!

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
