### ISSUE TITLE
[powershell] block comment does not auto-close

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9799]
- VSCode Version: Code - Insiders 1.4.0-insider (fc167f86c1aee27951b7d4b4db51229f62d0a0ad, 2016-07-26T05:12:44.554Z)
- OS Version: Linux x64 4.4.0-28-generic, Ubuntu 16.04
#9720

`<#` in PowerShell does not auto close. I expected `#>` to be added.

**Comment by aeschli** [comment]
@daviwil David, let me know if you want me to add that
