### ISSUE TITLE
Push from local to Github is highly challenged

### ISSUE THREAD

**Issue by VzNTArchSubra** [microsoft/vscode#97999]
Issue Type: <b>Bug</b>

Hello there, I am new to coding and VS Code. Principally I am good with Client and remote server concepts. Since I am working this out using my office private network, I made sure proxy is all set. 

However,  I am challenged by the below error for last two days, not sure what the issue is:
> git push
fatal: No configured push destination.
Either specify the URL from the command-line or configure a remote repository using

    git remote add <name> <url>

and then push using the remote name

    git push <name>
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git push First-WorkSpace master
fatal: unable to access 'https://github.com/VzNTArchSubra/First-WorkSpace.git/': Failed to connect to github.com port 443: Timed out

 What are the scenarios that I could face this issue, "fatal: No configured push destination."?

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.1.0
file-properties-viewer|bru|0.3.4
vscode-markdownlint|Dav|0.35.2
py-pack|dav|1.2.0
python-preview|don|0.0.4
githistory|don|0.6.5
gitlens|eam|10.2.1
code-runner|for|0.10.0
vscode-pull-request-github|Git|0.15.0
vscode-test-explorer|hbe|2.18.1
vscode-diff|huy|0.0.1
format-python-docstrings|ian|1.2.1
python-coding-conventions|igr|0.0.4
vscode-python-test-adapter|lit|0.4.2
git-graph|mhu|1.22.0
python|ms-|2020.5.78807
autodocstring|njp|0.5.1
trailing-spaces|sha|0.3.1
git-autoconfig|shy|0.0.1
code-spell-checker|str|1.8.0
snippet-creator|vin|1.1.0
markdown-all-in-one|yzh|2.8.0
json|Zai|1.0.4

</details>

**Comment by joaomoreno** [comment]
https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes
