### ISSUE TITLE
[feature] Comment block should handle nested comments

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#97996]
This issue has been bugging me since day one when I started writing CSS in VS Code.

It hinders productivity, and it is a real issue that doesn't deserve to be closed.

![](https://cloud.githubusercontent.com/assets/7921431/13696010/8e716974-e79e-11e5-89c7-87a537c246c8.png)

after `ctrl+/`

![](https://cloud.githubusercontent.com/assets/7921431/13696033/9eda04a6-e79e-11e5-941c-a8b3d4cf6ac7.png)

Most end users expect this functionality to work properly.

There is currently the [Nest Comments](https://marketplace.visualstudio.com/items?itemName=philsinatra.nested-comments) plugin as a workaround.

**Comment by huaigulin** [comment]
Hi @alexdima can I try to implement this feature, if nobody is already working on it?
