### ISSUE TITLE
Unable to use Emmet in style tags.

### ISSUE THREAD

**Issue by abhishekbh12** [microsoft/vscode#97997]
Before when I wrote into style tag Emmet abbreviations was working but not Emmet is not working in style tags only.
In other tags Emmet is working.

**Comment by abhishekbh12** [comment]
![15896553245753359565748193833438](https://user-images.githubusercontent.com/53327662/82127975-f5bebb00-97d4-11ea-9667-09bbf434219b.jpg)

**Comment by alexdima** [comment]
@abhishekbh12 Can you please explain in greater detail what the problem is? Can you also please include the html code you are using in a copy-paste friendly format?
