### ISSUE TITLE
Play button cuts into dropdown corners

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#97993]
The left corners of the debug viewlet dropdown are missing the border - maybe the play button is running into them. I see this in Light+ and Solarized Dark

![image](https://user-images.githubusercontent.com/323878/82126499-d0996080-9772-11ea-8475-854ba3ae1f95.png)
![image](https://user-images.githubusercontent.com/323878/82126522-eeff5c00-9772-11ea-9226-3589350ce16c.png)

**Comment by misolori** [comment]
FYI @isidorn, this was caused from the recent debug theming colors.

**Comment by isidorn** [comment]
@misolori thanks for fixing it!
