### ISSUE TITLE
Support user-wide installations

### ISSUE THREAD

**Issue by stkb** [Microsoft/vscode#98]
I run under a standard user account on my machine, and the installer requires administrator rights, which means running it in the context of a different (administrator) user account. After choosing the "Add to PATH" option, the installer adds `;C:\Program Files (x86)\Microsoft VS Code\bin` to the user PATH variable of that admin account instead, making it unavailable to me.

I guess the installer should add to the machine PATH instead? It would also be great if the installer could be run under a standard user instead, installing vscode to `%LOCALAPPDATA%\Programs`, or give the option whether to install for all users or just the current user.

**Comment by joaomoreno** [comment]
#534
