### ISSUE TITLE
Does Visual Studio Code support searching by Class in typescript?

### ISSUE THREAD

**Issue by ryan-wong** [Microsoft/vscode#980]
I know you can search a file by class name in other IDE like webstorm. Does visual studio code support it or plan on supporting it?

**Comment by jrieken** [comment]
Yes - by default it works for C# and TypeScript and can be invoked with `Cmd+T`. Other extension can contribute via the `WorkspaceSymbolProvider`

**Comment by pmunin** [comment]
Is there any way to merge/union it with searching by file?

**Comment by jrieken** [comment]
I believe that is `    "search.quickOpen.includeSymbols": true,`
