### ISSUE TITLE
CodeLens works in one example but not another

### ISSUE THREAD

**Issue by nickweavers** [microsoft/vscode#98004]
Issue Type: <b>Bug</b>

Please see the examples shown:

Example 1 (codelens doesn't show)
template settings for handler
![image](https://user-images.githubusercontent.com/194136/82131382-9b216100-97cc-11ea-83d6-9427e3975264.png)
script with handler - but no codelens
![image](https://user-images.githubusercontent.com/194136/82131407-f05d7280-97cc-11ea-9189-537460dcbb43.png)

Example 2 (codelens shows)
template settings for handler
![image](https://user-images.githubusercontent.com/194136/82131442-1d118a00-97cd-11ea-8e55-bfa6e863b8d4.png)
script with handler - shows codelens
![image](https://user-images.githubusercontent.com/194136/82131460-50541900-97cd-11ea-9b8d-7a5524bf2ce0.png)

Both projects are on the same machine, just under different directories and the same vscode executable is used for both.

The templates for both have the CodeUri set to the name of the directory holding the script that is using the handler, and both have the Handler set to the name of the script file concatenated with a period and then the name of the handler.

There must be there something else I've missed that is necessary to get codelens to hookup, but I've spent hours searching google for clues and am no wiser. Can someone help?

I'm not sure if this is a bug, or just a user problem.

Thanks.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (13.17GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-18.04/c/var/www/lambda/sam-app --remote=wsl+Ubuntu-18.04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2801)|
|Memory (System)|31.86GB (13.17GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2801)|
|Memory (System)|31.86GB (13.17GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.9.0
vscode-docker|ms-|1.2.0
python|ms-|2020.5.78807
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0

</details>

**Comment by alexdima** [comment]
Please open an issue directly against the AWS extension.
