### ISSUE TITLE
program will not run

### ISSUE THREAD

**Issue by mannheima** [microsoft/vscode#98003]
Issue Type: <b>Bug</b>

i try to run my program using terminal. but it says the system cannot execute the program

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.28.0

</details>

**Comment by mannheima** [comment]
um hello

**Comment by alexdima** [comment]
@mannheima Are you able to run your program using `cmd.exe` outside of VS Code?
