### ISSUE TITLE
Renaming C# entities using F2 shortcut opens a duplicate tab

### ISSUE THREAD

**Issue by octos4murai** [microsoft/vscode#98005]
Issue Type: <b>Bug</b>

-----

### Steps to reproduce
1. Open a C# class in a .cs file.
2. Place cursor over the name of a class, method, or variable.
3. Press F2 to bring up the auto-rename prompt.
4. Type a different name in the auto-rename prompt and press enter.

### Actual Result
A duplicate .cs file is opened in Visual Studio Code with the new name. The original tab remains but does not reflect the naming changes.

### Expected Result
No duplicate tab is created. The original tab reflects the naming changes.

-----

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz (8 x 1100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.21.18
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0

</details>

**Comment by octos4murai** [comment]
### Update
It appears the issue is not exclusive to the F2 rename functionality. It is also happening with the Generate Method helper, accessible through `CMD + .` (`CTRL + .` in Windows).

**Comment by alexdima** [comment]
This appears to be a problem caused by the C# extension, perhaps they don't give good workspace edits.

**Comment by jrieken** [comment]
fyi @bpasero for the epic that discusses casing
