### ISSUE TITLE
SASS / SCSS @Error Issue

### ISSUE THREAD

**Issue by BrokenShoeLace** [microsoft/vscode#98008]
Hi,

I am uses VS 16.5.5 and inside a SCSS document and have created a mixin. All I am doing is setting a property depending on a true / false value passed to it and checking the value is correct using an if, else if, else statement. In that else statement I am using the @error directive.

The error I keep getting is

```
    @if $yes-no == false {
        $yes-no: none;
    }

    @else if $yes-no == true {
        $yes-no: inherit;
    }

    @else {
        @error "Some Message Here";
    }
```

and receiving this error:

**Validation (CSS 4.0): "error" is not a known '@' directive.**

Of course it's not in the directive list and I think it's a bug within VS. If VS supports SASS / SCSS then should support the syntax, too.

I do not wish to change

**Comment by aeschli** [comment]
This is the issue tracker for VS Code, not VS.

I tried your sample in VS Code and it works. Please file the issue against VS
