### ISSUE TITLE
workspace.getConfiguration().get(...) returns a broken Proxy

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#98001]
- VSCode Version: 1.45.0
- OS Version: Windows 10

```
const c = workspace.getConfiguration();
const ls = c.get<Record<string, any>>(drawioLocalStorageKey, {});
// (breakpoint)
```

This is a screenshot of the debug console at (breakpoint), the expressions are entered manually:
![image](https://user-images.githubusercontent.com/2931520/82129999-a4f49580-97c7-11ea-9818-1b464405b48a.png)

As you can see, the first evaluation returns undefined, the second returns the correct value.

**Comment by sandy081** [comment]
@hediet Can you please provide steps to reproduce this? Since it is an extension issue also a sample extension would be great.

**Comment by hediet** [comment]
I guess it happens everytime `getConfiguration().get(...)` returns an object - I don't do very specific things there.
I don't have time right now to create a minimal reproducible example though, but you can have a look at [where it happens in my extension](https://github.com/hediet/vscode-drawio/blob/master/src/Config.ts#L58).

**Comment by sandy081** [comment]
I tried with simple sample and reading a value from an object works for me

```ts
const configuration = vscode.workspace.getConfiguration();
const value: any = configuration.get('workbench.colorCustomizations');
console.log(value['editorLineNumber.activeForeground']);
```

**Comment by sandy081** [comment]
I would request to provide a sample that can repro the issue you see. I don't think going through your extension might be helpful.

**Comment by hediet** [comment]
The important thing is to use JSON.stringify!

**Comment by sandy081** [comment]
Ok, I tried `JSON.stringify` and I see it stringified correctly

![image](https://user-images.githubusercontent.com/10746682/82205074-44b83d80-9906-11ea-8536-5063a30c48b1.png)

**Comment by hediet** [comment]
Thanks for trying! Guess I have to find time for the reproducible example...

**Comment by sandy081** [comment]
Sure.
