### ISSUE TITLE
GitHub Personal Access Token name has typo

### ISSUE THREAD

**Issue by djfdat** [microsoft/vscode#98000]
Issue Type: <b>Bug</b>

Name appears as 'Visuall' instead of 'Visual'

<img width="375" alt="Screen Shot 2020-05-16 at 1 23 19 PM" src="https://user-images.githubusercontent.com/1388271/82129742-b4e58880-9779-11ea-8d4d-bd2a1fe715ee.png">

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (3.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
indent-rainbow|ode|7.4.0

</details>

**Comment by djfdat** [comment]
This was probably made with an earlier version of VS Code, or possibly a VS Code Insider edition.

**Comment by RMacfarlane** [comment]
@djfdat How did you create this access token? Did you log in through a particular extension?

**Comment by djfdat** [comment]
Not sure, but I think it might have been using the Settings Sync in VS Code Insiders: https://code.visualstudio.com/docs/editor/settings-sync

If not that, it was when I was trying to set up the SCM login information.

**Comment by RMacfarlane** [comment]
Hmm, I'm not sure where this is coming from. Both settings sync and the git login should be using the same OAuth app named "GitHub for VSCode", previously they have also used an app called "Visual Studio Code - Insiders".
