### ISSUE TITLE
accessibility, item word not necessary in autocomplete.

### ISSUE THREAD

**Issue by nick777999** [microsoft/vscode#98018]
steps to reproduce:
1. launch NVDa screen reader;
2. open file in visual studio code or create a new one from a main interface;
3. type some keyword that visual studio can autocomplete;
4. now screen reader should say tree view, item word_to_be_autocompleted. where a word_to_be_autocompleted is an item name. there word "item" is extra, because the same word is repeated all over again, which is annoying. It hurts productivity, because that slows down development process and it is coming up slow. I have to wait for some time several seconds for that tree view to come up, so I can move with arrow keys and select item to be autocompleted.

Thanks in advance,
Nick.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17134

**Comment by isidorn** [comment]
@nick777999 thank you for providing feedback.
However we have tuned the suggestion widget behavior already. I have tried reproducing this with latest VS Code insiders and could not.
I also noticed you are not using latest VS Code stable. So please update to latest 1.45 or try out vscode insiders and let us know if you still see this issue. Thanks
