### ISSUE TITLE
Incorrect alignments of UTF-8-demo file

### ISSUE THREAD

**Issue by pepa65** [microsoft/vscode#98012]
- VSCode Version: 1.45.1
- OS Version: Ubuntu MATE 18.04.4 LTS

Steps to Reproduce:

1. Download and open https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@pepa65 What exactly is incorrect? Can you please be more specific?

**Comment by pepa65** [comment]
Not sure to what extend this depends on OS, font, etc. but on my box the long curly brackets are broken, the alignment of the rightmost paragraph of Thai writing is clearly off, and there are several smaller unhappinesses at the graphics at the bottom.

**Comment by alexdima** [comment]
@pepa65 Indeed, font rendering depends on the font and the OS. 

VS Code is built with Electron, which is built with Chromium. The editor inside VS Code delegates font rendering to Chromium.

How does the page render with Chromium on your machine? Here it is how it is rendering in Chromium for me:

![image](https://user-images.githubusercontent.com/5047891/82205119-57cb0d80-9906-11ea-9225-b537f24487f4.png)

![image](https://user-images.githubusercontent.com/5047891/82205135-60234880-9906-11ea-8c51-4e071b909503.png)

If you believe this is a font rendering problem, then please open an issue directly against Chromium at https://bugs.chromium.org/p/chromium/issues/list and link to it here.
