### ISSUE TITLE
Light Theme

### ISSUE THREAD

**Issue by ARTech-7** [microsoft/vscode#98017]
Hello Microsoft!
I have been a long-time light theme guy, and I noticed that VS Code has no default light themes, but two dark themes. So I just wanted to ask for a light theme. I use VS Code a lot, to work on my website ([here](https://artech-7.github.io)). Thanks :)

**Comment by spahnke** [comment]
There are four default light themes:
![image](https://user-images.githubusercontent.com/25029871/82139287-0566ef80-9827-11ea-813c-4809220564ff.png)

**Comment by ARTech-7** [comment]
Hello. I’m running Linux and I don’t see any default light themes.

**Comment by spahnke** [comment]
What themes do you see in the theme picker? There should be four light, nine dark and one high contrast theme showing in a default installation.

What do you see if you show the built-in extensions? For me it looks something like the following picture. Have you disabled built-in themes?
![image](https://user-images.githubusercontent.com/25029871/82142735-be84f400-983e-11ea-8bb8-f833f61ea383.png)

Does the issue occur if you run with extensions disabled (Ctrl-Shift-P -> Reload with extensions disabled)? Maybe one of your installed extensions messes with the built-in themes? (Don't know if that is possible...)

**Comment by ARTech-7** [comment]
Hello. I was only seeing Dark and Dark+ but now after opening the built-in themes extension and closing it again, I could see all the themes.
