### ISSUE TITLE
Test: system-ui font

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98022]
Refs: https://github.com/microsoft/vscode/issues/10144

- [x] Windows @fiveisprime
- [x] macOS @btholt 
- [x] macOS @weinand 
- [x] Linux @mjbvz

Complexity: 2
Authors: @bpasero

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%2398022%0A%0A)

---

All of our non-editor-font CSS declarations now start with `system-ui` as first `font-family` to prefer the OS installed font over the one we pick. Start insiders and compare the result of how fonts appear outside (!) of the editor with stable. You should see a difference **only** on:
- non-Ubuntu Linux
- Windows with e.g. a Chinese locale

**Comment by btholt** [comment]
Here's my dev tools.

![image](https://user-images.githubusercontent.com/999523/83568020-62290200-a4d7-11ea-8114-28207335b7a6.png)

And here's my  editors (Insiders and Stable respectively, side-by-side)

![image](https://user-images.githubusercontent.com/999523/83568096-82f15780-a4d7-11ea-9088-e9e6a006ddf2.png)

I think that's right but I wanted to make sure it looked right to you all.

**Comment by bpasero** [comment]
@weinand @btholt @fiveisprime @mjbvz fyi I have updated the test plan as it had a confusing statement:

![image](https://user-images.githubusercontent.com/900690/83631497-e34acc80-a59d-11ea-8415-46f0ad982479.png)

**Comment by mjbvz** [comment]
Tested on Fedora and confirmed that system-ui is being used
