### ISSUE TITLE
slow performance - could it be my extensions?

### ISSUE THREAD

**Issue by modernman00** [microsoft/vscode#98029]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Performance Issue</b>

Visual code is slow.  It occurs at startup and equally at run time

VS Code version: Code - Insiders 1.46.0-insider (6849775440496504e0677ffcf2a46d47ad9130f5, 2020-05-15T05:30:56.857Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (3.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    76	 14520	code-insiders main
    0	    74	  6568	   window (Issue Reporter)
    1	   332	 10892	   gpu-process
    0	    29	 16748	   utility
    0	   244	 17712	   window (Extension: Auto Comment Blocks - loaneasyfinance - Visual Studio Code - Insiders)
    0	    13	 18924	     watcherService 
    0	     7	 25544	       console-window-host (Windows internal process)
    0	   207	 22296	     extensionHost
    0	    24	  1988	       electron_node serverMain.js 
    0	    26	 10120	       electron_node eslintServer.js 
    0	    70	 11100	       electron_node server.js 
    0	    27	 11564	       electron_node languageserver.js 
    0	    53	 21164	       "C:\Users\moder\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Users\moder\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=22296
   21	  1493	 22812	       electron_node intelephense.js 
    0	    22	 26120	       "C:\Users\moder\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Users\moder\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=22296
    0	    24	 26068	     searchService
    0	    29	 17920	   window (undefined)
    0	    14	 22984	   electron-crash-reporter
    3	    71	 23416	   shared-process
    0	    45	 23952	   window (undefined)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Extension: Auto Comment Blocks - easy - Visual Studio Code - Insiders)
|    Folder (easy): more than 22019 files
|      File types: php(12995) js(6581) scss(102) json(76) txt(7) lock(2)
|           |      Conf files: package.json(1)
|      Launch Configs: php(2) chrome;
```

</details>
<details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
html-snippets|abu|0.2.1
codesnap|adp|1.0.27
aessoft-class-autocomplete|AES|0.1.0
laravel-blade-vscode|ami|2.0.2
beautify-blade|api|1.0.1
laravel-blade-spacer|aus|2.1.2
color-info|bie|0.5.1
vscode-intelephense-client|bme|1.3.11
simple-react-snippets|bur|1.2.2
vscode-exports-autocomplete|cap|0.5.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
laravel-blade|cjh|1.1.2
vscode-css-modules|cli|0.2.3
bracket-pair-colorizer-2|Coe|0.1.3
vs-phpclassgen|dam|0.1.1
vscode-eslint|dba|2.1.5
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
vscode-great-icons|emm|2.1.47
bootstrap-4-cdn-snippet|eve|1.6.1
comment-anchors|Exo|1.7.0
php-debug|fel|1.13.0
php-pack|fel|1.0.2
docblocker|fly|0.5.0
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.3
randomeverything|hel|0.0.3
path-autocomplete|ion|1.13.6
auto-comment-blocks|kev|1.0.1
php-import-checker|mar|0.5.0
code-beautifier|mic|2.3.3
dotenv|mik|1.0.1
debugger-for-chrome|msj|4.12.6
sqltools|mtx|0.21.7
color-highlight|nau|2.3.0
php-docblocker|nei|2.1.0
vetur|oct|0.24.0
indent-rainbow|ode|7.4.0
laravel-blade|one|1.21.0
prettier-vscode-with-tabs|pas|1.1.0
phpstorm-snippets|phi|1.1.1
vscode-php-getters-setters|php|1.2.3
LiveServer|rit|5.6.1
php-files|sev|0.0.5
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.8.0
vscode-laravel-assist|tia|0.1.7
vscode-icons|vsc|10.1.1
vscode-js-import|wan|0.15.5
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by joffarex** [comment]
Did you try to run code with ```code-insiders --disable-extensions``` in order to check if extensions cause slow performance?

I would also add that 22k files is really a lot, have you tried to check performance with any, a little bit smaller project?

**Comment by modernman00** [comment]
You raised a good point. I just checked on a smaller project and it worked perfectly okay.  Thank you
