### ISSUE TITLE
Emmet stopped working

### ISSUE THREAD

**Issue by Guyr989** [microsoft/vscode#98020]
- VSCode Version:1.45.1
- OS Version:Windows_NT ia32

Steps to Reproduce:

1.Update to new vs version. 
2.Try use Emmet on HTML files

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by Guyr989** [comment]
I also work with GRUNT and SCSS.
The issue dose not occur when it's a regular static html file.
Nevertheless this bug happens from time to time. Usually gets working on it's own after a while.

**Comment by Guyr989** [comment]
UPDATE: Emmet is working now.
I think this might have to do with what file structure I am loading to my working directory.
Make sure you are loading the root directory that contains the .git file.

**Comment by rzhao271** [comment]
Closing this old issue. Feel free to open a new issue if it happens again.
