### ISSUE TITLE
Unexpected and not-useful behavior of column mode re: untabbing.

### ISSUE THREAD

**Issue by danielmrussell** [microsoft/vscode#98037]
Issue Type: <b>Bug</b>

When `alt-shift`ing a selection in the editor, one expects to be able to manipulate the resulting selection independently of its surroundings. That is--after all--the entire point of Column Mode.

Probably one of the most common use cases for this is to align right-handed comments after editing has misaligned them:
```
"ADSP"             # Analog VisualDSP++ (analog.com)      
"AppleClang"       # = Apple Clang (apple.com)          
"ARMCC"            # ARM Compiler (arm.com)               
"ARMClang"         # ARM Compiler based on Clang 			
"Bruce"                    # Bruce C Compiler                     
"CCur"                     # Concurrent Fortran (ccur.com)        
"Clang"                    # LLVM Clang (clang.llvm.org)          
...
```

In this example, the user wishes to select the right column from `#Bruce C Compiler...` and down to the right hand corner, while not selecting the left column at all. So the user hits `alt-shift` and mouse-selects that section of the right column only. Then the user hits `shift-tab`, expecting only that section of right column to move to the left, to align it. But instead, the left column also moves to the left, destroying the entire point of using column mode.

The expected behavior is that in Column Mode, only selected columns are acted upon by "operations" like `shift-tab`ing. (Unselected areas can be overwritten by selected areas being so moved on top of them, but are otherwise left alone).

See Column Mode from UltraEdit as comparison. (Likely one of the best models of Column Mode to which VS Code can aspire).

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18362

**Comment by alexdima** [comment]
I don't think your complaint is about column selection at all, since the same behavior exists without column selection. Simply put, Shift+Tab deletes tabs from the beginning of the line, not from the cursor position.

I take it that Shift+Tab in UltraEdit deletes tabs to the left of the cursor position, not tabs from the beginning of the line. Do other editors behave like this or is this a specific UltraEdit behavior ?
