### ISSUE TITLE
Auto Close Multiple Tags When Creating With Multiple Cursor Instances (Alt+Click)

### ISSUE THREAD

**Issue by blindfirefly16** [microsoft/vscode#98038]
Currently VS Code is working nice with auto closing for one tag. But When we use multiple cursor instances to create multiple tags at once, the auto closing feature doesn't work. It only auto closes the first tag. Suppose, I want to create ten `<p>` tags at once. I will create ten instances of cursor with Alt+Click and type my `<p>` tag, but in this case, VS Code only auto closes the first one, not all ten.

**Comment by aeschli** [comment]
That's what I see:

![autoclose](https://user-images.githubusercontent.com/6461412/82196214-b63dbf00-98f9-11ea-8dab-97d9a22231af.gif)

Can you provide your code sample?

**Comment by blindfirefly16** [comment]
Oh!. Turns out I missed an important point to mention. It works nice when my file type or extension is `.html`, but in case of `PHP` files (having `.php` extensions), it simply doesn't work. Suppose I have a `PHP` file named `index.php` with following code:
```
/* index.php */
<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Document</title>
</head>
<body>
 
<?php

echo"

<div></div>

<div>
<div>
<div>

<div>
<div>

";


?>

</body>
</html>
```

![code](https://user-images.githubusercontent.com/26833854/82239510-ae623700-995a-11ea-9f26-95d6d5ed2a99.gif)

**Comment by blindfirefly16** [comment]
I know I should have mentioned the extension and problem environment more clearly. Because this problem is specific to the situation. That means, this problem happens only when coding inside `PHP echo` function.

**Comment by aeschli** [comment]
VSCode doesn't provide auto closing in PHP, so this comes from an exension. Maybe https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag?

Please file the issue against the extension.

**Comment by blindfirefly16** [comment]
Ok. Thanks for making it clear.
