### ISSUE TITLE
vim vg$ only moved the selection, it does not select

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9803]
- VSCode Version: Code - Insiders 1.4.0-insider (fc167f86c1aee27951b7d4b4db51229f62d0a0ad, 2016-07-26T05:12:44.554Z)
- OS Version: Linux x64 4.4.0-28-generic, Ubuntu 16.04

#9699

Steps to Reproduce:

1. Open a file
2. Go to the middle of a line with content
3. Type `"vg$"`, notice the cursor is only moved, no selection

**Comment by rebornix** [comment]
@sandy081 I can repro this issue. Previously when I tried this comamnd with `inSelectionMode` set as true, Code will help select the line or chars but now it didn't work. There is no code change in Vim side so can you help confirm is it a regression or maybe API signagure update?

**Comment by rebornix** [comment]
We have similar selection issue with `vg0` (wrappedLineStart) and `vg^` (nonChar) as well.

**Comment by sandy081** [comment]
As mentioned in #9732, this is an implementation issue in Vim sample extension. In Vim, in normal or visual mode, we always adjust the end of the line position to the one before that. So during selection, Vim sample extension is adjusting just the position instead of the complete selection.

**Comment by sandy081** [comment]
This issue was moved to Microsoft/vscode-samples#8
