### ISSUE TITLE
Ability to handle file:// URI schema links as external websites

### ISSUE THREAD

**Issue by evx73** [microsoft/vscode#98031]
Between other uses, I use VSCode as a personal wiki using markdown documents to note down various local system configurations , document path locations, etc. Similarity at work, we make extensive use of shared folders. We would like to be able to reference various folder and file locations via links using the "file://" URI.

Unfortunately it seems that file URI schema URLs are disabled, I guess for security reasons. Is it possible to add a configuration parameter to enable them as external website links?

**Comment by mjbvz** [comment]
We support absolute and relative links in markdown files which both work fine locally or on website. We do not support hardcoded `file:` uris and don't have plans to

**Comment by evx73** [comment]
Could you please hint at whether an extension could enable file URIs?

Link to absolute or relative markdown resources are not a workaround to my use case. Generic resources can be shared and made available via file shares with resources referenced via file:// links.

See this for example:
https://superuser.com/questions/1222136/share-samba-windows-file-server-links-in-emails-so-they-work-on-windows-and-l/1222141#1222141

What is the rationale for preventing linking to generic URIs? HTML is blind to URI schema. Why should VSCode be selective?

Thanks for looking into this and addressing my questions.

PS: I am underwhelmed by the lack of feedback on the rationale "we are not going to support this, because we are not going to support this".
