### ISSUE TITLE
Terminal display glitch

### ISSUE THREAD

**Issue by StealthAdder** [microsoft/vscode#98034]
Issue Type: <b>Bug</b>

Terminal issue, overall the terminal is not usable. text isn't visible or partial text alphabet are only visible. Tried fresh installs but didn't solve the problem.
Checked online, few posts said a wake up from sleep was the issue or chromium influence.
To be clear none of these are the factors exist as the problem in mine.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 4.15.0-99-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E7400  @ 2.80GHz (2 x 2619)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|3.84GB (1.97GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|4.7.0
python|ms-|2020.5.78807
material-icon-theme|PKi|4.1.0
LiveServer|rit|5.6.1

</details>

**Comment by Tyriar** [comment]
Looks like a problem with Chromium GPU acceleration in `<canvas>`, you can try updating your graphics driver and if that doesn't work you can move to the DOM-based renderer with this setting:

```
"terminal.integrated.rendererType": "dom"
```
