### ISSUE TITLE
Not prevented from starting multiple instances of a launch config

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#98035]
I can click the start debugging button a bunch of times and it keeps showing new instances of the launch config in the call stack. Usually I get the error that there is already a config by that name running. It's not actually launching again though.

![image](https://user-images.githubusercontent.com/323878/82156551-4409a380-9841-11ea-8ba0-2853c8a41251.png)

**Comment by isidorn** [comment]
@roblourens good catch, thanks
