### ISSUE TITLE
Cannot open TERMINAL by modifying the project name

### ISSUE THREAD

**Issue by Aisen60** [microsoft/vscode#98030]
- VSCode Version:1.4.4
- OS Version:mac 10.14.5 

Steps to Reproduce:

I opened a project through vscode. At this time, I changed the folder name of the project. Once again, I returned to vscode. I could n’t open TERMMINAL, and the project in vscode was still the folder name before modification

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
This is probably https://github.com/microsoft/vscode/issues/2259

@Aisen60 any error popping up?

**Comment by Aisen60** [comment]
@bpasero 

Maybe is this question #2259

However, I did not delete the project, just update the project name.

Steps to Reproduce:
- I opened a project through vscode.
- Modified the name of the system folder.
- Go back to vscode and find that the folder name has not been modified.
- Unable to open the command line.

Step video:
https://github.com/Aisen-cai/Test/blob/master/gif.mov

**Comment by bpasero** [comment]
Thanks, this seems terminal specific, waiting for Daniel to comment.

**Comment by Tyriar** [comment]
This is acting as designed imo, if you change the workspace folder you will break everything in the window anyway as it's like deleting it.
