### ISSUE TITLE
Emmet: Could not evaluate expression - Text selection

### ISSUE THREAD

**Issue by yegor-mialyk** [microsoft/vscode#98041]
**Steps to Reproduce:**

1. Open a new editor
2. Type the following line: Test2 1+2
3. Select 1+2 in the text
4. Select "Emmet: Evaluate Math Expression" from the command palette

**Expected result**
The expression being exchanged with '3', as the result the text should look as follows: Test2 3

**Actual result**
An error notification saying "Could not evaluate expression."

It looks like the feature does not respect user's text selection.

**Does this issue occur when all extensions are disabled?** Yes

**Exception (partial):**

> Math evaluation error Error: Unexpected number at column [object Object] of expression
> 	at O (c:\Users\Yegor\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\emmet\dist\extension.js:1:78244)
> 	at c:\Users\Yegor\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\emmet\dist\extension.js:1:76564
> 	at E (c:\Users\Yegor\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\emmet\dist\extension.js:1:77058)
> 	at Module.t.default (c:\Users\Yegor\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\emmet\dist\extension.js:1:78554)
> 	at c:\Users\Yegor\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\emmet\dist\extension.js:1:75524
> 	at Array.forEach (<anonymous>)
> 	at c:\Users\Yegor\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\emmet\dist\extension.js:1:75437
> 	at t.ExtHostTextEditor.edit (c:\Users\Yegor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:584:588)
> 	at Object.t.evaluateMathExpression (c:\Users\Yegor\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\emmet\dist\extension.js:1:75415)
> 	at c:\Users\Yegor\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\emmet\dist\extension.js:1:50190

**VS Code:**
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z (3 days ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by ArturoDent** [comment]
It is confused by the preceding number before the expression to be evaluated. 

` Test 1+2`

works perfectly fine for me whether the `1+2` is selected or not.  Once you add the trailing numeral as in 

` Test2 1+2` it stops working as you note.

**Comment by yegor-mialyk** [comment]
@ArturoDent, in my view, if there is a selection, it should have precedence over any other logic.

**Comment by ArturoDent** [comment]
I agree, I was just pointing out for debugging purposes it doesn't work because of the trailing numeral whether there is a selection or not.  It should work in both cases.

**Comment by rzhao271** [comment]
Verifier:

Test 1

1. Type `Test1 2+3` into a new empty file
2. Select the `2+3` part
3. Run 'Emmet: Evaluate Math Expression'
4. Verify the line has changed to `Test1 5`

Test 2

1. Type `Test1+ 2+3` into a new empty file and place the cursor at the end of the line
2. Run 'Emmet: Evaluate Math Expression'
3. Verify the line has changed to `Test6`

**Comment by yegor-mialyk** [comment]
Now it works as expected. Thanks.
