### ISSUE TITLE
Software takes up a lot of CPU memory 

### ISSUE THREAD

**Issue by programmingGu** [microsoft/vscode#98049]
We have written the neede    here is a problem with my vscode , everytime i run the vscode ,it starts slowly and takes up a lot of CPU memory  90% .  it takes up 30%CPU memory usually d data into your clipboard because it was too large to send. Please paste.

**Comment by miromannino** [comment]
Same for me, very very slow in the last days (maybe it's the last recent update). 
Even scrolling a file of 200 lines of code CPU goes to 90%.

I even did a fresh install deleting all preferences, so there are no even extensions installed.

MacOS 10.15.4

CPU Status: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3200)
GPU Status
2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled

Load (avg): 2, 2, 2
Memory (System): 16.00GB (0.27GB free)
Process Argv
Screen Reader no
VM 0%

**Comment by miromannino** [comment]
Even more strange. 

I opened Developer: Toggle Developer Tools

If I start profiling in the Performance tab the editor immediately speed up to normal speed (60fps)!

If I try profiling with the Capture Screenshots disabled, is still slow (~2fps)!

This is the profile while scrolling up and down a 200 lines of code file.

[Profile-20200521T183859 - screenshots OFF.json.zip](https://github.com/microsoft/vscode/files/4663021/Profile-20200521T183859.-.screenshots.OFF.json.zip)


[Profile-20200521T183859 - screenshots ON.json.zip](https://github.com/microsoft/vscode/files/4663022/Profile-20200521T183859.-.screenshots.ON.json.zip)
