### ISSUE TITLE
Terminal not displaying user environment variables correctly

### ISSUE THREAD

**Issue by adriandarian** [microsoft/vscode#98045]
- VSCode Version:1.45.1
- OS Version:
	> Microsoft Windows [Version 10.0.18362.836]
	> (c) 2019 Microsoft Corporation. All rights reserved.

Steps to Reproduce:

1. Open cmd terminal in vscode
2. run `SetX NEW_ENVIRONMENTAL_VARIABLE test123`

![image](https://user-images.githubusercontent.com/23567187/82165795-484ab680-986b-11ea-994f-870742847982.png)

3. Close terminal
4. Reopen a new terminal in vscode
5. run `echo %NEW_ENVIRONMENTAL_VARIABLE%`

	```bash
	$ echo %NEW_ENVIRONMENTAL_VARIABLE%
	%NEW_ENVIRONMENTAL_VARIABLE%
	```

![image](https://user-images.githubusercontent.com/23567187/82165703-f4d86880-986a-11ea-91e0-4b5a879fc861.png)

6. Open cmd.exe
7. run `echo %NEW_ENVIRONMENTAL_VARIABLE%`

	```bash
	$ echo %NEW_ENVIRONMENTAL_VARIABLE%
	teat123
	```

![image](https://user-images.githubusercontent.com/23567187/82165719-0588de80-986b-11ea-97ba-e1eef7f1ab78.png)

8. Hit `Windows_Key` and type `environmental variables`
9. Open environmental variables see that the env variable has been added

![image](https://user-images.githubusercontent.com/23567187/82165742-16d1eb00-986b-11ea-8d47-2f349f54498e.png)

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/23567187/82165813-5f89a400-986b-11ea-91a9-e95f2ba1fc0e.png)

**Comment by Tyriar** [comment]
This is by design for now as the terminal's environment is sourced from VS Code's main process which only gets refreshed when you close all VS Code windows.

/duplicate https://github.com/microsoft/vscode/issues/47816
