### ISSUE TITLE
"potential listener leak detected"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#98044]
Had this window open for awhile with lots of debugging, and I see a bunch of these warnings

![image](https://user-images.githubusercontent.com/323878/82161647-200b8980-9864-11ea-9bc4-52599c1ab4aa.png)

**Comment by isidorn** [comment]
As far as I can see from the stack trace. Debug changes value of context keys, thus view visibility changes which causes a potential listener leak.
@roblourens can you repro when running vscode out of source so we get a bit more precise stack traces?

fyi @sbatten and @joamoreno for view creation
