### ISSUE TITLE
Extremely Poor Lag

### ISSUE THREAD

**Issue by hammy4815** [microsoft/vscode#98040]
Issue Type: <b>Performance Issue</b>

Today I started using VS code like any other day but it is lagging horribly. I have disabled all extensions, rebooted, restarted my computer, closed all other applications, and nothing will help.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 3, 6|
|Memory (System)|8.00GB (0.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   18	    90	  8501	code main
    4	    49	  8502	   gpu-process
    0	    25	  8504	   utility
    0	   303	  8505	   window (network.py — Network)
    0	   115	  8827	     extensionHost
    0	    33	  8831	     watcherService
    4	    98	  8830	   shared-process
    0	     0	  8871	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    6	    74	  8869	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (network.py — Network)
|    Folder (Network): 4 files
|      File types: py(2) json(1)
|      Conf files: settings.json(1);
```

</details>
Extensions: none

**Comment by alexdima** [comment]
From the Process Info, I could see an unusual high CPU usage of the main process.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
