### ISSUE TITLE
vim g_ and vg_ does not function

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9804]
- VSCode Version: Code - Insiders 1.4.0-insider (fc167f86c1aee27951b7d4b4db51229f62d0a0ad, 2016-07-26T05:12:44.554Z)
- OS Version: Linux x64 4.4.0-28-generic, Ubuntu 16.04

#9699 

This does not happen:

- g_: Moves to last non white space character
- vg_: Selects till last non white space character

**Comment by rebornix** [comment]
Thanks @Tyriar , `g_` is include in https://github.com/VSCodeVim/Vim/pull/508 and for `vg_`, we still need to see if it shares the same problem as #9803 .

**Comment by sandy081** [comment]
g_ and vg_ were not implemented in the sample vim extension. I think because they are not mentioned in VIM road map. @rebornix FYI.

I implemented them in then sample now should be working now.
