### ISSUE TITLE
Explore bringing GitLens "Git Commands" into built-in Git

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#98047]
### Git Commands
> Provides guided (step-by-step) access to common Git commands and their flags
> ![menu-git-commands](https://user-images.githubusercontent.com/641685/67904366-85a45c80-fb44-11e9-8b6f-29f04090e9f5.png)

This feature IMO *should* be moved into VS Code as there is duplication with VS Code commands and it provides a nice unified way of dealing with the growing list of Git commands, of which are hard to discover and deal with different options for. By moving this into VS Code directly, the UX of this feature could be improved as well, to provide a more seamless experience for navigating commands. For example, it would be great if this experience was shown immediately upon typing `git ` (with the space) in the Command Palette. Also many of the hoops and hacks that are needed to provide this experience should be largely eliminated as well (although many could be addressed through an expanded quick pick api).

Including this feature would also eliminate many duplicate git commands between GitLens and VS Code. And also since this feature is on-demand, there is no perf overhead for VS Code to provide this.

**Comment by joaomoreno** [comment]
@eamodio Let's talk early June on how to advance this.
