### ISSUE TITLE
js-debug debugger terminal discoverability 

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#98054]
We want to explore ways to increase the discoverability of the debugger terminal. The entrypoints we have today are:

 - Command palette: undiscoverable
 - Debug welcome view: good discoverability, but only if you don't have a launch config
 - Scripts in package.json: this isn't the terminal itself, but is a common use case, good indirect discoverability.

Thing we can improve:

 - [x] Contribute the debugger terminal into the Run and Debug dynamic configurations. Good discoverability, easy and no overhead.
 - [ ] contribution to `...` in the debug view (august) *deferred*
 - [x]  a separate top-level dynamic debug configuration for the terminal
 - [x]  Kai suggested contributing a button to the debug terminal toolbar, in this area

    ![](https://memes.peet.io/img/20-05-68430601-cc6c-4af8-95f0-4123fb3a6bc8.png)

    We would be careful to only do this if the workspace contains javascript files. @Tyriar thoughts?

**Comment by eamodio** [comment]
👍 to adding a new button to the terminal toolbar. Or even a debug button or something to turn a regular terminal into a debug one (if that is possible).

**Comment by Tyriar** [comment]
Hmm, it's already fairly busy up there with the dropdown and 5 buttons. Looking ahead a little bit, how would this interact with a future shell selector/tabs that I'm hoping to have similar to Windows Terminal:

![image](https://user-images.githubusercontent.com/2193314/82965820-1a0d5b00-9f7e-11ea-8ee0-5904a3e09f26.png)

Would debug terminal be a shell entry in the dropdown, using your default shell by default? Allowing you to enable it on any shell in a custom profile (similar to this](https://github.com/Tyriar/vscode-shell-launcher#settings))?

**Comment by connor4312** [comment]
Something like that could work well. The debug terminal is a little 'weird' because it's a mode that can apply to any terminal, but we could just say it uses your default terminal and can be configured differently as desired.

I'm not sure if it's a pattern we use anywhere, but photoshop has these little arrows in the lower right of buttons to indicate you can click it or expand it. We could do something like that to avoid needing a separate button.

![](https://memes.peet.io/img/20-05-cbb1a836-d84d-4863-97f8-36fb41afdc48.png)

**Comment by jasonwilliams** [comment]
@connor4312 do you know if theres a shortcut to cycle between Debug, Terminal, Output and problems?
Sometimes i need to go back and forth between Terminal and Debug.
I know ctrl + ` gets you to Terminal, but doesn't look like its possible to get back

**Comment by Tyriar** [comment]
@jasonwilliams you can add keybindings for `workbench.action.nextPanelView` and `workbench.action.previousPanelView`

**Comment by connor4312** [comment]
One alternative Kai and I talked about last week is using the dropdown 

![](https://memes.peet.io/img/20-06-015a5bb9-efc3-432e-876f-eae7a164533d.png)

In addition to "select default shell", "Create new terminal" could be one of the actions and/or extensions could contribute other actions to the area.

**Comment by Tyriar** [comment]
@connor4312 sounds like a good solution until we gets the tabs/new terminal dropdown separation 👍

**Comment by connor4312** [comment]
One more suggestion. Kai and I talked about having some button in this area

![](https://memes.peet.io/img/20-06-3a54dff6-d685-4217-9c8c-9dc305b1c8e8.png)

This is a natural place for discoverability. I have two questions for this area:

 1. There's already a button for the debug console which is a nice bug + terminal icon, which is also a very natural icon for the debug terminal. Is there a way we can differentiate the debug terminal enough from those existing icons?
 2. This area gets crowded with a small sidebar. We should make sure it doesn't get too crowded.

     - The "run" title is standard on all views but probably irrelevant for the non-welcome debug view, since people's launch configs will already often say something like "Run app" or "Attach to extension host"
     - We could hide the debug console icon while a session is not currently in progress. It's always read-only then.
     - Some limit on how extensions can show a button there? For js-debug I would only show this when `debugStartLanguage` is js or ts.

cc @isidorn

**Comment by isidorn** [comment]
@connor4312 makes sense to make the js-debug terminal more discoverable. Please note that we are adding `...` button in all views to make hidden views more discoverable. More details here https://github.com/microsoft/vscode/issues/98614

Due to that I see two good options:
* We make the `...` contributable such that js-debug can contribute a js-debug terminal action there
* We make the behavior of the click on console contributable, so in the js-debug case this would open the js-debug terminal. I would dislike to have both of these actions as I think it can be quite confusing for users what is what.

Also for considerations look into a case the debug toolbar is docked via a setting in that area. Then we do not show these actions.

**Comment by connor4312** [comment]
> We make the behavior of the click on console contributable, so in the js-debug case this would open the js-debug terminal

I don't like the idea of installing an extension changing the behavior of an existing button in the UI.

A `...` menu contribution would work 🙂

**Comment by isidorn** [comment]
@connor4312 ok for this I have created
https://github.com/microsoft/vscode/issues/100771

Unfortunetly I will probably not have time for this this week, and from end of next week I am on a long vacation. So let me know if you need it before so I provide some code pointers so you can also maybe look into it.
If it is ok to do it in August then I can also jump on it.

**Comment by connor4312** [comment]
Sounds good. Closing this out as everything else is completed.
