### ISSUE TITLE
Compilation issues for the missing imports are not highlighting for the copy paste java code.

### ISSUE THREAD

**Issue by ganesa-vijayakumar** [microsoft/vscode#98059]
- VSCode Version: 1.45.1
- OS Version: Windows 10

Steps to Reproduce:

1. Copy-paste a simple java program without imports (For Example I copy-pasted the code `Calendar cal = Calendar.getInstance();`)
2. Verify that the compilation issue is not highlighted for the missing import of the class Calendar.

Note:
1. We can easily correct it for small programs but it will be difficult for the big programs since we can identify the import missing issue only when we run the program.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@ganesa-vijayakumar This appears to be a problem with the Java extension, which is the one that creates diagnostics. Please report directly against https://github.com/redhat-developer/vscode-java/issues
