### ISSUE TITLE
Slowness after Version: 1.45.1 update when editing big file

### ISSUE THREAD

**Issue by CreateLife** [microsoft/vscode#98055]
Issue Type: <b>Performance Issue</b>

experiencing slowness when editing a file with size 333MB
start to have the problem after  Version: 1.45.1 update

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (19.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   123	  3032	code main
    0	    14	  5768	   electron-crash-reporter
    0	   591	 40268	   window (td.log - dev - Visual Studio Code)
    0	    11	112220	     watcherService 
    0	    11	 49740	       console-window-host (Windows internal process)
    0	    64	136672	     extensionHost
    0	   137	 48328	   gpu-process
    0	    27	 66904	   utility
    1	    71	 66980	   shared-process
    0	    72	 73868	   window (Issue Reporter)
    0	    22	136796	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (td.log - dev - Visual Studio Code)
|    Folder (dev): 988 files
|      File types: png(368) bat(165) hlsl(132) dll(73) bin(40) gltf(40) pm(22)
|                  sh(18) pdb(14) pl(13)
|      Conf files: launch.json(1)
|      Launch Configs: perl(2);
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
perl-debug|mor|0.6.3

</details>

**Comment by alexdima** [comment]
@CreateLife 
1. Does this slowness occur only when editing this specific file? 
2. What file type is it? 
3. If you rename it to `.txt`, does the slowness persist?
4. If yes, can you please create a profile?

To get a CPU profile of the renderer process:
* Run `F1 > Toggle Developer Tools`
* Go to the three dots burger menu
* Choose `More Tools > JavaScript Profiler`
* Start a new CPU profile
* Do the actions that lead to slowness
* Save the CPU profile to a file and attach it

![kapture 2017-10-21 at 13 02 25](https://user-images.githubusercontent.com/5047891/31851158-30fd860a-b660-11e7-9018-661394adb754.gif)

**Comment by CreateLife** [comment]
The slowness disappeared after renaming from "td.log" to "td.txt"

**Comment by alexdima** [comment]
@CreateLife Can you please verify that you use `"editor.largeFileOptimizations": true` ? If you have configured `"editor.largeFileOptimizations": false`, then the editor will attempt to tokenize the very large file, which might lead to slowness.
