### ISSUE TITLE
Working Tree and Timeline not showing changes

### ISSUE THREAD

**Issue by sgkrenganathan** [microsoft/vscode#98058]
Issue Type: <b>Bug</b>

 Open Source Control from the menu and click on any modified file. 
Open any Timeline changes

Issue:
The changes and diff are not being displayed 

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|10.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.3.11
phpcs|ika|1.0.5
python|ms-|2020.5.78807

</details>

**Comment by eamodio** [comment]
Can you provide more details on the issue you are experiencing? Maybe even record a video? As I'm not seeing any issues with the SCM view and interaction with the Timeline view. Thanks!
