### ISSUE TITLE
主题（theme）问题

### ISSUE THREAD

**Issue by HydrIoner** [microsoft/vscode#98051]
- VSCode Version:1.45.1
- OS Version:19624

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/63766539/82172224-29e0cb80-98fc-11ea-8c62-f918e503f855.png)
^^
Sidebar is black

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by AkiraVoid** [comment]
There's no need of translation. The title is: The Problem of Theme

**Comment by alexdima** [comment]
@HydrIoner That is intentional, in our light theme, the sidebar is black. This color can be customized by you via user settings or you can install a new theme.
