### ISSUE TITLE
vim nvH and nvL do not work correctly

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9805]
- VSCode Version: Code - Insiders 1.4.0-insider (fc167f86c1aee27951b7d4b4db51229f62d0a0ad, 2016-07-26T05:12:44.554Z)
- OS Version: Linux x64 4.4.0-28-generic, Ubuntu 16.04

#9699

These do not seem to function correctly:

- nvH Select till first non white space character of nth line from the top of the view
- nvL Select till first non white space character of nth line from the bottom of the view

Both seem to select to outside the view.

**Comment by sandy081** [comment]
This is dependent on the view port range computation in the editor. When a line is partially visible (wrapped), view port data some times containing the wrapped line of the line as starting line even though it is not visible.  

This has to be fixed along with #9542.

Duplicates #9542
