### ISSUE TITLE
[html] auto rename matches wrong tag 

### ISSUE THREAD

**Issue by AkiraVoid** [microsoft/vscode#98053]
- VSCode Version: April 2020 (version 1.45)
- OS Version: Windows 10 1909 (18363.836)

Steps to Reproduce:

1. Add `<html>, <head>, <body>` tag
2. Insert a `<div>` tag into `<body></body>`
3. Insert another `<div>` tag into `<div></div>`

*No the code looks like:*
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <div>
            <div></div>
        </div>
    </body>
</html>
```

4. Type `<div` in second `<div></div>` tag, and if tag highlight extension was installed, the highlighted tag will be tag you typing and the first `</div>` tag
5. Now type `>`. VS Code will automatically add a `>` after the first `</div>` tag.

*Now the code looks like:*
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <div>
            <div>
                <div>
            </div>
        </div>>
    </body>
</html>
```

6. It seems like VS Code will always match outter end tag. I did not conduct a rigorous experiment.

Does this issue occur when all extensions are disabled?: Yes
****
**I must say this is a terrible bug.**

**Comment by aeschli** [comment]
"editor.renameOnType": true need to be on for the bug to show.

**Comment by lramos15** [comment]
![bug](https://user-images.githubusercontent.com/4544166/83891675-8bd26b00-a71b-11ea-9518-6f9b78f02306.gif)
Still can repo on latest insiders.
