### ISSUE TITLE
TS Server takes 100% cpu

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#98066]
Code insiders helper renderer gets at 100% cpu for the last 3 work days for me.
My clunky reprot steps: just open vscode repository and wait until you can hear your cpu fan.

Let me know what details you would like me to provide. Please do not link me to the performance issue page :)
This was not happening 7 days ago.

**Comment by bpasero** [comment]
@isidorn but is this using our E8 build or not? And did you make sure it is the renderer process and not some child process within (use our process explorer for that).

**Comment by isidorn** [comment]
@bpasero it is not the E8 build. But the regular one.
I will use our process explorer tomorrow when this happens again.

**Comment by isidorn** [comment]
Ok it is the TS Server
![Screenshot 2020-05-26 at 10 52 09](https://user-images.githubusercontent.com/1926584/82880612-f7a81d00-9f3e-11ea-9c2b-c94f08d61e13.png)

Here is the TS Log

[Info  - 07:31:19.334] Starting TS Server 
[Info  - 07:31:19.334] Using tsserver from: /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 07:31:19.336] <syntax> Forking...
[Info  - 07:31:19.341] <syntax> Starting...
[Info  - 07:31:19.341] <semantic> Forking...
[Info  - 07:31:19.344] <semantic> Starting...


@mjbvz please let me know what more data you need. I can repro this every time and hurst my productivity.

**Comment by isidorn** [comment]
Might it be TS semantic highlighthing that causes 100% cput?
fyi @aeschli

**Comment by aeschli** [comment]
@isidorn Try `"editor.semanticHighlighting.enabled": false` to test that hypothesis.

**Comment by isidorn** [comment]
@aeschli I am trying it now. We will see tomorrow, since this for some reasons happens once per day.

**Comment by isidorn** [comment]
This was not happening with semanticHighlighting disabled.
@aeschli @mjbvz what more data would you like me to provide so we can look into this?

**Comment by aeschli** [comment]
This will be something the TypeScript team has to look at when they take over our code. Clearly, semantic highlighting is expensive as it involve resolving many symbols. The TypeScript service does not seem to cache very much as @alexdima found in his investigations.

#92789 is the issue for the handover

**Comment by isidorn** [comment]
@aeschli actually this started reproducing every couple of days even thoough I have `semanticHighlighting` disabled. Maybe it was happening more often when I had it turned on.
How can I provide more info that could be helpful?

**Comment by isidorn** [comment]
@mjbvz thanks! Looking forward to the fix.

**Comment by primozs** [comment]
@mjbvz Hi,
So this is not yet released in TS 3.9.7 right? vscode 1.47.3
I get high cpu on yarn install. like described in #98665

code --status
CPU
108	   819	 86184	       electron_node tsserver.js

**Comment by mjbvz** [comment]
Closing this for now since the upstream TS  has been fixed. Let me know if you still see the problem when using the latest VS Code builds
