### ISSUE TITLE
not producing color from in the result page.

### ISSUE THREAD

**Issue by topynene** [microsoft/vscode#98062]
Issue Type: <b>Bug</b>

function love.draw()
    love.graphics.setBackgroundColor(125, 150, 150)
    love.graphics.setColor(255, 100, 100)
    love.graphics.rectangle("fill", 200, 200, 85, 100)
    love.graphics.circle("line", 250, 250, 56)
    love.graphics.setColor(100, 100, 250)
end

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz (4 x 1796)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.70GB (0.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexdima** [comment]
@topynene This issue does not appear to be an issue with VS Code.
