### ISSUE TITLE
Cannot move source control back to the side

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#98069]
- VSCode Version: 1.46.0-insider
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Move Source Control to the bottom
2. Can't move it back

Video: [simplescreenrecorder-2020-05-18_10.52.56.zip](https://github.com/microsoft/vscode/files/4643101/simplescreenrecorder-2020-05-18_10.52.56.zip)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
@sbatten Did we enable this?

**Comment by sbatten** [comment]
@joaomoreno no, i did not think this is possible but I know why it is happening now that I am looking. scm doesn't register views until the container is opened. the restriction for movement is on views, not containers. if someone moves scm before it is focused it will work as no view inside prevents this from happening. 

@SimonSiefke Please run ctrl+shift+p => reset view locations

**Comment by SimonSiefke** [comment]
Thanks @sbatten. That worked :)

**Comment by sbatten** [comment]
resolved for next release
