### ISSUE TITLE
Native local sync option for remote-ssh workflow

### ISSUE THREAD

**Issue by oncena** [microsoft/vscode#98065]
I'm seriously considering replacing my current IDE with visual studio code for PHP development. But only one option is keeping me from doing this. Syncing the files on a remote server (remote-ssh) with a local directory as a backup and git repository. I don't mean syncing the whole project but rather updating the file contents "**on save**" both on the remote server **and** the local directory.

**Comment by roblourens** [comment]
Great! We don't plan to implement something like this in vscode, but you can set up a workflow like this yourself with something like rsync: https://code.visualstudio.com/docs/remote/troubleshooting#_using-rsync-to-maintain-a-local-copy-of-your-source-code

**Comment by oncena** [comment]
This won't cut it but thanks.
