### ISSUE TITLE
View Open Editor as tree view

### ISSUE THREAD

**Issue by dutzi** [microsoft/vscode#98067]
When dealing with many files it would help if the Open Editors section inside the Explorer panel would have the option to view the open editors in tree view, instead of list.

I think that when having multiple files opened, across different parts of the code base, having them naturally grouped within the folders they are at would greatly improve "discoverability" (i.e., finding the file we are looking for).

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
