### ISSUE TITLE
光标失灵

### ISSUE THREAD

**Issue by GuoChen-thlg** [microsoft/vscode#98068]
Issue Type: <b>Bug</b>

When editing a file, when the cursor reaches the end of the last line, the cursor will automatically jump to the next line, jump back again, unable to save the file and run, and when there is a free line in front of the cursor, the cursor will delete directly and hover between the last line and the new line

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (8.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.1.3
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.7.1
vscode-html-css|ecm|0.2.3
json-tools|eri|1.0.2
auto-close-tag|for|0.5.7
code-runner|for|0.10.0
next-js|fox|0.0.2
beautify|Hoo|1.5.0
comment-translate|int|1.4.2
docthis|joe|0.7.1
vscode-liquid-snippets|kil|1.3.0
vscode-fileheader|mik|0.0.2
easy-less|mrc|1.6.3
vscode-language-pack-zh-hans|MS-|1.45.1
python|ms-|2020.5.78807
debugger-for-chrome|msj|4.12.7
language-liquid|nei|0.1.1
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.17.0
vscode-manifest-yaml|Piv|1.17.0
vscode-spring-boot|Piv|1.17.0
java|red|0.61.0
vscode-xml|red|0.11.0
missinglineendoffile|ric|0.3.1
LiveServer|rit|5.6.1
shopify-liquid|sis|2.3.0
easysass|spo|0.0.6
autoimport|ste|1.5.3
language-stylus|sys|1.11.0
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.1
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.22.4
vscode-maven|vsc|0.21.4
vscode-spring-boot-dashboard|vsc|0.1.10
vscode-spring-initializr|vsc|0.4.8
vscode-icons|vsc|10.1.1
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0
ReactSnippets|xab|2.4.0
swig-tpl|zha|0.0.6

</details>

**Comment by alexdima** [comment]
@GuoChen-thlg  Does the issue reproduce when disabling all extensions?

**Comment by GuoChen-thlg** [comment]
> @ GuoChen-thlg 禁用所有扩展名时是否会再次出现此问题？

Good thank you

**Comment by alexdima** [comment]
Please disable all installed extensions and attempt to reproduce. Does the problem reproduce?

**Comment by GuoChen-thlg** [comment]
> 请禁用所有已安装的扩展名并尝试重现。问题是否重现？

When the plug-in is disabled, it does not appear
