### ISSUE TITLE
I'm using VS Code-Insiders version- 1.45 it's always shows not responding prompts..

### ISSUE THREAD

**Issue by soumyadeepsinha** [microsoft/vscode#98064]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Visual Studio Code- Insiders
2. April 2020 Version 1.45

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by alexdima** [comment]
@soumyadeepsinha Can you please show what steps you are doing? Do you open a specific folder? Does this reproduce when opening a new empty window?

**Comment by soumyadeepsinha** [comment]
It doesn't matter. when I lunch vscode it shows me the same error.
