### ISSUE TITLE
Can't edit code

### ISSUE THREAD

**Issue by AssiaRachdi** [microsoft/vscode#98075]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

I can't edit a file whether after creating a new one or after duplicating from an existing one. Behaves like a read-only state. Doesn't react to keyboard, the only move is the cursor in the code (tried with .txt .html .js .css)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 7, 7|
|Memory (System)|4.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eslint|dba|2.1.5
vscode-html-css|ecm|0.2.3
vscode-pull-request-github|Git|0.16.0
sublime-keybindings|ms-|4.0.7
vscode-icons|vsc|10.1.1
vim|vsc|1.14.4
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by alexdima** [comment]
@AssiaRachdi It appears you have installed the `vim` extension and in consequence, text input now follows the `vim` style of input. I suggest you uninstall the `vim` extension if you don't want to use `vim`-style input.

**Comment by AssiaRachdi** [comment]
I've uninstalled so many extensions and didn't think of VIM !! You are a life saver ! thanks a lot !
