### ISSUE TITLE
IntelliSense not working when using absolute import paths

### ISSUE THREAD

**Issue by hazem94** [microsoft/vscode#98074]
- VSCode Version: `1.45.0`
- OS Version: `Deepin 15.11 Desktop 64-bit Linux`

Steps to Reproduce:

1. Added the following to `jsconfig.js` 
```
{
  "compilerOptions": {
    "baseUrl": "src",
    "module": "es6"
  }
}
```
2. IntelliScence is not working 
![image](https://user-images.githubusercontent.com/16942677/82199855-f0618d80-9906-11ea-97ff-da997cbc785f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

Also, please provide a small example project to reproduce the problem

**Comment by hazem94** [comment]
@mjbvz 
The update of `1.45.1` solved the issue already :) Thanks! It's working now.
