### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Hardik2101** [microsoft/vscode#98073]
We have written the needed data into your clipboard because it was too large to send
Issue Type: <b>Bug</b>

All suggestion are not working in my vs code why???
and sometime give me error.
otherwise give me warning aur code is corrrupt so install new version.i install new version of vs code bt same time of error show me.
i face this problem some days.
so what is the bug in vs code?/

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18363

. Please paste.

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by Hardik2101** [comment]
in vs code auto suggestion is not working
1: vs code version 1.30.2

**Comment by Hardik2101** [comment]
vs version is 1.30.2
auto suggestion is not working

**Comment by jrieken** [comment]
Use the recent version which is 1.45.1 and add repro steps

**Comment by Hardik2101** [comment]
i install this version but same problem face me

**Comment by jrieken** [comment]
This is not going anywhere, closing

**Comment by Hardik2101** [comment]
so what is the require solution???

**Comment by jrieken** [comment]
You write a bug report that allows me to reproduce what you are seeing. See, suggestions are working for me and our other users. It's one of our core features, if it breaks for all users it would not go unnoticed, so there is something special with your setup and we can only move forward if you share as much as possible about your setup, your project etc etc. As said before, use this guide to learn how to file a good issue:  https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests.
