### ISSUE TITLE
Option to disable automatic expansion of folded code, and expand on keypress.

### ISSUE THREAD

**Issue by yunti** [microsoft/vscode#98071]
Currently with code folding, the code will automatically expand if the cursor passes onto a folded section, rather than the code actively being expanded with eg a key press.

The current behaviour makes it very hard to navigate around a file with folded sections, as the editor is constantly trying to open this up automatically.
There doesn't apppear to be an option currently to turn off automatic expansion of folded code.

(Note the default in intellij,webstorm,pycharm etc.. is to expand code actively ie on key press, this makes it significantly easier to navigate around files with folded code).

**Comment by aeschli** [comment]
How do you you navigate around? Cursor down jumps over the folded regions.

**Comment by yunti** [comment]
Thanks, I navigate around with the vim plugin and the usual hjkl keys.

**Comment by yunti** [comment]
Seems to be an issue with the vim plugin and code folding when I test it.

Shall I raise an issue in the vim plugin directly?

**Comment by yunti** [comment]
Looks like it's this issue. you can close thanks.

**Comment by aeschli** [comment]
Thanks for finding the duplicate!
