### ISSUE TITLE
Use `sortText` to choose preselected `CompletionItem` if there are multiple CompletionItems with preselect=true

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/vscode#98070]
According to the vscode api doc, if there are multiple `CompletionItem` with `preselect=true`, vscode will choose the first item of those that match best. 

I think it's better to use `sortText` as a backup comparator in this case, there are two reasons:

1. The definition of **match best** is not clear to extension developers, this may cause unexpected behavior and it's really difficult to debug
2. Generally, better `CompletionItem` costs longer to compute. Just use the first `CompletionItem` as preselect item might lower the quality of the whole completion result.

**Comment by HaoboGu** [comment]
Here is an example:

![image](https://user-images.githubusercontent.com/8640918/82195057-5e6b7c00-992a-11ea-9ff2-69a68acaf4d3.png)


The first two completion items are provided by my extension. The preselected item will be always the last one, even though the first item matches better and I set the `preselect=true` for the first item.

**Comment by jrieken** [comment]
It is done like that. The editor uses `sortText` and prefix-match quality to determine a set of top scorer and when in that set multiple items have `preselet` set then the first is selected. I am not sure what the issue here is. Is this unclear doc or what is this?

**Comment by HaoboGu** [comment]
IMO, if there are multiple items having `preselect=true`, I think it's better to take `sortText` into consider, rather than just choose the first item. 

For example, if there are three completionItems:
```typescript
const item1 = {
  label = "item1",
  preselect = true,
  sortText = "000"
}
const item2 = {
  label = "item1",
  preselect = true,
  sortText = "001"
}
const item3 = {
  label = "item1",
  preselect = true,
  sortText = "002"
}
```
Then vscode should choose `item1` because this item has a better `sortText`, rather than just choose whichever comes first.

**Comment by jrieken** [comment]
>  rather than just choose whichever comes first.

`sortText` does determine which "comes first".

**Comment by HaoboGu** [comment]
It's strange. In this case, vscode chooses to preselect the last item, even though this item is sorted at the bottom(which means it has a lower `sortText` score, right?) 

![image](https://user-images.githubusercontent.com/8640918/82199596-76de9500-9930-11ea-997a-a3ddeff1e5bd.png)

**Comment by jrieken** [comment]
what's your config for `editor.suggestSelection`

**Comment by HaoboGu** [comment]
It's `first`.

**Comment by jrieken** [comment]
ok, then (while suggestion show), hit cmd+? (or ctrl+?) . the details widget will show internals, like sortText, prefix, score etc. That should explain the order

**Comment by HaoboGu** [comment]
I tried, but it shows nothing.. Do I have to do something like key binding?

**Comment by jrieken** [comment]
Make sure the details widget shows, usually via ctrl+space when suggestion already show

**Comment by HaoboGu** [comment]
The info doesn't explain the preselect behavior as well. 
In the previous example, the info for first `write` is:
```
score:-100(no prefix)
distance:0
index:0, based on sortText:"0"
```
The info for last `flush();` is:
```
score:-100(no prefix)
distance:0
index:8, based on sortText:"0"
```

**Comment by HaoboGu** [comment]
I haven't figure out why the last `flush();` is preselected, but I found another bug in vscode here:
https://github.com/microsoft/vscode/blob/7f49bf19401168d97be72ffa7c842ab5de4775fa/src/vs/editor/contrib/suggest/suggestMemory.ts#L24-L41

at line29, the index starts from 1, which means the preselected item will NEVER be the first item if there are multiple items having `preselect=true`. 

You can easily reproduce this using the following code:
```typescript

import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	let sel:vscode.DocumentSelector = { scheme: 'file' };
	let LanguageServerProvider = vscode.languages.registerCompletionItemProvider(sel, { 
		provideCompletionItems(document: vscode.TextDocument, position: vscode.Position) {
			let completionResult: vscode.CompletionItem[] = []
			let a = new vscode.CompletionItem("a");
			a.preselect = true;
			a.filterText = "a"
			a.sortText = "0";
			let b = new vscode.CompletionItem("b");
			b.preselect = true;
			b.filterText = "b"
			b.sortText = "00";
			let c = new vscode.CompletionItem("c");
			c.preselect = true;
			c.filterText = "c"
			b.sortText = "000";
			completionResult.push(a, b, c);
			return completionResult
		}
	}, " ", ".");
	context.subscriptions.push(LanguageServerProvider);
}

export function deactivate() {}

```

If you trigger completion, vscode would always choose `b` as the preselected item:

![bug](https://user-images.githubusercontent.com/8640918/82227151-f46acb00-9959-11ea-9265-ae3ed04d5454.gif)

I think it's definitely a bug

**Comment by jrieken** [comment]
Yes - but its a different issue, right? How about filing a new issue

**Comment by HaoboGu** [comment]
Okay, I'll open another issue about that. Thanks for your patience.

Let's concentrate on what's discussed in this issue - do you have any idea about why vscode prefers the last item with `preselect=true`, rather than the first completion item which has `preselect=true` and best `sortText`?

**Comment by HaoboGu** [comment]
> Yes - but its a different issue, right? How about filing a new issue

This strange behavior is caused by that bug: `write` is the first item having `preselect=true`, while `flush();` is the second. I'll close this one and move to #98102
