### ISSUE TITLE
Sometimes have to hit F12 twice

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#9808]
- VSCode Version: Code - Insiders 1.4.0-insider (fc167f86c1aee27951b7d4b4db51229f62d0a0ad, 2016-07-26T05:03:44.836Z)
- OS Version: Darwin x64 15.5.0

Only reproduces sometimes:
1. Place caret on a type reference
2. Press F12 -> nothing happens
3. Press F12 twice with some time between -> nothing happens
4. Press F12 twice quickly -> Goes to definition

Not sure if that was with a particular VS Code build or some configuration change on my machine unrelated to VS Code.

**Comment by kieferrm** [comment]
That works fine for me with the latest insider build.
