### ISSUE TITLE
Test: anchor selection

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#98087]
Refs: https://github.com/microsoft/vscode/issues/95894

- [x] anyOS @aeschli 
- [x] anyOS @sana-ajani

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%2398087%0A%0A)

---

We have introduced three new editor commands:

"Set Selection Anchor" Ctrl+k, Ctrl+b
"Select From Anchor to Cursor" Ctrl+k, Ctrl+k
"Go to Selection Anchor" 

Try out these commands and make sure they works as expected. Thus verify:
* Set Selection Anchor sets a selection anchor, only one anchor per file is possible
* Pressing `Esc` while an anchor is set cancles it
* Select From Anchor to Cursor select from set anchor to the cursor position
* Go to selection anchor navigates the cursor to the set anchor
* The anchor position nicely updates when you change text before it
* Once a new file is opened in the editor the anchor is no longer set

**Comment by ArturoDent** [comment]
Should the selection anchor persist after `Select From Anchor to Cursor`?  Perhaps a mistake was made the first time or there is a use case for repeated selections using the same anchor.

**Comment by isidorn** [comment]
@ArturoDent currently it is designed in a way that the anchor does not persist. I felt this would make a nicer expereince so user would most of the time not need to manage the anhcor. Though I see that once a new anchor is set the only one is lost, so there is not a lot of managin. I am open for feedback and that we potentially change this.

**Comment by jareds** [comment]
Based on the way I use this feature Select From Anchor to Cursor should destroy the anchor. I'd say I'm cutting or deleting text at least 50% of the time I use this feature. If I delete the text I would expect the anchor to go away. If I'm not deleting text I'd still prefer the anchor to go away since it would be extra complexity to try and remember that because I didn't delete text the anchor is still around.

**Comment by ArturoDent** [comment]
I would prefer to manage the anchor myself.  Perhaps there are other selections I would like to do begore getting back to the `select to anchor` action.

I agree with this: "If I delete the text I would expect the anchor to go away" .  But if I do a selection that doesn't involve the anchor I want the anchor to stay.

**Comment by sana-ajani** [comment]
@ArturoDent the anchor goes away after the command "select from anchor to cursor".
