### ISSUE TITLE
Jinja syntax highlighting in html templates file

### ISSUE THREAD

**Issue by knezdusan** [microsoft/vscode#98082]
Hi,

Apparently, the internal HTML code syntax and formatter are not working for the Jinja templating code that is used by the Flask framework. The available extensions require to switch from the native solution to the Jinja specific that decrements other features like code sniping.

http://prntscr.com/siym6y

I think this may be a great benefit for the web developers, especially those that are using VScoce in conjunction with the Flask framework, to integrate the Jinja syntax highlighting and formating alongside other HTML respective capabilities already present in native setup. 

Thanks.

**Comment by aeschli** [comment]
The correct solution is to have a Jinja language and a TextMate grammar for it.
This is something that has to come from a extension.

There are already several extensions for Jinja in the marketplace. Please give them a try and file issues against theme if you find issues or lacking features.
