### ISSUE TITLE
padStart() has not been added

### ISSUE THREAD

**Issue by vnvyvu** [microsoft/vscode#98085]
- VSCode Version: 1.45.1 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/22812601/82282039-16e20000-99bd-11ea-9648-122b10e152bc.png)

Code:

```js
let ax=(parseInt(prompt("Input ax (hex): "), 16)).toString(2).padStart(8,"0").split(``);
alert(ax);
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

/needsMoreInfo

**Comment by vnvyvu** [comment]
@mjbvz Text code and screenshots has been added

**Comment by mjbvz** [comment]
Thanks. This seems to be working for me in VS Code insiders:

<img width="1892" alt="Screen Shot 2020-05-20 at 2 25 16 PM" src="https://user-images.githubusercontent.com/12821956/82499025-c5617000-9aa5-11ea-8645-4ab50cb40a3f.png">

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by vnvyvu** [comment]
all extensions disabled
![image](https://user-images.githubusercontent.com/22812601/82519166-3dce3c80-9b4b-11ea-9d34-224ca3f90da4.png)
Is this version the latest and is the insiders build? If not how to convert?
![image](https://user-images.githubusercontent.com/22812601/82519207-54749380-9b4b-11ea-9705-55e734b8a91b.png)

**Comment by vnvyvu** [comment]
all extensions disabled
![image](https://user-images.githubusercontent.com/22812601/82520763-24c78a80-9b4f-11ea-8300-18c8975d6c1a.png)
I installed latest VS Code insiders build version
![image](https://user-images.githubusercontent.com/22812601/82520809-445eb300-9b4f-11ea-8343-79d54f69adab.png)
It still

**Comment by mjbvz** [comment]
Does your project have a jsconfig? If so, does it set a `target` for an earlier version of JavaScript that would not include `padStart`?
