### ISSUE TITLE
TS: imports are being rewritten even if disabled in settings

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98081]
Following the steps from https://github.com/microsoft/vscode/issues/98057#issue-619928707 configure `"javascript.updateImportsOnFileMove.enabled": "never"` and move the files around as instructed. I see them becoming dirty and it looks like TS is still rewriting the import even though this is disabled by settings.

**Comment by mjbvz** [comment]
I'm not able to reproduce this with the example project. One possible explanation is that there are two settings that control this behavior:

`typescript.updateImportsOnFileMove.enabled` and `javascript.updateImportsOnFileMove.enabled` control this independently for TypeScript and JavaScript. In the example project, if I set `"typescript.updateImportsOnFileMove.enabled": "never"` then the imports are not updated

Let me know if you see this after setting `"typescript.updateImportsOnFileMove.enabled": "never"` as well
