### ISSUE TITLE
VScode graphic line tabulation

### ISSUE THREAD

**Issue by Fylls** [microsoft/vscode#98097]
surely it is not a game changer but the line that extends outside the function really annoys me.
lines should be use to represent the end of a function or element tabulated inside other elements, so they should provide a visual guide for understanding code structures.

if the line extends outside (red area in picture), beginner developers could think that there might be a connection between the first function and the one that follows it, which is actually totally wrong

other than the misleading visual , it looks really terrible.
as I said it is not a game changer but are these subtle things that improve the experience using a program.

I have been using VScode for 2 years and it has been my favorite editor so far for its compatibility, versatility, design, extensions and customization. I really think this minor change could improve the program even more, thanks a lot.

![ghissue](https://user-images.githubusercontent.com/55017307/82230788-7f34d100-992c-11ea-9018-f9857d5d5a3b.PNG)

**Comment by Fylls** [comment]
any news about the issue?

**Comment by Colaveloper** [comment]
although entirely graphical, I personally consider that issue pretty annoying ...it has been around for quite a while now, isn't it time for a fix?

**Comment by Fylls** [comment]
![Capture](https://user-images.githubusercontent.com/55017307/87394899-b7653280-c5b0-11ea-8252-29115dce2b01.PNG)

seriously this bug is really ugly
