### ISSUE TITLE
.css color decorators don't seem to work with apha values != 1

### ISSUE THREAD

**Issue by OptiStrat** [microsoft/vscode#98090]
Issue Type: <b>Bug</b>

In a .css file, the color decorator displays the right color in this case ... 
.myClass {
  background-color: rgba(255, 0, 0, 1)
}

... or in this case ...
  background-color: rgb(255, 0, 0)

... but not in this case:
  background-color: rgba(255, 0, 0, 0.3)

For now, I have disabled the color decorator and installed an extension that exhibits the desired behavior (Color Highlight 2.3.0). However, by doing so, I am also deactivating the color picker, which is not ideal.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 4.18.0-147.8.1.el8_1.x86_64

**Comment by alexdima** [comment]
@OptiStrat This appears OK for me:

![image](https://user-images.githubusercontent.com/5047891/82223055-67584f80-9922-11ea-9714-d3feab2ede90.png)

**Comment by rebornix** [comment]
The bug behind is `hash` doesn't support float numbers.
