### ISSUE TITLE
Need a way to cancel timed telemetry events

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#9809]
E.g.: When the user cancels a file search by closing QuickOpen early (could be using ESC or selecting a recent file entry) we need a way to cancel the timed event.

Currently the TimeKeeper in timer.ts eventually cleans up timer events by 'stopping' them, the telemetry service then writes these to the backend because it has no way to tell the event was stopped by the clean up and not by the instrumented code.

**Comment by ramya-rao-a** [comment]
Closing as per offline discussions that this is no longer relevant
