### ISSUE TITLE
Select/focus node in custom TreeView not working

### ISSUE THREAD

**Issue by katelynienaber** [microsoft/vscode#98095]
I am trying to expand a node in the custom TreeView. The tree looks like this:
````
parentNode
    childNode
        child2
        child3
        child4
        ...etc
````

When a new node is created, the tree should automatically expand to that node (ex. child3) and the node should be selected.

I have tried all of the following, and various combinations thereof, none of which have worked:
````
        treeView.reveal(child3, { focus: true, select: false, expand: false });
````
````
        treeView.reveal(child3);
````
````
        treeView.reveal(child3, { focus: true, select: false });
````
````
        await treeView.reveal(child3.getParent(), {select: true, focus: true, expand: true});
        treeView.reveal(child3, { focus: true, select: false, expand: false });
````
````
        const parent = child3.getParent();
        parent.label = parent.label.trim() + " ";
        parent.label = parent.label.trim();
        parent.collapsibleState = vscode.TreeItemCollapsibleState.Expanded;
        parent.dirty = true;
        // This function fires onDidChangeTreeItem
        await this.refreshElement(parent);
        await treeView.reveal(child3.getParent(), {select: true, focus: true, expand: true});
        treeView.reveal(child3, { focus: true, select: false, expand: false });
````
````
        const parent = child3.getParent();
        parent.label = parent.label.trim() + " ";
        parent.label = parent.label.trim();
        parent.collapsibleState = vscode.TreeItemCollapsibleState.Expanded;
        parent.dirty = true;
        // This function fires onDidChangeTreeItem
        await this.refreshElement(parent);
        await treeView.reveal(child3.getParent(), {select: true, focus: true, expand: true});
        let children = await parent.getChildren();
        let memberNode = children.find((child) => child.label.trim() === child3.label.toUpperCase());
        treeView.reveal(child3, { focus: true, select: false, expand: false });
````

Can someone give me a hint why this will not work?

**Comment by alexr00** [comment]
Do you implement `getParent` [as required for `reveal`](https://github.com/microsoft/vscode/blob/e33a750ce80f83e1bbe2320bd0600e39965d675d/src/vs/vscode.d.ts#L7882-L7894)?

**Comment by katelynienaber** [comment]
> Do you implement `getParent` [as required for `reveal`](https://github.com/microsoft/vscode/blob/e33a750ce80f83e1bbe2320bd0600e39965d675d/src/vs/vscode.d.ts#L7882-L7894)?

Docs say: _TreeDataProvider is required to implement getParent method to access this API._
This is not clear to me. It sounds like TreeDataProvider is required, in order that getParent can be implemented (by the VSCode library). Do you mean instead that I must implement my own getParent method, because it is required by the TreeDataProvider?

Also, reveal() works elsewhere in the code. It only fails if I try to reveal a **new** node which I have created just before calling setItem.

I pass the TreeDataProvider into the function:
````
    public setItem(treeView: vscode.TreeView<IZoweTreeNode>, child3: IZoweTreeNode) {
        treeView.reveal(child3, { focus: true, select: false, expand: false });
    }
````

I call function setItem like this:
````
theTree.setItem(theTree.getTreeView(), newNode);
````

Function getTreeView:
````
    public getTreeView(): vscode.TreeView<IZoweJobTreeNode> {
        return this.treeView;
    }
````

The treeView is assigned to a class variable like so, when `theTree` is created:
````
    constructor() {
        this.treeView = vscode.window.createTreeView("zowe.uss.explorer", {treeDataProvider: this});
    }
````

**Comment by alexr00** [comment]
You must implement `getParent` in order to use `reveal`. Do you implement it? I will update the wording of the doc.

**Comment by katelynienaber** [comment]
Yes, it is implemented on the tree node:
````
    public getParent(): IZoweTreeNode {
        // This is a private variable that is passed to the node constructor
        // and refers to the node's parent
        return this.mParent;
    }
````
And on the tree provider:
````
    public getParent(element: IZoweTreeNode): IZoweTreeNode {
        return element.getParent();
    }
````

**Comment by alexr00** [comment]
If you open the dev tools (Developer: Toggle Developer Tools) are there any errors in the console when you hit this problem?

**Comment by katelynienaber** [comment]
Yep!
![image](https://user-images.githubusercontent.com/58596139/82312290-2403ec80-99c7-11ea-8702-7fb6363220a2.png)

**Comment by katelynienaber** [comment]
Blacked out bit should just be part of the rest of the string after /0:

So in this case the tree looks like:
````
nienaber
    XXXXXX.NEW.PDS.TEST
        tester
````

Where `tester` is the new node just created

**Comment by katelynienaber** [comment]
Is there any hope? This is still an issue for us.

**Comment by alexr00** [comment]
Can you provide a small self contained repro of this issue? The [tree view sample uses `reveal`](https://github.com/microsoft/vscode-extension-samples/blob/7b9a0a8c4c631e393862c3e767c7be26bb2233b2/tree-view-sample/src/testView.ts#L10-L10), and I'm not able to repro the issue with that.
