### ISSUE TITLE
Support for custom link handler in Markdown Cell and Webviews

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#98100]
- VSCode Version:
- OS Version:

**1. Add support to handle Notebook output link clicks in extension code**
**2. Add support to handle Notebook Markdown cell link clicks in extension code.**

* Currently we (Python Extension) displays custom links in the webviews (our notebook implementation).
	* We do this in the Markdown of a cell
	* We do this in output of a cell.
* We handle these clicks by monitoring the click event of the document.
* Any link clicked that has an href starting with `vscode` is handled by our code in webview and then passed onto the extension.

With the new VS Code notebooks, we'll need to do the same to handle links displayed in the output. I can see two solutions (for outputs):
* Use our own renderer when rendering HTML & and highjack all clicks to handle our custom links (not preferred, as I'd prefer to use VS Code renderers as much as possible).
* Add links in HTML using `href=javascript:acquireVsCodeAPI().postMessage(....)`.

**However, we won't be able to handle click events in markdown**  
* At least not with the above approach
* Open to alternatives

Had a chat with @rebornix and it was suggested that VSCode could provide a custom API that works in Markdown + Output rendered in WebViews as well as Notebooks

**Comment by kieferrm** [comment]
@DonJayamanne what is the use case for this. How would another notebook tool handle these notebook files?

**Comment by DonJayamanne** [comment]
This wouldn't work across another notebook tool.
We were planning on adding these cells or output temporarily when displaying nb in VS Code (when saving to disc that cell wouldn't be added).
Our goal was to use Markdown to render some content and have the same look and feel as VSCode markdown renderer, & have ability to include links that can trigger some code in the extension.

E.g. we add a cell with markdown (containing) instructions for user with links in the cell (clicking that triggers extension code).
Similarly when output text > certain limit), we truncate it and add a message with a link allowing user to change the value.

**Comment by roblourens** [comment]
Is this solved by supporting `command:` type links that will invoke a command when clicked? Or do you need to intercept the user's click on an arbitrary link like `http://microsoft.com`?

**Comment by roblourens** [comment]
And changing the URLs to that type of link is a vscode-specific solution, is that a problem?

**Comment by DonJayamanne** [comment]
> Is this solved by supporting command: type links that will invoke a command when clicked?

Yes that would work.

> And changing the URLs to that type of link is a vscode-specific solution, is that a problem?

No, that would work.

Today we handle all link click handlers and if the link starts with `http://command`, then we execute the command (provided its a link we generated - by looking at a white list).

**Comment by roblourens** [comment]
Ok, in markdown cells it will work in tomorrow's build. I'll have to think about it for output.

**Comment by rebornix** [comment]
Moving this to June and we still need to discuss what's the right solution for this problem. Command links work well in VS Code but they are not platform agnostic.

**Comment by rebornix** [comment]
@DonJayamanne we discussed this offline and `command` links are good as Python extension is already pre-processing the data, following links will work

* `[link](command:COMMANDID)` in markdown cell
* `<a href="command:COMMANDID"></a>` in outputs

We can continue discussion if we find the solution not feasible.

**Comment by roblourens** [comment]
These don't actually work in outputs currently though, I need to hook that up.

**Comment by rebornix** [comment]
I tested `command:` links are working fine in outputs in webview and pushed a change to `text/markdown` static output to support it as well.
