### ISSUE TITLE
lcursor problem

### ISSUE THREAD

**Issue by Zeeshan-Saleem** [microsoft/vscode#98107]
Issue Type: <b>Bug</b>

when ever i write code the cursor moves to the last line, when ever i want add indention it automatically removes the indention,please help me to solve this issue

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD PRO A8-8600B R6, 10 Compute Cores 4C+6G     (4 x 1597)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.42GB (0.55GB free)|
|Process Argv|E:\class work\11th class|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-JS-CSS-HTML-formatter|lon|0.2.3
python|ms-|2020.5.78807
LiveServer|rit|5.6.1

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

> VS Code version: Code 1.31.1

Is it correct version? Could you please update to latest (1.45.1) and try it again.
https://code.visualstudio.com/Download

If it's still reproducible could you provide screen recording or more detailed steps - which language, wheat are settings etc.
