### ISSUE TITLE
.html files considered as text file whereas .htm file works correctly.

### ISSUE THREAD

**Issue by chetanwork88** [microsoft/vscode#98104]
Issue Type: <b>Bug</b>

Create the HTML file with html extension.
Suggestions won't work as file is recognised as text file.
But,
If you create file with htm extension it recognises as html file and show suggestions.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

**Comment by aeschli** [comment]
Does this reproduce with extension disabled?

**Comment by chetanwork88** [comment]
No I think the issue was with one of the extension.Now it is resolved.

**Comment by aeschli** [comment]
Cool, glad it works again. Thanks for reporting back!
