### ISSUE TITLE
.Net CLI tools not being located

### ISSUE THREAD

**Issue by RMajere** [Microsoft/vscode#9810]
- VSCode Version: 1.3.1
- OS Version: windows 10 1511

Steps to Reproduce:

1. install visual studio 2015 enterprise with updates include all common tools
2. install visual studio code
3. open visual studio code
4. create file with CS extentions
5. error message appears error The .Net CLI tools cannot be located. .Net Core debugging will not be enabled. Make sure .NET CLI tools are installed and are on the path.

**Comment by kieferrm** [comment]
Moved to https://github.com/OmniSharp/omnisharp-vscode/issues/626. @RMajere pls subscribe there.
