### ISSUE TITLE
TextMate interpretation potentially broken?

### ISSUE THREAD

**Issue by bhair** [microsoft/vscode#98112]
- VSCode Version:
Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

I did not see an existing issue that talks about this.

Steps to Reproduce:

1. Open a .nsi or .nsh file in VS Code
2. Have the NSIS extension enabled for NSIS file syntax highlighting.
3. Observe that syntax is not being highlighted.
![image](https://user-images.githubusercontent.com/38145576/82252214-37a24b00-9914-11ea-919e-20796ba18069.png)

Portions such as 'SendMessage' and quoted strings used to be highlighted by the NSIS extension by Idleberg.

I originally opened a request against the extension developers repository and they mention that their extension has been using the VS Code TextMate syntax highlighting engine and that they suspect that something changed there to cause their TextMate to not function like it used to. This request can be seen here for additional details: https://github.com/idleberg/vscode-nsis/issues/17

Does this issue occur when all extensions are disabled?: This issue is because of an extension. Disabling extensions would not allow the issue to happen.

**Comment by bhair** [comment]
I have tested this against the latest insider build and it still occurs there.

**Comment by alexdima** [comment]
See https://github.com/microsoft/vscode-oniguruma/issues/2#issuecomment-638742406
