### ISSUE TITLE
Initializing JS/TS language features forever

### ISSUE THREAD

**Issue by tapz** [microsoft/vscode#98115]
Issue Type: <b>Bug</b>

1. Start vscode
2. Observe your MacBook to get extremely hot.
3. Buy a new battery to your MacBook.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|212, 267, 223|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
android-dev-ext|ade|1.1.0
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
pug2html|gin|0.0.5
swift|Kas|0.2.0
Kotlin|mat|1.7.1
vscode-puglint|mrm|2.3.0
vscode-docker|ms-|1.2.0
debugger-for-chrome|msj|4.12.7
gradle-language|nac|0.2.3
java|red|0.61.0
markdown-preview-enhanced|shd|0.5.3
pdf|tom|0.6.0
vscodeintellicode|Vis|1.2.7
vscode-swift-development-environment|vkn|2.10.0
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.1
vscode-java-pack|vsc|0.9.1
vscode-maven|vsc|0.21.4
markdown-all-in-one|yzh|2.8.0
material-theme|zhu|3.6.2

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code-insiders --status`
