### ISSUE TITLE
toggle block comment 

### ISSUE THREAD

**Issue by Arconapalus** [microsoft/vscode#98110]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I used to be able to comment out sections of my code by cmd + / on macOS and now nothing happens. I do have extensions installed such as, Vim and I have updated the extension and also updated the extension and still not able to comment out the lines of code. 

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
project-manager|ale|11.0.0
vscode-database|baj|2.2.0
vscode-icontheme-nomo-dark|be5|1.3.6
solargraph|cas|0.21.1
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.35.2
vscode-eslint|dba|2.1.5
vscode-PSStackoverflow|Dou|0.0.2
react-native-react-redux|EQu|2.0.4
git-project-manager|fel|1.7.1
vscode-pull-request-github|Git|0.16.0
cloudcode|goo|1.3.0
beautify|Hoo|1.5.0
wordpress|hri|1.0.1
rest-client|hum|0.23.2
powershellprotools|iro|5.10.2
search-editor-apply-changes|jak|0.1.1
vscode-codemetrics|kis|1.24.0
terraform|mau|1.4.0
vscode-language-babel|mgm|0.0.27
dotenv|mik|1.0.1
vscode-docker|ms-|1.2.0
vscode-kubernetes-tools|ms-|1.2.0
mssql|ms-|1.9.0
python|ms-|2020.5.78807
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
Go|ms-|0.14.2
powershell|ms-|2020.4.0
material-icon-theme|PKi|4.1.0
pluralsight|Plu|0.3.7
ruby|reb|0.27.0
vscode-yaml|red|0.8.0
LiveServer|rit|5.6.1
terraform-doc-snippets|run|0.4.0
jinjahtml|sam|0.13.0
vscode-icons|vsc|10.1.1
vim|vsc|1.14.4
vscode-ruby|win|0.27.0
vscode-import-cost|wix|2.12.0
wordpress-toolbox|wor|1.3.7
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.6.2

(10 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Default keybindindings are 
Add line comment `⌘K ⌘C`
Remove line comment `⌘K ⌘U`
Toggle line comment `⌘/`
Toggle block comment `⇧⌥A`

So you should check if any extension overrides them first. Also it's useful check in Keyboard Shortcuts screen what action is assigned to that shortcut.

**Comment by Arconapalus** [comment]
Yes I found the issue, in TerraForm syntax or .tf file extension the line comment short doesn't work but works elsewhere in other code. I have disable all extension and cannot add a line comment in TerraForm .tf file.

**Comment by IllusionMH** [comment]
If you use Command palette for to toggle line/block comments - do they work?

After installation of https://marketplace.visualstudio.com/items?itemName=mauve.terraform both toggle line and block shortcuts work for me (on Windows)

Do they work for you if you disable all extension except Terraform?

**Comment by egamma** [comment]
Closing as requested
