### ISSUE TITLE
Syntax highlighting is inappropriately dark after IIFE

### ISSUE THREAD

**Issue by elias6** [microsoft/vscode#98118]
Issue Type: <b>Bug</b>

I have the following code in a file:
```js
export const someNumber = (() => {
	try {
		return 123;
	} catch (ex) {
		return 0;
	}
})();

export const numberIsLucky = (x) => {
	return x === 42;
};
```

Everything under `someNumber` (the declaration for `numberIsLucky` in this case) looks dark, as if the code is unreachable, even though it is not unreachable.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 8, 6|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.1
prettier-vscode|esb|4.7.0
pyformat|giy|1.0.1
vscode-docker|ms-|1.2.0
python|ms-|2020.5.78807
vsliveshare|ms-|1.0.2169
language-stylus|sys|1.11.0
selectline-statusbar|tom|0.0.2

</details>

**Comment by IllusionMH** [comment]
This one is caused by microsoft/TypeScript#36828 that already fixed upstream in TS3.9 (and is in May iteration plan)

You can use https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next extension which provides nightly builds with the fix.

**Comment by elias6** [comment]
Thanks for responding. I think I will just wait until it gets fixed in a stable build.
