### ISSUE TITLE
High CPU usage making workstation unresponsive for minutes

### ISSUE THREAD

**Issue by janwilmans** [microsoft/vscode#98111]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Ctrl-Shift-F 
2. Replace something that occurs in 300+ .cpp files 
3. cpptools spawns 100ths of processes, consuming  >90.0 load (90 x 100% cpu)

![image](https://user-images.githubusercontent.com/5933444/82251987-81a82280-994e-11ea-92f0-95d13fdd6a6d.png)

Does this issue occur when all extensions are disabled?: No

**Comment by kieferrm** [comment]
@roblourens FYI

**Comment by kieferrm** [comment]
\extC++
