### ISSUE TITLE
Presentation group labels for launch config

### ISSUE THREAD

**Issue by SteelPhase** [microsoft/vscode#98114]
Not sure I'm missing a feature, but it would be great if we could label presentation groups in launch.json. I used the below to do this, but it is kinda jank.

```json
{
    "name": "--- Group Name ---",
    "type": "node",
    "request": "launch",
    "presentation": {
        "group": "0_Group",
        "order": 0
    }
}
```

**Comment by isidorn** [comment]
Yeah you can do that. But we just use the group for sorting.
Are you saying you would like that group label to be somewhere visible in the UI?

**Comment by SteelPhase** [comment]
So I don't think you should use the group name itself, but maybe offer a way to define a group display label. Could even use the order of the groups in the presentation array below as the order for the groups themselves instead of the current sorting,

```json
{
    "version": "0.2.0",
    "compounds": [
        {
            "name": "Example compount",
            "configurations": [],
            "presentation": {
                "group": "01_Group1",
                "order": 1
            }
        }
    ],
    "configurations": [
        {
            "name": "Example configuration",
            "type": "go",
            "request": "launch",
            "presentation": {
                "group": "02_Group2",
                "order": 1
            }
        }
    ],
    "presentation": [
        {
            "group": "01_Group1",
            "label": "Group One"
        },
        {
            "group": "02_Group2",
            "label": "Group Two"
        },
    ]
}

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by SteelPhase** [comment]
In the intermediate time, @isidorn how hard would it be to implement a configuration item that is just a label. I'd be willing to attempt a PR for that if it was an acceptable workaround for the time being?

**Comment by isidorn** [comment]
We do not currently accept a PRs that tackle this issue.
Maybe in the future once we have properly planned for this and designed this feature.
