### ISSUE TITLE
theJupyter Notebook is not working with Screen reader properly 

### ISSUE THREAD

**Issue by YashSonkiya** [microsoft/vscode#98117]
when I open a new Jupyter notebook it works well with my Screen reader (which is JAWS in this case). but when I close and open it again I can't read in the edit feeld using arrow keys. please fix this as soon as possible.  

- VSCode Version: v 1.45
- OS Version: Windows 10 v 18363.836

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
@YashSonkiya do you use the Jupyter notebook support that you get with the Python extension?

**Comment by YashSonkiya** [comment]
> /needsMoreInfo
yes i use the python extention

**Comment by kieferrm** [comment]
\extPython
