### ISSUE TITLE
Add a way to inspect memento contents

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#98113]
As an extension developer I do a lot of work with mementos. It would be nice if there was some Developer command / etc. to inspect (and modify) the contents of the memento storage for each extension, `globalState` in particular, though `workspaceState` would also be nice.

**Comment by bwateratmsft** [comment]
\<ShamelessSelfPromotion>
I made an extension that facilitates this: https://marketplace.visualstudio.com/items?itemName=bwater.memento-explorer
\</ShamelessSelfPromotion>

**Comment by lszomoru** [comment]
Closing this issue the functionality is available through an extension.
