### ISSUE TITLE
Branch code changes automatically ported to master

### ISSUE THREAD

**Issue by fmunteanu** [microsoft/vscode#98119]
- VSCode Version: 1.45.1
- OS Version: macOS Catalina 10.15.4

Steps to Reproduce:

1. Clone repo and make a branch.
2. Perform code edits to an existing file and create a new file.
3. Change back to master, changes made into branch show also in master
4. Delete branch, code changes remain in master, you have to manually delete the directories and undo file changes.

Does this issue occur when all extensions are disabled?: Yes

The expected behavior is to contain code changes into branch, I do not want to have master automatically updated. If I use IntelliJ, when I switch to master, all code changes and files are not displayed anymore and they remain contained into branch. Is there an option I missed in VSCode?

![Screen Shot 2020-05-18 at 5 25 07 PM](https://user-images.githubusercontent.com/19806136/82261786-ad66e080-992d-11ea-9670-94d41815b737.png) ![Screen Shot 2020-05-18 at 5 29 20 PM](https://user-images.githubusercontent.com/19806136/82261799-b22b9480-992d-11ea-8d93-8a8ef6ed62b7.png)

**Comment by IllusionMH** [comment]
I don't see this step in your description: did you commit before switching to master branch?

This is standard `git` behavior - switching branches don't hide/remove/commit etc. changes, and changing this behavior will break a lot of existing workflows.
So if you need that changes in branch - it's better to commit them first into branch and then switch to master.


Not sure what you are seen but in this case IntelliJ should have same behavior

> If your working tree is clean (that means you have no uncommitted changes), or your local changes do not conflict with the specified branch, this branch will be checked out (a notification will pop up in the bottom-right corner of the WebStorm window).

https://www.jetbrains.com/help/webstorm/manage-branches.html#switch-branches

Options with conflicts are handled manually

**Comment by fmunteanu** [comment]
My mistake, thank you for bringing it up.
