### ISSUE TITLE
使用qq五笔输入法与vscode出现无法输入文字的bug

### ISSUE THREAD

**Issue by yangqinjiang** [microsoft/vscode#98129]
Issue Type: <b>Bug</b>

我的英文不好， 这里只有中文表达
步骤：
1， 切换 qq五笔输入法， 中文输入状态 
2,   按下一个字母， 例如   d ， 这时出现一行待选择的汉字,
3,   再按一下shift按键， 输入法这时会切换英文状态
4， 再按其它字母，就会出现无法输入多个字母的 bug

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.70GB (3.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.3.11
java-run|cao|1.1.4
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
phpcs|ika|1.0.5
vscode-docker|ms-|1.2.0
vscode-language-pack-zh-hans|MS-|1.45.1
python|ms-|2020.5.78807
Go|ms-|0.14.2
debugger-for-chrome|msj|4.12.7
java|red|0.61.0
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.1
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.22.4
vscode-maven|vsc|0.21.4
markdown-html|zhy|0.1.8

</details>

**Comment by AkiraVoid** [comment]
Translation Here:
****
**A Bug Which Cannot Type In Letters Occured When Using VS Code With QQ's Wubi Input Software.**

Issue Type: **Bug**

My English is poor, there's only Chinese.

Reproduce：
1. Use QQ's Wubi Input software， switch to Chinese Input Mode
2. Type a letter, for example `d`,  now a row of Chinese Character appers and waiting to be selected,
3. Press <kbd>Shift</kbd>， switch to English Input Mode
4. Type other letters and now the bug of can't type in multi-letters appears.

VS Code version: Code 1.45.1 (5763d90, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

**Comment by rebornix** [comment]
It's already fixed in current Insiders.
