### ISSUE TITLE
"Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node." error when deleting a terminal tab

### ISSUE THREAD

**Issue by martellaj** [microsoft/vscode#98120]
![image](https://user-images.githubusercontent.com/1019478/82265227-5821d380-991b-11ea-82ac-99e76b210657.png)

Version: 1.46.0-insider (user setup)
Commit: 6849775440496504e0677ffcf2a46d47ad9130f5
Date: 2020-05-15T05:30:56.857Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19559

Steps to Reproduce:

1. Have 2 tabs in terminal
2. Delete 1 tab ("Kill terminal")

Does this issue occur when all extensions are disabled?: I didn't check.

**Comment by martellaj** [comment]
I've been seeing this for over a week in Insiders. Bystander effected and assumed it would be reported and fixed without me having to report. 😅

**Comment by Tyriar** [comment]
This should get fixed in https://github.com/microsoft/vscode/pull/98182
