### ISSUE TITLE
Preferences Sync: Error 429

### ISSUE THREAD

**Issue by mpearon** [microsoft/vscode#98121]
Issue Type: <b>Bug</b>

# Issue Description
Preferences Sync fails, returning error 429

# Steps to Reproduce
1. Enable Preferences Sync (GitHub Auth in this case)
2. Trigger Preferences Sync Manually (affects AutoSync as well)
3. Review **Log (Preferences Sync)**

# Log Data
```
2020-05-18 17:33:07.533] [userDataSync] [info] Auto Sync: Triggered.
[2020-05-18 17:33:07.668] [userDataSync] [error] Unknown (UserDataSyncError) undefined: Server returned 429
    at e.manifest (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:510:674)
    at async e.sync (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:502:527)
    at async e.sync (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:489:596)
```

VS Code version: Code - Insiders 1.46.0-insider (6849775440496504e0677ffcf2a46d47ad9130f5, 2020-05-15T09:06:06.454Z)
OS version: Darwin x64 19.4.0 *Also effecting Windows_NT x64 10.0.18363*

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 4, 3|
|Memory (System)|8.00GB (2.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-clock|Com|0.0.1
vscode-github-notifications-bell|fab|2.3.1
vscode-coffeebreak|fre|0.1.11
vscode-peacock|joh|3.7.2
svn-scm|joh|2.11.1
chat|kar|0.33.0
vscode-sshfs|Kel|1.17.0
vsce-show-triggerwords|MPe|0.2.13
mssql|ms-|1.9.0
powershell-preview|ms-|2020.5.0
vsliveshare|ms-|1.0.2169
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.3.4
git-autoconfig|shy|0.0.1
swdc-vscode|sof|2.2.6
vscode-wakatime|Wak|4.0.0
markdown-all-in-one|yzh|2.8.0

</details>

**Comment by Tyriar** [comment]
Should be fixed in a couple of minutes, sorry about the hassle.

**Comment by mpearon** [comment]
@Tyriar - It appears to be working as expected! :) No hassle at all!
Preferences Sync It's an awesome feature!  I've fiddled with a few different extensions which have been plagued with "x" issue or "y" issue, so I'm excited to see an official one being shipped with Code!
