### ISSUE TITLE
Respect trailing comma style when organizing imports

### ISSUE THREAD

**Issue by ravshansbox** [microsoft/vscode#98123]
Issue Type: <b>Bug</b>

I use trailing comma when importing multiple modules in multi-line. When I call "Organize imports" vscode removes trailing commas. It should respect trailing comma styled used in the file.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
prettier-vscode|esb|4.7.0
vscode-styled-components|jpo|0.0.29

</details>

**Comment by mjbvz** [comment]
Please file this issue against prettier. VS Code's built-in organize imports is a good starting point but we leave more advanced configuration up to extensions

**Comment by ravshansbox** [comment]
I don't think prettier can do anything here, cause it's not prettier doing organize imports action.

**Comment by ravshansbox** [comment]
VSCode already doing this kind of thing with semicolons, quote styles. Why not do the same with trailing commas?

**Comment by ravshansbox** [comment]
Why not labelling the issue as 'to be closed' for a while before closing and give some time for discussing the problem and the close later if it's really required?

**Comment by mjbvz** [comment]
Please file a feature request against Prettier then. Trailing commas are in the domain of linters and  we think extensions can do a better job in that area

**Comment by ravshansbox** [comment]
I may not be using prettier and still I wouldn't want vscode to remove my commas in imports.
