### ISSUE TITLE
icon on the right of top disappear when open in wsl

### ISSUE THREAD

**Issue by Direct-A** [microsoft/vscode#98133]
- VSCode Version: 1.45.1
- OS Version: Windows_NT x64 10.0.19041.264
              wsl2 ubuntu 18.04.4
                   kernal 4.19.84-microsoft-standard

Steps to Reproduce:

1. connect to the remote
2. icon on the right of top disappear

in windows:
![in windows](https://s1.ax1x.com/2020/05/19/Y5iYvV.png)

in wsl:
![in wsl](https://s1.ax1x.com/2020/05/19/Y5FQsK.png)

Does this issue occur when all extensions are disabled?: No

**Comment by alexdima** [comment]
@Direct-A I guess your problem was with the proxy settings -- https://github.com/microsoft/vscode-remote-release/issues/3084
