### ISSUE TITLE
Unfold all keybinding does not work

### ISSUE THREAD

**Issue by lzantal** [Microsoft/vscode#9813]
Hi all,

I used the shortcut to fold all code in a python file. It worked perfect. 
But when I went to unfold all it didn't do anything. 
I used the shortcuts from here https://code.visualstudio.com/docs/customization/keybindings

Mac 10.11.6
VSCode: 1.3.1

Laszlo

**Comment by kieferrm** [comment]
@lzantal `⌘K ⌘0` and `⌘K ⌘J` work for me on Mac, in 1.3.1 and 1.4.0 without problems.

![thbetg6sme](https://cloud.githubusercontent.com/assets/4674940/17155437/ea7cc694-5339-11e6-933e-370154f176c7.gif)

Please reopen if you have additional info.
