### ISSUE TITLE
Bulk Editing: dispose reference even in error case

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98139]
It looks like the reference created from https://github.com/microsoft/vscode/blob/403be36aebd235bbf00b36b585969a20bc954a6f/src/vs/workbench/services/bulkEdit/browser/bulkEditService.ts#L169 is potentially not being disposed in error cases. You must always dispose it otherwise a model will hang around forever.

**Comment by jrieken** [comment]
this is very unlikely to happen because all references are help in an instance field which is disposed when the overall operation finishes

**Comment by bpasero** [comment]
Yeah I was mainly referring to only this error case, which is probably not a big deal:

https://github.com/microsoft/vscode/blob/dd2f659a863c9adb17a31f35841633411d8ff8ac/src/vs/workbench/services/bulkEdit/browser/bulkEditService.ts#L172-L174

**Comment by jrieken** [comment]
That's from the pre-strict-null days and according to the typing doesn't exist, e.g those lines should be deleted
