### ISSUE TITLE
dirtyDiffDecorator: reference leak

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98134]
Check out:

https://github.com/microsoft/vscode/blob/403be36aebd235bbf00b36b585969a20bc954a6f/src/vs/workbench/contrib/scm/browser/dirtydiffDecorator.ts#L1123

There is an early return without disposing the reference. You always need to dispose the reference, otherwise the model will leak forever.

**Comment by joaomoreno** [comment]
Hmmmmmm

https://github.com/microsoft/vscode/blob/452dc54c780481129c0d57ac5c0908c0a573a622/src/vs/workbench/contrib/scm/browser/dirtydiffDecorator.ts#L1131-L1131

**Comment by bpasero** [comment]
I was referring to:

https://github.com/microsoft/vscode/blob/403be36aebd235bbf00b36b585969a20bc954a6f/src/vs/workbench/contrib/scm/browser/dirtydiffDecorator.ts#L1125
