### ISSUE TITLE
vs code Update issue

### ISSUE THREAD

**Issue by kitkav** [microsoft/vscode#98130]
Issue Type: <b>Performance Issue</b>

when i update vs code it disappear exe file and i cant open the vs code so i have to uninstall it then install it again to make it work. fit it!!

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

**Comment by sanket-bhalerao** [comment]
@kitkav is it similar to #98142?

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
