### ISSUE TITLE
`completeJSDocs: false` does not fully disable autocompletion 

### ISSUE THREAD

**Issue by FicoPrieto** [microsoft/vscode#98143]
# Steps to Reproduce

1. Add the following options to `User\settings.json`:  
    ```json
    "typescript.suggest.completeJSDocs": false,
    "javascript.suggest.completeJSDocs": false,
    ```
2. Create a Javascript or Typescript file.
3. Type `/**` and press `enter`.

&nbsp;  
# Results
### Expected
A blank new line will be inserted, respecting the user's new line indentation settings.

### Actual
A new line is inserted with the following characters: `<space>*<space>`
![VSCode](https://user-images.githubusercontent.com/22942079/82300998-a075db80-9985-11ea-9b38-7aafe9e3be51.gif)

&nbsp;  
-----

- **VS Code version:**  
  Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
- **OS version:**  
  Windows_NT x64 10.0.18362
- **Does this issue occur when all extensions are disabled?:**
  Yes

**Comment by mjbvz** [comment]
These settings only control filling in the JS Doc template. The behavior you show is controlled by the onEnter rules with is closer to bracket machine. I don't think we provide a way to disable the on rules at the moment.

Marking as a feature request

**Comment by FicoPrieto** [comment]
@mjbvz

I'd argue that this is more of an unexpected behavior than a feature request. If I open up Notepad, type `/**`, and press `enter`; the editor will add a new line with no additional characters. VSCode is adding unexpected autocompletion functionality that cannot be disabled.

I also don't think the `editor-autoindent` tag is relevant (*or primary, at least*). The note about respecting users' new line indentation settings is more of a precautionary statement to ensure the consideration of indentation based settings being applied in a way that would be expected, since that feature also interacts with the scope of the issue. However, that is a separate piece of functionality that is only partially related to the actual issue of unwanted characters being added. Maybe the `suggest` tag is more relevant, since it is noted with `IntelliSense, Auto Complete`.

**Comment by mjbvz** [comment]
The feature request is to be able to disable this functionality :)
