### ISSUE TITLE
1.46.0-insiders update 2020-05-19

### ISSUE THREAD

**Issue by nokternol** [microsoft/vscode#98147]
Issue Type: <b>Bug</b>

Just an FYI: The most recent update failed due to looking for Code - OSS.exe
A previous update appears to have put all the files in a folder named "_ "
I assume this was the error in an earlier update but causes the recent one to fail as Code - OSS.exe is not in the expected path.
I moved all files from within the "_ " directory up one level and re-ran the update.
Awaiting completion to make sure this was the only problem.

VS Code version: Code - Insiders 1.46.0-insider (6849775440496504e0677ffcf2a46d47ad9130f5, 2020-05-15T05:30:56.857Z)
OS version: Windows_NT x64 10.0.17763

**Comment by Lifeismana** [comment]
Also there is a new install for vscode (non-insider) in control panel/program
When you uninstall this new version, updater keep reinstalling it

**Comment by gmutinel** [comment]
this fixed for me, thanks

**Comment by nokternol** [comment]
The above steps stop the error from occurring but it does not appear to fix the update.
Refer to the linked issue #98142 to keep track of the response.
So far, the suggestion is to download the latest version from the [website](https://code.visualstudio.com/insiders/)
