### ISSUE TITLE
Error with daily insiders update

### ISSUE THREAD

**Issue by AlanNevill** [microsoft/vscode#98142]
- VSCode Version: Insiders 1.46.0
- OS Version: Windows 10 1909

Steps to Reproduce:

1. Install in background
2.
Error Log
May 19 08:40:34.752 INFO Starting: C:\Program Files\Microsoft Code OSS\Code - OSS.exe, true
May 19 08:40:34.755 ERRO Bad arguments: Code path doesn't seem to exist: C:\Program Files\Microsoft Code OSS\Code - OSS.exe

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sanket-bhalerao** [comment]
Microsoft code OSS?
for the insiders, I could not download/install the update. so I downloaded the latest insiders build and tried to install and I get this message
![image](https://user-images.githubusercontent.com/9264813/82300111-05582280-99d4-11ea-80ad-bcf6dee18ff5.png)
I thought maybe last time downloaded a 32-bit installer and installed, so I uninstalled both code oss and vs code insiders. tried the latest code insiders install (which is now Microsoft code oss?) made sure I am downloading 64bit version twice, and after installation, there are no old extensions and not even the setting sync option.
tried to download and install the vscode insider and got the 
![image](https://user-images.githubusercontent.com/9264813/82300492-8d3e2c80-99d4-11ea-96cd-a91d08733972.png)
message again.
not sure what is happening.

this is the code version i am on currently
![image](https://user-images.githubusercontent.com/9264813/82300777-ee660000-99d4-11ea-9f11-124bb30085a2.png)

**Comment by RALMAZ** [comment]
Same

![inno_updater_YK4eYEGKJd](https://user-images.githubusercontent.com/26162860/82301238-a0470180-99c0-11ea-8984-9189c3c6d3e8.png)

Log:
```log
May 19 11:01:46.613 INFO Starting: C:\Users\Admin\AppData\Local\Programs\Microsoft Code OSS\Code - OSS.exe, true
May 19 11:01:46.615 ERRO Bad arguments: Code path doesn't seem to exist: C:\Users\Admin\AppData\Local\Programs\Microsoft Code OSS\Code - OSS.exe
```

**Comment by sanket-bhalerao** [comment]
> 
> 
> Same
> 
> ![inno_updater_YK4eYEGKJd](https://user-images.githubusercontent.com/26162860/82301238-a0470180-99c0-11ea-8984-9189c3c6d3e8.png)
> 
> Log:
> 
> ```
> May 19 11:01:46.613 INFO Starting: C:\Users\Admin\AppData\Local\Programs\Microsoft Code OSS\Code - OSS.exe, true
> May 19 11:01:46.615 ERRO Bad arguments: Code path doesn't seem to exist: C:\Users\Admin\AppData\Local\Programs\Microsoft Code OSS\Code - OSS.exe
> ```

i got this error too

**Comment by sanket-bhalerao** [comment]
duplicate https://github.com/microsoft/vscode/issues/98146

**Comment by sanket-bhalerao** [comment]
duplicate https://github.com/microsoft/vscode/issues/98147

**Comment by alexdevero** [comment]
Looks like release channels for Insiders and OSS got mixed.

**Comment by sanket-bhalerao** [comment]
the repository itself is showing Microsoft code OSS, is this new? or I am just finding it out now ?

**Comment by seritools** [comment]
Pretty sure the repo has always said it like that. Code - OSS is the open-source application, VSCode is that + Microsoft-specific additions.

**Comment by Lifeismana** [comment]
Also control panel/program report a new install of vscode (non-insider) after updater runs

**Comment by sanket-bhalerao** [comment]
duplicate https://github.com/microsoft/vscode/issues/98149

**Comment by FernandoMiguel** [comment]
duplicate https://github.com/microsoft/vscode/issues/98150

**Comment by isidorn** [comment]
Hi, we acknowledge this issue and are working on a fix at the moment.
Unfortunetly since the update is broken you will have to manually download the latest insiders version from our website. You can do that right now:
https://code.visualstudio.com/insiders/

Thank you very much for using insiders and we appologize for this issue.
I will pin this so more users see it.

**Comment by joaomoreno** [comment]
Fix is in, builds are running, let's see if was get a healthy Insiders build out today.

**Comment by isidorn** [comment]
Though even while the build is still running all our users can safely go to our side and download insiders. The version on the site is now a good one from yesterday.

**Comment by sillyfrog** [comment]
I'm sure you know already, but for others searching, the same also happens on MacOS. Downloading from the link above and copying over the top of it in Applications sorts it. Thanks for the quick response!

**Comment by joaomoreno** [comment]
Once again, sorry for all the breakage everyone! Everything should be back to normal by now.

**Comment by nokternol** [comment]
Woohoo... my extensions are all back working and vscode appears to live once more.
Thank you for the fast turn-around
