### ISSUE TITLE
Error: Error: spawn EACCES

### ISSUE THREAD

**Issue by jimcal** [Microsoft/vscode#9814]
- VSCode Version: Version 1.3.1 (1.3.1)
- OS Version: OS X 10.10.3

Steps to Reproduce:

1. change something in the file
2. Cmd + S 

will see this error message.
https://cl.ly/2j2i30002k3P

Also tried to uninstall/reinstall VS Code but were never able to do a clean uninstallation.

**Comment by kieferrm** [comment]
@jimcal  can you please provide concrete steps that help us to recreate the issue? What's in your workspace? Do you have a sample workspace exhibiting the behavior? Which extensions have you installed? Does the same happen when you launch vscode with the `--disable-extensions` command line option? Thanks!

**Comment by jimcal** [comment]
Well, the error is coming from extension, but I suspect the reason being Code didn't have proper permission. Would you be able to tell me how to give Code sudo permission?

To make this issue more relevant, perhaps you can also help me by uninstall Code cleanly and reinstall Code to see if this problem persist.

**Comment by kieferrm** [comment]
@jimcal 

```
rm -rf ~/.vscode
rm -rf ~/Library/Application\ Support/Code
```

should remove all metadata on your Mac.

**Comment by jimcal** [comment]
Thank you! Looks like reinstall clear the issue. I still think it's a permission issue and I don't know how to fix it without reinstall. I had my code worked in Sublime hence I would say it's about the IDE/editor than the Go code I had. Thanks for tips to removing the application metadata.
