### ISSUE TITLE
Can not auto install update

### ISSUE THREAD

**Issue by KaoImin** [microsoft/vscode#98149]
Issue Type: <b>Bug</b>

The VScode can download the new version, however, it reports
```
Could not locate update bundle for com.microsoft.VSCodeInsiders within file:///Users/.../com.microsoft.VSCodeInsiders.ShipIt/update.8rOw6BR/
```
after finish download it.

VS Code version: Code - Insiders 1.46.0-insider (6849775440496504e0677ffcf2a46d47ad9130f5, 2020-05-15T09:06:06.454Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.23.6
markdown-toc|Ala|1.5.6
vscode-sqlite|ale|0.8.2
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.35.2
vscode-dash|dee|2.4.0
vscode-wasm|dts|1.3.1
vscode-rust-syntax|dun|0.0.32
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
code-runner|for|0.10.0
terminal|for|0.0.10
mdmath|goe|2.4.0
latex-workshop|Jam|8.9.0
asciidoctor-vscode|joa|2.7.15
rust-doc-viewer|JSc|1.0.15
language-haskell|jus|3.2.1
Lua|key|0.0.9
rust-analyzer|mat|0.2.174
Lisp|mat|0.1.10
rainbow-csv|mec|1.7.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.2.0
vscode-language-pack-zh-hans|MS-|1.45.1
python|ms-|2020.5.78807
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.28.0
Go|ms-|0.14.2
powershell|ms-|2020.4.0
ide-purescript|nwo|0.20.15
language-purescript|nwo|0.2.4
erlang|pgo|0.5.2
phoityne-vscode|pho|0.0.25
material-icon-theme|PKi|4.1.0
pytorch-snippets|SBS|1.0.2
vscode-libra-move|SDK|0.0.10
crates|ser|0.4.9
code-settings-sync|Sha|3.4.3
vscode-autohotkey|sle|0.2.2
vscode-hexdump|sle|1.7.2
tabnine-vscode|Tab|2.8.2
latex-support|tor|3.2.0
codelf|unb|11.7.0
vscode-lldb|vad|1.5.0
tensorflow-snippets|vah|0.3.3
vscodeintellicode|Vis|1.2.7
vscode-icons|vsc|10.1.1
vim|vsc|1.14.4
autocomplete-english-word|wus|0.1.7
plsql-language|xyz|1.8.2
markdown-all-in-one|yzh|2.8.0
vscode-proto3|zxh|0.4.2

(1 theme extensions excluded)

</details>

**Comment by gtim108** [comment]
And when trying to install from the web it installs OSS build, not insiders. Is it intentional?

**Comment by ScarletFlash** [comment]
Same problem here:

<details>
  <summary>Error modal</summary>
  
![2020-05-19 115118](https://user-images.githubusercontent.com/22850353/82305974-177f9400-99c7-11ea-931e-022c093152e9.png)
[vscode-inno-updater-1589877552.log](https://github.com/microsoft/vscode/files/4649244/vscode-inno-updater-1589877552.log)
  
</details>

> Version: 1.46.0-insider (system setup)
> Commit: 6849775440496504e0677ffcf2a46d47ad9130f5
> Date: 2020-05-15T05:30:56.857Z
> Electron: 7.2.4
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.18363

**Comment by isidorn** [comment]
https://github.com/microsoft/vscode/issues/98142
