### ISSUE TITLE
Call hierarchy: show file details as description part

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98156]
I would like to see a bit more context for call hierarchy to understand which file is making the call:

![image](https://user-images.githubusercontent.com/900690/82312476-66c5c480-99c7-11ea-9d3a-cb0eeb3a78b5.png)

E.g. put the name of the file as the description part.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Acallhierarchy+label%3Afeature-request
