### ISSUE TITLE
Corrupt Extension Installation - setprototypeof is missing

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#98159]
Some users of my drawio extension get this error:

![](https://user-images.githubusercontent.com/5338052/82312478-675e5b00-99c7-11ea-9209-afa4a9f81800.png)

It does not happen very often, it is not really reproducable, [so at first, I thought it was just bad luck](https://github.com/hediet/vscode-drawio/issues/13).

But then I got another bug report [with the same missing package](https://github.com/hediet/vscode-drawio/issues/43).

I guess something really strange is going on. Maybe some virus scanner/a proxy server is unpacking/repacking the vsix file. If this is the case, it would be good if VS Code could check the checksum of the vsix file to detect that!

I don't think this is an issue of vsce, since it works for most of the users, independent of their setup. Downloading the vsix manually seems to fix it.

**Comment by jacokok** [comment]
Running McAfee and Windows Defender on work computer that could be the cause of this.
On home PC all works as expected.

Bugs like these are the worst. 
I am happy to do manual install on work PC if it fails again.

Thanks for the help.

**Comment by alexdima** [comment]
@sandy081 This appears to be an installation problem. The extension is installed/unzipped incompletely.

**Comment by sandy081** [comment]
@hediet Can you please engage me with the user seeing this issue. It would be great if user can repro this and we can diagnose the root cause.

**Comment by jacokok** [comment]
I was having this issue on my work laptop. Happy to try and help reproduce this error.

**Comment by sandy081** [comment]
@jacokok If you are able to repro

- Can you try to reinstall the extension using the command `Developer: Reinstall extension` and try again?

**Comment by jacokok** [comment]
Sorry for the late feedback was unable to get to the office for a while and it works from my home PC.

Unfortunately I was not able to reproduce again and it is working with Developer: Reinstall extension.
Also downgraded to version 0.4 of the extension that was causing the issue and all worked this time.

My theory at this stage is that the proxy server cached an invalid version of the extension.

**Comment by sandy081** [comment]
No worries, please reopen it when you see it again
