### ISSUE TITLE
failure to upgrade

### ISSUE THREAD

**Issue by FernandoMiguel** [microsoft/vscode#98150]
Issue Type: <b>Bug</b>

```
2020-05-19 09:57:30.021 Electron[71867:3407309] Download completed to: file:///Users/fernando/Library/Caches/com.microsoft.VSCodeInsiders.ShipIt/update.WNLZhs6/VSCode-darwin-insider.zip
[main 2020-05-19T08:57:31.825Z] UpdateService error: Could not locate update bundle for com.microsoft.VSCodeInsiders within file:///Users/fernando/Library/Caches/com.microsoft.VSCodeInsiders.ShipIt/update.WNLZhs6/
[main 2020-05-19T08:57:31.825Z] update#setState idle
[71867:0519/095731.826856:INFO:CONSOLE(2892)] "Could not locate update bundle for com.microsoft.VSCodeInsiders within file:///Users/fernando/Library/Caches/com.microsoft.VSCodeInsiders.ShipIt/update.WNLZhs6/", source: file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (2892)
```

VS Code version: Code - Insiders 1.46.0-insider (6849775440496504e0677ffcf2a46d47ad9130f5, 2020-05-15T09:06:06.454Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.59GB free)|
|Process Argv|--verbose --log debug|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
markdown-toc|Ala|1.5.6
inline-hasher|ale|1.0.0
spellright|ban|3.0.50
git-temporal-vscode|bee|1.0.0
better-toml|bun|0.3.2
hadolint|exi|0.3.0
github-actions|for|0.0.1
terraform|mau|1.4.0
markdown-shortcuts|mdi|0.12.0
vscode-docker|ms-|1.2.0
github-actions-vscode|Oma|2.7.0
vscode-yaml-sort|Pas|2.3.1
errorlens|Phi|1.1.3
git-file-history|pom|1.0.1
vscode-yaml|red|0.8.0
vscode-gitweblinks|red|1.6.0
vscode-nginx|sha|0.6.0
shellcheck|tim|0.9.0
sort-lines|Tyr|1.9.0
vscode-icons|vsc|10.1.1

</details>

**Comment by isidorn** [comment]
https://github.com/microsoft/vscode/issues/98142
