### ISSUE TITLE
Version Invalid

### ISSUE THREAD

**Issue by blockfan7** [microsoft/vscode#98151]
yesterday, I upgraded flutter to the latest one.
after that, VS code can not run Flutter.
Could you please help me?

**Comment by IllusionMH** [comment]
/needsMoreInfo
Do you know how exactly it's related to editor itself and not an extension?
Did you update Flutter extension or local installation?

Most likely you need to ask general question about setup on StackOverflow or check existing issues/report new in https://github.com/Dart-Code/Dart-Code/issues

Also see https://github.com/Dart-Code/Dart-Code/issues/2464

**Comment by blockfan7** [comment]
I am really surprised that the support team is strong and give me exact answer immediately.
Thank you.

**Comment by DanTup** [comment]
I think https://github.com/Dart-Code/Dart-Code/issues/2576 is describing the same issue.  The Dart/Flutter extensions don't have the message shown in the screenshot there, so I don't think it's related to Dart/Flutter extensions.
