### ISSUE TITLE
Call hierarchy: allow to remove nodes

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98155]
Similar to "Find References", allow me to remove individual nodes from the call graph, e.g. to exclude references that I reviewed (or from tests).

![image](https://user-images.githubusercontent.com/900690/82312431-5281c780-99c7-11ea-87d9-4ee5ad644dac.png)

**Comment by babakks** [comment]
I'd like to work on this.

Is there notes/tips that I'd be better aware of?

**Comment by mitchell-frost** [comment]
I am new here. Can I work on this?

**Comment by jrieken** [comment]
@babakks was first

The sources are in a separate extension here: https://github.com/microsoft/vscode-references-view/blob/846367409ec890e3415c919db772c3fbfe01f41e/src/extension.ts#L356

**Comment by babakks** [comment]
@jrieken I've made the [PR][pr].

[pr]: https://github.com/microsoft/vscode-references-view/pull/61

**Comment by jrieken** [comment]
Done. Thanks @babakks
