### ISSUE TITLE
Code Helper Renderer

### ISSUE THREAD

**Issue by antoniofarina** [microsoft/vscode#98168]
Issue Type: <b>Performance Issue</b>

When VS Code runs for a long time, the process Code Helper eat 100%  of the CPU

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   17	    82	 54389	code main
    7	   229	 54391	   gpu-process
    0	    33	 54393	   utility
    0	   131	 54394	   window (strings.json — translated.com)
    1	    49	 54950	     extensionHost
    0	     0	 56094	       electron_node tsserver.js 
    0	    16	 56096	       electron_node tsserver.js 
    0	     0	 56132	         electron_node typingsInstaller.js typesMap.js 
    0	    16	 56106	       electron_node eslintServer.js 
    0	     0	 56147	       electron_node server.js 
    0	     0	 56148	       /usr/local/opt/php@7.3/bin/php /Users/antonio/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/felixfbecker/language-server/bin/php-language-server.php --tcp=127.0.0.1:59272 --memory-limit=4095M
    0	     0	 54951	     /bin/zsh -l
    0	     0	 55267	     watcherService
   53	    66	 54947	   shared-process
    0	   311	 56320	   window (Settings — marketing)
    1	    82	 56323	     extensionHost
    0	   246	 56495	       php /Users/antonio/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/felixfbecker/language-server/bin/php-language-server.php --tcp=127.0.0.1:59317 --memory-limit=4095M
   96	    16	 56509	       electron_node server.js 
    0	     0	 63144	       electron_node server.js 
    0	     0	 56324	     /bin/zsh -l
    0	    16	 56388	     watcherService
```

</details>
<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-test-explorer|hbe|2.18.1
composer|ika|0.7.1
php-cs-fixer|jun|0.1.153
git-graph|mhu|1.22.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.2.0
sublime-keybindings|ms-|4.0.7
vscode-phpunit|rec|2.0.72
phpdoc-comment-vscode-plugin|rex|1.3.0

</details>

**Comment by kieferrm** [comment]
What file types besides `php` are open when this happens?

**Comment by NathanDowner** [comment]
@kieferrm I have been experiencing the same issue after upgrading this morning. But the CPU usage climbs well past 100% without having to open any files at all. After 15 seconds the usage jumped to 151%

**Comment by NathanDowner** [comment]
@kieferrm I have been experiencing the same issue after upgrading this morning. But the CPU usage climbs well past 100% without having to open any files at all. After 15 seconds the usage jumped to 151%

<img width="856" alt="Screenshot 2020-05-22 at 11 36 11 PM" src="https://user-images.githubusercontent.com/32402220/82722495-e89a4400-9c8c-11ea-9c67-f6d6cb54bcad.png">
<img width="912" alt="Screenshot 2020-05-23 at 12 26 46 AM" src="https://user-images.githubusercontent.com/32402220/82722508-05cf1280-9c8d-11ea-9ee6-c4340537371b.png">


## VS Code Info
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

## Extensions:
aaron-bond.better-comments
adrianwilczynski.asp-net-core-switcher
alexdima.copy-relative-path
Angular.ng-template
anseki.vscode-color
christian-kohler.path-intellisense
codezombiech.gitignore
CoenraadS.bracket-pair-colorizer
craigthomas.supersharp
cstrap.flask-snippets
Dart-Code.dart-code
Dart-Code.flutter
dbaeumer.vscode-eslint
doggy8088.netcore-extension-pack
doggy8088.netcore-snippets
dsznajder.es7-react-js-snippets
EditorConfig.EditorConfig
eg2.vscode-npm-script
esbenp.prettier-vscode
felipe.nasc-touchbar
fivethree.vscode-ionic-snippets
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
formulahendry.dotnet
formulahendry.dotnet-test-explorer
Gruntfuggly.todo-tree
jchannon.csharpextensions
jmrog.vscode-nuget-package-manager
johnpapa.angular-essentials
johnpapa.Angular2
johnpapa.vscode-peacock
johnpapa.winteriscoming
k--kato.docomment
Leopotam.csharpfixformat
ms-azuretools.vscode-docker
ms-dotnettools.csharp
ms-mssql.mssql
ms-python.python
ms-vscode.vscode-typescript-tslint-plugin
ms-vsliveshare.vsliveshare
msjsdiag.debugger-for-chrome
msjsdiag.debugger-for-edge
msjsdiag.vscode-react-native
natewallace.angular2-inline
nrwl.angular-console
octref.vetur
PKief.material-icon-theme
quicktype.quicktype
ritwickdey.LiveServer
schneiderpat.aspnet-helper
sdras.vue-vscode-snippets
tintoy.msbuild-project-tools
VisualStudioExptTeam.vscodeintellicode
wayou.vscode-todo-highlight
whizkydee.material-palenight-theme

**Comment by NathanDowner** [comment]
Update, it calms right back down after about 15 or so minutes

**Comment by markedwards** [comment]
I also have been seeing this issue on 1.45.1.  I don't notice it subsiding after 15 minutes, it seems to go on for much longer, and I don't see a particular pattern.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|8.00GB (0.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: me_dev|
|OS|Linux x64 4.14.173-137.229.amzn2.x86_64|
|CPUs|AMD EPYC 7571 (2 x 2199)|
|Memory (System)|7.71GB (1.57GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container XXXXXXXXXXXXXXX…|
|OS|Linux x64 4.14.173-137.229.amzn2.x86_64|
|CPUs|AMD EPYC 7571 (2 x 2199)|
|Memory (System)|7.71GB (1.57GB free)|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.2.0
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0


</details>

**Comment by markedwards** [comment]
Also, I notice that Code Helper (Renderer) continues to run at 90-100% even after quitting VSCode.

**Comment by ggoodman** [comment]
I am also seeing `Code Helper (Renderer)` continuing to consume CPU even after quitting out of `vscode`. It appears to be pinning 1 core at 100% (maybe stuck in a sync loop and not responding to graceful exit signal?).

**Comment by mesqueeb** [comment]
i have had the same issue for the past week. Code Helper Renderer makes CPU stuck at 100% and **stays open after quitting VSCode**.

My Macbook has never been so hot as this past week, i'm getting scared.

**Comment by egamma** [comment]
@mesqueeb @ggoodman @markedwards pls file separate issue with a performance profile by following the steps described here https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by markedwards** [comment]
@egamma I haven't had the issue since I posted here, so I can't repro at the moment.  If it comes back I will file a separate issue.

**Comment by nandorojo** [comment]
Exact same thing happens to me when I run `gatsby develop` from the VSCode terminal. 

<img width="949" alt="Screen Shot 2020-06-08 at 1 31 12 PM" src="https://user-images.githubusercontent.com/13172299/84061865-a65f4b00-a98c-11ea-8639-1525e5c5614e.png">

I have 64GB of ram on 16 inch Macbook pro, but when this happens, I see completely broken intellisense. Only fix is to quit and re-open VSCode.

<img width="578" alt="Screen Shot 2020-06-08 at 1 13 55 PM" src="https://user-images.githubusercontent.com/13172299/84061901-b840ee00-a98c-11ea-9f7f-c97c47a2405c.png">

**Comment by egamma** [comment]
The CodeHelper process is running extensions and typically it is the extensions that cause the high CPU load. To help to narrow this down please follow this guide https://github.com/microsoft/vscode/wiki/Performance-Issues.

**Comment by viridia** [comment]
I experience this issue frequently. I have started habitually terminating the code help renderer process about once a day, since that is about how long it takes for the problem to manifest. Sometimes I see multiple copies of the renderer process - usually after I switch between several projects.

**Comment by viridia** [comment]
<img width="815" alt="Screen Shot 2020-06-29 at 3 01 46 PM" src="https://user-images.githubusercontent.com/1166135/86060461-967dd880-ba19-11ea-9b5b-7443eab94230.png">

**Comment by bmitchinson** [comment]
Also experiencing this, anyone have ideas on how to debug / see what part of VSCode is causing this demand?

**Comment by sashwatp** [comment]
I am also facing this issue. Not sure what is the solution. I verified that the search excludes 


```
"search.exclude": {
  "**/node_modules": true,
  "**/bower_components": true,
  "**/*.code-search": true
}

"files.exclude": {
  "**/node_modules": true
}
```

**Comment by kylehotchkiss** [comment]
To extend what @sashwatp said (as I'm encountering the same issue recently), I added the following to my files/search exclusion in case some background process is trying to index them:

* `**/.next` (nextjs)
* `**/.cache` (parcel)
* `**/dev`
* `**/dist`

**Comment by sjloyola** [comment]
I get this problem only with a project that uses SVN. All my Git projects are cool. Pun intended, because the SVN project makes my Mac nice and toasty, currently Code Helper (Renderer) is using 234% CPU!

**Comment by sjloyola** [comment]
SOLVED IT! (At least for me.) I take back my SVN accusation. That wasn't it. Code Helper (Renderer) became a CPU hog for me only when the project I was working on had **two recursive symbolic links that pointed to the same place** (note: not my design). At first I thought it might be the occurrence of any recursive symlink but VS Code handles one of those just fine. But have a directory structure like this:

```
A
    B1
        abc -> ../..
    B2
        abc -> ../..
```

and you'll see a Code Helper (Renderer) apparently get stuck in a double infinite loop and turn your computer into a room heater.

I suspect this means that VS Code is smart enough to catch itself in a **single** infinite symlink loop but having two interacting loops lets it alternate back and forth ad infinitum!

**Comment by restfulhead** [comment]
I've also started to see this after using `npm link`, which creates symbolic links. This issue should be re-opened.
