### ISSUE TITLE
Syntax/props coloring VSCode

### ISSUE THREAD

**Issue by gothdawid** [microsoft/vscode#98167]
Short description:
VSCode does not color my properties from prisma. Below are the extensions and the theme
Anyone have an idea how to fix it?

https://github.com/prisma/prisma/issues/2411#issue-615779088

**Comment by kieferrm** [comment]
@gothdawid does any theme color the properties?

**Comment by gothdawid** [comment]
![image](https://user-images.githubusercontent.com/5568734/82459862-b89a4780-9ab8-11ea-9fb0-78228554ce6f.png)
where, update, create .... no have color.

I had it so that for a second after opening the file it was colored. But it's not now.

I use "Material Theme" and "Material Theme Icons"

Changing the theme also has no improvement.

**Comment by kieferrm** [comment]
@aeschli related to semantic highlighting?

**Comment by aeschli** [comment]
@gothdawid You can run the `Inspect Editor Tokens And Scope` command to see where the color comes from.
It is related to semantic highlighting, as with semantic highlighting, `where`, `update`, ... are now classified as object properties, while TextMate grammars had a special thing called `object literal key` that could be colored in a different way.
We have https://github.com/aeschli/typescript-vscode-sh-plugin/issues/12 to bring this back.
