### ISSUE TITLE
UI corruption, editor font blur look bad for no reason, I don't know this issue

### ISSUE THREAD

**Issue by KInGATiLLa** [microsoft/vscode#98163]
- VSCode Version: 1.45.1 (in all versions)
- OS Version: Windows 10 Pro 1909 build:18363.836
- NodeJS 12.16.3
- Display ASUS vg258qr 165hz
- GPU NVIDIA RTX2060
- Cable - DisplayPort

Steps to Reproduce:

1. I changed some NVIDIA control panel settings
2. It will not appear for the first 30 minutes
3. **UI corruption** after 30min like this

![ezgif com-optimize](https://user-images.githubusercontent.com/17881842/82321817-0b67f680-9a08-11ea-90bf-8d579fb48441.gif)

Does it depend on GPU configuration? Or something else?

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
/needsMoreInfo

You can try to launce code with `--disable-gpu` or `--force-color-profile srgb` to see if it helps.

**Comment by KInGATiLLa** [comment]
> /needsMoreInfo
> 
> You can try to launce code with `--disable-gpu` or `--force-color-profile srgb` to see if it helps.

@IllusionMH  I didn't try anything else on vscode settings.

**Comment by IllusionMH** [comment]
In my previous comment there are 2 launch flags that should be used as `code --disable-gpu`.

You should try them to see if launching code with these settings helps.

**Comment by KInGATiLLa** [comment]
> In my previous comment there are 2 launch flags that should be used as `code --disable-gpu`.
> 
> You should try them to see if launching code with these settings helps.

Ok I'll try again.

**Comment by KInGATiLLa** [comment]
@IllusionMH hey, I have a question. Do I have to write this flag(--disable-gpu) everytime i launch vscode? Is it okay to write one?

**Comment by IllusionMH** [comment]
You need to launch it with this flag from cmd which is faster for test purposes, however you can add this one to configuration: following steps here https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration which is better for permanent flags
