### ISSUE TITLE
Search with Regex kills VS code

### ISSUE THREAD

**Issue by thunderbug1** [microsoft/vscode#98169]
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-91-generic

This bug kills the VS-code instance.
The regular expression itself works, tested here: https://regex101.com/

Steps to Reproduce:

1. open file containing:  {{ form.sku_form.sku_type.label }}
2. Ctrl+F to open search bar
3. activate regular expression search
4. paste regex:   (\{\{ )(([a-zA-F0-9_-]+|.)+)(.label \}\})

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
In your case properly escaping `.` as `\.` and avoiding `([...]+)+` (which is same as `([...]+|...)+`)
Simplified expression shouldn't hand VS Code `(\{\{ )(([a-zA-F0-9_-]+\.?)+)(\.label \}\})`
