### ISSUE TITLE
Not able to login to Visual Studio 2019 for Mac using Microsoft username and password(employee).

### ISSUE THREAD

**Issue by fooldrool** [microsoft/vscode#98162]
- VSCode Version:2019
- OS Version:MacOS Catalina

Steps to Reproduce:

1. Try to sign in using Microsoft Official email id and password(Microsoft employee email id and password).
2. Then take phone verification on step 2.

It will again redirect to sign in page without signing-in after successful authentication.

Note: I am able to successfully sign-in using my personal email id and password.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
@fooldrool Are you using **Visual Studio** or **Visual Studio Code**? They are two different products. This GitHub repository is only for VS Code.

**Comment by fooldrool** [comment]
> @fooldrool Are you using **Visual Studio** or **Visual Studio Code**? They are two different products. This GitHub repository is only for VS Code.

Visual Studio

**Comment by gjsjohnmurray** [comment]
@fooldrool so please close this issue here and raise your problem on a Visual Studio support channel.
