### ISSUE TITLE
Ignore Errors from Package.json file

### ISSUE THREAD

**Issue by Noorullah-Ahmadzai** [microsoft/vscode#98166]
How do I tell vscode to completely ignore warning and errors from Package.json file.
Thanks!

**Comment by aeschli** [comment]
Can you explain why you don't like the warnings from package.json?

**Comment by Noorullah-Ahmadzai** [comment]
![warning](https://user-images.githubusercontent.com/28804764/82561366-848e5780-9b88-11ea-8fa5-00503746176b.png)
Everytime I open up my vscode. I see this warning. I mostly mistake it for a linting bug in my source code which is very annoying and distracting. I tried everything to get rid of it. even read the previous issues about it but I have no idea how to fix it.

**Comment by Noorullah-Ahmadzai** [comment]
Can I get some feedback on this issue? 
It's been a long time since I created it and no feedback whatsoever. :(

**Comment by aeschli** [comment]
Can you access the url from a browser?
Is this because of connectivity issues? Or proxy configuration issues?

You can turn off schema loading with `"json.schemaDownload.enable": false`

**Comment by Noorullah-Ahmadzai** [comment]
It mostly happens when I am offline! 
I think that would do it.
Thanks!
