### ISSUE TITLE
VS Code kept attached to the terminal it was started from

### ISSUE THREAD

**Issue by AnrDaemon** [microsoft/vscode#98164]
Issue Type: <b>Bug</b>

Start VS Code from a terminal (cmd, bash, Far manager… whatever).
Wait a bit.
VS Code spamming console with logs.
![image](https://user-images.githubusercontent.com/6532485/82323090-38081800-99e0-11ea-8704-d4b8e179f23b.png)

It doesn't matter, how you start it, no amount of tricks would help. Even starting through a batch file in a separate console won't help.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz (4 x 3303)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (5.32GB free)|
|Process Argv|C:\Users\anrdaemon\Documents\.github\SimpleCache|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.3.11
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
php-debug|fel|1.13.0
todo-tree|Gru|0.0.175
smarty|imp|0.3.0
svn-scm|joh|2.11.1
sqltools|mtx|0.21.7

</details>

**Comment by IllusionMH** [comment]
How exactly are you launching `VS Code`?
Are you launching `code.exe` or `bin/code.cmd`?  if it's just `code` does your `PATH` contain `bin` at the end of the VS Code related folder?

Looks similar to #1369

**Comment by AnrDaemon** [comment]
In most common case, I use shell extension. Which launches `code.exe` directly as per Windows association.

No, I don't pollute my %PATH% with unnecessary… paths.

The issue you linked seems wholly unrelated. Did you mistype the number?

**Comment by IllusionMH** [comment]
Yep, correct one is #73789

> Which launches `code.exe` directly

For launches from cmd etc. it should use `bin/code.cmd` instead of `code.exe` directly.

**Comment by AnrDaemon** [comment]
Why it should? Why can't I use a program and OS like it's supposed to? There's a file type association, and it should behave the same for all intents and purposes.

I can't even get away from it, if I `START "" cmd /C "code.exe" Somedir\`. The Code.exe mysteriously WILL STILL know what terminal it was started from. Even if I chain multiple `cmd.exe`'s that would die long before `code.exe` is started. It seems like a dark magic, not an application behaving by the rules of the OS.

**Comment by Tyriar** [comment]
I suspect this is by design, but @joaomoreno might have more ideas.

**Comment by joaomoreno** [comment]
@IllusionMH is on the right track. Due to a limitation in Electron, you are forced to use the launcher in our `bin` folder if you want to run from the command line. This is why we add the `bin` folder to the PATH instead of exposing `Code.exe`.
