### ISSUE TITLE
Incorrect syntax colouring in `for` loops and statements starting with `for`

### ISSUE THREAD

**Issue by nullie** [microsoft/vscode#98179]
Version: 1.46.0-insider (user setup)
Commit: 6849775440496504e0677ffcf2a46d47ad9130f5
Date: 2020-05-15T05:30:56.857Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

Edit following Python code:
```python
forvariable = None
for a, b, c, invariable in [2 in q, 2 in w]:
    pass
```
![image](https://user-images.githubusercontent.com/355392/82340514-c0021800-9a08-11ea-8f22-70662cf456a5.png)

Does this issue occur when all extensions are disabled?: Yes

Originally reported in: https://github.com/microsoft/vscode-python/issues/11828 by @carlca
This is upstream issue in MagicPython: https://github.com/MagicStack/MagicPython/issues/211

Introduced in VSCode insiders with this commit: https://github.com/microsoft/vscode/commit/884fcedf97090348ba063709129fb1ede5b353b4#diff-3a8bc38ff5f89f092ec7f7c5f0d249b7 by @alexr00 

This issue is now fixed in MagicPython, so grammars have to be either updated to latest from MagicPython or reverted to ones before https://github.com/MagicStack/MagicPython/commit/2ca894f270f92e2bc8f09a2ebdcd482fbb3b1074

As a workaround MagicPython extension v1.1.0 can be installed from marketplace.

**Comment by alexr00** [comment]
@nullie thank you for the detailed information!
