### ISSUE TITLE
Windows Installer Doesn't Honor the /CLOSEAPPLICATIONS and /FORCECLOSEAPPLICATIONS Command-Line Parameters

### ISSUE THREAD

**Issue by bmkaiser** [microsoft/vscode#98174]
- **VSCode Version**: 1.45.0 (installed), 1.45.1 (installer)
- **OS Version**: Windows 10 1909 (10.0.18363.815)

## Steps to Reproduce:

1. Open Visual Studio Code
2. Run the EXE with one of the above mentioned command-line parameters. For example: `VSCodeUserSetup-x64-1.45.1.exe /closeapplications`
3. You will get a warning message that says: **Setup has detected that Visual Studio Code is currently running.**
![image](https://user-images.githubusercontent.com/5446414/82325000-87caed00-99a8-11ea-8569-1f07344345b6.png)

Does this issue occur when all extensions are disabled?: Not applicable

## Additional Information

- Expected behavior is that the running instance of VS Code would be closed automatically by the installer (causing the possible loss of work)
- It may be worth noting that in my test, I was testing switching from the System Installer to the User Installer. So I currently have the System Installer version of VS Code installed and was attempting to see what would happen when I run the User Installer version.
- Command-Line Parameter documentation can be found here: https://jrsoftware.org/ishelp/index.php?topic=setupcmdline

**Comment by joaomoreno** [comment]
Even though that flag is present in Inno, we don't support it, especially because it can cause data loss.
