### ISSUE TITLE
Implement smooth scrolling for lists/trees

### ISSUE THREAD

**Issue by stackprogram** [microsoft/vscode#98175]
About this Explorer-smooth topics have already a question that does not have an answer. I love VS code but I don't like the Explorer hard scrolling effect 😥, I like the smooth scrolling effect 🔥.

```"editor.smoothScrolling": true,``` using this setting I can get only the editor smooth scrolling not the explorer.
If there are any settings available for this effect please help otherwise I request to make it effective as soon as possible. 😏

again my questions are
1. Is it possible to make smooth scrolling like editor scroll effect to explorer tree scrolling
2. Is it possible to decrease the width of the scrollbar of the explorer?

**Comment by isidorn** [comment]
This feels like a list issue. Thus forwarding to @joaomoreno 
I am not sure if we support smooth scrolling in the lists, or what exactly smooth scrolling is to be honest.

**Comment by stackprogram** [comment]
please see my new update and is it possible then plz help.

**Comment by joaomoreno** [comment]
@stackprogram Can you elaborate on what `editor.smoothScrolling` changes for you? 
Can you please provide a [screen recording](https://gifcap.dev/)?

**Comment by musm** [comment]
Does the fix also apply to the editor/problems widget ?

**Comment by joaomoreno** [comment]
Yes it should.

**Comment by musm** [comment]
I also don't get smooth scrolling in the terminal box.

**Comment by roblourens** [comment]
I was just trying this and it's also not clear to me.

**Comment by joaomoreno** [comment]
Please test this on Windows/Linux with a mouse which has a discrete scroll wheel.

macOS won't work since the scrolling is continuous.

**Comment by connor4312** [comment]
Windows with my G502 mouse does not smooth scroll at all, either in the editor or list views 🤔

**Comment by musm** [comment]
> Windows with my G502 mouse does not smooth scroll at all, either in the editor or list views 🤔

Did you first enable smooth scroll in the settings 😄
