### ISSUE TITLE
Missing Javascript language and its identifier

### ISSUE THREAD

**Issue by prem48science** [microsoft/vscode#98171]
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Description
I can't find Javascriptlanguage in Select Language mode. ANYWHERE. I find all the extensions to use it better but, can't find the javascript option.
Vs code shows .js files as plain text and doesn't show javascript file identifier. 
this happened after suddenly chrome has crashed and I reinstalled chrome.
![Annotation 2020-05-19 184416](https://user-images.githubusercontent.com/16649351/82332687-56333f80-9a03-11ea-87b0-9812264f33f2.jpg)

![Annotation 2020-05-19 1844116](https://user-images.githubusercontent.com/16649351/82332725-60edd480-9a03-11ea-87ba-f436648aa506.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
In the extensions view search `@builtin javascript`. Is the `JavaScript and TypeScript language features` extension disabled?

**Comment by prem48science** [comment]
hi, sorry for the delay. No, nothing has been disabled. the problem was my corrupted hard drive I guess. files were being corrupted and I didn't know that a failed hard drive can corrupt parts of data randomly. my system got shut down and i have to replace the hard drive. now there is no problem. i feel the issue with VS code is also related to it.
