### ISSUE TITLE
[VSCode insiders] Font size in markdown preview cannot be changed

### ISSUE THREAD

**Issue by rami3l** [microsoft/vscode#98178]
- VSCode Version: 1.46.0-insider
- Commit: da3bf754c3c0eabda1dc80ed9d627679ee560697
- OS Version: macOS 10.15.4

Steps to Reproduce: same as #88344

PS: I am using the `"markdown.preview.fontSize"` option.

Does this issue occur when all extensions are disabled?: Yes, tried with `code-insiders --disable-extensions` and the problem is not solved.

**Comment by mjbvz** [comment]
Broken by 6fcec00d9235e3b3f9c726947477ca44ce73f78c
