### ISSUE TITLE
F8 in notebooks issues

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#98172]
Issue Type: <b>Bug</b>

Using a GH Issues notebook.

1) I have a notebook with multiple cells referencing a macro. Change the name of the macro so that all cells using it show an error.
2) F8 repeated
-> From time to time, cells that have the keyboard focus are not revealed correctly.
-> Sometime, the F8 problem zone gets stuck. I.e. while the keyboard focus moves forward the cell with the F8 problem zone stays in place.
-> When scrolling a cell with a F8 problem zone out of sight and then F8 again, the two problems become severe.

VS Code version: Code - Insiders 1.46.0-insider (da3bf754c3c0eabda1dc80ed9d627679ee560697, 2020-05-19T10:04:14.981Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.3.0-1020-azure

**Comment by jrieken** [comment]
Indeed - this goes bust when I have enough markdown between two code cells...


[May-19-2020 16-39-37.mp4.zip](https://github.com/microsoft/vscode/files/4651137/May-19-2020.16-39-37.mp4.zip)

**Comment by jrieken** [comment]
I cannot reproduce anymore. @kieferrm can you give it another shot?
