### ISSUE TITLE
Up and down arrows work on shell history and the IME proposal window at the same time.

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#9817]
Testing #9695 on MacOS:

Disclaimer: I don't really know what I'm using IME, I don't speak any of those languages.

Steps to reproduce:
1)  Configure your keyboard:

<img width="678" alt="screen shot 2016-07-26 at 3 36 00 pm" src="https://cloud.githubusercontent.com/assets/4674940/17157800/b82c68c2-5346-11e6-8bd6-28f41e7ebda8.png">

2) See screen recording: I'm typing a rather random sequence of key strokes and sometimes select another proposal using the `down arrow` followed by `space` to insert it. 

3) When the selection is at the top of the proposal window and I type `up arrow` the shell goes back in history. This might or might not be the right thing. Press the `up arrow` a few times.

4) Pressing the `down arrow` now changes the selection in the proposal window as well as scrolling forward in the shell's history.  This doesn't seem right.

![fdqrx1tpju](https://cloud.githubusercontent.com/assets/4674940/17157925/a813d14a-5347-11e6-9334-1d3d1ed68d1f.gif)

**Comment by kieferrm** [comment]
On further contemplation: The scrolling only happens on `character boundaries`, i.e. after having hit `space` for committing a character and while in a character composition. So, this might or might not be the intended behavior.

**Comment by Tyriar** [comment]
Marking for August as it's non-critical and an upstream issue.

**Comment by Tyriar** [comment]
Doesn't actually reproduce on Ubuntu using ibus hangul

**Comment by Tyriar** [comment]
Closing as designed as it only happens on Mac meaning the IME itself is allowing it to happen.
