### ISSUE TITLE
Stack View in VS Code

### ISSUE THREAD

**Issue by danrald** [microsoft/vscode#98184]
This is not really and issue. When I work, I am working with anywhere between 5 and 30 files at a time in my web project. The stack is large. Is there anyway to set up a view or multiple view that will show all the files in the stack. So say I'm working on the Users page, I want to be able to add all the files to a "View" called Users stack that will show all front end and back end files. I can create one for Accounting.. etc. 
Do we have this option? 

Thanks!

**Comment by kieferrm** [comment]
Not in core VS Code. Not sure of that is of any help but you could change the size of the `Open editors` section. There are also a bunch of bookmark extensions in marketplace, but I haven't checked them out.

**Comment by kieferrm** [comment]
This is the original issue: #9498.
