### ISSUE TITLE
Shortcuts, doesnt work with the propper keys. 

### ISSUE THREAD

**Issue by quodvis** [microsoft/vscode#98187]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I use dvorak spanish layout. And the keyboard is a spanish layout.  When I need cut. must be ctl-x en dvorak. the 'x' is in the leter 'b' position in my keyboard. But doesnt work. I must do ctl-q to cut. ctl-j to copy, y ctl-k to paste.  Some times, work well, anothers times, not. 

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.6.8-100.fc30.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2228)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.48GB (0.47GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
csharpextensions|jch|1.3.1
bash-ide-vscode|mad|1.10.0
vscode-docker|ms-|1.2.0
csharp|ms-|1.21.18
vscode-kubernetes-tools|ms-|1.2.0
python|ms-|2020.5.78807
java|red|0.61.0
vscode-yaml|red|0.8.0
python|tht|0.2.3
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.1
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.22.4
vscode-maven|vsc|0.21.4

</details>

**Comment by alexdima** [comment]
Does any of the following characterise your system? https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings
