### ISSUE TITLE
Screen deformation

### ISSUE THREAD

**Issue by atakilic** [microsoft/vscode#98183]
Issue Type: <b>Bug</b>

While using VSCode(1.45.1), there are so many blue, red and type of green or yellow squares on the screen. In the explorer pane, there are more less but they are everywhere in editor pane.
On previous versions, I had no problem like this.

screenshot
![vscode-problem](https://user-images.githubusercontent.com/17612996/82345879-744a7100-99fe-11ea-8bab-e66a395b5c05.jpg)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.901.7
todo-tree|Gru|0.0.175
Angular2|joh|9.1.2
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.7
vscode-icons|vsc|10.1.1

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

is it reproducible when you launch it as `code --disable-gpu` flag?
See alternative solution https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Comment by atakilic** [comment]
> /needsMoreInfo
> 
> is it reproducible when you launch it as `code --disable-gpu` flag?
> See alternative solution https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

Hi,
I applied your solution. It worked. It's related hardware or gpu driver. When I disabled hardware acceleration, I didn't see any deformation. 
Thank you!
