### ISSUE TITLE
[1.45.1] VSCode randomly closes opened files on tab over

### ISSUE THREAD

**Issue by MLefebvreICO** [microsoft/vscode#98192]
- VSCode Version: 1.45.1 (user setup)
- OS Version: Windows 10 Pro x64 1909 18363.778 

Steps to Reproduce:

1. Work normally in the editor
2. At some point while passing your mouse cursor over the working tabs(opened files), it will randomly close them until they all are closed ...

Does this issue occur when all extensions are disabled?: Yes/No .. Other : 

Did not check, the problem started with `1.45.1`. I had no issue with `1.45.0` with the same extensions.

**Comment by MLefebvreICO** [comment]
Just got it again ... 

Was trying to do `F1` and type a command  .. instead it wrote my command in my current file, making my file dirty and now it's trying to close it with those changes popping up a `Do you wish to cancel those changes` prompt.

Pressing `Cancel` on the prompt will only result in VSCode trying again to close the file and relaunch the prompt ..

I cannot make a gif/screenshot as it is work code .. and don't have perfect steps for reproduction either.

But it all started with the update `1.45.1`

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by MLefebvreICO** [comment]
After passing one morning into Insiders, I don't seems to have the issue for now. I'll continue for the rest of the day to see if it happens or not.

**Comment by MLefebvreICO** [comment]
Just curious .. Why has this been closed ?

I have the exact same extensions on Insiders that I have on the normal release, so it's not a extension issue and should prove there's something wrong with 1.45.1, no ?

I don't want to stay on Insiders, I want something solid, which 1.45.0 was ..
