### ISSUE TITLE
Folder compare

### ISSUE THREAD

**Issue by asklar** [microsoft/vscode#98197]
## Folder diffing. 

Today you can compare two files by calling `code --diff file1 file2` however there's no way to compare the contents of two folders which seems like a pretty basic scenario :)

Related feature #57687

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by moshfeu** [comment]
You can use (my) extension https://marketplace.visualstudio.com/items?itemName=moshfeu.compare-folders.
✋ It doesn't support comparing 3 files

**Comment by christhomas** [comment]
I should not even have to ask for this feature. It should have been a core feature from the beginning.

**Comment by SymmetricDesigns** [comment]
This is the one feature I go back to Eclipse for

**Comment by christhomas** [comment]
Imagine in 2023 going back to eclipse in the year 2006 in order to compare folders. So ridiculous

**Comment by ksa-real** [comment]
@isidorn Can you potentially reconsider this functionality? This is desperately needed. The free tools are mostly mediocre. Intellij Idea CE can compare directories, but lacks some commonly used stuff, like search, and is pretty heavy to load. The closest that is wanted is Meld. 
- Ability to compare directories and individual files by issuing CLI command
- Being able to edit text while comparing files

The commercial tools I'm aware are Araxis Merge, Beyond Compare. 

VSC looks like a very good starting framework to implement comparison and edit tool and it already contains file comparison functionality. It is lightweight enough to use a default `git difftool`.

**Comment by hzz4343** [comment]
This is really needed as a feature! Please reconsider.

**Comment by daxgames** [comment]
Just use beyond compare its better at folder compare anyway.

**Comment by christhomas** [comment]
I actually stopped using vscode for serious projects because it lacks basic tools like this, it's git integration is just plain horrid. It's fine for editing a single file or two. But if you wanna do anything like a real project. Nobody would use vscode. It's just not good enough.
