### ISSUE TITLE
Change the colour of warning/error squiggles

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/vscode#9819]
- VSCode Version: 1.3.1
- OS Version: El Capitan

Steps to Reproduce:
1. Create typescript files and produce Warning

Is it possible to change the colour of the warning message, I mean the squiggly line below and the warning marker on the scrollbar? In the darks themes the green colour is merely visible.

**Comment by c10ckw0rk** [comment]
+1

**Comment by bpasero** [comment]
PR: https://github.com/Microsoft/vscode/pull/27053

**Comment by alextreppass** [comment]
For anyone coming here from google, you can override this in user settings:

```json
    "workbench.colorCustomizations": {
        "editorWarning.foreground": "#FFAA00"
    }
```

See further: https://code.visualstudio.com/docs/getstarted/theme-color-reference
