### ISSUE TITLE
open vscode://file/path fails when path contains a question mark

### ISSUE THREAD

**Issue by lou1306** [microsoft/vscode#98190]
Issue Type: <b>Bug</b>

1. Create a directory with a question mark in the name (say, `mkdir a\?`)
2. Create a file within the directory (say, `touch a\?/b.txt`)
3. Try to `open "vscode://file/path/to/a?/b.txt`

A vscode dialog appears with the following message:

> **Path does not exist**
> The path '/path/to/a' does not seem to exist anymore on disk.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.50
todo-tree|Gru|0.0.175
Ionide-fsharp|Ion|4.11.0
latex-workshop|Jam|8.9.0
vscode-azurefunctions|ms-|0.22.1
csharp|ms-|1.21.18
python|ms-|2020.5.78807
azure-account|ms-|0.8.11
sublime-keybindings|ms-|4.0.7
team|ms-|1.161.0
java|red|0.61.0
rewrap|stk|1.10.1
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.1
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.22.4
vscode-maven|vsc|0.21.4
markdown-all-in-one|yzh|2.8.0

</details>

**Comment by joaomoreno** [comment]
You need to escape the question mark, since that's a URI.

https://stackoverflow.com/questions/9357032/question-mark-in-the-middle-of-a-url-variable
