### ISSUE TITLE
Ignored keybindings

### ISSUE THREAD

**Issue by Lohoris** [microsoft/vscode#98193]
Issue Type: <b>Bug</b>

Despite OS X allows users to redefine key bindings of any application (System Preferences -> Keyboard -> Shortcuts), VS Code completely ignores them in most circumstances (even if they DO appear in the menu).

Specifically, I'm trying to bind ⌘E to "Go to File…", and I've tried many other things.

The only one who worked (albeit useless obviously), is to bind ⌃⌥⇧⌘E

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (4.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
csharp|ms-|1.21.18
python|ms-|2020.5.78807
unity-debug|Uni|2.7.5

</details>

**Comment by kieferrm** [comment]
@Lohoris  You can define keyboard shortcuts inside VS Code: `Code` > `Preferences` > `Keyboard Shortcuts`.

**Comment by kieferrm** [comment]
@deepak1556 for the system integration issue.

**Comment by deepak1556** [comment]
This is a side effect of how electron overrides the shortcuts for an app, please use the method suggested by @kieferrm
