### ISSUE TITLE
Code formatter not working for C++

### ISSUE THREAD

**Issue by Sarveshgithub** [microsoft/vscode#98196]
Issue Type: <b>Bug</b>

Code format is  not working on latest update of vs code for c++.

Getting folloing error
There is no formatter for 'cpp' files installed.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (0.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
codescan-vscode|cod|1.6.2
vscode-eslint|dba|2.1.5
prettier-vscode|esb|4.7.0
aura-helper|Kan|1.9.4
python|ms-|2020.5.78807
cpptools|ms-|0.28.0
vscode-xml|red|0.11.0
salesforcedx-vscode|sal|48.15.0
salesforcedx-vscode-apex|sal|48.15.0
salesforcedx-vscode-apex-debugger|sal|48.15.0
salesforcedx-vscode-apex-replay-debugger|sal|48.15.0
salesforcedx-vscode-core|sal|48.15.0
salesforcedx-vscode-lightning|sal|48.15.0
salesforcedx-vscode-lwc|sal|48.15.0
salesforcedx-vscode-visualforce|sal|48.15.0
ayu|tea|0.18.0
material-theme|zhu|3.6.2

</details>

**Comment by kieferrm** [comment]
\extC++
