### ISSUE TITLE
VSCode retains a handle to the running tsserver

### ISSUE THREAD

**Issue by weswigham** [Microsoft/vscode#9820]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

1. Launch vscode.
2. Open a TS project.
3. Point "typescript.tsdk" at a custom tsserver folder.
4. Reload the window.
5. Open a TS file.
6. Attempt to delete the custom tsserver file in powershell/cmd and get a permission error.

**Comment by dbaeumer** [comment]
This is what node/electron does. It keeps the handle of the js file. There is nothing VS Code can do about this. I will close since this can't be fixed on the VS Code side. May be in node/electron.
