### ISSUE TITLE
Folders that are added to workspace close when selecting file

### ISSUE THREAD

**Issue by genbod** [microsoft/vscode#98205]
Issue Type: <b>Bug</b>

I just noticed that when navigating to a file inside a folder that has been added to the workspace, the file is opened in the editor but the folder in the Explorer pane is closed.  This feels like new behaviour and not expected.  Sometimes, when double clicking the file I can get the file to stay open but selecting another file makes the folder close.  This behaviour does not happen when selecting file from open folders from the main workspace, only from added folders.  Almost as if there is a refresh happening and the state from the added folder is not being captured.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (8 x 2295)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|32.00GB (4.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
shaderlabvscodefree|aml|1.1.6
githistory|don|0.6.5
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-npm-script|eg2|0.3.11
eppz-code|epp|1.2.41
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|4.7.0
vs-sharper|ese|0.2.0
vscode-diff|fab|1.4.0
image-to-base64|FEZ|1.0.1
scriptcsRunner|fil|0.1.0
vscode-test-explorer|hbe|2.18.1
Python-autopep8|him|1.0.2
rest-client|hum|0.23.2
csharpextensions|jch|1.3.1
csharpsortusings|jon|0.0.3
unity-code-snippets|kle|1.3.0
background-cover|man|2.2.3
dotenv|mik|1.0.1
azure-pipelines|ms-|1.165.1
vscode-apimanagement|ms-|0.1.3
vscode-azureappservice|ms-|0.16.5
vscode-azurefunctions|ms-|0.22.1
vscode-azureresourcegroups|ms-|0.1.0
vscode-azurestorage|ms-|0.9.0
vscode-azurevirtualmachines|ms-|0.1.0
vscode-cosmosdb|ms-|0.12.2
vscode-docker|ms-|1.2.0
csharp|ms-|1.21.18
vscode-dotnet-runtime|ms-|0.1.2
vscode-kubernetes-tools|ms-|1.2.0
mssql|ms-|1.9.0
python|ms-|2020.5.80290
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-ssh-explorer|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.11
azurecli|ms-|0.5.0
cpptools|ms-|0.28.0
powershell|ms-|2020.4.0
vscode-node-azure-pack|ms-|0.0.11
azurerm-vscode-tools|msa|0.10.0
json-parse-stringify|nex|1.0.2
quicktype|qui|12.0.46
vscode-yaml|red|0.8.0
synthwave-vscode|Rob|0.1.5
vscode-header-source|ryz|1.3.0
code-settings-sync|Sha|3.4.3
shell-launcher|Tyr|0.4.1
unity-debug|Uni|2.7.5
azure-iot-toolkit|vsc|2.16.1
vscode-icons|vsc|10.1.1
vscode-nxunit-test-adapter|wgh|0.1.3
change-case|wma|1.0.0

(2 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
If yes, can you please post a short gif showing this issue. You can use https://gifcap.dev/ for capturing gifs.

**Comment by genbod** [comment]
No, I can't recreate it using VS Code Insiders. I recorded the behaviour anyway.  I looked through my extensions again, but I don't see any explorer specific ones besides the icons.
![recording](https://user-images.githubusercontent.com/5254267/82454631-d474fd80-9a66-11ea-8e64-f9511bfb582d.gif)

**Comment by isidorn** [comment]
If you can not repro with insiders then it might be one of your extensions that is breaking it.
I suggest to either use vscode insiders, or try to figure out which extnesion is to blame.
Anyways nothing we can fix on the vscode side, thus closing this issue

**Comment by acgritt** [comment]
I have been having this issue for the past few months. I have a code-workspace file that is setup as such:
```json
{
    "folders": [
        {
            "name": "DotNet-Source",
            "path": "src"
        },
        {
            "name": "Angular-Source",
            "path": "src\\Project.UI\\ClientApp"
        },
        {
            "name": "Root",
            "path": "."
        }
    ],
    "settings": {
        "files.exclude": {
            "**/.git": true,
            "**/.svn": true,
            "**/.hg": true,
            "**/CVS": true,
            "**/.DS_Store": true,
            "src": true,
            "docs": true,
            "**/_NCrunch*": true,
            "**/.vs": true,
            "**/*.ncrunchsolution": true,
            "**/*.user": true,
            "**/bin/**": true,
            "**/obj/**": true
        },
        "typescript.preferences.quoteStyle": "single",
        "javascript.preferences.quoteStyle": "single",
    }
}
```

I download the Insiders and was able to reproduce it:
![recording](https://user-images.githubusercontent.com/10471937/83280977-05f37480-a19d-11ea-9ec9-da66343faf09.gif)

Even though I have the "src" folder set to exclude as I was trying to hide it in the "Root" and just have the direct link to it for quick access it shows up when I have a file open under it and that is also when it will collapse down the other folder.

**Comment by genbod** [comment]
Interesting.  My workspace setup is very similar.  I have several folders excluded from the root, but then added explicitly.  However, for some reason I couldn't recreate the behavior in the insiders version.

**Comment by acgritt** [comment]
It was a little more random in the insiders version but I was able to get it to happen as you can see. Also I didn't have any extensions installed.

**Comment by acgritt** [comment]
@isidorn I was able to replicate this issue with insiders and no extensions. Do you want me to log this as a new issue?

**Comment by isidorn** [comment]
Yes please file new issues with minimal repro steps. Thanks
