### ISSUE TITLE
Python intellisense not working for some modules

### ISSUE THREAD

**Issue by smagrath** [microsoft/vscode#98209]
- VSCode Version: 
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-29-generic

- OS Version: Linux bigbox 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Create a python file - say main.py
2. first line: "import networkx as nx"
3. All intellisense involving nx fails.
4. However, simply using "import networkx" works - though you must use the very long module name 

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
\extPython
