### ISSUE TITLE
Notebook output doesn't render VT-100 codes for `text/plain`

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode#98202]
- VSCode Version: 1.46.0-insider
- OS Version: Win10

Steps to Reproduce:

1. Install [.NET Interactive notebook extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode).
2. Open an existing file with the extension `.dotnet-interactive`.
3. Set first cell contents to this and execute:

``` csharp
Console.Write("\x1b[38;2;0;255;0m"); // set text color to green
Console.WriteLine("green");
Console.Write("\x1b[0m"); // reset colors
```

Does this issue occur when all extensions are disabled?: N/A

Expected:
The output stream contains VT-100 codes to set text color that should be honored.

Jupyter notebooks properly interprets these values in the `text/plain` mime type.

Top image is VS Code, bottom is Jupyter:
![image](https://user-images.githubusercontent.com/926281/82366621-56ade500-99c7-11ea-841a-9146485d335e.png)

**Comment by roblourens** [comment]
@rebornix you said something about having an xterm output for this? Or, there are simple npm packages that interpret these escape codes, the debug adapter uses one.

**Comment by rebornix** [comment]
We do support ansi colors with Error output, which is supported by https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/notebook/browser/view/output/transforms/errorTransform.ts#L54 . We can use the same transformer for `text/plain` mime type.

**Comment by rebornix** [comment]
mimetype `text/plain` in `CellOutputKind.Rich` output will now support ansi colors. `CellOutputKind.Text` will only be displayed as plain text.

**Comment by TylerLeonhardt** [comment]
@rebornix does that mean we can't use `CellStreamOutput` anymore? because that's set to `CellOutputKind.Text`:

https://github.com/microsoft/vscode/blob/master/src/vs/vscode.proposed.d.ts#L1587-L1590

**Comment by rebornix** [comment]
It's still available, but it only renders as plain text. We might also want to change its name to CellTextOuput to keep aligned.

**Comment by DonJayamanne** [comment]
> le, but it only renders as plain text. We might also want to change its name to CellTextOuput to keep aligned.

I too just came across this issue. For now, I'm using rich text.
