### ISSUE TITLE
[Bug] Title Bar Linux

### ISSUE THREAD

**Issue by userhv** [microsoft/vscode#98204]
Issue Type: <b>Bug</b>
![Captura de tela de 2020-05-19 16-30-18](https://user-images.githubusercontent.com/45722379/82369908-16ae2880-99ee-11ea-9181-c1d904c93c20.png)

When the title bar is changed from standard to customized, the maximize, minimize and close buttons are changed without preserving the system settings.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.4.0-31-generic

**Comment by tommai78101** [comment]
What Linux flavor are you using? What desktop environment frontend are you using?

**Comment by userhv** [comment]
> What Linux flavor are you using? What desktop environment frontend are you using?

Ubuntu 20.04.
Gnome 3.36.2
In KDE there is no such error.

**Comment by sbatten** [comment]
I'm sorry but I don't understand your statement "the maximize, minimize and close buttons are changed without preserving the system settings." Could you clarify?

The custom title bar is intended to replace the native system window controls.

**Comment by userhv** [comment]
> I'm sorry but I don't understand your statement "the maximize, minimize and close buttons are changed without preserving the system settings." Could you clarify?
> 
> The custom title bar is intended to replace the native system window controls.

The button design is not kept in vscode when we change the title bar to custom. In KDE (using gnome) the design remains. Realize?
![Captura de tela de 2020-05-19 21-01-18](https://user-images.githubusercontent.com/45722379/82390104-2fc9d000-9a14-11ea-8a22-a8bc65117ff5.png)

**Comment by sbatten** [comment]
The custom title bar is purely html and is designed to look like Windows. Linux allows too much customization for us to support looking like each and every distro/theme setup. So, unfortunately, this is by design.

**Comment by userhv** [comment]
> The custom title bar is purely html and is designed to look like Windows. Linux allows too much customization for us to support looking like each and every distro/theme setup. So, unfortunately, this is by design.

It is not true, because on another pc with ubuntu and one with KDE the design follows the system standard, maybe it is a bug
