### ISSUE TITLE
Insiders: search-in-panel support gone without warning 

### ISSUE THREAD

**Issue by olets** [microsoft/vscode#98200]
Issue Type: <b>Bug</b>

1. Update to 1.4.6
2. Search is not an option in panel

Maybe there's a setting that I'm overlooking? Having Search in the panel rather than the sidebar is my reason for using the Insiders track.

VS Code version: Code - Insiders 1.46.0-insider (da3bf754c3c0eabda1dc80ed9d627679ee560697, 2020-05-19T10:04:14.981Z)
OS version: Darwin x64 18.7.0

Edit: this issue persists when I disable all plugins.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 13, 13|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aga|0.5.0
copy-relative-path|ale|0.0.2
filewatcher|App|1.0.3
mergetool-navigator|aps|0.1.0
color-info|bie|0.5.1
markdown-preview-github-styles|bie|0.1.6
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
bracket-pair-colorizer-2|Coe|0.1.3
vscode-new-file|dku|4.0.2
dotfiles-syntax-highlighting|dot|0.1.0
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
vscode-npm-script|eg2|0.3.11
php-intellisense|fel|2.3.14
html-slim-scss-css-class-completion|gen|1.7.5
vscode-pull-request-github|Git|0.16.0
vs-code-paragraph-hard-wrapper|haa|0.0.2
svgeditor|hen|2.9.0
better-shellscript-syntax|jef|1.0.13
dupchecker|jia|0.1.6
svg|joc|1.1.9
vscode-peacock|joh|3.7.2
vscode-circleci|jva|0.5.0
chat|kar|0.33.0
chmod-command|lab|0.0.1
markdown-converter|man|3.0.2
twig-language-2|mbl|0.9.1
postcss-language|mhm|2.1.0
git-graph|mhu|1.22.0
code-beautifier|mic|2.3.3
prettify-json|moh|0.0.3
sublime-keybindings|ms-|4.0.7
vsliveshare|ms-|1.0.2169
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.3.4
debugger-for-chrome|msj|4.12.7
theme-timer|ray|1.0.1
ruby|reb|0.27.0
zsh-debug|rog|0.1.3
ActiveFileInStatusBar|Ros|1.0.3
bash-beautify|sha|0.1.1
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.0.1
sass-indented|syl|1.8.3
language-stylus|sys|1.11.0
ayu|tea|0.18.0
open-in-browser|tec|2.0.0
shellcheck|tim|0.9.0
terminal-zoom|try|1.7.1
lorem-ipsum|Tyr|1.2.0
alphabetical-sorter|ue|2.0.1
vscode-ruby|win|0.27.0
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.8.0
file-size|zh9|0.1.3

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
You can just drag Search (icon) from action bar to panel.

Had same issue but I thought that it was lost due to changes in settings and possible sync with other PR.

Is it possible that deprecated `"search.location": "panel"` is ignored, but position not set to panel (same as drag&drop)

**Comment by olets** [comment]
> You can just drag Search (icon) from action bar to panel.

Thanks, drag and drop worked! Had no idea that was supported.

> Is it possible that deprecated "search.location": "panel" is ignored, but position not set to panel (same as drag&drop)

There's no `"search.location"` in my user settings 🤷‍♂️

---

I'll close this, the drag and drop is such an easy fix it probably doesn't matter if some setting was lost
