### ISSUE TITLE
Sort order is not being honored in file view

### ISSUE THREAD

**Issue by ameltzerMSFT** [microsoft/vscode#98212]
Issue Type: <b>Bug</b>

In a folder with hundreds of files, sort order is not being honored. Even with a sort order of default as I scroll through files they are not being listed alphabetically.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz (12 x 3504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.70GB (15.00GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
gitlens|eam|10.2.1
prettify-json|moh|0.0.3
csharp|ms-|1.21.18
mssql|ms-|1.9.0
remote-wsl|ms-|0.42.4
cpptools|ms-|0.28.0
powershell|ms-|2020.4.0
trailing-spaces|sha|0.3.1
vscode-icons|vsc|10.1.1

</details>

**Comment by ameltzerMSFT** [comment]
Example: 
![image](https://user-images.githubusercontent.com/26661268/82390470-a4404700-99f3-11ea-9f22-499c59bd9c6c.png)

**Comment by ameltzerMSFT** [comment]
Example:

![image](https://user-images.githubusercontent.com/26661268/82390507-c0dc7f00-99f3-11ea-8f5c-59d7d142db96.png)

**Comment by isidorn** [comment]
Can not repro.
Can you please provide 2, 3 file names which I can create and that do not get properly sorted.
Thanks

**Comment by ameltzerMSFT** [comment]
It looks like you need lots of files.

Here’s a repro – in a new directory, run this PowerShell: 
`(1..1000) | foreach { Out-File ([guid]::NewGuid().ToString().ToUpper() + ".txt") }`

Open that directory in vscode

What I find is even with default sort order, the ordering is all over the place. 

Here's a quick demonstration:

![sorting](https://user-images.githubusercontent.com/26661268/82467606-b2837700-9a76-11ea-8292-d8f9c394d2a4.gif)

**Comment by isidorn** [comment]
I think this PR should fix it. https://github.com/microsoft/vscode/pull/97200
Thus try vscode insdiers and let us know if you still see the issue

**Comment by ameltzerMSFT** [comment]
Still seeing it in the latest Insiders build downloaded from: https://code.visualstudio.com/insiders/

![image](https://user-images.githubusercontent.com/26661268/82472510-24f75580-9a7d-11ea-914e-15da84271a16.png)

**Comment by isidorn** [comment]
Thanks for trying it out with insiders.
Code pointer for potential fix https://github.com/microsoft/vscode/blob/66ef23d401b24444d1465aa4bd6db369c1632de2/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L629

**Comment by ameltzerMSFT** [comment]
Update: This is still happening in 1.50.0

**Comment by isidorn** [comment]
There are other issues capturing similr problems. Please search for file-explorer and sort

**Comment by ameltzerMSFT** [comment]
@isidorn I'm confused by this resolution -- this isn't a feature request (which out-of-scope would seem to imply), but a straight up bug. Am I missing something here? This feels like a basic lexicographical sorting scenario that should just work.

I did a search on the tags but didn't see anything like this, but maybe I just missed it.

**Comment by isidorn** [comment]
https://github.com/microsoft/vscode/issues/104555

**Comment by ameltzerMSFT** [comment]
@isidorn is this the same root cause? In the linked bug you still get expected 1->2->3 sorting, but in my repro there's letters and numbers interleaved in a completely non-sensical manner (3->7->A->1). If it's the same root cause, then that's cool but this seems only tangentially related.
