### ISSUE TITLE
mouse cursor is pointing to the wrong line in debug mode python 3

### ISSUE THREAD

**Issue by Ahmed-Soli** [microsoft/vscode#98210]
VSCode : 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.3.9600
Steps to Reproduce:

1.open a debug mode on a python script
2.each line that get's executed , it's value is not shown in the left side ( debug panel) until you execute the next line 
![image](https://user-images.githubusercontent.com/39798205/82386905-ebe7c280-9a35-11ea-96c8-3199e5bd4f69.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
\extPython
