### ISSUE TITLE
"Go back" doesn't go back to the original editor group

### ISSUE THREAD

**Issue by tlemo** [microsoft/vscode#98216]
Issue Type: <b>Bug</b>

1. Create two editor groups (side by side)
    - group1: foo.cpp
    - group2: foo.cpp bar.cpp

2. Position the cursor somewhere in group2/foo.cpp

3. Ctrl-Tab to switch to group2/bar.cpp

4. "Go back" (Alt-Left Arrow)

Expected: switch to group2/foo.cpp with the previous cursor position

Actual: swtiching to group1/foo.cpp !

This is very frustrating, especially when group1 has other active editors (which would be deactivated and switched to foo.cpp)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 4.15.0-101-generic
Remote OS version: Linux x64 5.3.0-51-generic

**Comment by tlemo** [comment]
What is the duplicate issue # ? Thanks

**Comment by gjsjohnmurray** [comment]
Probably #9526

**Comment by tlemo** [comment]
Thanks @gjsjohnmurray , #9526 seems a related, but different issue. 

Maybe #88470? @bpasero, can you confirm? (and please note the duplicate issue # when adding the duplicate lablel in the future)

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/9526

**Comment by tlemo** [comment]
Thank you for the clarification @bpasero!
