### ISSUE TITLE
java lombok  experience    is not good

### ISSUE THREAD

**Issue by tgl123** [microsoft/vscode#98217]
Issue Type: <b>Feature Request</b>

//1.   add lombok  annotation  
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Response {

    private Integer errorCode = 0;

    private String errorMsg = "";

    private Object data;

    public Response(Object data) {
        this.data = data;
    }
}

//====================

// 2.   use  class  Response , vscode will display  “The constructor Response() is undefined‘
  Response response=new Response ();

//3.use get or set method ,vscode will display " The method 
setErrorCode(Integer) is undefined for the type Response"

 response.setErrorCode(ErrorCode.MERCHANTS_NOT_EXIST.getCode());

//4. At last,  the springboot project cannot build successfully(with  spring-boot dashboard plugin ).

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 6.1.7601

**Comment by kieferrm** [comment]
\extJava
