### ISSUE TITLE
Unable To Use Preferences Sync [Insiders]

### ISSUE THREAD

**Issue by Matelasse** [microsoft/vscode#98214]
- VSCode Version: Insiders
- OS Version: Arch

Steps to Reproduce:

1. Install gnome-keyring, open insiders
2. Open Output pane
3. Read
```
[Error  - 00:56:51.2] Getting token failed: Error: Error calling StartServiceByName for org.freedesktop.secrets: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)
[Error  - 00:57:46.33] Getting token failed: Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
```
I don't even want to be installing `gnome-keyring`, as I don't use gnome software. Is there an option for something else? I don't know how to make gnome-keyring work either, and it's not documented on vscode resources. I used `seahorse` to check that I have keyrings, but I don't see anything vscode related there.

**Comment by Matelasse** [comment]
cc @sandy081

**Comment by RMacfarlane** [comment]
@Matelasse Do you have `libsecret` installed?

We are currently [this library](https://github.com/atom/node-keytar) to store credentials cross-platform and don't have plans to change this.

I'd like to include some more documentation on setting this up, does https://wiki.archlinux.org/index.php/GNOME/Keyring have enough information under "Using the keyring outside GNOME" for you?

**Comment by Matelasse** [comment]
@RMacfarlane Of course I do have `libsecret` installed. However following that arch wiki guide throughout did not allow me to use vscode's new auth system. Note that without libsecret OR without gnome-keyring I get a diferent error message, saying that org.freedesktop.service is not available at all. However installing both and following the arch wiki got me down to the error mentioned in the original post:
`[Error  - 00:56:51.2] Getting token failed: Error: Error calling StartServiceByName for org.freedesktop.secrets: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=12000ms)`
I'd advise you to get a tester for linux distros that dont ship with native keyring managers. This is for sure going to come up as issues once this feature lands in stable.

**Comment by Matelasse** [comment]
It looks like for linux users there are only two package options that implement `org.freedesktop.secrets`: `gnome-keyring` and `keepassxc`. I couldn't get either of those working with vscode. If other users have stumbled upon this and figured out a fix, please do follow up on here. The solution might merit a mention in vscode docs too.
