### ISSUE TITLE
Huge memory consumption

### ISSUE THREAD

**Issue by emild** [microsoft/vscode#98213]
Issue Type: <b>Performance Issue</b>

Start visual studio code on an empty directory (let's call it my-dir)
From an external terminal
     cd my-dir
    create-react-app .
    Do minor edits in the generated react app
   Go to the terminal window inside Visual Studio Code and attempt to run 
  yarn start
 At some stage the http server cannot start because of ENOSPC. This is most likely because the process cannot fork() because Linux ran out of swap space because of the HUGE virtual space consumed by the VSCode process (12GBYTES!!) (see in the attached output of the top command the details of PID 14318)

14318 emil      20   0 11.911g 228036  99084 S   0.0  3.8   0:29.57 code

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 4.15.0-99-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU       Q 720  @ 1.60GHz (8 x 1384)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|5.76GB (0.21GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   118	 14271	code main
    0	    35	 14273	   zygote
    0	   130	 14296	   gpu-process
    0	    53	 14303	   utility
    0	   218	 14318	   window (App.js - crash-todo-list - Visual Studio Code)
    0	   112	 14371	     extensionHost
    0	    77	 14425	       electron_node tsserver.js 
    0	   348	 14426	       electron_node tsserver.js 
    0	   118	 14476	         electron_node typingsInstaller.js typesMap.js 
    0	    65	 14448	       electron_node dbaeumer.js server.js 
    0	   112	 14449	       electron_node eslintServer.js 
    0	     0	 14372	     /bin/bash
    0	    59	 14400	     watcherService
    0	    59	 14416	     searchService
    0	   106	 14343	   shared-process
    0	     0	 16131	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 16132	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    1	   106	 16107	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (App.js - crash-todo-list - Visual Studio Code)
|    Folder (crash-todo-list): 22 files
|      File types: js(5) json(2) png(2) css(2) gitignore(1) md(1) lock(1)
|                  ico(1) html(1) txt(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
[top.txt](https://github.com/microsoft/vscode/files/4653989/top.txt)

jshint|dba|0.10.21
vscode-eslint|dba|2.1.5
beautify|Hoo|1.5.0
python|ms-|2020.5.80290
cpptools|ms-|0.28.0
debugger-for-chrome|msj|4.12.7
vscode-react-native|msj|0.15.0

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
Also, what is the specific subprocess that has the large virtual memory usage? Is it `14318` in this case (the `window` process?)
