### ISSUE TITLE
The Color Picker extension reported an error

### ISSUE THREAD

**Issue by HackerWand** [microsoft/vscode#98222]
- VSCode Version: 1.45.1
- OS Version: macOS Catalina 10.15.1

Steps to Reproduce:

1. Install Color Picker extensions.
2. Normally, the mouse hover would activate the palette, but the palette was not activated under the vue file, and there were no color blocks in front of the color code. Then I tried to execute the Alt +c and Alt +c p commands and the error was reported as shown above.
3. I reported the problem to the Color Picker author, but the Color Picker author said I should report the problem to the VS Code team

https://github.com/anseki/vscode-color/issues/99

Does this issue occur when all extensions are disabled?: No

**Comment by HackerWand** [comment]
![image](https://user-images.githubusercontent.com/12233185/82399217-3b0a1380-9a87-11ea-817c-08c9b106feae.png)

**Comment by kieferrm** [comment]
@sandy081 this looks like an extension installation corruption issue.

**Comment by sandy081** [comment]
I went through the original issue user reported https://github.com/anseki/vscode-color/issues/99 and user is complaining about the colour picker we support in VS Code and it is nothing to do with the extension.

**Comment by sandy081** [comment]
Not sure who owns colour picker.

**Comment by rebornix** [comment]
The Vue extension should contribute the color info otherwise the color picker won't work.
