### ISSUE TITLE
Auto Suggestion is not working after pressing 'Enter' between function param

### ISSUE THREAD

**Issue by Tanvir-rahman** [microsoft/vscode#98220]
- VSCode Version: 1.45.1
- OS Version: Darwin x64 19.4.0

Steps to Reproduce:

1. While working on a flutter project, for indentation press enter between function param
<img width="750" alt="Screenshot 2020-05-20 at 7 33 30 AM" src="https://user-images.githubusercontent.com/15964566/82395458-6849c800-9a6d-11ea-8ead-be32c9ba0cb4.png">

2. Auto suggestion of params will not show
<img width="755" alt="Screenshot 2020-05-20 at 7 34 29 AM" src="https://user-images.githubusercontent.com/15964566/82395427-5b2cd900-9a6d-11ea-9a28-14bea8a3d4a6.png">

3. Clicking on other element and back the cursor to previous point will show the suggestion again.
<img width="759" alt="Screenshot 2020-05-20 at 7 35 15 AM" src="https://user-images.githubusercontent.com/15964566/82395419-56682500-9a6d-11ea-8231-6c69ba918b6b.png">

**Comment by Tanvir-rahman** [comment]
In issue #97874 there is not enough description.

**Comment by kieferrm** [comment]
Please file the issue against the flutter extension.
