### ISSUE TITLE
The Debug Icon does not appear 

### ISSUE THREAD

**Issue by maheshmurthi** [microsoft/vscode#98226]
Issue Type: <b>Bug</b>

Not able to see the Debug Icon - even after configuring Json
Am using Python

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
python-preview|don|0.0.4
vscode-html-css|ecm|0.2.3
MagicPython|mag|1.1.0
csharp|ms-|1.21.18
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.5.80290
vscode-yaml|red|0.8.0
jupyter-notebook-vscode|sam|0.0.2
python|tht|0.2.3
unity-debug|Uni|2.7.5
html-css-class-completion|Zig|1.19.0

</details>

**Comment by yume-chan** [comment]
Which "debug icon" are you referring to?

Can you attach a screenshot showing where you expect the debug icon to appear?

**Comment by maheshmurthi** [comment]
![image](https://user-images.githubusercontent.com/12374738/82455602-c065e600-9ad0-11ea-8098-6053ee77c65c.png)

**Comment by maheshmurthi** [comment]
Is there not a Bug Icon that is supposed to appear on the left pane ?

**Comment by maheshmurthi** [comment]
![image](https://user-images.githubusercontent.com/12374738/82456667-2b63ec80-9ad2-11ea-8415-f35a0b9b6c12.png)

**Comment by maheshmurthi** [comment]
Right Clicking on the Activity Bar does not show the Debug Option 
I've checked multiple YouTub Videos on installing VS Code and in all of them the ICON seems to appear as soon as they finish installation

**Comment by yume-chan** [comment]
The fourth one is what you are finding. It had been renamed to "Run".

**Comment by maheshmurthi** [comment]
Thank You - Am Closing this issue
