### ISSUE TITLE
RUBY not showing formatting correctly

### ISSUE THREAD

**Issue by jcrew99** [microsoft/vscode#98221]
- VSCode Version: 1.42.1
- OS Version: centos 7

Steps to Reproduce:

1.Open code in a Test.rb and put in the following code.

Ruby it isn't handling the following well.
It isn't rendering the correct colors and is messing up how some of my code looks.

![image](https://user-images.githubusercontent.com/37361441/82407980-e29a3c80-9aad-11ea-9022-a5be53f4578a.png)

It bugged me for a few days so i check and it is caused by the brackets in test 1
image

This is what i would expect it to look like with, which it does with the brackets removed:

![image](https://user-images.githubusercontent.com/37361441/82407946-d1e9c680-9aad-11ea-871e-d4bacbf197c7.png)

It also happens without a specific theme:

![image](https://user-images.githubusercontent.com/37361441/82408057-1c6b4300-9aae-11ea-85cf-eb945c1f5730.png)

Is it possible to get this fixed?

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Can you please provide a copy-paste-able example I can test with?
