### ISSUE TITLE
python debug console with huge unnecessary variable showed

### ISSUE THREAD

**Issue by ayeteng** [microsoft/vscode#98223]
- VSCode Version:
版本: 1.45.1
認可: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
日期: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
- Extension: ms-python.python 2020.5.80290
- OS Version:
OS: Darwin x64 19.4.0
macOS Catalina: 10.15.4

Steps to Reproduce:

The python debug console become very complicated with a lot of special variables. How can I hide the unnecessary variable like before?
![bad_python](https://user-images.githubusercontent.com/12135212/82411313-28520780-9aa4-11ea-8c25-fa99cb87ce29.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by JacksonKearl** [comment]
\extPython
