### ISSUE TITLE
The terminal IME composition view appears on top of the text when at the bottom of the screen

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9822]
See it appears on top of the second character being composed.

![image](https://cloud.githubusercontent.com/assets/2193314/17159329/3fec2018-5351-11e6-88bd-265f21f1b978.png)

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/208

**Comment by rebornix** [comment]
@Tyriar not sure which language you were typing on what platform when you found the issue, but the behavior on Mac with Chinese IME is not that perfect, see below gif

![imeinterminal](https://cloud.githubusercontent.com/assets/876920/18140666/6009afec-6f6b-11e6-9683-7ffc956e97d2.gif)

While typing `nihao`, the text is sometimes covered by the IME hint popup and while typing constnatly, the popup keeps moving, which is a little bit annoying.

**Comment by Tyriar** [comment]
The bug was created in #11334 and technically this is done so I'll make this verified
