### ISSUE TITLE
Terminal not responding

### ISSUE THREAD

**Issue by Aadhik611** [microsoft/vscode#98225]
I am a python programmer, I really like using VS code for writing my programs, but from past weeks I have this problem that, when I 'Kill the terminal window' (To start fresh), the program stops responding, and then after a minute or so, a window pops up saying "Do you want to reopen the application?", I always click on reopen then it restarts the program with the project file open. But nowadays this window always comes, I Need Help!

**Comment by thenineteen** [comment]
In my case, killing the terminal during debugging (e.g. at breakpoint) causing terminal to not respond as above 100% of the time

possibly related to #78138
