### ISSUE TITLE
Crash when clicking 'show context' on viewing search results in editor

### ISSUE THREAD

**Issue by AgrMohit** [microsoft/vscode#98230]
- VSCode Version: 1.45.1
- OS Version: Windows 10 Pro (Build 18363.836) x64

Steps to Reproduce:

1. Open a javascript project
2. Use (ctrl+shift+f) to search anything
3. View search results in the editor
4. Click on show context near top right corner

The progress bar on top in blue moves a little and then the window stops responding
and crashes after a few seconds

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by AgrMohit** [comment]
Update:
The crash only occurs when using opening the project in WSL.
Opening the project in windows works normally.

The crash only occurs in javascript projects.
C, C++ projects don't seem affected by this

**Comment by JacksonKearl** [comment]
Does this happen for projects of any size?

**Comment by AgrMohit** [comment]
The crash occurs even in small projects created by 'create-react-app'.
On removing 'node_modules' folder, it works as expected without any crashes

**Comment by JacksonKearl** [comment]
I haven't been able to reproduce this, does it still happen in the latest release (1.47) for you? Do you have any `search.` settings modified?

**Comment by JacksonKearl** [comment]
Cannot reproduce, closing as duplicate of #97180, please let me know if you run into this on 1.47.

**Comment by AgrMohit** [comment]
This issue does not occur in 1.47. Thanks
