### ISSUE TITLE
No error checking on JavaScript

### ISSUE THREAD

**Issue by jordyvandomselaar** [microsoft/vscode#98234]
Issue Type: <b>Bug</b>

I have this code:

```javascript
const foo = "bar";

foo = 123;
```

I'm not getting any red lines or errors shown:
![image](https://user-images.githubusercontent.com/12712484/82435735-07ce8100-9a95-11ea-9f36-8315d56f4c7d.png)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
project-manager|ale|11.0.1
atlascode|atl|2.6.1
vscode-intelephense-client|bme|1.3.11
htmltagwrap|bra|0.0.7
path-intellisense|chr|1.4.2
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
carbon-now-sh|eri|1.2.0
prettier-vscode|esb|4.7.0
php-debug|fel|1.13.0
auto-close-tag|for|0.5.7
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.3
vscode-styled-components|jpo|0.0.29
vscode-docker|ms-|1.2.0
debugger-for-chrome|msj|4.12.7
vscode-yaml|red|0.8.0
code-settings-sync|Sha|3.4.3
vscode-vuln-cost|sny|1.3.6
codetour|vsl|0.0.26

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
