### ISSUE TITLE
Stepping/Continuing after modifying a source file does not give the debugger any updated information

### ISSUE THREAD

**Issue by wesrupert** [Microsoft/vscode#9823]
- VSCode Version: 1.4.0-Insider 2016-07-26T05:09:25.359Z
### Steps to Reproduce:
1. Set and hit a breakpoint in a C# app
2. Write gibberish after the breakpoint, as many lines of it as you like
3. Step over
### Expected Result:
- Stepping leads to a no source page
### Actual Result:
- Stepping steps into garbage lines, as the debugger has no idea that the expected lines aren't there

![image](https://cloud.githubusercontent.com/assets/2474675/17159263/d50453ce-5350-11e6-87ad-f1c036d08ac5.png)

I'm not seeing an event come in indicating that we are now working with stale code in the window. It looks like [Issue 8077](https://github.com/Microsoft/vscode/issues/8077) improved this behavior when the user saves, but now we need something to enable correct behavior, e.g. a "no source" page since the window no longer represents the code that the debugger thinks it's running.

**Comment by weinand** [comment]
As soon as source is edited while a debug session is active, the breakpoints are marked as unverified and rendered as such.

**Comment by remss** [comment]
Yes when file is dirty breakpoints are marked as unverified in the GUI but the debugger will still break on old source breakpoints (on empty lines).
I this case I believe that the paused source cannot be the local one any more but should be a read-only loaded script tab, with current active breakpoints displayed.
