### ISSUE TITLE
Untitled editors: suggest file name only from words of first line, not symbols

### ISSUE THREAD

**Issue by CWempe** [microsoft/vscode#98244]
vscode does use the first line of a new file as the title for the tab, which is great.

![image](https://user-images.githubusercontent.com/1270359/82456009-f21c8400-9ab3-11ea-96e8-7fb8011c40a5.png)

But when you have a markdown file the first line is usually the title with a leading number sign.

![image](https://user-images.githubusercontent.com/1270359/82456286-550e1b00-9ab4-11ea-95cf-3e27c3b1ee44.png)

In this case I would like for vscode to remove the leading number sign.

The same for the save dialog.

![image](https://user-images.githubusercontent.com/1270359/82456227-3e67c400-9ab4-11ea-9eaa-abfd628f1a65.png)

**Comment by bpasero** [comment]
The reason for this is:

https://github.com/microsoft/vscode/blob/07a56fd95d26499351af05077043361b1cbe5830/src/vs/workbench/services/untitled/common/untitledTextEditorModel.ts#L364

We take the first line literally and not do any further processing. We could in theory only pick the words from the first line and leave out all symbols.
