### ISSUE TITLE
Terminal BUG

### ISSUE THREAD

**Issue by banyue-senior** [microsoft/vscode#98247]
When I enter text in Vscode found that I enter text, terminal display blank, don't know what the reason, I find the Internet a lot of methods to solve this problem, they say it's the software compatibility, but when I changed the software on the software compatibility, not my problem without any substantial effect.My computer is Windows10. I have tried many solutions, but none of them worked. I downloaded the plug-in run in terminal in this software, but none of them worked.It is just this problem for the time being. I hope the authorities can give me a solution to this problem.I have tried several ways, but none of them can be solved. I hope the official can reply to me as soon as possible. Thank you!

**Comment by oguru** [comment]
I have the same issue. It doesn't always happen and opening a new terminal works fine.

**Comment by Tyriar** [comment]
Can you share a screenshot and your settings.json file?

**Comment by oguru** [comment]
Sure, here you go. It was completely blank before i clicked inside the terminal. If i type, the command prompt moved across but no text appears

![vscode-terminal](https://user-images.githubusercontent.com/32145323/84264164-9eccad00-ab18-11ea-91a9-640d33638de6.PNG)

**Comment by oguru** [comment]
> 
> 
> Can you also share your windows version and build number (run `ver` in cmd.exe)?

The bug appears to have resolved itself following the latest update
