### ISSUE TITLE
Unable to copy text without formatting

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#98242]
Issue Type: <b>Bug</b>

In my theme, comments are set to be rendered emphasized. When I copy a comment and paste that in a richt-text-aware application, the comment will be emphasized as well, causing issues with formatting in the target application.

I don't understand why this is happening, because "Copy" and "Copy with syntax highlighting" are distinct functions and I am using the former, not the latter.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3672)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (36.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
generateuuid|Fir|0.0.5
shell-format|fox|7.0.1
vscode-esformatter|how|1.6.0
output-colorizer|IBM|0.1.2
code-beautifier|mic|2.3.3
vscode-puglint|mrm|2.3.0
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.7
vscode-paste-image|mus|1.0.4
copyplaintext|p26|1.0.7
vscode-yaml|red|0.8.0
vscode-icons|vsc|10.1.1

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
This feature can be disabled by `editor.copyWithSyntaxHighlighting`

**Comment by oliversalzburg** [comment]
Why even offer two distinct functions if they don't provide what they advertise without additional configuration? Seems like a poor UX choice.
