### ISSUE TITLE
Intellisense for C# not working for an unknown reason

### ISSUE THREAD

**Issue by sahilpant** [microsoft/vscode#98243]
Issue Type: <b>Bug</b>

Starting OmniSharp server at 20/5/2020, 7:34:56 pm
    Target: d:\Repos\Unity_2D\Number_Wizard_Console\Number Wizard Console\Number Wizard Console.sln

OmniSharp server started.
    Path: c:\Users\SAHIL\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.2-beta.51\OmniSharp.exe
    PID: 5672

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.4 - "c:\Users\SAHIL\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.2-beta.51\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'c:\Users\SAHIL\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.2-beta.51\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.4 - "c:\Users\SAHIL\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.2-beta.51\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\Users\SAHIL\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.2-beta.51\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = c:\Users\SAHIL\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.2-beta.51\.msbuild
            MSBuildToolsPath = c:\Users\SAHIL\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.2-beta.51\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'd:\Repos\Unity_2D\Number_Wizard_Console\Number Wizard Console'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'd:\Repos\Unity_2D\Number_Wizard_Console\Number Wizard Console\Number Wizard Console.sln'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\Repos\Unity_2D\Number_Wizard_Console\Number Wizard Console'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\Repos\Unity_2D\Number_Wizard_Console\Number Wizard Console' on host 9008.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (2.12GB free)|
|Process Argv|D:/Repos/Unity_2D/Number_Wizard_Console/Number Wizard Console -g D:\Repos\Unity_2D\Number_Wizard_Console\Number Wizard Console\Assets\NumberWizard.cs:1:0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
path-intellisense|chr|1.4.2
prettier-vscode|esb|4.7.0
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.3
dotnet|leo|1.2.0
csharp|ms-|1.21.18
python|ms-|2020.5.80290
cpptools|ms-|0.28.0
mono-debug|ms-|0.15.8
color-highlight|nau|2.3.0
vscode-paste-and-indent|Rub|0.0.8
unity-tools|Tob|1.2.3
unity-debug|Uni|2.7.5

(1 theme extensions excluded)

</details>

**Comment by sahilpant** [comment]
Starting OmniSharp server at 20/5/2020, 8:46:06 pm
    Target: d:\Repos\Unity_2D\Number_Wizard_Console\Number Wizard Console\Number Wizard Console.sln

OmniSharp server started.
    Path: c:\Users\SAHIL\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.2-beta.51\OmniSharp.exe
    PID: 16924

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.4 - "c:\Users\SAHIL\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.2-beta.51\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'c:\Users\SAHIL\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.2-beta.51\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.4 - "c:\Users\SAHIL\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.2-beta.51\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\Users\SAHIL\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.2-beta.51\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = c:\Users\SAHIL\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.2-beta.51\.msbuild
            MSBuildToolsPath = c:\Users\SAHIL\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.2-beta.51\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'd:\Repos\Unity_2D\Number_Wizard_Console\Number Wizard Console'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'd:\Repos\Unity_2D\Number_Wizard_Console\Number Wizard Console\Number Wizard Console.sln'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\Repos\Unity_2D\Number_Wizard_Console\Number Wizard Console'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\Repos\Unity_2D\Number_Wizard_Console\Number Wizard Console' on host 10404.
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: d:\Repos\Unity_2D\Number_Wizard_Console\Number Wizard Console\Assets\NumberWizard.cs added to workspace





why isn't intellisense not working is still unknown

**Comment by kieferrm** [comment]
\extC#
