### ISSUE TITLE
Missing "recently opened" section for some queries

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#98249]
- Open `search.test.ts` under `test/smoke/`
- Search `search.test`, I see it in Recently Opened

![image](https://user-images.githubusercontent.com/323878/82459262-52dc9a00-9a7d-11ea-95e6-e1cbef3ae136.png)

- Add `smoke ` to the query, so it highlights the smoke folder, but now I don't see it in Recently Opened

![image](https://user-images.githubusercontent.com/323878/82459291-625be300-9a7d-11ea-8a60-55fcad61aadf.png)

**Comment by bpasero** [comment]
This is actually intentional, when you do a more complex search we totally ditch the editor history which only searches in the label. I did that because otherwise you end up cluttering potentially bad results from the history above good results from file search. I did not want to change that.

**Comment by roblourens** [comment]
Oh ok I didn't realize that. Complex search == search with a space?

**Comment by bpasero** [comment]
@roblourens yeah, either that or when you actually include a path separator.
