### ISSUE TITLE
Default ctrl+d and ctrl+r keyboard shortcuts not working

### ISSUE THREAD

**Issue by srideshpande** [microsoft/vscode#98259]
Issue Type: <b>Bug</b>

I don't have any extensions added and no customizations made. 

OOTB vs code doesn't recongnize ctrl+d (keybord shortcut to select same occurence of the word) or ctrl+r (reveal active file in sidebar).

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (20.03GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kieferrm** [comment]
Ctrl+D requires a selection to start with.
Ctrl+R is "Open Recent"

When you open the keyboard shortcut editor you can filter for keyboard shortcuts and see what they are bound to. There is also `Help > Keyboard Shortcut Reference` or you can type the commands in the command palette to see what they are bound to.
