### ISSUE TITLE
Scrolling stutter when zoomed - with partial fix

### ISSUE THREAD

**Issue by sean9keenan** [microsoft/vscode#98251]
- VSCode Version: 1.45.1 and Master @ commit hash a67d00db97
- OS Version: Mac OS - Catalina

Steps to Reproduce:

1. Set `window.zoomLevel` to any non-default number (in my case -0.9)
2. Scroll around and see jitter - example gif below:
![VSCodeStudder](https://user-images.githubusercontent.com/2107356/82457421-413dc700-9a6a-11ea-80e4-9592950c662a.gif)
(This is hard to capture in a GIF - but not all lines move by 1 pixel up at the same time)

I have attempted to debug this somewhat - the zoom level causes the offsets to be non-integer pixels.
If you apply a scaling offset - of `(1 - window.zoomLevel * 0.2)` (0.2 because that's the scaling factor the chrome uses), then you can actually fix the problem (with zoom level -0.9 this comes to a factor of 1.18):
![VSCodeStudderFixed](https://user-images.githubusercontent.com/2107356/82457827-c1642c80-9a6a-11ea-9739-0f19891c28d3.gif)
(Again hard to capture in a GIF due to frame rate - but it's buttery smooth)

The commit for where [I modified this is here](https://github.com/sean9keenan/vscode/commit/1099079a0a39d16da4b11065050590770b9e7ff5)

But I'm not sure the "correct" way to fix this within the codebase. Could potentially create the PR, but would appreciate some input.

Not to clutter this issue too much - but I know relatedly there are a lot of past issues with fonts not looking smooth when you zoom. This can be fixed if you scale the font in line with the window zoom, while this can be done in the settings by setting a fractional fontSize (for the main editor font, terminal fonts only support integers), it could make sense to roll in a fix for that at the same time. I was imagining behind some experimental flag like `experimental-zoomed-font-fixes`.
(The equation for setting the font size is `(Whole Int Font Size) / (1 + .2 * zoomLevel)`)

**Comment by alexdima** [comment]
Thank you for your investigation. Unfortunately, the only way to get pixel perfect rendering is to stop using `window.zoomLevel`.

The implementation of `window.zoomLevel` is the same as in any browser, and it works by basically multiplying our perfect integer coordinates with a float (the zoom factor).

So if we render lines at the offsets 0, 19, 38, etc, they will become 0, 19 x factor, 38 x factor, etc. Depending on the zoom level, those will be floats with many digits.

The screen itself does not use floats, it uses integers again, so those floats will be rounded at one point to integers, and depending on how those land in relationship to integers, there will be a line that is fatter than the rest, e.g. 0, 20, 40, 61, 81, 101, 122 etc. This all depends on the zoom factor and the line height and the actual line number.

There is absolutely nothing we should do on our side to attempt to fix this madness. Feeding floating points for those values in the hope that the multiplication with the zoom factor will lead to an integer is madness. It also has some other negative consequences, such as breaking subpixel antialising rendering of fonts inside the GPU layer (any layer that is not positioned at integer coordinates goes to grayscale font rendering on Windows).

IMHO, the only solution is to disable this ridiculous zoom implementation and remove it entirely from VS Code, but my colleagues have shut me down in my attempts to remove this, arguing that it is useful for presenting at conferences and other such "temporary" cases.

My personal recommendation is to never ever use `window.zoomLevel`. Simply use `editor.fontSize` and upvote https://github.com/microsoft/vscode/issues/519 . If the font size could be changed in all of VS Code, then zooming would become unnecessary.

**Comment by sean9keenan** [comment]
Sounds good!

Thanks for linking #519 - that would give me what I want. (Also sorry for [missing some of your past comments](https://github.com/microsoft/vscode/issues/28439#issuecomment-308407781), and similar issues re: #85767

Makes sense that down this path only lays madness, for a variety of reasons - but thought I'd ask anyway, so thanks for being patient 😄(Also didn't know that tidbit re front rendering on Windows)

RE: The case of removing editor level zoom - I do agree that I find it useful (especially for presenting code), but perhaps from a caseload perspective the help text for the setting could describe or link to some of the limitations? I did attempt to search for this issue before filing a new one, just did a poor job of it apparently.

As a personal aside - Currently without #519, I actually prefer zooming, and dealing with this issue.

Thanks again for the through response!
