### ISSUE TITLE
Problems: filter box shows no border in default light theme

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#98250]
Default light theme
Problems view
Filter in title area shows no border

![Screenshot 2020-05-20 at 16 37 28](https://user-images.githubusercontent.com/1926584/82459412-34e05b00-9ab8-11ea-900a-7d30084e69b2.png)

**Comment by sandy081** [comment]
@misolori Do you know of any changes done in themes that is causing this. I see only on insiders.

**Comment by misolori** [comment]
I don't know of any changes here, but i did notice that `panelInput.border` no longer works. Maybe @sbatten knows since he made some changes to the panel in https://github.com/Microsoft/vscode/commit/8e67cd2dc673536fbfaeb922066f7c237baa2cdf?

**Comment by aeschli** [comment]
It seems the border color is defined at two places (one as transparent) and by making one rule more specific, the other one was cancelled out.
I removed transparent setting, to (hopefully) restore it the way we had it before.

@misolori For you to decide to also remove `vs` and have the border in dark and hc as well. There's a rule just above with different height settings for dark and hc, so I guess no border was intended. Maybe @sandy081 knows more.

**Comment by sandy081** [comment]
@aeschli Thanks for the fix.

I do not think we need custom styling for border, hence removed it.

@misolori I do not know why we have different heights, it seems this is introduced here - 2992ad820a916b0fb4eb51549db993317117e7f0 . Leaving it to you.
