### ISSUE TITLE
Space before code block in bullet point renders extra whitespace in preview mode

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#98254]
- VSCode Version: 1.45.1
- OS Version: Ubuntu 18.04

Markdownlint has a rule that says:

> MD031/blanks-around-fences: Fenced code blocks should be surrounded by blank 

Follow this rule however makes extra vertical white space between bullet points (or padding rather), which looks bad. The same thing happens here in GitHub, which the below example shows.

Could this be fixed in the VS Code markdown preview window to not render this extra padding?

### Example: No space before code block (breaks MD031, but looks good in preview)
~~~md
- Bullet point 1
- Bullet point 2
  ```javascript
  const test = 'test';
  ```
- Bullet point 3
~~~

### Example: Space before code block (follows MD031, but looks bad in preview)
~~~md
- Bullet point 1
- Bullet point 2

  ```javascript
  const test = 'test';
  ```

- Bullet point 3
~~~

(The easiest way to view this markdown code is via "view source" in your browser)

Does this issue occur when all extensions are disabled?: Yes

**Comment by thernstig** [comment]
Update:

I've found it has nothing to do with code blocks. This happens as soon as there is some line break in a bullet point. See these two examples:

### Example 1

```markdown
- Some text
  More text
- Some more text
  Some more text
- Text text
  text text
```

Will render as:

- Some text
  More text
- Some more text
  Some more text
- Text text
  text text



### Example 2

```
- Some text
  More text
- Some more text
  Some more text

- Text text
  text text
```

Will render as:

- Some text
  More text
- Some more text
  Some more text

- Text text
  text text

**Comment by thernstig** [comment]
As can be seen, this should also most likely be reported towards the Github rendering itself, but I'm unsure where to do that.

**Comment by mjbvz** [comment]
Do you have `markdown.preview.breaks` enabled? Because by default, the built-in markdown preview should render the markdown:

```
- Some text
  More text
- Some more text
  Some more text
- Text text
  text text
```

As

<img width="1419" alt="Screen Shot 2020-05-29 at 10 02 20 PM" src="https://user-images.githubusercontent.com/12821956/83320023-2ac90580-a1f8-11ea-9493-f372e742bb5f.png">

**Comment by mjbvz** [comment]
Also, the original two examples seem to renderer identically for me in the current VS Code insiders build

<img width="1537" alt="Screen Shot 2020-05-29 at 10 04 08 PM" src="https://user-images.githubusercontent.com/12821956/83320031-551ac300-a1f8-11ea-8325-e7b7b24fc573.png">

Can you please share a screenshot pointing out what is wrong?

**Comment by thernstig** [comment]
@mjbvz In your last screenshot, you can see they are not identical. Check the spacing between bullet-point 1 and 2 in the second example in your screenshot. This is what i am after. It incorrectly adds vertical padding. It happens when one uses line breaks in one bullet point. But that should not affect padding between bullet points. Please see my last reply https://github.com/microsoft/vscode/issues/98254#issuecomment-632582704

**Comment by mjbvz** [comment]
Thanks.

VS Code's built-in markdown preview targets commonmark. The current render does match [how commonmark renders the file](https://spec.commonmark.org/dingus/?text=-%20Bullet%20point%201%0A-%20Bullet%20point%202%0A%20%20%60%60%60javascript%0A%20%20const%20test%20%3D%20%27test%27%3B%0A%20%20%60%60%60%0A-%20Bullet%20point%203%0A%0A---%0A%0A-%20Bullet%20point%201%0A-%20Bullet%20point%202%0A%0A%20%20%60%60%60javascript%0A%20%20const%20test%20%3D%20%27test%27%3B%0A%20%20%60%60%60%0A%0A-%20Bullet%20point%203)

Specifically see the section of the spec on [loose vs tight lists](https://spec.commonmark.org/0.29/#loose)

I'm going to close this as by-design. I suspect that markdown lint rule may need to be reevaluated
