### ISSUE TITLE
Chinese version of the problem

### ISSUE THREAD

**Issue by hulang** [Microsoft/vscode#9825]
- VSCode Version:1.3.1
- OS Version:Win 7 x64

Steps to Reproduce:
Chinese version of the problem, there are a lot of local or English version, is estimated to be a new entry, there is no timely language. Hope that the next version of the language in a timely manner

**Comment by egamma** [comment]
@hulang there is a lag until we get all translations. We will sync the translations again for version 1.5.

**Comment by dbaeumer** [comment]
@hulang it is our plan that 1.5 will be fully translated.

**Comment by dbaeumer** [comment]
Made translation input today. Needs at least a week to be verified.
