### ISSUE TITLE
Mac Custom Keyboard Shortcut not working as expected

### ISSUE THREAD

**Issue by arturogh** [microsoft/vscode#98263]
Issue Type: <b>Bug</b>

I've set "CMD+Shift+G" to open "SCM" in my Mac Keyboard shortcut preferences. When I'm editing a file though, it brings up "Find" (CMD+F). If I click out of the file, then it does work.

VS Code version: Code - Insiders 1.46.0-insider (da3bf754c3c0eabda1dc80ed9d627679ee560697, 2020-05-19T10:04:14.981Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|-psn_0_848079|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.6.7
color-info|bie|0.5.1
vscode-eslint|dba|2.1.5
xcs-react-snippets|edu|0.1.1
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.7.0
path-autocomplete|ion|1.13.6
vscode-styled-components|jpo|0.0.29
color-highlight|nau|2.3.0
vscode-jest|Ort|3.2.0
markdown-preview-enhanced|shd|0.5.4

(2 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
![image](https://user-images.githubusercontent.com/4674940/82615761-0cbc2f00-9b80-11ea-860a-06671b2b86a7.png)

When an editor has focus, the `when` clause fires and the default keybinding wins. You need to unbind Cmd+Shift+G within the text editor.
