### ISSUE TITLE
Diagnostic Annotation API

### ISSUE THREAD

**Issue by aemino** [microsoft/vscode#98265]
Some languages have a system in place for annotated or "rich" error diagnostics. For example, take Rust, which can report errors like such:
![Five Years of Rust example error diagnostics](https://blog.rust-lang.org/images/2020-05-15-five-years-of-rust/trait-error-1.43.0.png)

Currently, such diagnostics tend to be relegated to the problems tab, where it can be rather difficult to figure out the context for each part of an error diagnostic.

I think that it would be hugely beneficial if there was a way that extensions were able to display advanced error diagnostics directly in the editor. Whether this is done by some kind of annotation that appears upon hovering over an error, or via a special zone widget, etc. is certainly up for discussion; I don't know what the best way to accomplish this would be.

Additionally, while the motivation for this feature is for better diagnostics, it's possible that this could be a more general feature that isn't specific to diagnostics; I could see potential uses of this feature in other domains.

**Comment by kieferrm** [comment]
Have  you tried `F8`?

**Comment by aemino** [comment]
Yes, I am aware of the Peek Problem interface but I don't think that it has the same capabilities as what I'm suggesting.

**Comment by sandy081** [comment]
/duplicate

#54272

**Comment by aemino** [comment]
Hi @sandy081, I don't think that this suggestion is a duplicate of #54272. While the two feature suggestions have similar aims—to expand the capabilities of the diagnostic feature—my suggestion is not the same. While the linked issue suggests allowing markdown in diagnostic tooltips, my suggestion is to expand what diagnostics are capable of, perhaps by allowing multiple tooltips to be displayed at once with annotation capabilities such as highlighting/underlining code in the editor itself.

**Comment by sandy081** [comment]
> I think that it would be hugely beneficial if there was a way that extensions were able to display advanced error diagnostics directly in the editor. Whether this is done by some kind of annotation that appears upon hovering over an error, or via a special zone widget, etc. is certainly up for discussion; I don't know what the best way to accomplish this would be.

We have peek and hover representations for diagnostics. Can you please let us know what do you think they are missing?
