### ISSUE TITLE
Activity bar items don't show focus border

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#98268]
![image](https://user-images.githubusercontent.com/35271042/82493370-b2966d80-9a9c-11ea-9f82-b0d03a84fcca.png)

Search, above, is in focus and the focus indicator does not appear. This doesn't affect the bottom part of the activity bar:

![image](https://user-images.githubusercontent.com/35271042/82493437-cfcb3c00-9a9c-11ea-95c3-ae0d09e489d4.png)

I think this is related to @sbatten's change (https://github.com/Microsoft/vscode/commit/6ec19f2840d570020b7c1520ae17ba2d57a928e7). Before, we would set the border color to transparent to not be visible, but once we introduced the opacity change this breaks the border color visibility:

https://github.com/microsoft/vscode/blob/b3162f52c64daca378537bdcf2a6211b48c154e3/src/vs/workbench/browser/parts/activitybar/media/activityaction.css#L16-L28

**Comment by sbatten** [comment]
fixed by https://github.com/microsoft/vscode/commit/858aff9699a11e9619b0049ee82066c647c6e399
