### ISSUE TITLE
Notebook webview mispositioned when closed as loading

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#98260]
```
Version: 1.46.0-insider (user setup)
Commit: da3bf754c3c0eabda1dc80ed9d627679ee560697
Date: 2020-05-19T10:07:59.927Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

Steps to Reproduce:

1. Opened a folder where I had a notebook open
2. "Close all" editors before the notebook loads

I ended up in this interesting state:

![](https://memes.peet.io/img/20-05-99f741ad-4f0b-40f8-a8b3-a71531ad8dd8.png)

Does this issue occur when all extensions are disabled?: No

**Comment by rebornix** [comment]
We have made a lot of bug fixes to the editor opening / events and I haven't been able to reproduce this issue for quite some time. Let's move it to June and see if anyone ran into similar issues.

**Comment by rebornix** [comment]
This should be gone now.
