### ISSUE TITLE
over 250 warning, error. can't be displayed.

### ISSUE THREAD

**Issue by owayo** [Microsoft/vscode#9826]
- VSCode Version: 1.3.1  

over 250 warning, error. can't be displayed.  

`_maxDiagnosticsPerFile` that are hard-coded.

[extHostDiagnostics.ts#L16](https://github.com/Microsoft/vscode/blob/bdaa72b842bb4db30fdf776534bcebd004b8faa1/src/vs/workbench/api/node/extHostDiagnostics.ts#L16)

want to change in user setting.
(of course understanding impact on performance)

**Comment by jrieken** [comment]
That's by design for (1) performance reasons (we don't want to allow the extension host spamming the main thread) and (2) we don't believe a user will appreciate/being able to act on so many errors.

@owayo What is your use-case that requires to have more than 250 diagnostics per file?

**Comment by owayo** [comment]
Thanks for reply.

use-case  
code review of too meny warnings include script from before the change.  
e.g.
originally script too many warning include. (over 250)
the script end line edit. (new warning add)
too many warnings to reach the change point, can't be checked a warning or error of Changes

**Comment by jrieken** [comment]
I still have trouble understanding why more than 250 messages are desirable. Is it that only the 251st diagnostic information is important? The model isn't append but replace when `DiagnosticCollection.set` is called so there is some control on the extension side.

**Comment by owayo** [comment]
yes, 251st diagnostic imformation is important.   
It should marked-up warning is not marked-up.

**Comment by jrieken** [comment]
And the first 250 diagnostics messages aren't important? Then just update the collection with the last `n` (`n < 250`) messages. The limit of 250 is per diagnostics collection so entirely up to you. Can you by any chance point me to some of your code where this happens?

**Comment by owayo** [comment]
yes. first 250 diagnostics messages are not important.  

sorry, It can not be published because it is the company app.  
  
e.g.
VSCode installed ESLint.
**Lint rule**
~~~
"rules": {
    "quotes": [
        "warn",
        "single"
    ]
}
~~~
**JavaScript (check target)**
~~~
var hoge = ""
    + ""
    + ""
    + ""
    ~~~ repeat 250 over ~~~
    + ""
    + "";

var fuga = ""; // <- want to check!
~~~
double-quote of `fuga` is not warning display.

**Comment by jrieken** [comment]
So, you are not authoring the extension but just using it (like eslint)?

**Comment by owayo** [comment]
I'm afraid I don't understand. sorry.
 # English is not my first language.

I hope 251st(and over) warnings, error display. (good in any way)
If the implementation is difficult, just use use it.

**Comment by jrieken** [comment]
I still believe that not showing thousands of errors is a good idea because the squiggle should be a call for attention. Also the editor not more than [500](https://github.com/Microsoft/vscode/blob/joh/next/src/vs/editor/common/services/modelServiceImpl.ts#L340) squiggles for the [same](https://github.com/Microsoft/vscode/issues/9826#issuecomment-236118378) reasons. My general advice to get rid of those warnings - either by changing your code or lint configuration. 

What we can do (tho I doubt it will help in your specific case) is to be smarter when cropping the list of errors. Instead of taking the first 250 we could sort by severity such that you get errors over warnings. Obviously that doesn't help if all diagnostics are of the same type. Last, we could also add a synthetic error that tells you how many errors have been ignored

**Comment by owayo** [comment]
thank you a lot.  
looking forward to seeing release.

**Comment by slifin** [comment]
(1) performance reasons (we don't want to allow the extension host spamming the main thread) 
- is 252 not okay for performance?

(2) we don't believe a user will appreciate/being able to act on so many errors.
- It's not just errors that this applies to it's also linting, a program still works if it has lint errors, as it is I just can't see those linting errors in 90% of my program

I hope this hard arbitrary limit will be changed to be user configurable

**Comment by Eldaw** [comment]
It also limits the number of spelling errors that the extension Spell Right can find, to 250.
