### ISSUE TITLE
Add option to remove currently open file from GoTo file menu

### ISSUE THREAD

**Issue by jgscherber** [microsoft/vscode#98264]
![image](https://user-images.githubusercontent.com/6207661/82489815-dd39f380-9aa7-11ea-8a34-e986f277280e.png)

Whe using the "Go To File..." shortcut, the files listed are in sorted by most recently opened. That means the current file is the one on top (because it's most recent), which means if I hit `Enter` immediately, VS Code does nothing (because I'm already in the file).

I want the file I was in previously to be the one at the top so I can use it similar to how `Ctrl-Tab` functions. I don't want to use `Ctrl-Tab` because the menu requires holding `Ctrl` to stay open and only lists open files.

The option would be
* `enabled (default)`: current file is displayed at the top of the "Go To File..." menu
* `disabled`: current file is not display in the drop down, but is displayed when searching

**Comment by bpasero** [comment]
There is a command `workbench.action.quickOpenPreviousEditor` you can bind that keybinding to which will do that.
