### ISSUE TITLE
[Insiders] Experimental Use Title Event Issue with Powershell 7

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode#98262]
Issue Type: <b>Bug</b>

Trying to use the new setting with Powershell 7. It does "work" except it constantly reverts the title to "pwsh" or "git" rather than what the UI has set for the terminal title after the script has completed. The loop is used in the example just to show that it reverts after script completion and not after each title "change".
![Capture](https://user-images.githubusercontent.com/15258962/82488456-c50ca900-9a94-11ea-852d-a4ab02afb0ee.gif)

Looping @TylerLeonhardt in case he has any insight.

VS Code version: Code - Insiders 1.46.0-insider (da3bf754c3c0eabda1dc80ed9d627679ee560697, 2020-05-19T10:07:59.927Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.60GB (1.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
azureautomation|Awe|1.0.2
bracket-pair-colorizer-2|Coe|0.1.3
gitlens|eam|10.2.1
vs-code-xml-format|fab|0.1.5
vscode-pull-request-github|Git|0.16.1
gc-excelviewer|Gra|2.1.34
todo-tree|Gru|0.0.175
vscode-drawio|hed|0.4.0
vscode-peacock|joh|3.7.2
better-powershell-syntax-highlighting|jus|0.0.2
git-graph|mhu|1.22.0
azure-pipelines|ms-|1.170.0
vscode-azurefunctions|ms-|0.22.1
vscode-azurestorage|ms-|0.9.0
vscode-docker|ms-|1.2.0
csharp|ms-|1.21.18
remote-containers|ms-|0.117.1
remote-ssh-edit-nightly|ms-|2020.5.19620
remote-ssh-nightly|ms-|2020.5.19620
remote-wsl|ms-|0.44.2
azure-account|ms-|0.8.11
powershell-preview|ms-|2020.5.0
vsonline|ms-|1.0.2220
team|ms-|1.161.0
indent-rainbow|ode|7.4.0
vscode-yaml|red|0.8.0
vscode-sort-json|ric|1.18.0
vscode-zipexplorer|sle|0.3.1
vscode-icons|vsc|10.1.1
codetour|vsl|0.0.26
gistfs|vsl|0.0.67
gitdoc|vsl|0.0.6
better-align|wwm|1.1.6
markdown-all-in-one|yzh|2.8.0

</details>

**Comment by Tyriar** [comment]
I suspect this is working as designed as pwsh would set it again when you return to the prompt? @TylerLeonhardt?

To test use `"terminal.integrated.experimentalUseTitleEvent": true`

**Comment by TylerLeonhardt** [comment]
No I don't think we do that:

![Screen-Cast-2020-06-08-at-12 52 58-PM](https://user-images.githubusercontent.com/2644648/84074801-fbe52900-a987-11ea-9f1a-0abd5335abcf.gif)

**Comment by JustinGrote** [comment]
@Tyriar @TylerLeonhardt  Confirmed fixed and working in latest insiders. Thanks!

**Comment by Tyriar** [comment]
Thanks for verifying 🙂
