### ISSUE TITLE
Ctrl+Click on Terminal not working

### ISSUE THREAD

**Issue by XynanXDB** [microsoft/vscode#98277]
I'm working on Unreal C++ project. Ctrl+click on Terminal started not working since a week ago. 

Expected result is when my mouse hover over the path link on Terminal, it will display "Ctrl+click to follow link" and when I ctrl+link, I will go to the file of the path.

Current result is when my mouse hover over the path link on Terminal, it DOES NOT display "Ctrl+click to follow link" and when I ctrl+click nothing happens.

**Comment by XynanXDB** [comment]
Hi, is there any update on the issue?

**Comment by Tyriar** [comment]
Please provide a screenshot illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/needsMoreInfo

**Comment by XynanXDB** [comment]
I wasn't able to capture the old terminal that was working perfectly but this is the one with the issue..
![Capture](https://user-images.githubusercontent.com/32987787/83776716-133bc200-a6bb-11ea-96f3-e025d5090a7e.PNG)

About 1-2 months ago, the error sentence will be underlined and clickable, on hover it will show "Ctrl-Click to follow link" but the picture I provided above shows that it's not underlined nor it's clickable.

VSCode version : April 2020 (v 1.45)
OS : Windows 10 Pro 10.0.18362 Build 18362
Extensions:
1. C/C++ by Microsoft (v 0.28.2)
2. C# by Microsoft(v 1.22.0)
3. C++ Helper by amir (v 0.1.1)
4. Clang-Format by xaver (v 1.9.0)
5. Debugger for Unity by Unity Technologies (v 2.7.5)
6. GitLens - Git supercharged by Eric Amodio (v 10.2.1)
7. Resource Monitor by mutantdino (v 1.0.7)
8. SynthWave '84 by Robb Owen (v 0.1.5)
9. Todo Tree by Gruntfuggly (v 0.0.176)
10. Unreal Engine 4 Snippets by CAPTNCAPS (v 2.0.0)
11. vscode-spotify by shyykoserhiy (v 3.1.0)

Here is my setting.json config:
![image](https://user-images.githubusercontent.com/32987787/83778340-294a8200-a6bd-11ea-9985-fc05899496da.png)


Thanks for replying, look forward to hear from you soon.

**Comment by Tyriar** [comment]
Are you expecting the .cpp path to be clickable? That won't work now as it has a space in it and I'm not sure there's a nice way to detect links with spaces.

**Comment by Tyriar** [comment]
Also note you can turn on the new link system which is way better, see https://code.visualstudio.com/updates/v1_45#_improved-links-in-the-terminal. Path links with spaces still won't work though.

**Comment by XynanXDB** [comment]
I can confirm it's the space in the link that breaks the ctrl-click feature. I suggest either add support for ctrl-click for terminal or make the Microsoft user name to auto omit the space in between last name and first name. I was using the Microsoft account with Xynan Lee as my name and my C:\Users\{Username} was Xynan Lee which clearly broke the ctrl-click feature.
