### ISSUE TITLE
VS Code has high CPU usage after April 2020 Update

### ISSUE THREAD

**Issue by aroyic** [microsoft/vscode#98273]
Issue Type: <b>Performance Issue</b>

All extensions have been disabled. But the CPU usage is still extremely high. This issue started after installing the April 2020 Update. Attached are some details from running **code --status** at different points of running my application.
[All extensions disabled.txt](https://github.com/microsoft/vscode/files/4659367/All.extensions.disabled.txt)
[All extensions disabled 1.txt](https://github.com/microsoft/vscode/files/4659368/All.extensions.disabled.1.txt)
[All extensions disabled 2.txt](https://github.com/microsoft/vscode/files/4659369/All.extensions.disabled.2.txt)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (9.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    72	 20840	code main
    0	    26	  9972	   utility
    4	   191	 12476	   gpu-process
    3	   189	 17300	   window (ChooseMailingModal.js - FishbowlONE - Visual Studio Code)
    0	    62	  9404	     extensionHost
    6	   133	  4316	       electron_node tsserver.js 
    0	    44	 19096	         electron_node typingsInstaller.js typesMap.js 
    1	    26	 21324	         electron_node watchGuard.js 
    0	    51	 22464	       electron_node tsserver.js 
    0	    11	 19544	     watcherService 
    0	    10	 13532	       console-window-host (Windows internal process)
    0	     6	 21652	     winpty-process
    0	     9	 10144	       console-window-host (Windows internal process)
    0	    61	 16316	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
   21	    71	 20376	   shared-process
    0	    65	 20896	   window (Issue Reporter)
    0	    14	 21868	   electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (ChooseMailingModal.js - FishbowlONE - Visual Studio Code)
|    Folder (FishbowlONE): 1695 files
|      File types: cs(834) js(284) cshtml(71) config(56) png(37) svg(36)
|                  jpg(23) csproj(20) sass(18) txt(13)
|      Conf files: csproj(20) sln(2) jsconfig.json(1) package.json(1)
|                  webpack.config.js(1);
```

</details>
Extensions: none

[All extensions enabled.txt](https://github.com/microsoft/vscode/files/4659385/All.extensions.enabled.txt)

**Comment by kieferrm** [comment]
In the first attachment, the typings installer is active. This may happen when you open a JS folder and the typings are not yet cached. This calms down after a brief moment. In the other two attachments, I see that you using `npm run watch` and `npm run dev` causes CPU load on your system.

**Comment by poteat** [comment]
Unfortunately, I've been getting this issue as well on the latest update.  On Ubuntu, if that helps.

```
1.45.1
5763d909d5f12fe19f215cbfdd29a91c0fa9208a
x64
```

**Comment by egamma** [comment]
@poteat unfortunately this does not help. please file a separate issue with your findings when you follow this guide https://github.com/microsoft/vscode/wiki/Performance-Issues
