### ISSUE TITLE
explorerResourceIsFolder combine with listDoubleSelection

### ISSUE THREAD

**Issue by moshfeu** [microsoft/vscode#98272]
Currently following `when` clause `explorerResourceIsFolder && listDoubleSelection` is `true` when the user choose a **file** and then a **folder** (unlike the vice-versa)

My propose is to add clauses such as `allSelectionIsFolder`, `allSelectionIsFile` etc.

**Comment by isidorn** [comment]
This is a fair feature request, however those context keys are designed for internal use and we would not change anything there at the moment.
However leaving this request open as we might tackle it in the future.

**Comment by moshfeu** [comment]
Thanks for the reply.
Maybe not to **change** but to **add**?
