### ISSUE TITLE
Find In Project: Add tooltips/help links for Include/Exclude file inputs - what is the syntax here?

### ISSUE THREAD

**Issue by dmurph** [microsoft/vscode#98271]
It is hard to know what the "Include files" and "exclude files" syntax is. It is NOT obvious that it is a comma separated list of.. regex? I haven't seen that before. Please a tooltip or help link or anything here that helps me learn that :)

Thanks!

**Comment by roblourens** [comment]
It's in the docs here: https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options

**Comment by dmurph** [comment]
I understand it's in the docs - this feature request was to add a tooltip or a help link into the UI.

**Comment by roblourens** [comment]
There is another issue to add a dropdown/button to get some nice pre-filled examples but I don't know when I'll get to that. I think we could add some basic placeholder to the inputs the same as in the Problems pane.

![image](https://user-images.githubusercontent.com/323878/83434392-02abf300-a400-11ea-8ab3-49266e9982fd.png)
