### ISSUE TITLE
Extension icons don't render in the remote WSL instance with VS Code Insiders (works with VS Code)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#98278]
- VSCode Version:Version: 1.46.0-insider (user setup)
Commit: da3bf754c3c0eabda1dc80ed9d627679ee560697
Date: 2020-05-19T10:07:59.927Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
- OS Version: local OS is Windows, remote connecting to WSL (Ubuntu 20)

Steps to Reproduce:

1. Open some folder under WSL (Ubuntu 20).
2. Install some extension in the remote WSL instance.

Bug: The extension icon doesn't render. It does with non-Insiders. See the screenshot:

![image](https://user-images.githubusercontent.com/19859882/82502042-2b042b00-9aab-11ea-886a-ee79e503e2b8.png)

Does this issue occur when all extensions are disabled?: N/A

**Comment by sean-mcmanus** [comment]
Also, when I open the Extension page for an extension, the currently selected local extension icon gets rendered for the currently selected remote icon. See the screenshot:
![image](https://user-images.githubusercontent.com/19859882/82527652-d3d27a80-9aeb-11ea-9dc5-4c0bd25359e5.png)

**Comment by sandy081** [comment]
I observed this with other action icons too.

**Comment by alexdima** [comment]
I have asked @aeschli to try to repro because he has a WSL2 working setup and he was not able to do so. 

@sean-mcmanus Can you please check again, maybe there was some kind of problem that got resolved in the meantime on Insiders?

![image](https://user-images.githubusercontent.com/5047891/83756461-5f611500-a66f-11ea-8ff1-164bbe69baaa.png)

**Comment by aeschli** [comment]
That's what I get on Windows 19041, VSCode Insiders 1.46.- 595d2b96 (2020-06-03)

**Comment by sean-mcmanus** [comment]
Yeah, it seems fixed now.
