### ISSUE TITLE
Intellisense not working on Chromebook

### ISSUE THREAD

**Issue by ThePotato10** [microsoft/vscode#98280]
- VSCode Version: 1.45.15763d909d5f12fe19f215cbfdd29a91c0fa9208ax64
- OS Version: ChromeOS 81.0.4044.141

Steps to Reproduce:

1. Started typing in a CSS stylesheet. Intellisense was rendering incorrectly
2. Issue also occured in HTML and JavaScript

Does this issue occur when all extensions are disabled?: 
Yes

![Screenshot 2020-05-20 at 7 04 57 PM](https://user-images.githubusercontent.com/63891976/82506449-cf976480-9acd-11ea-8ce1-02486539b953.png)

**Comment by kieferrm** [comment]
We don't have any supported distro for ChromeOS.

**Comment by ThePotato10** [comment]
Installed on a Chromebook through Linux app support. Debian download. Sorry for confusion

**Comment by kieferrm** [comment]
Can pls paste the About info?

**Comment by ThePotato10** [comment]
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.19.98-08076-g24ab33fb8e14

Looking at this, I realized I've given you wrong information. I'm sorry.

**Comment by aeschli** [comment]
Looks like a rendering issue. Not sure who owns the suggest widget now. @jrieken ?

**Comment by jrieken** [comment]
Cannot reproduce, please tweak your steps

**Comment by jrieken** [comment]
@mtbun please update steps here

**Comment by mtbun** [comment]
i solved my problem. i made the suggestion font bigger.

**Comment by jrieken** [comment]
how small was it? did you configure that beforehand or was the default bogous?

**Comment by mtbun** [comment]
i've no idea. it happened suddenly

**Comment by jrieken** [comment]
what was the value before, what is it now? what is your font size?

**Comment by mtbun** [comment]
before value: 2
i changed it, current value: 14
my font size:14

**Comment by mtbun** [comment]
i found out the problem as in the photo

photo: https://www.photobox.co.uk/my/photo?album_id=5866718323&photo_id=503017261915

**Comment by jrieken** [comment]
@ThePotato10 can you check your suggest font size setting
