### ISSUE TITLE
Hi, left sidebar Extensitions's update number can auto hide ?

### ISSUE THREAD

**Issue by fegg** [Microsoft/vscode#9828]
- VSCode Version: 1.3.1 (1.3.1)
- OS Version: Mac OS X 10.11

Steps to Reproduce:

1. open vscode.
2. click left sidebar extensions function.

I have an obsession...want to it can auto hide~

My english is not well , so use one image description:

[please click this link view image](http://i4.piimg.com/567571/ff7adf3c8ec68369.png)

**Comment by kieferrm** [comment]
We want you to be aware of the number of outdated extensions. It would be counter productive to hide the number.  We won't change the current behavior.
