### ISSUE TITLE
When saving a file, and clic right clic in folder list vscode crash

### ISSUE THREAD

**Issue by szchmausser** [microsoft/vscode#98281]
Issue Type: <b>Bug</b>

1. Create file
2. Save file
3. Right clic under some folder in opened explorer window

then Crash...

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (0.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.0.27
project-manager|ale|11.0.1
laravel-extra-intellisense|ami|0.3.1
All-Autocomplete|Ati|0.0.23
laravel-blade-spacer|aus|2.1.2
vagrant|bbe|0.5.0
vscode-intelephense-client|bme|1.3.11
intellij-parameter-hints|Bob|0.3.0
htmltagwrap|bra|0.0.7
laravel-blade|cjh|1.1.2
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.1.3
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
vscode-phpmd|eco|1.2.0
prettier-vscode|esb|4.7.0
php-debug|fel|1.13.0
auto-rename-tag|for|0.1.3
vscode-php-cs-fixer|fte|0.3.0
vscode-icontheme-nomo-dark-macos|Gau|1.0.3
lintlens|ghm|3.0.0
todo-tree|Gru|0.0.175
php-awesome-snippets|hak|1.1.3
output-colorizer|IBM|0.1.2
search-editor-apply-changes|jak|0.1.1
php-namespace-resolver|Meh|1.1.8
git-graph|mhu|1.22.0
dotenv|mik|1.0.1
vscode-duplicate|mrm|1.2.1
python|ms-|2020.5.80290
php-docblocker|nei|2.1.0
laravel-blade|one|1.21.0
laravel5-snippets|one|1.8.0
phpstorm-snippets|phi|1.1.1
vscode-css-peek|pra|3.0.2
explorer-exclude-vscode-extension|Red|1.2.0
Unotes|rya|1.1.7
vscode-open|san|0.1.0
code-settings-sync|Sha|3.4.3
rewrap|stk|1.10.1
code-spell-checker|str|1.9.0
code-spell-checker-spanish|str|1.0.3
control-snippets|svi|1.8.1
vscode-laravel-assist|tia|0.1.7
vscodeintellicode|Vis|1.2.7
vscode-icons|vsc|10.1.1
local-history|xyz|1.8.1
cursorCharCode|zei|0.1.1

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with all extensions disabled?

**Comment by bpasero** [comment]
@szchmausser 

> Right clic under some folder in opened explorer window

What does that mean exactly?
