### ISSUE TITLE
Code Helper Render High CPU when Python Plugin Enabled

### ISSUE THREAD

**Issue by shyamyadati** [microsoft/vscode#98286]
Issue Type: <b>Performance Issue</b>

Hi CPU usage (100%) when Microsoft Python plugin enabled.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (15.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   17	   131	 51535	code main
    0	    98	 51536	   gpu-process
    0	    33	 51538	   utility
    0	   393	 51539	   window (Settings — my (Workspace))
    0	   164	 51563	     extensionHost
  100	    33	 52159	       /usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python /Users/$USER/.vscode/extensions/ms-python.python-2020.4.76186/pythonFiles/pyvsc-run-isolated.py /Users/$USER/.vscode/extensions/ms-python.python-2020.4.76186/pythonFiles/completion.py
    0	    33	 52162	         /Users/$USER/miniconda3/bin/python /Users/$USER/.vscode/extensions/ms-python.python-2020.4.76186/pythonFiles/lib/python/jedi/inference/compiled/subprocess/__main__.py /Users/$USER/.vscode/extensions/ms-python.python-2020.4.76186/pythonFiles/lib/python 3.7.6
    0	    33	 52216	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=51563
    0	    33	 51564	     watcherService
    0	    33	 51565	     searchService
    0	   131	 51586	   shared-process
    0	     0	 52777	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    98	 52774	   window (Issue Reporter)
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
systemd-unit-file|coo|1.0.6
gitlens|eam|10.2.1
git-graph|mhu|1.22.0
python|ms-|2020.5.80290
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
Go|ms-|0.14.2
html5-boilerplate|sid|1.0.3
vscode-proto3|zxh|0.4.2

(1 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
\extPython
