### ISSUE TITLE
Bundled extensions behave differently than external extensions

### ISSUE THREAD

**Issue by karljs** [microsoft/vscode#98284]
Issue Type: <b>Bug</b>

I am working on a set of patches atop VS Code that are intended to produce something like a purpose-made IDE for a specific use-case.  As part of that, I want to bundle extensions beyond those that are normally already bundled.  When I copy extensions to the `extensions` directory and run my build, it seems to pick them up just fine, but in at least one case the runtime behavior is different.

Specifically, with this extension:
https://github.com/WebFreak001/code-debug

When I install it externally, or with the `--extensions-dir` flag, it works fine.  When I copy it to `extensions` and run a build, it fails to debug even a hello-world application with the following error:

```
ERR timeout after 1000 ms: Error: timeout after 1000 ms
    at RawDebugSession.handleErrorResponse (file:///Users/<snip>/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:161168:20)
    at file:///Users/<snip>/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:161141:59
    at async RawDebugSession.shutdown (file:///Users/<snip>/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:161001:25)
```

I'm running my build with the following steps (but note this is not MacOS-specific):
```
yarn
yarn gulp compile-build
yarn gulp compile-extensions-build
yarn gulp minify-vscode
yarn gulp vscode-darwin
```

Are there different assumptions around bundled extensions and their lifetimes? Am I missing a build step or failing to edit some file that allows additional bundled extensions?

Thanks for any help.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

**Comment by kieferrm** [comment]
I'm unaware of any impact on whether it runs as built-in extensions or as manually installed extension.
@connor4312 anything you're aware of regarding debuggers. Pls close if not.

**Comment by connor4312** [comment]
There's nothing different in VS Code about built-in extensions. It's possible something in the path of the bundled extension might be causing issues -- I've seen issues arising from special characters or path lengths in the past. I'd recommend contacting the extension author for further diagnosis.
