### ISSUE TITLE
Explorer Context Menu ordering issues

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#9829]
Testing #9153 (test plan #9702)

using https://github.com/chrisdias/vscode-opennewinstance

here is my menus contribution:

``` json
"menus": {
            "explorer/context": [
                {
                    "command": "extension.openNewInstance"
                    ,"group": "navigation"
                    
                },
                {
                    "command": "extension.scopeToHere"
                    ,"group": "navigation"
                }
            ]
        }
```

This results in a menu that looks like this:

> Open to the Side
> Reveal in Finder
> Open in Terminal
> **Open New Workbench Here**
> **Scope Workbench to Here**

Scenario: I want to move the second menu to the top of the list.  I set up my menus contribution to look like this:

``` json
"menus": {
            "explorer/context": [
                {
                    "command": "extension.openNewInstance"
                    ,"group": "navigation"
                    
                },
                {
                    "command": "extension.scopeToHere"
                    ,"group": "navigation@-1"
                }
            ]
        }
```

Expected: Given that "Legacy commands have the implicit order of zero (navigation@0)" I expected only the menu item that has a weighting < 0 to move to the top of the list, such as:

> **Scope Workbench to Here** (@-1)
> Open to the Side
> Reveal in Finder
> Open in Terminal
> **Open New Workbench Here**  (no order specified)

However, it looks like this:

> **Open New Workbench Here**  (no order specified)
> **Scope Workbench to Here** (order @-1)
> Open to the Side
> Reveal in Finder
> Open in Terminal

However, if I change the ordering as follows, where the first menu item has no ordering but the second does:

``` json
        "menus": {
            "explorer/context": [
                {
                    "command": "extension.openNewInstance"
                    ,"group": "navigation"
                    
                },
                {
                    "command": "extension.scopeToHere"
                    ,"group": "navigation@1"
                }
            ]
        }
``` 

The result in this:

> **Open New Workbench Here** (no order specified, why did this move to the top of the list??)
> Open to the Side
> Reveal in Finder
> Open in Terminal
> **Scope Workbench to Here** (order of @1)

I dont understand why the first menu is now at the top of the list, while i can see the second one is at the bottom of the list (because @1 is > @0).

**Comment by jrieken** [comment]
This was fixed with https://github.com/Microsoft/vscode/commit/dfea75a8f2328241a907cd9cc65fb9bd5e291d13. Sorting is hard and there an issue when sorting two item from the `navigation` group. With today's build it should be fine

**Comment by chrisdias** [comment]
verified, i like it!
