### ISSUE TITLE
Suggestions for importing or deleting packages?

### ISSUE THREAD

**Issue by 395053994** [microsoft/vscode#98293]
Suggestions for importing or deleting packages?
It is recommended that vscode can be like the IDEA IDE. In the process of adding new java packages or deleting useless Java packages, the code editor should not be shaken, just change the warning prompt.
Currently this behavior of vscode will be jittery and it feels very bad. Hope to improve, you can refer to the IDEA IDE implementation process..

**Comment by 395053994** [comment]
We hope that open source vscode will become the best code editor for all humans and Microsoft!

**Comment by kieferrm** [comment]
\extJava
