### ISSUE TITLE
Way to easily collapse folders having too many files or sub folders

### ISSUE THREAD

**Issue by electriccode** [microsoft/vscode#98299]
To be precise I am talking about node_modules folder which gets opened a lot of times when I am debugging things down to library level (say clicking a type definition or method implementation or putting logs or setting breakpoints in it). There is no convenient way to actually collapse it back without scrolling all the way up. Not sure if there is an easy way to tackle this.

![image](https://user-images.githubusercontent.com/1471581/82524892-aae2d180-9b4d-11ea-9592-528cf4a06b37.png)

**Comment by yubaoquan** [comment]
Try press left arrow button.

**Comment by electriccode** [comment]
Thanks @yubaoquan 
Closing this as pressing left arrow buttons collapses the parent folder and if you keep pressing it, it will eventually collapse `node_modules` folder as well.
