### ISSUE TITLE
Python black formatter broken when file starting with an empty line

### ISSUE THREAD

**Issue by ylilarry** [microsoft/vscode#98296]
- VSCode Version: 
- OS Version: macOS 10.15.4

Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (6 days ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:

1. create a python file, the first line is empty, and the following lines valid python code
2. in settings, set formatt provider to black
3. run format document

In the OUTPUT panel, the error shows up:

Formatting with black failed.
TypeError: Cannot read property 'length' of undefined

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
\extPython
