### ISSUE TITLE
stage/unstage selected ranges in standard text buffers/editor tabs

### ISSUE THREAD

**Issue by devinrhode2** [microsoft/vscode#98292]
I love staging chunks of code inside the git diff live view. I often edit lots of code in this git diff view, but it gets awkward once I've changed a certain amount of code. I'd love to be able to stage/unstage chunks of code outside the diff viewer, in normal editor tabs/text buffers.
![CleanShot 2020-05-20 at 20 56 36@2x](https://user-images.githubusercontent.com/539816/82515809-c8c51d80-9ade-11ea-9660-3667078c1705.png)
![CleanShot 2020-05-20 at 20 56 06@2x](https://user-images.githubusercontent.com/539816/82515815-ccf13b00-9ade-11ea-8379-3f0354d91577.png)

**Comment by joaomoreno** [comment]
Have you tried clicking on that little inline git diff marker+viewer and then checking out the actions in the header of the view which shows up?
