### ISSUE TITLE
many selected file, Finder display,  only selected a file

### ISSUE THREAD

**Issue by fjqingyou** [microsoft/vscode#98302]
Issue Type: <b>Bug</b>

selected many file,

mouse right and click menu  Finder display,

only selected a file in finder

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|23, 16, 10|
|Memory (System)|8.00GB (0.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
asp-net-core-switcher|adr|2.0.2
include-autocomplete|ajs|0.0.4
shaderlabvscodefree|aml|1.1.6
code-gnu-global|aus|0.2.2
razor-plus|aus|0.1.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
cocos-debug|Chu|0.0.1
cocos-creator|Chu|0.0.1
cocos-debug|Chu|0.0.1
githistory|don|0.6.5
gitlens|eam|10.2.1
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.11
english-to-chinese|ele|0.0.3
git-project-manager|fel|1.7.1
cshtml|fir|0.1.3
cshtml-tm|fir|1.0.0
export-zip|fjq|0.0.1
convertplist|gio|0.0.6
gc-excelviewer|Gra|2.1.34
ilspy-vscode|ics|0.7.11
vscode-csharp-snippets|jor|0.3.1
docomment|k--|0.1.11
vscode-codemetrics|kis|1.24.0
spectrogram|lan|1.1.0
csharpfixformat|Leo|0.0.84
autoconf|mae|0.1.0
vscode-clang|mit|0.2.3
vscode-docker|ms-|1.2.0
vscode-language-pack-en-GB|MS-|1.45.1
vscode-language-pack-zh-hans|MS-|1.45.1
csharp|ms-|1.21.18
mssql|ms-|1.9.0
cpptools|ms-|0.28.1
mono-debug|ms-|0.15.8
debugger-for-chrome|msj|4.12.7
vscode-json-editor|nic|0.2.3
vetur|oct|0.24.0
vscode-code-outline|pat|0.2.1
vscode-unitymeta|PTD|0.0.7
Csharp-ASPNETCore|rah|1.11.0
angelscript|ren|1.0.1
unityshader-intellisense|Sar|0.3.1
shader|sle|1.1.4
asp-net-core-vs-code-extension-pack|tem|1.0.3
unity-tools|Tob|1.2.3
tds-vscode|TOT|1.0.2
cmake|twx|0.0.17
unity-debug|Uni|2.7.5
vscode-icons|vsc|10.1.1
change-case|wma|1.0.0
cocos-effect|Yaj|0.2.0
propertylist|zho|0.0.2

</details>

**Comment by fjqingyou** [comment]
Confirm not overwrite

disabe all extensions, retry same result

**Comment by isidorn** [comment]
Yeah, Open In Finder does not support selecting multiple files in the native finder for now.
Though this is a fair feature request, thus assigning to backlog and we might look into it in the future.
