### ISSUE TITLE
Question : How to delete all the available snippets from VS code ? 

### ISSUE THREAD

**Issue by codingonHP** [Microsoft/vscode#9830]
I want to delete all the snippets from vs code because they keep showing up in the intellisense, even at the places where it doesn't make any sense. They move the important properties/method down the list. It makes the overall experience bad. I have to scroll down the list if I have to see all the available options and then figure out that this is a snippet and this is what I am looking for. It becomes a pain if I install other 3rd party snippets like for angular2 etc.
If there are workarounds apart from deleting, please suggest as well
-Thanks.

**Comment by jrieken** [comment]
With the July release (coming very soon) we will add a new configuration option that allows to define how snippets show show in the suggest widget. Either `none` or influence the sorting as `top`, `inline` (default, as today), and `bottom`. All details and improvements are here: https://github.com/Microsoft/vscode/issues/9286

**Comment by codingonHP** [comment]
:) 
Much needed !

**Comment by jrieken** [comment]
You can have with our [insider builds](https://code.visualstudio.com/insiders) already today ;-)

**Comment by codingonHP** [comment]
:+1:  Great!

**Comment by codingonHP** [comment]
I have update my insider build. Can you please tell me the new configuration option that needs to be configured ?

**Comment by jrieken** [comment]
Select `F1` > `Open User Settings` and add the `editor.snippetSuggestions`-setting.

**Comment by codingonHP** [comment]
-thanks
