### ISSUE TITLE
macOS Close Window / Close Editor use same shortcut key (cmd+W)

### ISSUE THREAD

**Issue by junketjim** [microsoft/vscode#98303]
Issue Type: <b>Bug</b>

Go to menu File... 
Close Window (shortcut cmd+W) and Close Editor (shortcut cmd+W)
The shortcuts are the same by default.  When using cmd+W the shortcut triggers Close Editor.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|24.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kieferrm** [comment]
@junketjim  Cmd+W closes the active editor. When no editor is active it closes the active Window. Similar behavior to browsers. You can always close a window with Shift+Cmd+W.
