### ISSUE TITLE
Some commands are missing the original English description

### ISSUE THREAD

**Issue by fangbinwei** [microsoft/vscode#98311]
- VSCode Version: 1.45.1
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. press F1 to show all commands
2. type English words to find the command

I used to ues `next terminal` or `next` to find the command , and focus to the next terminal. (v1.44.2)

![1 44 2](https://user-images.githubusercontent.com/13298807/82548448-dc7b8d00-9b8d-11ea-82c2-d0f633afa004.png)

after I update vscode to 1.45.1, I can't find these command by typing English words

![image](https://user-images.githubusercontent.com/13298807/82548885-a25ebb00-9b8e-11ea-9350-a386c5ae00e0.png)

But If i change vscode display language to English.

these commands can show English description correctly.

![image](https://user-images.githubusercontent.com/13298807/82549476-90314c80-9b8f-11ea-82e5-03514ff7c993.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
Since this works in general it doesn't look like a problem with the NLS infrastructure.

@Tyriar can you please check that you provide both strings for the command.
