### ISSUE TITLE
Weird Screen Glitch

### ISSUE THREAD

**Issue by donrafiki2918** [microsoft/vscode#98317]
I have this issue that the application starts glitching and fills with white dots.
This happens when the application is not the main focus, and I use another. Right now, the issue also happens when in full screen.

## Specs
Platform: Windows 10 version 1909
Screen resolution and size: 1920x1080, 17.3"
Laptop Brand: Dell
VSC Version: 1.45.1

![Screenshot (1)](https://user-images.githubusercontent.com/42477094/82558197-c2609100-9b32-11ea-9259-10f0f72d7d85.png)
At half screen

![Screenshot (3)](https://user-images.githubusercontent.com/42477094/82558342-0ce20d80-9b33-11ea-8008-b92e8f587b21.png)
At Full screen

**Comment by fejx** [comment]
I do not know how to resolve the issue, but anyone trying to help you will most definitely want to know which OS and which version of vscode you are using.

**Comment by fejx** [comment]
What OS are you using?

Try disabling hardware acceleration by running vscode with `--disable-gpu` and see if the issue persists.

**Comment by donrafiki2918** [comment]
I use Windows 10 version 1909, and I will try that, Thank you!

**Comment by donrafiki2918** [comment]
That solved the issue, thank you!
What I did: 
Put '"disable-hardware-acceleration": true' in the json file searching "Preferences: Configure Runtime Arguments" with the command pallette.

**Comment by fejx** [comment]
Glad to hear it helped!

However, this is just a workaround, since hardware acceration is useful. You could try updating your display driver and see if you can re-enable hardware acceleration.

**Comment by donrafiki2918** [comment]
It's weird, as I update the drivers every two weeks. I'll check it out, thanks!

**Comment by fejx** [comment]
Then it is probably an issue with [Electron](https://github.com/electron/electron), which is doing the rendering in vscode.
