### ISSUE TITLE
New command: Recent File in workspace

### ISSUE THREAD

**Issue by fejx** [microsoft/vscode#98319]
I would like to have a new command that is similar to "File: Open Recent...", with two differences:
1. It should not list *any* recently openned file, but only files that have been openend in the *current workspace*.
2. When executing the command for a file, the file should open in the current window instead of a new window.

**Comment by bpasero** [comment]
That exists, everytime you run "Go to file", there is a list of editor history to the top.

**Comment by fejx** [comment]
While it's not *exactly* the same, it's close enough in most cases. Sorry for the trouble.
