### ISSUE TITLE
The .NET CLI tools cannot be located

### ISSUE THREAD

**Issue by Tobyee** [Microsoft/vscode#9831]
- VSCode Version: 1.3.1
- OS Version: Win7-x64
- dotnet Version: 1.0.0-beta-001598

Steps to Reproduce:

1. cmd: mkdir demo & cd demo
2. cmd: dotnet new
3. cmd: dotnet restore
4. cmd: code .

Error:

![image](https://cloud.githubusercontent.com/assets/1400574/17165279/e21fc9d8-5401-11e6-8b2c-8bd0b94d4628.png)

I'am sure that  .NET Core SDK for Windows was installed and `dotnet` command can be execute in `cmd`.

See alse:

https://github.com/dotnet/cli/issues/3858

**Comment by egamma** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#627
