### ISSUE TITLE
clang compiler error when building multiple files on macOS with tasks.json using wildcards

### ISSUE THREAD

**Issue by DmitrySumaneev** [microsoft/vscode#98313]
Issue Type: <b>Bug</b>

1. Configure tasks.json as described in Using Clang in Visual Studio Code guide https://code.visualstudio.com/docs/cpp/config-clang-mac
2. Add two ore more '.cpp' files to your workspace.
3. Change the "${file}" to "${workspaceFolder}/*.cpp" as suggested in the "Modifying tasks.json" section of the same guide.
4. Build your project.
5. You will get an error: "clang: error: no such file or directory: '${workspaceFolder}/*.cpp'"

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.61GB free)|
|Process Argv|-psn_0_2310708|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.5
gitlens|eam|10.2.1
vscode-edit-csv|jan|0.2.7
python|ms-|2020.5.80290
cmake-tools|ms-|1.4.0
cpptools|ms-|0.28.1
subtitles-editor|pep|1.0.4
vscode-xml|red|0.11.0

</details>

**Comment by kieferrm** [comment]
\extC++
