### ISSUE TITLE
Git Branch not accurate after refreshing code

### ISSUE THREAD

**Issue by jzombie** [microsoft/vscode#98326]
Issue Type: <b>Bug</b>

When changing git branch outside of VS Code, it doesn't reflect in VS Code's blue footer (bottom left) when refreshing the file tree.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:10:24.511Z)
OS version: Linux x64 5.4.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 3256)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.54GB (1.24GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by joaomoreno** [comment]
Does it reflect, once you focus VS Code?

**Comment by jzombie** [comment]
It never updates until I close VS Code and reopen it.

**Comment by jzombie** [comment]
Okay, so I just discovered that the issue only is present on an sshfs mounted location.  It works when focusing on a local location.

**Comment by joaomoreno** [comment]
Very likely there is no file watching over SSHFS.
