### ISSUE TITLE
Visual Studio Code - PS7 - Feature Req

### ISSUE THREAD

**Issue by bobmaars** [microsoft/vscode#98329]
I have recently started using Visual Studio Code for Powershell,. I'm not a stranger to This interface. I have also migrated off ISE. I love the way the workbench works. OK, enough of that...
For a very long time (since PS V1 was available), if there was a command you wanted to run and the module was not installed it has always been a headache to research and find the correct appropriate module and install it. 
I have a standard Checkpoint daily task that I have been running for years now. I know what module to install "manually", but is there a way to use a feature similar to Intellisense, lets say "IntelliFindMod" to locate and install when one gets a message for example:
Checkpoint-Computer -Description "MODIFY_SETTINGS" -RestorePointType MODIFY_SETTINGS
error: Checkpoint-Computer : The term 'Checkpoint-Computer' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again. 
Question is: Can one "Automate" or advise the user what the appropriate module is for that command to install? Similar to the Yellow light bulb one sees to correct an issue.  Would be nice...

Here are some tools I use to find the latest appropriate modules: (of course one does not need to install everything, but this is here for documentation purposes...)
Looking for Specific Module:  Microsoft.PowerShell.Management
Find-Module -Name * | Out-GridView   #Note: Takes a long time and there are hundreds... Choose wisely!
Get-Module -ListAvailable -All | Out-GridView
Find-Module -Name *CheckPoint* | Install-Module -Force -Verbose #(Example!)
Find-Module -Name * | Install-Module -Force -Verbose #(Nope not wise!)

**Comment by kieferrm** [comment]
\extPowershell
