### ISSUE TITLE
plot didn't show image

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [microsoft/vscode#98324]
Issue Type: <b>Bug</b>

```python
import numpy as np
from matplotlib import pyplot as plt
a=np.arange(0,10,0.1)
b=np.exp(a)
plt.plot(a,b,label="e^x")
plt.show()
print("hi")
```

"hi" was printed but plt.show didn't show the image.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.4.0-31-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|7.56GB (0.56GB free)|
|Process Argv|--no-sandbox --unity-launch /home/wuxinyu/桌面/python.code-workspace|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-django|bat|0.20.0
vscode-markdownlint|Dav|0.35.2
python-extension-pack|don|1.6.0
python-in-julia|hab|0.1.0
CppSnippets|har|0.0.14
language-julia|jul|0.15.32
kite|kit|0.114.0
MagicPython|mag|1.1.0
vscode-language-pack-zh-hans|MS-|1.45.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.5.80290
cpptools|ms-|0.28.1
vsnotes|pat|0.7.1
vscode-yaml|red|0.8.0
markdown-preview-enhanced|shd|0.5.8
vscode-markdown-paste-image|tel|0.12.3
python|tht|0.2.3
vscodeintellicode|Vis|1.2.7
jinja|who|0.0.8
markdown-all-in-one|yzh|2.8.0

</details>

**Comment by kieferrm** [comment]
\extPython

**Comment by Xinyu-Wu-0000** [comment]
I don't think it is caused by extension. You may check this [similar problem with julia language](https://github.com/julia-vscode/julia-vscode/issues/1229)
