### ISSUE TITLE
Add terminal colors to Monokai Dimmed theme

### ISSUE THREAD

**Issue by JanisGailis** [microsoft/vscode#98322]
I'd like to suggest an improvement to the Monokai Dimmed theme.

Monokai Dimmed doesn't have `terminal` colors set, resulting in 'ugly looking' fancy terminal features, such as Powerline. 

For a nice looking improvement, the terminal colors can be taken from the Monokai theme:

Before:
![monokai-dimmed-before](https://user-images.githubusercontent.com/9655353/82563027-fcf01b00-9b7e-11ea-82c2-f23dfc32ef87.png)
After:
![monokai-dimmed-after](https://user-images.githubusercontent.com/9655353/82563042-011c3880-9b7f-11ea-8320-c61daf00a700.png)

I intend to open a Pull request shortly that realizes this suggestion.

**Comment by misolori** [comment]
👍  This looks much better, thanks for the PR!

## Before
![image](https://user-images.githubusercontent.com/35271042/82948230-457c4f80-9f56-11ea-9ad5-45ec049f9495.png)

## After
![image](https://user-images.githubusercontent.com/35271042/82948240-48774000-9f56-11ea-9fc0-fcede49cf780.png)

**Comment by JanisGailis** [comment]
@misolori Thanks for accepting the PR!

As a side note, I quickly looked at the other themes, and many of them haven't set any terminal colors, and even the ones that have them set usually haven't aligned ANSI black with the background, leading to weird-looking 'fancy shell features':

![image](https://user-images.githubusercontent.com/9655353/82985408-a8282680-9ffc-11ea-8c35-125cea8371d0.png)

![image](https://user-images.githubusercontent.com/9655353/82985332-86c73a80-9ffc-11ea-9003-6280b5a36a16.png)

Then again, there are documented ways how to adjust the color palettes for a particular VSCode installation or workspace, and this is quite likely a bit of an edge case anyway.

Thanks for all the good work you guys have been doing!

**Comment by ejose19** [comment]
Is there an option to disable this? I prefer the non washed terminal and noticed this changed on last update.
