### ISSUE TITLE
Emmet multiplication adds line break inside last element and excludes it from Tab navigation

### ISSUE THREAD

**Issue by osharaki** [microsoft/vscode#98338]
Issue Type: <b>Bug</b>

1) Inside an HTML file, run *Emmet: wrap with abbreviation*.
2) Type ul>li*3
3) Enter

![2020-05-21 18-57-18_gif](https://user-images.githubusercontent.com/38385026/82585193-eacda700-9b95-11ea-8472-eec5161aa5e3.gif)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (1.02GB free)|
|Process Argv|-r .|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
dart-code|Dar|3.10.2
flutter|Dar|3.10.2
emoji-snippets|dev|1.5.3
code-runner|for|0.10.0
macros|ged|1.2.1
todo-tree|Gru|0.0.176
latex-workshop|Jam|8.9.0
Kotlin|mat|1.7.1
vscode-language-babel|mgm|0.0.27
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.5.80290
cpptools|ms-|0.28.1
autodocstring|njp|0.5.2
java|red|0.62.0
vscode-yaml|red|0.8.0
vscode-autohotkey|sle|0.2.2
vscode-hexdump|sle|1.7.2
open-in-browser|tec|2.0.0
cif|thi|0.2.1
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.1
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.22.4
vscode-maven|vsc|0.21.4

</details>

**Comment by rzhao271** [comment]
@osharaki considering that you're using "Wrap with Abbreviation" instead of "Expand Abbreviation" I'm wondering what output you're expecting?

**Comment by osharaki** [comment]
> @osharaki considering that you're using "Wrap with Abbreviation" instead of "Expand Abbreviation" I'm wondering what output you're expecting?

You're absolutely right. It seems I was using the wrong tool for the job. [Expand Abbreviation](https://docs.emmet.io/actions/expand-abbreviation/) does the trick!
