### ISSUE TITLE
Dissallow Chords for Integrated Terminal config option is ignored

### ISSUE THREAD

**Issue by K20shores** [microsoft/vscode#98336]
Issue Type: <b>Bug</b>

I have `"terminal.integrated.allowChords": false` in my settings.json file, but when I press ⌘-K, I still see the `(⌘-K) was pressed. Waiting for second key of chord...` text in the bottom ribbon.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.1
dotnet-test-explorer|for|0.7.1
vscode-nuget-package-manager|jmr|1.1.6
vscode-docker|ms-|1.2.0
csharp|ms-|1.21.18
python|ms-|2020.5.80290
cpptools|ms-|0.28.1
sublime-keybindings|ms-|4.0.7
vim|vsc|1.14.4

</details>

**Comment by K20shores** [comment]
Not sure if it's relevant and if the OS version above includes all the information you would need, but I'm running macOS Catalina, 10.15.4 (19E266).

**Comment by Tyriar** [comment]
This is by design, what the setting actually does is for any keystroke that would normally be routed to the terminal, check if it's a chord and skip the terminal if so. For cmd+k, this would never normally go to the terminal so it just gets handled by VS Code's regular keybinding system.
