### ISSUE TITLE
Text rendering and intellisense very slow

### ISSUE THREAD

**Issue by justinbak-wk** [microsoft/vscode#98339]
Issue Type: <b>Performance Issue</b>

Vscode is consistently slow to render what I type. When I'm typing the editor will spontaneously freeze and not display any intellisense suggestions or what I type. After a few seconds it races to catch up and render what I've typed and bring up intellisense

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   15	    82	   781	code main
    7	    49	   782	   gpu-process
    0	    16	   784	   utility
   37	    82	   816	   shared-process
    0	     0	 66169	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   426	 36069	   window (modal_store_test.dart — doc_plat_client)
    0	   590	 36087	     extensionHost
    0	  1786	 36110	       /usr/local/Cellar/dart/2.8.2/libexec/bin/dart /usr/local/Cellar/dart/2.8.2/libexec/bin/snapshots/analysis_server.dart.snapshot --client-id=VS-Code --client-version=3.10.2
    0	    16	 36089	     watcherService
    0	     0	 36579	     /bin/zsh -l
    0	     0	 43862	     /bin/zsh -l
    0	     0	 44093	     /bin/zsh -l
    3	    82	 66154	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (modal_store_test.dart — doc_plat_client)
|    Folder (doc_plat_client): more than 28179 files
|      File types: library(5594) dart(3185) go(2168) js(1097) map(1036)
|                  module(1034) dill(1033) raw(360) clean(270) wdesk(110)
|      Conf files: makefile(10) package.json(1);
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.10.2
gitlens|eam|10.2.1
vscode-github|Kni|0.30.3
git-graph|mhu|1.22.0
Go|ms-|0.14.2
vim|vsc|1.14.4

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Especially vim extension.

**Comment by justinbak-wk** [comment]
After disabling the Vim extension the problem *seems* to go away. Is there a reason the Vim extension is causing this behavior?

**Comment by mfmayer** [comment]
In my case text rendering (delay while typing) is slow as long as the outline is shown.

see also #98680

**Comment by alexdima** [comment]
Let's track in #75627 . It appears that there are known freezes caused by the dart extension which lead to typing via vim being blocked due to the two extensions sharing a single threaded runtime.
