### ISSUE TITLE
alt+shift doesn't work on mac

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#98337]
- Latest Insiders
- Use alt+shift+left/right arrow in a text input in the search viewlet or scm
- Nothing happens, it should select text by word

This is even when I have no keybindings or settings. @deepak1556 is it possible that this is related to Electron 8?

**Comment by roblourens** [comment]
Oh, I think this is due to `views.moveViewLeft` taking that shortcut. Edited the repro steps

**Comment by MrTravisB** [comment]
I updated earlier today and this broke for me as well. Then after about 30min it just started working again. I didn't restart or change any settings. 🤷
