### ISSUE TITLE
jump to definition doesn't open new panel

### ISSUE THREAD

**Issue by caibirdme** [Microsoft/vscode#9833]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:31:10.994Z)
- OS Version: Darwin x64 15.0.0

Steps to Reproduce:

1.`commad+click` to jump to the definition of a function
2.it will open a new panel show the the definition code.
3.repeat step 1 in the latest opened panel,it will not open another new panel and just replace the current one  thus I can not back to the previous panel.

**Comment by egamma** [comment]
@jireken this looks like a peek inside the peek scenario and the current behaviour is as designed, pls confirm.

**Comment by jrieken** [comment]
@caibirdme `Cmd+Click` doesn't open a new panel but navigates inside the panel, `Alt+Cmd+Click` open a new panel. Can you update your steps?

![jul-27-2016 09-14-42](https://cloud.githubusercontent.com/assets/1794099/17166987/9f826670-53da-11e6-963a-7a30c8cb2b7f.gif)

**Comment by caibirdme** [comment]
@egamma @jrieken I'm sorry I mistook panel as tab, I mean tab.
When `command+click` on a function it will jump to its definition in a new tab(tab2).And when I `command+click` in tab2,it won't open another new tab,just replace the file opened in tab2 .I cannot back to previous file now.

**Comment by jrieken** [comment]
That's actually the implemented behaviour. When the file is _already open_ in a sibling tab (that's the same pane/group/column) it will reuse that, otherwise it will replace the current editor with the target file. To get back to the previous location you can use the `Back`-command (<kbd>Ctrl+-</kbd>)

**Comment by caibirdme** [comment]
@jrieken Helped a lot!
Thanks for your reply
