### ISSUE TITLE
Con't disable formatter

### ISSUE THREAD

**Issue by uploy** [microsoft/vscode#98330]
Issue Type: <b>Bug</b>

```json
{
  "javascript.format.enable": false,
  "typescript.format.enable": false,
  "javascript.validate.enable": false,
  "flow.enabled": true,
  "editor.formatOnType": false,
  "editor.formatOnSave": false,
  "json.format.enable": false,
  "eslint.format.enable": false,
  "vetur.format.defaultFormatter.js": "none",
  "editor.defaultFormatter": null
}
```

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|16.00GB (3.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
code-gnu-global|aus|0.2.2
better-toml|bun|0.3.2
vscode-wasm|dts|1.3.1
vscode-optimize-images|fab|1.1.0
flow-for-vscode|flo|1.5.0
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.3
vscode-pull-request-github|Git|0.16.0
rest-client|hum|0.23.2
vscode-styled-components|jpo|0.0.29
git-graph|mhu|1.22.0
dotenv|mik|1.0.1
vscode-language-pack-zh-hans|MS-|1.45.1
cmake-tools|ms-|1.4.0
cpptools|ms-|0.28.1
Go|ms-|0.14.3
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-yaml|red|0.8.0
nunjucks|ron|0.3.0
rust|rus|0.7.8
code-settings-sync|Sha|3.4.3
vscode-scss-formatter|sib|2.0.1
code-spell-checker|str|1.9.0
sass-indented|syl|1.8.3
cmake|twx|0.0.17
vscode-lldb|vad|1.5.0
highlight-matching-tag|vin|0.9.9
vscodeintellicode|Vis|1.2.7
vscode-icons|vsc|10.1.1

</details>

**Comment by uploy** [comment]
> /needsMoreInfo

what information

**Comment by mxrachel** [comment]
A

> 
> 
> > /needsMoreInfo
> 
> what information

They need to know how this happens. Please read; [https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests](url)
