### ISSUE TITLE
Regions or Header Codefolding in JupyterLab?

### ISSUE THREAD

**Issue by Allenite** [microsoft/vscode#98334]
The improvements to JupyterLab in VS Code are very exciting.  It works almost the same, other than some keybindings which can, of course, be updated per user.

One thing that is missing that would make me use VS Code 100% for my jupyterlab notebooks is some type of code folding.  In JupyterLab, I use a Table Of Contents extension to allow code folding based on header tags 1-6.

In VS Code, it would be great to have similar functionality, but the more direct path would be to include some type of #region recognition, so we can use VSCode's built-in code folding capabilities for #region and #endregion.

**Comment by kieferrm** [comment]
\extPython
