### ISSUE TITLE
'x' button on search results moves around, too easy to click unintentionally

### ISSUE THREAD

**Issue by johndog** [microsoft/vscode#98342]
Issue Type: <b>Bug</b>

When doing a search in files, the 'x' button to delete a result only appears on items you point at with the mouse.  The 'x' button appears tightly at the end of search result text.  So if you point at a search result on the right side of that result, the 'x' button can easily appear right under the mouse, so a reflex click deletes the result instead of navigating to it.  You can actually click anywhere on a line _except_ the x button to navigate to that result, so the fact that the 'x' can pop up at any point on that line, and does so immediately before you can actually click, is almost a practical joke.  It's definitely red cape and bull material.

To fix, 'x' should only appear in a right-justified column, so it's in the same place on every line, and so that the user can use the mouse in the right half of the search window to scan and click without worrying about potentially closing an item instead of selecting it.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.19628

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (12.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
chronicler|arc|0.1.7
unique-lines|bib|1.0.0
vscode-markdownlint|Dav|0.35.2
gitlens|eam|10.2.1
code-runner|for|0.10.0
perl-outline|hit|0.0.6
vscode-edit-csv|jan|0.2.9
rainbow-csv|mec|1.7.0
devinsights|Mic|2020.5.7-2
vscode-nmake-tools|Mic|3.0.200420008
cpptools|ms-|0.28.1
powershell-preview|ms-|2020.5.0
show-offset|ram|0.0.4
rewrap|stk|1.10.1
code-spell-checker|str|1.9.0
line-erase-game|tai|0.5.2
vscode-markdown-paste-image|tel|0.12.3
indent-one-space|use|0.2.6
markdown-all-in-one|yzh|2.8.0

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by IllusionMH** [comment]
/question
Exactly for this case you can set `"search.actionsPosition": "right"`

**Comment by johndog** [comment]
This is not a question, this is a design bug.  vscode should not default to 'prankster' mode, and one should not have to turn it off.

**Comment by IllusionMH** [comment]
I guess that you'll need more than just 2 links in your follow up issue to convince change default:
Initial discussion to even have a setting #61532 and comments about separate PR that changes default to 'right' https://github.com/microsoft/vscode/pull/63457#discussion_r236527750

Good luck anyway.
