### ISSUE TITLE
An error occurred while trying to replace the existing file: DeleteFile failed; code 32.

### ISSUE THREAD

**Issue by hvilchez04** [microsoft/vscode#98344]
- VSCode Version: 1.44.2
- OS Version: Windows_NT x64 10.0.17763
- Electron: 7.1.11
- Chrome: 78.0.3904.130
- Node.js: 12.8.1

Steps to Reproduce:

1. Open VS Code

![image](https://user-images.githubusercontent.com/13105141/82590640-44fd4680-9b5b-11ea-9d78-ca4cba53bcd2.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
