### ISSUE TITLE
include function alternative to mark

### ISSUE THREAD

**Issue by maravento** [microsoft/vscode#98341]
I would like you to review the possibility of including vscode the specific selection of line blocks in a file (if you don't have it)
This function exists in other editors and is called "mark", in which a mark is made on one line of the file, then with "set mark" the other mark is established on another line in the file and the block is selected to do things how to copy, delete, etc.

regards

**Comment by alexdima** [comment]
I am quite happy to say that #95894 implements this.

**Comment by isidorn** [comment]
Exactly, closing as duplicate
@maravento you can check that issue how it works and you can try vscode insiders. We call it "set selection anchor"

**Comment by maravento** [comment]
Hopefully you will release this feature in the next update. I really appreciate your effort

**Comment by isidorn** [comment]
Yes, it will be part of the next release in 10 days.

**Comment by maravento** [comment]
Hi. You said that in 7 or 8 days they implemented the solution. Two months have passed and I don't see this change, or if you did you could tell where it is. Thanks in advance
