### ISSUE TITLE
click twice to open folder after start vscode

### ISSUE THREAD

**Issue by zuoez02** [Microsoft/vscode#9834]
- VSCode Version:  1.3.1
- OS Version: Ubuntu 14.04.3 LTS

Steps to Reproduce:

1. Start Vscode
2. Click File -> open folder in menu
3. Select a folder and click OK, but nothing happened.
4. Click File -> open folder again and select the same folder.
5. Open folder successfully.

I have installed vscode since version 0.9 and installed every released version until now. But the problem is still existed. I install newest version on another Ubuntu 14.04 but nothing wrong. I tried to reinstalled vscode but it was still existed. What should I do except reinstall my ubuntu system?

**Comment by Tyriar** [comment]
Can you check the console for errors? (Help > Toggle Developer Tools)

**Comment by zuoez02** [comment]
@Tyriar 
![screenshot from 2016-08-04 13 46 45](https://cloud.githubusercontent.com/assets/4801955/17391615/29014e14-5a4a-11e6-8f1d-9f8e7dd19f31.png)
Open vscode, log the first error.
Open a folder, log the second error.
Open the same folder agian, the vscode reload and no error

**Comment by zuoez02** [comment]
@Tyriar I remove the .config/Code folder and reopen the vscode, then problem resovled. Thank you for your help.

PS: Why I can open it at second time?

**Comment by Tyriar** [comment]
@zuoez02 looks like it happened as storage.json was not owned by your user. Removing `~/.config/Code` however is essentially clearing all the cache/settings for vscode so it's starting from a clean slate. @bpasero perhaps we could allow opening of folders even if storage.json get s a permission exception?

**Comment by bpasero** [comment]
We already catch this possible error when reading the `storage.json` and now we are doing the same when writing. The error is printed when verbose logging is enabled.
