### ISSUE TITLE
CSS Intellisense doesn't support the "color-scheme" css property.

### ISSUE THREAD

**Issue by sean89butler** [microsoft/vscode#98351]
Issue Type: <b>Bug</b>

Atempting to add the "color-scheme"  property to a CSS stylesheet returns "Unknown property: 'color-scheme'css(unknownProperties)". 

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1800X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (25.03GB free)|
|Process Argv|C:\Users\Sean Butler\Documents\GitHub\MaintenanceDispatch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
color-scheme-selector|hen|0.2.0
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
Depends on mdn/browser-compat-data to adopt this: https://github.com/mdn/browser-compat-data/issues/5825
