### ISSUE TITLE
search.actionsPosition should default to 'right'

### ISSUE THREAD

**Issue by johndog** [microsoft/vscode#98356]
Issue Type: <b>Bug</b>

Current default behavior of search results window, allowing the close button to bounce around, makes no sense.

See related:

- https://github.com/microsoft/vscode/issues/98342
- https://github.com/microsoft/vscode/issues/97593

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.19628

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (12.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
chronicler|arc|0.1.7
unique-lines|bib|1.0.0
vscode-markdownlint|Dav|0.35.2
gitlens|eam|10.2.1
code-runner|for|0.10.0
perl-outline|hit|0.0.6
vscode-edit-csv|jan|0.2.9
rainbow-csv|mec|1.7.0
devinsights|Mic|2020.5.7-2
vscode-nmake-tools|Mic|3.0.200420008
cpptools|ms-|0.28.1
powershell-preview|ms-|2020.5.0
show-offset|ram|0.0.4
rewrap|stk|1.10.1
code-spell-checker|str|1.9.0
line-erase-game|tai|0.5.2
vscode-markdown-paste-image|tel|0.12.3
indent-one-space|use|0.2.6
markdown-all-in-one|yzh|2.8.0

</details>

**Comment by roblourens** [comment]
Thanks for the issue, but I'm not interested in changing the default right now. The earlier discussions were linked in your first issue, and changing it will just disturb people who are used to the way it works now.
