### ISSUE TITLE
Multiple RenameProviders don't respect all possible PrepareRename handlers

### ISSUE THREAD

**Issue by NTaylorMullen** [microsoft/vscode#98352]
In Razor we have 2 sets of providers for renames.
1. To handle C#/HTML renames
2. To handle Razor intrinsic renames (such as Blazor component renames etc.)
 
In each of our cases our C#/HTML renames will return "cannot prepare rename" for pieces that our Razor language server **can** handle and vice versa. Therefore, because of this:

https://github.com/microsoft/vscode/blob/724c307bf35646ac549a8533a255c51b63fea5c7/src/vs/editor/contrib/rename/rename.ts#L54

Only the first RenameProvider's prepareRename is called and then the result is imposed on all other providers. Meaning when our C#/HTML rename provider says "sorry can't handle it" our Razor language server prepare rename is never called. One quirk is if our C#/HTML rename provider returns `null` then our Razor language server handler is called to rename the element but not its prepare.

The expected behavior would be for each prepareRename to be called and to then to do the actual rename operation only on those that returned a valid prepareRename responses.

/cc @jrieken  @dbaeumer

**Comment by jrieken** [comment]
We are pretty clear about this and it needs some thinking what it means if we change this now: https://github.com/microsoft/vscode/blob/68f2488cbcd9244d9b2942d40df78642f108a67b/src/vs/vscode.d.ts#L9747-L9749

Can't you handle this inside your extension?

**Comment by NTaylorMullen** [comment]
> Can't you handle this inside your extension?

We could but that would entail manually calling our other language server's rename endpoint and emulate the behavior of trying multiple rename providers.

You're right though, given the comment it does seem quite intentional. Why does it work this way though? It seems odd that you wouldn't support multiple rename providers. How it's designed currently is there can only ever be one true rename provider because you typically want to purposefully fail if you can't handle a rename so the user is not presented with the rename box in invalid locations.

**Comment by jrieken** [comment]
Yeah, this is mostly historical I guess. BUT having actually looked at the [implementation](https://github.com/microsoft/vscode/blob/724c307bf35646ac549a8533a255c51b63fea5c7/src/vs/editor/contrib/rename/rename.ts#L87) this should and does work. E.g this sample is happy

```ts
	vscode.languages.registerRenameProvider('plaintext', new class implements vscode.RenameProvider {
		provideRenameEdits(document: vscode.TextDocument, position: vscode.Position, newName: string, token: vscode.CancellationToken): vscode.ProviderResult<vscode.WorkspaceEdit> {
			let range = document.getWordRangeAtPosition(position);
			if (!range) {
				return;
			}
			console.log('HERE-1, GOOD')
			let edit = new vscode.WorkspaceEdit();
			edit.replace(document.uri, range, newName);
			return edit;
		}
	});

	vscode.languages.registerRenameProvider('plaintext', new class implements vscode.RenameProvider {
		provideRenameEdits(document: vscode.TextDocument, position: vscode.Position, newName: string, token: vscode.CancellationToken): vscode.ProviderResult<vscode.WorkspaceEdit> {
			console.log('HERE-2, BAD')
			return undefined; // works
			// return null; // works
			// throw new Error('boom') // works
		}
	});
``` 

The second provider is called first, then the upper one (which is doing the actual rename). 

<img width="791" alt="image" src="https://user-images.githubusercontent.com/1794099/82928411-7d00f100-9f82-11ea-8fde-21adb766585b.png">

So, I'd say that's good news but I don't know why it isn't working for you. @dbaeumer any chance that falsy results or errors aren't propagated correctly?

**Comment by NTaylorMullen** [comment]
@jrieken it's specifically the "prepare" operation which breaks the multiple provider scenario 😢

**Comment by NTaylorMullen** [comment]
For instance:
![JDeObrFf0m](https://user-images.githubusercontent.com/2008729/82948195-32697f80-9f56-11ea-97ab-69a9210409f7.gif)

Code:
```TypeScript
vscode.languages.registerRenameProvider('plaintext', new class implements vscode.RenameProvider {
	prepareRename(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken): vscode.ProviderResult<vscode.Range> {
		console.log('PREPARE CALLED');
		let range = document.getWordRangeAtPosition(position);
		return range;
	}

	provideRenameEdits(document: vscode.TextDocument, position: vscode.Position, newName: string, token: vscode.CancellationToken): vscode.ProviderResult<vscode.WorkspaceEdit> {
		console.log('Never called 1')
		return undefined;
	}
});

vscode.languages.registerRenameProvider('plaintext', new class implements vscode.RenameProvider {
	prepareRename(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken): vscode.ProviderResult<vscode.Range> {
		console.log('PREPARE THAT REJECTS WAS CALLED');
		return Promise.reject('Cannot rename this symbol2.');
	}
	provideRenameEdits(document: vscode.TextDocument, position: vscode.Position, newName: string, token: vscode.CancellationToken): vscode.ProviderResult<vscode.WorkspaceEdit> {
		console.log('Never called 2')
		return undefined;
	}
});
```

**Comment by jrieken** [comment]
Yeah... It's a little more tricky because when provider A defines the rename-range than provider B cannot redefine that (since the UI already shows...) But I can do this: try preparing with all providers and then start rename with the provider that defined the rename-range

**Comment by jrieken** [comment]
This should be good now. I have adjusted the jsdoc to the actual behaviour and also tweaked it so that prepare is called until having a good result

**Comment by jrieken** [comment]
fixed via fb3dc8be662b22054148544a6ccd4e5e2af52531 and da872de01154a0422c431e8632d1257a6f1cb753

**Comment by dbaeumer** [comment]
@jrieken cool!

**Comment by NTaylorMullen** [comment]
Thanks for pulling this together so quickly @jrieken!
