### ISSUE TITLE
Unable to post message from rendered HTML output to NotebookEditor

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#98353]
- VSCode Version:
- OS Version:

Steps to Reproduce:

Renderer:
```javascript
 {
 outputKind: CellOutputKind.Rich,
 data: {
	 data['text/html'] = `
		 <button onclick="myFunction()">Click me</button>
		 <script>
			 function myFunction() {
				 acquireVsCodeApi().postMessage({type:'Don', payload:'wow'});
			 }
		 </script>
		 `
	}
 };
```
 
Add event handler to receive messages:
```typescript
 notebook.activeNotebookEditor?.onDidReceiveMessage((e) => {
	 console.error('Callback not executed');
 });
```

Does this issue occur when all extensions are disabled?: N/A

@rebornix /cc

**Comment by rebornix** [comment]
cc @connor4312 as we are moving to new API for renderers in webview.

**Comment by connor4312** [comment]
I'm not sure why postMessage stopped working for you in the webview, but I am planning to change this.

Primarily, there's now the API `acquireNotebookRendererApi(rendererType)` API which exposes events and state scoped per the renderer. The returned object also has the `postMessage` key on it. I plan to introduce an optional `onDidReceiveMessage` method to the `NotebookOutputRenderer` which will receive messages sent from the webview.
