### ISSUE TITLE
Compare showing different is not working

### ISSUE THREAD

**Issue by kiatle** [microsoft/vscode#98359]
Issue Type: <b>Bug</b>

"Compare with" function is not working as before.
Both tab is not moving together and highlighting function is not exists anymore compared to previous updates.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.85GB (5.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.9.0
vscode-eslint|dba|2.1.5
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-close-tag|for|0.5.7
vscode-pull-request-github|Git|0.16.0
gc-excelviewer|Gra|2.1.34
todo-tree|Gru|0.0.176
compareit|in4|0.0.2
git-tree-compare|let|1.9.1
mssql|ms-|1.9.0
pdf|tom|0.6.0
gitflow|vec|1.2.1
html-css-class-completion|Zig|1.19.0

</details>

**Comment by kiatle** [comment]
![not working](https://user-images.githubusercontent.com/30194582/82628473-7f301c00-9c1f-11ea-8369-5104f73bbb2f.JPG)

**Comment by githubbert22** [comment]
i also have the same issue.

i'm trying to compare 2 html codes.
clicked "select for compare" 1 file then "compare with selected" on the other.

a tab is created where the two files are. i was expecting to see the difference between the 2 files, however there were no difference indication and can't be scrolled together.

**Comment by kiatle** [comment]
yes, probably we are facing this same issues. 


> 
> 
> i also have the same issue.
> 
> i'm trying to compare 2 html codes.
> clicked "select for compare" 1 file then "compare with selected" on the other.
> 
> a tab is created where the two files are. i was expecting to see the difference between the 2 files, however there were no difference indication and can't be scrolled together.

**Comment by kiatle** [comment]
> 
> 
> i also have the same issue.
> 
> i'm trying to compare 2 html codes.
> clicked "select for compare" 1 file then "compare with selected" on the other.
> 
> a tab is created where the two files are. i was expecting to see the difference between the 2 files, however there were no difference indication and can't be scrolled together.

yes, probably we are facing this same issue.

[Both tab is not scrolled together.zip](https://github.com/microsoft/vscode/files/4749321/Both.tab.is.not.scrolled.together.zip)

**Comment by kiatle** [comment]
> 
> 
> i also have the same issue.
> 
> i'm trying to compare 2 html codes.
> clicked "select for compare" 1 file then "compare with selected" on the other.
> 
> a tab is created where the two files are. i was expecting to see the difference between the 2 files, however there were no difference indication and can't be scrolled together.

yes, probably we are facing this same issue.

[Both tab are not scrolled together.zip](https://github.com/microsoft/vscode/files/4749325/Both.tab.are.not.scrolled.together.zip)

**Comment by GreyElec** [comment]
I have the same issue too, trying to compare some *.il file.
