### ISSUE TITLE
insider version download link messed up

### ISSUE THREAD

**Issue by sweettyler** [microsoft/vscode#98354]
just followed the link at https://code.visualstudio.com/insiders/ downloaded a linux64 version (code-insider-1590013558.tar.gz) and found it was built in April.

**Comment by sweettyler** [comment]
maybe the server got a problem.

**Comment by sweettyler** [comment]
the downloaded file was this one "code-insider-1590013558.tar.gz", not "code-insider-1589883424.tar.gz" which I mentioned previously.

**Comment by sweettyler** [comment]
actually none of downloaded versions work since then!

Very surprise nobody has taken a look yet!

**Comment by sweettyler** [comment]
"code-insider-1590013558.tar.gz" could show me it was built in April, however, after a few tries.
"code-insider-1590182860.tar.gz" could show me a blank window.
"code-insider-1589883424.tar.gz" is the last one that works.

**Comment by joaomoreno** [comment]
Can you still reproduce this? Works for me.

**Comment by sweettyler** [comment]
"code-insider-1590472730.tar.gz", which was built today, gives me a blank window.
back to normal after reinstalling "code-insider-1589883424.tar.gz".

BTW, is there any big change for the insider version?

**Comment by sweettyler** [comment]
I just tried with a fresh installation.  after deleting "~/.config/Code\ -\ Insiders/" and "~/.vscode-insiders", and the latest "code-insider-1590472730.tar.gz" doesn't work for me: it does pop a window with title "Welcome - Visual Studio Code - Inside (on xxxxx)" but the rest of the window are blank.

**Comment by sweettyler** [comment]
Now I think it's some changes in the code caused my problem. Please let me know what kind of information you need to know. The following is from "code-insider-1589883424.tar.gz" (the latest insider version works for me):

VS Code version: Code - Insiders 1.46.0-insider (da3bf754c3c0eabda1dc80ed9d627679ee560697, 2020-05-19T10:04:43.228Z)
OS version: Linux x64 3.10.0-693.17.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (32 x 2100)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 2, 2|
|Memory (System)|187.41GB (78.19GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.5.80290
cpptools|ms-|0.28.1


</details>

**Comment by joaomoreno** [comment]
> the latest insider version works for me

So it's all good now?

**Comment by sweettyler** [comment]
@joaomoreno It is a surprise that "code-insider-1590558881.tar.gz" (which I downloaded this morning) works!

What I said in my previous posts was that "code-insider-1589883424.tar.gz" was the only one worked for me.

BTW, what have you changed in "code-insider-1590558881.tar.gz" (what was the problem exactly)?

**Comment by joaomoreno** [comment]
> BTW, what have you changed in "code-insider-1590558881.tar.gz" (what was the problem exactly)?

A lot changes between versions, not sure what caused what you saw.

Thanks!
