### ISSUE TITLE
Network Issues with VS Code v1.45.1

### ISSUE THREAD

**Issue by geneus** [microsoft/vscode#98358]
Issue Type: <b>Bug</b>

Update to 1.45.1. Fails to connect to the network when checking for IDE or extension updates.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

**Comment by deepak1556** [comment]
Can you start with code with `--log-net-log=netlog.json` and perform network actions, attach the log here. Thanks!

Also attach the HAR file following

* Open devtools from the editor
* Try to install an extension from the marketplace/any other network actions with devtools open
* From the Network panel in devtools, use the Export HAR.. option and attach the .har file here.
