### ISSUE TITLE
Menu options [Source Action] Shortcut keys cannot be set. You must right-click to display the Source Action dialog box, which greatly affects development efficiency and usage habits. Hope to improve in time.

### ISSUE THREAD

**Issue by 395053994** [microsoft/vscode#98360]
- VSCode Version: 1.46
- OS Version: Win10
Menu options [Source Action] Shortcut keys cannot be set. You must right-click to display the Source Action dialog box, which greatly affects development efficiency and usage habits.
Hope to improve in time.
![ggggfgfgfg](https://user-images.githubusercontent.com/27546390/82628416-5dcf3000-9c1f-11ea-823c-015d32890c36.png)

**Comment by mjbvz** [comment]
The `editor.action.sourceAction` command is used for this. Try: 

```json
{
    "key": "ctrl+shift+s",
    "command": "editor.action.sourceAction"
  }
```

**Comment by 395053994** [comment]
thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Matt Bierner"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月27日(星期三) 凌晨4:17
收件人:&nbsp;"microsoft/vscode"<vscode@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vscode] Menu options [Source Action] Shortcut keys cannot be set. You must right-click to display the Source Action dialog box, which greatly affects development efficiency and usage habits. Hope to improve in time. (#98360)





 
The editor.action.sourceAction command is used for this. Try:
 {     "key": "ctrl+shift+s",     "command": "editor.action.sourceAction"   }
