### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by naffydharni006** [microsoft/vscode#98368]
Issue Type: <b>Bug</b>

Visual studio code isn't properly working. The extensons are workng. But, the options which are shown when we right a tag name s not shown. The auto enclose tag name in angular brackets is also not working. I have also tried switching the extensions on and off. Please resolve the issue.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:06.081Z)
OS version: Windows_NT ia32 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU  N3540  @ 2.16GHz (4 x 2167)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|2.89GB (0.20GB free)|
|Process Argv|C:\Users\Gurdeep Singh\Desktop\New folder (2)|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.20.0
npm-intellisense|chr|1.3.0
vscode-npm-script|eg2|0.3.11
auto-rename-tag|for|0.1.3
code-runner|for|0.10.0
HTMLHint|mka|0.7.0
python|ms-|2020.5.80290
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
atom-keybindings|ms-|3.0.8
cpptools|ms-|0.28.1
notepadplusplus-keybindings|ms-|1.0.5
debugger-for-chrome|msj|4.12.7
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.7
commandlist|yam|1.0.3

</details>

**Comment by ewerybody** [comment]
Hello Naffy! Welcome!
You were using the Issue Reporter tool in vscode directly huh?

Your issue **title** needs improvement! Try to come up with a short and descriptive title for the problem.
If you're having **multiple** issues: Open multiple reports. One for each problem.

Please do not ignore the **Steps to Reproduce**. Without them there will probably be no one helping you.

**Comment by mxrachel** [comment]
Hello @naffydharni006, In addition to what @ewerybody has said, please take some time and read [this guide](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests) on how to make a good bug report.

**Comment by naffydharni006** [comment]
I have now deleted VS Code because it was creating some issues with my PC

**Comment by ewerybody** [comment]
And because of this the issues are gone now, right? 😑

Ok. pardon me. I know you were trying to help.
