### ISSUE TITLE
Better JS refactoring

### ISSUE THREAD

**Issue by kaushalyap** [microsoft/vscode#98374]
Please provide better JavaScript refactoring capabilities. Current support is [pretty limited ](https://code.visualstudio.com/docs/editor/refactoring), users have to depend on third party extension like [JS Refactor](https://github.com/cmstead/js-refactor)

In comparison [WebStorm have better refactoring capabilities](https://www.jetbrains.com/help/webstorm/refactoring-source-code.html#ws_supported_refactorings).

Please look at following list of refactoring capabilities in order find what is missing in VS Code.

- https://github.com/cmstead/js-refactor#automated-refactorings
- https://www.jetbrains.com/help/webstorm/refactoring-source-code.html#ws_supported_refactoring

Side note: Please do not ignore JS users.

**Comment by mjbvz** [comment]
Please open specific issues for the refactorings you want to see supported
