### ISSUE TITLE
Search for directory and reveal in explorer

### ISSUE THREAD

**Issue by CallMeBW** [microsoft/vscode#98377]
I would love to search for directories and reveal them in the project explorer.
Right now, the CTRL+P search only finds files. It would be awesome to have any sub-directories appear as well. Is there a way to do this at the moment?

**Comment by kieferrm** [comment]
You can highlight/filter in the explorer today. However, this is not true for folder inside collapsed folders.

**Comment by isidorn** [comment]
This could be done by an extension, thus closing as extension candidate.
The extension could contribute a command which uses quick pick and then call revealInExplorer command
As for filter in the explorer for searching inside collapsed there is already a feature request for this.
