### ISSUE TITLE
Publishing extension became failed due to validation error

### ISSUE THREAD

**Issue by freedomhero** [microsoft/vscode#98375]
I've got an vscode extension successfully published and updated in market for several versions. 

But it became failed today, and the reason explained in the mail from marketplace was due to a validation error, which said 'the extension contains an entry which is unsafe for extraction' in detailed log.

The only changes in this version were just some adds and deletes in an existing file. So I don't know if it's a bug or what going wrong here?

Also, I posted the question [here](https://stackoverflow.com/questions/61953089/publishing-vscode-extension-failed-due-to-validation-error-contains-an-entry-w).

**Comment by fiveisprime** [comment]
Following up with the marketplace team. I'll update when I hear back.

**Comment by freedomhero** [comment]
@fiveisprime Thank you, and here's my extension: https://marketplace.visualstudio.com/items?itemName=bsv-scrypt.sCrypt&ssr=false#overview

**Comment by fiveisprime** [comment]
Please try your deployment again. It should be corrected now.

**Comment by freedomhero** [comment]
> Please try your deployment again. It should be corrected now.

It works!!! Thank you very much.
