### ISSUE TITLE
Open workspace keyboard shortcut

### ISSUE THREAD

**Issue by CozyPenguin** [microsoft/vscode#98382]
I think it would be nice to have a default keyboard shortcut to open a workspace using the explorer, similar to `Ctrl` + `K` `Ctrl` + `O` for opening folders. `Ctrl` + `Alt` + `O` is not occupied by default.

**Comment by NotWearingPants** [comment]
<kbd>Ctrl</kbd>+<kbd>O</kbd> does this, just select a `.code-workspace` file

**Comment by CozyPenguin** [comment]
For me, that just opens the workspace as a text file
