### ISSUE TITLE
Width text see picture

### ISSUE THREAD

**Issue by mac4kent** [microsoft/vscode#98397]
I already have set font size 36pt on Visual Studio Code.app for mac

Please fix width see picture
<img width="1500" alt="Screen Shot 2020-05-22 at 1 37 05 PM" src="https://user-images.githubusercontent.com/4253305/82708102-506f7100-9c32-11ea-9541-10b3568af3bf.png">

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Asuggest+label%3Aux

**Comment by mac4kent** [comment]
Allright I have low vision and I use UI enlarge of ACCESSIBILITY. 
When too small text hurt my eyes on focus.

**Comment by jrieken** [comment]
I understand that and what I said is that there is already an issue that discusses custom/better sizing of the suggest widget

**Comment by mac4kent** [comment]
goooooooooooood Thank you for explain me
