### ISSUE TITLE
workbench.editor.showTabs set to false in upgrade

### ISSUE THREAD

**Issue by Thomazella** [microsoft/vscode#98391]
This issue is mostly to talk about upgrade experience. My vscode started behaving as if workbench.editor.showTabs was false and it took me a few days to figure it out WHAT it was and set to true. Just had never touched this setting before. Maybe a new default was introduced?

- VSCode Version: 1.45.1
- OS Version: mac 10.14.6

Steps to Reproduce:

1. update to 1.45.1 or 1.45 from 1.44
2. workbench.editor.showTabs behaves as if false, but you never set it to false.

Does this issue occur when all extensions are disabled?: Yes

Setting the setting manually brings back old behavior (having `workbench.editor.showTabs: true`). Even after setting this to true in the settings UI it would NOT show up in my settings json. Kinda odd.

**Comment by bpasero** [comment]
We did not change this setting at all. I think you have issues with the settings file maybe, can you check the contents of the file has this entry and then check the settings editor?

**Comment by Thomazella** [comment]
ok, Could be a local issue, just wanted to document here with an issue just in case, thanks.

**Comment by pudgeball** [comment]
I just updated my VS Code insiders and had this same experience.  All of a sudden my tabs had disappeared and required me to turn on `workbench.editor.showTabs` "on" which did not update my settings.json.

Version: 1.46.0-insider
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-09T17:34:56.826Z (4 hrs ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
