### ISSUE TITLE
Shell Script parsing/highlighting fails to detect closing quotation marks in certain situations

### ISSUE THREAD

**Issue by champgm** [microsoft/vscode#98394]
- VSCode Version: 
```
Version: 1.46.0-insider
Commit: da98a19a5d6724367bd99c8ec3b8f55054be37d1
Date: 2020-05-20T23:28:34.587Z
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 18.7.0
```

- OS Version: 
```
macOS Mojave Version 10.14.6
CPUs | Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)
-- | --
GPU Status | 
2d_canvas: enabled
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
metal: disabled_off
multiple_raster_threads: enabled_on
oop_rasterization: disabled_off
opengl: enabled_on
protected_video_decode: unavailable_off
rasterization: enabled
skia_renderer: disabled_off_ok
video_decode: enabled
viz_display_compositor: enabled_on
webgl: enabled
webgl2: enabled
Load (avg) | 3, 3, 3
Memory (System) | 16.00GB (0.08GB free)
Process Argv | -psn_0_11553540
Screen Reader | no
VM | 0%
Extensions: none
```

Steps to Reproduce:

1. Create a file, `temp.sh`
2. Paste these contents:
```
#!/usr/bin/env bash
priority=5
random_priority=$((priority + $(python -S -c 'import random; print(random.randrange(3,10))')))
echo "Calculated a random priority: ${random_priority}"
'
echo "More stuff"
```
3. You should notice that line 4 is detected and colored by the editor as if it were still within a string. Once another single-quote is added (line 5) this "closes" that string and line 6 appears normal. This also works if you replace those single quotes with double quotes. 

Here is how it looks in vscode: 
![image](https://user-images.githubusercontent.com/2091382/82705299-6f2b3300-9c45-11ea-953d-42608919ee2a.png)

And this is what it looks like in Sublime Text, as an example:
![image](https://user-images.githubusercontent.com/2091382/82705339-7d794f00-9c45-11ea-859b-0ea85562233e.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Thanks for reporting this issue! This is an issue with the shell script grammar we use from https://github.com/atom/language-shellscript. However, they aren't maintaining the textmate grammar anymore. I'll leave this issue open so that if we ever switch to a different grammar I can address it.

**Comment by alexr00** [comment]
Linking and closing in favor of https://github.com/microsoft/vscode/issues/77675, which tracks considering a new shellscript grammar.
