### ISSUE TITLE
Extend the API to add custom file opener

### ISSUE THREAD

**Issue by iamolivinius** [Microsoft/vscode#9839]
I wanted to port the [pdf-view](https://github.com/izuzak/atom-pdf-view) extension for atom to vscode.

One thing that I came across that I don't know how to do it in vscode is atom's ability to add custom file openers: https://atom.io/docs/api/v1.8.0/Workspace#instance-addOpener

I'm pretty new to vscode so correct me if I'm wrong but without such API one would have to take a detour through the command palette to open a PDF file with pdfjs and the intuitive way via "Open File..." and (double) clicking on the file tree wouldn't work.

**Comment by kieferrm** [comment]
Yes, you would have to go through the command pallet.

**Comment by jrieken** [comment]
Also, you can now add commands to the context menu like the markdown extension [does](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/package.json#L90)
