### ISSUE TITLE
Surprising & non-discoverable behavior regarding snippet suggestions

### ISSUE THREAD

**Issue by TheJCAB** [microsoft/vscode#98392]
- VSCode Version: 1.45.1
- OS Version: Windows 10.0.18363

Note: I open this as a bug. Might be a suggestion, but it's not for a new feature, but rather for a design rethink/discussion/adjustment. So there it is.

Before listing the repro, I have to say that I wasn't even aware of the whole "snippets" feature of VSCode until they started "messing with my finger memory", so to speak. One day, I suddenly started getting code generated for me as I typed, and I had no idea where it came from, or why. I usually would see it after typing (without looking at the screen) a ways past the point where the snippet was generated, so the end result was quite hilarious. My first attempts to find a disable flag in the settings page came up empty. I was looking for auto-formatting settings (which I had already disabled). I eventually tried to repro it more carefully, actually looking at the screen (the suggestions pop-up) and saw where it said "snippet", and that's how I found it.

Steps to Reproduce:

1. Start with snippet settings set to "inline" and ON. I write C++ code, so I get them from ms-vscode.cpptools (currently 0.28.1).
2. On a C++ file, type "struct", select the "struct" snippet in the suggestions popup, and then <ENTER>. It generates a name (from the filename), braces and a comment in the body.
3. In settings, disable snippets. For instance, on editor.suggest.showSnippets, and then try doing step 2 again.
4. This time there's no "struct" snippet offered. As expected. Use the "c++ keyword" suggestion instead.
5. Turn snippet suggestions on again (undo step 3), and then try doing step 2 yet again.
6. This time, the snippet suggestion is... not there. That can be extremely surprising. I mean... we re-enabled it, right!?

The reveal: the snippet is there. Scrolling up in the suggestions popup (pressing the UP arrow) will reveal it. If you select it and then try step 2 from scratch _all over again_ the snippet will be back as the "default".

In order tor repro properly, you'd need to make sure that the suggestions popup has many suggestions. I normally get dozens or hundreds, as intellisense works properly less often than not (but that's a separate issue).

The fact that it was hidden tells me a likely reason (I'll never know for sure) why I hadn't noticed the existence of snippets in months of using VSCode. It was there... but hidden. At some point I must have hit the UP arrow then ENTER, or something like that, making it the default.

Summary/suggestions:
- This behavior is surprising, and when things like this happen it can be difficult (and frankly annoying) to find the correct setting that matches the behavior and can correct it.
- It would be great if the VSCode developers could ponder on this a bit. Options that come to mind:
    - Offer a "master switchboard" settings page to turn entire feature-sets on or off, without the noise of having every little setting all together in one page.
    - Consider having whole feature-sets off by default. Especially those that can affect or disrupt normal text-typing activities. This is supposed to be a text editor at its core, after all.
    - Consider having, by default, all popups _not_ use any "natural" text-editing keys, like ENTER, and navigation arrows. Function keys and the like would be fine (although, I admit, perhaps awkward). This way, you wouldn't be able to activate auto-editing functions just by typing.
    - Maybe not having that by default, but as a nice, big, button in the master setting page I suggest above.

Does this issue occur when all extensions are disabled?: Yes/No
I didn't bother. Depends on extensions (I think) and it's more of a design issue in VSCode itself.

**Comment by jrieken** [comment]
This is controlled via the `editor.suggestSelection` setting. By default, it remembers the last selected suggestion so that you don't always have to arrow up/down. What you want is the `first` options of that setting
