### ISSUE TITLE
Evaluate in debug console keyboard shortcut

### ISSUE THREAD

**Issue by romainmartinez** [microsoft/vscode#98390]
A command widely used when debugging code is to evaluate a selection in the debug console.

There is an option to do this in vscode:
![Screenshot from 2020-05-22 14-22-10](https://user-images.githubusercontent.com/17710617/82697859-bad6e000-9c37-11ea-970e-36babec72993.png)

Using Auto completion in the `settings.json`, I couldn't find the keyboard shortcut for this action.

Would it be possible to add it?

**Comment by ArturoDent** [comment]
The command `Evaluate in Debug Console` is listed in the `Keyboard Shortcuts` - which is where you should look for commands and their keybindings, if any.

There is no default keybinding for that command.  You can set your own in the Keyboard Shortcut panel after you search for the command.  Click the `+` button to the command's left.

**Comment by romainmartinez** [comment]
You are absolutely right, thank you for the information. Sorry as I searched directly in the `json`.

The corresponding field is `editor.debug.action.selectionToRepl`.

Closing.
