### ISSUE TITLE
${relativeFile} not relative to workspace folder when symlinked

### ISSUE THREAD

**Issue by Xunnamius** [microsoft/vscode#98398]
- VSCode Version: 1.45.1
- OS Version: Linux x64 5.3.0-51-generic (Kubuntu 20.04)

Steps to Reproduce:

1. Symlink `~/repos`, a directory of repositories, to `/repos` on the root filesystem
2. Open `/repos/project1` TypeScript project in Code as root workspace. The directory has at least the following structure:
```
.
├── .vscode/
│   ├── launch.json
├── lib/
│   ├── index.test.ts
│   ├── index.ts
```
3. Add the following configuration to `.vscode/launch.json` based on the [jest debugging recipe at microsoft/vscode-recipes](https://github.com/microsoft/vscode-recipes/blob/master/debugging-jest-tests/.vscode/launch.json):
```JSON
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "name": "jest (all)",
            "request": "launch",
            "args": [
                "--runInBand"
            ],
            "cwd": "${workspaceFolder}",
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "disableOptimisticBPs": true,
            "program": "${workspaceFolder}/node_modules/jest/bin/jest"
        },
        {
            "type": "node",
            "name": "jest (current file)",
            "request": "launch",
            "args": [
                "--runInBand",
                "${relativeFile}"
            ],
            "cwd": "${workspaceFolder}",
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "disableOptimisticBPs": true,
            "program": "${workspaceFolder}/node_modules/jest/bin/jest"
        }
    ]
}
```
4. Navigate to `lib/index.test.ts` file in Code
5. Start `jest (current file)` in Code's debug view

Expected Behavior (Jest works properly): 

Code executes `cd /repos/project1 ; /usr/bin/node --inspect-brk=40687 /repos/project1/node_modules/jest/bin/jest.js lib/index.test.ts`

Actual Behavior (breaks Jest):

Code executes `cd /repos/project1 ; /usr/bin/node --inspect-brk=40687 /repos/project1/node_modules/jest/bin/jest.js ../../home/$USER/repos/project1/lib/index.test.ts`

This behavior does not seem to comport with how `${relativeFile}` (and also `${workspaceFolder}`) is described in [the documentation](https://code.visualstudio.com/docs/editor/variables-reference).

Does this issue occur when all extensions are disabled?: Yes

**Comment by Xunnamius** [comment]
Update: I noticed this path problem pop up in various places after accessing my project via the `/repos` symlink. For instance, when trying to use the debugger, breakpoints weren't being picked up. Seems to be because I'm making breakpoints in the `/repos/project1/lib/index.test.ts` file while Code is expecting the node inspector to understand `/home/$USER/repos/project1/lib/index.test.ts`. I noticed this after adding a `debugger;` line to my jest test and seeing what file popped up.

I was eventually able to fix this by bind mounting my repository directory to `/repos` instead of symlinking it. `${relativeFile} now returns the expected value.

**Comment by isidorn** [comment]
As this is configuration resovling assigning also to @alexr00 and unassigning myself.

**Comment by alexr00** [comment]
@Xunnamius I can't get the same behavior to happen. 
1. Make symlink: `sudo ln -s /home/alex/repos /repos`
2. Open the /repos/simpleTest in VS Code
3. Have this simple launch.json that should repro your behavior:
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch test",
			"request": "launch",
			"type": "node",
			"cwd": "${workspaceFolder}",
			"program": "${workspaceFolder}/${relativeFile}"
		}
	]
}
```
4. Have a /repos/simpleTest/test.js:
```javascript
console.log('hello!');
```
5. Run launch.
Output: 
```
/usr/bin/node --inspect-brk=8654 /repos/simpleTest/test.js 
Debugger listening on ws://127.0.0.1:8654/5bb3265b-40a1-4406-8cde-e855bafc2da2
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
hello!
```

If you use my simple repro do you still see the issue?

**Comment by Xunnamius** [comment]
@alexr00 I will test this out tonight and get back to you
