### ISSUE TITLE
tsd for lodash and underscore stopped working

### ISSUE THREAD

**Issue by lukasz-wronski** [Microsoft/vscode#984]
When I'm installing tsd for underscore or lodash Visual Sudio Code sees the variable that I'm assigning the module to as it is of type any. It correctly interprets it's members parameters, but does not see the members of fist level. Example: 

![problem example](http://i.imgur.com/DNkewKs.gif)

I'm installing my tsd with `tsd install lodash` or `tsd install underscore` command. It works correctly for other libraries like colors or node itself. It just have a problem with those two.

What I found also is that when I open definition file it shows some errors in it.

![errors](http://i.imgur.com/qZoi8VQ.png)

I would not suspect Visual Studio Code if there will be problem with only one of those libraries, but this is not looking like a coincidence.

**Comment by jrieken** [comment]
We have moved to project Salsa for JavaScript and this shouldn't happen anymore.
