### ISSUE TITLE
Unable to Install C# Extension

### ISSUE THREAD

**Issue by sebasijan** [Microsoft/vscode#9840]
- VSCode Version:     **1.2.0**
- OS Version:             **Windows 7 Professional Service Pack 1**

Steps to Reproduce:

1.  Use `ctrl` + `shit` + `p` and type "install".
2.  When the list of available extensions appear, install any extension - this works fine.
3. Now, try the same, but try installing **C# for Visual Studio Code (powered by OmniSharp)**
4. VSCode attempts to install the extension, but after some time (about 30 seconds to a minute) this error appears: 

> Server returned 404

After this message appears, VSCode still looks like it is trying to install something in the bottom left corner. 

**Extra Details:**
I have the following settings in my settings.json file: 

    // Place your settings in this file to overwrite the default settings
    {
        "http.proxyStrictSSL": false,
        "git.autofetch": false
    }

As I was not able to install any extensions before adding `"http.proxyStrictSSL": false`.
When I remove this line from my settings, I am again no longer able to search for extensions with this message: 

> Error unable to get local issuer certificate

**Comment by joaomoreno** [comment]
Can you reproduce with the latest stable (1.3.1) or latest insider release?

**Comment by sebasijan** [comment]
@joaomoreno  After downloading and installing VSCode 1.3.1 I was able to download the C# extension without any issues
