### ISSUE TITLE
Opening files from command line got very slow very recently

### ISSUE THREAD

**Issue by nguerrera** [microsoft/vscode#98400]
Issue Type: <b>Bug</b>

I'm not sure when it started happening, but it was within the last few days so I think there's a recent regression.

### Steps to reproduce

1. Start VS Code Insiders as usual
2. Run `code-insiders <any file>` on the command line

### Expected behavior

VS Code opens the file and takes focus relatively quickly

### Actual behavior

It takes five or six seconds before VS code has focus with the file open and I can begin to type.

### Notes

* The problem reproduces with all extensions disabled (replacing step 1 with `code-insiders --disable-extensions`)
* It does not reproduce with the stable version of VS Code
* Everything else is performing fine. If I open files from the explorer, it's as instant as ever.
* I tried profiling from developer tools. It doesn't appear to be registering any work during the long delay:

[Profile-20200522T144153.zip](https://github.com/microsoft/vscode/files/4670532/Profile-20200522T144153.zip)

![profile](https://user-images.githubusercontent.com/75470/82711686-f7580b00-9c3a-11ea-8994-d1a79ad9a627.gif)

VS Code version: Code - Insiders 1.46.0-insider (da98a19a5d6724367bd99c8ec3b8f55054be37d1, 2020-05-20T22:21:02.272Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 1950X 16-Core Processor  (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.88GB (120.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
macros|ctf|0.0.4
vscode-eslint|dba|2.1.5
EditorConfig|Edi|0.15.0
vscode-pull-request-github|Git|0.16.1
vscode-test-explorer|hbe|2.18.1
Lisp|mat|0.1.10
csharp|ms-|1.21.18
remote-wsl|ms-|0.44.2
vsliveshare|ms-|1.0.2236
debugger-for-edge|msj|1.0.14
material-icon-theme|PKi|4.1.0
toggle|reb|0.0.1
vscode-yaml|red|0.8.0
gitconfig|sid|2.0.1
rewrap|stk|1.10.1
emacs-mcx|tut|0.19.6
vscodeintellicode|Vis|1.2.7

</details>

**Comment by nickcoad** [comment]
I don't have anything to add to your very thorough report, other than I've also experienced this on the latest Code Insiders so it's not just you. I'm also not quite sure when it started but it was only the last couple of days max.

**Comment by eamodio** [comment]
See #97638

**Comment by nguerrera** [comment]
I'm now seeing extreme lag when typing too, not sure if it's the same root cause. Let me know if there's any details I can share to help determine that.

**Comment by nguerrera** [comment]
Got an update and this no longer repros. Still having some lagging typing, but I suspect that's altogether separate. I will file something else if it persists.

**Comment by deepak1556** [comment]
@nguerrera the slowdown was seen with an electron update, we reverted it temporarily. The underlying issue has not been fixed yet. I am reopening to investigate.
