### ISSUE TITLE
code -n stopped working 

### ISSUE THREAD

**Issue by tlemo** [microsoft/vscode#98403]
Issue Type: <b>Bug</b>

Repro:
```
1. Open <folder path> in code
2. code -n <folder path>
```

Expected: force a new code window to be created even if there's an existing window.

Actual: the existing code window is used.

This is a recent regression. Not sure when exactly started, but in 1.45.1 code -n does not force a new window to be opened.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 4.15.0-101-generic

**Comment by bpasero** [comment]
I cannot reproduce. 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by tlemo** [comment]
Sorry, an important part of the repro steps was lost in the description formatting (fixed): the issue happens when opening folders. Opening a file with -n works (it will open a new window)

```
code -n foo.cpp
code -n foo.cpp
```

But opening a folder with -n does not:

```
code -n folder
code -n folder
```

I can reproduce this on Windows 10 and Ubuntu 18.04 and 20.04. For what is worth, it reproduces with `--disable-extensions` as well.
