### ISSUE TITLE
There is more than one git project in Scm view

### ISSUE THREAD

**Issue by yzpTsubasa** [microsoft/vscode#98416]
Open a git project in VSCode, and open another git project in a new window.
Then there is more than one git project in Scm view, that makes me confused
![Snipaste_2020-05-23_11-15-59](https://user-images.githubusercontent.com/6694440/82720502-cc2af580-9ce6-11ea-9128-537840d1ae95.png)

**Comment by joaomoreno** [comment]
Maybe one is inside the other? Please search for SCM/Git settings to disable automatic discovery.
