### ISSUE TITLE
Search results UI does not respect results reported from custom TextSearchProvider

### ISSUE THREAD

**Issue by APLmath** [microsoft/vscode#98413]
- VSCode Version: 1.45.1, and 1.46.0-insider
- OS Version: macOS 10.14.6 (18G103)

Steps to Reproduce:

1. Launch VS Code (or Insiders) with `--enable-proposed-api APLmath.sample-fs-and-search-repro`
2. Install this sample extension, which implements a custom `TextSearchProvider`: https://github.com/APLmath/sample-fs-and-search-repro/releases/tag/v0.0.1
3. Open this workspace: [sample-workspace.code-workspace](https://github.com/APLmath/sample-fs-and-search-repro/blob/master/sample-workspace.code-workspace)
4. In the output console, select "SuperSimpleStringSystemProvider" to see the results that are being reported for each search. Each [result printed corresponds to an instance](https://github.com/APLmath/sample-fs-and-search-repro/blob/24d2631d6e96e8bbd93f5917daa15a8f0064a5b3/src/SuperSimpleStringSystemProvider.ts#L259-L260) of calling [`progress.report`](https://github.com/microsoft/vscode/blob/a1ed386162d6a5741ed440c6b8998ca5728a89f8/src/vs/vscode.proposed.d.ts#L625) from the `TextSearchProvider` API.
5. Try doing a search for "to hello"

Notice that in the output console, there are supposed to be 5 results, but only 3 are shown in the search results UI:

<img width="926" alt="inconsistent-search-results" src="https://user-images.githubusercontent.com/1169103/82719500-e8378400-9c5f-11ea-8449-a73f0b7802bc.png">

Additionally, after some time, all the results disappear.

Does this issue occur when all extensions are disabled?: No

I did some initial digging, and it seems like it has to do with some search models being cached, and those models assume that searches were being done in a regex style.

**Comment by roblourens** [comment]
Thanks for the report, but you should know that this API is not on the fast track to stabilization. I don't know when I will have time to pick it up again. Out of curiosity, can you tell me about what you want to use it for?

**Comment by APLmath** [comment]
I'm building an extension to display and search Azure DevOps git repos in VS Code. It's basically implementing `FileSystemProvider` and `TextSearchProvider` with a custom URI scheme to talk to the Azure DevOps [REST endpoints](https://docs.microsoft.com/en-us/rest/api/azure/devops/search/code%20search%20results/fetch%20code%20search%20results?view=azure-devops-rest-5.1). The `FileSystemProvider` part works fine, but `TextSearchProvider` is where I was running into issues.

In Azure DevOps code search, you can add semantic filters like "def:FunctionName" (to filter down to where FunctionName is defined), or "ext:cpp" (to limit to files where the extension is "cpp"): https://docs.microsoft.com/en-us/azure/devops/project/search/code-search?view=azure-devops

I want to be able to use the same search queries when doing a search in VS Code within the custom file system. For example, "def:foo". From my own investigation, it seems like some parts of VS Code assume the search query is a grep-like search, and would populate some search results based on trying to search for instances of the string "def:foo" in the files (which there aren't any), rather than using the results reported within `provideTextSearchResults`.

**Comment by gjsjohnmurray** [comment]
I am alsa longing for `TextSearchProvider` to be finalized. I work with a set of software platforms (InterSystems) in which the sources can be surfaced in VS Code via `FileSystemProvider`

**Comment by roblourens** [comment]
Closing this in favor of the main API issue
