### ISSUE TITLE
Broken font fallback implementation in UI

### ISSUE THREAD

**Issue by chinnnki** [microsoft/vscode#98419]
Issue Type: <b>Bug</b>

In some areas of VS Code’s user interface, like title bar, explorer, breadcrumbs, find/replace boxes, tabs, etc., Simplified Chinese characters are shown as tofus. Improvement is needed.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<img width="868" alt="スクリーンショット 2020-05-23 15 19 37" src="https://user-images.githubusercontent.com/12984268/82723430-cc88b800-9d09-11ea-9d68-b5f15f8896f8.png">

**Comment by rebornix** [comment]
@chinnnki may I ask what's the font you are using?

**Comment by chinnnki** [comment]
> @chinnnki may I ask what's the font you are using?

If you’re referring to the font I set for the editor, it’s probably not relevant to the issue here. It’s just the system font that is used in the UI.

**Comment by rebornix** [comment]
@chinnnki can you provide some sample text which leads to this issue?

**Comment by chinnnki** [comment]
> @chinnnki can you provide some sample text which leads to this issue?

The text I used for the file in the screenshot was “测试用文件”.

**Comment by rebornix** [comment]
I can't reproduce this issue. Can you try our Insiders to see if you are still seeing the same problem https://code.visualstudio.com/insiders/ ?

**Comment by chinnnki** [comment]
> I can't reproduce this issue. Can you try our Insiders to see if you are still seeing the same problem https://code.visualstudio.com/insiders/ ?

Just upgraded vscode to 1.46.1 and macOS to 11 beta, and it seems that the issue is gone. Don’t know which one of them fixed it though. Thank you for the help.
