### ISSUE TITLE
Set *.code-workspace file type associations and icons for linux/gnome desktop

### ISSUE THREAD

**Issue by arterrey** [microsoft/vscode#98417]
In Linux/Gnome desktop environments - Integrate opening vscode work spaces by implementing a file type icon and setting gnome configuration so that vscode is the default application when double clicking on the workspace file from the file browser.

**Motivation**

So that users who use of the file browser may be able to directly recognize vs code workspaces in folders and quickly open the workspaces.

**Comment by bpasero** [comment]
Looks like https://github.com/microsoft/vscode/pull/95637 does this.
