### ISSUE TITLE
VS Code Update fails and rendered unlaunchable

### ISSUE THREAD

**Issue by LightCC** [microsoft/vscode#98415]
Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Install VS Code, Windows 64-bit System install
2. After an update is available, attempt to update (either let VS Code install in-place, or close everything, download separately and install overtop of the current install)
3. Install will fail attempting to install code.exe file in c:\Program Files folder hierarchy. I think it was code 183, permission failure attempting to move a file (or something like that).
    * If you hit "retry" it fails
    * If you hit "Ignore" other files fail with the same problem later on.
4. After install attempt, Code will no longer run
5. Download latest code install (system, Windows 64-bit) from VS Code web site. Reattempt install. Same failure occurs.
6. Reboot PC. Before running anything else, Install Code from setup file already downloaded. This time it will succeed and work.

Note: This has been happening for a while now - maybe the last 6 or so installs, and I believe it has happened on both my Windows 7 laptop at work and my Windows 10 workstation there as well. I'm not 100% positive it's happened on both or every time, but it's very regular on my home Windows 10 PC.

Does this issue occur when all extensions are disabled?: Yes/No

* Not Tested with extensions disabled

**Comment by joaomoreno** [comment]
Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.
