### ISSUE TITLE
Visual Studio Code cannot be opened because of a problem.

### ISSUE THREAD

**Issue by EmmaN95** [microsoft/vscode#98427]
Ive updated my system but the application wont open.

<img width="433" alt="Screenshot 2020-05-23 at 13 11 56" src="https://user-images.githubusercontent.com/60002871/82730402-2f248880-9cf7-11ea-83ee-257207f77278.png">

- VSCode Version:  VSCode 1.45 stable
- OS Version: macOS Catalina 10.15.4

**Comment by joaomoreno** [comment]
Can you completely reinstall VS Code?
