### ISSUE TITLE
Can't see the left action bar icons

### ISSUE THREAD

**Issue by Kirajav** [microsoft/vscode#98420]
Issue Type: <b>Bug</b>

Every time i open VSCode application, the left side action bar doesn't show extensions' icons already installed, but the default ones shows correctly.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (7.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|31%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.5.80290
cpptools|ms-|0.28.1
vsliveshare|ms-|1.0.2236
platformio-ide|pla|1.10.0
LiveServer|rit|5.6.1
powerquerymlanguage|sea|1.0.0
vscode-icons|vsc|10.1.1

</details>

**Comment by gjsjohnmurray** [comment]
Please disable one extension at a time, restart VS Code each time, and see if the problem is caused by one of them.

**Comment by Kirajav** [comment]
Oh! thanks for answer me.
I've already uninstalled every extension but just left "Live Share" extension installed, but nothing happens, the problem persist. In fact, I did a full clean uninstallation and then i reinstalled it.

**Comment by gjsjohnmurray** [comment]
Sounds like a problem with that extension then.

**Comment by Kirajav** [comment]
Nope, it obviously happens with wherever extension is installed and activated (the ones that install an icon in the side bar). For example, If i install just one extension such as "Platform IO" or "Github" (just for demostration) it just shows invisible icons (by the way, the icons in side bar are all enabled in the right click menu).

So, i've been googling this issue for almost 1 and a half year (yeah, i got this problem almost 2 years ago 'cause it was not annoying until now that I use VSCode as ma' main supa dupah code and files editor) and i found some other github posts like:

[https://github.com/microsoft/vscode-remote-release/issues/687](url)
[https://github.com/microsoft/vscode-remote-release/issues/966](url)

But those issues are related to a previous versions of VSCode or in a previously called "insider version", (My version is 1.45.1 it has just been downloaded and installed in a clean way).

**Comment by gjsjohnmurray** [comment]
Please follow the steps at https://github.com/microsoft/vscode/issues/97851#issuecomment-629267868

Maybe they will show some requests failing. Perhaps you are behind a firewall or proxy that needs to whitelist some domains.

**Comment by Kirajav** [comment]
Thanks for the response, i've checked the steps in that post, so, i could see that maybe the problem is the icons (.svg) are not recognizable by VSCode (Look the image that diplays in the preview section): 

![VSCode icons problem](https://user-images.githubusercontent.com/7090756/82744247-4b4a1900-9d3b-11ea-926b-d267326c94c8.PNG)

By the way, i haven't a proxy or a DNS problem, my DNS are the 1.1.1.1 and 1.0.0.1 for my entire home network and can access perfectly to the link: [Python icon](https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default) that the post suggest.

**Comment by Kirajav** [comment]
I've also checked the icons' location and the archives exist correctly, but i can't open anyone 'cause i don't have the correct program to open it (.svg). i can open it only with notepad.
![icon location vscode](https://user-images.githubusercontent.com/7090756/82744429-19868180-9d3e-11ea-803b-2472d0d3a243.jpg)

**Comment by Kirajav** [comment]
so... any suggestions?

**Comment by gjsjohnmurray** [comment]
Perhaps a duplicate of #92323

**Comment by Kirajav** [comment]
Yes, yes, yes!, omg thankyou so much! it helps me a lot. I did the steps as the post says: 

> just delete all values in: 
> `\HKEY_CLASSES_ROOT\.svg` with the register editor (regedit)

but not `\HKEY_CLASSES_ROOT\.svg\OpenWithProgids` folder and any values in it. 
Seems like a program i installed in my pc called "ConceptDraw" caused the issue. So, you have freed me from long suffering (almost 2 years, lol).

Thankyou again!.
