### ISSUE TITLE
Cascading .vscode directory

### ISSUE THREAD

**Issue by gbmajaco** [Microsoft/vscode#9842]
```
root
+-- projects
|    +-- .vscode
|        +-- settings.json
|    +-- project-a
|        +-- .vscode
|            +-- settings.json
|        +-- foo
|        +-- bar
|    +-- project-b
+-- work-projects
|    +-- project-foo
```

#### Expected results:

`~/projects/project-a/foo` & `~/projects/project-a/bar` are both affected by `~/projects/project-a/.vscode` > `~/projects/.vscode` > `defaults`

`~/projects/project-b` is however only affected by `~/projects/.vscode` > `defaults`

finally all projects in `~/work-projects` are only affected by the editor `defaults`

#### Use case:
My use case is that all repos in `~/projects/project-a` have a similar eslint setup that forces me to use `options.rulePaths` in settings, but when changing to `~/work-projects` the editor settings cause errors. but at the same time there is a lot of repo churn in that project directory, so adding the same setting everytime isn't ideal. Also at the same time including the settings in the repo would be commitment to a single editor.

**Comment by kieferrm** [comment]
@gbmajaco  When you open start vscode with `code ~/projects` then vscode uses `~/projects/.vscode`as its workspace configuration directory. When you open vscode with `code ~/projects/project-a` vscode used `~/projects/project-a/.vscode` as its workspace configuration directory.' There is no *inheritance* between `~/projects/project-a/.vscode` and `~/projects/.vscode` when it comes to workspace configurations. They are considered separate.

When you make changes to the user settings and not the workspace settings they are shared across all workspaces. Workspace settings *inherit* from user settings.

In your case, using .eslintrc files seems like the right thing to do. They are specific to eslint and the editor you use. They support inheritance. They can and should be be maintained in the repository.

**Comment by ashclarke** [comment]
I had a need for this recently, but specifically for the search exclusion and file exclusion settings.

Only way to get around this is to copy-paste these settings and maintain them across multiple project folders, whereas it would be much better to be able to inherit these settings from the parent "solution" folder.
