### ISSUE TITLE
While fetching workspace settings via API, add an option to resolve setting value against the location of the workspace file

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#98424]
Consider a workspace setting which contains paths, for instance, `python.pythonPath`. While fetching those workspace settings containing paths (either when using `.inspect` or `.get`), resolve them relative to workspace file.

You guys already do that for `folders.path` section, it would be better this is handled on your side for all the settings in `.code-workspace` file which contains paths for consistency.

![image](https://user-images.githubusercontent.com/13199757/82726638-6284fa00-9c9a-11ea-94fc-d26939d22046.png)

### A problematic scenario

While using `.get` to access `python.pythonPath` setting, if we see a `.` in the setting value, we as an extension do not know whether it came from workspace setting, workspace folder setting, so we don't know what to resolve that `.` to. IMO it's easier to handle it here.

In issue https://github.com/microsoft/vscode-python/issues/11918, we were resolving everything relative to workspace folder which was the issue.

**Comment by mburszley** [comment]
@sandy081 How is that a duplicate?  This is about resolution of variables, not support for them.

**Comment by sandy081** [comment]
@mburszley we do not support resolving them by default and the dup issue is to support that.

**Comment by mburszley** [comment]
@sandy081 This issue is about vscode-supported variables like `${workspaceFolder}` being resolved at the "wrong" path in a multi-root workspace.  < to be a little more explicit

**Comment by sandy081** [comment]
We do not support resolving any variables in settings currently and the linked issue to add that support. I am guessing you are asking for the same.

**Comment by karrtikr** [comment]
@mburszley It was resolved to the wrong path because the extension did the resolving. VSCode does not resolve anything as of now, they'll start supporting it in #2809, so the extension need not do it, which will solve the problem.
