### ISSUE TITLE
The window looks like shadowed.

### ISSUE THREAD

**Issue by TZTsai** [microsoft/vscode#98422]
Issue Type: <b>Bug</b>

The whole window looks like covered by a shadow, except several bright rectangle areas like in the debugger and the left search bar. I think this may be a DPI problem. The minimap on the right side also becomes very small.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (6.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|Memory (System)|15.75GB (6.08GB free)|
|VM|67%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|4.7.0
vscode-icalendar|af4|1.0.1
cshtml|fir|0.1.3
remote-wsl|ms-|0.44.2
vim|vsc|1.14.5
vscode-ruby|win|0.27.0

</details>

**Comment by gjsjohnmurray** [comment]
Does https://github.com/microsoft/vscode/issues/94971#issuecomment-627987227 help?

**Comment by TZTsai** [comment]
> Does [#94971 (comment)](https://github.com/microsoft/vscode/issues/94971#issuecomment-627987227) help?

Thanks a lot! Disabling HDR color in the Windows setting perfectly solves this problem.
