### ISSUE TITLE
File copy+paste no longer works within Explorer pane

### ISSUE THREAD

**Issue by nickcoad** [microsoft/vscode#98425]
Version: 1.46.0-insider (user setup)
Commit: 2591ede95a52400d5d22989b16706f9b8b4831da
Date: 2020-05-22T21:13:15.709Z
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.18363

Attempting to copy + paste a file in the Explorer pane appears to have no effect. The file does not even appear to be copied to the clipboard. Copying using the keyboard shortcut (Ctrl+C and Ctrl+V) doesn't work, neither does copying using the right-click menu (you can select Copy, but when you try to Paste it is grayed out as though the clipboard does not contain the file).

Steps to Reproduce:

1. Using Code Insiders, open any project or start a new one and create at least one file
2. Select that file in the explorer pane
3. Press Ctrl+C to copy and then Ctrl+V to paste
4. Nothing occurs, instead of a copy of the file being pasted into the Explorer pane

Does this issue occur when all extensions are disabled?: Yes

**Comment by takahash** [comment]
I had a similar problem.

```
Version: 1.46.0-insider
Commit: 2591ede95a52400d5d22989b16706f9b8b4831da
Date: 2020-05-22T21:12:53.428Z
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Linux x64 5.4.0-31-generic
```

Attempting to copy the file will result in an error.

```
The file to paste has been deleted or moved since you copied it. Error: ENAMETOOLONG: name too long, stat '/102,105,108,101,58,47,47,47,104,111,109,101,47,116,97,107,97,107,101,110,47,119,111,114,107,115,112,97,99,101,47,106,103,109,47,106,103,109,45,104,105,116,111,114,105,45,100,101,45,103,111,108,102,45,97,100,109,105,110,47,97,112,112,47,97,112,105,47,115,116,97,102,102,85,115,101,114,47,105,110,100,101,120,46,116,115'
```

**Comment by furai** [comment]
Experiencing the same issue.
```
The file to paste has been deleted or moved since you copied it. Error: ENAMETOOLONG: name too long, stat (...)
```
Version: 1.46.0-insider
Commit: 2591ede95a52400d5d22989b16706f9b8b4831da
Date: 2020-05-22T21:12:53.428Z
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Linux x64 5.6.14-050614-generic

**Comment by isidorn** [comment]
I can reproduce this on Ubuntu 18. On macOS all works fine.
The error is coming from the `workingCopyFileService` thus forwarding to @bpasero to also inveistigate
fyi @deepak1556 since we upgraded to latest Electron and this is probably the root cause
Code pointer where we throw 
https://github.com/microsoft/vscode/blob/66ef23d401b24444d1465aa4bd6db369c1632de2/src/vs/workbench/contrib/files/browser/fileActions.ts#L1174

```
The file to paste has been deleted or moved since you copied it. Error: ENAMETOOLONG: name too long, stat '/102,105,108,101,58,47,47,47,104,111,109,101,47,112,97,114,97,108,108,101,108,115,47,68,101,118,101,108,111,112,109,101,110,116,47,118,115,99,111,100,101,47,115,114,99,47,118,115,47,119,111,114,107,98,101,110,99,104,47,98,114,111,119,115,101,114,47,112,97,114,116,115,47,109,101,100,105,97,47,99,111,109,112,111,115,105,116,101,112,97,114,116,46,99,115,115'
```

**Comment by bpasero** [comment]
Very possibly a Electron 8 regression from our use of the clipboard storing a custom type:

https://github.com/microsoft/vscode/blob/1ba6a15920c23d44a38f79e2225312c4417d9b56/src/vs/workbench/services/clipboard/electron-browser/clipboardService.ts#L46

**Comment by bpasero** [comment]
Hm, interestingly I do not see this fail from my `ben/electron-sandbox` branch where I moved `clipboard` access to `electron-main` process. It would be lucky, but maybe only `clipboard` in `electron-renderer` broke?

**Comment by bpasero** [comment]
Just verified that I can also not reproduce running from `master` with Electron 8 reverted.

**Comment by AlbertoBonfiglio** [comment]
HI, I have the same issue with 
Version: 1.46.0-insider
Commit: 8687508aa689b1f16d5f6ff317eb25bcf4544586
Date: 2020-05-26T05:44:44.454Z
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Linux x64 5.4.0-31-generic

however it works with 
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-31-generic

**Comment by fish-finger** [comment]
Version: 1.46.0-insider
Commit: b26e0bcf39c1b8faaf770265391b5a387d1d9172
Date: 2020-05-26T16:16:10.519Z
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Linux x64 5.4.0-31-generic

been impacting me for a few days now. I can drag and drop but not copy/paste.

**Comment by dimitry-ishenko** [comment]
@bpasero was this fixed somewhere? I still can't copy/paste in the insiders version

**Comment by bpasero** [comment]
Yeah should be fine now with the insiders build from today:

```
Version: 1.46.0-insider
Commit: 876f2e70f9a2e1988887f8ca82294418afac15a2
Date: 2020-05-27T05:41:02.088Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```
