### ISSUE TITLE
Option to not add files to recent history for files outside of the opened folder

### ISSUE THREAD

**Issue by GuiRitter** [microsoft/vscode#98428]
Somewhat related to this feature: #84271

Sometimes I'm working on a folder (Open `vscode` > *Open Folder...*) or several and I want to open a file with `vscode` that doesn't belong to any of the opened folders. This file gets added to the list of recently opened files.

I would like that it doesn't. The reason is because when I'm working on a folder, I would like to use Ctrl+E to search only for files contained in that folder. External files add noise that I have to clear manually.

I understand that other people might prefer differently from me, so it should be an option.

Thanks in advance.

**Comment by duganchen** [comment]
Heads up that @GuiRitter has started a forum thread to crowdsource upvotes.

https://www.linuxquestions.org/questions/general-10/please-vote-on-my-vscode-feature-request-4175677418/

**Comment by GuiRitter** [comment]
> Heads up that @GuiRitter has started a forum thread to crowdsource upvotes.
> 
> https://www.linuxquestions.org/questions/general-10/please-vote-on-my-vscode-feature-request-4175677418/

Is that a bad thing?

**Comment by TheDaemoness** [comment]
Another forum thread intended to round up upvotes:
https://cplusplus.com/forum/lounge/271356/

That said, quoting [the issues triaging page](https://github.com/microsoft/vscode/wiki/Issues-Triaging#managing-feature-requests) (emphasis mine):
> If you feel your feature request deserves to stay open, improve your use case and ping us **or gather more up-votes**.

**Comment by GuiRitter** [comment]
> Another forum thread intended to round up upvotes:
> https://cplusplus.com/forum/lounge/271348/
> 
> That said, quoting [the issues triaging page](https://github.com/microsoft/vscode/wiki/Issues-Triaging#managing-feature-requests) (emphasis mine):
> 
> > If you feel your feature request deserves to stay open, improve your use case and ping us **or gather more up-votes**.

Yeah, you're gonna find several...

I got the message. I'll take 'em down. I'm sorry, I wasn't aware.

**Comment by GuiRitter** [comment]
All right, I think I got all of them. On 3 I couldn't edit nor remove the post. In these cases, I reported myself, asking for moderation to remove my posts.

(I'm appalled by how only 1 or 2 allowed me to delete the thread)

Sorry again for the inconvenience. I honestly didn't imagine something like this would be frowned upon and I didn't mean to cause trouble.
