### ISSUE TITLE
VSCODE cant start

### ISSUE THREAD

**Issue by dzakydaffa24** [microsoft/vscode#98423]
Issue Type: <b>Bug</b>

After restart my laptop, VSCODE cant start

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
First suggestion is to update to the latest version (1.45.1). Uninstall and reinstall. Your settings will be preserved.

**Comment by dzakydaffa24** [comment]
Every time I restart the laptop, i always reinstall VSCode to open it

**Comment by gjsjohnmurray** [comment]
Why are you installing an outdated version?

**Comment by kieferrm** [comment]
@dzakydaffa24 we don't support old versions of VS Code. Please uninstall your old version and install the latest version. Try to run with auto-update enabled, so that you always stay on the latest version.
