### ISSUE TITLE
Colors washed out on MacOS Catalina

### ISSUE THREAD

**Issue by ianobermiller** [microsoft/vscode#98434]
- VSCode Version:
```
Version: 1.46.0-insider
Commit: 2591ede95a52400d5d22989b16706f9b8b4831da
Date: 2020-05-22T21:12:04.233Z
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 19.4.0
```
- OS Version: macOS Catalina v10.15.4

Steps to Reproduce:

1. Install Cobalt2 theme to make this obvious
2. Load up Code and Code Insiders side by side

Does this issue occur when all extensions are disabled?: Yes

I've also tried all combinations of "Configure Runtime Arguments":
(this was recommended in other issues but does not help)
```
{
  // "disable-hardware-acceleration": true,
  "disable-color-correct-rendering": true
  "force-color-profile": "srgb"
}
```

I do have [f.lux](https://justgetflux.com/) installed, but removing it and changing the color profiles in the Displays preferences still produces discrepancies between Insiders and Stable.

Screenshot: top is insiders, bottom is stable:

![image](https://user-images.githubusercontent.com/897931/82733477-f5d52400-9cc8-11ea-9fdb-79d220251efb.png)

**Comment by deepak1556** [comment]
Is this still an issue with latest insiders https://code.visualstudio.com/insiders

**Comment by ianobermiller** [comment]
No, this appears to have been fixed.
