### ISSUE TITLE
"Add all missing imports" adds import with doublequote not single quote

### ISSUE THREAD

**Issue by chopswil15** [microsoft/vscode#98432]
using quick fix in my angular app to "Add all missing imports"  does indeed add the missing imports however all the from statements are in double quotes and they then show as an error.

Seems like "Add all missing imports" should do so without creating an error.

![image](https://user-images.githubusercontent.com/59748191/82733172-5d8e6d80-9ccf-11ea-846b-9b26ba6a21e7.png)

**Comment by chopswil15** [comment]
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (22.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.1.4
vscode-eslint|dba|2.1.5
xml|Dot|2.5.0
vscode-html-css|ecm|0.2.3
beautify|Hoo|1.5.0
rest-client|hum|0.23.2
csharp|ms-|1.21.18
mssql|ms-|1.9.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vetur|oct|0.24.0

**Comment by mjbvz** [comment]
Those errors are from eslint, not VS Code itself

To have VS Code use single quotes for imports, try setting: `javascript.preferences.quoteStyle` or `typescript.preferences.quoteStyle`
