### ISSUE TITLE
OS X: Command line tool won't launch a file whose name is just a number

### ISSUE THREAD

**Issue by aselder** [microsoft/vscode#98439]
- VSCode Version: 1.45.1
- OS Version: OS X 10.15.5 Beta

Steps to Reproduce:

1. Create a text file whose name is just a number, e.g. `touch 8`, `touch 887987`, etc
2. Try to launch the file from the command line `code 8`
3. No file is opened. If VSCode was closed, it starts and just shows the welcome screen. If VSCode is running, you see another VSCode icon bounce in the dock and go away.
4. Rename to file to something else, it works fine `cp 8 a; code a`

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
@bpasero I have a feeling we've seen this before?

**Comment by bpasero** [comment]
@joaomoreno yes I remember something was not right with our argv lib (minimist?) with regards to handling numbers?

**Comment by foad** [comment]
Hi, was having this problem too and I think I found the problem

We were discarding empty args as part of https://github.com/microsoft/vscode/issues/58177, however this would discard numbers too as they were not strings when the check took place

Have made a PR to remedy this if that's ok
