### ISSUE TITLE
Editor: Turn off cursor position showing on a slider

### ISSUE THREAD

**Issue by younyokel** [microsoft/vscode#98438]
Editor has a feature that shows current cursor position. It is located on a slider on the right side of the screen. I personally don't like how it looks so I would like to have an option to disable this function.

![изображение](https://user-images.githubusercontent.com/53343081/82738521-fd90d900-9d59-11ea-9caf-5ea5c35b8d1c.png)

I am sorry if this feature already exists, but I didn't find it. If it does please provide me with information how to turn it off.

Thank you.

**Comment by IllusionMH** [comment]
Cursor position (horizontal line) can be hidden with `"editor.hideCursorInOverviewRuler": true`.
Is it what you were looking for?

Just in case vertical bar is from `"editor.selectionHighlight": true` - highlights text similar to selection across editor and shows them in overview ruler. If turned off - no vertical bars in ruler, but also no selections in editor.

**Comment by kieferrm** [comment]
See comment above.
