### ISSUE TITLE
Cannot enter ~ symbol in simple dialog

### ISSUE THREAD

**Issue by huye** [microsoft/vscode#98431]
Issue Type: <b>Bug</b>

When the simple dialog is enabled, the address cannot be entered with the ~ symbol, and every time you enter ~, the entire path is replaced with the home directory.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.3.0-3-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx (8 x 1582)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|14.66GB (1.37GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|deepin|
|XDG_CURRENT_DESKTOP|Deepin|
|XDG_SESSION_DESKTOP|deepin|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|0.6.0
githistory|don|0.6.5
vscode-language-pack-zh-hans|MS-|1.45.1
cpptools|ms-|0.28.1

</details>

**Comment by alexr00** [comment]
This is intentional and was a feature request. The idea was to provide a quick way to go to user home.

**Comment by huye** [comment]
I know that, but I think it should be done only when the path begins with the ~ character, not when you type the ~ in the path.
