### ISSUE TITLE
[Request] [Typescript] Expand Type Option and/or Interactive Type Resolution

### ISSUE THREAD

**Issue by bradennapier** [microsoft/vscode#98436]
# What

Provide a mechanism for expanding types into a "resolved type" when hovering and holding a special hot key (example hover and hold CMD/CTRL which expands the type a bit, then SHIFT to resolve the type via expansion).

This would be even more powerful if it could be done interactively by expanding the types similar to how chrome inspector shows objects and allows expanding them.  This would be extremely powerful especially if it allows grabbing the documentation along the way.  This would largely eliminate the need to ever open documentation outside of the code itself.

The interactive method would also be nice as it would make it far easier to expand into deeper types more efficiently and since recursive resolution can take time it helps do the expansion lazily.

In 90% of cases our types are just a couple levels deep though and if deeper we often do not care about those values.

I would be willing to work on this although the latter suggestion is probably a more fundamental change.  

# Why 

So as I get more advanced with Typescript, I have begun to derive my types from other types more to make things "just work" and properly describe the way the code works.  This has been a huge boost to the productivity of the team as well as the power the IDE provides in most cases.

However, there are downsides.  Specifically that often the IDE is just defining these advanced types until you start using them which makes it hard to know the actual type expected.  Completions helps as you are building the object but that has its limits as well.

As an example which produces a powerful example of how this can be useful, lets take a look at the `aws-sdk` 

```typescript
import AWS from 'aws-sdk';
type ClientOptions = AWS.DynamoDB.DocumentClient.DocumentClientOptions;
```

![image](https://user-images.githubusercontent.com/15365418/82736924-1e761180-9cfb-11ea-9923-17410652b2d6.png)

This doesn't give me much info to help me in actually providing this type when it is requested.  I can of course go and navigate into the type and check but often this starts looking like this:

```typescript
export interface DocumentClientOptions extends ConverterOptions {
        /**
         * An optional map of parameters to bind to every request sent by this service object.
         */
        params?: {[key: string]: any}
        /**
         * An optional pre-configured instance of the AWS.DynamoDB service object to use for requests. The object may bound parameters used by the document client.
         */
        service?: DynamoDB
    }
```

So it extends something and the keys are deeper types which also extend things... so it gets pretty difficult to figure out what we can actually provide without spending a decent amount of time on it.

We have created helpers to make this easier.  They aren't perfect due to typescripts built-in truncation of types which can't be configured yet (plan to request options for this as well).

We have defined `$Debug` and `$DebugDeep` in our `globals.d.ts` to help with this personally, but that doesn't help in many cases since we need to get the types alone to do so.  We can't easily add those values when we are calling the function, for example.

When we use `$Debug` the type ends up looking like this:

```typescript
type ClientOptions = {
    params?: {
        [key: string]: any;
    };
    service?: AWS.DynamoDB;
    convertEmptyValues?: boolean;
    wrapNumbers?: boolean;
}
```

![image](https://user-images.githubusercontent.com/15365418/82737102-50d43e80-9cfc-11ea-9abc-143d682c8fb8.png)

We have `$DebugDeep<T, ExcludeValuesOf = never, Depth = 5>` which will iterate through deeper as well (currently maximum to 5 levels deep).

Now we can a more useful type depending on the situation:

```typescript
type ClientOptions = {
    params?: {
        [x: string]: any;
    };
    service?: {
        config: {
            getCredentials: (callback: (err: AWS.AWSError) => void) => void;
            loadFromPath: (path: string) => ConfigBase;
            update: {
                (options: ConfigurationOptions & {
                    [key: string]: any;
                }, allowUnknownKeys: true): void;
                (options: ConfigurationOptions, allowUnknownKeys?: false): void;
            };
            getPromisesDependency: () => void | PromiseConstructor;
            setPromisesDependency: (dep: any) => void;
            computeChecksums?: boolean;
            convertResponseTypes?: boolean;
            correctClockSkew?: boolean;
            customUserAgent?: string;
            credentials?: {
                get: (callback: (err?: AWS.AWSError) => void) => void;
                getPromise: () => Promise<void>;
                needsRefresh: () => boolean;
                refresh: (callback: (err?: AWS.AWSError) => void) => void;
                refreshPromise: () => Promise<void>;
                accessKeyId: string;
                expired: boolean;
                expireTime: {
                    toString: () => string;
                    toDateString: () => string;
                    toTimeString: () => string;
                    toLocaleString: {
                        (): string;
                        (locales?: string | string[], options?: Intl.DateTimeFormatOptions): string;
                    };
                    toLocaleDateString: {
                        (): string;
                        ( ...
```

![image](https://user-images.githubusercontent.com/15365418/82737638-63e90d80-9d00-11ea-843f-7498c12d370f.png)

If we only use `$DebugDeep1` to only expand 1 level in, you can see why this is getting powerful as config is an intersection of a bunch of values we would otherwise need to go and check into each of to determine what we can actually provide:

```typescript
type ClientOptions = {
    params?: {
        [x: string]: any;
    };
    service?: {
        config: ConfigBase & ServiceConfigurationOptions & AWS.DynamoDB.ClientApiVersions;
        batchGetItem: {
            (params: AWS.DynamoDB.BatchGetItemInput, callback?: (err: AWS.AWSError, data: AWS.DynamoDB.BatchGetItemOutput) => void): AWS.Request<AWS.DynamoDB.BatchGetItemOutput, AWS.AWSError>;
            (callback?: (err: AWS.AWSError, data: AWS.DynamoDB.BatchGetItemOutput) => void): AWS.Request<AWS.DynamoDB.BatchGetItemOutput, AWS.AWSError>;
        };
        batchWriteItem: {
            (params: AWS.DynamoDB.BatchWriteItemInput, callback?: (err: AWS.AWSError, data: AWS.DynamoDB.BatchWriteItemOutput) => void): AWS.Request<AWS.DynamoDB.BatchWriteItemOutput, AWS.AWSError>;
            (callback?: (err: AWS.AWSError, data: AWS.DynamoDB.BatchWriteItemOutput) => void): AWS.Request<AWS.DynamoDB.BatchWriteItemOutput, AWS.AWSError>;
        };
        createBackup: {
            (params: AWS.DynamoDB.CreateBackupInput, callback?: (err: AWS.AWSError, data: AWS.DynamoDB.CreateBackupOutput) => void): AWS.Request<AWS.DynamoDB.CreateBackupOutput, AWS.AWSError>;
            (callback?: (err: AWS.AWSError, data: AWS.DynamoDB.CreateBackupOutput) => void): AWS.Request<AWS.DynamoDB.CreateBackupOutput, AWS.AWSError>;
        };
        createGlobalTable: {
            (params: AWS.DynamoDB.CreateGlobalTableInput, callback?: (err: AWS.AWSError, data: AWS.DynamoDB.CreateGlobalTableOutput) => void): AWS.Request<AWS.DynamoDB.CreateGlobalTableOutput, AWS.AWSError>;
            (callback?: (err: AWS.AWSError, data: AWS ...
```

We have the `ExcludesValuesOf` which can add values to ignore - but the interactive explorer would largely make this unimportant which is nice.

```typescript
type ClientOptions = $DebugDeep<
  AWS.DynamoDB.DocumentClient.DocumentClientOptions,
  AWS.Credentials | AWS.CredentialProviderChain | AWS.HTTPOptions
>;
```

```typescript
type ClientOptions = {
    params?: {
        [key: string]: any;
    };
    service?: {
        config: {
            getCredentials: (callback: (err: AWS.AWSError) => void) => void;
            loadFromPath: (path: string) => ConfigBase;
            update: {
                (options: ConfigurationOptions & {
                    [key: string]: any;
                }, allowUnknownKeys: true): void;
                (options: ConfigurationOptions, allowUnknownKeys?: false): void;
            };
            getPromisesDependency: () => void | PromiseConstructor;
            setPromisesDependency: (dep: any) => void;
            computeChecksums?: boolean;
            convertResponseTypes?: boolean;
            correctClockSkew?: boolean;
            customUserAgent?: string;
            credentials?: AWS.Credentials | {
                accessKeyId: string;
                secretAccessKey: string;
                sessionToken?: string;
            };
            credentialProvider?: AWS.CredentialProviderChain;
            accessKeyId?: string;
            secretAccessKey?: string;
            sessionToken?: string;
            httpOptions?: AWS.HTTPOptions;
            logger?: {
                write?: (chunk: any, encoding?: string, callback?: () => void) => void;
                log?: (...messages: any[]) => void;
            };
            maxRedirects?: number;
            maxRetries?: number;
            paramValidation?: boolean | {
                min?: boolean;
                max?: boolean;
                pattern?: boolean;
                enum?: boolean;
            };
            region ...
```

**Comment by bradennapier** [comment]
For anyone interested those debug types we use are defined here:
https://gist.github.com/bradennapier/1dbc2933148b6a5917536863e34d8613

**Comment by mjbvz** [comment]
Thanks for the detailed write-up. 

This is being tracked by #64566, which focuses on diagnostics but could also apply to hovers. Solving it requires new API from typescript, as well as new UI on the VS Code side
