### ISSUE TITLE
Support for Unicode-aware regular expressions in Monaco Monarch language definitions

### ISSUE THREAD

**Issue by D-to-the-K** [microsoft/vscode#98446]
Feature request for the Monaco Editor.

Create an optional flag for Monaco Monarch language definitions to indicate the usage of unicode-aware regular expressions.

An example of one such regular expression is `/\u{1D306}/u`, matching the '𝌆' character.

**Comment by alexdima** [comment]
@D-to-the-K What exactly does not work? Since you can pass in regular expressions directly e.g. https://github.com/microsoft/monaco-languages/blob/618f2cff2d8e72f04fe9d63085a0c5118b80e8a0/src/html/html.ts#L75

**Comment by D-to-the-K** [comment]
Hi, Alex. 

What's currently not working is the unicode-aware regular expressions supported by ES2015.

Even though you're able to write a RegExp including unicode-aware characters (in the format `\u\{[A-Fa-f0-9]+\}`), and even set the unicode flag for that RegExp, they don't work in Monaco Monarch at the moment.

Below is the monaco-language file for ABAP, edited to support the `𝌆` character in identifiers.

![image](https://user-images.githubusercontent.com/13403610/83412027-d0929500-a3ef-11ea-837a-5d2d59b1b4a6.png)

This is how it shows up in the editor:

![image](https://user-images.githubusercontent.com/13403610/83412074-e99b4600-a3ef-11ea-8175-ed9adb31a4df.png)

That happens precisely because the unicode flag is stripped away by compileRegExp:
https://github.com/microsoft/vscode/blob/master/src/vs/editor/standalone/common/monarch/monarchCompile.ts#L106

If we change that line to, say
`return new RegExp(str, (lexer.ignoreCase ? 'iu' : 'u'));`

it works as expected:

![image](https://user-images.githubusercontent.com/13403610/83412237-236c4c80-a3f0-11ea-9ee5-ceb71496d3cf.png)

The proposed solution is a way for the developer to tell Monaco Monarch that, instead of stripping away the unicode flag from all the regular expressions, it should instead add it to all the regular expressions if a `unicode` flag is set in the language definition, just like it's the current behavior for the ignoreCase option.

Another option I've considered was to instead use the unicode flag if, and only if, it is set in the regular expression itself, but for what I could gather, that would force us to compile the RegExp an extra time just for testing the flag, or to parse the RegExp manually.

Let me know if you need more information.

**Comment by alexdima** [comment]
:+1: Thank you, this makes good sense!
