### ISSUE TITLE
can not run debugger anymore

### ISSUE THREAD

**Issue by nbkgit** [microsoft/vscode#98449]
Issue Type: <b>Bug</b>

Since the last update, when i click on run and debug no window shows me some options, so that i can start debugging. the text highlight works fine, but nothing happens, and no problems are reported, only running a program doesn't seem to work any more with my python files. 

Edit: What happens, when i click _run and debug_ is for a minimal time appears the debugging ribbon at the top of he page and disappears instant nothing debugs. Also running the code also doesn't start.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 430  @ 2.27GHz (4 x 2261)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (3.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-django|bat|0.20.0
vscode-eslint|dba|2.1.5
python-extension-pack|don|1.6.0
xml|Dot|2.5.0
gitlens|eam|10.2.1
prettier-vscode|esb|4.7.0
rest-client|hum|0.23.2
sftp|lix|1.12.9
MagicPython|mag|1.1.0
vscode-language-babel|mgm|0.0.27
mssql|ms-|1.9.0
python|ms-|2020.5.80290
notepadplusplus-keybindings|ms-|1.0.5
debugger-for-chrome|msj|4.12.8
sqltools|mtx|0.21.7
LiveServer|rit|5.6.1
python|tht|0.2.3
vscodeintellicode|Vis|1.2.7
quokka-vscode|Wal|1.0.290
jinja|who|0.0.8

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by kieferrm** [comment]
@nbkgit what language do you want to debug?

**Comment by nbkgit** [comment]
for now i try to debug python with installed python 3.82 64 bit and i installed all the in vs code recommended  extensions, or if need be some other.

the python is a simple mysql.connector program that get a table and print its elements.

As i wrote in my issue i click on the button and then should be a small ribbon with some icons to get step by step debug and so on, this appears only for a split second, before it disappears.
Ni debugging and i also can't run the program.

The does show an error except this https://github.com/MicrosoftDocs/intellicode, but thos doesn' appear to be during run time.

so if you want more information please ask

**Comment by kieferrm** [comment]
\extPython
