### ISSUE TITLE
VSCode Gets Confused when using Multiple GitHub Accounts

### ISSUE THREAD

**Issue by tvmgoog** [microsoft/vscode#98448]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Sign into VSCode using a First GitHub Account
Have  browser session with Second GitHub Account

Expected Behavior:

VSCode should Run int he contect of the GitHub Account it isSinged into
Actual Behavior:
 For Some reason, it gets with Catched Credentials for teh Seconf GitHub account from Previous work or picks up account cred from GitHub for Windows App or from Browser

VS Code version: Code - Insiders 1.46.0-insider (2591ede95a52400d5d22989b16706f9b8b4831da, 2020-05-22T21:13:15.709Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
azds|azu|2.0.220200514
vscode-markdownlint|Dav|0.35.2
gitlens|eam|10.2.1
rest-client|hum|0.23.2
terraform|mau|1.4.0
azure-pipelines|ms-|1.170.0
vscode-apimanagement|ms-|0.1.3
vscode-azureappservice|ms-|0.16.5
vscode-azurefunctions|ms-|0.22.1
vscode-azureresourcegroups|ms-|0.1.0
vscode-azurestorage|ms-|0.9.0
vscode-azureterraform|ms-|0.3.0
vscode-azurevirtualmachines|ms-|0.1.0
vscode-cosmosdb|ms-|0.12.2
vscode-docker|ms-|1.2.0
vscode-dotnet-runtime|ms-|0.1.2
vscode-aks-tools|ms-|0.0.4
vscode-kubernetes-tools|ms-|1.2.0
mssql|ms-|1.9.0
python|ms-|2020.5.80290
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.11
azurecli|ms-|0.5.0
powershell|ms-|2020.4.0
resharper9-keybindings|ms-|1.1.0
vs-keybindings|ms-|0.2.0
vscode-node-azure-pack|ms-|0.0.11
team|ms-|1.161.0
azurerm-vscode-tools|msa|0.10.0
vscode-yaml|red|0.8.0
arm-snippets|sam|1.4.19
code-spell-checker|str|1.9.0
azure-iot-toolkit|vsc|2.16.1

</details>

**Comment by RMacfarlane** [comment]
This is as designed - VS Code does not have a way of knowing that you have a second browser session with a different GitHub account, it only remembers what you have logged in with
