### ISSUE TITLE
Proxy configuration

### ISSUE THREAD

**Issue by koala59230** [Microsoft/vscode#9844]
- VSCode Version: 1.3.1
- OS Version: Windows 7 Enterprise SP1

Hello,

I want to use Visual Code behind a enterprise proxy. This proxy configuration use a auto configuration script.

With or Without this configuration in json file, not working and no error.

Do you have some idea ?

thanxs a lot.

Great work for VSCode. (Y)

**Comment by joaomoreno** [comment]
You need to figure out what's the address of your proxy server and add it to [your settings](https://code.visualstudio.com/docs/setup/setup-overview#_proxy-server-support).
