### ISSUE TITLE
sidebar broke

### ISSUE THREAD

**Issue by Darthsoviet** [microsoft/vscode#98451]
when you drag the icon to the terminal window it separates and cannot be rejoined i

**Comment by sbatten** [comment]
@Darthsoviet, can you clarify which icon you dragged?

**Comment by sbatten** [comment]
A screenshot will help

**Comment by Darthsoviet** [comment]
I drag de docker sidebar icon into the terminal and breaks in pieces that can't be rejoined, I did it once again with the SQLServer  icon and happens the same, I reinstall my VS.
look at the bottom sidebar icons. that's the sqlServer pieces
![Captura de pantalla (34)](https://user-images.githubusercontent.com/31465914/84074862-d6ace680-a998-11ea-889c-b5a6d53b3502.png)

**Comment by sbatten** [comment]
@Darthsoviet `Ctrl+Shift+P` => `Reset View Locations`

**Comment by Darthsoviet** [comment]
Sorry, I had looked in the view tab, it never occurred to me

**Comment by sbatten** [comment]
no worries, improvements are coming next release. thanks for using it :)
