### ISSUE TITLE
cannot update environment variable immediately

### ISSUE THREAD

**Issue by wangzhankun** [microsoft/vscode#98454]
- VSCode Version: 1.45.1
- OS Version: Windows 10

Steps to Reproduce:

1. change your enviroment variable
2. load vscode and echo %VARIABLE_NAME%, you will find that the variable value is permanent,
but you can echo %VARIABLE_NAME% in an outside cmd and the value has been changed.
3. restart windows and open vscode, the variable will be right.

Does this issue occur when all extensions are disabled?:   
NO. But I think maybe it inherits its parent variable when load vscode in cmd.  Because when I load vscode with all enabled extensions in the cmd rather than load by double-clicking the icon , also has the right variable.

## issue
![image](https://user-images.githubusercontent.com/35724924/82747694-5732eb00-9dce-11ea-9801-16078c37c784.png)

![image](https://user-images.githubusercontent.com/35724924/82747699-6f0a6f00-9dce-11ea-80e2-24456a71fa9e.png)

**Comment by kieferrm** [comment]
VS Code inherits the environment of the process it is started by.
