### ISSUE TITLE
Clicking on item in outline is not jumping right

### ISSUE THREAD

**Issue by lefebvresam** [microsoft/vscode#98458]
![Capture](https://user-images.githubusercontent.com/15315428/82749846-4ffae580-9dac-11ea-9aee-7780068bfd76.JPG)
Issue Type: <b>Bug</b>

When you have a big header file and you click on function declarations in the outline window, the jump to the code is not correct. I always have an offset of about 300 lines.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17763

**Comment by kieferrm** [comment]
\extC++
