### ISSUE TITLE
Code language not supported or defined

### ISSUE THREAD

**Issue by saurabhprasadsah** [microsoft/vscode#98455]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by saurabhprasadsah** [comment]
when you are using index.html file but you are running in this in this server then Error message will be show this

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including platform, version numbers, details of how to reproduce. Screenshots can be pasted here.

**Comment by saurabhprasadsah** [comment]
okay
