### ISSUE TITLE
Panel: order of panes does not put terminal last

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98456]
When you run with fresh UI state, the terminal appears before debug console for some reason, I think it is always last normally:

![image](https://user-images.githubusercontent.com/900690/82748393-bdeddf80-9da1-11ea-931c-77d75dd3037e.png)

**Comment by bpasero** [comment]
I am still seeing this when I run `yarn web`.

**Comment by sbatten** [comment]
Fresh user directory?

**Comment by bpasero** [comment]
@sbatten yes. if you just use `yarn web` you will always get a fresh user data dir because no data is persisted.
