### ISSUE TITLE
Latest VS Code Installs Its Own Juypter Environment-Don't Want

### ISSUE THREAD

**Issue by j-a-lewis** [microsoft/vscode#98450]
I've previously installed Anaconda Python first, then Visual Studio Code and only the environments that I've created in Anaconda Navigator or the Anaconda Command Prompt have shown up on my Juypter Server or in Visual Studio Code.  However, when I did this on a brand new computer sometime after May 6, 2020, Visual Studio Code installed its own environment.  This environment shows up in Code in addition to the two conda created ones I have and it also shows up on my Juypter local server.  This "feature" is very annoying and wastes resources.  Please give us a clear and obvious way to recognize its going to be created in spite of the fact that we have several conda environments already and let us nip it in the bud.  I'm sure as with all things Microsoft, if I get an IT certification or two, I'll be able to  get rid of it after the fact but why not make things clear and easy for your users instead of hopelessly complicated?

**Comment by kieferrm** [comment]
\extPython
