### ISSUE TITLE
Poor File Explorer Design in Studio Code

### ISSUE THREAD

**Issue by Thierry-TGMDev** [microsoft/vscode#98452]
Issue Type: <b>Performance Issue</b>

Hello
I use Visual Studio Code to code all the files of my Web site. And it's quite a great software.
But your file explorer is a real nuisance. Akward and clumsy. Why did you reinvent the wheel ? It is done perfectly for Visual Studio 2019 (that I use to develope C++ application). But the wheel in Visal Studio code is turning square. I often use Windows Explorer besides for files handling. It's a pity, isn't it !

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please provide actual details what is wrong and what improvements you would expect.
