### ISSUE TITLE
Cannot find <stdio.h> and printf command

### ISSUE THREAD

**Issue by AGoh2019** [microsoft/vscode#98457]
#include <stdio.h>

int main(void)
{
    printf("Hello World");
    return 0;
}

And VS Code asked me to install the Clang extension which I did.  Can you make this VS Code IDE idiot proof, so that I can write software and care less about fighting with the VS Code IDE?

**Comment by kieferrm** [comment]
I'm guessing that the issue of not finding `stdio` happened after you installed the C extension.

**Comment by kieferrm** [comment]
\extC
