### ISSUE TITLE
How can I use input by python in Visual Studio Code?

### ISSUE THREAD

**Issue by Eric2i** [Microsoft/vscode#9846]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:31:10.994Z)
- OS Version: Darwin x64 16.0.0

I am pretty sure that I didn't make mistakes in my codes. But the vs code doesn't seem to be able to use 'input', because after I run the program, I can't type anything into the vs code or see anything when the program codes have 'input' in it. It won't show me anything either.

**Comment by DonJayamanne** [comment]
@Eric2i , you can find the solution here [DonJayamanne/pythonVSCode/issues/196](https://github.com/DonJayamanne/pythonVSCode/issues/196) with sample [instructions here](https://github.com/DonJayamanne/pythonVSCode/wiki/Capture-User-Input-via-input-raw_input).
If you are still experiencing issues with the Python extension, please raise a issue in the [Python git repo](https://github.com/DonJayamanne/pythonVSCode/issues), thanks.

_Similar to Microsoft/vscode#8765_
