### ISSUE TITLE
python test extra path

### ISSUE THREAD

**Issue by avdvir** [microsoft/vscode#98461]
Hi,
I'm trying to discover and run my test in my python project, but it failed due to the following reason:
The code itself placed in {workingDirectory}/src. The test code placed in {workingDirectory}/test. So the test code unable to import the source code. The solution is to add {workingDirectory}/src to the path, like the extraPath setting for auto complete.
So the feature request is either add extraPath setting to testing, or use the extraPath from auto complete when discover and run tests.

**Comment by kieferrm** [comment]
\extPython
