### ISSUE TITLE
Not able to run a python file on the terminal

### ISSUE THREAD

**Issue by TheKing003KS** [microsoft/vscode#98462]
Issue Type: <b>Performance Issue</b>

Whenever I try to run a python file on the terminal in VS Code it disappears after a second and the following message appears.
The terminal process terminated with exit code: 4294901760

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    75	 34292	code main
    0	    69	  2412	   shared-process
    0	    26	 17712	   utility
    0	   146	 27808	   gpu-process
    0	    14	 30552	   electron-crash-reporter
    0	   133	 31500	   window (Welcome - Visual Studio Code)
    0	    62	 23936	     extensionHost
    0	    68	 33180	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.5
python|ms-|2020.5.80290
cpptools|ms-|0.28.1
vscodeintellicode|Vis|1.2.7

</details>

**Comment by TheKing003KS** [comment]
Any idea on what's the issue & what should I do to solve it ??

**Comment by Tyriar** [comment]
Do you have anti-virus software that could be blocking the terminal? If so try following the instructions in https://code.visualstudio.com/docs/editor/integrated-terminal#_how-do-i-fix-the-errors-connectnamedpipe-failed-windows-error-232-or-terminal-exited-with-code-x-on-windows

/label "needs more info" integrated-terminal
