### ISSUE TITLE
java debug console code completion

### ISSUE THREAD

**Issue by jzdayz** [microsoft/vscode#98468]
hello,i try to write code on debug console.But i find no code completion.

- in java file

![image](https://user-images.githubusercontent.com/35563513/82756089-5e77ea00-9e0a-11ea-833e-f8c8fc88cec1.png)

- in java debug console

![image](https://user-images.githubusercontent.com/35563513/82756095-73ed1400-9e0a-11ea-8291-ae998cd97d17.png)

**Comment by kieferrm** [comment]
\extJava

**Comment by jzdayz** [comment]
> \extJava

Thanks i will report it to exjava
