### ISSUE TITLE
window.showTextDocument: Option for CustomTextEditorProvider

### ISSUE THREAD

**Issue by Paulomart** [microsoft/vscode#98473]
Given the following setup in an extension:

1. Custom TreeDataProvider and TreeView to display remote files
2. CustomTextEditorProvider for a specific file type (works for files from disk)
3. Custom TextDocumentContentProvider to load these remote files

I want to do the following:

When clicking an item in the TreeView I want to open that file in the CustomTextEditorProvider using the content from the Custom TextDocumentContentProvider.

Using an command I can listen for the click action and trigger the opening of the file:

```typescript
commands.registerCommand('myextension.openthething', async (resource: Uri) => {
  await window.showTextDocument(resource);
});
```

VSCode resolves the content from the URI using my custom content provider, but I only get the default Text Editor, not my CustomTextEditorProvider.

I also tried to use the same file extension (`.testfile`) in the resource URI as defined in the `filenamePattern`: (So that the URI passed into `await window.showTextDocument(resource);` ends with `.testfile`):

```json
{ "viewType": "myextension.editor",
  "displayName": "The editor",
  "selector": [{ "filenamePattern": "*.testfile" }]
}
```

That did not work either.

**My proposal**: Allow setting the `viewType` (CustomTextEditorProvider) in `showTextDocument`. VSCode would then use that custom editor to display the text document.

**Comment by mjbvz** [comment]
Try using the `vscode.openWith` command:

```ts
vscode.commands.executeCommand('vscode.openWith', resourceUri,  viewType, viewColumn);
```

`showTextDocument` returns a `TextEditor` so it always uses VS Code's standard text editor

**Comment by Paulomart** [comment]
@mjbvz Thanks for your response!

Using the command I can make it work, but the editor opens, only if the `filenamePattern` matches on the uri. Is there a way around that?

If not, how I match on the url scheme using the `selector` for the custom editor?

**Comment by mjbvz** [comment]
Just tested this again and it seems to work fine, even without any specific association for the editor. Let me know if you still see issues with `vscode.openWith`

**Comment by mjbvz** [comment]
For verification, here's the diff against the custom editor sample that I used to test

```diff
diff --git a/custom-editor-sample/package.json b/custom-editor-sample/package.json
index 1e4d019..a5687f8 100644
--- a/custom-editor-sample/package.json
+++ b/custom-editor-sample/package.json
@@ -14,7 +14,8 @@
 	"activationEvents": [
 		"onCustomEditor:catCustoms.catScratch",
 		"onCustomEditor:catCustoms.pawDraw",
-		"onCommand:catCustoms.pawDraw.new"
+		"onCommand:catCustoms.pawDraw.new",
+		"*"
 	],
 	"repository": {
 		"type": "git",
@@ -28,7 +29,7 @@
 				"displayName": "Cat Scratch",
 				"selector": [
 					{
-						"filenamePattern": "*.cscratch"
+						"filenamePattern": "*.bla"
 					}
 				]
 			},
diff --git a/custom-editor-sample/src/extension.ts b/custom-editor-sample/src/extension.ts
index fcd7d83..25960ae 100644
--- a/custom-editor-sample/src/extension.ts
+++ b/custom-editor-sample/src/extension.ts
@@ -9,4 +9,8 @@ export function activate(context: vscode.ExtensionContext) {
 	if (+vscode.version.match(/1\.(\d+)/)![1] >= 45) {
 		context.subscriptions.push(PawDrawEditorProvider.register(context));
 	}
+
+	vscode.commands.executeCommand('vscode.openWith',
+		vscode.Uri.joinPath(vscode.workspace.workspaceFolders![0].uri, 'a.xxx'),
+		'catCustoms.catScratch');
 }
```
