### ISSUE TITLE
Closing duplicate tab of file opens save prompt

### ISSUE THREAD

**Issue by shrfarzk** [Microsoft/vscode#9847]
- VSCode Version: 1.3.1
- OS Version: Windows 10 Version 1607 Build 14388

Steps to Reproduce:

1. Split editor
2. Open same file in left and right editors
3. Edit the file in one of the editors
4. Close the file in the second editor

Prompts to save file before closing, and if no is chosen, discards changes made in the first editor. 

Expected behavior is to only force choice between saving and losing the edits when closing the only remaining open instance of the file.

**Comment by stevencl** [comment]
Agreed. See https://github.com/Microsoft/vscode/issues/8983
