### ISSUE TITLE
VSCode installs wrong version of extension

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#98472]
## Info
- VSCode Version: 1.46.0-insider
- OS Version: Ubuntu 20.04

## Steps to Reproduce:

[simplescreenrecorder-2020-05-24_19.41.22.zip](https://github.com/microsoft/vscode/files/4674090/simplescreenrecorder-2020-05-24_19.41.22.zip)

Here is a screencast where I install version 0.1.3 of auto-rename-tag in vscode and in vscode-insiders. But the version 0.1.3 that I install with VSCode insiders isn't actually version 0.1.3. It is an older version that doesn't include the fix for https://github.com/formulahendry/vscode-auto-rename-tag/issues/535 and https://github.com/formulahendry/vscode-auto-rename-tag/issues/540
At the end you can see me comparing the source code of `~/.vscode/extensions/formulahendry.auto-rename-tag-0.1.3/packages/server/dist/serverMain.js` and `~/.vscode-insiders/extensions/formulahendry.auto-rename-tag-0.1.3/packages/server/dist/serverMain.js` which should be the same since it is the same extension version but it's different.

Does this issue occur when all extensions are disabled?: No

https://github.com/microsoft/vscode/issues/98366 might be related

**Comment by sandy081** [comment]
I tried it on latest stable and insiders and installed 0.1.3 version and I see both are same. 

May I know are you still seeing this issue?

**Comment by SimonSiefke** [comment]
I've been using v0.1.5 for some time now which has been working fine. I'll guess it's fair to close this issue and I open a new one if it occurs again.
