### ISSUE TITLE
Explorer disappears when I click on other action on the left panel

### ISSUE THREAD

**Issue by jojoforce** [microsoft/vscode#98478]
Explorer disappears when I click on other action on the left panel (i.e. Source Control, Extensions) or when you try to click "Explorer" itself.
![image](https://user-images.githubusercontent.com/24530217/82764728-0081dd00-9ddf-11ea-9459-b82dd454f9af.png)

**Comment by jojoforce** [comment]
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
Does it happen if you reload with all extensions disabled? There's a command on the Command Palette for doing this.

**Comment by jojoforce** [comment]
I disabled all extensions via the command palette (Extensions: Disable All Installed Extensions) and reloaded VS Code, and yes it still happens.

**Comment by gjsjohnmurray** [comment]
@sbatten any ideas?

**Comment by sbatten** [comment]
@jojoforce please right click the activity bar and show the contents of this menu
![image](https://user-images.githubusercontent.com/6561887/82930406-2e2f6900-9f3a-11ea-8836-e8dcbcbce037.png)

**Comment by jojoforce** [comment]
![image](https://user-images.githubusercontent.com/24530217/82930594-a22a3b00-9f53-11ea-8326-8f08f4571e64.png)

**Comment by sbatten** [comment]
@jojoforce this menu does not have a check next to Explorer indicating that the view container is not pinned. That means it will only be shown when focused either on startup or through keyboard shortcuts. In that menu, select explorer to recheck it and it should stay visible when you select other icons in the activity bar.

**Comment by jojoforce** [comment]
Thank you! It's strange though as the behavior seems to just have recently changed, when I go to View-->Explorer that would "pin" the view container by default - but then when I click, the Explorer on the Activity bar, it disappears. But it resolved my issue.

**Comment by sbatten** [comment]
@jojoforce we did not change any behavior. it should be pinned by default. my hunch is that some action you took unpinned it and now you need to repin following the steps above. If many others start reporting this, then perhaps there is a bug causing unpinning, but so far, I have not seen other reports.
