### ISSUE TITLE
Keybindings: weird search result

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98489]
Steps to Reproduce:

1. open keybindings editor
2. search for `alternativeAcceptSelectedQuickOpenItem`

=> 🐛 you see a lot of results?

![image](https://user-images.githubusercontent.com/900690/82779903-b982fe80-9e55-11ea-8ef9-ccc081542e78.png)

**Comment by IllusionMH** [comment]
Same for `altqweasdzcx`, `ctrlqweasdzcx`, and `shiftqweasdzxc`
On Windows it's clearly highlighting modifier key if it's in the beginning of the search.

**Comment by Toppole69** [comment]
```

```
