### ISSUE TITLE
Add waitForExit API to TaskExecution

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode#98483]
Currently there is no trivial way to wait for a TaskExecution to be completed. Before 1.44, there was a way to do this using `onDidEndTaskProcess`, however as of 1.44 this is broken, and a still open bug report (https://github.com/microsoft/vscode/issues/96643). Instead of needing to do workarounds with callbacks and condition variables to wait for a task to complete, a much simpler solution would be to add a `waitForExit(cancel: CancellationToken): Thenable<number>` api directly to `TaskExecution`. This would allow an easy way to wait for a process to exit, without needing to go through callback nightmares, especially when those callbacks break.

**Comment by meganrogge** [comment]
This should not be needed when https://github.com/microsoft/vscode/issues/96643 is fixed
