### ISSUE TITLE
"Copy Line Down" behaves strangely

### ISSUE THREAD

**Issue by nosynose** [microsoft/vscode#98482]
Steps:
1. Open a file
2. Use Shift-Alt-DownArrow to copy a line down.
3. Edit the copied line. type something, delete something or highlight something.

Issue: 
Frequently, a duplicate cursor will appear in an adjacently line and any editing you make to the currently line is duplicated in that line. Closing and reopening the file sometimes works and sometimes doesn't. Closing and re-opening Code fixes the problem. this does not happen every time. But it is frequent enough that I have to bounce Code multiple times per hour.

**Comment by CMarshall92** [comment]
If you are still holding alt this adds a second cursor to the text editor I wonder if that's the issue where its sometimes adding a second cursor.

**Comment by CMarshall92** [comment]
Just to confirm you weren't actively holding any key when you were selecting or type were you?

**Comment by nosynose** [comment]
Sorry for late reply.

Regarding the question "If you are still holding alt this adds a second
cursor to the text editor I wonder if that's the issue where its sometimes
adding a second cursor."

Yes, the problem is exactly that the feature you mentioned was triggered.
But it could not be an human error unless I have 2 left hands: my mouse is
left-handed and Shift-Alt-Up/Down uses left-Alt.
