### ISSUE TITLE
Select word at caret support (ctrl +w ) like Android Studio

### ISSUE THREAD

**Issue by pMertDogan** [microsoft/vscode#98480]
Hi, i use Android Studio for Flutter / Dart development and its great . I use it because its has awesome shortouts like ctrl + w ( Select word at caret ) . I like VS Code too but its not have this feature.

Alt+Shift+Arrow is terrible for selection. Is it possible add Android Studio 's  Select word at caret feature to VS Code? 

Its would be really helpfull ! 

Thanks.

**Comment by IllusionMH** [comment]
You can remap it in Keyboard Shortcuts view with ease.

Ctrl+W was used for a long time and also consisten with browsers, so I don't think it would be changed for all.

**Comment by pMertDogan** [comment]
I dont want VS Code remap ctrl +w .I just want Android Stuido ctrl+w feature .

**Comment by IllusionMH** [comment]
Please describe how is it different from `Alt+Shift+Arrow` in VS Code when cursor is in the middle of the word?

**Comment by pMertDogan** [comment]
I recorded video about my issue

Left VS Code ( shift+ alt + arrow )   , Right Android Studio ( ctrl + w )
Video link:
https://1drv.ms/u/s!An33J1c1rPZhhaVoFyJ4uGOoqj1HNQ?e=ugqOPj
