### ISSUE TITLE
Don't recommend extension base on apps installed on user's computer

### ISSUE THREAD

**Issue by ck97756** [microsoft/vscode#98485]
![圖片](https://user-images.githubusercontent.com/4375298/82775466-62435500-9e7a-11ea-9887-d403d980db09.png)

How do vscode know what App is on my computer?
Does microsoft collect these info?
If it does, can I disable this feature?

**Comment by ck97756** [comment]
Story:
I have firefox installed on my computer.
And I found out that vscode recommend extension "Debugger for Firefox" for me.
Since I didn't open any file relate to firefox development.
I'm concern about my privacy about what app I've installed, even what's on my computer

**Comment by sketchbuch** [comment]
Maybe check if you have an extensions.json file in the .vscode folder, extension recommendations can come from that file.

https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions

**Comment by ck97756** [comment]
No, both {home}/.vscode and {workspace}/.vscode don't have extension.json.
![圖片](https://user-images.githubusercontent.com/4375298/82884237-0eb63180-9f76-11ea-9a09-aa54491e2ad0.png)
And it says "because you have Mozilla Firefox installed"

**Comment by sketchbuch** [comment]
Also if you hover over the extension that is recommended the tooltip will tell you why it was recommended

**Comment by sketchbuch** [comment]
Maybe they do check your apps :/

**Comment by sketchbuch** [comment]
In the settings it says that "some recommendations are fetched from a microsoft online service"... maybe if you have windows and install apps via the app store this information is queried by VSCode

**Comment by ck97756** [comment]
Firefox is install by the installer downloaded from Mozilla.
I don't think Mozilla will provide microsoft such info

**Comment by ck97756** [comment]
They do parse your folder
I found the code

extensionTipsService.ts

`
	private async getValidExecutableBasedExtensionTips(executableTips: 
IStringDictionary<IExeBasedExtensionTip>): Promise<IExecutableBasedExtensionTip[]> {

		const result: IExecutableBasedExtensionTip[] = [];
		const checkedExecutables: Map<string, boolean> = new Map<string, boolean>();
		for (const exeName of Object.keys(executableTips)) {
			const extensionTip = executableTips[exeName];
			if (!isNonEmptyArray(extensionTip?.recommendations)) {
				continue;
			}

			const exePaths: string[] = [];
			if (isWindows) {
				if (extensionTip.windowsPath) {
					exePaths.push(extensionTip.windowsPath.replace('%USERPROFILE%', processEnv['USERPROFILE']!)
						.replace('%ProgramFiles(x86)%', processEnv['ProgramFiles(x86)']!)
						.replace('%ProgramFiles%', processEnv['ProgramFiles']!)
						.replace('%APPDATA%', processEnv['APPDATA']!)
						.replace('%WINDIR%', processEnv['WINDIR']!));
				}
			} else {
				exePaths.push(join('/usr/local/bin', exeName));
				exePaths.push(join(this.environmentService.userHome.fsPath, exeName));
			}

			for (const exePath of exePaths) {
				let exists = checkedExecutables.get(exePath);
				if (exists === undefined) {
					exists = await this.fileService.exists(URI.file(exePath));
					checkedExecutables.set(exePath, exists);
				}
				if (exists) {
					extensionTip.recommendations.forEach(recommendation => result.push({
						extensionId: recommendation,
						friendlyName: extensionTip.friendlyName,
						exeFriendlyName: extensionTip.exeFriendlyName,
						windowsPath: extensionTip.windowsPath,
					}));
				}
			}
		}

		return result;
	}
`

**Comment by rob3c** [comment]
This seems to be more privacy-violating telemetry that isn't actually disabled when setting the global `Enable Telemetry` setting to false. It may be because they choose not to define it as "telemetry", similar to the experiments-related behavior that was addressed in another recent issue.

While I can appreciate an argument for having the setting to disable this to be separate from the global one, I think the ethical thing to do would be to still have it appear in the settings results when users search for telemetry settings. That would avoid any appearance of bad faith on the part of Microsoft, since I'm sure many users trying to disable telemetry don't expect vscode to continue to snoop around their computer's file system after disabling the only obvious settings.

**Comment by chrisdias** [comment]
We don't send anything back in telemetry here, it all happens on the desktop in an attempt to provide users with recommendations of useful extensions based on what they have installed.
