### ISSUE TITLE
typescript service dies

### ISSUE THREAD

**Issue by jikanter** [microsoft/vscode#98486]
Issue Type: <b>Bug</b>

open js file. typescript service dies multiple times (>5). 

JS File content:

const listener = Deno.listen({port:8081})
console.log("listening on 0.0.0.0:8080")
for await (const conn of listener) { 
  Deno.copy(conn, conn)
}

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|README.md|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.12.0
npm-intellisense|chr|1.3.0
jshint|dba|0.10.21
xml|Dot|2.5.0
vscode-npm-script|eg2|0.3.11
beautify|Hoo|1.5.0
vue|jcb|0.1.5
intellij-idea-keybindings|k--|0.2.40
vscode-docker|ms-|1.2.0
python|ms-|2020.5.80290
cpptools|ms-|0.28.1
debugger-for-chrome|msj|4.12.8
vscode-react-native|msj|0.16.0
vetur|oct|0.24.0
java|red|0.62.0
vscode-xml|red|0.11.0
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.1
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.22.4
vscode-maven|vsc|0.21.4
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.7.1

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? 

Also, are you using the Deno TypeScript plugin?
