### ISSUE TITLE
Javascript Debug preview for package.json will on use the root directory??

### ISSUE THREAD

**Issue by Lee182** [microsoft/vscode#98481]
Javascript Debug preview for package.json will on use the root directory. It should be what file is active.

- VSCode Version: 1.45.1
5763d909d5f12fe19f215cbfdd29a91c0fa9208a
x64
- OS Version: Windows 10

Steps to Reproduce:
https://giphy.com/embed/THrfY15EbFtiwdz9IT

1. Goto nested package.json
2. Click debug
Bug. See the list for debugging root/package.json and not root/nested/package.json

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by connor4312** [comment]
Thanks for the issue!
