### ISSUE TITLE
Gulpfile.js new tasks not immediately recognised

### ISSUE THREAD

**Issue by markduk** [Microsoft/vscode#9849]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:
1. Create a new gulp file and add some tasks
2. Tasks are not immediately available to run
3. Creating or updating .vscode\tasks.json appears to cause a refresh and the task become available in the task runner  (Ctrl + Shift + P  =>  Run Task  =>  {new tasks appear}

**Comment by mwhite2386** [comment]
I second this. I've been using command line to execute my new task. If I close VS Code and start it back up, it shows all my tasks

**Comment by dbaeumer** [comment]
Currently the task framework doesn't watch the gulfile.

**Comment by Beofett** [comment]
This continues to be an issue.  It is disruptive to my workflow as I develop my gulp tasks for my dev environment.

**Comment by mtycholaz** [comment]
+1

**Comment by dbaeumer** [comment]
[Addressed in new terminal runner]

This is addressed in the new terminal runner. Gulp auto detection watches gulpfiles in this case. See https://code.visualstudio.com/updates/v1_10#_task-support

**Comment by dbaeumer** [comment]
Closing since this got addressed in the new terminal runner which is now the default.
