### ISSUE TITLE
Terminal window opens but no prompt is shown on Windows 10

### ISSUE THREAD

**Issue by ReddyKilowatt** [microsoft/vscode#98491]
Issue Type: <b>Bug</b>

I'm running VScode in a docker container on Windows 10.
When I click view terminal, the window for the terminal opens but no prompt is shown.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (1.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
vscode-docker|ms-|1.2.0
python|ms-|2020.5.80290
remote-wsl|ms-|0.44.2

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal

**Comment by ReddyKilowatt** [comment]
Hello Daniel

I've attached a screenshot

**Comment by Tyriar** [comment]
@ReddyKilowatt image attachments don't work via email, you'll need to go to github.com to attach it.
