### ISSUE TITLE
Codicon: font-size property can easily get overwritten

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98495]
I am shuffling around code and noticed that codicons can easily inherit a bad `font-size` because their rule is not very specific. To reproduce:

* `git co ben/98495`
* run out of sources

=> 🐛 

![image](https://user-images.githubusercontent.com/900690/82783659-32d31f00-9e5f-11ea-84a4-1cb39ec42d6e.png)

It looks like this small change is enough to put this rule above codicons:

![image](https://user-images.githubusercontent.com/900690/82783702-467e8580-9e5f-11ea-842e-4f80561b2b3b.png)

Usually the first one is below the other, but this can break very easily.

**Comment by bpasero** [comment]
@misolori can we move this to a milestone, this will block our effort of sandboxing VSCode.

**Comment by misolori** [comment]
@bpasero I'll take a look this week to see what we can do. I'm assuming we only want codicons to change in font-size when explicitly set like `.monaco-action-bar .action-label .codicon`?

**Comment by bpasero** [comment]
I did not look deeply into it but suspect that this is simply a CSS ordering problem that can be fixed by making the one rule more specific to win.

**Comment by misolori** [comment]
Ok, so it looks like if I move the `actionbar.css` link ref to the bottom of the head element in the inspector (so it's the last one that loads) it will show this state. Adding `.monaco-workbench` to the codicons file seems to fix this. Will commit this shortly.

**Comment by bpasero** [comment]
One thing to keep in mind is that `.monaco-workbench` can only be added on the layer of the `workbench`, not `base` because we use `base` also for the standalone editor without workbench.

**Comment by misolori** [comment]
hmm...that does it make it trickier. Let me see how else I can make these classes specific w/out using `.monaco-workbench `

**Comment by misolori** [comment]
After looking into this it seems that we either need to have a parent container for codicons (we'd need to update all references), a parent class added to the body element, or reference both `.monaco-workbench` and `.monaco-editor` (very ugly).

@aeschli thoughts?

**Comment by bpasero** [comment]
@misolori if it helps, we put workbench specific stuff here: `src/vs/workbench/browser/media/style.css`

**Comment by misolori** [comment]
@bpasero thanks, that does help and would minimize the changes (and appears to work).
