### ISSUE TITLE
ctrl+shift+u is unusable as a shortcut key binding

### ISSUE THREAD

**Issue by jjssoftware** [microsoft/vscode#98506]
- VSCode Version: 1.45.1
- OS Version: Linux Mint 18.3

Steps to Reproduce:

1. Start VS code
2. Open Keyboard shortcuts
3. Attempt to assign ctrl+shift+u to any existing command
4. Verify that the keys pressed are recognised as ctrl+shift+unknown
5. Verify that attempting to save the key press sequence fails and that that the shortcut key binding is unusable

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
AFAIK, caused by the OS.

Duplicate of #96536
Duplicate of #81955
Duplicate of #73003

**Comment by jjssoftware** [comment]
It looks like you need a "can't fix / won't fix" label.
