### ISSUE TITLE
extension API: select source control provider on the list

### ISSUE THREAD

**Issue by ppkwiatkowski** [microsoft/vscode#98509]
It would be useful to have more control over built-in source control providers list, because sometimes it is unclear, which repository will end up being selected :)

Source control providers list seems to remember last selected repository on the reload, unless the list is actually opened during the vscode initialization - in which case, for some reason there are two repositories selected (last selected and first one).

Allowing to select them through API would allow for more integration between extensions and built-in git functionalities.

**Comment by joaomoreno** [comment]
We're trying to get away from the SCM Providers list and the notion of a single selected repository, so this would lock us in even more. Closing it as out of scope.
