### ISSUE TITLE
Can't scroll in the terminal

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9850]
- OS Version: macOS

**Comment by Tyriar** [comment]
Can you repro in stable? Are you using zsh or oh-my-zsh?

**Comment by joaomoreno** [comment]
Can also repro in stable. Yes, using oh-my-zsh. Happens to both me and @egamma, we both use it.

**Comment by wallverb** [comment]
https://github.com/Microsoft/vscode/issues/7817 https://github.com/sourcelair/xterm.js/issues/151
