### ISSUE TITLE
change the code-language of tag-content in html files

### ISSUE THREAD

**Issue by xatian** [microsoft/vscode#98507]
If I open an html-file in VS-code I get nice syntax-highlighting since the content is treated as HTML. But depending on tags the language used inside the tag to highlight the code is changed.

```
<p>This is treated as HTML</p>
<script>
    Everything inside this tag is treated as Javascript.
</script>
<style>
    Everything inside this tag is treated as CSS.
</style>
<script type="unknown">
    Everything inside this tag is treated as HTML.
</script>
<script type="module">
    Everything inside this tag is treated as Javascript.
</script>
```

Is it possible to register a custom tag tied to a language?

What I actually want is `<script type="text/typescript">` that changes the language inside to Typescript. If that is not possible I would also settle for a `<typescript>` tag since my "build-process" will process this node anyways. Maybe that is already possible somehow?
If not please add it.
Thank you!

**Comment by aeschli** [comment]
The syntax highlighting comes from the HTML textmate grammar. The new types need to be added there.

**Comment by alexr00** [comment]
Moved to owning repo: https://github.com/textmate/html.tmbundle/issues/110

**Comment by alexr00** [comment]
Closing in favor of the upstream issue.
