### ISSUE TITLE
config.resolve.alias in configurewebpack compilation error

### ISSUE THREAD

**Issue by xyzgy** [microsoft/vscode#98505]
Issue Type: <b>Bug</b>

config.resolve.alias in configurewebpack ,  '@assets' or  '@store' compilation error except for '@components' 

![image](https://user-images.githubusercontent.com/21964169/82796332-f0820000-9ea7-11ea-986c-7d220e60540f.png)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.45.1
vetur|oct|0.24.0

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

What is your path configuration in`tsconfig.json`/`jsconfig.json`?

VS Code (TS) have no info about your custom aliases. You need to properly configure them in `tsconfig.json`/`jsconfig.json`.
https://code.visualstudio.com/docs/languages/jsconfig#_using-webpack-aliases
