### ISSUE TITLE
terminal can't input anything!!!

### ISSUE THREAD

**Issue by jackyPang10086** [microsoft/vscode#98501]
Issue Type: <b>Bug</b>

when i open the vs code,i found terminal can't input anything!!!

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 4.15.0-30deepin-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|7.66GB (0.48GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|deepin|
|XDG_CURRENT_DESKTOP|Deepin|
|XDG_SESSION_DESKTOP|deepin|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.5.80290
markdown-preview-enhanced|shd|0.5.9
markdown-all-in-one|yzh|3.0.0

</details>

**Comment by jackyPang10086** [comment]
i found if i click the vs code icon in the linux dock,This kind of problem will occur.
and if i click the icon in the desktop,this problem couldn't occer.
ps: My Linux distribution is deepin,i change from default dock to plank

**Comment by Tyriar** [comment]
Please provide a screenshot illustrating the problem and your settings.json file. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/needsMoreInfo
