### ISSUE TITLE
use ctrl + click jump to definition as deep as pycharm can do

### ISSUE THREAD

**Issue by fitzlm** [microsoft/vscode#98518]
Vscode can't jump to definition as deep as pycharm can do.

For example:
```python
from django.shortcuts import render
```

when i use 'command + click' on "render", it can jump to the render function, but when 
i click the method "render_to_string()" inside render function, it can not jump to definition any more, the following is the code snippet:

```python
def render(request, template_name, context=None, content_type=None, status=None, using=None):
    content = loader.render_to_string(template_name, context, request, using=using)
    return HttpResponse(content, content_type, status)
```

But when i use pycharm, it can jump to the definition of "render_to_string()" function. So sometimes i need to toggle between vscode and pycharm once i want to view more definition, I feel shame vscode does not have this function. If vscode
can add this feature, it would great!

**Comment by kieferrm** [comment]
\extPython

**Comment by fitzlm** [comment]
> \extPython
ok, thanks!
