### ISSUE TITLE
Add possibility to copy text selected with ctrl-A from a debug hover

### ISSUE THREAD

**Issue by wonkoRT** [microsoft/vscode#98511]
It seems like there are two different selections possible in the debug-hover:
- ctrl+A selects everything with a dark blue.
- When selecting some text in the hover with the mouse (i.e. press the left mouse button while near/over a char, move mouse, release left mouse button) the selected text is shown in a lighter and brighter blue.

- The two selections can coexist.
- Ctrl-C always copies the text selected with the mouse, or nothing if there's no such selection, no matter whether a ctrl-A selection also has been done.
- If there's only a ctrl-A selection, ctrl-C doesn't copy anything.
- The two selections can be selected in any order. The order doesn't change the behavior.

![image](https://user-images.githubusercontent.com/2768898/82740165-8867d880-9d46-11ea-945c-c9aa8fa9676e.png)

In the above screenshot, ctrl-C puts the following in the clipboard:

```
ction:"close"
content-enco
```

Here's the same hover without any selection:
![image](https://user-images.githubusercontent.com/2768898/82740336-3627b700-9d48-11ea-892e-db0767e77506.png)

And here with just the ctrl-A selection:
![image](https://user-images.githubusercontent.com/2768898/82740362-5c4d5700-9d48-11ea-9b85-9b3423e1c67e.png)

_Originally posted by @wonkoRT in https://github.com/microsoft/vscode/issues/63296#issuecomment-633138710_

**Comment by isidorn** [comment]
Copy all selection is simply not implemented in the debug hvoer.
Nad yeah we show the native selection and the tree selection.
We have a similar issue in the debug console.
For now leaving this open as a feature request and assigning to backlog. Thanks

**Comment by ShadowSmog** [comment]
Gdhehensnen
