### ISSUE TITLE
Weird editor focus when clicking in dev tools

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#9851]
While verifying #9759 I noticed that I can get vscode into a weird focus state. E.g both editors have focus and I see two cursors, or that the TS context menu actions are never present (due to the lack of focus I believe).
As explained in #9759,  open a TS writeable file, open dev tools (click something there), right click in the ts writeable file. Notice that sometimes the TS context menu actions are missing (and they do not return until a new file is opened) or two cursors can appear in different editors.

**Comment by jrieken** [comment]
I could repo with the dev tools but not with other windows or the part like the explorer/webview... The context menu is very special as it uses a stop the world approach.

**Comment by isidorn** [comment]
Oh yeah I forgot that electron context menu freezes everything...

**Comment by jrieken** [comment]
Yeah - as 'expected'
