### ISSUE TITLE
add-ons Go

### ISSUE THREAD

**Issue by Kur-Ich** [microsoft/vscode#98510]
I'm getting daily notifications that I'm missing some add-ons for Go. It would be nice if you could select in Settings which add-ons you want to use and which ones not, I really don't want to use formatting type add-ons for example which auto format the code in a certain way preferred by the language. Also an explanation would be nice of what the add-on exactly does so that it would be easy to select which ones you want. Currently a lot of Go extensions got automatically installed and it is not clear what they do.

**Comment by kieferrm** [comment]
\extGo
