### ISSUE TITLE
${workspaceFolder} does not work well in .env file, but "${workspaceFolder}." works

### ISSUE THREAD

**Issue by Haibao425** [microsoft/vscode#98519]
MacOS: 10.15.4

All VS Code versions.

**Add below strings in .env:**
_PYTHONPATH = ${PYTHONPATH}:${workspaceFolder}
PYTHONPATH = ${PYTHONPATH}:${workspaceFolder}./module2_

**and then Python sys.path shows that the path of module2 is correct, like below**
_0:'/Users/xxx/Projects/Python'
1:'/Users/xxx/Projects/Python/module2'_

----------------------------------------------------------------------------------------
**But if Add below string in .env:**
_PYTHONPATH = ${PYTHONPATH}:${workspaceFolder}
PYTHONPATH = ${PYTHONPATH}:${workspaceFolder}/module2_

**and then Python sys.path shows that the path of module2 is correct, like below**
_0:'/Users/xxx/Projects/Python'
1:'/module2_

What's is the different between "${workspaceFolder}" and "${workspaceFolder}."? "." means some thing?

**Comment by kieferrm** [comment]
\extPython
