### ISSUE TITLE
Extension does not install, caught in an endless loop

### ISSUE THREAD

**Issue by michaelpumo** [microsoft/vscode#98525]
Issue Type: <b>Bug</b>

Trying to install Version Lens extension (https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens). I previously had this installed but noticed it had (for some reason) disappeared. I tried installing this again and got this endless loop.

I quit VS Code, deleted the extension from the `.vscode/extensions` folder from my system and tried again with no luck.

See a video I recorded of my screen showing this endless loop: https://streamable.com/y6irdt

No other extensions appear to have been affected by whatever is causing this (that I am aware of anyway).

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (5.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-custom-css|be5|3.0.9
better-toml|bun|0.3.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
vscode-babel-coloring|dza|0.0.4
gitlens|eam|10.2.1
EditorConfig|Edi|0.15.1
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
carbon-now-sh|eri|1.2.0
prettier-vscode|esb|4.7.0
vue-snippets|hol|0.1.11
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-duplicate|mrm|1.2.1
mssql|ms-|1.9.0
language-liquid|nei|0.1.1
vetur|oct|0.24.0
indent-rainbow|ode|7.4.0
vscode-graphql|Pri|0.2.14
synthwave-vscode|Rob|0.1.5
stylelint|shi|0.51.0
svg-preview|Sim|2.8.3
vsfire|tob|1.4.1
twig|wha|1.0.2
vscode-import-cost|wix|2.12.0

(5 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
/duplicate

#98366
