### ISSUE TITLE
Zen Mode Git-Compare breaks single editor

### ISSUE THREAD

**Issue by Twiggeh** [microsoft/vscode#98526]
Issue Type: <b>Bug</b>

1. open 3 editors side by side
2. enter zen
3. open Source control and compare any file.
4. exit zen
5. close 2 editors, so that only one remains open
6. [Result](https://cdn.discordapp.com/attachments/694508622519992350/714490150360580137/unknown.png)

I can't get it unstuck. Restart of code & system didn't help. Whenever it's in more than 1 editor mode it works like expected. 

VS Code version: Code - OSS 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-23T19:32:05.786Z)
OS version: Linux x64 5.4.40-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1800X Eight-Core Processor (16 x 3699)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.65GB (9.13GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Twiggeh** [comment]
Apparently it gets stuck in a mode called "Centered Layout" and you can toggle that from the command palette.

**Comment by isidorn** [comment]
Please use this setting if you want to disable this behavior 	"zenMode.centerLayout": false,
