### ISSUE TITLE
Location of buttons in a git diff

### ISSUE THREAD

**Issue by djdongjin** [microsoft/vscode#98523]
Currently, when you press a git diff icon around the line numbers, the git diff bar will pop up, with all buttons (stage, revert, close) located at the right end of the bar, which I think is quite inefficient, because you have to click in the left end to show such a git diff bar and move to the right end to select the action you want. If you want to see multiple git diffs, you have to move left and right multiple times.

![Xnip2020-05-25_10-42-11](https://user-images.githubusercontent.com/28295179/82822822-6b312800-9e74-11ea-8f23-ccc9c4057e3f.jpg)

Is it a good idea to move these buttons close to the left end, or is there an existing way, to facilitate such an action flow?

Thanks!

**Comment by joaomoreno** [comment]
@jrieken Should we do this for every peek?

I have a feeling I've seen this in the past.

**Comment by jrieken** [comment]
this hasn't come up for other peeks, but I remember that it did occur for inline diff... I also still think that moving the left is bogous and unseen in our UI.

**Comment by joaomoreno** [comment]
@djdongjin Yeah I'm not too keen on moving these around, especially to the left of the labels, since it would misalign them. I suggest to just use the keyboard to run those actions instead of using the mouse for that.
