### ISSUE TITLE
.html 

### ISSUE THREAD

**Issue by RohitKamineni** [microsoft/vscode#98528]
the .html file extension is not being recognised by vs code for editing html.

**Comment by mxrachel** [comment]
What do you mean by not recognised? What version of are you using? What Operating System? What happens when you try to open the File with <kbd>Ctrl</kbd>+<kbd>O</kbd> or <kbd>Cmd</kbd>+<kbd>O</kbd>?

**Comment by RohitKamineni** [comment]
I created a new file "index.html" but the editor does not recognize the file as a HTML doc and the snippets don't work. Saving it as .htm instead seems to solve the issue. I'm guessing maybe one of the extensions I downloaded is interfering with the natural process. Will update once I can try and find out whats wrong

**Comment by egamma** [comment]
>I created a new file "index.html" but the editor does not recognize the file as a HTML doc

What is shown in the bottom left of the status line. Does the editor recognise the file as a HTML file, as shown below?

![image](https://user-images.githubusercontent.com/172399/82931074-a1f76300-9f86-11ea-9eb3-a75263187e03.png)

If this is the case then I suspect you are using an extension that contributes has an issue in the way it contributes the snippet.
