### ISSUE TITLE
Renaming multiple files and automatically Updating Imports doesn't work properly

### ISSUE THREAD

**Issue by kidsil** [microsoft/vscode#98529]
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 4.4.0-142-generic

Steps to Reproduce:

1. Open a project that uses file imports (mine was ReactJS)
2. Rename a file that gets imported by other files with F2
3. When the "Update imports for 'NEW_FILE_NAME'?" pops up, click "Yes"
4. Without saving the opened files, rename another file using F2
5. Again, click "Yes" for the "Update imports..." dialog
6. Import renaming will mix lines won't work properly at all, creating syntax errors in the process.

**Comment by mjbvz** [comment]
Can you please share a specific project that causes this

Also, does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?
