### ISSUE TITLE
i cant see suggestions

### ISSUE THREAD

**Issue by mtbun** [microsoft/vscode#98537]
hello, suggestions looking (----). i cant see commands
for example(css):
 when i write mar(-------
                              --------
                              --------
                              --------                         
                              --------
                              --------
                              --------
                              --------
                              --------)

bug link: https://hizliresim.com/jHqdQr

how can i fix it?

**Comment by mtbun** [comment]
I forgot to write. this problem in os x

**Comment by aeschli** [comment]
Looks like #98280
