### ISSUE TITLE
I cannot type áéíóú in integrated terminal

### ISSUE THREAD

**Issue by adelgar** [microsoft/vscode#98533]
Issue Type: **Bug**

When I type accented vowels (áéíóú) in the integrated terminal (only in terminal) the vowels appears without accent (aeiou). 

If I use the "locale" command I get:

 > LANG=es_ES.UTF-8
> LANGUAGE=es_ES
> LC_CTYPE="es_ES.UTF-8"
> LC_NUMERIC="es_ES.UTF-8"
> LC_TIME="es_ES.UTF-8"
> LC_COLLATE="es_ES.UTF-8"
> LC_MONETARY="es_ES.UTF-8"
> LC_MESSAGES="es_ES.UTF-8"
> LC_PAPER="es_ES.UTF-8"
> LC_NAME="es_ES.UTF-8"
> LC_ADDRESS="es_ES.UTF-8"
> LC_TELEPHONE="es_ES.UTF-8"
> LC_MEASUREMENT="es_ES.UTF-8"
> LC_IDENTIFICATION="es_ES.UTF-8"
> LC_ALL=

My terminal works properly and only have this issue with the integrated terminal.

VS Code Version: 1.45.1 ([5763d90](https://github.com/microsoft/vscode/commit/5763d909d5f12fe19f215cbfdd29a91c0fa9208a), 2020-05-14T08:27:22.494Z)
OS: Linux x64 5.3.0-53-generic (Linux Mint 19.3 Cinnamon)

**Comment by Tyriar** [comment]
/duplicate https://github.com/xtermjs/xterm.js/issues/2479, https://github.com/xtermjs/xterm.js/issues/2151
