### ISSUE TITLE
C Language Mode doesn't work properly with WSL

### ISSUE THREAD

**Issue by polt13** [microsoft/vscode#98531]
I'm writing C code on VSCode using the C Language mode, through WSL. With C++ language mode select on my files the highlighting works properly, even on WSL. It looks like this:
![image](https://user-images.githubusercontent.com/59566389/82839191-3b673c00-9ed7-11ea-84a1-2564efbcab3b.png)
However, if I select C language mode, highlighting doesn't work and looks like this:
![image](https://user-images.githubusercontent.com/59566389/82831542-5b8c0080-9ec1-11ea-86f1-fa71ba1fe3f5.png)

Without WSL it seems to work on both modes, both C language mode and C++. I spent a good deal of time today, trying to get it to work with C language mode and I couldn't, so I'd appreciate if you could lead me to a solution. Thank you!

- VSCode Version: 1.45.1
- OS Version: Windows 10, Build 1909

Steps to Reproduce:

1. Launch WSL window on VSCode
2. Open any C file and select C language mode

Does this issue occur when all extensions are disabled?: No

E: Forgot to mention I have the official C/C++ extension installed on both WSL and local
E2: Just noticed that, even with C++ language certain definitions don't get highlighted
e.g.
![image](https://user-images.githubusercontent.com/59566389/82832374-89724480-9ec3-11ea-864d-f4b734e5038f.png)

**Comment by mxrachel** [comment]
Does this happen with all extensions disabled? Otherwise this is an issue for the  [C/C++ Tools repo](https://github.com/Microsoft/vscode-cpptools).

**Comment by polt13** [comment]
> Does this happen with all extensions disabled? Otherwise this is an issue for the [C/C++ Tools repo](https://github.com/Microsoft/vscode-cpptools).

It seems to be happening regardless of extensions.

**Comment by mxrachel** [comment]
Could you post a short bit of code or create a repo that can be used to repro this?

**Comment by polt13** [comment]
@mxrachel  Even this little snippet of code doesn't properly work for me on C Lang mode, it doesn't highlight any of the typedefs on WSL (on non WSL all is fine).

`#ifndef`` GRAPH_H
#define GRAPH_H
#define MAXVERTEX 20

typedef enum {FALSE, TRUE} Boolean;

typedef int Vertex;

typedef struct edge {
   Vertex endpoint;
   struct edge *nextedge;
} Edge;

typedef struct graph {
   int n;     /* number of vertices in the graph */
   Edge *firstedge[MAXVERTEX];
} Graph;
Graph Initialize(Graph);
Edge CreateEdge(Vertex,Vertex,Edge*,Edge*);
Graph InsertEdge(Graph,Edge);
void ShowGraph(Graph);
void DepthFirst(Graph);
void traverse(Graph,int);
#endif`.. With C++ lang mode it highlights most, but still, not all.

**Comment by kieferrm** [comment]
@polt13, do I understand correctly: While the C/C++ extension is disabled  both locally and in WSL, the syntax highlighting you see locally differs from the one in WSL for the same file?

**Comment by polt13** [comment]
That is correct @kieferrm

**Comment by kieferrm** [comment]
Thank you. Since this is related to the C/C++ extension, it should be addressed there.

**Comment by kieferrm** [comment]
\extC
