### ISSUE TITLE
Auto merge option for save conflict resolution

### ISSUE THREAD

**Issue by melancthon** [microsoft/vscode#98532]
In the Visual Code settings, there is a "save conflict resolution" setting with two options: "askUser" and "overwriteFileOnDisk".  Could we add a third option for "attemptMerge"?  This "attemptMerge" option would attempt to auto merge when changes are in different parts of the file, and only bring up the diffing editor when the merge is unsuccessful.

**Comment by bpasero** [comment]
This is an interesting idea, but would we leverage Git for merging or write our own merger?
