### ISSUE TITLE
Can't open any file due unexpected toke

### ISSUE THREAD

**Issue by thiagodiniz** [microsoft/vscode#98536]
Issue Type: <b>Bug</b>

I am trying to open any file in my project folder but, vscode says the can't open file with unexpected token: in JSON position 100003.

I have scanned my project for any json with this error and couldn't find also i uninstalled all extesions, still it didn't work

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|8.00GB (0.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
ruby|reb|0.27.0
codetour|vsl|0.0.28
gistfs|vsl|0.0.67
vscode-ruby|win|0.27.0

</details>

**Comment by thiagodiniz** [comment]
hey @kieferrm  witch info is missing, I have searchd for all json files in my project and couldn't find the reason for this error

**Comment by egamma** [comment]
@thiagodiniz we need detailed steps so that we can reproduce the error:
- which file did you open when the error happens?
- can attach the file that caused the error
- can you provide more details about the error, where does it show up?
- is there any information in the developer tools console (Help>Toggle Developer Tools)

**Comment by thiagodiniz** [comment]
Thanks, @egamma.

The problem is any file from a Ruby On Rails project that I have.
The problem arises when I open the folder of the project e try to open any file at all.

In the console this message it's shown:

  ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.

```
Unable to open '.gitignore': Unexpected token : in JSON at position 100003.
  | onDidChangeNotification | @ | notificationsAlerts.ts:40
```

**Comment by egamma** [comment]
>Unable to open '.gitignore': Unexpected token : in JSON at position 100003.

Have you checked the contents of you .gitignore file? What is its contents?

**Comment by thiagodiniz** [comment]
@egamma Yes, I did. But as I mentioned earlier this happens with every file in this project. I have even deleted all files from Application support and Cache.

I did find this issue: https://github.com/microsoft/vscode/issues/85455

and this `code --user-data-dir . .` make the error to not happen

**Comment by thiagodiniz** [comment]
Solved the problem with this `rm -rf  ~/Library/Application\ Support/Code`

**Comment by egamma** [comment]
@thiagodiniz glad you could fix the problem.

**Comment by aeschli** [comment]
duplicate of https://github.com/microsoft/vscode/issues/102251.

Please try if https://github.com/microsoft/vscode/issues/102251#issuecomment-671912942 works as work around.
