### ISSUE TITLE
Python oddity

### ISSUE THREAD

**Issue by theycallmevirgo** [microsoft/vscode#98538]
- VSCode Version:1.45.1
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Install anaconda
2. Create venv
3. Activate venv
4. Install vscode

![Screenshot (1)_LI](https://user-images.githubusercontent.com/57016940/82840648-5919ae80-9ea1-11ea-9d62-2efdfaa104dc.jpg)

Additionally, I don't know if it's the same issue but the internal terminal will not allow me to activate the venv. 

Does this issue occur when all extensions are disabled?: Yes/No
N/A

ETA: Jupyter works fine

**Comment by kieferrm** [comment]
\extPython
