### ISSUE TITLE
Handle Upgrade Required (426) Client Error

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#98530]
Handle the Upgrade Required (426) client error from server by disabling the sync and prompting the user to upgrade VS Code to enable sync again.

**Comment by sandy081** [comment]
<img width="482" alt="image" src="https://user-images.githubusercontent.com/10746682/82826952-540f2c00-9eae-11ea-837e-4064e029ff50.png">

**Comment by Tyriar** [comment]
@sandy081 can you also include the hash in the message like this? "(1.46.0, abcdef1)"

**Comment by sandy081** [comment]
I see how hash helps us but do not see how it helps user.

**Comment by Tyriar** [comment]
@sandy081 because you might get an issue with a screenshot that may not give you enough information to action. Plus the notification is lying as "the current version (1.46.0-insider) is not compatible" is not true as that's the version of the following version too.

**Comment by sandy081** [comment]
@Tyriar  Please verify

**Comment by Tyriar** [comment]
The error works, wording discussion captured in https://github.com/microsoft/vscode/issues/92890
