### ISSUE TITLE
Search UX: Cancelling and Progress feedback

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#9853]
- VSCode Version: 1.4.0-insiders
- OS Version: OSX

Steps to Reproduce:
1. Open Project with large number of files
2. Search for something

Search will start running but then it will get stuck (or gets very slow - waited 15 min and did not finish) - CPU is at > 100%

![image](https://cloud.githubusercontent.com/assets/1723815/17177175/226a4082-53de-11e6-98be-ded12c25ac16.png)

I know that there is related task to speed of search https://github.com/Microsoft/vscode/issues/55

But I would like to propose 2 small things that would help:
1. Ability to stop the search - especially if its very slow/stuck - right now the only option is to kill VSCode
2. Some progress indication so user can know that it is still searching (and not stuck) - eg. atom shows number of files that it searched 

![image](https://cloud.githubusercontent.com/assets/1723815/17177241/818d4cbc-53de-11e6-8307-9e52d98104a1.png)

**Comment by kieferrm** [comment]
@wallverb how large is the workspace you search? Approximately how many matches? Any network folders involved?

**Comment by wallverb** [comment]
Ok, so here are the details:
1. Workspace size: `1.30GB`
2. Workspace files count: `30000`
3. SSD
4. It did finish the search in: `10 minutes`
5. It matched: `10 files`

It turned out that by default it was searching `build` folder that has concatenated and minified js files (there were multiple builds inside)

Here is the experience:
Blue bar (that shows progress) was going good until 90-95% and got stuck (as in first picture above) - probably because it got to that build folder which has huge files that are minified (just my guess)

so what would help users:

1. Ability to stop/cancel search (right now the only way is to kill vscode)
2. Numeric progress (like Atom?) or maybe even to show dir and/or file being searched so that users know that it really progresses (and is not stuck) and maybe even realize that things like `build` folders are being searched (were not excluded in vscode config file)

Thanks

**Comment by sandy081** [comment]
@wallverb 

> Ability to stop/cancel search (right now the only way is to kill vscode)

You can also stop/cancel the current search by pressing <kbd>esc</kbd> key in search box.

**Comment by sandy081** [comment]
You can also exclude search from looking up into build or minimized files through following conf: `search.exclude`

**Comment by wallverb** [comment]
@sandy081 Thanks for the info about `esc` trick - I guess I moved the focus away from that input box and did not think to click there again and hit Esc. Maybe adding one button or a text below (if there is no result) that `Esc cancels the search` - would be very helpful for users.
![image](https://cloud.githubusercontent.com/assets/1723815/17363288/7781c4be-5947-11e6-8863-cc6c10fbb15c.png)

Although if this https://github.com/Microsoft/vscode/issues/9435 will be implemented then closing Tab would be very clear way for cancelling the search

and right about `search.exclude` - it's just that user wouldn't be able to realize that's where search is looking into right now - unless I waited 10 min and saw search result in this directory.

But I guess my case is pretty rare and https://github.com/Microsoft/vscode/issues/55 would help so feel free to close

**Comment by sandy081** [comment]
@wallverb I agree we need some ux assistance here to help users.

1. Discovering how to cancel the search - One option is to provide a text in the results view.
2. More detailed feedback / progress like in Atom

@stevencl FYI - We need some UX feedback here.

Thanks

**Comment by raldred** [comment]
What's providing the search? 
Would it be possible to switch it ack?

**Comment by roblourens** [comment]
This should be faster in 1.8, and here's an issue to improve the progress bar - https://github.com/Microsoft/vscode/issues/16403
