### ISSUE TITLE
Visual Studio Download location 

### ISSUE THREAD

**Issue by Plummtw** [microsoft/vscode#98546]
Hi :

This is not a issue about the visual studio code itself, it's about the link in the website, because I don't know where to report so I just report here.

I live in Taiwan, and in my place I can download Visual Studio Code previously, but now I cannot.

I suggest we can specify the download location of Visual Studio Code in web site https://code.visualstudio.com/. Because the download location seems to redirect to China (azure.cn), but in Taiwan some organization just blocks connection to any ip address of China. 

So I suggest we can manually download it from other place.

I am not sure extensions and NuGet in VisualStudioCode connects to China or not, I suggest we can have a choice of the location.

**Comment by joaomoreno** [comment]
We won't advertise the CDN URLs, but you can easily get the non-China URL by replacing the domain with `az764295.vo.msecnd.net`
