### ISSUE TITLE
Main drop-down menu flickers on Linux, dark OS theme.

### ISSUE THREAD

**Issue by HubKing** [microsoft/vscode#98545]
- VSCode Version: 1.45.1
- OS Version: Ubuntu 20.4, Window theme = "Dark"
Steps to Reproduce:

1. Click "File" on the main menu
2. Move the mouse pointer to the right/left fast. Or keep clicking the "File" so that the drop-down menu keeps disappearing/reappearing.

The drop-down menu flickers too much. It seems the whole drop-down menu becomes white briefly, and then redrawn. Not a serious problem but if it can be fixed easily, it would be helpful to users' eyes...

To tell the truth, I came here to report that the menu font size is too small, but I have found a workaround. I had enabled "Large Text" in "Universal Access", and it seemed that VS Code did not respect that setting unlike other applications. While VS Code was running, I turned "Large Text" off and then turned it on again, and then VS Code's main menu font size became larger. Is that a bug?

![Screenshot from 2020-05-26 10-06-15](https://user-images.githubusercontent.com/10900489/82851781-e4e01900-9f3b-11ea-94ec-410f6fbdc734.png)

Does this issue occur when all extensions are disabled?: Yes

Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-31-generic

**Comment by ClementTsang** [comment]
I seem to be getting a similar issue, so you aren't alone.  At first I thought it was compositor acting up but disabling/playing around with settings/restarting it didn't solve anything, which led to searching for this issue and arriving here.

```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-15T10:46:12.662Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.6.14-arch1-1
```

**Comment by max-programming** [comment]
This happens on all Linux distros. As it is a Chromium window, it will show that behavior, it'll pick up the GTK theme. You can set the default vs code theme by changing the title bar setting.

Or by adding `"window.titleBarStyle": "custom"` in settings.json. I hope that helps

**Comment by deepak1556** [comment]
Can you check our [insiders version](https://code.visualstudio.com/insiders) and [exploration version](https://az764295.vo.msecnd.net/exploration/5103b1b09c0e26d466756bfdc1546a8c4bfd68c8/code-exploration_1.52.0-1604388902_amd64.deb) if this is still an issue ?

**Comment by HubKing** [comment]
> Can you check our [insiders version](https://code.visualstudio.com/insiders) and [exploration version](https://az764295.vo.msecnd.net/exploration/5103b1b09c0e26d466756bfdc1546a8c4bfd68c8/code-exploration_1.52.0-1604388902_amd64.deb) if this is still an issue ?

I tried the current version of Code (ver. 1.51.0, Ubunu 20.04.1) before installing Insider/Exploration, and it seems that the problem has been fixed. The menu now seems to be Gnome native menu, and no longer flickers or shows small text when Large Text has been enabled.
