### ISSUE TITLE
Work With nVidia So VS Code Can Be Used To Setup CUDA For Machine Learning Instead of Having To Use Visual Studio Community

### ISSUE THREAD

**Issue by j-a-lewis** [microsoft/vscode#98548]
I recently got a new computer with a powerful nVidia GPU to pursue online instruction in machine learning.  As part of Microsoft's instructions to set up CUDA 9.x, required for CNTK v2.7, I downloaded and installed an nVidia CUDA package that required Visual Studio Community 2019 to be installed for CUDA setup.  I'm an ignorant 74-yearold retiree hobbyist but I was wondering why Microsoft, VS Coders, and nVidia cannot get together and make it possible to also set up and administer CUDA through VS Code rather than require the install of another massive IDE.  Other than the CUDA setup, at the moment I have no foreseeable plans to use VS Community 2019 for anything else.  Since I'm an ignorant newbie, apologies if it's all ready possible to set up CUDA with VS Code and I just haven't learned about it yet.

**Comment by egamma** [comment]
Does this blog help https://ericzhng.github.io/eric-blogs/2018/10/11/vs-code-cuda/?

**Comment by j-a-lewis** [comment]
Thanks for the suggestion.  I'm saving it for future reference!  Allowing for my ignorance, that seems to be along the lines of what I want, to make use of C++ in VS Code to set up a CUDA environment.  I'm probably asking too much, though, in that I'd be even happier if nVidia and Microsoft would work together along the VS Coding community to make it an out-of-the-box alternative for running a CUDA setup executable for beginners like me who are still at the paint-by-numbers stage.  But I guess that's asking a lot of nVidia.  They don't even tell you about the Visual Studio C++ requirement 'til you're like 3/4's of the way thru the CUDA setup-then you have to rollback and start over after again after you've installed Visual Studio!

**Comment by egamma** [comment]
\extC++

Since this is a C++ specific request, please continue the discussion in the C++ extension

**Comment by j-a-lewis** [comment]
Will do.  Thanks for the suggestion.
