### ISSUE TITLE
Webview resource: support baseUrl and relative path

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#98542]
In webview, extensions are now converting file based URIs to `vscode-webview-resource` URI. It works for absolute paths but doesn't work for relative path. For example, say we have a webview which has base Url set as 

```html
<base url="vscode-webview-resource://7bec02ec-b6dc-4935-bece-581e0f5d9254/file///Users/rudi//notebook-test/test/">
```

and then use relative path for images

```html
<img src="./bridge.jpg">
```

Currently it's not resolved properly. If there is `baseUrl` set for the web view, we may want to convert it to

```
vscode-webview-resource://7bec02ec-b6dc-4935-bece-581e0f5d9254/file///Users/rudi//notebook-test/test/bridge.jpg
```

**Comment by rebornix** [comment]
@DonJayamanne mentioned that it works in normal Webview before so I'm wondering if something changed recently in how the Webview handles resources.

**Comment by mjbvz** [comment]
I just tested this in the markdown preview and it does seem to work:

<img width="633" alt="Screen Shot 2020-05-29 at 12 36 43 AM" src="https://user-images.githubusercontent.com/12821956/83234030-7f12ad80-a144-11ea-9760-162da4941809.png">

Can you please share an example where it is not working?

**Comment by rebornix** [comment]
oops, I used wrong attribute name, it should be `href`. Sorry for bothering, it works as charm.
