### ISSUE TITLE
SCM hover action overlaps with code folding chevron

### ISSUE THREAD

**Issue by datazen** [microsoft/vscode#98541]
Issue Type: <b>Feature Request</b>

The code folding caret and the view control next to it are too close together.  trying to click to fold code results in the other debug (not sure what its called) popup to happen.  move the line to the other side of the numbers to give more space. 

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

![grabilla em1424](https://user-images.githubusercontent.com/3129247/82850923-29cc6700-9ecc-11ea-9fd2-fae0752b7945.png)

**Comment by rebornix** [comment]
@misolori did we update the width of the scm indicator recently, it seems more challenging to click on the folding icon recently.

**Comment by misolori** [comment]
@rebornix nope, width has not changed in ~2 years https://github.com/microsoft/vscode/blame/4364509ef28ddf211668146d94a64c556ecd2961/src/vs/workbench/contrib/scm/browser/dirtydiffDecorator.ts#L611

I think with the recent pattern change it could appear to be bigger but it's an illusion
