### ISSUE TITLE
Allow to pin tabs

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98558]
Tabs can be pinned. See https://github.com/microsoft/vscode/issues/98019 for features and https://github.com/microsoft/vscode/issues/98161, https://github.com/microsoft/vscode/issues/98160 for follow up work. 

![pin-tabs](https://user-images.githubusercontent.com/900690/82874137-cd9e2d00-9f35-11ea-9826-d808cad3c4fb.gif)

**Comment by ChristopherSnay** [comment]
Is there any way to make it still show the filename in the pinned tab like in Visual Studio?

**Comment by bpasero** [comment]
See https://github.com/microsoft/vscode/issues/98161
