### ISSUE TITLE
.ini file coloring bug

### ISSUE THREAD

**Issue by dacapoday** [microsoft/vscode#98550]
.ini file character coloring is not correct when use single ' and " at value field.
![Snipaste_2020-05-26_14-18-14](https://user-images.githubusercontent.com/9378047/82866707-05b86680-9f5c-11ea-878f-fa89d509e911.png)
key_c and key_e color is different with key_a.

**Comment by alexr00** [comment]
Can you please provide a copy/paste-able example?

**Comment by dacapoday** [comment]
> Can you please provide a copy/paste-able example?
```
[ .ini file coloring bug ]
key_a = xxxxxxxxxxxxxxxxxxxxxxxxxxxx
key_b = can't use correct color when
key_c = use single ' at value field
key_d = the " also has this problem
key_e = " xxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by alexr00** [comment]
Thanks!
This looks like a duplicate of an upstream issue from where we get our ini grammar. https://github.com/textmate/ini.tmbundle/issues/3
