### ISSUE TITLE
Setting to exclude files from IntelliSense but not get and VS Code

### ISSUE THREAD

**Issue by awebdeveloper** [microsoft/vscode#98555]
I would like to exclude mocks files to be excluded from IntelliSense. While working on a React-TypeScrypt Project I notice that VS Code suggest me functions and tags from other files too in codebase which many not have been imported, which is great. On selecting that not only does it add the function, it imports it too, which is again awesome. 

But it needs a small change.  The way mocks work (at least in my codebase) is that they have the same name as the actual function. This leads to two line items being shown in IntelliSense. Selecting the wrong on will add the mock file in the import statement.

I spent the last 30min searching for a option to prevent code some files from showing up in IntelliSense. Can we please add a setting for this. Open to alternatives

**Comment by mjbvz** [comment]
Try configuring a [jsconfig.json](https://code.visualstudio.com/Docs/languages/javascript#_javascript-projects-jsconfigjson) or tsconfig that includes the files from your project but excludes the mock. This should prevent them from showing up in auto imports
