### ISSUE TITLE
PowerShell integrated Console errors

### ISSUE THREAD

**Issue by toybits** [microsoft/vscode#98551]
- VSCode Version: 1.45.1
- OS Version: 2012 R2 (6.3.9600)

Steps to Reproduce:
This is not happening on Win10 machines.

Is happening in an RDP Console.
When I type in the Integrated console, I get strange characters. I get the character I type and a bunch of others.

For example, if I type c (i.e. for clear-host) I get

c[38;5;238mls

I can keep typing, say cls and I get cls[38;5;238mcls, however, CLS still works as an alias for clear-host and it does, in fact, clear the host.

If I type G I get g[38;5;238mcls. But then I can keep typing ‘Get-Mailbox scottmcgrath’ I get ‘ get-mailbox scottmcgrath38m.mcgrathUpaQ3Nw==’

However, the ‘Get-Mailbox scottmcgrath’ command still does work. But it’s terrible to read and I’m not finding that running scripts interactively is also inserting characters so returning errors now.

Does this issue occur when all extensions are disabled?: No. However, you don't get the Integrated console when you disable the PowerShell Extension.
I'm using version 2020.4.0 of the PowerShell Extension however I do note that I DO observe the same behaviour with the Preview Version 2020.5.0

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
