### ISSUE TITLE
can't debug go program from windows to linux

### ISSUE THREAD

**Issue by mazhan465** [microsoft/vscode#98554]
Issue Type: <b>Bug</b>

when I in windows and  use remote-ssh connect to my centos7  debug for my go program:
go: GOPATH entry is relative; must be absolute path: "C".
For more details see: 'go help gopath'
exit status 2
Process exiting with code: 1
err happend and this was in my debug console.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 3.10.0-957.27.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.70GB (1.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 外网开发机|
|OS|Linux x64 3.10.0-957.27.2.el7.x86_64|
|CPUs|Intel Core Processor (Broadwell, no TSX) (2 x 2194)|
|Memory (System)|1.89GB (0.35GB free)|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
vscode-npm-script|eg2|0.3.11
search-node-modules|jas|1.3.0
node-module-intellisense|lei|1.5.0
vscode-language-pack-zh-hans|MS-|1.45.1
python|ms-|2020.5.80290
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.28.1
Go|ms-|0.14.3
vscode-leetcode|she|0.16.2
vscode-icons|vsc|10.1.1
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.8.0
vscode-proto3|zxh|0.4.2

</details>

![image](https://user-images.githubusercontent.com/20238053/82868377-1cac8800-9f5f-11ea-9875-84511a2ca215.png)

**Comment by egamma** [comment]
\extGo
