### ISSUE TITLE
Deleting searched phrase and closing file shows the deleted result in search pane

### ISSUE THREAD

**Issue by jdforsythe** [Microsoft/vscode#9855]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

1. Use global search to search for something in your project
2. Open one of the results and delete the searched phrase from the file - at this point the search results show "no matches"
3. Save and close the file
4. The search result for the closed file shows the original line (that no longer exists) with the matched phrase

**Comment by sandy081** [comment]
Fixed in 1.4

Duplicates #8710
