### ISSUE TITLE
Tun on Preference Sync does nothing

### ISSUE THREAD

**Issue by ssbarnea** [microsoft/vscode#98569]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Clicking "Turn on Preferences Sync"

VS Code version: Code - Insiders 1.46.0-insider (da98a19a5d6724367bd99c8ec3b8f55054be37d1, 2020-05-20T23:28:34.587Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|40.00GB (0.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
vagrant|bbe|0.5.0
markdown-mermaid|bie|1.5.0
insert-unicode|bru|0.8.0
language-hugo-vscode|bud|1.2.0
better-toml|bun|0.3.2
vscode-pytest|Cam|0.1.1
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.1.3
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
LogFileHighlighter|emi|2.8.0
vscode-install-vsix|fab|1.4.0
vscode-open-in-code|fab|1.1.6
vscode-open-in-github|fab|1.2.3
vscode-pull-request-github|Git|0.16.1
vscode-test-explorer|hbe|2.18.1
restructuredtext|lex|128.0.0
vscode-python-test-adapter|lit|0.4.2
pre-commit-vscode|Mar|0.0.8
mypy|mat|0.1.4
vscode-docker|ms-|1.2.0
python|ms-|2020.5.80290
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
docker-compose|p1c|0.3.5
vscode-yaml-sort|Pas|2.3.1
puppet-vscode|pup|0.26.1
show-offset|ram|0.0.4
vscode-yaml|red|0.8.0
rescuetime|Res|1.0.1
vscode-sort-json|ric|1.18.0
jinjahtml|sam|0.13.0
trailing-spaces|sha|0.3.1
code-spell-checker|str|1.9.0
gerrit-vscode|tht|0.4.1
shellcheck|tim|0.9.0
sort-lines|Tyr|1.9.0
errorlens|use|3.1.1
vscode-vtools|ven|1.0.6
vscode-ansible|vsc|0.5.2
vscode-wakatime|Wak|4.0.0
highlight-bad-chars|wen|0.0.3
html-css-class-completion|Zig|1.19.0

</details>

**Comment by sandy081** [comment]
@ssbarnea Can you please more information on what's happening - Any errors or notifications? What do you see in Sync logs? A recording would be helpful actually
Can you also please update your insiders and try again?

**Comment by ssbarnea** [comment]
Nothing gets logged into preferences sync pane, the button does nothing.
![](https://sbarnea.com/ss/Screen-Shot-2020-05-27-10-11-44.08.png)

**Comment by sandy081** [comment]
Can you please check if you are on latest insiders? I see there is a number badge notification on your bottom left gear icon. If it is an insiders update, can you please update and try again?

**Comment by ssbarnea** [comment]
I updated it and restarted. Here are mode details:
* If I click to re-use already logged-in github account, it gives the 401 error above
* If I click to login to GitHub, it opens my browser (Firefox), starts the authentication procesc and generates a token url which it tells me:
```
"Click Signing in to null... in the status bar.
Paste the token and hit enter."
```

Guess, what there is no such thing on any status bar, browser of vscode.

**Comment by sandy081** [comment]
/duplicate

I assume this is same as #98625
