### ISSUE TITLE
Integration test failure: notebook workflow notebook cell actions

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98560]
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=76289&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=8e2e103d-8d5d-54da-dc73-3c44bf1dc402&l=242

```
1 failing
  1) notebook workflow notebook cell actions:

      AssertionError [ERR_ASSERTION]: 1 == 2
      + expected - actual

      -1
      +2
      
      at Context.<anonymous> (extensions/vscode-notebook-tests/src/notebook.test.ts:324:10)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**Comment by rebornix** [comment]
Fixes have been pushed to master, considering we are in the endgame, I'm not going to enable this particular integration test this iteration but have it turned on early next week.

**Comment by rebornix** [comment]
It's already fixed.

**Comment by rebornix** [comment]
No longer valid as the test is assuming that after one command execution, all events are sent the extension host correctly, which is not guaranteed.
