### ISSUE TITLE
Native Android Development support in VSCode: Lint/Code Assist,Debug etc.

### ISSUE THREAD

**Issue by blackjyn** [microsoft/vscode#98568]
I'm NOT a big fan of Android Studio despite with Project Marble makes Android Studio runs faster.
I can code Flutter with IntelliJ IDEA but in my experience using VSCode is faster and consume less resources.

Would you please Microsoft create an "Android Development Extension" to support native Android development via VSCode? 

I've already done some hacks using several VSCode extensions (Java,gradle,kotlin,etc) to make a FULL Android development joy in VSCode that support code-assist, build etc, but no luck.

There are lot of people out there also wishing a support of FULL Android development via VSCode as an alternative to Android Studio, at least on the code-assist feature.

**Comment by blackjyn** [comment]
hey bot, Its not duplicate .
Its totally different thing

**Comment by blackjyn** [comment]
Sadly, currently there's no such extension like that in the marketplace.

I'm asking Microsoft to create such extension is because previously MS has already made official extension for several tech, then why not for Android?

Thank you @egamma for labelling this as "extension candidate". LOT of developers especially those with lower hardware specs are going to be happy if there's such alternative to Android Studio.

We don't need a full-fledge like that one, we just need code-assist/lint that correctly recognize the Android APIs and it's imported libs on .java , .kt along with the .xml sources.

That's would be more than just enough as an alternative.

**Comment by adelphes** [comment]
Hi @blackjyn - I'm the developer on the Android debugger extension.

I've seen a lot of comments about code-completion and other support for Android and I'm actively working on including a Java Language Server specifically supporting the Android framework.

If you'd like to help, there's a lot of other areas that could be developed for Android on VSCode - a visual editor for XML files or a simple command for creating a new Android project.

Feel free to add issues, uptick items you're interested in (https://github.com/adelphes/android-dev-ext/issues/33) or help out at https://github.com/adelphes/android-dev-ext

**Comment by blackjyn** [comment]
@adelphes wow I'm gonna tried it. Well I don't need the visual layout , it's more comfortable for me coding the layout from the plain XML as long as code assist is supported.
