### ISSUE TITLE
Window stays grayed out after opening a link

### ISSUE THREAD

**Issue by thefoxie** [microsoft/vscode#98563]
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-17T22:31:53.325Z
Electron: 7.1.14
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.6.14-arch1-1

Steps to Reproduce:

1. Open link which opens modal window (or whatever it is) 
2. Sometimes the background stays grayed out even after the action is taken

Opening `Help -> About`  makes it go away.

Does this issue occur when all extensions are disabled?: Yes

![obrázok](https://user-images.githubusercontent.com/15309350/82879607-74d29280-9f3d-11ea-8625-8a64a0f448ee.png)

**Comment by egamma** [comment]
This is the intended behaviour when you open an external link. You can configure the trusted domains from this dialog.

**Comment by thefoxie** [comment]
@egamma I think you misinterpreted what I thought was the issue. I meant that when I click the open button and the modal window itself disappears, the background stays the same (grayed out/dimmed) until I open About modal. Then it works as intended even when I open link and click the actual open button.
