### ISSUE TITLE
[loc][Query][VSCODE] Localizability of strings in vs_workbench

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode#98576]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Id | File Name Live Page Extended | String Resource ID | Full Source String | Extended Description | Answer Needed By
-- | -- | -- | -- | -- | --
49,746 | vscode-workbench\vs_workbench_contrib_debug.xlf | 0;   "src/vs/workbench/contrib/debug/browser/debugHover.variableAriaLabel_Duplicated35" | {0} value {1}, variables, debug | Please, define placeholders. |  
49,747 | vscode-workbench\vs_workbench_contrib_preferences.xlf | 0;   "src/vs/workbench/contrib/preferences/browser/tocTree.settingsTOC" | Settings   Table of Contents | It   seems to have 2 parts, Settings and Table of Contents. Or is it "the   settings of the table of contents"? Please, confirm. |  
49,766 | vscode-workbench\vs_workbench_contrib_callHierarchy.xlf | 0;   "src/vs/workbench/contrib/callHierarchy/browser/callHierarchyTree.to" | callers fo {0} | Should it be "callers   to"? Or even "calls to"? As opposed to previous string:     calls from {0}       0;   "src/vs/workbench/contrib/callHierarchy/browser/callHierarchyTree.from" |  
49,769 | vscode-workbench\vs_workbench_services_themes.xlf | 0;   "src/vs/workbench/services/themes/common/colorExtensionPoint.invalid.id.format_Duplicated5" | 'configuration.colors.id'   must follow the word[.word]* | Is   "word[.word]*" translatable? |  
49,780 | vscode-workbench\vs_workbench.xlf | 0;   "src/vs/workbench/browser/actions/layoutActions.moveFocusedView.title" | View: Move {0} | What does the placeholder stand   for? |  
49,781 | vscode-workbench\vs_workbench_contrib_debug.xlf | 0;   "src/vs/workbench/contrib/debug/browser/debugQuickAccess.contributed" | contributed | Does   anything precede this string? Or is there any special reason for not   capitalizing the word "contributed"? Also, can you provide more   context? What does "contributed" refer to here?          Similar strings:     configured tasks     recently used tasks     0;   "src/vs/workbench/contrib/tasks/browser/abstractTaskService.configured_Duplicated34"     0;   "src/vs/workbench/contrib/tasks/browser/abstractTaskService.recentlyUsed_Duplicated32" |  
49,782 | vscode-workbench\vs_workbench_contrib_search.xlf | 0;   "src/vs/workbench/contrib/search/browser/anythingQuickAccess.openToBottom_Duplicated6" | Open to the Bottom | What exactly does "Open to   the Bottom" mean? Please explain.          Similar string:     Open to the Side     0;   "src/vs/workbench/contrib/search/browser/anythingQuickAccess.openToSide_Duplicated4" |  
49,783 | vscode-workbench\vs_workbench_contrib_debug.xlf | 0;   "src/vs/workbench/contrib/debug/browser/variablesView.variableAriaLabel_Duplicated36" | {0}   value {1}, variables, debug | Please   explain placeholder contents. |  
49,788 | vscode-workbench\vs_workbench_contrib_extensions.xlf | 0;   "src/vs/workbench/contrib/extensions/browser/remoteExtensionsInstaller.remote" | Remote | Is this referred to remote   repository or is an adjective? If it is an adjective please provide context   in order to translate proper gender/number |  
49,796 | vscode-workbench\vs_workbench_contrib_terminal.xlf | 0;   "src/vs/workbench/contrib/terminal/common/terminalConfiguration.terminal.integrated.automationShell.linux" | A   path that when set will override {0} and ignore {1} values for   automation-related terminal usage like tasks and debug. | what   does {1} refer to? a name or a number? |  
49,797 | vscode-workbench\vs_workbench_contrib_terminal.xlf | 0;   "src/vs/workbench/contrib/terminal/common/terminalConfiguration.terminal.integrated.automationShell.osx" | A path that when set will   override {0} and ignore {1} values for automation-related terminal usage like   tasks and debug. | what does {1} refer to? a name   or a number? |  
49,798 | vscode-workbench\vs_workbench_contrib_terminal.xlf | 0;   "src/vs/workbench/contrib/terminal/common/terminalConfiguration.terminal.integrated.automationShell.windows" | A   path that when set will override {0} and ignore {1} values for   automation-related terminal usage like tasks and debug. | what   does {1} refer to? a name or a number? |  
49,809 | vscode-workbench\vs_workbench_contrib_debug.xlf | 0;   "src/vs/workbench/contrib/debug/browser/debugQuickAccess.providerAriaLabel" | {0} contributed configurations | What does the placeholder stand   for? We assumed a number for now, please advise.          Similar string:     {0} New Notifications     0;   "src/vs/workbench/browser/parts/notifications/notificationsStatus.notifications_Duplicated48" |  
49,810 | vscode-workbench\vs_workbench_contrib_tasks.xlf | 0;   "src/vs/workbench/contrib/tasks/browser/abstractTaskService.TaskService.noConfiguration" | Error:   The {0} task detection didn't contribute a task for the following   configuration:\n{1}\nThe task will be ignored.\n | What   does the placeholder stand for? Please explain/give an example. |

**Comment by egamma** [comment]
Please clarify the questions from the translators in the code you own.

**Comment by bpasero** [comment]
Swapping with @sbatten for `src/vs/workbench/browser/actions/layoutActions.moveFocusedView.title`

**Comment by alexr00** [comment]
49,810:
The first placeholder is a type of VS Code task that is contributed by an extension. For example, `npm` from the built in npm extension or `gulp` from the built in gulp extension. 
The second placeholder is the task from the user's `tasks.json` file. For example, an `npm` type task could be 
```
{
			"type": "npm",
			"script": "watch",
			"problemMatcher": "$tsc-watch",
			"isBackground": true,
			"presentation": {
				"reveal": "never"
			},
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
```

If, when we ask the npm extension to provide a task for the above json task, the npm extension doesn't give a runnable task back we would show the TaskService.noConfiguration message.

**Comment by Tyriar** [comment]
@PDostalek added a comment to the terminalConfiguration ones in the code: https://github.com/microsoft/vscode/commit/72550d1808c33c45173af77781f815e535bd4687

**Comment by isidorn** [comment]
I have pushed a commit which adds comments for all 4 of my localization strings, thus unassigning myself.

**Comment by sbatten** [comment]
added comment in commit above for view movement command

**Comment by PDostalek** [comment]
Hi @egamma  or@sandy081 Could you please help me with 3 questions without answers? 49766, 49769,49780. Thx

**Comment by sandy081** [comment]
Pinging 

49766 - @jrieken 
49769 - @aeschli 
49780 - @sbatten

**Comment by sbatten** [comment]
Committed comment here: https://github.com/microsoft/vscode/blob/dd62fa471cb39a36df06afb416d2b98966626251/src/vs/workbench/browser/actions/layoutActions.ts#L690

**Comment by aeschli** [comment]
49769 was fixed by https://github.com/microsoft/vscode/commit/6377e748afccd76d8c3b8518968da0324356ed1d
