### ISSUE TITLE
JsDoc in HTML files syntax highlight

### ISSUE THREAD

**Issue by Laser42** [microsoft/vscode#98575]
- VSCode Version: 1.45.1
- OS Version: Windows 10 Pro x64

JsDoc comments highlights incorrectly when editing html files.

Steps to Reproduce:

1. Create a HTML file
2. Add <script></script> section as follows:
```
<script>

    /**
     * A function
     * @param {string} arg - string argument
     * @returns {null} - desc
     */
    function MyFunc(arg) {
        return null;
    }
    /**
     * A class
     */
    class MyClass {
        /**
         * Ctor
         * @param {string} field - desc
         */
        constructor(field) {
            this.field = field;
        }
    }

</script>
```
3. Note that JsDoc syntax inside class has a highlight, while there is no syntax highlight for function's JsDoc:
![image](https://user-images.githubusercontent.com/40018028/82888375-e4eb1380-9f51-11ea-9e48-ce0a422c240b.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Moved to the owning repo: https://github.com/textmate/html.tmbundle/issues/109
