### ISSUE TITLE
VSCode and Ruby/Rails Debugging

### ISSUE THREAD

**Issue by iv10** [microsoft/vscode#98574]
I've set-up VSCode 1.45.1 with Ruby support and installed the following VSCode plugins:

 - Bust a Gem 0.1.8
 - Rails 0.16.4
 - Ruby 0.27.0
 - VSCode Ruby 0.27.0
 - vscode-ruby-ctags 1.4.1

I've also installed the *ruby-debug-ide* and *debase* Gems. My Ruby version is 2.5.7.

After adding the debug configuration like this:

    {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "Rails server",
                "type": "Ruby",
                "request": "launch",
                "program": "${workspaceRoot}/bin/rails",
                "args": [
                    "server"
                ]
            }
        ]
    }

I started debugging by pressing **F5** and can see the server boot-up properly. I can also open the web-application via browser.

However, the breakpoints I've set-up are just ignored by VSCode. When I try to add more breakpoints to the code I see ***Not available*** in the Debug Console.

Am I mssing something in my setup?

**Comment by egamma** [comment]
Please report the issue against the ruby extension
