### ISSUE TITLE
core dumped if a breakpoint was set

### ISSUE THREAD

**Issue by HarveyHub** [microsoft/vscode#98571]
- VSCode Version:1.45.1
- OS Version: Ubuntu 16.04  linux core:4.15.0

Steps to Reproduce:

1. press F5  to debug the executable
2. it will core dump if you set a break point on cpp fille

![Image_20200526173012](https://user-images.githubusercontent.com/7811407/82884709-ad429280-9f76-11ea-9498-afaa15f0a7f3.jpg)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by egamma** [comment]
Please report the issue against the C++ extension.
