### ISSUE TITLE
CallStack: set inline context key on hover not on context menu

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#98570]
Spinoff from https://github.com/microsoft/vscode/issues/97633

I need to fix that the context key is set per hovered item, not per context menu in the call stack view

**Comment by isidorn** [comment]
@connor4312 I was thinking more about this. And what you want is context key that would be set on hover to be exactly the id of the session.
That is a bit funky and we do not do it in other places in VS Code.
We usualy set context keys based on the type, not the id. So for example "we are hovering over a session" would be one. But that is not enough for your use case.

The current `callStackItemType` should only be used by the context menu.
For inline actions you can just push your actions there always since we only render the inline actions for sessions.

So what we are missing is specifying on what sessions you want your action to appear.
Is there something special about these sessions? Can vscode somehow see that they can be profilied by looking at some flag? And then we can introduce a context key on the vscode side in the sense of `callStackHoveredSessionCanBeProfiled`

I just want to try to simplify this since our latest approach is a bit too complex imho...

**Comment by connor4312** [comment]
There's nothing inherently special about the sessions themselves. Right now 'profiling' is a state kept in the logic on the extension side and in the debugger and transmitted via custom DAP messages. Because these are custom they aren't something that vs code can be aware of in a generalized way; so some dedicated API would probably be needed.

At this would a generic approach to, as originally suggested, support the setting of context keys on debug sessions be easier?

**Comment by isidorn** [comment]
After thinking about this more I kinda dislike this approach.
I would prefer if we look into https://github.com/microsoft/vscode/issues/97633
Sorry for not commenting on this sooner.

Since I am going on vacation end of this milestone, I can not look into that item in July, but feel free to drive this and to add proposed API for setting context keys on session.

**Comment by connor4312** [comment]
No worries. Have a good vacation! 🏖️

**Comment by isidorn** [comment]
@connor4312  Do you still need this? 
If not, can we close?

**Comment by connor4312** [comment]
The new `in` operator solves it https://github.com/microsoft/vscode/issues/97633#issuecomment-703916223
