### ISSUE TITLE
VS Code is capturing git credential request

### ISSUE THREAD

**Issue by SrBrahma** [microsoft/vscode#98579]
- VSCode Version: 1.45.1
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Spawn a child_process that executes a git command that asks the credentials to be inputted by the user

```
import { spawn } from 'child_process';

const child = spawn('git', ['clone', 'https://srbrahma@github.com/SrBrahma/Strenner.git'], {
  cwd: '/home/hb/Dev',
});
```

2. A VS Code will show a Input Box window to the user enter the credentials.

This is my problem. I don't want VS Code to "steal" this credential input from my program. I want that my code enters it via stdin.

![Captura de tela de 2020-05-26 08-35-47](https://user-images.githubusercontent.com/28177550/82896564-8cede600-9f2c-11ea-8e3d-6209e27e4e6b.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Disable `git.terminalAuthentication`.

**Comment by SrBrahma** [comment]
Many thanks for the quick and accurate answer! :)
