### ISSUE TITLE
Not recognizing " it() " function of JS

### ISSUE THREAD

**Issue by Saifullahiub** [microsoft/vscode#98577]
Issue Type: <b>Bug</b>

I am following an online course. Instructor is using " it() " function while programiing with JavaScript, but my Code is not recognizing it() function.
Instead it is auto corrected to instanceof(). please guide me...

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz (4 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>Extensions: none
(1 theme extensions excluded)

**Comment by Saifullahiub** [comment]
![Screenshot (14)](https://user-images.githubusercontent.com/57482083/82893029-e3c5e080-9f69-11ea-9b29-ce5b996569cb.png)

instructor's screenshot ^

**Comment by Saifullahiub** [comment]
Screenshot of my code ^
![Screenshot (13)](https://user-images.githubusercontent.com/57482083/82893403-5d5dce80-9f6a-11ea-8f6f-2c665a84a5b0.png)

**Comment by egamma** [comment]
The `it()` function comes from the jest framework and I suspect you are not import the `jest` module.

I see now error in VS Code.

**Comment by Saifullahiub** [comment]
@egamma 
i have imported jest modules, see my Screenshot
![jest](https://user-images.githubusercontent.com/57482083/82894481-1375e800-9f6c-11ea-9993-2b518636004a.png)
