### ISSUE TITLE
[loc][Query][VSCODE] Localizability of strings invscode-extensions\ms-vscode.js-debug-nightly

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode#98585]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Id | File Name Live Page Extended | String Resource ID | Full Source String | Extended Description | Answer Needed By
-- | -- | -- | -- | -- | --
49,765 | vscode-extensions\ms-vscode.js-debug-nightly.xlf | 0;   "browser.runtimeExecutable.edge.description" | Either 'canary', 'stable', dev,   'custom' or path to the browser executable. Custom means a custom wrapper,   custom build or EDGE_PATH environment variable. | Are these entries   translatable?Also, please, define "dev" in this context. |  
49,768 | vscode-extensions\ms-vscode.js-debug-nightly.xlf | 0;   "configuration.pickAndAttachOptions" | Default   options used when debugging a process through the `Debug: Attach to Node   Process` command | Is   it possible that it refers to string "Attach to Node.js Terminal   Process", following this one? We could not find command "Attach to   Node Process". |  
49,806 | vscode-extensions\ms-vscode.js-debug-nightly.xlf | 0;   "configuration.pickAndAttachOptions" | Default options used when   debugging a process through the `Debug: Attach to Node Process` command | is the command name of   "Debug: Attach to Node Process" translatable? |

**Comment by egamma** [comment]
@connor4312 please clarify the questions above in the code.

**Comment by connor4312** [comment]
> Are these entries translatable?Also, please, define "dev" in this context.

The items in quotes (canary, stable, custom) are not translatable -- also, "dev" should be wrapped in quotes, I will fix that. EDGE_PATH is not translatable.

> Is it possible that it refers to string "Attach to Node.js Terminal Process", following this one? We could not find command "Attach to Node Process".

Yes, I will correct that

> is the command name of "Debug: Attach to Node Process" translatable?

Yes

**Comment by PDostalek** [comment]
Thank you
