### ISSUE TITLE
"Problems" popup has ambiguous x icons

### ISSUE THREAD

**Issue by theigor** [microsoft/vscode#98588]
This is somewhere between a feature request, a suggestion and a UX bug. I searched open issues and didn't find a dupe, but please close this if it exists somewhere.

The "Problems" popup icon and the close icon are too similar. Especially for Mac users, I _always_ click on the icon on the left to try to close it. I am not sure if this can be changed by a theme/skin.

![image](https://user-images.githubusercontent.com/6673707/82909357-29b58100-9f37-11ea-9d55-eeca11f1751a.png)

I'm on the following version but this has been lightly bothering me for quite some time:
```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (1 wk ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

Thanks!

**Comment by misolori** [comment]
Please see https://github.com/microsoft/vscode/issues/92791 where you should be able to overwrite the default icons. I'm not sure whether the problems panel has these in yet but subscribe to that issue to get updates. cc @aeschli
