### ISSUE TITLE
File open under a single tab

### ISSUE THREAD

**Issue by puneethrj** [microsoft/vscode#98589]
Issue Type: <b>Feature Request</b>

Expected behaviour:
When I click a file from th explorer it should open up in a new tab and should show in the list of open editors, This was the behaviour until recently when I closed all open editors in the open editor panel.

Cause and effect
 After I closed all open editor using the open editor panel option when I click on multiple files it shows up under a single open editor and refuses to open another tabbed editor. 
It's not ideal as I cant switch between files in tab and have to keep the explorer open to switch files. attached images to show 
![Screenshot from 2020-05-26 19-38-16](https://user-images.githubusercontent.com/13819936/82912524-d836e180-9f8a-11ea-9263-7e317f8e576d.png)
![Screenshot from 2020-05-26 19-37-42](https://user-images.githubusercontent.com/13819936/82912534-d9680e80-9f8a-11ea-8ce0-905b714aacfc.png)

The hack/solution:
I edited a file and then opened up another file and now it opens up in another tab. 

The issue: 
The issue is that this is not a default behaviour and occurs every time I close all open editors using the option in the panel. To go back to the orignal behaviour i.e to open files in individual tabs I have to edit a file. 

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:10:24.511Z)
OS version: Linux x64 4.15.0-99-generic

Update:
This is also prevalent if I open another group. The new group refuses to open different files in different editors/tabs unless I edit a file in that group.

**Comment by bpasero** [comment]
Follow our docs to resolve this: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode
