### ISSUE TITLE
[themes] update seti-ui icons

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#98586]
[`seti-ui`](https://github.com/jesseweed/seti-ui/commits/master) accepted a couple of update PRs recently. Can you please sync extensions/theme-seti/icons?

Meanwhile, I noticed that `go.mod` file was falsely classified as `xml` type file. 
https://github.com/jesseweed/seti-ui/pull/568#issuecomment-633533831
I am not sure if that's a real issue in the latest vscode release candidate, 
or just a non-reproducible problem caused by some peculiarity in my vscode dev env.
Can you please take a look?

@orta @ramya-rao-a @inliquid

**Comment by YakoYakoYokuYoku** [comment]
Also something worth mentioning is that WebP images lack the image icon whereas WebM videos does indeed have the video icon. Adding lines:
```
"svgx": "_image",
"webp": "_image",
"sublime-project": "_sublime",
```
and
```
"svgx": "_image_light",
"webp": "_image_light",
"sublime-project": "_sublime_light",
```
indeed solves the issue.

**Comment by misolori** [comment]
@YakoYakoYokuYoku can you please file a separate issue? Thanks.

**Comment by YakoYakoYokuYoku** [comment]
NP sir #98596.

**Comment by hyangah** [comment]
@misolori thanks! While testing your PR, can you also please check the icon for `go.mod` file? There shouldn't be no icon assigned to it. Otherwise, that's a regression and I am happy to file an issue.

**Comment by misolori** [comment]
@hyangah we don't have any references to `.mod` files in our seti-ui directory and nearly all of our code is pulled directly from the seti repo, so i'm unsure where this is coming from. Please file a separate issue and @aeschli can look into it.

**Comment by misolori** [comment]
Verification steps: ensure that the following updates are reflected in the file explorer for file icons:

- `.go` use the new logo
- `.rmd` files point to the R icon
- `.tsx` files point to the TypeScript icon

![image](https://user-images.githubusercontent.com/35271042/82937527-275a2380-9f45-11ea-8b65-bebbdac1bb4c.png)
