### ISSUE TITLE
Settings error on visual studio

### ISSUE THREAD

**Issue by Oakcitycoder** [microsoft/vscode#98582]
Issue Type: <b>Bug</b>

when I go into settings and attempt to edit the font and tab size, an error notification pops up  "unable to write into user settings". I think it's the json code.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<img width="1280" alt="Screenshot 2020-05-26 08 23 05" src="https://user-images.githubusercontent.com/34259622/82900203-2c5da980-9f2a-11ea-812c-33630377557c.png">

[json settings.zip](https://github.com/microsoft/vscode/files/4682135/json.settings.zip)

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
beautify|Hoo|1.5.0
LiveServer|rit|5.6.1
vim|vsc|1.14.5

(1 theme extensions excluded)

</details>

**Comment by usernamehw** [comment]
Put a comma `,` at the end of the 5th line.

**Comment by Oakcitycoder** [comment]
> Put a comma `,` at the end of the 5th line.

Thanks
