### ISSUE TITLE
[loc][Query][VSCODE] Localizability of strings in vscode-editor

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode#98584]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Id | File Name Live Page Extended | String Resource ID | Full Source String | Extended Description | Answer Needed By
-- | -- | -- | -- | -- | --
49,748 | vscode-editor\vs_editor.xlf | 0;   "src/vs/editor/browser/widget/diffReview.unchangedLine" | {0} unchanged line {1} | Please, define   placeholders |  
49,756 | vscode-editor\vs_platform.xlf | 0;   "src/vs/platform/undoRedo/common/undoRedoService.ok_Duplicated10" | Undo   in {0} Files | Please,   define placeholder |  
49,776 | vscode-editor\vs_base.xlf | 0;   "src/vs/base/browser/ui/selectBox/selectBoxCustom.selectBox" | Select Box | Can you please explain this   further? We understood as "box for selection" for now. |  
49,778 | vscode-editor\vs_editor_contrib.xlf | 0;   "src/vs/editor/contrib/rename/renameInputField.label_Duplicated3" | {0}   to Rename, {1} to Preview | We   understood the placeholders as numbers for now, please confirm or advise. |  
49,779 | vscode-editor\vs_platform.xlf | 0;   "src/vs/platform/userDataSync/common/abstractSynchronizer.incompatible_Duplicated19" | Cannot sync {0} as its version   {1} is not compatible with cloud {2} | Please explain placeholder   contents/give a concrete example. |  
49,799 | vscode-editor\vs_editor.xlf | 0;   "src/vs/editor/browser/widget/diffReview.unchangedLine" | {0}   unchanged line {1} | what   do {0} and {1} refer to? |  
49,800 | vscode-editor\vs_editor_contrib.xlf | 0;   "src/vs/editor/contrib/rename/renameInputField.label_Duplicated3" | {0} to Rename, {1} to Preview | what do {0} and {1} refer to?   button name or some file name? |

**Comment by bpasero** [comment]
@isidorn for selectbox aria label

**Comment by isidorn** [comment]
@bpasero thanks. Tackled that

**Comment by alexdima** [comment]
@isidorn Can you please also take the ones in `diffReview.ts` -- some came in via https://github.com/microsoft/vscode/commit/791156d90f5a50e05236aec070166094186c01b1

**Comment by isidorn** [comment]
@alexdima just did via f48cb619ba
Thanks

**Comment by PDostalek** [comment]
We would need clarify those placeholders to have correct meaning of the string #98584 @jrieken 
Cannot find your comment @isidorn for selectBoxCustom.selectBox

**Comment by isidorn** [comment]
@PDostalek Here's my comment in code https://github.com/microsoft/vscode/blob/595d2b9b916d063aadfc2c1a8c8f6df5b45572a8/src/vs/base/browser/ui/selectBox/selectBoxCustom.ts#L732

"Behave like native select dropdown element."
