### ISSUE TITLE
Bug: High CPU usage and slow to start first time

### ISSUE THREAD

**Issue by brunolm** [microsoft/vscode#98581]
Issue Type: <b>Bug</b>

When I start insiders for the first time there's a task using 20% forever. If I stop it the extensions tab loads forever, but all extensions work normally.

It also seems that there's a long delay to start insiders now, takes a few seconds.

VS Code version: Code - Insiders 1.46.0-insider (8687508aa689b1f16d5f6ff317eb25bcf4544586, 2020-05-26T05:47:43.684Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (16.90GB free)|
|Process Argv|-n .|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.2.0
tinypng|and|0.3.3
ng-template|Ang|0.901.9
path-intellisense|chr|1.4.2
regex|chr|0.2.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
gitlens|eam|10.2.1
EditorConfig|Edi|0.15.1
prettier-vscode|esb|4.7.0
vscode-pull-request-github|Git|0.16.1
gc-excelviewer|Gra|2.1.34
rest-client|hum|0.23.2
reg|ion|1.0.1
vscode-styled-components|jpo|0.0.29
json-to-ts|Mar|1.7.5
Angular-BeastCode|Mik|8.1.2
dotenv|mik|1.0.1
vscode-docker|ms-|1.2.0
csharp|ms-|1.21.18
python|ms-|2020.5.80290
remote-wsl|ms-|0.44.2
powershell|ms-|2020.4.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2236
debugger-for-chrome|msj|4.12.8
sqltools|mtx|0.21.8
vscode-paste-image|mus|1.0.4
language-liquid|nei|0.1.1
vscode-graphql|Pri|0.2.14
ejs-language-support|Qas|0.0.1
typescript-hero|rbb|3.0.0
partial-diff|ryu|1.4.1
mdx|sil|0.1.0
addDocComments|ste|0.0.8
vscode-icons|vsc|10.1.1
change-case|wma|1.0.0
copy-with-line-numbers|yas|0.0.4

</details>

**Comment by egamma** [comment]
@brunolm please follow this guide to help us narrow down your performance problem https://github.com/microsoft/vscode/wiki/Performance-Issues.

**Comment by brunolm** [comment]
I killed the evil task and it's not happening anymore even if I close all instances of VSCode and open again. If I do reproduce it again I'll collect that info.

For now I'll close as a duplicate of https://github.com/microsoft/vscode/issues/98496 I strongly believe it's the exact same issue. I'll also post any new info in that thread.

If the problem persist afterwards I'll open a new ticket.
