### ISSUE TITLE
WebP and TIFF images icons missing

### ISSUE THREAD

**Issue by YakoYakoYokuYoku** [microsoft/vscode#98596]
The icon that WebP and TIFF images display is the default one instead of the image icon. Adding lines to `extensions/theme-seti/icons/vs-seti-icon-theme.json`:

```json
"svgx": "_image",
"tiff": "_image",
"webp": "_image",
"sublime-project": "_sublime",
```

and

```json
"svgx": "_image_light",
"tiff": "_image_light",
"webp": "_image_light",
"sublime-project": "_sublime_light",
```

does indeed solves the issue.

**Comment by aeschli** [comment]
We generate our seti-theme from files in https://github.com/jesseweed/seti-ui
as described in https://github.com/microsoft/vscode/blob/master/extensions/theme-seti/icons/vs-seti-icon-theme.json#L2. The new associations need to be made there first.

I see that with the latest update, `svgx` and `sublime-project` are now covered, but for the other ones you need to make a PR in https://github.com/jesseweed/seti-ui
