### ISSUE TITLE
rg process taking up all my CPU

### ISSUE THREAD

**Issue by samoclay** [microsoft/vscode#98594]
- VSCode Version: 1.45.1
- OS Version: MacOS Catalina 10.15.4 

Steps to Reproduce:

1. Install VScode
2. Install Node

Wasn't sure where to put this

Something is taking up all my CPU through a process called rg
![Screenshot 2020-05-26 at 16 19 26](https://user-images.githubusercontent.com/3073519/82918853-305eeb00-9f6d-11ea-99e0-321011ee74c9.png)

I ran a sample of the process [here](https://gist.github.com/samoclay/7404fa979bf2e34077fad571614a3dbb)

which appears to mention
`/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg`

So not sure how I can debug this further.

**Comment by roblourens** [comment]
This is used by search, so either you triggered a text search or file search in vscode, or an extension did, and it's taking an extremely long time to complete. Do any tips in here help? https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory

**Comment by rxmarbles** [comment]
I too am experiencing this same issue on a mac os running catalina 10.15.5 where i will find 3 - 4 rg processes running high CPU usage and draining the battery. This is on VS Code version 1.45.1

**Comment by saifeiLee** [comment]
Same here. rg process takes 100% cpu.
Osx 10.15.5
VScode: 1.45.1
![image](https://user-images.githubusercontent.com/28710808/83476878-61d33b80-a4c4-11ea-84ae-69afdb6c5f56.png)
![image](https://user-images.githubusercontent.com/28710808/83476888-6697ef80-a4c4-11ea-908f-151c7150215b.png)

**Comment by rxmarbles** [comment]
Just to provide an update here I did disable `"search.followSymlinks": false` as per the doc above this seemed to have relieved my issue with long running rg processes. However I would like to point out with monorepos becoming more popular especially with `lerna`, should probably look to improving this process in the editor in future iterations.

**Comment by a37h** [comment]
`"search.followSymlinks": false` solved my issue too, thx

**Comment by alicederyn** [comment]
Same issue, same fix.

**Comment by bnaydenov** [comment]
I can confirm, same issue and same solutions work
