### ISSUE TITLE
👁 Explorer UI toggle to hide hidden files

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode#98591]
**I'd like to see a simple 👁 button in Explorer to hide hidden files (dotfiles),** to cut visual clutter and improve focus on non-hidden files.

- **I know this could be built as an extension,** but it makes sense to include this as part of Code to encourage developer focus. The only reason to prepend a file/directory name with `.` is to hide it; the Explorer should offer a built-in way to respect this.

- **This would be most helpful with monorepos,** where hidden files litter every package directory in addition to the root directory. Generally speaking if I'm working across multiple packages, more than half of the entries visible in my Explorer at any time are hidden files/directories.

- **This is not a request for a `files.exclude` toggle in Explorer** (#21403, #53369). If I add `**/.*` to `files.exclude`, I exclude hidden files from fulltext search and quick open as well. I don't want to _exclude_ hidden files/directories, I just want to _hide_ them.

- **This could potentially be extended to also hide `.gitignore`d files.** This would be similar to the existing `search.useIgnoreFiles` + UI toggle, but for Explorer. #38878 is a very popular feature request for this.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
