### ISSUE TITLE
Extension Relevance Improvements

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#9860]
All versions of VS Code all OS.

Below are some examples where I think the extension sort order (relevance) is off.  In each case the most popular extension should also be the most relevant (based on the text match).

# C# - C# should be top
![image](https://cloud.githubusercontent.com/assets/1051190/17184200/d6c46746-53df-11e6-9b3e-a023e01a112b.png)

# Go - Go with Icon should be top
![image](https://cloud.githubusercontent.com/assets/1051190/17184229/fa12ea88-53df-11e6-8ff3-91921175ccc7.png)

# Python - Python with the transparent background should win
![image](https://cloud.githubusercontent.com/assets/1051190/17184284/42352ff6-53e0-11e6-86b1-c4cbf93f9f83.png)

cc: @waderyan

**Comment by joaomoreno** [comment]
cc @modigrv @hamenon

**Comment by hamenon** [comment]
We are working on improvements to the search relevance. We recently added a fix that gives substring matches greater importance. But FTS still treats full word matches as the same. We're looking into ways to improve that.

**Comment by joaomoreno** [comment]
Marketplace has improved their relevance sorting.

Thanks @hamenon!

**Comment by Tyriar** [comment]
C# and Python cases are fine but go case is not (using either "Go" or "go").

**Comment by joaomoreno** [comment]
ping @hamenon

**Comment by hamenon** [comment]
The go scenario will be harder to resolve as it will involve post processing, and that will likely make the search slower. We don't take into account the download count number in the relevance and base it purely on the extension name, publisher name tags and short description. Both these extensions have the same exact name, have go in the short description and tags, so they end up with the exact same score in our relevance algorithm, in which case the order in which they show is random and you can have cases like this where go shows up before Go.
