### ISSUE TITLE
Split Pane breadcrumbs focuses wrong window

### ISSUE THREAD

**Issue by tonysparks** [microsoft/vscode#98609]
- VSCode Version:
```
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```
- OS Version:
Windows 10: Windows_NT x64 10.0.18363
Steps to Reproduce:

Prerequisites:
* Have two files opened - ex. A.c, B.c; these files should have type definitions that allow breadcrumb navigation between files.

1. Open file `A.c`
2. Split Pane window (I did horizontal) - now you should have `A.c` in `left` and `A.c` in `right` panes
3. Click to gain focus in `right` pane
4. (In Right pane) Click into a definition/declaration (hold Ctrl + mouse click) that takes you to file `B.c` 
5. (`Right` pane should show `B.c` file) - Now do breadcrumb.previous (for me that is Ctrl + LeftArrow)
6. Notice the `left` pane moves to the appropriate breadcrumb location - Expected behavior would be the `right` pane moves back to file `A.c` in the appropriate breadcrumb location

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
> (Right pane should show B.c file) - Now do breadcrumb.previous (for me that is Ctrl + LeftArrow)

Something is missing here. You cannot just invoke that command, you first need to focus the breadcrumbs. How do you do that?

**Comment by tonysparks** [comment]
It does appear to be a duplicate of: https://github.com/microsoft/vscode/issues/89903

**Comment by jrieken** [comment]
there is still a gap in your steps as pointed out here https://github.com/microsoft/vscode/issues/98609#issuecomment-634549131

**Comment by tonysparks** [comment]
Maybe I'm using the wrong terminology - but essentially their Step 4 (`Press Alt+left to navigate back to the previous location.`) is what I'm referring to.

**Comment by jrieken** [comment]
Ok, I assume you mean the "Go back" (`workbench.action.navigateBack`) command, not breadcrumbs (which is the little strip the code showing the current file- and symbol-path).

**Comment by bpasero** [comment]
This issue has been reported already in either this or a similar form. Please check the label that was assigned to this issue to find it.
