### ISSUE TITLE
On macOS, when delete file dialog is open and cancel button has focus, hitting enter still deletes the file

### ISSUE THREAD

**Issue by tristan957** [microsoft/vscode#98608]
- VSCode Version: 1.45.1
- OS Version: 10.15

Steps to Reproduce:

1. Create new file
2. Delete said file
3. Notice blue highlight around Cancel button
4. Hit enter
5. Notice file was still deleted

Does this issue occur when all extensions are disabled?: Yes

**Comment by tristan957** [comment]
I have not confirmed if this happens on my Linux or Windows machines.

**Comment by bpasero** [comment]
This seems standard macOS behaviour, I suggest you file an issue against Apple.
