### ISSUE TITLE
Timeline doesn't show file saves changes

### ISSUE THREAD

**Issue by b1zzu** [microsoft/vscode#98601]
- VSCode Version: 1.45.0
- OS Version: Fedora 32

Steps to Reproduce:

1. Open a git workspace
2. Create a new file (without committing it)
3. Write some content in the file and save it
4. Edit the file (delete some of the content or add other content) and save it again
5. Open the Timeline view and instead of seeing the file history you will just see `Uncommitted Changes`
6. Open the *More Actions ...* menu
7. Only `Include: Git History` is available for selection
 
I don't know if this is the normal behavior, but because in the changelog it was documented that the timeline works also with `file saves` I'd expected it works and show changes for each saves.

> The Timeline view is now out of preview and enabled by default. This is a unified view for visualizing time-series events (for example, Git commits, file saves, test runs, etc.) for a file.
Quote: https://code.visualstudio.com/updates/v1_44#_timeline-view

Does this issue occur when all extensions are disabled?: Yes

**Comment by eamodio** [comment]
This is expected behavior as the timeline doesn't currently show file saves, just git history. The note in the release notes was about the things the timeline view *could* be used for visualizing.

Will treat this as the feature request for file save history.
