### ISSUE TITLE
[FR] Small screens: Debug toolbar docking location outside of side bar

### ISSUE THREAD

**Issue by lukepighetti** [microsoft/vscode#98606]
Option1: floating, top line, right justified
Pros: always visible
Cons: covers tabs
<img width="740" alt="Screen Shot 2020-05-26 at 4 05 15 PM" src="https://user-images.githubusercontent.com/666539/82945312-b168b300-9f6a-11ea-9c71-683cefb4055b.png">

Option 2: floating, top line, left justified
Pros: always visible
Cons: covers tabs and files icon

<img width="732" alt="Screen Shot 2020-05-26 at 4 05 27 PM" src="https://user-images.githubusercontent.com/666539/82945332-b88fc100-9f6a-11ea-885b-6add30b68415.png">

Option 3: floating, bottom line, left justified
Pros: always visible
Cons: covers search button, breadcrumbs

<img width="741" alt="Screen Shot 2020-05-26 at 4 05 47 PM" src="https://user-images.githubusercontent.com/666539/82945372-c80f0a00-9f6a-11ea-9a97-58116099f4c5.png">

Option 4: floating, bottom line, right justified
Pros: always visible
Cons: partially covers find dialog
<img width="734" alt="Screen Shot 2020-05-26 at 4 06 31 PM" src="https://user-images.githubusercontent.com/666539/82945410-de1cca80-9f6a-11ea-953e-0adcdbca59e5.png">

Option 5: docked
Pros: ????
Cons: not visible when sidebar is closed for editing, collapsed on small screens

<img width="738" alt="Screen Shot 2020-05-26 at 4 08 30 PM" src="https://user-images.githubusercontent.com/666539/82945560-263bed00-9f6b-11ea-82ad-d9171e4e92d0.png">

Recommendation: 

Revisit the debug toolbar UX to find a solution that allows it to stay always visible on small screens without the side bar open and without covering other UI elements. Maybe push the search dialog down so it's always visible when it's on the far right? Maybe put it in the vertical left-side toolbar? 

**Maybe let us pick horizontal or vertical and drag it to any part of the window?**

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
