### ISSUE TITLE
"Open Preview to Right" not showing if "Option" key pressed before hovering

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#9861]
Regarding #7666 and test item #9701

- VSCode Version: 1.4.0-insider (1.4.0-insider)
- OS Version: macOS El Capitan

Steps to Reproduce:

1. Hold <kbd>Option</kbd> key while not hovering over the "Open Preview to Right" command.
2. Then hover over the "Open Preview to Right" command.

Note that it does not change the icon.  It only changes when you are already hovering over it and then press the key.

**Comment by bgashler1** [comment]
Feel free to move to August if it's not worth the risk fixing it quickly.

**Comment by isidorn** [comment]
Not critical, and since tomorrow is thursday we only fix critical ones -> moving to august

**Comment by jrieken** [comment]
@bgashler1 Sure about the `Option` key? This implementation is about `alt` as in alternative command. I would not expect `option` to ever work

**Comment by bgashler1** [comment]
@jrieken When I say <kbd>Option</kbd>, I also mean the <kbd>Alt</kbd> key.
![img_0674](https://cloud.githubusercontent.com/assets/11839736/17903609/ff7c6462-6920-11e6-928b-d5c936d49a30.png)

When your cursor is already over this button and you press either of these keys (depending on your platform), the alternate action and its icon appear (i.e. "Open Preview to the Side").

**Comment by jrieken** [comment]
Thanks, understood.
