### ISSUE TITLE
Terminal does not use correct casing

### ISSUE THREAD

**Issue by Hyoretsu** [microsoft/vscode#98611]
If you open VSCode's terminal, a part of the project's folder gets turned to lowercase. If I go to that folder in Explorer and open PowerShell window through right-click, the folder casing is correct. In some cases, like running a React server, that messes with it and throws a warning about two paths that differ only in casing.
Visual Studio Code version: 1.45.1
![image](https://user-images.githubusercontent.com/20804322/82953068-82f5d280-9f80-11ea-9b7b-10d0d71a8421.png)

**Comment by Tyriar** [comment]
This can happen when you open the folder where it's lowercase. If it's an issue for react I suggest reporting to them to properly support case insensitive paths on Windows.
