### ISSUE TITLE
Javascript Debugger randomly pauses on Out of Memory errors

### ISSUE THREAD

**Issue by Friss** [microsoft/vscode#98616]
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 18.7.0 (Mac OSX 10.14.6)

Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Run a basic node script that runs out of memory via the debug tool
2. The debugger will pause once it hits the limit without any indication of this limit being hit. The debugger pauses even if the "Pause on uncaught exceptions" is unchecked.

<img width="1091" alt="Screen Shot 2020-05-26 at 7 03 45 PM" src="https://user-images.githubusercontent.com/4588318/82958582-abcb9700-9f83-11ea-9d9c-db2775de5131.png">

test.js
```js
var a = []
for (let i = 0; i < 9000000000; i++)
    a.push(i)
```

Launch config
```js
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "test",
      "program": "${workspaceFolder}/test.js",
      "skipFiles": [
        "<node_internals>/**"
      ]
    }
  ]
}
```

I would expect either the exception to be shown or raised.

This was reported earlier in https://github.com/microsoft/vscode/issues/83304 and closed but I think there should be a better experience when this happens. 

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

Still happens with extensions disabled.

**Comment by connor4312** [comment]
Hi, please give our [new debugger](https://github.com/microsoft/vscode-js-debug) a shot. We've fixed this there 🙂 

![](https://memes.peet.io/img/20-05-eb18d499-f257-43a0-a4eb-60759fc7952c.png)

**Comment by Friss** [comment]
Awesome 💯
