### ISSUE TITLE
Issues with window.***border settings in the theme. 

### ISSUE THREAD

**Issue by wapenshaw** [microsoft/vscode#98615]
Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

If you have these settings defined in your theme, 

```json
"window.activeBorder": "#00000000",
"window.inactiveBorder": "#00000000"
```
There is an issue with sidebar panels. They don't persist their locations across restart. I have noticed it when it started annoying me as other themes keep them where they are. 

Upon removal of these settings, the behavior is normal. 

Here is a recording of what the issue is. 
![uaPS1lYW6r](https://user-images.githubusercontent.com/739546/82772224-11a60a80-9e2e-11ea-9fc3-49bbdcd3f11c.gif)

Steps to Reproduce:

1. Install a theme with an active definition of window.activeBorder or window.inactiveBorder
2. Maximize VSCode, close and reopen VSCode 

Does this issue occur when all extensions are disabled?: Yes/No -- NA?

Edit: I forgot to mention that this also happens when you set 
```json
"workbench.colorCustomizations": {
		"window.activeBorder": "#ff0000",
	},
```

in your personal settings.json file.

**Comment by shungo27** [comment]
There is another problem. If "xxx.color-theme.json" contains "window.activeBorder" or "window.inactiveBorder", the sidebar moves very slowly.

**Comment by eamodio** [comment]
I can't reproduce this -- can you reproduce it on 1.46 (currently insiders, to be stable in a few days)?

**Comment by shungo27** [comment]
I'm having a problem with 1.45.1 slowing down the sidebar.

**Comment by eamodio** [comment]
@shungo27 please open a separate issue for that -- thanks!

**Comment by wapenshaw** [comment]
@eamodio Hello, I have checked the behaviour in the insiders edition. 

Version: 1.46.0-insider
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-09T17:34:47.110Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps I did to reproduce.

1. Download VSCode insders zip (64 bit)
2. Create data folder to make it portable
3. Open settings.json and add the following lines 

```json
{
    "workbench.colorCustomizations": {
        "window.activeBorder": "#ff0000",
        "window.inactiveBorder": "#ffffff"
	},
}
```

Still the same issue. 

Demo: https://i.imgur.com/rs82FRk.gifv
