### ISSUE TITLE
Add missing imports quick fix should come after all import actions

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#98613]
Issue Type: <b>Bug</b>

**Repo**

1. `git clone https://github.com/mjbvz/vscode-98613.git`
1. Open `index.ts` and trigger a quick fix on `abc`

**Bug**

<img width="535" alt="Screen Shot 2020-05-26 at 3 38 59 PM" src="https://user-images.githubusercontent.com/12821956/82957060-05719880-9f67-11ea-85fd-0834eb2d402a.png">
VS Code version: Code - Insiders 1.46.0-insider (b26e0bcf39c1b8faaf770265391b5a387d1d9172, 2020-05-26T17:07:53.549Z)

The 'add all missing import' action is in the middle of the other actions

OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.50GB free)|
|Process Argv|-psn_0_10402283|
|Screen Reader|no|
|VM|17%|
</details>

**Comment by pfongkye** [comment]
Hello @mjbvz 
I would like to work on this issue if no one else is.
If it's ok, any pointer to where to start will be welcomed.
Thanks.

**Comment by mjbvz** [comment]
Thanks @pfongkye but after I looked into how to better explain the problem, I realized it would require a pretty particular fix so I just went ahead and made it
