### ISSUE TITLE
Feature Request: Different Icons or colors for public, private or protected methods in the Outline view while using PHP 

### ISSUE THREAD

**Issue by ArmDubhe** [microsoft/vscode#98619]
On the outline view, will it be possible to have different icons or colors  for public, private or protected methods while using PHP.
![image](https://user-images.githubusercontent.com/49300788/82964596-7dea5080-9f8b-11ea-9579-3503fd7b1976.png)

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Aoutline
