### ISSUE TITLE
Mac Option+Shift+Arrow Doesn't Select

### ISSUE THREAD

**Issue by warling** [microsoft/vscode#98612]
Beginning with the past two nightly releases, Option+Shift+Right/Left Arrow no longer selects text as it does in all other Mac text editors. It would normally jump to the beginning/end of the current or next word/symbol while also selecting it.

Option+Left/Right Arrow jumps words as expected; adding +Shift should also select the text.

**Comment by gletthereblight** [comment]
Also happend in Win10, Alt+Shift+Right/Left/Up/Down is no longer works.

**Comment by alexdima** [comment]
@warling This works fine for me. Does the issue reproduce when disabling all extensions and commenting out all your customizations in `keybindings.json`?

@gletthereblight It is not possible that you have the same problem, as you are on Windows and the OP is on Mac. Please create a new issue if you believe there is a problem with VS Code (the likelihood of that is <1%).

**Comment by warling** [comment]
@alexdima, I've changed nothing about my settings, keybindings or extensions, but after approximately a week of this key combination not working in each new nightly build, it resolved itself as suddenly and mysteriously as it appeared.

**Comment by bkarlson** [comment]
might be related to https://github.com/microsoft/vscode/issues/99777
