### ISSUE TITLE
Changes to a task definition are not effective when the task is selected from "recently used" list

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode#98617]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Install Docker Desktop (Windows, Mac) or Docker engine (Linux). 
2. Install Docker extension by Microsoft (ms-azuretools.vscode-docker)
3. Clone https://github.com/kzadora/guestbook-express/tree/dockerized (note: 'dockerized' branch)
4. Do `Run Task` command and run `docker-build` task. Open Docker view (whale icon) and verify you have the `guestbook-express:1.0.0` image built.

![image](https://user-images.githubusercontent.com/15271049/82957697-82e9d880-9f68-11ea-808d-1b8784d6ae71.png)

5. Right click on `1.0.0` image tag, choose 'Remove...'. and confirm
6. Open `.vscode/tasks.json`  and change `dockerBuild.tag` property of the `docker-build` task to `guestbook-express:2.0.0`. Save `tasks.json` file.
7. Try `Run Task` command again

Expected: choosing recently used `docker-build` task should build the `guestbook-express` image and give it a tag of `2.0.0`

Actual: `docker-build` task shows up twice as "recently used" vs "configured". 

![image](https://user-images.githubusercontent.com/15271049/82958230-cd1f8980-9f69-11ea-91f6-747c34c33906.png)

Running the "recently used" task uses the old task settings and results in an image tagged `1.0.0`. This old task configuration survives even VS Code window restart!

This is very non-intuitive behavior and totally contrary to what developers are used to. I would never expect that VS Code will cache old task settings and use them after I save changes to the tasks file.

Does this issue occur when all extensions are disabled?: not applicable

Reproduced on Windows 10, VS Code build 1.45.1 and on Mac, VS Code Insiders build 1.46.

**Comment by bwateratmsft** [comment]
@karolz-ms does this also occur with shell tasks?

**Comment by karolz-ms** [comment]
@bwateratmsft I tried to repro with a simple shell task but couldn't. @alexr00 apologies for convoluted repro; let me know if you need any further information.

**Comment by alexr00** [comment]
The problem is that now that we more thoroughly cache recent tasks (cache the whole task instead of an ID), the recent task looks like a different task from the change tasks.json tasks. The task definition being change makes the task look like an entirely different task. This is clearly a confusing behavior.

I can fix it by adding an additional check that considers tasks with the same type and label to be the same task.
