### ISSUE TITLE
Activate embedded languages for indent rules

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#98621]
From https://github.com/microsoft/vscode/pull/98181#issuecomment-633875186

> PHP defines HTML as an embedded language here: https://github.com/microsoft/vscode/blob/master/extensions/php/package.json#L44. The bug is that VSCode doesn't activate 'html' when it needs it's indent rules. As HTML defines the indent rules in code, activation is necessary.

> It's a VSCode issue. I suggest to create a new issue and assign it to @alexdima.

**Comment by alexdima** [comment]
Currently, the `onLanguage` activation event fires only when a file that resolves to a certain language gets opened -- https://code.visualstudio.com/api/references/activation-events#onLanguage -- and not when encountering an embedded language as part of tokenization.

**Comment by roblourens** [comment]
via `extensionDependencies`? Could also do that. But it makes sense to me that if I want to add rules for the 'foo' language, then I always get activated when those rules would be applied to a region in some file.

**Comment by alexdima** [comment]
Currently, the `language-configuration.json` is read when encountering an embedded language. This is done [here](https://github.com/microsoft/vscode/blob/a59cde5933e9e3150cfd6460cdabc853032d5a91/src/vs/workbench/contrib/codeEditor/browser/languageConfigurationExtensionPoint.ts#L85-L87). But I think this must be something that the `html` extension does via API and not via the `language-configuration.json`? We want at one point to move also the `onEnter` rules to the `language-configuration.json`, perhaps that's what's missing here?

**Comment by roblourens** [comment]
Yeah, the html extension uses `vscode.languages.setLanguageConfiguration` with onEnterRules, wordPattern, and indentationRules.

**Comment by andrestone** [comment]
Hi!

Is there any workaround for this? 

I have an autocompletion extension that works with `onLanguage` activation and I'd like to have it working when the language is used as `embeddedLanguage`.

Thanks.

**Comment by alexdima** [comment]
Since we now support defining regular expression in `language-configuration.json` files, we could simply move the `setLanguageConfiguration` calls to the JSON files.
