### ISSUE TITLE
Blue bar briefly shows through taskbar

### ISSUE THREAD

**Issue by kewbish** [microsoft/vscode#98622]
- VSCode Version: 1.45
- OS Version: Windows 10 1909

Steps to Reproduce:
1. Open VSCode. In this specific case, I was opening a recent folder.  
 This thin blue bar shows up over the taskbar (which is not transparent) briefly.
![image](https://user-images.githubusercontent.com/45278276/82969378-5cd23180-9f84-11ea-908c-b5e410b9cc71.png)  
After minimizing and maximizing the window and maximizing other windows, the blue bar disappears.  

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I think I have heard about this before, but suspect an Electron and/or OS issue.

**Comment by 5dao** [comment]
>     * VSCode Version: 1.45
> 
>     * OS Version: Windows 10 1909
> 
> 
> Steps to Reproduce:
> 
>     1. Open VSCode. In this specific case, I was opening a recent folder.
>        This thin blue bar shows up over the taskbar (which is not transparent) briefly.
>        ![image](https://user-images.githubusercontent.com/45278276/82969378-5cd23180-9f84-11ea-908c-b5e410b9cc71.png)
>        After minimizing and maximizing the window and maximizing other windows, the blue bar disappears.
> 
> 
> Does this issue occur when all extensions are disabled?: Yes

#99415

please vote it.

**Comment by 5dao** [comment]
@bpasero  @deepak1556 

#99415

please vote it.

**Comment by deepak1556** [comment]
@kewbish is this still an issue with our latest insiders https://code.visualstudio.com/insiders ?

**Comment by kewbish** [comment]
I no longer use VSCode on Windows, so I'm unable to confirm. It wasn't a common issue back when I was using it however, so I'm unsure if / how it can be replicated.

**Comment by deepak1556** [comment]
Closing per above comment, thanks!
