### ISSUE TITLE
@remarks TSDoc links to an actual person named "remarks"

### ISSUE THREAD

**Issue by 5argon** [microsoft/vscode#98626]
Issue Type: <b>Bug</b>

If you hover the mouse over [TSDoc](https://github.com/Microsoft/tsdoc) `@remarks`, it shows this popup. It should be an exception not to show a person named "remarks" in this case.

![image](https://user-images.githubusercontent.com/5653276/82978588-27265a80-a00f-11ea-8bd4-e9a6823417f7.png)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
svelte-intellisense|ard|0.7.1
vsc-prolog|art|0.8.23
npm-intellisense|chr|1.3.0
mustache|daw|1.1.1
prettier-vscode|esb|4.7.0
dotnet-test-explorer|for|0.7.1
vscode-pull-request-github|Git|0.16.0
vscode-mocha-test-adapter|hbe|2.4.0
vscode-test-explorer|hbe|2.19.0
svelte-vscode|Jam|0.9.3
vscode-edit-csv|jan|0.2.9
vscode-peacock|joh|3.7.2
docomment|k--|0.1.11
graphql-for-vscode|kum|1.15.3
Kotlin|mat|1.7.1
vscode-clang|mit|0.2.3
HTMLHint|mka|0.7.0
lc3-assembly|mke|0.1.5
csharp|ms-|1.21.18
cpptools|ms-|0.28.1
Go|ms-|0.14.3
vsliveshare|ms-|1.0.2236
color-highlight|nau|2.3.0
language-liquid|nei|0.1.1
much-assembly-required-language-support|PJB|0.1.5
java|red|0.62.0
postcss|ric|2.0.0
text-marker|ryu|1.11.0
vscode-bolt-language|smk|0.0.4
ayu|tea|0.18.0
vsfire|tob|1.4.1
ink|tom|0.1.0
sort-lines|Tyr|1.9.0
unity-debug|Uni|2.7.5
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.1
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.22.4
vscode-maven|vsc|0.21.4
vim|vsc|1.14.5
better-align|wwm|1.1.6
vscode-surround|yat|1.0.2
vscode-proto3|zxh|0.4.2

(34 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
This is coming from one of your extensions, possible the vscode-pull-request-github one. Please file an issue against them
