### ISSUE TITLE
drag vscode file drop into web doesn't work

### ISSUE THREAD

**Issue by 02ff** [microsoft/vscode#98629]
[work]
1. if once open file at chrome, then drag vscode file drop into chrome work (chrome succesfuly open file)

2. drag file (that in eclipse explorer) drop into web file upload page work.
3. drag file (that in pycharm explorer) drop into web file upload page work.

[doesn't work]
1. If hadn't opened file at chrome before, drag vscode file drop into chrome then, just redirect to "about:blank#blocked" page.

2. drag file (that in vscode explorer) drop into web file upload page doesn't work.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo you haven't said what version you are using.

If not Insiders then I suggest you install that and retest.

**Comment by 02ff** [comment]
VS Code version : 1.45.0 (user setup)
d69a79b73808559a91206d73d7717ff5f798f23c
date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by gjsjohnmurray** [comment]
I suggest you give Insiders a try. It can coexist with the regular release you are using.

**Comment by 02ff** [comment]
OK. i will install Insiders Edition then, try this(=drag vscode file drop into web) thanks gjsjohnmurray!

**Comment by 02ff** [comment]
i tried but same issue... :(

Version: 1.46.0-insider (user setup)
Commit: 876f2e70f9a2e1988887f8ca82294418afac15a2
Date: 2020-05-27T05:43:41.115Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134

and i find another thing...

[work]
4. drag file (that in vscode explorer) drop into chrome "tab bar" (chrome succesfully open file)

**Comment by 02ff** [comment]
I think this issue seems to have some relation to this CASE.

CASE : when drag file (that in vscode explorer) drop into open MS-Word file,
-> then show just file path. (ex. C:\Users\....)

but other IDE (eclipse, pycharm) 
-> then show Real File

**Comment by bpasero** [comment]
This issue has been reported already in either this or a similar form. Please check the label that was assigned to this issue to find it.

**Comment by 02ff** [comment]
OK the keyword was "dnd", thanks!
