### ISSUE TITLE
Excessive Sync Requests

### ISSUE THREAD

**Issue by FizzBuzz791** [microsoft/vscode#98620]
Issue Type: <b>Bug</b>

Not sure, I left VS Code running overnight and when I came back to my computer this morning it shows a notification that sync was disabled due to excessive requests.

VS Code version: Code - Insiders 1.46.0-insider (8687508aa689b1f16d5f6ff317eb25bcf4544586, 2020-05-26T05:47:43.684Z)
OS version: Windows_NT x64 10.0.19631

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         960  @ 3.20GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.99GB (2.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
dotnet-test-explorer|for|0.7.1
docomment|k--|0.1.11
git-graph|mhu|1.23.0
csharp|ms-|1.22.0
remote-wsl|ms-|0.44.2
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.1.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by bestpika** [comment]
Same problem here.

**Comment by bestpika** [comment]
#98599

**Comment by sandy081** [comment]
/duplicate

Sorry for this. We are working on fixing this - #98625
