### ISSUE TITLE
Support Smooth Scrolling in tree widgets

### ISSUE THREAD

**Issue by musm** [microsoft/vscode#98627]
- VSCode Version: 1.45.1
- OS Version:
![image](https://user-images.githubusercontent.com/4319522/82978704-324b9d00-9fb3-11ea-899a-f263a85d2b90.png)

Steps to Reproduce:

![1](https://user-images.githubusercontent.com/4319522/82979095-2d3b1d80-9fb4-11ea-8c32-cd2dd9986033.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/98175
