### ISSUE TITLE
Settings sync error - too many requests

### ISSUE THREAD

**Issue by texnicii** [microsoft/vscode#98637]
Issue Type: <b>Bug</b>

Setting sync said - Error while starting Sync: Too many requests. Allowed only 100 requests in 5 minutes.

VS Code version: Code - Insiders 1.46.0-insider (b26e0bcf39c1b8faaf770265391b5a387d1d9172, 2020-05-26T16:16:10.519Z)
OS version: Linux x64 4.19.0-9-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) Gold G5400 CPU @ 3.70GHz (4 x 3699)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.74GB (1.22GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.4.0
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
git-project-manager|fel|1.7.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-sublime-merge|gio|0.1.2
git-graph|mhu|1.23.0
vscode-docker|ms-|1.2.1
sublime-keybindings|ms-|4.0.7
bootstrap4-vscode|the|6.1.0
vscode-docker-ws|tii|0.4.1

</details>

**Comment by olofwalker** [comment]
I had the same issue, sync was turned off, and cannot be enabled. 

```Error while starting Sync: Request 'https://vscode-sync.trafficmanager.net/v1/manifest' failed because of Unauthorized (401).```

**Comment by FredrikLindseth** [comment]
I got the same error too. Pasting from VS Code below 👇 


Issue Type: <b>Bug</b>

VS Code gave me a 

VS Code version: Code - Insiders 1.46.0-insider (2591ede95a52400d5d22989b16706f9b8b4831da, 2020-05-22T21:13:15.709Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (6.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|3.0.1
vscode-django|bat|0.20.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.35.2
vscode-eslint|dba|2.1.5
xml|Dot|2.5.0
gitlens|eam|10.2.1
prettier-vscode|esb|4.7.0
vscode-firefox-debug|fir|2.8.0
dotnet-test-explorer|for|0.7.1
vscode-pull-request-github|Git|0.16.1
vscode-drawio|hed|0.5.2
Ionide-fsharp|Ion|4.11.1
mechanic|Ion|0.0.19
mediawiki|jak|2.1.0
vscode-peacock|joh|3.7.2
chat|kar|0.33.0
guid|kos|0.0.1
gnuplot|Mar|1.0.11
rainbow-csv|mec|1.7.0
csharp|ms-|1.21.18
mssql|ms-|1.9.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.5.80290
remote-containers|ms-|0.118.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
js-debug-companion|ms-|1.0.0
powershell|ms-|2020.4.0
vsliveshare|ms-|1.0.2236
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.3.4
vscode-jest|Ort|3.2.0
vscode-yaml|red|0.8.0
wordcount|rid|0.1.33
nunjucks|ron|0.3.0
bash-beautify|sha|0.1.1
splunk|Sko|0.0.1
vscode-icons|vsc|10.1.1
vscode-wakatime|Wak|4.0.0

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
/duplicate

#98625
