### ISSUE TITLE
Search editor: resolves content even if not the active editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98639]
Steps to Reproduce:

1. open a search editor and save it
2. make sure it has contents
3. click on another tab thus making it inactive
4. add a console.log statement into [`getModel`](https://github.com/microsoft/vscode/blob/fb3dc8be662b22054148544a6ccd4e5e2af52531/src/vs/workbench/contrib/searchEditor/browser/searchEditorInput.ts#L320)
5. reload window

=> 🐛 the contents are resolved

That is not the idea of editors in VSCode, the model should only get loaded if:
* the model is dirty (e.g. restored from backup)
* the editor is active

**Comment by JacksonKearl** [comment]
Why should the model get loaded immediately if it is dirty? As in is there danger in always waiting until the editor is active to resolve the model?

**Comment by bpasero** [comment]
> Why should the model get loaded immediately 

We have to, because otherwise language services would not see these changes when they start up. They would load contents of the file on disk and not the model as it is dirty in VSCode, so we need to forcefully load any dirty model on startup.
