### ISSUE TITLE
Add option `editor.scrollbar.vertical/horizontal` as official

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#98632]
Is there any chance that the setting of `editor.scrollbar.vertical` and `editor.scrollbar.horizontal` will be official?
I currently have the "Unknown configuration setting" notification 😬
A lot of people using this option and it would be good to add it as official

![obraz](https://user-images.githubusercontent.com/30685349/82982115-be7ab600-9fed-11ea-8f61-e5d1ac3028a3.png)

**Comment by kanlukasz** [comment]
> 
> 
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [Add option `editor.lineDecorationsWidth` as official (#93887)](https://www.github.com/microsoft/vscode/issues/93887)

This is not a duplicate

**Comment by gjsjohnmurray** [comment]
Related - #35454, #66000

**Comment by escaner** [comment]
So, how do you upvote it?

**Comment by t00** [comment]
Will this change include disabling fading scrollbars in all VS Code sections including navigation (left)?

**Comment by gbritton1** [comment]
note that if you set e.g. vertical scrollbar to hidden, the gutter still appears:
![image](https://user-images.githubusercontent.com/12263288/112172537-2d537c00-8bcb-11eb-8e65-fe17033828ea.png)
Ideally there would be no gutter (where the scroll bar would be, if visible) but just more screen area in its place.  In my screenshot that would push the minimap all the way to the right of the tab window

**Comment by ZooDoo4U** [comment]
I'm curious what all will the fixed when this is resolved?  There are a number of requests related to this from a number of people.   First is making the scroll bars visible, but will they still be transparent?   Then once visible, what colors setting will be allowed...

**Comment by kanlukasz** [comment]
https://code.visualstudio.com/updates/v1_58#_editor-scroll-bar-customization

**Comment by t00** [comment]
@kanlukasz The new settings does not seem to be affecting file navigation panel where scrollbars are still automatically fading out. Are there any plans to fix this section as it is considerably more troublesome with fading scrollbars than editor where code structure preview bar can act as always visible scrollbar?
