### ISSUE TITLE
Not to "Trim Trailing Whitespace" for patch files

### ISSUE THREAD

**Issue by PengWang-SMARTM** [microsoft/vscode#98631]
I did a brief search but did not find an answer for this. I noticed that "Diff Editor" has an option to "Ignore Trim Whitespace", which is actually checked. Obviously it doesn't help. Probably that's because I'm editing patch files directly in a normal editor window.

Is it possible to add a white list so the "Trim Trailing Whitespace" rule won't be applied to certain type of files? Or make the tool smart enough to determine if the whitespaces are needed before removing them depending on the file type or contents.

Please let me know if any existing extension exists. Thanks!

**Comment by alexdima** [comment]
@PengWang-SMARTM Yes, e.g.
```
"[cpp]": { "files.trimTrailingWhitespace": false }
```
