### ISSUE TITLE
vue 部分没有提示，保存文件反应慢

### ISSUE THREAD

**Issue by zhnagyaxinjiayou** [microsoft/vscode#98634]
Issue Type: <b>Feature Request</b>

vue 部分没有提示，存文件反应慢

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

**Comment by Aaronsms78** [comment]
Translation: Vue does not have code suggestion/auto-completion，and saving a file is slow.

**Comment by egamma** [comment]
Auto completion for vue is provided by this extension https://marketplace.visualstudio.com/items?itemName=octref.vetur. If there are issues with this, then please report the issue against this extension.
