### ISSUE TITLE
A unkown page for github when open the VS Code

### ISSUE THREAD

**Issue by KringMiao** [microsoft/vscode#98643]
When I open the Vs Code,after a few minutes,it will show a dialog for github login,but that does not what I need.So it looks like a problem for using VS Code.Can you help me?

**Comment by egamma** [comment]
/needsMoreInfo

What kind of dialog shows up, pls add a screenshot? 
Which extensions do you have installed?

**Comment by KringMiao** [comment]
@egamma Thaks a lot.It`s because of some reasons about the net speed in my school that I can`t attch some inages.And now I find it maybe the Git is the problem`s answer.When I use the git to push the changes that it will show a dialog for login the github.I will do my best to attch those image about the dialog and my owner extensions .Finally，thanks for your response.

**Comment by KringMiao** [comment]
@egamma Hello,here are those screenshots.First is the dialog, and others are my owner extensions.
![github-login-un](https://user-images.githubusercontent.com/45806121/83116265-1dc7eb80-a0fe-11ea-9f3c-4133c217150f.PNG)
![vscode-extensions01](https://user-images.githubusercontent.com/45806121/83116319-31735200-a0fe-11ea-904c-6992a522ecce.PNG)
![vscode-extensions02](https://user-images.githubusercontent.com/45806121/83116448-6089c380-a0fe-11ea-81e1-a53e1ed4ec5a.PNG)
OKay,that is all.Thanks for your help.

**Comment by egamma** [comment]
Which version of VS Code are you running?
Is the project you are opening backed by a github repository?

**Comment by KringMiao** [comment]
@egamma The version  of my VS Code is 1.45.1.And the last time I used VS Code, I devided my working window into two parts.The one is my working content.Another is working for a project cloned from a github repository.When I finshed something, I closed the VS Code and did others.However, when I open the VS Code again, I face this view.Excuse my poor English.

**Comment by joaomoreno** [comment]
This is related to Git and GitHub for Desktop. VS Code invokes Git and tries to fetch from your repository. Your configured authentication method seems to be GitHub for Desktop.

If you'd like to disable automatic fetching in VS Code, please set the setting `git.autofetch` to `false`.
