### ISSUE TITLE
Suggestion. Highlight unsaved files in explorer.

### ISSUE THREAD

**Issue by AlexPritchin** [microsoft/vscode#98647]
Hello. I would like to suggest to add a new feature to VSCode.

It would be good if VSCode highlights unsaved files in the explorer tree view. It might be implemented like highlighting of file with error. But for unsaved file the color of filename might be stay unchanged like standard color. E.g. gray for dark theme. Or filename could be highlighted with white color for dark theme for example. So unsaved file could be highlighted only with a dot but the color of this dot could be different. E.g. white instead of red for dark theme. Also this highlighting should have lowest priority. So unsaved highlight should be replaced by error in file or/and git highlight.

It would be useful feature because only limited number of tabs are shown in tabbar at the same time. And git doesn't see changes in unsaved files.

I know that there is unsaved files extension exists but it offers a different approach to solving this problem.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by AlexPritchin** [comment]
Thank you for quick response.
