### ISSUE TITLE
markdown preview do not show images in parent dir

### ISSUE THREAD

**Issue by caoshen** [microsoft/vscode#98640]
- VSCode Version: 1.45.1 (user setup)
- OS Version: Windows_NT x64 10.0.18362

Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. open markdown file in preview tab
2. images in "../../pics/" dirs cannot preview

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Is the `pic` directory part of your workspace? The markdown preview can only load resources that in the current workspace

**Comment by caoshen** [comment]
@mjbvz thanks，open folder works
