### ISSUE TITLE
Perf machine: print the Electron version as part of the info

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98642]
I think it would help if the output of the performance runs included the Electron version.

//cc @jrieken

**Comment by jrieken** [comment]
Not a fan because the electron version is just one of many factors that influence startup perf. We usually know quite well what version is used and all the version, version, perf-tick etc pp is in kusto.

**Comment by bpasero** [comment]
@jrieken the reason I bring this up is that we had a few runs from the Exploration quality that had good numbers (in the range of E7) and we were surprised and not sure why that is. As Deepak found out the revert to E7 ended up on the exploration branch without us knowing about it.

![image](https://user-images.githubusercontent.com/900690/83003645-e3cbec00-a00e-11ea-8f89-3dc45d6c76e2.png)

**Comment by jrieken** [comment]
I know but I think we should just investigate properly when some unexpected report shows up (just like we do for test failures) and not print more and more into the bot (which is already quite noisy)

**Comment by deepak1556** [comment]
> Not a fan because the electron version is just one of many factors that influence startup perf. 

Isn't https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/performance/electron-browser/startupTimings.ts just adding some debug data to the final report after the perf values are generated, adding version data from the process object shouldn't affect negatively if I understanding it correctly.
