### ISSUE TITLE
difftool not work

### ISSUE THREAD

**Issue by starjesse** [microsoft/vscode#98648]
- VSCode Version: 1.45.1
- OS Version: Windows 10

Steps to Reproduce:

1. code -d test.cpp test1.cpp
2. do not display any difference(line 24 is different, seem like two seperated editor, not diff editor). And when I switch line in the right editor, the left does not move together. 
![image](https://user-images.githubusercontent.com/33248281/83016989-6c6d7b00-a055-11ea-9fc3-92578eea4a88.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
/needsMoreInfo please include the two files `test.cpp` and `test1.cpp`

**Comment by starjesse** [comment]
[cpp.zip](https://github.com/microsoft/vscode/files/4689260/cpp.zip)

Yes, I attach them now.

I have two devices, one Win10 and one Macos, connect to same remote. Macos's vscode works fine, but Win10's vscode works not good.

**Comment by egamma** [comment]
Cannot reproduce given the steps provided, pls see below

![image](https://user-images.githubusercontent.com/172399/83067544-25888100-a067-11ea-9b15-2b62823a953d.png)

**Comment by starjesse** [comment]
> Cannot reproduce given the steps provided, pls see below
> 
> ![image](https://user-images.githubusercontent.com/172399/83067544-25888100-a067-11ea-9b15-2b62823a953d.png)

Yes, so I think there is some problem in my `code` binary.
In the picture you shown I can find up/down arrow.
![image](https://user-images.githubusercontent.com/33248281/83089708-93659480-a0c9-11ea-84ac-63d24fd2ffcd.png)

But I can't see in my code diff editor.
![image](https://user-images.githubusercontent.com/33248281/83089760-af693600-a0c9-11ea-9d67-a5193f90d4e6.png)

**Comment by starjesse** [comment]
![image](https://user-images.githubusercontent.com/33248281/83091273-674c1280-a0cd-11ea-8167-8c45159cf11c.png)

I switch the suffix from cpp to txt, and the diff works. It seems like problem in cpp compares.

**Comment by starjesse** [comment]
![image](https://user-images.githubusercontent.com/33248281/83103325-0fbba000-a0e9-11ea-9224-77a4916329c4.png)

I clear the configuration of workbench.editorAssociations and it works.
