### ISSUE TITLE
events.js:287       throw er; // Unhandled 'error' event     

### ISSUE THREAD

**Issue by saurabhprasadsah** [microsoft/vscode#98650]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by saurabhprasadsah** [comment]
when use server.js file then error always throw

**Comment by saurabhprasadsah** [comment]
when we run the server.js file in server then after sometime it happen is that code is not working ...
it is not use proper way

**Comment by egamma** [comment]
Please provide detailed steps for how to reproduce the error and provide more details about the error. Where does the error show up, please include a screenshot of the error message and please include the file server.js.

**Comment by saurabhprasadsah** [comment]
okay thanks
