### ISSUE TITLE
Workplace window has a shade

### ISSUE THREAD

**Issue by Aaronsms78** [microsoft/vscode#98659]
Just downloaded vscode, and install Nord theme extension. A shade which I'm pretty sure is not supposed to be there appear at the workplace window. Tried other custom themes as well with the same issues. Default available themes do not cause such issue.

![image](https://user-images.githubusercontent.com/58265908/83040358-c0865880-a071-11ea-8218-bf8e497fa6a7.png)

**Comment by IllusionMH** [comment]
Looks like duplicate of #85452

/needsMoreInfo
Is it fixed if you launch VS Code as `code --disable-gpu` ?

If it works - see https://github.com/microsoft/vscode/issues/85452#issuecomment-558334562 for steps how to make it without passing `--disable-gpu` each time.

**Comment by Aaronsms78** [comment]
Yea seems like a duplicate issue. Just have it fixed. Thanks!
