### ISSUE TITLE
Closing background tab does not dispose dirty text models

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#98653]
* open `fileA.ts` that exports a symbol that is used in `fileB.ts`
* rename a symbol in `fileA.ts`
* (`fileB.ts` opens as a background tab)
* save all
* hit the `x` on the `fileB.ts` tab
* observe (through logging) that `fileB.ts` is not disposed

Now do the same steps, but first click on the tab with `fileB.ts` before hitting `x`. Now, `fileB.ts` is disposed.

---

Notice how `fileB.ts` and `fileC.ts` do not get disposed:
![Kapture 2020-05-27 at 15 39 52](https://user-images.githubusercontent.com/5047891/83027414-62855100-a030-11ea-9707-a9fb33188323.gif)

---
Notice how `fileB.ts` and `fileC.ts` get disposed now:
![Kapture 2020-05-27 at 15 41 58](https://user-images.githubusercontent.com/5047891/83027678-ae37fa80-a030-11ea-9b0d-a492c10bc0eb.gif)

**Comment by testforstephen** [comment]
Have tried the fix in the insider, looks like the dirty text models don't exist any more. But i observe a side effect on the moving file scenario.

A typical workflow as below:
- Open file A.java in VS Code.
- Modify file A.java and add some contents, and leave it unsaved.
- Drag and drop A.java to a new folder f1.
- I observed the following events happening:
-> didClose { uri: A.java }
-> didOpen { uri: f1/A.java, version: 1, text: <the contents in the disk file> }
-> didChange { uri: f1/A.java, version: 2, contentsChanges: <the unsaved changes before move> }

When moving files, the VS Code would modify the unsaved files again to restore the dirty state. If i want to enable refactoring feature based on the move operation, the silent didChange behavior from VS Code client probably conflicts with the refactoring job. 

Is it possible to restore the unsaved model contents in the didOpen event directly when reopening the newly moved file?

**Comment by bpasero** [comment]
@testforstephen I am not sure what you are trying to build, but do you maybe rather wanna use `vscode.onWillRenameFiles` and `vscode.onDidRenameFiles` to participate in that operation?

**Comment by testforstephen** [comment]
YES, i register listener on the renameFiles event for refactoring operation. IMO, how you restore the model is something that the client implements, and from the user's point of view, i just need know when to close the old file and open the new file. didChange is not user-operated.

**Comment by bpasero** [comment]
It is true that we first load the model from disk and then update it with the previous contents if you look at this code:

https://github.com/microsoft/vscode/blob/1cc95bad5440a0ce78db0bf0d2913f3f48325166/src/vs/workbench/services/textfile/common/textFileEditorModelManager.ts#L224-L240

It would probably make more sense to load the model directly with the contents we had before, but we currently have no way of doing so.

**Comment by bpasero** [comment]
I suggest a follow up issue to investigate 👍

**Comment by testforstephen** [comment]
Created a new issue https://github.com/microsoft/vscode/issues/100255
