### ISSUE TITLE
Git change autodetection not working in directories/links created with subst

### ISSUE THREAD

**Issue by zdavidsen** [microsoft/vscode#98667]
Issue Type: <b>Bug</b>

1. `git clone ... C:\Repos\ActualRepo`
1. `subst X: C:\Repos`
1. `code X:\ActualRepo`

Expected:
Git detects file changes and shows them in the source control tab

Actual:
Git doesn't auto detect any changes, either from an external editor or from within code.  Manual refresh does work.  Opening C:\Repos\ActualRepo does not have this issue

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (15.67GB free)|
|Process Argv|W:\KeeperPowerShellProvider\|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-opennewinstance|chr|0.0.7
vscode-svgviewer|css|2.0.0
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-peacock|joh|3.7.2
csharp|ms-|1.21.18
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
cpptools|ms-|0.28.1
vscode-scheme|sjh|0.4.0
msbuild-project-tools|tin|0.3.5
shell-launcher|Tyr|0.4.1
omnipascal|Wos|0.18.0

</details>

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/5970

**Comment by zdavidsen** [comment]
Just to follow up, that looks like it might be it.. Pretty sure the reason I just now noticed it is because of a semi-recent workflow change. I tried rolling back to January and still had the problem, so that seems like a pretty good indicator that it was my behavior that changed, not code's.
