### ISSUE TITLE
Find with regex

### ISSUE THREAD

**Issue by godabavinay** [microsoft/vscode#98661]
Issue Type: <b>Bug</b>

when I'm using searching using regular expressions in visual stdio code the output of search is not what it should be.

When I typed \b[a-z]{4}\b this pattern in the find and searched the output also highlights 4 letter words that contain caps.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.5.80290
remote-wsl|ms-|0.44.2
cpptools|ms-|0.28.1
LiveServer|rit|5.6.1
clang-format|xav|1.9.0

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you have Match case toggle (Aa icon) turned on?

**Comment by godabavinay** [comment]
Sorry, I did not turn on the Match case. It's working properly.
