### ISSUE TITLE
Custom Titlebar is incomplete and not draggable

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#98669]
Running OSS on Windows yields no controls and an undraggable window. This is new since yesterday and I see you have made changes near title bar service so assigning to you.

**Comment by joaomoreno** [comment]
@sbatten @bpasero Steps?

**Comment by bpasero** [comment]
Just run on Windows and verify you get window controls.

**Comment by joaomoreno** [comment]
LGTM

![image](https://user-images.githubusercontent.com/22350/83767194-a0602600-a67d-11ea-9d53-cdbdb431a287.png)
