### ISSUE TITLE
tsserver 100% CPU

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#98665]
Issue Type: <b>Bug</b>

Ran into this issue a couple of times with VS Code repo recently with TypeScript 3.9.3, the syntax only tsserver is running fine.

VS Code version: Code - Insiders 1.46.0-insider (876f2e70f9a2e1988887f8ca82294418afac15a2, 2020-05-27T05:41:02.088Z)
OS version: Darwin x64 19.4.0
Remote OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.95GB free)|
|Process Argv|-psn_0_3576681|
|Screen Reader|no|
|VM|12%|

|Item|Value|
|---|---|
|Remote|SSH: penlv-imac|
|OS|Darwin x64 19.4.0|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 6182)|
|Memory (System)|32.00GB (21.50GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
gitlens|eam|10.2.1
tsl-problem-matcher|eam|0.2.0
vscode-pull-request-github-insiders|Git|2020.5.38341
vscode-docker|ms-|1.2.1
vscode-language-pack-zh-hans|MS-|1.46.0
remote-containers|ms-|0.118.0
remote-ssh-edit-nightly|ms-|2020.5.19620
remote-ssh-nightly|ms-|2020.5.19620
js-debug-nightly|ms-|2020.5.1917
powershell|ms-|2020.4.0
vscode-github-issue-notebooks|ms-|0.0.24
vsliveshare|ms-|1.0.2236
debugger-for-chrome|msj|4.12.8
kuskus-extensions-pack|ros|1.0.1
kuskus-kusto-language-server|ros|1.0.1
kuskus-kusto-syntax-highlighting|ros|1.1.8
sourcekit-lsp|unp|0.0.1
notebook-renderers|vsc|1.0.0
notebook-test|vsc|1.0.0

(5 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
@rebornix Did you run `yarn` before this happened? Sometime a yarn install can trigger this

**Comment by rebornix** [comment]
Right, I `yarn` after fetching master due to electron version change. Will keep an eye on this.

**Comment by mjbvz** [comment]
Thanks. I believe this is the same issue as https://github.com/microsoft/TypeScript/issues/37653 then. I'm going to test out the potential TS fix for this

**Comment by rebornix** [comment]
I can confirm that the issue I was seeing was the typescript bug linked above, every time after `yarn`, tsserver goes to 100%.

**Comment by mjbvz** [comment]
Just updated VS Code to use TypeScript 4.0 in the workspace. Please let me know if you see this again after running yarn install
