### ISSUE TITLE
How can I open a second integrated terminal from first one

### ISSUE THREAD

**Issue by johnson-byjus** [microsoft/vscode#98670]
I need to execute a chain of tasks that need a terminal for each one. To do so, Is there a command that opens a new integrated terminal tab from a previous integrated terminal.?

**Comment by Tyriar** [comment]
There's ctrl+shift+` to open a new terminal and ctrl+shift+5 to split a terminal.

![image](https://user-images.githubusercontent.com/2193314/83669404-652efb80-a586-11ea-92e3-1f70c20a2efc.png)
