### ISSUE TITLE
Can't Auto Import

### ISSUE THREAD

**Issue by machineghost** [microsoft/vscode#98672]
- VSCode Version: 1.45.1
- OS Version: Linux x64 4.15.0-32-generic

**Steps to Reproduce:**

1. Create:

File A:

    export const foo = () => {};

File B:

    foo();

2. According to https://stackoverflow.com/questions/38210604/visual-studio-code-automatic-imports it seems like I should have a light bulb next to `foo()`, which lets me import it automatically ... but I don't.  If ALT + ENTER it I see "No code actions available".

**Does this issue occur when all extensions are disabled?:** Yes

One other note: I also can't "Go to Definition" of `foo()`, and here's my jsconfig.json in case the options are relevant:

```
{
  "compilerOptions": {
    "module": "esnext",
    "moduleResolution": "node",
    "baseUrl": "."
  }
}
```

**Comment by mjbvz** [comment]
Please share a small example project because this is works fine for me:

<img width="380" alt="Screen Shot 2020-05-28 at 11 49 24 AM" src="https://user-images.githubusercontent.com/12821956/83181133-4d183180-a0d9-11ea-93ee-e33a7a700d2c.png">

**Comment by mjbvz** [comment]
Oh actually you are probably in plain JS. That post is all about auto imports for TypeScript

To get auto imports quick fixes in JS, you must enable type checking: https://code.visualstudio.com/docs/nodejs/working-with-javascript#_type-checking-javascript

(quick fixes only show up when errors are reported)
