### ISSUE TITLE
Folders not ordered alphabetically

### ISSUE THREAD

**Issue by Dispersia** [microsoft/vscode#98676]
- VSCode Version: 1.46.0-insider
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Create the following folders:
- A.A
- A.B
- A.A.A

 These should be ordered A.A, A.A.A, A.B. They are currently in the order above.

 However,
 - A
 - B
 - A.A

 is ordered correctly in the explorer. We append .Tests to the end, so would be nice to keep these folders together

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Please search for order and file-explorer tag to find duplicates

**Comment by Dispersia** [comment]
I did, and didnt (and still don't) see an issue that is in any way related to this one. Do you have a specific link?

https://github.com/microsoft/vscode/issues?q=is%3Aopen+label%3Afile-explorer++order
