### ISSUE TITLE
Add a recovery mode that does not restore previous state if detected to crash

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#98674]
Issue Type: <b>Bug</b>

to repro:
- set your difftool to vscode
- open a git repo with > 100 files
- make changes to every file
- stage all the files
- right-click the 'Staged Changes' header in the 'Source Control' panel and choose 'Open all Changes (with difftool)', this will attempt to open >100 instances of vscode.
- vscode will eventually crash
- restart vscode
- vscode will eventually crash
- restart vscode
- ...

vscode needs to set a flag post-startup that indicates that the startup completed. if that flag is not set during the next startup then it should not attempt to load previous state.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.66GB (5.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.56.1:2222|
|OS|Linux x64 3.10.0-1127.el7.x86_64|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|3.70GB (0.11GB free)|
|VM|100%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-intelephense-client|bme|1.4.0
php-debug|fel|1.13.0
svn-scm|joh|2.11.1
cpptools|ms-|0.28.1
cmake|twx|0.0.17
plsql-language|xyz|1.8.2

</details>

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by Spongman** [comment]
no, it's not an extension issue. my machine just isn't capable of opening 100 vscode instances.

**Comment by bpasero** [comment]
@Spongman I was asking because I could not find such a command in my installation. So I wonder if maybe an extension added it. 

Slightly related: do you have `window.openFilesInNewWindow` configured in settings?

**Comment by Spongman** [comment]
it's there. did you follow the repro steps precisely?

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/83123530-51425000-a0d5-11ea-9b93-5c4f3fe2ae20.png)

**Comment by Spongman** [comment]
- stage all the files

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/83123809-ac744280-a0d5-11ea-8fc4-b83965877364.png)

@joaomoreno can you help please

**Comment by Spongman** [comment]
- right-click the 'Staged Changes' header

**Comment by Spongman** [comment]
really, though. this bug isn't about the means by which it crashes on startup. the bug is that if vscode automatically performs actions on startup that cause it to crash (whatever they may be), it will continue to do that every time it starts up, making it impossible to fix.

instead, it should only perform automatic startup actions (like opening previously opened files, workspaces, etc...) if the _previous_ startup completed successfully.

**Comment by bpasero** [comment]
Understood, and that makes sense to me. But I am still not sure why this command would decide to open 100 windows when it could simply do everything from one window.

**Comment by Spongman** [comment]
why was this closed ? was it fixed?
