### ISSUE TITLE
Adopt shadow dom for the context view service

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#98673]
PR #97965 fixes issues with maintaining focus inside a dom element when the context view is opened. However, by rendering as a child of other DOM elements we risk unintended DOM interaction via css or otherwise. As a workaround for now, this has been scoped to a handful of widgets that need the behavior change. Now we have debt that we should invest in making the context view a shadow dom node that has all of its css injected to avoid unintended interaction.

/cc @joaomoreno

**Comment by joaomoreno** [comment]
Interesting! 👍
