### ISSUE TITLE
JS autocomplete recommends and inserts out-of-context symbols

### ISSUE THREAD

**Issue by abbondanza** [microsoft/vscode#98686]
- VSCode Version: 1.43.2
- OS Version: Win 10 Enterprise v1909; build 18363.836

Steps to Reproduce:

1. Create a brand new JS file with the following contents:
```javascript
const o = {
  f: function() {},
};

```
2. Attempt to type in `...args` within the f function's parentheses.

Notice how `.apply` (this is just because apply is the first recommendation) is automatically inserted for each dot that is typed. This can also be reproduced in TS files.  The odd part is that `.apply` doesn't even belong in the argument list. Also, I've noticed that this does not happen with free functions, only ones that are defined within an object.

Reproduction GIF:

![776EC0C3-052B-4010-9416-9FAF3D5710EC](https://user-images.githubusercontent.com/5099199/83078173-fb26cb80-a046-11ea-856d-0c7214663691.GIF)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by yume-chan** [comment]
@mjbvz I can reproduce this with latest insider build and extensions disabled.

Version: 1.46.0-insider
Commit: 876f2e70f9a2e1988887f8ca82294418afac15a2
Date: 2020-05-27T05:41:02.088Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/TypeScript/issues/38840 to track upstream
