### ISSUE TITLE
Not able to get any extensions

### ISSUE THREAD

**Issue by amirhosseindavoody** [microsoft/vscode#98685]
# VS code information:
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

# Steps to Reproduce:

1. Search for any extension in marketplace
2. The following message is shown
![image](https://user-images.githubusercontent.com/8355965/83074604-4af59a80-a027-11ea-8057-d6c75187d916.png)
3. Open developer tools -> Network: look for errors

![image](https://user-images.githubusercontent.com/8355965/83074693-78424880-a027-11ea-9b6f-bdc569a78a86.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Maybe #34385 is relevant

**Comment by egamma** [comment]
/needsMoreInfo

Has this worked for you before?
Are you behind a proxy? If you are please check the following documentation https://code.visualstudio.com/docs/setup/network#_proxy-server-support

**Comment by amirhosseindavoody** [comment]
> /needsMoreInfo
> 
> Has this worked for you before?
> Are you behind a proxy? If you are please check the following documentation https://code.visualstudio.com/docs/setup/network#_proxy-server-support

I used to be able to update VS code and get extensions before the latest release.
I am not able to do any of those after I updated to 1.45.1

I am not using any proxy either, but I am on a company network.

**Comment by amirhosseindavoody** [comment]
> Maybe #34385 is relevant

I followed some of the recommendations that seemed to have more likes, but non of them helped.

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by chrmarti** [comment]
@amirhosseindavoody Do you any of the `HTTP_PROXY`, `HTTPS_PROXY` or `NO_PROXY` environment variables set? Or maybe the `http.proxy` setting in VS Code? Starting with 1.45 we allow these to override the OS settings.

**Comment by amirhosseindavoody** [comment]
Yes, I had it HTTP_PROXY and HTTPS_PROXY environment variables set. Deleting them resolved the issue. But how is there any way to keep them? I need them to use pip install and I don't want to type the proxy setting every time.

Thanks for the help.

**Comment by chrmarti** [comment]
@amirhosseindavoody If they work for pip I wonder why they don't work for VS Code. Could you post the values you have for HTTP_PROXY and HTTPS_PROXY? (If privacy is a concern with these, you could replace all letters with x and all digits with 1, keeping all other characters as they are.)

**Comment by amirhosseindavoody** [comment]
@chrmarti Here is the censored proxy settings http://xxxxx-xxxx.xxxx.xxx:111

**Comment by amirhosseindavoody** [comment]
Maybe this is a dumb question, but where should I get the netlog.json file.

**Comment by chrmarti** [comment]
@amirhosseindavoody When run like this the file should be written in the folder where you start VS Code from in the terminal.

**Comment by amirhosseindavoody** [comment]
@chrmarti I am starting VScode using the following command in cmd.exe but there is no json output file.
`code --log-net-log=netlog.json`

**Comment by chrmarti** [comment]
Make sure you close all VS Code windows before starting from the command line again.

**Comment by yamenarahman** [comment]
This a common issue cause by proxies.
I've solved this on macOS by adding these DNS: 
8.8.8.8
8.8.4.4

Go to network -> Advanced -> DNS tab 
Then add the above IPs to DNS servers.
