### ISSUE TITLE
Refresh in Explorer not picking up new files

### ISSUE THREAD

**Issue by elsigh** [Microsoft/vscode#9868]
- VSCode Version: 1.3.1
- OS Version: OSX El Capitan 10.11.6

Steps to Reproduce:

1. touch somedir/file.foo
2. click the refresh icon in the Explorer
3. file does NOT appear in the Explorer in the list of files in somedir
4. QuickOpen - type part of file name - it appears there.

**Comment by freebroccolo** [comment]
I've been noticing this a lot lately too. Running "Files: Refresh Explorer" directly from the command palette doesn't help either.

**Comment by bpasero** [comment]
Maybe you configured an exclude rule to hide it?

**Comment by elsigh** [comment]
@bpasero No, if that were so than my description wouldn't make sense. After I run quick-search/open on the file it then shows up in the Explorer, which it wouldn't if it were excluded.

**Comment by bpasero** [comment]
@elsigh screenshots video please

**Comment by elsigh** [comment]
@bpasero Did you try to repro and couldn't? I guess because it always happens for me I feel like putting more work on me to make a video is a little lame.
Here is a video though (in 480p)

[visualcode.mov.zip](https://github.com/Microsoft/vscode/files/407850/visualcode.mov.zip)

**Comment by bpasero** [comment]
@elsigh thanks, there are much easier tools to produce videos on mac (https://www.macupdate.com/app/mac/49461/licecap) that produce gifs that you can just paste into comments here and have much better quality than your video that I can almost not see. But I will try, thanks.

**Comment by bpasero** [comment]
@elsigh can you do what you did again but this time running "code --verbose" and opening the developer console (from help menu)? This should print a lot of file events that happen or errors related.

**Comment by elsigh** [comment]
I haven't done this yet, but fwiw if I git add the file it tends to show up with refresh

**Comment by bpasero** [comment]
Ping

**Comment by elsigh** [comment]
Since the 1.4.0 release I think this is fixed.
