### ISSUE TITLE
flutter app keep launching after stop it and run it again

### ISSUE THREAD

**Issue by dernoun** [microsoft/vscode#98683]
Issue Type: <b>Bug</b>

I am facing a strang problem where the flutter app keep lauching after stop  the app and start it again, but if i close the emelator and run it again the app starts the first time and keep in launching if i stop it and run it again

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 4.15.0-101-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz (8 x 2881)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.58GB (0.15GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
lorem-ipsum|Tyr|1.2.0
better-comments|aar|2.0.5
bracket-pair-colorizer-2|Coe|0.1.4
dart-code|Dar|3.10.2
flutter|Dar|3.10.2
vscode-author-generator|edw|0.0.10
vs-code-xml-format|fab|0.1.5
code-runner|for|0.10.0
kotlin|fwc|0.2.11
todo-tree|Gru|0.0.176
pubspec-assist|jer|1.0.3
vscode-gutter-preview|kis|0.26.1
vscode-typescript-next|ms-|4.0.20200526
color-highlight|nau|2.3.0
dartgettersetter|Pet|0.0.4
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.17.0
vscode-manifest-yaml|Piv|1.17.0
vscode-spring-boot|Piv|1.17.0
material-icon-theme|PKi|4.1.0
java|red|0.62.0
vscode-yaml|red|0.8.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.1
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.22.4
vscode-maven|vsc|0.21.4
vscode-spring-boot-dashboard|vsc|0.1.10
vscode-spring-initializr|vsc|0.4.8

</details>

**Comment by egamma** [comment]
Please report the issue against the flutter extension.
