### ISSUE TITLE
Market won't load

### ISSUE THREAD

**Issue by KunalGehlot** [microsoft/vscode#98689]
Issue Type: <b>Performance Issue</b>

If I type anything in MarketPlace, it keeps loading forever.

VS Code version: Code - Insiders 1.46.0-insider (876f2e70f9a2e1988887f8ca82294418afac15a2, 2020-05-27T05:43:41.115Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (10.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    91	  3944	code-insiders main
    1	   188	  4856	   gpu-process
    0	    97	  7200	   window (Issue Reporter)
    0	    53	 11736	   electron-crash-reporter
    0	    41	 13020	   utility
    0	   102	 16008	   shared-process
    1	   191	 16976	   window (altacv.cls - My Resume - Visual Studio Code - Insiders)
    0	    12	  1048	     watcherService 
    0	    11	 11788	       console-window-host (Windows internal process)
    0	    75	  7712	     searchService
    0	   228	 14304	     extensionHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (altacv.cls - My Resume - Visual Studio Code - Insiders)
|    Folder (My Resume): 4 files
|      File types: tex(3) cls(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-opennewinstance|chr|0.0.7
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
jupyter|don|1.1.5
gitlens|eam|10.2.1
prettier-vscode|esb|4.7.0
code-runner|for|0.10.0
beautify|Hoo|1.5.0
vscode-peacock|joh|3.7.2
vscode-github|Kni|0.30.3
vscode-kubernetes-tools|ms-|1.2.0
python|ms-|2020.6.81425-dev
remote-containers|ms-|0.118.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.28.1
vsliveshare|ms-|1.0.2236
material-icon-theme|PKi|4.1.0
vscode-yaml|red|0.8.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.7
vscode-arduino|vsc|0.3.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.0.0

(1 theme extensions excluded)

</details>

**Comment by egamma** [comment]
/needsMoreInfo it is not clear what you mean by:

>If I type anything in MarketPlace, it keeps loading forever.

Where do you type into the MarketPlace? When does the loading forever happen.

**Comment by KunalGehlot** [comment]
I'm sorry about that. 

Not always, but most of the time, when I search for any extension on VSCode Marketplace in the app, it just keeps loading forever. Not only that but it also sometimes takes a long time for an app to install if I'm able to open the marketplace at first.

The latest update v1.46.0 fixed most of it, but I still stumble upon it every now and then.

**Comment by egamma** [comment]
@KunalGehlot are you behind a proxy?

**Comment by KunalGehlot** [comment]
> @KunalGehlot are you behind a proxy?

Nothing, clean windows and VSCode install, haven't been even a week

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)
