### ISSUE TITLE
Change between splitted terminals on hover, without the need of click

### ISSUE THREAD

**Issue by tifDev** [microsoft/vscode#98687]
**When you have multiple splitted terminals, you just change focus by hovering over them with the mouse.**
[Tilix](https://github.com/gnunn1/tilix) terminal has this feature.
It would be awesome to add this feature to VScode.

**Comment by tifDev** [comment]
This relates with https://github.com/microsoft/vscode/issues/98475

**Comment by Tyriar** [comment]
Let's track there

/duplicate
