### ISSUE TITLE
#region comments automatically fold while editing code

### ISSUE THREAD

**Issue by dufferzafar** [microsoft/vscode#98697]
VS Code version: Code - Insiders 1.46.0-insider (8687508aa689b1f16d5f6ff317eb25bcf4544586, 2020-05-26T05:44:44.454Z)
OS version: Linux x64 4.19.122-1-MANJARO
Remote OS version: Linux x64 4.15.0-70-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.49GB (4.29GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: szafarlinux.gurg|
|OS|Linux x64 4.15.0-70-generic|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 4000)|
|Memory (System)|15.50GB (0.48GB free)|
|VM|0%|
</details><details><summary>Extensions (78)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
swagger-snippets|adi|0.0.1
expect|bda|0.1.0
vscode-sccconfig|be5|0.3.2
coddx-alpha|cod|0.2.28
vcard|cst|1.0.1
ini-for-vscode|Dav|0.0.4
vscode-dash|dee|2.4.0
auto-region-folder|DNE|1.0.1
LogFileHighlighter|emi|2.8.0
output-colorizer|IBM|0.1.2
ldif|jta|0.2.0
expand-region|let|0.1.4
sxhkdrc-syntax|mos|0.0.1
vscode-apache|mrm|1.2.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
sublime-keybindings|ms-|4.0.7
vsnotes|pat|0.7.1
diff|raf|0.0.1
vscode-yaml|red|0.8.0
shebang-snippets|rpi|0.1.4
latex-snippets|sab|0.1.1
jinjahtml|sam|0.13.0
vscode-nginx|sha|0.6.0
gitconfig|sid|2.0.1
dot|Ste|0.0.1
hosts|tom|1.1.1
vscode-websearch|Two|1.5.0
vscode-icons|vsc|10.1.1
snippet|vsc|0.8.1
viml|Xad|0.0.2
vscode-base64|ada|0.1.0
Bookmarks|ale|11.2.0
sublime-cmd-shift-d|and|1.2.2
clock|ang|1.0.1
pgformatter|bra|1.14.0
insert-unicode|bru|0.8.0
better-toml|bun|0.3.2
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
transformer|dak|1.6.0
chmod|dle|1.1.1
LogFileHighlighter|emi|2.8.0
vscode-projects-plus|fab|1.23.3
vscode-projects-plus-todo-plus|fab|1.6.10
vscode-todo-plus|fab|4.17.1
vscode-drawio|hed|0.5.2
vscode-settings-cycler|hoo|1.0.1
rest-client|hum|0.23.2
search-editor-apply-changes|jak|0.1.1
vscode-random|jre|1.6.1
vscode-insertdatestring|jsy|2.2.4
google-tasks|kri|0.2.6
codeacejumper|luc|3.3.2
rainbow-csv|mec|1.7.0
git-graph|mhu|1.23.0
python|ms-|2020.5.80290
sublime-keybindings|ms-|4.0.7
sqltools|mtx|0.21.8
autodocstring|njp|0.5.2
openapi-designer|phi|0.3.0
vscode-gitignore-generator|pio|1.0.1
text-power-tools|qcz|1.11.1
quicktype|qui|12.0.46
vscode-sort-json|ric|1.18.0
edit-with-shell|ryu|1.2.0
multi-command|ryu|1.4.0
todotasks|san|0.5.0
just|ske|2.0.0
vscode-fileutils|sle|3.0.1
vscode-input-sequence|tom|0.2.0
json2yaml|tux|0.2.0
vscode-terminal-here|Tyr|0.2.4
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.0.0
sublime-commands|Zar|0.1.0
commentbars|zfz|0.0.10

</details>

Steps to Reproduce:

1. Create a Python file with some `#region` comments
2. When opening this file, all regions automatically fold themselves - which is okay
3. Unfold a region
4. Hover over a symbol (like a function) in this region
5. Press Ctrl while hovering over the symbol
6. The region folds itself
7. Now, I can't jump to a symbol's definition using Ctrl + Click - because before I can click, the region is folded.

![VSCode-AutoFold-2](https://user-images.githubusercontent.com/1449512/83095610-5ac1bd00-a0c1-11ea-9575-b4ba811ae979.gif)

Does this issue occur when all extensions are disabled?: No

This could be related to the Python extension's Go to definition functionality.

I have set `"editor.foldingStrategy": "indentation"` in the settings.

**Comment by aeschli** [comment]
Does this reproduce with all extensions disabled?

**Comment by dufferzafar** [comment]
@aeschli No, it doesn't reproduce with extensions disabled, and since this was happening for me in Python files (haven't tried it on other files)

I guess the Python extension might be to blame. Do I need to re-create the issue on their repo?

**Comment by aeschli** [comment]
Yes, if you can recreate the issue in https://github.com/Microsoft/vscode-python, that would be great.
 (Unfortunately, the issue-transfer tool only works with write access on both repos, which I haven't)

**Comment by dufferzafar** [comment]
@aeschli This doesn't seem to be Python specific.

Here is the same issue in JavaScript files:

![VSCode-AutoFold-JS](https://user-images.githubusercontent.com/1449512/83516439-b1316000-a4f4-11ea-890b-9997cc861775.gif)

**Comment by aeschli** [comment]
So maybe it's a different extension causing the behavior? If you can find the problematic extension, that would be great. I don't know these extensions but based on the description I suspect https://marketplace.visualstudio.com/items?itemName=DNEK.auto-region-folder

**Comment by dufferzafar** [comment]
I wasn't aware that this extension was installed. I've removed it, and the behaviour still remains.

Just wondering, have you tried reproducing this? Are you not experiencing this?

**Comment by aeschli** [comment]
Yes, I have tried and I'm not able to reproduce with just the built-in extensions. Also, I'm not aware of any other reports of such an issue.

You have mentioned that it does not reproduce with all extension disabled. Is that still correct? If so the issue is with one of the extensions installed (according to the issue description you have over 78 extensions installed!). It would be great if you can find the problematic extension. That would help other users as well.
