### ISSUE TITLE
Expandables not keeping previous height/position

### ISSUE THREAD

**Issue by ChildishGiant** [microsoft/vscode#98699]
Issue Type: <b>Bug</b>

It seems like expandables (I don't know what they're called) can't retract downwards so always move upwards over time. 

![](https://thumbs.gfycat.com/ReadySnivelingEasternglasslizard-size_restricted.gif)

Steps to Reproduce:

1. Minimise all but the bottom expandable
2. Move them all as far down as possible
3. Expand one (not the bottom one)
4. Retract it again 

Does this issue occur when all extensions are disabled?: Yes
![HairyTidyGazelle](https://thumbs.gfycat.com/HairyTidyGazelle-size_restricted.gif)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600X Six-Core Processor            (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.84GB free)|
|Process Argv|E:\code\cloverleaf\npm|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by joaomoreno** [comment]
Well... there really is not good answer here. What would you suggest we do?

**Comment by ChildishGiant** [comment]
I feel like this should be addressed in some way, as the current behaviour leads to more and more of the screen being taken up by blank space over time, unless the user resizes things. My solution ,although I lack knowledge of the workings of the ui, would be to make it so if an expandable needs to expand up, it's flagged as having done so and when toggled off will then retract downwards instead of upwards.
