### ISSUE TITLE
First tab not rendering right.

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#9869]
- VSCode Version: 1.3.1
- OS Version: OS X 10.11.3

Normal tabs must be rendered as:

![](https://cloud.githubusercontent.com/assets/2157285/17191281/806877a0-545e-11e6-98ed-87fa4153444d.png)

With 2 borders at right and left. However the first tab always renders like this:

![](https://cloud.githubusercontent.com/assets/2157285/17191307/a29d5dae-545e-11e6-8568-b69cabb25e4d.png)

If you notice, in the left side of the tab has a bad rendering. In the dark it's really fine but in the light it renders bad. I suggest having a border or something around there...

As always.
I hope you're doing great and thanks for the awesome editor.
Pouya

**Comment by bpasero** [comment]
I don't mind how it looks today, but @bgashler1 fyi
