### ISSUE TITLE
Make notification toasts movable

### ISSUE THREAD

**Issue by ankitbko** [microsoft/vscode#98701]
![image](https://user-images.githubusercontent.com/3169316/83103320-1986d880-a0d4-11ea-8197-3803e6ab08fe.png)

Could we have a feature to hide/move the popups? As you can see in this screenshot it hides the size of the layer. Many times it hides important information on terminal.

**Comment by ankitbko** [comment]
Now I am not sure if it qualifies as a feature or UI bug, @bpasero ?

**Comment by jagretz** [comment]
This would be nice feature, but I am actually wondering if there is an option to hide all notifications (errors, from extensions, etc) after (configurable) "x" number of seconds?
