### ISSUE TITLE
Disable spelling suggestions

### ISSUE THREAD

**Issue by OoDeLally** [microsoft/vscode#98708]
A way to disable the `Change spelling to 'xxx'` suggestion item.
- In most cases, the other suggestions are better (e.g. fixing a missing import).
- I rarely misspell, since I extensively use the autocomplete feature (typescript support is awesome).

Therefore I don't need this feature, and I do not want it to clutter my suggestion list. Especially since it usually manages to be the top-suggestion, so I need to manually skip it every time.

**Comment by egamma** [comment]
This code action is reported by an extension, please report the issue/feature request against the spelling extension you are using.

**Comment by OoDeLally** [comment]
@egamma Could you double-check this?
I disabled all my extensions and restarted vscode, and still have the feature working.

![image](https://user-images.githubusercontent.com/1717629/83151468-e6a50a80-a0fc-11ea-851f-a68255779758.png)
