### ISSUE TITLE
Gutter is filled with undesired "outline" indicators

### ISSUE THREAD

**Issue by Stokestack** [microsoft/vscode#98700]
Issue Type: <b>Bug</b>

HI. I've disabled code-folding and any other option I can find that would account for grey lines and indentation indicators appearing in the gutter of my files, but they remain.
<img width="735" alt="WTGutter" src="https://user-images.githubusercontent.com/196304/83101905-3d143980-a068-11ea-857b-30e53f32b2d8.png">
Either there's no option to get rid of this, or it needs a better description.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (8.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by egamma** [comment]
You have the setting `editor.renderWhitespace` enabled that renders whitespace. You can change this setting to `none`.

**Comment by Stokestack** [comment]
Thanks for the reply.

Actually, the relevant item was "render indent guides."
