### ISSUE TITLE
[Markdown] Add angle brackets to language configuration

### ISSUE THREAD

**Issue by Ash258** [microsoft/vscode#98706]
Suitable for both `brackets` and `surroundingPairs`

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links
https://www.markdownguide.org/basic-syntax/#urls-and-email-addresses

```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by egamma** [comment]
/needsMoreInfo can you please describe you suggestion in more detail?

**Comment by Ash258** [comment]
Angle brackets should be handled as surrounding pair similar to normal bracket.

![A](https://i.imgur.com/q8iQDnu.gif)

**Comment by egamma** [comment]
@Ash258 thanks for following up, the use of angle brackets is very language specific.
