### ISSUE TITLE
Debug icon not visible in latest from master

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98704]
Today I see no debug icon in the activity bar.

**Comment by yc9274** [comment]
Yeah, I also can't see
![image](https://user-images.githubusercontent.com/32420644/83125361-0df7d980-a0f5-11ea-9c3b-3e273f91f85c.png)

**Comment by IllusionMH** [comment]
Removed in https://github.com/microsoft/vscode/commit/261c5b2863a046d0b0dd38a59ea043e4f1ffbc7f#diff-48ef009e5058687f1c59d44419ae3358
Looks like `debug-alt-2` not longer in font and `debug-alt` has different character code `\f102` but it's actually `\eb91` in font

**Comment by misolori** [comment]
Sorry about that, I must've copied the wrong unicode character when I was cleaning up the unused debug icons. Looking into @IllusionMH's PR right now.
