### ISSUE TITLE
Can't preview  css hex color

### ISSUE THREAD

**Issue by Kerinlin** [microsoft/vscode#98702]
Issue Type: <b>Bug</b>

When i use less with template in vue project,the color can't preview.
![with less](https://s1.ax1x.com/2020/05/28/tZmhFO.png)

![with scss](https://s1.ax1x.com/2020/05/28/tZnGtO.png)
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
vscode-npm-dependency|how|1.2.2
vscode-language-pack-zh-hans|MS-|1.45.1
vetur|oct|0.24.0
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.7

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
What's the file type of that file?

**Comment by Kerinlin** [comment]
> What's the file type of that file?

.vue

**Comment by aeschli** [comment]
Please file the issue against the vue extension: https://github.com/vuejs/vetur/issues
