### ISSUE TITLE
Re-add option to disable timeline

### ISSUE THREAD

**Issue by palfrey** [microsoft/vscode#98718]
https://github.com/microsoft/vscode/commit/46679eee363519cc2a8f73a111d6175a941d1b41 and https://github.com/microsoft/vscode/commit/0a8ffc6bcbde9d156f130ecc4943f1309dc056f5 enabled the timeline on stable, but removed the option to disable it. I don't want the timeline view, and so I'd like the `timeline.showView` setting returned so it can be disabled. It can be set to default enabled however, in line with current behaviour.

**Comment by egamma** [comment]
@palfrey you can hide a view using the context menu available on its titlebar:

![image](https://user-images.githubusercontent.com/172399/83140193-f832e600-a0ed-11ea-9c6c-45546175c618.png)

**Comment by eamodio** [comment]
As this is directly supported in the UI (for any view), I'm going to close this.
