### ISSUE TITLE
Running on windows10 1809 is slower then linux

### ISSUE THREAD

**Issue by xiaoping378** [microsoft/vscode#98714]
Issue Type: <b>Performance Issue</b>

Running on windows10 1809 is slower then linux.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 3.10.0-1062.12.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (9.10GB free)|
|Process Argv|D:\Documents\WeChat Files\yiyemeishui\FileStorage\File\2020-05\es数据备份迁移.md|
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|SSH: Huawei|
|OS|Linux x64 3.10.0-1062.12.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6278C CPU @ 2.60GHz (8 x 2600)|
|Memory (System)|15.51GB (12.61GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   111	 17064	code main
    0	    27	  2984	   utility
    0	   157	  3620	   window (Visual Studio Code)
    0	    66	  6624	     extensionHost
    0	     6	 18320	     winpty-process
    0	     4	 12916	       C:\Windows\System32\cmd.exe /c (type "C:\Users\xxp\AppData\Local\Temp\vscode-linux-multi-line-command--uawei-134787797.sh" | ssh -T -D 62379 Huawei bash) & exit /b 0
    0	     9	  4092	         ssh  -T -D 62379 Huawei bash
    0	    10	 17716	       console-window-host (Windows internal process)
    0	   282	  6568	   gpu-process
    0	    12	  6976	   electron-crash-reporter
    0	    75	 12480	   window (Issue Reporter)
    0	    72	 18976	   shared-process

Remote: SSH: Huawei
CPU %	Mem MB	   PID	Process
    0	     0	  9302	remote agent
    0	     0	  9636	   extensionHost
    0	     0	  9649	     /bin/bash
    0	     0	  9958	       zsh -l
    0	     0	 22876	   /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: SSH: Huawei;
```

</details>
<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.2.1
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
vscode-kubernetes-tools|ms-|1.2.0
python|ms-|2020.5.80290
quicktype|qui|12.0.46
vscode-yaml|red|0.8.0
vscodeintellicode|Vis|1.2.7
markdown-all-in-one|yzh|3.0.0

</details>

**Comment by egamma** [comment]
What operations are running slower?
Do you have Defender exclusions configured?
To narrow down a performance issue please follow this guide https://github.com/microsoft/vscode/wiki/Performance-Issues
