### ISSUE TITLE
PR Proposal: Open arbitrary commits with diff viewer

### ISSUE THREAD

**Issue by rigdern** [Microsoft/vscode#9871]
I would like to add a feature to VS Code in order to address a gap in my usage of it. I figured I should writeup my idea before submitting a pull request in order to get feedback from the VS Code team and maximize the chances that my PR will be along the lines of something the team will be interested in accepting.

### Motivation

VS Code has a fantastic diff viewer. It let's you see a list of changed files and, when you click on a file, it shows you the entire file and what changed in it. However, it is limited to seeing changes in your index and working tree. I'd like to extend the diff viewer so that it can be used to view the changes included in arbitrary commits.

This cannot be done as an extension because extensions cannot render into the side pane where the diff viewer displays the list of changed files.

In my workflow, I interact with git through the command line and through VS Code. Viewing diffs is one thing that VS Code can do much better than the command line so I'd like to see this feature in VS Code.

### Proposal

VS Code currently has a few side panes and one of them is for interacting with git. I propose extending it to support multiple views. The functionality that VS Code ships with today will be called the "Status" view. It shows you the changes in your index and working tree. The only change is that there will be a dropdown at the top of the pane for switching between views:

![image](https://cloud.githubusercontent.com/assets/199935/17192989/d7876aae-5405-11e6-9898-27c5e2d718e4.png)

There will be another option in the dropdown called "History". This represents a new view which enables you to view the changes in a particular commit. This is what it will look like:

![image](https://cloud.githubusercontent.com/assets/199935/17193126/6f417772-5406-11e6-84f9-cff2ee4a1517.png)

It will have two input fields. If you want to see the changes in a particular commit, you can enter the commit name into the first field. As you would expect, you can click on a changed file to view its diff:

![image](https://cloud.githubusercontent.com/assets/199935/17193009/ec9cd136-5405-11e6-83fe-21b89ceb6200.png)

If you want to view all of the changes in a range of commits, you can leverage the second field. For example, here I'm viewing all of the changes that occurred between my feature branch, `rigdern/diff`, and `master`:

![image](https://cloud.githubusercontent.com/assets/199935/17193015/f11ebdb4-5405-11e6-8bfc-954e60931214.png)

You may be wondering how developers will find the names of the commits to put into the two input fields. I've thought of a couple of options:
  1. One option is that they'll get them from an external tool. For example, in my case I'll get them from running `git log` on the command line. As I alluded to earlier, the command line works fine for browsing commit messages but it's not very good for looking at diffs.
  2. Another option is through a VS Code extension. We could expose an extension API enabling extensions to set the commit that the new git "History" view is displaying. Then a developer could write an extension which provides the functionality of `git log` within VS Code. It could interact with the new git "History" view when the user clicks on a commit in the log.

VS Code Team, what do you think of this proposal? I'd like to get some feedback on it and, if this is a feature you'd be interested in having, I'm interested in working on a pull request.

**Comment by joaomoreno** [comment]
I'd be reluctant in having such a feature, especially due to the way you'd have to input the refs in input boxes. Instead I'd argue to just implement a history view, like suggested in #68. You get diffing for free via context menu actions.

**Comment by stevencl** [comment]
Thanks for the idea and the detailed design and description. We discussed in our UX meeting and would rather that we step back and look holistically at the whole Git experience and determine how best we provide support for the likes of Git history etc.

**Comment by rigdern** [comment]
@stevencl Thanks for reviewing my proposal. Is supporting git history etc. something you are working on soon or is that more of a long term goal?

**Comment by stevencl** [comment]
It's more of a long term goal. We need to investigate and determine what we think we should do.
