### ISSUE TITLE
find inner unused function 

### ISSUE THREAD

**Issue by zhangenming** [microsoft/vscode#98711]
```js
function neverReadFuncOutter() {//this will hint   neverRead
  neverReadFuncInner()
}
function neverReadFuncInner() {} // but this not
```
now, neverReadFuncOutter can find this is never read
but inner unused function cant find , like neverReadFuncInner
can this be done? thanks

**Comment by mjbvz** [comment]
`neverReadFuncInner` is being used inside `neverReadFuncOutter`. Marking variables as unused if they are only used in other unused functions is rather difficult (any may not be the expected behavior).

Our unused detection  checks if a variable is used anywhere in the current file
