### ISSUE TITLE
Make the search function aware of language semantics

### ISSUE THREAD

**Issue by GuillaumeRossolini** [microsoft/vscode#98713]
Hi,

A use case I come across infrequently, but is always a big time sink, is when I need to look up complex function/procedure/method usage. For example, locate a specific method when it is called with at least 3 parameters.
One way to go about this could be with a regexp search, but as flexible as that is, language semantics make this non trivial to impossible, and always time consuming.

Would it be possible to use the language's awareness of its own semantics to improve the search function in vscode?

Thanks,

**Comment by egamma** [comment]
/needsMoreInfo which search function are you referring to? The `Find All References` function does a semantic reference search. The Search function does a full text search.

What language are you using?

**Comment by GuillaumeRossolini** [comment]
Thank you, `Find all references` should be the best approach but it doesn't return everything.
I just did a text search on the name of a random function in the codebase I am working on, and that gave me 5 results, while Find all references knew about 4. If I try it on the 5th one, it tells me there are no results.
At the moment I am using JS and PHP.

**Comment by egamma** [comment]
>I just did a text search on the name of a random function in the codebase I am working on

What language are you using in this project? Did you do a Find all References search for a PHP or JS symbol?

**Comment by GuillaumeRossolini** [comment]
In this specific case it was a PHP symbol search on a legacy codebase

**Comment by egamma** [comment]
Find all References for PHP is implemented by the PHP extension you are using. Therefore please file an issue against this extension.
