### ISSUE TITLE
Hide not important folders

### ISSUE THREAD

**Issue by diamond95** [microsoft/vscode#98710]
Is it possible to create Hide option for folders that I'm not using in my project? 
For example I have _node_modules_ in my project, and I want to hide it (right click?)..

**Comment by deitry** [comment]
You should put `**/node_modules` pattern into `files.exclude` option in settings

**Comment by egamma** [comment]
This is already supported as described by @deitry. There are extensions that provide context menu actions to exclude folders, e.g., https://marketplace.visualstudio.com/items?itemName=RedVanWorkshop.explorer-exclude-vscode-extension
