### ISSUE TITLE
Debugger icon missing

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode#98722]
Issue Type: <b>Bug</b>

With the last insiders update the icon has vanished.

<img width="170" alt="image" src="https://user-images.githubusercontent.com/30625381/83139866-58755800-a0ed-11ea-8dee-beb08a79a931.png">

VS Code version: Code - Insiders 1.46.0-insider (1d268b701376470bc638100fbe17d283404ac559, 2020-05-28T08:45:32.560Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|-psn_0_8026023|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by egamma** [comment]
see also https://github.com/microsoft/vscode/pull/98716
