### ISSUE TITLE
The terminal process terminated 

### ISSUE THREAD

**Issue by whatan** [microsoft/vscode#98720]
Issue Type: <b>Bug</b>

The terminal process terminated with exit code: 3221225477

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz (8 x 3700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (3.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
yandex-translate|air|1.0.7
insertnumbers|Asu|0.9.1
random-string-password-generator|bib|1.0.2
color-info|bie|0.5.1
vscode-glsllint|CAD|1.0.0
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
indent4to2|Com|0.1.2
scala|dal|0.0.5
vscode-eslint|dba|2.1.5
vscode-hasher|dee|1.0.1
javascript-ejs-support|Dig|1.3.1
marshal-command-code|din|1.1.2
gitlens|eam|10.2.1
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
php-intellisense|fel|2.3.14
auto-rename-tag|for|0.1.3
vscode-nginx-conf-hint|han|0.1.0
asciidecorator|hel|0.2.0
beautify|Hoo|1.5.0
graphql-for-vscode|kum|1.15.3
mcjson|Lev|0.4.1
edge|luo|0.3.2
dotenv|mik|1.0.1
vscode-docker|ms-|1.2.1
csharp|ms-|1.21.18
python|ms-|2020.5.80290
cpptools|ms-|0.28.1
debugger-for-chrome|msj|4.12.8
php-docblocker|nei|2.1.0
vetur|oct|0.24.0
laravel-blade|one|1.21.0
emoji|Per|0.0.3
sass-indented|rob|1.5.1
code-settings-sync|Sha|3.4.3
vscode-nginx|sha|0.6.0
indenticator|Sir|0.6.0
shader|sle|1.1.4
addDocComments|ste|0.0.8
ejs-snippets|Tao|0.1.0
ayu|tea|0.18.0
sort-lines|Tyr|1.9.0
php-docblock-generator|vin|0.0.1
vscode-icons|vsc|10.1.1
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
map-replace-js|Yuk|0.2.2

(8 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Do you have anti-virus software that could be blocking the terminal? If so try following the instructions in https://code.visualstudio.com/docs/editor/integrated-terminal#_how-do-i-fix-the-errors-connectnamedpipe-failed-windows-error-232-or-terminal-exited-with-code-x-on-windows

/label "needs more info" integrated-terminal
