### ISSUE TITLE
Failed to install any extension with recent VSCode Insider

### ISSUE THREAD

**Issue by mfmayer** [microsoft/vscode#98726]
- VSCode Version:
Version: 1.46.0-insider
Commit: 1d268b701376470bc638100fbe17d283404ac559
Date: 2020-05-28T08:50:53.373Z
Electron: 7.3.0
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763
- OS Version: Windows 10

Steps to Reproduce:

1. Fresh install of VSCode Insider 1.46.0 (also tried the zip package)
2. Try to install any extension (tried multiple popular extensions with same result)
3. Error message appears: 
![image](https://user-images.githubusercontent.com/8875306/83142627-0cc4ad80-a0f1-11ea-8b4a-687ae0e3a873.png)
4. Console in developer tools shows this:
![image](https://user-images.githubusercontent.com/8875306/83142706-27972200-a0f1-11ea-9a78-856a4edbfde9.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
Same here.

/cc @sandy081 @mjbvz as authors as https://github.com/microsoft/vscode/commit/f676774cb7d6060dcbb540ca0480f60e4d07fbda and https://github.com/microsoft/vscode/commit/40559425c7c7219a25f148a41d678c488629a662

Version: 1.46.0-insider (user setup)
Commit: 1d268b701376470bc638100fbe17d283404ac559
Date: 2020-05-28T08:50:53.373Z
OS: Windows_NT x64 10.0.18363

**Comment by sandy081** [comment]
Fixed it and triggered new insiders release.

**Comment by sandy081** [comment]
Can you please verify if you can able to install extensions on latest insiders?

**Comment by mfmayer** [comment]
Yes, thanks! Installing extensions is working again.

**Comment by IllusionMH** [comment]
@sandy081 I can install extensions (after release with fix as well as latest Insiders build).

Quick note about problem that I saw couple of times, but can't get enough investigation for separate issue ATM.

However it looks like extension uninstall is broken:
1. install extension and Reload window
2. Try to remove extension: I can see progress indicator above the list, but list is not updated (also I think search also broken after that)
3. Reload window - extension I tried to uninstall still in the list, but I see "Extensions have been modified on disk. Please reload the window." notification.
4. Click on Reload window in notification  - extension is gone

Can you repro this problem or need more info needed in separate issue?

Doesn't happen if I close VS Code after extension installation.

**Comment by sandy081** [comment]
Seems separate issue and unrelated to this. Please file a separate issue with step to repro.
