### ISSUE TITLE
presence of node_modules folder rises cpu usage to over 100 %

### ISSUE THREAD

**Issue by humahn** [microsoft/vscode#98725]
hello,

when I edit a single line of javascript/react file in a my react project, cpu spikes to over 100 percent. 

i did the following steps:
 - problem persists with all installed plugging disabled and even in insider.
- when i disable @builtin typescript and js language features plugin, cpu usage comes down dramatically.
- deleting typescript cache folder from user/Library/Caches/ doesnt help.
- after installing typescript@next cpu usage felt by around 20% but still around 110% when writing a single line of react component.
- when i delete the node_modules folder the usage comes down to 30-40%
- I excluded node_modules in search setting and created jsconfig.json with this content: 
```
{
    "compilerOptions": {
      "module": "commonjs",
      "target": "es6"
    },
    "exclude": ["node_modules", "**/node_modules/*"]
  }   
```
but it didnt help, and still it seems typescript and js features plugin looks in the node_modules folders.

- here is code-insiders --status during one of the peaks:
```
Version:          Code - Insiders 1.46.0-insider (876f2e70f9a2e1988887f8ca82294418afac15a2, 2020-05-27T05:41:02.088Z)
OS Version:       Darwin x64 18.7.0
CPUs:             Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)
Memory (System):  8.00GB (0.03GB free)
Load (avg):       1, 1, 2
VM:               0%
Screen Reader:    no
Process Argv:     
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    2	    90	  1092	code-insiders main
    0	    49	  1093	   gpu-process
    0	    25	  1095	   utility
    3	    90	  1105	   shared-process
    0	     0	  1242	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    1	   311	  1165	   window (CreateTrack.js — gp)
    0	    90	  1166	     extensionHost
    0	    74	  1168	       electron_node tsserver.js 
    0	   459	  1169	       electron_node tsserver.js 
    0	    74	  1193	         electron_node typingsInstaller.js typesMap.js 
    0	    41	  1196	       /private/var/folders/37/zl4562zn3sl7vszlnzqk2q_00000gn/T/AppTranslocation/1A89925B-51CA-4793-AE75-F271DCF97B72/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer) /private/var/folders/37/zl4562zn3sl7vszlnzqk2q_00000gn/T/AppTranslocation/1A89925B-51CA-4793-AE75-F271DCF97B72/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=1166
    0	    49	  1167	     watcherService

Workspace Stats: 
|  Window (CreateTrack.js — gp)
|    Folder (gp): 10549 files
|      File types: py(2154) pyc(2145) mo(1142) po(1142) html(123) js(111)
|                  txt(41) svg(26) css(14) py-tpl(13)
|      Conf files: jsconfig.json(2) package.json(1)
```
is there any way to make vscode ignore completely the node_modules folder? 
and besides, is this memory usage by vscode without any plugin normal (800-900 mb)?

**Comment by mjbvz** [comment]
The perf information you shared does not show high cpu usage. Where are you seeing it reported?

**Comment by humahn** [comment]
here is another status just after 120% of cpu usage, i tried to run the command in the mac terminal as quickly as possible:
```
[1625:0528/214018.748856:WARNING:dns_config_service_posix.cc(184)] dns_config has unhandled options!
[1630:0528/214019.164820:WARNING:dns_config_service_posix.cc(184)] dns_config has unhandled options!
Version:          Code - Insiders 1.46.0-insider (876f2e70f9a2e1988887f8ca82294418afac15a2, 2020-05-27T05:41:02.088Z)
OS Version:       Darwin x64 18.7.0
CPUs:             Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)
Memory (System):  8.00GB (0.24GB free)
Load (avg):       2, 2, 2
VM:               0%
Screen Reader:    no
Process Argv:     
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    1	    82	  1519	code-insiders main
    3	    49	  1521	   gpu-process
    0	    25	  1523	   utility
    3	   238	  1524	   window (CreateTrack.js — gp)
    0	   106	  1531	     extensionHost
    0	    66	  1537	       electron_node tsserver.js 
    2	   492	  1538	       electron_node tsserver.js 
    0	    66	  1555	         electron_node typingsInstaller.js typesMap.js 
    0	    41	  1540	       /private/var/folders/37/zl4562zn3sl7vszlnzqk2q_00000gn/T/AppTranslocation/386A24E6-3777-4B26-AA1A-22BF62BAA0F6/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer) /private/var/folders/37/zl4562zn3sl7vszlnzqk2q_00000gn/T/AppTranslocation/386A24E6-3777-4B26-AA1A-22BF62BAA0F6/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=1531
    0	    41	  1533	     watcherService
    3	    74	  1534	   shared-process
    0	     0	  1629	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Stats: 
|  Window (CreateTrack.js — gp)
|    Folder (gp): 10549 files
|      File types: py(2154) pyc(2145) mo(1142) po(1142) html(123) js(111)
|                  txt(41) svg(26) css(14) py-tpl(13)
|      Conf files: jsconfig.json(2) package.json(1)
```

here is a 90% spike just after writing the code in the red rectangle:
<img width="1440" alt="Screen Shot 2020-05-28 at 9 43 34 PM" src="https://user-images.githubusercontent.com/64265676/83172814-64810a00-a12d-11ea-9cab-f73ba4cf387c.png">

**Comment by mjbvz** [comment]
I don't know why the perf information is not showing any high cpu usage. 

Can you instead try using the command line to determine which specific process has the high cpu usage. Try a command such as:

```
ps -eo pid,ppid,%mem,%cpu,args -r | head
```

And share the details of the process that high the issue. An example process would look something like:

```
32619 32609  0.5   5.4 /Users/matb/projects/vscode/.build/electron/Code - OSS.app/Contents/Frameworks/Code - OSS Helper (GPU).app/Contents/MacOS/Code - OSS Helper (GPU) --type=gpu-process --field-trial-handle=1718379636,8236489936534508639,8373353186076804903,131072 --disable-features=LayoutNG,SpareRendererForSitePerProcess --disable-color-correct-rendering --no-sandbox ...
```

**Comment by humahn** [comment]
i think i wasn't quick enough to run the status command so i missed the peak.
i tried this command :` ps -eo pid,ppid,%mem,%cpu,args -r | head`  and this is the first result with 110 percent:

`1699  1696  5.5 110.8 /private/var/folders/37/zl4562zn3sl7vszlnzqk2q_00000gn/T/AppTranslocation/386A24E6-3777-4B26-AA1A-22BF62BAA0F6/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer) --max-old-space-size=3072 /private/var/folders/37/zl4562zn3sl7vszlnzqk2q_00000gn/T/AppTranslocation/386A24E6-3777-4B26-AA1A-22BF62BAA0F6/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/37/zl4562zn3sl7vszlnzqk2q_00000gn/T/vscode-typescript501/713c5a1e839802dc93e9/tscancellation-14239bd5eacf6e4cf48a.tmp* --globalPlugins typescript-vscode-sh-plugin --pluginProbeLocations /private/var/folders/37/zl4562zn3sl7vszlnzqk2q_00000gn/T/AppTranslocation/386A24E6-3777-4B26-AA1A-22BF62BAA0F6/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation`

 i reproduced this with just writing a single line of code.

**Comment by mjbvz** [comment]
Thanks. Can you share the project that causes this?

**Comment by humahn** [comment]
sure, but can i send it to you privately?
(because i dont own the project and i'm not aware if i'm allowed to share it publicly)

**Comment by mjbvz** [comment]
Sure, you can either invite me to a private GitHub repo or email me a copy of project: matb at microsoft

We only use shared projects to diagnose what is going wrong and do not store them

**Comment by humahn** [comment]
Thank you,
I emailed the project main folder and a screen video recorded while reproducing the issue.

**Comment by mjbvz** [comment]
@humahn Thanks. In that project, I see the cpu usage spike for just a moment and then drop back down to zero almost right away. Doe that match what you are seeing?


@aeschli It looks like the most expensive request during this is a call to `encodedSemanticClassifications-full`:

```
Info 310  [16:20:50.559] request:
    {"seq":30,"type":"request","command":"encodedSemanticClassifications-full","arguments":{"file":"/Users/matb/Downloads/project-main/react-tracks-client /src/components/Track/CreateTrack.js","start":1241,"length":3732}}
Info 311  [16:20:50.559] Starting updateGraphWorker: Project: /Users/matb/Downloads/project-main/react-tracks-client /jsconfig.json
Info 312  [16:20:50.603] Finishing updateGraphWorker: Project: /Users/matb/Downloads/project-main/react-tracks-client /jsconfig.json Version: 8 structureChanged: false Elapsed: 44ms
Info 313  [16:20:50.603] Different program with same set of files:: oldProgram.structureIsReused:: 2
Perf 314  [16:20:50.702] 30::encodedSemanticClassifications-full: elapsed time (in milliseconds) 143.3387
```

**Comment by humahn** [comment]
in fact there are two 100% peaks:
- one happens immediately after opening one of those .js files. which drops almost immediately afterwards.
- another one which is the main problem happens while writing in those .js files (just as in the video). it drops only if you stop writing. if you keep writing it remains >70-80 %. in fact after 10-15 lines of writing my laptop gets really warm.

Turning editor.semanticHighlighting.enabled to false didn't lower initial peak, nor the peak which caused by writing.

**Comment by mjbvz** [comment]
@humahn Are you still seeing this with the most recent VS Code insiders build?
