### ISSUE TITLE
Proxy regression between 1.33.x and 1.45.1

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#98721]
Today I updated from VSCode 1.33.x to 1.45.1 since there's an extension I needed to update, and I ran into the same issue. Somewhere between 1.33.x and 1.45.1 (also persists in the current Insiders build) something broke with regards to use of proxies. I'm using a corporate proxy which is configured by GPO as "system" proxy with NTLM authentication. It works fine for everything which is able to use these settings (i.e. browsers, including Chrome). This used to include VSCode. I never had to use any of the environment variables and other kludges, so I see this as a regression.

_Originally posted by @FOTempel in https://github.com/microsoft/vscode/issues/98429#issuecomment-635271656_

**Comment by chrmarti** [comment]
@FOTempel Could you start VS Code with `--log-net-log=netlog.json`, try some of the failing actions and then upload the `netlog.json` here?

**Comment by chrmarti** [comment]
Also: Which actions do not work anymore?

**Comment by FOTempel** [comment]
> Also: Which actions do not work anymore?

Well, the only one I use is installing extensions, but I assume the update check will also fail. But I'll get you that log. If I get some time I'll also try to trace back in which release this problem started, I'm installing 1.44.2 now...

**Comment by FOTempel** [comment]
> > Also: Which actions do not work anymore?
> 
> Well, the only one I use is installing extensions, but I assume the update check will also fail. But I'll get you that log. If I get some time I'll also try to trace back in which release this problem started, I'm installing 1.44.2 now...

Lucky, it works in 1.44.2 so that narrows it down considerably.

**Comment by FOTempel** [comment]
I created two netlog files, one for 1.44.2 where "it" works, and one for 1.45.1 where it doesn't anymore. I installed VSCode, went to extensions and typed "Puppet" as search string. 1.44.2 finds all Extensions with that keyword, 1.45.1 doesn't and tells me "We cannot connect to the Extensions Marketplace at this time, please try again later." If I go to Help->Check for Updates... I get greeted with "net::ERR_PROXY_CONNECTION_FAILED" with "Source: Update Service".

Downgrading to 1.44.2 makes everything work as expected again.

[netlog.zip](https://github.com/microsoft/vscode/files/4695930/netlog.zip)

**Comment by chrmarti** [comment]
@FOTempel The 1.45 log shows a second proxy configuration overwriting the one that works with 1.44. The only place we do overwrite what Electron/Chromium gets as proxy configuration from the OS is where we change Chromium's proxy configuration if HTTP_PROXY or HTTPS_PROXY is set. Could you double-check none of these environment variables are set?

**Comment by chrmarti** [comment]
Also check the `"http.proxy"` setting in VS Code is empty. Any value there would overwrite the configuration read from the OS.

**Comment by FOTempel** [comment]
Neither the HTTP*_PROXY variables nor http.proxy are set. If they were, I'd have made sure they were set correctlty. I never needed them for VSCode and apparently up until 1.44.2, VSCode was fine with it.

**Comment by chrmarti** [comment]
@FOTempel The logs both show a first configuration that seems to work (at least with 1.44):
![image](https://user-images.githubusercontent.com/9205389/83494705-f5057480-a4b6-11ea-8a36-00b8ee98310c.png)

In 1.44 the log shows that same configuration a second time. With 1.45 there is a different configuration overwriting the first one:
![image](https://user-images.githubusercontent.com/9205389/83494828-1ebe9b80-a4b7-11ea-8835-d2a0877dca94.png)

I guess that might just not be a working configuration, but I don't know where that might come from. Do you have any idea where that might be configured?

/cc @deepak1556

**Comment by FOTempel** [comment]
> @FOTempel The logs both show a first configuration that seems to work (at least with 1.44):
> ![image](https://user-images.githubusercontent.com/9205389/83494705-f5057480-a4b6-11ea-8a36-00b8ee98310c.png)
> 
> In 1.44 the log shows that same configuration a second time. With 1.45 there is a different configuration overwriting the first one:
> ![image](https://user-images.githubusercontent.com/9205389/83494828-1ebe9b80-a4b7-11ea-8835-d2a0877dca94.png)
> 
> I guess that might just not be a working configuration, but I don't know where that might come from. Do you have any idea where that might be configured?
> 
> /cc @deepak1556

That's definitly not a working configuration, but looks very environment specific. On second look, I do notice those things hidden in my environment. Why? No idea, really, but I'll get rid of them for sure.

So can we draw the preliminary conclusion here that 1.45.x works as designed with overriding general settings with specific ones and 1.44.x doesn't?

**Comment by chrmarti** [comment]
Yes, picking up the environment variables and the VS Code setting to override the OS configuration is a change we did in 1.45.

Sounds like this resolves the issue?

**Comment by FOTempel** [comment]
> Yes, picking up the environment variables and the VS Code setting to override the OS configuration is a change we did in 1.45.
> 
> Sounds like this resolves the issue?

Assumingly, but I'll test to make sure. Just need to finish up the thing I'm editing first :P

**Comment by FOTempel** [comment]
> > Yes, picking up the environment variables and the VS Code setting to override the OS configuration is a change we did in 1.45.
> > Sounds like this resolves the issue?
> 
> Assumingly, but I'll test to make sure. Just need to finish up the thing I'm editing first :P

Cleaned up my environment and it seems to work as designed now! Kinda stupid of me, but hey. Thanks!

**Comment by chrmarti** [comment]
Closing the issue, thanks!

**Comment by deepak1556** [comment]
@chrmarti can we close the issue ?

**Comment by chrmarti** [comment]
Yes, must have missed the button. 🤷
