### ISSUE TITLE
Git in vscode does not detect git status correctly if the files are on another OS partition

### ISSUE THREAD

**Issue by elieobeid7** [microsoft/vscode#98735]
- Have a dual booted PC, in my case it's windows 10 and Manjaro, previously it was windows 10 and Ubuntu 16.04, I had the same issue

- Have a git project placed on windows 10 partition, C drive or whatever

- Boot into Linux, mount that partition and open the project in VSCode

- Do a `git pull` from the terminal, it will say `everything is up to date`

- Look at the git icon in vscode menu, it will show that you have files to commit.

I don't know if the same issue is on mac, I don't have a mac to test. I use vscode on both Linux and windows. Maybe the issue is with `.vscode` folder? Can't tell for sure, maybe vscode is trying to read configurations off windows from that folder and it's not the same, or maybe it's something else.

**Comment by joaomoreno** [comment]
> Look at the git icon in vscode menu, it will show that you have files to commit.

What files? What if you run `git status` from the terminal, what does that output?

**Comment by elieobeid7** [comment]
You're right, git status reports modified files. I fixed it by following this question

https://github.com/microsoft/WSL/issues/184


```
git config --global core.filemode false
git config --global core.autocrlf true
```

I believe that the second line is the one that fixed it.
