### ISSUE TITLE
Quickfix and autoimport ignore real filenames with dot

### ISSUE THREAD

**Issue by glaucopater** [microsoft/vscode#98734]
- VSCode Version: 1.44.2
- OS Version: Darwin x64 18.7.0

Steps to Reproduce:

1. Use the Quick Fix -> "ïmport type from folder/types" (filename is types.d.ts)
2. Imported line will be "import type from folder/types"

Does this issue occur when all extensions are disabled? Yes

**Comment by mjbvz** [comment]
You generally do not want to use the file extension in imports

Please share a complete example of your project and what is going wrong

**Comment by glaucopater** [comment]
Exactly @mjbvz ! The problem is that VS Code is not only removing the file extension, but everithing after the first dot:
i.e types.d.ts (standard filename format for TypeScript) is imported as "types" and not the complete file name which is "types.d"

**Comment by mjbvz** [comment]
`.d.ts` is the file extension for typescript typings: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

During import, the entire extension is removed in this case
