### ISSUE TITLE
moveEditorToRightGroup should not attempt to move the editor when it's the only editor in the group

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9873]
- VSCode Version: Code - Insiders 1.4.0-insider (825a1e71a436007d88796cb1cf0bad85ad534e53, 2016-07-27T07:02:25.317Z)
- OS Version: Linux x64 4.4.0-31-generic, Ubuntu 16.04

Steps to Reproduce:

1. Open a single tab in a single editor group
2. Trigger `workbench.action.moveEditorToRightGroup`, notice the editor flashes but seemingly does nothing.

**Comment by bpasero** [comment]
Verifier: it should still be possible to use the command to move an editor to the left or right when it makes sense. The only case where we do not move is if the group of the active editor only has this editor within and there is no group to the right already.
