### ISSUE TITLE
Latest update caused extensions to fail installation 

### ISSUE THREAD

**Issue by JaredMRomano** [microsoft/vscode#98737]
Issue Type: <b>Bug</b>

Trying to install new extenstions. (Atlassian and GitLens) Gives Notification saying "failed to install [insert program name here]" The notification window contains a Download Manually button option.  The manual download button starts downloading a VISX, but when installing, it fails saying "One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code." There are no failure reasons in the output window, or any way to get failure details.

VS Code version: Code - Insiders 1.46.0-insider (1d268b701376470bc638100fbe17d283404ac559, 2020-05-28T08:50:53.373Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (17.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|4.7.0
vscode-pull-request-github|Git|0.16.1
vscode-peacock|joh|3.7.2
chat|kar|0.33.0
csharp|ms-|1.21.18
python|ms-|2020.6.81425-dev
remote-wsl|ms-|0.44.2
cpptools|ms-|0.28.1
powershell|ms-|2020.4.0
vsliveshare|ms-|1.0.2236
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.3.4
vscodeintellicode|Vis|1.2.7
vscode-arduino|vsc|0.3.0
vscode-icons|vsc|10.1.1
markdown-all-in-one|yzh|3.0.0
json|Zai|1.0.4

(1 theme extensions excluded)

</details>

**Comment by misolori** [comment]
Also seeing this on today's Insiders. Console logs:
```
extensionsActions.ts:263 Error: Cannot read property ‘isDefault’ of undefined
   (anonymous) @ extensionsActions.ts:263
```

**Comment by IllusionMH** [comment]
Same as #98726, but that don't have info about problems with manual install.

**Comment by sandy081** [comment]
/duplicate 

#98726
