### ISSUE TITLE
Run Icon not displaying in latest insiders build

### ISSUE THREAD

**Issue by kands-code** [microsoft/vscode#98739]
Issue Type: <b>Bug</b>

After the latest update, the "Run" icon in the activity bar will not display properly.
![image](https://user-images.githubusercontent.com/59006329/83155709-191e2a00-a134-11ea-9a5c-9c5a2bc4ee50.png)

VS Code version: Code - Insiders 1.46.0-insider (1d268b701376470bc638100fbe17d283404ac559, 2020-05-28T08:50:53.373Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) N4100 CPU @ 1.10GHz (4 x 1094)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.83GB (3.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.35.2
vscode-eslint|dba|2.1.5
code-runner|for|0.10.0
vscode-pull-request-github|Git|0.16.1
beautify|Hoo|1.5.0
vscode-language-pack-zh-hans|MS-|1.46.0
python|ms-|2020.5.80290
remote-wsl|ms-|0.44.2
cmake-tools|ms-|1.4.0
cpptools|ms-|0.28.1
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.7
vscode-icons|vsc|10.1.1
markdown-all-in-one|yzh|3.0.0
material-theme|zhu|3.7.1

</details>

**Comment by akaroml** [comment]
Same here. The icon of the Debug tab is missing in the latest insider build.

![image](https://user-images.githubusercontent.com/16755094/83157375-1a505680-a136-11ea-9ae0-0b17593c2096.png)

Version: 1.46.0-insider
Commit: 1d268b701376470bc638100fbe17d283404ac559
Date: 2020-05-28T08:45:32.560Z
Electron: 7.3.0
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Comment by lramos15** [comment]
https://github.com/microsoft/vscode/issues/98704

Should be fixed in the next insiders
