### ISSUE TITLE
Debugger dependOn another debugger?

### ISSUE THREAD

**Issue by Thaina** [microsoft/vscode#98742]
In blazor project it required that we need to start 2 debuggers in a row. I wish we could automate this process on vscode by specifying `dependOn` to a name of another debug configuration in the same `launch.json` file

And so it would check that another debugger was already run before launching selected debugger, if not it will try to start that root debugger first

Is it already possible? And if not is it possible to do in vscode?

**Comment by weinand** [comment]
@Thaina you can run multiple debuggers concurrently with "compound" launch configs. But you cannot express dependencies among them.

**Comment by Thaina** [comment]
@weinand Thank you very much. If I write compound config then is it sequential though?

**Comment by weinand** [comment]
@Thaina 
in theory: no, all debug configurations are launched in parallel.
In practice: yes, but you never know what order, so you cannot rely on it.

**Comment by Thaina** [comment]
@weinand Thank you for your clarifying. I think that might be the reason why Blazor launch config don't rely on that, because they specifically said in step to start one debugger before another

**Comment by Thaina** [comment]
@weinand Another approach I could this of is to use command `preLaunchTask` to start another debugger then `postDebugTask` to stop it. Is it possible?

**Comment by IllusionMH** [comment]
@Thaina  But how to detect when first application(debug) started and second debugger should start?

There is no "end" of first app start as with `preLaunchTask`, so current solution is preLauchTask that will use `sleep 5` or check if first app is reasy to accept connections on port etc.

**Comment by weinand** [comment]
IMO debuggers should not depend on each other. They depend only on the target: the debuggee. 
Why are you relying on a specific order?
If your setup has a client and a sever then they can startup in arbitrary order: client before server, server before client, etc. Both client and server will have to deal with hat. Adding debugging to the picture should not change anything: debugging the server requires that the server is running. Debugging the client requires that the client is running. 
If client debugging requires that server debugging is running, then something is strange...

**Comment by Thaina** [comment]
@weinand I don't actually know why too, it was requirement of blazor

https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1#visual-studio-code

**Comment by Thaina** [comment]
@IllusionMH isn't `postDebugTask` can signified an end to stop debugger?
