### ISSUE TITLE
ARM64 version on Windows - Extensions fail to install from store.

### ISSUE THREAD

**Issue by davide-rota** [microsoft/vscode#98743]
Steps to Reproduce:

1. Launch VS Code
2. Notice the Run Icon is missing
![image](https://user-images.githubusercontent.com/11763/83162792-87e68d80-a10a-11ea-9861-6127bef84ee9.png)
3. Try to install any extension (e.g. visualstudioexptteam.vscodeintellicode )
4.  Notice that extension fails to install
![image](https://user-images.githubusercontent.com/11763/83162810-8d43d800-a10a-11ea-87a7-f535ec371669.png)
5. Download vsix manually
6. Install vsix and notice that extension installs without problems.

VS Code version: Code - Insiders 1.46.0-insider (1d268b701376470bc638100fbe17d283404ac559, 2020-05-28T08:45:28.569Z)
OS version: Windows_NT arm64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Microsoft SQ1 @ 3.0 GHz (8 x 1670)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.54GB (1.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.51.0
remote-wsl|ms-|0.44.2
powershell|ms-|2020.4.0

</details>
 paste.

**Comment by IllusionMH** [comment]
I don't think it's ARM specific, most likely same problem in all insiders builds: #98726

**Comment by davide-rota** [comment]
It seems you're right! Did a search for issues related to the new ARM release but didn't think to include all versions, my bad. Closing the issue.

**Comment by IllusionMH** [comment]
> Fixed it and triggered new insiders release.

From https://github.com/microsoft/vscode/issues/98726#issuecomment-635486050

---

Off-topic: How do you find VS Code on SP X ? Is in possible to work on Windows side (for Node.js and other JS related stuff if you use it) or better to use WSL/SSH from the beginning?

**Comment by davide-rota** [comment]
> Off-topic: How do you find VS Code on SP X ? Is in possible to work on Windows side (for Node.js and other JS related stuff if you use it) or better to use WSL/SSH from the beginning?

It is sure possible to install nodejs, git and all other dependencies on Windows but I prefer WSL2 since all (nodejs, git, etc..) is ARM native under linux while most of the stuff runs emulated in windows (also, vscode WSL extension works great).
SPX biggest advantage is good battery life, very small and lightweight, no heat and dead silent (no fan). Also battery charges in 1 hour.

**Comment by IllusionMH** [comment]
Thanks for feedback!
