### ISSUE TITLE
TypeScript Intellisense not working for class properties

### ISSUE THREAD

**Issue by ties-s** [microsoft/vscode#98744]
- VSCode Version: 1.45.1
- OS Version: macOS 10.15.4 (Darwin x64 19.4.0)

Steps to Reproduce:

1. create a typescript class
2. try to assign existing variable to a class property: not autocomplete will show. Autocomplete works fine outside class definition or inside methods

Does this issue occur when all extensions are disabled?: Yes

Screenshots (Angular project):
<img width="938" alt="Screenshot 2020-05-28 om 17 46 20" src="https://user-images.githubusercontent.com/9462286/83163399-46a2ad80-a10b-11ea-8443-fbfd5bf1510b.png">
<img width="969" alt="Screenshot 2020-05-28 om 17 46 52" src="https://user-images.githubusercontent.com/9462286/83163416-4a363480-a10b-11ea-8e01-20cdf54bc9ea.png">

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by ties-s** [comment]
Very basic reproduction code: 
```typescript
// file.ts
const someValue = 'SOME VALUE';

// intellisense for someValue
const otherValue = someValue;

class TestClass {

  // no intellisense for someValue
  public prop = someValue;

}
```

**Comment by ties-s** [comment]
![Screenshot-2020-05-29-om-00 54 57](https://user-images.githubusercontent.com/9462286/83202338-aa4acc00-a147-11ea-8989-717c01c58768.gif)

**Comment by mjbvz** [comment]
Seems like this was already fixed in VS Code insiders. let me know if you see it with VS Code 1.46+

**Comment by ties-s** [comment]
1.46 fixes this bug
