### ISSUE TITLE
Calling activeTextEditor.edit twice will only work for the first call.

### ISSUE THREAD

**Issue by mimo84** [Microsoft/vscode#9874]
- VSCode Version: Version 1.3.1 (1.3.1) e6b4afa53e9c0f54edef1673de9001e9f0f547ae
- OS Version: OSX 10.11.6 (15G31)

I am trying to write an extension for VS Code where I need to insert text in two different places of the current document (module importing and injection).

What happens it is that if I edit the text as:

```
window.activeTextEditor.edit(editBuilder => {
    var indexA = new Position(0,0)
    var indexB = new Position(1,0)
    editBuilder.insert(indexA, 'Insert A')
    editBuilder.insert(indexB, 'Insert B')
})
```

it will work just fine, however, if I split it into two different calls:

```
window.activeTextEditor.edit(editBuilder => {           
   var indexA = new Position(0,0)
   editBuilder.insert(indexA, 'Insert A')
})

window.activeTextEditor.edit(editBuilder => {
    var indexB = new Position(1,0);
    editBuilder.insert(indexB, 'Insert B')
})
```

Only the first one will be in the document.

**Comment by siegebell** [comment]
@mimo84 `edit` is an asynchronous action &hyphen; you need to await its completion before issuing another edit.

```typescript
await editor.edit(...'Insert A'...);
await editor.edit(...'Insert B'...)
```
or
```typescript
editor.edit(...'Insert A'...).then(() => editor.edit(...'Insert B'...))
```

**Comment by mimo84** [comment]
Thanks, I realised this just after asking the question. I initially thought that an edit action would be run immediately, similar to what happens in Atom.

**Comment by siegebell** [comment]
@mimo84 it was a good question. The API is not documented nearly enough, especially w.r.t. the asynchronous behavior of edits and extension callbacks. Also, the behavior you describe is surprising; why does vscode discard, rather than buffer, additional edits that occur before the first edit is complete?
