### ISSUE TITLE
Jsconfig.json hint logic

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#9875]
The green lightbulb in the bottom of VS Code is very convenient for generating jsconfig.json. The problem is it doesn't show up all the time. In fact, when does it show up? 

Here is what I have done to try to make it give me the hint. 
1. Delete jsconfig.json
2. Reload Window
3. Restart VS Code

I can't seem to get it to come back. 

My feature request is that we change the logic so the hint shows up each time jsconfig.json should be there and it isn't (with an option to ignore the hint). 

Secondly, we should make it possible to invoke the action the hint suggests through the command palette.

**Comment by jrieken** [comment]
The logic goes like this

* a JS files becomes active (as in the active editor)
* we ask `tsserver` to which project that files belong
* iff that signals `none` we show the lightbulb

@waderyan please configure typescript for verbose logging (`"typescript.tsserver.trace": "verbose"`) and check the TypeScript output channel for messages ala `Sending request: projectInfo `. The response will tell you what project TS thinks your file belongs to - note that this must not be scoped the workspace location

**Comment by waderyan** [comment]
Thanks @jrieken this makes more sense now. I want to think about the user's perspective more (run a few tests). Maybe i'm the only one not understanding, but if not we might make it clearer from the user's perspective. 

Would it be possible to have a command available in the command palette to auto generate a jsconfig.json file? Essentially a way to invoke the lightbulb without the lightbulb showing up. 

Also, what do we call the lightbulb? Is it a project hint? Project code action?

**Comment by waderyan** [comment]
Closed as no longer relevant (tracking this work has moved to another area).

**Comment by wonbyte** [comment]
I too don't usually see the lightbulb within vscode on:

vscode: Version 1.7.2 (1.7.2)
macOS Sierra: 10.12.1

Here is the output when I create a new folder with a single .js file.  Any idea why this would not be giving me the hint to generate the jsconfig.json?

[Info  - 11:42:08 PM] Using tsserver from location: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js
[Trace - 11:46:17 PM] Sending request: quickinfo (102). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/gps/src/github/temp/foo.js",
    "line": 1,
    "offset": 13
}
[Trace - 11:46:17 PM] Response received: quickinfo (102). Request took 12 ms. Success: true 
Result: {
    "kind": "function",
    "kindModifiers": "",
    "start": {
        "line": 1,
        "offset": 10
    },
    "end": {
        "line": 1,
        "offset": 13
    },
    "displayString": "function boo(): number",
    "documentation": ""
}
[Trace - 11:46:18 PM] Sending request: projectInfo (103). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/gps/src/github/temp/foo.js",
    "needFileNameList": true
}
[Trace - 11:46:18 PM] Response received: projectInfo (103). Request took 0 ms. Success: true 
Result: {
    "configFileName": "/dev/null/inferredProject1*",
    "languageServiceDisabled": false,
    "fileNames": [
        "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/lib.es6.d.ts",
        "/Users/gps/src/github/temp/foo.js"
    ]
}
[Trace - 11:46:18 PM] Sending request: quickinfo (104). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/gps/src/github/temp/foo.js",
    "line": 2,
    "offset": 13
}
[Trace - 11:46:18 PM] Response received: quickinfo (104). Request took 2 ms. Success: false . Message: No content available.
[Trace - 11:46:18 PM] Sending request: quickinfo (105). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/gps/src/github/temp/foo.js",
    "line": 2,
    "offset": 14
}
[Trace - 11:46:18 PM] Response received: quickinfo (105). Request took 1 ms. Success: false . Message: No content available.
[Trace - 11:48:07 PM] Sending request: projectInfo (106). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/gps/src/github/temp/foo.js",
    "needFileNameList": true
}
[Trace - 11:48:07 PM] Response received: projectInfo (106). Request took 1 ms. Success: true 
Result: {
    "configFileName": "/dev/null/inferredProject1*",
    "languageServiceDisabled": false,
    "fileNames": [
        "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/lib.es6.d.ts",
        "/Users/gps/src/github/temp/foo.js"
    ]
}
[Trace - 11:48:44 PM] Sending request: projectInfo (107). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/gps/src/github/temp/foo.js",
    "needFileNameList": true
}
[Trace - 11:48:44 PM] Response received: projectInfo (107). Request took 1 ms. Success: true 
Result: {
    "configFileName": "/dev/null/inferredProject1*",
    "languageServiceDisabled": false,
    "fileNames": [
        "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/lib.es6.d.ts",
        "/Users/gps/src/github/temp/foo.js"
    ]
}
[Trace - 11:48:55 PM] Sending request: projectInfo (108). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/gps/src/github/temp/foo.js",
    "needFileNameList": true
}
[Trace - 11:48:55 PM] Response received: projectInfo (108). Request took 0 ms. Success: true 
Result: {
    "configFileName": "/dev/null/inferredProject1*",
    "languageServiceDisabled": false,
    "fileNames": [
        "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/lib.es6.d.ts",
        "/Users/gps/src/github/temp/foo.js"
    ]
}
