### ISSUE TITLE
Cannot install extensions in VS Code - Insiders

### ISSUE THREAD

**Issue by JordanMarr** [microsoft/vscode#98759]
- VSCode Version:  v1.46.0-insider
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Installed Visual Studio Code - Insiders
2. Rebooted machine
3. Trying to install _any_ extension produces error: "Failed to install '{extension name}'."

NOTE: I can install extensions on latest stable VS Code, but not in Insiders.

Does this issue occur when all extensions are disabled?: Yes/No
n/a

**Comment by cassshh** [comment]
Same here. It's fixed with #98726 
It's currently releasing a new version.
