### ISSUE TITLE
JetBrains Mono powerline characters not rendering correctly.

### ISSUE THREAD

**Issue by TheJSHuA** [microsoft/vscode#98772]
- VSCode Version: 1.46.0-insider
- OS Version: Manjaro KDE 20.0.1

Steps to Reproduce:

1. Set `JetBrains Mono` as the terminal font.
2. Use powerline characters somehow in the terminal.

Does this issue occur when all extensions are disabled?: Yes

In Konsole, the powerline characters render perfectly fine with JetBrains Mono, however, in visual studio code they render as squares. I have tested other powerline fonts like Fira Code and they render powerline characters perfectly fine in Code, so I don't know why JetBrains Mono isn't working correctly. Attached is an image showing the problem. Top window is Konsole, bottom window is the Visual Studio Code terminal. 

![image](https://user-images.githubusercontent.com/22226164/83207461-dd299b80-a118-11ea-9bf8-22ba268517c4.png)

**Comment by Tyriar** [comment]
The font looks different, you probably haven't set it correctly in the fontFamily setting.
