### ISSUE TITLE
web-playground error about activation events

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#98779]
Issue Type: <b>Bug</b>

**Repro**
1. On OSS build
1. Open  a workspace

**Bug**
See this error:

<img width="826" alt="Screen Shot 2020-05-28 at 8 04 05 PM" src="https://user-images.githubusercontent.com/12821956/83216620-8aeb7900-a11e-11ea-95a1-e3f960cae591.png">

VS Code version: Code - Insiders 1.46.0-insider (9e439b13d5784538333bee044ca1d1a992bc1c90, 2020-05-28T18:46:41.056Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.15GB free)|
|Process Argv|-psn_0_16535492 --max-memory=4096|
|Screen Reader|no|
|VM|14%|
</details>

**Comment by mjbvz** [comment]
Seems to have been triggered by d1a3e6ede65a3d0559b5146b6d7fdaf5a0ad4ac3

**Comment by aeschli** [comment]
I pushed a fix in the meantime https://github.com/microsoft/vscode/commit/c1575cfb9ac273724bf12f9ba475db155d56c7a9
