### ISSUE TITLE
Collapse all button not working in C++ debugging

### ISSUE THREAD

**Issue by gurrrung** [microsoft/vscode#98785]
- VSCode Version: 1.44.1
- OS Version: Ubuntu 18

Steps to Reproduce:

1. Write a program in C++.
2. Debug it and try collapse all button.

Does this issue occur when all extensions are disabled?: Yes/No

![Screenshot from 2020-05-29 10-53-46](https://user-images.githubusercontent.com/30543444/83224419-fd9a3a00-a19a-11ea-9fb5-71949e4fa46a.png)

**Comment by isidorn** [comment]
Thanks for filling this issue. I can not reproduce this. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by gurrrung** [comment]
This 

> Can you reproduce using Visual Studio Code Insiders [code.visualstudio.com/insiders](https://code.visualstudio.com/insiders/)

No, I couldn't reproduce it here either.

I will get back with more info about the issue and the extensions I use.

**Comment by isidorn** [comment]
If you can not reproduce with vscode insdiers taht means it is fixed. Thus closing
