### ISSUE TITLE
Code insiders: update does not open code for me anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98787]
A couple of times in the past days I have seen my insiders not restarting after clicking to apply the update. Maybe related to our signing changes?

**Comment by joaomoreno** [comment]
I'll leave this for @deepak1556 to investigate. Let me know if you need my help in someway.

**Comment by deepak1556** [comment]
I haven't been able to repro it yet, will keep an eye. This happened once with chrome on my machine, I feel this is an issue with the OS.

**Comment by bpasero** [comment]
I have not seen this ever since.

**Comment by deepak1556** [comment]
Thanks for the update! Lets reopen if the issue appears again, closing for now.
