### ISSUE TITLE
Incorrectly marking a declaration as unused

### ISSUE THREAD

**Issue by andokai** [microsoft/vscode#98782]
Apologies if this is the wrong repo for this.

- VSCode Version: 1.45.1
- OS Version: Windows 10 & macOS

Steps to Reproduce:

The issue can be observed on CodeSandbox which I guess uses the same underlying code.
https://codesandbox.io/s/lucid-http-qscl0?file=/src/App.js

`CancelToken` is being marked as an unused declaration when it clearly isn't and applying the quick fix breaks the code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by andokai** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Yes it does

**Comment by mjbvz** [comment]
This is a bug with the typings that axios is shipping


If you enable type checking in the JS file, you'll see the error on `new CancellationToken`:

```
'CancelToken' only refers to a type, but is being used as a value here.ts(2693)
```

If your code is correct, please file a bug against axios to have them fix their typings

**Comment by andokai** [comment]
No worries, thanks for investigating!
