### ISSUE TITLE
Slow Compiling/Building for Typescript 

### ISSUE THREAD

**Issue by Madaditya** [microsoft/vscode#98789]
Issue Type: <b>Performance Issue</b>

The last update has made compiling and debugging on VS code for typescript very slow

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|10.2.1
vscode-mysql|for|0.4.0
gc-excelviewer|Gra|2.1.34
rest-client|hum|0.23.2
json2csv|kha|0.0.1
python|ms-|2020.5.80290
azure-account|ms-|0.8.11
debugger-for-chrome|msj|4.12.8
sqltools|mtx|0.22.2
material-icon-theme|PKi|4.1.0
funclist|qrt|7.6.3
vscode-data-preview|Ran|2.0.0

</details>

**Comment by mjbvz** [comment]
Please share steps to reproduce and describe what exactly "slow" means
