### ISSUE TITLE
Warning Turn Off

### ISSUE THREAD

**Issue by THEDON10** [microsoft/vscode#98786]
Issue Type: <b>Feature Request</b>

Can you please put a "Turn Off", or "Suppress Warnings" feature on the problem and warning feature?

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

**Comment by egamma** [comment]
/needsMoreInfo can you please describe your feature request in more detail.
