### ISSUE TITLE
Loading freeze Mac when opening 2nd VS Code instance from Launchpad

### ISSUE THREAD

**Issue by cwali09** [microsoft/vscode#98781]
Issue Type: <b>Bug</b>

I have a VS Code app that was already in my LaunchBar and Task Bar. For testing purposes I tried to take the VS Code app that was in my downloads folder and drag it into the LaunchBar and then launch another instance of VS Code from there to see what happens. The second instance initially opened, then proceeded to show me a a grey colored screen with nothing else on it with the colored loading spinning icon and my Mac Pro started to heat up instantly. After 60 seconds of waiting I launched Activity Monitor and saw that Electron was crashing and VS Code was not responding with a high percentage of CPU usage

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 1|
|Memory (System)|16.00GB (6.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by deepak1556** [comment]
Do you see the crash with latest stable ? If so, can you provide the crash dumps following https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports
