### ISSUE TITLE
ctrl D

### ISSUE THREAD

**Issue by Moddoo** [microsoft/vscode#98798]
Issue Type: <b>Bug</b>

ctrl D not working

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx   (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.95GB (1.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
es7-react-js-snippets|dsz|2.7.1
prettier-vscode|esb|4.7.0
vscode-auto-open-markdown-preview|hnw|0.0.4
mssql|ms-|1.9.0
debugger-for-chrome|msj|4.12.8
vscode-extension-auto-import|Nuc|1.4.3
material-icon-theme|PKi|4.1.0
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0

(5 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Does the problem occur if you reload with all extensions disabled, using that command from Command Palette?

If yes, please give clear and simple steps on how to reproduce it.

**Comment by rdsedmundo** [comment]
Select all occurrences from all matches is not working as well (it's bliping, sometimes it works). Started on this latest month release.

**Comment by egamma** [comment]
@rdsedmundo pls open as separate issue with detailed steps.
