### ISSUE TITLE
VS Code is causing BSOD (REFERENCE_BY_POINTER) in combination with encryption software (ZoneCentral)

### ISSUE THREAD

**Issue by astaruch** [microsoft/vscode#98790]
Hi, 

I've observed that VS Code with encryption software (which is mandatory in our company on our devices) ZoneCentral is causing BSOD (REFERENCE_BY_POINTER). When the VS Code is opening a terminal, ZoneCentral is requesting to enter a password since the application is accessing path (default for my user, may differ for others) C:\Users\<user>\AppData\LocalTemp, which was probably in the encrypted area and need to be decrypted.

This is usually OK, but when there is some other process which is using AppData\LocalTemp, there is often popup window from the ZoneCentral to enter a password which leads to BSOD. The other process may be Spotify (playing songs which were never played before thus needs to be newly cached), opening a new terminal inside VS Code (also applies for opening WSL), or just executing a build (jom/cmake/nmake is creating temporary files somewhere). 

I need to say that this is sometimes easy to reproduce (several times per day) and sometimes I get this only 1-2 per month. Needless to say, it's really ugly problem but hard to debug/reproduce, so I'm not expecting that this can be solved, but it may helps to somebody realizing that there is that issue and takes some actions (I've stopped using VS Code when we have deadline, so I don't have to face with BSOD and stoping development for some time).

 
- VSCode Version: 1.51.1 (but this is regularly happening since January)
- OS Version: Windows 10 Enterprise 1909 18363.778

Steps to Reproduce:

1. Have installed ZoneCentral
2. Open VS Code
3. Open new terminal
4. Have on background some application which access AppData\LocalTemp (Spotify)
5. Execute build for some application which will create temporary files in AppData\LocalTemp
6. ZoneCentral pop-ups with request to enter a password to decrypt that path
7. BSOD (REFERENCE_BY_POINTER)

Does this issue occur when all extensions are disabled?: Yes

More info:
The BSOD report was automatically sent to the MS Servers, I can provide more information to pair it with this ticket if needed.

In the event viewer there were these (maybe relevant?) information:
|Level|Date and Time|Source|Event ID|Task Category|Detail|
|---|----|---|---|---|---|
|Error|5/29/2020 8:00:47 AM|ESENT|455|Logging/Recovery|svchost (6076,R,98) TILEREPOSITORYS-1-5-18: Error -1023 (0xfffffc01) occurred while opening logfile C:\WINDOWS\system32\config\systemprofile\AppData\Local\TileDataLayer\Database\EDB.log.|
|Critical|5/29/2020 8:03:48 AM|Kernel-Power|41|(63)|The system has rebooted without cleanly shutting down first. This error could be caused if the system stopped responding, crashed, or lost power unexpectedly.|

**Comment by WTassoux** [comment]
I'd say that it is extremely unlikely that VSCode is the culprit here, the software being run exclusively in userspace. However, after researching a bit, it seems that your encryption software installs a keyboard driver, which could lead to this kind of issue. You should probably fill a report to them instead.

**Comment by egamma** [comment]
@WTassoux thanks for you analysis.
