### ISSUE TITLE
Shell Script Syntax Highlight Bug

### ISSUE THREAD

**Issue by elony314** [microsoft/vscode#98797]
- VSCode Version: 1.45.1
- OS Version: macOS 10.15.5 (19F96)

Steps to Reproduce:

1. Set syntax highlight to shell scirpt.
2. Input following:
```shell
zinit ice wait lucid pick"it2git" as"program" atload'iterm2_print_user_vars() { it2git }'
zinit snippet https://raw.githubusercontent.com/gnachman/iterm2-website/master/source/utilities/it2git
```
3. get this:
![image](https://user-images.githubusercontent.com/25852061/83242343-1978ee00-a151-11ea-99d9-5424dfc8b9e1.png)

4. correct version:
![image](https://user-images.githubusercontent.com/25852061/83242492-5e048980-a151-11ea-8b6a-35ceee922980.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
We get our shell script grammar from https://github.com/atom/language-shellscript but they are no longer maintaining that grammar. I'll leave this issue open so that if we ever change our shell script grammar I can make sure it gets addressed.

**Comment by alexr00** [comment]
Linking and closing in favor of https://github.com/microsoft/vscode/issues/77675, which tracks considering a new shellscript grammar.
