### ISSUE TITLE
Trojan detected in Azure IoT Tools extension

### ISSUE THREAD

**Issue by frnk01** [microsoft/vscode#98791]
- VSCode Version: Latest
- OS Version: Windows 10

Steps to Reproduce:

1. Install Azure IoT Tools extension 
2. Windows defender prompts with malware found message

![E4185546-2009-447F-AB63-126D31A145E0](https://user-images.githubusercontent.com/2760702/83233973-d68a3b00-a18f-11ea-8bc7-5e7e92934205.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by egamma** [comment]
Please report the issue against the 'Azure IoT Tools' extension.
