### ISSUE TITLE
Append JSON settings list to list's defaults

### ISSUE THREAD

**Issue by TakingItCasual** [microsoft/vscode#98792]
When defining a JSON setting that takes a list, the current behavior is to replace the setting's defaults. I'd like for there to be a method to append to a setting's defaults, rather than replacing them. Relevant SO post here: https://stackoverflow.com/q/57796423

**Comment by egamma** [comment]
/needsMoreInfo can you please illustrate the desired behaviour with an example.

**Comment by TakingItCasual** [comment]
In my case, I'd like to append to the array of strings `latex-workshop.latex.clean.fileTypes`. The list has a default containing 22 values, so I'd like to avoid redefining it in my user settings. Instead of setting it like the following:
```
"latex-workshop.latex.clean.fileTypes": [
    <default value 1>,
    ...
    <default value 22>,
    <my value(s)>
]
```
I'd like to append to it, for example like so (although reserving `append` probably isn't feasible):
```
"latex-workshop.latex.clean.fileTypes.append": [
    <my value(s)>
]
```

**Comment by HannesGitH** [comment]
i'd also like to see this feature as i would like to add some specific values for a workspace without disregarding the user settings or default values.

a suggestion would be to use the spread operator (`...`) somewhat like:
```json
"latex-workshop.latex.recipes": [
    ...,
    {
        "name": "latexmk (xelatex)",
        "tools": [
            "xelatexmk"
        ]
    }
]
```

**Comment by nourgaser** [comment]
> i'd also like to see this feature as i would like to add some specific values for a workspace without disregarding the user settings or default values.
> 
> a suggestion would be to use the spread operator (`...`) somewhat like:
> 
> ```json
> "latex-workshop.latex.recipes": [
>     ...,
>     {
>         "name": "latexmk (xelatex)",
>         "tools": [
>             "xelatexmk"
>         ]
>     }
> ]
> ```

I know this is a closed issue, but it'd be a nice feature. It came to my mind because I'm using Latex Workshop as well and there's a massive default list of recipes and tools that clutter up my settings.json.

**Comment by sarabreu** [comment]
+1 need this feature
