### ISSUE TITLE
cannot set terminal process group (-1) when trying to run a C# console application (Ubuntu)

### ISSUE THREAD

**Issue by wk-done** [Microsoft/vscode#988]
When Starting VSCode in a console I get the following Message
```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```
VSCode runs well so far. But when I try to run a C# console-application the terminal window does not appear.

Also I cannot debug. If I hit F5 (after Building using a csproj-file) I get an errormessage that tells me:
```
error while processing request '{_request}' (exception: {_exception})
```

I also get the same results when I start VSCode by double clicking.

I run the following version on Ubuntu 14.04 64 Bit:
```
Version 0.10.3
Commit 783ecf841a2b21edca6d86853670cae89b4c244f
Date 2015-11-26T14:10:14.207Z
Shell 0.34.1
Renderer 45.0.2454.85
Node 4.1.1
```

**Comment by jrieken** [comment]
@wk-done What is you are trying to achieve? Running a C# app from terminal out of VS Code? Is it a msbuild app or dnx app? Please provide _exact_ steps like

1. have this code
2. do this
3. do that
4. _xyz_ happened which isn't expected

**Comment by jrieken** [comment]
Please provide the necessary details

**Comment by wk-done** [comment]
Shame on me. Please excuse me, I totally forgot that I asked here. The Problem does not occur any more.
