### ISSUE TITLE
Proxy window

### ISSUE THREAD

**Issue by luylucas10** [microsoft/vscode#98807]
Issue Type: <b>Bug</b>

I use my work pc inner a proxied lan and when I open vs code, it requests the username and password for the proxy auth, but that window stops to work, the ok and cancel buttons don't work anymore.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
This is fixed in `master` already.
