### ISSUE TITLE
Cannot edit file after creating it

### ISSUE THREAD

**Issue by aamirafridi** [microsoft/vscode#98800]
Issue Type: <b>Bug</b>

If you right click a folder and create a folder and file at the same time e.g. you right click a folder and enter `__mocks__/popper.js.js`
You cannot edit content of `popper.js.js`
I deleted the file and created it by right clicking `__mocks__` folder and it worked

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
sort-imports|ama|6.1.0
jest-snippets|and|1.8.0
vscode-eslint|dba|2.1.5
prettier-vscode|esb|4.7.0
auto-rename-tag|for|0.1.3
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.2.1
sublime-keybindings|ms-|4.0.7
code-svgr|Nat|1.0.0
markdown-preview-enhanced|shd|0.5.10
mdx|sil|0.1.0
code-spell-checker|str|1.9.0
vscode-status-bar-format-toggle|tom|2.0.0
gitblame|wad|4.0.1

(1 theme extensions excluded)

</details>

**Comment by egamma** [comment]
/needsMoreInfo cannot reproduce given the steps provided in the description.

**Comment by aamirafridi** [comment]
@egamma here https://gyazo.com/7110a11792155ab133012a48aa2e8604

**Comment by egamma** [comment]
@aamirafridi the action you are using creates a folder and not a file. To create a file use this action:

![image](https://user-images.githubusercontent.com/172399/83720972-6f123680-a63a-11ea-8c0e-2960caaa82ae.png)
