### ISSUE TITLE
 Duplicate function implementation error message while writing simple function

### ISSUE THREAD

**Issue by codingonHP** [Microsoft/vscode#9880]
- VSCode Version: 1.3.1
- OS Version: Windows 7
Steps to reproduce: 
1. Write one simple function
2. Notice the red underline
Error message : Duplicate function implementation.

Same happens for all the variables I declare using `let` keyword.
What am I doing wrong. I have tried examples from http://www.typescriptlang.org/docs/handbook/variable-declarations.html but they also show same error.

![image](https://cloud.githubusercontent.com/assets/7105293/17201581/685d0456-54ad-11e6-93c9-1c9c47275bb1.png)

![image](https://cloud.githubusercontent.com/assets/7105293/17201568/3dc20354-54ad-11e6-8349-572e1deeccd6.png)

![image](https://cloud.githubusercontent.com/assets/7105293/17201557/2bdfb532-54ad-11e6-91d6-c1f9e525250a.png)

**Comment by kieferrm** [comment]
@codingonHP I can't reproduce your problem with a simple ts file. Can your pls provide a sample workspace that exhibits the problem? Thanks!

**Comment by codingonHP** [comment]
@kieferrm Today when I re-opened my solution everything looks fine and there are no more errors like this. I have no idea about what must have happened yesterday. Now everything seems to be working as expected.

**Comment by kieferrm** [comment]
@codingonHP thanks!
