### ISSUE TITLE
Splitting code in two rows make a cloned chunk at the end of first ot two rows

### ISSUE THREAD

**Issue by nicolagranata** [microsoft/vscode#98809]
This problem occurs randomly but not infrequently.
I have a long row with a string to split:
eg:
$row_long="\<div class=first>text_1\</div>\<div class=second>text_2\</div>";
// now i split row adding "; " (note : chars are exactly doublequotes semicolon doublequotes - this not seems to happens when te string splitted is not a string in quoting)
$row_long="\<div class=first>text_1\</div>"; "\<div class=second>text_2\</div>" //note: this chunk is cloned after ENTER key is pressed
"\<div class=second>text_2\</div>" //[note: this is the original chunk splitted from long row;

You can see video:
<a href="http://imtools.it/press-area/vscode_insider_issue.mp4">Vscode insider chunk issue</a>

**Comment by egamma** [comment]
/needsMoreInfo

Thank you for the video, but I cannot see the issue. Can you please provide  detailed step by step instructions for how to reproduce the problem.
