### ISSUE TITLE
YAML Linting doesnt lint multiline scalars anymore

### ISSUE THREAD

**Issue by MaxRink** [microsoft/vscode#98804]
- VSCode Version: 1.45.1
- OS Version: Win10x86

Steps to Reproduce:
In previous versions vscode linted yaml in  multiline scalars, now it doesnt anymore:

1.45.1
![image](https://user-images.githubusercontent.com/4894735/83263623-32b88380-a1bf-11ea-964a-5ce9c9e1d7d6.png)

1.39.1
![image](https://user-images.githubusercontent.com/4894735/83263568-1f0d1d00-a1bf-11ea-805b-b7fdd6f46a76.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by MaxRink** [comment]
This also persists to current insider builds (eg 1.46.0)

**Comment by egamma** [comment]
Please report the issue against the YAML linter extension you are using.

**Comment by MaxRink** [comment]
YAML syntax highlighting and basic linting is literally a core feature of
vscode.
There is no extension installed at all

Erich Gamma <notifications@github.com> schrieb am So., 31. Mai 2020, 12:40:
