### ISSUE TITLE
Extension Host Crashes

### ISSUE THREAD

**Issue by AlexCraftt** [microsoft/vscode#98801]
Issue Type: <b>Bug</b>

При использовании приложения VS Code происходит ошибка "Хост-процесс для расширений неожиданно завершил работу". При нажатии на "Перезапустить хост-процесс для расширений" начинают загружаться расширения (на синей панели внизу справа), но в какой-то момент снова появляется эта же ошибка.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.43GB (1.51GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
vscode-eslint|dba|2.1.5
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|4.7.0
auto-close-tag|for|0.5.7
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.3
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.4.0
vscode-language-pack-ru|MS-|1.45.1
vsonline|ms-|1.0.2268
vuejs-extension-pack|mub|1.2.1
deepdark-material|Nim|3.2.1
vetur|oct|0.24.0
vscode-jest|Ort|3.2.0
prettier-vscode|pre|3.14.1
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.5
vscode-essentials-snippets|rob|2.0.0
vue-vscode-snippets|sdr|1.9.0
vscode-status-bar-format-toggle|tom|2.0.0
vscodeintellicode|Vis|1.2.7
vscode-wakatime|Wak|4.0.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
html-css-class-completion|Zig|1.19.0

(7 theme extensions excluded)

</details>

**Comment by oneslash** [comment]
Translation:
```
On the time of usage of VSCode, I get an error "Host-process for extensions stopped working", then I click on "Restart the host process for extensions" and I see them loading in the bottom blue bar, then at some point I have this error again.
```

**Comment by egamma** [comment]
/needsMoreInfo an extensionHost crash is typically caused by an extension and often the extension is using native code. From looking at your list I see no obvious culprit. The only way to narrow down the problem to a specific extension is to selectively disable an extension and check whether the issue reproduces.
