### ISSUE TITLE
VS Code start up delay

### ISSUE THREAD

**Issue by scandeiro** [microsoft/vscode#98808]
Issue Type: <b>Performance Issue</b>

VS Code is dealying a lot on start up. A progress bar could be better, in this case. It opened up three windows, because the lack of visual feedback on start up.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.4.0-33-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (3 x 2610)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 0|
|Memory (System)|7.78GB (4.31GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   127	  7292	code main
    0	    32	  7310	   zygote
    0	    56	  7381	   utility
    0	    72	  7396	   gpu-process
    0	   247	  7405	   window (Visual Studio Code)
    0	   104	  7735	     extensionHost
    1	   104	  7719	   shared-process
    0	     0	  7876	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  7877	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    1	   111	  7834	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none

**Comment by egamma** [comment]
/needsMoreInfo how long does it take for you for VS Code to startup? 
Can you pls use this guide to create a CPU profile of the startup https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly
