### ISSUE TITLE
Running extensions as worker threads

### ISSUE THREAD

**Issue by vijaybritto** [microsoft/vscode#98810]
I see my extensions consuming a lot of memory and I see they are run as separate node processes per extension. 
I think the resource consumption can be reduced significantly if the extensions are run as nodejs worker threads. Is this possible? Has there been any discussions on this already?

**Comment by egamma** [comment]
/needsMoreInfo 

>I see my extensions consuming a lot of memory and I see they are run as separate node processes per extension.

This is not fully accurate. There is an extensionHostProcess per window that runs all extensions loaded by this window.

>if the extensions are run as nodejs worker threads.

We are investigating how an extension can leverage a node worker to avoid blocking the extension host process. This is still in progress.



We
