### ISSUE TITLE
Cannot open remote folder loaded via SFTP

### ISSUE THREAD

**Issue by Ajeey** [Microsoft/vscode#9881]
- VSCode Version: 1.3.1 (1.3.1)
- OS Version: ubuntu 12.04

Steps to Reproduce:

1. I have connected to remote server via ubuntu's "connect to server" and using ssh.
2. And in VS, when I click on open folder, I do not see the remote server's content.

**Comment by bpasero** [comment]
The native file dialog is nothing we control, so marking as upstream.

**Comment by bpasero** [comment]
Closing, we really do not control the native file dialogs.

**Comment by Ajeey** [comment]
So basically you are saying a user cannot use Visual Studio if he is on Ubuntu and trying to load remote server's content.

That sucks! :(

**Comment by bpasero** [comment]
@Ajeey I say this issue should be reported against Ubuntu 👍
