### ISSUE TITLE
show eplorer keyboard shortcut not working on ubuntu 20.04

### ISSUE THREAD

**Issue by dhrunia** [microsoft/vscode#98824]
- VSCode Version: 1.45.1
- OS Version: Ubuntu 20.04
Steps to Reproduce:

1. Open a new file in vscode
2. Press ctrl+shift+e

Does this issue occur when all extensions are disabled?: Yes

Keyboard shortcut for `view: show explorer` is not working on ubuntu 20.04. Pressing ctrl+shift+e displays the letter "e" with an underscore and no further input from keyboard is taken until escape is pressed. See the attached gif demonstrating the issue. Also, I have the same issue on Debian testing on another machine as well.

![Peek 2020-05-29 18-43](https://user-images.githubusercontent.com/7869622/83285581-c3eb2280-a1de-11ea-958a-8aa28342ee65.gif)

**Comment by yunielrc** [comment]
Hi, @dhrunia , @kieferrm 

That Keyboard shortcut combination is used by the operating system, that creates conflict and that's why it doesn't work.

the vscode team should put another key combination for that functionality

**Comment by yunielrc** [comment]
@dhrunia 

1- open dconf Editor

2- change this:
![20200529_194116](https://user-images.githubusercontent.com/28462092/83313658-30692000-a1e5-11ea-84ba-028788a15f71.jpg)
3- by this:
![20200529_194133](https://user-images.githubusercontent.com/28462092/83313668-37902e00-a1e5-11ea-999b-c931b0faf6e6.jpg)

**Comment by jhpratt** [comment]
Do you have this installed as a snap or via apt? I originally had it as a snap, but installing it from apt resolves this.

**Comment by dhrunia** [comment]
It is installed via apt.

**Comment by isidorn** [comment]
You can change the default keybinding of vscode or you can do what @yunielrc proposed. Thus closing this. Thanks

**Comment by jaycverg** [comment]
I also encountered this issue but seems to be only if you installed from snap. I reinstalled using .deb and no keyboard issue so far.
