### ISSUE TITLE
VS Code freezes when starting up

### ISSUE THREAD

**Issue by anthony-gregg** [microsoft/vscode#98822]
- VSCode Version: The latest version was installed today and I do not know what version it was.
- OS Version: Windows 10 Build 1909

Steps to Reproduce:

1. I start up VS Code
2. After about 1-2 mins a message comes up saying "The window is no longer responding. You can reopen or close the window or keep waiting" with the appropriate buttons available for your choice.

Does this issue occur when all extensions are disabled?: I do not know as I get no control of the application after starting it. I cannot access anything in the product. Are there logs I can look at? I have three extensions installed, I believe: Powershell, Rest API and Azure Repos. Below is a screen shot of my VSCode with the error I get:
![VSCodeFrozenIssue](https://user-images.githubusercontent.com/23386642/83283327-ac8d4480-a1a0-11ea-8017-7c5fb15e3030.jpg)

**Comment by egamma** [comment]
/needsMoreInfo
@anthony-gregg does uninstalling and reinstalling of VS Code help?

**Comment by peter-sahajian** [comment]
Hello, I just want to point something out;
I have been having a similar issue, with the same error popup and symptoms, and one thing I want to point out, is it occurs when opening/having a Powershell (.ps1) file open. It seems to trigger the Powershell extension, and you will notice in the original post's attached image that the bottom right indicates VS Code is "Starting Powershell"... this is hanging.
When I personally use the command line to uninstall Powershell extension: `ms-vscode.powershell`, the hanging issue goes away.

This is no matter which version of VS Code I install, or if the ms-vscode.powershell extension is up to date (I had 2020.4.0).

 I don't know if they are related but I wanted to call out my similar experience.

**Comment by peter-sahajian** [comment]
Could be related to:
https://github.com/PowerShell/vscode-powershell/issues/2719

**Comment by egamma** [comment]
@peter-sahajian thank you for adding the additional information. Can you please report an issue against the Powershell extension and link it to this issue.

**Comment by anthony-gregg** [comment]
@peter-sahajian - Thanks so much for helping me here Peter. Sorry I have not been back in for awhile. Swamped at work .... :) I will go over to your issue that you opened in the Powershell Extension repo and check that out. 

Thanks also for the tip on uninstalling the extension from Command Line. I will do that so that I can at least use VS Code until the issue is resolved. Can't imagine that would be too long since it seems to render the extension useless until it is fixed.

Anthony

p.s. Where are the VS Code logs kept so that I can add them in the next time I open an issue?

**Comment by peter-sahajian** [comment]
> @peter-sahajian - Thanks so much for helping me here Peter. Sorry I have not been back in for awhile. Swamped at work .... :) I will go over to your issue that you opened in the Powershell Extension repo and check that out.
> 
> Thanks also for the tip on uninstalling the extension from Command Line. I will do that so that I can at least use VS Code until the issue is resolved. Can't imagine that would be too long since it seems to render the extension useless until it is fixed.
> 
> Anthony
> 
> p.s. Where are the VS Code logs kept so that I can add them in the next time I open an issue?

@anthony-gregg, my dude, no need to apologize... many of us have our full-time jobs and completely understand.

I am more than happy to have been able to help address your issue, especially since I myself and a few others I know are experiencing the same thing. Take a look at that other issue in the extension and lend your voice to help them find the issue/solution.

And yes, I am having to uninstall the extension to get VS Code to work, otherwise you have to wait for 2 minutes for the extension terminal to timeout (with an error) before you get control of the UI back, FYI.

Logs can be found by following the directions [here](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

**Comment by anthony-gregg** [comment]
@peter-sahajian - yep, I am going to focus my energy over on the other issue now. Thanks again for your further help re the logs Peter.

Anthony
