### ISSUE TITLE
watch variables lag on update

### ISSUE THREAD

**Issue by jupelester** [microsoft/vscode#98825]
Issue Type: <b>Bug</b>

I was debugging some code in python. I had a breakpoint set on a variable and I set up a watch to monitor the changes. When the line of code stopped at the breakpoint, I hit F10 run step over it but execute the code. The value in the watch did not change. I hit F10 again and it executed the line of code after the one with the breakpoint and THEN it updated the watch variable. Initially, I thought my code was wrong, but using the code executor at the bottom of the window (the ">") I was able to run the code snippet and get the result I was expecting. 

I exited Vscode and restarted VSCode and the problem persisted. I did not reboot. 

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (21.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
kite|kit|0.114.0
python|ms-|2020.5.80290

</details>
rd because it was too large to send. Please paste.

**Comment by egamma** [comment]
Please report the issue against the Python extension.
