### ISSUE TITLE
Extension list: problems with extensions uninstall and it's content update

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#98827]
Issue Type: <b>Bug</b>

Used with portable installation from zip, reproducible on regular user installation (haven't tried first steps there).
No extensions installed initially.

Unexpected behavior in middle steps are marked bold.

1. Open extensions list - 2 sections available Popular and Recommended
1. Type something in search bar (e.g. JavaScript) and install few extensions
1. Run `>Developer: Reload Window`
    1. Most of the times there's progress indicator above input field and on action bar icon
    1. I think search also broken after this moment - tying in input changes view but there are no requests or requests
1. Try to remove extension
    1. no change in appearance (should look like not installed one or have Reload button)
    1. Cursor over cog icon (manage) is no longer pointer but regular arrow
    1. On a few occasions after some delay I saw "Extensions have been modified on disk. Please reload the window." notification.
1. Run `>Developer: Reload Window` - extension I tried to uninstall still in the list, but I see "Extensions have been modified on disk. Please reload the window." notification almost immediately after reload.
1. Click on Reload window in notification - extension is gone

There are no problems with extensions uninstall if I close VS Code instead of Reloading window.

/cc @sandy081 

VS Code version: Code - Insiders 1.46.0-insider (cd41dd1f6065db76c77c6e2f659bb50e6f558dec, 2020-05-29T05:51:32.662Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (16.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>
This one left from testing, but reproduced on different extensions

Extension|Author (truncated)|Version
---|---|---
vscode-test-explorer|hbe|2.19.0

</details>

<details>
<summary>Removed known behavior</summary>

3. ~Click on Clear Extension Input or remove it's content manually~
    1. ~There are still Popular and Recommended sections, instead of Enabled, Recommended, and Disabled~

</details>

**Comment by sandy081** [comment]
> There are still Popular and Recommended sections, instead of Enabled, Recommended, and Disabled

I would skip this from this issue as it is a different and known issue. If wanted please file a separate issue for that. It would be easy to track.

**Comment by IllusionMH** [comment]
@sandy081 thanks, removed this step from description.

**Comment by sandy081** [comment]
@IllusionMH I cannot repro this behaviour on insiders.

Can you please repro again and when it happens provide me following info

- Log (Window)
- Console Log (Window)
- Log (Shared Process)
- Console log (Shared process)

**Comment by sandy081** [comment]
Thanks a lot @IllusionMH 

>  Is there a way to download Insiders .zip for a given date without collecting them locally every day?

It is not available for users but I can provide you the insiders download link for the day you want.

**Comment by IllusionMH** [comment]
Checked again today on two machines and I don't see any of mentioned problems in the latest build.

> It is not available for users but I can provide you the insiders download link for the day you want.

Thank you! I think I won't have time to bisect when issue was fixed, but hoped to know if there is an easy way.

---
And another off-topic question if you don't mind: is there a way to see what commits were used for insiders releases (for more precise log/diff in cases of regressions) or this info in public access is only in distributed builds?

**Comment by sandy081** [comment]
> if you don't mind: is there a way to see what commits were used for insiders releases (for more precise log/diff in cases of regressions) or this info in public access is only in distributed builds?

I do not know but I would request @joaomoreno if he is aware of any.

**Comment by joaomoreno** [comment]
If you know the commits of the two builds (always in the About dialog and in `--version`), then you can simply `git log A..B` or similar.

**Comment by IllusionMH** [comment]
That's the idea but I was wondering if there is a way how to get those commit hashes without need to download full copy.
