### ISSUE TITLE
Change cell language fires change event

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#98836]
Version: 1.46.0-insider
- Commit: cd41dd1f6065db76c77c6e2f659bb50e6f558dec
- Date: 2020-05-29T05:45:24.735Z
- Electron: 7.3.0
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Darwin x64 19.5.0

Steps to Reproduce:

1.Open a notebook
2.Create a markdown cell and change the language to `markdown`.

A notebook event if fires for change of cell language even though the current language is already the same.

I would not expect the event to get fired if the cell language is the same.
Also as a side effect the cell output change event also gets fired (feels this is a noop change, hence events shouldn't get fired)

Does this issue occur when all extensions are disabled?: Yes/No

@rebornix

**Comment by RMacfarlane** [comment]
I'm trying to use a `vscode.notebook.onDidChangeCellLanguage` listener, but this seems to never be called now, even if I do change a cell to a different language.

`vscode.notebook.onDidChangeNotebookCells` does get fired when the language is changed.

**Comment by rebornix** [comment]
@RMacfarlane did you switch only between Markdown and GitHub Issue Notebook, if so it's expected as switching between markdown and code cells is a cellsChange event but not a language change event.

**Comment by RMacfarlane** [comment]
Ah, yes, that is what I did. How do I change to a language outside of those?

**Comment by rebornix** [comment]
@RMacfarlane you can try 

* Firstly clone  https://github.com/microsoft/vscode-notebook-renderer-starter
* Add multiple language support to sample provider https://github.com/microsoft/vscode-notebook-renderer-starter/blob/master/src/extension/sampleProvider.ts#L49 . Change `languages` to `['json', 'css']`
* Register a cell language listener in https://github.com/microsoft/vscode-notebook-renderer-starter/blob/master/src/extension/extension.ts#L24 
* F5
* Create a `*.sample` file and open
* Switch language from `json` to `css`

**Comment by RMacfarlane** [comment]
Thanks, that worked!
