### ISSUE TITLE
Completions for $schema only work if string empty

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#9883]
- VSCode Version: insiders latest
- OS Version: os x

Steps to Reproduce:

1. Have a `myjson.json` with the following content
2. Trigger intelisense after character 'h' - notice you do not get any useful proposals
3. Delete 'h' and trigger intelisense again - notice all the proposals start with 'h'

```json
{
"$schema": "h|trigger intelisense here"
}
```

**Comment by aeschli** [comment]
Got fixed and works form me in the latest insiders.
@isidorn Can you verify as well?

**Comment by isidorn** [comment]
Works fine
