### ISSUE TITLE
Activity bar icon not visible

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#98833]
- VSCode Version: 1.45.1
- OS Version: Win 10 10.0.18363

Originally from @emendoza-dev in https://github.com/microsoft/vscode-docker/issues/2011.

The user has the Docker extension installed, but the icon does not show up in the activity bar. We cannot reproduce the issue; restarting VSCode or uninstalling/reinstalling the Docker extension doesn't help.

**Comment by gjsjohnmurray** [comment]
Maybe https://github.com/microsoft/vscode/issues/92323#issuecomment-611045838 will help

**Comment by bwateratmsft** [comment]
@emendoza-dev Can you try the workaround from that [comment](https://github.com/microsoft/vscode/issues/92323#issuecomment-611045838)?

> I had entries at `HKEY_CLASSES_ROOT\.svg` that were leftovers from ConceptDraw installation. Deleting these and reloading vscode resolved my issues with missing icons

**Comment by emendoza-dev** [comment]
thanks a lot to both. It was the problem. It's working right now.
