### ISSUE TITLE
[dark theme] flash on right mouse click

### ISSUE THREAD

**Issue by sergiocntr** [microsoft/vscode#98837]
Hi all
When I do a mouse right click in order to show the context menu a annoying white flash shows before the menu...how to avoid this that hurts my eyes. 
Thank you so  much. 
![image](https://user-images.githubusercontent.com/7195587/83304147-a1690180-a1fe-11ea-993e-e090b9aa7342.png)

**Comment by sergiocntr** [comment]
this is still with "disable-hardware-acceleration": true.

**Comment by sergiocntr** [comment]
this version works fine without issue

![image](https://user-images.githubusercontent.com/7195587/83323048-757c6900-a25c-11ea-9db8-4205adfac431.png)

**Comment by sergiocntr** [comment]
also this works fine

![image](https://user-images.githubusercontent.com/7195587/83323104-e459c200-a25c-11ea-9548-fffd8848ed79.png)

**Comment by sergiocntr** [comment]
also this fine

![image](https://user-images.githubusercontent.com/7195587/83323164-41ee0e80-a25d-11ea-8cd3-3c63df44a9db.png)

**Comment by sergiocntr** [comment]
also this works fine ,no flash issue opening menu item

![image](https://user-images.githubusercontent.com/7195587/83323271-d9ebf800-a25d-11ea-9611-1e25092b3a3d.png)

**Comment by sergiocntr** [comment]
**THIS VERSION INTRODUCED FLASH BUG** ,flash also launcing code ,flash opening menus.

![image](https://user-images.githubusercontent.com/7195587/83323296-1a4b7600-a25e-11ea-8bfc-fb204e0f3f5e.png)

**Comment by yume-chan** [comment]
Looks like #80798

Which distribution are you using?

**Comment by sergiocntr** [comment]
> Looks like #80798
> 
> Which distribution are you using?

Yes,it's just the same,thanks for point this out.

Debian 10 buster with LXDE windows manager
Linux debian 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
