### ISSUE TITLE
'git commit' opens a new VSCode Insiders window instead of a new tab

### ISSUE THREAD

**Issue by Lutrome** [microsoft/vscode#98849]
Issue Type: <b>Bug</b>

1. Set up multi-line commit message as shown here: https://stackoverflow.com/questions/30149132/multiline-git-commit-message-in-vscode/54139152#54139152
2. Set git default editor to 'C:\\Users\\your user dir\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\Code - Insiders.exe' --wait in .gitconfig file
3. Execute 'git commit' in Git Bash terminal in VSCode Insiders
4. New VSCode Insiders window opens instead of a new tab with GITCOMMIT

VS Code version: Code - Insiders 1.46.0-insider (cd41dd1f6065db76c77c6e2f659bb50e6f558dec, 2020-05-29T05:51:32.662Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.10.0
gitlens|eam|10.2.1
vscode-pull-request-github|Git|0.16.1
discord-vscode|icr|3.14.0
mssql|ms-|1.9.0
vscode-postgresql|ms-|0.3.0
python|ms-|2020.5.80290
remote-wsl|ms-|0.44.2
java|red|0.62.0
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.22.4
vscode-maven|vsc|0.21.4
vscode-icons|vsc|10.1.1
material-theme|zhu|3.7.1

</details>

**Comment by yume-chan** [comment]
Please add the `-r`  (`--reuse-window`) parameter to your command line.

**Comment by Lutrome** [comment]
That worked! Thank you!
