### ISSUE TITLE
I cannot type 'n' key editor window.

### ISSUE THREAD

**Issue by ggshappy** [microsoft/vscode#98848]
Issue Type: <b>Bug</b>

I cannot type 'n' key on the editor window.
if I do in another windows in Visual studio, it still works.
Also if I do Shift+n. it works.
though I put Caps Lock on and just press 'n' it doesn't work either...

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (3.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.28.1

</details>

**Comment by egamma** [comment]
/needsMoreInfo please follow this guide to troubleshoot keyboard issues https://github.com/microsoft/vscode/wiki/Keybinding-Issues
