### ISSUE TITLE
Opening a notebook triggers a cell change

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#98841]
Version: 1.46.0-insider
- Commit: cd41dd1f6065db76c77c6e2f659bb50e6f558dec
- Date: 2020-05-29T05:45:24.735Z
- Electron: 7.3.0
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Darwin x64 19.5.0

Steps to Reproduce:

1.Open a notebook
2.The cell change event gets fired.

User hasn't made any chanages, but opening a notebook triggers the change event to get fired. I think its unnecessary.

Does this issue occur when all extensions are disabled?: Yes/No

@rebornix

**Comment by rebornix** [comment]
Good catch, the event should not be emitted.

**Comment by JacksonKearl** [comment]
the docs here could better describe when it actually gets called, I was expecting it to be called whenever a cells content changed, not when cellls get added/removed

https://github.com/microsoft/vscode-github-issue-notebooks/blob/e8ca5b4be951df8598d877d7603aa2804e0ef05d/src/vscode.d.ts#L1483
