### ISSUE TITLE
Errors aren't cleared when isWatching is true

### ISSUE THREAD

**Issue by lex57ukr** [Microsoft/vscode#9884]
- VSCode Version: 1.3.1
- OS Version: OS X, 10.11.6

Steps to Reproduce:

1. Define a command in tasks.json to use with "isWatching" : true and a custom problemMatcher.
2. Problem matcher will report errors but those errors won't get cleared if fixed / on auto-recompile.

If I remove the isWatching, everything works properly.

**Comment by dbaeumer** [comment]
@lex57ukr does your problem matcher have a 
```json
        "watching": {
            "beginsPattern": '...',
            "endsPattern":  '...'
        }
```
section. Otherwise VSCode doesn't know when to clear errors (e.g. when an incremental compile runs)

**Comment by lex57ukr** [comment]
@dbaeumer that was it. Thank you!

When is this going to be finalized though? The documentation does not mention anything about the *watching* section for problem matchers...
