### ISSUE TITLE
Add cursor to line ends -> broken with more than 9999 lines

### ISSUE THREAD

**Issue by martinandersen3d** [microsoft/vscode#98840]
- VSCode Version: 
- OS Version: win10

Steps to Reproduce:

1. Create 15000 lines of words
2. Select all
3. editor.action.insertCursorAtEndOfEachLineSelected
4. type a comma ","
5. scroll to line 9999--- there should be a comma at every line end, but there is not

a warning message pops up, saying that the number of cursors is limited to 10000, maybe this should be increased or removed..? old code maybe? :-) 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexdima** [comment]
Let's track in #81589
