### ISSUE TITLE
Wordwrap scrolls to the right

### ISSUE THREAD

**Issue by Sibz** [microsoft/vscode#98853]
Issue Type: <b>Bug</b>

Expected:
When I write towards the end of a line, the non-fitting word should drop to the next line without scrolling to the right.

Actual:
Sometimes the screen scrolls to the right before dropping to the next line. Sometimes it scrolls back, other times it doesn't.

Steps taken to produce bug:
Created Markdown file. 
Ensure Minimap is enabled. (I was able to reproduce reliably with minimap, but it occurs also without).
Write to the end of line.
Write a large last word and observed scrolling.
Write a small last word and observed that it doesn't scroll.

Workaround:
None

A video of the bug available here: https://youtu.be/iwMUKSNXipE

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (6.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.1
vscode-docker|ms-|1.2.1
csharp|ms-|1.22.0
vscode-yaml|red|0.8.0
markdown-preview-enhanced|shd|0.5.10

</details>

**Comment by alexdima** [comment]
The root cause is the decoration added at the end of the line by the gitlens extension.

Let's track in #32856
