### ISSUE TITLE
flutter 项目，无法打印

### ISSUE THREAD

**Issue by pangzhanli** [microsoft/vscode#98856]
Issue Type: <b>Feature Request</b>

在flutter项目中，执行print函数时，控制台不打印信息

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.3.0

**Comment by dingyx99** [comment]
Translation to this issue:

Issue Type: Feature Request

In a Flutter project, no output in the console when executing `print` function.

VS Code version: Code 1.45.1 (5763d90, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.3.0
