### ISSUE TITLE
[html, javascript] Autocomplete for brackets/quote marks doesn't work inside HTML tags, and autocomplete for brackets/braces doesn't work inside quote marks 

### ISSUE THREAD

**Issue by MichaelNZ85** [microsoft/vscode#98855]
- VSCode Version:  1.45.1
- OS Version: Catalina (10.15.4)

Steps to Reproduce:

1. Open an HTML file
2. Create a tag, e.g. <h1></h1>
3. Type a quote mark. No closing quote mark will be shown

Does this issue occur when all extensions are disabled?: Yes

A similar issue occurs when using templating languages like Blade. If you have an <a> tag, and add src="{route: 'homeController@show'}">,when you type the opening brace, the closing brace will not be automatically inserted - you have to type it yourself..

**Comment by egamma** [comment]
/needsMoreInfo please illustrate the issue with an example and screenshots.
