### ISSUE TITLE
Blurry Screen

### ISSUE THREAD

**Issue by ledinhthuc** [microsoft/vscode#98851]
Issue Type: <b>Performance Issue</b>

Window getting blurs when i open VS Code on the second screen that has higher resolution. i don't get the same problem in other applications.

First, i opened VS Code on my device (1366x768)
 (i fixed the issue on the device already. that means it showed up sometimes before.)
Then, connect to my 2nd screen (1600x900), when i open a VSCode window on the 2nd screen, it gets blurred.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.85GB free)|
|Process Argv|--folder-uri file:///d%3A/__petPrjs/flutter/lordscalc|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mxrachel** [comment]
Does launching code with ```--disable-gpu``` help fix the problem?

**Comment by ledinhthuc** [comment]
> Does launching code with `--disable-gpu` help fix the problem?

**Comment by ledinhthuc** [comment]
> Does launching code with `--disable-gpu` help fix the problem?

**Comment by deepak1556** [comment]
@ledinhthuc is this still an issue with our latest insiders https://code.visualstudio.com/insiders ?
