### ISSUE TITLE
cannot select an entry in the Output pane drop down while connecting to CodeSpace

### ISSUE THREAD

**Issue by lukka** [microsoft/vscode#98850]
Issue Type: <b>Bug</b>

start vscode
switch to codespace extension
select a Cloud hosted codespace and Connect to it
a new document appeas with title: "Resuming Codespace Name".

While this is running, I cannot use the Output pane's drop down to switch to different output loggers

VS Code version: Code - Insiders 1.46.0-insider (da98a19a5d6724367bd99c8ec3b8f55054be37d1, 2020-05-20T22:21:02.272Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (45.52GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.5
xml|Dot|2.5.0
gitlens|eam|10.2.1
compareit|in4|0.0.2
vscode-graphviz|joa|0.0.6
vscode-peacock|joh|3.7.2
chat|kar|0.33.0
git-tree-compare|let|1.9.1
csharp|ms-|1.22.0
remote-wsl|ms-|0.44.2
azure-account|ms-|0.8.11
cpptools|ms-|0.28.1
powershell|ms-|2020.4.0
vsliveshare|ms-|1.0.2236
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.3.4
vsonline|ms-|1.0.2268
quantum-devkit-vscode|qua|0.11.20042825
vscode-hexdump|sle|1.7.2
clang-format|xav|1.9.0

</details>

**Comment by egamma** [comment]
Please report the issue against the Codespace extension.
