### ISSUE TITLE
Find in Folder case insensitive search seems to be broken

### ISSUE THREAD

**Issue by Zeriph** [microsoft/vscode#98852]
Go to global search ('Find in Folder') and do a search with case sensitive search turned off; if you do **all** lowercase for your search term you will get a search result as expected with any number of mixed upper/lower case. Do the same search term in all upper case with case sensitive search still turned off and you get **only** the upper case results, where I would expect to get any and all results regardless of case. This is true for any number of variations to the case of the search term.

**Comment by usernamehw** [comment]
Do you have `search.smartCase` setting enabled?

**Comment by Zeriph** [comment]
That was completely the case! I've been using the old version waiting for the Product Icon Theme release and didn't know that was a setting (and was re-enabled apparently).

Thanks! Closing the issue.
