### ISSUE TITLE
Convert npm script to Task

### ISSUE THREAD

**Issue by drschwabe** [microsoft/vscode#98854]
Simple right-click on any npm script and 'Create Task' then it auto-populates your tasks.json file with the aformentioned script in a task format (ie- such that you can run the task it would execute the npm script) 

By the way - for some projects, we may have hundreds of npm scripts across dozens of files.  This makes the NPM SCRIPTS pane difficult to use.     So it's almost exclusively for this reason I single a few out as Tasks to make them easier to find.  Another reason to make them Tasks is that they become easier to restart; that is a related separate issue:  npm scripts in VSCode are oddly difficult/unintuitive to restart as highlighted by microsoft/vscode/issues/95291

**Comment by yume-chan** [comment]
In my testing the `Task: Configure Task` command should list all your npm scripts.

![image](https://user-images.githubusercontent.com/1330321/83344652-666ce800-a33c-11ea-8da8-4b5c31360e6e.png)

Choose the one you want will create the corresponding task in `tasks.json` for you.

![image](https://user-images.githubusercontent.com/1330321/83344659-87cdd400-a33c-11ea-9403-8a73cea6bd00.png)

**Comment by egamma** [comment]
/needsMoreInfo have you tried to run the tasks using 'Terminal>Run Tasks...' and then select 'npm'.

![image](https://user-images.githubusercontent.com/172399/83350100-f9f0e980-a339-11ea-9497-af2eaa59a224.png)

![image](https://user-images.githubusercontent.com/172399/83350119-23aa1080-a33a-11ea-934f-3d0610ce8b3e.png)


Once you have selected a task there it shows up in the history section and can be easily re-executed again.

**Comment by drschwabe** [comment]
Thanks @yume-chan that solution basically solves this feature request!   

However, it would be more convenient to right-click a npm script from within the editor pane and then select "Configure Task"  (currently in VS Code when you do right click a npm script within editor you  get an option to "Run Script" so this is where I suggest adding shortctut for "Configure Task" ). 

And thanks @egamma that is another way to somehwhat conveniently run/re-run a script - it would be much more intuitive howerver to restart the task from the Terminal area where said Task's output is displayed (ie- beside the 'trash' icon or '+' for new terminal) 

But otherwise, the issue is basically solved so feel free to close - or if you think it's worthwhile as I suggest to offer a right-click context menu for "Configure Task" (and the secondary request of making a button to restart task in Terminal area) then perhaps leave open or file it in the queue however.

**Comment by egamma** [comment]
@drschwabe I still don't full understand why you need to convert the NPM script into a task. NPM scripts can be automatically run as a Task. Do you want to configure the Task used to run the NPM script?

**Comment by drschwabe** [comment]
@egamma the original reason was primarily UI because I have hundreds of npm scripts in a given project and so those Tasks are buried making it difficult to quickly find them; the thinking was by making a select few of them formal VS Code Tasks (ie- scripts that I run more frequently than others) we can more easily find those; particularly using the Task Explorer extension which improves Task UI. 

And yes, some of the npm scripts I run there is a need to specify the version of node that runs with it; so in these cases it would also be convenient to have a quick way to convert a given npm script to a Task. 

And finally, when you run a script from an npm file (ie- by right clicking the name of the script from within the package.json file in editor) the process is not run as a Task.   This is inconvenient cause now we cannot easily restart the script; so on this regard another request is to make VS Code run npm scripts in this right-click from editor context as Tasks not as anonymous terminal process.   This latter request here is most important above all now that I've had a bit longer to experiment with Tasks workflow and VS Code; perhaps I will open a separate issue for that.

**Comment by egamma** [comment]
@drschwabe thanks for the clarification. Please open a separate feature request for:

>This is inconvenient cause now we cannot easily restart the script; so on this regard another request is to make VS Code run npm scripts in this right-click from editor context as Tasks not as anonymous terminal process.
