### ISSUE TITLE
Auto suggestions appear small

### ISSUE THREAD

**Issue by kasiliwachiye** [microsoft/vscode#98869]
![Screenshot (23)](https://user-images.githubusercontent.com/63935096/83328378-d1f27f00-a282-11ea-9c00-73229792d204.png)
Issue Type: <b>Bug</b>

I have a problem with the auto suggestions on the VS Code where they appear small and I can't quite see them.

I thought installing and reinstalling might help but the problem is still there.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.21
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
beautify|Hoo|1.5.0
vscode-language-babel|mgm|0.0.27
debugger-for-chrome|msj|4.12.8

</details>

**Comment by egamma** [comment]
/needsMoreInfo have you changed the value of `editor.suggestFontSize`?

**Comment by kasiliwachiye** [comment]
Thanks @egamma it worked!
