### ISSUE TITLE
1px white line on second screen after startup in fullscreen

### ISSUE THREAD

**Issue by Rummskartoffel** [microsoft/vscode#98867]
Issue Type: <b>Bug</b>

**Reproduce**:
1. Start VS Code
2. Maximise the window
3. Restart VS Code

**Expected**: VS Code remembers the previous session and starts maximised normally

**Actual**: VS Code does start maximised, but there is a 1px wide white line on the edge of the neighbouring screen. Restoring, then maximising again removes the line. The line is only visible when VS Code is the active window. This only occurs after upgrading to Windows 10 2004.

This may have something to do with electron/electron#5267, which I found when googling for the issue, but I'm not sure, because the screenshots there show a thicker section that actually contains part of the window, which is not the case here. It also occurs with [Discord](https://discord.com), which is an otherwise unrelated Electron app.
![image](https://user-images.githubusercontent.com/20257197/83327439-20504f80-a27c-11ea-87d7-bb06614a20a8.png)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (10.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.44.2

</details>

**Comment by alexitx** [comment]
Same issue here. Started occurring after updating to Windows 10 2004. Also present with `--disable-extensions` flag.

```
VSCode 1.45.1
Windows 10 19041.264
NVIDIA Driver 446.14
Primary monitor: 1920x1080 60Hz
Secondary monitor: 1600x900 60Hz
```

**Comment by stefanhamburger** [comment]
Can confirm this issue after updating to Windows 10 2004, and it affects other Electron apps as well, including Microsoft Teams and GitHub Desktop. So this may have to be fixed upstream with Electron and not in VS Code.

Note however while Teams and GitHub Desktop will draw a bright white line (#ffffff), VS Code actually uses the background color from the current theme, so in my case the line is colored \#282828. Note that changing the theme does not update the color, nor does using the "Reload window" command help, instead I have to exit VS Code and restart it to have the line show up in the new theme's background color.

**Comment by deepak1556** [comment]
Merging this to https://github.com/microsoft/vscode/issues/98867
