### ISSUE TITLE
refactoring of imports on filename change

### ISSUE THREAD

**Issue by bkilinc** [microsoft/vscode#98862]
I changed MyClass.js to my-class.js and imports are refactored as follows 
import MyClass from './my-class.js/index.js';
it should be 
import MyClass from './my-class.js';

**Comment by mjbvz** [comment]
Please fill out the issue template and share a code example

/needsMoreInfo

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
