### ISSUE TITLE
Drop down shade has blinking white effect ( dark theme ) on MintOS

### ISSUE THREAD

**Issue by kenny-ngo** [microsoft/vscode#98863]
- VSCode Version: 1.45.1
- OS Version:
kenny@Z97M-D3H:~$ uname -a
Linux Z97M-D3H 5.3.0-53-generic #47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
kenny@Z97M-D3H:~$ cat /etc/lsb-release 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.3
DISTRIB_CODENAME=tricia
DISTRIB_DESCRIPTION="Linux Mint 19.3 Tricia"
kenny@Z97M-D3H:~$

Steps to Reproduce:

1.Using theme: https://www.gnome-look.org/p/1267246/ 
2.Regarless which theme I use, it still produces the same affect.

[2020-05-30 05-04-48.mkv.zip](https://github.com/microsoft/vscode/files/4705387/2020-05-30.05-04-48.mkv.zip)

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by max-programming** [comment]
There is one solution. You can change the title bar style in settings.
Or adding `"window.titleBarStyle": "custom"` to settings.json.
That will give the custom vs code styling

**Comment by egamma** [comment]
/needsMoreInfo can you please add a screenshot that illustrates the problem?
