### ISSUE TITLE
Test: canonical URIs

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98861]
https://github.com/microsoft/vscode/issues/93368

- [x] macOS @chrmarti
- [x] Windows @lszomoru
- [x] Linux @RMacfarlane

Complexity: 4
Authors: @jrieken @bpasero

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%2398861%0A%0A)

---

Canonical URIs respect the file system providers case-sensitivity capability. Given a file system that is case-insensitive (e.g. macOS, Windows in most cases), the first creator of a canonical URI defines its casing and subsequent URIs of different casing will have the same canonical form. 

The following is an example where canonical URIs help a lot:
* a user opens a file `path/someFile.c` from the explorer
* an extension produces markers by parsing the output of a compilation task
* the task decides to output file paths in lowercase
* the task finds an error in the file the user opened and emits a marker for `path/somefile.c`
* the user wants to open a marker from this output and clicks it
* at this point we would open a second editor for `path/somefile.c` even though the user already had the file opened with different casing

With canonical URIs, the user defined the canonical URI to be `path/someFile.c` when opening it. Even though the output is using `path/somefile.c` form, the markers are being created with the `path/someFile.c` path and thus match. You will only end up with a single editor opening, not two.

Canonical URIs have been adopted in the following places:
* any editor that opens
* any extension creating a document (`vscode.workspace.openTextDocument`)
* any marker that is created from an extension

**Test**
* opening editors with different casing only opens different editors on Linux, but same editors on Windows/macOS (e.g. try with producing links in the terminal or links in a text document)
* you can still rename files or parent folders to the same name but different case from the explorer and things continue to work as normal (note: a known issue is that the case change is not reflected in the editor because canonical URIs currently have no lifecycle)
* create an extension that produces markers with different casing and verify the scenario from above
* create an extension that uses the `vscode.workspace.openTextDocument` API and ensure that only on Linux you get different models for different casing

**Comment by chrmarti** [comment]
@bpasero With markers you mean `TextEditor.setDecorations()` in the extension API?

**Comment by jrieken** [comment]
Yeah, the API is using the diagnostic collection. Something like this is what I have

```ts
const diag = vscode.languages.createDiagnosticCollection('muhaha');


	for (let path of [
		'/Users/jrieken/Code/_samples/devfest/foo/TEST.less',
		'/Users/jrieken/Code/_samples/devfest/foo/TEST.ts'
	]) {
		const uri = vscode.Uri.file(path);
		const d = new vscode.Diagnostic(new vscode.Range(0, 0, 1, 0), 'casing matters', vscode.DiagnosticSeverity.Information);
		diag.set(uri, [d])
	}
```

**Comment by chrmarti** [comment]
Thanks. Also found a nice sample: https://github.com/microsoft/vscode-extension-samples/tree/master/diagnostic-related-information-sample
