### ISSUE TITLE
Add "clear extension input" command

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#98865]
Global search panel has a "clear search result" command, for consistency, would like to have a "clear extension input" command as well.

**Comment by egamma** [comment]
/needsMoreInfo what do you mean by "clear extension input", what would this command do?

**Comment by serenedu** [comment]
@egamma Hello, if you hover over this icon, it says "clear extension input"
![image](https://user-images.githubusercontent.com/28700378/83349909-c5e1ec80-a36a-11ea-8d56-735a99697a4a.png)

**Comment by egamma** [comment]
@serenedu just to confirm you are asking for a command 'Clear Search Input' in the Search View?

**Comment by serenedu** [comment]
Yes, for the extension panel. @egamma

**Comment by egamma** [comment]
@serenedu I'm still confused about your request.

- the Search View has an action 'Clear Search Results', this action clears the search input field and empties the search results
- the Extension View has an action 'Clear Extension Input', this action clears the input field and clears the search results.

Is you issue about the fact that these actions are not labeled consistently? That is, that the action in the Extension View should be called 'Clear Extension Search Results'?

**Comment by serenedu** [comment]
@egamma "Clear Search Results" has a command, whereas "Clear Extension Input" doesn't, I'm asking a command for "Clear Extension Input", the naming is fine for me, hope this clears your confusion :).

**Comment by egamma** [comment]
@serendu thanks for the clarification and my deepest apologies for immediately understanding your desire.

**Comment by egamma** [comment]
@sandy081 I suggest to rename the extension from 'Clear Extension Input' to 'Clear Extension Search Results'

**Comment by wenfangdu** [comment]
Add this piece of code to `keybindings.json`, pressing `escape` could clear extension search result now, thanks @egamma @sandy081 
```json
  {
    "key": "escape",
    "command": "workbench.extensions.action.clearExtensionsSearchResults",
    "when": "sideBarFocus && activeViewlet == 'workbench.view.extensions'"
  }
```
