### ISSUE TITLE
showTextDocument fails if run in parallel

### ISSUE THREAD

**Issue by lars-soem** [microsoft/vscode#98871]
This issue may be related to #51906 and #73595 that were closed without a solution. At least, the error message I get is the same:
```
Failed to show text document ..., should show in editor #undefined
```
Below is a simple example that provokes the error. It opens two documents with different schemes using `openTextDocument` and then shows them using `showTextDocument`. Both documents will get opened, but the first will return the error message above.

Code to reproduce:
```
import * as vscode from 'vscode';

export class Provider {
   provideTextDocumentContent () {
      return 'Hello, world';
   }
}

async function test () {
   let uri1 = 'file:///home/lh/.bashrc';
   let uri2 = 'foo:///bar';
   let doc1 = await vscode.workspace.openTextDocument(vscode.Uri.parse(uri1));
   let doc2 = await vscode.workspace.openTextDocument(vscode.Uri.parse(uri2));
   vscode.window.showTextDocument(doc1, {preview: false}).then(
      () => {},
      err => vscode.window.showErrorMessage(`Can't show ${uri1}: ${err}`)
   );
   vscode.window.showTextDocument(doc2, {preview: false}).then(
      () => {},
      err => vscode.window.showErrorMessage(`Can't show ${uri2}: ${err}`)
   );
}

export function activate (context: vscode.ExtensionContext) {
   context.subscriptions.push(
      vscode.workspace.registerTextDocumentContentProvider('foo', new Provider()),
      vscode.commands.registerCommand('lhTest.test', test)
   );
}
```

**Comment by jrieken** [comment]
Yeah, the problem is that you aren't awaiting the first call and that the second call to `showTextDocument` "cancels" it, e.g you open two editors in the same space but there can only be one editor (not that editors are different than editor tabs). I can tweak the error message but you it's likely that you won't get want you are looking for.

**Comment by jrieken** [comment]
> I was opening a bunch of files (editors) in parallel, and it works well as long as they have the same scheme.

I am not sure why the `scheme` would change that? There can only be one editor (not tab) per group and when calling `showTextDocument` in parallel only one will succeed.

**Comment by jrieken** [comment]
Two options to be discussed when calling `showTextDocument` repeatedly without await then

1. As today, fail but with a better error message
1. Sequentialise all calls internally so that for a short time the request editor is the actual editor
