### ISSUE TITLE
`Replace All` button should have a different UI

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9887]
![image](https://cloud.githubusercontent.com/assets/22350/17208181/b69f3bd4-54b7-11e6-976e-63ab5915a291.png)

I know we talked bout it, just not sure you had an issue for it, @sandy081.

The `Replace All` action looks like a toggle, not like an action. It would be great to get some UX in here. cc @bgashler1 @stevencl

**Comment by stevencl** [comment]
Just to get the conversation started, here's what it might look like exposed as a regular button:


![replaceall](https://cloud.githubusercontent.com/assets/1704059/17331755/327b4dd2-58c4-11e6-9920-2e4226b12cdb.png)

While it pushes the results down by a line, I think it makes the workflow a bit clearer.

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/17359557/660dfdc2-5967-11e6-98bd-fba867ce1381.png)

Wanted to see how that looked.

**Comment by sandy081** [comment]
I liked the idea of keeping Replace all button next to replace input box. We can also place Replace button and make it look similar to Find widget.

**Comment by stevencl** [comment]
Consistency with the find UX is good. Let's go with this option and see how it works.

**Comment by stevencl** [comment]
General consensus from the UX meeting was that this is the right approach too.

**Comment by sandy081** [comment]
![screen shot 2016-08-05 at 11 31 49 am](https://cloud.githubusercontent.com/assets/10746682/17432579/40ee15a0-5b00-11e6-97a5-10079da12710.png)


Moved replace all action outside replace input box.
