### ISSUE TITLE
Paste format doubly messed up

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#98879]
- VSCode Version: 1.45.1
- OS Version: Catalina

Copying and pasting code into VSCode results in very poorly indented code. Disabling the Format on Paste setting has no effect.

Please, *please* stop trying so hard to smart indent code on paste. Just insert the characters exactly as laid out in the clipboard, at the point in the tab where the cursor lies.

Steps to Reproduce:

1. Paste code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
/needsMoreInfo please illustrate the problem with screenshots. What programming language is used in the file when this happens?
