### ISSUE TITLE
Markdown Preview not loading in Codespaces (Brave Browser)

### ISSUE THREAD

**Issue by joshspicer** [microsoft/vscode#98876]
[Brave browser](brave.com) is getting increasingly popular as a web browser.  Codespaces works quite well with Brave, but one instance it doesn't is with markdown file previews.

![image](https://user-images.githubusercontent.com/23246594/83336245-cea9c400-a27f-11ea-828f-f857b45b982b.png)

![image](https://user-images.githubusercontent.com/23246594/83336265-00228f80-a280-11ea-8550-fbd5f34be2c7.png)

I'd suggest displaying an error indicating that Brave Shield must be disabled, or working around brave shield.

**Comment by mjbvz** [comment]
So it works when you disable Brave Shield? If so, this sounds like a bug with  Brave Shield to me
