### ISSUE TITLE
Tokenization Dart

### ISSUE THREAD

**Issue by zzj0402** [microsoft/vscode#98878]
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.2.0 

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/15345547/83337396-0744ae80-a30f-11ea-8a1a-230491ef1d53.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
please report the issue against the Dart extension.

**Comment by zzj0402** [comment]
> please report the issue against the Dart extension.

It's caused by tokenization.

**Comment by egamma** [comment]
@zzj0402 not sure I understand what you mean. The tokenization for Dart files is contributed by the dart extension and not done by VS Code. Therefore the issue should be reported againsted the dart extension

**Comment by zzj0402** [comment]
> @zzj0402 not sure I understand what you mean. The tokenization for Dart files is contributed by the dart extension and not done by VS Code. Therefore the issue should be reported againsted the dart extension

https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-token-provider

Here says vs code uses Text Mate. Again I don't see how closing solves issues.

**Comment by egamma** [comment]
>Here says vs code uses Text Mate. Again I don't see how closing solves issues.

This is correct, but the text mate rules for Dart files are contributed by the Dart extension. Therefore please file the issue against this extension. We cannot fix it in VS Code itself.
