### ISSUE TITLE
VScode cann't open file Jupyter Notebook

### ISSUE THREAD

**Issue by huy105** [microsoft/vscode#98885]
- VSCode Version:
- OS Version:

Steps to Reproduce:
I just met this problem a few day. When i open Jupyter Notebook, it doesn't convert to cell. Sometime, It finally convert in few minutes, sometime it don't.

![image](https://user-images.githubusercontent.com/55435653/83344599-281efb00-a333-11ea-9466-4ce309fdd5b5.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by richardyy1188** [comment]
Will reinstalling the python extension help ?

**Comment by egamma** [comment]
Please report the issue against the python extension.
