### ISSUE TITLE
Output Issue

### ISSUE THREAD

**Issue by CHAOS-007** [microsoft/vscode#98889]
Issue Type: <b>Bug</b>

The Chinese character output shows as messy codes when using UTF-8 as default coding standard, which should not happen.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (9.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
c-cpp-compile-run|dan|1.0.11
vscode-markdownlint|Dav|0.36.0
vscode-eslint|dba|2.1.5
code-runner|for|0.10.0
mdmath|goe|2.4.0
auto-markdown-toc|hun|3.0.5
vscode-language-pack-zh-hans|MS-|1.45.1
python|ms-|2020.5.80290
remote-wsl|ms-|0.44.2
cpptools|ms-|0.28.1
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0

</details>

**Comment by egamma** [comment]
/needsMoreInfo what are the 'messy codes'? Please illustrate the issue with some screenshots.
