### ISSUE TITLE
Allow extensions to know which extension created terminal

### ISSUE THREAD

**Issue by andycraig** [microsoft/vscode#98888]
It would be good if extensions could know whether a new terminal was created by another extension.

The motivating case for this is when using both Python and R. The Python extension sends Python environment activation code to newly created terminals, but if the terminal was created by an R extension this results in a confusing error for the user. I raised this as an issue at the Python extension repo https://github.com/microsoft/vscode-python/issues/11963 but was told that VS Code doesn't provide any way for an extension to know if a terminal was created by another extension https://github.com/microsoft/vscode-python/issues/11963#issuecomment-634885773

Here is the Python environment activation code that appears in the R terminal, and the R error message that results:

```
> source /home/[LOCATION]/python-R-test/env/bin/activate
Error: object 'home' not found
```

Thank you.

**Comment by Tyriar** [comment]
Out of scope as there's a solution to this that the Python extension has yet to support https://github.com/microsoft/vscode-python/issues/11963#issuecomment-638233225.
