### ISSUE TITLE
Add buttons for filtering and sorting when searching for extensions

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode#98883]
Tried searching for existing issues but couldn't find any, so my apologies if this is a duplicate.

![image](https://user-images.githubusercontent.com/12476526/83343945-b359ab80-a2b5-11ea-81b5-1f4c9b33d041.png)

Using the above image as reference:

I think that it would be a very useful to have dedicated buttons for applying filters, and for applying different sorting to the Extension Marketplace search view. I believe it would be a good addition for a few reasons:

1. Give these features more discoverable to new (and old) users.
2. Much quicker and easier access than clicking the "3 dot" button and then visually searching through the long list of very visually similar looking options.
3. This would be a good place to also add a "clear filters/sorting" button.

Thanks! 😊

**Comment by sandy081** [comment]
Filter and Sort actions are now grouped under a dedicated Filter button.
