### ISSUE TITLE
VScode should integrate with git/NPM/php install in WSL in launch without distro

### ISSUE THREAD

**Issue by darkRaspberry** [microsoft/vscode#98898]
VScode should integrate npm or git or php which are installed in WSL environment. 
When vscode is launched using wsl it work fine. But when it is launched using windows. It fails to integrate. 
Like my vscode setting look like this.
`    "git.path": "\\\\wsl$\\Ubuntu\\usr\\bin\\git",`
`    "typescript.npm": "\\\\wsl$\\Ubuntu\\usr\\bin\\npm"`
Now the vscode doesn't read this

Most important my vscode lauched in windows environment without using distro.
When using distro it works seemlessly good.

**Comment by egamma** [comment]
/needsMoreInfo have you tried using this extension https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl.

**Comment by darkRaspberry** [comment]
@egamma when i use Remote-WSL it works.
Meaning when i launch the vscode using distro(wsl).
The integration is automatic and it works fine.

when launching the vscode is windows environment it fails to integrate to wsl installed apps.

**Comment by egamma** [comment]
@darkRaspberry glad to hear that it works for you. We have implemented the Remote-WSL extension for this purpose.
