### ISSUE TITLE
Indent auto change to TAB:size 4 everytime when I open a .go file

### ISSUE THREAD

**Issue by pengyuwei** [microsoft/vscode#98894]
Issue Type: <b>Bug</b>

I want to use space instead TAB，but every time when I open a .go file,
Indent auto change to TAB:size 4

my setting：

```
"editor.insertSpaces": true
"editor.tabSize": 2
"editor.detectIndentation": false
```

Only .go file has this problem, if I open other file, it will be use space, why?

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz (8 x 1100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
Go|ms-|0.14.3

</details>

**Comment by egamma** [comment]
Since this only happens with .go file report the issue against the Go extension.

**Comment by pengyuwei** [comment]
Refer to the above issue to solve the problem：

```
"[go]": {
    "editor.tabSize": 2,
    "editor.insertSpaces": true
}
```
