### ISSUE TITLE
Auto detect Git installation from GithubDesktop

### ISSUE THREAD

**Issue by shivapoudel** [microsoft/vscode#98896]
Since I already have a WSL setup, I don't prefer installing Git for Windows and just GitHub Desktop works fine for me. Thus can VSCode detect essential needs for Git from it as I received this.

```node
Looking for git in: C:\Program Files\Git\cmd\git.exe
Looking for git in: C:\Program Files (x86)\Git\cmd\git.exe
Looking for git in: C:\Program Files\Git\cmd\git.exe
Looking for git in: C:\Users\shiva\AppData\Local\Programs\Git\cmd\git.exe
Git installation not found.
```

**Comment by DevFlamur** [comment]
I like this @vscodebot[bot] ! question here is if @shivapoudel has 2FA enabled? if yes then the workaround is to enter the 'some other value #94967' instead of the github password.
if no then it' some other issue

**Comment by joaomoreno** [comment]
Sorry, but VS Code only support Git for Windows on Windows platforms. Or `git` from WSL, when opening WSL Remote.

**Comment by shivapoudel** [comment]
@joaomoreno If WSL2 is set up and integrated terminal is set to WSL then when running VSCode in normal mode (not in remote) should also support git from WSL. If the terminal is supporting WSL then there should be an explorer/window setting to use VCS from WSL or auto-detect.

Is this planned elsewhere or not but what the mean of WSL if we need to install all the infrastructure in both the Windows environment and WSL environment?

**Comment by joaomoreno** [comment]
>  If WSL2 is set up and integrated terminal is set to WSL then when running VSCode in normal mode (not in remote) should also support git from WSL

We don't do this since it will provide **abysmal** performance. This is very much not recommended.

"All the infrastructure": it's just Git for Windows, a simple installation.
