### ISSUE TITLE
split file right/left/down/up

### ISSUE THREAD

**Issue by ZhengAu** [microsoft/vscode#98895]
When I split the file right/left/down/up, the file will open in group 2, it is good; but if the current file can close in group 1, it will be perfect.
The file I don't know is opened in the group 2, when I click the file in Side Bar, if the cursor don't in group 2, it will open again in the current group. If when I click the file whick is opened in a group, please locate to the group.

**Comment by egamma** [comment]
/needsMoreInfo Can you please illustrate the desired behaviour with some screenshots.

**Comment by ZhengAu** [comment]
![image2020.05.31.png](https://github.com/ZhengAu/myImage/blob/master/image2020.05.31.png)

**Comment by ZhengAu** [comment]
For example, I split *test2.js* to right, and I hope *test2.js* on the left group can closed.

![image2020 05 31](https://user-images.githubusercontent.com/26664115/83354321-81664900-a38a-11ea-9e7d-f5e17b65a4b0.png)

On the other hand, when the file *test2.js* is just opened on the right and the cursor is on the left group, and I click the file through the SideBar, the file *test2.js* will open again in the left group. And I hope the cursor can locate to the file *test2.js* that I have opened.

**Comment by bpasero** [comment]
@ZhengAu so instead of splitting you want to move the editor to the second group?

**Comment by ZhengAu** [comment]
@bpasero YEAH!! split and move right

**Comment by bpasero** [comment]
Why is this not working?

![image](https://user-images.githubusercontent.com/900690/83405858-bd8ebd80-a40d-11ea-95cc-c8bce25b1b33.png)

**Comment by ZhengAu** [comment]
**ooh, sorry. I donot use it before. Thanks for that.**

Other problem, if the file is opened in the second group and the cursor is in the first group, actually I donot know it is opened in the second group, when I click this file through Sidebar, it will open again in the first group. And I think the cursor can locate to the file will be perfect.

**Comment by bpasero** [comment]
Maybe try with `"workbench.editor.revealIfOpen": true` in settings.
