### ISSUE TITLE
vs code become colourful in my ubuntu laptop.

### ISSUE THREAD

**Issue by uday169** [microsoft/vscode#98899]
VS Code become coloruful in my ubuntu laptop, I remove it and reinstall several times but it remains same..please help me to solve it.
![Screenshot from 2020-05-31 13-04-19](https://user-images.githubusercontent.com/31014665/83349930-fc613c80-a355-11ea-80a1-14d00be4e8e1.png)

**Comment by egamma** [comment]
@uday have you switched a theme by accident. Does this reproduce when you run code with clear user settings `code --user-data-dir some_temp_dir`.

Can you reproduce the problem when you install the VS Code insider version https://code.visualstudio.com/insiders/?

**Comment by uday169** [comment]
Thanks for replying @egamma , I haven't switched any theme. I cleared all the vs code related file and reinstall vs code but it not solve the problem. And I also installed the **vs code insider**  but problem remain same there also.

**Comment by egamma** [comment]
@uday169 you have closed the issue, does this mean you could resolve the issue? How could you resolve the issue.

**Comment by uday169** [comment]
@egamma Actually I upgarded my ubuntu os, at that time it was some graphic issue there..perhaps it affected the vs code.. so I reinstalled the os and it resolve my vs code issue.

**Comment by egamma** [comment]
@uday169 thanks for the info and glad it is now working for you.
