### ISSUE TITLE
Markdown: Allow to open files inside the editor that are linked from the markdown

### ISSUE THREAD

**Issue by Enet4** [Microsoft/vscode#989]
The current behaviour of Code's Markdown previewer when clicking a relative link is actually a bit cryptic: it attempts to open the file relative to the user's home path with the system's application of choice. This will commonly lead to errors being dispatched because the file cannot be found.

If I have the following Markdown:

```
The data types are documented [here](typings/foo.d.ts).
```

Clicking the link will make my system attempt to open `/home/username/typings/foo.d.ts`.

Given that even [GitHub supports relative links to project files](https://help.github.com/articles/relative-links-in-readmes/), I strongly believe that they should be supported here. Such links should instead be relative to the markdown file's directory and open the linked file using the Code editor.

**Comment by RWeigelt** [comment]
+1; opening markdown files by clicking a (relative) link in the preview would be a very powerful feature both for *writing* developer documentation (split into individual files by topic) for a project, but also for *viewing* that documentation.

**Comment by noahleigh** [comment]
Related: [The markdown-it library that vscode uses stops file:// links from being being built.](https://github.com/markdown-it/markdown-it/issues/294)

Is this behavior something vscode could change for its markdown preview?
