### ISSUE TITLE
Test 'CSS Language Features extension' in web

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#98900]
https://github.com/microsoft/vscode/issues/97701

- [x] anyOS: @Tyriar Chrome
- [x] macOS: @isidorn Safari
- [x] anyOS @joaomoreno Firefox

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%2398900%0A%0A)

---

- From the VSCode sources, run `yarn web` and open http://localhost:8080 in the browser
- open the 'css' file and verify that rich css/less/scss language features work
See https://code.visualstudio.com/docs/languages/css for more info
- validation
- code completion
- code completion for paths (e.g. `background: url(^)`)
- hovers, for properties, and selectors
- color decorators
- css settings
- links
- custom data from settings (see https://github.com/Microsoft/vscode-css-languageservice/blob/master/docs/customData.md)

**Comment by isidorn** [comment]
@aeschli I am sort of blocked for testing this on Safari, since nothing seems to work
https://github.com/microsoft/vscode/issues/99049
