### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Aditya060806** [microsoft/vscode#98907]
Issue Type: <b>Bug</b>

i have installed vs code in my laptop one or two days a ago 
but now i am not able to get the run button on the right corner and also  when i am trying to open a folder it is not opening ..please help!!!

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz (4 x 1190)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.78GB (3.17GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.5.80290

</details>

**Comment by mxrachel** [comment]
Could you please post a screenshot or gif showing the problem. Also, does this happen when you reload with all extensions disabled? Press <kbd>F1</kbd> then select ```Developer: Reload with Extentions Disabled```.
