### ISSUE TITLE
workbench.files.action.showActiveFileInExplorer no longer works

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9890]
- VSCode Version: Code - Insiders 1.4.0-insider (6ef86d5f85a531caa59bfb1715469fcfaa8d2efd, 2016-07-28T07:20:25.358Z)
- OS Version: Linux x64 4.4.0-28-generic, Ubuntu 16.04

I bind `workbench.files.action.showActiveFileInExplorer` to ctrl+0 and it seems to have stopped working a couple of days ago.

**Comment by jrieken** [comment]
@Tyriar Not so sure about that. I have the same command bound (in combination with `"explorer.autoReveal": false`) and it still works for me

**Comment by isidorn** [comment]
@Tyriar works for me on the mac, both via custom keybinding and command pallete

**Comment by Tyriar** [comment]
It seems to be working now, closing until I see the issue again.
