### ISSUE TITLE
Text of current find match text is not visible in markdown file

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#9891]
- VSCode Version: 1.4.0 insiders (6ef86d5f85a531caa59bfb1715469fcfaa8d2efd)
- OS Version: OSX

Steps to Reproduce:
1. Open a markdown file that has following content:

`<p align="center">`
1. Find for `align`

Observed:
When current match is in above line, text of the match is barely visible

![screen shot 2016-07-28 at 12 41 31 pm](https://cloud.githubusercontent.com/assets/10746682/17210041/a4332196-54c0-11e6-9faa-3ae9c25d14e2.png)

**Comment by kieferrm** [comment]
There are other examples like this:

![screen shot 2016-07-28 at 12 03 30 pm](https://cloud.githubusercontent.com/assets/4674940/17225848/69d5ead8-54bb-11e6-903c-1e4a9cef77b2.png)

The general issue is the overlay of the editor background, the syntax highlighting, the line highlight, and the current-match highlight produce low contrast situations. In these situation the text color should automatically be adapted to produce higher contrast.

**Comment by alexandrudima** [comment]
IMHO this bug can only be fixed once we use the theme service and the theme colors to compute all the colors we end up rendering. Today, the color of the text and the color of the background comes from the theme, while the find highlight color comes from our own css and is the same regardless of chosen theme.

**Comment by sandy081** [comment]
With #11095 we exposed some of the colors as custom TM theme settings. This will let theme authors to provide a proper find highlight color.

We still have to do the same for our out of the box themes.

@bgashler1 FYI

**Comment by alexandrudima** [comment]
This can now be customized by each theme and by each user to their liking. There is no work planned.

This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
