### ISSUE TITLE
Digit grouping symbol to match system setting

### ISSUE THREAD

**Issue by AlsoScratch** [microsoft/vscode#98911]
I learned that comma is technically the wrong symbol to use for digit grouping. It should always be a space. Fortunately, Windows and macOS have the option to change it.

I wish it was possible for VSCode's displaying of numbers to follow my system's language & region settings and not be forced with commas.

<img width="257" alt="Screenshot 2020-05-31 at 11 59 45 PM" src="https://user-images.githubusercontent.com/48752273/83356787-f5a8e880-a39a-11ea-972e-f7730816f8f1.png">

**Comment by AlsoScratch** [comment]
I'm from Singapore

**Comment by sandy081** [comment]
I think we generate this string based on the VS Code locale hence It changes as per the locale. Not sure if we want to change it as per OS setting.

**Comment by AlsoScratch** [comment]
It is possible to change the symbol manually?

**Comment by sandy081** [comment]
Unfortunately you cannot.
