### ISSUE TITLE
Crtl + lshift + p does not work, Crtl + rshift + p does

### ISSUE THREAD

**Issue by memphiscodered** [microsoft/vscode#98915]
I can not open the command pallette anymore by using ctrl + lshift + p.
After some time I tried to fix it in the key binding settings, but it turns out the 'p' key is not recognized when holding ctrl + lshift. All other keys worked, and when using rshift insted 'p' also worked (I also tried different keyboards).
As of now I can only open my command pallette via ctrl + rshift + p, but it just feels wrong as I am so used to do it with lshift.

Edit:
For some reason it works with my new keyboard again (just arrived).

**Comment by egamma** [comment]
/needsMoreInfo can you please follow this guide to narrow down a keyboard problem https://github.com/microsoft/vscode/wiki/Keybinding-Issues
