### ISSUE TITLE
Blank White, Black, Or Transparent VS Code Window

### ISSUE THREAD

**Issue by n-gineer** [microsoft/vscode#98916]
Version of VS Code: 
   x64 1.45.1
Your operating system:
   Windows 10 Pro x64 Version 1909, Build 18363.836
List of extensions that you have installed:
   jumpinjackie.vscode-map-preview-0.5.2
   ms-python.python-2020.5.80290
   ms-vscode.cpptools-0.28.1
   ms-vscode.powershell-2020.4.0
   ms-vscode-remote.remote-wsl-0.44.2
   tomoki1207.pdf-0.6.0
Reproducible steps (1... 2... 3...) that cause the issue
1. opening vs code from start menu, cmd, windows subsystem for linux command line, or open with context command.
What you expected to see, versus what you actually saw
   expected normal vs code window, get blank windows instead (sometimes white, sometimes black, sometimes transparent)
Images, animations, or a link to a video showing the issue occurring
![image](https://user-images.githubusercontent.com/20650428/83359520-af2a9e00-a348-11ea-969d-b6f6e2add18e.png)

(notice the transparent window over my issue draft in the picture)

A code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally
   N/A
Errors from the Dev Tools Console (open from the menu: Help > Toggle Developer Tools)
   N/A can't access

Attempted troubleshooting:
The closest issue I found was #66340. I reinstalled over existing, no effect. I uninstalled and reinstalled, no effect. I tried running with --disable-gpu, no effect.

Most recent system change:
Installed [KB4497165: Intel microcode updates](https://support.microsoft.com/en-us/help/4497165/kb4497165-intel-microcode-updates)

**Comment by n-gineer** [comment]
At one point, I left a transparent vs code window open for multiple hours without thinking about it, and it eventually opened completely. I haven't had any problems since. I'm not sure if I should mark as closed or not. Let me know if I can provide any additional information or troubleshooting.

**Comment by deepak1556** [comment]
@n-gineer does this issue still happen with latest stable or insiders version ?

**Comment by n-gineer** [comment]
After leaving a blank window open for multiple hours (mentioned above), it has not given me any more problems after the June 1st release. I just installed Insiders and it didn't give me any trouble on startup either.

**Comment by deepak1556** [comment]
Thanks @n-gineer , closing this issue. Can reopen if the issue happens again.

**Comment by n-gineer** [comment]
Understood, thanks!
