### ISSUE TITLE
Click hierarchy -> double, triple, quadruple, etc

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/vscode#98917]
Right now, clicking works as follows:
Double Click: Selects word based on the boundaries in the config.
Triple Click: Selects the whole line.

I would like to alter this behaviour so triple click selects within different bounds. Quadruple click then selects the entire line.

e.g.:

string line = "some text in here";
double click on text:
string line = "some **text** in here";
triple click:
string line = "**some text in here**";
quadruple click:
**string line = "some text in here";**

Ideally, this would be extensible, so if others want to use even more clicks, they can. I work in a domain with many field identifiers that may be multiple words separated by a space. This means selecting them becomes a very manual effort. While I am mostly a keyboard user, I find myself using my mouse a lot while doing refactoring or initial bug exploration.

**Comment by alexdima** [comment]
Let's track in #3130

**Comment by mjmatthiesen** [comment]
Based on that thread, this isn't really a duplicate at all, but ok then.

**Comment by alexdima** [comment]
@mjmatthiesen You would like that triple click is no longer bound to selecting the entire line, but it is bound to another yet to be written command which selects things according to some rules. There are two steps to achieve that:
1. rebind triple click to be the new command - this is #3130
2. implement the new command - there is nothing blocking this and can be written from an extension
