### ISSUE TITLE
Disconnect when I using Notebook Editor

### ISSUE THREAD

**Issue by HaoHoo** [microsoft/vscode#98928]
When I try to using Notebook Editor to open .ipynb file, the VS codespace can't open it in edit tab and unstable. Then the browser page prompt me reconnect session or reload window.

**Comment by egamma** [comment]
Please report the issue with more detailed steps against the python extension.

**Comment by HaoHoo** [comment]
Hi Erich, Thanks for your reply. I have tested this in some different networking. It may be issued by poor network connection ( I connect from China mainland...). Just as ref.: After I install python modules by this command line:
pip install jupyter notebook --user
and re-connect from another network. The .ipynb file is work fine now.
