### ISSUE TITLE
Extension Host in vscode v1.45.1 is seriously broken. It even makes other apps crash.

### ISSUE THREAD

**Issue by aleksey-hoffman** [microsoft/vscode#98922]
- VSCode Version: 1.45.1
- OS Version: Windows 10

## Steps to Reproduce:

1. Install 1.45.1
2. Open multiple vscode windows 
3. Open multiple other apps after that
4. See how some of them crash / become unresponsive / display glitches

I assume all of this is related to vscode 1.45.1, and specifically (maybe?) to the extension host, because after I first launched 1.45.1:

- vscode started showing me `extension host` related errors
- when I open vscode with `code --disable-extensions`  the problem goes away.
- when vscode v1.45.1 is closed I don't see any problems, and as soon as I open it, other apps start crashing or become unresponsive in the first few seconds / minutes. 
- the previous versions of vscode didn't cause any troubles, and after I rolled back to 1.44 everything is fine now.

I think it might be something GPU related, but I don't know, I don't have any debug data.

On the first launch after the update, it showed me an error, saying extension host crashed. I didn't give it much thought, clicked reload, and kept using it. But then it got worse, after using vscode for a bit, I noticed Chrome browser has crashed. Not too weird, reloaded it, kept using it but it kept getting unresponsive. Then I got back to developing my Electron app, I served the dev version, but for some reason it kept crashing as well, and if it wasn't crashing, all of its windows were getting completely blacked out. And it wasn't crashing only Electron / Chromium based apps, many other apps were crashing soon after launch. I even opened a game and it crashed as soon as it loaded (presumably because it couldn't use GPU properly). Then something important crashed and all windows of all opened apps got black / unresponsive. I reloaded GPU drivers with `CTRL + SHIFT + WIN + B` and restarted both integrated and dedicated GPUs but it didn't help, OS became unusable and I had to restart it. After that I opened all the apps and everything worked fine, until I opened vscode.

I have the following extensions installed. But I really doubt any of them can cause such an issue by themsleves. I think it's caused by the extensions host itself:
```
arcticicestudio.nord-visual-studio-code
ms-python.python
octref.vetur
ritwickdey.LiveServer
sdras.vue-vscode-snippets
whizkydee.material-palenight-theme
xabikos.JavaScriptSnippets
zhuangtongfa.material-theme
```

## Does this issue occur when all extensions are disabled?: No

**Comment by aleksey-hoffman** [comment]
The causal chain is more complex than I thought. I'm not sure if it's vscode fault anymore. It seems the decribed issues occur only when the latest Chrome (83.0.4103.61) is opened.

**Comment by YazeedAlKhalaf** [comment]
The problem still occurs, please reopen
