### ISSUE TITLE
Windows Integration Tests: slow vscode.github warning on startup

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98931]
When I start the integration tests on my Windows VM I am often greeted with this:

`UNRESPONSIVE extension host, 'vscode.github' took 100% of 5756ms, saved PROFILE here: 'C:\Users\bpasero\AppData\Local\Temp\exthost-f23212.cpuprofile' [ { id: 'vscode.github', total: 5756000, percentage: 100 } ]`

Looks like there is a `windowsRelease` module somewhere in Git that spawns sync to find out the OS release?

![image](https://user-images.githubusercontent.com/900690/83379748-94a20480-a3dc-11ea-944c-13ed398cc919.png)

[profiles.zip](https://github.com/microsoft/vscode/files/4709604/profiles.zip)

**Comment by joaomoreno** [comment]
This seems to be related to octokit. @RMacfarlane have you seen this in GHPR?

**Comment by joaomoreno** [comment]
OMG there's a couple `sync` spawns just to get a user agent:

https://github.com/gr2m/universal-user-agent/blob/master/src/node.ts#L5
https://github.com/sindresorhus/windows-release/blob/master/index.js#L37

🤦‍♂️ 

Yup, GHPR avoids this with https://github.com/microsoft/vscode-pull-request-github/blob/c94ce87cc2f66d372d891ab19052b54f31ae6146/src/github/credentials.ts#L172

So we'll do the same here.

**Comment by joaomoreno** [comment]
There is no easy fix here other than forking or ditching Octokit.

**Comment by joaomoreno** [comment]
Let's see what they say https://github.com/octokit/rest.js/issues/1781

**Comment by joaomoreno** [comment]
This is really ugly:

![image](https://user-images.githubusercontent.com/22350/87662428-7dd42900-c762-11ea-8426-4c53f8c89800.png)

I'm still waiting on the upstream fix, but for now I just delay calling `require('@octokit/rest'`) and took it out of the activation path.

**Comment by bpasero** [comment]
Thanks, though the upstream fix is really needed because a `spawnSync` will hold the entire process

**Comment by joaomoreno** [comment]
And this is multiple spawn syncs.

**Comment by joaomoreno** [comment]
This was just fixed upstream: https://github.com/octokit/rest.js/issues/1781, thanks again @gr2m

Created follow-up issues:

- https://github.com/microsoft/vscode/issues/102759
- https://github.com/microsoft/vscode-pull-request-github/issues/2008
