### ISSUE TITLE
Background image for vscode

### ISSUE THREAD

**Issue by luisiacc** [microsoft/vscode#98933]
I would like to have a background image in vscode that does not have any problems with the selected color scheme, it would be just like the option that Jetbrains programs has on the Appeareance section(where it can be set a custom image, opacity, among other things), the background would not be just in the editor, but in the whole ui, including the menu and the gutter with the line numbers. Currently there are some extensions that allow to put a background image to the editor only, and there are pretty buggy and use hacky ways to get it done. That's it, I hope this can be done, I espect it wont be hard.
Could be done by example:
```
"window.backgroundStyle": {
   "background": pathh/to/img 
   "opacity": 0.2
}
```

**Comment by luisiacc** [comment]
I think there are a lot of developers who will like this feature since the background library (the one I speak above) has over 100k downloads, if this was built in I imagine more devs would be interested.

**Comment by langyo** [comment]
Now, many developers use the plugin in the community to modify the background.However, the way to modify is to directly modify the core webpage.That's not elegant.

🤔

**Comment by luisiacc** [comment]
> Now, many developers use the plugin in the community to modify the background. However, the way to modify is to directly modify the core webpage. That's not elegant.
> 
> 🤔

Exactly, it also only modifies the editor and not the rest of the UI, this is a very cool feature to have
