### ISSUE TITLE
Failed to continue: "Cannot find Delve debugger. Ensure it is in your `GOPATH/bin` or `PATH`."

### ISSUE THREAD

**Issue by ZhaiKunGitHub** [Microsoft/vscode#9893]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 
2.

**Comment by kieferrm** [comment]
@ZhaiKunGitHub pls file your issue with concrete steps to reproduce the problem in the [Go extension's repo](https://github.com/Microsoft/vscode-go/issues). Thanks!
