### ISSUE TITLE
ExtUri#isEqual does not account for drive letter casing

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98934]
As seen in our emmet tests [1], it looks like the newly introduced `ExtUri#isEqual` method fails over drive letter casing. Took me a long long time to figure this out because `URI#toString()` always seems to be returning the drive letter lowercase, while `URI.path` does not.

[1] https://dev.azure.com/vscode/VSCode/_build/results?buildId=44775&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=d494b5db-eef8-5766-984e-01186010c86f

Trying a workaround with https://github.com/microsoft/vscode/commit/bd84bb37866e789a66bf64c2f1956386fd5e1894

**Comment by bpasero** [comment]
Merging this in optimistically since tests seem to be green, but please revisit that solution.

**Comment by jrieken** [comment]
Thanks @bpasero

**Comment by jrieken** [comment]
The same happens with compare
