### ISSUE TITLE
duplicate definitions with "go to definition" when using CommonJS require

### ISSUE THREAD

**Issue by bbukaty** [microsoft/vscode#98930]
Issue Type: <b>Bug</b>

When using the "go to definition" command on a javascript function imported with `require`, multiple identical definitions are shown which results in a 'peek' instead of jumping to the definition in the other file.  
I disabled all extensions and created two minimal javascript files which demonstrate this. See image below:

![Annotation 2020-05-31 223931](https://user-images.githubusercontent.com/19913542/83379122-a1e4d200-a38f-11ea-9d14-a9f325fa96e8.png)
When I select the second definition, nothing changes. The filename and function that are displayed are identical. Here's a screenshot anyway:
![Annotation 2020-05-31 224352](https://user-images.githubusercontent.com/19913542/83379383-3c451580-a390-11ea-9622-d90e9d308f32.png)

### index.js
```
const importedFoo = require('./fooFile');

importedFoo.foo(4);
```
### fooFile.js
```
exports.foo = function (x) {
    return x + 5;
}
```

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (12 x 3498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (8.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Should already be fixed in VS Code insiders (which includes TypeScript 3.9)
