### ISSUE TITLE
Colours Washed Out 1.45.1 over RDP

### ISSUE THREAD

**Issue by Anatosuchus** [microsoft/vscode#98943]
Issue Type: <b>Bug</b>

My UI colours have become completely washed out to the point of syntax highlighting being almost unusable over the last 48 hours (presumably coinciding with most recent update). If I start code on my machine and RDP in AFTER starting, colours are fine. If I start code over RDP they are washed out.

Steps to reproduce: Open VS Code on machine via RDP connection, try to read code.
Expected results: Text and highlighting usefully contrasting
Actual results: Text faint and syntax highlighting useless

I have tried the fixes in various bug reports (command line options, changes to configuration json), my machine only has sRGP colour profile set up. This is across all windows/frames.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
csharp|ms-|1.22.0
mssql|ms-|1.9.0
python|ms-|2020.5.80290
remote-wsl|ms-|0.44.2
powershell|ms-|2020.4.0

</details>
our clipboard because it was too large to send. Please paste.

**Comment by Anatosuchus** [comment]
Found this is to do with the particular colour mode used for the RDP connection. Dropping from GFX to older TrueColor settings has fixed the profile detection.

**Comment by egamma** [comment]
Great that you have found a solution.
