### ISSUE TITLE
Hover is not appearing on a variable sometimes

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#9894]
- VSCode Version: 1.4.0 insiders (6ef86d5f85a531caa59bfb1715469fcfaa8d2efd)
- OS Version: OSX

![screen shot 2016-07-28 at 2 23 46 pm](https://cloud.githubusercontent.com/assets/10746682/17212344/f0722030-54ce-11e6-887b-d66b964429f5.png)

Hover on `window` property is not shown, but it is shown if vs.window... is on a new line

**Comment by isidorn** [comment]
There is a PR in progress which we plan for August which will hopefully tackle this issue #9821

**Comment by isidorn** [comment]
This got fixes as parst of 1a2701b
