### ISSUE TITLE
Cannot remote debug Python through SSH

### ISSUE THREAD

**Issue by lfdmn** [microsoft/vscode#98944]
- VSCode Version: 1.45.1
- OS Version: LinuxMint 19.3 (Ubuntu 18)
- remote device OS: poky linux running on Jetson Xavier

Steps to Reproduce:

1. Remote device is at IP 192.168.1.100
2. Python3 installed in /usr/bin/python3, pip packages installed in /usr/lib/python3.7/
3. python-debugpy_1.0.0b9 installed
4. vs code can connect to the device
5. created a  test.py file with 
```python
#!/usr/bin/python3
print ('hello')
```
6. hit F5 and select 'Python: Current file'
7. error window opens with message:
```
You need to select a Python interpreter before you startdebugging. Tip: click in "Select Python Interpreter" in the status bar

Source: Python (Extension)
```
8. click "Select Python Interpreter" > Enter Interpreter path... > Find
9. Enter /usr/bin/python3
10. Press Debug
11. Loops back to 7 indefinitely

Does this issue occur when all extensions are disabled?: Can't test, I need the extension

**Comment by egamma** [comment]
Please report the issue against the Python extension.
