### ISSUE TITLE
Feature request - Clear button of search panel should clear everything

### ISSUE THREAD

**Issue by MrChocolatine** [microsoft/vscode#98942]
The clear button of the search panel should clear everything, all the inputs, and not only the search results + the "search" input.

We still need to manually clear some inputs after clicking the clear button :

![vscode-searc-clear](https://user-images.githubusercontent.com/47531779/83393150-367e1d00-a3ee-11ea-9161-5f5c1cf18564.gif)

**Comment by timothycobrien** [comment]
Could I take a look at this? It'd be my first contribution to VSCode.

**Comment by roblourens** [comment]
Sure

**Comment by gjsjohnmurray** [comment]
Isn't there a risk of upsetting users who rely on the current behaviour? Perhaps a second click on the button should be what clears the other fields.

**Comment by MrChocolatine** [comment]
> Isn't there a risk of upsetting users who rely on the current behaviour? Perhaps a second click on the button should be what clears the other fields.

Why among all the search inputs only some of them should be cleared? Those users are used to something that, by nature, should not work like this.

**Comment by roblourens** [comment]
Hm, I dunno, thanks for mentioning that point @gjsjohnmurray. I can see a case where people are always searching in the same folder, they just want to clear out the query/results. You could argue, why should it change the folder you search in when it doesn't also say, reset the "case sensitive" search option?

Maybe ideally there would be a "reset everything" button and a "clear search results" button. I really don't want two buttons.

**Comment by tabaddor** [comment]
I'd like to look into this issue. Is there any other information I should know? 

Though it does make sense for this to clear all search inputs, maybe down the road it allows users to specify which input they wish to clear, along with the option of clearing all.

**Comment by roblourens** [comment]
@timothycobrien already asked, however I don't think it's ready to work on since I am not yet sure which direction we would actually want to go with it.

**Comment by roblourens** [comment]
I explained what I'm thinking above. @JacksonKearl what do you think?

**Comment by JacksonKearl** [comment]
I agree that we shouldn't change existing behaviour. I think making the clear button clear-all when the relevant fields (query, replacement, results) are blank makes good sense.

**Comment by roblourens** [comment]
Yeah a 2 step process could be cool

**Comment by JacksonKearl** [comment]
We have 2-stage buttons elsewhere in the product too, such as in that same action bar we collapse file results then workspace folder results in two stages.

**Comment by IllusionMH** [comment]
+1 for 2-stage clear.

I always have _files to include/exclude_ filled e.g. `*.js`/`3p, *.svg, *Test.java` but clear results or change query very often.
Navigating to each field and restoring it's value after Clear wound be painful.

---

However 2-stage buttons have problem with discoverability - having different icon/title or even title would be helpful.

**Comment by roblourens** [comment]
Yeah, I would take a PR that adds a 2-stage clear

**Comment by tabaddor** [comment]
Does #100024 resolve the issue?

**Comment by edjeffreys** [comment]
@tabaddor #100024 will clear the search & replace fields first on clicking clear (if there are values present) and then will clear the pattern filters if the search & replace fields are clear.

So I believe this does resolve the issue.
