### ISSUE TITLE
Folder-Specific Keymaps

### ISSUE THREAD

**Issue by SSead** [microsoft/vscode#98949]
VS Code has a great implementation of keyboard shortcuts. However, I think it could be improved further. It would be awesome to be able to create folder/project specific hotkeys. This can be implemented in a similar way to user snippet files.

Example:
You want a key combination (Ctrl+Shift+R) to run your program. In a C++ project, you can set that shortcut to compile and run your code. But in a node-js project, it could run 'npm start'.

The possibilities are endless!

**Comment by alexdima** [comment]
@SSead This is possible via an extension. An extension can set a context key depending on the current opened folder via the `setContext` command ([example](https://github.com/microsoft/vscode-extension-samples/blob/1c9a14f3e481d8fbfeec4a645e476bbaf8333d7a/vim-sample/src/extension.ts#L233-L248)) and then keybindings can be written based on that custom context key.

**Comment by SSead** [comment]
Thanks for the reply @alexdima! I'll try to create and publish an extension that implements this.
