### ISSUE TITLE
Redo cell insert holds reference to disposed model instance

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#98940]
This is a follow-up from #98750

* Create new cell
* Type 1
* Delete the cell
* Create new cell
* Type 2
* Delete the cell
* Undo x 6
* Redo x 1

![Kapture 2020-06-01 at 10 09 18](https://user-images.githubusercontent.com/5047891/83389274-3a12a380-a3f0-11ea-90df-60b80bb89cb3.gif)

**Comment by rebornix** [comment]
Already fixed in Insiders now.
