### ISSUE TITLE
GIT Commit messages

### ISSUE THREAD

**Issue by byvinx** [Microsoft/vscode#9895]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

I suggest the use of a combobox for selecting from a list of message used for the previous commit in GIT

**Comment by joaomoreno** [comment]
#6190
