### ISSUE TITLE
My vs code stoped working..

### ISSUE THREAD

**Issue by ketanAggarwal58** [microsoft/vscode#98957]
VS Code recently stop working and showing the error

Error: could not open `C:\user\owner name ' 

I have tried every thing including reinstalling my vs code but still nothing, so far.

The language I am using is java and I have installed the all the basic extensions which are provided by the microsoft. 

My programs are working on command prompt but not in the terminal of the vs code and i have also replaced my jdk due to this and tried to reinstall the vs code but the error is still their

**Comment by deepakkumargs-cloud** [comment]
I have basically the same issue. 
Microsoft Windows [Version 10.0.19041.264]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\Deepak Kumar\Desktop\Java> "c:\Users\Deepak Kumar\.vscode\extensions\vscjava.vscode-java-debug-0.26.0\scripts\launcher.bat" "C:\Program 
Files\Java\jdk-14.0.1\bin\java.exe" --enable-preview -Dfile.encoding=UTF-8 @C:\Users\Deepak Kumar\AppData\Local\Temp\cp_cqgq09d9thyv5bgmq5xga7hr.argfile Addition 
Error: could not open `C:\Users\Deepak'

C:\Users\Deepak Kumar\Desktop\Java>

**Comment by deepakkumargs-cloud** [comment]
This is the complete error showing here if i am trying to run my program

**Comment by cwgreene** [comment]
The issue appears to be spaces in the file path leading to the code.cmd; There may have been a breaking change in powershell.

**Comment by cwgreene** [comment]
```
C:\Users\Chris\AppData\Local\Programs\Microsoft : The term 'C:\Users\Chris\AppData\Local\Programs\Microsoft' is not
recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if
a path was included, verify that the path is correct and try again.
At line:1 char:1
+ C:\Users\Chris\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Chris\...grams\Microsoft:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by cwgreene** [comment]
Ah, I found the issue for me at least:
```
echo $env:ComSpec
```
had been set to powershell.exe. It appears to need to be `C:\Windows\System32\cmd.exe`

**Comment by egamma** [comment]
@ketanAggarwal58 does this https://github.com/microsoft/vscode/issues/98957#issuecomment-637062952 fix your issue as well?

**Comment by ketanAggarwal58** [comment]
> @ketanAggarwal58 does this [#98957 (comment)](https://github.com/microsoft/vscode/issues/98957#issuecomment-637062952) fix your issue as well?

I have checked my path it didn't have any spaces in them and it is still showing the error
