### ISSUE TITLE
Terminal fails to load (sometimes)

### ISSUE THREAD

**Issue by MrAmericanMike** [microsoft/vscode#98952]
- VSCode Version: 1.45.1
- OS Version: Windows_NT x64 6.1.7601

Steps to Reproduce:

1. Open VSC

Does this issue occur when all extensions are disabled?: Yes/No
Haven't tested, as it happens on rare occasions anyway.

https://imgur.com/n9bPse3

**Comment by Tyriar** [comment]
This happens right after opening just a _single_ terminal? Not sleeping the computer or something after opening?

I've never seen something like this but a sure workaround would be to move to the (slower) dom renderer with this setting:

```
"terminal.integrated.rendererType": "dom"
```

**Comment by MrAmericanMike** [comment]
It happens on at launch. I haven't tested yet the "terminal.integrated.rendererType": "dom"
I bet that is on the settings.json or something like that, but I find it always hard to understand on VSC where that file is located and how to access it, a lot of tutorials mention changing settings on the json file, but VSC doesn't make it clear how to find it (Or I'm missing the way)
I could give that a try, the problem is that this happens on rare occasions, so not sure how I could test if that did anything or not.

**Comment by Tyriar** [comment]
You can search for it by key in the settings ui:

![image](https://user-images.githubusercontent.com/2193314/86972704-362d1c00-c128-11ea-902d-f108c637025f.png)
