### ISSUE TITLE
Mac os stuck in full screen mode

### ISSUE THREAD

**Issue by MoMannn** [microsoft/vscode#98954]
This is a bug that exist for at least last 5-10 versions of VS. It happens when you put VS code into full screen mode. When in full screen mode you cannot close it anymore since application bar does not show up any more when you go to the top of the screen with mouse cursor. This does not happen all the time only sometimes.

Default:
![Screenshot 2020-06-01 at 13 18 55](https://user-images.githubusercontent.com/8865298/83404389-dcd81b80-a40a-11ea-8993-1dbdbb0e3671.png)

Expected behaviour:
![Screenshot 2020-06-01 at 13 22 30](https://user-images.githubusercontent.com/8865298/83404464-fda07100-a40a-11ea-8f7a-c66346494ef6.png)

Actual behaviour:
![Screenshot 2020-06-01 at 13 22 41](https://user-images.githubusercontent.com/8865298/83404515-16108b80-a40b-11ea-81ee-caa1ca559451.png)

Another thing I noticed is that when this happens and you do an action where VS code opens a popup the popup shows for a mili second and then disappears making the VS code unusable since VS code expects a popup response you cannot provide. Bug also only happens per windows. Since I can have multiple VS code instances open and in full screen mode bit this will happen only to one.

Versions:
- VSCode Version: 1.45.1
- OS Version: mac os 10.15.4

Steps to Reproduce:
1. Put visual studio code into full screen mode (secondary monitor), only happens sometimes cannot find a pattern.

Does this issue occur when all extensions are disabled?:
Yes

**Comment by bpasero** [comment]
Can you share your settings? Do you have native fullscreen disabled?

**Comment by MoMannn** [comment]
Native full screen? This happens when using mac native full screen mode (so that it opens app up like a new desktop). 
Can you be a bit more specific exactly which setting you are interested in?

**Comment by bpasero** [comment]
I was wondering if you had `window.nativeFullScreen` configured.

**Comment by MoMannn** [comment]
Ow, its set to true. :)

**Comment by bpasero** [comment]
@MoMannn ok, so that is the default and it means the native macOS fullscreen is used. To clarify, how do you get there, simply by clicking the fullscreen button of the window?

**Comment by MoMannn** [comment]
@bpasero Yes, just as you described.

**Comment by bpasero** [comment]
OK, waiting for Deepak to comment if he ever heard of this.

**Comment by MoMannn** [comment]
I may have found a possible scenario to replicate this. So I have an external monitor and what I can do is this:
1. I have a VS code open in full screen on secondary monitor.
2. I open a new VS code on primary monitor.
3. I drag the open VS code to the secondary monitor (on top of opened full screen VS code - mac prevents you to do this with any other app)
4. Then click full screen.

![Screenshot 2020-07-16 at 13 29 12](https://user-images.githubusercontent.com/8865298/87666156-68fa9400-c768-11ea-89f4-51df615a11c3.png)

**Comment by bpasero** [comment]
It is not true that macOS prevents you to drag a window over a fullscreen one, at least not when I tried with Finder app. The second window opens fullscreen though (which is different from how VSCode behaves), but I can then minimize the second window and drag it over the fullscreen one.

I tried your steps but cannot reproduce an issue.

**Comment by MoMannn** [comment]
I cannot drag finder over fullscreen VScode. Or any other application for that mater except another vscode window. And if I drag it over like this and then go full screen the bug happens. 

I am happy do demonstrate the bug over skype/hangouts if other options fail.

**Comment by deepak1556** [comment]
@MoMannn do you still see the issue with latest stable ?

**Comment by MoMannn** [comment]
@deepak1556 No I don't believe I do :) Closing the issues for now.

**Comment by deepak1556** [comment]
thanks for confirming!

**Comment by MoMannn** [comment]
@deepak1556 Happened again today. Not sure what I did for it to happen. But in either case it is much rarer for this to happen. Do I reopen the issue?

**Comment by deepak1556** [comment]
If you have reliable repro steps, please do reopen with that info otherwise there isn't much we can do here.
