### ISSUE TITLE
"Restart Frame" button is misaligned for frames with long names

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#98964]
The "Restart Frame" button appears to never want to overlay over the name of a frame (only over the path), so for names that don't fit in the current view, the button is inaccessible (behind the scrollbar or just off the view):

![restartButton](https://user-images.githubusercontent.com/1078012/83421444-064f7200-a420-11ea-83a6-8e88a0435477.gif)

**Comment by isidorn** [comment]
@DanTup thanks for filling this. I acknowledge this issue.
We are open for PRs that fix this
Code pointer https://github.com/microsoft/vscode/blob/05e851b52978f08a7d7780feeff26a121e31c0d1/src/vs/workbench/contrib/debug/browser/media/debugViewlet.css#L138
