### ISSUE TITLE
Command palette: install extension not working

### ISSUE THREAD

**Issue by VincentDondain** [microsoft/vscode#98961]
Issue Type: <b>Bug</b>

When using the command palette and selecting "install extension" I'm being redirected to the extension marketplace UI. I think in the past I was able to install extensions straight from the command palette.

If that is the expected behavior, how do you install extensions without using the mouse with the marketplace UI?

VS Code version: Code - Insiders 1.46.0-insider (2c1871d538c64df71af4902deba47d7fa4b53f27, 2020-06-01T10:32:27.369Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz (16 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (28.14GB free)|
|Process Argv|-psn_0_925922|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.2.0
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
EditorConfig|Edi|0.15.1
vscode-yarn|gam|1.7.0
vscode-pull-request-github|Git|0.16.1
better-line-select|kai|1.1.1
csharp|ms-|1.22.0
azure-account|ms-|0.8.11
azurecli|ms-|0.5.0
vsliveshare|ms-|1.0.2236
vsonline|ms-|1.0.2268
debugger-for-chrome|msj|4.12.8
debugger-for-edge|msj|1.0.14
material-icon-theme|PKi|4.1.0
vscode-xml|red|0.11.0
vscodeintellicode|Vis|1.2.7
vscode-icons|vsc|10.1.1
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Can you please provide  more information of what command are you using? May be a screenshot or a gif would be helpful

**Comment by VincentDondain** [comment]
![install-ext](https://user-images.githubusercontent.com/7839202/83536768-ab6e5700-a4c1-11ea-9c8f-b7cba0d16eee.gif)

**Comment by VincentDondain** [comment]
Just shift + cmd + p and install extension and I'm redirected to the marketplace. I thought we could install extensions from the command palette directly with the extension ID or something.

**Comment by sandy081** [comment]
Yeah but this is not from command pallette. You have to use following syntax

- Open Quick Pick using cmd+p
- Enter `ext install name`

**Comment by VincentDondain** [comment]
Aaaaaah I see thanks, maybe a feature suggestion would be for the command palette to do that when selecting "install extension".

Maybe a new option like: "Extensions: Install Extensions (Keyboard)" and you automatically populate `ext install` in the "palette UI" (don't know how that's called).

**Comment by sandy081** [comment]
Not a big fan of showing quick pick again from quick pick.

**Comment by VincentDondain** [comment]
Isn't that what's happening if you select "Go to symbol" in the command palette? Effectively, it replaces the `>` by a `@`.
Just a suggestion though, it would improve the discoverability of `ext install` (:

**Comment by sandy081** [comment]
Actually we want to direct users to the UI which is specially built for this purpose. Doing it from command pallette is advanced feature and only few wanted to get to this from command pallette. Hence it is not a good idea.

As said quick pick actions are advanced features and these can be discovered by opening quick pick and typing `?`. 

Just checking with @bpasero if there is another way to discover them.

**Comment by VincentDondain** [comment]
Oh yes the ? does the job, thanks I have been enlightened (:
