### ISSUE TITLE
Regex bug for simple text search

### ISSUE THREAD

**Issue by dgwyer** [microsoft/vscode#98960]
- VSCode Version: 1.45.1
- OS Version: Windows 10 (10.0.18363)

Steps to Reproduce:

1.  Enter the following text in a plain text type document:

How do I love thee? Let me count the ways.
I love thee to the depth and breadth and height
My soul can reach, when feeling out of sight
For the ends of being and ideal grace.

2. Search using regex for all instances of words that have a capital letter as the first character: \b[A-Z]+[A-Za-z]*\b

3. In regexr.com matches were returned as expected but in VS Code ALL words were returned.

![VSCode_regex](https://user-images.githubusercontent.com/1482075/83417211-af469e80-a419-11ea-8dee-1e8dfd230a50.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes, it still occurs.

**Comment by connor4312** [comment]
Unless this the "match case" button is clicked, case is ignored in the regex (equivalent to the `i`) flag.

![](https://memes.peet.io/img/20-06-5d54272e-b46e-4a86-af87-1940db5506af.png)

Does this answer your question?

/needsMoreInfo

**Comment by dgwyer** [comment]
Ah, I understand. And by the same token, I assume the 'Match Whole Word' toggle is used as the word boundary in the regex when enabled?

**Comment by connor4312** [comment]
I do not believe that "match whole word" has any effect when matching by regex.

**Comment by dgwyer** [comment]
I just tried it and it worked, hence my assumption as to why it's still visible when the regex toggle is enabled.

**Comment by dgwyer** [comment]
Also, I'd prefer to see the regex option on it's own without being influenced by the match case or match word toggle icons.

It's not that intuitive to enter a case sensitive regex and have it recognized ONLY if the match case toggle is also selected.
