### ISSUE TITLE
Errors sent in response to restartFrame are not shown to user

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#98963]
This was previously raised in #87605, but the fix doesn't seem to be working for me.

I'm setting `supportsRestartFrame` during `initializeRequest`:

```ts
response.body.supportsRestartFrame = true;
```

And I'm just always returning an error in `restartFrameRequest`:

```ts
protected restartFrameRequest(response: DebugProtocol.RestartFrameResponse, args: DebugProtocol.RestartFrameArguments): void {
	response.success = false;
	response.message = `Failed to restart frame !!`;
	this.sendResponse(response);
}
```

However no message appears anywhere when trying to restart a frame:

![restartFrameRequest2](https://user-images.githubusercontent.com/1078012/83420971-4bbf6f80-a41f-11ea-8d8b-1682f4e86512.gif)

@isidorn

**Comment by isidorn** [comment]
@DanTup thanks for filling this. Now we show an error notification
