### ISSUE TITLE
Wired behavior when using Microsoft Zhuyin IME in editor

### ISSUE THREAD

**Issue by kix99aug** [microsoft/vscode#98968]
Issue Type: <b>Bug</b>

It happens when using Zhuyin IME to type chinese.
If we switch from chinese to english using shift (as default) when typing a chinese word but not complete yet , it will stuck in a wired situation where we can't type anything or cancel.

[Imgur](https://imgur.com/xklvwNw)
In the 2nd row, after I typed "ㄋㄧ", I switched from chinese to english using shift.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (10.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hant|MS-|1.45.1
python|ms-|2020.5.80290

</details>

**Comment by kix99aug** [comment]
Addition Information: This issue happens after Windows update to 2004 (20H1), which uses new version of Zhuyin IME.

**Comment by rebornix** [comment]
@kix99aug thanks for the detailed info. IMHO it's a bug with Zhuyin IME. After switching to English mode while using Zhuyin, the IME doesn't quit composition yet, so any typing after it should still emit `compositionUpdate` events, but it doesn't now.

**Comment by rebornix** [comment]
After help from friends from Zhuyin IME team, we found that it only happens in recent chromium, which affects Chrome and Electron but native applications, Firefox, legacy Edge are all fine. Reported this issue to chromium https://bugs.chromium.org/p/chromium/issues/detail?id=1091069 cc @deepak1556 , we didn't see this issue in previous electron, but not sure which one is the last good version (Teams on Windows is on a good build).

**Comment by kix99aug** [comment]
Thanks for your helping, I've tried on my own Chrome and Electron Apps, the same problem happens too. So it's really a Chrome problem! (Tried on Discord (Chrome/78.0.3904.130 Electron/7.1.11) , VSCode (Chrome/78.0.3904.130 Electron/7.2.4))

**Comment by deepak1556** [comment]
This is fixed in latest insiders, @rebornix can you please verify. Thanks!
