### ISSUE TITLE
Staging of files not working 

### ISSUE THREAD

**Issue by nelsongnanaraj** [microsoft/vscode#98967]
Issue Type: <b>Bug</b>

1. Clone file from git repository
2. Make some changes. 
3. In Source control tab changes are shown.
4. Stage the changed files. It shows error, Files outside repository

Note: this issue occurred recently in VS code insider.

VS Code version: Code - Insiders 1.46.0-insider (cd41dd1f6065db76c77c6e2f659bb50e6f558dec, 2020-05-29T05:51:32.662Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (2.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|4.7.0
remote-wsl|ms-|0.44.2
material-icon-theme|PKi|4.1.0
vscode-scss-formatter|sib|2.0.1
sonarlint-vscode|Son|1.15.0

</details>

**Comment by joaomoreno** [comment]
What git version do you have installed? Also, can you show me the full output of `Git: Show Git Output`?

Related to https://github.com/microsoft/vscode/issues/99004

**Comment by nelsongnanaraj** [comment]
Same issue #99004

![image](https://user-images.githubusercontent.com/40351940/83512030-36187b80-a4ed-11ea-9275-7a64c5e245a0.png)

Here i mentioned git version **2.10.0.windows.1**

**Git output**
git.stage 1
git.stage.scmResources 1
> git add -A -- f:\Work\ionic_new_workspace\...\*.ts
fatal: f:\Work\ionic_new_workspace\...\*.ts: 'f:\Work\ionic_new_workspace\...\*.ts' is outside repository
> git ls-tree -l HEAD -- F:\Work\ionic_new_workspace\...\*.ts

**Comment by joaomoreno** [comment]
Can you show me the full output?

**Comment by nelsongnanaraj** [comment]
![image](https://user-images.githubusercontent.com/40351940/83535932-38400180-a510-11ea-8726-828e94aac13f.png)


![image](https://user-images.githubusercontent.com/40351940/83536016-573e9380-a510-11ea-9e88-e7fc3318ce40.png)


git.stage 1
git.stage.scmResources 1
> git add -A -- f:\Work\ionic_new_workspace\appM\01_Jun_2020\appM_Guide_V4\dynamockpages_mobile\pages\employee_d_m_hl_detail_view\employee_d_m_hl_detail_view.ts
fatal: f:\Work\ionic_new_workspace\appM\01_Jun_2020\appM_Guide_V4\dynamockpages_mobile\pages\employee_d_m_hl_detail_view\employee_d_m_hl_detail_view.ts: 'f:\Work\ionic_new_workspace\appM\01_Jun_2020\appM_Guide_V4\dynamockpages_mobile\pages\employee_d_m_hl_detail_view\employee_d_m_hl_detail_view.ts' is outside repository

**Comment by m10** [comment]
Updating git for Windows seems to resolve this issue
Tested with Versions 2.25 and 2.27

**Comment by sdegutis** [comment]
Just ran into the same issue. Copied the same command from the git log (in VS Code) to the command line (git bash) and it failed with the same reason, but showed that the backslackes (I'm on Windows) are gone, since they just escaped the following letter. And it's true, C:UsersStevenDocumentsEtcFile.html would in fact be outside my repo if it existed. I'm not at all confident that this is the same error causing this in VS Code, because it probably doesn't use the git bash I have installed outside VS Code. But I thought it might help someone to debug this if it's a related problem.
