### ISSUE TITLE
Auto-update paths for JavaScript requires opening JavaScript file

### ISSUE THREAD

**Issue by mjstelly** [microsoft/vscode#98979]
Issue Type: <b>Bug</b>

Use case: 
Given: I want to move a .js file to another folder, 
When: I relocate the file, I want VSC to update the import path reference,
Then: the app will compile successfully

Current settings
`"javascript.updateImportsOnFileMove.enabled": "prompt"`

Example:
Move ./App.js to ./src/App.js

Result:
Expected: VSC prompts me to update, then updates the import path if I select "yes".
Actual: No prompt and no update occur.

### Update: 
I tried moving the referenced file, App.js, while I had the referencing file, index.js, open. I **_was prompted_** to update the path. That is _not_ expected behavior. That would only work if every referencing file were open in the editor when I moved the referenced file. 

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (1.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.0.1
vscode-apollo|apo|1.16.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
vscode-npm-script|eg2|0.3.12
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|4.7.0
gitignore|mic|1.0.1
atom-keybindings|ms-|3.0.8
vsliveshare|ms-|1.0.2236
debugger-for-chrome|msj|4.12.8
vscode-react-native|msj|0.16.0
code-settings-sync|Sha|3.4.3
autoimport|ste|1.5.3
alphabetical-sorter|ue|2.0.1

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please share your project or a small example project that demonstrates the issue

**Comment by mjstelly** [comment]
The test project can be found [here](https://github.com/mjstelly/vsc_test.git).
To test:

1. Open the project in VSC
2. Check that the setting ` Update Imports On File Move: Enabled` is set to `always`
3. With no files open in the editor, drag `App.js` to the `/src` folder. 
4. Open `index.js`. 

Result:
Expected import: `import App from './src/App';`
Actual import: `import App from './App';`

If `index.js` is open in the editor and the file is moved, VSC will update the path. Also, if the import path is _incorrect_ and the file is relocated to its original spot, the import will not update.
