### ISSUE TITLE
GDB debugger for C++ not working on VS Code

### ISSUE THREAD

**Issue by ayonization** [microsoft/vscode#98978]
- VSCode Version:1.45.1
- OS Version:Windows 10

Ive been using VS Code for c++ development for some time.

Yesterday I mistakenly deleted some files from my C drive, and now the Gdb debugger does not work.

I tried everything, Uninstalled VS Code along with all the extensions and installed it again, also did the same with Mingw. 

I then followed the documentations [https://code.visualstudio.com/docs/cpp/config-mingw](url) thoroughly.
Everything goes well upto the "Running the build" point.

But whenver i try to debug, the terminal shows 

`C:\Users\Ayon\c++\helloworld> cmd /C "c:\Users\Ayon\.vscode\extensions\ms-vscode.cpptools-0.28.1\debugAdapters\bin\WindowsDebugLauncher.exe --stdin=Microsoft-MIEngine-In-h5bb0jol.ikn --stdout=Microsoft-MIEngine-Out-euoebo4n.lli --stderr=Microsoft-MIEngine-Error-ex1jwjkz.d3i --pid=Microsoft-MIEngine-Pid-dawgddvs.jcv "--dbgExe=C:\Program Files (x86)\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin\gdb.exe" --interpreter=mi "
'cmd' is not recognized as an internal or external command,
operable program or batch file.`

Please help me solve this issue. I know this might not be the relevant forum for it since its not an issue with VS Code itself but rather a fault on my part. But Im only asking here because this is my last option. Ive tried everywhere else to no success. 

Any help would be apprecitated.

**Comment by connor4312** [comment]
Please open this issue on the [cpp-tools](https://github.com/microsoft/vscode-cpptools) repo. Thanks!

/causedByExtension
