### ISSUE TITLE
Unable to move/copy when source

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/vscode#98977]
Issue Type: <b>Bug</b>

Unable to rename the file if:
source file name: foo
target file name: foo/index.mdx

Error message:

```
Unable to move/copy when source '/Users/max/Development/project/foo' is parent of target '/Users/max/Development/project/foo/index.mdx'.
```

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
quitcontrol-vscode|art|3.1.3
vscode-tailwindcss|bra|0.2.0
vscode-markdownlint|Dav|0.36.0
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-pull-request-github|Git|0.16.0
vscode-peacock|joh|3.7.2
vscode-github-actions|me-|3.0.0
dotenv|mik|1.0.1
language-gettext|mro|0.1.1
vscode-docker|ms-|1.2.1
python|ms-|2020.5.80290
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
Go|ms-|0.14.3
vsliveshare|ms-|1.0.2236
vscode-graphql|Pri|0.2.14
vscode-yaml|red|0.8.0
mdx|sil|0.1.0
vscode-wakatime|Wak|4.0.0

</details>

**Comment by bpasero** [comment]
That is an impossible file system operation. The file to move would be overwritten by that transaction.
