### ISSUE TITLE
Workspaces don't save when window is open

### ISSUE THREAD

**Issue by cfurst** [microsoft/vscode#98970]
Issue Type: <b>Bug</b>

This is for the case where a workspace has been saved before. So there is a file with the same name available.

1) load VSCode with an active workspace open
2) click on "Save worksapce as..."
3) type or select the workspace file currently in use.

An error should appear saying that the current workspace can't be saved because its in use.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.10.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.1.4
xml|Dot|2.5.0
gitlens|eam|10.2.1
prettier-vscode|esb|4.7.0
vscode-javac|geo|0.2.33
rest-client|hum|0.23.2
code-groovy|mar|0.1.2
vscode-docker|ms-|1.2.1
mssql|ms-|1.9.0
python|ms-|2020.5.80290
debugger-for-chrome|msj|4.12.8
gradle-language|nac|0.2.3
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.18.0
vscode-manifest-yaml|Piv|1.18.0
vscode-spring-boot|Piv|1.18.0
vscode-graphql|Pri|0.2.14
java|red|0.62.0
vscode-xml|red|0.11.0
vscode-yaml|red|0.8.0
scala|sca|0.3.9
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.22.4
vscode-maven|vsc|0.21.4
vscode-spring-boot-dashboard|vsc|0.1.10
vscode-spring-initializr|vsc|0.4.8
vscode-todo-highlight|way|1.0.4

</details>

**Comment by bpasero** [comment]
What exactly is the use caseß

**Comment by cfurst** [comment]
You would like to save the workspace, close it and create a new work with a different set of folders. This logically separates workspaces. Kind of like workbenches in Eclipse. You can have separate workbenches for separate groups of projects. 

Sorry for delayed response.

**Comment by bpasero** [comment]
I was asking about this use case:

> load VSCode with an active workspace open
> click on "Save worksapce as..."
> type or select the workspace file currently in use.

Why save it as same name?

**Comment by cfurst** [comment]
If I've saved it previously, opened it, and made changes to it, I would want to save those new changes to the same place, before I opened or created a new workspace.

**Comment by bpasero** [comment]
@cfurst sure, but:
* adding/removing folders will save it automatically
* if the file is opened in an editor you can simply save it

Just curious how the "Save workspace as" with same name is needed.

**Comment by bpasero** [comment]
This is what I get when I follow the steps:

![image](https://user-images.githubusercontent.com/900690/84119030-1d035380-aa34-11ea-8095-ef94a8f2ec60.png)

I guess you are referring to this as being an issueß

**Comment by bpasero** [comment]
Fixed via https://github.com/microsoft/vscode/commit/007d686e8b4c185462d1c4415342aa85e51fa363

**Verification:** make sure you can "File" > "Save Workspace As..." picking the same name as the workspace that is opened in that window.
