### ISSUE TITLE
Attaching to app take long time before working

### ISSUE THREAD

**Issue by jpchenel** [microsoft/vscode#98973]
Recently, I can't use the debugger anymore for Cordova projects. It takes forever to attach to the app. When I write .scripts in the command windows, I saw scripts loading once at each 15-20 sec. or so. The breakpoints are greyed out and after 2 minutes 15 sec. they turn red.

With fresh dummy project (HelloWorld), it takes 8 sec. to load. If I add 16 dummy .js file, it takes 1 min. to load.

Exemple of dummy js file
```
var _app = (function () {
    var private = "";
    var public1 = function () {
        return '';
    };
    var public2 = function () {
        return '';
    };
    function private() {

    }
    return {
        public1: public1,
        public2: public2
    }
})();
```

launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Run android on device",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "sourceMaps": true,
            "cwd": "${workspaceFolder}"
        }
    ]
}
```

I don't know if it is a circumstance, but before the last update of VS Code it was working. The last time I've played with this project was in the last month.

I've updated nodejs to last version. I've also tried VS Code 1.44.2 with no success.

Thanks for your help.

- VSCode Version:1.45.1 (user)
- OS Version: Windows 10

Steps to Reproduce:

1. Install VS Code
2. Install Cordova Tools 1.9.4
3. Create dummy application
4. Start debuger with breakpoint in index.js

Does this issue occur when all extensions are disabled?: Not supported

**Comment by connor4312** [comment]
Please open this issue on [vscode-cordova](https://github.com/microsoft/vscode-cordova)

/causedByExtension
