### ISSUE TITLE
error message "The terminal process terminated with exit code: 2

### ISSUE THREAD

**Issue by rmsharma5989** [microsoft/vscode#98975]
- VSCode Version: 1.45.1
- OS Version: Windows 10

Steps to Reproduce:
1. in my vs code i have just added the bash command as my default terminal as below 
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"
2. and opening the terminal by command cntrl+,

Terminal pops up and closes immediately with prompting this error at bottom right corner.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Do you have anti-virus software that could be blocking the terminal? If so try following the instructions in https://code.visualstudio.com/docs/editor/integrated-terminal#_how-do-i-fix-the-errors-connectnamedpipe-failed-windows-error-232-or-terminal-exited-with-code-x-on-windows

Also does that file exist? Can you run it in an external cmd window?

/label "needs more info" integrated-terminal
