### ISSUE TITLE
Horizontal rule in hover renders slightly off

### ISSUE THREAD

**Issue by bubba** [microsoft/vscode#98982]
- VSCode Version: 1.45.1 commit 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
- OS Version: macOS 10.15

Sorry in advance if this is the wrong place for the issue, I'm not sure if this belongs in one of the LSP client library packages. Either way hover boxes, from LSP plugins, seem to render horizontal rules (`* * *`) a bit off:

<img width="652" alt="image" src="https://user-images.githubusercontent.com/2488460/83455726-534e3b00-a456-11ea-9fac-0032bf7d1f1d.png">

The horizontal rule is slightly cutting through the line beginning with "throw"

Steps to Reproduce:

1. Use a language server that produces a horizontal rule ([haskell-language-server](https://github.com/haskell/haskell-language-server) uses this)
2. Trigger a hover?

Does this issue occur when all extensions are disabled?: Yes/No

I'm not sure how to reproduce this without using a language server extension!

**Comment by dbaeumer** [comment]
@bubba the easiest would be if you start with this at the Haskell language server repository. What I would need is the generated markdown of the hover to investigate. You can link to this issue so that the Haskell devs can provide it.

**Comment by bubba** [comment]
Here's some markdown string we are sending via the hover request

```
"\n```haskell\n_ :: SessionException -> IO ByteString\n```\n```haskell\n_ :: forall a e. Exception e => e -> a\n```\n*\t*\t*\n\n```haskell\nthrow :: forall a e. Exception e => e -> a\n```\n\n*Defined in \8216GHC.Exception\8217*\n\nThrow an exception.  Exceptions may be thrown from purely\n functional code, but may only be caught within the  `IO`  monad.\n"
```

It looks like there is a blank line between the horizontal rule`*\t*\t*\n` and where the third markdown block begins

**Comment by bubba** [comment]
Got a more minimal example
<img width="104" alt="image" src="https://user-images.githubusercontent.com/2488460/83555243-e8f4d380-a505-11ea-89b4-bad9ffe9eb81.png">
from the markdown:
```
Line1\n* * *\n\n```haskell\nLine 3\n```\n
```

**Comment by bubba** [comment]
Thanks for the fix!

**Comment by dbaeumer** [comment]
@alexdima can you mark the bug as verified since you reviewed and tested the PR.
