### ISSUE TITLE
Confusing, unnecessary highlight it Explorer

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#98986]
When using the Explorer there is a confusing second highlight. Whenever you select an element in the list, either by expanding a folder or opening a file, that element stays highlighted. Then, as you move selection with the arrow keys your 'real' selection is highlighted and you're left with 2 things highlighted. I can't see any purpose for the 'sticky' highlight on the last selected item. It's not useful at all and it's confusing.

In this gif, notice how `.vscode` stays highlighted as selection moves away from it.

![Stupid Highlight](https://user-images.githubusercontent.com/484784/83458828-0c415500-a418-11ea-98b6-0f81c6c9f79f.gif)

I notice there are different theme colors for these highlights:
`list.focusBackground`
`list.activeSelectionBackground`
but that doesn't really tell me why the sticky `activeSelectionBackground` is useful. I can't change the color the be transparent either because when real selection moves to that item that's the color that gets used instead of `focusBackground`.

I also can't find any settings to modify this behavior.

The search view doesn't have this behavior. I expect the explorer to work like search.

**Comment by misolori** [comment]
@isidorn @joaomoreno this looks like a list/explorer bug on selection. When you have no files open and select the a folder and use the keyboard arrows to navigate around the selection is stuck on the folder.

**Comment by isidorn** [comment]
This is how all our list/trees behave, for example also can be seen in the Extensions view.
I am not a big fan of this behavior, but we always behaved like this and changing it would break muscle memory of our users.
@joaomoreno would have more details why we originaly decided to have this behavior

**Comment by misolori** [comment]
If this were to open a file, that makes sense. But when you click on a folder, that looks like a bug:

![image](https://user-images.githubusercontent.com/35271042/83783145-e77df500-a644-11ea-9456-eee0aa9d2bad.png)

**Comment by akbyrd** [comment]
> changing it would break muscle memory of our users.

What muscle memory would this break? What operations can I do on that stray highlight that users might be relying on?

How long has it worked this way? I don't remember this being an issue in the past?

If the behavior absolutely must be preserved, an option to disable would be appreciated. Search doesn't work this way and selection should have the same behavior everywhere.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/95768

> How long has it worked this way? I don't remember this being an issue in the past?

Since day 1, actually. 👍
