### ISSUE TITLE
Test: Hex Editor Extension

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#98980]
https://github.com/microsoft/vscode/issues/98105

- [x] macOS @rebornix
- [x] Windows @9at8
- [x] Linux @joaomoreno

Complexity: 4
Author: @lramos15 

[Create Issue](https://github.com/microsoft/vscode-hexeditor/issues/new?body=Testing%20https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode%2Fissues%2F98980)

---

Testing Steps:

1. Install this VSIX 
[hexeditor-1.0.0.zip](https://github.com/microsoft/vscode/files/4717570/hexeditor-1.0.0.zip) (Just change the .zip to .vsix)
2. Test opening various files as hex via the reopen with dialog / setting the hex editor as your default editor for that file type.
3. Test arrow key navigation, scrolling, clicking etc within the editor.
4.  Test changing the endianness of the Data inspector.
5. Try changing the maxFileSize setting and ensuring it warns you for files over the maxFileSize you have specified.

Just overall ensure the editor feels natural to use and everything is working how you would expect it to.

**Comment by joaomoreno** [comment]
This totally fails for me:

![image](https://user-images.githubusercontent.com/22350/83519211-dd8cb280-a4db-11ea-908e-1a44d4889f42.png)

**Comment by lramos15** [comment]
I'll have to ask @mjbvz what changed. We tested it yesterday and it was working, but I believe he was doing some API work after I got off. I figured a VSIX would be easier than compiling from sources. It doesn't compile from sources anymore either. The VSIX is up to date with latest.

**Comment by lramos15** [comment]
I have updated the VSIX by using the types from sources as we're in this weird limbo where they're not in proposed, but not in the shipped types just yet. The VSIX should work and you no longer need the proposed API flag. Let me know if it doesn't.

**Comment by rebornix** [comment]
It works as documented above. The only concern I have is the scrolling performance, especially when using mouse/trackapd and blank frames are fairly easy to see.

**Comment by 9at8** [comment]
+1 to @rebornix 's comment from me too.
