### ISSUE TITLE
code --wait does not return when closing non-existing file

### ISSUE THREAD

**Issue by mbward** [microsoft/vscode#98981]
- VSCode Version: 1.44.0
- OS Version: Linux

Steps to Reproduce:

1. Start code
2. Open the terminal
3. Run `code --wait somenewfilethatdoesntexist`
4. Press Ctrl+W/Cmd+W/close the file in VSCode
5. Choose "Don't Save"

Expected:
`code --wait` returns, and I can use the terminal again.

Actual:
`code --wait` blocks forever.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by mbward** [comment]
Same thing with insiders .deb.

**Comment by bpasero** [comment]
@mbward is it any different if you use an external terminal for this?

**Comment by mbward** [comment]
Same result in both integrated terminal and Xfce Terminal.

**Comment by bpasero** [comment]
**Explanation:** [we have code](https://github.com/microsoft/vscode/blob/595d2b9b916d063aadfc2c1a8c8f6df5b45572a8/src/vs/workbench/services/editor/browser/editorService.ts#L1205) that observes closing of editors and in this case an untitled resource is being closed. We could change this to handle untitled files, however this would probably cause regressions for when you save the editor (where editors get replaced).

**Comment by lassevk** [comment]
It returns and completes the  "-wait" command if this was the last file open in vscode.

Here's some better steps to reproduce:

1. Execute `code somefilethatdoesnotexist.txt -w`
2. Once the window is open, hit Ctrl+N to open another window
3. Go back to the first tab/file, somefilethatdoesnotexist.txt
4. Hit Ctrl+W/Cmd+W to close this one, reply N to saving
5. Notice the console that ran the original command is still waiting
6. Now close the vscode window
7. Observe that the console now continues
