### ISSUE TITLE
Prompt to restart VS Code when installing same extension using VSIX

### ISSUE THREAD

**Issue by alberto-bc** [microsoft/vscode#98983]
- VSCode Version: 1.45.1
- OS Version: macOS Catalina 10.15.4

On Windows, after uninstalling an extension, VS Code prevents the user to reinstall the same extension without reloading VS Code. It shows the following message:
"Please restart VS Code before reinstalling <extension_name>."

On Mac, users can reinstall the extension without reloading VS Code. 

Steps to Reproduce:

1. Install any extension (tested with the Powershell extension)
2. Uninstall the extension
3. Install the extension again, without restarting VS Code

Does this issue occur when all extensions are disabled?: This is an extension handling problem

**Comment by sandy081** [comment]
Not sure what is the issue here. May I know what happens after your install extension again?

**Comment by alberto-bc** [comment]
As an extension developer, I rely on the use of the [uninstall hook](https://code.visualstudio.com/api/references/extension-manifest#extension-uninstall-hook)

Since such hook executes **only** when VS Code restarts, the Windows behavior (preventing the user to reinstall without reloading) is desirable in **all** platforms.

**Comment by sandy081** [comment]
If I understand correctly are you asking to trigger this hook immediately after user uninstalled it?

**Comment by sandy081** [comment]
> No, I opened this ticket because VS Code behaves differently on Windows and Mac when performing the same operation (i.e. trying to reinstall an extension without reloading).

The intention is to fix VS Code-Mac so that users are prevented from reinstalling, just as in Windows.

How are you performing the operation - reinstall without reload? Can you please provide a screenshot or a gif?

Also let me know what is the difference in behaviour

**Comment by alberto-bc** [comment]
> How are you performing the operation - reinstall without reload? Can you please provide a screenshot or a gif?

I have attached gifs for each platform.
![mac](https://user-images.githubusercontent.com/66279626/83801063-523b2a80-a65d-11ea-8d6d-0df730c62d01.gif)
![win](https://user-images.githubusercontent.com/66279626/83801075-58c9a200-a65d-11ea-9a87-43e4ebe1ba22.gif)



Repro steps:
1. Download PowerShell extension vsix file
2. Install the extension
3. Uninstall the extension
4. Reinstall the extension without reloading VS Code

Difference in behavior:
Windows: The extension can't be installed without reloading. VS Code displays the error message "Please restart VS Code before reinstalling PowerShell." (good)

macOS: No error message is displayed, and the user can reinstall the extension without reloading VS Code (bad)

Expected behavior:
VS Code should prevent the user to reinstall an extension without reloading. This behavior should be consistent on all platforms.

**Comment by sandy081** [comment]
Now I get it. 

When Installing from VSIX and if you are installing the same version, we will delete the existing version from the disk and install the new VSIX. It seems Windows is not liking to delete the folder for some reason, may be extension is running and some process is locking the files. 

I think VS Code is behaving correctly as it is supposed to be and not sure if anything can be done here.

**Comment by alberto-bc** [comment]
VS Code is behaving correctly **only on Windows**, as it is displaying an error message asking the user to reload VS Code.

The problem is macOS.

**Comment by sandy081** [comment]
I do not see a reason why an operation has to be failed if it can run successfully ? In other words why does the install has to fail if it can be successful and ask user to restart VS Code to install an extension even though it is not required?

**Comment by alberto-bc** [comment]
I see 2 problems here:

1. As mentioned before, the [`uninstall hook`](https://code.visualstudio.com/api/references/extension-manifest#extension-uninstall-hook) only executes on VS Code restart. If VS Code does not prevent the user to reinstall the **exact same** extension after uninstalling, there is no guarantee this hook will execute when needed.

2. Consistency - The extension management should be consistent across platforms. 

> why does the install has to fail if it can be successful and ask user to restart VS Code to install an extension even though it is not required?

It has to fail to ensure the uninstall hook is executed, and it has to fail on all platforms.

**Comment by sandy081** [comment]
Did you try reinstalling from Marketplace instead of VSIX? I think this will be consistent across platforms.

Installing VSIX is special because this includes a development / testing scenario so that users want to replace existing extension even though both are same. Also asking user to restart always when uninstalling an extension (from Marketplace or VSIX)  is not a good idea and users might not like it.

Mixing up uninstall hook requirement with this is scenario is not correct. It looks you wanted another requirement as a side affect of fixing another scenario and causes distraction in this issue. So please have them separately.

**Comment by alberto-bc** [comment]
> Did you try reinstalling from Marketplace instead of VSIX? I think this will be consistent across platforms.

The extension I'm developing is for private use, so it won't be in the Marketplace

> Installing VSIX is special because this includes a development / testing scenario so that users want to replace existing extension even though both are same. Also asking user to restart always when uninstalling an extension (from Marketplace or VSIX) is not a good idea and users might not like it.

This ticket is not about asking the users to restart when uninstalling an extension, but to prevent reinstalling the same extension without reloading (**just as Windows is doing right now**)

> Mixing up uninstall hook requirement with this is scenario is not correct. It looks you wanted another requirement as a side affect of fixing another scenario and causes distraction in this issue. So please have them separately.

I will open a different issue for the uninstall hook requirement

**Comment by sandy081** [comment]
> This ticket is not about asking the users to restart when uninstalling an extension, but to prevent reinstalling the same extension without reloading (just as Windows is doing right now)

Ok, updated the summary as you requested. So what is the use case behind this?

**Comment by alberto-bc** [comment]
> Ok, updated the summary as you requested. So what is the use case behind this?

Prevent the user from reinstalling an extension without restarting VS Code.


This use case is handled properly on Windows. It should be handled properly on Mac as well.

**Comment by sandy081** [comment]
> Prevent the user from reinstalling an extension without restarting VS Code.

Sorry I am asking for why you want this? If the reason is just this is different on different platforms I would say there is nothing we can change unless there is a strong reason why you need this.

**Comment by alberto-bc** [comment]
Related to this issue: #99474 

I'm working on an extension that relies on the uninstall hook. 
On Windows, users cannot reinstall the extension without restarting VS Code, so the extension has no problems.

On Mac, users can reinstall the extension without restarting VS Code, causing different issues.

The current behavior on Windows mitigates the current uninstall hook limitation.

**Comment by sandy081** [comment]
I see, then #99474 is the main use case you wanted to have and this is not the right approach for fixing that. As said, calling uninstall hook when an extension is uninstalled and is not used anywhere.
