### ISSUE TITLE
Test notebook core

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#98985]
Testing https://github.com/microsoft/vscode/issues/91987

- [x] Windows @aeschli 
- [x] macOS @JacksonKearl
- [x] Linux @lramos15

Complexity: 4

Authors: @roblourens, @rebornix, @jrieken, @misolori 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%2398985%0A%0A)

---

Install the [Github Issue Notebook extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-github-issue-notebooks). Run it through its basic functionality. Place special attention to these areas

- **UI**
  - We made changes to cell backgrounds, borders and how cell focus/hover indicators render. Please check if it looks reasonable in your theme
- Dragging and dropping cells
- Focus state
  - You can use ctrl+down (ctrl+cmd+down on mac) to put focus into the active cell's output, and ctrl+up (ctrl+cmd+up) to get back out
  - You can tab from the editor into the output (after using "Toggle Tab Focus" ctrl+shift+M), and tab back out, and it doesn't break things
    - And it's impossible to get into an inconsistent state where you have the blue focus line on cell A, when the editor in cell B has the cursor
- Markdown cell
  - You can have image references in markdown cells, using relative or absolute paths
  - Markdown cells stay in edit mode until they are explicitly put back in preview mode (by pressing esc, clicking the check, or executing the cell)
- Retained notebook editor
  - Moving notebook editor from one editor group to another should not rerender the execution result / output
  - Pined notebook editor should not rerender outputs when switching between different editors
- Commands
  - You can now Split Notebook Cells and Join with Next/Previous Cell, please test if they work as expected

**Comment by rebornix** [comment]
Testers FYI: this TPI covers most features/polishes we made to Notebook core, it doesn't cover changes we made to other VS Code components but they are covered in other TPIs:

* Undo/Redo #98991
* Language features #98821
