### ISSUE TITLE
Test cross-file undoing in files that were closed

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#98987]
Test plan item for #92272

- [x] anyOS @connor4312
- [x] anyOS @sbatten

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%2398987%0A%0A)

---

* Create a cross-file edit that involves file edits (not file renames), like a rename in a TS file.
* Close some of the files
* In one of the edited file, do an undo
* The closed files should now reopen and the undo should be applied in all of them

There are some special cases like renaming or editing files on disk before undoing. Please check that things work OK.

**Comment by connor4312** [comment]
Last week I renamed a function and undid it, but that ended up clobbering files giving some broken name. I wasn't able to get a repro for it then or now, but fyi.
