### ISSUE TITLE
Test: View Container Movement

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#98994]
- [x] anyOS @eamodio
- [x] macOS @ornellaalt

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%2398994%0A%0A)

---

This iteration, the focus for view and view container movement has been stabilization. Many issues have been fixed and some UX polish has been added. View collapsing in the panel has been improved with the bookend + icon model and view movement has been configured to reduce UI disruption. This item is open-ended to to root out any bugs that should be fixed before announcing this feature out of preview this month.

Testing involves:
* Moving views and containers around by icon, title, individual views
* Rearranging views inside a container
* Reload the window and verify there is no flashing
* Test with multiple windows and verify changes are propagated successfully

As always, use `Reset View Locations` if you want to get to a clean state. You can also reset individual views and containers with the context menu entry on the view/container.

**Comment by eamodio** [comment]
Overall looks really good -- great work!
