### ISSUE TITLE
add highlighting of common keywords like TODO

### ISSUE THREAD

**Issue by phra** [microsoft/vscode#9899]
hi,

i'm submitting a feature request.
it would be nice to have color highlighting of common keywords like TODO, FIXME, XXX et cetera.

**Comment by phra** [comment]
any update on this?

**Comment by alexandrudima** [comment]
From #11510:
---

Couldn't find any documentation on this or any good extensions. Would be amazing if we could have task tags, something that could be user defined/customizable inside settings.json

Similar to:
``` 
editor.taskTags: [
    { name: "TODO", color: "#00FF00" },
    { name: "BUG", color: "#FF0000" },
    { name: "NOTE", color: "#0000FF" }
]
```

``` javascript
// TODO: Find out why click event is undefined...
event.target.click();
```

The TODO comment would then be highlighted in the color chosen in the settings file, for this example "Green".

**Comment by phra** [comment]
any update on this? it seems to me a quick feature to implement.. maybe i can try to implement it the next weekend..

**Comment by smlombardi** [comment]
There is an extension : https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight

But I'd prefer this to be part of  VSCode scope, so we can include it in our themes.

**Comment by PierreRoudaut** [comment]
A couple of extensions exist indeed, but a native support by VSCode would be really nice !

**Comment by uditalias** [comment]
+1

**Comment by imranshafqat** [comment]
+1

**Comment by koutsenko** [comment]
When will a native feature available?
As Eclipse Team did many years ago
![2017-09-25 16 45 05](https://user-images.githubusercontent.com/529293/30812507-93c3472c-a213-11e7-9afc-a3a1c8d820b0.png)

**Comment by ScottEfird** [comment]
It would be awesome if we could get a task list like VS has. 
https://msdn.microsoft.com/en-us/library/txtwdysk.aspx

**Comment by phra** [comment]
@ScottyEfird it a nice idea! looking forward to see this implemented in the code.. or maybe, if someone can give some guidelines to help with the development of a PR, i can help with it!

**Comment by RKopczynski** [comment]
There is an extension with some possible customisations for highlighting.
[https://github.com/wayou/vscode-todo-highlight](VS Code TODO Highlight)

What about using this as reference? It could be great to see this as build-in feature.

**Comment by Hurtak** [comment]
I have also notices that there are some languages, like Python, have this implemented. So it would be nice if this worked in comments with any language.

**Comment by RKopczynski** [comment]
@Hurtak extension which I mentioned isn't language dependent. It works just by file extension, so in python it would work as well.

**Comment by mbenkmann** [comment]
The Eclipse implementation should really be the reference for this feature. It's better than all the VSCode extensions that try to add this feature. I especially like the feature that in Eclipse I can resolve TODOs, i.e. remove the respective comment, from within the TODO list. I don't have to go to the editor and manually delete the text.
As for the implementation of this feature in VS Code, I think the new Search panel is a good starting point. There's some crossover with feature request #47351. If you had that feature request implemented then you would just need to tie the "Dismiss" checkbox to removing/readding the TODO line from/to the comment.

**Comment by vphantom** [comment]
FYI for now I found my bliss with the [Todo Tree extension](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree) which highlights in editors and adds a configurable tree view summary as well.

**Comment by fabiospampinato** [comment]
I think my [Highlight](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight) extension should be used for this. [TODO Highlight](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight) is an alternative, but it may not be general/powerful enough for your use case.

**Comment by JeffML** [comment]
Atom (can I say that here?) supports this, IIRC.   Instead of a fixed color for TODOs, maybe an offset hex value based on editor background color?

**Comment by AnrDaemon** [comment]
Neither of the suggested extensions can limit highlighting to comments only.
(Translation: they are rather useless.)

P.S.
And I don't mean intricately crafted regexps - none of them will work inside docblocks, for example.

**Comment by fabiospampinato** [comment]
@AnrDaemon I think you're doing it wrong.

> Neither of the suggested extensions can limit highlighting to comments only.

Even if they could I wouldn't want that, I often write "//TODO" inside my markdown documents, should that not be highlighted because it's not inside a comment? (What even is a comment in markdown? `<!-- comment -->`?)

There are no comments at all in JSON, so where do you write your "//TODO"s if you need to? I put them inside strings, for instance reminding me to write a description for a package or reminding me to add some keywords, should that not be highlighted?

> And I don't mean intricately crafted regexps - none of them will work inside docblocks, for example.

[TODO Highlight](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight) is too limiting in this regard, but with my [Highlight](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight) you should be able to craft a good enough regex for highlighting only todos inside docblocks.

Of course this problem is impossible to solve in the general case with regexes, the same way you can't really parse xml with regexes, but for most, if not all, of your day-to-day cases it should work just fine. 

Feel free to open an issue [here](https://github.com/fabiospampinato/vscode-highlight) if you need help crafting that regex.

**Comment by AnrDaemon** [comment]
I have a strong feeling that this should be a part of highlighting library, not a separate extension. You just can't do it right with ad-hoc "solutions".

P.S.
I with for somebody implementing Colorer library plugin for VS Code. Would solve approx. 200 languages highlighting in a fingersnap.

**Comment by noktilux** [comment]
fabio.

your extension looks great and i have installed it but, as a new VS Cod user, i am not quite sure where (in which file) i need to write the syntax.  am using ubuntu as OS.

**Comment by AnrDaemon** [comment]
> @AnrDaemon I think you're doing it wrong.
> 
> > Neither of the suggested extensions can limit highlighting to comments only.
> 
> Even if they could I wouldn't want that, I often write "//TODO" inside my markdown documents, should that not be highlighted because it's not inside a comment? (What even is a comment in markdown? `<!-- comment -->`?)

"An image worth a thousand words." (q)
![An image worth a thousand words.](https://user-images.githubusercontent.com/6532485/49621249-7a4cbd80-f9d5-11e8-96f0-b5cffd61ef91.png)

**Comment by fabiospampinato** [comment]
@AnrDaemon you can absolutely achieve the result on the right with [Highlight](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight) today. If you need help crafting the right configuration please one an issue in Highlight's repo.

**Comment by sanket-bhalerao** [comment]
I would really like this feature. seeing all the TODOs in a viewlet always calms me down.

**Comment by AnrDaemon** [comment]
> @AnrDaemon you can absolutely achieve the result on the right with [Highlight](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight) today. If you need help crafting the right configuration please one an issue in Highlight's repo.

There's simple no way to achieve the desired results without knowing if you are inside a comment or not. No amount of regex will help, only structural language parsing.

**Comment by jrieken** [comment]
Marking as extension candidate (and hence closing). Multiple todo highlighter extensions of good quality are available. Duplicating their functionality would be unfair to extension authors and will also raise the "vscode is bloat" voices. Instead, we can make sure extensions are easy to consume, roam across computers, and that extension authors have all the API they need to built the best extensions possible. As users we should help extension authors with feature request, issue reports, and pull requests. 

Available todo-highlighter extensions (without specific order): [vscode-todo-highlight](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight), [todo-tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree), [vscode-highlight](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight)

**Comment by fabiospampinato** [comment]
> There's simple no way to achieve the desired results without knowing if you are inside a comment or not. No amount of regex will help, only structural language parsing.

@AnrDaemon The snippet of code you posted can absolutely be highlighted correctly with my extension:

<img width="319" alt="Screen Shot 2019-10-09 at 12 00 01" src="https://user-images.githubusercontent.com/1812093/66471867-64dc7000-ea8c-11e9-99f8-d689b8ff5eab.png">

You just need to write a proper regex and follow the instructions.

It's correct that you can't highlight all kind of possible valid code via regular expressions, but who writes that kind of code anyway, I haven't had any such issues yet.

I'd recommend this monster regex personally, give it a try:

```
  "highlight.regexFlags": "gi",
  "highlight.regexes": {
    "((?:<!-- *)?(?:#|// @|//|./\\*+|<!--|--|\\* @|{!|{{!--|{{!) *TODO(?:\\s*\\([^)]+\\))?:?)((?!\\w)(?: *-->| *\\*/| *!}| *--}}| *}}|(?= *(?:[^:]//|/\\*+|<!--|@|--|{!|{{!--|{{!))|(?: +[^\\n@]*?)(?= *(?:[^:]//|/\\*+|<!--|@|--(?!>)|{!|{{!--|{{!))|(?: +[^@\\n]+)?))": {
      "filterFileRegex": ".*(?<!CHANGELOG.md)$",
      "decorations": [
        {
          "overviewRulerColor": "#ffcc00",
          "backgroundColor": "#ffcc00",
          "color": "#1f1f1f"
        },
        {
          "backgroundColor": "#ffcc00",
          "color": "#1f1f1f"
        }
      ]
    }
  }
```

**Comment by AnrDaemon** [comment]
That's not the only case where your extension fails.
It easily picks tags in plain strings, for example.

**Comment by AnrDaemon** [comment]
> todo-tree,

Works like a charm after a little configuration. Thank you.
