### ISSUE TITLE
Saving untitled notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#98992]
- Version: 1.46.0-insider
- Commit: 2c1871d538c64df71af4902deba47d7fa4b53f27
- Date: 2020-06-01T10:32:27.369Z
- Electron: 7.3.0
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Darwin x64 19.5.0

Steps to Reproduce:

1.Create a new untitled notebook (using VS Code Python extension)
2.When you add a cell or the like, then VSC will invoke the save method on the `NotebookContentProvider`

**Problems**
* Adding cells should not invoke save (this happens when user has auto save turned on)
* Errors thrown in the `saveNotebook` method are ignored. VSC will assume the notebook was saved and mark it as not dirty (the dirty indicator doesn't exist on the tab anymore)

I don't think VSCode should call the `saveNotebook` method for untitled notebooks.

**FYI - We create untitled notebooks with a scehme `untitled`.**
If this isn't the way to indicate an untitled file (scheme), we might need some API or the like in the notebooks implememtation.

@rebornix /cc

**Comment by rebornix** [comment]
Good catch, untitled file should not trigger save until users explicitly run Save, which will invoke SaveAs.

**Comment by rebornix** [comment]
We should also improve the overall experience for creating untitled notebook documents, they can be created in two approaches:

* Users press cmd/ctrl+n to create an untitled file, switch to another view type (tracked in https://github.com/microsoft/vscode/pull/93669)
* Users run a specific command to quickly create a notebook untitled file. `workbench.action.files.newUntitledFile` command should take view type as arguments.

cc @mjbvz we may also want to adopt this in Custom Editor world.

**Comment by rebornix** [comment]
We now support opening a untitled file with specified editor view type through the existing new untitled file command (in master, and tomorrow's Insiders)

```
  {
    "key": "cmd+i",
    "command": "workbench.action.files.newUntitledFile",
    "args": { "viewType": "github-issues" }
  }
```

When the command is executed, `NotebookContentProvider.openNotebook` is invoked with an URI with `untitled` scheme. `NotebookContentProvider.saveNotebook` is invoked only when users save so no auto save for untitled files as usual.
