### ISSUE TITLE
Test: add missing imports and remove unused source actions

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#98997]
Refs: #95831

- [x] anyOS @kieferrm
- [x] anyOS @dbaeumer

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%2398997%0A%0A)

---

**Summary**
This iteration, we added two new source actions: `add missing imports` and `Remove all unused code`. This actions let you trigger add missing imports or remove unused from anywhere in a file

You can also use them with `editor.codeActionsOnSave` or configure a keybinding for them

```
    {
        "key": "ctrl+shift+i",
        "command": "editor.action.sourceAction",
        "args": {
            "kind": "source.addMissingImports",
            "apply": "first"
        }
    },
```

Test these new source actions and their behavior. `Add missing imports` should pretty much always work (although it may not select the ideal import in all cases). 

`Remove all unused code` has more limitations due to current TypeScript APIs

**Comment by dbaeumer** [comment]
@mjbvz it is not clear to me how extensively I should test this from a TS perspective. General impression is 'Add missing import' works as expected. `Remove unused code` is not.

**Comment by andrewzey** [comment]
I get the error `No source actions available for 'source.addMissingImports'` when trying to run this.
