### ISSUE TITLE
Test: Delayed startup activation events

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#98990]
Test plan item for #98083

- [x] anyOS @roblourens
- [x] anyOS @rebornix

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%2398990%0A%0A)

---

There is a new activation event which looks like e.g. `onStartup:1000` or `onStartup:5000`. This means that the extension wants to be activated 1000ms or 5000ms after startup. This is very similar to `*` activation, but the extension indicates that it can wait a bit.

Please check that this activation event works and please bring up any suggestions you might have about the name or if the number should be eliminated.

**Comment by alexdima** [comment]
Suggestions from today's standup:
* drop the number, since extensions wouldn't necessarily care about the exact delay
* suggestions for other names: e.g. `eventually`

**Comment by rebornix** [comment]
+1 for `eventually` as it's hard to know what's the magic number to use for `onStartup:${NUM}`

**Comment by roblourens** [comment]
Yeah I don't see why an extension author would know whether 1s or 5s or something else is better.

Would it be possible to make "*" work the same as "eventually", and add a new event like "immediately" that would be like the new "*"?

Or, what are some cases where the extension author would strongly care one way or the other, or when would "eventually" give you a really bad experience?

**Comment by alexdima** [comment]
@roblourens We can't change the semantics of `*` at this point, since so many extensions already use it. `*` means on startup. There are some extensions, like the dev containers one, which would like to activate in order to look at the folder and, with some custom logic, actively propose something to users. But the extension does not want to take time from other extensions running in during start-up.
