### ISSUE TITLE
Test: Contribute Icon and Context Title to Extension Views

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#98996]
Refs: #93972 #93968

- [x] anyOS @eamodio
- [x] anyOS @stevencl

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%2398996%0A%0A)

---

This iteration, we exposed the ability for extension authors to contribute an icon and contextual title for their views to help when the views are moved.

The purpose of the view icon:
1. When the view is collapsed in panel, the icon is shown in the bookend header.
2. When the view is moved to the activity bar, the view icon is used if it is the top-most view in the container.

The purpose of the view contextual title:
1. When the view is moved to the panel, the contextual title is used to give meaning to view since it normally lives in a container with context. e.g. Using the Bookmarks extension viewlet with the view named Explorer. Moving this view requires the context "Bookmarks: Explorer" to avoid confusion with the Explorer Viewlet. By default extensions will have a context of the original title the view was contributed to meaning no action needed for most extension authors.
2. The same logic above applies when the view is moved into another container that doesn't share the same context. e.g. supposed 2 extensions provide line history, but both are moved to the same container.

Testing involves:
1. Use the tree view sample https://github.com/microsoft/vscode-extension-samples/tree/master/tree-view-sample
2. Add icons to the contributed views with the property `icon` in the package.json
3. Add a contextual title with the property `contextualTitle` in package.json
4. Test moving the views around in multiple fashions to ensure the proper icon/title is used.

**Comment by eamodio** [comment]
Looks good!
