### ISSUE TITLE
Test: notebook renderer API

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#99001]
Refs: #95361

- [x] anyOS @misolori
- [x] anyOS @fiveisprime

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%2399001%0A%0A)

---

**Summary**
There's a new API exposed to renderers in webviews, defined like so:

```
export interface INotebookRendererApi<T> {
  setState(value: T): void;
  getState(): T | undefined;
  postMessage(msg: unknown): void;

  /**
   * Fired before an ouput is destroyed, with its cell URI, or undefined if
   * all cells are about to unmount.
   */
  onWillDestroyCell: Event<string | undefined>;

  /**
   * Fired when a cell is mounted.
   */
  onDidCreateCell: Event<HTMLElement>;
}

function acquireNotebookRendererApi<T = any>(rendererType: string): INotebookRendererApi<T>;
```

This API is "namespaced" to renderers. It's intended that you call it with your renderer type--though this is not enforced. Expected behavior:

 - `acquireNotebookRendererApi` is available to you.
 - Getting and setting the state is isolated in your renderer. Different renderers should not be affected by each others' state.
 - onDidCreateCell is fired with the HTML element to mount in when _this_ renderer should draw something on the screen.
 - onWillDestroyCell is fired with the cell URI immediately before the cell is removed from the DOM.
 - Currently postMessage isn't specially attached anywhere. Don't worry about testing this, yet.

I created a branch of the renderer-starter code that registers two renderers to help you test their interaction: https://github.com/microsoft/vscode-notebook-renderer-starter/tree/multi-renderers. You can toggle between them using this button:

![](https://memes.peet.io/img/20-06-b1333619-aa4b-4305-b5ed-dbea05a79cbb.png)

(note, both of them look the same in the quickpick, already have a bug for this https://github.com/microsoft/vscode/issues/99000)

**Comment by misolori** [comment]
Ran into a couple of issues:
- `Cannot find module 'nan'` when running `npm install` so I had to manually install via `npm i nan`
- In the sample provider, the `executeCell` function requires both document and cell parameters, so I had to update the sample

**Comment by misolori** [comment]
Thanks for providing the renderer starter repo, that saved so much time (not sure I'd be able to complete this without it). I did find one oddity in how the states are supposed to be used, but besides that it worked as expected. And the multi-renderer also works nicely (I see there how the states are isolated to each renderer, which was nice).

**Comment by misolori** [comment]
@connor4312 btw the milestone is set to `June` on this test plan item, not sure if that's intentional or not.

**Comment by connor4312** [comment]
whops, thanks for pointing that out. And for testing!

**Comment by fiveisprime** [comment]
Tested on Windows, looks good. 👍
