### ISSUE TITLE
Impossible to distinguish multiple output renderers provided in the same extension

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#99000]
I noticed this when writing my testplan and prepping a repo with two sample renderers to test their interaction:

![](https://memes.peet.io/img/20-06-0a189325-3900-4135-b998-c9a847ae876f.png)

I think there could be real scenarios where this is desirable, for example in a theoretical profiling notebook I might allow the output to be visualized both as a flame chart and table.

**Comment by rebornix** [comment]
We can show the id of the renderer in the quick pick entry description.

**Comment by connor4312** [comment]
At least in the case when there's multiple renderers for a single mime type provided by the extension

**Comment by rebornix** [comment]
![image](https://user-images.githubusercontent.com/876920/83572169-e7afb080-a4dd-11ea-939a-53a418166988.png)

The UI now aligns with `File: reopen with...` which shows the source of the renderer in detail.
