### ISSUE TITLE
Keyboard shortcut for scrolling activity bar icons

### ISSUE THREAD

**Issue by doubleUTF** [microsoft/vscode#99009]
The Activity Bar contains 7 or more icons to be selected (Explorer, Search, Source Control, Run, Extensions, Test, Manage, or more). For keyboard A11y and those too lazy to use the mouse or forgetful of their specific keyboard shortcuts, I propose a keyboard shortcut command to scroll up and down the activity bar (i.e. Ctrl+Shift+Down, Ctrl+Shift+Up). Now Instead of memorizing 5 or more distinct shortcuts, I could bring that down to two for navigating the Activity Bar.
![activity_bar](https://user-images.githubusercontent.com/17230520/83481843-b1c5ea00-a453-11ea-8be2-0d2d3d6654c5.png)

**Comment by isidorn** [comment]
Thanks for feedback however dup of https://github.com/microsoft/vscode/issues/97610
