### ISSUE TITLE
Deselecting a file using Ctrl-click doesn't work as expected

### ISSUE THREAD

**Issue by charlesg99** [microsoft/vscode#99002]
Issue Type: <b>Bug</b>

1. Select multiple files in the explorer using <kbd>Shift</kbd> + click
2. Deselect one of the files using <kbd>Ctrl</kbd> + click
3. Press <kbd>Delete</kbd>
4. The last clicked (deselected) file goes in the trash instead of the selected files

![Peek 2020-06-01 20-57](https://user-images.githubusercontent.com/33044886/83472161-9ad3c780-a454-11ea-8e56-c3b07db70117.gif)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.6.15-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3511)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.71GB (3.30GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-intelephense-client|bme|1.4.1
gitlens|eam|10.2.1
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
php-debug|fel|1.13.0
vscode-test-explorer|hbe|2.19.1
rest-client|hum|0.23.2
git-graph|mhu|1.23.0
language-gettext|mro|0.1.1
vscode-docker|ms-|1.2.1
cpptools|ms-|0.28.1
vsliveshare|ms-|1.0.2236
debugger-for-chrome|msj|4.12.8
vscode-phpunit|rec|2.0.72

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
@isidorn Could the explorer simply assume the user intends to delete the entire selection, if there's more than 1 file selected, independently of focus?

**Comment by isidorn** [comment]
I would not touch the logic for figuring out what is the context.
It is rather tricky since there are commands comming from all over the place, and anytime I touch something there something else gets broken.
Due to that closing as will not fix
