### ISSUE TITLE
Close the extension resource in the editor if it is filtered in the view 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#9900]
- Open Extension view
- Select any installed extension
- Filter for most popular extensions, make sure that selected is not part of these

Since selected extension is no longer available, it makes sense to close the resource too.

**Comment by joaomoreno** [comment]
I don't agree, since it seems to be a common flow to click on an extension, read a bit about it, and continue searching for more extensions while keeping the original's description open.

They are not nor should behave like editors.
