### ISSUE TITLE
Test: Smoke Test

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#99012]
- [x] Windows @roblourens 
- [x] macOS @isidorn
- [x] Linux @aeschli
- [x] Web (Chromium, anyOS) @dbaeumer 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%2399012%0A%0A)

---

**NOTE:** Desktop & Web tests MUST run with `--build` argument

**NOTE:** Desktop tests MUST run with `--stable-build` argument additionally

Documentation: https://github.com/Microsoft/vscode/blob/master/test/smoke/README.md#run.

If the automated tests fail, create and issue for that and run the tests manually: https://github.com/microsoft/vscode/wiki/Smoke-Test

**Comment by aeschli** [comment]
`languages features - verifies settings` reveals a bug that I fixed thorough #99108

With that test commented out, all is green in Linux with 1bfa086adb:
(`yarn smoketest --build ~/vscode/1.46.0-insider-1bfa086adb/VSCode-linux-x64/`)

**Comment by roblourens** [comment]
Does this need a 4th assignee? @dbaeumer

**Comment by dbaeumer** [comment]
I will take it.

**Comment by isidorn** [comment]
Ran it 2 times on mac both times all green ✅
