### ISSUE TITLE
Test: Git abort rebase

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#99015]
Ref - #72576

- [x] anyOS @isidorn
- [x] anyOS @bpasero

Complexity: 2

Authors: @lszomoru, @joaomoreno 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%2399015%0A%0A)

---

We have added a new command into the command palette to abort an in-progress rebase operation:
- Create a new git repository
- Add a new text file to the repository
- Add a new file to the `master` branch
- Create a new topic branch from master
- Update the file in the `master` branch. Commit.
- Update the file in the topic branch. Commit.
- Rebase topic branch on top of master. You should get a conflict. 
- From the command palette choose the `Git: Abort Rebase` command.

Expected: In progress rebase operation should be cancelled.

**Comment by isidorn** [comment]
Works niceyl 👏 
I tested on macOS.
