### ISSUE TITLE
Smoke Test failure: Language Feature - verify settings

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#99014]
Please see: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=76961&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=05af1eac-c39c-5c75-1e3f-dd115ec8907d&l=48

**Comment by sandy081** [comment]
/duplicate 

https://github.com/microsoft/vscode/issues/99108
