### ISSUE TITLE
Ctrl+K Ctrl+U doesn't uncomment lines in diff editor (right side)

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#99011]
For some reason `Ctrl+K Ctrl+U` (`editor.action.removeCommentLine`) doesn't work in the diff editor, but `Ctrl+K Ctrl+C` works fine

**Comment by rebornix** [comment]
Do you see the same issue when you run the command from command palette? I can't reproduce this issue with a TS file.

**Comment by eamodio** [comment]
From the command palette it works, but not with the shortcut

**Comment by rebornix** [comment]
@isidorn merged a PR which added default keybindings for git https://github.com/microsoft/vscode/issues/93564 , which conflict with this keybindings.

**Comment by isidorn** [comment]
Sorry about that, changed the git one to ctrl+k, ctrl+n
