### ISSUE TITLE
VS Code integrated git doesn't detect repository when .git directory marked as hidden

### ISSUE THREAD

**Issue by frodo821** [microsoft/vscode#99028]
VS Code integrated git functionality doesn't work when .git directory marked as hidden.

When I tried to open `source control` tab on the sidebar, I saw an error message and `initialize repository` button, but the project directory was created by the `git clone` command.

Git for windows marks .git directory as hidden, as default behavior, so I turned not hidden the .git directory, then the message disappeared.

**Comment by joaomoreno** [comment]
What does `git status` return in a Command Prompt in that folder?

**Comment by frodo821** [comment]
git status (or other subcommands) works fine on my powershell console. `Git: Show Git Output` makes no output (and when reload window from command palette and re-execute the command, somehow the error has disappeared)

**Comment by frodo821** [comment]
I found the problem happened when the CircleCI plugin (`jvandyke.vscode-circleci`) is enabled. May I close this issue and report this problem to them?
