### ISSUE TITLE
Terminal Clear doesn't work, when app launched with 'code' command

### ISSUE THREAD

**Issue by frontEndFahim** [microsoft/vscode#99024]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/needsMoreInfo
