### ISSUE TITLE
C++ extension not work after updating to 0.28.2

### ISSUE THREAD

**Issue by MarkSoviet** [microsoft/vscode#99023]
- VSCode Version: 1.45.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. update c++ extention to 0.28.2
2. auto-completion and error alert cannot work but "go to definition" can still work

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by connor4312** [comment]
Please open this issue on https://github.com/microsoft/vscode-cpptools

/causedByExtension
