### ISSUE TITLE
After upgrading the Ubuntu 20 system, it is not possible to debug the typescript project in vscode

### ISSUE THREAD

**Issue by 820465323** [microsoft/vscode#99038]
vscode version: 1.45.1
OS: Ubuntu 20.04 LTS
Nodejs: 12.17.0

Steps to Reproduce: (**It seems that it can only appear in Ubuntu 20.04 LTS, because it is normal to run on Ubuntu 19**)
Scaffolding generated using the following script
1. mkdir showcase && cd showcase
2. npm init egg --type=ts
3. npm i
4. Open vscode debugger
5. Use the following launsh.json to configure
**{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Egg Debug",
      "runtimeExecutable": "npm",
      "runtimeArgs": [
        "run",
        "debug",
        "--",
        "--inspect-brk"
      ],
      "console": "integratedTerminal",
      "restart": true,
      "protocol": "auto",
      "port": 9229,
      "autoAttachChildProcesses": true
    }
  ]
}**
6. Choose egg debug to start

I also try to get rid of -- inspect brk
But vscode reminds me Breakpoint ignored because generated code not found (source map problem?)

**Comment by connor4312** [comment]
Please enable `trace: true` in your launch configuration and share the logs with us!

You can also try using our [new debugger](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly) which may solve the issue.

**Comment by 820465323** [comment]
thanks so much, JavaScript debugger can solve my problem.
but I'm giving lanuch.json When trace: true is added, the output log does not change.  
In addition, I found another method. Running egg debug first, and then running egg attach can also return to normal

The configuration file is as follows
**  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Egg Debug",
      "runtimeExecutable": "npm",
      "runtimeArgs": [
        "run",
        "debug"
      ],
      "console": "integratedTerminal",
      "restart": true,
      "protocol": "inspector",
      "port": 9229,
      "autoAttachChildProcesses": true
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Egg Attach",
      "localRoot": "${workspaceRoot}",
      "remoteRoot": "${workspaceRoot}",
      "address": "localhost",
      "protocol": "auto",
      "port": 9999
    }
  ]**

But why can't I bring the -- inspect brk to work?
It can be started normally before I upgrade Ubuntu 20

**Comment by connor4312** [comment]
> but I'm giving lanuch.json When trace: true is added, the output log does not change.

With trace:true, the location of the log will be printed in the debug console -- please share that file 🙂

**Comment by 820465323** [comment]
[debugadapter-legacy.txt](https://github.com/microsoft/vscode/files/4718463/debugadapter-legacy.txt)

**Comment by 820465323** [comment]
@connor4312

**Comment by connor4312** [comment]
Thanks, cc @roblourens

**Comment by roblourens** [comment]
If the new Javascript Debugger solves this for you, I recommend sticking with that, it will become the default very soon. Thanks for trying it!
