### ISSUE TITLE
screen cheese while previewing icon theme

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#99032]
Testing #98019

* use no icon theme
* pin some tabs
* open icon theme picker and arrow up/down some candidates
* while previewing there is screen cheese when going from no icons to icons and reverse

<img width="277" alt="Screenshot 2020-06-02 at 11 34 58" src="https://user-images.githubusercontent.com/1794099/83504910-5fbdac80-a4c5-11ea-9f7d-aebacde11c26.png">
<img width="469" alt="Screenshot 2020-06-02 at 11 35 14" src="https://user-images.githubusercontent.com/1794099/83504915-60eed980-a4c5-11ea-87e6-8a7cf0d0dd77.png">

**Comment by bpasero** [comment]
I feel this is a bug on the theme layer: even though we seem to be applying CSS classes when you navigate over themes or icons, we do not change the setting or emit any event. So we are only lucky that it works ok in most places but here I really need an event to react to properly: pinned tabs switch between showing icons or first letter and that is not something I can easily express using CSS rules. 

I suggest to either introduce an event that everyone can adopt or change the setting value on the fly to get the correct result.
