### ISSUE TITLE
Splitting from a pinned editor, pins editor

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#99035]
Testing #98019

* pin an editor
* split editors
* editor is also pinned in the new group
* 😕 it's now pretty hard to dismiss the group
* 😕 it's confusing that I can unpin the editor in the new group and that it has no effect on the original group. Not clear if they are linked or not

**Comment by bpasero** [comment]
This is intentional, when splitting an editor we always try to preserve as much state as possible, and pinned state is one of it. I would like to hear back from more people if this is working fine for them or if this should change.

Maybe @Tyriar has a thought who I think is using this feature.

**Comment by jrieken** [comment]
I think the auto-pin behaviour in combination with https://github.com/microsoft/vscode/issues/99037 makes this really hard to work with, e.g easily end up with editor groups that cannot easily get rid off anymore

**Comment by Tyriar** [comment]
I would expect the new editor after a split to not be pinned, regardless of whether the original was. To me a second editor group is always a temporary thing, so pinning there is just an inconvenience. Also having multiple of the same file pinned doesn't seem very useful.

**Comment by bpasero** [comment]
Pushed a change that pinned state is only preserved if an editor is moved to another group, but not copied, which is what happens when you split an editor.
