### ISSUE TITLE
Close All doesn't close pinned editors

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#99037]
Testing #98019

* pin a few editors
* run Close All from the editor overflow title menu
* pinned editors are still there, it seems I need to unpin editors individually to dismiss them

**Comment by bpasero** [comment]
Yes, that is intentional. You can only close pinned tabs explicitly on the tab. 

![image](https://user-images.githubusercontent.com/900690/83536257-44699600-a4f3-11ea-9ba5-669f6048bae6.png)
