### ISSUE TITLE
Sash size setting: be more descriptive

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#99034]
Testing #99016

A suggestion to be more verbose in the sash size description to tell the user what sashes are and where they are used. E.g. put in views, panels, etc.

**Comment by gregvanl** [comment]
I agree, I don't know what this setting does. I set it to 20 and didn't notice any UI change.
Also what are the units, are they pixels?

**Comment by gregvanl** [comment]
Oops, didn't mean to close. I twitched.

**Comment by gregvanl** [comment]
I see now. There isn't a static UI change. The setting increases the width/height of the sash proximity region where the user can drag to resize an element.
Joao's proposed description makes sense.

**Comment by lszomoru** [comment]
Based on feedback from the `ux` channel we settled on the following. Hopefully this make it more clear:

> This controls the feedback area size in pixels of the dragging area in between views/editors. Set it to a larger value if you feel it's hard to resize views using the mouse.

**Comment by lszomoru** [comment]
Fixed in 505389caae9db1d1e34a55618152e1f42f83c083
