### ISSUE TITLE
Receiving notifications from uninstalled extension (advertising / Quokka)

### ISSUE THREAD

**Issue by madrussa** [microsoft/vscode#99030]
- VSCode Version: 1.45.1
- OS Version: Macos 10.15.4

Steps to Reproduce:

1. Install Quokka extension
2. Uninstall Quokka extension
3. Wait for notification from Quokka extension

Does this issue occur when all extensions are disabled?: Unknown

I uninstalled the Quokka extension due to the annoying notifications offering 40% off all the time. I would expect that this would stop the extensions from notifying me however this wasn't the case. 

There is an option to "Manage Quokka extension" using the gear icon, but clicking this doesn't do anything. 

Listing @enabled and @installed doesn't list Quokka as an extension.

An IDE should be free from annoyances so you can develop without distraction, even if it is free. The advertising should be kept within the marketplace and there should be rules around using notifications for promotions and advertising.

**Comment by connor4312** [comment]
>Does this issue occur when all extensions are disabled?

Please give this a shot. You can test this by launching code via `code  --disable-extensions`. It sounds like there's an extension lying around which is causing this.

/needsMoreInfo

**Comment by IllusionMH** [comment]
> 2. Uninstall Quokka extension
> 3. Wait for notification from Quokka extension

I think when you uninstall Quokka extension you should see "Reload required" button in extension.
Have you seen it and pressed before notification appeared?

**Comment by madrussa** [comment]
I'd restarted my Mac for updates between uninstalling the extension and receiving the notifications. It could be that Macos restored the complete session state when reopening the app... This issue is very hard to replicate as the notifications didn't appear often.

I'll close for now and reopen when I get another, I'll also take some screenshots and provide more info on all my installed extensions etc.
