### ISSUE TITLE
Notification to try editor.renameOnType feature is not shown 

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99045]
Testing #98901

Followed the steps from the test plan item 

- Install the  Auto Rename Tag extension (https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag)
- Ensure that the `editor.renameOnType` is not yet enabled 
- open a few HTML file

🐛 No notification showed up

**Comment by aeschli** [comment]
Did you open more than one html editor?

**Comment by sandy081** [comment]
Yeah I opened multiple.

It seems I got the notification once and I reloaded / restarted because of an update. I did not see the notification thereafter

**Comment by aeschli** [comment]
Start with a fresh user-data-dir.
You probably already saw it, it only shows once.

![image](https://user-images.githubusercontent.com/6461412/83507728-3a32a200-a4c9-11ea-96f0-438fa898882a.png)

**Comment by sandy081** [comment]
Yes, I confirm that this notification is shown only once and I won't be aware of this feature if I dismiss this notification for some reason and I reload the window. If it is important to allow users switch to built in feature why not show it always and have an `Do not show again` action?

**Comment by aeschli** [comment]
To only show a hint one time  was the feedback I got with the semantic highlighting notification. 

>  If it is important to allow users switch to built in feature why not show it always and have an Do not show again action?

No, it's not that important.
