### ISSUE TITLE
Provide setting to not show read-only full settings buffer when opening Settings

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9904]

**Comment by bpasero** [comment]
While this would maybe fix your selfhosting issue, isn't this a workaround for the real fix to work on a better settings UI?

**Comment by joaomoreno** [comment]
Yes, but until then let's just have this. It's not even about selfhost... I just want to open my settings without going into two pane mode (which I'm rarely on).

**Comment by bpasero** [comment]
@joaomoreno would this setting also apply for keybindings?

**Comment by joaomoreno** [comment]
Hm good question. I wouldn't know what to call it if so... But if separate, something in the lines of:

- `settings.openDefaultSettingsEditor`
- `keybindings.openDefaultKeybindingsEditor`

**Comment by bpasero** [comment]
Prefixed with our already established workbench category this would boil down to
* `workbench.settings.openDefaultSettingsEditor`
* `workbench.keybindings.openDefaultKeybindingsEditor`

**Comment by bpasero** [comment]
Added `workbench.settings.openDefaultSettings` for now since this is the bigger pain point.
