### ISSUE TITLE
Pinned editors are often indistinguishable

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#99044]
Testing #98019

* open and pin `vscode.d.ts` and `vscode.proposed.d.ts`
* there is no way to tell them apart 
* :confused: Not sure what I should do in this scenario. 

<img width="196" alt="Screenshot 2020-06-02 at 11 54 35" src="https://user-images.githubusercontent.com/1794099/83506737-d78cd680-a4c7-11ea-98c8-135364de5e40.png">

**Comment by bpasero** [comment]
Yeah, https://github.com/microsoft/vscode/issues/98161 is there to discuss other options.Marking as duplicate.
