### ISSUE TITLE
New issue editor not restored correctly

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#99040]
Testing #98019

* open and pin vscode.d.ts, vscode.proposed.d.ts, and NewIssue.md, open another file
* reload window
* select the 'N' editor
* an error about a missing file system provider happens (not sure if that's because of a missing activation event or because the event isn't fired)

**Comment by alexr00** [comment]
It looks like the file system provider is just registered too late in the extension. The extension already *-activates, but I can also add an `onFileSystem` activation if the editor looks for that. I'll also move the registration up.

**Comment by bpasero** [comment]
@alexr00 can you check if this reproduces independently from the editor being pinned, I would not expect that to have any impact.

**Comment by alexr00** [comment]
It is independent of pinning.

**Comment by lramos15** [comment]
There's no longer an error, but newIssue.md is blank after reloading the window. I'm not sure what the expected behavior is. I'm going to reopen this for now as I would still classify that as not restoring correctly, but feel free to close this if this was intended.

**Comment by alexr00** [comment]
It's intended, as the state of the repo may have changed since the file was created in VS Code.
