### ISSUE TITLE
Git: abort rebase command should only be available while I am rebasing

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#99048]
Testing #99015

Currently the command is always in the command palette. I would expect it to appear only when I am in the middle of a rebase.
Not sure if we could introduce some context keys which would be true when we are in the middle of the rebase. And then use those context keys as part of the commands `when` clause

**Comment by isidorn** [comment]
Since triggering it outside of a rebase produces this expected error.
Do we polish the message, since it looks a bit strange with the double `:`
![Screenshot 2020-06-02 at 12 18 51](https://user-images.githubusercontent.com/1926584/83509145-46b7fa00-a4cb-11ea-988a-339010b2f3ed.png)

**Comment by lszomoru** [comment]
Verification steps:
- Launch VS Code and close existing folder if needed
- Verify that `Git: Abort Rebase` command is not available in the command palette
- Open a Git repository
- Verify that `Git: Abort Rebase` command is not available in the command palette
- Switch to the SCM viewlet, and click on  `...` -> `Commit` -> `Abort Rebase`
- Verify that an information notification is displayed noting that there is no rebase in progress
- Use the steps from https://github.com/microsoft/vscode/issues/99015 to rebase a topic branch on top of the main branch 
- Verify that `Git: Abort Rebase` command is available in the command palette
- Invoke the `Git: Abort Rebase` command from the command palette
- Verify that `Git: Abort Rebase` command is available in the command palette
