### ISSUE TITLE
Closing inactive editors will still update breadcrumb

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#99041]
Testing #98019

* see attached GIF
* open and pin an editor, make sure it has breadcrumbs
* press `cmd+w`
* editor stays but breadcrumbs flash

![Jun-02-2020 11-49-24](https://user-images.githubusercontent.com/1794099/83506256-356cee80-a4c7-11ea-989b-386d1e3e4660.gif)

**Comment by bpasero** [comment]
@jrieken hm, `Cmd+W` at least should always close an editor, even if pinned. Did you assign anything special to `Cmd+W`?

**Comment by jrieken** [comment]
Yeah, looks like I have "close group"

<img width="1054" alt="Screenshot 2020-06-02 at 13 55 11" src="https://user-images.githubusercontent.com/1794099/83517156-af59a380-a4d8-11ea-8896-ee3bf8517585.png">

**Comment by bpasero** [comment]
@jrieken that would explain it, and is covered by https://github.com/microsoft/vscode/issues/99037

I can look why the breadcrumb flickers, that seems wrong to me.

**Comment by bpasero** [comment]
It looks like we would update breadcrumbs even if no editors are closing, I fixed that with https://github.com/microsoft/vscode/commit/64955f13910a2ce8e04055e33400ec41aa78b43a

Looking at https://github.com/microsoft/vscode/blob/64955f13910a2ce8e04055e33400ec41aa78b43a/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L430 we still might have cases where we call `updateBreadcrumbsControl` even if the editors that close are not the active one. Leaving that up to you to clean up, e.g. maybe this should only call when the active editor is part of the ones to close.

**Comment by jrieken** [comment]
I would need to know if the active tab was closed or not but it seems that `this.group.activeEditor` is already set to the new, active editor when reaching this code: https://github.com/microsoft/vscode/blob/e6470a9752007b1a0aa5552b007560732ac67ec5/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L385

@bpasero Am I missing something or this this too far down the line?

**Comment by jrieken** [comment]
nvm - looks like `openEditor` is called always before close (when closing a single tab) and then breadcrumbs are already updated. Only when closing all tab special breadcrumb updating is needed...

**Comment by bpasero** [comment]
@jrieken `closeEditors` may also be called without the active one being included, e.g. "Close Others". How about this code:

```ts
closeEditors(editors: IEditorInput[]): void {
	this.handleClosedEditors();

	if (this.group.activeEditor && editors.indexOf(this.group.activeEditor) !== -1) {
		this.updateBreadcrumbsControl();
	}
}
```

To make sure breadcrumbs update when the list of closed editors includes the active one. I can see that reduces flicker when running "Close Others".

**Comment by jrieken** [comment]
For `closeEditor` I see the same. Once the call reached me, the active editor is already updated and hence never in the list closed editors. Meaning, I'd never update the breadcrumbs here... Tho, it might be enough to only update the breadcrumbs when no more editor is around (which means hide breadcrumbs)
