### ISSUE TITLE
Provide an action to enable built in auto rename feature from notification

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99046]
Testing #98901

<img width="490" alt="image" src="https://user-images.githubusercontent.com/10746682/83507730-3b63cf00-a4c9-11ea-9cad-0acf37547e89.png">

Why not have an action to enable instead of an action to open the settings editor and showing the setting. Also as an user it was not clear to me how this setting is associated to auto renaming tags. 

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/10746682/83507924-7c5be380-a4c9-11ea-968e-0aa7c77058a8.png">

**Comment by aeschli** [comment]
That way the user learns how to enable/disable it.
No changes planed.
