### ISSUE TITLE
Searching for a string OR its prefix (with | operator) won't find the whole string, only its prefix

### ISSUE THREAD

**Issue by devnoel** [microsoft/vscode#99055]
Issue Type: <b>Bug</b>

**Reproduction steps:**

Write "Sia" in a file.
Write "SiaLabrinthDiplo" in the next line.
Search for `Sia|SiaLabrinthDiplo` (regexp search enabled).

Matches:
[Sia]
[Sia]LabrinthDiplo

The worst part: enable the "Match Whole Word" feature, and SiaLabrinthDiplo is entirely excluded from the results:
[Sia]
SiaLabrinthDiplo

If the order in the search field is reversed (`SiaLabrinthDiplo|Sia`), the matches become correct:
[Sia]
[SiaLabrinthDiplo]

This applies to the local and the file system search as well.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.3.0-51-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3099)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.66GB (1.28GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
gitlens|eam|10.2.1
vue-inline-template|fai|1.0.1
debugger-for-chrome|msj|4.12.8
vetur|oct|0.24.0
material-icon-theme|PKi|4.1.0
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by connor4312** [comment]
This is working as expected -- regex engines will take the first match, which in this case is `Sia` in both cases.
