### ISSUE TITLE
Drop feedback for empty panel is a bit weird

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#99052]
I would suggest to show the blue drop feedback over the entire panel, and not have that space to the top excluded.

![recording](https://user-images.githubusercontent.com/900690/83510931-1f166100-a4ce-11ea-89a4-49268661be3b.gif)

**Comment by sbatten** [comment]
I made it like this to there to avoid conflict with the panel close action and to match the area it normally covers

**Comment by bpasero** [comment]
I understand, but visually it just looks slightly broken to me. I think the entire area of the panel should be the drop area because that is the logical container I am dropping something into.

**Comment by bpasero** [comment]
This is even more evident when comparing with editor drop: if the editor area is empty, the drop feedback goes over the entire area:

![Image](https://github.com/user-attachments/assets/07b5ff01-d156-4021-aa3f-512f973964f7)

**Comment by bpasero** [comment]
Thanks!!
