### ISSUE TITLE
Setting `debug.console.closeOnEnd` does not work after debug console was moved

### ISSUE THREAD

**Issue by Fell** [microsoft/vscode#99050]
Issue Type: <b>Bug</b>

1. Set up an environment that makes use of `debug.console.closeOnEnd`
2. Click and drag the debug console somewhere else, for example in the side bar or the panel.
→ `debug.console.closeOnEnd` does not work anymore
3. Move the debug console back where it was
→ `debug.console.closeOnEnd` _still_ does not work

I found out, that the debug console is in a "dirty" state as long as the right click option "Reset View Location" is available. When I click "Reset View Location", said option disappears and the functionality of `debug.console.closeOnEnd` is restored. 
However, this is very confusing as there is no visual clue as to why the debug console does not close. 
At least add this to the description of the setting.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
increment-selection|alb|0.2.0
vscode-perforce-simple|cal|1.0.1
gltf-vscode|ces|2.2.10
vscode-icon-theme|jtl|1.6.6
cpptools|ms-|0.28.2
shader|sle|1.1.4
rewrap|stk|1.11.1
sort-lines|Tyr|1.9.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
I acklowedge this bug and we can look into it.
Code pointer https://github.com/microsoft/vscode/blob/05e851b52978f08a7d7780feeff26a121e31c0d1/src/vs/workbench/contrib/debug/browser/debugService.ts#L600

**Comment by Fell** [comment]
It works as expected now, however, I miss the old functionality that closed the whole panel after debugging. I created a feature request: https://github.com/microsoft/vscode/issues/100182
