### ISSUE TITLE
VSC doesn't connect to DevTools

### ISSUE THREAD

**Issue by LillaNemeth86** [microsoft/vscode#99057]
Hello,

I am writing to you because I changed some setting in DevTools because the changes I made in it did not come up in VSC as well. I made the change in the Sources panel Overrides tab Folder for Overrides, chose the directory allowed DevTools to read and write access to the directory and now if I open my html file in the Live Server it is different from the work I had done. It may be in connection with a permission issue.

Please let me know how I could fix this.

Have a lovely day,

Lilla

**Comment by connor4312** [comment]
I believe the source overrides in the devtools are stored only in Chrome and aren't persisted anywhere. It may be possible to get them to save on disk, but I haven't tried that personally. Regardless it sounds like this is more an issue in the devtools than with vscode -- StackOverflow or other sites might be able to provide you more relevant help.

/question
