### ISSUE TITLE
Remove unused is pretty aggressive in error cases

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#99059]
Testing #98997

```ts
function foo(x: number): void {
}

foo('dirk');
```

You get

```ts
function foo(): void {
}

foo();
```

In error cases it is IMO not clear what the intended behavior is and we should at least check with the user.

**Comment by dbaeumer** [comment]
Not so problematic but still
```
class A {
	constructor(x: number) {
	}
}

new A('dirk');
```

In general errors on the calling side should

**Comment by dbaeumer** [comment]
Another example:

```ts
function foo(x: number): void {
	xx = 10;
}

foo(20);
```

**Comment by mjbvz** [comment]
This source action is supposed to match the behavior of the existing  `delete all unused declarations` quick fix:

<img width="472" alt="Screen Shot 2020-06-02 at 11 58 33 AM" src="https://user-images.githubusercontent.com/12821956/83558781-6568c180-a4c8-11ea-8497-fca535e39536.png">

You can test this with the following code:

```ts
function foo(xx: number): void {
	xx = 10;
}
foo(20);

const z = 1;

export const _ = 1;
```


I'm going to close this as by-design
