### ISSUE TITLE
Collapse previewed file's folder when closing previewed file

### ISSUE THREAD

**Issue by kaylfc** [microsoft/vscode#99058]
Issue Type: <b>Feature Request</b>

Hey guys,

I opened a file (let's say `index.js`) from the Ctrl+P menu and saw it in preview mode (italicised file name). I had the Explorer menu open and saw the file's folder (let's say `server/`) open to reveal my previewed file.

I then closed the previewed file, and `server` remained open to show `server/index.js` inside.

It might be an idea to collapse this folder in this scenario, as after closing the previewed file I'm basically discarding it, so it's containing folder(s) is now irrelevant.

Thanks!

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
