### ISSUE TITLE
shift+cmd+3 is not performing sort descending operation on lines

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#9905]
- VSCode Version: 1.4 insiders (6ef86d5f85a531caa59bfb1715469fcfaa8d2efd)
- OS Version:OSX

Steps to Reproduce:

1. Select some lines in a file and type <kbd>shift</kbd>+<kbd>cmd</kbd>+<kbd>3</kbd>

Expected: Lines should be sorted descending
Actual: Nothing happens

**Note:** Sort descending happens if select the command from pallette. Also <kbd>shift</kbd>+<kbd>cmd</kbd>+<kbd>2</kbd> works properly.

**Comment by kieferrm** [comment]
@sandy081  On a Mac <kbd>shift</kbd>+<kbd>cmd</kbd>+<kbd>3</kbd> by default is bound to taking a screenshot of your whole screen.

![screen shot 2016-07-28 at 11 44 19 am](https://cloud.githubusercontent.com/assets/4674940/17225187/c23e71ca-54b8-11e6-8b35-ddef9136e82e.png)

When you reassign another keybinding to the action, it works.

So, out of the box there should be a different keybinding.

**Comment by alexandrudima** [comment]
I can remove the out-of-the-box keybinding.
