### ISSUE TITLE
Editor drop overlay not going away

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#99065]
Testing #98995

I don't have much to go on here but while testing this issue the editor drop overlay would not go away. I think it happened shortly after pressing escape instead of releasing the mouse to drop the drag, then opened devtools.

![image](https://user-images.githubusercontent.com/2193314/83516410-d938a900-a48b-11ea-8687-5b1e5698d4e4.png)

**Comment by sbatten** [comment]
I am not sure I can do much with this one if its repro involves dev tools. I haven't gotten it to trigger

**Comment by Tyriar** [comment]
I saw it trigger a few times while trying to reproduce https://github.com/microsoft/vscode/issues/99067, I'm guessing some event is missing or something. As an extra protection to prevent completely breaking the editor group could you add a click listener to the drop areas that deactivates it?

**Comment by sbatten** [comment]
@Tyriar will be hard to verify but I'll leave it to you. I tested by removing the line that hides it onDragEnd

**Comment by Tyriar** [comment]
Cannot reproduce what I was seeing before.
