### ISSUE TITLE
Reopening editor loses UI state

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#99061]
Testing #97578

Repro:

1. Manage trusted domains command (jsonc active)
2. Close tab
3. ctrl/cmd+shift+t to restore tab (plain text active)

**Comment by JacksonKearl** [comment]
@bpasero any ideas here? Editor is opened like:
https://github.com/microsoft/vscode/blob/f63f3bdd3fa448dbc3a58147b7d36883ba544156/src/vs/workbench/contrib/url/browser/trustedDomains.ts#L34

**Comment by bpasero** [comment]
This is probably currently not supported from this feature, e.g. we record only the resource and location of the editor, but none of its properties:

https://github.com/microsoft/vscode/blob/f48cb619ba9f1d7e8a0d1b150cbdfa42577ec6a8/src/vs/workbench/services/history/browser/history.ts#L620

Could we somehow register a file association pattern by default that would associate this resource with the `jsonc` mode? That would ensure it always has this mode.

**Comment by JacksonKearl** [comment]
Where would that happen? We could ideally go by scheme or potentially path. 

`const TRUSTED_DOMAINS_URI = URI.parse('trustedDomains:/Trusted Domains');`

**Comment by bpasero** [comment]
@aeschli might know how we could teach `jsonc` about trusted domains.

**Comment by aeschli** [comment]
It could work by adding `Trusted Domain` to the list here: https://github.com/microsoft/vscode/blob/master/extensions/configuration-editing/package.json#L42

A URL would be better, but not sure if that's supported for `filenames`

Also, we could also solve this by renaming the URI to `trustedDomains:/Trusted Domains.jsonc`

**Comment by Tyriar** [comment]
> This is probably currently not supported from this feature, e.g. we record only the resource and location of the editor, but none of its properties:

@bpasero why not retain the language mode as well. This seems like a good thing generally and a better than hardcoding it into the jsonc config.

**Comment by bpasero** [comment]
Fine with me, if someone is willing to do a PR. There is probably more UI state to preserve, e.g. encoding as well. View state should be fine though.

**Comment by bpasero** [comment]
This should work fine now given https://github.com/microsoft/vscode/commit/1eac96d162f7ab7792e271e6dad12cf1ef31a29b

Reopening closed editors is now going through the full editor input factory which will preserve selected mode and encoding.
