### ISSUE TITLE
Web upload: hierarchical selections result in duplicated objects

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#99060]
Refs: #97714

- have a folder with two or more files
- in the OS open the folder in a view that shows the folder and its contents hierarchically
- select the folder and one of the files contained
- drag and drop this into the VS Code explorer

Observe:
the file is copied twice: once as part of the folder (which is correct) and another time outside of the folder.

![2020-06-02_13-20-59 (1)](https://user-images.githubusercontent.com/1898161/83514479-03ae5480-a4d4-11ea-834d-d6f29d01cbf8.gif)

IMO the correct behavior is to ignore the selected file in the copy because it is already part of the containing folder. (That is the behavior the macOS Finder implements).

**Comment by bpasero** [comment]
I may not be able to figure that out, but will have a look.

**Comment by isidorn** [comment]
@bpasero I suggest that on drop we simply filter over the dragged resources and filter out the ones which are ancestors of one another using [`isEqualOrParent`](https://github.com/microsoft/vscode/blob/595d2b9b916d063aadfc2c1a8c8f6df5b45572a8/src/vs/base/common/resources.ts#L51)
If you like this idea I can create a PR.

**Comment by bpasero** [comment]
@isidorn yeah sounds good, thanks

**Comment by isidorn** [comment]
Tried it out and actually can not do it, reason being the API we are using is only giving us the name not the full path before the streaming starts
And just using the name we can not de-dup. 
Thus moving this to backlog 

![Screenshot 2020-06-03 at 13 59 11](https://user-images.githubusercontent.com/1926584/83634231-75ed6a80-a5a2-11ea-8a54-41111d08ad94.png)

**Comment by bpasero** [comment]
I actually see no way at all to do this because as far as the browser seems to be concerned these 2 files are independent from each other. The hierarchy is only something we make up when walking the folder, but not something the file that is being dropped carries.
