### ISSUE TITLE
Web upload: uploading folder with lots of files loses many in Chrome and Edge

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#99068]
Refs: #97714

- prepare a folder with lots of files with filenames where you can easily detect missing files (I was using a 4GB folder will 2000 sequentially numbered photos).
- drag and drop into Web VS Code's file explorer

Observe: with Chrome and Edge the operation finished quickly but only about 100 photos were uploaded. In Safari and Firefox the upload took much longer but I could not find missing files.

I think the total size of the files doesn't matter, but the number of files is important.

**Comment by bpasero** [comment]
Maybe not under our control, but I will check.

**Comment by isidorn** [comment]
Sounds like a Chromium issue since you can repro in Chrome and Edge and not in Safari and Firefox.
@weinand can you also reproduce this behavior if you for example drop your files to some other web application, for example Gmail?

**Comment by weinand** [comment]
I'm not using gmail.

**Comment by bpasero** [comment]
I was able to upload 1000 1byte files, so I think the limit may be size based and not count based, but have not fully figured it out yet. Used https://stackoverflow.com/questions/17034941/how-to-create-multiple-files-with-random-data-with-bash to create many small files.

**Comment by weinand** [comment]
The size of my photo files was around 100-400 kB.

**Comment by bpasero** [comment]
Learnt something: https://stackoverflow.com/a/23823587/4851043

**Comment by weinand** [comment]
Wow, that explains why I always saw about 100 uploaded files.
Good find!

**Comment by weinand** [comment]
uploading 12000 files with a total size of 4 GB works fine now.
