### ISSUE TITLE
Not clear what a "panel section" is from the new theme key descriptions

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#99069]
Testing #98995

![image](https://user-images.githubusercontent.com/2193314/83517066-19e4f200-a48d-11ea-866c-d4a9b47ba6b0.png)

**Comment by Tyriar** [comment]
Also I thought these were called views? Why use a different name, won't we have another sidebar/viewlet situation?

**Comment by sbatten** [comment]
I tried to remain consistent with the side bar because I don't want to break those theme keys

**Comment by sbatten** [comment]
Add some clarifying text since we don't want to change the key names
