### ISSUE TITLE
Maximizing while devtools is opened 

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#99067]
Testing #98995

Related: https://github.com/microsoft/vscode/issues/99065

Repro:

1. Drag terminal into output and into the left portion of it
2. Press escape instead of dropping
3. ctrl+shift+i for devtools
4. Press the maximize button

![recording (1)](https://user-images.githubusercontent.com/2193314/83516827-a642e500-a48c-11ea-801f-105cab5cc60e.gif)

**Comment by sbatten** [comment]
I cannot repro any behavior that looks like a bug based on those steps though I don't fully understand what the described bug is

**Comment by Tyriar** [comment]
@sbatten when the window is maximized, the electron window dimensions don't change, that small sliver is the entire window, no more activity bar, not more minimize/maximize/close buttons are visible.

**Comment by sbatten** [comment]
I cannot reproduce this but it sounds like an electron issue since that button press is just a call to electron API

**Comment by rzhao271** [comment]
@Tyriar does this issue still apply in the latest Insiders?
The appearance of the devtools has changed when they are docked to the right side.

**Comment by Tyriar** [comment]
I can't remember seeing this since it happened that day 🙂
