### ISSUE TITLE
Code completion does not work on third party JavaScript modules

### ISSUE THREAD

**Issue by MeguminSama** [microsoft/vscode#99077]
- VSCode Version: 1.45.1 (user setup)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:
(using example library)
1. require the npm module in an index.js file
2. instantiate the constructor to a variable (completion shows)
3. attempt to use that variable (no code completion shows)

Does this issue occur when all extensions are disabled?: Yes

Example code:
```js
const Eris = require('eris');
let bot = new Eris(""); // code completion works here
bot.on('.....'); // code completion does not work when typing "bot."
```

This issue only seems to affect npm modules, native modules and local files work fine.

**Comment by MrJacz** [comment]
Does eris have typings?

**Comment by MeguminSama** [comment]
> Does eris have typings?

Yes, it does have typings. I've tried restarting vscode and the TS server but it didn't change anything.

Code suggestions work fine in other editors also

**Comment by MeguminSama** [comment]
I should note this is a common problem I've experienced over the span of (probably more than) a year. My PC has been reset multiple times in this time, so I doubt it's a problem with my setup. It seems to occur completely randomly and when it happens, most npm modules will lose their code suggestions completely.

**Comment by mjbvz** [comment]
The `eris` typings appear to be wrong. If you run `go to definition` on `Eris` in `new Eris`, it jumps to:

```
declare function Eris(token: string, options?: Eris.ClientOptions): Eris.Client;
```

instead of to a constructor.

Try filing an issue against  `eris` to start. If this turns out to be a TS issue, they can follow up on the typescript repository
