### ISSUE TITLE
Rename input should be populated with old name

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#99078]
Testing #98962

In the synced machines view, press Edit next to a machine name. I would expect for the old name to appear populated and selected in the input, but currently the input shows empty:

![image](https://user-images.githubusercontent.com/5047891/83520200-956e8f80-a4dd-11ea-9df0-257ccd1c92b2.png)

**Comment by sandy081** [comment]
Fixed by d469683f794baf9d462bf587648cf245f4e9469d
