### ISSUE TITLE
Intellisense is not working when I type . in settings files

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#9907]
- VSCode Version: 1.4 insiders (6ef86d5f85a531caa59bfb1715469fcfaa8d2efd)
- OS Version:OSX

Steps to Reproduce:

1. Open settings
2. Type `git`
3. You see suggestions - Good
4. Type `.`
5. **Bug:** Suggestions go away

Expected: Suggestions remain

**Comment by aeschli** [comment]
Regression from my change to the JSON word rule.
