### ISSUE TITLE
Explorer: better experience for replacing and merging folders

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#99074]
Refs: #97714 

- have a folder with a few files
- drag and drop into web file explorer
- drag and drop the folder again

Observe:
Multiple dialogs appear that ask whether to replace the existing files/folder:
- first for the folder
- then for the individual files

From this behaviour I assume that the drag and drop is not a "replace" but a "merge".
This is confirmed by adding another file into the original folder and then dnd it again.
Or empty the original folder and then dnd it only asks for the folder but leaves the existing containing files alone.

But this "Merge" semantics needs a completely different UI than "Replace":
- it is not necessary to ask for replacing the folder because there will be more questions for the individual files inside anyways.
- the dialog needs three buttons: "replace", "do not replace", and "cancel"

Alternatively you could implement the "Replace" logic. In this case there is no need to ask for the individual files inside a folder if the whole folder is replaced anyway.

A third option is to ask initially whether to "Replace" or to "Merge" and then have different UI for the two strategies.

**Comment by bpasero** [comment]
Will check how the explorer does this, we may behave the same already for native drops.

**Comment by weinand** [comment]
The simplest solution is to implement the "Replace" strategy. That's what macOS Finder does.
IIRC Windows implements the "Merge" strategy.

**Comment by isidorn** [comment]
Yes this is also how our non web explorer behaves. So we will show a dialog for each conflict. We do not allow to bulk cancel.
Since this can be handled in the Explorer, unassigning from @bpasero and renaming

I am opening this up for PRs.
Code pointer

https://github.com/microsoft/vscode/blob/595d2b9b916d063aadfc2c1a8c8f6df5b45572a8/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L707

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/64dbafe1d374b9bc61330ca5a385e7e5df205bfc the solution is to ask for each thing that gets uploaded and then delete it upfront. This means, when you are being asked to replace a folder, you will not be asked for each file within. It will be a "Replace" and not "Merge".
