### ISSUE TITLE
What does panelSectionHeader.border do?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#99070]
Testing #98995

I have this set:

```
"panelSectionHeader.border": "#ff0000",
```

Isn't there meant to be a border around the section headers?

![image](https://user-images.githubusercontent.com/2193314/83517325-8fe95900-a48d-11ea-80d5-5588c570d881.png)

**Comment by Tyriar** [comment]
Ok, I figured it out, it depends on orientation. Why not just use `panelSection.border`? Same with sideBar.

**Comment by sbatten** [comment]
`panelSection.border` is necessary to split 2 views in horizontal layout
`panelSectionHeader.border` is optional since the header is already a separator

Just because you want one does not mean you want the other.

**Comment by Tyriar** [comment]
Along the same lines as https://github.com/microsoft/vscode/issues/99069, the doc should be more specific. I had to guess/experiment to figure out what it actually did.
