### ISSUE TITLE
Settings sync - display error message when expanding nodes in the Synched data panel

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#99082]
Testing #98962

When disconnecting from the network, then I try to expand any of the nodes in the `Synched data` panel nothing is happening. We should improve our error handling so that an error is being displayed when trying to expand the nodes. We might also want to cache some of that information locally so that we do not always call the service to get it.

**Comment by sandy081** [comment]
Accepting this request for handling errors, but for caching - I see how it is helpful but since this feature (synced data views) is not a prominent feature and not much worth the value to provide this.
