### ISSUE TITLE
Settings sync - We should not sync unless there are changes

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#99087]
Testing #98962

I have two machines (SurfaceLaptop, MacBook) that I have set up with settings sync:
- Both machines were in sync
- Update one setting on the SurfaceLaptop. 
- The settings change got synched to the MacBook. Diff confirms that the setting that I changed on the SurfaceLaptop was pushed to the MacBook. 
- But then couple of minutes later the settings were synched to the SurfaceLaptop even though they are the same that are already on the machine. Diff shows no differences. Ideally we would want to have a mechanism to detect no-ops and not sync in case there are no changes.

![image](https://user-images.githubusercontent.com/3372902/83524895-893a0080-a4e4-11ea-948e-c6432fdf0b1a.png)

**Comment by sandy081** [comment]
@lszomoru From the pic it seems the latest sync happened from your `SurfaceLaptop` which triggered by the settings change you mentioned - `Update one setting on the SurfaceLaptop.`

We do not sync if there are no changes. 

Can you please double check?

**Comment by lszomoru** [comment]
I have tried to repro again and things are looking good. I just misunderstood what the `Synched Data` view was telling me.
