### ISSUE TITLE
Moving a pinned editor unpins it

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#99086]
Testing https://github.com/microsoft/vscode/issues/98019

Drag a pinned tab and drop it on a tab bar empty space. I expected it to remain pinned. 🤷

**Comment by bpasero** [comment]
@joaomoreno can you clarify, do you only have 1 pinned tab? In general, moving a pinned tab after the last tab will unpin it if that last tab is unpinned.

**Comment by joaomoreno** [comment]
> In general, moving a pinned tab after the last tab will unpin it if that last tab is unpinned.

You seem to distinguish between the last tab of the drop container being pinned or not. As a user, this doesn't make much sense, since my perception is that I'm dragging a pinned tab onto a container, so it should remain pinned, independently of what the state of the last tab of that container is.

**Comment by bpasero** [comment]
Well, my argument is that you are dropping a tab _after_ an existing tab of a tab group. Now I am in conflict: should the tab be pinned or should it be after the last tab. Pinned tabs cannot be after unpinned tabs (currently), so I can either respect the index of the tab (which I prefer) or the pinned state.

**Comment by joaomoreno** [comment]
Isn't a split different than a drag and drop? :think

**Comment by bpasero** [comment]
Yeah, fair point. Again, I am preferring to preserve the index, not the pinned state here. If you drop into an empty group, I preserve pinned state.

**Comment by joaomoreno** [comment]
@bpasero  🙈 

![recording (11)](https://user-images.githubusercontent.com/22350/83616719-7547da80-a588-11ea-89d0-64e6f486b38b.gif)

> POWERED BY GIFCAP

**Comment by bpasero** [comment]
@joaomoreno well that is just how Chrome behaves. I decided to do what Safari does which allows you to easily drag/drop tabs in and out of pinning state (which is something I heard from users is good to have).

![recording](https://user-images.githubusercontent.com/900690/83617915-0c616200-a58a-11ea-9784-996d4de6f394.gif)
