### ISSUE TITLE
Settings sync - Opening Preferences sync viewlet should refresh the list of machines

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#99088]
Testing #98962

After I have enabled settings sync on the second machine, I went back to the first machine and when I switched to the `Preferences Sync` viewlet, I had to manually hit the `Refresh` action in order to see the second machine on which I have enabled settings sync. We should automatically refresh the list of machines when the viewlet gets activated.

**Comment by sandy081** [comment]
Agreed its good to have the data refreshed automatically but these views are for advanced purposes like trouble shooting and administering. So its ok to click on refresh button to update the data. 

I see how it is helpful to have the data refreshed while testing but not an issue in real time scenarios. Hence I would not rush on this and moving this to backlog candidates.
