### ISSUE TITLE
WSL does not support paths needed in electron-main

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#99099]
Testing #98021

I tried: `code-insiders --crash-reporter-directory=~/tmp .`

**Comment by dbaeumer** [comment]
Actually I couldn't get code started with any `--crash-reporter-directory` setting when running in WSL.

**Comment by bpasero** [comment]
I think the more often case would be `--user-data-dir` for example.

**Comment by aeschli** [comment]
To verify:
- in the WSL shell run `code-insiders --crash-reporter-directory=~/tmp .`
- you should see an error message

**Comment by dbaeumer** [comment]
Verified. 

@aeschli But I would like to recommend that we rephrase the wording. Current:

> Ignoring option crash-reporter-directory: not supported for code-insiders.

I would point somehow to WSL since the feature is supported in general.
