### ISSUE TITLE
Code not trigger remove unused code on save

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#99095]
Testing #98997

Tried using the following id `source.removeUnusedCode`

**Comment by mjbvz** [comment]
Can you share a code example that causes this?

**Comment by dbaeumer** [comment]
I tried to trigger remove unused code on save but was not successful configuring it. What code example do you need?

**Comment by mjbvz** [comment]
I'd like to see what exactly the unused code is. This fix removes some cases of instances code, but does try removing all unused code

**Comment by dbaeumer** [comment]
@mjbvz it was one of the examples I used in the other issues I filed. https://github.com/microsoft/vscode/issues/99059, https://github.com/microsoft/TypeScript/issues/38900

**Comment by dbaeumer** [comment]
Is the id I used correct? `source.removeUnusedCode`

**Comment by dbaeumer** [comment]
Reopen since I think the necessary information is available.

**Comment by mjbvz** [comment]
Closing in favor of https://github.com/microsoft/TypeScript/issues/40922
