### ISSUE TITLE
Settings sync - Preferences sync gets turned on even though there are conflicts

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#99096]
Testing #98962

In case of a conflict I have chosen to resolve the conflicts by merging the settings. Even though there is still a pending conflict to be resolved, I see that the settings sync has been turned on the machine. Settings sync should only be turned on when the conflict has been resolved. 

![image](https://user-images.githubusercontent.com/3372902/83527720-71647b80-a4e8-11ea-9a86-6b9b17d92c8f.png)

**Comment by sandy081** [comment]
Conflicts status happens only when Sync is on. Sync is On entry is also a way to navigate to more necessary sync actions like turning off.

Also conflicts in settings does not need to stop syncing other resources like keybindings.
