### ISSUE TITLE
Tabs: Toggling `workbench.editor.showTabs` setting clears pinned state

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#99090]
Related to https://github.com/microsoft/vscode/issues/98019

I toggled the `workbench.editor.showTabs` and it cleared the pinned state, I wasn't expecting it to happen.

**Comment by bpasero** [comment]
@joaomoreno yeah doing that explicitly because we have no visual indication that a tab is pinned when you have tabs disabled. In general this feature requires tabs to work. Are you suggesting it should work with tabs disabled?

**Comment by joaomoreno** [comment]
No not really, just if it's low hanging. I don't think it's a useful scenario, let's close it.
