### ISSUE TITLE
Extensions put into wrong groups

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99098]
* using my "normal" code insiders
* using another instance via `code-insiders --user-data-dir ~/Desktop/data --extensions-dir ~/Desktop/data-ext`
* enabled settings sync and let it restart
* 😕 its extensions viewlet shows extensions as disabled that are enabled, eg the theme is the active/selected theme

<img width="657" alt="Screenshot 2020-06-02 at 15 15 47" src="https://user-images.githubusercontent.com/1794099/83524483-f7ca8e80-a4e3-11ea-9fb1-fd2d019527fb.png">

@jrieken FYI - Moved to public repo

**Comment by sandy081** [comment]
@jrieken I see this issue occurred to you but I am not able to repro it. 

If you are able to repro, can you please provide the steps again, may be the data you also used to sync?

**Comment by jrieken** [comment]
This happened right after starting to sync and it seems like it was changing while I was reporting the issue. I felt to me like a lack of lifecycle steps or something like it

**Comment by sandy081** [comment]
This might have happened because we do not automatically move extensions across groups when their state is changed. Here is the issue tracking that feature - https://github.com/microsoft/vscode/issues/100415. Hence marking this as dup
