### ISSUE TITLE
Pinned tabs: add a setting to control location of pinned tabs (left, right)

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#99091]
Testing https://github.com/microsoft/vscode/issues/98019

The `workbench.editor.openPositioning` setting makes me wonder if we should also control where pinned tabs are placed: left or right. This would work great for those users who place the sidebar on the right.

**Comment by bpasero** [comment]
Setting to candidates to see if more people ask for it, I think the idea makes sense.

**Comment by kanlukasz** [comment]
Great idea, It could look like this eg.:
![obraz](https://user-images.githubusercontent.com/30685349/85105191-52652980-b20a-11ea-8950-7df8706deefd.png)
