### ISSUE TITLE
Refresh synced machines view when sync is turned on

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#99097]
Testing #98962

When enabling settings sync on a machine, the machine should automatically be added to the `synched machines` list.

**Comment by sandy081** [comment]
I think it is added. May I know if it is happening otherwise? If so what are the steps to repro?

**Comment by lszomoru** [comment]
- If settings sync is enabled, disable it, and hit the refresh button in the `Synched Machines` list to clear out the entry
- Open the `Preferences Sync` viewlet
- Turn on sync for the machine

Expected: Current machine should appear in the `Synched Machines` list.
Actual: `Synched Machines` list is empty until the `refresh` action is clicked

**Comment by sandy081** [comment]
Yeah it is because, I do not have auto refresh for these views. May be I can make it smarter atleast for this case.

**Comment by sandy081** [comment]
Fixed by 6df1b061bfa6a1d274b943617081554cf0136764
