### ISSUE TITLE
Menu needs to be aware of what is going on inside current active workbench

### ISSUE THREAD

**Issue by gianugo** [microsoft/vscode#991]
If the editor has no files open, choosing Find or Replace from the menu doesn't do anything and doesn't warn the user that this functionality requires an open file. A feedback to the user along the lines of "please open a file first" would point out the EBKAC more explicitly.

(as an aside, I tried doing that in the hope I could find a global, project-wide replace - since a global search is there, I was hoping a global replace would have been there)

**Comment by egamma** [comment]
>(as an aside, I tried doing that in the hope I could find a global, project-wide replace - since a global search is there, I was hoping a global replace would have been there)

Sorry not yet, but it is on our Roadmap.

**Comment by alexandrudima** [comment]
@bpasero  Some entries in the Edit menu should be disabled if no editor is open:
* undo/redo
* cut/copy/paste
* select all, find/replace

**Comment by bpasero** [comment]
Marking as upstream for better menu API around enablement.

**Comment by bpasero** [comment]
Also: the "Additional viewlets" entry under the view menu needs to update depending on the active window.

**Comment by sbatten** [comment]
@alexandrudima there were other issues before (though newer than this issue) that suggested even more fine-grained updating of menu items which were closed because the menu would have to be aware of too much. If the request is just whether or not an editor is open, we have that context key already. Is there something I should be concerned about just using that key for enablement.

**Comment by alexandrudima** [comment]
@sbatten Please create a PR, I'm happy to review. When changing things in the editor, the only thing to be aware of is that we ship the editor standalone (outside of the workbench) and we should not assume workbench concepts in editor actions.

**Comment by sbatten** [comment]
fix addresses the OP's example. since different commands require different level of granularity for context keys, they should be grouped according to interest and technical requirements. that is why, given the age of this issue, I have stopped at the OP's suggestion.

**Comment by rzhao271** [comment]
1. Have VS Code open with no files open, try find/replace and get the warning message
2. Open a single non-empty file
3. The warning message is still there
4. Do a search where there's a result in the opened file, and the search results show up properly
5. Close that file and clear the search query, the warning message is gone even though no files are open now

I think it just has to do with file open/close events

**Comment by sbatten** [comment]
this issue only deals with `Find` and `Replace`  not `Find in Files` or `Replace in Files`
