### ISSUE TITLE
panelSectionHeader.background doesn't appear to change anything

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#99103]
Testing https://github.com/microsoft/vscode/issues/98995

What is the `panelSectionHeader.background` changing?

![image](https://user-images.githubusercontent.com/38270282/83529429-9e199280-a4ea-11ea-8a97-0a80807d22f7.png)

**Comment by alexr00** [comment]
Same for `panelSectionHeader.foreground`.

**Comment by alexr00** [comment]
And `panelSectionHeader.border`

**Comment by alexr00** [comment]
And `panelSection.border`

**Comment by tabaddor** [comment]
Can you be more specific? What are the steps to reproduce and what is the expected behavior?

**Comment by sbatten** [comment]
Repro Steps:
1. Reset View Locations
2. Move Terminal into Debug
3. Set `panelSectionHeader.*` theme colors

Verify the settings have an effect on the panel views

**Comment by alexr00** [comment]
I'm still not seeing this have any effect:
```
	"workbench.colorCustomizations": {
		"panelSectionHeader.border": "#ff0000"
	}
```
All the others work great now though!

**Comment by sbatten** [comment]
@alexr00 my guess is that you did not have the panel docked left or right. I've updated the description to be clear that it is only applicable when stacked vertically.

**Comment by eamodio** [comment]
@sbatten Why not apply the border to the left edge when horizontal?
