### ISSUE TITLE
Settings sync -LocalTooManyRequests (UserDataSyncError) undefined: Too many requests. 

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#99100]
Testing #98962

When the LocalTooManyRequests occurs we are writing an `undefined` object into the logs.

_

> [2020-06-02 15:56:57.315] [userDataSync] [error] LocalTooManyRequests (UserDataSyncError) **undefined**: Too many requests. Allowed only 100 requests in 5 minutes.
>     at w.request (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:527:747)
>     at e.request (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:525:102)
>     at async e.manifest (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:523:528)
>     at async e.doSync (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:514:300)

_

**Comment by sandy081** [comment]
Good catch
