### ISSUE TITLE
sideBarSectionHeader.background affects panel

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#99104]
Testing https://github.com/microsoft/vscode/issues/98995

![image](https://user-images.githubusercontent.com/38270282/83529952-5cd5b280-a4eb-11ea-8a87-4b4feb1a3f6d.png)

`sideBarSectionHeader.foreground` also has this problem

**Comment by sbatten** [comment]
Repro Steps:
1. Reset View Locations
2. Move Terminal into Debug
3. Set `sideBarSectionHeader.background`

Verify the setting has no effect on the panel views
