### ISSUE TITLE
Crashing process ends in endless crash loop

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#99107]
Testing #98997

Setup as described in #98997 

Crash process using `process.crash()`. I get

![cast](https://user-images.githubusercontent.com/1931590/83530763-79261f00-a4ec-11ea-9e0b-c9125f5b2593.gif)

**Comment by bpasero** [comment]
I do not understand the setup, https://github.com/microsoft/vscode/issues/98997 seems wrong.

**Comment by dbaeumer** [comment]
Sorry wring issue. Setup from https://github.com/microsoft/vscode/issues/98021

**Comment by bpasero** [comment]
I can reproduce, but I also think this is a corner case. Looks like devtools is causing the window to crash again, I am not worried to ship this.
