### ISSUE TITLE
Statusbar: VoiceOver reads current item and entire line when receiving focus

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#99101]
Testing #97156

![image](https://user-images.githubusercontent.com/9205389/83528481-6e1dbf80-a4e9-11ea-80ed-5cec576d0044.png)

The activity bar's behavior is to only read the current item when the activity bar receives focus.

The activity bar's behavior seems preferable - although I'm not sure what the optimal behavior would be.

**Comment by isidorn** [comment]
Ideally VoiceOver would only read the currently focused item in the status bar. However this is VoiceOver behavior and we can not really control this.
Wish there was a place where we could file issues against VoiceOver

@cookiecrook VoiceOver reads the content of the whole `status` element even though the focus changes from one of it's child elements to another.

**Comment by chrmarti** [comment]
To clarify: When moving focus between statusbar items, VoiceOver reads out only the newly focused item.

VoiceOver reads out the focused item AND the entire statusbar (as in the screenshot above) when moving focus to the statusbar with F6.

**Comment by isidorn** [comment]
I actually think that behavior you are seeing is just fine. Previously I was seeing what I mentioned - though I can no longer repro that.
So I would probably just close this as designed.
