### ISSUE TITLE
JSDoc Support - Optional Parameters Ignored

### ISSUE THREAD

**Issue by benjaminmillhouse** [Microsoft/vscode#9910]
- VSCode Version: 1.3.1
- OS Version: OS X 10.11.6

Steps to Reproduce:
1. Annotate a class constructor with an optional parameter
2. Attempt to invoke the constructor with the optional parameter excluded
3. Intellisense does not provide code completion for the object without the optional parameter present
```javascript
/**
* @param {string} bar - A required string
* @param {string} [baz] - An optional string
*/
function Foo(bar, baz) {
    this.bar = bar;
    this.baz = baz === void 0 ? '' : baz;
}
new Foo('bar', 'baz'). // Intellisense provided
new Foo('bar'). // Intellisense not provided
```

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript#10012
