### ISSUE TITLE
incorrect JS highlight with lower than operator and semicolon in for loop condition

### ISSUE THREAD

**Issue by jybleau** [Microsoft/vscode#9911]
- VSCode Version: Version 1.3.1 (1.3.1)
- OS Version: OS X El Capitan 10.11.6

Steps to Reproduce:

1. This Javascript code does not highlight properly:

```
for (i = 0; i<len ; i++) {
  if (foo) {
    bar = true 
    break 
  }
}
```

2. Changing this part `i<len ;` to at least `i< len;` fixes the bug:

```
for (i = 0; i< len; i++) {
  if (foo) {
    bar = true 
    break 
  }
}
```

Problem seems only to occur with "lower than" operator alone when no space are around the operator and the next semicolon is separated by a space.

PS: that's not the way I would normally format it :)
Found this "for loop" format style in a popular external library.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#223
