### ISSUE TITLE
Unclear empty or loading nodes

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#99111]
Testing #98962

When expanding "User Snippets", nothing shows up. It is not immediately clear if they are empty or if they are still loading. I suggest:
1. removing the node if it is empty
2. (or) removing its twisty if it cannot be expanded
3. (or) rendering "No entries" when expanding

![image](https://user-images.githubusercontent.com/5047891/83533215-901a4080-a4ef-11ea-92bc-20988af0422b.png)

**Comment by sandy081** [comment]
When there is no data synced, showing `No Data` entry

<img width="449" alt="image" src="https://user-images.githubusercontent.com/10746682/83628027-29049680-a598-11ea-9aa0-e121f5c5355d.png">

**Comment by sandy081** [comment]
This is no longer valid and sync activity view is sorted by time.
