### ISSUE TITLE
Splitting Locked Cells

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#99116]
Testing #98985

When testing the UI for notebooks, if I lock a query I shouldn't be able to split it in my opinion. If splitting is allowed the new split cell should also be locked. Locking makes it "read only" yet I'm still able to edit the cell by splitting it and subsequently edit the split cell.

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/commit/e012490d2dfda67f96bc406f0ac34a1ae8674ecc
