### ISSUE TITLE
SCM file/folder fuzzy match is flipped compared to Cmd+P one

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#99117]
Testing #99019

In places like Cmd+P, paths are fuzzy filtered like `/my/path/with/file.ts`, so you could find that with "mpw.ts" to find all .ts files in the dir. But in the SCM they're fuzzy filtered like `file.ts /my/path/with`, so you'd need to filter `.tsmpw`, which feels a bit odd to me. 

![image](https://user-images.githubusercontent.com/8586769/83535726-28400780-a4a7-11ea-847e-1fd8ead4c9b0.png)
![image](https://user-images.githubusercontent.com/8586769/83535761-368e2380-a4a7-11ea-8e10-460f125014c3.png)
![image](https://user-images.githubusercontent.com/8586769/83535787-40b02200-a4a7-11ea-878c-6cdb880da967.png)
![image](https://user-images.githubusercontent.com/8586769/83535817-49085d00-a4a7-11ea-87ae-503fb90d40cf.png)

**Comment by lszomoru** [comment]
I agree that the filter behavior should be consistent between quick pick and the treeview/list. In order to achieve consistent behavior we need to update the treeview/list to return multiple labels for each node which then can be used for fuzzy filtering. We will tackle this next iteration.

**Comment by lszomoru** [comment]
Verification steps:
1. Open the `vscode` repository
2. Make changes to the following files:
    - `extensions/markdown-language-features/src/slugify.ts`
    - `extensions/markdown-language-features/src/markdownExtensions.ts`
3. Switch to the SCM viewlet
4. Make sure that 'List' mode is enabled
5. Type `ems.ts` which should match both items
