### ISSUE TITLE
Theme Color : Git : Staged

### ISSUE THREAD

**Issue by RichardFevrier** [microsoft/vscode#99129]
For better visibility it would be nice to add different color settings for "staged" files.
Like: 
- "gitDecoration.stagedModifiedResourceForeground"
- "gitDecoration.stagedAddedResourceForeground"

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the UI piece you would like to be able to theme?

**Comment by RichardFevrier** [comment]
Thank you for your answer. Here are two screenshots.

Initial context: Git is configured in my current project. I have made modifications on some files. I have added some files in the index (git add filename) so those files are in a staged state, prepared for the next commit. Some others are just modified.

- The first one is the "Source Control: Git" view. You can see the color on the right (on the "M") that is actually controlled by only one setting: "gitDecoration.modifiedResourceForeground" and it is yellow in this example. So we can't differentiate staged and non staged files.
- The second is the "Explorer" view. You can see the same color controlled by the same setting as the name of the file (blurred but still yellow).

So to be able to differentiate "added", "modified", "added staged" and "modified staged" we need to add two settings: 

- "gitDecoration.stagedModifiedResourceForeground"
- "gitDecoration.stagedAddedResourceForeground"

<img width="1470" alt="main_full" src="https://user-images.githubusercontent.com/5154754/83754278-00e66780-a66c-11ea-908a-c8fceb1f5ea7.png">

<img width="1471" alt="main_full-2" src="https://user-images.githubusercontent.com/5154754/83754298-08a60c00-a66c-11ea-8ed8-aca67582a023.png">

**Comment by mohtamba** [comment]
Hi, I would be interested in working on this feature.

**Comment by alexyu0610** [comment]
Hi I'm interested in working on this too! Been a VS code user for a while, find this feature useful!

**Comment by tabaddor** [comment]
I can look into this issue if it is still open.

**Comment by mwood77** [comment]
Hi! I've created a pull request for this issue: #107318

**Comment by joaomoreno** [comment]
**Verification**

As a theme author, you should be able to color staged modifications and deletions independently from unstaged ones.

**Comment by isidorn** [comment]
I have verified there is the following color
`gitDecoration.stagedModifiedResourceForeground`
However the other one seems to be `gitDecoration.addedResourceForeground"`

Both of these colors work fine when I change them via workbench.colorCusomtisations -> verified

![Screenshot 2020-09-29 at 17 55 37](https://user-images.githubusercontent.com/1926584/94582824-01d78080-027d-11eb-8f6a-78382a1dabdf.png)
