### ISSUE TITLE
Javascript - Go to definition does not work with variables (sublime does so VSC should too)

### ISSUE THREAD

**Issue by darkguy2008** [Microsoft/vscode#9912]
- VSCode Version: 1.3.1
- OS Version: Windows 8.1

Steps to Reproduce:

* Create a normal JS object (using ES6 syntax here):
```
class randomClass {
  constructor () {
    let self = this;
    this.variable = null;
    self.variable = 'lol';
  }
}
```

* Put the cursor in "variable" and press F12 (or click any of the definition stuff in the right-click menu - peek, go, etc.). Nothing happens, not even the tooltip shows anything.

- Expected behavior:
   VS Code should either:
   * Show a list of the found definitions in the command palette (Control+Shift+P) and when you scroll through them using the arrow keys the cursor/screen should scroll to where that definition is found (mimics Sublime's behavior which is great)
   * Show a list like in VS2015 when you click "Show all references" in a C# project. Same behavior: Click and it takes you where that definition is found.

Basically, there should be a way to find out where does a variable come from. A search works, or Control+D, but that way you can't go forward/backwards, whereas with the first proposed option you can do so :)

**Comment by kieferrm** [comment]
@darkguy2008 what would expect to happen?

**Comment by darkguy2008** [comment]
@kieferrm I have updated the issue accordingly, thanks!

**Comment by darkguy2008** [comment]
No updates about this yet?

**Comment by kieferrm** [comment]
When you cursor is at `self.varia|ble` you want to see that `this.variable` is the definition of it.

**Comment by darkguy2008** [comment]
@kieferrm Yeah of course! it does not matter if the cursor is in another function inside the same file, it should go where the (first?) definition is - or show a list where that variable is being defined. 

I understand it may be hard to have it work across different files, but Sublime works around it by just doing a full search of that variable and shows it in the command palette. While this is not exactly what one expects and sometimes it gets confused with files inside node_modules, it works and helps you to navigate through the code. For me, this is a blocker as I have to work with long JS files and I use this functionality a lot to figure out the variable declarations :)

**Comment by dbaeumer** [comment]
Moving to the TS team since this must come from the tsserver.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#10110
