### ISSUE TITLE
vscode killed by SEGV_MAPERR signal when stopping a debuged extension with a native folder picker open

### ISSUE THREAD

**Issue by dcermak** [microsoft/vscode#99120]
- VSCode Version: 1.45.1
- OS Version: openSUSE Tumbleweed

Steps to Reproduce:

1. Open the source code of an extension that itself opens a native folder picker dialog via `showOpenDialog`.
2. Start debugging the extension from withing vscode and trigger the folder picker to show up.
3. Stop the debugger. The native open folder dialog will stay open.
4. Press ESC or cancel in the native dialog.
5. VSCode dies with a stacktrace:
```
Received signal 11 SEGV_MAPERR ffffd58b9f022073
#0 0x55cf60639349 (/home/dan/packages/github.com/microsoft/vscode/.build/electron/code-oss+0x35f1348)
  r8: 0000000000000001  r9: 0000000000000003 r10: 0000000000000000 r11: 0000000000000040
 r12: 00002a76ce967650 r13: 00002a76ce967630 r14: 00007ffcdd072c70 r15: 00002a76cf7b3d20
  di: 00002a76ceabfa00  si: 0000000000000001  bp: 00007ffcdd072cb0  bx: 00002a76cf9d6ca0
  dx: 0000000000000000  ax: ffffd58b9f02200b  cx: 0000000000000006  sp: 00007ffcdd072c50
  ip: 000055cf5e74b834 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000005
 trp: 000000000000000e msk: 0000000000000000 cr2: ffffd58b9f022073
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Is this still an issue with our latest insiders https://code.visualstudio.com/insiders ?
