### ISSUE TITLE
Running a cell makes the file "dirty"

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#99127]
Testing #98985

If I execute a query on a cell it makes the notebook dirty which leaves me to believe that it is saving the output of the query, but after saving and reopening the file the output isn't there anymore and I have to rerun the query which causes the file to become dirty again. This is odd to me because whether I save or not doesn't matter in this case as it is making the file dirty, but nothing is changing/

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/96403
