### ISSUE TITLE
Settings sync - Preferences Sync quick pick dialog inconsistent title

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#99125]
Testing #98962

The `Preferences Sync` quick pick dialog depending on the action that opens it:
* Gear -> Turn on Preferences Sync... - "Preferences Sync"
* Preferences Sync viewlet -> Gear action - "Preferences Sync: Configure..."

**Comment by sandy081** [comment]
These are different UI pieces even though both show almost same information.

First one is to configure and turn on sync and second one is just to configure and hence the title is more specific.
