### ISSUE TITLE
Settings sync - Turning off sync and clearing cloud data

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#99122]
Testing #98962

I have multiple machines that have settings sync on, and everything is in sync. On one of the machines I have turned off sync, and chose the options to turn off sync on all devices and clear the data from the cloud. After doing so I am seeing weird behavior on some of the machines:
* There is still data in the `Synched Data` view, even though data should have been cleared from the cloud.
* I see the `current` machine in the `Synched Machines` view view even though sync is not on.

**Comment by sandy081** [comment]
Can you please refresh the views and check?

**Comment by lszomoru** [comment]
I did refresh multiple times and I was still seeing data that should have been cleared up.

**Comment by lszomoru** [comment]
Here are the logs that we have looked at today. Looks like on Windows, closing the dialog triggers a sync. 

> [2020-06-03 11:01:50.088] [userDataSync] [info] Auto Sync: Triggered by Activity
> [2020-06-03 11:01:50.210] [userDataSync] [info] Auto Sync: Disabled because sync is disabled
> [2020-06-03 11:01:50.210] [userDataSync] [info] Auto Sync: Stopped
> [2020-06-03 11:01:51.782] [userDataSync] [info] Settings: Updated remote settings
> [2020-06-03 11:01:51.800] [userDataSync] [info] Settings: Updated last synchronized settings
> [2020-06-03 11:01:52.248] [userDataSync] [info] Keybindings: No changes found during synchronizing keybindings.
> [2020-06-03 11:01:52.263] [userDataSync] [info] Keybindings: Updated last synchronized keybindings
> [2020-06-03 11:01:52.706] [userDataSync] [info] Snippets: No changes found during synchronizing snippets.
> [2020-06-03 11:01:52.728] [userDataSync] [info] Snippets: Updated last synchronized snippets
> [2020-06-03 11:01:54.042] [userDataSync] [info] GlobalState: Updated remote ui state
> [2020-06-03 11:01:54.065] [userDataSync] [info] GlobalState: Updated last synchronized ui state
> [2020-06-03 11:01:55.436] [userDataSync] [info] Extensions: Updated remote extensions
> [2020-06-03 11:01:55.461] [userDataSync] [info] Extensions: Updated last synchronized extensions
> [2020-06-03 11:01:56.561] [userDataSync] [info] Sync done. Took 6472ms

**Comment by sandy081** [comment]
Very good catch.
