### ISSUE TITLE
Navigating by peek shall first goto errors and then to warnings

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99138]
Testing #98821

- Have following issue notebook

```
[{"kind":2,"language":"github-issues","value":"repo:microsoft/vscode assigne:@me label:settings","editable":true},{"kind":2,"language":"github-issues","value":"rep:microsoft/vscode assignee:@me label=1234","editable":true}]
```

- Open the notebook
- Use F8 to navigate problems

It shall follow the same navigation order - errors, warnings

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Abug+label%3Anotebook
