### ISSUE TITLE
C++ Intellisense not working as expected

### ISSUE THREAD

**Issue by alex-tremblay** [microsoft/vscode#99137]
- VSCode Version: Lastest
- OS Version: Windows 10

Steps to Reproduce:

1. Fresh vscode (insider too)
2. Install extension c/c++ and cmake tools
3. Over an element
![image](https://user-images.githubusercontent.com/52473004/83545636-7a941f00-a4cd-11ea-90bf-2d567fa3f4ec.png)
3b. Or try to autocomplet and object 
![image](https://user-images.githubusercontent.com/52473004/83545776-afa07180-a4cd-11ea-8998-9f8575d24052.png)

Does this issue occur when all extensions are disabled?: No (c++ need extension)

**Comment by alex-tremblay** [comment]
This is my first issues, if I forgot something just tell me I will go add it

**Comment by connor4312** [comment]
\extC
