### ISSUE TITLE
Support relative paths for images in markdown/rich output cells (of untitled notebooks)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#99139]
- Version: 1.46.0-insider
- Commit: 1bfa086adb9271ff56be11821da686e4cfffb672
- Date: 2020-06-02T08:10:00.819Z
- Electron: 7.3.0
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Darwin x64 19.5.0

Steps to Reproduce:

1. Create an untitled notebook, markdown with relative images do not work.
2. Expectation is images will be resolved relative to current workspace folder
However in a multi-root workspace, things might be a little bit more complicated.

Not sure how VSC handles this today, e.g. with auto completion for relative imports in untitled js/ts files.

I'd also this to work with HTML output of cells (can create a separate issue, assumed they are similar)

Does this issue occur when all extensions are disabled?: Yes

@rebornix /cc

**Comment by rebornix** [comment]
This is also tricky with single workspace as the relative path might be broken once you save it to disk.

**Comment by roblourens** [comment]
Doesn't work in the normal markdown preview either. I dunno if it's worth it really

**Comment by DonJayamanne** [comment]
Agreed.
However as  Jupyter notebook user, when they create untitled files, relative images work in markdown & html output.

When using the WebView panel, we just change the base href in html document to point to the local workspace and that's how relative images work for markdown/html.

* If we were to create physical files, then this kind of defeats the purpose of the notion of untitled files.
* If we did create physical files that had a scheme of `untitled` would that work with the VS Code API (i.e. actual file but `untitled` scheme). I know VS Code custom editor has issues with such a combination.

I'm trying to understand how we make this possible with the new VS Code API.

**Comment by roblourens** [comment]
This seems to work now
