### ISSUE TITLE
Redundant error is shown

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99134]
Testing #98821

<img width="887" alt="image" src="https://user-images.githubusercontent.com/10746682/83544921-e93da080-a4fe-11ea-9547-61e5b9235d55.png">

It occurred to me when I closed the editor and opened the notebook from problems panel. Cant repro it again but filed it incase you know why it happens.

**Comment by jrieken** [comment]
might be because the close event for a notebook is missing and then markers are't cleaned up

**Comment by jrieken** [comment]
This should now be fixed with https://github.com/microsoft/vscode/issues/99142. Before, we would remove the project and create a new one, but we would never clean up markers...

**Comment by jrieken** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/99142
