### ISSUE TITLE
typescript not loading

### ISSUE THREAD

**Issue by yodacom** [microsoft/vscode#99132]
Issue Type: <b>Bug</b>

just booted up vscode and got the message that typescipt was unable to load

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.96GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-color|ans|0.4.5
vscode-apollo|apo|1.16.0
vscode-mjml|att|1.6.0
vscode-custom-css|be5|3.0.9
emojisense|bie|0.7.0
vscode-tailwindcss|bra|0.2.0
simple-react-snippets|bur|1.2.2
turbo-console-log|Cha|1.4.0
vscode-standardjs|che|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.36.0
vscode-eslint|dba|2.1.5
es7-react-js-snippets|dsz|2.7.1
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.0.0
vscode-optimize-images|fab|1.1.0
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.3
pug2html|gin|0.0.5
output-colorizer|IBM|0.1.2
svelte-vscode|Jam|0.9.3
vscode-peacock|joh|3.7.2
vscode-styled-components|jpo|0.0.29
graphql-for-vscode|kum|1.15.3
react-apollo-snippets|lev|0.0.3
vs-color-picker|lih|1.0.0
dotenv|mik|1.0.1
vscode-todo-parser|min|1.9.1
vscode-pugbeautify|mrm|1.0.2
vscode-puglint|mrm|2.3.0
vscode-docker|ms-|1.2.1
python|ms-|2020.5.80290
cpptools|ms-|0.28.2
node-debug2|ms-|1.42.1
debugger-for-chrome|msj|4.12.8
color-highlight|nau|2.3.0
vscode-extension-auto-import|Nuc|1.4.3
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.1.0
vscode-css-peek|pra|3.0.2
vscode-graphql|Pri|0.2.14
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.9.0
language-stylus|sys|1.11.0
vsfire|tob|1.4.1

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also, what is the error message?
