### ISSUE TITLE
JavaScript IntelliSense is not working without jsconfig.json

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#9913]
- VSCode Version: 1.3.1
- OS Version: El Capitan

**No IntelliSense without jsconfig.json**
Steps to Reproduce:

1. Open Visual Studio Code on a simple JavaScript project without jsconfig.json. 
2. Trigger Suggest on a first party module. I expect to see IntelliSense even without a jsconfig.json file. 

I am not seeing IntelliSense for my first party module. It is stuck loading. 

![image](https://cloud.githubusercontent.com/assets/2449568/17222878/1abb3e1e-54af-11e6-8062-b13ebee7c3c5.png)

I am not seeing any IntelliSense. It will load endlessly. I would expect to at least get basic code completion. 

![image](https://cloud.githubusercontent.com/assets/2449568/17222899/31a71e2c-54af-11e6-9cee-2a2a7244fdf5.png)

After adding jsconfig with the simplest of configuration and reloaded the window (this was important, it would not work if I didn't reload the window nor would it work if I reloaded the JavaScript project). 

```
{
  "compilerOptions": {
    "target": "ES6",
    "module": "commonjs"
  }
}
```

IntelliSense is working again. 

![image](https://cloud.githubusercontent.com/assets/2449568/17223037/b5926c82-54af-11e6-83cc-0af05d1dd7c6.png)

![image](https://cloud.githubusercontent.com/assets/2449568/17222995/8a38dd5a-54af-11e6-87b6-820005d2cac9.png)

Is this the intended behavior? 

I would expect to at least get basic code completion with no jsconfig.json file. Also I would expect to be given a hint to add a jsconfig.json file (see issue #9875) if it isn't there already.

**Comment by kieferrm** [comment]
I don't see the 'loading' message and do get at least basic intellisense in this situation. At least meaning that it depends on my workflow. For example, when I just created the files, intellisense is proposing what database exports. In other situations, I need to added a `jsconfig.json` file  to get that experience.

**Comment by jrieken** [comment]
@waderyan It seems like another problem since you don't even get the fallback word based completions. I believe your tsserver or extension is just struggling for some (unrelated) reason... Can you try to isolate the real issue?

**Comment by waderyan** [comment]
Yeah. I'm trying to recreate today but without luck. I'll see if I can catch some errors in the Developer's console.
