### ISSUE TITLE
Step in Targets visible in unrelated file?

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#99144]
Testing #97801

Not sure if this is an issue with the Mock Debug Adapter or Step in Targets itself, but if I open say `settings.json` while I am debugging, I get a context menu that has step in targets (and run to cursor, add inline breakpoint). These options don't make any sense in my current context.

**Comment by isidorn** [comment]
Good point. I think we should only show those actions for the "debugged" file.
Not something for endgame though.
