### ISSUE TITLE
Error while finding all references using refresh action

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99148]
Testing #98821

- Open My work notebook
- Find all references for `$vscode`
- Close the notebook
- Click on refresh action in References view
🐛 

<img width="481" alt="image" src="https://user-images.githubusercontent.com/10746682/83547960-44719200-a503-11ea-99d3-69c3ea650d95.png">

**Comment by jrieken** [comment]
The error is gone but note that there is https://github.com/microsoft/vscode/issues/99240 which means refresh doesn't yet return all results

**Comment by sandy081** [comment]
Verified that error is gone but I see #99240
