### ISSUE TITLE
Problems are not removed when issue notebook is closed

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99142]
Testing #98821

- Have following issue notebook

```
[{"kind":2,"language":"github-issues","value":"repo:microsoft/vscode assigne:@me label:settings","editable":true},{"kind":2,"language":"github-issues","value":"rep:microsoft/vscode assignee:@me label=1234","editable":true}]
```
- Open the notebook
- Open problems view and check there are problems
- Close the notebook
🐛 Problems are not cleared. I think the GitHub issue notebook extension shall clear the diagnostics when notebook is closed.

**Comment by jrieken** [comment]
They should, assuming this fires: https://github.com/microsoft/vscode-github-issue-notebooks/blob/0168f40b4db3e2c79cfeb045382b7cfbd85fed17/src/notebookProvider.ts#L81

**Comment by jrieken** [comment]
The event does fire, I forget to clean the diagnostics collection...
