### ISSUE TITLE
Headers are ignored, generating nonsense errors

### ISSUE THREAD

**Issue by nic-hartley** [microsoft/vscode#99146]
Issue Type: <b>Bug</b>

1. Create a new file with these contents:

    ```c
    #include <netdb.h>
    
    int foo(void) {
        struct addrinfo foo = {
            .ai_family = AF_UNSPEC,
        };
        (void) foo;
    }
    ```

2. Load it in VSC. Note the errors about `foo` having an incomplete type.
3. Attempt to compile it, with all warnings (gcc: `-Wall`)
4. Notice the lack of an actual error.

Expected behavior: VSC only reports real errors.

VS Code version: Code - OSS 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-23T19:32:05.786Z)
OS version: Linux x64 5.4.40-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor (32 x 2716)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.57GB (10.95GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
cpptools|ms-|0.28.2
rust|rus|0.7.8

</details>

**Comment by connor4312** [comment]
\extC
