### ISSUE TITLE
Problems are getting multi-selected

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99140]
Testing #98821

![Kapture 2020-06-02 at 18 41 04](https://user-images.githubusercontent.com/10746682/83546278-b7c5d480-a500-11ea-94bb-a7c7a5b5046e.gif)

🐛 See how problems are getting selected (multi) in the problems view while creating new cells

**Comment by jrieken** [comment]
@sandy081 How is the selection managed? That's really nothing I have touched but might be an issue with the way ids are computed and now used?

**Comment by sandy081** [comment]
I suspect we are generating same id for markers across cells?

https://github.com/microsoft/vscode/blob/187dedbdc33e91b53dff9e3ed0f8278b27d113c7/src/vs/workbench/contrib/markers/browser/markersModel.ts#L177-L177

**Comment by jrieken** [comment]
Yeah, looks like it...

**Comment by jrieken** [comment]
Pushed https://github.com/microsoft/vscode/commit/1434f626142e3f61e1dc24e7c130b24f2ea137b3 which fixes this. @sandy081 please take a quick look as this affect id computation which looks complicated.

**Comment by sandy081** [comment]
All it is trying to do is make id unique and feeding resource of raw marker makes it. With this change we do no need id of resourceMarkers to compute id of markers but there is no harm in just leaving it.

**Comment by jrieken** [comment]
ok, I can revisit this during debt week
