### ISSUE TITLE
Bogus matches in peek references view

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99150]
Testing #98821

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/10746682/83548116-8569a680-a503-11ea-98c5-e34724b773e1.png">

**Comment by jrieken** [comment]
@sandy081 can you share the notebook?

**Comment by sandy081** [comment]
Sorry that I did not mention, this is my work notebook from the ones you shared in the TPI.
