### ISSUE TITLE
Close the source tab when dragging to another window

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9915]
- VSCode Version: Code - Insiders 1.4.0-insider (531a56f772fc33ec88910328b88f4dbd7ae5df43, 2016-07-28T16:52:53.252Z)
- OS Version: Linux x64 4.4.0-31-generic, Ubuntu 16.04

Steps to Reproduce:
1. Open two vscode windows
2. Open a file tab
3. Drag the tab to the other window, notice the original file is still open after the drag and drop action

**Comment by Tekbr** [comment]
- VSCode Version: 1.4.0-insider commit 4656fe3 2016-07-29T05:08:49:671Z
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

1- Allow files "not saved" - "Untitled-1". They are moved to new windows, not only files and have already been saved.

2- So there is no conflict between the files, remove the number from "Untitled", or automatically rename to new sequence numbers when we moved to a new window that has the "Untitled -'x '."

3- By dragging the tab out of the tab bar to open in a new window. This is not possible.

![new-window](https://cloud.githubusercontent.com/assets/19866231/17247600/b15f043e-556a-11e6-8152-1c913b249729.png)

**Comment by bpasero** [comment]
This may require quite a bit of work to find out that the drop happened outside of the window, I am not sure this can be easily detected but I can give it a quick try.

**Comment by bpasero** [comment]
I could not find a solution to detect that you drop outside of the window other than maybe looking at the X/Y coordinates and then checking if they are within the window, which is super ugly. Given that, I think I would rather not want to add this until there is real support for better cross-window DND.
Also: this does not help with the case where the drop operation was not successful on the target. I think the real solution would be to somehow include the originating window in the dragged URI and in the target window send a IPC message over to the source if the drop was OK and only then close the editor.
