### ISSUE TITLE
Redundant entries in Find all references view

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99153]
Testing #98821

- Open My Work notebook
- Find all references for `$vscode`
- Rename `$vscode` to `$vscoderepo`
- clear results in references view
- click on refresh action on `$vscode` entry in references view
- clear results again

🐛 Two entries are shown now which are pointing to same

<img width="455" alt="image" src="https://user-images.githubusercontent.com/10746682/83549015-e8a80880-a504-11ea-9203-0c12b1e29365.png">

**Comment by jrieken** [comment]
Yeah, not so simple but independent of notebooks. The viewlet doesn't know anything about "anchor symbols" but simply remembers words at certain locations. It would need some de-dupe based on the location
