### ISSUE TITLE
Shift+enter notebook behavior is odd

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#99156]
Testing #98821

Disclaimer: I don't know how other notebooks behave, but I know shift+enter as run from kusto.

Shift+Enter appears to do the following:
- Empty cell: Creates a new cell underneath
- Non-empty cell: Runs the cell and then focuses the next cell after it's finished(???)
- Non-empty running cell(???): Focus and scrolls to the next cell. the textarea isn't focused though

It does so many things, some of them are broken (scrolling but breaking focus state?) and one of them is time based (when running cell).

![recording (2)](https://user-images.githubusercontent.com/2193314/83549960-f2a51980-a4ba-11ea-8018-ca23dc514c4a.gif)

**Comment by roblourens** [comment]
It is "execute and focus next". When there is no next cell, it creates a next cell - that should be the only time it creates a new cell. I think your gif shows that. One bug is, it should focus the next cell immediately and not wait for execution to finish.

**Comment by roblourens** [comment]
All of this matches JupyterLab (except the bug)

**Comment by Tyriar** [comment]
@roblourens it's also focusing next the next cell list item sometimes and the textarea other times. This isn't right surely?

**Comment by roblourens** [comment]
I see that issue - it should match whether the active cell editor is focused but doesn't do it consistently. Also an issue with alt+enter

**Comment by roblourens** [comment]
I don't know whether we will want that - it doesn't match JupyterLab but feels right to me. Leaving it for now.

**Comment by Tyriar** [comment]
> I see that issue - it should match whether the active cell editor is focused but doesn't do it consistently. Also an issue with alt+enter

Is this tracked? The inconsistency is very annoying, it seems to only focus the textarea if it's a new textarea, not an existing one:

![recording (5)](https://user-images.githubusercontent.com/2193314/83555930-e8d3e400-a4c3-11ea-92d1-88426f911797.gif)

**Comment by roblourens** [comment]
That was also fixed in my commit above

**Comment by Tyriar** [comment]
@roblourens the focus behavior is the opposite to what I was expecting where the cell is focused, not the textarea, just making sure it was intentional? To start working on the next cell now is shift+enter, _enter_, typing, as opposed to shift+enter, typing.

**Comment by roblourens** [comment]
It should focus the next cell's editor only if the active cell's editor is focused when you use the command. Does that make sense? Is that not what you see?

**Comment by Tyriar** [comment]
No it doesn't happen:

![recording (12)](https://user-images.githubusercontent.com/2193314/83767733-d88e4700-a632-11ea-99a1-f61d1beb154b.gif)

It also doesn't happen if the output was already there or on the last cell either:

![recording (13)](https://user-images.githubusercontent.com/2193314/83767859-fa87c980-a632-11ea-8cc6-f4f88e221225.gif)

**Comment by roblourens** [comment]
One more try

**Comment by Tyriar** [comment]
Thanks, works as expected now 👍
