### ISSUE TITLE
Find all references are not sorted by cell

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99152]
Testing #98821

![Kapture 2020-06-02 at 19 06 34](https://user-images.githubusercontent.com/10746682/83548574-42f49980-a504-11ea-84ac-34e2b4743dd9.gif)

**Comment by jrieken** [comment]
Yeah, the is the usual sort bug, e.g `1, 10, 11, 12, 2, 3`

**Comment by jrieken** [comment]
Cell fragments are now padded with zeros so that natural sort works againt. This is kinda lame but works...
