### ISSUE TITLE
Git init button has bad hover feedback

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9916]
![image](https://cloud.githubusercontent.com/assets/22350/17225590/df09735c-5505-11e6-8dd7-41f2eab9359a.png)

**Comment by joaomoreno** [comment]
@sandy081 You seem to have broken the hover feedback for this button in some places with 73339b066a3deee4bb2911780b67de37e0c9fd03.

**Comment by sandy081** [comment]
Bad.. will fix it
