### ISSUE TITLE
Web breakpoint icon takes a while to show

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#99168]
Testing #97876

I probably waited 5s before I saw the breakpoint icon appear. I thought this was a bug, as when I launched a debug session and quickly switched tabs back and forth the breakpoint immediately switched. You can see in the example below where the breakpoint is hit when you navigate to the web page I then wait a bit long for the breakpoint icon to show up. Would expect this to appear immediately.

EDIT: Safari seems to show it immediately. So it appears Chrome + FF take the longest.

![Kapture 2020-06-02 at 10 42 27](https://user-images.githubusercontent.com/35271042/83552555-d014ff80-a4be-11ea-9929-752eeb34df63.gif)

**Comment by misolori** [comment]
In FireFox this actually never gets shown if you restart the process and quickly switch tabs. In the end of this gif, I switch over and the icon is shown immediately:

![Kapture 2020-06-02 at 11 11 08](https://user-images.githubusercontent.com/35271042/83554640-f5efd380-a4c1-11ea-96f2-7c4474f1694b.gif)

**Comment by isidorn** [comment]
Good catch. However this is just the browser blocking us I believe.
Also assigning to @bpasero but nothing we can do in May thus assigning to On Deck.

**Comment by bpasero** [comment]
Maybe switching to web notifications instead would be a way out. Given this seems to be browser specific, setting upstream label.
