### ISSUE TITLE
Unexpected size change of notebook editor

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#99163]
Testing #98821

![recording (4)](https://user-images.githubusercontent.com/2193314/83551985-ee2e3000-a4bd-11ea-84ff-db2e781e95ec.gif)

**Comment by rebornix** [comment]
Good catch, not sure why monaco's height changes (I guess it's horizontal scrollbar but the query is short).

**Comment by rebornix** [comment]
let's track it in https://github.com/microsoft/vscode/issues/100224 which has more info.
