### ISSUE TITLE
Quick open doesn't work with files with 'view' in the name

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#99160]
Issue Type: <b>Bug</b>

The title is specific, but this is a general issue. When using quick open if a file name starts with something like "view" or "debug" it will not appear in the results list.

When typing "view" then a space the quick open panel switches to commands in the view category, rather than files. This feels unnecessary and undesireable because the panel already has a dedicated keybinding and query syntax for commands (`> `).

Notice the file "View Service.txt" in the Explorer that I can't actually get to via quick open. When I run quick open without `> ` I expect all of my results to be files, not commands. I expect the command entries visible in the screenshot to be in the `> ` category.

![image](https://user-images.githubusercontent.com/484784/83550052-19fbe680-a4bb-11ea-8cf6-2f709e7b6cd3.png)

VS Code version: Code - Insiders 1.46.0-insider (2c1871d538c64df71af4902deba47d7fa4b53f27, 2020-06-01T10:34:11.096Z)
OS version: Windows_NT x64 10.0.18363

**Comment by bpasero** [comment]
Yes, this is a consequence of the quick open architecture we cannot change easily. The workaround is to simply not use space at all. It should work fine then.

**Comment by akbyrd** [comment]
Ugh, seriously? The response to "my search query is clearly broken" is "it's too hard"?
