### ISSUE TITLE
Web upload DnD: Unclear how to cancel

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#99177]
Testing #97714

When uploading a very large directory, it would be helpful to have a way to cancel the operation. I'd expect a notification progress indicator with a cancel button or a cancel option onclick of the statusbar indicator.

**Comment by bpasero** [comment]
You click on the status bar entry to see a notification that has the "Cancel" button. Did you try that?

**Comment by JacksonKearl** [comment]
Oh, seems like that only works on chromium. On Safari clicking the status bar doesn't seem to do anything.

**Comment by bpasero** [comment]
Ok, thanks. Safari is currently not supported.
