### ISSUE TITLE
C language not an option, no syntax highlighting

### ISSUE THREAD

**Issue by DaveEveritt** [microsoft/vscode#99178]
- VSCode Version: 1.45.1
- OS Version: OS X Mojave 10.14.6 (18G103)
- C/C++ Extension Version: 0.28.1

Single project in C, multiple files. After installing the above C/C++ extension, there is no syntax highlighting. In the language syntax options, C does not appear. Tried: reloading window, reinstalling extension, restarting computer.

**Steps to Reproduce:**

After installing the above C/C++ extension on OS X Mojave:

1. Open a C file ".c"
2. Click the language option, bottom right (reads "plain text" by default)
3. "Select language mode" shows
4. Choose "Configure file association for .c"
5. There is no option to choose C

**Expected behavior:**

At point 5 above, I would expect "C" to be a language option

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
\extC

**Comment by DaveEveritt** [comment]
> \extC

Already posted on the repo for this extension, but the reply then pointed me here - it's a Microsoft extension… so going round in circles!

**Comment by aeschli** [comment]
@DaveEveritt Can you open the extensions view let and type `@builtin C/C++` in the input field.
Make sure the `C/C++ Language Basics` extension is enabled.
![image](https://user-images.githubusercontent.com/6461412/83657407-194d7800-a5c1-11ea-8229-224db9327627.png)

**Comment by DaveEveritt** [comment]
It is enabled

**Comment by aeschli** [comment]
Anything in the log (`Developer: Show Logs... Window, or Extension Host`)...?

**Comment by DaveEveritt** [comment]
> Anything in the log (`Developer: Show Logs... Window, or Extension Host`)...?

There was, about this particular extension… but then I hit a VSCode "insider build" recommendation 'yes' that (IIRC) mentioned the C/C++ extension and… all is now working as expected :-)
