### ISSUE TITLE
Git plugin loops when branch has no upstream

### ISSUE THREAD

**Issue by cardiffman** [microsoft/vscode#99179]
I'm working on a branch that has no upstream. 

The "output" window is full of repeats of this, that is hitting the "fatal" no-upstream message and then repeating. Repo and branch names renamed for confidentiality.

    Looking for git in: git
    Using git 2.11.0 from git
    > git rev-parse --show-toplevel
    > git rev-parse --git-dir
    Open repository: /path/to/repo
    > git status -z -u
    > git symbolic-ref --short HEAD
    > git rev-parse personal/my-branch
    > git rev-parse --symbolic-full-name personal/my-branch@{u}
    fatal: no upstream configured for branch 'personal/my-branch'
    > git for-each-ref --format %(refname) %(objectname) --sort -committerdate
    > git remote --verbose
    > git config --get commit.template
    > git check-ignore -v -z --stdin
    > git status -z -u
    > git symbolic-ref --short HEAD
    > git rev-parse personal/my-branch
    > git rev-parse --symbolic-full-name personal/my-branch@{u}
    fatal: no upstream configured for branch 'personal/my-branch'
    > git for-each-ref --format %(refname) %(objectname) --sort -committerdate
    > git remote --verbose
    > git config --get commit.template
    > git status -z -u
    > git symbolic-ref --short HEAD
    > git rev-parse personal/my-branch
    > git rev-parse --symbolic-full-name personal/my-branch@{u}
    fatal: no upstream configured for branch 'personal/my-branch'

I have to believe that not having an upstream is such an everyday thing that it isn't the reason for this loop. So I'm reporting in this channel because I think it's a defect in vscode. Let me know if you need more information.

I just updated this machine to 1.45.1 today:
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.9.0-12-amd64

**Comment by joaomoreno** [comment]
This is fine, it's just logging output.

**Comment by cardiffman** [comment]
It looks like a problem is happening. The word "fatal" for one thing. Can you give me more information?
