### ISSUE TITLE
`workbench.editorAssociations` configuration messes with git diff view

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#99172]
Version: 1.46.0-insider
Commit: 2c1871d538c64df71af4902deba47d7fa4b53f27
Date: 2020-06-01T10:32:27.369Z (1 day ago)
Electron: 7.3.0
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:

1. Set this setting:

```json
"workbench.editorAssociations": [
        {
            "viewType": "default",
            "filenamePattern": "*.ps1"
        }
    ],
```

which I use in the PowerShell extension for PowerShell Notebooks.

2. open a diff view of a PowerShell file

#### Expected

A normal diff view like:
![image](https://user-images.githubusercontent.com/2644648/83558301-ab715580-a4c7-11ea-8e88-f58dfbf09972.png)

#### Actual
![image](https://user-images.githubusercontent.com/2644648/83558335-ba580800-a4c7-11ea-98a3-e5c48f98e99f.png)

* Editors are not locked together
* diff view highlighting isn't showing up

**Comment by rebornix** [comment]
@mjbvz I found that when opening a diff editor with above configuration set, below code is always invoked and override the normal editor opening:

https://github.com/GustavoASC/vscode/blob/1d268b701376470bc638100fbe17d283404ac559/src/vs/workbench/contrib/customEditor/browser/customEditors.ts#L431

**Comment by mjbvz** [comment]
To test

1. Using our [custom editor sample extensions](https://github.com/microsoft/vscode-extension-samples/tree/master/custom-editor-sample)
1. Create a `*.cscratch` file that has been modified in git.
1. In your user/workspace settings, add:

    ```
    "workbench.editorAssociations": [
        {
            "viewType": "default",
            "filenamePattern": "*.cscratch"
        }
    ]
    ```

1. Now open the diff view and confirm that the standard text editor is used and that it includes the correct diff highlighting
