### ISSUE TITLE
Can't invoke code lens on mac from keyboard shortcut in Rust

### ISSUE THREAD

**Issue by CleanCut** [microsoft/vscode#99170]
Version: 1.46.0-insider
Commit: 1bfa086adb9271ff56be11821da686e4cfffb672
Date: 2020-06-02T08:10:00.819Z (9 hrs ago)
Electron: 7.3.0
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

Steps to Reproduce:

I'm trying to use the feature described in https://github.com/microsoft/vscode/issues/41579 and implemented in https://github.com/microsoft/vscode/pull/91232

1. Install the `rust-analyzer` extension
2. Open a Rust project
3. Bind `codelens.showLensesInCurrentLine` to a keyboard shortcut
4. Navigate to any line with a codelens bulb, but _not on the part of the line underlined_.  (If you are on the actual underlined part, you can press `cmd+.` to `Show Fixes`, but the `Show CodeLens Commands for Current Line` feature is supposed to show the fixes for the whole line, unless it is very misnamed).
5. Press your chosen keyboard shortcut (or shift-cmd-p and select `Show CodeLens Commands For Current Line`)
6. Nothing happens.

Does this issue occur when all extensions are disabled?: N/A - there's not code lenses without the `rust-analyzer` extension.

**Comment by jrieken** [comment]
> but the Show CodeLens Commands for Current Line feature is supposed to show the fixes for the whole line, unless it is very misnamed).

This is a misunderstanding. CodeLens is the inline command links, like "Complexity 6" in the screen capture below. They are there augment code with extra insights, like SCM information, reference information and they are always gestures to invoke a command. The light bulb on the other hand is always for source code enhancements, like refactoring or quick fixes.

<img width="458" alt="Screenshot 2020-06-03 at 08 46 03" src="https://user-images.githubusercontent.com/1794099/83604572-ab7c5e80-a576-11ea-9b63-e118fea29475.png">

**Comment by CleanCut** [comment]
My mistake, thanks.
