### ISSUE TITLE
Views moved to the SCM view don't always restore to the proper size/position

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#99181]
Testing #98994

This seems to only affect views on the SCM viewlet.
![views](https://user-images.githubusercontent.com/641685/83567652-e8514280-a4ef-11ea-837b-ec130e6b66f0.gif)

Might be related to #98615 but I've seen no correlation with a window border (and only on the SCM view)

**Comment by sbatten** [comment]
maybe because the SCM views are added after?

**Comment by joaomoreno** [comment]
Yes, definitely because SCM messes around with views. This will be fixed by https://github.com/microsoft/vscode/issues/90461
