### ISSUE TITLE
Notebook: "High Contrast" is incredibly low-contrast

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#99185]
Testing #98985

Very minimal contrast here:
![image](https://user-images.githubusercontent.com/8586769/83571224-3f4d1c80-a4dc-11ea-8cc4-ff8f08c74216.png)

**Comment by rebornix** [comment]
@misolori we may want to keep the background for high contrast theme.

**Comment by misolori** [comment]
Added the same color we use for borders in HC:

![image](https://user-images.githubusercontent.com/35271042/83588534-7df7cc80-a506-11ea-9c14-4036ce0663d7.png)

**Comment by lszomoru** [comment]
Should we add the orange border for the active cell, to be consistent with how the workbench represents the active element?

![image](https://user-images.githubusercontent.com/3372902/83744554-9b3eaf00-a65c-11ea-8ef6-192c87e86df2.png)

**Comment by misolori** [comment]
@lszomoru you could argue that we need the orange border for cell focus and indicator but that might make it busier:

![image](https://user-images.githubusercontent.com/35271042/83779151-70def880-a640-11ea-8b07-e56a27d34947.png)

I'd say for this milestone we stick with the default border and iterate on the focus in the next one. Will track this in https://github.com/microsoft/vscode/issues/98984.
