### ISSUE TITLE
Screencast: mouse circle doesn't go away after stopping a native dnd operation

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#99189]
Testing #98985

Drag and drop a cell with screencast mode enabled. If you successfully move the cell, the red circle around the cursor wont go away until you click.

**Comment by roblourens** [comment]
This happens with DND everywhere, such as in the explorer. You don't get mouse events during DND. You could listen to drag events along with the mouse events.

**Comment by lszomoru** [comment]
As far as my understanding goes is that this an issue only on MacOS as on MacOS we are using the native control so the events do not reach the DOM. One potential option would be for the screencast mode to listen to various events and act accordingly but at the moment that seems like too big of an investment for minimal return. Closing the issue as out of scope for now.
