### ISSUE TITLE
Notebook: Tab moves focus takes a few `tab`s to take effect

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#99186]
Testing #98985

Cursor like this:
![image](https://user-images.githubusercontent.com/8586769/83571334-6dcaf780-a4dc-11ea-94ad-b38062e00935.png)

With "Tab Moves Focus" on,

Tab once, suggestion window appears (bug)
Tab again, literal tab is inserted (bug)
Tab again, focus moves (correct)

In a normal editor tab always simply moves focus when "Tab Moves Focus" is on.

**Comment by roblourens** [comment]
Do you have a setting that would make the suggest widget pop up with you hit tab?

**Comment by JacksonKearl** [comment]
I have `editor.tabCompletion` enabled

**Comment by roblourens** [comment]
Oh, I think that would be by design then. At least you would probably see the same thing in a normal editor right?

**Comment by JacksonKearl** [comment]
No, in the normal editor tab always simply moves focus when "Tab Moves Focus" is on.

**Comment by roblourens** [comment]
I mean, for me in a normal editor when I turn on "tab moves focus" and also "editor.tabCompletion", then tab completion happens on the first tab, then I tab out of the editor on the second tab. Is that not what you see?

**Comment by JacksonKearl** [comment]
In a normal editor with "tab moves focus" and "editor.tabCompletion" enabled, tab will move focus if there is no active suggest widget, otherwise it will accept the suggest widget's entry, then pressing an additional time will move focus. 

In the notebook cell, I'm seeing tab move focus if you don't have a word ending at your cursor, otherwise it inserts a literal tab character, then pressing again moves focus. This was with both code cells and markdown cells in an issues-notebook.

I think tab should never insert a literal tab character if "tab moves focus" is enabled.
![Kapture 2020-06-05 at 11 08 51](https://user-images.githubusercontent.com/8586769/83909084-f932cb80-a71c-11ea-87ac-64425ba62ce4.gif)

**Comment by roblourens** [comment]
The point of tab completion is to insert the best suggestion when the suggest widget __isn't__ active. Maybe you aren't testing the same scenario. In a markdown file, I see exactly the same behavior that you are showing in a cell.

![Jun-05-2020 13-53-35](https://user-images.githubusercontent.com/323878/83912751-fbeceb00-a733-11ea-87ec-2d1738ad64c8.gif)

**Comment by JacksonKearl** [comment]
You're right, I am able to repro in other editors now.

**Comment by roblourens** [comment]
🤷‍♂️
