### ISSUE TITLE
Notebook: Esc doesnt cancel selection

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#99184]
Testing #98985

In other parts of the UI, pressing Esc in an embedded editor (peek, for instance) first cancels its selection, then blurs the entire embedded editor. In a notebook cell is first blurs the editor so the selection cannot be cleared with Esc. I think the defualt binding `when` should be changed to exclude when the cell has a selection.

**Comment by roblourens** [comment]
Ah good catch
