### ISSUE TITLE
vscode.window.showInputBox returns undefined when current window changes In VSCode Insider

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#9918]
- VSCode Version: Insider 1.4.0
- OS Version: Win 10

There is different behavior I'm facing in VScode insider build. When i open any page in browser and open a input box , after page opens and current window changes automatically to browser the promise for show input box returns undefined.

It is working fine in the current normal build of VSCode

Would you please tell me how to tackle such thing as i think it will go to the current build of VScode.

**Comment by shanalikhan** [comment]
Also will be behavior will go to stable build ?

**Comment by mrmlnc** [comment]
As far as I know, this is normal behavior. When the input field loses focus, the editor returns undefined. This change is related to https://github.com/Microsoft/vscode/commit/7c6e9672cd49e73a19953e8d72dd9b27ed61fef4 (@jrieken) and #8449.

**Comment by jrieken** [comment]
Yes - the _new_ rule is to hide the input box when focus is lost. We had a hard time coming up with cases in which we want to keep it open @shanalikhan What is you use case in which you want to keep the input box open? Also note that this is different to other related UIs (command palette, quick pick etc) that all close on focus lost

**Comment by shanalikhan** [comment]
@jrieken My Extension "Visual Studio Sync" was failing for insiders when it opens browser window to let use do something and copy the token from there and paste in input box , the input box already closed and provides undefined.

So i had to use keyword "esc" in order to close the input box and else it will continue show until user write anything in it. Its working fine now user is bound to write some identifier to close it.

**Comment by jrieken** [comment]
Makes sense. We should expose this as an option in the API

**Comment by shanalikhan** [comment]
Great, thanks :)

**Comment by jrieken** [comment]
@bpasero It doesn't seem like the `quickOpenController` it fit for this. I can expose the `ignoreFocusLost` property but then the logic of closing an active pick session when a new one starts doesn't work anymore (despite it working with a focus loss)

**Comment by bpasero** [comment]
@jrieken so you say when `ignoreFocusLost` is set, the picker does not open with a different picker configuration if triggered?

**Comment by jrieken** [comment]
@bpasero I believe the root of evil is that there is a `quickPickWidget` and a `quickOpenWidget` in the controller and that they don't really know of each other. It seems that the toggle between them relies on losing/gaining focus. Unsure why we have those two widget instances in there?

**Comment by bpasero** [comment]
Yeah two worlds since day one because the quick open controller was doing so many things already that are not needed for the picker... that area is a sinkhole of debt (that many developers had fun with in the past)

**Comment by bpasero** [comment]
@jrieken real fix is in https://github.com/Microsoft/vscode/issues/10362. Workaround that could do it for now is something like:

```typescript
onShow: () => {
	this.inQuickOpenMode.set(true);
	this.emitQuickOpenVisibilityChange(true);
	if (this.pickOpenWidget) {
		this.pickOpenWidget.hide(HideReason.FOCUS_LOST);
	}
}
```

In the `onShow()` handler of the quick open widget (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/quickopen/quickOpenController.ts#L459).

However, needs verification what kind of result is being returned to the extension host. I see we have different hide reasons (`FOCUS_LOST`, `CANCELED`) and depending on which one is used, the result can be different. I am a bit puzzled why a `FOCUS_LOST` reason would trigger the onOk handler in https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L723. Maybe an oversight when `FOCUS_LOST` was added.

**Comment by jrieken** [comment]
I will give it a try

> I am a bit puzzled why a FOCUS_LOST reason would trigger the onOk handler in https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L723. Maybe an oversight when FOCUS_LOST was added?

I don't think that I wrote that code...

**Comment by jrieken** [comment]
Now, clue how this should work because the input box isn't really modal. That means when you get back to VS Code the input box is still open but you focus the editor and type behind it etc. The label still says press `Enter`/`Esc` but those aren't globally bound but need focus.

@bpasero @stevencl ideas?

**Comment by bpasero** [comment]
@jrieken yes, not an ideal UI but I can do the same in ST by opening quick open and type in the editor under it, some people even ask for this being the default behaviour for quick open in general. 

I think one issue is that we start to make quick open a thingy to let the user type input (there is another request to allow for a more dialog like experience). Eventually we should bite the bullet and make a dialog API that can be presented modal if needed. Putting everything into quick open seems wrong to me.

**Comment by jrieken** [comment]
Not saying that the ST behaviour is bad, but at least `Esc` should then always close it (no matter of where focus is). Like we do it for info/warning/error messages

**Comment by bpasero** [comment]
Agree. We already have a context key for when quick open is visible, but it is not being used by picker widget. I want to look into simplifying quick open, not sure if I find the time for August, but that would be another reason to merge both widgets into one.

**Comment by jrieken** [comment]
Ideally, the widget looses a ton of weight and dismiss/accept is handled by the controller. That makes the widget less of a viewer+controller and also would allow users to reconfigure those commands

**Comment by bpasero** [comment]
I pushed some changes that improve this behaviour:
* cleaned up the confusion with HideReason as outlined in https://github.com/Microsoft/vscode/issues/9918#issuecomment-238657888
* added a global key handler to close quick open (or the picker) when you press `Escape`
* close quick open when the picker is opening and vice versa

This also helps for https://github.com/Microsoft/vscode/issues/444 to introduce a general setting to keep quick open and picker opened even when not focused.

**Comment by shanalikhan** [comment]
Is it available on the stable build yet ?

**Comment by jrieken** [comment]
No - on our calendars `August 2016` is not yet over. Still, you can try that with the [insider build](https://code.visualstudio.com/insiders) we publish once per day.
