### ISSUE TITLE
Should filter on type effect which files are reverted/staged by scm operations?

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#99183]
Testing #99019

**Repo**
1. In a git repo with a few changed files.
1. Open SCM view and enable filter on type
1. Filter the list down so only a few changed files are disabled
1. Now try using one of the top level operations, such as `discard all changes` or `stage all changes`

**Question**
Should these operations only operate on the visible files? I almost lost some work because I triggered `discard all changes` without realizing I had already filtered the list of visible files down

**Comment by joaomoreno** [comment]
Oooof this is pretty much impossible to fix today, since `Discard All Changes` is a command which doesn't get passed any resources.
