### ISSUE TITLE
Notebook: Split/Join cell arent properly Undoable

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#99194]
Testing #98985

Split cell. Attempt to undo. Newly inserted cell gets deleted, but the text doesn't return to the old cell. 

Similar, Join cell. Attempt to undo. Joined cell gets restored, but the newly added content isn't removed from the current cell.

**Comment by rebornix** [comment]
\closedWith cc937a368cdd37a55a27a4ac916ecd7ce0dcfe0a
