### ISSUE TITLE
VS Code Insiders still uses vscode-resource protocol, but bans CORS requests with that scheme.

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#99190]
#97777 does not seem to work properly.
`webview.asWebviewUri(...)` still returns a uri with the `vscode-resource` scheme, but CORS requests to `vscode-resource` uris are already blocked.

Version: 1.46.0-insider (user setup)
Commit: 1bfa086adb9271ff56be11821da686e4cfffb672
Date: 2020-06-02T06:55:33.079Z
Electron: 7.3.0
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

![image](https://user-images.githubusercontent.com/2931520/83572211-7138a000-a529-11ea-8bdc-ede0db681df3.png)

![](https://user-images.githubusercontent.com/2931520/83571717-91b42a80-a528-11ea-84ae-50b53ce02b32.png)

(https://github.com/hediet/vscode-drawio/issues/71)

**Comment by AlexZeitler** [comment]
Thanks for the reply. I’ll use VS Code with the extension until VS Code Insiders will have sorted things out.

**Comment by hediet** [comment]
Thanks for the fast fix ;)

But isn't `asWebViewUri` supposed to return a URI with `vscode-webview-resource` scheme (which it does not do in the current insiders)? Or is that just not shipped yet?

**Comment by mjbvz** [comment]
No, this broke because we effectively reverted #97777 but did not restore this place in the code where the old `vscode-resource` scheme had been configured. All uris still should be using `vscode-resource` for VS Code 1.46

**Comment by hediet** [comment]
Ah, thanks for the explanation ;) And thank you for supporting all this webview stuff! Seems to be quite nasty to support, but is invaluable for some really cool extensions!
