### ISSUE TITLE
Environment variables are not passed to debuggee proccess.

### ISSUE THREAD

**Issue by magpier84** [Microsoft/vscode#9919]
- VSCode Version:1.3.1
- OS Version:10.11.2
- C++ Tools 0.8.0

Steps to Reproduce:

1. Make default Launch C++ debug configuration
2. Run debug and check environment variables
3. Expected result: PATH, HOME etc variables set
4. Expected result: custom variables passed through launch.json set
5. Actual result: any variables aren't passed to debugee process.

**Comment by kieferrm** [comment]
@weinand not sure wether it's core or the C++ extension.

**Comment by weinand** [comment]
@kieferrm this is VS Code core problem #8434 and unrelated to debugging.
It is fixed in 1.4.0 and already available in the Insider.
A workaround is to launch VS Code from the command line.
