### ISSUE TITLE
Breaking into minified file during debugging causes prompt

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#99199]
refs #98989

This is what happened to me:

1. Start debugging vs code
2. Hit continue a bunch to skip some break points
3. Accidentally hit pause after no more breakpoints are hit

VS Code then stops in `xterm.js` which apparently has unusual line terminators.
:bug: => I now see a prompt about unusual line terminators.

**Comment by sbatten** [comment]
While I think this is a good fix for now, I suspect that debugging a file is not a time when you would want to make edits to it.

**Comment by alexdima** [comment]
Opening a file for debugging is 100% the same as opening a file for editing. If editors would be opened read-only by debugging, then this prompt would not show.
