### ISSUE TITLE
editor.rulers is ignored

### ISSUE THREAD

**Issue by CleanCut** [microsoft/vscode#99197]
Issue Type: <b>Bug</b>

`editor.rulers` is entirely ignored. There is always a vertical rule between column 78 and 79.

VS Code version: Code - Insiders 1.46.0-insider (1bfa086adb9271ff56be11821da686e4cfffb672, 2020-06-02T08:10:00.819Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (0.91GB free)|
|Process Argv|-psn_0_614550|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by ArturoDent** [comment]
It would help if you included your `editor.rulers` setting.  And do you get the vertical if you have no `editor.rulers` at all?

**Comment by connor4312** [comment]
Yes, please share both your user and workspace settings. Thanks!

/needsMoreInfo

**Comment by CleanCut** [comment]
@ArturoDent @connor4312 Sure thing, here you go.

Workspace settings is simply:
```
{
}
```

My user settings: [settings.json.zip](https://github.com/microsoft/vscode/files/4724998/settings.json.zip)


Inside of the user settings, I have (among other things): 
```
    "editor.rulers": [
        100
    ],
```

If I delete that setting, the vertical ruler between 78-79 disappears, but if I have that present with any value, then the ruler between 78-79 reappears (and no other ruler).

**Comment by CleanCut** [comment]
With today's build, everything works, even before making any of your changes. I wasn't in a handlebars file.  🤷‍♂️
