### ISSUE TITLE
Should nested panels have a clear boundary delimiter

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#99206]
Testing #98994

When you have multiple nested panels, the faint vertical line doesn't line up with the right edge of the panel. This is confusing when you are trying to resize a panel horizontally and you think the vertical line is the drag point.

Here you can see that the vertical line is directly under the last Output panel button.

![image](https://user-images.githubusercontent.com/12818376/83583023-0e7ae080-a4f8-11ea-8619-0a42afebe9e8.png)

**Comment by gregvanl** [comment]
OK, this vertical line is special to the Output panel and is the faint outline of a scroll bar. I'll repurpose and rename this issue to be that there isn't a clear boundary between nested panels. This makes it hard to see which buttons apply to which panel and where to grab the panel to resize.

**Comment by gregvanl** [comment]
Some sort of vertical boundary would also help with the collapsed case, where the chevrons and icons appear floating in space rather than being in a contained panel.

![image](https://user-images.githubusercontent.com/12818376/83583751-0de34980-a4fa-11ea-9c6f-07f7c8bd11bd.png)

**Comment by ornellaalt** [comment]
on macOS, there are lines between (ignore the weird "unsaved" text snippet, filing an issue for that now)
![image](https://user-images.githubusercontent.com/44654695/83650506-6bbd7300-a586-11ea-9cd1-04aaec49ff2b.png)

**Comment by gregvanl** [comment]
Looks like vertical delimiters have been added in the latest Insiders Commit: 595d2b9b916d063aadfc2c1a8c8f6df5b45572a8

Looks good!

**Comment by sbatten** [comment]
I am not sure what changed here, I added theme keys and defaults for the panel borders a while ago. In today's insiders things seem to be working. Can you verify @gregvanl ?

**Comment by gregvanl** [comment]
@sbatten Looks good to me.

![image](https://user-images.githubusercontent.com/12818376/83665035-b5568f80-a57f-11ea-9224-20457d32ac06.png)

**Comment by sbatten** [comment]
adding verified as per @gregvanl
