### ISSUE TITLE
Hard to move WebView tab down to open a new editor group

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode#99208]
- VSCode Version: 1.45.1
- OS Version: macOS 10.15.5

Steps to Reproduce:

1. Create a WebView with the following HTML where `url` is any localhost http server address (as done in https://github.com/Ikuyadeu/vscode-R/pull/353):

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    html, body {
        height: 100%;
        padding: 0;
        overflow: hidden;
    }
  </style>
</head>
<body>
    <iframe src="${url}" width="100%" height="100%" frameborder="0" />
</body>
</html>
```

2. Move down the WebView tab and it is almost impossible to create a new editor group in this way. User has to split down to create a new editor group below and move the tab there.

The following screencast demonstrates this problem more clearly:

![Kapture 2020-06-03 at 9 02 54](https://user-images.githubusercontent.com/4662568/83584598-3448c980-a57a-11ea-83bf-3f4c8d34c098.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by renkun-ken** [comment]
Yes, it is reproducible in the latest VSCode insiders build. I also tried on Ubuntu and there's no such problem. It seems that it is only problematic on macOS.

**Comment by mjbvz** [comment]
This seems to be related to your use of an iframe that covers the entire webview content; it does not happen for me in normal webviews

**Comment by renkun-ken** [comment]
Yes exactly. A normal non-iframe WebView does not have this problem.

**Comment by renkun-ken** [comment]
This problem no longer occurs with the latest release of vscode (1.55.0). Closing now.

**Comment by renkun-ken** [comment]
The problem no longer exists in the latest release of vscode (1.55.0). Closing now.
