### ISSUE TITLE
codebugging with vscode liveshare

### ISSUE THREAD

**Issue by carlosaicrag** [microsoft/vscode#99207]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. launch a vs code live share session 
2. invite a participant 
3. write a simple javascript function and place a debugger within it
4. start a debugging session
 what you'll notice is that the host will be able to debug but the invitee will not be able to.
the debugging console shows up but that's about it. 

I work as an instructor at app academy coding Bootcamp and I've seen it work with just one student.  One thing to note is that the student had recently gotten a new MacBook. other than that I see no difference between my computer and his computer.  Another thing to note is that it works when he shares the liveshare session with me but it doesn't work when I share a liveshare session with him.  I would really like for this to be fixed asap as it will serve as a great tool for the pair programming experience the students have with one another. especially during this time where we cannot be in person.  Thank you in advance for looking into this and please reach out if you have any questions about what i've described.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by connor4312** [comment]
Please file this issue over on the live-share repo. Their issue template also has instructions that will provide better info to help solve the problem: https://github.com/MicrosoftDocs/live-share/issues/new?template=bug_report.md

\extLiveshare
