### ISSUE TITLE
Kill Code Helper. Sucking up all the memory and CPU

### ISSUE THREAD

**Issue by timothymarois** [microsoft/vscode#99201]
All previous duplicated threads have been disabled. So here's another... 

**How do I disable code helper?** This is sucking up all the memory and all the CPU. Shut it down! 

#51776 and #11096

**Comment by connor4312** [comment]
Please see our wiki page with details on how to provide info for performance issues 🙂  https://github.com/microsoft/vscode/wiki/Performance-Issues

/needsMoreInfo
