### ISSUE TITLE
Can't drop view into Container with Open Editors

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#99200]
Testing #98994

1. Drag Open Editors to the Activity Bar to create a new view container
2. Go back to Explorer and try to drag either the Outline or Time views into the new container.

The new view container is displayed but you can't drop the dragged views there. You can drop the dragged view into other containers such as Search, Debug, Remote.
You also can't drop the view in the Extensions view container but perhaps this is a known limitation.

**Comment by eamodio** [comment]
This also affects the breakpoints view
