### ISSUE TITLE
Clicking a second time under expand chevron doesn't collapse panel

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#99205]
Testing #98994

When a clicking under the expand chevron for a collapsed panel, the panel expands. Clicking again at the same location doesn't collapse the panel.

It might be better if the only way to toggle the panel expand/collapse state was via the expand/collapse chevron. It may be convenient to be able to click anywhere in the collapsed column but it is confusing especially as the user may think that clicking the panel icon is opening the panel.

**Comment by sbatten** [comment]
i hesitate to change the behavior of clicking anywhere in the header because it is consistent with the side bar. in the side bar there are also cases where clicking the header moves it so clicking again in the same location would not work
