### ISSUE TITLE
Easily switch between Settings UI and `settings.json` by reusing the shortcut

### ISSUE THREAD

**Issue by bramus** [microsoft/vscode#99213]
When hitting `CMD`+`,`, the settings UI opens. It'd be neat/handy if upon hitting `CMD`+`,` **again**, it'd swap out the settings UI for the `settings.json` file.

**Comment by roblourens** [comment]
You can set up a separate keybinding to open the json file (I use `alt+cmd+,`), or you could even set up a `cmd+,` keybinding to do that using a when clause to only activate when the settings UI is open. I don't think I want to do this out of the box by default though.
