### ISSUE TITLE
Allow a different focusBorder for panel title

### ISSUE THREAD

**Issue by simurai** [microsoft/vscode#99210]
### Problem

When clicking on a panel title the `focusBorder` (blue) is shown while in the "pressed state". User feedback was that it's "too much colors" since the theme uses a coral color for `panelTitle.activeBorder`.

![img-2020-06-03-10 29 33](https://user-images.githubusercontent.com/378023/83585600-38c6af80-a585-11ea-93e4-64f036f428a4.gif)

### Possible solution

1. Add something like `panelTitle.focusBorder` to override the global `focusBorder`. Although I think that would be the only place that has a custom focus color.
2. Not show a border in the "pressed state". Same behaviour as the activity bar.
3. Use `panelTitle.activeBorder` also for the "pressed state". Like editor tabs.
4. Close as "wontfix". The theme would have to choose colors for `panelTitle.activeBorder` and `focusBorder` that don't clash as much.

**Comment by misolori** [comment]
Thanks for listing out the possible solutions! I do think that 2 & 3 are doable. I’d be more in favor of going with 3 so it’s a consistent behavior. @aeschli thoughts?

**Comment by misolori** [comment]
@bpasero thoughts on whether we should make the panel titles consistent with the activity bar? There would be no focus border on the clicked state but would still appear on keyboard navigation.

![Kapture 2020-06-09 at 10 31 36](https://user-images.githubusercontent.com/35271042/84180538-85563300-aa3c-11ea-96e8-b6b16cb3bf09.gif)

**Comment by bpasero** [comment]
Yeah that probably makes sense, + @isidorn for feedback

**Comment by isidorn** [comment]
Makes sense to me. Focus border on clicked state can be removed.
As for keyboard navigation focus color is that the exact same blue that we use for focus in other places? Asking because in the gif it looks a bit lighter and than it should.

**Comment by isidorn** [comment]
I can verify that we removed the border on click which I like.
What I do not like: have a focused panel, click on it's title -> the border turns from black invisible to blue.
Feels like a bug, thus reopening.

In the gif below I am clicking on the title

![recording](https://user-images.githubusercontent.com/1926584/86132004-a1526f00-bae6-11ea-95d0-935045f0353e.gif)
