### ISSUE TITLE
Dragging a collapsed view from the panel doesn't always work

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#99211]
Testing #98994

I haven't been able to reproduce this 100%, but it happens somewhat frequently (especially, maybe only?, if you are dragging the chevron.

In my setup, I had the timeline and debug console in the same container in the panel, and then with the timeline collapsed, I tried dragging the timeline (from the chevron) to the panel bar -- sometimes it will move and sometimes it won't.

**Comment by sbatten** [comment]
can you get a gif?

**Comment by eamodio** [comment]
Of course now that I am trying to capture it, I can't repro anymore. I'll re-open if I see it again.
