### ISSUE TITLE
Extension host crashes

### ISSUE THREAD

**Issue by madhusudanbabar** [microsoft/vscode#99218]
Issue Type: <b>Bug</b>

whenever i try to import a scss file into another file and start typing the name of file the extension hosts crashes everytime.
 - If i copy paste the exact name of the file then everything works fine, 
- autocompletion also works fine but while manually typing the path the extension host crashes.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
aessoft-class-autocomplete|AES|0.1.0
vscode-angular2-files|ale|1.6.2
html-class-suggestions|And|1.0.7
ng-template|Ang|0.901.9
vscode-color|ans|0.4.5
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.0.0
auto-close-tag|for|0.5.7
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.3
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.5.0
plantuml|jeb|2.13.12
vscode-peacock|joh|3.7.2
node-module-intellisense|lei|1.5.0
Kotlin|mat|1.7.1
vscode-language-babel|mgm|0.0.27
powershell-preview|ms-|2020.6.0
debugger-for-chrome|msj|4.12.8
angular2-inline|nat|0.0.17
color-highlight|nau|2.3.0
vscode-html-scss|P-d|0.0.42
material-icon-theme|PKi|4.1.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
html-preview-vscode|tht|0.2.5
python|tht|0.2.3
pdf|tom|0.6.0
vscodeintellicode|Vis|1.2.7
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.8.0
vscode-java-saber|You|0.1.1

(4 theme extensions excluded)

</details>

**here's the error**
``` 
Error: Import "tbd" could not be resolved.
    at File.load (D:\Projects\vscode-ext-color-highlight\node_modules\file-importer\index.js:130:1)
    at D:\Projects\vscode-ext-color-highlight\node_modules\file-importer\index.js:136:1
    at FSReqCallback.oncomplete (fs.js:165:21)
```
**here's screenshot**
![Screenshot (12)](https://user-images.githubusercontent.com/28552728/83603306-d58f4a00-a591-11ea-9894-dbdee80f1fb3.png)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by madhusudanbabar** [comment]
Can't rely on insider build as i got so many errors like this on ``` System Installer 64bit```
```
c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\search\node\searchApp.js

An error occurred while trying to read the source file:
The source file is corrupted
```


now trying with User Installer build.

**Comment by bpasero** [comment]
Ok

**Comment by madhusudanbabar** [comment]
no issues with insider build - User installer variant

i tried with all the previous extensions installed, but no issues,
everything worked fine.

**Comment by madhusudanbabar** [comment]
same thing here,
actually the issue is with **color highlight** ```naumovs.color-highlight``` extension

here again the extension host crashed

**Comment by bpasero** [comment]
OK can we try to extract the crash dump if any:
* close all code instances
* `code-insiders --crash-reporter-directory <absolute path>`
* do things that lead to crash
* see if there is a crash dump produced

**Comment by madhusudanbabar** [comment]
[crash.zip](https://github.com/microsoft/vscode/files/4722036/crash.zip)
here's the zip file

**Comment by bpasero** [comment]
Too bad, no dump got produced somehow. But you already identified an extension causing this?

**Comment by madhusudanbabar** [comment]
yes

**Comment by madhusudanbabar** [comment]
what should i do next?
shall i report it to the extension dev?

**Comment by bpasero** [comment]
@alexdima can maybe chime in to take note of this extension host crash, I feel filing an issue to the extension developer is good, but it would still be worthwhile understanding why that brings down the extension host.

**Comment by alexdima** [comment]
@bpasero I looked up exit code 7 for nodejs and it is:

![image](https://user-images.githubusercontent.com/5047891/83681315-858ca380-a5e2-11ea-83ba-cc58eee33006.png)

(from https://github.com/nodejs/node-v0.x-archive/blob/master/doc/api/process.markdown#exit-codes)

It is possible that there is an exception thrown by an extension and another extension has registered a broken uncaught exception handler. Or is our uncaught exception handler broken?

@madhusudanbabar Does this crash consistently reproduce for you when having only the `naumovs.color-highlight` enabled? We should reach out to the extension author and ask them to investigate.

**Comment by madhusudanbabar** [comment]
I tried with only ```naumovs.color-highlight``` and there was no crashes

But after that i enabled my extensions one by one and the time of extension **Live Sass Compiler** ```ritwickdey.live-sass``` it crashed again

**Comment by madhusudanbabar** [comment]
it keeps crashing while these 3 extensions enabled.
1. **Color - Highlight** ```naumovs.color-highlight```
2. **Live Sass Compiler** ``ritwickdey.live-sass``.
3. **Live Server** ``ritwickdey.liveserver`` ( I can't disable this as ```Live Sass Compiler``` depends on it ).

**Comment by bpasero** [comment]
@alexdima 

> It is possible that there is an exception thrown by an extension and another extension has registered a broken uncaught exception handler. Or is our uncaught exception handler broken?

Maybe, and now I wonder if there should be another override (as we e.g. do for `process.exit`) to not allow extensions to register a handler if this actually can cause a crash of node (would have to validate this theory). On the other hand, it seems OK that an extension could participate in these events if behaving correctly.

**Comment by bpasero** [comment]
No I cannot reproduce this exit code, tried with sample code:

```js
process.on('uncaughtException', function (err) {
    console.log(err.super());
});

process.on('unhandledRejection', function (err) {
    console.log(err.super());
});

setTimeout(async () => {
    // throw new Error();

    const p = new Promise((resolve, reject) => {
        reject(new Error("foo"));
    });

    await p;
}, 1000);
```
