### ISSUE TITLE
"files.autoSaveDelay" lower than 1000ms seems to be instant but not for that larger than 1000

### ISSUE THREAD

**Issue by singularitti** [microsoft/vscode#99212]
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

Steps to Reproduce:

1. Change `"files.autoSaveDelay": 1000,` to lower or larger than 1000 in settings
2. Change any text in the code editor to feel the delay by observing the full circle in the tab

![image](https://user-images.githubusercontent.com/25192197/83594299-e063c380-a52c-11ea-8eeb-5a4719101860.png)

If you set it too any number `< 1000`, the autosave feels instantly, seems to be no delay at all. But if larger than `1000`, even if `1001`, it feels delays about 1 second. This is kind of inconsistent to me. Not sure if this is a UI inconsistency.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
For historic reasons, the dirty indicator hides if auto save is <1s because I cannot stand it.

**Comment by singularitti** [comment]
> For historic reasons, the dirty indicator hides if auto save is <1s because I cannot stand it.

Ah, I see, so it is not saved instantly. It just doesn't show the indicator.

**Comment by bpasero** [comment]
Yes exactly.
