### ISSUE TITLE
C# preprocessor expressions highlighting is inconsistent

### ISSUE THREAD

**Issue by vors** [Microsoft/vscode#9921]
- VSCode Version: 1.3.1
- OS Version: OS X El Capitan

Steps to Reproduce:

```csharp
#if UNIX
            // some code here
#else
            // some code here
#endif
```

![image](https://cloud.githubusercontent.com/assets/816680/17228267/31944fd2-54c7-11e6-9b66-90ef8285e486.png)

It's very inconsistent highlighting:
- `#` is highlighted in the first `#if`, but not elsewhere
- `if`and `else` highlighted (probably as a keywords), but `endif` not

**Comment by kieferrm** [comment]
Moved to https://github.com/OmniSharp/omnisharp-vscode/issues/630. @vors pls subscribe to the new issue.
