### ISSUE TITLE
"Search Editor" searches `.git` folder

### ISSUE THREAD

**Issue by bramus** [microsoft/vscode#99216]
When searching your codebase – either using the Search pane in the sidebar or through a Search Editor – VS Code will ignore some folders, such as the `.git` folder. However, when opening the search results from the sidebar in a Search Editor, it won't adhere to this behavior.

- VSCode Version: 1.45.1
- OS Version: Darwin x64 19.5.0

Steps to Reproduce:

1. Search for a term using the search in the sidebar
2. Click on "Open in editor"
3. In the opened Search Editor search for a new term (or the same term by focussing it and hitting RETURN)

Upon step 2 all goes well. However, upon searching for a new (or the same) term, VS Code will now also search folders such as `.git`. The screenshot below shows the result of the steps above:

<img width="1792" alt="Screenshot 2020-06-03 at 06 51 10" src="https://user-images.githubusercontent.com/213073/83597899-b4feca00-a568-11ea-9aba-c0838e555c38.png">

To be complete: When manually opening a Search Editor and searching with the same settings as in the screenshot, it does not search the `.git` folder.

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment]
\duplicate #97180
