### ISSUE TITLE
Allow to create scratchpads (scratchpad = do not save this file)

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#99214]
Issue Type: <b>Feature Request</b>

problem statement:
ever so often i am dealing with JSON, i open a new untitled file in vs code and select language mode as JSON and paste it in the file to see a well-formatted JSON. As I go along I keep pressing save all files and every time i click save all i get the popup to save my untitled JSON file. It is useful if I want to save the untitled file but in this case its just a scratchpad. I would very much love to have some way to mark files as a scratchpad and select language mode for them. 
in my case it is JSON however the language mode for scratchpad can be anything that is supported by vs code.

Please see if this is worth a feature.
thanks

Note: i realized scratchpad means something different. Here scratchpad means this will be a file and it will not be saved when its marked scratchpad. do-not-save-this-file, not sure what else to call this (one of the suggestions: Rough page/work). 

VS Code version: Code - Insiders 1.46.0-insider (1bfa086adb9271ff56be11821da686e4cfffb672, 2020-06-02T06:55:33.079Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Awbmilne** [comment]
I use VScode to reformat text **very often**, whether it be from a file open in VScode or a spreadsheet. The Multiline editing is **way** better than anything else ive found.

I would be great to have a shortcut for pulling up a new "scratchpad".

Other possibly useful settings.json config options:
- always open scratchpad in new split panel (right, left, up, down)
- scratchpad closes when it loses focus
- scratchpad persists through reload
- optional historic scratchpad list in explorer sidebar

Thanks for all the Great Work VScode people! 👍

**Comment by mohtamba** [comment]
I would be interested in attempting to create this feature.
