### ISSUE TITLE
Safer UI by re-arranging the grouping of context menu

### ISSUE THREAD

**Issue by MattWilcox** [microsoft/vscode#99229]
The horizontal breakers are functional not just aesthetic. They provide non-clickable buffer space. I have just accidentally deleted a file I wanted to rename that was not yet in GIT - because I was off by one or two pixels using my trackball.

Destructive UI elements should not be next to other UI elements, please re-group these to avoid this sort of issue in future.

![Screen Shot 2020-06-03 at 09 43 24](https://user-images.githubusercontent.com/814039/83616441-c1425180-a57f-11ea-8b73-4706e251ec35.png)

**Comment by sbatten** [comment]
From the OS level, at least checking in Windows, Delete and Rename are adjacent and not separated.

/cc @bpasero @alexdima

**Comment by alexdima** [comment]
Personally, I think destructive actions that cannot be undone should prompt. @MattWilcox did the delete not prompt in your case?

**Comment by sbatten** [comment]
/cc @isidorn 

This is controlled by this setting I believe `explorer.confirmDelete`

**Comment by MattWilcox** [comment]
> Personally, I think destructive actions that cannot be undone should prompt. @MattWilcox did the delete not prompt in your case?

Nope it didn't. I'd guess the default option is not to, as I've not changed that - but I think these are two separate things tbh. prompting confirms would really annoy me more often than help me. This is about minimising UI errors without introducing friction.

**Comment by isidorn** [comment]
Yeah this prompts by default.
Let me know if you can reproduce it not prompting with latest vscode insiders
We will not change order due to users muscle memory, and putting a seperator might work, I just do not like having one item separator groups since it looks ugly.

**Comment by MattWilcox** [comment]
I would argue that "looks ugly" is less of a concern than "data loss", but I do get your viewpoint :) There are already two single-item-groups in that menu.
