### ISSUE TITLE
VSCode randomly fails to highlight JavaScript inside HTML

### ISSUE THREAD

**Issue by FlatAssembler** [microsoft/vscode#99228]
- VSCode Version: 1.45.1
- OS Version: Oracle Linux 7

Steps to Reproduce:

1. Open this file using Visual Studio Code: https://github.com/FlatAssembler/FlatAssembler.github.io/blob/master/informatics.html
2. Scroll down to:
```
</center>
<script type="text/javascript">
```
![image](https://user-images.githubusercontent.com/46264381/83615581-0ddd5b00-a587-11ea-8f4e-46b91b9b5925.png)
I have tried to produce a minimal example, but I just couldn't figure out what's going on exactly. What's even weirder is that the same error appears to occur when using NetBeans (I've always assumed NetBeans and VSCode used different engine for syntax highlighting, but apparently they don't.), though not when using Eclipse.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
The problem is that the `svg` tag on line 837 is missing a `>`

So the grammar still thinks you are inside a svg tag and no JavaScript is detected.

**Comment by FlatAssembler** [comment]
But there is a `>` in the `</svg>` tag, it's just that Prettier put it in
the next line.

sri, 3. lip 2020. 22:00 Martin Aeschlimann <notifications@github.com> je
napisao:

**Comment by FlatAssembler** [comment]
OK, I will change my code, though I am not sure I disobeyed the standard by putting the `>` in the new line. Browsers don't seem to mind that.

**Comment by aeschli** [comment]
You are right, the HTML grammar should tolerate that. We have issue https://github.com/textmate/html.tmbundle/issues/97 for that.
