### ISSUE TITLE
Unable to change workspace folder name

### ISSUE THREAD

**Issue by fcl-gary** [microsoft/vscode#99225]
Issue Type: <b>Feature Request</b>

When I used F3 on the left to rename the folder name, it was always gray. After a long time, the gray mask disappeared, and the folder name still remained unchanged.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 6.1.7601

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
