### ISSUE TITLE
Checking out to new git branch outside vscode does not switch the branch in vscode

### ISSUE THREAD

**Issue by lokesh-paulpandi** [microsoft/vscode#99238]
- VSCode Version: 1.45.1
- OS Version: Darwin x64 19.3.0

Steps to Reproduce:

1. Use terminal to switch to a new branch. In the previous VSCode  version, it will automatically move to the branch in vs code.
2. In current version I have to manually switch branch in the VSCode application.
3. Had two tabs in terminal open for the same code base. 

Is this an issue or thats how it works?

**Comment by joaomoreno** [comment]
VS Code should update to the right branch once it gets focused. Can you reproduce this in any repository? Is your repository in a symlink or network share?

**Comment by lokesh-paulpandi** [comment]
My codebase is in my local machine. I am not able to replicate the issue in another repository. It only happens in the current repository. Will try to find a solution. We have the .vscode/ folder to git ignore . Would this in any way cause issue ?

**Comment by joaomoreno** [comment]
I wonder if you opened the repository with a different letter casing that its real one?

**Comment by lokesh-paulpandi** [comment]
I just have one repository with the name. Just found that when moving from one branch to another using terminal the codes in the VSCode changes , but the branch name which is being displayed in the lower left corner doesn't change at all.

<img width="230" alt="Screen Shot 2020-06-05 at 2 05 24 PM" src="https://user-images.githubusercontent.com/39794861/83855390-9c8fda80-a735-11ea-81b5-b255a2cdb0ee.png">

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the Source Control view?

**Comment by lokesh-paulpandi** [comment]
Source Control : 
<img width="627" alt="Screen Shot 2020-06-05 at 3 13 23 PM" src="https://user-images.githubusercontent.com/39794861/83918760-fffe2480-a796-11ea-8fe0-fe50f3b27907.png">

Current branch in terminal 
<img width="306" alt="Screen Shot 2020-06-05 at 3 04 48 PM" src="https://user-images.githubusercontent.com/39794861/83918809-15734e80-a797-11ea-9e5d-a99554fe52f4.png">

Branch in VSCode
<img width="313" alt="Screen Shot 2020-06-05 at 3 06 04 PM" src="https://user-images.githubusercontent.com/39794861/83918852-2ae87880-a797-11ea-9b5a-d7a07c32f67e.png">

Switching to other branch
<img width="495" alt="Screen Shot 2020-06-05 at 3 05 50 PM" src="https://user-images.githubusercontent.com/39794861/83918896-3cca1b80-a797-11ea-8bd3-bce800dde49b.png">

Still branch remains the same
<img width="309" alt="Screen Shot 2020-06-05 at 3 05 14 PM" src="https://user-images.githubusercontent.com/39794861/83918934-4d7a9180-a797-11ea-9168-6b56985cff98.png">

Swithching to another branch from VSCode gets reflected in the terminal
<img width="591" alt="Screen Shot 2020-06-05 at 3 06 32 PM" src="https://user-images.githubusercontent.com/39794861/83918963-59665380-a797-11ea-9174-a55e048a4a9d.png">

**Comment by joaomoreno** [comment]
Are you sure this is exactly the same repository? Does the branch name update if you restart VS Code?

**Comment by lokesh-paulpandi** [comment]
Yes , it is the same repository. The branch name updates if I restart VSCode and if I switch to a different branch in VSCode , it gets reflected in the terminal.

**Comment by joaomoreno** [comment]
> Not sure if branch is taking more time to get reflected in VSCode, but sometimes I see the branch that I have checked out to in VSCode if I haven't opened it for sometime.

It should take at most 10 seconds, and VS Code needs to be the focused application. Can you check?

**Comment by lokesh-paulpandi** [comment]
Hi joaomoreno, yes I think that is the issue. It takes more than 25 seconds for that to happen not sure about the reason and only recently the time has increased after the latest VSCode update. Thanks for you help.
