### ISSUE TITLE
VSCode not detecting repo on local server using SSH

### ISSUE THREAD

**Issue by AlexKalopsia** [microsoft/vscode#99239]
- VSCode Version: 1.45.1
- OS Version: Win10 

I have a local server called SUN (Linux-based) that I connect to from my Win computer. It's a mapped drive /X: . I've opened the /X: folder and did a `git init`. Repo is created and Source Control finds it with no issue.

Now to the problem.

I've connected to /X: via SSH now using a remote connection. I can normally navigate through the folders with no issue BUT Source Control doesn't detect the repo, even though it's clearly there.

If I do `git init` I get `Reinitialized existing Git repository in /volume1/.git/`
If I do `git add .` or `git diff` I get `fatal: Invalid path '/SUN': No such file or directory`

Steps to Reproduce:
1. Map drive to local server
2. Open folder (as mapped drive) and `git init`
3. Source Control will detect the repo
3. Close VSCode and open a new session
4. Connect to local server via SSH
5. Source Control will not detect the repo

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Have you tried our Remote SSH features? https://code.visualstudio.com/docs/remote/ssh

**Comment by AlexKalopsia** [comment]
@joaomoreno I am already connecting via SSH using the Remote SSH extension. 
My current solution has been to connect via SSH, delete the .git folder, re-initialize it, and pull the remote again

**Comment by joaomoreno** [comment]
> My current solution has been to connect via SSH, delete the .git folder, re-initialize it, and pull the remote again

I'm glad you fixed it that way. Ideally always use the tools (eg git) of the remote when possible.
