### ISSUE TITLE
scrollPredominantAxis not aggressive enough

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#99237]
1. Use an apple magic mouse
2. Scroll vertically in the editor
3. Ocasionally there is an unwanted horizontal drift

I noticed the `scrollPredominantAxis` setting which is turned on by default, but it does not seem to have any effect for me and my mouse.
An alternative would be to just turn off horizontal scrolling for me, but I can not do this on the OS level and neither on the VS Code level.

I have to use an apple magic mouse becuase other mouses stutter when connected via bluetooth.

**Comment by alexdima** [comment]
That one is implemented here -- https://github.com/microsoft/vscode/blob/2aae1f26c72891c399f860409176fe435a154b13/src/vs/base/browser/ui/scrollbar/scrollableElement.ts#L356-L362 -- so it is as aggressive as it can be, it picks the axis which has the highest absolute value and sets to zero the other axis.

It sounds like maybe you want a code path where any `deltaY` that is non zero, even if it is smaller than the `deltaX`, still leads to vertical scrolling. But IMHO that would make it very difficult to scroll horizontally when you intend to do so.

**Comment by isidorn** [comment]
@alexdima thanks for the pointer.
Yeah I would probably want if there is at least a `deltaY` ignore `deltaX`.

Though I think the actual issue is the magic mouse which I changed now.
Let's keep this open for a month and if nobody else wants this we can just close. 
Thanks!

**Comment by nashspence** [comment]
I'm using a Magic Mouse on Windows 10 with VSCode. I also find the horizontal scrolling to be too aggressive. Personally, I would like a way to disable horizontal scrolling with the mouse altogether without having to enable wrapping. Aside from that, thanks for the great editor and the work y'all do.
