### ISSUE TITLE
Improve error message when notebook type is unknown

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#99231]
Testing #98985

- install the Github notebook extension
- create a file `foo.github-issues`, open it and add some cells
- close the editor, uninstall the extension
- open the file

error shows:
`Unable to open 'foo.github-issues': Cannot open notebook of type 'github-issues'.`

Some more help would be great, such as an extension is needed to open
It would be great if it could tell me which extension is needed and guide me towards that extension in the extensions viewlet.

**Comment by rebornix** [comment]
![image](https://user-images.githubusercontent.com/876920/84094783-7034c200-a9b2-11ea-9006-57d4c676aede.png)

For now we will show a notification with action to reopen the file in text editor. Once we have marketplace integration, we can also recommend extensions.
