### ISSUE TITLE
Facing issue while starting VS code application on windows system

### ISSUE THREAD

**Issue by muleghanshyam1991** [microsoft/vscode#99243]
Issue Type: <b>Bug</b>

Hello Team,

I have installed VS code on Windows server and when i did Remote Desktop to that server and tried open VS code application it isn't opening but when i checked task manager i can see multiple instance for VS code.Could you help me to overcome this problem

**Comment by connor4312** [comment]
This is as intended -- vscode runs multiple processes, which will all appear in task manager.

**Comment by muleghanshyam1991** [comment]
@connor4312  As i ran above command in terminal it launches VS code and generates some line of text code and i thinks it is initialising VS code resources and workspace components

**Comment by connor4312** [comment]
Are you saying that VS Code launches successfully when you run that command, but not when you launch it from your desktop/start menu?

**Comment by muleghanshyam1991** [comment]
Sorry for delay in response. The issue has been resolved
