### ISSUE TITLE
Clean up the View menu

### ISSUE THREAD

**Issue by darkred** [Microsoft/vscode#9924]
- VSCode Version: 1.3.1
- OS Version: Win 10 x64

Steps to Reproduce:

1.  In `View` Menu the first 5 entries (Explorer, Search, Git, Debug, Extensions)  
are also available on the Side Bar as buttons. 
The Side Bar itself cannot be hidden, so its 5 buttons are always accessible.
2.  My suggestion is to put the `Command Palette` entry on top of the View menu.  
This would offer quicker access to Command Palette (which provides access to so many commands)
![2016-07-28_233903 2](https://cloud.githubusercontent.com/assets/723651/17229059/8a54d00e-551e-11e6-8dfd-3035a0324f86.jpg)

**Comment by bpasero** [comment]
@chrisdias @stevencl @bgashler1 fine by me, thoughts?

**Comment by stevencl** [comment]
It's fine by me too but I would like to also consider refactoring the View menu overall as it is getting quite large. I have some rough mockups that I can show at the UX meeting tomorrow.

**Comment by bpasero** [comment]
Ok, lets revisit tomorrow then 👍

**Comment by stevencl** [comment]
Let's just move the command palette up and think about refactoring the rest of the menu later if we get more feedback that it really is too busy.
