### ISSUE TITLE
Status bar: gets outline on click

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#99248]
When I click anywhere into the status bar outside of an entry, I see the status bar taking focus and indicating this with an outline. This feels a bit weird to me, we do not seem to be doing this in other places (e.g. activity bar). 

Is this something we must have or could we simply focus the first entry? Similar to how the activity bar has a focused entry?

**Comment by isidorn** [comment]
I do agree we should be consistent with the activity bar.
And clicking anywhere in the activity bar produces no results, it currently does not focus the first entry.

Focuses the whole outline should happen if we F6 into it, so the screen reader would read all the content. Just mouse clicking it is fine not to do that.

Anyways closing this as dup of https://github.com/microsoft/vscode/issues/97610
Once we decide what to do for activity bar we should do the same for status bar
