### ISSUE TITLE
onDidChangeNotebookCells is hard to work with

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#99241]
The `onDidChangeNotebookCells` event doesn't contain the cells that got removed (only index and length) making it very hard to handle cell removal, e.g extension need to keep and manage their own copy of cells. It would be better if the event contains cells that got deleted and added including their indices

**Comment by rebornix** [comment]
Added `deletedItems` in addition to `deletedCount`. If we finalize on `deletedItems`, then we can remove `deletedCount`. Currently I'm not 100% sure about it as we don't control the lifecycle the `NotebookCell` object completely (maybe we need then add `isDisposed` property to `NotebookCell`).
