### ISSUE TITLE
Notebook: Content Security Policy warning for images on remote

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#99251]
Testing #98985

Windows 10, WSL
- create a GitHub notebook in a folder on c: , have a `foo.png` image in the same folder
- add a Markdown cell with content `![Foo](./foo.png)`
- preview the cll, image is fine
- reopen the folder in a Remote - WSL window, open the notebook
- image broken, dev console says:
```
internal/process/task_queues.js:85 Refused to load the image 
'vscode-remote://wsl%2Bubuntu/mnt/c/workspaces/testing/notebook/foo.png' 
because it violates the following Content Security Policy directive: 
"img-src 'self' https: data: blob: vscode-remote-resource:".
```

**Comment by aeschli** [comment]
Maybe the same as https://github.com/microsoft/vscode/issues/96916

**Comment by roblourens** [comment]
Not sure about that issue - might just be from git lfs? Images work fine in a remote markdown preview for me in general.

But images don't work in remote notebooks, tracked in https://github.com/microsoft/vscode/issues/97759
