### ISSUE TITLE
Input cursor blinks in unfocused windows

### ISSUE THREAD

**Issue by jsumners** [microsoft/vscode#99256]
- VSCode Version: 1.45.1
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Have an unfocused VSCode window visible in the background
2. Switch between other applications, desktops, screen locked/unlocked state, etc. At some point, the cursor in VSCode will begin to flash as if the VSCode window is the focused window.

In this screenshot, the window with the flashing cursor _is not_ the currently focused window.

![cursor](https://user-images.githubusercontent.com/321201/83639706-14fd6c80-a579-11ea-9495-c13934d0de06.gif)

**Comment by risoms** [comment]
Just FYI - It sounds like it's due to an issue in chromium. 
https://github.com/microsoft/vscode/issues/82326
https://bugs.chromium.org/p/chromium/issues/detail?id=992319

**Comment by deepak1556** [comment]
Thanks @risoms 

/duplicate https://github.com/microsoft/vscode/issues/82326
