### ISSUE TITLE
Notebook: Error in dev tools when moving editor

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#99255]
Testing #98985

- create a Github notebook, open it besides an other editor
- drag the notebook below the other editor
- drag seems to have worked, but dev tools console says:
```
baseWebviewElement.ts:186 Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at HTMLElement.WebViewElement.getWebContentsId (web-view-impl.ts:222)
    at HTMLElement.send (web-view-impl.ts:259)
    at t.postMessage (webviewElement.ts:443)
```

**Comment by rebornix** [comment]
@deepak1556 @mjbvz I often see this error and since I'm just using the norma webview element, I don't know what I did wrong.

**Comment by deepak1556** [comment]
The error indicates a webview method is being called before the webview was attached to the DOM or either after webview was destroyed. The stack trace indicates its happening for `<webview>.send`.


We seem to anchor webview methods on presence of the webview element `this.element?.send` instead we should have a state that is updated when `dom-ready`, `close`, `destroyed` events are fired to use the webview methods safely.

**Comment by rebornix** [comment]
Found a stable reproduce with a notebook containing fancy html outputs. After the notebook is opened, click into the notebook, if you click on the webview, the preload main.js will emit `did-focus` message

https://github.com/microsoft/vscode/blob/6fef59565b0f0573b9ab60f2c0b23b9128374b40/src/vs/workbench/contrib/webview/browser/pre/main.js#L596

and then it will try to ignore menu shortcut on all webviews, which will lead to the error

https://github.com/microsoft/vscode/blob/6fef59565b0f0573b9ab60f2c0b23b9128374b40/src/vs/workbench/contrib/webview/electron-browser/webviewElement.ts#L234-L237

In this `WebviewKeyboardHandler` I don't see an existing way of checking `dom-ready` so need @mjbvz 's help here.

**Comment by rebornix** [comment]
It's actually a bug in Notebook. When we create webview we mount it to a detached DOM node which will be attached to DOM later on. Also we didn't dispose the webview properly after editor widget is closed. Both of which will contribute to this error message.

**Comment by deepak1556** [comment]
Awesome, thanks for addressing it 👍
