### ISSUE TITLE
Gear icon is not obvious to set default editor type

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99254]
Testing #99003

<img width="590" alt="image" src="https://user-images.githubusercontent.com/10746682/83638109-f4e5a180-a5a8-11ea-8746-a0d2b58105a8.png">

**Comment by misolori** [comment]
An alternative would be to use a similar pattern for selecting the language mode on a file and have a specific section for setting default/searching for new ones:

![image](https://user-images.githubusercontent.com/35271042/83693103-362a8100-a5aa-11ea-984c-71d7e0a3acec.png)

**Comment by misolori** [comment]
I'd also be in favor of setting the `Description` text in the custom editor quick pick to the secondary text so it's a single line (like language picker)
