### ISSUE TITLE
Bug: Icons and other things are bigger.

### ISSUE THREAD

**Issue by Skymmel** [microsoft/vscode#99260]
Issue Type: <b>Bug</b>

Visual Studio Code is corrupted. I was creating my own website and suddenly it got bigger. 
https://ctrlv.cz/Jbtz
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.2.1
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
discord-vscode|icr|3.14.0
vsliveshare|ms-|1.0.2236
material-icon-theme|PKi|4.1.0

(1 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
Can you please describe in more detail the issue you're facing?

/needsMoreInfo

**Comment by connor4312** [comment]
from the link:

![image](https://user-images.githubusercontent.com/2230985/83660338-90f7b480-a579-11ea-87c7-c750927b02b0.png)

**Comment by bpasero** [comment]
Looks like the zoom level is just very large, you can change it configuring `window.zoomLevel`

**Comment by Skymmel** [comment]
Thank you so much!
