### ISSUE TITLE
Cannot override the integrated shell setting in a workspace

### ISSUE THREAD

**Issue by rick3rt** [microsoft/vscode#99263]
- VSCode Version: 1.45.1
- OS Version: Windows 10 1909, 18363.836

Steps to Reproduce:

1. Set global `settings.json`:
```
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "terminal.integrated.shellArgs.windows": [
        "--login",
        "-i"
    ],
```
2. Set workspace `settings.json`
```
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "terminal.integrated.shellArgs.windows": [],
```
3. Open folder with `code . --disable-extensions`, open terminal with ctrl+` and see that the terminal is still bash and not cmd. Only able to switch the default terminal by setting the global setting.

Does this issue occur when all extensions are disabled?:  **Yes**

**Comment by Tyriar** [comment]
You can, you need to whitelist the workspace though. A notification will appear the first time to try to do it which lets you do this, if a notification isn't showing up, run the Manage Workspace Shell Permissions command:

![image](https://user-images.githubusercontent.com/2193314/83643795-53892c00-a565-11ea-947d-b49014180c44.png)

**Comment by rick3rt** [comment]
Thank you, that works. I could not find this is the docs, perhaps this could be added to https://code.visualstudio.com/docs/editor/integrated-terminal ?

**Comment by Tyriar** [comment]
@rick3rt there was some info there but it was out of date, fixed in https://github.com/microsoft/vscode-docs/commit/3646edf344a43bc2799d9a18e3b03b082831156a
