### ISSUE TITLE
Clearing numeric setting writes "null" to json

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#99268]
- Find a numeric setting (eg fontsize)
- Clear its input box
- "null" is written to json for that value
- Click out of the input box
- Get the error "Setting has an invalid type", and the control changes to "Open in settings.json"

Instead of writing null, we should unset it when validation fails, so you can still edit it in the GUI

![image](https://user-images.githubusercontent.com/323878/83644803-4aa15600-a577-11ea-9f35-34f885e57f9c.png)

**Comment by lszomoru** [comment]
@roblourens, tried to validate the bug and here is what I am seeing right now:
- Set the sash size setting from `4` to `20`
- Clearing the value of the setting will keep the value at `20`. 

Should clearing revert to the default value of `4` or keep the value of `20`?

**Comment by roblourens** [comment]
It should not change the value from what it was (so keep it at 20)
