### ISSUE TITLE
scm.inputFontFamily should suggest "editor" as a potential value

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#99269]
Currently `scm.inputFontFamily` suggests `default`, but does not suggest "editor".
It would be great if we also suggested "editor" as the value to make it more discoverable.

I think you can do this by making this setting an enum or a string in the json schema, and then list the enum values.

**Comment by lszomoru** [comment]
Does the Settings UI support an editable dropdown control since we do need to have the capability to select `default`, `editor` or enter an arbitrary value.

**Comment by isidorn** [comment]
It does not as far as I know. But we can still do the enum | string trick to get a nice suggestion for the settings json users and in the future the settings UI might support this hopefully.

**Comment by lszomoru** [comment]
@isidorn, please correct me if I am wrong but if we were to use type = string with an enum array, that would mean that in the JSON file we would get the suggestions for the value specified in the enum array, however we would get a warning squiggle in case an arbitrary string is specified which is not part of the enum. Is that acceptable behavior as it could cause some confusion. 
Do you know any other settings that follow the pattern that you are suggesting? Thanks!

**Comment by isidorn** [comment]
I only know of a explorer.autoReveal which is a `boolean` or a `string`. An `enum` or a `string` might not work nicely after all. I do not think it would be nice behavior after all.

So feel free to close this if it is not possible to not get a warning from the JSON schema.

also fyi @aeschli for ideas.

**Comment by lszomoru** [comment]
Closing the issue for now. Will reopen if @aeschli has any suggestions that would make this work.

**Comment by aeschli** [comment]
The schema must use `oneOf` something like
```json
{ "oneOf": [ 
  {
    "type":  "string"
  }, { 
    "type": "string", "enum": [ "editor", "..." ]
  }
]}
```

But I don't think the settings UI has a control for that.
