### ISSUE TITLE
Show the default editor in the picker

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99262]
Testing #99003

<img width="626" alt="image" src="https://user-images.githubusercontent.com/10746682/83642030-98858080-a5ae-11ea-8635-778e4e4ce04d.png">

I do not know what is the default configured editor from the picker

**Comment by bashdx** [comment]
Hello, 

I work with Code on a daily basis, but I can't figure out how where this picker would be located. Could you please elaborate? 
Thank you

**Comment by mjbvz** [comment]
Closing since we have not had any additional feedback since it was opened
