### ISSUE TITLE
Custom editor is not tagged deleted if file is deleted

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99270]
Testing #99003

<img width="657" alt="image" src="https://user-images.githubusercontent.com/10746682/83645775-26fc0100-a5b3-11ea-8888-a069d81707b6.png">

Example:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/10746682/83646025-6e828d00-a5b3-11ea-935c-e34df1c1e162.png">

**Comment by mjbvz** [comment]
For testing:

1. Run the [custom editor sample](https://github.com/microsoft/vscode-extension-samples/tree/main/custom-editor-sample)
2. Copy both the binary (`.pawDraw`) and text files (`.cscratch`) from `exampleFiles` into a new workspace
1. Also create a backup of these two files so you can restore them easily
3. For each file:
4. Open the file and make an edit. Do not save and ensure that the file is marked dirty
5. Now use the command line to delete the file
6. Confirm that the editor is now labeled `(deleted)`
7. Now restore the file
8. Confirm that the editor is no longer labeled deleted
