### ISSUE TITLE
Text snippet appears in bookend view 

### ISSUE THREAD

**Issue by ornellaalt** [microsoft/vscode#99278]
Testing #98994

1. Open file and make a change without saving
2. Drag open editors to output pane
3. Collapse to bookend view 

![image](https://user-images.githubusercontent.com/44654695/83650767-b50dc280-a586-11ea-80a0-9260bded98e1.png)

**Comment by misolori** [comment]
Verified, badge is gone when collapsed:

![image](https://user-images.githubusercontent.com/35271042/83790235-b3a6cd80-a64c-11ea-9bc3-2b7e773de203.png)
