### ISSUE TITLE
Cancel button is not in right spot when turning on sync

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#99274]
The cancel button is meant to be on the very right on Windows

![image](https://user-images.githubusercontent.com/2193314/83650121-d497f180-a56c-11ea-8675-de287d918cfc.png)

**Comment by sandy081** [comment]
This is shown correctly in Mac

<img width="677" alt="image" src="https://user-images.githubusercontent.com/10746682/83656486-e5258780-a5bf-11ea-9608-e9a3450e99be.png">

@bpasero Any idea why the order is getting changed by platforms? I am showing the dialog as follows:

https://github.com/microsoft/vscode/blob/ecafac21dbb45d43718bfa80d27b7abb9104695b/src/vs/workbench/services/userDataSync/browser/userDataSyncWorkbenchService.ts#L246-L256

Let me know if I have to do anything to change?

**Comment by bpasero** [comment]
@sandy081 different OS have different order of buttons. I suggest you check with user interface guidelines if you think something is wrong.

**Comment by sandy081** [comment]
I thought when I use `cancelId` the underlying dialogService takes care of showing the cancel button at right location based on OS?

**Comment by bpasero** [comment]
No, that property is for knowing what to trigger when the user hits `ESC` key for example.

**Comment by sandy081** [comment]
Well that's not true at least on Mac as it always shows cancel button second one from right

https://github.com/microsoft/vscode/blob/0bf375a847652d75535b41271521caa310520302/src/vs/workbench/services/userDataSync/browser/userDataSyncWorkbenchService.ts#L246-L256

<img width="665" alt="image" src="https://user-images.githubusercontent.com/10746682/83756326-33de2a80-a66f-11ea-8e3e-62f955e34d4e.png">
