### ISSUE TITLE
Notebook: Split cell not working when at end of content

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#99275]
Testing #98985
Version: 1.46.0-insider
Commit: 595d2b9b916d063aadfc2c1a8c8f6df5b45572a8
Date: 2020-06-03T05:33:25.873Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-51-generic

Split cell does not seem to work at times (I've seen it working, not sure what exactly makes the difference)

- have a Github issues notebook:
```
[{"kind":2,"language":"github-issues","value":"$current=milestone:\"May 2020\"\n$repo=repo:microsoft/vscode\n","editable":true},{"kind":2,"language":"github-issues","value":"$repo $current is:issue label:breadcrumbs","editable":true},{"kind":2,"language":"github-issues","value":"Nor all there","editable":true}]
```
- set cursor in first cell, split, nothing happend
- same for other cells

**Comment by aeschli** [comment]
![notebook-split](https://user-images.githubusercontent.com/6461412/83650157-506b5b80-a5b8-11ea-8668-bf120aa419db.gif)

**Comment by rebornix** [comment]
@aeschli what's your expected behavior of splitting a cell when the cursor is at the end of the document? Creating a new cell?

**Comment by aeschli** [comment]
Yes. That's better than a no-op.

**Comment by tanhakabir** [comment]
I see an empty cell being created on split in stable
