### ISSUE TITLE
Custom editor documentation 

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#99279]
Testing https://github.com/microsoft/vscode/issues/99003

The [`webviewOptions`](https://github.com/microsoft/vscode/blob/a276865712bc9faa2a350b4befba61874f02b5ae/src/vs/vscode.d.ts#L8036 )has no documentation comment, but the `supportsMultipleEditorsPerDocument` property right below it has a huge comment. It would be nice to have comment on the `webviewOptions`. 

Looks like there's a word missing here (... instead of reading the file _from_ this user's...): 
https://github.com/microsoft/vscode/blob/eb099962389a28a5f32490a530adae05b8d25851/src/vs/vscode.d.ts#L7025-L7026

I find this to be confusing. "and the resolve(d) document is passed to `resolveCustomEditor`". I think it should not refer to an already resolved document, since at this point the document is not "resolved" by `resolveCustomEditor`. Instead, may the "returned" document?

https://github.com/microsoft/vscode/blob/eb099962389a28a5f32490a530adae05b8d25851/src/vs/vscode.d.ts#L7046-L7049

For the documentation around `resolveCustomEditor` and `resolveCustomTextEditor`, I have trouble understanding what the `webviewPanel` is for just by reading the comment. Perhaps consider adding something about how the webview should be used for displaying the custom editor data.

https://github.com/microsoft/vscode/blob/eb099962389a28a5f32490a530adae05b8d25851/src/vs/vscode.d.ts#L7059-L7074

Would be good to give an example of where in the UI this would be shown:

https://github.com/microsoft/vscode/blob/eb099962389a28a5f32490a530adae05b8d25851/src/vs/vscode.d.ts#L6963-L6968

Unfinished sentence? 

https://github.com/microsoft/vscode/blob/eb099962389a28a5f32490a530adae05b8d25851/src/vs/vscode.d.ts#L7013-L7014

**Comment by alexr00** [comment]
Does this mean that `CustomTextEditorProvider`s automatically allow multiple editors, or that the never do?
https://github.com/Microsoft/vscode/blob/eb099962389a28a5f32490a530adae05b8d25851/src/vs/vscode.d.ts#L8038-L8051

Reading the docs [here](https://code.visualstudio.com/api/extension-guides/custom-editors#custom-editor-api-basics), it talks about how a single `TextDocument` can have multiple webviews if you split. Sounds like that means that `CustomTextEditorProvider`s automatically can have multiple webviews.

**Comment by alexr00** [comment]
The [docs page](https://code.visualstudio.com/api/extension-guides/custom-editors) is excellent!

**Comment by mjbvz** [comment]
Thanks for the suggestions. I believe I've addressed them all but let me know if anything in the docs is still unclear
