### ISSUE TITLE
vscode-languageserver-types repo/license doesn't exist

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9928]
While running OSS tool I hit this:

```
ERROR: vscode-languageserver-types@1.0.1: No license detail found at repositoryURL: https://github.com/Microsoft/vscode-languageserver-types-node
```

The repo https://github.com/Microsoft/vscode-languageserver-types-node (or https://github.com/Microsoft/vscode-languageserver-types) seems to not exist, though I'd linked to from other repositories and npm packages.

**Comment by aeschli** [comment]
The node modules source is at https://github.com/Microsoft/vscode-languageserver-node/tree/master/types and had the wrong repo URL in the 'repository' field.
I pushed a fix, but I guess the OSS tool will continue to show the error until we publish and bump the version. You can ignore the error until this happens.
