### ISSUE TITLE
The markdown.styles stylesheet must be contained inside the current workspace.

### ISSUE THREAD

**Issue by sgon00** [microsoft/vscode#99280]
The stylesheet must be contained inside the current workspace.

Closing as by-design

_Originally posted by @mjbvz in https://github.com/microsoft/vscode/issues/77290#issuecomment-515729785_

This design decision is wrong.

**Comment by mjbvz** [comment]
Please don't reopen issues unless you have something to add

**Comment by sgon00** [comment]
@mjbvz ok, the design decision is wrong. If I can only markdown.styles to current workspace, how can I add css styles globally? What is the proper way? I doubt many people want to add stylesheet in current workspace. This design decision just doesn't make sense. Thanks.
