### ISSUE TITLE
Notebook: Join cell doesn't see to work with empty cell

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#99282]
Testing #98985

Version: 1.46.0-insider
Commit: 595d2b9
Date: 2020-06-03T05:33:25.873Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-51-generic

- Create a Github issues notebook
`[{"kind":2,"language":"github-issues","value":"$current=milestone:\"May 2020\"\n$repo=repo:microsoft/vscode","editable":true},{"kind":2,"language":"github-issues","value":"ddd"},{"kind":2,"language":"github-issues","value":"$repo $current is:issue","editable":true},{"kind":2,"language":"github-issues","value":"Nor all there","editable":true}]`
- put cusor in a cell (e.g. `ddd`)
- Try the `Join` cell command, nothing happens

**Comment by lszomoru** [comment]
@roblourens, command is working but I think that the content should be adjusted. 

Actual:
`ddd$repo $current is:issue`

Desired:
```
ddd
$repo $current is:issue
```

**Comment by misolori** [comment]
I'm still seeing this when running a cell with an output and then trying to join:

![Kapture 2020-06-04 at 10 27 17](https://user-images.githubusercontent.com/35271042/83791153-31b7a400-a64e-11ea-8a27-5f26be34c2d5.gif)
