### ISSUE TITLE
Codicons are not supported in the view + view container icons in package.json

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#99284]
Testing #98996

I think we should support codicons in the view icons, just like commands as it will make it easier for extension authors to provide icons.

**Comment by KamasamaK** [comment]
Absolutely. It doesn't make sense to me that `icon` wouldn't be consistent throughout the various extension points.

As a result, currently the [npm extension](https://github.com/microsoft/vscode/tree/master/extensions/npm) unnecessarily duplicates the `code` Codicon as a bundled SVG.

**Comment by aeschli** [comment]
implemented by https://github.com/microsoft/vscode/issues/106348
