### ISSUE TITLE
Remove all unused code

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#99287]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode/issues/98997.

Early observations  for **Remove All Unused Code**:
- unused variables and members are removed
- code after a `return` statement is not
- unused parameters of a function declaration are removed but I'd like more fine-grained control here. For example, in `src/vs/code/electron-main/app.ts` we use parameter declarations for documentation purposes, and I also do this sometimes in my code. I would not want to lose those.

VS Code version: Code - Insiders 1.46.0-insider (595d2b9b916d063aadfc2c1a8c8f6df5b45572a8, 2020-06-03T05:38:33.098Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.3.0-1020-azure
Remote OS version: Linux x64 5.3.0-1020-azure

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/40922 to track adding a new TS Server api to better support this

**Comment by mjbvz** [comment]
Closing this in favor of the upstream TS issue. Will continue discussion there
