### ISSUE TITLE
Add missing imports: Respect organize import order

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#99285]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode/issues/98997.

1) Open the VS Code source
2) Open `/src/vs/code/electron-main/app.ts`
3) run **Organize Imports** on the file
4) Remove the last 10 lines of `import` statements
5) Run **F1 > Source Actions > Add Missing Imports**

Comparing the result of 3 with the result of 5 I would have expected to see no difference. This is not the case. Every time multiple imports are added to a the list of imports I'd expect them to be in **Organize Imports** order.

VS Code version: Code - Insiders 1.46.0-insider (595d2b9b916d063aadfc2c1a8c8f6df5b45572a8, 2020-06-03T05:38:33.098Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.3.0-1020-azure
Remote OS version: Linux x64 5.3.0-1020-azure

**Comment by mjbvz** [comment]
This makes sense and I believe https://github.com/microsoft/TypeScript/issues/33839 is already tracking this. I'll mark this as a polish item for the TypeScript team to investigate
