### ISSUE TITLE
Decimal property is not displayed correctly in Variables in debugger

### ISSUE THREAD

**Issue by bgrainger** [Microsoft/vscode#9929]
- VSCode Version: Version 1.3.1 (1.3.1) e6b4afa53e9c0f54edef1673de9001e9f0f547ae
- OS Version: Mac OS X 10.10.5

#### Steps to Reproduce:

Create a .NET Core Console application with the following code:

```
namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var t = new Test { Value = 1.0m };
            // SET BREAKPOINT HERE
            System.Console.WriteLine(t.Value);
        }
    }

    public class Test
    {
        public decimal Value
        {
            get { return _value; }
            set { _value = value;}
        }

        private decimal _value;
    }
}
```

Debug it by pressing F5. Break on the `Console.WriteLine` line and look at the Variables pane. The value of `Value` is displayed incorrectly (but `_value`) is correct. The incorrect value changes each time the program is run.

#### Actual Output:

<img width="215" alt="screenshot 2016-07-28 18 11 56" src="https://cloud.githubusercontent.com/assets/188129/17234605/483c03a6-54ef-11e6-9175-91fe95d4bdd9.png">

#### Expected Output:

Both `Value` and `_value` should show `1.0 [decimal]`.

**Comment by sjones204g** [comment]
I'm getting this problem as well.

**Comment by weinand** [comment]
The formatting of these values is done in the debug adapter of the C# extension.

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#632
