### ISSUE TITLE
Remove comment does not work consistently in HTML

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#993]
When editing HTML, remove comment (ctrl+k,u) often *adds* a comment.

Reproducing:
* the code is not already commented
* the code is commented, but you select whole lines instead of selecting the specific start and end of the comment

**Comment by pali88** [comment]
(ctrl+k,u)

**Comment by warpdesign** [comment]
+1

![comment](https://cloud.githubusercontent.com/assets/199648/11816139/6bccaebc-a34f-11e5-9a1a-0e1d49768cfd.gif)
