### ISSUE TITLE
Vim extension breaks Powershell Command Explorer search

### ISSUE THREAD

**Issue by jimpudar** [microsoft/vscode#99309]
- VSCode Version: 1.45.1
- OS Version: macOS 10.15.5 (19F101)

Steps to Reproduce:

1. Install PowerShell extension
2. Open Powershell Command Explorer
3. Type some characters, observe the search/filter functionality works
4. Install Vim extension and enable
5. Open Powershell Command Explorer
6. Type some characters, observe the search/filter does not work

Does this issue occur when all extensions are disabled?: No (N/A)

Sorry if this is in the wrong place, I'm not sure where the bug should be raised, in tree view, vim extension, or in powershell extension.

**Comment by connor4312** [comment]
\extPowershell

**Comment by connor4312** [comment]
\extVim
