### ISSUE TITLE
Pinning dynamic configuration makes other edits to launch.json

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#99305]
Verifying #95836

- Pin some Node.js dynamic config in vscode's repo
- It adds the config, but makes several other edits - removes trailing commas, and removes comment lines which are important

Removing the commas isn't a big deal, I guess the json configuration editing service is normalizing the file, but removing the comments is bad since the file is "JSON With Comments" and the comments are our content

**Comment by isidorn** [comment]
@roblourens good catch.
I am writing the configuration [here](https://github.com/microsoft/vscode/blob/735e08aa9442d73c327811b33383898b2663e1a7/src/vs/workbench/contrib/debug/browser/debugConfigurationManager.ts#L724)

@sandy081 is it possible to somehow preserve the comments in the file if I use the `configurationService` to write?

**Comment by sandy081** [comment]
No comments cannot be preserved using the API - its a known issue - https://github.com/microsoft/vscode/issues/29453

**Comment by isidorn** [comment]
Thanks! Will still keep this open since we could theoratically use the fileService to write, but I would prefer not to do that.

**Comment by isidorn** [comment]
Closing as will not fix

**Comment by weinand** [comment]
@isidorn This is not a "won't fix" but just a duplicate of #29453.
You don't have to put this on a backlog.
