### ISSUE TITLE
Provide a good example for using  'setState' in NotebookRendererApi

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#99300]
Testing #99001

Maybe this is just my lack of understand with the notebook API, but all of the other methods in `INotebookRendererApi` seem to have clear instructions on what they're used for (`onWillDestroyCell` and `onDidCreateCell` are good examples). But for `setState` and `getState` I'm a bit unsure of how i'm suppose to use this. It seems as if once I set this in the entry point for the renderer the state is persisted, so this makes it a bit ambiguous on its use. Maybe if there was a good example for this.

**Comment by connor4312** [comment]
Thanks, merging into https://github.com/microsoft/vscode/issues/99320. I want to move those types from a copypasta'd .d.ts into its own package with appropriate documentation 🙂
