### ISSUE TITLE
Avoid absolute path in pinned dynamic config

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#99308]
Verifying #95836

We should try to resolve these to some form of `${workspaceFolder}` if possible, so I can check this in without fixing it.

![image](https://user-images.githubusercontent.com/323878/83671472-62d69c80-a59a-11ea-907c-3119ceb28abf.png)

**Comment by connor4312** [comment]
To verify:

 - In some workspace with package.json scripts ctrl + p and enter `debug node.js`
 - Hover one of the scripts in the quickpick that comes up and click on the gear icon
 - This saves that config to the launch.json. Verify that the cwd is set with the `${workspaceFolder}` in the launch.json
