### ISSUE TITLE
Change 'resolveCustomEditor' to 'resolveCustomTextEditor' [typo]

### ISSUE THREAD

**Issue by 9at8** [microsoft/vscode#99302]
Testing #99003

Under lifecycle docs: https://code.visualstudio.com/api/extension-guides/custom-editors#custom-text-editor-lifecycle

Change:
> Once `resolveCustomEditor` returns, our ...

to:
> Once `resolveCustomTextEditor` returns, our ...

![Screenshot_20200603_135104](https://user-images.githubusercontent.com/8235156/83670612-733e4580-a5a1-11ea-9df6-a8a47a85cd31.png)

**Comment by mjbvz** [comment]
Fixed by https://github.com/microsoft/vscode-docs/commit/05ecfcaa24ed7fcfe5d450da4a74ab95055ba4d8 (in vnext branch of docs)
