### ISSUE TITLE
Don't prefix node-terminal with pwa

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#99307]
Verifying #95836

This would look nicer if we could use a `node-terminal` type instead of `pwa-node-terminal`, since this is a place where we actually write this into user's launch configs. Typically users could see the pwa prefix but only if they are messing around with debug types on their own. We will have to either support the pwa prefix forever or get rid of it and make some users adjust their configs at some point.

![image](https://user-images.githubusercontent.com/323878/83671472-62d69c80-a59a-11ea-907c-3119ceb28abf.png)

**Comment by connor4312** [comment]
Yea. This is going to be kind of a pain in general when we swap over to replace node and chrome as well.

Maybe we just eat a breaking change then or have a quick notification with a button to remove the prefix. Removing the prefix for terminal, which is a new type, makes sense though.

**Comment by Tyriar** [comment]
This looks wrong now:

![image](https://user-images.githubusercontent.com/2193314/83914762-be359580-a726-11ea-97a6-92273e830d20.png)

Shouldn't pwa-node get the same treatment as node-terminal?

**Comment by connor4312** [comment]
The difficulty with doing that is that would require the user to have either js-debug or the built-in node extension installed, as registering a debug adapter descriptor factory for a debug type twice will fail. Requiring that would make opting-in harder / remove the possibility of having the `usePreview` flag.

**Comment by Tyriar** [comment]
@connor4312 would these eventually change to just `node`?

**Comment by connor4312** [comment]
Yea
