### ISSUE TITLE
Using excessive resource on java environment

### ISSUE THREAD

**Issue by rohangrge** [microsoft/vscode#99310]
Issue Type: <b>Bug</b>

The program is taking up extra resources while running java code and it is making the computer heat up while running vs code

VS Code version: Code - Insiders 1.46.0-insider (595d2b9b916d063aadfc2c1a8c8f6df5b45572a8, 2020-06-03T05:43:09.908Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.22.0
python|ms-|2020.6.83879-dev
remote-wsl|ms-|0.44.2
cpptools|ms-|0.28.2
java|red|0.62.0
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.22.4
vscode-maven|vsc|0.21.4

</details>

**Comment by connor4312** [comment]
\extJava
