### ISSUE TITLE
Problem modifying files on a directory mounted to a Docker container

### ISSUE THREAD

**Issue by lisandro52** [Microsoft/vscode#9931]
- VSCode Version: 1.3.1
- OS Version: Debian 8

Steps to Reproduce:

1.  Start a docker container with a host's directory mounted onto the container's work directory (using the `-v` parameter).
2.  Make changes to a file ( e.g. `index.html`)
3. Refresh your browser and you shouldn't see the changes.

The thing is that if I edit the HTML file with vim (and `noswapfile` enabled), the changes are made and shown on the container. [I found this issue on docker's Github](https://github.com/docker/docker/issues/15793) that links this problem with the way text editors implement 'atomic saves', and some people suggest how to disable this behaviour on vim and Sublime Text 3. 
I couldn't find anything like that on the settings for VSCode. Is there something related to look at?
Thank you!

**Comment by bpasero** [comment]
We use fs.writeFile() in node.js. I suggest you try to write to the file via a node.js script to see if that works and then report back if this is a VS Code issue or node.js issue (which we cannot do anything about it).
