### ISSUE TITLE
Explorer files highlighted with git status when in `.gitignore`

### ISSUE THREAD

**Issue by GammaGames** [microsoft/vscode#99314]
- Version: 1.45.1
- OS: Linux x64 5.3.0-53-generic

Steps to Reproduce:

1. Add file to git repo, notice it is green with badge in the explorer
2. Add file path to gitignore
3. Notice the badge is now gone but the file name is still green
![image](https://user-images.githubusercontent.com/7832163/83686234-1ba2d880-a5a7-11ea-9338-9029e1951e9e.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
I can't reproduce, btw.

**Comment by jrieken** [comment]
Please add the git output

**Comment by GammaGames** [comment]
Huh, it looks like it might be the theme since it goes away when I change to a default. I tried to launch without extensions but must've bungled the arguments. Thank you for following up, sorry about that!
