### ISSUE TITLE
Notebook EditorTitle menu items don't go away after closing split notebook editor

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#99316]
- Open some text editor
- Open Notebook
- Split it into two editors
- Close both, leaving the text editor
- The notebook actions are still visible in the text editor's title area, and some keyboard shortcuts like cmd+f don't work due to the notebook focus context key being set

**Comment by roblourens** [comment]
It looks like the input is disposed, we call `releaseNotebookEditorWidget`, then `onWillHide` happens, and we decide there is no widget, and onWillHide isn't called on the widget.

**Comment by rebornix** [comment]
I pushed a fix which unsets the editor focus context but I found that the context key service is not scoped to the editor (neither `NotebookEditor` nor `NotebookEditorWidget`). Let's do that next week https://github.com/microsoft/vscode/issues/99318 .

**Comment by roblourens** [comment]
Should it be? I thought those should be global, otherwise we wouldn't have to unset the key at all right?
