### ISSUE TITLE
Cannot connect to the Market Place

### ISSUE THREAD

**Issue by steffilion** [microsoft/vscode#99311]
Issue Type: <b>Bug</b>

I'm trying to get access to any marketplace  and it is always failing.  When I switch to the Developer mode I see this following error :
Failed to load resource: net::ERR_NO_SUPPORTED_PROXIES

I have no proxy configured.  I'm not behind a proxy either.

I deleted all stuff  in C:\Users\<user>\AppData\ about Visual Code

I re-install mulitiple time without any success.

I read a lot of thread talking about this, but didn't get any clear answer.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by chrmarti** [comment]
Do you have any of the HTTP_PROXY, HTTPS_PROXY or NO_PROXY environment variables or the `http.proxy` setting set?

**Comment by steffilion** [comment]
I had HTTP_PROXY in environment variables.  I thought it was only using the config in the settings.  

It works.

Thanks for your support
