### ISSUE TITLE
"Open Results in Editor" incompatible with `defaultNumberOfContextLines`

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#99321]
Search Editors created from "Open Results in Editor" will not have their context lines input pre-filled to `defaultNumberOfContextLines`. This is expected, because we don't want to run the search again. However, when explicitly toggling the context lines input, the default value should be `defaultNumberOfContextLines`, rather than right now it is hard coded to `2`.

**Comment by JacksonKearl** [comment]
Ref #97915

**Comment by tabaddor** [comment]
I can look into fixing this issue. 

Is there any other information I should know, aside from the reference issue you commented above? @JacksonKearl

**Comment by Dzejkop** [comment]
I authored the original [implementation](https://github.com/microsoft/vscode/pull/97920), I'd happily look into this

**Comment by tabaddor** [comment]
Is there a reason why it is hard coded as 2?

**Comment by JacksonKearl** [comment]
Nope. 🙂

**Comment by JacksonKearl** [comment]
Ended up taking this myself as I wanted to try out a few different models to see what felt best.

Now:
- `defaultNumberOfContextLines` is 1 by default instead of `null`. This is to help discoverability of context lines in general, as one can always disable context lines if they're annoying, but it's less likely for someone to know they exist in the first place if they've never seen them.
- Search view's `Open in Editor` command will open an editor with `defaultNumberOfContextLines` context lines *if* the search view was not dirty - if it was dirty, the behavior is the same as before (no context lines shown). It might be nice in the future to keep track of what results were removed so we can show context lines even for dirty searches.
