### ISSUE TITLE
Provide webview/renderer API typings somewhere

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#99320]
Right now we expose an API to cells, and to webviews, but we don't publish types for this. The webview API is very simple, but the renderer will be somewhat more complex.

We should consider either publishing these in @types/vscode, or in a separate @types package.

**Comment by JacksonKearl** [comment]
This would be helpful for https://github.com/microsoft/vscode-docs/issues/3784. I think a @types/vscode-notebook or something would be a good place for it.

Aside, it'd be cool if ts `lib`s could be contributed to... 
```json
{
	"compilerOptions": {
		"lib": [
			"es6",
			"vscode-notebook-output-context"
		],
	},
	"include": [
		"client",
	]
}
```

Right now we'd need a whole separate NPM scope to have separate @types I believe.

**Comment by connor4312** [comment]
> Right now we'd need a whole separate NPM scope to have separate @types I believe.

We can just PR a package called @types/vscode-notebook. The naming of packages is only constrained by the maintainers' policy, and there are types that don't correspond to single packages, e.g. https://www.npmjs.com/package/@types/kap-plugin

**Comment by JacksonKearl** [comment]
Poor wording, I mean the project would need a different `package.json` and `node_modules/@types` for the client code vs the extension host code.

**Comment by connor4312** [comment]
Oh, yea. In the sample renderer/code generator I'm using project references to keep things separated -- that also lets us use `lib: dom` only in the renderer and output es6 modules (only) for webpack.

**Comment by connor4312** [comment]
PR submitted
