### ISSUE TITLE
File open windown too small using remote desktop

### ISSUE THREAD

**Issue by paulelong** [microsoft/vscode#99325]
We have written the needed data into your clipboard because it 
Issue Type: <b>Bug</b>

Remote Desktop into machine and do a file open.  The dialog is very small compared to other file open dialogs.  Surface Pro 7 connecting to a desktop that is running 1680x1050 resolution with a GTX1050i video card.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (3.32GB free)|
|Process Argv|--folder-uri file:///e%3A/Program%20Files/Splunk/etc/apps/AB3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
cpp-helper|ami|0.1.1
vscode-instant-markdown|dba|1.4.4
gitlens|eam|10.2.1
html-preview-vscode|geo|0.2.5
gc-excelviewer|Gra|2.1.35
live-html-previewer|hdg|0.3.0
vscode-supercollider|jat|0.0.2
csharp|ms-|1.22.0
python|ms-|2020.5.80290
remote-wsl|ms-|0.44.2
cmake-tools|ms-|1.4.0
cpptools|ms-|0.28.2
Go|ms-|0.14.3
powershell|ms-|2020.4.0
r-lsp|REd|0.1.6
vscode-taskexplorer|spm|1.26.3
code-spell-checker|str|1.9.0
vscode-arduino|vsc|0.3.0
debug|web|0.25.0

</details>
was too large to send. Please paste.

**Comment by alexr00** [comment]
Can you please provide a screen shot?
