### ISSUE TITLE
Feature request: read-only mode

### ISSUE THREAD

**Issue by sweettyler** [microsoft/vscode#99322]
I would like to have a function that the user can use to set an opened file as "read-only", which means after clicking the button, the file is not editable within VScode (but actually you still can from outside of VScode). I know another editor has this function and feel it's useful especially when you read source code and want to avoid accidentally typing something into the code.

**Comment by connor4312** [comment]
This is a good extension idea.

**Comment by gjsjohnmurray** [comment]
@connor4312 I am not convinced the necessary API exists yet. See #4873
