### ISSUE TITLE
Unable to reveal to the explorer by pressing hotkey(ctrl+shift+e) when explorer.autoReveal is false

### ISSUE THREAD

**Issue by benxshen** [Microsoft/vscode#9932]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Add the user setting "explorer.autoReveal": false
2. Pressing hotkey(ctrl+shift+e) to try to reveal the current active editor file in the explorer.

explorer.autoReveal shall be a control to allow auto reveal the opened (focused) file in the explorer panel, andit shall be allow user to reveal the current active file manually even when the the setting "explorer.autoReveal" is false.

**Comment by f111fei** [comment]
`{ "key": "ctrl+shift+e",          "command": "workbench.view.explorer" }`

`ctrl+shift+e` do only show the explorer viewlet now.

**Comment by benxshen** [comment]
Is it a beautiful misunderstanding? :)
Actually, I can use  `ctrl+shift+e` to reveal my current active file, and the explorer viewlet will scroll to the file and highlight on the file item. 

It's useful when I scroll to view other files on the explorer viewlet and I can quick to focus back on my current active file. However, I don't want the autoReveal every time I change my current active file. I would like to reveal it manually. 

The autoReveal is turned off once the config is set to `"explorer.autoReveal": false`. But why the function `workbench.view.explorer` is not working when pressing `ctrl+shift+e` ? It shall `workbench.view.explorer` be effected when autoReveal is turned off, shall it?

If this is only my misunderstanding, would you let me know what the command or shortcut to maually reveal the current active file?

Thank you.

**Comment by bpasero** [comment]
I have no clue what the problem is, please reopen when you can explain.

**Comment by benxshen** [comment]
Hi Team,

My problem is simple: I would like to turn off "explorer.autoReveal" , and reveal the current active file only when I hit the hotkey. Is that possible in the VSCode?

**Comment by bpasero** [comment]
"Show Active File in Explorer" from F1

**Comment by benxshen** [comment]
Great! Thank you, team. ^^
