### ISSUE TITLE
Can't open perf profile

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#99323]
- Start a node process
- Start profiling
- Stop, the editor shows an infinite progress bar, and I see this error in devtools

![image](https://user-images.githubusercontent.com/323878/83696974-603c6d00-a5c3-11ea-8fbc-4c5a26c5c465.png)

**Comment by connor4312** [comment]
I noticed this earlier today and fixed it in 0.0.6 https://github.com/microsoft/vscode-js-profile-visualizer/commit/b1c2ba04d6706d7beac7fa27cf6b8ae0b6b111ff
