### ISSUE TITLE
Internal terminal started instead of configured external terminal

### ISSUE THREAD

**Issue by igordovgaluk** [microsoft/vscode#99338]
- VSCode Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-91-generic
- OS Version: Ubuntu 18.04.5

Steps to Reproduce:

1. set the settings "terminal.explorerKind": "external",
2. select New Terminal from the app menu

Actual state:
The internal terminal is started

Expected state:
The external terminal is started

**Comment by Tyriar** [comment]
`terminal.explorerKind` only drives what terminal is launched in the explorer's context menu:

![image](https://user-images.githubusercontent.com/2193314/83764764-2ef98680-a62f-11ea-8b71-cd9d1a35a567.png)
