### ISSUE TITLE
Improved downloading of folders / large files on ssh extension

### ISSUE THREAD

**Issue by bycn** [microsoft/vscode#99334]
When using the ssh extension to do development on a server, the download / opening of large files often crashes the client, or is incomplete and disconnects halfway. Not sure why this occurs as it could just run something like SCP that wouldn't depend on memory allowed for the application.

**Comment by alexdima** [comment]
@bycn In the meantime, we have pushed a number of changes which makes transferring the contents of large files streamed (such that other messages make it across at the same time) and cancelable. Does this still reproduce for you?

**Comment by bycn** [comment]
I don't have the capacity to test this right now, sorry :( but I was on a Macbook Pro and downloading a ~O(50 GB) folder.
