### ISSUE TITLE
Save shortcut does not work when using 

### ISSUE THREAD

**Issue by 9at8** [microsoft/vscode#99331]
Testing #99003

I use emacs shortcuts (lfs.vscode-emacs-friendly). It seems like the save shortcut doesn't work (`ctrl+x ctrl+s`) when I'm using the emacs shortcut extension, but works (`ctrl+s`) when I'm not using the emacs extension.

https://github.com/SebastianZaha/vscode-emacs-friendly/blob/master/package.json#L535

**Comment by 9at8** [comment]
ah it might be because of the `when` clause in the emacs extension itself, and might not be related to the custom editor.

**Comment by mjbvz** [comment]
Yes, this is caused by `editorTextFocus` which for custom editors would evaluate to false

Please file an issue against the emacs extension for this
