### ISSUE TITLE
Search and replace: improve readability of the replace preview

### ISSUE THREAD

**Issue by Nowaker** [microsoft/vscode#99336]
![image](https://user-images.githubusercontent.com/611746/83720663-1ec9b300-a5ff-11ea-90cd-80b2014bc08e.png)

Search: `permalink: ([^/])`
Replace with: `permalink: /$1`

Currently visible match and replace preview: 
![image](https://user-images.githubusercontent.com/611746/83720893-9b5c9180-a5ff-11ea-9553-a22198c077b4.png)

Requested match and replace preview: 
![image](https://user-images.githubusercontent.com/611746/83721156-2047ab00-a600-11ea-9673-81090ce73ab9.png)

All that really changes between "from" and "after" is an addition of `/`. It's clearer and more readable preview of the replace.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/19310
