### ISSUE TITLE
Extensions are keeping stuck at "installing"status.

### ISSUE THREAD

**Issue by nelsonc24** [Microsoft/vscode#9933]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:
1. Choose extension option.
2. Select any extension.
3. Keep stuck at "installing"status.
   ![vs_issue](https://cloud.githubusercontent.com/assets/10952301/17238689/2ca8bea6-55a1-11e6-9ea2-4105db5dfd7f.JPG)

Best Regards,

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by rylan** [comment]
I am coming across the same problem, I am behind a proxy. I have set my proxy settings as outlined here https://code.visualstudio.com/docs/setup/setup-overview#_proxy-server-support and just hangs at installing.

**Comment by joaomoreno** [comment]
@nelsonc24 @rylan Can you try the latest [insiders release](https://code.visualstudio.com/insiders)?

**Comment by rylan** [comment]
I was able to fix the problem. It turned out that the instance that I working on did not have the .cmd extension set in the PATHEXT environment variable.

**Comment by realdanielbyrne** [comment]
![image](https://cloud.githubusercontent.com/assets/2242293/26586640/69efc1a6-4515-11e7-8fce-c8591ff43ae4.png)
Same problem here.  

Visual Studio Code 
Version 1.12.2
Shell 1.6.6
Node 7.4.0
Rederer 56.0.2924.87
