### ISSUE TITLE
Auto complete ui is broken

### ISSUE THREAD

**Issue by mgowtham** [microsoft/vscode#99342]
- VSCode Version: 1.45.1
- OS Version:  mac OS Catalina (10.15.2)

Steps to Reproduce:

1. type somethig
2. Autocomplete UI is breaking

Does this issue occur when all extensions are disabled?: Yes
<img width="479" alt="Screenshot 2020-06-04 at 2 01 21 PM" src="https://user-images.githubusercontent.com/9431630/83733939-e9a77a00-a66b-11ea-9c9f-87e91523f36f.png">

**Comment by connor4312** [comment]
Can you run code with `code --disable-gpu` and let us know if the problem occurs there?

/needsMoreInfo

**Comment by mgowtham** [comment]
@connor4312  yes the issue occurs with code --disable-gpu

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by mgowtham** [comment]
@isidorn  Its woriking fine in insiders

**Comment by isidorn** [comment]
Great, then closing this and you can use vscode insiders or wait for a new release in a couple of days
