### ISSUE TITLE
Reloading the window does not retain the revealed position of the cell

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99349]
In the attached video, see how after reload the last cell's reveal position is getting changed

![Kapture 2020-06-04 at 11 40 46](https://user-images.githubusercontent.com/10746682/83741338-5add3200-a658-11ea-82d7-2857eb831738.gif)

**Comment by rebornix** [comment]
This one was already fixed in master now. However you can only test it after https://github.com/microsoft/vscode/issues/100783 is fixed.

**Comment by sandy081** [comment]
I can still reproduce this

**Comment by rebornix** [comment]
This issue can be reproduced by 

* create github issue notebook with content 
```
[
  {
    "kind": 1,
    "language": "markdown",
    "value": "# this is header\n\n## this is header 2\n\n# header 1\n\n## header 2\n\n### header 3\n\n# header 1\n\n## header 2\n\n# header 1\n\n## header 2\n\n### header 3",
    "editable": true
  },
  {
    "kind": 2,
    "language": "github-issues",
    "value": "repo:microsoft/vscode-atom-keybindings"
  },
  {
    "kind": 1,
    "language": "markdown",
    "value": "# another header"
  }
]
```
* open, turn all markdown cells into edit mode
* focus the last markdown cell editor
* reload

**Comment by roblourens** [comment]
This is fixed, probably by that other scroll position fix
