### ISSUE TITLE
Cannot find quick outline for an editor command in Command Pallette

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99347]
While verifying https://github.com/microsoft/vscode/issues/95234 one step is to verify quick outline of the notebook editor from command palette. I could not discover the command using `outline` term. 

![image (3)](https://user-images.githubusercontent.com/10746682/83739275-ab9f5b80-a655-11ea-8378-0d985aadaf39.png)

It is called `Go to symbol in editor`. 

I think this command shall be discovered also with outline term

@jrieken FYI

**Comment by JacksonKearl** [comment]
Also tripped me up.
