### ISSUE TITLE
Code Flickering

### ISSUE THREAD

**Issue by vineeshc9** [microsoft/vscode#99346]
Hi VS Code,

I am developing a Progressive Web App,
my coding file is flickering...
I am note able to code properly.

**Comment by connor4312** [comment]
Please try running code with `code --disable-gpu` and let us know if that fixes the issue.

/needsMoreInfo

**Comment by vineeshc9** [comment]
![V-S-Code-Flickering](https://user-images.githubusercontent.com/2756669/83892350-2d81a880-a76c-11ea-9a33-a20f8e4bf747.gif)

**Comment by connor4312** [comment]
That looks like the [indent-rainbow](https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow) extension.

**Comment by vineeshc9** [comment]
Thanks for the support .
Looks like its fixed.
