### ISSUE TITLE
Filename and Folder name conflict

### ISSUE THREAD

**Issue by drobertson123** [Microsoft/vscode#9934]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Create file named "Parsers" using the New File popup menu command. (Note-this was a mistake and it was meant to be a folder.)
2. Delete file using popup menu command Delete. At this point, the parsers editor is still open and active even after I delete the file.
3. Create the proper folder named "Parsers" and add some files to it.
4. At this point, it is impossible to close the open parsers editor. The system will not let me do a save all and I was forced to reboot to get the system working properly again.

Note - I would suggest the proper action would be to close the associated editor when you delete a file.

**Comment by kieferrm** [comment]
In 1.4.0 insiders the editor closes when you delete the file in step 2.
