### ISSUE TITLE
Reference cell is not revealed at the end of viewport and not shown completely

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99353]
- Used My work issues notebook
- Find all references for `$vscode`
- Navigate references using arrows and enter
🐛 Cell at the end of the viewport is not revealed completely

![Kapture 2020-06-04 at 12 18 22](https://user-images.githubusercontent.com/10746682/83745266-929aa880-a65d-11ea-9c7c-5cfe76032774.gif)

**Comment by rebornix** [comment]
Fixed already in Insiders.

**Comment by sandy081** [comment]
I can still repro this

**Comment by rebornix** [comment]
Moving to debt week as it's not a blocker.
