### ISSUE TITLE
References are shown in a cell that does not have references

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99354]
- Used My work issues notebook
- Open the notebook and have `### Performance` cell in edit mode
- Find all references for `$vscode`
- Navigate references

🐛 Markdown cell that does not has reference is revealed

![Kapture 2020-06-04 at 12 22 18](https://user-images.githubusercontent.com/10746682/83745622-1c4a7600-a65e-11ea-86f5-5ea02852b334.gif)

**Comment by jrieken** [comment]
wait... cannot reproduce. @sandy081 are you on lastest of the GH issue extension?

**Comment by sandy081** [comment]
Yeah I am on latest.. I think the step I missed to add is to have `## Performance` cell in edit mode. Updated.

**Comment by jrieken** [comment]
Thanks. The cell (markdown) needs to be in edit mode and must be outside the viewport for this to happens. For some reason the wrong editor is then picked up.

**Comment by jrieken** [comment]
@rebornix It seems like something goes wrong in the editor (and this might actually the same as https://github.com/microsoft/vscode/issues/98172). 

When I adding below 👇 log lines [here](https://github.com/microsoft/vscode/blob/2759576183d4f63d00f60059767baddb18a221a4/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L399)

```ts
console.log('CELL:', cell.uri.toString(), cell.getText().substr(0, 100));
console.log('EDITOR:', editor.getModel()!.uri.toString(), editor.getModel()!.getValue().substr(0, 100));
```

it will print this, which makes me believe that initially the right editor is selected but somehow the models must change or so...

```
CELL: vscode-notebook-cell:/Users/jrieken/Code/_samples/devfest/foo/my-work.github-issues#0000006 $vscode $milestone is:closed assignee:@me label:feature-request -label:on-testplan -label:verificati
notebookEditorWidget.js:302 EDITOR: vscode-notebook-cell:/Users/jrieken/Code/_samples/devfest/foo/my-work.github-issues#0000006 $vscode $milestone is:closed assignee:@me label:feature-request -label:on-testplan -label:verificati
notebookEditorWidget.js:301 CELL: vscode-notebook-cell:/Users/jrieken/Code/_samples/devfest/foo/my-work.github-issues#0000008 $vscode $milestone is:closed assignee:@me label:feature-request -label:on-release-notes -label:*dupl
notebookEditorWidget.js:302 EDITOR: vscode-notebook-cell:/Users/jrieken/Code/_samples/devfest/foo/my-work.github-issues#0000008 $vscode $milestone is:closed assignee:@me label:feature-request -label:on-release-notes -label:*dupl
```

**Comment by jrieken** [comment]
Digging a little deeper, it seems to be coming from [here (`revealInCenterIfOutsideViewport`)](https://github.com/microsoft/vscode/blob/2759576183d4f63d00f60059767baddb18a221a4/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L398) but somehow async, e.g first the cell code editor is selected and focused and after that the post scroll logic kicks in which makes the MD cell render, which in return realises that it is editable and questionably focuses itself.

<img width="310" alt="Screenshot 2020-06-04 at 14 48 18" src="https://user-images.githubusercontent.com/1794099/83758495-781efa00-a672-11ea-8cf0-0316e6815899.png">

**Comment by roblourens** [comment]
Thanks for the investigation! Found simpler repro steps -

- Put a markdown cell in edit mode
- Scroll it out of view
- Scroll it back into view, it takes focus

I see the issue

**Comment by roblourens** [comment]
@misolori are you verifying in master? This isn't in a build yet

**Comment by misolori** [comment]
@roblourens doh, my bad. I started testing this and saw this persisted so was writing up an issue. I assumed that because this didn't have the `unreleased` label that it was released. Didn't even look at the commit time, my mistake.

**Comment by roblourens** [comment]
Pushed a different fix, but also filed https://github.com/microsoft/vscode/issues/99390 for some related issues. Right now if you scroll the focused element out of view, list keyboard shortcuts will not work and it may or may not get refocused properly when scrolling back in.

**Comment by JacksonKearl** [comment]
\closedWith 0b18106
