### ISSUE TITLE
Got into a blank notebook editor state

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99351]
Got into a blank notebook editor state where I cannot add any cells

- Have issues notebook with following content/cells

```
[{"kind":2,"language":"github-issues","value":"repo:microsoft/vscode assigne:@me label:settings","editable":true},{"kind":2,"language":"github-issues","value":"epo:microsoft/vscode assignee:@me label:settings"}]
```

- Open the notebook and keep deleting cells
- Once all cells are deleted, Type `cmd+z` to undo

🐛 Editor becomes blank

![Kapture 2020-06-04 at 11 56 32](https://user-images.githubusercontent.com/10746682/83743078-806b3b00-a65a-11ea-853b-81e427c99049.gif)

**Comment by rebornix** [comment]
Already fixed, if you delete the last cell, we will insert an empty cell into the document automatically.

**Comment by sandy081** [comment]
I can still repro the blank state when at the end, Once all cells are deleted, Type cmd+z to undo.
