### ISSUE TITLE
unable to find the complier path

### ISSUE THREAD

**Issue by sundarhistoriya007** [microsoft/vscode#99358]
have written the needeWe d data into your clipboard because it was too large to send. Please paste.
hi 

i am facing the issue, compiler path is not find but i have given correct path only
problems console is shows cant fint c:/User/Welcomewin64/bin/gcc.exe is 
please help me fix this problem

**Comment by connor4312** [comment]
\ectC

**Comment by connor4312** [comment]
\extC
