### ISSUE TITLE
Undo is adding bogus problems

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99352]
- Have couple of cells with problems
- Keep removing one by one
- Make sure the problems are getting removed
- At the end (when only one cell is remaining), type `cmd+z` (undo)
🐛 Bogus problems are added

![Kapture 2020-06-04 at 12 02 21](https://user-images.githubusercontent.com/10746682/83743744-6b42dc00-a65b-11ea-88d5-2e4478181605.gif)

**Comment by jrieken** [comment]
Yeah, I would expect only one new error to shown...
