### ISSUE TITLE
The latest vscode can't use system installed python

### ISSUE THREAD

**Issue by halx99** [microsoft/vscode#99357]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by halx99** [comment]
I just wan't use reStructuredText, but it's always prompt ```Please review Python installtation on thi smachine before using this extension```, I already specify python path to System ```PATH```

**Comment by halx99** [comment]
But I installed python by official python installer, not ms vscode python extension

**Comment by IllusionMH** [comment]
VS Code editor doesn't use Python by itself and only provides basic syntax highlight.

Error that you have comes from extension and should be reported in extension repo, because this repo only for editor issues.

Also see https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/191

**Comment by halx99** [comment]
thanks
