### ISSUE TITLE
Notebook input cell has no left padding

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#99363]
On Windows:

![image](https://user-images.githubusercontent.com/22350/83756049-c03c1d80-a66e-11ea-9e49-d5792310b3de.png)

Actually the overall padding looks strange... no left padding, too much padding on top/bottom.

Also, is that `GitHub Issues` really needed? It seems to take over excessive space.

**Comment by rebornix** [comment]
Since now we don't show background for the cell editor, the editor and the statusbar blends together. It makes the padding around the editor text weird and also the language picker stands out when there is no execution status yet.

**Comment by rebornix** [comment]
Right now we always show a glyph margin on the left side.
