### ISSUE TITLE
Search and replace not working for some strings that contain parentheses

### ISSUE THREAD

**Issue by jrmcdona** [microsoft/vscode#99360]
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1.  Search and replace for string **Monthly Channel (Targeted)**
2.  Review screenshots below to see this should be working.  Only Monthly Channel search is working but not when you add (Targeted)

![image](https://user-images.githubusercontent.com/4327773/83753643-4ab15c80-a630-11ea-831e-5865211641c2.png)

You can see no results:
![image](https://user-images.githubusercontent.com/4327773/83753788-88ae8080-a630-11ea-994c-6578e386d66d.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by usernamehw** [comment]
You have regexp flag turned on

![83753643-4ab15c80-a630-11ea-831e-5865211641c2](https://user-images.githubusercontent.com/9638156/83755873-e2d23480-a676-11ea-871a-bb6f8c9849c7.png)

**Comment by jrmcdona** [comment]
You are right.  Thought was a bug.
