### ISSUE TITLE
Notebooks output contains unsupported/unknown types

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#99365]
![recording (14)](https://user-images.githubusercontent.com/22350/83756746-ca125080-a66f-11ea-9362-70b828a70e77.gif)

**Comment by jrieken** [comment]
That's part of the experience ;-) The special mime type is used for the "open in browser" command and the plan is to eventually have a real renderer for it. 

However, the notebook story is like this. A kernel can produce outputs for which you might need another extension to render. Like, there can be a charting extension that knows how to render charting mime types. Still, we can tweak the quick pick when certain types aren't supported and/or we can send you to the marketplace to search for extensions

**Comment by jrieken** [comment]
fyi @rebornix @misolori

**Comment by misolori** [comment]
Yea, I'd imagine that if a certain mime type isn't supported that we disable it in the quick pick and mark it as `Unsupported` in the list.

**Comment by jrieken** [comment]
fyi - the underlying issue is now fixed because we have a renderer for that data format.

**Comment by tanhakabir** [comment]
We've updated the flow for renderers, this exact feedback is no longer applicable
