### ISSUE TITLE
Notebook input cell padding varies with layout direction

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#99364]
Check it out:

![recording (13)](https://user-images.githubusercontent.com/22350/83756215-05f8e600-a66f-11ea-9b3e-661c7f418913.gif)

**Comment by rebornix** [comment]
Started to see this layout issue recently. My guess is monaco somehow renders horizontal scrollbar.

**Comment by rebornix** [comment]
/duplicate of #99163 and I left even almost the same reply ;(

**Comment by roblourens** [comment]
Why is there no left padding in the editor? Is that a settign?
