### ISSUE TITLE
Notebook editor dies when closing inactive tab

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#99368]
* use workbench tabs
* open notebook A
* open notebook B
* select notebook A again
* close notebook B via its (inactive) tab
* notebook A shows no more content

![Jun-04-2020 14-39-25](https://user-images.githubusercontent.com/1794099/83757800-5113f880-a671-11ea-8309-a6ca49999d5b.gif)

**Comment by rebornix** [comment]
stupid me, CLOSURE.
