### ISSUE TITLE
auto save workspace setting is overrode by user setting

### ISSUE THREAD

**Issue by MathieuDerelle** [microsoft/vscode#99367]
Issue Type: <b>Bug</b>

this page 
https://code.visualstudio.com/docs/getstarted/settings
states 
> Workspace settings override user settings

but it is the opposite for setting "files.autoSave"

# My config : 
- in user setting : after delay
- in workspace setting : off

# expected : 
auto save turned off 
(therefore no webpack reload when modifying a file without saving manually)

# got :
webpack is reloading when modifying files (without saving manually)
If I turn the user setting to "off", there is no more reloading when modifying files (and not saving manually)

its even mentioned in workspace setting
> Modified in: User
![image](https://user-images.githubusercontent.com/16286023/83757154-5886d200-a670-11ea-8bfc-e991d93eafdc.png)

like it was legit ? why ? 

How to get the correct behavior ?
which is
> Workspace settings override user settings

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 19.4.0

**Comment by sandy081** [comment]
It is working as expected - I mean workspace settings overriding user settings for auto save.

Can you please provide a sample GitHub repository with workspace settings that is having this issue and share it with us?
