### ISSUE TITLE
Editing settings via CLI interface

### ISSUE THREAD

**Issue by EricHripko** [microsoft/vscode#99361]
# Overview
[code CLI](https://code.visualstudio.com/docs/editor/command-line) is amazingly helpful for users that wish to quickly set Visual Studio Code up or even automate the setup altogether. For example, current CLI interface provides a great way to [manage extensions](https://code.visualstudio.com/docs/editor/command-line#_working-with-extensions) from command line.

CLI interface would be even more useful if it also provided a way to read and update settings.

# Proposed Interface
For example:
- `code --get-setting <name>` could return a JSON value for the setting _name_.
- `code --update-setting <name> <value>` could modify setting _name_ with the new _value_. Since values can be complex JSON objects, this interface may need additional inputs (e.g., file and/or STDIN).

# Alternatives Considered
One could attempt to parse `settings.json` manually, but will soon find that VSC JSON doesn't follow any specification, as it supports:
- Comments
- Trailing commas
- Single quotes
- ... and more

Looking at the [source code](https://github.com/microsoft/vscode/blob/656920b1ea53a8b70836b1d2517f73b8d1005dce/src/vs/base/common/json.ts), the parser appears to be custom and doesn't seem to follow a spec of any kind. While there is [jsonc-parser](https://www.npmjs.com/package/jsonc-parser) package, it also has a few flaws:
- It's not actually used by VSC, so parsing of valid (according to VSC) `settings.json` might fail
- It requires end user to use NodeJS. What if user is writing a simple automation with Python or bash?
- It enables you to specify invalid values for settings (e.g., a string where the list is expected)

Having Settings functionality exposed via CLI interface, circumvents the problem of parsing - and enables users to both configure VSC from CLI and build automations however they like.

**Comment by Rhahkeem** [comment]
Absolutely love this idea

**Comment by 2rs2ts** [comment]
Since we have over 20 upvotes, could this be reopened and put in the backlog? Even if it's at the very lowest spot in the backlog, that's better than nothing.

**Comment by sandy081** [comment]
I have to say it wont help keeping this in backlog and not addressing it. Our strategy is to close those features which we do not plan to attend in near time feature and come back to them later. Hope you understand it. Thanks.
