### ISSUE TITLE
Access toolbar when in fullscreen mode

### ISSUE THREAD

**Issue by talonmyburgh** [microsoft/vscode#99372]
OS: PopOS 18.04 LTS
MACHINE: Dell Laptop

Hi all,

This may be in line with issue #10121 but I thought I'd mention it here all the same as this is more specific. I work with a single screen (my laptop's) and usually work in fullscreen mode. The feature I'd appreciate having is if when in fullscreen mode, there were a way to access the toolbar. Perhaps it could be accessed by hovering my cursor at the top of my screen? Currently, I have to exit fullscreen, access the toolbar as needed and then resume fullscreen mode. 

Naturally, I could remember the keyboard shortcuts for the options I wish to change in the toolbar, but some do not possess keyboard shortcuts like the "Add Folder to Workspace" option in 'File'.

Thank you.

**Comment by sbatten** [comment]
@talonmyburgh the menu bar visibility can be controlled by this setting `window.menuBarVisibility`. By default, the menu bar disappears during fullscreen, but can be shown by pressing the alt key. If you want show it all the time, you can set the setting to `visible`
