### ISSUE TITLE
Copy Path Shortcut

### ISSUE THREAD

**Issue by jockrow** [microsoft/vscode#99374]
Issue Type: <b>Bug</b>

Keyboars Shortcut for Copy Path (Shift+Alt+C) doesn't any thing 

![image](https://user-images.githubusercontent.com/30563443/83766819-7dfce700-a642-11ea-8916-07fa34d06aa1.png)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.83GB (1.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
al-code-outline|and|1.0.48
vscode-eslint|dba|2.1.5
open-files|Div|0.0.4
macros|ged|1.2.1
gc-excelviewer|Gra|2.1.35
diff-tool|jin|0.0.1
vscode-smart-column-indenter|lmc|0.0.13
rainbow-csv|mec|1.7.0
remote-wsl|ms-|0.44.2
cpptools|ms-|0.28.2
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-react-native|msj|0.16.0
crs-al-language-extension|wal|1.2.4

</details>

**Comment by gjsjohnmurray** [comment]
@jockrow your screenshot is the context menu from a tab, right?

The corresponding entry in my Keyboard Shortcuts list has a `!editorFocus` when-clause:

![image](https://user-images.githubusercontent.com/6726799/83774551-bc63c780-a67d-11ea-9397-4838a9d1442f.png)

I think that'll be why your clipboard content doesn't change when you type <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>C</kbd>

/confirmed

**Comment by bpasero** [comment]
Needs more info.

**Comment by jockrow** [comment]
> @jockrow your screenshot is the context menu from a tab, right?
> 
> The corresponding entry in my Keyboard Shortcuts list has a `!editorFocus` when-clause:
> 
> ![image](https://user-images.githubusercontent.com/6726799/83774551-bc63c780-a67d-11ea-9397-4838a9d1442f.png)
> 
> I think that'll be why your clipboard content doesn't change when you type Shift+Alt+C
> 
> /confirmed

Yes my screenshot is context menu from a tab, and I have same !editorFocus that you

**Comment by jockrow** [comment]
> Needs more info.

What info do you need?

**Comment by bpasero** [comment]
How to reproduce the issue?

**Comment by jockrow** [comment]
> How to reproduce the issue?

1. I clicked any side in Text Editor from file that I want copy Path
2. I Pressed Shift+Alt+C
3. Result: not copy path :(

**Comment by bpasero** [comment]
It should work if you configure this as keybindings:

```json
{
	"key": "shift+alt+c",
	"command": "copyFilePath"
}
```
