### ISSUE TITLE
CTRL + P Not working

### ISSUE THREAD

**Issue by jshaolin** [microsoft/vscode#99379]
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:
1. CTRL + P does not show the drop down to type the name of the file you want to open.
2. And YES, ALL MY EXTENSIONS ARE DISABLED. In fact, I was working right now and it suddenly stopped working.

Now it's even crazier. For some reason, this was in the keymaps: 
`{
  "key": "ctrl+e",
  "command": "workbench.action.quickOpen"
}`
So the open file action was working with CTRL + E, which I tested. I cannot remap it to CTRL + P since it does not respond to P, I can do CTRL + "Anything" and it recognizes the combinations but when I press CTRL + P it only shows "Ctrl" WTF??? Yes, the extensions are disabled, yes, I restarted VS Code.

So I went ahead and opened `keybindings.json` and a wrote in it:
```
// Place your key bindings in this file to override the defaults
[
  {
    "key": "ctrl+p",
    "command": "workbench.action.quickOpen"
  }
]
```
Now, I see "Open File" in Keyboard Shortcuts, but still **it doesn't work**.

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
Hi, please take a look through our [keybinding troubleshooting](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-windows-keybindings) page and let us know.

/needsMoreInfo

**Comment by jshaolin** [comment]
No offense @connor4312 but I'm not sweeping through a mile long page to **hack** into a problem **that was not present 10 minutes ago**. It **just** happened. If you need specific info then let me know, but don't bother me with "read this stuff and see what's wrong" kind of things. I'm using VS Code primarily for it's usability and quick productivity setup, if I have to start getting things done on my own like in the old Linux days, I'll just switch to use another code editor.

Basic info is in the issue description: I was working normally, hitting CTRL+ P as usual (one of my most used keybindings), then all of a sudden CTRL+P didn't worked, looking into the keybindings I saw it was somehow remapped to "CTRL + E", trying to remap it didn't work as the combination "CTRL + P" was not recognized, it only showed "CTRL +" as if the "P" key was broken in my keyboard (which it isn't by the way), then I tried to do it manually through the json file. I added explicitly the open file CTRL + P binding and now I was able to see both on the Keyboard Shortcuts window but it didn't work, only CTRL+ E works, now I even deleted the CTRL+E binding and still CTRL+P doesn't work.

**Comment by jshaolin** [comment]
![Untitled](https://user-images.githubusercontent.com/44646385/83781627-ce813e00-a65c-11ea-8294-e0d06fa4f235.png)

They're even showing up both as **default**, the CTRL+P and CTRL+E. how can there be 2 defaults for the same action?

**Comment by jshaolin** [comment]
Well, since a Google search revealed several people with the same issue and all of them where unfairly closed for "needing additional information" even when their authors were giving it, and also taken into account that the only person who responded to me actually wanted **me** to do the job of diagnosing and possibly fixing the bug, I'm closing this issue and switching editors. This is was a really bad experience in the VS Code community for me. It saddens me to see Microsoft relying on such low quality people for building a product of their own branding. No wonder it has over 5000 issues. Disappointing.

**Comment by jshaolin** [comment]
@connor4312 and to anyone who saw this page. Sorry for the harsh comments, it was my short tempered "psycho" cousin who wrote them *we were sharing laptops as his got broken yesterday night), I just heard about it when he complained to me in a conversation. Apologize to the community, I'm definitely not switching editors 😄 and VS Code rocks! 🚀 .  The issue was real, but somehow it's solved, I can use ctrl + e and ctrl + p to show the open file drop-down. Keep up the good work people! 🎸 👍 🚀 🎆

**Comment by connor4312** [comment]
@jshaolin that's one of VS Code's default keybindings -- you can have multiple bindings for one command (action). Sending to Alex for further investigation

**Comment by alexdima** [comment]
@jshaolin The fact that VS Code does not receive `Ctrl+P` indicates that the OS is not sending it to VS Code. Have you perhaps installed any new software recently which would want to globally "take" `Ctrl+P`. When this happens, what does VS Code detect as input?

![keyboard-input](https://user-images.githubusercontent.com/5047891/80482640-da3e5e00-8954-11ea-9583-0f652b0595a8.gif)

**Comment by jshaolin** [comment]
@alexdima I've updated Windows through Windows Update the night before, but I'm still on 1809, I didn't switch to 1909 which is the latest version. However, in the morning after it was working, I was hitting ctrl+p as usual but in about 20 mins of coding it stopped working. I tried defining the keybinding as you're showing me in the image, but when pressing ctrl+p it just detected ctrl and displayed it like this in the input box: "ctrl +", without the "p". However, now it's working again, ctrl+p, but also ctrl+e. Is it normal to have 2 **default** keybindings for the same action? I would expect the extra keybindings for the same action to be "user defined".

**Comment by jshaolin** [comment]
@alexdima ctrl + p continues to work ok (but also ctrl + e), maybe this was a glitch caused by the os update? If that's the case I think we can close the issue. What do you think?

**Comment by alexdima** [comment]
@jshaolin The fact that VS Code only receives `ctrl+` indicates that the OS is not sending this key combination to VS Code. Windows has APIs where an application can consume global keybindings even if it does not own the focused Window. So it could be any piece of software on your machine or the OS itself.

IMHO, from past experiences this is caused by:
- (most likely) there is some software on the machine that decides to consume "Ctrl+P".
- (unlikely) Windows does this by itself
- (unlikely) the keyboard is defective

Unfortunately, there is nothing we can do on our side if we don't receive the keybinding.
