### ISSUE TITLE
Notebook: weird find widget animation

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#99371]
![recording (17)](https://user-images.githubusercontent.com/22350/83760087-bddcc200-a674-11ea-8c34-ab0bdcdaa49f.gif)

It feels like it's hiding behind something, but it's not!

**Comment by rebornix** [comment]
It's weird compared to the find widget for monaco, which will be always inside the editor area but this one is on top of the editor toolbar for a bit of time.

**Comment by joaomoreno** [comment]
So let's not have it go up and down, but rather fade in/out?

**Comment by rebornix** [comment]
With some CSS tricks, the find widget behaves the same as the one in text editor.
