### ISSUE TITLE
Donn't render newline-characters as new lines in suggest details widget

### ISSUE THREAD

**Issue by WebFreak001** [microsoft/vscode#99370]
- VSCode Version: 1.45.1
- OS Version: any

Steps to Reproduce:

1. Create an extension providing a completion item with detail set to
  `"void writeln(\n\tT...\n)(\n\tT args\n)"`

2. Observe that VSCode reordered the detail string in the small view:
  (changed to `void writeln( ) T...`)
  ![reordered](https://user-images.githubusercontent.com/2035977/83759569-0778dd00-a674-11ea-8a5e-ecde1e28803b.png)

3. Observe that the big detail view is missing the indentation: (doesn't work with tabs or with spaces)
  ![missing indentation](https://user-images.githubusercontent.com/2035977/83759699-3db65c80-a674-11ea-839b-3b687370f35c.png)

On the API documentation (https://code.visualstudio.com/api/references/vscode-api#CompletionItem) it says detail is just "A human-readable string with additional information about this item", so I wouldn't expect VSCode to split it up into lines, reorder the lines and show that in the short UI.

The missing indentation part is probably a separate issue from this though.

**Comment by jrieken** [comment]
Let's try this for October...

<img width="875" alt="Screenshot 2020-10-05 at 11 52 05" src="https://user-images.githubusercontent.com/1794099/95065498-6d986e00-0701-11eb-83af-fd02304efe7c.png">

**Comment by WebFreak001** [comment]
I actually quite liked that the suggest details widget showed newlines, instead my issue was that the small preview had mixed up the string somehow and I mentioned in the side that the details widget showed the string correctly, but without indentation.

For complex strings I think it's actually a good idea to keep the details widget newlines and properly embrace it as a feature.

**Comment by jrieken** [comment]
> instead my issue was that the small preview had mixed up the string somehow and

Yeah, it will always do that because it needs to wrap lines because of spacing and to honour the actual line breaks. That's why it is always a mess

**Comment by WebFreak001** [comment]
why was the string `void writeln(\n\tT...\n)(\n\tT args\n)` cut to `void writeln( ) T` and not cut to `void writeln( T )` though?

**Comment by jrieken** [comment]
Reopen for discussion

**Comment by MartinGC94** [comment]
I was sent here from this comment: https://github.com/microsoft/vscode/issues/29126#issuecomment-715227766 but I'm not sure what to say. It doesn't seem like anyone here wanted newlines removed from the detailed view, so let's just not do that.

I don't personally care about the small view, but I agree with the OP that it's weird if `void writeln(\n\tT...\n)(\n\tT args\n)` gets shortened to `void writeln( ) T` in the small view.

**Comment by jrieken** [comment]
I pushed a change to render line breaks as they are. No line breaks that are inserted to fit into the rendering box

**Comment by jrieken** [comment]
to verify:

* open suggest details for various completions like TS auto imports, TS DOM types like `AbortController` etc pp
* make sure the details isn't wrapped artificially but only at lines breaks the extension has defined

**Comment by jrieken** [comment]
@Tyriar for verification

**Comment by jrieken** [comment]
Refinement: when details (as provided by the extension) contain line breaks then we'll don't allow render-only breaks but when details are a single line we do wrap for rendering.

**Comment by JacksonKearl** [comment]
Spot on.
![image](https://user-images.githubusercontent.com/8586769/97478114-be207700-190d-11eb-8b2f-1a952511f3ce.png)

**Comment by Tyriar** [comment]
The primary case I had issue with is covered now:

![image](https://user-images.githubusercontent.com/2193314/97509704-415ac080-1940-11eb-8ac1-05d09908ffa6.png)

![image](https://user-images.githubusercontent.com/2193314/97509747-5d5e6200-1940-11eb-93aa-47f7b064526e.png)

I found one minor issue when long symbols are used, but you could argue that I just need to resize the detail and I will do that, so I'm fine with this:

![image](https://user-images.githubusercontent.com/2193314/97509637-17090300-1940-11eb-91bd-3539a162c9e3.png)

Thanks for following this up 👍
