### ISSUE TITLE
Use forward slashes when paths are copied

### ISSUE THREAD

**Issue by MythreyaK** [microsoft/vscode#99373]
Some formats treat the backslash as an escape character, so it becomes tedious to replace them with forward ones or append a new one. It would be really great If all path separators use the /.

I noticed an old issue #6308 that asked for this feature, but was rejected. Though it is true that the native path separator is \, in most programming languages, the / is supported, without having to add extra thinking. Could this be kindly reconsidered?  

Thanks

**Comment by IllusionMH** [comment]
Looks like duplicate of #56279

**Comment by MythreyaK** [comment]
Off, my bad. Guess my search wasn't as good. Closing.
