### ISSUE TITLE
SetExceptionBreakpoints and SetFunctionBreakpoints are not sent after initialized event received

### ISSUE THREAD

**Issue by juanantlopez** [microsoft/vscode#99377]
- VSCode Version: 1.45.1
- OS Version: Windows_NT x64 10.0.18363

Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Once our debug adapter implementation (implemented in C++) sent the initialized event, it is expected, according to the documentation, the frontend sends all the breakpoints in order to synchronize the frontend with the adapter, but the Exception breakpoints and the function breakpoints are not sent. And only after toggling their checkboxes in the breakpoints window, the commands are sent. Below you can see the json messages interchanged  between the frontend and the debugger adapter from the initialize command till the configurationDone command:

````json
VS -> DA '{"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"xxx","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true},"type":"request","seq":1}'

VS <- DA '{"type":"response","request_seq":1,"success":true,"body":{"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":true,"supportsEvaluateForHovers":true,"exceptionBreakpointFilters":[{"filter":"handled","label":"Caught exceptions","default":false},{"filter":"unhandled","label":"UnCaught exceptions","default":true},{"filter":"debug","label":"User debug breaks","default":true},{"filter":"assert","label":"Asserts failure","default":true}],"supportsSetVariable":true,"supportsGotoTargetsRequest":true,"supportsStepInTargetsRequest":true,"supportsCompletionsRequest":true,"supportsModulesRequest":true,"supportsRestartRequest":true,"supportsValueFormattingOptions":true,"supportTerminateDebuggee":false,"supportsDelayedStackTraceLoading":true,"supportsLogPoints":true,"supportsTerminateThreadsRequest":true,"supportsSetExpression":true}}'

VS -> DA '{"command":"launch","arguments":{"type":"xxx","name":"test_generator","request":"launch","moduleId":"test_generator","remote":{"addr":"localhost","port":4711},"parameters":"c:/code/jet_engine/libs/xxx-gen/tests/src/GenerateCode","program":"c:\\code\\jet_engine\\libs\\xxx-gen\\workspace\\workspace.jwks","__sessionId":"c2ef4ea4-5d43-4730-9a9d-3213bf614e5b"},"type":"request","seq":2}'

VS <- DA '{"type":"response","request_seq":2,"success":true}'

VS <- DA '{"type":"event","event":"initialized"}'

VS -> DA '{"command":"setBreakpoints","arguments":{"source":{"name":"test_generator.xxx","path":"c:\\code\\jet_engine\\libs\\xxx-gen\\workspace\\test_generator.xxx"},"lines":[28],"breakpoints":[{"line":28}],"sourceModified":false},"type":"request","seq":3}'

VS <- DA '{"type":"response","request_seq":3,"success":true,"body":[{"id":0,"verified":true,"line":28,"column":1}]}'

VS -> DA '{"command":"configurationDone","type":"request","seq":4}'
````

Only the 'setBreakpoints' command is sent.

Does this issue occur when all extensions are disabled?: Yes

**Comment by juanantlopez** [comment]
Thanks a lot, this issue is triggered because a malformed response to SetBreakpoints request, see the response:
````json
VS <- DA '{"type":"response","request_seq":3,"success":true,"body":[{"id":0,"verified":true,"line":28,"column":1}]}'
````
the field 'breakpoints' was not send.

This was triggering an out-of-bound exception here, function sendBreakpoints in debugSession.ts:
````ts
if (response && response.body) {
    const data = new Map<string, DebugProtocol.Breakpoint>();
    for (let i = 0; i < breakpointsToSend.length; i++) {
        data.set(breakpointsToSend[i].getId(), response.body.breakpoints[i]); <-- HERE
    }

    this.model.setBreakpointSessionData(this.getId(), this.capabilities, data);
}
````
This exception was preventing to send the rest of the breakpoint requests but not stopping the debugging session. 

So again thanks helping me to pinpoint the culprit and it is up to you to decide whether it is still a valid issue or you want to keep it open in order to improve the error handling for malformed responses.

**Comment by isidorn** [comment]
For now closing this. If more extensions hit this we can improve our error handling.
Thanks for letting us know
