### ISSUE TITLE
Search "files to exclude" syntax does not match "files to include"

### ISSUE THREAD

**Issue by stickeegreg** [microsoft/vscode#99378]
Issue Type: <b>Bug</b>

Using the search menu from the left, I can search in a directory by setting "files to include" to any one of the following (on Windows):

`.\my\directory`
`./my/directory`
`my\directory`
`my/directory`

However when excluding a directory using "files to exclude"
`.\my\directory` doesn't work
`./my/directory` doesn't work
`my\directory` works
`my/directory` works

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/50638
