### ISSUE TITLE
VS Code crashes often

### ISSUE THREAD

**Issue by geekybugger** [microsoft/vscode#99383]
Issue Type: <b>Performance Issue</b>

I am using VS code for the past 2 years . After recent update, VS code crashes so often and also eats up a lot of RAM. I request the team to fix it ASAP. Thank you :)

With Regards,
V Krishnakumar

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.25GB free)|
|Process Argv|C:\Users\krish\Desktop\covid-19-tracker|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
kite|kit|0.114.0
python|ms-|2020.5.80290
vscode-react-native|msj|0.16.0
material-icon-theme|PKi|4.1.0

(3 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
Please [capture a crash report](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues) and share it with us so that we can track it down. Thanks!

/needsMoreInfo

**Comment by geekybugger** [comment]
> Please [capture a crash report](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues) and share it with us so that we can track it down. Thanks!
> @vscode-triage-bot 
> /needsMoreInfo

![57916079-c159ab80-78af-11e9-9e5f-733abf3861fe](https://user-images.githubusercontent.com/15953689/83959816-3e7f0680-a89f-11ea-8382-add776656376.png)


Hello Developers, The Above is the screenshot of my crashing report . This issue mainly happens when I try to open a development server (like ` npm start `). Also when I hit reopen , it just keeps looping the same warning. Thankfully, VS code manages to save my work... 👍

**Comment by geekybugger** [comment]
> 2nd this, VSCode is very unstable now.

Yes, 😄  especially in windows, It eats up a lot of memory that eventually slows down my laptop. SICK 😪

**Comment by connor4312** [comment]
Thanks for the screenshot, however that's not the crash report we're after. The link I posted has instructions for how to capture crash reports. Thanks!

**Comment by sjdurfey** [comment]
For me, VSCode crashes immediately when starting up. I'm not even seeing the shell and getting a crash message. I can see the crash in the macOS system.log
```
Jun  9 10:42:17 StephensMBPWork com.apple.xpc.launchd[1] (com.microsoft.VSCode.18508[76135]): Service exited with abnormal code: 1```
But there isn't anything in `User Reports` in the macOS console (per the crash report guide). I do get the following information from the command line
```bash
⇒  code --version
1.45.1
5763d909d5f12fe19f215cbfdd29a91c0fa9208a
x64
#:~/Documents|
⇒  code --verbose
[76828:0609/104544.138813:WARNING:dns_config_service_posix.cc(184)] dns_config has unhandled options!
[main 2020-06-09T15:45:44.293Z] Error: connect EACCES /Users/<user>/Library/Application Support/Code/1.45.1-main.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
[main 2020-06-09T15:45:44.294Z] Lifecycle#kill()
```

**Comment by sjdurfey** [comment]
VS Code insiders version does work for me, but the error I was seeing is with the stable version I downloaded from the website. I also redownloaded it, deleted the old app, and used the new download, and it still had the same issue described above.
