### ISSUE TITLE
Ctrl + F2 doesn't open Find box correctly

### ISSUE THREAD

**Issue by Zappysam** [microsoft/vscode#99381]
- VSCode Version: 1.45.1
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Make sure that the Find and Replace box is not currently open
2. Highlight something in a document and press Ctrl + F2 to highlight all instances of it
3. Find and Replace box is half-loaded 

Does this issue occur when all extensions are disabled?: Yes/No

Yes it does.

Here is a screenshot of what it looks like:

![Ctrl F2 Issue](https://user-images.githubusercontent.com/66431876/83779418-83adf900-a651-11ea-9554-18f5197717a0.jpg)

**Comment by Zappysam** [comment]
This has been reproduced on a different machine running the same version of Windows and VSCode

**Comment by roblourens** [comment]
It's not supposed to open the find box, that command only selects all occurrences. That box shows you whether it will be case-sensitive, etc, and you can change those with commands like `alt+c`. That state is also used for other multicursor commands like ctrl+d
