### ISSUE TITLE
Intellisense doesn't work for python virtual environments that are locally installed

### ISSUE THREAD

**Issue by zackees** [microsoft/vscode#99389]
- VSCode Version: 1.27.2
- OS Version: macOS 10.15.5

Steps to Reproduce:

1. Download my code repo that I've zipped up here: https://drive.google.com/file/d/16uG-futxJSiU162Ry1TKB-k0VbTP0QVt/view?usp=sharing

2. Unzip into zachvorhies_com_dynamic 

3. Open up VS code, open the folder from the root folder.

4. Select the prod_env/.../python as the current interpreter, if it isn't already there.

5. Open up any python file.

6. Select any variable in the program (preferably local scope), right click and "find all references".

7. Notice that the VSCode will spin forever trying to find the reference and will never complete.

This all worked before I created a virtual environment using pyenv.

Does this issue occur when all extensions are disabled?: Yes/No

I'm using the python intellisense python extension so this doesn't apply.

**Comment by connor4312** [comment]
\extPython
