### ISSUE TITLE
Sluggish Performance when using External Display

### ISSUE THREAD

**Issue by frictionlessDevelopments** [microsoft/vscode#99387]
- VSCode Version: 1.46.0-insider
- OS Version: macOS 10.15.5 (19F101)
- Extensions Installed: none

Steps to Reproduce:

0. **NEW 20201112** Have a calibrated profile installed for the external monitor
1. Quit VSCode before attaching the external monitor
2. Sleep your mac
3. Hook up your Macbook to an external display ([as described here](https://support.apple.com/en-us/HT201834))
4. Launch VSCode. You'll start to notice that VSCode now performs really slowly.

Workaround

1. Do not quit VSCode when you're on your macbook without the external monitor attached
2. Sleep
3. Hook up your Macbook to an external display
4. No performance hit.

Workaround 2 **NEW 20201112**
1. Remove the calibrated profile installed for the external monitor

Does this issue occur when all extensions are disabled?: Yes

Strangely, when I attempted to profile performance, this problem would go away.
The typing speed goes back to normal, and VSCode behaves normally.

https://www.icloud.com/iclouddrive/0DJATm0_JKYV8SVv7HFAtUOGA#vscode_performance

**Comment by nidty719** [comment]
Just solved this by changing the calibrated color profile I had. I put it back to the default and now vscode and all the other apps are running great

**Comment by deepak1556** [comment]
Can you check if the issue happens with our latest [insiders](https://code.visualstudio.com/insiders) and [exploration builds]( https://az764295.vo.msecnd.net/exploration/3c1b4bacbef4ab788f72059f56ef53e9aa7923bc/VSCode-darwin.zip) ?

**Comment by frictionlessDevelopments** [comment]
> Just solved this by changing the calibrated color profile I had. I put it back to the default and now vscode and all the other apps are running great

@nidty719 is correct. Removing my calibrated color profile completely resolves this issue for me.

---

Both builds are still facing the same issue when you have a calibrated color profile.

`Version: 1.52.0-insider
Commit: 40558fc8e13dbdceee5f4a9ad3fc661b9f8dae15
Date: 2020-11-11T16:49:20.394Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0`

`Version: 1.52.0-exploration
Commit: 3c1b4bacbef4ab788f72059f56ef53e9aa7923bc
Date: 2020-11-04T06:53:16.102Z (1 wk ago)
Electron: 11.0.0-beta.17
Chrome: 87.0.4280.27
Node.js: 12.18.3
V8: 8.7.220.8-electron.0
OS: Darwin x64 19.6.0`
