### ISSUE TITLE
Wrong Syntax highlighting for parameter decorators

### ISSUE THREAD

**Issue by thomaspink** [Microsoft/vscode#9939]
- VSCode Version: Version 1.4.0-insider (1.4.0-insider)
- OS Version: MacOS 10.11.5

Steps to Reproduce:

1. Use multiple parameter decorators on your constructor (like Angular's `@Inject`)
2. The first decorator is highlighted different than the others (see screenshot)

![syntaxhighlight-error1](https://cloud.githubusercontent.com/assets/1368032/17241455/0d756662-5572-11e6-9a01-bdec3ed6cbbc.jpg)

**Comment by dominikstrasser** [comment]
Same here - this really bugs me :/

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#227
