### ISSUE TITLE
Can't copy out of a notebook's output cell

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#99398]
Currently you can seem to copy text out of a notebook cell -- there is no context menu, nor shortcut keys that work.

Related #90110

**Comment by netocervantes98** [comment]
Is this still an issue? If I try to copy from a cell output (in notebook preview) I get the following message:
`Cannot read property 'contains' of undefined`

**Comment by rebornix** [comment]
@netocervantes98 can you provide more details about how you end up with the error?

**Comment by netocervantes98** [comment]
I'm in the insiders version. I restarted it and the problem is gone.
