### ISSUE TITLE
Razor support not working!

### ISSUE THREAD

**Issue by bra0** [microsoft/vscode#99392]
Issue Type: <b>Bug</b>

Razor support not working

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.3.0-53-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz (4 x 2942)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|10.41GB (1.52GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|openbox|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|openbox|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
razor-snippets-for-asp-net-core|ale|0.0.3
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
vscode-google-translate|fun|1.4.5
todo-tree|Gru|0.0.176
vue|jcb|0.1.5
csharpextensions|jch|1.3.1
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|0.1.11
node-module-intellisense|lei|1.5.0
vscode-docker|ms-|1.2.1
csharp|ms-|1.22.0
remote-wsl|ms-|0.44.2
code-settings-sync|Sha|3.4.3
bootstrap-3-snippets|wcw|0.1.0

</details>

**Comment by connor4312** [comment]
\extCsharp
