### ISSUE TITLE
Scrolling Large Github Notebook with pictures is stuttery

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#99393]
1. Create a large Github notebook with large images
2. Scroll
3. 🐛 The scrollbar bounces a lot and is stuttery

**Comment by roblourens** [comment]
I don't know how to avoid this, I don't think we want to preload images/other content but that's probably what other notebooks do.

**Comment by rebornix** [comment]
There are actually two different factors to the sluggish.

One is we didn't set the dynamic height to `false` on code cells with image outputs, thus the list view to probeDynamicHeight by creating the cells again and after creation, it checks the size of the DOM node, and it often gets ~30px. In a 600px height window, it will cause 20 images to be rendered on every round of `probeDynamicHeight` on a single element, so in total, it's around 400 (`20*20`) rendering of images for just rendering the viewport. Scrolling in the document will trigger similar massive rerendering.

Second is the real image resizing but I didn't see any major difference between images and other outputs.

**Comment by roblourens** [comment]
I think this was talking about images in markdown, not code cells
