### ISSUE TITLE
VS Code doesn't keep tabs as tabs in the output console/terminal

### ISSUE THREAD

**Issue by viniciusvillas** [microsoft/vscode#99395]
Issue Type: <b>Bug</b>

VS Code should keep printed tabs as tabs in the output console. This is specially helpfull for copy/pasting code to Excel.
![](https://i.imgur.com/6q3T2Lk.png)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.19041

**Comment by Tyriar** [comment]
This is how tabs in the terminal work; a tab goes to the shell and the shell says "move the cursor to position (x,y)". This may be different in conhost when using the Console API but we're emulating a *nix terminal here.

**Comment by viniciusvillas** [comment]
> This is how tabs in the terminal work; a tab goes to the shell and the shell says "move the cursor to position (x,y)". This may be different in conhost when using the Console API but we're emulating a *nix terminal here.

OK, two quick questions:
1) Why would you emulate a *nix terminal on a PowerShell console?
2) Considering that the terminal is still moving the cursor to position (x,y), shouldn't it print the actual character (tab = 9 or 0x09) instead of replacing it with spaces (space = 32 or 0x20)?
