### ISSUE TITLE
Virtual documents - Set a custom title when using openTextDocument

### ISSUE THREAD

**Issue by JeffreyCA** [microsoft/vscode#99403]
I'm building an extension and would like to create and open a virtual document and have the tab label display arbitrary text.

From what I'm seeing, the tab title is set to the URI's *filename*, which can't contain certain characters like `/`. But I want to be able to set the tab title to a string that could contain slashes for instance.

**Comment by jrieken** [comment]
> From what I'm seeing, the tab title is set to the URI's filename

Knowing this, I'd suggest to use a filename that makes sense

**Comment by JeffreyCA** [comment]
I'm building an data viewer extension for a key-value store and clicking a key name will display a virtual text document. However, keys can contain slashes which is problematic.

For example, I'd like the filename to appear as `key/with/slash:colon` (a valid key name) in the virtual document tab.

I can double-encode the key name in the URI like this, but the encoded characters appear in the tab name of the document: `key%2Fwith%2Fslash%3Acolon`.
```ts
let name = 'key/with/slash:colon';
let encoded = encodeURIComponent(encodeURIComponent(key));

let uri =  vscode.Uri.parse(`my-ext:data/${encoded}`, true);
let doc = await vscode.workspace.openTextDocument(uri);
await vscode.window.showTextDocument(doc, { preserveFocus: true, preview: false });
```

This results in `slash:colon`.
```ts
let name = 'key/with/slash:colon';
let encoded = encodeURIComponent(key);

let uri =  vscode.Uri.parse(`my-ext:data/${encoded}`, true);
let doc = await vscode.workspace.openTextDocument(uri);
await vscode.window.showTextDocument(doc, { preserveFocus: true, preview: false });
```

Do you have other suggestions?
