### ISSUE TITLE
Mixed Case Search - No Results

### ISSUE THREAD

**Issue by crappy-coder** [microsoft/vscode#99404]
Issue Type: <b>Bug</b>

Repo Steps:
1. Create a source file, shouldn't matter but I tried with a .go and .sh
2. Add the text "FOO_BAR"
3. Search for "Foo_BaR" with [Match Case] and [Whole Words] OFF

Expected:
Search to find the text "FOO_BAR"

Actual:
No results found, however, when searching for "FOO_BAR" OR "foo_bar", the results were found.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900X CPU @ 3.50GHz (20 x 3504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.68GB (117.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Looks like you have **Search: Smart Case** (`"search.smartCase"`) enabled. Is it the case?
You need to disable it if you want to see matches with mixed case

**Comment by crappy-coder** [comment]
> /needsMoreInfo
> 
> Looks like you have **Search: Smart Case** (`"search.smartCase"`) enabled. Is it the case?
> You need to disable it if you want to see matches with mixed case

Yes, indeed that is the case. Closing, thanks!
