### ISSUE TITLE
Typscript Server Keeps crashing

### ISSUE THREAD

**Issue by mitch726** [microsoft/vscode#99402]
Issue Type: <b>Bug</b>

The typescript server keeps crashing and I'm not sure why. It's happened repeatedly for the last hour.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz (20 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (8.80GB free)|
|Process Argv|--folder-uri file:///c%3A/Source/Repos/Teamspace-Web|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.36.0
jshint|dba|0.10.21
gitlens|eam|10.2.1
beautify|Hoo|1.5.0
graphql-for-vscode|kum|1.15.3
powershell|ms-|2020.4.0
vscode-typescript-tslint-plugin|ms-|1.2.3
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.8
vscode-jest|Ort|3.2.0
markdown-preview-enhanced|shd|0.5.10
teams-dyson|tea|0.0.2020021302

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
Also, please share the error message or the error stack from the crash
