### ISSUE TITLE
debt - refine DocumentLinkProvider api

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#9940]
The current link provider API is designed that the provider is asked for all links when contents changes. For simple links this is easy but if the computation of link targets are expensive we should support a `resolve` model (like we allow to resolve code lenses and completion items). So the enhanced version would be

```ts
interface DocumentLinkProvider {
  provideDocumentLinks():DocumentLinks[];
  resolveDocumenLink?: (link: DocumentLink) => DocumentLink
}
```

When compute all links (`provideDocumentLinks`) it will be enough to just give a range and only when a link is selected `resolveDocumentLink` is called to fill in the target (iff expensive to compute)

**Comment by ThisIsManta** [comment]
@jrieken 
My problem is, `resolveDocumentLink` does not provide `TextDocument`, unlike `provideDocumentLinks`.

So I could not perform an expensive calculation in `resolveDocumentLink` using only `range` from an incomplete `DocumentLink` without knowing `TextDocument`.

I don't think grabbing `vscode.window.activeTextEditor.document` myself would be the safest idea. 
Please enlighten me.

**Comment by jrieken** [comment]
Correct... The usual pattern we have is to allow providers to return a subtype ala `class MyLink extends DocumentLink { // keeps more state}` and on resolve we would give you that *instance*. We do that IntelliSense and a few places but it seems we don't do that for links. I'll create another issue for that.

**Comment by jrieken** [comment]
There you go: https://github.com/Microsoft/vscode/issues/32788

**Comment by ThisIsManta** [comment]
First of all, thank you for your swift response.

Secondly, I was doing that (create my own class which extends `DocumentLink`), but then I realized you stripped off everything else, except the valid `DocumentLink` properties.

I see your commit(s) now. Looking forward to the new API.

Cheers!
