### ISSUE TITLE
intellisense keeps rebuilding references Unity C#

### ISSUE THREAD

**Issue by HawkenKing** [Microsoft/vscode#9941]
![intelli](https://cloud.githubusercontent.com/assets/5999766/17244794/9e4981c2-55be-11e6-9274-f3cd1ec91c99.gif)
- VSCode Version: Version 1.3.1 (1.3.1)
- OS Version: OSX 10.11.3

Steps to Reproduce:

1. install VSCode
2. write in a Unity C# project

As you type, suddenly intellisense is lost and all the references & auto complete are gone, then a few seconds later they come back. Coding like this is very frustrating as everything moves up and down all the time.

**Comment by kieferrm** [comment]
@HawkenKing I moved this issue to the C# extensions issue repo. Pls subscribe to https://github.com/OmniSharp/omnisharp-vscode/issues/637.
