### ISSUE TITLE
UX - Search panel "Toggle search detail" is default enable

### ISSUE THREAD

**Issue by mallocwang** [microsoft/vscode#99417]
Search is very high frequency operation, But detail mode is not very common scenario. (may make search panel smaller)
So can i default disable "Toggle search detail" or just remember the last state when next open vscode.

**Comment by roblourens** [comment]
Sorry I don't understand the request. What do you want to disable?

**Comment by mallocwang** [comment]
> Sorry I don't understand the request. What do you want to disable?

When open vscode,  search panel default in detail mode. (right after input line function by [...] ).
So "Search panel" with three input line area: 1. "SearchText", 2."Files to include", 3."Files to exclude".
I'd like to default not enable detail mode. just one "SearchText" input line area, or remember the last state of "[...]", so i don't need click "[...]" everytime i open vscode

**Comment by mallocwang** [comment]
> Sorry I don't understand the request. What do you want to disable?

Thanks for reply.
When open vscode, search panel default in detail mode. (right after input line function by [...] ).
So "Search panel" with three input line area: 1. "SearchText", 2."Files to include", 3."Files to exclude".
I'd like to default not enable detail mode. just one "SearchText" input line area, or remember the last state of "[...]", so i don't need click "[...]" everytime i open vscode

**Comment by roblourens** [comment]
It should remember the last state per workspace. Are you sure it's not doing that? If you close it then run "Reload Window", does it become opened?

**Comment by mallocwang** [comment]
> It should remember the last state per workspace. Are you sure it's not doing that? If you close it then run "Reload Window", does it become opened?

Yes, it works now. I think may be there is a not saved workspace before, so vscode not remember the state. now vscode works as expect. Thank you!
