### ISSUE TITLE
Stuck installing cobol-plus-pack

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#99414]
- VSCode Version: 1.45.1
- OS Version: Windows 10

Steps to Reproduce:

1. Have cobol-plus-pack in your Sync Settings:

```json
  {
    "metadata": {
      "id": "c9307bf1-5817-4295-a866-501e9e21b2f0",
      "publisherId": "bitlang.cobol-plus-pack",
      "publisherDisplayName": "bitlang"
    },
    "name": "cobol-plus-pack",
    "publisher": "bitlang",
    "version": "1.0.5"
  }
```

As long as this block is there, then Sync Settings tries indefinitely to install this extension. Worse, the extension doesn't show up in the VSCode plugin list. It's hidden. You have to manually cut it out of the Sync Settings data to work around.

Does this issue occur when all extensions are disabled?: No

**Comment by sandy081** [comment]
Seems you are using Settings Sync extension for this, so please file an issue against https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

FYI VS Code supports sync out of the box which is a preview feature and is available only in insiders - https://code.visualstudio.com/docs/editor/settings-sync
