### ISSUE TITLE
Allow to customize the application icon per workspace

### ISSUE THREAD

**Issue by 5dao** [microsoft/vscode#99415]
![taskbar](https://user-images.githubusercontent.com/5286750/83827406-e2867780-a710-11ea-8611-7b580f3beebc.png)

 Please vote to it ！

Open many vscode instance, with documents and projects in different languages, but taskbar icon is too single to distinguish easily

#84888
> In the last 60 days, this feature request has received less than 20 community upvotes and we closed it.

**Comment by 5dao** [comment]
Can you vote for it?
@jaramillo-carlos @UAQureshi @j-a-lewis @LucaGabi @rgfpy @vmanolasBeat
@aJamDonut @ubugnu @thombee @corydorning @omarefg @bckelley
@Pmoshbr @eine @talonrenaud @ent3r @j-a-lewis @eine
@j-a-lewis @eine @cloudziu @marqusG @mmege @slimterry
@iamsarthakjoshi @csears123 @shane-smith @QuentinDanjou @qzdl @ClintOxx
@csears123 @shane-smith @mittalyashu @HansHovanitz @rayholtz @outpoints
@faisalsanyo @hcallaway @zjp @damniamgood @siran @mookman288
@MikeChipshop @zbentley @develleoper @amandaporto

**Comment by mittalyashu** [comment]
Separate vscode application icon based on languages is not a good option, what if we’re using workspace opening different language projects in single vscode instance.

**Comment by 5dao** [comment]
> Separate vscode application icon based on languages is not a good option, what if we’re using workspace opening different language projects in single vscode instance.

As a heavy user, all projects, knowledge management and notes cannot be put in one  single vscode instance.

**Comment by 5dao** [comment]
> > Separate vscode application icon based on languages is not a good option, what if we’re using workspace opening different language projects in single vscode instance.
> 
> As a heavy user, all projects, knowledge management and notes cannot be put in one single vscode instance.

vscode is a swiss army knife,There are many uses, such as SVG draw and SQL management tool. I just want to use different uses and icons to distinguish them

**Comment by QuentinDanjou** [comment]
As most of the time projects uses different languages, I don't agree with the example however it can still be interesting to do it between projects(workspaces) when the user want a personal icon. I am also worrying about the feasibility on every OS.

> As a heavy user, all projects, knowledge management and notes cannot be put in one single vscode instance.

Well, I believe this is wrong and it is interesting to have the possibility to open multiple project in the same window as in #43188 but I understand that it may be interesting for some usage (as you pointed out just after) to have multiple window with different icons. _A bit like if you had multiple applications._

So yes, why not +1 :)

**Comment by zjp** [comment]
I'm not sure what I have to do with this issue; I use Emacs.

**Comment by 5dao** [comment]
Can you vote for it?
@IllusionMH @deepak1556 @GeorgeWL @manospasj  @SonOfHans @levrik @jsgoupil @kosmakoff @DanJ210 @SamHasler @Silic0nS0ldier @mate131909  @kcbleeker @Stefan-Z-Camilleri @jlira2 @PirateBread @ryan-harris @Silic0nS0ldier @mlewand @drewhemm @goleary @dhallstr @dwaynebradley @goleary @sagilevanon @airtonix @goleary

**Comment by GeorgeWL** [comment]
Don't spam random usernames

**Comment by aJamDonut** [comment]
Don't spam random usernames

**Comment by 5dao** [comment]
> Don't spam random usernames

It's not random, it's selected from relevant topics

**Comment by 5dao** [comment]
> Don't spam random usernames

I found your ID from the related topic reply， I just think it's possible for you to approve of this vote

**Comment by 5dao** [comment]
> Can you vote for it?
> @IllusionMH @deepak1556 @GeorgeWL @manospasj @SonOfHans @levrik @jsgoupil @kosmakoff @DanJ210 @SamHasler @Silic0nS0ldier @mate131909 @kcbleeker @Stefan-Z-Camilleri @jlira2 @PirateBread @ryan-harris @Silic0nS0ldier @mlewand @drewhemm @goleary @dhallstr @dwaynebradley @goleary @sagilevanon @airtonix @goleary

Hello everyone, not randomly generated ID, but from the relevant topic reply to see, not intended to disturb you, but I believe you have this view

**Comment by sagilevanon** [comment]
STOP TAGGING PEOPLE! 
It's randomly generated since I have NEVER posted a message about this topic or anything close to that. As a matter of fact, that's my second post on this platform. STOP harassing random people, you're embarrassing yourself. 
No need to reply to this post. I have unsubscribed anyway.

**Comment by GeorgeWL** [comment]
This sounds too specialised to ever see wider usage.

I think if you want this, you'd be better creating an extension which does this.

VSCode is designed for general purpose dev, and this goes against that idea.

**Comment by 5dao** [comment]
> This sounds too specialised to ever see wider usage.
> 
> I think if you want this, you'd be better creating an extension which does this.
> 
> VSCode is designed for general purpose dev, and this goes against that idea.

Well, I tried to extend the method, but failed. This has a deep relationship with the OS

**Comment by GeorgeWL** [comment]
That sounds like a "your problem" thing

**Comment by kcbleeker** [comment]
Based on being randomly tagged in this issue, I'm going to explicitly stated that I want this feature to not be implemented.

That's a -1 from me.
