### ISSUE TITLE
Can trigger "Pin Tab" too easily by accident

### ISSUE THREAD

**Issue by imahassle** [microsoft/vscode#99412]
Issue Type: <b>Bug</b>

Open a file as a draft, then use `Ctrl + k + Enter` chord  to focus file.

Expected: Tab opens as a focused file with filename in tab.
Reality: Tab collapses to just the filetype of the file, with no file name visible. Can still click on tab to view file.

This seems to only happen for the first file opened, the rest of the file tabs are unaffected.

VS Code version: Code - Insiders 1.46.0-insider (c7a37c4400bb4c1b92eeeaea1bcacc9ec3789ef3, 2020-06-04T08:37:48.091Z)
OS version: Windows_NT x64 10.0.19640

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (2.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.1.4
githistory|don|0.6.5
gitlens|eam|10.2.1
prettier-vscode|esb|5.0.0
vscode-solution-explorer|fer|0.3.10
csharp|ms-|1.22.0
remote-wsl|ms-|0.44.2
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.8
material-theme|zhu|3.7.1
html-css-class-completion|Zig|1.19.0
tslint-snippets|zuo|1.1.0

</details>

![image](https://user-images.githubusercontent.com/4740213/83821900-79592280-a684-11ea-8ce1-794317aab393.png)

**Comment by gjsjohnmurray** [comment]
Looks like you just discovered the new tab pinning feature. See #98558

**Comment by bpasero** [comment]
This makes me think that the keybinding should maybe be different for "Pinning".

**Comment by bpasero** [comment]
I changed the keybinding to be `CtrlCmd+K Shift+Enter`.

**Comment by imahassle** [comment]
Ah what a neat feature! I appreciate the quick response. I also didn't realize there were so many shortcut chords that used `Ctrl +` as the second part of the chord!

I think it makes sense to keep the "pin" shortcut close to the "keep open" shortcut since they are so similar in behavior. I'll try out the new command, but playing with the old one, I think I might like it better.
