### ISSUE TITLE
Cannot read property 'start' of undefined: TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#99410]
Issue Type: <b>Bug</b>

Seeing this frequently in my pipeline builds (e.g. https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=20513&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=95359773-9cfc-583f-7b87-0a0d44ca7da9&l=769).  Have occasionally see it locally, but don't have a repro scenaro.

Pretty sure this is not in my code.

VS Code version: Code - Insiders 1.46.0-insider (595d2b9b916d063aadfc2c1a8c8f6df5b45572a8, 2020-06-03T05:38:33.098Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azurestorage|ms-|0.9.0
vscode-azurevirtualmachines|ms-|0.1.0
vscode-cosmosdb|ms-|0.13.0
vscode-docker|ms-|1.2.1
csharp|ms-|1.22.0
vscode-dotnet-runtime|ms-|0.1.2
azure-account|ms-|0.8.11
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-yaml|red|0.8.0
tmcolor|sle|0.0.1
vscode-todo-highlight|way|1.0.4

</details>

**Comment by StephenWeatherford** [comment]
intersection(t){const i=v.Max(t.**start**,this._start)

**Comment by alexdima** [comment]
https://github.com/microsoft/vscode/blob/33676982c8eb722545b5108a8f24bd037d01089f/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L390

**Comment by StephenWeatherford** [comment]
Thanks for the pointer, allowed me to find the issue - our language server was returning some Diagnostics with a null Range.  This wasn't a problem for publishing errors to the diagnostics collection, that code was tolerant of this and this code has been like this a long time.

What triggered the error is that we started implementing provideCodeActions in the TypeScript (completely separate from our language server, which is a C# LSP), and *that* code in vscode didn't handle the null ranges in the diagnostics collection.  Seems like this could trip other extensions even...

I've fixed our code, but I recommend that you either sanitize the range when they're pushed to a diagnostics collection teach the code actions code to be tolerant of a null range.  Thanks!

**Comment by mjbvz** [comment]
@sandy081 Assigning you since it sounds like we may want to validate diagnostics before adding them to the diagnostic collection

**Comment by sandy081** [comment]
This seems to be in diagnostics API so moving to @jrieken

**Comment by jrieken** [comment]
creating diagnostics without range or message now throws a type error

**Comment by StephenWeatherford** [comment]
Thx

**Comment by isidorn** [comment]
Adding verified based on code review
