### ISSUE TITLE
Settings tab closes when opening a file that doesn't already have an open tab

### ISSUE THREAD

**Issue by 7--** [microsoft/vscode#99418]
- VSCode Version: 1.45.1-1589445302
- OS Version: Ubuntu 20.04 LTS 

Steps to Reproduce:

1. Open Settings (Ctrl + ,)
2. Click to open a file that doesn't already have an open tab.
3. Notice the Settings tab is replaced by the clicked file.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by gjsjohnmurray** [comment]
Have you understood about VS Code's preview mode?

**Comment by 7--** [comment]
No I've never used anything like that. I expect tabs to stay open until I close them. Thanks for letting me know I disabled Preview Mode.
