### ISSUE TITLE
Preview variable annoyance width of window to narrow not scrollable

### ISSUE THREAD

**Issue by asdf23** [microsoft/vscode#99416]
Issue Type: <b>Bug</b>

While debugging hover over any variable that's not an integer, the width of the popup window makes it impossible to use this feature.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.6.11-200.fc31.x86_64

**Comment by isidorn** [comment]
This is fixed in latest. Use vscode insiders or wait for the update in about a week and it should be fixed. Thanks
