### ISSUE TITLE
Notebook should use var(--monaco-monospace-font);

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#99424]
I see a few `font-family` in notebook land that should pick our CSS variables. Specifically `var(--monaco-monospace-font);`.

Location I found: `src/vs/workbench/contrib/notebook/browser/media/notebook.css`

//cc @misolori

**Comment by misolori** [comment]
@bpasero did you already fix these in https://github.com/Microsoft/vscode/commit/588097171c872f26ad9dcd9cf0441cf5b1a8b7e7?
