### ISSUE TITLE
Remove 'xsl' (sic) support from the built-in extension 'XML Language Basics' 

### ISSUE THREAD

**Issue by pgfearo** [microsoft/vscode#99427]
I have published an [XSLT extension for VSCode](https://marketplace.visualstudio.com/items?itemName=deltaxml.xslt-xpath). I would like to follow the [Language Identifier Guidelines](https://code.visualstudio.com/docs/languages/identifiers#_new-identifier-guidelines) and use 'xsl' as the language identifier (despite it missing the 't' at the end) as this is already established for XSLT.

The 'XML Language Basics' built-in extension binds to the 'xsl' language identifier. However the only language features I can tell it provides are XML syntax highlighting and tag-matching. The bracket-matching settings in the built-in extension would prevent users of my extension getting proper matching of '(', '{', '[' characters in the embedded XPath language, this is a potential show-stopper for any developer.

Currently, while my extension is not published to the marketplace, (just limited pre-releases of the .vsix file) I'm avoiding clashes with this built-in extension by using the 'xslt' language identifier.

To allow my extension to use the 'xsl' language identifier, would it be possible to remove the 'xsl' language identifier binding from the built-in extension? 

Removing support for 'xsl' in the built-in extension would also help encourage existing VSCode users to seek an external extension (like mine) dedicated to the language, rather than assuming that their only choice was the built-in generic XML syntax highlighting.

**Comment by pgfearo** [comment]
I guess the consequences of using the ‘xslt’ language id for XSLT are probably not irreversible. I’ll go ahead and publish my extension then using ‘xslt’ in the hope that this inconsistency with the standard id can if necessary be unravelled in the future.

**Comment by pgfearo** [comment]
I’m reopening this issue, as the XSLT extension is now published but there appear (as feared) to be issues coexisting with at least one other XSLT extension that uses the ‘xsl’ language id. My extension can’t use ‘xsl’ unless my extension forgoes built in VSCodes built in bracket matching feature (required for XPath expressions embedded within XSLT).

**Comment by aeschli** [comment]
Sorry for not replying earlier. We already discussed more in  #102584.
I'm not sure if you still want me to remote the `<` from bracket-pairs.We can still do that if needed. Feel free to file a PR.

**Comment by pgfearo** [comment]
It’s ok, there’s no need now to tweak bracket matching. I hadn’t realised that the bracket-matcher feature is effectively broken if using the ‘xsl’ language id. It then parses xml attributes as strings so effectively overrides the XPath semantic tokens within xml attributes. 

XSLT extensions will now just need to use the non-standard ‘xslt’ language id if they want to coexist with the [DeltaXML XSLT extension.](https://marketplace.visualstudio.com/items?itemName=deltaxml.xslt-xpath)
