### ISSUE TITLE
please add full word search in visual studio code

### ISSUE THREAD

**Issue by digish777** [Microsoft/vscode#9942]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

1. please add full word search in visual studio code
2.

**Comment by glen-84** [comment]
Like this?

![search](https://cloud.githubusercontent.com/assets/261509/17276743/38f34c16-5732-11e6-9fcf-9bd7ad7677f8.png)

**Comment by digish777** [comment]
When you press ctrl+f. I did not get that option.

**Comment by mrmlnc** [comment]
@digish777, 
![image](https://cloud.githubusercontent.com/assets/7034281/17277797/abb3c45c-5754-11e6-9614-de7b7b94037c.png)

**Comment by kieferrm** [comment]
@digish777 as @mrmlnc points out, that already exists.
