### ISSUE TITLE
split line highlight border and cell region lines

### ISSUE THREAD

**Issue by Monokai** [microsoft/vscode#99425]
Currently, setting `editor.lineHighlightBorder` to `#FF0000` also sets the Jupyter cell region lines:

![Screen Shot 2020-06-05 at 08 48 27](https://user-images.githubusercontent.com/277589/83845682-a69be400-a709-11ea-89f1-3b2a54efa223.png)

I'd like to have the option to style the border around the currently selected line differently from the cell regions. Specifically, I'd like to have a line designating the cell regions, but to not have a border around the currently selected line in the editor.

**Comment by rebornix** [comment]
I think the Python extension adds the decoration around the border of the cell region. @DonJayamanne can you help confirm that?

**Comment by DonJayamanne** [comment]
@rebornix Yes, this is the case, please could you transfer this issue to our Python repo.

**Comment by rebornix** [comment]
@DonJayamanne It seems I don't have the rights to do that ;)

**Comment by rebornix** [comment]
Let's now track it in https://github.com/microsoft/vscode-jupyter/issues/8005
