### ISSUE TITLE
Changes view: items no longer aligned when icons disabled

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#99423]
**Stable:**

![image](https://user-images.githubusercontent.com/900690/83841269-ced31500-a700-11ea-9dc3-1cf624f0adb3.png)

**Insiders:**

![image](https://user-images.githubusercontent.com/900690/83841283-d4305f80-a700-11ea-97f3-69db81d0f71e.png)

**Comment by joaomoreno** [comment]
Related: https://github.com/microsoft/vscode/issues/99008

**Comment by joaomoreno** [comment]
Closing as designed, as discussed.
