### ISSUE TITLE
"Evaluate In Debug Console" function without moving focus to Debug Console

### ISSUE THREAD

**Issue by jhyunetp** [microsoft/vscode#99437]
I tend to use "Evaluate In Debug Console" to develop like the function "Evaluate Selection" in Matlab.

But moving focus to Debug Console seriously cumulatively takes my time a lot.

Please add these functions...

disable moving focus.

evaluate the current line of keyboard cursor focus if there is no selection.

Or is it possible for me to add these functions as extension ?

thank you for consideration.

To remove that focus, ( tested on my local )

File : "Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.js"

previously 

```
class S extends r.EditorAction{constructor(){
    super({id:"editor.debug.action.selectionToRepl",label:i.localize(4,null),alias:"Evaluate",
    precondition:a.ContextKeyExpr.and(s.EditorContextKeys.hasNonEmptySelection,l.CONTEXT_IN_DEBUG_MODE,s.EditorContextKeys.editorTextFocus),
    contextMenuOpts:{group:"debug",order:0}})}
    async run(e,t){const i=e.get(l.IDebugService),n=e.get(g.IViewsService),o=i.getViewModel(),s=o.focusedSession;
        if(!t.hasModel()||!s)
        return;
        const r=t.getModel().getValueInRange(t.getSelection());
        await s.addReplExpression(o.focusedStackFrame,r),await n.openView(l.REPL_VIEW_ID,!0)}}


```
```
class S extends r.EditorAction{constructor(){
    super({id:"editor.debug.action.selectionToRepl",label:i.localize(4,null),alias:"Evaluate",
    precondition:a.ContextKeyExpr.and(s.EditorContextKeys.hasNonEmptySelection,l.CONTEXT_IN_DEBUG_MODE,s.EditorContextKeys.editorTextFocus),
    contextMenuOpts:{group:"debug",order:0}})}
    async run(e,t){const i=e.get(l.IDebugService),n=e.get(g.IViewsService),o=i.getViewModel(),s=o.focusedSession;
        if(!t.hasModel()||!s)
        return;
        const r=t.getModel().getValueInRange(t.getSelection());
        await s.addReplExpression(o.focusedStackFrame,r)}}
```

+ is it possible for me to add this extension with dependency on vscode workbench?

thank you

**Comment by connor4312** [comment]
The setting `debug.internalConsoleOptions` may be what you're looking for. Let us know if not.

**Comment by jhyunetp** [comment]
I set that as "NeverOpen" 
But it doesn't work...
I think it is irrelevant to when I debug-evaluate ;(

**Comment by jhyunetp** [comment]
Please add another option for this or remove that focus movement.
A lot of data scientists around me are bothered by this unnecessary action :(

**Comment by isidorn** [comment]
Thanks for providing feedback, I do not like introducing settings for small things like this.
And I think the behavior which you want is actually ok for all cases. So for now I have changed it to never pass focus.
Let's see if some users complain and if that is the case we can make a setting or look at other options
