### ISSUE TITLE
Click-to-maximize split editor does not work under certain conditions

### ISSUE THREAD

**Issue by 0mza987** [microsoft/vscode#99438]
- VSCode Version: 1.45.1
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Put 2 files in split editors
2. Maximize the right one
3. Click in the left editor and you are able to maximize the left editor
4. Ctrl+B to open the Explorer
5. Click in the right editor and you are able to maximize the right editor
6. Ctrl+B again to hide the Explorer
7. Click in the left editor and you can not maximize the left editor

I found this because I often toggle between two split editors and click-to-maximize is really a good feature in my case, but when I open/hide explorer this feature occasionally failed and I managed to reproduce it following above steps, hope you guys can fix this bug. Thanks in advance.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
There is a bug already for this, sorry for being too lazy to find it...

**Comment by 0mza987** [comment]
> There is a bug already for this, sorry for being too lazy to find it...

Okay but will you fix this bug?

**Comment by joaomoreno** [comment]
We sure will!
