### ISSUE TITLE
Hide commands from being customisable

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#99439]
When you define commands for a view, sometimes these commands only make sense for the `TreeItem` that the user has focused/selected/hovered.

```json
            "view/item/context": [                {
                {
                    "command": "bookmarks.editLabel",
                    "when": "view == bookmarksExplorer && viewItem == BookmarkNodeBookmark",
                    "group": "bookmark@1"
                },
                    "command": "bookmarks.editLabel",
                    "when": "view == bookmarksExplorer && viewItem == BookmarkNodeBookmark",
                    "group": "inline@1"
                }
```

In these case, you may decide to _hide_ the command from the `Command Palette`, and to do so, you do this:

```json
        "menus": {
            "commandPalette": [
                {
                    "command": "_bookmarks.editLabel",
                    "when": "false"
                },
```

This works perfectly, and the command is properly hidden from the Command Palette 👏 

But, this command is still _customisable_ to the end user in the `Preferences` panel (UI and JSON) and so, the user is able to define a `Keyboard Shortcut` and fire the command. The command may not work, because it expects a focused/selected/hovered `TreeItem` `node.command.arguments[0].

I asked for advices in the [VS Code Development Community Slack channel](https://vscode-dev-community.slack.com/archives/C74CB59NE/p1591268815192600) and a user gave me the tip to prefix the command with `_`, and it worked perfectly! Another user pointed out that these _xyz commands are so called _internal_ commands (when you use the `commands.getCommands` API).

In fact, I was expecting the command to be unavailable simply because I hide it from the `Command Palette`, but it appears not be the case. So, I'm asking one of these two options:

* Add proper documentation to these _internal_ commands in the [Contributes Command API topic](https://code.visualstudio.com/api/references/contribution-points#contributes.commands)
* Add another `contribution point` attribute to define a command as _internal_

I think the first option is already enough, and would work just fine. This information could be added like the [Context specific visibility of Command Palette menu items](https://code.visualstudio.com/api/references/contribution-points#Context-specific-visibility-of-Command-Palette-menu-items) section.

Thank you

**Comment by jrieken** [comment]
> Another user pointed out that these _xyz commands are so called internal commands (when you use the commands.getCommands API).

Yeah, that doesn't buy you much because it more a convention that some parts of the UI and API honour. 

> Add another contribution point attribute to define a command as internal

Well, that would mean users cannot associate keybindings to your command, like not even when the tree shows and focuses a target item. Generally (and I think that still makes sense) we recommend to write commands without assuming certain arguments, e.g bail out early or (better) try find the argument, e.g get the selection from your tree view.

**Comment by dcermak** [comment]
Johannes Rieken <notifications@github.com> writes:

>  or (better) try find the argument, e.g get the selection from your tree view. 

This is possible in certain cases, but otherwise risky at best or even
downright impossible. Having a way how commands can be forbidden from
being called outside of their context would be very helpful (at least
for me).

**Comment by jrieken** [comment]
> Having a way how commands can be forbidden from being called outside of their context would be very helpful (at least for me).

I understand that. The challenge is that internally we don't even know that a command is invoked outside of its context... 🙃 

It is always fair to simply do nothing in your commands but in my own extensions I have felt that pain... Maybe some smarter context keys can help, like "my tree is visible and an element type foo is focused/selected"

**Comment by alefragnani** [comment]
> without assuming certain arguments, e.g bail out early or (better) try find the argument, e.g get the selection from your tree view.

I thought about that too, and I already do this for some commands which depends on an `ActiveEditor` (just like a few native commands does). But I felt that in fact, the user being able to customize the keyboard shortcut for _hidden_ commands where a bug, until I learned about the `internal`. As @dcermak , this could be risky/hard, and I thought that the formalizing the hidden commands shouldn’t be an issue.

 > Maybe some smarter context keys can help, like "my tree is visible and an element type foo is focused/selected"

That’s an alternative. I just have to think about using the _visibility_ or _enablement_ attributes. And be sure the commands won’t execute, if the command is _unavailable_ :-)

**Comment by jrieken** [comment]
> And be sure the commands won’t execute, if the command is unavailable :-)

Commands can specify their `enablement` via a when-clause and we honour that ;-)

**Comment by alefragnani** [comment]
It was a _funny comment_ about a few other APIs (not VS Code related) I’ve playing recently, which does execute the command, even if the control is disabled or even invisible. Sad, but true 😢 .

**Comment by jrieken** [comment]
Yeah, I believe `executeCommand` ignores the enablement but menus and keybindings should not

**Comment by MrAndersen1** [comment]
> Yeah, I believe `executeCommand` ignores the enablement but menus and keybindings should not

Keybindings seemingly do ignore the enablement if there is an entry in e.g. "view/item/context" referencing the command.

But I've got some insight into how to treat the commands we provide through our extension after reading this thread (coming from #147838) so I'm satisfied enough.
