### ISSUE TITLE
Scrollbar slider difficult to see in dark themes

### ISSUE THREAD

**Issue by cocowalla** [Microsoft/vscode#9943]
- VSCode Version: 1.3.1
- OS Version: Windows 7

I'm colour blind (red/green, the most common type), and when using any dark theme I really struggle to see the scrollbar slider - there's just not enough contrast.

It would be helpful if themes were able to control the scrollbar colours. It would also be helpful if the scrollbar width could be increased (ideally themeable).

![Scrollbar](http://i.imgur.com/rojaTk6.png)

**Comment by csalv5** [comment]
yes, make it themeable please, at least for colors and transparency,  it's really difficult to see scrollbar, also i don't really like to see code cross the slider. Let us choose the right setting.

**Comment by bpasero** [comment]
This is supported with April release, the related colors to set are:

`scrollbarShadow`
`scrollbarSliderActiveBackground`
`scrollbarSliderBackground`
`scrollbarSliderHoverBackground`

(note that color names might still change!)
