### ISSUE TITLE
Slow Startup / more than60s

### ISSUE THREAD

**Issue by belotn** [microsoft/vscode#99431]
- VSCode Version: 1.45.1
- OS Version: Windows 2012R2

Steps to Reproduce:

1. Launch vsCode

Does this issue occur when all extensions are disabled?: Yes
Does this issue occur when AV is disabled?: Yes

Hello,

vscode is very slow to start since version 1.40, it ran on a 4vCPU 12GB RAM virtualMachine, i've try to launch without extension, without AV, without Git, it still take more than 60s to start. 

[prof-901e.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/4734728/prof-901e.extHost.cpuprofile.txt)
[prof-901e.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/4734729/prof-901e.main.cpuprofile.txt)
[prof-901e.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/4734731/prof-901e.renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
The attached profiles don't show anything special. The first windows opens after ~500ms, in that window the workbench renders after ~2000ms. So far, quite normal behaviour. 

<img width="632" alt="Screenshot 2020-06-08 at 08 59 50" src="https://user-images.githubusercontent.com/1794099/84001228-7a30d380-a966-11ea-913b-dc6ade387992.png">


<img width="540" alt="Screenshot 2020-06-08 at 09 00 04" src="https://user-images.githubusercontent.com/1794099/84001216-756c1f80-a966-11ea-96c5-7fd3c3acf5fb.png">

Please attach the reading from "F1 > Startup Performance"

**Comment by belotn** [comment]
Sorry for the delay.

When doing F1 > Startup Performance , document is stuck on "Loading..."
