### ISSUE TITLE
Panel focus lost after selecting a command using the mouse

### ISSUE THREAD

**Issue by Tazaf** [microsoft/vscode#99436]
Issue Type: <b>Bug</b>

There's a inconsistant behavior regarding panel focus and the command palette. When an item in the command palette is selected using the mouse, the previous focus on a panel is lost, which is not the case when selecting an item using the keyboard.

(0. Open a JS document, for the steps 3 and 7)
1. Click on a panel (like the Timeline panel) so it gets the focus (blue outline)
2. Hit `Ctrl+Shift+P` to open up the Command Palette
3. Click on any command (i.e. `Format Document`) using **the mouse**
4. See how the Timeline panel is not focused anymore
5. Click on the Timeline panel again so it regains focus
6. Open up the Command Palette again
7. Select the `Format Document` command using **the keyboard** and validate with the `Enter` key
8. See how the Timeline panel automatically gets the focus back

Here's a screen record of the steps:
![ezgif-2-88621bee1b58](https://user-images.githubusercontent.com/7702322/83859691-93dfda00-a71e-11ea-93ad-79cb8fc6fd45.gif)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (4.31GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by lambainsaan** [comment]
@chrmarti This looks straightforward to me, I can work on this. 🙂

**Comment by chrmarti** [comment]
@lambainsaan Great, looking forward to your PR!

**Comment by TylerLeonhardt** [comment]
/duplicate #114590

I know this is older but that one has more context and this one will be linked to that one.
