### ISSUE TITLE
Editing arguments in suggested functions don't seem to work right when coding in Dart

### ISSUE THREAD

**Issue by chrisnorman7** [microsoft/vscode#99435]
- VSCode Version: Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
- OS Version: Windows 10 Home Version 1903 (OS Build 18362.836)

Steps to Reproduce:

- Create a new file.
- Save it with a .dart extension.
- 4. Type the following code:

```
void main() {
  final String s = 'Hello world';
  print(s.repl
```
- Now you should get suggestions. If you don't, press Control space.
- Select one of the replace* functions.
- You should have the first argument selected (from).
- Type a string (or use a variable that you created), and press comma (x).
- I'm told this should move my selection to the next argument (replace in this case).
- In my case, it just keeps inserting before the first comma.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
I am guessing this has to do with suggestions and comma being an accepting character.

**Comment by jrieken** [comment]
> Type a string (or use a variable that you created), and press comma (x).

This happens with or without further suggestions showing? E.g you just type `"foo"` and comma or does a list of suggestions show while typing?

> I'm told this should move my selection to the next argument (replace in this case).

So, the replace suggestion inserted something like this `replace(from, replace)` where both arguments are rendered as placeholders, right? Did you try pressing `tab` and `shift+tab` to move back and forth the placeholders?

**Comment by chrisnorman7** [comment]
Ah, sorry, didn't think to try tab. Now it works, with or without control m.

Thanks so much.
