### ISSUE TITLE
[css] Variable proposals in CSS are not shown or are not showing correct variables

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#9944]
- VSCode Version: 1.4.0 (4656fe3ff2952e9538d81e7a7571674352e5d62f)
- OS Version: OSX

Steps to Reproduce:

- Create a CSS file with following data
``` css
a {
  color:  
}

:root {
  --bg-color: red;
}
```
- after `color:` use intelli-sense

Expected: Variable --bg-color is part of suggestions
Observed: Variable is not part of suggestions

Also

- Move the `:root` selector to above rule `a`
- Now, variable is part of the suggestions
- Change the variable name to `--main-bg-color`

Expected: New variable name should be shown in suggestions
Observed: Old variable name is shown in suggestions

**Comment by sandy081** [comment]
Second scenario where variable name was not updated is a regression.

**Comment by aeschli** [comment]
Oh, we hold on the symbol table, that's a must fix:
Fixed with Microsoft/vscode-css-languageservice@754687c8ad87cc8bee385e1c17d6f66202c72e19

**Comment by aeschli** [comment]
Delivered a fix for the second issue (showing old variable name) for July.

**Comment by aeschli** [comment]
Fixed by Microsoft/vscode-css-languageservice@ae68f5112b2c4f3fe2144cf94efc202978e6ee47
