### ISSUE TITLE
Cannot stop long running queries

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#99445]
Testing https://github.com/microsoft/vscode/issues/98821

![recording (3)](https://user-images.githubusercontent.com/2193314/83551390-24b77b00-a4bd-11ea-8e23-bc1e9db9469d.gif)

**Comment by lramos15** [comment]
I believe this is the same issue https://github.com/microsoft/vscode/issues/99128 and should be fixed as I can no longer repo this.
