### ISSUE TITLE
Copy All from debug console removes all empty lines

### ISSUE THREAD

**Issue by Maaartinus** [microsoft/vscode#99441]
Issue Type: <b>Bug</b>

1. Fill the debug console somehow so it contains empty lines. I did it while starting developing a new extension with console.log('whatever\n\n\n').
2. Switch to the debug console and use Copy All.

It gets copied nearly correctly, but all empty lines are gone (This makes it pretty unreadable and hard to process with scripts). This doesn't happen when copying from other applications or other vscode views.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.3.0-53-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.22GB (19.54GB free)|
|Process Argv|--disable-extensions absimporter.code-workspace --no-sandbox|
|Screen Reader|no|
|VM|67%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled

**Comment by isidorn** [comment]
We accept a PR which fixes this.
Code pointer https://github.com/microsoft/vscode/blob/af3d37848c49e763416cf927dcaf65ff3091cfd7/src/vs/workbench/contrib/debug/browser/repl.ts#L746

**Comment by Maaartinus** [comment]
Now, I copied the data and there are empty lines! In case, you can't reproduce it, feel free to close. I'll come back when it happens again (it bothered me for a few days before I filed the issue!).

**Comment by isidorn** [comment]
Ok, let me close it. And if you have steps to repro let me know and we can reopen. Thanks
