### ISSUE TITLE
Notification menus are broken

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#99448]
![recording (18)](https://user-images.githubusercontent.com/22350/83877587-11b1de80-a73b-11ea-94e8-8623c08aa9f7.gif)

**Comment by bpasero** [comment]
Reproduces in an insiders build from 3 days ago.

**Comment by sbatten** [comment]
\closedWith f8577ad1b6d8b5ed0bd0fade90aec430e0bada1e
