### ISSUE TITLE
Peek references shows other cells

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#99443]
Testing: microsoft/vscode#98821

![recording (7)](https://user-images.githubusercontent.com/2193314/83556345-8f1fe980-a4c4-11ea-9ae4-8ef2f677a6cd.gif)

**Comment by jrieken** [comment]
@Tyriar I don't really know what you are doing or expecting here. Can you at least share the notebook?

**Comment by Tyriar** [comment]
@jrieken the notebook is just those 3 cells, I don't know why gh.github-issues:2:2 and gh.github-issues:3:2 are showing up, they appear to be identifiers for the first markdown and query cell respectively. I can no longer reproduce this though with shift+f12:

![image](https://user-images.githubusercontent.com/2193314/83896514-25445180-a709-11ea-98a8-18c4fab08c10.png)

```
[{"kind":1,"language":"markdown","value":"# Hello world","editable":true},{"kind":2,"language":"github-issues","value":"$repo=repo:xtermjs/xterm.js\r\n$repo milestone:4.7.0 author:@me is:pr\r\n","editable":true},{"kind":2,"language":"github-issues","value":"$repo","editable":true}]
```
