### ISSUE TITLE
ctr+s

### ISSUE THREAD

**Issue by Saidakhrorkhon2000** [microsoft/vscode#99440]
Issue Type: <b>Performance Issue</b>

when saved the file is losing its style

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

**Comment by RussianElmo** [comment]
Is this happening for all types of files? Are there any specific conditions this occurs under?

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please follow template for Bug not Perfomance Issue and provide all details required by template.
Also clear steps to reproduce this behavior.
