### ISSUE TITLE
Conda interpreter recognition affected by conda file path.

### ISSUE THREAD

**Issue by cwenee** [microsoft/vscode#99454]
- VSCode Version: 1.45.1
- OS Version: Windows

Steps to Reproduce:

1. Select an interpreter for a workspace. I selected a Conda environment which it had no trouble recognizing. 
2. Restart VS Code. It doesn't recognize the interpreter anymore because there is a space in one of the folder names.
3. I restart a few more times. It's recognized again.
4. Another time, it isn't recognized anymore. I decide to remove the space because the problem happened again.
4. Restart VS Code. The conda environment is no longer recognized as a 'conda' environment.
5. I chose to create a new conda environment and not use the one first chosen.
6. Restart VS Code. Chose new environment. all good.

Does this issue occur when all extensions are disabled?: I don't know.

**Comment by connor4312** [comment]
\extPython

**Comment by cwenee** [comment]
ok thanks!
