### ISSUE TITLE
Smoketest: Notebook tests fail on Windows

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#99452]
![image](https://user-images.githubusercontent.com/22350/83883479-cd770c00-a743-11ea-90e0-a0a8b05b5b2e.png)

**Comment by roblourens** [comment]
Worked for me yesterday. That error implies that it is not applying `--enable-proposed-api` for the extension, which is weird, I'll try again.

**Comment by roblourens** [comment]
Have made a bunch of changes since then, can't repro
