### ISSUE TITLE
Visual code merge conflicts

### ISSUE THREAD

**Issue by grecdev** [microsoft/vscode#99451]
- VSCode Version: 1.45.1
- OS Version: Windows 10

Steps to Reproduce:

1. When i want to merge branches with: git merge branch_name it doesn't show the incoming changes

Does this issue occur when all extensions are disabled?: Yes/No

Like in this example:

I merge my branches everything works exactly as it should, but my visual code doesn't display the conflicts UI like in this image.

[![Visual code conflicts compare][2]][2]

But when i merge with git bash it shows the following message, but still no visual code conflicts UI.

[![Git bash merge message][3]][3]

I have codelens enabled. Still don't work.

  [2]: https://i.stack.imgur.com/qJFCt.png
  [3]: https://i.stack.imgur.com/uQTkM.png

**Comment by chrmarti** [comment]
@grecdev Please attach the entire file containing the conflict. We only detect conflicts with the `<<...<<`, `==...==`, `>>...>>` pattern.

**Comment by grecdev** [comment]
i have a single file with a single line, only for tests purposes.

On master branch is:
const test;

On feature branch is:
const feature;

And i checkout to master and merge feature
And doesn't show any conflicts message nothing. It changes directly

**Comment by chrmarti** [comment]
"It changes directly" makes me wonder if that is just a simply application of a change from one branch to the other without an actual conflict.

It definitely sounds like this is independent of VS Code and actually Git's behavior. Is that correct?

**Comment by grecdev** [comment]
Yes when i use visual code git CLI and also when i use the git bash it gives me the same problem.

But when i have a change on remote repo branch and i pull it on the local branch it shows me the actual <<<<<< >>>>>>> message incoming changes etc.

Only when i merge the branches it doesn't show me nothing in the visual code..

**Comment by chrmarti** [comment]
That's expected behavior from what I understand here. Please check the Git documentation.

Closing as this is independent of VS Code.
