### ISSUE TITLE
Terminal is Crashing

### ISSUE THREAD

**Issue by SCharyTHREESIGMA** [microsoft/vscode#99456]
Issue Type: <b>Bug</b>

when i open the terminal it crashes

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
classdiagram-ts|Ale|0.1.32
tsco|alj|1.0.19
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
plantuml|jeb|2.13.12
csharp|ms-|1.22.0
debugger-for-chrome|msj|4.12.8
debugger-for-edge|msj|1.0.14
material-icon-theme|PKi|4.1.0

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Did you change any defaults? Do you see any errors?

**Comment by SCharyTHREESIGMA** [comment]
The terminal process terminated with exit code: 4294901760

**Comment by Tyriar** [comment]
Do you have anti-virus software that could be blocking the terminal? If so try following the instructions in https://code.visualstudio.com/docs/editor/integrated-terminal#_how-do-i-fix-the-errors-connectnamedpipe-failed-windows-error-232-or-terminal-exited-with-code-x-on-windows

/label "needs more info" integrated-terminal
