### ISSUE TITLE
Add a simple mode

### ISSUE THREAD

**Issue by 456wyc** [microsoft/vscode#99463]
Is it possible to add a simple mode that only has base function like browse and edit files. Don’t load too many extensions for ensure it lightweight when we need use it to do some simple things .

**Comment by sanket-bhalerao** [comment]
@456wyc, if you use the command line to launch vscode you will find an option to disable all the extension.
https://code.visualstudio.com/docs/editor/command-line#_working-with-extensions

![image](https://user-images.githubusercontent.com/9264813/84066394-78f1bc00-a9e3-11ea-8fb9-e02980e7f150.png)

is this something similar to what you are looking for?
Note: i am not sure if this disables extensions just for the single launch or disables extension altogether.
