### ISSUE TITLE
Annoying "Do you want to save the changes?" messages.

### ISSUE THREAD

**Issue by spike-spb** [Microsoft/vscode#9946]
- VSCode Version:
1.3.1
- OS Version:
Linux (64bit)

Steps to Reproduce:
0. close all editors,
set:
1. "workbench.editor.showTabs": false,
2. { "key": "ctrl+w", "command": "workbench.action.closeEditorsInGroup" }
3. open an existing file 
4. press ctrl+2
5. open it again in the 2-nd editor and make some changes,

6. press ctrl+w.

Before the tabs feature come there were no annoying messages like "Do you want to save the changes..."?

I still have editor 1 with that file opened, I am not closing the file, **just 2nd editor (with one command)**. How to get rid of that message?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/8983
