### ISSUE TITLE
Cannot launch debug target in terminal (timeout) - NodeJS Debugging

### ISSUE THREAD

**Issue by paulsimongb** [microsoft/vscode#99467]
Saw this on issue 22409 and was apparently fixed but I am still getting it.

When starting the debugger in VS Code I get a standard Windows error dialog box with the error 
"Cannot launch debug target in terminal (timeout)"
The dialog box has buttons for Open Launch.JSON or Cancel

 I have the latest version of VS Code 1.45.1. If I click OK it still seems to proceed and the Nodemon  starts up my Server, however, getting this error every time

Relevant bit of launch.json is

`"version": "0.2.0",
    "configurations": [

        {
            "name": "Debug Node",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceFolder}/Server",
            "runtimeExecutable": "nodemon",
            "program": "${workspaceFolder}/Server/js/server.js",
            "restart": true,
            "console":"integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "autoAttachChildProcesses": true,
            "skipFiles": [
              "<node_internals>/**/*.js*/",
              "<node_internals>/**/*..js*/",
              "${workspaceFolder}/Server/node_modules/**/*.js"
            ],
            "smartStep": true,
            "env": { }
    `
Is there a workaround for this, ie something that I can add to launch.json. I already added the "env": {} from another suggestion. 

If not please would you work on a fix for this.

I guess the only oddity in my code is that my Workspace includes both the Client and Server, rather than just having the Server. That is why I need to set the cwd to "${workspaceFolder}/Server". This might perhaps have some bearing on the problem.

**Comment by connor4312** [comment]
Can you try this out with out [new debugger](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly) and let us know if that fixes it for you?

**Comment by paulsimongb** [comment]
Sorry didn't see this - the new debugger has cured it
