### ISSUE TITLE
Same aria alert messages not re-read by screen readers

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#99466]
Currently when we do an `alert` we actually change the content of a hidden live region element.
Screen reader detects this and reads the new content.

However if we want the same alert to be re-read nothing happens.
Maybe we could have two hidden aria elements and change focus on them if there is a same message.

fyi @joanmarie for ideas

**Comment by joanmarie** [comment]
@isidorn: It this the case for all screen readers, or mainly just event-spam-afraid Orca? :)

Also: Is this something I can reproduce locally now?

**Comment by isidorn** [comment]
@joanmarie this is the case for all screen readers
Easy reprot steps:
1. Open Explorer view
2. Click on the new file action
3. In the input type something and delete it, hear alert "A file or folder name must be provided"
4. Repeat step 3, nothing gets read

I will experiment with another hidden element.

**Comment by joanmarie** [comment]
So this seems to be the same issue I mentioned in https://github.com/microsoft/vscode/issues/95961#issuecomment-640704895. If we had a stand-alone test case, that would be helpful.

**Comment by isidorn** [comment]
@joanmarie thanks for looking into it. I will look into a workaround / stand-alone sample.

**Comment by isidorn** [comment]
@joanmarie did a workaround by having alternative containers so if a same message gets set we set on the alternate one so this seems fixed in vscode.
For the standalone, it should look something like this https://jsfiddle.net/Lfk1m4oh/1/ 
Though I did not verify if this works, just sketched it up

**Comment by isidorn** [comment]
Verifier: turn on NVDA on Orca
Explorer > new file > type something then delete it -> make sure the error that a name must be provided is read out
Do this again and make sure the errors is read out.
