### ISSUE TITLE
Modify checkbox text for creating a Start Menu folder

### ISSUE THREAD

**Issue by philringsmuth** [microsoft/vscode#99465]
This checkbox should say "Create Start Menu Folder" and should be checked by default. Check boxes should be used to DO or DON'T, YES or NO something. The way it currently works, a user must say: " YES - Don't do this!"
![startmenu](https://user-images.githubusercontent.com/635043/83901745-dbfffc00-a720-11ea-8992-2515c3d1b67a.png)

- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Install VS Code
2. Observe confusing checkbox

**Comment by joaomoreno** [comment]
While I somewhat agree with the rationale here, I can also see the other side: checkboxes are meant to opt-in to non-default things.

Ultimately since this seems to be the default in Inno Setup, our setup framework, I'll just leave it be. Sorry about that!
