### ISSUE TITLE
Disable line wrap in Visual Studio Code integrated Terminal?

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#99460]
This is something between a question and a future request.

Can I turn off line wrapping in the Visual Studio Code integrated terminal?

There is [already such a question at stackoverflow](https://stackoverflow.com/questions/58542199/disable-line-wrap-in-visual-studio-code-integrated-terminal), but no one answered there

I will be grateful for the information

**Comment by Tyriar** [comment]
No you can't, but you might be after https://github.com/microsoft/vscode/issues/74501
