### ISSUE TITLE
Deduplicate save dialogs when press and hold Cmd+S

### ISSUE THREAD

**Issue by sntpcvan** [microsoft/vscode#99477]
- VSCode Version: 1.45.1
- OS Version: windows 10

Steps to Reproduce:

1. open VS code => File => new file => Type some thing => press ctrl+s for more than 2 seconds
2. Try to close save dialog. It gettting quened proportional with how long we pressed the save.

Does this issue occur when all extensions are disabled?: Yes/No Yes

**Comment by bpasero** [comment]
> It gettting quened proportional with how long we pressed the save.

I do not understand what that means. Does the save dialog appear repeatedly?

**Comment by sntpcvan** [comment]
Yes, save dialog appears repeatedly. Its annoying to close multiple times.
