### ISSUE TITLE
Using Visual Studio Code and kinda hating the IDE, the file menu disappears after every use. I just learned after a 4 hour search on google that the alt key will restore the view of file menu. I use File menu a lot. Wish I could keep it visible always.

### ISSUE THREAD

**Issue by davemillerpublix** [Microsoft/vscode#9947]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 
2.

**Comment by glen-84** [comment]
This issue report is awful. The least that you can do is to fill in the version information. That title is far too long and should be the description.

**Comment by DickvdBrink** [comment]
Press alt.. go to the "view" menu and press "toggle menu bar"
Or press `ctrl+shift+p` and type "toggle menu". 

Maybe next time just put a normal bug report here without the "hating" in the title as this isn't really necessary ;)

**Comment by kieferrm** [comment]
`Toggle Menu Bar` in the command palette switches between a permanent and a auto-hidding menu bar on Windows.

**Comment by davemillerpublix** [comment]
thank you KieFerrm. this is answer I was hoping for. the shaming from the others is kind of touching that they care so much.
