### ISSUE TITLE
Provide reliable uninstall hook

### ISSUE THREAD

**Issue by alberto-bc** [microsoft/vscode#99474]
Problem:
The current [uninstall hook](https://code.visualstudio.com/api/references/extension-manifest#extension-uninstall-hook) only executes on VS Code restart. If the user uninstalls an extension but does not restart VS Code:
- Any extension processes/files will not be cleaned up in the meantime
- There is no mechanism stoping the user from reinstalling the same extension (without restarting VS Code), resulting in potential issues with the extension.

Feature request: Provide an uninstall hook that will execute as soon as the user uninstalls the extension.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/44552
