### ISSUE TITLE
Closing a notebook via its tab destroys active notebook

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#99485]
#99233
![Kapture 2020-06-05 at 12 44 50](https://user-images.githubusercontent.com/8586769/83916637-600ab180-a72a-11ea-848e-26d9e4e696d3.gif)

**Comment by rebornix** [comment]
It was fixed already master by https://github.com/microsoft/vscode/commit/96ce46b217fd8615bc93697dad804321d56e99a4
