### ISSUE TITLE
rendering mess when flipping between loading notebooks

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#99482]
Open two notebooks (github issues). Reload. Flip between the tabs as the extension is loading. See (there should be two empty cells):

![image](https://user-images.githubusercontent.com/8586769/83915765-bd056800-a728-11ea-841c-68a8f4968add.png)

**Comment by rebornix** [comment]
\closedWith 5222c24da0beebd5635618bdca97a3080f639b91
