### ISSUE TITLE
[Live Share] UriHandler (handleUri) isn't called when VS Code is opened as Admin

### ISSUE THREAD

**Issue by jramsay** [microsoft/vscode#99483]
Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Install Live Share
2. Open VS Code as Admin
3. From a browser enter the following:
vscode://ms-vsliveshare.vsliveshare/signin

Additional notes:
 On activation Live Share registers a VSLS Protocol Handler
 ExtensionUtil.context.subscriptions.push(window.registerUriHandler(new VSLSProtocolHandler(telemetryEvent)));

When VS Code is opened as an admin I'm not seeing this prompt:
![image](https://user-images.githubusercontent.com/8161247/83914975-3439fc80-a727-11ea-85e9-fce3b0ed302f.png)

I can repro the same behavior in another extension (Visual Studio Codepaces) that uses a UriHandler to sign in.

**Comment by bpasero** [comment]
Quite possibly a limitation in Electron or in general that protocol links are not triggered if the target is running with a different user than the source.

**Comment by deepak1556** [comment]
This is as designed in the runtime, the protocol registration are set under current user https://github.com/electron/electron/blob/08a51f333902247be7ee7528f2192e3bf4c2c045/shell/browser/browser_win.cc#L428-L440
