### ISSUE TITLE
Random rewriting of code on saving

### ISSUE THREAD

**Issue by jkhoogland** [microsoft/vscode#99493]
- VSCode Version:  1.45.1
- OS: Darwin x64 19.3.0

Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0

Steps to Reproduce:

It is very hard to provide a recipe to reproduce.

When editing a file, since about two month (202004), at random times, on saving the code will be messed in a random fashion. It seems to correlate with having some code selected. But as said, it is very hard to pin down when it happens. It is very bizarre and scary.

Does this issue occur when all extensions are disabled?: Yes/No

It looks like that after trying for one hour with all extensions disabled I do not see the issue.
However given that this is happening at random times, it is not 100% clear if it is due to an extension. I will further try to look for how to reproduce.

The extensions I have installed at the moment:

```
cheshirekow.cmake-format
cschlosser.doxdocgen
DavidAnson.vscode-markdownlint
eamodio.gitlens
James-Yu.latex-workshop
mhutchie.git-graph
mitaki28.vscode-clang
ms-dotnettools.csharp
ms-python.anaconda-extension-pack
ms-python.python
ms-vscode.cmake-tools
ms-vscode.cpptools
quicktype.quicktype
redhat.vscode-xml
redhat.vscode-yaml
smockle.xcode-default-theme
VisualStudioExptTeam.vscodeintellicode
```

**Comment by connor4312** [comment]
Yes, this is very likely due to an extension running an action, such as formatting, on save.
