### ISSUE TITLE
Option to clear debug console suggestions

### ISSUE THREAD

**Issue by jakelevi1996** [microsoft/vscode#99494]
I'd like there to be an option to clear debug console suggestions. For me, clearing the debug console history does not clear the debug console suggestions. I have tried setting `debug.console.historySuggestions` to `false` in `settings.json`, but it's not quite what I'm looking for: I still want to have suggestions in the debug console, I just want to clear all of the existing ones. For me, I can't make this history suggestions go away, either by reloading the window, or by closing and reopening VSCode entirely.

I'm using a Windows 10 64-bit computer. My VSCode "about" details are as follows:

Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by isidorn** [comment]
Let me get this precise: you want the debug console history suggestions to be dropped on vscode reload / restart?
I think this is a fair feature request

**Comment by jakelevi1996** [comment]
Hi @isidorn , thank you for looking into this. To be more precise, ideally I'd like there to be either a button or a VSCode command (that can be bound to a keyboard shortcut), so that when the debug console history gets too long/annoying, I can use that button/command to clear the suggestion history (without having to reload/restart VSCode)

**Comment by jakelevi1996** [comment]
(sorry I think I must have pressed the "Close and comment" button by mistake instead of "comment")

**Comment by isidorn** [comment]
Thanks for clarifying.

**Comment by michael140711** [comment]
wanna follow up on this. I see all the debug console suggesstion history is in state.vscdb file. If there is a way to clear only the history I don't see why this would be out-of-scope of VS Code. 

For others searching to solve this issue, it is in the file 'state.vscdb' at line debug.repl.history. File located at Appdata/Roaming/Code/User
