### ISSUE TITLE
Lacking a right-click context menu for .ipynb editing

### ISSUE THREAD

**Issue by rbtyod** [microsoft/vscode#99497]
Issue Type: <b>Feature Request</b>

Lack of a right-click context menu for .ipynb editing for at least cut, copy and paste is annoying and makes editing inefficient.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

**Comment by connor4312** [comment]
\extPython
