### ISSUE TITLE
Data Viewer for arrays in .ipynb does notwork

### ISSUE THREAD

**Issue by rbtyod** [microsoft/vscode#99498]
Issue Type: <b>Bug</b>

Data Viewer tab appears but no data is shown.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (18.15GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.1.35
kite|kit|0.114.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.5.80290
remote-wsl|ms-|0.44.2
vscode-yaml|red|0.8.0
vscodeintellicode|Vis|1.2.7
markdown-all-in-one|yzh|3.0.0

</details>

**Comment by connor4312** [comment]
\extPython
