### ISSUE TITLE
Long running custom editor backups can make editor uncloseable

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#99495]
![image](https://user-images.githubusercontent.com/8586769/83929213-72dfaf00-a747-11ea-975a-d05c387dc415.png)

I managed to get myself into a sate where I can't close the editor with this `backup` in pawdraw:
```ts
	async backup(destination: vscode.Uri, token: vscode.CancellationToken): Promise<vscode.CustomDocumentBackup> {
		let done = false;

		token.onCancellationRequested(() => {
			if (!done) {
				console.log('we abortin!');
			} else {
				console.log('posthumously cancelled');
			}
			done = true;
		});

		await new Promise(resolve => setTimeout(resolve, 5000));
		await this.saveAs(destination, token);

		return {
			id: destination.toString(),
			delete: async () => {
				try {
					await vscode.workspace.fs.delete(destination);
				} catch {
					// noop
				}
			}
		};
	}
```

Nothing was shown modified in git, but one time when I opened the .pdraw file again and saved it allowed me to close. Other times I've been totally unable to exit code without a force-quit.

_Originally posted by @JacksonKearl in https://github.com/microsoft/vscode/issues/91680#issuecomment-639888224_

**Comment by bpasero** [comment]
I would argue this is "as designed". You will have to manually revert or save each dirty editor on shutdown if backups take long or fail.

**Comment by JacksonKearl** [comment]
The editor was already closed, see I only have the single untitled editor open but I'm still unable to close. I had to re-open the file, then save it, then close.

**Comment by bpasero** [comment]
Exact steps? Does this reproduce out of sources with latest?

**Comment by JacksonKearl** [comment]
No longer able to reproduce. 

cc @mjbvz the backup for paw draw seems to not work anymore, I packaged from latest sources and running it I see that on restore from backup we get [here](https://github.com/microsoft/vscode-extension-samples/blob/8d079734512d8e81e23c7ac7c7242aa0054f8847/custom-editor-sample/src/pawDrawEditor.ts#L32) with the proper backup ID and file contents, but then the actual editor is blank. Not sure where the backup gets lost.
