### ISSUE TITLE
Trigger (full) completions when (incomplete) completions are already active

### ISSUE THREAD

**Issue by edzkite** [microsoft/vscode#99504]
- VSCode Version: 1.45.1
- OS Version: macOS 10.15.1

I'm part of the team that builds the Kite extension. Via https://github.com/microsoft/vscode/issues/11935, our understanding is that if we specify special triggers, IntelliSense will not wait for all providers to complete.

However, we're seeing instances where after a special character is typed, the subsequent alphabetical character does not return completions from IntelliSense anymore, even though we set`isIncomplete` to true, expecting the completions list to refresh on every keystroke.

For our extension, we've defined "," and "space" as triggers in the first example. Notice how only our completions appear after typing `e` for `err` initially.

![special](https://user-images.githubusercontent.com/47993402/83933956-eee6f080-a761-11ea-8723-22b22f92b61d.gif)

With the triggers removed, now suggestions for `e` from IntelliSense appear immediately.

![no_special](https://user-images.githubusercontent.com/47993402/83933959-f3130e00-a761-11ea-9aad-26390ee6329f.gif)

Does this issue occur when all extensions are disabled?: No

**Comment by jrieken** [comment]
> our understanding is that if we specify special triggers, IntelliSense will not wait for all providers to complete.

IntelliSense always waits for all applicable providers, so when multiple provider have registered for a certain character they will be called. Tho, I assume in your case that's not happening. 

The simplest way to know what providers are being called, e.g when subsequent typing is happening is this: "F1 > Log Level > Trace" and then "F1 > Show Log > Extension Host". This will print all providers and their extensions that are being invoked. That should give you an idea what's happening

**Comment by edzkite** [comment]
It appears that both providers are being hit, even though the golang provider doesn't show completions where I'd expect it to.
```
[2020-06-15 10:02:26.098] [exthost] [trace] [kiteco.kite] provider DONE after 204ms
[2020-06-15 10:02:26.139] [exthost] [trace] [golang.Go] INVOKE provider 'e'
[2020-06-15 10:02:26.139] [exthost] [trace] [golang.Go] INVOKE provider 'e'
[2020-06-15 10:02:26.140] [exthost] [trace] [vscode.merge-conflict] INVOKE provider 'e'
[2020-06-15 10:02:26.140] [exthost] [trace] [golang.Go] INVOKE provider 'e'
[2020-06-15 10:02:26.140] [exthost] [trace] [golang.Go] provider DONE after 1ms
[2020-06-15 10:02:26.140] [exthost] [trace] [golang.Go] provider DONE after 1ms
[2020-06-15 10:02:26.140] [exthost] [trace] [golang.Go] provider DONE after 0ms
[2020-06-15 10:02:26.142] [exthost] [trace] [vscode.merge-conflict] provider DONE after 1ms
[2020-06-15 10:02:26.240] [exthost] [trace] [golang.Go] INVOKE provider 'v'
[2020-06-15 10:02:26.252] [exthost] [trace] [golang.Go] provider DONE after 12ms
```

**Comment by jrieken** [comment]
To know more about each completion you can do this: Trigger suggest, show suggest details (the secondary suggest widget), hit cmd+? to see where each completion comes from

**Comment by edzkite** [comment]
What does the secondary suggest widget look like, and how can I toggle it on?

**Comment by jrieken** [comment]
The default keybinding is Ctrl+Space while completions show. That toggles the details widget. Then hit cmd+? for explain mode. This is how it should look: 
<img width="683" alt="image" src="https://user-images.githubusercontent.com/1794099/84739954-d1f5bd00-afac-11ea-9fba-b7b378e50f39.png">

**Comment by edzkite** [comment]
Thanks @jrieken!

<img width="670" alt="Screen Shot 2020-06-16 at 1 59 57 PM" src="https://user-images.githubusercontent.com/47993402/84827720-bc4abc80-afd9-11ea-9d45-e94bee3dbb6a.png">

This is my first pass. I then backspace and re-type "n":

<img width="663" alt="Screen Shot 2020-06-16 at 2 00 13 PM" src="https://user-images.githubusercontent.com/47993402/84827761-ca98d880-afd9-11ea-9902-26d4ef79a919.png">

The two Kite completions at the top have the same metadata across both instances.

**Comment by jrieken** [comment]
> This is my first pass. I then backspace and re-type "n":

That makes sense. When you hit backspace we cancel the suggest session and re-typing "n" will trigger quick suggestions because it's a word character. What we don't do is to re-start completions when "n" is typed for the first time because completions is already active. That's a little weird but I also doubt it's a common case

**Comment by edzkite** [comment]
If I understand correctly, this means that since we've shown completions for space, and the completions list is active when I type `n`, quick suggestions are not requested.

In that case:

1. How does this differ to situations where the completions list is able to refresh itself? When `isIncomplete` is toggled to true?
2. Is it possible to get the behavior of (1) in this case?
3. Alternatively, can we "cancel" the current list on the next keystroke if we show completions for these special characters?

**Comment by jrieken** [comment]
> How does this differ to situations where the completions list is able to refresh itself? When isIncomplete is toggled to true?

We always assume that there are multiple providers and when `inComplete: true` is used only those providers that marks their completion list as incomplete are re-queried, results from other providers are merged in.

> Is it possible to get the behavior of (1) in this case, and how involved would the code change be?

No sure what you mean

> Alternatively, can we "cancel" the current list on the next keystroke if we show completions for these special characters?

Your provider can always return something "falsy", like `undefined` or `[]`, which can then cancel the suggest session (assuming there are no other completions)

**Comment by edzkite** [comment]
Got it, thanks!

The desired behavior is for our extension to be able to provide suggestions on custom characters such as `space`, but not block other providers from being queried on the next keystroke, which is what's happening now.

This seems like it'd be hard to implement without modifying the source of VSCode itself. (Though it'd be great if we could via the extensions API!)

For instance:
> Your provider can always return something "falsy", like undefined or [], which can then cancel the suggest session (assuming there are no other completions)

Say we surfaced completions on `space`. Then on the next keystroke we return "falsy". Wouldn't this mean we would suppress our own completions for the next keystroke in favor of other providers? I'm not quite sure if that's desirable solution.

**Comment by edzkite** [comment]
Hey! Just wanted to follow up on this. I'd love to learn more about the bug / issue itself, and would even be open to contributing a fix?

**Comment by jrieken** [comment]
I have pushed a change that makes us re-trigger completions when entering a new word while it is active. In the following capture there is a provider that returns `Z aaa Eeee`, `Z bbb Aaaa` etc. and one provider that returns `aaa`, `bbb`, etc.  Completions are requested two times (for both providers): (1) when typing `Z` (new word) and when typing `a` (new word)

![Aug-11-2020 12-17-01](https://user-images.githubusercontent.com/1794099/89886467-f21cb380-dbcc-11ea-95a5-62751f4ee1b2.gif)

**Comment by jrieken** [comment]
@edzkite This should be in next 1.49 insiders which should appear end of this week
