### ISSUE TITLE
Security: VS Code can access System Root on macOS

### ISSUE THREAD

**Issue by F1LT3R** [microsoft/vscode#99506]
- VSCode Version: Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (3 wks ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
- OS Version: 10.15.4

Steps to Reproduce:

1. Install VS Code
2. Create a file `test.js`
3. Trigger path intellisense with `import foo from './`
4. You will notice that VS Code can access the system root directory. (see image)

<img width="790" alt="CleanShot 2020-06-05 at 22 35 04@2x" src="https://user-images.githubusercontent.com/1218446/83934199-d6380400-a77c-11ea-8213-fe859eceb562.png">

Does this mean **all extensions also have access the system root directory**?

Does this issue occur when all extensions are disabled?: Yes

**Comment by joffarex** [comment]
Similar thing is happening on Windows as well. I can access all files what I have on my C drive (Tho, i am not sure if it can access other drives too, as i only have one)

![image](https://user-images.githubusercontent.com/41587092/83940500-a416b880-a7f5-11ea-93ba-01d41277e2bc.png)

![image](https://user-images.githubusercontent.com/41587092/83940509-b8f34c00-a7f5-11ea-8ddf-a007df21dd3c.png)

**Comment by F1LT3R** [comment]
Interesting to see this on Windows too @joffarex .

I'm not a security expert, but my concern is... 

If any VS Code extension can have access to your system root directory, or anywhere else for that matter, then use of VS Code extensions should receive the same security review treatment that other software and packages do.

I'm assuming, perhaps incorrectly, that VS Code is running some kind of Node.js install process behind the scenes. If so, where are the security messages we normally see when installing Node packages?

Ideally these would be bubbled up to the user.

**Comment by greggman** [comment]
confused. How is this different than every scriptable text editor in existence? emacs, vi, sublime, notepad++, visual studio, xcode, etc....

**Comment by mjbvz** [comment]
This is not a security issue, it is the equivalent of running `ls /`. 

In your example, you have not opened any workspace so we assume that absolute imports start at the root of your drive. The fix is to open a workspace/folder, in which case  absolute imports will instead start at the folder instead

**Comment by hdahlheim** [comment]
@mjbvz this happens in workspaces/folders as well, but I think only in javascript/typescript files. The path completion for the `src` attribute of an HTML img tag, for example, starts at the root of the folder. Creating a jsconfig.json with a baseURL does not prevent this behavior.

![grafik](https://user-images.githubusercontent.com/16597280/86498639-f7ddd880-bd86-11ea-9353-43b8852446ed.png)

**Comment by F1LT3R** [comment]
> This is not a security issue, it is the equivalent of running `ls /`.
> 
> In your example, you have not opened any workspace so we assume that absolute imports start at the root of the drive. The fix is to open a workspace/folder, in which case absolute imports will instead start at that folder instead

This happens in workspaces too.

**Comment by F1LT3R** [comment]
@mjbvz the important question is, can third party VS Code extension code read from root by default?
