### ISSUE TITLE
Drag n drop of file into explorer not working

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#9950]
1. Linux, vscode - latest insiders
2. Drop a file into explorer
3. File does not get copied over

If I drag the file over to the editor it is nicely opened. Dragging a folder also works.

I also verified and this all works on OS X, I just can not seem to get it to work on linux.

**Comment by bpasero** [comment]
I can reproduce sometimes and it smells awfully like https://github.com/Microsoft/vscode/issues/7948
