### ISSUE TITLE
file search with `files to include` option for workspace names with slash included

### ISSUE THREAD

**Issue by hoonoh** [microsoft/vscode#99512]
With workspace named with slash included (e.g. workspaces from monorepo) trying to search with `files to include` option fails to resolve paths for the workspace. 
I think the path should be either resolved or there should be restrictions with workspace naming..

- VSCode Version: 1.45.1 (user setup)
- OS Version: Windows_NT x64 10.0.19640

Steps to Reproduce:

1. with workspaces with names including slash as:
#### temp.code-workspace
```json
{
  "folders": [
    {
      "name": "@monorepo_root",
      "path": "."
    },
    {
      "name": "@services/api",
      "path": "services/api"
    },
    {
      "name": "@modules/common",
      "path": "modules/common"
    }
  ]
}
```
2. when trying to search files from `@services/api`, as described in [docs](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_search)
![image](https://user-images.githubusercontent.com/2078254/83939925-a0962800-a81b-11ea-828d-c92818ab5938.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Try omitting the @ character. AFAIK the `name` property in your code-workspace file only affects how that root folder displays in the tree.

**Comment by tabaddor** [comment]
> The logic [here](https://github.com/microsoft/vscode/blob/a8c48bbacee3cb073a20611fca38bb4b46f7703a/src/vs/workbench/contrib/search/common/queryBuilder.ts#L368-L384) doesn't allow for folder names that contain / or \

I can look into this, but does this mean what the issue author documented above is expected behavior?

**Comment by roblourens** [comment]
If you have workspace folders `foo` and `foo/bar`, and `foo` as a child folder `bar`, then I don't know how you distinguish between the two possible `./foo/bar`, it feels like the `\` in a workspace folder name should have to be escaped. I feel like we would have disallowed `/` in a workspace folder name if we had thought of it :)

Feel free to look into it but I don't want to commit to a particular solution up front without more discussion
