### ISSUE TITLE
Indenting and shortcut key for folded code blocks

### ISSUE THREAD

**Issue by huytrvan** [microsoft/vscode#99511]
Hello everyone, 

I want to suggest two new features for VSCode:

1/ 'Indentable' folded code block where pressing `tab` and the entire block moves.
2/ Have a shortcut key where we can fold/unfold any code block which we designated previously.

Please let me know if I'm missing something. Thanks!

**Comment by aeschli** [comment]
Please only one request per issue.
1. You can already select a range and press tag to indent. That also works for a folded block, if you select it from the first line to the next visibuile line. Can you explain what's the difference with your proposal?
2. How do you designate the block?

**Comment by huytrvan** [comment]
@aeschli Thanks for answering.

1. What I meant is that if a user selects the first line of any folded block and press `tab`, the whole 'children' code should be indented as well (instead of just that line is indented).
2. Here I meant that if a user folds a block, vscode will automatically store the position where that user wants to fold, so when he/she selects any 'children' line and press a shortcut key, the whole block will be closed (instead of pressing on `glyphMargin`). 

PS: I apologize if it's confusing in any way. Now that I think again, this feature request is maybe a bit impractical :). Please let me know.
