### ISSUE TITLE
Kinda Buggy Extension Manager

### ISSUE THREAD

**Issue by konqui** [Microsoft/vscode#9951]
- VSCode Version: 1.3.1
- OS Version: Windows 7

The New Grafical Extension Manager works great and looks great.
But there is a big downside. It uses the same Panel and even worse the same Panel width as the other Tools like Search, Debugger, Filebrowser and Git Manager.

It would be better if one could set the panel width per Tool or just a different one for the Extension Manager

Or another way i could think of would be if one could chose to open the Extension Manager in a separate Window instead.

**Comment by joaomoreno** [comment]
Thanks for your feedback. This won't likely change soon.
