### ISSUE TITLE
Cannot enable extension

### ISSUE THREAD

**Issue by szalik-m** [microsoft/vscode#99516]
Issue Type: <b>Bug</b>

* I use platformio IDE, everything works well until the moment when C/C++ extension is automatically disabled. (Platformio depends on C/C++)
* It happens at irregular intervals (once per 1-4 weeks).
* The only fix is to reinstall C/C++ extension, but it's an annoying solution
* Why is C/C++ extenstion disabled, and I have no option to enable it?

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.2
extlibraries|dan|0.0.3
apacheconf-snippets|eim|1.3.0
latex-workshop|Jam|8.10.0
csharpfixformat|Leo|0.0.84
vscode-apache|mrm|1.2.0
csharp|ms-|1.22.0
mssql|ms-|1.9.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.5.80290
cpptools|ms-|0.28.2
platformio-ide|pla|1.10.0
vscode-yaml|red|0.8.0

</details>

**Comment by gjsjohnmurray** [comment]
Any reason you haven't updated your VS Code to the current release, 1.45.1?

**Comment by szalik-m** [comment]
Ok, not updated vscode was the problem, thanx:)
