### ISSUE TITLE
Extension view (panel on the left) not showing enabled extension 

### ISSUE THREAD

**Issue by jinnn0** [microsoft/vscode#99518]
- VSCode Version: 1.45.1
- OS Version: 10.15.4

Steps to Reproduce:

I installed a VSC in other desktop and by using Settings Sync extension I was able to bring all of the configurations and extensions I was using in the other computer. However, for some reason I do not see the "Enabled" folder in the extension panel. There are only "Popular" and "Recommended". When I click on the three dot, yeah I can see all the installed and enabled extensions but it has to use @enabled in the search bar. From reading through the official VSC docs, by default it has to show the enabled folder in the extension panel but, I just don't see it. What's the problem ?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
/causedByExtension

FYI, native support for synchronization is already available in Insiders, and will turn up in the standard VS Code soon. See https://code.visualstudio.com/updates/v1_45#_settings-sync
