### ISSUE TITLE
JS extension is recognized as swift by VS Code 

### ISSUE THREAD

**Issue by omkarbhosekar** [microsoft/vscode#99514]
Issue Type: <b>Bug</b>

Visual Studio Code recognises JS as Swift language and also set the syntax of swift. The icon of language is set to swift if a file is given an extension of .js . Even after installing VS code again,
the error still remains the same.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.2.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.36.0
jshint|dba|0.10.21
vscode-eslint|dba|2.1.5
vscode-npm-source|dku|1.0.0
jupyter|don|1.1.5
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.0.0
vscode-firefox-debug|fir|2.8.0
code-runner|for|0.10.0
beautify|Hoo|1.5.0
rainbow-end|jdu|0.7.7
language-julia|jul|0.15.40
vscode-codemetrics|kis|1.24.0
kite|kit|0.114.0
identical-sublime-monokai-csharp-theme-colorizer|max|0.11.1
rainbow-csv|mec|1.7.0
python|ms-|2020.5.78807
azure-account|ms-|0.8.11
sublime-keybindings|ms-|4.0.7
vsliveshare|ms-|1.0.2169
debugger-for-chrome|msj|4.12.8
sqltools|mtx|0.22.5
vscode-for-node-js-development-pack|nod|2.0.1
es6-css-minify|olb|3.3.2
vscode-css-peek|pra|3.0.2
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.7
vscode-icons|vsc|10.1.1
wallaby-vscode|Wal|1.0.199
vscode-import-cost|wix|2.12.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/62636304/83941834-2316eb80-a80c-11ea-979e-38cc331bbb58.png)

**Comment by gjsjohnmurray** [comment]
This is being done by one of your extensions. If you don't want it to happen, disable or remove the extension, or raise the issue with the extension author.

/causedByExtension

**Comment by omkarbhosekar** [comment]
Thanks
