### ISSUE TITLE
[JSON] Support textDocument/formatting capability

### ISSUE THREAD

**Issue by jfcherng** [microsoft/vscode#99513]
[The JSON language server](https://github.com/vscode-langservers/vscode-json-languageserver) supports `textDocument/rangeFormatting`, but it doesn't seem to support `textDocument/formatting`. 

I assume `textDocument/formatting` is just `textDocument/rangeFormatting` with a range across the whole file. Is this correct? If yes, is `textDocument/formatting` just not done or there are other concerns?

**Comment by aeschli** [comment]
For vscode, providing `textDocument/rangeFormatting` is enough. It also covers formatting of the full document. So no need to also provide `textDocument/formatting`
