### ISSUE TITLE
Image Error

### ISSUE THREAD

**Issue by ahmednaeem786** [microsoft/vscode#99522]
Issue Type: <b>Bug</b>

When Loading Image In Visual Studio code explorer it gives a error as followed:
An error occurred while loading the image.

Open file using VS Code's standard text/binary editor?

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 6.0.6002

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz (4 x 2693)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|3.88GB (1.87GB free)|
|Process Argv|--disable-gpu|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
prettier-vscode|esb|5.0.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
auto-rename-tag|for|0.1.3
vscode-css-peek|pra|3.0.2
LiveServer|rit|5.6.1

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by mjbvz** [comment]
@ahmednaeem786 Were you also opening an image that `%` in the path? 

Still see this in VS Code 1.46?
