### ISSUE TITLE
Make sure GITHUB_TOKEN is only used for GitHub URL

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#9952]
1.4.0-insiders

vscode-extension-vscode/lib/shared.ts sets the Auth header for all URLs when GITHUB_TOKEN is set, should only be set for GitHub's URLs to avoid passing it to other parties.

(Found verifying #8834.)

**Comment by maxandersen** [comment]
this won't fix #8834 imo since afaik the issue was found while accessing github urls. My github token don't have access to vscode repos thus I got denied rather than enabled to download.

**Comment by chrmarti** [comment]
@maxandersen I agree, this is meant as a general issue, not specific to your problem.

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode-extension-vscode/commit/0c0cfc4a4cc1912dbf36a31d8886189d8a62e281

@chrmarti please report issues for the VSCode module in https://github.com/Microsoft/vscode-extension-vscode
