### ISSUE TITLE
Debugged node process in integrated/external terminal has exit code 1

### ISSUE THREAD

**Issue by jeffrson** [microsoft/vscode#99529]
- VSCode Version: 1.45.1
- OS Version: Windows 10

Steps to Reproduce:

Use this launch.json:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Debug Launch",
            "program": "${workspaceFolder}/index.js",
            "console": "integratedTerminal",
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Debug Start",
            "runtimeArgs": ["--inspect-brk=9229", "index.js"],
            "runtimeExecutable": "node",
            "port": 9229,
            "console": "integratedTerminal"
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Debug Attach",
            "port": 9229
        }
    ]
}
```
and any simple index.js like
```
console.log("Hi")
```

1. Start debugging (F5) configuration "Debug Launch" and/or "Debug Start"
2. Check errorlevel in terminal: echo %errorlevel%
=> 1

3. Run without debugging (Ctrl-F5) configuration "Debug Launch"
4. Check errorlevel in terminal: echo %errorlevel%
=> 0

5. Run without debugging (Ctrl-F5) configuration "Debug Start"
6. Start debugging (F5) configuration "Debug attach"
7. Finish program and check errorlevel: echo %errorlevel%
=> 0

The bug has implications when node is run via npm script (https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-support-for-npm-and-other-tools) because npm always reports an error for the debugged process (it expects it to exit with 0).

There's apparently no such problem when run inside the internalConsole.

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
Can you give our [new debugger](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly) a shot and let us know if you have a problem there?

**Comment by jeffrson** [comment]
Tried it and this nightly does not have the bug - %errorlevel% is always 0 as expected.

**Comment by connor4312** [comment]
Thanks, I'll close this then. The new debugger will become the default in the future 🙂

**Comment by jeffrson** [comment]
Nice - hopefully not too distant future - is there a release plan/ETA?

Although it's a "nightly" - what would you thin - is it usable in daily work?

**Comment by connor4312** [comment]
We have a stable channel as well--which will be default on insiders and installed (but not enabled by default on stable in the upcoming release: https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug
