### ISSUE TITLE
The display of characters to draw a table is misaligned if Chinese characters included

### ISSUE THREAD

**Issue by Fang3s** [microsoft/vscode#99521]
I used the following characters,
```
				┌──────────────┐
				│　　　　　　　│
				│　　汉字啊　　│-----> x
				│　　　　　　　│
				└──────────────┘
				　　　　│
				　　　　y
				+--------------+
				|              |
				|    汉字啊    |
				|              |
				+--------------+
```

it looks good in notepad++.
![image](https://user-images.githubusercontent.com/6383616/83945964-d2c76b80-a7c2-11ea-87dc-778fddd0ab51.png)

But, it doesn't look pretty in VSCode,

![image](https://user-images.githubusercontent.com/6383616/83945961-c6431300-a7c2-11ea-9767-fc4b56657894.png)

CPUs | Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3598)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 15.88GB (8.06GB free)
Process Argv |  
Screen Reader | no
VM | 40%

```
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z (3 wks ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by alexdima** [comment]
This is entirely driven by the font. 

If you want to have wide characters be 2x the width of half-width characters, then please use a font that defines that e.g. Inconsolata.
