### ISSUE TITLE
Needs an updated guideline about how to contribute to translation after MLCP closed

### ISSUE THREAD

**Issue by fireattack** [microsoft/vscode#99538]
The platform for helping translating VS Code into other locales, Microsoft Localization Community Platform (MLCP), had been closed since April ([ref](https://github.com/Microsoft/Localization/wiki)).

After that, there is no clear guideline about how the community can continue their effort to help the translation of VS Code.

For issues reporting, there are people reporting issue here, on https://github.com/Microsoft/Localization, or directly on https://github.com/microsoft/vscode-loc.

For direct contribution, I saw people making PR at https://github.com/microsoft/vscode-loc/pulls. While most of them did get fixed by someone (core dev?) replying "fixed", they don't seem to accept PR and merge them directly, they just fixed it *for you*.

I assume the languages listed as "Core" on https://github.com/microsoft/vscode-loc (instead of "Community") are now no longer community driven, but centralizedlly managed? Which is totally fine, but the guideline needs to be clear and updated. For example, on that very page, it still says "Visual Studio Code translations are done in the Visual Studio Code Project in MLCP" (along with multiple other places) which clearly is outdated.

What makes things more confusing is that commit messages there still say "Merged in Translation from MLCP." merely a few days ago: https://github.com/microsoft/vscode-loc/commit/f59539e4700367186e701981997586cb04ae6c71 - Isn't MLCP closed already? Where did these contributions come from, just backlog? Or is there still a "MLCP" but internally?

Just to make my point more clear: I have no issue of the way VS Code accepts contributions and bug reporting w.r.t. translation/localization. I just think the guidelines need an update about how, after MLCP was closed.

**Comment by yume-chan** [comment]
I notice in the Release Notes for v1.46, instead listing community translators, there is an updated announcement.

> Stay tuned in the upcoming weeks for an announcement on our [Wiki](https://github.com/Microsoft/Localization/wiki) page about the new community platform. You can also visit the [FAQ](https://github.com/Microsoft/Localization/wiki/FAQ) page for answers about this platform transition.

It's almost one month since the release, not sure how many more *upcoming weeks* we need to wait.

**Comment by danyeh** [comment]
Following up on this. Will clean up guidance, release notes etc.

**Comment by danyeh** [comment]
Language pack has been updated. For example, https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-de
vscode-loc repo readme has been updated. 
Release notes is clean.
github localization site will be cleaned up by community team.
