### ISSUE TITLE
Blurry VSCode Window

### ISSUE THREAD

**Issue by Thawne1234** [microsoft/vscode#99534]
Issue Type: <b>Bug</b>

My VsCode window was having crackling spots all over the screen. Even though i have reinstalled tthe vs code again, the screen still has the crackling spots on it. Kindly tell me how to fix this errors.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.44GB (10.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
prettier-vscode|esb|5.0.0
code-runner|for|0.10.0
camelcasenavigation|map|1.1.2
python|ms-|2020.4.74986
cpptools|ms-|0.28.2
vscode-extension-auto-import|Nuc|1.4.3
java|red|0.60.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.22.4
vscode-maven|vsc|0.21.4

</details>

**Comment by kameshkotwani** [comment]
What is the resolution of your screen? can you please capture an image from an external camera and post?

**Comment by connor4312** [comment]
Can you try running code with `code --disable-gpu` and let us know if the problem is resolved?

**Comment by Thawne1234** [comment]
> 
> 
> Can you try running code with `code --disable-gpu` and let us know if the problem is resolved?

**Comment by Thawne1234** [comment]
@connor4312 Thanks for the help. The issue was resolved. Though, instead of disabling the gpu for vscode, i switched the graphics from the dedicated one to integrated one.

**Comment by Thawne1234** [comment]
@kameshkotwani the resolution is 1920x1080. I tried changing the resolution but it didn't help. Anyways the problem was resolved as stated in above comment. The screenshot is attached. Thanks.
![IMG_20200504_014253](https://user-images.githubusercontent.com/62470593/84091570-6cd12300-aa12-11ea-9722-0e4551ee0b10.jpg)
