### ISSUE TITLE
Developer: Startup Performance only loads when connected to network

### ISSUE THREAD

**Issue by RotationMatrix** [microsoft/vscode#99533]
- VS Code version: Code - Insiders 1.46.0-insider (b1ef2bf05f90dd0e6438782411ab84756f97d8f1, 2020-06-05T12:27:56.662Z)
- OS version: Darwin x64 18.7.0

Steps to Reproduce:

1. Disconnect all network connections.
2. Open VSCode.
3. Open "Developer: Startup Performance" from the Command Palette.

Expected result: Startup Performance measurements are displayed.

Actual result: Startup Performance never finishes "Loading...". Error logged in Dev Tools Console.
![image](https://user-images.githubusercontent.com/52428419/83952688-5f484d00-a808-11ea-8dda-b5460022acf2.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Failing requests are from the extension service, not sure if this is intended during the startup metrics collection. Deferring to @sandy081

**Comment by jrieken** [comment]
I don't believe this is specific to the performance editor but must be rooted somewhere lower. The perf editor shows `Loading...` while it [awaits](https://github.com/microsoft/vscode/blob/29b117216229e4cfdd3d95fd4cb83ad4c37529fc/src/vs/workbench/contrib/performance/browser/perfviewEditor.ts#L111-L113) the eventually lifecycle phase and extensions being registered. So, I believe the culprit must be somewhere there

**Comment by sandy081** [comment]
Assigning to @bpasero and @alexdima for lifecycle phase and extensions being registered steps respectively

**Comment by bpasero** [comment]
Running with `--verbose` and checking logs, the `LifecyclePhase.Eventually` is reached:

```
TRACE lifecycle: phase changed (value: 4)
```

There are 2 more things the editor awaits on:
* `this._timerService.whenReady(),`
* `this._extensionService.whenInstalledExtensionsRegistered()`

Maybe Jo could check on the former and Alex on the latter.

**Comment by jrieken** [comment]
The former is again installed extension registered and lifecycle phase awaiting

**Comment by jrieken** [comment]
Good digging. Thanks @bpasero. 

Adding @joaomoreno to decide if the update service should eventually error or return false when asked for latest without internet access

**Comment by joaomoreno** [comment]
I think throwing would make more sense for a service call.
