### ISSUE TITLE
Create VS Code Tasks Based on User Interaction

### ISSUE THREAD

**Issue by vsjha18** [microsoft/vscode#99532]
- VSCode Version: Doesn't matter
- OS Version: Mac/Linux (But doesn't matter)

Steps to Reproduce:

Does this issue occur when all extensions are disabled?: NA

I have asked this question on [stackoverflow](https://stackoverflow.com/questions/62181711/create-vs-code-tasks-based-on-user-interaction)  also, but since there is no response there, hence I am posting it here as well. I understand this is not the best place for my query.

**Question 1**
I want to create a task for the user, based on analysis of the workspace and also after couple of **user interactions**. `provideTasks` works just fine only till I add any user interaction. For example this code.
```javascript
class ExampleTaskProvider implements vscode.TaskProvider {
  async provideTasks(token?: vscode.CancellationToken): Promise<vscode.Task[]> {
    const count = await vscode.window.showInputBox({'prompt' : "count"})
    return [ new vscode.Task(few, arguments, here)]
  }
  async resolveTask(task: vscode.Task, token?: vscode.CancellationToken) {
    return task;
  }
}
```
Just having one `showInputBox` renders this API useless and it fails to return the task. I expect the code to stop at the `await` but for some reason I don't see any returned task. 

If you simply remove the `showInputTask`, everything falls in place and runs fine.

**Question 2**
Why the documentation talks so little about the role of `resolveTask`? I found this API very strange in a way that it is very hard to predict when it will be called and when it will not.

When I do not `configure` the task and directly for the run, then `resolveTask` is never called. Even if I first configure the task, and do not opt for `recently used` task, it is not called. Only when I opt for `recently used` task I see `resolveTask` being called.

What is `resolveTask` and when it called and more importantly when it is not?

My requirement is to trigger a build task, I can do it without following `task` workflow but I want to do it in the right way, hence all the struggle.

**Request**
In the `vscode extension example` project can we please improve the example for `task provider`. It is filled with all unnecessary details and does very little apart from confusing people. Please ...

**Comment by vsjha18** [comment]
If you can provide me with some example code other than the one in [vscode extension samples](https://github.com/Microsoft/vscode-extension-samples) related to `TaskProvider`, it will be great.

**Comment by alexr00** [comment]
`resolveTask` documentation updated:
https://github.com/microsoft/vscode-docs/blob/f9e6d362f473bbaf057668c607af901003fe3c66/api/extension-guides/task-provider.md#L71-L71

There are several tasks providers in the VS Code built in extensions:
https://github.com/microsoft/vscode/tree/master/extensions/gulp
https://github.com/microsoft/vscode/tree/master/extensions/jake
are probably the simplest.
