### ISSUE TITLE
Some strings not translated in latest vscode

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#9953]
I know that not every release has to be fully localized but it seems like in the latest vscode insiders due to files moving around some strings are not translated which have previously been translated. For example:
- Explorer title
- Open Editors and the titles inside
- Extensions title and extensions input box placeholder

![screen shot 2016-07-29 at 16 53 34](https://cloud.githubusercontent.com/assets/1926584/17252450/0b5af064-55ad-11e6-9c09-200fe954d19e.png)

**Comment by dbaeumer** [comment]
As discussed in todays standup reorganizing code requires new translation files. We can work on our own translation DB to work around this.

**Comment by dbaeumer** [comment]
Closing. IMO the current solution of having LP is satisfactory.
