### ISSUE TITLE
can't re-authorize for github

### ISSUE THREAD

**Issue by wmpauli** [microsoft/vscode#99535]
- VSCode Version: 1.45.1
- OS Version: ubuntu bionic (via ssh extension from windows 10)

Steps to Reproduce:

1. checkout repo before your org enforces SAML SSO
2. try to push

I get this error message:
remote: The <bleep> organization has enabled or enforced SAML SSO. To access
remote: this repository, you must re-authorize the OAuth Application `GitHub for VSCode`.
fatal: unable to access 'https://github.com/<bleep>': The requested URL returned error: 403

I can still log push pull if from the command line, outside, but not the terminal in vs code.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by RMacfarlane** [comment]
To re-authorize, you can go to your settings on GitHub -> Applications -> Authorized OAuth Apps, find "GitHub for VSCode", and choose "Revoke" from the "..." menu. If you then sign out in VSCode and sign in again, you should be prompted to re-authorized

**Comment by chris-larsen** [comment]
> To re-authorize, you can go to your settings on GitHub -> Applications -> Authorized OAuth Apps, find "GitHub for VSCode", and choose "Revoke" from the "..." menu. If you then sign out in VSCode and sign in again, you should be prompted to re-authorized

How do you sign out from VSCode?

**Comment by RMacfarlane** [comment]
@wmpauli Did the above work, or are you still seeing this issue?

**Comment by BunnyMan1** [comment]
> If you then sign out in VSCode and sign in again

How can I do this in VSCode? I don't find any option to logout from the previously authorised github account.

**Comment by jobara** [comment]
I'm having the same issue. I can't find a way to re-authorize the VSCode with GitHub. @RMacfarlane can you suggest where to find this?

**Comment by RMacfarlane** [comment]
@jobara Can you follow the steps in https://github.com/microsoft/vscode/issues/99535#issuecomment-640705813? That is, revoke the OAuth app on GitHub and then sign out and sign in again.
<img width="503" alt="Screen Shot 2020-07-17 at 2 11 59 PM" src="https://user-images.githubusercontent.com/3672607/87831143-7fbbec00-c837-11ea-85e6-9ae13a4bc03b.png">
<img width="412" alt="Screen Shot 2020-07-17 at 2 12 20 PM" src="https://user-images.githubusercontent.com/3672607/87831175-8cd8db00-c837-11ea-84f4-1e81a9ace27e.png">

**Comment by jobara** [comment]
@RMacfarlane thanks so much for the quick reply. The screenshot helped. I was completely missing the user icon, at the bottom left side, when I was looking for how to sign out. Unfortunately I'm running into another issue with preferences sync `TurnedOff (UserDataSyncError) syncResource:unknown operationId:unknown: Cannot sync because syncing is turned off in the cloud`. However, you've helped me get past the first issue. Thanks again.

**Comment by BunnyMan1** [comment]
> I was completely missing the user icon, at the bottom left side, when I was looking for how to sign out.

Exactly what happened to me.

**Comment by israelpgjm** [comment]
> > I was completely missing the user icon, at the bottom left side, when I was looking for how to sign out.
> 
> 
> 
> Exactly what happened to me.
