### ISSUE TITLE
Problem interfacing anaconda python on vscode

### ISSUE THREAD

**Issue by LLLD-1** [microsoft/vscode#99549]
Issue Type: <b>Bug</b>

I don't the actual steps to reproduce. I tried to import numpy and it is giving me an import error and says that it i not recognizing anaconda. This is the first error it gives me:
conda : The term 'conda' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was  
included, verify that the path is correct and try again.
At line:1 char:1
+ conda activate base
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

It also gives me this error:
Original error was: DLL load failed: The specified module could not be found.
PS C:\Users\Lorenz> import numpy& C:/Users/Lorenz/anaconda3/python.exe "c:/Personal Projects/Finance Project/Finance Project.py"
At line:1 char:13
+ import numpy& C:/Users/Lorenz/anaconda3/python.exe "c:/Personal Proje ...
+             ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a  
string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed

The ampersand (&) character is not allowed. The & operator is reserved fo  Personal Projects/Finance Project/Finance Project.py"r future use; wrap an ampersand in double quotation marks ("&") to pass ir t as part of a                                                           as
string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRec  future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a  ordException                                                             or
    + FullyQualifiedErrorId : AmpersandNotAllowed                          dException

I am greatly confused by this error, as I am not using an ampersand. 
Thank you for any help.

**Comment by connor4312** [comment]
\extPython
