### ISSUE TITLE
add more entries to Open Recent / Recent

### ISSUE THREAD

**Issue by greggman** [microsoft/vscode#99547]
I know this has been asked for before and I know there is Ctrl-R for a longer list. The thing is what's the point of the other lists being so short? (the one in File->Open Recent and the one on the Welcome page) It would seem obvious to me that a person that is working on 30 projects has far more use a recent feature than a person working on 3.

The short lists seem like an infuriating taunt. Because I use File->Open Recent in many places in the OS my muscle memory has me pick File->Open Recent, only to find that the project I want is not there. Ever time I happens my brain screams that my time was just wasted.

Even the Welcome page, sure, **maybe** for a new user they'll click the help on the bottom left (any metrics?). Then, the next 10000 times they see the Welcome page that space is entirely wasted. Maybe redesign that page or maybe only show the welcome page once and then show a "projects page" from then on?

<img width="1125" alt="Screen Shot 2020-06-07 at 13 00 19" src="https://user-images.githubusercontent.com/234804/83960093-a5acb300-a8bf-11ea-9998-8cc21450f523.png">

Can you please revisit the decision to close the request for this?

Further, this seems like a trivial change. Somewhere in the code the limit is 10. That code just needs to look up the limit from the config. I'd be happy to submit a PR if it is likely to be approved ... and assuming I'm right that it's trivial.  (color me embarrassed if this feature already exists and I just didn't find it)

**Comment by gjsjohnmurray** [comment]
Discussion on #94755 includes additional suggestions fir improvements to Welcome page.

**Comment by greggman** [comment]
I don't know if anyone can help. I started making a PR

https://github.com/greggman/vscode/compare/greggman:master...greggman:more-recent-projects-and-files

I'm not sure where to put update the schema for the settings. More important though I can't get VSCode to build on either Mac nor Windows

https://stackoverflow.com/questions/62257317/getting-vscode-to-compile-on-either-windows-or-macos

**Comment by chrmarti** [comment]
Just increasing the number of entries will throw off the layout's balance which would be considered a bug. In https://github.com/microsoft/vscode/issues/63152 we were looking into an overhaul of the layout that might allow for more entries.

**Comment by greggman** [comment]
> increasing the number of entries will throw off the layout's balance

As a developer shouldn't i get to choose if I care about functionality more than looks? Sure, make it look good. In the meantime I'd like to me get work done faster with less frustration.
