### ISSUE TITLE
VC often enters a long useless period after scrolling

### ISSUE THREAD

**Issue by dnfort** [microsoft/vscode#99541]
Issue Type: <b>Bug</b>

VC sometimes (way too often) enters a long period of high CPU usage after scrolling even short distances making the program unusable.  The only cure is to exit (which itself can take quite a while) and start it again.  Waiting for the program to finally finish whatever it is doing does not work.  The program eventually stops using excessive CPU power but even the slightest scrolling starts it again.

1. I think larger source files make it happen more often so start with a large source file.  Small files make it happen too but less often.

2. Move up and down the document using the scroll roller on the mouse or the scroll bar on the right to cause the problem.  

3. This is extremely frustrating problem in an otherwise extremely useful program.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17763

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/wiki/Performance-Issues for guidance about reporting performance issues.
