### ISSUE TITLE
 A quick way to blame extensions

### ISSUE THREAD

**Issue by fitzlm** [microsoft/vscode#99552]
I hope I can enable or disable half of extensions at a time, which is especially convenient when troubleshooting extension problems.

**Comment by sandy081** [comment]
> I hope I can enable or disable half of extensions at a time, which is especially convenient when troubleshooting extension problems.

Is it to find out an extension that is causing an issue?

**Comment by fitzlm** [comment]
@sandy081 Yes, I don't want to test one by one.

**Comment by sandy081** [comment]
Ok, so updating the summary accordingly.

**Comment by ackvf** [comment]
@fitzlm workspace project configuration per folder sounds great but I think you should move it into separate suggestion.

**Comment by fitzlm** [comment]
Thanks for your suggestion, I have updated my issue.

**Comment by sandy081** [comment]
@jrieken Is there an issue you used to track the changes you did for blaming extensions feature? If so, please mark this as dup of that.

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/109841
