### ISSUE TITLE
Extensions enable and disable automatically

### ISSUE THREAD

**Issue by Rasesh2005** [microsoft/vscode#99551]
I work on Vs Code with multiple frameworks for web development like flask , django, php,etc.
i also use Vs Code for Java And C++ .. So I have their extensions too

Whenever I am Not using Any extension  I have Have to disable them manually, else they are causing interruptions(Ex: While using flask all html files become Django HTML, So flask doesn't work many a times)..Can You Kindly  Find Some Workaround form any of the following:
1> Extensions Should be enabled and disabled automatically based on types of files in workspace
2> Some Other Way That Extensions do Not Interfere with the workspace in which they are not invloved)

**Comment by connor4312** [comment]
> Extensions Should be enabled and disabled automatically based on types of files in workspace

Extensions have the ability to do this.

The best way to do this for you sounds like enabling/disabling extensions for individual workspaces by right clicking on them and hitting `Disable/Enable (Workspace)`

**Comment by Rasesh2005** [comment]
I am telling i have a lot of extensions i don't want to disable each on of them by myself. if vs code could do it itself then it would be a great help
