### ISSUE TITLE
Breadcrumbs not working

### ISSUE THREAD

**Issue by davidpoundall** [microsoft/vscode#99559]
Issue Type: <b>Bug</b>

Cannot for the life of me get breadcrumbs working in my .js file. Just spent the last two hours searching the web and getting the same answer.  Set breadcrumbs.enabled:  true in settings.  But settings has no breadrumbs setting to set. ???? 

Am I missing an extension?

tried using cntrl shift full stop but nothing comes up.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz (4 x 2800)|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.98GB free)|
|Process Argv|/private/var/folders/k9/gxk_v2090_n1mkmyvk4b_f_r0000gn/T/AppTranslocation/FAD493B8-634A-4931-936B-ABA963D70B75/d/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.37
Bookmarks|ale|9.3.0
python|ms-|2018.4.0
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.0.3
vscode-icons|vsc|8.8.0
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0

</details>
Reproduces only with extensions

**Comment by gjsjohnmurray** [comment]
> Reproduces only with extensions

Disable extensions one by one until you discover which one is causing the problem.
