### ISSUE TITLE
Extension Packs / Extension Configurations

### ISSUE THREAD

**Issue by Mycl95** [microsoft/vscode#99557]
Managing extensions in vscode can be pretty messy and time consuming imho. It would be nice if I could add/remove some kind of extension packs or configurations. Either self made from local storage or community made from the repo.

EDIT:
A great application would be if a pack/config from the repo gets updated (maybe extension A gets replaced/forked by B) that these changes get automatically applied in my vscode so I don't have to struggle around with that.

**Comment by sandy081** [comment]
Not sure if I understand your requirement, can you please be elaborate ?
