### ISSUE TITLE
Got an error message and can't use browser feature

### ISSUE THREAD

**Issue by kangwooc** [microsoft/vscode#99554]
I deleted a typescript project that I didn't use. After that, I got a message that I tried to work on the different projects; ```The TypeScript language service died 5 times right after it got started. The service will not be restarted.``` Also, I could not use the browser on vscode. Do I need to reinstall the vscode? A tsc version is 3.7.5 and my vscode version is 1.45.1. Thanks.
<img width="173" alt="Screen Shot 2020-06-07 at 4 00 44 PM" src="https://user-images.githubusercontent.com/25312211/83962431-4d35df80-a8d8-11ea-9e94-00c2201605c3.png">

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) when using the current TS release (3.9+)?

**Comment by kangwooc** [comment]
I didn't try on latest VS Code insiders build. Instead, I reinstall the stable version of vscode and it works now.
