### ISSUE TITLE
can't open terminal on LinuxMint19.3

### ISSUE THREAD

**Issue by qscgu23** [microsoft/vscode#99561]
Issue Type: <b>Bug</b>

I can't open bash or other terminal in vscode,but sometimes it works,I don't know what should I do even if check vscode's doc

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.0.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.56GB (8.79GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.36.0
vscode-drawio|hed|0.6.6
rainbow-csv|mec|1.7.0
vscode-language-babel|mgm|0.0.27
easy-less|mrc|1.6.3
vscode-docker|ms-|1.2.1
vscode-language-pack-zh-hans|MS-|1.45.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.5.80290
vetur|oct|0.24.0
material-icon-theme|PKi|4.1.0
vscode-yaml|red|0.8.0
LiveServer|rit|5.6.1
easysass|spo|0.0.6
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

Also getting a trace log of the launch would be very helpful https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

/needsMoreInfo

**Comment by qscgu23** [comment]
![terminal](https://user-images.githubusercontent.com/48400210/84583590-a4820580-ae2c-11ea-8706-2d053ed11574.png)

just like that, always waiting

**Comment by Tyriar** [comment]
Are you setting `terminal.integrated.inheritEnv`?
