### ISSUE TITLE
Order which items gain focus using f6 or shift+f6 is unintuitive

### ISSUE THREAD

**Issue by Neurrone** [microsoft/vscode#99564]
CC: @isidorn

Issue Type: <b>Bug</b>

1. Press f6 to move focus between different parts of the interface, and have either a debug console or a problems view at the bottom visible.

Expected: from the explorer view on the left, I expect that pressing f6 moves first to the open editor, followed by any open panels at the bottom e.g consoles or problems panels
Actual: panels at the bottom are next in the f6 order, followed by the editor.

I know this could be subjective but I personally find this pretty unintuitive. Examples where this is really annoying:

1. Open a file in explorer view by pressing enter in the tree. Focus is at the editor. Now, to go back to the tree view it requires 2 presses of shift+f6 instead of just 1.
2. The same thing happens when using find all references or show call hierarchy

VS Code version: Code - Insiders 1.46.0-insider (b1ef2bf05f90dd0e6438782411ab84756f97d8f1, 2020-06-05T12:30:13.870Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.87GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
notes|can|1.0.1
vscode-markdownlint|Dav|0.36.0
vscode-eslint|dba|2.1.5
prettier-vscode|esb|5.0.0
rest-client|hum|0.23.2
python|ms-|2020.5.80290
remote-wsl|ms-|0.44.2
cpptools|ms-|0.28.2
Go|ms-|0.14.3
vsnotes|pat|0.7.1
rust|rus|0.7.8
markdown-preview-enhanced|shd|0.5.10
vscode-webhint|web|1.5.6

</details>

**Comment by isidorn** [comment]
@Neurrone thanks for feedback!
The idea behind F6 navigation is that it is a "bird's view" navigation over the workbench areas. Once a user is interested in an area he can navigate down into it.

Your suggestion would be for F6 to go into each view. Which is not by design and I think would make the original navigatino a bit more cumbersome.

For now let's leave this issue open and we might change the behavior in the future.

**Comment by Neurrone** [comment]
Hm, I get that it shouldn't go into each subpane. Am just saying that I think the order that things gain focus when pressing f6 isn't intuitive, which wouldnt require more items to be added to the f6 focus order.

**Comment by isidorn** [comment]
The current order is
Editor -> Status bar -> Activity Bar -> Sidebar -> Panel -> Editor

What order do you propose?

**Comment by Neurrone** [comment]
By Sidebar i assume this refers to e.g, the tree view if explorer view is active? 

The order I was hoping for is something like editor -> panel (problems view, debug console etc) -> status bar -> activity bar -> sidebar -> editor

I believe this would also look natural visually as well but let me know if I'm mistaken. Would also like to hear from more people about whether this feels more intuitive.

**Comment by isidorn** [comment]
Yes, by Side Bar I assume the Explorer for example.

The order you propose makes sense and visual goes into a sort of clockwise order.
I will bring this up in the accessibility channel to see if more people have opinions.

**Comment by isidorn** [comment]
Nobody gave negative feedback, let's change it in insiders so we see reactions.

**Comment by isidorn** [comment]
I have pushed a change to tackle this.
@Neurrone please try it out with vscode insiders and let us know if it is good for you now. Thanks!

**Comment by Neurrone** [comment]
@isidorn this is excellent and is exactly what I wanted, thanks!

**Comment by isidorn** [comment]
@Neurrone thank you, adding label verified.

**Comment by Neurrone** [comment]
I ran into something that might or might not be related to this.

When I did a find all for the entire project, my usage pattern is to go to the tree and press enter to review the match's surroundings in the editor. Then I expect to be able to press shift+f6 and have focus land back to the tree view of results that I just left so that I can resume where I left off.

However, focus instead lands on the search edit field which is an efficiency killer because I have to tab 4-5 times to reach the tree view just to be able to find my place in it and to continue. Is there a more efficient way of doing this? I would also prefer f6 to save my place if that makes sense in that particular situation.

**Comment by isidorn** [comment]
@Neurrone this makes sense.
@roblourens @JacksonKearl is it possible in the search view to preserve last focused item, such when the view is focused again we move the focus to the previously focused item, and not always to the input. Should I file a new issue for this?
