### ISSUE TITLE
ESLint doesn't work in WSL remote

### ISSUE THREAD

**Issue by exoRift** [microsoft/vscode#99567]
- VSCode Version: 1.45.1
- OS Version: Windows 10 1909

Steps to Reproduce:

1. Have WSL enabled
2. Open a remote to WSL (I use it to run Node debugging)
3. Open a file in your project
4. Make a lint error

No error will be shown. I have no idea why ESLint doesn't run but it doesn't

Does this issue occur when all extensions are disabled?: Yes

**Comment by kameshkotwani** [comment]
can you please provide a specific code that makes the error, plus, the node-js version.

**Comment by exoRift** [comment]
Node version: 12.16.3

```js
const foo = 'hello'
foo = 'hi'
```
(Not sure why either of these are needed. No ESLint errors are reported, that's the issue)

**Comment by connor4312** [comment]
Is the eslint installed in WSL in addition to your editor?

**Comment by exoRift** [comment]
ESLint is installed locally in the `node_modules` folder

**Comment by connor4312** [comment]
You need to install the eslint extension to display errors: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

**Comment by exoRift** [comment]
Ah, some extensions need to be separately installed in WSL in addition to Windows. I see.

![](https://i.imgur.com/8cgEaQK.png)
