### ISSUE TITLE
use quickOpen in preLaunchTask - debug would not launch

### ISSUE THREAD

**Issue by doronpor** [microsoft/vscode#99562]
- VSCode Version: 1.45.1
- OS Version: Windows 10 64 bit

Steps to Reproduce:

1. Define launch config file with preLaunchTask - workbench.action.quickOpen
        {
            "name": "Python: run from dir",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "cwd":"${fileDirname}",
            "preLaunchTask": {
                "task": "quickOpen",
                "type": "shell",
                "command": "${command:workbench.action.quickOpen}",
            }
        }
2. Start debugging (F5) - command palette will open on quickOpen
3. select file - jumps to desired file but debugger would not run 

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
@doronpor the `quickOpen` action doesn't return anything. As the name indicates it just "opens" something. Using it in this context is possible (as you've seen) but it doesn't make sense.

In addition a `preLaunchTask`  is a task that is run before the debug session is launched. Typically this is a build task. The task is only expected to return a binary result: success or failure. You cannot return a program file from this task.

In addition you have already specified the file to be debugged via the `program` attribute: you specify the variable `${file}` which refers to the file in the currently active editor.




 "preLaunchTask" isn't supposed
