### ISSUE TITLE
commands.icon contribution point is not clear

### ISSUE THREAD

**Issue by XVincentX** [Microsoft/vscode#9956]
According to the intellisense, it looks like it's possible to specify an `icon` as part of command properties.

However, it looks like it is not documented in VSCode website and I am not able to understand where is this displayed. I tried with bot `.png` and `.ico`, but I wasn't able to see anything.

Are there some restrictions? Am I doing something wrong?

**Comment by jrieken** [comment]
Icons are only shown for editor title commands that are in the navigation group (the place where VS Code also shows icons). Formats that browsers/css support are supported by this extension point

**Comment by XVincentX** [comment]
@jrieken 
I do not get what's editor title commands...do you mean this?
![image](https://cloud.githubusercontent.com/assets/1416224/17322172/72ae20d2-589c-11e6-8731-d66dae3d24a6.png)

**Comment by jrieken** [comment]
No, this: ![screen shot 2016-08-02 at 11 02 13](https://cloud.githubusercontent.com/assets/1794099/17323036/95b3ae68-58a0-11e6-8ebc-3c97b2d821fd.png)

**Comment by XVincentX** [comment]
Thanks a lot! Would it worth to update the documentation about that? It's a bit confusing.
