### ISSUE TITLE
explorer - filter on type - by word

### ISSUE THREAD

**Issue by manufv** [microsoft/vscode#99560]
Issue Type: <b>Feature Request</b>

actually when I use **explorer - filter on type**, the filter use each character I type as a distinct part of the search.  Is there a option to search by **word**. 
sample : 
I have filesnamed 
- **GE**T.FIEL**D**
- MAKE.**GED**
if I filter on type : **GED** , the two files are show ... I'll restrict only MAKE.GED where the typed word is complete.

![image](https://user-images.githubusercontent.com/4491759/83967125-fc65bd00-a8be-11ea-8198-f24a57731372.png)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

**Comment by isidorn** [comment]
This is currently not possible, but I guess a feature request against our list / tree filter, thus forwarding to @joaomoreno

**Comment by joaomoreno** [comment]
#66913
