### ISSUE TITLE
DebugConfiguration.noDebug is sticky

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#99576]
Version: 1.46.0-insider
Commit: b1ef2bf05f90dd0e6438782411ab84756f97d8f1
Date: 2020-06-05T12:27:56.662Z (2 days ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

Running _"Run > Start Debugging"_ *after* running _"Run > Start Without Debugging"_ does not start debugging. Close inspection revealed that `noDebug` of the `DebugConfiguration` passed to DebugConfigurationProvider's `resolveDebugConfiguration` remains `true`.

Steps to Reproduce:

1. Clone the vscode debug adapter sample 
`git clone https://github.com/microsoft/vscode-mock-debug`

2. Build the mock extension `npm install`.

3. Create a breakpoint at [`extension.ts:105`](https://github.com/microsoft/vscode-mock-debug/blob/7623477a3e824ec05225b553bc1f72f1ca8272b6/src/extension.ts#L105)

4. Launch the extension (F5)

5. Open a `readme.md` in the extension development host.

6. _"Run > Start Without Debugging"_ (Ctrl+F5) from the extension development host, and select `Mock Debug`.

7. See the breakpoint hit, and evaluate `config`. 

![Screen Shot 2020-06-07 at 7 00 04 PM](https://user-images.githubusercontent.com/4999471/83982051-3bad0180-a8f1-11ea-9dd1-aa86daeb0102.png)

8. Go back to the extension development host, and stop the task.

9. _"Run > Start Debugging"_ (F5) from the extension development host this time, and select `Mock Debug`.

10. See the breakpoint hit, and evaluate 'config'.

![Screen Shot 2020-06-07 at 7 05 04 PM](https://user-images.githubusercontent.com/4999471/83982122-d86f9f00-a8f1-11ea-81d7-d5bb4d926f5b.png)

You can see `noDebug` (the second row) is set true even though it's requested to debug. 

Actually, I see that if I start with F5 first, and try Ctrl+F5 later, the second run receives DebugConfiguration without `noDebug` property. So, it seems like the value chosen in the very first run remains unchanged in the subsequent task runs.

**Comment by isidorn** [comment]
@hyangah great catch!
I have pushed a fix for this which will be available in vscode insiders tomorrow.

**Comment by weinand** [comment]
The fix works for me in Insiders when using `node-debug2`. The new `js-debug` seems to ignore the `noDebug` property in launch configs.
