### ISSUE TITLE
All user settings deleted after installing extension

### ISSUE THREAD

**Issue by matangover** [microsoft/vscode#99570]
Issue Type: <b>Bug</b>

### Steps to Reproduce

This is not easily reproducible – probably some sort of race condition. It happened as follows:

1. (Install 'Test Explorer UI extension' - probably not related.)
2. Install 'TestMate C++' extension (`matepek.vscode-catch2-test-adapter`) from VS Code Marketplace. At the time this happened, the latest version was 3.2.5.
3. Upon installation, the extension prompted me to allow telemetry, and I selected "Over my dead body (No)". 
4. Immediately after clicking that button, my VS Code theme and appearance changed. Going into my user `settings.json`, I saw all my settings have been deleted, and it now had only new settings added by the `TestMate C++` extension:

```json
{
    "testMate.cpp.log.userId": "<some user id>",
    "testMate.cpp.log.logSentry": "disable_3"
}
```

I've searched the entire VS Code logs directory for the time in which this occurred, and found the following anomaly:
```
[2020-06-06 23:53:07.146] [renderer8] [error] [text file model] handleSaveError(1) - exit - resulted in a save error: Error: Unable to write file 'vscode-userdata:/Users/matan/Library/Application Support/Code/User/settings.json' (Error: File Modified Since) vscode-userdata:/Users/matan/Library/Application Support/Code/User/settings.json
[2020-06-06 23:53:07.317] [renderer8] [error] Unable to write into user settings because the content of the file is newer.: Error: Unable to write into user settings because the content of the file is newer.
    at e.reject (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5183:839)
    at e.doWriteConfiguration (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5181:271)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

I did not modify `settings.json` on disk when this happened, but I may have modified it a few hours before that. Anyway, that shouldn't be a problem.

I have reported the issue on the extension's bug tracker [here](https://github.com/matepek/vscode-catch2-test-adapter/issues/206), but it seems like this is a VS Code bug, as the extension author says it "doesn't do any magic". Looking at the [relevant point](https://github.com/matepek/vscode-catch2-test-adapter/blob/7d41e24cc9cb8bf32e9743551835d5866fdea0e0/src/Configurations.ts#L396) in the extension's code confirms that it's simply calling `WorkspaceConfiguration.update`.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
cpp-helper|ami|0.1.1
QML|bbe|1.0.0
better-toml|bun|0.3.2
xml|Dot|2.5.0
gitlens|eam|10.2.1
EditorConfig|Edi|0.15.1
vscode-test-explorer|hbe|2.19.1
latex-workshop|Jam|8.10.0
theme-karyfoundation-themes|kar|20.0.3
restructuredtext|lex|128.0.0
vscode-clangd|llv|0.1.5
mypy|mat|0.1.4
vscode-catch2-test-adapter|mat|3.2.5
git-graph|mhu|1.23.0
csharp|ms-|1.22.0
pyright|ms-|1.1.41
python|ms-|2020.5.80290
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
cpptools|ms-|0.28.2
vscode-typescript-tslint-plugin|ms-|1.2.3
wordcount|ms-|0.1.0
pandocciter|not|0.7.0
material-icon-theme|PKi|4.1.0
seti-icons|qin|0.1.3
shader|sle|1.1.4
best-light-themes-pack|the|1.0.2
vscode-lldb|vad|1.5.2
vim|vsc|1.14.5

(13 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
/duplicate

I suspect this has the same root cause as this - https://github.com/microsoft/vscode/issues/47763

**Comment by matangover** [comment]
Thanks @sandy081! If I may suggest - if #47763 is used to track the root cause of this issue, it's better to update it to reflect that with a more general title and description. I would never find that bug when searching for my issue, so I just wasted time looking through logs and crafting a good bug report.

**Comment by sandy081** [comment]
Sure - done.
