### ISSUE TITLE
VS Code sometimes uses too much CPU power after scrolling.

### ISSUE THREAD

**Issue by dnfort** [microsoft/vscode#99579]
Issue Type: <b>Performance Issue</b>

1.  This occurs occasionally (too often!) during scrolling with the mouse or the scroll bar on the side.  Once it starts it eventually stops but any scrolling starts it again.  Restarting Vs Code is the only solution.
2.  The problem occurs even when there is only one file open (no workspace).
3. Using Process Explorer shows that the excess CPU time is being used by Window/Rendering.
4.  I have enclosed a file of Profiling the Renderer Process ( (I think).

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (9.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   109	 24052	code main
    0	    22	 11464	   utility
    0	    72	 25252	   window (Issue Reporter)
    0	    63	 31564	   shared-process
    0	   178	 32664	   gpu-process
    0	   210	 35576	   window (observe.c - astro (Workspace) - Visual Studio Code)
    0	    35	 13008	     searchService
    0	    14	 20352	     watcherService 
    0	     5	 23592	       console-window-host (Windows internal process)
    0	   124	 36452	     extensionHost
    0	    22	 17524	       "C:\Users\dnfor\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\dnfor\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=36452
    0	     3	 34548	       cmd /s /c "c:\Users\dnfor\.vscode\extensions\ms-dotnettools.csharp-1.22.0\.omnisharp\1.35.2\OmniSharp.exe -s c:\cygwin32\home\David\astro\code\bahtinov-grabber-master\BahtinovGrabber.sln --hostPID 36452 DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin c:\Users\dnfor\.vscode\extensions\ms-dotnettools.csharp-1.22.0\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll FileOptions:SystemExcludeSearchPatterns:0=**/.git FileOptions:SystemExcludeSearchPatterns:1=**/.svn FileOptions:SystemExcludeSearchPatterns:2=**/.hg FileOptions:SystemExcludeSearchPatterns:3=**/CVS FileOptions:SystemExcludeSearchPatterns:4=**/.DS_Store formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4"
    0	    81	 17572	         c:\Users\dnfor\.vscode\extensions\ms-dotnettools.csharp-1.22.0\.omnisharp\1.35.2\OmniSharp.exe  -s c:\cygwin32\home\David\astro\code\bahtinov-grabber-master\BahtinovGrabber.sln --hostPID 36452 DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin c:\Users\dnfor\.vscode\extensions\ms-dotnettools.csharp-1.22.0\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll FileOptions:SystemExcludeSearchPatterns:0=**/.git FileOptions:SystemExcludeSearchPatterns:1=**/.svn FileOptions:SystemExcludeSearchPatterns:2=**/.hg FileOptions:SystemExcludeSearchPatterns:3=**/CVS FileOptions:SystemExcludeSearchPatterns:4=**/.DS_Store formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
    0	     5	 29348	         console-window-host (Windows internal process)
    0	    56	 37296	       c:\Users\dnfor\.vscode\extensions\ms-vscode.cpptools-0.28.2\bin\cpptools.exe
    0	    58	 35400	         "c:\Users\dnfor\.vscode\extensions\ms-vscode.cpptools-0.28.2/bin/cpptools-srv.exe" 37296 0
    0	     5	 36696	         console-window-host (Windows internal process)
    0	    10	 37808	   electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (observe.c - astro (Workspace) - Visual Studio Code)
|    Folder (code): 374 files
|      File types: c(234) exe(31) cs(29) txt(11) cache(4) py(3) resx(3)
|                  resources(3) stackdump(2) json(2)
|      Conf files: makefile(4) settings.json(1) csproj(1) sln(1);
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.22.0
python|ms-|2020.5.80290
cpptools|ms-|0.28.2

</details>

![vscode_problem](https://user-images.githubusercontent.com/38361088/83983876-b6245400-a8e6-11ea-8f92-c33903c5577a.jpg)

[CPU-20200607T172950.zip](https://github.com/microsoft/vscode/files/4743350/CPU-20200607T172950.zip)
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by jrieken** [comment]
Hm, the profile doesn't reveal much. Things are mostly idle. Can you try again? Can you also try the with Performance Tool (F1 > Developer Tools > Performance)?

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/1794099/84052137-7164ef80-a9b0-11ea-936b-65b68bd3e6da.png">
