### ISSUE TITLE
Peek Problem window truncates text

### ISSUE THREAD

**Issue by willt** [microsoft/vscode#99577]
- VSCode Version: 1.45.1
- OS Version: Linux

Steps to Reproduce:

1. Use a linter and press F8 until you get to  a problem with a large amount of text returned from the linter. The linter im using is a modified version of perl-toolbox that returns extra info.

This first image shows me hovering over the problem which lets you scroll the window all the way down to the end of the window content. The second image is what appears if you press F8 or press the Peek Problem link while hovering. It shows the content being cutoff if you scroll all the way down.

Does this issue occur when all extensions are disabled?: Yes
![PeekProblemView](https://user-images.githubusercontent.com/340016/83982260-32646a80-a8da-11ea-8848-d77a113250a3.png)
![HoverProblem](https://user-images.githubusercontent.com/340016/83982263-385a4b80-a8da-11ea-851e-9ce3bcf1022c.png)

**Comment by sandy081** [comment]
Can you please provide a sample repo (in GitHub) to repro this?
