### ISSUE TITLE
Codicons: add an alias for git-branch

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#99586]
Currently we have an icon that is a git branch, but it is called `source-control`. I think we should add an explicit `git-branch` version (with the same icon), so if we ever decide to change the SCM icon, it won't break other usages.

**Comment by misolori** [comment]
We actually already have `git-branch` that points to the same `source-control` icon 😄 we also have these:

![image](https://user-images.githubusercontent.com/35271042/84059020-d0a21000-a96e-11ea-9ee2-1842964654b0.png)

**Comment by eamodio** [comment]
@misolori it seems to be missing from here then:
![image](https://user-images.githubusercontent.com/641685/84166497-f862a800-aa42-11ea-8df7-cc9d5da103de.png)

**Comment by misolori** [comment]
@eamodio the codicon preview page doesn't show all of the aliases, just the primary names. Our [product icon references](https://code.visualstudio.com/api/references/icons-in-labels) has the full list of aliases.
