### ISSUE TITLE
Setup was unable to create the directory %USERPROFILE% Error 5: Access Denied

### ISSUE THREAD

**Issue by RG031102** [microsoft/vscode#99580]
- VSCode Version: 1.45.1
- OS Version: Windows 10

Steps to Reproduce:

1. rename user profile
2. launch visual studio code

Does this issue occur when all extensions are disabled?: Yes/No

I am trying to install VSCode but I keep getting this error. There was a post made about this in 2019 but no answer was given in the thread I would appreciate any help. Link to 2019 thread: https://github.com/Microsoft/vscode/issues/67516

**Comment by kameshkotwani** [comment]
It's very vague. Please elaborate the steps and please provide screenshots to help us understand better.

**Comment by joaomoreno** [comment]
We don't support renaming the user profile. Please completely uninstall VS Code and reinstall it, if you rename your user profile.
