### ISSUE TITLE
Can't preview the local pictures in VSCode

### ISSUE THREAD

**Issue by Icecream-blue-sky** [microsoft/vscode#99588]
- VSCode Version: 1.45.1
- OS Version: Windows_NT x64 10.0.18363(Windows 10)

Steps to Reproduce:

1. My markdown file is in "_posts" directory and the pictures are in "images" directory like below.
![image](https://user-images.githubusercontent.com/26771037/83990956-e23ee400-a97d-11ea-8cd1-7d40c6c236db.png)

2.Then I want to show the pictures in my file using relative file path like below.
![image](https://user-images.githubusercontent.com/26771037/83991056-30ec7e00-a97e-11ea-899a-f13d10357388.png)
But it just dosen't work...
![image](https://user-images.githubusercontent.com/26771037/83991126-6e510b80-a97e-11ea-82f8-2001cb96d78c.png)
PS: My preview plugin is the native plugin that comes with the VSCode.Not using Markdown preview ehanced.

Does this issue occur when all extensions are disabled?: No.
My friend's VSCode version is like below.
![NSN)4Q$QRZ~LD$HXFXVQG44](https://user-images.githubusercontent.com/26771037/83991457-5e85f700-a97f-11ea-8a48-bf7d2bcb7e02.png)
It seems that this version works well.I don't know why would this happen...
Plz help me.

**Comment by kameshkotwani** [comment]
the path for images is wrong, you have to write "../images/deep_learning/gm_1.png"

The .. is used to get out of the posts directory and then go to images directory.
Let me know if it works!

**Comment by Icecream-blue-sky** [comment]
I have tried "../images/deep_learning/gm_1.png".And I even reinstall the 1.43.2 version.But it doesn't work at all.

**Comment by Icecream-blue-sky** [comment]
> the path for images is wrong, you have to write "../images/deep_learning/gm_1.png"
> 
> The .. is used to get out of the posts directory and then go to images directory.
> Let me know if it works!

What's more, I find that it doesn't work even when I use absolute path like "D:\\Study\\Icecream's_blog\\icecream3\\source\\images\\deep_learning\\gm_1.png" or "D:/Study/Icecream's_blog/icecream3/source/images/deep_learning/gm_1.png".
It's extremely strange...

**Comment by kameshkotwani** [comment]
what extension are you using to preview the image?

**Comment by kameshkotwani** [comment]
VSCode is showing the image by using default preview in markdown.
![Code_uJnaQGYTxc](https://user-images.githubusercontent.com/36355951/83993523-4a3afd80-a971-11ea-88c0-cd03c242625a.jpg)

one thing you can try is remove the underscore from posts, and see if that works..

ALSO:
when using your path, the image is not showing up in default previewer in vscode. 
![Code_IDGmFjIO7K](https://user-images.githubusercontent.com/36355951/83993597-7e162300-a971-11ea-82f1-739c4c46d80b.jpg)

**Comment by Icecream-blue-sky** [comment]
> VSCode is showing the image by using default preview in markdown.
> ![Code_uJnaQGYTxc](https://user-images.githubusercontent.com/36355951/83993523-4a3afd80-a971-11ea-88c0-cd03c242625a.jpg)
> 
> one thing you can try is remove the underscore from posts, and see if that works..
> 
> ALSO:
> when using your path, the image is not showing up in default previewer in vscode.
> ![Code_IDGmFjIO7K](https://user-images.githubusercontent.com/36355951/83993597-7e162300-a971-11ea-82f1-739c4c46d80b.jpg)

Thanks! I think I find the cause of my problem. It's not VSCode's bug. I don't know I should open the  directory where the .md and pictures are saved in the explorer(hot key is Ctrl + shift + E) before opening the .md file until seeing your reply. After doing that, the pictures finally show.
Hope that this issue will help others who meet the same problem as mine!
