### ISSUE TITLE
Navigation dont work 

### ISSUE THREAD

**Issue by rohitraja** [microsoft/vscode#99593]
Issue Type: <b>Bug</b>

Most of the navigation dont work. 

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.4.0-179-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 1249)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|15.54GB (1.75GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
python|ms-|2019.6.24221
java|red|0.46.0
annotator|ryu|1.0.0
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.18.1
gitblame|wad|3.0.1

</details>

**Comment by gjsjohnmurray** [comment]
Start by updating to the current release, which is 1.45.1.

Then if the problem remains, please provide details of how to reproduce it. You can paste screenshots into GitHub.
