### ISSUE TITLE
No way to remove account for sync

### ISSUE THREAD

**Issue by catssie** [microsoft/vscode#99590]
Issue Type: <b>Bug</b>

I entered the wrong github account for syncing of my settings.  It's not possible or not clear how to remove that setting.  

VS Code version: Code - Insiders 1.46.0-insider (b1ef2bf05f90dd0e6438782411ab84756f97d8f1, 2020-06-05T12:30:13.870Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (10.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by RMacfarlane** [comment]
Hey @catssie, if you click on the account within the accounts menu, a quick pick should appear with the option to sign out of the account. You can then sign in with a different github account.

**Comment by catssie** [comment]
Thank you, it's the second conclusion then...
