### ISSUE TITLE
cmd无法启动

### ISSUE THREAD

**Issue by cheng11231456** [microsoft/vscode#99594]
Issue Type: <b>Performance Issue</b>

终端进程命令“C:\Windows\system32\cmd.exe ”无法启动 (退出代码: {2})

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    95	  4548	code main
    0	    25	  2576	   utility
    0	   318	  5136	   window (设置 - water3.0 - Visual Studio Code [管理员])
    0	    34	  3848	     searchService
    0	   116	  5656	     extensionHost
    0	    49	  1512	       electron_node eslintServer.js 
    0	    50	  2244	       electron_node tsserver.js 
    0	   171	  3592	       electron_node tsserver.js 
    0	    45	  5968	         electron_node typingsInstaller.js typesMap.js 
    0	   122	  5356	       electron_node vueServerMain.js 
    0	    58	  7312	       "D:\Program Files (x86)\Microsoft VS Code\Code.exe" "d:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=5656
    0	    11	  5924	     watcherService 
    0	    75	  5456	   shared-process
    0	    19	  5672	   electron-crash-reporter
    3	   105	  5788	   gpu-process
    1	    64	  7268	   window (问题报告程序)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (设置 - water3.0 - Visual Studio Code [管理员])
|    Folder (water3.0): 494 files
|      File types: png(237) js(94) vue(53) map(34) css(23) zip(15) json(3)
|                  html(3) development(1) production(1)
|      Conf files: package.json(1) settings.json(1);
```

</details>
<details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-styled-jsx|bla|1.5.0
vscode-express|Com|0.0.5
dart-code|Dar|3.11.0
flutter|Dar|3.11.0
vscode-eslint|dba|2.1.5
es7-react-js-snippets|dsz|2.8.0
vscode-html-css|ecm|0.2.3
vue-snippets-js-html-pug-razor|heb|0.0.3
vue-snippets|hol|0.1.11
beautify|Hoo|1.5.0
rest-client|hum|0.23.2
tangwei|lir|0.0.1
vscode-language-pack-zh-hans|MS-|1.45.1
sublime-keybindings|ms-|4.0.7
debugger-for-chrome|msj|4.12.8
vscode-react-native|msj|0.16.0
vetur|oct|0.24.0
html-to-jsx|ria|0.0.1
LiveServer|rit|5.6.1
any-rule|rus|0.3.3
vue-vscode-snippets|sdr|1.9.0
js-jsx-snippets|sky|10.1.0
vs-code-node-require|tgr|1.4.7
vscode-icons|vsc|10.1.1

</details>

**Comment by Hotinly** [comment]
如果你指的是在 settings.xml 中配置的cmd.exe 无法启动，
则转义路径为 ->  `C:\\Windows\\system32\\cmd.exe`

**Comment by dbaeumer** [comment]
I am closing the issue since no translation has been provided in 7 days.
