### ISSUE TITLE
Support temporarily installed fonts. (Win)

### ISSUE THREAD

**Issue by villiv** [Microsoft/vscode#996]
Please support font that loaded by the [AddFontResource](https://msdn.microsoft.com/en-us/library/windows/desktop/dd183326%28v=vs.85%29.aspx)\* function for the sake of the non-admin workers.
Along with the portable mode(#329) we may have, it helps a lot.

*It can be used to add font by non-admin user. ([FYI1](https://msdn.microsoft.com/en-us/library/dd144833%28v=vs.85%29.aspx)) ([FYI2](http://www.dailygyan.com/2008/05/how-to-install-fonts-in-windows-without.html))

**Comment by alexandrudima** [comment]
We just ask Chromium to render the font. The only alternative would be to add support for dynamically injecting css @font-face

**Comment by villiv** [comment]
Thanks for your reply.

So it's Electron's job. Since Chromium itself can see those temporary fonts, There has to be a way.

**Comment by vanowm** [comment]
After 7 years are there any plans add ability use custom fonts without installing them into the system?
