### ISSUE TITLE
Python integrated console debugger doesn't start properly, but hangs infinitely long

### ISSUE THREAD

**Issue by AndyLuckert** [microsoft/vscode#99609]
**VERSIONS:**
- VSCode Version:
1.45.1 (x64)

- OS Version:
Operating System: Ubuntu 18.04.4 LTS
Kernel: Linux 5.3.0-53-generic
Architecture: x86-64

- Python version:
Python 3.7.7 (default, Mar 23 2020, 22:36:06) 
[GCC 7.3.0] :: Anaconda, Inc. on linux

**Steps to Reproduce:**

1. Open `VS Code` application
2. Open a `python`-file and wait until loading of the extensions has finished (this sometimes almost bloats my 8 GB RAM recently for around 15 seconds).
3. Press `F5` for launching debugging process of currently opened file via integrated terminal in general debugging mode.

**Does this issue occur when all extensions are disabled?: Yes/No**

As of yet, it just occurred with all my extensions enabled.
Since the first time of occurrence, I managed to get rid of the aforementioned issue via restarting `VS Code` several times until it started working thankfully.
Nevertheless, this inconvenience has occurred now 3 times already after booting on 3 contiguous days.
If it happens again to me tomorrow, I will test it without the extensions to check for a possible difference.

**Comment by connor4312** [comment]
\extPython
