### ISSUE TITLE
My PHP codes are not running on browser

### ISSUE THREAD

**Issue by Kendrashya** [microsoft/vscode#99606]
I am entering php codes in visual studio code and they are not running on browser, they are running inside visual studio code only . My HTML codes are running live on browser but not php codes.
Please help me .

**Comment by augustnasman** [comment]
did you forget the <?php tag :P

**Comment by Kendrashya** [comment]
Actually , in my PHP codes there is no option of running code on browser , or on live server.
They are showing output in visual studio code in the output session.
My HTML codes are running on browser but not PHP codes.

**Comment by augustnasman** [comment]
The browser cannot run php code, you need a server for that. Lookup how to setup ex. Apache for that.

**Comment by Kendrashya** [comment]
I have WAMP server and I have also provide php.executable.path to it , I am showing my setting.json page 
![Screenshot (6)](https://user-images.githubusercontent.com/66623306/84031588-90b14c00-a9b3-11ea-9550-fe5fa15b36e8.png)

If anything is left , then you can advice me.
