### ISSUE TITLE
code coverage display

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#99602]
Issue Type: <b>Feature Request</b>

can code coverage be shown for various languages after unit testing the code?
is there any way of displaying code coverage directly against the file in vscode?
i came across a few extensions but i could not get a satisfactory results.

VS Code version: Code - Insiders 1.46.0-insider (b1ef2bf05f90dd0e6438782411ab84756f97d8f1, 2020-06-05T12:30:13.870Z)
OS version: Windows_NT x64 10.0.18363

**Comment by connor4312** [comment]
This is something that extensions will need to handle. If the ones you find aren't satisfactory, you can makes PRs to them, or even write your own!

**Comment by sanket-bhalerao** [comment]
@connor4312 can this be a worthwhile addon in VSCode? something similar to Setting Sync.

**Comment by connor4312** [comment]
We have formalized testing support on our roadmap for 2020. Once that is done, coverage becomes a possibility, but at the moment this is outside the scope of VS Code core.

**Comment by sanket-bhalerao** [comment]
this makes me happy to know this is a possibility down the road.
will hope this comes soon.
