### ISSUE TITLE
Jump back to the wrong window when going back with mouse

### ISSUE THREAD

**Issue by zingdle** [microsoft/vscode#99605]
- VSCode Version: 1.45.1
- OS Version: Ubuntu 20.04 / Windows 10 19041

Steps to Reproduce:

4 files in workspace:

```py
# foo.py

from bar import barfunc

def foofunc():
    barfunc()
```

```py
# bar.py

def barfunc():
    pass
```

```c
// foo.c

void bar();

int foo() {
    bar();
}
```

```c
// bar.c

void bar() {
    // whatever
}


```

1. Open `bar.py` and split window using `Ctrl-\`
2. `F12` to `Go to Definition` for `barfunc` in the right window. `bar.py` is opened in the right window and the cursor is under the function definition. 
3. Press `back` button on the mouse but the cursor jump back to `barfunc` in the left window (expected to jump back in the right window)
4. Same problem for `foo.c`. Same problem on Windows 10 and Ubuntu 20.04.

Does this issue occur when all extensions are disabled?: No

This issue requires `Python` and `C/C++` extension to reproduce.

**Comment by bpasero** [comment]
This issue has been reported already in either this or a similar form. Please check the label that was assigned to this issue to find it.
