### ISSUE TITLE
Closing a file that is open in twice (split panes) with unsaved changes prompts to save

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#9960]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a file and make some changes (don't save)
2. Split the window (`Ctrl`+`\`)
3. Close the file to remove the split

You'll be prompted to save changes (and clicking `Don't Save` will undo the changes). This isn't what I would expect, I would've expected the second file to silently close and the in-memory changes remain (since the file is still open and visible with changes in the other pane).

**Comment by stevencl** [comment]
Yes, this is something we will work on. See https://github.com/Microsoft/vscode/issues/8983

**Comment by DanTup** [comment]
lol, so many dupes.. Sorry, should've searched!
