### ISSUE TITLE
Keyboard Problem 

### ISSUE THREAD

**Issue by Muznahmm** [microsoft/vscode#99616]
We have written the needed data into your clipboard because it was too large to send. Please paste.
1.Keyboard is not responding when i press character key.
2.opening double window also causing same problem.
3.Shortcuts are working fine.but some notation keys are not working.
4.Keyboard strikes are working fine for other application.only vs code is causing problem.

**Comment by connor4312** [comment]
Please go through our keyboard troubleshooting steps and let us know -- https://github.com/microsoft/vscode/wiki/Keybinding-Issues

/needsMoreInfo

**Comment by Muznahmm** [comment]
i think .its because of CPU loading.i killed some running process and disabled all extension.it works fine now
