### ISSUE TITLE
Background processes not spawning for bash

### ISSUE THREAD

**Issue by Twiggeh** [microsoft/vscode#99618]
Can't create background processes from `tasks.json` . Basically if I append `&` to a command it doesn't work …
## tasks.json
```js
  "tasks": [
    {
      "type": "shell",
      "label": "start webpack",
      "command": "cd bin && ./startWebpack.sh &"
    },
]
```

## startWebpack.sh
```bash
#!/bin/bash
echo "Starting webpack-dev-server"
cd .. && cd client && yarn debug &
```

## Example recording

I start the command just by itself in bash & the script runs, if I start it from vsc it doesn't. This setup still worked yesterday …
![Peek 2020-06-08 15-46](https://user-images.githubusercontent.com/23149166/84037905-86855280-a99f-11ea-8fbd-c2c200466c38.gif)

**Comment by alexr00** [comment]
When your shell is bash, tasks are run like this:
```
bash -c cd bin && ./startWebpack.sh &
```
If you can get your command to run like that, then that's great. However, tasks does provide easier mechanisms for what you're trying to do.
If you want to run a task without showing it and start it in a different directory, try something like this:
```
		{
			"type": "shell",
			"label": "start webpack",
			"command": "./startWebpack.sh",
			"options": {
				"cwd": "${workspaceFolder}/bin"
			},
			"presentation": {
				"reveal": "never"
			}
		
```
