### ISSUE TITLE
Show active file's GIT Branch name (when working with multiple repos)

### ISSUE THREAD

**Issue by Vasista-Eranki** [microsoft/vscode#99617]
Hello team

Hope you're healthy and safe from the pandemic.

I'd like to request a feature that addresses my scenario as below:

My working directory has multiple repositories and I have to keep working on them in parallel. I often get lost with the branch I'm working with. The status bar on the footer shows the branch currently selected (to the left side) in the Source Control, but not the active file's branch.

(Example: 

Consider my directory [MyWork] has 2 repositories:

- repo_A[Master]
- repo_B[Master]

When I have to make changes in repos A/B, I create corresponding branches as required.

Say for example, I'm working on a bug 12345 which has files to be changed in repo_A. So, I create a branch for fix-for-bug-12345 under repo_A. Few moments after, I get to handle another bug, this time via repo_B (fix-for-bug-99887):

- repo_A[Master]  --> fix-for-bug-12345
- repo_B[Master]  --> fix-for-bug-99887 

Now, while fixing bug 99887, I get to know the fix requires changes in repo_A also.. and I'm unaware of, in what branch of repo_A is selected now. And many times, resulting in overlapping fixes (in repo_B) of 12345 and 99887.

The branch name (selected in Source Control) is shown in the bottom left of the footer Status bar; but, that doesn't have the following (which is my request):

**My Requests:**
- [x] The footer status bar shall contain the repo-branch name of the active file in the editor section. This is to be made _dynamic_ and is updated whenever the file selection in the editor changes.
- [ ] The repository name shall be included along with the branch name in the left of the footer status bar.

This shall resolve my problem and also add more clarity to all of our users.

Thank you for providing a platform to hear us and to read a (_rather_) lengthy request.

**Comment by joaomoreno** [comment]
> The status bar on the footer shows the branch currently selected (to the left side) in the Source Control, but not the active file's branch.

The status bar actually also tracks the active file in the editor, doesn't that work for you?

![recording (1)](https://user-images.githubusercontent.com/22350/84157763-6753f700-aa6b-11ea-942c-6e5519540871.gif)

**Comment by Vasista-Eranki** [comment]
Hi

Yes; this seems working now. Can you help me with a way to show-up the repo name along with the active-branch?

**Comment by joaomoreno** [comment]
We only render the repo name on the hover tooltip, have you tried hovering over the branch name?

**Comment by Vasista-Eranki** [comment]
nice; I haven't tried it earlier. 

Can we do any tweeks to show the _repo-name - branch-name_ like in the tooltip?

**Comment by Vasista-Eranki** [comment]
hello @joaomoreno 

Hope you're doing good.

I managed to secure the required votes. 
![image](https://user-images.githubusercontent.com/60959482/89372255-4de5c900-d703-11ea-808b-4a72f9638f79.png)

You may please take it forward.

**Comment by SneakyFish5** [comment]
Is something like this what you were looking for?

![beb5e8602dbfd1cd68a2e1c598c98695](https://user-images.githubusercontent.com/32284796/89720404-5f470380-d997-11ea-95b3-62e371979a11.png)

Example of switching between two repositories in the same workspace:

![example](https://user-images.githubusercontent.com/32284796/89720593-43dcf800-d999-11ea-964c-e54665dbfde5.gif)

I currently have it setup behind a setting called `git.repositoryName`, which defaults to `false`. Is that setting name suitable, or is there something else that might fit better?

Full commit here: https://github.com/SneakyFish5/vscode/commit/d8431699c72961e056bc6172aa6ba65c66810670

**Comment by Vasista-Eranki** [comment]
@SneakyFish5 : looks good to me.

**Comment by Vasista-Eranki** [comment]
@vscode-triage-bot Votes are provided for the comments.

@SneakyFish5 I hope this is being taken care..

**Comment by SneakyFish5** [comment]
I think the issues been closed because the votes were applied to your comment rather than the original post, which is why it was closed. I'll open the PR right now, it slipped my mind so sorry about that and thanks for the reminder.
