### ISSUE TITLE
Cannot re-save a permanently deleted file with same filename as when first created

### ISSUE THREAD

**Issue by Boss-Hogg** [microsoft/vscode#99619]
Issue Type: <b>Bug</b>

1. Create a new file, with some text content
2. Save File (MyFile.txt)
3. In file explorer, permanently delete MyFile.txt
4. In VSCode, note file is suffixed: "MyFile.txt (deleted)"
![VSCode_DeletedFile](https://user-images.githubusercontent.com/40139623/84050493-bb94a380-a9a5-11ea-915a-9742d732a213.png)
5. Attempt to re-save file (File > Save As...)
6. Use same filename as before (MyFile.txt)
7. Note file is not saved, and no warnings given

Workaround
6a: Use a different filename than before (MyNewFile.txt)

Possibly related
[#90090](https://github.com/microsoft/vscode/issues/90090)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-jira|chi|1.1.0
xml|Dot|2.5.0
LogFileHighlighter|emi|2.8.0
vscode-peacock|joh|3.7.2
chat|kar|0.34.0
csharp|ms-|1.22.0
mssql|ms-|1.9.0
cmake-tools|ms-|1.4.0
powershell|ms-|2020.4.0
vsliveshare|ms-|1.0.2274
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
markdown-all-in-one|yzh|3.0.0

</details>

**Comment by bpasero** [comment]
Good catch indeed!
