### ISSUE TITLE
scrollbar is getting a bit misplaced when integrated trminal panel is moved to right

### ISSUE THREAD

**Issue by yashswami** [microsoft/vscode#99623]
THANK YOU AWESOME DEVELOPERS, VSCODE IS A DREAM CODE EDITOR 🎊 , keep it up 

- VSCode Version: 1.45.1
- OS Version: MacOS 10.15.5

Steps to Reproduce:

1. ctrl+shift+~ and then move the panel to the right
2. write commands in terminal till a scrollbar appears without clearing the terminal

Does this issue occur when all extensions are disabled?: haven't checked

**Comment by Tyriar** [comment]
Please provide a screenshot illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/needsMoreInfo

**Comment by Tyriar** [comment]
@yashswami hmm, I've always had difficulty reproducing these types of issues on my own. Here are some things that could help diagnose:

- A [gif](https://gifcap.dev/) showing the non bug state to the bug state
- A trace log during the repro should let me know information about resize events https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
- Inspecting the terminal element in devtools (Help > Toggle Developer Tools) to show which element is smaller than expected

**Comment by yashswami** [comment]
@Tyriar , thank you for all the suggestions but I can only afford time of showing you the gif, so here you go.

![vscode](https://user-images.githubusercontent.com/65823519/84599347-9f937500-ae71-11ea-9014-76a5a80e14e2.gif)

Happy Coding 😃

**Comment by tabaddor** [comment]
@yashswami I can't seem to reproduce this issue. Scrollbar seems to be in the intended, correct position.

**Comment by yashswami** [comment]
@tabaddor I assume that you'd have taken every step that I took to reproduce the issue, got a VSCode update a few days earlier and the issue is still there, allow me to share a GIF showing the exact shortcuts I used when the issue occurs.

![vscode](https://user-images.githubusercontent.com/65823519/85277226-5485ed00-b483-11ea-99ea-783bb92fba5a.gif)

**Comment by yashswami** [comment]
fixed in `June 2020 (version 1.47)` 

information about a detailed fix not available, but fixed.

![image](https://user-images.githubusercontent.com/65823519/87165515-8ba12e80-c2ca-11ea-9888-b7e0e80d6d9f.png)

Scrollbar is on the right side where it should be
