### ISSUE TITLE
Maybe reduce the contrast to the default dark theme.

### ISSUE THREAD

**Issue by bao007fei** [microsoft/vscode#99628]
I really love the default color scheme. But the background is too dark, and the characters are too bright. Maybe soften it a little bit. The contrast like One Dark Pro theme looks more comfortable.

**Comment by misolori** [comment]
Thanks for the feedback. You're free to check out the various themes that are in the [marketplace](https://marketplace.visualstudio.com/search?target=VSCode&category=Themes&sortBy=Installs), [modify a theme](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme), or [create your own theme](https://code.visualstudio.com/docs/getstarted/themes#_creating-your-own-color-theme) that suits your preferences.
