### ISSUE TITLE
automatically enable/disable extensions according to type of files in workspace

### ISSUE THREAD

**Issue by Rasesh2005** [microsoft/vscode#99624]
I work on Vs Code with multiple frameworks for web development like flask , django, php,etc.
i also use Vs Code for Java And C++ .. So I have their extensions too

Whenever I am Not using Any extension I have Have to disable them manually, else they are causing interruptions(Ex: While using flask all html files become Django HTML, So flask doesn't work many a times)..Can You Kindly Find Some Workaround form any of the following:
1> Extensions Should be enabled and disabled automatically based on types of files in workspace
2> Some Other Way That Extensions do Not Interfere with the workspace in which they are not invloved)

I know I can disable them manually but if some machine learning algorithm could make it happen that extensions get enabled and disabled according to the type of file in workspace

**Comment by sandy081** [comment]
/duplicate

Looks similar to https://github.com/microsoft/vscode/issues/57548 Hence tagging this as dup
