### ISSUE TITLE
Migrate requestedIndex out of the ViewContainer Descriptor

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#99626]
As introduced here: https://github.com/microsoft/vscode/pull/99503

**Comment by sandy081** [comment]
@sbatten Feel free to close if this is no longer required.

**Comment by sbatten** [comment]
I think the property still exists on `IViewContainerDescriptor` and it shouldn't. But, also, I don't think I am going to tackle this without a change in how we ensure drag and dropped view containers ensure their index.
