### ISSUE TITLE
Cannot register more than one working copy...

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#99621]
* from the vscode repo, open `.vscode/searches/es6.code-search`
* refresh and save
* open SCM viewlet
* select the code-search-file
* :bug: error happens

```
Unable to open 'es6.code-search (Working Tree)': Cannot register more than one working copy with the same resource file:///Users/jrieken/Code/vscode/.vscode/searches/es6.code-search..
```

**Comment by JacksonKearl** [comment]
Sad. This is #93745, re-introduced when I was trying to get rid of #98766. 

The real fix is probably to totally remove all direct use of the working copy service via the work we've talked about on #89268.

**Comment by JacksonKearl** [comment]
Reverted to old Stable behaviour, going to fix for real next debt week iteration.

**Comment by bpasero** [comment]
@JacksonKearl fyi it is now possible to register working copies with the same resource as others provided the `typeId` is different and not used already.

The change would have to be made here:

https://github.com/microsoft/vscode/blob/b0d5ab6aabd9ff1395530dd967526a4361748c9a/src/vs/workbench/contrib/searchEditor/browser/searchEditorInput.ts#L115-L125

This essentially allows you to use `file` (or any file system provider scheme). We can discuss what the implications are.

**Comment by bpasero** [comment]
I cannot reproduce the original issue anymore and that can probably be explained by the fact that search editor working copies seem use a URI such as `search-editor:#0.9159690262561497 ` which does not collide with any other existing working copy that uses the `file` scheme.

**Comment by jrieken** [comment]
`Math.random` ftw

**Comment by JacksonKearl** [comment]
The fix for this went in a while back but wasn't tracked, assigning to this milestone for verification.
