### ISSUE TITLE
Explorer can freeze for large folders and many glob patterns

### ISSUE THREAD

**Issue by PowerSnail** [Microsoft/vscode#9962]
- VSCode Version: 1.3.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Open a folder from visual studio code
2. In the sidebar, select a subfolder with a huge number of files (mine has over 70000 json files)

Then the window will just freeze. No response to click or keyboard whatsoever, until after a while the system reports that "The Window is no longer responding". 

Thank you!

**Comment by bpasero** [comment]
Tree performance...

**Comment by bpasero** [comment]
This cannot be important because we shipped with this for years.

**Comment by bpasero** [comment]
When I open the tests/baseline folder of the TypeScript workspace (it includes 18000 files) it takes 30 seconds to show the contents (not seeing any progress during which, filed https://github.com/Microsoft/vscode/issues/10459).

@joaomoreno most time seems to be spend in the treeModel#Item() function, can you take a look? The profile is here: [explorer.cpuprofile.zip](https://github.com/Microsoft/vscode/files/414652/explorer.cpuprofile.zip)

One thing to note is that the explorer is not using templates yet but I would not expect that to be a problem for 18.000 elements where most of them show hidden. Only a problem when quickly scrolling through the results.

**Comment by joaomoreno** [comment]
Just comment out [this section](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerViewer.ts#L685-L690) and you'll get rid of the UI performance bottleneck. And obviously so: every filter call is going through all the sibling files, for every file, making this `O(n²)`.

It immediately becomes more responsive, although it still takes ~5 seconds on my machine. Most of that time is spent on the file service and the file viewer classes: 

![screen shot 2016-08-15 at 12 53 10](https://cloud.githubusercontent.com/assets/22350/17662642/414c7868-62e7-11e6-8724-f7dc880091e0.png)

**Comment by bpasero** [comment]
I pushed a fix that avoids the O(n^2) issue for most cases but if the user has configured a filter pattern where I need to know the siblings (`"**/*.js": { "when": "$(basename).ts" }`) we still run into the performance issue, so I am leaving this open.

**Comment by bpasero** [comment]
Pushed another fix to ignore glob patterns that need to check on siblings when the number of files in a folder exceed a threshold.

Expanding the typescript/test/baseline folder with 16.000 files still takes 3-4 seconds but is much better compared to the 30-60 seconds we used to have. Closing.
