### ISSUE TITLE
No way to select text with touch screen

### ISSUE THREAD

**Issue by rualark** [microsoft/vscode#99620]
- VSCode Version: 1.45.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Double click on text to select : text is not selected
2. Double click and drag to select: no text is selected

Does this issue occur when all extensions are disabled?: Yes

**Comment by lucloner** [comment]
same problem with touch screen.
i cannot click terminal selection either output!

**Comment by rualark** [comment]
> same problem with touch screen.
> i cannot click terminal selection either output!

Hi. Seems you need to upvote if you want this to be fixed.
