### ISSUE TITLE
Behavior of arrow keys in References in sidebar

### ISSUE THREAD

**Issue by kerzhner** [microsoft/vscode#99633]
I am a big fan of the References tab in the sidebar. I find that to show a reference in the code editor I have to either click on the reference or navigate to the reference using arrow keys and press enter.

Is it possible to change the behavior (or add a setting) to automatically show the reference in the code editor when the user navigates via arrow keys (without having to press enter/return).

Here is a gif of the current behavior:
![current behavior](https://user-images.githubusercontent.com/1062379/84068921-904a8e00-a97e-11ea-97ba-15fb55c632d8.gif)

Here are the detials of my application:
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Comment by jrieken** [comment]
The default is like this

* arrow keys navigate but don't change focus
* F4/Shift+F4 navigate _and_ change focus (that's what you want)

These keybindings match the defaults, e.g how search works, but you can cutomize them as you like.

**Comment by kerzhner** [comment]
Appreciate you pointing me to the right place @jrieken!
