### ISSUE TITLE
black flashlight

### ISSUE THREAD

**Issue by galllo83** [microsoft/vscode#99636]
Issue Type: <b>Performance Issue</b>

when i type or passing the mouse over the menus i have a black flashligth  and turns to slow to type or view changes

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (7.17GB free)|
|Process Argv|-psn_0_417894|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   14	    98	  2048	code main
    7	    98	  2049	   gpu-process
    0	    16	  2050	   utility
    4	    98	  2058	   shared-process
    0	     0	  2370	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   213	  2357	   window (Welcome)
    0	    82	  2359	     extensionHost
    5	    82	  2368	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-intelephense-client|bme|1.4.1
vue|jcb|0.1.5
color-highlight|nau|2.3.0
vetur|oct|0.24.0
color-vision|wil|0.1.0

</details>

**Comment by mxrachel** [comment]
Could you post a screenshot or gif?

**Comment by galllo83** [comment]
![IMG_3035 2(1)](https://user-images.githubusercontent.com/45882441/84166163-25f72380-aa3a-11ea-9eea-61c70ffda1fa.gif)

**Comment by deepak1556** [comment]
@galllo83 does the issue happen when you run with  `--disable-extensions` ?
