### ISSUE TITLE
Ruby Rails "The active editor cannot provide outline information"

### ISSUE THREAD

**Issue by ridhwaans** [microsoft/vscode#99631]
VSCode says "The active editor cannot provide outline information" for any .rb file, test, rails or ruby class.
However the outline works for python files and javascript files when they are open.
I installed some Ruby extensions off the VSCode marketplace but they did not bring the outline to work. How do I achieve that?

- VSCode Version: latest
- OS Version: Windows 10 version 2004

Steps to Reproduce:

1. Open any Rails project folder
2. Outline is blank for .rb code

Does this issue occur when all extensions are disabled?: Yes
Does this issue occur inside and outside of remote-wsl window?: Yes

**Comment by jrieken** [comment]
> I installed some Ruby extensions off the VSCode marketplace but they did not bring the outline to work. How do I achieve that?

I depends on the extension, they might support the outline feature or not. Unfortunately I am not a ruby expert but search for ruby language service might get yo there
