### ISSUE TITLE
How to get access to the application window from an extension

### ISSUE THREAD

**Issue by jots** [Microsoft/vscode#9963]
How can we access the window object from an extension?
I would like to create a canvas over the window such as is done in this code:
https://github.com/disjukr/activate-power-mode/blob/gh-pages/src/index.js

```javascript
var canvas = document.createElement('canvas');
canvas.width = window.innerWidth;
canvas.height = window.innerHeight;
canvas.style.cssText = 'position:fixed;top:0;left:0;pointer-events:none;z-index:999999';
window.addEventListener('resize', function () {
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
});
document.body.appendChild(canvas);
```
Would also like to place some globally accessible `<audio>` tags in vscode that my extension can play when events fire.  Just need to know how to access the global "window" or "document" so can stash them for use.

**Comment by kieferrm** [comment]
The current API doesn't give you unfiltered access to dom elements.

**Comment by jrieken** [comment]
There are no plans to give access to the dom for various reasons explained here: https://code.visualstudio.com/docs/extensions/our-approach

**Comment by JCMais** [comment]
@jrieken I was searching for something similar, and found this issue.

So if I want to know the current mouse position inside a TextDocumentContentProvider, it's not possible?

Scope: Trying to add an uniform with the current mouse position to a GLSL shader previewer.
