### ISSUE TITLE
Edit object type settings from the settings GUI

### ISSUE THREAD

**Issue by 9at8** [microsoft/vscode#99635]
A lot of settings expose configuration in the form of simple non-nested objects. It will be useful to explore different ways to expose editing functionality for these kinds of objects in the GUI.

| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/8235156/84073344-9fd9cf00-a99e-11ea-8014-7e0f79348775.png) | ![image](https://user-images.githubusercontent.com/8235156/84816149-0cc61800-afe2-11ea-8a62-655ed3468e42.png) |

---

Non-nested objects can be broadly put in three different categories:

1. Static Objects
    - All properties are defined using the [`properties` keyword](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.9.3.2.1) and default values for all properties are defined.
    - All the properties along with their default values are rendered in the GUI in a tabular format.
    - No additional properties may be added.
    - None of the existing properties can be removed. Instead, each property can be reset to its default value.
2. Dynamic Objects
    - Properties can only be defined using and the [`patternProperties` keyword](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.9.3.2.2) and [`additionalProperties` keyword](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.9.3.2.3), and **NOT** the [`properties` keyword](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.9.3.2.1).
3. A mix of static and dynamic objects
    - These contain statically defined [`properties` keyword](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.9.3.2.1), and at least one of [`patternProperties` keyword](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.9.3.2.2) and [`additionalProperties` keyword](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.9.3.2.3).

## Requirements ✅ 

- [x] Optimistic UI - setting should update when immediately, rather than just firing the change event, and waiting for the data to flow in.

### Static Objects

- [x] Show all keys with their default value
- [x] Show a revert to default value button
- [x] Hide the 'Add Item' button
- [x] Keys should not be editable

### Dynamic Objects

- [x] Show all the configured pairs
- [x] Show the 'Add Item' button
- [x] Show the remove button
- [x] New value widget should match `additionalProperties` / `patternProperties` type

## Some unknowns 🤔 

- Should we limit the number of settings that are shown in the GUI? 10 pairs are fine, but what about 100 pairs? Do such settings exist?
- Should we show a blue bar beside each pair that's edited? (just like other settings)
- What should validators look like? Should key-value pairs be validated individually?
- How should boolean values be rendered?
  - If an object has all values of type `boolean`, then we should render checkboxes, just like everywhere else in the settings UI.
  - What if an object has a mixture of `boolean` values and other primitives?
- Should an autocomplete be shown when adding a new key-value pair?

## Impacted Settings ⚙️ 

- `files.associations`
- `emmet.includeLanguages`
- `emmet.variables`

This is not a complete list. Settings that have type `object` and define either `properties`, `patternProperties` or `additionalProperties` as a non-nested object might be impacted.

# Prototypes

You can play around with the setting by using the insiders build of VSCode.

## Latest Prototypes (in insiders)

Example from the [go extension](https://github.com/golang/vscode-go/blob/master/package.json#L939):

![image](https://user-images.githubusercontent.com/8235156/84815968-cf618a80-afe1-11ea-8db7-fbadd4b9038d.png)

Example: [`files.associations`](https://github.com/microsoft/vscode/pull/99642/files#diff-b6af4d695e324d217307b3938493f2eeR241)

![image](https://user-images.githubusercontent.com/8235156/84816124-046ddd00-afe2-11ea-9693-ca378a5896ec.png)

## Old prototypes

Example from the [go extension](https://github.com/golang/vscode-go/blob/master/package.json#L939):

![image](https://user-images.githubusercontent.com/8235156/84308066-e7419600-ab2b-11ea-9818-3ac9590e71a8.png)

Example: [`files.associations`](https://github.com/microsoft/vscode/pull/99642/files#diff-b6af4d695e324d217307b3938493f2eeR241)

![image](https://user-images.githubusercontent.com/8235156/84073399-b849e980-a99e-11ea-9a61-05c30ae5fe86.png)

cc: @roblourens

**Comment by JacksonKearl** [comment]
You'll want to explicitly add a Milestone to every feature-request or else the bot will auto-assign it to our `candidate` milestone.

**Comment by savannahostrowski** [comment]
@9at8 With this work, would it be possible to render enums values as a dropdown in the UI? For my specific use case, this would make the UX much better by preventing users from having to read external documentation.

In an ideal case, the keys would be hard-coded in the UI for that setting, and the values would be dropdowns.

**Comment by 9at8** [comment]
@savannahostrowski yes!
