### ISSUE TITLE
Find in files occasionally hangs

### ISSUE THREAD

**Issue by blake-fisher** [microsoft/vscode#99634]
Issue Type: <b>Bug</b>

For a few weeks now, my find in files commands will hang ~25% of the time, and only give me results from files I currently have open. I've waited for results for up to ~30m, and they never return and my search window continues showing a spinner. If I search again the results will usually show up very quickly.

I've enabled trace logging, and it looks like in cases where the search hangs I don't ever get a line indicating the `rg` command that is used to handle my search. I don't see any exceptions or errors in the log or in developer tools.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|47.90GB (26.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
xml|Dot|2.5.0
ts-arrange2|DrM|2.0.4
gitlens|eam|10.2.1
tslint|eg2|1.0.44
prettier-vscode|esb|5.0.0
docthis|joe|0.7.1
import-sorter|mik|3.3.1
debugger-for-chrome|msj|4.12.8
debugger-for-edge|msj|1.0.14

</details>

**Comment by mxrachel** [comment]
Could you include a copy of the trace log?

**Comment by blake-fisher** [comment]
[trace.txt](https://github.com/microsoft/vscode/files/4754675/trace.txt)

The first search, for 'test', completed successfully. The second search, for 'anotherTest', is still spinning.

**Comment by roblourens** [comment]
Debugged this with a screen share, found that the last search finishes with a "cancelled" error. Disabling searchOnType fixed it. I think what the log shows is that search was triggered 4 times. 3 of them finished. The last 2 are triggered with the same query. The first one of those is cancelled, the second I guess never goes anywhere. Not sure whether it's the wrong search getting cancelled or something.

@JacksonKearl any ideas?

Also I'm pushing a change to make sure that the error message gets logged.

**Comment by JacksonKearl** [comment]
This is odd, I haven't been able to reproduce it locally, either manually or by explicitly adding code to fire off many searches in quick succession. Is there a repository&query that this happens in that you could share?

**Comment by blake-fisher** [comment]
Oh, sorry I missed this message @JacksonKearl! This happens for me for every repository and query that I run. It persists across version updates, and still happens if I reload with extensions disabled. I can even reproduce it by running a search out of an empty folder.

It looks like this is caused by the 'search.maintainFileSearchCache' setting - as soon as I turn that off the issue goes away, and I can reproduce the issue on a different machine by turning the setting on.

**Comment by roblourens** [comment]
Another user hit a similar issue in https://github.com/microsoft/vscode/issues/101524 and the same setting was behind it, and I realized that setting is actually broken and will do the wrong thing. I recommend just disabling it

**Comment by connor4312** [comment]
Verified by reading through code, not sure how to repro locally
