### ISSUE TITLE
dark mode: unchecked checkboxes are hard to see

### ISSUE THREAD

**Issue by mariusa** [microsoft/vscode#99648]
- VSCode Version: 1.45.1-1589445456.el7.x86_64
- OS Version: Fedora 31

Steps to Reproduce:

1. open Settings, search 'ident' (or others with checkboxes)
2. checkboxes are hard to see. When unchecked, it's not clear there's a checkbox there:
![Screenshot from 2020-06-09 09-44-48](https://user-images.githubusercontent.com/1283842/84114955-e3cbe300-aa35-11ea-96f2-22a50beba567.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
It's not great but I think it's acceptable as a default, and it can be customized by the user if needed.
