### ISSUE TITLE
Support sending some commands to syntax TS Server while a project is loading

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#99643]
## Problem
VS Code runs two TS servers for our JavaScript and TypeScript support:

- Syntax Server. Use for basic syntax related operations, such as outline, auto closing tags, etc. Only loads the current file

- Semantic server. Used for more advanced operations such as errors and intellisense. Requires loading the entire project

For larger projects, the semantic server can take time to load the entire project and start providing  responses. While the project is loading, the user does not get any IntelliSense.

Here's the state of things today:

| *Stage*   | *Syntax Operations (Outline)* | *Semantic Operations (IntelliSense)* |*Diagnostics* |
|---------|-----------------------------|------------------------------------|-------------|
| Loading | Full                            |  None                                  | None            |
| Loaded  | Full                            | Full                                   |  Full           |

## Proposal
We'd like to explore improving the UX while a project is loading by letting the syntax server handle basic semantic operations until the project has been fully loaded:

| *Stage*   | *Syntax Operations (Outline)* | *Semantic Operations (IntelliSense)* |*Diagnostics* |
|---------|-----------------------------|------------------------------------|-------------|
| Loading | Full                            |  **Partial**                                  | None            |
| Loaded  | Full                            | Full                                   |  Full           |

While loading is happening, we plan to use the syntax server to implement semantic operations such as hover and IntelliSense.

The key limitation of this approach is that the syntax server only knows about the current file, so it will not be able to provide complete results. For example,  IntelliSense would only include suggestions from the current file and would not be able to support auto imports

**Comment by mjbvz** [comment]
See https://github.com/microsoft/TypeScript/pull/38564 for the TS work on this

480c98f1abcb90cb77da7ed7b182a812f9498581 should enabled this in VS Code (you'll need to wait for the first VS Code 1.47 insiders build). To enable this, just set `"typescript.tsserver.useSeparateSyntaxServer": "dynamic"`. You'll also need to be using a supported TS build

/cc @sheetalkamat @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
Nice! (@amcasey) 

Just to be clear, it looks like it's not just intellisense/completions, right? It looks like the syntax server will basically handle every operation except for diagnostics:

https://github.com/microsoft/vscode/commit/480c98f1abcb90cb77da7ed7b182a812f9498581#diff-f647ee692cab93fdf6b2650168d3f315R530-R533

**Comment by mjbvz** [comment]
Yes, during project load syntax server should now get every command except the diagnostic ones and `projectInfo`

**Comment by amcasey** [comment]
We probably don't want any of the compile-on-save commands to go to the syntax server.

**Comment by amcasey** [comment]
Organize imports can only mangle things.  Personally, I'd also drop semantic classification (e.g. class vs interface) since I don't think a guess is better than nothing (e.g. just knowing its a type).

**Comment by DanielRosenwasser** [comment]
I'm not able to see things working better. I've

* installed the latest VS Code Insiders assuming it has commit https://github.com/microsoft/vscode/commit/480c98f1abcb90cb77da7ed7b182a812f9498581
* set `"typescript.tsserver.useSeparateSyntaxServer": "dynamic",`
* installed this TypeScript build: https://github.com/microsoft/TypeScript/pull/38561#issuecomment-641468803

**Comment by mjbvz** [comment]
@DanielRosenwasser You need to be on the VS code 1.47 insiders builds which have not been released yet. They should come out once we ship the stable version of VS Code 1.46

**Comment by DanielRosenwasser** [comment]
D'oh - thanks! By the way, I (like @amcasey) tried out the syntax-only server and the results are pretty great already. Very excited to see how this works out.

**Comment by mjbvz** [comment]
To verify this:

1. In the VS Code workspace.
1. Make sure you are using the workspace version of TypeScript (4.0)
1. Go into a TS file into a core VS Code project
1. Reload the VS Code window
1. You should see the `Initializing JS/TS language features` spinner in the status bar
1. While this is happening, try some basic operations in a file:

     - Hover
     - Suggest
     - Go to definitions
     
Keep in mind that these operations only look at the current file while the project is loading. Confirm that once the project loads, you start getting full results
