### ISSUE TITLE
Missing esc key on mac touchbar

### ISSUE THREAD

**Issue by brianwestphal** [microsoft/vscode#99647]
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (3 wks ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:

1. bring up autocomplete menu, use command-p or any popup menu
2. there's no esc key that can be used to dismiss the popup

Does this issue occur when all extensions are disabled?: Yes

![IMG_9957](https://user-images.githubusercontent.com/7001863/84111536-b85aef80-aa59-11ea-875b-621d4b8025e4.JPG)

**Comment by bpasero** [comment]
I suggest you report this to Apple itself, I do not think every app adds its own "ESC" key.

Btw newer macbookPro models have a physical ESC key :)

**Comment by brianwestphal** [comment]
@bpasero Since vscode is setting its own touchbar icons, the ones specified by vscode are being used.  I don't think this is an OS bug, it's just that vscode, being a programming tool, can benefit from an escape key -- where as most app withs custom touchbar icons, don't really need an escape key.  Those arrows in my initially attached image are not standard OS controls, they're for vscode.

The workaround is to change "Touch Bar shows" to "Expanded Control Strip" instead of the default "App Controls".  But that's a global setting, which doesn't actually make sense to use a fix here.

<img width="351" alt="Screen Shot 2020-06-10 at 8 30 45 AM" src="https://user-images.githubusercontent.com/7001863/84214051-dd507080-aaf4-11ea-8417-c23af5680e57.png">

**Comment by mattkrick** [comment]
after upgrading to the latest i swore the escape key just went missing. got frustrating because there was no good way to close the intellisense popup.

turn out it was a problem with macos. fixed it with `sudo pkill TouchBarServer`

**Comment by brianwestphal** [comment]
@mattkrick thanks!  and @bpasero I stand corrected, guess this is an OS issue.  Will file a radar

**Comment by ghs** [comment]
Before the weekend I finally applied the latest update/upgrade and today while typing some code felt something is missing and things were behaving weirdly... And indeed the "esc" key was missing. Made exactly the same photo as above but saw this issue here :)

As @mattkrick suggested, killing the touch bar worked, but all other apps had their proper touch bar settings except vscode...
