### ISSUE TITLE
VSCode does not recognize the color scheme theme file that I created.

### ISSUE THREAD

**Issue by CHRIBUR0309** [microsoft/vscode#99645]
I copied a folder of an existing color scheme theme file and renamed the folder name, the file name, and the color scheme name within the file. However, even though I restarted VSCode, the theme is not listed in the color scheme themes list and cannot be applied.

**Comment by gjsjohnmurray** [comment]
https://code.visualstudio.com/api/extension-guides/color-theme#create-a-new-color-theme
