### ISSUE TITLE
Follow symlinks doesn't work in search

### ISSUE THREAD

**Issue by richardbladh** [microsoft/vscode#99657]
- VSCode Version: 1.45.1
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

Follow Symlinks ("search.followSymlinks": true) doesn't work in search (CTRL+SHIFT+F).

I have a folder that contains multiple subfolders. Some of them are "real" folders and some are symlinks created using "mklink /J [Name] [Target]".
I start VS code from the root folder.

I can browse the symlink folders in the VS Code explorer without any problems and if I bring up a file from a symlink folder in the editor its content is searched as expected.
But as soon as I close the same file and perform the same search no hits are found in files that are in symlink folders (hits in files in normal folders are included in the result).

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
This works fine for me. Can you check whether exclude patterns or .gitignore could be keeping vscode from searching those files? https://github.com/microsoft/vscode/wiki/Search-Issues

**Comment by richardbladh** [comment]
You are absolutely right!
It was the .gitignore file that excluded the entire folders.

There is a reason however for our setup and that is to have a kind of view for certain projects, i.e. by having a frontend root folder that sums up all the frontend projects distributed over our entire solution (via symlinks). In the frontend folder however we also have "real" folders with projects in it.

So I guess there is no good solution here, but it's good to know why it behaves like it does!

Thank you for your help!

**Comment by roblourens** [comment]
You can tell search to not use the gitignore files by setting `"search.useIgnoreFiles": true`, if that helps. Or if there's something else that make you scenario work better, let me know.

**Comment by sandipb** [comment]
![Screen Shot 2020-06-19 at 12 37 41 PM](https://user-images.githubusercontent.com/105359/85174178-b3502a00-b229-11ea-8c6e-a14a72eec8ac.png)

I wonder what is the difference between these two pretty similar configs.
