### ISSUE TITLE
Limit text ripping in "rename symbol" function (F2) or "change all occurences" function (Ctrl+F2)

### ISSUE THREAD

**Issue by FALLAI-Denis** [microsoft/vscode#99651]
When a symbol is renamed, or a text is changed, with a shorter or longer name, or text, this causes all the text placed to its right to be shifted either to the left if the new name, or text, is shorter than the old one, or to the right if the new name, or text, is longer than the old one.

If the text of several lines has been aligned, or if we use a programming language which requires placing the text in precise locations (we use Cobol and Assembler for a mainframe platform), these shifts no longer respect the alignments implemented, or for languages which require respecting positions this can lead to compilation errors.

We propose that an "intelligent" shift system be implemented:
- if the new symbol name, or new text, is shorter than the old one, the text placed to its right is shifted to the left until a sequence of at least 2 spaces is encountered, from this point no shift of text is done to the left
- if the new symbol name, or new text, is longer than the old one, the text placed to its right is shifted to the right, reducing the number of spaces to keep only 1 until it is no longer need to shift right, that is, the existing text can remain in its position.

In order not to create a problem with the current behavior, this function could be controlled by a new option, which should be able to be associated with a language mode. This options would specify the minimum number of spaces to keep during text shifts in the event of renaming of symbols or replacing text.

Example: limit compression of spaces to only 1 (or n) space, expand spaces as soon as more than 1 (or n) space
```
"[langueid]": {
  "editor.smartshift": 1
  }
```
A value of 0 would disable the functionality.

Use case: 

Starting state
![SmartShift01](https://user-images.githubusercontent.com/63861965/84121218-22ae6880-aa37-11ea-846e-693881a07758.png)

Rename symbol "MIDDLE-NAME" to "AHAH"
![SmartShift02](https://user-images.githubusercontent.com/63861965/84121353-5be6d880-aa37-11ea-83ef-24661d4507a9.png)
the new symbol is shorter, the text is shifted to the left: the text is no longer aligned and the area in column 73 is shifted to the left which would trigger a compilation error.

Expected result:
![SmartShift03](https://user-images.githubusercontent.com/63861965/84121748-d7488a00-aa37-11ea-913b-f0c619e593c0.png)

Rename symbol "SHORNAME" to "A-LONGER-NAME"
![SmartShift04](https://user-images.githubusercontent.com/63861965/84121944-09f28280-aa38-11ea-924a-03e3209d1c6b.png)
the new name is longer, the text is shifted to the right: the text is no longer aligned and the area in column 73 is shifted to the right which would trigger a compilation error.

Expected result:
![SmartShift05](https://user-images.githubusercontent.com/63861965/84122126-3efed500-aa38-11ea-96ea-fff22eb76fcc.png)

**Comment by jrieken** [comment]
TBH I think there is low chances that vs code itself will support this. To me this seems like a perfect use for a COBOL formatter extension which is doing these kind of things. Or a source code action which is making this alignment "fixes"

**Comment by FALLAI-Denis** [comment]
Thanks for your feedback.

I think that the functionality does not only concern the "columned" languages inherited from the 80 column card format.
It can also concern more "modern" languages: the search and replace functions must keep the alignments that the developer has been able to set up to facilitate the reading of his code.
What identifies the presence of an alignment is the fact that several spaces (or tabulations) are present between words of the same line.
This can also concern data files.
