### ISSUE TITLE
Clean up legacy/migration code in workspaces

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#99653]
I think during support for remote in workspaces land, many properties got added and some deprecated. I am having a hard time seeing through:

![image](https://user-images.githubusercontent.com/900690/84121737-d31c6c80-aa37-11ea-9675-9ba4328f3466.png)

I suggest to make a cleanup pass, there maybe more...

**Comment by aeschli** [comment]
Yes, we can remove the old versions now.

**Comment by bpasero** [comment]
Thanks 🙏

**Comment by bpasero** [comment]
Unclear to me what to verify here?

**Comment by aeschli** [comment]
I guess just check that the code is gone. Or is there a way to say that an issue doesn't need verification?

**Comment by bpasero** [comment]
If the issue is not marked as "feature request" or "bug" it should be fine.
