### ISSUE TITLE
Keyboard shortcuts don't work when PDF-Viewer is focused

### ISSUE THREAD

**Issue by frederictobiasc** [microsoft/vscode#99655]
Issue Type: <b>Bug</b>

1. Open a PDF-file
2. Try keyboard shortcuts (e.g. CTRL+Shift+P, F1)

This occurs since I updated from 1.44.2

VS Code version: Code - OSS 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-17T22:31:53.325Z)
OS version: Linux x64 5.6.15-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.40GB (6.64GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.3.0
meson|asa|1.3.0
xml|Dot|2.5.0
latex-workshop|Jam|8.10.0
language-julia|jul|0.15.40
sftp|lix|1.12.9
markdown-shortcuts|mdi|0.12.0
python|ms-|2020.5.86398
cpptools|ms-|0.28.2
java|red|0.62.0
vscode-hexdump|sle|1.7.2
dot|Ste|0.0.1
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.0.0

</details>

**Comment by mjbvz** [comment]
Please start by filing this against whichever extension provides pdf viewing
