### ISSUE TITLE
Nested snippets not working in editor

### ISSUE THREAD

**Issue by Cheenu2811** [microsoft/vscode#99660]
- VSCode Version: 1.45.1
- OS Version: Windows

Steps to Reproduce:

1. Create 2 or more snippets with at least one tabstop other than $0
2. Try using another snippet when at a tabstop of an snippet other than $0

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by ArturoDent** [comment]
Please show your two snippets.  It generally does work to do what you are saying, I believe without seeing your snippets.  

Try disabling this setting:

>   // Controls whether an active snippet prevents quick suggestions.
>   "editor.suggest.snippetsPreventQuickSuggestions": false,    // default is true

and see if it works how you want.  When you get to `$0`, the snippet is no longer "active" and hence your next snippet prefix is recognized even with that setting set to `true`.  `false` might fix it for you - please report back.

**Comment by Cheenu2811** [comment]
Thank you this fixed my issue!
