### ISSUE TITLE
"Rename Symbol": Refactor failed due to "%matplotlib qt" syntax error

### ISSUE THREAD

**Issue by PrateekArya** [microsoft/vscode#99667]
Issue Type: <b>Bug</b>

Steps:
1. Create a '.py' file
2. Write "%matplotlib qt" in a new line.
3. Try "Rename Symbol" for any variable.

Sample code in 'abc.py':
%matplotlib qt
x = 10

Error while doing "Rename Symbol" x:
Refactor failed. Syntax error in file <abc.py> line <1>: invalid syntax
[<FrameSummary file c:\Users\prateekg\.vscode-insiders\extensions\ms-python.python-2020.5.86398\pythonFiles\refactor.py, line 382 in watch>, <FrameSummary file c:\Users\prateekg\.vscode-insiders\extensions\ms-python.python-2020.5.86398\pythonFiles\refactor.py, line 352 in _process_request>, <FrameSummary file c:\Users\prateekg\.vscode-insiders\extensions\ms-python.python-2020.5.86398\pythonFiles\refactor.py, line 260 in _rename>, <FrameSummary file c:\Users\prateekg\.vscode-insiders\extensions\ms-python.python-2020.5.86398\pythonFiles\refactor.py, line 129 in refactor>, <FrameSummary file c:\Users\prateekg\.vscode-insiders\extensions\ms-python.python-2020.5.86398\pythonFiles\refactor.py, line 156 in onRefactor>, <FrameSummary file C:\Users\prateekg\AppData\Local\Continuum\anaconda3\lib\site-packages\rope\refactor\rename.py, line 23 in __init__>, <FrameSummary file C:\Users\prateekg\AppData\Local\Continuum\anaconda3\lib\site-packages\rope\base\project.py, line 116 in get_pymodule>, <FrameSummary file C:\Users\prateekg\AppData\Local\Continuum\anaconda3\lib\site-packages\rope\base\pycore.py, line 142 in resource_to_pyobject>, <FrameSummary file C:\Users\prateekg\AppData\Local\Continuum\anaconda3\lib\site-packages\rope\base\pycore.py, line 255 in get_pymodule>, <FrameSummary file C:\Users\prateekg\AppData\Local\Continuum\anaconda3\lib\site-packages\rope\base\pyobjectsdef.py, line 162 in __init__>, <FrameSummary file C:\Users\prateekg\AppData\Local\Continuum\anaconda3\lib\site-packages\rope\base\pyobjectsdef.py, line 191 in _init_source>]

VS Code version: Code - Insiders 1.46.0-insider (9f89da69154ac6c99dfa7c82986e2df95b7bbe0b, 2020-06-08T22:10:54.220Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.84GB (52.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlab-workflow|fat|2.2.0
code-runner|for|0.10.0
matlab|Gim|2.0.0
gc-excelviewer|Gra|2.1.35
latex-workshop|Jam|8.10.0
nbpreviewer|jit|1.2.2
r|Mik|0.0.8
python|ms-|2020.5.86398
remote-wsl|ms-|0.44.2
vscode-data-preview|Ran|2.0.0
code-spell-checker|str|1.9.0

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by PrateekArya** [comment]
I have updated the issue with additional details. Let me know if I you need any further information. :)
