### ISSUE TITLE
Remove usages of values- and keys-utils

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#99664]
We have utilities to get all [values](https://github.com/microsoft/vscode/blob/0f1540e7ad050d0cf895da1f2075a60f263c756d/src/vs/base/common/map.ts#L17) or [key](https://github.com/microsoft/vscode/blob/0f1540e7ad050d0cf895da1f2075a60f263c756d/src/vs/base/common/map.ts#L26) from ES6 maps. Since we are actually targeting ES6 at runtime these utils aren't needed anymore and you should just use `someMap.keys()` or `someMap.values()`

- [x] src/vs/base/browser/ui/tree/abstractTree.ts @joaomoreno
- [x] src/vs/base/browser/ui/tree/asyncDataTree.ts @joaomoreno
- [x] src/vs/base/common/resourceTree.ts @joaomoreno
- [x] src/vs/editor/common/modes/tokenizationRegistry.ts @alexdima
- [x] src/vs/editor/common/services/markerDecorationsServiceImpl.ts @sandy081
- [x] src/vs/platform/configuration/common/configurationModels.ts @sandy081
- [x] src/vs/platform/configuration/common/configurationRegistry.ts @sandy081
- [x] src/vs/platform/contextkey/browser/contextKeyService.ts @alexdima
- [x] src/vs/platform/extensionManagement/common/extensionGalleryService.ts @sandy081
- [x] src/vs/platform/extensionManagement/common/extensionTipsService.ts @sandy081
- [x] src/vs/platform/keybinding/common/keybindingResolver.ts @alexdima
- [x] src/vs/platform/url/common/urlService.ts @joaomoreno
- [x] src/vs/platform/userDataSync/common/extensionsMerge.ts @sandy081
- [x] src/vs/platform/userDataSync/common/extensionsMerge.ts @sandy081
- [x] src/vs/platform/userDataSync/common/globalStateMerge.ts @sandy081
- [x] src/vs/platform/userDataSync/common/keybindingsMerge.ts @sandy081
- [x] src/vs/platform/userDataSync/common/keybindingsMerge.ts @sandy081
- [x] src/vs/platform/userDataSync/common/settingsMerge.ts @sandy081
- [x] src/vs/platform/userDataSync/common/snippetsMerge.ts @sandy081
- [x] src/vs/platform/userDataSync/common/storageKeys.ts @sandy081
- [x] src/vs/workbench/api/browser/mainThreadComments.ts @rebornix
- [x] src/vs/workbench/api/browser/mainThreadSearch.ts @roblourens
- [x] src/vs/workbench/common/views.ts @sbatten
- [x] src/vs/workbench/common/views.ts @sbatten
- [x] src/vs/workbench/contrib/comments/common/commentModel.ts @rebornix
- [x] src/vs/workbench/contrib/extensions/browser/configBasedRecommendations.ts @sandy081
- [x] src/vs/workbench/contrib/extensions/browser/extensionsDependencyChecker.ts @sandy081
- [x] src/vs/workbench/contrib/files/browser/views/explorerView.ts @isidorn
- [x] src/vs/workbench/contrib/search/common/queryBuilder.ts @roblourens
- [x] src/vs/workbench/contrib/search/common/searchModel.ts @roblourens
- [x] src/vs/workbench/services/extensions/common/extensionsRegistry.ts @alexdima 
- [x] src/vs/workbench/services/extensions/electron-browser/remoteExtensionManagementIpc.ts @alexdima
- [x] src/vs/workbench/services/log/common/inMemoryLogProvider.ts  @sandy081
- [x] src/vs/workbench/services/log/common/keyValueLogProvider.ts @sandy081
- [x] src/vs/workbench/services/preferences/common/preferencesModels.ts @sandy081
- [x] src/vs/workbench/services/preferences/common/preferencesModels.ts @sandy081
- [x] src/vs/workbench/services/search/common/searchService.ts @roblourens
- [x] src/vs/workbench/services/search/common/searchService.ts @roblourens
- [x] src/vs/workbench/services/userDataSync/browser/userDataSyncWorkbenchService.ts @sandy081
- [x] src/vs/workbench/services/views/common/viewContainerModel.ts @sbatten
- [x] src/vs/workbench/services/search/common/searchService.ts @roblourens 
- [x] src/vs/workbench/contrib/comments/common/commentModel.ts @rebornix

**Comment by jrieken** [comment]
fyi - more obsolete utils can be found with this search editor-file: `.vscode/searches/es6.code-search`

**Comment by sandy081** [comment]
@rebornix @roblourens Since there were only last two usages left each from you, cleaned them up myself.

**Comment by sandy081** [comment]
@jrieken Also removed these utils as there are no longer usages of these in code.

**Comment by jrieken** [comment]
👏
