### ISSUE TITLE
Python Environment + Terminal focus not working when key binding is used for workbench.action.terminal.new

### ISSUE THREAD

**Issue by jd-0001** [microsoft/vscode#99662]
- VSCode Version:
- OS Version:
```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.6.2-050602-generic
```

Steps to Reproduce:

1. Bind keyboard shortcut to open new terminal
2. Wait till virtual environment is applied by VS Code
3. Try to type

Does this issue occur when all extensions are disabled?: Yes/No

As the extension is the disabled environment is no longer activated hence this issue **doesn't occur**.

**Comment by kimadeline** [comment]
Hi @Tyriar, 

We have a command in the Python extension to create a terminal, and apparently it doesn't cause that issue (see https://github.com/microsoft/vscode-python/issues/12224#issuecomment-644697780).

We create and show the terminal by:
- calling `terminal = window.createTerminal(options)`
- activating the terminal 
- and then calling `terminal.show(false)`

What does the `workbench.action.terminal.new` command do that the `window.createTerminal()`+``terminal.show(false)` combo doesn't?

**Comment by kimadeline** [comment]
When a terminal is created via the `python.createTerminal` command `preserveFocus` is always set to `false` (in https://github.com/microsoft/vscode-python/blob/61b179b2092050709e3c373a6738abad8ce581c4/src/client/providers/terminalProvider.ts#L50)

**Comment by Tyriar** [comment]
@kimadeline I thought the issue here was about creating via the `workbench.action.terminal.new` command? I was thinking it could be caused by the virtual environment code running and potentially messing with focus after the `onDidCreateTerminal` event fires?

**Comment by kimadeline** [comment]
Oh sorry I was looking at the wrong spot! Yes you are right, `preserveFocus` is `undefined` when the activation commands are being sent when creating via `workbench.action.terminal.new`. But that shouldn't be a problem, right? since the documentation says 

> param preserveFocus When `true` the terminal will not take focus.


Even if we were changing focus, I don't understand why it would happen only sometimes, and not for all calls to `workbench.action.terminal.new`. We listen to `vscode.window.onDidOpenTerminal`, should it be something else?
