### ISSUE TITLE
Jest test with moduleNameMapper not recognised the parent class methods used in child classes

### ISSUE THREAD

**Issue by jafs** [microsoft/vscode#99673]
- VSCode Version: 1.45.1
- OS Version: Windows_NT x64 10.0.18363
- Node version: 12.16.3

Steps to Reproduce:

1. We have a parent class code:
```
export default class ParentClass {
  public parentMethod(): void {
  }
}
```
2. Also a child class with code:
```
import ParentClass from "pathAlias/ParentClass";
class ChildClass extends ParentClass {
}
```
3. The import path in child class uses a path alias. That we define in jest configuration of package.json:
```
moduleNameMapper: {
  "pathAlias/(.*)": "<rootDir>/somepath/$1"
}
```
4. Now we create a test that uses child class and call to the parent class method:
```
const childObject = new ChildClass();
childObject.parentMethod()
```
5. At this point, VSCode marks the method as not existing in child class, and is not shown as method in IntelliSense for the child class.
6. If I launch the test in console. The test is compiled and executed successfully.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
VS Code does not understand jest's `moduleNameMapper `. You also need to configure the `paths` option in your [`jsconfig`](https://code.visualstudio.com/docs/languages/jsconfig) to handle this

See https://code.visualstudio.com/docs/languages/jsconfig#_using-webpack-aliases for example
