### ISSUE TITLE
Revisit path ignore case usage

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#99679]
For https://github.com/microsoft/vscode/issues/93368 I have removed the ability to specify the path-case-ignore behaviour when calling `isEqual` and friend. This was possible because almost everyone used the defaults (which I preserved). However, the `simpleFileDialog` always ignores path casing when comparing uris. Therefore [`extUriIgnorePathCase`](https://github.com/microsoft/vscode/blob/d65758c312ecdc76d5fc3107128d05de2594a458/src/vs/base/common/resources.ts#L332) exist. Please review the usages and make sure the usage is as intended. Also note that there is [`IUriIdenityService#extUri`](https://github.com/microsoft/vscode/blob/cadabab73fef89fe0c4bfe23b5a33cd58e39ea9c/src/vs/workbench/services/uriIdentity/common/uriIdentity.ts#L24) which knows when to ignore path casing and when not to

```
src/vs/workbench/services/dialogs/browser/simpleFileDialog.ts 
  871, 18: 		if (!resources.extUriIgnorePathCase.isEqual(fileRepresentationCurr, fileRepresentationParent)) { 
  563, 20: 				if (!resources.extUriIgnorePathCase.isEqual(resources.removeTrailingPathSeparator(this.currentFolder), inputUriDirname)) { 
  544, 220: valueUri)) && resources.extUriIgnorePathCase.isEqualOrParent(this.currentFolder, resources.dirname(valueUri))))) { 
  544, 129: value) || (!resources.extUriIgnorePathCase.isEqual(this.currentFolder, resources.dirname(valueUri)) && resources.extUriIgnorePathCase.isEqualOrParent(this.currentFolder, resources.dirname(valueUri))))) { 
  544, 25:  else if (!resources.extUriIgnorePathCase.isEqual(this.currentFolder, valueUri) && (this.endsWithSlash(value) || (!resources.extUriIgnorePathCase.isEqual(this.currentFolder, resources.dirname(valueUri)) && resources.extUriIgnorePathCase.isEqualOrParent(this.currentFolder, resources.dirname(valueUri))))) { 
  406, 21: 					if (!resources.extUriIgnorePathCase.isEqual(this.currentFolder, filePickBoxUri)) { 
```

**Comment by alexr00** [comment]
I reviewed the uses of ignore case in simple file dialog, and they are mostly still needed, since most of the compares are between the truth (as gotten by the file service) and the user input from the quick input box. The user input is later converted to the truth when the file is chosen. 

I did find one place where the case ignore was note needed.
