### ISSUE TITLE
Enable VSIX caching 

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99674]
Enable VSIX caching so that the same VSIX need not be downloaded if requested again

**Comment by chrmarti** [comment]
@sandy081 Remote-Containers has its own cache folder locally and copies VSIXs from that into containers. Could that reuse the CachedExtensionVSIXs folder?

**Comment by sandy081** [comment]
I would not recommend to mix caches because these vsixs can be for different environments. I know currently they are same but this will lock us if in future if we get platform specific vsixs.

**Comment by chrmarti** [comment]
@sandy081 Ack, although that will be something to consider for the Remote-Containers VISX cache anyway.
