### ISSUE TITLE
Moving a view should also move the focus to the view

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#99689]
When you move a view it feels odd that focus isn't shifted to the view. You have to click and drag on the view to start moving, and whenever you select an item in the workbench we always move focus to that item.

![Kapture 2020-06-09 at 8 46 18](https://user-images.githubusercontent.com/35271042/84169976-1c67be80-aa2e-11ea-97b5-f5c862020d54.gif)

**Comment by sbatten** [comment]
It used to focus the view on drop but I got feedback saying the current behavior was preferred and less disruptive.
