### ISSUE TITLE
Improve Command Palette search experience for word permutations

### ISSUE THREAD

**Issue by guywaldman** [microsoft/vscode#99685]
When searching with the Command Palette, right now you can use fuzzy search which is great.
Searching for "pop stash" or similar will bring up `Git: Pop Stash...` from the native Git extension.
Searching for "stash pop" however, will not.

I frequently search for "stash pop" instead of "pop stash" and it doesn't match since it expects the word in order. That is just a contrived example, I am sure that there are better ones.

Anyway, not sure whether this is a good idea just in my eyes, but in some cases I think it would be useful if the words could be out of order.
This could be implemented using keywords (for secondary search in case there are no matches) or implementing the out of order functionality. If performance is an issue, you could opt for this search heuristic lazily in cases where there are no results without it.

**Comment by bpasero** [comment]
Related issues: https://github.com/Microsoft/vscode/issues/27317

**Comment by bpasero** [comment]
Yeah you are right, but what if that would only apply if no commands are otherwise found?

**Comment by guywaldman** [comment]
Yeah that or ranking them lower, after the first ones as I mentioned before, for which no results is a private case. WDYT: only if no results or with less weight?

**Comment by bpasero** [comment]
The problem with "ranking them lower" is that you suddenly no longer have commands sorted in alphabetic order. We do that on purpose so that commands with the same prefix are close to each other.
