### ISSUE TITLE
Opening VS Code with URLs doesn't work with `\\wsl$` urls

### ISSUE THREAD

**Issue by sarim** [microsoft/vscode#99691]
Issue Type: <b>Bug</b>

vscode://file///wsl$/Ubuntu-18.04/home
vscode://file/\\wsl$/Ubuntu-18.04/home

Both shows a error with `\wsl$\Ubuntu-18.04\home`  does not seem to exist anymore on disk.

vscode://file////wsl$/Ubuntu-18.04/home
vscode://file/////wsl$/Ubuntu-18.04/home
vscode://file//////wsl$/Ubuntu-18.04/home
vscode://file/\\\wsl$/Ubuntu-18.04/home
vscode://file/\\\\wsl$/Ubuntu-18.04/home
vscode://file/\\\\\wsl$/Ubuntu-18.04/home

Nothing happens for these ^

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.96GB (13.54GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-18.04/home/gittu/sploy --remote=wsl+Ubuntu-18.04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3392)|
|Memory (System)|18.73GB (16.51GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.3.14
php-cs-fixer|jun|0.1.154
php-namespace-resolver|Meh|1.1.8
bracket-pair-colorizer|Coe|1.0.61
systemd-unit-file|coo|1.0.6
autoconf|mae|0.1.0
dotenv|mik|1.0.1
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
devicetree|plo|0.1.1
vscode-nginx|sha|0.6.0
twig|wha|1.0.2

</details>

**Comment by CountessAnise** [comment]
`vscode-remote://wsl+` for WSL.   
So give `vscode-remote://wsl+Ubuntu-18.04/home` a try.

**Comment by aeschli** [comment]
@sarim How exactly do you use the `vscode://file/\\\wsl$/Ubuntu-18.04/home` URIs?

**Comment by sarim** [comment]
Sorry I didn't update this issue. But eventually I got it to work. Not sure if vscode updates (now I'm at 1.46.1) fixed it. I'm running  symfony projects inside wsl2, and coding via VSCode remote. Symfony in its debug generates links to exact file and line for error / warning / emitted events etc...
Like this.

```html
<a href="vscode://file//wsl$/Ubuntu-18.04/home/gittu/sploy/vendor/easycorp/easyadmin-bundle/src/Controller/AdminControllerTrait.php:63:0" title="App\Controller\Admin\DeployController">DeployController :: indexAction</a>
```

Symfony gets the pattern for generating the URL from a config value.

```sh
$ cat /etc/php/7.2/mods-available/xdebug.ini
zend_extension=xdebug.so
xdebug.file_link_format="vscode://file//wsl$/Ubuntu-18.04%f:%l:0"
```

With this now it works. Though it always opens the file in a new window (where I want it to open it inside the project window) but for now I can live with it.

**Comment by aeschli** [comment]
Thanks, I'm closing the issue then.

**Comment by hcoat** [comment]
I am hoping this issue could have another look.

While URLs like `vscode://file/$wsl/distro/path/to/file:18` will open the file in a new `local` window and not a `remote-wsl` window or project.
This is problematic because the extensions and settings are not the same for `local` and `remote-wsl` connections, making the new window unusable for me.

`wsl$` URLs really needs to be opened in the currently open `remote-wsl` project to be useful.

**Comment by aeschli** [comment]
@hcoat To open a remote window, don't use `file` but `vscode-remote`. Please try
`vscode://vscode-remote/wsl+distro/path/to/file`
