### ISSUE TITLE
updateImportsOnFileMove is case-insensitive

### ISSUE THREAD

**Issue by clshortfuse** [microsoft/vscode#99690]
- OS Version: MacOS v10.15.4

Version: 1.46.0-insider
Commit: 24ebced0aba496bd7bdacd432aa9e877181bcf63
Date: 2020-06-08T07:54:29.001Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:

1. create an imported JS file
2. rename the file with a different capitalization
3. Nothing happens

- [ ] Does this issue occur when all extensions are disabled?

**Comment by mjbvz** [comment]
@jrieken I looked into this quickly but it looks like `vscode.workspace.onDidRenameFiles` does not file if you only change capitalization on case-incentive file systems. Assigning to you for investigation

**Comment by bpasero** [comment]
A bad oversight on my end from changes I did.
