### ISSUE TITLE
Stray `}` added to Problems input filter

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#99695]
Only in the Insiders' Build (not in Standard Build) I noticed that there is  a stray `}` added to the filter input box.  If I delete it, it gets added right back if I move the Problems view again 

or

if I reload vscode.  The stray `}` is also there when I close and reopen vscode.

Version: 1.46.0-insider (user setup)
Commit: 9f89da69154ac6c99dfa7c82986e2df95b7bbe0b
Date: 2020-06-08T22:10:54.220Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19640

**Comment by sandy081** [comment]
So when you clear the input and reload the text appears again? Is it true with all text or only with `}` ? Can you please provide a gif/video showing this behaviour?

**Comment by sandy081** [comment]
I see its happening for you but I cannot repro it. 

Can you try to repro the same using fresh user data direcotry?  You can start code-insiders from command line using `--user-data-dir` arg

`code-insiders --user-data-dir <new user data dir>`

**Comment by ArturoDent** [comment]
That did get rid of the stray character.

There is still this, possibly related, issue though:

If I do a filter search, and then erase that filter term, and then move the Problems view - that deleted (by backspacing) text reappears in the filter input again.

But reloading vscode does properly remember that the filter input is now empty.

Let me know if you need another video of this.

**Comment by sandy081** [comment]
Yeah please
