### ISSUE TITLE
"Server returned 404" when trying to install different versions of extensions in VS Code

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#99699]
- VSCode Version: 1.45.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open the extensions view and install the Python extension (or the Docker extension)
2. Click to install a different version of the extension
2. See the "Server returned 404" notification prompt

Does this issue occur when all extensions are disabled?: No

The issue was originally filed here: https://github.com/Microsoft/vscode-python/issues/12217, but it can also be reproduced with the Docker extension. 

![image](https://user-images.githubusercontent.com/45497113/84183183-5477fd00-aa40-11ea-8792-c671bfcda429.png)

Log (Window): 

```
[2020-06-09 10:59:40.899] [renderer1] [error] Server returned 404: Error: Server returned 404
    at Object.t.asJson (file:///C:/Users/luabud/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1839:954)
    at file:///C:/Users/luabud/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2030:39
    at async Promise.all (index 13)

```

**Comment by sandy081** [comment]
Which version are you trying to install?

**Comment by sunbart** [comment]
Same thing happens to me. (same Win & VSCode versions as luabud)

This doesn't happen while installing, but before - it happens when VSCode tries to get the list of available versions to show under the "Select Version to Install" popup. (At least that's what I assume is happening)

The action sequence is:
1. Click on the Manage button of the extension in the Extensions list
2. Select "Install Another Version..." from the menu
3. The "Select Version to Install" prompt appears, with a loading indicator running at the bottom of it
4. After a few seconds, the "Server returned 404" error notification appears and the "Select Version to Install" prompt disappears.

**Comment by Rutikhal** [comment]
The same for me. I had an issue today with Azure Functions local dev (python worker) in VSCode and I noticed that was update 8th of June of Python extension, to troubleshoot I wanted to install previous version of this extension but having  error described here.

**Comment by Rutikhal** [comment]
my workaround to fix my issue https://github.com/Azure/azure-functions-python-worker/issues/481#issuecomment-641943047

**Comment by rhymu8354** [comment]
I've started seeing this with vscode 1.45.1 on Windows, but only for one extension (CMake Tools) which I had to revert to an earlier version due to a breaking bug.  Now I'm locked into the version I have, or to update to the latest which is broken for me.

**Comment by luabud** [comment]
> Which version are you trying to install?

I don't get to select a version, just by clicking on "Install version..." it throws that error. 

![image](https://user-images.githubusercontent.com/45497113/84345410-1f63cb80-ab62-11ea-8533-08111260b9a6.png)

I tried it with previous versions of the Python extension just in case, but that didn't change. And again, that can be reproduced with other extensions e.g. Docker and CMake Tools as said here. It's not happening to all extensions for me, it's working with the C/C++ extension.

**Comment by sandy081** [comment]
@fiveisprime Seems Marketplace is returning 404s for the valid URIs.

**Comment by fiveisprime** [comment]
The marketplace team has an idea of what's going on and they're looking into a fix.

**Comment by mgabeler-lee-6rs** [comment]
This is now working for me for _some_ extensions, but not all. Not sure if this is a CDN issue or what?

**Comment by darmawanaris** [comment]
I got this problem too when i want to install another version of terraform extension.

VSCode version : 1.46.0
OS : 16.04 xenial

Seems the issue still happening..

**Comment by bklynate** [comment]
Currently experiencing this issue as well...
<img width="796" alt="Screen Shot 2020-06-18 at 12 51 05 PM" src="https://user-images.githubusercontent.com/4186033/85049165-4b82dc00-b162-11ea-8675-71ff6136074b.png">

**Comment by thomasrobertz** [comment]
Also happens for Nativescript 0.11.0

**Comment by Chupaka** [comment]
VSCode 1.46.1, still 404. @fiveisprime, any news from marketplace team?

**Comment by fiveisprime** [comment]
Reached out again this morning and I'll let you know what I hear back. Sorry for the issues. :(

**Comment by Stropek** [comment]
Having the same problem with **Python** extension :(

**VS Code:** 1.46.1

![image](https://user-images.githubusercontent.com/2047989/85863235-e433e000-b790-11ea-906f-a18a4731e6f3.png)

**Comment by sandy081** [comment]
Added a fix in VS Code to ignore those versions which throw error (Eg: 404). So now you can see the list of versions even though some fail.

**Comment by ps-apalon** [comment]
@sandy081 do you have any ETA on when this will actually be "fixed" for everyone?

**Comment by sandy081** [comment]
Next stable release is planned for Thursday next week - Please follow our end game schedule here - https://github.com/microsoft/vscode/issues/101289

**Comment by aryan29** [comment]
Using vsocde-insiders 1.47.0 solved issue for me
