### ISSUE TITLE
initializing JS/TS language features constantly crashing

### ISSUE THREAD

**Issue by vtoomas** [microsoft/vscode#99698]
Issue Type: <b>Bug</b>

I'm developing on remote linux system over SSH. 
Not using Typescript. 
Smallish next.js application.  

Every now and then I notice the js file I'm editing gets automatically saved (while typing) and status bar showing initializing JS/TS language features. The auto saving usually results in nodemon restarting the webserver and throwing errors as I haven't finished typing. 

Occasionally VSCode also prompts that the JS/TS language features module has crashed 5 times over some period of time. 

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|SSH: *.*.*.*|
|OS|Linux x64 4.4.0|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (2 x 665)|
|Memory (System)|2.00GB (0.45GB free)|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
prettier-vscode|esb|5.0.0
docthis|joe|0.7.1

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
