### ISSUE TITLE
how can i solve it?

### ISSUE THREAD

**Issue by zjj2wry** [Microsoft/vscode#9969]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

2016/07/30 18:23:45 server.go:41: Using API v1
2016/07/30 18:23:45 debugger.go:61: launching process with args: [./debug]
could not launch process: Access is denied.

**Comment by kieferrm** [comment]
@zjj2wry can you please give us steps that allow us to reproduce the problem without guessing what you mean. Thanks a ton.

**Comment by zjj2wry** [comment]
vscode installed delve.but delve..
$ dlv debug main.go
could not launch process: Access is denied.

**Comment by zjj2wry** [comment]
linux can use,but windows cannot.

**Comment by aeschli** [comment]
Sorry, please add details steps that show how VS code is involved
