### ISSUE TITLE
Copying files to extensions folder during runtime

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#99697]
Today in the Python extension we copy some scripts files from external folders into the `Python Extension` folder.

This is to ensure script files that are outside the extensions folder (in a users Python environment folder) can be loaded inside webiviews. Currently VS Code webiviews do not allow loading script files from outside the extensions folder.

Our solution is to copy the files into a temporary directory in the extension solder and then serve those files to the webview.

We're planning on doing the same thing yet again for notebook renderers.
We are in the process of creating an extension for Notebook renderers, however we'd like to use the same scripts to render output in Python Interactive Window (it is not a notebook, but has similar functionality and behaviour). To do this we'd need to copy the script files from the renderer extension into the Python extensions folder.

Does this approach of copying files into extensions folder during runtime present a problem. I'm concerned about contexts such as Remote Environments, Code Spaces & the like.

@rebornix /cc

**Comment by sandy081** [comment]
> Does this approach of copying files into extensions folder during runtime present a problem.

Ideally we do not recommend maintaining the state in the extension folder because when extensions can get updated, the state in the folder will not be. We provide a global location for each extension to store its state and can be reused on update, See [globalStoragePath](https://code.visualstudio.com/api/extension-capabilities/common-capabilities#data-storage).

Since this is related to web views, I would ask @mjbvz recommendation.

**Comment by mjbvz** [comment]
@DonJayamanne Have you tried setting `localResourceRoots` on the webviews? This should allow loading content from any folder you configure (although try to be as restrictive as possible when configuring this)

**Comment by DonJayamanne** [comment]
Oh shoot, totally forgot about that.
Let me check and get back, sorry.

**Comment by DonJayamanne** [comment]
Oh yes, the draw back is that we do not have the list of the folders before creating the webview. At least not in the case of ipywidgets.
The kernel can be changed/selected after the webview has loaded.

& this path can change over time (without closing the webiview/notebook).
This would apply to both the new Notebook as well as the WebView.

**Comment by DonJayamanne** [comment]
I goes we could copy to the global extension cache directory.
Closing as that solves this.

**Comment by mjbvz** [comment]
The local resource roots can be updated after a webview is created: https://github.com/microsoft/vscode/blob/0d64f7bdbef9dd946ce228400c2be017f0acbe2b/src/vs/vscode.d.ts#L6714

Since you know what files need to be copied, I think you should be able to update the local resource roots too

**Comment by DonJayamanne** [comment]
> The local resource roots can be updated after a webview is created: /src/vs/vscode.d.ts@0d64f7b#L6714

That link doesn't work.
I assumed the localResourceRoots could not be updated once the webview had been created. Will try that, thanks a lot.
