### ISSUE TITLE
Extension APIs: suggest window is displayed despite not having any suggestions

### ISSUE THREAD

**Issue by jpoon** [Microsoft/vscode#997]
### Context 

For the [VIM extension](https://github.com/VSCodeVim/Vim), we need to add a keybinding for every key input, do some stuff, then manually insert it into the active text editor. Despite inserting a character at the current position, it will hide the suggest/autocomplete window.

### Problem

As you type and press a key that triggers an suggest window (e.g. `.`), regardless of the next character inserted via the active text editor API, it will close the suggest window.

We can manually trigger the suggest window following every insert via 

```
vscode.commands.executeCommand("editor.action.triggerSuggest");
```

But this results in the suggest window showing up even if there is nothing to suggest. Is there a way to trigger the suggest window only if there are actually suggestions?

**Comment by colbyrussell** [comment]
Update: vscode now has an `editor.cursorStyle` setting that allows a `block` value.  The issue as written is still valid, since (AFAICS) there's no way to control it from the extensions API.

**Comment by colbyrussell** [comment]
Sorry, that comment was supposed to be aimed at issue #561.

**Comment by alexandrudima** [comment]
@jpoon Please see https://github.com/alexandrudima/vscode-vim if you are authoring a vim emulation extension for VS Code. It delegates typing back to the VS Code editor when in insertion mode.
