### ISSUE TITLE
Watch: value hover should be on the whole element

### ISSUE THREAD

**Issue by Richhoef** [microsoft/vscode#99702]
Whenever I am debugging and want to watch larger variables or a statement, the actual values often disappear. Even when I hover over the watch, I only get to see what kind of value it is, not its value. Insteat of the ... that appear when the Watch window is smaller than the value, it would be awesome if the value would always be visible (like the linenumbers in the Breakpoints window are always visible regardless of the width of the window). Or, at least when I hover over a watch statement, show me the value. This would save me a lot of frustration and time increasing and decreasing the size of the watch window.

**Comment by ArturoDent** [comment]
A partial fix, which I highly recommend, is to move the Watch view into the Panel at the bottom - just drag it there.  You will see much more of your values but they will still be cut off if very long but it'll be better.

**Comment by Richhoef** [comment]
Thanks! That actually helps a lot (although now the number of variables visible is limited if I don't want to limit my editor height, but at least my watch values can all be read). I still hope they will fix this soon. Seems like a relatively easy fix to me

**Comment by isidorn** [comment]
@Richhoef when I hover over the watch value I always get the full value. Do you not get this? What are you doing differently than me?
And yes as @ArturoDent already suggested you can move the watch to the horizontal panel for more space.

![Screenshot 2020-06-10 at 09 56 40](https://user-images.githubusercontent.com/1926584/84242173-bdbf4500-ab00-11ea-8ac4-06065a6867f5.png)

**Comment by Richhoef** [comment]
@isidorn When I hover over the value it is oke, but often the value is not visible. If I hover over the watch statement (the thing that usually is the longest with me), only the value type is shown, not the value itself
![image](https://user-images.githubusercontent.com/51912545/84260052-ab053a00-ab19-11ea-9f0c-893e1f96aae9.png)

**Comment by isidorn** [comment]
Aha I understand, so you want the value hover to be over the whole element.
However by design we also want to show the type of the variable on hover if it is provided.
We can leave this open for further discussions for now.
