### ISSUE TITLE
Top debug session row says "paused" when not paused

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#99704]
- Start my debug config
- Hit a breakpoint on a debugger statement
- Continue
- The tab row says "Running" but the top row still says "Paused":

![image](https://user-images.githubusercontent.com/323878/83663262-403e8680-a58e-11ea-9827-66d61938cc1a.png)

**Comment by isidorn** [comment]
Fixed via compact trees https://github.com/microsoft/vscode/issues/99736
