### ISSUE TITLE
load and inject 3rd-party themes before execute completely vscode

### ISSUE THREAD

**Issue by imasood** [Microsoft/vscode#9970]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:28:46.761Z)
- OS Version: Linux x64 4.4.0-28-generic

Hi Friends,
I installed some themes for my vscode but i think the theme load and inject to vscode as common w3c way and suggest to inject the themes to vscode before execute completely vscode.
the common w3c way isn't very good and there's a delay in loading.
Thanks

**Comment by kieferrm** [comment]
@imasood can you explain in a bit more detail what you would like to see? Please feel free to use code references.

**Comment by aeschli** [comment]
Closing due to lack of information....
