### ISSUE TITLE
outline shows nothing but "The active editor cannot provide outline information" when editing a java file.

### ISSUE THREAD

**Issue by XuYan** [microsoft/vscode#99700]
- VSCode Version: 1.45.1
- OS Version: MacOS Catalina 10.15.5

Steps to Reproduce:

1. Open a single java or swift or any other code file with `code *.java/*.swift`
2. The outline is empty with text "The active editor cannot provide outline information"

I manually disable all the extensions and the issue still repros.

**Comment by gjsjohnmurray** [comment]
Outline info has to come from an extension. If you are already using a Java extension that claims to provide outline info, consult the extension author. If you haven't installed one that does, that is your problem.

/causedByExtension

**Comment by XuYan** [comment]
Thank you John.
