### ISSUE TITLE
"files to include" suggestions

### ISSUE THREAD

**Issue by jockrow** [microsoft/vscode#99707]
It would be nice for users to show suggestions hints in opaque text, how to write for controls, example by filters:

files to include
files to exclude

![image](https://user-images.githubusercontent.com/30563443/84196415-c44cae80-aa65-11ea-9543-fb34ede73e12.png)

**Comment by roblourens** [comment]
Have thought about doing this, except that any possible hint we could add would be context-specific in a way that I'm worried would confuse somebody. This is tracked in another issue.

**Comment by jockrow** [comment]
> Have thought about doing this, except that any possible hint we could add would be context-specific in a way that I'm worried would confuse somebody. Would rather add some sort of dropdown, Sublime Text-style. This stuff is tracked in another issue.

Please can tell me what is the tracked issue?

**Comment by roblourens** [comment]
Well I had considered it part of https://github.com/microsoft/vscode/issues/20530, because then we would add more special syntax for these inputs, but I think it can be a separate issue, I'll reopen this.

**Comment by jockrow** [comment]
Thanks for answer by
https://github.com/microsoft/vscode/issues/20530#issuecomment-651945229
