### ISSUE TITLE
Textbox Controls History

### ISSUE THREAD

**Issue by jockrow** [microsoft/vscode#99706]
Would great to recovery history for search controls in example for "Search Settings", "Search Extensions", like visual studio, example:

![image](https://user-images.githubusercontent.com/30563443/84193491-25be4e80-aa61-11ea-82de-4f801a89afa9.png)

![image](https://user-images.githubusercontent.com/30563443/84193538-3a9ae200-aa61-11ea-8d82-93c9e1a4ba2c.png)

**Comment by gjsjohnmurray** [comment]
Some of these fields already have history. Press the cursor-up key.

**Comment by jockrow** [comment]
Thank you for request, would be nice to display a list

**Comment by roblourens** [comment]
Tracking this in https://github.com/microsoft/vscode/issues/23099
