### ISSUE TITLE
Extend Intellisense for Javascript to recognize @lends from JSDoc and register class and methods.

### ISSUE THREAD

**Issue by saw235** [microsoft/vscode#99712]
For example, the code below creates a Person class with an object literal. JSDoc provides tags to document classes created this way. https://jsdoc.app/tags-lends.html

I would like for VSCode Intellisense to recognize the following as class and it's member function to show up as suggestions when coding.
```javascript
var Person = cc.Node.extend(
    /** @lends Person.protoype */
    {
        /** @constructs */
        ctor: function(){
        },

        /** @method */
        feed: function(){
        }
})

/**@type {Person} */
var a = new Person()
```

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project which provides VS Code's JavaScript tooling support. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
