### ISSUE TITLE
Support socks5 proxies

### ISSUE THREAD

**Issue by foisonocean** [Microsoft/vscode#9971]
- VSCode Version:1.3.1
- OS Version:OS X 10.11.6

``` json
// settings.json
{
  "http.proxy": "socks5://127.0.0.1:1080"
}
```

It doesn't work, and it shows `String does not match the pattern of "^https?://[^:]+(:\d+)?$|^$"`

**Comment by joaomoreno** [comment]
socks5 is not supported, do you really need it?

**Comment by foisonocean** [comment]
@joaomoreno Yes, I need it. Atom support socks5 in OS X, but VS Code don't.

**Comment by xuewang** [comment]
any update on this feature?

**Comment by distums** [comment]
+1

**Comment by harrylh** [comment]
Is there any plan to support socket5 proxy ? Thanks.

**Comment by wiz** [comment]
One can start a SOCKS proxy with basic `ssh`. So, yes, it would be very useful in travel etc.

**Comment by yushangj** [comment]
any update on support socks5 proxy?
we need it to access the github.
thanks!

**Comment by wbpmrck** [comment]
does this feature supported now?
we need it very much.

**Comment by Thiruppathi** [comment]
badly need this feature.

**Comment by joaomoreno** [comment]
Please check out #22214

**Comment by snugam** [comment]
Would be really really helpful!

**Comment by maple-leaf** [comment]
+1 for this feature. it will be very helpful

**Comment by joaomoreno** [comment]
Supported already in the latest version. Merging with #27838 for documentation.
