### ISSUE TITLE
node_modules should fold after file is closed

### ISSUE THREAD

**Issue by jackHedaya** [microsoft/vscode#99711]
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (3 wks ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:

1. In a project that includes node_modules, open a file that is in a node_modules subdirectory.
2. Close said file.
3. node_modules will not fold.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
