### ISSUE TITLE
References appear to be duplicated

### ISSUE THREAD

**Issue by Petrafan1** [microsoft/vscode#99714]
Issue Type: <b>Bug</b>

In a ps1 script I have, I see several functions have "2 references" however when I click on that, only 1 reference is shown (and I do believe 1 reference is accurate).  If I comment out the 1 reference, the 2 goes to 0.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (11.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.36.0
githistory|don|0.6.5
gitlens|eam|10.2.1
git-graph|mhu|1.23.0
mssql|ms-|1.9.0
powershell-preview|ms-|2020.6.1
vsliveshare|ms-|1.0.2274
team|ms-|1.161.0

</details>

**Comment by sandy081** [comment]
Please file the issue against powershell extension
