### ISSUE TITLE
Ignoring tsconfig.json for intellisense with Typescript 2.0

### ISSUE THREAD

**Issue by AnimaMundi** [Microsoft/vscode#9972]
- VSCode Version: 1.3.1 && 1.4.0-insider
- OS Version: 64 bit Windows 10

Steps to Reproduce:
1. Install Typescript 2.0: `$ npm install -g typescript@beta`
2. Open Typescript project with Visual Studio Code

Expected:
VS Code uses tsconfig.json to configure its intellisense

Actual:
VS Code ignores tsconfig.json

**Comment by AnimaMundi** [comment]
This can be resolved using `"typescript.tsdk": "node_modules/typescript/lib/"` in your workspace settings

**Comment by dalexander01** [comment]
@AnimaMundi can you give a better explanation how to do this? I am new to vscode. How do you change workspace settings? Also it's a little weird to me that this is needed. Are their plans to uplift vscode to work with Typescripts new way of doing typings thought npm without having to update workspace setttings?

**Comment by AnimaMundi** [comment]
@dalexander01 I can't speak on behalf of Microsoft, but I'd imagine they do plan to introduce support for Typescript 2.0 in vscode at some stage, but probably after it is officially released and no longer beta.

Before changing anything, make sure Typescript is installed locally in your project.
`npm install typescript@next --save`

On Windows you can reach workspace settings through:
File -> Preferences -> Workspace Settings

Paste `"typescript.tsdk": "node_modules/typescript/lib/"` into the file that opens on the right hand side.

Close the editor, then open it again and it will load tsc from your local installation.

If you have any problems during `npm install` at a later stage, then close the editor and try again.

**Comment by restes** [comment]
@AnimaMundi I'm trying to follow an Angular 2 course on Udemy. It wasn't until I found your solution, I couldn't concentrate on the course because Intellisense wasn't working like the video shows. 

Good stuff!
Thanks

> On Windows you can reach workspace settings through:
> File -> Preferences -> Workspace Settings
> 
> Paste "typescript.tsdk": "node_modules/typescript/lib/" into the file that opens on the right hand side.
> 
> Close the editor, then open it again and it will load tsc from your local installation.

**Comment by AnimaMundi** [comment]
@restes You should not need to do this anymore, I was able to remove this configuration from my workspace settings a couple of releases ago and I now get full support for TypeScript 2.x from VS Code without any extra configuration. Nonetheless I'm glad to have helped.
