### ISSUE TITLE
Not able to download "Salesforce Extension pack" from vscode

### ISSUE THREAD

**Issue by ravi0725** [microsoft/vscode#99729]
@sandy081 
Hi Sandeep, I follow each and every step you mentioned in the above post and attaching the result for the same. 
I am also not able to download "Salesforce Extension Pack", getting error "We can not connect to extension market place this time". 
Please help me on this.

**Help -> Toggle Developer Tools -> Network**
![image](https://user-images.githubusercontent.com/26737364/84235012-cb7dc600-ab12-11ea-8c9c-dcd1e343ea2e.png)
**To confirm its a DNS issue check if you can access this page** https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default,

_**_Yes I am able to open the link and see the image._**_

**Help -> Toggle Developer Tools -> Console**
`Failed to load resource: net::ERR_TIMED_OUT
workbench.desktop.main.js:1642   ERR net::ERR_TIMED_OUT: Error: net::ERR_TIMED_OUT
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2623:21)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TIMED_OUT
2workbench.desktop.main.js:6668 Error querying extensions gallery Canceled
(anonymous) @ workbench.desktop.main.js:6668
workbench.desktop.main.js:6668 Error querying extensions gallery XHR timeout: undefinedms
(anonymous) @ workbench.desktop.main.js:6668
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TIMED_OUT`

**View -> Command Pallette... -> Toggle Shared Process -> Console**
`2az764295.vo.msecnd.net/extensions/marketplace.json:1 Failed to load resource: net::ERR_TIMED_OUT`

**Log (shared)**
`[2020-06-10 11:50:32.933] [sharedprocess] [info] main {"machineId":"48fe33e62508cacf66f14a567d671e76e5f2563e2186c3f7681e1ce13e22add6","windowId":2}
[2020-06-10 11:51:13.033] [sharedprocess] [info] Starting to clean up unused language packs.
`

**log(window)**
`[2020-06-10 11:51:03.595] [renderer1] [error] net::ERR_TIMED_OUT: Error: net::ERR_TIMED_OUT
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2623:21)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)`

Thanks

_Originally posted by @ravi0725 in https://github.com/microsoft/vscode/issues/97484#issuecomment-641762355_

**Comment by sandy081** [comment]
> I am also not able to download "Salesforce Extension Pack", getting error "We can not connect to extension market place this time"

Do you mean are you able see the extension in the view but not able to install it?

Can you please record a gif or video and share it?

**Comment by ravi0725** [comment]
When I type "Salesforce extension pack" in extension search bar , I got error.....
![image](https://user-images.githubusercontent.com/26737364/84239795-b2791300-ab1a-11ea-8b76-4b51ad3350d8.png)

**Comment by ravi0725** [comment]
![image](https://user-images.githubusercontent.com/26737364/84240321-7b573180-ab1b-11ea-8cd0-59099a36ad8c.png)

**Comment by sandy081** [comment]
Please enable the log level to trace and try again typing "Salesforce extension pack" in extension search.. and provide 

    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by ravi0725** [comment]
Help -> Toggle Developer Tools -> Console
`Failed to load resource: net::ERR_TIMED_OUT workbench.desktop.main.js:1642 ERR net::ERR_TIMED_OUT: Error: net::ERR_TIMED_OUT at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2623:21) at SimpleURLLoaderWrapper.emit (events.js:203:13) marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TIMED_OUT 2workbench.desktop.main.js:6668 Error querying extensions gallery Canceled (anonymous) @ workbench.desktop.main.js:6668 workbench.desktop.main.js:6668 Error querying extensions gallery XHR timeout: undefinedms (anonymous) @ workbench.desktop.main.js:6668 marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TIMED_OUT`

View -> Command Pallette... -> Toggle Shared Process -> Console
`2az764295.vo.msecnd.net/extensions/marketplace.json:1 Failed to load resource: net::ERR_TIMED_OUT`

Log (shared)
`[2020-06-10 11:50:32.933] [sharedprocess] [info] main {"machineId":"48fe33e62508cacf66f14a567d671e76e5f2563e2186c3f7681e1ce13e22add6","windowId":2} [2020-06-10 11:51:13.033] [sharedprocess] [info] Starting to clean up unused language packs.
`
log(window)
`[2020-06-10 11:51:03.595] [renderer1] [error] net::ERR_TIMED_OUT: Error: net::ERR_TIMED_OUT at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2623:21) at SimpleURLLoaderWrapper.emit (events.js:203:13)`

**Comment by ravi0725** [comment]
Hi @sandy081 
Can you please confirm whether the last logs I sent you is correct or you want me to send again.
Also if you can clear me on ,when you say enable log level, from where I can do this, please help.

**Comment by sandy081** [comment]
It seems you are not able to access this URL -https://az764295.vo.msecnd.net/extensions/marketplace.json

**Comment by ravi0725** [comment]
{
	"malicious": [
		"visualstuiocode.emmet",
		"joaomoreno.banana",
		"JacobeanResearchandDevelopmentLLC.vscode-scxml-preview",
		"joaquin6.package-watch",
		"KazuoCode.gthubsum",
		"MaxGotovkin.tslens"
	]
}

Getting this result.

**Comment by ravi0725** [comment]
Can you please guide how to resolve this. I am not able to access the url (https://az764295.vo.msecnd.net/extensions/marketplace.json)

**Comment by ravi0725** [comment]
Visual Studio Code Insiders, is working fine on my system.
Can we use Visual Studio insider instead of Normal Visual Studio code.
I mean what is the difference ?

**Comment by sandy081** [comment]
@deepak1556 Again I need your help here to figure out why the user is not able to access above URL with in VS Code?

**Comment by deepak1556** [comment]
@ravi0725 can you start vscode with `--log-net-log=netlog.json` from the command line, search for the extension "Salesforce Extension Pack", quit the app and attach the log here.

Can you also check if the issue repros when you create a new user profile for vscode, to do this start vscode with `--user-data-dir <new-path-for-user-data>`

**Comment by ravi0725** [comment]
I  start the vscode from command line but did got get any log when I try to install it "Salesforce extension pack" . Got the same message "Could not connect to marketplace"

**Comment by sandy081** [comment]
Assigning to @deepak1556 as it seems network issues with VS Code. Please assign me back if there is something I can do.

**Comment by rzhao271** [comment]
@ravi0725 does this issue still occur for you on the latest version of VS Code (non-insiders)? 

> Can we use Visual Studio insider instead of Normal Visual Studio code.
I mean what is the difference?

Visual Studio Insiders updates more frequently, but if the issue still occurs for you on the latest VS Code, but not the latest VS Code Insiders, then I wonder whether it is a user-data issue.
