### ISSUE TITLE
vscode reports reachable "unreachable code" after an IIFE

### ISSUE THREAD

**Issue by ljharb** [microsoft/vscode#99726]
- VSCode Version: 1.45.1
- OS Version: Mac OS 10.14.5

Steps to Reproduce:

add this code:
```js
var noThrowOnStrictViolation = (function () {
	try {
		delete [].length;
		return true;
	} catch (e) {
		return false;
	}
}());
```

before a bunch of other code. see how vscode grays out and incorrectly marks "ts(7027)" on the following code.

If it's changed to this code:
```js
var noThrowOnStrictViolation = (function () {
	try {
		delete [].length;
		return true;
	} catch (e) {
	}
	return false;
}());
```
the bug does not occur.

**Comment by mjbvz** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/36828

Already fixed in VS Code insiders

**Comment by ljharb** [comment]
Thanks, any idea when it will be released?
