### ISSUE TITLE
Add API to contribute problem matchers (with fixits) as JS functions

### ISSUE THREAD

**Issue by matklad** [microsoft/vscode#99728]
I am writing a small [expect testing](https://blog.janestreet.com/using-ascii-waveforms-to-test-hardware-designs/) library for my project. After I run the test, I want to see a :bulb: in the editor with suggestions to update the expected value in the tests. 

Ideally, I'd just print failure messages in a special format to stdout on test failure, and have the editor automatically convert that into a diagostic and associated fix. 

The diagnostic part is possible today with regex problem matchers. However for providing fixits, it seems like a more flexible API is required.

**Comment by mjbvz** [comment]
Take a look at the code action api: https://github.com/microsoft/vscode/blob/11fda69d237b9aa006eb53da724fa509afe92e0a/src/vs/vscode.d.ts#L2122

This is what extensions such as eslint use to implement fixes

**Comment by matklad** [comment]
Yup, I can use `CodeAction`s to *provide* fixits. The problem is, I can't consume a `Task` output. I can work around this by writing substantially more code and managing process execution myself, but then it won't be integrated nicely with VS Code tasks UI.

Or am I missing something and there's some kind of `onTaskOutput(line: string)` event somewhere?

**Comment by mjbvz** [comment]
Tasks generate diagnostics which your code actions can use. 

There are no plans to generate fixes from task output. For more advanced use cases like your, you'll need to write adapter code in your extension. It would probably be easier not to use tasks at all here and just have your extension generate diagnostics directly. The logic for generating the diagnostics and fixes can still live in a separate library or process
