### ISSUE TITLE
Compare difference does not support *.il file

### ISSUE THREAD

**Issue by GreyElec** [microsoft/vscode#99723]
Please create a file with a name like differ1.il and differ2.il with content like 
12341234 for differ1.il and 12341235 for differ2.il

then select both and click the compare difference, you will see it does not work. 

please help to fix, it works before.

**Comment by bpasero** [comment]
I cannot reproduce, works fine:

![image](https://user-images.githubusercontent.com/900690/84234267-31a72080-aaf4-11ea-8cb6-37f6674eca4d.png)

**Comment by GreyElec** [comment]
I am using window10 system with VSCode version 1.45
![image](https://user-images.githubusercontent.com/33427038/84236453-3be41180-ab2a-11ea-84a2-0c0b768fc481.png)

**Comment by bpasero** [comment]
This looks like maybe a diff editor issue to me, adding @alexdima 

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by GreyElec** [comment]
it works well on the insider version
![image](https://user-images.githubusercontent.com/33427038/84237446-f0cafe00-ab2b-11ea-98e6-f518943d192e.png)
Does it mean this issue will be gone on next released version or its just something wrong with my vscode configuration?

**Comment by alexdima** [comment]
@GreyElec It is very weird that the diff does not appear on your stable installation.

* In the instance that does not show the diff information, do you see any errors in the console (F1 > Developer: Toggle Developer Tools)?
* Is the instance permanently broken? If you close VS Code and open it up again does it begin to show the diff information again?

**Comment by GreyElec** [comment]
![image](https://user-images.githubusercontent.com/33427038/84243592-01cc3d00-ab35-11ea-8837-83887590ef32.png)
there shows this error and it shows up again after I close and up it up again,

**Comment by alexdima** [comment]
@GreyElec Thank you for the quick reply. I notice that in one screenshot you are using the `D:` drive and this latest warning message refers to the `C:` drive. Are you by any chance doing something with virtual drives or stuff like that or are these really two distinct partitions?

To eliminate all variables, can you please rename the files to `a.txt` and `b.txt`. Does the diff computation work when they are plain text files?

**Comment by GreyElec** [comment]
![image](https://user-images.githubusercontent.com/33427038/84245786-2a096b00-ab38-11ea-952f-07c30ddbc07e.png)
it works if I change the extension name to .txt

**Comment by GreyElec** [comment]
Yes, the D drive is a virtual drive for my one drive on C drive. I did this because there is a space in the one drive path which can cause an error on some of my code.

**Comment by GreyElec** [comment]
I found the issue get fixed with the update today, thanks for the help.

**Comment by bpasero** [comment]
@GreyElec hey, what exactly did you do to resolve this?

**Comment by GreyElec** [comment]
I did nothing, the second day there is a meter says there is an update for VScode, after the update, I tested and found the issue is gone,

**Comment by bpasero** [comment]
Yeah confirmed, the `1.46` update has fixed this, though not clear to me yet how.

**Comment by GreyElec** [comment]
Sure, to me it's pretty good that I could keep enjoying the VScode, thanks for the help and thanks for your work to deliver this beautiful code editor.
