### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by shawn220a** [microsoft/vscode#99731]
Is there a way to make an app for the iPads. I would love to access my code and do a little programming on my iPad. The iPad would be more convenient to code on since I am always traveling and sometimes I am not in an area with public WiFi. If this is already available can you give me the steps for using vs code on iPad.

**Comment by bpasero** [comment]
See related issues https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+ipad
