### ISSUE TITLE
Sluggish

### ISSUE THREAD

**Issue by teeaarbee** [microsoft/vscode#99733]
Issue Type: <b>Performance Issue</b>

Unable to load extensions, everything freezes

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    95	 10940	code main
    0	    70	  3656	   shared-process
    0	    14	  8264	   electron-crash-reporter
    0	   195	  8528	   window (index.html - TEEAARBEE - Visual Studio Code)
    0	    13	  3596	     watcherService 
    0	    11	  9788	       console-window-host (Windows internal process)
    0	    35	  5940	     searchService
    8	   226	 17104	     extensionHost
    0	    88	  2240	       "C:\Users\G Rohit\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\G Rohit\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=17104
    0	    36	  3972	       electron_node eslintServer.js 
    0	   162	 12616	   gpu-process
    0	    66	 13732	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html - TEEAARBEE - Visual Studio Code)
|    Folder (TEEAARBEE): 336 files
|      File types: js(86) json(34) scss(25) svg(20) jpg(18) html(13) png(13)
|                  css(9) mdx(5) eot(4)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
vscode-json|and|1.5.0
minify-selection|box|0.0.2
htmltagwrap|bra|0.0.7
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.1
css-minify|Die|0.1.12
prettier-vscode|esb|5.0.0
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.1
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
uikit-3-snippets|Ken|1.4.2
wrapSelection|kon|0.8.0
es6-css-minify|olb|3.3.2
open-html-in-browser|pea|2.1.3
emoji|Per|0.0.3
material-icon-theme|PKi|4.1.0
html-to-jsx|ria|0.0.1
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.5.12
indenticator|Sir|0.6.0
sass-indented|syl|1.8.5
bootstrap4-vscode|the|6.1.0
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Please follow our Performance wiki - https://github.com/microsoft/vscode/wiki/Performance-Issues and provide necessary information.
