### ISSUE TITLE
Recommendation for Go language broken

### ISSUE THREAD

**Issue by gparlakov** [microsoft/vscode#99730]
Issue Type: <b>Bug</b>

Seems that the the recommendation for package **@id:ms-vscode.go** is no longer working. 

It seems that it's been changed to **@id:golang.go**

![Menubar_and_group_go_—_vss-rules-service_and_page_compliance-control-in-control-group_ts_—_webapp-new](https://user-images.githubusercontent.com/3482199/84239274-ed704c00-ab04-11ea-9c40-95e0f4990527.png)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.5.0

<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.901.9
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.0.0
Go|gol|0.14.4
scuri-code|gpa|1.2.1
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
vscode-peacock|joh|3.7.2
vscode-typescript-tslint-plugin|ms-|1.2.3
material-icon-theme|PKi|4.1.0
psi-header|psi|1.11.1
vscodeintellicode|Vis|1.2.8

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
This should be fixed with our next release.
