### ISSUE TITLE
Get errors from client side textDocument

### ISSUE THREAD

**Issue by XVincentX** [Microsoft/vscode#9973]
I'd like to block some commands when the current document has some errors.

What's the best way to access the current editor state? I am not able to find anything in `textDocument` nor `textEditor` instance!

**Comment by kieferrm** [comment]
@XVincentX what state are you looking for? If the document has errors? There is currently nothing in the API that lets you find out whether or not a linter found errors.

**Comment by XVincentX** [comment]
@kieferrm That's exactly what I was looking for. I'd like to get it the current document has problems or warnings - even better if I could get the number for both!

**Comment by jrieken** [comment]
@XVincentX Is it you generating those diagnostics? Iff so you can [`read`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2716) the diagnostics collections. If you don't own/generate the errors there is no currently no way to get to them and I doubt that you can make a reliable statement about the interference of all markers wrt a command.

**Comment by XVincentX** [comment]
I am generating those diagnostics - I am creating this collection on the server process but I do not understand how can I read back those from the client. Should I probably send a request from the client to the server?

**Comment by jrieken** [comment]
That's a different API, @dbaeumer will know.

**Comment by dbaeumer** [comment]
@XVincentX currently you can only ask your server about this since the client lib doesn't provide API for it. Can you please open an issue here https://github.com/Microsoft/vscode-languageserver-node so that I add API to give you access to the diagnostic collection that the client manages.

**Comment by XVincentX** [comment]
Done!
