### ISSUE TITLE
failed to select all occurrences by word 

### ISSUE THREAD

**Issue by dodoru** [microsoft/vscode#99749]
If use short-cut  `command + shift + F ` or ` command + ctrl + G`, 
it alerts "command 'extension.findBySelection' not found". 

I need this: 

https://stackoverflow.com/questions/46539714/select-all-occurrences-of-selected-word-in-vscode

**Comment by dodoru** [comment]
![image](https://user-images.githubusercontent.com/9798501/84343716-87a2c380-abdb-11ea-8964-1068f5d09b88.png)

```
{
  "key": "shift+cmd+l",
  "command": "editor.action.selectHighlights",
  "when": "editorFocus"
}
{
  "key": "shift+cmd+l",
  "command": "extension.findBySelection"
}
{
  "key": "shift+cmd+l",
  "command": "addCursorsAtSearchResults",
  "when": "fileMatchOrMatchFocus && searchViewletVisible"
}
{
  "key": "shift+cmd+l",
  "command": "selectAllSearchEditorMatches",
  "when": "inSearchEditor"
}
```


@sandy081  I install the keymap extension:  [k--kato.intellij-idea-keybindings](https://marketplace.visualstudio.com/items?itemName=ms-vscode.resharper9-keybindings) recommended by vscode

**Comment by sandy081** [comment]
Looks like this keymap extension is outdated, please file an issue against it.
