### ISSUE TITLE
Github is not appearing 

### ISSUE THREAD

**Issue by Rajkiran44** [microsoft/vscode#99741]
Issue Type: <b>Bug</b>

Github is not appearing  in vs code 

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.63GB (6.55GB free)|
|Process Argv|--folder-uri file:///g%3A/SPFX%20Project/Helloworld-Webpart|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.12.8

</details>

**Comment by IllusionMH** [comment]
Could you specify when you expect GitHub to appear in VS Code? Andi what exactly "appearing in VS Code" means?

There is an extension for working with GitHub (PRs, Issues) https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github but it's not in your list.
