### ISSUE TITLE
Improve Extension version information for updates

### ISSUE THREAD

**Issue by VishalMadhvani** [Microsoft/vscode#9974]
- VSCode Version: Version 1.4.0-insider (1.4.0-insider) 4656fe3ff2952e9538d81e7a7571674352e5d62f
- OS Version: Mac OS X EL Capitan 

I am currently being offered an Extension update but its not immediately obvious what my current version is and what the latest version I will be updated to is.

In the screenshot below, there is version 1.2.2, which I assume is the current version because that panel is showing my currently installed extensions. But if I click on update which version will I get?

My suggestion is to add something like "Currently Installed Version: {CurrentVersion}" and "Latest Version: {LatestVersion}" to the panel showing the Extension Information. So for example just above the Update and Uninstall buttons.

<img width="1280" alt="screen shot 2016-07-30 at 12 46 27" src="https://cloud.githubusercontent.com/assets/1994627/17270159/29c00a1a-5654-11e6-93e9-be5f1704a8f5.png">

**Comment by joaomoreno** [comment]
This is fixed.
