### ISSUE TITLE
Introduce noDebug flag to DebugSessionOptions

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#99743]
Code pointer:
https://github.com/microsoft/vscode/blob/e9426456b63862ac76252d49b7354937e7394988/src/vs/workbench/api/browser/mainThreadDebugService.ts#L232

`startDebugging` api makes an assumption that `noDebug` is false
The problem is shown when you want to Run Without Debugging using js-debug. The breakpoints are still hit.

Not sure who authored this code originally. Assigning all 3 of us, I can also look into it.
Assigning to June so we look into this if possible.

**Comment by weinand** [comment]
@isidorn IIRC you've introduced the VS Code API `DebugSessionOptions` which only surfaces a `parentSession` and a `consoleMode`. I understand that it would make sense to have a `noDebug` property on `DebugSessionOptions` because this makes it possible to use `startDebugging` both for the "debug" and the "run without debugging" cases.

So in June we should introduce the `noDebug` property on `DebugSessionOptions`.

But the way how `DebugSessionOptions` is converted into the internal `IDebugSessionOptions` is questionable but I do not really understand why the current hardcoded "false" results in the problem we are seeing with js-debug.

Are there three possible semantics for "noDebug" in `DebugSessionOptions`:
- false: start debugging
- true: run without debuging
- undefined: the decision is made somewhere else

**Comment by isidorn** [comment]
Good point, we can introduce that to the options.

There are just two ways how noDebug is interpretted:
If it is passed and true we set that `noDebug: true` otherwise we do not set the noDebug attribute in the launch configuration.

The hardcoded false results in the problem becuase:
1. User starts debugging with noDebug: true
2. VS Code sends to this js-debug
3. JS-debug wants to create a child session and calls the startDebugging api
4. The startDebugging api set the noDebug to false and thus the new session does not have a noDebug field set.

**Comment by weinand** [comment]
So the smallest fix for js-debug would be to pass a `noDebug` received for the parent session via `startDebugging` to a child session, correct?

**Comment by isidorn** [comment]
@weinand yes, the js-debug could pass a `noDebug` flag to the child session configuration.
Makes sense for the description of the settings.
Before we introduce this option though let's see what @connor4312 thinks

**Comment by isidorn** [comment]
As agreed I have surfaced the `noDebug` property on the DebugSessionOptions, thus adding API proposal so I bring this up in next weeks api sync fyi @jrieken
I have also changed the behavior of `noDebug` such that when `undefined` the behvaior of the parent session is inhereted.

@connor4312 since I will take this issue through the API process maybe we create a seperate one for js-debug and we unassign you from this one?

**Comment by connor4312** [comment]
Works for me

**Comment by isidorn** [comment]
For reference here's the js-debug issue https://github.com/microsoft/vscode-js-debug/issues/523

**Comment by weinand** [comment]
@isidorn the comment for `noDebug` does not yet explain (the new behavior) when `noDebug` is missing.

**Comment by isidorn** [comment]
@weinand thanks, tackled this via 9bebaefc7b

**Comment by isidorn** [comment]
We have done what we planned for this milestone.
Thus moving this out to on-deck and changing to api-finalisation.
Will create a test plan item to cover this.

**Comment by isidorn** [comment]
We plan to finalize this API this August milestone. Just in case there is more feedback before we finalize it.

fyi @connor4312

**Comment by connor4312** [comment]
I've adopted this in js-debug for setting noDebug in child sessions. Work well, no complaints :)

**Comment by isidorn** [comment]
I have finalized this and created this test plan item to cover the finalisation 
https://github.com/microsoft/vscode/issues/104986

@connor4312 @weinand please assign yourself if you feel like testing this. Only one tester is need, since this is just finalisation
