### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by Solido-Naso** [microsoft/vscode#99754]
Issue Type: <b>Bug</b>

- Aller dans paramètres
- Section "Auto Save", le lien est mort

![vscode](https://user-images.githubusercontent.com/54780116/84266977-a777b000-ab25-11ea-833c-6a7b4899059a.png)
![lien mort](https://user-images.githubusercontent.com/54780116/84267018-b8c0bc80-ab25-11ea-9b08-ca563617009a.png)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

**Comment by janbaltus** [comment]
Fixed in 1.46.4 LP version.

**Comment by lukaschal** [comment]
Fixed on DEU and ESN as well.
