### ISSUE TITLE
Notebook: blinking cursor very close to border

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#99755]
![image](https://user-images.githubusercontent.com/900690/84267087-d2620400-ab25-11ea-8d42-a40b456a9a6d.png)

I feel that maybe a bit of margins would make this look better.

**Comment by rebornix** [comment]
what it looks now in Insiders

![image](https://user-images.githubusercontent.com/876920/85638981-3ca59900-b63c-11ea-8cf1-2e373f6c6aa2.png)

we always show margin for the editor. We can reopen this issue you see it again.
