### ISSUE TITLE
Autocomplete font size doesn't change with font-size changes

### ISSUE THREAD

**Issue by fanckush** [Microsoft/vscode#9975]
- VSCode Version: 1.3.1
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. increase font of text, text gets bigger (or smaller)
2. type => autocomplete shows => font of autocomplete text is still small (or big)

Of course, i know that the auto complete font becomes bigger when i use the zoom feature, but soon scales everything and that is different.
<img width="686" alt="screen shot 2016-07-30 at 3 23 02 pm" src="https://cloud.githubusercontent.com/assets/6278713/17270366/9645b17a-5669-11e6-8cf5-74d0763e74c6.png">

**Comment by joaomoreno** [comment]
#2465
