### ISSUE TITLE
Unable to create file in vscode 

### ISSUE THREAD

**Issue by sfdcscenarios** [microsoft/vscode#99759]
Hi I am not able to create any file in the vscode though I have configured required settings. I am able to edit existing code. Could you please help me on this.
![image](https://user-images.githubusercontent.com/65494755/84273302-22ec5800-ab4c-11ea-9585-3e26a827468f.png)

**Comment by isidorn** [comment]
Creating files in vscode should just work.
That warning is unrelated.
