### ISSUE TITLE
Opening and executing a notebook cell does not mark the tab as "open"

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#99765]
1. Open notebook
2. Execute a cell either via the "Execute All" or a single cell
3. Notice the editor tab is in italics, meaning it's not "open"
4. Navigate to a different file
5. :bug: notebook tab is gone

![image](https://user-images.githubusercontent.com/35271042/84282036-1cc78e80-aaee-11ea-9388-e5e3682e1ca1.png)

I would expect that when I run a cell that it stays open. It isn't until I perform an action, like edit text or delete cells, that it registers.

**Comment by rebornix** [comment]
Now whenever users execute a cell or a document, the editor will be pinned immediately, similar to how content changes work.
