### ISSUE TITLE
Enablement using listDoubleSelection and listMultiSelection not working in contributed view

### ISSUE THREAD

**Issue by aeisenberg** [microsoft/vscode#99767]
Issue Type: <b>Bug</b>

I am creating an extension with a custom view. I am trying to make sure that certain commands are only enabled when there are two items selected and other commands when only a single item is selected.

I have tried using `"enablement": "listDoubleSelection"` and `"enablement": "!listMultiSelection"` in the command declaration for these cases. However, it looks like the values `listMultiSelection` and `listDoubleSelection` are always false. 

Perhaps I'm doing something wrong, but I'm pretty sure I'm following the docs.

I'm attaching a zip of a sample project that illustrates the problem I'm having.

[multi-select-bug.zip](https://github.com/microsoft/vscode/files/4759712/multi-select-bug.zip)

To reproduce:

1. unzip the workspace above
2. open workspace in vscode
3. run the extension
4. open the view with the icon like this: <img width="46" alt="package_json_—_multi-select-bug" src="https://user-images.githubusercontent.com/363559/84289932-eee74780-aaf7-11ea-8ff2-a4d478161beb.png">
5. select one or multiple items in the list view and right click. Notice that the enablement of the commands does not follow what is in the package.json file.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|64.00GB (34.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.36.0
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
tsl-problem-matcher|eam|0.2.0
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.0.0
vscode-diff|fab|1.4.0
wolfram-language|fli|0.1.0
vscode-codeql|Git|1.2.2
vscode-pull-request-github|Git|0.16.0
vscode-test-explorer|hbe|2.19.1
mysql-syntax|jak|1.3.1
vscode-edit-csv|jan|0.2.9
code-beautifier|mic|2.3.3
vscode-docker|ms-|1.2.1
azure-account|ms-|0.8.11
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2274
debugger-for-chrome|msj|4.12.8
vscode-react-native|msj|0.16.0
vscode-zipexplorer|sle|0.3.1
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
It looks like `listDoubleSelection` and `listMultiSelection` are not implemented for extension provided tree views. @joaomoreno, is this something you would consider adding at a lower level, or should I add this as a consumer of `WorkbenchAsyncDataTree`?

**Comment by joaomoreno** [comment]
They should 🤔 :

https://github.com/microsoft/vscode/blob/cadabab73fef89fe0c4bfe23b5a33cd58e39ea9c/src/vs/platform/list/browser/listService.ts#L867-L869

**Comment by joaomoreno** [comment]
@alexr00  Where is that `enablement` value read, in our code base?

**Comment by alexr00** [comment]
I see it read here:
https://github.com/microsoft/vscode/blob/21e43b670352ff1fdc8a75737c4ea76d5f22a916/src/vs/workbench/api/common/menusExtensionPoint.ts#L411-L411
Then that `precondition` gets read in many places. Not sure which one is applicable here, but can do some digging.

**Comment by petrbroz** [comment]
This is probably related: I've been trying to achieve the same thing (showing/hiding specific commands in a custom tree view based on whether there are multiple items selected) by using `listMultiSelection` in the `when` clause, but with no luck.

If it is in fact possible to show/hide `view/item/context` items based on the selection count, is that documented anywhere? Thanks!

**Comment by joaomoreno** [comment]
@alexr00 I would've made some $$$ here. 💸

**Comment by alexr00** [comment]
@joaomoreno indeed you would. Thanks for the context key service idea!
