### ISSUE TITLE
Quick open: include history results when searching by name

### ISSUE THREAD

**Issue by Blaisorblade** [microsoft/vscode#99762]
In VSCode, Ctrl/Cmd-P "Go to file", in particular lets me find open files quickly, but doesn't let me find HtmlViews, such as previews for Markdown files, or VSCoq ProofViews (https://github.com/coq-community/vscoq/issues/144).

That's despite the fact that ProofViews show up in the drop down list. To wit, here are ProofViews (at least, once you select the right pane):
![image](https://user-images.githubusercontent.com/289960/84272509-caa65d80-ab2d-11ea-989c-5979e4691595.png)

and here they disappear in the fuzzy search:
![image](https://user-images.githubusercontent.com/289960/84272542-d85be300-ab2d-11ea-9bdb-f53eb1ad0c87.png)

**Comment by bpasero** [comment]
@Blaisorblade did you try `Ctrl+Tab` for a pure searchable list of editors?

**Comment by Blaisorblade** [comment]
I don't see a (fuzzy or not) search in it:
![image](https://user-images.githubusercontent.com/289960/84369245-d8fc8400-abd6-11ea-8b24-8353fc90ac68.png). I didn't know about it.

The real question might be "why do you have enough non-file editors that you'd want fuzzy search".

**Comment by Blaisorblade** [comment]
I don't see a (fuzzy or not) search in it:
![image](https://user-images.githubusercontent.com/289960/84369245-d8fc8400-abd6-11ea-8b24-8353fc90ac68.png)
(tho I didn't know about it before).

The real question might be "why do you have enough non-file editors that you'd want fuzzy search"; and I'm not sure my answer generalizes enough.

**Comment by bpasero** [comment]
@Blaisorblade I mean this:

![image](https://user-images.githubusercontent.com/900690/84370779-06e2c800-abd9-11ea-8583-49c2bd3dc92b.png)

It brings up a quick open for editors that are open where you can search.

**Comment by Blaisorblade** [comment]
Oooh, thanks a lot! That's what I wanted 🎉 ; closing!
