### ISSUE TITLE
Weak Hash used - MD5

### ISSUE THREAD

**Issue by hmwoliul** [microsoft/vscode#99760]
### **MD5** is a a weak hash which is known to have collision. Use a strong hashing function.

1. https://github.com/microsoft/vscode/blob/ae8f171355908be0158360f769f23e4779c2f3c8/src/vs/loader.js#L819-L819
2. https://github.com/microsoft/vscode/blob/ae8f171355908be0158360f769f23e4779c2f3c8/src/vs/loader.js#L852-L852
3. https://github.com/microsoft/vscode/blob/ae8f171355908be0158360f769f23e4779c2f3c8/src/vs/loader.js#L923-L923
4. https://github.com/microsoft/vscode/blob/4b8e02ee1d3ae8ac2cb417452d3dac2a99c55dd8/build/gulpfile.vscode.js#L140-L140

**Comment by alexdima** [comment]
The md5 hash is used as a simple checksum to double check that the installation is not corrupt on disk. It does not serve any security purposes. The consequence of the md5 checksum not matching is that we show a popup indicating that the installation is corrupt on disk and asking people to reinstall VS Code.

IMHO this is a valid use-case of the `md5` hash algorihtm, even if the `md5` algorithm is considered weak.
