### ISSUE TITLE
Incorrect syntax highlight of async on arrow functions

### ISSUE THREAD

**Issue by hh10k** [Microsoft/vscode#9976]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

1.  Within a .js or .ts file, add an async lambda function like `async () => {}`
2. Observe that the `async` does not have the expected keyword color, as it would when used before function():

![asyncsyntaxhighlight](https://cloud.githubusercontent.com/assets/2985923/17270580/33e813ae-5698-11e6-9cbb-0e7a6503ed76.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#226
