### ISSUE TITLE
PHP Syntax highlighting wrong when I playing with quotes

### ISSUE THREAD

**Issue by denikod** [microsoft/vscode#99773]
Issue Type: <b>Bug</b>

Heej,

I found some syntax highlighting wrong when I use single and double quotes following the word "AND" in my string concat expression.

The example code you can see bellow:
```php
<?php
	$array = array(1,2,3,4,5);

	// Syntax highlighting is wrong:
	$s = " AND IN('" . implode("','", $array) . "')";
	
	// And normal if insert break-line:
	$s = " AND IN('"
			. implode("','", $array) . "')";

	// or use single quote:
	$s = ' AND IN(\'' . implode("','", $array) . "')";

?>
```
Screenshot: [http://prntscr.com/sxcyj6](http://prntscr.com/sxcyj6)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3502)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (6.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|13%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.0.1
alignment|ann|0.3.0
vscode-intelephense-client|bme|1.4.1
vscode-eslint|dba|2.1.5
expressionengine|jrr|0.4.1
vsc-expressionengine|min|2.1.2
python|ms-|2020.5.86398
sublime-keybindings|ms-|4.0.7
php-docblocker|nei|2.1.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
I think this is the same as https://github.com/atom/language-php/issues/392
