### ISSUE TITLE
Keys randomly stop working (arrows and lots of others); It seems key codes are not even being read

### ISSUE THREAD

**Issue by malvim** [microsoft/vscode#99777]
- VSCode Version:  Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
- OS Version: Ubuntu 20.04 (Linux x64 5.4.0-33-generic)

Steps to Reproduce:

Okay, I was writing a lot of stuff because it seemed I couldn't reproduce it consistently, but I found a way while reporting this, so I'm keeping it all but putting the deterministic steps to reproduce up here:

While everything seems to be working:
1. Press `alt` to activate menu bar;
2. Press `downArrow` to bring down the `File` menu;
3. Pres `Esc` twice to hide the menu and "deactivate" the menu bar, getting focus back to the editor
4. Arrows and most keys completely stop working. A few keys and combinations still work

So on to what I had written earlier:

So I've read a lot on stackoverflow and here on github wikis and issues, and none of the fixes seemed to work. I've copied my keymappings.json file at the end of this issue. I've also tested switching to keycode and it doesn't solve the issue. So here are some details and observations:

- It seems to happen more when I'm coming to vscode from another workspace (I use vscode on full-screen mode and usually switch to it from other workspaces using `ctrl`+`alt`+`downArrow`)
- Keys sometimes work in the beginning, but as soon as I try to navigate my code using arrows (and sometimes `ctrl`-`arrows` to navigate between words), they stop
- MOST letters also stop working (not sure it matters, but I've tried every letter key, and only `w`, `f`, `g`, `j`, `z`, and `n` worked, no idea why)

Now on to the things I find more interesting:
    
- pressing `alt` twice quickly to show and hide the menu bar again seem to get things back to work
- when I go to key bindings to try to see what codes are being sent (as per the wiki - go to key bindings, simulate creating a new key binding, press the desired key, mouseover to see the codes): the key *doesn't even show*, so I can't check codes! 

Does this issue occur when all extensions are disabled?: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3245)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.50GB (1.84GB free)|
|Process Argv|. --disable-gpu|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

<details>
<summary>Keymappings.json</summary>
{
	"layout": {
		"model": "pc105",
		"layout": "us,us,us",
		"variant": ",intl,",
		"options": "",
		"rules": "evdev"
	},
	"rawMapping": {
		"Sleep": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"WakeUp": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"KeyA": {
			"value": "a",
			"withShift": "A",
			"withAltGr": "a",
			"withShiftAltGr": "A"
		},
		"KeyB": {
			"value": "b",
			"withShift": "B",
			"withAltGr": "b",
			"withShiftAltGr": "B"
		},
		"KeyC": {
			"value": "c",
			"withShift": "C",
			"withAltGr": "c",
			"withShiftAltGr": "C"
		},
		"KeyD": {
			"value": "d",
			"withShift": "D",
			"withAltGr": "d",
			"withShiftAltGr": "D"
		},
		"KeyE": {
			"value": "e",
			"withShift": "E",
			"withAltGr": "e",
			"withShiftAltGr": "E"
		},
		"KeyF": {
			"value": "f",
			"withShift": "F",
			"withAltGr": "f",
			"withShiftAltGr": "F"
		},
		"KeyG": {
			"value": "g",
			"withShift": "G",
			"withAltGr": "g",
			"withShiftAltGr": "G"
		},
		"KeyH": {
			"value": "h",
			"withShift": "H",
			"withAltGr": "h",
			"withShiftAltGr": "H"
		},
		"KeyI": {
			"value": "i",
			"withShift": "I",
			"withAltGr": "i",
			"withShiftAltGr": "I"
		},
		"KeyJ": {
			"value": "j",
			"withShift": "J",
			"withAltGr": "j",
			"withShiftAltGr": "J"
		},
		"KeyK": {
			"value": "k",
			"withShift": "K",
			"withAltGr": "k",
			"withShiftAltGr": "K"
		},
		"KeyL": {
			"value": "l",
			"withShift": "L",
			"withAltGr": "l",
			"withShiftAltGr": "L"
		},
		"KeyM": {
			"value": "m",
			"withShift": "M",
			"withAltGr": "m",
			"withShiftAltGr": "M"
		},
		"KeyN": {
			"value": "n",
			"withShift": "N",
			"withAltGr": "n",
			"withShiftAltGr": "N"
		},
		"KeyO": {
			"value": "o",
			"withShift": "O",
			"withAltGr": "o",
			"withShiftAltGr": "O"
		},
		"KeyP": {
			"value": "p",
			"withShift": "P",
			"withAltGr": "p",
			"withShiftAltGr": "P"
		},
		"KeyQ": {
			"value": "q",
			"withShift": "Q",
			"withAltGr": "q",
			"withShiftAltGr": "Q"
		},
		"KeyR": {
			"value": "r",
			"withShift": "R",
			"withAltGr": "r",
			"withShiftAltGr": "R"
		},
		"KeyS": {
			"value": "s",
			"withShift": "S",
			"withAltGr": "s",
			"withShiftAltGr": "S"
		},
		"KeyT": {
			"value": "t",
			"withShift": "T",
			"withAltGr": "t",
			"withShiftAltGr": "T"
		},
		"KeyU": {
			"value": "u",
			"withShift": "U",
			"withAltGr": "u",
			"withShiftAltGr": "U"
		},
		"KeyV": {
			"value": "v",
			"withShift": "V",
			"withAltGr": "v",
			"withShiftAltGr": "V"
		},
		"KeyW": {
			"value": "w",
			"withShift": "W",
			"withAltGr": "w",
			"withShiftAltGr": "W"
		},
		"KeyX": {
			"value": "x",
			"withShift": "X",
			"withAltGr": "x",
			"withShiftAltGr": "X"
		},
		"KeyY": {
			"value": "y",
			"withShift": "Y",
			"withAltGr": "y",
			"withShiftAltGr": "Y"
		},
		"KeyZ": {
			"value": "z",
			"withShift": "Z",
			"withAltGr": "z",
			"withShiftAltGr": "Z"
		},
		"Digit1": {
			"value": "1",
			"withShift": "!",
			"withAltGr": "1",
			"withShiftAltGr": "!"
		},
		"Digit2": {
			"value": "2",
			"withShift": "@",
			"withAltGr": "2",
			"withShiftAltGr": "@"
		},
		"Digit3": {
			"value": "3",
			"withShift": "#",
			"withAltGr": "3",
			"withShiftAltGr": "#"
		},
		"Digit4": {
			"value": "4",
			"withShift": "$",
			"withAltGr": "4",
			"withShiftAltGr": "$"
		},
		"Digit5": {
			"value": "5",
			"withShift": "%",
			"withAltGr": "5",
			"withShiftAltGr": "%"
		},
		"Digit6": {
			"value": "6",
			"withShift": "^",
			"withAltGr": "6",
			"withShiftAltGr": "^"
		},
		"Digit7": {
			"value": "7",
			"withShift": "&",
			"withAltGr": "7",
			"withShiftAltGr": "&"
		},
		"Digit8": {
			"value": "8",
			"withShift": "*",
			"withAltGr": "8",
			"withShiftAltGr": "*"
		},
		"Digit9": {
			"value": "9",
			"withShift": "(",
			"withAltGr": "9",
			"withShiftAltGr": "("
		},
		"Digit0": {
			"value": "0",
			"withShift": ")",
			"withAltGr": "0",
			"withShiftAltGr": ")"
		},
		"Enter": {
			"value": "\r",
			"withShift": "\r",
			"withAltGr": "\r",
			"withShiftAltGr": "\r"
		},
		"Escape": {
			"value": "\u001b",
			"withShift": "\u001b",
			"withAltGr": "\u001b",
			"withShiftAltGr": "\u001b"
		},
		"Backspace": {
			"value": "\b",
			"withShift": "\b",
			"withAltGr": "\b",
			"withShiftAltGr": "\b"
		},
		"Tab": {
			"value": "\t",
			"withShift": "",
			"withAltGr": "\t",
			"withShiftAltGr": ""
		},
		"Space": {
			"value": " ",
			"withShift": " ",
			"withAltGr": " ",
			"withShiftAltGr": " "
		},
		"Minus": {
			"value": "-",
			"withShift": "_",
			"withAltGr": "-",
			"withShiftAltGr": "_"
		},
		"Equal": {
			"value": "=",
			"withShift": "+",
			"withAltGr": "=",
			"withShiftAltGr": "+"
		},
		"BracketLeft": {
			"value": "[",
			"withShift": "{",
			"withAltGr": "[",
			"withShiftAltGr": "{"
		},
		"BracketRight": {
			"value": "]",
			"withShift": "}",
			"withAltGr": "]",
			"withShiftAltGr": "}"
		},
		"Backslash": {
			"value": "\\",
			"withShift": "|",
			"withAltGr": "\\",
			"withShiftAltGr": "|"
		},
		"Semicolon": {
			"value": ";",
			"withShift": ":",
			"withAltGr": ";",
			"withShiftAltGr": ":"
		},
		"Quote": {
			"value": "'",
			"withShift": "\"",
			"withAltGr": "'",
			"withShiftAltGr": "\""
		},
		"Backquote": {
			"value": "`",
			"withShift": "~",
			"withAltGr": "`",
			"withShiftAltGr": "~"
		},
		"Comma": {
			"value": ",",
			"withShift": "<",
			"withAltGr": ",",
			"withShiftAltGr": "<"
		},
		"Period": {
			"value": ".",
			"withShift": ">",
			"withAltGr": ".",
			"withShiftAltGr": ">"
		},
		"Slash": {
			"value": "/",
			"withShift": "?",
			"withAltGr": "/",
			"withShiftAltGr": "?"
		},
		"CapsLock": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F1": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F2": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F3": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F4": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F5": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F6": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F7": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F8": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F9": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F10": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F11": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F12": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"PrintScreen": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"ScrollLock": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Pause": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Insert": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Home": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"PageUp": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Delete": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"End": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"PageDown": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"ArrowRight": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"ArrowLeft": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"ArrowDown": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"ArrowUp": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"NumLock": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"NumpadDivide": {
			"value": "/",
			"withShift": "/",
			"withAltGr": "/",
			"withShiftAltGr": "/"
		},
		"NumpadMultiply": {
			"value": "*",
			"withShift": "*",
			"withAltGr": "*",
			"withShiftAltGr": "*"
		},
		"NumpadSubtract": {
			"value": "-",
			"withShift": "-",
			"withAltGr": "-",
			"withShiftAltGr": "-"
		},
		"NumpadAdd": {
			"value": "+",
			"withShift": "+",
			"withAltGr": "+",
			"withShiftAltGr": "+"
		},
		"NumpadEnter": {
			"value": "\r",
			"withShift": "\r",
			"withAltGr": "\r",
			"withShiftAltGr": "\r"
		},
		"Numpad1": {
			"value": "",
			"withShift": "1",
			"withAltGr": "",
			"withShiftAltGr": "1"
		},
		"Numpad2": {
			"value": "",
			"withShift": "2",
			"withAltGr": "",
			"withShiftAltGr": "2"
		},
		"Numpad3": {
			"value": "",
			"withShift": "3",
			"withAltGr": "",
			"withShiftAltGr": "3"
		},
		"Numpad4": {
			"value": "",
			"withShift": "4",
			"withAltGr": "",
			"withShiftAltGr": "4"
		},
		"Numpad5": {
			"value": "",
			"withShift": "5",
			"withAltGr": "",
			"withShiftAltGr": "5"
		},
		"Numpad6": {
			"value": "",
			"withShift": "6",
			"withAltGr": "",
			"withShiftAltGr": "6"
		},
		"Numpad7": {
			"value": "",
			"withShift": "7",
			"withAltGr": "",
			"withShiftAltGr": "7"
		},
		"Numpad8": {
			"value": "",
			"withShift": "8",
			"withAltGr": "",
			"withShiftAltGr": "8"
		},
		"Numpad9": {
			"value": "",
			"withShift": "9",
			"withAltGr": "",
			"withShiftAltGr": "9"
		},
		"Numpad0": {
			"value": "",
			"withShift": "0",
			"withAltGr": "",
			"withShiftAltGr": "0"
		},
		"NumpadDecimal": {
			"value": "",
			"withShift": ".",
			"withAltGr": "",
			"withShiftAltGr": "."
		},
		"IntlBackslash": {
			"value": "<",
			"withShift": ">",
			"withAltGr": "|",
			"withShiftAltGr": "¦"
		},
		"ContextMenu": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Power": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"NumpadEqual": {
			"value": "=",
			"withShift": "=",
			"withAltGr": "=",
			"withShiftAltGr": "="
		},
		"F13": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F14": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F15": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F16": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F17": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F18": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F19": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F20": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F21": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F22": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F23": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"F24": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Open": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Help": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Select": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Again": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Undo": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Cut": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Copy": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Paste": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Find": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"AudioVolumeMute": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"AudioVolumeUp": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"AudioVolumeDown": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"NumpadComma": {
			"value": ".",
			"withShift": ".",
			"withAltGr": ".",
			"withShiftAltGr": "."
		},
		"IntlRo": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"KanaMode": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"IntlYen": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Convert": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"NonConvert": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Lang1": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Lang2": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Lang3": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Lang4": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Lang5": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"NumpadParenLeft": {
			"value": "(",
			"withShift": "(",
			"withAltGr": "(",
			"withShiftAltGr": "("
		},
		"NumpadParenRight": {
			"value": ")",
			"withShift": ")",
			"withAltGr": ")",
			"withShiftAltGr": ")"
		},
		"ControlLeft": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"ShiftLeft": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"AltLeft": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"MetaLeft": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"ControlRight": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"ShiftRight": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"AltRight": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"MetaRight": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"BrightnessUp": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"BrightnessDown": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"MediaPlay": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"MediaRecord": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"MediaFastForward": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"MediaRewind": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"MediaTrackNext": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"MediaTrackPrevious": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"MediaStop": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"Eject": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"MediaPlayPause": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"MediaSelect": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"LaunchMail": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"LaunchApp2": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"LaunchApp1": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"SelectTask": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"LaunchScreenSaver": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"BrowserSearch": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"BrowserHome": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"BrowserBack": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"BrowserForward": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"BrowserStop": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"BrowserRefresh": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"BrowserFavorites": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"MailReply": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"MailForward": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		},
		"MailSend": {
			"value": "",
			"withShift": "",
			"withAltGr": "",
			"withShiftAltGr": ""
		}
	}
}
>/details>

**Comment by bkarlson** [comment]
I'm experiencing somewhat similar issue on OSX: Option (alt) key at random stops working __system wide__ (even no scan code, I thought my keyboard is dying), but after re-opening VSCode Keyboard shortcuts settings the key is alive again. 

Right now it stopped again for not reason, but after mingling with Shift and Fn buttons it works again. Really bizarre behaviour, I could not find any other issues related to OSX, so I'll keep observing and maybe will post here again.

Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

**Comment by jhpratt** [comment]
Running into this on Ubuntu 20.04. The only key that appears to be affected for me is the <kbd>End</kbd> key. It is somewhat random, as if I press it multiple times, it'll work eventually. Holding it down does _not_ do anything different.

**Comment by orochies** [comment]
exactly the same problem in Ubuntu 20.04 x64

Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:08.304Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-37-generic snap

**Comment by alexdima** [comment]
> when I go to key bindings to try to see what codes are being sent (as per the wiki - go to key bindings, simulate creating a new key binding, press the desired key, mouseover to see the codes): the key doesn't even show, so I can't check codes!

This indicates that we don't receive the keybindings from the OS.

Since you mentioned that it has a lot to do with focusing / unfocusing the menus, I wonder if you tried `"window.titleBarStyle": "custom"` which means we would render the menu ourselves in HTML, perhaps the menu is the one that captures keystrokes...
