### ISSUE TITLE
Create a new untitled file with default template instead of blank content

### ISSUE THREAD

**Issue by Suphias** [Microsoft/vscode#9977]
- VSCode Version: 版本 1.3.1 (1.3.1)
- OS Version: OS X Yosemite 10.10.5

Steps to Reproduce:
1. 文件》新建文件

Q：创建一个文件，里面一片空白，有填充基本内容（例如using, namespace等）的快速方法吗？

**Comment by be5invis** [comment]
Translate: Provide ability to fill predefined contents for new files.

**Comment by kieferrm** [comment]
@Suphias can you pls describe your concrete use case? Thanks!

**Comment by yeluoqiuzhi** [comment]
he only wanted to create file from template.

**Comment by rebornix** [comment]
What @Suphias wants is creating new file with template. This can be a good extension by customizing `workbench.action.files.newUntitledFile` IMHO.

For now it can be archived by [code snippet](https://code.visualstudio.com/docs/customization/userdefinedsnippets), even though it requires an additional operation.

**Comment by aeschli** [comment]
We also suggest to use the yeoman to scaffold projects.

**Comment by bpasero** [comment]
Closing, this can and should be done via extension.
