### ISSUE TITLE
suddenly shutdown cause errors at working tree 

### ISSUE THREAD

**Issue by hpbonfim** [microsoft/vscode#99774]
The first error came when my notebook shutdown suddenly and I turn on with vscode with error (_Unable to open 'es6.code-search (Working Tree)': Cannot register more than one working copy with the same resource file:///Users/hpbonfim/Code/vscode/.vscode/searches/es6.code-search_) so I open the folder .vscode/searches/es6.code-search  and works fine after remove the file and reopen all projects folder again.

- VSCode Version: 1.45.1
- OS Version: Linux x64

Steps to Reproduce:

1. open 9 files with 3 different folders
2. shutdown suddenly
3. reopen vscode

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by JacksonKearl** [comment]
Had you opened `vscode/.vscode/searches/es6.code-search` recently?

**Comment by hpbonfim** [comment]
@JacksonKearl  but i had installed some plugins for my vscode and changed some config in settings.json

**Comment by JacksonKearl** [comment]
This should be fixed now with 71776589163b831768c408bcad2a87d73941bbb6.
