### ISSUE TITLE
Support --enabled-proposed-api thorugh argv.json

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#99775]
Currently, extensions which use proposed API's cannot be run on product builds without passing the `--enabled-proposed-api [...ext-id's...]` CLI flag. This makes long-term dogfooding of proposed API's and the extensions which use them very inconvenient for people (such as myself) who tend to open VS Code without the CLI and thus cannot pass CLI arguments. 

For instance, I have made extensions using the timeline view that I'd like to use in daily life to get more testing in to the Timeline API and provide feedback, but it's not worth it to manually edit `product.json` every day. I think as a "big kid" VS Code user I should be able to opt-in to enabling unstable features that might break at any point (that's what Insiders is all about, right?).

To this end, it would be nice if we could additionally enable proposed API's in the existing `argv.json` file. The main concern with doing this is that bad actors could in theory edit this file from the extension, but they could already edit `product.json`, so doing this isn't really adding any new holes. 

cc @eamodio @jrieken

**Comment by bpasero** [comment]
If someone has energy, be my guest. No work planned from my end.

**Comment by bpasero** [comment]
@JacksonKearl thanks, please keep in mind test plan item and/or verification needed.

**Comment by JacksonKearl** [comment]
@bpasero thanks, I always forget about that. (Maybe a bot...)
