### ISSUE TITLE
Auto-updater breaks VSCode instance

### ISSUE THREAD

**Issue by amayer42** [microsoft/vscode#99787]
Issue Type: <b>Bug</b>

## Actual Behavior

Occasionally once I close VSCode and the auto updater starts.  I get an error pop-up from the updater saying that it is unable to access a file and to ensure that all instances of VSCode are closed.

After checking that the only instance is the updater itself, hitting try again results in the same pop-up.  Hitting cancel causes the auto-updater to encounter an error which causes the VSCode shortcut icons that I have to disappear and causes VSCode to become un-openable.

In order to fix this, I must go and uninstall VSCode and re-install it entirely.

## Expected Behavior

The VSCode auto updater should not bork the VSCode instance.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (18.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.901.9
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.0
bracket-pair-colorizer-2|Coe|0.1.4
angular-schematics|cyr|4.1.0
vscode-markdownlint|Dav|0.36.0
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.0.0
vscode-firefox-debug|fir|2.8.0
vscode-github|Kni|0.30.3
vscode-scss|mrm|0.9.0
azure-pipelines|ms-|1.170.0
vscode-docker|ms-|1.2.1
csharp|ms-|1.22.0
azure-account|ms-|0.8.11
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2274
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.8
angular-console|nrw|12.0.0
material-icon-theme|PKi|4.1.0
vscode-yaml|red|0.8.0
code-spell-checker|str|1.9.0
vscodeintellicode|Vis|1.2.8
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
