### ISSUE TITLE
Notebook: very easy to scroll out of sight horisontally

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#99785]
Notebooks can be small visually, and scrollbars are not visible unless hovered.
Thus it is very easy for the user to accidently click on the horisontal scrollbar and be taken out of view.

First I suggest to put the scrollbar all the way to the bottom as mentioned here https://github.com/microsoft/vscode/issues/99781
Then I suggest to only render the scroll bar when there is somewhere to scroll to.
And potentialy not allow to scroll beyond last visible column

**Comment by misolori** [comment]
I believe these are all fixed already:

<img width="329" alt="CleanShot 2021-10-04 at 15 59 55@2x" src="https://user-images.githubusercontent.com/35271042/135935780-7a763209-1712-492e-9f65-6c51d9d37b8b.png">
