### ISSUE TITLE
Sync not working in new stable version 1.46.0

### ISSUE THREAD

**Issue by coaperator** [microsoft/vscode#99788]
- VSCode Version: 1.46
- OS Version: win 10

Steps to Reproduce:

1. install app

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/6645911/84313399-247b4780-ab6f-11ea-923c-5d4a043b5f85.png)
![image](https://user-images.githubusercontent.com/6645911/84313293-feee3e00-ab6e-11ea-8866-e36a67be8a6c.png)
![image](https://user-images.githubusercontent.com/6645911/84313354-12010e00-ab6f-11ea-9d16-912fe8293764.png)

**Comment by gjsjohnmurray** [comment]
See #97167 for a request to allow the Accounts icon to be hidden.

**Comment by sandy081** [comment]
Yes, we did not enable Sync yet in stable and the accounts icon is not only meant for sync but also for accounts user is being signed in to - Please check our release notes - https://code.visualstudio.com/updates/v1_46#_accounts-management

**Comment by hilari0n** [comment]
> 
> 
> Yes, we did not enable Sync yet in stable and the accounts icon is not only meant for sync but also for accounts user is being signed in to - Please check our release notes - https://code.visualstudio.com/updates/v1_46#_accounts-management

Athough I do actually sign in to some accounts in VSCode ("Team: Signin" from "Azure Repos" extension, "Azure: Sign In" & "Azure: Sign in to Azure Cloud" from "Azure Account" extension), the "Accounts" icon shows me nothing ("You are not signed in ...").
Shouldn't it be hidden until I actually have any extensions which do leverage it (the new API-s) or even until the extensions actually have something to show there? Now it is useless and appears as if it was something broken, (i.e. with no hint how you can actually put it to some use).

**Comment by gjsjohnmurray** [comment]
> Shouldn't it be hidden until I actually have any extensions which do leverage it (the new API-s) or even until the extensions actually have something to show there? Now it is useless and appears as if it was something broken, (i.e. with no hint how you can actually put it to some use).

Already suggested in https://github.com/microsoft/vscode/issues/99960#issuecomment-643276588
