### ISSUE TITLE
Notebook scrollbar rendered too high

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#99781]
Notice how the scrollbar in the notebook is too high compared to the space in the notebook. It should be 30 px lower, to be all the way to the bottom.
The current rendering make it look like it is floating in mid air

![Screenshot 2020-06-10 at 21 49 32](https://user-images.githubusercontent.com/1926584/84311858-53d88700-ab64-11ea-827b-d56336c940a8.png)

**Comment by greazer** [comment]
Time information is a much requested and appreciated by the DS community at large. So I don't think we should lose that, at least. We haven't heard any negative feedback about the horizontal scrollbar location, in relation.

**Comment by misolori** [comment]
I think we do a better job of this now:

<img width="440" src="https://user-images.githubusercontent.com/35271042/135935648-df0a64de-987a-4fa6-93f3-09e5e7d4d411.png">

<img width="340" alt="CleanShot 2021-10-04 at 15 57 57@2x" src="https://user-images.githubusercontent.com/35271042/135935645-55df049b-4506-43b8-b110-5081a8182d0a.png">
