### ISSUE TITLE
Change preferences sync log time to use UTC

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#99796]
This would make it easier to know what time a particular issue happened, without needing to know the user's timezone and calculating the difference. Currently the outputted time is local:

```
[2020-06-10 13:42:19.809] [userDataSync] [trace] Extensions: Merging remote extensions with local extensions...
[2020-06-10 13:42:19.810] [userDataSync] [info] Extensions: No changes found during synchronizing extensions.
[2020-06-10 13:42:19.810] [userDataSync] [trace] Extensions: Finished synchronizing extensions.
[2020-06-10 13:42:19.811] [userDataSync] [info] Sync done. Took 407ms
```

**Comment by sandy081** [comment]
We show all our logs in user's time zone. 

I see it makes it easy for us but I am worried that it will make it hard for users and confuses them. 

So not sure if it is a good idea to do.

**Comment by Tyriar** [comment]
@sandy081 just trying to save us iteration time by potentially needing to ask for their time zone to diagnose issues.

**Comment by sandy081** [comment]
Yeah I understand that but I do not know if it makes sense to have logs in UTC. 

@joaomoreno What do you suggest?

**Comment by joaomoreno** [comment]
I agree with @Tyriar, UTC seems to be a better choice for log files

**Comment by sandy081** [comment]
This need support from our `node-spdlog` library - Filed https://github.com/microsoft/node-spdlog/issues/8

**Comment by rzhao271** [comment]
I've been upgrading spdlog recently. It seems that we already expose a `logger.setPattern` API.
I have closed the upstream issue.

**Comment by sandy081** [comment]
It is, but I do not see the necessity and client time zone is more convenient as most of the logs are client side.
