### ISSUE TITLE
Using search causes computer to completely freeze

### ISSUE THREAD

**Issue by kdaulton-chwy** [microsoft/vscode#99792]
- VSCode Version: 1.45.1
- OS Version: MacOS Mojave 10.14.4

Steps to Reproduce:

1. Open a workspace
2. Navigate to the search controls
3. Type in a phrase

Does this issue occur when all extensions are disabled?: Not so far, but the issue only occurred intermittently with extensions added.

It's important to note this doesn't happen with every search, but does happen at least once a day. The effect is my computer becomes unusable to the point that I must force reboot it. This freeze has occurred on searches in workspaces varying from relatively small to fairly large file counts, using no include/exclude file filtering to aggressive include/exclude file filtering.

Example frozen search:
![search-that-froze-computer](https://user-images.githubusercontent.com/64433365/84314263-c1b98a00-ab35-11ea-8278-04d195515d46.jpg)

**Comment by roblourens** [comment]
There are a couple open issues which I think cover the same problem. I have never been able to reproduce it.

- Disabling `searchOnType` might help
- Is your mac low on free memory when this happens?

https://github.com/microsoft/vscode/issues/87254
https://github.com/microsoft/vscode/issues/88385
https://github.com/microsoft/vscode/issues/94903

**Comment by kdaulton-chwy** [comment]
@roblourens - 
I usually have 3-8gb free throughout the day out of 16gb of total memory. I'm would assume `searchOnType` might help, but seems like overkill to me. Especially when considering this hasn't ever occurred to me before until about the last few days. A few of my teammates have also starting having the same problem within the last few days too.
