### ISSUE TITLE
GitHub issue notebook: why gray background?

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#99791]
When I run my work query I get all the issues with a gray background.
Why not white? I think it would look more similar to GitHub, and would not look disabled as the current gray gives me that effect.

![Screenshot 2020-06-10 at 22 14 22](https://user-images.githubusercontent.com/1926584/84314128-d31b8a00-ab67-11ea-87df-d3a2fa0c6698.png)

**Comment by isidorn** [comment]
Great that this color is customisable.
@misolori Feel free to close this. I just personaly do not like it, due to the 2 reasons above: does not look like github and looks disabled.

**Comment by misolori** [comment]
I'll leave this open to see if others feel the same, in which case we can update the default color token in the light theme.

**Comment by rebornix** [comment]
The color is now customizable.
