### ISSUE TITLE
RCtrl+~ make vscode crash

### ISSUE THREAD

**Issue by Sshahar** [microsoft/vscode#99790]
<img width="273" alt="temp" src="https://user-images.githubusercontent.com/16301090/84313700-98b5eb00-ab6f-11ea-9e42-2ad77c0432b9.png">

- VSCode Version:
- OS Version:

Steps to Reproduce:

0. Set "Right Ctrl + Right Alt + `" shortcut to kill terminal
1. Press Right Ctrl + Right Alt + `
2. Press Right Ctrl + `

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sandy081** [comment]
Please follow this wiki - https://github.com/microsoft/vscode/wiki/Native-Crash-Issues and provide us requested information in there
