### ISSUE TITLE
Smooth scrolling does not apply in settings and extension views

### ISSUE THREAD

**Issue by musm** [microsoft/vscode#99798]
![image](https://user-images.githubusercontent.com/4319522/84317961-acdff500-ab3b-11ea-9631-4b4c1c9e7ada.png)

![image](https://user-images.githubusercontent.com/4319522/84317981-b5d0c680-ab3b-11ea-9f67-6adad5d93ae6.png)

Steps to Reproduce:

![1](https://user-images.githubusercontent.com/4319522/84317932-9fc30600-ab3b-11ea-9b4c-7685be4ac718.gif)

Does this issue occur when all extensions are disabled?: Yes 

# Notes
- Smooth scrolling is enabled throughout

- Smooth scrolling does not apply in the settings pane and also the extensions pane.

**Comment by ArturoDent** [comment]
You do specifically have the new `List: Smooth Scrolling` setting enabled?  It just came out today, disabled by default.  Designed to help lists and tree scrolling like the Explorer.  Just checking ;>}

**Comment by musm** [comment]
> You do specifically have the new `List: Smooth Scrolling` setting enabled? It just came out today, disabled by default. Designed to help lists and tree scrolling like the Explorer. Just checking ;>}

Yes, that setting is indeed enabled

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/99848

**Comment by joaomoreno** [comment]
Actually this is a separate issue.

**Comment by musm** [comment]
@joaomoreno yes this is separate.

Can you please also ensure consistency in the scroll sensitivity between all lists? Right now they are miscalibrated.
