### ISSUE TITLE
Notebook: Undo/Redo from menu do not work

### ISSUE THREAD

**Issue by Michael-N-N** [microsoft/vscode#99793]
In Python notebooks ‘Undo’ and ‘Redo’ do not work if they are selected from the ‘edit’ menu. Possibly the problem is caused by a lost focus on the notebook cells.

- VSCode Version: 1.46.0
- OS Version:Windows_NT x64 10.0.18363

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
Currently the notebook feature is provided by the python extension so please file issue against them.
