### ISSUE TITLE
Terminal links don't work with git bash paths

### ISSUE THREAD

**Issue by silkfire** [microsoft/vscode#99806]
- VSCode Version: 1.46
- OS Version: Windows 10 / v.2004 / 19041.329

Does this issue occur when all extensions are disabled?: Yes

I believe that the hyperlink feature in the integrated terminal could be slightly improved.

1. It currently doesn't execute IPv6 links correctly.  These links currently open Windows Explorer at the _This PC_ location. Expected is to open the default browser at `localhost:<port>`.

![image](https://user-images.githubusercontent.com/1554615/84325307-bdfc2680-ab7a-11ea-8221-04766056879b.png)

2. The working folder in bash is not parsed as a folder link. Instead it suggests to search in the workspace. Expected behaviour in this case is  to open Windows Explorer at the location of `D:\Projects\2017\2018\Wordsmith\word-flip-app`.

![image](https://user-images.githubusercontent.com/1554615/84325448-0d425700-ab7b-11ea-8f71-c1957124db67.png)

**Comment by Tyriar** [comment]
@silkfire does the first link also happen when you put it in a comment/string in the editor? If so can you create an issue for that as the terminal leverages the editor's link system now.

**Comment by silkfire** [comment]
@Tyriar The behaviour is the same if I type in the address as a comment in the editor, yes.

**Comment by Tyriar** [comment]
@silkfire please create an issue for that in the editor then, you can track that there. I'd create it but I know the details on ipv6 link formats. There's this related issue: https://github.com/microsoft/vscode/issues/62278

**Comment by silkfire** [comment]
@Tyriar Done, thanks. https://github.com/microsoft/vscode/issues/99993

**Comment by Tyriar** [comment]
For git bash specific paths I don't think we want to support these in core. An extension could handle this though by creating link providers to handle these specific cases.
