### ISSUE TITLE
Notebook completion list not showing/showing incorrectly with non-identifier characters.

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode#99801]
- VSCode Version: Insiders commit a5d1cc28bb5da32ec67e86cc50f84c67cc690321
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Install [.NET Interactive Notebook extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode).
2. Create an empty file with the extension `.dib`.
3. Open that file.
4. In the first notebook cell, type `#!` then invoke completion via `Ctrl+Space`.

Results:
The completion list doesn't show the existing `#!` characters as being a match which means committing the selection with `<Tab>` results in, e.g., `#!#!lsmagic`.  Removing the `!` and `#` characters from the word separator list seems to have no effect.

A potentially related issue is to set the cell contents to `#!w` then invoke completion via `Ctrl+Space`.  The editor reports no completion items available, but breaking in the extension code (instructions below) shows that 2 completion items are being returned.  Somewhere further along the editor is discarding the completion items.

Breakpoint instructions:
1. Clone: `git clone https://github.com/dotnet/interactive`
2. Go to notebook extension directory: `cd src/dotnet-interactive-vscode`
3. Install dependencies: `npm i`
4. Open extension in VS Code: `code-insiders .`
5. Add a breakpoint in `src/vscode/languageProvider.ts` on line 48:
   ``` typescript
   resolve(completionList); // <- breakpoint here
   ```
6. F5 and repeat the steps above.
7. In both cases (`#!` and `#!w`) the completion list contains items (4 and 2, respectively), but only in the first are those items then displayed in the editor.

Does this issue occur when all extensions are disabled?: Yes (with the exception of the notebook extension)

**Comment by jrieken** [comment]
A completion item provider is invoked, returns completions but they don't show up! 😕  What's the issue? Filtering! Filtering compares completions with a prefix and hides those that don't match.

#### Example

* trigger completions here: `say.he|` (`|` is the cursor)
* provider returns `abc`, `help`, `hood`
* the editor takes the `he`-prefix and scores it against `abc`, `help`, and `hood`. 
* scoring yields these result: 
  * `abc` - no match, don't show
  *  `help` - good match, show
  * `hood`  - no match, only `h` occurs, don't show
* editor shows `help` suggestion, does *not* show `abc` and `hood` suggestion

#### Extensions Rule!

The above sample was using "defaults" to determine the prefix and the filter criteria. 

 * `prefix:`  each completion can define its very own prefix via [`vscode.CompletionItem#range`](https://github.com/microsoft/vscode/blob/47b1183dfda519c32d78b591cfa721d3b0b874ae/src/vs/vscode.d.ts#L3803). Taking the example above, valid prefixes can be `say.he` or `.he` or ` ` (the empty string). Any range is valid as long as it includes the cursor position and is single line only.
* `filter:` each completion can define what string to use when filtering. The default is the label but via [`vscode.CompletionItem#filterText`](https://github.com/microsoft/vscode/blob/47b1183dfda519c32d78b591cfa721d3b0b874ae/src/vs/vscode.d.ts#L3776) any string can be defined

When to use what? It depends on the language, its word definition, and if you control/understand the word definition or not. The defaults usually work well enough but some languages might use a non-intuitive word definition, or completions span multiple words, or completions include non-word character etc. In all those cases the `range`-property should be used.
