### ISSUE TITLE
Environment variables sometimes do not apply on extension host attach

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#99800]
```
Version: 1.46.0-insider (user setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-09T17:34:47.110Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

@kieferrm reported this today -- that the [environment](https://github.com/microsoft/vscode-notebook-renderer-starter/blob/master/.vscode/launch.json#L16-L18) set in the notebook renderer starter doesn't get passed through to the extension host being debugged. After some number of times restarting vscode, it works.

I _think_ I've seen this once or twice before, but looking more into it now that may have only been the environment variable sticking around after I commented out from the launch config until vscode is restarted (which I can see see the cause of and get an easy reproduction). However I'm having trouble triggering Kai's case.

I verify that js-debug passes the variables though, and its logic is stateless between debug sessions so I do not think the problem lies in js-debug.

I tried to divine the root cause by just reading through our logic in vscode but didn't spot anything. Any ideas?

**Comment by isidorn** [comment]
I think @weinand was investigating a similar issue in the past, so first also assigning to him as he might know more.

**Comment by connor4312** [comment]
I thought I ran into this, but it turns out my OSS was running a very old js-debug version where environment variable setting was broken. Maybe Kai ran into the same thing? Aside from that I didn't run into this at all during the last ~week of building out webview debugging with probably several dozen launches on Windows and OSX.
