### ISSUE TITLE
Remove the selected number of characters from the status bar

### ISSUE THREAD

**Issue by jamesderlin** [microsoft/vscode#99807]
This is basically a duplicate of https://github.com/microsoft/vscode/issues/932 / https://github.com/microsoft/vscode/issues/15344 / https://github.com/microsoft/vscode/pull/17955 / https://github.com/microsoft/vscode/issues/21628 / https://github.com/microsoft/vscode/pull/87311, and maybe others that I missed.  All of those issues have been closed and locked, preventing any further discussion.

The stance seems to be that the number of selected lines will not be added to VS Code because that could be done by an extension.  That's fair, so I'd instead like to request that the number of selected characters be removed from the status bar.

1. Removing it would be consistent with not showing the selected number of lines.

2. I rarely care about the number of selected characters, and it's occupying valuable space on my status bar that instead could be used for, say, an extension showing the selected number of lines.

3. The current text shows "(N selected)".  Selected *what*?  What are the units?  Grapheme clusters?  Unicode code points?  UTF-16 code units?  UTF-8 code units/bytes?  Does it depend on the encoding of the open file?  This is so ambiguous and confusing that IMO it's better to just omit it.  Also see https://github.com/microsoft/vscode/issues/87626 where this was misinterpreted to mean the selected number of lines.

**Comment by yume-chan** [comment]
Interestingly in multiple cursor state, it actually tell you how many **characters** have been selected.

![image](https://user-images.githubusercontent.com/1330321/84489932-0596c580-acd5-11ea-8944-ab0f9c43fb2f.png)

---

I wonder if you can do the reverse, disable the built-in cursor position display, and replace it with some extension.

**Comment by jamesderlin** [comment]
@alexdima Since you championed using an extension for selected line counts in the referenced issues, perhaps you can champion this one too?
