### ISSUE TITLE
After install VS Code Extensions. The system reports that "The Window is no longer responding".

### ISSUE THREAD

**Issue by romanvieito** [Microsoft/vscode#9980]
- VSCode Version: 1.3.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Installing VS Code Extensions.
2. After restart it say HTML CSS Class Completion: Fetching CSS rules from CSS files, please wait.

No response to click or keyboard whatsoever, until after a while the system reports that "The Window is no longer responding".

**Comment by kieferrm** [comment]
@romanvieito what extensions did you install? Do you see the same hang when you start vscode with the following command line argument `--disable-extensions`?

**Comment by aeschli** [comment]
Please file this against the HTML Class Completion extension.
