### ISSUE TITLE
Current line indicator rectangle of the High Contrast theme is not closed.

### ISSUE THREAD

**Issue by HubKing** [microsoft/vscode#99805]
- VSCode Version: 1.46.0
- OS Version: Windows 10 (2004)

Steps to Reproduce:

1. Set the theme to High Contrast
2. Type something.

Does this issue occur when all extensions are disabled?: Yes

The brown rectangle outline is stretched too far to the right, so the right edge is lost. Not a critical issue, but not aesthetically pleasing. It would be nice to move the right edge a little bit to the left, so that one could see a beautiful closed rectangle.

![image](https://user-images.githubusercontent.com/10900489/84325161-223bdc00-abb5-11ea-8701-f119eb4c7cb8.png)

For a moment, I thought it could be intentionally designed so, but that does not seem to be the case, as the rectangle is closed on Linux.

![image](https://user-images.githubusercontent.com/10900489/84325924-d8ec8c00-abb6-11ea-822a-bc5461519c0e.png)

**Comment by alexdima** [comment]
The rectangle is "closed" to the right:

![image](https://user-images.githubusercontent.com/5047891/85295522-58743800-b4a0-11ea-98ea-f31d93e96fe7.png)

But if a line is longer than the viewport width (such that there is horizontal scrolling, then the "end" is scrolled all the way to the right):

![image](https://user-images.githubusercontent.com/5047891/85295609-76da3380-b4a0-11ea-8db2-ca550cc21bcb.png)
