### ISSUE TITLE
Cannot move "Source Control: Git" view back to Side Bar 

### ISSUE THREAD

**Issue by pepc** [microsoft/vscode#99810]
### Version of VS Code

Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z (13 hrs ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

### Your operating system

macOS 10.15.5

### List of extensions that you have installed

* C/C++ by Microsoft
* C# by Microsoft
* C Make Tools by Microsoft
* Debugger for Chrome by Microsoft
* Git Lens by Eric Amodio
* Go by Go Team at Google
* Live Share by Microsoft
* Native Debug by WebFreak
* Remote SSH by Microsoft
* Rust by The Rust Programming Language

### Reproducible steps (1... 2... 3...) that cause the issue

1. Move the **Source Control: Git** view from the Side Bar to the Panel.
2. Try to move the **Source Control: Git** view back to the Side Bar.

### What you expected to see, versus what you actually saw

I expected that the **Source Control: Git** view docks fine in the Side Bar.

The same thing happens with the **Remote Explorer** view.

However, the **Search** view moves fine back and forth between the Side Bar and the Panel.

**Comment by sbatten** [comment]
I thought this was prevented but it turns out the welcome view is being allowed to move. @pepc you can reset the view's location by right clicking > reset location. The SCM view is not yet moveable, but it should be next release. You will likely need to reload the window after resetting the view location.

**Comment by sbatten** [comment]
resolved in tomorrows build by source control being moveable

**Comment by sbatten** [comment]
To Verify:
1. Move the SCM Viewlet around and make sure you can do it twice without reloading
