### ISSUE TITLE
MACOS 10.15.5 Screen all black after app opens

### ISSUE THREAD

**Issue by yingyangxu** [microsoft/vscode#99817]
- VSCode Version: laster 
- OS Version: MacOS 10.15.5

Steps to Reproduce:

1. open vscode.app
![vs黑屏](https://user-images.githubusercontent.com/34048840/84337665-b6fe0400-abcc-11ea-8e91-6a6059e72a5c.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by deepak1556** [comment]
Can you try our insiders version https://code.visualstudio.com/insiders/
