### ISSUE TITLE
 Attribute 'program' is not absolute:

### ISSUE THREAD

**Issue by Ritwik880** [microsoft/vscode#99818]
This error occurs when we have a relative path in our debug configuration launch.json file (located in our workspace .vscode directory).

In the example below, the program attribute has a relative path to app.js at the root of the workspace (project folder).
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "./app.js"
    }
  ]
}

**Comment by isidorn** [comment]
Yeah, please use an absolute path, or the `${workspaceFolder}/app.js` since that will get substitued correctly.
More about substitution of varialbes you can find here https://code.visualstudio.com/docs/editor/variables-reference
