### ISSUE TITLE
Scroll position not retained when switching tabs from Release Notes

### ISSUE THREAD

**Issue by jay-ramani** [microsoft/vscode#99811]
Issue Type: <b>Bug</b>

As already mentioned in the title, the scroll position of Release Notes is not retained when switching to any tab (code or otherwise) and then back to the former. Easily reproducible.

Cheers,
Jay

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz (4 x 1512)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-monokai-seti|adi|0.0.5
alignment|ann|0.3.0
code-gnu-global|aus|0.2.2
theme-verdandi|be5|2.0.1
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
code-runner|for|0.10.0
terminal|for|0.0.10
Go|gol|0.14.4
helium-icon-theme|hel|1.0.0
output-colorizer|IBM|0.1.2
customize-ui|ioc|0.1.43
monkey-patch|ioc|0.1.7
better-cpp-syntax|jef|1.14.31
vsc-python-indent|Kev|1.10.1
MagicPython|mag|1.1.0
python|ms-|2020.5.86806
cpptools|ms-|0.28.3
deepdark-material|Nim|3.2.1
macos-dark-mode-theme|phi|1.0.1
material-icon-theme|PKi|4.1.0
platformio-ide|pla|1.10.0
try-material-icon-theme|raf|3.9.0
java|red|0.62.0
rust|rus|0.7.8
bunker|sld|1.1.6
java-generate-setters-getters|soh|5.3.0
python|tht|0.2.3
cmake|twx|0.0.17

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
This is a longstanding issue. See #27498, and my PR #85982
