### ISSUE TITLE
poor drag&drop performace

### ISSUE THREAD

**Issue by hualiansheng** [microsoft/vscode#99816]
- VSCode Version: 1.45.1 & 1.46.0
- OS Version: Windows 10 1909

Steps to Reproduce:

1. drag file from side menu into workbench
2. if do drag&drop very fast, file will not be opened
3. if hold your mouse for quite a while(multiple seconds) in workbench area, file will finally be opened

Does this issue occur when all extensions are disabled?: Yes

I suspect it's a network issue(maybe trying sending telemetry data), but no luck after disable all telemetry settings. Also, no repro in another pc in the same network env.

Is it caused by some hidden settings? or maybe a strange bug? thx

![repro](https://user-images.githubusercontent.com/3750578/84338217-1577b200-abce-11ea-9b69-9a505f0b8189.gif)

**Comment by isidorn** [comment]
Can not reproduce. Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
