### ISSUE TITLE
Explore minimizing shipped TS Server 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#99822]
## Problem
The `typescript` package with include to power VS Code's JS/TS support is around 30MB on disk. This is after we already strip out some unnecessary files, such as `tsc.js`.

## Proposal
See if we can run the bundled TypeScript version through terser or some other minimizer. This would help reduce the VS Code download and install size.

The main concern I have with this is error stacks that users share with us. Error stacks from minified TypeScript processes would be impossible to decipher without source maps (which we would likely not want to include in the bundled typescript package due to their size)

See https://github.com/microsoft/TypeScript/issues/4844

**Comment by mjbvz** [comment]
Running basic `terser` on the three javascript files we consume from the TypeScript project—`tsserver`, `typescript`, and `typingsInstaller`—the results a quite promising:

- `tsserver.js`: 8.9MB ->  2.7MB
- Entire TS package: 31.7MB -> 15.3MB

**Comment by mjbvz** [comment]
@amcasey The `typescript` package currently seems to be over 10% of VS Code's on disk install size (31MB out of 250MB on MacOS) so I'm pretty interested to see what we can do here.


As I mentioned, my main question is how we would handle error stacks from users. Is this something that you have thought about? Is minifying the shipped TypeScript code something the TS team had considered?

**Comment by mjbvz** [comment]
Also @amcasey, can we safely remove the `typescript/loc` directory for VS Code? My understanding is that all the localized strings actually come from files such as `typescript/lib/de/diagnosticMessages.generated.json`

**Comment by David-Else** [comment]
I recommend closure-compiler in simple mode https://developers.google.com/closure/compiler/docs/compilation_levels for minification. In my tests, it gives the best results.

**Comment by amcasey** [comment]
@mjbvz I think it was discussed, but it was before my time.  I'm happy to run some experiments and get the conversation going again if it makes a big differences.

Side note 1: I wanted to minify .d.ts files, but that was shot down since their purpose is to be readable.
Side note 2: @weswigham's work to convert TS to modules should make it easier to strip out unnecessary code.

**Comment by amcasey** [comment]
I'm not familiar with our loc story, but I think @sandersn touched it recently and might know what's strictly necessary.

**Comment by amcasey** [comment]
Regarding source maps, I'm not too concerned - .NET can debug assemblies shipped without PDBs because it maintains a store of them indexed by assembly hash.  I assume the same would work for minified JS.

**Comment by sandersn** [comment]
I may have the most knowledge about loc on the team, but I don't actually know that much. =) But I looked at `/loc` and it's full of VS-UI-specific items. I'm pretty sure it's for VS localisation only and you're safe to drop it. @minestarks could probably say for sure.

**Comment by amcasey** [comment]
Looks like `terser -c` causes a ~1% regression in total compilation time, but the output is nearly as small without `-c` and that seems not to have a perf impact.

**Comment by amcasey** [comment]
So I don't lose it, here's the command I used to end up with a composite source map, letting me step through the original .ts files:
```
npx --no-install terser tsc.js -o tsc2.js --source-map "content=tsc.js.map,url='tsc2.js.map'"
```
The `content` tells it where to find the input source map and the `url` tells it what to put in the source map comment at the bottom of the minified file.  Note the lack of `-c`, since that seemed to hurt runtime perf.

**Comment by mjbvz** [comment]
@amcasey Do you need to do any work for the TS telemetry tools before I merge this?

**Comment by amcasey** [comment]
@mjbvz If VS Code isn't going to (un)map the positions in stack traces before sending them, then yes. cc @armanio123

**Comment by mjbvz** [comment]
Yes I'd prefer not shipping the source map and tools for processing them as that brings up the install size again

Here's branch I have that runs terser: https://github.com/mjbvz/vscode/commit/4b885ad45f1ddcb3e63a99cf320f09a1f38f0735

**Comment by armanio123** [comment]
On the tools side, we could do the same minification but with source maps and map to the stack. I don't know much details about terser but a quick search on the documentation seems like we're able to do that.

**Comment by amcasey** [comment]
@armanio123 Is that easier than just applying the source map and then working with the same JS file as the other stacks?

**Comment by armanio123** [comment]
@amcasey, I'm not sure I understand your question. I'm assuming if minimization gets merged we're going to start getting stacks with positions on the minimized file. So the idea is to download the same tsserver version, get the source map, and start extracting the positions. Does it makes sense?

**Comment by mjbvz** [comment]
This has improved a lot by deduplicating the code that TS ships. We don't minify yet, but this makes stack tracks more useful out of the box. We do minify on web where file sizes are especially important

Closing as further work is out of scope for now
