### ISSUE TITLE
Debug Log filtering not working correctly

### ISSUE THREAD

**Issue by szmcdull** [microsoft/vscode#99821]
1) click on debug log pane
2) Press SHIFT+TAB
3) Key in something
4) Click Enable Filter On Type
5) The filtered result is not correct, desired content not showing up, or other content show up instead.

**Comment by isidorn** [comment]
I have no clue what log pane you are referring to.
What are you trying to filter. More precise but concise steps please!

**Comment by szmcdull** [comment]
The Debug Console
![image](https://user-images.githubusercontent.com/2098590/84731665-2197b100-afcc-11ea-8743-82ab17f71f3c.png)

**Comment by isidorn** [comment]
In that screen shot you are not filtering. Please click on the icon next to `aaa` to filter
We have other issues that mention this, so closing this one

**Comment by szmcdull** [comment]
1) click on debug log pane
2) Press SHIFT+TAB
3) Key in something
4) Click Enable Filter On Type
5) The filtered result is not correct, desired content not showing up, or other content show up instead.
