### ISSUE TITLE
Regression: Codicons in hovers are broken

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#99825]
This was introduced by https://github.com/microsoft/vscode/commit/464f3de63c439ecbeffde58b0a36326f995528f5

https://github.com/microsoft/vscode/blob/464f3de63c439ecbeffde58b0a36326f995528f5/src/vs/base/browser/markdownRenderer.ts#L213-L221

Codicons get translated into `span`s with a couple of classes, so this filtering needs to change to either allow `class` on `span` which opens a styling door I don't think we want, or we need to do this filtering before we translate the codicons into spans.

This is also broken in stable 1.46 -- so I've marked this as a recovery candidate.

Also related: the `color`, `background-color` regex is too strict to allow full css colors, e.g. `rbg(255, 0, 0)`

**Comment by alexr00** [comment]
@mjbvz and @jrieken is it ok to all allow through `class` on spans?

**Comment by alexr00** [comment]
Actually, we were letting class on spans through already with this
https://github.com/microsoft/vscode/blob/464f3de63c439ecbeffde58b0a36326f995528f5/src/vs/base/browser/markdownRenderer.ts#L233
Fix is to let class through.

**Comment by alexr00** [comment]
Per discussion, we allow through class, but only with the codicon class.

**Comment by alexr00** [comment]
The fix in action (I added a $(plus) into the hover before the label):
![image](https://user-images.githubusercontent.com/38270282/84390055-50daa680-abf7-11ea-8176-8a6037c4819b.png)
