### ISSUE TITLE
Unable to move search panel to bottom

### ISSUE THREAD

**Issue by amithegde** [microsoft/vscode#99824]
Issue Type: <b>Bug</b>

Just updated VS Code to latest. I had the search panel to show up at the bottom for very long time, now it's back to left. Unable to find a setting to change it back to bottom.

Setting `"workbench.panel.defaultLocation": "bottom"` on settings.json did not work.

Please simplify this.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (44.12GB free)|
|Process Argv|c:\One\Storage\XStore|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.901.9
code-gnu-global|aus|0.2.2
bracket-pair-colorizer-2|Coe|0.1.4
vscode-markdownlint|Dav|0.36.0
xml|Dot|2.5.0
gitlens|eam|10.2.2
json-tools|eri|1.0.2
todo-tree|Gru|0.0.176
rest-client|hum|0.23.2
csharpfixformat|Leo|0.0.84
vscode-clang|mit|0.2.3
vscode-azureappservice|ms-|0.17.0
csharp|ms-|1.22.0
azure-account|ms-|0.8.11
cpptools|ms-|0.28.3
powershell|ms-|2020.4.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2302
debugger-for-chrome|msj|4.12.8
debugger-for-edge|msj|1.0.15
vscode-sanddance|msr|1.2.12
gremlins|nho|0.20.0
indent-rainbow|ode|7.4.0
LiveServer|rit|5.6.1
trailing-spaces|sha|0.3.1
vscode-scss-formatter|sib|2.0.1
autoimport|ste|1.5.3
code-spell-checker|str|1.9.0
vscodeintellicode|Vis|1.2.8
vscode-icons|vsc|10.1.1
vscode-bond|yiw|0.0.10
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by ArturoDent** [comment]
Just drag the Search icon to the bottom panel.

**Comment by nolaneo** [comment]
Not sure if it's a coincidence, but the search panel also moved back to the left hand side for me after updating yesterday.

I couldn't figure out how to move it back (same confusion with `defaultLocation` having no effect), but thanks @ArturoDent for the tip to drag the icon. I'd never have figured that out! 😄

**Comment by novavsc** [comment]
Not able to drag search to bottom panel. It works in Windows but not in Linux rhel 7.x
