### ISSUE TITLE
Add sequence & workflow diagram support to Markdown

### ISSUE THREAD

**Issue by cilerler** [Microsoft/vscode#9982]
Supporting syntax through [jsSequence](https://bramp.github.io/js-sequence-diagrams/) and [jsFlow](http://flowchart.js.org/) would be great.

> related #2273

``````
```sequence
Andrew->China: Says Hello
Note right of China: China thinks\nabout it
China-->Andrew: How are you?
Andrew->>China: I am good thanks!
``
``````

<img width="399" alt="sequence" src="https://cloud.githubusercontent.com/assets/385958/17273056/fb130aa6-5675-11e6-90fe-b841596e3cb2.png">

``````
```flow
st=>start: Start:>http://www.google.com[blank]
e=>end:>http://www.google.com
op1=>operation: My Operation
sub1=>subroutine: My Subroutine
cond=>condition: Yes
or No?:>http://www.google.com
io=>inputoutput: catch something...

st->op1->cond
cond(yes)->io->e
cond(no)->sub1(right)->op1
``
``````

<img width="298" alt="flow" src="https://cloud.githubusercontent.com/assets/385958/17273009/aab136b0-5674-11e6-9014-cd4d56303cc1.png">

**Comment by chemaoxian** [comment]
yes , it's just what i want

**Comment by kaipaysen** [comment]
I'd love that feature!

**Comment by mjbvz** [comment]
Please take a look at our experimental markdown extension exploration in VSCode 1.11: https://github.com/Microsoft/vscode/issues/22916

For example, here's an experimental extension that adds mermaid diagram support to markdown files using this API: https://github.com/mjbvz/vscode-markdown-mermaid

If someone is interested in prototyping an extension for jsflow or jssequence, I'd be happy to help out and hear any feedback you have on the API. The [mermaid extension](https://github.com/mjbvz/vscode-markdown-mermaid) is probably a good staring point

**Comment by seanpk** [comment]
I am quite interested in having any diagram support in my markdown (I'm not particular about the syntax or underlying technology).
At a basic level, I'd like to be able to replicate what stackedit.io can do for sequence diagrams and flow charts.

@mjbvz - is markdown-mermaid still based on experimental features as indicated in its readme?
What are the next steps for getting a stable extension in place?

Also, related but not necessarily connected to the extension, I wonder what the best practices for doing builds of such documents would look like.

**Comment by mjbvz** [comment]
@seanpk The markdown extensions API is now enabled by default in the current VS Code insiders builds. I've update the [VSCode markdown mermaid extensions](https://github.com/mjbvz/vscode-markdown-mermaid) to support this. I plan on releasing the extension on the VS Code marketplace after 1.15 ships

Closing this issue since extensions should now be able to contribute this functionality

**Comment by seanpk** [comment]
thanks @mjbvz, that sounds great
