### ISSUE TITLE
Close mark X of tab is not displayed

### ISSUE THREAD

**Issue by ayatokura** [microsoft/vscode#99820]
Steps to Reproduce:
1. Open new file
2. Close mark X of tab is not displayed

Screenshot:
<img src="https://tofguw.by.files.1drv.com/y4mdFl-KxfZt9VLmJpHIUsON8NZ4gw5FDvCbKiWxO9RQr_m1dKuWxJAlXeCO_RPEcfU_HahJdnAZuDo1XDe6OKnkn3t2p5MYTfC_tJLrLgnXpRe4paEZIAZa1RqbE72jGFCKvvftHE_WFjjQIjCcEgvRS-fD4uyk-ADIH9UzWGglOwUn8nnbjjCNdqi8nFF1fI-baa2O7u3iAly_Pf5qjD4Ag?width=808&height=541&cropmode=none" width="600">

**Comment by ArturoDent** [comment]
What is this setting set to:

    workbench > Editor: Tab Close Button

default is `right`, could yours have been reset to `off` by any chance?

**Comment by ayatokura** [comment]
The problem was resolved by reconfiguring.  Thank you for your advice.
