### ISSUE TITLE
Test Explorer

### ISSUE THREAD

**Issue by Kradirhamik** [microsoft/vscode#99838]
VS Code should have an official extension for a test explorer, that supports Jest, Jest-Cucumber and automation tests of PlayWright out of the box.

**Comment by gjsjohnmurray** [comment]
I disagree. Doing that would add bloat for people who don't need it.

**Comment by axetroy** [comment]
I agree. But not for a specific testing framework

It is abstracted into a general purpose, similar to view

Such different extensions can create test legends

```ts
interface TestCase {
  label: string
  location: {
    file: Uri
    start: number
    end: number
  }
}

export async function activate(
  context: vscode.ExtensionContext
): Promise<void> {
	vscode.test.add({
      label: 'testxxx',
      location: {xxxxx}
    })

    vscode.test.registry(function (test: TestCase) {
	  // defined how to run this test case
    })
}
```

**Comment by Kradirhamik** [comment]
> I disagree. Doing that would add bloat for people who don't need it.

The idea is not to have it in VS Code by default, but rather just having such extension exist for people who need it - so there would be not bloating

**Comment by Kradirhamik** [comment]
> I agree. But not for a specific testing framework
> 
> It is abstracted into a general purpose, similar to view
> 
> Such different test framework extensions can create test legends
> 
> ```ts
> interface TestCase {
>   label: string
>   location: {
>     file: Uri
>     start: number
>     end: number
>   }
> }
> 
> export async function activate(
>   context: vscode.ExtensionContext
> ): Promise<void> {
> 	vscode.test.add({
>       label: 'testxxx',
>       location: {xxxxx}
>     })
> 
>     // defined how to run this test case
>     vscode.test.registry(function (test: TestCase) {
> 	  
>     })
> 
>     // defined how to run all test case
>     vscode.test.registryRunAll(function (test: TestCase) {
> 	  // defined how to run this test case
>     })
> }
> ```
> 
> Then add a test case in the sidebar
> 
> Each test case added by the extension has a different tree view in sidebar

Yes, I just meant to give an example. It should support popular test automation frameworks out of the box ideally.

**Comment by gjsjohnmurray** [comment]
> The idea is not to have it in VS Code by default, but rather just having such extension exist for people who need it - so there would be not bloating

Then I'm not clear why you asked for an _official_ one. 

This one seems popular and well rated.

https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer

But it seems you already tried it and had a problem - https://github.com/hbenl/vscode-test-explorer/issues/108

Maybe try this Test Adapter extension, which seems to be actively developed, and allows issues to be raised:

https://marketplace.visualstudio.com/items?itemName=kavod-io.vscode-jest-test-adapter&ssr=false
