### ISSUE TITLE
editor.codeActionsOnSave has no documentation and is broken

### ISSUE THREAD

**Issue by breathe** [microsoft/vscode#99833]
The functionality associated with this configuration used to work prior to the deprecation of the other setting (editor.formatOnSave or some such).  

This editor.codeActionsOnSave setting doesn't work properly for me and I can't find any information about it on the internet aside from comments that indicate the setting is related to eslint auto-fixes - and I am not using eslint in my project.

Pretty much everything I can find seems to suggest that this setting is aimed at organizing the pipline of actions that happen on save in order to provide an optimized eslint experience ... - well what happened to basically 'all action's on save' for non-js/ts languages?

Would it be possible to link to _one_ actual example of this configuration being used in a way that doesn't break all non-js/ts languages which have an autoformat extension ... -- and which doesn't popup useless messages with never completing spinners that prompt about 'getting code actions' associated with random extensions.

![image](https://user-images.githubusercontent.com/434034/84354850-d2422280-ab7e-11ea-8561-11640edb1d1d.png)

**Comment by gjsjohnmurray** [comment]
Related to #96509 

cc @jrieken

**Comment by mjbvz** [comment]
Can you please provide steps to reproduce the problem?

**Comment by breathe** [comment]
@mjbvz I'm having trouble _not_ reproducing the problem -- however I think I may have found a trigger ...

I think the errors start happening or start happening more frequently (randomly) if I have large json files open -- and the errors occur even when saving files other than the large json tabs if I have at some point prior opened a large json file ...  I've been inspecting unusually large (100MB) json files recently -- and several smaller large json files (2-5MB) -- and I believe these inspection tasks are associated with the issue ...

**Comment by mjbvz** [comment]
Can you please provide a list of steps to reproduce the problem

**Comment by breathe** [comment]
1. Open a large json file
2. Try to save it

**Comment by mjbvz** [comment]
Does happen with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? If not, then this is caused by one of your extensions

**Comment by breathe** [comment]
Is there anyone who can actually provide guidance for me to be able to provide information to diagnose this issue?? 

@mjbvz @alexr00 @gjsjohnmurray @jrieken ...

I've been asked for 'repro' steps and provided them.

I've been asked to turn off extensions -- -- so if all the extensions are off what exactly is the effect of that on the 'codeActions' setting?  If i turn off all the extensions and hit 'save' -- what do we expect to have happen here -- and how exactly does that help me address the original issue?

I have no idea how this 'codeAction' setting is supposed to work because there is no meaningful information about it anywhere on the internet.  

I don't know even know if its actually related to the issue and even if its ultimately related to the issue -- my assumption that its related to the codeAction setting is based on the name -- but I have literally nothing to go on -- especially since this popup randomly refers to different extensions ?

**Comment by mjbvz** [comment]
If this only happens when a specific extension is enabled, then it is caused by that extension. Please file an issue against that extension
