### ISSUE TITLE
Pinned tab doesn't show unsaved changes

### ISSUE THREAD

**Issue by SzaboViktor11** [microsoft/vscode#99839]
VS Code version: 1.46.0

Repro:
- pin a tab in VS Code editor
- make any changes inside the pinned tab

Expected behaviour: The pinned tab header should show a dot or something to indicate that there are unsaved changes in it.

Current behaviour: There is no any indicator that shows that the pinned tab has unsaved changes.

![image](https://user-images.githubusercontent.com/6562284/84361011-50c4b180-abcb-11ea-9e59-bd152d8550b3.png)

**Comment by gjsjohnmurray** [comment]
I think this was a design decision. To mitigate it you can set `"workbench.editor.highlightModifiedTabs": true`
