### ISSUE TITLE
TypeScript Region and Format Code

### ISSUE THREAD

**Issue by audinue** [Microsoft/vscode#9983]
- VSCode Version: 1.3.1
- OS Version: Windows 7

Steps to Reproduce: (Please be patient)

![animation](https://cloud.githubusercontent.com/assets/1407800/17273633/88ce347c-56e6-11e6-98cb-0d093b38984f.gif)

**Comment by wallverb** [comment]
Hmm, I'm not sure there is a region support in vscode, I think you are just using the fact that folding happens based on indentation (you can type anything after `//` in your example). In this situation format code works fine. Here is the task regarding folding that might interest you: https://github.com/Microsoft/vscode/issues/3422

**Comment by audinue** [comment]
Thank you very much for the information. :smile:

Closing this issue.
