### ISSUE TITLE
Copying line

### ISSUE THREAD

**Issue by mepsd** [microsoft/vscode#99837]
Issue Type: <b>Bug</b>

when we by mistakely press Ctrl+C instead Ctrl+V than it copies tht current blank line that does not make any sense. i think it should have to fix.
many of the developers i think find this issue

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

**Comment by usernamehw** [comment]
There was a feature like that but it was repeatedly reported as a bug #69903

An extension that implements this: https://marketplace.visualstudio.com/items?itemName=usernamehw.do-not-copy-empty

**Comment by alexdima** [comment]
@mepsd `"editor.emptySelectionClipboard": false`
