### ISSUE TITLE
Don't work hotkey

### ISSUE THREAD

**Issue by OdinVerst** [microsoft/vscode#99831]
Issue Type: <b>Bug</b>

cmd + shift + n - does not work 

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
youtrack|bul|0.0.30
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
es7-react-js-snippets|dsz|2.8.0
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.0.0
svelte-vscode|Jam|0.9.3
sftp|lix|1.12.9
LiveServer|rit|5.6.1
stylelint|thi|0.51.0

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Does this also happen after you use the Command palette command to reload with extensions disabled?

What does your Keyboard Shortcuts list show when you search for this key combination?

Is this something that used to work OK for you before 1.46.0?

**Comment by OdinVerst** [comment]
Yes, it worked before 1.46.0. HotKey does not work when there are no active window, if there is one - everything works.

Sorry for my English. 
I made a video, I hope it's more understandable.
https://youtu.be/jASZe_pvUC4

**Comment by gjsjohnmurray** [comment]
/duplicate

@OdinVerst thanks for your report. Merging with #99998 (logged later) because that has a better title and clarifies that the problem doesn't only affect keyboard shortcuts.
