### ISSUE TITLE
No longer can see variables for my script

### ISSUE THREAD

**Issue by daramir** [microsoft/vscode#99844]
Issue Type: <b>Bug</b>

Use Node.js Debug Terminal to "instantly debug Javascript you run from the command line"

create a node.js script such as:
```javascript
#!/usr/bin/env node
'use strict';

const path = require('path');
const execa = require('execa');
const { Command } = require('commander');


// Get CLI inputs
const program = new Command();


program
	// .option('--debug', 'output extra debugging')
	.option('-d, --dry-run [boolean]', 'The read part of Read/Write', "true")
	.option('-t, --target-path <path>', 'analyse this directory instead of cwd');

program.parse(process.argv);

let analysePath = '.';

//Set directory if applicable
if (program['targetPath']) {
	analysePath = program['targetPath'];
}
//Properly get bool value for dry run
program.dryRun = program.dryRun == "false" ? false : true;
```
call it.... `testfile.js`
when you run this from the VS Debug command line with e.g. `node testfile.js -d -t "/mnt/asdf/asdf"`, you wont be able to inspect variables such as `program`, nor see them in the variables pane. This was possible not too long ago. Now it only seems to work if I wrap all of my script logic in a function.

![image](https://user-images.githubusercontent.com/4935829/84365942-85f5f180-ac15-11ea-9492-2f44ae99eb44.png)

VS Code version: Code - Insiders 1.47.0-insider (6efc0b6950cef0dbed0a59c23c656a3f2cfb6403, 2020-06-11T05:45:05.735Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.99GB free)|
|Process Argv|-psn_0_2642565|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
gitlens|eam|10.2.2
prettier-vscode|esb|5.0.0
gitlab-workflow|fat|2.2.0
Go|gol|0.14.4
terraform|has|2.0.1
beautify|Hoo|1.5.0
powershell|ms-|2020.4.0
color-highlight|nau|2.3.0
annotator|ryu|1.0.0
vscode-icons|vsc|10.1.1

</details>

**Comment by connor4312** [comment]
@daramir can you please add this to your user settings, and try again?

```
  "debug.javascript.terminalOptions": {
    "trace": true,
  },
```

This will cause a log file to be generated (the location will be printed in the Debug Console) which you can share with us. Thanks!

/needsMoreInfo

**Comment by daramir** [comment]
Hi @connor4312 , 

Sorry for the delay. Sure, can do. I tried just now and issue persists. Same system info but on a newer version:

> Version: 1.47.0-insider
> Commit: 9bf6af04dcb5c2e531cedca83cd188939ca1b0db
> Date: 2020-06-26T21:11:02.609Z (2 days ago)
> Electron: 8.3.3
> Chrome: 80.0.3987.165
> Node.js: 12.13.0
> V8: 8.0.426.27-electron.0
> OS: Darwin x64 18.7.0

Uploading verbose log as requested
[vscode-debugadapter-1.zip](https://github.com/microsoft/vscode/files/4843831/vscode-debugadapter-1.zip)

**Comment by connor4312** [comment]
This doesn't not appear to be an issue with vscode. I see that Node.js says that it fails to parse `dependency-management.js`

```js
{
  "method": "Debugger.scriptFailedToParse",
  "params": {
    "scriptId": "120",
    "url": "file:///Users/ramirezd/TheoryDotRun/main/anzinsto/insto-housekeeping/dependency-management/npm/jira-dep-mgmt-cli/src/dependency-management.js",
```

Node.js can actually step into it, but it reports no scopes in its `scopeChain`, thus we reflect that in vscode

```
{
  "method": "Debugger.paused",
  "params": {
    "callFrames": [
      {
        "callFrameId": "{\"ordinal\":0,\"injectedScriptId\":1}",
        "functionName": "",
        "functionLocation": {
          "scriptId": "120",
          "lineNumber": 0,
          "columnNumber": 0
        },
        "location": {
          "scriptId": "120",
          "lineNumber": 55,
          "columnNumber": 9
        },
        "url": "file:///Users/ramirezd/TheoryDotRun/main/anzinsto/insto-housekeeping/dependency-management/npm/jira-dep-mgmt-cli/src/dependency-management.js",
        "scopeChain": [],
        "this": {
          "type": "object",
          "className": "Object",
          "description": "Object",
          "objectId": "{\"injectedScriptId\":1,\"id\":209}"
        }
      },
```
