### ISSUE TITLE
terminal launching error

### ISSUE THREAD

**Issue by NihitRanjan** [microsoft/vscode#99843]
Issue Type: <b>Bug</b>

'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe' failed to launch (exit code: -3)   
this error appears everytime i try to run my code.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
shell|bbe|0.3.0
prettier-vscode|esb|5.0.0
python|ms-|2020.5.86806

</details>

**Comment by Tyriar** [comment]
Do you have anti-virus software that could be blocking the terminal? If so try following the instructions in https://code.visualstudio.com/docs/editor/integrated-terminal#_how-do-i-fix-the-errors-connectnamedpipe-failed-windows-error-232-or-terminal-exited-with-code-x-on-windows

/label "needs more info" integrated-terminal

**Comment by NihitRanjan** [comment]
Resetting the following setting solved the problem: Terminal › External: Windows Exec
