### ISSUE TITLE
Improve explorer elements alignment

### ISSUE THREAD

**Issue by inwardmovement** [microsoft/vscode#99846]
Align explorer tree child elements with their parent folder's name. For now it's not clear which elements are in which folder. The `workbench.tree.indent` does not act on this.

![image](https://user-images.githubusercontent.com/9438102/84371022-57f2bc00-abd9-11ea-8aac-6df6b188f168.png)

Maybe also tweak folder icons alignment:
![image](https://user-images.githubusercontent.com/9438102/84372455-69d55e80-abdb-11ea-9dfb-6da54fcc75dd.png)

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by gjsjohnmurray** [comment]
@inwardmovement  your screenshots show no file icons. Have you intentionally used the `Preferences: File Icon Theme` command to do this?

**Comment by inwardmovement** [comment]
@gjsjohnmurray I use `"workbench.iconTheme": null` as an everyday setting, I prefer without file icons for now.
