### ISSUE TITLE
Performance issue when try to rename file

### ISSUE THREAD

**Issue by tuoitrexuquang** [microsoft/vscode#99849]
Issue Type: <b>Bug</b>

When i am trying rename a file, it's take long time for check & update reference files using.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|-psn_0_303178|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.2.0
vscode-ipaddress|Com|1.0.0
vscode-markdownlint|Dav|0.36.0
githistory|don|0.6.5
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-author-generator|edw|0.0.10
prettier-vscode|esb|5.0.0
Angular2|joh|9.1.2
git-graph|mhu|1.23.0
code-beautifier|mic|2.3.3
Angular-BeastCode|Mik|8.1.2
prettify-json|moh|0.0.3
azure-pipelines|ms-|1.170.0
vscode-azureappservice|ms-|0.17.0
vscode-azurefunctions|ms-|0.22.1
vscode-azureresourcegroups|ms-|0.1.0
vscode-azurestorage|ms-|0.9.0
vscode-azurevirtualmachines|ms-|0.1.0
vscode-cosmosdb|ms-|0.13.0
vscode-docker|ms-|1.2.1
csharp|ms-|1.22.0
vscode-dotnet-runtime|ms-|0.1.2
mssql|ms-|1.9.0
azure-account|ms-|0.8.11
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|0.0.11
vscode-typescript-tslint-plugin|ms-|1.2.3
azurerm-vscode-tools|msa|0.10.0
debugger-for-chrome|msj|4.12.8
java|red|0.62.0
open-in-browser|tec|2.0.0
pdf|tom|0.6.0
vscodeintellicode|Vis|1.2.8
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.21.4
vscode-icons|vsc|10.1.1

</details>

**Comment by isidorn** [comment]
Can not reproduce. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by tuoitrexuquang** [comment]
@isidorn with Visual Studio Code Insiders, it's work normally.

**Comment by tuoitrexuquang** [comment]
hi @isidorn  i am not sure the root cause because it's conflicting with some plugins i am using in my local. i asked my friends, it's work normally:(.

**Comment by isidorn** [comment]
Then it is caused by some of your extensions, figure out which one and file an issue against it.
