### ISSUE TITLE
"workbench.list.smoothScrolling": true does not affect the extensions list

### ISSUE THREAD

**Issue by Longhanks** [microsoft/vscode#99848]
- VSCode Version: 1.46.0
- OS Version: Windows 10 Version 2004
- Hardware: Discrete mouse wheel

Steps to Reproduce:

1. Set `workbench.list.smoothScrolling` to `true`
2. Observe that the extensions list does not scroll smoothly. It jumps a few lines, just like the file tree used to before 1.46 and the new `workbench.list.smoothScrolling` setting.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
If you enable `editor.smoothScrolling`, does it work for the editor?

**Comment by Longhanks** [comment]
Yes, if `editor.smoothScrolling` is set to `true`, the editor scrolls smoothly. Having neither `editor.smoothScrolling` nor `workbench.list.smoothScrolling` set to `true`, any one of them, or both of them, does however not affect the extension list, only the editor or respectively the file tree.

**Comment by joaomoreno** [comment]
Ah just the extensions list. Got it! Let's merge it into https://github.com/microsoft/vscode/issues/99798
