### ISSUE TITLE
'Edit in settings.json' does not add default for object-type setting

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#99854]
Issue Type: <b>Bug</b>

My extension's `settings.json` contributes a configuration property that is object-type, i.e. something like this:

```
	"contributes": {
		"configuration": {
			"title": "FooBar Servers",
			"properties": {
				"foobar.server": {
					"type": "object",
					"description": "Connection to server",
					"scope": "resource",
					"default": {
							"host": "127.0.0.1",
							"port": 80
						}
					},
...
```

The UI-mode settings editor offers me an 'Edit in settings.json' option which adds an entry for `foobar.server` but doesn't populate the object with its default property values. In contrast, if I manually add `foobar.server` in JSON-mode settings editor using completion, the defaults are inserted.

VS Code version: Code - Insiders 1.47.0-insider (6efc0b6950cef0dbed0a59c23c656a3f2cfb6403, 2020-06-11T05:46:14.594Z)
OS version: Windows_NT x64 10.0.18363

**Comment by jrieken** [comment]
It does insert a default value but it also triggers suggest in an unexpected location. @sandy081 what's up with that?

<img width="833" alt="Screenshot 2020-07-02 at 11 14 07" src="https://user-images.githubusercontent.com/1794099/86340477-3ffcde00-bc55-11ea-944d-03cc94f4162c.png">

**Comment by sandy081** [comment]
Yeah not good given that there are no suggestions which is hard to know. I think better is to avoid prompting suggest for array  or object types.
