### ISSUE TITLE
Allow language server hovers to be displayed while in a debug session

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#99856]
When debugging, hovering over a class name sends the request to the debugger for evaluation, and *not* to the language server. This is a bit awkward if you want to read the documentation for a type that's in the code you're debugging.

This was briefly discussed at https://github.com/microsoft/vscode/pull/48747#issuecomment-392735931 but I was asked about it again and it looks like there's no open issue tracking it.

This seems like really useful functionality - even if Code can't render multiple tooltips, being able to hold down a modifier or something to get the language tooltip while debugging would be nice.

**Comment by isidorn** [comment]
For now forwarding to @weinand as he looked into debug adapter language server integration and might have more details

**Comment by Trass3r** [comment]
True, VS has the same limitation.

**Comment by weinand** [comment]
@isidorn I like the idea of using a modifier key to switch between debug hover and language hover.
This approach does not need any additional integration between debug and language services.

**Comment by Trass3r** [comment]
Special case of #102939?

**Comment by isidorn** [comment]
I also like that idea. Let me assign to September so I can investigate more then.

**Comment by isidorn** [comment]
Let's close as dup of https://github.com/microsoft/vscode/issues/84561
Thanks @Trass3r for pointing out
