### ISSUE TITLE
Consider debugger control placement

### ISSUE THREAD

**Issue by keldju** [microsoft/vscode#99852]
It would be interesting to make the position of the debugger control more flexible for small monitors ...
Sometimes the control is over the tab name or the breacumbs or the sidebar or the typed code, what prevents reading.

( _maybe add the possibility to put it in the status bar_ )

Tks!

**Comment by isidorn** [comment]
Status bar -> there is an extension you can use
You can use this setting to put it in the sidebar 	"debug.toolBarLocation": "docked",
To put it anywhere search for duplicates, there are already issues requesting this. Thanks
