### ISSUE TITLE
screenshots in workbench part from the 1.46 release note are too small

### ISSUE THREAD

**Issue by copdips** [microsoft/vscode#99859]
Hello,

Just to report that in the latest 1.46 release note, the screenshots in [workbench](https://code.visualstudio.com/updates/v1_46#_workbench) part are too small, which make people difficult to see the 1.46 features from a small screen.

**Comment by gjsjohnmurray** [comment]
Can you use your browser's context menu to view the image in a separate window/tab, then zoom it? The first image's dimensions are 1823px × 1270px

**Comment by copdips** [comment]
Yes, I know how to zoom in the images, but it needs extra actions.
All the other images are large enough and very clear except for workbench part.

**Comment by sbatten** [comment]
updated
