### ISSUE TITLE
VSCode is freezing after last update

### ISSUE THREAD

**Issue by rohanrhu** [microsoft/vscode#99855]
Version: 1.46.0 (system setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

This problem was exists on two previous version but previous version was ok. Now, with last update, it is back. Especially it is freezing on switching over files or views.

**Comment by rohanrhu** [comment]
I thought this maybe due to the extension: https://github.com/CoenraadS/BracketPair Maybe a incompatibility between last update and the extension.

**Comment by sandy081** [comment]
Can you please disable that extension and let us know if freeze occurs or not?

**Comment by rohanrhu** [comment]
> Can you please disable that extension and let us know if freeze occurs or not?

Still there are freezings :/ Probably it is not related to that extension.

**Comment by rohanrhu** [comment]
I see a notification like "colorize plugin takes long time" and disabled it. Now there is no any problem.

**Comment by rohanrhu** [comment]
Probably, some incompatibility issues for some plugins maybe occured with last upgrade.
