### ISSUE TITLE
Debug view model - focused stack frame

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#99857]
Failing in: https://dev.azure.com/vscode/VSCode/_build/results?buildId=45880&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=08e986c2-058e-5f01-51da-ae4278e2d74e&l=13273

Seems to be an issue with using `!` in tests. In general I would try to avoid `!` as much as possible as it bypasses strict null checks.

**Comment by isidorn** [comment]
Thanks for disabling the test and for filling this!
