### ISSUE TITLE
Improvements for v1.46 

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#99850]
1. List of pinned tabs 
- need pin-out by checkboxes
- should be a list like TODO, Debug
- the idea is to hide some times pinned tab (eg. by checbox - visibility), to not close tab and not search again if to much tabs and the pinned version
2.  Terminals as tabs in main window
- the short size of window require often scroll up/down, in case main tab is hudge (idea is to resignation with down tab and pin-in as tab
3. Debug tree/list of elements have hudge fonts and they are not for change - I don't know how to change or it is possible to made smalest (vhr need this in option/config)
4. Need manage for github repositories, eg. working with more than 1, 
- expecting checkbox to select active repository
5. Need management with profile of configs
- maybe by login, expecting easy select for config.json and other for projects without opening other projects
6. Need option to roll-out the icons in menu and set how many there can be visible as normal
https://github.com/microsoft/vscode/issues/58368 - the issue is stil not solved for laptops
https://github.com/microsoft/vscode/issues/46403
7. Tab/cards and files comparation need better highlight as left and right side in list of files 
- eg. left green right reed
8. Number counter for rows in terminal, problems card, etc. (like table: No; event)
- want talk in work about No position as rows without showing this by finger
https://github.com/microsoft/vscode/issues/83127
- the datatime with this can be usable, specialy for debug console
9. Need icons in menu as rows/positions (now are just names and this is not cognitive to fast navigation)

..yes I know VSC team don't like my TODOs (for reflections and inspiration)

**Comment by egamma** [comment]
@ManPython thans for the great list.

>..yes I know VSC team don't like my TODOs (for reflections and inspiration)

This is not correct, we appreciate suggestions. However, enable that community members can upvote on features, the features need to be filed separately. Also when doing that please do a duplicate search. Many of the features you mentioned are already in the repository rather than filing a new one, please upvote the existing feature.

I'm closing this issue and looking forward to several issue reports that enable community participation.

**Comment by ManPython** [comment]
I think that options/settings need breadcrumbs and path url as sections to easy support useres in some settings around VSC and Extensions.
```
Text Editor > Cursor
Text Editor > Find
Text Editor > Font
..
Workbench > Appereance
Workbench  > Breadcumbs

```
Then:
```
User > Text Editor > Cursor
Extensions > SomeExtension > GitLens 
```
Optimized path
```
User/Text Editor/Cursor
Extensions/SomeExtension/GitLens#setting1 
Extensions/SomeExtension/GitLens#setting1=2
```
