### ISSUE TITLE
vscode open base64 code make windows system crushed

### ISSUE THREAD

**Issue by Mavinbin** [microsoft/vscode#99861]
when I open a css file which contains base64 code in vscode editor, it makes windows system into blue screen，this bug is always happened.

**Comment by VarunAnandK** [comment]
Can u please give file.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you provide example of base64 code that causes problems as was asked above and other data required by issue template (VSCode version, OS, extension etc., can be copied from about info or from issue that prefilled if reported through Help > Report Problem)

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`
