### ISSUE TITLE
.bas files (from excel VBA) doesn't show accented letters in french in UTF8 encoding

### ISSUE THREAD

**Issue by MilesTEG1** [microsoft/vscode#99865]
Issue Type: <b>Bug</b>

Hello,
On windows, in a french environnement, .bas files from excel VBA are encoded in UTF8, vbut accented letters aren't not displayed correctly. Example :
d�cimale
It should be : décimale
![image](https://user-images.githubusercontent.com/29298312/84388926-a7df7c00-abf5-11ea-832c-6bbf402cfaa0.png)

If I reopen with encoding "Western ISO 8859-15" they are showed correctly.
It's annoying that the .bas file aren't open automaticaly with this encoding...

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
avb|afe|1.11.3
multiwindows-highlight|aki|0.0.9
markdown-toc|Ala|1.5.6
vscode-form|ben|0.0.1
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
ini-for-vscode|Dav|0.0.4
docs-markdown|doc|0.2.73
prettier-vscode|esb|5.0.0
shell-format|fox|7.0.1
sort-json-array|fvc|2.0.3
vscode-pull-request-github|Git|0.16.1
better-shellscript-syntax|jef|1.0.13
vscode-format-context-menu|lac|1.0.4
uncrustify|Lau|2.20.2
prettify-json|moh|0.0.3
python|ms-|2020.5.86806
remote-wsl|ms-|0.44.2
cpptools|ms-|0.28.3
powershell|ms-|2020.4.0
vscode-open-iterm2|mus|0.0.4
run-external|nac|0.1.2
emoji|Per|0.0.3
highlight-counter|ram|1.5.1
code-settings-sync|Sha|3.4.3
vba|spe|1.4.0
vscode-vba-icons|spe|1.0.2
vscodeintellicode|Vis|1.2.8
vscode-icons|vsc|10.1.1
json|Zai|1.0.4
propertylist|zho|0.0.2
material-theme|zhu|3.7.3

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Try adding this to your settings (untested):
```
 "[vb]": {
    "files.encoding": "iso885915"
  }
```

**Comment by MilesTEG1** [comment]
> Try adding this to your settings (untested):
> 
> ```
>  "[vb]": {
>     "files.encoding": "iso885915"
>   }
> ```

Unfortunatly, it doesn't work. I tried to replace vb by bas, but no more luck.

**Comment by gjsjohnmurray** [comment]
What language mode is the file operating in? There's a clickable status bar indicator at the right-hand end to show this.

**Comment by MilesTEG1** [comment]
My OS is in french.
I don't really understand the indications you gave...

In searching for the settings encoding, I found this :
    "files.autoGuessEncoding"
I set it to true, and, tadamm ! My bas file are opened correctly :D

**Comment by MilesTEG1** [comment]
> This is the language Mode indicator I was referring to:
> 
> ![image](https://user-images.githubusercontent.com/6726799/84400384-dd866400-abf9-11ea-8bc6-db3af1933906.png)

Haaa Ok, so it's "vba" :
![image](https://user-images.githubusercontent.com/29298312/84419568-15e96a80-ac19-11ea-9746-11cc10eb71e4.png)

**Comment by gjsjohnmurray** [comment]
So if you want to get 8859-15 when you open a file that is configured to use language id `vba` try this:

 "[vba]": {
    "files.encoding": "iso885915"
  }

**Comment by MilesTEG1** [comment]
> So if you want to get 8859-15 when you open a file that is configured to use language id `vba` try this:
> 
> ```
>  "[vba]": {
>     "files.encoding": "iso885915"
>   }
> ```

Hello,
Thanks, after deactivating the "auto guess encodding", your solution works fine 😃  Thank you !
But I'm not sure what encoding I must use... as I don't know how to choose 😆

**Comment by gjsjohnmurray** [comment]
I think you need to find out what encoding was used by the app which wrote the files.

Please close this issue here.

**Comment by MilesTEG1** [comment]
> I think you need to find out what encoding was used by the app which wrote the files.
> 
> Please close this issue here.

Ok, Thanks
(The app is Excel, and Notepad++ open the files as ANSI (there is no ANSI encoding option in VSCode): 
![image](https://user-images.githubusercontent.com/29298312/84483610-df076900-ac99-11ea-8196-c5b8a834a64e.png)

**Comment by gjsjohnmurray** [comment]
https://en.wikipedia.org/wiki/ANSI_character_set

https://stackoverflow.com/questions/701882/what-is-ansi-format

**Comment by MilesTEG1** [comment]
Ok, so the "Windows 1252" encoding with "auto guess encoding" enabled was the best choice 😃 
Thanks !
