### ISSUE TITLE
Error after Standby: failed to save [file]: Unable to write file (Unknown (FileSystemError): Error: UNKNOWN: unknown error, open [file]

### ISSUE THREAD

**Issue by lorenzznerol** [microsoft/vscode#99863]
Error after Standby: failed to save xyz.py: Unable to write file (Unknown (FileSystemError): Error: UNKNOWN: unknown error, open xyz.py

Slightly similar and already closed issue: https://github.com/Microsoft/vscode/issues/59431

Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. have a file open and activated (whatever file, error thrown when using txt, java or py files)
2. go into standby mode
3. login again and save file
4. the .py file cannot be saved anymore, and it has 0 Bytes and is corrupted. It cannot be deleted or moved neither in Windows nor in VSC menu.

The error does not appear to files that are not currently active. I can have a couple of files open, but only the one that I am currently working on gets corrupt after standby.
The error does not appear if I just switch off and on the internet.

Same error even occurs after "save as", sort of a domino effect here:
1. have already unsavable .py or .java file open
2. save that corrupted file into a new file. An error shows that the current corrupted file cannot be saved (seems as if VSC saves the file before it "saves as" a new file), but the new file is saved properly. Now do not close the erroneous file without saving, but leave it open.
3. go into standby mode and come back
4. the new file is now as corrupt as the older corrupted one, the file cannot be saved anymore, and it has 0 Bytes. It cannot be deleted or moved neither in Windows nor in VSC menu.

You can avoid that by simply closing the older corrupted file without saving, and of course keeping closed the new file as soon as you go into standby.

It is quite possible that I have a problem with my standby of course, but it might still be a VSC issue.

Does this issue occur when all extensions are disabled?: Yes
Does this issue occur when started with `code --verbose`?: Yes

**error log:**

I used the instructions from https://github.com/Microsoft/vscode/issues/59431 that had a similar issue.
- run `code --verbose` from the command line and attach the output
- in Code select `Help | Toggle Developer Tools` and select the `Console`
- attach any output you see in the Console you can find

after coming back from standby, saving the file (reproducible, it always happens like this after standby):
workbench.desktop.main.js:2931 Failed to save 'main4.py': Unable to write file 'd:\...\main8.py' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, open 'd:\...\main4.py')

when the corrupted main4.py was open at the end of VSC, it normally is loaded from the vsc temp files, but cannot really be opened or saved. After closing it without saving to check if I can reload it, it is still unreadable.:
Unable to open 'main4.py': Unable to read file notificationsAlerts.ts:40 Unable to open 'main4.py': Unable to read file 'd:\...\main4.py' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'd:\...\main4.py').

console.ts:137 [Extension Host] Error Python Extension: 2020-06-11 13:02:36: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'd:\...\.vscode\settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'd:\...\.vscode\settings.json')	at _handleError (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:653:800)	at processTicksAndRejections (internal/process/task_queues.js:85:5)	at async v.readText (c:\Users\Admin\.vscode\extensions\ms-python.python-2020.5.86806\out\client\extension.js:1:551272)	at async doesFileNeedToBeFixed (c:\Users\Admin\.vscode\extensions\ms-python.python-2020.5.86806\out\client\extension.js:48:842707)	at async c:\Users\Admin\.vscode\extensions\ms-python.python-2020.5.86806\out\client\extension.js:48:841709	at async Promise.all (index 1)	at async d.getFilesToBeFixed (c:\Users\Admin\.vscode\extensions\ms-python.python-2020.5.86806\out\client\extension.js:48:841655)	at async d.updateTestSettings (c:\Users\Admin\.vscode\extensions\ms-python.python-2020.5.86806\out\client\extension.js:48:841282)] {  code: 'FileNotFound',  name: 'EntryNotFound (FileSystemError)'}

console.ts:137 [Extension Host] Info Python Extension: 2020-06-11 13:02:39: autoSelectInterpreter, Class name = f, completed in 7721ms, has a falsy return value, Arg 1: <Uri:d:\...>, Return Value: undefined

console.ts:137 [Extension Host] Error Python Extension: 2020-06-11 13:02:39: Failed to get interpreter information for 'C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\python.exe' [Error: Command failed: "C:\\Users\Admin\AppData\Local\Microsoft\WindowsApps\python.exe" "c:\Users\Admin\.vscode\extensions\ms-python.python-2020.5.86806\pythonFiles\pyvsc-run-isolated.py" "c:\Users\Admin\.vscode\extensions\ms-python.python-2020.5.86806\pythonFiles\interpreterInfo.py"Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640	at ChildProcess.exithandler (child_process.js:308:12)	at ChildProcess.emit (events.js:203:13)	at maybeClose (internal/child_process.js:1021:16)	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {  killed: false,  code: 9009,  signal: null,  cmd: '"C:\\\\Users\\Admin\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe" "c:\\Users\\Admin\\.vscode\\extensions\\ms-python.python-2020.5.86806\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\Admin\\.vscode\\extensions\\ms-python.python-2020.5.86806\\pythonFiles\\interpreterInfo.py"'}
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
console.ts:137 [Extension Host] Error Python Extension: 2020-06-11 13:02:39: Failed to get interpreter information for 'C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\python3.exe' [Error: Command failed: "C:\\Users\Admin\AppData\Local\Microsoft\WindowsApps\python3.exe" "c:\Users\Admin\.vscode\extensions\ms-python.python-2020.5.86806\pythonFiles\pyvsc-run-isolated.py" "c:\Users\Admin\.vscode\extensions\ms-python.python-2020.5.86806\pythonFiles\interpreterInfo.py"Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640	at ChildProcess.exithandler (child_process.js:308:12)	at ChildProcess.emit (events.js:203:13)	at maybeClose (internal/child_process.js:1021:16)	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {  killed: false,  code: 9009,  signal: null,  cmd: '"C:\\\\Users\\Admin\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe" "c:\\Users\\Admin\\.vscode\\extensions\\ms-python.python-2020.5.86806\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\Admin\\.vscode\\extensions\\ms-python.python-2020.5.86806\\pythonFiles\\interpreterInfo.py"'}

// on opening again:
notificationsAlerts.ts:40 Unable to open 'main4.py': Unable to read file 'd:\...\main4.py' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'd:\...\main4.py').

// same file error even occurs when having saved an unsavable main8 with "save as" into main9.py, but without having opened main9, and then go into standby and back again. Then the main9.py is also corrupted:
exit - resulted in a save error: Error: Unable to write file 'd:\...\main9.py' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, open 'd:\...\main9.py') file:///d:/.../main9.py

<img width="508" alt="0 byte files" src="https://user-images.githubusercontent.com/52793248/84387740-c6447800-abf3-11ea-834f-5c2fa3b58725.png">
<img width="333" alt="cannot be deleted" src="https://user-images.githubusercontent.com/52793248/84387742-c775a500-abf3-11ea-9fd1-d47eef609d98.png">
<img width="337" alt="cannot be moved" src="https://user-images.githubusercontent.com/52793248/84387743-c775a500-abf3-11ea-9787-820c10d3a1aa.png">

**I have just had another domino effect error here. I have closed a file that was not corrupted and perfectly working, it could be reopened and saved. When I reopened the VSC that I had opened without extensions (for the error testing only) to get my Python extensions back, this perfectly working new file that was saved correctly was simply empty. Of course I had a backup, else I would have lost my work now only because of the testing here. Thus, I recommend having backups of every file even from working files that are not corrupted as long as this issue is open.**

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by lorenzznerol** [comment]
I have already had it run without extensions before I had posted here. No extension was working (checked!) during the testing, with the same reproducible issue.

Now there is a new thing: my laptop which has caused the issue has crashed totally. I am not able to prove my issue again, as it seems. Either, this is an issue to close then, or you go for it without anyone else affected :). I suggest the former step, and perhaps just to revive this issue when it appears to anyone else. Thank you
