### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by Ananya-M** [microsoft/vscode#99869]
Issue Type: <b>Bug</b>

1. Installed version 1.46 by disabling the antivirus. ( if not an error occurs during installation that says, move file failed: code 2)
2. The first time I am able to run the test code after installing python extension.
3. After closing the applicatiion and starting again, the VS code is titled as an unsupported version.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.5.86806
vscode-yaml|red|0.8.0

</details>

**Comment by gjsjohnmurray** [comment]
Which antivirus? It sounds like this is interfering with the VS Code files.

**Comment by Ananya-M** [comment]
Quick Heal Total Security 17.0

**Comment by gjsjohnmurray** [comment]
See #94858 for advice from other Quick Heal users.

/duplicate
