### ISSUE TITLE
Default workspace settings

### ISSUE THREAD

**Issue by nihaals** [microsoft/vscode#99868]
I'm not really sure how this could be implemented but I have a few ideas.

## The problem
VSCode's `.vscode` is quite different to a lot of IDEs. It works well when committed to source control. The files are quite neat, make sense and there isn't any clutter like the list of tabs that are open. I know I'm not the only one who currently ignores `.vscode`, but some of its uses, like `launch.json`, should definitely be committed. I think the biggest reason why people do this is because it's marked as a config directory (starting with a `.`), which just doesn't feel right when you see it in a GitHub repo. If you get past that, then a problem is your workspace settings may have a few values that are machine specific. For example, if you are using [Poetry](https://python-poetry.org/) with the recommended and default settings, it creates the virtual environment in a folder in a config folder (not in your workspace) and will contain a unique hash part of the name. This means that you can't really push your entire settings just because of this single value (seems like VSCode isn't going to get built in support for getting your environment path, see https://github.com/microsoft/vscode-python/issues/8372, the stance seems to be there are so many tools it just doesn't make sense supporting them all).

### Ignore the line
You could just keep not committing this single line and any other machine specific values, but you would need to make sure they are not the last key, remember to not commit everything *forever*, and tell everyone else to do the same. You could create a pre-commit hook too, but this isn't great.

### Ignore `.vscode/settings.json`
You could add your workspace settings to your gitignore. This has the downside of losing any workspace specific settings that work particularly well your project, for example you may need to make sure autosave isn't on as it might mess up anything that watches and compiles (I've had this happen).
1. You could document these "required" settings in your README, but your making it more complicated than it could be, especially if you need a large number of settings changed, and if you're just copying and pasting the contents of an example `settings.json`, it feels silly when your editor could do this for you
2. You could add something like `vscode/settings.json`, `vscode.example/settings.json` or `.vscode/settings.example.json` (haven't tested this to see what happens if you have random files in your `.vscode`). Then when someone cloned they would copy and paste this file into the correct location. This has the same problem as before.

### Implement `.vscode/*.example.json`
This would somehow influence your actual config file, for example `.vscode/settings.example.json` could prompt VSC to ask the user if they want to use this example and will automatically copy it over and possibly open it. There's probably a few other ways this connection between the example and the real could be made.

### Implement some kind of ignore system
I have no idea how this would work, but it would be similar to Preferences Sync where you can exclude certain settings and machine specific settings from being shared.

One way to get more people interested in committing this folder and saving some time from having to debug editor settings is making it easier to share settings, and with machine specific settings this is hard. The last two suggestions are probably my favourite as they make the most sense and are much more usable. I would call the others workarounds.

**Comment by sandy081** [comment]
By default workspace settings do you mean workspace settings which are not sharable like not getting pushed into shared repository (like in git)?

**Comment by nihaals** [comment]
Are you referring to the title or one of the solutions? I didn’t know how to summarise the problem in the title so it might not reflect the actual problem mentioned in the issue

**Comment by sandy081** [comment]
> A short summary is the ability to not have some of your settings pushed to Git

Ok it makes it clear and there is an ask for this already. Hence making it duplicate

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/40233
