### ISSUE TITLE
Accounts

### ISSUE THREAD

**Issue by pashutaz** [microsoft/vscode#99876]
Issue Type: <b>Feature Request</b>

Why I cannot set up sync account in accounts section? It just shows me 'you are not signed in to any accounts', why not to ask create account or something? Its now user friendly at all!

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:04.923Z)
OS version: Linux x64 5.4.0-37-generic snap
Remote OS version: Linux x64 3.16.0-4-amd64

**Comment by tamimmirza** [comment]
Yes I am facing the same issue.
It doesn't even provide any details on how to log in or which account (Microsoft, Google, GitHub, etc) to log in.

Is it a work-in-progress feature or bug?

**Comment by gjsjohnmurray** [comment]
/duplicate - see https://github.com/microsoft/vscode/issues/99788#issuecomment-642548433
