### ISSUE TITLE
Can VSCode remote auto get git credential manager password?

### ISSUE THREAD

**Issue by HuAaron** [microsoft/vscode#99872]
I set two Windows 10 machines A and B. I installed SSH Server(build-in) on B and SSH client on A. 
I use Remote SSH (key auth) function in vscode from A to connect to B. I don't need to type username and password on vscode and just develop on B. However, when I run command on vscode terminal shell to git pull code, it prompt for username and password every time. When I login to B (rdp) and open vscode locally on B to git pull, it didn't ask for username and password as I already save this cred to credential manager on Windows. 
Any idea how to avoid this on vscode remote? (I don't want use private key to git clone or something)

**Comment by joaomoreno** [comment]
The git extension now has API for participants to join in on the auth dance, so the Remote SSH extension could potentially do this? 🤔 

pinging @chrmarti since he is knowledgeable in this area

**Comment by chrmarti** [comment]
I have figured out how to register a Git credentials helper on the remote (B) that forwards all requests to the Git credentials helper on the local machine (A).

@HuAaron It sounds like you have a credentials manager on B that works for Git when RDPing into B, but not when Remote-SSHing into B? That would be different from what my approach solves. Maybe the credentials manager requires a GUI login to work and an SSH login is not sufficient? What do you get for `git config --show-origin --get credential.helper`?

**Comment by HuAaron** [comment]
> I have figured out how to register a Git credentials helper on the remote (B) that forwards all requests to the Git credentials helper on the local machine (A).
> 
> @HuAaron It sounds like you have a credentials manager on B that works for Git when RDPing into B, but not when Remote-SSHing into B? That would be different from what my approach solves. Maybe the credentials manager requires a GUI login to work and an SSH login is not sufficient? What do you get for `git config --show-origin --get credential.helper`?

The output of "git config --show-origin --get credential.helper is:
file:C:/Program Files/Git/etc/gitconfig manager

Let me explain this more:
VSCode installed on A, and remote ssh code to B. When git push or pull ( actually this is on B), it asked for creds. Thing is different compared to when I open vscode directly on B: When git pull it doesn't ask for cred as there is a copy of cred on Credential manager (Control Panel) on B.  
This is nothing about A, only B.

**Comment by roblourens** [comment]
Is that what you get when running that command in the terminal through ssh? Or through rdp? Are they the same?

**Comment by chrmarti** [comment]
I think your passwords are stored in the Windows Credential Manager and I'm not sure if that is unlocked in an SSH session. When logged in via `ssh`, try running `cmdkey /list` to see if you have access to the Git credentials. Maybe that will ask you to unlock?

**Comment by HuAaron** [comment]
> I have figured out how to register a Git credentials helper on the remote (B) that forwards all requests to the Git credentials helper on the local machine (A).
> 
> @HuAaron It sounds like you have a credentials manager on B that works for Git when RDPing into B, but not when Remote-SSHing into B? That would be different from what my approach solves. Maybe the credentials manager requires a GUI login to work and an SSH login is not sufficient? What do you get for `git config --show-origin --get credential.helper`?

It sounds like you have a credentials manager on B that works for Git when RDPing into B, but not when Remote-SSHing into B?
-- Correct. 
The output of `git config --show-origin --get credential.helper` is:
`file:C:/Program Files/Git/etc/gitconfig manager`
And the output of `cmdkey /list` is:

```
Currently stored credentials:

* NONE *
```
![image](https://user-images.githubusercontent.com/28371968/85967180-725bd080-b9f4-11ea-816d-a01ffc821c9e.png)
