### ISSUE TITLE
Cannot stage files from source-control

### ISSUE THREAD

**Issue by ebrolask** [microsoft/vscode#99870]
- VSCode Version: May 2020
- OS Version: Windows 10 64bit

Steps to Reproduce:

1. Click the + icon to stage a changed file
2. Windows prompts an alert saying that the file is outside the repository

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/22645262/84392907-8fa13a00-abc0-11ea-830f-9f19f5a9ca12.png)

**Comment by TimePerformance** [comment]
same problem after updating

**Comment by lou920217** [comment]
I've had this problem, but I'll just update git to the latest version

**Comment by ebrolask** [comment]
> I've had this problem, but I'll just update git to the latest version

This fixed my issue. Thannks!
