### ISSUE TITLE
Attempting to run a .py file makes vscode open instead of running it!

### ISSUE THREAD

**Issue by rogersachan** [Microsoft/vscode#9987]
- VSCode Version: 1.3.1
- OS Version: Windows 10 1511

Steps to Reproduce:

1. Install VSCode
2. Attempt to run hello.py
3. Opens vscod instead of running the file

**Comment by kieferrm** [comment]
@rogersachan pls provide concrete steps that help us to recreate the problem without guessing what you mean. For example: *attempt to run hello.py*. What is `run` concretely? In what context to you `run` it? etc. Thanks!

**Comment by rogersachan** [comment]
In Python, you run a .py script by typing out the name of the file and its
ending. In this and any scenario regarding running a .py file in a
directory.

1. Open command prompt
2. Navigate to C://Users/Roger/Documents
3. Type hello.py (This should run a py file in all cases.
4. Opens VSCode instead (This doesn't happen on machines without VSCode,
and isn't supposed to happen)

**Comment by kieferrm** [comment]
@rogersachan when I try this on a brand new Windows 10 system (only python and vscode installed) I'm being asked about which app should be used to open the file. I'd suspect your system is configured to always use vscode to open `*.py` files. 

<img width="397" alt="screen shot 2016-08-02 at 2 23 27 pm" src="https://cloud.githubusercontent.com/assets/4674940/17345855/f78c2ab8-58bc-11e6-91ee-2e346b41eac8.png">


Please go to:
<img width="638" alt="screen shot 2016-08-02 at 2 26 23 pm" src="https://cloud.githubusercontent.com/assets/4674940/17345896/273bde8e-58bd-11e6-89c3-2a60a1d337f5.png">

and reset the default app for python files.

**Comment by rogersachan** [comment]
@kieferrm I use **Anaconda** as my distro of python, so python doesn't show up in my picker to begin with.

I get this when going to .py

![alt text](http://i.imgur.com/ncdXVFe.png "Logo Title Text 1")

There is no RESET button anywhere. Neither can I choose a new .exe for it.

**Comment by kieferrm** [comment]
@rogersachan you can use  `C:\Windows\System32>assoc | find /i "py"` to check the association for python files. It's most like `Python.File`. Then use `C:\Windows\System32>ftype  Python.File` or `C:\Windows\System32>ftype | find /i "py"` to find the open command string for python files. You should be able to delete the open command string with `ftype Python.File=`.
