### ISSUE TITLE
Test downloading extension VSIXs to a cached folder

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99873]
Ref - #99674

- [x] Mac @chrmarti
- [x] Windows @9at8
- [x] Linux @bpasero

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%2399873%0A%0A)

---

Extension VSIXs are now downloaded to a cached folder under `<user_data_dir>/CachedExtensionVSIXs`

1. Go to extension view and install an extension
2. Make sure that VSIX is downloaded to above provided directory
3. Uninstall the extension, and also go to Extensions Folder using command `Extensions: Open Extensions Folder` and delete the extension (This is to make sure that extension is downloaded again).
4. Install the extension again. 
5. Make sure that downloaded VSIX is used. You can test that by making sure that there is no request to Marketplace for the VSIX. To test that, 
  - Open shared process (`Developer: Toggle Shared Process`) and go to networks tab
  - There is no request to Marketplace to download VSIX Eg: `https://........../Microsoft.VisualStudio.Services.VSIXPackage`
6. Delete the downloaded VSIX in the above pointed directory and follow steps 3 & 4.
7. Make sure that VSIX is downloaded again to the above pointed directory. 
8. Make sure that we cache only recent 20 VSIXs.
  - Use extension packs with many extensions to install or uninstall bunch of extensions
  - Clean up is done when code is started. So you have to restart for clean up to kick off.

**Comment by bpasero** [comment]
It looks like the limit of 20 extensions cache is only respected after restart but not if installing >20 in one go without restart.

**Comment by sandy081** [comment]
Yes as mentioned in description

> Clean up is done when code is started. So you have to restart for clean up to kick off.
