### ISSUE TITLE
Erro no terminal do VSCode

### ISSUE THREAD

**Issue by cajlonbatista** [microsoft/vscode#99875]
# When typing an installation command, you receive this error in the terminal, before pressing Enter, as often when I type the @ character:

_System.ArgumentOutOfRangeException: the value must be greater than or equal to zero and less than the size of the console buffer in this dimension.
Parameter name: left
The actual value was -1.
    in System.Console.SetCursorPosition (left Int32, top Int32)
    in Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft (Int32 value)
    in Microsoft.PowerShell.PSConsoleReadLine.ReallyRender (RenderData renderData, String defaultColor)
    in Microsoft.PowerShell.PSConsoleReadLine.ForceRender ()
    on Microsoft.PowerShell.PSConsoleReadLine.Insert (Char c)
    in Microsoft.PowerShell.PSConsoleReadLine.SelfInsert (Nullable`1 key, arg object)
    in Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey (ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
    in Microsoft.PowerShell.PSConsoleReadLine.InputLoop ()
    in Microsoft.PowerShell.PSConsoleReadLine.ReadLine (Runspace execution space, EngineIntrinsics engineIntrinsics)
-------------------------------------------------- ---------------------_

**Comment by Tyriar** [comment]
@JacksonKearl stack traces look like Brazil Portuguese apparently.

**Comment by Tyriar** [comment]
Please provide a screenshot of [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal
