### ISSUE TITLE
Update imports takes a lot of time

### ISSUE THREAD

**Issue by Sti2nd** [microsoft/vscode#99885]
My colleagues and I suspects the time of updating the imports after renaming a file has increased for us in the last couple of days / from last week to this week. Today, waiting for the language server to update imports after renaming a file takes around 1:30 minutes, while we believed it took 20 - 30 seconds before.

The feature I am talking about is the one that produces this message:
![image](https://user-images.githubusercontent.com/6373430/84409509-cfdad980-ac0d-11ea-9a4e-af5acf2c16f4.png)

About project: a large project in Angular and TypeScript.
Editor: Visual Studio Code, it was upgraded to 1.46 today, used 1.45 last week.

There are not much info I am able to give, I don't know which version of this language server I have been on. If others could confirm this is an issue for them too that would be great.

**Comment by mjbvz** [comment]
@Sti2nd Are you using a custom version of TypeScript in your workspace? Also can you share the project?

**Comment by Sti2nd** [comment]
I am sorry, the project is proprietary so I cannot share it.

I don't know what a custom TypeScript version is, we are on TypeScript 3.5.3 right now.

Here is a selection of the package.json fields, if that helps.

```json
{
  "typings": "./src/typings.d.ts",
  "dependencies": {
    "@angular/animations": "8.2.0",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "8.2.0",
    "@angular/compiler": "8.2.0",
    "@angular/core": "8.2.0",
    "@angular/forms": "8.2.0",
    "@angular/platform-browser": "8.2.0",
    "@angular/platform-browser-dynamic": "8.2.0",
    "@angular/router": "8.2.0",
    "@aspnet/signalr": "^1.1.4",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@nicky-lenaers/ngx-scroll-to": "^2.0.0",
    "angular2-chartjs": "0.5.1",
    "angular2-hotkeys": "2.1.4",
    "bootstrap": "4.3.1",
    "class-validator": "0.9.1",
    "core-js": "2.5.7",
    "flatpickr": "4.6.2",
    "font-awesome": "4.7.0",
    "html2canvas": "1.0.0-alpha.10",
    "jquery": "3.4.1",
    "jsoneditor": "5.19.2",
    "moment": "2.24.0",
    "ng2-dnd": "^5.0.2",
    "ng2-select2": "1.0.0-beta.10",
    "ngx-bootstrap": "^5.3.2",
    "ngx-toastr": "^10.2.0",
    "platform": "1.3.5",
    "popper.js": "1.15.0",
    "rxjs": "6.5.2",
    "select2": "4.0.6-rc.1",
    "tinymce": "4.9.5",
    "tinymce-i18n": "17.12.31",
    "tslib": "^1.11.0",
    "zone.js": "~0.10.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.801.3",
    "@angular/cli": "8.2.0",
    "@angular/compiler-cli": "8.2.0",
    "@angular/language-service": "8.2.0",
    "@biesbjerg/ngx-translate-extract": "2.3.4",
    "@types/jasmine": "2.8.8",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "10.14.14",
    "@types/select2": "4.0.44",
    "@types/signalr": "^2.2.36",
    "codelyzer": "^5.2.1",
    "jasmine-core": "2.8.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.4.3",
    "karma-jasmine": "1.1.2",
    "karma-jasmine-html-reporter": "0.2.2",
    "node-sass": "^4.13.1",
    "patch-package": "6.1.2",
    "protractor": "5.1.2",
    "ts-node": "8.3.0",
    "tslint": "5.18.0",
    "typescript": "3.5.3",
    "webpack-bundle-analyzer": "3.4.1"
  }
}
```

**Comment by mjbvz** [comment]
Are you using TypeScript 3.5.3 in your workspace? With a js/ts file open, run `Select TypeScript Version` to check which TypeScript version is active

**Comment by Sti2nd** [comment]
For future reference, I used VS Code's Typescript version (3.9.4). It seems using the workspace version (3.5.3) decreased the renaming time with 30 seconds. Still took 1 minute, but that could be the size of the project.
