### ISSUE TITLE
"when" clause for diff editor

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#9988]
It would be great to have a way to define a keyboard shortcut for when the diff editor is/isn't active. I want one shortcut to toggle between the file and the Git diff view. Like: 

```
{ "key": "ctrl+alt+d", "command": "workbench.action.git.globalOpenChange",
        "when": "!diffEditorActive" },
{ "key": "ctrl+alt+d", "command": "workbench.action.git.globalOpenFile",
        "when": "diffEditorActive" }
```

**Comment by bpasero** [comment]
Try `textCompareEditorVisible`
