### ISSUE TITLE
PHP: Highlight SQL code in string if not first line.

### ISSUE THREAD

**Issue by mbomb007** [microsoft/vscode#99886]
At the moment, SQL code is only syntax highlighted in a PHP string if the SELECT or first code is on the first line of the string:

```php
    $query = "SELECT *
      FROM my_table
      WHERE 1=1
    ";
```

This doesn't work nicely if you want to use a multi-line string with the code starting on a clean line:

```php
    $query = "
      SELECT *
      FROM my_table
      WHERE 1=1
    ";
```

Screenshot:

![Capture](https://user-images.githubusercontent.com/22807401/84412355-c1bc9700-abd4-11ea-8abe-affd4f4c58f5.PNG)

This SQL is just an example and could easily go on a single line, but for large queries with many lines, it would be nice if highlighting worked even if the first line was all whitespace. It would be awesome if it checked the first non-whitespace line for SQL code.

**Comment by roblourens** [comment]
https://github.com/atom/language-php/issues/87

**Comment by adjenks** [comment]
@roblourens It doesn't look like VS Code uses the atom language package, or am I wrong? 
https://github.com/microsoft/vscode/blob/45db52ba6bd211cecd03897caee0531350071721/extensions/sql/cgmanifest.json

**Comment by adjenks** [comment]
I also noticed that VS code doesn't tokenize and highlight the word `WITH` for a CTE, but it's been fixed in the atom package already. 
![image](https://user-images.githubusercontent.com/10687569/84551203-b7c49200-acc1-11ea-9c1f-b52ca3cfb400.png)
![image](https://user-images.githubusercontent.com/10687569/84551224-c8750800-acc1-11ea-99e4-a063f26b9adf.png)

**Comment by roblourens** [comment]
It does use it via the PHP language. I don't see that working in Atom, can you share a screenshot of what you see?

Atom:

![image](https://user-images.githubusercontent.com/323878/84606849-dddb6500-ae6e-11ea-95f3-b60095b9325a.png)

**Comment by adjenks** [comment]
Oh interesting, it doesn't work. I stopped using atom so I just installed it now to test it, but it says the fix was merged into master in 2016, so I thought it would be in there. My mistake.
