### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by pelinoloji** [microsoft/vscode#99883]
We have written the needed data into your clipboard because it was too large to send. Please paste.I upgraded my VS Code then it has started to crash. My color pairing not showing the exact color. Prettier doesn't work also I can't see my source control files. 

CPUs | Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | 3, 12, 17
Memory (System) | 16.00GB (0.20GB free)
Process Argv | -psn_0_36873
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
html-snippets | abu | 0.2.1
bracket-pair-colorizer | Coe | 1.0.61
vscode-eslint | dba | 2.1.5
gitlens | eam | 10.2.2
prettier-vscode | esb | 5.0.0
debugger-for-chrome | msj | 4.12.8
color-highlight | nau | 2.3.0
live-sass | rit | 3.0.0
LiveServer | rit | 5.6.1
vscode-icons | vsc | 10.1.1
JavaScriptSnippets | xab | 1.8.0
ReactSnippets | xab | 2.4.0

**Comment by gjsjohnmurray** [comment]
Please disable your extensions systematically to try and discover which (if any) is causing the problem.
