### ISSUE TITLE
git fatal error: file is outside directory

### ISSUE THREAD

**Issue by iigmir** [microsoft/vscode#99881]
- VSCode Version: 1.46.0 ( a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z )
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Click the "Initialize Repository" button on the source control panel.
2. Add files to stage by clicking the plus sign on the "CHANGES" panel.
3. Then the error occurred: 
![pc](https://user-images.githubusercontent.com/11061770/84403342-2c52ee80-ac38-11ea-9421-1608004dccad.png)

The Git log is here with some of my edits:

```bash
Looking for git in: D:\Program Files\Git\bin\git.exe
Using git 2.9.2.windows.1 from D:\Program Files\Git\bin\git.exe
> git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git
> git init
> git rev-parse --show-toplevel
> git rev-parse --git-dir
Open repository: c:\Users\JohnDoe\my-repo
> git fetch
> git status -z -u
fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git check-ignore -v -z --stdin
> git add -A -- c:\Users\JohnDoe\my-repo\.gitignore c:\Users\JohnDoe\my-repo\some.files.a c:\Users\JohnDoe\my-repo\some.files.b
fatal: c:\Users\JohnDoe\my-repo\.gitignore: 'c:\Users\JohnDoe\my-repo\.gitignore' is outside repository
```

However, my Git works when using pure commands:

```bash
PS C:\JohnDoe\my-repo> git add *
warning: LF will be replaced by CRLF in .gitignore
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in some.files.a
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in some.files.b
The file will have its original line endings in your working directory.

PS C:\JohnDoe\my-repo> git rm --cached *
rm '.gitignore'
rm 'some.files.a'
rm 'some.files.b'
```

I don't know if this issue is related to the closed issue #88890.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
See also #99870

**Comment by DarrenLevine** [comment]
Same issue after upgrading to 1.46.0

**Comment by OYWB-keep** [comment]
+ 1 after upgrading to 1.46.0

**Comment by gongcChen** [comment]
Same

**Comment by wz71014q** [comment]
Same issue after update yesterday, and I resolve it update my git to 2.27

**Comment by ViperTG** [comment]
Same issue for me after updating to 1.46.0

**Comment by gjsjohnmurray** [comment]
cc @joaomoreno

**Comment by DreFalPoetry** [comment]
same question version 1.46.0

**Comment by gjsjohnmurray** [comment]
@joaomoreno maybe the built-in Git extension has been affected by [this change](https://code.visualstudio.com/updates/v1_46#_file-path-casing)

**Comment by sozonome** [comment]
I also face the same issue after VS Code updated to 1.46.
I checked my Git version and it was version 2.8.x
Then I update my Git to version 2.27 and I don't found any problems anymore.

I think it occurs when someone using older version of Git
Either update the Git version or wait for the next VS Code update

**Comment by iigmir** [comment]
Thank you @wz71014q and @sozonome, I updated my Git to 2.27 and the issue is solved.

**Comment by albu77** [comment]
Works for me after updating git

**Comment by joaomoreno** [comment]
Thanks to everyone for confirming the update to Git 2.27. And special thanks to @gjsjohnmurray for being such a good inbox tracker! 👏

**Comment by sharpround** [comment]
Any solutions other than updating git? I'm on git 2.11 for the foreseeable future, as my git installation is controlled by the organization.

**Comment by joaomoreno** [comment]
@sharpround 2.11 should actually work OK. What is the exact error you're seeing? Show me the actual error/output, thanks!

**Comment by iigmir** [comment]
I reproduce what @sharpround said in Windows 7. Here are my error/output:

```bash
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.11.1.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
> git rev-parse --git-dir
Open repository: c:\Users\john-doe\test-repo
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git check-ignore -v -z --stdin
> git add -A -- c:\Users\john-doe\test-repo\some.files.a c:\Users\john-doe\test-repo\some.files.b c:\Users\john-doe\test-repo\some.files.c
fatal: c:\Users\john-doe\test-repo\some.files.a: 'c:\Users\john-doe\test-repo\some.files.a' is outside repository
```

Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by shreepads** [comment]
Had the same issue with pretty much the same setup as @iigmir 
- OS: Windows 7 (Windows_NT x64 6.1.7601)
- VS Code 1.46.1 (user setup), commit cd9ea6, Electron 7.3.1, Chrome 78.0.3904.130 etc
- Git: v2.6

Upgrading Git to v2.22 solved the problem (git version choices limited by enterprise)

**Comment by sharpround** [comment]
@joaomoreno 
> @sharpround 2.11 should actually work OK. What is the exact error you're seeing? Show me the actual error/output, thanks!

Sure. There's really not much, though. From the beginning of the git terminal.

> git fetch
> git ls-files --stage -- C:\Users\project-folder\.gitignore
> git cat-file -s xxxxx
> git show :.gitignore
> git status -z -u
> git symbolic-ref --short HEAD
> git ls-files --stage -- C:\Users\project-folder\.gitignore
> git rev-parse master
> git cat-file -s xxxxx
> git rev-parse --symbolic-full-name master@{u}
> git show :.gitignore
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template
> git add -A -- C:\Users\project-folder\.gitignore C:\Users\project-folder\.gitignore
fatal: C:\Users\project-folder\.gitignore: 'C:\Users\project-folder\.gitignore' is outside repository

-----

Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134

-----

@iigmir, I can probably back up the version. I have to do some pretty intense elevations and logging for audits every time I make a change like that, though, so I avoid it when I can. Honestly, it's going to be easier to just use the git CLI.

**Comment by joaomoreno** [comment]
Unfortunately it seems 2.11 also has the same issue. 😢 There's really not much we can do besides recommending the update.

**Comment by brammitch** [comment]
> Any solutions other than updating git? I'm on git 2.11 for the foreseeable future, as my git installation is controlled by the organization.

@sharpround I have the same issue: VSCode 1.46.1 (user install), and Git 2.11 controlled by my organization. I added the GitLens extension and have been able to use it without any issues. This will be my workaround until they update Git.

@joaomoreno What would GitLens be doing differently that lets it work where the built-in Git does not?

**Comment by ahmedbeheiry** [comment]
I have the same issue
Git version is 2.9.3
VSCode version is 1.46.1
