### ISSUE TITLE
Active tab should have an indicator consistent with active viewlet, panel

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#99889]
- VSCode Version:
- OS Version:

![ActiveEditorTabDoesNotHaveSameActiveIndicatorAsViewletAndPanel](https://user-images.githubusercontent.com/1704059/84417510-a621b280-ac0d-11ea-8ed5-da68bc0e0d4f.png)

The active tab should probably have an indicator running along the top of the tab, consistent with how active viewlets and horizontal panels are shown.

We use an indicator to show that the tab contains changes (as shown in the package.json tab in the screenshot) but nothing indicating that the tab is active.

**Comment by misolori** [comment]
You've enabled `workbench.editor.highlightModifiedTabs`, which is disabled by default.

We do have `tab.activeBorderTop` but we don't have it set by default. @bpasero thoughts on adding an active tab indicator to our default themes to keep it consistent? 

<img width="80%" src="https://user-images.githubusercontent.com/35271042/84447316-86ce5980-abfc-11ea-9bc4-8d4acc0f3fe4.png">

I quite like how the GitHub theme works nicely with modified tabs:

<img width="80%" src="https://user-images.githubusercontent.com/35271042/84447371-a49bbe80-abfc-11ea-8823-5530d58c0d63.png">

**Comment by bpasero** [comment]
I was not a big fan of having the active indicator over the activity bar and I am not a fan of having it for tabs. My rationale is that historically we never used borders in our UI at all, only background colors. I am still not liking the fact that we have borders for indicating something. I prefer to use background/foreground color still.

**Comment by stevencl** [comment]
I too was never a big fan of active indicators in the activity bar etc. But now that we have them. we have an inconsistency. This issue on its own isn't a big deal but I am seeing more and more little inconsistencies creep into the product and I think it's worth paying attention to these.

**Comment by stevencl** [comment]
Closing this for now.
