### ISSUE TITLE
Blue tab indicator to indicate edits is inconsistent with editor indicator

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#99891]
If you make a change inside an editor with auto save off, a blue line is drawn on the tab to indicate that there are changes. At the same time, a green line is drawn in the editor gutter to show the location of the changes in the editor. These colours should probably be consistent?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by IllusionMH** [comment]
Doesn't looks like they should be synced:
1. This should be applied for files that aren't tracked in version control so there in no green "added lines" if there is no diff
1. If I've only removed lines from file - indicator in gutter will be red.
Red border on tab might be associated with "errors" state (used as color for files with errors in Explorer), not with removed lines.

**Comment by misolori** [comment]
The editor indicators on the left are SCM indicators, and those are different from the modified tabs indicator. SCM decorators can have a combination of added (green), modified (blue) or deleted (red):

![image](https://user-images.githubusercontent.com/35271042/84433483-33034680-abe3-11ea-9a39-2efa7efb7b50.png)

I don't think there is much we can change here.

**Comment by stevencl** [comment]
Sounds good.
