### ISSUE TITLE
Settings search behaves differently to search viewlet

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#99894]
- VSCode Version:
- OS Version:

The settings search expands search results when additional search terms are added (i.e., it appears to search for settings which contain one or more of the search terms). In contrast, the search viewlet reduces search results when additional terms are added as it appears to search for text which contains all search terms.
![SettingsSearchBehavesDifferentlyToSearchViewlet](https://user-images.githubusercontent.com/1704059/84419025-e97d2080-ac0f-11ea-98d7-8f5f355ec2b0.gif)

**Comment by misolori** [comment]
@roblourens is this because we're using bing's search API for the results in the settings ui but not in the search viewlet?

**Comment by roblourens** [comment]
Yeah, they are different - is that a problem though? It's not practical to do fuzzy search in your workspace and that's not what people typically want anyway.

**Comment by stevencl** [comment]
I think it's worth having the conversation. Being intentionally inconsistent is absolutely fine, I just wanted to have the conversation.

Ultimately I'm just looking for a way to minimise the impact of any differences. For example, perhaps by highlighting matching terms it might be more obvious how search is working (and would make the presentation of results more consistent with search results elsewhere).

![image](https://user-images.githubusercontent.com/1704059/84509493-b2644900-acbb-11ea-93c4-4c76ac8e6480.png)

Like I said though, I just want to make sure that we are deliberate and intentional about possible inconsistencies and that we aren't overlooking any ways in which we can improve the overall experience by addressing any unintentional inconsistencies.

**Comment by roblourens** [comment]
We tried to do this earlier, but the fuzzy search produces too many matches that aren't quite accurate, leading to lots of visual spam. Just highlighting literal matches might help though.

**Comment by stevencl** [comment]
I remember that now. I guess it might end up confusing matters if there are results that don't contain any literal matches and so aren't highlighted. Maybe we should just leave things as they are. I'll close this for now, glad we had the conversation.
