### ISSUE TITLE
Problems badge does not have the same colour as other badges

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#99893]
![ProblemBadgesAreNotThemedColour](https://user-images.githubusercontent.com/1704059/84418729-7b385e00-ac0f-11ea-9fd1-0cb8d3e5c66a.png)

The problems panel badge is not the same colour as other badges. They should be blue in this case instead of grey.

**Comment by misolori** [comment]
@stevencl I believe we have primary (blue) and secondary badges (grey). These secondary badges also show up in the debug viewlet, opened editors, and search results (settings, keyboard shortcuts). So these are intentionally a different color.

**Comment by stevencl** [comment]
Sounds good.
