### ISSUE TITLE
No way to distinguish between view panels that can be moved and those that can't

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#99898]
- VSCode Version:
- OS Version:

Some viewlet panels can be dragged out and placed in other panels. Some panels cannot. However, there is no way to distinguish between these other than trying to drag and drop and seeing if the action completes.
![NoWayToTellWhichPanelsCanBeMovedAndWhichCant](https://user-images.githubusercontent.com/1704059/84419394-73c58480-ac10-11ea-8819-586c7adb06e8.gif)

**Comment by sbatten** [comment]
This experienced seemed to be everybody's preference as opposed to having feedback that shows up far away from the dragged object. We don't show feedback if the action will not complete.

**Comment by stevencl** [comment]
There is feedback showing that the editor area is not a valid drop target (see the 'no entry' icon that appears when dragging over the editor). Can't we do the same when dragging over other UI that is also not a valid target?

**Comment by sbatten** [comment]
fair. we can add that feedback for non-macOS. the editor feedback does not exist on macOS either. this still does not indicate to the user until they drag the item all the way from the activity bar to the panel however, so not sure if it addresses all your concerns or if it is sufficient

**Comment by stevencl** [comment]
Thanks, I think this would be a good improvement.

**Comment by sbatten** [comment]
To Verify (**On Windows/Linux**):
1. Try to drag the extensions viewlet icon to the panel
2. Ensure that the forbidden cursor icon appears

**Comment by stevencl** [comment]
Looks good!
