### ISSUE TITLE
Editor ellipsis commands shown centred when tabs are off

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#99895]
- VSCode Version:
- OS Version:

With editor tabs turned off, the editor ellipsis menu draws the list of commands centred rather than left justified.
![WithTabsOffEditorEllipsisMenuCommandsAreDrawnCenteredInsteadOfLeftJustified](https://user-images.githubusercontent.com/1704059/84419178-23e6bd80-ac10-11ea-9ceb-941fbba7feb9.png)

**Comment by sbatten** [comment]
To Verify:
1. Use Windows/Linux with custom title bar
2. Turn off editor tabs
3. Open settings editor
4. Click triple dot menu in top right

Ensure the text is not centered but aligned-left
