### ISSUE TITLE
No easy way to revert changes made to views and panels

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#99899]
It is very easy to drag some panels out of a view and place them elsewhere. Eventually you can end up with many panels that were originally all in one view placed all over the workbench. Either this shouldn't be supported or it should be possible to easily revert back to the original, default layout.
![DontAllowPanelsFromOneViewToBeMovedToAnotherView](https://user-images.githubusercontent.com/1704059/84419699-e59dce00-ac10-11ea-984a-d9861d21eace.gif)

**Comment by gjsjohnmurray** [comment]
@stevencl I think the command `View: Reset View Locations` does that.

**Comment by misolori** [comment]
You can right-click on any view and reset the location of the individual one:

![image](https://user-images.githubusercontent.com/35271042/84422709-3e01ab00-abd2-11ea-8853-c7d915fe18ef.png)

Or as @gjsjohnmurray mentioned, you can reset all views:

![image](https://user-images.githubusercontent.com/35271042/84422803-68536880-abd2-11ea-8880-d6b5a769257d.png)

**Comment by stevencl** [comment]
Thanks, I didn't see that.
