### ISSUE TITLE
Emmet balance, updatetag failing due to invalid HTML parsing algorithm

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#99896]
- VSCode Version: 1.46.0
- OS Version: 10.15.5

Steps to Reproduce:

1. Create a `tsx` file with this content:
   ```tsx
   import React from 'react';

   // <f

   const MyComponent = () => <div className="foo">Hello, World</div>;
   ```
2. Highlight the opening tag of `div` and run any one of these commands:
   - "Emmet: Split/Join Tag"
   - "Emmet: Update Tag"
   - "Emmet: Go to Matching Pair"

Expected: the command should work
Actual: the command does nothing

If we remove the comment that contains `<f`, it works.

Does this issue occur when all extensions are disabled?: Yes

**Comment by OliverJAsh** [comment]
Updated issue to mention that this also effects "Emmet: Update Tag".

**Comment by amagupta-collab** [comment]
Interested in working on this, will be picking it up

**Comment by rzhao271** [comment]
The current parser in util.ts is trying to parse f as its own tag, and so I think it needs to be updated. This issue is similar to #73415

**Comment by rzhao271** [comment]
Verifier:

1. Set up a new .tsx file with the contents

```ts
import React from 'react';

// <f

const MyComponent = () => <div className="foo">Hello, World</div>;
```

2. Place cursor on the first `div`
3. `Emmet: Go to Matching Tag` should cause the cursor to go to the other `div` tag.
4. `Emmet: Update Tag` should bring up a prompt for the new tag name. Enter `span`. The `div` tag should have changed to a `span` tag. The `className="foo"` part and the inner contents should remain the same.
5. `Emmet: Split/Join Tag` should collapse the `<div className="foo">...</div>` into `<div className="foo"/>`, and then `<div className="foo"></div>`.
