### ISSUE TITLE
Cannot invoke an expression whose type lacks a call signature (versus optional semicolon)

### ISSUE THREAD

**Issue by bumpmann** [Microsoft/vscode#999]
I am getting the error "Cannot invoke an expression whose type lacks a call signature." on this minimalist js test code (tested with v0.10.2 and v0.10.3):

```javascript
module.exports = function(env) {
	env.deciders = []
	require('./test')(env)
}
```

the error is on the underlined code `[]
	require('./test')` (with the return, whatever LF or CRLF)

and adding the **optional** semicolon after [] makes the error disappear:

```javascript
module.exports = function(env) {
	env.deciders = [];
	require('./test')(env)
}
```

there's no test.js file since it does not matter if it exists or not.
my jsconfig.json file is set for ES6 / commonjs.

**Comment by jrieken** [comment]
A rewriting issue

**Comment by jrieken** [comment]
This is a limitation with our rewriter. Behind the scenes we transform the code to this

```
import * as _$steroids$_67_75 from './test';
declare var exports:any; declare var module:any; declare var require:any;
var _var_0 = function(env) {
    env.deciders = []
    (<typeof _$steroids$_67_75>require('./test'))(env)
}

export = _var_0;
```

**Comment by jokeyrhyme** [comment]
I have a Promise wrapper for [glob](https://www.npmjs.com/package/glob) that has the same problem:

```js
'use strict';

const glob = require('glob');

function globp (pattern, options) {
  return new Promise((resolve, reject) => {
    glob(pattern, options, (err, matches) => { // error highlight for this whole line and down
      if (err) {
        reject(err);
        return;
      }
      resolve(matches);
    }); // error highlight for this whole line and stops here
  });
}

module.exports = { glob: globp };
```

> Cannot invoke an expression whoe type lacks a call signature

**Comment by jrieken** [comment]
Closed with the adoption of Salsa (https://code.visualstudio.com/Updates#_languages-javascript).

**Comment by bumpmann** [comment]
Thanks, doesn't have the error anymore.
