### ISSUE TITLE
launching code did not work

### ISSUE THREAD

**Issue by pungggi** [Microsoft/vscode#9990]
- VSCode Version: Code - Insiders 1.4.0-insider (4656fe3ff2952e9538d81e7a7571674352e5d62f, 2016-07-29T05:08:49.671Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. open shell 
2. cd to a project folder
3. type 'code'

I needed to rename the code-insiders.cmd to code.cmd to make it work.

**Comment by wallverb** [comment]
That's by design - you need to start insider with `code-insiders` so that you can start regular version with `code` if both are installed

**Comment by pungggi** [comment]
Thats a little verbose, something like 'codei' would be easier to adopt, but its fine
