### ISSUE TITLE
Dragging and dropping a viewlet does not make it active

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#99900]
When repositioning a viewlet in the activity bar by dragging and dropping, it is not made active upon dropping. This is in contrast to dragging and dropping editor tabs.
![DraggingAndDroppingAViewletDoesNotMakeItActive](https://user-images.githubusercontent.com/1704059/84419913-31507780-ac11-11ea-9e6a-066a8ef492cb.gif)

**Comment by misolori** [comment]
Already created an issue for this #99689
