### ISSUE TITLE
Node js

### ISSUE THREAD

**Issue by RYAN-Git-clone** [microsoft/vscode#99903]
Issue Type: <b>Feature Request</b>

Hi, i used to run my Js file by just pressing ctrl + F5 and it runs automatically.
Now is like i have to confirm which runtime environment i want to use before my file can run....it wastes time! On the new Vscode version

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:44.937Z)
OS version: Windows_NT ia32 6.3.9600

**Comment by isidorn** [comment]
I guess this is beacuse we have both js-debug and node2. In the future we plan to remove node2 so this should be fixed.

**Comment by connor4312** [comment]
We plan to make js-debug the default in the next release, which will fix this!
