### ISSUE TITLE
Terminal Stopped its process on changing the folder inside editor

### ISSUE THREAD

**Issue by adisher** [microsoft/vscode#99909]
- VSCode Version: 1.45.1
- OS Version: Microsoft Windows 10

Steps to Reproduce:

1. Using built-in terminal to create a new react app
2. Meanwhile, switched to my new app folder
3. The process stopped, and a new vs code window opened.

What you expected to see:
The process will not stop and the folder will be switched.

What you actually saw:
The process did stop and folder switched with incomplete app files.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal
