### ISSUE TITLE
The extensions I installed have been deleted

### ISSUE THREAD

**Issue by JotaTorres** [microsoft/vscode#99904]
Issue Type: <b>Bug</b>

hello, my english is not so good but i will try; 
the 20 extensions that were installed for vscode simply disappeared from the 'extensions' folder, and now I have to reinstall all

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD E-350 Processor (2 x 1597)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|1.75GB (0.20GB free)|
|Process Argv|--extensions-dir=D:\Programs Files\Microsoft VS Code\extensions --user-data-dir=D:\Programs Files\Microsoft VS Code\settings|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by IllusionMH** [comment]
/needsMoreInfo

What were your last action before they disappeared? Have you updated existing VS Code installation, installed new version from website or something else?
Have you changes anything related to settings sync?

**Comment by sandy081** [comment]
Also were you using any extensions to sync your data?

**Comment by JotaTorres** [comment]
When recently updating vscode i noticed that the extensions were deleted again, i installed it again, but now i know the problem is when it updates. I do not know because

**Comment by sandy081** [comment]
Can you please provide following log before and after update

- View -> Open View… -> Log (Shared)
