### ISSUE TITLE
"Restart to Update" doesn't do anything

### ISSUE THREAD

**Issue by samuela** [microsoft/vscode#99913]
Version: 1.46.0-insider
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-09T17:34:56.826Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:

1. Try restarting VSCode via "Restart to Update"

Does this issue occur when all extensions are disabled?: unknown

Video: https://youtu.be/bdXCap0e6lY

**Comment by joaomoreno** [comment]
Can you run with `code --verbose` and show me the output when you execute that action?

**Comment by samuela** [comment]
If I can ever reproduce I'll try that out and gather as much other info as I can! Seems to be a fleeting thing. The only bit of info that I have about it was that I was attempting to "Restart to Update" from a window connected to a remote docker session running over SSH. No idea if that's related or not.

**Comment by joaomoreno** [comment]
Should not be related. Let me know if you ever can repro. I'll close this for now.
