### ISSUE TITLE
No Terminal

### ISSUE THREAD

**Issue by scifisatan** [microsoft/vscode#99910]
I'm using latest vscode in linux mint 19.3 and i can't seem to get the terminal of this code editor  working. The terminal is blank not a single letter and can't even run the python scripts.

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

You can also try setting `terminal.integrated.rendererType` to `dom` or launching via `code --disable-gpu`.

/label "needs more info" integrated-terminal

**Comment by davedub** [comment]
I have the same problem. Terminal is completely non-responsive.

Version: 1.46.0  
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z
Electron: 7.3.1  
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.7.0
![Screenshot 2020-06-15 17 11 11](https://user-images.githubusercontent.com/961729/84717643-40923680-af2b-11ea-85ce-8ee49ef31edd.png)
