### ISSUE TITLE
Disabling breakpoints while the debuggee is starting causes issues

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#99915]
- Set some BPs
- Start the Launch VS Code launch config
- While it's starting, click the "Deactivate Breakpoints" button
- I still hit the breakpoints. Toggling the "deactivate breakpoints" button doesn't help. If I remove the breakpoints, I still hit them

I've hit this a couple times but can't repro consistently

**Comment by isidorn** [comment]
Breakpoint deactivation only exists in the UI, so basicaly whenever you hit Deactivate Breakpoints we send the debug adapter that there are no breakpoints.
Code pointer where we get breakpoints which are enabled (enabled and activated) https://github.com/microsoft/vscode/blob/05c9b37e3bf086ec14d664d2c72182ff3cca784c/src/vs/workbench/contrib/debug/browser/debugService.ts#L899
That is the only code path when we send breakpoints, thus this flag should always be respected.

@connor4312 can you investigate what you are receiving on the extension side? That might be a good start.

**Comment by connor4312** [comment]
I was able to repro this by spamming enabled/disabled aggressively. I think I fixed this in the linked commit. Let me know if you see it again after this point.
