### ISSUE TITLE
集成的终端里，五笔输入法一码直接上屏了

### ISSUE THREAD

**Issue by caixw** [Microsoft/vscode#9991]
- VSCode Version: 1.3.1
- OS Version: macOS 10.11.5

Steps to Reproduce:

集成的终端里，五笔输入法一码直接上屏了。

shell: zsh
输入法：系统自带五笔

**Comment by Tyriar** [comment]
I'm assuming this is to do with the integrated terminal IME support. This was added recently to the Insiders build. https://code.visualstudio.com/insiders
