### ISSUE TITLE
Add viewType to NotebookDocument

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#99918]
Assume we have two notebook content providers, A & B.

If user opens notebook using view A, then a NotebookDocument is opened and VS Code will fire an event.

At this point, extension A & B do not know what view the document is associated with.
This gets event more complicated with the same notebook file is opened with both views. Now we have two NotebookDocuments, one for each view. However extensions do not know which one is which.

@rebornix /cc

**Comment by rebornix** [comment]
Good point, the `viewType` info is missing.

**Comment by rebornix** [comment]
Actually it's already there but we didn't put it in the typings.
