### ISSUE TITLE
React-native Intellisense

### ISSUE THREAD

**Issue by gabrielbarbosanascimento** [microsoft/vscode#99926]
Issue Type: <b>Bug</b>

After some day, update I guess, the react-native intelisense stopped working on react-native, react, and some packages, even using .js files

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (4.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none
(1 theme extensions excluded)

**Comment by mjbvz** [comment]
Please provide example code or a small example project that demonstrates the issue
