### ISSUE TITLE
Terminal on Ubuntu18.04 does not show any text

### ISSUE THREAD

**Issue by PistonY** [microsoft/vscode#99929]
Same issue with #43169 only different is my OS is Ubuntu 18.04, reinstall can't work.

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

Also try launch via `code --disable-gpu`

/label "needs more info" integrated-terminal

**Comment by PistonY** [comment]
Hi @Tyriar 
I use `code --disable-gpu ` solve my problem.
But how does it happen? Incompatible driver?

I install vscode by `snap` so I think I'm using latest version.
And I use `Driver Version: 440.59` .
This is my `settings.json`
```
{
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "terminal.integrated.inheritEnv": false,
    "python.pythonPath": "/home/piston/.conda/envs/pytorch/bin/python",
    "cmake.configureOnOpen": true,
    "terminal.integrated.shell.linux": "/bin/bash",
    "terminal.integrated.rendererType": "dom",
    "terminal.integrated.automationShell.linux": "",
    "terminal.explorerKind": "external"
}
```

**Comment by Tyriar** [comment]
@PistonY sometimes Linux distros/machines have problems rendering in Chromium.
