### ISSUE TITLE
update note remains after installed the updated package

### ISSUE THREAD

**Issue by calidion** [Microsoft/vscode#9992]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:50:12.291Z)
- OS Version: Linux x64 4.4.0-31-generic

Steps to Reproduce:

1.   download new *.deb
2.  install 
3.  check update
4. a prompt will occur again to remind me the update

**Comment by Tyriar** [comment]
You need to restart VS Code after installing the update.

**Comment by calidion** [comment]
I have installed for more than three times.
and restarted even more times.

**Comment by Tyriar** [comment]
Can you copy/paste the info in Help > About?

**Comment by calidion** [comment]
```
版本 1.3.0
提交 e724f269ded347b49fcf1657fc576399354e6703
日期 2016-07-07T16:50:12.291Z
Shell 0.37.6
呈现器 49.0.2623.75
Node 5.10.0
````

I have installed new version on another computer.
but can not install on this one.

**Comment by Tyriar** [comment]
Yeah that's definitely not the latest (1.3.1):

> Version 1.3.1
> Commit e6b4afa53e9c0f54edef1673de9001e9f0f547ae
> Date 2016-07-12T13:28:46.761Z
> Shell 0.37.6
> Renderer 49.0.2623.75
> Node 5.10.0

I recommend trying to update it through the command line using:

```
sudo dpkg -i <path>.deb
```

**Comment by calidion** [comment]
solved.
due to package problem.
redownloaded and sovled.

**Comment by Tyriar** [comment]
Great :)
