### ISSUE TITLE
Debug Console is useless

### ISSUE THREAD

**Issue by JCKodel** [microsoft/vscode#99921]
Issue Type: <b>Bug</b>

Despite the fact there is no filter (read it right: I said filter, not find!), the selection is useless.

1. You can't select more then what is displayed in the window (the acceptable behavior would the window scroll expanding the selection when the mouse is near the top or bottom border).

2. Clicking on a text, then holding shift while clicking at another text doesn't trigger selection (in almost all text editors and browsers, doing this will select everything between the first click position until the last click position, without the need to drag the selection).

3. The only way to select more lines than the current display is by using the mouse wheel, but the selection just vanishes when the window is scrolled!

4. Even when we think all text is selected, the copy command only copies what is on the view.

Recorded video: https://vimeo.com/428305369

Considering the fact this important debug tool doesn't even have a find function (such as this: https://i.stack.imgur.com/RPdCf.png), and considering there are no API's available for us to develop a decent Debug Console plugin, I urge you to refactory this important panel from scratch.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (18.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
tinypng|and|0.3.3
dart-code|Dar|3.11.0
flutter|Dar|3.11.0
vscode-google-translate|fun|1.4.5
todo-tree|Gru|0.0.176
svelte-vscode|Jam|0.9.3
pubspec-assist|jer|1.0.3
svg|joc|1.3.3
vscode-gutter-preview|kis|0.26.2
dart-import|lua|0.2.0
regionfolder|map|1.0.10
csharp|ms-|1.22.0
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
hexeditor|ms-|1.0.1
awesome-flutter-snippets|Nas|2.0.3
vscode-xml|red|0.12.0
vscode-taskexplorer|spm|1.26.3
comment-divider|sta|0.2.1
unique-window-colors|stu|1.0.51
sort-lines|Tyr|1.9.0
errorlens|use|3.1.1
vscode-icons|vsc|10.1.1

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/93750
