### ISSUE TITLE
Intellisense isn't working properly for npm modules

### ISSUE THREAD

**Issue by paboulos** [microsoft/vscode#99927]
Issue Type: <b>Bug</b>

For a typescript project installed Ramda, and ramda @types No peek definition, and no autocompletion or ctrl space details.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8350 Eight-Core Processor            (8 x 4013)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.90GB (13.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
calva-fmt|cos|0.0.38
clojure4vscode|cos|1.3.71
paredit-revived|cos|0.1.22
vscode-eslint|dba|2.1.5
react-native-react-redux|EQu|2.0.4
prettier-vscode|esb|5.0.0
flow-for-vscode|flo|1.5.0
path-autocomplete|ion|1.13.6
latex-workshop|Jam|8.10.0
docthis|joe|0.7.1
graphql-for-vscode|kum|1.15.3
vscode-sbt-scala|lig|0.2.4
dotenv|mik|1.0.1
vscode-docker|ms-|1.2.1
python|ms-|2020.5.86806
debugger-for-chrome|msj|4.12.8
material-icon-theme|PKi|4.1.0
qub-xml-vscode|qub|1.2.8
htmlescape-vscode-extension|ray|0.0.7
view-in-default-application|see|3.3.0
vscodeintellicode|Vis|1.2.8

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo does the problem also happen after you run the command to reload with all extensions disabled?

**Comment by Lypzis** [comment]
Experiencing same issue after updating.

**Comment by seoker** [comment]
Experiencing same issue here.

```
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

The issue remains after I disabled all the extensions.

**Comment by gjsjohnmurray** [comment]
Do you get this message in the status line?

![image](https://user-images.githubusercontent.com/6726799/84772342-b7363f00-afd2-11ea-81f6-f84ebdbd84b4.png)

If you wait long enough, does it disappear? If so, does Intellisense then start working?

**Comment by paboulos** [comment]
There is no message on the status line. VSC is not getting a context for the imported module. It does give recommendations but only from a general list.
 I used an import _ from "lodash"; 
Entered "_.f" and IntelliSense shows only a list of names from TypeScript Language Basic and FlowFixMe domain and nothing from lodash.
![vscIntelliSense](https://user-images.githubusercontent.com/5624815/84791886-3c185d00-afc1-11ea-92ac-103f1169f92d.png)

**Comment by mjbvz** [comment]
@paboulos Please provide steps to reproduce this (preferably a small example project that demonstrates the issue)

**Comment by paboulos** [comment]
I am following the guide on https://code.visualstudio.com/docs/editor/intellisense. It never instrospects the @types/lodash for suggestions. As I already mentioned all it does is return a cache list or prebaked TypeScript or React language types. So if I don't first write any of the available Lodash properties in that namespace, nothing shows up. I've used IntelliSense in other IDEs like Eclipse and it works with out any extra steps. Can you send me the address for a TypeScript project that I can clone with github?

**Comment by mjbvz** [comment]
You should not need to clone anything, please just share a a copy of your project  so we can investigate if is misconfigured or if there is a bug with VS Code

**Comment by paboulos** [comment]
Go to this github address https://github.com/paboulos/makesnosense

**Comment by mjbvz** [comment]
IntellISense seems to work for me:

<img width="1317" alt="Screen Shot 2020-06-25 at 12 26 23 PM" src="https://user-images.githubusercontent.com/12821956/85786434-1c7ae600-b6df-11ea-8207-0825b30012a7.png">

Can you provide steps to reproduce in that project?

**Comment by paboulos** [comment]
I just did what you did and see nothing.
![vscSens](https://user-images.githubusercontent.com/5624815/85801455-e5252d00-b710-11ea-959c-4b05ec94ee75.png)

**Comment by mjbvz** [comment]
Please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

Please share the log after you trigger intellisense so I can investigate what is going wrong

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by paboulos** [comment]
When I press ctrl+shift+p there is no option for TS Server log command. There is Developer: Show Logs...
From there: Main, Extension Host, Preferences Sync, Shared.
Is there another way to get tsserver.log?

**Comment by mjbvz** [comment]
Were you in a JS/TS file when you tried to run this command? Or have you perhaps disabled the built-in JavaScript and TypeScript extension. In the extensions view search `@builtin typescript` to check  this

**Comment by paboulos** [comment]
This was disabled i.e. the built-in JavaScript and TypeScript extension. IntelliSense is also working now.
