### ISSUE TITLE
Every time open a new VS Code application(Whether you are opening a same file or not)

### ISSUE THREAD

**Issue by KeyurRamoliya** [Microsoft/vscode#9993]
- VSCode Version:

![vscode version](https://cloud.githubusercontent.com/assets/12654542/17277698/d877710c-5766-11e6-8555-6288b5e61086.PNG)

- OS Version: Microsoft Windows [Version 10.0.10586]

Steps to Reproduce:
1. Right click on a file and open it in VS Code
2. Right click on same file or any other file and open it with VS Code
3. VS Code will fire an another VS Code application instead of showing it on already opened application

For same files it is better to show already opened file instead of opening an another one.

**Comment by bpasero** [comment]
You can control this via the `window.openFilesInNewWindow` setting.
