### ISSUE TITLE
Support for Running/Debugging Multiple Instances of VS Code Extension

### ISSUE THREAD

**Issue by kimprice** [microsoft/vscode#99936]
While developing my VS Code extension, it would be nice to be able to run multiple instances of it. Currently when I run the project, a separate window labeled [Extension Development Host] opens. If I open another window from this Extension Development Host, I would expect the new window to also be running the extension, but it is just a normal instance of VS Code as indicated by the absence of "[Extension Development Host]". 

The only workaround to be able to test multiple instances requires packaging the extension and temporarily installing it. See this related post: https://stackoverflow.com/questions/38303086/vscode-extensions-not-working-with-multiple-instances

**Comment by weinand** [comment]
@kimprice you can debug multiple instances of your extension if you duplicate the launch config and give it a different name.
