### ISSUE TITLE
CPU usage >400%. All fans up. Heating.

### ISSUE THREAD

**Issue by amrx101** [microsoft/vscode#99932]
- VSCode Version: 1.45
- OS Version: macOS Catalina 10.15
- Memory: 8 GB 2133 MHz LPDDR3
- Processor: 1.4 GHz Quad-Core Intel Core i5

Steps to Reproduce:

1. Open VS Code and let it be open for a great time.
2. Occasionally this cause the CPU usage shoot like the oil prices did in 1979. (Note: this is not deterministic as it might happen or it may not.) I will add more if I find some.

Process name that I got from `htop`

`/private/var/folders/yb/0sc33cj53m57kjd7kmqsdjd40000gn/T/AppTranslocation/4C83E0B3-FD2A-428A-BBFC-C7E084B92F0A/d/Visual Studio Code.app/Contents/Frameworks/C`

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Please update to 1.46 which was published on Wednesday. It might not solve your problem, but the team only supports the current version.

**Comment by gjsjohnmurray** [comment]
Also see https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by sandy081** [comment]
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks.

When Code is consuming lots of CPU, please run "code --status" from the command line (or "code-insiders --status" if you are using VS Code Insiders edition).

Please attach the output of this command to this issue. Thanks!

**Comment by amrx101** [comment]
Ok, So I can reproduce it. But it involves a dumb thing. Sorry if its not a bug.

- Open some project(dir) in VS code.
- And then delete the VS-Code.(I accidentally deleted the installed app, when I was doing clean up on my system).
- The CPU usage will go up like anything after that.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!
