### ISSUE TITLE
Investigate how to make persisted cell breakpoints robust

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#99943]
VS Code manages breakpoints outside from debug extensions and debug sessions. This includes breakpoints in notebook cells.

Today cell breakpoints use the cell's number to identify a breakpoint within the notebook.
When notebook cells are rearranged within a notebook (which renumbers cells), the persisted breakpoints no longer refer to the correct cell.

**Comment by weinand** [comment]
More details:

After rearranging cells in a notebook, the cell URIs are not changed as long as the notebook stays open (or is not re-read). That means that breakpoints still work. However, it does not make sense to show the URI's fragment in the UI, for example as "Cell 3" in the call stack view because the cell might no longer be cell "3".

Another problem occurs after closing the notebook and reopening it: here cell URIs are reassigned and the fragment of the cell URI changes. Since cell URIs are used in VS Code's breakpoint UI to persist them, they no longer refer to the correct cell.

I see two solutions to fix these issues:

- when generating DAP Source objects (used in Stackframes), we will stop using the URI's fragment for the display name, but use the cell's real index instead.
- when the notebook is closed, we will update the URI in the persisted breakpoints to reflect the cell's real index.

**Comment by jrieken** [comment]
Yeah, that sound reasonable. I do have a similar, but less severe, issue when moving cells that have problems - in that case error navigation is jumping back and forth between cells (see https://github.com/microsoft/vscode/issues/93938). I was thinking if that problem can be tackled by doing a rename, e.g cells change their names when being moved. However, we aren't very good with renames, e.g documents cannot change their uri and we would need to send close and open events... Still, that might be a solution that works for more use-cases.

> we will stop using the URI's fragment for the display name, but use the cell's real index instead.

For language features we aren't showing the cell index at anymore. I think the motivation was that we don't show indexes in the UI and therefore users cannot relate to them. I think that works well when showing cell source, like reference search, but is more confusing in the problems panel where we show names.

**Comment by weinand** [comment]
I still think that showing indices in the UI would be helpful, e.g. here:

![2020-06-18_12-16-48](https://user-images.githubusercontent.com/1898161/85008798-c09fe280-b15d-11ea-857e-d3800d7b8665.png)
