### ISSUE TITLE
Why is search.location no longer available?

### ISSUE THREAD

**Issue by markchagers** [microsoft/vscode#99948]
- VSCode Version: May 2020 (version 1.46)
- OS Version: Windows 10 Pro 1909

Steps to Reproduce:

1. Have search location set to in lower panel (with terminal debug etc)
2. Await latest update
3. Determine that search has now moved back to the sidebar
4. Attempt to find the setting to move it to preferred position
5. Conclude that this setting was apparently removed for some unfathomable reason

Does this issue occur when all extensions are disabled?: Yes

Update: when manually adding search.location to the settings.json file, an error is displayed that the setting is deprecated, and to use the search panel's context menu. However this context menu does not display any option to move the search to the panel location, only side bar location options.

Update 2: upon further inspection it turns out I can drag the search panel to the desired location, hence I'm closing this issue, except to note that the deprecation warning might be improved to better indicate how to change the panel's location.

**Comment by JacksonKearl** [comment]
cc @sbatten re deprecation warning & context menu UX.
