### ISSUE TITLE
Support programatic colourization 

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#9994]
I'm working on integrating Google's Dart analysis server into VS Code (it's a language server pretty similar to the one [specified here](https://github.com/Microsoft/language-server-protocol/)). One of the features it provides is colorization but as far as I can tell VS Code only supports colorization from TextMate language files.

Building a grammar that perfectly matches the Dart spec (and keeping it updated) is not a simple task. The SDK includes an analysis server providing an accurate implementation, it would be great to be able to use it!

**Comment by DanTup** [comment]
Probably this is a dupe of #1967?

**Comment by kieferrm** [comment]
Duplicate of #1967.
