### ISSUE TITLE
Invalid keybindings.json bricks editor

### ISSUE THREAD

**Issue by Hurtak** [Microsoft/vscode#9995]
- VSCode Version: 1.3.1
- OS Version: Win 10

Steps to Reproduce:

1. Put array instead of string in keybindings command field
2. Restart editor

exact key binding that caused bricking the editor
```json
{
    "key": "ctrl+up",
    "command": ["scrollLineUp", "scrollLineUp"],
    "when": "editorTextFocus"
}
```

![](http://i.imgur.com/CkDKBLq.png)

**Comment by kieferrm** [comment]
Duplicate of #9566.
