### ISSUE TITLE
autocompleted/suggestion of React Native Tools not show after auto updated vscode

### ISSUE THREAD

**Issue by zxccvvv** [microsoft/vscode#99951]
Forwarded from https://github.com/microsoft/vscode-react-native/issues/1316 since i don't know what caused the issue.

## Actual Behavior
1. No more auto completed suggestion after auto updated vscode to v1.46.0

here's an example: usually i'm type "did" to autocompleted `componentDidMount(){...}`

![image](https://user-images.githubusercontent.com/19633881/84480779-4d125700-acbf-11ea-8ea0-a2c618f6e0a0.png)

## Expected Behavior
1. bring back autocomplete

## Software versions
- React-Native VS Code extension version: v0.16.0
- VSCode version: 1.46.0
- OS platform and version: Windows 10

**Comment by sandy081** [comment]
It's good that you file issue against the extension first which is the right approach. Lets wait until we get feedback from their investigation.
