### ISSUE TITLE
Release Notes tab always reloads 

### ISSUE THREAD

**Issue by Svish** [microsoft/vscode#99953]
Issue Type: <b>Bug</b>

1. Open Release Notes tab in VS Code
2. Switch to a different tab
3. Switch back to Release Notes tab

Even though I was _just_ reading the release notes, when I switch back to it, the page is blank, the content reloads, and I'm back at the top of the page regardless of how far down the release notes I was.

This is super annoying because I like to read through the release notes and actually check out new things that seem useful. But when checking out the new thing (for example a new setting), I have to switch to a different tab. And since Release Notes keep reloading whenever I switch tabs, I constantly have to figure out "where I was" (and the release notes are often rather long...)

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.1
vscode-styled-jsx|bla|1.5.0
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.3.0
bracket-pair-colorizer-2|Coe|0.1.4
vscode-eslint|dba|2.1.5
vscode-faker|dee|1.4.1
githistory|don|0.6.5
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.8.0
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|5.0.0
php-debug|fel|1.13.0
php-pack|fel|1.0.2
vscode-text-pastry|jkj|1.2.0
vscode-peacock|joh|3.7.2
vscode-gutter-preview|kis|0.26.2
sftp|lix|1.12.9
vscode-docker|ms-|1.2.1
csharp|ms-|1.22.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vsliveshare|ms-|1.0.2302
gremlins|nho|0.20.0
hide-gitignored|npx|1.1.0
vscode-versionlens|pfl|1.0.7
material-icon-theme|PKi|4.1.0
vscode-sort-json|ric|1.18.0
vscode-sanity|san|0.0.3
code-settings-sync|Sha|3.4.3
mdx|sil|0.1.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.8
highlight-bad-chars|wen|0.0.3
vscode-import-cost|wix|2.12.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate

Workaround is to use the link at the top which takes you to the same docuemnt on the web.

**Comment by Svish** [comment]
@gjsjohnmurray Duplicate of what issue? When marking an issue as a duplicate, it's nice to actually link to that duplicate so I can upvote and/or follow that issue instead...

**Comment by Svish** [comment]
Also, there's no link at the top...?

**Comment by gjsjohnmurray** [comment]
> Duplicate of what issue?

![image](https://user-images.githubusercontent.com/6726799/84483690-9e0b5680-ac91-11ea-8880-17848e7b99f1.png)

> Also, there's no link at the top...?
![image](https://user-images.githubusercontent.com/6726799/84483405-30f7c100-ac91-11ea-9b64-d218a8e5b6b6.png)

**Comment by Svish** [comment]
Ah, less at the top than I was looking, sorry. Thanks 🙂👍
