### ISSUE TITLE
Python Extension

### ISSUE THREAD

**Issue by fahadmalik-creator** [microsoft/vscode#99952]
- VSCode Version: 1.46
- OS Version: Windows 10

Steps to Reproduce:

1. I am using Django and when I create a model and then I use it in my views to extract information from the database. The extension shows that this model has no objects member but my code works fine.
2. I just want you to handle this error. I can even share screenshots of the error if you want.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by sandy081** [comment]
Please file issue against the extension.

**Comment by fahadmalik-creator** [comment]
okay thanks...
