### ISSUE TITLE
Back Button

### ISSUE THREAD

**Issue by walterogrady** [microsoft/vscode#99964]
Issue Type: <b>Feature Request</b>

I know 'ctrl -' is the keyboard shortcut but when using a mouse/trackpad a back button on the editor would be so convenient. I have used vscode for months now and I still find myself automatically looking for a back button.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 19.5.0

**Comment by gjsjohnmurray** [comment]
Does your mouse have a back-button, or your trackpad a back-gesture?

**Comment by walterogrady** [comment]
Yes, two finger horizontal swipe on mac trackpad and single finger swipe on mouse. They trigger horizontal scroll in the editor.

**Comment by gjsjohnmurray** [comment]
Maybe https://code.visualstudio.com/updates/v1_12#_macos-mouse-swipe-to-navigate gives clues. But as I'm not a macOS user I can't verify.

#88029 may also be relevant.

**Comment by walterogrady** [comment]
Thanks for the suggestions.
The setting mentioned in the link (`workbench.editor.swipeToNavigate`) doesn't work for me and is highlighted as an unknown configuration when added to the settings. #88029 suggests that it might be a common bug.

**Comment by alexdima** [comment]
@bpasero IIRC you did something regarding the mouse swipe gestures?
