### ISSUE TITLE
Useless "Accounts" icon in activities bar

### ISSUE THREAD

**Issue by tborychowski** [microsoft/vscode#99960]
- VSCode Version: 1.46.0
- OS Version: MacOS 10.15.5

Steps to Reproduce:
1. Open VSCode

Does this issue occur when all extensions are disabled?: Yes

Since the last update I now have a useless "Accounts" icon in the Activities bar.
Here's how it looks when clicked:
<img width="378" alt="Screenshot 2020-06-12 at 10 16 14" src="https://user-images.githubusercontent.com/392513/84486773-c1d09b80-ac95-11ea-83fd-7b22d28262d7.png">

- I cannot sign-in (nor do I want to)!
- I cannot remove this icon
- I cannot do anything else with it!

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/99788#issuecomment-642548433

**Comment by gjsjohnmurray** [comment]
Also #97167 requesting the ability to hide it.

**Comment by tborychowski** [comment]
Thanks @gjsjohnmurray 
I still think this is a bug, as it shows the button for the functionality that is not yet ready/enabled.

**Comment by gjsjohnmurray** [comment]
The button becomes functional if you have certain extensions installed that integrate with external accounts, for example 'Visual Studio Codespaces'

**Comment by tborychowski** [comment]
Thanks @gjsjohnmurray for the explanation.
It makes more sense now.
In that case - it should be very easy to check if any extension needs the button, and - if not - than the button is useless, and should not be visible :-)
I'd be very happy even if there's a simple boolean setting that would allow me to hide it.

**Comment by jmarsh24** [comment]
Was this ever solved? I'm facing the same issue. I would like to either not see it or figure out how to actually log into an account.

**Comment by tborychowski** [comment]
Not yet.

**Comment by dacapoday** [comment]
The "Accounts" icon still can't be hidden in VSCode Version: 1.47.0
Damn ugly!!!!

**Comment by douglasrcjames** [comment]
Bumping this... Would be nice to link my settings and extensions to an account for my multiple machines. At the very least, only show this Account icon when it's needed? Seems obvious?

**Comment by gjsjohnmurray** [comment]
> Would be nice to link my settings and extensions to an account for my multiple machines.

Already possible as long as you're willing to use [Insiders](https://code.visualstudio.com/insiders). See [here](https://code.visualstudio.com/updates/v1_47#_settings-sync).

**Comment by douglasrcjames** [comment]
Thank you!! Exactly what I was looking for.

**Comment by Ambyjkl** [comment]
As a KDE user, I do not want to use this feature unless you support KWallet. I do not want to install gnome-keyring, If this cannot be provided, a way to disable this feature entirely and cleanly would be necessary

**Comment by RMacfarlane** [comment]
Closing this issue, as in the next release settings sync will ship which adds an entry to this menu by default, and as the icon will be hideable.
