### ISSUE TITLE
Command to scroll multiple lines (add args to keybindings.json)

### ISSUE THREAD

**Issue by Hurtak** [Microsoft/vscode#9996]
At the moment there are only keybinding commands to scroll one line up/down or one page.
Feature request: provide commands to scroll 2, 3 or more lines at a time

**Comment by kieferrm** [comment]
@Hurtak I guess you want to be able to assign keybindings to those? You are not talking about complex API commands that an extensions of yours wants to call?

**Comment by Hurtak** [comment]
Yes, I was talking about command to assign keybinding to those

**Comment by Hurtak** [comment]
Little more context:

the scroll line with ctrl+up/down is great but feels little too slow on big monitors, that's why I think it would be useful to have scroll 2 or 3 lines at a time command

**Comment by alexandrudima** [comment]
I wanted since a long time to add support for `args` in the keybindings.

**Comment by alexandrudima** [comment]
We support this since quite a while. e.g.:

```
    {
        "key": "cmd+down",
        "command": "editorScroll",
        "args": {
            "to": "down",
            "by": "line",
            "revealCursor": true,
            "value": 3
        }
    }
```
