### ISSUE TITLE
Terminal history is lost after building (C++)

### ISSUE THREAD

**Issue by maciekgajewski** [microsoft/vscode#99969]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

I use the built-in terminal to launch my C++ program.
Sometimes, after building, the terminal history is gone, and so I have to re-type al the params again.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 4.15.0-106-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (12 x 3792)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 1, 1|
|Memory (System)|22.57GB (2.42GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
togglehs|bbe|0.1.2
vscode-markdownlint|Dav|0.36.0
flatbuffers|gab|0.1.0
postgresql|JPT|0.0.2
python|ms-|2020.5.86806
cmake-tools|ms-|1.4.0
cpptools|ms-|0.28.3
code-spell-checker|str|1.9.0
unique-window-colors|stu|1.0.51
cmake|twx|0.0.17
sort-lines|Tyr|1.9.0

</details>

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/84491050-8e623100-acd6-11ea-9c1f-f4ec0bc3e599.png)

Some time the build task will spawn a new terminal. You can switch between terminals here.
