### ISSUE TITLE
Make debug console link behavior consistent with the editor

### ISSUE THREAD

**Issue by CTimmerman** [microsoft/vscode#99967]
#83620 but for the debug console.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by CTimmerman** [comment]
Out of scope? Fixing accessibility everywhere but where it's most used, i.e. the debug panel is not out of scope for VS Code!

**Comment by CTimmerman** [comment]
Link preview text on hover are inconsistent #78647
