### ISSUE TITLE
[marketplace] Black star is almost invisible on dark background

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#99965]
![Screenshot (249)](https://user-images.githubusercontent.com/9638156/84488683-3a8d2300-aca9-11ea-817b-1860aab7e1a0.png)

https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens

package.json:
```js
"galleryBanner": {
	"color": "#332020",
	"theme": "dark"
},
```

**Comment by sandy081** [comment]
Please file issue against Marketplace.

@fiveisprime FYI

**Comment by usernamehw** [comment]
@sandy081 is there a GitHub repo?

**Comment by kanlukasz** [comment]
Maybe here:
https://docs.microsoft.com/en-us/azure/devops/marketplace/faq-extensions?view=azure-devops
- General Marketplace help - Contact the Marketplace team (vsmarketplace@microsoft.com)

**Comment by fiveisprime** [comment]
This is fixed in prod now.
