### ISSUE TITLE
Duplicate files found with search tool; one prefixed in (os/ directory)

### ISSUE THREAD

**Issue by krworks** [Microsoft/vscode#9997]
- VSCode Version:1.3.1
- OS Version:Ubuntu 16.04

Steps to Reproduce:

1. Use the Ctrl+P tool to find any specific file
2. There exists duplicates of each file of the project, one being in an **os**/project_sub_folder/file.c and project_sub_folder/file.c.   If you select the 'os' prefixed location it will present the same file, but it will not respond to git checkouts or anything.  There is absolutely NO relevant os folder in this project.  There does exist one on this machine but its something in /usr/share/locale/os with absolutely no relevance to my project; it's also not a symlink.  So, the 'os' folder only exists in abstract by vscode and only serves to give duplicates for every file I have.  There seems to be no possible way to get rid of this behavior.

Just to clarify, there is no 'os' folder accessible in the project explorer list.  It only exists in search.

**Comment by krworks** [comment]
What's happening here is my project root folder name ends in 'os' but has 2 other letters before that.  If I rename '%prefix%os' with '%prefix%Zs' I see that the search results now show Zs/project_sub_folder/file.c.  I am attempting to narrow this down a bit further, because it doesn't always reproduce with the steps above.

**Comment by krworks** [comment]
Upon further investigation, this only happens with the existence of .browse.VC.db files.  If I do not use the C++ debugger extension from Microsoft, this does not happen.  It's likely being called upon to label the location of a file resource, and the plugin is doing a bad job at parsing the location for the path label.  The label is then obviously used in a literal way for file monitoring (i.e, not responding to git checkouts).

It's not due to any symlink as the entirety of the path had no symlinks it at all. It's purely a labeling issue; clicking on this would-be faulty path still brings up the .c file I'm looking for.

Once a db file is built and you reenter the application again, you will see even more duplicates in the search.  If this cannot be reproduced, I will outline exact instructions.

**Comment by kieferrm** [comment]
@krworks can you pls file an issue in the C++ extension's repo: https://github.com/Microsoft/vscppsamples/issues  Usually I would do it but given the details in your comments and your later findings it's best you consolidate. Thanks!
