### ISSUE TITLE
Files watcher problem on samba Volume

### ISSUE THREAD

**Issue by ottopic** [microsoft/vscode#99975]
Hello I have a big problems files watcher.
I'm using VS Code 1.46 on Mac OS 10.15.5 and my work's folder is on samba server.

```
/Volumes/space/libs/
/Volumes/space/commons/
/Volumes/space/Works/project1/
/Volumes/space/Works/project2/
```

I work on "space" volume but I don't need to index all folders because there are too many files.

I tried configuring Watcher Exclude and Search Exclude but indexing go on and causing traffic congestion on server.

```
"search.exclude": {
    "**/Volumes/space/commons/**": true,
    "**/Volumes/space/libs/**": true,
},
"files.watcherExclude": {
    "**/Volumes/space/commons/**": true,
    "**/Volumes/space/libs/**": true,
},
```

**Comment by gjsjohnmurray** [comment]
Previously #67934 so cc @bpasero
