### ISSUE TITLE
[marketplace] Last update time diff

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#99970]
Last updated row would be more useful if it was a difference between current date:

![Screenshot (251)](https://user-images.githubusercontent.com/9638156/84489712-c5225200-acaa-11ea-917b-52faedfe0a56.png)

Last updated: 5 hours ago
Last updated: 1 day ago
Last updated: 3 years ago

**Comment by sandy081** [comment]
This is request to Marketplace.

@fiveisprime
