### ISSUE TITLE
Allow debug controls to be dragged over the titlebar

### ISSUE THREAD

**Issue by atg** [microsoft/vscode#99977]
- VSCode Version: 1.46.0
- OS Version: macOS

Steps to Reproduce:

1. Start new debugging session
2. Attempt to drag debugging controls to titlebar (even custom titlebar)

Does this issue occur when all extensions are disabled?: Yes

This is a UI bug. A while ago VSCode added the ability to drag the debugging controls down a level so that they don't cover up tabs. However, it's not enough, they are in the way, and I still end up dragging them around all the time to uncover various parts of the UI.

I am on a laptop, probably users with external monitors don't have this problem as much.

I always wish I could just drag the debugging controls *up* into the empty titlebar instead of *down* over my code.

I know this would be difficult to support for native titlebars, but for custom titlebars I believe it's possible?

**Comment by gjsjohnmurray** [comment]
Related to #98606

@atg are you aware that this toolbar can already be docked rather than floating (see https://github.com/microsoft/vscode/issues/88067#issuecomment-570720074)?

**Comment by atg** [comment]
@gjsjohnmurray Unfortunately docking it doesn't solve the issue for laptop screens specifically. Laptop users are precisely the kinds of users who are likely to have the side bar hidden at various times. If I want to get two side-by-side editors comfortably I have to hide the side bar, I don't really want to have be in a position of having to show the side bar just to step through my code. That would be swapping one inconvenience (of having to move the debug controls around) for an even greater one.

The problem is that the area where the debug controls are currently allowed to be dragged is already extraordinarily busy. There is: the top line of code in each editor, the tab bar, and the find/replace bar.

There's this really nice free area of unused real estate in the titlebar, and since it's floating it feels so natural to just drag it up there, but it's not allowed.
