### ISSUE TITLE
Git fatal ... File is outsite repository

### ISSUE THREAD

**Issue by tdchien** [microsoft/vscode#99973]
Issue Type: <b>Bug</b>

Today I just upgrade to new version and got this problem. I also face this problem in a build before but it fixed.
This error message display when I tried stag file changes. But it's working in terminal
![image](https://user-images.githubusercontent.com/1614393/84491574-f1e86080-acce-11ea-9d94-ec77ecdf9ad1.png)

I've tried disable all extension but still got this problem. Does someone also got this problem like me ?

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz (8 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (7.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
Yes.

![image](https://user-images.githubusercontent.com/6726799/84491899-2fcc9100-ac9d-11ea-90a7-d7eb0297c340.png)

/duplicate

**Comment by tdchien** [comment]
Thank @gjsjohnmurray for reference
