### ISSUE TITLE
Dont show install formatter dialog when formatting disabled

### ISSUE THREAD

**Issue by ljhack** [microsoft/vscode#99979]
- VSCode Version: 1.46.0
- OS Version: macOS 10.15.5
- Extensions: ms-vscode.cpptools v0.28.3

The formatting inserts lots of blank in source code files.
Dont show "Install Formatter" dialog when formatting is disabled.

Steps to Reproduce:

1. "C_Cpp.formatting": "Disabled",

2. ⇧⌥F

3. this is shown even if formatting is disabled
"
There is no formatter for 'cpp' files installed.
    Install Formatter...
"

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
Assuming the when-clause on the keyboard shortcut you enter in step 2 tests `editorHasDocumentFormattingProvider` I wonder if the ms-vscode.cpptools extension isn't conforming to #70314

**Comment by jrieken** [comment]
We ignore `editorHasDocumentFormattingProvider` on purpose because users are so used to pressing it and to be guided towards formatting. 

@ljhack What motivates this issue? Are you so used to pressing the keybinding?

**Comment by ljhack** [comment]
Hi, there is formatter installed with ms-vscode.cpptools but it inserts lot of blanks into source code files. I intend to disable formatting feature. When Format document shortcut is pressed when formatting is disabled, can you please just ignore it and keep quiet and do not show this additional dialog:

"
There is no formatter for 'cpp' files installed.
    [Install Formatter...]
"

**Comment by jrieken** [comment]
I understand what you said but I wonder why you press format when it's disabled?

**Comment by gjsjohnmurray** [comment]
@ljhack I guess you could try tweaking your keybinding's where-clause to test `editorLangId != cpp` [(doc)](https://code.visualstudio.com/docs/getstarted/keybindings#_conditional-operators)

**Comment by ljhack** [comment]
@jrieken, Hi. it's to prevent someone else from trying to format the code and installing extra extensions by following the [Install Formatter...].

**Comment by jrieken** [comment]
I see but that's also a weak way to enforce something that sounds like a team policy. Having the keybinding enabled is on purpose to "sell" the formatting feature to users that expect formatting to be there.
