### ISSUE TITLE
Markdown extension is not using codicons?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#99976]
I think the icons are not aligned well:

![image](https://user-images.githubusercontent.com/900690/84494483-e20a5580-aca9-11ea-8d15-9e447cf3d7f4.png)

![image](https://user-images.githubusercontent.com/900690/84494523-f2bacb80-aca9-11ea-88a5-a9fedaaea5d8.png)

@misolori didn't we adopt codicons for all our built in extensions?

**Comment by misolori** [comment]
Good catch, I thought we had already updated these. Fixed. Worth noting that we can't update the preview icon to use codicons until #90616 is fixed.
