### ISSUE TITLE
Pinned Tabs: Add Pin Icons

### ISSUE THREAD

**Issue by Sayvai** [microsoft/vscode#99985]
**The problem:**
With the introduction of **Pinned Tabs** in [release 1.46](https://code.visualstudio.com/updates/v1_46#_pin-tabs), the current implementation makes it really difficult to distinguish / differentiate between files of the same file type, since the tab shrinks to only display the icon which represents the file type.

**The proposed solution:**
Add a pin-like icon to the tab, without shrinking the tab down to only the file type icon (i.e. maintain file type icon and display of filename, as it was prior to 1.46).

See the proposed mockup solution below using pins. (credit @JanBN for the initial [inspiration](https://github.com/microsoft/vscode/issues/98161#issuecomment-643229239))

![Screenshot 2020-06-12 at 13 10 43](https://user-images.githubusercontent.com/7581546/84501547-973f0c80-acae-11ea-964b-f6895a16832f.png)

**Comment by bpasero** [comment]
This issue has been reported already in either this or a similar form. Please check the label that was assigned to this issue to find it.
