### ISSUE TITLE
Code Suggestione

### ISSUE THREAD

**Issue by leobade** [microsoft/vscode#99989]
Issue Type: <b>Bug</b>

Hello,
i can't see the code suggestion, when i write 
It's kind of strange 

Thank you for any help 

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|3.2.0
vscode-intelephense-client|bme|1.4.1
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
es7-react-js-snippets|dsz|2.8.0
gitlens|eam|10.2.2
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|5.0.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
vscode-php-cs-fixer|fte|0.3.0
vscode-back-forward-button|gri|0.1.2
smarty|imp|0.3.0
sublime-babel-vscode|jos|0.2.10
sftp|lix|1.12.9
vscode-language-babel|mgm|0.0.27
git-graph|mhu|1.23.0
debugger-for-chrome|msj|4.12.8
csv-to-table|php|1.2.3
material-icon-theme|PKi|4.1.0
java|red|0.62.0
vscode-yaml|red|0.8.0
phpdoc-comment-vscode-plugin|rex|1.3.0
code-stats-vscode|riu|1.0.18
ActiveFileInStatusBar|Ros|1.0.3
vscode-format|rya|0.0.6
vscode-spotify|shy|3.1.0
swdc-vscode|sof|2.2.9
code-spell-checker|str|1.9.0
clockify-tracker|tob|3.0.11
material-theme|zhu|3.7.3

(9 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
May I know for which code language you are looking suggestions?

**Comment by VuongVu** [comment]
same error, using javascript

**Comment by leobade** [comment]
Practically the problem occurs with all languages

________________________________
Da: Sandeep Somavarapu <notifications@github.com>
Inviato: venerdì 12 giugno 2020 13:39
A: microsoft/vscode <vscode@noreply.github.com>
Cc: leobade <leobade@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [microsoft/vscode] Code Suggestione (#99989)


May I know for which code language you are looking suggestions?

**Comment by jrieken** [comment]
This is not actionable! Please add repro steps
