### ISSUE TITLE
dotnet quit unexpectedly

### ISSUE THREAD

**Issue by suphero** [Microsoft/vscode#9998]
- VSCode Version: 1.3.1
- OS Version: EL Capitan (10.11.6)

Steps to Reproduce:

1. I Select Language Mode C#
2. Problem Report window shows "dotnet quit unexpectedly" 
[Problem Report.txt](https://github.com/Microsoft/vscode/files/392620/Problem.Report.txt)
3. VSCode shows "Downloading and configuring .NET Core Debugger" message but nothing happens

**Comment by Tyriar** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#636
