### ISSUE TITLE
Java Test Runner Extension not working in Remote-Containers Docker VM

### ISSUE THREAD

**Issue by jimboowens** [microsoft/vscode#99987]
- VSCode Version: 1.46.0(user setup)
- OS Version: Windows 10 Pro (Version 10.0.18363 Build 18363), or Windows 1909

Steps to Reproduce:

1. Install Remote-Containers Extension
2. Follow steps to instantiate Docker Container with RedHat UBI 7.latest, maven 3.5.4, and openJDK v1.8.0_242, openJDK 64-Bit Server VM (build 25.242-b08, mixed mode)directory of the same path. 
3. import the following extensions:
```javascript
	"extensions": [
		"vscjava.vscode-java-pack",
		"ivory-lab.jenkinsfile-support",
		"mutantdino.resourcemonitor",
		"redhat.vscode-xml",
		"dotjoshjohnson.xml",
		"sohibe.java-generate-setters-getters",
		"eamodio.gitlens",
		"sylten.strawberry-theme",
		"vscjava.vscode-java-test"
	]
```
4. Install a Java project with a test file in project.src.test.java.control, with resources in the java 
5. navigate to a test file, being sure to import org.junit.Test in order to implement the @Test annotation before a non-static public function within the file class.
6. Verify the Run Test | Debug Test actions do not appear.

Does this issue occur when all extensions are disabled?: Yes, as the issue is extension-related and this by default disables the Java Test Runner Extension

**Comment by jimboowens** [comment]
Additional Remark, I tested whether this functionality worked in a non-VM instance, and verified it does in a generic Java Test file, all other things being the same.

**Comment by sandy081** [comment]
Please file the issue against the Java Test Runner extension.

**Comment by jimboowens** [comment]
I did, found a similar issue, and that one is pending a general VSCode issue filing. I tagged you, @sandy081, on that issue as well. It is issue #1014, and my refiled issue against the Java Test Runner Extension is issue #1015.
