### ISSUE TITLE
storage.json - windowsState.openedWindows not updated properly.

### ISSUE THREAD

**Issue by shlomo666** [microsoft/vscode#99980]
- VSCode Version: 1.46.0
- OS Version: Mac 10.15.4

Since the last version windowsState.openedWindows is not updated properly when opening the first window, and also when closing window. 

Steps to Reproduce:

1. Open some folder with visual studio. (single window)
2. windowsState.openedWindows is now empty (should have one item).
3. Open a second window.
4. windowsState.openedWindows size is now 2 (as should).
5. Close one of the windows.
6. windowsState.openedWindows is now either empty or still have 2 items (should have one item).
7. If 2 items - wait a while (for me something around 10 seconds).
8. windowsState.openedWindows is now empty (should have one item).

It all worked just fine until the last version. 
What went wrong? 

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Are there any published guarantees about the content of storage.json and how/when it changes during use of VS Code?

**Comment by shlomo666** [comment]
Not that I'm aware of. But it's really helpful for third party apps like I have to know what are the current opened windows.
I think it's a bug mainly because it was working properly and now it's not. But I'm not sure what are the side effects of this change, or if there are any. 
Is this an intentional change?

**Comment by bpasero** [comment]
I doubt we changed something there, but I will need more people to confirm this issue, also that it is a regression from the previous version. If someone has energy to even find the commit causing this, would be great.

**Comment by abdulmannanshekh** [comment]
jajhakallah
