### ISSUE TITLE
explorer default sort order incorrect

### ISSUE THREAD

**Issue by MarkBoote** [microsoft/vscode#99984]
Version 1.46.0 - explorer default sort order is wrong.
Previously sorted as:
a.component.html
a.component.scss
a.component.spec.ts
a.component.ts

Now sorts as:
a.component.html
a.component.scss
a.component.ts
a.component.spec.ts

The .ts & spec.ts files are the wrong way around.

**Comment by gjsjohnmurray** [comment]
See also #99955
