### ISSUE TITLE
Debug Terminal freezes after update to 1.46.0

### ISSUE THREAD

**Issue by sdomagala** [microsoft/vscode#99981]
- VSCode Version: 1.46.0
- OS Version: CentOS 7

Steps to Reproduce:

1. Use js-debug-nightly in previous releases of VS Code (worked as expected)
2. Upgrade VS Code to 1.46.0
3. Open Debug Terminal
4. Terminal freezes on 
```
Debugger listening on ws://127.0.0.1:38097/b77e6af0-2610-46bf-be16-2347d88e4e2e
For help, see: https://nodejs.org/en/docs/inspector
```

Does this issue occur when all extensions are disabled?: *Yes*

After updating to newer version, if I have js-debug-nightly installed I can see that debug menu is doubled
------
![image](https://user-images.githubusercontent.com/6019897/84498131-55af6100-acb0-11ea-925b-f15d11493c12.png)
-----

I tried removing this extension (one debug terminal button disappears from debugging menu), tried switching off option in Settings called "Use Preview" in JavaScript > Debug section. After each of those I was reloading VS Code, still nothing.

Any help regarding solving this would be great

**Comment by MNorgren** [comment]
Is it just the terminal that freezes or the entire debug session? I've noticed my application that I am debugging freezes entirely after the debug console freezes

**Comment by connor4312** [comment]
`js-debug` stable is now a built-in extension -- please disable that (you can find it by searching `@builtin js-debug`) before using js-debug-nightly. Let me know if you still run into that problem with that fixed. Thanks!

/needsMoreInfo

**Comment by sdomagala** [comment]
@connor4312 Thanks for the reply, I believe the problem is now resolved, I can't really tell what changed but three days ago it was broken - even with extensions disabled - and today everything works fine, even with nightly version enabled, maybe there was an update along the way or some env issue?
 
Anyway, thanks for your help and I'm really glad that it worked cause I am so used to it. I will monitor the behaviour but it looks like the issue is now resolved, I will close the issue

**Comment by sdomagala** [comment]
Hey @connor4312, turns out I was too fast saying that it works.
Turns out that it works only for some repositories but not for the others, which doesn't make sense to me, are there any prerequisites that need to exist in the directory for the debugger to work?

I also found out why it froze when opening terminal - my .zshrc contained one command that used node, namely NVM, and it stopped the execution when debugger was attaching. 
When I commented out NVM execution for zshrc terminal has opened but then it froze on first node command that I tried to run.

That said, I can't really nail down what might be the cause for debugger to fail in single repo - I removed .vscode dir, node_modules, dist etc., tried to run it with --disable-extensions flag but still nothing, freezes on first node command

**Comment by connor4312** [comment]
Ok, thanks for checking. Can you add the following option to your user settings?

```
  "debug.javascript.terminalOptions": {
    "trace": true,
  },
```

This will cause the the location of a log file to be printed to the Debug Console in VS Code. Then, please share that with me so I can root cause the freeze. Thanks!

**Comment by sdomagala** [comment]
@connor4312 nothing is being printed to the console when I add that, but maybe that's because nothing is actually being attached to the debugger? I mean, when I run it, VS Code doesn't switch to debugging (orange stripe on the bottom, start/stop console on top). It just hangs before it has a chance to do that

**Comment by connor4312** [comment]
Ah, okay, thanks for clarifying. That's kind of a pain to debug then.

I created a special extension build for you that will log a bunch of extra stuff directly to the terminal when you run it. Please [grab this file](https://memes.peet.io/img/fccb81a1-94de-48ed-a448-8ae4c7fe82bf.vsix) and:

 1. Search for `@id:ms-vscode.js-debug` in the marketplace view and make sure it's disabled.
 2. Hit F1 and run `Install from VSIX` -- pick the file I gave you
 3. It'll want you to reload the window most likely. Do so.
 4. Then, open the debug terminal and just run `node`

That will dump a bunch of extra info to your terminal. Please share that info here 🙂

**Comment by sdomagala** [comment]
Here is the ouput, terminal freezes on those lines

```
❯ node
Debugger listening on ws://127.0.0.1:37229/13f70459-d15d-41ab-b0da-7c67023992fa
For help, see: https://nodejs.org/en/docs/inspector
ℹ  info      [runtime.welcome] js-debug-nightly v2020.6.1610 started: {"os":"linux x64","nodeVersion":"v13.14.0","adapterVersion":"2020.6.1610"}
Debugger attached.
Welcome to Node.js v13.14.0.
Type ".help" for more information.
> ℹ  info      [runtime.welcome] js-debug-nightly v2020.6.1610 started: {"os":"linux x64","nodeVersion":"v13.14.0","adapterVersion":"2020.6.1610"}
ℹ  info      [runtime.launch] Bootloader imported: {"env":{"inspectorIpc":"/tmp/node-cdp.8289-2.sock","deferredMode":false,"waitForDebugger":"","execPath":"/home/s.domagala/.nvm/versions/node/v13.14.0/bin/node","onlyEntrypoint":false,"fileCallback":"/tmp/node-debug-callback-4fea49f8177b2973"},"args":["/home/s.domagala/.nvm/versions/node/v13.14.0/bin/node"]}
ℹ  info      [runtime] Set debug mode: {"mode":0}
ℹ  info      [runtime] Spawned, waiting for inspector: {"info":{"ipcAddress":"/tmp/node-cdp.8289-2.sock","pid":"10408","telemetry":{"cwd":"/home/s.domagala/projects/directory/my-project","processId":10408,"nodeVersion":"v13.14.0","architecture":"x64"},"inspectorURL":"ws://127.0.0.1:37229/13f70459-d15d-41ab-b0da-7c67023992fa","waitForDebugger":true,"ppid":""}}
```

**Comment by connor4312** [comment]
Sorry for the delay. Since you said this happened using nightly and then failed when updating to 1.46.0 (where we have a stable variant built-in) I think you might be hitting a conflict like Christoff was running into. Please follow the three steps I gave here https://github.com/microsoft/vscode/issues/98778#issuecomment-649784816 and let me know if that works for you.

Thanks!

**Comment by sdomagala** [comment]
Hello @connor4312,
I am unable to replicate it now, this issue used to pop up randomly, mostly in JS repos, TS worked fine.
I am going to close it now since I am not able to move this issue forward, hopefully it was fixed in some other issue.

Thanks for you help!
