### ISSUE TITLE
Error processing "variables": not connected to runtime

### ISSUE THREAD

**Issue by diyijing** [microsoft/vscode#99990]
Issue Type: <b>Bug</b>

connect ETIMEDOUT
app.ts:69
[node-debug2] Error processing "variables": not connected to runtime
Error processing "variables": Error: not connected to runtime
    at Object.errP (~/.vscode-server/extensions/ms-vscode.node-debug2-1.42.4/node_modules/vscode-chrome-debug-core/out/src/utils.js:262:13)

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 19.5.0
Remote OS version: Linux x64 4.14.81.bm.14-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 6, 7|
|Memory (System)|16.00GB (1.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: pro|
|OS|Linux x64 4.14.81.bm.14-amd64|
|CPUs|Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz (8 x 2394)|
|Memory (System)|15.42GB (2.47GB free)|
|VM|0%|
</details><details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Handlebars|and|0.4.1
thrift|cdu|0.0.1
vscode-wxml|cod|0.1.9
language-postcss|cpy|1.1.0
riot-tag|cri|0.1.7
javascript-ejs-support|Dig|1.3.1
eslint-disable-snippets|drK|1.2.0
es7-react-js-snippets|dsz|2.8.0
Angular-BeastCode|Mik|8.1.2
dotenv|mik|1.0.1
vscode-language-pack-zh-hans|MS-|1.46.3
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.8
postcss|ric|2.0.0
vscode-snippets|the|0.1.3
highlight-matching-tag|vin|0.9.9
vscode-icons|vsc|10.1.1
vscode-todo-highlight|way|1.0.4
prettier-for-handlebars-vscode|alo|2.0.1
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.0
vscode-css-modules|cli|0.2.3
gitignore|cod|0.6.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
xml|Dot|2.5.0
vscode-generate-getter-setter|DSK|0.5.0
vscode-wasm|dts|1.3.1
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.0.0
code-runner|for|0.10.0
shell-format|fox|7.0.1
Go|gol|0.14.4
beautify|Hoo|1.5.0
search-node-modules|jas|1.3.0
vscode-styled-components|jpo|0.0.29
graphql-for-vscode|kum|1.15.3
node-module-intellisense|lei|1.5.0
sftp|lix|1.12.9
HTMLHint|mka|0.8.0
vscode-scss|mrm|0.9.0
vscode-language-pack-zh-hans|MS-|1.46.3
python|ms-|2020.5.86806
cpptools|ms-|0.28.3
node-debug2|ms-|1.42.4
vetur|oct|0.24.0
remote-vscode|raf|1.1.0
java|red|0.62.0
vscode-yaml|red|0.8.0
code-settings-sync|Sha|3.4.3
vscode-leetcode|she|0.16.2
code-spell-checker|str|1.9.0
vscodeintellicode|Vis|1.2.8
vscode-java-debug|vsc|0.26.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.0.0
html-css-class-completion|Zig|1.19.0
vscode-open-in-github|ziy|1.3.6
vscode-proto3|zxh|0.4.2

</details>

**Comment by diyijing** [comment]
### My launch.json
```
{
            "name": "debug",
            "type": "node",
            "runtimeVersion": "10.21.0",
            "request": "launch",
			"args": ["${workspaceRoot}/src/app.ts"],
            "runtimeArgs": ["-r", "ts-node/register", "--inspect"],
            "cwd": "${workspaceRoot}",
            "internalConsoleOptions": "openOnSessionStart",
            // "runtimeExecutable": "nodemon",
            "restart": true,
            "env": {
                "TARGET": "node",
                "NODE_ENV": "development",
                "SERVER_ENV": "development",
                "TS_NODE_PROJECT": "${workspaceRoot}/tsconfig.json"
            }
        }
```
### log
> ~/.nvm/versions/node/v10.21.0/bin/node -r ts-node/register --inspect --inspect-brk=18211 path-to-project/src/app.ts 
Debugger listening on ws://127.0.0.1:18211/5927e226-a383-48bf-b658-19d56b16ef02
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

### curl http://localhost:18211/json
```json
[
  {
    "description": "node.js instance",
    "devtoolsFrontendUrl": "chrome-devtools://devtools/bundled/js_app.html?experiments=true&v8only=true&ws=localhost:18211/5927e226-a383-48bf-b658-19d56b16ef02",
    "devtoolsFrontendUrlCompat": "chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=localhost:18211/5927e226-a383-48bf-b658-19d56b16ef02",
    "faviconUrl": "https://nodejs.org/static/favicon.ico",
    "id": "5927e226-a383-48bf-b658-19d56b16ef02",
    "title": "/path-to-project/src/app.ts",
    "type": "node",
    "url": "file:///path-to-project/src/app.ts",
    "webSocketDebuggerUrl": "ws://localhost:18211/5927e226-a383-48bf-b658-19d56b16ef02"
  }
]
```

**Comment by roblourens** [comment]
Could you try this with our new debugger implementation? https://code.visualstudio.com/updates/v1_43#_new-javascript-debugger

**Comment by diyijing** [comment]
> Could you try this with our new debugger implementation? https://code.visualstudio.com/updates/v1_43#_new-javascript-debugger

This problem has disappeared after mac reboot suddenly 🤣
