### ISSUE TITLE
git

### ISSUE THREAD

**Issue by sonukrr** [microsoft/vscode#99992]
Issue Type: <b>Bug</b>

unable to stage or unstage files due after May 2020 release.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:44.937Z)
OS version: Windows_NT ia32 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (7.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
ng-template|Ang|0.901.11
python|ms-|2020.5.86806
azure-account|ms-|0.8.11
LiveServer|rit|5.6.1
vscode-scss-formatter|sib|2.0.1
sass-indented|syl|1.8.5
usql-vscode-ext|usq|0.2.15

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Maybe #99881 but you haven't given us enough detail of your problem.
