### ISSUE TITLE
Preserve settings and extensions data from user through an account

### ISSUE THREAD

**Issue by gach87** [Microsoft/vscode#9999]
Visual Studio Code could let the user login to a service to preserve extensions and settings through different systems and sessions like Google, or another Single sign on systems

**Comment by rozzzly** [comment]
I recommend checking out the [code-settings-sync](https://github.com/shanalikhan/code-settings-sync) extension it lets you sync all your configs to github (via a gist). I've used it for several months now, it's perfect; keybindings, editor settings, themes, extensions, snippets, and probably something else I can't remember. The best part is it saves it all to a git so you can always access it, revert, share, etc.

**Comment by kieferrm** [comment]
Related to #2743.

**Comment by pcgeek86** [comment]
Related to #10114

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/2743
