### ISSUE TITLE
Notebook shows up at the wrong time after changing editor setting

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#99999]
- Open a notebook in a tab in the background
- Open settings.json
- Toggle the `editor.scrollBeyondLastLine` setting
- The notebook shows up on top even though its editor tab is not visible

![Jun-12-2020 09-11-41](https://user-images.githubusercontent.com/323878/84511851-c2b0ff80-ac8c-11ea-984a-0f4d774d8237.gif)

**Comment by roblourens** [comment]
Peng says editor config change triggers a layout

**Comment by rebornix** [comment]
https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L124 which tries to layout the list view after the setting is changed and we should only update the widget's visibility when it's visible https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L724-L726
