### ISSUE TITLE
Markdown cell doesn't always update when editing in split notebook editor

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#99995]
- Open a notebook with a markdown cell
- Split it
- Edit a markdown cell on one side, see that it's not updated on the other side in preview mode
- If it works, repeat a couple times

Seems that the right events are being fired, but `getText` in the viewmodel returns the old text. If I put the preview cell into edit mode, the editor has the right contents. 

Any idea what's going on @rebornix? I touched this area recently but I can still repro after reverting my changes.

Pushed a1feacf5c445f040d42419ddbe07b29bbe5bc165 because I removed that and I think I shouldn't have.

**Comment by roblourens** [comment]
Now I've really broken it

![Jun-12-2020 08-38-31](https://user-images.githubusercontent.com/323878/84508593-24229f80-ac88-11ea-8bc4-7d8b8866823d.gif)

**Comment by rebornix** [comment]
I was not able to reproduce this issue with https://github.com/microsoft/vscode/pull/100545 .
